TRUST: src/Kernel/Geometrie/Analyse_Angle.h File Reference
src/Kernel/Geometrie/Analyse_Angle.h File Reference
#include <Interprete.h>
Classes
class Analyse_Angle
Functions
void histogramme_angle (const Domaine &, Sortie &, int nb_histo=18)
Function Documentation
void histogramme_angle (const Domaine & , Sortie & , int nb_histo = 18)
Definition at line 113 of file Analyse_Angle.cpp.
References Cerr, IntTab::dimension(), DoubleTab::dimension(), Objet_U::dimension, Process::exit(), finl, largest_angle(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Process::mp_sum(), Zone::nb_elem(), Objet_U::que_suis_je(), test(), Zone::type_elem(), type_elem(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by Zone_VF::discretiser(), and Analyse_Angle::interpreter().
{
  out<<finl<<"Histogram of the largest angle of each element found into the mesh "<<dom.le_nom()<<" :" << finl;
  Motcle type_elem(dom.zone(0).type_elem().valeur().que_suis_je());
  if (((type_elem!="triangle")&& (type_elem!="tetraedre")) || ((type_elem=="triangle") && (Domaine::dimension==3)))
    {
      out<<"Not available for "<<type_elem<<" in dimension "<<Domaine::dimension<<finl;
      return;
    }
  ArrOfInt histo(nb_histo+1);
  int nb_elem=dom.zone(0).nb_elem();
  const DoubleTab& som=dom.les_sommets();
  const IntTab& les_elems=dom.zone(0).les_elems();
  int dim_space=som.dimension(1);
  int nb_som_elem=les_elems.dimension(1);
  DoubleTab coords(nb_som_elem,3);
  for (int elem=0; elem<nb_elem; elem++)
    {
      for (int s=0; s<nb_som_elem; s++)
        {
          int sommet=les_elems(elem,s);
          for (int dir=0; dir<dim_space; dir++)
            coords(s,dir)=som(sommet,dir);
        }
      double teta=largest_angle(coords);
      int test=(int)(teta/180*nb_histo);
      histo(test)++;
      if (test==nb_histo)
        Cerr << "Error, the mesh cell " << elem << " is flat. Fix your mesh." << finl;
    }
  if (histo(nb_histo)>0)
    Process::exit();
  int nb_elem_tot=(int)Process::mp_sum(nb_elem);
  if (nb_elem_tot>0)
    {
      double obtuse_cells_proportion=0;
      for (int h=0; h<nb_histo; h++)
        {
          histo(h)=Process::mp_sum(histo(h));
// Pas d'angles en dessous de 60 forcement
          if (180/nb_histo*h>=60)
            {
              obtuse_cells_proportion=histo(h)*100./nb_elem_tot;
              int angle=180/nb_histo*h;
              out <<"Between "<<angle<<" degrees and " << 180/nb_histo*(h+1)<<" degrees : "<<histo(h)<<" elements ( "<<obtuse_cells_proportion<< " %)"<<finl;
            }
        }
// Criteria used on the last bin (170-180 degrees)
      if (obtuse_cells_proportion>20)
        {
          Cerr << finl;
          Cerr << "Warning:" << finl;
          Cerr << "Your mesh has too much obtuse cells for a TRUST calculation." << finl;
          Cerr << "Check the mesh requirements." << finl;
// Process::exit();
        }
    }
  out << finl;
}