TRUST: src/Kernel/Utilitaires/arch.cpp File Reference
arch.cpp File Reference
#include <arch.h>
#include <unistd.h>
#include <Process.h>
#include <iostream>
Functions
void desalloue_pwd ()
char * pwd ()
ARCH_H
Variables
static char * buf =0
Function Documentation
desalloue_pwd()
void desalloue_pwd ()
Definition at line 48 of file arch.cpp.
{
// si on a alloue le buf on le detruit ...
#if defined(_CSH_) || defined(linux) || defined(cygwin) || defined(MICROSOFT)
  if (buf)
    delete [] buf;
  buf=0;
#endif
}
References buf.
Referenced by main_TRUST().
pwd()
char * pwd ()
ARCH_H
Definition at line 57 of file arch.cpp.
{
#if defined(_CSH_) || defined(linux) || defined(cygwin) || defined(MICROSOFT) || defined(__APPLE__)
  if (buf==0)
    buf=new char[801];
#endif
#ifdef MICROSOFT
  int longueur=800;
  _getcwd(buf, longueur);
#else
#if defined(_CSH_) || defined(linux) || defined(cygwin) || defined(__APPLE__)
  int longueur=800;
  if (getcwd(buf, longueur)==NULL)
    {
      cerr << "getcwd returns an error code." << endl;
      Process::exit();
    };
#else
  buf=getenv("PWD");
#endif
#endif
  return buf;
}
References buf, and Process::exit().
Referenced by init_petsc(), main_TRUST(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), and EcrFicPartage::ouvrir().
Variable Documentation
buf
char* buf =0 static
Definition at line 45 of file arch.cpp.
Referenced by desalloue_pwd(), Schema_Comm::echange_messages(), Lec_Diffuse_base::get(), and pwd().