TRUST: src/Kernel/Utilitaires/arch.h File Reference
arch.h File Reference
#include <generique.h>
Macros
#define IOS_OPEN_MODE std::_Ios_Openmode
Gestion des dependances machines pour l'appel a FORTRAN
La macro F77DECLARE(TOTO) permet de declarer une routine FORTRAN.
La macro F77NAME(TOTO) permet d'appeler une routine FORTRAN.
Exemple :
toto.f :
SUBROUTINE TOTO(DOUBLE X)
X=2.0*X
RETURN
END
appel_toto.cpp
void F77DECLARE(TOTO) (const double*);
void main()
{
double x;
F77NAME(TOTO)(x);
}.
#define IOS_FORMAT std::_Ios_Fmtflags
#define F77DECLARE(x) F77NAME(x)
#define F77NAME(x) name2(x,_)
Typedefs
typedef int entier
typedef int integer
typedef int True_int
Functions
char * pwd ()
ARCH_H
Macro Definition Documentation
F77DECLARE
#define F77DECLARE (x) F77NAME(x)
Definition at line 64 of file arch.h.
F77NAME
#define F77NAME (x) name2(x,_)
Definition at line 68 of file arch.h.
IOS_FORMAT
#define IOS_FORMAT std::_Ios_Fmtflags
Definition at line 45 of file arch.h.
IOS_OPEN_MODE
#define IOS_OPEN_MODE std::_Ios_Openmode
Gestion des dependances machines pour l'appel a FORTRAN
La macro F77DECLARE(TOTO) permet de declarer une routine FORTRAN.
La macro F77NAME(TOTO) permet d'appeler une routine FORTRAN.
Exemple :
toto.f :
SUBROUTINE TOTO(DOUBLE X)
X=2.0*X
RETURN
END
appel_toto.cpp
void F77DECLARE(TOTO) (const double*);
void main()
{
double x;
F77NAME(TOTO)(x);
}.
Definition at line 44 of file arch.h.
Typedef Documentation
entier
typedef int entier
Definition at line 78 of file arch.h.
integer
typedef int integer
Definition at line 79 of file arch.h.
True_int
typedef int True_int
Definition at line 80 of file arch.h.
Function Documentation
pwd()
char * pwd ()
ARCH_H
Definition at line 57 of file arch.cpp.
{
#if defined(_CSH_) || defined(linux) || defined(cygwin) || defined(MICROSOFT) || defined(__APPLE__)
  if (buf==0)
    buf=new char[801];
#endif
#ifdef MICROSOFT
  int longueur=800;
  _getcwd(buf, longueur);
#else
#if defined(_CSH_) || defined(linux) || defined(cygwin) || defined(__APPLE__)
  int longueur=800;
  if (getcwd(buf, longueur)==NULL)
    {
      cerr << "getcwd returns an error code." << endl;
      Process::exit();
    };
#else
  buf=getenv("PWD");
#endif
#endif
  return buf;
}
References buf, and Process::exit().
Referenced by init_petsc(), main_TRUST(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), and EcrFicPartage::ouvrir().