TRUST: src/Kernel/Math/Array_tools.h File Reference
Array_tools.h File Reference
#include <TRUSTTab.h>
Functions
void array_trier_retirer_doublons (ArrOfInt &array)
Methode outil pour retirer les doublons dans un tableau.
void array_calculer_intersection (ArrOfInt &liste1, const ArrOfInt &liste2)
Methode outil pour calculer l'intersection entre deux listes d'entiers.
void array_retirer_elements (ArrOfInt &sorted_array, const ArrOfInt &sorted_elements_list)
Methode outil pour calculer la difference entre deux listes d'entiers triees.
int array_bsearch (const ArrOfInt &tab, int valeur)
Methode outil pour chercher une valeur dans un tableau trie.
int tri_lexicographique_tableau (IntTab &tab)
Tri lexicographique d'un tableau.
int tri_lexicographique_tableau_indirect (const IntTab &tab, ArrOfInt &index)
Tri indirect (on trie le tableau index qui contient des numeros de lignes dans tab)
void tableau_trier_retirer_doublons (IntTab &tab)
Methode outil pour retirer les doublons dans un tableau.
void calculer_renum_sans_doublons (const IntTab &tab, ArrOfInt &renum, ArrOfInt &items_a_garder)
Methode outil pour trouver les doublons (permet de retirer les doublons
sans changer l'ordre des elements)
template<typename _TYPE_ >
void array_smart_allocate (TRUSTArray< _TYPE_ > &array, const int n)
Set the smart_resize flag, preallocates memory for the given size, and resize to zero.
template<typename _TYPE_ >
void append_array_to_array (TRUSTArray< _TYPE_ > &dest, const TRUSTArray< _TYPE_ > &src)
Function Documentation
append_array_to_array()
template<typename _TYPE_ > void append_array_to_array (TRUSTArray< _TYPE_ > & dest, const TRUSTArray< _TYPE_ > & src) inline
Definition at line 56 of file Array_tools.h.
{
  const int n1 = dest.size_array(), n2 = src.size_array();
  dest.resize_array(n1+n2);
  dest.inject_array(src, n2 /* nb elem */, n1 /* dest index */, 0 /* src index */);
}
References TRUSTArray< _TYPE_ >::inject_array(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
array_bsearch()
int array_bsearch (const ArrOfInt & tab, int valeur)
Methode outil pour chercher une valeur dans un tableau trie.
Methode outil pour chercher une valeur dans un tableau trie.
< j = fin de tableau + 1 (important)
< prendre la valeur milieu et pas milieu - 1
< prendre la valeur milieu + 1 et pas milieu
Definition at line 146 of file Array_tools.cpp.
{
// attention tout est important !
  int i = 0;
  int j = tab.size_array(); //!< j = fin de tableau + 1 (important)
  while (j > i)
    {
// Le tableau doit etre trie
      assert(j == tab.size_array() || tab[i] <= tab[j]);
      const int milieu = (i + j) / 2;
      const int val = tab[milieu];
      if (val > valeur)
        j = milieu; //!< prendre la valeur milieu et pas milieu - 1
      else if (val < valeur)
        i = milieu + 1; //!< prendre la valeur milieu + 1 et pas milieu
      else
        return milieu;
    }
// Si on arrive ici, c'est que i==j, donc
// - soit j == fin de tableau + 1 et on n'a pas trouve la valeur
// - soit tab[j] a ete teste et n'est pas egale a valeur
// Dans les deux cas, valeur n'est pas dans le tableau
  return -1;
}
References TRUSTArray< _TYPE_ >::size_array(), and valeur().
array_calculer_intersection()
void array_calculer_intersection (ArrOfInt & liste1, const ArrOfInt & liste2)
Methode outil pour calculer l'intersection entre deux listes d'entiers.
Methode outil pour calculer l'intersection entre deux listes d'entiers.
< Pointeur en lecture dans liste1
< Pointeur en lecture dans liste2
< Pointeur en ecriture
< Bout de liste, on a fini
< On garde cette valeur
Definition at line 69 of file Array_tools.cpp.
{
  const int sz1 = liste1.size_array();
  const int sz2 = liste2.size_array();
  int i; //!< Pointeur en lecture dans liste1
  int j = 0; //!< Pointeur en lecture dans liste2
  int k = 0; //!< Pointeur en ecriture
  for (i = 0; i < sz1; i++)
    {
// On verifie que les listes sont triees dans l'ordre croissant
      assert((i >= sz1-1) || (liste1[i] < liste1[i+1]));
      assert((j >= sz2-1) || (liste2[j] < liste2[j+1]));
      const int valeur_i = liste1[i];
// Avancer dans liste2 jusqu'a trouver ou depasser liste1[i]
      while (j < sz2 && liste2[j] < valeur_i)
        j++;
      if (j == sz2)
        break; //!< Bout de liste, on a fini
      if (liste2[j] == valeur_i)
        {
          liste1[k] = valeur_i;
          k++; //!< On garde cette valeur
        }
    }
  liste1.resize_array(k);
}
References TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Partitionneur_base::corriger_sommets_bord(), and Refine_Mesh::find_edge().
array_retirer_elements()
void array_retirer_elements (ArrOfInt & sorted_array, const ArrOfInt & sorted_elements_list)
Methode outil pour calculer la difference entre deux listes d'entiers triees.
Methode outil pour calculer la difference entre deux listes d'entiers triees.
< Index dans sorted_array (en lecture)
< Index dans sorted_array (la ou on ecrit)
< Index dans sorted_elements
< Tableau trie ?
Definition at line 102 of file Array_tools.cpp.
{
  int i_read;      //!< Index dans sorted_array (en lecture)
  int i_write = 0; //!< Index dans sorted_array (la ou on ecrit)
  int j = 0;       //!< Index dans sorted_elements
  const int n = sorted_array.size_array();
  const int m = sorted_elements_list.size_array();
  if (m == 0)
    return;
  int j_value = sorted_elements_list[j];
  for (i_read = 0; i_read < n; i_read++)
    {
// Tableau trie ?
      assert(i_read == 0 || sorted_array[i_read] > sorted_array[i_read-1]);
      const int i_value = sorted_array[i_read];
// On avance dans la liste sorted_elements jusqu'a trouver ou depasser
// l'element i_value
      while ((j_value < i_value) && (j < m))
        {
          j++;
          if (j == m)
            break;
          assert(sorted_elements_list[j] > j_value); //!< Tableau trie ?
          j_value = sorted_elements_list[j];
        }
      if (j == m || j_value != i_value)
        {
// i_value ne figure pas dans le tableau sorted_elements, on le garde
          sorted_array[i_write] = i_value;
          i_write++;
        }
    }
  sorted_array.resize_array(i_write);
}
References TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
array_smart_allocate()
template<typename _TYPE_ > void array_smart_allocate (TRUSTArray< _TYPE_ > & array, const int n) inline
Set the smart_resize flag, preallocates memory for the given size, and resize to zero.
< get memory for the requested size
< and set actual size to zero
Definition at line 48 of file Array_tools.h.
{
  array.set_smart_resize(1);
  array.resize_array(n, Array_base::NOCOPY_NOINIT); //!< get memory for the requested size
  array.resize_array(0); //!< and set actual size to zero
}
References Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::set_smart_resize().
array_trier_retirer_doublons()
void array_trier_retirer_doublons (ArrOfInt & array)
Methode outil pour retirer les doublons dans un tableau.
Methode outil pour retirer les doublons dans un tableau.
Definition at line 50 of file Array_tools.cpp.
{
// IntVect n'est pas traite correctement car on ne
// fait pas un resize() mais un resize_array().
  assert(typeid(array) != typeid(IntVect));
  const int size = array.size_array();
  if (size == 0)
    return;
// Tri dans l'ordre croissant
  array.ordonne_array();
// Retire les doublons
  const int sz = array_retirer_doublons(array);
  array.resize_array(sz);
}
References array_retirer_doublons(), TRUSTArray< _TYPE_ >::ordonne_array(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
calculer_renum_sans_doublons()
void calculer_renum_sans_doublons (const IntTab & tab, ArrOfInt & renum, ArrOfInt & renum_inverse)
Methode outil pour trouver les doublons (permet de retirer les doublons
sans changer l'ordre des elements)
Methode outil pour trouver les doublons (permet de retirer les doublons
sans changer l'ordre des elements)
< compteur de lignes dans le tableau reduit
< indice dans le tableau initial de la derniere ligne ajoutee dans le tableau reduit
< pas de reallocation
Definition at line 447 of file Array_tools.cpp.
{
// MODIF ELI LAUCOIN 31/01/2012 :
// Je re-ecris completement cette fonction
// index permet de parcourir le tableau tab dans l'ordre
  ArrOfInt index;
  tri_lexicographique_tableau_indirect(tab, index);
  const int n = index.size_array();
// on redimensionne renum et renum_index
  renum.resize_array(n, Array_base::NOCOPY_NOINIT);
  renum_inverse.resize_array(n, Array_base::NOCOPY_NOINIT);
  int count  = -1; //!< compteur de lignes dans le tableau reduit
  int latest = -1; //!< indice dans le tableau initial de la derniere ligne ajoutee dans le tableau reduit
  for (int i=0; i<n; ++i)
    {
// on parcourt tab dans l'ordre croissant donne par index.
// si la ligne courante est differente de la derniere ligne ajoutee dans le tableau reduit,
// on incremente count et on met a jour latest.
      if ( ( latest < 0 ) || ( !(same_line(tab,index[i],index[latest]))) )
        {
          ++count;
          latest=i;
        }
// on indique dans renum ou se trouve la ligne courante dans le tableau reduit
      renum[index[i]]      = count;
// on ajoute la derniere ligne traitee au tableau reduit
      renum_inverse[count] = index[latest];
    }
// on redimensionne renum_inverse a la taille du tableau reduit
  renum_inverse.set_smart_resize(1); //!< pas de reallocation
  renum_inverse.resize_array(count+1);
// FIN MODIF ELI LAUCOIN 31/01/2012
}
References Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::resize_array(), same_line(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), and tri_lexicographique_tableau_indirect().
Referenced by Refine_Mesh::build_edges().
tableau_trier_retirer_doublons()
void tableau_trier_retirer_doublons (IntTab & tab)
Methode outil pour retirer les doublons dans un tableau.
Methode outil pour retirer les doublons dans un tableau.
< Taille du tableau apres suppression
< Derniere ligne retenue
Definition at line 380 of file Array_tools.cpp.
{
  const int nb_lignes = tab.dimension(0);
  if (nb_lignes == 0)
    return;
  const int nb_colonnes = tri_lexicographique_tableau(tab);
// Retire les doublons
  if (nb_colonnes == 1)
    {
      const int new_size = array_retirer_doublons(tab);
      resize_tab_lines(tab, new_size);
    }
  else if (nb_colonnes == 2)
    {
      int j = 1; //!< Taille du tableau apres suppression
      int last_x = tab(0, 0);
      int last_y = tab(0, 1);
      for (int i = 1; i < nb_lignes; i++)
        {
          const int x = tab(i, 0);
          const int y = tab(i, 1);
          if (x != last_x || y != last_y)
            {
              tab(j, 0) = last_x = x;
              tab(j, 1) = last_y = y;
              j++;
            }
        }
      resize_tab_lines(tab, j);
    }
  else
    {
      int j = 0; //!< Derniere ligne retenue
      fct_qsort_nbcolonnes = nb_colonnes;
      for (int i = 1; i < nb_lignes; i++)
        {
// Si la ligne i est differente de la ligne j, on la conserve:
          if (!fct_qsort_tableau_n(&tab(i, 0), &tab(j, 0)))
            {
              j++;
              for (int k = 0; k < nb_colonnes; k++)
                tab(j, k) = tab(i, k);
            }
        }
      resize_tab_lines(tab, j+1);
    }
}
References array_retirer_doublons(), TRUSTTab< _TYPE_ >::dimension(), fct_qsort_nbcolonnes, fct_qsort_tableau_n(), resize_tab_lines(), and tri_lexicographique_tableau().
Referenced by Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), SETS::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Domain_Graph::construire_graph_from_segment(), Op_EF_base::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Matrix_tools::extend_matrix_stencil(), and Matrice_Base::set_stencil().
tri_lexicographique_tableau()
int tri_lexicographique_tableau (IntTab & tab)
Tri lexicographique d'un tableau.
Tri lexicographique d'un tableau.
Definition at line 228 of file Array_tools.cpp.
{
// On verifie que le tableau n'est pas un tableau distribue:
  assert(!tab.get_md_vector().non_nul());
  const int nb_lignes = tab.dimension(0);
  const int nb_colonnes = tab.line_size();
  if (nb_lignes != 0)
    {
      if (nb_colonnes == 1)
        tab.ordonne_array();
      else if (nb_colonnes == 2)
        qsort(tab.addr(), nb_lignes, nb_colonnes * sizeof(int), fct_qsort_tableau_2);
      else
        {
          fct_qsort_nbcolonnes = nb_colonnes;
          qsort(tab.addr(), nb_lignes, nb_colonnes * sizeof(int), fct_qsort_tableau_n);
        }
    }
  return nb_colonnes;
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), fct_qsort_nbcolonnes, fct_qsort_tableau_2(), fct_qsort_tableau_n(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), and TRUSTArray< _TYPE_ >::ordonne_array().
Referenced by ExtrudeParoi::extrude(), and tableau_trier_retirer_doublons().
tri_lexicographique_tableau_indirect()
int tri_lexicographique_tableau_indirect (const IntTab & tab, ArrOfInt & index)
Tri indirect (on trie le tableau index qui contient des numeros de lignes dans tab)
Tri indirect (on trie le tableau index qui contient des numeros de lignes dans tab)
Definition at line 333 of file Array_tools.cpp.
{
// On verifie que le tableau n'est pas un tableau distribue:
  assert(!tab.get_md_vector().non_nul());
  const int dimtab = tab.dimension_tot(0);
  if (index.size_array() == 0 && dimtab > 0)
    {
      index.resize_array(dimtab, Array_base::NOCOPY_NOINIT);
      for (int i = 0; i < dimtab; i++)
        index[i] = i;
    }
  const int nb_lignes = index.size_array();
  const int nb_colonnes = tab.line_size();
  if (nb_lignes != 0)
    {
      if (fct_qsort_tab_ptr)
        {
          Cerr << "Internal error in tri_lexicographique_tableau_indirect !" << finl;
          Process::exit();
// Aie ! on essaye de faire du multithread ??? acces concurrent au pointeur
        }
      fct_qsort_tab_ptr = &tab;
      if (nb_colonnes == 1)
        qsort(index.addr(), index.size_array(), sizeof(int), fct_qsort_tableau_1_indirect);
      else if (nb_colonnes == 2)
        qsort(index.addr(), index.size_array(), sizeof(int), fct_qsort_tableau_2_indirect);
      else
        {
          fct_qsort_nbcolonnes = nb_colonnes;
          qsort(index.addr(), index.size_array(), sizeof(int), fct_qsort_tableau_n_indirect);
        }
      fct_qsort_tab_ptr = 0;
    }
  return nb_colonnes;
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), fct_qsort_nbcolonnes, fct_qsort_tab_ptr, fct_qsort_tableau_1_indirect(), fct_qsort_tableau_2_indirect(), fct_qsort_tableau_n_indirect(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by build_edges(), calculer_renum_sans_doublons(), Matrice_Morse::get_stencil_and_coefficients(), and Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients().