TRUST: src/Kernel/Math/Array_tools.cpp File Reference
src/Kernel/Math/Array_tools.cpp File Reference
#include <Array_tools.h>
#include <IntTab.h>
#include <ArrOfDouble.h>
Functions
int array_retirer_doublons (ArrOfInt &array)
retire les doublons du tableau array
(suppose que le tableau est trie dans l'ordre croissant)
On deplace les elements conserves pour qu'ils soient contigus
au debut du tableau.
ATTENTION: on ne resize pas le tableau, utiliser la valeur
de retour pour le faire ensuite!
(au cas ou on veuille appliquer cette fonction a un IntTab,
il faut faire resize() et non resize_array())
Valeur de retour : nombre d'elements conserves dans le tableau
void array_trier_retirer_doublons (ArrOfInt &array)
Trie le tableau array dans l'ordre croissant
et retire les doublons.
void array_calculer_intersection (ArrOfInt &liste1, const ArrOfInt &liste2)
calcule l'intersection entre les deux listes d'entiers
liste1 et liste2. Le resultat est mis dans liste1.
Les deux listes doivent etre triees et sans doublons. liste1 est
triee en sortie.
void array_retirer_elements (ArrOfInt &sorted_array, const ArrOfInt &sorted_elements_list)
Retire de "sorted_array" les elements qui figurent dans "sorted_elements".
Les deux tableaux doivent etre initialement ordonnes dans l'ordre croissant.
Exemple:
En entree sorted_array=[1,4,9,10,12,18], sorted_elements=[3,5,9,10,18,25]
En sortie sorted_array=[1,4,12].
int array_bsearch (const ArrOfInt &tab, int valeur)
cherche la "valeur" dans le tableau tab par recherche binaire
Le tableau tab doit etre trie dans l'ordre croissant
Si elle n'est pas trouvee, renvoie -1 (y compris si tab est vide),
sinon, renvoie un index i tel que tab[i] == valeur<br>(si la valeur figure plusieurs fois dans le tableau, on ne renvoie<br>pas forcement la premiere occurence).
True_int fct_qsort_tableau_2 (const void *ptr1, const void *ptr2)
True_int fct_qsort_tableau_n (const void *ptr1, const void *ptr2)
int tri_lexicographique_tableau (IntTab &tab)
tri lexicographique du tableau tab (par ordre croissant
de la premiere colonne, si premiere colonne identique, ordre croissant
de la deuxieme, etc).
Le tableau ne doit pas etre un tableau distribue.
Valeur de retour: nombre de colonnes du tableau (produit des tab.dimension(i) pour i>0)
True_int fct_qsort_tableau_1_indirect (const void *ptr1, const void *ptr2)
True_int fct_qsort_tableau_2_indirect (const void *ptr1, const void *ptr2)
True_int fct_qsort_tableau_n_indirect (const void *ptr1, const void *ptr2)
int tri_lexicographique_tableau_indirect (const IntTab &tab, ArrOfInt &index)
Idem que tri_lexicographique_tableau mais on trie le tableau index qui
contient les indices de lignes du tableau tab tel que tab(index[i], *) soit
croissant quant i augmente. Tri de tous les indices de index...
Si le tableau index est de taille nulle, on en cree un de taille tab.dimension_tot(0)
Sinon on suppose qu'il contient deja des indices de lignes dans tab.
Valeur de retour: nombre de colonnes du tableau (produit des tab.dimension(i) pour i>0)
void resize_tab_lines (IntTab &tab, const int n)
void tableau_trier_retirer_doublons (IntTab &tab)
Trie le tableau tab dans l'ordre lexicographique
et retire les doublons (attention [1,2] n'est pas egal a [2,1])
static int same_line (const IntVect &v, int i, int j)
void calculer_renum_sans_doublons (const IntTab &tab, ArrOfInt &renum, ArrOfInt &renum_inverse)
cherche par un tri lexicographique les lignes identiques de "tab"
et initialise les tailles et contenus de renum et renum_inverse.
renum est de taille tab.dimension_tot(0).
renum[i] contiendra l'indice de la ligne i dans le tableau reduit trie (contenant les lignes uniques)
renum_inverse contient, pour chaque ligne du tableau reduit trie, le plus petit indice de la ligne
correspondante dans tab.
on peut construire le tableau reduit trie en extayant les lignes tab(renum_inverse[i], ...)
void array_smart_allocate (ArrOfInt &array, const int n)
Set the smart_resize flag, preallocates memory for the given size, and resize to zero.
void array_smart_allocate (ArrOfDouble &array, const int n)
void append_array_to_array (ArrOfInt &dest, const ArrOfInt &src)
Increase size of "dest" array and copy "src" at the end of "dest".
void append_array_to_array (ArrOfDouble &dest, const ArrOfDouble &src)
Increase size of "dest" array and copy "src" at the end of "dest".
Variables
static int fct_qsort_nbcolonnes
static const IntVect * fct_qsort_tab_ptr = 0
Function Documentation
void append_array_to_array (ArrOfInt & dest, const ArrOfInt & src)
Increase size of "dest" array and copy "src" at the end of "dest".
Definition at line 515 of file Array_tools.cpp.
References ArrOfInt::inject_array(), ArrOfInt::resize_array(), and ArrOfInt::size_array().
{
  const int n1 = dest.size_array();
  const int n2 = src.size_array();
  dest.resize_array(n1+n2);
  dest.inject_array(src, n2 /* nb elem */, n1 /* dest index */, 0 /* src index */);
}
void append_array_to_array (ArrOfDouble & dest, const ArrOfDouble & src)
Increase size of "dest" array and copy "src" at the end of "dest".
Definition at line 523 of file Array_tools.cpp.
References ArrOfDouble::inject_array(), ArrOfDouble::resize_array(), and ArrOfDouble::size_array().
{
  const int n1 = dest.size_array();
  const int n2 = src.size_array();
  dest.resize_array(n1+n2);
  dest.inject_array(src, n2 /* nb elem */, n1 /* dest index */, 0 /* src index */);
}
int array_bsearch (const ArrOfInt & tab, int valeur)
cherche la "valeur" dans le tableau tab par recherche binaire
Le tableau tab doit etre trie dans l'ordre croissant
Si elle n'est pas trouvee, renvoie -1 (y compris si tab est vide),
sinon, renvoie un index i tel que tab[i] == valeur<br>(si la valeur figure plusieurs fois dans le tableau, on ne renvoie<br>pas forcement la premiere occurence).
Methode outil pour chercher une valeur dans un tableau trie.
< j = fin de tableau + 1 (important)
< prendre la valeur milieu et pas milieu - 1
< prendre la valeur milieu + 1 et pas milieu
Definition at line 155 of file Array_tools.cpp.
References ArrOfInt::size_array().
{
// attention tout est important !
  int i = 0;
  int j = tab.size_array(); //!< j = fin de tableau + 1 (important)
  while (j > i)
    {
// Le tableau doit etre trie
      assert(j == tab.size_array() || tab[i] <= tab[j]);
      const int milieu = (i + j) / 2;
      const int val = tab[milieu];
      if (val > valeur)
        j = milieu; //!< prendre la valeur milieu et pas milieu - 1
      else if (val < valeur)
        i = milieu + 1; //!< prendre la valeur milieu + 1 et pas milieu
      else
        return milieu;
    }
// Si on arrive ici, c'est que i==j, donc
// - soit j == fin de tableau + 1 et on n'a pas trouve la valeur
// - soit tab[j] a ete teste et n'est pas egale a valeur
// Dans les deux cas, valeur n'est pas dans le tableau
  return -1;
}
void array_calculer_intersection (ArrOfInt & liste1, const ArrOfInt & liste2)
calcule l'intersection entre les deux listes d'entiers
liste1 et liste2. Le resultat est mis dans liste1.
Les deux listes doivent etre triees et sans doublons. liste1 est
triee en sortie.
Methode outil pour calculer l'intersection entre deux listes d'entiers.
< Pointeur en lecture dans liste1
< Pointeur en lecture dans liste2
< Pointeur en ecriture
< Bout de liste, on a fini
< On garde cette valeur
Definition at line 78 of file Array_tools.cpp.
References ArrOfInt::resize_array(), and ArrOfInt::size_array().
Referenced by Partitionneur_base::corriger_sommets_bord(), and Refine_Mesh::find_edge().
{
  const int sz1 = liste1.size_array();
  const int sz2 = liste2.size_array();
  int i; //!< Pointeur en lecture dans liste1
  int j = 0; //!< Pointeur en lecture dans liste2
  int k = 0; //!< Pointeur en ecriture
  for (i = 0; i < sz1; i++)
    {
// On verifie que les listes sont triees dans l'ordre croissant
      assert((i >= sz1-1) || (liste1[i] < liste1[i+1]));
      assert((j >= sz2-1) || (liste2[j] < liste2[j+1]));
      const int valeur_i = liste1[i];
// Avancer dans liste2 jusqu'a trouver ou depasser liste1[i]
      while (j < sz2 && liste2[j] < valeur_i)
        j++;
      if (j == sz2)
        break; //!< Bout de liste, on a fini
      if (liste2[j] == valeur_i)
        {
          liste1[k] = valeur_i;
          k++; //!< On garde cette valeur
        }
    }
  liste1.resize_array(k);
}
int array_retirer_doublons (ArrOfInt & array)
retire les doublons du tableau array
(suppose que le tableau est trie dans l'ordre croissant)
On deplace les elements conserves pour qu'ils soient contigus
au debut du tableau.
ATTENTION: on ne resize pas le tableau, utiliser la valeur
de retour pour le faire ensuite!
(au cas ou on veuille appliquer cette fonction a un IntTab,
il faut faire resize() et non resize_array())
Valeur de retour : nombre d'elements conserves dans le tableau
Definition at line 36 of file Array_tools.cpp.
References ArrOfInt::size_array().
Referenced by array_trier_retirer_doublons(), and tableau_trier_retirer_doublons().
{
  const int size = array.size_array();
  if (size == 0)
    return 0;
// Retire les doublons
  int new_size = 1;
  int last_value = array[0];
  for (int i = 1; i < size; i++)
    {
// Le tableau doit etre trie !
      assert(array[i] >= last_value);
      if (array[i] != last_value)
        {
          array[new_size] = last_value = array[i];
          new_size++;
        }
    }
  return new_size;
}
void array_retirer_elements (ArrOfInt & sorted_array, const ArrOfInt & sorted_elements_list)
Retire de "sorted_array" les elements qui figurent dans "sorted_elements".
Les deux tableaux doivent etre initialement ordonnes dans l'ordre croissant.
Exemple:
En entree sorted_array=[1,4,9,10,12,18], sorted_elements=[3,5,9,10,18,25]
En sortie sorted_array=[1,4,12].
Methode outil pour calculer la difference entre deux listes d'entiers triees.
< Index dans sorted_array (en lecture)
< Index dans sorted_array (la ou on ecrit)
< Index dans sorted_elements
< Tableau trie ?
Definition at line 111 of file Array_tools.cpp.
References ArrOfInt::resize_array(), and ArrOfInt::size_array().
{
  int i_read;      //!< Index dans sorted_array (en lecture)
  int i_write = 0; //!< Index dans sorted_array (la ou on ecrit)
  int j = 0;       //!< Index dans sorted_elements
  const int n = sorted_array.size_array();
  const int m = sorted_elements_list.size_array();
  if (m == 0)
    return;
  int j_value = sorted_elements_list[j];
  for (i_read = 0; i_read < n; i_read++)
    {
// Tableau trie ?
      assert(i_read == 0 || sorted_array[i_read] > sorted_array[i_read-1]);
      const int i_value = sorted_array[i_read];
// On avance dans la liste sorted_elements jusqu'a trouver ou depasser
// l'element i_value
      while ((j_value < i_value) && (j < m))
        {
          j++;
          if (j == m)
            break;
          assert(sorted_elements_list[j] > j_value); //!< Tableau trie ?
          j_value = sorted_elements_list[j];
        }
      if (j == m || j_value != i_value)
        {
// i_value ne figure pas dans le tableau sorted_elements, on le garde
          sorted_array[i_write] = i_value;
          i_write++;
        }
    }
  sorted_array.resize_array(i_write);
}
void array_smart_allocate (ArrOfDouble & array, const int n)
Definition at line 506 of file Array_tools.cpp.
References Array_base::NOCOPY_NOINIT, ArrOfDouble::resize_array(), and ArrOfDouble::set_smart_resize().
{
  array.set_smart_resize(1);
// get memory for the requested size
  array.resize_array(n, Array_base::NOCOPY_NOINIT);
// and set actual size to zero
  array.resize_array(0);
}
void array_smart_allocate (ArrOfInt & array, const int n)
Set the smart_resize flag, preallocates memory for the given size, and resize to zero.
Definition at line 497 of file Array_tools.cpp.
References Array_base::NOCOPY_NOINIT, ArrOfInt::resize_array(), and ArrOfInt::set_smart_resize().
{
  array.set_smart_resize(1);
// get memory for the requested size
  array.resize_array(n, Array_base::NOCOPY_NOINIT);
// and set actual size to zero
  array.resize_array(0);
}
void array_trier_retirer_doublons (ArrOfInt & array)
Trie le tableau array dans l'ordre croissant
et retire les doublons.
Methode outil pour retirer les doublons dans un tableau.
Definition at line 59 of file Array_tools.cpp.
References array_retirer_doublons(), ArrOfInt::ordonne_array(), ArrOfInt::resize_array(), ArrOfInt::size_array(), sub_type, and sz.
{
// IntVect n'est pas traite correctement car on ne
// fait pas un resize() mais un resize_array().
  assert(!sub_type(IntVect, array));
  const int size = array.size_array();
  if (size == 0)
    return;
// Tri dans l'ordre croissant
  array.ordonne_array();
// Retire les doublons
  const int sz = array_retirer_doublons(array);
  array.resize_array(sz);
}
void calculer_renum_sans_doublons (const IntTab & tab, ArrOfInt & renum, ArrOfInt & renum_inverse)
cherche par un tri lexicographique les lignes identiques de "tab"
et initialise les tailles et contenus de renum et renum_inverse.
renum est de taille tab.dimension_tot(0).
renum[i] contiendra l'indice de la ligne i dans le tableau reduit trie (contenant les lignes uniques)
renum_inverse contient, pour chaque ligne du tableau reduit trie, le plus petit indice de la ligne
correspondante dans tab.
on peut construire le tableau reduit trie en extayant les lignes tab(renum_inverse[i], ...)
Methode outil pour trouver les doublons (permet de retirer les doublons
sans changer l'ordre des elements)
< compteur de lignes dans le tableau reduit
< indice dans le tableau initial de la derniere ligne ajoutee dans le tableau reduit
< pas de reallocation
Definition at line 456 of file Array_tools.cpp.
References Array_base::NOCOPY_NOINIT, ArrOfInt::resize_array(), same_line(), ArrOfInt::set_smart_resize(), ArrOfInt::size_array(), and tri_lexicographique_tableau_indirect().
Referenced by Refine_Mesh::build_edges().
{
// MODIF ELI LAUCOIN 31/01/2012 :
// Je re-ecris completement cette fonction
// index permet de parcourir le tableau tab dans l'ordre
  ArrOfInt index;
  tri_lexicographique_tableau_indirect(tab, index);
  const int n = index.size_array();
// on redimensionne renum et renum_index
  renum.resize_array(n, Array_base::NOCOPY_NOINIT);
  renum_inverse.resize_array(n, Array_base::NOCOPY_NOINIT);
  int count  = -1; //!< compteur de lignes dans le tableau reduit
  int latest = -1; //!< indice dans le tableau initial de la derniere ligne ajoutee dans le tableau reduit
  for (int i=0; i<n; ++i)
    {
// on parcourt tab dans l'ordre croissant donne par index.
// si la ligne courante est differente de la derniere ligne ajoutee dans le tableau reduit,
// on incremente count et on met a jour latest.
      if ( ( latest < 0 ) || ( !(same_line(tab,index[i],index[latest]))) )
        {
          ++count;
          latest=i;
        }
// on indique dans renum ou se trouve la ligne courante dans le tableau reduit
      renum[index[i]]      = count;
// on ajoute la derniere ligne traitee au tableau reduit
      renum_inverse[count] = index[latest];
    }
// on redimensionne renum_inverse a la taille du tableau reduit
  renum_inverse.set_smart_resize(1); //!< pas de reallocation
  renum_inverse.resize_array(count+1);
// FIN MODIF ELI LAUCOIN 31/01/2012
}
True_int fct_qsort_tableau_1_indirect (const void * ptr1, const void * ptr2)
Definition at line 263 of file Array_tools.cpp.
References fct_qsort_tab_ptr.
Referenced by tri_lexicographique_tableau_indirect().
{
  const int t1 = *((const int *) ptr1);
  const int t2 = *((const int *) ptr2);
  const IntVect& tab = *fct_qsort_tab_ptr;
  int delta = tab[t1] - tab[t2];
#ifdef INT_is_64_
  if (delta==0)
    return 0;
  if (delta<0)
    return -1;
  return 1;
#else
  return delta;
#endif
}
True_int fct_qsort_tableau_2 (const void * ptr1, const void * ptr2)
Definition at line 182 of file Array_tools.cpp.
Referenced by tri_lexicographique_tableau().
{
  const int *t1 = (const int *) ptr1;
  const int *t2 = (const int *) ptr2;
  int delta = t1[0] - t2[0];
  int delta2 = t1[1] - t2[1];
#ifdef INT_is_64_
  delta= delta ? delta : delta2;
  if (delta==0)
    return 0;
  if (delta<0)
    return -1;
  return 1;
#else
  return delta ? delta : delta2;
#endif
}
True_int fct_qsort_tableau_2_indirect (const void * ptr1, const void * ptr2)
Definition at line 280 of file Array_tools.cpp.
References fct_qsort_tab_ptr.
Referenced by tri_lexicographique_tableau_indirect().
{
  const int t1 = *((const int *) ptr1) * 2;
  const int t2 = *((const int *) ptr2) * 2;
  const IntVect& tab = *fct_qsort_tab_ptr;
  int delta = tab[t1] - tab[t2];
  int delta2 = tab[t1+1] - tab[t2+1];
#ifdef INT_is_64_
  delta= delta ? delta : delta2;
  if (delta==0)
    return 0;
  if (delta<0)
    return -1;
  return 1;
#else
  return delta ? delta : delta2;
#endif
}
True_int fct_qsort_tableau_n (const void * ptr1, const void * ptr2)
Definition at line 200 of file Array_tools.cpp.
References fct_qsort_nbcolonnes.
Referenced by tableau_trier_retirer_doublons(), and tri_lexicographique_tableau().
{
  const int *t1 = (const int *) ptr1;
  const int *t2 = (const int *) ptr2;
  const int n = fct_qsort_nbcolonnes - 1;
  int i;
  for (i = 0; i < n; i++)
    {
      int delta = t1[i] - t2[i];
      if (delta)
        {
#ifdef INT_is_64_
          if (delta<0)
            return -1;
          return 1;
#else
          return delta;
#endif
        }
    }
#ifdef INT_is_64_
  int delta= t1[i] - t2[i];
  if (delta==0)
    return 0;
  if (delta<0)
    return -1;
  return 1;
#else
  return t1[i] - t2[i];
#endif
}
True_int fct_qsort_tableau_n_indirect (const void * ptr1, const void * ptr2)
Definition at line 300 of file Array_tools.cpp.
References fct_qsort_nbcolonnes, and fct_qsort_tab_ptr.
Referenced by tri_lexicographique_tableau_indirect().
{
  const int nc = fct_qsort_nbcolonnes;
  int t1 = *((const int *) ptr1) * nc;
  int t2 = *((const int *) ptr2) * nc;
  const IntVect& tab = *fct_qsort_tab_ptr;
  const int n = nc - 1;
  int i;
  for (i = 0; i < n; i++)
    {
      int delta = tab[t1++] - tab[t2++];
      if (delta)
        {
#ifdef INT_is_64_
          if (delta<0)
            return -1;
          return 1;
#else
          return delta;
#endif
        }
    }
#ifdef INT_is_64_
  int delta=tab[t1] - tab[t2];
  if (delta==0)
    return 0;
  if (delta<0)
    return -1;
  return 1;
#else
  return tab[t1] - tab[t2];
#endif
}
void resize_tab_lines (IntTab & tab, const int n)
Definition at line 382 of file Array_tools.cpp.
References IntTab::resize_dim0().
Referenced by tableau_trier_retirer_doublons().
{
  tab.resize_dim0(n);
}
static int same_line (const IntVect & v, int i, int j) [inline, static]
Definition at line 439 of file Array_tools.cpp.
References IntVect::line_size().
Referenced by calculer_renum_sans_doublons().
{
  const int ls = v.line_size();
  int k;
  for (k = 0; k < ls; k++)
    if (v[i*ls+k] != v[j*ls+k])
      break;
  return k == ls;
}
void tableau_trier_retirer_doublons (IntTab & tab)
Trie le tableau tab dans l'ordre lexicographique
et retire les doublons (attention [1,2] n'est pas egal a [2,1])
Methode outil pour retirer les doublons dans un tableau.
< Taille du tableau apres suppression
< Derniere ligne retenue
Definition at line 389 of file Array_tools.cpp.
References array_retirer_doublons(), IntTab::dimension(), fct_qsort_nbcolonnes, fct_qsort_tableau_n(), resize_tab_lines(), and tri_lexicographique_tableau().
Referenced by Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_EF::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Domain_Graph::construire_graph_from_segment(), Op_Grad_VDF_Face::dimensionner(), Masse_PolyMAC_Face::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Op_Grad_PolyMAC_Face::dimensionner(), Op_Div_PolyMAC::dimensionner(), Op_Diff_PolyMAC_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner(), Op_EF_base::dimensionner(), Op_Div_CoviMAC::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Op_PolyMAC_Elem::dimensionner_bloc_vitesse(), QDM_Multiphase::dimensionner_blocs(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Matrix_tools::extend_matrix_stencil(), Zone_PolyMAC::init_m2solv(), and Matrice_Base::set_stencil().
{
  const int nb_lignes = tab.dimension(0);
  if (nb_lignes == 0)
    return;
  const int nb_colonnes = tri_lexicographique_tableau(tab);
// Retire les doublons
  if (nb_colonnes == 1)
    {
      const int new_size = array_retirer_doublons(tab);
      resize_tab_lines(tab, new_size);
    }
  else if (nb_colonnes == 2)
    {
      int j = 1; //!< Taille du tableau apres suppression
      int last_x = tab(0, 0);
      int last_y = tab(0, 1);
      for (int i = 1; i < nb_lignes; i++)
        {
          const int x = tab(i, 0);
          const int y = tab(i, 1);
          if (x != last_x || y != last_y)
            {
              tab(j, 0) = last_x = x;
              tab(j, 1) = last_y = y;
              j++;
            }
        }
      resize_tab_lines(tab, j);
    }
  else
    {
      int j = 0; //!< Derniere ligne retenue
      fct_qsort_nbcolonnes = nb_colonnes;
      for (int i = 1; i < nb_lignes; i++)
        {
// Si la ligne i est differente de la ligne j, on la conserve:
          if (!fct_qsort_tableau_n(&tab(i, 0), &tab(j, 0)))
            {
              j++;
              for (int k = 0; k < nb_colonnes; k++)
                tab(j, k) = tab(i, k);
            }
        }
      resize_tab_lines(tab, j+1);
    }
}
int tri_lexicographique_tableau (IntTab & tab)
tri lexicographique du tableau tab (par ordre croissant
de la premiere colonne, si premiere colonne identique, ordre croissant
de la deuxieme, etc).
Le tableau ne doit pas etre un tableau distribue.
Valeur de retour: nombre de colonnes du tableau (produit des tab.dimension(i) pour i>0)
Tri lexicographique d'un tableau.
Definition at line 237 of file Array_tools.cpp.
References ArrOfInt::addr(), IntTab::dimension(), fct_qsort_nbcolonnes, fct_qsort_tableau_2(), fct_qsort_tableau_n(), IntVect::get_md_vector(), IntVect::line_size(), MD_Vector::non_nul(), and ArrOfInt::ordonne_array().
Referenced by ExtrudeParoi::extrude(), and tableau_trier_retirer_doublons().
{
// On verifie que le tableau n'est pas un tableau distribue:
  assert(!tab.get_md_vector().non_nul());
  const int nb_lignes = tab.dimension(0);
  const int nb_colonnes = tab.line_size();
  if (nb_lignes != 0)
    {
      if (nb_colonnes == 1)
        tab.ordonne_array();
      else if (nb_colonnes == 2)
        qsort(tab.addr(), nb_lignes, nb_colonnes * sizeof(int), fct_qsort_tableau_2);
      else
        {
          fct_qsort_nbcolonnes = nb_colonnes;
          qsort(tab.addr(), nb_lignes, nb_colonnes * sizeof(int), fct_qsort_tableau_n);
        }
    }
  return nb_colonnes;
}
int tri_lexicographique_tableau_indirect (const IntTab & tab, ArrOfInt & index)
Idem que tri_lexicographique_tableau mais on trie le tableau index qui
contient les indices de lignes du tableau tab tel que tab(index[i], *) soit
croissant quant i augmente. Tri de tous les indices de index...
Si le tableau index est de taille nulle, on en cree un de taille tab.dimension_tot(0)
Sinon on suppose qu'il contient deja des indices de lignes dans tab.
Valeur de retour: nombre de colonnes du tableau (produit des tab.dimension(i) pour i>0)
Tri indirect (on trie le tableau index qui contient des numeros de lignes dans tab)
Definition at line 342 of file Array_tools.cpp.
References ArrOfInt::addr(), Cerr, IntTab::dimension_tot(), Process::exit(), fct_qsort_nbcolonnes, fct_qsort_tableau_1_indirect(), fct_qsort_tableau_2_indirect(), fct_qsort_tableau_n_indirect(), finl, IntVect::get_md_vector(), IntVect::line_size(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), ArrOfInt::resize_array(), and ArrOfInt::size_array().
Referenced by build_edges(), calculer_renum_sans_doublons(), Matrice_Morse::get_stencil_and_coefficients(), and Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients().
{
// On verifie que le tableau n'est pas un tableau distribue:
  assert(!tab.get_md_vector().non_nul());
  const int dimtab = tab.dimension_tot(0);
  if (index.size_array() == 0 && dimtab > 0)
    {
      index.resize_array(dimtab, Array_base::NOCOPY_NOINIT);
      for (int i = 0; i < dimtab; i++)
        index[i] = i;
    }
  const int nb_lignes = index.size_array();
  const int nb_colonnes = tab.line_size();
  if (nb_lignes != 0)
    {
      if (fct_qsort_tab_ptr)
        {
          Cerr << "Internal error in tri_lexicographique_tableau_indirect !" << finl;
          Process::exit();
// Aie ! on essaye de faire du multithread ??? acces concurrent au pointeur
        }
      fct_qsort_tab_ptr = &tab;
      if (nb_colonnes == 1)
        qsort(index.addr(), index.size_array(), sizeof(int), fct_qsort_tableau_1_indirect);
      else if (nb_colonnes == 2)
        qsort(index.addr(), index.size_array(), sizeof(int), fct_qsort_tableau_2_indirect);
      else
        {
          fct_qsort_nbcolonnes = nb_colonnes;
          qsort(index.addr(), index.size_array(), sizeof(int), fct_qsort_tableau_n_indirect);
        }
      fct_qsort_tab_ptr = 0;
    }
  return nb_colonnes;
}
Variable Documentation
int fct_qsort_nbcolonnes [static]
Definition at line 180 of file Array_tools.cpp.
Referenced by fct_qsort_tableau_n(), fct_qsort_tableau_n_indirect(), tableau_trier_retirer_doublons(), tri_lexicographique_tableau(), and tri_lexicographique_tableau_indirect().
const IntVect* fct_qsort_tab_ptr = 0 [static]
Definition at line 261 of file Array_tools.cpp.
Referenced by fct_qsort_tableau_1_indirect(), fct_qsort_tableau_2_indirect(), and fct_qsort_tableau_n_indirect().