TRUST: src/Kernel/Math/ArrOfDouble.cpp File Reference
src/Kernel/Math/ArrOfDouble.cpp File Reference
#include <ArrOfDouble.h>
#include <math.h>
#include <Memoire.h>
#include <Vect_ArrOfDouble.h>
#include <Ref_ArrOfDouble.h>
#include <climits>
Classes
class VDoubledata
VDoubledata alloue une zone de memoire de la taille specifiee au
constructeur, et libere la zone de memoire a la destruction.
La memoire peut etre allouee sur le tas (avec new) ou par le
mecanisme Memoire::add_trav_double.
"ref_count" compte le nombre de pointeurs qui font reference a "this".
(permet au dernier utilisateur de l'objet de le detruire), voir
ArrOfDouble.
Functions
int operator== (const Ref_ArrOfDouble &r1, const Ref_ArrOfDouble &r2)
int operator== (const ArrOfDouble &v, const ArrOfDouble &a)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille
et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
int imin_array (const ArrOfDouble &dx)
Retourne l'indice du min ou -1 si le tableau est vide.
int imax_array (const ArrOfDouble &dx)
Retourne l'indice du max ou -1 si le tableau est vide.
double min_array (const ArrOfDouble &dx)
Retourne la valeur minimale.
double max_array (const ArrOfDouble &dx)
Retourne la valeur maximale.
static double scalar_abs (double x)
double max_abs_array (const ArrOfDouble &dx)
Retourne le max des abs(i)
double min_abs_array (const ArrOfDouble &dx)
Retourne le min des abs(i)
static True_int fonction_compare_arrofdouble_ordonner (const void *data1, const void *data2)
Fonction de comparaison utilisee pour trier le tableau
dans ArrOfDouble::trier(). Voir man qsort.
double dotproduct_array (const ArrOfDouble &dx, const ArrOfDouble &dy)
Produit scalaire de deux "array".
(dotproduct_array remplace operator* car le nom indique clairement
que l'on fait un produit scalaire non distribue)
double norme_array (const ArrOfDouble &dx)
Calcul de la norme du vecteur dx (fonction blas DNRM2,
soit racine carree(somme des dx[i]*dx[i]).
Variables
const Type_info * ArrOfDoublebases [1] = { &(Array_base ::info_obj)}
const Type_info * Vect_ArrOfDoublebases [1] = { &(vect_impl ::info_obj)}
const Type_info * Ref_ArrOfDoublebases [1] = { &(Ref_ ::info_obj)}
Function Documentation
double dotproduct_array (const ArrOfDouble & dx, const ArrOfDouble & dy)
Produit scalaire de deux "array".
(dotproduct_array remplace operator* car le nom indique clairement
que l'on fait un produit scalaire non distribue)
Returns:
double
Signification: produit scalaire
Contraintes:
Definition at line 1277 of file ArrOfDouble.cpp.
References ArrOfDouble::addr(), F77NAME, and ArrOfDouble::size_array().
Referenced by Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Op_Conv_EF::ajouter_sous_cond_gen(), dotproduct_array_fois_inverse_quantitee_entrelacee(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), gradient_biconjugue(), Extraire_plan::interpreter_(), and som_pscal().
{
  const int size = dx.size_array();
  assert(size == dy.size_array());
  double resultat = 0.;
  if (size > 0)
    {
      integer n = size;
      integer incx = 1;
      resultat = F77NAME(DDOT)(&n, dx.addr(), &incx, dy.addr(), &incx);
    }
  return resultat;
}
static True_int fonction_compare_arrofdouble_ordonner (const void * data1, const void * data2) [static]
Fonction de comparaison utilisee pour trier le tableau
dans ArrOfDouble::trier(). Voir man qsort.
Definition at line 894 of file ArrOfDouble.cpp.
Referenced by ArrOfDouble::ordonne_array().
{
  const double x = *(const double*)data1;
  const double y = *(const double*)data2;
  if (x < y)
    return -1;
  else if (x > y)
    return 1;
  else
    return 0;
}
int imax_array (const ArrOfDouble & dx)
Retourne l'indice du max ou -1 si le tableau est vide.
Returns:
int
Signification: indice du max
Definition at line 763 of file ArrOfDouble.cpp.
References ArrOfDouble::size_array().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), and Domaine::imprimer().
{
  int indice_max = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_max = 0;
      double valeur_max = dx[0];
      for(int i = 1; i < size; i++)
        {
          const double val = dx[i];
          if(val > valeur_max)
            {
              indice_max = i;
              valeur_max = val;
            }
        }
    }
  return indice_max;
}
int imin_array (const ArrOfDouble & dx)
Retourne l'indice du min ou -1 si le tableau est vide.
Returns:
int
Signification: indice du min
Definition at line 735 of file ArrOfDouble.cpp.
References ArrOfDouble::size_array().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), calcul_longueur_filtre(), Rectify_Mesh::check_cell_enumeration_3D(), check_internal_diagonal_for_tetrahedron(), choose_internal_diagonal_for_tetrahedron(), and Domaine::imprimer().
{
  int indice_min = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_min = 0;
      double valeur_min = dx[0];
      for(int i = 1; i < size; i++)
        {
          const double val = dx[i];
          if(val < valeur_min)
            {
              indice_min = i;
              valeur_min = val;
            }
        }
    }
  return indice_min;
}
double max_abs_array (const ArrOfDouble & dx)
Retourne le max des abs(i)
Returns:
double
Signification: valeur du max des valeurs absolues
Contraintes:
Definition at line 848 of file ArrOfDouble.cpp.
References scalar_abs(), and ArrOfDouble::size_array().
Referenced by Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Op_VEF_Face::impr(), and Champ_Fonc_MED::readOn().
{
  const int size = dx.size_array();
  assert(size > 0);
  double valeur_max = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const double val = scalar_abs(dx[i]);
      if (val > valeur_max)
        valeur_max = val;
    }
  return valeur_max;
}
double max_array (const ArrOfDouble & dx)
Retourne la valeur maximale.
Returns:
double
Signification: valeur du max
Definition at line 814 of file ArrOfDouble.cpp.
References ArrOfDouble::size_array().
Referenced by Octree_Int::build(), calcul_longueur_filtre(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Reordonner_faces_periodiques::chercher_direction_perio(), Partitionneur_Tranche::chercher_direction_perio(), compute_global_connex_components(), Partitionneur_Partition::construire_partition(), Decouper::ecrire(), ExtrudeParoi::extrude(), DomaineCutter::initialiser(), Zone_VEF_PreP1b::lecture_ok_arete(), Zone_Cl_EF::remplir_type_elem_Cl(), and reverse_send_recv_pe_list().
{
  const int size = dx.size_array();
  assert(size > 0);
  double valeur_max = dx[0];
  for(int i = 1; i < size; i++)
    {
      const double val = dx[i];
      if (val > valeur_max)
        valeur_max = val;
    }
  return valeur_max;
}
double min_abs_array (const ArrOfDouble & dx)
Retourne le min des abs(i)
Returns:
double
Signification: valeur du min des valeurs absolues
Contraintes:
Definition at line 877 of file ArrOfDouble.cpp.
References scalar_abs(), and ArrOfDouble::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  double v = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const double val = scalar_abs(dx[i]);
      if (val < v)
        v = val;
    }
  return v;
}
double min_array (const ArrOfDouble & dx)
Retourne la valeur minimale.
Returns:
double
Signification: valeur du min
Definition at line 792 of file ArrOfDouble.cpp.
References ArrOfDouble::size_array().
Referenced by Polyedre::affecte_connectivite_numero_global(), Octree_Int::build(), calcul_longueur_filtre(), Reordonner_faces_periodiques::chercher_direction_perio(), Chimie::completer(), Zone_VEF_PreP1b::construire_ok_arete(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), ExtrudeParoi::extrude(), Champ_implementation_P1::init_from_file(), DomaineCutter::initialiser(), Partitionneur_Tranche::initialiser(), Sonde::initialiser(), Execute_parallel::interpreter(), Zone_VEF_PreP1b::lecture_ok_arete(), Pave::lire_Noeuds(), Pave::readOn(), Partitionneur_Tranche::readOn(), champ_init_canal_sinal::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Zone_Cl_EF::remplir_type_elem_Cl(), Rectangle::reordonner_elem(), Hexaedre::reordonner_elem(), reverse_send_recv_pe_list(), and Zone_VEF_PreP1b::verifie_ok_arete().
{
  const int size = dx.size_array();
  assert(size > 0);
  double valeur_min = dx[0];
  for(int i = 1; i < size; i++)
    {
      const double val = dx[i];
      if (val < valeur_min)
        valeur_min = val;
    }
  return valeur_min;
}
double norme_array (const ArrOfDouble & dx)
Calcul de la norme du vecteur dx (fonction blas DNRM2,
soit racine carree(somme des dx[i]*dx[i]).
Definition at line 1294 of file ArrOfDouble.cpp.
References F77NAME, and ArrOfDouble::size_array().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), ajouter_bord(), calcul_normal_norme(), calcul_normal_norme2(), Champ_base::calculer_valeurs_som_post(), check_espace_virtuel_vect(), Terme_Source_Canal_perio::completer(), Periodique::completer(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), gradient_biconjugue(), Champ_front_recyclage::initialiser(), Zone_Cl_EF::remplir_type_elem_Cl(), som_pscal(), and Loi_horaire::tester().
{
  integer n = dx.size_array();
  double resultat = 0.;
  if (n > 0)
    {
      integer incx = 1;
      resultat = F77NAME(DNRM2)(&n, &dx(0), &incx);
    }
  return resultat;
}
int operator== (const Ref_ArrOfDouble & r1, const Ref_ArrOfDouble & r2)
Definition at line 41 of file ArrOfDouble.cpp.
{
int operator== (const ArrOfDouble & v, const ArrOfDouble & a)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille
et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
Definition at line 702 of file ArrOfDouble.cpp.
References ArrOfDouble::addr(), and ArrOfDouble::size_array().
{
  const int n = v.size_array();
  const int na = a.size_array();
  int resu = 1;
  if (n != na)
    {
      resu = 0;
    }
  else
    {
      const double* vv = v.addr();
      const double* av = a.addr();
      int i;
      for (i = 0; i < n; i++)
        {
          if (av[i] != vv[i])
            {
              resu = 0;
              break;
            }
        }
    }
  return resu;
}
static double scalar_abs (double x) [inline, static]
Definition at line 828 of file ArrOfDouble.cpp.
References dabs().
Referenced by max_abs_array(), and min_abs_array().
{
  return dabs(x);
}
Variable Documentation
const Type_info* ArrOfDoublebases[1] = { &(Array_base ::info_obj)}
Definition at line 37 of file ArrOfDouble.cpp.
const Type_info* Ref_ArrOfDoublebases[1] = { &(Ref_ ::info_obj)}
Definition at line 41 of file ArrOfDouble.cpp.
const Type_info* Vect_ArrOfDoublebases[1] = { &(vect_impl ::info_obj)}
Definition at line 39 of file ArrOfDouble.cpp.