TRUST: src/Kernel/Math/ArrOfInt.h File Reference
src/Kernel/Math/ArrOfInt.h File Reference
#include <Array_base.h>
#include <Int.h>
#include <climits>
Classes
class ArrOfInt
Represente un tableau d'elements de type int.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0
(etat obtenu par le constructeur par defaut, detach_array()
et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure Vdbldata, data_==p->data_
et size_array_ <= p->size_. A la destruction du tableau, si
p->ref_count_ est nul on libere la memoire.
data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs
ArrOfInt (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier ArrOfInt a utiliser une zone de memoire
la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire
n'est pas liberee a la destruction du ArrOfInt.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir
pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value".
Priere de supposer desormais que les tableaux ne sont pas initialises
par defaut.
Functions
int operator== (const ArrOfInt &x, const ArrOfInt &y)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille
et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
int imin_array (const ArrOfInt &)
Retourne l'indice du min ou -1 si le tableau est vide.
int imax_array (const ArrOfInt &)
Retourne l'indice du max ou -1 si le tableau est vide.
int min_array (const ArrOfInt &)
Retourne la valeur minimale.
int max_array (const ArrOfInt &)
Retourne la valeur maximale.
int max_abs_array (const ArrOfInt &)
Retourne le max des abs(i)
int min_abs_array (const ArrOfInt &)
Retourne le min des abs(i)
Function Documentation
int imax_array (const ArrOfInt & dx)
Retourne l'indice du max ou -1 si le tableau est vide.
Returns:
int
Signification: indice du max
Definition at line 747 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  int indice_max = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_max = 0;
      int valeur_max = dx[0];
      for(int i = 1; i < size; i++)
        {
          const int val = dx[i];
          if(val > valeur_max)
            {
              indice_max = i;
              valeur_max = val;
            }
        }
    }
  return indice_max;
}
int imin_array (const ArrOfInt & dx)
Retourne l'indice du min ou -1 si le tableau est vide.
Returns:
int
Signification: indice du min
Definition at line 719 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  int indice_min = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_min = 0;
      int valeur_min = dx[0];
      for(int i = 1; i < size; i++)
        {
          const int val = dx[i];
          if(val < valeur_min)
            {
              indice_min = i;
              valeur_min = val;
            }
        }
    }
  return indice_min;
}
int max_abs_array (const ArrOfInt & dx)
Retourne le max des abs(i)
Returns:
int
Signification: valeur du max des valeurs absolues
Contraintes:
Definition at line 832 of file ArrOfInt.cpp.
References scalar_abs(), and ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int valeur_max = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const int val = scalar_abs(dx[i]);
      if (val > valeur_max)
        valeur_max = val;
    }
  return valeur_max;
}
int max_array (const ArrOfInt & dx)
Retourne la valeur maximale.
Returns:
int
Signification: valeur du max
Definition at line 798 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int valeur_max = dx[0];
  for(int i = 1; i < size; i++)
    {
      const int val = dx[i];
      if (val > valeur_max)
        valeur_max = val;
    }
  return valeur_max;
}
int min_abs_array (const ArrOfInt & dx)
Retourne le min des abs(i)
Returns:
int
Signification: valeur du min des valeurs absolues
Contraintes:
Definition at line 861 of file ArrOfInt.cpp.
References scalar_abs(), and ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int v = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const int val = scalar_abs(dx[i]);
      if (val < v)
        v = val;
    }
  return v;
}
int min_array (const ArrOfInt & dx)
Retourne la valeur minimale.
Returns:
int
Signification: valeur du min
Definition at line 776 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int valeur_min = dx[0];
  for(int i = 1; i < size; i++)
    {
      const int val = dx[i];
      if (val < valeur_min)
        valeur_min = val;
    }
  return valeur_min;
}
int operator== (const ArrOfInt & x, const ArrOfInt & y)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille
et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
Definition at line 686 of file ArrOfInt.cpp.
References ArrOfInt::addr(), and ArrOfInt::size_array().
{
  const int n = v.size_array();
  const int na = a.size_array();
  int resu = 1;
  if (n != na)
    {
      resu = 0;
    }
  else
    {
      const int* vv = v.addr();
      const int* av = a.addr();
      int i;
      for (i = 0; i < n; i++)
        {
          if (av[i] != vv[i])
            {
              resu = 0;
              break;
            }
        }
    }
  return resu;
}