TRUST: src/Kernel/Math/ArrOfInt.cpp File Reference
src/Kernel/Math/ArrOfInt.cpp File Reference
#include <ArrOfInt.h>
#include <Memoire.h>
#include <limits.h>
#include <Vect_ArrOfInt.h>
#include <Ref_ArrOfInt.h>
#include <climits>
Classes
class VIntdata
VIntdata alloue une zone de memoire de la taille specifiee au
constructeur, et libere la zone de memoire a la destruction.
La memoire peut etre allouee sur le tas (avec new) ou par le
mecanisme Memoire::add_trav_int.
"ref_count" compte le nombre de pointeurs qui font reference a "this".
(permet au dernier utilisateur de l'objet de le detruire), voir
ArrOfInt.
Functions
int operator== (const Ref_ArrOfInt &r1, const Ref_ArrOfInt &r2)
int operator== (const ArrOfInt &v, const ArrOfInt &a)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille
et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
int imin_array (const ArrOfInt &dx)
Retourne l'indice du min ou -1 si le tableau est vide.
int imax_array (const ArrOfInt &dx)
Retourne l'indice du max ou -1 si le tableau est vide.
int min_array (const ArrOfInt &dx)
Retourne la valeur minimale.
int max_array (const ArrOfInt &dx)
Retourne la valeur maximale.
static int scalar_abs (int x)
int max_abs_array (const ArrOfInt &dx)
Retourne le max des abs(i)
int min_abs_array (const ArrOfInt &dx)
Retourne le min des abs(i)
static True_int fonction_compare_arrofint_ordonner (const void *data1, const void *data2)
Fonction de comparaison utilisee pour trier le tableau
dans ArrOfInt::trier(). Voir man qsort.
Variables
const Type_info * ArrOfIntbases [1] = { &(Array_base ::info_obj)}
const Type_info * Vect_ArrOfIntbases [1] = { &(vect_impl ::info_obj)}
const Type_info * Ref_ArrOfIntbases [1] = { &(Ref_ ::info_obj)}
Function Documentation
static True_int fonction_compare_arrofint_ordonner (const void * data1, const void * data2) [static]
Fonction de comparaison utilisee pour trier le tableau
dans ArrOfInt::trier(). Voir man qsort.
Definition at line 878 of file ArrOfInt.cpp.
Referenced by ArrOfInt::ordonne_array().
{
  const int x = *(const int*)data1;
  const int y = *(const int*)data2;
#ifndef INT_is_64_
  return x - y;
#else
  if (x < y)
    return -1;
  else if (x > y)
    return 1;
  else
    return 0;
#endif
}
int imax_array (const ArrOfInt & dx)
Retourne l'indice du max ou -1 si le tableau est vide.
Returns:
int
Signification: indice du max
Definition at line 747 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  int indice_max = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_max = 0;
      int valeur_max = dx[0];
      for(int i = 1; i < size; i++)
        {
          const int val = dx[i];
          if(val > valeur_max)
            {
              indice_max = i;
              valeur_max = val;
            }
        }
    }
  return indice_max;
}
int imin_array (const ArrOfInt & dx)
Retourne l'indice du min ou -1 si le tableau est vide.
Returns:
int
Signification: indice du min
Definition at line 719 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  int indice_min = -1;
  const int size = dx.size_array();
  if (size > 0)
    {
      indice_min = 0;
      int valeur_min = dx[0];
      for(int i = 1; i < size; i++)
        {
          const int val = dx[i];
          if(val < valeur_min)
            {
              indice_min = i;
              valeur_min = val;
            }
        }
    }
  return indice_min;
}
int max_abs_array (const ArrOfInt & dx)
Retourne le max des abs(i)
Returns:
int
Signification: valeur du max des valeurs absolues
Contraintes:
Definition at line 832 of file ArrOfInt.cpp.
References scalar_abs(), and ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int valeur_max = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const int val = scalar_abs(dx[i]);
      if (val > valeur_max)
        valeur_max = val;
    }
  return valeur_max;
}
int max_array (const ArrOfInt & dx)
Retourne la valeur maximale.
Returns:
int
Signification: valeur du max
Definition at line 798 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int valeur_max = dx[0];
  for(int i = 1; i < size; i++)
    {
      const int val = dx[i];
      if (val > valeur_max)
        valeur_max = val;
    }
  return valeur_max;
}
int min_abs_array (const ArrOfInt & dx)
Retourne le min des abs(i)
Returns:
int
Signification: valeur du min des valeurs absolues
Contraintes:
Definition at line 861 of file ArrOfInt.cpp.
References scalar_abs(), and ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int v = scalar_abs(dx[0]);
  for(int i = 1; i < size; i++)
    {
      const int val = scalar_abs(dx[i]);
      if (val < v)
        v = val;
    }
  return v;
}
int min_array (const ArrOfInt & dx)
Retourne la valeur minimale.
Returns:
int
Signification: valeur du min
Definition at line 776 of file ArrOfInt.cpp.
References ArrOfInt::size_array().
{
  const int size = dx.size_array();
  assert(size > 0);
  int valeur_min = dx[0];
  for(int i = 1; i < size; i++)
    {
      const int val = dx[i];
      if (val < valeur_min)
        valeur_min = val;
    }
  return valeur_min;
}
int operator== (const ArrOfInt & v, const ArrOfInt & a)
Renvoie 1 si les tableaux "v" et "a" sont de la meme taille
et contiennent les memes valeurs au sens strict, sinon renvoie 0.
Le test est !(v[i]!=a[i])
Definition at line 686 of file ArrOfInt.cpp.
References ArrOfInt::addr(), and ArrOfInt::size_array().
{
  const int n = v.size_array();
  const int na = a.size_array();
  int resu = 1;
  if (n != na)
    {
      resu = 0;
    }
  else
    {
      const int* vv = v.addr();
      const int* av = a.addr();
      int i;
      for (i = 0; i < n; i++)
        {
          if (av[i] != vv[i])
            {
              resu = 0;
              break;
            }
        }
    }
  return resu;
}
int operator== (const Ref_ArrOfInt & r1, const Ref_ArrOfInt & r2)
Definition at line 42 of file ArrOfInt.cpp.
{
static int scalar_abs (int x) [inline, static]
Definition at line 812 of file ArrOfInt.cpp.
Referenced by max_abs_array(), and min_abs_array().
{
  return abs(x);
}
Variable Documentation
const Type_info* ArrOfIntbases[1] = { &(Array_base ::info_obj)}
Definition at line 38 of file ArrOfInt.cpp.
const Type_info* Ref_ArrOfIntbases[1] = { &(Ref_ ::info_obj)}
Definition at line 42 of file ArrOfInt.cpp.
const Type_info* Vect_ArrOfIntbases[1] = { &(vect_impl ::info_obj)}
Definition at line 40 of file ArrOfInt.cpp.