TRUST: src/EF/Operateurs/Assembleur_P_EF.cpp File Reference
Assembleur_P_EF.cpp File Reference
#include <Assembleur_P_EF.h>
#include <Zone_Cl_EF.h>
#include <Zone_EF.h>
#include <Neumann_sortie_libre.h>
#include <Dirichlet.h>
#include <Champ_front_instationnaire_base.h>
#include <Champ_front_var_instationnaire.h>
#include <Matrice_Bloc.h>
#include <Array_tools.h>
#include <Debog.h>
#include <Connectivite_som_elem.h>
#include <Static_Int_Lists.h>
#include <Champ_Fonc_Q1_EF.h>
Functions
void calculer_inv_volume_special (DoubleTab &inv_volumes_som, const Zone_Cl_EF &zone_Cl_EF, const DoubleTab &volumes_som, const DoubleTab &marqueur)
void calculer_inv_volume (DoubleTab &inv_volumes_som, const Zone_Cl_EF &zone_Cl_EF, const DoubleVect &volumes_som)
Variables
const Type_info * Assembleur_P_EFbases [1] ={ &(Assembleur_base ::info_obj)}
Function Documentation
calculer_inv_volume()
void calculer_inv_volume (DoubleTab & inv_volumes_som, const Zone_Cl_EF & zone_Cl_EF, const DoubleVect & volumes_som)
Definition at line 62 of file Assembleur_P_EF.cpp.
{
// maintenant l 'inverse du volume est un DoubleTab
// c'est pour faire fonctionner le Piso
  const DoubleTab* doubleT = dynamic_cast<const DoubleTab*>(&volumes_som);
  if (doubleT)
    {
      DoubleTab marqueur(*doubleT);
      marqueur=1;
      zone_Cl_EF.equation().solv_masse().valeur().appliquer_impl(marqueur);
      calculer_inv_volume_special(inv_volumes_som, zone_Cl_EF,*doubleT,marqueur);
      return;
    }
  DoubleTab marqueur;
  marqueur=(volumes_som);
  marqueur=1;
  zone_Cl_EF.equation().solv_masse().appliquer(marqueur);
  int taille=volumes_som.size_totale();
  inv_volumes_som.resize(taille,Objet_U::dimension);
// marqueur
  {
    for (int i=0; i<taille; i++)
      if (marqueur(i))
        for (int comp=0; comp<Objet_U::dimension; comp++)
          inv_volumes_som(i,comp)=1./volumes_som(i);
  }
}
References Solveur_Masse::appliquer(), Solveur_Masse_base::appliquer_impl(), calculer_inv_volume_special(), Objet_U::dimension, MorEqn::equation(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size_totale(), Equation_base::solv_masse(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Assembleur_P_EF::assembler_mat().
calculer_inv_volume_special()
void calculer_inv_volume_special (DoubleTab & inv_volumes_som, const Zone_Cl_EF & zone_Cl_EF, const DoubleTab & volumes_som, const DoubleTab & marqueur)
Definition at line 44 of file Assembleur_P_EF.cpp.
{
  inv_volumes_som=volumes_som;
// MODIF GB
  inv_volumes_som=0.;
  int taille=volumes_som.dimension_tot(0);
  for (int i=0; i<taille; i++)
// MODIF GB
// if (marqueur(i,0))
    {
      double marq_norm2 = 0.;
      for (int comp=0; comp<Objet_U::dimension; comp++) marq_norm2 += marqueur(i,comp)*marqueur(i,comp);
      if (marq_norm2)
        for (int comp=0; comp<Objet_U::dimension; comp++)
          inv_volumes_som(i,comp)=1./volumes_som(i,comp);
    }
}
References Objet_U::dimension, and TRUSTTab< _TYPE_ >::dimension_tot().
Referenced by calculer_inv_volume().
Variable Documentation
Assembleur_P_EFbases
const Type_info* Assembleur_P_EFbases[1] ={ &(Assembleur_base ::info_obj)}
Definition at line 31 of file Assembleur_P_EF.cpp.