TRUST: src/P1NCP1B/Solveurs/Assembleur_P_VEFPreP1B.cpp File Reference
Assembleur_P_VEFPreP1B.cpp File Reference
#include <Assembleur_P_VEFPreP1B.h>
#include <Matrice_Bloc_Sym.h>
#include <Domaine.h>
#include <Dirichlet.h>
#include <Dirichlet_homogene.h>
#include <Entree_fluide_vitesse_imposee.h>
#include <Neumann_sortie_libre.h>
#include <Champ_front_instationnaire_base.h>
#include <Milieu_base.h>
#include <Navier_Stokes_std.h>
#include <TRUSTLists.h>
#include <Op_Grad_VEF_P1B_Face.h>
#include <Op_Div_VEFP1B_Elem.h>
#include <SFichier.h>
#include <Champ_Fonc_P1NC.h>
#include <SolveurPP1B.h>
#include <Check_espace_virtuel.h>
#include <Champ_front_var_instationnaire.h>
#include <Solv_Petsc.h>
#include <Matrice_Petsc.h>
Functions
static double estim_cond (Matrice &A)
void assemblerP0P0 (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee)
void assemblerP1P1 (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
void assemblerPaPa (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee)
void assemblerP0P1 (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
void assemblerP0Pa (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee)
void assemblerP1Pa (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
void updateP0P0 (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee)
void updateP1P1 (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
void modifieP1P1neumann (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
void updatePaPa (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee)
void updateP0P1 (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
void updateP0Pa (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee)
void updateP1Pa (const Zone_dis_base &z, const Zone_Cl_dis_base &zcl, Matrice &matrice, const DoubleTab &inverse_quantitee_entrelacee, const ArrOfDouble &coef_som)
int verifier (const Assembleur_P_VEFPreP1B &ass, const Matrice_Bloc_Sym &matrice, const Zone_VEF_PreP1b &zone_VEF, const DoubleTab &inverse_quantitee_entrelacee)
void zero (Matrice_Bloc_Sym &matrice)
void range (double &prod, int &i, int &n, int &j, int &m, Matrice_Morse &ARR, Matrice_Morse &ARV, Matrice_Morse &AVR, Matrice_Morse &AVV)
void operation11 (Matrice_Bloc &A00, Matrice_Bloc &A01, Matrice_Bloc &A11, double beta, const Zone &zone)
void operation01 (Matrice_Bloc &A00, Matrice_Bloc &A01, double alpha, double beta, const Zone &zone)
Variables
const Type_info * Assembleur_P_VEFPreP1Bbases [1] ={ &(Assembleur_P_VEF ::info_obj)}
Function Documentation
assemblerP0P0()
void assemblerP0P0 (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee)
Definition at line 2209 of file AssembleurPP1BUtil.cpp.
{
  Assembleur_P_VEF Assembleur_P0;
  Assembleur_P0.associer_zone_dis_base(z);
  Assembleur_P0.associer_zone_cl_dis_base(zcl);
  Assembleur_P0.remplir(matrice,inverse_quantitee_entrelacee);
  Cerr << "Assemblage P0 OK" << finl;
}
References Assembleur_P_VEF::associer_zone_cl_dis_base(), Assembleur_P_VEF::associer_zone_dis_base(), Cerr, finl, and Assembleur_P_VEF::remplir().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
assemblerP0P1()
void assemblerP0P1 (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
< RIEN
< On ne traite que les faces internes
Definition at line 2955 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int nb_elem = zone.nb_elem_tot();
  int elem1, elem2, face, ok;
  int nnz=0;
  IntLists voisins(nb_elem);
  DoubleLists coeffs(nb_elem);
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          if(ok==3)
            {
              contribuer_matrice_NeumannP0P1(zone_VEF,
                                             inverse_quantitee_entrelacee,
                                             face, elem1, sommets,
                                             face_opp1, coef_som,
                                             voisins, coeffs, nnz);
            }
          else if(ok==4)
            {
              ;//!< RIEN
            }
          else
            contribuer_matriceP0P1(zone_VEF,
                                   inverse_quantitee_entrelacee,
                                   face, elem1, elem2, sommets,
                                   face_opp1, face_opp2, coef_som,
                                   voisins, coeffs, nnz);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          contribuer_matriceP0P1(zone_VEF,
                                 inverse_quantitee_entrelacee,
                                 face, elem1, elem2, sommets,
                                 face_opp1, face_opp2, coef_som,
                                 voisins, coeffs, nnz);
        }
    }
  matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice_bloc=ref_cast(Matrice_Bloc, matrice.valeur());
  matrice_bloc.remplir(voisins, coeffs, zone.nb_elem(), zone.nb_elem_tot(), zone.nb_som(), zone.nb_som_tot());
  Cerr << "Assemblage POP1 OK" << finl;
}
References Cerr, contribuer_matrice_NeumannP0P1(), contribuer_matriceP0P1(), Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_elem(), Zone::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone::nb_som(), Zone::nb_som_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, Matrice_Bloc::remplir(), remplir_sommets(), vect_impl::size(), sort(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
assemblerP0Pa()
void assemblerP0Pa (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee)
< RIEN
< On ne traite que les faces internes
Definition at line 2642 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int nb_elem = zone.nb_elem_tot();
  int elem1, elem2, face, ok;
  int nnz=0;
  IntLists voisins(nb_elem);
  DoubleLists coeffs(nb_elem);
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          if(ok==3)
            {
              contribuer_matrice_NeumannP0Pa(zone_VEF,
                                             inverse_quantitee_entrelacee,
                                             face, elem1, sommets,
                                             face_opp1,
                                             voisins, coeffs, nnz);
            }
          else if(ok==4)
            {
              ; //!< RIEN
            }
          else
            contribuer_matriceP0Pa(zone_VEF, inverse_quantitee_entrelacee, face, elem1, elem2, sommets,
                                   face_opp1, face_opp2,
                                   voisins, coeffs, nnz);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          contribuer_matriceP0Pa(zone_VEF,
                                 inverse_quantitee_entrelacee,
                                 face, elem1, elem2, sommets,
                                 face_opp1, face_opp2,
                                 voisins, coeffs, nnz);
        }
    }
  matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice_bloc=ref_cast(Matrice_Bloc, matrice.valeur());
  matrice_bloc.remplir(voisins, coeffs, zone.nb_elem(), zone.nb_elem_tot(), zone.nb_aretes(), zone.nb_aretes_tot());
  Cerr << "Assemblage P0Pa OK" << finl;
}
References Cerr, contribuer_matrice_NeumannP0Pa(), contribuer_matriceP0Pa(), Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_aretes(), Zone::nb_aretes_tot(), Zone::nb_elem(), Zone::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, Matrice_Bloc::remplir(), remplir_sommets(), vect_impl::size(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
assemblerP1P1()
void assemblerP1P1 (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
< On ne traite que les faces internes
Definition at line 2234 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int nb_som = zone_VEF.zone().nb_som_tot();
  int elem1, elem2, face, ok;
  int nnz=nb_som;
  IntLists voisins(nb_som);
  DoubleLists coeffs(nb_som);
  DoubleVect diag(nb_som);
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          if(ok==3)
            {
              contribuer_matrice_NeumannP1P1(zone_VEF,
                                             inverse_quantitee_entrelacee,
                                             face, elem1, sommets,
                                             face_opp1, coef_som,
                                             voisins, coeffs, diag, nnz);
            }
          else if(ok==4)
            {
              contribuer_matrice_SymetrieP1P1(zone_VEF,
                                              inverse_quantitee_entrelacee,
                                              face, elem1, sommets,
                                              face_opp1, coef_som,
                                              voisins, coeffs, diag, nnz);
            }
          else
            contribuer_matriceP1P1(zone_VEF,
                                   inverse_quantitee_entrelacee,
                                   face, elem1, elem2, sommets,
                                   face_opp1, face_opp2, coef_som,
                                   voisins, coeffs, diag, nnz);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          contribuer_matriceP1P1(zone_VEF,
                                 inverse_quantitee_entrelacee,
                                 face, elem1, elem2, sommets,
                                 face_opp1, face_opp2, coef_som,
                                 voisins, coeffs, diag, nnz);
        }
    }
  for(int i=0; i<nb_som; i++)
    if(diag(i)==0)
      {
// Cerr << "On modifie la ligne (sommet) orpheline " << i << finl;
        diag(i)=1.;
      }
  matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice_bloc=ref_cast(Matrice_Bloc, matrice.valeur());
  matrice_bloc.remplir(voisins, coeffs, diag, zone.nb_som(), zone.nb_som_tot());
  Cerr << "Assemblage P1 OK" << finl;
}
References Cerr, contribuer_matrice_NeumannP1P1(), contribuer_matrice_SymetrieP1P1(), contribuer_matriceP1P1(), Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone::nb_som(), Zone::nb_som_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, Matrice_Bloc::remplir(), remplir_sommets(), vect_impl::size(), sort(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
assemblerP1Pa()
void assemblerP1Pa (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
< On ne traite que les faces internes
Definition at line 2790 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int elem1, elem2, face, ok;
  int nnz=0;
  int nb_som = zone.nb_som_tot();
  IntLists voisins(nb_som);
  DoubleLists coeffs(nb_som);
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          if(ok==3)
            {
              contribuer_matrice_NeumannP1Pa(zone_VEF,
                                             inverse_quantitee_entrelacee,
                                             face, elem1, sommets,
                                             face_opp1,coef_som,
                                             voisins, coeffs, nnz);
            }
          else if(ok==4)
            {
              contribuer_matrice_SymetrieP1Pa(zone_VEF,
                                              inverse_quantitee_entrelacee,
                                              face, elem1, sommets,
                                              face_opp1, coef_som,
                                              voisins, coeffs, nnz);
            }
          else
            contribuer_matriceP1Pa(zone_VEF,
                                   inverse_quantitee_entrelacee,
                                   face, elem1, elem2, sommets,
                                   face_opp1, face_opp2, coef_som,
                                   voisins, coeffs, nnz);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          contribuer_matriceP1Pa(zone_VEF,
                                 inverse_quantitee_entrelacee,
                                 face, elem1, elem2, sommets,
                                 face_opp1, face_opp2, coef_som,
                                 voisins, coeffs, nnz);
        }
    }
  matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice_bloc=ref_cast(Matrice_Bloc, matrice.valeur());
  matrice_bloc.remplir(voisins, coeffs, zone.nb_som(), zone.nb_som_tot(), zone.nb_aretes(), zone.nb_aretes_tot());
  Cerr << "Assemblage P1Pa OK" << finl;
}
References Cerr, contribuer_matrice_NeumannP1Pa(), contribuer_matrice_SymetrieP1Pa(), contribuer_matriceP1Pa(), Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_aretes(), Zone::nb_aretes_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone::nb_som(), Zone::nb_som_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, Matrice_Bloc::remplir(), remplir_sommets(), vect_impl::size(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
assemblerPaPa()
void assemblerPaPa (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee)
< On ne traite que les faces internes
Definition at line 2464 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int nb_arete = zone.nb_aretes_tot();
  int elem1, elem2, face, ok;
  int nnz=nb_arete;
  IntLists voisins(nb_arete);
  DoubleLists coeffs(nb_arete);
  DoubleVect diag(nb_arete);
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          if(ok==3)
            {
              contribuer_matrice_NeumannPaPa(zone_VEF,
                                             inverse_quantitee_entrelacee,
                                             face, elem1, sommets,
                                             face_opp1,
                                             voisins, coeffs, diag, nnz);
            }
          else if(ok==4)
            {
              contribuer_matrice_SymetriePaPa(zone_VEF,
                                              inverse_quantitee_entrelacee,
                                              face, elem1, sommets,
                                              face_opp1,
                                              voisins, coeffs, diag, nnz);
            }
          else
            contribuer_matricePaPa(zone_VEF,
                                   inverse_quantitee_entrelacee,
                                   face, elem1, elem2, sommets,
                                   face_opp1, face_opp2,
                                   voisins, coeffs, diag, nnz);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          contribuer_matricePaPa(zone_VEF,
                                 inverse_quantitee_entrelacee,
                                 face, elem1, elem2, sommets,
                                 face_opp1, face_opp2,
                                 voisins, coeffs, diag, nnz);
        }
    }
  for(int i=0; i<nb_arete; i++)
    if(diag(i)==0)
      {
// On n'affiche pas car trop sur de gros maillages
// Cerr << "On modifie la ligne (arete) orpheline " << i << finl;
        diag(i)=1;
      }
  matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice_bloc=ref_cast(Matrice_Bloc, matrice.valeur());
  matrice_bloc.remplir(voisins, coeffs, diag, zone.nb_aretes(), zone.nb_aretes_tot());
  Cerr << "Assemblage Pa OK" << finl;
}
References Cerr, contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetriePaPa(), contribuer_matricePaPa(), Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_aretes(), Zone::nb_aretes_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, Matrice_Bloc::remplir(), remplir_sommets(), vect_impl::size(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
estim_cond()
static double estim_cond (Matrice & A) static
Definition at line 51 of file Assembleur_P_VEFPreP1B.cpp.
{
  int i=A.valeur( ).nb_lignes();
// Cout << "rang " << i << finl;
  DoubleVect p(A.valeur( ).nb_lignes());
  for(int j=0; j<i; j++)
    p(j)=drand48();
  double normep=sqrt(mp_prodscal(p,p));
  p/=normep;
  DoubleVect r(A.valeur( ).nb_lignes());
  double lmax=1.e-36, lmin=1.e24;
// double cond=-1;
  i=10000;
  while(i-- )
    {
// cond=lmax/lmin;
      A.valeur( ).multvect(p,r);
      double pscpr=mp_prodscal(p,r);
// Cout << "lambda " << i << " : " << pscpr << " , " << lmax/lmin << finl;
      double pscrr=mp_prodscal(r,r);
      double epsilon=-pscpr/pscrr;
      p.ajoute(epsilon,r);
      double normepbis=sqrt(mp_prodscal(p,p));
// Cout << "normep : " << normep << finl;
      p/=normepbis;
      if(pscpr>lmax)
        lmax=pscpr;
      else if(pscpr<lmin)
        lmin=pscpr;
    }
// Cout << "lmax " << lmax << " lmin = " << lmin << finl;
// Cout << p << finl;
  if (A.valeur( ).nb_lignes()<30) A.valeur( ).imprimer_formatte(Cerr);
  return(lmax/lmin);
}
References TRUSTVect< _TYPE_ >::ajoute(), Cerr, Matrice_Base::imprimer_formatte(), mp_prodscal(), Matrice_Base::multvect(), Matrice_Base::nb_lignes(), and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
modifieP1P1neumann()
void modifieP1P1neumann (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
Definition at line 2416 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
// const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
// int nnz=nb_som;
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
  Matrice_Bloc& A=ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse_Sym& ARR=ref_cast(Matrice_Morse_Sym, A.get_bloc(0,0).valeur());
// Faces de bord :
  assert(ref_cast(Zone_VEF_PreP1b, z).get_cl_pression_sommet_faible()==0);
  int nb_som_tot=z.nb_som();
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim_base& la_cl = les_cl[i].valeur();
      if (sub_type(Neumann_sortie_libre,la_cl))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int nb_faces_bord = le_bord.nb_faces_tot();
          const IntTab& faces=zone_VEF.face_sommets();
          int nbsf=faces.dimension(1);
          for(int ind_face=0; ind_face<nb_faces_bord; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for(int som=0; som<nbsf; som++)
                {
                  int som_glob=faces(face,som);
                  if (som_glob<nb_som_tot)
                    ARR(som_glob,som_glob)=1e12;
// Cout<<ref_cast(Zone_VEF_PreP1b, z).numero_premier_sommet()<<" ici "<<som_glob<<finl;
                }
            }
        }
    }
  Cerr << "Modifie P1P1 Neumann OK" << finl;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::face_sommets(), finl, Cond_lim_base::frontiere_dis(), Matrice_Bloc::get_bloc(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_som(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
operation01()
void operation01 (Matrice_Bloc & A00, Matrice_Bloc & A01, double alpha, double beta, const Zone & zone)
< Element k1
< Element k2
< Calcul de -alpha*beta*Ak1k2
Definition at line 1105 of file Assembleur_P_VEFPreP1B.cpp.
{
// Cerr << "[" << Process::me() << "] Operation01" << finl;
  Matrice_Morse& A01RR=ref_cast(Matrice_Morse, A01.get_bloc(0,0).valeur());
  Matrice_Morse& A01RV=ref_cast(Matrice_Morse, A01.get_bloc(0,1).valeur());
  Matrice_Morse& A01VR=ref_cast(Matrice_Morse, A01.get_bloc(1,0).valeur());
  Matrice_Morse& A01VV=ref_cast(Matrice_Morse, A01.get_bloc(1,1).valeur());
  const IntTab& les_elems=zone.les_elems();
  const Domaine& dom=zone.domaine();
  int nb_elem=A01RR.nb_lignes();
  int nb_som=A01RR.nb_colonnes();
  int nb_som_elem=les_elems.dimension(1);
// On parcours les coefficients de A00
  int ligne=0;
  for (int i_bloc=0; i_bloc<A00.nb_bloc_lignes(); i_bloc++)
    {
      int colonne=0;
      int nb_lignes=0;
      for (int j_bloc=0; j_bloc<A00.nb_bloc_colonnes(); j_bloc++)
        {
          Matrice_Morse& A00ij=ref_cast(Matrice_Morse, A00.get_bloc(i_bloc,j_bloc).valeur());
          const int* tab1=A00ij.get_tab1().addr();
          const int* tab2=A00ij.get_tab2().addr();
          const double* coeff=A00ij.get_coeff().addr();
          nb_lignes=A00ij.nb_lignes();
          int nb_colonnes=A00ij.nb_colonnes();
          int s;
          for (int i=0; i<nb_lignes; i++)
            {
              int k1=ligne+i; //!< Element k1
              for (int n=tab1[i]-1; n<tab1[i+1]-1; n++)
                {
                  int k2=colonne+tab2[n]-1; //!< Element k2
                  if (k2>=k1)
                    {
                      double prod = -alpha * beta * coeff[n];        //!< Calcul de -alpha*beta*Ak1k2
                      for (int som=0; som<nb_som_elem; som++)
{
                          s = dom.get_renum_som_perio(les_elems(k2,som));
                          range(prod,k1,nb_elem,s,nb_som,A01RR,A01RV,A01VR,A01VV);
                          if (k1!=k2)
{
                              s = dom.get_renum_som_perio(les_elems(k1,som));
                              range(prod,k2,nb_elem,s,nb_som,A01RR,A01RV,A01VR,A01VV);
                            }
                        }
                    }
                }
            }
          colonne+=nb_colonnes;
        }
      ligne+=nb_lignes;
    }
}
References TRUSTArray< _TYPE_ >::addr(), coeff, TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_coeff(), Domaine::get_renum_som_perio(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Zone::les_elems(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), prod(), range(), ref_cast, and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::changer_base_matrice().
operation11()
void operation11 (Matrice_Bloc & A00, Matrice_Bloc & A01, Matrice_Bloc & A11, double beta, const Zone & zone)
< Element k1
< Element k2
< Calcul de beta*beta*Ak1k2
< Element k
< Sommet s1
< Calcul de -beta*Aks
< Sommet s2
Definition at line 1006 of file Assembleur_P_VEFPreP1B.cpp.
{
// Cerr << "Operation11" << finl;
  Matrice_Morse_Sym& A11RR=ref_cast(Matrice_Morse_Sym, A11.get_bloc(0,0).valeur());
  Matrice_Morse& A11RV=ref_cast(Matrice_Morse, A11.get_bloc(0,1).valeur());
  Matrice_Morse& A11VR=ref_cast(Matrice_Morse, A11.get_bloc(1,0).valeur());
  Matrice_Morse& A11VV=ref_cast(Matrice_Morse, A11.get_bloc(1,1).valeur());
  const IntTab& les_elems=zone.les_elems();
  const Domaine& dom=zone.domaine();
  int nb_som=A11RR.nb_lignes();
  int nb_som_elem=les_elems.dimension(1);
// On parcours les elements de la matrice A00
// Cerr << "[" << Process::me() << "] Contribution de A00 dans A11~" << finl;
  int ligne=0;
  for (int i_bloc=0; i_bloc<A00.nb_bloc_lignes(); i_bloc++)
    {
      int colonne=0;
      int nb_lignes=0;
      for (int j_bloc=0; j_bloc<A00.nb_bloc_colonnes(); j_bloc++)
        {
          Matrice_Morse& A00ij=ref_cast(Matrice_Morse, A00.get_bloc(i_bloc,j_bloc).valeur());
          const int* tab1=A00ij.get_tab1().addr();
          const int* tab2=A00ij.get_tab2().addr();
          const double* coeff=A00ij.get_coeff().addr();
          nb_lignes=A00ij.nb_lignes();
          int nb_colonnes=A00ij.nb_colonnes();
          for (int i=0; i<nb_lignes; i++)
            {
              int k1=ligne+i; //!< Element k1
              for (int n=tab1[i]-1; n<tab1[i+1]-1; n++)
                {
                  int k2=colonne+tab2[n]-1; //!< Element k2
                  if (k2>=k1)
                    {
                      double prod = beta * beta * coeff[n];        //!< Calcul de beta*beta*Ak1k2
                      for (int som1=0; som1<nb_som_elem; som1++)
{
                          int s1 = dom.get_renum_som_perio(les_elems(k1,som1));
                          for (int som2=0; som2<nb_som_elem; som2++)
{
                              int s2 = dom.get_renum_som_perio(les_elems(k2,som2));
                              if (s2>=s1) range(prod,s1,nb_som,s2,nb_som,A11RR,A11RV,A11VR,A11VV);
                            }
                        }
                      if (k1!=k2)
{
                          for (int som1=0; som1<nb_som_elem; som1++)
{
                              int s1 = dom.get_renum_som_perio(les_elems(k2,som1));
                              for (int som2=0; som2<nb_som_elem; som2++)
{
                                  int s2 = dom.get_renum_som_perio(les_elems(k1,som2));
                                  if (s2>=s1) range(prod,s1,nb_som,s2,nb_som,A11RR,A11RV,A11VR,A11VV);
                                }
                            }
                        }
                    }
                }
            }
          colonne+=nb_colonnes;
        }
      ligne+=nb_lignes;
    }
// On parcours les elements de la matrice A01
// Cerr << "[" << Process::me() << "] Contribution de A01 dans A11~" << finl;
  ligne=0;
  for (int i_bloc=0; i_bloc<A01.nb_bloc_lignes(); i_bloc++)
    {
      int colonne=0;
      int nb_lignes=0;
      for (int j_bloc=0; j_bloc<A01.nb_bloc_colonnes(); j_bloc++)
        {
          Matrice_Morse& A01ij=ref_cast(Matrice_Morse, A01.get_bloc(i_bloc,j_bloc).valeur());
          const int* tab1=A01ij.get_tab1().addr();
          const int* tab2=A01ij.get_tab2().addr();
          const double* coeff=A01ij.get_coeff().addr();
          nb_lignes=A01ij.nb_lignes();
          int nb_colonnes=A01ij.nb_colonnes();
          for (int i=0; i<nb_lignes; i++)
            {
              int k=ligne+i; //!< Element k
              for (int n=tab1[i]-1; n<tab1[i+1]-1; n++)
                {
                  int s1 = dom.get_renum_som_perio(colonne+tab2[n]-1); //!< Sommet s1
                  double prod = -beta * coeff[n];        //!< Calcul de -beta*Aks
                  for (int som=0; som<nb_som_elem; som++)
                    {
                      int s2 = dom.get_renum_som_perio(les_elems(k,som)); //!< Sommet s2
                      if (s2>=s1) range(prod,s1,nb_som,s2,nb_som,A11RR,A11RV,A11VR,A11VV);
                      if (s1>=s2) range(prod,s2,nb_som,s1,nb_som,A11RR,A11RV,A11VR,A11VV);
                    }
                }
            }
          colonne+=nb_colonnes;
        }
      ligne+=nb_lignes;
    }
}
References TRUSTArray< _TYPE_ >::addr(), coeff, TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_coeff(), Domaine::get_renum_som_perio(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Zone::les_elems(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), prod(), range(), ref_cast, and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::changer_base_matrice().
range()
void range (double & prod, int & i, int & n, int & j, int & m, Matrice_Morse & ARR, Matrice_Morse & ARV, Matrice_Morse & AVR, Matrice_Morse & AVV) inline
Definition at line 993 of file Assembleur_P_VEFPreP1B.cpp.
{
  if (i<n)
    if (j<m)
      ARR(i,j)+=prod;
    else
      ARV(i,j-m)+=prod;
  else if (j<m)
    AVR(i-n,j)+=prod;
  else
    AVV(i-n,j-m)+=prod;
}
References prod().
Referenced by operation01(), and operation11().
updateP0P0()
void updateP0P0 (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee)
Definition at line 2222 of file AssembleurPP1BUtil.cpp.
{
  Assembleur_P_VEF Assembleur_P0;
  Assembleur_P0.associer_zone_dis_base(z);
  Assembleur_P0.associer_zone_cl_dis_base(zcl);
  Assembleur_P0.remplir(matrice,inverse_quantitee_entrelacee);
  Cerr << "Update P0 OK" << finl;
}
References Assembleur_P_VEF::associer_zone_cl_dis_base(), Assembleur_P_VEF::associer_zone_dis_base(), Cerr, finl, and Assembleur_P_VEF::remplir().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
updateP0P1()
void updateP0P1 (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
< RIEN
< On ne traite que les faces internes
Definition at line 3035 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int elem1, elem2, face, ok;
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
  Matrice_Bloc& A=ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse& ARR=ref_cast(Matrice_Morse, A.get_bloc(0,0).valeur());
  Matrice_Morse& ARV=ref_cast(Matrice_Morse, A.get_bloc(0,1).valeur());
  Matrice_Morse& AVR=ref_cast(Matrice_Morse, A.get_bloc(1,0).valeur());
  Matrice_Morse& AVV=ref_cast(Matrice_Morse, A.get_bloc(1,1).valeur());
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          if(ok==3)
            {
              update_matrice_NeumannP0P1(zone_VEF,
                                         inverse_quantitee_entrelacee,
                                         face, elem1, sommets,
                                         face_opp1, coef_som,
                                         ARR,ARV,AVR,AVV);
            }
          else if(ok==4)
            {
              ;//!< RIEN
            }
          else
            update_matriceP0P1(zone_VEF,
                               inverse_quantitee_entrelacee,
                               face, elem1, elem2, sommets,
                               face_opp1, face_opp2, coef_som,
                               ARR,ARV,AVR,AVV);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          update_matriceP0P1(zone_VEF,
                             inverse_quantitee_entrelacee,
                             face, elem1, elem2, sommets,
                             face_opp1, face_opp2, coef_som,
                             ARR,ARV,AVR,AVV);
        }
    }
  Cerr << "Update POP1 OK" << finl;
}
References Cerr, Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Matrice_Bloc::get_bloc(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, remplir_sommets(), vect_impl::size(), sort(), update_matrice_NeumannP0P1(), update_matriceP0P1(), and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
updateP0Pa()
void updateP0Pa (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee)
< RIEN
< On ne traite que les faces internes
Definition at line 2717 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int elem1, elem2, face, ok;
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
  Matrice_Bloc& A=ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse& ARR=ref_cast(Matrice_Morse, A.get_bloc(0,0).valeur());
  Matrice_Morse& ARV=ref_cast(Matrice_Morse, A.get_bloc(0,1).valeur());
  Matrice_Morse& AVR=ref_cast(Matrice_Morse, A.get_bloc(1,0).valeur());
  Matrice_Morse& AVV=ref_cast(Matrice_Morse, A.get_bloc(1,1).valeur());
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          if(ok==3)
            {
              update_matrice_NeumannP0Pa(zone_VEF,
                                         inverse_quantitee_entrelacee,
                                         face, elem1, sommets,
                                         face_opp1,
                                         ARR,ARV,AVR,AVV);
            }
          else if(ok==4)
            {
              ; //!< RIEN
            }
          else
            update_matriceP0Pa(zone_VEF, inverse_quantitee_entrelacee,
                               face, elem1, elem2, sommets,
                               face_opp1, face_opp2,
                               ARR,ARV,AVR,AVV);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          update_matriceP0Pa(zone_VEF,
                             inverse_quantitee_entrelacee,
                             face, elem1, elem2, sommets,
                             face_opp1, face_opp2,
                             ARR,ARV,AVR,AVV);
        }
    }
  Cerr << "Update P0Pa OK" << finl;
}
References Cerr, Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Matrice_Bloc::get_bloc(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, remplir_sommets(), vect_impl::size(), update_matrice_NeumannP0Pa(), update_matriceP0Pa(), and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
updateP1P1()
void updateP1P1 (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
< On ne traite que les faces internes
Definition at line 2326 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
// const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
// int nb_som = zone_VEF.zone().nb_som_tot();
  int elem1, elem2, face, ok;
// int nnz=nb_som;
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
  Matrice_Bloc& A=ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse_Sym& ARR=ref_cast(Matrice_Morse_Sym, A.get_bloc(0,0).valeur());
  Matrice_Morse& ARV=ref_cast(Matrice_Morse, A.get_bloc(0,1).valeur());
  Matrice_Morse& AVR=ref_cast(Matrice_Morse, A.get_bloc(1,0).valeur());
  Matrice_Morse& AVV=ref_cast(Matrice_Morse, A.get_bloc(1,1).valeur());
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          if(ok==3)
            {
              update_matrice_NeumannP1P1(zone_VEF,
                                         inverse_quantitee_entrelacee,
                                         face, elem1, sommets,
                                         face_opp1, coef_som,
                                         ARR,ARV,AVR,AVV);
            }
          else if(ok==4)
            {
              update_matrice_SymetrieP1P1(zone_VEF,
                                          inverse_quantitee_entrelacee,
                                          face, elem1, sommets,
                                          face_opp1, coef_som,
                                          ARR,ARV,AVR,AVV);
            }
          else
            update_matriceP1P1(zone_VEF,
                               inverse_quantitee_entrelacee,
                               face, elem1, elem2, sommets,
                               face_opp1, face_opp2, coef_som,
                               ARR,ARV,AVR,AVV);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          sort(sommets, face_opp1, face_opp2);
          update_matriceP1P1(zone_VEF, inverse_quantitee_entrelacee,
                             face, elem1, elem2, sommets,
                             face_opp1, face_opp2, coef_som,
                             ARR,ARV,AVR,AVV);
        }
    }
  int nb_som=zone_VEF.zone().nb_som();
  for(int i=0; i<nb_som; i++)
    if(ARR(i,i)==0)
      {
// Cerr << "On modifie la ligne (sommet) orpheline " << i << finl;
        ARR(i,i)=1.;
      }
  Cerr << "Update P1 OK" << finl;
}
References Cerr, Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Matrice_Bloc::get_bloc(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone::nb_som(), okface(), Zone_VF::premiere_face_int(), ref_cast, remplir_sommets(), vect_impl::size(), sort(), update_matrice_NeumannP1P1(), update_matrice_SymetrieP1P1(), update_matriceP1P1(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
updateP1Pa()
void updateP1Pa (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee, const ArrOfDouble & coef_som)
< On ne traite que les faces internes
Definition at line 2872 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int elem1, elem2, face, ok;
  int nb_som = zone.nb_som_tot();
  IntLists voisins(nb_som);
  DoubleLists coeffs(nb_som);
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
  Matrice_Bloc& A=ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse& ARR=ref_cast(Matrice_Morse, A.get_bloc(0,0).valeur());
  Matrice_Morse& ARV=ref_cast(Matrice_Morse, A.get_bloc(0,1).valeur());
  Matrice_Morse& AVR=ref_cast(Matrice_Morse, A.get_bloc(1,0).valeur());
  Matrice_Morse& AVV=ref_cast(Matrice_Morse, A.get_bloc(1,1).valeur());
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          if(ok==3)
            {
              update_matrice_NeumannP1Pa(zone_VEF,
                                         inverse_quantitee_entrelacee,
                                         face, elem1, sommets,
                                         face_opp1, coef_som,
                                         ARR,ARV,AVR,AVV);
            }
          else if(ok==4)
            {
              update_matrice_SymetrieP1Pa(zone_VEF,
                                          inverse_quantitee_entrelacee,
                                          face, elem1, sommets,
                                          face_opp1, coef_som,
                                          ARR,ARV,AVR,AVV);
            }
          else
            update_matriceP1Pa(zone_VEF,
                               inverse_quantitee_entrelacee,
                               face, elem1, elem2, sommets,
                               face_opp1, face_opp2, coef_som,
                               ARR,ARV,AVR,AVV);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          update_matriceP1Pa(zone_VEF,
                             inverse_quantitee_entrelacee,
                             face, elem1, elem2, sommets,
                             face_opp1, face_opp2,coef_som,
                             ARR,ARV,AVR,AVV);
        }
    }
  Cerr << "Update P1Pa OK" << finl;
}
References Cerr, Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Matrice_Bloc::get_bloc(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone::nb_som_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, remplir_sommets(), vect_impl::size(), update_matrice_NeumannP1Pa(), update_matrice_SymetrieP1Pa(), update_matriceP1Pa(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
updatePaPa()
void updatePaPa (const Zone_dis_base & z, const Zone_Cl_dis_base & zcl, Matrice & matrice, const DoubleTab & inverse_quantitee_entrelacee)
< On ne traite que les faces internes
Definition at line 2554 of file AssembleurPP1BUtil.cpp.
{
  int dimension=Objet_U::dimension;
  const Zone_VEF_PreP1b& zone_VEF=ref_cast(Zone_VEF_PreP1b, z);
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=ref_cast(Zone_Cl_VEF, zcl);
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int nint = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces_tot();
  int nb_arete = zone.nb_aretes();
  int elem1, elem2, face, ok;
  ArrOfInt sommets(dimension+2);
  ArrOfInt face_opp1(dimension+2);
  ArrOfInt face_opp2(dimension+2);
  Matrice_Bloc& A=ref_cast(Matrice_Bloc, matrice.valeur());
  Matrice_Morse_Sym& ARR=ref_cast(Matrice_Morse_Sym, A.get_bloc(0,0).valeur());
  Matrice_Morse& ARV=ref_cast(Matrice_Morse, A.get_bloc(0,1).valeur());
  Matrice_Morse& AVR=ref_cast(Matrice_Morse, A.get_bloc(1,0).valeur());
  Matrice_Morse& AVV=ref_cast(Matrice_Morse, A.get_bloc(1,1).valeur());
// Faces de bord :
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot = le_bord.nb_faces_tot();
      for(int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
        {
          ok=okface(ind_face, face, la_cl);
          if (ok==-1) break;
          elem1=face_voisins(face, 0);
          elem2=face_voisins(face, 1);
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          if(ok==3)
            {
              update_matrice_NeumannPaPa(zone_VEF,
                                         inverse_quantitee_entrelacee,
                                         face, elem1, sommets,
                                         face_opp1,
                                         ARR, ARV, AVR, AVV);
            }
          else if(ok==4)
            {
              update_matrice_SymetriePaPa(zone_VEF,
                                          inverse_quantitee_entrelacee,
                                          face, elem1, sommets,
                                          face_opp1,
                                          ARR, ARV, AVR, AVV);
            }
          else
            update_matricePaPa(zone_VEF,
                               inverse_quantitee_entrelacee,
                               face, elem1, elem2, sommets,
                               face_opp1, face_opp2,
                               ARR, ARV, AVR, AVV);
        }
    }
  face_associee=-1;
  for(face=nint; face<nb_faces; face++)
    {
      elem1=face_voisins(face, 0);
      elem2=face_voisins(face, 1);
      if (!zone_VEF.est_une_face_virt_bord(face)) //!< On ne traite que les faces internes
        {
          remplir_sommets(zone_VEF, face, elem1, elem2, sommets,
                          face_opp1, face_opp2);
          update_matricePaPa(zone_VEF,
                             inverse_quantitee_entrelacee,
                             face, elem1, elem2, sommets,
                             face_opp1, face_opp2,
                             ARR,ARV,AVR,AVV);
        }
    }
  for(int i=0; i<nb_arete; i++)
    if(ARR(i,i)==0)
      {
// On n'affiche pas car trop sur de gros maillages
// Cerr << "On modifie la ligne (arete) orpheline " << i << finl;
        ARR(i,i)=1;
      }
  Cerr << "Update Pa OK" << finl;
}
References Cerr, Objet_U::dimension, Zone_VF::est_une_face_virt_bord(), face_associee, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Matrice_Bloc::get_bloc(), Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_aretes(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), okface(), Zone_VF::premiere_face_int(), ref_cast, remplir_sommets(), vect_impl::size(), update_matrice_NeumannPaPa(), update_matrice_SymetriePaPa(), update_matricePaPa(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
verifier()
int verifier (const Assembleur_P_VEFPreP1B & ass, const Matrice_Bloc_Sym & matrice, const Zone_VEF_PreP1b & zone_VEF, const DoubleTab & inverse_quantitee_entrelacee)
Definition at line 133 of file AssembleurPP1BUtil.cpp.
{
  if (zone_VEF.get_alphaE()+zone_VEF.get_alphaS()+zone_VEF.get_alphaA()!=Objet_U::dimension)
    {
      Cerr << "Assembleur_P_VEFPreP1B::verifier n'est pas prevu pour verifier votre discretisation." << finl;
      Process::exit();
    }
  const Navier_Stokes_std& eqn=ref_cast(Navier_Stokes_std, ass.equation());
  const Operateur_Div& opdiv=eqn.operateur_divergence();
  const Op_Div_VEFP1B_Elem& div=ref_cast(Op_Div_VEFP1B_Elem,
                                         opdiv.valeur());
// div.verifier();
  const Operateur_Grad& opgrad=eqn.operateur_gradient();
  const Op_Grad_VEF_P1B_Face& grad=ref_cast(Op_Grad_VEF_P1B_Face,
                                            opgrad.valeur());
// grad.verifier();
// const Solveur_Masse& solvm=eqn.solv_masse();
  const DoubleTab& pression=eqn.pression().valeurs();
  int ko=0;
  ko=verifier_complet(ass, matrice, zone_VEF);
  DoubleTab pre(pression);
  DoubleTab resu(pre), resu2(pre), erreur(pre);
  DoubleTab gradP(eqn.inconnue().valeurs());
  const Zone& zone=zone_VEF.zone();
  int nb_elem=zone.nb_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int nb_som=zone.domaine().nb_som();
  int nb_som_tot=zone.domaine().nb_som_tot();
  int nb_aretes=zone.nb_aretes();
  const ArrOfInt& ok_arete=zone_VEF.get_ok_arete();
  for (int proc=0; proc<Process::nproc(); proc++)
    {
      int n = pre.dimension_tot(0);
// Le processeur proc impose sa valeur de n a tout le monde
      envoyer_broadcast(n, proc);
      for(int i=0; i<n; i++)
        {
// Cerr << "[" << Process::me() << "] On verifie la ligne " << i << " de la matrice." << finl;
          pre=0;
          if (Process::me()==proc)
            {
              if (0<=i && i<nb_elem)
                {
                  Cerr << "On verifie l'element reel " << i << " du processeur " << proc;
                  pre(i)=1;
                }
              else if (nb_elem_tot<=i && i<nb_elem_tot+nb_som)
                {
                  int sommet=i-nb_elem_tot;
                  Cerr << "On verifie le sommet reel ";
                  if (zone.domaine().get_renum_som_perio(sommet)!=sommet) Cerr << "periodique ";
                  Cerr << i-nb_elem_tot << " du processeur " << proc;
                  pre(i)=1;
                }
              else if (nb_elem_tot+nb_som_tot<=i && i<nb_elem_tot+nb_som_tot+nb_aretes && ok_arete[i-nb_elem_tot-nb_som_tot])
                {
                  int arete=i-nb_elem_tot-nb_som_tot;
                  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
                  if (renum_arete_perio[arete]==arete)
                    {
                      Cerr << "On verifie l'arete reelle non superflue et non periodique " << arete << " du processeur " << proc;
                      pre(i)=1;
                    }
                }
              Cerr << " ";
// Cerr << finl;
            }
          double verifie=mp_max_vect(pre);
// verifie=1;pre(i)=1; // On teste tout
          if (verifie)
            {
              pre.echange_espace_virtuel();
              /* Inutile le debog ce n'est pas comparable le sequentiel et le parallele
                 Nom ch;
                 ch="pre pour la ligne ";
                 ch+=(Nom)i+" du processeur ";
                 ch+=(Nom)proc+" =";
                 Debog::verifier(ch,pre);
              */
// Calcul par Div(Grad(P))
              grad.calculer(pre, gradP);
              {
                int nbf=inverse_quantitee_entrelacee.size();
                int d = Objet_U::dimension;
                for (int face=0; face<nbf; face++)
                  for(int k=0; k<d; k++)
                    gradP(face,k)*=inverse_quantitee_entrelacee(face,k);
              }
// solvm.appliquer(gradP);
              div.calculer(gradP, resu);
// Calcul par -Lap(P)
              matrice.multvect(pre, resu2);
// On doit trouver erreur nul
              erreur=resu2;
              erreur+=resu;
              resu*=-1;
// Cas ou la diagonale est *2, on corrige:
              if (est_egal(2*resu(i),resu2(i))) erreur(i)=0;
              double erreur_absolue=mp_norme_vect(erreur);
              double erreur_relative=erreur_absolue/(mp_norme_vect(resu2)+mp_norme_vect(resu)+DMINFLOAT);
              double app=mp_prodscal(resu,pre);
              if(erreur_absolue>1.e-12 && erreur_relative>1.e-6)
                {
                  Cerr << "[" << Process::me() << "] KO a la ligne " << i << " pour le proc " << proc << " (AP,P)= " << app << " erreur= " << erreur_absolue << finl;
                  ko=1;
                  Cerr << "[" << Process::me() << "] pre= ";
                  pre.ecrit(Cerr);
                  Cerr << "[" << Process::me() << "] Div(gradP) = ";
                  resu.ecrit(Cerr);
                  Cerr << "[" << Process::me() << "] Lap(P) = ";
                  resu2.ecrit(Cerr);
                  Cerr << "[" << Process::me() << "] erreur = ";
                  erreur.ecrit(Cerr);
                  Cerr << "[" << Process::me() << "] invqtentrelacee = ";
                  inverse_quantitee_entrelacee.ecrit(Cerr);
                }
              else
                {
                  Cerr << "[" << Process::me() << "] OK a la ligne " << i << " pour le proc " << proc << " (AP,P)= " << app << " erreur= " << erreur_absolue << finl;
                }
            }
        }
    }
  if (ko)
    {
      Cerr << "[" << Process::me() << "] Matrice en pression:" << finl;
      matrice.imprimer_formatte(Cerr);
      Cerr << "Echec de la methode verifier de l'assembleur. Voir les KO." << finl;
      Process::exit();
    }
  return 1;
}
References Op_Div_VEF_Elem::calculer(), Op_Grad_VEF_Face::calculer(), Cerr, Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), DMINFLOAT, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTTab< _TYPE_ >::ecrit(), envoyer_broadcast(), Assembleur_P_VEFPreP1B::equation(), erreur(), est_egal(), Process::exit(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Matrice_Bloc_Sym::imprimer_formatte(), Navier_Stokes_std::inconnue(), Process::me(), mp_max_vect(), mp_norme_vect(), mp_prodscal(), Matrice_Base::multvect(), Zone::nb_aretes(), Zone::nb_elem(), Zone::nb_elem_tot(), Domaine::nb_som(), Domaine::nb_som_tot(), Process::nproc(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Navier_Stokes_std::pression(), ref_cast, TRUSTVect< _TYPE_ >::size(), Deriv_Operateur_Div_base::valeur(), Deriv_Operateur_Grad_base::valeur(), Champ_Inc::valeurs(), verifie(), verifier_complet(), and Zone_dis_base::zone().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
zero()
void zero (Matrice_Bloc_Sym & matrice)
Definition at line 199 of file Assembleur_P_VEFPreP1B.cpp.
{
  int nombre_supports = matrice.ordre();
  for(int i=0; i<nombre_supports; i++)
    for(int j=i; j<nombre_supports; j++)
      {
        Matrice_Bloc& bloc_ij=ref_cast(Matrice_Bloc, matrice.get_bloc(i,j).valeur());
        ref_cast(Matrice_Morse, bloc_ij.get_bloc(0,0).valeur()).clean();
        if(Process::nproc()>1)
          {
            ref_cast(Matrice_Morse, bloc_ij.get_bloc(0,1).valeur()).clean();
            ref_cast(Matrice_Morse, bloc_ij.get_bloc(1,0).valeur()).clean();
            ref_cast(Matrice_Morse, bloc_ij.get_bloc(1,1).valeur()).clean();
          }
      }
}
References Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Process::nproc(), Matrice_Bloc::ordre(), ref_cast, and Deriv_Matrice_Base::valeur().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Fluide_base::calculer_e_int(), Fluide_reel_base::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), Fluide_reel_base::calculer_masse_volumique(), check_ICEM_binary_file(), Fluide_reel_base::check_unknown_range(), erreur_chfront(), Extraire_plan::interpreter_(), and read_write_string_from().
Variable Documentation
Assembleur_P_VEFPreP1Bbases
const Type_info* Assembleur_P_VEFPreP1Bbases[1] ={ &(Assembleur_P_VEF ::info_obj)}
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.