TRUST: src/Kernel/Utilitaires/Avanc.h File Reference
src/Kernel/Utilitaires/Avanc.h File Reference
Functions
double avancer_fichier (Entree &, const Nom &, const int read_header=0)
double get_last_time (Entree &)
Function Documentation
double avancer_fichier (Entree & , const Nom & , const int read_header = 0)
< Entree::set_diffuse() set to 1, only Lec_Diffuse_base::set_diffuse() can set to 0
< Number of digits to write the time
< Old time format
Definition at line 46 of file Avanc.cpp.
References Cerr, envoyer_broadcast(), erreur(), extract_time_from_string(), finl, Entree::get_diffuse(), Entree::get_istream(), Process::je_suis_maitre(), Deriv_Objet_U::reprendre(), Entree::set_diffuse(), Operateur_Statistique_tps_base::temps(), and Deriv_::typer().
Referenced by get_last_time(), Champ_Fonc_reprise::readOn(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Equation_base::reprendre(), and Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
{
  /* Surcharge par:
   double LecFicDiffuse::seek(const Nom& id)
   {
      double time;
      diffuse_=0;
      if (Process::je_suis_maitre()) time = Entree::seek(id);
      diffuse_=1;
      envoyer_broadcast(temps, 0);
      return time;
   }
// Possible evolution:
// avancer_fichier(fich,id) -> fich.avancer_fichier(id);
// Implementation of double Entree::seek(const Nom& id):
// diffuse_ redescend dans LecFicDiffuseBase
  */
  double temps=0;
  fich.set_diffuse(0); //!< Entree::set_diffuse() set to 1, only Lec_Diffuse_base::set_diffuse() can set to 0
  if (fich.get_diffuse() || Process::je_suis_maitre())
    {
      Cerr << "Looking for the tag " << id << " in the file." << finl;
      Nom ident_lu;
      Nom type_lu;
      int digits=12; //!< Number of digits to write the time
      fich >> ident_lu;
      if (read_header)
        {
          if (ident_lu!="format_sauvegarde:")
            {
              digits=8; //!< Old time format
            }
          else
            {
// New format
              int format;
              fich >> format;
              fich >> ident_lu;
            }
        }
      fich >> type_lu;
      while (Motcle(ident_lu) != Motcle(id))
        {
          DerObjU un_objet;
          un_objet.typer(type_lu);
          Cerr << "-> Passing object " << ident_lu << " ... " << flush;
          un_objet.reprendre(fich);
          Cerr << "OK" << finl;
          temps = extract_time_from_string(ident_lu, digits);
          if (!fich.get_istream()) erreur(id);
          fich >> ident_lu;
          if (id!=(Nom)"fin" && ident_lu == (Nom)"fin") erreur(id);
          fich >> type_lu;
        }
      Cerr << "-> Find object " << id << " and reading data in it ..." << finl;
    }
  envoyer_broadcast(temps, 0);
  fich.set_diffuse(1);
  return temps;
}
double get_last_time (Entree &)
Definition at line 109 of file Avanc.cpp.
References avancer_fichier().
Referenced by Champ_Fonc_reprise::readOn(), and Probleme_base::readOn().
{
  return avancer_fichier(fich, "fin", 1);
}