TRUST: src/Kernel/Utilitaires/Avanc.cpp File Reference
src/Kernel/Utilitaires/Avanc.cpp File Reference
#include <Avanc.h>
#include <Motcle.h>
#include <DerOu_.h>
#include <communications.h>
Functions
void erreur (const Nom &id)
void convert_to (const char *s, double &ob)
double extract_time_from_string (const Nom &ident_lu, const int &digits)
double avancer_fichier (Entree &fich, const Nom &id, const int read_header)
double get_last_time (Entree &fich)
Function Documentation
double avancer_fichier (Entree & fich, const Nom & id, const int read_header)
< Entree::set_diffuse() set to 1, only Lec_Diffuse_base::set_diffuse() can set to 0
< Number of digits to write the time
< Old time format
Definition at line 46 of file Avanc.cpp.
References Cerr, envoyer_broadcast(), erreur(), extract_time_from_string(), finl, Entree::get_diffuse(), Entree::get_istream(), Process::je_suis_maitre(), Deriv_Objet_U::reprendre(), Entree::set_diffuse(), Operateur_Statistique_tps_base::temps(), and Deriv_::typer().
Referenced by get_last_time(), Champ_Fonc_reprise::readOn(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Equation_base::reprendre(), and Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
{
  /* Surcharge par:
   double LecFicDiffuse::seek(const Nom& id)
   {
      double time;
      diffuse_=0;
      if (Process::je_suis_maitre()) time = Entree::seek(id);
      diffuse_=1;
      envoyer_broadcast(temps, 0);
      return time;
   }
// Possible evolution:
// avancer_fichier(fich,id) -> fich.avancer_fichier(id);
// Implementation of double Entree::seek(const Nom& id):
// diffuse_ redescend dans LecFicDiffuseBase
  */
  double temps=0;
  fich.set_diffuse(0); //!< Entree::set_diffuse() set to 1, only Lec_Diffuse_base::set_diffuse() can set to 0
  if (fich.get_diffuse() || Process::je_suis_maitre())
    {
      Cerr << "Looking for the tag " << id << " in the file." << finl;
      Nom ident_lu;
      Nom type_lu;
      int digits=12; //!< Number of digits to write the time
      fich >> ident_lu;
      if (read_header)
        {
          if (ident_lu!="format_sauvegarde:")
            {
              digits=8; //!< Old time format
            }
          else
            {
// New format
              int format;
              fich >> format;
              fich >> ident_lu;
            }
        }
      fich >> type_lu;
      while (Motcle(ident_lu) != Motcle(id))
        {
          DerObjU un_objet;
          un_objet.typer(type_lu);
          Cerr << "-> Passing object " << ident_lu << " ... " << flush;
          un_objet.reprendre(fich);
          Cerr << "OK" << finl;
          temps = extract_time_from_string(ident_lu, digits);
          if (!fich.get_istream()) erreur(id);
          fich >> ident_lu;
          if (id!=(Nom)"fin" && ident_lu == (Nom)"fin") erreur(id);
          fich >> type_lu;
        }
      Cerr << "-> Find object " << id << " and reading data in it ..." << finl;
    }
  envoyer_broadcast(temps, 0);
  fich.set_diffuse(1);
  return temps;
}
void convert_to (const char * s, double & ob)
Definition at line 232 of file Entree.cpp.
Referenced by extract_time_from_string(), Perte_Charge_Singuliere::lire_donnees(), Entree::operator>>(), and Champ_Fonc_reprise::readOn().
{
  errno = 0;
  char * errorptr = 0;
  ob = strtod(s, &errorptr);
  if (errno || *errorptr != 0)
    {
      Cerr << "Error converting a string to type float : string = " << s << finl;
      Process::exit();
    }
}
void erreur (const Nom & id) [inline]
Definition at line 28 of file Avanc.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << finl;
  Cerr << "The restarting has failed. The tag " << id << " has not been" << finl;
  Cerr << "found in the restarting file. Check the restarting time in your data set." << finl;
  Process::exit();
}
double extract_time_from_string (const Nom & ident_lu, const int & digits)
Definition at line 37 of file Avanc.cpp.
References convert_to(), Nom::longueur(), Nom::substr_old(), and Operateur_Statistique_tps_base::temps().
Referenced by avancer_fichier().
{
  double temps;
  int length = ident_lu.longueur();
  convert_to(ident_lu.substr_old(length-digits,digits),temps);
  return temps;
}
double get_last_time (Entree & fich)
Definition at line 109 of file Avanc.cpp.
References avancer_fichier().
Referenced by Champ_Fonc_reprise::readOn(), and Probleme_base::readOn().
{
  return avancer_fichier(fich, "fin", 1);
}