TRUST: src/MAIN/catch_and_trace.h File Reference
catch_and_trace.h File Reference
#include <execinfo.h>
#include <signal.h>
#include <stdio.h>
#include <cstring>
#include <dlfcn.h>
#include <iostream>
#include <cstdlib>
#include <memory>
#include <string>
#include <array>
#include <Process.h>
#include <EntreeSortie.h>
Classes
struct _sig_ucontext
Macros
#define _GNU_SOURCE
#define __USE_GNU
Typedefs
typedef struct _sig_ucontext sig_ucontext_t
Functions
int exec_cmd_and_get_output (const char *cmd, std::string &result)
void crit_err_hdlr (True_int sig_num, siginfo_t *info, void *ucontext)
void install_handlers ()
Macro Definition Documentation
__USE_GNU
#define __USE_GNU
Definition at line 23 of file catch_and_trace.h.
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 20 of file catch_and_trace.h.
Typedef Documentation
sig_ucontext_t
typedef struct _sig_ucontext sig_ucontext_t
Function Documentation
crit_err_hdlr()
void crit_err_hdlr (True_int sig_num, siginfo_t * info, void * ucontext)
Definition at line 77 of file catch_and_trace.h.
{
  std::cerr << "Error handler triggered!! See Journal - process ID: " << Process::me() << std::endl;
  Process::Journal() << "signal " << (int)sig_num
                     << " (" << strsignal(sig_num) << "), address is "
                     << long(info->si_addr) << finl; //" from "
  void * array[100];
  int size = backtrace(array, 100);
  Process::Journal() << __FUNCTION__ << " backtrace returned " << size << " frames\n" << finl;
// Extract symbols from backtrace
  char ** messages = backtrace_symbols(array, size);
// Skip first stack frame (points here) and print out backtrace
  for (int i = 1; i < size && messages != NULL; ++i)
    {
      Process::Journal() << "[proc " << Process::me() << "]: (" << i << ") " << messages[i] << finl;
// Find first occurence of '(' or ' ' in message[i] and assume
// everything before that is the file name (don't go beyond 0 though, string terminator)
      size_t p = 0;
      while(messages[i][p] != '(' && messages[i][p] != ' '
            && messages[i][p] != 0)
        ++p;
// Call 'addr2line' system utility to extract line number in the source code:
      char syscom[256];
      sprintf(syscom, "addr2line %p --functions -e %.*s | tr '\n' ' ' | c++filt", array[i], (True_int)p, messages[i]);
      std::string output;
      int ret = exec_cmd_and_get_output(syscom, output);
      if(!ret)
        Process::Journal() << "(Unable to execute 'addr2line' to get line number in source ...)" << finl;
      else
        Process::Journal() << "[proc " << Process::me() << "]: (" << i << ") ----> "
                           << output << finl;
    }
  Process::Journal() << finl;
  free(messages);
  Process::exit();
}
References exec_cmd_and_get_output(), Process::exit(), finl, info, Process::Journal(), and Process::me().
Referenced by install_handlers().
exec_cmd_and_get_output()
int exec_cmd_and_get_output (const char * cmd, std::string & result)
< popen failed - unable to execute system command
Definition at line 59 of file catch_and_trace.h.
{
  std::array<char, 128> buffer;
  std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd, "r"), pclose);
  if (!pipe)
    {
      return 0; //!< popen failed - unable to execute system command
    }
  while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr)
    {
      result += buffer.data();
    }
  return 1;
}
Referenced by crit_err_hdlr().
install_handlers()
void install_handlers ()
Definition at line 123 of file catch_and_trace.h.
{
  struct sigaction sigact;
  sigemptyset(&sigact.sa_mask);
  sigact.sa_sigaction = crit_err_hdlr;
  sigact.sa_flags = SA_RESTART | SA_SIGINFO;
  if (sigaction(SIGABRT, &sigact, (struct sigaction *)NULL) != 0)
    {
      std::cerr << "FATAL ERROR setting handler for signal " << SIGABRT
                << " (" << strsignal(SIGABRT) << ")" << std::endl;
      Process::exit();
    }
  if (sigaction(SIGFPE, &sigact, (struct sigaction *)NULL) != 0)
    {
      std::cerr << "FATAL ERROR setting handler for signal " << SIGFPE
                << " (" << strsignal(SIGFPE) << ")" << std::endl;
      Process::exit();
    }
  std::cerr << "Custom error handlers correctly installed. SIGFPE and SIGABRT redirected." << std::endl;
}
References crit_err_hdlr(), and Process::exit().
Referenced by init_petsc().