TRUST: src/Kernel/Framework/Champ_base.cpp File Reference
Champ_base.cpp File Reference
#include <Discretisation_base.h>
#include <Dirichlet_homogene.h>
#include <Format_Post_base.h>
#include <communications.h>
#include <Equation_base.h>
#include <Probleme_base.h>
#include <Schema_Comm.h>
#include <Champ_base.h>
#include <TRUSTVects.h>
#include <TRUSTTrav.h>
#include <Dirichlet.h>
#include <TRUSTList.h>
#include <Symetrie.h>
#include <strings.h>
#include <Zone_VF.h>
Functions
void add_sommets_communs (const Domaine &dom, DoubleTab &les_valeurs, IntTab &compteur)
Variables
const Type_info * Champ_basebases [1] ={ &(Field_base ::info_obj)}
Function Documentation
add_sommets_communs()
void add_sommets_communs (const Domaine & dom, DoubleTab & les_valeurs, IntTab & compteur) inline
Definition at line 650 of file Champ_base.cpp.
{
// if (Process::nproc()>9) return;
  char* theValue = getenv("TRUST_POST_SOM_NON_PARA");
  if (theValue != NULL)
    return;
  int nb_compo_ = les_valeurs.line_size();
// On balaie les joints
  const Joints& joints = dom.zone(0).faces_joint();
  const int nb_joints = joints.size();
  for (int i_joint = 0; i_joint < nb_joints; i_joint++)
    {
      const Joint& joint = joints[i_joint];
      const int PEvoisin = joint.PEvoisin();
      const Joint_Items& joint_item = joint.joint_item(Joint::SOMMET);
      const ArrOfInt& sommets_communs = joint_item.items_communs();
// Tableaux temporaires
      IntTab envoie_sommets;
      DoubleTab envoie_valeurs;
      IntTab envoie_compteur;
      IntTab recoit_sommets;
      DoubleTab recoit_valeurs;
      IntTab recoit_compteur;
      int size=0;
// On balaie les sommets communs
      int size_sommets_communs = sommets_communs.size_array();
      for (int j=0; j<size_sommets_communs; j++)
        {
          int sommet = sommets_communs[j];
// Si ce sommet commun appartient a la liste des sommets Dirichlet:
          if ( compteur(sommet)>0)
            {
// Le numero du sommet voisin distant est:
              int sommet_voisin = joint_item.renum_items_communs()(j,0);
// On verifie que le sommet local est bien sommet:
              assert(joint_item.renum_items_communs()(j,1)==sommet);
// On redimensionne les tableaux d'envoi et on les remplit
              size++;
              envoie_sommets.resize(size);
              envoie_sommets(size-1) = sommet_voisin;
              envoie_compteur.resize(size);
              envoie_compteur(size-1) = compteur(sommet);
              envoie_valeurs.resize(size, nb_compo_);
              for(int compo=0; compo<nb_compo_; compo++)
                envoie_valeurs(size-1,compo) = les_valeurs(sommet,compo);
            }
        }
      if (Process::me()<PEvoisin)
        {
// On envoie les tableaux a PEvoisin
          envoyer(envoie_sommets,Process::me(),PEvoisin,Process::me()+1000);
          envoyer(envoie_valeurs,Process::me(),PEvoisin,Process::me()+2000);
          envoyer(envoie_compteur,Process::me(),PEvoisin,Process::me()+3000);
// On recoit les tableaux de PEvoisin
          recevoir(recoit_sommets,PEvoisin,Process::me(),PEvoisin+1000);
          recevoir(recoit_valeurs,PEvoisin,Process::me(),PEvoisin+2000);
          recevoir(recoit_compteur,PEvoisin,Process::me(),PEvoisin+3000);
        }
      else
        {
// On recoit les tableaux de PEvoisin
          recevoir(recoit_sommets,PEvoisin,Process::me(),PEvoisin+1000);
          recevoir(recoit_valeurs,PEvoisin,Process::me(),PEvoisin+2000);
          recevoir(recoit_compteur,PEvoisin,Process::me(),PEvoisin+3000);
// On envoie les tableaux a PEvoisin
          envoyer(envoie_sommets,Process::me(),PEvoisin,Process::me()+1000);
          envoyer(envoie_valeurs,Process::me(),PEvoisin,Process::me()+2000);
          envoyer(envoie_compteur,Process::me(),PEvoisin,Process::me()+3000);
        }
// On ajoute la contribution de PEvoisin aux tableaux valeurs et compteur
// si les compteurs de part et d'autre ne sont pas nuls
      int recoit_size = recoit_sommets.size_array();
      for (int i=0; i<recoit_size; i++)
        {
          int sommet = recoit_sommets(i);
// Contribution recu d'un sommet Dirichlet
          if (recoit_compteur(i))
            {
// Si le sommet local n'est pas Dirichlet, on annulle valeurs
              if (compteur(sommet)==0)
                for(int compo=0; compo<nb_compo_; compo++)
                  les_valeurs(sommet,compo)=0;
              compteur(sommet)+=recoit_compteur(i);
              for(int compo=0; compo<nb_compo_; compo++)
                les_valeurs(sommet,compo)+=recoit_valeurs(i,compo);
            }
        }
    }
}
References compteur, envoyer(), Zone::faces_joint(), Joint_Items::items_communs(), Joint::joint_item(), TRUSTVect< _TYPE_ >::line_size(), Process::me(), Joint::PEvoisin(), recevoir(), Joint_Items::renum_items_communs(), TRUSTTab< _TYPE_ >::resize(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), Joint::SOMMET, and Domaine::zone().
Referenced by Champ_base::calculer_valeurs_som_compo_post(), and Champ_base::calculer_valeurs_som_post().
Variable Documentation
Champ_basebases
const Type_info* Champ_basebases[1] ={ &(Field_base ::info_obj)}
Definition at line 32 of file Champ_base.cpp.