TRUST: src/Kernel/Champs/Champ_front_lu.cpp File Reference
Champ_front_lu.cpp File Reference
#include <Champ_front_lu.h>
#include <Domaine.h>
#include <LecFicDiffuse.h>
#include <Interprete.h>
#include <Zone_VF.h>
Functions
void erreur_chfront (const Nom &nom_fic, const int dim, const Nom &nom_domaine)
Variables
const Type_info * Champ_front_lubases [1] ={ &(Ch_front_var_stationnaire ::info_obj)}
Function Documentation
erreur_chfront()
void erreur_chfront (const Nom & nom_fic, const int dim, const Nom & nom_domaine)
Definition at line 86 of file Champ_front_lu.cpp.
{
  Cerr << "****************************************************************************************************************" << finl;
  Cerr << "Error! It seems that several faces into the file " << nom_fic << " does not match any faces of the current mesh." << finl;
  Cerr << finl;
  Cerr << "First, check that the file " << nom_fic << " can be used to define a boundary field on the specified boundary of the current mesh." << finl;
  Cerr << "Second, try to switch to a different algorithm in your data file (find the nearest geometric face of the mesh for each face defined in the " << nom_fic << " file):" << finl;
  Cerr << "Replace:" <<finl;
  Cerr << "Champ_front_lu " << nom_domaine << " " << dim << " " << nom_fic << finl;
  Nom un((Nom)dim),zero((Nom)dim);
  for (int i=0; i<dim; i++)
    {
      un+=" 1";
      zero+=" 0";
    }
  Cerr << "By:"<<finl;
  Nom chaine="moyenne_imposee connexion_approchee fichier";
  Cerr << "Champ_front_recyclage { pb_champ_evaluateur problem_name field_name "<<dim<<finl;
  Cerr << "                        "<<chaine<<" "<<nom_fic<<finl;
  Cerr << "                        ampli_moyenne_imposee "<<un<<finl;
  Cerr << "                        ampli_moyenne_recyclee "<<zero<<finl;
  Cerr << "                        ampli_fluctuation "<<zero<<" }" <<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and zero().
Referenced by Champ_front_lu::initialiser().
Variable Documentation
Champ_front_lubases
const Type_info* Champ_front_lubases[1] ={ &(Ch_front_var_stationnaire ::info_obj)}
Definition at line 22 of file Champ_front_lu.cpp.