TRUST: src/VEF/Champs/Champ_som_lu_VEF.cpp File Reference
Champ_som_lu_VEF.cpp File Reference
#include <Champ_som_lu_VEF.h>
#include <EFichier.h>
#include <TRUSTTab.h>
#include <Domaine.h>
Functions
double coord_barycentrique3D (const IntTab &polys, const DoubleTab &coord, double x, double y, double z, int le_poly, int i)
double coord_barycentrique2D (const IntTab &polys, const DoubleTab &coord, double x, double y, int le_poly, int i)
Variables
const Type_info * Champ_som_lu_VEFbases [1] ={ &(Champ_som_lu ::info_obj)}
Function Documentation
coord_barycentrique2D()
double coord_barycentrique2D (const IntTab & polys, const DoubleTab & coord, double x, double y, int le_poly, int i)
Definition at line 209 of file Champ_som_lu_VEF.cpp.
{
  int som0 = polys(le_poly, i), som1 = polys(le_poly, 1);
  if (i == 1) som1 = polys(le_poly, 0);
  double xref = coord(som1, 0) - coord(som0, 0);
  double yref = coord(som1, 1) - coord(som0, 1);
  double xp = x - coord(som0, 0);
  double yp = y - coord(som0, 1);
  double pscal = (xref * xp) + (yref * yp);
  double norm = (xref * xref) + (yref * yref);
  assert(norm != 0.);
  double coord_bary = pscal / norm;
  assert(sup_ou_egal(coord_bary, 0) && inf_ou_egal(coord_bary, 1));
  return coord_bary;
}
References inf_ou_egal(), and sup_ou_egal().
Referenced by Champ_som_lu_VEF::valeur_aux_elems(), and Champ_som_lu_VEF::valeur_aux_elems_compo().
coord_barycentrique3D()
double coord_barycentrique3D (const IntTab & polys, const DoubleTab & coord, double x, double y, double z, int le_poly, int i)
Definition at line 146 of file Champ_som_lu_VEF.cpp.
{
  int som0, som1, som2, som3;
  switch(i)
    {
    case 0:
      {
        som0 = polys(le_poly, 0);
        som1 = polys(le_poly, 1);
        som2 = polys(le_poly, 2);
        som3 = polys(le_poly, 3);
        break;
      }
    case 1:
      {
        som0 = polys(le_poly, 1);
        som1 = polys(le_poly, 2);
        som2 = polys(le_poly, 3);
        som3 = polys(le_poly, 0);
        break;
      }
    case 2:
      {
        som0 = polys(le_poly, 2);
        som1 = polys(le_poly, 3);
        som2 = polys(le_poly, 0);
        som3 = polys(le_poly, 1);
        break;
      }
    case 3:
      {
        som0 = polys(le_poly, 3);
        som1 = polys(le_poly, 0);
        som2 = polys(le_poly, 1);
        som3 = polys(le_poly, 2);
        break;
      }
    default:
      {
        som0 = som1 = som2 = som3 = -1;
        assert(0);
        Process::exit();
        break;
      }
    }
  double xp = (coord(som2, 1) - coord(som1, 1)) * (coord(som0, 2) - coord(som1, 2)) - (coord(som2, 2) - coord(som1, 2)) * (coord(som0, 1) - coord(som1, 1));
  double yp = (coord(som2, 2) - coord(som1, 2)) * (coord(som0, 0) - coord(som1, 0)) - (coord(som2, 0) - coord(som1, 0)) * (coord(som0, 2) - coord(som1, 2));
  double zp = (coord(som2, 0) - coord(som1, 0)) * (coord(som0, 1) - coord(som1, 1)) - (coord(som2, 1) - coord(som1, 1)) * (coord(som0, 0) - coord(som1, 0));
  double den = xp * (coord(som3, 0) - coord(som1, 0)) + yp * (coord(som3, 1) - coord(som1, 1)) + zp * (coord(som3, 2) - coord(som1, 2));
  xp = (coord(som2, 1) - coord(som1, 1)) * (z - coord(som1, 2)) - (coord(som2, 2) - coord(som1, 2)) * (y - coord(som1, 1));
  yp = (coord(som2, 2) - coord(som1, 2)) * (x - coord(som1, 0)) - (coord(som2, 0) - coord(som1, 0)) * (z - coord(som1, 2));
  zp = (coord(som2, 0) - coord(som1, 0)) * (y - coord(som1, 1)) - (coord(som2, 1) - coord(som1, 1)) * (x - coord(som1, 0));
  double num = xp * (coord(som3, 0) - coord(som1, 0)) + yp * (coord(som3, 1) - coord(som1, 1)) + zp * (coord(som3, 2) - coord(som1, 2));
  assert(den != 0.);
  double coord_bary = num / den;
  assert(sup_ou_egal(coord_bary, 0) && inf_ou_egal(coord_bary, 1));
  return coord_bary;
}
References Process::exit(), inf_ou_egal(), and sup_ou_egal().
Referenced by Champ_som_lu_VEF::valeur_aux_elems(), and Champ_som_lu_VEF::valeur_aux_elems_compo().
Variable Documentation
Champ_som_lu_VEFbases
const Type_info* Champ_som_lu_VEFbases[1] ={ &(Champ_som_lu ::info_obj)}
Definition at line 22 of file Champ_som_lu_VEF.cpp.