TRUST: src/Kernel/Framework/Champ_Don_base.h File Reference
Champ_Don_base.h File Reference
#include <Champ_base.h>
#include <TRUSTTab.h>
Classes
class Champ_Don_base
Typedefs
template<bool B, typename T >
using enable_if_t = typename std::enable_if< B, T >::type
classe Champ_Don_base
classe de base des Champs donnes (non calcules)
les proprietes physiques sont des Champs donnes
mais peuvent etre variables dans le temps dans l'espace
fonctions d'autres champs ...
Functions
void erreur_champ_ (const char *nom_methode)
template<typename _TYPE_RETURN_ >
_TYPE_RETURN_ not_implemented_champ_ (const char *nom_methode)
Typedef Documentation
enable_if_t
template<bool B, typename T > using enable_if_t = typename std::enable_if<B, T>::type
classe Champ_Don_base
classe de base des Champs donnes (non calcules)
les proprietes physiques sont des Champs donnes
mais peuvent etre variables dans le temps dans l'espace
fonctions d'autres champs ...
Definition at line 34 of file Champ_Don_base.h.
Function Documentation
erreur_champ_()
void erreur_champ_ (const char * nom_methode) inline
Definition at line 68 of file Champ_Don_base.h.
{
  Cerr << "TRUST Error !!! Verify the method " << nom_methode << " !!!" << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
Referenced by TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >::mettre_a_jour_positions(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_compo(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_a_elem(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_a_elem_compo(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_compo_(), TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_(), Champ_som_lu::valeur_aux_elems(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), and TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_().
not_implemented_champ_()
template<typename _TYPE_RETURN_ > _TYPE_RETURN_ not_implemented_champ_ (const char * nom_methode) inline
Definition at line 75 of file Champ_Don_base.h.
{
  Cerr << "TRUST Error !!! The method " << nom_methode << " is not implemented !!!" << finl;
  throw;
}
References Cerr, and finl.