TRUST: src/Kernel/Champs_dis/Champ_implementation_P1.cpp File Reference
Champ_implementation_P1.cpp File Reference
#include <Champ_implementation_P1.h>
#include <Domaine.h>
#include <Octree_Double.h>
Functions
double coord_barycentrique_P1 (const IntTab &polys, const DoubleTab &coord, double x, double y, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y) par
rapport au sommet specifie d'un triangle ou d'un rectange (un element)
Ce calcul concerne un point 2D.
double coord_barycentrique_P1 (const IntTab &polys, const DoubleTab &coord, double x, double y, double z, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y,z) par
rapport au sommet specifie d'un tetraedre ou d'un hexaedre (un element)
Ce calcul concerne un point 3D.
Function Documentation
coord_barycentrique_P1() [1/2]
double coord_barycentrique_P1 (const IntTab & polys, const DoubleTab & coord, double x, double y, double z, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y,z) par
rapport au sommet specifie d'un tetraedre ou d'un hexaedre (un element)
Ce calcul concerne un point 3D.
Returns
double
Signification: la coordonnee barycentrique du point (x,y,z) par rapport
au sommet specifie (i) dans l'element specifie (le_poly)
Contraintes: 0 <= valeur <= 1
Definition at line 353 of file Champ_implementation_P1.cpp.
{
  int nb_som_elem = polys.dimension(1);
// Distinction du calcul de la coordonnee barycentrique en fonction du type de l element
// Cas Tetraedre
  if (nb_som_elem==4)
    return coord_barycentrique_P1_tetraedre(polys, coord, x, y, z, le_poly, i);
  else if (nb_som_elem==8)
    return coord_barycentrique_P1_hexaedre(polys, coord, x, y, z, le_poly, i);
  Cerr<<"The number of nodes by element " <<nb_som_elem<<" does not correspond to a treated situation in the coord_barycentrique_P1 function."<<finl;
  Process::exit();
  return 0.;
}
References Cerr, coord_barycentrique_P1_hexaedre(), coord_barycentrique_P1_tetraedre(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), and finl.
coord_barycentrique_P1() [2/2]
double coord_barycentrique_P1 (const IntTab & polys, const DoubleTab & coord, double x, double y, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y) par
rapport au sommet specifie d'un triangle ou d'un rectange (un element)
Ce calcul concerne un point 2D.
Returns
double
Signification: la coordonnee barycentrique du point (x,y) par rapport
au sommet specifie (i) dans l'element specifie (le_poly)
Contraintes: 0 <= valeur <= 1
Excpetion: un triangle n'a pas plus de 3 sommets
Excpetion: un rectangle n'a pas plus de 4 sommets
Definition at line 273 of file Champ_implementation_P1.cpp.
{
  int nb_som_elem = polys.dimension(1);
// Distinction du calcul de la coordonnee barycentrique en fonction du type de l element
// Cas Triangle
  if (nb_som_elem==3)
    return coord_barycentrique_P1_triangle(polys,coord,x,y,le_poly,i);
// Cas Rectangle
  else if (nb_som_elem==4)
    return coord_barycentrique_P1_rectangle(polys,coord,x,y,le_poly,i);
  Cerr<<"The number of nodes by element " <<nb_som_elem<<" does not correspond to a treated situation in the coord_barycentrique_P1 function."<<finl;
  Process::exit();
  return 0.;
}
References Cerr, coord_barycentrique_P1_rectangle(), coord_barycentrique_P1_triangle(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), and finl.