TRUST: src/Kernel/Champs_dis/Champ_implementation_P1.h File Reference
Champ_implementation_P1.h File Reference
#include <Champ_implementation_sommet_base.h>
#include <TRUSTTab.h>
Classes
class Champ_implementation_P1
Functions
double coord_barycentrique_P1 (const IntTab &polys, const DoubleTab &coord, double x, double y, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y) par
rapport au sommet specifie d'un triangle ou d'un rectange (un element)
Ce calcul concerne un point 2D.
double coord_barycentrique_P1 (const IntTab &polys, const DoubleTab &coord, double x, double y, double z, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y,z) par
rapport au sommet specifie d'un tetraedre ou d'un hexaedre (un element)
Ce calcul concerne un point 3D.
double coord_barycentrique_P1_triangle (const IntTab &polys, const DoubleTab &coord, double x, double y, int le_poly, int i)
double coord_barycentrique_P1_rectangle (const IntTab &polys, const DoubleTab &coord, double x, double y, int le_poly, int i)
double coord_barycentrique_P1_tetraedre (const IntTab &polys, const DoubleTab &coord, double x, double y, double z, int le_poly, int i)
double coord_barycentrique_P1_hexaedre (const IntTab &polys, const DoubleTab &coord, double x, double y, double z, int le_poly, int i)
Function Documentation
coord_barycentrique_P1() [1/2]
double coord_barycentrique_P1 (const IntTab & polys, const DoubleTab & coord, double x, double y, double z, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y,z) par
rapport au sommet specifie d'un tetraedre ou d'un hexaedre (un element)
Ce calcul concerne un point 3D.
Returns
double
Signification: la coordonnee barycentrique du point (x,y,z) par rapport
au sommet specifie (i) dans l'element specifie (le_poly)
Contraintes: 0 <= valeur <= 1
Definition at line 353 of file Champ_implementation_P1.cpp.
{
  int nb_som_elem = polys.dimension(1);
// Distinction du calcul de la coordonnee barycentrique en fonction du type de l element
// Cas Tetraedre
  if (nb_som_elem==4)
    return coord_barycentrique_P1_tetraedre(polys, coord, x, y, z, le_poly, i);
  else if (nb_som_elem==8)
    return coord_barycentrique_P1_hexaedre(polys, coord, x, y, z, le_poly, i);
  Cerr<<"The number of nodes by element " <<nb_som_elem<<" does not correspond to a treated situation in the coord_barycentrique_P1 function."<<finl;
  Process::exit();
  return 0.;
}
References Cerr, coord_barycentrique_P1_hexaedre(), coord_barycentrique_P1_tetraedre(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), and finl.
coord_barycentrique_P1() [2/2]
double coord_barycentrique_P1 (const IntTab & polys, const DoubleTab & coord, double x, double y, int le_poly, int i)
Calcule la coordonnee barycentrique d'un point (x,y) par
rapport au sommet specifie d'un triangle ou d'un rectange (un element)
Ce calcul concerne un point 2D.
Returns
double
Signification: la coordonnee barycentrique du point (x,y) par rapport
au sommet specifie (i) dans l'element specifie (le_poly)
Contraintes: 0 <= valeur <= 1
Excpetion: un triangle n'a pas plus de 3 sommets
Excpetion: un rectangle n'a pas plus de 4 sommets
Definition at line 273 of file Champ_implementation_P1.cpp.
{
  int nb_som_elem = polys.dimension(1);
// Distinction du calcul de la coordonnee barycentrique en fonction du type de l element
// Cas Triangle
  if (nb_som_elem==3)
    return coord_barycentrique_P1_triangle(polys,coord,x,y,le_poly,i);
// Cas Rectangle
  else if (nb_som_elem==4)
    return coord_barycentrique_P1_rectangle(polys,coord,x,y,le_poly,i);
  Cerr<<"The number of nodes by element " <<nb_som_elem<<" does not correspond to a treated situation in the coord_barycentrique_P1 function."<<finl;
  Process::exit();
  return 0.;
}
References Cerr, coord_barycentrique_P1_rectangle(), coord_barycentrique_P1_triangle(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), and finl.
coord_barycentrique_P1_hexaedre()
double coord_barycentrique_P1_hexaedre (const IntTab & polys, const DoubleTab & coord, double x, double y, double z, int le_poly, int i) inline
Definition at line 246 of file Champ_implementation_P1.h.
{
  assert(polys.dimension(1)==8);
  double alpha_x, alpha_y, alpha_z;
  switch(i)
    {
    case 0 :
      {
        alpha_x = -1.;
        alpha_y = -1.;
        alpha_z = -1.;
        break;
      }
    case 1 :
      {
        alpha_x = 1.;
        alpha_y = -1.;
        alpha_z = -1.;
        break;
      }
    case 2 :
      {
        alpha_x = -1.;
        alpha_y = 1.;
        alpha_z = -1.;
        break;
      }
    case 3 :
      {
        alpha_x = 1.;
        alpha_y = 1.;
        alpha_z = -1.;
        break;
      }
    case 4 :
      {
        alpha_x = -1.;
        alpha_y = -1;
        alpha_z = 1.;
        break;
      }
    case 5 :
      {
        alpha_x = 1.;
        alpha_y = -1.;
        alpha_z = 1.;
        break;
      }
    case 6 :
      {
        alpha_x = -1.;
        alpha_y = 1.;
        alpha_z = 1.;
        break;
      }
    case 7 :
      {
        alpha_x = 1.;
        alpha_y = 1.;
        alpha_z = 1.;
        break;
      }
    default :
      {
        alpha_x = 0;
        alpha_y = 0;
        alpha_z = 0;
        Cerr << "Error in Champ_P1::coord_barycentrique : " << finl;
        Process::exit();
      }
    }
  int som0=polys(le_poly , 0);
  int som1=polys(le_poly , 1);
  int som2=polys(le_poly , 2);
  int som3=polys(le_poly , 4);
  double delta_x = coord(som1,0)-coord(som0,0);
  double delta_y = coord(som2,1)-coord(som0,1);
  double delta_z = coord(som3,2)-coord(som0,2);
  double x0 = coord(som0,0)+delta_x/2.;
  double y0 = coord(som0,1)+delta_y/2.;
  double z0 = coord(som0,2)+delta_z/2.;
  double coord_bary = (1./8.)*(1.+2.*alpha_x*(x-x0)/delta_x)*(1.+2.*alpha_y*(y-y0)/delta_y)*(1.+2.*alpha_z*(z-z0)/delta_z);
#ifndef NDEBUG
  if ((coord_bary < -Objet_U::precision_geom) || (coord_bary > 1.+Objet_U::precision_geom))
    {
      Cerr << "WARNING: The barycentric coordinate of point :" << finl;
      Cerr << "x= " << x << " y=" << y <<" z="<< z <<finl;
      Cerr << "is not between 0 and 1 : " << coord_bary << finl;
      Cerr << "On the element " << le_poly << " of the processor " << Process::me() << finl;
    }
#endif
  return coord_bary;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Process::me(), and Objet_U::precision_geom.
Referenced by coord_barycentrique_P1().
coord_barycentrique_P1_rectangle()
double coord_barycentrique_P1_rectangle (const IntTab & polys, const DoubleTab & coord, double x, double y, int le_poly, int i) inline
Definition at line 102 of file Champ_implementation_P1.h.
{
  assert(polys.dimension(1)==4);
  double alpha_x, alpha_y;
  switch(i)
    {
    case 0 :
      {
        alpha_x = -1.;
        alpha_y = -1;
        break;
      }
    case 1 :
      {
        alpha_x = 1.;
        alpha_y = -1.;
        break;
      }
    case 2 :
      {
        alpha_x = -1.;
        alpha_y = 1.;
        break;
      }
    case 3 :
      {
        alpha_x = 1.;
        alpha_y = 1.;
        break;
      }
    default :
      {
        alpha_x = 0;
        alpha_y = 0;
        Cerr << "Error in Champ_P1::coord_barycentrique : " << finl;
        Process::exit();
      }
    }
  int som0=polys(le_poly , 0);
  int som1=polys(le_poly , 1);
  int som2=polys(le_poly , 2);
  double delta_x = coord(som1,0)-coord(som0,0);
  double delta_y = coord(som2,1)-coord(som0,1);
  double x0 = coord(som0,0)+delta_x/2.;
  double y0 = coord(som0,1)+delta_y/2.;
  double coord_bary = 0.25*(1.+2.*alpha_x*(x-x0)/delta_x)*(1.+2.*alpha_y*(y-y0)/delta_y);
#ifndef NDEBUG
  if ((coord_bary < -Objet_U::precision_geom) || (coord_bary > 1.+Objet_U::precision_geom))
    {
      Cerr << "WARNING: The barycentric coordinate of point :" << finl;
      Cerr << "x= " << x << " y=" << y << finl;
      Cerr << "is not between 0 and 1 : " << coord_bary << finl;
      Cerr << "On the element " << le_poly << " of the processor " << Process::me() << finl;
    }
#endif
  return coord_bary;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Process::me(), and Objet_U::precision_geom.
Referenced by coord_barycentrique_P1().
coord_barycentrique_P1_tetraedre()
double coord_barycentrique_P1_tetraedre (const IntTab & polys, const DoubleTab & coord, double x, double y, double z, int le_poly, int i) inline
Definition at line 163 of file Champ_implementation_P1.h.
{
  int som0,som1,som2,som3;
  assert(polys.dimension(1)==4);
  switch(i)
    {
    case 0 :
      {
        som0=polys(le_poly , 0);
        som1=polys(le_poly , 1);
        som2=polys(le_poly , 2);
        som3=polys(le_poly , 3);
        break;
      }
    case 1 :
      {
        som0=polys(le_poly , 1);
        som1=polys(le_poly , 2);
        som2=polys(le_poly , 3);
        som3=polys(le_poly , 0);
        break;
      }
    case 2 :
      {
        som0=polys(le_poly , 2);
        som1=polys(le_poly , 3);
        som2=polys(le_poly , 0);
        som3=polys(le_poly , 1);
        break;
      }
    case 3 :
      {
        som0=polys(le_poly , 3);
        som1=polys(le_poly , 0);
        som2=polys(le_poly , 1);
        som3=polys(le_poly , 2);
        break;
      }
    default :
      {
        som0=-1;
        som1=-1;
        som2=-1;
        som3=-1;
        Cerr << "Error in Champ_P1::coord_barycentrique : " << finl;
        Cerr << "A tetrahedron does not have " << i << "nodes " << finl;
        Process::exit();
      }
    }
  double xp = (coord(som2,1)-coord(som1,1))*(coord(som0,2)-coord(som1,2))
              - (coord(som2,2)-coord(som1,2))*(coord(som0,1)-coord(som1,1));
  double yp = (coord(som2,2)-coord(som1,2))*(coord(som0,0)-coord(som1,0))
              - (coord(som2,0)-coord(som1,0))*(coord(som0,2)-coord(som1,2));
  double zp = (coord(som2,0)-coord(som1,0))*(coord(som0,1)-coord(som1,1))
              - (coord(som2,1)-coord(som1,1))*(coord(som0,0)-coord(som1,0));
  double den = xp * (coord(som3,0)-coord(som1,0))
               + yp * (coord(som3,1)-coord(som1,1))
               + zp * (coord(som3,2)-coord(som1,2));
  xp = (coord(som2,1)-coord(som1,1))*(z-coord(som1,2))
       - (coord(som2,2)-coord(som1,2))*(y-coord(som1,1));
  yp = (coord(som2,2)-coord(som1,2))*(x-coord(som1,0))
       - (coord(som2,0)-coord(som1,0))*(z-coord(som1,2));
  zp = (coord(som2,0)-coord(som1,0))*(y-coord(som1,1))
       - (coord(som2,1)-coord(som1,1))*(x-coord(som1,0));
  double num = xp * (coord(som3,0)-coord(som1,0))
               + yp * (coord(som3,1)-coord(som1,1))
               + zp * (coord(som3,2)-coord(som1,2));
  assert (den != 0.);
  double coord_bary = num/den;
#ifndef NDEBUG
  if ((coord_bary < -Objet_U::precision_geom) || (coord_bary > 1.+Objet_U::precision_geom))
    {
      Cerr << "WARNING: The barycentric coordinate of point :" << finl;
      Cerr << "x= " << x << " y=" << y << " z=" << z << finl;
      Cerr << "is not between 0 and 1 : " << coord_bary << finl;
      Cerr << "On the element " << le_poly << " of the processor " << Process::me() << finl;
    }
#endif
  return coord_bary;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Process::me(), and Objet_U::precision_geom.
Referenced by Champ_P1NC_implementation::coord_barycentrique(), coord_barycentrique_P1(), Champ_P1NC_implementation::fonction_forme_3D(), and Champ_P1iP1B_implementation::valeur_aux_elems().
coord_barycentrique_P1_triangle()
double coord_barycentrique_P1_triangle (const IntTab & polys, const DoubleTab & coord, double x, double y, int le_poly, int i) inline
Definition at line 46 of file Champ_implementation_P1.h.
{
  assert(polys.dimension(1)==3);
  int som0 ,som1,som2;
  switch(i)
    {
    case 0 :
      {
        som0=polys(le_poly , 0);
        som1=polys(le_poly , 1);
        som2=polys(le_poly , 2);
        break;
      }
    case 1 :
      {
        som0=polys(le_poly , 1);
        som1=polys(le_poly , 2);
        som2=polys(le_poly , 0);
        break;
      }
    case 2 :
      {
        som0=polys(le_poly , 2);
        som1=polys(le_poly , 0);
        som2=polys(le_poly , 1);
        break;
      }
    default :
      {
        som0=-1;
        som1=-1;
        som2=-1;
        Cerr << "A triangle does not have " << i << " nodes in Champ_P1::coord_barycentrique." << finl;
        Process::exit();
      }
    }
  double den = (coord(som2,0)-coord(som1,0))*(coord(som0,1)-coord(som1,1))
               - (coord(som2,1)-coord(som1,1))*(coord(som0,0)-coord(som1,0));
  double num = (coord(som2,0)-coord(som1,0))*(y-coord(som1,1))
               - (coord(som2,1)-coord(som1,1))*(x-coord(som1,0));
  assert (den != 0.);
  double coord_bary=num/den;
#ifndef NDEBUG
  if ((coord_bary < -Objet_U::precision_geom) || (coord_bary > 1.+Objet_U::precision_geom))
    {
      Cerr << "WARNING: The barycentric coordinate of point :" << finl;
      Cerr << "x= " << x << " y=" << y << finl;
      Cerr << "is not between 0 and 1 : " << coord_bary << finl;
      Cerr << "On the element " << le_poly << " of the processor " << Process::me() << finl;
    }
#endif
  return coord_bary;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Process::me(), and Objet_U::precision_geom.
Referenced by Champ_P1NC_implementation::coord_barycentrique(), coord_barycentrique_P1(), Champ_P1NC_implementation::fonction_forme_2D(), and Champ_P1iP1B_implementation::valeur_aux_elems().