TRUST: src/VDF/Champs/Champ_Face.h File Reference
src/VDF/Champs/Champ_Face.h File Reference
#include <Champ_Inc_base.h>
#include <Ref_Zone_VDF.h>
#include <Champ_Face_implementation.h>
Classes
class Champ_Face
class Champ_Face
Cette classe sert a representer un champ vectoriel dont on ne calcule
que les composantes normales aux faces.Il n'y a donc qu'un degre de
liberte par face et l'attribut nb_comp_ d'un objet de type Champ_Face
vaut 1. On peut neammoins imposer toutes les composantes du champ sur
le bord. Si n est le nombre de faces total de la zone et nb_faces_bord
le nombre de faces de bord le tableau de valeurs associe au champ
est construit comme suit:
- n valeurs pour representer les composantes normales aux faces
- nb_faces_bord*dimension pour stocker les valeurs imposees
sur les faces de bord
Rq : cette classe est specifique au module VDF
Functions
double Champ_Face_get_val_imp_face_bord (const double &temp, int face, int comp, const Zone_Cl_VDF &zclo)
double Champ_Face_get_val_imp_face_bord (const double &temp, int face, int comp, int comp2, const Zone_Cl_VDF &zclo)
double Champ_Face_get_val_imp_face_bord_sym (const DoubleTab &tab_valeurs, const double &temp, int face, int comp, const Zone_Cl_VDF &zclo)
int Champ_Face_test ()
Function Documentation
double Champ_Face_get_val_imp_face_bord (const double & temp, int face, int comp, const Zone_Cl_VDF & zclo)
< Maintenant numero dans le tableau global des faces.
< All other cases
Definition at line 324 of file Champ_Face.cpp.
References Cerr, Cond_lim_base::champ_front(), Zone_Cl_dis_base::condition_limite_de_la_face_reelle(), Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle(), DoubleTab::dimension(), Process::exit(), finl, Zone_VF::nb_faces(), Zone_VDF::orientation(), Zone_VF::premiere_face_bord(), sub_type, and Zone_Cl_VDF::zone_VDF().
Referenced by Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Diff_VDF_var_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter_bord(), Op_Dift_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), Eval_Amont_VDF_Face::flux_arete_coin_fluide(), Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_fluide(), Eval_Quick_VDF_Face::flux_arete_fluide(), Eval_Centre_VDF_Face::flux_arete_fluide(), Eval_centre4_VDF_Face::flux_arete_fluide(), Eval_Amont_VDF_Face::flux_arete_fluide(), Eval_Quick_VDF_Face_Axi::flux_arete_fluide(), Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi(), Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi_fluide(), Eval_Quick_VDF_Face::flux_arete_paroi_fluide(), Eval_Centre_VDF_Face::flux_arete_paroi_fluide(), Eval_centre4_VDF_Face::flux_arete_paroi_fluide(), Eval_Amont_VDF_Face::flux_arete_paroi_fluide(), Eval_Quick_VDF_Face_Axi::flux_arete_paroi_fluide(), Eval_Quick_VDF_Face::flux_arete_symetrie_fluide(), Eval_Centre_VDF_Face::flux_arete_symetrie_fluide(), Eval_centre4_VDF_Face::flux_arete_symetrie_fluide(), Eval_Amont_VDF_Face::flux_arete_symetrie_fluide(), Eval_Amont_VDF_Face::secmem_arete_coin_fluide(), Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_fluide(), Eval_Amont_VDF_Face::secmem_arete_fluide(), Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi(), Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi_fluide(), Eval_Amont_VDF_Face::secmem_arete_paroi_fluide(), Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie_fluide(), Eval_Amont_VDF_Face::secmem_arete_symetrie_fluide(), and Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie_paroi().
{
  const Zone_VDF& zone_vdf=zclo.zone_VDF();
  int face_globale,face_locale;
  face_globale=face+zone_vdf.premiere_face_bord(); //!< Maintenant numero dans le tableau global des faces.
  const Zone_Cl_dis_base& zcl = zclo; //equation().zone_Cl_dis().valeur();
// On recupere la CL associee a la face et le numero local de la face dans la frontiere.
// assert(equation().zone_Cl_dis().valeur()==zclo);
  const Cond_lim_base& cl=(face<zone_vdf.nb_faces()) ?
                          zcl.condition_limite_de_la_face_reelle(face_globale,face_locale) :
                          zcl.condition_limite_de_la_face_virtuelle(face_globale,face_locale);
  int ori = zone_vdf.orientation()(face_globale);
  const DoubleTab& vals=cl.champ_front()->valeurs_au_temps(temp);
  int face_de_vals=vals.dimension(0)==1 ? 0 : face_locale;
  if(sub_type(Symetrie,cl))
    {
      if (comp == ori)
        return 0;
      else
        {
          Cerr<<"You should call Champ_Face_get_val_imp_face_bord_sym and not  Champ_Face_get_val_imp_face_bord"<<finl;
          Process::exit();
          return 1e9;
        }
    }
  else if ( sub_type(Dirichlet_entree_fluide,cl) )
    {
      return vals(face_de_vals,comp);
    }
  else if ( sub_type(Dirichlet_paroi_fixe,cl) )
    {
      return 0;
    }
  else if ( sub_type(Dirichlet_paroi_defilante,cl) )
    {
      return vals(face_de_vals,comp);
    }
  return 0; //!< All other cases
}
double Champ_Face_get_val_imp_face_bord (const double & temp, int face, int comp, int comp2, const Zone_Cl_VDF & zclo)
< For compilers
Definition at line 443 of file Champ_Face.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Champ_Face::val_imp_face_bord(,,) exit" << finl;
  Process::exit();
  return 0; //!< For compilers
}
double Champ_Face_get_val_imp_face_bord_sym (const DoubleTab & tab_valeurs, const double & temp, int face, int comp, const Zone_Cl_VDF & zclo)
< Maintenant numero dans le tableau global des faces.
< All other cases
Definition at line 374 of file Champ_Face.cpp.
References Cond_lim_base::champ_front(), Zone_Cl_dis_base::condition_limite_de_la_face_reelle(), Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Objet_U::dimension, DoubleTab::dimension(), Zone_VF::elem_faces(), Zone_VF::face_voisins(), Zone_VF::nb_faces(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_bord(), sub_type, and Zone_Cl_VDF::zone_VDF().
Referenced by Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie_fluide(), Eval_Quick_VDF_Face::flux_arete_symetrie_fluide(), Eval_Centre_VDF_Face::flux_arete_symetrie_fluide(), Eval_centre4_VDF_Face::flux_arete_symetrie_fluide(), Eval_Amont_VDF_Face::flux_arete_symetrie_fluide(), Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie_paroi(), and Champ_Face::val_imp_face_bord_private().
{
  const Zone_VDF& zone_vdf=zclo.zone_VDF();
  int face_globale,face_locale;
  face_globale=face+zone_vdf.premiere_face_bord(); //!< Maintenant numero dans le tableau global des faces.
  const Zone_Cl_dis_base& zcl = zclo; //equation().zone_Cl_dis().valeur();
// On recupere la CL associee a la face et le numero local de la face dans la frontiere.
// assert(equation().zone_Cl_dis().valeur()==zclo);
  const Cond_lim_base& cl=(face<zone_vdf.nb_faces()) ?
                          zcl.condition_limite_de_la_face_reelle(face_globale,face_locale) :
                          zcl.condition_limite_de_la_face_virtuelle(face_globale,face_locale);
  const IntTab& face_voisins = zone_vdf.face_voisins();
  const IntTab& elem_faces = zone_vdf.elem_faces();
  const DoubleVect& porosite = zone_vdf.porosite_face();
  int ori = zone_vdf.orientation()(face_globale);
  const DoubleTab& vals=cl.champ_front()->valeurs_au_temps(temp);
  int face_de_vals=vals.dimension(0)==1 ? 0 : face_locale;
  if(sub_type(Symetrie,cl))
    {
      if (comp == ori)
        return 0;
      else
        {
          int elem=0;
          if (face_voisins(face_globale,0) != -1)
            elem = face_voisins(face_globale,0);
          else
            elem = face_voisins(face_globale,1);
          int comp2=comp+Objet_U::dimension;
          return (tab_valeurs(elem_faces(elem,comp))*porosite[elem_faces(elem,comp)]
                  + tab_valeurs(elem_faces(elem,comp2))*porosite[elem_faces(elem,comp2)])
                 /    (porosite[elem_faces(elem,comp)] + porosite[elem_faces(elem,comp2)]) ;
        }
    }
  else if ( sub_type(Dirichlet_entree_fluide,cl) )
    {
      return vals(face_de_vals,comp);
    }
  else if ( sub_type(Dirichlet_paroi_fixe,cl) )
    {
      return 0;
    }
  else if ( sub_type(Dirichlet_paroi_defilante,cl) )
    {
      return vals(face_de_vals,comp);
    }
  return 0; //!< All other cases
}
int Champ_Face_test ()