TRUST: src/Kernel/Framework/Champ_front_instationnaire_base.cpp File Reference
Champ_front_instationnaire_base.cpp File Reference
#include <Champ_front_instationnaire_base.h>
Functions
void print (const Roue_ptr &les_valeurs)
Variables
const Type_info * Champ_front_instationnaire_basebases [1] ={ &(Champ_front_base ::info_obj)}
Function Documentation
print()
void print (const Roue_ptr & les_valeurs) inline
Definition at line 87 of file Champ_front_instationnaire_base.cpp.
{
  Cerr << "The times available are :" << finl;
  for(int i=1; i<les_valeurs->nb_cases(); i++)
    Cerr << "  " << les_valeurs[i].temps() << finl;
}
References Cerr, finl, and Roue::nb_cases().
Referenced by Champ_front_instationnaire_base::avancer(), Champ_front_instationnaire_base::reculer(), and Champ_front_instationnaire_base::valeurs_au_temps().
Variable Documentation
Champ_front_instationnaire_basebases
const Type_info* Champ_front_instationnaire_basebases[1] ={ &(Champ_front_base ::info_obj)}
Definition at line 18 of file Champ_front_instationnaire_base.cpp.