TRUST: src/Kernel/Champs/Champ_Generique_Transformation.cpp File Reference
src/Kernel/Champs/Champ_Generique_Transformation.cpp File Reference
#include <Champ_Generique_Transformation.h>
#include <Probleme_base.h>
#include <Zone_VF.h>
#include <DoubleTabs.h>
#include <Champ_Fonc.h>
#include <Champ_Inc.h>
#include <Discretisation_base.h>
#include <Interprete.h>
#include <Equation_base.h>
#include <Entree_complete.h>
#include <Milieu_base.h>
#include <Postraitement.h>
#include <Synonyme_info.h>
#include <Param.h>
#include <Linear_algebra_tools_impl.h>
#include <MD_Vector.h>
#include <MD_Vector_composite.h>
#include <Zone_dis_base.h>
Functions
void projette (DoubleTab &valeurs_espace, const DoubleTab &val_source, const Zone_VF &zvf, const Motcle &loc, bool champ_normal_faces)
Variables
const Type_info * Champ_Generique_Transformationbases [1] = { &(Champ_Gen_de_Champs_Gen ::info_obj)}
const Synonyme_info synonym_Champ_Generique_Transformation__LINE__ ("Champ_Post_Transformation", Champ_Generique_Transformation::info_obj.name())
Function Documentation
void projette (DoubleTab & valeurs_espace, const DoubleTab & val_source, const Zone_VF & zvf, const Motcle & loc, bool champ_normal_faces)
Definition at line 456 of file Champ_Generique_Transformation.cpp.
References Cerr, Domaine::coord_sommets(), Objet_U::dimension, DoubleTab::dimension(), Zone::domaine(), Process::exit(), finl, Zone::les_elems(), Zone_dis_base::nb_elem(), Vecteur3::produit_scalaire(), Vecteur3::produit_vectoriel(), Objet_U::que_suis_je(), Vecteur3::set(), Zone::type_elem(), type_elem(), Deriv_Elem_geom_base::valeur(), and Zone_dis_base::zone().
Referenced by contribuer_matrice_SymetrieP1P1(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), Champ_Generique_Transformation::get_champ(), update_matrice_SymetrieP1P1(), update_matrice_SymetrieP1Pa(), and update_matrice_SymetriePaPa().
{
  const Nom& type_elem=zvf.zone().type_elem().valeur().que_suis_je();
  if ((champ_normal_faces)||(loc!="elem")|| (type_elem!="Quadrangle"))
    {
      Cerr<<"option composante_normale not coded in this case"<<finl;
      Process::exit();
    }
  const DoubleTab& coord=zvf.zone().domaine().coord_sommets();
  const IntTab& elems=zvf.zone().les_elems();
  int nb_v= valeurs_espace.dimension(0);
  assert(nb_v==zvf.nb_elem());
  assert(val_source.dimension(1)==Objet_U::dimension);
  for (int i=0; i<nb_v; i++)
    {
      Vecteur3 v1,v2,normal,val;
      int s0=elems(i,0);
      int s1=elems(i,1);
      int s2=elems(i,2);
      if (Objet_U::dimension!=3)
        {
          Cerr<<"not implemented "<<finl;
          assert(0);
          Process::exit();
        }
      v1.set(coord(s1,0)-coord(s0,0),coord(s1,1)-coord(s0,1),coord(s1,2)-coord(s0,2));
      v2.set(coord(s2,0)-coord(s0,0),coord(s2,1)-coord(s0,1),coord(s2,2)-coord(s0,2));
      val.set(val_source(i,0),val_source(i,1),val_source(i,2));
      Vecteur3::produit_vectoriel(v1,v2,normal);
      double norm=Vecteur3::produit_scalaire(normal,normal);
      double inv=1./sqrt(norm);
      normal*=inv;
      double prod_scal= Vecteur3::produit_scalaire(normal,val);
      valeurs_espace(i)=prod_scal;
    }
}
Variable Documentation
const Type_info* Champ_Generique_Transformationbases[1] = { &(Champ_Gen_de_Champs_Gen ::info_obj)}
Definition at line 43 of file Champ_Generique_Transformation.cpp.
const Synonyme_info synonym_Champ_Generique_Transformation__LINE__("Champ_Post_Transformation", Champ_Generique_Transformation::info_obj.name())