TRUST: src/VEF/Champs/Champ_P1NC_implementation.cpp File Reference
src/VEF/Champs/Champ_P1NC_implementation.cpp File Reference
#include <Champ_P1NC_implementation.h>
#include <Champ_P1NC.h>
#include <Champ_Fonc_P1NC.h>
#include <Domaine.h>
#include <LecFicDiffuse.h>
#include <DoubleLists.h>
#include <Periodique.h>
#include <Debog.h>
#include <Solv_GCP.h>
#include <SSOR.h>
#include <Equation_base.h>
#include <Mod_turb_hyd_base.h>
#include <Dirichlet_paroi_fixe.h>
#include <Dirichlet_paroi_defilante.h>
#include <distances_VEF.h>
#include <Matrice_Bloc.h>
#include <IntLists.h>
Functions
DoubleTab & valeur_P1_L2 (Champ_P1NC &cha, const Domaine &dom)
Projection du champ P1NC "cha" sur l'espace des champs P1.
Le resultat est stocke dans cha.ch_som() et renvoye (valeur de retour)
Voir note technique 2006/010 de Patrick Quemere "Nouvelle approche VEF pour la LES...".
Voir aussi "What is in TRUST" : Scales_Separation_P1_P1NC.
DoubleTab & valeur_P1_L2 (Champ_Fonc_P1NC &cha, const Domaine &dom)
DoubleTab & valeur_P1_H1 (const Champ_P1NC &cha, const Domaine &dom, DoubleTab &ch_som)
Variables
static int methode_calcul_valeurs_sommets = 2
static const double coeff_penalisation = 1e9
Function Documentation
DoubleTab& valeur_P1_H1 (const Champ_P1NC & cha, const Domaine & dom, DoubleTab & ch_som)
Definition at line 716 of file Champ_P1NC_implementation.cpp.
References coeff, Matrice_Morse_Sym::compacte(), Objet_U::dimension, DoubleTab::dimension(), Matrice_Morse::dimensionner(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Champ_P1NC_implementation::MatP1NC2P1_H1, Process::mp_min(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Matrice_Morse::nb_lignes(), Zone::nb_som(), Zone::nb_som_elem(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), Entree_Fichier_base::ouvrir(), ref_cast, ref_cast_non_const, Matrice_Morse::remplir(), SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), Champ_P1NC_implementation::solveur_H1, Deriv_Zone_Cl_dis_base::valeur(), Champ_P1NC::valeur_a_sommet_compo(), Champ_Inc_base::valeurs(), Zone_VF::volumes(), Domaine::zone(), Equation_base::zone_Cl_dis(), and Champ_P1NC::zone_vef().
{
  const Zone& zone = dom.zone(0);
  int nb_elem_tot = zone.nb_elem_tot();
  int nb_som = zone.nb_som();
  int nb_som_elem = zone.nb_som_elem();
  const DoubleTab& ch = cha.valeurs();
  const Zone_VEF& zone_VEF = cha.zone_vef();
  const DoubleTab& normales=zone_VEF.face_normales();
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF, cha.equation().zone_Cl_dis().valeur());
  const IntTab& elem_som = zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  double mijK;
  int nb_comp=ch_som.dimension(1);
  int dimension=Objet_U::dimension;
  if(dimension==2)
    {
      mijK=1./4.;
    }
  else
    {
      mijK=1./9.;
    }
  int elem;
  int n_bord;
  static double diag_ref;
  double non_prepare=0;
  if ( cha.MatP1NC2P1_H1.nb_lignes() <2 )
    non_prepare=1;
  non_prepare=Process::mp_min(non_prepare);
  if (non_prepare==1)
    {
      EFichier fic;
      if(fic.ouvrir("solveur.bar"))
        {
          SolveurSys& solv=ref_cast_non_const(SolveurSys,cha.solveur_H1);
          fic >> solv;
        }
      Matrice_Morse_Sym& mat=ref_cast_non_const(Matrice_Morse_Sym,cha.MatP1NC2P1_H1);
      int rang;
      int nnz=0;
      IntLists voisins(nb_som);
      DoubleLists coeffs(nb_som);
      DoubleVect diag(nb_som);
      for (elem=0; elem<nb_elem_tot; elem++)
        {
          double volume=zone_VEF.volumes(elem);
          for (int isom=0; isom<nb_som_elem; isom++)
            {
              int facei=elem_faces(elem,isom);
              int i=dom.get_renum_som_perio(elem_som(elem,isom));
              for (int jsom=isom+1; jsom<nb_som_elem; jsom++)
                {
                  int facej=elem_faces(elem,jsom);
                  int j=dom.get_renum_som_perio(elem_som(elem,jsom));
                  double coeffij=0.0;
                  for(int k=0; k<dimension; k++)
                    coeffij+=normales(facei,k)*normales(facej,k);
                  coeffij*=zone_VEF.oriente_normale(facei,elem)*
                           zone_VEF.oriente_normale(facej,elem);
                  coeffij*=mijK/volume;
                  int ii=i, jj=j;
                  if(ii>jj)
                    {
                      int tmp=ii;
                      ii=jj;
                      jj=tmp;
                    }
                  rang=voisins[ii].rang(jj);
                  if(rang==-1)
                    {
                      voisins[ii].add(jj);
                      coeffs[ii].add(coeffij);
                      nnz++;
                    }
                  else
                    {
                      coeffs[ii][rang]+=coeffij;
                    }
                  diag[ii]-=coeffij;
                  diag[jj]-=coeffij;
                }
            }
        }
      diag_ref=diag(0);
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
// for n_bord
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (int face=num1; face<num2; face++)
            {
              elem=zone_VEF.face_voisins(face,0);
              for(int isom=0; isom<dimension; isom++)
                {
                  int som=zone_VEF.face_sommets(face,isom);
                  som=dom.get_renum_som_perio(som);
                  diag[som]=1.e1*diag_ref;
                }
            }
        }
      mat.dimensionner(nb_som, nnz+nb_som) ;
      mat.remplir(voisins, coeffs, diag) ;
      mat.compacte() ;
      mat.set_est_definie(1);
// Cerr << "Matrice de filtrage OK" << finl;
// Cerr << "Matrice de Laplacien P1 : " << finl;
// mat.imprimer(Cerr) << finl;
    }
  double coeff=-1./dimension;
  int k;
  for(int comp=0; comp<nb_comp; comp++)
    {
// for comp
      DoubleVect secmem(nb_som);
      DoubleVect solution(nb_som);
      for (elem=0; elem<nb_elem_tot; elem++)
        {
// for elem
          double volume=zone_VEF.volumes(elem);
          for (int isom=0; isom<nb_som_elem; isom++)
            {
              int facei=elem_faces(elem,isom);
              int i=dom.get_renum_som_perio(elem_som(elem,isom));
              for (int jsom=0; jsom<nb_som_elem; jsom++)
                {
                  int facej=elem_faces(elem,jsom);
                  double coeffij=0;
                  for(k=0; k<dimension; k++)
                    coeffij+=normales(facei,k)*normales(facej,k);
                  coeffij*=zone_VEF.oriente_normale(facei,elem)*
                           zone_VEF.oriente_normale(facej,elem);
                  coeffij*=coeff/volume;
                  secmem(i)+=coeffij*ch(facej,comp);
                }
            }
        }
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
// for n_bord
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (int face=num1; face<num2; face++)
            {
              elem=zone_VEF.face_voisins(face,0);
              for(int isom=0; isom<dimension; isom++)
                {
                  int som=zone_VEF.face_sommets(face,isom);
                  som=dom.get_renum_som_perio(som);
                  secmem(som)=1.e1*diag_ref* cha.valeur_a_sommet_compo(som, elem, comp);
                }
            }
        }
      SolveurSys& solv=ref_cast_non_const(SolveurSys,cha.solveur_H1);
      solv.resoudre_systeme(cha.MatP1NC2P1_H1, secmem, solution);
      for(int som=0; som<nb_som; som++)
        ch_som(som,comp)=solution(dom.get_renum_som_perio(som));
    }
  return ch_som;
}
DoubleTab& valeur_P1_L2 (Champ_P1NC & cha, const Domaine & dom)
Projection du champ P1NC "cha" sur l'espace des champs P1.
Le resultat est stocke dans cha.ch_som() et renvoye (valeur de retour)
Voir note technique 2006/010 de Patrick Quemere "Nouvelle approche VEF pour la LES...".
Voir aussi "What is in TRUST" : Scales_Separation_P1_P1NC.
Definition at line 76 of file Champ_P1NC_implementation.cpp.
References Cerr, Champ_P1NC_implementation::ch_som(), Champ_P1NC_implementation::ch_som_vect(), coeff, coeff_penalisation, Matrice_Morse_Sym::compacte(), Objet_U::dimension, Matrice_Morse::dimensionner(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), DoubleVect::echange_espace_virtuel(), IntVect::echange_espace_virtuel(), MorEqn::equation(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), Lec_Diffuse_base::good(), Field_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), DoubleVect::line_size(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Champ_P1NC_implementation::MatP1NC2P1_L2, Champ_P1NC_implementation::MatP1NC2P1_L2_Parallele, Process::me(), Process::mp_min(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Matrice_Morse::nb_lignes(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), Zone::nb_som_tot(), Front_VF::num_face(), LecFicDiffuse::ouvrir(), Zone_VF::premiere_face_int(), ref_cast, Matrice_Morse::remplir(), SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), Champ_P1NC_implementation::solveur_L2, sub_type, Deriv_Matrice_Base::valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Champ_Inc_base::valeurs(), Debog::verifier(), Zone_VF::volumes(), Domaine::zone(), Equation_base::zone_Cl_dis(), and Champ_P1NC::zone_vef().
{
  const Zone& mazone = dom.zone(0);
  int nb_elem_tot = mazone.nb_elem_tot();
  int nb_som = mazone.nb_som_tot();
  int nb_som_elem = mazone.nb_som_elem();
  const DoubleTab& ch = cha.valeurs();
  const Zone_VEF& zone_VEF = cha.zone_vef();
  const Zone_Cl_VEF& zone_Cl_VEF = ref_cast(Zone_Cl_VEF, cha.equation().zone_Cl_dis().valeur());
  const IntTab& elem_som = mazone.les_elems();
  double mijK, miiK;
  DoubleTab& vit_som=cha.ch_som();
  int n_bord, nb_comp=vit_som.line_size();
  DoubleTab secmem(cha.ch_som());
  secmem=0.;
// vit_som=0.; // PQ : 06/10/04 : dans la resolution du systeme, "solution" repart de vit_som=cha.ch_som()
// pour s'affranchir de recalculer u_bar lors d'un double appel a filtrer_L2
  if(Objet_U::dimension==2)
    {
      mijK=1./12.;
      miiK= 1./6.;
    }
  else
    {
      mijK=1./18.;
      miiK= 1./12.;
    }
// dans le cas d'une zone nulle on doit effectuer le dimensionnement
// mais une seule fois
  double non_prepare=0;
  if (cha.MatP1NC2P1_L2.nb_lignes() <2)
    non_prepare=1;
  non_prepare=Process::mp_min(non_prepare);
  if (non_prepare==1)
    {
// Initialisation du solveur
      SolveurSys& solv=ref_cast(SolveurSys, (cha.solveur_L2));
      LecFicDiffuse fic;
      fic.ouvrir("solveur.bar");
      if(fic.good())
        {
          fic >> solv;
          Cerr << Process::me() << "solveur.bar ouvert pour lire: " << solv << finl;
        }
      solv->reinit();
      Cerr<<"On remplit la matrice cha.MatP1NC2P1_L2 pour le champ "<< cha.le_nom() <<finl;
      Matrice_Morse_Sym& mat=ref_cast(Matrice_Morse_Sym, (cha.MatP1NC2P1_L2));
      int rang;
      int nnz=0;
      IntLists voisins(nb_som);
      DoubleLists coeffs(nb_som);
      DoubleVect diag(nb_som);
      int elem;
      for (elem=0; elem<nb_elem_tot; elem++)
        {
          double coeff_ij=mijK*zone_VEF.volumes(elem);
          double coeff_ii=miiK*zone_VEF.volumes(elem);
          for (int isom=0; isom<nb_som_elem; isom++)
            {
              int som=elem_som(elem,isom);
              int ii=dom.get_renum_som_perio(som);
              diag[ii]+=coeff_ii;
              for (int jsom=isom+1; jsom<nb_som_elem; jsom++)
                {
                  int asom=elem_som(elem,jsom);
                  int j=dom.get_renum_som_perio(asom);
                  int i=ii;
                  if(i>j)
                    {
                      int k=j;
                      j=i;
                      i=k;
                    }
                  rang=voisins[i].rang(j);
                  if(rang==-1)
                    {
                      voisins[i].add(j);
                      coeffs[i].add(coeff_ij);
                      nnz++;
                    }
                  else
                    {
                      coeffs[i][rang]+=coeff_ij;
                    }
                }
            }
        }
// PQ : pour le remplissage des coefficients de la matrice specifiques au CL Dirichlet,
// on commence par traiter les conditions Dirichlet, PUIS Dirichlet_homogene pour s'assurer
// de l'"adherence" des points sommets appartenant aux deux types de CL (aretes de bords)
      IntVect test_cl_imposee(nb_som);
      test_cl_imposee = 0;
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
// for n_bord
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int face;
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
// if (sub_type(Dirichlet,la_cl.valeur()))
          if (!sub_type(Periodique,la_cl.valeur()))
            {
              for (int ind_face=num1; ind_face<num2; ind_face++)
                {
                  face = le_bord.num_face(ind_face);
                  for(int isom=0; isom<Objet_U::dimension; isom++)
                    {
                      int som=zone_VEF.face_sommets(face,isom);
                      som=dom.get_renum_som_perio(som);
                      if (test_cl_imposee(som) == 0)
                        diag[som] = 0;
                      diag[som] += coeff_penalisation;
                      test_cl_imposee(som) += 1;
                    }
                }
            }
        }//for n_bord
      test_cl_imposee = 0;
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
// for n_bord
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int face;
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
          if (  sub_type(Dirichlet_homogene,la_cl.valeur()) )
            {
              for (int ind_face=num1; ind_face<num2; ind_face++)
                {
                  face = le_bord.num_face(ind_face);
                  for(int isom=0; isom<Objet_U::dimension; isom++)
                    {
                      int som=zone_VEF.face_sommets(face,isom);
                      som=dom.get_renum_som_perio(som);
                      if (test_cl_imposee(som) == 0)
                        diag[som] = 0;
                      diag[som] += coeff_penalisation;
                      test_cl_imposee(som) += 1;
                    }
                }
            }
        }//for n_bord
      {
        for (int i=0; i<nb_som; i++)
          if(diag(i)==0)
            diag(i)=1.;
      }
// coeffs = 0.;
// diag = 10.;
      mat.dimensionner(nb_som, nnz+nb_som) ;
      mat.remplir(voisins, coeffs, diag) ;
      mat.compacte() ;
      mat.set_est_definie(1);
// Modif CD 15/04/03 pour paralleliser le filtrage
// On copie la matrice remplie ci-dessus dans une matrice bloc.
// Cette modification permet d'utiliser le preconditionnement SSOR
// On fait aussi la transformation en matrice bloc en sequentiel car sinon
// probleme avec NP
      cha.dimensionner_Mat_Bloc_Morse_Sym(cha.MatP1NC2P1_L2_Parallele);
      cha.Mat_Morse_to_Mat_Bloc(cha.MatP1NC2P1_L2_Parallele);
// Fin Modif CD 15/04/03
// mat.imprimer_formatte(Cerr);
// Cerr<<"zone.nb_som_tot() = "<<mazone.nb_som_tot()<<", zone.nb_som() = "<<mazone.nb_som()<<finl;
// Cerr << "Matrice de filtrage OK" << finl;
// Cout << "Matrice de masse P1 : " << finl;
// mat.imprimer(Cout) << finl;
    }
// Debog::verifier(" verif champ " , ch);
  double coeff;
  if(Objet_U::dimension==2)
    coeff=1./6.;
  else
    coeff=1./12.;
  int nb_faces=zone_VEF.nb_faces();
  int nb_faces_tot=zone_VEF.nb_faces_tot();
  ArrOfInt virtfait(nb_faces_tot-nb_faces);
  int nb_som_face=zone_VEF.nb_som_face();
  const IntTab& face_sommets=zone_VEF.face_sommets();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int face;
  int premiere_face_int = zone_VEF.premiere_face_int();
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
// for n_bord
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord = le_bord.nb_faces();
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
// *0.5 car les faces perio sont parcourues deux fois
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              if (ind_face-nb_faces_bord>=0) virtfait(face-nb_faces)=1;
              int elem1=face_voisins(face,0);
              int elem2=face_voisins(face,1);
              double volume=zone_VEF.volumes(elem1);
              if(elem2!=-1)
                volume+=zone_VEF.volumes(elem2);
              for(int isom=0; isom<nb_som_face; isom++)
                {
                  int som=face_sommets(face,isom);
                  int som1=dom.get_renum_som_perio(som);
                  for(int k=0; k<nb_comp; k++)
                    secmem(som1,k)+=0.5*coeff*volume*ch(face,k);
                }
            }
        }
      else
        for (int ind_face=num1; ind_face<num2; ind_face++)
          {
            face = le_bord.num_face(ind_face);
            if (ind_face-nb_faces_bord>=0) virtfait(face-nb_faces)=1;
            int elem1=face_voisins(face,0);
            int elem2=face_voisins(face,1);
            double volume=zone_VEF.volumes(elem1);
            if(elem2!=-1)
              volume+=zone_VEF.volumes(elem2);
            for(int isom=0; isom<nb_som_face; isom++)
              {
                int som=face_sommets(face,isom);
                int som1=dom.get_renum_som_perio(som);
                for(int k=0; k<nb_comp; k++)
                  secmem(som1,k)+=coeff*volume*ch(face,k);
              }
          }
    }
  for(face=premiere_face_int; face<nb_faces_tot; face++)
    {
      int indvirtface=face-nb_faces;
// on regarde si la face virtuelle n'a pas deja ete traitee
      if (indvirtface>=0)
        if (virtfait[indvirtface]==1) continue;
      int elem1=face_voisins(face,0);
      int elem2=face_voisins(face,1);
      double volume=zone_VEF.volumes(elem1);
      if(elem2!=-1)
        volume+=zone_VEF.volumes(elem2);
      for(int isom=0; isom<nb_som_face; isom++)
        {
          int som=face_sommets(face,isom);
          int som1=dom.get_renum_som_perio(som);
          for(int k=0; k<nb_comp; k++)
            secmem(som1,k)+=coeff*volume*ch(face,k);
        }
    }
// ************************************************************************************************
// ************************************************************************************************
//
// Pour imposer u_som = u donne par CL_Dirichlet
//
// ************************************************************************************************
// ************************************************************************************************
// PQ : on commence par traiter les conditions Dirichlet, PUIS Dirichlet_homogene pour s'assurer
// de l'"adherence" des points sommets appartenant aux deux types de CL (aretes de bords)
  IntVect test_cl_imposee(nb_som);
  test_cl_imposee = 0;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
// for n_bord
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
// if (sub_type(Dirichlet,la_cl.valeur()))
      if (!sub_type(Periodique,la_cl.valeur()))
        {
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              for(int isom=0; isom<nb_som_face; isom++)
                {
                  int som=face_sommets(face,isom);
                  int som1=dom.get_renum_som_perio(som);
                  for(int k=0; k<nb_comp; k++)
                    {
                      if (test_cl_imposee(som1)==0)
                        secmem(som1,k) = 0;
                      secmem(som1,k) += coeff_penalisation * ch(face,k);
                    }
                  test_cl_imposee(som1) += 1;
                }
            }
        }
    }//for n_bord
  test_cl_imposee = 0;
  for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
// for n_bord
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      if (sub_type(Dirichlet_homogene,la_cl.valeur()))
        {
          for (int ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              for(int isom=0; isom<nb_som_face; isom++)
                {
                  int som=face_sommets(face,isom);
                  int som1=dom.get_renum_som_perio(som);
                  for(int k=0; k<nb_comp; k++)
                    {
                      if (test_cl_imposee(som1)==0)
                        secmem(som1,k) = 0;
                      secmem(som1,k) += coeff_penalisation * ch(face,k);
                    }
                  test_cl_imposee(som1) += 1;
                }
            }
        }
    }//for n_bord
// ************************************************************************************************
// ************************************************************************************************
  secmem.echange_espace_virtuel();
// Debog::verifier(" verif secmem_ech " , secmem);
  SolveurSys& solv=ref_cast(SolveurSys, cha.solveur_L2);
  DoubleVect secmemk(cha.ch_som_vect());
  DoubleVect solution(cha.ch_som_vect());
  if(nb_comp==1)
    {
      solution=vit_som;
      secmem.echange_espace_virtuel();
      Debog::verifier(" verif secmem " , secmem);
// ON UTILISE LA MEME MATRICE EN SEQUENTIEL ET PARALLELE
// CE QUI PERMET D UTILISER UNE MATRICE BLOC QUAND ON APPELLE LE SOLVEUR NP
      solv.resoudre_systeme(cha.MatP1NC2P1_L2_Parallele.valeur(), secmem, solution);
      for(int som=0; som<nb_som; som++)
        vit_som(som)=solution(dom.get_renum_som_perio(som));
    }
  else
    {
      for(int k=0; k<nb_comp; k++)
        {
          int som;
          for(som=0; som<nb_som; som++)
            {
              solution(som)=vit_som(som,k);
              secmemk(som)=secmem(som,k);
            }
          solution.echange_espace_virtuel();
          secmemk.echange_espace_virtuel();
// ON UTILISE LA MEME MATRICE EN SEQUENTIEL ET PARALLELE
// CE QUI PERMET D UTILISER UNE MATRICE BLOC QUAND ON APPELLE LE SOLVEUR NP
          solv.resoudre_systeme(cha.MatP1NC2P1_L2_Parallele.valeur(), secmemk, solution);
          for(som=0; som<nb_som; som++)
            vit_som(som,k)=solution(dom.get_renum_som_perio(som));
        }
    }
// Debog::verifier(" verif vit_som 0 " , vit_som);
  vit_som.echange_espace_virtuel();
// Debog::verifier(" verif vit_som 1 " , vit_som);
// {
// for(int k=0; k<nb_comp; k++)
// for(int som=0; som<nb_som; som++)
// Cerr << k << " x " << coord(som,0)<< " y " << coord(som,1) << " " << vit_som(som,k) << finl;
// double psc=vit_som*vit_som;
// psc = Process::mp_sum(psc);
// Debog::verifier("norme : ", psc);
// Cerr << "############ psc = " << psc << finl;
// }
  Debog::verifier(" verif vit_som " , vit_som);
  return vit_som;
}
DoubleTab& valeur_P1_L2 (Champ_Fonc_P1NC & cha, const Domaine & dom)
Definition at line 494 of file Champ_P1NC_implementation.cpp.
References Cerr, Champ_P1NC_implementation::ch_som(), Champ_P1NC_implementation::ch_som_vect(), coeff, Matrice_Morse_Sym::compacte(), Objet_U::dimension, Matrice_Morse::dimensionner(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), DoubleVect::echange_espace_virtuel(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Domaine::get_renum_som_perio(), Lec_Diffuse_base::good(), Field_base::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Champ_P1NC_implementation::MatP1NC2P1_L2, Champ_P1NC_implementation::MatP1NC2P1_L2_Parallele, Process::me(), Process::mp_min(), Zone::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Matrice_Morse::nb_lignes(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), Zone::nb_som_tot(), LecFicDiffuse::ouvrir(), ref_cast, Matrice_Morse::remplir(), SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), Champ_P1NC_implementation::solveur_L2, Deriv_Matrice_Base::valeur(), Champ_Don_base::valeurs(), Debog::verifier(), Zone_VF::volumes(), Domaine::zone(), and Champ_Fonc_P1NC::zone_vef().
{
  const Zone& mazone = dom.zone(0);
  int nb_elem_tot = mazone.nb_elem_tot();
  int nb_som = mazone.nb_som_tot();
  int nb_som_elem = mazone.nb_som_elem();
  const DoubleTab& ch = cha.valeurs();
  const Zone_VEF& zone_VEF = cha.zone_vef();
  const IntTab& elem_som = mazone.les_elems();
  double mijK, miiK;
  DoubleTab& vit_som=cha.ch_som();
  int nb_comp=vit_som.line_size();
  DoubleTab secmem(cha.ch_som());
  secmem=0.;
  if(Objet_U::dimension==2)
    {
      mijK=1./12.;
      miiK= 1./6.;
    }
  else
    {
      mijK=1./18.;
      miiK= 1./12.;
    }
// dans le cas d'une zone nulle on doit effectuer le dimensionnement
// mais une seule fois
  double non_prepare=0;
  if (cha.MatP1NC2P1_L2.nb_lignes() <2)
    non_prepare=1;
  non_prepare=Process::mp_min(non_prepare);
  if (non_prepare==1)
    {
// Initialisation du solveur
      SolveurSys& solv=ref_cast(SolveurSys, (cha.solveur_L2));
      LecFicDiffuse fic;
      fic.ouvrir("solveur.bar");
      if(fic.good())
        {
          fic >> solv;
          Cerr << Process::me() << "solveur.bar ouvert pour lire: " << solv << finl;
        }
      solv->reinit();
      Cerr<<"On remplit la matrice cha.MatP1NC2P1_L2 pour le champ "<< cha.le_nom() <<finl;
      Matrice_Morse_Sym& mat=ref_cast(Matrice_Morse_Sym, (cha.MatP1NC2P1_L2));
      int rang;
      int nnz=0;
      IntLists voisins(nb_som);
      DoubleLists coeffs(nb_som);
      DoubleVect diag(nb_som);
      int elem;
      for (elem=0; elem<nb_elem_tot; elem++)
        {
          double coeff_ij=mijK*zone_VEF.volumes(elem);
          double coeff_ii=miiK*zone_VEF.volumes(elem);
          for (int isom=0; isom<nb_som_elem; isom++)
            {
              int som=elem_som(elem,isom);
              int ii=dom.get_renum_som_perio(som);
              diag[ii]+=coeff_ii;
              for (int jsom=isom+1; jsom<nb_som_elem; jsom++)
                {
                  int asom=elem_som(elem,jsom);
                  int j=dom.get_renum_som_perio(asom);
                  int i=ii;
                  if(i>j)
                    {
                      int k=j;
                      j=i;
                      i=k;
                    }
                  rang=voisins[i].rang(j);
                  if(rang==-1)
                    {
                      voisins[i].add(j);
                      coeffs[i].add(coeff_ij);
                      nnz++;
                    }
                  else
                    {
                      coeffs[i][rang]+=coeff_ij;
                    }
                }
            }
        }
      {
        for (int i=0; i<nb_som; i++)
          if(diag(i)==0)
            diag(i)=1.;
      }
      mat.dimensionner(nb_som, nnz+nb_som) ;
      mat.remplir(voisins, coeffs, diag) ;
      mat.compacte() ;
      mat.set_est_definie(1);
// Modif CD 15/04/03 pour paralleliser le filtrage
// On copie la matrice remplie ci-dessus dans une matrice bloc.
// Cette modification permet d'utiliser le preconditionnement SSOR
// On fait aussi la transformation en matrice bloc en sequentiel car sinon
// probleme avec NP
      cha.dimensionner_Mat_Bloc_Morse_Sym(cha.MatP1NC2P1_L2_Parallele);
      cha.Mat_Morse_to_Mat_Bloc(cha.MatP1NC2P1_L2_Parallele);
// Fin Modif CD 15/04/03
// mat.imprimer_formatte(Cerr);
// Cerr<<"zone.nb_som_tot() = "<<mazone.nb_som_tot()<<", zone.nb_som() = "<<mazone.nb_som()<<finl;
// Cerr << "Matrice de filtrage OK" << finl;
// Cout << "Matrice de masse P1 : " << finl;
// mat.imprimer(Cout) << finl;
    }
// Debog::verifier(" verif champ " , ch);
  double coeff;
  if(Objet_U::dimension==2)
    coeff=1./6.;
  else
    coeff=1./12.;
  int nb_faces=zone_VEF.nb_faces();
  int nb_faces_tot=zone_VEF.nb_faces_tot();
  ArrOfInt virtfait(nb_faces_tot-nb_faces);
  int nb_som_face=zone_VEF.nb_som_face();
  const IntTab& face_sommets=zone_VEF.face_sommets();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int face;
  for(face=0; face<nb_faces_tot; face++)
    {
      int indvirtface=face-nb_faces;
// on regarde si la face virtuelle n'a pas deja ete traitee
      if (indvirtface>=0)
        if (virtfait[indvirtface]==1) continue;
      int elem1=face_voisins(face,0);
      int elem2=face_voisins(face,1);
      double volume=zone_VEF.volumes(elem1);
      if(elem2!=-1)
        volume+=zone_VEF.volumes(elem2);
      for(int isom=0; isom<nb_som_face; isom++)
        {
          int som=face_sommets(face,isom);
          int som1=dom.get_renum_som_perio(som);
// Pour un sommet periodique on ne retient qu une seule contribution
// pour deux faces en vis a vis
          if (som1==som)
            for(int k=0; k<nb_comp; k++)
              secmem(som1,k)+=coeff*volume*ch(face,k);
        }
    }
  secmem.echange_espace_virtuel();
// Debog::verifier(" verif secmem_ech " , secmem);
  SolveurSys& solv=ref_cast(SolveurSys, cha.solveur_L2);
  DoubleVect secmemk(cha.ch_som_vect());
  DoubleVect solution(cha.ch_som_vect());
  if(nb_comp==1)
    {
      solution=vit_som;
      secmem.echange_espace_virtuel();
      Debog::verifier(" verif secmem " , secmem);
// ON UTILISE LA MEME MATRICE EN SEQUENTIEL ET PARALLELE
// CE QUI PERMET D UTILISER UNE MATRICE BLOC QUAND ON APPELLE LE SOLVEUR NP
      solv.resoudre_systeme(cha.MatP1NC2P1_L2_Parallele.valeur(), secmem, solution);
      for(int som=0; som<nb_som; som++)
        vit_som(som)=solution(dom.get_renum_som_perio(som));
    }
  else
    {
      for(int k=0; k<nb_comp; k++)
        {
          int som;
          for(som=0; som<nb_som; som++)
            {
              solution(som)=vit_som(som,k);
              secmemk(som)=secmem(som,k);
            }
          solution.echange_espace_virtuel();
          secmemk.echange_espace_virtuel();
// ON UTILISE LA MEME MATRICE EN SEQUENTIEL ET PARALLELE
// CE QUI PERMET D UTILISER UNE MATRICE BLOC QUAND ON APPELLE LE SOLVEUR NP
          solv.resoudre_systeme(cha.MatP1NC2P1_L2_Parallele.valeur(), secmemk, solution);
          for(som=0; som<nb_som; som++)
            vit_som(som,k)=solution(dom.get_renum_som_perio(som));
        }
    }
// Debog::verifier(" verif vit_som 0 " , vit_som);
  vit_som.echange_espace_virtuel();
// Debog::verifier(" verif vit_som 1 " , vit_som);
// {
// for(int k=0; k<nb_comp; k++)
// for(int som=0; som<nb_som; som++)
// Cerr << k << " x " << coord(som,0)<< " y " << coord(som,1) << " " << vit_som(som,k) << finl;
// double psc=vit_som*vit_som;
// psc = Process::mp_sum(psc);
// Debog::verifier("norme : ", psc);
// Cerr << "############ psc = " << psc << finl;
// }
  Debog::verifier(" verif vit_som " , vit_som);
  return vit_som;
}
Variable Documentation
const double coeff_penalisation = 1e9 [static]
Definition at line 67 of file Champ_P1NC_implementation.cpp.
Referenced by Champ_P1NC_implementation::filtrer_resu(), and valeur_P1_L2().
int methode_calcul_valeurs_sommets = 2 [static]
Definition at line 43 of file Champ_P1NC_implementation.cpp.
Referenced by Champ_P1NC_implementation::valeur_aux_sommets(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().