TRUST: src/VDF/Champs/Champ_Don_Face_lu.cpp File Reference
Champ_Don_Face_lu.cpp File Reference
#include <Champ_Don_Face_lu.h>
#include <Probleme_base.h>
#include <Zone_VDF.h>
#include <EFichier.h>
#include <Interprete.h>
#include <Motcle.h>
#include <ArrOfBit.h>
Functions
int meme_point (const ArrOfInt &x, const DoubleTab &tab, int rang_tab)
Variables
const Type_info * Champ_Don_Face_lubases [1] ={ &(Champ_Fonc_Face ::info_obj)}
Function Documentation
meme_point()
int meme_point (const ArrOfInt & x, const DoubleTab & tab, int rang_tab)
Definition at line 25 of file Champ_Don_Face_lu.cpp.
{
  int dime = x.size_array();
  assert(tab.dimension(1) == dime);
  int k;
  for (k=0; k<dime; k++)
    if (std::fabs(x[k]-tab(rang_tab,k)) >= 1.e-12)
      break;
  return (k == dime);
}
References TRUSTTab< _TYPE_ >::dimension(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Champ_Don_Face_lu::readOn().
Variable Documentation
Champ_Don_Face_lubases
const Type_info* Champ_Don_Face_lubases[1] ={ &(Champ_Fonc_Face ::info_obj)}
Definition at line 36 of file Champ_Don_Face_lu.cpp.