TRUST: src/VEF/Champs/Champ_P1NC.cpp File Reference
Champ_P1NC.cpp File Reference
#include <Champ_P1NC.h>
#include <Periodique.h>
#include <Dirichlet_paroi_fixe.h>
#include <Dirichlet_paroi_defilante.h>
#include <Echange_externe_impose.h>
#include <Neumann_paroi.h>
#include <Neumann_homogene.h>
#include <Fluide_base.h>
#include <Scalaire_impose_paroi.h>
#include <Champ_Uniforme.h>
#include <Operateur.h>
#include <Operateur_base.h>
#include <Mod_turb_hyd_base.h>
#include <distances_VEF.h>
#include <TRUSTTrav.h>
#include <Schema_Temps_base.h>
#include <SFichier.h>
#include <Probleme_base.h>
Functions
void calculer_gradientP1NC (const DoubleTab &variable, const Zone_VEF &zone_VEF, const Zone_Cl_VEF &zone_Cl_VEF, DoubleTab &gradient_elem)
class Champ_P1NC
Rq : cette classe est specifique au module VEF
static double norme_L2 (const DoubleTab &u, const Zone_VEF &zone_VEF)
Variables
const Type_info * Champ_P1NCbases [1] ={ &(Champ_Inc_base ::info_obj)}
Function Documentation
calculer_gradientP1NC()
void calculer_gradientP1NC (const DoubleTab & variable, const Zone_VEF & zone_VEF, const Zone_Cl_VEF & zone_Cl_VEF, DoubleTab & gradient_elem)
class Champ_P1NC
Rq : cette classe est specifique au module VEF
Definition at line 144 of file Champ_P1NC.cpp.
{
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const int nb_faces = zone_VEF.nb_faces_tot();
  const int nb_elem = zone_VEF.nb_elem_tot();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int premiere_face_int = zone_VEF.premiere_face_int();
  int dimension=Objet_U::dimension;
  const int nb_comp = variable.line_size();
  gradient_elem=0.;
  int icomp,fac,i,elem1,elem2,elem,num_face;
  int n_bord;
  int ind_face;
// Cas du calcul du gradient d'un tableau de vecteurs
  if (nb_comp!=1)
    {
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl =
            zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord =
            ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
          int nb_faces_bord = le_bord.nb_faces();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              for (ind_face=num1; ind_face<num2; ind_face++)
                {
                  num_face = le_bord.num_face(ind_face);
                  elem1=face_voisins(num_face,0);
                  elem2=face_voisins(num_face,1);
                  for (icomp=0; icomp<nb_comp; icomp++)
                    for (i=0; i<dimension; i++)
                      {
                        if (ind_face<nb_faces_bord)
{
                            gradient_elem(elem1, icomp, i) +=
                              0.5*face_normales(num_face,i)*variable(num_face,icomp);
                            gradient_elem(elem2, icomp, i) -=
                              0.5*face_normales(num_face,i)*variable(num_face,icomp);
                          }
                        else
{
// Correction pour prise en compte des faces virtuelles periodiques
// On retranche la contribution en exces ajoutee quand on traite
// les faces entre nb_faces et nb_faces_tot (dans le cas des faces periodiques)
                            gradient_elem(elem1, icomp, i) -=
                              0.5*face_normales(num_face,i)*variable(num_face,icomp);
                            gradient_elem(elem2, icomp, i) +=
                              0.5*face_normales(num_face,i)*variable(num_face,icomp);
                          }
                      }
                }
            }
          else
            for (ind_face=num1; ind_face<nb_faces_bord; ind_face++)
              {
                fac = le_bord.num_face(ind_face);
                elem1=face_voisins(fac,0);
                for (icomp=0; icomp<nb_comp; icomp++)
                  for (i=0; i<dimension; i++)
                    {
                      gradient_elem(elem1, icomp, i) +=
                        face_normales(fac,i)* variable(fac,icomp);
                    }
              }
        }
      for (fac=premiere_face_int; fac<nb_faces; fac++)
        {
          elem1=face_voisins(fac,0);
          elem2=face_voisins(fac,1);
// Deroulement de la boucle pour optimiser un peu (-20% sur 12000 mailles):
          if (elem1>=0 && elem2>=0)
            {
              if (dimension==2)
                {
                  for (icomp=0; icomp<nb_comp; icomp++)
                    {
                      double var = variable(fac,icomp);
                      gradient_elem(elem1, icomp, 0) += face_normales(fac,0)*var;
                      gradient_elem(elem2, icomp, 0) -= face_normales(fac,0)*var;
                      gradient_elem(elem1, icomp, 1) += face_normales(fac,1)*var;
                      gradient_elem(elem2, icomp, 1) -= face_normales(fac,1)*var;
                    }
                }
              else
                {
                  for (icomp=0; icomp<nb_comp; icomp++)
                    {
                      double var = variable(fac,icomp);
                      gradient_elem(elem1, icomp, 0) += face_normales(fac,0)*var;
                      gradient_elem(elem2, icomp, 0) -= face_normales(fac,0)*var;
                      gradient_elem(elem1, icomp, 1) += face_normales(fac,1)*var;
                      gradient_elem(elem2, icomp, 1) -= face_normales(fac,1)*var;
                      gradient_elem(elem1, icomp, 2) += face_normales(fac,2)*var;
                      gradient_elem(elem2, icomp, 2) -= face_normales(fac,2)*var;
                    }
                }
            }
          else
            {
              for (icomp=0; icomp<nb_comp; icomp++)
                for (i=0; i<dimension; i++)
                  {
                    if (elem1>=0) gradient_elem(elem1, icomp, i) += face_normales(fac,i)*variable(fac,icomp);
                    if (elem2>=0) gradient_elem(elem2, icomp, i) -= face_normales(fac,i)*variable(fac,icomp);
                  }
            }
        }
    }
// Cas du calcul du gradient d'un tableau de scalaire dans un tableau gradient_elem(,,)
  else if (gradient_elem.nb_dim()==3)
    {
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
          int nb_faces_bord = le_bord.nb_faces();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              for (ind_face=num1; ind_face<num2; ind_face++)
                {
                  num_face = le_bord.num_face(ind_face);
                  elem1=face_voisins(num_face,0);
                  elem2=face_voisins(num_face,1);
                  for (i=0; i<dimension; i++)
                    {
                      if (ind_face<nb_faces_bord)
{
                          gradient_elem(elem1, 0, i) +=
                            0.5*face_normales(num_face,i)*variable(num_face);
                          gradient_elem(elem2, 0, i) -=
                            0.5*face_normales(num_face,i)*variable(num_face);
                        }
                      else
{
// Correction pour prise en compte des faces virtuelles periodiques
// On retranche la contribution en exces ajoutee quand on traite
// les faces entre nb_faces et nb_faces_tot (dans le cas des faces periodiques)
                          gradient_elem(elem1, 0, i) -=
                            0.5*face_normales(num_face,i)*variable(num_face);
                          gradient_elem(elem2, 0, i) +=
                            0.5*face_normales(num_face,i)*variable(num_face);
                        }
                    }
                }
            }
          else
            for (ind_face=num1; ind_face<nb_faces_bord; ind_face++)
              {
                fac = le_bord.num_face(ind_face);
                elem1=face_voisins(fac,0);
                for (i=0; i<dimension; i++)
                  {
                    gradient_elem(elem1, 0, i) +=
                      face_normales(fac,i)* variable(fac);
                  }
              }
        }
      for (fac=premiere_face_int; fac<nb_faces; fac++)
        {
          elem1=face_voisins(fac,0);
          elem2=face_voisins(fac,1);
          for (i=0; i<dimension; i++)
            {
              if (elem1>=0)
                gradient_elem(elem1, 0, i) += face_normales(fac,i)*variable(fac);
              if (elem2>=0)
                gradient_elem(elem2, 0, i) -= face_normales(fac,i)*variable(fac);
            }
        }
    }
// Cas du calcul du gradient d'un tableau de scalaire dans un tableau gradient_elem(,)
  else
    {
      for (n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
          int nb_faces_bord = le_bord.nb_faces();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              for (ind_face=num1; ind_face<num2; ind_face++)
                {
                  num_face = le_bord.num_face(ind_face);
                  elem1=face_voisins(num_face,0);
                  elem2=face_voisins(num_face,1);
                  for (i=0; i<dimension; i++)
                    {
                      if (ind_face<nb_faces_bord)
{
                          gradient_elem(elem1, i) +=
                            0.5*face_normales(num_face,i)*variable(num_face);
                          gradient_elem(elem2, i) -=
                            0.5*face_normales(num_face,i)*variable(num_face);
                        }
                      else
{
// Correction pour prise en compte des faces virtuelles periodiques
// On retranche la contribution en exces ajoutee quand on traite
// les faces entre nb_faces et nb_faces_tot (dans le cas des faces periodiques)
                          gradient_elem(elem1,i) -=
                            0.5*face_normales(num_face,i)*variable(num_face);
                          gradient_elem(elem2,i) +=
                            0.5*face_normales(num_face,i)*variable(num_face);
                        }
                    }
                }
            }
          else
            for (ind_face=num1; ind_face<nb_faces_bord; ind_face++)
              {
                fac = le_bord.num_face(ind_face);
                elem1=face_voisins(fac,0);
                for (i=0; i<dimension; i++)
                  {
                    gradient_elem(elem1, i) +=
                      face_normales(fac,i)* variable(fac);
                  }
              }
        }
      for (fac=premiere_face_int; fac<nb_faces; fac++)
        {
          elem1=face_voisins(fac,0);
          elem2=face_voisins(fac,1);
          for (i=0; i<dimension; i++)
            {
              if (elem1>=0)
                gradient_elem(elem1, i) += face_normales(fac,i)*variable(fac);
              if (elem2>=0)
                gradient_elem(elem2, i) -= face_normales(fac,i)*variable(fac);
            }
        }
    }
  const DoubleVect& inverse_volumes = zone_VEF.inverse_volumes();
  if (gradient_elem.nb_dim()==3)
    for ( elem=0; elem<nb_elem; elem++)
      for (icomp=0; icomp<nb_comp; icomp++)
        for (i=0; i<dimension; i++)
          gradient_elem(elem,icomp,i) *= inverse_volumes(elem);
  else
    for ( elem=0; elem<nb_elem; elem++)
      for (i=0; i<dimension; i++)
        gradient_elem(elem,i) *= inverse_volumes(elem);
}
References Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VF::inverse_volumes(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, and Deriv_Cond_lim_base::valeur().
Referenced by Champ_P1NC::calcul_grad_T(), Champ_P1NC::calcul_grad_U(), Champ_P1NC::calcul_gradient(), Op_Diff_P1NC_barprim::calculer(), and Champ_P1NC::gradient().
norme_L2()
static double norme_L2 (const DoubleTab & u, const Zone_VEF & zone_VEF) static
Definition at line 845 of file Champ_P1NC.cpp.
{
  const DoubleVect& volumes = zone_VEF.volumes_entrelaces();
  const int nb_faces = zone_VEF.nb_faces();
  int i=0;
  double norme =0;
  int nb_compo_=u.line_size();
  for(; i<nb_faces; i++)
    {
      double s=0;
      for(int j=0; j<nb_compo_; j++)
        s+=u(i,j)*u(i,j);
      norme+=volumes(i)*s;
    }
  return sqrt(norme);
}
References TRUSTVect< _TYPE_ >::line_size(), Zone_VF::nb_faces(), norme(), and Zone_VF::volumes_entrelaces().
Referenced by Champ_P1NC::norme_L2().
Variable Documentation
Champ_P1NCbases
const Type_info* Champ_P1NCbases[1] ={ &(Champ_Inc_base ::info_obj)}
Definition at line 35 of file Champ_P1NC.cpp.