TRUST: src/Kernel/Framework/Champs_compris.cpp File Reference
Champs_compris.cpp File Reference
#include <Champs_compris.h>
#include <Champ_base.h>
#include <List_Nom.h>
Functions
int new_liste_add_if_not (List_Nom &new_list, const Nom &nom_champ)
void rebuild_liste_noms (const List_Ref_Champ_base &liste_champs_, const Noms &liste_noms_, Noms &liste_noms_construits_, int info=0)
Variables
const Type_info * List_Ref_Champ_basebases [1] ={ &(liste ::info_obj)}
const Type_info * Champs_comprisbases [1] ={ &(Objet_U ::info_obj)}
Function Documentation
new_liste_add_if_not()
int new_liste_add_if_not (List_Nom & new_list, const Nom & nom_champ)
Definition at line 104 of file Champs_compris.cpp.
{
  Motcle mot(nom_champ);
  CONST_LIST_CURSEUR(Nom) curseur = new_list;
  while (curseur)
    {
      if (mot == curseur.valeur())
        return 0;
      ++curseur;
    }
  new_list.add(nom_champ);
  return 1;
}
References CONST_LIST_CURSEUR.
Referenced by rebuild_liste_noms().
rebuild_liste_noms()
void rebuild_liste_noms (const List_Ref_Champ_base & liste_champs_, const Noms & liste_noms_, Noms & liste_noms_construits_, int info = 0)
Definition at line 118 of file Champs_compris.cpp.
{
  if (liste_noms_construits_.size()<liste_noms_.size())
    liste_noms_construits_=liste_noms_;
  LIST(Nom) new_liste;
  int size = liste_noms_.size();
  for (int i=0; i<size; i++)
    new_liste.add(liste_noms_[i]);
  REF(Champ_base) ref_champ;
  CONST_LIST_CURSEUR(REF(Champ_base)) curseur = liste_champs_;
  Nom nom_champ;
  while (curseur)
    {
      const Champ_base& ch= curseur.valeur().valeur();
      nom_champ = ch.le_nom();
// Cerr<<" ok "<<nom_champ<<finl;
      if (nom_champ!=Nom())
        new_liste_add_if_not(new_liste,nom_champ);
      const Noms& syno= ch.get_synonyms();
      int nb_syno=syno.size();
      for (int s=0; s<nb_syno; s++)
        {
          if (syno[s]!=Nom())
            new_liste_add_if_not(new_liste,syno[s]);
        }
      int nb_composantes = ch.nb_comp();
      for (int i=0; i<nb_composantes; i++)
        {
          nom_champ = (ch.nom_compo(i));
          if (nom_champ!=Nom())
            new_liste_add_if_not(new_liste,nom_champ);
        }
      ++curseur;
    }
  int size_new_liste=new_liste.size();
  int prem=1;
  if (size_new_liste!=liste_noms_construits_.size())
    {
      if (info)
        if (prem)
          {
            prem=0;
          }
      Noms nn_liste_noms_construits_(size_new_liste);
      for (int i=0; i<liste_noms_construits_.size(); i++)
        if (i<size_new_liste)
          nn_liste_noms_construits_[i]=liste_noms_construits_[i];
      liste_noms_construits_ =nn_liste_noms_construits_;
    }
  for (int i=0; i<size_new_liste; i++)
    if (liste_noms_construits_[i]!=new_liste(i))
      {
        if (info)
          {
            if (prem)
              {
                prem=0;
              }
// Cout<<liste_noms_construits_[i] << " va etre remplace par "<< new_liste(i)<<finl;
          }
        liste_noms_construits_[i]=new_liste(i);
      }
// if ((prem==0) && (info))
// Cout<<"liste apres modif "<<liste_noms_construits_<<finl;
// Cerr<<" ici2 "<<finl;
}
References CONST_LIST_CURSEUR, Field_base::get_synonyms(), info, Field_base::le_nom(), LIST, Field_base::nb_comp(), new_liste_add_if_not(), Field_base::nom_compo(), prem, REF, and vect_impl::size().
Referenced by Champs_compris::ajoute_champ(), Champs_compris::ajoute_nom_compris(), and Champs_compris::liste_noms_compris().
Variable Documentation
Champs_comprisbases
const Type_info* Champs_comprisbases[1] ={ &(Objet_U ::info_obj)}
Definition at line 22 of file Champs_compris.cpp.
List_Ref_Champ_basebases
const Type_info* List_Ref_Champ_basebases[1] ={ &(liste ::info_obj)}
Definition at line 20 of file Champs_compris.cpp.