TRUST: src/P1NCP1B/Champs/Champ_P1iP1B_implementation.cpp File Reference
Champ_P1iP1B_implementation.cpp File Reference
#include <Champ_P1iP1B_implementation.h>
#include <Champ_implementation_P1.h>
#include <Domaine.h>
#include <Zone_VEF_PreP1b.h>
#include <Zone_Cl_VEFP1B.h>
#include <Debog.h>
#include <Matrice_Morse_Sym.h>
#include <TRUSTLists.h>
#include <SolveurSys.h>
#include <Solv_GCP.h>
#include <SSOR.h>
#include <Neumann_sortie_libre.h>
#include <Champ_P0_VEF.h>
#include <TRUSTTab_parts.h>
#include <Frontiere_dis_base.h>
Functions
void assembler (const Zone_VEF_PreP1b &zone_VEF, Matrice &matrice)
double second_membre (const Zone_VEF_PreP1b &zone_VEF, ArrOfDouble &Pa, DoubleVect &secmem)
void corriger (const Zone_VEF_PreP1b &zone_VEF, DoubleTab &champ_filtre_, Matrice &matrice, const int Condition_Neumann_imposee_)
Variables
static double coeff = 4. / 5.
static double coeff_inv = 1 / coeff
Function Documentation
assembler()
void assembler (const Zone_VEF_PreP1b & zone_VEF, Matrice & matrice)
< Sommets periodiques
Definition at line 261 of file Champ_P1iP1B_implementation.cpp.
{
  matrice.typer("Matrice_Morse_Sym");
  Matrice_Morse_Sym& MatPoisson=ref_cast(Matrice_Morse_Sym, matrice.valeur());
  int nb_som_tot = zone_VEF.zone().nb_som_tot();
  int nb_arete_tot = zone_VEF.zone().nb_aretes_tot();
  int nnz=nb_som_tot+nb_arete_tot;
  const IntTab& aretes_som=zone_VEF.zone().aretes_som();
  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
  const Domaine& dom=zone_VEF.zone().domaine();
  IntLists voisins(nb_som_tot);
  DoubleLists coeffs(nb_som_tot);
  DoubleVect diag(nb_som_tot);
// On parcourt toutes les aretes non periodiques:
  for(int arete=0; arete<nb_arete_tot; arete++)
    {
      if (renum_arete_perio[arete]==arete)
        {
          int som1=dom.get_renum_som_perio(aretes_som(arete, 0));
          int som2=dom.get_renum_som_perio(aretes_som(arete, 1));
          if(som1>som2)
            {
              int tmp=som1;
              som1=som2;
              som2=tmp;
            }
          voisins[som1].add(som2);
          coeffs[som1].add(1);
          diag(som1)++;
          diag(som2)++;
        }
    }
  for (int i=0; i<nb_som_tot; i++)
    {
      if (diag(i)==0)
        {
          assert(i!=dom.get_renum_som_perio(i));
          diag(i)=1; //!< Sommets periodiques
        }
    }
  MatPoisson.dimensionner(nb_som_tot, nnz) ;
  MatPoisson.remplir(voisins, coeffs, diag) ;
  MatPoisson.compacte() ;
  MatPoisson.set_est_definie(1);
// Cerr << "Matrice P1";MatPoisson.imprimer(Cerr);
}
References Zone::aretes_som(), Matrice_Morse_Sym::compacte(), Matrice_Morse::dimensionner(), Zone::domaine(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Zone::nb_aretes_tot(), Zone::nb_som_tot(), ref_cast, Matrice_Morse::remplir(), Matrice_Sym::set_est_definie(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by corriger().
corriger()
void corriger (const Zone_VEF_PreP1b & zone_VEF, DoubleTab & champ_filtre_, Matrice & matrice, const int Condition_Neumann_imposee_)
< partie elements
< partie sommets
< partie aretes
< Copie de la structure
< Calcul de la moyenne du champ aux elements
< Correction des elements du champ_filtre_
< Correction des sommets du champ_filtre_
< Correction des sommets du champ_filtre_
< Mise a jour des espaces virtuels
Definition at line 337 of file Champ_P1iP1B_implementation.cpp.
{
  int nb_elem=zone_VEF.nb_elem();
  int nb_som=zone_VEF.nb_som();
// Tableaux d'acces aux valeurs Pk et Ps
  if (!zone_VEF.get_alphaE() || !zone_VEF.get_alphaS())
    {
      Cerr << "Erreur dans Champ_P1iP1B_impl.cpp: corriger(...), le champ doit avoir une partie sommets et elements" << finl;
      Process::exit();
    }
  DoubleTab_parts parties_P(champ_filtre_);
  DoubleVect& Pk = parties_P[0];  //!< partie elements
  DoubleVect& Ps = parties_P[1];  //!< partie sommets
// Filtrage si support arete
  if (zone_VEF.get_alphaA())
    {
      if (zone_VEF.get_renum_arete_perio().size_array()==0)
        {
          Cerr<<"We try to Champ_P1iP1B_impl::corriger but get_renum_arete_perio"<<finl;
        }
    }
  if (zone_VEF.get_alphaA()&& zone_VEF.get_renum_arete_perio().size_array())
    {
      DoubleVect& Pa = parties_P[2];  //!< partie aretes
// Si premier passage on assemble la matrice
      if (!matrice.non_nul()) assembler(zone_VEF, matrice);
// Construction du second membre
      DoubleVect secmem;
      zone_VEF.zone().domaine().creer_tableau_sommets(secmem);
      second_membre(zone_VEF, Pa, secmem);
// Calcul de la correction
      DoubleVect solution;
      solution.copy(secmem, ArrOfDouble::NOCOPY_NOINIT); //!< Copie de la structure
      solution = 0.;
      SolveurSys solveur;
      solveur.typer("Solv_GCP");
      Precond p;
      p.typer("SSOR");
      ref_cast(Solv_GCP,solveur.valeur()).set_precond(p);
      solveur.nommer("Pa_filter_solver");
      solveur.resoudre_systeme(matrice, secmem, solution);
// Application de la periodicite sur la solution:
      const Domaine& dom=zone_VEF.zone().domaine();
      for(int i=0; i<nb_som; i++)
        {
          int som=dom.get_renum_som_perio(i);
          if (som!=i)
            solution(i)=solution(som);
        }
// Correction de Ps:
      for(int som=0; som<nb_som; som++)
        Ps(som) += solution(som);
// Correction de Pa:
      int nb_arete = zone_VEF.zone().nb_aretes();
      const IntTab& aretes_som=zone_VEF.zone().aretes_som();
      const ArrOfInt& ok_arete=zone_VEF.get_ok_arete();
      for(int arete=0; arete<nb_arete; arete++)
        {
          if(!ok_arete[arete] && Pa(arete)!=0)
            {
              Cerr << "Pa(arete_superflue)!=0 dans Champ_P1iP1B_implementation::corriger" << finl;
              Cerr << "Contacter le support TRUST." << finl;
              Cerr << "S'il s'agit d'une reprise au format xyz d'un calcul" << finl;
              Cerr << "alors il faut ecraser le fichier .ok_arete de votre calcul de reprise" << finl;
              Cerr << "par le fichier .ok_arete de votre calcul precedant afin d'avoir les" << finl;
              Cerr << "memes aretes superflues." << finl;
              Process::exit();
            }
          int som1=aretes_som(arete, 0);
          int som2=aretes_som(arete, 1);
          double sigma=solution(som1)+solution(som2);
          Pa(arete)-=sigma*coeff_inv;
        }
// Correction de Pk:
      const IntTab& les_elems = zone_VEF.zone().les_elems();
      int nb_som_par_elem=les_elems.dimension_tot(1);
      for(int elem=0; elem<nb_elem; elem++)
        {
          double sigma=0;
          for (int som=0; som<nb_som_par_elem; som++)
            sigma+=solution(les_elems(elem,som));
          Pk(elem)-=sigma/4;
        }
    }
// Filtrage L2:
  double moyenne_K = mp_moyenne_vect(Pk);                //!< Calcul de la moyenne du champ aux elements
  Pk -= moyenne_K;                                 //!< Correction des elements du champ_filtre_
  Ps += moyenne_K;                                 //!< Correction des sommets du champ_filtre_
// On retranche a Ps sa moyenne si pas de Cl de Neumann pour avoir une moyenne nulle
// Il faudrait peut etre mieux faire cela dans Assembleur_P_VEFPreP1B::modifier_solution
// si cela est possible...
  assert(Condition_Neumann_imposee_!=-1);
  if (!Condition_Neumann_imposee_)
    {
// L'espace virtuel de Ps n'a pas besoin d'etre a jour pour calculer correctement la moyenne
      Ps -= mp_moyenne_vect(Ps); //!< Correction des sommets du champ_filtre_
    }
  champ_filtre_.echange_espace_virtuel();         //!< Mise a jour des espaces virtuels
}
References Zone::aretes_som(), assembler(), Cerr, coeff_inv, TRUSTVect< _TYPE_ >::copy(), Domaine::creer_tableau_sommets(), TRUSTTab< _TYPE_ >::dimension_tot(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Zone::les_elems(), mp_moyenne_vect(), Zone::nb_aretes(), Zone_VEF_PreP1b::nb_elem(), Zone_VEF_PreP1b::nb_som(), Array_base::NOCOPY_NOINIT, SolveurSys::nommer(), O_U_Ptr::non_nul(), ref_cast, SolveurSys::resoudre_systeme(), second_membre(), TRUSTArray< _TYPE_ >::size_array(), Deriv_::typer(), Deriv_SolveurSys_base::valeur(), and Zone_dis_base::zone().
Referenced by Champ_P1iP1B_implementation::filtrage().
second_membre()
double second_membre (const Zone_VEF_PreP1b & zone_VEF, ArrOfDouble & Pa, DoubleVect & secmem)
Definition at line 311 of file Champ_P1iP1B_implementation.cpp.
{
  int nb_arete_tot = zone_VEF.zone().nb_aretes_tot();
  const IntTab& aretes_som=zone_VEF.zone().aretes_som();
  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
  const Domaine& dom=zone_VEF.zone().domaine();
  secmem=0;
// On parcourt toutes les aretes non periodiques
  for(int arete=0; arete<nb_arete_tot; arete++)
    {
      if (renum_arete_perio[arete]==arete)
        {
          double x=Pa[arete];
          int som1=dom.get_renum_som_perio(aretes_som(arete, 0));
          int som2=dom.get_renum_som_perio(aretes_som(arete, 1));
          secmem(som1)+=x;
          secmem(som2)+=x;
        }
    }
  secmem*=coeff;
  secmem.echange_espace_virtuel();
  double norme=mp_norme_vect(secmem);
// Cerr << "||somme Pa||= " << norme << finl;
  return norme;
}
References Zone::aretes_som(), coeff, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), mp_norme_vect(), Zone::nb_aretes_tot(), norme(), and Zone_dis_base::zone().
Referenced by corriger(), and SolveurPP1B::resoudre_systeme().
Variable Documentation
coeff
double coeff = 4. / 5. static
Definition at line 309 of file Champ_P1iP1B_implementation.cpp.
Referenced by CSR_Builder::add_coeff(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face_Penalise::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_antidiffusion(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes_internes(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Solveur_Masse_base::appliquer(), Assembleur_P_VDF_Q4::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Simpler_Base::assembler_matrice_pression_implicite(), Champ_front_contact_VEF::calcul_grads_locaux(), Equation_base::calculer_champ_conserve(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), Multiplicateur_diphasique_Friedel::coefficient(), Multiplicateur_diphasique_homogene::coefficient(), Multiplicateur_diphasique_Lottes_Flinn::coefficient(), Multiplicateur_diphasique_Muhler_Steinhagen::coefficient(), Portance_interfaciale_Tomiyama::coefficient(), Frottement_interfacial_bulles::coefficient(), Frottement_interfacial_Sonnenburg::coefficient(), Frottement_interfacial_Tomiyama::coefficient(), Frottement_interfacial_Wallis::coefficient(), Frottement_interfacial_Weber::coefficient(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), convbisimplicite(), T_It_VDF_Face< _TYPE_ >::corriger_coeffs_fa7_elem_periodicite_(), descente(), descente_assert(), descente_assert_precond_diag(), descente_bloc_extradiag_assert(), descente_diag_ok_assert(), descente_generique(), descente_precond_diag(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Zone_VEF_PreP1b::discretiser(), SETS::eliminer(), Op_Diff_VDF_Face_Axi_base::fill_coeff_matrice_morse(), Op_Dift_VDF_Face_Axi_base::fill_coeff_matrice_morse(), T_It_VDF_Face< _TYPE_ >::fill_coeff_matrice_morse(), T_It_VDF_Elem< _TYPE_ >::fill_flux_tables_(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), inverser_par_diagonale(), Piso::iterer_NS(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl_(), Source_PDF_EF::multiply_coeff_volume(), operation01(), operation11(), Matrice_Morse::operator+=(), Convection_Diffusion_Temperature::penalisation_L2(), Navier_Stokes_std::preparer_calcul(), range(), remontee(), remontee_assert(), remontee_assert_precond_diag(), remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), remontee_generique(), remontee_precond_diag(), Matrice_Bloc::remplir(), second_membre(), SSOR::ssor(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), traite_diagonale(), and Convection_Diffusion_Temperature::transport_ibc().
coeff_inv
double coeff_inv = 1 / coeff static
Definition at line 310 of file Champ_P1iP1B_implementation.cpp.
Referenced by corriger().