TRUST: src/Kernel/Champs_dis/Champ_implementation_Q1.cpp File Reference
Champ_implementation_Q1.cpp File Reference
#include <Champ_implementation_Q1.h>
#include <Domaine.h>
#include <Linear_algebra_tools.h>
#include <Linear_algebra_tools_impl.h>
Functions
void calcul_plan_quadra (Vecteur3 &coeff_plan, double &d, int cell, const IntTab &cells, const DoubleTab &nodes, int dir)
void calcul_plan_hexa (Vecteur3 &coeff_plan, double &d, int cell, const IntTab &cells, const DoubleTab &nodes, int dir)
Variables
static int faces_sommets_quadra [4][2]
static int faces_sommets_hexa [6][4]
static int info =0
Function Documentation
calcul_plan_hexa()
void calcul_plan_hexa (Vecteur3 & coeff_plan, double & d, int cell, const IntTab & cells, const DoubleTab & nodes, int dir)
Definition at line 109 of file Champ_implementation_Q1.cpp.
{
// Plan 012
  int s0=cells(cell,faces_sommets_hexa[dir][0]);
  int s1=cells(cell,faces_sommets_hexa[dir][1]);
  int s2=cells(cell,faces_sommets_hexa[dir][2]);
  Vecteur3 S0(nodes(s0,0),nodes(s0,1),nodes(s0,2));
  Vecteur3 S0S1(nodes(s1,0)-S0[0],nodes(s1,1)-S0[1],nodes(s1,2)-S0[2]);
  Vecteur3 S0S2(nodes(s2,0)-S0[0],nodes(s2,1)-S0[1],nodes(s2,2)-S0[2]);
  Vecteur3::produit_vectoriel(S0S1,S0S2,coeff_plan);
  coeff_plan*=(1./coeff_plan.length());
  d=-Vecteur3::produit_scalaire(coeff_plan,S0);
}
References faces_sommets_hexa, Vecteur3::length(), Vecteur3::produit_scalaire(), and Vecteur3::produit_vectoriel().
Referenced by Champ_implementation_Q1::value_interpolation().
calcul_plan_quadra()
void calcul_plan_quadra (Vecteur3 & coeff_plan, double & d, int cell, const IntTab & cells, const DoubleTab & nodes, int dir)
Definition at line 82 of file Champ_implementation_Q1.cpp.
{
// Plan 012
  int s0=cells(cell,faces_sommets_quadra[dir][0]);
  int s1=cells(cell,faces_sommets_quadra[dir][1]);
  double S0x=nodes(s0,0);
  double S0y=nodes(s0,1);
  double SOS1x=nodes(s1,0)-S0x;
  double SOS1y=nodes(s1,1)-S0y;
  double len=sqrt(SOS1x*SOS1x+SOS1y*SOS1y);
  coeff_plan.set(-SOS1y/len,SOS1x/len,0);
  d=-(S0x*coeff_plan[0]+S0y*coeff_plan[1]);
}
References faces_sommets_quadra, and Vecteur3::set().
Referenced by Champ_implementation_Q1::value_interpolation().
Variable Documentation
faces_sommets_hexa
int faces_sommets_hexa[6][4] static
Initial value:
=
{
  { 0, 2, 4, 6 },
  { 0, 1, 4, 5 },
  { 0, 1, 2, 3 },
  { 1, 3, 5, 7 },
  { 2, 3, 6, 7 },
  { 4, 5, 6, 7 }
}
Definition at line 99 of file Champ_implementation_Q1.cpp.
Referenced by calcul_plan_hexa().
faces_sommets_quadra
int faces_sommets_quadra[4][2] static
Initial value:
=
{
  { 0, 2 },
  { 0, 1 },
  { 1, 3 },
  { 2, 3 }
}
Definition at line 71 of file Champ_implementation_Q1.cpp.
Referenced by calcul_plan_quadra().
info
int info =0 static
Definition at line 262 of file Champ_implementation_Q1.cpp.
Referenced by Statistiques::begin_count_(), crit_err_hdlr(), Champ_implementation_Q1::form_function(), kersol(), and rebuild_liste_noms().