TRUST: src/VDF/Champs/Champ_Face3.cpp File Reference
Champ_Face3.cpp File Reference
#include <Champ_Face.h>
#include <Champ_Uniforme.h>
#include <Zone_Cl_VDF.h>
#include <Dirichlet_paroi_fixe.h>
#include <Fluide_base.h>
#include <Equation_base.h>
#include <Mod_turb_hyd_base.h>
#include <distances_VDF.h>
Functions
void calrotord2centelemdim2 (DoubleTab &rot, const DoubleTab &val, const Zone_VDF &zone_VDF, int nb_elem, const IntTab &face_voisins, const IntTab &elem_faces)
void calcul_interne3D (int num_elem, int elx0, int elx1, int ely0, int ely1, int elz0, int elz1, const Zone_VDF &zone_VDF, const DoubleTab &val, DoubleTab &rot)
void calcul_bord3D (int num_elem, int elx0, int elx1, int ely0, int ely1, int elz0, int elz1, const Zone_VDF &zone_VDF, const DoubleTab &val, DoubleTab &rot)
void calrotord2centelemdim3 (DoubleTab &rot, const DoubleTab &val, const Zone_VDF &zone_VDF, int nb_elem, const IntTab &face_voisins, const IntTab &elem_faces)
Function Documentation
calcul_bord3D()
void calcul_bord3D (int num_elem, int elx0, int elx1, int ely0, int ely1, int elz0, int elz1, const Zone_VDF & zone_VDF, const DoubleTab & val, DoubleTab & rot)
< elx1 = -1 et elx0 != -1
< ely1 = -1 et ely0 != -1
< elz1 = -1 et elz0 != -1
< ely1 = -1 et ely0 != -1
< elz1 = -1 et elz0 != -1
Definition at line 117 of file Champ_Face3.cpp.
{
  const IntTab& elem_faces = zone_VDF.elem_faces();
  double delta_x_0,delta_x_1,delta_y_0,delta_y_1,delta_z_0,delta_z_1;
  double delta_x,delta_y,delta_z;
  double deriv_wy,deriv_vz,deriv_uz,deriv_wx,deriv_vx,deriv_uy;
  deriv_wy = 0;
  deriv_vz = 0;
  deriv_uz = 0;
  deriv_wx = 0;
  deriv_vx = 0;
  deriv_uy = 0;
// Traitement des elements bord
  if ( (elx0 == -1) || (elx1 == -1) )
    {
      if (elx0 == -1)
        {
          if (elx1 != -1)
            {
              delta_x_1 = zone_VDF.dist_elem_period(elx1,num_elem,0);
              deriv_vx = (val(elem_faces(elx1,1))-val(elem_faces(num_elem,1))
                          + val(elem_faces(elx1,4))-val(elem_faces(num_elem,4)));
              deriv_vx *= 0.5/delta_x_1;
              deriv_wx = (val(elem_faces(elx1,2))-val(elem_faces(num_elem,2))
                          + val(elem_faces(elx1,5))-val(elem_faces(num_elem,5)));
              deriv_wx *= 0.5/delta_x_1;
            }
          else
            {
              deriv_vx = 0;
              deriv_wx = 0;
            }
        }
      else //!< elx1 = -1 et elx0 != -1
        {
          delta_x_0 = zone_VDF.dist_elem_period(num_elem,elx0,0);
          deriv_vx = (val(elem_faces(num_elem,1))-val(elem_faces(elx0,1))
                      + val(elem_faces(num_elem,4))-val(elem_faces(elx0,4)));
          deriv_vx *= 0.5/delta_x_0;
          deriv_wx = (val(elem_faces(num_elem,2))-val(elem_faces(elx0,2))
                      + val(elem_faces(num_elem,5))-val(elem_faces(elx0,5)));
          deriv_wx *= 0.5/delta_x_0;
        }
      if ( (ely0 == -1) || (ely1 == -1) )
        {
          if (ely0 == -1)
            {
              if (ely1 != -1)
                {
                  delta_y_1 = zone_VDF.dist_elem_period(ely1,num_elem,1);
                  deriv_uy = (val(elem_faces(ely1,0))-val(elem_faces(num_elem,0))
                              + val(elem_faces(ely1,3))-val(elem_faces(num_elem,3)));
                  deriv_uy *= 0.5/delta_y_1;
                  deriv_wy = (val(elem_faces(ely1,2))-val(elem_faces(num_elem,2))
                              + val(elem_faces(ely1,5))-val(elem_faces(num_elem,5)));
                  deriv_wy *= 0.5/delta_y_1;
                }
              else
                {
                  deriv_uy = 0;
                  deriv_wy = 0;
                }
            }
          else //!< ely1 = -1 et ely0 != -1
            {
              delta_y_0 = zone_VDF.dist_elem_period(num_elem,ely0,1);
              deriv_uy = (val(elem_faces(num_elem,0))-val(elem_faces(ely0,0))
                          + val(elem_faces(num_elem,3))-val(elem_faces(ely0,3)));
              deriv_uy *= 0.5/delta_y_0;
              deriv_wy = (val(elem_faces(num_elem,2))-val(elem_faces(ely0,2))
                          + val(elem_faces(num_elem,5))-val(elem_faces(ely0,5)));
              deriv_wy *= 0.5/delta_y_0;
            }
        }
      else
        {
          delta_y_0 = zone_VDF.dist_elem_period(num_elem,ely0,1);
          delta_y_1 = zone_VDF.dist_elem_period(ely1,num_elem,1);
          delta_y = (delta_y_1-delta_y_0)*(delta_y_1+delta_y_0)/(delta_y_1*delta_y_0);
          deriv_uy = (delta_y_0/delta_y_1*val(elem_faces(ely1,0))
                      + delta_y*val(elem_faces(num_elem,0))
                      - delta_y_1/delta_y_0*val(elem_faces(ely0,0)));
          deriv_uy += (delta_y_0/delta_y_1*val(elem_faces(ely1,3))
                       + delta_y*val(elem_faces(num_elem,3))
                       - delta_y_1/delta_y_0*val(elem_faces(ely0,3)));
          deriv_uy *= 0.5/(delta_y_0 + delta_y_1);
          deriv_wy = (delta_y_0/delta_y_1*val(elem_faces(ely1,2))
                      + delta_y*val(elem_faces(num_elem,2))
                      - delta_y_1/delta_y_0*val(elem_faces(ely0,2)));
          deriv_wy += (delta_y_0/delta_y_1*val(elem_faces(ely1,5))
                       + delta_y*val(elem_faces(num_elem,5))
                       - delta_y_1/delta_y_0*val(elem_faces(ely0,5)));
          deriv_wy *= 0.5/(delta_y_0 + delta_y_1);
        }
      if ( (elz0 == -1) || (elz1 == -1) )
        {
          if (elz0 == -1)
            {
              if (elz1 != -1)
                {
                  delta_z_1 = zone_VDF.dist_elem_period(elz1,num_elem,2);
                  deriv_uz = (val(elem_faces(elz1,0))-val(elem_faces(num_elem,0))
                              + val(elem_faces(elz1,3))-val(elem_faces(num_elem,3)));
                  deriv_uz *= 0.5/delta_z_1;
                  deriv_vz = (val(elem_faces(elz1,1))-val(elem_faces(num_elem,1))
                              + val(elem_faces(elz1,4))-val(elem_faces(num_elem,4)));
                  deriv_vz *= 0.5/delta_z_1;
                }
              else
                {
                  deriv_uz = 0;
                  deriv_vz = 0;
                }
            }
          else //!< elz1 = -1 et elz0 != -1
            {
              delta_z_0 = zone_VDF.dist_elem_period(num_elem,elz0,2);
              deriv_uz = (val(elem_faces(num_elem,0))-val(elem_faces(elz0,0))
                          + val(elem_faces(num_elem,3))-val(elem_faces(elz0,3)));
              deriv_uz *= 0.5/delta_z_0;
              deriv_vz =(val(elem_faces(num_elem,1))-val(elem_faces(elz0,1))
                         + val(elem_faces(num_elem,4))-val(elem_faces(elz0,4)));
              deriv_vz *= 0.5/delta_z_0;
            }
        }
      else
        {
          delta_z_0 = zone_VDF.dist_elem_period(num_elem,elz0,2);
          delta_z_1 = zone_VDF.dist_elem_period(elz1,num_elem,2);
          delta_z = (delta_z_1-delta_z_0)*(delta_z_1+delta_z_0)/(delta_z_1*delta_z_0);
          deriv_uz = (delta_z_0/delta_z_1*val(elem_faces(elz1,0))
                      + delta_z*val(elem_faces(num_elem,0))
                      - delta_z_1/delta_z_0*val(elem_faces(elz0,0)));
          deriv_uz += (delta_z_0/delta_z_1*val(elem_faces(elz1,3))
                       + delta_z*val(elem_faces(num_elem,3))
                       - delta_z_1/delta_z_0*val(elem_faces(elz0,3)));
          deriv_uz *= 0.5/(delta_z_0 + delta_z_1);
          deriv_vz = (delta_z_0/delta_z_1*val(elem_faces(elz1,1))
                      + delta_z*val(elem_faces(num_elem,1))
                      - delta_z_1/delta_z_0*val(elem_faces(elz0,1)));
          deriv_vz += (delta_z_0/delta_z_1*val(elem_faces(elz1,4))
                       + delta_z*val(elem_faces(num_elem,4))
                       - delta_z_1/delta_z_0*val(elem_faces(elz0,4)));
          deriv_vz *= 0.5/(delta_z_0 + delta_z_1);
        }
    }
  else if ( (ely0 == -1) || (ely1 == -1) )
    {
      if (ely0 == -1)
        {
          if (ely1 != -1)
            {
              delta_y_1 = zone_VDF.dist_elem_period(ely1,num_elem,1);
              deriv_uy = (val(elem_faces(ely1,0))-val(elem_faces(num_elem,0))
                          + val(elem_faces(ely1,3))-val(elem_faces(num_elem,3)));
              deriv_uy *= 0.5/delta_y_1;
              deriv_wy = (val(elem_faces(ely1,2))-val(elem_faces(num_elem,2))
                          + val(elem_faces(ely1,5))-val(elem_faces(num_elem,5)));
              deriv_wy *= 0.5/delta_y_1;
            }
          else
            {
              deriv_uy = 0;
              deriv_wy = 0;
            }
        }
      else  //!< ely1 = -1 et ely0 != -1
        {
          delta_y_0 = zone_VDF.dist_elem_period(num_elem,ely0,1);
          deriv_uy = (val(elem_faces(num_elem,0))-val(elem_faces(ely0,0))
                      + val(elem_faces(num_elem,3))-val(elem_faces(ely0,3)));
          deriv_uy *= 0.5/delta_y_0;
          deriv_wy = (val(elem_faces(num_elem,2))-val(elem_faces(ely0,2))
                      + val(elem_faces(num_elem,5))-val(elem_faces(ely0,5)));
          deriv_wy *= 0.5/delta_y_0;
        }
      delta_x_0 = zone_VDF.dist_elem_period(num_elem,elx0,0);
      delta_x_1 = zone_VDF.dist_elem_period(elx1,num_elem,0);
      delta_x = (delta_x_1-delta_x_0)*(delta_x_1+delta_x_0)/(delta_x_1*delta_x_0);
      deriv_wx = (delta_x_0/delta_x_1*val(elem_faces(elx1,2))
                  + delta_x*val(elem_faces(num_elem,2))
                  - delta_x_1/delta_x_0*val(elem_faces(elx0,2)));
      deriv_wx += (delta_x_0/delta_x_1*val(elem_faces(elx1,5))
                   + delta_x*val(elem_faces(num_elem,5))
                   - delta_x_1/delta_x_0*val(elem_faces(elx0,5)));
      deriv_wx *= 0.5/(delta_x_0 + delta_x_1);
      deriv_vx = (delta_x_0/delta_x_1*val(elem_faces(elx1,1))
                  + delta_x*val(elem_faces(num_elem,1))
                  - delta_x_1/delta_x_0*val(elem_faces(elx0,1)));
      deriv_vx += (delta_x_0/delta_x_1*val(elem_faces(elx1,4))
                   + delta_x*val(elem_faces(num_elem,4))
                   - delta_x_1/delta_x_0*val(elem_faces(elx0,4)));
      deriv_vx *= 0.5/(delta_x_0 + delta_x_1);
      if ( (elz0 == -1) || (elz1 == -1) )
        {
          if (elz0 == -1)
            {
              if (elz1 != -1)
                {
                  delta_z_1 = zone_VDF.dist_elem_period(elz1,num_elem,2);
                  deriv_uz = (val(elem_faces(elz1,0))-val(elem_faces(num_elem,0))
                              + val(elem_faces(elz1,3))-val(elem_faces(num_elem,3)));
                  deriv_uz *= 0.5/delta_z_1;
                  deriv_vz = (val(elem_faces(elz1,1))-val(elem_faces(num_elem,1))
                              + val(elem_faces(elz1,4))-val(elem_faces(num_elem,4)));
                  deriv_vz *= 0.5/delta_z_1;
                }
              else
                {
                  deriv_uz = 0;
                  deriv_vz = 0;
                }
            }
          else
            {
              delta_z_0 = zone_VDF.dist_elem_period(num_elem,elz0,2);
              deriv_uz = (val(elem_faces(num_elem,0))-val(elem_faces(elz0,0))
                          + val(elem_faces(num_elem,3))-val(elem_faces(elz0,3)));
              deriv_uz *= 0.5/delta_z_0;
              deriv_vz =(val(elem_faces(num_elem,1))-val(elem_faces(elz0,1))
                         + val(elem_faces(num_elem,4))-val(elem_faces(elz0,4)));
              deriv_vz *= 0.5/delta_z_0;
            }
        }
      else
        {
          delta_z_0 = zone_VDF.dist_elem_period(num_elem,elz0,2);
          delta_z_1 = zone_VDF.dist_elem_period(elz1,num_elem,2);
          delta_z = (delta_z_1-delta_z_0)*(delta_z_1+delta_z_0)/(delta_z_1*delta_z_0);
          deriv_uz = (delta_z_0/delta_z_1*val(elem_faces(elz1,0))
                      + delta_z*val(elem_faces(num_elem,0))
                      - delta_z_1/delta_z_0*val(elem_faces(elz0,0)));
          deriv_uz += (delta_z_0/delta_z_1*val(elem_faces(elz1,3))
                       + delta_z*val(elem_faces(num_elem,3))
                       - delta_z_1/delta_z_0*val(elem_faces(elz0,3)));
          deriv_uz *= 0.5/(delta_z_0 + delta_z_1);
          deriv_vz = (delta_z_0/delta_z_1*val(elem_faces(elz1,1))
                      + delta_z*val(elem_faces(num_elem,1))
                      - delta_z_1/delta_z_0*val(elem_faces(elz0,1)));
          deriv_vz += (delta_z_0/delta_z_1*val(elem_faces(elz1,4))
                       + delta_z*val(elem_faces(num_elem,4))
                       - delta_z_1/delta_z_0*val(elem_faces(elz0,4)));
          deriv_vz *= 0.5/(delta_z_0 + delta_z_1);
        }
    }
  else if ( (elz0 == -1) || (elz1 == -1) )
    {
      if (elz0 == -1)
        {
          if (elz1 != -1)
            {
              delta_z_1 = zone_VDF.dist_elem_period(elz1,num_elem,2);
              deriv_uz = (val(elem_faces(elz1,0))-val(elem_faces(num_elem,0))
                          + val(elem_faces(elz1,3))-val(elem_faces(num_elem,3)));
              deriv_uz *= 0.5/delta_z_1;
              deriv_vz = (val(elem_faces(elz1,1))-val(elem_faces(num_elem,1))
                          + val(elem_faces(elz1,4))-val(elem_faces(num_elem,4)));
              deriv_vz *= 0.5/delta_z_1;
            }
          else
            {
              deriv_uz = 0;
              deriv_vz = 0;
            }
        }
      else //!< elz1 = -1 et elz0 != -1
        {
          delta_z_0 = zone_VDF.dist_elem_period(num_elem,elz0,2);
          deriv_uz = (val(elem_faces(num_elem,0))-val(elem_faces(elz0,0))
                      + val(elem_faces(num_elem,3))-val(elem_faces(elz0,3)));
          deriv_uz *= 0.5/delta_z_0;
          deriv_vz =(val(elem_faces(num_elem,1))-val(elem_faces(elz0,1))
                     + val(elem_faces(num_elem,4))-val(elem_faces(elz0,4)));
          deriv_vz *= 0.5/delta_z_0;
        }
      delta_x_0 = zone_VDF.dist_elem_period(num_elem,elx0,0);
      delta_x_1 = zone_VDF.dist_elem_period(elx1,num_elem,0);
      delta_x = (delta_x_1-delta_x_0)*(delta_x_1+delta_x_0)/(delta_x_1*delta_x_0);
      deriv_wx = (delta_x_0/delta_x_1*val(elem_faces(elx1,2))
                  + delta_x*val(elem_faces(num_elem,2))
                  - delta_x_1/delta_x_0*val(elem_faces(elx0,2)));
      deriv_wx += (delta_x_0/delta_x_1*val(elem_faces(elx1,5))
                   + delta_x*val(elem_faces(num_elem,5))
                   - delta_x_1/delta_x_0*val(elem_faces(elx0,5)));
      deriv_wx *= 0.5/(delta_x_0 + delta_x_1);
      deriv_vx = (delta_x_0/delta_x_1*val(elem_faces(elx1,1))
                  + delta_x*val(elem_faces(num_elem,1))
                  - delta_x_1/delta_x_0*val(elem_faces(elx0,1)));
      deriv_vx += (delta_x_0/delta_x_1*val(elem_faces(elx1,4))
                   + delta_x*val(elem_faces(num_elem,4))
                   - delta_x_1/delta_x_0*val(elem_faces(elx0,4)));
      deriv_vx *= 0.5/(delta_x_0 + delta_x_1);
      delta_y_0 = zone_VDF.dist_elem_period(num_elem,ely0,1);
      delta_y_1 = zone_VDF.dist_elem_period(ely1,num_elem,1);
      delta_y = (delta_y_1-delta_y_0)*(delta_y_1+delta_y_0)/(delta_y_1*delta_y_0);
      deriv_wy = (delta_y_0/delta_y_1*val(elem_faces(ely1,2))
                  + delta_y*val(elem_faces(num_elem,2))
                  - delta_y_1/delta_y_0*val(elem_faces(ely0,2)));
      deriv_wy += (delta_y_0/delta_y_1*val(elem_faces(ely1,5))
                   + delta_y*val(elem_faces(num_elem,5))
                   - delta_y_1/delta_y_0*val(elem_faces(ely0,5)));
      deriv_wy *= 0.5/(delta_y_0 + delta_y_1);
      deriv_uy = (delta_y_0/delta_y_1*val(elem_faces(ely1,0))
                  + delta_y*val(elem_faces(num_elem,0))
                  - delta_y_1/delta_y_0*val(elem_faces(ely0,0)));
      deriv_uy += (delta_y_0/delta_y_1*val(elem_faces(ely1,3))
                   + delta_y*val(elem_faces(num_elem,3))
                   - delta_y_1/delta_y_0*val(elem_faces(ely0,3)));
      deriv_uy *= 0.5/(delta_y_0 + delta_y_1);
    }
  rot(num_elem,0) = deriv_wy - deriv_vz;
  rot(num_elem,1) = deriv_uz - deriv_wx;
  rot(num_elem,2) = deriv_vx - deriv_uy;
}
References Zone_VDF::dist_elem_period(), and Zone_VF::elem_faces().
Referenced by calrotord2centelemdim3().
calcul_interne3D()
void calcul_interne3D (int num_elem, int elx0, int elx1, int ely0, int ely1, int elz0, int elz1, const Zone_VDF & zone_VDF, const DoubleTab & val, DoubleTab & rot)
Definition at line 31 of file Champ_Face3.cpp.
{
  const IntTab& elem_faces = zone_VDF.elem_faces();
  double delta_x_0,delta_x_1,delta_y_0,delta_y_1,delta_z_0,delta_z_1;
  double delta_x,delta_y,delta_z;
  double deriv_wy,deriv_vz,deriv_uz,deriv_wx,deriv_vx,deriv_uy;
  deriv_wy = 0;
  deriv_vz = 0;
  deriv_uz = 0;
  deriv_wx = 0;
  deriv_vx = 0;
  deriv_uy = 0;
  delta_x_0 = zone_VDF.dist_elem_period(num_elem,elx0,0);
  delta_x_1 = zone_VDF.dist_elem_period(elx1,num_elem,0);
  delta_y_0 = zone_VDF.dist_elem_period(num_elem,ely0,1);
  delta_y_1 = zone_VDF.dist_elem_period(ely1,num_elem,1);
  delta_z_0 = zone_VDF.dist_elem_period(num_elem,elz0,2);
  delta_z_1 = zone_VDF.dist_elem_period(elz1,num_elem,2);
  delta_x = (delta_x_1-delta_x_0)*(delta_x_1+delta_x_0)/(delta_x_1*delta_x_0);
  delta_y = (delta_y_1-delta_y_0)*(delta_y_1+delta_y_0)/(delta_y_1*delta_y_0);
  delta_z = (delta_z_1-delta_z_0)*(delta_z_1+delta_z_0)/(delta_z_1*delta_z_0);
  deriv_vz = (delta_z_0/delta_z_1*val(elem_faces(elz1,1))
              + delta_z*val(elem_faces(num_elem,1))
              - delta_z_1/delta_z_0*val(elem_faces(elz0,1)));
  deriv_vz += (delta_z_0/delta_z_1*val(elem_faces(elz1,4))
               + delta_z*val(elem_faces(num_elem,4))
               - delta_z_1/delta_z_0*val(elem_faces(elz0,4)));
  deriv_vz *= 0.5/(delta_z_0 + delta_z_1);
  deriv_wy = (delta_y_0/delta_y_1*val(elem_faces(ely1,2))
              + delta_y*val(elem_faces(num_elem,2))
              - delta_y_1/delta_y_0*val(elem_faces(ely0,2)));
  deriv_wy += (delta_y_0/delta_y_1*val(elem_faces(ely1,5))
               + delta_y*val(elem_faces(num_elem,5))
               - delta_y_1/delta_y_0*val(elem_faces(ely0,5)));
  deriv_wy *= 0.5/(delta_y_0 + delta_y_1);
  deriv_uz = (delta_z_0/delta_z_1*val(elem_faces(elz1,0))
              + delta_z*val(elem_faces(num_elem,0))
              - delta_z_1/delta_z_0*val(elem_faces(elz0,0)));
  deriv_uz += (delta_z_0/delta_z_1*val(elem_faces(elz1,3))
               + delta_z*val(elem_faces(num_elem,3))
               - delta_z_1/delta_z_0*val(elem_faces(elz0,3)));
  deriv_uz *= 0.5/(delta_z_0 + delta_z_1);
  deriv_wx = (delta_x_0/delta_x_1*val(elem_faces(elx1,2))
              + delta_x*val(elem_faces(num_elem,2))
              - delta_x_1/delta_x_0*val(elem_faces(elx0,2)));
  deriv_wx += (delta_x_0/delta_x_1*val(elem_faces(elx1,5))
               + delta_x*val(elem_faces(num_elem,5))
               - delta_x_1/delta_x_0*val(elem_faces(elx0,5)));
  deriv_wx *= 0.5/(delta_x_0 + delta_x_1);
  deriv_vx = (delta_x_0/delta_x_1*val(elem_faces(elx1,1))
              + delta_x*val(elem_faces(num_elem,1))
              - delta_x_1/delta_x_0*val(elem_faces(elx0,1)));
  deriv_vx += (delta_x_0/delta_x_1*val(elem_faces(elx1,4))
               + delta_x*val(elem_faces(num_elem,4))
               - delta_x_1/delta_x_0*val(elem_faces(elx0,4)));
  deriv_vx *= 0.5/(delta_x_0 + delta_x_1);
  deriv_uy = (delta_y_0/delta_y_1*val(elem_faces(ely1,0))
              + delta_y*val(elem_faces(num_elem,0))
              - delta_y_1/delta_y_0*val(elem_faces(ely0,0)));
  deriv_uy += (delta_y_0/delta_y_1*val(elem_faces(ely1,3))
               + delta_y*val(elem_faces(num_elem,3))
               - delta_y_1/delta_y_0*val(elem_faces(ely0,3)));
  deriv_uy *= 0.5/(delta_y_0 + delta_y_1);
  rot(num_elem,0) = deriv_wy - deriv_vz;
  rot(num_elem,1) = deriv_uz - deriv_wx;
  rot(num_elem,2) = deriv_vx - deriv_uy;
}
References Zone_VDF::dist_elem_period(), and Zone_VF::elem_faces().
Referenced by calrotord2centelemdim3().
calrotord2centelemdim2()
void calrotord2centelemdim2 (DoubleTab & rot, const DoubleTab & val, const Zone_VDF & zone_VDF, int nb_elem, const IntTab & face_voisins, const IntTab & elem_faces)
Definition at line 427 of file Champ_Face2.cpp.
{
  if(rot.dimension(0)!=nb_elem)
    rot.resize(nb_elem);
  int elx0,elx1,ely0,ely1;
  for (int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      elx0 = face_voisins(elem_faces(num_elem,0),0);
      elx1 = face_voisins(elem_faces(num_elem,2),1);
      ely0 = face_voisins(elem_faces(num_elem,1),0);
      ely1 = face_voisins(elem_faces(num_elem,3),1);
      if ( (elx0 != -1) && (elx1 != -1) && (ely0 != -1)
           && (ely1 != -1))
// Cas d'un element interne
        calcul_interne2D(num_elem,elx0,elx1,ely0,ely1,zone_VDF,val,rot);
      else
        calcul_bord2D(num_elem,elx0,elx1,ely0,ely1,zone_VDF,val,rot);
    }
}
References calcul_bord2D(), calcul_interne2D(), TRUSTTab< _TYPE_ >::dimension(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Champ_Face::calculer_rotationnel_ordre2_centre_element().
calrotord2centelemdim3()
void calrotord2centelemdim3 (DoubleTab & rot, const DoubleTab & val, const Zone_VDF & zone_VDF, int nb_elem, const IntTab & face_voisins, const IntTab & elem_faces)
Definition at line 462 of file Champ_Face3.cpp.
{
  if(rot.dimension(0)!=nb_elem)
    rot.resize(nb_elem, 3);
  int elx0,elx1,ely0,ely1,elz0,elz1;
  for (int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      elx0 = face_voisins(elem_faces(num_elem,0),0);
      elx1 = face_voisins(elem_faces(num_elem,3),1);
      ely0 = face_voisins(elem_faces(num_elem,1),0);
      ely1 = face_voisins(elem_faces(num_elem,4),1);
      elz0 = face_voisins(elem_faces(num_elem,2),0);
      elz1 = face_voisins(elem_faces(num_elem,5),1);
      if ( (elx0 != -1) && (elx1 != -1) && (ely0 != -1)
           && (ely1 != -1) && (elz0 != -1) && (elz1 != -1) )
// Cas d'un element interne
        calcul_interne3D(num_elem,elx0,elx1,ely0,ely1,elz0,elz1,zone_VDF,val,rot);
      else
        calcul_bord3D(num_elem,elx0,elx1,ely0,ely1,elz0,elz1,zone_VDF,val,rot);
    }
}
References calcul_bord3D(), calcul_interne3D(), TRUSTTab< _TYPE_ >::dimension(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Champ_Face::calculer_rotationnel_ordre2_centre_element().