TRUST: src/Kernel/Math/Check_espace_virtuel.h File Reference
Check_espace_virtuel.h File Reference
#include <Comm_Group.h>
#include <TRUSTVect.h>
Functions
int check_espace_virtuel_vect (const DoubleVect &v)
Verifie si le vecteur v a son espace virtuel a jour. Cette fonction doit etre appelee simultanement par tous les processeurs qui partagent le vecteur.
(pour cela, on cree une copie qu'on echange, puis on compare a l'original).
int check_espace_virtuel_vect (const IntVect &v)
Idem que check_espace_virtuel_vect(const DoubleVect & v)
void assert_invalide_items_non_calcules (DoubleVect &v, double valeur=0.)
Appelle remplir_items_non_calcules() si on est en
mode comm_check_enabled() ou en mode debug (NDEBUG non defini)
La "valeur" par defaut est censee provoquer une erreur si on
essaye de l'utiliser.
template<typename _TYPE_ >
void remplir_items_non_calcules_ (TRUSTVect< _TYPE_ > &v, _TYPE_ valeur)
template<typename _TYPE_ >
void remplir_items_non_calcules (TRUSTVect< _TYPE_ > &v, _TYPE_ valeur=0)
Remplit les "items non calcules" du tableau avec une valeur invalide. Ce sont tous les items qui ne sont pas repertories
dans v.get_md_vector().valeurs().get_items_to_compute(). (items non calcules par les operations par defaut sur les vecteurs, en general ce sont les items virtuels)
Il est conseille d'appliquer cette methode a la fin des fonctions qui ne renvoient pas un espace virtuel a jour avec declare_espace_virtuel_invalide(...))
de sorte a provoquer une erreur si l'espace virtuel est utilise.
template<typename _TYPE_ >
void assert_espace_virtuel_vect (const TRUSTVect< _TYPE_ > &v)
en mode comm_check_enabled(), verifie si l'espace virtuel du vecteur est a jour, si ce n'est pas le cas, exit().
Ce test n'est fait qu'en mode comm_check_enabled() car il necessite des communications.
template<typename _TYPE_ >
void declare_espace_virtuel_invalide (TRUSTVect< _TYPE_ > &v)
When compiled without NDEBUG or when running with check_enabled flag,
fills all "not computed" items with an invalid value (ie, items that are not VECT_REAL_ITEMS, usually, these are the virtual items).
You should call this method whenever you compute some field values but you don't compute or update the virtual space.
Function Documentation
assert_espace_virtuel_vect()
template<typename _TYPE_ > void assert_espace_virtuel_vect (const TRUSTVect< _TYPE_ > & v) inline
en mode comm_check_enabled(), verifie si l'espace virtuel du vecteur est a jour, si ce n'est pas le cas, exit().
Ce test n'est fait qu'en mode comm_check_enabled() car il necessite des communications.
Definition at line 65 of file Check_espace_virtuel.h.
{
  if (Comm_Group::check_enabled())
    {
      if (! check_espace_virtuel_vect(v))
        {
          Cerr << "Fatal error in assert_espace_virtuel_vect: virtual space of this vector is not up to date." << finl;
          Process::barrier();
          Process::exit();
        }
    }
}
References Process::barrier(), Cerr, Comm_Group::check_enabled(), check_espace_virtuel_vect(), Process::exit(), and finl.
Referenced by Op_Grad_EF::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Perte_Charge_VEF::contribuer_a_avec(), Zone_VEF_PreP1b::discretiser(), EOS_Tools_VDF::divu_discvit(), EOS_Tools_VEF::divu_discvit(), Matrice_Morse::inverse(), Zone_VEF_PreP1b::lecture_ok_arete(), PrecondSolv::preconditionner_(), Op_Diff_VEF_base::remplir_nu(), and Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1().
assert_invalide_items_non_calcules()
void assert_invalide_items_non_calcules (DoubleVect & v, double valeur = 0.)
Appelle remplir_items_non_calcules() si on est en
mode comm_check_enabled() ou en mode debug (NDEBUG non defini)
La "valeur" par defaut est censee provoquer une erreur si on
essaye de l'utiliser.
Definition at line 58 of file Check_espace_virtuel.cpp.
{
#ifdef NDEBUG
  if (Comm_Group::check_enabled())
    remplir_items_non_calcules(v, valeur);
#else
  remplir_items_non_calcules(v, valeur);
#endif
}
References Comm_Group::check_enabled(), remplir_items_non_calcules(), and valeur().
Referenced by Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Op_Diff_VDF_Face_base::ajouter_blocs(), and Op_Div_VEFP1B_Elem::ajouter_elem().
check_espace_virtuel_vect() [1/2]
int check_espace_virtuel_vect (const DoubleVect & v)
Verifie si le vecteur v a son espace virtuel a jour. Cette fonction doit etre appelee simultanement par tous les processeurs qui partagent le vecteur.
(pour cela, on cree une copie qu'on echange, puis on compare a l'original).
Definition at line 21 of file Check_espace_virtuel.cpp.
{
// On fait une copie:
  DoubleVect w(v);
// On echange
  w.echange_espace_virtuel();
// Norme de w :
  const double norme_w = norme_array(w);
// On compare : difference entre les deux vecteurs au sens
// ArrOfDouble (pas d'echange espace virtuel)
  w.ArrOfDouble::operator-=(v);
  const double ecart = norme_array(w);
  if (ecart > (norme_w + 1e-30) * 1e-12)
    return 0;
  else
    return 1;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), and norme_array().
Referenced by assert_espace_virtuel_vect(), Assembleur_P_VEFPreP1B::changer_base_pression(), and Assembleur_P_VEFPreP1B::changer_base_pression_inverse().
check_espace_virtuel_vect() [2/2]
int check_espace_virtuel_vect (const IntVect & v)
Idem que check_espace_virtuel_vect(const DoubleVect & v)
Definition at line 40 of file Check_espace_virtuel.cpp.
{
// On fait une copie:
  IntVect w(v);
// On echange
  w.echange_espace_virtuel();
// On compare:
  const int n = v.size_array();
  for (int i = 0; i < n; i++)
    if (v[i] != w[i])
      return 0;
  return 1;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), and TRUSTArray< _TYPE_ >::size_array().
declare_espace_virtuel_invalide()
template<typename _TYPE_ > void declare_espace_virtuel_invalide (TRUSTVect< _TYPE_ > & v) inline
When compiled without NDEBUG or when running with check_enabled flag,
fills all "not computed" items with an invalid value (ie, items that are not VECT_REAL_ITEMS, usually, these are the virtual items).
You should call this method whenever you compute some field values but you don't compute or update the virtual space.
Definition at line 82 of file Check_espace_virtuel.h.
{
  const _TYPE_ valeur = (std::is_same<_TYPE_,double>::value) ? -98765.4321 : -1999999999;
#ifdef NDEBUG
  if (Comm_Group::check_enabled())
    remplir_items_non_calcules(v, valeur);
#else
  remplir_items_non_calcules(v, valeur);
#endif
}
References Comm_Group::check_enabled(), remplir_items_non_calcules(), and valeur().
Referenced by Op_Div_EF::ajouter().
remplir_items_non_calcules()
template<typename _TYPE_ > void remplir_items_non_calcules (TRUSTVect< _TYPE_ > & v, _TYPE_ valeur = 0) inline
Remplit les "items non calcules" du tableau avec une valeur invalide. Ce sont tous les items qui ne sont pas repertories
dans v.get_md_vector().valeurs().get_items_to_compute(). (items non calcules par les operations par defaut sur les vecteurs, en general ce sont les items virtuels)
Il est conseille d'appliquer cette methode a la fin des fonctions qui ne renvoient pas un espace virtuel a jour avec declare_espace_virtuel_invalide(...))
de sorte a provoquer une erreur si l'espace virtuel est utilise.
Definition at line 57 of file Check_espace_virtuel.h.
{
  remplir_items_non_calcules_(v, valeur);
}
References remplir_items_non_calcules_(), and valeur().
Referenced by assert_invalide_items_non_calcules(), and declare_espace_virtuel_invalide().
remplir_items_non_calcules_()
template<typename _TYPE_ > void remplir_items_non_calcules_ (TRUSTVect< _TYPE_ > & v, _TYPE_ valeur) inline
Definition at line 28 of file Check_espace_virtuel.h.
{
  if (v.get_md_vector().non_nul())
    {
      const ArrOfInt& blocs = v.get_md_vector().valeur().get_items_to_compute();
      const int sz = blocs.size_array() / 2, line_size = v.line_size();
      int j = 0;
// Ne pas passer par operator[], sinon plantage si la valeur actuelle est invalide
      _TYPE_ *ptr = v.addr();
      for (int i = 0; i < sz; i++)
        {
// remplir les elements jusqu'au debut du bloc:
          const int j_fin = blocs[i*2] * line_size;
          assert(j >= 0 && j_fin <= v.size_array());
          for (; j < j_fin; j++) ptr[j] = valeur;
// Sauter a la fin du bloc
          j = blocs[i*2+1] * line_size;
        }
// Remplir les elements entre la fin du dernier bloc et la fin du vecteur
      const int j_fin = v.size_array();
      for (; j < j_fin; j++) ptr[j] = valeur;
    }
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector_base::get_items_to_compute(), TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), TRUSTArray< _TYPE_ >::size_array(), MD_Vector::valeur(), and valeur().
Referenced by remplir_items_non_calcules().