TRUST: Test_solveur Class Reference
Test_solveur Class Reference
#include <Solv_Optimal.h>
Public Member Functions
Test_solveur ()
< Car sinon conflit avec Petsc
~Test_solveur ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Test_solveur & self_cast (Objet_U &)
static const Test_solveur & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 38 of file Solv_Optimal.h.
Constructor & Destructor Documentation
Test_solveur()
Test_solveur::Test_solveur ()
< Car sinon conflit avec Petsc
Definition at line 27 of file Solv_Optimal.cpp.
~Test_solveur()
Test_solveur::~Test_solveur ()
Definition at line 27 of file Solv_Optimal.cpp.
Member Function Documentation
cree_instance()
Objet_U * Test_solveur::cree_instance () static
Definition at line 27 of file Solv_Optimal.cpp.
duplique()
int Test_solveur::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Solv_Optimal.cpp.
get_info()
const Type_info * Test_solveur::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Solv_Optimal.cpp.
info()
const Type_info * Test_solveur::info () static
Definition at line 27 of file Solv_Optimal.cpp.
interpreter()
Entree & Test_solveur::interpreter (Entree & is) override virtual
< On teste 2 fois un solveur car la premiere fois, le cout du preconditionnement peut penaliser
< nom du fichier contenant le second membre (Secmem.sa par defaut)
< nom du fichier contenant la matrice (Matrice.sa par defaut)
< nom du fichier contenant la solution (Solution.sa par defaut)
< nb de resolution pour mesurer le temps (un seul preconditionnemt)
< impr des solveurs
< pour specifier un solveur
< pour specifier un fichier contenant des solveurs
< genere le fichier de solveur avec un seuil donne
< verifie si la soulution trouvee par la resolution est telle que Ax -b < seuil_verification
< pas_de_solution_initiale : on n'initialise pas la resolution avec la solution
< dans le cas ou les fichiers sont ascii
Reimplemented from Interprete.
Definition at line 166 of file Solv_Optimal.cpp.
{
  Matrice matrice;
  DoubleVect secmem,solution;
  Nom fichier_secmem("Secmem.sa");
  Nom fichier_solution("Solution.sa");
  Nom fichier_matrice("Matrice.sa");
  Nom fichier_solveur;
  int pas_de_solution_init=0,ascii;
  double seuil_verification=DMAXFLOAT;
  SolveurSys solveur;
  double seuil_list=0;
  int limpr_;
  int nb_test=2; //!< On teste 2 fois un solveur car la premiere fois, le cout du preconditionnement peut penaliser
  Param  param((*this).que_suis_je());
  param.ajouter("fichier_secmem",&fichier_secmem);  //!< nom du fichier contenant le second membre (Secmem.sa par defaut)
  param.ajouter("fichier_matrice",&fichier_matrice);  //!< nom du fichier contenant la matrice (Matrice.sa par defaut)
  param.ajouter("fichier_solution",&fichier_solution);  //!< nom du fichier contenant la solution (Solution.sa par defaut)
  param.ajouter("nb_test",&nb_test);  //!< nb de resolution pour mesurer le temps (un seul preconditionnemt)
  param.ajouter_flag("impr",&limpr_); //!< impr des solveurs
  param.ajouter("solveur",&solveur); //!< pour specifier un solveur
  param.ajouter("fichier_solveur",&fichier_solveur); //!< pour specifier un fichier contenant des solveurs
  param.ajouter("genere_fichier_solveur",&seuil_list); //!< genere le fichier de solveur avec un seuil donne
  param.ajouter("seuil_verification",&seuil_verification); //!< verifie si la soulution trouvee par la resolution est telle que Ax -b < seuil_verification
  param.ajouter_flag("pas_de_solution_initiale",&pas_de_solution_init); //!< pas_de_solution_initiale : on n'initialise pas la resolution avec la solution
  param.ajouter_flag("ascii",&ascii); //!< dans le cas ou les fichiers sont ascii
  param.lire_avec_accolades_depuis(is);
  int binaire=1;
  if (ascii)
    binaire=0;
// On relit la matrice et le secmem
  {
    LecFicDistribue entree;
    entree.set_bin(binaire);
    entree.ouvrir(fichier_matrice);
    entree>>matrice;
    Cout<<" size of system "<<matrice.valeur( ).nb_colonnes()<<finl;
// matrice.valeur().imprimer_formatte(Cout);
  }
  {
    LecFicDistribue entree;
    entree.set_bin(binaire);
    entree.ouvrir(fichier_secmem);
    MD_Vector_tools::restore_vector_with_md(secmem,entree);
    Cout<<" size of system "<<secmem.size_totale()<<finl;
  }
  if (pas_de_solution_init)
    {
      solution=secmem;
      solution=0.;
    }
  else
    {
      LecFicDistribue entree;
      entree.set_bin(binaire);
      entree.ouvrir(fichier_solution);
      MD_Vector_tools::restore_vector_with_md(solution,entree);
      Cout<<" size of system "<<solution.size_totale()<<finl;
      solution.set_md_vector(secmem.get_md_vector());
    }
  if (seuil_list!=0)
    {
      if (fichier_solveur==Nom())
        fichier_solveur="list_solveur";
      if (je_suis_maitre())
        {
          SFichier list_solveur(fichier_solveur);
          generate_defaut(matrice,seuil_list,list_solveur,limpr_);
        }
    }
  secmem.echange_espace_virtuel();
  solution.echange_espace_virtuel();
// Champ_Inc bidon;
// bidon.typer("Champ_P0_VDF");
  ArrOfDouble temps(nb_test);
  if (fichier_solveur==Nom())
    test_un_solveur(solveur,  matrice , secmem , solution , -10, temps,seuil_verification);
  else
    {
      LecFicDiffuse list_solveur(fichier_solveur);
      int numero_best=test_solveur(solveur,  matrice , secmem , solution  , -10, temps,list_solveur,seuil_verification);
      Cout <<"------------------------------------------------"<<finl;
      Cout <<"Best solver : number "<<numero_best<<" "<<solveur<<finl;
      Cout <<"Best CPU time = "<<temps[0]<<finl;
      Cout <<"------------------------------------------------"<<finl;
    }
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), Cout, DMAXFLOAT, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, generate_defaut(), TRUSTVect< _TYPE_ >::get_md_vector(), Process::je_suis_maitre(), Param::lire_avec_accolades_depuis(), LecFicDistribue::ouvrir(), MD_Vector_tools::restore_vector_with_md(), Entree::set_bin(), TRUSTVect< _TYPE_ >::set_md_vector(), TRUSTVect< _TYPE_ >::size_totale(), test_solveur(), and test_un_solveur().
printOn()
Sortie & Test_solveur::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Solv_Optimal.cpp.
{
  return s;
}
readOn()
Entree & Test_solveur::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Solv_Optimal.cpp.
{
  return is;
}
self_cast() [1/2]
const Test_solveur & Test_solveur::self_cast (const Objet_U & r) static
Definition at line 27 of file Solv_Optimal.cpp.
self_cast() [2/2]
Test_solveur & Test_solveur::self_cast (Objet_U & r) static
Definition at line 27 of file Solv_Optimal.cpp.
taille_memoire()
unsigned Test_solveur::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Solv_Optimal.cpp.
Member Data Documentation
info_obj
const Type_info Test_solveur::info_obj static
Definition at line 40 of file Solv_Optimal.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_Optimal.h
src/Kernel/Math/SolvSys/Solv_Optimal.cpp