TRUST: SolveurPP1B Class Reference
SolveurPP1B Class Reference
#include <SolveurPP1B.h>
Public Member Functions
SolveurPP1B ()
~SolveurPP1B ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &, int niter_max) override
void reinit () override
int associer (const Assembleur_P_VEFPreP1B &, const SolveurSys &)
int solveur_direct () const override
void fixer_schema_temps_limpr (int l) override
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static SolveurPP1B & self_cast (Objet_U &)
static const SolveurPP1B & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
SolveurSys solveur_pression_
Assembleur_P_VEFPreP1B assembleur_pression_
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 24 of file SolveurPP1B.h.
Constructor & Destructor Documentation
SolveurPP1B()
SolveurPP1B::SolveurPP1B ()
Definition at line 20 of file SolveurPP1B.cpp.
~SolveurPP1B()
SolveurPP1B::~SolveurPP1B ()
Definition at line 20 of file SolveurPP1B.cpp.
Member Function Documentation
associer()
int SolveurPP1B::associer (const Assembleur_P_VEFPreP1B & assembleur_pression, const SolveurSys & solveur_pression)
< Pas d'impression
Definition at line 63 of file SolveurPP1B.cpp.
{
  assembleur_pression_=assembleur_pression;
  solveur_pression_=solveur_pression;
  fixer_limpr(-1); //!< Pas d'impression
  return 0;
}
References assembleur_pression_, SolveurSys_base::fixer_limpr(), and solveur_pression_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat().
cree_instance()
Objet_U * SolveurPP1B::cree_instance () static
Definition at line 20 of file SolveurPP1B.cpp.
duplique()
int SolveurPP1B::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file SolveurPP1B.cpp.
fixer_schema_temps_limpr()
void SolveurPP1B::fixer_schema_temps_limpr (int l) inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 39 of file SolveurPP1B.h.
{ solveur_pression_.valeur().fixer_schema_temps_limpr(l); }
References SolveurSys_base::fixer_schema_temps_limpr(), solveur_pression_, and Deriv_SolveurSys_base::valeur().
get_info()
const Type_info * SolveurPP1B::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from SolveurSys_base.
Definition at line 20 of file SolveurPP1B.cpp.
info()
const Type_info * SolveurPP1B::info () static
Definition at line 20 of file SolveurPP1B.cpp.
printOn()
Sortie & SolveurPP1B::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from SolveurSys_base.
Definition at line 23 of file SolveurPP1B.cpp.
{
  return s  << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & SolveurPP1B::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from SolveurSys_base.
Definition at line 30 of file SolveurPP1B.cpp.
{
  return is;
}
reinit()
void SolveurPP1B::reinit () inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 31 of file SolveurPP1B.h.
  {
    SolveurSys_base::reinit();
    solveur_pression_.valeur().reinit();
  }
References SolveurSys_base::reinit(), solveur_pression_, and Deriv_SolveurSys_base::valeur().
resoudre_systeme() [1/2]
int SolveurPP1B::resoudre_systeme (const Matrice_Base & A, const DoubleVect & second_membre, DoubleVect & x) override virtual
Implements SolveurSys_base.
Definition at line 35 of file SolveurPP1B.cpp.
{
// Stop the solv_sys_counter_ counter to not count the changing base
  statistiques().end_count(solv_sys_counter_,0,-1);
  DoubleVect b(second_membre);
  assembleur_pression_.changer_base_second_membre(b);
  assembleur_pression_.changer_base_pression(x);
  int nb_iter=solveur_pression_.resoudre_systeme(A,b,x);
  assembleur_pression_.changer_base_pression_inverse(x);
  statistiques().begin_count(solv_sys_counter_);
  return nb_iter;
}
References assembleur_pression_, Statistiques::begin_count(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), Statistiques::end_count(), SolveurSys::resoudre_systeme(), second_membre(), solv_sys_counter_, solveur_pression_, and statistiques().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int SolveurPP1B::resoudre_systeme (const Matrice_Base & A, const DoubleVect & b, DoubleVect & x, int niter_max) override virtual
Reimplemented from SolveurSys_base.
Definition at line 52 of file SolveurPP1B.cpp.
{
  return SolveurPP1B::resoudre_systeme(A,b,x);
}
References resoudre_systeme().
self_cast() [1/2]
const SolveurPP1B & SolveurPP1B::self_cast (const Objet_U & r) static
Definition at line 20 of file SolveurPP1B.cpp.
self_cast() [2/2]
SolveurPP1B & SolveurPP1B::self_cast (Objet_U & r) static
Definition at line 20 of file SolveurPP1B.cpp.
solveur_direct()
int SolveurPP1B::solveur_direct () const inline override virtual
Implements SolveurSys_base.
Definition at line 38 of file SolveurPP1B.h.
{ return solveur_pression_.valeur().solveur_direct(); }
References SolveurSys_base::solveur_direct(), solveur_pression_, and Deriv_SolveurSys_base::valeur().
taille_memoire()
unsigned SolveurPP1B::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file SolveurPP1B.cpp.
Member Data Documentation
assembleur_pression_
Assembleur_P_VEFPreP1B SolveurPP1B::assembleur_pression_ protected
Definition at line 43 of file SolveurPP1B.h.
Referenced by associer(), and resoudre_systeme().
info_obj
const Type_info SolveurPP1B::info_obj static
Definition at line 26 of file SolveurPP1B.h.
solveur_pression_
SolveurSys SolveurPP1B::solveur_pression_ protected
Definition at line 42 of file SolveurPP1B.h.
Referenced by associer(), fixer_schema_temps_limpr(), reinit(), resoudre_systeme(), and solveur_direct().
The documentation for this class was generated from the following files:
src/P1NCP1B/Solveurs/SolveurPP1B.h
src/P1NCP1B/Solveurs/SolveurPP1B.cpp