TRUST: PrecondA Class Reference
PrecondA Class Reference
#include <PrecondA.h>
Public Member Functions
~PrecondA ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
PrecondA ()
int supporte_matrice_morse_sym () override
Matrice_Morse_Sym non supporte.
Public Member Functions inherited from Precond_base
~Precond_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Precond_base ()
void reinit (Init_Status x=REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
void set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
void prepare (const Matrice_Base &, const DoubleVect &src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
virtual int supporte_matrice_morse_sym ()
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Init_Status get_status ()
virtual int get_flag_updated_input () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static PrecondA & self_cast (Objet_U &)
static const PrecondA & self_cast (const Objet_U &)
Static Public Member Functions inherited from Precond_base
static const Type_info * info ()
static Precond_base & self_cast (Objet_U &)
static const Precond_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Precond_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution) override
Calcule la solution du systeme lineaire: A * solution = b
avec la methode de relaxation PrecondA.
void prepare_ (const Matrice_Base &, const DoubleVect &src) override
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)=0
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Precond le_precond_0
Precond le_precond_1
Precond le_precond_a
double alpha_0
double alpha_1
double alpha_a
Protected Attributes inherited from Precond_base
int echange_ev_solution_
Additional Inherited Members
Public Types inherited from Precond_base
enum Init_Status { READY = 0 , REINIT_COEFF = 1 , REINIT_ALL = 2 }
Detailed Description
Definition at line 25 of file PrecondA.h.
Constructor & Destructor Documentation
~PrecondA()
PrecondA::~PrecondA ()
Definition at line 22 of file PrecondA.cpp.
PrecondA()
PrecondA::PrecondA ()
Definition at line 22 of file PrecondA.cpp.
Member Function Documentation
cree_instance()
Objet_U * PrecondA::cree_instance () static
Definition at line 22 of file PrecondA.cpp.
duplique()
int PrecondA::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file PrecondA.cpp.
get_info()
const Type_info * PrecondA::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Precond_base.
Definition at line 22 of file PrecondA.cpp.
info()
const Type_info * PrecondA::info () static
Definition at line 22 of file PrecondA.cpp.
preconditionner_()
int PrecondA::preconditionner_ (const Matrice_Base & matrice, const DoubleVect & src, DoubleVect & solution) override protected virtual
Calcule la solution du systeme lineaire: A * solution = b
avec la methode de relaxation PrecondA.
Implements Precond_base.
Definition at line 128 of file PrecondA.cpp.
{
  double pscb = mp_prodscal(b, b);
  if(pscb<1.e-24)
    {
      solution=b;
      return 1;
    }
// On calcule solution = inverse(C)*b avec:
// inverse(C) = inverse((1/w D - E)) *(2-w/w D) * inverse((1/wD -E)t)
// D :partie diagonale des blocs de la matrice
// E :partie triangulaire inferieure des blocs de la matrice
  const Matrice_Bloc_Sym& matbloc=ref_cast(Matrice_Bloc_Sym, matrice);
  if (matbloc.nb_bloc_lignes()<2
      || matbloc.nb_bloc_colonnes()<2
      || matbloc.nb_bloc_lignes()!=matbloc.nb_bloc_colonnes())
    {
      Cerr << "The preconditioning SSOR_BLOC can be used only for symetric block matrixes" << finl;
      Cerr << "containing at least 2*2 blocs. For example, when considering the following VEF discretizations :"<< finl;
      Cerr << "P0+P1 or P0+Pa or P0+P1+Pa." << finl;
      exit();
    }
  int nblocs=matbloc.nb_bloc_lignes();
  const Matrice_Base& A00=matbloc.get_bloc(0,0);
  const Matrice_Base& A01=matbloc.get_bloc(0,1);
  const Matrice_Base& A11=matbloc.get_bloc(1,1);
  const Matrice_Base& A0a=matbloc.get_bloc(0,nblocs-1);
  const Matrice_Base& A1a=matbloc.get_bloc(1,nblocs-1);
  const Matrice_Base& Aaa=matbloc.get_bloc(nblocs-1,nblocs-1);
  DoubleTab_parts parties(solution);
  DoubleVect& X0 = parties[0];
  DoubleVect& X1 = parties[1];
  DoubleVect& Xa = parties[parties.size() - 1];
  DoubleVect F(b);
  DoubleTab_parts parties_f(F);
  DoubleVect& Y0 = parties_f[0];
  DoubleVect& Y1 = parties_f[1];
  DoubleVect& Ya = parties_f[parties_f.size() - 1];
#ifdef TRACE
  Cerr << finl << "Y0 " << mp_norme_vect(Y0) << finl;
  Cerr << finl << "Y1 " << mp_norme_vect(Y1) << finl;
  if(nblocs == 3)
    Cerr << finl << "Ya " << mp_norme_vect(Ya) << finl;
  matrice.multvect(b, F);
  double psc=mp_prodscal(F,b);
  assert(psc>0);
  double pscF=mp_prodscal(F,F);
  Cout << finl <<"cos(angle) no prec " << psc*psc/(pscF*pscb) << finl;
  Cout << finl <<"(F,b) " << psc << finl;
  Cout << finl <<"(b,b) " << pscb << finl;
  Cout << finl <<"(F,F) " << pscF << finl;
  F.ajoute(-psc/pscb,b,VECT_ALL_ITEMS);
  Cout << finl <<"(F0,F0) " << mp_prodscal(Y0,Y0) << finl;
  Cout << finl <<"(F1,F1) " << mp_prodscal(Y1,Y1) << finl;
  if(nblocs == 3)
    Cout << finl <<"(Fa,Fa) " << mp_prodscal(Ya,Ya) << finl;
  F=b;
#endif
// Descente :
  le_precond_1.preconditionner(A11,Y1,X1);
  operator_multiply(X1, -alpha_1, VECT_ALL_ITEMS);
  A11.ajouter_multvect(X1, Y1);
  A01.ajouter_multvect(X1, Y0);
  if(nblocs == 3)
    A1a.ajouter_multvectT(X1, Ya);
  operator_multiply(X1, -1, VECT_ALL_ITEMS);
  le_precond_0.preconditionner(A00,Y0,X0);
  operator_multiply(X0, -alpha_0, VECT_ALL_ITEMS);
  A00.ajouter_multvect(X0, Y0);
  A01.ajouter_multvectT(X0, Y1);
  if(nblocs == 3)
    A0a.ajouter_multvectT(X0, Ya);
  operator_multiply(X0, -1, VECT_ALL_ITEMS);
  if(nblocs == 3)
    {
      le_precond_a.preconditionner(Aaa,Ya,Xa);
      operator_multiply(Xa, -alpha_a, VECT_ALL_ITEMS);
      Aaa.ajouter_multvect(Xa, Ya);
      A1a.ajouter_multvect(Xa, Y1);
      A0a.ajouter_multvect(Xa, Y0);
      operator_multiply(Xa, -1, VECT_ALL_ITEMS);
    }
// X contient S,
  F=solution;
// Diagonale :
  A11.multvect(Y1,X1);
  operator_multiply(X1, 1./alpha_1, VECT_ALL_ITEMS);
  A00.multvect(Y0,X0);
  operator_multiply(X0, 1./alpha_0, VECT_ALL_ITEMS);
  if(nblocs == 3)
    {
      Aaa.multvect(Ya,Xa);
      operator_multiply(Xa, 1./alpha_a, VECT_ALL_ITEMS);
    }
// X contient T,
  F=solution;
// Remontee :
  if(nblocs == 3)
    {
      le_precond_a.preconditionner(Aaa,Ya,Xa);
      operator_multiply(Xa, -alpha_a, VECT_ALL_ITEMS);
      Aaa.ajouter_multvect(Xa, Ya);
      A1a.ajouter_multvect(Xa, Y1);
      A0a.ajouter_multvect(Xa, Y0);
      operator_multiply(Xa, -1., VECT_ALL_ITEMS);
    }
  le_precond_0.preconditionner(A00,Y0,X0);
  operator_multiply(X0, -alpha_0, VECT_ALL_ITEMS);
  A00.ajouter_multvect(X0, Y0);
  A01.ajouter_multvectT(X0, Y1);
  if(nblocs == 3)
    A0a.ajouter_multvectT(X0, Ya);
  operator_multiply(X0, -1., VECT_ALL_ITEMS);
  le_precond_1.preconditionner(A11,Y1,X1);
  operator_multiply(X1, -alpha_1, VECT_ALL_ITEMS);
  A11.ajouter_multvect(X1, Y1);
  A01.ajouter_multvect(X1, Y0);
  if(nblocs == 3)
    A1a.ajouter_multvectT(X1, Ya);
  operator_multiply(X1, -1., VECT_ALL_ITEMS);
#ifdef TRACE
  matrice.multvect(solution, F);
  psc=mp_prodscal(F,b);
  assert(psc>0);
  pscF=mp_prodscal(F,F);
  Cout << finl <<"cos(angle) " << psc*psc/(pscF*pscb) << finl;
  Cout << finl <<"(F,b) " << psc << finl;
  Cout << finl <<"(b,b) " << pscb << finl;
  Cout << finl <<"(F,F) " << pscF << finl;
  F.ajoute(-psc/pscb,b);
  Cout << finl <<"(F0,F0) " << mp_prodscal(Y0,Y0) << finl;
  Cout << finl <<"(F1,F1) " << mp_prodscal(Y1,Y1) << finl;
  if(nblocs == 3)
    Cout << finl <<"(Fa,Fa) " << mp_prodscal(Ya,Ya) << finl;
#endif
  return 1;
}
References TRUSTVect< _TYPE_ >::ajoute(), Matrice_Base::ajouter_multvect(), Matrice_Base::ajouter_multvectT(), alpha_0, alpha_1, alpha_a, Cerr, Cout, Process::exit(), finl, Matrice_Bloc_Sym::get_bloc(), le_precond_0, le_precond_1, le_precond_a, mp_norme_vect(), mp_prodscal(), Matrice_Base::multvect(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), operator_multiply(), Precond::preconditionner(), ref_cast, TRUSTTab_parts< _TYPE_ >::size(), and VECT_ALL_ITEMS.
prepare_()
void PrecondA::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
Definition at line 113 of file PrecondA.cpp.
{
  Init_Status status = get_status();
  const Matrice_Bloc_Sym& matbloc = ref_cast(Matrice_Bloc_Sym, m);
  ConstDoubleTab_parts parts(v);
  prepare_precond(le_precond_0, matbloc.get_bloc(0,0), parts[0], status);
  prepare_precond(le_precond_1, matbloc.get_bloc(1,1), parts[1], status);
  if (parts.size() > 2)
    prepare_precond(le_precond_a, matbloc.get_bloc(2,2), parts[2], status);
  Precond_base::prepare_(m, v);
}
References Matrice_Bloc_Sym::get_bloc(), Precond_base::get_status(), le_precond_0, le_precond_1, le_precond_a, Precond_base::prepare_(), prepare_precond(), ref_cast, and ConstTRUSTTab_parts< _TYPE_ >::size().
printOn()
Sortie & PrecondA::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 26 of file PrecondA.cpp.
{
  return s;
}
readOn()
Entree & PrecondA::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 31 of file PrecondA.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcles les_parametres(6);
  {
    les_parametres[0] = "precond0";
    les_parametres[1] = "precond1";
    les_parametres[2] = "preconda";
    les_parametres[3] = "alpha_0";
    les_parametres[4] = "alpha_1";
    les_parametres[5] = "alpha_a";
    int rang;
    Motcle motlu;
    is >> motlu;
    if (motlu != accolade_ouverte)
      {
        Cerr << "Error when reading the parameters of the conjugate gradient PrecondA " << finl;
        Cerr << "One expected : " << accolade_ouverte << finl;
        exit();
      }
    is >> motlu;
    while (motlu != accolade_fermee)
      {
        rang = les_parametres.search(motlu);
        switch(rang)
          {
          case 0:
            {
              is >> le_precond_0;
              break;
            }
          case 1:
            {
              is >> le_precond_1;
              break;
            }
          case 2:
            {
              is >> le_precond_a;
              break;
            }
          case 3:
            {
              is >> alpha_0;
              break;
            }
          case 4:
            {
              is >> alpha_1;
              break;
            }
          case 5:
            {
              is >> alpha_a;
              break;
            }
          default :
            {
              Cerr << "Error when reading the parameters of the preconditioning PrecondA " << finl;
              Cerr << "On expected " << les_parametres << " instead of " << motlu << finl;
              exit();
            }
          }
        is >> motlu;
      }
  }
  return is;
}
References alpha_0, alpha_1, alpha_a, Cerr, Process::exit(), finl, le_precond_0, le_precond_1, le_precond_a, and Motcles::search().
self_cast() [1/2]
const PrecondA & PrecondA::self_cast (const Objet_U & r) static
Definition at line 22 of file PrecondA.cpp.
self_cast() [2/2]
PrecondA & PrecondA::self_cast (Objet_U & r) static
Definition at line 22 of file PrecondA.cpp.
supporte_matrice_morse_sym()
int PrecondA::supporte_matrice_morse_sym () inline override virtual
Matrice_Morse_Sym non supporte.
Reimplemented from Precond_base.
Definition at line 30 of file PrecondA.h.
taille_memoire()
unsigned PrecondA::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file PrecondA.cpp.
Member Data Documentation
alpha_0
double PrecondA::alpha_0 protected
Definition at line 37 of file PrecondA.h.
Referenced by preconditionner_(), and readOn().
alpha_1
double PrecondA::alpha_1 protected
Definition at line 37 of file PrecondA.h.
Referenced by preconditionner_(), and readOn().
alpha_a
double PrecondA::alpha_a protected
Definition at line 37 of file PrecondA.h.
Referenced by preconditionner_(), and readOn().
info_obj
const Type_info PrecondA::info_obj static
Definition at line 27 of file PrecondA.h.
le_precond_0
Precond PrecondA::le_precond_0 protected
Definition at line 36 of file PrecondA.h.
Referenced by preconditionner_(), prepare_(), and readOn().
le_precond_1
Precond PrecondA::le_precond_1 protected
Definition at line 36 of file PrecondA.h.
Referenced by preconditionner_(), prepare_(), and readOn().
le_precond_a
Precond PrecondA::le_precond_a protected
Definition at line 36 of file PrecondA.h.
Referenced by preconditionner_(), prepare_(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/PrecondA.h
src/Kernel/Math/SolvSys/PrecondA.cpp