TRUST: Terme_Source_Decroissance_Radioactive_P0_CoviMAC Class Reference
Terme_Source_Decroissance_Radioactive_P0_CoviMAC Class Reference
class Terme_Source_Decroissance_Radioactive_P0_CoviMAC
#include <Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h>
Public Member Functions
~Terme_Source_Decroissance_Radioactive_P0_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void associer_pb (const Probleme_base &)
void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Decroissance_Radioactive_P0_CoviMAC & self_cast (Objet_U &)
static const
Terme_Source_Decroissance_Radioactive_P0_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
std::vector< double > lambda
int nb_groupes = 0
Ref_Zone_CoviMAC la_zone_CoviMAC
Detailed Description
class Terme_Source_Decroissance_Radioactive_P0_CoviMAC
See also:
Source_base
Definition at line 42 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
Constructor & Destructor Documentation
Terme_Source_Decroissance_Radioactive_P0_CoviMAC::~Terme_Source_Decroissance_Radioactive_P0_CoviMAC ()
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
Member Function Documentation
void Terme_Source_Decroissance_Radioactive_P0_CoviMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Source_base.
void Terme_Source_Decroissance_Radioactive_P0_CoviMAC::associer_pb (const Probleme_base &) [inline, virtual]
Implements Source_base.
Definition at line 58 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
{ };
void Terme_Source_Decroissance_Radioactive_P0_CoviMAC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 72 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
References Cerr, finl, la_zone_CoviMAC, ref_cast, and Deriv_Zone_dis_base::valeur().
{
  Cerr << " Terme_Source_Decroissance_Radioactive_P0_CoviMAC::associer_zones " << finl ;
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC, zone_dis.valeur());
}
void Terme_Source_Decroissance_Radioactive_P0_CoviMAC::completer () [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 61 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
References Cerr, MorEqn::equation(), Process::exit(), finl, Equation_base::inconnue(), DoubleVect::line_size(), nb_groupes, and Champ_Inc::valeurs().
{
  Source_base::completer();
  const int N = equation().inconnue().valeurs().line_size();
  if (N != nb_groupes)
    {
      Cerr << "Terme_Source_Decroissance_Radioactive_P0_CoviMAC : inconsistency between the number of radioactive decay constants ( " << nb_groupes << " ) and the number of components of the unknown of the equation ( " << N << " )" << finl;
      Process::exit();
    }
}
Objet_U * Terme_Source_Decroissance_Radioactive_P0_CoviMAC::cree_instance () [static]
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
void Terme_Source_Decroissance_Radioactive_P0_CoviMAC::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Source_base.
int Terme_Source_Decroissance_Radioactive_P0_CoviMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
const Type_info * Terme_Source_Decroissance_Radioactive_P0_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
int Terme_Source_Decroissance_Radioactive_P0_CoviMAC::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 51 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
  {
    return 1;
  }
const Type_info * Terme_Source_Decroissance_Radioactive_P0_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
void Terme_Source_Decroissance_Radioactive_P0_CoviMAC::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 57 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
{ };
Sortie & Terme_Source_Decroissance_Radioactive_P0_CoviMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 38 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je();
}
Entree & Terme_Source_Decroissance_Radioactive_P0_CoviMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
References Cerr, finl, lambda, and nb_groupes.
{
  double lambda_tmp;
  s >> nb_groupes;
  Cerr << "Nombre de groupes a lire : " << nb_groupes << finl;
  for (int i = 0; i < nb_groupes; i++)
    {
      s >> lambda_tmp;
      Cerr << "lambda lu : " << lambda_tmp << finl;
      lambda.push_back(lambda_tmp);
    }
  return s ;
}
Terme_Source_Decroissance_Radioactive_P0_CoviMAC & Terme_Source_Decroissance_Radioactive_P0_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
const Terme_Source_Decroissance_Radioactive_P0_CoviMAC & Terme_Source_Decroissance_Radioactive_P0_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
unsigned Terme_Source_Decroissance_Radioactive_P0_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 32 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp.
Member Data Documentation
const Type_info Terme_Source_Decroissance_Radioactive_P0_CoviMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 47 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
Ref_Zone_CoviMAC Terme_Source_Decroissance_Radioactive_P0_CoviMAC::la_zone_CoviMAC [protected]
Definition at line 65 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
Referenced by associer_zones().
std::vector<double> Terme_Source_Decroissance_Radioactive_P0_CoviMAC::lambda [protected]
Definition at line 63 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
Referenced by readOn().
int Terme_Source_Decroissance_Radioactive_P0_CoviMAC::nb_groupes = 0 [protected]
Definition at line 64 of file Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h.
Referenced by completer(), and readOn().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Terme_Source_Decroissance_Radioactive_P0_CoviMAC.h
src/CoviMAC/Sources/Terme_Source_Decroissance_Radioactive_P0_CoviMAC.cpp