TRUST: Viscosite_turbulente_multiple Class Reference
Viscosite_turbulente_multiple Class Reference
classe Viscosite_turbulente_multiple
Classe qui peut contenir plusieurs viscosites turbulentes pour faire de la turbulence monophasique + diphasique
En pratique, la viscosite turbulente n'est que monophasique et l'operateur de diffusion reste identique
La classe Source_BIF_PolyMAC_P0 appelle reynolds_stress_BIF et entre les termes de divergence du tenseur de Reynolds
en explicite dans la QDM
#include <Viscosite_turbulente_multiple.h>
Public Member Functions
Viscosite_turbulente_multiple ()
~Viscosite_turbulente_multiple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void eddy_viscosity (DoubleTab &nu_t) const override
void reynolds_stress (DoubleTab &R_ij) const override
< Renvoie <u_i'u_j'>
void k_over_eps (DoubleTab &k_sur_eps) const override
int gradu_required () const override
void eps (DoubleTab &eps) const override
void reynolds_stress_BIF (DoubleTab &R_ij) const
< Renvoie <u_i'u_j'>
Public Member Functions inherited from Viscosite_turbulente_base
Viscosite_turbulente_base ()
~Viscosite_turbulente_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void eddy_viscosity (DoubleTab &nu_t) const =0
virtual void reynolds_stress (DoubleTab &R_ij) const =0
virtual void k_over_eps (DoubleTab &k_sur_eps) const =0
virtual void eps (DoubleTab &eps) const =0
double limiteur () const
virtual int gradu_required () const
Public Member Functions inherited from Correlation_base
Correlation_base ()
~Correlation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & lire (Entree &is)
void associer_pb (const Probleme_base &pb)
virtual void mettre_a_jour (double temps)
virtual void completer ()
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Viscosite_turbulente_multiple & self_cast (Objet_U &)
static const Viscosite_turbulente_multiple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Viscosite_turbulente_base
static const Type_info * info ()
static Viscosite_turbulente_base & self_cast (Objet_U &)
static const Viscosite_turbulente_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Correlation_base
static const Type_info * info ()
static Correlation_base & self_cast (Objet_U &)
static const Correlation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Viscosite_turbulente_base
static const Type_info info_obj
Static Public Attributes inherited from Correlation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
std::map< std::string, Correlation > viscs_turbs
Additional Inherited Members
Protected Attributes inherited from Correlation_base
Ref_Probleme_base pb_
Champs_compris champs_compris_
Detailed Description
classe Viscosite_turbulente_multiple
Classe qui peut contenir plusieurs viscosites turbulentes pour faire de la turbulence monophasique + diphasique
En pratique, la viscosite turbulente n'est que monophasique et l'operateur de diffusion reste identique
La classe Source_BIF_PolyMAC_P0 appelle reynolds_stress_BIF et entre les termes de divergence du tenseur de Reynolds
en explicite dans la QDM
Definition at line 33 of file Viscosite_turbulente_multiple.h.
Constructor & Destructor Documentation
Viscosite_turbulente_multiple()
Viscosite_turbulente_multiple::Viscosite_turbulente_multiple ()
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
~Viscosite_turbulente_multiple()
Viscosite_turbulente_multiple::~Viscosite_turbulente_multiple ()
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
Member Function Documentation
cree_instance()
Objet_U * Viscosite_turbulente_multiple::cree_instance () static
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
duplique()
int Viscosite_turbulente_multiple::duplique () const override virtual
Implements Objet_U.
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
eddy_viscosity()
void Viscosite_turbulente_multiple::eddy_viscosity (DoubleTab & nu_t) const override virtual
Implements Viscosite_turbulente_base.
Definition at line 45 of file Viscosite_turbulente_multiple.cpp.
{
// On fait appel aux correlations d'en_dessous
  nu_t = 0;
  DoubleTrav nu_loc = DoubleTrav(nu_t);
  for (auto &&corr : viscs_turbs)
    {
      nu_loc = 0;
      ref_cast(Viscosite_turbulente_base, corr.second.valeur()).eddy_viscosity(nu_loc);
      for (int i = 0; i < nu_t.dimension_tot(0); i++)
        for (int n = 0; n < nu_t.dimension(1); n++)
          nu_t(i, n) += nu_loc(i,n);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), ref_cast, and viscs_turbs.
eps()
void Viscosite_turbulente_multiple::eps (DoubleTab & eps) const override virtual
Implements Viscosite_turbulente_base.
Definition at line 111 of file Viscosite_turbulente_multiple.cpp.
{
  eps_ = 0;
  DoubleTrav eps_loc = DoubleTrav(eps_);
  for (auto &&corr : viscs_turbs)
    {
      eps_loc = 0;
      ref_cast(Viscosite_turbulente_base, corr.second.valeur()).eps(eps_loc);
      for (int i = 0; i < eps_.dimension_tot(0); i++)
        for (int n = 0; n < eps_.dimension(1); n++)
          eps_(i, n) += eps_loc(i,n);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), ref_cast, and viscs_turbs.
get_info()
const Type_info * Viscosite_turbulente_multiple::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Viscosite_turbulente_base.
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
gradu_required()
int Viscosite_turbulente_multiple::gradu_required () const inline override virtual
Reimplemented from Viscosite_turbulente_base.
Definition at line 40 of file Viscosite_turbulente_multiple.h.
{  return 1; };
info()
const Type_info * Viscosite_turbulente_multiple::info () static
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
k_over_eps()
void Viscosite_turbulente_multiple::k_over_eps (DoubleTab & k_sur_eps) const override virtual
Implements Viscosite_turbulente_base.
Definition at line 96 of file Viscosite_turbulente_multiple.cpp.
{
  k_sur_eps = 0;
  DoubleTrav k_sur_eps_loc = DoubleTrav(k_sur_eps);
  for (auto &&corr : viscs_turbs)
    {
      k_sur_eps_loc = 0;
      ref_cast(Viscosite_turbulente_base, corr.second.valeur()).k_over_eps(k_sur_eps_loc);
      for (int i = 0; i < k_sur_eps.dimension_tot(0); i++)
        for (int n = 0; n < k_sur_eps.dimension(1); n++)
          k_sur_eps(i, n) += k_sur_eps_loc(i,n);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), ref_cast, and viscs_turbs.
printOn()
Sortie & Viscosite_turbulente_multiple::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Viscosite_turbulente_base.
Definition at line 28 of file Viscosite_turbulente_multiple.cpp.
{
  return os;
}
readOn()
Entree & Viscosite_turbulente_multiple::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Viscosite_turbulente_base.
Definition at line 33 of file Viscosite_turbulente_multiple.cpp.
{
  Motcle mot;
  is >> mot;
  if (mot != "{") Cerr << "Multiple turbulent viscosities : { expected instead of " << mot << finl, Process::exit();
  for (is >> mot; mot != "}"; is >> mot)
    if (viscs_turbs.count(mot.getString())) Process::exit(que_suis_je() + " : a correlation already exists for " + mot + " !");
    else viscs_turbs[mot.getString()].typer_lire(pb_.valeur(), "viscosite_turbulente", is);
  return is;
}
References Cerr, Process::exit(), finl, Nom::getString(), Correlation_base::pb_, Objet_U::que_suis_je(), Ref_Probleme_base::valeur(), and viscs_turbs.
reynolds_stress()
void Viscosite_turbulente_multiple::reynolds_stress (DoubleTab & R_ij) const override virtual
< Renvoie <u_i'u_j'>
Implements Viscosite_turbulente_base.
Definition at line 60 of file Viscosite_turbulente_multiple.cpp.
{
  int D = dimension;
  R_ij = 0;
  DoubleTrav R_ij_loc = DoubleTrav(R_ij);
  for (auto &&corr : viscs_turbs)
    {
      R_ij_loc = 0;
      ref_cast(Viscosite_turbulente_base, corr.second.valeur()).reynolds_stress(R_ij_loc);
      for (int i = 0; i < R_ij.dimension(0); i++)
        for (int n = 0; n < R_ij.dimension(1); n++)
          for (int d = 0; d < D; d++)
            for (int db = 0; db < D; db++)
              R_ij(i, n, d, db) += R_ij_loc(i, n, d, db);
    }
}
References ref_cast.
reynolds_stress_BIF()
void Viscosite_turbulente_multiple::reynolds_stress_BIF (DoubleTab & R_ij) const
< Renvoie <u_i'u_j'>
Definition at line 77 of file Viscosite_turbulente_multiple.cpp.
{
  int D = dimension;
  R_ij = 0;
  DoubleTrav R_ij_loc = DoubleTrav(R_ij);
  for (auto &&corr : viscs_turbs)
    if ((corr.first == "BIF") | (corr.first == "WIF") | (corr.first == "WIT"))
      {
        R_ij_loc = 0;
        ref_cast(Viscosite_turbulente_base, corr.second.valeur()).reynolds_stress(R_ij_loc);
        for (int i = 0; i < R_ij.dimension(0); i++)
          for (int n = 0; n < R_ij.dimension(1); n++)
            for (int d = 0; d < D; d++)
              for (int db = 0; db < D; db++)
                R_ij(i, n, d, db) += R_ij_loc(i, n, d, db);
      }
}
References ref_cast.
self_cast() [1/2]
const Viscosite_turbulente_multiple & Viscosite_turbulente_multiple::self_cast (const Objet_U & r) static
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
self_cast() [2/2]
Viscosite_turbulente_multiple & Viscosite_turbulente_multiple::self_cast (Objet_U & r) static
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
taille_memoire()
unsigned Viscosite_turbulente_multiple::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 26 of file Viscosite_turbulente_multiple.cpp.
Member Data Documentation
info_obj
const Type_info Viscosite_turbulente_multiple::info_obj static
Definition at line 35 of file Viscosite_turbulente_multiple.h.
viscs_turbs
std::map<std::string, Correlation> Viscosite_turbulente_multiple::viscs_turbs private
Definition at line 46 of file Viscosite_turbulente_multiple.h.
Referenced by eddy_viscosity(), eps(), k_over_eps(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Turbulence/Viscosite_turbulente_multiple.h
src/ThHyd/Multiphase/Turbulence/Viscosite_turbulente_multiple.cpp