TRUST: Loi_Etat_base Class Reference
Loi_Etat_base Class Reference abstract
classe Loi_Etat_base
Cette classe est la base de la hierarchie des lois d'etat.
Elle definit un fluide dilatable
#include <Loi_Etat_base.h>
Public Member Functions
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Private Attributes
Champs_compris champs_compris_
Detailed Description
classe Loi_Etat_base
Cette classe est la base de la hierarchie des lois d'etat.
Elle definit un fluide dilatable
Definition at line 42 of file Loi_Etat_base.h.
Constructor & Destructor Documentation
~Loi_Etat_base()
Loi_Etat_base::~Loi_Etat_base () override
Definition at line 25 of file Loi_Etat_base.cpp.
Loi_Etat_base()
Loi_Etat_base::Loi_Etat_base ()
Definition at line 28 of file Loi_Etat_base.cpp.
: Pr_(-1.), debug(0) { }
Member Function Documentation
abortTimeStep()
void Loi_Etat_base::abortTimeStep () virtual
Definition at line 485 of file Loi_Etat_base.cpp.
{
  int i, n=tab_rho_n.size_totale();
  for (i=0 ; i<n ; i++)
    tab_rho_np1(i) = tab_rho_n(i);
}
References TRUSTVect< _TYPE_ >::size_totale(), tab_rho_n, and tab_rho_np1.
associer_fluide()
void Loi_Etat_base::associer_fluide (const Fluide_Dilatable_base & fl) virtual
Associe le fluide a la loi d'etat.
Reimplemented in Loi_Etat_GP_base, and Loi_Etat_Melange_GP_base.
Definition at line 55 of file Loi_Etat_base.cpp.
{
  le_fluide = fl;
}
References le_fluide.
Referenced by Loi_Etat_GP_base::associer_fluide(), and Loi_Etat_Melange_GP_base::associer_fluide().
assoscier_probleme()
void Loi_Etat_base::assoscier_probleme (const Probleme_base & pb)
Associe le probleme a la loi d'etat.
Definition at line 74 of file Loi_Etat_base.cpp.
{
  le_prob_ = pb;
}
References le_prob_.
calculer_alpha()
void Loi_Etat_base::calculer_alpha () virtual
Calcule la diffusivite.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, and Loi_Etat_Multi_GP_base.
Definition at line 329 of file Loi_Etat_base.cpp.
{
  const Champ_Don& lambda = le_fluide->conductivite();
  const DoubleTab& tab_lambda = lambda.valeurs();
  const DoubleTab& tab_Cp = le_fluide->capacite_calorifique().valeurs();
  const DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  DoubleTab& tab_alpha = le_fluide->diffusivite().valeurs();
  int i, n = tab_alpha.size();
  if (sub_type(Champ_Uniforme,lambda.valeur()))
    {
      double lambda0 = tab_lambda(0,0);
      for (i=0 ; i<n ; i++) tab_alpha(i,0) = lambda0 / (tab_rho(i,0)*tab_Cp(i,0));
    }
  else
    {
      for (i=0 ; i<n ; i++) tab_alpha(i,0) = tab_lambda(i,0) / (tab_rho(i,0)*tab_Cp(i,0));
    }
  tab_alpha.echange_espace_virtuel();
  Debog::verifier("Loi_Etat_base::calculer_alpha alpha",tab_alpha);
}
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Milieu_base::diffusivite(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), le_fluide, Milieu_base::masse_volumique(), TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), and Debog::verifier().
calculer_Cp()
virtual void Loi_Etat_base::calculer_Cp () pure virtual
Implemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, Loi_Etat_GR_base, and Loi_Etat_Multi_GP_base.
calculer_H()
double Loi_Etat_base::calculer_H (double Pth_, double T_) const virtual
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
Reimplemented in Loi_Etat_rhoT_GR_QC, and Loi_Etat_GR_base.
Definition at line 437 of file Loi_Etat_base.cpp.
{
  return T_;
}
calculer_lambda()
void Loi_Etat_base::calculer_lambda () virtual
Calcule la conductivite.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, Loi_Etat_GR_base, and Loi_Etat_Multi_GP_base.
Definition at line 222 of file Loi_Etat_base.cpp.
{
  const Champ_Don& mu = le_fluide->viscosite_dynamique();
  const DoubleTab& tab_Cp = le_fluide->capacite_calorifique().valeurs();
  const DoubleTab& tab_mu = mu.valeurs();
  Champ_Don& lambda = le_fluide->conductivite();
  DoubleTab& tab_lambda = lambda.valeurs();
  int i, n = tab_lambda.size();
// La conductivite est soit un champ uniforme soit calculee a partir de la viscosite dynamique et du Pr
  if (!sub_type(Champ_Uniforme,lambda.valeur()))
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          double mu0 = tab_mu(0,0);
          for (i=0 ; i<n ; i++) tab_lambda(i,0) = mu0 * tab_Cp(i,0) / Pr_;
        }
      else
        {
          for (i=0 ; i<n ; i++) tab_lambda(i,0) = tab_mu(i,0) * tab_Cp(i,0) / Pr_;
        }
    }
  tab_lambda.echange_espace_virtuel();
}
References Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), le_fluide, Pr_, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Champ_Don::valeurs(), and Fluide_base::viscosite_dynamique().
calculer_masse_volumique() [1/2]
void Loi_Etat_base::calculer_masse_volumique () virtual
Recalcule la masse volumique.
Reimplemented in Loi_Etat_GP_base, Loi_Etat_GR_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_rhoT_GR_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, Loi_Etat_Multi_GP_WC, Loi_Etat_Binaire_GP_base, and Loi_Etat_Multi_GP_base.
Definition at line 406 of file Loi_Etat_base.cpp.
{
  const DoubleTab& tab_ICh = le_fluide->inco_chaleur().valeurs();
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  double Pth = le_fluide->pression_th();
  int n=tab_rho.size();
  for (int som=0 ; som<n ; som++)
    {
      tab_rho_np1(som) = calculer_masse_volumique(Pth,tab_ICh(som,0));
      tab_rho(som,0) = 0.5 * ( tab_rho_n(som) + tab_rho_np1(som) );
    }
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
  le_fluide->calculer_rho_face(tab_rho_np1);
}
References calculer_masse_volumique(), Fluide_Dilatable_base::calculer_rho_face(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Fluide_Dilatable_base::inco_chaleur(), le_fluide, Milieu_base::masse_volumique(), Fluide_Dilatable_base::pression_th(), TRUSTVect< _TYPE_ >::size(), tab_rho_n, tab_rho_np1, Champ::valeurs(), and Champ_Inc::valeurs().
Referenced by calculer_masse_volumique(), Loi_Etat_GP_base::calculer_masse_volumique(), Loi_Etat_GR_base::calculer_masse_volumique(), initialiser_inco_ch(), EDO_Pression_th_VDF::masse_totale(), EDO_Pression_th_VEF::masse_totale(), and preparer_calcul().
calculer_masse_volumique() [2/2]
virtual double Loi_Etat_base::calculer_masse_volumique (double , double) const pure virtual
Implemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_rhoT_GR_QC, Loi_Etat_GP_WC, Loi_Etat_Multi_GP_WC, and Loi_Etat_GR_base.
calculer_mu()
void Loi_Etat_base::calculer_mu () virtual
Calcule la viscosite.
Reimplemented in Loi_Etat_Binaire_GP_base, and Loi_Etat_Multi_GP_base.
Definition at line 192 of file Loi_Etat_base.cpp.
{
  Champ_Don& mu = le_fluide->viscosite_dynamique();
  if (!sub_type(Champ_Uniforme,mu.valeur()))
    {
// E. Saikali : Pourquoi pas Champ_fonc_xyz pour mu ???
      if (sub_type(Champ_Fonc_Tabule,mu.valeur()) || sub_type(Champ_Don_base,mu.valeur()))
        mu.mettre_a_jour(temperature_.valeur().temps());
      else
        {
          Cerr<<"The viscosity field mu of type "<<mu.valeur().que_suis_je()<<" is not recognized.";
          Process::exit();
        }
    }
}
References Cerr, Process::exit(), le_fluide, Champ_Don::mettre_a_jour(), Objet_U::que_suis_je(), sub_type, temperature_, Champ_base::temps(), Deriv_Champ_Don_base::valeur(), and Fluide_base::viscosite_dynamique().
calculer_mu_sur_Sc()
void Loi_Etat_base::calculer_mu_sur_Sc () virtual
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_Multi_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 367 of file Loi_Etat_base.cpp.
{
  /* Do nothing : overloaded later */
}
calculer_nu()
void Loi_Etat_base::calculer_nu ()
Calcule la viscosite cinematique.
< VEF
Definition at line 261 of file Loi_Etat_base.cpp.
{
  const Champ_Don& mu = le_fluide->viscosite_dynamique();
  const DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  const DoubleTab& tab_mu = mu.valeurs();
  Champ_Don& nu= le_fluide->viscosite_cinematique ();
  DoubleTab& tab_nu = nu.valeurs();
  int i, n = tab_nu.size(), isVDF=0;
  if (nu.valeur().que_suis_je()=="Champ_Fonc_P0_VDF") isVDF = 1;
  if (isVDF)
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          double mu0 = tab_mu(0,0);
          for (i=0 ; i<n ; i++) tab_nu(i,0) = mu0 / tab_rho(i,0);
        }
      else
        {
          for (i=0 ; i<n ; i++) tab_nu(i,0) = tab_mu(i,0) / tab_rho(i,0);
        }
    }
  else //!< VEF
    {
      const IntTab& elem_faces=ref_cast(Zone_VF,le_fluide->vitesse().zone_dis_base()).elem_faces();
      double rhoelem;
      int face, nfe = elem_faces.line_size();
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          double mu0 = tab_mu(0,0);
          for (i=0 ; i<n ; i++)
            {
              rhoelem=0;
              for (face=0; face<nfe; face++) rhoelem += tab_rho(elem_faces(i,face),0);
              rhoelem /= nfe;
              tab_nu(i,0) = mu0 / rhoelem;
            }
        }
      else
        {
          for (i=0 ; i<n ; i++)
            {
              rhoelem=0;
              for (face=0; face<nfe; face++) rhoelem += tab_rho(elem_faces(i,face),0);
              rhoelem /= nfe;
              tab_nu(i,0) = tab_mu(i,0) / rhoelem;
            }
        }
    }
  tab_nu.echange_espace_virtuel();
  Debog::verifier("Loi_Etat_base::calculer_nu tab_nu",tab_nu);
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), le_fluide, TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Objet_U::que_suis_je(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), Champ::valeurs(), Champ_Don::valeurs(), Debog::verifier(), Fluide_base::viscosite_cinematique(), Fluide_base::viscosite_dynamique(), Fluide_Dilatable_base::vitesse(), and Champ_Inc::zone_dis_base().
calculer_nu_sur_Sc()
void Loi_Etat_base::calculer_nu_sur_Sc () virtual
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
Reimplemented in Loi_Etat_Binaire_GP_base, and Loi_Etat_Multi_GP_WC.
Definition at line 387 of file Loi_Etat_base.cpp.
{
  /* Do nothing : overloaded later */
}
ch_temperature() [1/2]
Champ_Don & Loi_Etat_base::ch_temperature ()
Definition at line 98 of file Loi_Etat_base.cpp.
{
  return temperature_;
}
References temperature_.
Referenced by temperature().
ch_temperature() [2/2]
const Champ_Don & Loi_Etat_base::ch_temperature () const
Renvoie le champ de le temperature.
Definition at line 93 of file Loi_Etat_base.cpp.
{
  return temperature_;
}
References temperature_.
champs_compris()
Champs_compris & Loi_Etat_base::champs_compris () inline
Definition at line 84 of file Loi_Etat_base.h.
{ return champs_compris_; }
References champs_compris_.
Referenced by Fluide_Quasi_Compressible::discretiser().
creer_champ()
void Loi_Etat_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Definition at line 467 of file Loi_Etat_base.cpp.
{
  /* Do nothing */
}
De_DP()
double Loi_Etat_base::De_DP (double , double) const virtual
Reimplemented in Loi_Etat_GR_base.
Definition at line 454 of file Loi_Etat_base.cpp.
{
  Cerr<<"De_DP doit etre code dans la classe fille "<<que_suis_je()<<" pour etre utilisee"<<finl;
  abort();
  return 0;
}
References Process::abort(), Cerr, finl, and Objet_U::que_suis_je().
De_DT()
double Loi_Etat_base::De_DT (double , double) const virtual
Reimplemented in Loi_Etat_GR_base.
Definition at line 460 of file Loi_Etat_base.cpp.
{
  Cerr<<"De_DT doit etre code dans la classe fille "<<que_suis_je()<<" pour etre utilisee"<<finl;
  abort();
  return 0;
}
References Process::abort(), Cerr, finl, and Objet_U::que_suis_je().
Drho_DP()
double Loi_Etat_base::Drho_DP (double , double) const virtual
Reimplemented in Loi_Etat_rhoT_GR_QC, and Loi_Etat_GR_base.
Definition at line 442 of file Loi_Etat_base.cpp.
{
  Cerr<<"Drho_DP doit etre code dans la classe fille "<<que_suis_je()<<" pour etre utilisee"<<finl;
  abort();
  return 0;
}
References Process::abort(), Cerr, finl, and Objet_U::que_suis_je().
Drho_DT()
double Loi_Etat_base::Drho_DT (double , double) const virtual
Reimplemented in Loi_Etat_rhoT_GR_QC, and Loi_Etat_GR_base.
Definition at line 448 of file Loi_Etat_base.cpp.
{
  Cerr<<"Drho_DT doit etre code dans la classe fille "<<que_suis_je()<<" pour etre utilisee"<<finl;
  abort();
  return 0;
}
References Process::abort(), Cerr, finl, and Objet_U::que_suis_je().
get_champ()
const Champ_base & Loi_Etat_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Definition at line 472 of file Loi_Etat_base.cpp.
{
  return champs_compris_.get_champ(nom);
}
References champs_compris_, and Champs_compris::get_champ().
get_info()
const Type_info * Loi_Etat_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, Loi_Etat_GR_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_rhoT_GR_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 25 of file Loi_Etat_base.cpp.
get_noms_champs_postraitables()
void Loi_Etat_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Definition at line 477 of file Loi_Etat_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<"Loi_Etat_base : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, and Champs_compris::liste_noms_compris().
info()
const Type_info * Loi_Etat_base::info () static
Definition at line 25 of file Loi_Etat_base.cpp.
initialiser()
virtual void Loi_Etat_base::initialiser () pure virtual
Implemented in Loi_Etat_GP_base, and Loi_Etat_GR_base.
initialiser_inco_ch()
void Loi_Etat_base::initialiser_inco_ch () virtual
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
Reimplemented in Loi_Etat_GR_base, Loi_Etat_Multi_GP_base, Loi_Etat_rhoT_GP_QC, and Loi_Etat_Multi_GP_WC.
Definition at line 117 of file Loi_Etat_base.cpp.
{
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  tab_rho_n=tab_rho;
  tab_rho_np1=tab_rho;
  calculer_masse_volumique();
  double t = le_prob_->schema_temps().temps_courant();
  mettre_a_jour(t);
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
}
References calculer_masse_volumique(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), le_fluide, le_prob_, Milieu_base::masse_volumique(), mettre_a_jour(), Probleme_base::schema_temps(), tab_rho_n, tab_rho_np1, Schema_Temps_base::temps_courant(), and Champ::valeurs().
Referenced by Loi_Etat_Multi_GP_base::initialiser_inco_ch(), and Loi_Etat_rhoT_GP_QC::initialiser_inco_ch().
inverser_Pth()
virtual double Loi_Etat_base::inverser_Pth (double , double) pure virtual
Implemented in Loi_Etat_rhoT_GP_QC, Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, Loi_Etat_GR_base, and Loi_Etat_GP_WC.
mettre_a_jour()
void Loi_Etat_base::mettre_a_jour (double temps)
Met a jour la loi d'etat et le champ rho.
Definition at line 165 of file Loi_Etat_base.cpp.
{
// remplissage de rho avec rho(n+1)
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  int i, n=tab_rho.size_totale();
  for (i=0 ; i<n ; i++)
    {
      tab_rho_n(i) = tab_rho_np1(i);
      tab_rho(i,0) = tab_rho_np1(i);
    }
  le_fluide->masse_volumique().mettre_a_jour(temps);
}
References le_fluide, Milieu_base::masse_volumique(), Champ::mettre_a_jour(), TRUSTVect< _TYPE_ >::size_totale(), tab_rho_n, tab_rho_np1, and Champ::valeurs().
Referenced by initialiser_inco_ch(), and preparer_calcul().
Prandt()
double Loi_Etat_base::Prandt () const inline
Definition at line 88 of file Loi_Etat_base.h.
{ return Pr_; }
References Pr_.
preparer_calcul()
void Loi_Etat_base::preparer_calcul (void) virtual
Prepare le fluide au calcul.
Definition at line 143 of file Loi_Etat_base.cpp.
{
  remplir_T();
  calculer_masse_volumique();
  double t = le_prob_->schema_temps().temps_courant();
  mettre_a_jour(t);
}
References calculer_masse_volumique(), le_prob_, mettre_a_jour(), remplir_T(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
printOn()
Sortie & Loi_Etat_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, Loi_Etat_GR_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_rhoT_GR_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 30 of file Loi_Etat_base.cpp.
{
  os << que_suis_je() << finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, Loi_Etat_GR_base, Loi_Etat_Melange_GP_base, Loi_Etat_Mono_GP_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_rhoT_GR_QC, Loi_Etat_Binaire_GP_WC, Loi_Etat_GP_WC, and Loi_Etat_Multi_GP_WC.
Definition at line 36 of file Loi_Etat_base.cpp.
{
  return is;
}
remplir_T()
virtual void Loi_Etat_base::remplir_T () pure virtual
Implemented in Loi_Etat_GP_base, and Loi_Etat_GR_base.
Referenced by preparer_calcul().
rho_n()
const DoubleTab & Loi_Etat_base::rho_n () const inline
Definition at line 86 of file Loi_Etat_base.h.
{ return tab_rho_n; }
References tab_rho_n.
rho_np1()
const DoubleTab & Loi_Etat_base::rho_np1 () const inline
Definition at line 87 of file Loi_Etat_base.h.
{ return tab_rho_np1; }
References tab_rho_np1.
self_cast() [1/2]
const Loi_Etat_base & Loi_Etat_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Loi_Etat_base.cpp.
self_cast() [2/2]
Loi_Etat_base & Loi_Etat_base::self_cast (Objet_U & r) static
Definition at line 25 of file Loi_Etat_base.cpp.
temperature()
const DoubleTab & Loi_Etat_base::temperature () const inline
Definition at line 85 of file Loi_Etat_base.h.
{ return ch_temperature().valeurs(); }
References ch_temperature(), and Champ_Don::valeurs().
type_fluide()
virtual const Nom Loi_Etat_base::type_fluide () const pure virtual
Implemented in Loi_Etat_Binaire_GP_base, Loi_Etat_GP_base, and Loi_Etat_GR_base.
Member Data Documentation
champs_compris_
Champs_compris Loi_Etat_base::champs_compris_ private
Definition at line 99 of file Loi_Etat_base.h.
Referenced by champs_compris(), get_champ(), and get_noms_champs_postraitables().
debug
int Loi_Etat_base::debug protected
Definition at line 96 of file Loi_Etat_base.h.
Referenced by Loi_Etat_Mono_GP_base::readOn(), and Loi_Etat_rhoT_GR_QC::readOn().
info_obj
const Type_info Loi_Etat_base::info_obj static
Definition at line 44 of file Loi_Etat_base.h.
le_fluide
Ref_Fluide_Dilatable_base Loi_Etat_base::le_fluide protected
Definition at line 91 of file Loi_Etat_base.h.
Referenced by associer_fluide(), Loi_Etat_GP_base::associer_fluide(), calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_GR_base::calculer_Cp(), Loi_Etat_Multi_GP_base::calculer_Cp(), calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Loi_Etat_GR_base::inverser_Pth(), mettre_a_jour(), Loi_Etat_GP_base::remplir_T(), Loi_Etat_GR_base::remplir_T(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
le_prob_
Ref_Probleme_base Loi_Etat_base::le_prob_ protected
Definition at line 92 of file Loi_Etat_base.h.
Referenced by assoscier_probleme(), initialiser_inco_ch(), and preparer_calcul().
Pr_
double Loi_Etat_base::Pr_ protected
Definition at line 95 of file Loi_Etat_base.h.
Referenced by calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Prandt(), Loi_Etat_Mono_GP_base::readOn(), Loi_Etat_Multi_GP_QC::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), and Loi_Etat_Multi_GP_WC::readOn().
tab_rho_n
DoubleTab Loi_Etat_base::tab_rho_n protected
Definition at line 94 of file Loi_Etat_base.h.
Referenced by abortTimeStep(), calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), mettre_a_jour(), and rho_n().
tab_rho_np1
DoubleTab Loi_Etat_base::tab_rho_np1 protected
Definition at line 94 of file Loi_Etat_base.h.
Referenced by abortTimeStep(), calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), mettre_a_jour(), and rho_np1().
temperature_
Champ_Don Loi_Etat_base::temperature_ protected
Definition at line 93 of file Loi_Etat_base.h.
Referenced by Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), ch_temperature(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), Loi_Etat_GP_base::remplir_T(), and Loi_Etat_GR_base::remplir_T().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_base.cpp