TRUST: Perte_Charge_Singuliere_VEF_Face Class Reference
Perte_Charge_Singuliere_VEF_Face Class Reference
class Perte_Charge_Singuliere_VEF_Face
#include <Perte_Charge_Singuliere_VEF_Face.h>
Public Member Functions
Perte_Charge_Singuliere_VEF_Face ()
~Perte_Charge_Singuliere_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
contribution a la matrice implicite des termes sources
par defaut pas de contribution
void remplir_num_faces (Entree &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Perte_Charge_VEF_Face
Perte_Charge_VEF_Face ()
~Perte_Charge_VEF_Face () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const override=0
DoubleTab & calculer (DoubleTab &) const override=0
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Public Member Functions inherited from Perte_Charge_Singuliere
virtual ~Perte_Charge_Singuliere ()
Entree & lire_donnees (Entree &)
Lit les specifications d'une perte de charge singuliere
a partir d'un flot d'entree.
virtual void lire_surfaces (Entree &, const Domaine &, const Zone_dis_base &, IntVect &, IntVect &)
double K () const
double calculate_Q (const Equation_base &eqn, const IntVect &num_faces, const IntVect &sgn) const
void update_K (const Equation_base &eqn, double deb, DoubleVect &bilan)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Renvoie la direction de perte de charge.
(X,Y ou Z), ou -1 si toutes les directions.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Perte_Charge_Singuliere_VEF_Face & self_cast (Objet_U &)
static const Perte_Charge_Singuliere_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Perte_Charge_VEF_Face
static const Type_info * info ()
static Perte_Charge_VEF_Face & self_cast (Objet_U &)
static const Perte_Charge_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Perte_Charge_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Member Functions inherited from Perte_Charge_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect sgn
Protected Attributes inherited from Perte_Charge_VEF_Face
Ref_Champ_Inc_base la_vitesse
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Ref_Fluide_base le_fluide
IntVect num_faces
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Protected Attributes inherited from Perte_Charge_Singuliere
double K_
Nom identifiant_
int regul_
Parser_U deb_cible_
Parser_U eps_
Protected Attributes inherited from Perte_Charge
int direction_perte_charge_
Detailed Description
class Perte_Charge_Singuliere_VEF_Face
See also
Perte_Charge_VEF_Face
Definition at line 35 of file Perte_Charge_Singuliere_VEF_Face.h.
Constructor & Destructor Documentation
Perte_Charge_Singuliere_VEF_Face()
Perte_Charge_Singuliere_VEF_Face::Perte_Charge_Singuliere_VEF_Face ()
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
~Perte_Charge_Singuliere_VEF_Face()
Perte_Charge_Singuliere_VEF_Face::~Perte_Charge_Singuliere_VEF_Face ()
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Perte_Charge_Singuliere_VEF_Face::ajouter (DoubleTab & resu) const override virtual
< vitesse debitante
< pressure loss
< Taking account of inclined plane
Implements Perte_Charge_VEF_Face.
Definition at line 83 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
// const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleVect& porosite_surf = zone_VEF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  int nb_faces = num_faces.size();
  int numfa;
  double Ud; //!< vitesse debitante
  double area;
  double coefK; //!< pressure loss
  for (int i=0; i<nb_faces; i++)
    {
      numfa = num_faces[i];
      for (int j=0; j<dimension; j++)
        {
          Ud = vit(numfa,j)*porosite_surf[numfa];
// area=zone_VEF.face_surfaces(numfa);
          area=direction_perte_charge() < 0 ? zone_VEF.face_surfaces(numfa) : std::fabs(zone_VEF.face_normales(numfa,direction_perte_charge())); //!< Taking account of inclined plane
          coefK=K();
// if (j!=direction_perte_charge()) coefK=0.;
          resu(numfa,j) -= 0.5*coefK*Ud*std::fabs(Ud)*area*porosite_surf[numfa];
        }
    }
  return resu;
}
References Objet_U::dimension, Perte_Charge::direction_perte_charge(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Perte_Charge_Singuliere::K(), Perte_Charge_VEF_Face::la_vitesse, Perte_Charge_VEF_Face::la_zone_VEF, Perte_Charge_VEF_Face::num_faces, Zone_VF::porosite_face(), TRUSTVect< _TYPE_ >::size(), Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
Referenced by Perte_Charge_Singuliere_QC_VEF_P1NC::ajouter_mere(), and calculer().
calculer()
DoubleTab & Perte_Charge_Singuliere_VEF_Face::calculer (DoubleTab & resu) const override virtual
Implements Perte_Charge_VEF_Face.
Definition at line 113 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References ajouter().
contribuer_a_avec()
void Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources
par defaut pas de contribution
< vitesse debitante
< pressure loss
< Taking account of inclined plane
Reimplemented from Source_base.
Definition at line 119 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const DoubleVect& porosite_surf = zone_VEF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  int nb_faces = num_faces.size();
  int numfa;
  double Ud; //!< vitesse debitante
  double area;
  double coefK; //!< pressure loss
  for (int i=0; i<nb_faces; i++)
    {
      numfa = num_faces[i];
      for (int j=0; j<dimension; j++)
        {
// Ud    = vit(numfa,j)*porosite_surf[numfa];
          Ud = porosite_surf[numfa];
          double Ud2= vit(numfa,j)*porosite_surf[numfa];
          int n0=numfa*dimension+j;
// area=zone_VEF.face_surfaces(numfa);
          area=direction_perte_charge() < 0 ? zone_VEF.face_surfaces(numfa) : std::fabs(zone_VEF.face_normales(numfa,direction_perte_charge())); //!< Taking account of inclined plane
          coefK=K();
// if (j!=direction_perte_charge()) coefK=0.;
          matrice.coef(n0,n0)+= 0.5*coefK*Ud*std::fabs(Ud2)*area*porosite_surf[numfa];
        }
    }
}
References Matrice_Morse::coef(), Objet_U::dimension, Perte_Charge::direction_perte_charge(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Perte_Charge_Singuliere::K(), Perte_Charge_VEF_Face::la_vitesse, Perte_Charge_VEF_Face::la_zone_VEF, Perte_Charge_VEF_Face::num_faces, Zone_VF::porosite_face(), TRUSTVect< _TYPE_ >::size(), Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
cree_instance()
Objet_U * Perte_Charge_Singuliere_VEF_Face::cree_instance () static
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
duplique()
int Perte_Charge_Singuliere_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
get_info()
const Type_info * Perte_Charge_Singuliere_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
info()
const Type_info * Perte_Charge_Singuliere_VEF_Face::info () static
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
mettre_a_jour()
void Perte_Charge_Singuliere_VEF_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 150 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  Perte_Charge_VEF_Face::mettre_a_jour(temps);
  update_K(equation(), calculate_Q(equation(), num_faces, sgn), bilan());
}
References Source_base::bilan(), Perte_Charge_Singuliere::calculate_Q(), MorEqn::equation(), Perte_Charge_VEF_Face::mettre_a_jour(), Perte_Charge_VEF_Face::num_faces, sgn, and Perte_Charge_Singuliere::update_K().
printOn()
Sortie & Perte_Charge_Singuliere_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 29 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
Referenced by Perte_Charge_Singuliere_QC_VEF_P1NC::printOn().
readOn()
Entree & Perte_Charge_Singuliere_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 37 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  Perte_Charge_Singuliere::lire_donnees(s);
  remplir_num_faces(s);
  if (regul_) //fichier de sortie si regulation
    {
      bilan().resize(3); //K deb cible
      set_fichier(Nom("K_") + identifiant_);
      set_description(Nom("Regulation du Ksing de la surface ") + identifiant_ + "\nt K deb cible");
    }
  return s;
}
References Source_base::bilan(), Perte_Charge_Singuliere::identifiant_, Perte_Charge_Singuliere::lire_donnees(), Perte_Charge_Singuliere::regul_, remplir_num_faces(), TRUSTVect< _TYPE_ >::resize(), Source_base::set_description(), and Source_base::set_fichier().
Referenced by Perte_Charge_Singuliere_QC_VEF_P1NC::readOn().
remplir_num_faces()
void Perte_Charge_Singuliere_VEF_Face::remplir_num_faces (Entree & s)
< not to count several (number of processes) times the same face
Definition at line 59 of file Perte_Charge_Singuliere_VEF_Face.cpp.
{
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,equation().zone_dis().valeur());
  int taille_bloc = zone_VEF.nb_elem();
  num_faces.resize(taille_bloc);
  lire_surfaces(s,le_domaine,zone_VEF,num_faces, sgn);
// int nfac_tot = mp_sum(num_faces.size());
  int nfac_tot = (int)mp_max(num_faces.size()); //!< not to count several (number of processes) times the same face
  if(je_suis_maitre())
    {
      Cerr << "Faces number found in Perte_Charge_Singuliere_VEF_Face : " << nfac_tot << finl;
      if (nfac_tot==0)
        {
          Cerr << "Error when defining the surface plane for the singular porosity :" << finl;
          Cerr << "No mesh faces has been found for the surface plane." << finl;
          Cerr << "Check the coordinate of the surface plane which should match mesh coordinates." << finl;
          exit();
        }
    }
}
References Cerr, Probleme_base::domaine(), MorEqn::equation(), Process::exit(), finl, Process::je_suis_maitre(), Perte_Charge_Singuliere::lire_surfaces(), Process::mp_max(), Zone_dis_base::nb_elem(), Perte_Charge_VEF_Face::num_faces, Equation_base::probleme(), ref_cast, TRUSTVect< _TYPE_ >::resize(), sgn, TRUSTVect< _TYPE_ >::size(), and valeur().
Referenced by readOn().
self_cast() [1/2]
const Perte_Charge_Singuliere_VEF_Face & Perte_Charge_Singuliere_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
self_cast() [2/2]
Perte_Charge_Singuliere_VEF_Face & Perte_Charge_Singuliere_VEF_Face::self_cast (Objet_U & r) static
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
taille_memoire()
unsigned Perte_Charge_Singuliere_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Perte_Charge_Singuliere_VEF_Face.cpp.
Member Data Documentation
info_obj
const Type_info Perte_Charge_Singuliere_VEF_Face::info_obj static
Definition at line 39 of file Perte_Charge_Singuliere_VEF_Face.h.
sgn
IntVect Perte_Charge_Singuliere_VEF_Face::sgn protected
Definition at line 50 of file Perte_Charge_Singuliere_VEF_Face.h.
Referenced by mettre_a_jour(), and remplir_num_faces().
The documentation for this class was generated from the following files:
src/VEF/Sources/Perte_Charge_Singuliere_VEF_Face.h
src/VEF/Sources/Perte_Charge_Singuliere_VEF_Face.cpp