TRUST: Champ_Ostwald_VDF Class Reference
Champ_Ostwald_VDF Class Reference
classe Champ_Ostwald_VDF
Represente un champ en discretisation VDF qui varie en fonction
de la consistance et de l'indice de structure.
Champ utilise pour le fluide d'Ostwald et la discretisation VDF.
Fait reference a Champ_Face pour lancer le calcul de D:D dans Champ4.cpp
zone_VDF pou utiliser la
#include <Champ_Ostwald_VDF.h>
Public Member Functions
Champ_Ostwald_VDF ()
~Champ_Ostwald_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Champ_Face & mon_champs () const
void associer_champ (const Champ_Face &)
void associer_zone_dis_base (const Zone_dis_base &la_zone_dis_base) override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
const Zone_dis_base & zone_dis_base () const override
void mettre_a_jour (double temps) override
met le parametre mu a jour
void me_calculer (double tps) override
Calcul le champ Ostwald :
calcul de D::D
puis calcul de mu.
int initialiser (const double temps) override
Initialise le champs.
Public Member Functions inherited from Champ_Ostwald
Champ_Ostwald ()
~Champ_Ostwald ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void me_calculer (double tps)
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
int initialiser (const double temps) override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual const Fluide_Ostwald & mon_fluide () const
virtual void associer_fluide (const Fluide_Ostwald &)
void associer_zone_dis_base (const Zone_dis_base &la_zone_dis_base) override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante.
Champ_base & affecter_ (const Champ_base &) override
const Zone_dis_base & zone_dis_base () const override
Public Member Functions inherited from Champ_Fonc_P0_base
Champ_Fonc_P0_base ()
~Champ_Fonc_P0_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Champ_base & affecter_ (const Champ_base &) override
int fixer_nb_valeurs_nodales (int n) override
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
double moyenne (int) const
DoubleVect moyenne () const
int imprime (Sortie &, int) const override
void mettre_a_jour (double) override
mettre_a_jour de la classe de base Champ_base :ne fait rien !
double valeur_au_bord (int face) const
Public Member Functions inherited from Champ_Fonc_base
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from Champ_implementation_P0
~Champ_implementation_P0 () override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_P0 (Sortie &, int) const
Public Member Functions inherited from Champ_implementation_base
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Ostwald_VDF & self_cast (Objet_U &)
static const Champ_Ostwald_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Ostwald
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Ostwald & self_cast (Objet_U &)
static const Champ_Ostwald & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_P0_base
static const Type_info * info ()
static Champ_Fonc_P0_base & self_cast (Objet_U &)
static const Champ_Fonc_P0_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_base
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Ostwald
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_P0_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le champ sur un flot de sortie.
Entree & readOn (Entree &) override
Ne sert a rien
Format:
void calculer_mu (DoubleTab &)
Calcul la viscosite mu en fonction de la consistance et de
l'indice de structure en utilisant la loi d'Ostwald. Pour
des viscsites tres faible et tres fortes on utilise une regression.
Sortie & printOn (Sortie &x) const override
Imprime le champ sur un flot de sortie.
Imprime le nb_de composantes.
Entree & readOn (Entree &) override
Lit un champ a partir d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp)
Format:
Champ_Ostwald nb_comp.
Protected Member Functions inherited from Champ_Fonc_P0_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Champ_base & le_champ (void) override
const Champ_base & le_champ (void) const override
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Champ_implementation_P0
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const override
int affecter_ (const Champ_base &)
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation_base
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Protected Attributes
Ref_Champ_Face mon_champ_
pour calculer D::D
Ref_Zone_VDF la_zone_VDF
Protected Attributes inherited from Champ_Ostwald
Ref_Fluide_Ostwald mon_fluide_
pour obtenir K et N
Protected Attributes inherited from Champ_Fonc_P0_base
Ref_Zone_VF la_zone_VF
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_Ostwald_VDF
Represente un champ en discretisation VDF qui varie en fonction
de la consistance et de l'indice de structure.
Champ utilise pour le fluide d'Ostwald et la discretisation VDF.
Fait reference a Champ_Face pour lancer le calcul de D:D dans Champ4.cpp
zone_VDF pou utiliser la
Definition at line 38 of file Champ_Ostwald_VDF.h.
Constructor & Destructor Documentation
Champ_Ostwald_VDF()
Champ_Ostwald_VDF::Champ_Ostwald_VDF ()
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
~Champ_Ostwald_VDF()
Champ_Ostwald_VDF::~Champ_Ostwald_VDF ()
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
Member Function Documentation
associer_champ()
void Champ_Ostwald_VDF::associer_champ (const Champ_Face & un_champ) inline
Definition at line 80 of file Champ_Ostwald_VDF.h.
{
  mon_champ_ = un_champ;
}
References mon_champ_.
Referenced by VDF_discretisation::proprietes_physiques_fluide_Ostwald().
associer_zone_dis_base()
void Champ_Ostwald_VDF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) inline override virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Champ_Ostwald.
Definition at line 86 of file Champ_Ostwald_VDF.h.
{
  Cerr<<"on est dans  Champ_Ostwald_VDF::associer_zone_dis_base "<<finl;
  la_zone_VDF = (const Zone_VDF&) la_zone_dis_base;
}
References Cerr, finl, and la_zone_VDF.
Referenced by VDF_discretisation::proprietes_physiques_fluide_Ostwald().
calculer_mu()
void Champ_Ostwald_VDF::calculer_mu (DoubleTab & mu_tab) protected
Calcul la viscosite mu en fonction de la consistance et de
l'indice de structure en utilisant la loi d'Ostwald. Pour
des viscsites tres faible et tres fortes on utilise une regression.
< K varie en fonction de la temperature
Definition at line 107 of file Champ_Ostwald_VDF.cpp.
{
  const double d_n = mon_fluide_->indice_struct().valeurs()(0,0);
  for (int i=0 ; i<nb_valeurs_nodales() ; i++)
    {
      if (sub_type(Champ_Uniforme, mon_fluide_->consistance().valeur()))
        {
          const double d_k = mon_fluide_->consistance().valeurs()(0,0);
          if ( mu_tab[i] < 1.E-4 )
            mu_tab[i] = d_k * pow( 0.5 * 1.E-4 , (d_n - 1.) / 2.);
          else if ( mu_tab[i] > 1.E16 )
            mu_tab[i] = d_k * pow( 0.5 * 1.E16 , (d_n - 1.) / 2.);
          else
            mu_tab[i] = d_k * pow( 0.5 * mu_tab[i] , (d_n - 1.) / 2.);
        }
      else  //!< K varie en fonction de la temperature
        {
          const DoubleTab& K_tab = mon_fluide_->consistance().valeurs();
          if ( mu_tab[i] < 1.E-4 )
            mu_tab[i] = K_tab[i] * pow( 0.5 * 1.E-4 , (d_n - 1.) / 2.);
          else if ( mu_tab[i] > 1.E16 )
            mu_tab[i] = K_tab[i] * pow( 0.5 * 1.E16 , (d_n - 1.) / 2.);
          else
            mu_tab[i] = K_tab[i] * pow( 0.5 * mu_tab[i] , (d_n - 1.) / 2.);
        }
    }
}
References Fluide_Ostwald::consistance(), Fluide_Ostwald::indice_struct(), Champ_Ostwald::mon_fluide_, Champ_Don_base::nb_valeurs_nodales(), sub_type, Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
Referenced by me_calculer().
cree_instance()
Objet_U * Champ_Ostwald_VDF::cree_instance () static
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
duplique()
int Champ_Ostwald_VDF::duplique () const override virtual
Reimplemented from Champ_Ostwald.
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
get_info()
const Type_info * Champ_Ostwald_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
info()
const Type_info * Champ_Ostwald_VDF::info () static
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
initialiser()
int Champ_Ostwald_VDF::initialiser (const double temps) override virtual
Initialise le champs.
Reimplemented from Champ_Ostwald.
Definition at line 178 of file Champ_Ostwald_VDF.cpp.
{
  mettre_a_jour(un_temps);
  return 1;
}
References mettre_a_jour().
me_calculer()
void Champ_Ostwald_VDF::me_calculer (double tps) override virtual
Calcul le champ Ostwald :
calcul de D::D
puis calcul de mu.
Reimplemented from Champ_Ostwald.
Definition at line 154 of file Champ_Ostwald_VDF.cpp.
{
  if (temps_ != tps)
    {
// Cerr<< "Calcul de Mu Ostwald"<<finl;
      mon_champ_->calculer_dscald_centre_element(valeurs());
      calculer_mu(valeurs());
    }
}
References Champ_Face::calculer_dscald_centre_element(), calculer_mu(), mon_champ_, Champ_base::temps_, and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
mettre_a_jour()
void Champ_Ostwald_VDF::mettre_a_jour (double temps) override virtual
met le parametre mu a jour
Reimplemented from Champ_Ostwald.
Definition at line 81 of file Champ_Ostwald_VDF.cpp.
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Don_base::mettre_a_jour(tps);
}
References Champ_base::changer_temps(), me_calculer(), and Champ_Don_base::mettre_a_jour().
Referenced by initialiser().
mon_champs()
const Champ_Face & Champ_Ostwald_VDF::mon_champs () const inline
Definition at line 68 of file Champ_Ostwald_VDF.h.
{
  return mon_champ_.valeur();
}
References mon_champ_, and Ref_Champ_Face::valeur().
printOn()
Sortie & Champ_Ostwald_VDF::printOn (Sortie & os) const override protected virtual
Imprime le champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 38 of file Champ_Ostwald_VDF.cpp.
{
// const int nb_compo = valeurs()(0,0);
  os << valeurs()(0,0);
  return os;
}
References Champ_Don_base::valeurs().
readOn()
Entree & Champ_Ostwald_VDF::readOn (Entree & is) override protected virtual
Ne sert a rien
Format:
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Ostwald.
Definition at line 62 of file Champ_Ostwald_VDF.cpp.
{
  return is;
}
self_cast() [1/2]
const Champ_Ostwald_VDF & Champ_Ostwald_VDF::self_cast (const Objet_U & r) static
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
self_cast() [2/2]
Champ_Ostwald_VDF & Champ_Ostwald_VDF::self_cast (Objet_U & r) static
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
taille_memoire()
unsigned Champ_Ostwald_VDF::taille_memoire () const override virtual
Reimplemented from Champ_Ostwald.
Definition at line 21 of file Champ_Ostwald_VDF.cpp.
zone_dis_base()
const Zone_dis_base & Champ_Ostwald_VDF::zone_dis_base () const override virtual
Reimplemented from Champ_Ostwald.
Definition at line 185 of file Champ_Ostwald_VDF.cpp.
{
  return la_zone_VDF.valeur();
}
References la_zone_VDF, and Ref_Zone_VDF::valeur().
Member Data Documentation
info_obj
const Type_info Champ_Ostwald_VDF::info_obj static
Definition at line 41 of file Champ_Ostwald_VDF.h.
la_zone_VDF
Ref_Zone_VDF Champ_Ostwald_VDF::la_zone_VDF protected
Definition at line 63 of file Champ_Ostwald_VDF.h.
Referenced by associer_zone_dis_base(), and zone_dis_base().
mon_champ_
Ref_Champ_Face Champ_Ostwald_VDF::mon_champ_ protected
pour calculer D::D
Definition at line 62 of file Champ_Ostwald_VDF.h.
Referenced by associer_champ(), me_calculer(), and mon_champs().
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_Ostwald_VDF.h
src/VDF/Champs/Champ_Ostwald_VDF.cpp