TRUST: Deriv_Matrice_Base Class Reference
Deriv_Matrice_Base Class Reference
#include <Deriv_Matrice_Base.h>
Public Member Functions
~Deriv_Matrice_Base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Matrice_Base ()
Deriv_Matrice_Base (const Deriv_Matrice_Base &)
const Matrice_Base & valeur () const
Matrice_Base & valeur ()
const Matrice_Base * operator-> () const
Matrice_Base * operator-> ()
const Deriv_Matrice_Base & operator= (const Matrice_Base &)
const Deriv_Matrice_Base & operator= (const Deriv_Matrice_Base &)
operator const Matrice_Base & () const
operator Matrice_Base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Matrice_Base & self_cast (Objet_U &)
static const Deriv_Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Matrice_Base * pointeur_
Detailed Description
Definition at line 21 of file Deriv_Matrice_Base.h.
Constructor & Destructor Documentation
~Deriv_Matrice_Base()
Deriv_Matrice_Base::~Deriv_Matrice_Base ()
Definition at line 19 of file Deriv_Matrice_Base.cpp.
Deriv_Matrice_Base() [1/2]
Deriv_Matrice_Base::Deriv_Matrice_Base ()
Definition at line 19 of file Deriv_Matrice_Base.cpp.
Deriv_Matrice_Base() [2/2]
Deriv_Matrice_Base::Deriv_Matrice_Base (const Deriv_Matrice_Base & t)
Definition at line 19 of file Deriv_Matrice_Base.cpp.
Member Function Documentation
cree_instance()
Objet_U * Deriv_Matrice_Base::cree_instance () static
Definition at line 19 of file Deriv_Matrice_Base.cpp.
duplique()
int Deriv_Matrice_Base::duplique () const override virtual
Implements Objet_U.
Reimplemented in Matrice.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
get_info()
const Type_info * Deriv_Matrice_Base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Matrice.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
get_info_ptr()
const Type_info & Deriv_Matrice_Base::get_info_ptr () const override virtual
Implements O_U_Ptr.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
info()
const Type_info * Deriv_Matrice_Base::info () static
Definition at line 19 of file Deriv_Matrice_Base.cpp.
operator const Matrice_Base &()
Deriv_Matrice_Base::operator const Matrice_Base & () const
Definition at line 19 of file Deriv_Matrice_Base.cpp.
operator Matrice_Base &()
Deriv_Matrice_Base::operator Matrice_Base & ()
Definition at line 19 of file Deriv_Matrice_Base.cpp.
operator->() [1/2]
Matrice_Base * Deriv_Matrice_Base::operator-> () inline
Definition at line 21 of file Deriv_Matrice_Base.h.
operator->() [2/2]
const Matrice_Base * Deriv_Matrice_Base::operator-> () const inline
Definition at line 21 of file Deriv_Matrice_Base.h.
operator=() [1/2]
const Deriv_Matrice_Base & Deriv_Matrice_Base::operator= (const Deriv_Matrice_Base & t)
Definition at line 19 of file Deriv_Matrice_Base.cpp.
operator=() [2/2]
const Deriv_Matrice_Base & Deriv_Matrice_Base::operator= (const Matrice_Base & t)
Definition at line 19 of file Deriv_Matrice_Base.cpp.
printOn()
Sortie & Deriv_Matrice_Base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Matrice.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
readOn()
Entree & Deriv_Matrice_Base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Matrice.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
self_cast() [1/2]
const Deriv_Matrice_Base & Deriv_Matrice_Base::self_cast (const Objet_U & r) static
Definition at line 19 of file Deriv_Matrice_Base.cpp.
self_cast() [2/2]
Deriv_Matrice_Base & Deriv_Matrice_Base::self_cast (Objet_U & r) static
Definition at line 19 of file Deriv_Matrice_Base.cpp.
set_O_U_Ptr()
void Deriv_Matrice_Base::set_O_U_Ptr (Objet_U * ptr) override protected virtual
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
taille_memoire()
unsigned Deriv_Matrice_Base::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Matrice.
Definition at line 19 of file Deriv_Matrice_Base.cpp.
valeur() [1/2]
Matrice_Base & Deriv_Matrice_Base::valeur () inline
Definition at line 21 of file Deriv_Matrice_Base.h.
valeur() [2/2]
const Matrice_Base & Deriv_Matrice_Base::valeur () const inline
Definition at line 21 of file Deriv_Matrice_Base.h.
Referenced by Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Op_Diff_RotRot::ajouter(), Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_from_stencil(), assembler(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Matrice_Bloc::build_stencil(), Op_Diff_RotRot::calculer_vorticite(), Assembleur_P_VEFPreP1B::changer_base_matrice(), Matrice_Bloc::check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), Assembleur_P_VDF::construire(), construire_matrice_implicite(), Navier_Stokes_std::corriger_derivee_impl(), Equation_base::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), estim_cond(), Matrix_tools::extend_matrix_stencil(), Champ_P1NC_implementation::filtrer_resu(), Matrice_Bloc::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Bloc::imprimer(), Matrice_Bloc::imprimer_formatte(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Matrice_Morse_Sym::Matrice_Morse_Sym(), modifieP1P1neumann(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Matrice_Bloc::nb_colonnes(), Matrice_Bloc::nb_lignes(), operation01(), operation11(), operator*(), Matrice_Morse_Sym::operator=(), Matrice::operator=(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), SSOR::preconditionner_(), ILU::prepare_(), Precond_local::prepare_(), Solv_GCP::prepare_data(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Matrice_Morse_Sym::renumerote(), Solv_Cholesky::resoudre_systeme(), Solv_Gen::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Solv_Petsc::resoudre_systeme(), Matrice_Bloc::scale(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), SSOR::ssor(), Op_Diff_RotRot::tester(), Op_Diff_PolyMAC_base::update_aux(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), and zero().
Member Data Documentation
info_obj
const Type_info Deriv_Matrice_Base::info_obj static
Definition at line 21 of file Deriv_Matrice_Base.h.
pointeur_
Matrice_Base* Deriv_Matrice_Base::pointeur_ private
Definition at line 21 of file Deriv_Matrice_Base.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Deriv_Matrice_Base.h
src/Kernel/Math/Matrices/Deriv_Matrice_Base.cpp