TRUST: TRUSTChamp_Don_generique< _TYPE_ > Class Template Reference
TRUSTChamp_Don_generique< _TYPE_ > Class Template Reference
#include <TRUSTChamp_Don_generique.h>
Public Member Functions
Sortie & printOn (Sortie &os) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
void mettre_a_jour (double) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
double valeur_a_compo (const DoubleVect &position, int ncomp) const override
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
Domaine & interprete_get_domaine (const Nom &nom)
Champ_base & affecter (const Champ_base &ch)
Champ_base & affecter_ (const Champ_base &ch) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &vals) const override
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &vals, int le_poly) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &vals) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &vals, int ncomp) const override
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &vals) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &vals, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from Parser_Eval
Vect_Parser_U & fonction ()
Parser_U & parser (int i)
Parser_U & parser (int i) const
void eval_fct (const DoubleVect &positions, DoubleVect &val) const
void eval_fct (const DoubleTab &positions, DoubleTab &val) const
void eval_fct (const DoubleTab &positions, DoubleVect &val, const int ncomp) const
void eval_fct (const DoubleVect &positions, const double tps, DoubleVect &val) const
void eval_fct (const DoubleTab &positions, const double tps, DoubleTab &val) const
void eval_fct (const DoubleTab &positions, const double tps, DoubleVect &val, const int ncomp) const
void eval_fct (const DoubleTab &positions, const double tps, const DoubleTab &val_param, DoubleTab &val) const
void eval_fct (const DoubleTab &positions, const double tps, const DoubleTab &val_param, DoubleVect &val, const int ncomp) const
void eval_fct (const DoubleTabs &variables, DoubleTab &val) const
Protected Member Functions
void mettre_a_jour_positions (DoubleTab &)
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Domaine mon_domaine
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from Parser_Eval
Vect_Parser_U fonction_
Private Member Functions
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > valeur_a_ (const DoubleVect &position, DoubleVect &valeurs) const
Renvoie la valeur du champ au point specifie par ses coordonnees.
Parametre: DoubleVect& x
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& val
Signification: la valeur du champ au point specifie.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > valeur_a_ (const DoubleVect &position, DoubleVect &valeurs) const
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > valeur_a_elem_ (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& val
Signification: la valeur du champ au point specifie
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > valeur_a_elem_ (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::TXYZ, double > valeur_a_elem_compo_ (const DoubleVect &position, int le_poly, int ncomp) const
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::TXYZ, double > valeur_a_elem_compo_ (const DoubleVect &position, int le_poly, int ncomp) const
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::LU, DoubleTab & > valeur_aux_ (const DoubleTab &positions, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parametre: DoubleTab& x
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleTab& val
Signification: le tableau des valeurs du champ aux points specifies.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::LU, DoubleTab & > valeur_aux_ (const DoubleTab &positions, DoubleTab &valeurs) const
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > valeur_aux_compo_ (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees.
Parametre: DoubleVect& x
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleVect& valeurs
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > valeur_aux_compo_ (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::LU, DoubleTab & > valeur_aux_elems_ (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::LU, DoubleTab & > valeur_aux_elems_ (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > valeur_aux_elems_compo_ (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parametre: DoubleTab& x
Signification: le tableau des coordonnees des points de calcul
Parametre: IntVect& les_polys
Signification: le tableau des elements dans lesquels sont situes les points de calcul
Parametre: DoubleVect& val
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
template<Champ_Don_Type T = _TYPE_>
enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > valeur_aux_elems_compo_ (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Additional Inherited Members
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Detailed Description
template<Champ_Don_Type _TYPE_>
class TRUSTChamp_Don_generique< _TYPE_ >
Definition at line 28 of file TRUSTChamp_Don_generique.h.
Member Function Documentation
affecter()
template<Champ_Don_Type _TYPE_> Champ_base & TRUSTChamp_Don_generique< _TYPE_ >::affecter (const Champ_base & ch) inline
Definition at line 43 of file TRUSTChamp_Don_generique.h.
  {
    Champ_base::affecter_erreur();
    return *this;
  }
References Champ_base::affecter_erreur().
affecter_()
template<Champ_Don_Type _TYPE_> Champ_base & TRUSTChamp_Don_generique< _TYPE_ >::affecter_ (const Champ_base &) inline override virtual
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
< throw
Reimplemented from Champ_Don_base.
Definition at line 49 of file TRUSTChamp_Don_generique.h.
  {
    static constexpr bool IS_LU = (_TYPE_ == Champ_Don_Type::LU);
    if (IS_LU) return Champ_Don_base::affecter_(ch); //!< throw
    if (sub_type(Champ_Uniforme, ch)) valeurs() = ch.valeurs()(0, 0);
    else valeurs() = ch.valeurs();
    return *this;
  }
References Champ_Don_base::affecter_(), LU, sub_type, Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
interprete_get_domaine()
template<Champ_Don_Type _TYPE_> Domaine & TRUSTChamp_Don_generique< _TYPE_ >::interprete_get_domaine (const Nom & nom) inline
Definition at line 36 of file TRUSTChamp_Don_generique.h.
  {
    mon_domaine = ref_cast(Domaine, Interprete::objet(nom));
    return mon_domaine.valeur();
  }
References TRUSTChamp_Don_generique< _TYPE_ >::mon_domaine, Interprete::objet(), ref_cast, and Ref_Domaine::valeur().
mettre_a_jour()
template<Champ_Don_Type _TYPE_> void TRUSTChamp_Don_generique< _TYPE_ >::mettre_a_jour (double temps) override virtual
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
Reimplemented from Champ_Don_base.
Definition at line 29 of file TRUSTChamp_Don_generique.tpp.
{
  static constexpr bool IS_TXYZ = (_TYPE_ == Champ_Don_Type::TXYZ);
  if (!IS_TXYZ) /* XYZ ou LU */
    Champ_Don_base::mettre_a_jour(t);
  else
    {
      changer_temps(t);
      int nb_elems = mon_domaine->zone(0).nb_elem();
      DoubleTab& mes_val = valeurs();
      DoubleTab positions(nb_elems, dimension);
      mettre_a_jour_positions(positions);
      eval_fct(positions, temps(), mes_val);
      mes_val.echange_espace_virtuel();
    }
}
References TXYZ.
mettre_a_jour_positions()
template<Champ_Don_Type _TYPE_> void TRUSTChamp_Don_generique< _TYPE_ >::mettre_a_jour_positions (DoubleTab & positions) protected
Definition at line 66 of file TRUSTChamp_Don_generique.tpp.
{
  double x, y, z;
  const int nb_elems = mon_domaine->zone(0).nb_elem();
  const IntTab& les_Polys = mon_domaine->zone(0).les_elems();
  for (int num_elem = 0; num_elem < nb_elems; num_elem++)
    {
      x = y = z = 0;
      int nb_som = 0;
      for (int s = 0, num_som; s < les_Polys.dimension(1); s++)
        if ((num_som = les_Polys(num_elem, s)) >= 0)
          {
            x += mon_domaine->coord(num_som, 0);
            y += mon_domaine->coord(num_som, 1);
            if (dimension > 2) z += mon_domaine->coord(num_som, 2);
            nb_som++;
          }
      positions(num_elem, 0) = x / nb_som;
      positions(num_elem, 1) = y / nb_som;
      if (dimension > 2) positions(num_elem, 2) = z / nb_som;
    }
}
References TRUSTTab< _TYPE_ >::dimension().
printOn()
template<Champ_Don_Type _TYPE_> Sortie & TRUSTChamp_Don_generique< _TYPE_ >::printOn (Sortie & os) const override virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 20 of file TRUSTChamp_Don_generique.tpp.
{
  const DoubleTab& tab = valeurs();
  os << tab.size() << " ";
  for (int i = 0; i < tab.size(); i++) os << tab(0, i);
  return os;
}
References TRUSTVect< _TYPE_ >::size().
Referenced by Champ_Don_Fonc_txyz::printOn(), Champ_Don_Fonc_xyz::printOn(), and Champ_Don_lu::printOn().
valeur_a()
template<Champ_Don_Type _TYPE_> DoubleVect & TRUSTChamp_Don_generique< _TYPE_ >::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const inline override virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns
reference a "valeurs"
Reimplemented from Champ_base.
Definition at line 59 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_a_<_TYPE_>(position, vals);
  }
valeur_a_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_ (const DoubleVect & position, DoubleVect & valeurs) const private
Renvoie la valeur du champ au point specifie par ses coordonnees.
Parametre: DoubleVect& x
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& val
Signification: la valeur du champ au point specifie.
< DoubleVect val doesn't have the correct size
Definition at line 96 of file TRUSTChamp_Don_generique.tpp.
{
  static constexpr bool IS_XYZ = (_TYPE_ == Champ_Don_Type::XYZ);
  if (val.size() != nb_compo_) erreur_champ_(__func__); //!< DoubleVect val doesn't have the correct size
  IS_XYZ ? eval_fct(x,val) : eval_fct(x,temps(),val);
  return val;
}
valeur_a_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_ (const DoubleVect & position, DoubleVect & valeurs) const private
Definition at line 107 of file TRUSTChamp_Don_generique.tpp.
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect le_poly(1);
  la_zone.chercher_elements(x,le_poly);
  return valeur_a_elem(x,val,le_poly(0));
}
valeur_a_compo()
template<Champ_Don_Type _TYPE_> double TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_compo (const DoubleVect & pos, int compo) const override virtual
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
Returns
double
< appel simple si TXYZ ou LU !
< asking ncomp > nb_compo_ ?????
Reimplemented from Champ_base.
Definition at line 48 of file TRUSTChamp_Don_generique.tpp.
{
  static constexpr bool IS_XYZ = (_TYPE_ == Champ_Don_Type::XYZ);
  if (!IS_XYZ) return Champ_Don_base::valeur_a_compo(x, ncomp); //!< appel simple si TXYZ ou LU !
  if (ncomp > nb_compo_) erreur_champ_(__func__); //!< asking ncomp > nb_compo_ ?????
  DoubleTab positions(1, dimension);
  DoubleTab val_fct(1);
  positions(0, 0) = x(0);
  positions(0, 1) = x(1);
  if (dimension > 2) positions(0, 2) = x(2);
  eval_fct(positions, val_fct, ncomp);
  return val_fct(0);
}
References erreur_champ_(), Champ_base::valeur_a_compo(), and XYZ.
valeur_a_elem()
template<Champ_Don_Type _TYPE_> DoubleVect & TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 64 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_a_elem_<_TYPE_>(position, vals, le_poly);
  }
valeur_a_elem_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_ (const DoubleVect & position, DoubleVect & valeurs, int le_poly) const private
Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& val
Signification: la valeur du champ au point specifie
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul.
Definition at line 126 of file TRUSTChamp_Don_generique.tpp.
{
  return valeur_a(x,val);
}
valeur_a_elem_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_ (const DoubleVect & position, DoubleVect & valeurs, int le_poly) const private
< DoubleVect val doesn't have the correct size
Definition at line 133 of file TRUSTChamp_Don_generique.tpp.
{
  if (val.size() != nb_compo_) erreur_champ_(__func__); //!< DoubleVect val doesn't have the correct size
  const DoubleTab& ch = valeurs();
  for (int k = 0; k < nb_compo_; k++) val(k) = ch(le_poly, k);
  return val;
}
References erreur_champ_(), and TRUSTVect< _TYPE_ >::size().
valeur_a_elem_compo()
template<Champ_Don_Type _TYPE_> double TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 69 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_a_elem_compo_<_TYPE_>(position, le_poly, ncomp);
  }
valeur_a_elem_compo_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::TXYZ, double > TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_compo_ (const DoubleVect & position, int le_poly, int ncomp) const private
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
< asking ncomp > nb_compo_ ?????
Definition at line 154 of file TRUSTChamp_Don_generique.tpp.
{
  static constexpr bool IS_XYZ = (_TYPE_ == Champ_Don_Type::XYZ);
  if (ncomp > nb_compo_) erreur_champ_(__func__); //!< asking ncomp > nb_compo_ ?????
  return IS_XYZ ? valeur_a_compo(x,ncomp) : valeurs()(le_poly,ncomp) /* LU */;
}
References erreur_champ_(), and XYZ.
valeur_a_elem_compo_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::TXYZ, double > TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_elem_compo_ (const DoubleVect & position, int le_poly, int ncomp) const private
Definition at line 164 of file TRUSTChamp_Don_generique.tpp.
{
  DoubleTab positions(1,dimension);
  DoubleVect val_fct(1);
  positions(0,0) = x(0);
  positions(0,1) = x(1);
  if (dimension>2) positions(0,2) = x(2);
  eval_fct(positions,temps(),val_fct,ncomp);
  double val = val_fct(0);
  return val;
}
valeur_aux()
template<Champ_Don_Type _TYPE_> DoubleTab & TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const inline override virtual
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 74 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_aux_<_TYPE_>(positions, vals);
  }
valeur_aux_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::LU, DoubleTab & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_ (const DoubleTab & positions, DoubleTab & valeurs) const private
Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parametre: DoubleTab& x
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleTab& val
Signification: le tableau des valeurs du champ aux points specifies.
< DoubleTab val has more than 2 entries !
Definition at line 185 of file TRUSTChamp_Don_generique.tpp.
{
  static constexpr bool IS_XYZ = (_TYPE_ == Champ_Don_Type::XYZ);
  if (val.nb_dim() == 1) assert(nb_compo_ == 1);
  else if (val.nb_dim() == 2) assert(val.dimension(1) == nb_compo_);
  else erreur_champ_(__func__); //!< DoubleTab val has more than 2 entries !
  IS_XYZ ? eval_fct(x,val) : eval_fct(x,temps(),val);
  return val;
}
References TRUSTTab< _TYPE_ >::dimension(), erreur_champ_(), TRUSTTab< _TYPE_ >::nb_dim(), and XYZ.
valeur_aux_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::LU, DoubleTab & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_ (const DoubleTab & positions, DoubleTab & valeurs) const private
< VTABLE pour Champ_som_lu
Definition at line 199 of file TRUSTChamp_Don_generique.tpp.
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(x,les_polys);
  return valeur_aux_elems(x,les_polys,val); //!< VTABLE pour Champ_som_lu
}
References Zone::chercher_elements(), and Zone::nb_elem().
valeur_aux_compo()
template<Champ_Don_Type _TYPE_> DoubleVect & TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const inline override virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns
reference au tableau les_valeurs
Reimplemented from Champ_base.
Definition at line 79 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_aux_compo_<_TYPE_>(positions, vals, ncomp);
  }
valeur_aux_compo_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_compo_ (const DoubleTab & positions, DoubleVect & valeurs, int ncomp) const private
Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees.
Parametre: DoubleVect& x
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleVect& valeurs
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
Definition at line 217 of file TRUSTChamp_Don_generique.tpp.
{
  static constexpr bool IS_XYZ = (_TYPE_ == Champ_Don_Type::XYZ);
  IS_XYZ ? eval_fct(x,val,ncomp) : eval_fct(x,temps(),val,ncomp);
  return val;
}
References XYZ.
valeur_aux_compo_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_compo_ (const DoubleTab & positions, DoubleVect & valeurs, int ncomp) const private
< VTABLE pour Champ_som_lu
Definition at line 226 of file TRUSTChamp_Don_generique.tpp.
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(x,les_polys);
  return valeur_aux_elems_compo(x,les_polys,val,ncomp); //!< VTABLE pour Champ_som_lu
}
References Zone::chercher_elements(), and Zone::nb_elem().
valeur_aux_elems()
template<Champ_Don_Type _TYPE_> DoubleTab & TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 84 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_aux_elems_<_TYPE_>(positions, les_polys, vals);
  }
valeur_aux_elems_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::LU, DoubleTab & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_ (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const private
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Definition at line 247 of file TRUSTChamp_Don_generique.tpp.
{
  return valeur_aux(x, val);
}
valeur_aux_elems_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::LU, DoubleTab & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_ (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const private
< DoubleTab val don't have 2 entries
Definition at line 254 of file TRUSTChamp_Don_generique.tpp.
{
  if (val.nb_dim() > 2) erreur_champ_(__func__); //!< DoubleTab val don't have 2 entries
  int p;
  const DoubleTab& ch = valeurs();
  val = 0.;
  for (int rang_poly = 0; rang_poly < les_polys.size(); rang_poly++)
    if ((p = les_polys(rang_poly)) != -1)
      for (int n = 0; n < nb_compo_; n++) val(rang_poly, n) = ch(p, n);
  return val;
}
References erreur_champ_(), TRUSTTab< _TYPE_ >::nb_dim(), and TRUSTVect< _TYPE_ >::size().
valeur_aux_elems_compo()
template<Champ_Don_Type _TYPE_> DoubleVect & TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 89 of file TRUSTChamp_Don_generique.h.
  {
    return valeur_aux_elems_compo_<_TYPE_>(positions,les_polys,vals,ncomp);
  }
valeur_aux_elems_compo_() [1/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T !=Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_compo_ (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const private
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parametre: DoubleTab& x
Signification: le tableau des coordonnees des points de calcul
Parametre: IntVect& les_polys
Signification: le tableau des elements dans lesquels sont situes les points de calcul
Parametre: DoubleVect& val
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
Definition at line 282 of file TRUSTChamp_Don_generique.tpp.
{
  return valeur_aux_compo(x, val, ncomp);
}
valeur_aux_elems_compo_() [2/2]
template<Champ_Don_Type _TYPE_> template<Champ_Don_Type T> enable_if_t< T==Champ_Don_Type::LU, DoubleVect & > TRUSTChamp_Don_generique< _TYPE_ >::valeur_aux_elems_compo_ (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const private
Definition at line 289 of file TRUSTChamp_Don_generique.tpp.
{
  assert(val.size() == les_polys.size());
  const DoubleTab& ch = valeurs();
  for (int rang_poly = 0; rang_poly < les_polys.size(); rang_poly++)
    {
      int le_poly = les_polys(rang_poly);
      if (le_poly == -1) val(rang_poly) = 0;
      else val(rang_poly) = ch(le_poly, ncomp);
    }
  return val;
}
References TRUSTVect< _TYPE_ >::size().
Member Data Documentation
mon_domaine
template<Champ_Don_Type _TYPE_> Ref_Domaine TRUSTChamp_Don_generique< _TYPE_ >::mon_domaine protected
Definition at line 95 of file TRUSTChamp_Don_generique.h.
Referenced by TRUSTChamp_Don_generique< _TYPE_ >::interprete_get_domaine().
The documentation for this class was generated from the following files:
src/Kernel/Framework/TRUSTChamp_Don_generique.h
src/Kernel/Framework/TRUSTChamp_Don_generique.tpp