TRUST: latatoother Class Reference
latatoother Class Reference
#include <LataToMED.h>
Public Member Functions
latatoother ()
~latatoother ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &is) override
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static latatoother & self_cast (Objet_U &)
static const latatoother & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 43 of file LataToMED.h.
Constructor & Destructor Documentation
latatoother()
latatoother::latatoother ()
Definition at line 34 of file LataToMED.cpp.
~latatoother()
latatoother::~latatoother ()
Definition at line 34 of file LataToMED.cpp.
Member Function Documentation
cree_instance()
Objet_U * latatoother::cree_instance () static
Definition at line 34 of file LataToMED.cpp.
duplique()
int latatoother::duplique () const override virtual
Implements Objet_U.
Definition at line 34 of file LataToMED.cpp.
get_info()
const Type_info * latatoother::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 34 of file LataToMED.cpp.
info()
const Type_info * latatoother::info () static
Definition at line 34 of file LataToMED.cpp.
interpreter()
Entree & latatoother::interpreter (Entree & is) override virtual
< CHAMPPOINT";
Reimplemented from Interprete.
Definition at line 184 of file LataToMED.cpp.
{
  Cerr<<"syntax  Latatoother::interpreter format_post_supp [nom_lata||NOM_DU_CAS] [nom_fichier_sortie||NOM_DU_CAS]   "<<finl;
  Nom nom_dom, nom_lata,nom_fic;
  Nom format_post_supp;
  is >>format_post_supp>> nom_lata>>nom_fic ;
  std::set<std::string> formats( { "LML", "LATA", "LATA_V1", "LATA_V2", "MED" });
  Nom tmp = format_post_supp;
  if(formats.count(tmp.majuscule().getString())==0)
    {
      Cerr << "Error, format " << format_post_supp << " is not supported!" << finl;
      Process::exit();
    }
// Creation d'un sous-groupe contenant uniquement le processeur maitre
  ArrOfInt liste_pe(1);
  DERIV(Comm_Group) group;
// on se met en non axi le temps de la conversion
  int axi_sa=axi;
  axi=0;
  PE_Groups::create_group(liste_pe, group);
  if (PE_Groups::enter_group(group.valeur()))
    {
      if (nom_lata=="NOM_DU_CAS")
        nom_lata=nom_du_cas()+".lata";
      if (nom_fic=="NOM_DU_CAS")
        nom_fic=nom_du_cas();
      Nom filename(nom_lata);
      LataOptions opt;
      LataDB  lata_db;
      LataFilter  filter;
      set_Journal_level(0);
      LataOptions::extract_path_basename(filename, opt.path_prefix, opt.basename);
      opt.dual_mesh = true;
      opt.faces_mesh = false;
// on ne veut jamais creer le domaine IJK
      opt.regularize = 0;
      opt.regularize_tolerance = 1e-7;
      read_any_format_options(filename, opt);
// Read the source file to the lata database
      read_any_format(filename, opt.path_prefix, lata_db);
      filter.initialize(opt, lata_db);
// On met dual_mesh a "false" si on lit un domaine de polyedres PolyMAC (pas encore supporte)
// et on-reouvre la database:
      Noms geom_names = filter.get_exportable_geometry_names();
      int elt_type = filter.get_geometry(Domain_Id(geom_names[0], 1, -1)).elt_type_;
      Cerr << elt_type << finl;
      if (elt_type==Domain::polyedre || elt_type==Domain::polygone)
        {
          opt.dual_mesh = false;
          filter.initialize(opt, lata_db);
        }
      Nom nom_pdb(nom_fic);
      Nom format_post_(format_post_supp);
      if (format_post_=="lata")
        format_post_+="_V1";
// copie de Postraiter_domaine
      Nom type("Format_Post_");
      type+=format_post_;
      Format_Post  post_typer;
      post_typer.typer_direct(type);
      Format_Post_base& post=ref_cast(Format_Post_base,post_typer.valeur());
      Nom nom_2(nom_pdb);
      Nom format_post_bis(format_post_);
      if (format_post_bis.debute_par("lata"))
        format_post_bis="lata";
      Nom suffix(".");
      suffix+=format_post_bis;
      nom_2.prefix(suffix);
// int est_le_premie_post=0;
      int format_binaire_=0;
      if (format_post_bis!="lata")
        post.initialize_by_default(nom_2);
      else
        post.initialize(nom_2,format_binaire_,"SIMPLE");
// ecriture des domaines
      {
        Noms geoms = filter.get_exportable_geometry_names();
        for (int i = 0; i < geoms.size(); i++)
          {
            Domain_Id id(geoms[i], 1, -1);
            const Domain& dom = filter.get_geometry(id);
            Domaine dom_trio;
            dom_trio.nommer(geoms[i]);
            convert_domain_to_Domaine(dom,dom_trio);
            int est_le_premier_post=(i==0);
            post.ecrire_entete(0.,0,est_le_premier_post);
            int reprise = 0;
            double t_init = 0.;
            post.preparer_post(dom_trio.le_nom(),est_le_premier_post,reprise,t_init);
            post.ecrire_domaine(dom_trio, est_le_premier_post);
// meddrive.ecrire_domaine(nom_fic,dom_trio,dom_trio.le_nom(),mode);
            filter.release_geometry(dom);
          }
      }
// les champs
      const char *suffix_vector_names[] = { "X", "Y", "Z" };
      for (int t = 1; t < lata_db.nb_timesteps(); t++)
        {
          int timestate=t;
// if (filter.get_nb_timesteps() > 1)      timestate++;
          Noms geoms = filter.get_exportable_geometry_names();
          double time=filter.get_timestep(t);
          post.ecrire_temps(time);
          for (int i = 0; i < geoms.size(); i++)
            {
              Domain_Id id(geoms[i], timestate, -1);
              const Domain& dom = filter.get_geometry(id);
              Domaine dom_trio;
              dom_trio.nommer(geoms[i]);
              convert_domain_to_Domaine(dom,dom_trio);
              Field_UNames fields = filter.get_exportable_field_unames(geoms[i]);
              for (int j = 0; j < fields.size(); j++)
                {
// const Nom& nom= fields[j].get_field_name();
// if ((nom!=Motcle("ELEM_FACES"))&& (nom!=Motcle("FACES"))&&  (nom!=Motcle("ELEMENTS")))
                  {
                    int est_le_premie_post=(i==0);
                    post.init_ecriture(time,-1.,est_le_premie_post,dom_trio);
                    Field_Id fieldid(fields[j],timestate,-1);
                    DoubleTab values;
                    try
                      {
                        const FieldFloat& field = filter.get_float_field(fieldid);
{
                          const FloatTab& values_lata = field.data_;
                          int dim1=values_lata.dimension(0);
                          int dim2=values_lata.dimension(1);
                          values.resize(dim1,dim2);
                          for (int i1=0; i1<dim1; i1++)
                            for (int i2=0; i2<dim2; i2++)
                              values(i1,i2)=values_lata(i1,i2);
                        }
                        Nom nom_type;
                        if (field.localisation_==LataField_base::ELEM)
                          nom_type="ELEM";//"CHAMPMAILLE";
                        else if (field.localisation_==LataField_base::SOM)
                          nom_type="SOM";//!< CHAMPPOINT";
                        else
{
                            Cerr<<nom_type<<" not coded ...... "<<finl;
                            Cerr<<__FILE__<<":"<<(int)__LINE__<<finl;
                            exit();
                          }
                        Nom type_elem=dom.lata_element_name(dom.elt_type_);
                        Noms unites(values.dimension(1));
                        Noms noms_post(values.dimension(1));
                        Cerr<<"Extraction "<< time<<" "<< geoms[i]<<" "<< fields[j].get_field_name()<<finl;
                        Nom nom_post,ajout;
                        nom_post=fields[j].get_field_name();
// pour eviter qu'en med on est le champ aux faces et sur le dual avec le meme nom
                        if (dom_trio.le_nom().finit_par("_faces")) nom_post+="_Centre";
                        ajout="_";
                        ajout+=nom_type;
                        ajout+="_";
                        ajout+=geoms[i];
                        for (int ii=0; ii<values.dimension(1); ii++)
{
                            noms_post[ii]=nom_post;
                            if (values.dimension(1)==dom_trio.les_sommets().dimension(1))
                              noms_post[ii]+=suffix_vector_names[ii];
                            else
                              noms_post[ii]+=Nom(ii);
                            noms_post[ii]+=ajout;
                          }
                        nom_post+=ajout;
// exit();
// meddrive.ecrire_champ(type,nom_fic,geoms[i],fields[j].get_field_name(),values,unites,type_elem   ,time,0);
                        post.ecrire_champ(dom_trio,unites,noms_post,-1,time,time,nom_post,geoms[i],nom_type,"iii",values);
                        filter.release_field(field);
                      }
                    catch(...)
                      {
                        Cerr<<fieldid.uname_.get_field_name()<<" is not a FloatField !!!"<<finl;
                      }
                  }
                }
              filter.release_geometry(dom);
            }
        }
      int fin=1;
      post.finir(fin);
// delete [] les_domaines;
// delete [] list_champ;
      PE_Groups::exit_group();
    }
  barrier();
// on remet eventuellement axi
  axi=axi_sa;
  return is;
}
References Objet_U::axi, Process::barrier(), Nom::basename(), Cerr, convert_domain_to_Domaine(), PE_Groups::create_group(), ArrOfFloat::data_, Nom::debute_par(), DERIV, FloatTab::dimension(), TRUSTTab< _TYPE_ >::dimension(), Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_temps(), PE_Groups::enter_group(), Process::exit(), PE_Groups::exit_group(), Format_Post_base::finir(), Nom::finit_par(), finl, Format_Post_base::init_ecriture(), Format_Post_base::initialize(), Format_Post_base::initialize_by_default(), Domaine::le_nom(), Domaine::les_sommets(), Objet_U::nom_du_cas(), Domaine::nommer(), Nom::prefix(), Format_Post_base::preparer_post(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), type_elem(), Format_Post::typer_direct(), and Deriv_Format_Post_base::valeur().
Referenced by LataToMED::interpreter().
printOn()
Sortie & latatoother::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 409 of file LataToMED.cpp.
{
  Cerr<<__FILE__<<(int)__LINE__<<" not coded"<<finl;
  Process::exit();
  return is;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & latatoother::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 403 of file LataToMED.cpp.
{
  Cerr<<__FILE__<<(int)__LINE__<<" not coded"<<finl;
  Process::exit();
  return is;
}
References Cerr, Process::exit(), and finl.
self_cast() [1/2]
const latatoother & latatoother::self_cast (const Objet_U & r) static
Definition at line 34 of file LataToMED.cpp.
self_cast() [2/2]
latatoother & latatoother::self_cast (Objet_U & r) static
Definition at line 34 of file LataToMED.cpp.
taille_memoire()
unsigned latatoother::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 34 of file LataToMED.cpp.
Member Data Documentation
info_obj
const Type_info latatoother::info_obj static
Definition at line 45 of file LataToMED.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/LataToMED.h
src/Kernel/MEDimpl/LataToMED.cpp