TRUST: Octree_Zone Class Reference
Octree_Zone Class Reference
: Un octree permettant de retrouver l'element d'une zone contenant
point particulier.
#include <Octree_Zone.h>
Public Member Functions
void reset ()
void build (const Zone &zone, const double epsilon)
int rang_elem (double x, double y, double z) const
void rang_elements (double x, double y, double z, ArrOfInt &elements) const
const Octree_Double & octree_double () const
Protected Member Functions
int find_elements (double x, double y, double z, ArrOfInt *elements) const
si elements est non nul, remplit le tableau avec la liste des
elements contenant le point x,y,z et renvoie -1, sinon renvoie l'indice du
premier element trouve contenant le point x,y,z ou -1 si aucun element.
Protected Attributes
Ref_Zone ref_zone_
Octree_Double octree_double_
ArrOfDouble pos_
Detailed Description
: Un octree permettant de retrouver l'element d'une zone contenant
point particulier.
Definition at line 21 of file Octree_Zone.h.
Member Function Documentation
build()
void Octree_Zone::build (const Zone & zone, const double epsilon)
Definition at line 25 of file Octree_Zone.cpp.
{
  ref_zone_ = zone;
  octree_double_.build_elements(zone.domaine().les_sommets(),
                                zone.les_elems(),
                                epsilon,
                                1);
  pos_.resize_array(zone.domaine().les_sommets().dimension(1));
}
References Octree_Double::build_elements(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Zone::les_elems(), Domaine::les_sommets(), octree_double_, pos_, ref_zone_, and TRUSTArray< _TYPE_ >::resize_array().
find_elements()
int Octree_Zone::find_elements (double x, double y, double z, ArrOfInt * elements) const protected
si elements est non nul, remplit le tableau avec la liste des
elements contenant le point x,y,z et renvoie -1, sinon renvoie l'indice du
premier element trouve contenant le point x,y,z ou -1 si aucun element.
Definition at line 48 of file Octree_Zone.cpp.
{
  if (elements)
    elements->resize_array(0);
  const ArrOfInt& floor_elements = octree_double_.floor_elements();
  const Elem_geom& elemgeom = ref_zone_.valeur().type_elem();
  int index;
  const int nb_elem = octree_double_.search_elements(x, y, z, index);
  pos_[0] = x;
  const int dim = pos_.size_array();
  if (dim>=2) pos_[1] = y;
  if (dim>2) pos_[2] = z;
  for (int i_elem = 0; i_elem < nb_elem; i_elem++)
    {
      const int test_elem = floor_elements[index + i_elem];
// tester l'intersection
      if (elemgeom.contient(pos_, test_elem))
        {
          if (elements)
            elements->append_array(test_elem);
          else
            return test_elem;
        }
    }
  return -1;
}
References TRUSTArray< _TYPE_ >::append_array(), Elem_geom::contient(), Octree_Double::floor_elements(), octree_double_, pos_, ref_zone_, TRUSTArray< _TYPE_ >::resize_array(), Octree_Double::search_elements(), TRUSTArray< _TYPE_ >::size_array(), Zone::type_elem(), and Ref_Zone::valeur().
Referenced by rang_elem(), and rang_elements().
octree_double()
const Octree_Double & Octree_Zone::octree_double () const inline
Definition at line 28 of file Octree_Zone.h.
  {
    return octree_double_;
  };
References octree_double_.
rang_elem()
int Octree_Zone::rang_elem (double x, double y, double z) const
Definition at line 35 of file Octree_Zone.cpp.
{
  return find_elements(x, y, z, 0 /* pointeur nul */);
}
References find_elements().
rang_elements()
void Octree_Zone::rang_elements (double x, double y, double z, ArrOfInt & elements) const
Definition at line 40 of file Octree_Zone.cpp.
{
  find_elements(x, y, z, &elements);
}
References find_elements().
reset()
void Octree_Zone::reset ()
Definition at line 18 of file Octree_Zone.cpp.
{
  ref_zone_.reset();
  octree_double_.reset();
  pos_.reset();
}
References octree_double_, pos_, ref_zone_, Octree_Double::reset(), TRUSTArray< _TYPE_ >::reset(), and Ref_::reset().
Member Data Documentation
octree_double_
Octree_Double Octree_Zone::octree_double_ protected
Definition at line 35 of file Octree_Zone.h.
Referenced by build(), find_elements(), octree_double(), and reset().
pos_
ArrOfDouble Octree_Zone::pos_ mutable protected
Definition at line 36 of file Octree_Zone.h.
Referenced by build(), find_elements(), and reset().
ref_zone_
Ref_Zone Octree_Zone::ref_zone_ protected
Definition at line 34 of file Octree_Zone.h.
Referenced by build(), find_elements(), and reset().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Octree_Zone.h
src/Kernel/Geometrie/Octree_Zone.cpp