TRUST: Discret_Thermique Class Reference
Discret_Thermique Class Reference
Class Discret_Thermique
Cette classe est la classe de base representant une discretisation
spatiale appliquee aux problemes thermiques.
Les methodes virtuelles pures sont a implementer dans les classes
derivees pour typer et discretiser les champs portes par les
equations liees a la discretisation.
#include <Discret_Thermique.h>
Public Member Functions
Discret_Thermique ()
~Discret_Thermique ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void flux_neutronique (const Schema_Temps_base &sch, Zone_dis &z, Champ_Inc &ch, int nb_comp=1) const
void Fluctu_Temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void Flux_Chaleur_Turb (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Discret_Thermique & self_cast (Objet_U &)
static const Discret_Thermique & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Detailed Description
Class Discret_Thermique
Cette classe est la classe de base representant une discretisation
spatiale appliquee aux problemes thermiques.
Les methodes virtuelles pures sont a implementer dans les classes
derivees pour typer et discretiser les champs portes par les
equations liees a la discretisation.
Definition at line 50 of file Discret_Thermique.h.
Constructor & Destructor Documentation
Discret_Thermique::Discret_Thermique ()
Definition at line 32 of file Discret_Thermique.cpp.
Discret_Thermique::~Discret_Thermique ()
Definition at line 32 of file Discret_Thermique.cpp.
Member Function Documentation
virtual int Discret_Thermique::duplique () const [pure virtual]
Implements Discretisation_base.
Implemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
void Discret_Thermique::Fluctu_Temperature (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch) const
Definition at line 90 of file Discret_Thermique.cpp.
References Cerr, Discretisation_base::discretiser_champ(), finl, multi_scalaire, Schema_Temps_base::nb_valeurs_temporelles(), Field_base::nommer(), Schema_Temps_base::temps_courant(), Deriv_Champ_Inc_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "Discretisation des fluctuations en temperature" << finl;
  Noms noms(2);
  Noms unit(2);
  noms[0]="variance_temperature";
  noms[1]="taux_dissipation_temperature";
  unit[0]="K2";
  unit[1]="m2s-3";
  discretiser_champ("temperature",z.valeur(),multi_scalaire,noms,unit,2,sch.nb_valeurs_temporelles(),sch.temps_courant(),ch);
  ch.valeur().nommer("Fluctu_Temperature");
}
void Discret_Thermique::Flux_Chaleur_Turb (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch) const
Definition at line 104 of file Discret_Thermique.cpp.
References Cerr, Objet_U::dimension, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::nb_valeurs_temporelles(), Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "Discretisation du flux de chaleur turbulente" << finl;
  discretiser_champ("vitesse",z.valeur(),"Flux_Chaleur_Turbulente","truc1",dimension,sch.nb_valeurs_temporelles(),
                    sch.temps_courant(),ch);
}
void Discret_Thermique::flux_neutronique (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch, int nb_comp = 1) const
Definition at line 114 of file Discret_Thermique.cpp.
References Cerr, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::nb_valeurs_temporelles(), Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << "Discretisation du flux neutronique" << finl;
  discretiser_champ("temperature",z.valeur(),"flux_neutronique","m-2.s-1",nb_comp,sch.nb_valeurs_temporelles(),sch.temps_courant(),ch);
}
const Type_info * Discret_Thermique::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 32 of file Discret_Thermique.cpp.
const Type_info * Discret_Thermique::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 32 of file Discret_Thermique.cpp.
Sortie & Discret_Thermique::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 49 of file Discret_Thermique.cpp.
{
  return s;
}
Entree & Discret_Thermique::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 69 of file Discret_Thermique.cpp.
{
  return s ;
}
Discret_Thermique & Discret_Thermique::self_cast (Objet_U & r) [static]
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 32 of file Discret_Thermique.cpp.
const Discret_Thermique & Discret_Thermique::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 32 of file Discret_Thermique.cpp.
void Discret_Thermique::temperature (const Schema_Temps_base & sch, Zone_dis & z, Champ_Inc & ch, int nb_comp = 1) const
Definition at line 74 of file Discret_Thermique.cpp.
References Cerr, Discretisation_base::discretiser_champ(), finl, Schema_Temps_base::nb_valeurs_temporelles(), Schema_Temps_base::temps_courant(), and Deriv_Zone_dis_base::valeur().
Referenced by Conduction::discretiser(), Energie_Multiphase::discretiser(), Convection_Diffusion_Temperature::discretiser(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser().
{
  Cerr << "Discretisation de la temperature" << finl;
  discretiser_champ("temperature",z.valeur(),"temperature","K",nb_comp,sch.nb_valeurs_temporelles(),sch.temps_courant(),ch);
}
Member Data Documentation
const Type_info Discret_Thermique::info_obj [static]
Reimplemented from Discretisation_base.
Reimplemented in CoviMAC_discretisation, EF_axi_discretisation, EF_discretisation, VEFPreP1B, PolyMAC_discretisation, Discret_Thyd, VDF_discretisation, VEF_1D, and VEF_discretisation.
Definition at line 52 of file Discret_Thermique.h.
The documentation for this class was generated from the following files:
src/ThSol/Discret_Thermique.h
src/ThSol/Discret_Thermique.cpp