TRUST: Champ_implementation_P0 Class Reference
Champ_implementation_P0 Class Reference abstract
: class Champ_implementation_P0
Decrire ici la classe Champ_implementation_P0
#include <Champ_implementation_P0.h>
Public Member Functions
~Champ_implementation_P0 () override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_P0 (Sortie &, int) const
Public Member Functions inherited from Champ_implementation_base
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Protected Member Functions
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const override
int affecter_ (const Champ_base &)
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation_base
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Detailed Description
: class Champ_implementation_P0
Decrire ici la classe Champ_implementation_P0
Definition at line 30 of file Champ_implementation_P0.h.
Constructor & Destructor Documentation
~Champ_implementation_P0()
Champ_implementation_P0::~Champ_implementation_P0 () inline override
Definition at line 38 of file Champ_implementation_P0.h.
{ };
Member Function Documentation
affecter_()
int Champ_implementation_P0::affecter_ (const Champ_base & ch) protected
Definition at line 237 of file Champ_implementation_P0.cpp.
{
// if (le_champ().a_une_zone_dis_base() && ch.a_une_zone_dis_base() && le_champ().zone_dis_base()==ch.zone_dis_base())
// Plus general en comparant la zone:
// Ajout de Champ_Uniforme_Morceaux/Champ_Fonc_Morceaux/Champ_Don_Fonc_txyz qui sont aux elements
  if (sub_type(Champ_Uniforme_Morceaux, ch) || sub_type(Champ_Fonc_Morceaux, ch) || sub_type(Champ_Don_Fonc_txyz, ch) ||
      (le_champ().a_une_zone_dis_base() && ch.a_une_zone_dis_base() && le_champ().zone_dis_base().zone()==ch.zone_dis_base().zone()))
    {
// Meme support donc on utilise une methode plus rapide pour affecter_
// que la methode generale dans Champ_Fonc_base::affecter_ ou Champ_Inc_base::affecter_
      DoubleTab noeuds;
      IntVect polys;
      remplir_coord_noeuds_et_polys(noeuds, polys);
      ch.valeur_aux_elems(noeuds, polys, le_champ().valeurs());
      return 1;
    }
  else
    {
      if ((le_champ().zone_dis_base().zone().nb_elem()>10000) && (!sub_type(Champ_Uniforme, ch)))
        Cerr << "Warning (if called each time step): computing field " << le_champ().le_nom() << " on domain " << le_champ().zone_dis_base().zone().domaine().le_nom() << " is not optimized... " << finl;
      return 0;
    }
}
References Champ_base::a_une_zone_dis_base(), Cerr, Zone::domaine(), finl, le_champ(), Field_base::le_nom(), Domaine::le_nom(), remplir_coord_noeuds_et_polys(), sub_type, Champ_base::valeur_aux_elems(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by Champ_Fonc_P0_base::affecter_(), and Champ_Inc_P0_base::affecter_().
imprime_P0()
int Champ_implementation_P0::imprime_P0 (Sortie & os, int ncomp) const
Definition at line 213 of file Champ_implementation_P0.cpp.
{
  const Champ_base& cha=le_champ();
  const Zone& la_zone=get_zone_geom();
  int nb_elem_tot = la_zone.nb_elem_tot();
  const DoubleTab& val = cha.valeurs();
  int elem;
// On recalcule les centres de gravite :
  DoubleTab pos_centre;
  la_zone.calculer_centres_gravite(pos_centre);
  os << nb_elem_tot << finl;
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      if (Objet_U::dimension==3)
        os << pos_centre(elem,0) << " " << pos_centre(elem,1) << " " << pos_centre(elem,2) << " " ;
      if (Objet_U::dimension==2)
        os << pos_centre(elem,0) << " " << pos_centre(elem,1) << " " ;
      os << val(elem,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_P0_implementation::imprime_P0 END >>>>>>>>>> " << finl;
  return 1;
}
References Zone::calculer_centres_gravite(), Cout, Objet_U::dimension, finl, Champ_implementation_base::get_zone_geom(), le_champ(), Zone::nb_elem_tot(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_P0_base::imprime(), and Champ_P0_VEF::imprime().
le_champ() [1/2]
const Champ_base & Champ_implementation_P0::le_champ (void) const override protected pure virtual
Implements Champ_implementation_base.
Implemented in Champ_Fonc_P0_base, and Champ_Inc_P0_base.
le_champ() [2/2]
Champ_base & Champ_implementation_P0::le_champ (void) override protected pure virtual
Implements Champ_implementation_base.
Implemented in Champ_Fonc_P0_base, and Champ_Inc_P0_base.
Referenced by affecter_(), imprime_P0(), valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), valeur_aux_elems_compo(), valeur_aux_sommets_compo_impl(), and valeur_aux_sommets_impl().
remplir_coord_noeuds()
DoubleTab & Champ_implementation_P0::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_P0_VDF, and Champ_Inc_P0_base.
Definition at line 117 of file Champ_implementation_P0.cpp.
{
  const Zone& zone = get_zone_geom();
  positions.resize(zone.nb_elem(), Objet_U::dimension);
  zone.calculer_centres_gravite(positions);
  return positions;
}
References Zone::calculer_centres_gravite(), Objet_U::dimension, Champ_implementation_base::get_zone_geom(), Zone::nb_elem(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Champ_Fonc_P0_base::remplir_coord_noeuds(), Champ_Inc_P0_base::remplir_coord_noeuds(), and remplir_coord_noeuds_et_polys().
remplir_coord_noeuds_et_polys()
int Champ_implementation_P0::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P0_base.
Definition at line 125 of file Champ_implementation_P0.cpp.
{
  const Zone& zone = get_zone_geom();
  int nb_elem = zone.nb_elem();
  polys.resize(nb_elem);
  remplir_coord_noeuds(positions);
  for(int i=0; i<nb_elem; i++)
    {
      polys(i)=i;
    }
  return 1;
}
References Champ_implementation_base::get_zone_geom(), Zone::nb_elem(), remplir_coord_noeuds(), and TRUSTVect< _TYPE_ >::resize().
Referenced by affecter_(), Champ_Fonc_P0_base::remplir_coord_noeuds_et_polys(), and Champ_Inc_P0_base::remplir_coord_noeuds_et_polys().
trace()
DoubleTab & Champ_implementation_P0::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const inline protected
Definition at line 57 of file Champ_implementation_P0.h.
{
  if (distant)
    fr.frontiere().trace_elem_distant(y, x);
  else
    {
      fr.frontiere().trace_elem_local(y, x);
      x.echange_espace_virtuel();
    }
  return x;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Frontiere_dis_base::frontiere(), Frontiere::trace_elem_distant(), and Frontiere::trace_elem_local().
Referenced by Champ_Fonc_P0_base::trace(), and Champ_Inc_P0_base::trace().
valeur_a_elem()
DoubleVect & Champ_implementation_P0::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P0_base.
Definition at line 27 of file Champ_implementation_P0.cpp.
{
  const Champ_base& ch_base       = le_champ();
  int            nb_components = ch_base.nb_comp();
  const DoubleTab&  values        = ch_base.valeurs();
  assert(result.size() == nb_components);
  assert(poly>=0);
  assert(poly<values.dimension_tot(0));
  assert(values.nb_dim() == 2);
  assert(values.dimension(1) == nb_components);
  for (int i=0; i<nb_components; i++)
    result(i) = values(poly,i);
  return result;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTVect< _TYPE_ >::size(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_P0_base::valeur_a_elem(), and Champ_Inc_P0_base::valeur_a_elem().
valeur_a_elem_compo()
double Champ_implementation_P0::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P0_base.
Definition at line 45 of file Champ_implementation_P0.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  assert(ncomp>=0);
  assert(ncomp<ch_base.nb_comp());
  assert(poly>=0);
  assert(poly<values.dimension_tot(0));
  double result = 0;
  assert(values.line_size() == ch_base.nb_comp());
  result = values(poly,ncomp);
  return result;
}
References TRUSTTab< _TYPE_ >::dimension_tot(), le_champ(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_P0_base::valeur_a_elem_compo(), and Champ_Inc_P0_base::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_implementation_P0::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const override virtual
< Some post-processed fields can have nb_dim() == 1
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P0_base.
Definition at line 63 of file Champ_implementation_P0.cpp.
{
  const Champ_base& ch_base       = le_champ();
  int            nb_components = ch_base.nb_comp();
  const DoubleTab&  values        = ch_base.valeurs();
  int nb_polys = polys.size();
  if (nb_polys==0)
    return result;
// TODO : FIXME
// For FT the resize should be done in its good position and not here ...
  if (result.nb_dim() == 1 ) result.resize(nb_polys,1);
  assert(values.line_size() == nb_components);
  assert(result.line_size() == nb_components || nb_components == 1);
  for (int i=0; i<nb_polys; i++)
    {
      int cell = polys(i);
      assert(cell<values.dimension_tot(0));
      for (int j = 0; j < result.line_size(); j++)
        if (cell != -1)
          result(i, j) = values.nb_dim() == 1 ? values(cell) : values(cell, (result.line_size() == nb_components) * j); //!< Some post-processed fields can have nb_dim() == 1
    }
  return result;
}
References TRUSTTab< _TYPE_ >::dimension_tot(), le_champ(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_P0_base::valeur_aux_elems(), and Champ_Inc_P0_base::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_implementation_P0::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const override virtual
Implements Champ_implementation_base.
Reimplemented in Champ_Inc_P0_base.
Definition at line 93 of file Champ_implementation_P0.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  int nb_polys = polys.size();
  assert(ncomp>=0);
  assert(ncomp<ch_base.nb_comp());
  assert(result.size() == nb_polys);
  assert(values.line_size() == ch_base.nb_comp());
  for (int i=0; i<nb_polys; i++)
    {
      int cell = polys(i);
      assert(cell<values.dimension_tot(0));
      if (cell!=-1)
        result(i) = values(cell,ncomp);
// result(i) = (cell == -1) ? 0 : values(cell,ncomp);
    }
  return result;
}
References TRUSTTab< _TYPE_ >::dimension_tot(), le_champ(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_P0_base::valeur_aux_elems_compo(), and Champ_Inc_P0_base::valeur_aux_elems_compo().
valeur_aux_sommets_compo_impl()
DoubleVect & Champ_implementation_P0::valeur_aux_sommets_compo_impl (DoubleVect & result, int ncomp) const override protected virtual
Implements Champ_implementation_base.
Definition at line 178 of file Champ_implementation_P0.cpp.
{
  const Champ_base& ch_base       = le_champ();
  const DoubleTab&  values        = ch_base.valeurs();
  const Zone& zone              = get_zone_geom();
  int      nb_cells          = zone.nb_elem_tot();
  int      nb_nodes          = zone.nb_som();
  int      nb_nodes_per_cell = zone.nb_som_elem();
  ArrOfInt count(nb_nodes);
// dvq ajout result=0;
  result=0;
  assert(ncomp>=0);
  assert(ncomp<ch_base.nb_comp());
  assert(result.size() == nb_nodes);
  assert(values.line_size() == ch_base.nb_comp());
  for (int i=0; i<nb_cells; i++)
    for (int j=0; j<nb_nodes_per_cell; j++)
      {
        int node = zone.sommet_elem(i,j);
        if (node < nb_nodes)
          {
            count[node]++;
            result(node) += values(i,ncomp);
          }
      }
  for (int i=0; i<nb_nodes; i++)
    result(i) /= count[i];
  return result;
}
References Champ_implementation_base::get_zone_geom(), le_champ(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), TRUSTVect< _TYPE_ >::size(), Zone::sommet_elem(), and Champ_Proto::valeurs().
valeur_aux_sommets_impl()
DoubleTab & Champ_implementation_P0::valeur_aux_sommets_impl (DoubleTab & result) const override protected virtual
< TODO : FIXME : champ porosite doit etre un DoubleTab
Implements Champ_implementation_base.
Definition at line 138 of file Champ_implementation_P0.cpp.
{
  const Champ_base& ch_base       = le_champ();
  int            nb_components = ch_base.nb_comp();
  const DoubleTab&  values        = ch_base.valeurs();
  const Zone& zone              = get_zone_geom();
  int      nb_cells          = zone.nb_elem_tot();
  int      nb_nodes          = zone.nb_som();
  int      nb_nodes_per_cell = zone.nb_som_elem();
  ArrOfInt count(nb_nodes);
  assert((result.dimension_tot(0) == nb_nodes)||(result.dimension(0) == nb_nodes));
  result = 0;
  count  = 0;
  assert(result.line_size() == nb_components);
  assert(values.line_size() == nb_components);
  for (int i=0; i<nb_cells; i++)
    for (int j=0; j<nb_nodes_per_cell; j++)
      {
        int node = zone.sommet_elem(i,j);
        if (node < nb_nodes)
          {
            count[node]++;
            if ( values.nb_dim() == 1 ) //!< TODO : FIXME : champ porosite doit etre un DoubleTab
              for (int k=0; k<nb_components; k++) result(node,k) += values(i);
            else
              for (int k=0; k<nb_components; k++) result(node,k) += values(i,k);
          }
      }
  for (int i=0; i<nb_nodes; i++)
    for (int j=0; j<nb_components; j++) result(i,j) /= count[i];
  return result;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Champ_implementation_base::get_zone_geom(), le_champ(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), Zone::sommet_elem(), and Champ_Proto::valeurs().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_implementation_P0.h
src/Kernel/Champs_dis/Champ_implementation_P0.cpp