TRUST: LecFicDiffuse Class Reference
LecFicDiffuse Class Reference
Cette classe implemente les operateurs et les methodes virtuelles de la classe EFichier de la facon suivante :
Le fichier a lire est physiquement localise sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
et chaque item lu dans ce fichier est diffuse a tous les autres processus du groupe tous.
Il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
#include <LecFicDiffuse.h>
Public Member Functions
~LecFicDiffuse ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
LecFicDiffuse ()
LecFicDiffuse (const char *name, std::_Ios_Openmode mode=ios::in)
ouverture du fichier name. Cette methode
doit etre appelee sur tous les processeurs. En cas
d'echec : exit()
int ouvrir (const char *name, std::_Ios_Openmode mode=ios::in)
Ouverture du fichier. Cette methode doit etre appelee
par tous les processeurs du groupe.
Valeur de retour: 1 si ok, 0 sinon.
virtual istream & get_istream ()
virtual const istream & get_istream () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static LecFicDiffuse & self_cast (Objet_U &)
static const LecFicDiffuse & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & get_entree_master ()
Protected Attributes
EFichier file_
Detailed Description
Cette classe implemente les operateurs et les methodes virtuelles de la classe EFichier de la facon suivante :
Le fichier a lire est physiquement localise sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
et chaque item lu dans ce fichier est diffuse a tous les autres processus du groupe tous.
Il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Definition at line 41 of file LecFicDiffuse.h.
Constructor & Destructor Documentation
LecFicDiffuse::~LecFicDiffuse ()
Definition at line 26 of file LecFicDiffuse.cpp.
LecFicDiffuse::LecFicDiffuse ()
Definition at line 41 of file LecFicDiffuse.cpp.
References Entree::ERROR_CONTINUE, file_, and Entree::set_error_action().
{
  file_.set_error_action(ERROR_CONTINUE);
}
LecFicDiffuse::LecFicDiffuse (const char * name, std::_Ios_Openmode mode = ios::in)
ouverture du fichier name. Cette methode
doit etre appelee sur tous les processeurs. En cas
d'echec : exit()
Definition at line 49 of file LecFicDiffuse.cpp.
References Cerr, Entree::ERROR_CONTINUE, Process::exit(), file_, finl, Process::je_suis_maitre(), ouvrir(), and Entree::set_error_action().
{
  file_.set_error_action(ERROR_CONTINUE);
  int ok = ouvrir(name, mode);
  if (!ok && Process::je_suis_maitre())
    {
      Cerr << "File " << name << " does not exist (LecFicDiffuse)" << finl;
      Process::exit();
    }
}
Member Function Documentation
Objet_U * LecFicDiffuse::cree_instance () [static]
Reimplemented from EFichier.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
int LecFicDiffuse::duplique () const [virtual]
Implements Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
Entree& LecFicDiffuse::get_entree_master () [inline, protected, virtual]
Implements Lec_Diffuse_base.
Definition at line 53 of file LecFicDiffuse.h.
References file_.
  {
    return file_;
  };
const Type_info * LecFicDiffuse::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
istream & LecFicDiffuse::get_istream () [virtual]
Reimplemented from Entree.
Definition at line 75 of file LecFicDiffuse.cpp.
References Cerr, Process::exit(), file_, finl, Entree::get_istream(), and Process::je_suis_maitre().
{
  if(!Process::je_suis_maitre())
    {
      Cerr << "Error get_istream (LecFicDiffuse)" << finl;
      Process::exit();
    }
  return file_.get_istream();
}
const istream & LecFicDiffuse::get_istream () const [virtual]
Reimplemented from Entree.
Definition at line 86 of file LecFicDiffuse.cpp.
References Cerr, Process::exit(), file_, finl, Entree::get_istream(), and Process::je_suis_maitre().
{
  if(!Process::je_suis_maitre())
    {
      Cerr << "Error get_istream (LecFicDiffuse)" << finl;
      Process::exit();
    }
  return file_.get_istream();
}
const Type_info * LecFicDiffuse::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
int LecFicDiffuse::ouvrir (const char * name, std::_Ios_Openmode mode = ios::in) [virtual]
Ouverture du fichier. Cette methode doit etre appelee
par tous les processeurs du groupe.
Valeur de retour: 1 si ok, 0 sinon.
Reimplemented from Entree_Fichier_base.
Definition at line 64 of file LecFicDiffuse.cpp.
References envoyer_broadcast(), file_, Process::je_suis_maitre(), and Entree_Fichier_base::ouvrir().
Referenced by Champ_front_lu::initialiser(), Raffiner_isotrope_parallele::interpreter(), VerifierCoin::interpreter_(), LecFicDiffuse(), LecFicDiffuseBin::LecFicDiffuseBin(), Scatter::lire_domaine(), Champ_Fonc_reprise::readOn(), Probleme_base::readOn(), Schema_Implicite_Multi_TimeStep_base::reprendre(), and valeur_P1_L2().
{
  int ok = 0;
  if(Process::je_suis_maitre())
    ok = file_.ouvrir(name, mode);
  envoyer_broadcast(ok, 0);
  return ok;
}
Sortie & LecFicDiffuse::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 34 of file LecFicDiffuse.cpp.
{
  throw;
  return s;
}
Entree & LecFicDiffuse::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 28 of file LecFicDiffuse.cpp.
{
  throw;
  return s;
}
const LecFicDiffuse & LecFicDiffuse::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
LecFicDiffuse & LecFicDiffuse::self_cast (Objet_U & r) [static]
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
unsigned LecFicDiffuse::taille_memoire () const [virtual]
Reimplemented from EFichier.
Reimplemented in LecFicDiffuseBin.
Definition at line 26 of file LecFicDiffuse.cpp.
Member Data Documentation
EFichier LecFicDiffuse::file_ [protected]
Definition at line 56 of file LecFicDiffuse.h.
Referenced by get_entree_master(), get_istream(), LecFicDiffuse(), and ouvrir().
const Type_info LecFicDiffuse::info_obj [static]
Reimplemented from Lec_Diffuse_base.
Reimplemented in LecFicDiffuseBin.
Definition at line 43 of file LecFicDiffuse.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/LecFicDiffuse.h
src/Kernel/Utilitaires/LecFicDiffuse.cpp