TRUST: Distanceparoi Class Reference
Distanceparoi Class Reference
#include <Distanceparoi.h>
Public Member Functions
Distanceparoi ()
~Distanceparoi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Distanceparoi & self_cast (Objet_U &)
static const Distanceparoi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 33 of file Distanceparoi.h.
Constructor & Destructor Documentation
Distanceparoi()
Distanceparoi::Distanceparoi ()
Definition at line 24 of file Distanceparoi.cpp.
~Distanceparoi()
Distanceparoi::~Distanceparoi ()
Definition at line 24 of file Distanceparoi.cpp.
Member Function Documentation
cree_instance()
Objet_U * Distanceparoi::cree_instance () static
Definition at line 24 of file Distanceparoi.cpp.
duplique()
int Distanceparoi::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Distanceparoi.cpp.
get_info()
const Type_info * Distanceparoi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Distanceparoi.cpp.
info()
const Type_info * Distanceparoi::info () static
Definition at line 24 of file Distanceparoi.cpp.
interpreter_()
Entree & Distanceparoi::interpreter_ (Entree & is) override virtual
< Tableau dont on aura pas besoin
< centres de gravite des elements
< centres de gravite des faces
< coordonnees des sommets
Implements Interprete_geometrique_base.
Definition at line 36 of file Distanceparoi.cpp.
{
  if(Process::nproc()>1)
    {
      Cerr << " Distance_paroi : the calculation of the distance to the wall is made in sequential mode !! " << finl;
      exit();
    }
  int nb_paroi;
  Motcle format;
  associer_domaine(is);
  is >> nb_paroi;
  Noms nom_paroi(nb_paroi);
  for (int i=0; i< nb_paroi; i++) is >> nom_paroi[i];
  is >> format;
  if( (format != "binaire") && (format != "formatte"))
    {
      Cerr<<"Define the writing's format 'formatte' to write the file Wall_length.xyz"<<finl;
      Cerr<<"both in binary and ascii format, otherwise specify 'binaire'"<<finl;
      exit();
    }
  Domaine& dom=domaine();
  Nom fichier = dom.le_nom();
  fichier += "_Wall_length.xyz";
  Zone& la_zone=dom.zone(0);
  if (Process::je_suis_maitre())
    Cerr << "In Distanceparoi::interpreter : Generate faces" << finl;
  Faces* les_faces_ptr=new(Faces);
  Faces& les_faces= *les_faces_ptr;
// la_zone.creer_faces(les_faces);
  {
// bloc a factoriser avec Zone_VF.cpp :
    Type_Face type_face = la_zone.type_elem().type_face(0);
    les_faces.typer(type_face);
    les_faces.associer_zone(la_zone);
    Static_Int_Lists connectivite_som_elem;
    const int     nb_sommets_tot = la_zone.domaine().nb_som_tot();
    const IntTab&    elements       = la_zone.les_elems();
    construire_connectivite_som_elem(nb_sommets_tot,
                                     elements,
                                     connectivite_som_elem,
                                     1 /* include virtual elements */);
    Faces_builder faces_builder;
    IntTab elem_faces; //!< Tableau dont on aura pas besoin
    faces_builder.creer_faces_reeles(la_zone,
                                     connectivite_som_elem,
                                     les_faces,
                                     elem_faces);
  }
  if (Process::je_suis_maitre())
    Cerr << "In Distanceparoi::interpreter : Generate faces finished" << finl;
  DoubleTab xp;                                     //!< centres de gravite des elements
  DoubleTab xv;                                     //!< centres de gravite des faces
  const DoubleTab& xs=dom.coord_sommets();        //!< coordonnees des sommets
  les_faces.calculer_centres_gravite(xv);
  la_zone.calculer_centres_gravite(xp);
  int nb_elem_tot = xp.dimension(0);
  int dim = xv.dimension(1);
  DoubleVect wall_length(nb_elem_tot);
  wall_length=10e+15;
  DoubleVect dist_min(wall_length);
  ifstream fic1(fichier);
  if (fic1)
    {
      Cerr << " file " << fichier << " already exits : to generate a new one, this file has to be deleted" << finl;
      exit();
    }
  else
    {
      if (Process::je_suis_maitre())
        Cerr << " Generation of the external file named : " << fichier << finl;
      for (int b=0; b<nb_paroi; b++)
        {
          int rang=la_zone.rang_frontiere(nom_paroi[b]);
          const Frontiere& la_frontiere=la_zone.frontiere(rang);
// pas de methode const pour Frontiere::les_sommets_des_faces();
          const IntTab& sommets_face = (ref_cast(Frontiere,la_frontiere)).les_sommets_des_faces();
          int ndeb = la_frontiere.num_premiere_face();
          int nb_faces = la_frontiere.nb_faces();
          int nfin = ndeb + nb_faces;
          int pourcent=0;
          for (int face=ndeb; face<nfin; face++)
            {
              if((((face-ndeb)*100)/nb_faces)>pourcent)
                {
                  pourcent=((face-ndeb)*100)/nb_faces;
                  Cerr <<"\r"<<  pourcent << " % performs of " << nom_paroi[b] ;
                }
              if (dim==2)
                {
                  double compx_0=(xv(face,0));
                  double compy_0=(xv(face,1));
                  int som1=sommets_face(face-ndeb,0);
                  int som2=sommets_face(face-ndeb,1);
                  double nx=  xs(som1,1)-xs(som2,1);
                  double ny=-(xs(som1,0)-xs(som2,0));
                  double norme=sqrt(nx*nx+ny*ny);
                  if (norme==0)
                    {
                      Cerr << "Error in Distanceparoi::interpreter_" << finl;
                      Cerr << "Two nodes " << som1 << " and " << som2 << " seems to have same coordinates:" << finl;
                      Cerr << "xs(" << som1 << ")=" << xs(som1,0) <<" ys(" << som1 << ")= " << xs(som1,1) << finl;
                      Cerr << "xs(" << som2 << ")=" << xs(som2,0) <<" ys(" << som2 << ")= " << xs(som2,1) << finl;
                      Cerr << "Check your mesh and suppress same nodes or contact TRUST support." << finl;
                      exit();
                    }
                  if ( (la_zone.chercher_elements(compx_0+nx, compy_0+ny)) < 0 ) norme*=-1.;
                  nx/=norme;
                  ny/=norme;
                  for (int num_elem=0; num_elem<nb_elem_tot; num_elem++)
                    {
                      double min_loc=dist_min[num_elem];
                      double compx=(compx_0-xp(num_elem,0));
                      if (compx<min_loc)
{
                          double compy=(compy_0-xp(num_elem,1));
                          if (compy<min_loc)
{
                              double w_dist=sqrt(compx*compx+compy*compy);
                              if (w_dist<min_loc)
{
                                  double compx_vect=compx*nx;
                                  double compy_vect=compy*ny;
// double compz_vect=compz*nz;
                                  double w_distproj=sqrt(compx_vect*compx_vect+compy_vect*compy_vect);
                                  wall_length[num_elem]=w_distproj;
                                  dist_min[num_elem]=w_dist;
                                }
                            }
                        }
                    }
                }
              else if (dim==3)
                {
                  double compx_0=(xv(face,0));
                  double compy_0=(xv(face,1));
                  double compz_0=(xv(face,2));
                  int som1=sommets_face(face-ndeb,0);
                  int som2=sommets_face(face-ndeb,1);
                  int som3=sommets_face(face-ndeb,2);
                  double x1= xs(som2,0)-xs(som1,0);
                  double y1= xs(som2,1)-xs(som1,1);
                  double z1= xs(som2,2)-xs(som1,2);
                  double x2= xs(som3,0)-xs(som1,0);
                  double y2= xs(som3,1)-xs(som1,1);
                  double z2= xs(som3,2)-xs(som1,2);
                  double nx= y1*z2 - z1*y2 ;
                  double ny= z1*x2 - x1*z2 ;
                  double nz= x1*y2 - y1*x2 ;
                  double norme=sqrt(nx*nx+ny*ny+nz*nz);
                  if ( (la_zone.chercher_elements(compx_0+nx, compy_0+ny, compz_0+nz)) < 0 ) norme*=-1.;
                  nx/=norme;
                  ny/=norme;
                  nz/=norme;
                  for (int num_elem=0; num_elem<nb_elem_tot; num_elem++)
                    {
                      double min_loc=dist_min[num_elem];
                      double compx=(compx_0-xp(num_elem,0));
                      if (compx<min_loc)
{
                          double compy=(compy_0-xp(num_elem,1));
                          if (compy<min_loc)
{
                              double compz=(compz_0-xp(num_elem,2));
                              if (compz<min_loc)
{
                                  double w_dist=sqrt(compx*compx+compy*compy+compz*compz);
                                  if (w_dist<min_loc)
{
                                      double compx_vect=compx*nx;
                                      double compy_vect=compy*ny;
                                      double compz_vect=compz*nz;
                                      double w_distproj=sqrt(compx_vect*compx_vect+compy_vect*compy_vect+compz_vect*compz_vect);
                                      wall_length[num_elem]=w_distproj;
                                      dist_min[num_elem]=w_dist;
                                    }
                                }
                            }
                        }
                    }
                }
              else
                {
                  Cerr << "ERROR : Dimension 2 or 3 are required to calculate wall distance "<< finl;
                  exit();
                }
            }//!< fin face
          Cerr<<finl;
        }//!< fin nb_paroi
    }//(!fic1)
  Cerr<<" Max distance"<< local_max_vect(dist_min)<<" "<< local_max_vect(wall_length)<<finl;
  SFichierBin fic_sauv(fichier);
  fic_sauv<<nom_paroi<<finl;
  int ntot=(nb_elem_tot*(1+Objet_U::dimension));
// entete pour  pouvoir passer les blocs
// fic_sauv<<1 <<finl<<ntot << finl<< (int)1 <<ntot<<finl<<ntot<<finl;
  fic_sauv << (int)1 <<ntot << (int)1 << ntot << finl << ntot << finl;
// fic_sauv << (int)1 << ntot << (int)1 << ntot << ntot;
  for (int p=0; p<nb_elem_tot; p++)
    {
      fic_sauv<<xp(p,0)<<" "<<xp(p,1);
      if (Objet_U::dimension==3) fic_sauv<<" "<<xp(p,2);
      fic_sauv<<" "<<wall_length(p)<<finl;
    }
  fic_sauv << ntot << (int)0 << (int)0 << (int)0 << (int)1 << (int)0 << finl << ntot << finl << (int)1 << (int)0 << (int)0 <<finl;
  if (format=="formatte")
    {
      fichier = dom.le_nom();
      fichier += "_Wall_length_formatted.xyz";
      SFichier fic_sauv_format(fichier);
      fic_sauv_format<<nom_paroi<<finl;
      int ntot2=(nb_elem_tot*(1+Objet_U::dimension));
// entete pour  pouvoir passer les blocs
      fic_sauv_format << (int)1 <<ntot2 << (int)1 << ntot2 << finl << ntot2 << finl;
      for (int p=0; p<nb_elem_tot; p++)
        {
          fic_sauv_format<<xp(p,0)<<" "<<xp(p,1);
          if (Objet_U::dimension==3) fic_sauv_format<<" "<<xp(p,2);
          fic_sauv_format<<" "<<wall_length(p)<<finl;
        }
      fic_sauv_format << ntot2 << (int)0 << (int)0 << (int)0 << (int)1 << (int)0 << finl << ntot2 << finl << (int)1 << (int)0 << (int)0 <<finl;
    }
  delete les_faces_ptr;
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Faces::associer_zone(), Faces::calculer_centres_gravite(), Zone::calculer_centres_gravite(), Cerr, Zone::chercher_elements(), construire_connectivite_som_elem(), Domaine::coord_sommets(), Faces_builder::creer_faces_reeles(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Interprete_geometrique_base::domaine(), Process::exit(), finl, Zone::frontiere(), Process::je_suis_maitre(), Domaine::le_nom(), Zone::les_elems(), local_max_vect(), Frontiere::nb_faces(), Domaine::nb_som_tot(), norme(), Process::nproc(), Frontiere::num_premiere_face(), Zone::rang_frontiere(), ref_cast, Zone::type_elem(), Elem_geom::type_face(), Faces::typer(), and Domaine::zone().
printOn()
Sortie & Distanceparoi::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Distanceparoi.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Distanceparoi::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 31 of file Distanceparoi.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Distanceparoi & Distanceparoi::self_cast (const Objet_U & r) static
Definition at line 24 of file Distanceparoi.cpp.
self_cast() [2/2]
Distanceparoi & Distanceparoi::self_cast (Objet_U & r) static
Definition at line 24 of file Distanceparoi.cpp.
taille_memoire()
unsigned Distanceparoi::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Distanceparoi.cpp.
Member Data Documentation
info_obj
const Type_info Distanceparoi::info_obj static
Definition at line 35 of file Distanceparoi.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Distanceparoi.h
src/Kernel/Geometrie/Distanceparoi.cpp