TRUST: MD_Vector_tools Class Reference
MD_Vector_tools Class Reference
#include <MD_Vector_tools.h>
Public Types
enum Operations_echange {
ECHANGE_EV , EV_SOMME , EV_SOMME_ECHANGE , EV_MAX ,
EV_MINCOL1
}
Static Public Member Functions
static void creer_tableau_distribue (const MD_Vector &, Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
transforme v en un tableau parallele ayant la structure md.
md doit est non nul !
Les dimension(i>=1) du tableau v (si c'est un IntTab ou DoubleTab) sont conservees,
les dimension(0) et dimension_tot(0) sont modifiees en fonction du nombre d'items
specifies dans le MD_Vector.
La dimension initiale du vecteur doit etre soit 0, soit md.get_nb_items_reels(),
soit md.get_nb_items_tot(). Si besoin, la taille du tableau est modifiee et on
initialise le tableau selon opt.
ATTENTION, echange_espace_virtuel() n'est PAS appele.
Les cases virtuelles ne sont pas initialisees...
static void echange_espace_virtuel (IntVect &, Operations_echange opt=ECHANGE_EV)
static void echange_espace_virtuel (DoubleVect &, Operations_echange opt=ECHANGE_EV)
static int get_sequential_items_flags (const MD_Vector &, ArrOfBit &flags, int line_size=1)
static int get_sequential_items_flags (const MD_Vector &, ArrOfInt &flags, int line_size=1)
static void compute_sequential_items_index (const MD_Vector &, MD_Vector_renumber &, int line_size=1)
static void creer_md_vect_renum (const IntVect &renum, MD_Vector &md_vect)
cree un descripteur pour un sous-ensemble d'un vecteur.
renum fournit la structure et le descripteur du vecteur source (doit avoir line_size==1)
renum doit contenir -1 pour les items du vecteur source a ne pas conserver et une
valeur positive ou nulle pour les items a conserver.
La valeur renum[i] donne l'indice de cet item dans le nouveau tableau.
Attention, si un item du vecteur source est recu d'un autre processeur et doit etre conserve,
ce meme item doit aussi etre conserve sur le processeur qui envoie cet item.
static void creer_md_vect_renum_auto (IntVect &flags_renum, MD_Vector &md_vect)
Idem que creer_md_vect_renum() mais cree une numerotation par defaut.
Le tableau flags_renum doit contenir en entree une valeur POSITIVE OU NULLE pour les
valeurs a conserver et une valeur negative pour les autres.
En sortie, flags_renum contient l'indice de l'item dans le tableau reduit s'il est
conserve, sinon la valeur d'origine non modifiee.
Les items sont places dans l'ordre croissant de leur indice local sur dans le descripteur
d'origine.
static void dump_vector_with_md (const DoubleVect &, Sortie &)
dumps vector v with its parallel descriptor to os.
os must be a file type with one file per process (no shared file).
static void restore_vector_with_md (DoubleVect &, Entree &)
restores a vector saved by dump_vector_with_md.
The code must run with the same number of processors.
"v" will have a newly created copy of the descriptor (not equal to any
other descriptor previously loaded). If "identical" descriptors are needed
for several vectors, you might want to call set_md_vector() afterwards to
attach another descriptor. See save_matrice_conditionnel()
static MD_Vector extend (const MD_Vector &src, extra_item_t &items)
Detailed Description
Definition at line 32 of file MD_Vector_tools.h.
Member Enumeration Documentation
Operations_echange
enum MD_Vector_tools::Operations_echange
Enumerator
ECHANGE_EV
EV_SOMME
EV_SOMME_ECHANGE
EV_MAX
EV_MINCOL1
Definition at line 41 of file MD_Vector_tools.h.
{ ECHANGE_EV, EV_SOMME, EV_SOMME_ECHANGE, EV_MAX, EV_MINCOL1 };
Member Function Documentation
compute_sequential_items_index()
void MD_Vector_tools::compute_sequential_items_index (const MD_Vector & , MD_Vector_renumber & , int line_size = 1) static
Definition at line 255 of file MD_Vector_tools.cpp.
{
  Cerr << "MD_Vector_tools::compute_sequential_items_index" << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
creer_md_vect_renum()
void MD_Vector_tools::creer_md_vect_renum (const IntVect & renum, MD_Vector & md_vect) static
cree un descripteur pour un sous-ensemble d'un vecteur.
renum fournit la structure et le descripteur du vecteur source (doit avoir line_size==1)
renum doit contenir -1 pour les items du vecteur source a ne pas conserver et une
valeur positive ou nulle pour les items a conserver.
La valeur renum[i] donne l'indice de cet item dans le nouveau tableau.
Attention, si un item du vecteur source est recu d'un autre processeur et doit etre conserve,
ce meme item doit aussi etre conserve sur le processeur qui envoie cet item.
Definition at line 554 of file MD_Vector_tools.cpp.
{
  const MD_Vector& src_md = renum.get_md_vector();
  if (!src_md.non_nul())
    {
      Cerr << "Internal error in MD_Vector_tools::creer_md_vect_renum: descripteur nul !" << finl;
      Process::exit();
    }
  if (renum.line_size() != 1)
    {
      Cerr << "Internal error in MD_Vector_tools::creer_md_vect_renum: line_size != 1" << finl;
      Process::exit();
    }
  const MD_Vector_base& src_md_val = src_md.valeur();
  if (sub_type(MD_Vector_std, src_md_val))
    {
      const MD_Vector_std& src = ref_cast(MD_Vector_std, src_md_val);
      MD_Vector_std dest;
      ::creer_md_vect_renum(renum, src, dest);
      md_vect.copy(dest);
    }
  else if (sub_type(MD_Vector_composite, src_md_val))
    {
      const MD_Vector_composite& src1 = ref_cast(MD_Vector_composite, src_md_val);
      const MD_Vector_std& src = src1.global_md_;
      MD_Vector_std dest;
      ::creer_md_vect_renum(renum, src, dest);
      md_vect.copy(dest);
    }
  else
    {
      Cerr << "Error in MD_Vector_tools::creer_md_vect_renum: unknown MD_Vector type "
           << src_md_val.que_suis_je() << finl;
      Process::exit();
    }
}
References Cerr, MD_Vector::copy(), creer_md_vect_renum(), Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), MD_Vector_composite::global_md_, TRUSTVect< _TYPE_ >::line_size(), MD_Vector::non_nul(), Objet_U::que_suis_je(), ref_cast, sub_type, and MD_Vector::valeur().
Referenced by Zone_Cl_VEF::associer(), creer_md_vect_renum(), and creer_md_vect_renum_auto().
creer_md_vect_renum_auto()
void MD_Vector_tools::creer_md_vect_renum_auto (IntVect & flags_renum, MD_Vector & md_vect) static
Idem que creer_md_vect_renum() mais cree une numerotation par defaut.
Le tableau flags_renum doit contenir en entree une valeur POSITIVE OU NULLE pour les
valeurs a conserver et une valeur negative pour les autres.
En sortie, flags_renum contient l'indice de l'item dans le tableau reduit s'il est
conserve, sinon la valeur d'origine non modifiee.
Les items sont places dans l'ordre croissant de leur indice local sur dans le descripteur
d'origine.
Definition at line 599 of file MD_Vector_tools.cpp.
{
  const int n = flags_renum.size_array();
  int count = 0;
  for (int i = 0; i < n; i++)
    {
      int x = flags_renum[i];
      if (x >= 0)
        flags_renum[i] = count++;
    }
  creer_md_vect_renum(flags_renum, md_vect);
}
References creer_md_vect_renum(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Zone_Cl_VEF::associer(), Zone::init_faces_virt_bord(), Solv_GCP::prepare_data(), and Zone_VEF::reordonner().
creer_tableau_distribue()
void MD_Vector_tools::creer_tableau_distribue (const MD_Vector & md, Array_base & v, Array_base::Resize_Options opt = Array_base::COPY_INIT) static
transforme v en un tableau parallele ayant la structure md.
md doit est non nul !
Les dimension(i>=1) du tableau v (si c'est un IntTab ou DoubleTab) sont conservees,
les dimension(0) et dimension_tot(0) sont modifiees en fonction du nombre d'items
specifies dans le MD_Vector.
La dimension initiale du vecteur doit etre soit 0, soit md.get_nb_items_reels(),
soit md.get_nb_items_tot(). Si besoin, la taille du tableau est modifiee et on
initialise le tableau selon opt.
ATTENTION, echange_espace_virtuel() n'est PAS appele.
Les cases virtuelles ne sont pas initialisees...
Definition at line 102 of file MD_Vector_tools.cpp.
{
  if (!md.non_nul())
    {
      Cerr << "Error in MD_Vector_tools::creer_tableau_distribue(): MD_Vector is null" << finl;
      Process::exit();
    }
  IntVect* intV = dynamic_cast<IntVect*>(&v);
  DoubleVect* doubleV = dynamic_cast<DoubleVect*>(&v);
  if (intV) creer_tableau_distribue_<IntVect, IntTab>(md, *intV, opt);
  else if (doubleV) creer_tableau_distribue_<DoubleVect, DoubleTab>(md, *doubleV, opt);
  else
    {
      Cerr << "Internal error in MD_Vector_tools::creer_tableau_distribue(const MD_Vector & md, Array_base & v):\n"
           << " Invalid array type " << v.que_suis_je()
           << "\n Array must be a subtype of IntVect or DoubleVect" << finl;
      Process::exit();
    }
}
References Cerr, Process::exit(), finl, MD_Vector::non_nul(), and Objet_U::que_suis_je().
Referenced by Debog_Pb::add_renum_item(), Zone_Cl_VEF::associer(), Scatter::construire_espace_virtuel_traduction(), Scatter::construire_md_vector(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Scatter::construire_structures_paralleles(), Zone_VF::creer_tableau_aretes(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Zone::creer_tableau_elements(), Frontiere::creer_tableau_faces(), Zone_VF::creer_tableau_faces(), Zone_VF::creer_tableau_faces_bord(), Zone_VEF_PreP1b::creer_tableau_p1bulle(), Domaine::creer_tableau_sommets(), Zone_Poly_base::init_dist_paroi_globale(), Zone::init_faces_virt_bord(), Traduction_Indice_Global_Local::initialiser(), Echange_contact_VDF::initialiser(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Op_Diff_PolyMAC_base::update_aux(), and Debog_Pb::verifier_matrice().
dump_vector_with_md()
void MD_Vector_tools::dump_vector_with_md (const DoubleVect & v, Sortie & os) static
dumps vector v with its parallel descriptor to os.
os must be a file type with one file per process (no shared file).
Definition at line 614 of file MD_Vector_tools.cpp.
{
  const MD_Vector_base& md = v.get_md_vector().valeur();
  os << md.que_suis_je() << finl;
  os << md << finl;
  os << "line_size" << space << v.line_size() << finl;
  os << v.size_array() << finl;
  os.put(v.addr(), v.size_array(), v.line_size());
  os << finl;
}
References TRUSTArray< _TYPE_ >::addr(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), TRUSTVect< _TYPE_ >::line_size(), Sortie::put(), Objet_U::que_suis_je(), TRUSTArray< _TYPE_ >::size_array(), space, and MD_Vector::valeur().
Referenced by SolveurSys_base::save_matrice_secmem_conditionnel().
echange_espace_virtuel() [1/2]
void MD_Vector_tools::echange_espace_virtuel (DoubleVect & v, Operations_echange opt = ECHANGE_EV) static
Definition at line 188 of file MD_Vector_tools.cpp.
{ call_echange_espace_virtuel<double>(v,opt); }
echange_espace_virtuel() [2/2]
void MD_Vector_tools::echange_espace_virtuel (IntVect & v, Operations_echange opt = ECHANGE_EV) static
Definition at line 187 of file MD_Vector_tools.cpp.
{ call_echange_espace_virtuel<int>(v,opt); }
Referenced by Zone_VEF_PreP1b::discretiser_arete(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
extend()
MD_Vector MD_Vector_tools::extend (const MD_Vector & src, extra_item_t & items) static
Definition at line 663 of file MD_Vector_tools.cpp.
{
  if (Process::mp_max(items.size()) == 0) return src; //rien a faire
  /* remplissage de : recep[p] -> liste des items qu'on veut recevoir du processeur p
                      items[{p, i}] -> ou on va placer chaque item dans le MD_Vector elargi */
  int i, j, p, nb_items_tot = src.valeur().get_nb_items_tot(), idx = nb_items_tot;
  const MD_Vector_std *mds = NULL;
  if (sub_type(MD_Vector_std, src.valeur())) mds = &ref_cast(MD_Vector_std, src.valeur());
  else if (sub_type(MD_Vector_composite, src.valeur())) mds = &ref_cast(MD_Vector_composite, src.valeur()).global_md_;
  /* recv[p] : items qu'on veut recevoir du processeur p : taille nrecv[p]. On en profite pour les numeroter dans items */
  ArrsOfInt recv(Process::nproc());
  for (p = 0; p < Process::nproc(); p++) recv[p].set_smart_resize(1);
  std::vector<int> nrecv(Process::nproc());
  for (auto &kv : items) recv[kv.first[0]].append_array(kv.first[1]), kv.second = idx, nrecv[kv.first[0]]++, idx++;
  /* send[p] : items qu'on doit envoyer au processeur p */
  ArrsOfInt send(Process::nproc());
  envoyer_all_to_all(recv, send);
  std::map<int, std::array<std::vector<int>, 3>> map; //map[p] = { items a envoyer a p, items a recevoir de p, blocs a recevoir de p }
  for (i = 0; i < mds->pe_voisins_.size_array(); i++)
    {
      p = mds->pe_voisins_[i];
      for (j = 0; j < mds->items_to_send_.get_list_size(i); j++) map[p][0].push_back(mds->items_to_send_(i, j));
      for (j = 0; j < mds->items_to_recv_.get_list_size(i); j++) map[p][1].push_back(mds->items_to_recv_(i, j));
      for (j = 0; j < mds->blocs_to_recv_.get_list_size(i); j++) map[p][2].push_back(mds->blocs_to_recv_(i, j));
    }
  /* ajout de ce qu'on doit envoyer/recevoir en plus */
  for (p = 0; p < Process::nproc(); p++)
    for (i = 0; i < send[p].size_array(); i++) map[p][0].push_back(send[p][i]);
  for (p = 0, idx = nb_items_tot; p < Process::nproc(); idx += nrecv[p], p++)
    if (nrecv[p]) map[p][2].insert(map[p][2].end(), { idx, idx + nrecv[p] });
  /* reconstruction de tableaux pour MD_Vector_std */
  ArrOfInt pe_voisins(map.size());
  ArrsOfInt items_to_send(map.size()), items_to_recv(map.size()), blocs_to_recv(map.size());
  for (p = 0, i = 0; p < Process::nproc(); nb_items_tot += nrecv[p],  p++)
    if (map.count(p))
      {
        pe_voisins[i] = p;
        items_to_send[i].resize(map[p][0].size()), std::copy(map[p][0].begin(), map[p][0].end(), items_to_send[i].addr());
        items_to_recv[i].resize(map[p][1].size()), std::copy(map[p][1].begin(), map[p][1].end(), items_to_recv[i].addr());
        blocs_to_recv[i].resize(map[p][2].size()), std::copy(map[p][2].begin(), map[p][2].end(), blocs_to_recv[i].addr());
        i++;
      }
  /* c'est parti */
  MD_Vector_std mdd(nb_items_tot, mds->get_nb_items_reels(), pe_voisins, items_to_send, items_to_recv, blocs_to_recv);
  MD_Vector res;
  res.copy(mdd);
  return res;
}
References MD_Vector_std::blocs_to_recv_, MD_Vector::copy(), envoyer_all_to_all(), Static_Int_Lists::get_list_size(), MD_Vector_base2::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), MD_Vector_std::items_to_recv_, MD_Vector_std::items_to_send_, Process::mp_max(), Process::nproc(), MD_Vector_std::pe_voisins_, ref_cast, TRUSTArray< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), sub_type, and MD_Vector::valeur().
get_sequential_items_flags() [1/2]
int MD_Vector_tools::get_sequential_items_flags (const MD_Vector & md, ArrOfBit & flags, int line_size = 1) static
< valeur par defaut la plus courante (0 est le cas particulier), voir setflag(ArrOfBit)
Definition at line 236 of file MD_Vector_tools.cpp.
{
  const MD_Vector_base& mdv = md.valeur();
  const int sz = mdv.get_nb_items_tot() * line_size;
// setbit et clearbit font |= et &=, donc valgrind ne voit pas qu'on initialise tout
// le tableau. On initialise tout explicitement:
  flags.resize_array(sz);
  flags = 1; //!< valeur par defaut la plus courante (0 est le cas particulier), voir setflag(ArrOfBit)
  return get_seq_flags(mdv, flags, 0, line_size);
}
References MD_Vector_base::get_nb_items_tot(), get_seq_flags(), ArrOfBit::resize_array(), and MD_Vector::valeur().
Referenced by SETS::assembler(), Traitement_particulier_NS_THI::calcul_nb_som_dir(), Zone_VEF_PreP1b::construire_ok_arete(), ecriture_special_part2(), lire_special(), and SSOR::prepare_().
get_sequential_items_flags() [2/2]
int MD_Vector_tools::get_sequential_items_flags (const MD_Vector & md, ArrOfInt & flags, int line_size = 1) static
Definition at line 247 of file MD_Vector_tools.cpp.
{
  const MD_Vector_base& mdv = md.valeur();
  const int sz = mdv.get_nb_items_tot() * line_size;
  flags.resize_array(sz, Array_base::NOCOPY_NOINIT);
  return get_seq_flags(mdv, flags, 0, line_size);
}
References MD_Vector_base::get_nb_items_tot(), get_seq_flags(), Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::resize_array(), and MD_Vector::valeur().
restore_vector_with_md()
void MD_Vector_tools::restore_vector_with_md (DoubleVect & v, Entree & is) static
restores a vector saved by dump_vector_with_md.
The code must run with the same number of processors.
"v" will have a newly created copy of the descriptor (not equal to any
other descriptor previously loaded). If "identical" descriptors are needed
for several vectors, you might want to call set_md_vector() afterwards to
attach another descriptor. See save_matrice_conditionnel()
Definition at line 632 of file MD_Vector_tools.cpp.
{
  v.reset();
  DERIV(MD_Vector_base) md_ptr;
  Nom md_type;
  is >> md_type;
  md_ptr.typer(md_type);
  is >> md_ptr.valeur();
// Creation du MD_Vector attache au tableau
  MD_Vector md;
  md.copy(md_ptr.valeur());
  Nom unused;
  int line_size;
  is >> unused >> line_size;
// Astuce pour restaurer le line_size:
  DoubleTab toto;
  toto.resize(md_ptr.valeur().get_nb_items_tot(), line_size, Array_base::NOCOPY_NOINIT);
  int size_tot;
  is >> size_tot;
  is.get(toto.addr(), size_tot);
  toto.set_md_vector(md);
// Attache v a toto et oublie toto... line_size est transfere sur v
  v.reset();
  v.ref(toto);
}
References TRUSTArray< _TYPE_ >::addr(), MD_Vector::copy(), DERIV, Entree::get(), Array_base::NOCOPY_NOINIT, TRUSTVect< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), and TRUSTTab< _TYPE_ >::set_md_vector().
Referenced by Test_solveur::interpreter().
The documentation for this class was generated from the following files:
src/Kernel/Math/MD_Vector_tools.h
src/Kernel/Math/MD_Vector_tools.cpp