TRUST: Read_MED_For_Testing_No_Verify_Option Class Reference
Read_MED_For_Testing_No_Verify_Option Class Reference
#include <Read_MED_For_Testing_No_Verify_Option.h>
Public Member Functions
Read_MED_For_Testing_No_Verify_Option ()
~Read_MED_For_Testing_No_Verify_Option ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
void lire_geom (Nom &nom_fic, Domaine &dom, const Nom &nom_dom, const Nom &nom_dom1, int isvef=0, int isfamilyshort=0)
Public Member Functions inherited from LireMED
~LireMED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
LireMED ()
Entree & interpreter_ (Entree &) override
void lire_geom (Nom &nom_fic, Domaine &dom, const Nom &nom_dom, const Nom &nom_dom1, int isvef=0, int convertAllToPoly=0, int isfamilyshort=0)
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Read_MED_For_Testing_No_Verify_Option & self_cast (Objet_U &)
static const Read_MED_For_Testing_No_Verify_Option & self_cast (const Objet_U &)
Static Public Member Functions inherited from LireMED
static Objet_U * cree_instance ()
static const Type_info * info ()
static LireMED & self_cast (Objet_U &)
static const LireMED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from LireMED
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from LireMED
bool use_medcoupling_
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 38 of file Read_MED_For_Testing_No_Verify_Option.h.
Constructor & Destructor Documentation
Read_MED_For_Testing_No_Verify_Option()
Read_MED_For_Testing_No_Verify_Option::Read_MED_For_Testing_No_Verify_Option ()
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
~Read_MED_For_Testing_No_Verify_Option()
Read_MED_For_Testing_No_Verify_Option::~Read_MED_For_Testing_No_Verify_Option ()
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
Member Function Documentation
cree_instance()
Objet_U * Read_MED_For_Testing_No_Verify_Option::cree_instance () static
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
duplique()
int Read_MED_For_Testing_No_Verify_Option::duplique () const override virtual
Reimplemented from LireMED.
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
get_info()
const Type_info * Read_MED_For_Testing_No_Verify_Option::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from LireMED.
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
info()
const Type_info * Read_MED_For_Testing_No_Verify_Option::info () static
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
interpreter_()
Entree & Read_MED_For_Testing_No_Verify_Option::interpreter_ (Entree & is) override virtual
Reimplemented from LireMED.
Definition at line 31 of file Read_MED_For_Testing_No_Verify_Option.cpp.
{
  LireMED::interpreter_( is );
  return is;
}
References LireMED::interpreter_().
lire_geom()
void Read_MED_For_Testing_No_Verify_Option::lire_geom (Nom & nom_fic, Domaine & dom, const Nom & nom_dom, const Nom & nom_dom1, int isvef = 0, int isfamilyshort = 0)
Definition at line 36 of file Read_MED_For_Testing_No_Verify_Option.cpp.
{
  LireMED::lire_geom( nom_fic, dom, nom_dom, nom_dom_trio, isvef, isfamilyshort );
}
References LireMED::lire_geom().
printOn()
Sortie & Read_MED_For_Testing_No_Verify_Option::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from LireMED.
Definition at line 20 of file Read_MED_For_Testing_No_Verify_Option.cpp.
{
  return LireMED::printOn(os);
}
References LireMED::printOn().
readOn()
Entree & Read_MED_For_Testing_No_Verify_Option::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from LireMED.
Definition at line 25 of file Read_MED_For_Testing_No_Verify_Option.cpp.
{
  return LireMED::readOn(is);
}
References LireMED::readOn().
self_cast() [1/2]
const Read_MED_For_Testing_No_Verify_Option & Read_MED_For_Testing_No_Verify_Option::self_cast (const Objet_U & r) static
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
self_cast() [2/2]
Read_MED_For_Testing_No_Verify_Option & Read_MED_For_Testing_No_Verify_Option::self_cast (Objet_U & r) static
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
taille_memoire()
unsigned Read_MED_For_Testing_No_Verify_Option::taille_memoire () const override virtual
Reimplemented from LireMED.
Definition at line 18 of file Read_MED_For_Testing_No_Verify_Option.cpp.
Member Data Documentation
info_obj
const Type_info Read_MED_For_Testing_No_Verify_Option::info_obj static
Definition at line 40 of file Read_MED_For_Testing_No_Verify_Option.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Read_MED_For_Testing_No_Verify_Option.h
src/Kernel/MEDimpl/Read_MED_For_Testing_No_Verify_Option.cpp