TRUST: Traitement_particulier_NS_canal Class Reference
Traitement_particulier_NS_canal Class Reference abstract
classe Traitement_particulier_NS_canal
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
#include <Traitement_particulier_NS_canal.h>
Public Member Functions
~Traitement_particulier_NS_canal () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Traitement_particulier_NS_canal ()
Entree & lire (Entree &) override
void preparer_calcul_particulier () override
void reprendre_stat () override
void sauver_stat () const override
void post_traitement_particulier () override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Traitement_particulier_NS_canal & self_cast (Objet_U &)
static const Traitement_particulier_NS_canal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void reprendre_stat_canal (DoubleTab &, const Nom &)
void sauver_stat_canal (const DoubleTab &, const Nom &) const
virtual void remplir_Y (DoubleVect &, DoubleVect &, int &) const =0
virtual void remplir_Tab_recap (IntTab &) const
void remplir_reordonne_Y_tot (const DoubleVect &, DoubleVect &) const
virtual void calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab &) const =0
virtual void calculer_moyenne_spatiale_nut (DoubleTab &) const =0
virtual void calculer_moyenne_spatiale_Temp (DoubleTab &) const =0
void calcul_reynolds_tau ()
void ecriture_fichiers_moy_vitesse_rho_mu (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_nut (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_Temp (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_vitesse_rho_mu_old (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_Temp_old (const DoubleTab &, const Nom &, const double, const int) const
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
int Ny
int Nval
int Nphase
DoubleTab val_moy_tot
DoubleTab val_moy_temp
DoubleTab val_moy_phase
DoubleVect Y
DoubleVect Y_tot
DoubleVect compt
DoubleVect compt_tot
IntVect Nb_ech_phase
nombre d'echantillons par phase
IntTab Tab_recap
double w
double freq
int ind_phase
int oui_profil_nu_t
int oui_profil_Temp
int oui_repr
int oui_pulse
double temps_deb
double temps_fin
double debut_phase
double dt_impr_moy_spat
double dt_impr_moy_temp
Nom fich_repr
Ref_Champ_base Temp
DoubleVect uv_moy_temp
DoubleVect wv_moy_temp
DoubleVect uw_moy_temp
DoubleVect u2_moy_temp
DoubleVect v2_moy_temp
DoubleVect w2_moy_temp
DoubleVect nu_t_temp
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_NS_canal
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
Definition at line 36 of file Traitement_particulier_NS_canal.h.
Constructor & Destructor Documentation
~Traitement_particulier_NS_canal()
Traitement_particulier_NS_canal::~Traitement_particulier_NS_canal () override
Definition at line 31 of file Traitement_particulier_NS_canal.cpp.
Traitement_particulier_NS_canal()
Traitement_particulier_NS_canal::Traitement_particulier_NS_canal ()
Definition at line 33 of file Traitement_particulier_NS_canal.cpp.
{
  oui_profil_nu_t = 0;
  oui_profil_Temp = 0;
  oui_repr = 0;
  oui_pulse = 0;
  dt_impr_moy_spat=1e6;
  dt_impr_moy_temp=1e6;
  temps_deb=1e6;
  temps_fin=1e6;
  debut_phase=1e6;
  ind_phase=0;
  Nval=12;
  Nphase=1;
  Nb_ech_phase.resize(1);
  Nb_ech_phase(0)=1;
}
References debut_phase, dt_impr_moy_spat, dt_impr_moy_temp, ind_phase, Nb_ech_phase, Nphase, Nval, oui_profil_nu_t, oui_profil_Temp, oui_pulse, oui_repr, TRUSTVect< _TYPE_ >::resize(), temps_deb, and temps_fin.
Member Function Documentation
a_pour_Champ_Fonc()
int Traitement_particulier_NS_canal::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const inline
Definition at line 48 of file Traitement_particulier_NS_canal.h.
{ return 0 ; }
calcul_reynolds_tau()
void Traitement_particulier_NS_canal::calcul_reynolds_tau () protected
< indice du dernier point hors paroi
< position du premier point
< position du dernier point
< demi-hauteur
Definition at line 696 of file Traitement_particulier_NS_canal.cpp.
{
// Aspects geometriques du maillage
//
// !!!!!  Hypotheses : maillage symetrique suivant la demi-hauteur et s'etendant de Y=0 a Y=H
  Nom nom_discr=mon_equation.valeur().discretisation().que_suis_je();
// indice du premier point hors paroi
  int kmin=(nom_discr=="VEFPreP1B" || nom_discr=="VEF") ? 1 : 0;
  int kmax=Y_tot.size()-1-kmin;                         //!< indice du dernier point hors paroi
  double ymin=Y_tot(kmin);                              //!< position du premier point
  double ymax=Y_tot(kmax);                              //!< position du dernier point
  double hs2=0.5*(ymin+ymax);                           //!< demi-hauteur
// check that the canal is in the good bounds
  if ( ymin < 0. || ymax < 0.)
    {
      Cerr << "Error Traitement_particulier_NS_canal" << finl;
      Cerr << "Invalid mesh: Y must be between 0 and H>0" << finl;
      Cerr << "In addition, the mesh must be symmetric along the half-height." << finl;
      exit() ;
    }
// viscosite dynamique
  double mu_bas  = val_moy_tot(kmin,11,0);
  double mu_haut = val_moy_tot(kmax,11,0);
// masse volumique
  double rho_bas  = val_moy_tot(kmin,10,0);
  double rho_haut = val_moy_tot(kmax,10,0);
// cisaillement a la paroi
  double tauwb, tauwh, tauwm;
// int nbfaces_tot=0;
  int nb_cl_diri=0;
  double tauw_diri_m=0.;
  double retau_diri_m=0.;
  double utau_diri_m=0.;
  int nb_cl_robin=0;
  double tauw_robin_m=0.;
  double retau_robin_m=0.;
  double utau_robin_m=0.;
  const RefObjU& modele_turbulence         = mon_equation.valeur().get_modele(TURBULENCE);
  const Equation_base& eqn                 = ref_cast(Equation_base,mon_equation.valeur()) ;
  const Zone_Cl_dis_base& zone_Cl_dis_base = ref_cast(Zone_Cl_dis_base,eqn.zone_Cl_dis().valeur());
  const Conds_lim& les_cl                  = zone_Cl_dis_base.les_conditions_limites();
  const Zone_VF& zone_VF                   = ref_cast(Zone_VF,eqn.zone_dis().valeur());
  double tps                               = mon_equation->inconnue().temps();
  double nb_pas_dt=mon_equation->schema_temps().nb_pas_dt();
  int reprise = mon_equation.valeur().probleme().reprise_effectuee();
  bool new_file = ( nb_pas_dt == 0 && reprise == 0 );
  IOS_OPEN_MODE mode;
  if (new_file == 0)
    mode = (ios::out | ios::app);
  else
    mode = ios::out;
  int nb_cl=les_cl.size();
  for (int num_cl=0; num_cl<nb_cl; num_cl++)
    {
      const Cond_lim& la_cl = les_cl[num_cl];
      if (la_cl.valeur().que_suis_je() == "Paroi_decalee_Robin")
        {
          nb_cl_robin+=1;
        }
      if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()))
        {
          nb_cl_diri+=1;
        }
    }
  if (modele_turbulence.non_nul() && !ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur()).loi_paroi().valeur().que_suis_je().debute_par("negligeable"))
    {
// PQ : 13/07/05 : prise en compte des lois de paroi pour le calcul de u_tau
// Hypotheses :    1ere condition de Dirichlet = paroi basse
// 2eme condition de Dirichlet = paroi haute
// maillage regulier suivant x
      const Fluide_base& fluide = ref_cast(Fluide_base,mon_equation.valeur().probleme().equation(0).milieu());
      const Turbulence_paroi& loipar           = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur()).loi_paroi();
      DoubleTab tau_tan;
      tau_tan.ref(loipar->Cisaillement_paroi());
// int num_cl_rep=0;
// int nbfaces=0;
      tauwb=0.;
      tauwh=0.;
// dirichlet
      if ( nb_cl_diri != 0 )
        {
          DoubleVect tauw_diri(nb_cl_diri);
          DoubleVect retau_diri(nb_cl_diri);
          DoubleVect utau_diri(nb_cl_diri);
// search of cl diri
// nb cl diri
          double tauw_diri_tmp=0.;
          int numero_bord_diri=0;
          int nbfaces_bord_diri=0;
          double rho = 0.;
          double mu = 0.;
          if ( sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
            {
              rho = fluide.masse_volumique().valeurs()(0,0);
            }
          if ( sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
            {
              mu = fluide.viscosite_dynamique().valeurs()(0,0);
            }
// for each cl, calculation of the mean tauw
// loop on boundaries
          for (int num_cl=0; num_cl<nb_cl; num_cl++)
            {
              tauw_diri_tmp=0.;
              if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                rho = 0.;
              if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                mu = 0.;
              const Cond_lim& la_cl = les_cl[num_cl];
              if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()))
                {
                  const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
                  nbfaces_bord_diri = la_front_dis.nb_faces();
                  int ndeb = la_front_dis.num_premiere_face();
                  int nfin = ndeb + nbfaces_bord_diri;
                  if (Objet_U::dimension == 2 )
                    {
// loop on faces in 2D
                      for (int fac=ndeb; fac<nfin ; fac++)
{
                          tauw_diri_tmp += sqrt(tau_tan(fac,0)*tau_tan(fac,0));
                          int elem = zone_VF.face_voisins(fac,0);
                          if (elem == -1)
                            elem = zone_VF.face_voisins(fac,1);
                          if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                            rho += fluide.masse_volumique().valeurs()[elem];
                          if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                            mu += fluide.viscosite_dynamique().valeurs()[elem];
                        }
                    }
                  else
                    {
// loop on faces on 3D
                      for (int fac=ndeb; fac<nfin ; fac++)
{
                          tauw_diri_tmp += sqrt(tau_tan(fac,0)*tau_tan(fac,0)+tau_tan(fac,2)*tau_tan(fac,2));
                          int elem = zone_VF.face_voisins(fac,0);
                          if (elem == -1)
                            elem = zone_VF.face_voisins(fac,1);
                          if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                            rho += fluide.masse_volumique().valeurs()[elem];
                          if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                            mu += fluide.viscosite_dynamique().valeurs()[elem];
                        }
                    }
                  tauw_diri_tmp=mp_sum(tauw_diri_tmp)/mp_sum(nbfaces_bord_diri);
                  if(!(mon_equation.valeur().probleme().is_dilatable()))
                    tauw_diri_tmp *= rho ;
                  if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                    rho=mp_sum(rho)/mp_sum(nbfaces_bord_diri);
                  if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                    mu=mp_sum(mu)/mp_sum(nbfaces_bord_diri);
                  tauw_diri(numero_bord_diri) = tauw_diri_tmp;
                  utau_diri(numero_bord_diri) = sqrt(tauw_diri_tmp/rho);
                  retau_diri(numero_bord_diri)= rho*utau_diri(numero_bord_diri)*hs2/mu;
                  tauw_diri_m  += tauw_diri(numero_bord_diri);
                  utau_diri_m  += utau_diri(numero_bord_diri);
                  retau_diri_m += retau_diri(numero_bord_diri);
                  numero_bord_diri+=1;
                }
            } //!< loop on boundaries
          tauw_diri_m  =tauw_diri_m/nb_cl_diri;
          retau_diri_m =retau_diri_m/nb_cl_diri;
          utau_diri_m  =utau_diri_m/nb_cl_diri;
// prints
          if (je_suis_maitre())
            {
              SFichier fic7("tauw.dat", mode);
              SFichier fic8("reynolds_tau.dat", mode);
              SFichier fic9("u_tau.dat", mode);
              fic7 << tps << "   " << tauw_diri_m   << "   ";
              fic8 << tps << "   " << retau_diri_m  << "   ";
              fic9 << tps << "   " << utau_diri_m   << "   ";
              for ( int num=0 ; num<nb_cl_diri ; num++)
                {
                  fic7 << tauw_diri(num)   << "   ";
                  fic8 << retau_diri(num)  << "   ";
                  fic9 << utau_diri(num)   << "   ";
                }
              fic7 <<  finl;
              fic8 <<  finl;
              fic9 <<  finl;
              fic7.flush();
              fic8.flush();
              fic9.flush();
              fic7.close();
              fic8.close();
              fic9.close();
            }
        } //!< end dirichlet
// robin
      if ( nb_cl_robin != 0 )
        {
          DoubleVect tauw_robin(nb_cl_robin);
          DoubleVect retau_robin(nb_cl_robin);
          DoubleVect utau_robin(nb_cl_robin);
// search of cl robin
// nb cl robin
          double tauw_robin_tmp=0.;
          int numero_bord_robin=0;
          int nbfaces_bord_robin=0;
          double rho = 0.;
          double mu = 0.;
          if ( sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
            {
              rho = fluide.masse_volumique().valeurs()(0,0);
            }
          if ( sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
            {
              mu = fluide.viscosite_dynamique().valeurs()(0,0);
            }
// for each cl, calculation of the mean tauw
// loop on boundaries
          for (int num_cl=0; num_cl<nb_cl; num_cl++)
            {
              tauw_robin_tmp=0.;
              if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                rho = 0.;
              if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                mu = 0.;
              const Cond_lim& la_cl = les_cl[num_cl];
              if (la_cl.valeur().que_suis_je() == "Paroi_decalee_Robin")
                {
                  const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
                  nbfaces_bord_robin = la_front_dis.nb_faces();
                  int ndeb = la_front_dis.num_premiere_face();
                  int nfin = ndeb + nbfaces_bord_robin;
                  if (Objet_U::dimension == 2 )
                    {
// loop on faces in 2D
                      for (int fac=ndeb; fac<nfin ; fac++)
{
                          tauw_robin_tmp+=sqrt(tau_tan(fac,0)*tau_tan(fac,0));
                          int elem = zone_VF.face_voisins(fac,0);
                          if (elem == -1)
                            elem = zone_VF.face_voisins(fac,1);
                          if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                            rho+=fluide.masse_volumique().valeurs()[elem];
                          if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                            mu+=fluide.viscosite_dynamique().valeurs()[elem];
                        }
                    }
                  else
                    {
// loop on faces on 3D
                      for (int fac=ndeb; fac<nfin ; fac++)
{
                          tauw_robin_tmp+=sqrt(tau_tan(fac,0)*tau_tan(fac,0)+tau_tan(fac,2)*tau_tan(fac,2));
                          int elem = zone_VF.face_voisins(fac,0);
                          if (elem == -1)
                            elem = zone_VF.face_voisins(fac,1);
                          if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                            rho+=fluide.masse_volumique().valeurs()[elem];
                          if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                            mu+=fluide.viscosite_dynamique().valeurs()[elem];
                        }
                    }
                  tauw_robin_tmp=mp_sum(tauw_robin_tmp)/mp_sum(nbfaces_bord_robin);
                  if(!(mon_equation.valeur().probleme().is_dilatable()))
                    tauw_robin_tmp *= rho ;
                  if ( !sub_type(Champ_Uniforme,fluide.masse_volumique().valeur()) )
                    rho=mp_sum(rho)/mp_sum(nbfaces_bord_robin);
                  if ( !sub_type(Champ_Uniforme,fluide.viscosite_dynamique().valeur()) )
                    mu=mp_sum(mu)/mp_sum(nbfaces_bord_robin);
                  tauw_robin(numero_bord_robin) = tauw_robin_tmp;
                  utau_robin(numero_bord_robin) = sqrt(tauw_robin_tmp/rho);
                  retau_robin(numero_bord_robin)= rho*utau_robin(numero_bord_robin)*hs2/mu;
                  tauw_robin_m  += tauw_robin(numero_bord_robin);
                  utau_robin_m  += utau_robin(numero_bord_robin);
                  retau_robin_m += retau_robin(numero_bord_robin);
                  numero_bord_robin+=1;
                }
            } //!< loop on boundaries
          tauw_robin_m  = tauw_robin_m/nb_cl_robin;
          retau_robin_m = retau_robin_m/nb_cl_robin;
          utau_robin_m  = utau_robin_m/nb_cl_robin;
// prints
          if (je_suis_maitre())
            {
              SFichier fic4("tauw_robin.dat", mode);
              SFichier fic5("reynolds_tau_robin.dat", mode);
              SFichier fic6("u_tau_robin.dat", mode);
              fic4 << tps << "   " << tauw_robin_m   << "   ";
              fic5 << tps << "   " << retau_robin_m  << "   ";
              fic6 << tps << "   " << utau_robin_m   << "   ";
              for ( int num=0 ; num<nb_cl_robin ; num++)
                {
                  fic4 << tauw_robin(num)   << "   ";
                  fic5 << retau_robin(num)  << "   ";
                  fic6 << utau_robin(num)   << "   ";
                }
              fic4 <<  finl;
              fic5 <<  finl;
              fic6 <<  finl;
              fic4.flush();
              fic5.flush();
              fic6.flush();
              fic4.close();
              fic5.close();
              fic6.close();
            }
        } //!< end robin
////!< begin old
////!<    search of cl dirichlet      for (int num_cl=0; num_cl<nb_cl; num_cl++)        {          //Loop on boundaries          const Cond_lim& la_cl = les_cl[num_cl];          if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()))            {              const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());              nbfaces = la_front_dis.nb_faces();              int ndeb = la_front_dis.num_premiere_face();              int nfin = ndeb + nbfaces;              if (Objet_U::dimension == 2)                for (int fac=ndeb; fac<nfin ; fac++)                  {                    tauwb+=sqrt(tau_tan(fac,0)*tau_tan(fac,0));                  }              else                for (int fac=ndeb; fac<nfin ; fac++)                  {                    tauwb+=sqrt(tau_tan(fac,0)*tau_tan(fac,0)+tau_tan(fac,2)*tau_tan(fac,2));                  }              num_cl_rep=num_cl+1;              break;            }        } //Loop on boundaries      nbfaces_tot=mp_sum(nbfaces);      if (nbfaces_tot)        tauwb=mp_sum(tauwb)/nbfaces_tot;
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
////!<    on cherche la deuxieme cl dirichlet      nbfaces=0;      for (int num_cl=num_cl_rep; num_cl<nb_cl; num_cl++)        {          //Boucle sur les bords          const Cond_lim& la_cl = les_cl[num_cl];          if (sub_type(Dirichlet_paroi_fixe,la_cl.valeur()))            {              const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());              nbfaces = la_front_dis.nb_faces();              int ndeb = la_front_dis.num_premiere_face();              int nfin = ndeb + nbfaces;              if (Objet_U::dimension == 2)                for (int fac=ndeb; fac<nfin ; fac++)                  {                    tauwh+=sqrt(tau_tan(fac,0)*tau_tan(fac,0));                  }              else                for (int fac=ndeb; fac<nfin ; fac++)                  {                    tauwh+=sqrt(tau_tan(fac,0)*tau_tan(fac,0)+tau_tan(fac,2)*tau_tan(fac,2));                  }              break;            }        } //Boucle sur les bords      nbfaces_tot=mp_sum(nbfaces);      if (nbfaces_tot)        tauwh=mp_sum(tauwh)/nbfaces_tot;      if(!(mon_equation.valeur().probleme().is_QC()))        {          tauwb*=rho_bas;          tauwh*=rho_haut;        }      if (je_suis_maitre())        {          // calcul et ecritures des differentes grandeurs parietales          //////////////////////////////////////////////////////          // vitesse de frottement          double utaub=sqrt(tauwb/rho_bas);          if(val_moy_tot(kmin,0,0)<=0) utaub*=-1.;          double utauh=sqrt(tauwh/rho_haut);          if(val_moy_tot(kmax,0,0)<=0) utauh*=-1.;          double utaum=0.5*(utauh+utaub);          // Reynolds de frottement          double retaub=rho_bas*utaub*hs2/mu_bas;          double retauh=rho_haut*utauh*hs2/mu_haut;          double retaum=0.5*(retauh+retaub);          tauwm=0.5*(tauwh+tauwb);          SFichier fic1("reynolds_tau_old.dat",ios::app);          SFichier fic2("u_tau_old.dat",ios::app);          SFichier fic3("tauw_old.dat",ios::app);          fic1 << tps << " " << retaum << " " << retaub << " " << retauh << finl;          fic2 << tps << " " << utaum << " "  << utaub << " "  << utauh  << finl;          fic3 << tps << " " << tauwm << " "  << tauwb << " "  << tauwh  << finl;          fic1.close();          fic2.close();          fic3.close();        }
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
//
////!< end old
    } //!< end if turbul
  else
    {
// norme de la vitesse tangente a la paroi
      double utang_bas  = val_moy_tot(kmin,9,0);
      double utang_haut = val_moy_tot(kmax,9,0);
// calcul du cisaillement a la paroi suivant la vitesse tangentielle
//
// approximation lineaire : Tau_w = mu * ||u_t||(y1) / dy1
      tauwb= mu_bas * utang_bas  / ymin;
      tauwh= mu_haut* utang_haut / ymin;
      if (je_suis_maitre())
        {
// calcul et ecritures des differentes grandeurs parietales
//
// vitesse de frottement
          double utaub=sqrt(tauwb/rho_bas);
          if(val_moy_tot(kmin,0,0)<=0) utaub*=-1.;
          double utauh=sqrt(tauwh/rho_haut);
          if(val_moy_tot(kmax,0,0)<=0) utauh*=-1.;
          double utaum=0.5*(utauh+utaub);
// Reynolds de frottement
          double retaub=rho_bas*utaub*hs2/mu_bas;
          double retauh=rho_haut*utauh*hs2/mu_haut;
          double retaum=0.5*(retauh+retaub);
          tauwm=0.5*(tauwh+tauwb);
          SFichier fic1("reynolds_tau.dat", mode);
          SFichier fic2("u_tau.dat", mode);
          SFichier fic3("tauw.dat", mode);
          fic1 << tps << " " << retaum << " " << retaub << " " << retauh << finl;
          fic2 << tps << " " << utaum << " "  << utaub << " "  << utauh  << finl;
          fic3 << tps << " " << tauwm << " "  << tauwb << " "  << tauwh  << finl;
          fic1.close();
          fic2.close();
          fic3.close();
        }
    } //!< end if not-turbul
}
References Cerr, Turbulence_paroi::Cisaillement_paroi(), Sortie_Fichier_base::close(), Objet_U::dimension, Equation_base::discretisation(), Probleme_base::equation(), Process::exit(), Zone_VF::face_voisins(), finl, Sortie_Fichier_base::flush(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), Navier_Stokes_std::inconnue(), IOS_OPEN_MODE, Probleme_base::is_dilatable(), Process::je_suis_maitre(), Zone_Cl_dis_base::les_conditions_limites(), Milieu_base::masse_volumique(), Equation_base::milieu(), Traitement_particulier_NS_base::mon_equation, Process::mp_sum(), Front_VF::nb_faces(), Schema_Temps_base::nb_pas_dt(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Equation_base::probleme(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), ref_cast, Probleme_base::reprise_effectuee(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), vect_impl::size(), sub_type, Champ_Inc::temps(), TURBULENCE, val_moy_tot, Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Ref_Objet_U::valeur(), Ref_Navier_Stokes_std::valeur(), Champ::valeurs(), Champ_Don::valeurs(), Fluide_base::viscosite_dynamique(), Y_tot, Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_nut()
virtual void Traitement_particulier_NS_canal::calculer_moyenne_spatiale_nut (DoubleTab &) const protected pure virtual
Implemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_Temp()
virtual void Traitement_particulier_NS_canal::calculer_moyenne_spatiale_Temp (DoubleTab &) const protected pure virtual
Implemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_vitesse_rho_mu()
virtual void Traitement_particulier_NS_canal::calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab &) const protected pure virtual
Implemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Referenced by post_traitement_particulier().
comprend_champ()
int Traitement_particulier_NS_canal::comprend_champ (const Motcle & mot) const inline
Definition at line 49 of file Traitement_particulier_NS_canal.h.
{ return 0 ; }
ecriture_fichiers_moy_nut()
void Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut (const DoubleTab & val_moy, const Nom & fichier, const double dt, const int k) const protected
Definition at line 1223 of file Traitement_particulier_NS_canal.cpp.
{
  SFichier fic (fichier);
  double tps = mon_equation->inconnue().temps();
  fic << "# Temps : " << tps << finl;
  fic << " " << finl;
  fic << "# (0)  : Y " << finl;
  fic << "# (1)  : <nu_t> " << finl;
  fic << "#  " << finl;
  fic << "# Nombre minimum de points par plan Y=cste ayant servi au calcul de la moyenne spatiale : " << min_array(compt_tot) << finl;
  fic << "#  " << finl;
  for (int i=0; i<Y_tot.size(); i++)
    fic << Y_tot(i) << "    " << val_moy(i,12,k)/dt << finl;
  fic.flush();
  fic.close();
}
References Sortie_Fichier_base::close(), compt_tot, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), min_array(), Traitement_particulier_NS_base::mon_equation, TRUSTVect< _TYPE_ >::size(), Champ_Inc::temps(), and Y_tot.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_Temp()
void Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp (const DoubleTab & val_moy, const Nom & fichier, const double dt, const int k) const protected
Definition at line 1246 of file Traitement_particulier_NS_canal.cpp.
{
  SFichier fic (fichier);
  double tps = mon_equation->inconnue().temps();
  double T,T2,uT,vT,wT;
  fic << "# Temps : " << tps << finl;
  fic << " " << finl;
  fic << "# (0)  : Y " << finl;
  fic << "# (1)  : <T> " << finl;
  fic << "# (2)  : sqrt(<T.T>-<T>*<T>) " << finl;
  fic << "# (3)  : <u.T>-<u>*<T> " << finl;
  fic << "# (4)  : <v.T>-<v>*<T> " << finl;
  fic << "# (5)  : <w.T>-<w>*<T> " << finl;
  fic << "#  " << finl;
  fic << "# Nombre minimum de points par plan Y=cste ayant servi au calcul de la moyenne spatiale : " << min_array(compt_tot) << finl;
  fic << "#  " << finl;
  for (int i=0; i<Y_tot.size(); i++)
    {
// u    = val_moy(i,0,k)/dt;
// v    = val_moy(i,1,k)/dt;
// w    = val_moy(i,2,k)/dt;
      T    = val_moy(i,13,k)/dt;
      T2   = val_moy(i,14,k)/dt;
      uT   = val_moy(i,15,k)/dt;
      vT   = val_moy(i,16,k)/dt;
      wT   = val_moy(i,17,k)/dt;
      fic << Y_tot(i) << "    "  ;
// Pour eviter NAN, on prend le std::max(,0):
      fic << T << "    "  <<sqrt(std::max(T2,0.))<<" ";
      fic << -uT << "    " << -vT  << "    " << -wT  << "    ";
      fic << finl;
    }
  fic.flush();
  fic.close();
}
References Sortie_Fichier_base::close(), compt_tot, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), min_array(), Traitement_particulier_NS_base::mon_equation, TRUSTVect< _TYPE_ >::size(), Champ_Inc::temps(), and Y_tot.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_Temp_old()
void Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old (const DoubleTab & val_moy, const Nom & fichier, const double dt, const int k) const protected
Definition at line 1350 of file Traitement_particulier_NS_canal.cpp.
{
  SFichier fic (fichier);
  fic.setf(ios::scientific);
  double tps = mon_equation->inconnue().temps();
  double u,v,wl,T,T2,uT,vT,wT;
  fic << "# Temps : " << tps << finl;
  fic << " " << finl;
  fic << "# (0)  : Y " << finl;
  fic << "# (1)  : <T> " << finl;
  fic << "# (2)  : sqrt(<T.T>-<T>*<T>) " << finl;
  fic << "# (3)  : <u.T>-<u>*<T> " << finl;
  fic << "# (4)  : <v.T>-<v>*<T> " << finl;
  fic << "# (5)  : <w.T>-<w>*<T> " << finl;
  fic << "#  " << finl;
  fic << "# Nombre minimum de points par plan Y=cste ayant servi au calcul de la moyenne spatiale : " << min_array(compt_tot) << finl;
  fic << "#  " << finl;
  for (int i=0; i<Y_tot.size(); i++)
    {
      u    = val_moy(i,0,k)/dt;
      v    = val_moy(i,1,k)/dt;
      wl    = val_moy(i,2,k)/dt;
      T    = val_moy(i,13,k)/dt;
      T2   = val_moy(i,14,k)/dt;
      uT   = val_moy(i,15,k)/dt;
      vT   = val_moy(i,16,k)/dt;
      wT   = val_moy(i,17,k)/dt;
      fic << Y_tot(i) << "    "  ;
// Pour eviter NAN, on prend le std::max(,0):
      fic << T << "    " << sqrt(std::max(T2-T*T,0.)) << "    "  ;
      fic << u*T-uT << "    " << v*T-vT << "    " << wl*T-wT << "    ";
      fic << finl;
    }
  fic.flush();
  fic.close();
}
References Sortie_Fichier_base::close(), compt_tot, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), min_array(), Traitement_particulier_NS_base::mon_equation, Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_ >::size(), Champ_Inc::temps(), and Y_tot.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_vitesse_rho_mu()
void Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu (const DoubleTab & val_moy, const Nom & fichier, const double dt, const int k) const protected
Definition at line 1169 of file Traitement_particulier_NS_canal.cpp.
{
  SFichier fic (fichier);
  double tps = mon_equation->inconnue().temps();
  double u,v,wl,u2,v2,w2,uv,uw,vw,rho,mu;
  fic << "# Temps : " << tps << finl;
  fic << " " << finl;
  fic << "# (0)  : Y " << finl;
  fic << "# (1)  : <u> " << finl;
  fic << "# (2)  : <v> " << finl;
  fic << "# (3)  : <w> " << finl;
  fic << "# (4)  : sqrt(<u.u>-<u>*<u>) " << finl;
  fic << "# (5)  : sqrt(<v.v>-<v>*<v>) " << finl;
  fic << "# (6)  : sqrt(<w.w>-<w>*<w>) " << finl;
  fic << "# (7)  : <u.v>-<u>*<v> " << finl;
  fic << "# (8)  : <u.w>-<u>*<w> " << finl;
  fic << "# (9)  : <v.w>-<v>*<w> " << finl;
  fic << "# (10) : <rho> " << finl;
  fic << "# (11) : <mu> " << finl;
  fic << "#  " << finl;
  fic << "# Nombre minimum de points par plan Y=cste ayant servi au calcul de la moyenne spatiale : " << min_array(compt_tot) << finl;
  fic << "#  " << finl;
  for (int i=0; i<Y_tot.size(); i++)
    {
      u    = val_moy(i,0,k)/dt;
      v    = val_moy(i,1,k)/dt;
      wl    = val_moy(i,2,k)/dt;
      u2   = val_moy(i,3,k)/dt;
      v2   = val_moy(i,4,k)/dt;
      w2   = val_moy(i,5,k)/dt;
      uv   = val_moy(i,6,k)/dt;
      uw   = val_moy(i,7,k)/dt;
      vw   = val_moy(i,8,k)/dt;
      rho  = val_moy(i,10,k)/dt;
      mu   = val_moy(i,11,k)/dt;
      fic << Y_tot(i) << "    "  ;
      fic << u << "    " << v << "    " << wl << "    " ;
// Pour eviter NAN, on prend le std::max(,0):
      fic << sqrt(std::max(0.,u2)) << "    " << sqrt(std::max(v2,0.)) << "    " << sqrt(std::max(w2,0.)) << "    "  ;
      fic << -uv << "    " << -uw << "    " << -vw  << "    " ;
      fic << rho << "    " << mu << "    " ;
      fic << finl;
    }
  fic.flush();
  fic.close();
}
References Sortie_Fichier_base::close(), compt_tot, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), min_array(), Traitement_particulier_NS_base::mon_equation, TRUSTVect< _TYPE_ >::size(), Champ_Inc::temps(), and Y_tot.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_vitesse_rho_mu_old()
void Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old (const DoubleTab & val_moy, const Nom & fichier, const double dt, const int k) const protected
Definition at line 1292 of file Traitement_particulier_NS_canal.cpp.
{
  SFichier fic (fichier);
  double tps = mon_equation->inconnue().temps();
  double u,v,wl,u2,v2,w2,uv,uw,vw,rho,mu;
  fic << "# Temps : " << tps << finl;
  fic << " " << finl;
  fic << "# (0)  : Y " << finl;
  fic << "# (1)  : <u> " << finl;
  fic << "# (2)  : <v> " << finl;
  fic << "# (3)  : <w> " << finl;
  fic << "# (4)  : sqrt(<u.u>-<u>*<u>) " << finl;
  fic << "# (5)  : sqrt(<v.v>-<v>*<v>) " << finl;
  fic << "# (6)  : sqrt(<w.w>-<w>*<w>) " << finl;
  fic << "# (7)  : <u.v>-<u>*<v> " << finl;
  fic << "# (8)  : <u.w>-<u>*<w> " << finl;
  fic << "# (9)  : <v.w>-<v>*<w> " << finl;
  fic << "# (10) : <rho> " << finl;
  fic << "# (11) : <mu> " << finl;
  fic << "#  " << finl;
  fic << "# Nombre minimum de points par plan Y=cste ayant servi au calcul de la moyenne spatiale : " << min_array(compt_tot) << finl;
  fic << "#  " << finl;
  for (int i=0; i<Y_tot.size(); i++)
    {
      u    = val_moy(i,0,k)/dt;
      v    = val_moy(i,1,k)/dt;
      wl    = val_moy(i,2,k)/dt;
      u2   = val_moy(i,3,k)/dt;
      v2   = val_moy(i,4,k)/dt;
      w2   = val_moy(i,5,k)/dt;
      uv   = val_moy(i,6,k)/dt;
      uw   = val_moy(i,7,k)/dt;
      vw   = val_moy(i,8,k)/dt;
      rho  = val_moy(i,10,k)/dt;
      mu   = val_moy(i,11,k)/dt;
      fic << Y_tot(i) << "    "  ;
      fic << u << "    " << v << "    " << wl << "    " ;
// Pour eviter NAN, on prend le std::max(,0):
      fic << sqrt(std::max(0.,u2-u*u)) << "    " << sqrt(std::max(v2-v*v,0.)) << "    " << sqrt(std::max(w2-wl*wl,0.)) << "    "  ;
      fic << u*v-uv << "    " << u*wl-uw << "    " << v*wl-vw  << "    " ;
      fic << rho << "    " << mu << "    " ;
      fic << finl;
    }
  fic.flush();
  fic.close();
}
References Sortie_Fichier_base::close(), compt_tot, finl, Sortie_Fichier_base::flush(), Navier_Stokes_std::inconnue(), min_array(), Traitement_particulier_NS_base::mon_equation, TRUSTVect< _TYPE_ >::size(), Champ_Inc::temps(), and Y_tot.
Referenced by post_traitement_particulier().
en_cours_de_resolution()
void Traitement_particulier_NS_canal::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 47 of file Traitement_particulier_NS_canal.h.
{ }
get_info()
const Type_info * Traitement_particulier_NS_canal::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Definition at line 31 of file Traitement_particulier_NS_canal.cpp.
info()
const Type_info * Traitement_particulier_NS_canal::info () static
Definition at line 31 of file Traitement_particulier_NS_canal.cpp.
lire()
Entree & Traitement_particulier_NS_canal::lire (Entree & is) override virtual
< intervalle de temps de sorties des moyennes spatiales
< intervalle de temps de sorties des moyennes temporelles
< temps de debut des moyennes temporelles
< temps de debut des moyennes temporelles
< indication du nom du fichier de reprise des stats
< pulsation
< frequence associee
< nombre de points pour decrire une phase
Implements Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Definition at line 93 of file Traitement_particulier_NS_canal.cpp.
{
  if(!sub_type(Navier_Stokes_std,mon_equation.valeur()))
    {
      Cerr << " Traitement_particulier_canal has to be called from a Navier_Stokes problem " << finl;
      exit();
    }
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle motbidon, motlu;
  is >> motbidon ;
  if (motbidon == accouverte)
    {
      Motcles les_mots(7);
      les_mots[0] = "dt_impr_moy_spat";
      les_mots[1] = "dt_impr_moy_temp";
      les_mots[2] = "debut_stat";
      les_mots[3] = "fin_stat";
      les_mots[4] = "reprise";
      les_mots[5] = "pulsation_w";
      les_mots[6] = "nb_points_par_phase";
      is >> motlu;
      while(motlu != accfermee)
        {
          int rang=les_mots.search(motlu);
          switch(rang)
            {
            case 0 :
              {
                is >> dt_impr_moy_spat;      //!< intervalle de temps de sorties des moyennes spatiales
                Cerr << "Spatial averages are printed for : dt_impr_moy_spat = " << dt_impr_moy_spat << finl;
                break;
              }
            case 1 :
              {
                is >> dt_impr_moy_temp;      //!< intervalle de temps de sorties des moyennes temporelles
                Cerr << "Temporal averages are printed for : dt_impr_moy_temp = " << dt_impr_moy_temp << finl;
                break;
              }
            case 2 :
              {
                is >> temps_deb;             //!< temps de debut des moyennes temporelles
                Cerr << "Temporal averages start at : temps_deb = " << temps_deb << finl;
                break;
              }
            case 3 :
              {
                is >> temps_fin;             //!< temps de debut des moyennes temporelles
                Cerr << "Temporal averages finish at : temps_fin = " << temps_fin << finl;
                break;
              }
            case 4 :
              {
                oui_repr = 1;
                is  >> fich_repr ;             //!< indication du nom du fichier de reprise des stats
                Cerr << "The time statistics file is : " << fich_repr << finl;
                break;
              }
            case 5 :
              {
                oui_pulse = 1;
                is  >> w ;                     //!< pulsation
                freq = w/(2.*3.141592653); //!< frequence associee
                break;
              }
            case 6 :
              {
                oui_pulse = 1;
                is  >> Nphase ;            //!< nombre de points pour decrire une phase
                break;
              }
            default :
              {
                Cerr << motlu << " is not a keyword for Traitement_particulier_NS_canal " << finl;
                Cerr << "Since the TRUST v1.5, the syntax of Canal option has changed." << finl;
                Cerr << "Check the reference manual." << finl;
                exit();
              }
            }
          is >> motlu;
        }
      is >> motlu;
      if (motlu != accfermee)
        {
          Cerr << "Error while reading in Traitement_particulier_NS_canal" << finl;;
          Cerr << "We were expecting a }" << finl;
          exit();
        }
    }
  else
    {
      Cerr << "Error while reading in Traitement_particulier_NS_canal" << finl;
      Cerr << "We were expecting a {" << finl;
      exit();
    }
  return is;
}
References Cerr, dt_impr_moy_spat, dt_impr_moy_temp, Process::exit(), fich_repr, finl, freq, Traitement_particulier_NS_base::mon_equation, Nphase, oui_pulse, oui_repr, Motcles::search(), sub_type, temps_deb, temps_fin, Ref_Navier_Stokes_std::valeur(), and w.
Referenced by Traitement_particulier_NS_canal_VDF::lire(), and Traitement_particulier_NS_canal_VEF::lire().
post_traitement_particulier()
void Traitement_particulier_NS_canal::post_traitement_particulier (void) override virtual
< sinon, les valeurs de val_moy_temp ont ete lues a partir de reprendre_stat()
< debut d'une periode
< recherche de la k-phase correspondant
< marqueur pour ecriture de moyennes de phase (voir plus bas)
Implements Traitement_particulier_NS_base.
Definition at line 411 of file Traitement_particulier_NS_canal.cpp.
{
// Calcul des Moyennes spatiales
//
  DoubleTrav val_moy(Ny,Nval);
  val_moy=0.;
  calculer_moyenne_spatiale_vitesse_rho_mu(val_moy);
  if (oui_profil_nu_t != 0)
    calculer_moyenne_spatiale_nut(val_moy);
  if (oui_profil_Temp != 0)
    calculer_moyenne_spatiale_Temp(val_moy);
// Echange des donnees entre processeurs
//
  DoubleVect Y_p(Y);
  DoubleVect compt_p(compt);
  DoubleTab val_moy_p(val_moy);
  const int NN = Y_tot.size();
  envoyer(Y_p,Process::me(),0,Process::me());
  envoyer(compt_p,Process::me(),0,Process::me());
  envoyer(val_moy_p,Process::me(),0,Process::me());
  if(je_suis_maitre())
    {
      compt_tot=0;
      val_moy_tot=0.;
      int j;
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(Y_p,p,0,p);
          recevoir(compt_p,p,0,p);
          recevoir(val_moy_p,p,0,p);
          int Y_p_size = Y_p.size();
          for (int i=0; i<Y_p_size; i++)
            {
              for (j=0; j<NN; j++)
                if(est_egal(Y_tot[j],Y_p[i])) break;
              compt_tot(j) += compt_p(i);
              for (int k=0; k<Nval; k++)
                val_moy_tot(j,k,0) += val_moy_p(i,k);
            }
        }
      for (int i=0; i<NN; i++)
        for (int k=0; k<Nval; k++)
          val_moy_tot(i,k,0) /= compt_tot[i];
    }
// Calcul et ecriture des grandeurs parietales
//
  calcul_reynolds_tau();
// Calcul des Moyennes temporelles
//
  double tps = mon_equation->inconnue().temps();
  if(je_suis_maitre())
    {
      if ((tps>=temps_deb)&&(tps<=temps_fin))
        {
          static int init_stat_temps = 0;
          double dt_v = mon_equation->schema_temps().pas_de_temps();
          int NN2 = Y_tot.size();
          if(init_stat_temps==0 && oui_repr!=1) //!< sinon, les valeurs de val_moy_temp ont ete lues a partir de reprendre_stat()
            {
              temps_deb = tps-dt_v;
              val_moy_temp.resize(NN2,Nval,1);
              val_moy_temp=0.;
              init_stat_temps++;
            }
          for (int j=0; j<Nval; j++)
            for (int i=0; i<NN2; i++)
              {
                if ((j!=3) && (j!=4) && (j!=5) && (j!=6) && (j!=7) && (j!=8) && (j!=14) && (j!=15) && (j!=16) && (j!=17))
                  val_moy_temp(i,j,0)+= dt_v*val_moy_tot(i,j,0);
                if (j==3)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,3,0)-val_moy_tot(i,0,0)*val_moy_tot(i,0,0));
                if (j==4)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,4,0)-val_moy_tot(i,1,0)*val_moy_tot(i,1,0));
                if (j==5)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,5,0)-val_moy_tot(i,2,0)*val_moy_tot(i,2,0));
                if (j==6)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,6,0)-val_moy_tot(i,0,0)*val_moy_tot(i,1,0));
                if (j==7)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,7,0)-val_moy_tot(i,0,0)*val_moy_tot(i,2,0));
                if (j==8)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,8,0)-val_moy_tot(i,1,0)*val_moy_tot(i,2,0));
                if (j==14)
// val_moy_temp(i,j,0)+= dt_v*val_moy_tot(i,13,0)*val_moy_tot(i,13,0);
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,14,0)-val_moy_tot(i,13,0)*val_moy_tot(i,13,0));
                if (j==15)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,15,0)-val_moy_tot(i,0,0)*val_moy_tot(i,13,0));
                if (j==16)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,16,0)-val_moy_tot(i,1,0)*val_moy_tot(i,13,0));
                if (j==17)
                  val_moy_temp(i,j,0)+= dt_v*(val_moy_tot(i,17,0)-val_moy_tot(i,2,0)*val_moy_tot(i,13,0));
              }
        }
    }
// Calcul des Moyennes de phases
//
  if(je_suis_maitre() && oui_pulse==1)
    {
      if ((tps>=temps_deb)&&(tps<=temps_fin))
        {
          double dt_v = mon_equation->schema_temps().pas_de_temps();
          if ( (cos(w*tps) > cos(w*(tps+dt_v))) && (cos(w*tps) > cos(w*(tps-dt_v))) ) //!< debut d'une periode
            {
              debut_phase=tps;
              ind_phase=1;
            }
          if(ind_phase==1)
            {
              for(int k=0; k<Nphase; k++)
                {
                  double tps_k=debut_phase+k/(Nphase*freq);
                  if( (tps > tps_k-0.5*dt_v)  && (tps < tps_k+0.5*dt_v) ) //!< recherche de la k-phase correspondant
                    {
                      for (int j=0; j<Nval; j++)
                        for (int i=0; i<NN; i++)
                          val_moy_phase(i,j,k) += val_moy_tot(i,j,0);
                      Nb_ech_phase(k)++;
                      if(k==Nphase-1)  ind_phase=2; //!< marqueur pour ecriture de moyennes de phase (voir plus bas)
                    }
                }
            }
        }
    }
// Ecriture des Moyennes spatiales et temporelles
//
  if(je_suis_maitre())
    {
      double stationnaire_atteint=mon_equation->schema_temps().stationnaire_atteint();
      double tps_passe=mon_equation->schema_temps().temps_courant();
      double nb_pas_dt_max=mon_equation->schema_temps().nb_pas_dt_max();
      double nb_pas_dt=mon_equation->schema_temps().nb_pas_dt();
      double temps_max=mon_equation->schema_temps().temps_max();
      int impr_inst;
      if (dt_impr_moy_spat<=(tps-tps_passe))
        impr_inst=1;
      else
        {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
          double i, j, epsilon = 1.e-8;
          modf(tps/dt_impr_moy_spat + epsilon, &i);
          modf(tps_passe/dt_impr_moy_spat + epsilon, &j);
          impr_inst=(i>j);
        }
      int impr_stat;
      if (dt_impr_moy_temp<=(tps-tps_passe))
        impr_stat=1;
      else
        {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
          double i, j, epsilon = 1.e-8;
          modf(tps/dt_impr_moy_temp + epsilon, &i);
          modf(tps_passe/dt_impr_moy_temp + epsilon, &j);
          impr_stat=(i>j);
        }
// sauvegarde periodique des moyennes spatiales
      if ((nb_pas_dt+1<=1) || impr_inst || (temps_max <= tps) || (nb_pas_dt_max <= nb_pas_dt+1) || stationnaire_atteint)
        {
          double dt = 1.;
          Nom fichier1 = "Moyennes_spatiales_vitesse_rho_mu_";
          Nom fichier2 = "Moyennes_spatiales_nut_";
          Nom fichier3 = "Moyennes_spatiales_Temp_";
          Nom temps = Nom(tps);
          fichier1 += temps;
          fichier2 += temps;
          fichier3 += temps;
          /*
            ecriture_fichiers_moy_vitesse_rho_mu(val_moy_tot,fichier1,dt,0);
            if (oui_profil_nu_t == 1)   ecriture_fichiers_moy_nut(val_moy_tot,fichier2,dt,0);
            if (oui_profil_Temp == 1)   ecriture_fichiers_moy_Temp(val_moy_tot,fichier3,dt,0);
          */
          ecriture_fichiers_moy_vitesse_rho_mu_old(val_moy_tot,fichier1,dt,0);
          if (oui_profil_nu_t == 1)   ecriture_fichiers_moy_nut(val_moy_tot,fichier2,dt,0);
          if (oui_profil_Temp == 1)   ecriture_fichiers_moy_Temp_old(val_moy_tot,fichier3,dt,0);
        }
// sauvegarde periodique des moyennes temporelles
      if ((tps>temps_deb) && ((nb_pas_dt+1<=1) || impr_stat || (temps_max <= tps) || (nb_pas_dt_max <= nb_pas_dt+1) || stationnaire_atteint))
        {
          double dt = tps-temps_deb;
          Nom fichier1 = "Moyennes_temporelles_vitesse_rho_mu_";
          Nom fichier2 = "Moyennes_temporelles_nut_";
          Nom fichier3 = "Moyennes__temporelles_Temp_";
          Nom temps = Nom(tps);
          fichier1 += temps;
          fichier2 += temps;
          fichier3 += temps;
          ecriture_fichiers_moy_vitesse_rho_mu(val_moy_temp,fichier1,dt,0);
          if (oui_profil_nu_t == 1)   ecriture_fichiers_moy_nut(val_moy_temp,fichier2,dt,0);
          if (oui_profil_Temp == 1)   ecriture_fichiers_moy_Temp(val_moy_temp,fichier3,dt,0);
        }
// sauvegarde en continue des moyennes temporelles
      if (tps>temps_deb)
        {
          double dt = tps-temps_deb;
          Nom fichier1 = "Moyennes_temporelles_vitesse_rho_mu";
          Nom fichier2 = "Moyennes_temporelles_nut";
          Nom fichier3 = "Moyennes__temporelles_Temp";
          ecriture_fichiers_moy_vitesse_rho_mu(val_moy_temp,fichier1,dt,0);
          if (oui_profil_nu_t == 1)   ecriture_fichiers_moy_nut(val_moy_temp,fichier2,dt,0);
          if (oui_profil_Temp == 1)   ecriture_fichiers_moy_Temp(val_moy_temp,fichier3,dt,0);
        }
// sauvegarde en continue des moyennes de phase (en fin de cycle)
      if ( (ind_phase==2) && (tps>temps_deb) )
        {
          ind_phase=0;
          for(int k=0; k<Nphase; k++)
            {
              double dt = Nb_ech_phase(k);
              Nom fichier1 = "Moyennes_de_phase_vitesse_rho_mu_";
              Nom fichier2 = "Moyennes_de_phase_nut_";
              Nom fichier3 = "Moyennes_de_phase_Temp_";
              Nom phase = Nom(k);
              fichier1 += phase;
              fichier2 += phase;
              fichier3 += phase;
              ecriture_fichiers_moy_vitesse_rho_mu_old(val_moy_phase,fichier1,dt,k);
              if (oui_profil_nu_t == 1)   ecriture_fichiers_moy_nut(val_moy_phase,fichier2,dt,k);
              if (oui_profil_Temp == 1)   ecriture_fichiers_moy_Temp_old(val_moy_phase,fichier3,dt,k);
            }
        }
    }
}
References calcul_reynolds_tau(), calculer_moyenne_spatiale_nut(), calculer_moyenne_spatiale_Temp(), calculer_moyenne_spatiale_vitesse_rho_mu(), compt, compt_tot, debut_phase, dt_impr_moy_spat, dt_impr_moy_temp, ecriture_fichiers_moy_nut(), ecriture_fichiers_moy_Temp(), ecriture_fichiers_moy_Temp_old(), ecriture_fichiers_moy_vitesse_rho_mu(), ecriture_fichiers_moy_vitesse_rho_mu_old(), envoyer(), est_egal(), freq, Navier_Stokes_std::inconnue(), ind_phase, Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_base::mon_equation, Nb_ech_phase, Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), Nphase, Process::nproc(), Nval, Ny, oui_profil_nu_t, oui_profil_Temp, oui_pulse, oui_repr, Schema_Temps_base::pas_de_temps(), recevoir(), TRUSTTab< _TYPE_ >::resize(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), Schema_Temps_base::stationnaire_atteint(), Champ_Inc::temps(), Schema_Temps_base::temps_courant(), temps_deb, temps_fin, Schema_Temps_base::temps_max(), val_moy_phase, val_moy_temp, val_moy_tot, w, Y, and Y_tot.
preparer_calcul_particulier()
void Traitement_particulier_NS_canal::preparer_calcul_particulier (void) override virtual
< renvoie vers Traitement_particulier_NS_canal_VDF ou Traitement_particulier_NS_canal_VEF
Implements Traitement_particulier_NS_base.
Definition at line 200 of file Traitement_particulier_NS_canal.cpp.
{
  const RefObjU& modele_turbulence = mon_equation.valeur().get_modele(TURBULENCE);
  if (modele_turbulence.non_nul() && sub_type(Mod_turb_hyd_base,modele_turbulence.valeur()))
    {
      oui_profil_nu_t = 1;
      Nval=13;
    }
  if (mon_equation.valeur().probleme().nombre_d_equations()>1)
    try
      {
        Temp = mon_equation.valeur().probleme().equation(1).get_champ("temperature");
        oui_profil_Temp = 1 ;
        Nval=18;
      }
    catch (Champs_compris_erreur)
      {
      }
  remplir_Y(Y,compt,Ny); //!< renvoie vers Traitement_particulier_NS_canal_VDF ou Traitement_particulier_NS_canal_VEF
  remplir_Tab_recap(Tab_recap);
  remplir_reordonne_Y_tot(Y,Y_tot);
  int NN=Y_tot.size();
  compt_tot.resize(NN);
  val_moy_tot.resize(NN,Nval,1);
  if (oui_repr!=1)
    {
      val_moy_temp.resize(Y_tot.size(),Nval,1);
      val_moy_temp=0.;
      if (oui_pulse==1)
        {
          val_moy_phase.resize(Y_tot.size(),Nval,Nphase);
          val_moy_phase=0.;
          Nb_ech_phase.resize(Nphase);
          Nb_ech_phase=0;
        }
    }
}
References compt, compt_tot, Probleme_base::equation(), Equation_base::get_champ(), Equation_base::get_modele(), Traitement_particulier_NS_base::mon_equation, Nb_ech_phase, Probleme_base::nombre_d_equations(), O_U_Ptr::non_nul(), Nphase, Nval, Ny, oui_profil_nu_t, oui_profil_Temp, oui_pulse, oui_repr, Equation_base::probleme(), remplir_reordonne_Y_tot(), remplir_Tab_recap(), remplir_Y(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), sub_type, Tab_recap, Temp, TURBULENCE, val_moy_phase, val_moy_temp, val_moy_tot, Ref_Objet_U::valeur(), Ref_Navier_Stokes_std::valeur(), Y, and Y_tot.
printOn()
Sortie & Traitement_particulier_NS_canal::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Definition at line 68 of file Traitement_particulier_NS_canal.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_canal::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Definition at line 88 of file Traitement_particulier_NS_canal.cpp.
{
  return is;
}
remplir_reordonne_Y_tot()
void Traitement_particulier_NS_canal::remplir_reordonne_Y_tot (const DoubleVect & tab_Y, DoubleVect & tab_Y_tot) const protected
< on recherche si Y_p(k) est deja contenu dans Y_tot
Definition at line 243 of file Traitement_particulier_NS_canal.cpp.
{
  DoubleVect Y_p(tab_Y);
  int j_tot=1;
  envoyer(Y_p, Process::me(), 0, Process::me());
  if(je_suis_maitre())
    {
      tab_Y_tot.resize(1);
      tab_Y_tot(0) = tab_Y(0);
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(Y_p,p,0,p);
          for (int k=0; k<Y_p.size(); k++)
            {
              if(!est_egal(Y_p(k),-100.)) //!< on recherche si Y_p(k) est deja contenu dans Y_tot
                {
                  int ok_new=1;
                  for (int j=0; j<tab_Y_tot.size(); j++)
                    if (est_egal(tab_Y_tot(j),Y_p(k)))
                      ok_new=0;
                  if(ok_new==1)
                    {
                      tab_Y_tot.resize(j_tot+1);
                      tab_Y_tot(j_tot) = Y_p(k);
                      j_tot++;
                    }
                }
            }
        }
      if(est_egal(tab_Y_tot(0),1.e12))
        {
          Cerr << "Probleme a la construction de Y_tot" << finl;
          exit();
        }
      tab_Y_tot.ordonne_array();
// Envoi de Y_tot aux autres processeurs
      for(int p=1; p<Process::nproc(); p++)
        envoyer(tab_Y_tot, 0, p, 0);
    }
  else
    {
      recevoir(tab_Y_tot,0,Process::me(),0);
    }
}
References Cerr, envoyer(), est_egal(), Process::exit(), finl, Process::je_suis_maitre(), Process::me(), Process::nproc(), TRUSTArray< _TYPE_ >::ordonne_array(), recevoir(), TRUSTVect< _TYPE_ >::resize(), and TRUSTVect< _TYPE_ >::size().
Referenced by preparer_calcul_particulier().
remplir_Tab_recap()
void Traitement_particulier_NS_canal::remplir_Tab_recap (IntTab & Tab_rec) const protected virtual
Reimplemented in Traitement_particulier_NS_canal_VDF.
Definition at line 193 of file Traitement_particulier_NS_canal.cpp.
{
// surchargeee dans VDF
  Cerr << "Traitement_particulier_NS_canal::remplir_Tab_recap ne marche pas pour le VEF" << finl;
// Process::exit();
}
References Cerr, and finl.
Referenced by preparer_calcul_particulier().
remplir_Y()
virtual void Traitement_particulier_NS_canal::remplir_Y (DoubleVect & , DoubleVect & , int &) const protected pure virtual
Implemented in Traitement_particulier_NS_canal_VDF, and Traitement_particulier_NS_canal_VEF.
Referenced by preparer_calcul_particulier().
reprendre_stat()
void Traitement_particulier_NS_canal::reprendre_stat (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 295 of file Traitement_particulier_NS_canal.cpp.
{
  if (je_suis_maitre())
    {
      Cerr << "Traitement_particulier_NS_canal::reprendre_stat!!" << flush << finl;
      if (oui_repr==1)
        {
          reprendre_stat_canal(val_moy_temp,fich_repr);
          Nval=val_moy_temp.dimension(1);
        }
      if (oui_repr==1 && oui_pulse==1)
        {
          Nom fich_repr_phase;
          fich_repr_phase  = fich_repr;
          fich_repr_phase +="_phase";
          reprendre_stat_canal(val_moy_phase,fich_repr_phase);
          Nphase=val_moy_phase.dimension(2);
        }
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), fich_repr, finl, Process::je_suis_maitre(), Nphase, Nval, oui_pulse, oui_repr, reprendre_stat_canal(), val_moy_phase, and val_moy_temp.
reprendre_stat_canal()
void Traitement_particulier_NS_canal::reprendre_stat_canal (DoubleTab & val, const Nom & fichier) protected
Definition at line 319 of file Traitement_particulier_NS_canal.cpp.
{
  double tps,tps_deb_moy;
  int NN,Nv,Np;
  Nom temps;
  EFichier fic(fichier);
  fic.setf(ios::scientific);
  if(fic.fail())
    {
      Cerr << "Impossible d'ouvrir le fichier " << fichier << finl;
      exit();
    }
  fic >> tps;
  fic >> tps_deb_moy;
  fic >> debut_phase;
  fic >> ind_phase;
  fic >> NN;
  fic >> Nv;
  fic >> Np;
  val.resize(NN,Nv,Np);
  Nb_ech_phase.resize(Np);
  for (int k=0; k<Np; k++)
    fic >> Nb_ech_phase(k);
  for (int k=0; k<Np; k++)
    for (int j=0; j<Nv; j++)
      for (int i=0; i<NN; i++)
        fic >> val(i,j,k);
  if(!est_egal(tps_deb_moy,temps_deb,0.1))
    {
      Cerr << "ERREUR : le temps de debut des stats figurant dans le jeu de donnees differe de beaucoup" << finl;
      Cerr << "du temps defini dans le fichier de reprise : " << fichier << finl;
      exit();
    }
  temps_deb=tps_deb_moy;
}
References Cerr, debut_phase, est_egal(), Process::exit(), Entree_Fichier_base::fail(), finl, ind_phase, Nb_ech_phase, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Entree_Fichier_base::setf(), and temps_deb.
Referenced by reprendre_stat().
sauver_stat()
void Traitement_particulier_NS_canal::sauver_stat (void) const override virtual
Implements Traitement_particulier_NS_base.
Definition at line 363 of file Traitement_particulier_NS_canal.cpp.
{
  double tps = mon_equation->inconnue().temps();
  if (je_suis_maitre() && (tps>=temps_deb) && (tps<=temps_fin) )
    {
      Cerr << "Traitement_particulier_NS_canal::sauver_stat!!" << flush << finl;
      Nom temps = Nom(tps);
      Nom fich_sauv1 ="val_moy_temp_";
      fich_sauv1+=temps;
      fich_sauv1+=".sauv";
      Nom fich_sauv2 = fich_sauv1;
      fich_sauv2+="_phase";
      sauver_stat_canal(val_moy_temp,fich_sauv1);
      if(oui_pulse==1)  sauver_stat_canal(val_moy_phase,fich_sauv2);
    }
}
References Cerr, finl, Navier_Stokes_std::inconnue(), Process::je_suis_maitre(), Traitement_particulier_NS_base::mon_equation, oui_pulse, sauver_stat_canal(), Champ_Inc::temps(), temps_deb, temps_fin, val_moy_phase, and val_moy_temp.
sauver_stat_canal()
void Traitement_particulier_NS_canal::sauver_stat_canal (const DoubleTab & val, const Nom & fichier) const protected
Definition at line 383 of file Traitement_particulier_NS_canal.cpp.
{
  double tps = mon_equation->inconnue().temps();
  int NN,Nv,Np;
  NN=val.dimension(0);
  Nv=val.dimension(1);
  Np=val.dimension(2);
  SFichier fic(fichier);
  fic.setf(ios::scientific);
  fic << tps << finl;
  fic << temps_deb << finl;
  fic << debut_phase << finl;
  fic << ind_phase << finl;
  fic << NN << finl;
  fic << Nv << finl;
  fic << Np << finl;
  for (int k=0; k<Np; k++)
    fic <<Nb_ech_phase(k) << finl;
  for (int k=0; k<Np; k++)
    for (int j=0; j<Nv; j++)
      for (int i=0; i<NN; i++)
        fic << val(i,j,k) << finl;
}
References debut_phase, TRUSTTab< _TYPE_ >::dimension(), finl, Navier_Stokes_std::inconnue(), ind_phase, Traitement_particulier_NS_base::mon_equation, Nb_ech_phase, Sortie_Fichier_base::setf(), Champ_Inc::temps(), and temps_deb.
Referenced by sauver_stat().
self_cast() [1/2]
const Traitement_particulier_NS_canal & Traitement_particulier_NS_canal::self_cast (const Objet_U & r) static
Definition at line 31 of file Traitement_particulier_NS_canal.cpp.
self_cast() [2/2]
Traitement_particulier_NS_canal & Traitement_particulier_NS_canal::self_cast (Objet_U & r) static
Definition at line 31 of file Traitement_particulier_NS_canal.cpp.
Member Data Documentation
compt
DoubleVect Traitement_particulier_NS_canal::compt protected
Definition at line 69 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
compt_tot
DoubleVect Traitement_particulier_NS_canal::compt_tot protected
Definition at line 69 of file Traitement_particulier_NS_canal.h.
Referenced by ecriture_fichiers_moy_nut(), ecriture_fichiers_moy_Temp(), ecriture_fichiers_moy_Temp_old(), ecriture_fichiers_moy_vitesse_rho_mu(), ecriture_fichiers_moy_vitesse_rho_mu_old(), post_traitement_particulier(), and preparer_calcul_particulier().
debut_phase
double Traitement_particulier_NS_canal::debut_phase protected
Definition at line 74 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), reprendre_stat_canal(), sauver_stat_canal(), and Traitement_particulier_NS_canal().
dt_impr_moy_spat
double Traitement_particulier_NS_canal::dt_impr_moy_spat protected
Definition at line 74 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), and Traitement_particulier_NS_canal().
dt_impr_moy_temp
double Traitement_particulier_NS_canal::dt_impr_moy_temp protected
Definition at line 74 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), and Traitement_particulier_NS_canal().
fich_repr
Nom Traitement_particulier_NS_canal::fich_repr protected
Definition at line 75 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), and reprendre_stat().
freq
double Traitement_particulier_NS_canal::freq protected
Definition at line 72 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), and post_traitement_particulier().
ind_phase
int Traitement_particulier_NS_canal::ind_phase protected
Definition at line 73 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), reprendre_stat_canal(), sauver_stat_canal(), and Traitement_particulier_NS_canal().
info_obj
const Type_info Traitement_particulier_NS_canal::info_obj static
Definition at line 38 of file Traitement_particulier_NS_canal.h.
Nb_ech_phase
IntVect Traitement_particulier_NS_canal::Nb_ech_phase protected
nombre d'echantillons par phase
Definition at line 70 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat_canal(), sauver_stat_canal(), and Traitement_particulier_NS_canal().
Nphase
int Traitement_particulier_NS_canal::Nphase protected
Definition at line 67 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat(), and Traitement_particulier_NS_canal().
nu_t_temp
DoubleVect Traitement_particulier_NS_canal::nu_t_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
Nval
int Traitement_particulier_NS_canal::Nval protected
Definition at line 67 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat(), and Traitement_particulier_NS_canal().
Ny
int Traitement_particulier_NS_canal::Ny protected
Definition at line 67 of file Traitement_particulier_NS_canal.h.
Referenced by Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), post_traitement_particulier(), preparer_calcul_particulier(), and Traitement_particulier_NS_canal_VDF::remplir_Tab_recap().
oui_profil_nu_t
int Traitement_particulier_NS_canal::oui_profil_nu_t protected
Definition at line 73 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), preparer_calcul_particulier(), and Traitement_particulier_NS_canal().
oui_profil_Temp
int Traitement_particulier_NS_canal::oui_profil_Temp protected
Definition at line 73 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), preparer_calcul_particulier(), and Traitement_particulier_NS_canal().
oui_pulse
int Traitement_particulier_NS_canal::oui_pulse protected
Definition at line 73 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat(), sauver_stat(), and Traitement_particulier_NS_canal().
oui_repr
int Traitement_particulier_NS_canal::oui_repr protected
Definition at line 73 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat(), and Traitement_particulier_NS_canal().
Tab_recap
IntTab Traitement_particulier_NS_canal::Tab_recap protected
Definition at line 71 of file Traitement_particulier_NS_canal.h.
Referenced by Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), and preparer_calcul_particulier().
Temp
Ref_Champ_base Traitement_particulier_NS_canal::Temp protected
Definition at line 77 of file Traitement_particulier_NS_canal.h.
Referenced by Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), and preparer_calcul_particulier().
temps_deb
double Traitement_particulier_NS_canal::temps_deb protected
Definition at line 74 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), reprendre_stat_canal(), sauver_stat(), sauver_stat_canal(), and Traitement_particulier_NS_canal().
temps_fin
double Traitement_particulier_NS_canal::temps_fin protected
Definition at line 74 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), post_traitement_particulier(), sauver_stat(), and Traitement_particulier_NS_canal().
u2_moy_temp
DoubleVect Traitement_particulier_NS_canal::u2_moy_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
uv_moy_temp
DoubleVect Traitement_particulier_NS_canal::uv_moy_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
uw_moy_temp
DoubleVect Traitement_particulier_NS_canal::uw_moy_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
v2_moy_temp
DoubleVect Traitement_particulier_NS_canal::v2_moy_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
val_moy_phase
DoubleTab Traitement_particulier_NS_canal::val_moy_phase protected
Definition at line 68 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat(), and sauver_stat().
val_moy_temp
DoubleTab Traitement_particulier_NS_canal::val_moy_temp protected
Definition at line 68 of file Traitement_particulier_NS_canal.h.
Referenced by post_traitement_particulier(), preparer_calcul_particulier(), reprendre_stat(), and sauver_stat().
val_moy_tot
DoubleTab Traitement_particulier_NS_canal::val_moy_tot protected
Definition at line 68 of file Traitement_particulier_NS_canal.h.
Referenced by calcul_reynolds_tau(), post_traitement_particulier(), and preparer_calcul_particulier().
w
double Traitement_particulier_NS_canal::w protected
Definition at line 72 of file Traitement_particulier_NS_canal.h.
Referenced by lire(), and post_traitement_particulier().
w2_moy_temp
DoubleVect Traitement_particulier_NS_canal::w2_moy_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
wv_moy_temp
DoubleVect Traitement_particulier_NS_canal::wv_moy_temp protected
Definition at line 79 of file Traitement_particulier_NS_canal.h.
Y
DoubleVect Traitement_particulier_NS_canal::Y protected
Definition at line 69 of file Traitement_particulier_NS_canal.h.
Referenced by Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), post_traitement_particulier(), preparer_calcul_particulier(), and Traitement_particulier_NS_canal_VDF::remplir_Tab_recap().
Y_tot
DoubleVect Traitement_particulier_NS_canal::Y_tot protected
Definition at line 69 of file Traitement_particulier_NS_canal.h.
Referenced by calcul_reynolds_tau(), ecriture_fichiers_moy_nut(), ecriture_fichiers_moy_Temp(), ecriture_fichiers_moy_Temp_old(), ecriture_fichiers_moy_vitesse_rho_mu(), ecriture_fichiers_moy_vitesse_rho_mu_old(), post_traitement_particulier(), and preparer_calcul_particulier().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_canal.h
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_canal.cpp