TRUST: champ_init_canal_sinal Class Reference
champ_init_canal_sinal Class Reference
#include <champ_init_canal_sinal.h>
Public Member Functions
champ_init_canal_sinal ()
~champ_init_canal_sinal ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Public Member Functions inherited from TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >
Champ_base & affecter (const Champ_base &ch)
DoubleVect & valeur_a (const DoubleVect &, DoubleVect &tab_valeurs) const override
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
double valeur_a_compo (const DoubleVect &x, int ncomp) const override
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
DoubleVect & valeur_a_elem (const DoubleVect &positions, DoubleVect &tab_valeurs, int) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &, int, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &tab_valeurs) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &, DoubleVect &tab_valeurs, int ncomp) const override
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &, DoubleTab &tab_valeurs) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &, DoubleVect &tab_valeurs, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static champ_init_canal_sinal & self_cast (Objet_U &)
static const champ_init_canal_sinal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
double fx (double x) const
double fx (double x, double y) const
double fy (double x, double y) const
double fx (double x, double y, double z) const
double fy (double x, double y, double z) const
double fz (double x, double y, double z) const
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double Ucent = -1.
double h = -1.
double ampli_bruit = -1.
double omega = -1.
double ampli_sin = -1.
int dir_wall = 1
int dir_flow = 0
double min_dir_flow = 0.
double min_dir_wall = 0.
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
Definition at line 21 of file champ_init_canal_sinal.h.
Constructor & Destructor Documentation
champ_init_canal_sinal()
champ_init_canal_sinal::champ_init_canal_sinal ()
Definition at line 19 of file champ_init_canal_sinal.cpp.
~champ_init_canal_sinal()
champ_init_canal_sinal::~champ_init_canal_sinal ()
Definition at line 19 of file champ_init_canal_sinal.cpp.
Member Function Documentation
cree_instance()
Objet_U * champ_init_canal_sinal::cree_instance () static
Definition at line 19 of file champ_init_canal_sinal.cpp.
duplique()
int champ_init_canal_sinal::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file champ_init_canal_sinal.cpp.
fx() [1/3]
double champ_init_canal_sinal::fx (double x) const inline protected
Definition at line 36 of file champ_init_canal_sinal.h.
{ return 0.; }
Referenced by valeur_a(), valeur_a_elem_compo(), valeur_aux(), and valeur_aux_compo().
fx() [2/3]
double champ_init_canal_sinal::fx (double x, double y) const inline protected
Definition at line 38 of file champ_init_canal_sinal.h.
  {
    return Ucent / (h * h) * (y - min_dir_wall) * (2.0 * h - (y - min_dir_wall));
  }
References h, min_dir_wall, and Ucent.
fx() [3/3]
double champ_init_canal_sinal::fx (double x, double y, double z) const inline protected
Definition at line 48 of file champ_init_canal_sinal.h.
  {
    return Ucent / (h * h) * (y - min_dir_wall) * (2.0 * h - (y - min_dir_wall));
  }
References h, min_dir_wall, and Ucent.
fy() [1/2]
double champ_init_canal_sinal::fy (double x, double y) const inline protected
Definition at line 43 of file champ_init_canal_sinal.h.
  {
    return ampli_bruit * (-0.5 + drand48()) + ampli_sin * sin(omega * (x - min_dir_flow));
  }
References ampli_bruit, ampli_sin, min_dir_flow, and omega.
Referenced by valeur_a(), valeur_a_elem_compo(), valeur_aux(), and valeur_aux_compo().
fy() [2/2]
double champ_init_canal_sinal::fy (double x, double y, double z) const inline protected
Definition at line 53 of file champ_init_canal_sinal.h.
  {
    return ampli_bruit * (-0.5 + drand48()) + ampli_sin * sin(omega * (x - min_dir_flow));
  }
References ampli_bruit, ampli_sin, min_dir_flow, and omega.
fz()
double champ_init_canal_sinal::fz (double x, double y, double z) const inline protected
Definition at line 58 of file champ_init_canal_sinal.h.
  {
    return ampli_bruit * (-0.5 + drand48());
  }
References ampli_bruit.
Referenced by valeur_a(), valeur_a_elem_compo(), valeur_aux(), and valeur_aux_compo().
get_info()
const Type_info * champ_init_canal_sinal::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 19 of file champ_init_canal_sinal.cpp.
info()
const Type_info * champ_init_canal_sinal::info () static
Definition at line 19 of file champ_init_canal_sinal.cpp.
printOn()
Sortie & champ_init_canal_sinal::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file champ_init_canal_sinal.cpp.
{ return os; }
readOn()
Entree & champ_init_canal_sinal::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 23 of file champ_init_canal_sinal.cpp.
{
  int dim = lire_dimension(is, que_suis_je());
  dimensionner(1, dim);
  if (abs(dim) > 3)
    {
      Cerr << "Problem while reading the dimension of field champ_init_canal_sinal" << finl;
      Cerr << "Check that it was correctly indicated : dim = " << dim << finl;
      Process::exit();
    }
  ArrOfInt Verif(9);
  Verif[3] = 1;
  Verif[5] = 1;
  Verif[6] = 1;
  Verif[7] = 1;
  Verif[8] = 1;
  Motcles les_mots(9);
  Motcle mot_lu;
  {
    les_mots[0] = "Ucent";
    les_mots[1] = "h";
    les_mots[2] = "ampli_bruit";
    les_mots[3] = "ampli_sin";
    les_mots[4] = "omega";
    les_mots[5] = "dir_flow";
    les_mots[6] = "dir_wall";
    les_mots[7] = "min_dir_flow";
    les_mots[8] = "min_dir_wall";
  }
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  is >> mot_lu;
  if (mot_lu != acc_ouverte)
    {
      Cerr << "Expecting a { instead of " << mot_lu << "while reading intial condition" << finl;
    }
  is >> mot_lu;
  while (mot_lu != acc_fermee)
    {
      int rang = les_mots.search(mot_lu);
      switch(rang)
        {
        case 0:
          is >> Ucent;
          Cerr << "Centerline Longitudinal Velocity = " << Ucent << finl;
// valeur par defaut de ampli_sin = Ucent/10.
          ampli_sin = Ucent / 10.;
          Verif[0] = 1;
          break;
        case 1:
          is >> h;
          Cerr << "Channel Half-height = " << h << finl;
          Verif[1] = 1;
          break;
        case 2:
          is >> ampli_bruit;
          Cerr << "Noise Amplitude = " << ampli_bruit << finl;
          Verif[2] = 1;
          break;
        case 3:
          is >> ampli_sin;
          Cerr << "Sine Perturbation Amplitude = " << ampli_sin << finl;
          Verif[3] = 1;
          break;
        case 4:
          is >> omega;
          Cerr << "Omega = " << omega << finl;
          Verif[4] = 1;
          break;
        case 5:
          is >> dir_flow;
          Cerr << "Flow direction : " << dir_flow << finl;
          Verif[5] = 1;
          break;
        case 6:
          is >> dir_wall;
          Cerr << "The specified Wall direction : " << dir_wall << finl;
          Verif[6] = 1;
          break;
        case 7:
          is >> min_dir_flow;
          Cerr << "Minimum value position in flow direction : " << min_dir_flow << finl;
          Verif[7] = 1;
          break;
        case 8:
          is >> min_dir_wall;
          Cerr << "Minimum value position in wall direction : " << min_dir_wall << finl;
          Verif[8] = 1;
          break;
        default:
          {
            Cerr << "Error in champ_init_canal_sinal::readOn " << finl;
            Cerr << mot_lu << " is not understood by velocity initial condition generation." << finl;
            Cerr << "The understood keywords are : " << les_mots << finl;
            Process::exit();
          }
        }
      is >> mot_lu;
    }
  if (dir_flow == dir_wall)
    {
      Cerr << "Error in champ_init_canal_sinal::readOn " << finl;
      Cerr << "You gave the same direction for a wall and the flow direction : Impossible !" << finl;
      Process::exit();
    }
  if ((dir_wall > 2) || (dir_flow > 2))
    {
      Cerr << "Error in champ_init_canal_sinal::readOn " << finl;
      Cerr << "One of the specified directions are not possible." << finl;
      Cerr << "Use : 0 for X, 1 for Y and 2 for Z !" << finl;
      Process::exit();
    }
  int valmin = min_array(Verif);
  if (valmin == 0)
    {
      for (int i = 0; i < 5; i++)
        if (Verif[i] == 0) Cerr << "You didn't give a value for " << les_mots[i] << finl;
      Cerr << "Error in champ_init_canal_sinal::readOn " << finl;
      Cerr << "User needs to specify values for the parameters below.";
      Cerr << "The syntax is : Ucent val_Ucent   h val_h   ampli_bruit val_ampli_bruit [ampli_sin val_ampli_sin] omega val_omega" << finl;
      Cerr << "dir_flow val_dir_flow   dir_wall val_dir_wall" << finl;
      Process::exit();
    }
  return is;
}
References ampli_bruit, ampli_sin, Cerr, Champ_Don_base::dimensionner(), dir_flow, dir_wall, Process::exit(), finl, h, Champ_Proto::lire_dimension(), min_array(), min_dir_flow, min_dir_wall, omega, Objet_U::que_suis_je(), Motcles::search(), and Ucent.
self_cast() [1/2]
const champ_init_canal_sinal & champ_init_canal_sinal::self_cast (const Objet_U & r) static
Definition at line 19 of file champ_init_canal_sinal.cpp.
self_cast() [2/2]
champ_init_canal_sinal & champ_init_canal_sinal::self_cast (Objet_U & r) static
Definition at line 19 of file champ_init_canal_sinal.cpp.
taille_memoire()
unsigned champ_init_canal_sinal::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file champ_init_canal_sinal.cpp.
valeur_a()
DoubleVect & champ_init_canal_sinal::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const override virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns
reference a "valeurs"
Reimplemented from Champ_base.
Definition at line 155 of file champ_init_canal_sinal.cpp.
{
  Cerr << "values = " << tab_valeurs << finl;
  Cerr << "In champ_init_canal_sinal::valeur_a nb_compo_=" << nb_compo_ << finl;
  tab_valeurs.resize(nb_compo_);
  switch(dimension)
    {
    case (1):
      {
        assert(nb_compo_ == 1);
        tab_valeurs(dir_flow) = fx(positions(dir_flow));
        break;
      }
    case (2):
      {
        assert(nb_compo_ <= 2);
        tab_valeurs(dir_flow) = fx(positions(dir_flow), positions(dir_wall));
        if (nb_compo_ == 2) tab_valeurs(dir_wall) = fy(positions(dir_flow), positions(dir_wall));
        break;
      }
    case (3):
      {
        assert(nb_compo_ <= 3);
        tab_valeurs(dir_flow) = fx(positions(dir_flow), positions(dir_wall), positions(3 - dir_flow - dir_wall));
        if (nb_compo_ >= 2) tab_valeurs(dir_wall) = fy(positions(dir_flow), positions(dir_wall), positions(3 - dir_flow - dir_wall));
        if (nb_compo_ >= 3) tab_valeurs(3 - dir_flow - dir_wall) = fz(positions(dir_flow), positions(dir_wall), positions(3 - dir_flow - dir_wall));
        break;
      }
    }
  return tab_valeurs;
}
References Cerr, Objet_U::dimension, dir_flow, dir_wall, finl, fx(), fy(), fz(), Field_base::nb_compo_, and TRUSTVect< _TYPE_ >::resize().
valeur_a_elem_compo()
double champ_init_canal_sinal::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 187 of file champ_init_canal_sinal.cpp.
{
  double val = 0.;
  switch(dimension)
    {
    case (1):
      val = fx(positions(dir_flow));
      break;
    case (2):
      {
        if (ncomp == 1 + dir_flow) val = fx(positions(dir_flow), positions(dir_wall));
        else val = fy(positions(dir_flow), positions(dir_wall));
      }
      break;
    case (3):
      {
        if (ncomp == 1 + dir_flow) val = fx(positions(dir_flow), positions(dir_wall), positions(3 - dir_flow - dir_wall));
        else if (ncomp == 1 + dir_wall) val = fy(positions(dir_flow), positions(dir_wall), positions(3 - dir_flow - dir_wall));
        else val = fz(positions(dir_flow), positions(dir_wall), positions(3 - dir_flow - dir_wall));
      }
      break;
    default:
      val = -1;
      Process::exit();
      break;
    }
  return val;
}
References Objet_U::dimension, dir_flow, dir_wall, Process::exit(), fx(), fy(), and fz().
valeur_aux()
DoubleTab & champ_init_canal_sinal::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const override virtual
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 216 of file champ_init_canal_sinal.cpp.
{
  assert(tab_valeurs.size_totale() == dimension * positions.dimension(0));
  int i;
  switch(dimension)
    {
    case (1):
      {
        assert(nb_compo_ == 1);
        for (i = 0; i < tab_valeurs.dimension(0); i++)
          tab_valeurs(i, dir_flow) = fx(positions(i, dir_flow));
        break;
      }
    case (2):
      {
        assert(nb_compo_ <= 2);
        for (i = 0; i < tab_valeurs.dimension(0); i++)
          {
            tab_valeurs(i, dir_flow) = fx(positions(i, dir_flow), positions(i, dir_wall));
            if (nb_compo_ == 2) tab_valeurs(i, dir_wall) = fy(positions(i, dir_flow), positions(i, dir_wall));
          }
        break;
      }
    case (3):
      {
        assert(nb_compo_ <= 3);
        for (i = 0; i < tab_valeurs.dimension(0); i++)
          {
            tab_valeurs(i, dir_flow) = fx(positions(i, dir_flow), positions(i, dir_wall), positions(i, 3 - dir_flow - dir_wall));
            if (nb_compo_ >= 2) tab_valeurs(i, dir_wall) = fy(positions(i, dir_flow), positions(i, dir_wall), positions(i, 3 - dir_flow - dir_wall));
            if (nb_compo_ >= 3) tab_valeurs(i, 3 - dir_flow - dir_wall) = fz(positions(i, dir_flow), positions(i, dir_wall), positions(i, 3 - dir_flow - dir_wall));
          }
        break;
      }
    }
  return tab_valeurs;
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, dir_flow, dir_wall, fx(), fy(), fz(), Field_base::nb_compo_, and TRUSTVect< _TYPE_ >::size_totale().
valeur_aux_compo()
DoubleVect & champ_init_canal_sinal::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const override virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns
reference au tableau les_valeurs
Reimplemented from Champ_base.
Definition at line 254 of file champ_init_canal_sinal.cpp.
{
  int nb_pos = positions.dimension(0);
  tab_valeurs.resize(nb_pos);
  assert(ncomp < 3);
  int i;
  switch(dimension)
    {
    case 1:
      {
        for (i = 0; i < nb_pos; i++)
          tab_valeurs(i) = fx(positions(i, dir_flow));
        break;
      }
    case 2:
      {
        if (ncomp == dir_flow)
          for (i = 0; i < nb_pos; i++)
            tab_valeurs(i) = fx(positions(i, dir_flow), positions(i, dir_wall));
        else
          for (i = 0; i < nb_pos; i++)
            tab_valeurs(i) = fy(positions(i, dir_flow), positions(i, dir_wall));
        break;
      }
    case 3:
      {
        if (ncomp == dir_flow)
          for (i = 0; i < nb_pos; i++)
            tab_valeurs(i) = fx(positions(i, dir_flow), positions(i, dir_wall), positions(i, 3 - dir_flow - dir_wall));
        else if (ncomp == dir_wall)
          for (i = 0; i < nb_pos; i++)
            tab_valeurs(i) = fy(positions(i, dir_flow), positions(i, dir_wall), positions(i, 3 - dir_flow - dir_wall));
        else
          for (i = 0; i < nb_pos; i++)
            tab_valeurs(i) = fz(positions(i, dir_flow), positions(i, dir_wall), positions(i, 3 - dir_flow - dir_wall));
        break;
      }
    }
  return tab_valeurs;
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, dir_flow, dir_wall, fx(), fy(), fz(), and TRUSTVect< _TYPE_ >::resize().
Member Data Documentation
ampli_bruit
double champ_init_canal_sinal::ampli_bruit = -1. protected
Definition at line 31 of file champ_init_canal_sinal.h.
Referenced by fy(), fz(), and readOn().
ampli_sin
double champ_init_canal_sinal::ampli_sin = -1. protected
Definition at line 31 of file champ_init_canal_sinal.h.
Referenced by fy(), and readOn().
dir_flow
int champ_init_canal_sinal::dir_flow = 0 protected
Definition at line 33 of file champ_init_canal_sinal.h.
Referenced by readOn(), valeur_a(), valeur_a_elem_compo(), valeur_aux(), and valeur_aux_compo().
dir_wall
int champ_init_canal_sinal::dir_wall = 1 protected
Definition at line 33 of file champ_init_canal_sinal.h.
Referenced by readOn(), valeur_a(), valeur_a_elem_compo(), valeur_aux(), and valeur_aux_compo().
h
double champ_init_canal_sinal::h = -1. protected
Definition at line 31 of file champ_init_canal_sinal.h.
Referenced by fx(), and readOn().
info_obj
const Type_info champ_init_canal_sinal::info_obj static
Definition at line 23 of file champ_init_canal_sinal.h.
min_dir_flow
double champ_init_canal_sinal::min_dir_flow = 0. protected
Definition at line 34 of file champ_init_canal_sinal.h.
Referenced by fy(), and readOn().
min_dir_wall
double champ_init_canal_sinal::min_dir_wall = 0. protected
Definition at line 34 of file champ_init_canal_sinal.h.
Referenced by fx(), and readOn().
omega
double champ_init_canal_sinal::omega = -1. protected
Definition at line 31 of file champ_init_canal_sinal.h.
Referenced by fy(), and readOn().
Ucent
double champ_init_canal_sinal::Ucent = -1. protected
Definition at line 31 of file champ_init_canal_sinal.h.
Referenced by fx(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champs_Don/champ_init_canal_sinal.h
src/Kernel/Champs/Champs_Don/champ_init_canal_sinal.cpp