TRUST: Puissance_Thermique_QC_EF Class Reference
Puissance_Thermique_QC_EF Class Reference
class Puissance_Thermique_QC_EF
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique<br>.SECTION
voir aussi Terme_Puissance_Thermique, Terme_Source_EF_base
#include <Puissance_Thermique_QC_EF.h>
Public Member Functions
~Puissance_Thermique_QC_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Puissance_Thermique_QC_EF ()
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Terme_Puissance_Thermique
void lire_donnees (Entree &, const Equation_base &eqn)
Lit le terme de puissance thermique a partir
d'un flot d'entree et d une equation pour eventuellement
acceder a la discretisation afin de typer la_puissance.
Lit uniquement un champ donne representant la_puissance.
void mettre_a_jour (double temps)
void modify_name_file (Nom &) const
const DoubleTab & puissance_thermique () const
void initialiser_champ_puissance (const Equation_base &eqn)
Public Member Functions inherited from Terme_Source_EF_base
Terme_Source_EF_base ()
~Terme_Source_EF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Terme_Source_EF_base (const Iterateur_Source_EF_base &)
constructeur
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
int impr (Sortie &os) const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Puissance_Thermique_QC_EF & self_cast (Objet_U &)
static const Puissance_Thermique_QC_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Terme_Source_EF_base
static const Type_info * info ()
static Terme_Source_EF_base & self_cast (Objet_U &)
static const Terme_Source_EF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Terme_Source_EF_base
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Champs_compris champs_compris_
Additional Inherited Members
Protected Attributes inherited from Terme_Puissance_Thermique
Champ_Don la_puissance_lu
Champ_Don la_puissance
Protected Attributes inherited from Terme_Source_EF_base
Iterateur_Source_EF iter
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Puissance_Thermique_QC_EF
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique<br>.SECTION
voir aussi Terme_Puissance_Thermique, Terme_Source_EF_base
Definition at line 38 of file Puissance_Thermique_QC_EF.h.
Constructor & Destructor Documentation
~Puissance_Thermique_QC_EF()
Puissance_Thermique_QC_EF::~Puissance_Thermique_QC_EF ()
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
Puissance_Thermique_QC_EF()
Puissance_Thermique_QC_EF::Puissance_Thermique_QC_EF () inline
Definition at line 64 of file Puissance_Thermique_QC_EF.h.
  : Terme_Puissance_Thermique(),Terme_Source_EF_base(It_Sou_EF(Eval_Puiss_Th_QC_EF)())
{
}
Member Function Documentation
associer_pb()
void Puissance_Thermique_QC_EF::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 61 of file Puissance_Thermique_QC_EF.cpp.
{
  const Equation_base& eqn = pb.equation(0);
  eqn.discretisation().nommer_completer_champ_physique(eqn.zone_dis(),"Puissance_volumique","W/m3",la_puissance,pb);
  Eval_Puiss_Th_QC_EF& eval_puis = (Eval_Puiss_Th_QC_EF&) iter.evaluateur();
  eval_puis.associer_puissance(la_puissance);
}
References Eval_Puiss_Th_QC_EF::associer_puissance(), Equation_base::discretisation(), Probleme_base::equation(), Iterateur_Source_EF::evaluateur(), Terme_Source_EF_base::iter, Terme_Puissance_Thermique::la_puissance, Discretisation_base::nommer_completer_champ_physique(), and Equation_base::zone_dis().
associer_zones()
void Puissance_Thermique_QC_EF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) override virtual
Implements Source_base.
Definition at line 48 of file Puissance_Thermique_QC_EF.cpp.
{
  const Zone_EF& zEF = ref_cast(Zone_EF,zone_dis.valeur());
  const Zone_Cl_EF& zclEF = ref_cast(Zone_Cl_EF,zone_cl_dis.valeur());
  iter->associer_zones(zEF, zclEF);
  Eval_Puiss_Th_QC_EF& eval_puis = (Eval_Puiss_Th_QC_EF&) iter.evaluateur();
  eval_puis.associer_zones(zEF, zclEF );
}
References Evaluateur_Source_EF::associer_zones(), Iterateur_Source_EF::evaluateur(), Terme_Source_EF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
cree_instance()
Objet_U * Puissance_Thermique_QC_EF::cree_instance () static
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
duplique()
int Puissance_Thermique_QC_EF::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
get_champ()
const Champ_base & Puissance_Thermique_QC_EF::get_champ (const Motcle & nom) const override virtual
Reimplemented from Source_base.
Definition at line 70 of file Puissance_Thermique_QC_EF.cpp.
{
  try
    {
      return champs_compris_.get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  try
    {
      return Terme_Source_EF_base::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  throw Champs_compris_erreur();
}
References champs_compris_, Champs_compris::get_champ(), and Source_base::get_champ().
get_info()
const Type_info * Puissance_Thermique_QC_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
get_noms_champs_postraitables()
void Puissance_Thermique_QC_EF::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Source_base.
Definition at line 89 of file Puissance_Thermique_QC_EF.cpp.
{
  Terme_Source_EF_base::get_noms_champs_postraitables(nom,opt);
  if (opt==DESCRIPTION)
    Cerr<<"Terme_Puissance_Thermique_QC_EF : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, Source_base::get_noms_champs_postraitables(), and Champs_compris::liste_noms_compris().
info()
const Type_info * Puissance_Thermique_QC_EF::info () static
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
mettre_a_jour()
void Puissance_Thermique_QC_EF::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 48 of file Puissance_Thermique_QC_EF.h.
  {
    Terme_Puissance_Thermique::mettre_a_jour(temps);
  }
References Terme_Puissance_Thermique::mettre_a_jour().
printOn()
Sortie & Puissance_Thermique_QC_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 28 of file Puissance_Thermique_QC_EF.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Puissance_Thermique_QC_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_EF_base.
Definition at line 36 of file Puissance_Thermique_QC_EF.cpp.
{
  const Equation_base& eqn = equation();
  Terme_Puissance_Thermique::lire_donnees(s,eqn);
  champs_compris_.ajoute_champ(la_puissance);
// set_fichier("Puissance_Thermique");
// set_description("Degagement de puissance thermique = Integrale(P*dv)[W]");
  return s;
}
References Champs_compris::ajoute_champ(), champs_compris_, MorEqn::equation(), Terme_Puissance_Thermique::la_puissance, and Terme_Puissance_Thermique::lire_donnees().
self_cast() [1/2]
const Puissance_Thermique_QC_EF & Puissance_Thermique_QC_EF::self_cast (const Objet_U & r) static
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
self_cast() [2/2]
Puissance_Thermique_QC_EF & Puissance_Thermique_QC_EF::self_cast (Objet_U & r) static
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
taille_memoire()
unsigned Puissance_Thermique_QC_EF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Puissance_Thermique_QC_EF.cpp.
Member Data Documentation
champs_compris_
Champs_compris Puissance_Thermique_QC_EF::champs_compris_ private
Definition at line 55 of file Puissance_Thermique_QC_EF.h.
Referenced by get_champ(), get_noms_champs_postraitables(), and readOn().
info_obj
const Type_info Puissance_Thermique_QC_EF::info_obj static
Definition at line 41 of file Puissance_Thermique_QC_EF.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/EF/Puissance_Thermique_QC_EF.h
src/ThHyd/Dilatable/Quasi_Compressible/EF/Puissance_Thermique_QC_EF.cpp