TRUST: Testeur_MEDCoupling Class Reference
Testeur_MEDCoupling Class Reference
: class Testeur_MEDCoupling
For testing conversion from Champ_base to MEDField
#include <Testeur_MEDCoupling.h>
Public Member Functions
Testeur_MEDCoupling ()
~Testeur_MEDCoupling ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Testeur_MEDCoupling & self_cast (Objet_U &)
static const Testeur_MEDCoupling & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
: class Testeur_MEDCoupling
For testing conversion from Champ_base to MEDField
Definition at line 36 of file Testeur_MEDCoupling.h.
Constructor & Destructor Documentation
Testeur_MEDCoupling::Testeur_MEDCoupling ()
Definition at line 30 of file Testeur_MEDCoupling.cpp.
Testeur_MEDCoupling::~Testeur_MEDCoupling ()
Definition at line 30 of file Testeur_MEDCoupling.cpp.
Member Function Documentation
Objet_U * Testeur_MEDCoupling::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
int Testeur_MEDCoupling::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
const Type_info * Testeur_MEDCoupling::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
const Type_info * Testeur_MEDCoupling::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
Entree & Testeur_MEDCoupling::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Definition at line 46 of file Testeur_MEDCoupling.cpp.
References build_medfield(), Cerr, Process::exit(), Probleme_base::findOutputField(), finl, Objet_U::nom_du_cas(), Interprete::objet(), and ref_cast.
{
  Nom nom_pb,nom_champ;
  is >> nom_pb;
  is >> nom_champ;
#ifdef NO_MEDFIELD
  Cerr<<"Version compiled without MEDCoupling"<<finl;
  exit();
#else
  const Probleme_base& pb = ref_cast(Probleme_base,objet(nom_pb));
  const Champ_Generique_base& ch=pb.findOutputField(nom_champ);
  ICoCo::MEDDoubleField medfield=build_medfield(ch);
  medfield.getMCField()->writeVTK(nom_du_cas().getString(),false);
#endif
  return is;
}
Sortie & Testeur_MEDCoupling::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 32 of file Testeur_MEDCoupling.cpp.
{
  Interprete::printOn( os );
  return os;
}
Entree & Testeur_MEDCoupling::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 38 of file Testeur_MEDCoupling.cpp.
{
  Interprete::readOn( is );
  return is;
}
Testeur_MEDCoupling & Testeur_MEDCoupling::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
const Testeur_MEDCoupling & Testeur_MEDCoupling::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
unsigned Testeur_MEDCoupling::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 30 of file Testeur_MEDCoupling.cpp.
Member Data Documentation
const Type_info Testeur_MEDCoupling::info_obj [static]
Reimplemented from Interprete.
Definition at line 39 of file Testeur_MEDCoupling.h.
The documentation for this class was generated from the following files:
src/Kernel/ICoCo/Testeur_MEDCoupling.h
src/Kernel/ICoCo/Testeur_MEDCoupling.cpp