TRUST: TRUSTArray< _TYPE_ > Class Template Reference
TRUSTArray< _TYPE_ > Class Template Reference
Represente un tableau d'elements de type int/double/float.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0 (etat obtenu par le constructeur par defaut, detach_array() et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure VTRUSTdata, data_==p->data_ et size_array_ <= p->size_.
A la destruction du tableau, si p->ref_count_ est nul on libere la memoire. data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs TRUSTArray (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier TRUSTArray a utiliser une zone de memoire la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire n'est pas liberee a la destruction du TRUSTArray.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value". Priere de supposer desormais que les tableaux ne sont pas initialises par defaut.
#include <TRUSTArray.h>
Public Types
using value_type = _TYPE_
return int, double ou float
using Iterator = TRUSTIterator< TRUSTArray< _TYPE_ > >
Public Types inherited from Array_base
enum Resize_Options { NOCOPY_NOINIT = 0 , COPY_NOINIT = 1 , COPY_INIT = 2 }
enum Storage { STANDARD , TEMP_STORAGE }
Public Member Functions
Iterator begin ()
Iterator end ()
virtual ~TRUSTArray ()
TRUSTArray ()
TRUSTArray (int n)
TRUSTArray (const TRUSTArray &A)
void resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void resize_array (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void set_smart_resize (int flag)
void set_mem_storage (const Storage storage)
Storage get_mem_storage () const
TRUSTArray & operator= (const TRUSTArray &)
TRUSTArray & operator= (_TYPE_ x)
_TYPE_ & operator[] (int i)
const _TYPE_ & operator[] (int i) const
!<
_TYPE_ & operator() (int i)
const _TYPE_ & operator() (int i) const
_TYPE_ * addr ()
!<
const _TYPE_ * addr () const
int size_array () const
int ref_count () const
void append_array (_TYPE_ valeur)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & inject_array (const TRUSTArray &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
TRUSTArray & copy_array (const TRUSTArray &a)
void ordonne_array ()
void array_trier_retirer_doublons ()
!<
virtual void ref_data (_TYPE_ *ptr, int size)
virtual void reset ()
virtual void ref_array (TRUSTArray &, int start=0, int sz=-1)
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Protected Member Functions
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &is) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void attach_array (const TRUSTArray &a, int start=0, int size=-1)
void fill_default_value (Array_base::Resize_Options opt, int first, int nb)
void resize_array_ (int n, Array_base::Resize_Options opt=COPY_INIT)
int detach_array ()
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void memory_resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
Private Attributes
VTRUSTdata< _TYPE_ > * p_
_TYPE_ * data_
int size_array_
int memory_size_
int smart_resize_
Storage storage_type_
Additional Inherited Members
Static Public Member Functions inherited from Array_base
static const Type_info * info ()
static Array_base & self_cast (Objet_U &)
static const Array_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Array_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Detailed Description
template<typename _TYPE_>
class TRUSTArray< _TYPE_ >
Represente un tableau d'elements de type int/double/float.
L'etat du tableau est caracterise par la valeur de p_ et de data_ :
* detache : on a alors p_==0, data_==0, size_array_==0 (etat obtenu par le constructeur par defaut, detach_array() et resize_array(0) dans certains cas)
* normal : alors p pointe vers une structure VTRUSTdata, data_==p->data_ et size_array_ <= p->size_.
A la destruction du tableau, si p->ref_count_ est nul on libere la memoire. data_ n'est pas nul.
L'espace memoire du tableau peut etre partage entre plusieurs TRUSTArray (le pointeur "p" pointe alors sur une meme structure).
Ce type de tableau est produit par ref_array().
Le dernier TRUSTArray a utiliser une zone de memoire la detruit lorsqu'il a fini (voir detach_array())
Si smart_resize_==0, alors on a toujours size_array_==p->size_.
* ref_data : p_==0, data_ pointe vers un tableau existant, la memoire n'est pas liberee a la destruction du TRUSTArray.
Ces tableaux sont obtenus par appel a ref_data(...) et peuvent servir pour importer un tableau fourni par une routine exterieure (C ou fortran)
Valeur initiale par defaut : voir "fill_default_value". Priere de supposer desormais que les tableaux ne sont pas initialises par defaut.
Definition at line 40 of file TRUSTArray.h.
Member Typedef Documentation
Iterator
template<typename _TYPE_ > using TRUSTArray< _TYPE_ >::Iterator = TRUSTIterator<TRUSTArray<_TYPE_> >
Definition at line 92 of file TRUSTArray.h.
value_type
template<typename _TYPE_ > using TRUSTArray< _TYPE_ >::value_type = _TYPE_
return int, double ou float
Definition at line 91 of file TRUSTArray.h.
Constructor & Destructor Documentation
~TRUSTArray()
template<typename _TYPE_ > virtual TRUSTArray< _TYPE_ >::~TRUSTArray () inline virtual
< Paranoia: si size_array_==-1, c'est un zombie
Definition at line 98 of file TRUSTArray.h.
  {
    detach_array();
    size_array_ = -1; //!< Paranoia: si size_array_==-1, c'est un zombie
  }
References TRUSTArray< _TYPE_ >::detach_array(), and TRUSTArray< _TYPE_ >::size_array_.
TRUSTArray() [1/3]
template<typename _TYPE_ > TRUSTArray< _TYPE_ >::TRUSTArray () inline
Definition at line 104 of file TRUSTArray.h.
: p_(0), data_(0), size_array_(0), memory_size_(0), smart_resize_(0), storage_type_(STANDARD) { }
Referenced by TRUSTArray< _TYPE_ >::duplique().
TRUSTArray() [2/3]
template<typename _TYPE_ > TRUSTArray< _TYPE_ >::TRUSTArray (int n) inline
Definition at line 106 of file TRUSTArray.h.
                   : p_(0), data_(0), size_array_(n), memory_size_(n), smart_resize_(0), storage_type_(STANDARD)
  {
    if (n)
      {
        p_ = new VTRUSTdata<_TYPE_>(n, STANDARD);
        data_ = p_->get_data();
        fill_default_value(COPY_INIT, 0, n);
      }
  }
References Array_base::COPY_INIT, TRUSTArray< _TYPE_ >::data_, TRUSTArray< _TYPE_ >::fill_default_value(), TRUSTArray< _TYPE_ >::p_, and Array_base::STANDARD.
TRUSTArray() [3/3]
template<typename _TYPE_ > TRUSTArray< _TYPE_ >::TRUSTArray (const TRUSTArray< _TYPE_ > & A) inline
Definition at line 117 of file TRUSTArray.h.
                                  : Array_base()
  {
    const int size = A.size_array();
    if (size > 0)
      {
// Creation d'un tableau "normal"
        storage_type_ = STANDARD;
        p_ = new VTRUSTdata<_TYPE_>(size, STANDARD);
        data_ = p_->get_data();
        size_array_ = size;
        memory_size_ = size;
        smart_resize_ = A.smart_resize_;
        inject_array(A);
      }
    else
      {
// Creation d'un tableau "detache"
        p_ = 0;
        data_ = 0;
        size_array_ = 0;
        memory_size_ = 0;
        smart_resize_ = 0;
        storage_type_ = STANDARD;
      }
  }
References TRUSTArray< _TYPE_ >::data_, TRUSTArray< _TYPE_ >::inject_array(), TRUSTArray< _TYPE_ >::memory_size_, TRUSTArray< _TYPE_ >::p_, TRUSTArray< _TYPE_ >::size_array(), TRUSTArray< _TYPE_ >::size_array_, TRUSTArray< _TYPE_ >::smart_resize_, Array_base::STANDARD, and TRUSTArray< _TYPE_ >::storage_type_.
Member Function Documentation
addr() [1/2]
template<typename _TYPE_ > _TYPE_ * TRUSTArray< _TYPE_ >::addr inline
!<
Returns
const TYPE*
Signification: pointeur sur le premier element du tableau
Definition at line 181 of file TRUSTArray.tpp.
{
  return data_;
}
Referenced by affecte_double_avec_doubletab(), affecte_int_avec_inttab(), ajoute_alpha_v_norme(), ajoute_operation_speciale_generic(), ajoute_produit_scalaire(), TRUSTTab< _TYPE_ >::ajoute_produit_tensoriel(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse::ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Diagonale::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), TRUSTTab< _TYPE_ >::append_line(), TRUSTArray< int >::array_trier_retirer_doublons(), SETS::assembler(), Domaine::buildUFacesMesh(), Fluide_base::calculer_nu(), Scatter::Chercher_Correspondance(), Solv_Cholesky::Cholesky(), interface_INITGAUSS::Compute(), interface_CALCULSI::Compute(), interface_CALCULBIJ::Compute(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Tranche::construire_partition(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Solveur_Masse_base::corriger_solution(), descente_bloc_extradiag_assert(), descente_generique(), Matrice_Morse::diagmulmat(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), disp_da(), disp_dt(), disp_ia(), disp_it(), disp_m(), dotproduct_array(), MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_partie(), DomaineCutter::ecrire_zones(), ecrit(), SETS::eliminer(), envoyer_all_to_all(), exchange_data(), Solv_Cholesky::Fact_Cholesky(), ILU::factoriser(), Zone_PolyMAC_P0::fgrad(), Champ_P1iP1B_implementation::filtrage(), Champ_Generique_Transformation::get_champ(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), get_seq_flags(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), ILU::ilu(), ILU::ilut(), Echange_contact_PolyMAC::init_f_dist(), Champ_implementation_P1::init_from_file(), Echange_contact_PolyMAC_P0::init_fs_dist(), Traduction_Indice_Global_Local::initialiser(), Integrer_champ_med::interpreter(), Decouper_multi::interpreter(), Lire_Ideas::interpreter_(), invalidate_data(), Matrice_Dense::inverse(), Matrice_Morse::inverse(), SolvElem_BiCGStab::iteration(), SolvElem_Gmres::iteration(), kersol(), Matrice_Morse::largeur_de_bande(), Champ_Fonc_MED::lire(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), lire_special(), TRUSTVect< _TYPE_ >::lit(), local_extrema_vect_generic(), local_operations_vect_bis_generic(), local_prodscal(), TRUSTTab< _TYPE_ >::max_du_u(), Chimie::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), mincol1_to_vect_items(), mp_collective_op(), multiply_sub(), Matrice_Morse_Sym::multvect_et_prodscal(), operation01(), operation11(), operation_speciale_tres_generic(), Matrice_Morse::operator()(), operator==(), operator_vect_single_generic(), operator_vect_vect_generic(), Solv_GCP::prepare_data(), TRUSTTab< _TYPE_ >::printOn(), remontee_bloc_extradiag_assert(), remontee_generique(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), remplir_items_non_calcules_(), Matrice_Morse_Sym::renumerote(), Solv_Petsc::resoudre_systeme(), MD_Vector_tools::restore_vector_with_md(), sameDoubleTab(), Champ_Input_Proto::setValueOnTab(), Matrice_Morse::sort_stencil(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_face_local(), traite_diagonale(), tri_lexicographique_tableau(), tri_lexicographique_tableau_indirect(), trier_index_colonne_i(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), vect_blocs_generic(), vect_items_generic(), Vecteur3::Vecteur3(), Debog_Pb::verifier_partie_std(), Format_Post_Lata::write_doubletab(), Format_Post_Lata::write_inttab(), and Zone_VF::xv_bord().
addr() [2/2]
template<typename _TYPE_ > const _TYPE_ * TRUSTArray< _TYPE_ >::addr inline
Definition at line 187 of file TRUSTArray.tpp.
{
  return data_;
}
append_array()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::append_array (_TYPE_ valeur) inline
Definition at line 215 of file TRUSTArray.tpp.
{
  assert(smart_resize_);
  const int n = size_array_;
  resize_array(size_array_+1, COPY_NOINIT);
  data_[n] = valeur;
}
References valeur().
Referenced by Schema_Comm_Vecteurs::add(), CSR_Builder::add_coeff(), Objet_a_lire::add_dict(), MD_Vector_composite::add_part(), Sonde::ajouter_bords(), Scatter::ajouter_joints(), append_global_md(), MD_Vector_base2::append_item_to_blocs(), Polyedre::build_reduced(), Polygone::build_reduced(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Scatter::check_consistancy_remote_items(), Raccord_distant_homogene::completer(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), construire_liste_faces_sous_domaine(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), creer_md_vect_renum(), DomaineCutter::ecrire_zones(), extract_blocs(), Domaine_bord::extraire_domaine_bord(), Octree_Zone::find_elements(), find_matching_coordinates(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Champ_front_recyclage::initialiser(), Create_domain_from_sous_zone::interpreter_(), MD_Vector_std::MD_Vector_std(), Scatter::mergeDomains(), parcourir_epaisseurs_elements(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), Scatter::reordonner_faces_de_joint(), search_connex_components_local(), and Octree_Int::search_elements_box_floor().
array_trier_retirer_doublons()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::array_trier_retirer_doublons inline
!<
< Tri dans l'ordre croissant Retire les doublons (codage optimise en pointeurs)
Definition at line 314 of file TRUSTArray.tpp.
{
  const int size_ = size_array_;
  if (size_ <= 0) return;
  ordonne_array(); //!< Tri dans l'ordre croissant Retire les doublons (codage optimise en pointeurs)
//
  _TYPE_ last_value = *data_;
  _TYPE_ *src = data_ + 1;
  _TYPE_ *dest = data_ + 1;
  for (int i = size_ - 1; i != 0; i--)
    {
      _TYPE_ x = *(src++);
      if (x != last_value)
        {
          *(dest++) = x;
          last_value = x;
        }
    }
  int new_size_ = dest - data_;
  resize_array(new_size_);
}
Referenced by ExtrudeParoi::interpreter_(), and Scatter::mergeDomains().
attach_array()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::attach_array (const TRUSTArray< _TYPE_ > & a, int start = 0, int size = -1) inline protected
Definition at line 348 of file TRUSTArray.tpp.
{
// Le tableau doit etre detache
  assert(data_ == 0 && p_ == 0);
// Le tableau doit etre different de *this
  assert(&m != this);
  if (size < 0) size = m.size_array_ - start;
  assert(start >= 0 && size >=0 && start + size <= m.size_array_);
  if (m.size_array() > 0)
    {
      p_ = m.p_;
      if (p_) p_->add_one_ref();
      data_ = m.data_ + start;
      size_array_ = size;
      memory_size_ = m.memory_size_ - start;
      smart_resize_ = m.smart_resize_;
    }
  else
    {
// Cas particulier ou on attache un tableau de taille nulle: en theorie, c'est pareil qu'un tableau de taille non nulle, MAIS
// dans les operateurs (ex:Op_Dift_VDF_Face_Axi), une ref est construite avant que le tableau ne prenne sa taille definitive. Donc, pour ne pas
// empecher le resize, il ne faut pas attacher le tableau s'il n'a pas encore la bonne taille. Solution propre: reecrire les operateurs pour
// qu'ils ne prennent pas une ref avant que le tableau ne soit valide et faire p_ = m.p_ dans tous les cas.
// Process::Journal() << "Warning TRUSTArray::attach_array(m), m.size_array()==0, on n attache pas le tableau" << finl;
    }
}
References TRUSTArray< _TYPE_ >::data_, TRUSTArray< _TYPE_ >::memory_size_, TRUSTArray< _TYPE_ >::p_, TRUSTArray< _TYPE_ >::size_array(), TRUSTArray< _TYPE_ >::size_array_, and TRUSTArray< _TYPE_ >::smart_resize_.
Referenced by TRUSTVect< int >::ref_array().
begin()
template<typename _TYPE_ > Iterator TRUSTArray< _TYPE_ >::begin () inline
Definition at line 95 of file TRUSTArray.h.
{ return Iterator(data_); }
References TRUSTArray< _TYPE_ >::data_.
copy_array()
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::copy_array (const TRUSTArray< _TYPE_ > & a) inline
Definition at line 241 of file TRUSTArray.h.
  {
    operator=(a);
    return *this;
  }
References TRUSTArray< _TYPE_ >::operator=().
Referenced by Champ_front_contact_VEF::calcul_grads_transf().
detach_array()
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::detach_array inline protected
Returns
int
Signification: 1 si les donnees du tableau ont ete supprimees
Definition at line 443 of file TRUSTArray.tpp.
{
  int retour = 0;
  if (p_)
    {
// Le tableau est de type "normal". Si la zone de memoire n'est plus utilisee par personne, on la detruit.
      if ((p_->suppr_one_ref()) == 0)
        {
          delete p_;
          retour = 1;
        }
      p_ = 0;
    }
  data_ = 0;
  size_array_ = 0;
  memory_size_ = 0;
  return retour;
}
Referenced by TRUSTVect< int >::ref_array(), TRUSTArray< _TYPE_ >::reset(), and TRUSTArray< _TYPE_ >::~TRUSTArray().
duplique()
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::duplique () const inline override protected virtual
Implements Objet_U.
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTrav< _TYPE_ >, TRUSTVect< _TYPE_ >, TRUSTVect< int >, and TRUSTVect< double >.
Definition at line 45 of file TRUSTArray.h.
  {
    TRUSTArray* xxx = new  TRUSTArray(*this);
    if(!xxx)
      {
        Cerr << "Not enough memory " << finl;
        Process::exit();
      }
    return xxx->numero();
  }
References Cerr, Process::exit(), finl, Objet_U::numero(), and TRUSTArray< _TYPE_ >::TRUSTArray().
end()
template<typename _TYPE_ > Iterator TRUSTArray< _TYPE_ >::end () inline
Definition at line 96 of file TRUSTArray.h.
{ return Iterator(data_ + size_array_); }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array_.
fill_default_value()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::fill_default_value (Array_base::Resize_Options opt, int first, int nb) inline protected
< On initialise uniquement en mode debug
< Comportement pour les tableaux normaux : compatibilite avec la version precedente : on initialise avec 0.
Definition at line 394 of file TRUSTArray.tpp.
{
  assert((nb == 0) || (first >= 0 && first < memory_size_));
  assert((nb == 0) || (nb > 0 && nb <= memory_size_ - first));
  _TYPE_ * data = data_;
  assert(data!=0 || nb==0);
  data += first;
  if (opt != COPY_INIT)
    {
#ifndef NDEBUG //!< On initialise uniquement en mode debug
      static const _TYPE_  INVALIDE_ = (std::is_same<_TYPE_,double>::value) ? DMAXFLOAT*0.999 : INT_MIN;
      for (int i = 0; i < nb; i++) data[i] = INVALIDE_;
#endif
    }
  else //!< Comportement pour les tableaux normaux : compatibilite avec la version precedente : on initialise avec 0.
    for (int i = 0; i < nb; i++) data[i] = (_TYPE_) 0;
}
References DMAXFLOAT.
Referenced by TRUSTArray< _TYPE_ >::TRUSTArray().
get_mem_storage()
template<typename _TYPE_ > Storage TRUSTArray< _TYPE_ >::get_mem_storage () const inline
Definition at line 154 of file TRUSTArray.h.
{ return storage_type_; }
References TRUSTArray< _TYPE_ >::storage_type_.
inject_array()
template<typename _TYPE_ > TRUSTArray< _TYPE_ > & TRUSTArray< _TYPE_ >::inject_array (const TRUSTArray< _TYPE_ > & source, int nb_elements = -1, int first_element_dest = 0, int first_element_source = 0) inline
Returns
ArrOfDouble&
Signification: *this
Definition at line 239 of file TRUSTArray.tpp.
{
  assert(&source != this && nb_elements >= -1);
  assert(first_element_dest >= 0 && first_element_source >= 0);
  if (nb_elements < 0) nb_elements = source.size_array();
  assert(first_element_source + nb_elements <= source.size_array());
  assert(first_element_dest + nb_elements <= size_array());
  if (nb_elements > 0)
    {
      _TYPE_ * addr_dest = data_ + first_element_dest;
      const _TYPE_ * addr_source = source.addr() + first_element_source;
// PL: On utilise le memcpy car c'est VRAIMENT plus rapide (10% +vite sur RNR_G20)
      memcpy(addr_dest , addr_source, nb_elements * sizeof(_TYPE_));
      /*
        int i;
        for (i = 0; i < nb_elements; i++) {
        addr_dest[i] = addr_source[i];
        } */
    }
  return *this;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by append_array_to_array(), Eval_Source_C_VEF_Face::calculer_terme_source_non_standard(), Eval_Source_C_VEF_Face::calculer_terme_source_standard(), Zone_VF::construire_face_virt_pe_num(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), TRUSTVect< _TYPE_ >::copy_(), Static_Int_Lists::copy_list_to_array(), envoyer_all_to_all(), ExtrudeParoi::extrude(), Champ_front_recyclage::mettre_a_jour(), multiplier_diviser_rho(), Solv_GCP::prepare_data(), Op_Diff_VEF_base::remplir_nu(), Solv_GCP::resoudre_(), Discret_Thyd::section_passage(), Static_Int_Lists::set(), Static_Int_Lists::set_data(), and TRUSTArray< _TYPE_ >::TRUSTArray().
memory_resize()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::memory_resize (int new_size, Array_base::Resize_Options opt = COPY_INIT) inline private
< La nouvelle taille est nulle, on cree un tableau "detache"
< Destruction de l'ancienne zone (si plus aucune reference)
Definition at line 477 of file TRUSTArray.tpp.
{
  assert(new_size >= 0);
// Si new_size==size_array_, on ne fait rien, c'est toujours autorise
  if (new_size == size_array_) return;
// Sinon, il faut que le resize soit autorise, c'est a dire
// - soit le tableau est detache
// - soit le tableau est normal et il n'y a pas d'autre reference au tableau
  assert((data_ == 0) || ((p_ != 0) && (p_->get_data() == data_) && (ref_count() == 1)));
// Occupation memoire de l'ancien tableau:
  int old_mem_size = memory_size_;
  assert((!p_) || (p_->get_size() == memory_size_));
  assert(memory_size_ >= size_array_);
// Occupation memoire du nouveau tableau : Si smart_resize, on prend au moins deux fois la taille precedente, ou new_size
  int new_mem_size = new_size;
  if (smart_resize_)
    {
      if (new_size <= old_mem_size) new_mem_size = old_mem_size;
      else if (new_size < old_mem_size * 2) new_mem_size = old_mem_size * 2;
      else if (new_size > old_mem_size && old_mem_size > INT_MAX / 2) new_mem_size = INT_MAX;
    }
  if (new_mem_size != old_mem_size)
    {
// detach_array() efface le contenu de size_array_. On le met de cote:
      const int old_size_array = size_array_;
      if (new_mem_size == 0) detach_array(); //!< La nouvelle taille est nulle, on cree un tableau "detache"
      else
        {
// Allocation d'une nouvelle zone
          VTRUSTdata<_TYPE_> * new_p = new VTRUSTdata<_TYPE_>(new_mem_size, storage_type_);
          _TYPE_ * new_data = new_p->get_data();
// Raccourci si le tableau etait "detache", inutile de copier les anciennes donnees. On copie si COPY_OLD est demande
          int copy_size = 0;
          if (data_ != 0)
            {
// Calcul du nombre d'elements a copier vers la nouvelle zone de memoire : c'est le min de l'ancienne et de la nouvelle taille.
              if (opt != NOCOPY_NOINIT)
                {
                  copy_size = size_array_;
                  if (new_size < copy_size) copy_size = new_size;
// Copie des valeurs dans le nouveau tableau
                  for (int i = 0; i < copy_size; i++) new_data[i] = data_[i];
                }
              detach_array(); //!< Destruction de l'ancienne zone (si plus aucune reference)
            }
// On attache la nouvelle zone de memoire
          p_ = new_p;
          data_ = new_data;
          memory_size_ = new_mem_size;
// Initialisation des cases supplementaires avec une valeur par defaut
          fill_default_value(opt, copy_size, new_mem_size - copy_size);
// Restaure l'ancienne valeur de size_array_
          size_array_ = old_size_array;
        }
    }
  else
    {
// Pas de reallocation, initialisation si besoin
      if (opt == COPY_INIT && new_size > size_array_) fill_default_value(opt, size_array_, new_size - size_array_);
    }
}
References VTRUSTdata< _TYPE_ >::get_data().
operator()() [1/2]
template<typename _TYPE_ > _TYPE_ & TRUSTArray< _TYPE_ >::operator() (int i) inline
Definition at line 171 of file TRUSTArray.h.
{ return operator[](i); }
References TRUSTArray< _TYPE_ >::operator[]().
operator()() [2/2]
template<typename _TYPE_ > const _TYPE_ & TRUSTArray< _TYPE_ >::operator() (int i) const inline
Definition at line 172 of file TRUSTArray.h.
{ return operator[](i); }
References TRUSTArray< _TYPE_ >::operator[]().
operator*=()
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator*= (const _TYPE_ dy) inline
Definition at line 223 of file TRUSTArray.h.
  {
    _TYPE_ * data = data_;
    for(int i=0; i < size_array(); i++) data[i] *= dy;
    return *this;
  }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by TRUSTArray< _TYPE_ >::operator/=().
operator+=() [1/2]
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator+= (const _TYPE_ dy) inline
Definition at line 197 of file TRUSTArray.h.
  {
    _TYPE_ * data = data_;
    for(int i = 0; i < size_array(); i++) data[i] += dy;
    return *this;
  }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array().
operator+=() [2/2]
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator+= (const TRUSTArray< _TYPE_ > & y) inline
Definition at line 188 of file TRUSTArray.h.
  {
    assert(size_array()==y.size_array());
    _TYPE_* dx = data_;
    const _TYPE_* dy = y.data_;
    for (int i = 0; i < size_array(); i++) dx[i] += dy[i];
    return *this;
  }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array().
operator-=() [1/2]
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator-= (const _TYPE_ dy) inline
Definition at line 215 of file TRUSTArray.h.
  {
    _TYPE_ * data = data_;
    for(int i = 0; i < size_array(); i++) data[i] -= dy;
    return *this;
  }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array().
operator-=() [2/2]
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator-= (const TRUSTArray< _TYPE_ > & y) inline
Definition at line 205 of file TRUSTArray.h.
  {
    assert(size_array() == y.size_array());
    _TYPE_ * data = data_;
    const _TYPE_ * data_y = y.data_;
    for (int i = 0; i < size_array(); i++) data[i] -= data_y[i];
    return *this;
  }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array().
operator/=()
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator/= (const _TYPE_ dy) inline
Definition at line 231 of file TRUSTArray.h.
  {
    if (std::is_same<_TYPE_,int>::value) throw;
    const _TYPE_ i_dy = 1. / dy;
    operator*=(i_dy);
    return *this;
  }
References TRUSTArray< _TYPE_ >::operator*=().
operator=() [1/2]
template<typename _TYPE_ > TRUSTArray & TRUSTArray< _TYPE_ >::operator= (_TYPE_ x) inline
Definition at line 160 of file TRUSTArray.h.
  {
    const int n = size_array_;
    _TYPE_ *data = data_;
    for (int i = 0; i < n; i++) data[i] = x;
    return *this;
  }
References TRUSTArray< _TYPE_ >::data_, and TRUSTArray< _TYPE_ >::size_array_.
operator=() [2/2]
template<typename _TYPE_ > TRUSTArray< _TYPE_ > & TRUSTArray< _TYPE_ >::operator= (const TRUSTArray< _TYPE_ > & m) inline
Returns
TRUSTArray<TYPE>&
Signification: *this
Definition at line 122 of file TRUSTArray.tpp.
{
  if (&m != this)
    {
      const int new_size = m.size_array();
// On utilise la methode resize_array() qui teste le type derive de l'objet (resize interdit sur un type derive)
      resize_array(new_size, NOCOPY_NOINIT);
      inject_array(m);
    }
  return *this;
}
References TRUSTArray< _TYPE_ >::size_array().
Referenced by TRUSTArray< _TYPE_ >::copy_array(), TRUSTArrayFT< _TYPE_ >::operator=(), and TRUSTVect< _TYPE_ >::operator=().
operator[]() [1/2]
template<typename _TYPE_ > _TYPE_ & TRUSTArray< _TYPE_ >::operator[] (int i) inline
Definition at line 139 of file TRUSTArray.tpp.
{
  assert(i >= 0 && i < size_array_);
  return data_[i];
}
Referenced by TRUSTArray< _TYPE_ >::operator()(), TRUSTTab< _TYPE_ >::operator()(), and TRUSTTab< _TYPE_ >::operator[]().
operator[]() [2/2]
template<typename _TYPE_ > const _TYPE_ & TRUSTArray< _TYPE_ >::operator[] (int i) const inline
!<
Definition at line 160 of file TRUSTArray.tpp.
{
  assert(i >= 0 && i < size_array_);
  return data_[i];
}
ordonne_array()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::ordonne_array () inline
Referenced by array_trier_retirer_doublons(), auto_build_joints(), Scatter::calculer_espace_distant(), Schema_Comm::check_send_recv_pe_list(), Raccord_distant_homogene::completer(), OctreeFloor::construire(), DomaineCutter::construire_elements_distants_ssdom(), Scatter::corriger_espace_distant_elements_perio(), Schema_Comm_Vecteurs::end_init(), Matrice_Morse::get_stencil(), Matrice_Morse_Sym::get_symmetric_stencil(), Remove_elem::recreer_faces(), Remove_elem::remplir_liste(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), reordonner_vdf(), tri_lexicographique_tableau(), Scatter::trier_les_joints(), and Static_Int_Lists::trier_liste().
printOn()
template<typename _TYPE_ > Sortie & TRUSTArray< _TYPE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Array_base.
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTrav< _TYPE_ >, TRUSTVect< _TYPE_ >, TRUSTVect< int >, and TRUSTVect< double >.
Definition at line 56 of file TRUSTArray.h.
  {
    int sz = size_array();
    os << sz << finl;
    if (sz > 0)
      {
        const _TYPE_* v = data_;
        os.put(v,sz,sz);
      }
    return os;
  }
References TRUSTArray< _TYPE_ >::data_, finl, Sortie::put(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by TRUSTVect< _TYPE_ >::ecrit(), and TRUSTVect< _TYPE_ >::printOn().
readOn()
template<typename _TYPE_ > Entree & TRUSTArray< _TYPE_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Array_base.
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTrav< _TYPE_ >, TRUSTVect< _TYPE_ >, TRUSTVect< int >, and TRUSTVect< double >.
Definition at line 68 of file TRUSTArray.h.
  {
    int sz;
    is >> sz;
    if (sz >= 0)
      {
// Appel a la methode sans precondition sur le type derive (car readOn est virtuelle, les autres proprietes seront initialisees correctement)
        resize_array_(sz);
        if (sz > 0)
          {
            _TYPE_* v = data_;
            is.get(v,sz);
          }
      }
    else
      {
        Cerr << "Error in TRUSTArray:readOn : size = " << sz << finl;
        Process::exit();
      }
    return is;
  }
References Cerr, TRUSTArray< _TYPE_ >::data_, Process::exit(), finl, Entree::get(), and TRUSTArray< _TYPE_ >::resize_array_().
Referenced by TRUSTVect< _TYPE_ >::readOn().
ref_array()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::ref_array (TRUSTArray< _TYPE_ > & m, int start = 0, int size = -1) inline virtual
Returns
TRUSTArray<TYPE>&
Signification: *this
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTVect< _TYPE_ >, TRUSTTab< double >, TRUSTVect< double >, TRUSTTab< int >, and TRUSTVect< int >.
Definition at line 106 of file TRUSTArray.tpp.
{
  assert(&m != this);
// La condition 'm n'est pas de type "ref_data"' est necessaire pour attach_array().
  detach_array();
  attach_array(m, start, size);
}
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Champ_implementation_P1::init_from_file(), TRUSTVect< _TYPE_ >::ref_array(), Traduction_Indice_Global_Local::traduire_espace_virtuel(), and Static_Int_Lists::trier_liste().
ref_count()
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::ref_count inline
Returns
int
Signification: ref_count_
Definition at line 204 of file TRUSTArray.tpp.
{
  return p_ ? p_->ref_count() : -1;
}
ref_data()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::ref_data (_TYPE_ * ptr, int size) inline virtual
Returns
TRUSTArray<TYPE>&
Signification: *this
< Pour passer les tests si on resize a la meme taille
Reimplemented in TRUSTVect< _TYPE_ >, TRUSTTab< _TYPE_ >, TRUSTVect< double >, TRUSTTab< double >, TRUSTVect< int >, and TRUSTTab< int >.
Definition at line 87 of file TRUSTArray.tpp.
{
  assert(ptr != 0 || size == 0);
  assert(size >= 0);
  detach_array();
  data_ = ptr;
  size_array_ = size;
  memory_size_ = size; //!< Pour passer les tests si on resize a la meme taille
}
Referenced by Partitionneur_Tranche::construire_partition(), Schema_Comm_Vecteurs::get_next_area_template(), Solv_GCP::prepare_data(), and TRUSTVect< _TYPE_ >::ref_data().
reset()
template<typename _TYPE_ > virtual void TRUSTArray< _TYPE_ >::reset () inline virtual
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTVect< _TYPE_ >, TRUSTVect< int >, and TRUSTVect< double >.
Definition at line 255 of file TRUSTArray.h.
{ detach_array(); }
References TRUSTArray< _TYPE_ >::detach_array().
Referenced by Domaine_bord::extraire_domaine_bord(), Domaine::read_vertices(), Domaine::readOn(), DomaineCutter_Correspondance::reset(), Joint_Items::reset(), Octree_Double::reset(), Octree_Int::reset(), Octree_Zone::reset(), and TRUSTVect< _TYPE_ >::reset().
resize()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::resize (int new_size, Array_base::Resize_Options opt = COPY_INIT) inline
Definition at line 145 of file TRUSTArray.h.
{ resize_array(new_size, opt); }
References TRUSTArray< _TYPE_ >::resize_array().
Referenced by Partitionneur_Tranche::associer_domaine(), Polyedre::compute_virtual_index(), construire_elems_sous_domaine(), MD_Vector_tools::extend(), Extruder::Extruder(), Extruder_en20::Extruder_en20(), Extruder_en3::Extruder_en3(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Nulle::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), init_parts(), Terme_Boussinesq_base::lire_donnees(), Terme_Source_Canal_perio::lire_donnees(), MD_Vector_std::MD_Vector_std(), print_stat(), Champ_Fonc_MED::readOn(), and Terme_Source_Canal_perio::source().
resize_array()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::resize_array (int new_size, Array_base::Resize_Options opt = COPY_INIT) inline
Definition at line 38 of file TRUSTArray.tpp.
{
// Si le tableau change de taille, il doit etre du type TRUSTArray
  assert(new_size == size_array_ || std::string(typeid(*this).name()).find("TRUSTArray") != std::string::npos );
  resize_array_(new_size, opt);
}
Referenced by RTabInt::add(), CSR_Builder::add_coeff(), Op_Conv_VEF_Face::ajouter(), Polyedre::ajouter_elements(), Scatter::ajouter_joints(), append_array_to_array(), append_blocs(), append_global_md(), append_items(), array_calculer_intersection(), array_retirer_elements(), array_smart_allocate(), array_trier_retirer_doublons(), auto_build_joints(), Schema_Comm_Vecteurs::begin_init(), Octree_Int::build(), Octree_Zone::build(), Octree_Int::build_octree_floor(), Octree_Int::build_octree_recursively(), Calcul_integrale_locale::calculer(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), calculer_renum_sans_doublons(), Reordonner_faces_periodiques::check_faces_periodiques(), Reordonner_faces_periodiques::chercher_direction_perio(), Partitionneur_Tranche::chercher_direction_perio(), chercher_elems_voisins_faces(), Periodique::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Op_Conv_Muscl_New_VEF_Face::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Reaction::completer(), Chimie::completer(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), compute_global_connex_components(), Octree_Double::compute_origin_factors(), Assembleur_P_VDF::construire(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_elements_distants_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_sommets_sousdomaine(), Scatter::construire_md_vector(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Tranche::construire_partition(), Zone_VEF_PreP1b::construire_renum_arete_perio(), DomaineCutter::construire_sommets_joints_ssdom(), construit_connectivite_sommet(), Static_Int_Lists::copy_list_to_array(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), Faces_builder::creer_faces_reeles(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), creer_md_vect_renum(), SolvElem_BiCGStab::dimensionne_wks(), SolvElem_Gmres::dimensionne_wks(), Schema_Comm::echange_taille(), Schema_Comm::echange_taille_et_messages(), DomaineCutter::ecrire_zones(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), extract_blocs(), extract_coef_local(), ExtrudeParoi::ExtrudeParoi(), Solv_Cholesky::Fact_Cholesky(), ILU::factoriser(), find_adjacent_elements(), Octree_Zone::find_elements(), find_matching_coordinates(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), MD_Vector_tools::get_sequential_items_flags(), Matrice_Morse::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Zone::init_faces_virt_bord(), Comm_Group::init_group(), Comm_Group::init_group_trio(), init_parts(), init_simple_md_vector(), Raccord_distant_homogene::initialise(), Ch_front_Vortex::initialiser(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Calculer_Moments::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Equation_base::lire_motcle_non_standard(), lire_special(), Assembleur_P_VDF::liste_faces_periodiques(), Op_EF_base::marque_elem(), Zone_VF::marquer_faces_double_contrib(), MD_Vector_std::MD_Vector_std(), Chimie::mettre_a_jour(), mon_construire_correspondance_items_par_coordonnees(), OctreeFloor::OctreeFloor(), parcourir_epaisseurs_elements(), Polyedriser::polyedriser(), Solv_GCP::prepare_data(), OctreeRoot::rang_arete(), OctreeRoot::rang_elem(), OctreeRoot::rang_elem_depuis(), OctreeRoot::rang_elems_sommet(), OctreeRoot::rang_sommet(), Probleme_Couple::readOn(), Sous_Zone::readOn(), Champ_front_contact_VEF::remplir_connect_bords(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), remplir_marqueur_sommet_neumann(), Zone_Cl_EF::remplir_type_elem_Cl(), Matrice_Morse_Sym::renumerote(), Static_Int_Lists::reset(), TRUSTArray< _TYPE_ >::resize(), RTabInt::resize(), reverse_send_recv_pe_list(), RTabInt::RTabInt(), search_connex_components_local(), Octree_Double::search_elements_box(), Octree_Int::search_elements_box(), Octree_Double::search_nodes_close_to(), Static_Int_Lists::set(), Static_Int_Lists::set_list_sizes(), tri_lexicographique_tableau_indirect(), trier(), trier_abs(), TRUSTArrayFT< _TYPE_ >::TRUSTArrayFT(), and Matrice_Sym::unsymmetrize_stencil_and_coefficients().
resize_array_()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::resize_array_ (int n, Array_base::Resize_Options opt = COPY_INIT) inline protected
Definition at line 415 of file TRUSTArray.tpp.
{
  assert(new_size >= 0);
// Soit le tableau est detache (data_==0), soit il est normal (p_!=0)
// S'il est normal, il ne faut pas qu'il y ait d'autre reference au tableau, ou alors la taille ne doit pas changer.
  assert(new_size == size_array_ || data_ == 0 || (p_ != 0 && ref_count() == 1));
// Le seul cas ou on n'appelle pas memory_resize est le suivant : e tableau est smart_resize
// ET la taille reste inferieure ou egale a la taille allouee ET on ne veut pas initialiser les nouvelles cases
  if ((opt == COPY_INIT) || (new_size > memory_size_) || (smart_resize_ == 0))
// attention, il existe un cas ou memory_resize realloue un buffer meme si size_array_== new_size:
// si on est passe de smart_resize=1 a smart_resize=0, on realloue juste ce qu'il faut.
    memory_resize(new_size, opt);
  size_array_ = new_size;
}
Referenced by TRUSTVect< _TYPE_ >::copy_(), TRUSTArray< _TYPE_ >::readOn(), and TRUSTVect< _TYPE_ >::resize_vect_().
resize_tab()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) inline virtual
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTVect< _TYPE_ >, TRUSTVect< int >, and TRUSTVect< double >.
Definition at line 50 of file TRUSTArray.tpp.
{
  resize_array(n, opt);
}
Referenced by Zone::chercher_elements(), and Champ_front_recyclage::initialiser().
set_mem_storage()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::set_mem_storage (const Storage storage) inline
Definition at line 70 of file TRUSTArray.tpp.
{
  storage_type_ = storage;
}
Referenced by TRUSTTrav< _TYPE_ >::TRUSTTrav().
set_smart_resize()
template<typename _TYPE_ > void TRUSTArray< _TYPE_ >::set_smart_resize (int flag) inline
Definition at line 58 of file TRUSTArray.tpp.
{
  assert(flag == 0 || flag == 1);
  smart_resize_ = flag;
}
Referenced by Objet_a_lire::add_dict(), MD_Vector_composite::add_part(), Debog_Pb::add_renum_item(), Domaine::ajouter(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Op_Div_PolyMAC::ajouter_blocs(), Op_Grad_PolyMAC_Face::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Sonde::ajouter_bords(), Polyedre::ajouter_elements(), Scatter::ajouter_joints(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), append_global_md(), array_smart_allocate(), SETS::assembler(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Octree_Int::build(), build_edges(), build_frontier(), Polyedre::build_reduced(), Polygone::build_reduced(), Ch_front_input::buildSommetsFaces(), Calcul_integrale_locale::Calcul_integrale_locale(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Scatter::calculer_renum_items_communs(), calculer_renum_sans_doublons(), Scatter::check_consistancy_remote_items(), Raccord_distant_homogene::completer(), compute_global_connex_components(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), Scatter::construire_md_vector(), Partitionneur_Tranche::construire_partition(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), Faces_builder::creer_faces_reeles(), creer_md_vect_renum(), Op_Div_PolyMAC_P0::dimensionner(), Op_VDF_Elem::dimensionner_bloc_vitesse(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Diff_PolyMAC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Assembleur_P_PolyMAC::dimensionner_continuite(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Schema_Comm::echange_taille(), DomaineCutter::ecrire_zones(), SETS::eliminer(), Matrix_tools::extend_matrix_stencil(), extract_blocs(), Domaine_bord::extraire_domaine_bord(), Zone_PolyMAC_P0::fgrad(), find_joint_faces(), find_matching_coordinates(), Matrice_Dense::get_stencil(), Matrice_Morse::get_stencil(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Champ_implementation_P1::init_from_file(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Zone_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Traduction_Indice_Global_Local::initialiser(), Champ_front_recyclage::initialiser(), Create_domain_from_sous_zone::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Zone_VEF_PreP1b::lecture_ok_arete(), lire_special(), MD_Vector_std::MD_Vector_std(), Scatter::mergeDomains(), Champ_front_recyclage::mettre_a_jour(), Zone_PolyMAC::orthocentrer(), parcourir_epaisseurs_elements(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), Scatter::reordonner_faces_de_joint(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), Schema_Comm::Schema_Comm(), Schema_Comm_Vecteurs::Schema_Comm_Vecteurs(), search_connex_components_local(), TRUSTArrayFT< _TYPE_ >::TRUSTArrayFT(), and TRUSTTabFT< _TYPE_ >::TRUSTTabFT().
size_array()
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::size_array inline
Definition at line 195 of file TRUSTArray.tpp.
{
  return size_array_;
}
Referenced by Schema_Comm_Vecteurs::add(), RTabInt::add(), CSR_Builder::add_coeff(), Debog_Pb::add_renum_item(), Matrix_tools::add_scaled_matrices(), add_sommets_communs(), Matrix_tools::add_symmetric_scaled_matrices(), Polygone::affecte_connectivite_numero_global(), Polyedre::affecte_connectivite_numero_global(), affecte_double_avec_doubletab(), affecte_int_avec_inttab(), ajoute_operation_speciale_generic(), ajoute_produit_scalaire(), TRUSTTab< _TYPE_ >::ajoute_produit_tensoriel(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Op_Conv_VEF_Face::ajouter(), Domaine::ajouter(), Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Polyedre::ajouter_elements(), Scatter::ajouter_joints(), ajouter_joints(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Morse::ajouter_multvect_(), Matrice_Bloc::ajouter_multvect_(), Matrice_Dense::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Morse::ajouter_multvectT_(), Matrice_Bloc::ajouter_multvectT_(), Matrice_Dense::ajouter_multvectT_(), Faces_builder::ajouter_une_face(), append_array_to_array(), append_blocs(), append_global_md(), MD_Vector_base2::append_item_to_blocs(), append_items(), array_bsearch(), array_calculer_intersection(), array_retirer_doublons(), array_retirer_elements(), array_trier_retirer_doublons(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), TRUSTArray< _TYPE_ >::attach_array(), auto_build_joints(), Schema_Comm_Vecteurs::begin_comm(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Octree_Int::build(), Refine_Mesh::build_edges(), build_frontier(), Matrix_tools::build_morse_matrix(), Octree_Int::build_octree_floor(), Octree_Int::build_octree_recursively(), Polyedre::build_reduced(), Polygone::build_reduced(), Matrix_tools::build_symmetric_morse_matrix(), Reaction::calcul_proportion_implicite(), Calcul_integrale_locale::calculer(), Zone_EF::calculer_Bij(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Scatter::calculer_nb_items_virtuels(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_Face::calculer_pour_post(), Scatter::calculer_renum_items_communs(), calculer_renum_sans_doublons(), Op_Conv_EF_VEF_P1NC_Stab::calculer_senseur(), Op_Conv_Muscl_New_VEF_Face::calculer_senseur_v1(), Eval_Puiss_Th_QC_VDF_Elem::calculer_terme_source(), calculer_vecteur_2faces(), Zone_EF::calculer_volumes_sommets(), Schema_Comm_Vecteurs::check_buffers_full(), Scatter::check_consistancy_remote_items(), Faces_builder::check_erreur_faces(), check_espace_virtuel_vect(), check_index_data(), Schema_Comm_Vecteurs::check_next_area(), check_PE_in_list(), Schema_Comm::check_send_recv_pe_list(), Scatter::Chercher_Correspondance(), Zone::chercher_elements(), chercher_elems_voisins_faces(), Matrice_Morse_Sym::compacte(), Raccord_distant_homogene::completer(), Periodique::completer(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), compute_global_connex_components(), compute_graph_connex_components(), Polyedre::compute_virtual_index(), Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Octree::construire(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_elements_distants_ssdom(), construire_elems_sous_domaine(), DomaineCutter::construire_faces_joints_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), construire_liste_faces_sous_domaine(), construire_liste_sommets_sousdomaine(), Scatter::construire_md_vector(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Tranche::construire_partition(), Partitionneur_Union::construire_partition(), Zone_VEF_PreP1b::construire_renum_arete_perio(), DomaineCutter::construire_sommets_joints_ssdom(), Hexaedre::contient(), Hexaedre_axi::contient(), Hexaedre_VEF::contient(), Point::contient(), Prisme::contient(), Quadrangle_VEF::contient(), Rectangle::contient(), Rectangle_axi::contient(), Segment::contient(), Tetraedre::contient(), Triangle::contient(), TRUSTVect< _TYPE_ >::copy(), TRUSTVect< int >::copy_(), TRUSTVect< _TYPE_ >::copy_(), corriger(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), PE_Groups::create_group(), create_listb_geom(), create_listb_naif(), Zone::creer_aretes(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_internes(), Zone_EF::creer_faces_virtuelles_non_std(), Zone_VEF::creer_faces_virtuelles_non_std(), creer_md_vect_renum(), MD_Vector_tools::creer_md_vect_renum_auto(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), descente_bloc_extradiag_assert(), descente_generique(), Matrice_Morse::diagmulmat(), Op_EF_base::dimensionner(), Matrice_Morse::dimensionner(), disp_da(), disp_ia(), dotproduct_array(), dotproduct_array_fois_inverse_quantitee_entrelacee(), dump_lata(), MD_Vector_tools::dump_vector_with_md(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::echange_taille_et_messages(), Decouper::ecrire(), Debog_Pb::ecrire_partie(), DomaineCutter::ecrire_zones(), Op_EF_base::elem_contribue(), SETS::eliminer(), Schema_Comm::end_comm(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), est_un_coin(), Moyenne_volumique::eval_filtre(), Schema_Comm_Vecteurs::exchange(), exchange_data(), exemple_champ_non_homogene(), Equation_base::expression_residu(), MD_Vector_tools::extend(), extract_blocs(), Reaction::extract_coef(), find_adjacent_elements(), find_cl_face(), Refine_Mesh::find_edge(), Octree_Zone::find_elements(), find_in_array(), find_joint_faces(), find_matching_coordinates(), Turbulence_paroi_base::get_champ(), Static_Int_Lists::get_nb_lists(), get_seq_flags(), Matrice_Morse::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), Polyedre::get_tab_faces_sommets_locaux(), gmres_local(), imax_array(), imin_array(), Navier_Stokes_std::impr(), Equation_base::imprime_residu(), Sonde::init_bords(), Champ_implementation_P1::init_from_file(), Comm_Group::init_group(), Comm_Group_Noparallel::init_group(), init_parts(), Raccord_distant_homogene::initialise(), Sonde::initialiser(), Partitionneur_Tranche::initialiser(), DomaineCutter::initialiser(), Traduction_Indice_Global_Local::initialiser(), Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_recyclage::initialiser(), MD_Vector_std::initialize_comm_template(), TRUSTArray< _TYPE_ >::inject_array(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), Create_domain_from_sous_zone::interpreter_(), DecoupeBord::interpreter_(), Extraire_plan::interpreter_(), ExtrudeParoi::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), invalidate_data(), inverse(), TRUSTTab< _TYPE_ >::inverse_LU(), Probleme_Couple::iterateTimeStep(), Zone_VEF_PreP1b::lecture_ok_arete(), Champ_Fonc_MED::lire(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), lire_special(), Perte_Charge_Singuliere::lire_surfaces(), TRUSTTab< _TYPE_ >::lit(), local_carre_norme_tab(), local_extrema_vect_generic(), local_max_abs_tab(), local_operations_vect_bis_generic(), local_prodscal(), max_abs_array(), max_array(), TRUSTTab< _TYPE_ >::max_du_u(), MD_Vector_std::MD_Vector_std(), meme_point(), Scatter::mergeDomains(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Op_Dift_EF_base::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Terme_Boussinesq_base::mettre_a_jour(), Op_Dift_VEF_base::mettre_a_jour(), Sonde::mettre_a_jour_bords(), min_abs_array(), min_array(), mincol1_to_vect_items(), Zone_Cl_EF::modifie_gradient(), Zone_VEF_PreP1b::modifier_pour_Cl(), mon_construire_correspondance_items_par_coordonnees(), mp_collective_op(), mp_norme_tab(), multiplie(), Front_VF::nb_faces_tot(), Frontiere::nb_faces_virt(), next(), norme_array(), Front_VF::num_local_face(), operation_speciale_tres_generic(), TRUSTTab< _TYPE_ >::operator()(), TRUSTArray< _TYPE_ >::operator*=(), TRUSTArray< _TYPE_ >::operator+=(), TRUSTArray< _TYPE_ >::operator-=(), TRUSTArray< _TYPE_ >::operator=(), TRUSTTab< _TYPE_ >::operator=(), operator==(), operator_vect_single_generic(), operator_vect_vect_generic(), parcourir_epaisseurs_elements(), Solv_GCP::prepare_data(), MD_Vector_std::prepare_send_data_template(), TRUSTArray< _TYPE_ >::printOn(), TRUSTTab< _TYPE_ >::printOn(), MD_Vector_std::process_recv_data_template(), OctreeFloor::rang_elem_depuis_loc(), OctreeFloor::rang_elem_loc(), Objet_a_lire::read(), Champ_input_P0::readOn(), Ch_input_uniforme::readOn(), Loi_horaire::readOn(), MD_Vector_std::readOn(), RTabInt::readOn(), Champ_Fonc_MED::readOn(), Pbc_MED::readOn(), TRUSTTab< _TYPE_ >::readOn(), TRUSTVect< _TYPE_ >::readOn(), TRUSTTab< _TYPE_ >::ref_array(), TRUSTVect< _TYPE_ >::ref_array(), Raffiner_Simplexes::refine_domain(), remontee_bloc_extradiag_assert(), remontee_generique(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), remplir_coordsommets_sous_domaine(), remplir_items_non_calcules_(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Zone::renum_joint_common_items(), Matrice_Morse_Sym::renumerote(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), Scatter::reordonner_faces_de_joint(), reordonner_vdf(), Precond_local::res_syst_loc_hybride(), TRUSTTab< _TYPE_ >::resize(), RTabInt::resize(), Solv_Petsc::resoudre_systeme(), Comm_Group_Noparallel::reverse_send_recv_list(), reverse_send_recv_pe_list(), sameDoubleTab(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), search_connex_components_local(), Octree_Double::search_elements_box(), Octree_Int::search_elements_box(), Octree_Double::search_nodes_close_to(), Zone_VF::section_passage_face(), Comm_Group_MPI::send_recv_start(), Comm_Group_Noparallel::send_recv_start(), Static_Int_Lists::set(), Static_Int_Lists::set_data(), Static_Int_Lists::set_list_sizes(), TRUSTVect< _TYPE_ >::set_md_vector(), TRUSTVect< _TYPE_ >::size_totale(), Solv_Gen::solve(), sort(), tab_divide_any_shape(), tab_multiply_any_shape(), OctreeFloor::taille(), test_solveur(), test_un_solveur(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_som_local(), Traduction_Indice_Global_Local::traduire_indice_global_vers_local(), tri_lexicographique_tableau_indirect(), trier(), trier_abs(), trier_index_colonne_i(), Static_Int_Lists::trier_liste(), TRUSTArray< _TYPE_ >::TRUSTArray(), TRUSTTrav< _TYPE_ >::TRUSTTrav(), Matrice_Sym::unsymmetrize_stencil_and_coefficients(), Schema_Temps_base::update_critere_statio(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), vect_blocs_generic(), vect_items_generic(), Zone_VEF_PreP1b::verifie_ok_arete(), Loi_horaire::verifier_derivee(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Debog_Pb::verifier_gen(), and Verifier_Qualite_Raffinements::verifier_qualite_raffinements().
taille_memoire()
template<typename _TYPE_ > unsigned TRUSTArray< _TYPE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
Reimplemented in TRUSTTab< _TYPE_ >, TRUSTTab< int >, TRUSTTab< double >, TRUSTTrav< _TYPE_ >, TRUSTVect< _TYPE_ >, TRUSTVect< int >, and TRUSTVect< double >.
Definition at line 43 of file TRUSTArray.h.
{ return sizeof(TRUSTArray<_TYPE_>); }
Member Data Documentation
data_
template<typename _TYPE_ > _TYPE_* TRUSTArray< _TYPE_ >::data_ private
Definition at line 276 of file TRUSTArray.h.
Referenced by TRUSTArray< _TYPE_ >::attach_array(), TRUSTArray< _TYPE_ >::begin(), TRUSTArray< _TYPE_ >::end(), TRUSTArray< _TYPE_ >::operator*=(), TRUSTArray< _TYPE_ >::operator+=(), TRUSTArray< _TYPE_ >::operator-=(), TRUSTArray< _TYPE_ >::operator=(), TRUSTArray< int >::operator[](), TRUSTArray< _TYPE_ >::printOn(), TRUSTArray< _TYPE_ >::readOn(), and TRUSTArray< _TYPE_ >::TRUSTArray().
memory_size_
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::memory_size_ private
Definition at line 282 of file TRUSTArray.h.
Referenced by TRUSTArray< _TYPE_ >::attach_array(), and TRUSTArray< _TYPE_ >::TRUSTArray().
p_
template<typename _TYPE_ > VTRUSTdata<_TYPE_>* TRUSTArray< _TYPE_ >::p_ private
Definition at line 272 of file TRUSTArray.h.
Referenced by TRUSTArray< _TYPE_ >::attach_array(), and TRUSTArray< _TYPE_ >::TRUSTArray().
size_array_
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::size_array_ private
Definition at line 279 of file TRUSTArray.h.
Referenced by TRUSTArray< _TYPE_ >::attach_array(), TRUSTArray< _TYPE_ >::end(), TRUSTArray< _TYPE_ >::operator=(), TRUSTArray< int >::operator[](), TRUSTArray< _TYPE_ >::TRUSTArray(), and TRUSTArray< _TYPE_ >::~TRUSTArray().
smart_resize_
template<typename _TYPE_ > int TRUSTArray< _TYPE_ >::smart_resize_ private
Definition at line 286 of file TRUSTArray.h.
Referenced by TRUSTArray< _TYPE_ >::attach_array(), and TRUSTArray< _TYPE_ >::TRUSTArray().
storage_type_
template<typename _TYPE_ > Storage TRUSTArray< _TYPE_ >::storage_type_ private
Definition at line 289 of file TRUSTArray.h.
Referenced by TRUSTArray< _TYPE_ >::get_mem_storage(), and TRUSTArray< _TYPE_ >::TRUSTArray().
The documentation for this class was generated from the following files:
src/Kernel/Math/TRUSTArray.h
src/Kernel/Math/TRUSTArray.tpp