TRUST: Iterateur_Source_VEF_base Class Reference
Iterateur_Source_VEF_base Class Reference
#include <Iterateur_Source_VEF_base.h>
Public Member Functions
Iterateur_Source_VEF_base ()
~Iterateur_Source_VEF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zones (const Zone_VEF &, const Zone_Cl_VEF &)
void associer (const Source_base &source)
virtual DoubleTab & ajouter (DoubleTab &) const =0
virtual DoubleTab & calculer (DoubleTab &) const =0
virtual Evaluateur_Source_VEF & evaluateur ()=0
virtual void completer_ ()=0
virtual int initialiser (double tps)=0
virtual int equation_divisee_par_rho () const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Iterateur_Source_VEF_base & self_cast (Objet_U &)
static const
Iterateur_Source_VEF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zcl
Ref_Source_base so_base
Detailed Description
Definition at line 42 of file Iterateur_Source_VEF_base.h.
Constructor & Destructor Documentation
Iterateur_Source_VEF_base::Iterateur_Source_VEF_base ()
Definition at line 25 of file Iterateur_Source_VEF_base.cpp.
Iterateur_Source_VEF_base::~Iterateur_Source_VEF_base ()
Definition at line 25 of file Iterateur_Source_VEF_base.cpp.
Member Function Documentation
virtual DoubleTab& Iterateur_Source_VEF_base::ajouter (DoubleTab &) const [pure virtual]
Implemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Referenced by Iterateur_Source_VEF::ajouter().
void Iterateur_Source_VEF_base::associer (const Source_base & source) [inline]
Definition at line 74 of file Iterateur_Source_VEF_base.h.
References so_base.
Referenced by Iterateur_Source_VEF::associer().
{
  so_base = source;
}
void Iterateur_Source_VEF_base::associer_zones (const Zone_VEF & zone_VEF, const Zone_Cl_VEF & zone_cl_VEF)
Definition at line 48 of file Iterateur_Source_VEF_base.cpp.
References la_zcl, and la_zone.
{
  la_zone = zone_VEF;
  la_zcl = zone_cl_VEF;
}
virtual DoubleTab& Iterateur_Source_VEF_base::calculer (DoubleTab &) const [pure virtual]
Implemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Referenced by Iterateur_Source_VEF::calculer().
virtual void Iterateur_Source_VEF_base::completer_ () [pure virtual]
Implemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Referenced by Iterateur_Source_VEF::completer_().
virtual int Iterateur_Source_VEF_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
int Iterateur_Source_VEF_base::equation_divisee_par_rho () const [inline, virtual]
Definition at line 65 of file Iterateur_Source_VEF_base.h.
References Nom::debute_par(), and Objet_U::que_suis_je().
{
  Nom nom_eqn=la_zcl->equation().que_suis_je();
  if (nom_eqn.debute_par("Navier_Stokes"))
    return 1;
  else
    return 0;
}
virtual Evaluateur_Source_VEF& Iterateur_Source_VEF_base::evaluateur () [pure virtual]
Implemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Referenced by Iterateur_Source_VEF::evaluateur().
const Type_info * Iterateur_Source_VEF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 25 of file Iterateur_Source_VEF_base.cpp.
const Type_info * Iterateur_Source_VEF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 25 of file Iterateur_Source_VEF_base.cpp.
virtual int Iterateur_Source_VEF_base::initialiser (double tps) [pure virtual]
Implemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Referenced by Terme_Source_VEF_base::initialiser().
Sortie & Iterateur_Source_VEF_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 30 of file Iterateur_Source_VEF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Iterateur_Source_VEF_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 38 of file Iterateur_Source_VEF_base.cpp.
{
  return s ;
}
const Iterateur_Source_VEF_base & Iterateur_Source_VEF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 25 of file Iterateur_Source_VEF_base.cpp.
Iterateur_Source_VEF_base & Iterateur_Source_VEF_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 25 of file Iterateur_Source_VEF_base.cpp.
Member Data Documentation
const Type_info Iterateur_Source_VEF_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_VEF_FaceEval_Puiss_Th_QC_VEF_Face, Iterateur_Source_VEF_FaceEval_Darcy_VEF_Face, Iterateur_Source_VEF_FaceEval_Dirac_VEF_Face, Iterateur_Source_VEF_FaceEval_Forchheimer_VEF_Face, Iterateur_Source_VEF_FaceEval_Puiss_Th_VEF_Face, and Iterateur_Source_VEF_FaceEval_Source_C_VEF_Face.
Definition at line 45 of file Iterateur_Source_VEF_base.h.
Ref_Zone_Cl_VEF Iterateur_Source_VEF_base::la_zcl [protected]
Definition at line 61 of file Iterateur_Source_VEF_base.h.
Referenced by associer_zones().
Ref_Zone_VEF Iterateur_Source_VEF_base::la_zone [protected]
Definition at line 60 of file Iterateur_Source_VEF_base.h.
Referenced by associer_zones().
Ref_Source_base Iterateur_Source_VEF_base::so_base [protected]
Definition at line 62 of file Iterateur_Source_VEF_base.h.
Referenced by associer().
The documentation for this class was generated from the following files:
src/VEF/Sources/Iterateurs/Iterateur_Source_VEF_base.h
src/VEF/Sources/Iterateurs/Iterateur_Source_VEF_base.cpp