TRUST: Precond_local Class Reference
Precond_local Class Reference
#include <Precond_local.h>
Public Member Functions
Precond_local ()
~Precond_local ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Precond_base
~Precond_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Precond_base ()
void reinit (Init_Status x=REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
void set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
void prepare (const Matrice_Base &, const DoubleVect &src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
virtual int supporte_matrice_morse_sym ()
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Init_Status get_status ()
virtual int get_flag_updated_input () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Precond_local & self_cast (Objet_U &)
static const Precond_local & self_cast (const Objet_U &)
Static Public Member Functions inherited from Precond_base
static const Type_info * info ()
static Precond_base & self_cast (Objet_U &)
static const Precond_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Precond_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void prepare_ (const Matrice_Base &, const DoubleVect &) override
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
int preconditionner_ (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int precond (const Matrice_Base &, const DoubleVect &, DoubleVect &)
void res_syst_loc_simple (const Matrice_Morse_Sym &mat, const DoubleVect &secmem, DoubleVect &solution, const Champ_Inc_base &champ)
void res_syst_loc_hybride (const Matrice_Morse_Sym &mat, const DoubleVect &secmem, DoubleVect &solution, const Champ_Inc_base &champ)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)=0
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
SolveurSys le_precond_local_
Matrice_Morse_Sym la_matrice_locale_
Matrice_Morse_Sym matrice_de_travail_
Ref_Matrice_Base matrice_a_resoudre_
Protected Attributes inherited from Precond_base
int echange_ev_solution_
Additional Inherited Members
Public Types inherited from Precond_base
enum Init_Status { READY = 0 , REINIT_COEFF = 1 , REINIT_ALL = 2 }
Detailed Description
Definition at line 24 of file Precond_local.h.
Constructor & Destructor Documentation
Precond_local()
Precond_local::Precond_local ()
Definition at line 19 of file Precond_local.cpp.
~Precond_local()
Precond_local::~Precond_local ()
Definition at line 19 of file Precond_local.cpp.
Member Function Documentation
cree_instance()
Objet_U * Precond_local::cree_instance () static
Definition at line 19 of file Precond_local.cpp.
duplique()
int Precond_local::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Precond_local.cpp.
get_info()
const Type_info * Precond_local::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Precond_base.
Definition at line 19 of file Precond_local.cpp.
info()
const Type_info * Precond_local::info () static
Definition at line 19 of file Precond_local.cpp.
precond()
int Precond_local::precond (const Matrice_Base & mat, const DoubleVect & secmem, DoubleVect & solution) protected
Definition at line 85 of file Precond_local.cpp.
{
  if(Process::nproc()>1)
    {
      Cerr << "Precond_local::precond not coded for nproc > 1" << finl;
      exit();
#if 0
      VECT(Descripteur)& desc = solution.structure().descripteur();
      int nb_struct = desc.size();
      if(nb_struct==1)
        res_syst_loc_simple(mat,secmem,solution,champ);
      else if (nb_struct==2)
        res_syst_loc_hybride(mat,secmem,solution,champ);
      else
        {
          Cerr << "Cases still not supported in Precond_local::preconditionner." << finl;
// PL: Il suffit de generaliser res_syst_loc_hybride comme dans NP une
// taille nb_struct quelconque...pour supporter P0+P1+Pa (pas le temps de le faire).
          exit();
        }
#endif
      return 0;
    }
  else
    {
      /*
        if (ref_champ_inc_.non_nul())
        return le_precond_local_.resoudre_systeme(mat,secmem,solution,ref_champ_inc_.valeur());
        else
      */
      return le_precond_local_.resoudre_systeme(mat,secmem,solution);
    }
}
References Cerr, Process::exit(), finl, le_precond_local_, Process::nproc(), res_syst_loc_hybride(), res_syst_loc_simple(), SolveurSys::resoudre_systeme(), TRUSTVect< _TYPE_ >::size(), and VECT.
Referenced by preconditionner_().
preconditionner_()
int Precond_local::preconditionner_ (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override protected virtual
Implements Precond_base.
Definition at line 76 of file Precond_local.cpp.
{
  const Matrice_Base& m = matrice_a_resoudre_.valeur();
  int ok = precond(m, secmem, solution);
  return ok;
}
References matrice_a_resoudre_, precond(), and Ref_Matrice_Base::valeur().
prepare_()
void Precond_local::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
Definition at line 36 of file Precond_local.cpp.
{
  le_precond_local_.valeur().reinit();
  if(sub_type(Matrice_Bloc_Sym,la_matrice))
    {
      const Matrice_Bloc_Sym& m = ref_cast(Matrice_Bloc_Sym, la_matrice);
      m.BlocSymToMatMorseSym(matrice_de_travail_);
// La matrice est t'elle definie ? On regarde son bloc(0,0)
      const Matrice_Bloc&       bloc     = ref_cast(Matrice_Bloc, m.get_bloc(0,0).valeur());
      const Matrice_Morse_Sym& sous_bloc= ref_cast(Matrice_Morse_Sym, bloc.get_bloc(0,0).valeur());
      int ok = sous_bloc.get_est_definie();
      matrice_de_travail_.set_est_definie(ok);
      matrice_a_resoudre_ = matrice_de_travail_;
    }
  else if (sub_type(Matrice_Bloc,la_matrice))
    {
      const Matrice_Bloc& matrice = ref_cast(Matrice_Bloc,la_matrice);
      const Matrice&      MB00 = matrice.get_bloc(0,0);
      if(!sub_type(Matrice_Morse_Sym,MB00.valeur()))
        {
          Cerr<<"Precond_local::prepare_ MB00 is not of type deriving from matrice_morse_sym "
              <<MB00.valeur().que_suis_je()<<finl;
          exit();
        }
      matrice_a_resoudre_ = MB00.valeur();
    }
  else if (sub_type(Matrice_Morse_Sym,la_matrice))
    {
      matrice_a_resoudre_ = la_matrice;
    }
  else
    {
      Cerr<<"In Precond_local: prepare_, the type of the matrix " << la_matrice.que_suis_je() << finl;
      Cerr<<"is not yet supported." << finl;
      exit();
    }
  Precond_base::prepare_(la_matrice, secmem);
}
References Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Cerr, Process::exit(), finl, Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Matrice_Sym::get_est_definie(), le_precond_local_, matrice_a_resoudre_, matrice_de_travail_, Precond_base::prepare_(), Objet_U::que_suis_je(), ref_cast, SolveurSys_base::reinit(), Matrice_Sym::set_est_definie(), sub_type, Deriv_Matrice_Base::valeur(), and Deriv_SolveurSys_base::valeur().
printOn()
Sortie & Precond_local::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 22 of file Precond_local.cpp.
{
  return s << le_precond_local_.que_suis_je() << finl;
}
References finl, le_precond_local_, and Objet_U::que_suis_je().
readOn()
Entree & Precond_local::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 27 of file Precond_local.cpp.
{
  is >> le_precond_local_;
// Pour eviter trop d'affichage (Convergence)
  if (!le_precond_local_.valeur().limpr())
    le_precond_local_.valeur().fixer_limpr(-1);
  return is;
}
References SolveurSys_base::fixer_limpr(), le_precond_local_, SolveurSys_base::limpr(), and Deriv_SolveurSys_base::valeur().
res_syst_loc_hybride()
void Precond_local::res_syst_loc_hybride (const Matrice_Morse_Sym & mat, const DoubleVect & secmem, DoubleVect & solution, const Champ_Inc_base & champ) protected
Definition at line 176 of file Precond_local.cpp.
{
  exit();
#if 0
  if(a_remplir_)
    {
      a_remplir_=0;
      {
        const Zone_dis_base& zdisb = champ.zone_dis_base();
        const Zone& zone = zdisb.zone();
        int nb_som = zone.nb_som();
        int nb_elem = zone.nb_elem();
        int nb_elem_tot = zone.nb_elem_tot();
        la_matrice_locale_.dimensionner(nb_elem+nb_som,0);
        int ii,jj;
        int cpt=0;
        const IntVect& tab1_tot = mat.tab1_;
        const IntVect& tab2_tot = mat.tab2_;
        const DoubleVect& coeff_tot = mat.coeff_;
        IntVect& tab1_reel = la_matrice_locale_.tab1_;
        IntVect& tab2_reel = la_matrice_locale_.tab2_;
        DoubleVect& coeff_reel = la_matrice_locale_.coeff_;
        tab1_reel(0)=1;
        for(ii=0; ii<nb_elem; ii++)
          {
            int dl = tab1_tot(ii);
            int fl = tab1_tot(ii+1);
            for(jj=dl; jj<fl; jj++)
              {
                int i_col = tab2_tot(jj-1);
                if( (i_col<=nb_elem) ||
                    ((i_col>=nb_elem_tot+1) && (i_col<=(nb_elem_tot+nb_som))) )
                  cpt++;
              }
            tab1_reel(ii+1)=cpt+1;
          }
        for(ii=nb_elem_tot; ii<(nb_elem_tot+nb_som); ii++)
          {
            int dl = tab1_tot(ii);
            int fl = tab1_tot(ii+1);
            for(jj=dl; jj<fl; jj++)
              {
                if(tab2_tot(jj-1)<=(nb_elem_tot+nb_som))
                  cpt++;
              }
            tab1_reel((ii-nb_elem_tot)+nb_elem+1)=cpt+1;
          }
        la_matrice_locale_.dimensionner(nb_elem+nb_som,tab1_reel(nb_elem+nb_som)-1);
        cpt=0;
        for(ii=0; ii<nb_elem; ii++)
          {
            int dl = tab1_tot(ii);
            int fl = tab1_tot(ii+1);
            for(jj=dl; jj<fl; jj++)
              {
                int i_col = tab2_tot(jj-1);
                if(i_col<=nb_elem)
                  {
                    tab2_reel(cpt)=tab2_tot(jj-1);
                    coeff_reel(cpt++)=coeff_tot(jj-1);
                  }
                if( (i_col>=nb_elem_tot+1) &&
                    (i_col<=(nb_elem_tot+nb_som)) )
                  {
                    tab2_reel(cpt)=tab2_tot(jj-1)-nb_elem_tot+nb_elem;
                    coeff_reel(cpt++)=coeff_tot(jj-1);
                  }
              }
          }
        for(ii=nb_elem_tot; ii<(nb_elem_tot+nb_som); ii++)
          {
            int dl = tab1_tot(ii);
            int fl = tab1_tot(ii+1);
            for(jj=dl; jj<fl; jj++)
              {
                if(tab2_tot(jj-1)<=(nb_elem_tot+nb_som))
                  {
                    tab2_reel(cpt)=tab2_tot(jj-1)-nb_elem_tot+nb_elem;
                    coeff_reel(cpt++)=coeff_tot(jj-1);
                  }
              }
          }
        la_matrice_locale_.set_est_definie(mat.get_est_definie());
        {
          int i,j,k,l;
          const ArrOfInt& items_tot = solution.get_items_communs_tot();
          for(i=0; i<items_tot.size_array(); i++)
            {
              k = items_tot[i]-nb_elem_tot+nb_elem;
              for(j=tab1_reel[k]+1; j<tab1_reel[k+1]; j++)
                {
                  coeff_reel(j-1) = 0. ;
                }
// On parcourt les lignes au-dessus pour annuler la colonne k
              for(j=0; j<k; j++)
                {
                  for(l=tab1_reel[j]+1; l<tab1_reel[j+1]; l++)
                    {
                      if((tab2_reel[l-1]-1)==k)
{
                          coeff_reel(l-1) = 0. ;
                        }
                    }
                }
            }
        }
      }
    }
  VECT(Descripteur)& desc = solution.structure().descripteur();
  int nb_struct = desc.size();
  int ind_struct;
  int taille=0;
  for(ind_struct=0; ind_struct<nb_struct; ind_struct++)
    {
      Descripteur& desci=desc[ind_struct];
      taille+=desci.nb();
    }
  DoubleTab sol_loc(taille);
  DoubleTab sec_loc(taille);
  int cpt=0;
  for(ind_struct=0; ind_struct<nb_struct; ind_struct++)
    {
      Descripteur& desci=desc[ind_struct];
      int i;
      int deb=desci.deb();
      int fin=deb+desci.nb();
      for(i=deb; i<fin; i++)
        {
          sol_loc[cpt] = solution[i];
          sec_loc[cpt] = secmem[i];
          cpt++;
        }
    }
  le_precond_local_.resoudre_systeme(la_matrice_locale_,
                                     sec_loc,sol_loc,champ);
  cpt=0;
  for(ind_struct=0; ind_struct<nb_struct; ind_struct++)
    {
      Descripteur& desci=desc[ind_struct];
      int i;
      int deb=desci.deb();
      int fin=deb+desci.nb();
      for(i=deb; i<fin; i++)
        solution[i]=sol_loc[cpt++];
    }
  solution.echange_espace_virtuel();
#endif
}
References Matrice_Morse::coeff_, Matrice_Morse::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Matrice_Sym::get_est_definie(), la_matrice_locale_, le_precond_local_, Zone::nb_elem(), Zone::nb_elem_tot(), Zone::nb_som(), SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Morse::tab1_, Matrice_Morse::tab2_, VECT, Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by precond().
res_syst_loc_simple()
void Precond_local::res_syst_loc_simple (const Matrice_Morse_Sym & mat, const DoubleVect & secmem, DoubleVect & solution, const Champ_Inc_base & champ) protected
Definition at line 122 of file Precond_local.cpp.
{
  exit();
#if 0
  if(a_remplir_)
    {
      a_remplir_=0;
      int n_reel = secmem.size();
      la_matrice_locale_.dimensionner(n_reel,0);
      int ii,jj;
      int cpt=0;
      const IntVect& tab1_tot = mat.tab1_;
      const IntVect& tab2_tot = mat.tab2_;
      const DoubleVect& coeff_tot = mat.coeff_;
      IntVect& tab1_reel = la_matrice_locale_.tab1_;
      IntVect& tab2_reel = la_matrice_locale_.tab2_;
      DoubleVect& coeff_reel = la_matrice_locale_.coeff_;
      tab1_reel(0)=1;
      for(ii=0; ii<n_reel; ii++)
        {
          int dl = tab1_tot(ii);
          int fl = tab1_tot(ii+1);
          for(jj=dl; jj<fl; jj++)
            {
              if(tab2_tot(jj-1)<=n_reel)
                cpt++;
            }
          tab1_reel(ii+1)=cpt+1;
        }
      la_matrice_locale_.dimensionner(n_reel,tab1_reel(n_reel)-1);
      cpt=0;
      for(ii=0; ii<n_reel; ii++)
        {
          int dl = tab1_tot(ii);
          int fl = tab1_tot(ii+1);
          for(jj=dl; jj<fl; jj++)
            {
              if(tab2_tot(jj-1)<=n_reel)
                {
                  tab2_reel(cpt)=tab2_tot(jj-1);
                  coeff_reel(cpt++)=coeff_tot(jj-1);
                }
            }
        }
      la_matrice_locale_.set_est_definie(mat.get_est_definie());
    }
  le_precond_local_.resoudre_systeme(la_matrice_locale_,
                                     secmem,solution,champ);
#endif
}
References Matrice_Morse::coeff_, Matrice_Morse::dimensionner(), Process::exit(), Matrice_Sym::get_est_definie(), la_matrice_locale_, le_precond_local_, SolveurSys::resoudre_systeme(), Matrice_Sym::set_est_definie(), TRUSTVect< _TYPE_ >::size(), Matrice_Morse::tab1_, and Matrice_Morse::tab2_.
Referenced by precond().
self_cast() [1/2]
const Precond_local & Precond_local::self_cast (const Objet_U & r) static
Definition at line 19 of file Precond_local.cpp.
self_cast() [2/2]
Precond_local & Precond_local::self_cast (Objet_U & r) static
Definition at line 19 of file Precond_local.cpp.
taille_memoire()
unsigned Precond_local::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Precond_local.cpp.
Member Data Documentation
info_obj
const Type_info Precond_local::info_obj static
Definition at line 26 of file Precond_local.h.
la_matrice_locale_
Matrice_Morse_Sym Precond_local::la_matrice_locale_ protected
Definition at line 34 of file Precond_local.h.
Referenced by res_syst_loc_hybride(), and res_syst_loc_simple().
le_precond_local_
SolveurSys Precond_local::le_precond_local_ protected
Definition at line 33 of file Precond_local.h.
Referenced by precond(), prepare_(), printOn(), readOn(), res_syst_loc_hybride(), and res_syst_loc_simple().
matrice_a_resoudre_
Ref_Matrice_Base Precond_local::matrice_a_resoudre_ protected
Definition at line 37 of file Precond_local.h.
Referenced by preconditionner_(), and prepare_().
matrice_de_travail_
Matrice_Morse_Sym Precond_local::matrice_de_travail_ protected
Definition at line 35 of file Precond_local.h.
Referenced by prepare_().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Precond_local.h
src/Kernel/Math/SolvSys/Precond_local.cpp