TRUST: Pb_Multiphase Class Reference
Pb_Multiphase Class Reference
classe Pb_Multiphase
Cette classe represente un probleme de thermohydraulique multiphase de type "3*N equations" :
- QDM_Multiphase : equations de Navier-Stokes et de continuite pour chaque phase
inconnues : v_k (vitesses par phase)
champs auxiliaires : pression p, taux de presence a_k (sum a_k = 1)
- Energie_Multiphase : equations de conservation de l'energie pour chaque phase
inconnues : T_k (temperatures)
schema de resolution typique :
1) QDM_Multiphase -> prediction des vitesses
conservation de la masse -> Newton (etape "semi-implicite")
3) Energie_Multiphase -> advection/dffusion implicite de l'energie
#include <Pb_Multiphase.h>
Public Member Functions
Pb_Multiphase ()
~Pb_Multiphase ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser (const Discretisation_base &) override
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
int nombre_d_equations () const override
Renvoie le nombre d'equation,
Renvoie 2 car il y a 2 equations a un probleme de
thermo-hydraulique standard:
l'equation de Navier Stokes
l' equation de la thermique de type Convection_Diffusion_Temperature.
const Equation_base & equation (int) const override
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1
(version const)
Equation_base & equation (int) override
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1.
void associer_milieu_base (const Milieu_base &) override
Associe le milieu au probleme
Le milieu doit etre de type fluide incompressible
Parametre: Milieu_base& mil
Signification: le milieu physique a associer au probleme
Valeurs par defaut:
Contraintes: doit etre de type fluide incompressible
reference constante
Acces: entree.
void creer_milieu (const Noms)
virtual Entree & lire_equations (Entree &is, Motcle &dernier_mot) override
Lecture des equations du probleme.
int verifier () override
Teste la compatibilite des equations de la thermique
et de l'hydraulique. Le test se fait sur les conditions
aux limites discretisees de chaque equation.
Appel la fonction de librairie hors classe:
tester_compatibilite_hydr_thermique(const Zone_Cl_dis&,const Zone_Cl_dis&)
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
void completer () override
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
virtual Entree & lire_correlations (Entree &is)
void preparer_calcul () override
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
const Champ_base & get_champ (const Motcle &nom) const override
bool has_champ (const Motcle &nom) const override
int nb_phases () const
const Nom & nom_phase (int i) const
const Noms & noms_phases () const
void set_noms_phases (Noms &noms)
const Correlation & get_correlation (std::string nom_correlation) const
int has_correlation (std::string nom_correlation) const
Public Member Functions inherited from Pb_Fluide_base
Pb_Fluide_base ()
~Pb_Fluide_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int expression_predefini (const Motcle &motlu, Nom &expression) override
Public Member Functions inherited from Probleme_base
~Probleme_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
bool solveTimeStep () override
pour recodage eventuel et appel unifie en python
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Si force=1, effectue le postraitement sans tenir compte des
frequences de postraitement.
Le postraitement est mis a jour et les traitements eventuels sur
les sondes, champs et statistiques sont effectues.
Si force=0, tient compte des frequences d'impression demandees.
int limpr () const override
Demande au schema en temps s'il faut faire une impression.
int lsauv () const override
Demande au schema en temps s'il faut faire une sauvegarde.
void sauver () const override
Ecriture sur fichier en vue d'une reprise (sauvegarde)
virtual void allocation () const
Verifie que la place necessaire existe sur le disque dur.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
Probleme_base ()
virtual void associer ()
Associe le probleme a toutes ses equations.
virtual Entree & lire_equations (Entree &is, Motcle &dernier_mot)
Lecture des equations du probleme.
virtual void completer ()
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
virtual int verifier ()
Verifie que l'objet est complet, coherent, ...
NON DEVELOPPE RENVOIE TOUJOURS 1.
virtual int nombre_d_equations () const =0
virtual const Equation_base & equation (int) const =0
virtual Equation_base & equation (int)=0
const Equation_base & equation (const Nom &) const
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
(version const)
Equation_base & equation (const Nom &)
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
virtual const Equation_base & get_equation_by_name (const Nom &) const
virtual Equation_base & getset_equation_by_name (const Nom &)
virtual const Milieu_base & milieu () const
Renvoie le milieu physique associe au probleme.
(version const)
On renvoie le milieu associe a la premiere equation.
virtual Milieu_base & milieu ()
Renvoie le milieu physique associe au probleme.
On renvoie le milieu associe a la premiere equation.
int sauvegarder (Sortie &) const override
Ecriture du probleme sur fichier en vue d'une reprise.
Ecrit le nom du probleme et sauvegarde les equations.
int reprendre (Entree &) override
Lecture d'un flot d'entree (fichier) pour reprise apres
une sauvegarde avec Probleme_base::sauvegarder(Sortie& os).
virtual void imprimer (Sortie &os) const
Appelle imprimer sur chaque equation.
virtual double calculer_pas_de_temps () const
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees
au probleme.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
virtual void preparer_calcul ()
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
virtual void associer_domaine (const Domaine &)
Associe un domaine au probleme.
Prend un_domaine comme support.
apelle Domaine_dis::associer_dom(const Domaine&)
virtual void associer_milieu_base (const Milieu_base &)
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
int associer_ (Objet_U &) override
surcharge Objet_U::associer_(Objet_U& ob)
Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
virtual void discretiser (const Discretisation_base &)
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
virtual void finir ()
Finit le postraitement et sauve le probleme dans un fichier.
Fermeture du fichier associe au postraitement.(Postraitement::finir())
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe au probleme. (si il est non nul)
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe au probleme. (si il est non nul)
const Domaine & domaine () const
Renvoie le domaine associe au probleme.
(version const)
Domaine & domaine ()
Renvoie le domaine associe au probleme.
const Domaine_dis & domaine_dis () const
Renvoie le domaine discretise associe au probleme.
(version const)
Domaine_dis & domaine_dis ()
Renvoie le domaine discretise associe au probleme.
int is_dilatable () const
virtual int allocate_file_size (long int &size) const
Verifie que la place necessaire existe sur le disque dur.
virtual int file_size_xyz () const
Ecrit le probleme dans un fichier *.calcul_xyz
et calcul la place disque prise par ce fichier.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au probleme
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du probleme
const Discretisation_base & discretisation () const
Renvoie la discretisation associee au probleme.
Postraitements & postraitements ()
const Postraitements & postraitements () const
void init_postraitements ()
virtual int expression_predefini (const Motcle &motlu, Nom &expression)
const char * reprise_format_temps () const
int & reprise_effectuee ()
int reprise_effectuee () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual bool has_champ (const Motcle &nom) const
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &nom) const
virtual int verifie_tdeb_tfin (const Motcle &nom) const
On verifie que le temps de debut et de fin des statistiques est identique sur tous les champsde tous les postraitements.
virtual int a_pour_IntVect (const Motcle &, Ref_IntVect &) const
virtual void lire_postraitement_interfaces (Entree &is)
virtual void postraiter_interfaces (const Nom &nom_fich, Sortie &s, const Nom &format, double temps)
virtual void addInputField (Field_base &f)
void sauver_xyz (int) const
void set_coupled (int i)
int get_coupled () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Pb_Multiphase & self_cast (Objet_U &)
static const Pb_Multiphase & self_cast (const Objet_U &)
Static Public Member Functions inherited from Pb_Fluide_base
static const Type_info * info ()
static Pb_Fluide_base & self_cast (Objet_U &)
static const Pb_Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_base
static const Type_info * info ()
static Probleme_base & self_cast (Objet_U &)
static const Probleme_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
QDM_Multiphase eq_qdm
Energie_Multiphase eq_energie
Masse_Multiphase eq_masse
List_Equation eq_opt
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Pb_Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Probleme_base
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Noms noms_phases_
std::map< std::string, Correlation > correlations
Protected Attributes inherited from Probleme_base
Domaine_dis le_domaine_dis
Postraitements les_postraitements
Ref_Schema_Temps_base le_schema_en_temps
Ref_Discretisation_base la_discretisation
List_Ref_Field_base input_fields
List of input fields inside this problem.
Deriv_Sortie_Fichier_base ficsauv_
Sortie_Brute * osauv_hdf_
int reprise_effectuee_
int reprise_version_
Nom nom_fich
Nom format_sauv
int restart_file
bool initialized
true if initialize was called
bool terminated
true if terminate was called
bool dt_defined
true if computation interval is defined set to true by initTimeStep, to false by validateTimeStep & abortTimeStep
bool dt_validated
true if last computation was validated set to true by validateTimeStep, to false by initTimeStep
double tstat_deb_
double tstat_fin_
Nom error
Erreur d'allocation.
int coupled_
Flag to indicate it is a part of a coupled problem.
List_Ref_Loi_Fermeture_base liste_loi_fermeture_
liste des fermetures associees au probleme
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Additional Inherited Members
Static Protected Attributes inherited from Probleme_base
static long int file_size =0
Espace disque pris par les sauvegarde XYZ.
static int bad_allocate =1
1 si allocation reussi, 0 sinon
static int nb_pb_total =0
Nombre total de probleme.
static int num_pb =1
numero du probleme
Detailed Description
classe Pb_Multiphase
Cette classe represente un probleme de thermohydraulique multiphase de type "3*N equations" :
- QDM_Multiphase : equations de Navier-Stokes et de continuite pour chaque phase
inconnues : v_k (vitesses par phase)
champs auxiliaires : pression p, taux de presence a_k (sum a_k = 1)
- Energie_Multiphase : equations de conservation de l'energie pour chaque phase
inconnues : T_k (temperatures)
schema de resolution typique :
1) QDM_Multiphase -> prediction des vitesses
conservation de la masse -> Newton (etape "semi-implicite")
3) Energie_Multiphase -> advection/dffusion implicite de l'energie
Definition at line 47 of file Pb_Multiphase.h.
Constructor & Destructor Documentation
Pb_Multiphase()
Pb_Multiphase::Pb_Multiphase ()
Definition at line 27 of file Pb_Multiphase.cpp.
~Pb_Multiphase()
Pb_Multiphase::~Pb_Multiphase ()
Definition at line 27 of file Pb_Multiphase.cpp.
Member Function Documentation
associer_milieu_base()
void Pb_Multiphase::associer_milieu_base (const Milieu_base & mil) override virtual
Associe le milieu au probleme
Le milieu doit etre de type fluide incompressible
Parametre: Milieu_base& mil
Signification: le milieu physique a associer au probleme
Valeurs par defaut:
Contraintes: doit etre de type fluide incompressible
reference constante
Acces: entree.
Reimplemented from Probleme_base.
Definition at line 240 of file Pb_Multiphase.cpp.
{
  /* controler le type de milieu ici */
  eq_qdm.associer_milieu_base(mil);
  eq_energie.associer_milieu_base(mil);
  eq_masse.associer_milieu_base(mil);
}
References Navier_Stokes_std::associer_milieu_base(), Energie_Multiphase::associer_milieu_base(), Masse_Multiphase::associer_milieu_base(), eq_energie, eq_masse, and eq_qdm.
Referenced by creer_milieu().
completer()
void Pb_Multiphase::completer (void) override virtual
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
Reimplemented from Probleme_base.
Definition at line 345 of file Pb_Multiphase.cpp.
{
  Pb_Fluide_base::completer();
  for (auto &&corr : correlations)
    {
      corr.second->completer();
    }
}
References Probleme_base::completer(), and correlations.
cree_instance()
Objet_U * Pb_Multiphase::cree_instance () static
Definition at line 27 of file Pb_Multiphase.cpp.
creer_milieu()
void Pb_Multiphase::creer_milieu (const Noms noms_milieux)
Definition at line 248 of file Pb_Multiphase.cpp.
{
  DerObjU ref;
  ref.typer("Milieu_composite");
  Objet_U& obj = Interprete_bloc::interprete_courant().ajouter("milieu", ref);
  Milieu_composite& mil = ref_cast(Milieu_composite, obj);
  Nom nmil("{ ");
  for (int i = 0; i < noms_milieux.size(); i++)
    nmil += noms_milieux[i] + " ";
  nmil += "}";
  EChaine chaine_mil(nmil);
  chaine_mil >> mil;
  associer_milieu_base(mil);
}
References Interprete_bloc::ajouter(), associer_milieu_base(), Interprete_bloc::interprete_courant(), ref_cast, vect_impl::size(), and Deriv_::typer().
Referenced by Phases::interpreter().
discretiser()
void Pb_Multiphase::discretiser (const Discretisation_base & une_discretisation) override virtual
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
Reimplemented from Probleme_base.
Definition at line 141 of file Pb_Multiphase.cpp.
{
  if (!noms_phases_.size())
    Cerr << "Pb_Multiphase : the phases must be set using Phase " << le_nom() << " { ... } before Discretiser" << finl, Process::exit();
  return Pb_Fluide_base::discretiser(disc);
}
References Cerr, Probleme_base::discretiser(), Process::exit(), finl, Probleme_base::le_nom(), noms_phases_, and vect_impl::size().
duplique()
int Pb_Multiphase::duplique () const override virtual
Implements Objet_U.
Reimplemented in Pb_HEM.
Definition at line 27 of file Pb_Multiphase.cpp.
equation() [1/2]
const Equation_base & Pb_Multiphase::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1
(version const)
Returns
Equation_base&
Signification: l'equation correspondante a l'index
Contraintes: reference constante
Implements Probleme_base.
Definition at line 188 of file Pb_Multiphase.cpp.
{
  if      (i == 0) return eq_qdm;
  else if (i == 1) return eq_masse;
  else if (i == 2) return eq_energie;
  else if (i < 3 + eq_opt.size()) return eq_opt[i - 3].valeur();
  else Cerr << "Pb_Multiphase::equation() : Wrong equation number" << i << "!" << finl, Process::exit();
  return eq_qdm; //pour renvoyer quelque chose
}
References Cerr, eq_energie, eq_masse, eq_opt, eq_qdm, Process::exit(), finl, liste::size(), and List_Equation::valeur().
Referenced by SETS::iterer_NS().
equation() [2/2]
Equation_base & Pb_Multiphase::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1.
Returns
Equation_base&
Signification: l'equation correspondante a l'index
Contraintes:
Implements Probleme_base.
Definition at line 214 of file Pb_Multiphase.cpp.
{
  if      (i == 0) return eq_qdm;
  else if (i == 1) return eq_masse;
  else if (i == 2) return eq_energie;
  else if (i < 3 + eq_opt.size()) return eq_opt[i - 3].valeur();
  else Cerr << "Pb_Multiphase::equation() : Wrong equation number" << i << "!" << finl, Process::exit();
  return eq_qdm; //pour renvoyer quelque chose
}
References Cerr, eq_energie, eq_masse, eq_opt, eq_qdm, Process::exit(), finl, liste::size(), and List_Equation::valeur().
get_champ()
const Champ_base & Pb_Multiphase::get_champ (const Motcle & nom) const override virtual
Reimplemented from Probleme_base.
Definition at line 325 of file Pb_Multiphase.cpp.
{
  REF(Champ_base) ref_champ;
  for (auto &&corr : correlations)
    {
      try
        {
          return corr.second->get_champ(un_nom);
        }
      catch (Champs_compris_erreur)  {        }
    }
  try
    {
      return Pb_Fluide_base::get_champ(un_nom);
    }
  catch (Champs_compris_erreur)     {      }
  throw Champs_compris_erreur();
  return ref_champ;
}
References correlations, Probleme_base::get_champ(), and REF.
get_correlation()
const Correlation & Pb_Multiphase::get_correlation (std::string nom_correlation) const inline
Definition at line 77 of file Pb_Multiphase.h.
  {
    Motcle mot(nom_correlation);
    return correlations.at(mot.getString());
  }
References correlations, and Nom::getString().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::completer(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::readOn(), Flux_interfacial_PolyMAC::readOn(), Frottement_interfacial_PolyMAC_P0::readOn(), and Portance_interfaciale_PolyMAC_P0::readOn().
get_info()
const Type_info * Pb_Multiphase::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_HEM.
Definition at line 27 of file Pb_Multiphase.cpp.
has_champ()
bool Pb_Multiphase::has_champ (const Motcle & nom) const override virtual
Reimplemented from Probleme_base.
Definition at line 307 of file Pb_Multiphase.cpp.
{
  Champ_base const * champ = NULL ;
  REF(Champ_base) ref_champ;
  for (auto &&corr : correlations)
    {
      try
        {
          champ = &corr.second->get_champ(un_nom);
        }
      catch (Champs_compris_erreur)  {        }
    }
  if (champ) return true ;
  return Probleme_base::has_champ(un_nom);
}
References correlations, Probleme_base::has_champ(), and REF.
Referenced by Flux_interfacial_Ranz_Marshall::completer().
has_correlation()
int Pb_Multiphase::has_correlation (std::string nom_correlation) const inline
Definition at line 83 of file Pb_Multiphase.h.
  {
    Motcle mot(nom_correlation);
    return correlations.count(mot.getString());
  }
References correlations, and Nom::getString().
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::completer(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), lire_equations(), Aire_interfaciale::readOn(), Dispersion_bulles_PolyMAC_P0::readOn(), Flux_interfacial_PolyMAC::readOn(), Frottement_interfacial_PolyMAC_P0::readOn(), and Portance_interfaciale_PolyMAC_P0::readOn().
info()
const Type_info * Pb_Multiphase::info () static
Definition at line 27 of file Pb_Multiphase.cpp.
lire_correlations()
Entree & Pb_Multiphase::lire_correlations (Entree & is) virtual
Definition at line 130 of file Pb_Multiphase.cpp.
{
  Motcle mot;
  is >> mot;
  if (mot != "{") Cerr << "correlations : { expected instead of " << mot << finl, Process::exit();
  for (is >> mot; mot != "}"; is >> mot)
    if (correlations.count(mot.getString())) Process::exit(que_suis_je() + " : a correlation already exists for " + mot + " !");
    else correlations[mot.getString()].typer_lire(*this, mot, is);
  return is;
}
References Cerr, correlations, Process::exit(), finl, Nom::getString(), and Objet_U::que_suis_je().
Referenced by lire_equations().
lire_equations()
Entree & Pb_Multiphase::lire_equations (Entree & is, Motcle & dernier_mot) override virtual
Lecture des equations du probleme.
Reimplemented from Probleme_base.
Definition at line 50 of file Pb_Multiphase.cpp.
{
  bool already_read;
  is >> mot;
  if (mot == "correlations") lire_correlations(is), already_read = false;
  else already_read = true;
// Particular treatment in cas of Homogeneous Equilibrium Mechanical
// calculation using the Pb_HEM class
// We enforce a interfacial flux correlation with constant coefficient
  if (que_suis_je() == "Pb_HEM")
    {
// enforce_interfacial_flux_correlation();
      if (has_correlation("flux_interfacial"))
        {
          for (auto &&corr : correlations)
            {
              if (corr.second.valeur().que_suis_je() == "Flux_interfacial_Coef_Constant")
                {
                  Cout << "Flux_interfacial_Coef_Constant is already defined." << finl;
                }
              else
                {
                  Cerr << "An interfacial flux correlation is already defined in the data file, but from a different kind that coef_constant." << finl;
                  Cerr << "For a Pb_HEM, the interfacial flux correlation must be of the kind coef_constant. Please either remove the line as it will be automatically added or modify the expression." << finl;
                  Process::exit();
                }
            }
        }
      else
        {
// The coefficient 1e10 is enforced. If the user wants to
// modify it, we invite her to add the line in the data
// file.
          Cout << "Pb_HEM: we add a interfacial flux correlation with constant coefficient." << finl;
          Nom corr_FICC ("{ flux_interfacial coef_constant { ");
          for (int ii = 0; ii < nb_phases(); ii++)
            {
              corr_FICC += nom_phase(ii);
              corr_FICC += " 1e10 ";
            }
          corr_FICC += "} }";
          Cout << "Expression added: " << corr_FICC << finl;
          Cout << "Please add this line to the data file directly if you want to modify the enforced coefficient 1e10." << finl;
          EChaine corr_flux_inter_coef_const(corr_FICC);
          lire_correlations(corr_flux_inter_coef_const);
        }
    }
// End of Pb_HEM special treatment
  Cerr << "Reading of the equations" << finl;
  for(int i = 0; i < nombre_d_equations(); i++, already_read = false)
    {
      if (!already_read) is >> mot;
      is >> getset_equation_by_name(mot);
    }
  /* lecture d'equations optionnelles */
  Noms noms_eq, noms_eq_maj; //noms de toutes les equations possibles!
  Type_info::les_sous_types(Nom("Equation_base"), noms_eq);
  for (int i = 0; i < noms_eq.size(); i++) noms_eq_maj.add(Motcle(noms_eq(i))); //ha ha ha
  for (is >> mot; noms_eq_maj.rang(mot) >= 0; is >> mot)
    {
      eq_opt.add(Equation()); //une autre equation optionelle
      eq_opt.dernier().valeur().typer(mot); //on lui donne le bon type
      Equation_base& eq = eq_opt.dernier().valeur().valeur();
// memes associations que pour les autres equations : probleme, milieu, schema en temps
      eq.associer_pb_base(*this);
      eq.associer_milieu_base(milieu());
      eq.associer_sch_tps_base(le_schema_en_temps);
      eq.associer_zone_dis(domaine_dis().zone_dis(0));
      eq.discretiser(); //a faire avant de lire l'equation
      is >> eq; //et c'est parti!
      eq.associer_milieu_equation(); //remontee vers le milieu
    }
  return is;
}
References List_Equation::add(), Vect_Nom::add(), Equation_base::associer_milieu_base(), Equation_base::associer_milieu_equation(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), Equation_base::associer_zone_dis(), Cerr, correlations, Cout, List_Equation::dernier(), Equation_base::discretiser(), Probleme_base::domaine_dis(), eq_opt, Process::exit(), finl, Probleme_base::getset_equation_by_name(), has_correlation(), Probleme_base::le_schema_en_temps, Type_info::les_sous_types(), lire_correlations(), Probleme_base::milieu(), nb_phases(), nom_phase(), nombre_d_equations(), Objet_U::que_suis_je(), Noms::rang(), vect_impl::size(), Deriv_::typer(), List_Equation::valeur(), and Deriv_Equation_base::valeur().
mettre_a_jour()
void Pb_Multiphase::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Reimplemented from Probleme_base.
Definition at line 291 of file Pb_Multiphase.cpp.
{
  Probleme_base::mettre_a_jour(temps);
  for (auto &&corr : correlations)
    {
      corr.second->mettre_a_jour(temps);
    }
}
References correlations, and Probleme_base::mettre_a_jour().
Referenced by SETS::iterer_NS(), and preparer_calcul().
nb_phases()
int Pb_Multiphase::nb_phases () const inline
Definition at line 67 of file Pb_Multiphase.h.
{ return noms_phases_.size(); }
References noms_phases_, and vect_impl::size().
Referenced by Flux_interfacial_Ranz_Marshall::completer(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), lire_equations(), Op_Conv_EF_Stab_PolyMAC_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Flux_interfacial_Coef_Constant::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Weber::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Tomiyama::readOn(), Aire_interfaciale::readOn(), QDM_Multiphase::readOn(), Dispersion_bulles_PolyMAC_P0::readOn(), Force_Tchen_PolyMAC_P0::readOn(), and Portance_interfaciale_PolyMAC_P0::readOn().
nom_phase()
const Nom & Pb_Multiphase::nom_phase (int i) const inline
Definition at line 68 of file Pb_Multiphase.h.
{ return noms_phases_[i]; }
References noms_phases_.
Referenced by Flux_interfacial_Ranz_Marshall::completer(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), lire_equations(), Op_Conv_EF_Stab_PolyMAC_Elem::readOn(), Op_Diff_Turbulent_PolyMAC_P0_Face::readOn(), Diametre_bulles_constant::readOn(), Flux_interfacial_Coef_Constant::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Frottement_interfacial_Tomiyama::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Weber::readOn(), Masse_ajoutee_Coef_Constant::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Portance_interfaciale_Tomiyama::readOn(), Aire_interfaciale::readOn(), QDM_Multiphase::readOn(), Force_Tchen_PolyMAC_P0::readOn(), and Portance_interfaciale_PolyMAC_P0::readOn().
nombre_d_equations()
int Pb_Multiphase::nombre_d_equations () const override virtual
Renvoie le nombre d'equation,
Renvoie 2 car il y a 2 equations a un probleme de
thermo-hydraulique standard:
l'equation de Navier Stokes
l' equation de la thermique de type Convection_Diffusion_Temperature.
Returns
int
Signification: le nombre d'equation
Contraintes: toujours 2 car il y a 2 equations au probleme
Implements Probleme_base.
Definition at line 166 of file Pb_Multiphase.cpp.
{
  return 3 + eq_opt.size();
}
References eq_opt, and liste::size().
Referenced by SETS::iterer_NS(), and lire_equations().
noms_phases()
const Noms & Pb_Multiphase::noms_phases () const inline
Definition at line 69 of file Pb_Multiphase.h.
{ return noms_phases_; }
References noms_phases_.
preparer_calcul()
void Pb_Multiphase::preparer_calcul (void) override virtual
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
Definition at line 300 of file Pb_Multiphase.cpp.
{
  Pb_Fluide_base::preparer_calcul();
  const double temps = schema_temps().temps_courant();
  mettre_a_jour(temps);
}
References mettre_a_jour(), Probleme_base::preparer_calcul(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
printOn()
Sortie & Pb_Multiphase::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_HEM.
Definition at line 46 of file Pb_Multiphase.cpp.
{ return Pb_Fluide_base::printOn(os); }
References Pb_Fluide_base::printOn().
Referenced by Pb_HEM::printOn().
readOn()
Entree & Pb_Multiphase::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Returns
Entree&
Signification: le flot d'entre modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_HEM.
Definition at line 48 of file Pb_Multiphase.cpp.
{ return Pb_Fluide_base::readOn(is); }
References Pb_Fluide_base::readOn().
Referenced by Pb_HEM::readOn().
self_cast() [1/2]
const Pb_Multiphase & Pb_Multiphase::self_cast (const Objet_U & r) static
Definition at line 27 of file Pb_Multiphase.cpp.
self_cast() [2/2]
Pb_Multiphase & Pb_Multiphase::self_cast (Objet_U & r) static
Definition at line 27 of file Pb_Multiphase.cpp.
set_noms_phases()
void Pb_Multiphase::set_noms_phases (Noms & noms) inline
Definition at line 70 of file Pb_Multiphase.h.
{ noms_phases_ = noms; }
References noms_phases_.
Referenced by Phases::interpreter().
taille_memoire()
unsigned Pb_Multiphase::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Pb_HEM.
Definition at line 27 of file Pb_Multiphase.cpp.
verifier()
int Pb_Multiphase::verifier () override virtual
Teste la compatibilite des equations de la thermique
et de l'hydraulique. Le test se fait sur les conditions
aux limites discretisees de chaque equation.
Appel la fonction de librairie hors classe:
tester_compatibilite_hydr_thermique(const Zone_Cl_dis&,const Zone_Cl_dis&)
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Probleme_base.
Definition at line 284 of file Pb_Multiphase.cpp.
{
  const Zone_Cl_dis& zone_Cl_hydr = eq_qdm.zone_Cl_dis();
  const Zone_Cl_dis& zone_Cl_th = eq_energie.zone_Cl_dis();
  return tester_compatibilite_hydr_thermique(zone_Cl_hydr,zone_Cl_th);
}
References eq_energie, eq_qdm, tester_compatibilite_hydr_thermique(), and Equation_base::zone_Cl_dis().
Member Data Documentation
correlations
std::map<std::string, Correlation> Pb_Multiphase::correlations protected
Definition at line 92 of file Pb_Multiphase.h.
Referenced by completer(), get_champ(), get_correlation(), has_champ(), has_correlation(), lire_correlations(), lire_equations(), and mettre_a_jour().
eq_energie
Energie_Multiphase Pb_Multiphase::eq_energie
Definition at line 73 of file Pb_Multiphase.h.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), associer_milieu_base(), equation(), and verifier().
eq_masse
Masse_Multiphase Pb_Multiphase::eq_masse
Definition at line 74 of file Pb_Multiphase.h.
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Assembleur_P_PolyMAC::assembler_continuite(), associer_milieu_base(), and equation().
eq_opt
List_Equation Pb_Multiphase::eq_opt
Definition at line 75 of file Pb_Multiphase.h.
Referenced by equation(), lire_equations(), and nombre_d_equations().
eq_qdm
QDM_Multiphase Pb_Multiphase::eq_qdm
Definition at line 72 of file Pb_Multiphase.h.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), associer_milieu_base(), equation(), and verifier().
info_obj
const Type_info Pb_Multiphase::info_obj static
Definition at line 49 of file Pb_Multiphase.h.
noms_phases_
Noms Pb_Multiphase::noms_phases_ protected
Definition at line 91 of file Pb_Multiphase.h.
Referenced by discretiser(), nb_phases(), nom_phase(), noms_phases(), and set_noms_phases().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Pb_Multiphase.h
src/ThHyd/Multiphase/Pb_Multiphase.cpp