TRUST: Masse_PolyMAC_P0_Face Class Reference
Masse_PolyMAC_P0_Face Class Reference
#include <Masse_PolyMAC_P0_Face.h>
Public Member Functions
Masse_PolyMAC_P0_Face ()
~Masse_PolyMAC_P0_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
void completer () override
DoubleTab & appliquer_impl (DoubleTab &) const override
DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const override
void check_multiphase_compatibility () const override
Public Member Functions inherited from Solveur_Masse_base
Solveur_Masse_base ()
~Solveur_Masse_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & appliquer (DoubleTab &) const
renvoie appliquer_impl(x/coeffient_temporelle)
si on a un coefficient temporelle
sinon renvoie appliquer_impl(x)
Return M-1.x
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du solveur de masse.
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual void assembler ()
NE FAIT RIEN
Eventuellement a surcharger dans les classes derivees
si la matrice de masse necessite un assemblage.
Assemble le solveur de masse (en general la matrice de masse)
virtual Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual Matrice_Base & ajouter_masse_dt_local (DoubleVect &dt_locaux, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse_dt_local (DoubleVect &dt_locaux, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual void get_masse_dt_local (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual void get_masse_divide_by_local_dt (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
void set_name_of_coefficient_temporel (const Nom &)
permet de choisir le nom du coefficient temporelle
que l'on veut utiliser pour appliquer
verifie que le champ exsite bien
int has_coefficient_temporel () const
const Nom & get_name_of_coefficient_temporel () const
virtual DoubleTab & appliquer_impl (DoubleTab &x) const =0
virtual void dimensionner (Matrice_Morse &matrix) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
virtual void completer (void)
virtual void preparer_calcul (void)
void set_penalisation_flag (int pen)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Masse_PolyMAC_P0_Face & self_cast (Objet_U &)
static const Masse_PolyMAC_P0_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Masse_base
static const Type_info * info ()
static Solveur_Masse_base & self_cast (Objet_U &)
static const Solveur_Masse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Masse_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
Ref_Zone_PolyMAC_P0 la_zone_PolyMAC_P0
Ref_Zone_Cl_PolyMAC la_Zone_Cl_PolyMAC
Additional Inherited Members
Protected Attributes inherited from Solveur_Masse_base
Nom name_of_coefficient_temporel_
nom du coefficient temporelle
int has_coefficient_temporel_
int penalisation_flag_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 25 of file Masse_PolyMAC_P0_Face.h.
Constructor & Destructor Documentation
Masse_PolyMAC_P0_Face()
Masse_PolyMAC_P0_Face::Masse_PolyMAC_P0_Face ()
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
~Masse_PolyMAC_P0_Face()
Masse_PolyMAC_P0_Face::~Masse_PolyMAC_P0_Face ()
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Masse_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 125 of file Masse_PolyMAC_P0_Face.cpp.
{
  const DoubleTab& inco = equation().inconnue().valeurs(), &passe = equation().inconnue().passe();
  Matrice_Morse *mat = matrices[equation().inconnue().le_nom().getString()]; //facultatif
  const Zone_PolyMAC_P0& zone = la_zone_PolyMAC_P0;
  const Conds_lim& cls = la_Zone_Cl_PolyMAC->les_conditions_limites();
  const IntTab& f_e = zone.face_voisins(), &fcl = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur()).fcl();
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes(), &fs = zone.face_surfaces();
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const DoubleTab& nf = zone.face_normales(), &rho = equation().milieu().masse_volumique().passe(),
                   *alpha = pbm ? &pbm->eq_masse.inconnue().passe() : NULL, *a_r = pbm ? &pbm->eq_masse.champ_conserve().passe() : NULL, &vfd = zone.volumes_entrelaces_dir();
  const Masse_ajoutee_base *corr = pbm && pbm->has_correlation("masse_ajoutee") ? &ref_cast(Masse_ajoutee_base, pbm->get_correlation("masse_ajoutee").valeur()) : NULL;
  int i, e, f, nf_tot = zone.nb_faces_tot(), m, n, N = inco.line_size(), d, D = dimension, cR = rho.dimension_tot(0) == 1;
  /* faces : si CLs, pas de produit par alpha * rho en multiphase */
  DoubleTrav masse(N, N), masse_e(N, N); //masse alpha * rho, contribution
  for (f = 0; f < zone.nb_faces(); f++) //faces reelles
    {
      if (!pbm || fcl(f, 0) >= 2)
        for (masse = 0, n = 0; n < N; n++) masse(n, n) = 1; //pas Pb_Multiphase ou CL -> pas de alpha * rho
      else for (masse = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
          {
            for (masse_e = 0, n = 0; n < N; n++) masse_e(n, n) = (*a_r)(e, n); //partie diagonale
            if (corr) corr->ajouter(&(*alpha)(e, 0), &rho(!cR * e, 0), masse_e); //partie masse ajoutee
            for (n = 0; n < N; n++)
              for (m = 0; m < N; m++) masse(n, m) += vfd(f, i) / vf(f) * masse_e(n, m); //contribution au alpha * rho de la face
          }
      for (n = 0; n < N; n++)
        {
          double fac = pf(f) * vf(f) / dt;
          for (m = 0; m < N; m++) secmem(f, n) -= fac * resoudre_en_increments * masse(n, m) * inco(f, m);
          if (fcl(f, 0) < 2)
            for (m = 0; m < N; m++) secmem(f, n) += fac * masse(n, m) * passe(f, m);
          else if (fcl(f, 0) == 3)
            for (d = 0; d < D; d++)
              secmem(f, n) += fac * masse(n, n) * ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), N * d + n) * nf(f, d) / fs(f);
          if (mat)
            for (m = 0; m < N; m++)
              if (masse(n, m)) (*mat)(N * f + n, N * f + m) += fac * masse(n, m);
        }
    }
  for (e = 0, i = nf_tot; e < zone.nb_elem_tot(); e++) //tous les elems (pour Op_Grad_PolyMAC_P0_Face)
    {
      for (masse = 0, n = 0; n < N; n++) masse(n, n) = a_r ? (*a_r)(e, n) : 1; //partie diagonale
      if (corr) corr->ajouter(&(*alpha)(e, 0), &rho(!cR * e, 0), masse); //partie masse ajoutee
      for (d = 0; d < D; d++, i++)
        for (n = 0; n < N; n++)
          {
            double fac = pe(e) * ve(e) / dt;
            for (m = 0; m < N; m++) secmem(i, n) -= fac * masse(n, m) * (resoudre_en_increments * inco(i, m) - passe(i, m));
            if (mat)
              for (m = 0; m < N; m++)
                if (masse(n, m)) (*mat)(N * i + n, N * i + m) += fac * masse(n, m);
          }
    }
  i++;
}
References Masse_ajoutee_base::ajouter(), Equation_base::champ_conserve(), Objet_U::dimension, Pb_Multiphase::eq_masse, MorEqn::equation(), Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Pb_Multiphase::get_correlation(), Nom::getString(), Pb_Multiphase::has_correlation(), Equation_base::inconnue(), Masse_Multiphase::inconnue(), la_Zone_Cl_PolyMAC, la_zone_PolyMAC_P0, O_U_Ptr::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Champ_Proto::passe(), Champ_Inc::passe(), Champ_Inc_base::passe(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Deriv_Correlation_base::valeur(), valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Zone_Poly_base::volumes_entrelaces_dir().
appliquer_impl()
DoubleTab & Masse_PolyMAC_P0_Face::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
Definition at line 69 of file Masse_PolyMAC_P0_Face.cpp.
{
  const Zone_PolyMAC_P0& zone = la_zone_PolyMAC_P0.valeur();
  const IntTab& f_e = zone.face_voisins();
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  int i, e, f, nf_tot = zone.nb_faces_tot(), n, N = equation().inconnue().valeurs().line_size(), d, D = dimension;
  const DoubleTab *a_r = sub_type(QDM_Multiphase, equation()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.champ_conserve().passe() : NULL, &vfd = zone.volumes_entrelaces_dir();
  double fac;
// vitesses aux faces
  for (f = 0; f < zone.nb_faces(); f++)
    for (n = 0; n < N; n++)
      {
        for (fac = 0, i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) fac += vfd(f, i) / vf(f) * (a_r ? (*a_r)(e, n) : 1);
        sm(f, n) /= pf(f) * vf(f) * fac; //vitesse calculee
      }
// vitesses aux elements
  if (sm.dimension_tot(0) > N * nf_tot)
    for (e = 0; e < zone.nb_elem(); e++)
      for (d = 0; d < D; d++)
        for (n = 0; n < N; n++)
          sm(nf_tot + D * e + d, n) /= pe(e) * ve(e) * (a_r ? (*a_r)(e, n) : 1);
  sm.echange_espace_virtuel();
  return sm;
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Zone_VF::face_voisins(), Equation_base::inconnue(), la_zone_PolyMAC_P0, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Ref_Zone_PolyMAC_P0::valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Zone_Poly_base::volumes_entrelaces_dir().
associer_zone_cl_dis_base()
void Masse_PolyMAC_P0_Face::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 190 of file Masse_PolyMAC_P0_Face.cpp.
{
  la_Zone_Cl_PolyMAC = ref_cast(Zone_Cl_PolyMAC, la_zone_Cl_dis_base);
}
References la_Zone_Cl_PolyMAC, and ref_cast.
associer_zone_dis_base()
void Masse_PolyMAC_P0_Face::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 185 of file Masse_PolyMAC_P0_Face.cpp.
{
  la_zone_PolyMAC_P0 = ref_cast(Zone_PolyMAC_P0, la_zone_dis_base);
}
References la_zone_PolyMAC_P0, and ref_cast.
check_multiphase_compatibility()
void Masse_PolyMAC_P0_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 48 of file Masse_PolyMAC_P0_Face.h.
{ };
completer()
void Masse_PolyMAC_P0_Face::completer (void) override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 61 of file Masse_PolyMAC_P0_Face.cpp.
{
  Solveur_Masse_base::completer();
  Equation_base& eq = equation();
  Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, eq.inconnue().valeur());
  ch.init_auxiliary_variables();
}
References Solveur_Masse_base::completer(), MorEqn::equation(), Equation_base::inconnue(), Champ_Face_PolyMAC_P0::init_auxiliary_variables(), ref_cast, and Deriv_Champ_Inc_base::valeur().
corriger_solution()
DoubleTab & Masse_PolyMAC_P0_Face::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 196 of file Masse_PolyMAC_P0_Face.cpp.
{
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  Option_PolyMAC_P0::interp_ve1 ? ch.update_ve(x) : ch.update_ve2(x, incr);
  return x;
}
References MorEqn::equation(), Option_PolyMAC_P0::interp_ve1, ref_cast, Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::update_ve2(), and valeur().
cree_instance()
Objet_U * Masse_PolyMAC_P0_Face::cree_instance () static
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
dimensionner_blocs()
void Masse_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 97 of file Masse_PolyMAC_P0_Face.cpp.
{
  const std::string& nom_inc = equation().inconnue().le_nom().getString();
  if (!matrices.count(nom_inc)) return; //rien a faire
  Matrice_Morse& mat = *matrices.at(nom_inc), mat2;
  const Zone_PolyMAC_P0& zone = la_zone_PolyMAC_P0;
  const DoubleTab& inco = equation().inconnue().valeurs();
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const Masse_ajoutee_base *corr = pbm && pbm->has_correlation("masse_ajoutee") ? &ref_cast(Masse_ajoutee_base, pbm->get_correlation("masse_ajoutee").valeur()) : NULL;
  int i, e, f, nf_tot = zone.nb_faces_tot(), m, n, N = inco.line_size(), d, D = dimension;
  IntTrav sten(0, 2);
  sten.set_smart_resize(1);
  for (f = 0, i = 0; f < zone.nb_faces(); f++)
    for (n = 0; n < N; n++, i++) //faces reelles
      if (corr)
        for (m = 0; m < N; m++) sten.append_line(i, N * f + m);
      else sten.append_line(i, i);
  for (e = 0, i = N * nf_tot; e < zone.nb_elem_tot(); e++)
    for (d = 0; d < D; d++)
      for (n = 0; n < N; n++, i++) //tous les elems (pour Op_Grad_PolyMAC_P0_Face)
        if (corr)
          for (m = 0; m < N; m++) sten.append_line(i, N * (nf_tot + D * e + d) + m);
        else sten.append_line(i, i);
  Matrix_tools::allocate_morse_matrix(inco.size_totale(), inco.size_totale(), sten, mat2);
  mat.nb_colonnes() ? mat += mat2 : mat = mat2;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::get_correlation(), Nom::getString(), Pb_Multiphase::has_correlation(), Equation_base::inconnue(), la_zone_PolyMAC_P0, O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), sub_type, Deriv_Correlation_base::valeur(), and Champ_Inc::valeurs().
duplique()
int Masse_PolyMAC_P0_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
get_info()
const Type_info * Masse_PolyMAC_P0_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
has_interface_blocs()
int Masse_PolyMAC_P0_Face::has_interface_blocs () const inline override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_P0_Face.h.
  {
    return 1;
  }
info()
const Type_info * Masse_PolyMAC_P0_Face::info () static
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
printOn()
Sortie & Masse_PolyMAC_P0_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_P0_Face.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_PolyMAC_P0_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 49 of file Masse_PolyMAC_P0_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Masse_PolyMAC_P0_Face & Masse_PolyMAC_P0_Face::self_cast (const Objet_U & r) static
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
self_cast() [2/2]
Masse_PolyMAC_P0_Face & Masse_PolyMAC_P0_Face::self_cast (Objet_U & r) static
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
taille_memoire()
unsigned Masse_PolyMAC_P0_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 35 of file Masse_PolyMAC_P0_Face.cpp.
Member Data Documentation
info_obj
const Type_info Masse_PolyMAC_P0_Face::info_obj static
Definition at line 28 of file Masse_PolyMAC_P0_Face.h.
la_Zone_Cl_PolyMAC
Ref_Zone_Cl_PolyMAC Masse_PolyMAC_P0_Face::la_Zone_Cl_PolyMAC private
Definition at line 52 of file Masse_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), and associer_zone_cl_dis_base().
la_zone_PolyMAC_P0
Ref_Zone_PolyMAC_P0 Masse_PolyMAC_P0_Face::la_zone_PolyMAC_P0 private
Definition at line 51 of file Masse_PolyMAC_P0_Face.h.
Referenced by ajouter_blocs(), appliquer_impl(), associer_zone_dis_base(), and dimensionner_blocs().
The documentation for this class was generated from the following files:
src/PolyMAC/Solveurs/Masse_PolyMAC_P0_Face.h
src/PolyMAC/Solveurs/Masse_PolyMAC_P0_Face.cpp