TRUST: Roue Class Reference
Roue Class Reference
Classe Roue utilisee dans Champ_Inc_Base.
Permet de gerer le nombre de valeurs du temps pour lesquels le champ
doit rester en memoire.
#include <Roue.h>
Public Member Functions
const DoubleTab & valeurs () const
Retourne le tableau des valeurs de la Roue.
DoubleTab & valeurs ()
Retourne le tableau des valeurs de la Roue.
Roue ()
Constructeur
Construit une roue avec une seule case, au temps t=0.
Roue (const Roue &)
Constructeur par copie
Le temps, les valeurs et les valeurs des Roues futures sont copies.
~Roue ()
Desctructeur.
void dimensionner (int nb_val)
Dimensionne (1D) les valeurs de la Roue et des ses roues futures.
void dimensionner (int nb_val, int nb_comp)
Dimensionne (2D) les valeurs de la Roue et des ses roues futures.
int nb_cases () const
Retourne le nombre de cases de la Roue.
int fixer_nb_cases (int)
Change le nombre de cases de la Roue.
void ajouter_case (int n=1)
Ajoute n cases a la Roue.
void supprimer_case (int n=1)
Supprime n cases de la Roue.
double temps () const
Retoune la valeur du temps de la Roue.
double changer_temps (const double t)
Change le temps de la Roue.
const Roue & futur (int i=1) const
Retourne la Roue correspondant a la ieme case future.
Roue & futur (int i=1)
Retourne la Roue correspondant a la ieme case future.
const Roue & passe (int i=1) const
Retourne la Roue correspondant a la ieme case passee.
Roue & passe (int i=1)
Retourne la Roue correspondant a la ieme case passee.
Roue & operator= (const Roue &)
Affectation d'une Roue
Les attibuts modifies sont le temps, les valeurs, le nombre de cases et les valeurs des cases futures.
void avancer (Roue_ptr &ptr)
void reculer (Roue_ptr &ptr)
Private Attributes
double temps_
int nb_cases_
DoubleTab valeurs_
Roue_ptr passe_
Roue_ptr futur_
Detailed Description
Classe Roue utilisee dans Champ_Inc_Base.
Permet de gerer le nombre de valeurs du temps pour lesquels le champ
doit rester en memoire.
Definition at line 89 of file Roue.h.
Constructor & Destructor Documentation
Roue() [1/2]
Roue::Roue ()
Constructeur
Construit une roue avec une seule case, au temps t=0.
Definition at line 152 of file Roue.cpp.
           : temps_(0), nb_cases_(1), valeurs_(), passe_(this), futur_(this)
{
}
Referenced by ajouter_case().
Roue() [2/2]
Roue::Roue (const Roue & roue)
Constructeur par copie
Le temps, les valeurs et les valeurs des Roues futures sont copies.
Definition at line 172 of file Roue.cpp.
                           : temps_(roue.temps_), nb_cases_(1), valeurs_(roue.valeurs_), passe_(this), futur_(this)
{
  fixer_nb_cases(roue.nb_cases_);
  for(int i=1; i<nb_cases_; i++)
    {
      futur(i).valeurs_ = roue.futur(i).valeurs_;
// abort();
    }
}
References fixer_nb_cases(), futur(), nb_cases_, and valeurs_.
~Roue()
Roue::~Roue ()
Desctructeur.
Definition at line 197 of file Roue.cpp.
{
  supprimer_case(nb_cases_);
  assert(nb_cases_==1);
  assert(futur_.ptr==this);
  assert(passe_.ptr==this);
  assert(valeurs_.size()==0);
  futur_.ptr=passe_.ptr=0;
}
References futur_, nb_cases_, passe_, Roue_ptr::ptr, TRUSTVect< _TYPE_ >::size(), supprimer_case(), and valeurs_.
Member Function Documentation
ajouter_case()
void Roue::ajouter_case (int n = 1)
Ajoute n cases a la Roue.
Definition at line 425 of file Roue.cpp.
{
  for (int n_to_add = 0; n_to_add < n; n_to_add++)
    {
      Roue * old_futur = futur_.ptr;
      Roue * new_futur = new Roue;
      this     ->futur_.ptr = new_futur;
      old_futur->passe_.ptr = new_futur;
      new_futur->futur_.ptr = old_futur;
      new_futur->passe_.ptr = this;
// On met a jour nb_cases_ de toutes les cases:
      {
        const int new_nb_cases = nb_cases_ + 1;
        Roue * ptr_roue = this;
        for(int i = 0; i < new_nb_cases; i++, ptr_roue = ptr_roue->futur_.ptr)
          ptr_roue->nb_cases_ = new_nb_cases;
      }
    }
}
References futur_, nb_cases_, passe_, Roue_ptr::ptr, and Roue().
Referenced by fixer_nb_cases().
avancer()
void Roue::avancer (Roue_ptr & ptr) inline
Definition at line 110 of file Roue.h.
  {
    ptr=ptr->futur_.valeur();
  };
References futur_, and Roue_ptr::valeur().
Referenced by Champ_Inc_base::avancer().
changer_temps()
double Roue::changer_temps (const double t) inline
Change le temps de la Roue.
Returns
double
Signification: le nouveau temps
Contraintes:
Definition at line 253 of file Roue.h.
{
  return temps_=t;
}
References temps_.
Referenced by Champ_Inc_base::changer_temps(), Champ_front_base::changer_temps_futur(), Champ_Inc_base::changer_temps_futur(), and Champ_Inc_base::changer_temps_passe().
dimensionner() [1/2]
void Roue::dimensionner (int nb_val)
Dimensionne (1D) les valeurs de la Roue et des ses roues futures.
Definition at line 328 of file Roue.cpp.
{
  if (valeurs_.size() != nb_val )
    {
      valeurs_.resize(nb_val);
      for(int j=1; j<nb_cases_; j++)
        futur(j).valeurs_.resize(nb_val);
    }
}
References futur(), nb_cases_, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), and valeurs_.
dimensionner() [2/2]
void Roue::dimensionner (int nb_val, int nb_comp)
Dimensionne (2D) les valeurs de la Roue et des ses roues futures.
Definition at line 359 of file Roue.cpp.
{
  if ((valeurs_.size() != nb_val*nb_comp )||(valeurs_.nb_dim()!=2) ||  (nb_comp!=valeurs_.dimension(1)))
    {
      valeurs_.resize(nb_val, nb_comp);
      for(int j=1; j<nb_cases_; j++)
        futur(j).valeurs_.resize(nb_val, nb_comp);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), futur(), nb_cases_, TRUSTTab< _TYPE_ >::nb_dim(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), and valeurs_.
fixer_nb_cases()
int Roue::fixer_nb_cases (int nb_case)
Change le nombre de cases de la Roue.
Returns
int
Signification: le nouveau nombre de cases
Contraintes:
Definition at line 384 of file Roue.cpp.
{
  if(nb_case==nb_cases_)
    return nb_cases_;
  int nb_case_a_ajouter=nb_case-nb_cases_;
  if(nb_case_a_ajouter>0)
    ajouter_case(nb_case_a_ajouter);
  else
    supprimer_case(-nb_case_a_ajouter);
  return nb_cases_;
}
References ajouter_case(), nb_cases_, and supprimer_case().
Referenced by Champ_front_instationnaire_base::fixer_nb_valeurs_temporelles(), Champ_front_var_instationnaire::fixer_nb_valeurs_temporelles(), Champ_Inc_base::fixer_nb_valeurs_temporelles(), Ch_front_input_P1::initialiser(), operator=(), and Roue().
futur() [1/2]
Roue & Roue::futur (int i = 1)
Retourne la Roue correspondant a la ieme case future.
Returns
const Roue&
Signification: la ieme Roue future
Contraintes:
Definition at line 246 of file Roue.cpp.
{
  assert(i>=0);
  assert(i<=nb_cases_);
  if(i==0)
    return *this;
  else
    return futur_->futur(--i);
}
References futur(), futur_, and nb_cases_.
futur() [2/2]
const Roue & Roue::futur (int i = 1) const
Retourne la Roue correspondant a la ieme case future.
Returns
const Roue&
Signification: reference sur la ieme Roue future
Contraintes:
Definition at line 221 of file Roue.cpp.
{
  assert(i>=0);
  assert(i<=nb_cases_);
  if(i==0)
    return *this;
  else
    return futur_->futur(--i);
}
References futur(), futur_, and nb_cases_.
Referenced by Champ_front_base::changer_temps_futur(), Champ_Inc_base::changer_temps_futur(), dimensionner(), futur(), Champ_Inc_base::futur(), operator=(), Roue_ptr::operator[](), Champ_Inc_base::recuperer_temps_futur(), Roue(), and Champ_Inc_base::valeurs().
nb_cases()
int Roue::nb_cases () const inline
Retourne le nombre de cases de la Roue.
Returns
int
Signification: le nombre de cases de la Roue
Contraintes:
Definition at line 271 of file Roue.h.
{
  return nb_cases_;
}
References nb_cases_.
Referenced by Champ_Inc_base::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_front_instationnaire_base::avancer(), Champ_front_var_instationnaire::avancer(), Ch_front_input_uniforme::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_instationnaire_base::initialiser(), Champ_front_var::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_Inc_base::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Champ_Inc_base::nb_valeurs_temporelles(), print(), Champ_front_instationnaire_base::reculer(), Champ_front_var_instationnaire::reculer(), Ch_front_input::setDoubleValue(), Ch_front_input::setValue(), Ch_front_input_uniforme::setValue(), Ch_front_input_P1::setValue(), Champ_front_instationnaire_base::valeurs_au_temps(), and Champ_front_var_instationnaire::valeurs_au_temps().
operator=()
Roue & Roue::operator= (const Roue & roue)
Affectation d'une Roue
Les attibuts modifies sont le temps, les valeurs, le nombre de cases et les valeurs des cases futures.
Returns
Roue&
Signification: la Roue modifiee
Contraintes:
Definition at line 527 of file Roue.cpp.
{
  temps_ = roue.temps_;
  valeurs_ = roue.valeurs_;
  fixer_nb_cases(roue.nb_cases_);
  for(int i=1; i<nb_cases_; i++)
    {
      futur(i).valeurs_ = roue.futur(i).valeurs_;
// abort();
    }
  return *this;
}
References fixer_nb_cases(), futur(), nb_cases_, temps_, and valeurs_.
passe() [1/2]
Roue & Roue::passe (int i = 1)
Retourne la Roue correspondant a la ieme case passee.
Returns
const Roue&
Signification: la ieme Roue passee
Contraintes:
Definition at line 296 of file Roue.cpp.
{
  assert(i>=0);
  assert(i<=nb_cases_);
  if(i==0)
    return*this;
  else
    return passe_->passe(--i);
}
References nb_cases_, passe(), and passe_.
passe() [2/2]
const Roue & Roue::passe (int i = 1) const
Retourne la Roue correspondant a la ieme case passee.
Returns
const Roue&
Signification: reference sur la ieme Roue passee
Contraintes:
Definition at line 271 of file Roue.cpp.
{
  assert(i>=0);
  assert(i<=nb_cases_);
  if(i==0)
    return *this;
  else
    return passe_->passe(--i);
}
References nb_cases_, passe(), and passe_.
Referenced by Champ_Inc_base::changer_temps_passe(), passe(), Champ_Inc_base::passe(), Champ_Inc_base::recuperer_temps_passe(), and Champ_Inc_base::valeurs().
reculer()
void Roue::reculer (Roue_ptr & ptr) inline
Definition at line 114 of file Roue.h.
  {
    ptr=ptr->passe_.valeur();
  };
References passe_, and Roue_ptr::valeur().
Referenced by Champ_Inc_base::reculer().
supprimer_case()
void Roue::supprimer_case (int n = 1)
Supprime n cases de la Roue.
Definition at line 471 of file Roue.cpp.
{
  for (int n_to_kill = 0; n_to_kill < n; n_to_kill++)
    {
      if (nb_cases_ == 1)
        {
          assert(futur_.ptr == this);
          assert(passe_.ptr == this);
          valeurs_.reset();
          temps_=0;
        }
      else
        {
// Sauvegarde du futur du futur:
          Roue * new_futur = futur_->futur_.ptr;
// Destruction du futur:
          {
            Roue * to_kill = futur_.ptr;
            to_kill->nb_cases_ = 1;
            to_kill->futur_.ptr = to_kill->passe_.ptr = to_kill;
            delete to_kill;
          }
// On referme la liste chainee:
          new_futur->passe_.ptr = this;
          futur_.ptr = new_futur;
          const int new_nb_cases = nb_cases_ - 1;
          if(new_nb_cases == 1)
            passe_.ptr=this;
// On met a jour nb_cases_ de toutes les cases:
          {
            Roue * ptr_roue = this;
            for(int i = 0; i < new_nb_cases; i++, ptr_roue = ptr_roue->futur_.ptr)
              ptr_roue->nb_cases_ = new_nb_cases;
          }
        }
    }
}
References futur_, nb_cases_, passe_, Roue_ptr::ptr, TRUSTTab< _TYPE_ >::reset(), temps_, and valeurs_.
Referenced by fixer_nb_cases(), and ~Roue().
temps()
double Roue::temps () const inline
Retoune la valeur du temps de la Roue.
Returns
double
Signification: le temps
Contraintes:
Definition at line 233 of file Roue.h.
{
  return temps_;
}
References temps_.
Referenced by Champ_front_instationnaire_base::avancer(), Champ_front_var_instationnaire::avancer(), Champ_Inc_base::avancer(), Champ_Inc_base::reculer(), Champ_Inc_base::recuperer_temps_futur(), Champ_Inc_base::recuperer_temps_passe(), and Champ_Inc_base::valeurs().
valeurs() [1/2]
DoubleTab & Roue::valeurs () inline
Retourne le tableau des valeurs de la Roue.
Returns
const DoubleTab&
Signification: reference sur le tableau des valeurs
Contraintes:
Definition at line 213 of file Roue.h.
{
  return valeurs_;
}
References valeurs_.
valeurs() [2/2]
const DoubleTab & Roue::valeurs () const inline
Retourne le tableau des valeurs de la Roue.
Returns
const DoubleTab&
Signification: reference constante sur le tableau des valeurs
Contraintes:
Definition at line 193 of file Roue.h.
{
  return valeurs_;
}
References valeurs_.
Referenced by Champ_Inc_base::futur(), Ch_front_var_instationnaire_dep::initialiser(), Champ_Inc_base::lire_donnees(), Champ_Inc_base::passe(), Champ_front_uniforme::readOn(), Champ_Inc_base::valeurs(), Champ_front_uniforme::valeurs_au_temps(), Champ_front_vide::valeurs_au_temps(), and Ch_front_var_stationnaire::valeurs_au_temps().
Member Data Documentation
futur_
Roue_ptr Roue::futur_ private
Definition at line 125 of file Roue.h.
Referenced by ajouter_case(), avancer(), futur(), supprimer_case(), and ~Roue().
nb_cases_
int Roue::nb_cases_ private
Definition at line 122 of file Roue.h.
Referenced by ajouter_case(), dimensionner(), fixer_nb_cases(), futur(), nb_cases(), operator=(), passe(), Roue(), supprimer_case(), and ~Roue().
passe_
Roue_ptr Roue::passe_ private
Definition at line 124 of file Roue.h.
Referenced by ajouter_case(), passe(), reculer(), supprimer_case(), and ~Roue().
temps_
double Roue::temps_ private
Definition at line 121 of file Roue.h.
Referenced by changer_temps(), operator=(), supprimer_case(), and temps().
valeurs_
DoubleTab Roue::valeurs_ private
Definition at line 123 of file Roue.h.
Referenced by dimensionner(), operator=(), Roue(), supprimer_case(), valeurs(), and ~Roue().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Roue.h
src/Kernel/Utilitaires/Roue.cpp