TRUST: Terme_Source_Acceleration_VDF_Face Class Reference
Terme_Source_Acceleration_VDF_Face Class Reference
Terme source d'acceleration specialise pour la discretisation VDF.
#include <Terme_Source_Acceleration_VDF_Face.h>
Public Member Functions
Terme_Source_Acceleration_VDF_Face ()
~Terme_Source_Acceleration_VDF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_champ_rho (const Champ_base &champ_rho) override
Associe le champ de masse volumique=>
Le terme source calcule sera alors homogene a d/dt(integrale(rho*v)).
Parametre: champ_rho
Signification: un champ de type Champ_Fonc_P0_VDF qui sera utilise
lors des appels a "ajouter()" pour evaluer la masse volumique.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
Ajoute le terme (la_source_ * rho * volume_entrelace) au champ resu.
On suppose que resu est discretise comme la vitesse en VDF.
Effet de bord:
On met (la_source_ * rho) dans terme_source_post_.
int has_interface_blocs () const override
Public Member Functions inherited from Terme_Source_Acceleration
~Terme_Source_Acceleration () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Terme_Source_Acceleration ()
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
resu=0; ajouter(resu); (appel a ajouter() de la classe derivee)
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const override
Methode surchargee de Source_base.
Les mots compris sont:
"ACCELERATION" => renvoie terme_source_post_, homogene a d/dt(rho*v)
Attention a l'effet de bord de ajouter() (voir commentaires de ajouter())
const Champ_Don & champ_vitesse () const
const Champ_Don & omega () const
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Acceleration_VDF_Face & self_cast (Objet_U &)
static const Terme_Source_Acceleration_VDF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Terme_Source_Acceleration
static const Type_info * info ()
static Terme_Source_Acceleration & self_cast (Objet_U &)
static const Terme_Source_Acceleration & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Terme_Source_Acceleration
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
Appel a Terme_Source_Acceleration::lire_data.
const DoubleTab & calculer_vitesse_faces (DoubleTab &v_faces_stockage) const override
Calcul des trois composantes du champ de vitesse fluide au centre
de chaque face. Le resultat est stocke dans v_faces_stockage et on renvoie
une reference au tableau. Pas d'espace virtuel dans le tableau.
La composante normale a la face est deja connue: c'est la valeur discrete.
Les autres composantes sont calculees en faisant la moyenne des vitesse
des faces des elements voisins qui ont la bonne orientation, ponderee
par le volume de l'element.
Traitement des bords : on prend la vitesse de l'element voisin (a priori
pas bon pour les conditions aux limites de vitesse imposee au bord,
mais le vpoint est corrige ensuite pour imposer la vitesse).
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Methode appelee par Source_base::completer() apres associer_zones
Remplit les ref. aux zones et zone_cl.
Protected Member Functions inherited from Terme_Source_Acceleration
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
Appel a Terme_Source_Acceleration::lire_data.
virtual void lire_data (Entree &s)
Methode appelee par readOn des classes derivees
Terme_Source_Acceleration_VDF_Face, ...
Le format attendu est le suivant
{
[ omega Un_Champ_uniforme
domegadt Un_Champ_uniforme
centre_rotation Un_Champ_uniforme
option TERME_COMPLET | CORIOLIS_SEUL | ENTRAINEMENT_SEUL ]
[ acceleration Un_Champ_uniforme ]
}
Un_Champ_uniforme est typiquement:
Champ_Uniforme 3 x y z
ou
Champ_Fonc_t DOM 3 fx(t) fy(t) fz(t)
virtual const Champ_Fonc_base & get_terme_source_post () const
virtual Champ_Fonc & get_set_terme_source_post () const
virtual const DoubleTab & calculer_vitesse_faces (DoubleTab &stockage) const =0
const DoubleTab & calculer_la_source (DoubleTab &src_faces) const
Calcul de la valeur du champ la_source aux faces en fonction de
- calculer_vitesse_faces()
- champ_acceleration_
- omega_
- domegadt_
- centre_rotation_
Parametre: champ_source
Signification: un champ discretise aux elements de la zone_VF dans lequel
on stocke le resultat du calcul. Espace virtuel a jour.
virtual const Navier_Stokes_std & get_eq_hydraulique () const
Renvoie eq_hydraulique_ !
void mettre_a_jour (double temps) override
Evalue les champs d'acceleration et de rotation au temps t.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Ref_Zone_VDF la_zone_VDF_
Ref_Zone_Cl_VDF la_zone_Cl_VDF_
Ref_Champ_base ref_rho_
Additional Inherited Members
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Terme source d'acceleration specialise pour la discretisation VDF.
See also
Terme_Source_Acceleration
Definition at line 28 of file Terme_Source_Acceleration_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Acceleration_VDF_Face()
Terme_Source_Acceleration_VDF_Face::Terme_Source_Acceleration_VDF_Face ()
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
~Terme_Source_Acceleration_VDF_Face()
Terme_Source_Acceleration_VDF_Face::~Terme_Source_Acceleration_VDF_Face ()
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Terme_Source_Acceleration_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Ajoute le terme (la_source_ * rho * volume_entrelace) au champ resu.
On suppose que resu est discretise comme la vitesse en VDF.
Effet de bord:
On met (la_source_ * rho) dans terme_source_post_.
Reimplemented from Source_base.
Definition at line 116 of file Terme_Source_Acceleration_VDF_Face.cpp.
{
  const Zone_VDF&    zone_VDF           = la_zone_VDF_.valeur();
  const Zone_Cl_VDF& zone_Cl_VDF        = la_zone_Cl_VDF_.valeur();
  const IntTab&      face_voisins       = zone_VDF.face_voisins();
  const IntVect&     orientation        = zone_VDF.orientation();
  const DoubleVect& porosite_surf      = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  DoubleTab& s_face = get_set_terme_source_post().valeur().valeurs();
  s_face = 0.;
// Calcul de la_source_ en fonction des champs d'acceleration et de la
// vitesse du fluide.
  const int dim     = Objet_U::dimension;
  const int nb_faces = secmem.dimension(0);
  DoubleTab acceleration_aux_faces(nb_faces, dim);
  calculer_la_source(acceleration_aux_faces);
// Boucle sur les conditions limites pour traiter les faces de bord
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
// Si face de Dirichlet ou de Symetrie on ne fait rien
// Si face de Neumann on calcule la contribution au terme source
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = le_bord.num_premiere_face();
      const int nfin = ndeb + le_bord.nb_faces();
      TSAVDF_ajouter_liste_faces(ndeb, nfin,
                                 volumes_entrelaces,
                                 la_zone_VDF_.valeur().volumes(),
                                 porosite_surf,
                                 orientation,
                                 face_voisins,
                                 ref_rho_,
                                 acceleration_aux_faces,
                                 s_face,
                                 secmem);
    }
// Boucle sur les faces internes
  {
    const int ndeb = zone_VDF.premiere_face_int();
    const int nfin = zone_VDF.nb_faces();
    TSAVDF_ajouter_liste_faces(ndeb, nfin,
                               volumes_entrelaces,
                               la_zone_VDF_.valeur().volumes(),
                               porosite_surf,
                               orientation,
                               face_voisins,
                               ref_rho_,
                               acceleration_aux_faces,
                               s_face,
                               secmem);
  }
  {
// Force la periodicite
    for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
        if (sub_type(Periodique,la_cl.valeur()))
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
            const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
            int nb_faces_bord=le_bord.nb_faces();
            ArrOfInt fait(nb_faces_bord);
            fait = 0;
            for (int ind_face=0; ind_face<nb_faces_bord; ind_face++)
              {
                if (fait[ind_face] == 0)
                  {
                    int ind_face_associee = la_cl_perio.face_associee(ind_face);
                    fait[ind_face] = 1;
                    fait[ind_face_associee] = 1;
                    int face = le_bord.num_face(ind_face);
                    int face_associee = le_bord.num_face(ind_face_associee);
                    double val = 0.5*(secmem(face_associee)+secmem(face));
                    secmem(face)=secmem(face_associee) = val;
                  }//!< if fait
              }//!< for face
          }//!< sub_type Perio
      }
  }
}
References Terme_Source_Acceleration::calculer_la_source(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Periodique::face_associee(), face_associee, Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Terme_Source_Acceleration::get_set_terme_source_post(), la_zone_Cl_VDF_, la_zone_VDF_, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, ref_rho_, sub_type, TSAVDF_ajouter_liste_faces(), Deriv_Champ_Fonc_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Don_base::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
Referenced by Acceleration_QC_VDF_Face::ajouter_mere().
associer_champ_rho()
void Terme_Source_Acceleration_VDF_Face::associer_champ_rho (const Champ_base & champ_rho) override virtual
Associe le champ de masse volumique=>
Le terme source calcule sera alors homogene a d/dt(integrale(rho*v)).
Parametre: champ_rho
Signification: un champ de type Champ_Fonc_P0_VDF qui sera utilise
lors des appels a "ajouter()" pour evaluer la masse volumique.
Reimplemented from Source_base.
Definition at line 291 of file Terme_Source_Acceleration_VDF_Face.cpp.
{
// Il faut que le champ soit discretise aux elements: possibilite
// d'autoriser d'autres types si besoin (Champ_Don, Champ_Inc, etc.)
// du moment que c'est des champs P0.
  if (!sub_type(Champ_Fonc_P0_VDF, champ_rho))
    {
      Cerr << "Erreur dans Terme_Source_Acceleration_VDF_Face::associer_champ_rho" << finl;
      Cerr << " Le champ de masse volumique doit etre de type Champ_Fonc_P0_VDF" << finl;
      Cerr << " Type du champ associe : " << champ_rho.que_suis_je() << finl;
      Cerr << " Nom du champ associe :  " << champ_rho.le_nom() << finl;
      assert(0);
      exit();
    }
  ref_rho_ = champ_rho;
}
References Cerr, Process::exit(), finl, Field_base::le_nom(), Objet_U::que_suis_je(), ref_rho_, and sub_type.
associer_zones()
void Terme_Source_Acceleration_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Methode appelee par Source_base::completer() apres associer_zones
Remplit les ref. aux zones et zone_cl.
Implements Source_base.
Definition at line 41 of file Terme_Source_Acceleration_VDF_Face.cpp.
{
  if (je_suis_maitre())
    Cerr << "Terme_Source_Acceleration_VDF_Face::associer_zones" << finl;
  la_zone_VDF_    = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF_ = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References Cerr, finl, Process::je_suis_maitre(), la_zone_Cl_VDF_, la_zone_VDF_, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer_vitesse_faces()
const DoubleTab & Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces (DoubleTab & v_faces_stockage) const override protected virtual
Calcul des trois composantes du champ de vitesse fluide au centre
de chaque face. Le resultat est stocke dans v_faces_stockage et on renvoie
une reference au tableau. Pas d'espace virtuel dans le tableau.
La composante normale a la face est deja connue: c'est la valeur discrete.
Les autres composantes sont calculees en faisant la moyenne des vitesse
des faces des elements voisins qui ont la bonne orientation, ponderee
par le volume de l'element.
Traitement des bords : on prend la vitesse de l'element voisin (a priori
pas bon pour les conditions aux limites de vitesse imposee au bord,
mais le vpoint est corrige ensuite pour imposer la vitesse).
< volumes des elements
< Ponderation par le volume
Implements Terme_Source_Acceleration.
Definition at line 214 of file Terme_Source_Acceleration_VDF_Face.cpp.
{
  const Zone_VDF&    zone_VDF      = la_zone_VDF_.valeur();
  const IntVect&     orientation   = zone_VDF.orientation();
  const IntTab&      faces_voisins = zone_VDF.face_voisins();
  const DoubleVect& volumes       = zone_VDF.volumes();  //!< volumes des elements
  const IntTab&      elem_faces    = zone_VDF.elem_faces();
  const DoubleTab&   v_faces  = get_eq_hydraulique().inconnue()->valeurs();
  const int       dim      = Objet_U::dimension;
  const int       nb_faces = v_faces.dimension(0);
  v_faces_stockage.resize(nb_faces, dim);
  int i_face;
  ArrOfDouble composante_vitesse(3);
  for (i_face = 0; i_face < nb_faces; i_face++)
    {
      const int orientation_face = orientation(i_face);
      composante_vitesse=0;
      int composante;
// Numeros des deux elements voisins de la face (-1 si face de bord)
      int elem[2];
      elem[0] = faces_voisins(i_face, 0);
      elem[1] = faces_voisins(i_face, 1);
// Volumes de ces deux elements (0. si pas de voisin)
      double volume_elem[2] = {0., 0.};
      if (elem[0] >= 0)
        volume_elem[0] = volumes(elem[0]);
      if (elem[1] >= 0)
        volume_elem[1] = volumes(elem[1]);
      const double i_volume_total = 1. / (volume_elem[0] + volume_elem[1]);
      for (composante = 0; composante < dim; composante++)
        {
          if (composante == orientation_face)
            {
              composante_vitesse[composante] = v_faces(i_face);
            }
          else
            {
// Calcul de la moyenne des vitesses sur les faces voisines
// qui ont la bonne orientation:
              composante_vitesse[composante] = 0.;
              int i_elem;
              for (i_elem = 0; i_elem < 2; i_elem++)
                {
                  if (elem[i_elem] >= 0)
                    {
                      const int element = elem[i_elem];
                      const int face1 = elem_faces(element, composante);
                      const int face2 = elem_faces(element, composante + dim);
                      const double v1 = v_faces(face1);
                      const double v2 = v_faces(face2);
                      const double p = volume_elem[i_elem]; //!< Ponderation par le volume
                      composante_vitesse[composante] += (v1 + v2) * 0.5 * p;
                    }
                }
              composante_vitesse[composante] *= i_volume_total;
            }
        }
      for (composante = 0; composante < dim; composante++)
        {
          v_faces_stockage(i_face, composante) = composante_vitesse[composante];
        }
    }
  return v_faces_stockage;
}
References composante(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), Terme_Source_Acceleration::get_eq_hydraulique(), Navier_Stokes_std::inconnue(), la_zone_VDF_, Zone_VDF::orientation(), TRUSTTab< _TYPE_ >::resize(), Ref_Zone_VDF::valeur(), Champ_Inc::valeurs(), and Zone_VF::volumes().
cree_instance()
Objet_U * Terme_Source_Acceleration_VDF_Face::cree_instance () static
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
dimensionner_blocs()
void Terme_Source_Acceleration_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 34 of file Terme_Source_Acceleration_VDF_Face.h.
{}
duplique()
int Terme_Source_Acceleration_VDF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
get_info()
const Type_info * Terme_Source_Acceleration_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Acceleration.
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
has_interface_blocs()
int Terme_Source_Acceleration_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 36 of file Terme_Source_Acceleration_VDF_Face.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_Acceleration_VDF_Face::info () static
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
printOn()
Sortie & Terme_Source_Acceleration_VDF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_Acceleration.
Definition at line 26 of file Terme_Source_Acceleration_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
Referenced by Acceleration_QC_VDF_Face::printOn().
readOn()
Entree & Terme_Source_Acceleration_VDF_Face::readOn (Entree & s) override protected virtual
Appel a Terme_Source_Acceleration::lire_data.
Reimplemented from Terme_Source_Acceleration.
Definition at line 32 of file Terme_Source_Acceleration_VDF_Face.cpp.
{
  lire_data(s);
  return s;
}
References Terme_Source_Acceleration::lire_data().
Referenced by Acceleration_QC_VDF_Face::readOn().
self_cast() [1/2]
const Terme_Source_Acceleration_VDF_Face & Terme_Source_Acceleration_VDF_Face::self_cast (const Objet_U & r) static
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
self_cast() [2/2]
Terme_Source_Acceleration_VDF_Face & Terme_Source_Acceleration_VDF_Face::self_cast (Objet_U & r) static
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Acceleration_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Terme_Source_Acceleration_VDF_Face.cpp.
Member Data Documentation
info_obj
const Type_info Terme_Source_Acceleration_VDF_Face::info_obj static
Definition at line 30 of file Terme_Source_Acceleration_VDF_Face.h.
la_zone_Cl_VDF_
Ref_Zone_Cl_VDF Terme_Source_Acceleration_VDF_Face::la_zone_Cl_VDF_ private
Definition at line 48 of file Terme_Source_Acceleration_VDF_Face.h.
Referenced by ajouter_blocs(), and associer_zones().
la_zone_VDF_
Ref_Zone_VDF Terme_Source_Acceleration_VDF_Face::la_zone_VDF_ private
Definition at line 47 of file Terme_Source_Acceleration_VDF_Face.h.
Referenced by ajouter_blocs(), associer_zones(), and calculer_vitesse_faces().
ref_rho_
Ref_Champ_base Terme_Source_Acceleration_VDF_Face::ref_rho_ private
Definition at line 51 of file Terme_Source_Acceleration_VDF_Face.h.
Referenced by ajouter_blocs(), and associer_champ_rho().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_Acceleration_VDF_Face.h
src/VDF/Sources/Terme_Source_Acceleration_VDF_Face.cpp