TRUST: Eval_Diff_VDF_Face< DERIVED_T > Class Template Reference
Eval_Diff_VDF_Face< DERIVED_T > Class Template Reference
class Eval_Diff_VDF_Face
Evaluateur VDF pour la diffusion
Le champ diffuse est un Champ_Face
#include <Eval_Diff_VDF_Face.h>
Public Member Functions
double surface_ (int i, int j) const
double porosity_ (int i, int j) const
double nu_mean_2pts (int i=0, int j=0, int compo=0) const
double nu_mean_4pts (int i, int j, int k, int l, int compo=0) const
double nu_lam (int i, int j=0) const
double nu_lam_mean_4pts (int i, int j, int k, int l, int compo=0) const
double nu_lam_mean_2pts (int i, int j, int compo=0) const
double nu_turb (int i, int compo=0) const
double tau_tan (int, int) const
bool uses_wall_law () const
bool uses_mod_turb () const
DoubleTab k_elem () const
int calculer_fa7_sortie_libre () const
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_arete_periodicite () const
int calculer_arete_symetrie_paroi () const
int calculer_arete_symetrie_fluide () const
int calculer_arete_coin_fluide () const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
double flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int) const
void flux_arete_coin_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_coin_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void coeffs_fa7_elem (int, int, int, double &aii, double &ajj) const
void coeffs_fa7_sortie_libre (int, const Neumann_sortie_libre &, double &aii, double &ajj) const
void coeffs_arete_interne (int, int, int, int, double &aii, double &ajj) const
void coeffs_arete_mixte (int, int, int, int, double &aii, double &ajj) const
void coeffs_arete_symetrie (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_paroi (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_paroi_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_periodicite (int, int, int, int, double &aii, double &ajj) const
void coeffs_arete_symetrie_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_symetrie_paroi (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_coin_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
double secmem_fa7_elem (int, int, int) const
double secmem_fa7_sortie_libre (int, const Neumann_sortie_libre &, int) const
double secmem_arete_interne (int, int, int, int) const
double secmem_arete_mixte (int, int, int, int) const
double secmem_arete_symetrie (int, int, int, int) const
double secmem_arete_paroi (int, int, int, int) const
void secmem_arete_periodicite (int, int, int, int, double &, double &) const
void secmem_arete_fluide (int, int, int, int, double &, double &) const
void secmem_arete_paroi_fluide (int, int, int, int, double &, double &) const
void secmem_arete_symetrie_fluide (int, int, int, int, double &, double &) const
double secmem_arete_symetrie_paroi (int, int, int, int) const
void secmem_arete_coin_fluide (int, int, int, int, double &, double &) const
void coeffs_fa7_elem (int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_fa7_sortie_libre (int, const Neumann_sortie_libre &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_interne (int, int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_mixte (int, int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_symetrie (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_paroi (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_paroi_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_periodicite (int, int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_symetrie_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_symetrie_paroi (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_coin_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void secmem_fa7_elem (int, int, int, DoubleVect &flux) const
void secmem_fa7_sortie_libre (int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void secmem_arete_interne (int, int, int, int, DoubleVect &flux) const
void secmem_arete_mixte (int, int, int, int, DoubleVect &flux) const
void secmem_arete_symetrie (int, int, int, int, DoubleVect &) const
void secmem_arete_paroi (int, int, int, int, DoubleVect &) const
void secmem_arete_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_paroi_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_periodicite (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_symetrie_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_symetrie_paroi (int, int, int, int, DoubleVect &) const
void secmem_arete_coin_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
Static Public Attributes
static constexpr bool IS_VAR = false
static constexpr bool IS_TURB = false
Detailed Description
template<typename DERIVED_T>
class Eval_Diff_VDF_Face< DERIVED_T >
class Eval_Diff_VDF_Face
Evaluateur VDF pour la diffusion
Le champ diffuse est un Champ_Face
See also:
Eval_VDF_Face2, Evaluateur_VDF
Definition at line 41 of file Eval_Diff_VDF_Face.h.
Member Function Documentation
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_coin_fluide () const [inline]
Definition at line 74 of file Eval_Diff_VDF_Face.h.
  {
    Cerr << "arete_coin_fluide not coded for this scheme." << finl;
    Cerr << "For TRUST support: code like Eval_Amont_VDF_Face::flux_arete_coin_fluide()" << finl;
    Process::exit();
    return 1;
  }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_fluide () const [inline]
Definition at line 65 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_interne () const [inline]
Definition at line 69 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_mixte () const [inline]
Definition at line 70 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_paroi () const [inline]
Definition at line 66 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_paroi_fluide () const [inline]
Definition at line 67 of file Eval_Diff_VDF_Face.h.
{ return DERIVED_T::IS_TURB ? 0 : 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_periodicite () const [inline]
Definition at line 71 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_symetrie () const [inline]
Definition at line 68 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_symetrie_fluide () const [inline]
Definition at line 73 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_arete_symetrie_paroi () const [inline]
Definition at line 72 of file Eval_Diff_VDF_Face.h.
{ return 1; }
template<typename DERIVED_T> int Eval_Diff_VDF_Face< DERIVED_T >::calculer_fa7_sortie_libre () const [inline]
Definition at line 64 of file Eval_Diff_VDF_Face.h.
{ return DERIVED_T::IS_TURB ? 1 : 0; }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_coin_fluide (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 170 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_coin_fluide (int , int , int , int , double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 138 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_fluide (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 165 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_fluide (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 331 of file Eval_Diff_VDF_Face.h.
{
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int ori= orientation(fac3);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double surfporos = surface(fac3)*porosite(fac3);
  double dist1 = dist_norm_bord(fac1);
  double dist2 = dist_face(fac1,fac2,ori);
  double tau = signe/dist1;
  double tau_tr = 1/dist2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      aii3_4 = ((tau+tau_tr)*visc_lam + reyn)*surf*poros;
      aii1_2 = ajj1_2  = ((tau+tau_tr)*visc_lam + reyn)*surfporos;
    }
  else
    {
      aii3_4 = (tau*visc_lam + reyn)*surf*poros;
      aii1_2 = ajj1_2  = (tau_tr*visc_lam + reyn)*surfporos;
    }
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_interne (int , int , int , int , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 161 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_interne (int fac1, int fac2, int fac3, int fac4, double & aii, double & ajj) const [inline]
Definition at line 426 of file Eval_Diff_VDF_Face.h.
{
  int ori1=orientation(fac1);
  int ori3 = orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int elem3 = elem_(fac4,0);
  int elem4 = elem_(fac4,1);
  double visc_lam = nu_lam_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double visc_turb = nu_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double tau = 1/dist_face(fac3,fac4,ori1);
  double tau_tr = 1/dist_face(fac1,fac2,ori3);
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if (DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    aii = ajj = (reyn + visc_lam*(tau+tau_tr))*surf*poros;
  else
    aii = ajj = (reyn + visc_lam*tau)*surf*poros;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_mixte (int , int , int , int , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 162 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_mixte (int fac1, int fac2, int fac3, int fac4, double & aii, double & ajj) const [inline]
Definition at line 502 of file Eval_Diff_VDF_Face.h.
{
  if (inconnue->valeurs()[fac4]*inconnue->valeurs()[fac3] != 0)
    {
      int ori1 = orientation(fac1);
      int ori3 = orientation(fac3);
      int elem[4];
      elem[0] = elem_(fac3,0);
      elem[1] = elem_(fac3,1);
      elem[2] = elem_(fac4,0);
      elem[3] = elem_(fac4,1);
      double visc_lam_temp=0;
      double visc_turb_temp=0;
      for (int i=0; i<4; i++)
        if (elem[i] != -1)
          {
            visc_lam_temp += nu_lam(elem[i]);
            visc_turb_temp += nu_turb(elem[i]);
          }
      visc_lam_temp/=3.0;
      visc_turb_temp/=3.0;
      double visc_lam = DERIVED_T::IS_VAR ? visc_lam_temp : nu_lam(0);
      double visc_turb = visc_turb_temp;
      double surf = surface_(fac1,fac2);
      double poros = porosity_(fac1,fac2);
      double tau = 1/dist_face(fac3,fac4,ori1);
      double tau_tr = 1/dist_face(fac1,fac2,ori3);
      double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
      // XXX : if we regroup => SOME TEST CASES BROKE UP !
      if (DERIVED_T::IS_TURB && DERIVED_T::IS_VAR)
        aii = ajj = (reyn + visc_lam*(tau+tau_tr))* surf * poros;
      else
        aii = ajj= surf * visc_lam * poros * tau;
    }
  else
    aii=ajj=0;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_paroi (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 164 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_paroi (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 602 of file Eval_Diff_VDF_Face.h.
{
  if ( !uses_wall_law())
    {
      int elem1 = elem_(fac3,0);
      int elem2 = elem_(fac3,1);
      if (elem1==-1)
        elem1 = elem2;
      else if (elem2==-1)
        elem2 = elem1;
      int ori = orientation(fac3);
      double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
      double visc_turb = nu_mean_2pts(elem1,elem2,ori);
      double dist = dist_norm_bord(fac1);
      double surf = surface_(fac1,fac2);
      aii1_2 = ajj1_2 = 0;
      aii3_4 = (DERIVED_T::IS_TURB && DERIVED_T::IS_VAR) ? signe*surf*(visc_lam+visc_turb)/dist :
               signe*surf*visc_lam/dist;
    }
  else
    aii3_4 = aii1_2 = ajj1_2 = 0;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_paroi_fluide (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 166 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_paroi_fluide (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 727 of file Eval_Diff_VDF_Face.h.
{
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int ori= orientation(fac3);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1, fac2);
  double surfporos = surface(fac3)*porosite(fac3);
  double dist1 = dist_norm_bord(fac1);
  double dist2 = dist_face(fac1,fac2,ori);
  double tau = signe/dist1;
  double tau_tr = 1/dist2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      aii3_4 = ((tau+tau_tr)*visc_lam + reyn)*surf*poros;
      aii1_2 = ajj1_2 =((tau+tau_tr)*visc_lam + reyn)*surfporos;
    }
  else
    {
      aii3_4 = (tau*visc_lam + reyn)*surf*poros;
      aii1_2 = ajj1_2 =(tau_tr*visc_lam + reyn)*surfporos;
    }
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_periodicite (int , int , int , int , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 167 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_periodicite (int fac1, int fac2, int fac3, int fac4, double & aii, double & ajj) const [inline]
Definition at line 835 of file Eval_Diff_VDF_Face.h.
{
  int ori1 = orientation(fac1);
  int ori3 = orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int elem3 = elem_(fac4,0);
  int elem4 = elem_(fac4,1);
  double dist3_4 = dist_face_period(fac3,fac4,ori1);
  double dist1_2 = dist_face_period(fac1,fac2,ori3);
  double visc_lam = nu_lam_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double visc_turb = nu_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1, fac2);
  double tau = 1/dist3_4;
  double tau_tr = 1/dist1_2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr) * visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    aii = ajj = (reyn + visc_lam*(tau+tau_tr))* surf * poros;
  else
    aii = ajj = (reyn + visc_lam*tau) * surf * poros;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_symetrie (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 163 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_symetrie (int , int , int , int , double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 131 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_symetrie_fluide (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 168 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_symetrie_fluide (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 948 of file Eval_Diff_VDF_Face.h.
{
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int ori= orientation(fac3);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double dist1 = dist_norm_bord(fac1);
  double dist2 = dist_face(fac1,fac2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double surfporos = surface(fac3)*porosite(fac3);
  double tau = signe/dist1;
  double tau_tr = 1/dist2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      aii3_4 = ((tau+tau_tr)*visc_lam + reyn) * surf * poros;
      aii1_2 = ajj1_2  = ((tau+tau_tr)*visc_lam + reyn) * surfporos;
    }
  else
    {
      aii3_4 = (tau*visc_lam + reyn)*surf*poros;
      aii1_2 = ajj1_2  = DERIVED_T::IS_VAR ? 0.5 * tau_tr * visc_lam * surfporos : (tau_tr * visc_lam + reyn) * surfporos;
    }
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_symetrie_paroi (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Definition at line 169 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_arete_symetrie_paroi (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Definition at line 1050 of file Eval_Diff_VDF_Face.h.
{
  if ( !uses_wall_law() )
    {
      int elem1 = elem_(fac3,0);
      int elem2 = elem_(fac3,1);
      int ori = orientation(fac3);
      double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
      double visc_turb = nu_mean_2pts(elem1,elem2,ori);
      double dist = dist_norm_bord(fac1);
      double surf = surface_(fac1,fac2);
      aii1_2 = ajj1_2 = 0;
      aii3_4 = DERIVED_T::IS_TURB ? ( DERIVED_T::IS_VAR ? signe * surf * (visc_lam + visc_turb) / dist : 0.0 )
                 : signe * surf * visc_lam / dist;
    }
  else
    aii3_4 = aii1_2 = ajj1_2 =0;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_fa7_elem (int , int , int , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 159 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_fa7_elem (int elem, int fac1, int fac2, double & aii, double & ajj) const [inline]
Definition at line 888 of file Eval_Diff_VDF_Face.h.
{
  int ori = orientation(fac1);
  double tau = 1/dist_face(fac1,fac2,ori);
  double surf = 0.5*(surface(fac1)*porosite(fac1)+surface(fac2)*porosite(fac2));
  double visc_lam = nu_lam(elem);
  // On considere que l energie est dans la pression
  //  double reyn = 2./3.*k_elem - 2.*dv_diffusivite_turbulente(elem)*tau ;
  double reyn = DERIVED_T::IS_TURB ? - 2.*nu_turb(elem)*tau : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    aii = ajj =(-reyn +2.*visc_lam*tau) * surf;
  else
    aii = ajj =(-reyn + visc_lam*tau) * surf;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_fa7_sortie_libre (int , const Neumann_sortie_libre & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 160 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::coeffs_fa7_sortie_libre (int , const Neumann_sortie_libre & , double & aii, double & ajj) const [inline]
Definition at line 128 of file Eval_Diff_VDF_Face.h.
{ aii = ajj = 0; }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_coin_fluide (const DoubleTab & , int , int , int , int , double & , double &) const [inline]
Definition at line 96 of file Eval_Diff_VDF_Face.h.
  {
    Cerr << "arete_coin_fluide not coded for this scheme." << finl;
    Cerr << "For TRUST support: code like Eval_Amont_VDF_Face::flux_arete_coin_fluide()" << finl;
    Process::exit();
  }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_coin_fluide (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 117 of file Eval_Diff_VDF_Face.h.
  {
    Cerr << "arete_coin_fluide not coded for this scheme." << finl;
    Cerr << "For TRUST support: code like Eval_Amont_VDF_Face::flux_arete_coin_fluide()" << finl;
    Process::exit();
  };
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_fluide (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 112 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 291 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord().
{
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int ori= orientation(fac3);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double surfporos = surface(fac3)*porosite(fac3);
  double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)+
                        Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl));
  double dist1 = dist_norm_bord(fac1);
  double dist2 = dist_face(fac1,fac2,ori);
  double tau = signe * (vit_imp - inco[fac3])/dist1;
  double tau_tr = (inco[fac2] - inco[fac1])/dist2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      flux3 = ((tau+tau_tr)*visc_lam + reyn)*surf*poros;
      flux1_2 = ((tau+tau_tr)*visc_lam + reyn)*surfporos;
    }
  else
    {
      flux3 = (tau*visc_lam + reyn)*surf*poros;
      flux1_2 = (tau_tr*visc_lam + reyn)*surfporos;
    }
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_interne (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 108 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Definition at line 396 of file Eval_Diff_VDF_Face.h.
{
  double flux;
  int ori1=orientation(fac1);
  int ori3 = orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int elem3 = elem_(fac4,0);
  int elem4 = elem_(fac4,1);
  double visc_lam = nu_lam_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double visc_turb = nu_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double tau = (inco[fac4]-inco[fac3])/dist_face(fac3,fac4,ori1);
  double tau_tr = (inco[fac2]-inco[fac1])/dist_face(fac1,fac2,ori3);
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if (DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    flux = (reyn + visc_lam*(tau+tau_tr))* surf*poros;
  else
    flux = (reyn + visc_lam*tau)*surf*poros;
  return flux;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_mixte (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 109 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Definition at line 456 of file Eval_Diff_VDF_Face.h.
{
  double flux=0;
  if (inco[fac4]*inco[fac3] != 0)
    {
      int ori1 = orientation(fac1);
      int ori3 = orientation(fac3);
      int elem[4];
      elem[0] = elem_(fac3,0);
      elem[1] = elem_(fac3,1);
      elem[2] = elem_(fac4,0);
      elem[3] = elem_(fac4,1);
      double visc_lam_temp=0;
      double visc_turb_temp=0;
      for (int i=0; i<4; i++)
        if (elem[i] != -1)
          {
            visc_lam_temp += nu_lam(elem[i]);
            visc_turb_temp += nu_turb(elem[i]);
          }
      visc_lam_temp/=3.0;
      visc_turb_temp/=3.0;
      double visc_lam = DERIVED_T::IS_VAR ? visc_lam_temp : nu_lam(0);
      double visc_turb = visc_turb_temp;
      double surf = surface_(fac1,fac2);
      double poros = porosity_(fac1,fac2);
      double tau = (inco[fac4]-inco[fac3])/dist_face(fac3,fac4,ori1);
      double tau_tr = (inco[fac2]-inco[fac1])/dist_face(fac1,fac2,ori3);
      double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
      if (DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
        flux = (reyn + visc_lam*(tau+tau_tr)) * surf * poros;
      else
        flux = tau * surf * visc_lam * poros;
    }
  return flux;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 111 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe) const [inline]
Definition at line 548 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord().
{
  double flux;
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int ori = orientation(fac3);
  double vit = inco(fac3);
  double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)+
                        Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl));
  if ( !uses_wall_law() )
    {
      int elem1 = elem_(fac3,0);
      int elem2 = elem_(fac3,1);
      if (elem1==-1)
        elem1 = elem2;
      else if (elem2==-1)
        elem2 = elem1;
      double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
      double visc_turb = nu_mean_2pts(elem1,elem2,ori);
      double dist = dist_norm_bord(fac1);
      double tau  = signe*(vit_imp - inco[fac3])/dist;
      double surf = surface_(fac1,fac2);
      if (DERIVED_T::IS_TURB && DERIVED_T::IS_VAR)
        flux = tau*surf*(visc_lam+visc_turb);
      else
        flux = tau*surf*visc_lam;
    }
  else
    {
      // On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
      int signe_terme;
      if ( vit < vit_imp )
        signe_terme = -1;
      else
        signe_terme = 1;
      //30/09/2003  YB : influence de signe terme eliminee, signe pris en compte dans la loi de paroi
      signe_terme = 1;
      double tau1 = tau_tan(rang1,ori)*0.5*surface(fac1);
      double tau2 = tau_tan(rang2,ori)*0.5*surface(fac2);
      double coef = tau1+tau2;
      flux = signe_terme*coef;
    }
  return flux;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi_fluide (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 113 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 683 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), and est_egal().
{
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int ori= orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double vit_imp;
  // On ne sait pas qui de fac1 ou de fac2 est la face de paroi
  if (est_egal(inco[fac1],0)) // fac1 est la face de paroi
    vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl);
  else  // fac2 est la face de paroi
    vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl);
  double dist1 = dist_norm_bord(fac1);
  double dist2 =dist_face(fac1,fac2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1, fac2);
  double surfporos = surface(fac3)*porosite(fac3);
  double tau = signe * (vit_imp - inco[fac3])/dist1;
  double tau_tr = (inco[fac2] - inco[fac1])/dist2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      flux3 = ((tau+tau_tr)*visc_lam + reyn) * surf * poros;
      flux1_2 = ((tau+tau_tr)*visc_lam + reyn) * surfporos;
    }
  else
    {
      flux3 = (tau*visc_lam + reyn) * surf * poros;
      flux1_2 = (tau_tr*visc_lam + reyn) * surfporos;
    }
}
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, double & flux3_4, double & flux1_2) const [inline]
Definition at line 796 of file Eval_Diff_VDF_Face.h.
{
  int ori1 = orientation(fac1);
  int ori3 = orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int elem3 = elem_(fac4,0);
  int elem4 = elem_(fac4,1);
  double dist3_4 = dist_face_period(fac3,fac4,ori1);
  double dist1_2 = dist_face_period(fac1,fac2,ori3);
  double surf1_2 = surface_(fac1,fac2);
  double poros1_2 = porosity_(fac1, fac2);
  double surf3_4 = surface_(fac3,fac4);
  double poros3_4 = porosity_(fac3, fac4);
  double visc_lam = nu_lam_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double visc_turb = nu_mean_4pts(elem1,elem2,elem3,elem4,ori3);
  double tau = (inco[fac4]-inco[fac3])/dist3_4;
  double tau_tr = (inco[fac2]-inco[fac1])/dist1_2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      flux3_4 = (reyn + visc_lam*(tau+tau_tr)) * surf1_2 * poros1_2;
      flux1_2 = (reyn + visc_lam*(tau+tau_tr)) * surf3_4 * poros3_4;
    }
  else
    {
      flux3_4 = (reyn + visc_lam*tau) * surf1_2 * poros1_2;
      flux1_2 = (reyn + visc_lam*tau_tr) * surf3_4 * poros3_4;
    }
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_periodicite (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 114 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 110 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Definition at line 86 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 909 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord_sym().
{
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int ori= orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double dist1 = dist_norm_bord(fac1);
  double dist2 = dist_face(fac1,fac2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double surfporos = surface(fac3)*porosite(fac3);
  double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang1,ori,la_zcl)+
                        Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang2,ori,la_zcl));
  double tau = signe * (vit_imp - inco[fac3])/dist1;
  double tau_tr = (inco[fac2] - inco[fac1])/dist2;
  double reyn = DERIVED_T::IS_TURB ? (tau + tau_tr)*visc_turb : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    {
      flux3 = ((tau+tau_tr)*visc_lam + reyn) * surf * poros;
      flux1_2 = ((tau+tau_tr)* visc_lam + reyn) * surfporos;
    }
  else
    {
      flux3 = (tau*visc_lam + reyn) * surf * poros;
      flux1_2 = DERIVED_T::IS_VAR ? 0.5 * tau_tr * visc_lam * surfporos : (tau_tr*visc_lam + reyn) * surfporos;
    }
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie_fluide (const DoubleTab & , int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 115 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie_paroi (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe) const [inline]
Definition at line 1011 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord_sym().
{
  double flux;
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int ori = orientation(fac3);
  if ( !uses_wall_law() )
    {
      int elem1 = elem_(fac3,0);
      int elem2 = elem_(fac3,1);
      double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
      double visc_turb = nu_mean_2pts(elem1,elem2,ori);
      double surf =  surface_(fac1,fac2);
      double dist = dist_norm_bord(fac1);
      double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang1,ori,la_zcl)+
                            Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang2,ori,la_zcl));
      double tau  = signe*(vit_imp - inco[fac3])/dist;
      flux = DERIVED_T::IS_TURB ? tau * surf * (visc_lam + visc_turb) : tau * surf * visc_lam;
    }
  else
    {
      // solution retenue pour le calcul du frottement sachant que sur l'une des faces
      // tau_tan vaut 0 car c'est une face qui porte une condition de symetrie
      // On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
      double tau1 = tau_tan(rang1,ori)*0.5*surface(fac1);
      double tau2 = tau_tan(rang2,ori)*0.5*surface(fac2);
      flux = tau1+tau2;
    }
  return flux;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 116 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_fa7_elem (const DoubleTab & , int , int , int , DoubleVect & flux) const [inline]
Definition at line 106 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::flux_fa7_elem (const DoubleTab & inco, int elem, int fac1, int fac2) const [inline]
Definition at line 864 of file Eval_Diff_VDF_Face.h.
{
  double flux;
  int ori=orientation(fac1);
  double dist = dist_face(fac1,fac2,ori);
  double tau = (inco[fac2]-inco[fac1])/dist;
  double surf = 0.5*(surface(fac1)*porosite(fac1)+surface(fac2)*porosite(fac2));
  double visc_lam = nu_lam(elem);
  // On considere que l energie est dans la pression
  double reyn = DERIVED_T::IS_TURB ? - 2.*nu_turb(elem)*tau : 0.0;
  if(DERIVED_T::IS_VAR && DERIVED_T::IS_TURB)
    flux = (-reyn + 2.*visc_lam*tau) * surf ;
  else
    flux = (-reyn + visc_lam*tau) * surf ;
  return flux;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::flux_fa7_sortie_libre (const DoubleTab & , int , const Neumann_sortie_libre & , int , DoubleVect & flux) const [inline]
Definition at line 107 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::flux_fa7_sortie_libre (const DoubleTab & , int , const Neumann_sortie_libre & , int) const [inline]
Definition at line 85 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T > DoubleTab Eval_Diff_VDF_Face< DERIVED_T >::k_elem () const [inline]
Definition at line 259 of file Eval_Diff_VDF_Face.h.
{
  DoubleTab k = static_cast<const DERIVED_T *>(this)->get_k_elem();
  return k;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::nu_lam (int i, int j = 0) const [inline]
Definition at line 210 of file Eval_Diff_VDF_Face.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_2_impl(i,j); // Attention nu_2_impl and not nu_1_impl for Dift ...
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::nu_lam_mean_2pts (int i, int j, int compo = 0) const [inline]
Definition at line 224 of file Eval_Diff_VDF_Face.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_lam_impl_face2(i,j,compo);
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::nu_lam_mean_4pts (int i, int j, int k, int l, int compo = 0) const [inline]
Definition at line 217 of file Eval_Diff_VDF_Face.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_lam_impl_face(i,j,k,l,compo);
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::nu_mean_2pts (int i = 0, int j = 0, int compo = 0) const [inline]
Definition at line 196 of file Eval_Diff_VDF_Face.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_1_impl_face(i, j, compo);
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::nu_mean_4pts (int i, int j, int k, int l, int compo = 0) const [inline]
Definition at line 203 of file Eval_Diff_VDF_Face.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_2_impl_face(i, j, k, l,compo);
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::nu_turb (int i, int compo = 0) const [inline]
Definition at line 231 of file Eval_Diff_VDF_Face.h.
{
  double nu = static_cast<const DERIVED_T *>(this)->nu_t_impl(i,compo);
  return nu;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::porosity_ (int i, int j) const [inline]
Definition at line 278 of file Eval_Diff_VDF_Face.h.
{
  const double poros = (DERIVED_T::IS_VAR || DERIVED_T::IS_TURB) ? 0.5*(porosite(i)+porosite(j)) : 1.0;
  return poros;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_coin_fluide (int , int , int , int , double & , double &) const [inline]
Definition at line 154 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_coin_fluide (int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 187 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_fluide (int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 364 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord().
{
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int ori= orientation(fac3);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double dist = dist_norm_bord(fac1);
  double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)+
                        Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl));
  double tau = signe*vit_imp/dist;
  double reyn = DERIVED_T::IS_TURB ? tau*visc_turb : 0.0;
  // XXX : if we regroup => SOME TEST CASES BROKE UP !
  if(DERIVED_T::IS_TURB)
    flux3 = (tau*visc_lam + reyn)*surf*poros;
  else
    flux3 = tau*surf*visc_lam*poros;
  flux1_2 = 0;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_fluide (int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 182 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_interne (int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 178 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_interne (int , int , int , int) const [inline]
Definition at line 145 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_mixte (int , int , int , int , DoubleVect & flux) const [inline]
Definition at line 179 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_mixte (int , int , int , int) const [inline]
Definition at line 146 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi (int fac1, int fac2, int fac3, int signe) const [inline]
Definition at line 633 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord().
{
  double flux;
  int ori = orientation(fac3);
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  const DoubleTab& inco = inconnue->valeurs();
  double vit = inco(fac3);
  double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)+
                        Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl));
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  if ( !uses_wall_law() )
    {
      double dist = dist_norm_bord(fac1);
      double surf = surface_(fac1,fac2);
      double tau  = DERIVED_T::IS_TURB ? signe*(vit_imp - inco[fac3])/dist : signe * vit_imp/dist;
      flux = (DERIVED_T::IS_TURB && DERIVED_T::IS_VAR) ? tau*surf*(visc_lam+visc_turb) :
             tau * surf * visc_lam;
    }
  else
    {
      // On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
      int signe_terme;
      if ( vit < vit_imp )
        signe_terme = -1;
      else
        signe_terme = 1;
      //30/09/2003  YB : influence de signe terme eliminee, signe pris en compte dans la loi de paroi
      signe_terme = 1;
      double tau1 = tau_tan(rang1,ori)*0.5*surface(fac1);
      double tau2 = tau_tan(rang2,ori)*0.5*surface(fac2);
      double coef = tau1+tau2;
      flux = signe_terme*coef;
    }
  return flux;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi (int , int , int , int , DoubleVect &) const [inline]
Definition at line 181 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi_fluide (int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 183 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_paroi_fluide (int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 761 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), and est_egal().
{
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int ori= orientation(fac3);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1, fac2);
  double dist = dist_norm_bord(fac1);
  double vit_imp;
  // On ne sait pas qui de fac1 ou de fac2 est la face de paroi
  if (est_egal(inconnue->valeurs()[fac1],0)) // fac1 est la face de paroi
    vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl);
  else  // fac2 est la face de paroi
    vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl);
  double tau = signe*vit_imp/dist;
  double reyn = DERIVED_T::IS_TURB ? tau*visc_turb : 0.0;
  if(DERIVED_T::IS_TURB)
    flux3 = (tau*visc_lam + reyn) * surf * poros;
  else
    flux3 = tau * surf * visc_lam * poros;
  flux1_2 = 0;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_periodicite (int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 184 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_periodicite (int , int , int , int , double & , double &) const [inline]
Definition at line 149 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie (int , int , int , int) const [inline]
Definition at line 147 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie (int , int , int , int , DoubleVect &) const [inline]
Definition at line 180 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie_fluide (int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Definition at line 185 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie_fluide (int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Definition at line 983 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord().
{
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int elem1 = elem_(fac3,0);
  int elem2 = elem_(fac3,1);
  int ori= orientation(fac3);
  double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
  double visc_turb = nu_mean_2pts(elem1,elem2,ori);
  double dist = dist_norm_bord(fac1);
  double surf = surface_(fac1,fac2);
  double poros = porosity_(fac1,fac2);
  double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)+
                        Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl));
  double tau = signe*vit_imp/dist;
  double reyn = DERIVED_T::IS_TURB ? tau*visc_turb : 0.0;
  flux3 = DERIVED_T::IS_TURB ? (tau*visc_lam + reyn) * surf * poros : tau*surf*visc_lam*poros;
  flux1_2 = 0;
}
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie_paroi (int , int , int , int , DoubleVect &) const [inline]
Definition at line 186 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::secmem_arete_symetrie_paroi (int fac1, int fac2, int fac3, int signe) const [inline]
Definition at line 1075 of file Eval_Diff_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord().
{
  double flux;
  int rang1 = (fac1-premiere_face_bord);
  int rang2 = (fac2-premiere_face_bord);
  int ori = orientation(fac3);
  if ( !uses_wall_law() )
    {
      int elem1 = elem_(fac3,0);
      int elem2 = elem_(fac3,1);
      double dist = dist_norm_bord(fac1);
      double visc_lam = nu_lam_mean_2pts(elem1,elem2,ori);
      double visc_turb = nu_mean_2pts(elem1,elem2,ori);
      double surf = surface_(fac1,fac2);
      const DoubleTab& inco = inconnue->valeurs();
      double vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)+
                            Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl));
      // WHY WHY WHY ?
      double tau  = DERIVED_T::IS_TURB ? signe * (vit_imp - inco[fac3]) / dist :
                    signe * vit_imp / dist;
      flux = (DERIVED_T::IS_TURB && DERIVED_T::IS_VAR) ? tau * surf * (visc_lam + visc_turb) :
             tau * surf * visc_lam;
    }
  else
    {
      // solution retenue pour le calcul du frottement sachant que sur l'une des faces
      // tau_tan vaut 0 car c'est une face qui porte une condition de symetrie
      // On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
      double tau1 = tau_tan(rang1,ori)*0.5*surface(fac1);
      double tau2 = tau_tan(rang2,ori)*0.5*surface(fac2);
      flux = tau1 + tau2;
    }
  return flux;
}
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::secmem_fa7_elem (int , int , int) const [inline]
Definition at line 143 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_fa7_elem (int , int , int , DoubleVect & flux) const [inline]
Definition at line 176 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> void Eval_Diff_VDF_Face< DERIVED_T >::secmem_fa7_sortie_libre (int , const Neumann_sortie_libre & , int , DoubleVect & flux) const [inline]
Definition at line 177 of file Eval_Diff_VDF_Face.h.
{ /* Do nothing */ }
template<typename DERIVED_T> double Eval_Diff_VDF_Face< DERIVED_T >::secmem_fa7_sortie_libre (int , const Neumann_sortie_libre & , int) const [inline]
Definition at line 144 of file Eval_Diff_VDF_Face.h.
{ return 0; }
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::surface_ (int i, int j) const [inline]
Definition at line 270 of file Eval_Diff_VDF_Face.h.
{
  const double surf = (DERIVED_T::IS_VAR || DERIVED_T::IS_TURB) ? 0.5*(surface(i)+surface(j)) :
                      0.5*(surface(i)*porosite(i)+surface(j)*porosite(j));
  return surf;
}
template<typename DERIVED_T > double Eval_Diff_VDF_Face< DERIVED_T >::tau_tan (int i, int j) const [inline]
Definition at line 238 of file Eval_Diff_VDF_Face.h.
{
  double tt = static_cast<const DERIVED_T *>(this)->tau_tan_impl(i,j);
  return tt;
}
template<typename DERIVED_T > bool Eval_Diff_VDF_Face< DERIVED_T >::uses_mod_turb () const [inline]
Definition at line 252 of file Eval_Diff_VDF_Face.h.
{
  bool nm = static_cast<const DERIVED_T *>(this)->uses_mod();
  return nm;
}
template<typename DERIVED_T > bool Eval_Diff_VDF_Face< DERIVED_T >::uses_wall_law () const [inline]
Definition at line 245 of file Eval_Diff_VDF_Face.h.
{
  bool wl = static_cast<const DERIVED_T *>(this)->uses_wall();
  return wl;
}
Member Data Documentation
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Face< DERIVED_T >::IS_TURB = false [static]
Reimplemented in Eval_Dift_VDF_const_Face, and Eval_Dift_VDF_var_Face.
Definition at line 46 of file Eval_Diff_VDF_Face.h.
template<typename DERIVED_T> constexpr bool Eval_Diff_VDF_Face< DERIVED_T >::IS_VAR = false [static]
Reimplemented in Eval_Diff_VDF_var_Face, and Eval_Dift_VDF_var_Face.
Definition at line 45 of file Eval_Diff_VDF_Face.h.
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_Diff_VDF_Face.h