TRUST: Champ_Generique_Moyenne Class Reference
Champ_Generique_Moyenne Class Reference
class Champ_Generique_Moyenne
Champ destine a post-traiter une moyenne d un champ generique
La classe porte un operateur statistique "Op_Moyenne"
#include <Champ_Generique_Moyenne.h>
Public Member Functions
Champ_Generique_Moyenne ()
~Champ_Generique_Moyenne ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
double temps () const
const Integrale_tps_Champ & integrale () const
const
Operateur_Statistique_tps_base & Operateur_Statistique () const
Operateur_Statistique_tps_base & Operateur_Statistique ()
void completer (const Postraitement_base &post)
virtual const Champ_base & get_champ (Champ &espace_stockage) const
void nommer_source ()
const Champ_Generique_base & get_champ_post (const Motcle &nom) const
int comprend_champ_post (const Motcle &identifiant) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Generique_Moyenne & self_cast (Objet_U &)
static const
Champ_Generique_Moyenne & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom et le type de l'operateur sur
un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Op_Moyenne Op_Moyenne_
Detailed Description
class Champ_Generique_Moyenne
Champ destine a post-traiter une moyenne d un champ generique
La classe porte un operateur statistique "Op_Moyenne"
Definition at line 47 of file Champ_Generique_Moyenne.h.
Constructor & Destructor Documentation
Champ_Generique_Moyenne::Champ_Generique_Moyenne ()
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
Champ_Generique_Moyenne::~Champ_Generique_Moyenne ()
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
Member Function Documentation
void Champ_Generique_Moyenne::completer (const Postraitement_base & post) [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 67 of file Champ_Generique_Moyenne.cpp.
References Op_Moyenne::associer(), Op_Moyenne::completer(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Op_Moyenne_, Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Probleme_base& Pb = get_ref_pb_base();
  const Champ_Generique_base& ch_integre = get_source(0);
  const Zone_dis_base& zdis = get_ref_zone_dis_base();
  Op_Moyenne_.associer(zdis,ch_integre,tstat_deb_,tstat_fin_);
  Op_Moyenne_.completer(Pb);
}
int Champ_Generique_Moyenne::comprend_champ_post (const Motcle & identifiant) const [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 195 of file Champ_Generique_Moyenne.cpp.
References Champ_Gen_de_Champs_Gen::comprend_champ_post(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
{
  if (Champ_Gen_de_Champs_Gen::comprend_champ_post(identifiant))
    return 1;
// Nom supplementaire teste car c est le nom utilise par :
// Champ_Generique_Ecart_Type::completer()
// Champ_Generique_Correlation::completer()
  Noms nom_source = get_source(0).get_property("nom");
  Motcle nom_champ = nom_source[0];
  Motcle nom_champ_moyenne("Moyenne_");
  nom_champ_moyenne += nom_champ;
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_deb_,"%e");
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_fin_,"%e");
  if (nom_champ_moyenne==identifiant)
    return 1;
  return 0;
}
Objet_U * Champ_Generique_Moyenne::cree_instance () [static]
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
int Champ_Generique_Moyenne::duplique () const [virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
const Champ_base & Champ_Generique_Moyenne::get_champ (Champ & espace_stockage) const [virtual]
Implements Champ_Generique_base.
Definition at line 79 of file Champ_Generique_Moyenne.cpp.
References Op_Moyenne::calculer_valeurs(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), DoubleVect::echange_espace_virtuel(), integrale(), Integrale_tps_Champ::le_champ(), Field_base::nature_du_champ(), Field_base::nb_comp(), Op_Moyenne_, REF, Deriv_Champ_base::valeur(), and Champ::valeurs().
{
  const REF(Champ_Generique_base)& mon_champ = integrale().le_champ();
  Champ espace_stockage_source;
  const Champ_base& source = mon_champ->get_champ(espace_stockage_source);
  Nature_du_champ nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  DoubleTab& tab_moy = espace_stockage.valeurs();
  tab_moy = Op_Moyenne_.calculer_valeurs();
  tab_moy.echange_espace_virtuel();
  return espace_stockage.valeur();
}
const Champ_Generique_base & Champ_Generique_Moyenne::get_champ_post (const Motcle & nom) const [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 160 of file Champ_Generique_Moyenne.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), REF, Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
{
  REF(Champ_Generique_base) ref_champ;
  try
    {
      return Champ_Gen_de_Champs_Gen::get_champ_post(nom) ;
    }
  catch (Champs_compris_erreur)
    {
    }
// Nom supplementaire teste car c est le nom utilise par :
// Champ_Generique_Ecart_Type::completer()
// Champ_Generique_Correlation::completer()
  Noms nom_source = get_source(0).get_property("nom");
  Motcle nom_champ = nom_source[0];
  Motcle nom_champ_moyenne("Moyenne_");
  nom_champ_moyenne += nom_champ;
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_deb_,"%e");
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_fin_,"%e");
  if (nom_champ_moyenne==nom)
    {
      ref_champ = *this;
      ref_champ->fixer_identifiant_appel(nom);
      return ref_champ;
    }
  throw Champs_compris_erreur();
  return ref_champ;
}
const Type_info * Champ_Generique_Moyenne::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
const Noms Champ_Generique_Moyenne::get_property (const Motcle & query) const [virtual]
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 95 of file Champ_Generique_Moyenne.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, Motcles::search(), and vect_impl::size().
{
// Creation des composantes serait a faire de maniere dynamique (Moyenne_...)
  Motcles motcles(1);
  motcles[0] = "composantes";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
// On fixe les composantes specifiques pour le Champ_Generique_Moyenne
// car dans Format_Post_Lml::ecrire_champ_lml() dans le cas d une localisation ELEM
// elles sont utilisees
        /*
          const Noms compo_cibles = get_source(0).get_property("composantes");
          int size = compo_cibles.size();
          Noms mots(size);
          for (int i=0; i<size; i++) {
          mots[i] = "Moyenne_";
          mots[i] += compo_cibles[i];
          }
          return mots;
          break;
// Actuellement choix fait d ajouter simplement numero de composante
        */
        const Noms source_compos = get_source(0).get_property("composantes");
        int nb_comp = source_compos.size();
        Noms compo(nb_comp);
        for (int i=0; i<nb_comp; i++)
          {
            Nom nume(i);
            compo[i] = nom_post_+nume;
          }
        return compo;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
const Type_info * Champ_Generique_Moyenne::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
const Integrale_tps_Champ& Champ_Generique_Moyenne::integrale () const [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 61 of file Champ_Generique_Moyenne.h.
References Op_Moyenne::integrale(), and Op_Moyenne_.
Referenced by get_champ().
  {
    return Op_Moyenne_.integrale();
  };
int Champ_Generique_Moyenne::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 54 of file Champ_Generique_Moyenne.cpp.
References Op_Moyenne::moyenne_convergee(), Operateur_Statistique(), and ref_cast.
{
  if (mot=="moyenne_convergee")
    {
      Op_Moyenne& operateur = ref_cast(Op_Moyenne,Operateur_Statistique());
      is>>operateur.moyenne_convergee();
      return 1;
    }
  else
    return Champ_Generique_Statistiques_base::lire_motcle_non_standard(mot,is);
  return 1;
}
void Champ_Generique_Moyenne::nommer_source () [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 147 of file Champ_Generique_Moyenne.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source;
      const Noms nom = get_source(0).get_property("nom");
      nom_champ_source = nom[0];
      nom_post_source =  "Moyenne_";
      nom_post_source +=  nom_champ_source;
      nommer(nom_post_source);
    }
}
Operateur_Statistique_tps_base & Champ_Generique_Moyenne::Operateur_Statistique () [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 88 of file Champ_Generique_Moyenne.h.
References Op_Moyenne_.
{
  return Op_Moyenne_;
}
const Operateur_Statistique_tps_base & Champ_Generique_Moyenne::Operateur_Statistique () const [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 83 of file Champ_Generique_Moyenne.h.
References Op_Moyenne_.
Referenced by lire_motcle_non_standard().
{
  return Op_Moyenne_;
}
Sortie & Champ_Generique_Moyenne::printOn (Sortie & s) const [protected, virtual]
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 33 of file Champ_Generique_Moyenne.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Generique_Moyenne::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 38 of file Champ_Generique_Moyenne.cpp.
{
  Champ_Generique_Statistiques_base::readOn(s);
  return s ;
}
const Champ_Generique_Moyenne & Champ_Generique_Moyenne::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
Champ_Generique_Moyenne & Champ_Generique_Moyenne::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
void Champ_Generique_Moyenne::set_param (Param & param) [virtual]
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 48 of file Champ_Generique_Moyenne.cpp.
References Param::ajouter_non_std().
{
  Champ_Generique_Statistiques_base::set_param(param);
  param.ajouter_non_std("moyenne_convergee",(this));
}
unsigned Champ_Generique_Moyenne::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Champ_Generique_Moyenne.cpp.
double Champ_Generique_Moyenne::temps () const [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 57 of file Champ_Generique_Moyenne.h.
References Op_Moyenne::integrale(), Op_Moyenne_, and Champ_Fonc::temps().
  {
    return Op_Moyenne_.integrale().temps();
  };
Member Data Documentation
const Type_info Champ_Generique_Moyenne::info_obj [static]
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 49 of file Champ_Generique_Moyenne.h.
Op_Moyenne Champ_Generique_Moyenne::Op_Moyenne_ [protected]
Definition at line 78 of file Champ_Generique_Moyenne.h.
Referenced by completer(), get_champ(), integrale(), Operateur_Statistique(), and temps().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Moyenne.h
src/Kernel/Champs/Champ_Generique_Moyenne.cpp