TRUST: Iterateur_Source_PolyMAC_base Class Reference
Iterateur_Source_PolyMAC_base Class Reference abstract
#include <Iterateur_Source_PolyMAC_base.h>
Public Member Functions
Iterateur_Source_PolyMAC_base ()
~Iterateur_Source_PolyMAC_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zones (const Zone_PolyMAC &, const Zone_Cl_PolyMAC &)
void associer (const Source_base &source)
virtual DoubleTab & ajouter (DoubleTab &) const =0
virtual DoubleTab & calculer (DoubleTab &) const =0
virtual Evaluateur_Source_PolyMAC & evaluateur ()=0
virtual void completer_ ()=0
virtual int equation_divisee_par_rho () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Iterateur_Source_PolyMAC_base & self_cast (Objet_U &)
static const Iterateur_Source_PolyMAC_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Ref_Source_base so_base
Detailed Description
Definition at line 28 of file Iterateur_Source_PolyMAC_base.h.
Constructor & Destructor Documentation
Iterateur_Source_PolyMAC_base()
Iterateur_Source_PolyMAC_base::Iterateur_Source_PolyMAC_base ()
Definition at line 18 of file Iterateur_Source_PolyMAC_base.cpp.
~Iterateur_Source_PolyMAC_base()
Iterateur_Source_PolyMAC_base::~Iterateur_Source_PolyMAC_base () override
Definition at line 18 of file Iterateur_Source_PolyMAC_base.cpp.
Member Function Documentation
ajouter()
virtual DoubleTab & Iterateur_Source_PolyMAC_base::ajouter (DoubleTab &) const pure virtual
Implemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Referenced by Iterateur_Source_PolyMAC::ajouter().
associer()
void Iterateur_Source_PolyMAC_base::associer (const Source_base & source) inline
Definition at line 61 of file Iterateur_Source_PolyMAC_base.h.
{
  so_base = source;
}
References so_base.
Referenced by Iterateur_Source_PolyMAC::associer().
associer_zones()
void Iterateur_Source_PolyMAC_base::associer_zones (const Zone_PolyMAC & zone_vdf, const Zone_Cl_PolyMAC & zone_cl_vdf)
Definition at line 41 of file Iterateur_Source_PolyMAC_base.cpp.
{
  la_zone = zone_vdf;
  la_zcl = zone_cl_vdf;
}
References la_zcl, and la_zone.
calculer()
virtual DoubleTab & Iterateur_Source_PolyMAC_base::calculer (DoubleTab &) const pure virtual
Implemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Referenced by Iterateur_Source_PolyMAC::calculer().
completer_()
virtual void Iterateur_Source_PolyMAC_base::completer_ () pure virtual
Implemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Referenced by Iterateur_Source_PolyMAC::completer_().
equation_divisee_par_rho()
int Iterateur_Source_PolyMAC_base::equation_divisee_par_rho () const inline virtual
Definition at line 52 of file Iterateur_Source_PolyMAC_base.h.
{
  Nom nom_eqn=la_zcl->equation().que_suis_je();
  if (nom_eqn.debute_par("Navier_Stokes"))
    return 1;
  else
    return 0;
}
References Nom::debute_par(), MorEqn::equation(), la_zcl, and Objet_U::que_suis_je().
evaluateur()
virtual Evaluateur_Source_PolyMAC & Iterateur_Source_PolyMAC_base::evaluateur () pure virtual
Implemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Referenced by Iterateur_Source_PolyMAC::evaluateur().
get_info()
const Type_info * Iterateur_Source_PolyMAC_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Definition at line 18 of file Iterateur_Source_PolyMAC_base.cpp.
info()
const Type_info * Iterateur_Source_PolyMAC_base::info () static
Definition at line 18 of file Iterateur_Source_PolyMAC_base.cpp.
printOn()
Sortie & Iterateur_Source_PolyMAC_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Definition at line 23 of file Iterateur_Source_PolyMAC_base.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Iterateur_Source_PolyMAC_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Iterateur_Source_PolyMAC_ElemEval_Puiss_Th_PolyMAC_Elem, and Iterateur_Source_PolyMAC_ElemEval_Source_C_PolyMAC_Elem.
Definition at line 31 of file Iterateur_Source_PolyMAC_base.cpp.
{
  return s ;
}
self_cast() [1/2]
const Iterateur_Source_PolyMAC_base & Iterateur_Source_PolyMAC_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Iterateur_Source_PolyMAC_base.cpp.
self_cast() [2/2]
Iterateur_Source_PolyMAC_base & Iterateur_Source_PolyMAC_base::self_cast (Objet_U & r) static
Definition at line 18 of file Iterateur_Source_PolyMAC_base.cpp.
Member Data Documentation
info_obj
const Type_info Iterateur_Source_PolyMAC_base::info_obj static
Definition at line 31 of file Iterateur_Source_PolyMAC_base.h.
la_zcl
Ref_Zone_Cl_PolyMAC Iterateur_Source_PolyMAC_base::la_zcl protected
Definition at line 47 of file Iterateur_Source_PolyMAC_base.h.
Referenced by associer_zones(), and equation_divisee_par_rho().
la_zone
Ref_Zone_PolyMAC Iterateur_Source_PolyMAC_base::la_zone protected
Definition at line 46 of file Iterateur_Source_PolyMAC_base.h.
Referenced by associer_zones().
so_base
Ref_Source_base Iterateur_Source_PolyMAC_base::so_base protected
Definition at line 48 of file Iterateur_Source_PolyMAC_base.h.
Referenced by associer().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Iterateur_Source_PolyMAC_base.h
src/PolyMAC/Sources/Iterateur_Source_PolyMAC_base.cpp