TRUST: Sources Class Reference
Sources Class Reference
class Sources
Sources represente une liste de Source.
Une equation contient un membres Equation_base::les_sources de type
Sources. Un objet Sources est un morceaux d'equation, cette classe
herite donc de MorEqn.
#include <Sources.h>
Public Member Functions
Sources ()
~Sources ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
Ajoute la contribution de toutes les sources de la
liste au tableau passe en parametre, et renvoie ce tableau.
DoubleTab & calculer (DoubleTab &) const
Calcule la contribution de toutes les sources de la
liste stocke le resultat dans le tableau passe en parametre,
et renvoie ce tableau.
void contribuer_jacobienne (Matrice_Bloc &matrice, int n) const
void mettre_a_jour (double temps)
Mise a jour en temps, de toute les sources de la liste.
void completer ()
Appelle Source::completer() sur toutes les sources de la
liste. voir Source_base::completer().
void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Parcours toutes les sources de la liste pour dimensionner.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void associer_champ_rho (const Champ_base &champ_rho)
Pour chaque source de la liste, appel a associer_champ_rho
de la source.
Si la masse volumique est variable, il faut declarer le
champ de rho aux sources avec cette methode (front-tracking)
Sinon, par defaut, les calculs sont faits avec rho=1.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Pour chaque source de la liste, appel a a_pour_Champ_Fonc(mot,ch_ref).
Cette methode est appelee par Equation_base::a_pour_Champ_Fonc.
int impr (Sortie &) const
Appelle Source::impr() sur toutes les sources de la
liste. voir Source_base::impr().
int initialiser (double temps)
Appelle Source::initialiser(temps) sur toutes les sources de la
liste. voir Source_base::initialiser(double temps).
void check_multiphase_compatibility () const override
Public Member Functions inherited from List_Source
List_Source ()
~List_Source ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Source (const Source &t)
List_Source (const List_Source &t)
Source & operator[] (int)
const Source & operator[] (int) const
Source & operator[] (const Nom &)
const Source & operator[] (const Nom &) const
Source & operator() (int i)
const Source & operator() (int i) const
Source & operator() (const Nom &n)
const Source & operator() (const Nom &n) const
Source & valeur ()
const Source & valeur () const
List_Source & operator= (const Source &t)
Source * operator-> ()
List_Source & operator= (const List_Source &)
List_Source & add (const List_Source &)
Source & add (const Source &)
List_Source & inserer (const List_Source &)
Source & inserer (const Source &)
void supprimer ()
List_Source & operator+= (const List_Source &)
List_Source & operator+= (const Source &)
Source & add_if_not (const Source &)
Source & add_if_not (const char *const)
List_Source & search (const Source &) const
List_Source & search (const char *const) const
List_Source & suivant ()
const List_Source & suivant () const
const List_Source & dernier () const
List_Source & dernier ()
List_Source & operator-= (const Source &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Source &) const
int contient (const char *const) const
int rang (const Source &) const
void suppr (const Source &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sources & self_cast (Objet_U &)
static const Sources & self_cast (const Objet_U &)
Static Public Member Functions inherited from List_Source
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Source & self_cast (Objet_U &)
static const List_Source & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from List_Source
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime la liste des Sources sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste de sources sur un flot d'entree.
Lit une liste de sources separees par des virgules
et le sajoute a la liste.
format:
{
bloc de lecture d'une source
[, bloc de lecture d'une source]
...
}.
Protected Member Functions inherited from List_Source
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Source &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Additional Inherited Members
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Sources
Sources represente une liste de Source.
Une equation contient un membres Equation_base::les_sources de type
Sources. Un objet Sources est un morceaux d'equation, cette classe
herite donc de MorEqn.
Definition at line 34 of file Sources.h.
Constructor & Destructor Documentation
Sources()
Sources::Sources ()
Definition at line 21 of file Sources.cpp.
~Sources()
Sources::~Sources ()
Definition at line 21 of file Sources.cpp.
Member Function Documentation
a_pour_Champ_Fonc()
int Sources::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const virtual
Pour chaque source de la liste, appel a a_pour_Champ_Fonc(mot,ch_ref).
Cette methode est appelee par Equation_base::a_pour_Champ_Fonc.
Definition at line 234 of file Sources.cpp.
{
  int ok = 0;
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      const Source& src = curseur.valeur();
      const Source_base& src_base = src.valeur();
      if (src_base.a_pour_Champ_Fonc(mot, ch_ref))
        {
          ok = 1;
          break;
        }
      ++curseur;
    }
  return ok;
}
References Source_base::a_pour_Champ_Fonc(), CONST_LIST_CURSEUR, and Deriv_Source_base::valeur().
ajouter()
DoubleTab & Sources::ajouter (DoubleTab & xx) const
Ajoute la contribution de toutes les sources de la
liste au tableau passe en parametre, et renvoie ce tableau.
Returns
DoubleTab&
Signification: le parametre xx modifie
Contraintes:
Definition at line 123 of file Sources.cpp.
{
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      curseur->ajouter(xx);
      ++curseur;
    }
  return xx;
}
References CONST_LIST_CURSEUR.
Referenced by Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), and Navier_Stokes_std::preparer_calcul().
associer_champ_rho()
void Sources::associer_champ_rho (const Champ_base & champ_rho) virtual
Pour chaque source de la liste, appel a associer_champ_rho
de la source.
Si la masse volumique est variable, il faut declarer le
champ de rho aux sources avec cette methode (front-tracking)
Sinon, par defaut, les calculs sont faits avec rho=1.
Definition at line 219 of file Sources.cpp.
{
  LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      Source& src = curseur.valeur();
      Source_base& src_base = src.valeur();
      src_base.associer_champ_rho(champ_rho);
      ++curseur;
    }
}
References Source_base::associer_champ_rho(), LIST_CURSEUR, and Deriv_Source_base::valeur().
calculer()
DoubleTab & Sources::calculer (DoubleTab & xx) const
Calcule la contribution de toutes les sources de la
liste stocke le resultat dans le tableau passe en parametre,
et renvoie ce tableau.
Returns
DoubleTab&
Signification: le parametre xx modifie
Contraintes:
Definition at line 151 of file Sources.cpp.
{
  xx=0;
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      curseur->ajouter(xx);
      ++curseur;
    }
  return xx;
}
References CONST_LIST_CURSEUR.
check_multiphase_compatibility()
void Sources::check_multiphase_compatibility () const override virtual
Reimplemented from MorEqn.
Definition at line 349 of file Sources.cpp.
{
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      const Source& src = curseur.valeur();
      const Source_base& src_base = src.valeur();
      src_base.check_multiphase_compatibility();
      ++curseur;
    }
}
References MorEqn::check_multiphase_compatibility(), CONST_LIST_CURSEUR, and Deriv_Source_base::valeur().
completer()
void Sources::completer (void)
Appelle Source::completer() sur toutes les sources de la
liste. voir Source_base::completer().
Definition at line 203 of file Sources.cpp.
{
  LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      curseur->completer();
      ++curseur;
    }
}
References LIST_CURSEUR.
Referenced by Equation_base::completer().
contribuer_a_avec()
void Sources::contribuer_a_avec (const DoubleTab & a, Matrice_Morse & matrice) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Definition at line 298 of file Sources.cpp.
{
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      const Source& src = curseur.valeur();
      const Source_base& src_base = src.valeur();
      src_base.contribuer_a_avec(a,matrice);
      ++curseur;
    }
}
References CONST_LIST_CURSEUR, Source_base::contribuer_a_avec(), and Deriv_Source_base::valeur().
Referenced by Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), and Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl().
contribuer_jacobienne()
void Sources::contribuer_jacobienne (Matrice_Bloc & matrice, int n) const
Definition at line 310 of file Sources.cpp.
{
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      const Source& src = curseur.valeur();
      const Source_base& src_base = src.valeur();
      src_base.contribuer_jacobienne(matrice, n);
      ++curseur;
    }
}
References CONST_LIST_CURSEUR, Source_base::contribuer_jacobienne(), and Deriv_Source_base::valeur().
cree_instance()
Objet_U * Sources::cree_instance () static
Definition at line 21 of file Sources.cpp.
dimensionner()
void Sources::dimensionner (Matrice_Morse & matrice) const
Dimensionnement de la matrice implicite des termes sources.
Parcours toutes les sources de la liste pour dimensionner.
Definition at line 282 of file Sources.cpp.
{
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      const Source& src = curseur.valeur();
      const Source_base& src_base = src.valeur();
      Matrice_Morse mat;
      src_base.dimensionner(mat);
      if (mat.nb_colonnes()) matrice += mat;
      ++curseur;
    }
}
References CONST_LIST_CURSEUR, Source_base::dimensionner(), Matrice_Morse::nb_colonnes(), and Deriv_Source_base::valeur().
Referenced by Equation_base::dimensionner_matrice_sans_mem().
duplique()
int Sources::duplique () const override virtual
Reimplemented from List_Source.
Definition at line 21 of file Sources.cpp.
get_info()
const Type_info * Sources::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Source.
Definition at line 21 of file Sources.cpp.
impr()
int Sources::impr (Sortie & os) const
Appelle Source::impr() sur toutes les sources de la
liste. voir Source_base::impr().
Definition at line 268 of file Sources.cpp.
{
  CONST_LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      curseur->impr(os);
      ++curseur;
    }
  return 1;
}
References CONST_LIST_CURSEUR.
Referenced by Equation_base::impr().
info()
const Type_info * Sources::info () static
Definition at line 21 of file Sources.cpp.
initialiser()
int Sources::initialiser (double temps)
Appelle Source::initialiser(temps) sur toutes les sources de la
liste. voir Source_base::initialiser(double temps).
Definition at line 337 of file Sources.cpp.
{
  LIST_CURSEUR(Source) curseur(*this);
  int ok=1;
  while(curseur)
    {
      ok = ok && curseur->initialiser(temps);
      ++curseur;
    }
  return ok;
}
References LIST_CURSEUR.
Referenced by Equation_base::preparer_calcul().
mettre_a_jour()
void Sources::mettre_a_jour (double temps)
Mise a jour en temps, de toute les sources de la liste.
Definition at line 177 of file Sources.cpp.
{
  LIST_CURSEUR(Source) curseur(*this);
  while(curseur)
    {
      curseur->mettre_a_jour(temps);
      ++curseur;
    }
}
References LIST_CURSEUR.
Referenced by Equation_base::mettre_a_jour(), Probleme_base::postraiter(), Navier_Stokes_std::preparer_calcul(), and Equation_base::updateGivenFields().
printOn()
Sortie & Sources::printOn (Sortie & os) const override protected virtual
Imprime la liste des Sources sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from List_Source.
Definition at line 38 of file Sources.cpp.
{
  return LIST(Source)::printOn(os);
}
References LIST, and printOn().
Referenced by printOn().
readOn()
Entree & Sources::readOn (Entree & is) override protected virtual
Lecture d'une liste de sources sur un flot d'entree.
Lit une liste de sources separees par des virgules
et le sajoute a la liste.
format:
{
bloc de lecture d'une source
[, bloc de lecture d'une source]
...
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from List_Source.
Definition at line 68 of file Sources.cpp.
{
  Nom accouverte="{";
  Nom accfermee="}";
  Nom virgule=",";
  Nom typ;
  is >> typ;
  if (typ!=accouverte)
    {
      Cerr << "We were waiting for { before " << typ << finl;
      exit();
    }
  Source t;
  is >> typ;
  if(typ==accfermee)
    return is;
  while(1)
    {
      Source& so=add(t);
      Cerr << "Reading of term " << typ << finl;
      Cerr << "and typing: ";
// Cout << ">>>>>>>>>>>>>>>>>>>> Type de Source = " << typ << finl;
      so.typer(typ,mon_equation.valeur());
      so->associer_eqn(mon_equation.valeur());
      is >> so.valeur();
      is >> typ;
      if(typ==accfermee)
        return is;
      if(typ!=virgule)
        {
          Cerr << typ << " : we expected a ',' or a '}'" << finl;
          exit();
        }
      assert (typ==virgule);
      is >> typ;
    }
}
References List_Source::add(), Cerr, Process::exit(), finl, MorEqn::mon_equation, Source::typer(), Ref_Equation_base::valeur(), and Deriv_Source_base::valeur().
self_cast() [1/2]
const Sources & Sources::self_cast (const Objet_U & r) static
Definition at line 21 of file Sources.cpp.
self_cast() [2/2]
Sources & Sources::self_cast (Objet_U & r) static
Definition at line 21 of file Sources.cpp.
taille_memoire()
unsigned Sources::taille_memoire () const override virtual
Reimplemented from List_Source.
Definition at line 21 of file Sources.cpp.
Member Data Documentation
info_obj
const Type_info Sources::info_obj static
Definition at line 36 of file Sources.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sources.h
src/Kernel/Framework/Sources.cpp