TRUST: Entree_fluide_T_h_imposee Class Reference
Entree_fluide_T_h_imposee Class Reference
classe Entree_fluide_temperature_imposee
Cas particulier de la classe Dirichlet_entree_fluide
pour la temperature imposee: impose la temperature d'entree du fluide
dans une equation de type Convection_Diffusion_Temperature
#include <Entree_fluide_T_h_imposee.h>
Public Member Functions
Entree_fluide_T_h_imposee ()
~Entree_fluide_T_h_imposee ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
double val_imp (int i) const
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
double val_imp (int i, int j) const
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_temperature_imposee sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
void bascule_cond_lim_en_enthalpie ()
void bascule_cond_lim_en_temperature ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Entree_fluide_T_h_imposee & self_cast (Objet_U &)
static const
Entree_fluide_T_h_imposee & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext" ou "K_Eps_ext"
Produit une erreur sinon.
Protected Attributes
Champ_front le_champ_Text
Champ_front le_champ_hext
int type_cond_lim
Detailed Description
classe Entree_fluide_temperature_imposee
Cas particulier de la classe Dirichlet_entree_fluide
pour la temperature imposee: impose la temperature d'entree du fluide
dans une equation de type Convection_Diffusion_Temperature
Definition at line 40 of file Entree_fluide_T_h_imposee.h.
Constructor & Destructor Documentation
Entree_fluide_T_h_imposee::Entree_fluide_T_h_imposee ()
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
Entree_fluide_T_h_imposee::~Entree_fluide_T_h_imposee ()
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
Member Function Documentation
void Entree_fluide_T_h_imposee::bascule_cond_lim_en_enthalpie () [inline]
Definition at line 60 of file Entree_fluide_T_h_imposee.h.
References type_cond_lim.
{
  type_cond_lim = 1;
}
void Entree_fluide_T_h_imposee::bascule_cond_lim_en_temperature () [inline]
Definition at line 65 of file Entree_fluide_T_h_imposee.h.
References type_cond_lim.
{
  type_cond_lim = 0;
}
int Entree_fluide_T_h_imposee::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Entree_fluide_temperature_imposee sont compatibles
avec une equation dont le domaine est la Thermique
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Definition at line 144 of file Entree_fluide_T_h_imposee.cpp.
References Cerr, Equation_base::domaine_application(), Cond_lim_base::err_pas_compatible(), and finl.
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Thermique="Thermique";
  Motcle indetermine="indetermine";
  Cerr<<"Entree_fluide_T_h_imposee::compatible_avec_eqn"<<finl;
  if ( (dom_app==Thermique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Entree_fluide_T_h_imposee::cree_instance () [static]
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
int Entree_fluide_T_h_imposee::duplique () const [virtual]
Implements Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
const Type_info * Entree_fluide_T_h_imposee::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
const Type_info * Entree_fluide_T_h_imposee::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
Sortie & Entree_fluide_T_h_imposee::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 44 of file Entree_fluide_T_h_imposee.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Entree_fluide_T_h_imposee::readOn (Entree & s) [protected, virtual]
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext" ou "K_Eps_ext"
Produit une erreur sinon.
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet_entree_fluide.
Definition at line 67 of file Entree_fluide_T_h_imposee.cpp.
References Cerr, Process::exit(), finl, Cond_lim_base::le_champ_front, le_champ_hext, le_champ_Text, Objet_U::que_suis_je(), Motcles::search(), and Deriv_::typer().
{
  le_champ_front.typer("Champ_front_uniforme");
  le_champ_Text.typer("Champ_front_uniforme");
  le_champ_hext.typer("Champ_front_uniforme");
  Motcle motlu;
  Motcles les_motcles(5);
  {
    les_motcles[0] = "T_ext";
    les_motcles[1] = "C_ext";
    les_motcles[2] = "K_Eps_ext";
    les_motcles[3] = "H_ext";
    les_motcles[4] = "Y_ext";
  }
  Motcle accfermee="}";
  Motcle accouverte="{";
  s >> motlu;
  int rang;
  if (motlu != accouverte)
    {
      Cerr << "On attendait une { dans la lecture de l'interface " << finl;
      exit();
    }
  s >> motlu;
  while(motlu != accfermee)
    {
      rang = les_motcles.search(motlu);
      switch(rang)
        {
        case 0:
          {
            s >> le_champ_Text;
            break;
          }
        case 1:
        case 2:
        case 3:
        case 4:
          {
            s >> le_champ_hext;
            break;
          }
        default:
          {
            Cerr << "Erreur a la lecture de la condition aux limites de type: " << finl;
            Cerr << que_suis_je() << finl;
            Cerr << "On attendait " << les_motcles << " a la place de " <<  motlu << finl;
            exit();
          }
        }
      s >> motlu;
    }
  return s;
}
const Entree_fluide_T_h_imposee & Entree_fluide_T_h_imposee::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
Entree_fluide_T_h_imposee & Entree_fluide_T_h_imposee::self_cast (Objet_U & r) [static]
Reimplemented from Dirichlet_entree_fluide.
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
unsigned Entree_fluide_T_h_imposee::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Entree_fluide_T_h_imposee.cpp.
double Entree_fluide_T_h_imposee::val_imp (int i) const [virtual]
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Dirichlet.
Definition at line 174 of file Entree_fluide_T_h_imposee.cpp.
References Cerr, DoubleTab::dimension(), Process::exit(), finl, le_champ_hext, le_champ_Text, DoubleVect::size(), type_cond_lim, and Champ_front::valeurs().
{
  if (type_cond_lim == 0)
    {
// Cerr<<"Entree_fluide_T_h_imposee Condition limite en temperature"<<finl;
      if (le_champ_Text.valeurs().size()==1)
        return le_champ_Text(0,0);
      else if (le_champ_Text.valeurs().dimension(1)==1)
        return le_champ_Text(i,0);
      else
        Cerr << "Entree_fluide_T_h_imposee::val_ext" << finl;
      exit();
      return 0.;
    }
  else
    {
// Cerr<<"Entree_fluide_T_h_imposee Condition limite en enthalpie"<<finl;
      if (le_champ_hext.valeurs().size()==1)
        return le_champ_hext(0,0);
      else if (le_champ_hext.valeurs().dimension(1)==1)
        return le_champ_hext(i,0);
      else
        Cerr << "Entree_fluide_T_h_imposee::val_ext" << finl;
      exit();
      return 0.;
    }
}
double Entree_fluide_T_h_imposee::val_imp (int i, int j) const [virtual]
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Dirichlet.
Definition at line 222 of file Entree_fluide_T_h_imposee.cpp.
References DoubleTab::dimension(), le_champ_hext, le_champ_Text, type_cond_lim, and Champ_front::valeurs().
{
  if (type_cond_lim == 0)
    {
// Condition limite en temperature
// Cerr<<"Entree_fluide_T_h_imposee Condition limite en temperature2 "<<finl;
      if (le_champ_Text.valeurs().dimension(0)==1)
        return le_champ_Text(0,j);
      else
        return le_champ_Text(i,j);
    }
  else
    {
// Condition limite en enthalpie
// Cerr<<"Entree_fluide_T_h_imposee Condition limite en enthalpie2 "<<finl;
      if (le_champ_hext.valeurs().dimension(0)==1)
        return le_champ_hext(0,j);
      else
        return le_champ_hext(i,j);
    }
}
Member Data Documentation
const Type_info Entree_fluide_T_h_imposee::info_obj [static]
Reimplemented from Dirichlet_entree_fluide.
Definition at line 43 of file Entree_fluide_T_h_imposee.h.
Champ_front Entree_fluide_T_h_imposee::le_champ_hext [protected]
Definition at line 55 of file Entree_fluide_T_h_imposee.h.
Referenced by readOn(), and val_imp().
Champ_front Entree_fluide_T_h_imposee::le_champ_Text [protected]
Definition at line 54 of file Entree_fluide_T_h_imposee.h.
Referenced by readOn(), and val_imp().
int Entree_fluide_T_h_imposee::type_cond_lim [protected]
Definition at line 56 of file Entree_fluide_T_h_imposee.h.
Referenced by bascule_cond_lim_en_enthalpie(), bascule_cond_lim_en_temperature(), and val_imp().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Entree_fluide_T_h_imposee.h
src/ThHyd/Incompressible/Cond_Lim/Entree_fluide_T_h_imposee.cpp