TRUST: Extraire_domaine Class Reference
Extraire_domaine Class Reference
Classe Extraire_domaine
Lecture d'un fichier.
#include <Extraire_domaine.h>
Public Member Functions
Extraire_domaine ()
~Extraire_domaine ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Extraire_domaine & self_cast (Objet_U &)
static const Extraire_domaine & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Extraire_domaine
Lecture d'un fichier.
Definition at line 38 of file Extraire_domaine.h.
Constructor & Destructor Documentation
Extraire_domaine()
Extraire_domaine::Extraire_domaine ()
Definition at line 27 of file Extraire_domaine.cpp.
~Extraire_domaine()
Extraire_domaine::~Extraire_domaine ()
Definition at line 27 of file Extraire_domaine.cpp.
Member Function Documentation
cree_instance()
Objet_U * Extraire_domaine::cree_instance () static
Definition at line 27 of file Extraire_domaine.cpp.
duplique()
int Extraire_domaine::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Extraire_domaine.cpp.
get_info()
const Type_info * Extraire_domaine::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Extraire_domaine.cpp.
info()
const Type_info * Extraire_domaine::info () static
Definition at line 27 of file Extraire_domaine.cpp.
interpreter_()
Entree & Extraire_domaine::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 44 of file Extraire_domaine.cpp.
{
  Nom nom_pb;
  Nom nom_dom;
  Nom nom_sous_zone;
  Parser_U condition_elements;
  Nom expr_elements("1");
  condition_elements.setNbVar(dimension);
  condition_elements.addVar("x");
  condition_elements.addVar("y");
  if (dimension==3)
    condition_elements.addVar("z");
  ArrOfDouble origine,point1,point2,point3;
// int avec_les_bords;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_dom,Param::REQUIRED);
  param.ajouter("probleme",&nom_pb,Param::REQUIRED);
  param.ajouter("condition_elements",&expr_elements);
  param.ajouter("sous_zone",&nom_sous_zone);
// param.ajouter("condition_faces",&expr_faces);
// param.ajouter_flag("avec_les_bords",&avec_les_bords);
  param.lire_avec_accolades_depuis(is);
  condition_elements.setString(expr_elements);
  condition_elements.parseString();
  associer_domaine(nom_dom);
  Domaine& dom=domaine();
// on recupere le pb
  if(! sub_type(Probleme_base, objet(nom_pb)))
    {
      Cerr << nom_pb << " is of type " << objet(nom_pb).que_suis_je() << finl;
      Cerr << "and not of type Probleme_base" << finl;
      exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base, objet(nom_pb));
  const Zone_VF& zone_vf=ref_cast(Zone_VF,pb.equation(0).zone_dis().valeur());
  dom.les_sommets()=zone_vf.zone().domaine().les_sommets();
// const DoubleTab& coord=dom.les_sommets();
  Zone zone__;
  dom.add(zone__);
  Zone& zone=dom.zone(0);
  zone.nommer(dom.le_nom());
  zone.typer(zone_vf.zone().type_elem().valeur().que_suis_je());
  zone.associer_domaine(dom);
// IntTab& les_elems=zone.les_elems();
//
  const DoubleTab& xp =zone_vf.xp();
  int nb_elem=zone_vf.nb_elem();
  IntTab marq_elem;
// on marque les elts qui nous interessent
  zone_vf.zone().creer_tableau_elements(marq_elem);
  int nb_elem_m=0;
  if (nom_sous_zone== Nom())
    {
      for (int elem=0; elem<nb_elem; elem++)
        {
          condition_elements.setVar("x",xp(elem,0));
          condition_elements.setVar("y",xp(elem,1));
          if (dimension==3)
            condition_elements.setVar("z",xp(elem,2));
          double res=condition_elements.eval();
          if (std::fabs(res)>1e-5)
            {
              marq_elem(elem)=1;
              nb_elem_m++;
            }
          else
            marq_elem(elem)=0;
        }
    }
  else
    {
      const Sous_Zone& ssz= ref_cast(Sous_Zone,objet(nom_sous_zone));
      int npol=ssz.nb_elem_tot();
      for (int i=0; i<npol; i++)
        {
          if (ssz(i)<nb_elem)
            {
              marq_elem(ssz(i))=1;
              nb_elem_m++;
            }
        }
    }
// Attention grosse ruse on echange pas les espaces virtuels pour que le joint devienne un bord
// marq_elem.echange_espace_virtuel();
// const DoubleTab& xv =zone_vf.xv();
  int nb_faces=zone_vf.nb_faces();
  const IntTab& face_voisin=zone_vf.face_voisins();
  ArrOfInt marq(nb_faces);
// on marque les joints
// const Joints& joints=zone_vf.face_joints();
// int nbjoints=zone_vf.nb_joints();
// for(int njoint=0; njoint<nbjoints; njoint++)
// {
// const Joint& joint_temp = zone_vf.joint(njoint);
// int pe_voisin=joint_temp.PEvoisin();
// if (pe_voisin<me())
// {
// const IntTab & indices_faces_joint = joint_temp.joint_item(Joint::FACE).renum_items_communs();
// const int nb_faces = indices_faces_joint.dimension(0);
// for (int j = 0; j < nb_faces; j++) {
// int face_de_joint = indices_faces_joint(j, 1);
// marq(face_de_joint) = -1;
// }
// }
// }
// on cherche les faces au bord du domaine (joint compris)
  int nb_t=0;
  for (int fac=0; fac<nb_faces; fac++)
    {
      int elem0=face_voisin(fac,0);
      int elem1=face_voisin(fac,1);
      int val0=-1;
      if (elem0!=-1) val0=marq_elem(elem0);
      int val1=-1;
      if (elem1!=-1) val1=marq_elem(elem1);
      if (val0!=val1)
        {
          if ((val0==1)||(val1==1))
            {
              if (marq[fac]!=-1) //pas un joint
                {
                  marq[fac]=1;
                  nb_t++;
                }
            }
        }
    }
  Cerr<<me()<<" nb_elem_m "<<nb_elem_m<<finl;
  Cerr<<me()<<" nb_t "<<nb_t<<finl;
  IntTab& les_elems=zone.les_elems();
  const IntTab& les_elems_old=zone_vf.zone().les_elems();
  int nb_som_elem=les_elems_old.dimension(1);
  les_elems.resize(nb_elem_m,nb_som_elem);
  const IntTab& face_sommets=zone_vf.face_sommets();
  int nb=0;
  for (int ele=0; ele<nb_elem; ele++)
    {
      if (marq_elem(ele)==1)
        {
          for (int k=0; k<nb_som_elem; k++)
            les_elems(nb,k)=les_elems_old(ele,k);
          nb++;
        }
    }
  assert(nb==nb_elem_m);
  Bord faces;
  faces.nommer("Bord");
  faces.typer_faces(zone_vf.zone().type_elem().type_face());
  Faces& les_faces=faces.faces();
// const IntTab& faces_sommets=zone_vf.faces_sommets();
  int nb_som_face=face_sommets.dimension(1);
  IntTab& indfaces=les_faces.les_sommets();
  indfaces.resize(nb_t,nb_som_face);
  IntTab& facesv=les_faces.voisins();
  facesv.resize(nb_t,2);
  facesv=-1;
  nb=0;
  for (int fac=0; fac<nb_faces; fac++)
    if (marq[fac]==1)
      {
        for (int s=0; s<nb_som_face; s++)
          indfaces(nb,s)=face_sommets(fac,s);
// on calcule la normale
        nb++;
      }
  Cerr<<finl;;
  zone.faces_bord().add(faces);
  zone.faces_bord().associer_zone(zone);
  zone.type_elem().associer_zone(zone);
  zone.fixer_premieres_faces_frontiere();
  assert(nb==nb_t);
  NettoieNoeuds::nettoie(dom);
  return is;
}
References List_Bord::add(), Domaine::add(), Parser_U::addVar(), Param::ajouter(), Zone::associer_domaine(), Interprete_geometrique_base::associer_domaine(), Bords::associer_zone(), Elem_geom::associer_zone(), Cerr, Zone::creer_tableau_elements(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Interprete_geometrique_base::domaine(), Probleme_base::equation(), Parser_U::eval(), Process::exit(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Frontiere::faces(), Zone::faces_bord(), finl, Zone::fixer_premieres_faces_frontiere(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), Param::lire_avec_accolades_depuis(), Process::me(), Zone_dis_base::nb_elem(), Sous_Zone::nb_elem_tot(), Zone_VF::nb_faces(), NettoieNoeuds::nettoie(), Frontiere::nommer(), Zone::nommer(), Interprete::objet(), Parser_U::parseString(), Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, TRUSTTab< _TYPE_ >::resize(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), sub_type, Zone::type_elem(), Elem_geom::type_face(), Zone::typer(), Frontiere::typer_faces(), Deriv_Zone_dis_base::valeur(), Deriv_Elem_geom_base::valeur(), Faces::voisins(), Zone_VF::xp(), Zone_dis_base::zone(), Domaine::zone(), and Equation_base::zone_dis().
printOn()
Sortie & Extraire_domaine::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 29 of file Extraire_domaine.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Extraire_domaine::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Extraire_domaine.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Extraire_domaine & Extraire_domaine::self_cast (const Objet_U & r) static
Definition at line 27 of file Extraire_domaine.cpp.
self_cast() [2/2]
Extraire_domaine & Extraire_domaine::self_cast (Objet_U & r) static
Definition at line 27 of file Extraire_domaine.cpp.
taille_memoire()
unsigned Extraire_domaine::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Extraire_domaine.cpp.
Member Data Documentation
info_obj
const Type_info Extraire_domaine::info_obj static
Definition at line 40 of file Extraire_domaine.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Extraire_domaine.h
src/Kernel/Geometrie/Extraire_domaine.cpp