TRUST: Champ_front_fonc_gradient Class Reference
Champ_front_fonc_gradient Class Reference
class Champ_front_fonc_gradient
Classe derivee de Champ_front_base
#include <Champ_front_fonc_gradient.h>
Public Member Functions
Champ_front_fonc_gradient ()
~Champ_front_fonc_gradient ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_ch_inc_base (const Champ_Inc_base &)
const Cond_lim_base & condition_limite (const Nom &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_fonc_gradient & self_cast (Objet_U &)
static const
Champ_front_fonc_gradient & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_Inc_base inconnue
Detailed Description
class Champ_front_fonc_gradient
Classe derivee de Champ_front_base
Definition at line 40 of file Champ_front_fonc_gradient.h.
Constructor & Destructor Documentation
Champ_front_fonc_gradient::Champ_front_fonc_gradient ()
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
Champ_front_fonc_gradient::~Champ_front_fonc_gradient ()
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
Member Function Documentation
void Champ_front_fonc_gradient::associer_ch_inc_base (const Champ_Inc_base & inc)
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 42 of file Champ_front_fonc_gradient.cpp.
References inconnue.
Referenced by Paroi_Knudsen_non_negligeable::completer().
{
  inconnue=inc;
}
const Cond_lim_base & Champ_front_fonc_gradient::condition_limite (const Nom & nom_bord)
Definition at line 47 of file Champ_front_fonc_gradient.cpp.
References Cerr, MorEqn::equation(), Process::exit(), finl, Cond_lim::frontiere_dis(), inconnue, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Deriv_Zone_Cl_dis_base::valeur(), Ref_Champ_Inc_base::valeur(), and Equation_base::zone_Cl_dis().
Referenced by Champ_front_fonc_gradient_VDF::mettre_a_jour().
{
  const Zone_Cl_dis_base& zcl=inconnue.valeur().equation().zone_Cl_dis().valeur();
  int n=zcl.nb_cond_lim();
  for(int i=0; i<n ; i++)
    {
      const Frontiere_dis_base& fr_dis=zcl.les_conditions_limites(i).frontiere_dis();
      if (fr_dis.le_nom() == nom_bord)
        return zcl.les_conditions_limites(i);
    }
  Cerr << nom_bord << " not found..." << finl;
  exit();
  return zcl.les_conditions_limites(0);
}
Objet_U * Champ_front_fonc_gradient::cree_instance () [static]
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
int Champ_front_fonc_gradient::duplique () const [virtual]
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
const Type_info * Champ_front_fonc_gradient::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
const Type_info * Champ_front_fonc_gradient::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
Sortie & Champ_front_fonc_gradient::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 30 of file Champ_front_fonc_gradient.cpp.
{
  return Champ_front_tangentiel::printOn(os);
}
Entree & Champ_front_fonc_gradient::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 36 of file Champ_front_fonc_gradient.cpp.
References Cerr, and finl.
{
  Cerr << "Champ_front_fonc_gradient::readOn" << finl;
  return s;
}
const Champ_front_fonc_gradient & Champ_front_fonc_gradient::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
Champ_front_fonc_gradient & Champ_front_fonc_gradient::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
unsigned Champ_front_fonc_gradient::taille_memoire () const [virtual]
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 27 of file Champ_front_fonc_gradient.cpp.
Member Data Documentation
Ref_Champ_Inc_base Champ_front_fonc_gradient::inconnue [protected]
Definition at line 48 of file Champ_front_fonc_gradient.h.
Referenced by associer_ch_inc_base(), condition_limite(), and Champ_front_fonc_gradient_VDF::mettre_a_jour().
const Type_info Champ_front_fonc_gradient::info_obj [static]
Reimplemented from Champ_front_tangentiel.
Reimplemented in Champ_front_fonc_gradient_VDF, and Champ_front_fonc_gradient_VEF.
Definition at line 42 of file Champ_front_fonc_gradient.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_fonc_gradient.h
src/Kernel/Champs/Champ_front_fonc_gradient.cpp