TRUST: Deriv_Operateur_Grad_base Class Reference
Deriv_Operateur_Grad_base Class Reference
#include <Operateur_Grad.h>
Public Member Functions
~Deriv_Operateur_Grad_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Operateur_Grad_base ()
Deriv_Operateur_Grad_base (const Deriv_Operateur_Grad_base &)
const Operateur_Grad_base & valeur () const
Operateur_Grad_base & valeur ()
const Operateur_Grad_base * operator-> () const
Operateur_Grad_base * operator-> ()
const Deriv_Operateur_Grad_base & operator= (const Operateur_Grad_base &)
const Deriv_Operateur_Grad_base & operator= (const Deriv_Operateur_Grad_base &)
operator const Operateur_Grad_base & () const
operator Operateur_Grad_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Operateur_Grad_base & self_cast (Objet_U &)
static const
Deriv_Operateur_Grad_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Operateur_Grad_base * pointeur_
Detailed Description
Definition at line 29 of file Operateur_Grad.h.
Constructor & Destructor Documentation
Deriv_Operateur_Grad_base::~Deriv_Operateur_Grad_base ()
Definition at line 28 of file Operateur_Grad.cpp.
Deriv_Operateur_Grad_base::Deriv_Operateur_Grad_base ()
Definition at line 28 of file Operateur_Grad.cpp.
Deriv_Operateur_Grad_base::Deriv_Operateur_Grad_base (const Deriv_Operateur_Grad_base & t)
Definition at line 28 of file Operateur_Grad.cpp.
Member Function Documentation
Objet_U * Deriv_Operateur_Grad_base::cree_instance () [static]
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
int Deriv_Operateur_Grad_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
const Type_info * Deriv_Operateur_Grad_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
const Type_info & Deriv_Operateur_Grad_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 28 of file Operateur_Grad.cpp.
const Type_info * Deriv_Operateur_Grad_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
Deriv_Operateur_Grad_base::operator const Operateur_Grad_base & () const
Definition at line 28 of file Operateur_Grad.cpp.
Deriv_Operateur_Grad_base::operator Operateur_Grad_base & ()
Definition at line 28 of file Operateur_Grad.cpp.
const Operateur_Grad_base * Deriv_Operateur_Grad_base::operator-> () const [inline]
Definition at line 29 of file Operateur_Grad.h.
: public Operateur, public DERIV(Operateur_Grad_base)
Operateur_Grad_base * Deriv_Operateur_Grad_base::operator-> () [inline]
Definition at line 29 of file Operateur_Grad.h.
: public Operateur, public DERIV(Operateur_Grad_base)
const Deriv_Operateur_Grad_base & Deriv_Operateur_Grad_base::operator= (const Deriv_Operateur_Grad_base & t)
Definition at line 28 of file Operateur_Grad.cpp.
const Deriv_Operateur_Grad_base & Deriv_Operateur_Grad_base::operator= (const Operateur_Grad_base & t)
Definition at line 28 of file Operateur_Grad.cpp.
Sortie & Deriv_Operateur_Grad_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
Entree & Deriv_Operateur_Grad_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
const Deriv_Operateur_Grad_base & Deriv_Operateur_Grad_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
Deriv_Operateur_Grad_base & Deriv_Operateur_Grad_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
void Deriv_Operateur_Grad_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 28 of file Operateur_Grad.cpp.
unsigned Deriv_Operateur_Grad_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Operateur_Grad.
Definition at line 28 of file Operateur_Grad.cpp.
const Operateur_Grad_base & Deriv_Operateur_Grad_base::valeur () const [inline]
Definition at line 29 of file Operateur_Grad.h.
Referenced by Operateur_Grad::ajouter(), Operateur_Grad::calculer(), Simple::calculer_correction_en_vitesse(), QDM_Multiphase::completer(), Navier_Stokes_std::dimensionner_matrice_sans_mem(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Gradient::get_directive_pour_discr(), Champ_Generique_Gradient::get_localisation(), Navier_Stokes_std::has_interface_blocs(), Solveur_U_P::iterer_NS(), Simpler::iterer_NS(), Piso::iterer_NS(), Operateur_Grad::l_op_base(), Champ_Generique_Gradient::Operateur(), and Operateur_Grad::typer().
: public Operateur, public DERIV(Operateur_Grad_base)
Operateur_Grad_base & Deriv_Operateur_Grad_base::valeur () [inline]
Definition at line 29 of file Operateur_Grad.h.
: public Operateur, public DERIV(Operateur_Grad_base)
Member Data Documentation
const Type_info Deriv_Operateur_Grad_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Operateur_Grad.
Definition at line 29 of file Operateur_Grad.h.
Operateur_Grad_base* Deriv_Operateur_Grad_base::pointeur_ [private]
Definition at line 29 of file Operateur_Grad.h.
The documentation for this class was generated from the following files:
src/Kernel/Operateurs/Operateur_Grad.h
src/Kernel/Operateurs/Operateur_Grad.cpp