TRUST: Op_Conv_negligeable Class Reference
Op_Conv_negligeable Class Reference
Classe Op_Conv_negligeable
Cette classe represente un opperateur de convection negligeable.
Lorsqu'un operateur de ce type est utilise dans une equation
cela revient a negliger le terme de convection.
Les methodes de modification et de participation a un calcul de
l'operateur sont en fait des appels aux meme methodes de
Operateur_negligeable qui ne font rien.
#include <Op_Conv_negligeable.h>
Public Member Functions
Op_Conv_negligeable ()
~Op_Conv_negligeable ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void mettre_a_jour (double) override
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::mettre_a_jour(double)
void associer_vitesse (const Champ_base &) override
Associe la vitesse a l'operateur.
const Champ_base & vitesse () const
Renvoie le champ inconnue representant la vitesse.
void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const override
void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const override
void check_multiphase_compatibility () const override
void set_incompressible (const int) override
Public Member Functions inherited from Operateur_negligeable
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
Ajout de la contribution d'un operateur negligeable a
un tableau.
NE FAIT RIEN, renvoie le parametre tableau sans le modifie.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
Initialise le parametre tableau avec la contribution
de l'operateur negligeable: initialise le tableau a ZERO.
void mettre_a_jour (double)
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN.
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_negligeable & self_cast (Objet_U &)
static const Op_Conv_negligeable & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime la vitesse sur un flot de sortie.
Entree & readOn (Entree &) override
Lit la vitesse a partir d'un flot d'entree.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
Associe divers objets a un operateurs negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::associer(const Zone_dis&,
const Zone_Cl_dis&,
const Champ_Inc&)
Protected Member Functions inherited from Operateur_negligeable
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
Associe divers objets a un operateurs negligeable: NE FAIT RIEN.
Protected Member Functions inherited from Operateur_Conv_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Ref_Champ_base la_vitesse
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
Classe Op_Conv_negligeable
Cette classe represente un opperateur de convection negligeable.
Lorsqu'un operateur de ce type est utilise dans une equation
cela revient a negliger le terme de convection.
Les methodes de modification et de participation a un calcul de
l'operateur sont en fait des appels aux meme methodes de
Operateur_negligeable qui ne font rien.
Definition at line 36 of file Op_Conv_negligeable.h.
Constructor & Destructor Documentation
Op_Conv_negligeable()
Op_Conv_negligeable::Op_Conv_negligeable ()
Definition at line 19 of file Op_Conv_negligeable.cpp.
~Op_Conv_negligeable()
Op_Conv_negligeable::~Op_Conv_negligeable ()
Definition at line 19 of file Op_Conv_negligeable.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Conv_negligeable::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Operateur_base.
Definition at line 55 of file Op_Conv_negligeable.h.
{}) const override { };
ajouter_flux()
void Op_Conv_negligeable::ajouter_flux (const DoubleTab & inconnue, DoubleTab & contribution) const override virtual
Reimplemented from Operateur_base.
Definition at line 101 of file Op_Conv_negligeable.cpp.
{
// nothing to do
}
associer()
void Op_Conv_negligeable::associer (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch) inline override protected virtual
Associe divers objets a un operateurs negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::associer(const Zone_dis&,
const Zone_Cl_dis&,
const Champ_Inc&)
Implements Operateur_base.
Definition at line 137 of file Op_Conv_negligeable.h.
{
  Operateur_negligeable::associer(z, zcl, ch);
}
References Operateur_negligeable::associer().
associer_vitesse()
void Op_Conv_negligeable::associer_vitesse (const Champ_base & ch) override virtual
Associe la vitesse a l'operateur.
Implements Operateur_Conv_base.
Definition at line 76 of file Op_Conv_negligeable.cpp.
{
  la_vitesse = ch;
}
References la_vitesse.
associer_zone_cl_dis()
void Op_Conv_negligeable::associer_zone_cl_dis (const Zone_Cl_dis_base &) inline override virtual
Reimplemented from Operateur_base.
Definition at line 45 of file Op_Conv_negligeable.h.
  {
    ;
  } ;
calculer_flux()
void Op_Conv_negligeable::calculer_flux (const DoubleTab & inconnue, DoubleTab & flux) const override virtual
Reimplemented from Operateur_base.
Definition at line 106 of file Op_Conv_negligeable.cpp.
{
  flux = 0.0;
}
check_multiphase_compatibility()
void Op_Conv_negligeable::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 64 of file Op_Conv_negligeable.h.
{ };
contribuer_au_second_membre()
void Op_Conv_negligeable::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 78 of file Op_Conv_negligeable.h.
{
  ;
}
cree_instance()
Objet_U * Op_Conv_negligeable::cree_instance () static
Definition at line 19 of file Op_Conv_negligeable.cpp.
dimensionner_blocs()
void Op_Conv_negligeable::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Operateur_base.
Definition at line 54 of file Op_Conv_negligeable.h.
{}) const override { };
duplique()
int Op_Conv_negligeable::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Op_Conv_negligeable.cpp.
get_info()
const Type_info * Op_Conv_negligeable::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_base.
Definition at line 19 of file Op_Conv_negligeable.cpp.
has_interface_blocs()
int Op_Conv_negligeable::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 50 of file Op_Conv_negligeable.h.
  {
    return 1;
  };
info()
const Type_info * Op_Conv_negligeable::info () static
Definition at line 19 of file Op_Conv_negligeable.cpp.
mettre_a_jour()
void Op_Conv_negligeable::mettre_a_jour (double temps) inline override virtual
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::mettre_a_jour(double)
Reimplemented from Operateur_base.
Definition at line 104 of file Op_Conv_negligeable.h.
{
  Operateur_negligeable::mettre_a_jour(temps);
}
References Operateur_negligeable::mettre_a_jour().
modifier_pour_Cl()
void Op_Conv_negligeable::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 84 of file Op_Conv_negligeable.h.
{
  ;
}
printOn()
Sortie & Op_Conv_negligeable::printOn (Sortie & os) const override protected virtual
Imprime la vitesse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Conv_negligeable.cpp.
{
  return os << la_vitesse;
}
References la_vitesse.
readOn()
Entree & Op_Conv_negligeable::readOn (Entree & is) override protected virtual
Lit la vitesse a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Operateur_base.
Definition at line 56 of file Op_Conv_negligeable.cpp.
{
  return is >> la_vitesse;
}
References la_vitesse.
self_cast() [1/2]
const Op_Conv_negligeable & Op_Conv_negligeable::self_cast (const Objet_U & r) static
Definition at line 19 of file Op_Conv_negligeable.cpp.
self_cast() [2/2]
Op_Conv_negligeable & Op_Conv_negligeable::self_cast (Objet_U & r) static
Definition at line 19 of file Op_Conv_negligeable.cpp.
set_incompressible()
void Op_Conv_negligeable::set_incompressible (const int) inline override virtual
Reimplemented from Operateur_Conv_base.
Definition at line 65 of file Op_Conv_negligeable.h.
{ };
taille_memoire()
unsigned Op_Conv_negligeable::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Op_Conv_negligeable.cpp.
vitesse()
const Champ_base & Op_Conv_negligeable::vitesse () const
Renvoie le champ inconnue representant la vitesse.
Returns
Champ_Inc&
Signification: le champ inconnue representant la vitesse
Contraintes: reference constante
Definition at line 96 of file Op_Conv_negligeable.cpp.
{
  return la_vitesse.valeur();
}
References la_vitesse, and Ref_Champ_base::valeur().
Member Data Documentation
info_obj
const Type_info Op_Conv_negligeable::info_obj static
Definition at line 39 of file Op_Conv_negligeable.h.
la_vitesse
Ref_Champ_base Op_Conv_negligeable::la_vitesse protected
Definition at line 69 of file Op_Conv_negligeable.h.
Referenced by associer_vitesse(), printOn(), readOn(), and vitesse().
The documentation for this class was generated from the following files:
src/Kernel/Operateurs/Op_Conv_negligeable.h
src/Kernel/Operateurs/Op_Conv_negligeable.cpp