TRUST: Op_Grad_EF Class Reference
Op_Grad_EF Class Reference
class Op_Grad_EF
Cette classe represente l'operateur de gradient
La discretisation est EF
On calcule le gradient d'un champ_P0_EF (la pression)
#include <Op_Grad_EF.h>
Public Member Functions
Op_Grad_EF ()
~Op_Grad_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Public Member Functions inherited from Operateur_Grad_base
Operateur_Grad_base ()
~Operateur_Grad_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
virtual DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
Calcul sans les conditions aux limites ?
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_EF & self_cast (Objet_U &)
static const Op_Grad_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Grad_base
static const Type_info * info ()
static Operateur_Grad_base & self_cast (Objet_U &)
static const Operateur_Grad_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Grad_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Operateur_Grad_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Ref_Zone_EF la_zone_EF
Ref_Zone_Cl_EF la_zcl_EF
Champ_Don int_P_bord_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Grad_EF
Cette classe represente l'operateur de gradient
La discretisation est EF
On calcule le gradient d'un champ_P0_EF (la pression)
Definition at line 49 of file Op_Grad_EF.h.
Constructor & Destructor Documentation
Op_Grad_EF()
Op_Grad_EF::Op_Grad_EF ()
Definition at line 34 of file Op_Grad_EF.cpp.
~Op_Grad_EF()
Op_Grad_EF::~Op_Grad_EF ()
Definition at line 34 of file Op_Grad_EF.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Grad_EF::ajouter (const DoubleTab & pression, DoubleTab & grad) const override virtual
Reimplemented from Operateur_base.
Definition at line 233 of file Op_Grad_EF.cpp.
{
  test(pression,grad,(*this));
// Gradient d'un champ scalaire localise aux centres des elements
// On initialise grad a zero
  grad = 0;
  assert_espace_virtuel_vect(pression);
  Debog::verifier("pression dans Op_Grad_EF",pression);
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  const DoubleTab& Bij_thilde=zone_ef.Bij_thilde();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  for (int elem=0; elem<nb_elem_tot; elem++)
    {
      double pe=pression(elem);
      for (int s=0; s<nb_som_elem; s++)
        {
          int som=elems(elem,s);
          for (int i=0; i<dimension; i++)
            {
              grad(som,i)-=Bij_thilde(elem,s,i)*pe;
            }
        }
    }
  const IntTab& faces_sommets=zone_ef.face_sommets();
  int nb_som_face=faces_sommets.dimension(1);
// const IntTab& face_voisins = zone_ef.face_voisins();
  const DoubleTab& face_normales = zone_ef.face_normales();
  const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
// prise en compte des " cl " ajout du temr - int P sur le bord
// test ...
  for (int n_bord=0; n_bord<zone_ef.nb_front_Cl()*1; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()) )
        continue;
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = 0;
      int num2 = + le_bord.nb_faces_tot();
      if (sub_type(Dirichlet,la_cl.valeur()) )
// ca ne sert a rien
        for (int ind_face=num1; ind_face<num2; ind_face++)
          {
            int face=le_bord.num_face(ind_face);
            for (int s=0; s<nb_som_face; s++)
              {
                int som=faces_sommets(face,s);
                for (int comp=0; comp<dimension; comp++)
                  grad(som,comp) = 0;
              }
          }
      else
        for (int ind_face=num1; ind_face<num2*0; ind_face++)
          {
            int face=le_bord.num_face(ind_face);
// int elem1 = face_voisins(face,0);
// double diff =  - pression[elem1]/nb_som_face;
            for (int s=0; s<nb_som_face; s++)
              {
                int som=faces_sommets(face,s);
// on calcule grad.S /S2
                double grad_n=0;
                for (int comp=0; comp<dimension; comp++)
                  grad_n+=grad(som,comp)*face_normales(face,comp);
                grad_n/=(zone_ef.surface(face)*zone_ef.surface(face));
                for (int comp=0; comp<dimension; comp++)
                  grad(som,comp) -= grad_n*face_normales(face,comp);
              }
          }
    }
  ajouter_bord(grad,zone_ef,la_zcl_EF.valeur(),int_P_bord_);
  grad.echange_espace_virtuel();
  return grad;
}
References ajouter_bord(), assert_espace_virtuel_vect(), Zone_EF::Bij_thilde(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Zone_EF::face_normales(), Zone_VF::face_sommets(), Cond_lim::frontiere_dis(), int_P_bord_, la_zcl_EF, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Front_VF::num_face(), ref_cast, sub_type, Zone_VF::surface(), test(), Ref_Zone_Cl_EF::valeur(), Deriv_Cond_lim_base::valeur(), valeur(), Debog::verifier(), and Zone_dis_base::zone().
Referenced by calculer(), and test().
associer()
void Op_Grad_EF::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc & inc) override virtual
Implements Operateur_base.
Definition at line 61 of file Op_Grad_EF.cpp.
{
  const Zone_EF& zEF = ref_cast(Zone_EF, zone_dis.valeur());
  const Zone_Cl_EF& zclEF = ref_cast(Zone_Cl_EF, zone_Cl_dis.valeur());
  la_zone_EF = zEF;
  la_zcl_EF = zclEF;
// const IntTab& face_sommets=zEF.face_sommets();
#ifdef  lire_valimp_dans_med_
// assert(face_sommets.dimension(1)==4);
// if (face_sommets.dimension(1)==4)
  {
    zclEF.equation().probleme().discretisation().discretiser_champ("CHAMP_SOMMETS",zEF,"int_P_bord","?",dimension,0.,int_P_bord_);
    {
      Champ_Don champ_lu;
      EChaine ee("champ_fonc_med last_time termes.med MAILLAGE_GENEPI terme_pression_limite_qdm_10 som 0.");
      ee>>champ_lu;
      int_P_bord_.valeur().affecter(champ_lu);
    }
  }
#endif
}
References Champ_base::affecter(), Objet_U::dimension, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), int_P_bord_, la_zcl_EF, la_zone_EF, Equation_base::probleme(), ref_cast, Deriv_Champ_Don_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Op_Grad_EF::calculer (const DoubleTab & pre, DoubleTab & grad) const override virtual
Reimplemented from Operateur_base.
Definition at line 322 of file Op_Grad_EF.cpp.
{
  grad = 0;
  return ajouter(pre,grad);
}
References ajouter().
cree_instance()
Objet_U * Op_Grad_EF::cree_instance () static
Definition at line 34 of file Op_Grad_EF.cpp.
duplique()
int Op_Grad_EF::duplique () const override virtual
Implements Objet_U.
Definition at line 34 of file Op_Grad_EF.cpp.
get_info()
const Type_info * Op_Grad_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 34 of file Op_Grad_EF.cpp.
impr()
int Op_Grad_EF::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 329 of file Op_Grad_EF.cpp.
{
  const int impr_mom=la_zone_EF->zone().Moments_a_imprimer();
  const int impr_sum=(la_zone_EF->zone().Bords_a_imprimer_sum().est_vide() ? 0:1);
  const int impr_bord=(la_zone_EF->zone().Bords_a_imprimer().est_vide() ? 0:1);
  const Schema_Temps_base& sch = equation().probleme().schema_temps();
  double temps = sch.temps_courant();
  const Zone_Cl_EF& zone_Cl_EF = la_zcl_EF.valeur();
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& face_voisins = zone_EF.face_voisins();
  const DoubleTab& face_normales = zone_EF.face_normales();
  const Equation_base& eqn = equation();
  const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,eqn);
  const Champ_P0_EF& la_pression_P0 = ref_cast(Champ_P0_EF,eqn_hydr.pression_pa().valeur());
  const DoubleTab& pression_P0 = la_pression_P0.valeurs();
  int n_bord, elem ;
  int face;
  double n0, n1, n2 ;
  const ArrOfDouble& c_grav=la_zone_EF->zone().cg_moments();
  flux_bords_.resize(zone_EF.nb_faces_bord(),dimension);
  flux_bords_ = 0.;
  int flag=je_suis_maitre();
  SFichier Flux_grad;
  ouvrir_fichier(Flux_grad,"",flag);
  SFichier Flux_grad_moment;
  ouvrir_fichier( Flux_grad_moment,"moment",impr_mom&&flag);
  SFichier Flux_grad_sum;
  ouvrir_fichier(Flux_grad_sum,"sum",impr_sum&&flag);
  EcrFicPartage Flux_grad_face;
  ouvrir_fichier_partage(Flux_grad_face,"",impr_bord);
  if (je_suis_maitre())
    {
      Flux_grad.add_col(temps);
      if (impr_mom) Flux_grad_moment.add_col(temps);
      if (impr_sum) Flux_grad_sum.add_col(temps);
    }
  for ( n_bord=0; n_bord<zone_EF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      double fluxx_s = 0. ;
      double fluxy_s = 0. ;
      double fluxz_s = 0. ;
      double fluxx_sum_s = 0. ;
      double fluxy_sum_s = 0. ;
      double fluxz_sum_s = 0. ;
      double moment_x = 0.;
      double moment_y = 0.;
      double moment_z = 0.;
      for (face=ndeb; face<nfin; face++)
        {
          elem = face_voisins(face,0);
          if (dimension == 2)
            {
              n0   = face_normales(face,0) ;
              n1   = face_normales(face,1) ;
              flux_bords_(face,0) = pression_P0(elem)*n0 ;
              flux_bords_(face,1) = pression_P0(elem)*n1 ;
              fluxx_s += flux_bords_(face,0) ;
              fluxy_s += flux_bords_(face,1) ;
// Calcul du moment exerce par le fluide sur le bord (OM/\F)
              if (impr_mom) moment_z+=flux_bords_(face,1)*c_grav[0]-flux_bords_(face,0)*c_grav[1];
              if (zone_EF.zone().Bords_a_imprimer_sum().contient(le_bord.le_nom()))
                {
                  fluxx_sum_s += flux_bords_(face,0) ;
                  fluxy_sum_s += flux_bords_(face,1) ;
                }
            }
          else if (dimension == 3)
            {
              n0   = face_normales(face,0) ;
              n1   = face_normales(face,1) ;
              n2   = face_normales(face,2) ;
              flux_bords_(face,0) = pression_P0(elem)*n0 ;
              flux_bords_(face,1) = pression_P0(elem)*n1 ;
              flux_bords_(face,2) = pression_P0(elem)*n2 ;
              fluxx_s += flux_bords_(face,0) ;
              fluxy_s += flux_bords_(face,1) ;
              fluxz_s += flux_bords_(face,2) ;
// Calcul du moment exerce par le fluide sur le bord (OM/\F)
              moment_x+=flux_bords_(face,2)*c_grav[1]-flux_bords_(face,1)*c_grav[2];
              moment_y+=flux_bords_(face,0)*c_grav[2]-flux_bords_(face,2)*c_grav[0];
              moment_z+=flux_bords_(face,1)*c_grav[0]-flux_bords_(face,0)*c_grav[1];
              if (zone_EF.zone().Bords_a_imprimer_sum().contient(le_bord.le_nom()))
                {
                  fluxx_sum_s += flux_bords_(face,0) ;
                  fluxy_sum_s += flux_bords_(face,1) ;
                  fluxz_sum_s += flux_bords_(face,2) ;
                }
            }
        }
      if (dimension == 2)
        {
          fluxx_s=Process::mp_sum(fluxx_s);
          fluxy_s=Process::mp_sum(fluxy_s);
          fluxx_sum_s=Process::mp_sum(fluxx_sum_s);
          fluxy_sum_s=Process::mp_sum(fluxy_sum_s);
          moment_z=Process::mp_sum(moment_z);
          if (je_suis_maitre())
            {
              Flux_grad.add_col(fluxx_s);
              Flux_grad.add_col(fluxy_s);
              if (impr_sum)
                {
                  Flux_grad_sum.add_col(fluxx_sum_s);
                  Flux_grad_sum.add_col(fluxy_sum_s);
                }
              if (impr_mom) Flux_grad_moment.add_col(moment_z);
            }
        }
      if (dimension == 3)
        {
          fluxx_s=Process::mp_sum(fluxx_s);
          fluxy_s=Process::mp_sum(fluxy_s);
          fluxz_s=Process::mp_sum(fluxz_s);
          fluxx_sum_s=Process::mp_sum(fluxx_sum_s);
          fluxy_sum_s=Process::mp_sum(fluxy_sum_s);
          fluxz_sum_s=Process::mp_sum(fluxz_sum_s);
          moment_x=Process::mp_sum(moment_x);
          moment_y=Process::mp_sum(moment_y);
          moment_z=Process::mp_sum(moment_z);
          if(je_suis_maitre())
            {
              Flux_grad.add_col(fluxx_s);
              Flux_grad.add_col(fluxy_s);
              Flux_grad.add_col(fluxz_s);
              if (impr_sum)
                {
                  Flux_grad_sum.add_col(fluxx_sum_s);
                  Flux_grad_sum.add_col(fluxy_sum_s);
                  Flux_grad_sum.add_col(fluxz_sum_s);
                }
              if (impr_mom)
                {
                  Flux_grad_moment.add_col(moment_x);
                  Flux_grad_moment.add_col(moment_y);
                  Flux_grad_moment.add_col(moment_z);
                }
            }
        }
    }
  if (je_suis_maitre())
    {
      Flux_grad << finl;
      if (impr_mom) Flux_grad_moment<<finl;
      if (impr_sum) Flux_grad_sum<<finl;
    }
  for ( n_bord=0; n_bord<zone_EF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if (zone_EF.zone().Bords_a_imprimer().contient(le_bord.le_nom()))
        {
          if (je_suis_maitre()) Flux_grad_face << "# Force par face sur " << le_bord.le_nom() << " au temps " << temps << " : " << finl;
          for (face=ndeb; face<nfin; face++)
            {
              if (dimension==2)
                Flux_grad_face << "# Face a x= " << zone_EF.xv(face,0) << " y= " << zone_EF.xv(face,1) << " flux_x= " << flux_bords_(face,0) << " flux_y= " << flux_bords_(face,1) << finl;
              else if (dimension == 3)
                Flux_grad_face << "# Face a x= " << zone_EF.xv(face,0) << " y= " << zone_EF.xv(face,1) << " z= " << zone_EF.xv(face,3) << " flux_x= " << flux_bords_(face,0) << " flux_y= " << flux_bords_(face,1) << " flux_z= " << flux_bords_(face,2) << finl;
            }
          Flux_grad_face.syncfile();
        }
    }
  return 1;
}
References Sortie::add_col(), Zone::Bords_a_imprimer(), Zone::Bords_a_imprimer_sum(), Zone::cg_moments(), List_Nom::contient(), Objet_U::dimension, MorEqn::equation(), liste::est_vide(), Zone_EF::face_normales(), Zone_VF::face_voisins(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Process::je_suis_maitre(), la_zcl_EF, la_zone_EF, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone::Moments_a_imprimer(), Process::mp_sum(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Navier_Stokes_std::pression_pa(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeurs(), Zone_VF::xv(), and Zone_dis_base::zone().
info()
const Type_info * Op_Grad_EF::info () static
Definition at line 34 of file Op_Grad_EF.cpp.
mettre_a_jour()
void Op_Grad_EF::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Operateur_base.
Definition at line 53 of file Op_Grad_EF.cpp.
{
  Operateur_Grad_base::mettre_a_jour(temps);
}
References Operateur_base::mettre_a_jour().
printOn()
Sortie & Op_Grad_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 40 of file Op_Grad_EF.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 48 of file Op_Grad_EF.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Grad_EF & Op_Grad_EF::self_cast (const Objet_U & r) static
Definition at line 34 of file Op_Grad_EF.cpp.
self_cast() [2/2]
Op_Grad_EF & Op_Grad_EF::self_cast (Objet_U & r) static
Definition at line 34 of file Op_Grad_EF.cpp.
taille_memoire()
unsigned Op_Grad_EF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 34 of file Op_Grad_EF.cpp.
Member Data Documentation
info_obj
const Type_info Op_Grad_EF::info_obj static
Definition at line 52 of file Op_Grad_EF.h.
int_P_bord_
Champ_Don Op_Grad_EF::int_P_bord_ protected
Definition at line 64 of file Op_Grad_EF.h.
Referenced by ajouter(), and associer().
la_zcl_EF
Ref_Zone_Cl_EF Op_Grad_EF::la_zcl_EF protected
Definition at line 63 of file Op_Grad_EF.h.
Referenced by ajouter(), associer(), and impr().
la_zone_EF
Ref_Zone_EF Op_Grad_EF::la_zone_EF protected
Definition at line 62 of file Op_Grad_EF.h.
Referenced by associer(), and impr().
The documentation for this class was generated from the following files:
src/EF/Operateurs/Op_Grad_EF.h
src/EF/Operateurs/Op_Grad_EF.cpp