TRUST: Old_Debog Class Reference
Old_Debog Class Reference
#include <Old_Debog.h>
Public Member Functions
Old_Debog ()
~Old_Debog ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Old_Debog & self_cast (Objet_U &)
static const Old_Debog & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 25 of file Old_Debog.h.
Constructor & Destructor Documentation
Old_Debog::Old_Debog ()
Definition at line 79 of file Debog.cpp.
Old_Debog::~Old_Debog ()
Definition at line 79 of file Debog.cpp.
Member Function Documentation
Objet_U * Old_Debog::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
int Old_Debog::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
const Type_info * Old_Debog::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
const Type_info * Old_Debog::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
Entree & Old_Debog::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Definition at line 94 of file Debog.cpp.
References Interprete_bloc::BLOC_EOF, Cerr, finl, Interprete_bloc::interprete_courant(), Interprete_bloc::interpreter_bloc(), and Process::je_suis_maitre().
{
  Nom nom_pb;
  is >> nom_pb;
  Nom nom_fic, nom_fic_faces;
  Nom seuil;
  int mode_db;
  is >> nom_fic >> nom_fic_faces >> seuil >> mode_db;
  Nom n("Debog_pb debog Lire debog { nom_pb ");
  n += nom_pb;
  n += " fichier_domaine ";
  n += nom_fic;
  n += " fichier_faces ";
  n += nom_fic_faces;
  n += " fichier_debog DEBOG";
  n += " seuil_absolu ";
  n += Nom(seuil);
  n += " seuil_relatif ";
  n += Nom(seuil);
  n += " mode_db ";
  if (mode_db == 0)
    n += "write";
  else
    n += "read";
  n += "  }";
  if (je_suis_maitre())
    Cerr << "Old_Debog: convert to new syntax: " << finl << n << finl;
  EChaine echaine(n);
  Interprete_bloc::interprete_courant().interpreter_bloc(echaine, Interprete_bloc::BLOC_EOF,
                                                         0 /* verifie_sans_interpreter */);
  return is;
}
Sortie & Old_Debog::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 82 of file Debog.cpp.
References Process::exit().
{
  exit();
  return os;
}
Entree & Old_Debog::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 88 of file Debog.cpp.
References Process::exit().
{
  exit();
  return is;
}
Old_Debog & Old_Debog::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
const Old_Debog & Old_Debog::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
unsigned Old_Debog::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 79 of file Debog.cpp.
Member Data Documentation
const Type_info Old_Debog::info_obj [static]
Reimplemented from Interprete.
Definition at line 27 of file Old_Debog.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Old_Debog.h
src/Kernel/Framework/Debog.cpp