TRUST: Masse_PolyMAC_Face Class Reference
Masse_PolyMAC_Face Class Reference
#include <Masse_PolyMAC_Face.h>
Public Member Functions
Masse_PolyMAC_Face ()
~Masse_PolyMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &matrix) const
DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const
DoubleTab & appliquer_impl (DoubleTab &) const
void appliquer_coef (DoubleVect &) const
void completer ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Masse_PolyMAC_Face & self_cast (Objet_U &)
static const Masse_PolyMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Private Attributes
bool no_diff_
Ref_Zone_PolyMAC la_zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_zone_Cl_PolyMAC
Detailed Description
Definition at line 37 of file Masse_PolyMAC_Face.h.
Constructor & Destructor Documentation
Masse_PolyMAC_Face::Masse_PolyMAC_Face ()
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
Masse_PolyMAC_Face::~Masse_PolyMAC_Face ()
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
Member Function Documentation
DoubleTab & Masse_PolyMAC_Face::ajouter_masse (double dt, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 145 of file Masse_PolyMAC_Face.cpp.
References appliquer_coef(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_PolyMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Solveur_Masse_base::has_coefficient_temporel_, Champ_Face_PolyMAC::icl, Zone_PolyMAC::init_m1(), Zone_PolyMAC::init_m2(), Champ_Face_PolyMAC::init_ra(), la_zone_Cl_PolyMAC, la_zone_PolyMAC, Zone_PolyMAC::m2c, Zone_PolyMAC::m2d, Zone_PolyMAC::m2i, Zone_PolyMAC::m2j, Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, valeur(), and Zone_VF::volumes().
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC;
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const Conds_lim& cls = la_zone_Cl_PolyMAC->les_conditions_limites();
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  const DoubleTab& nf = zone.face_normales();
  const DoubleVect& fs = zone.face_surfaces(), &pe = zone.porosite_elem(), &ve = zone.volumes();
  DoubleVect coef(zone.porosite_face());
  coef = 1.;
  int i, j, k, l, e, f, fb;
  if (has_coefficient_temporel_) appliquer_coef(coef);
  zone.init_m1(), zone.init_m2(), ch.init_ra();
// partie vitesses : vitesses imposees par CLs
  for (f = 0; f < zone.premiere_face_int(); f++)
    if (ch.icl(f, 0) == 3) for (k = 0, secmem(f) = 0; k < dimension; k++)//valeur imposee par une CL de type Dirichlet
        secmem(f) += nf(f, k) * ref_cast(Dirichlet, cls[ch.icl(f, 1)].valeur()).val_imp(ch.icl(f, 2), k) / fs(f);
    else if (ch.icl(f, 0) > 1) secmem(f) = 0; //Dirichlet homogene ou Symetrie
// partie vitesses : m2 / dt
  for (e = 0; e < zone.nb_elem_tot(); e++) for (i = 0, j = zone.m2d(e); j < zone.m2d(e + 1); i++, j++)
      for (f = e_f(e, i), k = zone.m2i(j); ch.icl(f, 0) < 2 && f < zone.nb_faces() && k < zone.m2i(j + 1); k++)
        if (ch.icl(fb = e_f(e, zone.m2j(k)), 0) < 2) //vfb calcule
          secmem(f) += ve(e) * pe(e) * zone.m2c(k) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * coef(f) * inco(fb) / dt;
        else if (ch.icl(fb, 0) == 3) for (l = 0; l < dimension; l++) //vfb impose par Dirichlet
            secmem(f) += ve(e) * pe(e) * zone.m2c(k) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * coef(f)
                         * ref_cast(Dirichlet, cls[ch.icl(fb, 1)].valeur()).val_imp(ch.icl(fb, 2), l) * nf(fb, l) / (fs(fb) * dt);
  return secmem;
}
Matrice_Base & Masse_PolyMAC_Face::ajouter_masse (double dt, Matrice_Base & matrice, int penalisation = 1) const [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 178 of file Masse_PolyMAC_Face.cpp.
References appliquer_coef(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_voisins(), Solveur_Masse_base::has_coefficient_temporel_, Champ_Face_PolyMAC::icl, Zone_PolyMAC::init_m1(), Zone_PolyMAC::init_m2(), Champ_Face_PolyMAC::init_ra(), la_zone_PolyMAC, Zone_PolyMAC::m2c, Zone_PolyMAC::m2d, Zone_PolyMAC::m2i, Zone_PolyMAC::m2j, Zone::nb_aretes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Matrice_Morse::nb_lignes(), Zone_dis_base::nb_som(), no_diff_, Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC;
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  const DoubleVect& pe = zone.porosite_elem(), &ve = zone.volumes();
  DoubleVect coef(zone.porosite_face());
  coef = 1.;
  int i, j, k, e, a, f, fb, nf_tot = zone.nb_faces_tot();
  Matrice_Morse& mat = ref_cast(Matrice_Morse, matrice);
  if (has_coefficient_temporel_) appliquer_coef(coef);
  zone.init_m1(), zone.init_m2(), ch.init_ra();
// partie vitesses : vitesses imposees par CLs
  for (f = 0; f < zone.premiere_face_int(); f++) if (ch.icl(f, 0) > 1) mat(f, f) = 1;
// partie vitesses : m2 / dt
  for (e = 0; e < zone.nb_elem_tot(); e++) for (i = 0, j = zone.m2d(e); j < zone.m2d(e + 1); i++, j++)
      for (f = e_f(e, i), k = zone.m2i(j); ch.icl(f, 0) < 2 && f < zone.nb_faces() && k < zone.m2i(j + 1); k++)
        if (ch.icl(fb = e_f(e, zone.m2j(k)), 0) < 2) //vfb calcule
          mat(f, fb) += ve(e) * pe(e) * zone.m2c(k) * (e == f_e(f, 0) ? 1 : -1) * (e == f_e(fb, 0) ? 1 : -1) * coef(f) / dt;
// partie vorticites : diagonale si Op_Diff_negligeable
  if (mat.nb_lignes() > nf_tot) for (a = 0; no_diff_ && a < (dimension < 3 ? zone.nb_som() : zone.zone().nb_aretes()); a++)
      mat(nf_tot + a, nf_tot + a) = 1;
  return matrice;
}
void Masse_PolyMAC_Face::appliquer_coef (DoubleVect & coef) const
Definition at line 208 of file Masse_PolyMAC_Face.cpp.
References coeff, MorEqn::equation(), Equation_base::get_champ(), Solveur_Masse_base::has_coefficient_temporel_, Equation_base::inconnue(), Solveur_Masse_base::name_of_coefficient_temporel_, DoubleTab::ref(), REF, ref_cast, Champ_Inc_base::remplir_coord_noeuds(), sub_type, tab_multiply_any_shape(), Deriv_Champ_Inc_base::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and VECT_REAL_ITEMS.
Referenced by ajouter_masse().
{
  if (has_coefficient_temporel_)
    {
      REF(Champ_base) ref_coeff;
      ref_coeff = equation().get_champ(name_of_coefficient_temporel_);
      DoubleTab values;
      if (sub_type(Champ_Inc_base,ref_coeff.valeur()))
        {
          const Champ_Inc_base& coeff = ref_cast(Champ_Inc_base,ref_coeff.valeur());
          ConstDoubleTab_parts val_parts(coeff.valeurs());
          values.ref(val_parts[0]);
        }
      else if (sub_type(Champ_Fonc_base,ref_coeff.valeur()))
        {
          const Champ_Fonc_base& coeff = ref_cast(Champ_Fonc_base,ref_coeff.valeur());
          values.ref(coeff.valeurs());
        }
      else if (sub_type(Champ_Don_base,ref_coeff.valeur()))
        {
          DoubleTab nodes;
          equation().inconnue().valeur().remplir_coord_noeuds(nodes);
          ref_coeff.valeur().valeur_aux(nodes,values);
        }
      tab_multiply_any_shape(coef, values, VECT_REAL_ITEMS);
    }
}
DoubleTab & Masse_PolyMAC_Face::appliquer_impl (DoubleTab & sm) const [virtual]
< sinon on ne fait pas ce qu'il faut
Implements Solveur_Masse_base.
Definition at line 68 of file Masse_PolyMAC_Face.cpp.
References Cerr, Objet_U::dimension, DoubleTab::dimension_tot(), MorEqn::equation(), Process::exit(), finl, Champ_Face_PolyMAC::icl, Champ_Face_PolyMAC::init_cl(), la_zone_Cl_PolyMAC, la_zone_PolyMAC, DoubleVect::line_size(), DoubleTab::nb_dim(), O_U_Ptr::non_nul(), ref_cast, valeur(), and Ref_Zone_PolyMAC::valeur().
{
// hors faces de bord, on ne fait rien et on passe secmem a corriger_derivee_* (car PolyMAC a une matrice de masse)
  assert(la_zone_PolyMAC.non_nul());
  assert(la_zone_Cl_PolyMAC.non_nul());
  const Zone_PolyMAC& zone_PolyMAC = la_zone_PolyMAC.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  ch.init_cl();
  assert(sm.nb_dim() <= 2); //!< sinon on ne fait pas ce qu'il faut
  int nb_faces_tot = zone_PolyMAC.nb_faces_tot();
  int nb_aretes_tot = (dimension < 3 ? zone_PolyMAC.nb_som_tot() : zone_PolyMAC.zone().nb_aretes_tot()), nc = sm.line_size();
  if (sm.dimension_tot(0) != nb_faces_tot && sm.dimension_tot(0) != nb_faces_tot + nb_aretes_tot)
    {
      Cerr << "Masse_PolyMAC_Face::appliquer :  erreur dans la taille de sm" << finl;
      exit();
    }
// mise a zero de la partie vitesse de sm sur les faces a vitesse imposee
  for (int f = 0; f < zone_PolyMAC.nb_faces(); f++) if (ch.icl(f, 0) > 1)
      for (int k = 0; k < nc; k++) sm(f, k) = 0;
  return sm;
}
void Masse_PolyMAC_Face::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 100 of file Masse_PolyMAC_Face.cpp.
References la_zone_Cl_PolyMAC, and ref_cast.
{
  la_zone_Cl_PolyMAC = ref_cast(Zone_Cl_PolyMAC, la_zone_Cl_dis_base);
}
void Masse_PolyMAC_Face::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 95 of file Masse_PolyMAC_Face.cpp.
References la_zone_PolyMAC, and ref_cast.
{
  la_zone_PolyMAC = ref_cast(Zone_PolyMAC, la_zone_dis_base);
}
void Masse_PolyMAC_Face::completer (void) [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 105 of file Masse_PolyMAC_Face.cpp.
References Cerr, MorEqn::equation(), Process::exit(), finl, no_diff_, Equation_base::nombre_d_operateurs(), Objet_U::que_suis_je(), Equation_base::schema_temps(), and sub_type.
{
  if (!sub_type(Schema_Implicite_base, equation().schema_temps()))
    {
      Cerr << "===================================================================================" << finl;
      Cerr << "Error when using " << equation().schema_temps().que_suis_je() << " scheme:" << finl;
      Cerr << "You can only use implicit schemes with the PolyMAC discretization (for mass solver)." << finl;
      Process::exit();
    }
  no_diff_ = true;
  for(int i = 0; i < equation().nombre_d_operateurs(); i++)
    if (sub_type(Operateur_Diff_base, equation().operateur(i).l_op_base()))
      if (!sub_type(Op_Diff_negligeable, equation().operateur(i).l_op_base())) no_diff_ = false;
}
Objet_U * Masse_PolyMAC_Face::cree_instance () [static]
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
void Masse_PolyMAC_Face::dimensionner (Matrice_Morse & matrix) const [virtual]
Reimplemented from Solveur_Masse_base.
Definition at line 120 of file Masse_PolyMAC_Face.cpp.
References Matrix_tools::allocate_morse_matrix(), IntTab::append_line(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Champ_Face_PolyMAC::icl, Zone_PolyMAC::init_m1(), Zone_PolyMAC::init_m2(), Champ_Face_PolyMAC::init_ra(), la_zone_PolyMAC, Zone_PolyMAC::m2d, Zone_PolyMAC::m2i, Zone_PolyMAC::m2j, Zone::nb_aretes(), Zone::nb_aretes_tot(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Matrice_Morse::nb_lignes(), Zone_dis_base::nb_som(), Zone::nb_som_tot(), no_diff_, ref_cast, ArrOfInt::set_smart_resize(), tableau_trier_retirer_doublons(), valeur(), and Zone_dis_base::zone().
{
  const Zone_PolyMAC& zone = la_zone_PolyMAC;
  const IntTab& e_f = zone.elem_faces();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  int i, j, k, e, a, f, fb, nf_tot = zone.nb_faces_tot(), na_tot = dimension < 3 ? zone.zone().nb_som_tot() : zone.zone().nb_aretes_tot();
  const bool only_m2 = (matrix.nb_lignes() == nf_tot);
  zone.init_m1(), zone.init_m2(), ch.init_ra();
  IntTab indice(0,2);
  indice.set_smart_resize(1);
// partie vitesses : matrice de masse des vitesses si la face n'est pas a vitesse imposee, diagonale sinon
  for (e = 0; e < zone.nb_elem_tot(); e++) for (i = 0, j = zone.m2d(e); j < zone.m2d(e + 1); i++, j++)
      if (ch.icl(f = e_f(e, i), 0) > 1 && f < zone.nb_faces()) indice.append_line(f, f);
      else for (k = zone.m2i(j); f < zone.nb_faces() && k < zone.m2i(j + 1); k++)
          if (ch.icl(fb = e_f(e, zone.m2j(k)), 0) < 2) indice.append_line(f, fb);
// partie vorticites : diagonale si pas de diffusion
  if (!only_m2) for (a = 0; no_diff_ && a < (dimension < 3 ? zone.nb_som() : zone.zone().nb_aretes()); a++)
      indice.append_line(nf_tot + a, nf_tot + a);
  tableau_trier_retirer_doublons(indice);
  Matrix_tools::allocate_morse_matrix(nf_tot + !only_m2 * na_tot, nf_tot + !only_m2 * na_tot, indice, matrix);
}
int Masse_PolyMAC_Face::duplique () const [virtual]
Implements Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
const Type_info * Masse_PolyMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
const Type_info * Masse_PolyMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
Sortie & Masse_PolyMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 47 of file Masse_PolyMAC_Face.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Masse_PolyMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 55 of file Masse_PolyMAC_Face.cpp.
{
  return s ;
}
const Masse_PolyMAC_Face & Masse_PolyMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
Masse_PolyMAC_Face & Masse_PolyMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Solveur_Masse_base.
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
unsigned Masse_PolyMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 41 of file Masse_PolyMAC_Face.cpp.
Member Data Documentation
const Type_info Masse_PolyMAC_Face::info_obj [static]
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_PolyMAC_Face.h.
Ref_Zone_Cl_PolyMAC Masse_PolyMAC_Face::la_zone_Cl_PolyMAC [private]
Definition at line 59 of file Masse_PolyMAC_Face.h.
Referenced by ajouter_masse(), appliquer_impl(), and associer_zone_cl_dis_base().
Ref_Zone_PolyMAC Masse_PolyMAC_Face::la_zone_PolyMAC [private]
Definition at line 58 of file Masse_PolyMAC_Face.h.
Referenced by ajouter_masse(), appliquer_impl(), associer_zone_dis_base(), and dimensionner().
bool Masse_PolyMAC_Face::no_diff_ [private]
Definition at line 57 of file Masse_PolyMAC_Face.h.
Referenced by ajouter_masse(), completer(), and dimensionner().
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Masse_PolyMAC_Face.h
src/PolyMAC/Zones/Masse_PolyMAC_Face.cpp