TRUST: Deriv_Champ_base Class Reference
Deriv_Champ_base Class Reference
#include <Champ.h>
Public Member Functions
~Deriv_Champ_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_base ()
Deriv_Champ_base (const Deriv_Champ_base &)
const Champ_base & valeur () const
Champ_base & valeur ()
const Champ_base * operator-> () const
Champ_base * operator-> ()
const Deriv_Champ_base & operator= (const Champ_base &)
const Deriv_Champ_base & operator= (const Deriv_Champ_base &)
operator const Champ_base & () const
operator Champ_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Champ_base & self_cast (Objet_U &)
static const Deriv_Champ_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_base * pointeur_
Detailed Description
Definition at line 30 of file Champ.h.
Constructor & Destructor Documentation
Deriv_Champ_base::~Deriv_Champ_base ()
Definition at line 25 of file Champ.cpp.
Deriv_Champ_base::Deriv_Champ_base ()
Definition at line 25 of file Champ.cpp.
Deriv_Champ_base::Deriv_Champ_base (const Deriv_Champ_base & t)
Definition at line 25 of file Champ.cpp.
Member Function Documentation
Objet_U * Deriv_Champ_base::cree_instance () [static]
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
int Deriv_Champ_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
const Type_info * Deriv_Champ_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
const Type_info & Deriv_Champ_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Champ.cpp.
const Type_info * Deriv_Champ_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
Deriv_Champ_base::operator Champ_base & ()
Definition at line 25 of file Champ.cpp.
Deriv_Champ_base::operator const Champ_base & () const
Definition at line 25 of file Champ.cpp.
const Champ_base * Deriv_Champ_base::operator-> () const [inline]
Definition at line 30 of file Champ.h.
: public DERIV(Champ_base), public Champ_Proto
Champ_base * Deriv_Champ_base::operator-> () [inline]
Definition at line 30 of file Champ.h.
: public DERIV(Champ_base), public Champ_Proto
const Deriv_Champ_base & Deriv_Champ_base::operator= (const Deriv_Champ_base & t)
Definition at line 25 of file Champ.cpp.
const Deriv_Champ_base & Deriv_Champ_base::operator= (const Champ_base & t)
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
Sortie & Deriv_Champ_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
Entree & Deriv_Champ_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
const Deriv_Champ_base & Deriv_Champ_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
Deriv_Champ_base & Deriv_Champ_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
void Deriv_Champ_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Champ.cpp.
unsigned Deriv_Champ_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Champ.
Definition at line 25 of file Champ.cpp.
const Champ_base & Deriv_Champ_base::valeur () const [inline]
Definition at line 30 of file Champ.h.
Referenced by Champ::affecter(), Champ::affecter_compo(), Milieu_base::calculer_alpha(), Fluide_base::calculer_nu(), Champ::changer_temps(), Fluide_base::creer_nu(), Milieu_base::discretiser(), Champ::fixer_nb_comp(), Champ::fixer_nom_compo(), Champ::fixer_noms_compo(), Champ::fixer_unite(), Champ::fixer_unites(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Morceau_Equation::get_champ(), Champ_Generique_Interpolation::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Champ::get_champ(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Transformation::get_champ_without_evaluation(), Champ_Generique_Morceau_Equation::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Gradient::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Generique_Divergence::get_champ_without_evaluation(), Champ_Generique_Champ::get_ref_champ_base(), Milieu_composite::initialiser(), Fluide_reel_base::initialiser(), Milieu_base::initialiser(), Milieu_composite::initTimeStep(), Fluide_reel_base::initTimeStep(), Fluide_base::initTimeStep(), Champ::le_nom(), Fluide_reel_base::mettre_a_jour(), Champ::mettre_a_jour(), Champ::nb_comp(), Champ::nom_compo(), Champ::nommer(), Champ::noms_compo(), Champ::operator=(), Champ::temps(), Champ::unite(), Champ::unites(), Milieu_base::update_rho_cp(), Champ::valeur_a(), Champ::valeur_a_elem(), Champ::valeur_a_elem_compo(), Champ::valeur_a_sommet_compo(), Champ::valeur_aux(), Champ::valeur_aux_compo(), Champ::valeur_aux_elems(), Champ::valeur_aux_elems_compo(), Champ::valeurs(), and Fluide_Incompressible::verifier_coherence_champs().
: public DERIV(Champ_base), public Champ_Proto
Champ_base & Deriv_Champ_base::valeur () [inline]
Definition at line 30 of file Champ.h.
: public DERIV(Champ_base), public Champ_Proto
Member Data Documentation
const Type_info Deriv_Champ_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Champ.
Definition at line 30 of file Champ.h.
Champ_base* Deriv_Champ_base::pointeur_ [private]
Definition at line 30 of file Champ.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ.h
src/Kernel/Framework/Champ.cpp