TRUST: FloatTab Class Reference
FloatTab Class Reference
#include <FloatTab.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
FloatTab ()
FloatTab (int ni, int nj)
FloatTab (const FloatTab &tab)
const FloatTab & operator= (const FloatTab &tab)
~FloatTab () override
float operator() (int i, int j) const
float & operator() (int i, int j)
int dimension (int i) const
int nb_dim () const
void resize (int ni, int nj)
Public Member Functions inherited from ArrOfFloat
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
ArrOfFloat ()
Construit un tableau vide.
ArrOfFloat (int n)
Constructeur d'un tableau vide de taille n.
Le tableau n'est pas initialise.
ArrOfFloat (const ArrOfFloat &array)
Constructeur par copie.
const ArrOfFloat & operator= (const ArrOfFloat &array)
Operateur copie (deep copy)
~ArrOfFloat () override
Destructeur.
float & operator[] (int i) const
Renvoie la i-ieme valeur du tableau (0 <= i < taille)
float & operator[] (int i)
Renvoie la i-ieme valeur du tableau (0 <= i < taille)
void ordonne_array ()
ArrOfFloat & inject_array (const ArrOfFloat &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
Copie les elements source[first_element_source + i]
dans les elements (*this)[first_element_dest + i] pour 0 <= i < nb_elements
Les autres elements de (*this) sont inchanges.
int size_array () const
Renvoie le nombre de valeurs dans le tableau.
float * addr ()
const float * addr () const
void resize_array (int size)
Changement de taille du tableau, en cas d'augmentation,
le contenu des nouveaux elements est indefini.
const ArrOfFloat & operator*= (const float)
muliplie toutes les cases par dy
const ArrOfFloat & operator/= (const float)
divise toutes les cases par dy
const ArrOfFloat & operator= (const float)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static FloatTab & self_cast (Objet_U &)
static const FloatTab & self_cast (const Objet_U &)
Static Public Member Functions inherited from ArrOfFloat
static Objet_U * cree_instance ()
static const Type_info * info ()
static ArrOfFloat & self_cast (Objet_U &)
static const ArrOfFloat & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from ArrOfFloat
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Entree & readOn (Entree &) override
Lecture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Protected Member Functions inherited from ArrOfFloat
Sortie & printOn (Sortie &x) const override
Ecriture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Entree & readOn (Entree &) override
Lecture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
void mem_resize (int size)
Augmentation de taille du tableau (appele uniquement si l'espace
memoire est insuffisant et qu'il faut reallouer de la memoire).
Les anciennes donnees sont recopiees dans le nouveau tableau,
le contenu des elements nouveaux est indefini.
void invalidate (int first_element, int nb_elements)
remplit nb_elements consecutifs du tableau avec une valeur invalide
en commencant par l'indice first_element.
Il faut first_element >= 0 et first_element+nb_elements <= memory_size_.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int ni_
int nj_
Protected Attributes inherited from ArrOfFloat
float * data_
int size_
Nombre d'elements du tableau.
int memory_size_
Taille allouee (on a memory_size_ >= size_)
Additional Inherited Members
Static Protected Attributes inherited from ArrOfFloat
static const int grow_factor_num_ = 2
static const int grow_factor_denom_ = 1
Detailed Description
Definition at line 21 of file FloatTab.h.
Constructor & Destructor Documentation
FloatTab() [1/3]
FloatTab::FloatTab ()
Definition at line 21 of file FloatTab.cpp.
                   :
  ni_(0), nj_(0)
{
}
FloatTab() [2/3]
FloatTab::FloatTab (int ni, int nj)
Definition at line 26 of file FloatTab.cpp.
                                 :
  ni_(0), nj_(0)
{
  resize(ni, nj);
}
References resize().
FloatTab() [3/3]
FloatTab::FloatTab (const FloatTab & tab)
Definition at line 32 of file FloatTab.cpp.
                                      :
  ArrOfFloat(tab), ni_(tab.ni_), nj_(tab.nj_)
{
}
~FloatTab()
FloatTab::~FloatTab () override
Definition at line 49 of file FloatTab.cpp.
{
  ni_ = nj_ = 0;
}
References ni_, and nj_.
Member Function Documentation
cree_instance()
Objet_U * FloatTab::cree_instance () static
Definition at line 17 of file FloatTab.cpp.
dimension()
int FloatTab::dimension (int i) const inline
Definition at line 56 of file FloatTab.h.
{
  assert(i == 0 || i == 1);
  return (i == 0) ? ni_ : nj_;
}
References ni_, and nj_.
Referenced by latatoother::interpreter().
duplique()
int FloatTab::duplique () const override virtual
Reimplemented from ArrOfFloat.
Definition at line 17 of file FloatTab.cpp.
get_info()
const Type_info * FloatTab::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from ArrOfFloat.
Definition at line 17 of file FloatTab.cpp.
info()
const Type_info * FloatTab::info () static
Definition at line 17 of file FloatTab.cpp.
nb_dim()
int FloatTab::nb_dim () const inline
Definition at line 62 of file FloatTab.h.
{
  return 2;
}
operator()() [1/2]
float & FloatTab::operator() (int i, int j) inline
Definition at line 50 of file FloatTab.h.
{
  assert(i >= 0 && i < ni_ && j >= 0 && j < nj_);
  return data_[i*nj_+j];
}
References ArrOfFloat::data_, and nj_.
operator()() [2/2]
float FloatTab::operator() (int i, int j) const inline
Definition at line 44 of file FloatTab.h.
{
  assert(i >= 0 && i < ni_ && j >= 0 && j < nj_);
  return data_[i*nj_+j];
}
References ArrOfFloat::data_, and nj_.
operator=()
const FloatTab & FloatTab::operator= (const FloatTab & tab)
Definition at line 39 of file FloatTab.cpp.
{
  ArrOfFloat::operator=(tab);
  ni_ = tab.ni_;
  nj_ = tab.nj_;
  return *this;
}
References ni_, nj_, and ArrOfFloat::operator=().
printOn()
Sortie & FloatTab::printOn (Sortie & x) const override protected virtual
Ecriture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Reimplemented from ArrOfFloat.
Definition at line 75 of file FloatTab.cpp.
{
  os << (int)2 << finl;
  os << ni_ << nj_ << finl;
  os << size_ << finl;
  if (size_ > 0)
    os.put(data_, size_, nj_);
  return os;
}
References ArrOfFloat::data_, finl, ni_, nj_, Sortie::put(), and ArrOfFloat::size_.
readOn()
Entree & FloatTab::readOn (Entree & is) override protected virtual
Lecture du tableau. Format :
n (int)
x[0] x[1] x[2] ... x[n-1] (float)
Reimplemented from ArrOfFloat.
Definition at line 56 of file FloatTab.cpp.
{
// nbdim pour compatibilite avec IntTab
  int nbdim;
  is >> nbdim;
  assert(nbdim == 2);
  is >> ni_ >> nj_;
  assert(ni_ >= 0 && nj_ >= 0);
  int mysize;
  is >> mysize;
  assert(mysize == ni_ * nj_);
// Resize en deux fois pour ne pas faire de memcpy inutile
  resize_array(0);
  resize_array(ni_ * nj_);
  if (size_ > 0)
    is.get(data_, size_);
  return is;
}
References ArrOfFloat::data_, Entree::get(), ni_, nj_, ArrOfFloat::resize_array(), and ArrOfFloat::size_.
resize()
void FloatTab::resize (int ni, int nj) inline
Definition at line 67 of file FloatTab.h.
{
  assert(ni >= 0 && nj >= 0);
  int new_size = ni * nj;
  resize_array(new_size);
  ni_ = ni;
  nj_ = nj;
}
References ni_, nj_, and ArrOfFloat::resize_array().
Referenced by FloatTab().
self_cast() [1/2]
const FloatTab & FloatTab::self_cast (const Objet_U & r) static
Definition at line 17 of file FloatTab.cpp.
self_cast() [2/2]
FloatTab & FloatTab::self_cast (Objet_U & r) static
Definition at line 17 of file FloatTab.cpp.
taille_memoire()
unsigned FloatTab::taille_memoire () const override virtual
Reimplemented from ArrOfFloat.
Definition at line 17 of file FloatTab.cpp.
Member Data Documentation
info_obj
const Type_info FloatTab::info_obj static
Definition at line 23 of file FloatTab.h.
ni_
int FloatTab::ni_ protected
Definition at line 39 of file FloatTab.h.
Referenced by dimension(), operator=(), printOn(), readOn(), resize(), and ~FloatTab().
nj_
int FloatTab::nj_ protected
Definition at line 39 of file FloatTab.h.
Referenced by dimension(), operator()(), operator=(), printOn(), readOn(), resize(), and ~FloatTab().
The documentation for this class was generated from the following files:
src/Kernel/Math/FloatTab.h
src/Kernel/Math/FloatTab.cpp