TRUST: Solveur_Lineaire_Std Class Reference
Solveur_Lineaire_Std Class Reference
#include <Solveur_Lineaire_Std.h>
Public Member Functions
Solveur_Lineaire_Std ()
~Solveur_Lineaire_Std ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
SolveurSys & solveur_sys (void)
const SolveurSys & solveur_sys (void) const
Public Member Functions inherited from Solveur_lineaire
Solveur_lineaire ()
~Solveur_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solveur_Lineaire_Std & self_cast (Objet_U &)
static const Solveur_Lineaire_Std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_lineaire
static const Type_info * info ()
static Solveur_lineaire & self_cast (Objet_U &)
static const Solveur_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Solveur_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
SolveurSys solveur
Detailed Description
Definition at line 25 of file Solveur_Lineaire_Std.h.
Constructor & Destructor Documentation
Solveur_Lineaire_Std()
Solveur_Lineaire_Std::Solveur_Lineaire_Std ()
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
~Solveur_Lineaire_Std()
Solveur_Lineaire_Std::~Solveur_Lineaire_Std ()
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
Member Function Documentation
cree_instance()
Objet_U * Solveur_Lineaire_Std::cree_instance () static
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
duplique()
int Solveur_Lineaire_Std::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
get_info()
const Type_info * Solveur_Lineaire_Std::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_lineaire.
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
info()
const Type_info * Solveur_Lineaire_Std::info () static
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
iterer_eqn()
bool Solveur_Lineaire_Std::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) override virtual
Implements Solveur_Implicite_Base.
Definition at line 94 of file Solveur_Lineaire_Std.cpp.
{
  assert( numero_iteration == 1 );
  Matrice_Morse matrix;
  DoubleTrav    rhs(result);
  equation.dimensionner_matrice(matrix);
  equation.assembler_avec_inertie(matrix, inconnue, rhs);
  solveur.valeur().reinit();
  solveur.resoudre_systeme(matrix, rhs, result);
  return true;
}
References Equation_base::assembler_avec_inertie(), Equation_base::dimensionner_matrice(), SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), solveur, and Deriv_SolveurSys_base::valeur().
printOn()
Sortie & Solveur_Lineaire_Std::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Solveur_lineaire.
Definition at line 26 of file Solveur_Lineaire_Std.cpp.
{
  Cerr << " The implicit solver used is of type Solveur_Lineaire_Std " << finl;
  return Solveur_lineaire::printOn(os);
}
References Cerr, finl, and Solveur_lineaire::printOn().
readOn()
Entree & Solveur_Lineaire_Std::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Solveur_lineaire.
Definition at line 32 of file Solveur_Lineaire_Std.cpp.
{
  Cerr << " The implicit solver used is of type Solveur_Lineaire_Std " << finl;
  Motcles les_mots(1);
  {
    les_mots[0] = "solveur";
  }
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "One expected a { when reading " << que_suis_je() << finl;
      Cerr << "instead of : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while(motlu != accolade_fermee )
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
// case 0 : {
// is >> seuil_convg_implicite_;
// break;
// }
// case 1 : {
// is >> seuil_resol_implicite_;
// break;
// }
        case 0 :
          {
            Nom nom_solveur("Solv_");
            Nom type_solv_sys;
            is >> type_solv_sys;
            nom_solveur+=type_solv_sys;
            Cerr << "nom_solveur " << nom_solveur << finl;
            solveur.typer(nom_solveur);
            is >> solveur.valeur();
            solveur.nommer("solveur_implicite");
            break;
          }
        default :
          {
            Cerr<<"An object of type "<<que_suis_je()<<" cannot read the word "<<motlu<<finl;
            Cerr<<"One expected a word among :"<<finl<<les_mots<<finl;
            abort();
          }
        }
      is >> motlu;
    }
  if (!solveur.non_nul())
    {
      Cerr << "Error among the data given for the implicite time scheme " << finl;
      Cerr << "The solver has not been specified.  " << finl;
      exit();
    }
  return is;
}
References Process::abort(), Cerr, Process::exit(), finl, SolveurSys::nommer(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Motcles::search(), solveur, Deriv_::typer(), and Deriv_SolveurSys_base::valeur().
self_cast() [1/2]
const Solveur_Lineaire_Std & Solveur_Lineaire_Std::self_cast (const Objet_U & r) static
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
self_cast() [2/2]
Solveur_Lineaire_Std & Solveur_Lineaire_Std::self_cast (Objet_U & r) static
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
solveur_sys() [1/2]
const SolveurSys & Solveur_Lineaire_Std::solveur_sys (void) inline
Definition at line 42 of file Solveur_Lineaire_Std.h.
{
  return solveur;
}
References solveur.
solveur_sys() [2/2]
const SolveurSys & Solveur_Lineaire_Std::solveur_sys (void) const inline
taille_memoire()
unsigned Solveur_Lineaire_Std::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Solveur_Lineaire_Std.cpp.
Member Data Documentation
info_obj
const Type_info Solveur_Lineaire_Std::info_obj static
Definition at line 27 of file Solveur_Lineaire_Std.h.
solveur
SolveurSys Solveur_Lineaire_Std::solveur protected
Definition at line 37 of file Solveur_Lineaire_Std.h.
Referenced by iterer_eqn(), readOn(), and solveur_sys().
The documentation for this class was generated from the following files:
src/Kernel/Solveurs/Solveur_Lineaire_Std.h
src/Kernel/Solveurs/Solveur_Lineaire_Std.cpp