TRUST: Champ_implementation_Q1 Class Reference
Champ_implementation_Q1 Class Reference abstract
: class Champ_implementation_Q1
Decrire ici la classe Champ_implementation_Q1
#include <Champ_implementation_Q1.h>
Public Member Functions
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
~Champ_implementation_Q1 () override
void value_interpolation (const DoubleTab &positions, const ArrOfInt &cells, const DoubleTab &values, DoubleTab &resu, int ncomp=-1) const override
Public Member Functions inherited from Champ_implementation_sommet_base
Champ_base & le_champ (void) override=0
const Champ_base & le_champ (void) const override=0
~Champ_implementation_sommet_base () override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_implementation_base
virtual ~Champ_implementation_base ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Private Member Functions
virtual double form_function (const ArrOfDouble &position, int cell, int ddl) const
Additional Inherited Members
Protected Member Functions inherited from Champ_implementation_sommet_base
virtual void value_interpolation (const DoubleTab &positions, const ArrOfInt &cells, const DoubleTab &values, DoubleTab &resu, int ncomp=-1) const =0
DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const override
DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const override
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation_base
virtual DoubleTab & valeur_aux_sommets_impl (DoubleTab &result) const =0
virtual DoubleVect & valeur_aux_sommets_compo_impl (DoubleVect &result, int ncomp) const =0
const Zone_VF & get_zone_dis (void) const
const Zone & get_zone_geom (void) const
virtual Champ_base & le_champ (void)=0
virtual const Champ_base & le_champ (void) const =0
Detailed Description
: class Champ_implementation_Q1
Decrire ici la classe Champ_implementation_Q1
Definition at line 28 of file Champ_implementation_Q1.h.
Constructor & Destructor Documentation
~Champ_implementation_Q1()
Champ_implementation_Q1::~Champ_implementation_Q1 () inline override
Definition at line 36 of file Champ_implementation_Q1.h.
{ };
Member Function Documentation
form_function()
double Champ_implementation_Q1::form_function (const ArrOfDouble & position, int cell, int ddl) const private virtual
Definition at line 264 of file Champ_implementation_Q1.cpp.
{
  if (info==0)
    {
      Cerr << "***********************************************************************" << finl;
      Cerr << "Warning : shape functions of the Q1 elements are not coded !" << finl;
      Cerr << finl;
      Cerr << "For the moment, the value of the elements is not interpolated." << finl;
      Cerr << "It returns the average value on the element, ie the point value" << finl;
      Cerr << "at the barycenter of the element" << finl;
      Cerr << finl;
      Cerr << "It is therefore recommended to postprocess the Q1 fields only"<< finl;
      Cerr << "on mesh nodes." << finl;
      Cerr << "***********************************************************************" << finl;
      info=1;
    }
  const Zone& zone_geom = get_zone_geom();
  int test_sommet=1;
  if (test_sommet)
    {
      const IntTab& cells    = zone_geom.les_elems();
      const DoubleTab& nodes = zone_geom.domaine().les_sommets();
      int nb_nodes_per_cell = cells.dimension(1);
      int sc=-1;
      double l=Objet_U::precision_geom*Objet_U::precision_geom;
      for (int s=0; s<nb_nodes_per_cell; s++)
        {
          int som=cells(cell,s);
          double dist=0;
          for (int j=0; j<Objet_U::dimension; j++)
            {
              double dx=(nodes(som,j)-position[j]);
              dist+=dx*dx;
            }
          if (dist<l)
            sc=s;
        }
      if (sc!=-1)
        {
// Cerr<< ddl<< " sc "<< sc <<finl;
          if (ddl==sc)
            return 1;
          else
            return 0;
        }
    }
  double factor = 1./zone_geom.nb_som_elem();
  return factor;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), finl, Champ_implementation_base::get_zone_geom(), info, Zone::les_elems(), Domaine::les_sommets(), Zone::nb_som_elem(), and Objet_U::precision_geom.
le_champ() [1/2]
const Champ_base & Champ_implementation_Q1::le_champ (void) const override pure virtual
Implements Champ_implementation_sommet_base.
Implemented in Champ_Fonc_Q1_base, and Champ_Inc_Q1_base.
le_champ() [2/2]
Champ_base & Champ_implementation_Q1::le_champ (void) override pure virtual
Implements Champ_implementation_sommet_base.
Implemented in Champ_Fonc_Q1_base, and Champ_Inc_Q1_base.
value_interpolation()
void Champ_implementation_Q1::value_interpolation (const DoubleTab & positions, const ArrOfInt & cells, const DoubleTab & values, DoubleTab & resu, int ncomp = -1) const override virtual
Implements Champ_implementation_sommet_base.
Definition at line 125 of file Champ_implementation_Q1.cpp.
{
  const Zone&      zone  = get_zone_geom();
  const IntTab&    les_elems = zone.les_elems();
  const DoubleTab& nodes = zone.domaine().les_sommets();
  const int nb_nodes_per_cell = les_elems.dimension(1);
  ArrOfDouble position(Objet_U::dimension);
  Vecteur3 coeff_plan;
  double d;
  IntTab cell3D;
  Vecteur3 coord_bar;
  resu = 0;
  for (int ic=0; ic<cells.size_array(); ic++)
    {
      int cell = cells[ic];
      if (cell<0) continue;
      for (int k = 0; k < Objet_U::dimension; k++)
        position[k] = positions(ic, k);
      if (nb_nodes_per_cell == 4)
        {
          if (Objet_U::dimension == 3)
            {
              cell3D.resize(1, 8);
              for (int i = 0; i < 4; i++)
                cell3D(0, 2 * i) = les_elems(cell, i);
              calcul_plan_hexa(coeff_plan, d, 0, cell3D, nodes, 0);
              double A = d;
              for (int i = 0; i < Objet_U::dimension; i++) A += coeff_plan[i] * position[i];
              if (std::fabs(A) > std::fabs(d) * 1e-5)
                {
                  Cerr << "Error point not in the plane " << finl;
                  Process::exit();
                }
              coord_bar = 0.5;
            }
          else
            for (int dir = 0; dir < 2; dir++)
              {
                calcul_plan_quadra(coeff_plan, d, cell, les_elems, nodes, dir);
                double A = d;
                for (int i = 0; i < Objet_U::dimension; i++) A += coeff_plan[i] * position[i];
                calcul_plan_quadra(coeff_plan, d, cell, les_elems, nodes, dir + 2);
                double B = d;
                for (int i = 0; i < Objet_U::dimension; i++) B += coeff_plan[i] * position[i];
                assert(inf_ou_egal((A * B), 0, 1e-10));
                coord_bar[dir] = A / (A - B);
              }
        }
      else
        {
          assert(Objet_U::dimension == 3);
          for (int dir = 0; dir < 3; dir++)
            {
              calcul_plan_hexa(coeff_plan, d, cell, les_elems, nodes, dir);
              double A = d;
              for (int i = 0; i < 3; i++) A += coeff_plan[i] * position[i];
              calcul_plan_hexa(coeff_plan, d, cell, les_elems, nodes, dir + 3);
              double B = d;
              for (int i = 0; i < 3; i++) B += coeff_plan[i] * position[i];
              assert(inf_ou_egal((A * B), 0, 1e-10));
              coord_bar[dir] = A / (A - B);
            }
        }
      ArrOfDouble val(nb_nodes_per_cell);
      int nb_dim = resu.nb_dim();
      int nb_components = nb_dim == 1 ? 1 : resu.dimension_tot(1);
      for (int k = 0; k < nb_components; k++)
        {
          if (ncomp != -1)
            {
              for (int j = 0; j < nb_nodes_per_cell; j++)
                {
                  int node = les_elems(cell, j);
                  val[j] = values(node, ncomp);
                }
            }
          else
            {
              if (values.nb_dim() == 1)
                {
                  for (int j = 0; j < nb_nodes_per_cell; j++)
                    {
                      int node = les_elems(cell, j);
                      val[j] = values(node);
                    }
                }
              else
                {
                  assert(values.nb_dim() == 2);
                  for (int j = 0; j < nb_nodes_per_cell; j++)
                    {
                      int node = les_elems(cell, j);
                      val[j] = values(node, k);
                    }
                }
            }
          double res = 0;
          if (nb_nodes_per_cell == 4)
            {
              const double i = coord_bar[0];
              const double j = coord_bar[1];
              double unmi = 1. - i;
              double unmj = 1. - j;
              res = unmj * (unmi * val[0] + i * val[1])
                    + j * (unmi * val[2] + i * val[3]);
            }
          else
            {
              assert(Objet_U::dimension == 3);
              const double i = coord_bar[0];
              const double j = coord_bar[1];
              const double kk = coord_bar[2];
              double unmi = 1. - i;
              double unmj = 1. - j;
              double unmk = 1. - kk;
              res = unmk * (unmj * (unmi * val[0] + i * val[1])
                            + j * (unmi * val[2] + i * val[3]))
                    + kk * (unmj * (unmi * val[4] + i * val[5])
                            + j * (unmi * val[6] + i * val[7]));
            }
          if (nb_dim==1)
            resu(ic) = res;
          else
            resu(ic, k) = res;
        }
    }
}
References calcul_plan_hexa(), calcul_plan_quadra(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Zone::domaine(), Process::exit(), finl, Champ_implementation_base::get_zone_geom(), inf_ou_egal(), Zone::les_elems(), Domaine::les_sommets(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTTab< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), and Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_implementation_Q1.h
src/Kernel/Champs_dis/Champ_implementation_Q1.cpp