TRUST: Parametre_diffusion_implicite Class Reference
Parametre_diffusion_implicite Class Reference
classe Parametre_diffusion_implicite
Un objet Parametre_diffusion_implicite est un objet regroupant les differentes
options specifiques pour diffusion_implicite
#include <Parametre_diffusion_implicite.h>
Public Member Functions
Parametre_diffusion_implicite ()
~Parametre_diffusion_implicite ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
const double & seuil_diffusion_implicite () const
const int & nb_it_max () const
const int & crank () const
const int & precoditionnement_diag () const
SolveurSys & solveur ()
Matrice_Morse & matrice ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Parametre_diffusion_implicite & self_cast (Objet_U &)
static const
Parametre_diffusion_implicite & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
int preconditionnement_diag_
int crank_
int nb_it_max_
double seuil_diffusion_implicite_
SolveurSys solveur_
Solveur utilise pour la resolution diffusion implicite.
Matrice_Morse matrice_
Matrice pour la resolution diffusion implicite.
Detailed Description
classe Parametre_diffusion_implicite
Un objet Parametre_diffusion_implicite est un objet regroupant les differentes
options specifiques pour diffusion_implicite
Definition at line 41 of file Parametre_diffusion_implicite.h.
Constructor & Destructor Documentation
Parametre_diffusion_implicite::Parametre_diffusion_implicite ()
Definition at line 29 of file Parametre_diffusion_implicite.cpp.
References crank_, nb_it_max_, preconditionnement_diag_, and seuil_diffusion_implicite_.
{
  preconditionnement_diag_=0;
  crank_=0;
  nb_it_max_=-1;
  seuil_diffusion_implicite_=-1;
}
Parametre_diffusion_implicite::~Parametre_diffusion_implicite ()
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
Member Function Documentation
const int& Parametre_diffusion_implicite::crank () const [inline]
Definition at line 54 of file Parametre_diffusion_implicite.h.
References crank_.
Referenced by Equation_base::Gradient_conjugue_diff_impl().
  {
    return crank_ ;
  };
Objet_U * Parametre_diffusion_implicite::cree_instance () [static]
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
int Parametre_diffusion_implicite::duplique () const [virtual]
Implements Parametre_equation_base.
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
const Type_info * Parametre_diffusion_implicite::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
const Type_info * Parametre_diffusion_implicite::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
int Parametre_diffusion_implicite::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Objet_U.
Definition at line 60 of file Parametre_diffusion_implicite.cpp.
References Cerr, Process::exit(), finl, SolveurSys::nommer(), Objet_U::que_suis_je(), and solveur_.
{
  Motcle motlu;
  if (mot=="solveur")
    {
      is >> solveur_;
      solveur_.nommer("solveur_diffusion_implicite");
    }
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
Matrice_Morse& Parametre_diffusion_implicite::matrice () [inline]
Definition at line 63 of file Parametre_diffusion_implicite.h.
References matrice_.
{ return matrice_; }
const int& Parametre_diffusion_implicite::nb_it_max () const [inline]
Definition at line 50 of file Parametre_diffusion_implicite.h.
References nb_it_max_.
Referenced by Equation_base::Gradient_conjugue_diff_impl().
  {
    return nb_it_max_ ;
  };
const int& Parametre_diffusion_implicite::precoditionnement_diag () const [inline]
Definition at line 58 of file Parametre_diffusion_implicite.h.
References preconditionnement_diag_.
Referenced by Equation_base::Gradient_conjugue_diff_impl().
  {
    return  preconditionnement_diag_ ;
  };
Sortie & Parametre_diffusion_implicite::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 38 of file Parametre_diffusion_implicite.cpp.
{
  return os;
}
Entree & Parametre_diffusion_implicite::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 48 of file Parametre_diffusion_implicite.cpp.
References Param::ajouter(), Param::ajouter_non_std(), crank_, Param::lire_avec_accolades_depuis(), nb_it_max_, preconditionnement_diag_, Objet_U::que_suis_je(), and seuil_diffusion_implicite_.
{
  Param param(que_suis_je());
  param.ajouter("crank",&crank_);
  param.ajouter("niter_max_diffusion_implicite",&nb_it_max_);
  param.ajouter("preconditionnement_diag",&preconditionnement_diag_);
  param.ajouter("seuil_diffusion_implicite",&seuil_diffusion_implicite_);
  param.ajouter_non_std("solveur",(this));
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Parametre_diffusion_implicite & Parametre_diffusion_implicite::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Parametre_equation_base.
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
Parametre_diffusion_implicite & Parametre_diffusion_implicite::self_cast (Objet_U & r) [static]
Reimplemented from Parametre_equation_base.
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
const double& Parametre_diffusion_implicite::seuil_diffusion_implicite () const [inline]
Definition at line 46 of file Parametre_diffusion_implicite.h.
References seuil_diffusion_implicite_.
Referenced by Equation_base::Gradient_conjugue_diff_impl().
  {
    return seuil_diffusion_implicite_ ;
  };
SolveurSys& Parametre_diffusion_implicite::solveur () [inline]
Definition at line 62 of file Parametre_diffusion_implicite.h.
References solveur_.
{ return solveur_; }
unsigned Parametre_diffusion_implicite::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Parametre_diffusion_implicite.cpp.
Member Data Documentation
int Parametre_diffusion_implicite::crank_ [protected]
Definition at line 66 of file Parametre_diffusion_implicite.h.
Referenced by crank(), Parametre_diffusion_implicite(), and readOn().
const Type_info Parametre_diffusion_implicite::info_obj [static]
Reimplemented from Parametre_equation_base.
Definition at line 43 of file Parametre_diffusion_implicite.h.
Matrice_Morse Parametre_diffusion_implicite::matrice_ [protected]
Matrice pour la resolution diffusion implicite.
Definition at line 70 of file Parametre_diffusion_implicite.h.
Referenced by matrice().
int Parametre_diffusion_implicite::nb_it_max_ [protected]
Definition at line 67 of file Parametre_diffusion_implicite.h.
Referenced by nb_it_max(), Parametre_diffusion_implicite(), and readOn().
int Parametre_diffusion_implicite::preconditionnement_diag_ [protected]
Definition at line 65 of file Parametre_diffusion_implicite.h.
Referenced by Parametre_diffusion_implicite(), precoditionnement_diag(), and readOn().
double Parametre_diffusion_implicite::seuil_diffusion_implicite_ [protected]
Definition at line 68 of file Parametre_diffusion_implicite.h.
Referenced by Parametre_diffusion_implicite(), readOn(), and seuil_diffusion_implicite().
SolveurSys Parametre_diffusion_implicite::solveur_ [protected]
Solveur utilise pour la resolution diffusion implicite.
Definition at line 69 of file Parametre_diffusion_implicite.h.
Referenced by lire_motcle_non_standard(), and solveur().
The documentation for this class was generated from the following files:
src/Kernel/Solveurs/Parametre_diffusion_implicite.h
src/Kernel/Solveurs/Parametre_diffusion_implicite.cpp