TRUST: Probleme_Couple Class Reference
Probleme_Couple Class Reference
classe Probleme_Couple
C'est la classe historique de couplage de TRUST.
Il s'agit d'un Couplage_U particulier.
Le Probleme_Couple ne couple que des Probleme_base, tous
associes au meme schema en temps.
Il possede son propre mecanisme d'echange de champs par "raccords".
Les problemes sont groupes. Chaque groupe fait un iteration, puis les
nouveaux champs sont disponibles pour les groupes suivants. A l'interieur
d'un groupe, ce sont les anciens champs qui sont echanges.
#include <Probleme_Couple.h>
Public Member Functions
Probleme_Couple ()
~Probleme_Couple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool solveTimeStep () override
pour recodage eventuel et appel unifie en python
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
void ajouter (Probleme_base &)
Ajoute un probleme a la liste des problemes couples.
Met en place la reference du probleme vers this.
Verifie que l'ordre conduction, thHyd est respecte.
int associer_ (Objet_U &) override
Surcharge Objet_U::associer_(Objet_U&)
Associe un objet au probleme couple, en verifiant le type
dynamiquement. L'objet peut-etre:
- un schema en temps (Schema_Temps_base), et on l'associe aux problemes
- un probleme (Probleme_base), on l'ajoute a la liste.
virtual void associer_sch_tps_base (Schema_Temps_base &)
Associe une copie du schema en temps a chaque probleme
du Probleme couple.
virtual const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe aux problemes couples.
(version const)
virtual Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe aux problemes couples.
virtual void discretiser (const Discretisation_base &)
Associe une discretisation a tous les problemes du probleme
couple.
Appelle Probleme_Base::discretiser(const Discretisation_base&)
sur chacun des problemes du probleme couple.
voir Probleme_Base::discretiser(const Discretisation_base&)
virtual void mettre_a_jour_modele_rayo (double temps)
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
Public Member Functions inherited from Couplage_U
Couplage_U ()
~Couplage_U ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
int limpr () const override
Doit-on imprimer les statistiques d'execution maintenant ?
int lsauv () const override
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
void sauver () const override
Sauvegarder l'etat du probleme sur disque.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
void addProblem (Probleme_U &)
Append a problem to the list.
int nb_problemes () const
Number of problems.
const Probleme_U & probleme (int i) const
Access by index (const)
Probleme_U & probleme (int i)
Access by index.
const Probleme_U & probleme (const Nom &nom_pb) const
Access by name (const)
Probleme_U & probleme (const Nom &nom_pb)
Access by name.
int indice_probleme (const Nom &nom_pb) const
Index from name.
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Probleme_Couple & self_cast (Objet_U &)
static const Probleme_Couple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Couplage_U
static Objet_U * cree_instance ()
static const Type_info * info ()
static Couplage_U & self_cast (Objet_U &)
static const Couplage_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Couplage_U
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime les problemes couples sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Probleme_U
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ArrOfInt groupes
Vect_Schema_Temps sch_clones
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Detailed Description
classe Probleme_Couple
C'est la classe historique de couplage de TRUST.
Il s'agit d'un Couplage_U particulier.
Le Probleme_Couple ne couple que des Probleme_base, tous
associes au meme schema en temps.
Il possede son propre mecanisme d'echange de champs par "raccords".
Les problemes sont groupes. Chaque groupe fait un iteration, puis les
nouveaux champs sont disponibles pour les groupes suivants. A l'interieur
d'un groupe, ce sont les anciens champs qui sont echanges.
Definition at line 52 of file Probleme_Couple.h.
Constructor & Destructor Documentation
Probleme_Couple()
Probleme_Couple::Probleme_Couple ()
Definition at line 26 of file Probleme_Couple.cpp.
~Probleme_Couple()
Probleme_Couple::~Probleme_Couple ()
Definition at line 26 of file Probleme_Couple.cpp.
Member Function Documentation
ajouter()
void Probleme_Couple::ajouter (Probleme_base & pb)
Ajoute un probleme a la liste des problemes couples.
Met en place la reference du probleme vers this.
Verifie que l'ordre conduction, thHyd est respecte.
Definition at line 242 of file Probleme_Couple.cpp.
{
  addProblem(pb);
  pb.set_coupled(1);
  int nb_pb=nb_problemes();
  Nom nom_pb=probleme(nb_pb-1).que_suis_je();
  if (nb_pb!=1
      && probleme(0).que_suis_je()=="Pb_Conduction"
      && nom_pb.prefix("Turbulent") != probleme(nb_pb-1).que_suis_je())
    {
      Cerr << finl;
      Cerr << "Warning !" << finl;
      Cerr << "You define a conduction problem named "<<probleme(0).le_nom()<<" before your turbulent thermalhydraulic problem named "<<probleme(nb_pb-1).le_nom()<<"." << finl;
      Cerr << "Please, define first your turbulent thermalhydraulic problem in your data file like:" << finl;
      Cerr << finl;
      Cerr << "Probleme_Couple "<<le_nom()<< finl;
      for (int i=nb_pb-1; i>=0; i--)
        Cerr << "Associer "<<le_nom()<<" "<<probleme(i).le_nom()<<finl;
      Cerr << finl;
      exit();
    }
}
References Couplage_U::addProblem(), Cerr, Process::exit(), finl, Probleme_U::le_nom(), Couplage_U::nb_problemes(), Nom::prefix(), Couplage_U::probleme(), Objet_U::que_suis_je(), and Probleme_base::set_coupled().
Referenced by associer_(), and readOn().
associer_()
int Probleme_Couple::associer_ (Objet_U & ob) override virtual
Surcharge Objet_U::associer_(Objet_U&)
Associe un objet au probleme couple, en verifiant le type
dynamiquement. L'objet peut-etre:
- un schema en temps (Schema_Temps_base), et on l'associe aux problemes
- un probleme (Probleme_base), on l'ajoute a la liste.
Returns
int
Signification: 1 si l'association a reussie 0 sinon
Contraintes:
Reimplemented from Objet_U.
Definition at line 300 of file Probleme_Couple.cpp.
{
  if( sub_type(Schema_Temps_base, ob))
    {
      associer_sch_tps_base(ref_cast(Schema_Temps_base, ob));
      return 1;
    }
  else if( sub_type(Probleme_base, ob))
    {
      Probleme_base& pb = ref_cast(Probleme_base, ob);
      ajouter(pb);
      return 1;
    }
  else
    return 0;
}
References ajouter(), associer_sch_tps_base(), ref_cast, and sub_type.
Referenced by Pbc_MED::readOn().
associer_sch_tps_base()
void Probleme_Couple::associer_sch_tps_base (Schema_Temps_base & sch) virtual
Associe une copie du schema en temps a chaque probleme
du Probleme couple.
< Clonage du schema
< association On attribue la valeur 1 a schema_impr_ pour le schema du probleme 0 et 0 pour les autres. Un seul schema doit imprimer.
Definition at line 334 of file Probleme_Couple.cpp.
{
  sch_clones.dimensionner(nb_problemes());
  for (int i=0; i<nb_problemes(); i++)
    {
      sch_clones[i]=sch; //!< Clonage du schema
      Probleme_base& pb=ref_cast(Probleme_base,probleme(i));
      pb.associer_sch_tps_base(sch_clones[i]); //!< association On attribue la valeur 1 a schema_impr_ pour le schema du probleme 0 et 0 pour les autres. Un seul schema doit imprimer.
//
//
      if (i!=0) pb.schema_temps().schema_impr()=0;
    }
}
References Probleme_base::associer_sch_tps_base(), vect_impl::dimensionner(), Couplage_U::nb_problemes(), Couplage_U::probleme(), ref_cast, sch_clones, Schema_Temps_base::schema_impr(), and Probleme_base::schema_temps().
Referenced by associer_(), and Pbc_MED::readOn().
computeTimeStep()
double Probleme_Couple::computeTimeStep (bool & stop) const override virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
Returns
double
Signification: The desired time step
Contraintes:
Reimplemented from Probleme_U.
Definition at line 47 of file Probleme_Couple.cpp.
{
  double dt_=DMAXFLOAT;
// On prend le dt min.
// On stoppe si l'un des problemes veut stopper.
  for (int i=0; i<nb_problemes(); i++)
    {
      double dt1=probleme(i).computeTimeStep(stop);
      if (stop)
        return 0;
      if (dt1<dt_)
        dt_=dt1;
    }
  return dt_;
}
References Probleme_U::computeTimeStep(), DMAXFLOAT, Couplage_U::nb_problemes(), and Couplage_U::probleme().
cree_instance()
Objet_U * Probleme_Couple::cree_instance () static
Definition at line 26 of file Probleme_Couple.cpp.
discretiser()
void Probleme_Couple::discretiser (const Discretisation_base & dis) virtual
Associe une discretisation a tous les problemes du probleme
couple.
Appelle Probleme_Base::discretiser(const Discretisation_base&)
sur chacun des problemes du probleme couple.
voir Probleme_Base::discretiser(const Discretisation_base&)
Definition at line 417 of file Probleme_Couple.cpp.
{
// Loop to discretize each problem of the coupled problem:
  for(int i=0; i< nb_problemes(); i++)
    {
      Cerr<<"The problem that we are starting to discretize is "<<probleme(i).le_nom()<<finl;
      Probleme_base& pb=ref_cast(Probleme_base,probleme(i));
      pb.discretiser(dis);
    }
}
References Cerr, Probleme_base::discretiser(), finl, Probleme_U::le_nom(), Couplage_U::nb_problemes(), Couplage_U::probleme(), and ref_cast.
Referenced by Discretiser::interpreter().
duplique()
int Probleme_Couple::duplique () const override virtual
Reimplemented from Couplage_U.
Reimplemented in Pbc_MED.
Definition at line 26 of file Probleme_Couple.cpp.
get_info()
const Type_info * Probleme_Couple::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Couplage_U.
Reimplemented in Pbc_MED.
Definition at line 26 of file Probleme_Couple.cpp.
info()
const Type_info * Probleme_Couple::info () static
Definition at line 26 of file Probleme_Couple.cpp.
initialize()
void Probleme_Couple::initialize () override virtual
This method is called once at the beginning, before any other one of
the interface Problem.
Reimplemented from Couplage_U.
Definition at line 267 of file Probleme_Couple.cpp.
{
  for (int i=0; i<nb_problemes(); i++)
    {
      Probleme_base& pb=ref_cast(Probleme_base,probleme(i));
// On attribue la valeur 1 a schema_impr_ pour le schema du probleme 0
// et 0 pour les autres. Un seul schema doit imprimer.
      pb.schema_temps().schema_impr()=(i==0);
    }
  Couplage_U::initialize();
}
References Couplage_U::initialize(), Couplage_U::nb_problemes(), Couplage_U::probleme(), ref_cast, Schema_Temps_base::schema_impr(), and Probleme_base::schema_temps().
initTimeStep()
bool Probleme_Couple::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
Returns
bool
Signification: true=OK, false=error, not able to tackle this dt
Contraintes:
Reimplemented from Couplage_U.
Definition at line 34 of file Probleme_Couple.cpp.
{
  /*
  double& residu_max = schema_temps().residu();
  double test=residu_max;
  for (int i=1; i<nb_problemes(); i++)
    residu_max = std::max(residu_max,sch_clones[i]->residu());
  if (test!=residu_max) abort();
  */
  bool ok =  Couplage_U::initTimeStep(dt);
  return ok;
}
References Couplage_U::initTimeStep().
iterateTimeStep()
bool Probleme_Couple::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
Returns
bool
Signification: true=OK, false=unable to converge
Contraintes:
Reimplemented from Couplage_U.
Definition at line 94 of file Probleme_Couple.cpp.
{
  bool ok=true;
  converged=true;
  int debut_gr=0;
  int fin_gr=0;
  int gr=0;
  while(ok && fin_gr<nb_problemes())
    {
      if (gr<groupes.size_array())
        fin_gr += groupes[gr++];
      else
        fin_gr=nb_problemes();
      for(int i=debut_gr; ok && i<fin_gr; i++)
        ok &= probleme(i).updateGivenFields();
      for(int i=debut_gr; ok && i<fin_gr; i++)
        {
          bool cv;
          ok &= probleme(i).iterateTimeStep(cv);
          converged = converged && cv;
        }
      debut_gr=fin_gr;
    }
  return ok;
}
References groupes, Probleme_U::iterateTimeStep(), Couplage_U::nb_problemes(), Couplage_U::probleme(), TRUSTArray< _TYPE_ >::size_array(), and Probleme_U::updateGivenFields().
mettre_a_jour_modele_rayo()
void Probleme_Couple::mettre_a_jour_modele_rayo (double temps) inline virtual
Definition at line 101 of file Probleme_Couple.h.
{
  Cerr<<"The method Probleme_Couple::mettre_a_jour_modele_rayo does nothing"<<finl;
  Cerr<<"We should not pass through here"<<finl;
  exit();
}
References Cerr, Process::exit(), and finl.
printOn()
Sortie & Probleme_Couple::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime les problemes couples sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Couplage_U.
Reimplemented in Pbc_MED.
Definition at line 206 of file Probleme_Couple.cpp.
{
  for(int i=1; i< nb_problemes(); i++)
    os << probleme(i) << finl;
  return os;
}
References finl, Couplage_U::nb_problemes(), and Couplage_U::probleme().
readOn()
Entree & Probleme_Couple::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< fin du readOn
Reimplemented from Couplage_U.
Reimplemented in Pbc_MED.
Definition at line 136 of file Probleme_Couple.cpp.
{
  Cerr << "Reading of Probleme_Couple " << le_nom() << finl;
  Motcle motlu;
  is >> motlu;
  if (motlu != Motcle("{"))
    {
      Cerr << "We expected { to start to read the Probleme_Couple" << finl;
      exit();
    }
  is >> motlu;
  while (motlu!=Motcle("}"))   //!< fin du readOn
    {
      if (motlu != Motcle("groupes"))
        {
          Cerr << "The keyword " << motlu << " is not understood" << finl;
          exit();
        }
      if (nb_problemes())
        {
          Cerr << "We can associate problems to Probleme_Couple" << finl;
          Cerr << "* either by \"associer prob_couple pb\" (in which case they are all in the same group)" << finl;
          Cerr << "* either by the keyword \"groupes\" while reading the object Probleme_Couple" << finl;
          Cerr << "but not both!" << finl;
        }
      assert(nb_problemes()==0);
      LIST(LIST(Nom)) les_noms;
      is >> les_noms;
      groupes.resize_array(les_noms.size());
      for (int i=0; i<les_noms.size(); i++)
        {
          groupes[i]=les_noms[i].size();
          for (int j=0; j<les_noms[i].size(); j++)
            {
              Nom nom_pb=les_noms[i][j];
              Objet_U& ob=Interprete::objet(nom_pb);
              Probleme_base& pb=ref_cast(Probleme_base,ob);
              ajouter(pb);
            }
        }
      is >> motlu;
    }
  return is;
}
References ajouter(), Cerr, Process::exit(), finl, groupes, Probleme_U::le_nom(), LIST, Couplage_U::nb_problemes(), Interprete::objet(), ref_cast, and TRUSTArray< _TYPE_ >::resize_array().
schema_temps() [1/2]
Schema_Temps_base & Probleme_Couple::schema_temps () virtual
Renvoie le schema en temps associe aux problemes couples.
Returns
Schema_Temps_base&
Signification: le schema en temps associe
Contraintes:
Definition at line 388 of file Probleme_Couple.cpp.
{
  if (nb_problemes()==0)
    {
      Cerr << "You forgot to associate problems to the coupled problem named " << le_nom() << finl;
      Process::exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base,probleme(0));
  return pb.schema_temps();
}
References Cerr, Process::exit(), finl, Probleme_U::le_nom(), Couplage_U::nb_problemes(), Couplage_U::probleme(), ref_cast, and Probleme_base::schema_temps().
schema_temps() [2/2]
const Schema_Temps_base & Probleme_Couple::schema_temps () const virtual
Renvoie le schema en temps associe aux problemes couples.
(version const)
Returns
Schema_Temps_base&
Signification: le schema en temps associe
Contraintes: reference constante
Definition at line 362 of file Probleme_Couple.cpp.
{
  if (nb_problemes()==0)
    {
      Cerr << "You forgot to associate problems to the coupled problem named " << le_nom() << finl;
      Process::exit();
    }
  const Probleme_base& pb=ref_cast(Probleme_base,probleme(0));
  return pb.schema_temps();
}
References Cerr, Process::exit(), finl, Probleme_U::le_nom(), Couplage_U::nb_problemes(), Couplage_U::probleme(), ref_cast, and Probleme_base::schema_temps().
Referenced by Discretiser::interpreter(), Pbc_MED::readOn(), and solveTimeStep().
self_cast() [1/2]
const Probleme_Couple & Probleme_Couple::self_cast (const Objet_U & r) static
Definition at line 26 of file Probleme_Couple.cpp.
self_cast() [2/2]
Probleme_Couple & Probleme_Couple::self_cast (Objet_U & r) static
Definition at line 26 of file Probleme_Couple.cpp.
solveTimeStep()
bool Probleme_Couple::solveTimeStep (void) override virtual
pour recodage eventuel et appel unifie en python
Reimplemented from Probleme_U.
Definition at line 66 of file Probleme_Couple.cpp.
{
// WEC : A changer !!!!
  if (sch_clones.size())
    if (sub_type(Schema_Euler_Implicite,schema_temps()))
      {
        Schema_Euler_Implicite& sch_eul_imp=ref_cast(Schema_Euler_Implicite,schema_temps());
        int ok = 1, cv;
        cv = sch_eul_imp.faire_un_pas_de_temps_pb_couple(*this, ok);
        if (!ok) return false;
// on propage un certain nombre de choses vers les clones
        for (int i=1; i<sch_clones.size(); i++)
          {
            sch_clones[i].facteur_securite_pas()=schema_temps().facteur_securite_pas();
            sch_clones[i]->set_stationnaire_atteint()=schema_temps().stationnaire_atteint();
            sch_clones[i]->residu()=schema_temps().residu();
          }
        return cv;
      }
  bool ok=Couplage_U::solveTimeStep();
  double& residu_max = schema_temps().residu();
  for (int i=1; i<nb_problemes(); i++)
    residu_max = std::max(residu_max,ref_cast(Probleme_base,probleme(i)).schema_temps().residu());
  return ok;
}
References Schema_Temps_base::facteur_securite_pas(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Couplage_U::nb_problemes(), Couplage_U::probleme(), ref_cast, Schema_Temps_base::residu(), sch_clones, schema_temps(), vect_impl::size(), Probleme_U::solveTimeStep(), Schema_Temps_base::stationnaire_atteint(), and sub_type.
taille_memoire()
unsigned Probleme_Couple::taille_memoire () const override virtual
Reimplemented from Couplage_U.
Reimplemented in Pbc_MED.
Definition at line 26 of file Probleme_Couple.cpp.
updateGivenFields()
bool Probleme_Couple::updateGivenFields () override virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
true=OK, false=error
Signification:
Contraintes:
Reimplemented from Couplage_U.
Definition at line 215 of file Probleme_Couple.cpp.
{
// Pas de champs provenant de l'exterieur du couplage.
// Les echanges internes se font pendant iterateTimeStep.
  return true;
}
Member Data Documentation
groupes
ArrOfInt Probleme_Couple::groupes protected
Definition at line 95 of file Probleme_Couple.h.
Referenced by iterateTimeStep(), and readOn().
info_obj
const Type_info Probleme_Couple::info_obj static
Definition at line 54 of file Probleme_Couple.h.
sch_clones
Vect_Schema_Temps Probleme_Couple::sch_clones protected
Definition at line 98 of file Probleme_Couple.h.
Referenced by associer_sch_tps_base(), and solveTimeStep().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Probleme_Couple.h
src/Kernel/Framework/Probleme_Couple.cpp