TRUST: Operateur_Conv Class Reference
Operateur_Conv Class Reference
classe Operateur_Conv
Classe generique de la hierarchie des operateurs representant un terme
de convection. Un objet Operateur_Conv peut referencer n'importe quel
objet derivant de Operateur_Conv_base.
#include <Operateur_Conv.h>
Public Member Functions
Operateur_Conv ()
~Operateur_Conv ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Operateur_base & l_op_base ()
Renvoie l'objet sous-jacent upcaste en Operateur_base.
const Operateur_base & l_op_base () const
Renvoie l'objet sous-jacent upcaste en Operateur_base<br>(version const)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
Ajoute la contribution de l'operateur au tableau
passe en parametre.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
Initialise le tableau passe en parametre avec la contribution
de l'operateur.
void associer_vitesse (const Champ_base &)
Associe la vitesse (en tant que vitesse transportante)
a l'operateur de convection.
const Champ_base & vitesse () const
Renvoie la vitesse transportante de l'operateur.
void typer ()
Type l'operateur:
"Op_Conv" + motcle + discretisation + inconnue
Associe la vitesse transportante a l'operateur base.
void typer (const Nom &)
Type l'operateur.
virtual int op_non_nul () const
void associer_norme_vitesse (const Champ_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Operateur_Conv & self_cast (Objet_U &)
static const Operateur_Conv & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Operateur::ecrire(Sortie&)
Ecrit l'operateur sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a Operateur::lire(Entree&)
Lit l'operateur a partir d'un flot d'entree.
Protected Attributes
Ref_Champ_base la_vitesse
Detailed Description
classe Operateur_Conv
Classe generique de la hierarchie des operateurs representant un terme
de convection. Un objet Operateur_Conv peut referencer n'importe quel
objet derivant de Operateur_Conv_base.
Definition at line 44 of file Operateur_Conv.h.
Constructor & Destructor Documentation
Operateur_Conv::Operateur_Conv ()
Definition at line 30 of file Operateur_Conv.cpp.
Operateur_Conv::~Operateur_Conv ()
Definition at line 30 of file Operateur_Conv.cpp.
Member Function Documentation
DoubleTab & Operateur_Conv::ajouter (const DoubleTab & donnee, DoubleTab & resu) const [virtual]
Ajoute la contribution de l'operateur au tableau
passe en parametre.
Returns:
DoubleTab&
Signification: le tableau contenant le resultat
Contraintes:
Implements Operateur.
Definition at line 133 of file Operateur_Conv.cpp.
References Operateur_base::ajouter(), Statistiques::begin_count(), convection_counter_, Statistiques::end_count(), statistiques(), and Deriv_Operateur_Conv_base::valeur().
Referenced by Op_Conv_ALE::ajouter().
{
  statistiques().begin_count(convection_counter_);
  DoubleTab& tmp = valeur().ajouter(donnee, resu);
  statistiques().end_count(convection_counter_);
  return tmp;
}
void Operateur_Conv::associer_norme_vitesse (const Champ_base & norme_vitesse)
Definition at line 172 of file Operateur_Conv.cpp.
References Operateur_Conv_base::associer_norme_vitesse(), op_non_nul(), and Deriv_Operateur_Conv_base::valeur().
{
  assert( op_non_nul() );
  valeur().associer_norme_vitesse(norme_vitesse);
}
void Operateur_Conv::associer_vitesse (const Champ_base & vit) [inline]
Associe la vitesse (en tant que vitesse transportante)
a l'operateur de convection.
Returns:
Champ_Inc&
Signification: le champ inconnue representant la vitesse transportante
Contraintes:
Definition at line 117 of file Operateur_Conv.h.
References la_vitesse.
Referenced by Navier_Stokes_std::lire_motcle_non_standard(), and Convection_Diffusion_std::lire_motcle_non_standard().
{
  la_vitesse = vit;
}
DoubleTab & Operateur_Conv::calculer (const DoubleTab & donnee, DoubleTab & resu) const [virtual]
Initialise le tableau passe en parametre avec la contribution
de l'operateur.
Returns:
DoubleTab&
Signification: le tableau contenant le resultat
Contraintes:
Implements Operateur.
Definition at line 163 of file Operateur_Conv.cpp.
References Statistiques::begin_count(), Operateur_base::calculer(), convection_counter_, Statistiques::end_count(), statistiques(), and Deriv_Operateur_Conv_base::valeur().
Referenced by Op_Conv_ALE::calculer().
{
  statistiques().begin_count(convection_counter_);
  DoubleTab& tmp = valeur().calculer(donnee, resu);
  statistiques().end_count(convection_counter_);
  return tmp;
}
Objet_U * Operateur_Conv::cree_instance () [static]
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
int Operateur_Conv::duplique () const [virtual]
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
const Type_info * Operateur_Conv::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
const Type_info * Operateur_Conv::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
Operateur_base & Operateur_Conv::l_op_base () [inline, virtual]
Renvoie l'objet sous-jacent upcaste en Operateur_base.
Returns:
Operateur_base&
Signification: l'objet sous-jacent upcaste en Operateur_base
Contraintes:
Implements Operateur.
Definition at line 78 of file Operateur_Conv.h.
References Deriv_Operateur_Conv_base::valeur().
Referenced by Op_Conv_ALE::associer().
{
  return valeur();
}
const Operateur_base & Operateur_Conv::l_op_base () const [inline, virtual]
Renvoie l'objet sous-jacent upcaste en Operateur_base<br>(version const)
Returns:
Operateur_base&
Signification: l'objet sous-jacent upcaste en Operateur_base
Contraintes: reference constante
Implements Operateur.
Definition at line 97 of file Operateur_Conv.h.
References Deriv_Operateur_Conv_base::valeur().
{
  return valeur();
}
int Operateur_Conv::op_non_nul () const [inline, virtual]
Implements Operateur.
Definition at line 162 of file Operateur_Conv.h.
References O_U_Ptr::non_nul().
Referenced by associer_norme_vitesse(), and Convection_Diffusion_Concentration::readOn().
{
  if (non_nul())
    return 1;
  else
    return 0;
}
Sortie & Operateur_Conv::printOn (Sortie & os) const [protected, virtual]
Simple appel a Operateur::ecrire(Sortie&)
Ecrit l'operateur sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 48 of file Operateur_Conv.cpp.
References Operateur::ecrire().
{
  return Operateur::ecrire(os);
}
Entree & Operateur_Conv::readOn (Entree & is) [protected, virtual]
Simple appel a Operateur::lire(Entree&)
Lit l'operateur a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 69 of file Operateur_Conv.cpp.
References Operateur::lire(), Objet_U::que_suis_je(), and Deriv_Operateur_Conv_base::valeur().
{
  Operateur::lire(is);
  if (valeur().que_suis_je()=="Op_Conv_ALE_VEF" )//|| valeur().que_suis_je()=="Op_Conv_ALE_VDF")
    {
// Op_Conv_ALE_VEF& mon_op_conv_ALE_VEF=ref_cast(Op_Conv_ALE_VEF, valeur());
// valeur().lire_op_conv(is);
    }
  return is;
}
const Operateur_Conv & Operateur_Conv::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
Operateur_Conv & Operateur_Conv::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
unsigned Operateur_Conv::taille_memoire () const [virtual]
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 30 of file Operateur_Conv.cpp.
void Operateur_Conv::typer (const Nom & a_type) [inline]
Type l'operateur.
Definition at line 157 of file Operateur_Conv.h.
References DERIV, and typer().
{
  DERIV(Operateur_Conv_base)::typer(a_type);
}
void Operateur_Conv::typer () [virtual]
Type l'operateur:
"Op_Conv" + motcle + discretisation + inconnue
Associe la vitesse transportante a l'operateur base.
Implements Operateur.
Definition at line 98 of file Operateur_Conv.cpp.
References Operateur_Conv_base::associer_vitesse(), Cerr, DERIV, Equation_base::discretisation(), finl, Discretisation_base::get_name_of_type_for(), MorEqn::mon_equation, Objet_U::que_suis_je(), Operateur::typ, Deriv_Operateur_Conv_base::valeur(), Ref_Equation_base::valeur(), and vitesse().
Referenced by typer().
{
  if (Motcle(typ)==Motcle("negligeable"))
    DERIV(Operateur_Conv_base)::typer("Op_Conv_negligeable");
  else
    {
      Equation_base& eqn=mon_equation.valeur();
      Nom nom_type=eqn.discretisation().get_name_of_type_for(que_suis_je(),typ,eqn,vitesse());
      DERIV(Operateur_Conv_base)::typer(nom_type);
      valeur().associer_vitesse(vitesse());
    }
  Cerr << valeur().que_suis_je() << finl;
}
const Champ_base & Operateur_Conv::vitesse () const [inline]
Renvoie la vitesse transportante de l'operateur.
Returns:
Champ_Inc&
Signification: le champ inconnue representant la vitesse transportante
Contraintes: reference constante
Definition at line 136 of file Operateur_Conv.h.
References la_vitesse, and Ref_Champ_base::valeur().
Referenced by typer().
{
  return la_vitesse.valeur();
}
Member Data Documentation
const Type_info Operateur_Conv::info_obj [static]
Reimplemented from Deriv_Operateur_Conv_base.
Definition at line 46 of file Operateur_Conv.h.
Ref_Champ_base Operateur_Conv::la_vitesse [protected]
Definition at line 61 of file Operateur_Conv.h.
Referenced by associer_vitesse(), and vitesse().
The documentation for this class was generated from the following files:
src/Kernel/Operateurs/Operateur_Conv.h
src/Kernel/Operateurs/Operateur_Conv.cpp