TRUST: Statistiques Class Reference
Statistiques Class Reference
#include <Statistiques.h>
Public Member Functions
Statistiques ()
~Statistiques ()
void set_debug_level (int level)
Stat_Counter_Id new_counter (int level, const char *const description, const char *const familly=0, int comm=0)
void begin_count (const Stat_Counter_Id &counter_id, bool track_comm=true)
void end_count (const Stat_Counter_Id &counter_id, int quantity=0, int count=1, bool track_comm=true)
Arret du compteur counter_id. On ajoute quantity a la somme des
'quantity' (par defaut 0) stockees pour ce compteur
et on ajoute 'count' (par defaut 1) au compteur d'appels a end_count pour ce compteur<br>(quantity sert a sommer par exemple la taille des donnees traitees pendant ce comptage<br>et count sert a compter combien de fois on a appele ce compteur)
double last_time (const Stat_Counter_Id &counter_id)
void dump (const char *message_info, int mode_append)
void reset_counters ()
void reset_counter (int counter_id)
void stop_counters ()
void restart_counters ()
void get_stats (const Stat_Counter_Id &counter_id, Stat_Results &result)
void get_stats_familly (const char *familly, Stat_Results &result)
void cumulate_stats (int counter_id, Stat_Results &result)
double get_total_time ()
void compute_avg_min_max_var_per_step (int tstep)
int allocate_communication_tracking_times ()
int delete_communication_tracking_times ()
void begin_communication_tracking (int cid)
void end_communication_tracking (int cid)
void print_communciation_tracking_details (const char *message, int mode_append)
const char * get_counter_family (int id)
int get_counter_id_from_index_in_comm_tracking_info (int index) const
int get_index_in_comm_tracking_info_from_counter_id (int id) const
int get_nb_comm_counters () const
Stat_Results get_communication_tracking_info (int i, int j) const
void set_three_first_steps_elapsed (bool b)
int get_counter_id_from_description (const char *desc) const
Static Public Member Functions
static double get_time_now ()
Cette methode renvoie un temps en secondes depuis une origine
qui depend de la methode de mesure de la classe Time. Precision, normalement
de l'ordre de 1ms ou inferieur.
Protected Member Functions
void begin_count_ (const int id_)
void end_count_ (const int id_, int quantity, int count)
Protected Attributes
int debug_level_
Stat_Internals * stat_internals
double total_time_
bool three_first_steps_elapsed_
Detailed Description
Definition at line 30 of file Statistiques.h.
Constructor & Destructor Documentation
Statistiques()
Statistiques::Statistiques ()
Definition at line 364 of file Statistiques.cpp.
{
  total_time_ = 0;
  debug_level_ = 0;
  three_first_steps_elapsed_ = false;
  stat_internals = new Stat_Internals();
}
References debug_level_, stat_internals, three_first_steps_elapsed_, and total_time_.
~Statistiques()
Statistiques::~Statistiques ()
Definition at line 372 of file Statistiques.cpp.
{
// Cerr << "Stat::~Stat called !!! " << finl;
  delete stat_internals;
  stat_internals = 0;
}
References stat_internals.
Member Function Documentation
allocate_communication_tracking_times()
int Statistiques::allocate_communication_tracking_times ()
Definition at line 995 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  si.communication_tracking_info = new Stat_Results*[si.nb_comm_counters];
  for(int i = 0; i < si.nb_comm_counters; i++)
    si.communication_tracking_info[i] = new Stat_Results[MAXCOUNTERS+1];
  return 0;
}
References Stat_Internals::communication_tracking_info, MAXCOUNTERS, Stat_Internals::nb_comm_counters, and stat_internals.
Referenced by declare_stat_counters().
begin_communication_tracking()
void Statistiques::begin_communication_tracking (int cid)
Definition at line 1020 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  if(!GET_COMM_DETAILS || si.counter_comm[cid] )
    return;
  for (int i = 0; i < si.nb_comm_counters; i++)
    {
// correspondance entre l'indice dans le tableau communication_tracking_times et l'id du compteur associe
      int counter_id = get_counter_id_from_index_in_comm_tracking_info(i);
      Stat_Results& comm_total_time = si.communication_tracking_info[i][0];
      cumulate_stats(counter_id, comm_total_time);
      for (int j = 0; j < si.nb_counters; j++)
        {
// si d'autres zones de communication sont activees,
// on met a jour leurs donnees
          if (si.comm_zones_on[j])
            {
              Stat_Results& comm_time_in_zone_j = si.communication_tracking_info[i][j + 1];
              cumulate_stats(counter_id, comm_time_in_zone_j);
            }
        }
      reset_counter(counter_id);
    }
  si.comm_zones_on[cid] = true;
}
References Stat_Internals::comm_zones_on, Stat_Internals::communication_tracking_info, Stat_Internals::counter_comm, cumulate_stats(), GET_COMM_DETAILS, get_counter_id_from_index_in_comm_tracking_info(), Stat_Internals::nb_comm_counters, Stat_Internals::nb_counters, reset_counter(), and stat_internals.
Referenced by begin_count().
begin_count()
void Statistiques::begin_count (const Stat_Counter_Id & counter_id, bool track_comm = true) inline
Definition at line 212 of file Statistiques.h.
{
  assert(counter_id.initialized());
  if (counter_id.level_ <= debug_level_)
    {
      begin_count_(counter_id.id_);
      if(track_comm) begin_communication_tracking(counter_id.id_);
    }
}
References begin_communication_tracking(), begin_count_(), debug_level_, Stat_Counter_Id::id_, Stat_Counter_Id::initialized(), and Stat_Counter_Id::level_.
Referenced by Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Operateur_Div::ajouter(), Operateur_Grad::ajouter(), Source::ajouter(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), Comm_Group_MPI::all_to_all(), Comm_Group_MPI::all_to_allv(), Equation_base::assembler(), Convection_Diffusion_Temperature::assembler(), Equation_base::assembler_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_mat(), Comm_Group_MPI::barrier(), Comm_Group_MPI::broadcast(), Operateur_Conv::calculer(), Operateur_Diff::calculer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Source::calculer(), Operateur::calculer_pas_de_temps(), call_echange_espace_virtuel(), mon_main::dowork(), Equation_base::Gradient_conjugue_diff_impl(), ICoCo::ProblemTrio::initialize(), Scatter::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Pb_Dilatable_base::iterateTimeStep(), Scatter::lire_domaine(), Comm_Group_MPI::mp_collective_op(), Comm_Group_MPI::mppartial_sum(), Probleme_base::postraiter(), Comm_Group_MPI::ptop_send_recv(), EcrFicPartageMPIIO::put(), Champ_Fonc_reprise::readOn(), Comm_Group_MPI::recv(), Probleme_base::reprendre(), Solv_Petsc::resoudre_systeme(), SolveurPP1B::resoudre_systeme(), SolveurSys::resoudre_systeme(), Probleme_U::run(), Probleme_U::runUntil(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), Comm_Group_MPI::send(), Comm_Group_MPI::send_recv_start(), ICoCo::ProblemTrio::solveTimeStep(), EcrFicPartage::syncfile(), test_un_solveur(), and Schema_Temps_base::validateTimeStep().
begin_count_()
void Statistiques::begin_count_ (const int id_) protected
Definition at line 444 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  assert(id < si.nb_counters);
  if(si.counter_running[id])
    {
      Process::Journal() << "WARNING : counter " << si.description[id]
                         << " has been started while it's already running !" << finl;
      return;
    }
// demarrage des compteurs seulement apres les 3 premieres iterations car elles peuvent fausser les statistiques
// (on demarre le compteur du temps total sans attendre que les 3 premiers pas de temps soient ecoules)
  bool is_temps_total = strcmp(si.description[id], "Temps total") == 0;
  if ( (JUMP_3_FIRST_STEPS && (is_temps_total || three_first_steps_elapsed_ ) )
       || !JUMP_3_FIRST_STEPS)
    {
      si.time_begin[id].get_time();
      si.counter_running[id] = 1;
#ifdef PETSCKSP_H
      Nom info(si.description[id]);
      info+="\n";
      PetscInfo(0,info);
#endif
#ifdef VTRACE
// Level 1 only to avoid MPI calls
      if (si.counter_level[id]==1) VT_USER_START(si.description[id]);
#endif
    }
}
References Stat_Internals::counter_level, Stat_Internals::counter_running, Stat_Internals::description, finl, Time::get_time(), info, Process::Journal(), JUMP_3_FIRST_STEPS, Stat_Internals::nb_counters, stat_internals, three_first_steps_elapsed_, and Stat_Internals::time_begin.
Referenced by begin_count().
compute_avg_min_max_var_per_step()
void Statistiques::compute_avg_min_max_var_per_step (int tstep)
Definition at line 1304 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  int step = JUMP_3_FIRST_STEPS ? tstep - 3 : tstep;
  double counter_time_step;
  for (int i = 0; i < si.nb_counters; i++)
    {
// suivant que l'option GET_COMM_DETAILS est activee ou non,
// les informations de temps des compteurs de communication sont a jour uniquement dans le tableau communication_tracking_times
      if ( (GET_COMM_DETAILS && !si.counter_comm[i]) || !GET_COMM_DETAILS )
        {
          counter_time_step =  si.counter_time[i].second() - si.counters_avg_min_max_var_per_step[i][0]; //temps passe par le compteur i durant l'iteration tstep
          si.counters_avg_min_max_var_per_step[i][0] = si.counter_time[i].second();
        }
      else
        {
          if(si.communication_tracking_info == 0)
            {
              Cerr << "compute_avg_min_max_var_per_step: error ! communication_tracking_times hasn't been allocated yet... (disable the option GET_COMM_DETAILS in file Statistiques.h)" <<finl;
              Process::exit();
            }
// correspondance entre l'identifiant du compteur de communication et son indice dans le tableau communication_tracking_times
          int index = si.index_in_communication_tracking_info[i] ;
          counter_time_step = si.communication_tracking_info[index][0].time - si.counters_avg_min_max_var_per_step[i][0]; //temps passe par le compteur i durant l'iteration tstep
          si.counters_avg_min_max_var_per_step[i][0] = si.communication_tracking_info[index][0].time;
        }
      double old_moy = si.counters_avg_min_max_var_per_step[i][1];
// moyenne courante
      si.counters_avg_min_max_var_per_step[i][1] = ((si.counters_avg_min_max_var_per_step[i][1] * step) + counter_time_step) / (step + 1);
// min courant
      si.counters_avg_min_max_var_per_step[i][2] = std::min(si.counters_avg_min_max_var_per_step[i][2],counter_time_step);
// max courant
      si.counters_avg_min_max_var_per_step[i][3] = std::max(si.counters_avg_min_max_var_per_step[i][3],counter_time_step);
// variance courante
      si.counters_avg_min_max_var_per_step[i][4] = (si.counters_avg_min_max_var_per_step[i][4] + old_moy*old_moy)* step;
      si.counters_avg_min_max_var_per_step[i][4] += counter_time_step*counter_time_step;
      si.counters_avg_min_max_var_per_step[i][4] /= step+1;
      si.counters_avg_min_max_var_per_step[i][4] -= si.counters_avg_min_max_var_per_step[i][1] * si.counters_avg_min_max_var_per_step[i][1];
// avec les erreurs d'arrondis, on peut obtenir une variance negative
      if (si.counters_avg_min_max_var_per_step[i][4] < 0)
        si.counters_avg_min_max_var_per_step[i][4] = 0.0;
    }
}
References Cerr, Stat_Internals::communication_tracking_info, Stat_Internals::counter_comm, Stat_Internals::counter_time, Stat_Internals::counters_avg_min_max_var_per_step, Process::exit(), finl, GET_COMM_DETAILS, Stat_Internals::index_in_communication_tracking_info, JUMP_3_FIRST_STEPS, Stat_Internals::nb_counters, Time::second(), stat_internals, and Stat_Results::time.
Referenced by Probleme_U::run().
cumulate_stats()
void Statistiques::cumulate_stats (int counter_id, Stat_Results & result)
Definition at line 955 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  assert(counter_id < si.nb_counters);
  result.time += si.counter_time[counter_id].second();
  result.count += si.counter_nb[counter_id];
  result.quantity += si.counter_quantity[counter_id];
}
References Stat_Results::count, Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_time, Stat_Internals::nb_counters, Stat_Results::quantity, Time::second(), stat_internals, and Stat_Results::time.
Referenced by begin_communication_tracking(), end_communication_tracking(), and print_communciation_tracking_details().
delete_communication_tracking_times()
int Statistiques::delete_communication_tracking_times ()
Definition at line 1006 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  for(int i = 0; i < si.nb_comm_counters; ++i)
    {
      delete [] si.communication_tracking_info[i];
      si.communication_tracking_info[i] = 0;
    }
  delete [] si.communication_tracking_info;
  si.communication_tracking_info = 0;
  return 0;
}
References Stat_Internals::communication_tracking_info, Stat_Internals::nb_comm_counters, and stat_internals.
Referenced by end_stat_counters().
dump()
void Statistiques::dump (const char * message_info, int mode_append)
< message non nul !
< Update total_time_
Definition at line 623 of file Statistiques.cpp.
{
  assert(message); //!< message non nul !
  Stat_Internals& si = *stat_internals;
  char tampon[BUFLEN+150];
  stop_counters();
  SChaine perfs;
  SChaine perfs_globales;
  if (Process::nproc() > 1)
    {
      perfs.precision(3);
      perfs << "Statistics execution [PE " << Process::me() << "] : " << message << finl;
      perfs << " the time was measured by the following method :" << finl;
      perfs << " " << Time::description << finl;
      sprintf(tampon, "%60s %10s         %10s %10s  %-23s %10s ",
              "Counter (level)", "time(s)", "count", "quantity", "avg time per step", "(min,max,std dev)" );
      perfs << tampon << finl;
    }
  if (Process::je_suis_maitre())
    {
      sprintf(tampon,
              "%60s %10s         %-23s %10s %-23s %10s %-23s %10s %-23s",
              "Counter (level)",
              "avg time", "(min,max)",
              "avg count", "(min,max)",
              "avg qty", "(min,max)",
              "avg time per step", "(std dev)");
      perfs_globales << "Statistics overall execution : " << message << finl;
      perfs_globales << " the time was measured by the following method :" << finl;
      perfs_globales << " " << Time::description << finl;
      perfs_globales << tampon << finl;
    }
// Verification : on a le meme nombre de compteurs sur tous les procs ?
  int skip_globals = 0;
  {
    int min_nb = (int) Process::mp_min(si.nb_counters);
    int max_nb = (int) Process::mp_max(si.nb_counters);
    if (min_nb != max_nb)
      {
        if (Process::je_suis_maitre())
          {
            perfs_globales << "Unable to collect statistics :" << finl
                           << " there is not the same number of counters on all"
                           " processors.";
          }
        skip_globals = 1;
      }
  }
// Temps de reference pour les pourcentages
  double temps_total_max = 0.;
// Compute Divers (time not counted by other counters in time step loop):
  if (si.counter_nb[2]>0)
    {
      if (strcmp(si.description[2],"Resoudre (timestep loop)"))
        {
          Cerr << "Error in Statistiques::dump(...)" << finl;
          Process::exit();
        }
      int id=-1;
// Look for counter Divers
      for (int i = 0; i < si.nb_counters; i++)
        if (!strcmp(si.description[i],"Divers"))
          id=i;
// Compute CPU Divers = counter(time step) - sum(other counters))
      si.counter_time[id].add(si.counter_time[2]);
      for (int i = 3; i < si.nb_counters; i++)
        {
          if (i!=id && si.counter_level[i]==1)
            si.counter_time[id].minus(si.counter_time[i]);
        }
    }
// Affichage des compteurs individuels
  for (int i = 0; i < si.nb_counters; i++)
    {
      char description[BUFLEN];
      if (si.family[i])
        sprintf(description, "%s:%s", si.family[i], si.description[i]);
      else
        sprintf(description, "%s", si.description[i]);
      double time;
      double nb;
      double quantity;
// si l'option GET_COMM_DETAILS est activee, les infos des compteurs de communication dans les stat_internals ne sont plus a jour
// elles sont neanmoins stockees dans le tableau communication_tracking_times
      if(GET_COMM_DETAILS && si.counter_comm[i] && si.communication_tracking_info )
        {
// correspondance entre l'identifiant du compteur de communication et son indice dans le tableau communication_tracking_times
          int index =  si.index_in_communication_tracking_info[i];
          time = si.communication_tracking_info[index][0].time;
          nb = si.communication_tracking_info[index][0].count;
          quantity = si.communication_tracking_info[index][0].quantity;
        }
      else
        {
          time = si.counter_time[i].second();
          nb = si.counter_nb[i];
          quantity = si.counter_quantity[i];
        }
      int level = si.counter_level[i];
      double avg_time_per_step = si.counters_avg_min_max_var_per_step[i][1];
      double min_time_per_step = si.counters_avg_min_max_var_per_step[i][2];
      double max_time_per_step = si.counters_avg_min_max_var_per_step[i][3];
      double var_time_per_step = si.counters_avg_min_max_var_per_step[i][4];
      if (i == 0)
        {
          temps_total_max = time;
          total_time_+=time;     //!< Update total_time_
        }
      if( JUMP_3_FIRST_STEPS && i == 2 )
        temps_total_max = time;
      assert(var_time_per_step >= 0.);
      print_stat(perfs,perfs_globales,description,
                 level,time,nb,quantity,temps_total_max, skip_globals,
                 avg_time_per_step, min_time_per_step, max_time_per_step, sqrt(var_time_per_step));
    }
// Affichage par famille de compteur
  int * drapeaux = new int[si.nb_counters];
  for (int i = 0; i < si.nb_counters; i++)
    drapeaux[i] = 0;
  int next = 0;
// Next designe le premier compteur d'une famille en cours
  while (next < si.nb_counters)
    {
      int level = 0;
      double time = 0.;
      double nb = 0.;
      double quantity = 0.;
      double avg_time_per_step = 0.;
      double min_time_per_step = 0.;
      double max_time_per_step = 0.;
      double var_time_per_step = 0.;
// Trouve le premier compteur de la famille suivante
// (famille non nulle et pas encore traitee)
      while (next < si.nb_counters
             && (si.family[next] == 0 || drapeaux[next] != 0))
        next++;
      if (next >= si.nb_counters)
        break;
// Somme des valeurs des compteurs de cette famille
      for (int i = next; i < si.nb_counters; i++)
        {
          if (si.family[i] != 0)
            {
              if (strcmp(si.family[i], si.family[next]) == 0)
                {
// OK, on veut compter celui-la
                  drapeaux[i] = 1;
// si l'option GET_COMM_DETAILS est activee, les infos des compteurs de communication dans les stat_internals ne sont plus a jour
// elles sont neanmoins stockees dans le tableau communication_tracking_times
                  if(GET_COMM_DETAILS && si.counter_comm[i] && si.communication_tracking_info )
                    {
// correspondance entre l'identifiant du compteur de communication et son indice dans le tableau communication_tracking_times
                      int index = si.index_in_communication_tracking_info[i];
                      time += si.communication_tracking_info[index][0].time;
                      nb   += si.communication_tracking_info[index][0].count;
                      quantity += si.communication_tracking_info[index][0].quantity;
                    }
                  else
                    {
                      time += si.counter_time[i].second();
                      nb += si.counter_nb[i];
                      quantity += si.counter_quantity[i];
                    }
                  avg_time_per_step += si.counters_avg_min_max_var_per_step[i][1];
                  var_time_per_step += si.counters_avg_min_max_var_per_step[i][4];
                }
            }
        }
      const char * description = si.family[next];
      assert(var_time_per_step >= 0.);
      print_stat(perfs,perfs_globales,description,
                 level,time,nb,quantity,temps_total_max, skip_globals,
                 avg_time_per_step, min_time_per_step, max_time_per_step, sqrt(var_time_per_step));
      next++;
    }
  delete[] drapeaux;
  if (Process::nproc() > 1)
    perfs << finl;
  if (Process::je_suis_maitre())
    perfs_globales << finl;
// Les fichiers sont ouverts en mode append.
  {
    Nom TU(Objet_U::nom_du_cas());
    TU+="_detail.TU";
    EcrFicPartage file(TU, mode_append ? (ios::out | ios::app) : (ios::out));
    if (Process::je_suis_maitre())
      file << perfs_globales.get_str();
    file << perfs.get_str();
    file.syncfile();
  }
  restart_counters();
}
References Time::add(), BUFLEN, Cerr, Stat_Internals::communication_tracking_info, Stat_Results::count, Stat_Internals::counter_comm, Stat_Internals::counter_level, Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_time, Stat_Internals::counters_avg_min_max_var_per_step, Time::description, Stat_Internals::description, Process::exit(), Stat_Internals::family, finl, GET_COMM_DETAILS, SChaine::get_str(), Stat_Internals::index_in_communication_tracking_info, Process::je_suis_maitre(), JUMP_3_FIRST_STEPS, Process::me(), message(), Time::minus(), Process::mp_max(), Process::mp_min(), Stat_Internals::nb_counters, next(), Objet_U::nom_du_cas(), Process::nproc(), Sortie::precision(), print_stat(), Stat_Results::quantity, restart_counters(), Time::second(), stat_internals, stop_counters(), EcrFicPartage::syncfile(), Stat_Results::time, and total_time_.
Referenced by mon_main::dowork(), ICoCo::ProblemTrio::initialize(), Probleme_U::run(), and ICoCo::ProblemTrio::terminate().
end_communication_tracking()
void Statistiques::end_communication_tracking (int cid)
Definition at line 1052 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  if(!GET_COMM_DETAILS || si.counter_comm[cid] )
    return;
  assert(cid >=0);
  if (si.comm_zones_on[cid] == false)
    {
      Process::Journal() << "Error! end_communication_tracking (" << si.description[cid] << ") has not been activated" <<finl;
      return;
    }
  for (int i = 0; i < si.nb_comm_counters; i++)
    {
// correspondance entre l'indice dans le tableau communication_tracking_times et l'id du compteur associe
      int counter_id = get_counter_id_from_index_in_comm_tracking_info(i);
      Stat_Results& comm_time_in_zone_cid = si.communication_tracking_info[i][cid + 1];
      cumulate_stats(counter_id, comm_time_in_zone_cid);
    }
  si.comm_zones_on[cid] = false;
}
References Stat_Internals::comm_zones_on, Stat_Internals::communication_tracking_info, Stat_Internals::counter_comm, cumulate_stats(), Stat_Internals::description, finl, GET_COMM_DETAILS, get_counter_id_from_index_in_comm_tracking_info(), Process::Journal(), Stat_Internals::nb_comm_counters, and stat_internals.
Referenced by end_count().
end_count()
void Statistiques::end_count (const Stat_Counter_Id & counter_id, int quantity = 0, int count = 1, bool track_comm = true) inline
Arret du compteur counter_id. On ajoute quantity a la somme des
'quantity' (par defaut 0) stockees pour ce compteur
et on ajoute 'count' (par defaut 1) au compteur d'appels a end_count pour ce compteur<br>(quantity sert a sommer par exemple la taille des donnees traitees pendant ce comptage<br>et count sert a compter combien de fois on a appele ce compteur)
Definition at line 230 of file Statistiques.h.
{
  assert(counter_id.initialized());
  if (counter_id.level_ <= debug_level_)
    {
      end_count_(counter_id.id_, quantity, count);
      if(track_comm) end_communication_tracking(counter_id.id_);
    }
}
References debug_level_, end_communication_tracking(), end_count_(), Stat_Counter_Id::id_, Stat_Counter_Id::initialized(), and Stat_Counter_Id::level_.
Referenced by Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Operateur_Div::ajouter(), Operateur_Grad::ajouter(), Source::ajouter(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Conv_VDF_base::ajouter_blocs(), Comm_Group_MPI::all_to_all(), Comm_Group_MPI::all_to_allv(), Equation_base::assembler(), Convection_Diffusion_Temperature::assembler(), Equation_base::assembler_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_mat(), Comm_Group_MPI::barrier(), Comm_Group_MPI::broadcast(), Operateur_Conv::calculer(), Operateur_Diff::calculer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Source::calculer(), Operateur::calculer_pas_de_temps(), call_echange_espace_virtuel(), Equation_base::Gradient_conjugue_diff_impl(), Scatter::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Pb_Dilatable_base::iterateTimeStep(), Scatter::lire_domaine(), Comm_Group_MPI::mp_collective_op(), Comm_Group_MPI::mppartial_sum(), Probleme_base::postraiter(), Comm_Group_MPI::ptop_send_recv(), EcrFicPartageMPIIO::put(), Champ_Fonc_reprise::readOn(), Comm_Group_MPI::recv(), Probleme_base::reprendre(), Solv_Petsc::resoudre_systeme(), SolveurPP1B::resoudre_systeme(), SolveurSys::resoudre_systeme(), Probleme_U::run(), Probleme_U::runUntil(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), Comm_Group_MPI::send(), Comm_Group_MPI::send_recv_finish(), EcrFicPartage::syncfile(), test_un_solveur(), Schema_Temps_base::validateTimeStep(), and ICoCo::ProblemTrio::validateTimeStep().
end_count_()
void Statistiques::end_count_ (const int id_, int quantity, int count) protected
Definition at line 478 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  assert(id < si.nb_counters);
// arret des compteurs seulement apres les 3 premieres iterations (car on les demarre seulement apres 3 iterations)
  bool is_temps_total = strcmp(si.description[id], "Temps total") == 0;
  if ( (JUMP_3_FIRST_STEPS && (is_temps_total || three_first_steps_elapsed_ ) )
       || !JUMP_3_FIRST_STEPS)
    {
      if (si.counter_running[id])
        {
          Time time_end;
          time_end.get_time();
          si.counter_time[id].add_time(si.time_begin[id], time_end);
          si.counter_running[id] = 0;
          si.counter_nb[id] += count;
          si.counter_quantity[id] += quantity;
#ifdef VTRACE
// Level 1 only to avoid MPI calls
          if (si.counter_level[id]==1) VT_USER_END(si.description[id]);
#endif
        }
    }
}
References Time::add_time(), Stat_Internals::counter_level, Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_running, Stat_Internals::counter_time, Stat_Internals::description, Time::get_time(), JUMP_3_FIRST_STEPS, Stat_Internals::nb_counters, stat_internals, three_first_steps_elapsed_, and Stat_Internals::time_begin.
Referenced by end_count(), and stop_counters().
get_communication_tracking_info()
Stat_Results Statistiques::get_communication_tracking_info (int i, int j) const
Definition at line 1367 of file Statistiques.cpp.
{
  return ( stat_internals -> communication_tracking_info[i][j]);
}
References stat_internals.
Referenced by print_statistics_analyse().
get_counter_family()
const char * Statistiques::get_counter_family (int id)
Definition at line 1357 of file Statistiques.cpp.
{
  return ( stat_internals -> family[id]);
}
References stat_internals.
Referenced by print_statistics_analyse().
get_counter_id_from_description()
int Statistiques::get_counter_id_from_description (const char * desc) const
Definition at line 991 of file Statistiques.cpp.
{
  return ( stat_internals -> description_to_id[desc] );
}
References stat_internals.
Referenced by print_statistics_analyse().
get_counter_id_from_index_in_comm_tracking_info()
int Statistiques::get_counter_id_from_index_in_comm_tracking_info (int index) const
Definition at line 967 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  int counter_id = -1;
  for (int i = 0; i < si.nb_counters; i++)
    if ( si.index_in_communication_tracking_info[i] == index )
      counter_id=i;
  if(counter_id == -1)
    {
      Cerr << "Statistiques::get_counter_id_from_index_in_comm_tracking_info() : error! The provided index does not correspond to any counter..." << finl;
      Process::exit();
    }
  return counter_id;
}
References Cerr, Process::exit(), finl, Stat_Internals::index_in_communication_tracking_info, Stat_Internals::nb_counters, and stat_internals.
Referenced by begin_communication_tracking(), end_communication_tracking(), print_communciation_tracking_details(), and print_statistics_analyse().
get_index_in_comm_tracking_info_from_counter_id()
int Statistiques::get_index_in_comm_tracking_info_from_counter_id (int id) const
Definition at line 985 of file Statistiques.cpp.
{
  return ( stat_internals->index_in_communication_tracking_info[id] );
}
References Stat_Internals::index_in_communication_tracking_info, and stat_internals.
Referenced by print_statistics_analyse().
get_nb_comm_counters()
int Statistiques::get_nb_comm_counters () const
Definition at line 1362 of file Statistiques.cpp.
{
  return ( stat_internals -> nb_comm_counters);
}
References stat_internals.
Referenced by print_statistics_analyse().
get_stats()
void Statistiques::get_stats (const Stat_Counter_Id & counter_id, Stat_Results & result)
Definition at line 919 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  int id = counter_id.id_;
  assert(id < si.nb_counters);
  result.time = si.counter_time[id].second();
  result.count = si.counter_nb[id];
  result.quantity = si.counter_quantity[id];
  result.compute_min_max_avg();
}
References Stat_Results::compute_min_max_avg(), Stat_Results::count, Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_time, Stat_Counter_Id::id_, Stat_Internals::nb_counters, Stat_Results::quantity, Time::second(), stat_internals, and Stat_Results::time.
Referenced by print_statistics_analyse(), and test_un_solveur().
get_stats_familly()
void Statistiques::get_stats_familly (const char * familly, Stat_Results & result)
Definition at line 931 of file Statistiques.cpp.
{
  assert(familly);
  Stat_Internals& si = *stat_internals;
  result.time = 0.;
  result.count = 0.;
  result.quantity = 0.;
  int i;
  for (i = 0; i < si.nb_counters; i++)
    {
      if (si.family[i] != 0)
        {
          if (strcmp(si.family[i], familly) == 0)
            {
              result.time += si.counter_time[i].second();
              result.count += si.counter_nb[i];
              result.quantity += si.counter_quantity[i];
            }
        }
    }
  result.compute_min_max_avg();
}
References Stat_Results::compute_min_max_avg(), Stat_Results::count, Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_time, Stat_Internals::family, Stat_Internals::nb_counters, Stat_Results::quantity, Time::second(), stat_internals, and Stat_Results::time.
Referenced by print_statistics_analyse().
get_time_now()
double Statistiques::get_time_now () static
Cette methode renvoie un temps en secondes depuis une origine
qui depend de la methode de mesure de la classe Time. Precision, normalement
de l'ordre de 1ms ou inferieur.
Definition at line 242 of file Statistiques.cpp.
{
  Time t;
  t.get_time();
  return t.second();
}
References Time::get_time(), and Time::second().
Referenced by estimate_allreduce(), and Solv_Petsc::resoudre_systeme().
get_total_time()
double Statistiques::get_total_time () inline
Definition at line 88 of file Statistiques.h.
  {
    return total_time_;
  };
References total_time_.
Referenced by mon_main::dowork().
last_time()
double Statistiques::last_time (const Stat_Counter_Id & counter_id)
Definition at line 509 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  if (si.counter_running[counter_id.id_])
    {
      Time time_begin(si.time_begin[counter_id.id_]);
      Time time_end;
      time_end.get_time();
      Time delta;
      delta.add_time(time_begin, time_end);
      return delta.second();
    }
  else
    {
      return si.time_begin[counter_id.id_].second();
    }
}
References Time::add_time(), Stat_Internals::counter_running, Time::get_time(), Stat_Counter_Id::id_, Time::second(), stat_internals, and Stat_Internals::time_begin.
Referenced by Assembleur_P_PolyMAC::assembler_mat(), Scatter::interpreter(), Schema_Temps_base::mettre_a_jour(), Champ_Fonc_reprise::readOn(), Probleme_base::reprendre(), SolveurSys::resoudre_systeme(), Probleme_U::run(), Probleme_U::runUntil(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), and Schema_Temps_base::validateTimeStep().
new_counter()
Stat_Counter_Id Statistiques::new_counter (int level, const char *const description, const char *const familly = 0, int comm = 0)
< Pointeur non nul ?
Definition at line 396 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  assert(description); //!< Pointeur non nul ?
  if (si.nb_counters >= MAXCOUNTERS)
    {
      Cerr << "Stat_Counter_Id::new_counter : too much counters." << finl;
      Cerr << " Check this : new_counter must be called only once per counter." << finl;
      Cerr << " (counter " << description << ")" << finl;
      Cerr << " Otherwise, increase MAXCOUNTERS in Statistiques.cpp." << finl;
      assert(0);
      Process::exit();
    }
  int length = strlen(description);
  if (family) length += strlen(family);
  if (length > BUFLEN - 10)
    {
      Cerr << "Statistiques::new_counter : description or family : string too long"
           << finl;
      Cerr << description << finl;
      assert(0);
      Process::exit();
    }
  if (level < 1)
    level = 1;
  const int id = si.nb_counters;
  Stat_Counter_Id new_id(id, level);
  si.counter_level[id] = level;
  si.description[id] = description;
  si.family[id] = family;
  si.nb_counters++;
  si.description_to_id[description] = id;
  si.counter_comm[id] = comm;
  if (comm)
    {
      si.index_in_communication_tracking_info[id] = si.nb_comm_counters;
      si.nb_comm_counters++;
    }
  return new_id;
}
References BUFLEN, Cerr, comm, Stat_Internals::counter_comm, Stat_Internals::counter_level, Stat_Internals::description, Stat_Internals::description_to_id, Process::exit(), Stat_Internals::family, finl, Stat_Internals::index_in_communication_tracking_info, MAXCOUNTERS, Stat_Internals::nb_comm_counters, Stat_Internals::nb_counters, and stat_internals.
Referenced by declare_stat_counters(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), and test_un_solveur().
print_communciation_tracking_details()
void Statistiques::print_communciation_tracking_details (const char * message, int mode_append)
< message non nul !
Definition at line 1080 of file Statistiques.cpp.
{
  assert(message); //!< message non nul !
  Stat_Internals& si = *stat_internals;
  stop_counters();
// on recupere les donnees de communication produites depuis la derniere remise a zero
  for (int i = 0; i < si.nb_comm_counters; i++)
    {
// correspondance entre l'indice dans le tableau communication_tracking_times et l'id du compteur associe
      int counter_id = get_counter_id_from_index_in_comm_tracking_info(i);
      Stat_Results& comm_total_time = si.communication_tracking_info[i][0];
      cumulate_stats(counter_id, comm_total_time);
    }
  SChaine comm;
  char desc[BUFLEN+100];
  comm << "*************************************************************************************************" << finl;
  comm << message << finl;
  comm << "Block divided into 2 parts:" << finl;
  comm << "Part 1: for each function, gives the percentage consumed by communications" << finl;
  comm << "Part 2: for each type of communication, gives the percentage of time spent in each function" << finl;
  comm << "        Note that some counters are nested within each other, " << finl;
  comm << "        that's why the sum of the percentages does not necessarily add up to 100% in this part." << finl;
  comm << "*************************************************************************************************" << finl;
  comm << finl;
// parcours des zones de communication
// on laisse tomber temps total
  for (int i = 1; i < si.nb_counters; i++)
    {
      double tot_communication_in_zone_i = 0;
      for(int j = 0; j < si.nb_comm_counters; j++)
        {
// on ne compte pas echange_espace_vectoriel (redondant avec send_recv)
          int counter_id = get_counter_id_from_index_in_comm_tracking_info(j);
          if( strcmp(si.description[counter_id], "DoubleVect/IntVect::echange_espace_virtuel") )
            tot_communication_in_zone_i += si.communication_tracking_info[j][i+1].time;
        }
      double tot_avg_communication_in_zone_i = Process::mp_sum(tot_communication_in_zone_i);
      tot_avg_communication_in_zone_i /= Process::nproc();
      double tot_time_in_zone_i = si.counter_time[i].second();
      int comm_pourcent = tot_time_in_zone_i != 0.0 ? tot_communication_in_zone_i / tot_time_in_zone_i * 100 : 0.0;
      int avg_comm_pourcent = Process::mp_sum(comm_pourcent) / Process::nproc();
      if (tot_avg_communication_in_zone_i)
        {
          comm << si.description[i] << " : " << tot_avg_communication_in_zone_i << "s de communications (soit ";
          comm << avg_comm_pourcent << "% du temps total consomme par ce compteur)\n";
          for(int j = 0; j < si.nb_comm_counters; j++)
            {
// on ne compte pas echange_espace_vectoriel
              int counter_id = get_counter_id_from_index_in_comm_tracking_info(j);
              if( strcmp(si.description[counter_id], "DoubleVect/IntVect::echange_espace_virtuel") )
                {
                  Stat_Results& communication_of_type_j = si.communication_tracking_info[j][i+1];
                  double avg_communication_of_type_j = Process::mp_sum(communication_of_type_j.time);
                  avg_communication_of_type_j /= Process::nproc();
                  int communication_type_pourcentage = tot_communication_in_zone_i != 0.0 ? communication_of_type_j.time / tot_communication_in_zone_i * 100 : 0.0;
                  int avg_communication_type_pourcentage = Process::mp_sum(communication_type_pourcentage);
                  avg_communication_type_pourcentage /= Process::nproc();
                  if(avg_communication_of_type_j)
                    {
#ifdef INT_is_64_
                      sprintf(desc, "%10s %-25s %.2e s (%2li%%)\n", "\tdont", si.description[counter_id], avg_communication_of_type_j,avg_communication_type_pourcentage);
#else
                      sprintf(desc, "%10s %-25s %.2e s (%2i%%)\n", "\tdont", si.description[counter_id], avg_communication_of_type_j,avg_communication_type_pourcentage);
#endif
                      comm << desc;
                    }
                }
            }
          comm << "\n";
        }
    }
  double* send_recv_family = (double *)calloc(si.nb_counters+1, sizeof(double));
  double* all_reduce_family = (double *)calloc(si.nb_counters+1, sizeof(double));
// parcours des compteurs de communication
  for(int i = 0; i < si.nb_comm_counters; i++)
    {
      int counter_id = get_counter_id_from_index_in_comm_tracking_info(i);
      double total_time_of_communication_i = si.communication_tracking_info[i][0].time;
      double total_avg_time_of_communication_i = Process::mp_sum(total_time_of_communication_i);
      total_avg_time_of_communication_i /= Process::nproc();
      if(total_avg_time_of_communication_i == 0.0) continue;
      comm
          << "\n-----------------------------------------------------------------"
          << "\n";
      comm
          <<                        si.description[counter_id]
          << "\n";
      comm
          << "-----------------------------------------------------------------"
          << "\n";
      comm << "Temps total : " << total_avg_time_of_communication_i << "s\n";
      if( si.family[counter_id] != 0 )
        {
          if( !strcmp(si.family[counter_id], "MPI_allreduce" ) )
            all_reduce_family[0] += total_time_of_communication_i;
          else if ( !strcmp(si.family[counter_id], "MPI_sendrecv" ) )
            send_recv_family[0] += total_time_of_communication_i;
        }
// first counter is "Temps total", we can skip it
      for (int j = 1; j < si.nb_counters; j++)
        {
          double communication_in_zone_j = si.communication_tracking_info[i][j+1].time;
          double avg_communication_in_zone_j = Process::mp_sum(communication_in_zone_j);
          avg_communication_in_zone_j /= Process::nproc();
          int pourcentage = total_time_of_communication_i != 0.0 ? communication_in_zone_j / total_time_of_communication_i * 100 : 0.0;
          int avg_pourcentage = Process::mp_sum(pourcentage);
          avg_pourcentage /= Process::nproc();
          if(avg_pourcentage)
            comm << "\tdont " << si.description[j] << " : " << avg_communication_in_zone_j << "s (" << avg_pourcentage << "%) \n";
          if (si.family[counter_id] != 0)
            {
              if( !strcmp(si.family[counter_id], "MPI_allreduce" ) )
                all_reduce_family[j+1] += communication_in_zone_j;
              else if ( !strcmp(si.family[counter_id], "MPI_sendrecv" ) )
                send_recv_family[j+1] += communication_in_zone_j;
            }
        }
    }
  comm << finl;
// affichage des informations sur les familles de commpteurs
  comm
      << "\n-----------------------------------------------------------------"
      << "\n";
  comm
      << "                    Famille MPI_allreduce                         "
      << "\n";
  comm
      << "-----------------------------------------------------------------"
      << "\n";
  double tot_avg_all_reduce = Process::mp_sum(all_reduce_family[0]);
  tot_avg_all_reduce /= Process::nproc();
  comm << "Temps total : " << tot_avg_all_reduce << "s\n";
  for (int i = 1; i < si.nb_counters; i++)
    {
      double avg_all_reduce_in_zone_i = Process::mp_sum(all_reduce_family[i]);
      avg_all_reduce_in_zone_i /= Process::nproc();
      int pourcentage = all_reduce_family[0] != 0.0 ? all_reduce_family[i] / all_reduce_family[0] * 100 : 0.0;
      int avg_pourcentage = Process::mp_sum(pourcentage);
      avg_pourcentage /= Process::nproc();
      if(avg_pourcentage)
        comm << "\tdont " << si.description[i-1] << " : " << avg_all_reduce_in_zone_i << "s (" << avg_pourcentage << "%) \n";
    }
  comm
      << "\n-----------------------------------------------------------------"
      << "\n";
  comm
      << "                    Famille MPI_sendrecv                           "
      << "\n";
  comm
      << "-----------------------------------------------------------------"
      << "\n";
  double tot_avg_send_recv = Process::mp_sum(send_recv_family[0]);
  tot_avg_send_recv /= Process::nproc();
  comm << "Temps total : " << tot_avg_send_recv << "s\n";
  for (int i = 1; i < si.nb_counters; i++)
    {
      double avg_send_recv_in_zone_i = Process::mp_sum(send_recv_family[i]);
      avg_send_recv_in_zone_i /= Process::nproc();
      int pourcentage = send_recv_family[0] != 0.0 ? send_recv_family[i] / send_recv_family[0] * 100 : 0.0;
      int avg_pourcentage = Process::mp_sum(pourcentage);
      avg_pourcentage /= Process::nproc();
      if(avg_pourcentage)
        comm << "\tdont " << si.description[i-1] << " : " << avg_send_recv_in_zone_i << "s (" << avg_pourcentage << "%) \n";
    }
  comm << "\n\n";
  free(send_recv_family);
  free(all_reduce_family);
  if (Process::je_suis_maitre())
    {
      Nom TU(Objet_U::nom_du_cas());
      TU += "_comm.TU";
      SFichier comm_file(TU, mode_append ? (ios::out | ios::app) : (ios::out));
      comm_file << comm.get_str();
    }
  restart_counters();
}
References BUFLEN, comm, Stat_Internals::communication_tracking_info, Stat_Internals::counter_time, cumulate_stats(), Stat_Internals::description, Stat_Internals::family, finl, get_counter_id_from_index_in_comm_tracking_info(), Process::je_suis_maitre(), message(), Process::mp_sum(), Stat_Internals::nb_comm_counters, Stat_Internals::nb_counters, Objet_U::nom_du_cas(), Process::nproc(), restart_counters(), Time::second(), stat_internals, stop_counters(), and Stat_Results::time.
Referenced by mon_main::dowork(), and Probleme_U::run().
reset_counter()
void Statistiques::reset_counter (int counter_id)
Definition at line 878 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  Time time_zero;
  si.time_begin[counter_id] = time_zero;
  si.counter_time[counter_id] = time_zero;
  si.counter_running[counter_id] = 0;
  si.counter_nb[counter_id] = 0;
  si.counter_quantity[counter_id] = 0;
}
References Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_running, Stat_Internals::counter_time, stat_internals, and Stat_Internals::time_begin.
Referenced by begin_communication_tracking().
reset_counters()
void Statistiques::reset_counters ()
Definition at line 854 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  Time time_zero;
  for (int i = 0; i < MAXCOUNTERS; i++)
    {
      si.time_begin[i] = time_zero;
      si.counter_time[i] = time_zero;
      si.counter_running[i] = 0;
      si.counter_nb[i] = 0;
      si.counter_quantity[i] = 0;
      for(int j = 0; j < 5; j++)
        {
          si.counters_avg_min_max_var_per_step[i][j] = j==2 ? INITIAL_MIN : 0.0;   //l'indice 2 correspond au min courant
        }
    }
  for (int i = 0; i < si.nb_comm_counters; i++)
    for (int j = 0; j < MAXCOUNTERS; j++)
      si.communication_tracking_info[i][j].reset();
}
References Stat_Internals::communication_tracking_info, Stat_Internals::counter_nb, Stat_Internals::counter_quantity, Stat_Internals::counter_running, Stat_Internals::counter_time, Stat_Internals::counters_avg_min_max_var_per_step, INITIAL_MIN, MAXCOUNTERS, Stat_Internals::nb_comm_counters, Stat_Results::reset(), stat_internals, and Stat_Internals::time_begin.
Referenced by ICoCo::ProblemTrio::initialize(), and Probleme_U::run().
restart_counters()
void Statistiques::restart_counters ()
Definition at line 908 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  assert(si.change_level_forbidden == 1);
// Reactiver les compteurs
  debug_level_ = si.debug_level_before;
  si.change_level_forbidden = 0;
}
References Stat_Internals::change_level_forbidden, debug_level_, Stat_Internals::debug_level_before, and stat_internals.
Referenced by dump(), print_communciation_tracking_details(), and print_statistics_analyse().
set_debug_level()
void Statistiques::set_debug_level (int level)
Definition at line 380 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
// Lors de l'impression des stats, on bloque les compteurs.
// Le niveau est mis a zero, et
// on n'a pas le droit de changer de niveau.
  if (si.change_level_forbidden)
    return;
  debug_level_ = level;
  if (level > si.max_debug_level_during_session)
    si.max_debug_level_during_session = level;
}
References Stat_Internals::change_level_forbidden, debug_level_, Stat_Internals::max_debug_level_during_session, and stat_internals.
Referenced by declare_stat_counters().
set_three_first_steps_elapsed()
void Statistiques::set_three_first_steps_elapsed (bool b) inline
Definition at line 132 of file Statistiques.h.
  {
    three_first_steps_elapsed_ = b;
  }
References three_first_steps_elapsed_.
Referenced by Probleme_U::run().
stop_counters()
void Statistiques::stop_counters ()
Definition at line 893 of file Statistiques.cpp.
{
  Stat_Internals& si = *stat_internals;
  assert(si.change_level_forbidden == 0);
// Bloquer tous les compteurs pendant le dump (on fait appel a des communications)
  si.change_level_forbidden = 1;
  si.debug_level_before = debug_level_;
  debug_level_ = 0;
  int i;
// Arret de tous les compteurs
  for (i = 0; i < si.nb_counters; i++)
    if (si.counter_running[i])
      end_count_(i, 0, 0);
}
References Stat_Internals::change_level_forbidden, Stat_Internals::counter_running, debug_level_, Stat_Internals::debug_level_before, end_count_(), Stat_Internals::nb_counters, and stat_internals.
Referenced by dump(), print_communciation_tracking_details(), and print_statistics_analyse().
Member Data Documentation
debug_level_
int Statistiques::debug_level_ protected
Definition at line 144 of file Statistiques.h.
Referenced by begin_count(), end_count(), restart_counters(), set_debug_level(), Statistiques(), and stop_counters().
stat_internals
Stat_Internals* Statistiques::stat_internals protected
Definition at line 145 of file Statistiques.h.
Referenced by allocate_communication_tracking_times(), begin_communication_tracking(), begin_count_(), compute_avg_min_max_var_per_step(), cumulate_stats(), delete_communication_tracking_times(), dump(), end_communication_tracking(), end_count_(), get_communication_tracking_info(), get_counter_family(), get_counter_id_from_description(), get_counter_id_from_index_in_comm_tracking_info(), get_index_in_comm_tracking_info_from_counter_id(), get_nb_comm_counters(), get_stats(), get_stats_familly(), last_time(), new_counter(), print_communciation_tracking_details(), reset_counter(), reset_counters(), restart_counters(), set_debug_level(), Statistiques(), stop_counters(), and ~Statistiques().
three_first_steps_elapsed_
bool Statistiques::three_first_steps_elapsed_ protected
Definition at line 147 of file Statistiques.h.
Referenced by begin_count_(), end_count_(), set_three_first_steps_elapsed(), and Statistiques().
total_time_
double Statistiques::total_time_ protected
Definition at line 146 of file Statistiques.h.
Referenced by dump(), get_total_time(), and Statistiques().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Statistiques.h
src/Kernel/Utilitaires/Statistiques.cpp