TRUST: Sondes_Int Class Reference
Sondes_Int Class Reference
classe Sondes_Int
Cette classe represente une liste d'objets de type Sonde_Int.
#include <Sondes_Int.h>
Public Member Functions
Sondes_Int ()
~Sondes_Int ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void ouvrir_fichiers ()
Ouvre tous les fichiers associes a chacune des sondes
de la liste.
void fermer_fichiers ()
Ferme tous les fichiers des sondes de la liste.
void associer_post (const Postraitement &)
Associe un postraitement a la liste des sondes.
void postraiter (double)
Effectue le postraitement sur chacune des sondes de
la liste.
void mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune
des sondes de la liste.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Sondes_Int & self_cast (Objet_U &)
static const Sondes_Int & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
Lit une liste de sondes a partir d'un flot d'entree
Format: { [LIRE UNE SONDE AUTANT DE FOIS QUE NECESSAIRE] }.
Private Attributes
Ref_Postraitement mon_post
Detailed Description
classe Sondes_Int
Cette classe represente une liste d'objets de type Sonde_Int.
Definition at line 40 of file Sondes_Int.h.
Constructor & Destructor Documentation
Sondes_Int::Sondes_Int ()
Definition at line 27 of file Sondes_Int.cpp.
Sondes_Int::~Sondes_Int ()
Definition at line 27 of file Sondes_Int.cpp.
Member Function Documentation
void Sondes_Int::associer_post (const Postraitement & post)
Associe un postraitement a la liste des sondes.
Definition at line 174 of file Sondes_Int.cpp.
References mon_post.
Referenced by Postraitement::lire_motcle_non_standard().
{
  mon_post = post;
}
Objet_U * Sondes_Int::cree_instance () [static]
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
int Sondes_Int::duplique () const [virtual]
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
void Sondes_Int::fermer_fichiers () [inline]
Ferme tous les fichiers des sondes de la liste.
Definition at line 99 of file Sondes_Int.h.
References LIST_CURSEUR.
{
  LIST_CURSEUR(Sonde_Int) curseur=*this;
  while(curseur)
    {
      curseur->fermer_fichier();
      ++curseur;
    }
}
const Type_info * Sondes_Int::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
const Type_info * Sondes_Int::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
void Sondes_Int::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune
des sondes de la liste.
Definition at line 149 of file Sondes_Int.cpp.
References LIST_CURSEUR.
{
  LIST_CURSEUR(Sonde_Int) curseur=*this;
  while(curseur)
    {
      curseur->mettre_a_jour(temps,tinit);
      ++curseur;
    }
}
void Sondes_Int::ouvrir_fichiers () [inline]
Ouvre tous les fichiers associes a chacune des sondes
de la liste.
Definition at line 74 of file Sondes_Int.h.
References LIST_CURSEUR.
Referenced by Postraitement::lire_motcle_non_standard().
{
  LIST_CURSEUR(Sonde_Int) curseur=*this;
  while(curseur)
    {
      curseur->ouvrir_fichier();
      ++curseur;
    }
}
void Sondes_Int::postraiter (double temps)
Effectue le postraitement sur chacune des sondes de
la liste.
Definition at line 118 of file Sondes_Int.cpp.
References LIST_CURSEUR.
Referenced by Postraitement::postraiter_sondes().
{
  LIST_CURSEUR(Sonde_Int) curseur=*this;
  while(curseur)
    {
      curseur->postraiter(temps);
      ++curseur;
    }
}
Sortie & Sondes_Int::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from List_Sonde_Int.
Definition at line 97 of file Sondes_Int.cpp.
{
  return s ;
}
Entree & Sondes_Int::readOn (Entree & s) [protected, virtual]
Lit une liste de sondes a partir d'un flot d'entree
Format: { [LIRE UNE SONDE AUTANT DE FOIS QUE NECESSAIRE] }.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from List_Sonde_Int.
Definition at line 46 of file Sondes_Int.cpp.
References List_Sonde_Int::add(), Sonde_Int::associer_post(), Cerr, Process::exit(), finl, mon_post, O_U_Ptr::non_nul(), and Ref_Postraitement::valeur().
{
  assert(mon_post.non_nul());
  Motcle motlu;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  s >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error while reading the probes in the postprocessing" << finl;
      Cerr << "We expected { to start to read the probes" << finl;
      exit();
    }
  s >> motlu;
  if (motlu == accolade_fermee)
    {
      Cerr << "Error while reading the probes in the postprocessing" << finl;
      Cerr << "You have not defined any probe" << finl;
      exit();
    }
  while (motlu != accolade_fermee)
    {
      Sonde_Int une_sonde(motlu);
      une_sonde.associer_post(mon_post.valeur());
      s >> une_sonde;
      add(une_sonde);
      s >> motlu;
    }
  Cerr << "End of reading probes " << finl;
  return s;
}
const Sondes_Int & Sondes_Int::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
Sondes_Int & Sondes_Int::self_cast (Objet_U & r) [static]
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
unsigned Sondes_Int::taille_memoire () const [virtual]
Reimplemented from List_Sonde_Int.
Definition at line 27 of file Sondes_Int.cpp.
Member Data Documentation
const Type_info Sondes_Int::info_obj [static]
Reimplemented from List_Sonde_Int.
Definition at line 43 of file Sondes_Int.h.
Ref_Postraitement Sondes_Int::mon_post [private]
Definition at line 55 of file Sondes_Int.h.
Referenced by associer_post(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sondes_Int.h
src/Kernel/Framework/Sondes_Int.cpp