TRUST: Convection_Diffusion_Espece_Multi_QC Class Reference
Convection_Diffusion_Espece_Multi_QC Class Reference
classe Convection_Diffusion_Espece_Multi_QC
Cas particulier de Convection_Diffusion_Espece_Multi_base
pour un fluide quasi conpressible quand le scalaire subissant le transport est
la fraction massique
#include <Convection_Diffusion_Espece_Multi_QC.h>
Public Member Functions
Convection_Diffusion_Espece_Multi_QC ()
~Convection_Diffusion_Espece_Multi_QC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
void completer () override
Associe l inconnue de l equation a la loi d etat,.
void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem) override
const Champ_base & diffusivite_pour_pas_de_temps () const override
void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Renvoie la derivee en temps de l'inconnue de l'equation.
Le calcul est le suivant:
d(inconnue)/dt = M^{-1} * (sources - somme(Op_{i}(inconnue))) / rho.
const Espece & espece () const
Espece & espece ()
Public Member Functions inherited from Convection_Diffusion_Espece_Multi_base
Convection_Diffusion_Espece_Multi_base ()
~Convection_Diffusion_Espece_Multi_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Champ_base & get_champ (const Motcle &nom) const override
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
const Motcle & get_alias () const
Public Member Functions inherited from Convection_Diffusion_Espece_Fluide_Dilatable_base
Convection_Diffusion_Espece_Fluide_Dilatable_base ()
~Convection_Diffusion_Espece_Fluide_Dilatable_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
void calculer_div_u_ou_div_rhou (DoubleTab &res) const override
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int preparer_calcul () override
Tout ce qui ne depend pas des autres problemes eventuels.
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem) override=0
const Champ_base & diffusivite_pour_pas_de_temps () const override=0
DoubleTab & derivee_en_temps_inco (DoubleTab &) override=0
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
bool is_thermal () const override
bool is_generic () const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
Convection_Diffusion_Fluide_Dilatable_base ()
~Convection_Diffusion_Fluide_Dilatable_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &)
void associer_milieu_base (const Milieu_base &) override
int impr (Sortie &os) const override
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
const Champ_Don & diffusivite_pour_transport () const override
const Fluide_Dilatable_base & fluide () const
Fluide_Dilatable_base & fluide ()
const Milieu_base & milieu () const override
Milieu_base & milieu () override
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void calculer_div_u_ou_div_rhou (DoubleTab &res) const override=0
bool is_thermal () const override=0
bool is_generic () const override=0
const Champ_Inc & inconnue () const override
Champ_Inc & inconnue () override
const Zone_Cl_dis & zone_cl_modif () const
Zone_Cl_dis & zone_cl_modif ()
Public Member Functions inherited from Convection_Diffusion_std
Convection_Diffusion_std ()
~Convection_Diffusion_std () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void associer_vitesse (const Champ_base &)
Associe la vitesse transportante a l'equation.
const Champ_Inc_base & vitesse_transportante () const
Renvoie une reference sur le champ representant
la vitesse transportante.
const Champ_Inc & inconnue () const override=0
Champ_Inc & inconnue () override=0
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
int sauvegarder_base (Sortie &) const
int reprendre_base (Entree &)
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
virtual ~Convection_Diffusion_Fluide_Dilatable_Proto ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Convection_Diffusion_Espece_Multi_QC & self_cast (Objet_U &)
static const Convection_Diffusion_Espece_Multi_QC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_Espece_Multi_base
static const Type_info * info ()
static Convection_Diffusion_Espece_Multi_base & self_cast (Objet_U &)
static const Convection_Diffusion_Espece_Multi_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_Espece_Fluide_Dilatable_base
static const Type_info * info ()
static Convection_Diffusion_Espece_Fluide_Dilatable_base & self_cast (Objet_U &)
static const Convection_Diffusion_Espece_Fluide_Dilatable_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
static const Type_info * info ()
static Convection_Diffusion_Fluide_Dilatable_base & self_cast (Objet_U &)
static const Convection_Diffusion_Fluide_Dilatable_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Convection_Diffusion_std
static const Type_info * info ()
static Convection_Diffusion_std & self_cast (Objet_U &)
static const Convection_Diffusion_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
static int Sauvegarder_WC (Sortie &os, const Convection_Diffusion_std &eq, const Fluide_Dilatable_base &fld)
static int Reprendre_WC (Entree &is, double temps, Convection_Diffusion_std &eq, Fluide_Dilatable_base &fld, Champ_Inc &inco, Probleme_base &pb)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_Espece_Multi_base
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_Espece_Fluide_Dilatable_base
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_Fluide_Dilatable_base
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Protected Member Functions inherited from Convection_Diffusion_std
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
void calculer_div_rho_u_impl (DoubleTab &res, const Convection_Diffusion_Fluide_Dilatable_base &eqn) const
void assembler_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
void assembler_blocs (Convection_Diffusion_Fluide_Dilatable_base &eqn, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl)
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Renvoie la derivee en temps de l'inconnue de l'equation.
Le calcul est le suivant:
d(inconnue)/dt = M^{-1} * (sources - somme(Op_{i}(inconnue))) / rho.
virtual void calculer_div_u_ou_div_rhou (DoubleTab &res) const =0
virtual bool is_thermal () const =0
virtual bool is_generic () const =0
Protected Attributes
Espece mon_espece_
Protected Attributes inherited from Convection_Diffusion_Espece_Multi_base
Motcle alias_
Protected Attributes inherited from Convection_Diffusion_Fluide_Dilatable_base
Champ_Inc l_inco_ch
Zone_Cl_dis zcl_modif_
Ref_Fluide_Dilatable_base le_fluide
Protected Attributes inherited from Convection_Diffusion_std
Ref_Champ_Inc_base la_vitesse_transportante
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe Convection_Diffusion_Espece_Multi_QC
Cas particulier de Convection_Diffusion_Espece_Multi_base
pour un fluide quasi conpressible quand le scalaire subissant le transport est
la fraction massique
Definition at line 33 of file Convection_Diffusion_Espece_Multi_QC.h.
Constructor & Destructor Documentation
Convection_Diffusion_Espece_Multi_QC()
Convection_Diffusion_Espece_Multi_QC::Convection_Diffusion_Espece_Multi_QC ()
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
~Convection_Diffusion_Espece_Multi_QC()
Convection_Diffusion_Espece_Multi_QC::~Convection_Diffusion_Espece_Multi_QC ()
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
Member Function Documentation
assembler()
void Convection_Diffusion_Espece_Multi_QC::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 147 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  resu=0;
  const IntVect& tab1= matrice.get_tab1();
  DoubleVect& coeff=matrice.get_set_coeff();
  const DoubleTab& rho=get_champ("masse_volumique").valeurs();
  operateur(0).l_op_base().contribuer_a_avec(inco, matrice );
  operateur(0).ajouter( resu );
  int ndl=rho.dimension(0);
// on divise par rho chaque ligne
  for (int som=0; som<ndl; som++)
    {
      double inv_rho=1/rho(som);
      for (int k=tab1(som)-1; k<tab1(som+1)-1; k++)
        coeff(k)*=inv_rho;
      resu(som)*=inv_rho;
    }
// ajout de la convection
  operateur(1).l_op_base().contribuer_a_avec(inco, matrice );
  operateur(1).ajouter(resu );
// on retire Divu1 *inco
  DoubleTrav unite(inco),divu1(inco);
  unite=1;
  {
// on change temporairement la zone_cl
    operateur(1).l_op_base().associer_zone_cl_dis(zcl_modif_.valeur());
    operateur(1).ajouter(unite,divu1);
    operateur(1).l_op_base().associer_zone_cl_dis(zone_Cl_dis().valeur());
  }
  for (int i=0; i<ndl; i++)
    {
      resu(i)-=divu1(i)*inco(i);
      matrice(i,i)+=divu1(i);
    }
  les_sources.contribuer_a_avec(inco,matrice);
  les_sources.ajouter(resu);
  int test_op=0;
  {
    char* theValue = getenv("TRUST_TEST_OPERATEUR_IMPLICITE_BLOQUANT");
    if (theValue != NULL) test_op=1;
  }
  if (test_op)
    {
      DoubleTab test(resu);
      DoubleTab test2(resu);
      DoubleTrav resu2(resu);
      derivee_en_temps_inco(resu2);
      solveur_masse.appliquer(test2);
      resu2-=test2;
      Cerr<<" here " <<mp_max_abs_vect(resu2)<<finl;
      matrice.ajouter_multvect(inco,test);
      solveur_masse.appliquer(test);
      const double max_test = mp_max_abs_vect(test);
      Cerr<<"iii "<<max_test<<finl;
      if (max_test>0)
        {
          for (int i=0; i<resu.size(); i++)
            if (std::fabs(test(i))>1e-5)
              Cerr<<i << " "<<test(i)<<finl;
// Cerr<<resu <<finl;
          Process::exit();
        }
    }
  matrice.ajouter_multvect(inco,resu);
  /*
    Cerr<<" Convection_Diffusion_Espece_Multi_QC::assembler non code "<<finl;
    Cerr<<"vous ne pouvez pas faire d'implicite avec des fracions massiques "<<finl;
    exit();
  */
}
References Operateur::ajouter(), Sources::ajouter(), Matrice_Base::ajouter_multvect(), Solveur_Masse::appliquer(), Operateur_base::associer_zone_cl_dis(), Cerr, coeff, Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), derivee_en_temps_inco(), TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Convection_Diffusion_Espece_Multi_base::get_champ(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Operateur::l_op_base(), Equation_base::les_sources, mp_max_abs_vect(), Convection_Diffusion_std::operateur(), TRUSTVect< _TYPE_ >::size(), Equation_base::solveur_masse, test(), Deriv_Zone_Cl_dis_base::valeur(), valeur(), Champ_Proto::valeurs(), Convection_Diffusion_Fluide_Dilatable_base::zcl_modif_, and Equation_base::zone_Cl_dis().
assembler_blocs_avec_inertie()
void Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) override virtual
Reimplemented from Equation_base.
Definition at line 237 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  statistiques().begin_count(assemblage_sys_counter_);
  const std::string& nom_inco = inconnue().le_nom().getString();
  const DoubleTab& inco = inconnue().valeurs();
  Matrice_Morse *mat = matrices.count(nom_inco)?matrices.at(nom_inco):NULL;
  secmem=0;
  const IntVect& tab1= mat->get_tab1();
  DoubleVect& coeff=mat->get_set_coeff();
  const DoubleTab& rho=get_champ("masse_volumique").valeurs();
  operateur(0).l_op_base().ajouter_blocs(matrices, secmem, semi_impl);
  int ndl=rho.dimension(0);
// on divise par rho chaque ligne
  for (int som=0; som<ndl; som++)
    {
      double inv_rho=1/rho(som);
      for (int k=tab1(som)-1; k<tab1(som+1)-1; k++)
        coeff(k)*=inv_rho;
      secmem(som)*=inv_rho;
    }
// ajout de la convection
  operateur(1).l_op_base().ajouter_blocs(matrices, secmem, semi_impl);
// on retire Divu1 *inco
  DoubleTrav unite(inco),divu1(inco);
  unite=1;
  {
// on change temporairement la zone_cl
    operateur(1).l_op_base().associer_zone_cl_dis(zcl_modif_.valeur());
    operateur(1).ajouter(unite,divu1);
    operateur(1).l_op_base().associer_zone_cl_dis(zone_Cl_dis().valeur());
  }
  for (int i=0; i<ndl; i++)
    {
      secmem(i)-=divu1(i)*inco(i);
      if(mat) (*mat)(i,i)+=divu1(i);
    }
  statistiques().end_count(assemblage_sys_counter_);
  statistiques().begin_count(source_counter_);
  for (int i = 0; i < sources().size(); i++)
    sources()(i).valeur().ajouter_blocs(matrices, secmem, semi_impl);
  statistiques().end_count(source_counter_);
  statistiques().begin_count(assemblage_sys_counter_);
  if(mat) mat->ajouter_multvect(inco,secmem);
  schema_temps().ajouter_blocs(matrices, secmem, *this);
  if (!discretisation().que_suis_je().debute_par("PolyMAC"))
    modifier_pour_Cl(*mat,secmem);
  statistiques().end_count(assemblage_sys_counter_);
}
References Operateur::ajouter(), Schema_Temps_base::ajouter_blocs(), Operateur_base::ajouter_blocs(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Operateur_base::associer_zone_cl_dis(), Statistiques::begin_count(), coeff, TRUSTTab< _TYPE_ >::dimension(), Equation_base::discretisation(), Statistiques::end_count(), Convection_Diffusion_Espece_Multi_base::get_champ(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Nom::getString(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Operateur::l_op_base(), O_U_Ptr::le_nom(), Equation_base::modifier_pour_Cl(), Convection_Diffusion_std::operateur(), Objet_U::que_suis_je(), Equation_base::schema_temps(), liste::size(), source_counter_, Equation_base::sources(), statistiques(), Deriv_Zone_Cl_dis_base::valeur(), valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Convection_Diffusion_Fluide_Dilatable_base::zcl_modif_, and Equation_base::zone_Cl_dis().
completer()
void Convection_Diffusion_Espece_Multi_QC::completer (void) override virtual
Associe l inconnue de l equation a la loi d etat,.
Reimplemented from Equation_base.
Definition at line 68 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  Convection_Diffusion_Espece_Multi_base::completer();
  Fluide_Quasi_Compressible& le_fluideQC=ref_cast(Fluide_Quasi_Compressible,fluide());
  Loi_Etat_Multi_GP_QC& loi_etat = ref_cast_non_const(Loi_Etat_Multi_GP_QC,le_fluideQC.loi_etat().valeur());
  loi_etat.associer_inconnue(l_inco_ch.valeur());
  loi_etat.associer_espece(*this);
}
References Loi_Etat_Multi_GP_QC::associer_espece(), Loi_Etat_Multi_GP_base::associer_inconnue(), Equation_base::completer(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch, Fluide_Dilatable_base::loi_etat(), ref_cast, ref_cast_non_const, Deriv_Champ_Inc_base::valeur(), and Deriv_Loi_Etat_base::valeur().
cree_instance()
Objet_U * Convection_Diffusion_Espece_Multi_QC::cree_instance () static
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Renvoie la derivee en temps de l'inconnue de l'equation.
Le calcul est le suivant:
d(inconnue)/dt = M^{-1} * (sources - somme(Op_{i}(inconnue))) / rho.
Returns
DoubleTab&
Signification: le tableau des valeurs de la derivee en temps du champ inconnu
Contraintes:
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 93 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  if (schema_temps().diffusion_implicite())
    {
// on ne peut  pas pour l'instanrt aller plus vite que la CFL
      double dt=le_schema_en_temps->pas_de_temps();
      double dt_op = operateur(1).calculer_pas_de_temps();
      if(inf_strict(dt_op,dt))
        {
          Cerr<<"diffusion_implicite cannot be achieved for the case dt > dt_op_conv"<<finl;
          Process::exit();
        }
    }
  DoubleTrav secmem(derivee);
// on commence par retirer phi*div(1 U)
  const DoubleTab& frac_mass = inconnue().valeurs();
  int n = frac_mass.dimension_tot(0);
  DoubleTrav unite(frac_mass);
  unite=1;
// on change temporairement la zone_cl
  operateur(1).l_op_base().associer_zone_cl_dis(zcl_modif_.valeur());
  operateur(1).ajouter(unite,secmem);
  operateur(1).l_op_base().associer_zone_cl_dis(zone_Cl_dis().valeur());
  for (int i=0; i<n; i++)
    secmem(i)=-secmem(i)*frac_mass(i);
// suite + standard
  operateur(1).ajouter(secmem);
  les_sources.ajouter(secmem);
  solveur_masse.appliquer(secmem);
  solveur_masse->set_name_of_coefficient_temporel("masse_volumique");
  if (schema_temps().diffusion_implicite())
    {
      derivee=inconnue().valeurs();
      Equation_base::Gradient_conjugue_diff_impl(secmem, derivee);
    }
  else
    {
      DoubleTrav secmem_bis(secmem);
      operateur(0).ajouter(secmem_bis);
      solveur_masse.appliquer(secmem_bis);
      secmem += secmem_bis;
      derivee = secmem;
    }
  solveur_masse->set_name_of_coefficient_temporel("no_coeff");
  return derivee;
}
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::appliquer(), Operateur_base::associer_zone_cl_dis(), Operateur::calculer_pas_de_temps(), Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), finl, Equation_base::Gradient_conjugue_diff_impl(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), inf_strict(), Operateur::l_op_base(), Equation_base::le_schema_en_temps, Equation_base::les_sources, Convection_Diffusion_std::operateur(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Equation_base::solveur_masse, Deriv_Zone_Cl_dis_base::valeur(), valeur(), Champ_Inc::valeurs(), Convection_Diffusion_Fluide_Dilatable_base::zcl_modif_, and Equation_base::zone_Cl_dis().
Referenced by assembler().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_Espece_Multi_QC::diffusivite_pour_pas_de_temps () const override virtual
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 47 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
// TODO : FIXME : on passe actuellement en parametre mu_sur_Schmidt
// qu il faut remplacer par nu_sur_Schmidt
  return le_fluide->mu_sur_Schmidt();
}
References Convection_Diffusion_Fluide_Dilatable_base::le_fluide, and Fluide_Dilatable_base::mu_sur_Schmidt().
duplique()
int Convection_Diffusion_Espece_Multi_QC::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
espece() [1/2]
Espece & Convection_Diffusion_Espece_Multi_QC::espece () inline
Definition at line 47 of file Convection_Diffusion_Espece_Multi_QC.h.
{ return mon_espece_; }
References mon_espece_.
espece() [2/2]
const Espece & Convection_Diffusion_Espece_Multi_QC::espece () const inline
Definition at line 46 of file Convection_Diffusion_Espece_Multi_QC.h.
{ return mon_espece_; }
References mon_espece_.
Referenced by Loi_Etat_Multi_GP_QC::associer_espece().
get_info()
const Type_info * Convection_Diffusion_Espece_Multi_QC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Multi_base.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
info()
const Type_info * Convection_Diffusion_Espece_Multi_QC::info () static
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
printOn()
Sortie & Convection_Diffusion_Espece_Multi_QC::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Multi_base.
Definition at line 31 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  return Convection_Diffusion_Espece_Multi_base::printOn(is);
}
References Convection_Diffusion_Espece_Multi_base::printOn().
readOn()
Entree & Convection_Diffusion_Espece_Multi_QC::readOn (Entree & is) override protected virtual
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< XD attr disable_equation_residual chaine disable_equation_residual 1 The equation residual will not be used for the problem residual used when checking time convergence or computing dynamic time-step
Reimplemented from Convection_Diffusion_Espece_Multi_base.
Definition at line 36 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  return Convection_Diffusion_Espece_Multi_base::readOn(is);
}
References Convection_Diffusion_Espece_Multi_base::readOn().
self_cast() [1/2]
const Convection_Diffusion_Espece_Multi_QC & Convection_Diffusion_Espece_Multi_QC::self_cast (const Objet_U & r) static
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
self_cast() [2/2]
Convection_Diffusion_Espece_Multi_QC & Convection_Diffusion_Espece_Multi_QC::self_cast (Objet_U & r) static
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
set_param()
void Convection_Diffusion_Espece_Multi_QC::set_param (Param & titi) override virtual
< XD_ADD_P espece Assosciate a species (with its properties) to the equation
Reimplemented from Convection_Diffusion_Espece_Multi_base.
Definition at line 41 of file Convection_Diffusion_Espece_Multi_QC.cpp.
{
  Convection_Diffusion_Espece_Multi_base::set_param(param);
  param.ajouter("espece",&mon_espece_); //!< XD_ADD_P espece Assosciate a species (with its properties) to the equation
}
References Param::ajouter(), mon_espece_, and Convection_Diffusion_Espece_Multi_base::set_param().
taille_memoire()
unsigned Convection_Diffusion_Espece_Multi_QC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Convection_Diffusion_Espece_Multi_QC.cpp.
Member Data Documentation
info_obj
const Type_info Convection_Diffusion_Espece_Multi_QC::info_obj static
Definition at line 35 of file Convection_Diffusion_Espece_Multi_QC.h.
mon_espece_
Espece Convection_Diffusion_Espece_Multi_QC::mon_espece_ protected
Definition at line 50 of file Convection_Diffusion_Espece_Multi_QC.h.
Referenced by espece(), and set_param().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Equations/Convection_Diffusion_Espece_Multi_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Equations/Convection_Diffusion_Espece_Multi_QC.cpp