TRUST: Op_Conv_EF Class Reference
Op_Conv_EF Class Reference
class Op_Conv_EF
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est EF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Decentre ou Centre
#include <Op_Conv_EF.h>
Public Member Functions
Op_Conv_EF ()
~Op_Conv_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_a_la_diffusion (const DoubleTab &, DoubleTab &) const
double calculer_dt_stab () const
Calcul dt_stab.
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice au moyen de la methode dimensionner de la classe
Op_EF_base.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
On modifie le second membre et la matrice dans le cas des
conditions de dirichlet.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice des inconnues implicite.
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution_sous_cond (const DoubleTab &transporte, Matrice_Morse &matrice, int btd_impl, int hourglass_impl, int centre_impl) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_a_la_diffusion (const DoubleTab &, Matrice_Morse &) const
void contribue_au_second_membre_a_la_diffusion (DoubleTab &resu) const
DoubleTab & ajouter_sous_cond (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
virtual double coefficient_btd () const
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
double get_btd () const
const Champ_base & get_champ (const Motcle &nom) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_EF & self_cast (Objet_U &)
static const Op_Conv_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Types
enum type_operateur { amont, muscl, centre }
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter_sous_cond_gen (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim3_nbn8_nbdim1 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim3_nbn8_nbdim2 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim2_nbn4_nbdim1 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
DoubleTab & ajouter_sous_cond_dim2_nbn4_nbdim2 (const DoubleTab &transporte, DoubleTab &resu, int btd_impl, int hourglass_impl, int centre_impl) const
Protected Attributes
double hourglass
int hourglass_impl_
int btd_impl_
int centre_impl_
flag pour savoir si les termes sont implicites
int hourglass_hors_conv_
int btd_hors_conv_
double f_lu_
int calcul_dt_stab_
type_operateur type_op
double max_ue_
double min_dx_
Champ_Uniforme coefficient_correcteur_supg_
double btd_
Detailed Description
class Op_Conv_EF
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est EF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Decentre ou Centre
Definition at line 45 of file Op_Conv_EF.h.
Member Enumeration Documentation
enum Op_Conv_EF::type_operateur [protected]
Enumerator:
amont
muscl
centre
Definition at line 86 of file Op_Conv_EF.h.
{ amont, muscl, centre };
Constructor & Destructor Documentation
Op_Conv_EF::Op_Conv_EF ()
Definition at line 36 of file Op_Conv_EF.cpp.
                      : hourglass(0.),hourglass_impl_(0),btd_impl_(0),centre_impl_(0), hourglass_hors_conv_(0),btd_hors_conv_(0),f_lu_(-1.),calcul_dt_stab_(0)
{
}
Op_Conv_EF::~Op_Conv_EF ()
Definition at line 34 of file Op_Conv_EF.cpp.
Member Function Documentation
DoubleTab & Op_Conv_EF::ajouter (const DoubleTab & transporte, DoubleTab & resu) const [virtual]
Reimplemented from Operateur_base.
Definition at line 169 of file Op_Conv_EF.cpp.
References ajouter_sous_cond(), btd_hors_conv_, and hourglass_hors_conv_.
{
  return ajouter_sous_cond(transporte,resu,btd_hors_conv_,hourglass_hors_conv_,0);
}
DoubleTab & Op_Conv_EF::ajouter_a_la_diffusion (const DoubleTab & transporte, DoubleTab & resu) const
Definition at line 174 of file Op_Conv_EF.cpp.
References ajouter_sous_cond(), btd_hors_conv_, and hourglass_hors_conv_.
{
  return ajouter_sous_cond(transporte,resu,!btd_hors_conv_,!hourglass_hors_conv_,1);
}
void Op_Conv_EF::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 1159 of file Op_Conv_EF.cpp.
References ajouter_contribution_sous_cond(), btd_hors_conv_, btd_impl_, centre_impl_, hourglass_hors_conv_, and hourglass_impl_.
Referenced by contribuer_a_avec().
{
  return ajouter_contribution_sous_cond(transporte,matrice,(btd_impl_)&&(btd_hors_conv_==0),(hourglass_impl_)&&(hourglass_hors_conv_==0),centre_impl_);
}
void Op_Conv_EF::ajouter_contribution_a_la_diffusion (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 1164 of file Op_Conv_EF.cpp.
References ajouter_contribution_sous_cond(), btd_hors_conv_, btd_impl_, hourglass_hors_conv_, and hourglass_impl_.
{
  ajouter_contribution_sous_cond(transporte,matrice,(btd_impl_)&&(btd_hors_conv_==1),(hourglass_impl_)&&(hourglass_hors_conv_==1),0);
}
void Op_Conv_EF::ajouter_contribution_sous_cond (const DoubleTab & transporte, Matrice_Morse & matrice, int btd_impl, int hourglass_impl, int centre_impl) const
Definition at line 1033 of file Op_Conv_EF.cpp.
References amont, Zone_EF::Bij(), Matrice_Morse::coef(), coefficient_btd(), Objet_U::dimension, dotproduct_array(), Op_EF_base::elem_contribue(), MorEqn::equation(), Probleme_base::get_champ(), hourglass, Zone_EF::IPhi_thilde(), O_U_Ptr::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Equation_base::probleme(), ref_cast, DoubleVect::size(), type_op, valeur(), Ref_Champ_Inc_base::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), Op_Conv_EF_base::vitesse_, Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
Referenced by ajouter_contribution(), and ajouter_contribution_a_la_diffusion().
{
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  int nb_comp = transporte.line_size();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  ArrOfDouble G_e(dimension);
  double f=coefficient_btd();
// DoubleTab transp_loc(nb_som_elem,nb_comp);
// A DEPLACER !!!!!
  const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif=1;
  if (lambda.size()==1)
    is_not_lambda_unif=0;
  int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
  int sommetoppose[8]= {7,6,5,4,3,2,1,0};
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<dimension; b++)
              G_e(b)+=G(glob,b);
          }
        G_e/=nb_som_elem;
        double pond2=volumes_thilde(elem)/volumes(elem)/volumes(elem);
        if (transport_rhou) pond2 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
        if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==1))
          {
            double pond3=f*dotproduct_array(G_e,G_e);
            if (transport_rhou) pond3 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            if (is_not_lambda_unif)
              pond3+=lambda(elem);
            else
              pond3+=lambda(0,0);
            pond3*=volumes_thilde(elem)/volumes(elem)*pow(volumes(elem),0.3333333333333333);
            pond3*=hourglass;
            for (int a=0; a<nb_comp; a++)
              {
                double coef2d=0.042*pond3;
                double coef3d=coef2d*0.5;
                for (int i1=0; i1<8; i1++)
                  {
                    int n1=elems(elem,i1)*nb_comp+a;
                    for (int i2=0; i2<8; i2++)
                      {
                        int n2=elems(elem,i2)*nb_comp+a;
                        matrice.coef(n1,n2)+=mcoef3d[i1]*mcoef3d[i2]*coef3d-coef2d;
                      }
                    matrice.coef(n1,n1)+=coef2d*4.;
                    matrice.coef(n1,elems(elem,sommetoppose[i1])*nb_comp+a)+=coef2d*4.;
                  }
              }
          }
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            if (((btd_impl==1)&&(type_op==amont))||(centre_impl==1))
              {
                double cb=0;
                for (int b=0; b<dimension; b++)
                  cb+=G_e(b)*bij(elem,i1,b);
                cb*=(f*pond2);
                for (int i2=0; i2<nb_som_elem; i2++)
                  {
                    int glob2=elems(elem,i2);
                    double ca=0;
                    if (centre_impl==1)
                      {
                        for (int b=0; b<dimension; b++)
                          ca+=G_e(b)*bij(elem,i2,b);
                        double pond=IPhi_thilde(elem,i1)/volumes(elem);
                        ca*=pond;
                      }
                    double cc=0;
                    if ((btd_impl==1)&&(type_op==amont))
                      {
                        for (int c=0; c<dimension; c++)
                          cc+=G_e(c)*bij(elem,i2,c);
                        cc*=cb;
                      }
// resu(glob)-=cc*cb*transp_loc(i2,0);
                    for (int a=0; a<nb_comp; a++)
                      {
                        int n1=glob*nb_comp+a;
                        int n2=glob2*nb_comp+a;
                        matrice.coef(n1,n2)+=cc+ca;
                      }
                  }
              }
          }
      }
  return;
}
DoubleTab & Op_Conv_EF::ajouter_sous_cond (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const
Definition at line 1016 of file Op_Conv_EF.cpp.
References ajouter_sous_cond_dim3_nbn8_nbdim1(), ajouter_sous_cond_dim3_nbn8_nbdim2(), ajouter_sous_cond_gen(), Objet_U::dimension, MorEqn::equation(), DoubleVect::line_size(), Zone::nb_som_elem(), ref_cast, valeur(), and Zone_dis_base::zone().
Referenced by ajouter(), ajouter_a_la_diffusion(), contribue_au_second_membre(), and contribue_au_second_membre_a_la_diffusion().
{
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  int nb_compo=transporte.line_size();
  if ((dimension==3)&&(nb_som_elem==8))
    {
      if (nb_compo==1)
        return ajouter_sous_cond_dim3_nbn8_nbdim1(transporte,resu,btd_impl,hourglass_impl,centre_impl);
      else
        return ajouter_sous_cond_dim3_nbn8_nbdim2(transporte,resu,btd_impl,hourglass_impl,centre_impl);
    }
  return ajouter_sous_cond_gen(transporte,resu,btd_impl,hourglass_impl,centre_impl);
}
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const [protected]
Definition at line 850 of file Op_Conv_EF.cpp.
References Process::abort(), ArrOfDouble::addr(), amont, Zone_EF::Bij(), bij_, coefficient_btd(), dotproduct_array(), DoubleVect::echange_espace_virtuel(), Op_EF_base::elem_contribue(), MorEqn::equation(), est_egal(), Op_Conv_EF_base::fluent, Probleme_base::get_champ(), hourglass, Zone_EF::IPhi_thilde(), Op_Conv_EF_base::la_zone_EF, O_U_Ptr::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Zone::nb_elem_tot(), Equation_base::probleme(), ref_cast, resu_, DoubleVect::size(), transp_loc_, transporte_, type_op, Ref_Champ_Inc_base::valeur(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), verifier(), Op_Conv_EF_base::vitesse_, Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
{
  const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
  const int nb_som_elem=4;
  if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;
  DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  Debog::verifier("conv vitesse",G);
  Debog::verifier("conv rho",rho_elem);
  Debog::verifier("conv transporte",transporte);
  int nb_comp0 = resu.line_size();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  double f= coefficient_btd();
  int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
  int sommetoppose[8]= {7,6,5,4,3,2,1,0};
  DoubleTab transp_loc(nb_som_elem,nb_comp0);
// A DEPLACER !!!!!
  const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif=1;
  if (lambda.size()==1) is_not_lambda_unif=0;
  const int const_dimension= 2;
// const int nb_som_elem= 4;
  const int nb_comp=1;
  const int dim_fois_nbn=8;
  if (nb_comp0!=nb_comp) abort();
  ArrOfDouble G_e(const_dimension);
  double pr[nb_comp],ge_bij[nb_som_elem];
  const double* bij_ptr=bij.addr();
  const double* transp_loc_ptr=transp_loc.addr();
  const double* transporte_ptr=transporte.addr();
  double* resu_ptr=resu.addr();
#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]
#define resu_(som,a) resu_ptr[som*nb_comp+a]
  double inv_nb_som_elem=1./nb_som_elem;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<const_dimension; b++)
              G_e[b]+=G(glob,b);
            for (int a=0; a<nb_comp; a++)
              transp_loc(i1,a)=transporte_(glob,a);
          }
        G_e*=inv_nb_som_elem;
// Cerr<<" coucou "<<G_e<<finl;
// *10 !!!!!!!!!!!
        double vol_elem=volumes(elem);
        double inv_vol_elem=1./vol_elem;
        double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;
        if (transport_rhou)
          pond2 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
        double fpond2=f*pond2;
        if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
          {
            double pond3=f*dotproduct_array(G_e,G_e);
            if (transport_rhou) pond3 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            if (is_not_lambda_unif)
              pond3+=lambda(elem);
            else
              pond3+=lambda(0,0);
            pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
            pond3*=hourglass;
            for (int a=0; a<nb_comp; a++)
              {
                double coef2d=0.042*pond3;
                double coef3d=coef2d*0.5;
                double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                   +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));
                double t3d=0;
                for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                t3d*=coef3d;
                double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                    -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                if (!est_egal(t3d,t3db,1e-6)) assert(0);
                /*
                double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                */
// if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                for (int i=0; i<8; i++)
                  resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
              }
          }
        {
          for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
          if ((centre_impl==0)||(btd_impl==0))
            {
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double cb=0;
                  for (int b=0; b<const_dimension; b++)
                    cb+=G_e[b]*bij_(elem,i1,b);
                  ge_bij[i1]=cb;
                }
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double pond=0;
                  if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                  int glob=elems(elem,i1);
// pr=0;
                  for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;
                  double cbbtd=pond;
                  if ((btd_impl==0)&&(type_op==amont))
                    cbbtd+=ge_bij[i1]*(fpond2);
                  for (int i2=0; i2<nb_som_elem; i2++)
                    {
                      const double cbi2=ge_bij[i2];
                      double coef=cbbtd*cbi2;
                      for (int a=0; a<nb_comp; a++)
                        pr[a]-=coef*transp_loc_(i2,a);
                    }
                  for (int a=0; a<nb_comp; a++)
                    resu_(glob,a)+=pr[a];
                }
            }
        }
      }
  fluent_.echange_espace_virtuel();
  return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
}
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const [protected]
Definition at line 685 of file Op_Conv_EF.cpp.
References Process::abort(), ArrOfDouble::addr(), amont, Zone_EF::Bij(), bij_, coefficient_btd(), dotproduct_array(), DoubleVect::echange_espace_virtuel(), Op_EF_base::elem_contribue(), MorEqn::equation(), est_egal(), Op_Conv_EF_base::fluent, Probleme_base::get_champ(), hourglass, Zone_EF::IPhi_thilde(), Op_Conv_EF_base::la_zone_EF, O_U_Ptr::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Zone::nb_elem_tot(), Equation_base::probleme(), ref_cast, resu_, DoubleVect::size(), transp_loc_, transporte_, type_op, Ref_Champ_Inc_base::valeur(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), verifier(), Op_Conv_EF_base::vitesse_, Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
{
  const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
  const int nb_som_elem=4;
  if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;
  DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  Debog::verifier("conv vitesse",G);
  Debog::verifier("conv rho",rho_elem);
  Debog::verifier("conv transporte",transporte);
  int nb_comp0 = resu.line_size();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  double f= coefficient_btd();
  int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
  int sommetoppose[8]= {7,6,5,4,3,2,1,0};
  DoubleTab transp_loc(nb_som_elem,nb_comp0);
// A DEPLACER !!!!!
  const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif=1;
  if (lambda.size()==1) is_not_lambda_unif=0;
  const int const_dimension= 2;
// const int nb_som_elem= 4;
  const int nb_comp=2;
  const int dim_fois_nbn=8;
  if (nb_comp0!=nb_comp) abort();
  ArrOfDouble G_e(const_dimension);
  double pr[nb_comp],ge_bij[nb_som_elem];
  const double* bij_ptr=bij.addr();
  const double* transp_loc_ptr=transp_loc.addr();
  const double* transporte_ptr=transporte.addr();
  double* resu_ptr=resu.addr();
#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]
#define resu_(som,a) resu_ptr[som*nb_comp+a]
  double inv_nb_som_elem=1./nb_som_elem;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<const_dimension; b++)
              G_e[b]+=G(glob,b);
            for (int a=0; a<nb_comp; a++)
              transp_loc(i1,a)=transporte_(glob,a);
          }
        G_e*=inv_nb_som_elem;
// Cerr<<" coucou "<<G_e<<finl;
// *10 !!!!!!!!!!!
        double vol_elem=volumes(elem);
        double inv_vol_elem=1./vol_elem;
        double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;
        if (transport_rhou)
          pond2 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
        double fpond2=f*pond2;
        if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
          {
            double pond3=f*dotproduct_array(G_e,G_e);
            if (transport_rhou) pond3 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            if (is_not_lambda_unif)
              pond3+=lambda(elem);
            else
              pond3+=lambda(0,0);
            pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
            pond3*=hourglass;
            for (int a=0; a<nb_comp; a++)
              {
                double coef2d=0.042*pond3;
                double coef3d=coef2d*0.5;
                double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                   +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));
                double t3d=0;
                for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                t3d*=coef3d;
                double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                    -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                if (!est_egal(t3d,t3db,1e-6)) assert(0);
                /*
                double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                */
// if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                for (int i=0; i<8; i++)
                  resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
              }
          }
        {
          for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
          if ((centre_impl==0)||(btd_impl==0))
            {
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double cb=0;
                  for (int b=0; b<const_dimension; b++)
                    cb+=G_e[b]*bij_(elem,i1,b);
                  ge_bij[i1]=cb;
                }
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double pond=0;
                  if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                  int glob=elems(elem,i1);
// pr=0;
                  for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;
                  double cbbtd=pond;
                  if ((btd_impl==0)&&(type_op==amont))
                    cbbtd+=ge_bij[i1]*(fpond2);
                  for (int i2=0; i2<nb_som_elem; i2++)
                    {
                      const double cbi2=ge_bij[i2];
                      double coef=cbbtd*cbi2;
                      for (int a=0; a<nb_comp; a++)
                        pr[a]-=coef*transp_loc_(i2,a);
                    }
                  for (int a=0; a<nb_comp; a++)
                    resu_(glob,a)+=pr[a];
                }
            }
        }
      }
  fluent_.echange_espace_virtuel();
  return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
}
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const [protected]
Definition at line 519 of file Op_Conv_EF.cpp.
References Process::abort(), ArrOfDouble::addr(), amont, Zone_EF::Bij(), bij_, coefficient_btd(), dotproduct_array(), DoubleVect::echange_espace_virtuel(), Op_EF_base::elem_contribue(), MorEqn::equation(), est_egal(), Op_Conv_EF_base::fluent, Probleme_base::get_champ(), hourglass, Zone_EF::IPhi_thilde(), Op_Conv_EF_base::la_zone_EF, O_U_Ptr::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Zone::nb_elem_tot(), Equation_base::probleme(), ref_cast, resu_, DoubleVect::size(), transp_loc_, transporte_, type_op, Ref_Champ_Inc_base::valeur(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), verifier(), Op_Conv_EF_base::vitesse_, Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
Referenced by ajouter_sous_cond().
{
  const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
  const int nb_som_elem=8;
  if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;
  DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  Debog::verifier("conv vitesse",G);
  Debog::verifier("conv rho",rho_elem);
  Debog::verifier("conv transporte",transporte);
  int nb_comp0 = resu.line_size();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  double f= coefficient_btd();
  int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
  int sommetoppose[8]= {7,6,5,4,3,2,1,0};
  DoubleTab transp_loc(nb_som_elem,nb_comp0);
// A DEPLACER !!!!!
  const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif=1;
  if (lambda.size()==1) is_not_lambda_unif=0;
  const int const_dimension= 3;
// const int nb_som_elem= 8;
  const int nb_comp=1;
  const int dim_fois_nbn=24;
  if (nb_comp0!=nb_comp) abort();
  ArrOfDouble G_e(const_dimension);
  double pr[nb_comp],ge_bij[nb_som_elem];
  const double* bij_ptr=bij.addr();
  const double* transp_loc_ptr=transp_loc.addr();
  const double* transporte_ptr=transporte.addr();
  double* resu_ptr=resu.addr();
#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]
#define resu_(som,a) resu_ptr[som*nb_comp+a]
  double inv_nb_som_elem=1./nb_som_elem;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<const_dimension; b++)
              G_e[b]+=G(glob,b);
            for (int a=0; a<nb_comp; a++)
              transp_loc(i1,a)=transporte_(glob,a);
          }
        G_e*=inv_nb_som_elem;
// Cerr<<" coucou "<<G_e<<finl;
// *10 !!!!!!!!!!!
        double vol_elem=volumes(elem);
        double inv_vol_elem=1./vol_elem;
        double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;
        if (transport_rhou)
          pond2 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
        double fpond2=f*pond2;
        if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
          {
            double pond3=f*dotproduct_array(G_e,G_e);
            if (transport_rhou) pond3 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            if (is_not_lambda_unif)
              pond3+=lambda(elem);
            else
              pond3+=lambda(0,0);
            pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
            pond3*=hourglass;
            for (int a=0; a<nb_comp; a++)
              {
                double coef2d=0.042*pond3;
                double coef3d=coef2d*0.5;
                double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                   +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));
                double t3d=0;
                for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                t3d*=coef3d;
                double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                    -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                if (!est_egal(t3d,t3db,1e-6)) assert(0);
                /*
                double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                */
// if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                for (int i=0; i<8; i++)
                  resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
              }
          }
        {
          for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
          if ((centre_impl==0)||(btd_impl==0))
            {
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double cb=0;
                  for (int b=0; b<const_dimension; b++)
                    cb+=G_e[b]*bij_(elem,i1,b);
                  ge_bij[i1]=cb;
                }
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double pond=0;
                  if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                  int glob=elems(elem,i1);
// pr=0;
                  for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;
                  double cbbtd=pond;
                  if ((btd_impl==0)&&(type_op==amont))
                    cbbtd+=ge_bij[i1]*(fpond2);
                  for (int i2=0; i2<nb_som_elem; i2++)
                    {
                      const double cbi2=ge_bij[i2];
                      double coef=cbbtd*cbi2;
                      for (int a=0; a<nb_comp; a++)
                        pr[a]-=coef*transp_loc_(i2,a);
                    }
                  for (int a=0; a<nb_comp; a++)
                    resu_(glob,a)+=pr[a];
                }
            }
        }
      }
  fluent_.echange_espace_virtuel();
  return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
}
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const [protected]
Definition at line 354 of file Op_Conv_EF.cpp.
References Process::abort(), ArrOfDouble::addr(), amont, Zone_EF::Bij(), bij_, coefficient_btd(), dotproduct_array(), DoubleVect::echange_espace_virtuel(), Op_EF_base::elem_contribue(), MorEqn::equation(), est_egal(), Op_Conv_EF_base::fluent, Probleme_base::get_champ(), hourglass, Zone_EF::IPhi_thilde(), Op_Conv_EF_base::la_zone_EF, O_U_Ptr::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Zone::nb_elem_tot(), Equation_base::probleme(), ref_cast, resu_, DoubleVect::size(), transp_loc_, transporte_, type_op, Ref_Champ_Inc_base::valeur(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), verifier(), Op_Conv_EF_base::vitesse_, Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
Referenced by ajouter_sous_cond().
{
  const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
  const int nb_som_elem=8;
  if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;
  DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  Debog::verifier("conv vitesse",G);
  Debog::verifier("conv rho",rho_elem);
  Debog::verifier("conv transporte",transporte);
  int nb_comp0 = resu.line_size();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  double f= coefficient_btd();
  int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
  int sommetoppose[8]= {7,6,5,4,3,2,1,0};
  DoubleTab transp_loc(nb_som_elem,nb_comp0);
// A DEPLACER !!!!!
  const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif=1;
  if (lambda.size()==1) is_not_lambda_unif=0;
  const int const_dimension= 3;
// const int nb_som_elem= 8;
  const int nb_comp=3;
  const int dim_fois_nbn=24;
  if (nb_comp0!=nb_comp) abort();
  ArrOfDouble G_e(const_dimension);
  double pr[nb_comp],ge_bij[nb_som_elem];
  const double* bij_ptr=bij.addr();
  const double* transp_loc_ptr=transp_loc.addr();
  const double* transporte_ptr=transporte.addr();
  double* resu_ptr=resu.addr();
#define bij_(elem,i,j) bij_ptr[elem*dim_fois_nbn+i*const_dimension+j]
#define transp_loc_(som,a) transp_loc_ptr[som*nb_comp+a]
#define transporte_(som,a) transporte_ptr[som*nb_comp+a]
#define resu_(som,a) resu_ptr[som*nb_comp+a]
  double inv_nb_som_elem=1./nb_som_elem;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<const_dimension; b++)
              G_e[b]+=G(glob,b);
            for (int a=0; a<nb_comp; a++)
              transp_loc(i1,a)=transporte_(glob,a);
          }
        G_e*=inv_nb_som_elem;
// Cerr<<" coucou "<<G_e<<finl;
// *10 !!!!!!!!!!!
        double vol_elem=volumes(elem);
        double inv_vol_elem=1./vol_elem;
        double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;
        if (transport_rhou)
          pond2 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
        double fpond2=f*pond2;
        if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
          {
            double pond3=f*dotproduct_array(G_e,G_e);
            if (transport_rhou) pond3 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            if (is_not_lambda_unif)
              pond3+=lambda(elem);
            else
              pond3+=lambda(0,0);
            pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
            pond3*=hourglass;
            for (int a=0; a<nb_comp; a++)
              {
                double coef2d=0.042*pond3;
                double coef3d=coef2d*0.5;
                double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                   +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));
                double t3d=0;
                for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                t3d*=coef3d;
                double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                    -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                if (!est_egal(t3d,t3db,1e-6)) assert(0);
                /*
                double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                */
// if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                for (int i=0; i<8; i++)
                  resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
              }
          }
        {
          for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
          if ((centre_impl==0)||(btd_impl==0))
            {
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double cb=0;
                  for (int b=0; b<const_dimension; b++)
                    cb+=G_e[b]*bij_(elem,i1,b);
                  ge_bij[i1]=cb;
                }
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double pond=0;
                  if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                  int glob=elems(elem,i1);
// pr=0;
                  for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;
                  double cbbtd=pond;
                  if ((btd_impl==0)&&(type_op==amont))
                    cbbtd+=ge_bij[i1]*(fpond2);
                  for (int i2=0; i2<nb_som_elem; i2++)
                    {
                      const double cbi2=ge_bij[i2];
                      double coef=cbbtd*cbi2;
                      for (int a=0; a<nb_comp; a++)
                        pr[a]-=coef*transp_loc_(i2,a);
                    }
                  for (int a=0; a<nb_comp; a++)
                    resu_(glob,a)+=pr[a];
                }
            }
        }
      }
  fluent_.echange_espace_virtuel();
  return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
}
DoubleTab & Op_Conv_EF::ajouter_sous_cond_gen (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const [protected]
Definition at line 193 of file Op_Conv_EF.cpp.
References amont, Zone_EF::Bij(), bij_, coefficient_btd(), Objet_U::dimension, dotproduct_array(), DoubleVect::echange_espace_virtuel(), Op_EF_base::elem_contribue(), MorEqn::equation(), est_egal(), Op_Conv_EF_base::fluent, Probleme_base::get_champ(), hourglass, Zone_EF::IPhi_thilde(), Op_Conv_EF_base::la_zone_EF, O_U_Ptr::le_nom(), Zone::les_elems(), DoubleVect::line_size(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Equation_base::probleme(), ref_cast, resu_, DoubleVect::size(), transp_loc_, transporte_, type_op, Ref_Champ_Inc_base::valeur(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), verifier(), Op_Conv_EF_base::vitesse_, Zone_VF::volumes(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
Referenced by ajouter_sous_cond().
{
  const Zone_EF& zone_ef = ref_cast(Zone_EF, la_zone_EF.valeur());
  const int nb_som_elem=zone_ef.zone().nb_som_elem();
  if ((btd_impl==1)&&(hourglass_impl==1)&&(centre_impl==1)) return resu;
  DoubleVect& fluent_ = ref_cast(DoubleVect, fluent);
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  Debog::verifier("conv vitesse",G);
  Debog::verifier("conv rho",rho_elem);
  Debog::verifier("conv transporte",transporte);
  int nb_comp0 = resu.line_size();
  const DoubleVect& volumes_thilde= zone_ef.volumes_thilde();
  const DoubleVect& volumes= zone_ef.volumes();
  const DoubleTab& IPhi_thilde=zone_ef.IPhi_thilde();
  const DoubleTab& bij=zone_ef.Bij();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  double f= coefficient_btd();
  int mcoef3d[8]= {1,-1,-1,1,-1,1,1,-1};
  int sommetoppose[8]= {7,6,5,4,3,2,1,0};
  DoubleTab transp_loc(nb_som_elem,nb_comp0);
// A DEPLACER !!!!!
  const DoubleTab& lambda=ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif=1;
  if (lambda.size()==1) is_not_lambda_unif=0;
  const int nb_comp=nb_comp0;
  const int const_dimension=Objet_U::dimension;
// int nb_som_elem=zone_ef.zone().nb_som_elem();
  ArrOfDouble G_e(const_dimension);
  ArrOfDouble pr(nb_comp),ge_bij(nb_som_elem);
#define bij_(elem,i,j) bij(elem,i,j)
#define transp_loc_(som,a) transp_loc(som,a)
#define transporte_(som,a) transporte(som,a)
#define resu_(som,a) resu(som,a)
  double inv_nb_som_elem=1./nb_som_elem;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<const_dimension; b++)
              G_e[b]+=G(glob,b);
            for (int a=0; a<nb_comp; a++)
              transp_loc(i1,a)=transporte_(glob,a);
          }
        G_e*=inv_nb_som_elem;
// Cerr<<" coucou "<<G_e<<finl;
// *10 !!!!!!!!!!!
        double vol_elem=volumes(elem);
        double inv_vol_elem=1./vol_elem;
        double pond2=volumes_thilde(elem)*inv_vol_elem*inv_vol_elem;
        if (transport_rhou)
          pond2 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
        double fpond2=f*pond2;
        if ((hourglass)&&(nb_som_elem==8)&&(hourglass_impl==0))
          {
            double pond3=f*dotproduct_array(G_e,G_e);
            if (transport_rhou) pond3 /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            if (is_not_lambda_unif)
              pond3+=lambda(elem);
            else
              pond3+=lambda(0,0);
            pond3*=volumes_thilde(elem)*inv_vol_elem*pow(vol_elem,0.3333333333333333);
            pond3*=hourglass;
            for (int a=0; a<nb_comp; a++)
              {
                double coef2d=0.042*pond3;
                double coef3d=coef2d*0.5;
                double t0=-coef2d*(transp_loc_(0,a)+transp_loc_(1,a)+transp_loc_(2,a)+transp_loc_(3,a)
                                   +transp_loc_(4,a)+transp_loc_(5,a)+transp_loc_(6,a)+transp_loc_(7,a));
                double t3d=0;
                for (int i=0; i<8; i++) t3d+=mcoef3d[i]*transp_loc_(i,a);
                t3d*=coef3d;
                double t3db=coef3d*(transp_loc_(0,a)-transp_loc_(1,a)+transp_loc_(3,a)-transp_loc_(2,a)
                                    -transp_loc_(4,a)+transp_loc_(5,a)-transp_loc_(7,a)+transp_loc_(6,a));
                if (!est_egal(t3d,t3db,1e-6)) assert(0);
                /*
                double t1=t0+coef2d*4.*(transp_loc_(0,a)+transp_loc_(7,a));
                double t2=t0+coef2d*4.*(transp_loc_(1,a)+transp_loc_(6,a));
                double t3=t0+coef2d*4.*(transp_loc_(3,a)+transp_loc_(4,a));
                double t4=t0+coef2d*4.*(transp_loc_(2,a)+transp_loc_(5,a));
                */
// if (elem==0) Cerr<<a<<" "<<t3d<<" iiiiii "<<t1<<" "<<pond3<<" "<<f<<finl;
                for (int i=0; i<8; i++)
                  resu_(elems(elem,i),a)-=mcoef3d[i]*t3d+t0+coef2d*4.*(transp_loc_(i,a)+transp_loc_(sommetoppose[i],a));
              }
          }
        {
          for (int yy=0; yy<nb_som_elem; yy++) ge_bij[yy]=0;
          if ((centre_impl==0)||(btd_impl==0))
            {
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double cb=0;
                  for (int b=0; b<const_dimension; b++)
                    cb+=G_e[b]*bij_(elem,i1,b);
                  ge_bij[i1]=cb;
                }
              for (int i1=0; i1<nb_som_elem; i1++)
                {
                  double pond=0;
                  if (centre_impl==0) pond=IPhi_thilde(elem,i1)*inv_vol_elem;
                  int glob=elems(elem,i1);
// pr=0;
                  for (int yy=0; yy<nb_comp; yy++) pr[yy]=0;
                  double cbbtd=pond;
                  if ((btd_impl==0)&&(type_op==amont))
                    cbbtd+=ge_bij[i1]*(fpond2);
                  for (int i2=0; i2<nb_som_elem; i2++)
                    {
                      const double cbi2=ge_bij[i2];
                      double coef=cbbtd*cbi2;
                      for (int a=0; a<nb_comp; a++)
                        pr[a]-=coef*transp_loc_(i2,a);
                    }
                  for (int a=0; a<nb_comp; a++)
                    resu_(glob,a)+=pr[a];
                }
            }
        }
      }
  fluent_.echange_espace_virtuel();
  return resu;
#undef bij_
#undef transp_loc_
#undef transporte_
#undef resu_
}
double Op_Conv_EF::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
< comme G2
Reimplemented from Op_Conv_EF_base.
Definition at line 1169 of file Op_Conv_EF.cpp.
References btd_, calcul_dt_stab_, coefficient_correcteur_supg_, Cout, dabs(), Objet_U::dimension, Champ_Don_base::dimensionner(), DMINFLOAT, Zone::domaine(), Op_EF_base::elem_contribue(), MorEqn::equation(), Process::exit(), finl, Operateur_Conv_base::fixer_dt_stab_conv(), Probleme_base::get_champ(), O_U_Ptr::le_nom(), Zone::les_elems(), Domaine::les_sommets(), max_ue_, min(), min_dx_, Process::mp_max(), Process::mp_min(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Equation_base::probleme(), ref_cast, ref_cast_non_const, DoubleVect::size(), valeur(), Ref_Champ_Inc_base::valeur(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), Op_Conv_EF_base::vitesse_, and Zone_dis_base::zone().
Referenced by Op_Conv_BTD_EF::coefficient_btd().
{
  if (calcul_dt_stab_==0) return  Operateur_base::calculer_dt_stab();
  const Champ_Inc_base& la_vitesse=vitesse_.valeur();
  const DoubleTab& G=la_vitesse.valeurs();
  int transport_rhou=0;
  if (vitesse_.le_nom()=="rho_u") transport_rhou=1;
  const DoubleTab& rho_elem=(transport_rhou==1 ? equation().probleme().get_champ("masse_volumique_melange").valeurs() : \
                             equation().probleme().get_champ("masse_volumique").valeurs());
  int is_not_rho_unif = (rho_elem.size() == 1 ? 0 : 1);
  const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
  const DoubleVect& valeurs_diffusivite = ref_cast(Operateur_Diff_base,equation().operateur(0).l_op_base()).diffusivite().valeurs();
  int is_not_lambda_unif = (valeurs_diffusivite.size() == 1 ? 0 : 1);
  int autre_eq=0;
  const DoubleVect& valeurs_diffusivite_p = ref_cast(Operateur_Diff_base,equation().probleme().equation(autre_eq).operateur(0).l_op_base()).diffusivite().valeurs();
  if (calcul_dt_stab_==2)
    {
      if (&valeurs_diffusivite_p == &valeurs_diffusivite)
        autre_eq=1;
    }
  const DoubleVect& valeurs_diffusivite_2 = ref_cast(Operateur_Diff_base,equation().probleme().equation(autre_eq).operateur(0).l_op_base()).diffusivite().valeurs();
  const DoubleTab& coord=zone_ef.zone().domaine().les_sommets();
  int nb_elem_tot=zone_ef.zone().nb_elem_tot();
  int nb_som_elem=zone_ef.zone().nb_som_elem();
  const IntTab& elems=zone_ef.zone().les_elems() ;
  ArrOfDouble G_e(dimension);
  max_ue_=1e-8 ; //!< comme G2
  min_dx_=1e37;
  double Max=0;
  double dt_l=0,dt2=0;
  for (int elem=0; elem<nb_elem_tot; elem++)
    if (elem_contribue(elem))
      {
        G_e=0;
        for (int i1=0; i1<nb_som_elem; i1++)
          {
            int glob=elems(elem,i1);
            for (int b=0; b<dimension; b++)
              G_e(b)+=G(glob,b);
          }
        G_e/=nb_som_elem;
// if (transport_rhou)  G_e/=rho_elem(elem);
        double ml=0;
        double dx2;
// pas de temps de diffusion !!
        double ml2=0;
        double vx[3];
        for (int d=0; d<3; d++)
          {
            dx2=dabs(coord(elems(elem,0),d)-coord(elems(elem,7),d));
            dx2+=dabs(coord(elems(elem,1),d)-coord(elems(elem,6),d));
            dx2+=dabs(coord(elems(elem,2),d)-coord(elems(elem,5),d));
            dx2+=dabs(coord(elems(elem,3),d)-coord(elems(elem,4),d));
            dx2*=0.25;
            dx2*=dx2;
            ml2+=dx2;
// double p=G_e(d)*G_e(d)/dx2;
            ml+=G_e(d)*G_e(d)/dx2;
            vx[d]=G_e(d)*G_e(d);
          }
        double diffu=(is_not_lambda_unif?valeurs_diffusivite(elem):valeurs_diffusivite(0));
        if (calcul_dt_stab_==2)
          {
            double diffu2=(is_not_lambda_unif?valeurs_diffusivite_2(elem):valeurs_diffusivite_2(0));
            if (diffu2<diffu)
              diffu=diffu2;
          }
        diffu /= (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
// horreur pour NR G2 cas clotaire
// diffu*=0.5;
// if (elem==0) Cerr<<"uu "<<diffu<<finl;
        if (transport_rhou)
          {
            double rho_e = (is_not_rho_unif ? rho_elem(elem) : rho_elem(0,0));
            double inv_rho2= rho_e*rho_e;
            inv_rho2=1./inv_rho2;
            ml*=inv_rho2;
            for (int d=0; d<dimension; d++)
              vx[d]*=inv_rho2;
          }
// le .5* c'est pour avoir le meme dt que g2 mais faux
        double dxe=sqrt(ml2);
        if (dxe<min_dx_)
          min_dx_=dxe;
        ml2=diffu/ml2;
        ml*=btd_;
        ml=sqrt(ml2*ml2+ml)+ml2+DMINFLOAT;
        /*      if (ml2>0)
        ml=ml/(sqrt(ml2*ml2+ml)-ml2);
        else ml=-1.;
        */
        if (ml > Max) Max=ml;
        double ue=sqrt(vx[0]+vx[1]+vx[2]);
        if (ue>max_ue_) max_ue_=ue;
        dt_l= 1./(Max+DMINFLOAT);
        if (elem==0) dt2=dt_l;
        if (btd_!=3.)
          {
            double dt0=dt2;
            double s=1.;
            while(s>0)
              {
                s=-1;
                for (int d=0; d<dimension; d++)
                  {
                    double c=vx[d]*dt0;
                    if (dabs(c)>1e-16)
                      s+=c/(2.*diffu  +c*btd_);
                  }
                if (s>0)
                  {
                    dt0*=0.9;
                    Cout<<elem<<" " <<dt_l<<" "<<s<<" "<<dt0<<finl;
                    exit();
                  }
              }
            dt2=min(dt2,dt0);
            dt_l=min(dt2,dt_l);
          }
      }
  min_dx_=mp_min(min_dx_);
  max_ue_=mp_max(max_ue_);
  coefficient_correcteur_supg_.dimensionner(1,1);
  coefficient_correcteur_supg_(0,0)=min_dx_/max_ue_;
  double dt_stab=dt_l;
  dt_stab = Process::mp_min(dt_stab);
// astuce pour contourner le type const de la methode
  Op_Conv_EF_base& op = ref_cast_non_const(Op_Conv_EF_base,*this);
  op.fixer_dt_stab_conv(dt_stab);
  return dt_stab;
}
double Op_Conv_EF::coefficient_btd () const [virtual]
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 181 of file Op_Conv_EF.cpp.
References Objet_U::dimension, MorEqn::equation(), f_lu_, Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
Referenced by ajouter_contribution_sous_cond(), ajouter_sous_cond_dim2_nbn4_nbdim1(), ajouter_sous_cond_dim2_nbn4_nbdim2(), ajouter_sous_cond_dim3_nbn8_nbdim1(), ajouter_sous_cond_dim3_nbn8_nbdim2(), and ajouter_sous_cond_gen().
{
  double dt=equation().schema_temps().pas_de_temps();
  double f=(dimension)*dt/(dimension-1);
  if (f_lu_>=0) f=f_lu_;
  return f;
}
void Op_Conv_EF::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF.
Definition at line 137 of file Op_Conv_EF.cpp.
References btd_hors_conv_, calcul_dt_stab_, MorEqn::equation(), hourglass_hors_conv_, and sub_type.
{
  Op_Conv_EF_base::completer();
  if (sub_type(Op_Diff_EF,equation().operateur(0).l_op_base()))
    {
      if (equation().schema_temps().diffusion_implicite())
        {
          btd_hors_conv_=1;
          hourglass_hors_conv_=1;
          calcul_dt_stab_=2;
        }
    }
  else
    {
      btd_hors_conv_=0;
      hourglass_hors_conv_=0;
    }
}
void Op_Conv_EF::contribue_au_second_membre (DoubleTab & resu) const
Definition at line 1315 of file Op_Conv_EF.cpp.
References ajouter_sous_cond(), btd_hors_conv_, btd_impl_, centre_impl_, MorEqn::equation(), hourglass_hors_conv_, and hourglass_impl_.
Referenced by contribuer_au_second_membre().
{
// on a rien implicite
  ajouter_sous_cond(equation().inconnue().valeurs(),resu,((btd_hors_conv_==1)||btd_impl_),((hourglass_hors_conv_==1)||hourglass_impl_),centre_impl_);
}
void Op_Conv_EF::contribue_au_second_membre_a_la_diffusion (DoubleTab & resu) const
Definition at line 1321 of file Op_Conv_EF.cpp.
References ajouter_sous_cond(), btd_hors_conv_, btd_impl_, MorEqn::equation(), hourglass_hors_conv_, and hourglass_impl_.
{
  ajouter_sous_cond(equation().inconnue().valeurs(),resu,((btd_hors_conv_==0)||btd_impl_),((hourglass_hors_conv_==0)||hourglass_impl_),1);
}
void Op_Conv_EF::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice des inconnues implicite.
Reimplemented from Operateur_base.
Definition at line 135 of file Op_Conv_EF.h.
References ajouter_contribution().
{
  ajouter_contribution(inco, matrice);
}
void Op_Conv_EF::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 144 of file Op_Conv_EF.h.
References contribue_au_second_membre().
{
  contribue_au_second_membre(resu);
}
Objet_U * Op_Conv_EF::cree_instance () [static]
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
void Op_Conv_EF::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice au moyen de la methode dimensionner de la classe
Op_EF_base.
Reimplemented from Operateur_base.
Definition at line 116 of file Op_Conv_EF.h.
References Op_Conv_EF_base::la_zcl_EF, Op_Conv_EF_base::la_zone_EF, Ref_Zone_Cl_EF::valeur(), and Ref_Zone_EF::valeur().
{
  Op_EF_base::dimensionner(la_zone_EF.valeur(),la_zcl_EF.valeur(), matrice);
}
int Op_Conv_EF::duplique () const [virtual]
Implements Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
double Op_Conv_EF::get_btd () const [inline]
Definition at line 76 of file Op_Conv_EF.h.
References btd_.
  {
    return btd_;
  }
const Champ_base & Op_Conv_EF::get_champ (const Motcle & nom) const [virtual]
Reimplemented from Operateur_base.
Definition at line 1326 of file Op_Conv_EF.cpp.
References coefficient_correcteur_supg_.
{
  if (nom=="coefficient_correcteur_supg")
    return coefficient_correcteur_supg_;
  return Op_Conv_EF_base::get_champ(nom);
}
const Type_info * Op_Conv_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
const Type_info * Op_Conv_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
void Op_Conv_EF::modifier_pour_Cl (Matrice_Morse & matrice, DoubleTab & secmem) const [inline, virtual]
On modifie le second membre et la matrice dans le cas des
conditions de dirichlet.
Reimplemented from Operateur_base.
Definition at line 126 of file Op_Conv_EF.h.
References Op_Conv_EF_base::la_zcl_EF, Op_Conv_EF_base::la_zone_EF, Ref_Zone_Cl_EF::valeur(), and Ref_Zone_EF::valeur().
{
  Op_EF_base::modifier_pour_Cl(la_zone_EF.valeur(),la_zcl_EF.valeur(), matrice, secmem);
}
Sortie & Op_Conv_EF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 82 of file Op_Conv_EF.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_EF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 89 of file Op_Conv_EF.cpp.
References amont, btd_, btd_impl_, centre, centre_impl_, Cerr, Process::exit(), f_lu_, finl, hourglass, hourglass_impl_, Objet_U::que_suis_je(), and type_op.
{
  btd_=3.;
  Motcle type_op_lu;
  s >> type_op_lu;
  if (!(type_op_lu=="amont") &&  !(type_op_lu=="centre")  &&  !(type_op_lu=="amont3")&&!(type_op_lu=="btd"))
    {
      Cerr << type_op_lu << " n'est pas compris par " << que_suis_je() << finl;
      Cerr << " choisir parmi : amont -btd - centre " << finl;
      exit();
    }
  if (type_op_lu=="centre")
    {
      type_op = centre;
    }
  if ((type_op_lu=="amont")||(type_op_lu=="amont3")||(type_op_lu=="btd"))
    {
      type_op = amont;
    }
  if ((type_op==amont)
      &&  (type_op_lu!="amont2"))
    {
      f_lu_=0.036585;
      hourglass=1;
      hourglass_impl_=1;
      btd_impl_=1;
      centre_impl_=1;
    }
  if (type_op_lu=="amont3")
    {
      s >> f_lu_;
// decommente  les 2 lognes
// centre_impl_=0;
// calcul_dt_stab_=1;
    }
  if  (type_op_lu=="btd")
    f_lu_=-1;
  return s ;
}
Op_Conv_EF & Op_Conv_EF::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
const Op_Conv_EF & Op_Conv_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
unsigned Op_Conv_EF::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 34 of file Op_Conv_EF.cpp.
Member Data Documentation
double Op_Conv_EF::btd_ [protected]
Definition at line 100 of file Op_Conv_EF.h.
Referenced by calculer_dt_stab(), Op_Conv_BTD_EF::coefficient_btd(), get_btd(), Op_Conv_SUPG_EF::readOn(), readOn(), and Op_Conv_BTD_EF::readOn().
int Op_Conv_EF::btd_hors_conv_ [protected]
Definition at line 84 of file Op_Conv_EF.h.
Referenced by ajouter(), ajouter_a_la_diffusion(), ajouter_contribution(), ajouter_contribution_a_la_diffusion(), completer(), contribue_au_second_membre(), contribue_au_second_membre_a_la_diffusion(), and Op_Conv_BTD_EF::Op_Conv_BTD_EF().
int Op_Conv_EF::btd_impl_ [protected]
Definition at line 83 of file Op_Conv_EF.h.
Referenced by ajouter_contribution(), ajouter_contribution_a_la_diffusion(), contribue_au_second_membre(), contribue_au_second_membre_a_la_diffusion(), Op_Conv_BTD_EF::Op_Conv_BTD_EF(), and readOn().
int Op_Conv_EF::calcul_dt_stab_ [protected]
Definition at line 87 of file Op_Conv_EF.h.
Referenced by calculer_dt_stab(), completer(), and Op_Conv_BTD_EF::Op_Conv_BTD_EF().
int Op_Conv_EF::centre_impl_ [protected]
flag pour savoir si les termes sont implicites
Definition at line 83 of file Op_Conv_EF.h.
Referenced by ajouter_contribution(), contribue_au_second_membre(), Op_Conv_BTD_EF::Op_Conv_BTD_EF(), and readOn().
Champ_Uniforme Op_Conv_EF::coefficient_correcteur_supg_ [mutable, protected]
Definition at line 92 of file Op_Conv_EF.h.
Referenced by calculer_dt_stab(), and get_champ().
double Op_Conv_EF::f_lu_ [protected]
Definition at line 85 of file Op_Conv_EF.h.
Referenced by coefficient_btd(), and readOn().
double Op_Conv_EF::hourglass [protected]
Definition at line 82 of file Op_Conv_EF.h.
Referenced by ajouter_contribution_sous_cond(), ajouter_sous_cond_dim2_nbn4_nbdim1(), ajouter_sous_cond_dim2_nbn4_nbdim2(), ajouter_sous_cond_dim3_nbn8_nbdim1(), ajouter_sous_cond_dim3_nbn8_nbdim2(), ajouter_sous_cond_gen(), Op_Conv_BTD_EF::Op_Conv_BTD_EF(), and readOn().
int Op_Conv_EF::hourglass_hors_conv_ [protected]
Definition at line 84 of file Op_Conv_EF.h.
Referenced by ajouter(), ajouter_a_la_diffusion(), ajouter_contribution(), ajouter_contribution_a_la_diffusion(), completer(), contribue_au_second_membre(), contribue_au_second_membre_a_la_diffusion(), and Op_Conv_BTD_EF::Op_Conv_BTD_EF().
int Op_Conv_EF::hourglass_impl_ [protected]
Definition at line 83 of file Op_Conv_EF.h.
Referenced by ajouter_contribution(), ajouter_contribution_a_la_diffusion(), contribue_au_second_membre(), contribue_au_second_membre_a_la_diffusion(), Op_Conv_BTD_EF::Op_Conv_BTD_EF(), and readOn().
const Type_info Op_Conv_EF::info_obj [static]
Reimplemented from Op_Conv_EF_base.
Reimplemented in Op_Conv_BTD_EF, and Op_Conv_SUPG_EF.
Definition at line 48 of file Op_Conv_EF.h.
double Op_Conv_EF::max_ue_ [mutable, protected]
Definition at line 91 of file Op_Conv_EF.h.
Referenced by calculer_dt_stab(), and Op_Conv_SUPG_EF::coefficient_btd().
double Op_Conv_EF::min_dx_ [mutable, protected]
Definition at line 91 of file Op_Conv_EF.h.
Referenced by calculer_dt_stab(), and Op_Conv_SUPG_EF::coefficient_btd().
type_operateur Op_Conv_EF::type_op [protected]
Definition at line 88 of file Op_Conv_EF.h.
Referenced by ajouter_contribution_sous_cond(), ajouter_sous_cond_dim2_nbn4_nbdim1(), ajouter_sous_cond_dim2_nbn4_nbdim2(), ajouter_sous_cond_dim3_nbn8_nbdim1(), ajouter_sous_cond_dim3_nbn8_nbdim2(), ajouter_sous_cond_gen(), Op_Conv_BTD_EF::Op_Conv_BTD_EF(), and readOn().
The documentation for this class was generated from the following files:
src/EF/Operateurs/Op_Conv_EF.h
src/EF/Operateurs/Op_Conv_EF.cpp