TRUST: OctreeRoot Class Reference
OctreeRoot Class Reference
Classe OctreeRoot.
#include <Octree.h>
Public Member Functions
~OctreeRoot ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
OctreeRoot ()
OctreeRoot (const Zone &z)
OctreeRoot (const OctreeRoot &oc)
int rang_sommet (double x, double y=0, double z=0) const
int rang_arete (double x, double y=0, double z=0) const
int rang_elem (double x, double y=0, double z=0) const
int rang_elem_depuis (int prems, double x, double y=0, double z=0) const
int rang_sommet (const DoubleTab &, ArrOfInt &) const
int rang_arete (const DoubleTab &, ArrOfInt &) const
int rang_elem (const DoubleTab &, ArrOfInt &) const
int rang_elem_depuis (const DoubleTab &, const ArrOfInt &, ArrOfInt &) const
void rang_elems_sommet (ArrOfInt &, double x, double y=0, double z=0) const
const Zone & zone () const override
Renvoie la zone associe a l'octree.
void associer_Zone (const Zone &)
Associe une zone a l'octree.
void construire (int reel=0)
int construit () const
Renvoie vrai si la zone associee a l'octree
est non nulle.
void invalide ()
int reel () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Octree
Octree ()
virtual ~Octree ()
Destructeur: appelle Octree::detruire().
Octree (const Octree &)
Octree (int n, Octree *mon_pere, const ArrOfInt &val, const OctreeLoc &loc)
virtual int rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const
virtual int rang_elem_depuis_loc (const OctreeLoc &, int prems, double x, double y=0, double z=0) const
virtual const Zone & zone () const
Renvoie une reference sur la zone associe a l'octree.
void construire (int, const ArrOfInt &, const OctreeLoc &, Octree *p=0)
int niveau () const
virtual int taille () const
Renvoie la taille de l'octree.
virtual Sortie & printOn (Sortie &is) const
virtual Entree & readOn (Entree &is)
NE FAIT RIEN.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static OctreeRoot & self_cast (Objet_U &)
static const OctreeRoot & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Member Functions inherited from Octree
static int nombre_d_octrees ()
Renvoie le nombre d'octree.
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Octree::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Octree::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Octree
void detruire ()
Detruit l'octree.
Methode appelee par le destructeur.
void ranger_elem_1D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double)
void ranger_elem_2D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double, double)
void ranger_elem_3D (ArrOfInt &, int, int, int, const DoubleTab &, const IntTab &, ArrOfInt &, IntVects &, double, double, double)
double get_epsilon () const
Protected Attributes
Ref_Zone la_zone
OctreeLoc loc
int valid_
int reel_
Protected Attributes inherited from Octree
Octree ** les_octrees
Octree * pere
Detailed Description
Classe OctreeRoot.
Definition at line 97 of file Octree.h.
Constructor & Destructor Documentation
~OctreeRoot()
OctreeRoot::~OctreeRoot ()
Definition at line 27 of file Octree.cpp.
OctreeRoot() [1/3]
OctreeRoot::OctreeRoot () inline
Definition at line 102 of file Octree.h.
:valid_(0) {}
OctreeRoot() [2/3]
OctreeRoot::OctreeRoot (const Zone & z) inline
Definition at line 103 of file Octree.h.
  {
    associer_Zone(z);
    construire();
  }
References associer_Zone(), and construire().
OctreeRoot() [3/3]
OctreeRoot::OctreeRoot (const OctreeRoot & oc) inline
Definition at line 108 of file Octree.h.
                                  : Objet_U(oc),Octree(oc)
  {
    if(oc.construit())
      {
        associer_Zone(oc.zone());
        construire();
      }
    else
      valid_=0;
  }
References associer_Zone(), construire(), construit(), valid_, and zone().
Member Function Documentation
associer_Zone()
void OctreeRoot::associer_Zone (const Zone & z)
Associe une zone a l'octree.
Definition at line 999 of file Octree.cpp.
{
  la_zone=z;
}
References la_zone.
Referenced by Zone::construit_octree(), and OctreeRoot().
construire()
void OctreeRoot::construire (int reel = 0)
Definition at line 1018 of file Octree.cpp.
{
  detruire();
  valid_=1;
  reel_=reel_prec;
  pere=0;
  const Zone& z=zone();
  const Domaine& dom=z.domaine();
  {
// Calcul du min et du max des coordonnees dans chaque direction
    double min[3] = { 1e30, 1e30, 1e30 };
    double max[3] = {-1e30,-1e30,-1e30 };
    int i;
    const DoubleTab& tab = dom.coord_sommets();
// tot sinon bouding box trop petite
// peut etre teste reel_ ...
    const int n = tab.dimension_tot(0);
    const int dim = tab.dimension(1);
    assert(dim <= 3);
    for (i = 0; i < n; i++)
      {
        int j;
        for (j = 0; j < 3; j++)
          {
            if (j>=dim) break;
            double x = tab(i,j);
            if (x < min[j])
              min[j] = x;
            if (x > max[j])
              max[j] = x;
          }
      }
    loc.xmin = min[0];
    loc.xmax = max[0];
    if (axi)
      {
        loc.ymin = 0.;
        loc.ymax = 2. * M_PI;
      }
    else
      {
        loc.ymin = min[1];
        loc.ymax = max[1];
      }
    if (dim > 2)
      {
        loc.zmin = min[2];
        loc.zmax = max[2];
      }
    else
      {
        loc.zmin = 0.;
        loc.zmax = 1.;
      }
  }
  int nb_elem=z.nb_elem_tot();
  if(reel_prec)
    nb_elem=z.nb_elem();
  ArrOfInt SousTab(nb_elem);
  for(int i=0; i<nb_elem; i++)
    SousTab[i]=i;
  Octree::construire(Octree::nombre_d_octrees(), SousTab, loc);
  Cerr << "Construction of the OctreeRoot OK " << finl;
}
References Objet_U::axi, Cerr, Octree::construire(), Domaine::coord_sommets(), Octree::detruire(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Zone::domaine(), finl, loc, M_PI, Zone::nb_elem(), Zone::nb_elem_tot(), Octree::nombre_d_octrees(), Octree::pere, reel_, valid_, OctreeLoc::xmax, OctreeLoc::xmin, OctreeLoc::ymax, OctreeLoc::ymin, OctreeLoc::zmax, OctreeLoc::zmin, and zone().
Referenced by Zone::construit_octree(), and OctreeRoot().
construit()
int OctreeRoot::construit () const
Renvoie vrai si la zone associee a l'octree
est non nulle.
Returns
int
Signification: code de retour propage
Contraintes:
Definition at line 1575 of file Octree.cpp.
{
  if((la_zone.non_nul()==0)||(valid_!=1))
// L'Octree n'est pas construit ou la zone est nulle
    return 0;
  else
    return 1;
}
References la_zone, O_U_Ptr::non_nul(), and valid_.
Referenced by Zone::chercher_elements(), Zone::construit_octree(), and OctreeRoot().
cree_instance()
Objet_U * OctreeRoot::cree_instance () static
Definition at line 27 of file Octree.cpp.
duplique()
int OctreeRoot::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Octree.cpp.
get_info()
const Type_info * OctreeRoot::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Octree.cpp.
info()
const Type_info * OctreeRoot::info () static
Definition at line 27 of file Octree.cpp.
invalide()
void OctreeRoot::invalide ()
Definition at line 1584 of file Octree.cpp.
{
  if(valid_!=0)
    {
      Cerr << "Invalidation of the Octree" << finl;
      valid_ = 0;
      detruire();
    }
}
References Cerr, Octree::detruire(), finl, and valid_.
printOn()
Sortie & OctreeRoot::printOn (Sortie & os) const override protected virtual
Simple appel a: Octree::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Octree.
Definition at line 95 of file Octree.cpp.
{
  return Octree::printOn(os);
}
References Octree::printOn().
rang_arete() [1/2]
int OctreeRoot::rang_arete (const DoubleTab & positions, ArrOfInt & aretes) const
Returns
int
Signification:
Contraintes:
Definition at line 1370 of file Octree.cpp.
{
  int sz=positions.dimension(0);
  assert(positions.dimension(1)==Objet_U::dimension);
  aretes.resize_array(sz);
  for(int i=0; i<sz; i++)
    {
      double x=0, y=0, z=0;
      switch(Objet_U::dimension)
        {
        case 1:
          x=positions(i,0);
          break;
        case 2:
          x=positions(i,0);
          y=positions(i,1);
          break;
        case 3:
          x=positions(i,0);
          y=positions(i,1);
          z=positions(i,2);
          break;
        default:
          Cerr << "Error in OctreeRoot::rang_arete" << finl;
          exit();
        }
      aretes[i]=rang_arete(x,y,z);
    }
  return 1;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, rang_arete(), and TRUSTArray< _TYPE_ >::resize_array().
rang_arete() [2/2]
int OctreeRoot::rang_arete (double x, double y = 0, double z = 0) const
Returns
int
Signification:
Contraintes:
Definition at line 1185 of file Octree.cpp.
{
// Recherche l'element contenant le point x,y,z:
  int elem=rang_elem(x, y, z);
  const IntTab& elem_aretes=zone().elem_aretes();
  if (elem>=elem_aretes.dimension(0)) return -2;
  if (elem != -1 && elem<elem_aretes.dimension(0))
    {
// Boucle sur les aretes de l'element
      double epsilon=get_epsilon();
      const IntTab& aretes_som=zone().aretes_som();
      const DoubleTab& coord=zone().domaine().coord_sommets();
      int nb_aretes_elem=elem_aretes.dimension(1);
      for(int i=0; i<nb_aretes_elem; i++)
        {
// On boucle sur les aretes de l'element pour trouver celle
// dont le centre de gravite coincide avec le point x,y,z
          int arete=elem_aretes(elem,i);
          int s0=aretes_som(arete,0);
          int s1=aretes_som(arete,1);
          switch(Objet_U::dimension)
            {
            case 3:
              if((std::fabs(0.5*(coord(s0,0)+coord(s1,0))-x)<epsilon) &&
                  (std::fabs(0.5*(coord(s0,1)+coord(s1,1))-y)<epsilon) &&
                  (std::fabs(0.5*(coord(s0,2)+coord(s1,2))-z)<epsilon))
                return arete;
              break;
            default:
              Cerr << "Error in OctreeRoot::rang_elem" << finl;
              exit();
              return -1;
            }
        }
      return -1;
    }
  else
// Cerr << "On a pas trouve d'arete a ces coordonnees" << finl;
    return -1;
}
References Zone::aretes_som(), Cerr, Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone::elem_aretes(), Process::exit(), finl, Octree::get_epsilon(), rang_elem(), and zone().
Referenced by Zone::chercher_aretes(), and rang_arete().
rang_elem() [1/2]
int OctreeRoot::rang_elem (const DoubleTab & positions, ArrOfInt & elems) const
Returns
int
Signification:
Contraintes:
Definition at line 1419 of file Octree.cpp.
{
  int sz=positions.dimension(0);
  assert(positions.dimension(1)==Objet_U::dimension);
  elems.resize_array(sz);
  for(int i=0; i<sz; i++)
    {
      double x=0, y=0, z=0;
      switch(Objet_U::dimension)
        {
        case 1:
          x=positions(i,0);
          break;
        case 2:
          x=positions(i,0);
          y=positions(i,1);
          break;
        case 3:
          x=positions(i,0);
          y=positions(i,1);
          z=positions(i,2);
          break;
        default:
          Cerr << "Error in OctreeRoot::rang_elem" << finl;
          assert(0);
          exit();
        }
      elems[i]=rang_elem(x,y,z);
    }
  return 1;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, rang_elem(), and TRUSTArray< _TYPE_ >::resize_array().
rang_elem() [2/2]
int OctreeRoot::rang_elem (double x, double y = 0, double z = 0) const
Returns
int
Signification:
Contraintes:
Definition at line 1249 of file Octree.cpp.
{
  double epsilon=get_epsilon();
  if(       (x<loc.xmin-epsilon) || (y<loc.ymin-epsilon) || (z<loc.zmin-epsilon)
            ||   (x>loc.xmax+epsilon) || (y>loc.ymax+epsilon) || (z>loc.zmax+epsilon)   )
    return -1;
  return Octree::rang_elem_loc(loc, x, y, z);
}
References Octree::get_epsilon(), loc, Octree::rang_elem_loc(), OctreeLoc::xmax, OctreeLoc::xmin, OctreeLoc::ymax, OctreeLoc::ymin, OctreeLoc::zmax, and OctreeLoc::zmin.
Referenced by Zone::chercher_elements(), rang_arete(), rang_elem(), and rang_sommet().
rang_elem_depuis() [1/2]
int OctreeRoot::rang_elem_depuis (const DoubleTab & positions, const ArrOfInt & prems, ArrOfInt & elems) const
Definition at line 1475 of file Octree.cpp.
{
  int sz=positions.dimension(0);
  assert(positions.dimension(1)==Objet_U::dimension);
  elems.resize_array(sz);
  for(int i=0; i<sz; i++)
    {
      double x=0, y=0, z=0;
      switch(Objet_U::dimension)
        {
        case 1:
          x=positions(i,0);
          break;
        case 2:
          x=positions(i,0);
          y=positions(i,1);
          break;
        case 3:
          x=positions(i,0);
          y=positions(i,1);
          z=positions(i,2);
          break;
        default:
          Cerr << "Error in OctreeRoot::rang_elem_depuis" << finl;
          assert(0);
          exit();
        }
      elems[i]=rang_elem_depuis(prems[i],x,y,z);
    }
  return 1;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, rang_elem_depuis(), and TRUSTArray< _TYPE_ >::resize_array().
rang_elem_depuis() [2/2]
int OctreeRoot::rang_elem_depuis (int prems, double x, double y = 0, double z = 0) const
Definition at line 1287 of file Octree.cpp.
{
  double epsilon=get_epsilon();
  if(       (x<loc.xmin-epsilon) || (y<loc.ymin-epsilon) || (z<loc.zmin-epsilon)
            ||   (x>loc.xmax+epsilon) || (y>loc.ymax+epsilon) || (z>loc.zmax+epsilon)   )
    return -1;
  return Octree::rang_elem_depuis_loc(loc, prems, x, y, z);
}
References Octree::get_epsilon(), loc, Octree::rang_elem_depuis_loc(), OctreeLoc::xmax, OctreeLoc::xmin, OctreeLoc::ymax, OctreeLoc::ymin, OctreeLoc::zmax, and OctreeLoc::zmin.
Referenced by rang_elem_depuis().
rang_elems_sommet()
void OctreeRoot::rang_elems_sommet (ArrOfInt & elements, double x, double y = 0, double z = 0) const
Definition at line 1536 of file Octree.cpp.
{
  RTabInt els;
  int fini=0;
  int i=0;
  int el=0;
  while(fini==0)
    {
      el = Octree::rang_elem_depuis_loc(loc, el, x, y, z);
      if(el==-1)
        fini=1;
      else
        {
          els.add(el);
          i++;
          el++;
        }
    }
  elements.resize_array(i);
  for(int j=0; j<i; j++)
    elements[j] = els[j];
}
References RTabInt::add(), loc, Octree::rang_elem_depuis_loc(), and TRUSTArray< _TYPE_ >::resize_array().
Referenced by Champ_front_recyclage::initialiser(), Perte_Charge_Singuliere::lire_surfaces(), and Zone::rang_elems_sommet().
rang_sommet() [1/2]
int OctreeRoot::rang_sommet (const DoubleTab & positions, ArrOfInt & sommets) const
Returns
int
Signification:
Contraintes:
Definition at line 1315 of file Octree.cpp.
{
  int sz=positions.dimension(0);
  assert(positions.dimension(1)==Objet_U::dimension);
  sommets.resize_array(sz);
  for(int i=0; i<sz; i++)
    {
      double x=0, y=0, z=0;
      switch(Objet_U::dimension)
        {
        case 1:
          x=positions(i,0);
          break;
        case 2:
          x=positions(i,0);
          y=positions(i,1);
          break;
        case 3:
          x=positions(i,0);
          y=positions(i,1);
          z=positions(i,2);
          break;
        default:
          Cerr << "Error in OctreeRoot::rang_sommet" << finl;
          assert(0);
          exit();
        }
      sommets[i]=rang_sommet(x,y,z);
    }
  return 1;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, rang_sommet(), and TRUSTArray< _TYPE_ >::resize_array().
rang_sommet() [2/2]
int OctreeRoot::rang_sommet (double x, double y = 0, double z = 0) const
Returns
int
Signification:
Contraintes:
Definition at line 1110 of file Octree.cpp.
{
  int elem=rang_elem(x, y, z);
  if (elem != -1)
    {
      const Zone& zo=zone();
      const Domaine& dom=zo.domaine();
      int nb_som_elem=zo.nb_som_elem();
      double epsilon=get_epsilon();
      for(int i=0; i<nb_som_elem; i++)
        {
// for i
          int sommet=zo.sommet_elem(elem,i);
          if(sommet<0)
            {
              Cerr << "This is not a mesh !" << finl;
              Cerr << zo << finl;
              exit();
            }
          switch(Objet_U::dimension)
            {
// switch
            case 1:
              if(std::fabs(dom.coord(sommet,0)-x)<epsilon)
                return sommet;
              break;
            case 2:
              if((std::fabs(dom.coord(sommet,0)-x)<epsilon) &&
                  (std::fabs(dom.coord(sommet,1)-y)<epsilon))
                return sommet;
              break;
            case 3:
              if((std::fabs(dom.coord(sommet,0)-x)<epsilon) &&
                  (std::fabs(dom.coord(sommet,1)-y)<epsilon) &&
                  (std::fabs(dom.coord(sommet,2)-z)<epsilon))
                return sommet;
              break;
            default:
              Cerr << "Error in OctreeRoot::rang_sommet" << finl;
              assert(0);
              exit();
              return -1;
            }
        }
      return -1;
    }
  else
// Cerr << "On a pas trouve de sommet a ces coordonnees" << finl;
    return -1;
}
References Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), Process::exit(), finl, Octree::get_epsilon(), Zone::nb_som_elem(), rang_elem(), Zone::sommet_elem(), and zone().
Referenced by Zone::chercher_sommets(), and rang_sommet().
readOn()
Entree & OctreeRoot::readOn (Entree & is) override protected virtual
Simple appel a: Octree::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Octree.
Definition at line 115 of file Octree.cpp.
{
  return Octree::readOn(is);
}
References Octree::readOn().
reel()
int OctreeRoot::reel () const inline
Definition at line 142 of file Octree.h.
{
  return reel_;
}
References reel_.
Referenced by Zone::construit_octree().
self_cast() [1/2]
const OctreeRoot & OctreeRoot::self_cast (const Objet_U & r) static
Definition at line 27 of file Octree.cpp.
self_cast() [2/2]
OctreeRoot & OctreeRoot::self_cast (Objet_U & r) static
Definition at line 27 of file Octree.cpp.
taille_memoire()
unsigned OctreeRoot::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Octree.cpp.
zone()
const Zone & OctreeRoot::zone () const override virtual
Renvoie la zone associe a l'octree.
Returns
Zone&
Signification: la zone associe a l'octree
Contraintes: reference constante
Reimplemented from Octree.
Definition at line 979 of file Octree.cpp.
{
  return la_zone.valeur();
}
References la_zone, and Ref_Zone::valeur().
Referenced by construire(), OctreeRoot(), rang_arete(), and rang_sommet().
Member Data Documentation
info_obj
const Type_info OctreeRoot::info_obj static
Definition at line 99 of file Octree.h.
la_zone
Ref_Zone OctreeRoot::la_zone protected
Definition at line 136 of file Octree.h.
Referenced by associer_Zone(), construit(), and zone().
loc
OctreeLoc OctreeRoot::loc protected
Definition at line 137 of file Octree.h.
Referenced by construire(), rang_elem(), rang_elem_depuis(), and rang_elems_sommet().
reel_
int OctreeRoot::reel_ protected
Definition at line 139 of file Octree.h.
Referenced by construire(), and reel().
valid_
int OctreeRoot::valid_ protected
Definition at line 138 of file Octree.h.
Referenced by construire(), construit(), invalide(), and OctreeRoot().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Octree.h
src/Kernel/Geometrie/Octree.cpp