TRUST: Neumann_sortie_libre Class Reference
Neumann_sortie_libre Class Reference
classe Neumann_sortie_libre
Cette classe represente une frontiere ouverte sans vitesse imposee
Pour les equations de Navier_Stokes on impose necessairement
la pression sur une telle frontiere
Pour traiter l'hydraulique, on derive donc de la classe
Neumann_sortie_libre la classe Sortie_libre_pression_imposee
Les conditions aux limites de type Neumann_sortie_libre ou des
types derives se traduisent par des flux diffusifs nuls.
En revanche, le traitement des flux convectifs impose de connaitre
le champ convecte a l'exterieur de la frontiere en cas de re-entree
de fluide. C'est pourquoi la classe porte un Champ_front<br>(membre le_champ_ext).
Dans les operateurs de calcul, les conditions aux limites
de type Neumann_sortie_libre et des types derives seront traites
de maniere identique
#include <Neumann_sortie_libre.h>
Public Member Functions
Neumann_sortie_libre ()
~Neumann_sortie_libre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const DoubleTab & tab_ext () const override
DoubleTab & tab_ext () override
double val_ext (int i) const override
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
double val_ext (int i, int j) const override
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
Public Member Functions inherited from Neumann_val_ext
Neumann_val_ext ()
~Neumann_val_ext () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual const DoubleTab & tab_ext () const =0
virtual DoubleTab & tab_ext ()=0
virtual double val_ext (int i) const =0
virtual double val_ext (int i, int j) const =0
Public Member Functions inherited from Neumann
Neumann ()
~Neumann () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double flux_impose (int i) const
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
virtual double flux_impose (int i, int j) const
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Neumann_sortie_libre & self_cast (Objet_U &)
static const Neumann_sortie_libre & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann_val_ext
static const Type_info * info ()
static Neumann_val_ext & self_cast (Objet_U &)
static const Neumann_val_ext & self_cast (const Objet_U &)
Static Public Member Functions inherited from Neumann
static const Type_info * info ()
static Neumann & self_cast (Objet_U &)
static const Neumann & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Neumann_val_ext
static const Type_info info_obj
Static Public Attributes inherited from Neumann
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Cond_lim_base::readOn(Entree&)
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_front le_champ_ext
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Neumann_sortie_libre
Cette classe represente une frontiere ouverte sans vitesse imposee
Pour les equations de Navier_Stokes on impose necessairement
la pression sur une telle frontiere
Pour traiter l'hydraulique, on derive donc de la classe
Neumann_sortie_libre la classe Sortie_libre_pression_imposee
Les conditions aux limites de type Neumann_sortie_libre ou des
types derives se traduisent par des flux diffusifs nuls.
En revanche, le traitement des flux convectifs impose de connaitre
le champ convecte a l'exterieur de la frontiere en cas de re-entree
de fluide. C'est pourquoi la classe porte un Champ_front<br>(membre le_champ_ext).
Dans les operateurs de calcul, les conditions aux limites
de type Neumann_sortie_libre et des types derives seront traites
de maniere identique
Definition at line 43 of file Neumann_sortie_libre.h.
Constructor & Destructor Documentation
Neumann_sortie_libre()
Neumann_sortie_libre::Neumann_sortie_libre ()
Definition at line 21 of file Neumann_sortie_libre.cpp.
~Neumann_sortie_libre()
Neumann_sortie_libre::~Neumann_sortie_libre ()
Definition at line 21 of file Neumann_sortie_libre.cpp.
Member Function Documentation
associer_fr_dis_base()
void Neumann_sortie_libre::associer_fr_dis_base (const Frontiere_dis_base & fr) override virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Reimplemented from Cond_lim_base.
Definition at line 159 of file Neumann_sortie_libre.cpp.
{
  Cond_lim_base::associer_fr_dis_base(fr);
  assert(le_champ_ext.non_nul());
  le_champ_ext->associer_fr_dis_base(fr);
  modifier_val_imp = 0;
}
References Champ_front::associer_fr_dis_base(), Cond_lim_base::associer_fr_dis_base(), le_champ_ext, Cond_lim_base::modifier_val_imp, and O_U_Ptr::non_nul().
avancer()
int Neumann_sortie_libre::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Definition at line 279 of file Neumann_sortie_libre.cpp.
{
  return Neumann::avancer(temps)
         && le_champ_ext->avancer(temps);
}
References Cond_lim_base::avancer(), and le_champ_ext.
changer_temps_futur()
void Neumann_sortie_libre::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Cond_lim_base.
Definition at line 273 of file Neumann_sortie_libre.cpp.
{
  Neumann::changer_temps_futur(temps,i);
  le_champ_ext->changer_temps_futur(temps,i);
}
References Cond_lim_base::changer_temps_futur(), and le_champ_ext.
compatible_avec_eqn()
int Neumann_sortie_libre::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_sortie_libre sont compatibles
avec une equation dont le domaine est la Thermique, le Transport_Keps,
la Concentration, la Fraction_massique ou bien indetermine.
Returns
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Reimplemented in Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 215 of file Neumann_sortie_libre.cpp.
{
  Motcle dom_app=eqn.domaine_application();
  Motcle KEPS               ="Transport_Keps";
  Motcle KEPS_V2            ="Transport_Keps_V2";
  Motcle K_Eps_Bas_Re       ="Transport_Keps_Bas_Re";
  Motcle K_Eps_Rea          ="Transport_Keps_Rea";
  Motcle Thermique          ="Thermique";
  Motcle Thermique_H        ="Thermique_H";
  Motcle Concentration      ="Concentration";
  Motcle Fraction_massique  ="Fraction_massique";
  Motcle Fraction_volumique ="Fraction_volumique";
  Motcle V2                 ="Transport_V2";
  Motcle indetermine        ="indetermine";
  Motcle turbulence         = "Turbulence";
  Motcle aire_interfaciale  = "Interfacial_area";
  if ( (dom_app==KEPS) || (dom_app==K_Eps_Bas_Re) || (dom_app==K_Eps_Rea) || (dom_app==indetermine) ||
       (dom_app==Thermique) || (dom_app==Concentration) ||
       (dom_app==Thermique_H) || (dom_app==V2) || (dom_app==KEPS_V2) ||
       (dom_app==Fraction_massique) || (dom_app==Fraction_volumique) || (dom_app == turbulence) || (dom_app == aire_interfaciale))
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
cree_instance()
Objet_U * Neumann_sortie_libre::cree_instance () static
Definition at line 21 of file Neumann_sortie_libre.cpp.
duplique()
int Neumann_sortie_libre::duplique () const override virtual
Implements Objet_U.
Reimplemented in Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 21 of file Neumann_sortie_libre.cpp.
fixer_nb_valeurs_temporelles()
void Neumann_sortie_libre::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Cond_lim_base.
Definition at line 255 of file Neumann_sortie_libre.cpp.
{
  Neumann::fixer_nb_valeurs_temporelles(nb_cases);
  le_champ_ext->fixer_nb_valeurs_temporelles(nb_cases);
}
References Cond_lim_base::fixer_nb_valeurs_temporelles(), and le_champ_ext.
get_info()
const Type_info * Neumann_sortie_libre::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_val_ext.
Reimplemented in Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 21 of file Neumann_sortie_libre.cpp.
info()
const Type_info * Neumann_sortie_libre::info () static
Definition at line 21 of file Neumann_sortie_libre.cpp.
initialiser()
int Neumann_sortie_libre::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Cond_lim_base.
Reimplemented in Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 151 of file Neumann_sortie_libre.cpp.
{
  Cond_lim_base::initialiser(temps);
  assert(le_champ_ext.non_nul());
  return le_champ_ext->initialiser(temps,zone_Cl_dis().equation().inconnue());
  return 1;
}
References Cond_lim_base::initialiser(), le_champ_ext, O_U_Ptr::non_nul(), and Cond_lim_base::zone_Cl_dis().
mettre_a_jour()
void Neumann_sortie_libre::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Cond_lim_base.
Reimplemented in Sortie_libre_Gradient_Pression_libre_VEF, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, and Sortie_libre_Pression_imposee_Orlansky.
Definition at line 261 of file Neumann_sortie_libre.cpp.
{
  Neumann::mettre_a_jour(temps);
  le_champ_ext->mettre_a_jour(temps);
}
References le_champ_ext, Champ_front::mettre_a_jour(), and Cond_lim_base::mettre_a_jour().
printOn()
Sortie & Neumann_sortie_libre::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann_val_ext.
Reimplemented in Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 38 of file Neumann_sortie_libre.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Neumann_sortie_libre::readOn (Entree & s) override protected virtual
Type le_champ_front en "Champ_front_uniforme".
Lit les valeurs du champ exterieur si les conditions
aux limites sont specifiees: "T_ext", "C_ext", "Y_ext", "K_Eps_ext" ou "F_M_ext"
Produit une erreur sinon.
Returns
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann_val_ext.
Reimplemented in Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 61 of file Neumann_sortie_libre.cpp.
{
// le_champ_front.typer("Champ_front_uniforme");
  Motcle motlu;
  Motcles les_motcles(13);
  {
    les_motcles[0] = "T_ext";
    les_motcles[1] = "C_ext";
    les_motcles[2] = "K_Eps_ext";
    les_motcles[3] = "F_M_ext";
    les_motcles[4] = "Fluctu_Temperature_ext";
    les_motcles[5] = "Flux_Chaleur_Turb_ext";
    les_motcles[6] = "V2_ext";
    les_motcles[7] = "Y_ext";
    les_motcles[8] = "A_ext";
    les_motcles[9] = "k_ext";
    les_motcles[10] = "tau_ext";
    les_motcles[11] = "omega_ext";
    les_motcles[12] = "k_WIT_ext";
    les_motcles[12] = "a_i_ext";
  }
  s >> motlu;
  int rang = les_motcles.search(motlu);
  if (rang >= 0) s >> le_champ_ext;
  else
    {
      Cerr << "Erreur a la lecture de la condition aux limites de type: " << finl;
      Cerr << que_suis_je() << finl;
      Cerr << "On attendait " << les_motcles << " a la place de " <<  motlu << finl;
      exit();
    }
  le_champ_front = le_champ_ext;
  return s;
}
References Cerr, Process::exit(), finl, le_champ_ext, Cond_lim_base::le_champ_front, Objet_U::que_suis_je(), and Motcles::search().
reculer()
int Neumann_sortie_libre::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Definition at line 285 of file Neumann_sortie_libre.cpp.
{
  return Neumann::reculer(temps)
         && le_champ_ext->reculer(temps);
}
References le_champ_ext, and Cond_lim_base::reculer().
self_cast() [1/2]
const Neumann_sortie_libre & Neumann_sortie_libre::self_cast (const Objet_U & r) static
Definition at line 21 of file Neumann_sortie_libre.cpp.
self_cast() [2/2]
Neumann_sortie_libre & Neumann_sortie_libre::self_cast (Objet_U & r) static
Definition at line 21 of file Neumann_sortie_libre.cpp.
set_temps_defaut()
void Neumann_sortie_libre::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Cond_lim_base.
Definition at line 267 of file Neumann_sortie_libre.cpp.
{
  Neumann::set_temps_defaut(temps);
  le_champ_ext->set_temps_defaut(temps);
}
References le_champ_ext, and Cond_lim_base::set_temps_defaut().
tab_ext() [1/2]
const DoubleTab & Neumann_sortie_libre::tab_ext () const override virtual
Implements Neumann_val_ext.
Definition at line 245 of file Neumann_sortie_libre.cpp.
{
  return le_champ_ext.valeurs();
}
References le_champ_ext, and Champ_front::valeurs().
tab_ext() [2/2]
DoubleTab & Neumann_sortie_libre::tab_ext () override virtual
Implements Neumann_val_ext.
Definition at line 250 of file Neumann_sortie_libre.cpp.
{
  return le_champ_ext.valeurs();
}
References le_champ_ext, and Champ_front::valeurs().
taille_memoire()
unsigned Neumann_sortie_libre::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Sortie_libre_pression_imposee, Sortie_libre_pression_moyenne_imposee, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose_VEF, and Sortie_libre_Gradient_Pression_libre_VEF.
Definition at line 21 of file Neumann_sortie_libre.cpp.
val_ext() [1/2]
double Neumann_sortie_libre::val_ext (int i) const override virtual
Renvoie la valeur de la i-eme composante
du champ impose a l'exterieur de la frontiere.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Implements Neumann_val_ext.
Definition at line 136 of file Neumann_sortie_libre.cpp.
{
  if (le_champ_ext.valeurs().size()==1)
    return le_champ_ext(0,0);
  else if (le_champ_ext.valeurs().dimension(1)==1)
    return le_champ_ext(i,0);
  else
    {
      Cerr << "Neumann_sortie_libre::val_ext" << finl;
      Cerr<<le_champ_ext<<finl;
    }
  exit();
  return 0.;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, le_champ_ext, TRUSTVect< _TYPE_ >::size(), and Champ_front::valeurs().
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Eval_Conv_VDF_Elem< DERIVED_T >::coeffs_face_bloc_vitesse(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Eval_Conv_VDF_Face< DERIVED_T >::flux_fa7(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Eval_Conv_VDF_Face< DERIVED_T >::secmem_fa7(), and Eval_Conv_VDF_Elem< DERIVED_T >::secmem_face().
val_ext() [2/2]
double Neumann_sortie_libre::val_ext (int i, int j) const override virtual
Renvoie la valeur de la (i,j)-eme composante
du champ impose a l'exterieur de la frontiere.
Returns
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Implements Neumann_val_ext.
Definition at line 187 of file Neumann_sortie_libre.cpp.
{
  if (le_champ_ext.valeurs().dimension(0)==1)
    return le_champ_ext(0,j);
  else
    return le_champ_ext(i,j);
}
References TRUSTTab< _TYPE_ >::dimension(), le_champ_ext, and Champ_front::valeurs().
verifie_ch_init_nb_comp()
void Neumann_sortie_libre::verifie_ch_init_nb_comp () const override virtual
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Reimplemented from Cond_lim_base.
Definition at line 102 of file Neumann_sortie_libre.cpp.
{
  if (le_champ_front.non_nul())
    {
      const Equation_base& eq = zone_Cl_dis().equation();
      const int nb_comp = le_champ_front.valeur().nb_comp();
      if ((que_suis_je()=="Frontiere_ouverte") || (que_suis_je()=="Frontiere_ouverte_rayo_semi_transp")
          || (que_suis_je()=="Frontiere_Ouverte_Rayo_transp") || (que_suis_je()=="Sortie_libre_temperature_imposee_H"))
        eq.verifie_ch_init_nb_comp_cl(eq.inconnue(),nb_comp, *this);
      else
        {
          const Navier_Stokes_std& eq_ns = ref_cast(Navier_Stokes_std,eq);
          eq.verifie_ch_init_nb_comp_cl(eq_ns.pression(),nb_comp, *this);
        }
    }
}
References MorEqn::equation(), Equation_base::inconnue(), Cond_lim_base::le_champ_front, Field_base::nb_comp(), O_U_Ptr::non_nul(), Navier_Stokes_std::pression(), Objet_U::que_suis_je(), ref_cast, Deriv_Champ_front_base::valeur(), Equation_base::verifie_ch_init_nb_comp_cl(), and Cond_lim_base::zone_Cl_dis().
Member Data Documentation
info_obj
const Type_info Neumann_sortie_libre::info_obj static
Definition at line 46 of file Neumann_sortie_libre.h.
le_champ_ext
Champ_front Neumann_sortie_libre::le_champ_ext protected
Definition at line 69 of file Neumann_sortie_libre.h.
Referenced by associer_fr_dis_base(), avancer(), changer_temps_futur(), Sortie_libre_Pression_imposee_Orlansky::completer(), fixer_nb_valeurs_temporelles(), initialiser(), mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Neumann_sortie_libre_Temp_H::readOn(), Sortie_libre_pression_imposee_QC::readOn(), readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), reculer(), set_temps_defaut(), tab_ext(), Neumann_sortie_libre_Temp_H::val_ext(), and val_ext().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Neumann_sortie_libre.h
src/ThHyd/Incompressible/Cond_Lim/Neumann_sortie_libre.cpp