TRUST: Perte_Charge_Singuliere Class Reference
Perte_Charge_Singuliere Class Reference
Classe Perte_Charge_Singuliere
Cette classe derivee de Perte_Charge est utilisee lorsque l'on veut
modeliser une perte de charge sur une surface (passage d'une grille par exemple)
par exemple)
#include <Perte_Charge_Singuliere.h>
Public Member Functions
virtual ~Perte_Charge_Singuliere ()
Entree & lire_donnees (Entree &)
Lit les specifications d'une perte de charge singuliere
a partir d'un flot d'entree.
virtual void lire_surfaces (Entree &, const Domaine &, const Zone_dis_base &, IntVect &, IntVect &)
double K () const
double calculate_Q (const Equation_base &eqn, const IntVect &num_faces, const IntVect &sgn) const
void update_K (const Equation_base &eqn, double deb, DoubleVect &bilan)
Protected Attributes
double K_
Nom identifiant_
int regul_
Parser_U deb_cible_
Parser_U eps_
Detailed Description
Classe Perte_Charge_Singuliere
Cette classe derivee de Perte_Charge est utilisee lorsque l'on veut
modeliser une perte de charge sur une surface (passage d'une grille par exemple)
par exemple)
Definition at line 49 of file Perte_Charge_Singuliere.h.
Constructor & Destructor Documentation
virtual Perte_Charge_Singuliere::~Perte_Charge_Singuliere () [inline, virtual]
Definition at line 54 of file Perte_Charge_Singuliere.h.
{}
Member Function Documentation
double Perte_Charge_Singuliere::calculate_Q (const Equation_base & eqn, const IntVect & num_faces, const IntVect & sgn) const
< get_champ pour flica5 car la masse volumique n'est pas dans le milieu...
Definition at line 382 of file Perte_Charge_Singuliere.cpp.
References Zone_VF::creer_tableau_faces(), Objet_U::dimension, Zone_VF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Probleme_base::get_champ(), Equation_base::inconnue(), mp_somme_vect(), Zone_VF::porosite_face(), Equation_base::probleme(), ref_cast, sgn, IntVect::size(), sub_type, Deriv_Zone_dis_base::valeur(), Champ_Proto::valeurs(), Champ_Inc::valeurs(), and Equation_base::zone_dis().
Referenced by Perte_Charge_Singuliere_VEF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VDF_Face::mettre_a_jour(), Perte_Charge_Singuliere_PolyMAC_Face::mettre_a_jour(), DP_Impose_PolyMAC_Face::mettre_a_jour(), Perte_Charge_Singuliere_CoviMAC_Face::mettre_a_jour(), and DP_Impose_CoviMAC_Face::mettre_a_jour().
{
  const Zone_VF& zvf = ref_cast(Zone_VF, eqn.zone_dis().valeur());
  const DoubleTab& vit = eqn.inconnue().valeurs(),
                   &fac = sub_type(Pb_Multiphase, eqn.probleme()) ? ref_cast(Pb_Multiphase, eqn.probleme()).eq_masse.champ_conserve().passe()
                          : eqn.probleme().get_champ("masse_volumique").valeurs(); //!< get_champ pour flica5 car la masse volumique n'est pas dans le milieu...
  const DoubleVect& pf = zvf.porosite_face(), &fs = zvf.face_surfaces();
  const IntTab& f_e = zvf.face_voisins();
  int cF = fac.dimension_tot(0) == 1, i, n, N = fac.line_size(), d, D = Objet_U::dimension;
  DoubleTrav deb_vect;
  zvf.creer_tableau_faces(deb_vect); //pour bien sommer les debits en parallele
  for (i = 0; i < num_faces.size(); i++)
    {
      int f = num_faces(i), e = f_e(f, f_e(f, 0) < 0); //todo : evaluer fac du bon cote
      if (vit.line_size() > N) for (d = 0; d < D; d++) for (n = 0; n < N; n++) deb_vect(f) += zvf.face_normales(f, d) * vit(f, N * d + n) * fac(!cF * e, n); //vecteur complet : v . nf
      else for (n = 0; n < N; n++) deb_vect(f) += fs(f) * vit(f, n) * fac(!cF * e, n); //normale aux faces seule
      deb_vect(f) *= pf(f) * (sgn.size() ? sgn(i) : deb_vect(f) > 0 ? 1 : -1) ; //produit par la porosite + orientation (si elle n'est pas definie, on compte tout en positif)
    }
  return mp_somme_vect(deb_vect);
}
double Perte_Charge_Singuliere::K () const [inline]
Returns:
double
Signification:
Contraintes:
Definition at line 85 of file Perte_Charge_Singuliere.h.
References K_.
Referenced by Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec(), and Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec().
{
  return K_;
}
Entree & Perte_Charge_Singuliere::lire_donnees (Entree & is)
Lit les specifications d'une perte de charge singuliere
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented in DP_Impose.
Definition at line 59 of file Perte_Charge_Singuliere.cpp.
References Parser_U::addVar(), Param::ajouter(), Cerr, convert_to(), deb_cible_, Perte_Charge::direction_perte_charge_, eps_, Process::exit(), finl, K_, Param::lire_avec_accolades(), Parser_U::parseString(), regul_, Param::REQUIRED, Motcles::search(), Parser_U::setNbVar(), and Parser_U::setString().
Referenced by Perte_Charge_Singuliere_VEF_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), and Perte_Charge_Singuliere_CoviMAC_Face::readOn().
{
  Motcle motlu;
  Motcle acc_ouverte("{");
  Motcles les_motcles(4);
  les_motcles[0] = "KX";
  les_motcles[1] = "KY";
  les_motcles[2] = "KZ";
  les_motcles[3] = "K";
  regul_ = 0;
  is >> motlu;
  if (motlu != acc_ouverte)
    {
      Cerr << "On attendait le mot cle" << acc_ouverte << " a la place de " << motlu << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu != "dir")
    {
      Cerr << "On attendait le mot cle dir a la place de " << motlu << finl;
      Process::exit();
    }
  else
    {
      is >> motlu;
      int rang = les_motcles.search(motlu);
      if (rang == -1)
        {
          Cerr << "Erreur a la lecture des donnees de Perte_Charge_Singuliere" << finl;
          Cerr << "On attendait l'un des mots cles " << les_motcles << finl;
          Cerr << "a la place de " << motlu << finl;
          Process::exit();
        }
      direction_perte_charge_ = rang == 3 ? -1 : rang;
    }
  is >> motlu;
  if (motlu == "regul")
    {
      regul_ = 1;
      Nom eps_str, deb_str;
      Param param("regul");
      param.ajouter("K0", &K_, Param::REQUIRED);
      param.ajouter("deb", &deb_str, Param::REQUIRED);
      param.ajouter("eps", &eps_str, Param::REQUIRED);
      param.lire_avec_accolades(is);
      deb_cible_.setNbVar(1), eps_.setNbVar(1);
      deb_cible_.setString(deb_str), eps_.setString(eps_str);
      deb_cible_.addVar("t"), eps_.addVar("t");
      deb_cible_.parseString(), eps_.parseString();
    }
  else if (motlu == "coeff")
    {
      is >> motlu;
      convert_to(motlu.getChar(), K_);
    }
  else
    {
      Cerr << "On attendait le mot cle coeff ou regul a la place de " << motlu << finl;
      Process::exit();
    }
  Cerr << " direction_perte_charge_ " << direction_perte_charge_ << finl;
  Cerr << " perte de charge K_ " << K_ << finl;
  return is;
}
void Perte_Charge_Singuliere::lire_surfaces (Entree & is, const Domaine & le_domaine, const Zone_dis_base & zone_dis, IntVect & les_faces, IntVect & sgn) [virtual]
Definition at line 127 of file Perte_Charge_Singuliere.cpp.
References Zone::calculer_centres_gravite(), Cerr, compteur, Zone::construit_octree(), Domaine::coord_sommets(), Zone_VF::creer_tableau_faces(), Nom::debute_par(), Objet_U::dimension, Perte_Charge::direction_perte_charge(), Zone_VF::elem_faces(), est_egal(), Process::exit(), Zone_VF::face_normales(), Zone_VF::face_sommets(), finl, identifiant_, Objet_U::interprete(), mp_somme_vect(), Zone::nb_elem_tot(), Sous_Zone::nb_elem_tot(), Zone::nb_faces_elem(), Zone::nb_som_elem(), Domaine::nb_zones(), Interprete::objet(), Objet_U::que_suis_je(), OctreeRoot::rang_elems_sommet(), ref_cast, IntVect::resize(), sgn, ArrOfInt::size_array(), Zone::sommet_elem(), Domaine::ss_zone(), Zone_VF::xv(), Domaine::zone(), and Zone_dis_base::zone().
Referenced by Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), and DP_Impose_CoviMAC_Face::remplir_num_faces().
{
  const Zone_VF& zvf = ref_cast(Zone_VF,zone_dis);
  const IntTab& elem_faces = zvf.elem_faces();
  const DoubleTab& xv = zvf.xv();
  int nfe = zvf.zone().nb_faces_elem();
  IntTab face_tab; //1 for faces in the surface
  zvf.creer_tableau_faces(face_tab);
  Champ_Don orientation;
  int algo=-1;
  Motcle method;
  Motcle motlu;
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  Nom nom_ss_zone, nom_surface;
  double position;
  /* Read plan */
  is >> motlu;
  if (motlu != "surface")
    {
      Cerr << "On attendait le mot cle surface a la place de " << motlu << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu != acc_ouverte)
    {
      Cerr << "On attendait le mot cle" << acc_ouverte << " a la place de " << motlu << finl;
      Process::exit();
    }
  is >> method;
  if (method=="X" || method=="Y" || method=="Z")
    {
      /* Subzone algorithm */
      algo=0;
      Nom direction=method, egal;
      if (  ((direction=="X") && (direction_perte_charge()!=0))
            || ((direction=="Y") && (direction_perte_charge()!=1))
            || ((direction=="Z") && (direction_perte_charge()!=2)))
        {
          Nom dir,sect;
          if (direction_perte_charge() == 0)
            {
              dir="KX";
              sect="X";
            }
          else if (direction_perte_charge() == 1)
            {
              dir="KY";
              sect="Y";
            }
          else if (direction_perte_charge() == 2)
            {
              dir="KZ";
              sect="Z";
            }
          Cerr << "The section specified " << direction << " is not coherent with the coefficient pressure loss direction indicated by " << dir << finl;
          Cerr << "Here the section to specify is " << sect << "." << finl;
          Process::exit();
        }
      is >> egal >> position;
      is >> nom_ss_zone;
      Cerr << " position " << direction << " " << position << finl;
      identifiant_ = nom_ss_zone + "_" + direction + "=" + Nom(position);
    }
  else if (method=="Surface")
    {
      /* Surface algorithm */
      algo=1;
      /*
            if (zvf.dimension!=3)
              {
                Cerr << "Error in Perte_Charge_Singuliere::lire_surfaces" << finl;
                Cerr << "The keyword " << method << " specified for plan definition is only possible in 3D !" << finl;
                Cerr << "You must used the method of intersection between subzone and location of plane." << finl;
                Process::exit();
              }
      */
      if (zone_dis.que_suis_je().debute_par("Zone_VDF"))
        {
          Cerr << "Error in Perte_Charge_Singuliere::lire_surfaces" << finl;
          Cerr << "The keyword " << method << " specified for plan definition is only possible in VEF discretization !" << finl;
          Cerr << "You must used the method of intersection between subzone and location of plane." << finl;
          Process::exit();
        }
      is >> nom_surface;
      Cerr << " surface " << nom_surface << finl;
      identifiant_ = nom_surface;
    }
  else
    {
      Cerr << "Error in Perte_Charge_Singuliere::lire_surfaces" << finl;
      Cerr << "The keyword " << method << " specified for plan definition is not coherent !" << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu == "orientation") is >> orientation, is >> motlu; //on lit un champ pour orienter la surface
  if (motlu != acc_fermee)
    {
      Cerr << "On attendait le mot cle" << acc_fermee << " a la place de " << motlu << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu != acc_fermee)
    {
      Cerr << "On attendait le mot cle" << acc_fermee << " a la place de " << motlu << finl;
      Process::exit();
    }
  /* Found faces */
  int compteur=0;
  if (algo==0)
    {
      /* Subzone algorithm */
      const Sous_Zone& ssz = le_domaine.ss_zone(nom_ss_zone);
      for (int poly=0; poly<ssz.nb_elem_tot(); poly++)
        {
          for (int j=0; j<nfe; j++)
            {
              int numfa = elem_faces(ssz(poly),j);
// numfa might be negative in case of polyhedron where number of faces for an elem varies (padding)
              if (numfa >= 0 && est_egal(xv(numfa,direction_perte_charge()),position) )
                {
                  bool trouve=0;
                  for (int i=0; i<compteur; i++)
                    if (les_faces[i]==numfa)
                      {
                        trouve=1;
                        break;
                      }
                  if (trouve==0) les_faces[compteur++] = numfa, face_tab(numfa) = 1;
                }
            }
        }
    }
  else if (algo==1)
    {
      /* Surface algorithm */
      const Domaine& le_domaine2D = ref_cast(Domaine,le_domaine.interprete().objet(nom_surface));
      if (le_domaine2D.nb_zones() == 0)
        {
          Cerr << "Error in Perte_Charge_Singuliere::lire_surfaces" << finl;
          Cerr << "You must correct your data file because the " << nom_surface << " surface is not well defined in parallel !" << finl;
          Process::exit();
        }
      const Zone& zone_2D = le_domaine2D.zone(0);
      const DoubleTab& coord_sommets_2D=le_domaine2D.coord_sommets();
      DoubleTab xv2D;
      zone_2D.calculer_centres_gravite(xv2D);
      const int nb_elem_2D = zone_2D.nb_elem_tot();
      int nse2D = zone_2D.nb_som_elem();
      const DoubleTab& coord_sommets=le_domaine.coord_sommets();
      const IntTab& face_sommets = zvf.face_sommets();
      const Zone& zone_vol = le_domaine.zone(0);
      const OctreeRoot& octree_vol = zone_vol.construit_octree();
// Loop on faces on the surface domain
      Cerr << " Surface " << nom_surface << " with " << nb_elem_2D << " faces" << finl;
      for (int ind_face=0; ind_face<nb_elem_2D; ind_face++)
        {
// Fill elem_list_vol by elements surrounding the center of gravity
          ArrOfInt elem_list_vol;
          double zv2d=0;
          if (Objet_U::dimension>2)
            zv2d=xv2D(ind_face,2);
          octree_vol.rang_elems_sommet(elem_list_vol,xv2D(ind_face,0),xv2D(ind_face,1),zv2d);
          int nb_elem_vol = elem_list_vol.size_array();
// Loop on elements on the volume domain
          for (int ind_elem=0; ind_elem<nb_elem_vol; ind_elem++)
            {
              int elem = elem_list_vol(ind_elem);
// Loop on faces of each element on the volume domain
              for (int j=0, numfa; j < nfe && (numfa = elem_faces(elem,j)) >= 0; j++)
                {
// Test if the same face between surface domain and volum domain
                  int coincide=0;
// Loop on vertex of each face of each element on the volume domain
                  for (int k=0; k<nse2D; k++)
                    {
                      int numso = face_sommets(numfa,k);
                      double xcoord_vol=coord_sommets(numso,0);
                      double ycoord_vol=coord_sommets(numso,1);
// double zcoord_vol=coord_sommets(numso,2);
                      double  zcoord_vol=0;
                      if (Objet_U::dimension>2)
                        zcoord_vol=coord_sommets(numso,2);
                      for (int i=0; i<nse2D ; i++)
{
                          int numso2D = zone_2D.sommet_elem(ind_face,i);
                          double xcoord_2D=coord_sommets_2D(numso2D,0);
                          double ycoord_2D=coord_sommets_2D(numso2D,1);
                          double zcoord_2D=0;
                          if (Objet_U::dimension>2)
                            zcoord_2D=coord_sommets_2D(numso2D,2);
                          if ( est_egal(xcoord_vol,xcoord_2D)
                               && est_egal(ycoord_vol,ycoord_2D)
                               && est_egal(zcoord_vol,zcoord_2D))
{
                              coincide=coincide+1;
                              break;
                            }
                        }
                    }
                  if (coincide==nse2D)
                    {
                      bool trouve=0;
                      for (int i=0; i<compteur ; i++)
                        if (les_faces[i]==numfa)
{
                            trouve=1;
                            break;
                          }
                      if (trouve==0) les_faces[compteur++] = numfa, face_tab(numfa) = 1;
                    }
                }
            }
        }
    }
  int faces_found=mp_somme_vect(face_tab);
  if (faces_found==0)
    {
      Cerr << "Error in Perte_Charge_Singuliere::lire_surfaces" << finl;
      Cerr << "No faces has been found !" << finl;
      Process::exit();
    }
  else
    Cerr << " " << faces_found << " faces have been found for the section." << finl;
  les_faces.resize(compteur);
  if (orientation.non_nul())
    {
      sgn.resize(compteur);
      DoubleTrav xvf(compteur, Objet_U::dimension), ori(compteur, Objet_U::dimension);
      for (int i = 0; i < compteur; i++) for (int j = 0; j < Objet_U::dimension; j++) xvf(i, j) = xv(les_faces(i), j);
      orientation.valeur().valeur_aux(xvf, ori);
      for (int i = 0; i < compteur; i++)
        {
          double scal = 0;
          for (int j = 0; j < Objet_U::dimension; j++) scal += ori(i, j) * zvf.face_normales(les_faces(i), j);
          sgn(i) = (scal > 0 ? 1 : -1);
        }
    }
}
void Perte_Charge_Singuliere::update_K (const Equation_base & eqn, double deb, DoubleVect & bilan)
Definition at line 404 of file Perte_Charge_Singuliere.cpp.
References dabs(), deb_cible_, eps_, Parser_U::eval(), K_, max(), Process::me(), min(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), regul_, Probleme_base::schema_temps(), Parser_U::setVar(), and Schema_Temps_base::temps_courant().
Referenced by Perte_Charge_Singuliere_VEF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VDF_Face::mettre_a_jour(), Perte_Charge_Singuliere_PolyMAC_Face::mettre_a_jour(), and Perte_Charge_Singuliere_CoviMAC_Face::mettre_a_jour().
{
  if (!regul_) return;
  double t = eqn.probleme().schema_temps().temps_courant(), dt = eqn.probleme().schema_temps().pas_de_temps();
  deb_cible_.setVar(0, t), eps_.setVar(0, t);
  double deb_cible = deb_cible_.eval(), eps = eps_.eval(), f_min = std::pow(1 - eps, dt), f_max = std::pow(1 + eps, dt); //bande de variation de K
  K_ *= min(max(std::pow(dabs(deb) / deb_cible, 2), f_min), f_max);
// pour le fichier de suivi : seulement sur le maitre, car Source_base::imprimer() fait une somme sur les procs
  if (!Process::me()) bilan(0) = K_, bilan(1) = deb, bilan(2) = deb_cible;
}
Member Data Documentation
Parser_U Perte_Charge_Singuliere::deb_cible_ [protected]
Definition at line 68 of file Perte_Charge_Singuliere.h.
Referenced by lire_donnees(), and update_K().
Parser_U Perte_Charge_Singuliere::eps_ [protected]
Definition at line 68 of file Perte_Charge_Singuliere.h.
Referenced by lire_donnees(), and update_K().
Nom Perte_Charge_Singuliere::identifiant_ [protected]
Definition at line 66 of file Perte_Charge_Singuliere.h.
Referenced by lire_surfaces(), Perte_Charge_Singuliere_VEF_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), DP_Impose_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_CoviMAC_Face::readOn(), and DP_Impose_CoviMAC_Face::readOn().
double Perte_Charge_Singuliere::K_ [protected]
Definition at line 63 of file Perte_Charge_Singuliere.h.
Referenced by K(), lire_donnees(), and update_K().
int Perte_Charge_Singuliere::regul_ [protected]
Definition at line 67 of file Perte_Charge_Singuliere.h.
Referenced by lire_donnees(), DP_Impose::lire_donnees(), Perte_Charge_Singuliere_VEF_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), Perte_Charge_Singuliere_CoviMAC_Face::readOn(), and update_K().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Perte_Charge_Singuliere.h
src/ThHyd/Incompressible/Sources/Perte_Charge_Singuliere.cpp