TRUST: Zone_Cl_CoviMAC Class Reference
Zone_Cl_CoviMAC Class Reference
#include <Zone_Cl_CoviMAC.h>
Public Member Functions
Zone_Cl_CoviMAC ()
~Zone_Cl_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_CoviMAC &)
etape de discretisation : dimensionnement des tableaux
void completer (const Zone_dis &)
remplissage des tableaux
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void imposer_cond_lim (Champ_Inc &, double)
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
int nb_faces_sortie_libre () const
Zone_CoviMAC & zone_CoviMAC ()
const Zone_CoviMAC & zone_CoviMAC () const
int nb_bord_periodicite () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Zone_Cl_CoviMAC & self_cast (Objet_U &)
static const Zone_Cl_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
void remplir_type_elem_Cl (const Zone_CoviMAC &)
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Protected Attributes
int modif_perio_fait_
Detailed Description
Definition at line 46 of file Zone_Cl_CoviMAC.h.
Constructor & Destructor Documentation
Zone_Cl_CoviMAC::Zone_Cl_CoviMAC ()
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
Zone_Cl_CoviMAC::~Zone_Cl_CoviMAC ()
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
Member Function Documentation
void Zone_Cl_CoviMAC::associer (const Zone_CoviMAC & la_zone_CoviMAC)
etape de discretisation : dimensionnement des tableaux
Definition at line 71 of file Zone_Cl_CoviMAC.cpp.
{
// int nb_elem_Cl  = la_zone_CoviMAC.nb_elem_Cl();
}
void Zone_Cl_CoviMAC::completer (const Zone_dis & une_zone_dis) [virtual]
remplissage des tableaux
Implements Zone_Cl_dis_base.
Definition at line 78 of file Zone_Cl_CoviMAC.cpp.
References Process::exit(), modif_perio_fait_, ref_cast, remplir_type_elem_Cl(), sub_type, and Deriv_Zone_dis_base::valeur().
{
  modif_perio_fait_ =0;
  if (sub_type(Zone_CoviMAC,une_zone_dis.valeur()))
    {
      const Zone_CoviMAC& la_zone_CoviMAC = ref_cast(Zone_CoviMAC, une_zone_dis.valeur());
      remplir_type_elem_Cl(la_zone_CoviMAC);
    }
  else
    {
      cerr << "Zone_Cl_CoviMAC::completer() prend comme argument une Zone_CoviMAC\n";
      exit();
    }
}
Objet_U * Zone_Cl_CoviMAC::cree_instance () [static]
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
int Zone_Cl_CoviMAC::duplique () const [virtual]
Implements Zone_Cl_dis_base.
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
const Type_info * Zone_Cl_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
void Zone_Cl_CoviMAC::imposer_cond_lim (Champ_Inc & ch, double temps) [virtual]
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
Implements Zone_Cl_dis_base.
Definition at line 101 of file Zone_Cl_CoviMAC.cpp.
References Process::abort(), Cerr, Objet_U::dimension, DoubleVect::echange_espace_virtuel(), Process::exit(), Zone_VF::face_normales(), Zone_VF::face_surfaces(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), DoubleVect::line_size(), modif_perio_fait_, Field_base::nature_du_champ(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), ref_cast, scalaire, sub_type, Dirichlet::val_imp_au_temps(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeurs(), verifier(), and Champ_Face_CoviMAC::zone_vf().
{
  Champ_Inc_base& ch_base=ch.valeur();
  DoubleTab& ch_tab = ch_base.valeurs(temps);
  int n, N = ch_tab.line_size();
  if (sub_type(Champ_Inc_P0_base,ch_base))
    ;
  else if(ch_base.nature_du_champ()==scalaire)
    ;
  else if (sub_type(Champ_Face_CoviMAC,ch_base))
    {
      Champ_Face_CoviMAC& ch_face = ref_cast(Champ_Face_CoviMAC, ch_base);
      const Zone_VF& ma_zone_VF = ch_face.zone_vf();
      int ndeb,nfin, num_face;
      for(int i=0; i<nb_cond_lim(); i++)
        {
          const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
          if (sub_type(Periodique,la_cl)) abort(); //nope
          else if( sub_type(Symetrie,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++) for (n = 0; n < N; n++)
                  ch_tab(num_face, n) = 0;
            }
          else if ( sub_type(Dirichlet_entree_fluide,la_cl) )
            {
              const Dirichlet_entree_fluide& la_cl_diri = ref_cast(Dirichlet_entree_fluide,la_cl);
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++) for (n = 0; n < N; n++)
                  {
// WEC : optimisable (pour chaque face recherche le bon temps !)
// vn
                    double vn=0;
                    for (int d=0; d<dimension; d++)
                      vn+=ma_zone_VF.face_normales(num_face,d)*la_cl_diri.val_imp_au_temps(temps,num_face-ndeb, N * d + n);
                    vn/=ma_zone_VF.face_surfaces(num_face);
                    ch_tab(num_face, n) = vn;
                  }
            }
          else if ( sub_type(Dirichlet_paroi_fixe,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++) for (n = 0; n < N; n++)
                  ch_tab(num_face, n) = 0;
            }
          else if ( sub_type(Dirichlet_paroi_defilante,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++) for (n = 0; n < N; n++)
                  ch_tab(num_face, n) = 0;
            }
        }
      modif_perio_fait_  = 1;
    }
  else
    {
      Cerr << "Le type de Champ_Inc " <<  ch->que_suis_je() << " n'est pas prevu en CoviMAC\n";
      exit();
    }
  ch_tab.echange_espace_virtuel();
  Debog::verifier("Zone_Cl_CoviMAC::imposer_cond_lim ch_tab",ch_tab);
}
const Type_info * Zone_Cl_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
int Zone_Cl_CoviMAC::initialiser (double temps) [virtual]
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns:
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 209 of file Zone_Cl_CoviMAC.cpp.
References Process::abort(), Cerr, finl, and nb_bord_periodicite().
{
  Zone_Cl_dis_base::initialiser(temps);
  if (nb_bord_periodicite()>0)
    {
      Cerr<<" La periodicite n'est pas code !!!"<<finl;
      abort();
    }
  return 1;
}
int Zone_Cl_CoviMAC::nb_bord_periodicite () const
Definition at line 197 of file Zone_Cl_CoviMAC.cpp.
References compteur, Zone_Cl_dis_base::les_conditions_limites_, vect_impl::size(), sub_type, and valeur().
Referenced by initialiser().
{
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if (sub_type(Periodique,les_conditions_limites_[cl].valeur()))
        compteur++;
    }
  return compteur;
}
int Zone_Cl_CoviMAC::nb_faces_sortie_libre () const
Definition at line 179 of file Zone_Cl_CoviMAC.cpp.
References Process::exit().
{
  exit();
  /*
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if(sub_type(Neumann_sortie_libre, les_conditions_limites_[cl].valeur()))
  {
    const Front_VF& le_bord=ref_cast(Front_VF,les_conditions_limites_[cl]->frontiere_dis());
    compteur+=le_bord.nb_faces();
  }
    }
  return compteur;
  */
  return -1;
}
Sortie & Zone_Cl_CoviMAC::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 49 of file Zone_Cl_CoviMAC.cpp.
{
  return os;
}
Entree & Zone_Cl_CoviMAC::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 57 of file Zone_Cl_CoviMAC.cpp.
{
  return Zone_Cl_dis_base::readOn(is) ;
}
void Zone_Cl_CoviMAC::remplir_type_elem_Cl (const Zone_CoviMAC & la_zone_CoviMAC) [protected]
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Definition at line 94 of file Zone_Cl_CoviMAC.cpp.
Referenced by completer().
{
}
Zone_Cl_CoviMAC & Zone_Cl_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Zone_Cl_dis_base.
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
const Zone_Cl_CoviMAC & Zone_Cl_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Zone_Cl_dis_base.
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
unsigned Zone_Cl_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 45 of file Zone_Cl_CoviMAC.cpp.
const Zone_CoviMAC & Zone_Cl_CoviMAC::zone_CoviMAC () const
Definition at line 226 of file Zone_Cl_CoviMAC.cpp.
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
{
  return ref_cast(Zone_CoviMAC, zone_dis().valeur());
}
Zone_CoviMAC & Zone_Cl_CoviMAC::zone_CoviMAC ()
Definition at line 221 of file Zone_Cl_CoviMAC.cpp.
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
{
  return ref_cast(Zone_CoviMAC, zone_dis().valeur());
}
Member Data Documentation
const Type_info Zone_Cl_CoviMAC::info_obj [static]
Reimplemented from Zone_Cl_dis_base.
Definition at line 49 of file Zone_Cl_CoviMAC.h.
int Zone_Cl_CoviMAC::modif_perio_fait_ [protected]
Definition at line 70 of file Zone_Cl_CoviMAC.h.
Referenced by completer(), and imposer_cond_lim().
The documentation for this class was generated from the following files:
src/CoviMAC/Zones/Zone_Cl_CoviMAC.h
src/CoviMAC/Zones/Zone_Cl_CoviMAC.cpp