TRUST: Ref_Sous_zone_VF Class Reference
Ref_Sous_zone_VF Class Reference
#include <Ref_Sous_zone_VF.h>
Public Member Functions
~Ref_Sous_zone_VF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Sous_zone_VF ()
Ref_Sous_zone_VF (const Sous_zone_VF &)
Ref_Sous_zone_VF (const Ref_Sous_zone_VF &)
const Sous_zone_VF & valeur () const
Sous_zone_VF & valeur ()
const Sous_zone_VF * operator-> () const
Sous_zone_VF * operator-> ()
const Ref_Sous_zone_VF & operator= (const Sous_zone_VF &)
const Ref_Sous_zone_VF & operator= (const Ref_Sous_zone_VF &)
operator const Sous_zone_VF & () const
operator Sous_zone_VF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Sous_zone_VF & self_cast (Objet_U &)
static const Ref_Sous_zone_VF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Sous_zone_VF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Sous_zone_VF.h.
Constructor & Destructor Documentation
Ref_Sous_zone_VF::~Ref_Sous_zone_VF ()
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Ref_Sous_zone_VF::Ref_Sous_zone_VF ()
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Ref_Sous_zone_VF::Ref_Sous_zone_VF (const Sous_zone_VF & t)
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Ref_Sous_zone_VF::Ref_Sous_zone_VF (const Ref_Sous_zone_VF & t)
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Member Function Documentation
Objet_U * Ref_Sous_zone_VF::cree_instance () [static]
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
int Ref_Sous_zone_VF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Type_info * Ref_Sous_zone_VF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Type_info & Ref_Sous_zone_VF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Type_info * Ref_Sous_zone_VF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Ref_Sous_zone_VF::operator const Sous_zone_VF & () const
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Ref_Sous_zone_VF::operator Sous_zone_VF & ()
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Sous_zone_VF * Ref_Sous_zone_VF::operator-> () const [inline]
Definition at line 28 of file Ref_Sous_zone_VF.h.
Sous_zone_VF * Ref_Sous_zone_VF::operator-> () [inline]
Definition at line 28 of file Ref_Sous_zone_VF.h.
const Ref_Sous_zone_VF & Ref_Sous_zone_VF::operator= (const Ref_Sous_zone_VF & t)
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Ref_Sous_zone_VF & Ref_Sous_zone_VF::operator= (const Sous_zone_VF & t)
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Sortie & Ref_Sous_zone_VF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Entree & Ref_Sous_zone_VF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Ref_Sous_zone_VF & Ref_Sous_zone_VF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
Ref_Sous_zone_VF & Ref_Sous_zone_VF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
void Ref_Sous_zone_VF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
unsigned Ref_Sous_zone_VF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Sous_zone_VF.cpp.
const Sous_zone_VF & Ref_Sous_zone_VF::valeur () const [inline]
Definition at line 28 of file Ref_Sous_zone_VF.h.
Referenced by Perte_Charge_VEF::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::contribuer_a_avec().
Sous_zone_VF & Ref_Sous_zone_VF::valeur () [inline]
Definition at line 28 of file Ref_Sous_zone_VF.h.
Member Data Documentation
const Type_info Ref_Sous_zone_VF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Sous_zone_VF.h.
Sous_zone_VF* Ref_Sous_zone_VF::pointeur_ [private]
Definition at line 28 of file Ref_Sous_zone_VF.h.
The documentation for this class was generated from the following files:
src/Kernel/VF/Zones/Ref_Sous_zone_VF.h
src/Kernel/VF/Zones/Ref_Sous_zone_VF.cpp