TRUST: Champ_Don_Fonc_xyz Class Reference
Champ_Don_Fonc_xyz Class Reference
class Champ_Don_Fonc_xyz
Cette classe represente un champ de donnees fonction
des variables d'espaces x,y,z. La fonction est fournie
directement dans le jeu de donnees sous la forme d'une expression
mathematique contenant les variables x,y,z (en minuscules)
.......................
#include <Champ_Don_Fonc_xyz.h>
Public Member Functions
Champ_Don_Fonc_xyz ()
~Champ_Don_Fonc_xyz ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_base & affecter (const Champ_base &ch)
Provoque une erreur: cela n'a pas de sens
de vouloir effectuer une affectation avec un Champ_Don_Fonc_xyz.
virtual Champ_base & affecter_ (const Champ_base &)
Provoque une erreur !
A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Renvoie la valeur du champ au point specifie
par ses coordonnees.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Renvoie la valeur du champ au point specifie
par ses coordonnees.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Don_Fonc_xyz & self_cast (Objet_U &)
static const Champ_Don_Fonc_xyz & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime les valeurs du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le champ sur un flot d'entree.
Protected Attributes
Ref_Domaine mon_domaine
Detailed Description
class Champ_Don_Fonc_xyz
Cette classe represente un champ de donnees fonction
des variables d'espaces x,y,z. La fonction est fournie
directement dans le jeu de donnees sous la forme d'une expression
mathematique contenant les variables x,y,z (en minuscules)
.......................
Definition at line 43 of file Champ_Don_Fonc_xyz.h.
Constructor & Destructor Documentation
Champ_Don_Fonc_xyz::Champ_Don_Fonc_xyz ()
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
Champ_Don_Fonc_xyz::~Champ_Don_Fonc_xyz ()
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
Member Function Documentation
Champ_base & Champ_Don_Fonc_xyz::affecter (const Champ_base & ch)
Provoque une erreur: cela n'a pas de sens
de vouloir effectuer une affectation avec un Champ_Don_Fonc_xyz.
Returns:
Champ_base&
Signification:
Contraintes:
Reimplemented from Champ_base.
Definition at line 150 of file Champ_Don_Fonc_xyz.cpp.
References Champ_base::affecter_erreur().
{
  Champ_base::affecter_erreur();
  return *this;
}
Champ_base & Champ_Don_Fonc_xyz::affecter_ (const Champ_base &) [virtual]
Provoque une erreur !
A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Returns:
Champ_base&
Signification:
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 156 of file Champ_Don_Fonc_xyz.cpp.
References sub_type, Champ_Proto::valeurs(), and Champ_Don_base::valeurs().
{
  if(sub_type(Champ_Uniforme, ch))
    valeurs()=ch.valeurs()(0,0);
  else
    valeurs()=ch.valeurs();
  return *this;
}
Objet_U * Champ_Don_Fonc_xyz::cree_instance () [static]
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
int Champ_Don_Fonc_xyz::duplique () const [virtual]
Implements Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
const Type_info * Champ_Don_Fonc_xyz::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
const Type_info * Champ_Don_Fonc_xyz::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
Sortie & Champ_Don_Fonc_xyz::printOn (Sortie & os) const [protected, virtual]
Imprime les valeurs du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 45 of file Champ_Don_Fonc_xyz.cpp.
References DoubleVect::size(), and Champ_Don_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_Don_Fonc_xyz::readOn (Entree & is) [protected, virtual]
Lit le champ sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 70 of file Champ_Don_Fonc_xyz.cpp.
References Cerr, compteur, Domaine::coord(), Domaine::creer_tableau_elements(), IntTab::dimension(), Objet_U::dimension, Champ_Don_base::dimensionner(), DoubleVect::echange_espace_virtuel(), Parser_Eval::eval_fct(), finl, Parser_Eval::fonction(), Zone::les_elems(), Champ_Proto::lire_dimension(), mon_domaine, Zone::nb_elem(), Interprete::objet(), Objet_U::que_suis_je(), ref_cast, Ref_Domaine::valeur(), Champ_Don_base::valeurs(), VECT, and Domaine::zone().
{
  int dim;
  Motcle motlu;
  Nom nom;
  is >> nom;
  mon_domaine = ref_cast(Domaine, Interprete::objet(nom));
  Domaine& domaine=mon_domaine.valeur();
  const Zone& ma_zone = domaine.zone(0);
  const IntTab& les_Polys = ma_zone.les_elems();
  int nb_elems = ma_zone.nb_elem(),num_som;
  dim=lire_dimension(is,que_suis_je());
  dimensionner(nb_elems,dim);
  domaine.creer_tableau_elements(valeurs());
  DoubleTab& mes_val = valeurs();
  IntTab compteur(nb_elems);
  compteur = 0;
  int num_elem;
  int dernier_elem=0;
  double x,y,z;
  VECT(Parser_U)& fxyz = fonction();
  fxyz.dimensionner(dim);
  for (int i=0; i<dim; i++)
    {
      Nom tmp;
      is >> tmp;
      Cerr << "Reading and interpretation of the function " << tmp << finl;
      fxyz[i].setNbVar(3);
      fxyz[i].setString(tmp);
      fxyz[i].addVar("x");
      fxyz[i].addVar("y");
      if (dimension>2)
        fxyz[i].addVar("z");
      fxyz[i].parseString();
      Cerr << "Interpretation of function " << tmp << " Ok" << finl;
    }
  DoubleTab positions(nb_elems-dernier_elem,dimension);
  for (num_elem=dernier_elem; num_elem<nb_elems; num_elem++)
    {
      x=y=z=0;
      int s, n;
      for(s = n = 0; s < les_Polys.dimension(1); s++) if ((num_som = les_Polys(num_elem,s)) >= 0)
          {
            x += domaine.coord(num_som,0);
            y += domaine.coord(num_som,1);
            if (dimension>2) z += domaine.coord(num_som,2);
            n++;
          }
      positions(num_elem,0) = x/n;
      positions(num_elem,1) = y/n;
      if (dimension>2)
        positions(num_elem,2) = z/n;
    }
  eval_fct(positions,mes_val);
  mes_val.echange_espace_virtuel();
  return is;
}
Champ_Don_Fonc_xyz & Champ_Don_Fonc_xyz::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
const Champ_Don_Fonc_xyz & Champ_Don_Fonc_xyz::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
unsigned Champ_Don_Fonc_xyz::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Champ_Don_Fonc_xyz.cpp.
DoubleVect & Champ_Don_Fonc_xyz::valeur_a (const DoubleVect & x, DoubleVect & val) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 185 of file Champ_Don_Fonc_xyz.cpp.
References Cerr, Parser_Eval::eval_fct(), Process::exit(), finl, Field_base::nb_compo_, Objet_U::que_suis_je(), and DoubleVect::size().
Referenced by valeur_a_elem().
{
  if (val.size() != nb_compo_)
    {
      Cerr << "Error TRUST in "<<que_suis_je()<<"::valeur_a()" << finl;
      Cerr << "The DoubleVect val doesn't have the correct size" << finl;
      exit();
    }
  eval_fct(x,val);
  return val;
}
double Champ_Don_Fonc_xyz::valeur_a_compo (const DoubleVect & x, int ncomp) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 218 of file Champ_Don_Fonc_xyz.cpp.
References Cerr, Objet_U::dimension, Parser_Eval::eval_fct(), Process::exit(), finl, Field_base::nb_compo_, and Objet_U::que_suis_je().
Referenced by valeur_a_elem_compo().
{
  double val;
  if (ncomp > nb_compo_)
    {
      Cerr << "Error TRUST in "<<que_suis_je()<<"::valeur_a_compo()" << finl;
      Cerr << "the integer ncomp is upper than the number of field components" << finl;
      exit();
    }
  DoubleTab positions(1,dimension);
  DoubleTab val_fct(1);
  positions(0,0) = x(0);
  positions(0,1) = x(1);
  if (dimension>2)
    positions(0,2) = x(2);
  eval_fct(positions,val_fct,ncomp);
  val = val_fct(0);
  return val;
}
DoubleVect & Champ_Don_Fonc_xyz::valeur_a_elem (const DoubleVect & x, DoubleVect & val, int le_poly) const [virtual]
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 268 of file Champ_Don_Fonc_xyz.cpp.
References valeur_a().
{
  return valeur_a(x,val);
}
double Champ_Don_Fonc_xyz::valeur_a_elem_compo (const DoubleVect & x, int le_poly, int ncomp) const [virtual]
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
double
Signification: la valeur de la composante du champ specifiee au
point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 304 of file Champ_Don_Fonc_xyz.cpp.
References Cerr, Process::exit(), finl, Field_base::nb_compo_, Objet_U::que_suis_je(), and valeur_a_compo().
{
  if (ncomp > nb_compo_)
    {
      Cerr << "Error TRUST in "<<que_suis_je()<<"::valeur_a()" << finl;
      Cerr << "the integer ncomp is upper than the number of field components" << finl;
      exit();
    }
  return valeur_a_compo(x,ncomp);
}
DoubleTab & Champ_Don_Fonc_xyz::valeur_aux (const DoubleTab & x, DoubleTab & val) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 338 of file Champ_Don_Fonc_xyz.cpp.
References Cerr, Parser_Eval::eval_fct(), Process::exit(), finl, DoubleTab::nb_dim(), and Objet_U::que_suis_je().
Referenced by valeur_aux_elems().
{
  if (val.nb_dim() > 2)
    {
      Cerr << "Error TRUST in "<<que_suis_je()<<"::valeur_aux_elems()" << finl;
      Cerr << "The DoubleTab val has more than 2 entries" << finl;
      exit();
    }
  eval_fct(x,val);
  return val;
}
DoubleVect & Champ_Don_Fonc_xyz::valeur_aux_compo (const DoubleTab & x, DoubleVect & val, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 378 of file Champ_Don_Fonc_xyz.cpp.
References Parser_Eval::eval_fct().
Referenced by valeur_aux_elems_compo().
{
  eval_fct(x,val,ncomp);
  return val;
}
DoubleTab & Champ_Don_Fonc_xyz::valeur_aux_elems (const DoubleTab & x, const IntVect & les_polys, DoubleTab & val) const [virtual]
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 417 of file Champ_Don_Fonc_xyz.cpp.
References valeur_aux().
{
  return valeur_aux(x,val);
}
DoubleVect & Champ_Don_Fonc_xyz::valeur_aux_elems_compo (const DoubleTab & x, const IntVect & les_polys, DoubleVect & val, int ncomp) const [virtual]
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 458 of file Champ_Don_Fonc_xyz.cpp.
References valeur_aux_compo().
{
  return valeur_aux_compo(x,val,ncomp);
}
Member Data Documentation
const Type_info Champ_Don_Fonc_xyz::info_obj [static]
Reimplemented from Champ_Don_base.
Definition at line 46 of file Champ_Don_Fonc_xyz.h.
Ref_Domaine Champ_Don_Fonc_xyz::mon_domaine [protected]
Definition at line 77 of file Champ_Don_Fonc_xyz.h.
Referenced by readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Don_Fonc_xyz.h
src/Kernel/Champs/Champ_Don_Fonc_xyz.cpp