TRUST: Source_base Class Reference
Source_base Class Reference
classe Source_base
Un objet Source_base est un terme apparaissant au second membre d'une
equation. Cette classe est la base de la hierarchie des Sources, une
source est un morceau d'equation donc Source_base herite de MorEqn.
#include <Source_base.h>
Public Member Functions
Source_base ()
~Source_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void creer_champ (const Motcle &motlu)
virtual const Champ_base & get_champ (const Motcle &nom) const
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int &flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Attributes
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Detailed Description
classe Source_base
Un objet Source_base est un terme apparaissant au second membre d'une
equation. Cette classe est la base de la hierarchie des Sources, une
source est un morceau d'equation donc Source_base herite de MorEqn.
Definition at line 49 of file Source_base.h.
Constructor & Destructor Documentation
Source_base::Source_base ()
Definition at line 34 of file Source_base.cpp.
Source_base::~Source_base ()
Definition at line 34 of file Source_base.cpp.
Member Function Documentation
int Source_base::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const [virtual]
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
Reimplemented in Terme_Source_Acceleration.
Definition at line 163 of file Source_base.cpp.
Referenced by Sources::a_pour_Champ_Fonc().
{
// La classe de base ne comprend aucun motcle
  return 0;
}
DoubleTab & Source_base::ajouter (DoubleTab & secmem) const [virtual]
Reimplemented in Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_QDM_Gen, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Source_WC_Chaleur, Source_WC_Gravite_VDF, Source_WC_Gravite_VEF, Force_Centrifuge_VDF_Face_Axi, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 265 of file Source_base.cpp.
References ajouter_blocs(), Process::exit(), has_interface_blocs(), and Objet_U::que_suis_je().
Referenced by Source::ajouter(), Terme_Source_Canal_perio::calculer(), Terme_Source_Acceleration::calculer(), Terme_Boussinesq_base::calculer(), and calculer().
{
  if (has_interface_blocs()) ajouter_blocs({}, secmem, {});
  else Process::exit(que_suis_je() + " : ajouter() not coded!");
  return secmem;
}
virtual void Source_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, and Travail_pression_CoviMAC.
Referenced by ajouter(), and contribuer_a_avec().
void Source_base::associer_champ_rho (const Champ_base & champ_rho) [virtual]
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
Reimplemented in Terme_Source_Acceleration_VDF_Face, and Terme_Source_Acceleration_VEF_Face.
Definition at line 149 of file Source_base.cpp.
References Cerr, Process::exit(), finl, Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Sources::associer_champ_rho().
{
  Cerr << "In Source_base::associer_champ_rho" << finl;
  Cerr << " field : " << champ_rho.le_nom() << finl;
  Cerr << " Source of type : " << que_suis_je() << finl;
  Cerr << " This source does not support the association of a field rho." << finl;
  Cerr << " (method associer_champ_rho must be coded for this source term)." << finl;
  assert(0);
  exit();
}
virtual void Source_base::associer_pb (const Probleme_base &) [protected, pure virtual]
Implemented in Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Source_Generique_base, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_QDM_Gen, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_QC_VEF_Face, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Neutronique_VDF, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
Referenced by completer().
virtual void Source_base::associer_zones (const Zone_dis & , const Zone_Cl_dis &) [protected, pure virtual]
Implemented in Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Source_Generique_base, Source_Generique_P0_Elem, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur_Verif, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
Referenced by associer_zones_public(), and completer().
void Source_base::associer_zones_public (const Zone_dis & zdis, const Zone_Cl_dis & zcldis) [inline]
Definition at line 128 of file Source_base.h.
References associer_zones().
{
  associer_zones(zdis,zcldis);
}
DoubleVect& Source_base::bilan () [inline]
Definition at line 102 of file Source_base.h.
References bilan_.
Referenced by DP_Impose_PolyMAC_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Perte_Charge_Singuliere_VDF_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::mettre_a_jour(), Perte_Charge_Singuliere_PolyMAC_Face::mettre_a_jour(), DP_Impose_PolyMAC_Face::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::mettre_a_jour(), Perte_Charge_Singuliere_CoviMAC_Face::mettre_a_jour(), DP_Impose_CoviMAC_Face::mettre_a_jour(), Perte_Charge_Singuliere_VEF_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), and Perte_Charge_Singuliere_CoviMAC_Face::readOn().
  {
    return bilan_;
  };
DoubleVect& Source_base::bilan () const [inline]
Definition at line 106 of file Source_base.h.
References bilan_.
  {
    return bilan_;
  };
DoubleTab & Source_base::calculer (DoubleTab & secmem) const [virtual]
Reimplemented in Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, DP_Impose_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_QDM_Gen, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Force_Centrifuge_VDF_Face_Axi, Source_Neutronique_VDF, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 272 of file Source_base.cpp.
References ajouter().
Referenced by Source::calculer().
{
  secmem = 0;
  return ajouter(secmem);
}
Champs_compris& Source_base::champs_compris () [inline]
Definition at line 110 of file Source_base.h.
References champs_compris_.
  {
    return champs_compris_;
  };
void Source_base::completer (void) [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented in Perte_Charge_CoviMAC, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_EF_base, Source_Generique_base, Perte_Charge_PolyMAC, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Source_QC_QDM_Gen, Terme_Source_Canal_perio, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Source_Neutronique_VDF, Terme_Source_Constituant_VDF_Elem, Terme_Source_VDF_base, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_VEF, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 124 of file Source_base.cpp.
References associer_pb(), associer_zones(), bilan_, MorEqn::equation(), Equation_base::inconnue(), Field_base::nb_comp(), Equation_base::probleme(), DoubleVect::resize(), Deriv_Champ_Inc_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Source::completer().
{
  const Equation_base& eqn = equation();
  const Zone_dis& zdis= eqn.zone_dis();
  const Zone_Cl_dis& zcldis = eqn.zone_Cl_dis();
  associer_zones(zdis, zcldis);
  associer_pb(eqn.probleme());
// Initialize the bilan_ array:
  bilan_.resize(eqn.inconnue().valeur().nb_comp());
  bilan_=0;
}
void Source_base::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented in Source_PDF_EF, DP_Impose_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_Singuliere_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Source_PDF_base, Perte_Charge_Singuliere_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, and Terme_Source_Decroissance_Radioactive_VEF_Face.
Definition at line 281 of file Source_base.cpp.
References ajouter_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), and O_U_Ptr::le_nom().
Referenced by Sources::contribuer_a_avec().
{
  if (!has_interface_blocs()) return;
  DoubleTrav secmem(equation().inconnue().valeurs()); //sera jete
  ajouter_blocs({{ equation().inconnue().le_nom().getString(), &mat}}, secmem, {});
}
void Source_base::contribuer_au_second_membre (DoubleTab &) const [virtual]
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
Definition at line 292 of file Source_base.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Source_base::contribuer_au_second_membre(DoubleTab& ) const uncoded"<<finl;
  exit();
}
virtual void Source_base::contribuer_jacobienne (Matrice_Bloc & , int) const [inline, virtual]
Definition at line 69 of file Source_base.h.
Referenced by Sources::contribuer_jacobienne().
{}
void Source_base::creer_champ (const Motcle & motlu) [virtual]
Implements Champs_compris_interface.
Reimplemented in Source_QC_QDM_Gen.
Definition at line 170 of file Source_base.cpp.
{
}
const Nom Source_base::description () const [inline]
Definition at line 97 of file Source_base.h.
References description_.
Referenced by Source_PDF_base::ouvrir_fichier(), and ouvrir_fichier().
  {
    return description_;
  };
void Source_base::dimensionner (Matrice_Morse & mat) const [virtual]
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
Definition at line 255 of file Source_base.cpp.
References dimensionner_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), and O_U_Ptr::le_nom().
Referenced by Sources::dimensionner().
{
  if (has_interface_blocs()) dimensionner_blocs({{ equation().inconnue().le_nom().getString(), &mat }});
}
void Source_base::dimensionner_bloc_vitesse (Matrice_Morse & mat) const [virtual]
Definition at line 260 of file Source_base.cpp.
References dimensionner_blocs(), and has_interface_blocs().
{
  if (has_interface_blocs()) dimensionner_blocs({{ "vitesse", &mat }});
}
virtual void Source_base::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, and Travail_pression_CoviMAC.
Referenced by dimensionner(), and dimensionner_bloc_vitesse().
virtual int Source_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
const Nom Source_base::fichier () const [inline]
Definition at line 93 of file Source_base.h.
References out_.
  {
    return out_;
  };
const Champ_base & Source_base::get_champ (const Motcle & nom) const [virtual]
Implements Champs_compris_interface.
Reimplemented in Puissance_Thermique_QC_EF, and Source_QC_QDM_Gen.
Definition at line 174 of file Source_base.cpp.
References champs_compris_, and Champs_compris::get_champ().
Referenced by Source_PDF_base::updateChampRho().
{
  return champs_compris_.get_champ(nom);
}
const Type_info * Source_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 34 of file Source_base.cpp.
void Source_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const [virtual]
Implements Champs_compris_interface.
Reimplemented in Puissance_Thermique_QC_EF, and Source_QC_QDM_Gen.
Definition at line 183 of file Source_base.cpp.
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, Champs_compris::liste_noms_compris(), and Objet_U::que_suis_je().
{
  if (opt==DESCRIPTION)
    Cerr<<que_suis_je()<<" : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
}
bool Source_base::has_champ (const Motcle & nom, Ref_Champ_base & ref_champ) const [virtual]
Definition at line 178 of file Source_base.cpp.
References champs_compris_, and Champs_compris::has_champ().
{
  return champs_compris_.has_champ(nom, ref_champ);
}
virtual int Source_base::has_interface_blocs () const [inline, virtual]
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, and Travail_pression_CoviMAC.
Definition at line 72 of file Source_base.h.
Referenced by ajouter(), contribuer_a_avec(), dimensionner(), and dimensionner_bloc_vitesse().
  {
    return 0;
  };
int Source_base::impr (Sortie & os) const [virtual]
Reimplemented in Source_PDF_EF, Terme_Source_EF_base, Source_QC_QDM_Gen, and Source_PDF_base.
Definition at line 209 of file Source_base.cpp.
References Sortie::add_col(), bilan_, Cerr, MorEqn::equation(), finl, Process::je_suis_maitre(), mp_sum_for_each_item(), out_, ouvrir_fichier(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), DoubleVect::size(), and Schema_Temps_base::temps_courant().
Referenced by Source::impr().
{
  if (out_=="??")
    {
// Cerr << "No balance printed for " << que_suis_je() << finl;
    }
  else
    {
      int nb_compo=bilan_.size();
      if (nb_compo==0)
        {
          Cerr << "No balance printed for " << que_suis_je() << finl;
          Cerr << "cause bilan_ array is not filled." << finl;
        }
      else
        {
          int flag=je_suis_maitre();
          SFichier Flux;
          ouvrir_fichier(Flux,"",flag);
          const Probleme_base& pb=equation().probleme();
          const Schema_Temps_base& sch=pb.schema_temps();
          double temps=sch.temps_courant();
          if(Process::je_suis_maitre())
            Flux.add_col(temps);
          DoubleVect bilan_p(bilan_);
          mp_sum_for_each_item(bilan_p);
          /*
          for(int k=0; k<nb_compo; k++)
               bilan_(k)=Process::mp_sum(bilan_(k)); */
// Replaced by:
// mp_sum_for_each_item(bilan_); // Fixed bug: double line!
          if (Process::je_suis_maitre())
            {
              for(int k=0; k<nb_compo; k++)
                Flux.add_col(bilan_p(k));
              Flux << finl;
            }
        }
    }
  return 1;
}
const Type_info * Source_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 34 of file Source_base.cpp.
int Source_base::initialiser (double temps) [virtual]
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
Reimplemented in Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VEF_base, and Terme_Source_VEF_base.
Definition at line 325 of file Source_base.cpp.
References mettre_a_jour().
Referenced by Source::initialiser().
{
  mettre_a_jour(temps);
  return 1;
}
void Source_base::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_Qdm_EF, Source_Scalaire_EF, Source_Generique_base, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_QDM_Gen, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_QC_VEF_Face, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, and Terme_Source_Th_TdivU_VEF_Face.
Definition at line 97 of file Source_base.cpp.
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by initialiser(), and Source::mettre_a_jour().
{
  Cerr << finl;
  Cerr << "You must to overload the method Source_base::mettre_a_jour() because there's big" << finl;
  Cerr << "chances that the source term " <<  que_suis_je() << " must be updated," << finl;
  Cerr << "especially if your source has a field, you must update it..." << finl << finl;
  exit();
}
void Source_base::ouvrir_fichier (SFichier & os, const Nom & type, const int & flag = 1) const [virtual]
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
Reimplemented in Source_PDF_base, and Terme_Source_Constituant_VDF_Elem.
Definition at line 347 of file Source_base.cpp.
References Sortie::add_col(), Cerr, col_width_, description(), MorEqn::equation(), Process::exit(), finl, Nom::getString(), Schema_Temps_base::gnuplot_header(), Probleme_base::le_nom(), max(), Schema_Temps_base::nb_impr(), out_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie::set_col_width(), Sortie_Fichier_base::setf(), and Schema_Temps_base::wcol().
Referenced by impr().
{
// flag nul on n'ouvre pas le fichier
  if (flag==0)
    return ;
// ToDo provisoire:
  counters[type.getString()]++;
  if (counters[type.getString()]>1 && type!="")
    {
      Cerr << "Code should be rewritten to have only one call to Source_base::ouvrir_fichier for " << type << " source and not " << counters[type.getString()] << " times." << finl;
      Process::exit();
    }
  const Probleme_base& pb=equation().probleme();
  const Schema_Temps_base& sch=pb.schema_temps();
  const int& precision = sch.precision_impr(), wcol = max(col_width_, sch.wcol()), gnuplot_header = sch.gnuplot_header();
  os.set_col_width(wcol);
  Nom nomfichier(out_);
  if (type!="") nomfichier+=(Nom)"_"+type;
  nomfichier+=".out";
// On cree le fichier a la premiere impression avec l'en tete
  if (sch.nb_impr()==1 && !pb.reprise_effectuee())
    {
      os.ouvrir(nomfichier);
      SFichier& fic=os;
      Nom espace="\t\t";
      fic << (Nom)"# Printing of the source term "+que_suis_je()+" of the equation "+equation().que_suis_je()+" of the problem "+equation().probleme().le_nom() << finl;
      fic << "# " << description() << finl;
      if (!gnuplot_header) fic << "#";
      os.set_col_width(wcol - !gnuplot_header);
      fic.add_col("Time");
      os.set_col_width(wcol);
      fic << finl;
    }
// Sinon on l'ouvre
  else
    {
      os.ouvrir(nomfichier,ios::app);
    }
  os.precision(precision);
  os.setf(ios::scientific);
}
Sortie & Source_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 53 of file Source_base.cpp.
{
  return os;
}
Entree & Source_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 75 of file Source_base.cpp.
{
  return is;
}
Source_base & Source_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 34 of file Source_base.cpp.
const Source_base & Source_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 34 of file Source_base.cpp.
void Source_base::set_description (const Nom & nom) [inline]
Definition at line 89 of file Source_base.h.
References description_.
Referenced by Terme_Source_Canal_perio::completer(), Terme_Source_Constituant_VEF_Face::readOn(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Source_Dirac_VEF_Face::readOn(), Source_Darcy_VEF_Face::readOn(), Perte_Charge_Singuliere_VEF_Face::readOn(), Terme_Source_Constituant_VDF_Elem::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::readOn(), Terme_Gravite_VDF_Face::readOn(), Source_Forchheimer_VDF_Face::readOn(), Source_Echange_Th_VDF::readOn(), Source_Dirac_VDF_Elem::readOn(), Source_Darcy_VDF_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Terme_Source_Constituant_PolyMAC_Elem::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), DP_Impose_PolyMAC_Face::readOn(), Terme_Source_Constituant_CoviMAC_Elem::readOn(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::readOn(), Terme_Puissance_Thermique_CoviMAC_base::readOn(), Perte_Charge_Singuliere_CoviMAC_Face::readOn(), and DP_Impose_CoviMAC_Face::readOn().
  {
    description_=nom;
  };
void Source_base::set_fichier (const Nom & nom)
Definition at line 391 of file Source_base.cpp.
References MorEqn::equation(), Probleme_base::le_nom(), Objet_U::nom_du_cas(), out_, and Equation_base::probleme().
Referenced by Terme_Source_Canal_perio::completer(), Terme_Source_Constituant_VEF_Face::readOn(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Source_Dirac_VEF_Face::readOn(), Source_Darcy_VEF_Face::readOn(), Perte_Charge_Singuliere_VEF_Face::readOn(), Terme_Source_Constituant_VDF_Elem::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::readOn(), Terme_Gravite_VDF_Face::readOn(), Source_Forchheimer_VDF_Face::readOn(), Source_Echange_Th_VDF::readOn(), Source_Dirac_VDF_Elem::readOn(), Source_Darcy_VDF_Face::readOn(), Perte_Charge_Singuliere_VDF_Face::readOn(), Terme_Source_Constituant_PolyMAC_Elem::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::readOn(), Perte_Charge_Singuliere_PolyMAC_Face::readOn(), DP_Impose_PolyMAC_Face::readOn(), Terme_Source_Constituant_CoviMAC_Elem::readOn(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::readOn(), Terme_Puissance_Thermique_CoviMAC_base::readOn(), Perte_Charge_Singuliere_CoviMAC_Face::readOn(), and DP_Impose_CoviMAC_Face::readOn().
{
  out_=Objet_U::nom_du_cas();
  out_+="_";
  out_+=equation().probleme().le_nom()+"_"+nom;
}
Member Data Documentation
DoubleVect Source_base::bilan_ [mutable, protected]
Vecteur contenant les valeurs du terme source dans le domaine.
Definition at line 122 of file Source_base.h.
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), bilan(), completer(), impr(), and Source_PDF_EF::impr().
Champs_compris Source_base::champs_compris_ [protected]
Reimplemented in Puissance_Thermique_QC_EF.
Definition at line 124 of file Source_base.h.
Referenced by champs_compris(), get_champ(), get_noms_champs_postraitables(), has_champ(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Source_Scalaire_EF::readOn(), Puissance_Thermique_EF::readOn(), and Terme_Puissance_Thermique_CoviMAC_base::readOn().
int Source_base::col_width_ = 0 [protected]
Definition at line 119 of file Source_base.h.
Referenced by ouvrir_fichier().
Nom Source_base::description_ [protected]
Description du terme source.
Definition at line 121 of file Source_base.h.
Referenced by description(), and set_description().
const Type_info Source_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in DP_Impose_CoviMAC_Face, Perte_Charge_Anisotrope_CoviMAC_Face, Perte_Charge_Circulaire_CoviMAC_Face, Perte_Charge_CoviMAC, Perte_Charge_CoviMAC_Face, Perte_Charge_Directionnelle_CoviMAC_Face, Perte_Charge_Isotrope_CoviMAC_Face, Perte_Charge_Singuliere_CoviMAC_Face, Terme_Boussinesq_CoviMAC_Face, Terme_Puissance_Thermique_CoviMAC_base, Terme_Puissance_Thermique_CoviMAC_Elem, Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC, Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_CoviMAC_base, Terme_Source_Decroissance_Radioactive_P0_CoviMAC, Terme_Source_Qdm_Face_CoviMAC, Puissance_Thermique_EF, Source_PDF_EF, Source_Qdm_EF, Source_Scalaire_EF, Terme_Source_EF_base, Source_dep_inco_base, Source_Generique_base, Source_Generique_P0_Elem, DP_Impose_PolyMAC_Face, Perte_Charge_Anisotrope_PolyMAC_Face, Perte_Charge_Circulaire_PolyMAC_Face, Perte_Charge_Directionnelle_PolyMAC_Face, Perte_Charge_Isotrope_PolyMAC_Face, Perte_Charge_PolyMAC, Perte_Charge_PolyMAC_Face, Perte_Charge_Singuliere_PolyMAC_Face, Source_Generique_Face_PolyMAC, Terme_Boussinesq_PolyMAC_Face, Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC, Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Decroissance_Radioactive_P0_PolyMAC, Terme_Source_PolyMAC_base, Terme_Source_Qdm_Face_PolyMAC, Source_Chaleur_Fluide_Dilatable_base, Source_Gravite_Fluide_Dilatable_base, Puissance_Thermique_QC_EF, Source_QC_Chaleur, Source_QC_Chaleur_Verif, Source_QC_Chaleur_Verif_VEF, Source_QC_Chaleur_Verif_VEF_P1NC, Source_QC_QDM_Gen, Source_QC_Chaleur_VDF, Source_QC_Gravite_VDF, Acceleration_QC_VDF_Face, Source_qdm_QC_VDF_Face, Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Darcy_QC_VDF_Face, Forchheimer_QC_VDF_Face, Terme_Puissance_Thermique_QC_VDF_Elem, Source_QC_Chaleur_VEF, Source_QC_Gravite_VEF, Acceleration_QC_VEF_P1NC, Perte_Charge_Circulaire_QC_VEF_P1NC, Perte_Charge_Anisotrope_QC_VEF_P1NC, Perte_Charge_Directionnelle_QC_VEF_P1NC, Perte_Charge_Isotrope_QC_VEF_P1NC, Perte_Charge_Reguliere_QC_VEF_P1NC, Perte_Charge_Singuliere_QC_VEF_P1NC, Source_qdm_QC_VEF_P1NC, Darcy_QC_VEF_P1NC, Forchheimer_QC_VEF_P1NC, Terme_Puissance_Thermique_QC_VEF_Face, Source_WC_Chaleur, Source_WC_Chaleur_VDF, Source_WC_Gravite_VDF, Source_WC_Chaleur_VEF, Source_WC_Gravite_VEF, Source_PDF_base, Terme_Boussinesq_base, Terme_Source_Acceleration, Terme_Source_Canal_perio, Flux_interfacial_CoviMAC, Frottement_interfacial_CoviMAC, Travail_pression_CoviMAC, Source_Neutronique, Force_Centrifuge_VDF_Face_Axi, Perte_Charge_Reguliere_VDF_Face, Perte_Charge_Singuliere_VDF_Face, Perte_Charge_VDF_Face, Source_Darcy_VDF_Face, Source_Dirac_VDF_Elem, Source_Echange_Th_VDF, Source_Forchheimer_VDF_Face, Source_Generique_VDF_Face, Source_Neutronique_VDF, Terme_Boussinesq_VDF_Face, Terme_Gravite_VDF_Face, Terme_Puissance_Thermique_Echange_Impose_P0_VDF, Terme_Puissance_Thermique_VDF_base, Terme_Puissance_Thermique_VDF_Elem, Terme_Source_Acceleration_VDF_Face, Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_RANS_LES_VDF_Elem, Terme_Source_Canal_RANS_LES_VDF_Face, Terme_Source_Constituant_VDF_Elem, Terme_Source_Coriolis_VDF_Face, Terme_Source_Coriolis_QC_VDF_Face, Terme_Source_inc_th_VDF_Face, Terme_Source_inc_VDF_Face, Terme_Source_Qdm_VDF_Face, Terme_Source_Solide_SWIFT_VDF, Terme_Source_VDF_base, Perte_Charge_Anisotrope_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Reguliere_VEF_P1NC, Perte_Charge_Singuliere_VEF_Face, Perte_Charge_VEF, Perte_Charge_VEF_Face, Source_Darcy_VEF_Face, Source_Dirac_VEF_Face, Source_Forchheimer_VEF_Face, Source_Generique_VEF, Terme_Boussinesq_VEF_Face, Terme_Boussinesq_VEFPreP1B_Face, Terme_Puissance_Thermique_Echange_Impose_VEF_Face, Terme_Puissance_Thermique_VEF_base, Terme_Puissance_Thermique_VEF_Face, Terme_Source_Acceleration_VEF_Face, Terme_Source_Canal_perio_VEF_P1NC, Terme_Source_Canal_perio_QC_VEF_P1NC, Terme_Source_Canal_RANS_LES_VEF_Face, Terme_Source_Constituant_VEF_Face, Terme_Source_Decroissance_Radioactive_VEF_Face, Terme_Source_Qdm_lambdaup_VEF_Face, Terme_Source_Qdm_VEF_Face, Terme_Source_Rappel_T_VEF_Face, Terme_Source_Th_TdivU_VEF_Face, and Terme_Source_VEF_base.
Definition at line 51 of file Source_base.h.
Nom Source_base::out_ [protected]
Nom du fichier .out pour l'impression.
Definition at line 120 of file Source_base.h.
Referenced by fichier(), impr(), Source_PDF_EF::impr(), Source_PDF_base::ouvrir_fichier(), ouvrir_fichier(), and set_fichier().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Source_base.h
src/Kernel/Framework/Source_base.cpp