TRUST: Remove_elem Class Reference
Remove_elem Class Reference
#include <Remove_elem.h>
Public Member Functions
Remove_elem ()
~Remove_elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
void Remove_elem_ (Zone &)
void recreer_faces (Zone &, Faces &, IntTab &) const
void creer_faces (Zone &, Faces &, IntTab &) const
void remplir_liste (IntTab &, int, int, int, int) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Remove_elem & self_cast (Objet_U &)
static const Remove_elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
IntList listelem
Parser_U f
int f_ok
Private Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Detailed Description
Definition at line 42 of file Remove_elem.h.
Constructor & Destructor Documentation
Remove_elem::Remove_elem ()
Definition at line 30 of file Remove_elem.cpp.
Remove_elem::~Remove_elem ()
Definition at line 30 of file Remove_elem.cpp.
Member Function Documentation
Objet_U * Remove_elem::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 30 of file Remove_elem.cpp.
void Remove_elem::creer_faces (Zone & zone, Faces & faces, IntTab & som_face) const
< nombre de sommets par face
Definition at line 151 of file Remove_elem.cpp.
References IntTab::dimension(), Objet_U::dimension, DoubleTab::dimension(), Faces::dimensionner(), Interprete_geometrique_base::domaine(), Domaine::les_sommets(), Faces::les_sommets(), IntTab::ref(), and IntTab::resize().
Referenced by Remove_elem_().
{
  faces.dimensionner(1);
  IntTab& sommets=faces.les_sommets();
  int nbsom=domaine().les_sommets().dimension(0);
  int nbs = (dimension==2) ? 2 : 4 ;  //!< nombre de sommets par face
  IntTab faces_recreees(1,nbs);
  int ii=0;
  for(int i=0; i<nbsom; i++)
    {
      for(int j=0 ; j<som_face.dimension(2); j++)
        {
          if(som_face(i,0,j)!=-1)
            {
              faces_recreees.resize(ii+1,nbs);
              faces_recreees(ii,0) = i;
              faces_recreees(ii,1) = som_face(i,0,j);
              if(dimension==3)
                {
                  faces_recreees(ii,2) = som_face(i,1,j);
                  faces_recreees(ii,3) = som_face(i,2,j);
                }
              ii++;
            }
        }
    }
  faces.dimensionner(ii);
  sommets.ref(faces_recreees);
}
int Remove_elem::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 30 of file Remove_elem.cpp.
const Type_info * Remove_elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Remove_elem.cpp.
const Type_info * Remove_elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Remove_elem.cpp.
Entree & Remove_elem::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 62 of file Remove_elem.cpp.
References Parser_U::addVar(), Param::ajouter(), Param::ajouter_non_std(), Interprete_geometrique_base::associer_domaine(), Cerr, Interprete_geometrique_base::domaine(), f, f_ok, finl, Scatter::init_sequential_domain(), Param::lire_avec_accolades_depuis(), Domaine::nb_zones(), NettoieNoeuds::nettoie(), Parser_U::parseString(), Objet_U::que_suis_je(), Remove_elem_(), Parser_U::setNbVar(), Parser_U::setString(), and Scatter::uninit_sequential_domain().
{
  associer_domaine(is);
  Param param(que_suis_je());
  Nom fonction;
  param.ajouter_non_std("liste",this);
  param.ajouter("fonction",&fonction);
  param.lire_avec_accolades_depuis(is);
  if (fonction=="??")
    f_ok=0;
  else
    {
      Cerr << "Reading and interpretation of the function " << fonction << " ... ";
      f.setNbVar(3);
      f.setString(fonction);
      f.addVar("x");
      f.addVar("y");
      f.addVar("z");
      f.parseString();
      f_ok=1;
      Cerr << " Ok" << finl;
    }
  Scatter::uninit_sequential_domain(domaine());
  for(int i=0; i<domaine().nb_zones() ; i++)
    {
      Remove_elem_(domaine().zone(i));
    }
  Scatter::init_sequential_domain(domaine());
  NettoieNoeuds::nettoie(domaine());
  Cerr << "Refinement... OK" << finl;
  return is;
}
int Remove_elem::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [private, virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Objet_U.
Definition at line 42 of file Remove_elem.cpp.
References IntList::add(), Cerr, Process::exit(), finl, listelem, and Objet_U::que_suis_je().
{
  if (mot=="liste")
    {
      int nb_elem,elem;
      is >> nb_elem;
      for (int i=0; i<nb_elem; i++)
        {
          is >> elem;
          listelem.add(elem);
        }
      return 1;
    }
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return 0;
}
Sortie & Remove_elem::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 32 of file Remove_elem.cpp.
{
  return Interprete::printOn(os);
}
Entree & Remove_elem::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 37 of file Remove_elem.cpp.
{
  return Interprete::readOn(is);
}
void Remove_elem::recreer_faces (Zone & zone, Faces & faces, IntTab & som_face) const
< nombre de sommets par face
< ordonnancement des indices pour eviter les mauvaises surprises de numerotations d'indices
< on "supprime" la face en reinitialisant a -1 les indices
Definition at line 96 of file Remove_elem.cpp.
References Objet_U::dimension, IntTab::dimension(), Faces::les_sommets(), ArrOfInt::ordonne_array(), IntTab::ref(), IntTab::reset(), and IntTab::resize().
Referenced by Remove_elem_().
{
  IntTab& sommets=faces.les_sommets();
  int nb_faces=sommets.dimension(0);
  int nbs = (dimension==2) ? 2 : 4 ;  //!< nombre de sommets par face
  IntTab faces_recreees(nb_faces,nbs);
  int ii=0;
  for(int i=0; i<nb_faces; i++)
    {
      ArrOfInt ind(4);
      ind[0]=sommets(i,0);
      ind[1]=sommets(i,1);
      ind[2]=(dimension==3) ? sommets(i,2) : -1;
      ind[3]=(dimension==3) ? sommets(i,3) : -1;
      ind.ordonne_array(); //!< ordonnancement des indices pour eviter les mauvaises surprises de numerotations d'indices
      int trouve=0;
      int j=0;
      for( ; j<som_face.dimension(2); j++)
        {
          if(som_face(ind[3],0,j)==ind[2] && som_face(ind[3],1,j)==ind[1] && som_face(ind[3],2,j)==ind[0])
            {
              trouve=1;
              break;
            }
        }
      if(trouve==1) //!< on "supprime" la face en reinitialisant a -1 les indices
        {
          som_face(ind[3],0,j)=-1 ;
          som_face(ind[3],1,j)=-1 ;
          som_face(ind[3],2,j)=-1 ;
        }
      else
        {
          faces_recreees(ii,0) = sommets(i,0);
          faces_recreees(ii,1) = sommets(i,1);
          if(dimension==3)
            {
              faces_recreees(ii,2) = sommets(i,2);
              faces_recreees(ii,3) = sommets(i,3);
            }
          ii++;
        }
    }
  faces_recreees.resize(ii,nbs);
  sommets.reset();
  sommets.ref(faces_recreees);
}
void Remove_elem::Remove_elem_ (Zone & zone)
< nombre de sommets par element
< nbre de faces connectees a un sommet
Definition at line 223 of file Remove_elem.cpp.
References List_Bord::add(), Elem_geom::calculer_centres_gravite(), Cerr, Zone::construit_octree(), creer_faces(), Objet_U::dimension, DoubleTab::dimension(), IntTab::dimension(), Interprete_geometrique_base::domaine(), Parser_U::eval(), Process::exit(), f, f_ok, Frontiere::faces(), Zone::faces_bord(), Zone::faces_int(), finl, Zone::invalide_octree(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), LIST_CURSEUR, listelem, Zone::nb_som(), Frontiere::nommer(), Faces::quadrangle_3D, Objet_U::que_suis_je(), recreer_faces(), IntTab::ref(), remplir_liste(), Zone::reordonner(), IntTab::resize(), Faces::segment_2D, Parser_U::setVar(), IntList::size(), Zone::type_elem(), Faces::typer(), and Frontiere::typer_faces().
Referenced by interpreter_().
{
  if (zone.type_elem()->que_suis_je() == "Rectangle" || zone.type_elem()->que_suis_je() == "Hexaedre")
    {
      IntTab& les_elems=zone.les_elems();
      int oldsz=les_elems.dimension(0);
      ArrOfInt marq_remove(oldsz);
      int nbsom=domaine().les_sommets().dimension(0);
      int nbs = (dimension==2) ? 4 : 8 ;  //!< nombre de sommets par element
      IntTab new_elems(oldsz,nbs);
      int nbfacesom = (dimension==2) ? 4 : 4*3 ; //!< nbre de faces connectees a un sommet
      IntTab som_face(nbsom,3,nbfacesom);
      som_face=-1;
      if(f_ok)
        {
          DoubleTab xg(oldsz, dimension);
          zone.type_elem()->calculer_centres_gravite(xg);
          for(int i=0; i<oldsz; i++)
            {
              f.setVar(0,xg(i,0));
              f.setVar(1,xg(i,1));
              if(dimension==3) f.setVar(2,xg(i,2));
// if(f.eval()) listelem.add(i);
              if((int)(f.eval()+0.5)) marq_remove[i]=1; //listelem.add(i); //!< pour etre conforme a ce qui est fait dans DecoupeBord
            }
        }
      else
        {
          for (int i=0; i<listelem.size(); i++)
            {
              marq_remove[listelem[i]]=1;
            }
        }
      int j=0;
      Cerr << "-> " << listelem.size() << " elements will be removed from the domain " << domaine().le_nom() << finl;
      /*    if (listelem.size()==0)
        {
          Cerr << "May be an error when applying Remove_elem : no elements found." << finl;
          Process::exit();
      } */
      for(int i=0; i<oldsz; i++)
        {
          if(marq_remove[i]==0)
            {
              for(int k=0; k<nbs; k++) new_elems(j,k) = les_elems(i,k);
              j++;
            }
          else
            {
              if(dimension==2)
                {
                  int i0 = les_elems(i,0);
                  int i1 = les_elems(i,1);
                  int i2 = les_elems(i,2);
                  int i3 = les_elems(i,3);
                  remplir_liste(som_face,i0,i1,-1,-1) ;
                  remplir_liste(som_face,i0,i2,-1,-1) ;
                  remplir_liste(som_face,i1,i3,-1,-1) ;
                  remplir_liste(som_face,i2,i3,-1,-1) ;
                }
              else
                {
                  int i0 = les_elems(i,0);
                  int i1 = les_elems(i,1);
                  int i2 = les_elems(i,2);
                  int i3 = les_elems(i,3);
                  int i4 = les_elems(i,4);
                  int i5 = les_elems(i,5);
                  int i6 = les_elems(i,6);
                  int i7 = les_elems(i,7);
                  remplir_liste(som_face,i0,i1,i2,i3) ;
                  remplir_liste(som_face,i0,i1,i4,i5) ;
                  remplir_liste(som_face,i0,i4,i2,i6) ;
                  remplir_liste(som_face,i1,i5,i3,i7) ;
                  remplir_liste(som_face,i2,i3,i6,i7) ;
                  remplir_liste(som_face,i4,i5,i6,i7) ;
                }
            }
        }
      new_elems.resize(j,nbs);
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      zone.invalide_octree();
      zone.construit_octree();
      zone.reordonner();
      {
        Cerr << " Regeneration of boundaries" << finl;
        LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            if(dimension==2) les_faces.typer(Faces::segment_2D);
            else             les_faces.typer(Faces::quadrangle_3D);
            recreer_faces(zone, les_faces, som_face);
            ++curseur;
          }
        Cerr << " addition of a new boundary issued from removed elements" << finl;
        Bord& new_bord=zone.faces_bord().add(Bord());
        new_bord.nommer("newBord");
        if(dimension==2) new_bord.typer_faces(Faces::segment_2D);
        else             new_bord.typer_faces(Faces::quadrangle_3D);
        Faces& les_faces=new_bord.faces();
        creer_faces(zone, les_faces, som_face);
      }
      {
// Les Faces internes
        Cerr << "Regeneration of internal faces" << finl;
        LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            if(dimension==2) les_faces.typer(Faces::segment_2D);
            else             les_faces.typer(Faces::quadrangle_3D);
            recreer_faces(zone, les_faces, som_face);
            ++curseur;
          }
      }
      Cerr<<"END of Remove_elem..."<<finl;
      Cerr<<"  1 NbElem="<<zone.les_elems().dimension(0)<<"  NbNod="<<zone.nb_som()<<finl;
    }
  else
    {
      Cerr << "We do not yet know how to Remove_elem the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
      exit();
    }
}
void Remove_elem::remplir_liste (IntTab & som_face, int ind1, int ind2, int ind3, int ind4) const
< ordonnancement des indices pour eviter les mauvaises surprises de numerotations d'indices (rencontrees prealablement)
< on "supprime" la face en reinitialisant a -1 les indices concernes
< on "ajoute" la face en affectant les indices aux premieres cases "libres" (=-1)
Definition at line 184 of file Remove_elem.cpp.
References IntTab::dimension(), and ArrOfInt::ordonne_array().
Referenced by Remove_elem_().
{
  ArrOfInt ind(4);
  ind[0]=ind1;
  ind[1]=ind2;
  ind[2]=ind3;
  ind[3]=ind4;
  ind.ordonne_array(); //!< ordonnancement des indices pour eviter les mauvaises surprises de numerotations d'indices (rencontrees prealablement)
  int trouve=0;
  int j=0;
  for( ; j<som_face.dimension(2); j++)
    {
      if(som_face(ind[3],0,j)==ind[2] && som_face(ind[3],1,j)==ind[1] && som_face(ind[3],2,j)==ind[0])
        {
          trouve=1;
          break;
        }
    }
  if(trouve==1) //!< on "supprime" la face en reinitialisant a -1 les indices concernes
    {
      som_face(ind[3],0,j)=-1 ;
      som_face(ind[3],1,j)=-1 ;
      som_face(ind[3],2,j)=-1 ;
    }
  else //!< on "ajoute" la face en affectant les indices aux premieres cases "libres" (=-1)
    {
      for(j=0; j<som_face.dimension(2); j++)
        {
          if(som_face(ind[3],0,j)==-1) break;
        }
      som_face(ind[3],0,j)=ind[2] ;
      som_face(ind[3],1,j)=ind[1] ;
      som_face(ind[3],2,j)=ind[0] ;
    }
}
Remove_elem & Remove_elem::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Remove_elem.cpp.
const Remove_elem & Remove_elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Remove_elem.cpp.
unsigned Remove_elem::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 30 of file Remove_elem.cpp.
Member Data Documentation
Parser_U Remove_elem::f [protected]
Definition at line 57 of file Remove_elem.h.
Referenced by interpreter_(), and Remove_elem_().
int Remove_elem::f_ok [protected]
Definition at line 58 of file Remove_elem.h.
Referenced by interpreter_(), and Remove_elem_().
const Type_info Remove_elem::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 44 of file Remove_elem.h.
IntList Remove_elem::listelem [protected]
Definition at line 56 of file Remove_elem.h.
Referenced by lire_motcle_non_standard(), and Remove_elem_().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Remove_elem.h
src/Kernel/Geometrie/Remove_elem.cpp