TRUST: Entree_complete Class Reference
Entree_complete Class Reference
Cette classe se comporte comme EChaine tant que l'on n'est pas
a la fin de la chaine. La suite est lue dans entree2 passee en parametre.
check_types() et error_action() sont identiques a ceux de entree2.
#include <Entree_complete.h>
Public Member Functions
Entree_complete (const char *str, Entree &entree2)
~Entree_complete ()
Entree & operator>> (int &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
Entree & operator>> (long &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
Entree & operator>> (float &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
Entree & operator>> (double &ob)
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
int get (int *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (long *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (float *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (double *ob, int n)
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
int eof ()
int fail ()
int good ()
int set_bin (int bin)
Il est interdit de changer de type d'entree. exit()
void set_error_action (Error_Action)
affecte la valeur aux deux entrees sources
Attention, la valeur de entree2 est modifiee !
Voir Entree::set_error_action()
void set_check_types (int flag)
affecte le drapeau aux deux entrees sources
Attention, le drapeau de entree2 est modifie !
Voir Entree::set_check_types()
Protected Member Functions
Entree & get_input ()
Protected Attributes
int num_entree_
int str_size_
EChaine chaine_str_
Entree * entree2_
Detailed Description
Cette classe se comporte comme EChaine tant que l'on n'est pas
a la fin de la chaine. La suite est lue dans entree2 passee en parametre.
check_types() et error_action() sont identiques a ceux de entree2.
Definition at line 37 of file Entree_complete.h.
Constructor & Destructor Documentation
Entree_complete::Entree_complete (const char * str, Entree & entree2)
Definition at line 31 of file Entree_complete.cpp.
References chaine_str_, Entree::check_types(), entree2_, finl, Entree::get_error_action(), EChaine::init(), Process::Journal(), num_entree_, Entree::set_check_types(), set_check_types(), Entree::set_error_action(), set_error_action(), and str_size_.
{
  num_entree_ = 0;
  str_size_ = strlen(str_entree1);
  chaine_str_.init(str_entree1);
  Process::Journal() << "Construction of a Entree_complete with : " << str_entree1 << finl;
  entree2_ = &entree2;
  num_entree_ = 0;
  Error_Action action = entree2.get_error_action();
  Entree::set_error_action(action);
  chaine_str_.set_error_action(action);
  int check_types_sa = entree2.check_types();
  Entree::set_check_types(check_types_sa);
  chaine_str_.set_check_types(check_types_sa);
}
Entree_complete::~Entree_complete ()
Definition at line 47 of file Entree_complete.cpp.
References entree2_.
{
  entree2_ = 0;
}
Member Function Documentation
int Entree_complete::eof () [virtual]
Reimplemented from Entree.
Definition at line 150 of file Entree_complete.cpp.
References Entree::eof(), and get_input().
{
  Entree& is = get_input();
  return is.eof();
}
int Entree_complete::fail () [virtual]
Reimplemented from Entree.
Definition at line 156 of file Entree_complete.cpp.
References Entree::fail(), and get_input().
{
  Entree& is = get_input();
  return is.fail();
}
int Entree_complete::get (char * buf, int bufsize) [virtual]
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented from Entree.
Definition at line 64 of file Entree_complete.cpp.
References Entree::get(), and get_input().
{
  Entree& is = get_input();
  return is.get(ob, bufsize);
}
int Entree_complete::get (int * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 78 of file Entree_complete.cpp.
References Entree::get(), and get_input().
{
// Je fais une boucle pour permettre au tableau de valeurs d'etre
// a cheval sur les deux entrees:
  for (int i = 0; i < n; i++)
    {
      Entree& is = get_input();
      if (! is.get(ob+i, 1))
        return 0;
    }
  return 1;
}
int Entree_complete::get (double * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 137 of file Entree_complete.cpp.
References Entree::get(), and get_input().
{
// Je fais une boucle pour permettre au tableau de valeurs d'etre
// a cheval sur les deux entrees:
  for (int i = 0; i < n; i++)
    {
      Entree& is = get_input();
      if (! is.get(ob+i, 1))
        return 0;
    }
  return 1;
}
int Entree_complete::get (long * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 98 of file Entree_complete.cpp.
References Entree::get(), and get_input().
{
// Je fais une boucle pour permettre au tableau de valeurs d'etre
// a cheval sur les deux entrees:
  for (int i = 0; i < n; i++)
    {
      Entree& is = get_input();
      if (! is.get(ob+i, 1))
        return 0;
    }
  return 1;
}
int Entree_complete::get (float * ob, int n) [virtual]
methode virtuelle pour lire un tableau d'ints ou reels<br>(le tableau doit avoir la bonne dimension: attention pas de verification possible)
Voir aussi operator>>()
Reimplemented from Entree.
Definition at line 118 of file Entree_complete.cpp.
References Entree::get(), and get_input().
{
// Je fais une boucle pour permettre au tableau de valeurs d'etre
// a cheval sur les deux entrees:
  for (int i = 0; i < n; i++)
    {
      Entree& is = get_input();
      if (! is.get(ob+i, 1))
        return 0;
    }
  return 1;
}
Entree & Entree_complete::get_input () [protected]
Definition at line 52 of file Entree_complete.cpp.
References chaine_str_, entree2_, Entree::get_istream(), and num_entree_.
Referenced by eof(), fail(), get(), good(), and operator>>().
{
  if (num_entree_ == 0)
    {
      int pos = chaine_str_.get_istream().tellg();
      if (pos < str_size_ && pos >= 0)
        return chaine_str_;
      num_entree_ = 1;
    }
  return *entree2_;
}
int Entree_complete::good () [virtual]
Reimplemented from Entree.
Definition at line 162 of file Entree_complete.cpp.
References get_input(), and Entree::good().
{
  Entree& is = get_input();
  return is.good();
}
Entree & Entree_complete::operator>> (double & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 130 of file Entree_complete.cpp.
References get_input().
{
  Entree& is = get_input();
  is >> ob;
  return *this;
}
Entree & Entree_complete::operator>> (int & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 71 of file Entree_complete.cpp.
References get_input().
{
  Entree& is = get_input();
  is >> ob;
  return *this;
}
Entree & Entree_complete::operator>> (long & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 91 of file Entree_complete.cpp.
References get_input().
{
  Entree& is = get_input();
  is >> ob;
  return *this;
}
Entree & Entree_complete::operator>> (float & ob) [virtual]
methode virtuelle pour lire un int ou un reel.
Dans cette classe de base, on lit dans le istream avec read() (si is_bin() == 1)
ou avec operator>>() (si is_bin() == 0). Si le drapeau check_types est mis,
on appelle convert_to() pour verifier les types des objets lus.
Dans ce cas, pour les ints on comprend les formats 123 (decimal),
0xa345 (hexa) et autres.
Si une erreur se produit, on appelle error_handle_()
Note pour les programmeurs des classes derivees:
L'implementation de cette methode doit toujours passer par hande_error()
< Bien appeler get de cette classe
Reimplemented from Entree.
Definition at line 111 of file Entree_complete.cpp.
References get_input().
{
  Entree& is = get_input();
  is >> ob;
  return *this;
}
int Entree_complete::set_bin (int bin) [virtual]
Il est interdit de changer de type d'entree. exit()
Reimplemented from Entree.
Definition at line 169 of file Entree_complete.cpp.
References Cerr, Process::exit(), and finl.
{
  if (bin)
    {
      Cerr << "Error in Entree_complete::set_bin(int bin) : not supported" << finl;
      Process::exit();
    }
  return bin;
}
void Entree_complete::set_check_types (int flag) [virtual]
affecte le drapeau aux deux entrees sources
Attention, le drapeau de entree2 est modifie !
Voir Entree::set_check_types()
Reimplemented from Entree.
Definition at line 182 of file Entree_complete.cpp.
References chaine_str_, entree2_, and Entree::set_check_types().
Referenced by Entree_complete().
{
  Entree::set_check_types(flag);
  chaine_str_.set_check_types(flag);
  entree2_->set_check_types(flag);
}
void Entree_complete::set_error_action (Error_Action action) [virtual]
affecte la valeur aux deux entrees sources
Attention, la valeur de entree2 est modifiee !
Voir Entree::set_error_action()
Reimplemented from Entree.
Definition at line 192 of file Entree_complete.cpp.
References chaine_str_, entree2_, and Entree::set_error_action().
Referenced by Entree_complete().
{
  Entree::set_error_action(action);
  chaine_str_.set_error_action(action);
  entree2_->set_error_action(action);
}
Member Data Documentation
EChaine Entree_complete::chaine_str_ [protected]
Definition at line 71 of file Entree_complete.h.
Referenced by Entree_complete(), get_input(), set_check_types(), and set_error_action().
Entree* Entree_complete::entree2_ [protected]
Definition at line 73 of file Entree_complete.h.
Referenced by Entree_complete(), get_input(), set_check_types(), set_error_action(), and ~Entree_complete().
int Entree_complete::num_entree_ [protected]
Definition at line 69 of file Entree_complete.h.
Referenced by Entree_complete(), and get_input().
int Entree_complete::str_size_ [protected]
Definition at line 70 of file Entree_complete.h.
Referenced by Entree_complete().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Entree_complete.h
src/Kernel/Utilitaires/Entree_complete.cpp