TRUST: Op_Correlation Class Reference
Op_Correlation Class Reference
#include <Op_Correlation.h>
Public Member Functions
Op_Correlation ()
~Op_Correlation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
double temps () const override
const Integrale_tps_produit_champs & integrale () const override
const Op_Moyenne & la_moyenne_a () const
const Op_Moyenne & la_moyenne_b () const
const DoubleTab & valeurs_a () const
const DoubleTab & valeurs_b () const
DoubleTab & valeurs_ab ()
double dt_integration_a () const
double dt_integration_b () const
double dt_integration_ab () const
void mettre_a_jour (double tps) override
void initialiser (double val) override
void associer (const Zone_dis_base &, const Champ_base &, double t1, double t2)
void associer (const Zone_dis_base &, const Champ_Generique_base &, double t1, double t2) override
void associer (const Zone_dis_base &, const Champ_Generique_base &, const Champ_Generique_base &, double t1, double t2)
void fixer_tstat_deb (double, double) override
void fixer_tstat_fin (double) override
int completer_post_statistiques (const Domaine &dom, const int is_axi, Format_Post_base &format) override
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
void associer_op_stat (const Operateur_Statistique_tps_base &) override
void completer (const Probleme_base &) override
DoubleTab calculer_valeurs () const override
Public Member Functions inherited from Operateur_Statistique_tps_base
Operateur_Statistique_tps_base ()
~Operateur_Statistique_tps_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Nom & localisation_post () const
void associer (const Nom &loc_post)
virtual void associer_op_stat (const Operateur_Statistique_tps_base &)
virtual void associer (const Zone_dis_base &, const Champ_Generique_base &, double, double)=0
virtual void fixer_tstat_deb (double, double)=0
virtual void fixer_tstat_fin (double)=0
virtual void mettre_a_jour (double temps)=0
const Nom & le_nom () const override=0
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual double temps () const =0
virtual const Integrale_tps_Champ & integrale () const =0
virtual void initialiser (double val)=0
virtual void completer (const Probleme_base &)=0
virtual DoubleTab calculer_valeurs () const =0
virtual int completer_post_statistiques (const Domaine &dom, const int is_axi, Format_Post_base &format)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Correlation & self_cast (Objet_U &)
static const Op_Correlation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Statistique_tps_base
static const Type_info * info ()
static Operateur_Statistique_tps_base & self_cast (Objet_U &)
static const Operateur_Statistique_tps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Statistique_tps_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Operateur_Statistique_tps_base
Sortie & printOn (Sortie &x) const override
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Op_Moyenne la_moyenne_a_
Ref_Op_Moyenne la_moyenne_b_
Ref_Integrale_tps_Champ integrale_tps_a_
Ref_Integrale_tps_Champ integrale_tps_b_
Integrale_tps_produit_champs integrale_tps_ab_
Protected Attributes inherited from Operateur_Statistique_tps_base
Nom localisation_post_
Detailed Description
Definition at line 26 of file Op_Correlation.h.
Constructor & Destructor Documentation
Op_Correlation()
Op_Correlation::Op_Correlation ()
Definition at line 21 of file Op_Correlation.cpp.
~Op_Correlation()
Op_Correlation::~Op_Correlation ()
Definition at line 21 of file Op_Correlation.cpp.
Member Function Documentation
associer() [1/3]
void Op_Correlation::associer (const Zone_dis_base & une_zdis, const Champ_base & le_champ, double t1, double t2) inline
Definition at line 119 of file Op_Correlation.h.
{
  Cerr << "Exactly two fields must be associated to Correlation operator." << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by Champ_Generique_Correlation::completer().
associer() [2/3]
void Op_Correlation::associer (const Zone_dis_base & une_zdis, const Champ_Generique_base & le_champ_a, const Champ_Generique_base & le_champ_b, double t1, double t2) inline
Definition at line 131 of file Op_Correlation.h.
{
  Champ espace_stockage_source;
  const Champ_base& source = le_champ_a.get_champ(espace_stockage_source);
  Nom type_le_champ = source.que_suis_je();
  int renomme;
  renomme=0;
  if (type_le_champ.debute_par("Champ"))
    renomme=1;
  type_le_champ.suffix("Champ_");
  type_le_champ.suffix("Fonc_");
  Nom type("Champ_Fonc_");
  if (renomme==1)
    type+=type_le_champ;
  else
    type = type_le_champ;
  integrale_tps_ab_.typer(type);
  integrale_tps_ab_.associer_zone_dis_base(une_zdis);
  integrale_tps_ab_.associer(le_champ_a,le_champ_b,1,1,t1,t2);
}
References Integrale_tps_produit_champs::associer(), Champ_Fonc::associer_zone_dis_base(), Nom::debute_par(), Champ_Generique_base::get_champ(), integrale_tps_ab_, Objet_U::que_suis_je(), Nom::suffix(), and Deriv_::typer().
associer() [3/3]
void Op_Correlation::associer (const Zone_dis_base & une_zdis, const Champ_Generique_base & le_champ, double t1, double t2) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 125 of file Op_Correlation.h.
{
  Cerr << "Exactly two fields must be associated to Correlation operator." << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
associer_op_stat()
void Op_Correlation::associer_op_stat (const Operateur_Statistique_tps_base & un_op_stat) inline override virtual
Reimplemented from Operateur_Statistique_tps_base.
Definition at line 96 of file Op_Correlation.h.
{
  if (!la_moyenne_a_.non_nul())
    la_moyenne_a_ = ref_cast(Op_Moyenne,un_op_stat);
  else if (!la_moyenne_b_.non_nul())
    la_moyenne_b_ = ref_cast(Op_Moyenne,un_op_stat);
  else
    {
      Cerr << "Op_Correlation::associer_op_stat : Two operators of type Moyenne have already been associated." << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, la_moyenne_a_, la_moyenne_b_, O_U_Ptr::non_nul(), and ref_cast.
Referenced by Champ_Generique_Correlation::completer().
calculer_valeurs()
DoubleTab Op_Correlation::calculer_valeurs () const override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 198 of file Op_Correlation.cpp.
{
  Integrale_tps_produit_champs correlation(integrale_tps_ab_);
  const double dt_ab = dt_integration_ab();
  if ( dt_ab > 0 )
    {
// On calcule Moyenne(a'b')=Moyenne(ab)-Moyenne(a)*Moyenne(b)
      correlation.valeurs() /= dt_ab;
      const double dt_a = dt_integration_a();
      const double dt_b = dt_integration_b();
      assert(est_egal(dt_a,dt_ab));
      assert(est_egal(dt_b,dt_ab));
      correlation.ajoute_produit_tensoriel(-1/(dt_a*dt_b),integrale_tps_a_.valeur().valeur(),integrale_tps_b_.valeur().valeur());
    }
  return correlation.valeurs();
}
References Integrale_tps_produit_champs::ajoute_produit_tensoriel(), dt_integration_a(), dt_integration_ab(), dt_integration_b(), est_egal(), integrale_tps_a_, integrale_tps_ab_, integrale_tps_b_, Deriv_Champ_Fonc_base::valeur(), Ref_Integrale_tps_Champ::valeur(), and Champ_Fonc::valeurs().
Referenced by Champ_Generique_Correlation::get_champ().
completer()
void Op_Correlation::completer (const Probleme_base & Pb) override virtual
< B.M.: quoi donner a fixer_nb_valeurs_nodales ???
Implements Operateur_Statistique_tps_base.
Definition at line 45 of file Op_Correlation.cpp.
{
  const REF(Champ_Generique_base)& a = la_moyenne_a().integrale().le_champ();
  const REF(Champ_Generique_base)& b = la_moyenne_b().integrale().le_champ();
  integrale_tps_a_ = la_moyenne_a().integrale();
  integrale_tps_b_ = la_moyenne_b().integrale();
// On recupere la zone discretisee
  const Zone_dis_base& zone = a->get_ref_zone_dis_base();
// Dimensionnement du champ integrale_champ a la meme taille que mon_champ
  const DoubleTab& tab_a = valeurs_a();
  const DoubleTab& tab_b = valeurs_b();
  Champ espace_stockage_source_a, espace_stockage_source_b;
  const Champ_base& source_a = a->get_champ(espace_stockage_source_a);
  const Champ_base& source_b = b->get_champ(espace_stockage_source_b);
  const int nb_compo_a = source_a.nb_comp();
  const int nb_compo_b = source_b.nb_comp();
// Pour utiliser nom_cible uniquement si a et b sont des Champ_Generique_refChamp
// pour pouvoir reproduire le nom des variables dans le lml
  Noms noms_a, noms_b;
  if (!(sub_type(Champ_Generique_refChamp,a.valeur()) && (sub_type(Champ_Generique_refChamp,b.valeur()))))
    {
      noms_a = a->get_property("nom");
      noms_b = b->get_property("nom");
    }
  else
    {
      noms_a = a->get_property("nom_cible");
      noms_b = b->get_property("nom_cible");
    }
  const Nom nom_a = noms_a[0];
  const Nom nom_b = noms_b[0];
// Cas particulier si a et b sont des Champ_Generique_refChamp
// pour pouvoir reproduire le nom des variables dans le lml
  Noms compo_a, compo_b;
  if (!(sub_type(Champ_Generique_refChamp,a.valeur()) && (sub_type(Champ_Generique_refChamp,b.valeur()))))
    {
      compo_a = a->get_property("composantes");
      compo_b = b->get_property("composantes");
    }
  else
    {
      compo_a = source_a.noms_compo();
      compo_b = source_b.noms_compo();
    }
  const Noms unites_a = a->get_property("unites");
  const Noms unites_b = b->get_property("unites");
  int nb_valeurs_nodales = -1;
// Note B.M.: integrale_tps_ab_ est deja type dans Correlation::associer
// En revanche fixer_nb_valeurs_nodales n'est pas fait.
  if ( ( tab_a.get_md_vector() != tab_b.get_md_vector() ) ||
       ( tab_a.dimension_tot(0) != tab_b.dimension_tot(0) ) ||
       ( nb_compo_a > 1 && ( tab_a.nb_dim() == 1 || tab_a.dimension(1) != nb_compo_a ) ) ||
       ( nb_compo_b > 1 && ( tab_b.nb_dim() == 1 || tab_b.dimension(1) != nb_compo_b ) ) )
    {
// Support different pour les champs a et b ou pour leurs composantes
// Alors on ramene aux elements en creant un Champ_Fonc_PO_VDF ou VEF
      integrale_tps_ab_.support_different()=1;
      Nom Champ_Fonc_P0="Champ_Fonc_P0_";
      Champ_Fonc_P0+=Pb.discretisation().que_suis_je().substr_old(1,3);
      integrale_tps_ab_.typer(Champ_Fonc_P0);
      nb_valeurs_nodales = zone.nb_elem();
    }
  else
    {
// Meme support pour les champs a et b
      integrale_tps_ab_.support_different()=0;
      if (tab_a.size_reelle_ok())
        nb_valeurs_nodales = tab_a.dimension(0);
      else
        nb_valeurs_nodales = -1; //!< B.M.: quoi donner a fixer_nb_valeurs_nodales ???
    }
  int nb_comp= nb_compo_a * nb_compo_b;
  DoubleTab& val = valeurs_ab();
  Noms noms_composantes;
  if (nb_compo_a == 1)
    if (nb_compo_b == 1)
      {
// A et B champs scalaires
      }
    else
      {
// A champ scalaire, B champ vectoriel
        noms_composantes.dimensionner(nb_comp);
        Nom debut("Correlation_");
        debut += nom_a+"_";
        for (int i=0; i<nb_comp; i++)
          noms_composantes[i]=debut+compo_b[i];
      }
  else if (nb_compo_b == 1)
    {
// A champ vectoriel, B champ scalaire
      noms_composantes.dimensionner(nb_comp);
      Nom debut("Correlation_");
      debut+=nom_b+"_";
      for (int i=0; i<nb_comp; i++)
        noms_composantes[i]=debut+compo_a[i];
    }
  else
    {
// A et B champs vectoriels
      noms_composantes.dimensionner(nb_comp);
      Nom debut("Correlation_");
      for (int i=0; i<nb_compo_a; i++)
        for (int j=0; j<nb_compo_b; j++)
          noms_composantes[i*nb_compo_b+j]=debut+compo_a[i]+"_"+compo_b[j];
    }
  if (nb_comp > 1)
    val.resize(0, nb_comp);
  Nom nom_pour_post("Correlation_");
  nom_pour_post+=nom_a+"_"+nom_b;
  integrale_tps_ab_->nommer(nom_pour_post);
  integrale_tps_ab_.associer_zone_dis_base(zone);
  integrale_tps_ab_->fixer_nb_comp(nb_comp);
// BM: le parametre de fixer_nb_valeurs_nodales est inutile,
// le champ sait determiner tout seul combien de ddl il a, mais
// il y a un test sur le parametre: il faut que la valeur soit la bonne.
  integrale_tps_ab_.fixer_nb_valeurs_nodales(nb_valeurs_nodales);
// On fixe les unites
  Nom unite(unites_a[0]);
  unite+=".";
  unite+=unites_b[0];
  if (nb_comp == 1)
    integrale_tps_ab_->fixer_unite(unite);
  else
    {
      Noms unites(nb_comp);
      for (int i=0; i<unites.size(); i++)
        unites[i]=unite;
      integrale_tps_ab_->fixer_noms_compo(noms_composantes);
      integrale_tps_ab_->fixer_unites(unites);
    }
  integrale_tps_ab_.changer_temps(Pb.schema_temps().temps_courant());
}
References Champ_Fonc::associer_zone_dis_base(), Champ_Fonc::changer_temps(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), vect_impl::dimensionner(), Probleme_base::discretisation(), Champ_Fonc::fixer_nb_valeurs_nodales(), TRUSTVect< _TYPE_ >::get_md_vector(), Op_Moyenne::integrale(), integrale_tps_a_, integrale_tps_ab_, integrale_tps_b_, la_moyenne_a(), la_moyenne_b(), Integrale_tps_Champ::le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem(), Champ_Fonc::nommer(), Field_base::noms_compo(), Objet_U::que_suis_je(), REF, TRUSTTab< _TYPE_ >::resize(), Probleme_base::schema_temps(), vect_impl::size(), TRUSTVect< _TYPE_ >::size_reelle_ok(), sub_type, Nom::substr_old(), Integrale_tps_produit_champs::support_different(), Schema_Temps_base::temps_courant(), Deriv_::typer(), valeurs_a(), valeurs_ab(), and valeurs_b().
Referenced by Champ_Generique_Correlation::completer().
completer_post_statistiques()
int Op_Correlation::completer_post_statistiques (const Domaine & dom, const int is_axi, Format_Post_base & format) override virtual
Reimplemented from Operateur_Statistique_tps_base.
Definition at line 215 of file Op_Correlation.cpp.
{
  return 1;
}
cree_instance()
Objet_U * Op_Correlation::cree_instance () static
Definition at line 21 of file Op_Correlation.cpp.
dt_integration_a()
double Op_Correlation::dt_integration_a () const inline
Definition at line 62 of file Op_Correlation.h.
  {
    return integrale_tps_a_->dt_integration();
  };
References Integrale_tps_Champ::dt_integration(), and integrale_tps_a_.
Referenced by calculer_valeurs().
dt_integration_ab()
double Op_Correlation::dt_integration_ab () const inline
Definition at line 70 of file Op_Correlation.h.
  {
    return integrale_tps_ab_.dt_integration();
  };
References Integrale_tps_Champ::dt_integration(), and integrale_tps_ab_.
Referenced by calculer_valeurs().
dt_integration_b()
double Op_Correlation::dt_integration_b () const inline
Definition at line 66 of file Op_Correlation.h.
  {
    return integrale_tps_b_->dt_integration();
  };
References Integrale_tps_Champ::dt_integration(), and integrale_tps_b_.
Referenced by calculer_valeurs().
duplique()
int Op_Correlation::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Op_Correlation.cpp.
fixer_tstat_deb()
void Op_Correlation::fixer_tstat_deb (double tdeb, double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 166 of file Op_Correlation.h.
{
  integrale_tps_ab_.fixer_t_debut(tdeb);
  integrale_tps_ab_.fixer_tps_integrale(tps);
  integrale_tps_ab_.fixer_dt_integr(tps-tdeb);
}
References Integrale_tps_Champ::fixer_dt_integr(), Integrale_tps_Champ::fixer_t_debut(), Integrale_tps_Champ::fixer_tps_integrale(), and integrale_tps_ab_.
fixer_tstat_fin()
void Op_Correlation::fixer_tstat_fin (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 173 of file Op_Correlation.h.
{
  integrale_tps_ab_.fixer_t_fin(tps);
}
References Integrale_tps_Champ::fixer_t_fin(), and integrale_tps_ab_.
get_info()
const Type_info * Op_Correlation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Op_Correlation.cpp.
info()
const Type_info * Op_Correlation::info () static
Definition at line 21 of file Op_Correlation.cpp.
initialiser()
void Op_Correlation::initialiser (double val) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 114 of file Op_Correlation.h.
{
  integrale_tps_ab_.valeurs()= val_init;
}
References integrale_tps_ab_, and Champ_Fonc::valeurs().
integrale()
const Integrale_tps_produit_champs & Op_Correlation::integrale () const inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 38 of file Op_Correlation.h.
  {
    return integrale_tps_ab_;
  };
References integrale_tps_ab_.
Referenced by Champ_Generique_Correlation::integrale(), and Champ_Generique_Correlation::temps().
la_moyenne_a()
const Op_Moyenne & Op_Correlation::la_moyenne_a () const inline
Definition at line 42 of file Op_Correlation.h.
  {
    return la_moyenne_a_.valeur();
  };
References la_moyenne_a_, and Ref_Op_Moyenne::valeur().
Referenced by completer(), and Champ_Generique_Correlation::get_directive_pour_discr().
la_moyenne_b()
const Op_Moyenne & Op_Correlation::la_moyenne_b () const inline
Definition at line 46 of file Op_Correlation.h.
  {
    return la_moyenne_b_.valeur();
  };
References la_moyenne_b_, and Ref_Op_Moyenne::valeur().
Referenced by completer().
le_nom()
const Nom & Op_Correlation::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Implements Operateur_Statistique_tps_base.
Definition at line 30 of file Op_Correlation.h.
  {
    return integrale_tps_ab_.le_nom();
  };
References integrale_tps_ab_, and O_U_Ptr::le_nom().
Referenced by printOn().
mettre_a_jour()
void Op_Correlation::mettre_a_jour (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 109 of file Op_Correlation.h.
{
  integrale_tps_ab_.mettre_a_jour(tps);
}
References integrale_tps_ab_, and Integrale_tps_produit_champs::mettre_a_jour().
printOn()
Sortie & Op_Correlation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Op_Correlation.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Op_Correlation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 34 of file Op_Correlation.cpp.
{
  return s ;
}
reprendre()
int Op_Correlation::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 161 of file Op_Correlation.h.
{
  return integrale_tps_ab_.reprendre(is);
}
References integrale_tps_ab_, and Champ_Fonc::reprendre().
sauvegarder()
int Op_Correlation::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 156 of file Op_Correlation.h.
{
  return integrale_tps_ab_.sauvegarder(os);
}
References integrale_tps_ab_, and Champ_Fonc::sauvegarder().
self_cast() [1/2]
const Op_Correlation & Op_Correlation::self_cast (const Objet_U & r) static
Definition at line 21 of file Op_Correlation.cpp.
self_cast() [2/2]
Op_Correlation & Op_Correlation::self_cast (Objet_U & r) static
Definition at line 21 of file Op_Correlation.cpp.
taille_memoire()
unsigned Op_Correlation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Op_Correlation.cpp.
temps()
double Op_Correlation::temps () const inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 34 of file Op_Correlation.h.
  {
    return integrale_tps_ab_.temps();
  };
References integrale_tps_ab_, and Champ_Fonc::temps().
valeurs_a()
const DoubleTab & Op_Correlation::valeurs_a () const inline
Definition at line 50 of file Op_Correlation.h.
  {
    return integrale_tps_a_->valeurs();
  };
References integrale_tps_a_, and Champ_Fonc::valeurs().
Referenced by completer().
valeurs_ab()
DoubleTab & Op_Correlation::valeurs_ab () inline
Definition at line 58 of file Op_Correlation.h.
  {
    return integrale_tps_ab_.valeurs();
  };
References integrale_tps_ab_, and Champ_Fonc::valeurs().
Referenced by completer().
valeurs_b()
const DoubleTab & Op_Correlation::valeurs_b () const inline
Definition at line 54 of file Op_Correlation.h.
  {
    return integrale_tps_b_->valeurs();
  };
References integrale_tps_b_, and Champ_Fonc::valeurs().
Referenced by completer().
Member Data Documentation
info_obj
const Type_info Op_Correlation::info_obj static
Definition at line 28 of file Op_Correlation.h.
integrale_tps_a_
Ref_Integrale_tps_Champ Op_Correlation::integrale_tps_a_ protected
Definition at line 91 of file Op_Correlation.h.
Referenced by calculer_valeurs(), completer(), dt_integration_a(), and valeurs_a().
integrale_tps_ab_
Integrale_tps_produit_champs Op_Correlation::integrale_tps_ab_ protected
Definition at line 93 of file Op_Correlation.h.
Referenced by associer(), calculer_valeurs(), completer(), dt_integration_ab(), fixer_tstat_deb(), fixer_tstat_fin(), initialiser(), integrale(), le_nom(), mettre_a_jour(), reprendre(), sauvegarder(), temps(), and valeurs_ab().
integrale_tps_b_
Ref_Integrale_tps_Champ Op_Correlation::integrale_tps_b_ protected
Definition at line 92 of file Op_Correlation.h.
Referenced by calculer_valeurs(), completer(), dt_integration_b(), and valeurs_b().
la_moyenne_a_
Ref_Op_Moyenne Op_Correlation::la_moyenne_a_ protected
Definition at line 89 of file Op_Correlation.h.
Referenced by associer_op_stat(), and la_moyenne_a().
la_moyenne_b_
Ref_Op_Moyenne Op_Correlation::la_moyenne_b_ protected
Definition at line 90 of file Op_Correlation.h.
Referenced by associer_op_stat(), and la_moyenne_b().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Op_Correlation.h
src/Kernel/Statistiques_temps/Op_Correlation.cpp