TRUST: Discretisation_tools Class Reference
Discretisation_tools Class Reference
: class Discretisation_tools
<Description of class Discretisation_tools>
#include <Discretisation_tools.h>
Static Public Member Functions
static void nodes_to_cells (const Champ_base &Hn, Champ_base &He)
static void cells_to_nodes (const Champ_base &He, Champ_base &Hn)
static void faces_to_cells (const Champ_base &Hf, Champ_base &He)
static void cells_to_faces (const Champ_base &He, Champ_base &Hf)
Detailed Description
: class Discretisation_tools
<Description of class Discretisation_tools>
Definition at line 29 of file Discretisation_tools.h.
Member Function Documentation
cells_to_faces()
void Discretisation_tools::cells_to_faces (const Champ_base & He, Champ_base & Hf) static
Definition at line 112 of file Discretisation_tools.cpp.
{
  DoubleTab& tabHf=Hf.valeurs();
  const DoubleTab& tabHe=He.valeurs();
  Debog::verifier("element_face entreee",tabHe);
  assert_espace_virtuel_vect(tabHe);
  const Zone_dis_base& zone_dis_base=He.zone_dis_base();
  const Zone_VF& zone_vf= ref_cast(Zone_VF,zone_dis_base);
// en realite on fait P1B vers face
// assert(tabHe.dimension_tot(0)==zone_dis_base.nb_elem_tot());
  assert(tabHf.dimension_tot(0)==zone_vf.nb_faces_tot());
  const IntTab& elem_faces=zone_vf.elem_faces();
  const DoubleVect& volumes=zone_vf.volumes();
  const DoubleVect& volumes_entrelaces=zone_vf.volumes_entrelaces();
  tabHf=0;
  int nb_face_elem=elem_faces.dimension(1);
  int nb_elem_tot=zone_dis_base.nb_elem_tot();
  double coeffb=nb_face_elem;
  double coeffi=coeffb;
  if (zone_vf.que_suis_je()=="Zone_VDF")
    {
      coeffb=1;
      coeffi=2;
    }
// TODO : FIXME
// XXX : codage pas coherent... à voir : volumes ou volumes_entrelaces ???
  if (tabHe.line_size() == 1)
    {
      DoubleTab vol_tot(tabHf);
      for (int ele=0; ele<nb_elem_tot; ele++)
        for (int s=0; s<nb_face_elem; s++)
          {
            tabHf(elem_faces(ele,s))+=tabHe(ele,0)*volumes(ele);
            vol_tot(elem_faces(ele,s)) += volumes(ele);
          }
      for (int f = 0; f < zone_vf.nb_faces(); f++)
        tabHf(f) /= vol_tot(f);
    }
  else
    {
// TODO : factorize these cases ...
      if (tabHf.nb_dim()==1)
        {
          assert(coeffi==2);
          assert(coeffb==1);
// VDF
// abort();
          for (int ele=0; ele<nb_elem_tot; ele++)
            {
              for (int s=0; s<nb_face_elem; s++)
                {
                  int face=elem_faces(ele,s);
                  for (int r = 0; r < zone_vf.dimension; r++)
                    {
// Change of basis N.K.N, with N the normal of the face, and K the tensorial coefficient to get the value of the diffusivity
// on the direction of the surface normal.
                      double normOnSurf = zone_vf.face_normales(face, r) / zone_vf.face_surfaces(face);
                      tabHf(face) += tabHe(ele, r) * normOnSurf * normOnSurf * volumes(ele);
                    }
                }
            }
          for (int f=0; f<zone_vf.premiere_face_int(); f++)
            tabHf(f)/=volumes_entrelaces(f)*coeffb;
          for (int f=zone_vf.premiere_face_int(); f<zone_vf.nb_faces(); f++)
            tabHf(f)/=volumes_entrelaces(f)*coeffi;
        }
      else
        {
// abort();
          int nb_comp=tabHf.dimension(1);
          for (int ele=0; ele<nb_elem_tot; ele++)
            {
              for (int s=0; s<nb_face_elem; s++)
                {
                  int face=elem_faces(ele,s);
                  for (int comp=0; comp<nb_comp; comp++)
                    tabHf(face,comp)+=tabHe(ele,comp)*volumes(ele);
                }
            }
          for (int f=0; f<zone_vf.premiere_face_int(); f++)
            for (int comp=0; comp<nb_comp; comp++)
              tabHf(f,comp)/=volumes_entrelaces(f)*coeffb;
          for (int f=zone_vf.premiere_face_int(); f<zone_vf.nb_faces(); f++)
            for (int comp=0; comp<nb_comp; comp++)
              tabHf(f,comp)/=volumes_entrelaces(f)*coeffi;
        }
    }
  tabHf.echange_espace_virtuel();
// Cerr<<min_array(tabHe)<<" elem  "<<max_array(tabHe)<<finl;
// Cerr<<min_array(tabHf)<<" face  "<<max_array(tabHf)<<finl;
  Debog::verifier("element_face sortie",tabHf);
}
References assert_espace_virtuel_vect(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_VF::face_normales(), Zone_VF::face_surfaces(), TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_VF::premiere_face_int(), Objet_U::que_suis_je(), ref_cast, Champ_Proto::valeurs(), Debog::verifier(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Champ_base::zone_dis_base().
Referenced by Milieu_base::update_rho_cp().
cells_to_nodes()
void Discretisation_tools::cells_to_nodes (const Champ_base & He, Champ_base & Hn) static
Definition at line 49 of file Discretisation_tools.cpp.
{
  DoubleTab& tabHn=Hn.valeurs();
  const DoubleTab& tabHe=He.valeurs();
  Debog::verifier("elno entreee",tabHe);
  assert_espace_virtuel_vect(tabHe);
  const Zone_dis_base& zone_dis_base=He.zone_dis_base();
  assert(tabHe.dimension_tot(0)==zone_dis_base.nb_elem_tot());
  assert(tabHn.dimension_tot(0)==zone_dis_base.nb_som_tot());
  const IntTab& les_elems=zone_dis_base.zone().les_elems();
  const DoubleVect& volumes=ref_cast(Zone_VF,zone_dis_base).volumes();
  tabHn=0;
  DoubleTrav vsom(tabHn.dimension_tot(0));
  int nb_som_elem=les_elems.dimension(1);
  int nb_elem_tot=zone_dis_base.nb_elem_tot();
  int N = tabHn.line_size();
  for (int e = 0; e < nb_elem_tot; e++)
    for (int s = 0; s < nb_som_elem; s++)
      {
        int sglob = les_elems(e, s);
        for (int n = 0; n < N; n++)
          tabHn(sglob, n) += tabHe(e, n) * volumes(e);
        vsom(sglob) += volumes(e);
      }
  for (int s = 0; s < zone_dis_base.nb_som(); s++)
    for (int n = 0; n < N; n++)
      tabHn(s, n) /= vsom(s);
  tabHn.echange_espace_virtuel();
  Debog::verifier("elno sortie",tabHn);
}
References assert_espace_virtuel_vect(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_som(), Zone_dis_base::nb_som_tot(), ref_cast, Champ_Proto::valeurs(), Debog::verifier(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by Milieu_base::update_rho_cp().
faces_to_cells()
void Discretisation_tools::faces_to_cells (const Champ_base & Hf, Champ_base & He) static
Definition at line 86 of file Discretisation_tools.cpp.
{
  const DoubleTab& tabHf=Hf.valeurs();
  DoubleTab& tabHe=He.valeurs();
  const Zone_dis_base& zone_dis_base=He.zone_dis_base();
  const Zone_VF& zone_vf= ref_cast(Zone_VF,zone_dis_base);
  assert(tabHe.dimension_tot(0)==zone_dis_base.nb_elem_tot());
  assert(tabHf.dimension_tot(0)==zone_vf.nb_faces_tot());
  const IntTab& elem_faces=zone_vf.elem_faces();
  int nb_face_elem=elem_faces.dimension(1);
  int nb_elem=zone_dis_base.nb_elem();
  tabHe=0;
  for (int ele=0; ele<nb_elem; ele++)
    {
      for (int s=0; s<nb_face_elem; s++)
        {
          tabHe(ele)+=tabHf(elem_faces(ele,s));
        }
    }
  double inv_nb_face_elem=1./(nb_face_elem);
  tabHe*=inv_nb_face_elem;
  tabHe.echange_espace_virtuel();
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), ref_cast, Champ_Proto::valeurs(), and Champ_base::zone_dis_base().
nodes_to_cells()
void Discretisation_tools::nodes_to_cells (const Champ_base & Hn, Champ_base & He) static
Definition at line 23 of file Discretisation_tools.cpp.
{
  const DoubleTab& tabHn=Hn.valeurs();
  DoubleTab& tabHe=He.valeurs();
  const Zone_dis_base& zone_dis_base=He.zone_dis_base();
  assert(tabHe.dimension_tot(0)==zone_dis_base.nb_elem_tot());
  assert(tabHn.dimension_tot(0)==zone_dis_base.nb_som_tot());
  const IntTab& les_elems=zone_dis_base.zone().les_elems();
  int nb_som_elem=les_elems.dimension(1);
  int nb_elem=zone_dis_base.nb_elem();
  tabHe=0;
  for (int ele=0; ele<nb_elem; ele++)
    {
      for (int s=0; s<nb_som_elem; s++)
        {
          int sglob=les_elems(ele,s);
          tabHe(ele)+=tabHn(sglob);
        }
    }
  double inv_nb_som_elem=1./(nb_som_elem);
  tabHe*=inv_nb_som_elem;
  tabHe.echange_espace_virtuel();
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone::les_elems(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_som_tot(), Champ_Proto::valeurs(), Zone_dis_base::zone(), and Champ_base::zone_dis_base().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Discretisation_tools.h
src/Kernel/Geometrie/Discretisation_tools.cpp