TRUST: Echange_contact_CoviMAC Class Reference
Echange_contact_CoviMAC Class Reference
#include <Echange_contact_CoviMAC.h>
Public Member Functions
Echange_contact_CoviMAC ()
~Echange_contact_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
virtual void verifie_ch_init_nb_comp ()
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
const IntTab & fe_dist () const
void harmonic_points (DoubleTab &xh, DoubleTab &wh, DoubleTab &whm) const
void fgrad (int full_stencil, DoubleTab &phif_w, IntTab &phif_d, IntTab &phif_e, DoubleTab &phif_c, IntTab &phif_pe, DoubleTab &phif_pc) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Echange_contact_CoviMAC & self_cast (Objet_U &)
static const
Echange_contact_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
Ref_Front_VF fvf
Ref_Front_VF o_fvf
int i_fvf
int i_o_fvf
Ref_Op_Diff_CoviMAC_base diff
Ref_Op_Diff_CoviMAC_base o_diff
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
void init_fe_dist () const
Protected Attributes
Nom nom_autre_pb_
Nom nom_bord_
Nom nom_champ_
double invh_paroi_
double t_last_maj_
IntTab fe_dist_
int fe_init_
Detailed Description
Definition at line 49 of file Echange_contact_CoviMAC.h.
Constructor & Destructor Documentation
Echange_contact_CoviMAC::Echange_contact_CoviMAC ()
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
Echange_contact_CoviMAC::~Echange_contact_CoviMAC ()
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
Member Function Documentation
Objet_U * Echange_contact_CoviMAC::cree_instance () [static]
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
int Echange_contact_CoviMAC::duplique () const [virtual]
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
const IntTab& Echange_contact_CoviMAC::fe_dist () const [inline]
Definition at line 62 of file Echange_contact_CoviMAC.h.
References fe_dist_, and init_fe_dist().
Referenced by Op_Diff_CoviMAC_base::init_op_ext().
  {
    init_fe_dist();
    return fe_dist_;
  }
void Echange_contact_CoviMAC::fgrad (int full_stencil, DoubleTab & phif_w, IntTab & phif_d, IntTab & phif_e, DoubleTab & phif_c, IntTab & phif_pe, DoubleTab & phif_pc) const
Definition at line 174 of file Echange_contact_CoviMAC.cpp.
References IntTab::append_line(), dabs(), IntTab::dimension(), DoubleTab::dimension(), Objet_U::dimension, Zone_CoviMAC::dist_norm_bord(), Zone_CoviMAC::dot(), Process::exit(), F77NAME, Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::fbord(), Zone_CoviMAC::fsten_d, Zone_CoviMAC::fsten_f, Nom::le_nom(), local_max_abs_vect(), max(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_CoviMAC::nu_dot(), ref_cast, DoubleTab::resize(), ArrOfDouble::set_smart_resize(), Zone_VF::xp(), and Zone_VF::xv().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC, fvf->zone_dis()), &o_zone = ref_cast(Zone_CoviMAC, o_fvf->zone_dis());
  o_zone.init_stencils();
  int i_f, i, il, ic, j, k, l, f, o_f, fb, o_fb, e, o_e, e_s, f_s, f_sb, m, m_s, n, n_max, on_max, nw, infoo = 0;
  int d, D = dimension, ne_tot = zone.nb_elem_tot(), o_ne_tot = o_zone.nb_elem_tot();
  int N = phif_w.dimension(1), oN = o_diff->equation().inconnue().valeurs().line_size(), M = max(N, oN);
  const IntTab& f_e = zone.face_voisins(), &o_f_e = o_zone.face_voisins(), &fe_d = fe_dist(), &pe_ext = diff->pe_ext, &o_pe_ext = o_diff->pe_ext;
  const DoubleTab& xv = zone.xv(), &xp = zone.xp(), &o_xp = o_zone.xp(), &nf = zone.face_normales(), &o_nf = o_zone.face_normales(),
                   &nu = diff->nu(), &invh = diff->invh(), &o_nu = o_diff->nu(), &o_invh = o_diff->invh(), &xh = diff->xh(), &o_xh = o_diff->xh(),
                    &wh = diff->wh(), &o_wh = o_diff->wh(), &whm = diff->whm(), &o_whm = o_diff->whm();
  const DoubleVect& fs = zone.face_surfaces(), &o_fs = o_zone.face_surfaces();
  double i3[3][3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 }}, tphi;
  char trans = 'N';
// traduction des indices de probleme dans o_diff en indices de problemes dans diff (avec extension de op_ext si necessaire)
  std::vector<int> trad;
  for (auto op : o_diff->op_ext)
    {
      trad.push_back(std::find(diff->op_ext.begin(), diff->op_ext.end(), op) - diff->op_ext.begin());
      if (trad.back() == (int) diff->op_ext.size()) diff->op_ext.push_back(op);
    }
// verification : phif_d doit etre rempli jusqu'a la premiere face de la CL, on ne doit pas demander les faces virtuelles
  assert(phif_d.dimension(0) == fvf->num_face(0) + 1 && phif_w.dimension(0) == zone.nb_faces());
  std::vector<std::pair<int, int>> p_e; //stencil aux elemens : { { pb, elem/bord }, ... }
  DoubleTrav base, A , B, lambda(2, M), r_int(2, M), h(2, M), xef(2, M, D), interp,  phi, W(1); //base de champs possibles, systeme A.x = B,
  base.set_smart_resize(1), A.set_smart_resize(1), B.set_smart_resize(1), interp.set_smart_resize(1), phi.set_smart_resize(1), W.set_smart_resize(1);
  for (i_f = 0; i_f < fvf->nb_faces(); i_f++, phif_d.append_line(phif_e.dimension(0), phif_pe.dimension(0)))
    {
      f = fvf->num_face(i_f), e = f_e(f, 0), o_f = fe_d(i_f, 0), o_e = fe_d(i_f, 1), fb = zone.fbord(f), o_fb = o_zone.fbord(o_f);
      const int *fa = &zone.fsten_f(zone.fsten_d(f)), *o_fa = &o_zone.fsten_f(o_zone.fsten_d(o_f)); //debuts des stencils de chaque cote
      int n_f = zone.fsten_d(f + 1) - zone.fsten_d(f), o_n_f = o_zone.fsten_d(o_f + 1) - o_zone.fsten_d(o_f), n_tf = n_f + o_n_f + 2, nnz, hdiag, ok = 1;
      /* verification qu'on dispose de tous les points harmoniques dont on a besoin */
      for (i = 0; i <   n_f; i++) ok &= (  wh(  fa[i], 0) >= 0);
      for (i = 0; i < o_n_f; i++) ok &= (o_wh(o_fa[i], 0) >= 0);
      if (!ok) Process::exit(Nom("Echange_contact_CoviMAC: missing face neighborhood detected between ") + fvf->le_nom() + " and " + o_fvf->le_nom()
                               + " ! Have you used Decouper_multi?");
      double h_max[2] = { 0, }, h_tot[2] = { 0, }, dist[2] = { zone.dist_norm_bord(f), o_zone.dist_norm_bord(o_f) }; //coeff d'echange max de chaque cote, distances
      /* nf.lambda.nf de chaque cote + identification des phases dominantes (-> diffusant le plus) */
      const double *xe; //coordonnees de l'amont/aval
      for (i = 0; i < 2; i++) for (xe = i ? &o_xp(o_e, 0) : &xp(e, 0), n = 0; n < (i ? oN : N); n++)
          {
            lambda(i, n) = zone.nu_dot(i ? &o_nu : &nu, i ? o_e : e, n, &nf(f, 0), &nf(f, 0)) / (fs(f) * fs(f));
            r_int(i, n) = dist[i] / lambda(i, n);
            for (d = 0; d < D; d++) xef(i, n, d) = xe[d] + (i ? -1 : 1) * r_int(i, n) * zone.nu_dot(i ? &o_nu : &nu, i ? o_e : e, n, &nf(f, 0), i3[d]) / fs(f);
            h(i, n) = 1. / (r_int(i, n) + (i ? o_invh(o_fb, n): invh(fb, n)) + invh_paroi_ / 2), h_tot[i] += h(i, n);
            if (h(i, n) > h_max[i]) h_max[i] = h(i, n), *(i ? &on_max : &n_max) = n;
          }
      /* interpolation des points projetes de chaque cote */
      interp.resize(2, M, n_tf, M); //ordre des colonnes : faces de zone.fsten_f -> xh local -> faces de o_zone.fsten_f -> xh distant
      for (interp = 0, i = 0; i < 2; i++) for (n = 0; n < (i ? oN : N); n++) interp(i, n, i ? n_tf - 1 : n_f, n) = 1;
      if (invh_paroi_ > 0 || oN != N) /* paroi fine ou nombre de composantes differents -> partition du flux total */
        {
          int nrhs = N + oN, ng = D + N + oN - 2, nl = ng + 1, nc = N * (n_f + 1) + oN * (o_n_f + 1);
          B.resize(nrhs, nc), A.resize(nc, nl), base.resize(ng, 2, M, D), base = 0;
          /* base de gradients amont/aval */
// D premiers : diffusion dans les phases dominantes
          for (i = 0; i < D; i++) for (j = 0; j < 2; j++) for (d = 0; d < D; d++)
                base(i, j, j ? on_max : n_max, d) = i3[i][d] + (j ? -1 : 1) * (zone.nu_dot(&o_nu, o_e, on_max, &nf(f, 0), i3[i]) - zone.nu_dot(&nu, e, n_max, &nf(f, 0), i3[i]))
                                                    * nf(f, d) / (2 * fs(f) * fs(f) * lambda(j, j ? on_max : n_max));
// N + oN - 2 suivants : gradient normal dans la phase n (non dominante) d'un cote, compense par la phase dominante de l'autre
          for (i--, n = 0; n <  N; n++) if (n != n_max) for (i++, j = 0; j < 2; j++) for (d = 0; d < D; d++)
                  base(i, j, j ? on_max : n, d) = nf(f, d) / fs(f) * (j ? lambda(0, n) / lambda(1, on_max) : 1);
          for (n = 0; n < oN; n++) if (n != on_max) for (i++, j = 0; j < 2; j++) for (d = 0; d < D; d++)
                  base(i, j, j ? n : n_max, d)  = nf(f, d) / fs(f) * (j ? 1 : lambda(1, n) / lambda(0, n_max));
          /* seconds membres : pour les N + oN interpolations a calculer, une equation par gradient possible + une pour la constante */
          for (B = 0, i = 0, j = 0; i < 2; i++) for (n = 0; n < (i ? oN : N); n++, j++) for (k = 0; k < nl; k++)
                B(j, k) = k < ng ? zone.dot(&xef(i, n, 0), &base(k, i, n, 0), i ? &o_xh(o_f, n, 0) : &xh(f, n, 0)) : 0;
          /* poids par defaut : pt harmonique du bon cote */
          if (std::pow(1e6 * local_max_abs_vect(B), D - 1) > fs(f)) //pts projetes distants des pts harmoniques -> recherche d'interpolation
            {
              /* matrice */
              for (i = 0, ic = 0; i <= n_f; i++) for (n = 0; n < N; n++, ic++) for (il = 0; il <= ng; il++) //cote interne
                    A(ic, il) = il < ng ? zone.dot(&xh(i < n_f ? fa[i] : f, n, 0), &base(il, 0, n, 0), &xv(f, 0))
                                + (invh(fb, n) + invh_paroi_ / 2) * zone.nu_dot(&nu, e, n, &nf(f, 0), &base(il, 0, n, 0)) / fs(f) : 1;
              for (i = 0; i <= o_n_f; i++) for (n = 0; n < oN; n++, ic++) for (il = 0; il <= ng; il++) //cote externe
                    A(ic, il) = il < ng ? zone.dot(&o_xh(i < o_n_f ? o_fa[i] : o_f, n, 0), &base(il, 1, n, 0), &xv(f, 0))
                                - (o_invh(o_fb, n) + invh_paroi_ / 2) * zone.nu_dot(&o_nu, o_e, n, &nf(f, 0), &base(il, 1, n, 0)) / fs(f) : 1;
              /* resolution */
              nw = -1, F77NAME(dgels)(&trans, &nl, &nc, &nrhs, &A(0, 0), &nl, &B(0, 0), &nc, &W(0), &nw, &infoo);
              W.resize(nw = W(0)), F77NAME(dgels)(&trans, &nl, &nc, &nrhs, &A(0, 0), &nl, &B(0, 0), &nc, &W(0), &nw, &infoo);
              /* correction de interp (avec ecretage) */
              for (i = 0, j = 0; i < 2; i++) for (n = 0; n < (i ? oN : N); n++, j++) for (k = 0, il = 0; k < n_tf; k++)
                    for (m = 0; m < (k > n_f ? oN : N); m++, il++) interp(i, n, k, m) += dabs(B(j, il)) > 1e-8 ? B(j, il) : 0;
            }
        }
      else for (n = 0; n < N; n++) /* sinon -> composante par composante */
          {
            int nrhs = 2, nl = D + 1, nc = n_tf;
            B.resize(nrhs, nc), A.resize(nc, nl), base.resize(2, D, D);
            /* base : base de "vecteurs tests" amont/aval d'un gradient verifiant nf.nu_am.vec_am = nf.nu_av.vec_av */
            for (i = 0; i < 2; i++) for (j = 0; j < D; j++) for (d = 0; d < D; d++)
                  base(i, j, d) = i3[j][d] + (i ? -1 : 1) * (zone.nu_dot(&o_nu, o_e, n, &nf(f, 0), i3[j]) - zone.nu_dot(&nu, e, n, &nf(f, 0), i3[j])) * nf(f, d) / (2 * lambda(i, n) * fs(f) * fs(f));
            /* seconds membres : au passage, on calcule la resistance interne r = d / lambda */
            for (B = 0, i = 0; i < 2; i++) for (d = 0; d < D; d++)
                B(i, d) = (i ? o_xp(o_e, d) : xp(e, d)) + (i ? -1 : 1) * r_int(i, n) * zone.nu_dot(i ? &o_nu : &nu, i ? o_e : e, n, &nf(f, 0), i3[d]) / fs(f) - xh(f, n, d);
            /* interpolation des points projetes amont / aval */
            if (std::pow(1e6 * local_max_abs_vect(B), D - 1) > fs(f)) //si les pts projetes ne sont pas dessus -> corrections
              {
                /* matrice */
                for (i = 0, ic = 0; i <= n_f; i++, ic++) for (il = 0; il <= D; il++) //cote interne
                    A(ic, il) = il < D ? zone.dot(&xh(i < n_f ? fa[i] : f, n, 0), &base(0, il, 0), &xv(f, 0))
                                + (invh(fb, n) + invh_paroi_ / 2) * zone.nu_dot(&nu, e, n, &nf(f, 0), &base(0, il, 0)) / fs(f) : 1;
                for (i = 0; i <= o_n_f; i++, ic++) for (il = 0; il <= D; il++) //cote externe
                    A(ic, il) = il < D ? zone.dot(&o_xh(i < o_n_f ? o_fa[i] : o_f, n, 0), &base(1, il, 0), &xv(f, 0))
                                - (o_invh(o_fb, n) + invh_paroi_ / 2) * zone.nu_dot(&o_nu, o_e, n, &nf(f, 0), &base(1, il, 0)) / fs(f) : 1;
                /* resolution */
                nw = -1, F77NAME(dgels)(&trans, &nl, &nc, &nrhs, &A(0, 0), &nl, &B(0, 0), &nc, &W(0), &nw, &infoo);
                W.resize(nw = W(0)), F77NAME(dgels)(&trans, &nl, &nc, &nrhs, &A(0, 0), &nl, &B(0, 0), &nc, &W(0), &nw, &infoo);
                /* correction de interp (avec ecretage) */
                for (i = 0; i < 2; i++) for (j = 0; j < nc; j++) interp(i, n, j, n) += dabs(B(i, j)) > 1e-8 ? B(i, j) : 0;
              }
          }
      /* stencil aux elements */
      for (p_e.clear(), i = 0; i < n_f; i++) for (f_s = fa[i], f_sb = zone.fbord(f_s), j = 0; j < 2; j++) //cote interne
          if ((e_s = f_e(f_s, j)) >= 0) p_e.push_back({ 0, e_s }); //element normal
          else if (f_sb >= 0 && (e_s = pe_ext(f_sb, 1)) >= 0) p_e.push_back({ pe_ext(f_sb, 0), e_s }); //de l'autre cote d'un Echange_contact
          else if (f_sb >= 0) p_e.push_back({ 0, ne_tot + f_s }); //CL non Echange_contact -> dependance en les valeurs aux bords
      for (i = 0; i < o_n_f; i++) for (f_s = o_fa[i], f_sb = o_zone.fbord(f_s), j = 0; j < 2; j++) //cote externe
          if ((e_s = o_f_e(f_s, j)) >= 0) p_e.push_back({ trad[0], e_s }); //element normal
          else if (f_sb >= 0 && (e_s = o_pe_ext(f_sb, 1)) >= 0) p_e.push_back({ trad[o_pe_ext(f_sb, 0)], e_s }); //de l'autre cote d'un Echange_contact
          else if (f_sb >= 0) p_e.push_back({ trad[0], o_ne_tot + f_s }); //CL non Echange_contact -> dependance en les valeurs aux bords
      std::sort(p_e.begin(), p_e.end()), p_e.erase(std::unique(p_e.begin(), p_e.end()), p_e.end()); //classement + deduplication
      /* flux par composante */
      phi.resize(p_e.size(), M, M, 2), phi = 0;
// dependances points amont/aval
      for (i = 0; i < 2; i++) for (k = std::lower_bound(p_e.begin(), p_e.end(), std::make_pair(i ? trad[0] : 0, i ? o_e : e)) - p_e.begin(), n = 0; n < (i ? oN : N); n++)
          phi(k, n, n, i) += (i ? 1 : -1) / r_int(i, n);
// dependances cote local
      for (i = 0; i <= n_f; i++) for (f_s = i < n_f ? fa[i] : f, f_sb = zone.fbord(f_s), j = 0; j < 2; j++)
          if ((e_s = f_e(f_s, j) >= 0 ? f_e(f_s, j) : f_sb >= 0 && pe_ext(f_sb, 0) >= 0 ? pe_ext(f_sb, 1) : -1) >= 0) //il existe un element source
            {
              k = std::lower_bound(p_e.begin(), p_e.end(), std::make_pair(f_e(f_s, j) >= 0 ? 0 : pe_ext(f_sb, 0), e_s)) - p_e.begin();
              if (f_sb < 0 || pe_ext(f_sb, 0) < 0) for (l = 0; l < 2; l++) for (n = 0; n < (l ? oN : N); n++) for (m = 0; m < wh.dimension(1); m++) //pt harmonique normal : dependance diagonale
                      phi(k, n, m, l) += (l ? -1 : 1) / r_int(l, n) * interp(l, n, i, m) * (j ? 1 - wh(f_s, m) : wh(f_s, m));
              else for (l = 0; l < 2; l++) for (n = 0; n < (l ? oN : N); n++) for (m = 0; m < whm.dimension(1); m++) for (m_s = 0; m_s < whm.dimension(2); m_s++) //pt harmonique d'Echange_contact : melange...
                        phi(k, n, m_s, l) += (l ? -1 : 1) / r_int(l, n) * interp(l, n, i, m) * whm(pe_ext(f_sb, 2), m, m_s, j);
            }
          else for (k = std::find(p_e.begin(), p_e.end(), std::make_pair((int)0, ne_tot + f_s)) - p_e.begin(), l = 0; l < 2; l++) //pas d'elem source -> dependance en la CL
              for (n = 0; n < (l ? oN : N); n++) for (m = 0; m < wh.dimension(1); m++)
                  phi(k, n, m, l) += (l ? -1 : 1) / r_int(l, n) * interp(l, n, i, m)
                                     * (wh(f_s, m) < 1 ? 1 - wh(f_s, m) : - zone.dist_norm_bord(f_s) * fs(f_s) * fs(f_s) / zone.nu_dot(&nu, f_e(f_s, 0), m, &nf(f_s, 0), &nf(f_s, 0)));
// dependances cote distant
      for (i = n_f + 1; i < n_tf; i++) for (f_s = i < n_tf - 1 ? o_fa[i - (n_f + 1)] : o_f, f_sb = o_zone.fbord(f_s), j = 0; j < 2; j++)
          if ((e_s = o_f_e(f_s, j) >= 0 ? o_f_e(f_s, j) : f_sb >= 0 && o_pe_ext(f_sb, 0) >= 0 ? o_pe_ext(f_sb, 1) : -1) >= 0) //il existe un element source
            {
              k = std::lower_bound(p_e.begin(), p_e.end(), std::make_pair(trad[o_f_e(f_s, j) >= 0 ? 0 : o_pe_ext(f_sb, 0)], e_s)) - p_e.begin();
              if (f_sb < 0 || o_pe_ext(f_sb, 0) < 0) for (l = 0; l < 2; l++) for (n = 0; n < (l ? oN : N); n++) for (m = 0; m < o_wh.dimension(1); m++) //pt harmonique normal : dependance diagonale
                      phi(k, n, m, l) += (l ? -1 : 1) / r_int(l, n) * interp(l, n, i, m) * (j ? 1 - o_wh(f_s, m) : o_wh(f_s, m));
              else for (l = 0; l < 2; l++) for (n = 0; n < (l ? oN : N); n++) for (m = 0; m < o_whm.dimension(1); m++) for (m_s = 0; m_s < o_whm.dimension(2); m_s++) //pt harmonique d'Echange_contact : melange...
                        phi(k, n, m_s, l) += (l ? -1 : 1) / r_int(l, n) * interp(l, n, i, m) * o_whm(o_pe_ext(f_sb, 2), m, m_s, j);
            }
          else for (k = std::find(p_e.begin(), p_e.end(), std::make_pair(trad[0], o_ne_tot + f_s)) - p_e.begin(), l = 0; l < 2; l++) //pas d'elem source -> dependance en la CL
              for (n = 0; n < (l ? oN : N); n++) for (m = 0; m < o_wh.dimension(1); m++)
                  phi(k, n, m, l) += (l ? -1 : 1) / r_int(l, n) * interp(l, n, i, m)
                                     * (o_wh(f_s, m) < 1 ? 1 - o_wh(f_s, m) : - o_zone.dist_norm_bord(f_s) * o_fs(f_s) * o_fs(f_s) / o_zone.nu_dot(&o_nu, o_f_e(f_s, 0), m, &o_nf(f_s, 0), &o_nf(f_s, 0)));
      if (invh_paroi_ > 0 || oN != N) /* paroi fine ou nombre de composantes differents -> calcul du flux total, puis partition entre composantes */
        {
          for (n = 0; n < N; n++) phif_w(f, n) = h_tot[1] / (h_tot[0] + h_tot[1]); //poids amont/aval : par le flux total
          for (i = 0; i < (int) p_e.size(); i++) for (m = 0; m < M; m++) for (j = 0; j < 2; j++)
                {
                  for (tphi = 0, n = 0; n < (j ? oN : N); n++) tphi += phi(i, n, m, j); //contrib de l'item i au flux total
                  for (n = 0; n < (j ? oN : N); n++) phi(i, n, m, j) = h(0, n) / h_tot[0] * tphi; //re-repartition
                }
        }
      else for (n = 0; n < N; n++) phif_w(f, n) = h(1, n) / (h(0, n) + h(1, n)); //poids amont/aval : par composante
      /* remplissage */
      for (i = 0; i < (int) p_e.size(); i++)
        {
          for (nnz = 0, hdiag = 0, n = 0; n < N; n++) for (m = 0; m < M; m++) for (j = 0; j < 2; j++) if (phi(i, n, m, j) != 0) nnz++, hdiag += (n != m);
          if (!nnz && !full_stencil) continue; //on peut sauter cette dependance
          if (p_e[i].first == 0 && hdiag == 0) //coeffs diagonaux et probleme local -> phif_e / phif_c
            for (phif_e.append_line(p_e[i].second), phif_c.resize((k = phif_c.dimension(0)) + 1, N, 2), n = 0; n < N; n++) for (j = 0; j < 2; j++)
                phif_c(k, n, j) = phi(i, n, n, j);
          else for (phif_pe.append_line(p_e[i].first, p_e[i].second), phif_pc.resize((k = phif_pc.dimension(0)) + 1, N, M, 2), n = 0; n < N; n++) for (m = 0; m < M; m++) for (j = 0; j < 2; j++)
                  phif_pc(k, n, m, j) = phi(i, n, m, j); //sinon -> phif_pe / phif_pc
        }
    }
}
const Type_info * Echange_contact_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
void Echange_contact_CoviMAC::harmonic_points (DoubleTab & xh, DoubleTab & wh, DoubleTab & whm) const
Definition at line 117 of file Echange_contact_CoviMAC.cpp.
References Objet_U::dimension, Zone_CoviMAC::dot(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::fbord(), max(), Zone_CoviMAC::nu_dot(), ref_cast, Zone_VF::xp(), and Zone_VF::xv().
{
  int i, f, o_f, fb, o_fb, e, o_e, nf_tot = fvf->nb_faces_tot(), d, D = dimension, i_mono, n, m,
                                   N = diff->equation().inconnue().valeurs().line_size(),
                                   oN = o_diff->equation().inconnue().valeurs().line_size(), M = max(N, oN);
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC, fvf->zone_dis()), &o_zone = ref_cast(Zone_CoviMAC, o_fvf->zone_dis());
  const IntTab& f_e = zone.face_voisins(), &pe_ext = diff->pe_ext, &fe_d = fe_dist();
  const DoubleTab& xv = zone.xv(), &o_xv = o_zone.xv(), &xp = zone.xp(), &o_xp = o_zone.xp(), &nf = zone.face_normales(),
                   &nu = diff->nu(), &invh =  diff->invh(), &o_nu = o_diff->nu(), &o_invh = o_diff->invh();
  const DoubleVect& fs = zone.face_surfaces();
  DoubleTrav def(2), xef(2, D), lambda(2, M), lambda_t(2, M, D), xh_c(D), wh_c(2, M);
  double i3[3][3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 }}, den;
  for (i = 0; i < nf_tot; i++) if ((o_f = fe_d(i, 0)) >= 0) /* il faut que la face / element de l'autre cote soient presents */
      {
        f = fvf->num_face(i), e = f_e(f, 0), o_e = fe_d(i, 1), fb = zone.fbord(f), o_fb = o_zone.fbord(o_f), i_mono = pe_ext(fb, 2);
// distances / projections
        for (def(0) = zone.dot(&xv(f, 0), &nf(f, 0), &xp(e, 0)) / fs(f), d = 0; d < D; d++)
          xef(0, d) = xp(e, d) + def(0) * nf(f, d) / fs(f);
        for (def(1) = - zone.dot(&o_xv(o_f, 0), &nf(f, 0), &o_xp(o_e, 0)) / fs(f), d = 0; d < D; d++)
          xef(1, d) = o_xp(o_e, d) - def(1) * nf(f, d) / fs(f);
// diffusivites de chaque cote : partie normale, partie transverse
        for (n = 0; n <  N; n++) for (lambda(0, n) = zone.nu_dot(&nu, e, n, &nf(f, 0), &nf(f, 0)) / (fs(f) * fs(f)), d = 0; d < D; d++)
            lambda_t(0, n, d) = (zone.nu_dot(&nu, e, n, i3[d], &nf(f, 0)) - lambda(0, n) * nf(f, d)) / fs(f);
        for (n = 0; n < oN; n++) for (lambda(1, n) = zone.nu_dot(&o_nu, o_e, n, &nf(f, 0), &nf(f, 0)) / (fs(f) * fs(f)), d = 0; d < D; d++)
            lambda_t(1, n, d) = (zone.nu_dot(&o_nu, o_e, n, i3[d], &nf(f, 0)) - lambda(1, n) * nf(f, d)) / fs(f);
        if (invh_paroi_ || oN != N) /* paroi fine ou nb de composantes differents -> couplage par le flux total */
          {
// xh_c / wh_c : point harmonique commun, correspondant a la temperature de paroi du cote du pb courant
            den = 0, xh_c = 0, wh_c = 0; //denominateur des expressions, position, poids des temperatures amont/aval
            for (n = 0; n <  N; n++) for (den += (wh_c(0, n) = lambda(0, n) / (def(0) + invh(fb, n) * lambda(0, n))), d = 0; d < D; d++)
                xh_c(d) += (lambda(0, n) * xef(0, d) + def(0) * lambda_t(0, n, d)) / (def(0) + invh(fb, n) * lambda(0, n));
            for (n = 0; n < oN; n++) for (den += (wh_c(1, n) = lambda(1, n) / (def(1) + (o_invh(o_fb, n) + invh_paroi_) * lambda(1, n))), d = 0; d < D; d++)
                xh_c(d) += (lambda(1, n) * xef(1, d) - def(1) * lambda_t(1, n, d)) / (def(1) + (o_invh(o_fb, n) + invh_paroi_) * lambda(1, n));
            xh_c /= den, wh_c /= den; //normalisation
            for (n = 0; n < N; n++) for (d = 0; d < D; d++) //position du point pour chaque composante -> dans xh (tableau sur toutes les faces)
                xh(f, n, d) = (def(0) * xh_c(d) + invh(fb, n) * (lambda(0, n) * xef(0, d) + def(0) * lambda_t(0, n, d))) / (def(0) + invh(fb, n) * lambda(0, n));
            for (n = 0; n < N; n++) //poids de chaque cote -> dans whm
              {
                for (m = 0; m <  N; m++) whm(i_mono, n, m, 0) = (def(0) * wh_c(0, m) + (m == n) * invh(fb, n) * lambda(0, n)) / (def(0) + invh(fb, n) * lambda(0, n));
                for (m = 0; m < oN; m++) whm(i_mono, n, m, 1) = def(0) * wh_c(1, m) / (def(0) + invh(fb, n) * lambda(0, n));
              }
          }
        else for (n = 0; n < N; n++) /* sinon -> couplage composante par composante */
            {
              for (d = 0; d < D; d++) /* position du "harmonic average point "*/
                xh(f, n, d) = (lambda(1, n) * def(0) * xef(1, d) + lambda(0, n) * def(1) * xef(0, d) + def(0) * def(1) * (lambda_t(1, n, d) - lambda_t(0, n, d)))
                              / (lambda(1, n) * def(0) + lambda(0, n) * def(1));
              for (n = 0; n < N; n++) for (m = 0; m < M; m++) /* poids de l'amont dans la valeur a ce point */
                  whm(i_mono, n, m, 0) = (m == n) * lambda(0, n) * def(1) / (lambda(1, n) * def(0) + lambda(0, n) * def(1)), whm(i_mono, n, m, 1) = (m == n) - whm(i_mono, m, n, 0);
            }
        for (n = 0; n < N; n++) wh(f, n) = 0; //pour indiquer que la face a ete traitee
      }
}
const Type_info * Echange_contact_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
void Echange_contact_CoviMAC::init_fe_dist () const [protected]
Definition at line 82 of file Echange_contact_CoviMAC.cpp.
References ArrOfDouble::addr(), Objet_U::dimension, Zone_CoviMAC::dot(), Process::exit(), Nom::le_nom(), ref_cast, and Zone_VF::xv().
Referenced by fe_dist().
{
  if (fe_init_) return; //deja fait
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC, fvf->zone_dis()), &o_zone = ref_cast(Zone_CoviMAC, o_fvf->zone_dis());
  const IntTab& o_f_e = o_zone.face_voisins();
  const DoubleTab& xv = zone.xv(), &o_xv = o_zone.xv();
  int i, f, o_f, nf_tot = fvf->nb_faces_tot(), o_nf_tot = o_fvf->nb_faces_tot(), d, D = dimension;
  fe_dist_.resize(nf_tot, 2);
  DoubleTrav xyz(nf_tot, D), o_xyz(o_nf_tot, D); //positions locales/distantes -> pour calcul de correspondance
  for (i = 0; i <   nf_tot; i++) for (d = 0; d < D; d++)   xyz(i, d) =   xv(  fvf->num_face(i), d);
  for (i = 0; i < o_nf_tot; i++) for (d = 0; d < D; d++) o_xyz(i, d) = o_xv(o_fvf->num_face(i), d);
#ifdef MEDCOUPLING_
  MCAuto<DataArrayDouble> dad(DataArrayDouble::New()), o_dad(DataArrayDouble::New());
  dad->useExternalArrayWithRWAccess(xyz.addr(), nf_tot, D), o_dad->useExternalArrayWithRWAccess(o_xyz.addr(), o_nf_tot, D);
// point de o_xyz le plus proche de chaque point de xyz
  MCAuto<DataArrayInt> idx(o_dad->findClosestTupleId(dad));
  for (i = 0; i < nf_tot; i++) //remplissage : (face distante, elem distant) si coincidence, -1 sinon
    {
      f = fvf->num_face(i), o_f = o_fvf->num_face(idx->getIJ(i, 0));
      double d2 = zone.dot(&xv(f, 0), &xv(f, 0), &o_xv(o_f, 0), &o_xv(o_f, 0));
      if (d2 < 1e-12) fe_dist_(i, 0) = o_f, fe_dist_(i, 1) = o_f_e(o_f, 0);
      else fe_dist_(i, 0) = fe_dist_(i, 1) = -1;
      if (i < fvf->nb_faces() && d2 >= 1e-12)
        Process::exit(Nom("Echange_contact_CoviMAC: missing opposite faces detected between ") + fvf->le_nom() + " and " + o_fvf->le_nom()
                      + " ! Have you used Decouper_multi?");
    }
#else
  Process::exit("Echange_contact_CoviMAC : MEDCoupling is required!");
#endif
  fe_init_ = 1;
}
int Echange_contact_CoviMAC::initialiser (double temps) [virtual]
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 58 of file Echange_contact_CoviMAC.cpp.
References Champ_front_calc::creer(), Champ_front_calc::equation(), Process::exit(), Champ_front_calc::front_dis(), Echange_impose_base::initialiser(), Nom::le_nom(), Field_base::le_nom(), ref_cast, sub_type, Champ_Inc_base::zone_Cl_dis(), and Equation_base::zone_dis().
{
  Echange_externe_impose::initialiser(temps);
  Champ_front_calc ch;
  ch.creer(nom_autre_pb_, nom_bord_, nom_champ_);
  fvf = ref_cast(Front_VF, frontiere_dis()), o_fvf = ref_cast(Front_VF, ch.front_dis()); //frontieres
  const Equation_base& eqn = zone_Cl_dis().equation(), &o_eqn = ch.equation(); //equations
  i_fvf = eqn.zone_dis()->rang_frontiere(fvf.le_nom()), i_o_fvf = o_eqn.zone_dis()->rang_frontiere(nom_bord_);
  int i_op = -1, o_i_op = -1, i; //indice de l'operateur de diffusion dans l'autre equation
  for (i = 0; i < eqn.nombre_d_operateurs(); i++)
    if (sub_type(Op_Diff_CoviMAC_base, eqn.operateur(i).l_op_base())) i_op = i;
  if (i_op < 0) Process::exit(le_nom() + " : no diffusion operator found in " + eqn.probleme().le_nom() + " !");
  for (i = 0; i < o_eqn.nombre_d_operateurs(); i++)
    if (sub_type(Op_Diff_CoviMAC_base, o_eqn.operateur(i).l_op_base())) o_i_op = i;
  if (o_i_op < 0) Process::exit(le_nom() + " : no diffusion operator found in " + o_eqn.probleme().le_nom() + " !");
  diff = ref_cast(Op_Diff_CoviMAC_base, eqn.operateur(i_op).l_op_base());
  o_diff = ref_cast(Op_Diff_CoviMAC_base, o_eqn.operateur(o_i_op).l_op_base());
  fe_init_ = 0;
  return 1;
}
virtual void Echange_contact_CoviMAC::mettre_a_jour (double temps) [inline, virtual]
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
Reimplemented from Echange_impose_base.
Definition at line 54 of file Echange_contact_CoviMAC.h.
{ }; //non utilise
Sortie & Echange_contact_CoviMAC::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 42 of file Echange_contact_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Echange_contact_CoviMAC::readOn (Entree & s) [protected, virtual]
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 47 of file Echange_contact_CoviMAC.cpp.
{
  Nom nom_bord;
  Motcle nom_champ;
  s >> nom_autre_pb_ >> nom_bord_ >> nom_champ_ >> invh_paroi_;
  invh_paroi_ = invh_paroi_ > 1e8 ? 0 : 1. / invh_paroi_;
  T_ext().typer("Ch_front_var_instationnaire_dep");
  T_ext()->fixer_nb_comp(1);
  return s;
}
const Echange_contact_CoviMAC & Echange_contact_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
Echange_contact_CoviMAC & Echange_contact_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
unsigned Echange_contact_CoviMAC::taille_memoire () const [virtual]
Reimplemented from Echange_externe_impose.
Definition at line 39 of file Echange_contact_CoviMAC.cpp.
virtual void Echange_contact_CoviMAC::verifie_ch_init_nb_comp () [inline, virtual]
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Reimplemented from Echange_externe_impose.
Definition at line 55 of file Echange_contact_CoviMAC.h.
{ }; //pas de contrainte sur les composantes de chaque cote
Member Data Documentation
Ref_Op_Diff_CoviMAC_base Echange_contact_CoviMAC::diff
Definition at line 59 of file Echange_contact_CoviMAC.h.
IntTab Echange_contact_CoviMAC::fe_dist_ [mutable, protected]
Definition at line 80 of file Echange_contact_CoviMAC.h.
Referenced by fe_dist().
int Echange_contact_CoviMAC::fe_init_ [mutable, protected]
Definition at line 81 of file Echange_contact_CoviMAC.h.
Ref_Front_VF Echange_contact_CoviMAC::fvf
Definition at line 55 of file Echange_contact_CoviMAC.h.
int Echange_contact_CoviMAC::i_fvf
Definition at line 58 of file Echange_contact_CoviMAC.h.
int Echange_contact_CoviMAC::i_o_fvf
Definition at line 58 of file Echange_contact_CoviMAC.h.
const Type_info Echange_contact_CoviMAC::info_obj [static]
Reimplemented from Echange_externe_impose.
Definition at line 51 of file Echange_contact_CoviMAC.h.
double Echange_contact_CoviMAC::invh_paroi_ [protected]
Definition at line 76 of file Echange_contact_CoviMAC.h.
Nom Echange_contact_CoviMAC::nom_autre_pb_ [protected]
Definition at line 75 of file Echange_contact_CoviMAC.h.
Nom Echange_contact_CoviMAC::nom_bord_ [protected]
Definition at line 75 of file Echange_contact_CoviMAC.h.
Nom Echange_contact_CoviMAC::nom_champ_ [protected]
Definition at line 75 of file Echange_contact_CoviMAC.h.
Ref_Op_Diff_CoviMAC_base Echange_contact_CoviMAC::o_diff
Definition at line 59 of file Echange_contact_CoviMAC.h.
Referenced by Op_Diff_CoviMAC_base::init_op_ext().
Ref_Front_VF Echange_contact_CoviMAC::o_fvf
Definition at line 55 of file Echange_contact_CoviMAC.h.
double Echange_contact_CoviMAC::t_last_maj_ [protected]
Definition at line 77 of file Echange_contact_CoviMAC.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Cond_Lim/Echange_contact_CoviMAC.h
src/CoviMAC/Cond_Lim/Echange_contact_CoviMAC.cpp