TRUST: Tetraedriser_homogene_fin Class Reference
Tetraedriser_homogene_fin Class Reference
#include <Tetraedriser_homogene_fin.h>
Public Member Functions
Tetraedriser_homogene_fin ()
~Tetraedriser_homogene_fin ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void decoupe (Zone &, Faces &, IntTab &, IntTab &, int, IntTab &, int) const
void trianguler (Zone &) const override
int creer_sommet (Domaine &, Zone &, DoubleTab &, IntTab &, IntTab &, int, IntTab &, int &, int, int &, IntTab &, int &, IntTab &, int &) const
int dimension_application () const override
Public Member Functions inherited from Triangulation_base
Triangulation_base ()
~Triangulation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void trianguler (Zone &) const =0
virtual int dimension_application () const =0
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Tetraedriser_homogene_fin & self_cast (Objet_U &)
static const Tetraedriser_homogene_fin & self_cast (const Objet_U &)
Static Public Member Functions inherited from Triangulation_base
static const Type_info * info ()
static Triangulation_base & self_cast (Objet_U &)
static const Triangulation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Triangulation_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Triangulation_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 36 of file Tetraedriser_homogene_fin.h.
Constructor & Destructor Documentation
Tetraedriser_homogene_fin()
Tetraedriser_homogene_fin::Tetraedriser_homogene_fin ()
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
~Tetraedriser_homogene_fin()
Tetraedriser_homogene_fin::~Tetraedriser_homogene_fin ()
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
Member Function Documentation
cree_instance()
Objet_U * Tetraedriser_homogene_fin::cree_instance () static
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
creer_sommet()
int Tetraedriser_homogene_fin::creer_sommet (Domaine & dom, Zone & zone, DoubleTab & new_soms, IntTab & elem_traite, IntTab & new_soms_old_elems, int NbSom, IntTab & sommets, int & compteur, int oldnbsom, int & nbnewsoms, IntTab & fait_sommet, int & nface, IntTab & fait_sommet_arete, int & narete) const
< On verifie que le sommet rattache a une face n'a pas ete cree ulterieurement
< On verifie que le sommet rattache a une arete n'a pas ete cree ulterieurement
Definition at line 189 of file Tetraedriser_homogene_fin.cpp.
{
  const DoubleTab& coord_sommets=dom.coord_sommets();
// int nb_zones = dom.nb_zones();
  int _out;
  if(NbSom==4) //!< On verifie que le sommet rattache a une face n'a pas ete cree ulterieurement
    {
      int permut,som;
      do
        {
          permut=0;
          for(int j=1; j<4; j++)
            {
              if( sommets[j]<sommets[j-1] )
                {
                  som=sommets[j-1];
                  sommets[j-1]=sommets[j];
                  sommets[j]=som;
                  permut++;
                }
            }
        }
      while(permut);
    }
  if(NbSom==2) //!< On verifie que le sommet rattache a une arete n'a pas ete cree ulterieurement
    {
      int permut,som;
      do
        {
          permut=0;
          for(int j=1; j<2; j++)
            {
              if( sommets[j]<sommets[j-1] )
                {
                  som=sommets[j-1];
                  sommets[j-1]=sommets[j];
                  sommets[j]=som;
                  permut++;
                }
            }
        }
      while(permut);
    }
  double x=0,y=0,z=0;
// x = 0.5*(coord_sommets(i1,0)+coord_sommets(i2,0));
// y = 0.5*(coord_sommets(i1,1)+coord_sommets(i2,1));
// z = 0.5*(coord_sommets(i1,2)+coord_sommets(i2,2));
  for (int ii=0 ; ii<NbSom ; ii++)
    {
      x += coord_sommets(sommets(ii),0);
      y += coord_sommets(sommets(ii),1);
      z += coord_sommets(sommets(ii),2);
    }
  x /= NbSom;
  y /= NbSom;
  z /= NbSom;
  int trouve = -1;
  trouve = zone.chercher_elements(x,y,z);
  if (trouve<0)
    {
      for (int ii=0 ; ii<NbSom ; ii++)
        {
          Cerr<<"i"<<ii<<"="<<sommets(ii)<<" coord="<<coord_sommets(sommets(ii),0)<<" "<<coord_sommets(sommets(ii),1)<<" "<<coord_sommets(sommets(ii),2)<<finl;
        }
      Cerr<<"x="<<x<<" y="<<y<<" z="<<z<<finl;
      Cerr<<"-----"<<finl;
      assert(trouve>=0);
    }
  if (elem_traite(trouve))
    {
      _out = -1;
      int j = 0;
      double epsilon = Objet_U::precision_geom;
      do
        {
          if ((std::fabs(coord_sommets(new_soms_old_elems(trouve, j), 0)-x)<epsilon) &&
              (std::fabs(coord_sommets(new_soms_old_elems(trouve, j), 1)-y)<epsilon)&&
              (std::fabs(coord_sommets(new_soms_old_elems(trouve, j), 2)-z)<epsilon))
            {
              _out = new_soms_old_elems(trouve, j);
            }
          j++;
        }
      while ((_out == -1) && (j<19));
      if (_out<0)
        {
          Cerr << "Error, not found !" << finl;
          Cerr << "found="<<trouve<<" x="<<x<<" y="<<y<<" z="<<z<<finl;
          for (int ii=0 ; ii<NbSom ; ii++)
            {
              Cerr<<"i"<<ii<<"="<<sommets(ii)<<" coord="<<coord_sommets(sommets(ii),0)<<" "<<coord_sommets(sommets(ii),1)<<" "<<coord_sommets(sommets(ii),2)<<finl;
            }
          exit();
        }
    }
  else
    {
      _out = oldnbsom + nbnewsoms;
      new_soms(compteur, 0) = x;
      new_soms(compteur, 1) = y;
      new_soms(compteur, 2) = z;
      nbnewsoms++;
      compteur++;
      if(NbSom==4)
        {
          fait_sommet(nface,  0)=sommets[0];
          fait_sommet(nface,  1)=sommets[1];
          fait_sommet(nface,  2)=sommets[2];
          fait_sommet(nface,  3)=_out;
// Cerr << sommets(0) << " " << sommets(1) << " " << sommets(2) << " " << _out << finl;
          nface++;
        }
      if(NbSom==2)
        {
          fait_sommet_arete(narete,  0)=sommets[0];
          fait_sommet_arete(narete,  1)=sommets[1];
          fait_sommet_arete(narete,  2)=_out;
// Cerr << sommets(0) << " " << sommets(1) << " " << _out << finl;
          narete++;
        }
    }
  if(_out<0)
    {
      Cerr << "Problem at the creation of node" << finl;
      exit();
    }
  return _out;
}
References Cerr, Zone::chercher_elements(), compteur, Domaine::coord_sommets(), Process::exit(), finl, and Objet_U::precision_geom.
Referenced by trianguler().
decoupe()
void Tetraedriser_homogene_fin::decoupe (Zone & zone, Faces & faces, IntTab & new_soms_old_elems, IntTab & fait_sommet, int nface, IntTab & fait_sommet_arete, int narete) const
Definition at line 33 of file Tetraedriser_homogene_fin.cpp.
{
  IntTab& sommets=faces.les_sommets();
  int nb_faces=sommets.dimension(0);
  assert(sommets.dimension(1)==4);
  IntTab nouveaux(8*nb_faces, 3);
  faces.voisins().resize(8*nb_faces, 2);
  faces.voisins()=-1;
  IntVect indice(5);
  for(int i=0; i<nb_faces; i++)
    {
      indice(0) = sommets(i,0);
      indice(1) = sommets(i,1);
      indice(2) = sommets(i,2);
      indice(3) = sommets(i,3);
// on remet un peu d'ordre dans les indices
      int permut,ind;
      do
        {
          permut=0;
          for(int j=1; j<4; j++)
            {
              if( indice[j]<indice[j-1] )
                {
                  ind=indice[j-1];
                  indice[j-1]=indice[j];
                  indice[j]=ind;
                  permut++;
                }
            }
        }
      while(permut);
      int i0=indice(0);
      int i1=indice(1);
      int i2=indice(2);
      int i3=indice(3);
      int i4=-1;
      for (int ii=0 ; ii<nface ; ii++)
        {
          if ( fait_sommet(ii,0)==i0 && fait_sommet(ii,1)==i1 && fait_sommet(ii,2)==i2 )
            {
              i4=fait_sommet(ii,3);
              break;
            }
        }
      if(i4<0)
        {
          Cerr << " FALSE " << finl;
          exit();
        }
      assert(i4>=0);
      int jj=0;
      for (int ii=0 ; ii<narete ; ii++)
        {
          if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i1)
            {
              nouveaux(jj*nb_faces+i,0) = i0;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
              nouveaux(jj*nb_faces+i,0) = i1;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
            }
          if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i2)
            {
              nouveaux(jj*nb_faces+i,0) = i0;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
              nouveaux(jj*nb_faces+i,0) = i2;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
            }
          if ( fait_sommet_arete(ii,0)==i0 && fait_sommet_arete(ii,1)==i3)
            {
              nouveaux(jj*nb_faces+i,0) = i0;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
              nouveaux(jj*nb_faces+i,0) = i3;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
            }
          if ( fait_sommet_arete(ii,0)==i1 && fait_sommet_arete(ii,1)==i2)
            {
              nouveaux(jj*nb_faces+i,0) = i1;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
              nouveaux(jj*nb_faces+i,0) = i2;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
            }
          if ( fait_sommet_arete(ii,0)==i1 && fait_sommet_arete(ii,1)==i3)
            {
              nouveaux(jj*nb_faces+i,0) = i1;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
              nouveaux(jj*nb_faces+i,0) = i3;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
            }
          if ( fait_sommet_arete(ii,0)==i2 && fait_sommet_arete(ii,1)==i3)
            {
              nouveaux(jj*nb_faces+i,0) = i2;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
              nouveaux(jj*nb_faces+i,0) = i3;
              nouveaux(jj*nb_faces+i,1) = fait_sommet_arete(ii,2);
              nouveaux(jj*nb_faces+i,2) = i4;
              jj++;
            }
        }
// if(jj!=8)
// {
// Cerr << " il manque des nouvelles faces " << finl;
// exit();
// }
      assert(jj==8);
    }
  sommets.ref(nouveaux);
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Faces::les_sommets(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), and Faces::voisins().
Referenced by trianguler().
dimension_application()
int Tetraedriser_homogene_fin::dimension_application () const inline override virtual
Implements Triangulation_base.
Definition at line 48 of file Tetraedriser_homogene_fin.h.
{
  return 3;
}
duplique()
int Tetraedriser_homogene_fin::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
get_info()
const Type_info * Tetraedriser_homogene_fin::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
info()
const Type_info * Tetraedriser_homogene_fin::info () static
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
printOn()
Sortie & Tetraedriser_homogene_fin::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 21 of file Tetraedriser_homogene_fin.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Tetraedriser_homogene_fin::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Tetraedriser_homogene_fin.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Tetraedriser_homogene_fin & Tetraedriser_homogene_fin::self_cast (const Objet_U & r) static
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
self_cast() [2/2]
Tetraedriser_homogene_fin & Tetraedriser_homogene_fin::self_cast (Objet_U & r) static
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
taille_memoire()
unsigned Tetraedriser_homogene_fin::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Tetraedriser_homogene_fin.cpp.
trianguler()
void Tetraedriser_homogene_fin::trianguler (Zone & zone) const override virtual
< PQ : 04-03 : dimensionnement de fait_sommet a 3*nbs (a revoir si insuffisant)
< PQ : 02-05 : dimensionnement de fait_sommet_arete a 3*nbs (a revoir si insuffisant)
Implements Triangulation_base.
Definition at line 348 of file Tetraedriser_homogene_fin.cpp.
{
  if  ((zone.type_elem()->que_suis_je() == "Hexaedre")
       ||(zone.type_elem()->que_suis_je() == "Hexaedre_VEF"))
    {
      IntTab& les_elems = zone.les_elems();
      int oldsz = les_elems.dimension(0);
      int nbs = zone.nb_som();
      IntTab elem_traite(oldsz);
      int oldnbsom = zone.nb_som();
      IntTab new_elems(48*oldsz, 4);
// pour chaque cube, liste des nouveaux sommets qu'il contient :
      IntTab new_soms_old_elems(oldsz,19);
      IntTab sommets(8);
      Domaine& dom = zone.domaine();
      int compteur = 0;
      int nbnewsoms = 0;
      int nface = 0;
      int narete = 0;
      int i;
      Cerr << " NB ELEM : " << oldsz << " NB NODE : " << nbs << finl;
      IntTab fait_sommet(3*nbs,4); //!< PQ : 04-03 : dimensionnement de fait_sommet a 3*nbs (a revoir si insuffisant)
      IntTab fait_sommet_arete(3*nbs,3); //!< PQ : 02-05 : dimensionnement de fait_sommet_arete a 3*nbs (a revoir si insuffisant)
      fait_sommet=-1;
      fait_sommet_arete=-1;
// Construction de l'Octree sur la grille "VDF" de base
      zone.construit_octree();
// On dimensionne une premiere fois le tableau des sommets avec la dimension maximun
// puis on redimensionnera seulement a la fin par la dimension exacte
      DoubleTab& sommets_dom = dom.les_sommets();
// int dim_som_max=19*oldsz*40;
// 19 pour les nouveaux sommets et 8 pour les anciens sommets = 27
      int dim_som_max=27*oldsz;
      int dim_som_old=sommets_dom.dimension(0);
      sommets_dom.resize(dim_som_max,3);
      IntTab indice(19);
      DoubleTab new_soms(19,3);
      for(i=0; i< oldsz; i++)
        {
          if (nface>=3*nbs)
            {
              Cerr << " The sizing of the array fait_sommet in Tetraedriser_homogene_fin::Trianguler is inappropriate " << finl;
              exit();
            }
          if (narete>=3*nbs)
            {
              Cerr << " The sizing of the array fait_sommet_arete in Tetraedriser_homogene_fin::Trianguler is inappropriate " << finl;
              exit();
            }
          int i0=les_elems(i,0);
          int i1=les_elems(i,1);
          int i2=les_elems(i,2);
          int i3=les_elems(i,3);
          int i4=les_elems(i,4);
          int i5=les_elems(i,5);
          int i6=les_elems(i,6);
          int i7=les_elems(i,7);
          compteur = 0;
// Definition des nouveaux sommets : creation des barycentres
// centre de l'hexaedre
          sommets(0)=i0;
          sommets(1)=i1;
          sommets(2)=i2;
          sommets(3)=i3;
          sommets(4)=i4;
          sommets(5)=i5;
          sommets(6)=i6;
          sommets(7)=i7;
          indice(0)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 8,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des faces bas (0-1-3-2)
          sommets(0)=i0;
          sommets(1)=i1;
          sommets(2)=i3;
          sommets(3)=i2;
          indice(1)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des faces haut (4-5-7-6)
          sommets(0)=i4;
          sommets(1)=i5;
          sommets(2)=i7;
          sommets(3)=i6;
          indice(4)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des faces avant (0-1-5-4)
          sommets(0)=i0;
          sommets(1)=i1;
          sommets(2)=i5;
          sommets(3)=i4;
          indice(3)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des faces arriere (2-3-7-6)
          sommets(0)=i2;
          sommets(1)=i3;
          sommets(2)=i7;
          sommets(3)=i6;
          indice(6)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des faces gauche (0-2-6-4)
          sommets(0)=i0;
          sommets(1)=i2;
          sommets(2)=i6;
          sommets(3)=i4;
          indice(2)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des faces droite (1-3-7-5)
          sommets(0)=i1;
          sommets(1)=i3;
          sommets(2)=i7;
          sommets(3)=i5;
          indice(5)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 4,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (0-1)
          sommets(0)=i0;
          sommets(1)=i1;
          indice(7)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (1-3)
          sommets(0)=i1;
          sommets(1)=i3;
          indice(8)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (3-2)
          sommets(0)=i3;
          sommets(1)=i2;
          indice(9)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (2-0)
          sommets(0)=i2;
          sommets(1)=i0;
          indice(10)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (1-5)
          sommets(0)=i1;
          sommets(1)=i5;
          indice(11)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (3-7)
          sommets(0)=i3;
          sommets(1)=i7;
          indice(12)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (2-6)
          sommets(0)=i2;
          sommets(1)=i6;
          indice(13)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (0-4)
          sommets(0)=i0;
          sommets(1)=i4;
          indice(14)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (4-5)
          sommets(0)=i4;
          sommets(1)=i5;
          indice(15)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (5-7)
          sommets(0)=i5;
          sommets(1)=i7;
          indice(16)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (7-6)
          sommets(0)=i7;
          sommets(1)=i6;
          indice(17)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// centres des aretes (6-4)
          sommets(0)=i6;
          sommets(1)=i4;
          indice(18)  =
            creer_sommet(dom, zone, new_soms, elem_traite, new_soms_old_elems, 2,
                         sommets, compteur, oldnbsom, nbnewsoms, fait_sommet, nface, fait_sommet_arete, narete);
// Liste des nouveaux sommets pour cet ancien cube
          for (int t=0; t<19; t++)
            {
              new_soms_old_elems(i, t) = indice(t);
              if(indice(t)<0)
                {
                  Cerr << "Error negative index" << finl;
                  exit();
                }
              for(int s=0; s<t; s++)
                if(indice(s)==indice(t))
                  {
                    Cerr << "Error repeated index" << finl;
                    exit();
                  }
            }
          for(int j=0; j<compteur; j++)
            for(int k=0; k<3; k++)
              sommets_dom(dim_som_old+j,k)=new_soms(j,k) ;
          dim_som_old += compteur;
// L'element en cours a ete "traite" en entier
          elem_traite(i) = 1;
// pyramide bas (base : 0-1-3-2)
          new_elems(i, 0) = les_elems(i,0);
          new_elems(i, 1) = indice(7);
          new_elems(i, 2) = indice(1);
          new_elems(i, 3) = indice(0);
          new_elems(i+oldsz, 0) = indice(7);
          new_elems(i+oldsz, 1) = les_elems(i,1);
          new_elems(i+oldsz, 2) = indice(1);
          new_elems(i+oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
          new_elems(i+2*oldsz, 0) = les_elems(i,1);
          new_elems(i+2*oldsz, 1) = indice(8);
          new_elems(i+2*oldsz, 2) = indice(1);
          new_elems(i+2*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
          new_elems(i+3*oldsz, 0) = indice(8);
          new_elems(i+3*oldsz, 1) = les_elems(i,3);
          new_elems(i+3*oldsz, 2) = indice(1);
          new_elems(i+3*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+3*oldsz,1);
          new_elems(i+4*oldsz, 0) = les_elems(i,3);
          new_elems(i+4*oldsz, 1) = indice(9);
          new_elems(i+4*oldsz, 2) = indice(1);
          new_elems(i+4*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+4*oldsz,1);
          new_elems(i+5*oldsz, 0) = indice(9);
          new_elems(i+5*oldsz, 1) = les_elems(i,2);
          new_elems(i+5*oldsz, 2) = indice(1);
          new_elems(i+5*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+5*oldsz,1);
          new_elems(i+6*oldsz, 0) = les_elems(i,2);
          new_elems(i+6*oldsz, 1) = indice(10);
          new_elems(i+6*oldsz, 2) = indice(1);
          new_elems(i+6*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+6*oldsz,1);
          new_elems(i+7*oldsz, 0) = indice(10);
          new_elems(i+7*oldsz, 1) = les_elems(i,0);
          new_elems(i+7*oldsz, 2) = indice(1);
          new_elems(i+7*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+7*oldsz,1);
// pyramide haut (base : 4-5-7-6)
          new_elems(i+8*oldsz, 0) = les_elems(i,4);
          new_elems(i+8*oldsz, 1) = indice(15);
          new_elems(i+8*oldsz, 2) = indice(4);
          new_elems(i+8*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+8*oldsz,1);
          new_elems(i+9*oldsz, 0) = indice(15);
          new_elems(i+9*oldsz, 1) = les_elems(i,5);
          new_elems(i+9*oldsz, 2) = indice(4);
          new_elems(i+9*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+9*oldsz,1);
          new_elems(i+10*oldsz, 0) = les_elems(i,5);
          new_elems(i+10*oldsz, 1) = indice(16);
          new_elems(i+10*oldsz, 2) = indice(4);
          new_elems(i+10*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+10*oldsz,1);
          new_elems(i+11*oldsz, 0) = indice(16);
          new_elems(i+11*oldsz, 1) = les_elems(i,7);
          new_elems(i+11*oldsz, 2) = indice(4);
          new_elems(i+11*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+11*oldsz,1);
          new_elems(i+12*oldsz, 0) = les_elems(i,7);
          new_elems(i+12*oldsz, 1) = indice(17);
          new_elems(i+12*oldsz, 2) = indice(4);
          new_elems(i+12*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+12*oldsz,1);
          new_elems(i+13*oldsz, 0) = indice(17);
          new_elems(i+13*oldsz, 1) = les_elems(i,6);
          new_elems(i+13*oldsz, 2) = indice(4);
          new_elems(i+13*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+13*oldsz,1);
          new_elems(i+14*oldsz, 0) = les_elems(i,6);
          new_elems(i+14*oldsz, 1) = indice(18);
          new_elems(i+14*oldsz, 2) = indice(4);
          new_elems(i+14*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+14*oldsz,1);
          new_elems(i+15*oldsz, 0) = indice(18);
          new_elems(i+15*oldsz, 1) = les_elems(i,4);
          new_elems(i+15*oldsz, 2) = indice(4);
          new_elems(i+15*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+15*oldsz,1);
// pyramide avant (base : 0-1-5-4)
          new_elems(i+16*oldsz, 0) = les_elems(i,0);
          new_elems(i+16*oldsz, 1) = indice(7);
          new_elems(i+16*oldsz, 2) = indice(3);
          new_elems(i+16*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+16*oldsz,1);
          new_elems(i+17*oldsz, 0) = indice(7);
          new_elems(i+17*oldsz, 1) = les_elems(i,1);
          new_elems(i+17*oldsz, 2) = indice(3);
          new_elems(i+17*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+17*oldsz,1);
          new_elems(i+18*oldsz, 0) = les_elems(i,1);
          new_elems(i+18*oldsz, 1) = indice(11);
          new_elems(i+18*oldsz, 2) = indice(3);
          new_elems(i+18*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+18*oldsz,1);
          new_elems(i+19*oldsz, 0) = indice(11);
          new_elems(i+19*oldsz, 1) = les_elems(i,5);
          new_elems(i+19*oldsz, 2) = indice(3);
          new_elems(i+19*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+19*oldsz,1);
          new_elems(i+20*oldsz, 0) = les_elems(i,5);
          new_elems(i+20*oldsz, 1) = indice(15);
          new_elems(i+20*oldsz, 2) = indice(3);
          new_elems(i+20*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+20*oldsz,1);
          new_elems(i+21*oldsz, 0) = indice(15);
          new_elems(i+21*oldsz, 1) = les_elems(i,4);
          new_elems(i+21*oldsz, 2) = indice(3);
          new_elems(i+21*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+21*oldsz,1);
          new_elems(i+22*oldsz, 0) = les_elems(i,4);
          new_elems(i+22*oldsz, 1) = indice(14);
          new_elems(i+22*oldsz, 2) = indice(3);
          new_elems(i+22*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+22*oldsz,1);
          new_elems(i+23*oldsz, 0) = indice(14);
          new_elems(i+23*oldsz, 1) = les_elems(i,0);
          new_elems(i+23*oldsz, 2) = indice(3);
          new_elems(i+23*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+23*oldsz,1);
// pyramide arriere (base : 2-3-7-6)
          new_elems(i+24*oldsz, 0) = les_elems(i,2);
          new_elems(i+24*oldsz, 1) = indice(9);
          new_elems(i+24*oldsz, 2) = indice(6);
          new_elems(i+24*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+24*oldsz,1);
          new_elems(i+25*oldsz, 0) = indice(9);
          new_elems(i+25*oldsz, 1) = les_elems(i,3);
          new_elems(i+25*oldsz, 2) = indice(6);
          new_elems(i+25*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+25*oldsz,1);
          new_elems(i+26*oldsz, 0) = les_elems(i,3);
          new_elems(i+26*oldsz, 1) = indice(12);
          new_elems(i+26*oldsz, 2) = indice(6);
          new_elems(i+26*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+26*oldsz,1);
          new_elems(i+27*oldsz, 0) = indice(12);
          new_elems(i+27*oldsz, 1) = les_elems(i,7);
          new_elems(i+27*oldsz, 2) = indice(6);
          new_elems(i+27*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+27*oldsz,1);
          new_elems(i+28*oldsz, 0) = les_elems(i,7);
          new_elems(i+28*oldsz, 1) = indice(17);
          new_elems(i+28*oldsz, 2) = indice(6);
          new_elems(i+28*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+28*oldsz,1);
          new_elems(i+29*oldsz, 0) = indice(17);
          new_elems(i+29*oldsz, 1) = les_elems(i,6);
          new_elems(i+29*oldsz, 2) = indice(6);
          new_elems(i+29*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+29*oldsz,1);
          new_elems(i+30*oldsz, 0) = les_elems(i,6);
          new_elems(i+30*oldsz, 1) = indice(13);
          new_elems(i+30*oldsz, 2) = indice(6);
          new_elems(i+30*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+30*oldsz,1);
          new_elems(i+31*oldsz, 0) = indice(13);
          new_elems(i+31*oldsz, 1) = les_elems(i,2);
          new_elems(i+31*oldsz, 2) = indice(6);
          new_elems(i+31*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+31*oldsz,1);
// pyramide gauche (base : 0-2-6-4)
          new_elems(i+32*oldsz, 0) = les_elems(i,0);
          new_elems(i+32*oldsz, 1) = indice(10);
          new_elems(i+32*oldsz, 2) = indice(2);
          new_elems(i+32*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+32*oldsz,1);
          new_elems(i+33*oldsz, 0) = indice(10);
          new_elems(i+33*oldsz, 1) = les_elems(i,2);
          new_elems(i+33*oldsz, 2) = indice(2);
          new_elems(i+33*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+33*oldsz,1);
          new_elems(i+34*oldsz, 0) = les_elems(i,2);
          new_elems(i+34*oldsz, 1) = indice(13);
          new_elems(i+34*oldsz, 2) = indice(2);
          new_elems(i+34*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+34*oldsz,1);
          new_elems(i+35*oldsz, 0) = indice(13);
          new_elems(i+35*oldsz, 1) = les_elems(i,6);
          new_elems(i+35*oldsz, 2) = indice(2);
          new_elems(i+35*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+35*oldsz,1);
          new_elems(i+36*oldsz, 0) = les_elems(i,6);
          new_elems(i+36*oldsz, 1) = indice(18);
          new_elems(i+36*oldsz, 2) = indice(2);
          new_elems(i+36*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+36*oldsz,1);
          new_elems(i+37*oldsz, 0) = indice(18);
          new_elems(i+37*oldsz, 1) = les_elems(i,4);
          new_elems(i+37*oldsz, 2) = indice(2);
          new_elems(i+37*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+37*oldsz,1);
          new_elems(i+38*oldsz, 0) = les_elems(i,4);
          new_elems(i+38*oldsz, 1) = indice(14);
          new_elems(i+38*oldsz, 2) = indice(2);
          new_elems(i+38*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+38*oldsz,1);
          new_elems(i+39*oldsz, 0) = indice(14);
          new_elems(i+39*oldsz, 1) = les_elems(i,0);
          new_elems(i+39*oldsz, 2) = indice(2);
          new_elems(i+39*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+39*oldsz,1);
// pyramide droite (base : 1-3-7-5)
          new_elems(i+40*oldsz, 0) = les_elems(i,1);
          new_elems(i+40*oldsz, 1) = indice(8);
          new_elems(i+40*oldsz, 2) = indice(5);
          new_elems(i+40*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+40*oldsz,1);
          new_elems(i+41*oldsz, 0) = indice(8);
          new_elems(i+41*oldsz, 1) = les_elems(i,3);
          new_elems(i+41*oldsz, 2) = indice(5);
          new_elems(i+41*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+41*oldsz,1);
          new_elems(i+42*oldsz, 0) = les_elems(i,3);
          new_elems(i+42*oldsz, 1) = indice(12);
          new_elems(i+42*oldsz, 2) = indice(5);
          new_elems(i+42*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+42*oldsz,1);
          new_elems(i+43*oldsz, 0) = indice(12);
          new_elems(i+43*oldsz, 1) = les_elems(i,7);
          new_elems(i+43*oldsz, 2) = indice(5);
          new_elems(i+43*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+43*oldsz,1);
          new_elems(i+44*oldsz, 0) = les_elems(i,7);
          new_elems(i+44*oldsz, 1) = indice(16);
          new_elems(i+44*oldsz, 2) = indice(5);
          new_elems(i+44*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+44*oldsz,1);
          new_elems(i+45*oldsz, 0) = indice(16);
          new_elems(i+45*oldsz, 1) = les_elems(i,5);
          new_elems(i+45*oldsz, 2) = indice(5);
          new_elems(i+45*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+45*oldsz,1);
          new_elems(i+46*oldsz, 0) = les_elems(i,5);
          new_elems(i+46*oldsz, 1) = indice(11);
          new_elems(i+46*oldsz, 2) = indice(5);
          new_elems(i+46*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+46*oldsz,1);
          new_elems(i+47*oldsz, 0) = indice(11);
          new_elems(i+47*oldsz, 1) = les_elems(i,1);
          new_elems(i+47*oldsz, 2) = indice(5);
          new_elems(i+47*oldsz, 3) = indice(0);
          mettre_a_jour_sous_zone(zone,i,i+47*oldsz,1);
        }
      sommets_dom.resize(dim_som_old,3);
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      Cerr << "We have split the cubes..." << finl;
      zone.invalide_octree();
      zone.typer("Tetraedre");
      Cerr << "  Reconstruction of the Octree" << finl;
      zone.construit_octree();
      Cerr << "  Octree rebuilt" << finl;
      {
        Cerr << "Splitting of the boundaries" << finl;
        LIST_CURSEUR(Bord) curseur(zone.faces_bord());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            les_faces.typer(Faces::triangle_3D);
            decoupe(zone, les_faces, new_soms_old_elems, fait_sommet, nface, fait_sommet_arete, narete);
            ++curseur;
          }
      }
      {
// Les Raccords
        Cerr << "Splitting of the connectors" << finl;
        LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());;;
        while(curseur)
          {
            Faces& les_faces=curseur.valeur()->faces();
            les_faces.typer(Faces::triangle_3D);
            decoupe(zone, les_faces, new_soms_old_elems, fait_sommet, nface, fait_sommet_arete, narete);
            ++curseur;
          }
      }
      {
// Les Faces internes
        Cerr << "Splitting of the internal faces" << finl;
        LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());;;
        while(curseur)
          {
            Faces& les_faces=curseur->faces();
            les_faces.typer(Faces::triangle_3D);
            decoupe(zone, les_faces, new_soms_old_elems, fait_sommet, nface, fait_sommet_arete, narete);
            ++curseur;
          }
      }
      Cerr<<"END of Tetraedriser_homogene_fin..."<<finl;
      Cerr<<"  1 NbElem="<<zone.les_elems().dimension(0)<<"  NbNod="<<zone.nb_som()<<finl;
    }
  else
    {
      Cerr << "We do not yet know how to Tetraedriser_homogene_fin the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
    }
}
References Cerr, compteur, Zone::construit_octree(), creer_sommet(), decoupe(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_raccord(), finl, Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), LIST_CURSEUR, Interprete_geometrique_base::mettre_a_jour_sous_zone(), Zone::nb_som(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::triangle_3D, Zone::type_elem(), Faces::typer(), and Zone::typer().
Member Data Documentation
info_obj
const Type_info Tetraedriser_homogene_fin::info_obj static
Definition at line 38 of file Tetraedriser_homogene_fin.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Tetraedriser_homogene_fin.h
src/Kernel/Geometrie/Tetraedriser_homogene_fin.cpp