TRUST: Ref_Convection_Diffusion_std Class Reference
Ref_Convection_Diffusion_std Class Reference
#include <Ref_Convection_Diffusion_std.h>
Public Member Functions
~Ref_Convection_Diffusion_std ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Convection_Diffusion_std ()
Ref_Convection_Diffusion_std (const Convection_Diffusion_std &)
Ref_Convection_Diffusion_std (const Ref_Convection_Diffusion_std &)
const Convection_Diffusion_std & valeur () const
Convection_Diffusion_std & valeur ()
const Convection_Diffusion_std * operator-> () const
Convection_Diffusion_std * operator-> ()
const
Ref_Convection_Diffusion_std & operator= (const Convection_Diffusion_std &)
const
Ref_Convection_Diffusion_std & operator= (const Ref_Convection_Diffusion_std &)
operator const Convection_Diffusion_std & () const
operator Convection_Diffusion_std & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Ref_Convection_Diffusion_std & self_cast (Objet_U &)
static const
Ref_Convection_Diffusion_std & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Convection_Diffusion_std * pointeur_
Detailed Description
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
Constructor & Destructor Documentation
Ref_Convection_Diffusion_std::~Ref_Convection_Diffusion_std ()
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Ref_Convection_Diffusion_std::Ref_Convection_Diffusion_std ()
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Ref_Convection_Diffusion_std::Ref_Convection_Diffusion_std (const Convection_Diffusion_std & t)
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Ref_Convection_Diffusion_std::Ref_Convection_Diffusion_std (const Ref_Convection_Diffusion_std & t)
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Member Function Documentation
Objet_U * Ref_Convection_Diffusion_std::cree_instance () [static]
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
int Ref_Convection_Diffusion_std::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Type_info * Ref_Convection_Diffusion_std::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Type_info & Ref_Convection_Diffusion_std::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Type_info * Ref_Convection_Diffusion_std::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Ref_Convection_Diffusion_std::operator const Convection_Diffusion_std & () const
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Ref_Convection_Diffusion_std::operator Convection_Diffusion_std & ()
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Convection_Diffusion_std * Ref_Convection_Diffusion_std::operator-> () const [inline]
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
Convection_Diffusion_std * Ref_Convection_Diffusion_std::operator-> () [inline]
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
const Ref_Convection_Diffusion_std & Ref_Convection_Diffusion_std::operator= (const Ref_Convection_Diffusion_std & t)
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Ref_Convection_Diffusion_std & Ref_Convection_Diffusion_std::operator= (const Convection_Diffusion_std & t)
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Sortie & Ref_Convection_Diffusion_std::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Entree & Ref_Convection_Diffusion_std::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Ref_Convection_Diffusion_std & Ref_Convection_Diffusion_std::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
Ref_Convection_Diffusion_std & Ref_Convection_Diffusion_std::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
void Ref_Convection_Diffusion_std::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
unsigned Ref_Convection_Diffusion_std::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Convection_Diffusion_std.cpp.
const Convection_Diffusion_std & Ref_Convection_Diffusion_std::valeur () const [inline]
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
Referenced by Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Modele_turbulence_scal_base::equation(), and Terme_Boussinesq_base::equation_scalaire().
Convection_Diffusion_std & Ref_Convection_Diffusion_std::valeur () [inline]
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
Member Data Documentation
const Type_info Ref_Convection_Diffusion_std::info_obj [static]
Reimplemented from Ref_.
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
Convection_Diffusion_std* Ref_Convection_Diffusion_std::pointeur_ [private]
Definition at line 27 of file Ref_Convection_Diffusion_std.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Equations/Ref_Convection_Diffusion_std.h
src/ThHyd/Incompressible/Equations/Ref_Convection_Diffusion_std.cpp