TRUST: List_Champ_Generique Class Reference
List_Champ_Generique Class Reference
classe List_Champ_Generique
Represente une liste de Champ_Generique
#include <Liste_Champ_Generique.h>
Public Member Functions
List_Champ_Generique ()
~List_Champ_Generique ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
List_Champ_Generique (const Champ_Generique &t)
List_Champ_Generique (const List_Champ_Generique &t)
Champ_Generique & operator[] (int)
const Champ_Generique & operator[] (int) const
Champ_Generique & operator[] (const Nom &)
const Champ_Generique & operator[] (const Nom &) const
Champ_Generique & operator() (int i)
const Champ_Generique & operator() (int i) const
Champ_Generique & operator() (const Nom &n)
const Champ_Generique & operator() (const Nom &n) const
Champ_Generique & valeur ()
const Champ_Generique & valeur () const
List_Champ_Generique & operator= (const Champ_Generique &t)
Champ_Generique * operator-> ()
List_Champ_Generique & operator= (const List_Champ_Generique &)
List_Champ_Generique & add (const List_Champ_Generique &)
Champ_Generique & add (const Champ_Generique &)
List_Champ_Generique & inserer (const List_Champ_Generique &)
Champ_Generique & inserer (const Champ_Generique &)
void supprimer ()
List_Champ_Generique & operator+= (const List_Champ_Generique &)
List_Champ_Generique & operator+= (const Champ_Generique &)
Champ_Generique & add_if_not (const Champ_Generique &)
Champ_Generique & add_if_not (const char *const)
List_Champ_Generique & search (const Champ_Generique &) const
List_Champ_Generique & search (const char *const) const
List_Champ_Generique & suivant ()
const List_Champ_Generique & suivant () const
const List_Champ_Generique & dernier () const
List_Champ_Generique & dernier ()
List_Champ_Generique & operator-= (const Champ_Generique &)
int est_egal_a (const Objet_U &) const override
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Champ_Generique &) const
int contient (const char *const) const
int rang (const Champ_Generique &) const
void suppr (const Champ_Generique &)
Public Member Functions inherited from liste
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
liste ()
Constructeur par defaut
Construit une liste vide.
liste (const liste &)
Constructeur
Ajoute les elements contenus dans la liste passe en parametre.
liste (const Objet_U &)
Constructeur
Construit une liste singleton.
~liste () override
Destructeur de liste.
int size () const
Renvoie la taille de la liste
Une liste vide est de taille nulle.
int rang (const char *const) const
Renvoie le rang d'une chaine de caracteres contenue dans la liste
Recherche un Objet_U de Nom ch.
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
void suppr (const char *const)
Supprime l'Objet de Nom ch contenu dans la liste.
int est_vide () const
Teste si la liste est vide.
int est_dernier () const
Teste si la liste comporte des elements suivants ou non.
Retourne 1 si la liste est vide.
void vide ()
Vide la liste.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static List_Champ_Generique & self_cast (Objet_U &)
static const List_Champ_Generique & self_cast (const Objet_U &)
Static Public Member Functions inherited from liste
static Objet_U * cree_instance ()
static const Type_info * info ()
static liste & self_cast (Objet_U &)
static const liste & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from liste
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int est_egal_a (const List_Champ_Generique &) const
Protected Member Functions inherited from liste
Sortie & printOn (Sortie &x) const override
Ecriture d'une liste sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une liste sur un flot d'entree.
Objet_U & operator() (int)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Objet_U & operator() (int) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Objet_U & operator() (const Nom &)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Objet_U & operator() (const Nom &) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Objet_U & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Objet_U & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
liste & operator+= (const Objet_U &)
Ajoute un Objet_U a la fin de la liste.
liste & operator+= (const liste &)
Ajoute une list d'Objet_U a la fin de la liste.
liste & operator-= (const Objet_U &)
Supprime un Objet_U de la liste
Affiche un message d'erreur si l'objet n'est pas trouve.
const liste & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
liste & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
Objet_U * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
const Objet_U * operator-> () const
Retourne un pointeur sur l'Objet_U premier element de la liste.
Objet_U & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Objet_U & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Objet_U & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Objet_U & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Objet_U & add (const Objet_U &)
Ajout d'un Objet_U a la liste.
Objet_U & add_deplace (DerObjU &)
Ajout d'un Objet_U a la liste
to_add est libere en sortie.
Objet_U & inserer (const Objet_U &)
Insertion d'un Objet_U dans la liste.
liste & add (const liste &)
Ajout d'une liste a la liste.
liste & inserer (const liste &)
Insertion d'une liste
NON CODE - SORT SYSTEMATIQUEMENT EN ERREUR.
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Objet_U & add_if_not (const Objet_U &)
Ajout d'un Objet_U a la liste ssi il n'existe pas deja.
liste & search (const Objet_U &) const
Recherche d'un Objet_U dans la liste.
liste & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
int contient (const Objet_U &) const
Verifie si un Objet_U appartient ou non a la liste.
int rang (const Objet_U &) const
Renvoie le rang d'un Objet_U dans la liste.
void suppr (const Objet_U &)
Supprime un Objet_U contenu dans la liste.
liste & operator= (const liste &)
Operateur d'affectation de liste.
const liste & dernier () const
Renvoie le dernier element de la liste.
liste & dernier ()
Renvoie le dernier element de la liste.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from liste
DerObjU data
liste * suivant_
Detailed Description
classe List_Champ_Generique
Represente une liste de Champ_Generique
Definition at line 33 of file Liste_Champ_Generique.h.
Constructor & Destructor Documentation
List_Champ_Generique() [1/3]
List_Champ_Generique::List_Champ_Generique ()
Definition at line 18 of file Liste_Champ_Generique.cpp.
~List_Champ_Generique()
List_Champ_Generique::~List_Champ_Generique ()
Definition at line 18 of file Liste_Champ_Generique.cpp.
List_Champ_Generique() [2/3]
List_Champ_Generique::List_Champ_Generique (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
List_Champ_Generique() [3/3]
List_Champ_Generique::List_Champ_Generique (const List_Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
Member Function Documentation
add() [1/2]
Champ_Generique & List_Champ_Generique::add (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
add() [2/2]
List_Champ_Generique & List_Champ_Generique::add (const List_Champ_Generique & a_list) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
Referenced by Champ_Generique_Transformation::completer(), Champ_Gen_de_Champs_Gen::get_set_source(), and Champ_Gen_de_Champs_Gen::lire_motcle_non_standard().
add_if_not() [1/2]
Champ_Generique & List_Champ_Generique::add_if_not (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
Referenced by Postraitement::complete_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), and Postraitement::creer_champ_post_stat().
add_if_not() [2/2]
Champ_Generique & List_Champ_Generique::add_if_not (const char * const t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
contient() [1/2]
int List_Champ_Generique::contient (const Champ_Generique & t) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
contient() [2/2]
int List_Champ_Generique::contient (const char * const c) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
cree_instance()
Objet_U * List_Champ_Generique::cree_instance () static
Definition at line 18 of file Liste_Champ_Generique.cpp.
dernier() [1/2]
List_Champ_Generique & List_Champ_Generique::dernier () inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
dernier() [2/2]
const List_Champ_Generique & List_Champ_Generique::dernier () const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
duplique()
int List_Champ_Generique::duplique () const override virtual
Implements Objet_U.
Reimplemented in Liste_Champ_Generique.
Definition at line 18 of file Liste_Champ_Generique.cpp.
est_egal_a() [1/2]
int List_Champ_Generique::est_egal_a (const List_Champ_Generique &) const inline protected
est_egal_a() [2/2]
int List_Champ_Generique::est_egal_a (const Objet_U & x) const override virtual
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 18 of file Liste_Champ_Generique.cpp.
get_info()
const Type_info * List_Champ_Generique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Liste_Champ_Generique.
Definition at line 18 of file Liste_Champ_Generique.cpp.
info()
const Type_info * List_Champ_Generique::info () static
Definition at line 18 of file Liste_Champ_Generique.cpp.
inserer() [1/2]
Champ_Generique & List_Champ_Generique::inserer (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
inserer() [2/2]
List_Champ_Generique & List_Champ_Generique::inserer (const List_Champ_Generique & a_list) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator()() [1/4]
Champ_Generique & List_Champ_Generique::operator() (const Nom & n) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator()() [2/4]
const Champ_Generique & List_Champ_Generique::operator() (const Nom & n) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator()() [3/4]
Champ_Generique & List_Champ_Generique::operator() (int i) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator()() [4/4]
const Champ_Generique & List_Champ_Generique::operator() (int i) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator+=() [1/2]
List_Champ_Generique & List_Champ_Generique::operator+= (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator+=() [2/2]
List_Champ_Generique & List_Champ_Generique::operator+= (const List_Champ_Generique & a_list) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator-=()
List_Champ_Generique & List_Champ_Generique::operator-= (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator->()
Champ_Generique * List_Champ_Generique::operator-> () inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator=() [1/2]
List_Champ_Generique & List_Champ_Generique::operator= (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator=() [2/2]
List_Champ_Generique & List_Champ_Generique::operator= (const List_Champ_Generique & a_list) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator[]() [1/4]
Champ_Generique & List_Champ_Generique::operator[] (const Nom & nom) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator[]() [2/4]
const Champ_Generique & List_Champ_Generique::operator[] (const Nom & nom) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator[]() [3/4]
Champ_Generique & List_Champ_Generique::operator[] (int i) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
operator[]() [4/4]
const Champ_Generique & List_Champ_Generique::operator[] (int i) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
printOn()
Sortie & List_Champ_Generique::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Liste_Champ_Generique.
Definition at line 18 of file Liste_Champ_Generique.cpp.
rang()
int List_Champ_Generique::rang (const Champ_Generique & t) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
readOn()
Entree & List_Champ_Generique::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Liste_Champ_Generique.
Definition at line 18 of file Liste_Champ_Generique.cpp.
search() [1/2]
List_Champ_Generique & List_Champ_Generique::search (const Champ_Generique & t) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
search() [2/2]
List_Champ_Generique & List_Champ_Generique::search (const char * const c) const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
self_cast() [1/2]
const List_Champ_Generique & List_Champ_Generique::self_cast (const Objet_U & r) static
Definition at line 18 of file Liste_Champ_Generique.cpp.
self_cast() [2/2]
List_Champ_Generique & List_Champ_Generique::self_cast (Objet_U & r) static
Definition at line 18 of file Liste_Champ_Generique.cpp.
suivant() [1/2]
List_Champ_Generique & List_Champ_Generique::suivant () inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
suivant() [2/2]
const List_Champ_Generique & List_Champ_Generique::suivant () const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
suppr()
void List_Champ_Generique::suppr (const Champ_Generique & t) inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
supprimer()
void List_Champ_Generique::supprimer () inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
taille_memoire()
unsigned List_Champ_Generique::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Liste_Champ_Generique.
Definition at line 18 of file Liste_Champ_Generique.cpp.
valeur() [1/2]
Champ_Generique & List_Champ_Generique::valeur () inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
Referenced by Postraitement::creer_champ_post_med(), Postraitement::get_champ_post(), Champ_Gen_de_Champs_Gen::get_source(), and Postraitement::mettre_a_jour().
valeur() [2/2]
const Champ_Generique & List_Champ_Generique::valeur () const inline
Definition at line 33 of file Liste_Champ_Generique.h.
: public LIST(Champ_Generique)
Member Data Documentation
info_obj
const Type_info List_Champ_Generique::info_obj static
Definition at line 33 of file Liste_Champ_Generique.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Liste_Champ_Generique.h
src/Kernel/Framework/Liste_Champ_Generique.cpp