TRUST: Piso Class Reference
Piso Class Reference
#include <Piso.h>
Public Member Functions
~Piso ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Piso ()
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
virtual void first_special_treatment (Equation_base &, Navier_Stokes_std &eqnNS, DoubleTab &current, double dt, DoubleTrav &resu)
virtual void second_special_treatment (Equation_base &eqn, DoubleTab &current, DoubleTrav &resu, Matrice_Morse &matrice)
Public Member Functions inherited from Simpler
Simpler ()
~Simpler ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
Public Member Functions inherited from Simple
~Simple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Simple ()
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override
void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok) override
bool iterer_eqs (List_Ref_Equation_base eqs, int compteur, int &ok) override
Public Member Functions inherited from Simpler_Base
~Simpler_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int max_iter_implicite ()
int max_iter_implicite () const
bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok) override=0
virtual void iterer_NS (Equation_base &, DoubleTab &current, DoubleTab &pression, double, Matrice_Morse &, double, DoubleTrav &, int nb_iter, int &converge, int &ok)=0
void assembler_matrice_pression_implicite (Equation_base &eqn_NS, const Matrice_Morse &matrice, Matrice &matrice_en_pression_2)
Parametre_equation & get_and_set_parametre_equation (Equation_base &) override
retourne le parametre_implicte de l'equation si il existe si il n'existe pas le cree...
si les params sont vides on copie ceux du simpler
Parametre_implicite & get_and_set_parametre_implicite (Equation_base &eqn)
Public Member Functions inherited from Solveur_non_lineaire
Solveur_non_lineaire ()
~Solveur_non_lineaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Solveur_Implicite_Base
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Piso & self_cast (Objet_U &)
static const Piso & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simpler
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simpler & self_cast (Objet_U &)
static const Simpler & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simple
static Objet_U * cree_instance ()
static const Type_info * info ()
static Simple & self_cast (Objet_U &)
static const Simple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Simpler_Base
static const Type_info * info ()
static Simpler_Base & self_cast (Objet_U &)
static const Simpler_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_non_lineaire
static const Type_info * info ()
static Solveur_non_lineaire & self_cast (Objet_U &)
static const Solveur_non_lineaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Implicite_Base
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Simpler
static const Type_info info_obj
Static Public Attributes inherited from Simple
static const Type_info info_obj
Static Public Attributes inherited from Simpler_Base
static const Type_info info_obj
Static Public Attributes inherited from Solveur_non_lineaire
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Implicite_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & lire (const Motcle &, Entree &) override
Protected Member Functions inherited from Simpler
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Simple
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Entree & lire (const Motcle &, Entree &) override
void calculer_correction_en_vitesse (const DoubleTrav &correction_en_pression, DoubleTrav &gradP, DoubleTrav &correction_en_vitesse, const Matrice_Morse &matrice, const Operateur_Grad &gradient)
Protected Member Functions inherited from Simpler_Base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Entree & lire (const Motcle &, Entree &)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int nb_corrections_max_
int avancement_crank_
on ne fait pas vraiment du piso mais plutot du CN
Protected Attributes inherited from Simple
DoubleTab Ustar_old
double alpha_
double beta_
int with_d_rho_dt_
std::map< std::vector< intptr_t >, Matrice_Bloc > mbloc
Protected Attributes inherited from Simpler_Base
Parametre_implicite param_defaut_
int is_seuil_convg_variable
double facteur_convg_
int no_qdm_
int controle_residu_
Detailed Description
Definition at line 83 of file Piso.h.
Constructor & Destructor Documentation
~Piso()
Piso::~Piso ()
Definition at line 36 of file Piso.cpp.
Piso()
Piso::Piso ()
Definition at line 40 of file Piso.cpp.
{
  nb_corrections_max_ = 21;
  avancement_crank_ = 0;
}
References avancement_crank_, and nb_corrections_max_.
Member Function Documentation
cree_instance()
Objet_U * Piso::cree_instance () static
Definition at line 36 of file Piso.cpp.
duplique()
int Piso::duplique () const override virtual
Implements Objet_U.
Reimplemented in Implicite.
Definition at line 36 of file Piso.cpp.
first_special_treatment()
void Piso::first_special_treatment (Equation_base & eqn, Navier_Stokes_std & eqnNS, DoubleTab & current, double dt, DoubleTrav & resu) virtual
Reimplemented in Implicite.
Definition at line 412 of file Piso.cpp.
{
// nothing to do
}
Referenced by iterer_NS().
get_info()
const Type_info * Piso::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Implicite.
Definition at line 36 of file Piso.cpp.
info()
const Type_info * Piso::info () static
Definition at line 36 of file Piso.cpp.
iterer_NS()
void Piso::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Implements Simpler_Base.
Definition at line 127 of file Piso.cpp.
{
  converge = 1;
  if (nb_ite>1) return;
  Navier_Stokes_std& eqnNS = ref_cast(Navier_Stokes_std,eqn);
  Parametre_implicite& param_eqn = get_and_set_parametre_implicite(eqn);
  SolveurSys& le_solveur_ = param_eqn.solveur();
  DoubleTrav gradP(current);
  DoubleTrav correction_en_pression(pression);
  DoubleTrav resu(current);
  int is_dilat = eqn.probleme().is_dilatable();
  double vitesse_norme,vitesse_norme_old ;
  double pression_norme,pression_norme_old ;
  vitesse_norme_old = 1.e10 ;
  pression_norme_old = 1.e10 ;
// int deux_entrees = 0;
// if (current.nb_dim()==2) deux_entrees = 1;
  Operateur_Grad& gradient = eqnNS.operateur_gradient();
  Operateur_Div& divergence = eqnNS.operateur_divergence();
// int nb_comp = 1;
// int nb_dim = current.nb_dim();
// if(nb_dim==2)    nb_comp = current.dimension(1);
// Construction de matrice et resu
// matrice = A[Un] = M/delta_t + CONV +DIFF
// resu =  A[Un]Un -(A[Un]Un-Ss) + Sv -BtPn
// <IBM> Taking into account penality term for Immersed Boundary Method
  const int i_source_PDF = eqnNS.get_i_source_pdf();
  if (i_source_PDF != -1)
    {
      Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((eqnNS.sources())[i_source_PDF].valeur());
      Cerr<<"Immersed Interface: Dirichlet velocity in momentum equation for PDF (if any)."<<finl;
// Terme PDF IB value : -rho/delta_t  ksi_gamma/epsilon U_gamma
      DoubleTab secmem_pdf(resu);
      src.calculer_pdf(secmem_pdf);
      resu -= secmem_pdf;
      resu.echange_espace_virtuel();
// Terme en temps : -rho/delta_t ksi_gamma Un
      int i_traitement_special = 101;
      if (eqnNS.nombre_d_operateurs() > 1)
        {
          if (eqnNS.vitesse_pour_transport().le_nom()=="rho_u") i_traitement_special = 1;
        }
      DoubleTrav secmem_pdf_time(resu);
      src.calculer(secmem_pdf_time, i_traitement_special);
      secmem_pdf += secmem_pdf_time;
// Sauvegarde de secmem_pdf
      secmem_pdf.echange_espace_virtuel();
      src.set_sec_mem_pdf(secmem_pdf);
      DoubleTab coeff;
      coeff = eqnNS.get_champ_coeff_pdf_som();
      if (eqnNS.get_gradient_pression_qdm_modifie()==1)
        {
          Cerr<<"(IBM) Immersed Interface: modified pressure gradient in momentum equation."<<finl;
          gradP/=coeff;
        }
      gradP.echange_espace_virtuel();
    }
// </IBM>
  gradient.valeur().calculer(pression,gradP);
  if (eqnNS.has_interface_blocs()) //si l'interface blocs est disponible, on l'utilise
    {
      eqnNS.assembler_blocs_avec_inertie({{ "vitesse", &matrice }}, resu);
      if (eqnNS.discretisation().que_suis_je().debute_par("PolyMAC"))
        matrice.ajouter_multvect(current, resu);  //pour ne pas etre en increment
    }
  else //sinon, on passe par ajouter/contribuer
    {
      resu -= gradP;
      first_special_treatment( eqn, eqnNS, current, dt, resu );
      eqnNS.assembler_avec_inertie(matrice,current,resu);
    }
  le_solveur_.valeur().reinit();
// sometimes we need a second special treatement like for ALE for example
  second_special_treatment( eqn, current, resu, matrice );
// Construction de matrice_en_pression_2 = BD-1Bt[Un]
// Assemblage reeffectue seulement pour algorithme Piso (avancement_crank_==0)
  Matrice& matrice_en_pression_2 = eqnNS.matrice_pression();
  SolveurSys& solveur_pression_ = eqnNS.solveur_pression();
  if (avancement_crank_==0)
    {
      assembler_matrice_pression_implicite(eqnNS,matrice,matrice_en_pression_2);
      solveur_pression_.valeur().reinit();
    }
// Etape predicteur
// Resolution du systeme A[Un]U* = -BtPn + Sv + Ss
// current = U*
  le_solveur_.resoudre_systeme(matrice,resu,current);
  test_imposer_cond_lim(eqn,current,"apres resolution ",0);
  current.echange_espace_virtuel();
  Debog::verifier("Piso::iterer_NS current apres solveur",current);
// Calcul de secmem = BU* (en incompressible) BU* -drho/dt (en quasi-compressible)
  if (is_dilat)
    {
      if (with_d_rho_dt_)
        {
          Fluide_Dilatable_base& fluide_dil = ref_cast(Fluide_Dilatable_base,eqn.milieu());
          fluide_dil.secmembre_divU_Z(secmem);
          secmem *= -1;
        }
      else   secmem = 0;
      divergence.ajouter(current,secmem);
    }
  else
    divergence.calculer(current,secmem);
  secmem *= -1;
  secmem.echange_espace_virtuel();
  Debog::verifier("Piso::iterer_NS secmem",secmem);
// GF il ne faut pas modifier le scd membre le terme en du/dt au bord a deja ete pris en compte dans la resolution precedente
// eqnNS.assembleur_pression().valeur().modifier_secmem(secmem);
// Etape de correction 1
  Cout << "Solving mass equation :" << finl;
// Description du cas implicite
// Resolution du systeme (BD-1Bt)P' = Bu* (D-1 = M-1 pour le cas implicite)
// correction_en_pression = P' pour Piso et correction_en_pression = delta_t*P' pour implicite
  eqnNS.assembleur_pression()->modifier_secmem_pour_incr_p(pression, 1. / dt, secmem);
  solveur_pression_.resoudre_systeme(matrice_en_pression_2.valeur(),
                                     secmem,correction_en_pression);
  correction_en_pression.echange_espace_virtuel();
  Debog::verifier("Piso::iterer_NS apres correction_pression",correction_en_pression);
  if (avancement_crank_==1)
    {
// calcul de Un+1
// Calcul de Bt(delta_t*delta_P)
      gradient.valeur().multvect(correction_en_pression,gradP);
      eqn.solv_masse().appliquer(gradP);
      if ((i_source_PDF != -1) && (eqnNS.get_correction_vitesse_modifie()==1))
        {
          Cerr<<"(IBM) Immersed Interface: modified velocity correction."<<finl;
          DoubleTab coeff;
          coeff = eqnNS.get_champ_coeff_pdf_som();
          gradP/=coeff;
          gradP.echange_espace_virtuel();
        }
// Calcul de Un+1 = U* -delta_t*delta_P
      current -= gradP;
      eqn.solv_masse().corriger_solution(current, current); //pour PolyMAC_P0 : sert a corriger ve
      current.echange_espace_virtuel();
      divergence.calculer(current,secmem);
// Calcul de Pn+1 = Pn + (delta_t*delta_P)/delat_t
      Debog::verifier("Piso::iterer_NS correction avant dt",correction_en_pression);
      correction_en_pression /= dt;
// <IBM> Immersed Interface: modified pressure correction.
      if ((i_source_PDF != -1) && (eqnNS.get_correction_pression_modifie()==1))
        {
          Cerr<<"Immersed Interface: modified pressure correction."<<finl;
          DoubleTab coeff;
          coeff = eqnNS.get_champ_coeff_pdf_som();
          const Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((eqnNS.sources())[i_source_PDF].valeur());
          src.correct_pressure(coeff,pression,correction_en_pression);
        }
      else
        {
          pression += correction_en_pression;
        }
// </IBM>
      eqnNS.assembleur_pression().valeur().modifier_solution(pression);
      pression.echange_espace_virtuel();
      Debog::verifier("Piso::iterer_NS pression finale",pression);
      Debog::verifier("Piso::iterer_NS current final",current);
      if (is_dilat)
        {
// on redivise par rho_np_1 avant de sortir
          diviser_par_rho_np1_face(eqn,current);
        }
      return;
    }
// calcul de la correction en vitesse premiere etape (DU' =-Bt P)
// Calcul de P* = Pn + P'
  pression += correction_en_pression;
  eqnNS.assembleur_pression().valeur().modifier_solution(pression);
// Resolution du systeme D[Un]U' = -BtP'
  DoubleTrav correction_en_vitesse(current);
  calculer_correction_en_vitesse(correction_en_pression,gradP,correction_en_vitesse,matrice,gradient);
// Calcul de U** = U* + U'
  current += correction_en_vitesse;
  test_imposer_cond_lim(eqn,current,"apres premiere correction ",0);
  Debog::verifier("Piso::iterer_NS arpes cor pression",pression);
  Debog::verifier("Piso::iterer_NS arpes cor vitesse",current);
// Etape correcteur 2
  for (int compt=0; compt<nb_corrections_max_-1; compt++)
    {
      correction_en_vitesse.echange_espace_virtuel();
// Resolution du systeme D resu = EU' + (resu2=0) pour stocker resu = D-1EU'
      DoubleTrav resu2(resu);
      int status = inverser_par_diagonale(matrice,resu2,correction_en_vitesse,resu);
      if (status!=0) exit();
// calcul de P''  BD-1Bt P''= -div(D-1EU')
      resu.echange_espace_virtuel();
// Calcul de B(D-1EU')
      divergence.calculer(resu,secmem);
      secmem *= -1;
      secmem.echange_espace_virtuel();
// Resolution du systeme (BD-1Bt)P'' = (BD-1E)U'
// correction_en_pression = P''
      correction_en_pression = 0;
      solveur_pression_.resoudre_systeme(matrice_en_pression_2.valeur(),
                                         secmem,correction_en_pression);
#ifdef DEBUG
// Pour verifier que le calcul du gradient ne modifie pas la pression
      DoubleTrav correction_en_pression_mod(pression);
      correction_en_pression_mod = correction_en_pression;
#endif
// Resolution du systeme D[Un]U'' = -BtP''
// correction_en_vitesse = U''
      calculer_correction_en_vitesse(correction_en_pression,gradP,correction_en_vitesse,matrice,gradient);
#ifdef DEBUG
      correction_en_pression_mod -= correction_en_pression;
      assert(max_abs(correction_en_pression_mod)==0);
#endif
// Calcul de U'' = U'' + D-1EU'
      correction_en_vitesse += resu;
// ajout des increments
      vitesse_norme = mp_norme_vect(correction_en_vitesse);
      pression_norme = mp_norme_vect(correction_en_pression);
      if ( (vitesse_norme>vitesse_norme_old) || (pression_norme>pression_norme_old) )
        {
          Cout <<"PISO : "<< compt+1 <<" corrections to perform the projection."<< finl;
          if (is_dilat)
            {
// on redivise par rho_np_1 avant de sortir
              diviser_par_rho_np1_face(eqn,current);
            }
          return ;
        }
      vitesse_norme_old = vitesse_norme;
      pression_norme_old = pression_norme;
// Calcul de P** = P* + P''
      pression += correction_en_pression;
      eqnNS.assembleur_pression().valeur().modifier_solution(pression);
// Calcul de U*** = U** + U''
      current += correction_en_vitesse;
      test_imposer_cond_lim(eqn,current,"apres correction (int)__LINE__",0);
      Debog::verifier("Piso::iterer_NS apres correction pression",pression);
      Debog::verifier("Piso::iterer_NS apres correction vitesse",current);
    }
  if (is_dilat)
    {
      diviser_par_rho_np1_face(eqn,current);
// ref_cast(Navier_Stokes_QC,eqn).impr_impl(eqnNS, Cout);
    }
  current.echange_espace_virtuel();
// divergence.calculer(current, secmem); Cerr<<" ici DIVU  "<<mp_max_abs_vect(secmem)<<finl;;
  Cout <<"PISO : "<<nb_corrections_max_<<" corrections to perform the projection."<< finl;
}
References Operateur_Div::ajouter(), Matrice_Base::ajouter_multvect(), Solveur_Masse::appliquer(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Simpler_Base::assembler_matrice_pression_implicite(), Navier_Stokes_std::assembleur_pression(), avancement_crank_, Operateur_base::calculer(), Operateur_Div::calculer(), Source_PDF_base::calculer(), Simple::calculer_correction_en_vitesse(), Source_PDF_base::calculer_pdf(), Cerr, coeff, Source_PDF_base::correct_pressure(), Solveur_Masse::corriger_solution(), Cout, Nom::debute_par(), Equation_base::discretisation(), diviser_par_rho_np1_face(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, first_special_treatment(), Simpler_Base::get_and_set_parametre_implicite(), Navier_Stokes_std::get_champ_coeff_pdf_som(), Navier_Stokes_std::get_correction_pression_modifie(), Navier_Stokes_std::get_correction_vitesse_modifie(), Navier_Stokes_std::get_gradient_pression_qdm_modifie(), Navier_Stokes_std::get_i_source_pdf(), Navier_Stokes_std::has_interface_blocs(), inverser_par_diagonale(), Probleme_base::is_dilatable(), Field_base::le_nom(), Navier_Stokes_std::matrice_pression(), Equation_base::milieu(), Assembleur_base::modifier_solution(), mp_norme_vect(), Operateur_Grad_base::multvect(), nb_corrections_max_, Navier_Stokes_std::nombre_d_operateurs(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, SolveurSys_base::reinit(), SolveurSys::resoudre_systeme(), Fluide_Dilatable_base::secmembre_divU_Z(), second_special_treatment(), Source_PDF_base::set_sec_mem_pdf(), Equation_base::solv_masse(), Parametre_implicite::solveur(), Navier_Stokes_std::solveur_pression(), Equation_base::sources(), test_imposer_cond_lim(), Deriv_Assembleur_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Deriv_Operateur_Grad_base::valeur(), valeur(), Debog::verifier(), Navier_Stokes_std::vitesse_pour_transport(), and Simple::with_d_rho_dt_.
lire()
Entree & Piso::lire (const Motcle & motlu, Entree & is) override protected virtual
Implements Simpler_Base.
Definition at line 74 of file Piso.cpp.
{
  Motcles les_mots(1);
  {
    les_mots[0] = "nb_corrections_max";
  }
  int rang = les_mots.search(motlu);
  switch(rang)
    {
    case 0:
      {
        is >> nb_corrections_max_;
        if (nb_corrections_max_ < 2)
          {
            Cerr<<"There must be at least two corrections steps for the PISO algorithm."<<finl;
            exit();
          }
        break;
      }
    default :
      {
        Cerr << "Keyword : " << motlu << " is not understood in " << que_suis_je() << finl;
        exit();
      }
    }
  return is;
}
References Cerr, Process::exit(), finl, nb_corrections_max_, Objet_U::que_suis_je(), and Motcles::search().
printOn()
Sortie & Piso::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Implicite.
Definition at line 51 of file Piso.cpp.
{
  return Simpler::printOn(os);
}
References Simpler::printOn().
Referenced by Implicite::printOn().
readOn()
Entree & Piso::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Solveur_non_lineaire.
Reimplemented in Implicite.
Definition at line 56 of file Piso.cpp.
{
  Simpler::readOn(is);
  return is;
}
References Simpler::readOn().
Referenced by Implicite::readOn().
second_special_treatment()
void Piso::second_special_treatment (Equation_base & eqn, DoubleTab & current, DoubleTrav & resu, Matrice_Morse & matrice) virtual
Reimplemented in Implicite.
Definition at line 417 of file Piso.cpp.
{
// nothing to do
}
Referenced by iterer_NS().
self_cast() [1/2]
const Piso & Piso::self_cast (const Objet_U & r) static
Definition at line 36 of file Piso.cpp.
self_cast() [2/2]
Piso & Piso::self_cast (Objet_U & r) static
Definition at line 36 of file Piso.cpp.
taille_memoire()
unsigned Piso::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Implicite.
Definition at line 36 of file Piso.cpp.
Member Data Documentation
avancement_crank_
int Piso::avancement_crank_ protected
on ne fait pas vraiment du piso mais plutot du CN
Definition at line 97 of file Piso.h.
Referenced by Implicite::Implicite(), iterer_NS(), and Piso().
info_obj
const Type_info Piso::info_obj static
Definition at line 86 of file Piso.h.
nb_corrections_max_
int Piso::nb_corrections_max_ protected
Definition at line 96 of file Piso.h.
Referenced by iterer_NS(), lire(), and Piso().
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Piso.h
src/ThHyd/Schemas_Temps/Piso.cpp