TRUST: Eval_Puiss_Neutr_VDF_Elem Class Reference
Eval_Puiss_Neutr_VDF_Elem Class Reference
#include <Eval_Puiss_Neutr_VDF_Elem.h>
Public Member Functions
Eval_Puiss_Neutr_VDF_Elem ()
void associer_champs (const Champ_base &, const Champ_Don &, const Champ_Don &)
void associer_repartition (const Nom &fxyz, const Nom &nom_ssz)
void mettre_a_jour ()
double calculer_terme_source (int) const
void calculer_terme_source (int, DoubleVect &) const
void completer ()
Protected Attributes
Ref_Champ_base rho_ref
double rho_ref_
Ref_Champ_Don Cp
double Cp_
Ref_Champ_Uniforme la_puissance
double puissance
DoubleTab rep
Nom fxyz
Detailed Description
Definition at line 38 of file Eval_Puiss_Neutr_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Puiss_Neutr_VDF_Elem::Eval_Puiss_Neutr_VDF_Elem () [inline]
Definition at line 69 of file Eval_Puiss_Neutr_VDF_Elem.h.
:rho_ref_(-123.),Cp_(-123.) {}
Member Function Documentation
void Eval_Puiss_Neutr_VDF_Elem::associer_champs (const Champ_base & rho, const Champ_Don & capa, const Champ_Don & Q)
Definition at line 30 of file Eval_Puiss_Neutr_VDF_Elem.cpp.
References Cp, Cp_, la_puissance, puissance, ref_cast, rho_ref, rho_ref_, and Deriv_Champ_Don_base::valeur().
Referenced by Source_Neutronique_VDF::associer_pb().
{
  rho_ref = rho;
  rho_ref_ = rho(0,0);
  Cp = capa;
  Cp_ = capa(0,0);
  la_puissance = ref_cast(Champ_Uniforme,Q.valeur());
  puissance = Q(0,0);
}
void Eval_Puiss_Neutr_VDF_Elem::associer_repartition (const Nom & fxyz, const Nom & nom_ssz)
Definition at line 42 of file Eval_Puiss_Neutr_VDF_Elem.cpp.
References Objet_U::dimension, fxyz, Nom::getChar(), Evaluateur_Source_VDF::la_zone, Sous_Zone::nb_elem_tot(), rep, and DoubleTab::resize().
Referenced by Source_Neutronique_VDF::associer_pb().
{
  const int nb_elem = la_zone->nb_elem();
  const DoubleTab& xp = la_zone->xp();
  const Sous_Zone& ssz = la_zone->zone().domaine().ss_zone(nom_ssz);
  fxyz = n;
  String2 sfxyz(fxyz.getChar());
  Parser         p(sfxyz,3);
  p.addVar("x");
  p.addVar("y");
  p.addVar("z");
  p.parseString();
  rep.resize(nb_elem);
  rep = 0.;
  for(int i=0; i<ssz.nb_elem_tot(); i++)
    rep(ssz(i))=1.;
  for (int i=0; i<nb_elem; i++)
    {
      double x,y,z;
      x = xp(i,0);
      y = xp(i,1);
      if (Objet_U::dimension == 3) z = xp(i,2);
      else z=0.;
      p.setVar("x",x);
      p.setVar("y",y);
      p.setVar("z",z);
      rep(i) *= p.eval();
    }
}
void Eval_Puiss_Neutr_VDF_Elem::calculer_terme_source (int , DoubleVect &) const [inline, virtual]
Implements Evaluateur_Source_VDF.
Definition at line 78 of file Eval_Puiss_Neutr_VDF_Elem.h.
{
  ;
}
double Eval_Puiss_Neutr_VDF_Elem::calculer_terme_source (int num_elem) const [inline, virtual]
Implements Evaluateur_Source_VDF.
Definition at line 71 of file Eval_Puiss_Neutr_VDF_Elem.h.
References Cp_, est_egal(), Evaluateur_Source_VDF_Elem::porosite_vol, puissance, rep, rho_ref_, and Evaluateur_Source_VDF_Elem::volumes.
{
  assert(!est_egal(Cp_,-123.));
  assert(!est_egal(rho_ref_,-123.));
  return rep(num_elem)*puissance*volumes(num_elem)*porosite_vol(num_elem)/(Cp_*rho_ref_);
}
void Eval_Puiss_Neutr_VDF_Elem::completer (void) [virtual]
Reimplemented from Evaluateur_Source_VDF_Elem.
Definition at line 82 of file Eval_Puiss_Neutr_VDF_Elem.cpp.
{
  Evaluateur_Source_VDF_Elem::completer();
  /*volume_tot = 0.;
    const int nb_elem = la_zone->nb_elem();
    for (int i=0;i<nb_elem;i++)
    volume_tot += volumes(i);
  */
// Cerr << "Volume total du domaine contenant les termes sources de neutronique " << volume_tot << finl;
}
void Eval_Puiss_Neutr_VDF_Elem::mettre_a_jour () [virtual]
< on met a jour le tableau de puissance
Implements Evaluateur_Source_VDF.
Definition at line 77 of file Eval_Puiss_Neutr_VDF_Elem.cpp.
References la_puissance, and puissance.
{
  puissance = la_puissance->valeurs()(0); //!< on met a jour le tableau de puissance
}
Member Data Documentation
Ref_Champ_Don Eval_Puiss_Neutr_VDF_Elem::Cp [protected]
Definition at line 55 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_champs().
double Eval_Puiss_Neutr_VDF_Elem::Cp_ [protected]
Definition at line 56 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
Nom Eval_Puiss_Neutr_VDF_Elem::fxyz [protected]
Definition at line 61 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_repartition().
Ref_Champ_Uniforme Eval_Puiss_Neutr_VDF_Elem::la_puissance [protected]
Definition at line 57 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_champs(), and mettre_a_jour().
double Eval_Puiss_Neutr_VDF_Elem::puissance [protected]
Definition at line 58 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_champs(), calculer_terme_source(), and mettre_a_jour().
DoubleTab Eval_Puiss_Neutr_VDF_Elem::rep [protected]
Definition at line 60 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_repartition(), and calculer_terme_source().
Ref_Champ_base Eval_Puiss_Neutr_VDF_Elem::rho_ref [protected]
Definition at line 53 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_champs().
double Eval_Puiss_Neutr_VDF_Elem::rho_ref_ [protected]
Definition at line 54 of file Eval_Puiss_Neutr_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
The documentation for this class was generated from the following files:
src/VDF/Sources/Evaluateurs/Eval_Puiss_Neutr_VDF_Elem.h
src/VDF/Sources/Evaluateurs/Eval_Puiss_Neutr_VDF_Elem.cpp