TRUST: Iterateur_VDF_base Class Reference
Iterateur_VDF_base Class Reference abstract
#include <Iterateur_VDF_base.h>
Public Member Functions
Iterateur_VDF_base ()
~Iterateur_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_VDF &, const Zone_Cl_VDF &, const Operateur_base &)
void associer (const Zone_dis &, const Zone_Cl_dis &, const Operateur_base &)
void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void calculer_flux_bord (const DoubleTab &) const
virtual void ajouter_contribution_autre_pb (const DoubleTab &inco, Matrice_Morse &matrice, const Cond_lim &la_cl, std::map< int, std::pair< int, int > > &) const
virtual int impr (Sortie &os) const =0
virtual void contribuer_au_second_membre (DoubleTab &) const =0
virtual void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const =0
virtual void ajouter_contribution_vitesse (const DoubleTab &, Matrice_Morse &) const =0
virtual void completer_ ()=0
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const =0
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const =0
virtual Evaluateur_VDF & evaluateur ()=0
virtual const Evaluateur_VDF & evaluateur () const =0
const Zone_VDF & zone () const
const Zone_Cl_VDF & zone_Cl () const
Type_Cl_VDF type_cl (const Cond_lim &) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Iterateur_VDF_base & self_cast (Objet_U &)
static const Iterateur_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Ref_Operateur_base op_base
Detailed Description
Definition at line 48 of file Iterateur_VDF_base.h.
Constructor & Destructor Documentation
Iterateur_VDF_base()
Iterateur_VDF_base::Iterateur_VDF_base ()
Definition at line 19 of file Iterateur_VDF_base.cpp.
~Iterateur_VDF_base()
Iterateur_VDF_base::~Iterateur_VDF_base () override
Definition at line 19 of file Iterateur_VDF_base.cpp.
Member Function Documentation
ajouter()
virtual DoubleTab & Iterateur_VDF_base::ajouter (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::ajouter().
ajouter_contribution()
virtual void Iterateur_VDF_base::ajouter_contribution (const DoubleTab & , Matrice_Morse &) const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::ajouter_contribution().
ajouter_contribution_autre_pb()
void Iterateur_VDF_base::ajouter_contribution_autre_pb (const DoubleTab & inco, Matrice_Morse & matrice, const Cond_lim & la_cl, std::map< int, std::pair< int, int > > & f2e) const virtual
Reimplemented in T_It_VDF_Elem< _TYPE_ >.
Definition at line 50 of file Iterateur_VDF_base.cpp.
{ /* ne fait rien en general */ }
Referenced by Iterateur_VDF::ajouter_contribution_autre_pb().
ajouter_contribution_vitesse()
virtual void Iterateur_VDF_base::ajouter_contribution_vitesse (const DoubleTab & , Matrice_Morse &) const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::ajouter_contribution_vitesse().
associer() [1/2]
void Iterateur_VDF_base::associer (const Zone_dis & z, const Zone_Cl_dis & zcl, const Operateur_base & op)
Definition at line 29 of file Iterateur_VDF_base.cpp.
{
  const Zone_VDF& zone_vdf=ref_cast(Zone_VDF, z.valeur());
  const Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl.valeur());
  associer(zone_vdf, zone_cl_vdf,op);
}
References associer(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
associer() [2/2]
void Iterateur_VDF_base::associer (const Zone_VDF & zone_vdf, const Zone_Cl_VDF & zone_cl_vdf, const Operateur_base & op)
Definition at line 42 of file Iterateur_VDF_base.cpp.
{
  la_zone=zone_vdf;
  la_zcl=zone_cl_vdf;
  op_base=op;
// completer_();
}
References la_zcl, la_zone, and op_base.
Referenced by associer(), and Iterateur_VDF::associer().
associer_zone_cl_dis()
void Iterateur_VDF_base::associer_zone_cl_dis (const Zone_Cl_dis_base & zcl)
Definition at line 36 of file Iterateur_VDF_base.cpp.
{
  const Zone_Cl_VDF& zone_cl_vdf=ref_cast(Zone_Cl_VDF, zcl);
  la_zcl=zone_cl_vdf;
}
References la_zcl, and ref_cast.
Referenced by Op_Conv_VDF_base::associer_zone_cl_dis().
calculer()
virtual DoubleTab & Iterateur_VDF_base::calculer (const DoubleTab & , DoubleTab &) const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::calculer().
calculer_flux_bord()
void Iterateur_VDF_base::calculer_flux_bord (const DoubleTab & inco) const virtual
Reimplemented in T_It_VDF_Elem< _TYPE_ >.
Definition at line 60 of file Iterateur_VDF_base.cpp.
{
  Cerr << que_suis_je() << " must implement calculer_flux_bord" << finl;
  assert(0);
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Op_Diff_VDF_base::calculer_flux_bord().
completer_()
virtual void Iterateur_VDF_base::completer_ () pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::completer_().
contribuer_au_second_membre()
virtual void Iterateur_VDF_base::contribuer_au_second_membre (DoubleTab &) const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::contribuer_au_second_membre().
evaluateur() [1/2]
virtual const Evaluateur_VDF & Iterateur_VDF_base::evaluateur () const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
evaluateur() [2/2]
virtual Evaluateur_VDF & Iterateur_VDF_base::evaluateur () pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::evaluateur().
get_info()
const Type_info * Iterateur_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 19 of file Iterateur_VDF_base.cpp.
impr()
virtual int Iterateur_VDF_base::impr (Sortie & os) const pure virtual
Implemented in T_It_VDF_Elem< _TYPE_ >, and T_It_VDF_Face< _TYPE_ >.
Referenced by Iterateur_VDF::impr().
info()
const Type_info * Iterateur_VDF_base::info () static
Definition at line 19 of file Iterateur_VDF_base.cpp.
printOn()
Sortie & Iterateur_VDF_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 58 of file Iterateur_VDF_base.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
readOn()
Entree & Iterateur_VDF_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Iterateur_VDF_base.cpp.
{ return s ; }
self_cast() [1/2]
const Iterateur_VDF_base & Iterateur_VDF_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Iterateur_VDF_base.cpp.
self_cast() [2/2]
Iterateur_VDF_base & Iterateur_VDF_base::self_cast (Objet_U & r) static
Definition at line 19 of file Iterateur_VDF_base.cpp.
type_cl()
Type_Cl_VDF Iterateur_VDF_base::type_cl (const Cond_lim & la_cl) const inline
Definition at line 78 of file Iterateur_VDF_base.h.
{
  Type_Cl_VDF retour=nouvelle_Cl_VDF;
  if ( sub_type(Symetrie,la_cl.valeur()) ) retour=symetrie;
  else if ( sub_type(Neumann_sortie_libre, la_cl.valeur()) ) retour=sortie_libre;
  else if ( sub_type(Dirichlet_entree_fluide, la_cl.valeur()) ) retour=entree_fluide;
  else if ( sub_type(Dirichlet_paroi_fixe, la_cl.valeur()) ) retour=paroi_fixe;
  else if ( sub_type(Dirichlet_paroi_defilante, la_cl.valeur()) ) retour=paroi_defilante;
  else if ( sub_type(Neumann_paroi_adiabatique, la_cl.valeur()) ) retour=paroi_adiabatique;
  else if ( sub_type(Neumann_paroi, la_cl.valeur()) ) retour=paroi;
  else if ( sub_type(Echange_externe_impose, la_cl.valeur()) ) retour=echange_externe_impose;
  else if ( sub_type(Echange_global_impose, la_cl.valeur()) ) retour=echange_global_impose;
  else if ( sub_type(Periodique, la_cl.valeur()) ) retour=periodique;
  return retour;
}
References echange_externe_impose, echange_global_impose, entree_fluide, nouvelle_Cl_VDF, paroi, paroi_adiabatique, paroi_defilante, paroi_fixe, periodique, sortie_libre, sub_type, symetrie, and Deriv_Cond_lim_base::valeur().
Referenced by Iterateur_VDF::type_cl().
zone()
const Zone_VDF & Iterateur_VDF_base::zone () const inline
Definition at line 68 of file Iterateur_VDF_base.h.
{ return la_zone.valeur(); }
References la_zone, and Ref_Zone_VDF::valeur().
Referenced by Iterateur_VDF::zone().
zone_Cl()
const Zone_Cl_VDF & Iterateur_VDF_base::zone_Cl () const inline
Definition at line 69 of file Iterateur_VDF_base.h.
{ return la_zcl.valeur(); }
References la_zcl, and Ref_Zone_Cl_VDF::valeur().
Referenced by Iterateur_VDF::zone_Cl().
Member Data Documentation
info_obj
const Type_info Iterateur_VDF_base::info_obj static
Definition at line 50 of file Iterateur_VDF_base.h.
la_zcl
Ref_Zone_Cl_VDF Iterateur_VDF_base::la_zcl protected
Definition at line 74 of file Iterateur_VDF_base.h.
Referenced by associer(), associer_zone_cl_dis(), T_It_VDF_Elem< _TYPE_ >::milieu(), and zone_Cl().
la_zone
Ref_Zone_VDF Iterateur_VDF_base::la_zone protected
Definition at line 73 of file Iterateur_VDF_base.h.
Referenced by associer(), T_It_VDF_Elem< _TYPE_ >::completer_(), and zone().
op_base
Ref_Operateur_base Iterateur_VDF_base::op_base protected
Definition at line 75 of file Iterateur_VDF_base.h.
Referenced by associer().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Iterateurs/Iterateur_VDF_base.h
src/VDF/Operateurs/Iterateurs/Iterateur_VDF_base.cpp