TRUST: Operateur_Statistique_tps Class Reference
Operateur_Statistique_tps Class Reference
classe Operateur_Statistique_tps
Classe generique de la hierarchie des operateurs statistiques en
en temps. Un objet Operateur_Statistique_tps peut referencer
n'importe quel objet derivant de Operateur_Statistique_tps_base.
#include <Operateur_Statistique_tps.h>
Public Member Functions
Operateur_Statistique_tps ()
~Operateur_Statistique_tps ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Operateur_Statistique_tps & operator= (const Operateur_Statistique_tps_base &)
Operateur d'affectation d'un Operateur_Statistique_tps_base dans
un Operateur_Statistique_tps.
void completer (Probleme_base &pb)
DoubleTab calculer_valeurs () const
void mettre_a_jour (double un_temps)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
double temps () const
const Integrale_tps_Champ & integrale () const
void initialiser (double val)
void fixer_tstat_deb (double t1, double t2)
void fixer_tstat_fin (double t2)
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
const Nom & localisation_post () const
virtual int completer_post_statistiques (const Domaine &dom, const int is_axi, Format_Post_base &format)
Public Member Functions inherited from Deriv_Operateur_Statistique_tps_base
~Deriv_Operateur_Statistique_tps_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Operateur_Statistique_tps_base ()
Deriv_Operateur_Statistique_tps_base (const Deriv_Operateur_Statistique_tps_base &)
const Operateur_Statistique_tps_base & valeur () const
Operateur_Statistique_tps_base & valeur ()
const Operateur_Statistique_tps_base * operator-> () const
Operateur_Statistique_tps_base * operator-> ()
const Deriv_Operateur_Statistique_tps_base & operator= (const Operateur_Statistique_tps_base &)
const Deriv_Operateur_Statistique_tps_base & operator= (const Deriv_Operateur_Statistique_tps_base &)
operator const Operateur_Statistique_tps_base & () const
operator Operateur_Statistique_tps_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Operateur_Statistique_tps & self_cast (Objet_U &)
static const Operateur_Statistique_tps & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Operateur_Statistique_tps_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Operateur_Statistique_tps_base & self_cast (Objet_U &)
static const Deriv_Operateur_Statistique_tps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Operateur_Statistique_tps_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le type et le nom de l'operateur statistique
sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Deriv_Operateur_Statistique_tps_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Operateur_Statistique_tps
Classe generique de la hierarchie des operateurs statistiques en
en temps. Un objet Operateur_Statistique_tps peut referencer
n'importe quel objet derivant de Operateur_Statistique_tps_base.
Definition at line 38 of file Operateur_Statistique_tps.h.
Constructor & Destructor Documentation
Operateur_Statistique_tps()
Operateur_Statistique_tps::Operateur_Statistique_tps ()
Definition at line 19 of file Operateur_Statistique_tps.cpp.
~Operateur_Statistique_tps()
Operateur_Statistique_tps::~Operateur_Statistique_tps ()
Definition at line 19 of file Operateur_Statistique_tps.cpp.
Member Function Documentation
calculer_valeurs()
DoubleTab Operateur_Statistique_tps::calculer_valeurs () const inline
Definition at line 50 of file Operateur_Statistique_tps.h.
  {
    return valeur().calculer_valeurs();
  };
References Operateur_Statistique_tps_base::calculer_valeurs(), and Deriv_Operateur_Statistique_tps_base::valeur().
completer()
void Operateur_Statistique_tps::completer (Probleme_base & pb) inline
Definition at line 46 of file Operateur_Statistique_tps.h.
  {
    valeur().completer(pb);
  };
References Operateur_Statistique_tps_base::completer(), and Deriv_Operateur_Statistique_tps_base::valeur().
completer_post_statistiques()
int Operateur_Statistique_tps::completer_post_statistiques (const Domaine & dom, const int is_axi, Format_Post_base & format) inline virtual
Definition at line 121 of file Operateur_Statistique_tps.h.
{
  return valeur().completer_post_statistiques(dom,is_axi,format);
}
References Operateur_Statistique_tps_base::completer_post_statistiques(), and Deriv_Operateur_Statistique_tps_base::valeur().
cree_instance()
Objet_U * Operateur_Statistique_tps::cree_instance () static
Definition at line 19 of file Operateur_Statistique_tps.cpp.
duplique()
int Operateur_Statistique_tps::duplique () const override virtual
Reimplemented from Deriv_Operateur_Statistique_tps_base.
Definition at line 19 of file Operateur_Statistique_tps.cpp.
fixer_tstat_deb()
void Operateur_Statistique_tps::fixer_tstat_deb (double t1, double t2) inline
Definition at line 74 of file Operateur_Statistique_tps.h.
  {
    valeur().fixer_tstat_deb(t1,t2);
  };
References Operateur_Statistique_tps_base::fixer_tstat_deb(), and Deriv_Operateur_Statistique_tps_base::valeur().
fixer_tstat_fin()
void Operateur_Statistique_tps::fixer_tstat_fin (double t2) inline
Definition at line 78 of file Operateur_Statistique_tps.h.
  {
    valeur().fixer_tstat_fin(t2);
  };
References Operateur_Statistique_tps_base::fixer_tstat_fin(), and Deriv_Operateur_Statistique_tps_base::valeur().
get_info()
const Type_info * Operateur_Statistique_tps::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Operateur_Statistique_tps_base.
Definition at line 19 of file Operateur_Statistique_tps.cpp.
info()
const Type_info * Operateur_Statistique_tps::info () static
Definition at line 19 of file Operateur_Statistique_tps.cpp.
initialiser()
void Operateur_Statistique_tps::initialiser (double val) inline
Definition at line 70 of file Operateur_Statistique_tps.h.
  {
    valeur().initialiser(val);
  };
References Operateur_Statistique_tps_base::initialiser(), and Deriv_Operateur_Statistique_tps_base::valeur().
integrale()
const Integrale_tps_Champ & Operateur_Statistique_tps::integrale () const inline
Definition at line 66 of file Operateur_Statistique_tps.h.
  {
    return valeur().integrale();
  };
References Operateur_Statistique_tps_base::integrale(), and Deriv_Operateur_Statistique_tps_base::valeur().
le_nom()
const Nom & Operateur_Statistique_tps::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 58 of file Operateur_Statistique_tps.h.
  {
    return valeur().le_nom();
  };
References Operateur_Statistique_tps_base::le_nom(), and Deriv_Operateur_Statistique_tps_base::valeur().
Referenced by printOn().
localisation_post()
const Nom & Operateur_Statistique_tps::localisation_post () const inline
Definition at line 90 of file Operateur_Statistique_tps.h.
  {
    return valeur().localisation_post();
  };
References Operateur_Statistique_tps_base::localisation_post(), and Deriv_Operateur_Statistique_tps_base::valeur().
mettre_a_jour()
void Operateur_Statistique_tps::mettre_a_jour (double un_temps) inline
Definition at line 54 of file Operateur_Statistique_tps.h.
  {
    valeur().mettre_a_jour(un_temps);
  };
References Operateur_Statistique_tps_base::mettre_a_jour(), and Deriv_Operateur_Statistique_tps_base::valeur().
operator=()
Operateur_Statistique_tps & Operateur_Statistique_tps::operator= (const Operateur_Statistique_tps_base & op_stat_base) inline
Operateur d'affectation d'un Operateur_Statistique_tps_base dans
un Operateur_Statistique_tps.
Returns
Operateur_Statistique_tps&
Signification: le resulrtat de l'affectation (*this)
Contraintes:
Definition at line 115 of file Operateur_Statistique_tps.h.
{
  DERIV(Operateur_Statistique_tps_base)::operator=(op_stat_base);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
printOn()
Sortie & Operateur_Statistique_tps::printOn (Sortie & s) const override protected virtual
Imprime le type et le nom de l'operateur statistique
sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Operateur_Statistique_tps_base.
Definition at line 38 of file Operateur_Statistique_tps.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Operateur_Statistique_tps::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Operateur_Statistique_tps_base.
Definition at line 58 of file Operateur_Statistique_tps.cpp.
{
  return s ;
}
reprendre()
int Operateur_Statistique_tps::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 86 of file Operateur_Statistique_tps.h.
  {
    return valeur().reprendre(is);
  };
References Objet_U::reprendre(), and Deriv_Operateur_Statistique_tps_base::valeur().
sauvegarder()
int Operateur_Statistique_tps::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 82 of file Operateur_Statistique_tps.h.
  {
    return valeur().sauvegarder(os);
  };
References Objet_U::sauvegarder(), and Deriv_Operateur_Statistique_tps_base::valeur().
self_cast() [1/2]
const Operateur_Statistique_tps & Operateur_Statistique_tps::self_cast (const Objet_U & r) static
Definition at line 19 of file Operateur_Statistique_tps.cpp.
self_cast() [2/2]
Operateur_Statistique_tps & Operateur_Statistique_tps::self_cast (Objet_U & r) static
Definition at line 19 of file Operateur_Statistique_tps.cpp.
taille_memoire()
unsigned Operateur_Statistique_tps::taille_memoire () const override virtual
Reimplemented from Deriv_Operateur_Statistique_tps_base.
Definition at line 19 of file Operateur_Statistique_tps.cpp.
temps()
double Operateur_Statistique_tps::temps () const inline
Definition at line 62 of file Operateur_Statistique_tps.h.
  {
    return valeur().temps();
  };
References Operateur_Statistique_tps_base::temps(), and Deriv_Operateur_Statistique_tps_base::valeur().
Member Data Documentation
info_obj
const Type_info Operateur_Statistique_tps::info_obj static
Definition at line 41 of file Operateur_Statistique_tps.h.
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Operateur_Statistique_tps.h
src/Kernel/Statistiques_temps/Operateur_Statistique_tps.cpp