TRUST: Champ_front_debit_QC_fonc_t Class Reference
Champ_front_debit_QC_fonc_t Class Reference
classe Champ_front_debit_QC_fonc_t
Classe derivee de Champ_front_base qui represente les
champs aux frontieres debit_QCs : ch(*,i)=m(i)+alea*amplitude(i)
ou alea est une variable aleatoire de loi uniforme sur [0,1]
#include <Champ_front_debit_QC_fonc_t.h>
Public Member Functions
Champ_front_debit_QC_fonc_t ()
~Champ_front_debit_QC_fonc_t ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Pas code !!
void mettre_a_jour (double temps) override
Mise a jour du temps
et retirage aleatoire des valeurs du bruit.
virtual double valeur_au_temps (double temps, int som, int comp) const
Public Member Functions inherited from Ch_front_var_instationnaire_indep
Ch_front_var_instationnaire_indep ()
~Ch_front_var_instationnaire_indep () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_debit_QC_fonc_t & self_cast (Objet_U &)
static const Champ_front_debit_QC_fonc_t & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_indep
static const Type_info * info ()
static Ch_front_var_instationnaire_indep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_indep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_indep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
Entree & readOn (Entree &) override
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int ismoyen
Ref_Fluide_Quasi_Compressible fluide
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Private Attributes
Vect_Parser_U f_debit_t
Detailed Description
classe Champ_front_debit_QC_fonc_t
Classe derivee de Champ_front_base qui represente les
champs aux frontieres debit_QCs : ch(*,i)=m(i)+alea*amplitude(i)
ou alea est une variable aleatoire de loi uniforme sur [0,1]
Definition at line 35 of file Champ_front_debit_QC_fonc_t.h.
Constructor & Destructor Documentation
Champ_front_debit_QC_fonc_t()
Champ_front_debit_QC_fonc_t::Champ_front_debit_QC_fonc_t ()
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
~Champ_front_debit_QC_fonc_t()
Champ_front_debit_QC_fonc_t::~Champ_front_debit_QC_fonc_t ()
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
Member Function Documentation
affecter_()
Champ_front_base & Champ_front_debit_QC_fonc_t::affecter_ (const Champ_front_base & ch) override virtual
Pas code !!
Returns
Champ_front_base&
Signification:
Contraintes:
Implements Champ_front_base.
Definition at line 145 of file Champ_front_debit_QC_fonc_t.cpp.
{
  return *this;
}
cree_instance()
Objet_U * Champ_front_debit_QC_fonc_t::cree_instance () static
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
duplique()
int Champ_front_debit_QC_fonc_t::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
get_info()
const Type_info * Champ_front_debit_QC_fonc_t::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
info()
const Type_info * Champ_front_debit_QC_fonc_t::info () static
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
mettre_a_jour()
void Champ_front_debit_QC_fonc_t::mettre_a_jour (double temps) override virtual
Mise a jour du temps
et retirage aleatoire des valeurs du bruit.
Reimplemented from Champ_front_base.
Definition at line 165 of file Champ_front_debit_QC_fonc_t.cpp.
{
  const Frontiere& front=la_frontiere_dis->frontiere();
  int nb_faces=front.nb_faces();
  DoubleTab& tab=valeurs();
  DoubleTab& Debit=valeurs_au_temps(tps);
  int dim=nb_comp();
  const Zone_VDF& la_zone_VDF = ref_cast(Zone_VDF,zone_dis());
  const IntTab& face_voisins=la_zone_VDF.face_voisins();
  const Front_VF& front_vf=ref_cast(Front_VF,la_frontiere_dis.valeur());
  int ndeb = front_vf.num_premiere_face();
  int nfin = ndeb + nb_faces;
  const DoubleTab& tab_rhonp1P0 =fluide.valeur().loi_etat()->rho_np1();
  if (ismoyen==0)
    for (int num_face=ndeb; num_face<nfin; num_face++)
      {
        int n0 = face_voisins(num_face, 0);
        if (n0 == -1)
          n0 = face_voisins(num_face, 1);
        for (int ori=0; ori<dim; ori++)
          {
            f_debit_t[ori].setVar("t",tps);
            Debit(num_face-ndeb,ori)=f_debit_t[ori].eval();
            tab(num_face-ndeb,ori)=Debit(num_face-ndeb,ori)/tab_rhonp1P0(n0);
          }
      }
  else
    {
      int num_face;
      double rho_moy=0,S=0,s;
      const DoubleVect& surface=la_zone_VDF.face_surfaces();
      for ( num_face=ndeb; num_face<nfin; num_face++)
        {
          int n0 = face_voisins(num_face, 0);
          if (n0 == -1)
            n0 = face_voisins(num_face, 1);
          s=surface(num_face);
          S+=s;
          rho_moy+=s*tab_rhonp1P0(n0);
        }
      S = mp_sum(S);
      rho_moy = mp_sum(rho_moy);
      rho_moy/=S;
      for ( num_face=ndeb; num_face<nfin; num_face++)
        for (int ori=0; ori<dim; ori++)
          {
            f_debit_t[ori].setVar("t",tps);
            Debit(num_face-ndeb,ori)=f_debit_t[ori].eval();
            tab(num_face-ndeb,ori)=Debit(num_face-ndeb,ori)/rho_moy;
          }
    }
}
References f_debit_t, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), fluide, Frontiere_dis_base::frontiere(), ismoyen, Champ_front_base::la_frontiere_dis, Fluide_Dilatable_base::loi_etat(), Process::mp_sum(), Field_base::nb_comp(), Frontiere::nb_faces(), Front_VF::num_premiere_face(), ref_cast, Ref_Frontiere_dis_base::valeur(), Ref_Fluide_Quasi_Compressible::valeur(), Champ_front_base::valeurs(), Champ_front_var_instationnaire::valeurs_au_temps(), and Champ_front_base::zone_dis().
printOn()
Sortie & Champ_front_debit_QC_fonc_t::printOn (Sortie & os) const override protected virtual
Impression sur un flot de sortie au format:
taille
valeur(0) ... valeur(i) ... valeur(taille-1)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 49 of file Champ_front_debit_QC_fonc_t.cpp.
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
References TRUSTVect< _TYPE_ >::size(), and Champ_front_base::valeurs().
readOn()
Entree & Champ_front_debit_QC_fonc_t::readOn (Entree & is) override protected virtual
Lecture a partir d'un flot d'entree au format:
nombre_de_composantes
moyenne moyenne(0) ... moyenne(nombre_de_composantes-1)
moyenne amplitude(0) ... amplitude(nombre_de_composantes-1)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 77 of file Champ_front_debit_QC_fonc_t.cpp.
{
  Cerr<<"Champ_front_debit_QC_VDF_fonc_t usage : dim { val1 .. valdim } [ moyen ] nom_pb"<<finl;
  ismoyen=0;
  int dim;
  is >> dim;
  Motcle motlu;
  Motcles les_mots(2);
  les_mots[0]="{";
  les_mots[1]="}";
  is >> motlu;
  if (motlu != les_mots[0])
    {
      Cerr << "Erreur a la lecture d'un Champ_front_debit_QC_VDF_fonc_t" << finl;
      Cerr << "On attendait { a la place de " << motlu << finl;
      exit();
    }
  fixer_nb_comp(dim);
  f_debit_t.dimensionner(dim);
  for (int i = 0; i<dim; i++)
    {
      Nom tmp;
      is >> tmp;
      Cerr << "Reading and interpretation of the function " << tmp << finl;
      f_debit_t[i].setNbVar(1);
      f_debit_t[i].setString(tmp);
      f_debit_t[i].addVar("t");
      f_debit_t[i].parseString();
      Cerr << "Interpretation of function " << tmp << " Ok" << finl;
    }
  is >> motlu;
  if (motlu != les_mots[1])
    {
      Cerr << "Erreur a la lecture d'un Champ_front_debit_QC_VDF_fonc_t" << finl;
      Cerr << "On attendait } a la place de " << finl;
      exit();
    }
  Nom nom_pb;
  is>>nom_pb;
  Motcle nom;
  nom=nom_pb;
  if (nom=="moyen")
    {
      ismoyen=1;
      is >> nom_pb;
    }
  Objet_U& ob1=Interprete::objet(nom_pb);
  const Probleme_base& pb=ref_cast(Probleme_base,ob1);
  fluide=ref_cast(Fluide_Quasi_Compressible,pb.equation(0).milieu());
  return is;
}
References Cerr, vect_impl::dimensionner(), Probleme_base::equation(), Process::exit(), f_debit_t, finl, Field_base::fixer_nb_comp(), fluide, ismoyen, Equation_base::milieu(), Interprete::objet(), and ref_cast.
self_cast() [1/2]
const Champ_front_debit_QC_fonc_t & Champ_front_debit_QC_fonc_t::self_cast (const Objet_U & r) static
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
self_cast() [2/2]
Champ_front_debit_QC_fonc_t & Champ_front_debit_QC_fonc_t::self_cast (Objet_U & r) static
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
taille_memoire()
unsigned Champ_front_debit_QC_fonc_t::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Champ_front_debit_QC_fonc_t.cpp.
valeur_au_temps()
double Champ_front_debit_QC_fonc_t::valeur_au_temps (double temps, int som, int comp) const virtual
Definition at line 224 of file Champ_front_debit_QC_fonc_t.cpp.
{
  Parser_U& f_debit_tk=f_debit_t[k];
  f_debit_tk.setVar("t",tps);
  return f_debit_tk.eval();
}
References Parser_U::eval(), f_debit_t, and Parser_U::setVar().
Member Data Documentation
f_debit_t
Vect_Parser_U Champ_front_debit_QC_fonc_t::f_debit_t mutable private
Definition at line 50 of file Champ_front_debit_QC_fonc_t.h.
Referenced by mettre_a_jour(), readOn(), and valeur_au_temps().
fluide
Ref_Fluide_Quasi_Compressible Champ_front_debit_QC_fonc_t::fluide protected
Definition at line 47 of file Champ_front_debit_QC_fonc_t.h.
Referenced by mettre_a_jour(), and readOn().
info_obj
const Type_info Champ_front_debit_QC_fonc_t::info_obj static
Definition at line 37 of file Champ_front_debit_QC_fonc_t.h.
ismoyen
int Champ_front_debit_QC_fonc_t::ismoyen protected
Definition at line 46 of file Champ_front_debit_QC_fonc_t.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Champ_front_debit_QC_fonc_t.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Champ_front_debit_QC_fonc_t.cpp