TRUST: Marqueur_Lagrange_base Class Reference
Marqueur_Lagrange_base Class Reference abstract
classe Marqueur_Lagrange_base
La classe Marqueur_Lagange_base est la classe de base des classes de marqueurs
Actuellement une seule classe instanciable derivant : Marqueur_FT
Un marqueur est destine a suivre le mouvement du fluide en integrant la trajectoire
d un ensemble de particules a partir de la vitesse (interpolee) du fluide.
-l ensemble des points suivis est attribut de Marqueur_FT car de type Maillage_FT_Disc
-le postraitement est realise sur le nombre de particules par maille (densite_particules_)
ou sur le nuage de points
-l integration est demarree a partir d un temps t_debut_integr_ fixe par l utilisateur
ou egal a t_init par defaut
#include <Marqueur_Lagrange_base.h>
Public Member Functions
~Marqueur_Lagrange_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Marqueur_Lagrange_base ()
virtual Ensemble_Lagrange_base & ensemble_points ()=0
virtual const Ensemble_Lagrange_base & ensemble_points () const =0
virtual void calculer_valeurs_champs ()=0
const double & temps_debut_integration () const
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual void mettre_a_jour (double temps)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Marqueur_Lagrange_base & self_cast (Objet_U &)
static const Marqueur_Lagrange_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Fonc densite_particules_
double t_debut_integr_
Private Attributes
Champs_compris champs_compris_
Detailed Description
classe Marqueur_Lagrange_base
La classe Marqueur_Lagange_base est la classe de base des classes de marqueurs
Actuellement une seule classe instanciable derivant : Marqueur_FT
Un marqueur est destine a suivre le mouvement du fluide en integrant la trajectoire
d un ensemble de particules a partir de la vitesse (interpolee) du fluide.
-l ensemble des points suivis est attribut de Marqueur_FT car de type Maillage_FT_Disc
-le postraitement est realise sur le nombre de particules par maille (densite_particules_)
ou sur le nuage de points
-l integration est demarree a partir d un temps t_debut_integr_ fixe par l utilisateur
ou egal a t_init par defaut
Definition at line 50 of file Marqueur_Lagrange_base.h.
Constructor & Destructor Documentation
~Marqueur_Lagrange_base()
Marqueur_Lagrange_base::~Marqueur_Lagrange_base () override
Definition at line 25 of file Marqueur_Lagrange_base.cpp.
Marqueur_Lagrange_base()
Marqueur_Lagrange_base::Marqueur_Lagrange_base ()
Definition at line 27 of file Marqueur_Lagrange_base.cpp.
{
  t_debut_integr_ = -1.;
}
References t_debut_integr_.
Member Function Documentation
calculer_valeurs_champs()
virtual void Marqueur_Lagrange_base::calculer_valeurs_champs () pure virtual
Referenced by mettre_a_jour().
creer_champ()
void Marqueur_Lagrange_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Definition at line 69 of file Marqueur_Lagrange_base.cpp.
{
}
discretiser()
void Marqueur_Lagrange_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) virtual
Definition at line 47 of file Marqueur_Lagrange_base.cpp.
{
  const Zone_dis_base& zone_dis=pb.equation(0).zone_dis();
  const Zone& zone = pb.domaine().zone(0);
  double temps = pb.schema_temps().temps_courant();
  Nom nom="densite_particules";
  Nom unite="sans_dimension";
  dis.discretiser_champ("champ_elem",zone_dis,nom,unite,1,temps,densite_particules_);
  champs_compris_.ajoute_champ(densite_particules_.valeur());
  ensemble_points().associer_zone(zone);
  if (t_debut_integr_==-1.)
    t_debut_integr_ = pb.schema_temps().temps_init();
}
References Champs_compris::ajoute_champ(), Ensemble_Lagrange_base::associer_zone(), champs_compris_, densite_particules_, Discretisation_base::discretiser_champ(), Probleme_base::domaine(), ensemble_points(), Probleme_base::equation(), Probleme_base::schema_temps(), t_debut_integr_, Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), Deriv_Champ_Fonc_base::valeur(), Domaine::zone(), and Equation_base::zone_dis().
ensemble_points() [1/2]
virtual const Ensemble_Lagrange_base & Marqueur_Lagrange_base::ensemble_points () const pure virtual
ensemble_points() [2/2]
virtual Ensemble_Lagrange_base & Marqueur_Lagrange_base::ensemble_points () pure virtual
Referenced by discretiser().
get_champ()
const Champ_base & Marqueur_Lagrange_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Definition at line 74 of file Marqueur_Lagrange_base.cpp.
{
  return champs_compris_.get_champ(nom);
}
References champs_compris_, and Champs_compris::get_champ().
get_info()
const Type_info * Marqueur_Lagrange_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Marqueur_Lagrange_base.cpp.
get_noms_champs_postraitables()
void Marqueur_Lagrange_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Definition at line 79 of file Marqueur_Lagrange_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<" Marqueur_Lagrange_base : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, and Champs_compris::liste_noms_compris().
info()
const Type_info * Marqueur_Lagrange_base::info () static
Definition at line 25 of file Marqueur_Lagrange_base.cpp.
mettre_a_jour()
void Marqueur_Lagrange_base::mettre_a_jour (double temps) virtual
Definition at line 63 of file Marqueur_Lagrange_base.cpp.
{
  calculer_valeurs_champs();
  densite_particules_.changer_temps(temps);
}
References calculer_valeurs_champs(), Champ_Fonc::changer_temps(), and densite_particules_.
printOn()
Sortie & Marqueur_Lagrange_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 32 of file Marqueur_Lagrange_base.cpp.
{
  return os;
}
readOn()
Entree & Marqueur_Lagrange_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Marqueur_Lagrange_base.cpp.
{
  return is;
}
self_cast() [1/2]
const Marqueur_Lagrange_base & Marqueur_Lagrange_base::self_cast (const Objet_U & r) static
Definition at line 25 of file Marqueur_Lagrange_base.cpp.
self_cast() [2/2]
Marqueur_Lagrange_base & Marqueur_Lagrange_base::self_cast (Objet_U & r) static
Definition at line 25 of file Marqueur_Lagrange_base.cpp.
temps_debut_integration()
const double & Marqueur_Lagrange_base::temps_debut_integration () const inline
Definition at line 82 of file Marqueur_Lagrange_base.h.
{
  return t_debut_integr_;
}
References t_debut_integr_.
Member Data Documentation
champs_compris_
Champs_compris Marqueur_Lagrange_base::champs_compris_ private
Definition at line 78 of file Marqueur_Lagrange_base.h.
Referenced by discretiser(), get_champ(), and get_noms_champs_postraitables().
densite_particules_
Champ_Fonc Marqueur_Lagrange_base::densite_particules_ protected
Definition at line 73 of file Marqueur_Lagrange_base.h.
Referenced by discretiser(), and mettre_a_jour().
info_obj
const Type_info Marqueur_Lagrange_base::info_obj static
Definition at line 52 of file Marqueur_Lagrange_base.h.
t_debut_integr_
double Marqueur_Lagrange_base::t_debut_integr_ protected
Definition at line 74 of file Marqueur_Lagrange_base.h.
Referenced by discretiser(), Marqueur_Lagrange_base(), and temps_debut_integration().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Marqueur_Lagrange_base.h
src/ThHyd/Incompressible/Marqueur_Lagrange_base.cpp