TRUST: Navier_Stokes_std Class Reference
Navier_Stokes_std Class Reference
classe Navier_Stokes_std
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide incompressible: div U = 0
On considere la masse volumique constante (egale a rho_0) sauf dans le
terme des forces de gravite (hypotheses de Boussinesq).
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho_0 + Bt(T-T0)g + autres sources/rho_0
div U = 0
avec DU/dt : derivee particulaire de la vitesse
rho_0 : masse volumique de reference
T0 : temperature de reference
Bt : coefficient de dilatabilite du fluide
g : vecteur gravite
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
Pour le traitement des cas un peu particulier : ajout de Traitement_particulier
exemple : THI, canal (CA)
#include <Navier_Stokes_std.h>
Public Member Functions
~Navier_Stokes_std ()
< For Immersed Boundary Method (IBM)
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Navier_Stokes_std ()
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_pb_base (const Probleme_base &) override
S'associe au probleme:
apelle Equation_base::associer_pb_base(const Probleme_base&)
s'associe avec les operateurs de divergence et de gradient.
void associer_fluide (const Fluide_base &)
Associe un fluide incompressible a l'equation.
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
(version const)
const Fluide_base & fluide () const
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
(version const)
Fluide_base & fluide ()
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
void associer_milieu_base (const Milieu_base &) override
Associe un mileu physique a l'equation en construisant
dynamiquement (cast) un objet de type Fluide_base
a partir de l'objet Milieu_base passe en parametre.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
Pour Navier Stokes Standard c'est 2.
int nombre_d_operateurs_tot () const override
const Operateur & operateur (int) const override
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1.
const Operateur & operateur_fonctionnel (int) const override
Operateur & operateur_fonctionnel (int) override
Operateur_Div & operateur_divergence ()
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
const Operateur_Div & operateur_divergence () const
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
(version const)
Operateur_Grad & operateur_gradient ()
Renvoie l'operateur de calcul du gradient
associe a l'equation.
const Operateur_Grad & operateur_gradient () const
Renvoie l'operateur de calcul du gradient
associe a l'equation.
(version const)
const Champ_Inc & inconnue () const override
Renvoie la vitesse (champ inconnue de l'equation)
(version const)
Champ_Inc & inconnue () override
Renvoie la vitesse (champ inconnue de l'equation)
SolveurSys & solveur_pression ()
Renvoie le solveur en pression<br>(version const)
void discretiser () override
Dicretise l'equation.
virtual void discretiser_vitesse ()
void completer () override
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique
Association d une equation de transport d interface a l ensemble
de points suivis si le fluide est marque.
Entree & lire_cond_init (Entree &) override
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
bool initTimeStep (double dt) override
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double)
et met a jour la pression.
Integration des points suivis si le fluide est marque
Mise a jour du champ postraitable correspondant.
void abortTimeStep () override
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
int impr (Sortie &os) const override
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
void dimensionner_matrice_sans_mem (Matrice_Morse &matrice) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
int sauvegarder (Sortie &) const override
Appelle Equation_base::sauvegarder(Sortie&)
et sauvegarde la pression sur un flot de sortie.
int reprendre (Entree &) override
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre()
et reprend la pression.
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
DoubleTab & corriger_derivee_expl (DoubleTab &) override
Add a specific term for Navier Stokes (-gradP(n)) if necessary.
DoubleTab & corriger_derivee_impl (DoubleTab &) override
Resolution de la pression, inconnue implicitee de Navier Stokes.
int preparer_calcul () override
cf Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Matrice & matrice_pression ()
Assembleur & assembleur_pression ()
Champ_Inc & pression ()
Renvoie le champ de pression.
Champ_Inc & grad_P ()
Renvoie le gradient de pression<br>(version const)
const Champ_Inc & grad_P () const
Champ_Inc & pression_pa ()
Champ_Inc & div ()
const Champ_Inc & pression () const
Renvoie le champ de pression.
const Champ_Inc & pression_pa () const
const Champ_Inc & div () const
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application: "Hydraulique".
virtual const Champ_Inc & vitesse () const
virtual Champ_Inc & vitesse ()
virtual void projeter ()
Calcule la solution U des equations:
| M(U-V)/dt + BtP = 0
|-BU=0
On resoud le probleme en pression: -BM-1BtP = -BV/dt
sachant que -BV represente le calcul de la divergence de V
On resoud le probleme en vitesse en appliquant le solveur
de masse au gradient de P: U=V - dt*M-1BtP.
virtual int projection_a_faire ()
virtual void sauver () const
virtual void calculer_la_pression_en_pa ()
Calcul de "la_pression_en_pa" en fonction de "la_pression".
Si le champ milieu().masse_volumique() est uniforme, on suppose que
la_pression est P* = P/rho, et on multiplie par rho. Sinon,
la_pression est deja en Pa.
Cette methode est surchargee en front-tracking.
virtual void calculer_pression_hydrostatique (Champ_base &pression_hydro) const
int verif_Cl () const override
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual const Champ_Inc & rho_la_vitesse () const
Operateur_Conv & get_terme_convectif ()
virtual void renewing_jacobians (DoubleTab &derivee)
virtual void div_ale_derivative (DoubleTrav &derivee_ale, double timestep, DoubleTab &derivee, DoubleTrav &secmemP)
virtual void update_pressure_matrix (void)
const int & get_matrice_pression_penalisee_H1 () const
const int & get_correction_matrice_pression () const
const int & get_correction_vitesse_modifie () const
const int & get_correction_pression_modifie () const
const int & get_gradient_pression_qdm_modifie () const
const int & get_i_source_pdf () const
const DoubleTab & get_champ_coeff_pdf_som () const
const int & get_correction_vitesse_projection_initiale () const
const int & get_correction_calcul_pression_initiale () const
const int & get_correction_matrice_projection_initiale () const
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Navier_Stokes_std & self_cast (Objet_U &)
static const Navier_Stokes_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Entree & readOn (Entree &) override
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
virtual void discretiser_assembleur_pression ()
Typage de l'assembleur pression. Le nom de l'assembleur
utilise est construit comme :
Assembleur_P_xxx" ou "xxx" est le nom de la discretisation.
Cette methode est virtuelle et surchargee dans le front-tracking.
Elle est appelee par Navier_Stokes_std::discretiser()
void uzawa (const DoubleTab &, const Matrice_Base &, SolveurSys &, DoubleTab &, DoubleTab &)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Fluide_base le_fluide
Champ_Inc la_vitesse
Champ_Inc la_pression
Champ_Inc divergence_U
Champ_Inc gradient_P
Champ_Inc la_pression_en_pa
Champ_Fonc la_vorticite
Champ_Fonc grad_u
Champ_Fonc critere_Q
Champ_Fonc pression_hydrostatique_
Champ_Fonc porosite_volumique
Champ_Fonc combinaison_champ
Champ_Fonc distance_paroi_globale
Champ_Fonc y_plus
Champ_Fonc Reynolds_maille
Champ_Fonc Courant_maille
Champ_Fonc Taux_cisaillement
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Operateur_Div divergence
Operateur_Grad gradient
Matrice matrice_pression_
Assembleur assembleur_pression_
SolveurSys solveur_pression_
int projection_initiale
double dt_projection
double seuil_projection
double seuil_uzawa
double max_div_U
double seuil_divU
double raison_seuil_divU
double LocalFlowRateRelativeError_
double cumulative_
Traitement_particulier_NS le_traitement_particulier
Nom chaine_champ_combi
int methode_calcul_pression_initiale_
int div_u_nul_et_non_dsurdt_divu_
int postraiter_gradient_pression_sans_masse_
int correction_matrice_projection_initiale_
int correction_calcul_pression_initiale_
int correction_vitesse_projection_initiale_
int correction_matrice_pression_
int matrice_pression_penalisee_H1_
int correction_vitesse_modifie_
int correction_pression_modifie_
int gradient_pression_qdm_modifie_
int i_source_pdf_
DoubleTab champ_coeff_pdf_som_
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Private Attributes
DoubleTab P_n
int postraitement_gradient_P_
Detailed Description
classe Navier_Stokes_std
Cette classe porte les termes de l'equation de la dynamique
pour un fluide sans modelisation de la turbulence.
On suppose l'hypothese de fluide incompressible: div U = 0
On considere la masse volumique constante (egale a rho_0) sauf dans le
terme des forces de gravite (hypotheses de Boussinesq).
Sous ces hypotheses, on utilise la forme suivante des equations de
Navier_Stokes:
DU/dt = div(terme visqueux) - gradP/rho_0 + Bt(T-T0)g + autres sources/rho_0
div U = 0
avec DU/dt : derivee particulaire de la vitesse
rho_0 : masse volumique de reference
T0 : temperature de reference
Bt : coefficient de dilatabilite du fluide
g : vecteur gravite
Rq : l'implementation de la classe permet bien sur de negliger
certains termes de l'equation (le terme visqueux, le terme
convectif, tel ou tel terme source).
L'inconnue est le champ de vitesse.
Pour le traitement des cas un peu particulier : ajout de Traitement_particulier
exemple : THI, canal (CA)
Definition at line 57 of file Navier_Stokes_std.h.
Constructor & Destructor Documentation
~Navier_Stokes_std()
Navier_Stokes_std::~Navier_Stokes_std ()
< For Immersed Boundary Method (IBM)
Definition at line 42 of file Navier_Stokes_std.cpp.
Navier_Stokes_std()
Navier_Stokes_std::Navier_Stokes_std ()
Definition at line 44 of file Navier_Stokes_std.cpp.
                                    :methode_calcul_pression_initiale_(0),div_u_nul_et_non_dsurdt_divu_(0),postraitement_gradient_P_(0)
{
  projection_initiale = 1;
  dt_projection=1.e12;
  max_div_U=1.e12;
  seuil_projection = 0.;
  seuil_uzawa = 1.e-12;
  seuil_divU = 100.;
  cumulative_=0;
  champs_compris_.ajoute_nom_compris("vorticite");
  champs_compris_.ajoute_nom_compris("critere_Q");
  champs_compris_.ajoute_nom_compris("porosite_volumique");
  champs_compris_.ajoute_nom_compris("y_plus");
  champs_compris_.ajoute_nom_compris("reynolds_maille");
  champs_compris_.ajoute_nom_compris("courant_maille");
  champs_compris_.ajoute_nom_compris("taux_cisaillement");
  champs_compris_.ajoute_nom_compris("pression_hydrostatique");
  champs_compris_.ajoute_nom_compris("gradient_vitesse");
  champs_compris_.ajoute_nom_compris("vitesse_residu");
// Default values for IBM parameters
  postraiter_gradient_pression_sans_masse_ = 0;
  correction_matrice_projection_initiale_ = 0;
  correction_calcul_pression_initiale_ = 0;
  correction_vitesse_projection_initiale_ = 1;
  correction_matrice_pression_ = 1;
  matrice_pression_penalisee_H1_ = 0;
  correction_vitesse_modifie_ = 1;
  correction_pression_modifie_ = 0;
  gradient_pression_qdm_modifie_ = 0;
}
References Champs_compris::ajoute_nom_compris(), Equation_base::champs_compris_, correction_calcul_pression_initiale_, correction_matrice_pression_, correction_matrice_projection_initiale_, correction_pression_modifie_, correction_vitesse_modifie_, correction_vitesse_projection_initiale_, cumulative_, dt_projection, gradient_pression_qdm_modifie_, matrice_pression_penalisee_H1_, max_div_U, postraiter_gradient_pression_sans_masse_, projection_initiale, seuil_divU, seuil_projection, and seuil_uzawa.
Member Function Documentation
abortTimeStep()
void Navier_Stokes_std::abortTimeStep () override virtual
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 1452 of file Navier_Stokes_std.cpp.
{
// On reprend la pression du debut du pas de temps
// Utile si on reprend le pas de temps parce que la pression a diverge (sinon tres mauvaise precision)
// et si on est en Piso (suppose pression juste au debut du pas de temps).
  pression()->valeurs()=P_n;
// pression()->valeurs()=0;
  Equation_base::abortTimeStep();
}
References Equation_base::abortTimeStep(), P_n, pression(), and Champ_Inc::valeurs().
assembler_blocs()
void Navier_Stokes_std::assembler_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
Definition at line 2098 of file Navier_Stokes_std.cpp.
{
  Equation_base::assembler_blocs(matrices, secmem, semi_impl);
  if (!discretisation().que_suis_je().debute_par("PolyMAC"))
    {
      DoubleTab tmp(secmem);
      tmp = 0.0;
      gradient.valeur().ajouter_blocs(matrices, tmp, semi_impl);
      secmem-=tmp;
    }
  else
    gradient.valeur().ajouter_blocs(matrices, secmem, semi_impl);
}
References Operateur_base::ajouter_blocs(), Equation_base::assembler_blocs(), Equation_base::discretisation(), gradient, Objet_U::que_suis_je(), and Deriv_Operateur_Grad_base::valeur().
assembleur_pression()
Assembleur & Navier_Stokes_std::assembleur_pression () inline
Definition at line 338 of file Navier_Stokes_std.h.
{
  return assembleur_pression_;
}
References assembleur_pression_.
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), initTimeStep(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), preparer_calcul(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
associer_fluide()
void Navier_Stokes_std::associer_fluide (const Fluide_base & un_fluide) inline
Associe un fluide incompressible a l'equation.
Definition at line 366 of file Navier_Stokes_std.h.
{
  le_fluide = un_fluide;
}
References le_fluide.
Referenced by associer_milieu_base().
associer_milieu_base()
void Navier_Stokes_std::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un mileu physique a l'equation en construisant
dynamiquement (cast) un objet de type Fluide_base
a partir de l'objet Milieu_base passe en parametre.
Implements Equation_base.
Definition at line 1649 of file Navier_Stokes_std.cpp.
{
  if (sub_type(Fluide_base, un_milieu))
    {
      const Fluide_base& un_fluide = ref_cast(Fluide_base,un_milieu);
      associer_fluide(un_fluide);
    }
  else
    {
      Cerr << "Error of fluid type for the method Navier_Stokes_std::associer_milieu_base" << finl;
      exit();
    }
}
References associer_fluide(), Cerr, Process::exit(), finl, ref_cast, and sub_type.
Referenced by Pb_Hydraulique::associer_milieu_base(), Pb_Hydraulique_Concentration::associer_milieu_base(), Pb_Thermohydraulique::associer_milieu_base(), Pb_Thermohydraulique_Concentration::associer_milieu_base(), and Pb_Multiphase::associer_milieu_base().
associer_pb_base()
void Navier_Stokes_std::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au probleme:
apelle Equation_base::associer_pb_base(const Probleme_base&)
s'associe avec les operateurs de divergence et de gradient.
Reimplemented from Equation_base.
Definition at line 362 of file Navier_Stokes_std.cpp.
{
  Equation_base::associer_pb_base(pb);
  divergence.associer_eqn(*this);
  gradient.associer_eqn(*this);
}
References MorEqn::associer_eqn(), Equation_base::associer_pb_base(), divergence, and gradient.
calculer_la_pression_en_pa()
void Navier_Stokes_std::calculer_la_pression_en_pa () virtual
Calcul de "la_pression_en_pa" en fonction de "la_pression".
Si le champ milieu().masse_volumique() est uniforme, on suppose que
la_pression est P* = P/rho, et on multiplie par rho. Sinon,
la_pression est deja en Pa.
Cette methode est surchargee en front-tracking.
Definition at line 1557 of file Navier_Stokes_std.cpp.
{
  DoubleTab& Pa=la_pression_en_pa.valeurs();
  DoubleTab& tab_pression=la_pression.valeurs();
  ConstDoubleTab_parts ppart(tab_pression);
  const Champ_base& rho=milieu().masse_volumique().valeur();
  if (Pa.get_md_vector() == tab_pression.get_md_vector())
    Pa = tab_pression; //Pa et tab_pression ont le meme support
  else if (Pa.get_md_vector() == ppart[0].get_md_vector())
    Pa = ppart[0]; //tab_pression a un morceau en plus
  else abort(); //euh...
// On multiplie par rho si uniforme sinon deja en Pa...
  if (sub_type(Champ_Uniforme,rho))
    Pa *= rho(0,0);
}
References Process::abort(), TRUSTVect< _TYPE_ >::get_md_vector(), la_pression, la_pression_en_pa, Milieu_base::masse_volumique(), milieu(), sub_type, Deriv_Champ_base::valeur(), and Champ_Inc::valeurs().
Referenced by mettre_a_jour(), and preparer_calcul().
calculer_pression_hydrostatique()
void Navier_Stokes_std::calculer_pression_hydrostatique (Champ_base & pression_hydro) const virtual
Definition at line 1815 of file Navier_Stokes_std.cpp.
{
// abort();
  DoubleTab& val= pression_hydro.valeurs();
  const DoubleTab& coords = zone_dis().zone().domaine().les_sommets();
  if (!milieu().a_gravite())
    {
      Cerr<<"postprocessing of presion_hydrostatique needs gravity"<<finl;
      exit();
    }
  const Champ_base& rho = milieu().masse_volumique().valeur();
  if (!sub_type(Champ_Uniforme,rho))
    {
      Cerr<<"postprocessing of presion_hydrostatique availabe only for incompressible flow"<<finl;
      exit();
    }
  const DoubleTab& gravite = milieu().gravite().valeurs();
  val=rho.valeurs()(0,0);
  const int nb_som=val.dimension(0);
  for (int som=0; som<nb_som; som++)
    {
      double gz=0;
      for (int dir=0; dir<dimension; dir++)
        gz+=coords(som,dir)*gravite(0,dir);
      val[som]*=gz;
    }
  val.echange_espace_virtuel();
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Milieu_base::gravite(), Domaine::les_sommets(), Milieu_base::masse_volumique(), milieu(), sub_type, Deriv_Champ_base::valeur(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), Zone_dis::zone(), and Equation_base::zone_dis().
Referenced by get_champ().
completer()
void Navier_Stokes_std::completer (void) override virtual
Complete l'equation base,
associe la pression a l'equation,
complete la divergence, le gradient et le solveur pression.
Ajout de 2 termes sources: l'un representant la force centrifuge
dans le cas axi-symetrique,l'autre intervenant dans la resolution
en 2D axisymetrique
Association d une equation de transport d interface a l ensemble
de points suivis si le fluide est marque.
< On initialize la distance au bord au dbut du calcul si on en a besoin, ce ne sera plus mis a jour par la suite car le maillage est fixe ; on le fait tard car il faut avoir lu les CL
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 390 of file Navier_Stokes_std.cpp.
{
  if (axi == 1)
    {
      Source t;
      Source& so=les_sources.add(t);
      Cerr << "Centrifuge force term creation for Axi case."<< finl;
      Nom type_so = "Force_Centrifuge_";
      Nom disc = discretisation().que_suis_je();
      Nom champ = inconnue()->que_suis_je();
      champ.suffix("Champ_");
      type_so+=disc;
      type_so+="_";
      type_so+=champ;
      type_so += "_Axi";
      so.typer_direct(type_so);
      so->associer_eqn(*this);
    }
  Equation_base::completer();
// On ne decline pas le residu par composantes pour la vitesse:
  initialise_residu(1);
  la_pression.associer_eqn(*this);
  la_pression->completer(la_zone_Cl_dis.valeur());
// [ABN] make sure the pressure knows the zone_Cl_dis to be able to use specific postreatment like 'gravcl'
  la_pression->associer_zone_cl_dis(la_zone_Cl_dis);
  divergence_U.associer_eqn(*this);
  gradient_P.associer_eqn(*this);
  la_pression_en_pa.associer_eqn(*this);
  la_pression_en_pa->completer(la_zone_Cl_dis.valeur());
  la_pression_en_pa->associer_zone_cl_dis(la_zone_Cl_dis);
  divergence.completer();
  gradient.completer();
  assembleur_pression_.associer_zone_cl_dis_base(zone_Cl_dis().valeur());
  assembleur_pression_.completer(*this);
  if (distance_paroi_globale.non_nul())//!< On initialize la distance au bord au dbut du calcul si on en a besoin, ce ne sera plus mis a jour par la suite car le maillage est fixe ; on le fait tard car il faut avoir lu les CL
    {
      Zone_dis_base& zone = zone_dis().valeur();
      zone.init_dist_paroi_globale(zone_Cl_dis().les_conditions_limites());
      Cerr << "Initializing distance_paroi_globale ... " << finl;
      const DoubleTab& dist_calc = zone.y_elem();
      for (int e = 0 ; e < zone.nb_elem() ; e++) distance_paroi_globale->valeurs()(e, 0) = dist_calc(e);
      distance_paroi_globale->valeurs().echange_espace_virtuel();
    }
}
References List_Source::add(), assembleur_pression_, Champ_Inc::associer_eqn(), Assembleur::associer_zone_cl_dis_base(), Objet_U::axi, Cerr, Equation_base::completer(), Operateur::completer(), Assembleur::completer(), Equation_base::discretisation(), distance_paroi_globale, divergence, divergence_U, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, gradient, gradient_P, inconnue(), Zone_dis_base::init_dist_paroi_globale(), Equation_base::initialise_residu(), la_pression, la_pression_en_pa, Equation_base::la_zone_Cl_dis, Equation_base::les_sources, Zone_dis_base::nb_elem(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Nom::suffix(), Source::typer_direct(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), valeur(), Champ_Fonc::valeurs(), Zone_dis_base::y_elem(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Navier_Stokes_Fluide_Dilatable_base::completer(), and QDM_Multiphase::completer().
corriger_derivee_expl()
DoubleTab & Navier_Stokes_std::corriger_derivee_expl (DoubleTab & derivee) override virtual
Add a specific term for Navier Stokes (-gradP(n)) if necessary.
Reimplemented from Equation_base.
Definition at line 885 of file Navier_Stokes_std.cpp.
{
  if (assembleur_pression_.valeur().get_resoudre_increment_pression())
    {
// PL: Pour ne pas calculer ce gradient, il faut
// A) postraitement_gradient_P_==0 car sinon grad contient alors M-1BtP
// B) les conditions en pression soient stationnaires (pas facile a detecter: Orlansky, P(t), gradient_pression impose...)
// En outre, cela fait des ecarts avec le schema CN iteratif
      const DoubleTab& tab_pression = la_pression.valeurs();
      DoubleTab& gradP = gradient_P.valeurs();
      gradient.calculer(tab_pression, gradP);
      derivee -= gradP;
    }
  return derivee;
}
References assembleur_pression_, Operateur_Grad::calculer(), Assembleur_base::get_resoudre_increment_pression(), gradient, gradient_P, la_pression, Deriv_Assembleur_base::valeur(), and Champ_Inc::valeurs().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star().
corriger_derivee_impl()
DoubleTab & Navier_Stokes_std::corriger_derivee_impl (DoubleTab & derivee) override virtual
Resolution de la pression, inconnue implicitee de Navier Stokes.
< Div(M-1(F - BtP))
< Div(M-1(F - BtP))
< car div =-B Correction du second membre d'apres les conditions aux limites :
< M-1 F
Reimplemented from Equation_base.
Definition at line 904 of file Navier_Stokes_std.cpp.
{
// We want to solve:
// dU/dt + M-1 Bt Cp = M-1(F - BtP)
// B dU/dt = 0
// with F explicit terms: sum(operators)+sources
// In:  derivee = M-1(F - BtP(n))
// Out: derivee = M-1(F - BtP(n+1)), P(n+1)=P(n)+Cp
// In case of ALE:
// Out: derivee = M-1(F + ALEconvectiveTerm - BtP(n+1)) = derivee_out, P(n+1)=P(n)+Cp
// Cp is calculated from the following equation:
// (BJ_{n}M-1Bt)Cp=B(J_{n}U_{n}/timestep+J_{n}derivee_out-J_{n+1}U_ALE), J-Jacobian, _{n}- at time n
  DoubleTab& tab_pression=la_pression.valeurs();
  DoubleTab& gradP=gradient_P.valeurs();
  DoubleTrav secmemP(tab_pression);
  DoubleTrav deriveeALE(derivee);
  double timestep=probleme().schema_temps().pas_de_temps();
// can be used for methods like ALE
  renewing_jacobians( derivee );
  if (div_u_nul_et_non_dsurdt_divu_)
    {
// on veut div u =0 et non d/dt (div u)=0 pour eviter de cumuler les erreurs
// cela ne marche qu'avec les schema type euler_explicite
      DoubleTab derivee2(derivee);
      const double dt=schema_temps().pas_de_temps();
      derivee2*=dt;
      derivee2+=la_vitesse.passe();
      derivee2/=dt;
      if( !sub_type(Op_Conv_ALE, terme_convectif.valeur()) ) //No ALE method
        {
          divergence.calculer(derivee2, secmemP); //!< Div(M-1(F - BtP))
        }
    }
  else
    {
      if( !sub_type(Op_Conv_ALE, terme_convectif.valeur()) ) //No ALE method
        {
          divergence.calculer(derivee, secmemP); //!< Div(M-1(F - BtP))
        }
    }
  if( !sub_type(Op_Conv_ALE, terme_convectif.valeur()) ) //No ALE method
    {
      secmemP *= -1; //!< car div =-B Correction du second membre d'apres les conditions aux limites :
//
      assembleur_pression_.modifier_secmem(secmemP);
    }
// Set print of the linear system solve according to dt_impr:
  solveur_pression_->fixer_schema_temps_limpr(schema_temps().limpr());
  const bool is_ALE = ( sub_type(Op_Conv_ALE, terme_convectif.valeur()) );
  if (assembleur_pression_.valeur().get_resoudre_increment_pression())
    {
      if( is_ALE )
        {
// we don't want to have domaine_ale object here
          div_ale_derivative( deriveeALE, timestep, derivee, secmemP );
        }
// Solve B M-1 Bt Cp = M-1(F - BtP)
      DoubleTrav Cp(tab_pression);
      solveur_pression_.resoudre_systeme(matrice_pression_.valeur(), secmemP, Cp);
// P(n+1) = P(n) + Cp
      tab_pression += Cp;
      assembleur_pression_.modifier_solution(tab_pression);
// M-1 Bt P(n+1)
      solveur_masse.appliquer(gradP);
      derivee += gradP; //!< M-1 F
    }
  else
    {
// Solve B M-1 Bt P(n+1) = B M-1 F
      solveur_pression_.resoudre_systeme(matrice_pression_.valeur(), secmemP, tab_pression);
      assembleur_pression_.modifier_solution(tab_pression);
// It is not done anymore cause:
// Iterative solvers are less accurate
// Time converges in O(sqrt(dt)) and not O(dt)
// See: http://www.sciencedirect.com/science/article/pii/S0021999108004518
    }
// (BM) gradient operator requires updated virtual space in source vector
// Calculate Bt P(n+1)
  tab_pression.echange_espace_virtuel();
  gradient.calculer(tab_pression, gradP);
// gradP = Bt P(n+1) is kept and
// M-1Bt P(n+1) is calculated:
  DoubleTrav Mmoins1gradP(gradP);
  Mmoins1gradP = gradP;
  solveur_masse.appliquer(Mmoins1gradP);
// dU/dt = M-1(F-Bt P(n+1))
  derivee -= Mmoins1gradP;
  return derivee;
}
References Solveur_Masse::appliquer(), assembleur_pression_, Operateur_Div::calculer(), Operateur_Grad::calculer(), div_ale_derivative(), div_u_nul_et_non_dsurdt_divu_, divergence, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Assembleur_base::get_resoudre_increment_pression(), gradient, gradient_P, la_pression, la_vitesse, Equation_base::limpr(), matrice_pression_, Assembleur::modifier_secmem(), Assembleur::modifier_solution(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), Equation_base::probleme(), renewing_jacobians(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Probleme_base::schema_temps(), Equation_base::solveur_masse, solveur_pression_, sub_type, terme_convectif, Deriv_Assembleur_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_Operateur_Conv_base::valeur(), and Champ_Inc::valeurs().
cree_instance()
Objet_U * Navier_Stokes_std::cree_instance () static
Definition at line 42 of file Navier_Stokes_std.cpp.
creer_champ()
void Navier_Stokes_std::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 1714 of file Navier_Stokes_std.cpp.
{
  Equation_base::creer_champ(motlu);
  if (motlu == "vorticite")
    {
      if (!la_vorticite.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.creer_champ_vorticite(schema_temps(),la_vitesse,la_vorticite);
          champs_compris_.ajoute_champ(la_vorticite);
        }
    }
  else if (motlu == "critere_Q")
    {
      if (!critere_Q.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
          dis.critere_Q(zone_dis(),zone_Cl_dis(),la_vitesse,critere_Q);
          champs_compris_.ajoute_champ(critere_Q);
        }
    }
  else if (motlu == "porosite_volumique")
    {
      if (!porosite_volumique.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
          dis.porosite_volumique(zone_dis(),schema_temps(),porosite_volumique);
          champs_compris_.ajoute_champ(porosite_volumique);
        }
    }
  else if (motlu == "y_plus")
    {
      if (!y_plus.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.y_plus(zone_dis(),zone_Cl_dis(),la_vitesse,y_plus);
          champs_compris_.ajoute_champ(y_plus);
        }
    }
  else if (motlu == "distance_paroi_globale")
    {
      if (!distance_paroi_globale.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.distance_paroi_globale(schema_temps(), zone_dis(), distance_paroi_globale);
          champs_compris_.ajoute_champ(distance_paroi_globale);
        }
    }
  else if (motlu == "reynolds_maille")
    {
      if (!Reynolds_maille.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.reynolds_maille(zone_dis(),fluide(),la_vitesse,Reynolds_maille);
          champs_compris_.ajoute_champ(Reynolds_maille);
        }
    }
  else if (motlu == "courant_maille")
    {
      if (!Courant_maille.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.courant_maille(zone_dis(),schema_temps(),la_vitesse,Courant_maille);
          champs_compris_.ajoute_champ(Courant_maille);
        }
    }
  else if (motlu == "taux_cisaillement")
    {
      if (!Taux_cisaillement.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.taux_cisaillement(zone_dis(),zone_Cl_dis(),la_vitesse,Taux_cisaillement);
          champs_compris_.ajoute_champ(Taux_cisaillement);
        }
    }
  else if (motlu == "pression_hydrostatique")
    {
      if (!pression_hydrostatique_.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd,discretisation());
          dis.discretiser_champ("Champ_sommets",zone_dis(),"pression_hydrostatique","Pa",1,0.,pression_hydrostatique_);
          champs_compris_.ajoute_champ(pression_hydrostatique_);
        }
    }
  else if (motlu == "gradient_vitesse")
    {
      if (!grad_u.non_nul())
        {
          const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
          dis.grad_u(zone_dis(),zone_Cl_dis(),la_vitesse,grad_u);
          champs_compris_.ajoute_champ(grad_u);
        }
    }
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier->creer_champ(motlu);
}
References Champs_compris::ajoute_champ(), Equation_base::champs_compris_, Discret_Thyd::courant_maille(), Courant_maille, Equation_base::creer_champ(), Discret_Thyd::creer_champ_vorticite(), Discret_Thyd::critere_Q(), critere_Q, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Discret_Thyd::distance_paroi_globale(), distance_paroi_globale, fluide(), Discret_Thyd::grad_u(), grad_u, la_vitesse, la_vorticite, le_traitement_particulier, O_U_Ptr::non_nul(), Discret_Thyd::porosite_volumique(), porosite_volumique, pression_hydrostatique_, ref_cast, Discret_Thyd::reynolds_maille(), Reynolds_maille, Equation_base::schema_temps(), Discret_Thyd::taux_cisaillement(), Taux_cisaillement, Discret_Thyd::y_plus(), y_plus, Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by QDM_Multiphase::creer_champ().
derivee_en_temps_inco()
DoubleTab & Navier_Stokes_std::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
< Change secmem for some schemes (eg: Adams_Bashforth)
< Add specific term for an equation (eg: -gradP for Navier Stokes)
< M-1 * secmem
< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
Reimplemented from Equation_base.
Definition at line 2112 of file Navier_Stokes_std.cpp.
{
// Calcul de la derivee en temps:
  if(!implicite_)
    {
// Calcul explicite, on utilise la derivee en temps standard:
      return Equation_base::derivee_en_temps_inco(derivee);
    }
  else
    {
// Calcul implicite d'un ou plusieurs operateurs (peu utilise)
// Syntaxe jeu de donnees: operateur { implicite solveur cholesky|gcp ... }
      derivee = 0;
      for(int i=0; i<nombre_d_operateurs(); i++)
        operateur(i).ajouter(derivee);
      les_sources.ajouter(derivee);
      derivee.echange_espace_virtuel();
      const double dt=schema_temps().pas_de_temps();
      static double dt_old=dt;
      for(int i=0; i<nombre_d_operateurs(); i++)
        {
          Operateur_base& op=operateur(i).l_op_base();
// If matrix not build or matrix time dependant:
          if(!op.get_matrice().non_nul() || !sys_invariant_)
            construire_matrice_implicite(op, inconnue().valeurs(), solv_masse(), dt);
          if(op.get_decal_temps()==1)
            {
              if(sys_invariant_ && dt!=dt_old)
                {
// La matrice ne change pas mais on change le pas de temps.
// La matrice s'ecrit A =
// Mise a jour simplifiee de la matrice
                  Matrice_Morse& matrice=ref_cast(Matrice_Morse, op.set_matrice().valeur());
                  matrice/=dt_old;
                  solv_masse().ajouter_masse(-dt_old, op.set_matrice().valeur());
                  solv_masse().ajouter_masse(dt, op.set_matrice().valeur());
                  matrice*=dt;
                  ref_cast_non_const(SolveurSys_base,op.get_solveur().valeur()).reinit();
                }
              Matrice_Morse& matrice=ref_cast(Matrice_Morse, op.set_matrice().valeur());
              if(implicite_==1)
                {
// Un seul operateur implicite.
                  DoubleTrav secmem(derivee);
                  secmem=derivee;
                  DoubleTrav incre_pre(la_pression.valeurs());
                  gradient.calculer(la_pression.valeurs(),gradient_P.valeurs());
                  secmem-=gradient_P.valeurs();
                  uzawa(secmem, matrice,op.set_solveur(),derivee, incre_pre);
                  la_pression.valeurs()+=incre_pre;
                  gradient.calculer(la_pression.valeurs(),gradient_P.valeurs());
                }
              else
                {
// plusieurs operateurs implicites ...
                  Cerr << "To be developped ... " << finl;
                  exit();
                }
            }
        }
      dt_old=dt;
      return derivee;
    }
}
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::ajouter_masse(), Operateur_Grad::calculer(), Cerr, construire_matrice_implicite(), Equation_base::derivee_en_temps_inco(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Operateur_base::get_decal_temps(), Operateur_base::get_matrice(), Operateur_base::get_solveur(), gradient, gradient_P, Equation_base::implicite_, inconnue(), Operateur::l_op_base(), la_pression, Equation_base::les_sources, nombre_d_operateurs(), O_U_Ptr::non_nul(), operateur(), Schema_Temps_base::pas_de_temps(), ref_cast, ref_cast_non_const, Equation_base::schema_temps(), Operateur_base::set_matrice(), Operateur_base::set_solveur(), Equation_base::solv_masse(), Equation_base::sys_invariant_, uzawa(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), and Champ_Inc::valeurs().
diffusivite_pour_pas_de_temps()
const Champ_base & Navier_Stokes_std::diffusivite_pour_pas_de_temps () const virtual
Reimplemented in Navier_Stokes_Fluide_Dilatable_base, and QDM_Multiphase.
Definition at line 333 of file Navier_Stokes_std.cpp.
{
  return terme_diffusif.diffusivite();
}
References Operateur_Diff::diffusivite(), and terme_diffusif.
Referenced by lire_motcle_non_standard().
diffusivite_pour_transport()
const Champ_Don & Navier_Stokes_std::diffusivite_pour_transport () const virtual
Reimplemented in Navier_Stokes_Fluide_Dilatable_base, and QDM_Multiphase.
Definition at line 328 of file Navier_Stokes_std.cpp.
{
  return fluide().viscosite_cinematique();
}
References fluide(), and Fluide_base::viscosite_cinematique().
Referenced by lire_motcle_non_standard().
dimensionner_blocs()
void Navier_Stokes_std::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 2092 of file Navier_Stokes_std.cpp.
{
  Equation_base::dimensionner_blocs(matrices, semi_impl);
  gradient.valeur().dimensionner_blocs(matrices, semi_impl);
}
References Equation_base::dimensionner_blocs(), Operateur_base::dimensionner_blocs(), gradient, and Deriv_Operateur_Grad_base::valeur().
Referenced by QDM_Multiphase::dimensionner_blocs(), and Solveur_U_P::iterer_NS().
dimensionner_matrice_sans_mem()
void Navier_Stokes_std::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 2079 of file Navier_Stokes_std.cpp.
{
  Equation_base::dimensionner_matrice_sans_mem(matrice);
  if (gradient.valeur().has_interface_blocs())
    gradient.valeur().dimensionner_blocs({{ "vitesse", &matrice }});
}
References Operateur_base::dimensionner_blocs(), Equation_base::dimensionner_matrice_sans_mem(), gradient, Operateur_base::has_interface_blocs(), and Deriv_Operateur_Grad_base::valeur().
Referenced by QDM_Multiphase::dimensionner_matrice_sans_mem().
discretiser()
void Navier_Stokes_std::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Equation_base.
Definition at line 460 of file Navier_Stokes_std.cpp.
{
  Cerr << "Hydraulic equation discretization (Navier_Stokes_std::discretiser)" << finl;
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  discretiser_vitesse();
  champs_compris_.ajoute_champ(la_vitesse);
  la_vitesse.valeur().add_synonymous(Nom("velocity"));
  dis.pression(schema_temps(), zone_dis(), la_pression);
  champs_compris_.ajoute_champ(la_pression);
  la_pression.valeur().add_synonymous(Nom("P_star"));
  dis.pression_en_pa(schema_temps(), zone_dis(), la_pression_en_pa);
  champs_compris_.ajoute_champ(la_pression_en_pa);
  la_pression_en_pa.valeur().add_synonymous(Nom("Pressure"));
  dis.divergence_U(schema_temps(), zone_dis(), divergence_U);
  dis.gradient_P(schema_temps(), zone_dis(), gradient_P);
  divergence.typer();
  divergence.l_op_base().associer_eqn(*this);
  gradient.typer();
  gradient.l_op_base().associer_eqn(*this);
  champs_compris_.ajoute_champ(gradient_P);
  champs_compris_.ajoute_champ(divergence_U);
// Appel a la methode virtuelle de discretisation de l'assembleur pression:
  discretiser_assembleur_pression();
  Equation_base::discretiser();
}
References Field_base::add_synonymous(), Champs_compris::ajoute_champ(), Operateur_base::associer_eqn(), Cerr, Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), discretiser_assembleur_pression(), discretiser_vitesse(), divergence, Discret_Thyd::divergence_U(), divergence_U, finl, gradient, Discret_Thyd::gradient_P(), gradient_P, Operateur_Div::l_op_base(), Operateur_Grad::l_op_base(), la_pression, la_pression_en_pa, la_vitesse, Discret_Thyd::pression(), Discret_Thyd::pression_en_pa(), ref_cast, Equation_base::schema_temps(), Operateur_Div::typer(), Operateur_Grad::typer(), Deriv_Champ_Inc_base::valeur(), and Equation_base::zone_dis().
Referenced by Navier_Stokes_Fluide_Dilatable_base::discretiser().
discretiser_assembleur_pression()
void Navier_Stokes_std::discretiser_assembleur_pression () protected virtual
Typage de l'assembleur pression. Le nom de l'assembleur
utilise est construit comme :
Assembleur_P_xxx" ou "xxx" est le nom de la discretisation.
Cette methode est virtuelle et surchargee dans le front-tracking.
Elle est appelee par Navier_Stokes_std::discretiser()
Definition at line 509 of file Navier_Stokes_std.cpp.
{
  Nom type = "Assembleur_P_";
  type += discretisation().que_suis_je();
  Cerr << "Navier_Stokes_std::discretiser_assembleur_pression : type="<< type << finl;
  assembleur_pression_.typer(type);
  assembleur_pression_.associer_zone_dis_base(zone_dis().valeur());
}
References assembleur_pression_, Assembleur::associer_zone_dis_base(), Cerr, Equation_base::discretisation(), finl, Objet_U::que_suis_je(), Deriv_::typer(), valeur(), and Equation_base::zone_dis().
Referenced by discretiser().
discretiser_vitesse()
void Navier_Stokes_std::discretiser_vitesse () virtual
Reimplemented in QDM_Multiphase.
Definition at line 497 of file Navier_Stokes_std.cpp.
{
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  dis.vitesse(schema_temps(), zone_dis(), la_vitesse);
}
References Equation_base::discretisation(), la_vitesse, ref_cast, Equation_base::schema_temps(), Discret_Thyd::vitesse(), and Equation_base::zone_dis().
Referenced by discretiser().
div() [1/2]
Champ_Inc & Navier_Stokes_std::div () inline
Definition at line 342 of file Navier_Stokes_std.h.
{
  return divergence_U;
}
References divergence_U.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
div() [2/2]
const Champ_Inc & Navier_Stokes_std::div () const inline
Definition at line 346 of file Navier_Stokes_std.h.
{
  return divergence_U;
}
References divergence_U.
div_ale_derivative()
void Navier_Stokes_std::div_ale_derivative (DoubleTrav & derivee_ale, double timestep, DoubleTab & derivee, DoubleTrav & secmemP) virtual
Definition at line 2313 of file Navier_Stokes_std.cpp.
{
// nothing to do
}
Referenced by corriger_derivee_impl().
domaine_application()
const Motcle & Navier_Stokes_std::domaine_application () const override virtual
Renvoie le nom du domaine d'application: "Hydraulique".
Returns
Motcle&
Signification: lenom representant le domaine d'application
Contraintes: toujours egal a "Hydraulique", reference constante.
Reimplemented from Equation_base.
Definition at line 2039 of file Navier_Stokes_std.cpp.
{
  static Motcle domaine = "Hydraulique";
  return domaine;
}
duplique()
int Navier_Stokes_std::duplique () const override virtual
Implements Objet_U.
Reimplemented in QDM_Multiphase.
Definition at line 42 of file Navier_Stokes_std.cpp.
fluide() [1/2]
Fluide_base & Navier_Stokes_std::fluide ()
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes:
Definition at line 830 of file Navier_Stokes_std.cpp.
{
  return le_fluide.valeur();
}
References le_fluide, and Ref_Fluide_base::valeur().
fluide() [2/2]
const Fluide_base & Navier_Stokes_std::fluide () const
Renvoie le fluide incompressible (milieu physique de l'equation)
associe a l'equation.
(version const)
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes: reference constante
Definition at line 809 of file Navier_Stokes_std.cpp.
{
  return le_fluide.valeur();
}
References le_fluide, and Ref_Fluide_base::valeur().
Referenced by creer_champ(), diffusivite_pour_transport(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), and Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson().
get_champ()
const Champ_base & Navier_Stokes_std::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Definition at line 1846 of file Navier_Stokes_std.cpp.
{
  REF(Champ_base) ref_champ;
  double temps_init = schema_temps().temps_init();
  if (nom=="gradient_pression") postraitement_gradient_P_=1;
  if (nom=="vorticite")
    {
      if (!la_vorticite.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,la_vorticite.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="critere_Q")
    {
      if (!critere_Q.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,critere_Q.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="porosite_volumique")
    {
      if (!porosite_volumique.non_nul())  throw Champs_compris_erreur();
      double temps_courant = schema_temps().temps_courant();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,porosite_volumique.valeur());
      if ((ch.temps()!=temps_courant) || (ch.temps()==temps_init))
        ch.mettre_a_jour(temps_courant);
      return champs_compris_.get_champ(nom);
    }
  if (nom=="y_plus")
    {
      if (!y_plus.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,y_plus.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="reynolds_maille")
    {
      if (!Reynolds_maille.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,Reynolds_maille.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="courant_maille")
    {
      if (!Courant_maille.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,Courant_maille.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="taux_cisaillement")
    {
      if (!Taux_cisaillement.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,Taux_cisaillement.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="gradient_vitesse")
    {
      if (!grad_u.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base, grad_u.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        ch.mettre_a_jour(la_vitesse->temps());
      return champs_compris_.get_champ(nom);
    }
  if (nom=="pression_hydrostatique")
    {
      if (!pression_hydrostatique_.non_nul())  throw Champs_compris_erreur();
      Champ_Fonc_base& ch=ref_cast_non_const(Champ_Fonc_base,pression_hydrostatique_.valeur());
      if (((ch.temps()!=la_vitesse->temps()) || (ch.temps()==temps_init)) && (la_vitesse->mon_equation_non_nul()))
        {
          calculer_pression_hydrostatique(ch);
          ch.mettre_a_jour(la_vitesse->temps());
        }
      return champs_compris_.get_champ(nom);
    }
  try
    {
      return Equation_base::get_champ(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  if (le_traitement_particulier.non_nul())
    try
      {
        return le_traitement_particulier->get_champ(nom);
      }
    catch (Champs_compris_erreur)
      {
      }
  throw Champs_compris_erreur();
  return ref_champ;
}
References calculer_pression_hydrostatique(), Equation_base::champs_compris_, Courant_maille, critere_Q, Champs_compris::get_champ(), Equation_base::get_champ(), grad_u, la_vitesse, la_vorticite, le_traitement_particulier, Champ_Fonc_base::mettre_a_jour(), O_U_Ptr::non_nul(), porosite_volumique, postraitement_gradient_P_, pression_hydrostatique_, REF, ref_cast_non_const, Reynolds_maille, Equation_base::schema_temps(), Taux_cisaillement, Champ_base::temps(), Champ_Inc::temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), Deriv_Champ_Fonc_base::valeur(), and y_plus.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Navier_Stokes_Fluide_Dilatable_base::get_champ(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), and Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star().
get_champ_coeff_pdf_som()
const DoubleTab & Navier_Stokes_std::get_champ_coeff_pdf_som () const inline
Definition at line 410 of file Navier_Stokes_std.h.
{
  return champ_coeff_pdf_som_;
}
References champ_coeff_pdf_som_.
Referenced by Piso::iterer_NS().
get_correction_calcul_pression_initiale()
const int & Navier_Stokes_std::get_correction_calcul_pression_initiale () const inline
Definition at line 420 of file Navier_Stokes_std.h.
{
  return correction_calcul_pression_initiale_;
}
References correction_calcul_pression_initiale_.
get_correction_matrice_pression()
const int & Navier_Stokes_std::get_correction_matrice_pression () const inline
Definition at line 385 of file Navier_Stokes_std.h.
{
  return correction_matrice_pression_;
}
References correction_matrice_pression_.
get_correction_matrice_projection_initiale()
const int & Navier_Stokes_std::get_correction_matrice_projection_initiale () const inline
Definition at line 425 of file Navier_Stokes_std.h.
{
  return correction_matrice_projection_initiale_;
}
References correction_matrice_projection_initiale_.
get_correction_pression_modifie()
const int & Navier_Stokes_std::get_correction_pression_modifie () const inline
Definition at line 395 of file Navier_Stokes_std.h.
{
  return correction_pression_modifie_;
}
References correction_pression_modifie_.
Referenced by Piso::iterer_NS().
get_correction_vitesse_modifie()
const int & Navier_Stokes_std::get_correction_vitesse_modifie () const inline
Definition at line 390 of file Navier_Stokes_std.h.
{
  return correction_vitesse_modifie_;
}
References correction_vitesse_modifie_.
Referenced by Piso::iterer_NS().
get_correction_vitesse_projection_initiale()
const int & Navier_Stokes_std::get_correction_vitesse_projection_initiale () const inline
Definition at line 415 of file Navier_Stokes_std.h.
{
  return correction_vitesse_projection_initiale_;
}
References correction_vitesse_projection_initiale_.
get_gradient_pression_qdm_modifie()
const int & Navier_Stokes_std::get_gradient_pression_qdm_modifie () const inline
Definition at line 400 of file Navier_Stokes_std.h.
{
  return gradient_pression_qdm_modifie_;
}
References gradient_pression_qdm_modifie_.
Referenced by Piso::iterer_NS().
get_i_source_pdf()
const int & Navier_Stokes_std::get_i_source_pdf () const inline
Definition at line 405 of file Navier_Stokes_std.h.
{
  return i_source_pdf_;
}
References i_source_pdf_.
Referenced by Piso::iterer_NS().
get_info()
const Type_info * Navier_Stokes_std::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 42 of file Navier_Stokes_std.cpp.
get_matrice_pression_penalisee_H1()
const int & Navier_Stokes_std::get_matrice_pression_penalisee_H1 () const inline
Definition at line 380 of file Navier_Stokes_std.h.
{
  return matrice_pression_penalisee_H1_;
}
References matrice_pression_penalisee_H1_.
get_noms_champs_postraitables()
void Navier_Stokes_std::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
Definition at line 1948 of file Navier_Stokes_std.cpp.
{
  Equation_base::get_noms_champs_postraitables(nom,opt);
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier->get_noms_champs_postraitables(nom,opt);
}
References Equation_base::get_noms_champs_postraitables(), le_traitement_particulier, and O_U_Ptr::non_nul().
get_terme_convectif()
Operateur_Conv & Navier_Stokes_std::get_terme_convectif () inline
Definition at line 371 of file Navier_Stokes_std.h.
{
  return terme_convectif;
}
References terme_convectif.
grad_P() [1/2]
Champ_Inc & Navier_Stokes_std::grad_P () inline
Renvoie le gradient de pression<br>(version const)
Returns
Champ_Inc&
Signification: le champ inconnue representant le gradient de pression
Contraintes: reference constante
Definition at line 289 of file Navier_Stokes_std.h.
{
  return gradient_P;
}
References gradient_P.
Referenced by Source_WC_Chaleur_VDF::compute_interpolate_gradP(), and Source_WC_Chaleur_VDF::compute_interpolate_gradP_old().
grad_P() [2/2]
const Champ_Inc & Navier_Stokes_std::grad_P () const inline
Definition at line 294 of file Navier_Stokes_std.h.
{
  return gradient_P;
}
References gradient_P.
has_interface_blocs()
int Navier_Stokes_std::has_interface_blocs () const override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 2086 of file Navier_Stokes_std.cpp.
{
  return Equation_base::has_interface_blocs() && gradient.valeur().has_interface_blocs();
}
References gradient, Equation_base::has_interface_blocs(), Operateur_base::has_interface_blocs(), and Deriv_Operateur_Grad_base::valeur().
Referenced by QDM_Multiphase::has_interface_blocs(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), and Solveur_U_P::iterer_NS().
impr()
int Navier_Stokes_std::impr (Sortie & os) const override virtual
Effectue quelques impressions sur un flot de sortie:
- maximum de div U
- terme convectif
- terme diffusif
- divergence
- gradient.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< max|sum(u.ndS)i/(vol(i)/dt)|=max|div(U)i/dt| Calculation as OpenFOAM: http://foam.sourceforge.net/docs/cpp/a04190_source.html It is relative errors (normalized by the volume/dt)
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 1975 of file Navier_Stokes_std.cpp.
{
// Affichage des bilans volumiques si on n'est pas en QC, ni en Front Tracking
  if (!probleme().is_dilatable() && probleme().que_suis_je()!="Probleme_FT_Disc_gen")
    {
      double LocalFlowRateError=mp_max_abs_vect(divergence_U.valeurs());
      os << finl;
      os << "Cell balance flow rate control for the problem " << probleme().le_nom() << " : " << finl;
      os << "Absolute value : " << LocalFlowRateError << " m"<<dimension+bidim_axi<<"/s" << finl;
      os << "Relative value : " << LocalFlowRateRelativeError_ << finl; //!< max|sum(u.ndS)i/(vol(i)/dt)|=max|div(U)i/dt| Calculation as OpenFOAM: http://foam.sourceforge.net/docs/cpp/a04190_source.html It is relative errors (normalized by the volume/dt)
//
//
      double dt = schema_temps().pas_de_temps();
      double local = LocalFlowRateError / ( probleme().domaine().zone(0).volume_total() / dt );
      double global = mp_somme_vect(divergence_U.valeurs()) / ( probleme().domaine().zone(0).volume_total() / dt );
      cumulative_ += global;
      os << "time step continuity errors : sum local = " << local << ", global = " << global << ", cumulative = " << cumulative_ << finl;
// Nouveau 1.6.1, arret si bilans de masse mauvais et seuil<1.e20
      if (local>0.01 && sub_type(solv_iteratif,solveur_pression_.valeur()))
        {
          if (ref_cast(solv_iteratif,solveur_pression_.valeur()).get_seuil()<1e10)
            {
              Cerr << "The mass balance is too bad (relative value>1%)." << finl;
              Cerr << "Please check and lower the convergence value of the pressure solver." << finl;
              exit();
            }
        }
// Since 1.6.6, warning to use PETSc Cholesky instead of an iterative method for pressure solver
      int nw=100;
      if (solveur_pression_->solveur_direct()==0 && le_schema_en_temps->nb_pas_dt()<nw && Process::nproc()<256 && la_pression.valeurs().size_array()<40000)
        {
          Cerr << finl << "********************** Advice (printed only on the first " << nw << " time steps) *********************" << finl;
          Cerr << "You should use PETSc Cholesky solver instead of an iterative method for the pressure solver." << finl;
          Cerr << "For the caracteristics of your problem, it will be faster and give a better mass flow balance." << finl;
          Cerr << "**********************************************************************************************" << finl << finl;
        }
    }
  if ((seuil_divU < 1.) && (sub_type(solv_iteratif,solveur_pression_.valeur())))
    {
      const solv_iteratif& solv_iter=ref_cast(solv_iteratif,solveur_pression_.valeur());
      os << " seuil de convergence du solveur iteratif  : " << solv_iter.get_seuil() << finl;
    }
  Equation_base::impr(os);
  divergence.impr(os);
  gradient.impr(os);
  return 1;
}
References Objet_U::bidim_axi, Cerr, cumulative_, Objet_U::dimension, divergence, divergence_U, Probleme_base::domaine(), Process::exit(), finl, solv_iteratif::get_seuil(), gradient, Equation_base::impr(), Operateur::impr(), la_pression, Probleme_base::le_nom(), Equation_base::le_schema_en_temps, LocalFlowRateRelativeError_, mp_max_abs_vect(), mp_somme_vect(), Schema_Temps_base::nb_pas_dt(), Process::nproc(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, Equation_base::schema_temps(), seuil_divU, TRUSTArray< _TYPE_ >::size_array(), solveur_pression_, sub_type, Deriv_SolveurSys_base::valeur(), Champ_Inc::valeurs(), Zone::volume_total(), and Domaine::zone().
Referenced by Navier_Stokes_Fluide_Dilatable_base::impr().
inconnue() [1/2]
const Champ_Inc & Navier_Stokes_std::inconnue () const override virtual
Renvoie la vitesse (champ inconnue de l'equation)
(version const)
Returns
Champ_Inc&
Signification: le champ inconnue representant la vitesse
Contraintes: reference constante
Implements Equation_base.
Definition at line 749 of file Navier_Stokes_std.cpp.
{
  return la_vitesse;
}
References la_vitesse.
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Champ_Ostwald_VEF::calculer_dscald(), Traitement_particulier_NS_EC::calculer_Ec(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces(), Navier_Stokes_Fluide_Dilatable_base::completer(), completer(), QDM_Multiphase::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), derivee_en_temps_inco(), Fluide_Ostwald::discretiser(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), initTimeStep(), SETS::iterer_NS(), Traitement_particulier_NS_Pression_VEF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), lire_cond_init(), QDM_Multiphase::mettre_a_jour(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), Traitement_particulier_NS_chmoy_faceperio::post_traitement_particulier(), Traitement_particulier_NS_EC::post_traitement_particulier(), Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), preparer_calcul(), Traitement_particulier_NS_chmoy_faceperio::preparer_calcul_particulier(), Traitement_particulier_NS_EC::preparer_calcul_particulier(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), Traitement_particulier_NS_canal::sauver_stat(), Traitement_particulier_NS_Profils::sauver_stat(), Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat(), Traitement_particulier_NS_canal::sauver_stat_canal(), verifier(), verifier_complet(), and Convection_Diffusion_Chaleur_QC::vitesse_pour_transport().
inconnue() [2/2]
Champ_Inc & Navier_Stokes_std::inconnue () override virtual
Renvoie la vitesse (champ inconnue de l'equation)
Returns
Champ_Inc&
Signification: le champ inconnue representant la vitesse
Contraintes:
Implements Equation_base.
Definition at line 768 of file Navier_Stokes_std.cpp.
{
  return la_vitesse;
}
References la_vitesse.
info()
const Type_info * Navier_Stokes_std::info () static
Definition at line 42 of file Navier_Stokes_std.cpp.
initTimeStep()
bool Navier_Stokes_std::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
Returns
0 en cas d'erreur, 1 sinon
Signification:
Contraintes:
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 1463 of file Navier_Stokes_std.cpp.
{
  P_n=pression()->valeurs();
// needed by ALE method and we don't want domaine_ale object in TRUST
  update_pressure_matrix( );
// Verification que dt_max est correctement fixe pour un champ
// de vitesse nul et diffusion_implicite active <=> dt_conv=INF
  const Schema_Temps_base& sch_tps = le_schema_en_temps.valeur();
  const double dt_max = sch_tps.pas_temps_max();
  const int diff_implicite = sch_tps.diffusion_implicite();
  if (diff_implicite)
    {
      const DoubleTab& tab_vitesse = inconnue().valeurs();
      int size = tab_vitesse.nb_dim()==1?1:tab_vitesse.dimension(1);
      DoubleVect max_vit;
      max_vit.resize(size);
      mp_max_abs_tab(tab_vitesse,max_vit);
      double max = mp_max_abs_vect(max_vit);
      if (!sup_strict(max,0.))
        {
          if (est_egal(dt_max,1.e30))
            {
              Cerr<<" "<<finl;
              Cerr<<" Diffusion operators are implicited and the current velocity field is null,"<<finl;
              Cerr<<" then leading to an infinite time step if dt_max is not defined." << finl;
              Cerr<<" Please, specify an appropriate dt_max value."<<finl;
              Cerr<<" WARNING : The first value of dt_max that you will specified "<<finl;
              Cerr<<" may need to be decreased if the calculation still crash."<<finl;
              exit();
            }
          else
            {
              Cerr<<" "<<finl;
              Cerr<<"==========================================================================="<<finl;
              Cerr<<" WARNING : "<<finl;
              Cerr<<" Diffusion operators are implicited and the current velocity field is null. "<<finl;
              Cerr<<" In the case the calculation crash, please try to decrease"<<finl;
              Cerr<<" the dt_max value in the time scheme block of your data set. "<<finl;
              Cerr<<"==========================================================================="<<finl;
              Cerr<<" "<<finl;
            }
        }
    }
// <IBM> Immersed Boundary Method
  double ddt = Equation_base::initTimeStep(dt);
  for (int i=1; i<=sch_tps.nb_valeurs_futures(); i++)
    if (i <= pression().nb_valeurs_temporelles())
      {
        double tps=sch_tps.temps_futur(i);
// Mise a jour du temps dans les champs de pression
        pression()->changer_temps_futur(tps,i);
        pression_pa()->changer_temps_futur(tps,i);
        pression()->futur(i)=pression()->valeurs();
        pression_pa()->futur(i)=pression_pa()->valeurs();
      }
  if (i_source_pdf_ != -1)
    {
      Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((sources())[i_source_pdf_].valeur());
      src.updateChampRho();
      src.calculer_vitesse_imposee();
      bool mat_var = src.get_matrice_pression_variable_bool_();
      if (mat_var == false) return  ddt;
      Cerr << "(IBM) Immersed Interface: update of pressure matrix coefficents."<<finl;
      champ_coeff_pdf_som_ = src.compute_coeff_matrice_pression();
      champ_coeff_pdf_som_.echange_espace_virtuel();
// Cerr<<"Min/max of coefficients: "<< mp_min_vect(champ_coeff_pdf_som_) << " " << mp_max_vect(champ_coeff_pdf_som_) <<finl;
      if ((correction_matrice_pression_==1) || (matrice_pression_penalisee_H1_==1))
        {
          Cerr<<"(IBM) Immersed Interface: update of pressure matrix."<<finl;
          DoubleTab inv_coeff(champ_coeff_pdf_som_);
          inv_coeff = 1.;
          inv_coeff *= champ_coeff_pdf_som_;
          src.multiply_coeff_volume(inv_coeff);
          inv_coeff.echange_espace_virtuel();
          assembleur_pression().valeur().assembler_mat(matrice_pression_,inv_coeff,1,1);
        }
    }
// </IBM>
  return ddt;
}
References Assembleur_base::assembler_mat(), assembleur_pression(), Source_PDF_base::calculer_vitesse_imposee(), Cerr, champ_coeff_pdf_som_, Source_PDF_base::compute_coeff_matrice_pression(), correction_matrice_pression_, Schema_Temps_base::diffusion_implicite(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), est_egal(), Process::exit(), finl, Champ_Inc::futur(), Source_PDF_base::get_matrice_pression_variable_bool_(), i_source_pdf_, inconnue(), Equation_base::initTimeStep(), Equation_base::le_schema_en_temps, matrice_pression_, matrice_pression_penalisee_H1_, mp_max_abs_tab(), mp_max_abs_vect(), Source_PDF_base::multiply_coeff_volume(), TRUSTTab< _TYPE_ >::nb_dim(), Schema_Temps_base::nb_valeurs_futures(), P_n, Schema_Temps_base::pas_temps_max(), pression(), pression_pa(), TRUSTVect< _TYPE_ >::resize(), Equation_base::sources(), sup_strict(), Schema_Temps_base::temps_futur(), update_pressure_matrix(), Source_PDF_base::updateChampRho(), Deriv_Assembleur_base::valeur(), Ref_Schema_Temps_base::valeur(), valeur(), and Champ_Inc::valeurs().
Referenced by Navier_Stokes_Fluide_Dilatable_base::initTimeStep().
lire_cond_init()
Entree & Navier_Stokes_std::lire_cond_init (Entree & is) override virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 835 of file Navier_Stokes_std.cpp.
{
  Cerr << "Reading of initial conditions\n";
  Nom nom;
  Motcle motlu;
  is >> nom;
  motlu = nom;
  if(motlu!=Motcle("{"))
    {
      Cerr << "We expected a { while reading " << que_suis_je() << finl;
      Cerr << "and not : " << nom << finl;
      exit();
    }
  Motcles compris(3);
  compris[0]="}";
  compris[1]="vitesse";
  compris[2]="pression";
  int ind = -1;
  while (ind!=0)
    {
      is >> nom;
      motlu = nom;
      ind = compris.rang(motlu);
      if (ind==1)
        {
          Champ_Don ch_init;
          is >> ch_init;
          verifie_ch_init_nb_comp(inconnue(),ch_init.nb_comp());
          inconnue()->affecter(ch_init.valeur());
        }
      else if (ind==2)
        {
          Champ_Don ch_init;
          is >> ch_init;
          verifie_ch_init_nb_comp(pression(),ch_init.nb_comp());
          pression()->affecter(ch_init.valeur());
        }
      else if (ind==-1)
        {
          Cerr << nom << " is not understood. Keywords are:" << finl;
          Cerr << compris << finl;
          exit();
        }
    }
  return is;
}
References Cerr, Process::exit(), finl, inconnue(), Champ_Don::nb_comp(), pression(), Objet_U::que_suis_je(), Motcles::rang(), Deriv_Champ_Don_base::valeur(), and Equation_base::verifie_ch_init_nb_comp().
lire_motcle_non_standard()
int Navier_Stokes_std::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 195 of file Navier_Stokes_std.cpp.
{
  if (mot=="diffusion")
    {
      Cerr << "Reading and typing of the diffusion operator : " << finl;
      terme_diffusif.associer_diffusivite(diffusivite_pour_transport());
      is >> terme_diffusif;
// le champ pour le dt_stab est le meme que celui de l'operateur
      terme_diffusif.associer_diffusivite_pour_pas_de_temps(diffusivite_pour_pas_de_temps());
      return 1;
    }
  else if (mot=="convection")
    {
      Cerr << "Reading and typing of the convection operator : " << finl;
      const Champ_base& vitesse_transportante = vitesse_pour_transport();
      terme_convectif.associer_vitesse(vitesse_transportante);
      is >> terme_convectif;
      return 1;
    }
  else if (mot=="solveur_pression")
    {
      Cerr << "Reading and typing of pressure solver : " << finl;
      is >> solveur_pression_;
      Cerr<<"Pressure solver type : "<<solveur_pression_.valeur().que_suis_je()<< finl;
      solveur_pression_.nommer("solveur_pression");
      return 1;
    }
  else if (mot=="dt_projection")
    {
      Cerr << "Reading projection time step " << finl;
      is >> dt_projection;
      is >> seuil_projection;
      return 1;
    }
  else if (mot=="Traitement_particulier")
    {
      Cerr << "Reading and typing of Traitement_particulier considered : " << finl;
      Nom type="Traitement_particulier_NS_";
      Motcle motbidon;
      Motcle accouverte = "{" , accfermee = "}" ;
      is >> motbidon;
      if (motbidon == accouverte)
        {
          Motcle le_cas;
          is >> le_cas;
          if (le_cas == accfermee)
            le_cas ="";
          else
            {
              type+= le_cas;
              type+= "_";
            }
          Nom discr=discretisation().que_suis_je();
          if (discr == "VEFPreP1B")
            discr = "VEF";
          type+=discr;
          Cerr << type << finl;
          le_traitement_particulier.typer(type);
          le_traitement_particulier.associer_eqn(*this);
          le_traitement_particulier.lire(is);
        }
      else
        {
          Cerr << "Error while reading Traitement_particulier for Navier_Stokes_standard equation";
          Cerr << "A { was expected." << finl;
          exit();
        }
      return 1;
    }
  else if (mot=="Erreur_max_DivU")
    {
      Cerr << "Reading DivU maximun" << finl;
      is >> max_div_U;
      is >> seuil_projection;
      return 1;
    }
  else if (mot=="seuil_divU")
    {
      Cerr << "Reading the threshold value for the velocity divergence " << finl;
      is >> seuil_divU;
      is >> raison_seuil_divU;
      return 1;
    }
  else if (mot=="solveur_bar")
    {
      Motcle motlu;
      Motcle accouverte = "{" , accfermee = "}" ;
      Nom type_solv("");
      int acc=0;
      int ok=0;
      while (acc!=0 || !ok)
        {
          is >> motlu;
          if (motlu==accouverte)
            {
              ok=1;
              acc++;
            };
          if (motlu==accfermee) acc--;
          type_solv+=" ";
          type_solv+=motlu;
        }
      if (je_suis_maitre())
        {
          SFichier s("solveur.bar");
          s<<type_solv<<finl;
          s.close();
        }
      return 1;
    }
  else if (mot=="methode_calcul_pression_initiale")
    {
      Motcle methode;
      is >> methode;
      Motcles compris(4);
      compris[0]="avec_les_cl";
      compris[1]="avec_sources";
      compris[2]="avec_sources_et_operateurs";
      compris[3]="sans_rien";
      methode_calcul_pression_initiale_=compris.rang(methode);
      if (methode_calcul_pression_initiale_<0)
        {
          Cerr<<methode<<" is not understood."<<finl;
          Cerr<<" Allowed keywords are :"<<compris<<finl;
          exit();
        }
      return 1;
    }
  else
    return Equation_base::lire_motcle_non_standard(mot,is);
  return 1;
}
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Traitement_particulier_NS::associer_eqn(), Operateur_Conv::associer_vitesse(), Cerr, Sortie_Fichier_base::close(), diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Equation_base::discretisation(), dt_projection, Process::exit(), finl, Process::je_suis_maitre(), le_traitement_particulier, Traitement_particulier_NS::lire(), Equation_base::lire_motcle_non_standard(), max_div_U, methode_calcul_pression_initiale_, SolveurSys::nommer(), Objet_U::que_suis_je(), raison_seuil_divU, Motcles::rang(), seuil_divU, seuil_projection, solveur_pression_, terme_convectif, terme_diffusif, Deriv_::typer(), Deriv_SolveurSys_base::valeur(), and vitesse_pour_transport().
Referenced by QDM_Multiphase::lire_motcle_non_standard().
matrice_pression()
Matrice & Navier_Stokes_std::matrice_pression () inline
Definition at line 333 of file Navier_Stokes_std.h.
{
  return matrice_pression_;
}
References matrice_pression_.
Referenced by Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
mettre_a_jour()
void Navier_Stokes_std::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double)
et met a jour la pression.
Integration des points suivis si le fluide est marque
Mise a jour du champ postraitable correspondant.
< array(i)=sum(u.ndS)
< array(i)=sum(u.ndS)/vol(i)
< =max|sum(u.ndS)/(vol(i)/dt)|
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 1393 of file Navier_Stokes_std.cpp.
{
// Mise a jour de la classe mere (on tourne la roue).
  Equation_base::mettre_a_jour(temps);
// Mise a jour de la pression
  la_pression.mettre_a_jour(temps);
// Update the divergence of the velocity div(U)
  divergence.calculer(la_vitesse->valeurs(),divergence_U.valeurs());
  divergence_U.mettre_a_jour(temps);
// Update the pressure field in Pascal
  calculer_la_pression_en_pa();
  la_pression_en_pa.mettre_a_jour(temps);
// Pour le postraitement, on veut M-1BtP et non BtP
  if (postraitement_gradient_P_)
    {
      gradient.calculer(la_pression.valeurs(), gradient_P.valeurs());
      if (!postraiter_gradient_pression_sans_masse_)
        {
          solveur_masse.appliquer(gradient_P.valeurs());
        }
    }
  gradient_P.mettre_a_jour(temps);
// Estimation of a flow rate relative error
  DoubleTab array(divergence_U.valeurs()); //!< array(i)=sum(u.ndS)
  divergence.volumique(array); //!< array(i)=sum(u.ndS)/vol(i)
  double dt = schema_temps().pas_de_temps();
  LocalFlowRateRelativeError_ = mp_max_abs_vect(array) * dt; //!< =max|sum(u.ndS)/(vol(i)/dt)|
// PQ : 04/03 : procedure de determination dynamique du seuil de convergence en pression
  if(sub_type(solv_iteratif,solveur_pression_.valeur()) && seuil_divU < 1.)
    {
// Calcul dynamique d'un seuil sur le solveur iteratif de pression
      solv_iteratif& solv_iter=ref_cast(solv_iteratif,solveur_pression_.valeur());
      double seuil_dyn=solv_iter.get_seuil();
      if(LocalFlowRateRelativeError_<seuil_divU)
        seuil_dyn*=raison_seuil_divU;
      else
        seuil_dyn/=raison_seuil_divU;
      double seuil_dyn_max = 1.e-10;
      seuil_dyn=std::max(seuil_dyn,seuil_dyn_max);
      solv_iter.set_seuil(seuil_dyn);
    }
// fin procedure de determination du seuil dynamique de convergence en pression
  if (projection_a_faire())
    projeter();
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier.post_traitement_particulier();
  Debog::verifier("Navier_Stokes_std::mettre_a_jour : pression",  la_pression.valeurs());
  Debog::verifier("Navier_Stokes_std::mettre_a_jour : vitesse", la_vitesse.valeurs());
}
References Solveur_Masse::appliquer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), calculer_la_pression_en_pa(), divergence, divergence_U, solv_iteratif::get_seuil(), gradient, gradient_P, la_pression, la_pression_en_pa, la_vitesse, le_traitement_particulier, LocalFlowRateRelativeError_, Champ_Inc::mettre_a_jour(), Equation_base::mettre_a_jour(), mp_max_abs_vect(), O_U_Ptr::non_nul(), Schema_Temps_base::pas_de_temps(), Traitement_particulier_NS::post_traitement_particulier(), postraitement_gradient_P_, postraiter_gradient_pression_sans_masse_, projection_a_faire(), projeter(), raison_seuil_divU, ref_cast, Equation_base::schema_temps(), solv_iteratif::set_seuil(), seuil_divU, Equation_base::solveur_masse, solveur_pression_, sub_type, Deriv_SolveurSys_base::valeur(), Champ_Inc::valeurs(), Debog::verifier(), and Operateur_Div::volumique().
milieu() [1/2]
const Milieu_base & Navier_Stokes_std::milieu () const override virtual
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
Returns
Milieu_base&
Signification: le Fluide_base de l'equation upcaste en Milieu_base
Contraintes:
Implements Equation_base.
Definition at line 1678 of file Navier_Stokes_std.cpp.
{
  if (!le_fluide.non_nul())
    {
      Cerr << "You forgot to associate a fluid to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_fluide.valeur();
}
References Cerr, Process::exit(), finl, le_fluide, Probleme_base::le_nom(), O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Fluide_base::valeur().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Traitement_particulier_NS_EC::calculer_Ec(), calculer_la_pression_en_pa(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), calculer_pression_hydrostatique(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Navier_Stokes_Fluide_Dilatable_base::get_champ(), and SETS::iterer_NS().
milieu() [2/2]
Milieu_base & Navier_Stokes_std::milieu () override virtual
Renvoie le milieu physique de l'equation<br>(le Fluide_base upcaste en Milieu_base)
(version const)
Returns
Milieu_base&
Signification: le Fluide_base de l'equation upcaste en Milieu_base
Contraintes: reference constante
Implements Equation_base.
Definition at line 1704 of file Navier_Stokes_std.cpp.
{
  if (!le_fluide.non_nul())
    {
      Cerr << "You forgot to associate a fluid to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_fluide.valeur();
}
References Cerr, Process::exit(), finl, le_fluide, Probleme_base::le_nom(), O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Fluide_base::valeur().
nombre_d_operateurs()
int Navier_Stokes_std::nombre_d_operateurs () const override virtual
Renvoie le nombre d'operateurs de l'equation:
Pour Navier Stokes Standard c'est 2.
Returns
int
Signification: le nombre d'operateur de l'equation
Contraintes: toujours egal a 2
Implements Equation_base.
Definition at line 533 of file Navier_Stokes_std.cpp.
{
  return 2;
}
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), derivee_en_temps_inco(), Source_PDF_EF::impr(), Piso::iterer_NS(), operateur(), operateur_fonctionnel(), and preparer_calcul().
nombre_d_operateurs_tot()
int Navier_Stokes_std::nombre_d_operateurs_tot () const override virtual
Reimplemented from Equation_base.
Definition at line 538 of file Navier_Stokes_std.cpp.
{
  return 4;
}
operateur() [1/2]
const Operateur & Navier_Stokes_std::operateur (int i) const override virtual
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1
(version const)
Returns
Operateur&
Signification: l'operateur indexe par i
Contraintes: reference constante
Implements Equation_base.
Definition at line 561 of file Navier_Stokes_std.cpp.
{
  switch(i)
    {
    case 0:
      return terme_diffusif;
    case 1:
      return terme_convectif;
    default :
      Cerr << "Error for Navier_Stokes_std::operateur(int i)" << finl;
      Cerr << "Navier_Stokes_std has " << nombre_d_operateurs() <<" operators "<<finl;
      Cerr << "and you are trying to access the " << i <<" th one."<< finl;
      exit();
    }
// Pour les compilos!!
  return terme_diffusif;
}
References Cerr, Process::exit(), finl, nombre_d_operateurs(), terme_convectif, and terme_diffusif.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), derivee_en_temps_inco(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), and preparer_calcul().
operateur() [2/2]
Operateur & Navier_Stokes_std::operateur (int i) override virtual
Renvoie le i-eme operateur de l'equation:
- le terme_diffusif si i = 0
- le terme_convectif si i = 1
exit si i>1.
Returns
Operateur&
Signification: l'operateur indexe par i
Contraintes:
Implements Equation_base.
Definition at line 596 of file Navier_Stokes_std.cpp.
{
  switch(i)
    {
    case 0:
      return terme_diffusif;
    case 1:
      return terme_convectif;
    default :
      Cerr << "Error for Navier_Stokes_std::operateur(int i)" << finl;
      Cerr << "Navier_Stokes_std has " << nombre_d_operateurs() <<" operators "<<finl;
      Cerr << "and you are trying to access the " << i <<" th one."<< finl;
      exit();
    }
// Pour les compilos!!
  return terme_diffusif;
}
References Cerr, Process::exit(), finl, nombre_d_operateurs(), terme_convectif, and terme_diffusif.
operateur_divergence() [1/2]
Operateur_Div & Navier_Stokes_std::operateur_divergence ()
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
Returns
Operateur_Div&
Signification: l'operateur de calcul de la divergence.
Contraintes:
Definition at line 666 of file Navier_Stokes_std.cpp.
{
  return divergence;
}
References divergence.
Referenced by Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Champ_front_pression_from_u::mettre_a_jour(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), verifier(), and verifier_complet().
operateur_divergence() [2/2]
const Operateur_Div & Navier_Stokes_std::operateur_divergence () const
Renvoie l'operateur de calcul de la divergence
associe a l'equation.
(version const)
Returns
Operateur_Div&
Signification: l'operateur de calcul de la divergence
Contraintes: reference constante
Definition at line 687 of file Navier_Stokes_std.cpp.
{
  return divergence;
}
References divergence.
operateur_fonctionnel() [1/2]
const Operateur & Navier_Stokes_std::operateur_fonctionnel (int i) const override virtual
Reimplemented from Equation_base.
Definition at line 614 of file Navier_Stokes_std.cpp.
{
  switch(i)
    {
    case 0:
      return gradient;
    case 1:
      return divergence;
    default :
      Cerr << "Error for Navier_Stokes_std::operateur_fonctionnel(int i)" << finl;
      Cerr << "Navier_Stokes_std has " << nombre_d_operateurs() <<" functional operators "<<finl;
      Cerr << "and you are trying to access the " << i <<" th one."<< finl;
      exit();
    }
// Pour les compilos!!
  return Navier_Stokes_std::operateur_fonctionnel(i);
}
References Cerr, divergence, Process::exit(), finl, gradient, nombre_d_operateurs(), and operateur_fonctionnel().
Referenced by operateur_fonctionnel().
operateur_fonctionnel() [2/2]
Operateur & Navier_Stokes_std::operateur_fonctionnel (int i) override virtual
Reimplemented from Equation_base.
Definition at line 632 of file Navier_Stokes_std.cpp.
{
  switch(i)
    {
    case 0:
      return gradient;
    case 1:
      return divergence;
    default :
      Cerr << "Error for Navier_Stokes_std::operateur_fonctionnel(int i)" << finl;
      Cerr << "Navier_Stokes_std has " << nombre_d_operateurs() <<" functional operators "<<finl;
      Cerr << "and you are trying to access the " << i <<" th one."<< finl;
      exit();
    }
// Pour les compilos!!
  return Navier_Stokes_std::operateur_fonctionnel(i);
}
References Cerr, divergence, Process::exit(), finl, gradient, nombre_d_operateurs(), and operateur_fonctionnel().
operateur_gradient() [1/2]
Operateur_Grad & Navier_Stokes_std::operateur_gradient ()
Renvoie l'operateur de calcul du gradient
associe a l'equation.
Returns
Operateur_Grad&
Signification: l'operateur de calcul du gradient
Contraintes:
Definition at line 707 of file Navier_Stokes_std.cpp.
{
  return gradient;
}
References gradient.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), verifier(), and verifier_complet().
operateur_gradient() [2/2]
const Operateur_Grad & Navier_Stokes_std::operateur_gradient () const
Renvoie l'operateur de calcul du gradient
associe a l'equation.
(version const)
Returns
Operateur_Grad&
Signification: l'operateur de calcul du gradient
Contraintes: reference constante
Definition at line 728 of file Navier_Stokes_std.cpp.
{
  return gradient;
}
References gradient.
preparer_calcul()
int Navier_Stokes_std::preparer_calcul (void) override virtual
cf Equation_base::preparer_calcul()
Assemblage du solveur pression et
initialisation de la pression.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< on remet les bons flux bords
< on remet les bons flux bords pour div
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 1168 of file Navier_Stokes_std.cpp.
{
  const double temps = schema_temps().temps_courant();
  sources().mettre_a_jour(temps);
  Equation_base::preparer_calcul();
  Nom nom_eq=que_suis_je();
  Nom nom_eq2(nom_eq);
  nom_eq2.prefix("_QC");
  if (i_source_pdf_ != -1)
    {
      Cerr<<"(IBM) Immersed Interface: compute pressure matrix coefficients."<<finl;
      Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((sources())[i_source_pdf_].valeur());
      src.updateChampRho();
// if (src.getInterpolationBool())
// {
// src.calculer_vitesse_imposee();
// }
      DoubleTab coeff;
      coeff = src.compute_coeff_matrice_pression();
      coeff.echange_espace_virtuel();
// Cerr<<"Min/max : "<< mp_min_vect(coeff) << " " << mp_max_vect(coeff) <<finl;
      champ_coeff_pdf_som_ = coeff;
      if (correction_matrice_projection_initiale_==1)
        {
          Cerr<<"(IBM) Immersed Interface: modified pressure matrix for initial projection."<<finl;
          DoubleTab inv_coeff(champ_coeff_pdf_som_);
          inv_coeff = 1. ;
          inv_coeff *= champ_coeff_pdf_som_;
          src.multiply_coeff_volume(inv_coeff);
          inv_coeff.echange_espace_virtuel();
          assembleur_pression().valeur().assembler_mat(matrice_pression_,inv_coeff,1,1);
        }
      else
        {
          if ((nom_eq2==nom_eq))
            {
              assembleur_pression_.assembler(matrice_pression_);
            }
          else
            {
              Cerr<<"Assembling for quasi-compressible"<<finl;
              assembleur_pression_.assembler_QC(le_fluide->masse_volumique().valeurs(),matrice_pression_);
            }
        }
    }
  else
    {
      if ((nom_eq2==nom_eq))
        {
          assembleur_pression_.assembler(matrice_pression_);
        }
      else
        {
          Cerr<<"Assembling for quasi-compressible"<<finl;
          assembleur_pression_.assembler_QC(le_fluide->masse_volumique().valeurs(),matrice_pression_);
        }
    }
// GF en cas de reprise on conserve la valeur de la pression
// avant elle ne servait qu' a initialiser le lagrange pour la projection
// C'est important pour le Simpler/Piso de bien repartir de la pression
// sauvegardee...
// la_pression.valeurs()=0.;
  la_pression.changer_temps(temps);
// Calcul du gradient et mise au meme temps que la pression
  gradient.calculer(la_pression.valeurs(), gradient_P.valeurs());
  gradient_P.changer_temps(temps);
  Debog::verifier("Navier_Stokes_std::preparer_calcul, la_pression av projeter", la_pression.valeurs());
  int proj_fait=0;
  if (projection_a_faire())
    {
      Cerr << "Projection of initial and boundaries conditions " << finl;
      projeter();
      proj_fait=1;
    }
  else
    {
      divergence.calculer(la_vitesse.valeurs(),divergence_U.valeurs());
      divergence_U.valeurs()=0.;  //!< on remet les bons flux bords
    }
  divergence_U.changer_temps(temps);
// Au cas ou une cl de pression depend de u que l'on vient de modifier
  la_zone_Cl_dis->mettre_a_jour(temps);
  gradient.calculer(la_pression.valeurs(), gradient_P.valeurs());
  Debog::verifier("Navier_Stokes_std::preparer_calcul, la_pression ap projeter", la_pression.valeurs());
// Initialisation du champ de pression (resolution de Laplacien(P)=0 avec les conditions limites en pression)
// Permet de demarrer la resolution avec une bonne approximation de la pression (important pour le Piso ou P!=0)
  if  (methode_calcul_pression_initiale_!=3)
    if (!probleme().reprise_effectuee())
      {
        Cout<<"Estimation du champ de pression au demarrage:" <<finl;
        DoubleTrav secmem(la_pression.valeurs());
        DoubleTrav vpoint(gradient_P.valeurs());
        vpoint-=gradient_P.valeurs();
        if ((i_source_pdf_ != -1) && ((correction_matrice_projection_initiale_==1)||(matrice_pression_penalisee_H1_==1)))
          {
// Source_PDF& src = ref_cast(Source_PDF, (sources())[i_source_pdf_].valeur());
// if (src.getInterpolationBool())
// {
// src.calculer_vitesse_imposee();
// }
            if ((i_source_pdf_ != -1)&&(((correction_matrice_projection_initiale_==1)||(matrice_pression_penalisee_H1_==1))))
              {
                Cerr<<"(IBM) Immersed Interface: modified pressure gradient for initial pressure computation."<<finl;
                vpoint/=champ_coeff_pdf_som_;
              }
          }
        if (methode_calcul_pression_initiale_>=2)
          for (int op=0; op<nombre_d_operateurs(); op++)
            operateur(op).ajouter(vpoint);
        if (methode_calcul_pression_initiale_>=1)
          {
            int mod=0;
            if (le_schema_en_temps->pas_de_temps()==0)
              {
                double dt = std::max(le_schema_en_temps->pas_temps_min(),calculer_pas_de_temps());
                dt = std::min(dt, le_schema_en_temps->pas_temps_max());
                le_schema_en_temps->set_dt()=(dt);
                mod=1;
              }
            sources().ajouter(vpoint);
// <IBM> Taking into account potential Source_PDF term for Immersed Boundary Method
            if ((i_source_pdf_ != -1) && ((correction_matrice_projection_initiale_==1)||(matrice_pression_penalisee_H1_==1)) && proj_fait)
              {
                const Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((sources())[i_source_pdf_].valeur());
                Cerr<<"Immersed Interface: Dirichlet velocity in initial pressure computation for PDF (if any)."<<finl;
                DoubleTrav secmem_pdf(vpoint);
                src.calculer_pdf(secmem_pdf);
                vpoint -= secmem_pdf;
                vpoint.echange_espace_virtuel();
              }
// </IBM>
            if (mod)
              le_schema_en_temps->set_dt()=0;
          }
        solveur_masse.appliquer(vpoint);
        vpoint.echange_espace_virtuel();
        divergence.calculer(vpoint, secmem);
        secmem*=-1;
        secmem.echange_espace_virtuel();
        assembleur_pression_->modifier_secmem_pour_incr_p(la_pression.valeurs(), 1, secmem);
        DoubleTrav inc_pre(la_pression.valeurs());
        solveur_pression_.resoudre_systeme(matrice_pression_.valeur(),secmem, inc_pre);
// <IBM> Correction of pressure for Immersed Boundary Method
        Cerr << "Pressure increment computed successfully" << finl;
        if ((i_source_pdf_ != -1) && (correction_calcul_pression_initiale_ == 1))
          {
            Cerr<<"(IBM) Immersed Interface: correction of initial pressure."<<finl;
            const Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((sources())[i_source_pdf_].valeur());
            src.correct_incr_pressure(champ_coeff_pdf_som_, inc_pre);
            inc_pre.echange_espace_virtuel();
          }
// </IBM>
// On veut que l'espace virtuel soit a jour, donc all_items
        operator_add(la_pression.valeurs(), inc_pre, VECT_ALL_ITEMS);
        gradient.calculer(la_pression.valeurs(),gradient_P.valeurs());
        divergence.calculer(la_vitesse.valeurs(),divergence_U.valeurs());
        divergence_U.valeurs()=0.;  //!< on remet les bons flux bords pour div
      }
  calculer_la_pression_en_pa();
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier.preparer_calcul_particulier();
  Debog::verifier("Navier_Stokes_std::preparer_calcul, vitesse", inconnue());
  Debog::verifier("Navier_Stokes_std::preparer_calcul, pression", la_pression);
// <IBM> Immersed Boundary Method
  if (i_source_pdf_ != -1)
    {
      DoubleTab coeff(champ_coeff_pdf_som_);
      coeff = 1.;
      if (matrice_pression_penalisee_H1_==1)
        {
          Cerr<<"(IBM) Immersed Interface: H1 penalty of pressure matrix."<<finl;
          coeff /= champ_coeff_pdf_som_;
        }
      else if (correction_matrice_pression_==1)
        {
          Cerr<<"(IBM) Immersed Interface: modification of pressure matrix."<<finl;
          coeff *= champ_coeff_pdf_som_;
// Cerr<<"Min/max of coefficients: "<< mp_min_vect(champ_coeff_pdf_som_) << " " << mp_max_vect(champ_coeff_pdf_som_) <<finl;
        }
      const Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((sources())[i_source_pdf_].valeur());
      src.multiply_coeff_volume(coeff);
      coeff.echange_espace_virtuel();
      assembleur_pression().valeur().assembler_mat(matrice_pression_,coeff,1,1);
    }
// </IBM>
  return 1;
}
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::appliquer(), Assembleur::assembler(), Assembleur_base::assembler_mat(), Assembleur::assembler_QC(), assembleur_pression(), assembleur_pression_, Operateur_Div::calculer(), Operateur_Grad::calculer(), calculer_la_pression_en_pa(), Equation_base::calculer_pas_de_temps(), Source_PDF_base::calculer_pdf(), Cerr, champ_coeff_pdf_som_, Champ_Inc::changer_temps(), coeff, Source_PDF_base::compute_coeff_matrice_pression(), Source_PDF_base::correct_incr_pressure(), correction_calcul_pression_initiale_, correction_matrice_pression_, correction_matrice_projection_initiale_, Cout, divergence, divergence_U, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, gradient, gradient_P, i_source_pdf_, inconnue(), la_pression, la_vitesse, Equation_base::la_zone_Cl_dis, le_fluide, Equation_base::le_schema_en_temps, le_traitement_particulier, Milieu_base::masse_volumique(), matrice_pression_, matrice_pression_penalisee_H1_, methode_calcul_pression_initiale_, Sources::mettre_a_jour(), Zone_Cl_dis::mettre_a_jour(), Source_PDF_base::multiply_coeff_volume(), nombre_d_operateurs(), O_U_Ptr::non_nul(), operateur(), operator_add(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_max(), Schema_Temps_base::pas_temps_min(), Nom::prefix(), Equation_base::preparer_calcul(), Traitement_particulier_NS::preparer_calcul_particulier(), Equation_base::probleme(), projection_a_faire(), projeter(), Objet_U::que_suis_je(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Schema_Temps_base::set_dt(), Equation_base::solveur_masse, solveur_pression_, Equation_base::sources(), Schema_Temps_base::temps_courant(), Source_PDF_base::updateChampRho(), Deriv_Assembleur_base::valeur(), Deriv_Matrice_Base::valeur(), valeur(), Champ::valeurs(), Champ_Inc::valeurs(), VECT_ALL_ITEMS, and Debog::verifier().
Referenced by Navier_Stokes_Fluide_Dilatable_base::preparer_calcul().
pression() [1/2]
Champ_Inc & Navier_Stokes_std::pression () inline
Renvoie le champ de pression.
Returns
Champ_Inc&
Signification: le champ inconnue representant la pression
Contraintes:
Definition at line 262 of file Navier_Stokes_std.h.
{
  return la_pression;
}
References la_pression.
Referenced by abortTimeStep(), Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Fluide_Dilatable_base::completer(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), initTimeStep(), QDM_Multiphase::initTimeStep(), Simple::iterer_eqn(), SETS::iterer_NS(), lire_cond_init(), QDM_Multiphase::mettre_a_jour(), Schema_Backward_Differentiation_base::modify_equation_parameters(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), EOS_Tools_VEF::secmembre_divU_Z(), Schema_Backward_Differentiation_base::store_equation_parameters(), Neumann_sortie_libre::verifie_ch_init_nb_comp(), verifier(), and verifier_complet().
pression() [2/2]
const Champ_Inc & Navier_Stokes_std::pression () const inline
Renvoie le champ de pression.
Returns
Champ_Inc&
Signification: le champ inconnue representant la pression
Contraintes:
Definition at line 313 of file Navier_Stokes_std.h.
{
  return la_pression;
}
References la_pression.
pression_pa() [1/2]
Champ_Inc & Navier_Stokes_std::pression_pa () inline
Definition at line 267 of file Navier_Stokes_std.h.
{
  return la_pression_en_pa;
}
References la_pression_en_pa.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), initTimeStep(), QDM_Multiphase::initTimeStep(), and QDM_Multiphase::mettre_a_jour().
pression_pa() [2/2]
const Champ_Inc & Navier_Stokes_std::pression_pa () const inline
Definition at line 318 of file Navier_Stokes_std.h.
{
  return la_pression_en_pa;
}
References la_pression_en_pa.
printOn()
Sortie & Navier_Stokes_std::printOn (Sortie & is) const override protected virtual
Simple appel a: Equation_base::printOn(Sortie&)
Ecrit l'equation sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 91 of file Navier_Stokes_std.cpp.
{
  return Equation_base::printOn(is);
}
References Equation_base::printOn().
Referenced by Navier_Stokes_Fluide_Dilatable_base::printOn().
projection_a_faire()
int Navier_Stokes_std::projection_a_faire () virtual
Definition at line 1132 of file Navier_Stokes_std.cpp.
{
// Pas de projection si l'equation n'est pas resolue
// if (equation_non_resolue()) return 0;
  double temps = le_schema_en_temps->temps_courant()+le_schema_en_temps->pas_de_temps();
// Voir Schema_Temps_base::limpr pour information sur modf
  double nb_proj_int;
  modf(temps/dt_projection, &nb_proj_int);
  static double nb_proj = nb_proj_int;
  if (projection_initiale)
    return 1;
  else if (inf_ou_egal((nb_proj+1.)*dt_projection,temps))
    {
      nb_proj=nb_proj+1.;
      return 1;
    }
  return 0;
}
References dt_projection, inf_ou_egal(), Equation_base::le_schema_en_temps, Schema_Temps_base::pas_de_temps(), projection_initiale, and Schema_Temps_base::temps_courant().
Referenced by mettre_a_jour(), and preparer_calcul().
projeter()
void Navier_Stokes_std::projeter () virtual
Calcule la solution U des equations:
| M(U-V)/dt + BtP = 0
|-BU=0
On resoud le probleme en pression: -BM-1BtP = -BV/dt
sachant que -BV represente le calcul de la divergence de V
On resoud le probleme en vitesse en appliquant le solveur
de masse au gradient de P: U=V - dt*M-1BtP.
< on remet les bons flux bords
Definition at line 1030 of file Navier_Stokes_std.cpp.
{
  if (probleme().is_dilatable() && probleme().reprise_effectuee())
    {
      Cerr<<"WARNING: Quasi compressible model --> no projection (except the first time step)."<<finl;
    }
  else
    {
      DoubleTab& tab_vitesse=la_vitesse.valeurs();
      tab_vitesse.echange_espace_virtuel();
      la_pression.valeurs().echange_espace_virtuel();
      DoubleTrav secmem(la_pression.valeurs());
// Cela ne sert a rien d'initialiser lagrange avec la pression
// voir ca penalise le calcul en p1B et CL p<>0
// On prend un DoubleTrav au lieu d'un DoubleTab pour avoir lagrange=0
      DoubleTrav lagrange(la_pression.valeurs());
      DoubleTrav gradP(gradient_P.valeurs());
      double normal_seuil=0;
// M u + eBt l = M v
// B u = 0
// => e B(M-1)Bt l = Bv
//
      if ((i_source_pdf_ != -1) && (correction_vitesse_projection_initiale_==1))
        {
          Cerr<<"(IBM) Immersed Interface: modified initial velocity for initial projection."<<finl;
          const Source_PDF_base& src = dynamic_cast<Source_PDF_base&>((sources())[i_source_pdf_].valeur());
          src.correct_vitesse(champ_coeff_pdf_som_, tab_vitesse);
          tab_vitesse.echange_espace_virtuel();
        }
      divergence.calculer(tab_vitesse, secmem);
// Desormais on calcule le pas de temps avant la projection
// Avant, on avait dt=dt_min au debut du calcul
      double dt = std::max(le_schema_en_temps->pas_temps_min(),calculer_pas_de_temps());
      dt = std::min(dt, le_schema_en_temps->pas_temps_max());
      secmem*=(-1./dt);
      secmem.echange_espace_virtuel();
      double bilan=mp_norme_vect(secmem);
      Cout << "-------------  Projection  -----------------" << finl;
      Cout << "--------------------------------------------" << finl;
      Cout << "Bilan de masse avant projection : " << bilan << finl;
      if( sub_type(solv_iteratif,solveur_pression_.valeur()) )
        {
          solv_iteratif& solv_iter=ref_cast(solv_iteratif,solveur_pression_.valeur());
          normal_seuil=solv_iter.get_seuil();
          solv_iter.set_seuil(seuil_projection);
        }
// Correction du second membre d'apres les conditions aux limites :
      solveur_pression_.resoudre_systeme(matrice_pression_.valeur(),secmem,lagrange);
      assembleur_pression_.modifier_solution(lagrange);
      lagrange.echange_espace_virtuel();
// M-1 Bt l
      gradient->multvect(lagrange, gradP);
      if ((i_source_pdf_ != -1) && (correction_vitesse_projection_initiale_==1))
        {
          Cerr<<"(IBM) Immersed Interface: modified velocity corrector for initial projection."<<finl;
          gradP /= champ_coeff_pdf_som_;
        }
      gradP.echange_espace_virtuel();
      solveur_masse.appliquer(gradP);
      gradP.echange_espace_virtuel();
      if (tab_vitesse.dimension_tot(0) == gradP.dimension_tot(0))
        tab_vitesse.ajoute(-dt,gradP);
      else
        {
          DoubleTab_parts partv(tab_vitesse);
          partv[0].ajoute(-dt,gradP);
        }
      tab_vitesse.echange_espace_virtuel();
      solveur_masse.corriger_solution(tab_vitesse, tab_vitesse);
      Debog::verifier("Navier_Stokes_std::projeter, vitesse", tab_vitesse);
// Verif ...
      divergence.calculer(tab_vitesse, secmem);
      secmem.echange_espace_virtuel();
      bilan=mp_norme_vect(secmem);
      Cout << "Bilan de masse apres projection : " << bilan << finl;
      Cout << "-------------  Projection  OK---------------" << finl;
      Cout << "--------------------------------------------" << finl;
      if( sub_type(solv_iteratif,solveur_pression_.valeur()) )
        {
          solv_iteratif& solv_iter=ref_cast(solv_iteratif,solveur_pression_.valeur());
          solv_iter.set_seuil(normal_seuil);
        }
      divergence.calculer(la_vitesse.valeurs(),divergence_U.valeurs());
      divergence_U.valeurs()=0.;  //!< on remet les bons flux bords
    }
  projection_initiale = 0;
}
References TRUSTVect< _TYPE_ >::ajoute(), Solveur_Masse::appliquer(), assembleur_pression_, Operateur_Div::calculer(), Equation_base::calculer_pas_de_temps(), Cerr, champ_coeff_pdf_som_, Source_PDF_base::correct_vitesse(), correction_vitesse_projection_initiale_, Solveur_Masse::corriger_solution(), Cout, TRUSTTab< _TYPE_ >::dimension_tot(), divergence, divergence_U, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, solv_iteratif::get_seuil(), gradient, gradient_P, i_source_pdf_, la_pression, la_vitesse, Equation_base::le_schema_en_temps, matrice_pression_, Assembleur::modifier_solution(), mp_norme_vect(), Schema_Temps_base::pas_temps_max(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), projection_initiale, ref_cast, SolveurSys::resoudre_systeme(), solv_iteratif::set_seuil(), seuil_projection, Equation_base::solveur_masse, solveur_pression_, Equation_base::sources(), sub_type, Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), valeur(), Champ_Inc::valeurs(), and Debog::verifier().
Referenced by mettre_a_jour(), and preparer_calcul().
readOn()
Entree & Navier_Stokes_std::readOn (Entree & is) override protected virtual
Appel Equation_base::readOn(Entree& is)
En sortie verifie que l'on a bien lu:
- le terme diffusif,
- le terme convectif,
- le solveur en pression.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 119 of file Navier_Stokes_std.cpp.
{
  Equation_base::readOn(is);
  if (est_egal(seuil_projection,0.) && (sub_type(solv_iteratif,solveur_pression_.valeur())))
    {
      solv_iteratif& solv_iter = ref_cast(solv_iteratif,solveur_pression_.valeur());
      seuil_projection = solv_iter.get_seuil();
    }
  terme_convectif.set_fichier("Convection_qdm");
  terme_convectif.set_description("Momentum flow rate=Integral(rho*u*u*ndS) [N] if SI units used");
  terme_diffusif.set_fichier("Contrainte_visqueuse");
  terme_diffusif.set_description("Friction drag exerted by the fluid=Integral(-mu*grad(u)*ndS) [N] if SI units used");
  divergence.set_fichier("Debit");
  divergence.set_description((Nom)"Volumetric flow rate=Integral(u*ndS) [m"+(Nom)(dimension+bidim_axi)+".s-1] if SI units used");
  gradient.set_fichier("Force_pression");
  gradient.set_description("Pressure drag exerted by the fluid=Integral(P*ndS) [N] if SI units used");
  int i_source = -1;
  int nb_source_pdf = 0;
  int nb_source  = sources().size();
  Cerr << "nb_source : " << nb_source << finl;
  for(int i = 0; i<nb_source; i++)
    {
// Cerr << (sources())[i].valeur().que_suis_je() << ", " << (sources())[i].valeur().que_suis_je().find("gne") << finl;
      if ((sources())[i].valeur().que_suis_je().find("Source_PDF") > -1)
        {
          i_source = i;
          nb_source_pdf++;
        }
    }
  if (nb_source_pdf>1)
    {
      Cerr<<"(IBM) More than one Source_PDF_base detected."<<finl;
      Cerr<<"(IBM) Case not supported."<<finl;
      Cerr<<"Aborting..."<<finl;
      abort();
    }
  i_source_pdf_ = i_source;
  if (i_source_pdf_ != -1)
    {
      sources()[i_source_pdf_].valeur().set_description((Nom)"Sum of the source term on the obstacle (~= force induced by the obstacle under some assumptions)");
      sources()[i_source_pdf_].valeur().set_fichier((Nom)"Force_induced_by_obstacle");
    }
  return is;
}
References Process::abort(), Objet_U::bidim_axi, Cerr, Objet_U::dimension, divergence, est_egal(), finl, solv_iteratif::get_seuil(), gradient, i_source_pdf_, Objet_U::que_suis_je(), Equation_base::readOn(), ref_cast, Operateur::set_description(), Operateur::set_fichier(), seuil_projection, liste::size(), solveur_pression_, Equation_base::sources(), sub_type, terme_convectif, terme_diffusif, List_Source::valeur(), Deriv_SolveurSys_base::valeur(), and valeur().
Referenced by Navier_Stokes_Fluide_Dilatable_base::readOn(), and QDM_Multiphase::readOn().
renewing_jacobians()
void Navier_Stokes_std::renewing_jacobians (DoubleTab & derivee) virtual
Definition at line 2308 of file Navier_Stokes_std.cpp.
{
// nothing to do
}
Referenced by corriger_derivee_impl().
reprendre()
int Navier_Stokes_std::reprendre (Entree & is) override virtual
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre()
et reprend la pression.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Definition at line 1616 of file Navier_Stokes_std.cpp.
{
  Equation_base::reprendre(is);
  double temps = schema_temps().temps_courant();
  Nom ident_pression(la_pression.le_nom());
  ident_pression += la_pression.valeur().que_suis_je();
  ident_pression += probleme().domaine().le_nom();
  ident_pression += Nom(temps,probleme().reprise_format_temps());
  avancer_fichier(is, ident_pression);
  la_pression.reprendre(is);
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier.reprendre_stat();
  return 1;
}
References avancer_fichier(), Probleme_base::domaine(), la_pression, Domaine::le_nom(), O_U_Ptr::le_nom(), le_traitement_particulier, O_U_Ptr::non_nul(), Equation_base::probleme(), Objet_U::que_suis_je(), Champ_Inc::reprendre(), Equation_base::reprendre(), Traitement_particulier_NS::reprendre_stat(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Deriv_Champ_Inc_base::valeur().
rho_la_vitesse()
const Champ_Inc & Navier_Stokes_std::rho_la_vitesse () const virtual
Reimplemented in Navier_Stokes_Fluide_Dilatable_base.
Definition at line 2299 of file Navier_Stokes_std.cpp.
{
  Cerr<<" Navier_Stokes_std::rho_la_vitesse() must be overloaded "<<finl;
  assert(0);
  exit();
  throw;
  return rho_la_vitesse();
}
References Cerr, Process::exit(), finl, and rho_la_vitesse().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), rho_la_vitesse(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport(), Convection_Diffusion_Espece_Binaire_base::vitesse_pour_transport(), and Convection_Diffusion_Espece_Multi_WC::vitesse_pour_transport().
sauvegarder()
int Navier_Stokes_std::sauvegarder (Sortie & os) const override virtual
Appelle Equation_base::sauvegarder(Sortie&)
et sauvegarde la pression sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Definition at line 1588 of file Navier_Stokes_std.cpp.
{
  int bytes=0;
  bytes += Equation_base::sauvegarder(os);
  bytes += la_pression.sauvegarder(os);
// La methode sauver() assurant la sauvegarde pour le traitement particulier
// est maintenant appelee ici au lieu d etre appelee dans des problemes particuliers
  sauver();
  return bytes;
}
References la_pression, Champ_Inc::sauvegarder(), Equation_base::sauvegarder(), and sauver().
sauver()
void Navier_Stokes_std::sauver () const virtual
Definition at line 2293 of file Navier_Stokes_std.cpp.
{
  if (le_traitement_particulier.non_nul())
    le_traitement_particulier.sauver_stat();
}
References le_traitement_particulier, O_U_Ptr::non_nul(), and Traitement_particulier_NS::sauver_stat().
Referenced by sauvegarder().
self_cast() [1/2]
const Navier_Stokes_std & Navier_Stokes_std::self_cast (const Objet_U & r) static
Definition at line 42 of file Navier_Stokes_std.cpp.
self_cast() [2/2]
Navier_Stokes_std & Navier_Stokes_std::self_cast (Objet_U & r) static
Definition at line 42 of file Navier_Stokes_std.cpp.
set_param()
void Navier_Stokes_std::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
Definition at line 165 of file Navier_Stokes_std.cpp.
{
  Equation_base::set_param(param);
  param.ajouter_non_std("diffusion",(this));
  param.ajouter_non_std("convection",(this));
  param.ajouter_condition("is_read_diffusion","The diffusion operator must be read, select negligeable type if you want to neglect it.");
  param.ajouter_condition("is_read_convection","The convection operator must be read, select negligeable type if you want to neglect it.");
  param.ajouter_non_std("solveur_pression",(this),Param::REQUIRED);
  param.ajouter_non_std("dt_projection",(this));
  param.ajouter_non_std("Traitement_particulier",(this));
  param.ajouter_non_std("Erreur_max_DivU",(this));
  param.ajouter("uzawa",&seuil_uzawa);
// param.ajouter_non_std("vitesse_transportante",(this));
  param.ajouter_non_std("seuil_divU",(this));
  param.ajouter_non_std("solveur_bar",(this));
  param.ajouter("projection_initiale",&projection_initiale);
  param.ajouter_non_std("methode_calcul_pression_initiale",(this));
// Parameters for IBM
  param.ajouter_flag("postraiter_gradient_pression_sans_masse",&postraiter_gradient_pression_sans_masse_,Param::OPTIONAL);
  param.ajouter("correction_matrice_projection_initiale",&correction_matrice_projection_initiale_,Param::OPTIONAL);
  param.ajouter("correction_calcul_pression_initiale",&correction_calcul_pression_initiale_,Param::OPTIONAL);
  param.ajouter("correction_vitesse_projection_initiale",&correction_vitesse_projection_initiale_,Param::OPTIONAL);
  param.ajouter("correction_matrice_pression",&correction_matrice_pression_,Param::OPTIONAL);
  param.ajouter("matrice_pression_penalisee_H1",&matrice_pression_penalisee_H1_,Param::OPTIONAL);
  param.ajouter("correction_vitesse_modifie",&correction_vitesse_modifie_,Param::OPTIONAL);
  param.ajouter("correction_pression_modifie",&correction_pression_modifie_,Param::OPTIONAL);
  param.ajouter("gradient_pression_qdm_modifie",&gradient_pression_qdm_modifie_,Param::OPTIONAL);
}
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), correction_calcul_pression_initiale_, correction_matrice_pression_, correction_matrice_projection_initiale_, correction_pression_modifie_, correction_vitesse_modifie_, correction_vitesse_projection_initiale_, gradient_pression_qdm_modifie_, matrice_pression_penalisee_H1_, Param::OPTIONAL, postraiter_gradient_pression_sans_masse_, projection_initiale, Param::REQUIRED, Equation_base::set_param(), and seuil_uzawa.
Referenced by QDM_Multiphase::set_param().
solveur_pression()
SolveurSys & Navier_Stokes_std::solveur_pression ()
Renvoie le solveur en pression<br>(version const)
Returns
SolveurSys&
Signification: le solveur en pression
Contraintes: reference constante
Definition at line 788 of file Navier_Stokes_std.cpp.
{
  return solveur_pression_;
}
References solveur_pression_.
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), and Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment().
taille_memoire()
unsigned Navier_Stokes_std::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in QDM_Multiphase.
Definition at line 42 of file Navier_Stokes_std.cpp.
update_pressure_matrix()
void Navier_Stokes_std::update_pressure_matrix (void) virtual
Definition at line 2318 of file Navier_Stokes_std.cpp.
{
// nothing to do
}
Referenced by initTimeStep().
uzawa()
void Navier_Stokes_std::uzawa (const DoubleTab & secmem, const Matrice_Base & A, SolveurSys & solveur, DoubleTab & U, DoubleTab & P) protected
< pour les C.L. de Dirichlet!
< pour les C.L. de Dirichlet!
Definition at line 2182 of file Navier_Stokes_std.cpp.
{
// A U + Bt P = secmem
// B U        = G
// On part de la pression courante et
// secmem = inertie + conv + sources + cl diff
// On part de P0 et U0 verifiant les C.L. et BU0=G
// AU + Bt Cp = secmem
// BU         = 0
// On ecrit un GC sur B(A-1)Bt Cp = B(A-1)(secmem)
  DoubleTrav Cu(U);
  DoubleTrav grad(U);
  DoubleTrav grad0(U);
  DoubleTrav resu(P);
  DoubleTrav residu(P);
  DoubleTrav Cp(P);
  double dold,dnew,alfa;
  double seuil=seuil_uzawa;
// Cu = A(-1) secmem
  Cerr << "Begining Uzawa, secmem norm value : " << mp_norme_vect(secmem) << finl;
  P=0.;
  gradient->multvect(P, grad0);
  solveur.nommer("uzawa_solver");
  solveur.resoudre_systeme(A, secmem, U);
  solv_masse().corriger_solution(U,Cu); //!< pour les C.L. de Dirichlet!
// residu=BCu
  divergence->multvect(U, resu);
  residu.copy(resu);
  residu*=-1.;
// Cp = -residu;
  Cp = residu;
  Cp*=-1;
  Cp.echange_espace_virtuel();
// Carre de la norme
  dold = mp_norme_vect(residu);
  dold = dold * dold;
  dnew = dold;
  double s=0;
  int niter=0;
  int nmax=Cp.size();
  Cerr << "Uzawa, initial residue : " << dnew << finl;
// seuil=std::max(seuil, dnew*1.e-12);
  while ( ( dnew > seuil ) && (niter++ < nmax) )
    {
      gradient->multvect(Cp, grad);
      grad-=grad0;
      grad*=-1;
      solveur.resoudre_systeme(A, grad, Cu);
      solv_masse().corriger_solution(Cu,U); //!< pour les C.L. de Dirichlet!
      divergence->multvect(Cu, resu);
      resu*=-1;
      s = mp_prodscal(resu, Cp);
      alfa = dold/(s);
      P.ajoute(alfa,Cp);
      residu.ajoute(alfa,resu);
      U.ajoute(alfa,Cu);
      dnew = mp_norme_vect(residu);
      dnew = dnew * dnew;
      assert(dnew >= 0);
      Cp *= (dnew/dold);
      Cp -= residu;
      dold = dnew;
// Cerr << "Uzawa, Residu apres "
// << niter << " iterations = " << dnew << finl;
    }
  if(dnew > seuil)
    {
      Cerr << "######## Uzawa, No convergence after : " << niter << " iterations\n";
      Cerr << "######## Uzawa,  Residue : "<< dnew << "\n";
      exit();
    }
  else if ((je_suis_maitre()))
    {
      Cerr << finl << "Uzawa, convergence reached after " << niter << " iterations" << finl;
    }
  {
// On verifie :
    DoubleTrav R(resu);
    divergence->multvect(U, R);
    Cerr << "Ending Uzawa : mass residue : " << mp_norme_vect(R) <<finl;
    gradient->multvect(P, grad);
    grad-=grad0;
    DoubleTrav F(secmem);
    DoubleTrav UU(U);
    F=secmem;
    F-=grad;
    solveur.resoudre_systeme(A, F, UU);
    UU-=U;
    Cerr << "Ending Uzawa : Qdm residue : " << mp_norme_vect(UU)<<finl;
  }
}
References TRUSTVect< _TYPE_ >::ajoute(), Cerr, TRUSTTab< _TYPE_ >::copy(), Solveur_Masse::corriger_solution(), divergence, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, gradient, Process::je_suis_maitre(), mp_norme_vect(), mp_prodscal(), SolveurSys::nommer(), SolveurSys::resoudre_systeme(), seuil_uzawa, TRUSTVect< _TYPE_ >::size(), and Equation_base::solv_masse().
Referenced by derivee_en_temps_inco().
verif_Cl()
int Navier_Stokes_std::verif_Cl () const override virtual
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
Returns
int
Signification:
Contraintes:
Reimplemented from Equation_base.
Definition at line 441 of file Navier_Stokes_std.cpp.
{
  return Equation_base::verif_Cl();
}
References Equation_base::verif_Cl().
vitesse() [1/2]
Champ_Inc & Navier_Stokes_std::vitesse () inline virtual
Definition at line 328 of file Navier_Stokes_std.h.
{
  return la_vitesse;
}
References la_vitesse.
vitesse() [2/2]
const Champ_Inc & Navier_Stokes_std::vitesse () const inline virtual
Definition at line 323 of file Navier_Stokes_std.h.
{
  return la_vitesse;
}
References la_vitesse.
Referenced by Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), and Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries().
vitesse_pour_transport()
const Champ_base & Navier_Stokes_std::vitesse_pour_transport () const virtual
Reimplemented in Navier_Stokes_Fluide_Dilatable_base, and QDM_Multiphase.
Definition at line 338 of file Navier_Stokes_std.cpp.
{
  return la_vitesse;
}
References la_vitesse.
Referenced by Source_PDF_EF::impr(), Piso::iterer_NS(), and lire_motcle_non_standard().
Member Data Documentation
assembleur_pression_
Assembleur Navier_Stokes_std::assembleur_pression_ protected
Definition at line 201 of file Navier_Stokes_std.h.
Referenced by assembleur_pression(), completer(), corriger_derivee_expl(), corriger_derivee_impl(), discretiser_assembleur_pression(), preparer_calcul(), and projeter().
chaine_champ_combi
Nom Navier_Stokes_std::chaine_champ_combi protected
Definition at line 220 of file Navier_Stokes_std.h.
champ_coeff_pdf_som_
DoubleTab Navier_Stokes_std::champ_coeff_pdf_som_ protected
Definition at line 237 of file Navier_Stokes_std.h.
Referenced by get_champ_coeff_pdf_som(), initTimeStep(), preparer_calcul(), and projeter().
combinaison_champ
Champ_Fonc Navier_Stokes_std::combinaison_champ protected
Definition at line 189 of file Navier_Stokes_std.h.
correction_calcul_pression_initiale_
int Navier_Stokes_std::correction_calcul_pression_initiale_ protected
Definition at line 229 of file Navier_Stokes_std.h.
Referenced by get_correction_calcul_pression_initiale(), Navier_Stokes_std(), preparer_calcul(), and set_param().
correction_matrice_pression_
int Navier_Stokes_std::correction_matrice_pression_ protected
Definition at line 231 of file Navier_Stokes_std.h.
Referenced by get_correction_matrice_pression(), initTimeStep(), Navier_Stokes_std(), preparer_calcul(), and set_param().
correction_matrice_projection_initiale_
int Navier_Stokes_std::correction_matrice_projection_initiale_ protected
Definition at line 228 of file Navier_Stokes_std.h.
Referenced by get_correction_matrice_projection_initiale(), Navier_Stokes_std(), preparer_calcul(), and set_param().
correction_pression_modifie_
int Navier_Stokes_std::correction_pression_modifie_ protected
Definition at line 234 of file Navier_Stokes_std.h.
Referenced by get_correction_pression_modifie(), Navier_Stokes_std(), and set_param().
correction_vitesse_modifie_
int Navier_Stokes_std::correction_vitesse_modifie_ protected
Definition at line 233 of file Navier_Stokes_std.h.
Referenced by get_correction_vitesse_modifie(), Navier_Stokes_std(), and set_param().
correction_vitesse_projection_initiale_
int Navier_Stokes_std::correction_vitesse_projection_initiale_ protected
Definition at line 230 of file Navier_Stokes_std.h.
Referenced by get_correction_vitesse_projection_initiale(), Navier_Stokes_std(), projeter(), and set_param().
Courant_maille
Champ_Fonc Navier_Stokes_std::Courant_maille protected
Definition at line 193 of file Navier_Stokes_std.h.
Referenced by creer_champ(), and get_champ().
critere_Q
Champ_Fonc Navier_Stokes_std::critere_Q protected
Definition at line 186 of file Navier_Stokes_std.h.
Referenced by creer_champ(), and get_champ().
cumulative_
double Navier_Stokes_std::cumulative_ mutable protected
Definition at line 211 of file Navier_Stokes_std.h.
Referenced by impr(), and Navier_Stokes_std().
distance_paroi_globale
Champ_Fonc Navier_Stokes_std::distance_paroi_globale protected
Definition at line 190 of file Navier_Stokes_std.h.
Referenced by completer(), and creer_champ().
div_u_nul_et_non_dsurdt_divu_
int Navier_Stokes_std::div_u_nul_et_non_dsurdt_divu_ protected
Definition at line 224 of file Navier_Stokes_std.h.
Referenced by corriger_derivee_impl().
divergence
Operateur_Div Navier_Stokes_std::divergence protected
Definition at line 198 of file Navier_Stokes_std.h.
Referenced by associer_pb_base(), completer(), corriger_derivee_impl(), discretiser(), impr(), mettre_a_jour(), operateur_divergence(), operateur_fonctionnel(), preparer_calcul(), projeter(), Navier_Stokes_Fluide_Dilatable_base::readOn(), readOn(), QDM_Multiphase::readOn(), and uzawa().
divergence_U
Champ_Inc Navier_Stokes_std::divergence_U protected
Definition at line 181 of file Navier_Stokes_std.h.
Referenced by completer(), discretiser(), div(), impr(), mettre_a_jour(), preparer_calcul(), and projeter().
dt_projection
double Navier_Stokes_std::dt_projection protected
Definition at line 204 of file Navier_Stokes_std.h.
Referenced by lire_motcle_non_standard(), Navier_Stokes_std(), and projection_a_faire().
grad_u
Champ_Fonc Navier_Stokes_std::grad_u protected
Definition at line 185 of file Navier_Stokes_std.h.
Referenced by creer_champ(), QDM_Multiphase::creer_champ(), get_champ(), and QDM_Multiphase::mettre_a_jour().
gradient
Operateur_Grad Navier_Stokes_std::gradient protected
Definition at line 199 of file Navier_Stokes_std.h.
Referenced by assembler_blocs(), associer_pb_base(), completer(), QDM_Multiphase::completer(), corriger_derivee_expl(), corriger_derivee_impl(), derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), discretiser(), has_interface_blocs(), impr(), mettre_a_jour(), operateur_fonctionnel(), operateur_gradient(), preparer_calcul(), projeter(), readOn(), and uzawa().
gradient_P
Champ_Inc Navier_Stokes_std::gradient_P protected
Definition at line 182 of file Navier_Stokes_std.h.
Referenced by completer(), corriger_derivee_expl(), corriger_derivee_impl(), derivee_en_temps_inco(), discretiser(), grad_P(), mettre_a_jour(), preparer_calcul(), and projeter().
gradient_pression_qdm_modifie_
int Navier_Stokes_std::gradient_pression_qdm_modifie_ protected
Definition at line 235 of file Navier_Stokes_std.h.
Referenced by get_gradient_pression_qdm_modifie(), Navier_Stokes_std(), and set_param().
i_source_pdf_
int Navier_Stokes_std::i_source_pdf_ protected
Definition at line 236 of file Navier_Stokes_std.h.
Referenced by get_i_source_pdf(), initTimeStep(), preparer_calcul(), projeter(), and readOn().
info_obj
const Type_info Navier_Stokes_std::info_obj static
Definition at line 59 of file Navier_Stokes_std.h.
la_pression
Champ_Inc Navier_Stokes_std::la_pression protected
Definition at line 180 of file Navier_Stokes_std.h.
Referenced by calculer_la_pression_en_pa(), completer(), corriger_derivee_expl(), corriger_derivee_impl(), derivee_en_temps_inco(), discretiser(), impr(), QDM_Multiphase::lire_cond_init(), mettre_a_jour(), preparer_calcul(), pression(), projeter(), reprendre(), and sauvegarder().
la_pression_en_pa
Champ_Inc Navier_Stokes_std::la_pression_en_pa protected
Definition at line 183 of file Navier_Stokes_std.h.
Referenced by calculer_la_pression_en_pa(), completer(), discretiser(), QDM_Multiphase::lire_cond_init(), mettre_a_jour(), and pression_pa().
la_vitesse
Champ_Inc Navier_Stokes_std::la_vitesse protected
Definition at line 179 of file Navier_Stokes_std.h.
Referenced by corriger_derivee_impl(), creer_champ(), discretiser(), discretiser_vitesse(), QDM_Multiphase::discretiser_vitesse(), get_champ(), inconnue(), QDM_Multiphase::lire_cond_init(), mettre_a_jour(), preparer_calcul(), projeter(), vitesse(), vitesse_pour_transport(), Navier_Stokes_Fluide_Dilatable_base::vitesse_pour_transport(), and QDM_Multiphase::vitesse_pour_transport().
la_vorticite
Champ_Fonc Navier_Stokes_std::la_vorticite protected
Definition at line 184 of file Navier_Stokes_std.h.
Referenced by creer_champ(), QDM_Multiphase::creer_champ(), get_champ(), and QDM_Multiphase::mettre_a_jour().
le_fluide
Ref_Fluide_base Navier_Stokes_std::le_fluide protected
Definition at line 177 of file Navier_Stokes_std.h.
Referenced by associer_fluide(), Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), QDM_Multiphase::diffusivite_pour_pas_de_temps(), Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_transport(), QDM_Multiphase::diffusivite_pour_transport(), fluide(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), milieu(), preparer_calcul(), Navier_Stokes_QC::readOn(), Navier_Stokes_WC::readOn(), and QDM_Multiphase::readOn().
le_traitement_particulier
Traitement_particulier_NS Navier_Stokes_std::le_traitement_particulier protected
Definition at line 213 of file Navier_Stokes_std.h.
Referenced by creer_champ(), get_champ(), get_noms_champs_postraitables(), lire_motcle_non_standard(), mettre_a_jour(), preparer_calcul(), reprendre(), and sauver().
LocalFlowRateRelativeError_
double Navier_Stokes_std::LocalFlowRateRelativeError_ protected
Definition at line 210 of file Navier_Stokes_std.h.
Referenced by impr(), and mettre_a_jour().
matrice_pression_
Matrice Navier_Stokes_std::matrice_pression_ protected
Definition at line 200 of file Navier_Stokes_std.h.
Referenced by corriger_derivee_impl(), initTimeStep(), matrice_pression(), preparer_calcul(), and projeter().
matrice_pression_penalisee_H1_
int Navier_Stokes_std::matrice_pression_penalisee_H1_ protected
Definition at line 232 of file Navier_Stokes_std.h.
Referenced by get_matrice_pression_penalisee_H1(), initTimeStep(), Navier_Stokes_std(), preparer_calcul(), and set_param().
max_div_U
double Navier_Stokes_std::max_div_U protected
Definition at line 207 of file Navier_Stokes_std.h.
Referenced by lire_motcle_non_standard(), and Navier_Stokes_std().
methode_calcul_pression_initiale_
int Navier_Stokes_std::methode_calcul_pression_initiale_ protected
Definition at line 221 of file Navier_Stokes_std.h.
Referenced by lire_motcle_non_standard(), and preparer_calcul().
P_n
DoubleTab Navier_Stokes_std::P_n private
Definition at line 243 of file Navier_Stokes_std.h.
Referenced by abortTimeStep(), and initTimeStep().
porosite_volumique
Champ_Fonc Navier_Stokes_std::porosite_volumique protected
Definition at line 188 of file Navier_Stokes_std.h.
Referenced by creer_champ(), and get_champ().
postraitement_gradient_P_
int Navier_Stokes_std::postraitement_gradient_P_ mutable private
Definition at line 245 of file Navier_Stokes_std.h.
Referenced by get_champ(), and mettre_a_jour().
postraiter_gradient_pression_sans_masse_
int Navier_Stokes_std::postraiter_gradient_pression_sans_masse_ protected
Definition at line 227 of file Navier_Stokes_std.h.
Referenced by mettre_a_jour(), Navier_Stokes_std(), and set_param().
pression_hydrostatique_
Champ_Fonc Navier_Stokes_std::pression_hydrostatique_ protected
Definition at line 187 of file Navier_Stokes_std.h.
Referenced by creer_champ(), and get_champ().
projection_initiale
int Navier_Stokes_std::projection_initiale protected
Definition at line 203 of file Navier_Stokes_std.h.
Referenced by Navier_Stokes_std(), projection_a_faire(), projeter(), and set_param().
raison_seuil_divU
double Navier_Stokes_std::raison_seuil_divU protected
Definition at line 209 of file Navier_Stokes_std.h.
Referenced by lire_motcle_non_standard(), and mettre_a_jour().
Reynolds_maille
Champ_Fonc Navier_Stokes_std::Reynolds_maille protected
Definition at line 192 of file Navier_Stokes_std.h.
Referenced by creer_champ(), and get_champ().
seuil_divU
double Navier_Stokes_std::seuil_divU protected
Definition at line 208 of file Navier_Stokes_std.h.
Referenced by impr(), lire_motcle_non_standard(), mettre_a_jour(), and Navier_Stokes_std().
seuil_projection
double Navier_Stokes_std::seuil_projection protected
Definition at line 205 of file Navier_Stokes_std.h.
Referenced by lire_motcle_non_standard(), Navier_Stokes_std(), projeter(), and readOn().
seuil_uzawa
double Navier_Stokes_std::seuil_uzawa protected
Definition at line 206 of file Navier_Stokes_std.h.
Referenced by Navier_Stokes_std(), set_param(), and uzawa().
solveur_pression_
SolveurSys Navier_Stokes_std::solveur_pression_ protected
Definition at line 202 of file Navier_Stokes_std.h.
Referenced by corriger_derivee_impl(), impr(), lire_motcle_non_standard(), mettre_a_jour(), preparer_calcul(), projeter(), readOn(), and solveur_pression().
Taux_cisaillement
Champ_Fonc Navier_Stokes_std::Taux_cisaillement protected
Definition at line 194 of file Navier_Stokes_std.h.
Referenced by creer_champ(), QDM_Multiphase::creer_champ(), get_champ(), and QDM_Multiphase::mettre_a_jour().
terme_convectif
Operateur_Conv Navier_Stokes_std::terme_convectif protected
Definition at line 196 of file Navier_Stokes_std.h.
Referenced by QDM_Multiphase::completer(), corriger_derivee_impl(), get_terme_convectif(), lire_motcle_non_standard(), operateur(), readOn(), and QDM_Multiphase::readOn().
terme_diffusif
Operateur_Diff Navier_Stokes_std::terme_diffusif protected
Definition at line 197 of file Navier_Stokes_std.h.
Referenced by QDM_Multiphase::completer(), diffusivite_pour_pas_de_temps(), lire_motcle_non_standard(), operateur(), and readOn().
y_plus
Champ_Fonc Navier_Stokes_std::y_plus protected
Definition at line 191 of file Navier_Stokes_std.h.
Referenced by creer_champ(), get_champ(), and QDM_Multiphase::update_y_plus().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Equations/Navier_Stokes_std.h
src/ThHyd/Incompressible/Equations/Navier_Stokes_std.cpp