TRUST: Pave Class Reference
Pave Class Reference
Classe Pave
Une zone particulierement facile a mailler!
La structure du jeu de donnee pour specifier un Pave est:
Pave nom_pave
{
Origine OX OY (OZ)
Longueurs LX LY (LZ)
Nombre_de_noeuds NX NY (NZ)
Facteurs Fx Fy (Fz)
(Symx)
(Symy)
(Symz)
}
{
(Bord) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Raccord) local homogene nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Internes) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Joint) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 PE_voisin
...
}.
#include <Pave.h>
Public Member Functions
Pave ()
~Pave ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_domaine (const Domaine &) override
Associe un domaine au Pave.
IntVect & Nb_Noeud ()
Renvoie le nombre de noeuds du pave dans
chacune des dimensions d'espace.
int numero_maille (int)
Renvoie le numero de la i-ieme maille<br>(suivant X)
int numero_maille (int, int)
Renvoie le numero de la (i,j)-ieme maille<br>(suivant (X,Y)).
int numero_maille (int, int, int)
Renvoie le numero de la (i,j,k)-ieme maille<br>(suivant (X,Y,Z)).
int numero_sommet (int)
Renvoie le numero du i-ieme sommet<br>(suivant X)
int numero_sommet (int, int)
Renvoie le numero du (i,j)-ieme sommet<br>(suivant (X,Y)).
int numero_sommet (int, int, int)
Renvoie le numero du (i,j,k)-ieme sommet<br>(suivant (X,Y,Z)).
int & maille_sommet (int, int)
Renvoie une reference sur le numero du l-ieme sommet
de la i-ieme maille (suivant X) du pave.
int & maille_sommet (int, int, int)
Renvoie une reference sur le numero du l-ieme sommet
de la (i,j)-ieme maille (suivant (X,Y)) du pave.
int & maille_sommet (int, int, int, int)
Renvoie une reference sur le numero du l-ieme sommet
de la (i,j,k)-ieme maille (suivant (X,Y,Z)) du pave.
double & coord_noeud (int)
Renvoie une reference sur les coordonnees
du i-ieme noeud.
double & coord_noeud (int, int, int)
Renvoie une reference sur les coordonnees
du (i,j)-ieme noeud.
double & coord_noeud (int, int, int, int)
Renvoie une reference sur les coordonnees
du (i,j,k)-ieme noeud.
void maille1D ()
Effectue un maillage 1D, du pave
avec les valeurs des parametres lus par ReadOn.
void maille2D ()
Effectue un maillage 2D, du pave
avec les valeurs des parametres lus par ReadOn.
void maille3D ()
Effectue un maillage 3D, du pave
avec les valeurs des parametres lus par ReadOn.
void typer_ ()
Type le pave suivant la dimension d'espace
et suivant le repere de coordonnees demande (cylindrique
ou cartesien)
En dimension 1 : le pave est maille avec des segments
En dimension 2 (axi): la pave est maille avec des rectangle (axi)
En dimension 3 (axi): la pave est maille avec des hexaedres (axi)
void lire_Longueurs (Entree &is)
Lit les longueurs LX LY [LZ] du jeu de donnee
a partir d'un flot d'entree.
Methode appelee par readOn(Entree&)
void lire_Noeuds (Entree &is)
Lit le nombre de noeuds dans le jeu de donnee
a partir d'un flot d'entree et construit les noeuds.
Methode appelee par readOn(Entree&)
void lire_front (Entree &, Frontiere &)
Lit les specifications d'une frontiere du jeu de donnee
a partir d'un flot d'entree et la construit.
Format:
nom_front X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1.
Public Member Functions inherited from Zone
Zone ()
~Zone ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Elem_geom & type_elem () const
Renvoie un element geometrique du type de ceux
qui constituent la zone.
(version const)
Elem_geom & type_elem ()
Renvoie un element geometrique du type de ceux
qui constituent la zone.
void typer (const Nom &)
Type les elements de la zone avec le
nom passe en parametre. Et associe le type
d'element a la zone.
int nb_elem () const
Renvoie le nombre d'elements de la zone.
int nb_elem_tot () const
Renvoie le nombre total d'elements de la zone.
int nb_aretes () const
renvoie le nombre d'aretes reelles.
int nb_aretes_tot () const
renvoie le nombre d'aretes total (reelles+virtuelles).
int nb_som () const
Renvoie le nombre de sommets de la zone.
int nb_som_tot () const
Renvoie le nombre total de sommets de la zone.
i.e. le nombre de sommets reels et virtuels
sur le processeur courant.
int nb_som_elem () const
Renvoie le nombre de sommets des elements geometriques
constituants la zone. Tous les elements de la zone etant
du meme type ils ont tous le meme nombre de sommets
qui est le nombre de sommet du type des elements geometriques
de la zone.
int nb_faces_elem (int=0) const
Renvoie le nombre de face de type i
des elements geometriques constituants la zone.
Ex: les objets de la classe Prisme ont 2 types
de faces: triangle ou quadrangle.
int sommet_elem (int, int) const
Renvoie le numero (global) j-ieme sommet du i-ieme element.
const Nom & le_nom () const override
Renvoie le nom de la zone.
void nommer (const Nom &) override
Donne un nom a la zone.
const Domaine & domaine () const
Renvoie le domaine dont la zone fait partie.
(version const)
Domaine & domaine ()
Renvoie le domaine dont la zone fait partie.
void fixer_premieres_faces_frontiere ()
ArrOfInt & chercher_elements (const DoubleTab &, ArrOfInt &, int reel=0) const
ArrOfInt & chercher_elements (const DoubleVect &, ArrOfInt &, int reel=0) const
Recherche des elements contenant les points dont les
coordonnees sont specifiees.
ArrOfInt & indice_elements (const IntTab &, ArrOfInt &, int reel=0) const
che les numeros (indices) des elements contenants les sommets
specifies par le parametre "sommets".
Utilise:
ArrOfInt& Zone::chercher_elements(const DoubleTab&,ArrOfInt&) const
int chercher_elements (double x, double y=0, double z=0, int reel=0) const
Renvoie le rang de l'element contenant
le point dont les coordonnees sont specifiees.
ArrOfInt & chercher_sommets (const DoubleTab &, ArrOfInt &, int reel=0) const
int chercher_sommets (double x, double y=0, double z=0, int reel=0) const
ArrOfInt & chercher_aretes (const DoubleTab &, ArrOfInt &, int reel=0) const
virtual void associer_domaine (const Domaine &)
Specifie le domaine dont la zone fait partie.
void init_faces_virt_bord (const MD_Vector &md_vect_faces, MD_Vector &md_vect_faces_bord)
Methode appelee par Zone_VF::discretiser().
Construction du descripteur pour les faces de bord
Remplissage de ind_faces_virt_bord et des tableaux get_faces_virt() des frontieres
a partir du descripteur parallele des faces.
Note B.M.: le fait d'avoir mis les faces dans la Zone_VF, les aretes dans la Zone,
certaines parties des proprites des faces de bord dans la Zone_VF et d'autres dans la Zone
fait que l'initialisation passe par des chemins un peu tordus... il faudra nettoyer ca.
void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites des elements de la zone.
void calculer_centres_gravite_aretes (DoubleTab &) const
Calcule les centres de gravites des aretes de la zone.
void creer_aretes ()
void calculer_volumes (DoubleVect &, DoubleVect &) const
Calcule les volumes des elements de la zone.
void calculer_mon_centre_de_gravite (ArrOfDouble &)
Calcule le centre de gravite de la zone.
IntTab & les_elems ()
Renvoie le tableau des sommets des elements.
const IntTab & les_elems () const
Renvoie le tableau des sommets des elements<br>(version const)
int arete_sommets (int i, int j) const
renvoie le numero du jeme sommet de la ieme arete.
int elem_aretes (int i, int j) const
renvoie le numero de la jeme arete du ieme element.
const IntTab & aretes_som () const
renvoie le tableau de connectivite aretes/sommets.
const IntTab & elem_aretes () const
renvoie le tableau de connectivite elements/aretes.
IntTab & set_aretes_som ()
IntTab & set_elem_aretes ()
int nb_bords () const
Renvoie le nombre de bords de la zone.
int nb_joints () const
Renvoie le nombre de joints de la zone.
int nb_raccords () const
Renvoie le nombre de raccords de la zone.
int nb_frontieres_internes () const
Renvoie le nombre de frontieres internes de la zone.
int nb_front_Cl () const
Renvoie le nombre de bords
+ le nombre de raccords
+ le nombre de faces frontieres internes.
int nb_faces_bord () const
Renvoie le nombre de faces qui sont des bords.
int nb_faces_joint () const
Renvoie le nombre de joints de la zone.
int nb_faces_raccord () const
Renvoie le nombre de raccords de la zone.
int nb_faces_int () const
Renvoie le nombre de face internes de la zone.
int nb_faces_bord (int) const
Renvoie le nombre de faces du i-ieme bord.
int nb_faces_joint (int) const
Renvoie le nombre de faces du i-ieme joint.
int nb_faces_raccord (int) const
Renvoie le nombre de faces du i-ieme raccord.
int nb_faces_int (int) const
Renvoie le nombre de faces de la i-ieme
liste de faces internes.
int nb_faces_frontiere (Type_Face type) const
Renvoie le nombre de faces frontiere de la zone
du type specifie.
C'est la somme des nombres de bords, de raccords
et de faces internes du type specifie.
int nb_faces_frontiere () const
Renvoie le nombre de faces frontiere de la zone.
C'est la somme des nombres de bords, de raccords et de faces internes.
const Bord & bord (int) const
Renvoie le i-ieme bord de la zone<br>(version const)
Bord & bord (int)
Renvoie le i-ieme bord de la zone.
const Joint & joint (int) const
Renvoie le i-ieme joint de la zone<br>(version const)
Joint & joint (int)
Renvoie le i-ieme joint de la zone.
Joint & joint_of_pe (int)
const Joint & joint_of_pe (int) const
Renvoie le joint correspondant au PE specifie.
(PE = Processeur Elementaire, ou numero de processus)
Un joint est une frontiere entre 2 PE.
const Raccord & raccord (int) const
Renvoie le i-ieme raccord de la zone<br>(version const)
Raccord & raccord (int)
Renvoie le i-ieme raccord de la zone.
const Faces_Interne & faces_interne (int) const
Renvoie les i-ieme faces internes de la zone<br>(version const)
Faces_Interne & faces_interne (int)
Renvoie les i-ieme faces internes de la zone.
const Bord & bord (const Nom &) const
Renvoie le bord dont le nom est specifie.
(version const)
Bord & bord (const Nom &)
Renvoie le bord dont le nom est specifie.
const Frontiere & frontiere (int i) const
Frontiere & frontiere (int i)
int rang_frontiere (const Nom &) const
const Frontiere & frontiere (const Nom &) const
Frontiere & frontiere (const Nom &)
const Joint & joint (const Nom &) const
Renvoie le joint dont le nom est specifie<br>(version const)
Joint & joint (const Nom &)
Renvoie le joint dont le nom est specifie.
const Raccord & raccord (const Nom &) const
Renvoie le raccord dont le nom est specifie<br>(version const)
Raccord & raccord (const Nom &)
Renvoie le raccord dont le nom est specifie.
const Faces_Interne & faces_interne (const Nom &) const
Renvoie les faces_internes dont le nom est specifie<br>(version const)
Faces_Interne & faces_interne (const Nom &)
Renvoie les faces_internes dont le nom est specifie.
const Bords & faces_bord () const
Renvoie la liste des bords de la zone.
(version const)
Bords & faces_bord ()
Renvoie la liste des bords de la zone.
const Joints & faces_joint () const
Renvoie la liste des joints de la zone.
(version const)
Joints & faces_joint ()
Renvoie la liste des joints de la zone.
const Raccords & faces_raccord () const
Renvoie la liste des racoords de la zone.
(version const)
Raccords & faces_raccord ()
Renvoie la liste des racoords de la zone.
const Faces_Internes & faces_int () const
Renvoie la liste des faces internes de la zone.
(version const)
Faces_Internes & faces_int ()
Renvoie la liste des faces internes de la zone.
void renum (const IntVect &)
Renumerotation des noeuds:
Le noeud de numero k devient le noeud de numero Les_Nums[k].
void renum_joint_common_items (const IntVect &Les_Nums, const int elem_offset)
Renumerotation des noeuds et des elements presents dans les items communs des joints
Le noeud de numero k devient le noeud de numero Les_Nums[k]
l'element de numero e devient l'element de numero e+elem_offset.
void reordonner ()
Reordonne les elements suivant la convention
employe par Trio-U.
int face_interne_conjuguee (int) const
Renvoie -1 si face n'est pas une face interne
Renvoie le numero de la face dupliquee sinon.
int comprimer ()
Concatene les bords de meme nom et ceci pour:
les bords, les bords periodiques et les faces internes.
int comprimer_joints ()
Concatene les joints de meme nom.
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie
Ecrit les noms des: bords, bords periodiques, raccords
et faces internes.
double epsilon () const
void associer_Bords_a_imprimer (List_Nom)
void associer_Bords_a_imprimer_sum (List_Nom)
Entree & Lire_Bords_a_imprimer (Entree &s)
Entree & Lire_Bords_a_imprimer_sum (Entree &s)
const List_Nom & Bords_a_imprimer () const
const List_Nom & Bords_a_imprimer_sum () const
int Moments_a_imprimer () const
int & Moments_a_imprimer ()
const ArrOfDouble & cg_moments () const
ArrOfDouble & cg_moments ()
void exporter_mon_centre_de_gravite (ArrOfDouble c)
double volume_total () const
int nb_faces_bord (Type_Face type) const
Renvoie le nombre de faces du type specifie.
int nb_faces_joint (Type_Face type) const
Renvoie le nombre de joints du type specifie.
int nb_faces_raccord (Type_Face type) const
Renvoie le nombre de raccords du type specifie.
int nb_faces_int (Type_Face type) const
Renvoie le nombre de faces interieures du type specifie.
int rang_elem_depuis (const DoubleTab &, const ArrOfInt &, ArrOfInt &) const
void rang_elems_sommet (ArrOfInt &, double x, double y=0, double z=0) const
void invalide_octree ()
const OctreeRoot & construit_octree () const
const OctreeRoot & construit_octree (int &) const
construction de l'octree si pas deja fait
const ArrOfInt & ind_faces_virt_bord () const
void construire_elem_virt_pe_num ()
void construire_elem_virt_pe_num (IntTab &elem_virt_pe_num_cpy) const
const IntTab & elem_virt_pe_num () const
virtual void creer_tableau_elements (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
creation d'un tableau parallele de valeurs aux elements.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual const MD_Vector & md_vector_elements () const
renvoie le descripteur parallele des tableaux aux elements de la zone
void read_zone (Entree &s)
read zone from the input stream
void check_zone ()
associate the read objects to the zone
and check that the reading objects are coherent
void correct_type_of_borders_after_merge ()
Correcting type of borders if they were empty before merge (ie equal to vide_0D)
difference with corriger_type is that we don't want to delete faces inside borders afterwards.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Pave & self_cast (Objet_U &)
static const Pave & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone & self_cast (Objet_U &)
static const Zone & self_cast (const Objet_U &)
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
DoubleVect Origine
DoubleVect Longueurs
IntVect Nb_Noeuds
DoubleVect Facteurs
DoubleVect Pas
DoubleTab Les_Noeuds
IntVect Les_Nums
IntVect Symetrique
double a_tanh
a pour le maillage en tanh dans la diry!!
int tanh_dilatation
double xa_tanh
xa pour le maillage en tanh dans la dirx!!
int xtanh_dilatation
double za_tanh
za pour le maillage en tanh dans la dirz!!
int ztanh_dilatation
int rep_VEF
int Nx
int Ny
int Nz
int Mx
int My
int Mz
int tour_complet
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Zone::printOn(Sortie&)
Entree & readOn (Entree &) override
Lit les specifications d'un pave a partir
d'un flot d'entree.
Le format de lecture d'un pave dans le jeu de donnee est le suivant:
Pave nom_pave
{
Origine OX OY (OZ)
Longueurs LX LY (LZ)
Nombre_de_noeuds NX NY (NZ)
Facteurs Fx Fy (Fz)
(Symx)
(Symy)
(Symz)
}
{
(Bord) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Raccord) local homogene nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Internes) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Joint) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 PE_voisin
...
}.
Protected Member Functions inherited from Zone
Sortie & printOn (Sortie &x) const override
Ecrit la Zone sur un flot de sortie.
On ecrit le nom, le type des elements, les elements
et les bords, les bords periodiques, les joints, les
raccords et les faces internes.
Entree & readOn (Entree &) override
Lit les objets constituant une Zone
a partir d'un flot d'entree. Une fois les objets
lus on les associe a la zone.
void duplique_faces_internes ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Zone
Nom nom
Ref_Domaine le_domaine
Elem_geom elem
IntTab mes_elems
IntTab Aretes_som
IntTab Elem_Aretes
Bords mes_faces_bord
Raccords mes_faces_raccord
Faces_Internes mes_faces_int
Joints mes_faces_joint
ArrOfInt ind_faces_virt_bord_
contient les indices des faces virtuelles de bord
Deriv_OctreeRoot deriv_octree_
ArrOfDouble cg_moments_
IntTab elem_virt_pe_num_
List_Nom Bords_a_imprimer_
List_Nom Bords_a_imprimer_sum_
int Moments_a_imprimer_
Detailed Description
Classe Pave
Une zone particulierement facile a mailler!
La structure du jeu de donnee pour specifier un Pave est:
Pave nom_pave
{
Origine OX OY (OZ)
Longueurs LX LY (LZ)
Nombre_de_noeuds NX NY (NZ)
Facteurs Fx Fy (Fz)
(Symx)
(Symy)
(Symz)
}
{
(Bord) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Raccord) local homogene nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Internes) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Joint) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 PE_voisin
...
}.
Definition at line 52 of file Pave.h.
Constructor & Destructor Documentation
Pave()
Pave::Pave ()
Definition at line 59 of file Pave.cpp.
:a_tanh(-123),tanh_dilatation(-123),xa_tanh(-123),xtanh_dilatation(-123),za_tanh(-123),ztanh_dilatation(-123),Nx(-1),Ny(-1),Nz(-1),Mx(-1),My(-1),Mz(-1),tour_complet(-123) {}
~Pave()
Pave::~Pave ()
Definition at line 20 of file Pave.cpp.
Member Function Documentation
associer_domaine()
void Pave::associer_domaine (const Domaine & un_dom) override virtual
Associe un domaine au Pave.
Reimplemented from Zone.
Definition at line 507 of file Pave.cpp.
{
  Zone::associer_domaine(un_dom);
  if(Les_Noeuds.size() > 0)
    {
// On copie Les_Noeuds dans le domaine
      le_domaine->ajouter(Les_Noeuds, Les_Nums);
// On n'a plus besoin du tableau Les_Noeuds
      Les_Noeuds.resize(0,Les_Noeuds.dimension(1));
// On renumerote la zone avec le tableau Les_Nums
      renum(Les_Nums);
      Les_Nums.resize(0);
    }
}
References Domaine::ajouter(), Zone::associer_domaine(), TRUSTTab< _TYPE_ >::dimension(), Zone::le_domaine, Les_Noeuds, Les_Nums, Zone::renum(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), and TRUSTVect< _TYPE_ >::size().
coord_noeud() [1/3]
double & Pave::coord_noeud (int i) inline
Renvoie une reference sur les coordonnees
du i-ieme noeud.
Returns
double&
Signification: reference sur les coordonnees du noeud cherche
Contraintes:
Definition at line 405 of file Pave.h.
{
  assert(dimension == 1);
  return Les_Noeuds(numero_sommet(i));
}
References Objet_U::dimension, Les_Noeuds, and numero_sommet().
Referenced by lire_front(), maille1D(), maille2D(), and maille3D().
coord_noeud() [2/3]
double & Pave::coord_noeud (int i, int j, int l) inline
Renvoie une reference sur les coordonnees
du (i,j)-ieme noeud.
Returns
double&
Signification: reference sur les coordonnees du noeud cherche
Contraintes:
Definition at line 431 of file Pave.h.
{
  assert(dimension == 2);
  return Les_Noeuds(numero_sommet(i, j),l);
}
References Objet_U::dimension, Les_Noeuds, and numero_sommet().
coord_noeud() [3/3]
double & Pave::coord_noeud (int i, int j, int k, int l) inline
Renvoie une reference sur les coordonnees
du (i,j,k)-ieme noeud.
Returns
double&
Signification: reference sur les coordonnees du noeud cherche
Contraintes:
Definition at line 462 of file Pave.h.
{
  assert(dimension == 3);
  return Les_Noeuds(numero_sommet(i, j, k),l);
}
References Objet_U::dimension, Les_Noeuds, and numero_sommet().
cree_instance()
Objet_U * Pave::cree_instance () static
Definition at line 20 of file Pave.cpp.
duplique()
int Pave::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Pave.cpp.
get_info()
const Type_info * Pave::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 20 of file Pave.cpp.
info()
const Type_info * Pave::info () static
Definition at line 20 of file Pave.cpp.
lire_front()
void Pave::lire_front (Entree & is, Frontiere & front)
Lit les specifications d'une frontiere du jeu de donnee
a partir d'un flot d'entree et la construit.
Format:
nom_front X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1.
Definition at line 53 of file Pave2.cpp.
{
  int i, j, k;
  Nom nom_front;
  is >> nom_front;
  Cerr << "Reading of the boundary " << nom_front << finl;
  front.nommer(nom_front);
  front.typer_faces(elem.type_face());
  int internes=sub_type(Faces_Interne, front);
  if(dimension==1)
    {
      Nom X, egal;
      double coupe;
      is  >> X >> egal >> coupe ;
      if( X!="X")
        {
          Cerr << "We expected a = X instead of" << X  <<
               " before " << egal << " " << coupe << finl;
          exit();
        }
      if( egal!="=")
        {
          Cerr << "We expected a = after " << X << finl;
          exit();
        }
      front.dimensionner(0);
      IntTab som(1,1);
      if ( (coupe != Origine(0)) && (coupe != (Origine(0)+Longueurs(0))) )
        {
          Cerr << coupe << " is not an extremity" << finl;
          Cerr << "The extremities are : "
               << Origine(0) << " " << Origine(0)+Longueurs(0) << finl;
          exit();
        }
      if(std::fabs(coupe - Origine(0))<epsilon())
        som(0,0)=0;
      else
        som(0,0)=Mx;
      front.ajouter_faces(som);
      front.associer_zone(*this);
    }
  else if(dimension==2)
    {
      Nom X, Y, egal, infegal1, infegal2;
      double coupe;
      double xmin, xmax;
      is  >> X >> egal >> coupe ;
      if( (X!="X") && (X!="Y") )
        {
          Cerr << "We expected a = X or Y instead of" << X <<
               " before " << egal << " " << coupe << finl;
          exit();
        }
      if( egal!="=")
        {
          Cerr << "We expected a = after " << X << finl;
          exit();
        }
      is >> xmin >> infegal1 >> Y >> infegal2 >> xmax;
      if( infegal1!="<=")
        {
          Cerr << "We expected a <= after " << xmin << " and not " << infegal1 << finl;
          exit();
        }
      if (X=="X")
        {
          if( Y!="Y" )
            {
              Cerr << "We expected a Y after " << infegal1 << finl;
              exit();
            }
          if (axi)
            {
              double deux_pi=M_PI*2.0 ;
              xmin*=deux_pi;
              xmax*=deux_pi;
            }
        }
      else
        {
          assert(tour_complet!=-123);
          if(tour_complet)
            {
              Cerr << "There is no boundary in teta! " << finl;
              Cerr << "You have meshed a complete crown! " << finl;
              exit();
            }
          if( Y!="X" )
            {
              Cerr << "We expected a X after " << infegal1 << finl;
              exit();
            }
        }
      if( infegal2!="<=")
        {
          Cerr << "We expected a <= after " << Y << " and not " << infegal2 <<finl;
          exit();
        }
      front.dimensionner(0);
      IntTab som;
      if (X=="X")
        {
          if ( (std::fabs(Origine(0) - coupe)>epsilon()) &&
               (std::fabs(coupe - Origine(0)-Longueurs(0))>epsilon()) && (!internes))
            {
              Cerr << "X = " << coupe << " is not a boundary" << finl;
              exit();
            }
          if ( ((std::fabs(Origine(0) - coupe)<epsilon()) ||
                (std::fabs(coupe - Origine(0)-Longueurs(0))<epsilon())) && (internes))
            {
              Cerr << "X = " << coupe << " is a boundary" << finl;
              exit();
            }
          int jmin, jmax;
          if (std::fabs(Origine(0) - coupe)<epsilon())
            i=0;
          else
            i=Nx;
          if(internes)
            for(i=0; coord_noeud(i,0,0)+epsilon()<coupe; i++) {};
          jmin=0;
          for(; coord_noeud(0,jmin,1)+epsilon()<xmin; jmin++) {};
          if(std::fabs(xmax-(Origine(1)+Longueurs(1)))<epsilon())
            {
              assert(tour_complet!=-123);
              jmax=My-1+tour_complet;
            }
          else
            {
              jmax = jmin;
              for(; coord_noeud(0,jmax,1)+epsilon()<xmax; jmax++) {};
// if(jmax-jmin==0)
// {
// Cerr << "le bord de nom " << nom_front << "est vide !" << finl;
// exit();
// }
            }
          som.resize(jmax-jmin,2);
          for(j=jmin; j<jmax; j++)
            {
              som(j-jmin,0)=numero_sommet(i, j);
              som(j-jmin,1)=numero_sommet(i, j+1);
            }
        }
      else
        {
          if (axi)
            {
              double deux_pi=M_PI*2.0 ;
              coupe*=deux_pi;
            }
          if ( (std::fabs(Origine(1) - coupe)>epsilon()) &&
               (std::fabs(coupe - Origine(1)-Longueurs(1))>epsilon()) && (!internes))
            {
              Cerr << "Y = " << coupe << " is not a boundary" << finl;
              exit();
            }
          if ( ((std::fabs(Origine(1) - coupe)<epsilon()) ||
                (std::fabs(coupe - Origine(1)-Longueurs(1))<epsilon())) && (internes))
            {
              Cerr << "Y = " << coupe <<" is a boundary" << finl;
              exit();
            }
          int imin, imax;
          if (std::fabs(coupe-Origine(1))<epsilon())
            j=0;
          else
            j=Ny;
          if(internes)
            for(j=0; coord_noeud(0,j,1)+epsilon()<coupe; j++) {};
          imin=0;
          for(; coord_noeud(imin,0,0)+epsilon()<xmin; imin++) {};
          if(std::fabs(xmax-(Origine(0)+Longueurs(0)))<epsilon())
            imax=Mx-1;
          else
            {
              imax = imin;
              for(; coord_noeud(imax,0,0)+epsilon()<xmax; imax++) {};
// if(imax-imin==0)
// {
// Cerr << "le bord de nom " << nom_front << "est vide !" << finl;
// exit();
// }
            }
          som.resize(imax-imin,2);
          for(i=imin; i<imax; i++)
            {
              som(i-imin,0)=numero_sommet(i, j);
              som(i-imin,1)=numero_sommet(i+1, j);
            }
        }
      front.ajouter_faces(som);
      front.associer_zone(*this);
    }
  else if(dimension==3)
    {
      Nom  X, Y, Z, egal, infegal1, infegal2, infegal3, infegal4;
      double coupe;
      double xmin, xmax, ymin, ymax;
      is  >> X >> egal >> coupe ;
      if( (X!="X") && (X!="Y") && (X!="Z"))
        {
          Cerr << "We expected a = X or Y or Z instead of" << X  <<
               " before " << egal << " " << coupe << finl;
          exit();
        }
      if( egal!="=")
        {
          Cerr << "We expected a = after " << X << finl;
          exit();
        }
      is >> xmin >> infegal1 >> Y >> infegal2 >> xmax;
      if( infegal1!="<=")
        {
          Cerr << "We expected a <= after " << xmin << " and not " << infegal1 <<finl;
          exit();
        }
      if( infegal2!="<=")
        {
          Cerr << "We expected a <= after " << Y << " and not " << infegal2 << finl;
          exit();
        }
      is >> ymin >> infegal3 >> Z >> infegal4 >> ymax;
      if( infegal3!="<=")
        {
          Cerr << "We expected a <= after " << ymin << " and not " << infegal3 << finl;
          exit();
        }
      if( infegal4!="<=")
        {
          Cerr << "We expected a <= after " << Z << " and not " << infegal4 << finl;
          exit();
        }
      if (X=="X")
        {
          if( Y!="Y" )
            {
              Cerr << "We expected a Y and not " << Y  << finl;
              exit();
            }
          if (axi)
            {
              double deux_pi=M_PI*2.0 ;
              xmin*=deux_pi;
              xmax*=deux_pi;
            }
          if( Z!="Z")
            {
              Cerr << "We expected a Z and not " << Z  << finl;
              exit();
            }
        }
      else if(X=="Y")
        {
          assert(tour_complet!=-123);
          if(tour_complet)
            {
              Cerr << "There is no boundary in teta! " << finl;
              Cerr << "You have meshed a complete crown! " << finl;
              exit();
            }
          if( Y!="X" )
            {
              Cerr << "We expected a X and not " << Y  << finl;
              exit();
            }
          if( Z!="Z")
            {
              Cerr << "We expected a Z and not " << Z  << finl;
              exit();
            }
        }
      else
        {
          if( Y!="X" )
            {
              Cerr << "We expected a X and not " << Y  << finl;
              exit();
            }
          if( Z!="Y" )
            {
              Cerr << "We expected a Z and not " << Z  << finl;
              exit();
            }
          if (axi)
            {
              double deux_pi=M_PI*2.0 ;
              ymin*=deux_pi;
              ymax*=deux_pi;
            }
        }
      front.dimensionner(0);
      IntTab som;
      if (X=="X")
        {
          if ( (std::fabs(Origine(0)-coupe)>epsilon()) &&
               (std::fabs(Origine(0)+Longueurs(0)-coupe)>epsilon()) && (!internes) )
            {
              Cerr << "X = " << coupe << " is not a boundary " << finl;
              exit();
            }
          if ( ((std::fabs(Origine(0)-coupe)<epsilon()) ||
                (std::fabs(Origine(0)+Longueurs(0)-coupe)<epsilon())) && (internes) )
            {
              Cerr << "X = " << coupe << " is a boundary " << finl;
              exit();
            }
          int jmin, jmax, kmin, kmax;
          if (std::fabs(Origine(0)-coupe)<epsilon())
            i=0;
          else
            i=Nx;
          if(internes)
            for(i=0; coord_noeud(i,0,0,0)+epsilon()<coupe; i++) {};
          jmin=kmin=0;
          for(; coord_noeud(0,jmin,0,1)+epsilon()<xmin; jmin++) {};
          for(; coord_noeud(0,0,kmin,2)+epsilon()<ymin; kmin++) {};
          jmax = jmin;
          kmax=kmin;
          if(std::fabs(xmax-(Origine(1)+Longueurs(1)))<epsilon())
            {
              assert(tour_complet!=-123);
              jmax=My-1+tour_complet;
            }
          else
            for(; coord_noeud(0,(jmax),0,1)+epsilon()<xmax; jmax++) {};
          for(; coord_noeud(0,0,(kmax),2)+epsilon()<ymax; kmax++) {};
// if((jmax-jmin)*(kmax-kmin)==0)
// {
// Cerr << "le bord de nom " << nom_front << "est vide !" << finl;
// exit();
// }
          som.resize((jmax-jmin)*(kmax-kmin),4);
          for(j=jmin; j<jmax; j++)
            for(k=kmin; k<kmax; k++)
              {
                som((k-kmin)*(jmax-jmin)+j-jmin,0)=numero_sommet(i, j, k);
                som((k-kmin)*(jmax-jmin)+j-jmin,1)=numero_sommet(i, j+1, k);
                som((k-kmin)*(jmax-jmin)+j-jmin,2)=numero_sommet(i, j, k+1);
                som((k-kmin)*(jmax-jmin)+j-jmin,3)=numero_sommet(i, j+1, k+1);
              }
        }
      else if(X=="Y")
        {
          if (axi)
            {
              double deux_pi=M_PI*2.0 ;
              coupe*=deux_pi;
            }
          if ( (std::fabs(Origine(1) - coupe)>epsilon()) &&
               (std::fabs(coupe - Origine(1)-Longueurs(1))>epsilon()) && (!internes)        )
            {
              Cerr << "Y = " << coupe << " is not a boundary " << finl;
              exit();
            }
          if ( ((std::fabs(Origine(1) - coupe)<epsilon()) ||
                (std::fabs(coupe - Origine(1)-Longueurs(1))<epsilon())) && (internes)        )
            {
              Cerr << "Y = " << coupe << " is a boundary " << finl;
              exit();
            }
          int imin, imax, kmin, kmax;
          if (std::fabs(coupe-Origine(1))<epsilon())
            j=0;
          else
            j=Ny;
          if(internes)
            for(j=0; coord_noeud(0,j,0,1)+epsilon()<coupe; j++) {};
          imin=kmin=0;
          for(; coord_noeud(imin,0,0,0)+epsilon()<xmin; imin++) {};
          for(; coord_noeud(0,0,kmin,2)+epsilon()<ymin; kmin++) {};
          imax = imin;
          kmax=kmin;
          for(; coord_noeud(imax,0,0,0)+epsilon()<xmax; imax++) {};
          for(; coord_noeud(0,0,(kmax),2)+epsilon()<ymax; kmax++) {};
// if((imax-imin)*(kmax-kmin)==0)
// {
// Cerr << "le bord de nom " << nom_front << "est vide !" << finl;
// exit();
// }
          som.resize((imax-imin)*(kmax-kmin),4);
          for(i=imin; i<imax; i++)
            for(k=kmin; k<kmax; k++)
              {
                som((k-kmin)*(imax-imin)+i-imin,0)=numero_sommet(i, j, k);
                som((k-kmin)*(imax-imin)+i-imin,1)=numero_sommet(i+1, j, k);
                som((k-kmin)*(imax-imin)+i-imin,2)=numero_sommet(i, j, k+1);
                som((k-kmin)*(imax-imin)+i-imin,3)=numero_sommet(i+1, j, k+1);
              }
        }
      else
        {
          if ( (std::fabs(Origine(2)-coupe)>epsilon()) &&
               (std::fabs(coupe-Origine(2)-Longueurs(2))>epsilon()) && (!internes))
            {
              Cerr << "Z = " << coupe << " is not a boundary " << finl;
              exit();
            }
          if ( ((std::fabs(Origine(2)-coupe)<epsilon()) ||
                (std::fabs(coupe-Origine(2)-Longueurs(2))<epsilon())) && (internes))
            {
              Cerr << "Z = " << coupe << " is a boundary " << finl;
              exit();
            }
          int imin, imax, jmin, jmax;
          if (std::fabs(coupe-Origine(2))<epsilon())
            k=0;
          else
            k=Nz;
          if(internes)
            for(k=0; coord_noeud(0,0,k,3)+epsilon()<coupe; k++) {};
          imin=jmin=0;
          for(; coord_noeud(imin,0,0,0)+epsilon()<xmin; imin++) {};
          for(; coord_noeud(0,jmin,0,1)+epsilon()<ymin; jmin++) {};
          imax = imin;
          jmax=jmin;
          for(; coord_noeud(imax,0,0,0)+epsilon()<xmax; imax++) {};
          if(std::fabs(ymax-(Origine(1)+Longueurs(1)))<epsilon())
            {
              assert(tour_complet!=-123);
              jmax=My-1+tour_complet;
            }
          else
            for(; coord_noeud(0,jmax,0,1)+epsilon()<ymax; jmax++) {};
// if((imax-imin)*(jmax-jmin)==0)
// {
// Cerr << "le bord de nom " << nom_front << "est vide !" << finl;
// exit();
// }
          som.resize((imax-imin)*(jmax-jmin),4);
          for(i=imin; i<imax; i++)
            for(j=jmin; j<jmax; j++)
              {
                som((j-jmin)*(imax-imin)+i-imin,0)=numero_sommet(i, j, k);
                som((j-jmin)*(imax-imin)+i-imin,1)=numero_sommet(i+1, j, k);
                som((j-jmin)*(imax-imin)+i-imin,2)=numero_sommet(i, j+1, k);
                som((j-jmin)*(imax-imin)+i-imin,3)=numero_sommet(i+1, j+1, k);
              }
        }
      front.ajouter_faces(som);
      front.associer_zone(*this);
    }
  else
    {
      exit();
    }
  Cerr << "End of reading of the boundary : " << nom_front << finl;
}
References Frontiere::ajouter_faces(), Frontiere::associer_zone(), Objet_U::axi, Cerr, coord_noeud(), Objet_U::dimension, Frontiere::dimensionner(), Zone::elem, Zone::epsilon(), Process::exit(), finl, Longueurs, M_PI, Mx, My, Frontiere::nommer(), numero_sommet(), Nx, Ny, Nz, Origine, TRUSTTab< _TYPE_ >::resize(), sub_type, tour_complet, Elem_geom::type_face(), and Frontiere::typer_faces().
Referenced by readOn().
lire_Longueurs()
void Pave::lire_Longueurs (Entree & is)
Lit les longueurs LX LY [LZ] du jeu de donnee
a partir d'un flot d'entree.
Methode appelee par readOn(Entree&)
Definition at line 1381 of file Pave.cpp.
{
  int i;
  for(i=0; i< dimension; i++)
    is >> Longueurs(i);
  if(axi)
    {
      if(Longueurs(1) >1.+epsilon())
        {
          Cerr << "The length \"Longueurs\" is in number of turns in axisymmetric" << finl;
          Cerr << "It must be between 0 and 1" << finl;
          exit();
        }
      else if(Longueurs(1)==1.)
        tour_complet=1;
    }
}
References Objet_U::axi, Cerr, Objet_U::dimension, Zone::epsilon(), Process::exit(), finl, Longueurs, and tour_complet.
Referenced by readOn().
lire_Noeuds()
void Pave::lire_Noeuds (Entree & is)
Lit le nombre de noeuds dans le jeu de donnee
a partir d'un flot d'entree et construit les noeuds.
Methode appelee par readOn(Entree&)
Definition at line 1416 of file Pave.cpp.
{
  int i, j, k;
  if( (axi) && (Longueurs(0)==0.))
    {
      Cerr<< "You must first read the length in axisymmetric!" << finl;
      exit();
    }
  for(i=0; i< dimension; i++)
    is >> Nb_Noeuds(i);
  if (min_array(Nb_Noeuds)<2)
    {
      Cerr << "\nError: The number of nodes in directions Nx and Ny (and Nz) for 'Pave " << nom << "' must be greater than 1." << finl;
      Cerr << "If you want to define a unique cell in a given direction, set the number of nodes to 2 in that direction." << finl;
      exit();
    }
  if(dimension==1)
    {
      Mx=Nb_Noeuds(0);
      Nx=Nb_Noeuds(0)-1;
      mes_elems.resize(Nx,2);
      Les_Noeuds.resize(Mx);
      for (i=0; i<Nx; i++)
        {
          maille_sommet(i,0)=numero_sommet(i);
          maille_sommet(i,1)=numero_sommet(i+1);
        }
    }
  else if(dimension==2)
    {
      Mx=Nb_Noeuds(0);
      My=Nb_Noeuds(1);
      Nx=Nb_Noeuds(0)-1;
      Ny=Nb_Noeuds(1)-1;
      assert(tour_complet!=-123);
      if(tour_complet) Ny++;
      mes_elems.resize(Nx*Ny,4);
      Les_Noeuds.resize(Mx*My,2);
      for (i=0; i<Nx; i++)
        for (j=0; j<Ny; j++)
          {
            maille_sommet(i,j,0)=numero_sommet(i, j);
            maille_sommet(i,j,1)=numero_sommet(i+1, j);
            maille_sommet(i,j,2)=numero_sommet(i, j+1);
            maille_sommet(i,j,3)=numero_sommet(i+1, j+1);
          }
    }
  else if(dimension==3)
    {
      Mx=Nb_Noeuds(0);
      My=Nb_Noeuds(1);
      Mz=Nb_Noeuds(2);
      Nx=Nb_Noeuds(0)-1;
      Ny=Nb_Noeuds(1)-1;
      Nz=Nb_Noeuds(2)-1;
      assert(tour_complet!=-123);
      if(tour_complet) Ny++;
      mes_elems.resize(Nx*Ny*Nz,8);
      Les_Noeuds.resize(Mx*My*Mz,3);
      for (i=0; i<Nx; i++)
        for ( j=0; j<Ny; j++)
          for ( k=0; k<Nz; k++)
            {
              maille_sommet(i,j,k,0)=numero_sommet(i, j, k);
              maille_sommet(i,j,k,1)=numero_sommet(i+1, j, k);
              maille_sommet(i,j,k,2)=numero_sommet(i, j+1, k);
              maille_sommet(i,j,k,3)=numero_sommet(i+1, j+1, k);
              maille_sommet(i,j,k,4)=numero_sommet(i, j, k+1);
              maille_sommet(i,j,k,5)=numero_sommet(i+1, j, k+1);
              maille_sommet(i,j,k,6)=numero_sommet(i, j+1, k+1);
              maille_sommet(i,j,k,7)=numero_sommet(i+1, j+1, k+1);
            }
    }
  else
    {
      Cerr << "dimension = " << dimension << "not provided " << finl;
      exit();
    }
}
References Objet_U::axi, Cerr, Objet_U::dimension, Process::exit(), finl, Les_Noeuds, Longueurs, maille_sommet(), Zone::mes_elems, min_array(), Mx, My, Mz, Nb_Noeuds, Zone::nom, numero_sommet(), Nx, Ny, Nz, TRUSTTab< _TYPE_ >::resize(), and tour_complet.
Referenced by readOn().
maille1D()
void Pave::maille1D ()
Effectue un maillage 1D, du pave
avec les valeurs des parametres lus par ReadOn.
Definition at line 538 of file Pave.cpp.
{
  Cerr << "Step of 1D mesh in progress... " << finl;
  double epsilon_geom=Objet_U::precision_geom;
  int i;
  if(Longueurs(0)<0)
    {
      Origine(0)+=Longueurs(0);
      Longueurs(0)=-Longueurs(0);
      Facteurs(0)=1./Facteurs(0);
    }
  if( (!Symetrique(0)) || (std::fabs(Facteurs(0)-1.)<epsilon_geom)   )
    {
      if(std::fabs(Facteurs(0)-1.)>epsilon_geom)
        Pas(0)=Longueurs(0)*(Facteurs(0)-1)/(pow(Facteurs(0),Nx)-1);
      else
        Pas(0)=Longueurs(0)/Nx;
      double dx=Pas(0);
      double x=Origine(0);
      for (i=0; i<Nx; i++)
        {
          coord_noeud(i)=x;
          x+=dx;
          dx*=Facteurs(0);
        }
      coord_noeud(Nx)=Origine(0)+Longueurs(0);
    }
  else
    {
      int Ix=Nx/2;
      if( (Ix*2)==Nx )
        Pas(0)=0.5*Longueurs(0)*(Facteurs(0)-1)/(pow(Facteurs(0),Ix)-1);
      else
        {
          if(Ix)
            {
              Ix+=1;
              Pas(0)=0.5*Longueurs(0)/( (pow(Facteurs(0),Ix-1)-1)/(Facteurs(0)-1)
                                        +0.5*pow(Facteurs(0),Ix) );
            }
          else
            {
              Ix+=1;
              Pas(0)=0;
            }
        }
      double dx=Pas(0);
      double x=0;
      for (i=0; i<Ix; i++)
        {
          coord_noeud(i)=Origine(0)+x;
          coord_noeud(Nx-i)=Origine(0)+Longueurs(0)-x;
          x+=dx;
          dx*=Facteurs(0);
        }
      if( (Ix*2)==Nx )
        coord_noeud(Ix)=0.5*(coord_noeud(Ix+1)+coord_noeud(Ix-1));
    }
  Cerr << finl;
  Cerr << "Step of mesh ended " << finl;
}
References Cerr, coord_noeud(), Facteurs, finl, Longueurs, Nx, Origine, Pas, Objet_U::precision_geom, and Symetrique.
Referenced by readOn().
maille2D()
void Pave::maille2D ()
Effectue un maillage 2D, du pave
avec les valeurs des parametres lus par ReadOn.
!< Maillage en x en tanh
!< Maillage en y en tanh
Definition at line 616 of file Pave.cpp.
{
  Cerr << "Step of 2D mesh in progress... " << finl;
  double epsilon_geom=Objet_U::precision_geom;
  int i, j;
  int pourcent=0;
  int tmp;
  if(Longueurs(0)<0)
    {
      Origine(0)+=Longueurs(0);
      Longueurs(0)=-Longueurs(0);
      Facteurs(0)=1./Facteurs(0);
    }
  if(Longueurs(1)<0)
    {
      Origine(1)+=Longueurs(1);
      Longueurs(1)=-Longueurs(1);
      Facteurs(1)=1./Facteurs(1);
    }
  if( (!Symetrique(0)) || (std::fabs(Facteurs(0)-1.)<epsilon_geom) )
    {
      assert(!est_egal(xa_tanh,-123.));
      if ((xa_tanh>epsilon_geom)&&(xa_tanh<1.) )
        {
          ///!<  Maillage en x en tanh
          Cerr << "In if( (xa_tanh>epsilon_geom)&&(xa_tanh<1.) )" << finl;
          pourcent =0;
          double fac_sym;
          assert(xtanh_dilatation!=-123);
          if (xtanh_dilatation != 0)
            fac_sym=1.;
          else
            fac_sym=2.;
          if (xtanh_dilatation != -1 )
            {
              for (i=0; i<Mx; i++)
                {
                  Cerr << "i=" << i << finl;
                  tmp=(i*100)/Mx;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordx" << flush;
                    }
                  assert(!est_egal(xa_tanh,-123.));
                  for (j=0; j<My; j++)
                    coord_noeud(i,j,0)=Origine(0)+Longueurs(0)/fac_sym*(1.+tanh((-1.+fac_sym*i/((Mx-1)*1.))*atanh(xa_tanh))/xa_tanh);
                  Cerr << "coord_noeud(0,j,1)=" << coord_noeud(0,j,0) << finl;
                  Cerr << "It was created " << pourcent << "% of coordx" << flush;
                }
            }
          else
            {
              for (i=0; i<Mx; i++)
                {
                  Cerr << "i=" << i << finl;
                  tmp=(i*100)/Mx;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordx" << flush;
                    }
                  assert(!est_egal(xa_tanh,-123.));
                  for (j=0; j<My; j++)
                    coord_noeud(i,j,0)=Origine(0)+Longueurs(0)-Longueurs(0)/fac_sym*(1.+tanh((-1.+fac_sym*(Mx-1-i)/((Mx-1)*1.))*atanh(xa_tanh))/xa_tanh);
                  Cerr << "coord_noeud(0,j,0)=" << coord_noeud(0,j,0) << finl;
                  Cerr << "It was created " << pourcent << "% of coordx" << flush;
                }
            }
//
          for (j=0; j<My; j++)
            coord_noeud(0,j,0)=Origine(0);
        }
      else
        {
          double x;
          for (i=0; i<Nx; i++)
            {
              tmp=(i*100)/Nx;
              if(tmp > pourcent)
                {
                  pourcent=tmp;
                  Cerr << "It was created " << pourcent << "% of coordx" << flush;
                }
              if (std::fabs(Facteurs(0)-1.)>epsilon_geom)
                x=Origine(0)+Longueurs(0)*(pow(Facteurs(0),i)-1)/(pow(Facteurs(0),Nx)-1);
              else
                x=Origine(0)+Longueurs(0)*i/Nx;
              for (j=0; j<My; j++)
                coord_noeud(i,j,0)=x;
            }
          for (j=0; j<My; j++)
            coord_noeud(Nx,j,0)=Origine(0)+Longueurs(0);
        }
    }
  else
    {
      int Ix=Nx/2;
      if( (Ix*2)==Nx )
        Pas(0)=0.5*Longueurs(0)*(Facteurs(0)-1)/(pow(Facteurs(0),Ix)-1);
      else
        {
          if(Ix)
            {
              Ix+=1;
              Pas(0)=0.5*Longueurs(0)/( (pow(Facteurs(0),Ix-1)-1)/(Facteurs(0)-1)
                                        +0.5*pow(Facteurs(0),Ix) );
            }
          else
            {
              Ix+=1;
              Pas(0)=Longueurs(0);
            }
        }
      double dx=Pas(0);
      double x=0;
      for (i=0; i<Ix; i++)
        {
          tmp=(i*100)/Ix;
          if(tmp > pourcent)
            {
              pourcent=tmp;
              Cerr << "It was created " << pourcent << "% of coordx" << flush;
            }
          for (j=0; j<My; j++)
            {
              coord_noeud(i,j,0)=Origine(0)+x;
              coord_noeud(Nx-i,j,0)=Origine(0)+Longueurs(0)-x;
            }
          x+=dx;
          dx*=Facteurs(0);
        }
      if( (Ix*2)==Nx )
        for (j=0; j<My; j++)
          coord_noeud(Ix,j,0)=0.5*(coord_noeud(Ix+1,j,0)
                                   +coord_noeud(Ix-1,j,0));
    }
  pourcent=0;
//
  if( (!Symetrique(1)) || (std::fabs(Facteurs(1)-1.)<epsilon_geom) )
    {
      assert(!est_egal(a_tanh,-123.));
      if ((a_tanh>epsilon_geom)&&(a_tanh<1.) )
        {
          ///!<  Maillage en y en tanh
          Cerr << "In if( (a_tanh>epsilon_geom)&&(a_tanh<1.) )" << finl;
          pourcent =0;
          double fac_sym;
          assert(tanh_dilatation!=-123);
          if (tanh_dilatation != 0)
            fac_sym=1.;
          else
            fac_sym=2.;
          if (tanh_dilatation != -1 )
            {
              for (j=0; j<My; j++)
                {
                  Cerr << "j=" << j << finl;
                  tmp=(j*100)/My;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordy" << flush;
                    }
                  assert(!est_egal(a_tanh,-123.));
                  for (i=0; i<Mx; i++)
                    coord_noeud(i,j,1)=Origine(1)+Longueurs(1)/fac_sym*(1.+tanh((-1.+fac_sym*j/((My-1)*1.))*atanh(a_tanh))/a_tanh);
                  Cerr << "coord_noeud(0,j,1)=" << coord_noeud(0,j,1) << finl;
                  Cerr << "It was created " << pourcent << "% of coordy" << flush;
                }
            }
          else
            {
              for (j=0; j<My; j++)
                {
                  Cerr << "j=" << j << finl;
                  tmp=(j*100)/My;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordy" << flush;
                    }
                  assert(!est_egal(a_tanh,-123.));
                  for (i=0; i<Mx; i++)
                    coord_noeud(i,j,1)=Origine(1)+Longueurs(1)-Longueurs(1)/fac_sym*(1.+tanh((-1.+fac_sym*(My-1-j)/((My-1)*1.))*atanh(a_tanh))/a_tanh);
                  Cerr << "coord_noeud(0,j,1)=" << coord_noeud(0,j,1) << finl;
                  Cerr << "It was created " << pourcent << "% of coordy" << flush;
                }
            }
//
          for (i=0; i<Mx; i++)
            coord_noeud(i,0,1)=Origine(1);
        }
      else
        {
          double y;
          for (j=0; j<Ny; j++)
            {
              tmp=(j*100)/Ny;
              if(tmp > pourcent)
                {
                  pourcent=tmp;
                  Cerr << "It was created " << pourcent << "% of coordy" << flush;
                }
              if (std::fabs(Facteurs(1)-1.)>epsilon_geom)
                y=Origine(1)+Longueurs(1)*(pow(Facteurs(1),j)-1)/(pow(Facteurs(1),Ny)-1);
              else
                y=Origine(1)+Longueurs(1)*j/Ny;
              for (i=0; i<Mx; i++)
                coord_noeud(i,j,1)=y;
            }
          for (i=0; i<Mx; i++)
            coord_noeud(i,j,1)=Origine(1)+Longueurs(1);
        }
    }
  else
    {
      int Iy=Ny/2;
      if( (Iy*2)==Ny )
        Pas(1)=0.5*Longueurs(1)*(Facteurs(1)-1)/(pow(Facteurs(1),Iy)-1);
      else
        {
          if(Iy)
            {
              Iy+=1;
              Pas(1)=0.5*Longueurs(1)/( (pow(Facteurs(1),Iy-1)-1)/(Facteurs(1)-1)
                                        +0.5*pow(Facteurs(1),Iy) );
            }
          else
            {
              Iy+=1;
              Pas(1)=Longueurs(1);
            }
        }
      double dy=Pas(1);
      double y=0;
      for (j=0; j<Iy; j++)
        {
          tmp=(j*100)/Iy;
          if(tmp > pourcent)
            {
              pourcent=tmp;
              Cerr << "It was created " << pourcent << "% of coordy" << flush;
            }
          for (i=0; i<Mx; i++)
            {
              coord_noeud(i,j,1)=Origine(1)+y;
              coord_noeud(i,Ny-j,1)=Origine(1)+Longueurs(1)-y;
            }
          y+=dy;
          dy*=Facteurs(1);
        }
      if( (Iy*2)==Ny )
        for (i=0; i<Mx; i++)
          coord_noeud(i,Iy,1)=0.5*(coord_noeud(i,Iy-1,1)
                                   +coord_noeud(i,Iy+1,1));
    }
  Cerr << finl;
  Cerr << "Step of mesh ended " << finl;
}
References a_tanh, Cerr, coord_noeud(), est_egal(), Facteurs, finl, Longueurs, Mx, My, Nx, Ny, Origine, Pas, Objet_U::precision_geom, Symetrique, tanh_dilatation, xa_tanh, and xtanh_dilatation.
Referenced by readOn().
maille3D()
void Pave::maille3D ()
Effectue un maillage 3D, du pave
avec les valeurs des parametres lus par ReadOn.
!< Maillage en x en tanh
!< Maillage en y en tanh
!< Maillage en z en tanh
Definition at line 894 of file Pave.cpp.
{
  Cerr << "Step of 3D mesh in progress... " << finl;
  double epsilon_geom=Objet_U::precision_geom;
  int i, j, k;
  int pourcent=0;
  int tmp;
  if(Longueurs(0)<0)
    {
      Origine(0)+=Longueurs(0);
      Longueurs(0)=-Longueurs(0);
      Facteurs(0)=1./Facteurs(0);
    }
  if(Longueurs(1)<0)
    {
      Origine(1)+=Longueurs(1);
      Longueurs(1)=-Longueurs(1);
      Facteurs(1)=1./Facteurs(1);
    }
  if(Longueurs(2)<0)
    {
      Origine(2)+=Longueurs(2);
      Longueurs(2)=-Longueurs(2);
      Facteurs(2)=1./Facteurs(2);
    }
  if( (!Symetrique(0)) || (std::fabs(Facteurs(0)-1.)<epsilon_geom) )
    {
      assert(!est_egal(xa_tanh,-123.));
      if ((xa_tanh>epsilon_geom)&&(xa_tanh<1.) )
        {
          ///!<  Maillage en x en tanh
          Cerr << "In if( (xa_tanh>epsilon)&&(xa_tanh<1.) )" << finl;
          pourcent =0;
          double fac_sym;
          assert(xtanh_dilatation!=-123);
          if (xtanh_dilatation != 0)
            fac_sym=1.;
          else
            fac_sym=2.;
          if (xtanh_dilatation != -1 )
            {
              for (i=0; i<Mx; i++)
                {
                  Cerr << "i=" << i << finl;
                  tmp=(i*100)/Mx;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordx" << flush;
                    }
                  assert(!est_egal(xa_tanh,-123.));
                  for (j=0; j<My; j++)
                    for (k=0; k<Mz; k++)
                      coord_noeud(i,j,k,0)=Origine(0)+Longueurs(0)/fac_sym*(1.+tanh((-1.+fac_sym*i/((Mx-1)*1.))*atanh(xa_tanh))/xa_tanh);
                  Cerr << "coord_noeud(i,0,0,0)=" << coord_noeud(i,0,0,0) << finl;
                }
            }
          else
            {
              for (i=0; i<Mx; i++)
                {
                  Cerr << "i=" << i << finl;
                  tmp=(i*100)/Mx;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "It was created " << pourcent << "% of coordx" << flush;
                    }
                  assert(!est_egal(xa_tanh,-123.));
                  for (j=0; j<My; j++)
                    for (k=0; k<Mz; k++)
                      coord_noeud(i,j,k,0)=Origine(0)+Longueurs(0)-Longueurs(0)/fac_sym*(1.+tanh((-1.+fac_sym*(Mx-1-i)/((Mx-1)*1.))*atanh(xa_tanh))/xa_tanh);
                  Cerr << "coord_noeud(i,0,0,0)=" << coord_noeud(i,0,0,0) << finl;
                }
            }
          for (j=0; j<My; j++)
            for (k=0; k<Mz; k++)
              coord_noeud(0,j,k,0)=Origine(0);
        }
//
      else
        {
          double x;
          for (i=0; i<Nx; i++)
            {
              tmp=(i*100)/Nx;
              if(tmp > pourcent)
                {
                  pourcent=tmp;
                  Cerr << "It was created " << pourcent << "% of coordx" << flush;
                }
              if(std::fabs(Facteurs(0)-1.)>epsilon_geom)
                x=Origine(0)+Longueurs(0)*(pow(Facteurs(0),i)-1)/(pow(Facteurs(0),Nx)-1);
              else
                x=Origine(0)+Longueurs(0)*i/Nx;
              for (j=0; j<My; j++)
                for (k=0; k<Mz; k++)
                  coord_noeud(i,j,k,0)=x;
            }
          for (j=0; j<My; j++)
            for (k=0; k<Mz; k++)
              coord_noeud(Nx,j,k,0)=Origine(0)+Longueurs(0);
        }
    }
  else
    {
      int Ix=Nx/2;
      if( (Ix*2)==Nx )
        Pas(0)=0.5*Longueurs(0)*(Facteurs(0)-1)/(pow(Facteurs(0),Ix)-1);
      else
        {
          if(Ix)
            {
              Ix+=1;
              Pas(0)=0.5*Longueurs(0)/( (pow(Facteurs(0),Ix-1)-1)/(Facteurs(0)-1)
                                        +0.5*pow(Facteurs(0),Ix) );
            }
          else
            {
              Ix+=1;
              Pas(0)=Longueurs(0);
            }
        }
      double dx=Pas(0);
      double x=0;
      for (i=0; i<Ix; i++)
        {
          tmp=(i*100)/Ix;
          if(tmp > pourcent)
            {
              pourcent=tmp;
              Cerr << "It was created " << pourcent << "% of coordx" << flush;
            }
          for (j=0; j<My; j++)
            for (k=0; k<Mz; k++)
              {
                coord_noeud(i,j,k,0)=Origine(0)+x;
                coord_noeud(Nx-i,j,k,0)=Origine(0)+Longueurs(0)-x;
              }
          x+=dx;
          dx*=Facteurs(0);
        }
      if( (Ix*2)==Nx )
        for (j=0; j<My; j++)
          for (k=0; k<Mz; k++)
            coord_noeud(Ix,j,k,0)=0.5*(coord_noeud(Ix+1,j,k,0)+
                                       coord_noeud(Ix-1,j,k,0));
    }
//
  pourcent=0;
  Cerr << finl;
  if( (!Symetrique(1)) || (std::fabs(Facteurs(1)-1.)<epsilon_geom) )
    {
      assert(!est_egal(a_tanh,-123.));
      if ((a_tanh>epsilon_geom)&&(a_tanh<1.) )
        {
          ///!<  Maillage en y en tanh
          Cerr << "In if( (a_tanh>epsilon)&&(a_tanh<1.) )" << finl;
          pourcent =0;
          double fac_sym;
          assert(tanh_dilatation!=-123);
          if (tanh_dilatation != 0)
            fac_sym=1.;
          else
            fac_sym=2.;
          if (tanh_dilatation != -1 )
            {
              for (j=0; j<My; j++)
                {
                  Cerr << "j=" << j << finl;
                  tmp=(j*100)/My;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordy" << flush;
                    }
                  assert(!est_egal(a_tanh,-123.));
                  for (i=0; i<Mx; i++)
                    for (k=0; k<Mz; k++)
                      coord_noeud(i,j,k,1)=Origine(1)+Longueurs(1)/fac_sym*(1.+tanh((-1.+fac_sym*j/((My-1)*1.))*atanh(a_tanh))/a_tanh);
                  Cerr << "coord_noeud(0,j,0,1)=" << coord_noeud(0,j,0,1) << finl;
                }
            }
          else
            {
              for (j=0; j<My; j++)
                {
                  Cerr << "j=" << j << finl;
                  tmp=(j*100)/My;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "It was created " << pourcent << "% of coordy" << flush;
                    }
                  assert(!est_egal(a_tanh,-123.));
                  for (i=0; i<Mx; i++)
                    for (k=0; k<Mz; k++)
                      coord_noeud(i,j,k,1)=Origine(1)+Longueurs(1)-Longueurs(1)/fac_sym*(1.+tanh((-1.+fac_sym*(My-1-j)/((My-1)*1.))*atanh(a_tanh))/a_tanh);
                  Cerr << "coord_noeud(0,j,0,1)=" << coord_noeud(0,j,0,1) << finl;
                }
            }
          for (i=0; i<Mx; i++)
            for (k=0; k<Mz; k++)
              coord_noeud(i,0,k,1)=Origine(1);
        }
//
      else
        {
          double y;
          for (j=0; j<Ny; j++)
            {
              tmp=(j*100)/Ny;
              if(tmp > pourcent)
                {
                  pourcent=tmp;
                  Cerr << "It was created " << pourcent << "% of coordy" << flush;
                }
              if(std::fabs(Facteurs(1)-1.)>epsilon_geom)
                y=Origine(1)+Longueurs(1)*(pow(Facteurs(1),j)-1)/(pow(Facteurs(1),Ny)-1);
              else
                y=Origine(1)+Longueurs(1)*j/Ny;
              for (i=0; i<Mx; i++)
                for (k=0; k<Mz; k++)
                  coord_noeud(i,j,k,1)=y;
            }
          for (i=0; i<Mx; i++)
            for (k=0; k<Mz; k++)
              coord_noeud(i,j,k,1)=Origine(1)+Longueurs(1);
        }
    }
  else
    {
      int Iy=Ny/2;
      if( (Iy*2)==Ny )
        Pas(1)=0.5*Longueurs(1)*(Facteurs(1)-1)/(pow(Facteurs(1),Iy)-1);
      else
        {
          if(Iy)
            {
              Iy+=1;
              Pas(1)=0.5*Longueurs(1)/( (pow(Facteurs(1),Iy-1)-1)/(Facteurs(1)-1)
                                        +0.5*pow(Facteurs(1),Iy) );
            }
          else
            {
              Iy+=1;
              Pas(1)=Longueurs(1);
            }
        }
      double dy=Pas(1);
      double y=0;
      for (j=0; j<Iy; j++)
        {
          tmp=(j*100)/Iy;
          if(tmp > pourcent)
            {
              pourcent=tmp;
              Cerr << "It was created " << pourcent << "% of coordy" << flush;
            }
          for (i=0; i<Mx; i++)
            for (k=0; k<Mz; k++)
              {
                coord_noeud(i,j,k,1)=Origine(1)+y;
                coord_noeud(i,Ny-j,k,1)=Origine(1)+Longueurs(1)-y;
              }
          y+=dy;
          dy*=Facteurs(1);
        }
      if( (Iy*2)==Ny )
        for (i=0; i<Mx; i++)
          for (k=0; k<Mz; k++)
            coord_noeud(i,Iy,k,1)=0.5*(coord_noeud(i,Iy-1,k,1)
                                       +coord_noeud(i,Iy+1,k,1));
    }
//
  pourcent=0;
  Cerr << finl;
  if( (!Symetrique(2)) ||( std::fabs(Facteurs(2)-1.)<epsilon_geom)    )
    {
      assert(!est_egal(za_tanh,-123.));
      if ((za_tanh>epsilon_geom)&&(za_tanh<1.) )
        {
          ///!<  Maillage en z en tanh
          Cerr << "In if( (za_tanh>epsilon)&&(za_tanh<1.) )" << finl;
          pourcent =0;
          double fac_sym;
          assert(ztanh_dilatation!=-123);
          if (ztanh_dilatation != 0)
            fac_sym=1.;
          else
            fac_sym=2.;
          if (ztanh_dilatation != -1 )
            {
              for (k=0; k<Mz; k++)
                {
                  Cerr << "k=" << k << finl;
                  tmp=(k*100)/Mz;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "\rIt was created " << pourcent << "% of coordz" << flush;
                    }
                  assert(!est_egal(za_tanh,-123.));
                  for (i=0; i<Mx; i++)
                    for (j=0; j<My; j++)
                      coord_noeud(i,j,k,2)=Origine(2)+Longueurs(2)/fac_sym*(1.+tanh((-1.+fac_sym*k/((Mz-1)*1.))*atanh(za_tanh))/za_tanh);
                  Cerr << "coord_noeud(0,0,k,2)=" << coord_noeud(0,0,k,2) << finl;
                }
            }
          else
            {
              for (k=0; k<Mz; k++)
                {
                  Cerr << "k=" << k << finl;
                  tmp=(k*100)/Mz;
                  if(tmp > pourcent)
                    {
                      pourcent=tmp;
                      Cerr << "It was created " << pourcent << "% of coordz" << flush;
                    }
                  assert(!est_egal(za_tanh,-123.));
                  for (i=0; i<Mx; i++)
                    for (j=0; j<My; j++)
                      coord_noeud(i,j,k,2)=Origine(2)+Longueurs(2)-Longueurs(2)/fac_sym*(1.+tanh((-1.+fac_sym*(Mz-1-k)/((Mz-1)*1.))*atanh(za_tanh))/za_tanh);
                  Cerr << "coord_noeud(0,0,k,2)=" << coord_noeud(0,0,k,2) << finl;
                }
            }
          for (i=0; i<Mx; i++)
            for (j=0; j<My; j++)
              coord_noeud(i,j,0,2)=Origine(2);
        }
//
      else
        {
          double z;
          for (k=0; k<Nz; k++)
            {
              tmp=(k*100)/Nz;
              if(tmp > pourcent)
                {
                  pourcent=tmp;
                  Cerr << "It was created " << pourcent << "% of coordz" << flush;
                }
              if(std::fabs(Facteurs(2)-1.)>epsilon_geom)
                z=Origine(2)+Longueurs(2)*(pow(Facteurs(2),k)-1)/(pow(Facteurs(2),Nz)-1);
              else
                z=Origine(2)+Longueurs(2)*k/Nz;
              for (i=0; i<Mx; i++)
                for (j=0; j<My; j++)
                  coord_noeud(i,j,k,2)=z;
            }
          for (i=0; i<Mx; i++)
            for (j=0; j<My; j++)
              coord_noeud(i,j,Nz,2)=Origine(2)+Longueurs(2);
        }
    }
  else
    {
      int Iz=Nz/2;
      if( (Iz*2)==Nz )
        Pas(2)=0.5*Longueurs(2)*(Facteurs(2)-1)/(pow(Facteurs(2),Iz)-1);
      else
        {
          if(Iz)
            {
              Iz+=1;
              Pas(2)=0.5*Longueurs(2)/( (pow(Facteurs(2),Iz-1)-1)/(Facteurs(2)-1)
                                        +0.5*pow(Facteurs(2),Iz) );
            }
          else
            {
              Iz+=1;
              Pas(2)=Longueurs(2);
            }
        }
      double dz=Pas(2);
      double z=0;
      for (k=0; k<Iz; k++)
        {
          tmp=(k*100)/Iz;
          if(tmp > pourcent)
            {
              pourcent=tmp;
              Cerr << "It was created " << pourcent << "% of coordz" << flush;
            }
          for (i=0; i<Mx; i++)
            for (j=0; j<My; j++)
              {
                coord_noeud(i,j,k,2)=Origine(2)+z;
                coord_noeud(i,j,Nz-k,2)=Origine(2)+Longueurs(2)-z;
              }
          z+=dz;
          dz*=Facteurs(2);
        }
      if( (Iz*2)==Nz )
        for (i=0; i<Mx; i++)
          for (j=0; j<My; j++)
            coord_noeud(i,j,Iz,2)=0.5*(coord_noeud(i,j,Iz+1,2)
                                       +coord_noeud(i,j,Iz-1,2));
    }
// PaQ : pour pouvoir passer d'un maillage VDF a VEF suivant tetraedriser homogene
  if(rep_VEF)
    {
      for (j=1; j<My; j+=2)
        for (i=0; i<Mx; i++)
          for (k=0; k<Mz; k++)
            coord_noeud(i,j,k,1)=coord_noeud(i,j-1,k,1)+0.5*(coord_noeud(i,j+1,k,1)-coord_noeud(i,j-1,k,1));
    }
  Cerr << finl;
  Cerr << "Step of mesh ended " << finl;
}
References a_tanh, Cerr, coord_noeud(), est_egal(), Facteurs, finl, Longueurs, Mx, My, Mz, Nx, Ny, Nz, Origine, Pas, Objet_U::precision_geom, rep_VEF, Symetrique, tanh_dilatation, xa_tanh, xtanh_dilatation, za_tanh, and ztanh_dilatation.
Referenced by readOn().
maille_sommet() [1/3]
int & Pave::maille_sommet (int i, int l) inline
Renvoie une reference sur le numero du l-ieme sommet
de la i-ieme maille (suivant X) du pave.
Returns
int&
Signification: reference sur le numero du sommet cherche
Contraintes:
Definition at line 317 of file Pave.h.
{
  assert(dimension == 1);
  return mes_elems(numero_maille(i),l);
}
References Objet_U::dimension, Zone::mes_elems, and numero_maille().
Referenced by lire_Noeuds().
maille_sommet() [2/3]
int & Pave::maille_sommet (int i, int j, int l) inline
Renvoie une reference sur le numero du l-ieme sommet
de la (i,j)-ieme maille (suivant (X,Y)) du pave.
Returns
int&
Signification: reference sur le numero du sommet cherche
Contraintes:
Definition at line 348 of file Pave.h.
{
  assert(dimension == 2);
  return mes_elems(numero_maille(i, j),l);
}
References Objet_U::dimension, Zone::mes_elems, and numero_maille().
maille_sommet() [3/3]
int & Pave::maille_sommet (int i, int j, int k, int l) inline
Renvoie une reference sur le numero du l-ieme sommet
de la (i,j,k)-ieme maille (suivant (X,Y,Z)) du pave.
Returns
int&
Signification: reference sur le numero du sommet cherche
Contraintes:
Definition at line 384 of file Pave.h.
{
  assert(dimension == 3);
  return mes_elems(numero_maille(i, j, k), l);
}
References Objet_U::dimension, Zone::mes_elems, and numero_maille().
Nb_Noeud()
IntVect & Pave::Nb_Noeud () inline
Renvoie le nombre de noeuds du pave dans
chacune des dimensions d'espace.
Returns
IntVect&
Signification: vecteur d'entier contenant
le nombre de noeud du pave suivant
X, Y et Z
Contraintes: taille du vecteur = dimension de l'espace
Definition at line 116 of file Pave.h.
{
  return Nb_Noeuds;
}
References Nb_Noeuds.
numero_maille() [1/3]
int Pave::numero_maille (int i) inline
Renvoie le numero de la i-ieme maille<br>(suivant X)
Returns
int
Signification: le numero de la maille cherchee
Contraintes:
Definition at line 138 of file Pave.h.
{
  assert(dimension == 1);
  assert(i < Nx);
  return i;
}
References Objet_U::dimension, and Nx.
Referenced by maille_sommet().
numero_maille() [2/3]
int Pave::numero_maille (int i, int j) inline
Renvoie le numero de la (i,j)-ieme maille<br>(suivant (X,Y)).
Returns
int
Signification: le numero de la maille cherchee
Contraintes:
Definition at line 165 of file Pave.h.
{
  assert(dimension == 2);
  assert(i < Nx);
  assert(j < Ny);
  return j*Nx+i;
}
References Objet_U::dimension, Nx, and Ny.
numero_maille() [3/3]
int Pave::numero_maille (int i, int j, int k) inline
Renvoie le numero de la (i,j,k)-ieme maille<br>(suivant (X,Y,Z)).
Returns
int
Signification: le numero de la maille cherchee
Contraintes:
Definition at line 198 of file Pave.h.
{
  assert(dimension == 3);
  assert(i < Nx);
  assert(j < Ny);
  assert(k < Nz);
  return k*Ny*Nx+j*Nx+i;
}
References Objet_U::dimension, Nx, Ny, and Nz.
numero_sommet() [1/3]
int Pave::numero_sommet (int i) inline
Renvoie le numero du i-ieme sommet<br>(suivant X)
Returns
int
Signification: le numero du sommet cherche
Contraintes:
Definition at line 223 of file Pave.h.
{
  assert(dimension == 1);
  assert(i < Mx);
  return i;
}
References Objet_U::dimension, and Mx.
Referenced by coord_noeud(), lire_front(), and lire_Noeuds().
numero_sommet() [2/3]
int Pave::numero_sommet (int i, int j) inline
Renvoie le numero du (i,j)-ieme sommet<br>(suivant (X,Y)).
Returns
int
Signification: le numero du sommet cherche
Contraintes:
Definition at line 250 of file Pave.h.
{
  assert(dimension == 2);
  assert(i < Mx);
  assert(tour_complet!=-123);
  if((tour_complet) && (j==My))
    j=0;
  return j*Mx+i;
}
References Objet_U::dimension, Mx, My, and tour_complet.
numero_sommet() [3/3]
int Pave::numero_sommet (int i, int j, int k) inline
Renvoie le numero du (i,j,k)-ieme sommet<br>(suivant (X,Y,Z)).
Returns
int
Signification: le numero du sommet cherche
Contraintes:
Definition at line 285 of file Pave.h.
{
  assert(dimension == 3);
  assert(i < Mx);
  assert(tour_complet!=-123);
  if((tour_complet) && (j==My))
    j=0;
  assert(j < My);
  assert(k < Mz);
  return k*My*Mx+j*Mx+i;
}
References Objet_U::dimension, Mx, My, Mz, and tour_complet.
printOn()
Sortie & Pave::printOn (Sortie & s) const override protected virtual
Simple appel a: Zone::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 54 of file Pave.cpp.
{
  return Zone::printOn(s) ;
}
References Zone::printOn().
readOn()
Entree & Pave::readOn (Entree & is) override protected virtual
Lit les specifications d'un pave a partir
d'un flot d'entree.
Le format de lecture d'un pave dans le jeu de donnee est le suivant:
Pave nom_pave
{
Origine OX OY (OZ)
Longueurs LX LY (LZ)
Nombre_de_noeuds NX NY (NZ)
Facteurs Fx Fy (Fz)
(Symx)
(Symy)
(Symz)
}
{
(Bord) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Raccord) local homogene nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Internes) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
...
(Joint) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 PE_voisin
...
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< Symx
< Symy
< Symz
< Fin
< Bord
< Raccord
< Plaques
< Trous
< Joint
< Fin
Reimplemented from Objet_U.
Definition at line 104 of file Pave.cpp.
{
  xtanh_dilatation=0;
  tanh_dilatation=0;
  ztanh_dilatation=0;
  if(dimension<0)
    {
      Cerr << "You must give the dimension before to mesh" << finl;
      Cerr << " The syntax is \"Dimension dim\" " << finl ;
      exit();
    }
  Facteurs.resize(dimension);
  Facteurs = 1.;
  Symetrique.resize(dimension);
  Symetrique=0;
  xa_tanh = 10.;
  a_tanh = 10.;
  za_tanh = 10.;
  Origine.resize(dimension);
  Longueurs.resize(dimension);
  Nb_Noeuds.resize(dimension);
  Motcle motlu;
  int rang;
  tour_complet=0;
  rep_VEF=0;
  typer_();
  is >> nom;
  Cerr << "Reading of the block " << nom << finl;
  is >> motlu;
  if (motlu!="{")
    {
      Cerr << "We expected a { after " << nom << finl;
      exit();
    }
  {
    Motcles les_mots(18);
    {
      les_mots[0]="Origine";
      les_mots[1]="Longueurs";
      les_mots[2]="Nombre_de_noeuds";
      les_mots[3]="Facteurs";
      les_mots[4]="Symx";
      les_mots[5]="Symy";
      les_mots[6]="Symz";
      les_mots[7]="xtanh";
      les_mots[8]="xtanh_dilatation";
      les_mots[9]="xtanh_taille_premiere_maille";
      les_mots[10]="ytanh";
      les_mots[11]="ytanh_dilatation";
      les_mots[12]="ytanh_taille_premiere_maille";
      les_mots[13]="ztanh";
      les_mots[14]="ztanh_dilatation";
      les_mots[15]="ztanh_taille_premiere_maille";
      les_mots[16]="reprise_VEF";
      les_mots[17]="}";
    }
    while(motlu != "}")
      {
        is >> motlu;
        rang = les_mots.search(motlu);
        switch(rang)
          {
          case 0:
            for(int i=0; i< dimension; i++)
              is >> Origine(i);
            break;
          case 1:
            lire_Longueurs(is);
            break;
          case 2:
            lire_Noeuds(is);
            break;
          case 3:
            for(int i=0; i< dimension; i++)
              is >> Facteurs(i);
            break;
          case 4:      //!< Symx
            Symetrique(0)=1;
            break;
          case 5:      //!< Symy
            if(dimension<2)
              {
                Cerr << "Symy has meaning only in dimension >= 2" << finl;
                exit();
              }
            Symetrique(1)=1;
            break;
          case 6:      //!< Symz
            if(dimension<3)
              {
                Cerr << "Symz has meaning only in dimension >= 3" << finl;
                exit();
              }
            Symetrique(2)=1;
            break;
          case 7:
            {
              is >> xa_tanh;
              break;
            }
          case 8:
            {
              is >> xtanh_dilatation;
              break;
            }
          case 9:
            {
              double x1, x_tmp;
              is >> x1;
              xa_tanh=.1;
              double fac_sym;
              assert(xtanh_dilatation!=-123);
              if (xtanh_dilatation != 0 )
                fac_sym=1.;
              else
                fac_sym=2.;
              assert(!est_egal(xa_tanh,-123.));
              for(int decimale=1; decimale<7; decimale++)
                {
                  x_tmp=Longueurs(0)/fac_sym*(1.+tanh((-1.+fac_sym*1./((Mx-1)*1.))*atanh(xa_tanh))/xa_tanh);
                  while ( x_tmp > x1 )
                    {
                      xa_tanh+=pow(10.,-decimale);
                      xa_tanh = std::min(xa_tanh,1-Objet_U::precision_geom);
                      if ( std::fabs(xa_tanh) < Objet_U::precision_geom)
{
                          Cerr << "Error: The coefficient xa_tanh has a value of : " << xa_tanh << finl ;
                          Cerr << "So the mesh can't be generated with tanh (hyperbolic tangent) variation!" << finl ;
                          Cerr << "You must decrease either the xtanh_taille_premiere_maille size of the first cell of the mesh " << finl;
                          Cerr << "or the nombre_de_noeuds Nx node number in the X direction." << finl;
                          exit();
                        }
                      x_tmp=Longueurs(0)/fac_sym*(1.+tanh((-1.+fac_sym*1./((Mx-1)*1.))*atanh(xa_tanh))/xa_tanh);
                    }
                  xa_tanh-=pow(10.,-decimale);
                  xa_tanh = std::min(xa_tanh,1-Objet_U::precision_geom);
                  if ( std::fabs(xa_tanh) < Objet_U::precision_geom)
                    {
                      Cerr << "Error: The coefficient xa_tanh has a value of : " << xa_tanh << finl ;
                      Cerr << "So the mesh can't be generated with tanh (hyperbolic tangent) variation!" << finl ;
                      Cerr << "You must decrease either the xtanh_taille_premiere_maille size of the first cell of the mesh " << finl;
                      Cerr << "or the nombre_de_noeuds Nx node number in the X direction." << finl;
                      exit();
                    }
                }
              Cerr << "The coefficient xa_tanh has a value of : " << xa_tanh << finl ;
              break;
            }
          case 10:
            {
              is >> a_tanh;
              break;
            }
          case 11:
            {
              is >> tanh_dilatation;
              break;
            }
          case 12:
            {
              double y1, y_tmp;
              is >> y1;
              a_tanh=.1;
              double fac_sym;
              assert(tanh_dilatation!=-123);
              if (tanh_dilatation != 0 )
                fac_sym=1.;
              else
                fac_sym=2.;
              assert(!est_egal(a_tanh,-123.));
              for(int decimale=1; decimale<7; decimale++)
                {
                  y_tmp=Longueurs(1)/fac_sym*(1.+tanh((-1.+fac_sym*1./((My-1)*1.))*atanh(a_tanh))/a_tanh);
                  while ( y_tmp > y1 )
                    {
                      a_tanh+=pow(10.,-decimale);
                      a_tanh = std::min(a_tanh,1-Objet_U::precision_geom);
                      if ( std::fabs(a_tanh) < Objet_U::precision_geom)
{
                          Cerr << "Error: The coefficient ya_tanh has a value of : " << a_tanh << finl ;
                          Cerr << "So the mesh can't be generated with tanh (hyperbolic tangent) variation!" << finl ;
                          Cerr << "You must decrease either the ytanh_taille_premiere_maille size of the first cell of the mesh " << finl;
                          Cerr << "or the nombre_de_noeuds Ny node number in the Y direction." << finl;
                          exit();
                        }
                      y_tmp=Longueurs(1)/fac_sym*(1.+tanh((-1.+fac_sym*1./((My-1)*1.))*atanh(a_tanh))/a_tanh);
                    }
                  a_tanh-=pow(10.,-decimale);
                  a_tanh = std::min(a_tanh,1-Objet_U::precision_geom);
                  if ( std::fabs(a_tanh) < Objet_U::precision_geom)
                    {
                      Cerr << "Error: The coefficient ya_tanh has a value of : " << a_tanh << finl ;
                      Cerr << "So the mesh can't be generated with tanh (hyperbolic tangent) variation!" << finl ;
                      Cerr << "You must decrease either the ytanh_taille_premiere_maille size of the first cell of the mesh " << finl;
                      Cerr << "or the nombre_de_noeuds Ny node number in the Y direction." << finl;
                      exit();
                    }
                }
              Cerr << "The coefficient ya_tanh has a value of : " << a_tanh << finl ;
              break;
            }
          case 13:
            {
              is >> za_tanh;
              break;
            }
          case 14:
            {
              is >> ztanh_dilatation;
              break;
            }
          case 15:
            {
              double z1, z_tmp;
              is >> z1;
              za_tanh=.1;
              double fac_sym;
              assert(ztanh_dilatation!=-123);
              if (ztanh_dilatation != 0 )
                fac_sym=1.;
              else
                fac_sym=2.;
              assert(!est_egal(za_tanh,-123.));
              for(int decimale=1; decimale<7; decimale++)
                {
                  z_tmp=Longueurs(2)/fac_sym*(1.+tanh((-1.+fac_sym*1./((Mz-1)*1.))*atanh(za_tanh))/za_tanh);
                  while ( z_tmp > z1 )
                    {
                      za_tanh+=pow(10.,-decimale);
                      za_tanh = std::min(za_tanh,1-Objet_U::precision_geom);
                      if ( std::fabs(za_tanh) < Objet_U::precision_geom)
{
                          Cerr << "Error: The coefficient za_tanh has a value of : " << za_tanh << finl ;
                          Cerr << "So the mesh can't be generated with tanh (hyperbolic tangent) variation!" << finl ;
                          Cerr << "You must decrease either the ztanh_taille_premiere_maille size of the first cell of the mesh " << finl;
                          Cerr << "or the nombre_de_noeuds Nz node number in the Z direction." << finl;
                          exit();
                        }
                      z_tmp=Longueurs(2)/fac_sym*(1.+tanh((-1.+fac_sym*1./((Mz-1)*1.))*atanh(za_tanh))/za_tanh);
                    }
                  za_tanh-=pow(10.,-decimale);
                  za_tanh = std::min(za_tanh,1-Objet_U::precision_geom);
                  if ( std::fabs(za_tanh) < Objet_U::precision_geom)
                    {
                      Cerr << "Error: The coefficient za_tanh has a value of : " << za_tanh << finl ;
                      Cerr << "So the mesh can't be generated with tanh (hyperbolic tangent) variation!" << finl ;
                      Cerr << "You must decrease either the ztanh_taille_premiere_maille size of the first cell of the mesh " << finl;
                      Cerr << "or the nombre_de_noeuds Nz node number in the Z direction." << finl;
                      exit();
                    }
                }
              Cerr << "The coefficient za_tanh has a value of : " << za_tanh << finl ;
              break;
            }
          case 16:
            {
              rep_VEF=1;
              break;
            }
          case 17: //!< Fin
            break;
          default:
            if (motlu == "tanh" || motlu == "tanh_dilatation" || motlu == "tanh_taille_premiere_maille")
              {
                Cerr << "Error: '" << motlu << "' keyword is obsolete since V1.7.9. We renamed it to 'Y"<< motlu <<"'" << finl;
              }
            else
              {
                Cerr << motlu << "  is not understood " << finl;
                Cerr << les_mots;
              }
            exit();
          }
      }
    Pas.resize(dimension);
    if(min_array(Facteurs)<=0.)
      {
        Cerr << "The progression factors must be positives" << finl;
        exit();
      }
    switch(dimension)
      {
      case 1:
        maille1D();
        break;
      case 2:
        maille2D();
        break;
      case 3:
        maille3D();
        break;
      }
  }
  if(Mx<2)
    {
      Cerr << "There must be at least two cells on x" << finl;
      exit();
    }
  if (axi)
    {
// Les coordonnees sont modulo 2 pi
      double deux_pi=M_PI*2.0 ;
      {
        int Les_Noeuds_dimension0_opt=Les_Noeuds.dimension(0);
        for(int i=0; i<Les_Noeuds_dimension0_opt; i++)
          {
            Les_Noeuds(i, 1)-=(int) Les_Noeuds(i, 1);
            Les_Noeuds(i, 1)*=deux_pi;
          }
      }
      Longueurs(1)*=deux_pi;
      Origine(1)*=deux_pi;
    }
  {
    is >> motlu;
    if (motlu!="{")
      {
        Cerr << "We expected a { before reading the boundaries" << finl;
        exit();
      }
    Motcles les_mots(6);
    {
      les_mots[0]="Bord";
      les_mots[1]="Raccord";
      les_mots[2]="Internes";
      les_mots[3]="Trou";
      les_mots[4]="Joint";
      les_mots[5]="}";
    }
    while(motlu != "}")
      {
        is >> motlu;
        rang = les_mots.search(motlu);
        switch(rang)
          {
          case 0:      //!< Bord
            {
              Bord& newbord=mes_faces_bord.add(Bord());
              lire_front(is , newbord );
            }
            break;
          case 1:      //!< Raccord
            {
              Raccord& newraccord=mes_faces_raccord.add(Raccord());
              Nom type="Raccord_";
              Nom local, homogene;
              is >> local >> homogene;
              type+=local;
              type+="_";
              type+=homogene;
              if (type == "local")
                {
                  Cerr << "Do not use sequential local connection!" << finl;
                  exit();
                }
              newraccord.typer(type);
              lire_front(is , newraccord.valeur() );
            }
            break;
          case 2:      //!< Plaques
            {
              Faces_Interne& faces=mes_faces_int.add(Faces_Interne());
              lire_front(is , faces );
            }
            break;
          case 3:      //!< Trous
            break;
          case 4:      //!< Joint
            {
              Joint& newjoint=mes_faces_joint.add(Joint());
              lire_front(is , newjoint );
            }
            break;
          case 5:      //!< Fin
            break;
          default:
            Cerr << motlu << "  is not understood " << finl;
            Cerr << les_mots;
            exit();
          }
      }
  }
  return is;
}
References a_tanh, List_Bord::add(), List_Faces_Interne::add(), List_Joint::add(), List_Raccord::add(), Objet_U::axi, Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, est_egal(), Process::exit(), Facteurs, finl, Les_Noeuds, lire_front(), lire_Longueurs(), lire_Noeuds(), Longueurs, M_PI, maille1D(), maille2D(), maille3D(), Zone::mes_faces_bord, Zone::mes_faces_int, Zone::mes_faces_joint, Zone::mes_faces_raccord, min_array(), Mx, My, Mz, Nb_Noeuds, Zone::nom, Origine, Pas, Objet_U::precision_geom, rep_VEF, TRUSTVect< _TYPE_ >::resize(), Motcles::search(), Symetrique, tanh_dilatation, tour_complet, Deriv_::typer(), typer_(), Deriv_Raccord_base::valeur(), xa_tanh, xtanh_dilatation, za_tanh, and ztanh_dilatation.
self_cast() [1/2]
const Pave & Pave::self_cast (const Objet_U & r) static
Definition at line 20 of file Pave.cpp.
self_cast() [2/2]
Pave & Pave::self_cast (Objet_U & r) static
Definition at line 20 of file Pave.cpp.
taille_memoire()
unsigned Pave::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Pave.cpp.
typer_()
void Pave::typer_ ()
Type le pave suivant la dimension d'espace
et suivant le repere de coordonnees demande (cylindrique
ou cartesien)
En dimension 1 : le pave est maille avec des segments
En dimension 2 (axi): la pave est maille avec des rectangle (axi)
En dimension 3 (axi): la pave est maille avec des hexaedres (axi)
Definition at line 1339 of file Pave.cpp.
{
  switch(dimension)
    {
    case 1:
      typer("Segment");
      break;
    case 2:
      if (axi)
        typer("Rectangle_Axi");
      else if (bidim_axi)
        typer("Rectangle_2D_Axi");
      else
        typer("Rectangle");
      break;
    case 3:
      if (axi)
        typer("Hexaedre_Axi");
      else
        typer("Hexaedre");
      break;
    default :
      break;
    }
}
References Objet_U::axi, Objet_U::bidim_axi, Objet_U::dimension, and Zone::typer().
Referenced by readOn().
Member Data Documentation
a_tanh
double Pave::a_tanh
a pour le maillage en tanh dans la diry!!
Definition at line 66 of file Pave.h.
Referenced by maille2D(), maille3D(), and readOn().
Facteurs
DoubleVect Pave::Facteurs
Definition at line 61 of file Pave.h.
Referenced by maille1D(), maille2D(), maille3D(), and readOn().
info_obj
const Type_info Pave::info_obj static
Definition at line 54 of file Pave.h.
Les_Noeuds
DoubleTab Pave::Les_Noeuds
Definition at line 63 of file Pave.h.
Referenced by associer_domaine(), coord_noeud(), lire_Noeuds(), and readOn().
Les_Nums
IntVect Pave::Les_Nums
Definition at line 64 of file Pave.h.
Referenced by associer_domaine().
Longueurs
DoubleVect Pave::Longueurs
Definition at line 59 of file Pave.h.
Referenced by lire_front(), lire_Longueurs(), lire_Noeuds(), maille1D(), maille2D(), maille3D(), and readOn().
Mx
int Pave::Mx
Definition at line 86 of file Pave.h.
Referenced by lire_front(), lire_Noeuds(), maille2D(), maille3D(), numero_sommet(), and readOn().
My
int Pave::My
Definition at line 86 of file Pave.h.
Referenced by lire_front(), lire_Noeuds(), maille2D(), maille3D(), numero_sommet(), and readOn().
Mz
int Pave::Mz
Definition at line 86 of file Pave.h.
Referenced by lire_Noeuds(), maille3D(), numero_sommet(), and readOn().
Nb_Noeuds
IntVect Pave::Nb_Noeuds
Definition at line 60 of file Pave.h.
Referenced by lire_Noeuds(), Nb_Noeud(), and readOn().
Nx
int Pave::Nx
Definition at line 86 of file Pave.h.
Referenced by lire_front(), lire_Noeuds(), maille1D(), maille2D(), maille3D(), and numero_maille().
Ny
int Pave::Ny
Definition at line 86 of file Pave.h.
Referenced by lire_front(), lire_Noeuds(), maille2D(), maille3D(), and numero_maille().
Nz
int Pave::Nz
Definition at line 86 of file Pave.h.
Referenced by lire_front(), lire_Noeuds(), maille3D(), and numero_maille().
Origine
DoubleVect Pave::Origine
Definition at line 58 of file Pave.h.
Referenced by lire_front(), maille1D(), maille2D(), maille3D(), and readOn().
Pas
DoubleVect Pave::Pas
Definition at line 62 of file Pave.h.
Referenced by maille1D(), maille2D(), maille3D(), and readOn().
rep_VEF
int Pave::rep_VEF
Definition at line 72 of file Pave.h.
Referenced by maille3D(), and readOn().
Symetrique
IntVect Pave::Symetrique
Definition at line 65 of file Pave.h.
Referenced by maille1D(), maille2D(), maille3D(), and readOn().
tanh_dilatation
int Pave::tanh_dilatation
Definition at line 67 of file Pave.h.
Referenced by maille2D(), maille3D(), and readOn().
tour_complet
int Pave::tour_complet
Definition at line 96 of file Pave.h.
Referenced by lire_front(), lire_Longueurs(), lire_Noeuds(), numero_sommet(), and readOn().
xa_tanh
double Pave::xa_tanh
xa pour le maillage en tanh dans la dirx!!
Definition at line 68 of file Pave.h.
Referenced by maille2D(), maille3D(), and readOn().
xtanh_dilatation
int Pave::xtanh_dilatation
Definition at line 69 of file Pave.h.
Referenced by maille2D(), maille3D(), and readOn().
za_tanh
double Pave::za_tanh
za pour le maillage en tanh dans la dirz!!
Definition at line 70 of file Pave.h.
Referenced by maille3D(), and readOn().
ztanh_dilatation
int Pave::ztanh_dilatation
Definition at line 71 of file Pave.h.
Referenced by maille3D(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Pave.h
src/Kernel/Geometrie/Pave.cpp
src/Kernel/Geometrie/Pave2.cpp