TRUST: DoubleTab Class Reference
DoubleTab Class Reference
Tableau a n entrees pour n<= 4
Repose sur un DoubleVect avec calculs de l'indice corespondant
Voir les commentaires de DoubleVect.
#include <DoubleTab.h>
Public Member Functions
~DoubleTab ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab ()
DoubleTab (const DoubleTab &)
DoubleTab (int n)
DoubleTab (int n1, int n2)
DoubleTab (int n1, int n2, int n3)
DoubleTab (int n1, int n2, int n3, int n4)
virtual void ref (const DoubleVect &)
fait pointer le tableau sur le vecteur v et en associant
la meme structure parallele.
Attention, si line_size du vecteur v est different de 1,
on cree un tableau bidimensionnel (on peut avoir un vecteur
de ce type si on copie un Tab dans un Vect puis on prend
une ref sur ce Vect).
virtual void ref (const DoubleTab &)
fait pointer le tableau sur le tableau t
en recuperant la structure parallele. Attention,
on fige le tableau qui ne pourra plus etre resize
virtual void ref_data (double *ptr, int size)
identique a DoubleVect::ref_data()
virtual void ref_array (ArrOfDouble &, int start=0, int sz=-1)
identique a DoubleVect::ref_array()
(cree un tableau monodimensionnel sans structure parallele)
Attention, le tableau source et destination sont figes (resize interdit)
(voir ArrOfDouble::
virtual void ref_tab (DoubleTab &, int start_line=0, int nb_lines=-1)
fait pointer le tableau sur une sous-partie du tableau t
definie par la valeur du premier indice et ne nombre de "lignes" du tableau
a recuperer (une ligne = toutes les valeurs tab(i,j,k,...) pour un i donne).
Le nombre de dimensions du tableau est le meme que pour t,
les dimension(i) pour i>=1 sont les memes et dimension(0) = nb_lines.
virtual void reset ()
met le tableau dans l'etat obtenu par le constructeur par defaut
voir DoubleVect::reset()
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
methode virtuelle qui force le tableau a changer de taille.
Change aussi nb_dim_ a 1. Equivalent a DoubleTab::resize(n, opt)
void resize_dim0 (int n, Array_base::Resize_Options opt=COPY_INIT)
change la dimension[0] du tableau en conservant les autres.
void resize (int n, Array_base::Resize_Options opt=COPY_INIT)
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un DoubleTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
void resize (int n1, int n2, Array_base::Resize_Options opt=COPY_INIT)
void resize (int n1, int n2, int n3, Array_base::Resize_Options opt=COPY_INIT)
void resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt=COPY_INIT)
void resize (const ArrOfInt &tailles, Array_base::Resize_Options opt=COPY_INIT)
redimensionne le tableau (nb_dim_ sera egal a tailles.size_array()
et dimension(i) a tailles[i].
DoubleTab & operator= (const DoubleTab &)
copie la structure et les valeurs du tableau src
Restrictions et preconditions identiques a DoubleVect::operator=(const DoubleVect & v)
DoubleTab & operator= (const DoubleVect &)
copie la structure et les valeurs de src.
Attention: appel invalide si src est un type derive de Vect
(sinon quoi faire, un tableau unidimensionnel, ou une copie de la structure ?)
DoubleTab & operator= (const FDoubleTab &)
DoubleTab & operator= (double d)
idem que ArrOfDouble::operator=(double)
void copy (const DoubleTab &, Array_base::Resize_Options opt=COPY_INIT)
double & operator() (const ArrOfInt &indice)
double operator() (const ArrOfInt &indice) const
double & operator[] (int i)
operateur [] retourne le ieme element du tableau
const double & operator[] (int i) const
operateur [] retourne le ieme element du tableau
double & operator() (int i)
idem operator[]
const double & operator() (int i) const
double & operator() (int i1, int i2)
const double & operator() (int i1, int i2) const
double & operator() (int i1, int i2, int i3)
const double & operator() (int i1, int i2, int i3) const
double & operator() (int i1, int i2, int i3, int i4)
const double & operator() (int i1, int i2, int i3, int i4) const
int dimension (int) const
Returns one of the "real" dimensions of the multi-dimensionnal array,
as defined by:
dimension(0) = size_reelle() / line_size(), or 0 if line_size()==0
and, for i >= 1:
dimension(i) is equal to dimension_tot(i)
If size_reelle_ok() returns 0, it is invalid to ask for dimension(0). You can only ask for
dimension_tot(0) (see DoubleVect::size_reelle_ok())
int dimension_tot (int) const
Returns the total dimensions of the multi-dimensionnal array, including
virtual items (used in parallel distributed arrays)
int nb_dim () const
Returns the number of dimensions of the array (>= 1)
void ajoute_produit_tensoriel (double alpha, const DoubleTab &, const DoubleTab &)
z+=alpha*x*y;
int inverse_LU (const ArrOfDouble &, ArrOfDouble &)
Resolution du systeme Ax=b.
int decomp_LU (int, ArrOfInt &, DoubleTab &)
Decomposition d'une matrice en L.U
methode de Crout (diagonale de L =1)
void resoud_LU (int, ArrOfInt &, const ArrOfDouble &, ArrOfDouble &)
Resolution du systeme A_x=b
A_ contenant le decompostion LU de A (stockee dans une seule matrice)
double max_du_u (const DoubleTab &)
Fonction utilisee pour le calcul du du/u (pour convergence implicite)
renvoie le max de abs(du(i)/u(i))
utilisation max_ = (u(n+1)-u(n)).max_du_u(u(n))
virtual void set_md_vector (const MD_Vector &)
associe le md_vector au vecteur (voir DoubleVect::set_md_vector())
dimension(0) sera initialise a md_vector...get_nb_items_reels().
virtual void jump (Entree &)
virtual void lit (Entree &, int resize_and_read=1)
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
virtual void ecrit (Sortie &) const
ecriture des valeurs du tableau "raw" sans structure parallele
void append_line (double)
Adds 1 to dimension_tot(0) and puts a in the added line.
void append_line (double, double)
Adds 1 to dimension_tot(0) and puts a and b in the added line.
void append_line (double, double, double)
Like append_line(i,j), but for arrays with line_size()==3.
void append_line (double, double, double, double)
Like append_line(i,j), but for arrays with line_size()==4.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static DoubleTab & self_cast (Objet_U &)
static const DoubleTab & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
ecriture d'un tableau sequentiel
(idem que DoubleVect::printOn() on ne sait pas quoi faire de pertinent
pour un tableau distribue).
virtual Entree & readOn (Entree &)
lecture d'un tableau sequentiel
Private Attributes
int nb_dim_
int dimensions_ [4]
int dimension_tot_0_
Detailed Description
Tableau a n entrees pour n<= 4
Repose sur un DoubleVect avec calculs de l'indice corespondant
Voir les commentaires de DoubleVect.
Definition at line 49 of file DoubleTab.h.
Constructor & Destructor Documentation
DoubleTab::~DoubleTab ()
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
DoubleTab::DoubleTab ()
Definition at line 124 of file DoubleTab.cpp.
References dimensions_, and init_dimensions().
                     :
  nb_dim_(1), dimension_tot_0_(0)
{
  init_dimensions(dimensions_);
  dimensions_[0] = 0;
}
DoubleTab::DoubleTab (const DoubleTab & dbt)
Definition at line 131 of file DoubleTab.cpp.
References dimensions_, and MAXDIM_TAB.
                                         :
  DoubleVect(dbt),
  nb_dim_(dbt.nb_dim_),
  dimension_tot_0_(dbt.dimension_tot_0_)
{
  for (int i = 0; i < MAXDIM_TAB; i++)
    dimensions_[i] = dbt.dimensions_[i];
}
DoubleTab::DoubleTab (int n)
Definition at line 142 of file DoubleTab.cpp.
References dimensions_, and init_dimensions().
  : DoubleVect(n PARAM_X2),
    nb_dim_(1),
    dimension_tot_0_(n)
{
  init_dimensions(dimensions_);
  dimensions_[0] = n;
}
DoubleTab::DoubleTab (int n1, int n2)
Definition at line 151 of file DoubleTab.cpp.
References dimensions_, init_dimensions(), and DoubleVect::set_line_size_().
  : DoubleVect(n1*n2 PARAM_X2),
    nb_dim_(2),
    dimension_tot_0_(n1)
{
  assert(n1 >= 0 && n2 >= 0);
  init_dimensions(dimensions_);
  dimensions_[0]=n1;
  dimensions_[1]=n2;
  set_line_size_(n2);
}
DoubleTab::DoubleTab (int n1, int n2, int n3)
Definition at line 176 of file DoubleTab.cpp.
References dimensions_, init_dimensions(), and DoubleVect::set_line_size_().
  : DoubleVect(n1*n2*n3 PARAM_X2),
    nb_dim_(3),
    dimension_tot_0_(n1)
{
  assert(n1 >= 0 && n2 >= 0 && n3 >= 0);
  init_dimensions(dimensions_);
  dimensions_[0]=n1;
  dimensions_[1]=n2;
  dimensions_[2]=n3;
  set_line_size_(n2*n3);
}
DoubleTab::DoubleTab (int n1, int n2, int n3, int n4)
Definition at line 189 of file DoubleTab.cpp.
References dimensions_, init_dimensions(), and DoubleVect::set_line_size_().
  : DoubleVect(n1*n2*n3*n4 PARAM_X2),
    nb_dim_(4),
    dimension_tot_0_(n1)
{
  assert(n1 >= 0 && n2 >= 0 && n3 >= 0 && n4 >= 0);
  init_dimensions(dimensions_);
  dimensions_[0]=n1;
  dimensions_[1]=n2;
  dimensions_[2]=n3;
  dimensions_[3]=n4;
  set_line_size_(n2*n3*n4);
}
Member Function Documentation
void DoubleTab::ajoute_produit_tensoriel (double alpha, const DoubleTab & x, const DoubleTab & y)
z+=alpha*x*y;
Quelqu'un veut-il expliquer ce que fait cette methode ?
Definition at line 668 of file DoubleTab.cpp.
References ArrOfInt::addr(), MD_Vector_base::get_items_to_compute(), DoubleVect::get_md_vector(), DoubleVect::line_size(), MD_Vector::non_nul(), ArrOfInt::size_array(), DoubleVect::size_totale(), and MD_Vector::valeur().
Referenced by Integrale_tps_produit_champs::ajoute_produit_tensoriel().
{
// Tableaux vus comme des tableaux unidimensionnels (pour ne pas avoir a gerer nb_dim)
  const DoubleVect& vx = x;
  const DoubleVect& vy = y;
  DoubleVect& v = *this;
  const int line_size_x = vx.line_size();
  const int line_size_y = vy.line_size();
  const int line_size_xy = v.line_size();
  assert(line_size_xy == line_size_x * line_size_y);
// Pour ne pas diviser par line_size()
  assert(vx.size_totale() * line_size_xy == v.size_totale() * line_size_x);
  assert(vy.size_totale() * line_size_xy == v.size_totale() * line_size_y);
// blocs d'items a traiter (un bloc par defaut: tout le tableau)
  int default_bloc[2];
  default_bloc[0] = 0;
  default_bloc[1] = (v.line_size() > 0) ? (v.size_totale() / v.line_size()) : 0;
  const int *blocs = default_bloc;
  int nb_blocs = 1;
  if (v.get_md_vector().non_nul())
    {
      const ArrOfInt& blk = v.get_md_vector().valeur().get_items_to_compute();
      blocs = blk.addr();
      nb_blocs = blk.size_array() / 2;
    }
  for (int i_bloc = 0; i_bloc < nb_blocs; i_bloc++)
    {
      const int debut = blocs[i_bloc*2];
      const int fin = blocs[i_bloc*2+1];
      int v_index = debut * line_size_xy;
      for (int i = debut; i < fin; i++)
        {
          for (int j = 0; j < line_size_x; j++)
            {
              double xval = vx[i * line_size_x + j];
              for (int k = 0; k < line_size_y; k++)
                {
                  double yval = vy[i * line_size_y + k];
                  v[v_index] += alpha * xval * yval;
                  v_index++;
                }
            }
        }
    }
}
void DoubleTab::append_line (double a) [inline]
Adds 1 to dimension_tot(0) and puts a in the added line.
Definition at line 271 of file DoubleTab.h.
References ArrOfDouble::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, DoubleVect::line_size(), DoubleVect::resize_vect_(), and ArrOfDouble::size_array().
Referenced by Zone_PolyMAC::init_m1_2d(), Zone_PolyMAC::init_m1_3d(), Zone_PolyMAC::init_m2(), Champ_Face_PolyMAC::init_ra(), Zone_PolyMAC::init_rf(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Zone_PolyMAC::init_we_2d(), and Zone_PolyMAC::init_we_3d().
{
  assert(line_size() == 1);
  assert(dimension_tot_0_ * line_size() == size_array());
  const int n = dimension_tot_0_;
  dimensions_[0] = ++dimension_tot_0_;
  DoubleVect::resize_vect_(n+1, COPY_NOINIT);
  double * ptr = addr() + n;
  ptr[0] = a;
}
void DoubleTab::append_line (double a, double b) [inline]
Adds 1 to dimension_tot(0) and puts a and b in the added line.
Definition at line 284 of file DoubleTab.h.
References ArrOfDouble::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, DoubleVect::line_size(), DoubleVect::resize_vect_(), and ArrOfDouble::size_array().
{
  assert(line_size() == 2);
  assert(dimension_tot_0_ * line_size() == size_array());
  const int n = dimension_tot_0_ * 2;
  dimensions_[0] = ++dimension_tot_0_;
  DoubleVect::resize_vect_(n+2, COPY_NOINIT);
  double * ptr = addr() + n;
  ptr[0] = a;
  ptr[1] = b;
}
void DoubleTab::append_line (double a, double b, double c) [inline]
Like append_line(i,j), but for arrays with line_size()==3.
Definition at line 297 of file DoubleTab.h.
References ArrOfDouble::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, DoubleVect::line_size(), DoubleVect::resize_vect_(), and ArrOfDouble::size_array().
{
  assert(line_size() == 3);
  assert(dimension_tot_0_  * line_size() == size_array());
  const int n = dimension_tot_0_ * 3;
  dimensions_[0] = ++dimension_tot_0_;
  DoubleVect::resize_vect_(n+3, COPY_NOINIT);
  double * ptr = addr() + n;
  ptr[0] = a;
  ptr[1] = b;
  ptr[2] = c;
}
void DoubleTab::append_line (double a, double b, double c, double d) [inline]
Like append_line(i,j), but for arrays with line_size()==4.
Definition at line 311 of file DoubleTab.h.
References ArrOfDouble::addr(), Array_base::COPY_NOINIT, dimension_tot_0_, dimensions_, DoubleVect::line_size(), DoubleVect::resize_vect_(), and ArrOfDouble::size_array().
{
  assert(line_size() == 4);
  assert(dimension_tot_0_  * line_size() == size_array());
  const int n = dimension_tot_0_ * 4;
  dimensions_[0] = ++dimension_tot_0_;
  DoubleVect::resize_vect_(n+4, COPY_NOINIT);
  double * ptr = addr() + n;
  ptr[0] = a;
  ptr[1] = b;
  ptr[2] = c;
  ptr[3] = d;
}
void DoubleTab::copy (const DoubleTab & src, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 466 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, DoubleVect::copy_(), dimension_tot_0_, dimensions_, MAXDIM_TAB, and nb_dim_.
Referenced by Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Op_Moyenne::completer(), Equation_base::derivee_en_temps_conv(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), DoubleTrav::DoubleTrav(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), operator=(), and Navier_Stokes_std::uzawa().
{
  if (&src != this)
    {
      DoubleVect::copy_(src, opt);
      nb_dim_ = src.nb_dim_;
      for (int i = 0; i < MAXDIM_TAB; i++)
        dimensions_[i] = src.dimensions_[i];
      dimension_tot_0_ = src.dimension_tot_0_;
      assert(CHECK_LINE_SIZE);
    }
}
Objet_U * DoubleTab::cree_instance () [static]
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
int DoubleTab::decomp_LU (int n, ArrOfInt & index, DoubleTab & matLU)
Decomposition d'une matrice en L.U
methode de Crout (diagonale de L =1)
Returns:
matrice A_ = assemblage (L-diagonale)+U
Definition at line 780 of file DoubleTab.cpp.
References Cerr, Process::exit(), and finl.
{
  ArrOfDouble vv(n);
  int i, imax=-1, j , k;
  double big, dum, sum, temp;
  int cvg = 1;
  matLU = (*this);
// Recupere le coeff max d'une ligne, stocke dans vv
  for (i=0 ; i<n ; i++)
    {
      big = 0;
      for (j=0 ; j<n ; j++)
        {
          if ((temp = fabs(matLU(i,j))) > big)
            {
              big = temp;
            }
        }
// Cout<<"decomp_LU big "<<big<<finl;
      if (big == 0)
        {
          Cerr <<"Singular matrix in LU decomposition"<<finl;
          cvg = 0;
          exit();
        }
      vv[i] = 1./big;
    }
// calcul de la matrice matLU
  for (j=0 ; j<n ; j++)
    {
      for (i=0 ; i<j ; i++)
        {
          sum = matLU(i,j);
          for (k=0 ; k<i ; k++)
            {
              sum -= matLU(i,k) * matLU(k,j);
            }
          matLU(i,j) = sum;
        }
      big = 0;
      for (i=j ; i<n ; i++)
        {
          sum = matLU(i,j);
          for (k=0 ; k<j ; k++)
            {
              sum -= matLU(i,k) * matLU(k,j);
            }
          matLU(i,j) = sum;
          if ((dum = vv(i)*fabs(sum)) >= big)
            {
              big = dum;
              imax = i;
            }
        }
      if (j != imax)
        {
          for (k=0 ; k<n ; k++)
            {
              dum = matLU(imax,k);
              matLU(imax,k) = matLU(j,k);
              matLU(j,k) = dum;
            }
          vv(imax) = vv(j);
        }
      index(j) = imax;
      dum = 1./matLU(j,j);
      for (i=j+1 ; i<n ; i++)
        {
          matLU(i,j) *= dum;
        }
    }
  return cvg;
}
int DoubleTab::dimension (int i) const [inline]
Returns one of the "real" dimensions of the multi-dimensionnal array,
as defined by:
dimension(0) = size_reelle() / line_size(), or 0 if line_size()==0
and, for i >= 1:
dimension(i) is equal to dimension_tot(i)
If size_reelle_ok() returns 0, it is invalid to ask for dimension(0). You can only ask for
dimension_tot(0) (see DoubleVect::size_reelle_ok())
Definition at line 243 of file DoubleTab.h.
References dimensions_, and nb_dim_.
Referenced by BlocData::add_bloc(), Debog_Pb::add_renum_item(), Champ_Face::affecter(), Champ_P1NC::affecter_(), Champ_Inc_base::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter(), T_It_VDF_Face< _TYPE_ >::ajouter(), Masse_ajoutee_Coef_Constant::ajouter(), Source_WC_Chaleur::ajouter(), Source_QC_Chaleur::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::ajouter(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Domaine::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Sonde::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), T_It_VDF_Face< _TYPE_ >::ajouter_contribution(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_vitesse(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_vitesse(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Matrice_Morse_Sym::ajouter_multTab_(), Matrice_Morse::ajouter_multTab_(), Matrice_Diagonale::ajouter_multTab_(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Zone_PolyMAC::ajouter_stabilisation(), Masse_VEF_P1NC::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Solveur_Masse_EF::appliquer_impl(), Refine_Mesh::apply_2D(), Refine_Mesh::apply_3D(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), Pave::associer_domaine(), auto_build_joints(), bbox_intersection(), Octree_Zone::build(), Octree_Double::build_elements(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), build_nodes(), Octree_Double::build_nodes(), build_triofield(), Ch_front_input::buildSommetsFaces(), Champ_P1NC::calcul_h_conv(), Calcul_integrale_locale::Calcul_integrale_locale(), calcul_tab_norme(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Calcul_integrale_locale::calculer(), Op_Dift_VEF_base::calculer_borne_locale(), Polygone::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), calculer_centres_gravite(), Elem_geom_base::calculer_centres_gravite(), Zone_VF::calculer_coefficient_echange_thermique(), Zone_VF::calculer_coefficient_frottement(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Moyenne_volumique::calculer_convolution(), Moyenne_volumique::calculer_convolution_champ_elem(), Simple::calculer_correction_en_vitesse(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), T_It_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Loi_Etat_rhoT_GR_QC::calculer_H(), Echange_contact_VDF::calculer_h_autre_pb(), calculer_h_distant(), Terme_Source_Acceleration::calculer_la_source(), Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Diff_VEF_Face_Stab::calculer_min(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Navier_Stokes_std::calculer_pression_hydrostatique(), Faces::calculer_surfaces(), Loi_Etat_rhoT_GR_QC::calculer_temperature(), Echange_contact_VDF::calculer_Teta_equiv(), calculer_vecteur_2faces(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), caldscaldcentelemdim2(), caldscaldcentelemdim3(), calrotord2centelemdim2(), calrotord2centelemdim3(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), check(), Fluide_reel_base::check_unknown_range(), Scatter::Chercher_Correspondance(), Reordonner_faces_periodiques::chercher_direction_perio(), Zone::chercher_elements(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Frottement_interfacial_bulles::coefficient(), Flux_interfacial_Coef_Constant::coeffs(), Op_Correlation::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Octree_Double::compute_origin_factors(), OctreeRoot::construire(), Partitionneur_Tranche::construire_partition(), Partitionneur_Partition::construire_partition(), Scatter::construire_structures_paralleles(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::contribuer_a_avec(), Source_Fluide_Dilatable_Face< DERIVED_T >::contribuer_a_avec_impl(), T_It_VDF_Face< _TYPE_ >::contribuer_au_second_membre(), T_It_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre(), convert_domain_to_Domaine(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), Source_PDF_EF::correct_vitesse(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), create_listb_geom(), Remove_elem::creer_faces(), Polynome::degre(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_PolyMAC_Elem::dimensionner(), Roue::dimensionner(), Zone_VEF_PreP1b::discretiser_arete(), disp_dt(), diviser_par_rho_np1_face(), Loi_Etat_rhoT_GR_QC::Drho_DP(), Loi_Etat_rhoT_GR_QC::Drho_DT(), Loi_Etat_rhoT_GR_QC::DT_DH(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Med::ecrire_domaine_med(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Debog_Pb::ecrire_gen(), Postraitement_lata::ecrire_zone(), ecrit(), EcritureLectureSpecial::ecriture_special(), envoyer_all_to_all(), Parser_Eval::eval_fct(), Moyenne_volumique::eval_filtre(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extruder_en3::extruder(), Extruder_en20::extruder(), Extruder::extruder(), ExtrudeBord::extruder_bord(), Extruder::extruder_hexa(), Zone_CoviMAC::fgrad(), Echange_contact_CoviMAC::fgrad(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_resu(), find_matching_coordinates(), Sortie_libre_Text_H_ext::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Neumann_paroi::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Neumann::flux_impose(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_refChamp::get_dimension(), Champ_Generique_refChamp::get_localisation(), Domaine::getBoundingBox(), Ch_front_input_P1::getTemplate(), Champ_input_P0::getTemplate(), Ch_front_input::getTemplate(), Champ_front_instationnaire_base::Gpoint(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Champ_Q1NC::gradient(), Champ_Q1_EF::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Echange_impose_base::h_imp(), Zone_CoviMAC::harmonic_points(), histogramme_angle(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Op_Div_VEF_Elem::impr(), T_It_VDF_Face< _TYPE_ >::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), Op_Div_PolyMAC::impr(), Op_Diff_PolyMAC_base::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Diff_CoviMAC_base::impr(), Op_Conv_CoviMAC_base::impr(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Champ_implementation_P1::init_from_file(), Zone_PolyMAC::init_m1_3d(), Loi_Etat_GR_base::initialiser(), Loi_Etat_GP_base::initialiser(), Champ_front_recyclage::initialiser(), Sonde_Int::initialiser(), Sonde::initialiser(), Champ_front_var::initialiser(), Ch_front_input_P1::initialiser(), Ch_front_input_uniforme::initialiser(), Loi_Etat_GR_base::initialiser_inco_ch(), Navier_Stokes_std::initTimeStep(), Champ_Face_PolyMAC::interp_ve(), Moyenne_volumique::interpreter(), latatoother::interpreter(), Integrer_champ_med::interpreter(), VerifierCoin::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Extruder_en3::interpreter_(), Distanceparoi::interpreter_(), Corriger_frontiere_periodique::interpreter_(), inverser_par_diagonale(), kersol(), largest_angle(), Champ_Fonc_MED::lire(), Postraitement_lata::lire_champs(), Terme_Source_Acceleration::lire_data(), Scatter::lire_domaine(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Champ_front_recyclage::lire_fichier_format1(), lire_special(), lit(), meme_point(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Chimie::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_PolyMAC::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_calc_interne::mettre_a_jour(), Champ_Fonc_Morceaux::mettre_a_jour(), Champ_Fonc_Fonction_txyz_Morceaux::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_CoviMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_CoviMAC::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), Op_EF_base::modifier_flux(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_EF_base::modifier_pour_Cl(), EOS_Tools_VDF::moyenne_vol(), Source_PDF_EF::multiply_coeff_volume(), Matrice_Dense::nb_colonnes(), Matrice_Dense::nb_lignes(), Domaine::nb_som(), Champ_Inc_base::nb_valeurs_nodales(), Champ_Don_base::nb_valeurs_nodales(), NettoieNoeuds::nettoie(), Polynome::operator()(), Sonde_Int::ouvrir_fichier(), Sonde::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Sonde_Int::postraiter(), Sonde::postraiter(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Postraitement::postraiter_tableau(), prod(), projette(), Raffiner_anisotrope::Raffiner_anisotrope_(), OctreeRoot::rang_arete(), OctreeRoot::rang_elem(), OctreeRoot::rang_elem_depuis(), OctreeRoot::rang_sommet(), Loi_Etat_rhoT_GR_QC::readOn(), Champ_Fonc_MED::readOn(), Pave::readOn(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Champ_Q1NC_impl::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Face_implementation::remplir_coord_noeuds(), remplir_coordsommets_sous_domaine(), Op_Diff_EF::remplir_nu(), Ensemble_Lagrange_base::remplir_sommets_tmp(), Loi_Etat_GR_base::remplir_T(), Champ_front_MED::remplir_tab(), Reordonner_faces_periodiques::renum_som_perio(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), Traitement_particulier_NS_canal::reprendre_stat(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Traitement_particulier_NS_canal::sauver_stat_canal(), Octree_Double::search_nodes_close_to(), Champ_input_P0::setValue(), Champ_Input_Proto::setValueOnTab(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Echange_impose_base::T_ext(), Echange_externe_impose_H::T_ext(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_Face_implementation::trace(), Champ_P0_PolyMAC::trace(), Champ_P1iP1B_implementation::trace(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_face_local(), Frontiere::trace_som_local(), trait_part_calculer_ec_faces(), Moyenne_volumique::traiter_champs(), Transformer::transformer(), transp(), Trianguler_H::trianguler(), Trianguler_fin::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene::trianguler(), trier_index_colonne_i(), Echange_contact_PolyMAC::update_coeffs(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_CoviMAC_base::update_nu_invh(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre::val_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Entree_fluide_T_h_imposee::val_imp(), Temperature_imposee_paroi_H::val_imp(), Entree_fluide_temperature_imposee_H::val_imp(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Dirichlet::val_imp_au_temps(), valeur(), Champ_implementation_P0::valeur_a_elem(), Ch_front_input_P1::valeur_au_temps_et_au_point(), Champ_Fonc_base::valeur_aux(), Tayl_Green::valeur_aux(), Init_par_partie::valeur_aux(), Champ_Uniforme::valeur_aux(), champ_init_canal_sinal::valeur_aux(), Champ_Don_Fonc_txyz::valeur_aux(), Champ_base::valeur_aux_centres_de_gravite(), Champ_Fonc_Face::valeur_aux_compo(), Champ_Inc_base::valeur_aux_compo(), Champ_base::valeur_aux_compo(), Tayl_Green::valeur_aux_compo(), champ_init_canal_sinal::valeur_aux_compo(), Champ_som_lu_VDF::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems(), Champ_Uniforme_Morceaux::valeur_aux_elems(), Champ_Uniforme::valeur_aux_elems(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P0_PolyMAC::valeur_aux_faces(), Champ_base::valeur_aux_sommets(), Champ_base::valeur_aux_sommets_compo(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet_base::valeur_aux_sommets_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), valeur_P1_H1(), NettoieNoeuds::verifie_noeuds(), Op_Diff_VEF_Face::verifier(), Op_Diff_VEF_Anisotrope_Face::verifier(), verifier(), Loi_horaire::verifier_derivee(), Zone_PolyMAC::W_stabiliser(), and Format_Post_Lata::write_doubletab().
{
  assert(i >= 0 && i < nb_dim_);
// Si dimension_[0] == -1, c'est que c'est un vecteur distribue et que l'attribut size() est invalide.
// Il faut alors utiliser dimension_tot pour ce tableau.
  assert(dimensions_[i] >= 0);
  return dimensions_[i];
}
int DoubleTab::dimension_tot (int i) const [inline]
Returns the total dimensions of the multi-dimensionnal array, including
virtual items (used in parallel distributed arrays)
Definition at line 254 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, and nb_dim_.
Referenced by Debog_Pb::add_renum_item(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Fonc_Face_CoviMAC::affecter_(), Champ_Face_CoviMAC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Masse_PolyMAC_Elem::ajouter_masse(), Solveur_Masse_base::ajouter_masse(), Masse_PolyMAC_Face::appliquer_impl(), Masse_CoviMAC_Elem::appliquer_impl(), SETS::assembler(), Source_PDF_EF::associer_pb(), Octree_Double::build_nodes(), Ch_front_input::buildSommetsFaces(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Equation_base::calculer_champ_conserve(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Fluide_base::calculer_e_int(), Milieu_composite::calculer_energie_interne(), Fluide_reel_base::calculer_energie_interne(), Milieu_composite::calculer_enthalpie(), Fluide_reel_base::calculer_enthalpie(), calculer_inv_volume_special(), Milieu_composite::calculer_masse_volumique(), Fluide_reel_base::calculer_masse_volumique(), Fluide_base::calculer_nu(), Fluide_Weakly_Compressible::calculer_pression_hydro(), Fluide_Dilatable_base::calculer_pression_tot(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Op_Correlation::completer(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Octree_Double::compute_origin_factors(), OctreeRoot::construire(), corriger_incr_alpha(), Solveur_Masse_base::corriger_solution(), Fluide_base::creer_nu(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Solveur_Masse_base::dimensionner(), disp_dt(), diviser_par_rho_np1_face(), Format_Post_Lata::ecrire_domaine(), ecrit(), Source_WC_Chaleur_VEF::elem_to_face(), Source_WC_Chaleur_VDF::face_to_elem(), Discretisation_tools::faces_to_cells(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Equation_base::Gradient_conjugue_diff_impl(), Zone_Cl_EF::imposer_symetrie(), Equation_base::imprime_residu(), init_parts(), Fluide_Weakly_Compressible::initialiser_pth(), lit(), Op_EF_base::marque_elem(), Fluide_reel_base::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), modif_par_porosite_si_flag(), Domaine::nb_som_tot(), Discretisation_tools::nodes_to_cells(), Convection_Diffusion_Temperature::penalisation_L2(), Champ_Fonc_reprise::readOn(), Champ_input_P0::readOn(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Op_Diff_VEF_base::remplir_nu(), Champ_Input_Proto::setValueOnTab(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Champ_P0_PolyMAC::trace(), Schema_Temps_base::update_critere_statio(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_CoviMAC_base::update_nu_invh(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_Inc_base::valeur_aux(), Champ_Uniforme::valeur_aux(), Champ_Inc_base::valeur_aux_bords(), Champ_base::valeur_aux_bords(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_implementation_sommet_base::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Uniforme_Morceaux::valeur_aux_elems(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P0_PolyMAC::valeur_aux_faces(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_implementation_sommet_base::valeur_aux_sommets_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_Q1::value_interpolation(), Vecteur3::Vecteur3(), and verifier().
{
  assert(i >= 0 && i < nb_dim_);
  if (i == 0)
    return dimension_tot_0_;
  else
    return dimensions_[i];
}
int DoubleTab::duplique () const [virtual]
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
void DoubleTab::ecrit (Sortie & os) const [virtual]
ecriture des valeurs du tableau "raw" sans structure parallele
< le marqueur -1 indique que c'est le nouveau format "ecrit", sans structure parallele
Reimplemented from DoubleVect.
Definition at line 534 of file DoubleTab.cpp.
References dimension_tot(), dimensions_, finl, nb_dim_, and Sortie::put().
Referenced by Zone_VEF::ecrit(), Zone_PolyMAC::ecrit(), Zone_EF::ecrit(), Zone_CoviMAC::ecrit(), Zone_VF::printOn(), Champ_Inc_base::sauvegarder(), Champ_Fonc_base::sauvegarder(), and verifier().
{
  os << nb_dim_ << finl;
  if (nb_dim_ > 0)
    os.put(dimensions_, nb_dim_, nb_dim_);
  ArrOfInt tmp(nb_dim_);
  for (int i = 0; i < nb_dim_; i++)
    tmp[i] = dimension_tot(i);
  os << tmp;
  DoubleVect::ecrit(os);
}
const Type_info * DoubleTab::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
const Type_info * DoubleTab::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
Referenced by operator=(), and ref().
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
int DoubleTab::inverse_LU (const ArrOfDouble & b, ArrOfDouble & solution)
Resolution du systeme Ax=b.
Definition at line 720 of file DoubleTab.cpp.
References resoud_LU(), and ArrOfDouble::size_array().
{
  int n = b.size_array();
  ArrOfInt index(n);
  DoubleTab lu_dec(n,n);
  int cvg = (*this).decomp_LU(n,index,lu_dec);
// Cout<<"##DecompositionLU : origine"<<finl;
// int i,j;
// for (i=0;i<n;i++)
// {
// for (j=0;j<n;j++)
// {
// Cout<<"  "<<(*this)(i,j);
// }
// Cout<<finl;
// }
// Cout<<"##DecompositionLU : L"<<finl;
// for (i=0;i<n;i++)
// {
// for (j=0;j<i;j++)
// {
// Cout<<"  "<<lu_dec(i,j);
// }
// Cout<<"  1.00000e+00";
// for (j=i+1;j<n;j++)
// {
// Cout<<"  0.00000e+00";
// }
// Cout<<finl;
// }
// Cout<<"##DecompositionLU : U"<<finl;
// for (i=0;i<n;i++)
// {
// for (j=0;j<i;j++)
// {
// Cout<<"  0.00000e+00";
// }
// for (j=i;j<n;j++)
// {
// Cout<<"  "<<lu_dec(i,j);
// }
// Cout<<finl;
// }
  if(cvg == 1)
    {
      lu_dec.resoud_LU(n,index,b,solution);
    }
// Cout<<"Convergence decomposition matrice : "<<cvg<<finl;
  return cvg;
}
void DoubleTab::jump (Entree & is) [virtual]
Reimplemented from DoubleVect.
Definition at line 546 of file DoubleTab.cpp.
References lit().
Referenced by Champ_Generique_Statistiques_base::lire_bidon(), Operateurs_Statistique_tps::reprendre(), Postraitement::reprendre(), Champ_Inc_base::reprendre(), and Champ_Fonc_base::reprendre().
{
  DoubleTab::lit(is, 0 /* Do not resize&read the array */);
}
void DoubleTab::lit (Entree & is, int resize_and_read = 1) [virtual]
lecture d'un tableau pour reprise de calcul. On lit les valeurs "raw".
Attention, si le tableau n'est pas vide, il doit deja avoir la bonne
taille et la bonne structure, sinon erreur !
Parameter resize_and_read if the array is sized AND read (by default, yes)
Reimplemented from DoubleVect.
Definition at line 555 of file DoubleTab.cpp.
References Cerr, dimension(), dimension_tot(), Process::exit(), finl, DoubleVect::get_md_vector(), nb_dim_, Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), resize(), ArrOfDouble::size_array(), and DoubleVect::size_reelle_ok().
Referenced by jump(), Zone_VF::readOn(), Champ_Inc_base::reprendre(), and Champ_Fonc_base::reprendre().
{
  ArrOfInt tmp;
  is >> tmp;
  int ok = 1;
  if (tmp.size_array() != nb_dim_)
    ok = 0;
  if (ok)
    {
      if (size_reelle_ok() && dimension(0) != tmp[0])
        ok = 0;
      for (int i = 1; i < nb_dim_; i++)
        if (dimension(i) != tmp[i])
          ok = 0;
    }
  is >> tmp;
  if (ok && tmp.size_array() != nb_dim_)
    ok = 0;
  if (ok)
    for (int i = 0; i < nb_dim_; i++)
      if (dimension_tot(i) != tmp[i])
        ok = 0;
// Autorisation ancien format des champs scalaire 183:
  if (tmp.size_array()==1 && nb_dim_==2 && dimension(1)==1 && dimension_tot(0) == tmp[0])
    ok = 1;
  if (resize_and_read)
    {
      if (size_array() == 0 && (!get_md_vector().non_nul()))
        {
          resize(tmp, NOCOPY_NOINIT);
        }
      else
        {
          if (!ok)
            {
// Si on cherche a relire un tableau de taille inconnue, le tableau doit
// etre reset() a l'entree. On n'aura pas la structure parallele du tableau !
              Cerr << "Error in DoubleTab::lit: array has wrong dimensions" << finl;
              exit();
            }
        }
    }
  DoubleVect::lit(is,resize_and_read);
}
double DoubleTab::max_du_u (const DoubleTab & u)
Fonction utilisee pour le calcul du du/u (pour convergence implicite)
renvoie le max de abs(du(i)/u(i))
utilisation max_ = (u(n+1)-u(n)).max_du_u(u(n))
Definition at line 909 of file DoubleTab.cpp.
References ArrOfDouble::addr(), and ArrOfDouble::size_array().
{
  assert(size_array() == u.size_array());
  const double *du_ptr = addr();
  const double *u_ptr = u.addr();
  const double epsilon = 1.e-8;
  double res = 0.;
  for (int n = size_array(); n; n--)
    {
      double a = fabs(*du_ptr);
      double b = fabs(*u_ptr);
      double c = a / (b + epsilon);
      if (b > 1.e-2 && c > res)
        res = c;
      du_ptr++;
      u_ptr++;
    }
  return res;
}
int DoubleTab::nb_dim () const [inline]
Returns the number of dimensions of the array (>= 1)
Definition at line 264 of file DoubleTab.h.
References nb_dim_.
Referenced by Champ_Face::affecter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), T_It_Sou_VDF_Face< _TYPE_ >::ajouter(), T_It_Sou_VDF_Elem< _TYPE_ >::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Diff_VDF_var_Face_Axi::ajouter(), T_It_VDF_Face< _TYPE_ >::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Dift_VDF_var_Face_Axi::ajouter_contribution(), Op_Dift_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_var_Face_Axi::ajouter_contribution(), T_It_VDF_Face< _TYPE_ >::ajouter_contribution(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_vitesse(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_vitesse(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Matrice_Morse_Sym::ajouter_multTab_(), Matrice_Morse::ajouter_multTab_(), Matrice_Diagonale::ajouter_multTab_(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Masse_VDF_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Solveur_Masse_EF::appliquer_impl(), Simpler_Base::assembler_matrice_pression_implicite(), Op_Diff_VEF_base::associer(), build_triofield(), Champ_front_contact_VEF::calcul_grads_locaux(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Simple::calculer_correction_en_vitesse(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord(), T_It_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), calculer_gradientP1NC(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_min(), Op_Diff_VEF_Face_Stab::calculer_min(), Operateur_base::calculer_pour_post(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_CoviMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_CoviMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_standard(), Eval_Puiss_Th_QC_EF::calculer_terme_source_standard(), Discretisation_tools::cells_to_faces(), Scatter::Chercher_Correspondance(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Op_Correlation::completer(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), T_It_VDF_Face< _TYPE_ >::contribuer_au_second_membre(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre(), T_It_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre(), Op_PolyMAC_Elem::dimensionner(), Roue::dimensionner(), disp_dt(), diviser_par_rho_np1_face(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Debog_Pb::ecrire_gen(), ecrit(), EcritureLectureSpecial::ecriture_special(), Parser_Eval::eval_fct(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Ch_front_input_P1::getTemplate(), Ch_front_input::getTemplate(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_Diff_PolyMAC_base::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_Diff_CoviMAC_base::impr(), Op_Conv_CoviMAC_base::impr(), init_parts(), Navier_Stokes_std::initTimeStep(), inverser_par_diagonale(), Champ_Fonc_MED::lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), lire_special(), Champ_front_calc_interne::mettre_a_jour(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Zone_EF::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Zone_CoviMAC::nu_dot(), Operateur_base::ouvrir_fichier(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Champ_Fonc_reprise::readOn(), Op_Diff_EF::remplir_nu(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Champ_P0_PolyMAC::trace(), Raccord_distant_homogene::trace_face_distant(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), valeur(), Champ_implementation_P0::valeur_a_elem(), Champ_Uniforme::valeur_aux(), Champ_Don_Fonc_xyz::valeur_aux(), Champ_Don_Fonc_txyz::valeur_aux(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_som_lu_VDF::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Uniforme_Morceaux::valeur_aux_elems(), Champ_Uniforme::valeur_aux_elems(), Champ_Fonc_Morceaux::valeur_aux_elems(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems(), Champ_Don_lu::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P0_PolyMAC::valeur_aux_faces(), Champ_implementation_sommet_base::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_Q1::value_interpolation(), and Format_Post_Lata::write_doubletab().
{
  return nb_dim_;
}
double & DoubleTab::operator() (int i) [inline]
idem operator[]
Reimplemented from ArrOfDouble.
Definition at line 169 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return DoubleVect::operator[](i);
}
const double & DoubleTab::operator() (int i) const [inline]
Reimplemented from ArrOfDouble.
Definition at line 176 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return DoubleVect::operator[](i);
}
double & DoubleTab::operator() (int i1, int i2) [inline]
Definition at line 183 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 2);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  return DoubleVect::operator[](i1*dimensions_[1]+i2);
}
const double & DoubleTab::operator() (int i1, int i2) const [inline]
Definition at line 191 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 2);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  return DoubleVect::operator[](i1*dimensions_[1]+i2);
}
double & DoubleTab::operator() (int i1, int i2, int i3) [inline]
Definition at line 199 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 3);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  return DoubleVect::operator[]((i1*dimensions_[1]+i2)*dimensions_[2]+i3);
}
const double & DoubleTab::operator() (int i1, int i2, int i3) const [inline]
Definition at line 208 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 3);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  return DoubleVect::operator[]((i1*dimensions_[1]+i2)*dimensions_[2]+i3);
}
double & DoubleTab::operator() (int i1, int i2, int i3, int i4) [inline]
Definition at line 217 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 4);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  assert(i4 >= 0 && i4 < dimensions_[3]);
  return DoubleVect::operator[](((i1*dimensions_[1]+i2)*dimensions_[2]+i3)*dimensions_[3]+i4);
}
const double & DoubleTab::operator() (int i1, int i2, int i3, int i4) const [inline]
Definition at line 226 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 4);
  assert(i1 >= 0 && i1 < dimension_tot_0_);
  assert(i2 >= 0 && i2 < dimensions_[1]);
  assert(i3 >= 0 && i3 < dimensions_[2]);
  assert(i4 >= 0 && i4 < dimensions_[3]);
  return DoubleVect::operator[](((i1*dimensions_[1]+i2)*dimensions_[2]+i3)*dimensions_[3]+i4);
}
double & DoubleTab::operator() (const ArrOfInt & indice)
Definition at line 479 of file DoubleTab.cpp.
References nb_dim_, and ArrOfInt::size_array().
Referenced by operator()().
{
  assert(indice.size_array() == nb_dim_);
#if MAXDIM_TAB != 4
#error Mettre a jour le code pour MAXDIM_TAB ici
#endif
  switch(nb_dim_)
    {
    case 1:
      return operator()(indice[0]);
    case 2:
      return operator()(indice[0], indice[1]);
    case 3:
      return operator()(indice[0], indice[1], indice[2]);
    default:
      return operator()(indice[0], indice[1], indice[2], indice[3]);
    }
}
double DoubleTab::operator() (const ArrOfInt & indice) const
Definition at line 497 of file DoubleTab.cpp.
References nb_dim_, operator()(), and ArrOfInt::size_array().
{
  assert(indice.size_array() == nb_dim_);
#if MAXDIM_TAB != 4
#error Mettre a jour le code pour MAXDIM_TAB ici
#endif
  switch(nb_dim_)
    {
    case 1:
      return operator()(indice[0]);
    case 2:
      return operator()(indice[0], indice[1]);
    case 3:
      return operator()(indice[0], indice[1], indice[2]);
    default:
      return operator()(indice[0], indice[1], indice[2], indice[3]);
    }
}
DoubleTab & DoubleTab::operator= (double x)
idem que ArrOfDouble::operator=(double)
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 460 of file DoubleTab.cpp.
References operator=().
{
  DoubleVect::operator=(d);
  return *this;
}
DoubleTab & DoubleTab::operator= (const DoubleTab & src)
copie la structure et les valeurs du tableau src
Restrictions et preconditions identiques a DoubleVect::operator=(const DoubleVect & v)
Reimplemented in DoubleTrav.
Definition at line 421 of file DoubleTab.cpp.
References copy().
Referenced by operator=().
{
  copy(src);
  return *this;
}
DoubleTab& DoubleTab::operator= (const FDoubleTab &)
DoubleTab & DoubleTab::operator= (const DoubleVect & src)
copie la structure et les valeurs de src.
Attention: appel invalide si src est un type derive de Vect
(sinon quoi faire, un tableau unidimensionnel, ou une copie de la structure ?)
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 430 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, DoubleVect::copy_(), dimension_tot_0_, dimensions_, DoubleVect::get_info(), info(), DoubleVect::line_size(), nb_dim_, ArrOfDouble::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and sz.
{
  assert(src.get_info() == DoubleVect::info());
  DoubleVect::copy_(src);
// Idem que dans ref(DoubleVect) pour le nombre de dimensions du tableau cree
  const int l = src.line_size();
  if (l == 1)
    {
      nb_dim_ = 1;
    }
  else
    {
      nb_dim_ = 2;
      dimensions_[1] = l;
    }
  if (src.size_reelle_ok())
    {
      int sz = src.size_reelle();
      dimensions_[0] = sz / l;
      assert(sz % l == 0);
    }
  else
    {
      dimensions_[0] = -1;
    }
  dimension_tot_0_ = size_array() / l;
  assert(CHECK_LINE_SIZE);
  return *this;
}
const double & DoubleTab::operator[] (int i) const [inline]
operateur [] retourne le ieme element du tableau
Reimplemented from ArrOfDouble.
Definition at line 162 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, nb_dim_, and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return DoubleVect::operator[](i);
}
double & DoubleTab::operator[] (int i) [inline]
operateur [] retourne le ieme element du tableau
Reimplemented from ArrOfDouble.
Definition at line 155 of file DoubleTab.h.
References dimension_tot_0_, dimensions_, and nb_dim_.
Referenced by operator()(), and operator[]().
{
  assert(nb_dim_ == 1 || (nb_dim_ == 2 && dimensions_[1] == 1));
  assert(i >= 0 && i < dimension_tot_0_);
  return DoubleVect::operator[](i);
}
Sortie & DoubleTab::printOn (Sortie & x) const [protected, virtual]
ecriture d'un tableau sequentiel
(idem que DoubleVect::printOn() on ne sait pas quoi faire de pertinent
pour un tableau distribue).
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 48 of file DoubleTab.cpp.
References ArrOfDouble::addr(), Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, DoubleVect::get_md_vector(), DoubleVect::line_size(), nb_dim_, Process::nproc(), Sortie::put(), ArrOfDouble::size_array(), and sz.
{
  assert(CHECK_LINE_SIZE);
  if (nproc() > 1 && get_md_vector().non_nul())
    {
      Cerr << "Error in DoubleTab::printOn: try to print a parallel vector" << finl;
      exit();
    }
  os << nb_dim_ << finl;
  assert(dimensions_[0] == dimension_tot_0_);
  if (nb_dim_ > 0)
    os.put(dimensions_, nb_dim_, nb_dim_);
  const int sz = size_array();
  os << sz << finl;
  const int l_size = line_size();
  const double *data = addr();
  if (sz > 0)
    os.put(data, sz, l_size);
  return os;
}
Entree & DoubleTab::readOn (Entree & is) [protected, virtual]
lecture d'un tableau sequentiel
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 72 of file DoubleTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, Entree::get(), DoubleVect::get_md_vector(), MAXDIM_TAB, nb_dim_, DoubleVect::set_line_size_(), and ArrOfDouble::size_array().
{
  if (get_md_vector().non_nul())
    {
// Que veut-on faire si on lit dans un vecteur ayant deja une structure parallele ?
      Cerr << "Error in DoubleTab::readOn: vector has a parallel structure" << finl;
      exit();
    }
  is >> nb_dim_;
  if (nb_dim_ < 1 || nb_dim_ > MAXDIM_TAB)
    {
      Cerr << "Error in DoubleTab::readOn: wrong nb_dim_ = " << nb_dim_ << finl;
      exit();
    }
  is.get(dimensions_, nb_dim_);
  if (dimensions_[0] < 0)
    {
      Cerr << "Error in DoubleTab::readOn: wrong dimension(0) = " << dimensions_[0] << finl;
      exit();
    }
  int l_size = 1;
  for (int i = 1; i < nb_dim_; i++)
    {
      if (dimensions_[i] < 0)
        {
          Cerr << "Error in DoubleTab::readOn: wrong dimension(" << i << ") = " << dimensions_[i] << finl;
          exit();
        }
      l_size *= dimensions_[i];
    }
  dimension_tot_0_ = dimensions_[0];
  DoubleVect::readOn(is);
  set_line_size_(l_size);
  if (dimension_tot_0_ * l_size != size_array())
    {
      Cerr << "Error in DoubleTab::readOn: wrong size_array " << size_array()
           << ", expected " << dimension_tot_0_ * l_size << finl;
      exit();
    }
  assert(CHECK_LINE_SIZE);
  return is;
}
void DoubleTab::ref (const DoubleVect & v) [virtual]
fait pointer le tableau sur le vecteur v et en associant
la meme structure parallele.
Attention, si line_size du vecteur v est different de 1,
on cree un tableau bidimensionnel (on peut avoir un vecteur
de ce type si on copie un Tab dans un Vect puis on prend
une ref sur ce Vect).
Reimplemented from DoubleVect.
Definition at line 211 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, DoubleVect::get_info(), info(), DoubleVect::line_size(), nb_dim_, ArrOfDouble::size_array(), DoubleVect::size_reelle(), DoubleVect::size_reelle_ok(), and sz.
Referenced by Op_Conv_VEF_Face::ajouter(), Solveur_Masse_base::appliquer(), Masse_PolyMAC_Face::appliquer_coef(), Masse_PolyMAC_Elem::appliquer_coef(), Op_Dift_VDF_var_Face_Axi::associer(), Op_Dift_VDF_Face_Axi::associer(), Op_Diff_VDF_var_Face_Axi::associer(), Op_Diff_VDF_Face_Axi::associer(), Op_Grad_VDF_Face::associer(), Op_Grad_P0_to_Face::associer(), Eval_Diff_VDF_var_aniso::associer(), Eval_Diff_VDF_Multi_inco_var::associer(), Eval_Conv_VDF::associer(), Op_Grad_PolyMAC_Face::associer(), Eval_Conv_PolyMAC::associer(), Eval_Source_C_VEF_Face::associer_champs(), Eval_Puiss_Th_VEF_Face::associer_champs(), Eval_Source_C_VDF_Elem::associer_champs(), Eval_Puiss_Th_VDF_Elem::associer_champs(), Eval_Echange_Himp_VDF_Elem::associer_champs(), Eval_Source_C_PolyMAC_Elem::associer_champs(), Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Eval_Puiss_Th_EF::associer_champs(), Eval_Source_C_CoviMAC_Elem::associer_champs(), Eval_Puiss_Th_CoviMAC_Elem::associer_champs(), Eval_Puiss_Th_QC_VEF_Face::associer_puissance(), Eval_Puiss_Th_QC_VDF_Elem::associer_puissance(), Eval_Puiss_Th_QC_EF::associer_puissance(), Evaluateur_VDF::associer_zones(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_PolyMAC::associer_zones(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Eval_Conv_PolyMAC::Eval_Conv_PolyMAC(), Eval_Conv_VDF::Eval_Conv_VDF(), Evaluateur_PolyMAC::Evaluateur_PolyMAC(), Evaluateur_VDF::Evaluateur_VDF(), Champ_P1NC_implementation::filtrer_L2(), Equation_base::Gradient_conjugue_diff_impl(), init_parts(), Loi_Etat_GR_base::initialiser(), Op_Dift_VEF_base::mettre_a_jour(), Eval_Echange_Himp_VDF_Elem::mettre_a_jour(), Op_Dift_VDF_var_Face_Axi::mettre_a_jour(), Op_Dift_VDF_Face_Axi::mettre_a_jour(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Eval_Dift_VDF_const_Face::mettre_a_jour(), Eval_Diff_VDF_var_aniso::mettre_a_jour(), Eval_Conv_VDF::mettre_a_jour(), Eval_Conv_PolyMAC::mettre_a_jour(), modif_par_porosite_si_flag(), ref(), Table::remplir(), Champ_Q1NC_impl::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_Face_implementation::remplir_coord_noeuds(), Refine_Mesh::update_nodes(), and Champ_Inc_base::valeur_aux_bords().
{
  assert(v.get_info() == DoubleVect::info());
  DoubleVect::ref(v);
  const int l = v.line_size();
// Attention:
// En prenant la ref, on est oblige de conserver l'attribut line_size
// du Vect (sinon echange_espace_virtuel ne fonctionnera pas car
// on n'aura pas le bon facteur multiplicatif des items geometriques)
// Si on voulait creer un tableau monodimensionnel avec line_size > 1,
// le tableau devient invalide car on n'a plus line_size = produit des
// dimensions > 1.
// On peut le faire a condition de laisser tomber le md_vector_ en
// faisant  tab.ref_array(v) au lieu de  tab.ref(v)
  if (l == 1)
    {
      nb_dim_ = 1;
    }
  else
    {
      nb_dim_ = 2;
      dimensions_[1] = l;
    }
  if (v.size_reelle_ok())
    {
      int sz = v.size_reelle();
      dimensions_[0] = sz / l;
    }
  else
    {
      dimensions_[0] = -1;
    }
  dimension_tot_0_ = size_array() / l;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::ref (const DoubleTab & src) [virtual]
fait pointer le tableau sur le tableau t
en recuperant la structure parallele. Attention,
on fige le tableau qui ne pourra plus etre resize
Definition at line 250 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, MAXDIM_TAB, nb_dim_, and ref().
{
  DoubleVect::ref(src);
  nb_dim_ = src.nb_dim_;
  for (int i = 0; i < MAXDIM_TAB; i++)
    dimensions_[i] = src.dimensions_[i];
  dimension_tot_0_ = src.dimension_tot_0_;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::ref_array (ArrOfDouble & src, int start = 0, int sz = -1) [virtual]
identique a DoubleVect::ref_array()
(cree un tableau monodimensionnel sans structure parallele)
Attention, le tableau source et destination sont figes (resize interdit)
(voir ArrOfDouble::
< pas sz qui peut valoir -1
Reimplemented from DoubleVect.
Definition at line 274 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, DoubleVect::get_md_vector(), nb_dim_, ArrOfDouble::size_array(), and DoubleVect::size_reelle().
Referenced by init_parts(), ref_tab(), Solv_Gen::solve(), and Debog_Pb::verifier_partie().
{
  DoubleVect::ref_array(src, start, sz);
  assert(!get_md_vector().non_nul() && size_reelle() == size_array());
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = size_array(); //!< pas sz qui peut valoir -1
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::ref_data (double * ptr, int size) [virtual]
identique a DoubleVect::ref_data()
Reimplemented from DoubleVect.
Definition at line 261 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, DoubleVect::get_md_vector(), nb_dim_, ArrOfDouble::size_array(), and DoubleVect::size_reelle().
{
  DoubleVect::ref_data(ptr, new_size);
  assert(!get_md_vector().non_nul() && size_reelle() == size_array());
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = new_size;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::ref_tab (DoubleTab & t, int start_line = 0, int nb_lines = -1) [virtual]
fait pointer le tableau sur une sous-partie du tableau t
definie par la valeur du premier indice et ne nombre de "lignes" du tableau
a recuperer (une ligne = toutes les valeurs tab(i,j,k,...) pour un i donne).
Le nombre de dimensions du tableau est le meme que pour t,
les dimension(i) pour i>=1 sont les memes et dimension(0) = nb_lines.
Definition at line 288 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, DoubleVect::get_md_vector(), DoubleVect::line_size(), MAXDIM_TAB, nb_dim_, ref_array(), DoubleVect::set_line_size_(), ArrOfDouble::size_array(), and DoubleVect::size_reelle().
Referenced by Champ_Inc_base::affecter_().
{
  if (nb_lines < 0)
    nb_lines = t.dimension_tot_0_ - start_line;
  assert(start_line >= 0 && nb_lines >= 0 && start_line + nb_lines <= t.dimension_tot_0_);
  const int l_size = t.line_size();
  DoubleVect::ref_array(t, start_line * l_size, nb_lines * l_size);
  assert(!get_md_vector().non_nul() && size_reelle() == size_array());
  set_line_size_(l_size);
  nb_dim_ = t.nb_dim_;
  dimension_tot_0_ = nb_lines;
  dimensions_[0] = nb_lines;
  for (int i = 1; i < MAXDIM_TAB; i++)
    dimensions_[i] = t.dimensions_[i];
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::reset () [virtual]
met le tableau dans l'etat obtenu par le constructeur par defaut
voir DoubleVect::reset()
Reimplemented from DoubleVect.
Definition at line 307 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, and nb_dim_.
Referenced by Op_Ecart_type::completer(), Tri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Hexa_VEF::creer_facette_normales(), ExtrudeParoi::extrude(), Extruder_en20::extruder(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Postraitement_lata::postraiter_liste_champs(), Domaine::read_vertices(), Domaine::readOn(), Operateurs_Statistique_tps::reprendre(), Roue::supprimer_case(), and Moyenne_volumique::traiter_champs().
{
  nb_dim_ = 1;
  dimensions_[0] = 0;
  dimension_tot_0_ = 0;
  DoubleVect::reset();
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize (int n, Array_base::Resize_Options opt = COPY_INIT)
Change la taille du vecteur (identique a resize_array()
pour le traitement des anciennes valeurs et de nouvelles cases).
Attention: Cette methode n'est pas virtuelle, et afin d'eviter d'amener
un DoubleTab dans un etat invalide, l'appel est interdit si l'objet
est de ce type. Dans ce cas, voir resize_tab.
Reimplemented from DoubleVect.
Definition at line 335 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, nb_dim_, DoubleVect::resize_vect_(), and DoubleVect::set_line_size_().
Referenced by BlocData::add_bloc(), add_sommets_communs(), Champ_P1NC::affecter_(), Champ_Fonc_Face_CoviMAC::affecter_(), Champ_Face_CoviMAC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), T_It_VDF_Face< _TYPE_ >::ajouter(), T_It_VDF_Elem< _TYPE_ >::ajouter(), Op_Div_PolyMAC::ajouter(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Domaine::ajouter(), Op_Div_EF::ajouter(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), T_It_VDF_Face< _TYPE_ >::ajouter_contribution(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution(), T_It_PolyMAC_Elem< _TYPE_ >::ajouter_contribution(), Zone_PolyMAC::ajouter_stabilisation(), SETS::assembler(), Assembleur_P_EF::assembler_mat(), Zone_Cl_VEF::associer(), Eval_Darcy_VEF_Face::associer(), Eval_Darcy_VDF_Face::associer(), Pave::associer_domaine(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), auto_build_joints(), Refine_Mesh::build_new_nodes(), build_nodes(), Ch_front_input::buildSommetsFaces(), Calcul_integrale_locale::Calcul_integrale_locale(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Calcul_integrale_locale::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Zone_EF::calculer_Bij(), Aretes::calculer_centre_de_gravite(), Rectangle_axi::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), calculer_centres_gravite(), Elem_geom_base::calculer_centres_gravite(), Zone::calculer_centres_gravite_aretes(), Equation_base::calculer_champ_conserve(), Zone_VF::calculer_diametres_hydrauliques(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Fluide_base::calculer_e_int(), Milieu_composite::calculer_energie_interne(), Fluide_reel_base::calculer_energie_interne(), Milieu_composite::calculer_enthalpie(), Fluide_reel_base::calculer_enthalpie(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord(), T_It_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Assembleur_P_VEF::calculer_inv_volume(), calculer_inv_volume(), Zone_EF_axi::calculer_IPhi(), Zone_EF::calculer_IPhi(), Milieu_composite::calculer_masse_volumique(), Fluide_reel_base::calculer_masse_volumique(), Echange_contact_VDF::calculer_Teta_paroi(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Zone_VDF::calculer_volumes_entrelaces(), Zone_PolyMAC::calculer_volumes_entrelaces(), caldscaldcentelemdim2(), caldscaldcentelemdim3(), calrotord2centelemdim2(), calrotord2centelemdim3(), Scatter::check_consistancy_remote_items(), Echange_contact_Correlation_VEF::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Echange_contact_Correlation_VDF::completer(), Source_Neutronique::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_base::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Op_Correlation::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), Op_Diff_CoviMAC_base::completer(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Bashforth_order_2::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Scatter::construire_correspondance_items_par_coordonnees(), Matrice_Morse::construire_sous_bloc(), Op_Conv_VEF_Face::contribue_au_second_membre(), T_It_VDF_Face< _TYPE_ >::contribuer_au_second_membre(), convert_domain_to_Domaine(), Tri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Hexa_VEF::creer_facette_normales(), Fluide_base::creer_nu(), Champ_Inc_base::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Roue::dimensionner(), Matrice_Dense::dimensionner(), Champ_Face::dimensionner_tenseur_Grad(), Zone_VEF::discretiser(), Zone_PolyMAC::discretiser(), Sous_zone_VF::discretiser(), Zone_EF::discretiser(), Zone_CoviMAC::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), DoubleTrav::DoubleTrav(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder_en3::extruder(), Extruder::extruder(), Extruder::extruder_hexa(), ExtrudeBord::extruder_hexa_old(), Zone_CoviMAC::fgrad(), Echange_contact_CoviMAC::fgrad(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Don_base::fixer_nb_valeurs_nodales(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_front_recyclage::get_coord_faces(), Champ_front_instationnaire_base::Gpoint(), Zone::identifie_item_unique(), Op_Grad_VDF_Face::impr(), Op_Grad_PolyMAC_Face::impr(), T_It_PolyMAC_Elem< _TYPE_ >::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Champ_P0_VDF::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_Face_implementation::imprime_Face(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_stats(), Traitement_particulier_NS_Profils::init_calcul_stats(), Champ_Inc_base::init_champ_calcule(), Champ_implementation_P1::init_from_file(), Zone_PolyMAC::init_m1_3d(), Zone_PolyMAC::init_m2(), Op_Diff_CoviMAC_base::init_op_ext(), init_parts(), Champ_Face_PolyMAC::init_ra(), Echange_contact_Correlation_VDF::init_tab_echange(), Champ_Face_PolyMAC::init_va(), Zone_PolyMAC::init_ve(), Zone_CoviMAC::init_ve(), Zone_PolyMAC::init_we_3d(), Echange_contact_VDF::initialiser(), Loi_Etat_GR_base::initialiser(), Echange_contact_PolyMAC::initialiser(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), Champ_front_var::initialiser(), Ch_front_input_P1::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Loi_Etat_Multi_GP_base::initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Moyenne_volumique::interpreter(), latatoother::interpreter(), Raffiner_isotrope_parallele::interpreter(), VerifierCoin::interpreter_(), Lire_Tgrid::interpreter_(), Lire_Ideas::interpreter_(), Extraire_plan::interpreter_(), kersol(), Traitement_particulier_NS_Brech_VEF::lire(), Champ_front_recyclage::lire_fichier_format3(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Pave::lire_Noeuds(), lit(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), mon_construire_correspondance_items_par_coordonnees(), Op_Grad_CoviMAC_Face::mu_f(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Format_Post_base::postraiter_debug_valeurs_un_instant(), Postraitement_lata::postraiter_liste_champs(), Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Raffiner_anisotrope::Raffiner_anisotrope_(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Flux_interfacial_Coef_Constant::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_pression_imposee::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Champ_front_MED::readOn(), Sonde_Int::readOn(), Sonde::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Tabule_Morceaux::readOn(), Champ_input_P0::readOn(), Champ_front_uniforme::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Ch_input_uniforme::readOn(), Assembleur_P_VEF::remplir(), Champ_P0_VDF::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds(), Champ_implementation_P0::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), remplir_coordsommets_sous_domaine(), Op_Diff_VEF_base::remplir_nu(), Ensemble_Lagrange_base::remplir_sommets_tmp(), Zone_EF_axi::remplir_tableau_origine(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_canal::reprendre_stat_canal(), resize_tab(), MD_Vector_tools::restore_vector_with_md(), Simple::Simple(), Solv_Gen::solve(), Champ_P0_PolyMAC::trace(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), Frontiere::trace_som_local(), Moyenne_volumique::traiter_champs(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Trianguler_H::trianguler(), Trianguler_fin::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene::trianguler(), Echange_contact_PolyMAC::update_coeffs(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_CoviMAC::valeur_aux_faces(), Zone_VEF::vecteur_face_facette(), Zone_PolyMAC::W_stabiliser(), and Zone_VF::xv_bord().
{
  assert(n >= 0);
  set_line_size_(1);
  DoubleVect::resize_vect_(n, opt);
  nb_dim_ = 1;
  dimensions_[0] = dimension_tot_0_ = n;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize (int n1, int n2, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 345 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, nb_dim_, DoubleVect::resize_vect_(), and DoubleVect::set_line_size_().
{
  assert(n >= 0 && n2 >= 0);
  set_line_size_(n2);
  int new_size = n * n2;
  DoubleVect::resize_vect_(new_size, opt);
  nb_dim_ = 2;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize (int n1, int n2, int n3, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 358 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, nb_dim_, DoubleVect::resize_vect_(), and DoubleVect::set_line_size_().
{
  assert(n >= 0 && n2 >= 0 && n3 >= 0);
  set_line_size_(n2 * n3);
  int new_size = n * n2 * n3;
  DoubleVect::resize_vect_(new_size, opt);
  nb_dim_ = 3;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  dimensions_[2] = n3;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt = COPY_INIT)
Definition at line 372 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, nb_dim_, DoubleVect::resize_vect_(), and DoubleVect::set_line_size_().
{
  assert(n >= 0 && n2 >= 0 && n3 >= 0 && n4 >= 0);
  set_line_size_(n2 * n3 * n4);
  int new_size = n * n2 * n3 * n4;
  DoubleVect::resize_vect_(new_size, opt);
  nb_dim_ = 4;
  dimensions_[0] = dimension_tot_0_ = n;
  dimensions_[1] = n2;
  dimensions_[2] = n3;
  dimensions_[3] = n4;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize (const ArrOfInt & tailles, Array_base::Resize_Options opt = COPY_INIT)
redimensionne le tableau (nb_dim_ sera egal a tailles.size_array()
et dimension(i) a tailles[i].
Definition at line 390 of file DoubleTab.cpp.
References Cerr, CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, Process::exit(), finl, MAXDIM_TAB, nb_dim_, DoubleVect::resize_vect_(), DoubleVect::set_line_size_(), and ArrOfInt::size_array().
{
  nb_dim_ = tailles.size_array();
  if (nb_dim_ <= 0 || nb_dim_ > MAXDIM_TAB)
    {
      Cerr << "Internal error in DoubleTab::resize(const ArrOfInt & tailles, ...) \n"
           << " wrong dimensions number " << nb_dim_ << finl;
      exit();
    }
  int l_size = 1;
  for (int i = 0; i < nb_dim_; i++)
    {
      const int n = tailles[i];
      dimensions_[i] = n;
      if (i > 0)
        l_size *= n;
      if (n < 0)
        {
          Cerr << "Internal error in DoubleTab::resize(const ArrOfInt & tailles, ...) \n"
               << " wrong dimensions: " << tailles << finl;
          exit();
        }
    }
  dimension_tot_0_ = dimensions_[0];
  set_line_size_(l_size);
  resize_vect_(dimensions_[0] * l_size, opt);
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize_dim0 (int n, Array_base::Resize_Options opt = COPY_INIT)
change la dimension[0] du tableau en conservant les autres.
Definition at line 326 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, DoubleVect::line_size(), DoubleVect::resize_vect_(), and ArrOfDouble::size_array().
{
  assert(n >= 0);
  assert(dimension_tot_0_ * line_size() == size_array());
  DoubleVect::resize_vect_(n * line_size(), opt);
  dimensions_[0] = dimension_tot_0_ = n;
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resize_tab (int n, Array_base::Resize_Options opt = COPY_INIT) [virtual]
methode virtuelle qui force le tableau a changer de taille.
Change aussi nb_dim_ a 1. Equivalent a DoubleTab::resize(n, opt)
Reimplemented from DoubleVect.
Definition at line 318 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, and resize().
{
  resize(n, opt);
  assert(CHECK_LINE_SIZE);
}
void DoubleTab::resoud_LU (int n, ArrOfInt & index, const ArrOfDouble & b, ArrOfDouble & solution)
Resolution du systeme A_x=b
A_ contenant le decompostion LU de A (stockee dans une seule matrice)
Definition at line 865 of file DoubleTab.cpp.
Referenced by inverse_LU().
{
  int i,ii=-1,ip,j;
  double sum;
  solution = b;
  for (i=0 ; i<n ; i++)
    {
      ip = index(i);
      sum = solution(ip);
      solution(ip) = solution(i);
      if (ii!=-1)
        {
          for (j=ii ; j<i ; j++)
            {
              sum -= (*this)(i,j)*solution(j);
            }
        }
      else
        {
          if (sum)
            {
              ii =i;
            }
        }
      solution(i) = sum;
    }
  for (i=n-1 ; i>=0 ; i--)
    {
      sum = solution(i);
      for (j=i+1 ; j<n ; j++)
        {
          sum -= (*this)(i,j)*solution(j);
        }
      solution(i) = sum/(*this)(i,i);
    }
}
DoubleTab & DoubleTab::self_cast (Objet_U & r) [static]
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
const DoubleTab & DoubleTab::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
void DoubleTab::set_md_vector (const MD_Vector & md_vector) [virtual]
associe le md_vector au vecteur (voir DoubleVect::set_md_vector())
dimension(0) sera initialise a md_vector...get_nb_items_reels().
Reimplemented from DoubleVect.
Definition at line 520 of file DoubleTab.cpp.
References CHECK_LINE_SIZE, dimension_tot_0_, dimensions_, MD_Vector_base::get_nb_items_reels(), MD_Vector::non_nul(), and MD_Vector::valeur().
Referenced by Domaine::ajouter(), calculer_centres_gravite(), Scatter::construire_structures_paralleles(), DoubleTrav::DoubleTrav(), init_parts(), Scatter::init_sequential_domain(), Debog_Pb::read_geometry_data(), Champ_Fonc_MED::readOn(), MD_Vector_tools::restore_vector_with_md(), Solv_Gen::solve(), and Scatter::uninit_sequential_domain().
{
  int dim0 = dimension_tot_0_;
  if (md_vector.non_nul())
    {
// renvoie -1 si l'appel et invalide:
      dim0 = md_vector.valeur().get_nb_items_reels();
    }
  dimensions_[0] = dim0;
  assert(CHECK_LINE_SIZE);
// a appeler meme pour un md_vector nul (pour remettre size_reelle_):
  DoubleVect::set_md_vector(md_vector);
}
unsigned DoubleTab::taille_memoire () const [virtual]
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 33 of file DoubleTab.cpp.
:1)*((nb_dim_>2)?dimensions_[2]:1)*((nb_dim_>3)?dimensions_[3]:1)) \
Member Data Documentation
int DoubleTab::dimension_tot_0_ [private]
Definition at line 132 of file DoubleTab.h.
Referenced by append_line(), copy(), dimension_tot(), operator()(), operator=(), operator[](), printOn(), readOn(), ref(), ref_array(), ref_data(), ref_tab(), reset(), resize(), resize_dim0(), and set_md_vector().
int DoubleTab::dimensions_[4] [private]
Definition at line 127 of file DoubleTab.h.
Referenced by append_line(), copy(), dimension(), dimension_tot(), DoubleTab(), ecrit(), operator()(), operator=(), operator[](), printOn(), readOn(), ref(), ref_array(), ref_data(), ref_tab(), reset(), resize(), resize_dim0(), and set_md_vector().
const Type_info DoubleTab::info_obj [static]
Reimplemented from DoubleVect.
Reimplemented in DoubleTrav.
Definition at line 51 of file DoubleTab.h.
int DoubleTab::nb_dim_ [private]
Definition at line 124 of file DoubleTab.h.
Referenced by copy(), dimension(), dimension_tot(), ecrit(), lit(), nb_dim(), operator()(), operator=(), operator[](), printOn(), readOn(), ref(), ref_array(), ref_data(), ref_tab(), reset(), and resize().
The documentation for this class was generated from the following files:
src/Kernel/Math/DoubleTab.h
src/Kernel/Math/DoubleTab.cpp