TRUST: Polyedriser Class Reference
Polyedriser Class Reference
Polyedriser
Classe destinee a convertir un hexaedre en polyedre.
#include <Polyedriser.h>
Public Member Functions
Polyedriser ()
~Polyedriser ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void polyedriser (Zone &) const
int dimension_application () const
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Polyedriser & self_cast (Objet_U &)
static const Polyedriser & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Polyedriser
Classe destinee a convertir un hexaedre en polyedre.
Definition at line 27 of file Polyedriser.h.
Constructor & Destructor Documentation
Polyedriser()
Polyedriser::Polyedriser ()
Definition at line 45 of file Polyedriser.cpp.
~Polyedriser()
Polyedriser::~Polyedriser ()
Definition at line 45 of file Polyedriser.cpp.
Member Function Documentation
cree_instance()
Objet_U * Polyedriser::cree_instance () static
Definition at line 45 of file Polyedriser.cpp.
dimension_application()
int Polyedriser::dimension_application () const inline
Definition at line 33 of file Polyedriser.h.
  {
    return 3;
  }
Referenced by interpreter_().
duplique()
int Polyedriser::duplique () const override virtual
Implements Objet_U.
Definition at line 45 of file Polyedriser.cpp.
get_info()
const Type_info * Polyedriser::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 45 of file Polyedriser.cpp.
info()
const Type_info * Polyedriser::info () static
Definition at line 45 of file Polyedriser.cpp.
interpreter_()
Entree & Polyedriser::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 245 of file Polyedriser.cpp.
{
  if(dimension !=dimension_application())
    {
      Cerr << "Interpreter "<<que_suis_je()<<" cannot be applied for dimension " << dimension <<finl;
      exit();
    }
  if (Process::nproc()>1)
    {
      Cerr << "Interpreter "<<que_suis_je()<<" cannot be applied during a parallel calculation !" << finl;
      Cerr << "The mesh can't be changed after it has been partitioned." << finl;
      Process::exit();
    }
  associer_domaine(is);
  Scatter::uninit_sequential_domain(domaine());
  for(int i=0; i<domaine().nb_zones() ; i++)
    {
      polyedriser(domaine().zone(i));
    }
  Scatter::init_sequential_domain(domaine());
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Cerr, Objet_U::dimension, dimension_application(), Interprete_geometrique_base::domaine(), Process::exit(), finl, Scatter::init_sequential_domain(), Domaine::nb_zones(), Process::nproc(), polyedriser(), Objet_U::que_suis_je(), and Scatter::uninit_sequential_domain().
polyedriser()
void Polyedriser::polyedriser (Zone & zone) const
< Index des polyedres
< Index des faces:
Definition at line 165 of file Polyedriser.cpp.
{
  if(zone.type_elem()->que_suis_je() == "Hexaedre")
    {
      zone.typer("Polyedre");
      Polyedre& p = ref_cast(Polyedre, zone.type_elem().valeur());
      ArrOfInt Pi, Fi, N;
      const IntTab& elements = zone.les_elems();
      int nb_elems = elements.dimension(0);
      Pi.resize_array(nb_elems+1);
      Fi.resize_array(nb_elems*6+1);
      N.resize_array(nb_elems*24);
      int face = 0;
      int node = 0;
      for (int e = 0; e < nb_elems; e++)
        {
          Pi[e] = face; //!< Index des polyedres
          for(int f=0; f<6; f++)
            {
              Fi[face] = face*4; //!< Index des faces:
              for(int s=0; s<4; s++)
                {
                  int som_loc = faces_sommets_poly[f][s];
                  N[node] = elements(e, som_loc);
                  node++;
                }
              face++;
            }
        }
      Fi[nb_elems*6] = node;
      Pi[nb_elems] = face;
      p.affecte_connectivite_numero_global(N, Fi, Pi, zone.les_elems());
    }
  else
    {
      Cerr << "We do not yet know how to Polyedriser the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
      exit();
    }
  const DoubleTab coords = zone.domaine().coord_sommets();
  {
    LIST_CURSEUR(Bord) curseur(zone.faces_bord());
    while(curseur)
      {
        Faces& les_faces=curseur->faces();
        les_faces.typer(Faces::polygone_3D);
        reorder_vertices(les_faces, coords);
        ++curseur;
      }
  }
  {
// Les Raccords
    LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());
    while(curseur)
      {
        Faces& les_faces=curseur.valeur()->faces();
        les_faces.typer(Faces::polygone_3D);
        reorder_vertices(les_faces, coords);
        ++curseur;
      }
  }
  {
// Les Faces internes
    LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());
    while(curseur)
      {
        Faces& les_faces=curseur->faces();
        les_faces.typer(Faces::polygone_3D);
        reorder_vertices(les_faces, coords);
        ++curseur;
      }
  }
  return;
}
References Polyedre::affecte_connectivite_numero_global(), Cerr, Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_raccord(), faces_sommets_poly, finl, Zone::les_elems(), LIST_CURSEUR, Faces::polygone_3D, Objet_U::que_suis_je(), ref_cast, reorder_vertices(), TRUSTArray< _TYPE_ >::resize_array(), Zone::type_elem(), Faces::typer(), Zone::typer(), and Deriv_Elem_geom_base::valeur().
Referenced by interpreter_().
printOn()
Sortie & Polyedriser::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 49 of file Polyedriser.cpp.
{
  return os;
}
readOn()
Entree & Polyedriser::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 54 of file Polyedriser.cpp.
{
  return is;
}
self_cast() [1/2]
const Polyedriser & Polyedriser::self_cast (const Objet_U & r) static
Definition at line 45 of file Polyedriser.cpp.
self_cast() [2/2]
Polyedriser & Polyedriser::self_cast (Objet_U & r) static
Definition at line 45 of file Polyedriser.cpp.
taille_memoire()
unsigned Polyedriser::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 45 of file Polyedriser.cpp.
Member Data Documentation
info_obj
const Type_info Polyedriser::info_obj static
Definition at line 29 of file Polyedriser.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Polyedriser.h
src/Kernel/Geometrie/Polyedriser.cpp