TRUST: Terme_Source_Constituant Class Reference
Terme_Source_Constituant Class Reference
Classe Terme_Source_Constituant
Cette classe represente un terme source de l'equation de transport des constituants
de type degagement volumique de puissance thermique.!!!!A MODIFIER
Un objet Terme_Source_Constituant contient la puissance (Champ donne
utilisateur) et des references a la masse volumique (rho) et la chaleur.
specifique (Cp).
#include <Terme_Source_Constituant.h>
Public Member Functions
void associer_champs (const Champ_base &)
void lire_donnees (Entree &)
Lit le terme de puissance a partir
d'un flot d'entree.
Lit uniquement un champ donne representant la_puissance.
void ouvrir_fichier (const Equation_base &eq, const Nom &out, const Nom &qsj, const Nom &description, SFichier &os, const Nom &type, const int &flag) const
int completer (const Champ_Inc_base &inco)
const Champ_Don & get_source () const
void mettre_a_jour (double temps)
Protected Attributes
int colw_
Ref_Champ_base rho_ref
Champ_Don la_source_constituant
Detailed Description
Classe Terme_Source_Constituant
Cette classe represente un terme source de l'equation de transport des constituants
de type degagement volumique de puissance thermique.!!!!A MODIFIER
Un objet Terme_Source_Constituant contient la puissance (Champ donne
utilisateur) et des references a la masse volumique (rho) et la chaleur.
specifique (Cp).
Definition at line 44 of file Terme_Source_Constituant.h.
Member Function Documentation
void Terme_Source_Constituant::associer_champs (const Champ_base & rho) [inline]
Definition at line 101 of file Terme_Source_Constituant.h.
{
  rho_ref=rho;
}
int Terme_Source_Constituant::completer (const Champ_Inc_base & inco)
Definition at line 49 of file Terme_Source_Constituant.cpp.
References colw_, max(), Field_base::nb_comp(), and Field_base::noms_compo().
Referenced by Terme_Source_Constituant_VDF_Elem::completer().
{
  colw_ = -1;
  for (int i = 0; i < inco.nb_comp(); ++i)
    colw_ = max(colw_, inco.noms_compo()[i].longueur());
  return colw_;
}
const Champ_Don& Terme_Source_Constituant::get_source () const [inline]
Definition at line 54 of file Terme_Source_Constituant.h.
References la_source_constituant.
  {
    return la_source_constituant ;
  };
void Terme_Source_Constituant::lire_donnees (Entree & is)
Lit le terme de puissance a partir
d'un flot d'entree.
Lit uniquement un champ donne representant la_puissance.
Definition at line 43 of file Terme_Source_Constituant.cpp.
References Cerr, finl, and la_source_constituant.
Referenced by Terme_Source_Constituant_VEF_Face::readOn(), Terme_Source_Constituant_VDF_Elem::readOn(), Terme_Source_Constituant_PolyMAC_Elem::readOn(), and Terme_Source_Constituant_CoviMAC_Elem::readOn().
{
  Cerr << "Lecture du Champ Source pour le terme source du/des constituants" << finl;
  is >> la_source_constituant;
}
void Terme_Source_Constituant::mettre_a_jour (double temps) [inline]
Reimplemented in Terme_Source_Constituant_CoviMAC_Elem, Terme_Source_Constituant_PolyMAC_Elem, Terme_Source_Constituant_VDF_Elem, and Terme_Source_Constituant_VEF_Face.
Definition at line 59 of file Terme_Source_Constituant.h.
References la_source_constituant, and Champ_Don::mettre_a_jour().
Referenced by Terme_Source_Constituant_VEF_Face::mettre_a_jour(), Terme_Source_Constituant_VDF_Elem::mettre_a_jour(), Terme_Source_Constituant_PolyMAC_Elem::mettre_a_jour(), and Terme_Source_Constituant_CoviMAC_Elem::mettre_a_jour().
  {
    la_source_constituant.mettre_a_jour(temps);
  };
void Terme_Source_Constituant::ouvrir_fichier (const Equation_base & eq, const Nom & out, const Nom & qsj, const Nom & description, SFichier & os, const Nom & type, const int & flag) const
Definition at line 57 of file Terme_Source_Constituant.cpp.
References Sortie::add_col(), colw_, finl, Schema_Temps_base::gnuplot_header(), Equation_base::inconnue(), Probleme_base::le_nom(), max(), Schema_Temps_base::nb_impr(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie::set_col_width(), Sortie_Fichier_base::setf(), and Schema_Temps_base::wcol().
Referenced by Terme_Source_Constituant_VDF_Elem::ouvrir_fichier().
{
// flag nul on n'ouvre pas le fichier
  if (flag==0)
    return ;
  const Probleme_base& pb = eq.probleme();
  const Schema_Temps_base& sch = pb.schema_temps();
  Nom nomfichier(out);
  if (type!="") nomfichier+=(Nom)"_"+type;
  nomfichier+=".out";
// On cree le fichier a la premiere impression avec l'en tete
  const int wcol = max(colw_, sch.wcol());
  os.set_col_width(wcol);
  if (sch.nb_impr()==1 && !pb.reprise_effectuee())
    {
      const int& gnuplot_header = sch.gnuplot_header();
      os.ouvrir(nomfichier);
      SFichier& fic=os;
      fic << (Nom)"# Printing of the source term " + qsj + " of the equation "+ eq.que_suis_je() +" of the problem "+ eq.probleme().le_nom() << finl;
      fic << "# " << description << finl;
      if (!gnuplot_header) fic << "#";
      os.set_col_width(wcol - !gnuplot_header);
      fic.add_col("Time");
      os.set_col_width(wcol);
      for (int i = 0; i < eq.inconnue()->nb_comp(); ++i)
        fic.add_col(eq.inconnue()->noms_compo()[i].getChar());
      fic << finl;
    }
// Sinon on l'ouvre
  else
    {
      os.ouvrir(nomfichier,ios::app);
    }
  os.precision(sch.precision_impr());
  os.setf(ios::scientific);
}
Member Data Documentation
int Terme_Source_Constituant::colw_ [protected]
Definition at line 62 of file Terme_Source_Constituant.h.
Referenced by completer(), and ouvrir_fichier().
Champ_Don Terme_Source_Constituant::la_source_constituant [protected]
Definition at line 67 of file Terme_Source_Constituant.h.
Referenced by Terme_Source_Constituant_VEF_Face::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_CoviMAC_Elem::associer_pb(), get_source(), lire_donnees(), and mettre_a_jour().
Ref_Champ_base Terme_Source_Constituant::rho_ref [protected]
Definition at line 66 of file Terme_Source_Constituant.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Terme_Source_Constituant.h
src/ThHyd/Incompressible/Sources/Terme_Source_Constituant.cpp