TRUST: Discretiser Class Reference
Discretiser Class Reference
classe Discretiser
Discretise un probleme:
{DANS LE JEU DE DONNEES] Discretiser pb dis
Discretise le probleme "pb" avec la discretisation "dis"
ou "dis" est une Discretisation_base VDF ou VEF pour le moment.
#include <Discretiser.h>
Public Member Functions
Discretiser ()
~Discretiser ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Fonction principale de l'interprete Discretiser:
discretiser un probleme avec une discretisation
On controle dynamiquement le type du probleme et
de la discretisation que l'on a lu, on verifie
que le schema en temps du probleme a ete lu et on
discretise le probleme avec la discretisation.
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Discretiser & self_cast (Objet_U &)
static const Discretiser & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a:
Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Attributes
static int is_deja_appele =0
Detailed Description
classe Discretiser
Discretise un probleme:
{DANS LE JEU DE DONNEES] Discretiser pb dis
Discretise le probleme "pb" avec la discretisation "dis"
ou "dis" est une Discretisation_base VDF ou VEF pour le moment.
Definition at line 37 of file Discretiser.h.
Constructor & Destructor Documentation
Discretiser()
Discretiser::Discretiser ()
Definition at line 21 of file Discretiser.cpp.
~Discretiser()
Discretiser::~Discretiser ()
Definition at line 21 of file Discretiser.cpp.
Member Function Documentation
cree_instance()
Objet_U * Discretiser::cree_instance () static
Definition at line 21 of file Discretiser.cpp.
duplique()
int Discretiser::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Discretiser.cpp.
get_info()
const Type_info * Discretiser::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Discretiser.cpp.
info()
const Type_info * Discretiser::info () static
Definition at line 21 of file Discretiser.cpp.
interpreter()
Entree & Discretiser::interpreter (Entree & is) override virtual
Fonction principale de l'interprete Discretiser:
discretiser un probleme avec une discretisation
On controle dynamiquement le type du probleme et
de la discretisation que l'on a lu, on verifie
que le schema en temps du probleme a ete lu et on
discretise le probleme avec la discretisation.
Reimplemented from Interprete.
Definition at line 90 of file Discretiser.cpp.
{
saisie :
  Nom nom1, nom2;
  is >> nom1 >> nom2;
  Objet_U& ob1=objet(nom1);
  Objet_U& ob2=objet(nom2);
  if (is_deja_appele==0)
    is_deja_appele = 1;
  else
    {
      Cerr<<"Be careful, you call several times the interpreter Discretiser"<<finl;
      Cerr<<"there is probably an error in your data set"<<finl;
// exit();
    }
  if( !( sub_type(Discretisation_base, ob2) ) )
    {
      Cerr << nom2 << "is not a recognized discretization" << finl;
      exit();
    }
  Discretisation_base& typ=ref_cast(Discretisation_base, ob2);
  Cerr << "The chosen discretization is of type " << typ.que_suis_je() << finl;
  if (typ.que_suis_je()=="VEF")
    {
      Cerr << "Since 1.6 version, the keyword VEF is obsolete." << finl;
      Cerr << "Use keyword VEFPreP1B and P0 support to match the old VEF keyword." << finl;
      exit();
    }
// Test on bidim_axi
  if ( dimension == 2 && !(typ.que_suis_je()=="VDF") && bidim_axi == 1 )
    {
      Cerr << "The feature 'bidim_axi' is only available for 2D calculation with VDF discretisation." << finl;
      exit();
    }
//
  if( sub_type(Probleme_base, ob1) )
    {
      Probleme_base& pb=ref_cast(Probleme_base,ob1);
      if(!pb.schema_temps().lu())
        {
          Cerr << "it must have read the time scheme before to discretize" << finl;
          exit();
        }
      Cerr << "The chosen time scheme is of type " << pb.schema_temps().que_suis_je() << finl;
      Cerr << "We treat the problem " << pb.le_nom() << " of type " << pb.que_suis_je() << finl;
      Cerr << "Discretization of " << pb.le_nom() << " in progress..." << finl;
      pb.discretiser(typ);
    }
  else if( sub_type(Probleme_Couple, ob1) )
    {
      Probleme_Couple& pbc=ref_cast(Probleme_Couple,ob1);
      if(!pbc.schema_temps().lu())
        {
          Cerr << "it must have read the time scheme before to discretize" << finl;
          exit();
        }
      Cerr << "The chosen time scheme is of type " << pbc.schema_temps().que_suis_je() << finl;
      Cerr << "We treat the problem " << pbc.le_nom() << " of type " << pbc.que_suis_je() << finl;
      Cerr << "It corresponds to the coupling of the following problems: " << finl;
      for(int i=0; i< pbc.nb_problemes(); i++)
        Cerr << " " <<  pbc.probleme(i).le_nom() << " of type " << pbc.probleme(i).que_suis_je() << finl;
      Cerr << "Discretization of " << pbc.le_nom() << " in progress..." << finl;
      pbc.discretiser(typ);
    }
  else
    {
      Cerr << "It is not known discretize a : " << ob1.que_suis_je()        << finl;
      Cerr << "return at the seizure of the arguments" << finl;
      goto saisie;
    }
  return is;
}
References Objet_U::bidim_axi, Cerr, Objet_U::dimension, Probleme_base::discretiser(), Probleme_Couple::discretiser(), Process::exit(), finl, is_deja_appele, Probleme_base::le_nom(), Probleme_U::le_nom(), Schema_Temps_base::lu(), Couplage_U::nb_problemes(), Interprete::objet(), Couplage_U::probleme(), Objet_U::que_suis_je(), ref_cast, Probleme_base::schema_temps(), Probleme_Couple::schema_temps(), and sub_type.
printOn()
Sortie & Discretiser::printOn (Sortie & os) const override protected virtual
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 42 of file Discretiser.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Discretiser::readOn (Entree & is) override protected virtual
Simple appel a:
Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 63 of file Discretiser.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Discretiser & Discretiser::self_cast (const Objet_U & r) static
Definition at line 21 of file Discretiser.cpp.
self_cast() [2/2]
Discretiser & Discretiser::self_cast (Objet_U & r) static
Definition at line 21 of file Discretiser.cpp.
taille_memoire()
unsigned Discretiser::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Discretiser.cpp.
Member Data Documentation
info_obj
const Type_info Discretiser::info_obj static
Definition at line 39 of file Discretiser.h.
is_deja_appele
int Discretiser::is_deja_appele =0 static protected
Definition at line 43 of file Discretiser.h.
Referenced by interpreter().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Discretiser.h
src/Kernel/Framework/Discretiser.cpp