TRUST: Deriv_Raccord_base Class Reference
Deriv_Raccord_base Class Reference
#include <Raccord.h>
Public Member Functions
~Deriv_Raccord_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Raccord_base ()
Deriv_Raccord_base (const Deriv_Raccord_base &)
const Raccord_base & valeur () const
Raccord_base & valeur ()
const Raccord_base * operator-> () const
Raccord_base * operator-> ()
const Deriv_Raccord_base & operator= (const Raccord_base &)
const Deriv_Raccord_base & operator= (const Deriv_Raccord_base &)
operator const Raccord_base & () const
operator Raccord_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Raccord_base & self_cast (Objet_U &)
static const Deriv_Raccord_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Raccord_base * pointeur_
Detailed Description
Definition at line 28 of file Raccord.h.
Constructor & Destructor Documentation
Deriv_Raccord_base::~Deriv_Raccord_base ()
Definition at line 25 of file Raccord.cpp.
Deriv_Raccord_base::Deriv_Raccord_base ()
Definition at line 25 of file Raccord.cpp.
Deriv_Raccord_base::Deriv_Raccord_base (const Deriv_Raccord_base & t)
Definition at line 25 of file Raccord.cpp.
Member Function Documentation
Objet_U * Deriv_Raccord_base::cree_instance () [static]
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
int Deriv_Raccord_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
const Type_info * Deriv_Raccord_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
const Type_info & Deriv_Raccord_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Raccord.cpp.
const Type_info * Deriv_Raccord_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
Deriv_Raccord_base::operator const Raccord_base & () const
Definition at line 25 of file Raccord.cpp.
Deriv_Raccord_base::operator Raccord_base & ()
Definition at line 25 of file Raccord.cpp.
const Raccord_base * Deriv_Raccord_base::operator-> () const [inline]
Definition at line 28 of file Raccord.h.
: public DERIV(Raccord_base)
Raccord_base * Deriv_Raccord_base::operator-> () [inline]
Definition at line 28 of file Raccord.h.
: public DERIV(Raccord_base)
const Deriv_Raccord_base & Deriv_Raccord_base::operator= (const Deriv_Raccord_base & t)
Definition at line 25 of file Raccord.cpp.
const Deriv_Raccord_base & Deriv_Raccord_base::operator= (const Raccord_base & t)
Definition at line 25 of file Raccord.cpp.
Sortie & Deriv_Raccord_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
Entree & Deriv_Raccord_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
const Deriv_Raccord_base & Deriv_Raccord_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
Deriv_Raccord_base & Deriv_Raccord_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
void Deriv_Raccord_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Raccord.cpp.
unsigned Deriv_Raccord_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Raccord.
Definition at line 25 of file Raccord.cpp.
const Raccord_base & Deriv_Raccord_base::valeur () const [inline]
Definition at line 28 of file Raccord.h.
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), DomaineCutter::construire_faces_raccords_ssdom(), DecoupeBord::Decouper(), Zone_VF::discretiser(), Echange_contact_VDF::initialiser(), Modif_bord_to_raccord::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Decouper_multi::lire_motcle_non_standard(), and Pave::readOn().
: public DERIV(Raccord_base)
Raccord_base & Deriv_Raccord_base::valeur () [inline]
Definition at line 28 of file Raccord.h.
: public DERIV(Raccord_base)
Member Data Documentation
const Type_info Deriv_Raccord_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Raccord.
Definition at line 28 of file Raccord.h.
Raccord_base* Deriv_Raccord_base::pointeur_ [private]
Definition at line 28 of file Raccord.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raccord.h
src/Kernel/Geometrie/Raccord.cpp