TRUST: Terme_Source_inc_th_VDF_Face Class Reference
Terme_Source_inc_th_VDF_Face Class Reference
#include <Terme_Source_inc_th_VDF_Face.h>
Public Member Functions
Terme_Source_inc_th_VDF_Face ()
~Terme_Source_inc_th_VDF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
const Champ_Don & beta () const
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_inc_th
void associer_eqn (const Navier_Stokes_std &)
void associer_eqn (const Convection_Diffusion_Temperature &)
const Navier_Stokes_std & eq_hydraulique () const
const Convection_Diffusion_Temperature & eq_thermique () const
void mettre_a_jour (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_inc_th_VDF_Face & self_cast (Objet_U &)
static const Terme_Source_inc_th_VDF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Terme_Source_inc_th
Entree & lire_donnees (Entree &)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_inc_th
Ref_Navier_Stokes_std eq_hydraulique_
Ref_Convection_Diffusion_Temperature eq_thermique_
Ref_Champ_Don beta_t_
int impr
Detailed Description
Definition at line 39 of file Terme_Source_inc_th_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Source_inc_th_VDF_Face()
Terme_Source_inc_th_VDF_Face::Terme_Source_inc_th_VDF_Face ()
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
~Terme_Source_inc_th_VDF_Face()
Terme_Source_inc_th_VDF_Face::~Terme_Source_inc_th_VDF_Face ()
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Terme_Source_inc_th_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
< dimension == 3
Reimplemented from Source_base.
Definition at line 90 of file Terme_Source_inc_th_VDF_Face.cpp.
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const Zone_Cl_VDF& zone_Cl_VDF = la_zone_Cl_VDF.valeur();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const IntVect& orientation = zone_VDF.orientation();
// const DoubleTab& xv = zone_VDF.xv();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const Zone& zone = la_zone_VDF->zone();
  int nb_elem = zone.nb_elem();
  const Champ_Uniforme& ch_beta = ref_cast(Champ_Uniforme,beta().valeur());
  const DoubleTab& vitesse = eq_hydraulique().inconnue().valeurs();
  const DoubleVect& temperature = eq_thermique().inconnue().valeurs();
  DoubleVect cell_cent_temp(temperature);
  int ndeb,nfin,ncomp,num_face;
// double debit_e=0.,dt,vol,Surf;
// double vol,Surf;
  double vol;
  DoubleTrav s(3);
  s = 0.;
// int nb_elem_tot = la_zone_VDF->zone().nb_elem_tot();
// double dQij=0;
// double si;
// static int deb=0;
// static double source=0.;
// static double debnm1;
// static double debit_ref=0.;
// Cerr << " debut de inc" << finl;
// double tps = eq_hydraulique().inconnue().temps();
// const DoubleVect& vit = eq_hydraulique().inconnue().valeurs();
// calculer_cell_cent_vel
// -------------------------------------------------------------------
// Exemple XTOF
// Cerr << " debut de parallel " << finl;
  DoubleTab cell_cent_vel(0, dimension);
  la_zone_VDF.valeur().zone().creer_tableau_elements(cell_cent_vel);
// DoubleTrav toto(cell_cent_vel);
  DoubleTab temp1(cell_cent_vel);
  DoubleTab temp2(cell_cent_vel);
  DoubleTab filt_vel(cell_cent_vel);
  DoubleTab inc_dv(cell_cent_vel);
// DoubleTrav cell_cent_vel(nb_elem_tot,dimension);
// -------------------------------------------------------------------
// Cerr << " vitesse " << vitesse << finl;
// Cerr << " temperature " << cell_cent_temp << finl;
  DoubleVect temp1_t(cell_cent_temp);
  DoubleVect temp2_t(cell_cent_temp);
  DoubleVect filt_temp(cell_cent_temp);
  DoubleVect inc_dt(cell_cent_temp);
  DoubleVect dQij_j(cell_cent_temp);
// const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
// const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
// int nb_elem_tot = zone_VDF.zone().nb_elem_tot();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  int element_number;
  int num0=-1,num1,num2=-1,num3,num4=-1,num5=-1;
// Cerr << " vitesse " << vitesse << finl;
// This is to calculate the cell centered velocity values
  DoubleTab uij_filt(cell_cent_vel);
// DoubleTab uij_filt(nb_elem,dimension,dimension);
  for (element_number=0 ; element_number<nb_elem ; element_number ++)
    {
// Cerr << me() << " " << element_number << finl;
      cell_cent_temp(element_number)*=ch_beta(0,0);
      temp1_t(element_number)=0.;
      temp2_t(element_number)=0.;
      filt_temp(element_number)=0.;
      inc_dt(element_number)=0.;
      dQij_j(element_number)=0.;
      num0 = elem_faces(element_number,0);
      num1 = elem_faces(element_number,1);
      num2 = elem_faces(element_number,2);
      num3 = elem_faces(element_number,3);
// uij_filt(element_number,0,0)=uij_filt_1(element_number,0);
// uij_filt(element_number,1,0)=uij_filt_1(element_number,1);
// uij_filt(element_number,0,1)=uij_filt_2(element_number,0);
// uij_filt(element_number,1,1)=uij_filt_2(element_number,1);
      if (dimension == 3)
        {
// uij_filt(element_number,0,2)=uij_filt_3(element_number,0);
// uij_filt(element_number,1,2)=uij_filt_3(element_number,1);
// uij_filt(element_number,2,2)=uij_filt_3(element_number,2);
// uij_filt(element_number,2,0)=uij_filt_1(element_number,2);
// uij_filt(element_number,2,1)=uij_filt_2(element_number,2);
          num4 = elem_faces(element_number,4);
          num5 = elem_faces(element_number,5);
          inc_dv(element_number,0)=0.;
          inc_dv(element_number,1)=0.;
          inc_dv(element_number,2)=0.;
        }
      if (dimension == 2)
        {
          cell_cent_vel(element_number,0)=0.5*(vitesse[num0]+vitesse[num2]);
          cell_cent_vel(element_number,1)=0.5*(vitesse[num1]+vitesse[num3]);
          inc_dv(element_number,0)=0.;
          inc_dv(element_number,1)=0.;
        }
      else
        {
          cell_cent_vel(element_number,0)=0.5*(vitesse[num0]+vitesse[num3]);
          cell_cent_vel(element_number,1)=0.5*(vitesse[num1]+vitesse[num4]);
          cell_cent_vel(element_number,2)=0.5*(vitesse[num2]+vitesse[num5]);
        }
    }
  cell_cent_vel.echange_espace_virtuel();
// Cerr << " calculer_filter_field" << finl;
//
// calculer_filter_field(cell_cent_vel,filt_vel);
//
// calculate filter vector, unfilter tensor and
// increment fields in the same loop to speed up calculation
//
// -------------------------------------------------------------------
// DoubleTab toto(cell_cent_vel);
  DoubleTab Qij(cell_cent_vel);
  DoubleTab Lij(cell_cent_vel);
  DoubleTab ttemp1(cell_cent_vel);
  DoubleTab ttemp2(cell_cent_vel);
// DoubleTab Qij(uij_filt);
// DoubleTab Lij(uij_filt);
// DoubleTab ttemp1(uij_filt);
// DoubleTab ttemp2(uij_filt);
// DoubleTrav filt_vel(nb_elem_tot,dimension);
// DoubleTrav inc_dv(nb_elem_tot,dimension);
// inc_dv.resize(nb_elem_tot,dimension);
// DoubleTrav uij_filt(nb_elem_tot,dimension,dimension);
// -------------------------------------------------------------------
// const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
// const IntTab& face_voisins = zone_VDF.face_voisins();
// int nb_elem_tot = zone_VDF.zone().nb_elem_tot();
// const IntTab& elem_faces = zone_VDF.elem_faces();
// int element_number;
// int num0,num1,num2,num3,num4,num5;
  int f0,f1,f2,f3,f4,f5;
  int i;
  int num0_1,num1_1,num2_1,num3_1,num4_1,num5_1;
  int f0_1,f1_1,f2_1,f3_1,f4_1,f5_1;
// DoubleTrav temp1(nb_elem_tot,dimension);
// DoubleTrav temp2(nb_elem_tot,dimension);
// This is to calculate the filtered velocity field
// Cerr << me() << " boucle 1 " << finl;
  if (dimension ==2)
    {
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
// for (i=0 ; i<dimension ; i++)
// for (j=0 ; j<dimension ; j++)
// uij_filt(element_number,i,j)=cell_cent_vel(element_number,i)*
// cell_cent_vel(element_number,j);
          for (i=0 ; i<dimension ; i++)
            {
              uij_filt(element_number,i)=cell_cent_vel(element_number,i)*
                                         cell_cent_temp(element_number);
            }
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,1);
          if ( (num0 == -1) || (num2 == -1) )
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  temp1(element_number,i)=cell_cent_vel(element_number,i);
                  inc_dv(element_number,i)=0.;
                }
              temp1_t(element_number)=cell_cent_temp(element_number);
              inc_dt(element_number)=0.;
            }
          else
            {
              {
                for (i=0 ; i<dimension ; i ++)
                  {
                    temp1(element_number,i)=0.25*(cell_cent_vel(num0,i)+
                                                  2.0*cell_cent_vel(element_number,i)+
                                                  cell_cent_vel(num2,i));
                  }
                temp1_t(element_number)=0.25*(cell_cent_temp(num0)+
                                              2.0*cell_cent_temp(element_number)+
                                              cell_cent_temp(num2));
              }
              f0_1 = elem_faces(num0,0);
              num0_1 = face_voisins(f0_1,0);
              f2_1 = elem_faces(num2,2);
              num2_1 = face_voisins(f2_1,1);
              if ( (num0_1 == -1) || (num2_1 == -1) )
                {
                  for (i=0 ; i<dimension ; i ++)
                    {
                      inc_dv(element_number,i)+=(cell_cent_vel(num0,i))-(cell_cent_vel(num2,i));
                    }
                  inc_dt(element_number)+=(cell_cent_temp(num0))-(cell_cent_temp(num2));
                }
              else
                {
                  for (i=0 ; i<dimension ; i ++)
                    {
                      inc_dv(element_number,i)+=(cell_cent_vel(num0_1,i))-(cell_cent_vel(num2_1,i));
                    }
                  inc_dt(element_number)+=(cell_cent_temp(num0_1))-(cell_cent_temp(num2_1));
                }
            }
        }
      temp1.echange_espace_virtuel();
      temp1_t.echange_espace_virtuel();
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if ( (num1 == -1) || (num3 == -1) )
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  filt_vel(element_number,i)=temp1(element_number,i);
                  inc_dv(element_number,i)=0.;
                }
              filt_temp(element_number)=temp1_t(element_number);
              inc_dt(element_number)=0.;
            }
          else
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  filt_vel(element_number,i)=0.25*(temp1(num1,i)+
                                                   2.0*temp1(element_number,i)+
                                                   temp1(num3,i));
                }
              filt_temp(element_number)=0.25*(temp1_t(num1)+
                                              2.0*temp1_t(element_number)+
                                              temp1_t(num3));
              f1_1 = elem_faces(num0,1);
              num1_1 = face_voisins(f1_1,0);
              f3_1 = elem_faces(num3,3);
              num3_1 = face_voisins(f3_1,1);
              if ( (num1_1 == -1) || (num3_1 == -1) )
                {
                  for (i=0 ; i<dimension ; i ++)
                    inc_dv(element_number,i)+=(cell_cent_vel(num1,i))-(cell_cent_vel(num3,i));
                  inc_dt(element_number)+=(cell_cent_temp(num1))-(cell_cent_temp(num3));
                }
              else
                {
                  for (i=0 ; i<dimension ; i ++)
                    {
                      inc_dv(element_number,i)+=(cell_cent_vel(num1_1,i))-(cell_cent_vel(num3_1,i));
                    }
                  inc_dt(element_number)+=(cell_cent_temp(num1_1))-(cell_cent_temp(num3_1));
                }
            }
        }
    }
  else //!< dimension == 3
    {
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
// for (i=0 ; i<dimension ; i++)
// for (j=0 ; j<dimension ; j++)
// uij_filt(element_number,i,j)=cell_cent_vel(element_number,i)*
// cell_cent_vel(element_number,j);
// Cerr << " elem " << element_number << finl;
          for (i=0 ; i<dimension ; i++)
            {
              uij_filt(element_number,i)=cell_cent_vel(element_number,i)*
                                         cell_cent_temp(element_number);
            }
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if ( (num0 == -1) || (num3 == -1) )
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  temp1(element_number,i)=cell_cent_vel(element_number,i);
                  inc_dv(element_number,i)+=0.;
                }
              temp1_t(element_number)=cell_cent_temp(element_number);
              inc_dt(element_number)+=0.;
            }
          else
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  temp1(element_number,i)=0.25*(cell_cent_vel(num0,i)+
                                                2.0*cell_cent_vel(element_number,i)+
                                                cell_cent_vel(num3,i));
                }
              temp1_t(element_number)=0.25*(cell_cent_temp(num0)+
                                            2.0*cell_cent_temp(element_number)+
                                            cell_cent_temp(num3));
// Cerr << " not num0 et num3 " << num0 << " " << num3 << finl;
              f0_1 = elem_faces(num0,0);
              num0_1 = face_voisins(f0_1,0);
              f3_1 = elem_faces(num3,3);
              num3_1 = face_voisins(f3_1,1);
              if ( (num0_1 == -1) || (num3_1 == -1) )
                {
                  for (i=0 ; i<dimension ; i ++)
                    inc_dv(element_number,i)+=(cell_cent_vel(num0,i))-(cell_cent_vel(num3,i));
                  inc_dt(element_number)+=(cell_cent_temp(num0))-(cell_cent_temp(num3));
                }
              else
                {
// Cerr << " not num0_1 et num3_1 " << num0_1 << " " << num3_1 << finl;
                  for (i=0 ; i<dimension ; i ++)
                    {
                      inc_dv(element_number,i)+=(cell_cent_vel(num0_1,i))-(cell_cent_vel(num3_1,i));
                    }
                  inc_dt(element_number)+=(cell_cent_temp(num0_1))-(cell_cent_temp(num3_1));
                }
            }
        }
      temp1.echange_espace_virtuel();
      temp1_t.echange_espace_virtuel();
      Cerr << " part 1 " << finl;
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          f4 = elem_faces(element_number,4);
          num4 = face_voisins(f4,1);
          if ( (num1 == -1) || (num4 == -1) )
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  temp2(element_number,i)=temp1(element_number,i);
                  inc_dv(element_number,i)+=0.;
                }
              temp2_t(element_number)=temp1_t(element_number);
              inc_dt(element_number)+=0.;
            }
          else
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  temp2(element_number,i)=0.25*(temp1(num1,i)+
                                                2.0*temp1(element_number,i)+
                                                temp1(num4,i));
                }
              temp2_t(element_number)=0.25*(temp1_t(num1)+
                                            2.0*temp1_t(element_number)+
                                            temp1_t(num4));
// Cerr << " not num1 et num4 " << num1 << " " << num4 << finl;
              f1_1 = elem_faces(num1,1);
              num1_1 = face_voisins(f1_1,0);
              f4_1 = elem_faces(num4,4);
              num4_1 = face_voisins(f4_1,1);
              if ( (num1_1 == -1) || (num4_1 == -1) )
                {
                  for (i=0 ; i<dimension ; i ++)
                    inc_dv(element_number,i)+=(cell_cent_vel(num1,i))-(cell_cent_vel(num4,i));
                  inc_dt(element_number)+=(cell_cent_temp(num1))-(cell_cent_temp(num4));
                }
              else
                {
// Cerr << " not num1_1 et num4_1 " << num1_1 << " " << num4_1 << finl;
                  for (i=0 ; i<dimension ; i ++)
                    {
                      inc_dv(element_number,i)+=(cell_cent_vel(num1_1,i))-(cell_cent_vel(num4_1,i));
                    }
                  inc_dt(element_number)+=(cell_cent_temp(num1_1))-(cell_cent_temp(num4_1));
                }
            }
        }
      temp2.echange_espace_virtuel();
      temp2_t.echange_espace_virtuel();
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,0);
          f5 = elem_faces(element_number,5);
          num5 = face_voisins(f5,1);
          if ( (num2 == -1) || (num5 == -1) )
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  filt_vel(element_number,i)=temp2(element_number,i);
                  inc_dv(element_number,i)+=0.;
                }
              filt_temp(element_number)=temp2_t(element_number);
              inc_dt(element_number)+=0.;
            }
          else
            {
              for (i=0 ; i<dimension ; i ++)
                {
                  filt_vel(element_number,i)=0.25*(temp2(num2,i)+
                                                   2.0*temp2(element_number,i)+
                                                   temp2(num5,i));
                }
              filt_temp(element_number)=0.25*(temp2_t(num2)+
                                              2.0*temp2_t(element_number)+
                                              temp2_t(num5));
// Cerr << " not num2 et num5 " << num2 << " " << num5 << finl;
              f2_1 = elem_faces(num2,2);
              num2_1 = face_voisins(f2_1,0);
              f5_1 = elem_faces(num5,5);
              num5_1 = face_voisins(f5_1,1);
              if ( (num2_1 == -1) || (num5_1 == -1) )
                {
                  for (i=0 ; i<dimension ; i ++)
                    inc_dv(element_number,i)+=(cell_cent_vel(num2,i))-(cell_cent_vel(num5,i));
                  inc_dt(element_number)+=(cell_cent_temp(num2))-(cell_cent_temp(num5));
                }
              else
                {
// Cerr << " not num2_1 et num5_1 " << num2_1 << " " << num5_1 << finl;
                  for (i=0 ; i<dimension ; i ++)
                    {
                      inc_dv(element_number,i)+=(cell_cent_vel(num2_1,i))-(cell_cent_vel(num5_1,i));
                    }
                  inc_dt(element_number)+=(cell_cent_temp(num2_1))-(cell_cent_temp(num5_1));
                }
            }
        }
    }
  filt_vel.echange_espace_virtuel();
  inc_dv.echange_espace_virtuel();
  filt_temp.echange_espace_virtuel();
  inc_dt.echange_espace_virtuel();
  uij_filt.echange_espace_virtuel();
  Cerr << " first loop " << finl;
//
// calculer_Qij(inc_dv,Qij);
// -------------------------------------------------------------------
// DoubleTrav Qij(nb_elem_tot,dimension,dimension);
// -------------------------------------------------------------------
// const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
// int nb_elem_tot = zone_VDF.zone().nb_elem_tot();
// int element_number;
// This is to calculate the Qij tensor
// for (element_number=0 ; element_number<nb_elem_tot ; element_number ++)
// {
// for (int i=0 ; i<dimension ; i++)
// for (int j=0 ; j<dimension ; j++)
// Qij(element_number,i,j)=inc_dv(element_number,i)*inc_dv(element_number,j);
// }
// Cerr << " calculer_Lij " << finl;
//
// calculer_Lij(cell_cent_vel,filt_vel,Lij);
//
// calculate Qij and uij_filt in the same loop to speed up calculation
//
// -------------------------------------------------------------------
// DoubleTrav Lij(nb_elem_tot,dimension,dimension);
// -------------------------------------------------------------------
// const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
// int nb_elem_tot = zone_VDF.zone().nb_elem_tot();
// int element_number;
// DoubleTrav uij_filt(nb_elem_tot,dimension,dimension);
// DoubleTrav ttemp1(nb_elem_tot,dimension,dimension);
// DoubleTrav ttemp2(nb_elem_tot,dimension,dimension);
// This is to calculate the Lij term for the C coefficient
// for (element_number=0 ; element_number<nb_elem_tot ; element_number ++)
// {
// for (int i=0 ; i<dimension ; i++)
// for (int j=0 ; j<dimension ; j++)
// {
// uij_filt(element_number,i,j)=cell_cent_vel(element_number,i)*
// cell_cent_vel(element_number,j);
// }
// }
// calculer_filter_tensor(uij_filt);
// Cerr << " calculer_uij_filt " << finl;
// This is to calculate the filtered tensor field
// int j;
// Cerr << me() << " boucle 2 " << finl;
  if (dimension ==2)
    {
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,1);
          if ( (num0 == -1) || (num2 == -1) )
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// ttemp1(element_number,i,j)=uij_filt(element_number,i,j);
            for (i=0 ; i<dimension ; i++)
              {
                ttemp1(element_number,i)=uij_filt(element_number,i);
              }
          else
            {
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// {
// ttemp1(element_number,i,j)=0.25*(uij_filt(num0,i,j)+
// 2.0*uij_filt(element_number,i,j)+
// uij_filt(num2,i,j));
// }
              for (i=0 ; i<dimension ; i++)
                {
                  ttemp1(element_number,i)=0.25*(uij_filt(num0,i)+
                                                 2.0*uij_filt(element_number,i)+
                                                 uij_filt(num2,i));
                }
            }
        }
      ttemp1.echange_espace_virtuel();
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if ( (num1 == -1) || (num3 == -1) )
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// uij_filt(element_number,i,j)=ttemp1(element_number,i,j);
            for (i=0 ; i<dimension ; i++)
              {
                uij_filt(element_number,i)=ttemp1(element_number,i);
              }
          else
            {
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// {
// uij_filt(element_number,i,j)=0.25*(ttemp1(num1,i,j)+
// 2.0*ttemp1(element_number,i,j)+
// ttemp1(num3,i,j));
// }
              for (i=0 ; i<dimension ; i++)
                {
                  uij_filt(element_number,i)=0.25*(ttemp1(num0,i)+
                                                   2.0*ttemp1(element_number,i)+
                                                   ttemp1(num2,i));
                }
            }
        }
    }
  else
    {
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if ( (num0 == -1) || (num3 == -1) )
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// ttemp1(element_number,i,j)=uij_filt(element_number,i,j);
            for (i=0 ; i<dimension ; i++)
              {
                ttemp1(element_number,i)=uij_filt(element_number,i);
              }
          else
            {
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// {
// ttemp1(element_number,i,j)=0.25*(uij_filt(num0,i,j)+
// 2.0*uij_filt(element_number,i,j)+
// uij_filt(num3,i,j));
// }
              for (i=0 ; i<dimension ; i++)
                {
                  ttemp1(element_number,i)=0.25*(uij_filt(num0,i)+
                                                 2.0*uij_filt(element_number,i)+
                                                 uij_filt(num2,i));
                }
            }
        }
      ttemp1.echange_espace_virtuel();
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          f4 = elem_faces(element_number,4);
          num4 = face_voisins(f4,1);
          if ( (num1 == -1) || (num4 == -1) )
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// ttemp2(element_number,i,j)=ttemp1(element_number,i,j);
            for (i=0 ; i<dimension ; i++)
              {
                ttemp2(element_number,i)=ttemp1(element_number,i);
              }
          else
            {
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// {
// ttemp2(element_number,i,j)=0.25*(ttemp1(num1,i,j)+
// 2.0*ttemp1(element_number,i,j)+
// ttemp1(num4,i,j));
// }
            }
        }
      ttemp2.echange_espace_virtuel();
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,0);
          f5 = elem_faces(element_number,5);
          num5 = face_voisins(f5,1);
          if ( (num2 == -1) || (num5 == -1) )
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// uij_filt(element_number,i,j)=ttemp2(element_number,i,j);
            for (i=0 ; i<dimension ; i++)
              {
                uij_filt(element_number,i)=ttemp2(element_number,i);
              }
          else
            {
// for (i=0 ; i<dimension ; i ++)
// for (j=0 ; j<dimension ; j ++)
// {
// uij_filt(element_number,i,j)=0.25*(ttemp2(num2,i,j)+
// 2.0*ttemp2(element_number,i,j)+
// ttemp2(num5,i,j));
// }
              for (i=0 ; i<dimension ; i++)
                {
                  uij_filt(element_number,i)=0.25*(ttemp2(num0,i)+
                                                   2.0*ttemp2(element_number,i)+
                                                   ttemp2(num2,i));
                }
            }
        }
    }
// finish calculating Lij
  uij_filt.echange_espace_virtuel();
// Cerr << me() << " boucle 3 " << finl;
  for (element_number=0 ; element_number<nb_elem ; element_number ++)
    {
// for (int i=0 ; i<dimension ; i++)
// for (int j=0 ; j<dimension ; j++)
// {
// Qij(element_number,i,j)=inc_dv(element_number,i)*inc_dv(element_number,j);
// Lij(element_number,i,j)=uij_filt(element_number,i,j)-
// filt_vel(element_number,i)*filt_vel(element_number,j);
// }
      for (int ii=0 ; ii<dimension ; ii++)
        {
          Qij(element_number,ii)=inc_dv(element_number,ii)*inc_dt(element_number);
          Lij(element_number,ii)=uij_filt(element_number,ii)-
                                 filt_vel(element_number,ii)*filt_temp(element_number);
        }
    }
  Lij.echange_espace_virtuel();
  Qij.echange_espace_virtuel();
//
// calculer_f(Lij,Qij);
// -------------------------------------------------------------------
  DoubleVect f(nb_elem);
// -------------------------------------------------------------------
  DoubleVect temp_1(nb_elem);
  DoubleVect temp_2(nb_elem);
// Evaluate the dynamic model coefficient f
  int elem;
  if (dimension == 2)
    for (elem=0; elem<nb_elem; elem++)
      {
// temp_1(elem)=0.;
// temp_2(elem)=0.;
// for (int k=0 ; k<dimension ; k++)
// for (int l=0 ; l<dimension ; l++)
// {
// temp_1(elem)+=Lij(elem,k,k);
// temp_2(elem)+=4.*Qij(elem,l,l);
// }
        temp_1(elem)=Lij(elem,0)+Lij(elem,1);
        temp_2(elem)=4.*Qij(elem,0)+4.*Qij(elem,1);
        if(std::fabs(temp_2(elem)) < 1.e-12)
          f(elem)=0.;
        else
          f(elem)=temp_1(elem)/temp_2(elem);
      }
  else
    for (elem=0; elem<nb_elem; elem++)
      {
// temp_1(elem)=0.;
// temp_2(elem)=0.;
        temp_1(elem)=Lij(elem,0)+Lij(elem,1)+Lij(elem,2);
        temp_2(elem)=4.*Qij(elem,0)+4.*Qij(elem,1)+4.*Qij(elem,2);
        if(std::fabs(temp_2(elem)) < 1.e-12)
          f(elem)=0.;
        else
          f(elem)=temp_1(elem)/temp_2(elem);
      }
  f.echange_espace_virtuel();
// Cerr << " calculer_dQij_j" << f << " " << Qij << finl;
//
// calculer_dQij_j(f,Qij,dQij_j);
// -------------------------------------------------------------------
// DoubleTrav dQij_j(nb_elem_tot,dimension);
// dQij_j.resize(nb_elem_tot,dimension);
// -------------------------------------------------------------------
// const IntTab& Qdm = zone_VDF.Qdm();
// const IntVect& orientation = zone_VDF.orientation();
//
// Calculate the source term dQij_j = d/dxj (f Qij)
//
// Cerr << me() << " boucle 4 " << nb_elem << finl;
  if (dimension ==2)
    {
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          if (num0 == -1)
            num0 = element_number;
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          if (num1 == -1)
            num1 = element_number;
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,1);
          if (num2 == -1)
            num2 = element_number;
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if (num3 == -1)
            num3 = element_number;
          dQij_j(element_number)=0.5*((f(num2)*Qij(num2,0)-f(num0)*Qij(num0,0))/
                                      zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,0)+=0.5*((f(num3)*Qij(num3,0)-f(num1)*Qij(num1,0))/
// zone_VDF.dim_elem(element_number,1));
          dQij_j(element_number)+=0.5*((f(num2)*Qij(num2,1)-f(num0)*Qij(num0,1))/
                                       zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,1)+=0.5*((f(num3)*Qij(num3,1)-f(num1)*Qij(num1,1))/
// zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,0)=0.5*((f(num2)*Qij_1(num2,0)-f(num0)*Qij_1(num0,0))/
// zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,0)+=0.5*((f(num3)*Qij_2(num3,0)-f(num1)*Qij_2(num1,0))/
// zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,1)=0.5*((f(num2)*Qij_1(num2,1)-f(num0)*Qij_1(num0,1))/
// zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,1)+=0.5*((f(num3)*Qij_2(num3,1)-f(num1)*Qij_2(num1,1))/
// zone_VDF.dim_elem(element_number,1));
        }
    }
  else
    {
      for (element_number=0 ; element_number<nb_elem ; element_number ++)
        {
          f0 = elem_faces(element_number,0);
          num0 = face_voisins(f0,0);
          if (num0 == -1 || num0 >= nb_elem)
            {
// Cerr << me() << " bord num0 " << finl;
              num0 = element_number;
            }
          f1 = elem_faces(element_number,1);
          num1 = face_voisins(f1,0);
          if (num1 == -1 || num0 >= nb_elem)
            {
// Cerr << me() << " bord num1 " << finl;
              num1 = element_number;
            }
          f2 = elem_faces(element_number,2);
          num2 = face_voisins(f2,0);
          if (num2 == -1 || num2 >= nb_elem)
            {
// Cerr << me() << " bord num2 " << finl;
              num2 = element_number;
            }
          f3 = elem_faces(element_number,3);
          num3 = face_voisins(f3,1);
          if (num3 == -1 || num3 >= nb_elem)
            {
// Cerr << me() << " bord num3 " << finl;
              num3 = element_number;
            }
          f4 = elem_faces(element_number,4);
          num4 = face_voisins(f4,1);
          if (num4 == -1 || num4 >= nb_elem)
            {
// Cerr << me() << " bord num4 " << finl;
              num4 = element_number;
            }
          f5 = elem_faces(element_number,5);
          num5 = face_voisins(f5,1);
          if (num5 == -1 || num5 >= nb_elem)
            {
// Cerr << me() << " bord num5 " << finl;
              num5 = element_number;
            }
          dQij_j(element_number)=0.5*((f(num3)*Qij(num3,0)-f(num0)*Qij(num0,0))/
                                      zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,0)+=0.5*((f(num4)*Qij(num4,0)-f(num1)*Qij(num1,0))/
// zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,0)+=0.5*((f(num5)*Qij(num5,0)-f(num2)*Qij(num2,0))/
// zone_VDF.dim_elem(element_number,2));
// dQij_j(element_number,0)=0.5*((f(num3)*Qij_1(num3,0)-f(num0)*Qij_1(num0,0))/
// zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,0)+=0.5*((f(num4)*Qij_2(num4,0)-f(num1)*Qij_2(num1,0))/
// zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,0)+=0.5*((f(num5)*Qij_3(num5,0)-f(num2)*Qij_3(num2,0))/
// zone_VDF.dim_elem(element_number,2));
// dQij_j(element_number,1)=0.5*((f(num3)*Qij(num3,1)-f(num0)*Qij(num0,1))/
// zone_VDF.dim_elem(element_number,0));
          dQij_j(element_number)+=0.5*((f(num4)*Qij(num4,1)-f(num1)*Qij(num1,1))/
                                       zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,1)+=0.5*((f(num5)*Qij(num5,1)-f(num2)*Qij(num2,1))/
// zone_VDF.dim_elem(element_number,2));
// dQij_j(element_number,1)=0.5*((f(num3)*Qij_1(num3,1)-f(num0)*Qij_1(num0,1))/
// zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,1)+=0.5*((f(num4)*Qij_2(num4,1)-f(num1)*Qij_2(num1,1))/
// zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,1)+=0.5*((f(num5)*Qij_3(num5,1)-f(num2)*Qij_3(num2,1))/
// zone_VDF.dim_elem(element_number,2));
// dQij_j(element_number,2)=0.5*((f(num3)*Qij(num3,2)-f(num0)*Qij(num0,2))/
// zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,2)+=0.5*((f(num4)*Qij(num4,2)-f(num1)*Qij(num1,2))/
// zone_VDF.dim_elem(element_number,1));
          dQij_j(element_number)+=0.5*((f(num5)*Qij(num5,2)-f(num2)*Qij(num2,2))/
                                       zone_VDF.dim_elem(element_number,2));
// dQij_j(element_number,2)=0.5*((f(num3)*Qij_1(num3,2)-f(num0)*Qij_1(num0,2))/
// zone_VDF.dim_elem(element_number,0));
// dQij_j(element_number,2)+=0.5*((f(num4)*Qij_2(num4,2)-f(num1)*Qij_2(num1,2))/
// zone_VDF.dim_elem(element_number,1));
// dQij_j(element_number,2)+=0.5*((f(num5)*Qij_3(num5,2)-f(num2)*Qij_3(num2,2))/
// zone_VDF.dim_elem(element_number,2));
        }
    }
  dQij_j.echange_espace_virtuel();
  double min_f=1.e6, max_f=-1.e6;
  double min_q=1.e6, max_q=-1.e6;
  double min_dq=1.e6, max_dq=-1.e6;
  double min_dq1=1.e6, max_dq1=-1.e6, sum_t=0.;
  for (element_number=0 ; element_number<nb_elem ; element_number ++)
    {
      if (inc_dv(element_number,0)<min_q)
        min_q=inc_dv(element_number,0);
      if (inc_dv(element_number,0)>max_q)
        max_q=inc_dv(element_number,0);
      if (inc_dt(element_number)<min_f)
        min_f=inc_dt(element_number);
      if (inc_dt(element_number)>max_f)
        max_f=inc_dt(element_number);
      if (inc_dv(element_number,1)<min_dq)
        min_dq=inc_dv(element_number,1);
      if (inc_dv(element_number,1)>max_dq)
        max_dq=inc_dv(element_number,1);
      if (inc_dv(element_number,2)<min_dq1)
        min_dq1=inc_dv(element_number,2);
      if (inc_dv(element_number,2)>max_dq1)
        max_dq1=inc_dv(element_number,2);
      sum_t+=inc_dt(element_number);
    }
  Cerr << me() << " min/max " << min_f << " " << max_f << " "  << min_dq1 << " " << max_dq1 << finl;
  Cerr << " min/max " << (sum_t/nb_elem) << " "  << min_q << " " << max_q << " " << min_dq << " " << max_dq << finl;
  double inc_s=0;
// Cerr << "Force de volume (gradient de pression moteur) = " << source << finl;
// Boucle sur les conditions limites pour traiter les faces de bord
// Cerr << me() << " cond lims " << finl;
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
// Si face de Dirichlet ou de Symetrie on ne fait rien
// Si face de Neumann on calcule la contribution au terme source
      const Cond_lim& la_cl = zone_Cl_VDF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
// const Neumann_sortie_libre& la_cl_neumann = ref_cast(Neumann_sortie_libre,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
              ncomp = orientation(num_face);
              num0 = face_voisins(num_face,0);
              if (num0 == -1)
                num0 = face_voisins(num_face,1);
              inc_s=dQij_j(num0)*vol;
              inc_s=0.;
// resu(num_face)+= s(ncomp)*vol;
              secmem(num_face)+= inc_s;
            }
        }
      else if (sub_type(Symetrie,la_cl.valeur()))
        ;
      else if ( (sub_type(Dirichlet,la_cl.valeur()))
                ||
                (sub_type(Dirichlet_homogene,la_cl.valeur()))
              )
        ;
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
              ncomp = orientation(num_face);
              num0 = face_voisins(num_face,0);
              if (num0 == -1)
                num0 = face_voisins(num_face,1);
              inc_s=dQij_j(num0)*vol;
              inc_s=0.;
// resu(num_face)+= s(ncomp)*vol;
              secmem(num_face)+= inc_s;
            }
        }
    }
// Boucle sur les faces internes
  Cerr << me() << " faces internes thermique" << ch_beta(0,0) << finl;
  double min_inc=1.e6, max_inc=-1.e6;
  int num_e1=-1, n_comp1=-1;
  int num_e2=-1, n_comp2=-1;
  ndeb = zone_VDF.premiere_face_int();
  for (num_face =zone_VDF.premiere_face_int(); num_face<zone_VDF.nb_faces(); num_face++)
    {
      vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
      ncomp = orientation(num_face);
      num0 = face_voisins(num_face,0);
      num1 = face_voisins(num_face,1);
      inc_s=0.5*(dQij_j(num0)+dQij_j(num1))*vol;
// resu(num_face)+= s(ncomp)*vol;
      if (inc_s<min_inc)
        {
          min_inc=inc_s;
          num_e1=num0;
          n_comp1=ncomp;
        }
      if (inc_s>max_inc)
        {
          max_inc=inc_s;
          num_e2=num0;
          n_comp2=ncomp;
        }
    }
// inc_s=0.;
  secmem(num_face)+= inc_s;
  Cerr << min_inc << " " << num_e1 << " " << n_comp1 << finl;
  Cerr << max_inc << " " << num_e2 << " " << n_comp2 << finl;
  secmem.echange_espace_virtuel();
}
References beta(), Cerr, Zone::creer_tableau_elements(), Zone_VDF::dim_elem(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Terme_Source_inc_th::eq_hydraulique(), Terme_Source_inc_th::eq_thermique(), f1, f2, Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Convection_Diffusion_Temperature::inconnue(), Navier_Stokes_std::inconnue(), la_zone_Cl_VDF, la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), Process::me(), Zone::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), valeur(), Champ_Inc::valeurs(), Zone_VF::volumes_entrelaces(), and Zone_dis_base::zone().
associer_pb()
void Terme_Source_inc_th_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 51 of file Terme_Source_inc_th_VDF_Face.cpp.
{
  if (sub_type(Pb_Fluide_base,pb) && (pb.nombre_d_equations()>1))
    {
      const Equation_base& eqn = pb.equation(1);
      if (sub_type(Convection_Diffusion_Temperature,eqn))
        {
          const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,pb.equation(0));
          const Convection_Diffusion_Temperature& eqn_thermo = ref_cast(Convection_Diffusion_Temperature,eqn);
          Terme_Source_inc_th::associer_eqn(eqn_hydr);
          Terme_Source_inc_th::associer_eqn(eqn_thermo);
        }
    }
  else
    {
      Cerr << "Error for the method Terme_Source_inc_th_VDF_Face::associer_pb" << finl;
      Cerr << "The source term "<<que_suis_je()<<" cannot be activated for the problem "<<pb.que_suis_je()<< finl;
      exit();
    }
  const Fluide_base& fluide=eq_thermique().fluide();
  beta_t_=fluide.beta_t();
}
References Terme_Source_inc_th::associer_eqn(), Milieu_base::beta_t(), Terme_Source_inc_th::beta_t_, Cerr, Terme_Source_inc_th::eq_thermique(), Probleme_base::equation(), Process::exit(), finl, Convection_Diffusion_Temperature::fluide(), Probleme_base::nombre_d_equations(), Objet_U::que_suis_je(), ref_cast, and sub_type.
associer_zones()
void Terme_Source_inc_th_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 75 of file Terme_Source_inc_th_VDF_Face.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
beta()
const Champ_Don & Terme_Source_inc_th_VDF_Face::beta () const inline
Definition at line 74 of file Terme_Source_inc_th_VDF_Face.h.
{
  return beta_t_.valeur();
}
References Terme_Source_inc_th::beta_t_, and Ref_Champ_Don::valeur().
Referenced by ajouter_blocs().
calculer()
DoubleTab & Terme_Source_inc_th_VDF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 1091 of file Terme_Source_inc_th_VDF_Face.cpp.
{
  resu = 0;
  ajouter(resu);
  resu.echange_espace_virtuel();
  return resu;
}
References Source_base::ajouter(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
cree_instance()
Objet_U * Terme_Source_inc_th_VDF_Face::cree_instance () static
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
dimensionner_blocs()
void Terme_Source_inc_th_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 54 of file Terme_Source_inc_th_VDF_Face.h.
{}
duplique()
int Terme_Source_inc_th_VDF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
get_info()
const Type_info * Terme_Source_inc_th_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
has_interface_blocs()
int Terme_Source_inc_th_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 57 of file Terme_Source_inc_th_VDF_Face.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_inc_th_VDF_Face::info () static
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
mettre_a_jour()
void Terme_Source_inc_th_VDF_Face::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 48 of file Terme_Source_inc_th_VDF_Face.h.
  {
    Terme_Source_inc_th::mettre_a_jour(temps);
  }
References Terme_Source_inc_th::mettre_a_jour().
printOn()
Sortie & Terme_Source_inc_th_VDF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 37 of file Terme_Source_inc_th_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_inc_th_VDF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_inc_th_VDF_Face.cpp.
{
  return Terme_Source_inc_th::lire_donnees(s);
}
References Terme_Source_inc_th::lire_donnees().
self_cast() [1/2]
const Terme_Source_inc_th_VDF_Face & Terme_Source_inc_th_VDF_Face::self_cast (const Objet_U & r) static
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
self_cast() [2/2]
Terme_Source_inc_th_VDF_Face & Terme_Source_inc_th_VDF_Face::self_cast (Objet_U & r) static
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
taille_memoire()
unsigned Terme_Source_inc_th_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 32 of file Terme_Source_inc_th_VDF_Face.cpp.
Member Data Documentation
info_obj
const Type_info Terme_Source_inc_th_VDF_Face::info_obj static
Definition at line 41 of file Terme_Source_inc_th_VDF_Face.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Terme_Source_inc_th_VDF_Face::la_zone_Cl_VDF protected
Definition at line 65 of file Terme_Source_inc_th_VDF_Face.h.
Referenced by ajouter_blocs(), and associer_zones().
la_zone_VDF
Ref_Zone_VDF Terme_Source_inc_th_VDF_Face::la_zone_VDF protected
Definition at line 64 of file Terme_Source_inc_th_VDF_Face.h.
Referenced by ajouter_blocs(), and associer_zones().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_inc_th_VDF_Face.h
src/VDF/Sources/Terme_Source_inc_th_VDF_Face.cpp