TRUST: Terme_Source_Qdm_Face_CoviMAC Class Reference
Terme_Source_Qdm_Face_CoviMAC Class Reference
class Terme_Source_Qdm_Face_CoviMAC
#include <Terme_Source_Qdm_Face_CoviMAC.h>
Public Member Functions
Terme_Source_Qdm_Face_CoviMAC ()
~Terme_Source_Qdm_Face_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &)
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Qdm_Face_CoviMAC & self_cast (Objet_U &)
static const
Terme_Source_Qdm_Face_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zone_Cl_CoviMAC
Detailed Description
class Terme_Source_Qdm_Face_CoviMAC
See also:
Source_base
Definition at line 42 of file Terme_Source_Qdm_Face_CoviMAC.h.
Constructor & Destructor Documentation
Terme_Source_Qdm_Face_CoviMAC::Terme_Source_Qdm_Face_CoviMAC ()
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
Terme_Source_Qdm_Face_CoviMAC::~Terme_Source_Qdm_Face_CoviMAC ()
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
Member Function Documentation
void Terme_Source_Qdm_Face_CoviMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Source_base.
void Terme_Source_Qdm_Face_CoviMAC::associer_pb (const Probleme_base &) [virtual]
Implements Source_base.
Definition at line 64 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
{
  ;
}
void Terme_Source_Qdm_Face_CoviMAC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 69 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
References la_zone_Cl_CoviMAC, la_zone_CoviMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC, zone_dis.valeur());
  la_zone_Cl_CoviMAC = ref_cast(Zone_Cl_CoviMAC, zone_Cl_dis.valeur());
}
void Terme_Source_Qdm_Face_CoviMAC::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 57 of file Terme_Source_Qdm_Face_CoviMAC.h.
{ }; //ok
Objet_U * Terme_Source_Qdm_Face_CoviMAC::cree_instance () [static]
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
void Terme_Source_Qdm_Face_CoviMAC::dimensionner_blocs (matrices_t matrices) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 54 of file Terme_Source_Qdm_Face_CoviMAC.h.
{}) const { }; //rien
int Terme_Source_Qdm_Face_CoviMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
const Type_info * Terme_Source_Qdm_Face_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
int Terme_Source_Qdm_Face_CoviMAC::has_interface_blocs () const [inline, virtual]
Reimplemented from Source_base.
Definition at line 50 of file Terme_Source_Qdm_Face_CoviMAC.h.
  {
    return 1;
  };
const Type_info * Terme_Source_Qdm_Face_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
void Terme_Source_Qdm_Face_CoviMAC::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 121 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
References Terme_Source_Qdm::la_source, and Champ_Don::mettre_a_jour().
{
  la_source->mettre_a_jour(temps);
}
Sortie & Terme_Source_Qdm_Face_CoviMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 43 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_Qdm_Face_CoviMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 52 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
References Cerr, Objet_U::dimension, MorEqn::equation(), Process::exit(), finl, Equation_base::inconnue(), Terme_Source_Qdm::la_source, Field_base::nb_comp(), Objet_U::que_suis_je(), and Deriv_Champ_Inc_base::valeur().
{
  s >> la_source;
  if (la_source->nb_comp() != equation().inconnue().valeur().nb_comp())
    {
      Cerr << "Erreur a la lecture du terme source de type " << que_suis_je() << finl;
      Cerr << "le champ source doit avoir " << dimension << " composantes" << finl;
      exit();
    }
  return s ;
}
Terme_Source_Qdm_Face_CoviMAC & Terme_Source_Qdm_Face_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
const Terme_Source_Qdm_Face_CoviMAC & Terme_Source_Qdm_Face_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
unsigned Terme_Source_Qdm_Face_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 36 of file Terme_Source_Qdm_Face_CoviMAC.cpp.
Member Data Documentation
const Type_info Terme_Source_Qdm_Face_CoviMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 45 of file Terme_Source_Qdm_Face_CoviMAC.h.
Ref_Zone_Cl_CoviMAC Terme_Source_Qdm_Face_CoviMAC::la_zone_Cl_CoviMAC [protected]
Definition at line 62 of file Terme_Source_Qdm_Face_CoviMAC.h.
Referenced by associer_zones().
Ref_Zone_CoviMAC Terme_Source_Qdm_Face_CoviMAC::la_zone_CoviMAC [protected]
Definition at line 57 of file Terme_Source_Qdm_Face_CoviMAC.h.
Referenced by associer_zones().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Terme_Source_Qdm_Face_CoviMAC.h
src/CoviMAC/Sources/Terme_Source_Qdm_Face_CoviMAC.cpp