TRUST: Ch_input_uniforme Class Reference
Ch_input_uniforme Class Reference
class Ch_input_uniforme
Cette classe represente un champ uniforme accessible par setInputField
#include <Ch_input_uniforme.h>
Public Member Functions
Ch_input_uniforme ()
~Ch_input_uniforme ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Champ_base & affecter_ (const Champ_base &)
Renvoie l'objet upcaste en Champ_base.
virtual void getTemplate (TrioField &afield) const
virtual void setValue (const TrioField &afield)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ch_input_uniforme & self_cast (Objet_U &)
static const Ch_input_uniforme & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le champ sur un flot de sortie.
Imprime la taille du tableau et les valeurs.
virtual Entree & readOn (Entree &)
Lit un champ a partir d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp)
et les valeurs de ces composantes.
Format:
Champ_Uniforme nb_comp vrel_1 ... [vrel_i].
virtual void set_nb_comp (int i)
calls fixer_nb_comp
virtual void set_name (const Nom &name)
calls nommer
virtual const Nom & get_name () const
calls le_nom
Detailed Description
class Ch_input_uniforme
Cette classe represente un champ uniforme accessible par setInputField
Definition at line 42 of file Ch_input_uniforme.h.
Constructor & Destructor Documentation
Ch_input_uniforme::Ch_input_uniforme ()
Definition at line 28 of file Ch_input_uniforme.cpp.
Ch_input_uniforme::~Ch_input_uniforme ()
Definition at line 28 of file Ch_input_uniforme.cpp.
Member Function Documentation
virtual Champ_base& Ch_input_uniforme::affecter_ (const Champ_base & ch) [inline, virtual]
Renvoie l'objet upcaste en Champ_base.
Returns:
Champ_base&
Signification: renvoie (*this) upcaste en Champ_base
Contraintes:
Reimplemented from Champ_Uniforme.
Definition at line 48 of file Ch_input_uniforme.h.
  {
    return *this;
  }
Objet_U * Ch_input_uniforme::cree_instance () [static]
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
int Ch_input_uniforme::duplique () const [virtual]
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
const Type_info * Ch_input_uniforme::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
const Nom & Ch_input_uniforme::get_name () const [protected, virtual]
calls le_nom
Definition at line 56 of file Ch_input_uniforme.cpp.
References Field_base::le_nom().
{
  return le_nom();
}
void Ch_input_uniforme::getTemplate (TrioField & afield) const [virtual]
Implements Champ_Input_Proto.
Definition at line 64 of file Ch_input_uniforme.cpp.
References Field_base::le_nom(), Champ_Input_Proto::mon_pb, and Field_base::nb_comp().
{
  afield.dummy_geom();
  afield.setName(le_nom().getChar());
  afield._time1=mon_pb->presentTime();
  afield._time2=mon_pb->futureTime();
  afield._nb_field_components=nb_comp();
}
const Type_info * Ch_input_uniforme::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
Sortie & Ch_input_uniforme::printOn (Sortie & os) const [protected, virtual]
Imprime le champ sur un flot de sortie.
Imprime la taille du tableau et les valeurs.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Uniforme.
Definition at line 41 of file Ch_input_uniforme.cpp.
{
  return os;
}
Entree & Ch_input_uniforme::readOn (Entree & is) [protected, virtual]
Lit un champ a partir d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp)
et les valeurs de ces composantes.
Format:
Champ_Uniforme nb_comp vrel_1 ... [vrel_i].
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Uniforme.
Definition at line 31 of file Ch_input_uniforme.cpp.
References Champ_Input_Proto::initial_value_, Champ_Input_Proto::mon_pb, Field_base::nb_compo_, Champ_Input_Proto::read(), DoubleTab::resize(), ArrOfDouble::size_array(), Champ_Input_Proto::sous_zone_ok, and Champ_Don_base::valeurs().
{
  sous_zone_ok=false;
  read(is);
  valeurs().resize(1, nb_compo_);
  if (initial_value_.size_array()) for (int i = 0; i < nb_compo_; i++) valeurs()(0, i) = initial_value_(i);
  mon_pb->addInputField(*this);
  return is;
}
const Ch_input_uniforme & Ch_input_uniforme::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
Ch_input_uniforme & Ch_input_uniforme::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
void Ch_input_uniforme::set_name (const Nom & name) [protected, virtual]
calls nommer
Implements Champ_Input_Proto.
Definition at line 51 of file Ch_input_uniforme.cpp.
References Field_base::nommer().
{
  nommer(name);
}
void Ch_input_uniforme::set_nb_comp (int i) [protected, virtual]
calls fixer_nb_comp
Implements Champ_Input_Proto.
Definition at line 46 of file Ch_input_uniforme.cpp.
References Field_base::fixer_nb_comp().
{
  fixer_nb_comp(i);
}
void Ch_input_uniforme::setValue (const TrioField & afield) [virtual]
Implements Champ_Input_Proto.
Definition at line 78 of file Ch_input_uniforme.cpp.
References Champ_Input_Proto::setValueOnTab(), and Champ_Don_base::valeurs().
{
  Champ_Input_Proto::setValueOnTab(afield, valeurs());
}
unsigned Ch_input_uniforme::taille_memoire () const [virtual]
Reimplemented from Champ_Uniforme.
Definition at line 28 of file Ch_input_uniforme.cpp.
Member Data Documentation
const Type_info Ch_input_uniforme::info_obj [static]
Reimplemented from Champ_Uniforme.
Definition at line 44 of file Ch_input_uniforme.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Ch_input_uniforme.h
src/Kernel/Champs/Ch_input_uniforme.cpp