TRUST: Champ_P0_PolyMAC Class Reference
Champ_P0_PolyMAC Class Reference
: class Champ_P0_PolyMAC
Champ correspondant a une inconnue scalaire (type temperature ou pression)
Degres de libertes : valeur aux elements + flux aux faces
#include <Champ_P0_PolyMAC.h>
Public Member Functions
Champ_P0_PolyMAC ()
~Champ_P0_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Zone_PolyMAC & zone_PolyMAC () const
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
Champ_base & affecter_ (const Champ_base &ch)
int imprime (Sortie &, int) const
virtual int fixer_nb_valeurs_nodales (int n)
DoubleTab & valeur_aux_faces (DoubleTab &vals) const
renvoie la valeur du champ aux faces
DoubleTab & trace (const Frontiere_dis_base &fr, DoubleTab &x, double t, int distant) const
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
void init_cl () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_P0_PolyMAC & self_cast (Objet_U &)
static const Champ_P0_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
IntTab icl
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
virtual Entree & readOn (Entree &)
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Protected Attributes
Ref_Zone_VF la_zone_VF
Detailed Description
: class Champ_P0_PolyMAC
Champ correspondant a une inconnue scalaire (type temperature ou pression)
Degres de libertes : valeur aux elements + flux aux faces
Definition at line 42 of file Champ_P0_PolyMAC.h.
Constructor & Destructor Documentation
Champ_P0_PolyMAC::Champ_P0_PolyMAC ()
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
Champ_P0_PolyMAC::~Champ_P0_PolyMAC ()
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
Member Function Documentation
Champ_base & Champ_P0_PolyMAC::affecter_ (const Champ_base & ch) [virtual]
Reimplemented from Champ_Inc_P0_base.
Definition at line 145 of file Champ_P0_PolyMAC.cpp.
References DoubleVect::echange_espace_virtuel(), la_zone_VF, ref_cast, Ref_Zone_VF::valeur(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), Zone_VF::xp(), and Zone_VF::xv().
{
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC,la_zone_VF.valeur());
  DoubleTab_parts part(valeurs());
  for (int i = 0; i < part.size(); i++) ch.valeur_aux(i ? zone.xv() : zone.xp(), part[i]);
  valeurs().echange_espace_virtuel();
  return *this;
}
void Champ_P0_PolyMAC::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Returns:
z_dis
Signification: la zone discretise
Contraintes:
Reimplemented from Champ_base.
Definition at line 88 of file Champ_P0_PolyMAC.cpp.
References la_zone_VF, and ref_cast.
{
  la_zone_VF=ref_cast(Zone_VF, z_dis);
}
Objet_U * Champ_P0_PolyMAC::cree_instance () [static]
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
int Champ_P0_PolyMAC::duplique () const [virtual]
Implements Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
int Champ_P0_PolyMAC::fixer_nb_valeurs_nodales (int n) [virtual]
Reimplemented from Champ_Inc_P0_base.
Definition at line 136 of file Champ_P0_PolyMAC.cpp.
References Champ_Inc_base::creer_tableau_distribue(), ref_cast, and zone_dis_base().
{
  if (n == zone_dis_base().zone().nb_elem()) //champ sans flux aux faces (ex. aiguilles)
    creer_tableau_distribue(zone_dis_base().zone().md_vector_elements());
  else //champ avec flux
    creer_tableau_distribue(ref_cast(Zone_PolyMAC, zone_dis_base()).mdv_elems_faces);
  return n;
}
const Type_info * Champ_P0_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
int Champ_P0_PolyMAC::imprime (Sortie & os, int ncomp) const [virtual]
Reimplemented from Champ_Inc_base.
Definition at line 111 of file Champ_P0_PolyMAC.cpp.
References Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), finl, Field_base::nb_compo_, Domaine::nb_som(), Champ_Inc_base::valeurs(), Zone_dis_base::zone(), and zone_dis_base().
{
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& zone = zone_dis.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const int nb_som = zone.domaine().nb_som();
  const DoubleTab& val = valeurs();
  int som;
  os << nb_som << finl;
  for (som=0; som<nb_som; som++)
    {
      if (dimension==3)
        os << coord(som,0) << " " << coord(som,1) << " " << coord(som,2) << " " ;
      if (dimension==2)
        os << coord(som,0) << " " << coord(som,1) << " " ;
      if (nb_compo_ == 1)
        os << val(som) << finl;
      else
        os << val(som,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_P0_PolyMAC::imprime FIN >>>>>>>>>> " << finl;
  return 1;
}
const Type_info * Champ_P0_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
void Champ_P0_PolyMAC::init_cl () const
Definition at line 155 of file Champ_P0_PolyMAC.cpp.
References Cerr, IntTab::dimension(), MorEqn::equation(), Process::exit(), finl, icl, la_zone_VF, Zone_Cl_dis::les_conditions_limites(), Champ_Inc_base::ma_zone_cl_dis, Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, IntTab::resize(), sub_type, valeur(), Ref_Zone_Cl_dis::valeur(), and Ref_Zone_VF::valeur().
Referenced by Masse_PolyMAC_Elem::ajouter_masse(), Op_Diff_PolyMAC_Elem::completer(), and Masse_PolyMAC_Elem::dimensionner().
{
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC,la_zone_VF.valeur());
  const Conds_lim& cls = ma_zone_cl_dis.valeur().les_conditions_limites();
  int i, f, n;
  if (icl.dimension(0)) return;
  icl.resize(zone.nb_faces_tot(), 3);
  for (n = 0; n < cls.size(); n++)
    {
      const Front_VF& fvf = ref_cast(Front_VF, cls[n].frontiere_dis());
      int idx = sub_type(Echange_externe_impose, cls[n].valeur()) + 2 * sub_type(Echange_global_impose, cls[n].valeur())
                + 4 * sub_type(Neumann_paroi, cls[n].valeur())      + 5 * (sub_type(Neumann_homogene, cls[n].valeur()) || sub_type(Neumann_sortie_libre, cls[n].valeur()) || sub_type(Symetrie, cls[n].valeur()))
                + 6 * sub_type(Dirichlet, cls[n].valeur())          + 7 * sub_type(Dirichlet_homogene, cls[n].valeur());
      if (sub_type(Echange_contact_PolyMAC, cls[n].valeur()) && sub_type(Schema_Euler_Implicite, equation().schema_temps())
          && ref_cast(Schema_Euler_Implicite, equation().schema_temps()).thermique_monolithique()) idx = 3;
      if (!idx) Cerr << "Champ_P0_PolyMAC : CL non codee rencontree!" << finl, Process::exit();
      for (i = 0; i < fvf.nb_faces_tot(); i++)
        f = fvf.num_face(i), icl(f, 0) = idx, icl(f, 1) = n, icl(f, 2) = i;
    }
}
Sortie & Champ_P0_PolyMAC::printOn (Sortie & os) const [protected, virtual]
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 44 of file Champ_P0_PolyMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_P0_PolyMAC::readOn (Entree & is) [protected, virtual]
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_P0_base.
Definition at line 52 of file Champ_P0_PolyMAC.cpp.
References Champ_Inc_base::lire_donnees().
{
  lire_donnees(s) ;
  return s ;
}
Champ_P0_PolyMAC & Champ_P0_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
const Champ_P0_PolyMAC & Champ_P0_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Inc_P0_base.
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
unsigned Champ_P0_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 40 of file Champ_P0_PolyMAC.cpp.
DoubleTab & Champ_P0_PolyMAC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const [inline, virtual]
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_P0_base.
Definition at line 79 of file Champ_P0_PolyMAC.h.
References DoubleTab::dimension(), DoubleTab::dimension_tot(), Zone_VF::face_voisins(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_face(), ref_cast, DoubleTab::resize(), Champ_Inc_base::valeurs(), and zone_dis_base().
{
  /* dimensionnement du tableau de destination x si necessaire */
  const DoubleTab& src = valeurs();
  const Front_VF& fvf = ref_cast(Front_VF, fr);
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, zone_dis_base());
  const IntTab& f_e = zone.face_voisins();
  DoubleTrav dst; //reconstruction du champ aux faces (on ne le remplit que sur le bord concerne)
  int i, n, e, f, N = src.nb_dim() > 1 ? src.dimension(1): 1, has_faces = src.dimension_tot(0) > zone.nb_elem_tot();
  if (!x.dimension(0) && !x.get_md_vector().non_nul()) x.resize(fvf.nb_faces(), N);
  N > 1 ? dst.resize(zone.nb_faces(), N) : dst.resize(zone.nb_faces()); //aargh
  for (i = 0; i < fvf.nb_faces(); i++) for (n = 0, f = fvf.num_face(i), e = f_e(f, 0); n < N; n++)
      dst(f, n) = src(has_faces ? zone.nb_elem_tot() + f : e, n);
  if (distant) fr.frontiere().trace_face_distant(dst, x);
  else fr.frontiere().trace_face_local(dst, x);
  return x;
}
DoubleTab & Champ_P0_PolyMAC::valeur_aux_faces (DoubleTab & result) const [virtual]
renvoie la valeur du champ aux faces
Reimplemented from Champ_base.
Definition at line 177 of file Champ_P0_PolyMAC.cpp.
References DoubleTab::dimension(), DoubleTab::dimension_tot(), Zone_VF::face_voisins(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone_VF::premiere_face_int(), ref_cast, Champ_Inc_base::valeurs(), Zone_VF::xv(), and zone_dis_base().
{
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, zone_dis_base());
  const IntTab& f_e = zone.face_voisins();
  const DoubleTab& src = valeurs();
  /* vals doit etre pre-dimensionne */
  int i, e, f, n, N = (src.nb_dim() == 1 ? 1 : src.dimension(1));
  assert(dst.dimension(0) == zone.xv().dimension(0) && N == (dst.nb_dim() == 1 ? 1 : dst.dimension(1)));
  if (src.dimension_tot(0) > zone.nb_elem_tot()) //on a les valeurs aux faces
    for (f = 0; f < dst.dimension(0); f++) for (n = 0; n < N; n++) dst(f, n) = src(zone.nb_elem_tot() + f, n);
  else for (f = 0; f < dst.dimension(0); f++) //on prend (amont + aval) / 2
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) for (n = 0; n < N; n++)
          dst(f, n) += src(e, n) * (f < zone.premiere_face_int() ? 1 : 0.5);
  return dst;
}
const Zone_dis_base & Champ_P0_PolyMAC::zone_dis_base () const [virtual]
Reimplemented from Champ_base.
Definition at line 71 of file Champ_P0_PolyMAC.cpp.
References la_zone_VF, and Ref_Zone_VF::valeur().
Referenced by fixer_nb_valeurs_nodales(), imprime(), trace(), and valeur_aux_faces().
{
  return la_zone_VF.valeur();
}
const Zone_PolyMAC & Champ_P0_PolyMAC::zone_PolyMAC () const
Returns:
la_zone_PolyMAC_P0.valeur()
Signification:
Contraintes:
Definition at line 106 of file Champ_P0_PolyMAC.cpp.
References la_zone_VF, ref_cast, and Ref_Zone_VF::valeur().
{
  return ref_cast(Zone_PolyMAC, la_zone_VF.valeur());
}
Member Data Documentation
IntTab Champ_P0_PolyMAC::icl [mutable]
Definition at line 70 of file Champ_P0_PolyMAC.h.
Referenced by Op_Diff_PolyMAC_Elem::ajouter(), Masse_PolyMAC_Elem::ajouter_masse(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Masse_PolyMAC_Elem::dimensionner(), init_cl(), and Op_Diff_PolyMAC_Elem::update_delta().
const Type_info Champ_P0_PolyMAC::info_obj [static]
Reimplemented from Champ_Inc_P0_base.
Definition at line 44 of file Champ_P0_PolyMAC.h.
Ref_Zone_VF Champ_P0_PolyMAC::la_zone_VF [protected]
Definition at line 74 of file Champ_P0_PolyMAC.h.
Referenced by affecter_(), associer_zone_dis_base(), init_cl(), zone_dis_base(), and zone_PolyMAC().
The documentation for this class was generated from the following files:
src/PolyMAC/Champs/Champ_P0_PolyMAC.h
src/PolyMAC/Champs/Champ_P0_PolyMAC.cpp