TRUST: Navier_Stokes_Fluide_Dilatable_Proto Class Reference
Navier_Stokes_Fluide_Dilatable_Proto Class Reference
classe Navier_Stokes_Fluide_Dilatable_Proto
#include <Navier_Stokes_Fluide_Dilatable_Proto.h>
Public Member Functions
Navier_Stokes_Fluide_Dilatable_Proto ()
int impr_impl (const Navier_Stokes_std &eqn, Sortie &os) const
void assembler_impl (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
void assembler_avec_inertie_impl (const Navier_Stokes_std &eqn, Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
void assembler_blocs_avec_inertie (const Navier_Stokes_std &eqn, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl)
DoubleTab & derivee_en_temps_inco_impl (Navier_Stokes_std &, DoubleTab &res)
Calcule la derivee en temps de l'inconnue vitesse,
i.e. l'acceleration dU/dt et la renvoie.
Appelle Equation_base::derivee_en_temps_inco(DoubleTab&)
Calcule egalement la pression.
DoubleTab & rho_vitesse_impl (const DoubleTab &tab_rho, const DoubleTab &vit, DoubleTab &rhovitesse) const
Protected Attributes
Champ_Inc rho_la_vitesse_
IntVect orientation_VDF_
DoubleTab tab_W
RHS of div(rho.U)
Private Member Functions
void prepare_and_solve_u_star (Navier_Stokes_std &eqn, const Fluide_Dilatable_base &fluide_dil, DoubleTab &rhoU, DoubleTab &vpoint)
void update_vpoint_on_boundaries (const Navier_Stokes_std &eqn, const Fluide_Dilatable_base &fluide_dil, DoubleTab &vpoint)
void solve_pressure_increment (Navier_Stokes_std &eqn, const Fluide_Dilatable_base &fluide_dil, DoubleTab &rhoU, DoubleTab &secmem, DoubleTab &inc_pre, DoubleTab &vpoint)
void correct_and_compute_u_np1 (Navier_Stokes_std &eqn, const Fluide_Dilatable_base &fluide_dil, DoubleTab &rhoU, DoubleTab &Mmoins1grad, DoubleTab &inc_pre, DoubleTab &gradP, DoubleTab &vpoint)
Private Attributes
double cumulative_
Detailed Description
classe Navier_Stokes_Fluide_Dilatable_Proto
Definition at line 35 of file Navier_Stokes_Fluide_Dilatable_Proto.h.
Constructor & Destructor Documentation
Navier_Stokes_Fluide_Dilatable_Proto()
Navier_Stokes_Fluide_Dilatable_Proto::Navier_Stokes_Fluide_Dilatable_Proto ()
Definition at line 32 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
: cumulative_(0) { }
Member Function Documentation
assembler_avec_inertie_impl()
void Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl (const Navier_Stokes_std & eqn, Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem)
< rho*U
Definition at line 166 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
// ******   avant inertie   ******
// diffusion en div(mu grad u) or on veut impliciter en rho * u => on divise les contributions par le rho_face associe
// GF on ajoute apres avoir contribuer pour avoir les bons flux bords
  DoubleTrav rhovitesse(present);
// Op diff
  eqn.operateur(0).l_op_base().contribuer_a_avec(present,mat_morse);
  eqn.operateur(0).ajouter(secmem);
  const Fluide_Dilatable_base& fluide_dil=ref_cast(Fluide_Dilatable_base,eqn.milieu());
  const DoubleTab& tab_rho_face_np1 = fluide_dil.rho_face_np1(), tab_rho_face_n=fluide_dil.rho_face_n();
  const int nb_compo = present.line_size();
  const IntVect& tab1 = mat_morse.get_tab1(), tab2 = mat_morse.get_tab2();
  DoubleVect& coeff = mat_morse.get_set_coeff();
  for (int i=0; i<mat_morse.nb_lignes(); i++)
    for (int k=tab1(i)-1; k<tab1(i+1)-1; k++)
      {
        int j = tab2(k)-1;
        double rapport = tab_rho_face_np1(j/nb_compo);
        coeff(k) /= rapport;
      }
  rho_vitesse_impl(tab_rho_face_np1,present,rhovitesse); //!< rho*U
// Op conv
  eqn.operateur(1).l_op_base().contribuer_a_avec(rhovitesse,mat_morse);
  eqn.operateur(1).ajouter(rhovitesse,secmem);
// sources
  eqn.sources().ajouter(secmem);
  eqn.sources().contribuer_a_avec(present,mat_morse);
// on resout en rho u on stocke donc rho u dans present
  rho_vitesse_impl(tab_rho_face_np1,present,ref_cast_non_const(DoubleTab,present));
  mat_morse.ajouter_multvect(present,secmem);
  /*
   * contribution a la matrice de l'inertie :
   * on divisie la diagonale par rhon+1 face
   * on ajoute l'inertie de facon standard
   * on remultiplie la diagonale par rhon+1
   */
// ajout de l'inertie
  const double dt=eqn.schema_temps().pas_de_temps();
  eqn.solv_masse().ajouter_masse(dt,mat_morse,0);
  rho_vitesse_impl(tab_rho_face_n,eqn.inconnue().passe(),rhovitesse);
  eqn.solv_masse().ajouter_masse(dt,secmem,rhovitesse,0);
// blocage_cl faux si dirichlet u!=0 !!!!!! manque multiplication par rho
  for (int op=0; op< eqn.nombre_d_operateurs(); op++) eqn.operateur(op).l_op_base().modifier_pour_Cl(mat_morse,secmem);
  /*
   * correction finale pour les dirichlets
   * on ne doit pas imposer un+1 mais rho_un+1 => on multiplie dons le resu par rho_face_np1
   */
  const Conds_lim& lescl=eqn.zone_Cl_dis().les_conditions_limites();
  int nbcondlim=lescl.size();
  for (int icl=0; icl<nbcondlim; icl++)
    {
      const Cond_lim_base& la_cl_base = lescl[icl].valeur();
      if (sub_type(Dirichlet,la_cl_base))
        {
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
          int ndeb = la_front_dis.num_premiere_face();
          int nfin = ndeb + la_front_dis.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              if (present.line_size()==1) secmem(num_face)*=tab_rho_face_np1(num_face);
              else
                for (int dir=0; dir<Objet_U::dimension; dir++) secmem(num_face,dir)*=tab_rho_face_np1(num_face);
            }
        }
    }
}
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::ajouter_masse(), Matrice_Base::ajouter_multvect(), coeff, Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Objet_U::dimension, Cond_lim_base::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Navier_Stokes_std::inconnue(), Operateur::l_op_base(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Navier_Stokes_std::milieu(), Operateur_base::modifier_pour_Cl(), Front_VF::nb_faces(), Matrice_Morse::nb_lignes(), Navier_Stokes_std::nombre_d_operateurs(), Front_VF::num_premiere_face(), Navier_Stokes_std::operateur(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), ref_cast, ref_cast_non_const, Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Equation_base::schema_temps(), vect_impl::size(), Equation_base::solv_masse(), Equation_base::sources(), sub_type, and Equation_base::zone_Cl_dis().
Referenced by Navier_Stokes_Fluide_Dilatable_base::assembler_avec_inertie().
assembler_blocs_avec_inertie()
void Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie (const Navier_Stokes_std & eqn, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl)
< rho*U
Definition at line 250 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  statistiques().begin_count(assemblage_sys_counter_);
  const std::string& nom_inco = eqn.inconnue().le_nom().getString();
  Matrice_Morse *mat = matrices.count(nom_inco)?matrices.at(nom_inco):NULL;
  const DoubleTab& present = eqn.inconnue()->valeurs();
// ******   avant inertie   ******
// diffusion en div(mu grad u) or on veut impliciter en rho * u => on divise les contributions par le rho_face associe
// GF on ajoute apres avoir contribuer pour avoir les bons flux bords
  DoubleTrav rhovitesse(present);
// Op diff
  eqn.operateur(0).l_op_base().ajouter_blocs(matrices, secmem, semi_impl);
  const Fluide_Dilatable_base& fluide_dil=ref_cast(Fluide_Dilatable_base,eqn.milieu());
  const DoubleTab& tab_rho_face_np1 = fluide_dil.rho_face_np1(), tab_rho_face_n=fluide_dil.rho_face_n();
  const int nb_compo = present.line_size();
  const IntVect& tab1 = mat->get_tab1(), tab2 = mat->get_tab2();
  DoubleVect& coeff = mat->get_set_coeff();
  for (int i=0; i<mat->nb_lignes(); i++)
    for (int k=tab1(i)-1; k<tab1(i+1)-1; k++)
      {
        int j = tab2(k)-1;
        double rapport = tab_rho_face_np1(j/nb_compo);
        coeff(k) /= rapport;
      }
  rho_vitesse_impl(tab_rho_face_np1,present,rhovitesse); //!< rho*U
// Op conv
  eqn.operateur(1).l_op_base().ajouter_blocs(matrices, secmem, {{nom_inco,rhovitesse}});
  statistiques().end_count(assemblage_sys_counter_);
// sources
  statistiques().begin_count(source_counter_);
  for (int i = 0; i < eqn.sources().size(); i++)
    eqn.sources()(i).valeur().ajouter_blocs(matrices, secmem, semi_impl);
  statistiques().end_count(source_counter_);
  statistiques().begin_count(assemblage_sys_counter_);
// on resout en rho u on stocke donc rho u dans present
  rho_vitesse_impl(tab_rho_face_np1,present,ref_cast_non_const(DoubleTab,present));
  mat->ajouter_multvect(present,secmem);
  DoubleTab tmp(secmem);
  tmp = 0.0;
  eqn.operateur_gradient().valeur().ajouter_blocs(matrices, tmp, semi_impl);
  secmem-=tmp;
  /*
   * contribution a la matrice de l'inertie :
   * on divisie la diagonale par rhon+1 face
   * on ajoute l'inertie de facon standard
   * on remultiplie la diagonale par rhon+1
   */
// ajout de l'inertie
  const double dt=eqn.schema_temps().pas_de_temps();
  eqn.solv_masse().ajouter_masse(dt,*mat,0);
  rho_vitesse_impl(tab_rho_face_n,eqn.inconnue().passe(),rhovitesse);
  eqn.solv_masse().ajouter_masse(dt,secmem,rhovitesse,0);
// blocage_cl faux si dirichlet u!=0 !!!!!! manque multiplication par rho
  for (int op=0; op< eqn.nombre_d_operateurs(); op++) eqn.operateur(op).l_op_base().modifier_pour_Cl(*mat,secmem);
  /*
   * correction finale pour les dirichlets
   * on ne doit pas imposer un+1 mais rho_un+1 => on multiplie dons le resu par rho_face_np1
   */
  const Conds_lim& lescl=eqn.zone_Cl_dis().les_conditions_limites();
  int nbcondlim=lescl.size();
  for (int icl=0; icl<nbcondlim; icl++)
    {
      const Cond_lim_base& la_cl_base = lescl[icl].valeur();
      if (sub_type(Dirichlet,la_cl_base))
        {
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
          int ndeb = la_front_dis.num_premiere_face();
          int nfin = ndeb + la_front_dis.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              if (present.line_size()==1) secmem(num_face)*=tab_rho_face_np1(num_face);
              else
                for (int dir=0; dir<Objet_U::dimension; dir++) secmem(num_face,dir)*=tab_rho_face_np1(num_face);
            }
        }
    }
  secmem.echange_espace_virtuel();
  statistiques().end_count(assemblage_sys_counter_);
}
References Operateur_base::ajouter_blocs(), Solveur_Masse::ajouter_masse(), Matrice_Base::ajouter_multvect(), assemblage_sys_counter_, Statistiques::begin_count(), coeff, Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Statistiques::end_count(), Cond_lim_base::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Navier_Stokes_std::inconnue(), Operateur::l_op_base(), O_U_Ptr::le_nom(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Navier_Stokes_std::milieu(), Operateur_base::modifier_pour_Cl(), Front_VF::nb_faces(), Matrice_Morse::nb_lignes(), Navier_Stokes_std::nombre_d_operateurs(), Front_VF::num_premiere_face(), Navier_Stokes_std::operateur(), Navier_Stokes_std::operateur_gradient(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), ref_cast, ref_cast_non_const, Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Equation_base::schema_temps(), vect_impl::size(), Equation_base::solv_masse(), source_counter_, Equation_base::sources(), statistiques(), sub_type, Deriv_Operateur_Grad_base::valeur(), valeur(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
Referenced by Navier_Stokes_Fluide_Dilatable_base::assembler_blocs_avec_inertie().
assembler_impl()
void Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem)
Definition at line 347 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  Cerr << "Navier_Stokes_Fluide_Dilatable_Proto::assembler is not coded ! You should use assembler_avec_inertie !" << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
Referenced by Navier_Stokes_Fluide_Dilatable_base::assembler().
correct_and_compute_u_np1()
void Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1 (Navier_Stokes_std & eqn, const Fluide_Dilatable_base & fluide_dil, DoubleTab & rhoU, DoubleTab & Mmoins1grad, DoubleTab & inc_pre, DoubleTab & gradP, DoubleTab & vpoint) private
< M-1 F
< rhoU(n+1)
Definition at line 540 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  const DoubleTab& tab_rho_face_np1=fluide_dil.rho_face_np1();
  const DoubleTab& vit = eqn.vitesse().valeurs();
  DoubleTab& press = eqn.pression().valeurs();
  const double dt_ = eqn.schema_temps().pas_de_temps();
// On a besoin de l'espace virtuel de la pression pour calculer le gradient plus bas
// et modifier_solution ne fait pas toujours l'echange_espace_virtuel.
// On suppose que pression et inc_pre ont leur espace virtuel a jour
// On fait pression += inc_pre:
  operator_add(press, inc_pre, VECT_ALL_ITEMS);
  eqn.assembleur_pression().modifier_solution(press);
// Correction de la vitesse en pression : M-1 Bt P
  eqn.solv_masse().appliquer(gradP);
  vpoint += gradP; //!< M-1 F
  press.echange_espace_virtuel();
  eqn.operateur_gradient().calculer(press, gradP);
// On conserve Bt P pour la prochaine fois.
  Mmoins1grad = gradP;
  eqn.solv_masse().appliquer(Mmoins1grad);
// Correction en pression
  vpoint -= Mmoins1grad;
// vpoint = (rhoU(n+1)-rhoU(n))/dt
  vpoint *= dt_;
  vpoint += rhoU; //!< rhoU(n+1)
// Compute U(n+1):
  const int n = vpoint.dimension(0), ncomp = vpoint.line_size();
  for (int i=0 ; i<n ; i++)
    for (int j=0 ; j< ncomp; j++) vpoint(i,j) /= tab_rho_face_np1(i);
// Compute (U(n+1)-U(n))/dt :
  vpoint -= vit;
  vpoint /= dt_;
  vpoint.echange_espace_virtuel();
  Debog::verifier("Navier_Stokes_Fluide_Dilatable_base::derivee_en_temps_inco, vpoint : ", vpoint);
} /* END correct_and_compute_u_np1 */
References Solveur_Masse::appliquer(), Navier_Stokes_std::assembleur_pression(), Operateur_Grad::calculer(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::line_size(), Assembleur::modifier_solution(), Navier_Stokes_std::operateur_gradient(), operator_add(), Schema_Temps_base::pas_de_temps(), Navier_Stokes_std::pression(), Fluide_Dilatable_base::rho_face_np1(), Equation_base::schema_temps(), Equation_base::solv_masse(), Champ_Inc::valeurs(), VECT_ALL_ITEMS, Debog::verifier(), and Navier_Stokes_std::vitesse().
Referenced by derivee_en_temps_inco_impl().
derivee_en_temps_inco_impl()
DoubleTab & Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl (Navier_Stokes_std & eqn, DoubleTab & vpoint)
Calcule la derivee en temps de l'inconnue vitesse,
i.e. l'acceleration dU/dt et la renvoie.
Appelle Equation_base::derivee_en_temps_inco(DoubleTab&)
Calcule egalement la pression.
Returns
DoubleTab&
Signification: le tableau des valeurs de l'acceleration (derivee de la vitesse)
Contraintes:
< copie la structure initialisation sinon plantage assert lors du remplissage dans EDO_Pression_th_VEF::secmembre_divU_Z_VEFP1B
< copie la structure
Definition at line 118 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  const Fluide_Dilatable_base& fluide_dil=ref_cast(Fluide_Dilatable_base,eqn.milieu());
  DoubleTab& press = eqn.pression().valeurs(), vit = eqn.vitesse().valeurs();
  DoubleTab secmem(press);
  DoubleTrav inc_pre(press);
  if (!tab_W.get_md_vector().non_nul())
    {
      tab_W.copy(secmem, Array_base::NOCOPY_NOINIT); //!< copie la structure initialisation sinon plantage assert lors du remplissage dans EDO_Pression_th_VEF::secmembre_divU_Z_VEFP1B
//
      tab_W = 0.;
    }
  DoubleTab rhoU;
  rhoU.copy(vit, Array_base::NOCOPY_NOINIT); //!< copie la structure
// Get champ gradP
  REF(Champ_base) gradient_pression;
  try
    {
      gradient_pression = eqn.get_champ("gradient_pression");
    }
  catch (Champs_compris_erreur)
    {
      Cerr<<" l'equation ne comprend pas gradient_pression "<<finl;
      Process::exit();
    }
  DoubleTab& gradP=gradient_pression.valeur().valeurs();
  DoubleTrav Mmoins1grad(gradP);
// We use the incremental pressure-projection algorithm (Chorin)
// Step 1 : prepare operators and solve for a provisional velocity u*
  prepare_and_solve_u_star(eqn,fluide_dil,rhoU, vpoint);
// Step 2 : solve the poisson equation for the pressure increment (Pi = P^n+1 - P^n)
// Attention the matrix has a constant coefficient as the variable of NS is rhoU and not U !!!
  solve_pressure_increment(eqn,fluide_dil,rhoU,secmem,inc_pre,vpoint);
// Step 3 : compute P^n+1 & compute the correct velocity u^n+1
  correct_and_compute_u_np1(eqn,fluide_dil,rhoU,Mmoins1grad,inc_pre,gradP,vpoint);
  return vpoint;
}
References Cerr, TRUSTTab< _TYPE_ >::copy(), correct_and_compute_u_np1(), Process::exit(), finl, Navier_Stokes_std::get_champ(), TRUSTVect< _TYPE_ >::get_md_vector(), Navier_Stokes_std::milieu(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), prepare_and_solve_u_star(), Navier_Stokes_std::pression(), REF, ref_cast, solve_pressure_increment(), tab_W, Champ_Inc::valeurs(), and Navier_Stokes_std::vitesse().
Referenced by Navier_Stokes_Fluide_Dilatable_base::derivee_en_temps_inco().
impr_impl()
int Navier_Stokes_Fluide_Dilatable_Proto::impr_impl (const Navier_Stokes_std & eqn, Sortie & os) const
< init structure uniquement
< max|sum(rho*u*ndS)|
< =max|LocalMassFlowRateError/(rho_moyen*Vol(i)/dt)|
Definition at line 47 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  const Fluide_Dilatable_base& fluide_dil = ref_cast(Fluide_Dilatable_base,eqn.fluide());
  const DoubleTab& vit = eqn.vitesse().valeurs(), rho = fluide_dil.rho_face_np1();
  DoubleTab mass_flux(vit);
  rho_vitesse_impl(rho,vit,mass_flux);
  DoubleTab array;
  array.copy(eqn.div().valeurs(), Array_base::NOCOPY_NOINIT); //!< init structure uniquement
  if (tab_W.get_md_vector().non_nul())
    {
      operator_egal(array, tab_W ); //, VECT_REAL_ITEMS); //!< initialise
      array*=-1;
    }
  else
    {
// remarque B.M.: certaines implementations de cette methode ne font pas echange espace virtuel:
      fluide_dil.secmembre_divU_Z(array);
      array*=-1;
    }
  array.echange_espace_virtuel();
  eqn.operateur_divergence().ajouter(mass_flux, array);
  double LocalMassFlowRateError = mp_max_abs_vect(array); //!< max|sum(rho*u*ndS)|
  os << "-------------------------------------------------------------------"<< finl;
  os << "Cell balance mass flow rate control for the problem " << eqn.probleme().le_nom() << " : " << finl;
  os << "Absolute value : " << LocalMassFlowRateError << " kg/s" << finl; ;
// On divise array par vol(i)
  eqn.operateur_divergence().volumique(array);
// On divise par un rho moyen
  double rho_moyen = mp_moyenne_vect(rho), dt = eqn.probleme().schema_temps().pas_de_temps();
  double bilan_massique_relatif = mp_max_abs_vect(array) * dt / rho_moyen;
  os << "Relative value : " << bilan_massique_relatif << finl; //!< =max|LocalMassFlowRateError/(rho_moyen*Vol(i)/dt)|
// Calculation as OpenFOAM: http://foam.sourceforge.net/docs/cpp/a04190_source.html
// It is relative errors (normalized by the volume/dt)
  double TotalMass = rho_moyen * eqn.probleme().domaine().zone(0).volume_total();
  double local = LocalMassFlowRateError / ( TotalMass / dt ), global = mp_somme_vect(array) / ( TotalMass / dt );
  cumulative_ += global;
  os << "time step continuity errors : sum local = " << local << ", global = " << global << ", cumulative = " << cumulative_ << finl;
  if (local > 0.01)
    {
      Cerr << "The mass balance is too bad (relative value > 1%)." << finl;
      Cerr << "Please check and lower the convergence value of the pressure solver." << finl;
      Process::exit();
    }
  return 1;
}
References Operateur_Div::ajouter(), Cerr, TRUSTTab< _TYPE_ >::copy(), cumulative_, Navier_Stokes_std::div(), Probleme_base::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Navier_Stokes_std::fluide(), TRUSTVect< _TYPE_ >::get_md_vector(), Probleme_base::le_nom(), mp_max_abs_vect(), mp_moyenne_vect(), mp_somme_vect(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), Navier_Stokes_std::operateur_divergence(), operator_egal(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), ref_cast, Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Probleme_base::schema_temps(), Fluide_Dilatable_base::secmembre_divU_Z(), tab_W, Champ_Inc::valeurs(), Navier_Stokes_std::vitesse(), Zone::volume_total(), Operateur_Div::volumique(), and Domaine::zone().
Referenced by Navier_Stokes_Fluide_Dilatable_base::impr().
prepare_and_solve_u_star()
void Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star (Navier_Stokes_std & eqn, const Fluide_Dilatable_base & fluide_dil, DoubleTab & rhoU, DoubleTab & vpoint) private
< rho avec la meme discretisation que la vitesse
Definition at line 358 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  const DoubleTab& tab_rho_face_n =fluide_dil.rho_face_n(), tab_rho_face_np1=fluide_dil.rho_face_np1();
  const DoubleTab& tab_rho = fluide_dil.rho_discvit(); //!< rho avec la meme discretisation que la vitesse
  const DoubleTab& vit = eqn.vitesse().valeurs();
  fluide_dil.secmembre_divU_Z(tab_W); //Calcule W=-dZ/dt, 2nd membre de l'equation div(rhoU) = W
  vpoint=0;
// ajout diffusion (avec la viscosite dynamique)
  if (!eqn.schema_temps().diffusion_implicite()) eqn.operateur(0).ajouter(vpoint);
  DoubleTab& rhovitesse = ref_cast_non_const(DoubleTab,eqn.rho_la_vitesse().valeurs());
  rho_vitesse_impl(tab_rho,vit,rhovitesse);
// ajout convection utilise rhovitesse
  if (!eqn.schema_temps().diffusion_implicite()) eqn.operateur(1).ajouter(rhovitesse,vpoint);
  else
    {
      DoubleTrav trav(vpoint);
      eqn.derivee_en_temps_conv(trav,rhovitesse);
      vpoint = trav;
    }
// ajout source
  eqn.sources().ajouter(vpoint);
// ajout de gradP
  eqn.corriger_derivee_expl(vpoint);
  const Champ_base& rho_vit=eqn.get_champ("rho_comme_v");
  ref_cast_non_const(DoubleTab,rho_vit.valeurs())=tab_rho_face_np1;
  if (eqn.schema_temps().diffusion_implicite())
    {
      DoubleTrav secmemV(vpoint);
      secmemV = vpoint;
      double dt = eqn.schema_temps().pas_de_temps();
      /*
       * secmemV contient M(rhonp1 unp1 -rhon un)/dt
       * M-1 secmemv*dt+rhon un -rhonp1un= rhonp1 (unp1 -unp )
       * dt/rhnhonp1 =(unp1-un)/dt
       * M-1 secmemV/rhonp1 + (rhon  -rhonp1)/rhonp1/dt  un
       *
       * on modifie le solveur masse pour diviser par rhonp1
       * (pratique aussi pour la diffusion implicite)
       */
      eqn.solv_masse()->set_name_of_coefficient_temporel("rho_comme_v");
      eqn.solv_masse().appliquer(secmemV);
      DoubleTrav dr(tab_rho_face_n);
      for (int i=0; i<dr.size_totale(); i++) dr(i)=(tab_rho_face_n(i)/tab_rho_face_np1(i)-1.)/dt;
// on sert de vpoint pour calculer
      rho_vitesse_impl(dr,vit,vpoint);
      secmemV += vpoint;
      DoubleTab delta_u(eqn.inconnue().futur());
      eqn.Gradient_conjugue_diff_impl(secmemV, delta_u ) ;
      /*
       * delta_u=unp1 -un => delta_u + un=unp1
       * (delat_u + un)*rhonp1 = rhonp1 * unp1
       * (delat_u + un)*rhonp1  - rhon * un= rhonp1 * unp1 - rhon * un
       */
      delta_u *= dt;
      delta_u += vit;
      rho_vitesse_impl(tab_rho_face_np1,delta_u,vpoint);
      vpoint -= rhovitesse;
      vpoint /= dt;
      eqn.solv_masse()->set_name_of_coefficient_temporel("no_coeff");
    }
  else eqn.solv_masse().appliquer(vpoint);
  update_vpoint_on_boundaries(eqn,fluide_dil,vpoint);
} /* END prepare_and_solve_u_star */
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse::appliquer(), Navier_Stokes_std::corriger_derivee_expl(), Equation_base::derivee_en_temps_conv(), Schema_Temps_base::diffusion_implicite(), Champ_Inc::futur(), Navier_Stokes_std::get_champ(), Equation_base::Gradient_conjugue_diff_impl(), Navier_Stokes_std::inconnue(), Navier_Stokes_std::operateur(), Schema_Temps_base::pas_de_temps(), ref_cast_non_const, Fluide_Dilatable_base::rho_discvit(), Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), Navier_Stokes_std::rho_la_vitesse(), rho_vitesse_impl(), Equation_base::schema_temps(), Fluide_Dilatable_base::secmembre_divU_Z(), TRUSTVect< _TYPE_ >::size_totale(), Equation_base::solv_masse(), Equation_base::sources(), tab_W, update_vpoint_on_boundaries(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Navier_Stokes_std::vitesse().
Referenced by derivee_en_temps_inco_impl().
rho_vitesse_impl()
DoubleTab & Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl (const DoubleTab & tab_rho, const DoubleTab & vit, DoubleTab & rhovitesse) const
Definition at line 35 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  const int n = vit.dimension(0), ncomp = vit.line_size();
  for (int i=0 ; i<n ; i++)
    for (int j=0 ; j<ncomp ; j++) rhovitesse(i,j) = tab_rho(i,0)*vit(i,j);
  rhovitesse.echange_espace_virtuel();
  Debog::verifier("Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse : ", rhovitesse);
  return rhovitesse;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::line_size(), and Debog::verifier().
Referenced by assembler_avec_inertie_impl(), assembler_blocs_avec_inertie(), impr_impl(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), prepare_and_solve_u_star(), and solve_pressure_increment().
solve_pressure_increment()
void Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment (Navier_Stokes_std & eqn, const Fluide_Dilatable_base & fluide_dil, DoubleTab & rhoU, DoubleTab & secmem, DoubleTab & inc_pre, DoubleTab & vpoint) private
< (-tabW + Div(rhoU))/dt
Definition at line 492 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
  const DoubleTab& tab_rho_face_n =fluide_dil.rho_face_n(), tab_rho_face_np1=fluide_dil.rho_face_np1();
  const DoubleTab& vit = eqn.vitesse().valeurs();
  const double dt_ = eqn.schema_temps().pas_de_temps(),t = eqn.schema_temps().temps_courant();
// Resolution pression
  vpoint.echange_espace_virtuel();
// Compute rhoU(n) :
  rho_vitesse_impl(tab_rho_face_n,vit,rhoU);
// Add source term to vpoint if interfaces
  Probleme_base& prob=eqn.probleme();
  DoubleTrav vpoint0(vpoint) ;
  vpoint0 = vpoint ;
  for (int i=0; i<prob.nombre_d_equations(); i++)
    if (sub_type(Transport_Interfaces_base,prob.equation(i)))
      {
        Transport_Interfaces_base& eq_transport = ref_cast(Transport_Interfaces_base,prob.equation(i));
        const int nb = vpoint.dimension(0), m = vpoint.line_size();
        DoubleTab source_ibc(nb,m);
// On ajoute un terme source a vpoint pour imposer au fluide la vitesse de l interface
// source_ibc est local pas postraitable (different cas FT ou le terme source est defini et peut etre postraite)
        eq_transport.modifier_vpoint_pour_imposer_vit(rhoU,vpoint0,vpoint,tab_rho_face_np1,source_ibc,t,dt_);
      }
  secmem = tab_W;
  operator_negate(secmem);
  eqn.operateur_divergence().ajouter(rhoU,secmem);
  secmem /= dt_; //!< (-tabW + Div(rhoU))/dt
  eqn.operateur_divergence().ajouter(vpoint, secmem);
  secmem *= -1;
  secmem.echange_espace_virtuel();
  Debog::verifier("Navier_Stokes_Fluide_Dilatable_base::derivee_en_temps_inco, secmem : ", secmem);
// On ne fait appel qu une seule fois a assembler dans preparer calcul (au lieu de assembler_QC)
// Correction du second membre d'apres les conditions aux limites :
  eqn.assembleur_pression().modifier_secmem(secmem);
  eqn.solveur_pression().resoudre_systeme(eqn.matrice_pression().valeur(),secmem,inc_pre);
} /* END  solve_pressure_increment */
References Operateur_Div::ajouter(), Navier_Stokes_std::assembleur_pression(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Probleme_base::equation(), TRUSTVect< _TYPE_ >::line_size(), Navier_Stokes_std::matrice_pression(), Assembleur::modifier_secmem(), Transport_Interfaces_base::modifier_vpoint_pour_imposer_vit(), Probleme_base::nombre_d_equations(), Navier_Stokes_std::operateur_divergence(), operator_negate(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), ref_cast, SolveurSys::resoudre_systeme(), Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Equation_base::schema_temps(), Navier_Stokes_std::solveur_pression(), sub_type, tab_W, Schema_Temps_base::temps_courant(), Deriv_Matrice_Base::valeur(), Champ_Inc::valeurs(), Debog::verifier(), and Navier_Stokes_std::vitesse().
Referenced by derivee_en_temps_inco_impl().
update_vpoint_on_boundaries()
void Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries (const Navier_Stokes_std & eqn, const Fluide_Dilatable_base & fluide_dil, DoubleTab & vpoint) private
< VDF //
< VEF //
Definition at line 439 of file Navier_Stokes_Fluide_Dilatable_Proto.cpp.
{
// on ajoute durho/dt au bord Dirichlet car les solveur masse a mis a zero
// NOTE : en incompressible le terme est rajoute par modifier_secmem
  const double dt_ = eqn.schema_temps().pas_de_temps();
  const DoubleTab& tab_rho_face_n =fluide_dil.rho_face_n(), tab_rho_face_np1=fluide_dil.rho_face_np1();
  const DoubleTab& vit = eqn.vitesse().valeurs();
  const Conds_lim& lescl=eqn.zone_Cl_dis().les_conditions_limites();
  const IntTab& face_voisins = eqn.zone_dis().valeur().face_voisins();
  const int nbcondlim = lescl.size(), taille = vpoint.line_size();
  if (taille==1)
    if (orientation_VDF_.size() == 0)
      orientation_VDF_.ref(ref_cast(Zone_VF,eqn.zone_dis().valeur()).orientation());
  for (int icl=0; icl<nbcondlim; icl++)
    {
      const Cond_lim_base& la_cl_base = lescl[icl].valeur();
      if (sub_type(Dirichlet,la_cl_base))
        {
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
          const Dirichlet& diri=ref_cast(Dirichlet,la_cl_base);
          const int ndeb = la_front_dis.num_premiere_face(), nfin = ndeb + la_front_dis.nb_faces();
          if (taille==1) //!< VDF //
            {
              for (int num_face=ndeb; num_face<nfin; num_face++)
                {
                  int n0 = face_voisins(num_face, 0);
                  if (n0 == -1) n0 = face_voisins(num_face, 1);
// GF en cas de diffsion implicite vpoint!=0 on ignrore l'ancienne valeur
                  vpoint(num_face)=(diri.val_imp(num_face-ndeb,orientation_VDF_(num_face))*tab_rho_face_np1(num_face)-
                                    vit(num_face)*tab_rho_face_n(num_face))/dt_;
                }
            }
          else //!< VEF //
            {
              for (int num_face=ndeb; num_face<nfin; num_face++)
                for (int jj=0; jj<Objet_U::dimension; jj++)
                  {
// GF en cas de diffsion implicite vpoint!=0 on ignrore l'ancienne valeur
                    vpoint(num_face,jj)=(tab_rho_face_np1(num_face)*diri.val_imp(num_face-ndeb,jj)
                                         -tab_rho_face_n(num_face)*vit(num_face,jj))/dt_;
                  }
            }
        }
    }
} /* END update_vpoint_on_boundaries */
References Objet_U::dimension, Zone_dis_base::face_voisins(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), orientation_VDF_, Schema_Temps_base::pas_de_temps(), TRUSTVect< _TYPE_ >::ref(), ref_cast, Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), vect_impl::size(), sub_type, Dirichlet::val_imp(), Deriv_Zone_dis_base::valeur(), Champ_Inc::valeurs(), Navier_Stokes_std::vitesse(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by prepare_and_solve_u_star().
Member Data Documentation
cumulative_
double Navier_Stokes_Fluide_Dilatable_Proto::cumulative_ mutable private
Definition at line 53 of file Navier_Stokes_Fluide_Dilatable_Proto.h.
Referenced by impr_impl().
orientation_VDF_
IntVect Navier_Stokes_Fluide_Dilatable_Proto::orientation_VDF_ protected
Definition at line 49 of file Navier_Stokes_Fluide_Dilatable_Proto.h.
Referenced by update_vpoint_on_boundaries().
rho_la_vitesse_
Champ_Inc Navier_Stokes_Fluide_Dilatable_Proto::rho_la_vitesse_ protected
Definition at line 48 of file Navier_Stokes_Fluide_Dilatable_Proto.h.
Referenced by Navier_Stokes_Fluide_Dilatable_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), and Navier_Stokes_Fluide_Dilatable_base::rho_la_vitesse().
tab_W
DoubleTab Navier_Stokes_Fluide_Dilatable_Proto::tab_W protected
RHS of div(rho.U)
Definition at line 50 of file Navier_Stokes_Fluide_Dilatable_Proto.h.
Referenced by derivee_en_temps_inco_impl(), impr_impl(), prepare_and_solve_u_star(), and solve_pressure_increment().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Equations/Navier_Stokes_Fluide_Dilatable_Proto.h
src/ThHyd/Dilatable/Common/Equations/Navier_Stokes_Fluide_Dilatable_Proto.cpp