TRUST: Champ_Fonc_Tabule_P0_CoviMAC Class Reference
Champ_Fonc_Tabule_P0_CoviMAC Class Reference
#include <Champ_Fonc_Tabule_P0_CoviMAC.h>
Public Member Functions
Champ_Fonc_Tabule_P0_CoviMAC ()
~Champ_Fonc_Tabule_P0_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_param (const Vect_Ref_Champ_base &, const Table &)
void mettre_a_jour (double)
Mise a jour en temps du champ.
int initialiser (const double &temps)
NE FAIT RIEN
A surcharger dans les classes derivees
Provoque l'initialisation du champ si necessaire.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Champ_Fonc_Tabule_P0_CoviMAC & self_cast (Objet_U &)
static const
Champ_Fonc_Tabule_P0_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Vect_Ref_Champ_base les_ch_param
Ref_Table la_table
Detailed Description
Definition at line 36 of file Champ_Fonc_Tabule_P0_CoviMAC.h.
Constructor & Destructor Documentation
Champ_Fonc_Tabule_P0_CoviMAC::Champ_Fonc_Tabule_P0_CoviMAC ()
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
Champ_Fonc_Tabule_P0_CoviMAC::~Champ_Fonc_Tabule_P0_CoviMAC ()
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
Member Function Documentation
void Champ_Fonc_Tabule_P0_CoviMAC::associer_param (const Vect_Ref_Champ_base & les_champs, const Table & une_table)
Definition at line 45 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
References la_table, and les_ch_param.
Referenced by CoviMAC_discretisation::modifier_champ_tabule().
{
  les_ch_param = les_champs;
// for (int i = 0; i < les_champs.size(); i++)
// {
// REF(Champ_base) champ;
// champ = les_champs[i];
// les_ch_param.add(champ);
// }
  la_table = une_table;
}
Objet_U * Champ_Fonc_Tabule_P0_CoviMAC::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
int Champ_Fonc_Tabule_P0_CoviMAC::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
const Type_info * Champ_Fonc_Tabule_P0_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
const Type_info * Champ_Fonc_Tabule_P0_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
int Champ_Fonc_Tabule_P0_CoviMAC::initialiser (const double & temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Provoque l'initialisation du champ si necessaire.
Reimplemented from Champ_Don_base.
Definition at line 99 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
References mettre_a_jour(), and Champ_base::temps().
{
  Champ_Fonc_Tabule_P0_CoviMAC::mettre_a_jour(temps());
  return 1;
}
void Champ_Fonc_Tabule_P0_CoviMAC::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 59 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
References Process::abort(), DoubleTab::dimension(), Table::isfonction(), la_table, Champ_Fonc_P0_CoviMAC::la_zone_CoviMAC, les_ch_param, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), vect_impl::size(), Table::val(), valeur(), Ref_Table::valeur(), Ref_Zone_CoviMAC::valeur(), Table::valeurs(), Champ_Don_base::valeurs(), VECT, and Zone_VF::xp().
Referenced by initialiser().
{
  const Zone_CoviMAC& zone_CoviMAC = la_zone_CoviMAC.valeur();
  const Table& table = la_table.valeur();
  DoubleTab& mes_valeurs = valeurs();
  const int nb_elem = zone_CoviMAC.nb_elem(), nb_elem_tot = zone_CoviMAC.nb_elem_tot(), nb_param = les_ch_param.size();
  VECT(DoubleTab) val_params_aux_elems;
  for (int i = 0; i < nb_param; i++)
    {
      DoubleTab vp(nb_elem_tot, mes_valeurs.dimension(1));
      val_params_aux_elems.add(vp);
    }
  const DoubleTab& centres_de_gravites = zone_CoviMAC.xp();
  IntVect les_polys(nb_elem_tot);
  for(int elem = 0; elem < nb_elem_tot; elem++) les_polys(elem) = elem;
// Estimate the field parameter on cells:
  for (int i = 0; i < nb_param; i++)
    les_ch_param[i].valeur().valeur_aux_elems(centres_de_gravites, les_polys, val_params_aux_elems[i]);
// Compute the field according to the parameter field
  if (table.isfonction() != 2)
    {
      const int nbcomp = mes_valeurs.dimension(1);
      for (int num_elem = 0; num_elem < nb_elem; num_elem++)
        for (int ncomp = 0; ncomp < nbcomp; ncomp++)
          {
            std::vector<double> vals;
            for (int n = 0; n < nb_param; n++) vals.push_back(val_params_aux_elems[n](num_elem, ncomp));
            mes_valeurs(num_elem, ncomp) = table.val(vals, ncomp);
          }
    }
  else
    {
      abort();
      table.valeurs(val_params_aux_elems[0], centres_de_gravites, t, mes_valeurs);
    }
  Champ_Fonc_base::mettre_a_jour(t);
}
Sortie & Champ_Fonc_Tabule_P0_CoviMAC::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 33 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Fonc_Tabule_P0_CoviMAC::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 40 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
{
  return s ;
}
Champ_Fonc_Tabule_P0_CoviMAC & Champ_Fonc_Tabule_P0_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
const Champ_Fonc_Tabule_P0_CoviMAC & Champ_Fonc_Tabule_P0_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
unsigned Champ_Fonc_Tabule_P0_CoviMAC::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 28 of file Champ_Fonc_Tabule_P0_CoviMAC.cpp.
Member Data Documentation
const Type_info Champ_Fonc_Tabule_P0_CoviMAC::info_obj [static]
Reimplemented from Champ_Fonc_P0_CoviMAC.
Definition at line 38 of file Champ_Fonc_Tabule_P0_CoviMAC.h.
Ref_Table Champ_Fonc_Tabule_P0_CoviMAC::la_table [protected]
Definition at line 49 of file Champ_Fonc_Tabule_P0_CoviMAC.h.
Referenced by associer_param(), and mettre_a_jour().
Vect_Ref_Champ_base Champ_Fonc_Tabule_P0_CoviMAC::les_ch_param [protected]
Definition at line 48 of file Champ_Fonc_Tabule_P0_CoviMAC.h.
Referenced by associer_param(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/CoviMAC/Champs/Champ_Fonc_Tabule_P0_CoviMAC.h
src/CoviMAC/Champs/Champ_Fonc_Tabule_P0_CoviMAC.cpp