TRUST: Raccord_local_homogene Class Reference
Raccord_local_homogene Class Reference
Classe Raccord_local_homogene
Cette classe represente un Raccord_local ou les maillages de part et
d'autres coincident.
#include <Raccord_base.h>
Public Member Functions
Raccord_local_homogene ()
~Raccord_local_homogene ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void trace_elem_distant (const DoubleTab &, DoubleTab &) const override
void trace_face_distant (const DoubleTab &, DoubleTab &) const override
void trace_face_distant (const DoubleVect &, DoubleVect &) const override
Public Member Functions inherited from Raccord_local
Raccord_local ()
~Raccord_local () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Raccord_base
Raccord_base ()
~Raccord_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Frontiere
Frontiere ()
~Frontiere () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe la frontiere a la zone dont elle depend.
const Zone & zone () const
Renvoie la Zone associee a la frontiere.
(version const)
Zone & zone ()
Renvoie la Zone associee a la frontiere.
void nommer (const Nom &) override
Donne un nom a la frontiere.
void ajouter_faces (const IntTab &)
Ajoute une (ou plusieurs) face(s) a la frontiere,
la (les) face(s) est (sont) specifiee(s) par un tableau
contenant les numeros des sommets.
void typer_faces (const Motcle &)
Type les faces de la frontiere.
void typer_faces (const Type_Face &)
Type les faces de la frontiere.
const Faces & faces () const
Renvoie les faces de la frontiere<br>(version const)
Faces & faces ()
Renvoie les faces de la frontiere.
IntTab & les_sommets_des_faces ()
Renvoie les sommets des faces de la frontiere.
const IntTab & les_sommets_des_faces () const
Renvoie les sommets des faces de la frontiere.
int nb_faces () const
Renvoie le nombre de faces de la frontiere.
void dimensionner (int)
Dimensionne la frontiere, i.e. fixe
son nombre de faces.
const Nom & le_nom () const override
Renvoie le nom de la frontiere.
void renum (const IntVect &)
Renumerote les noeuds (sommets) des faces.
Le noeud de numero k devient le noeud de numero Les_Nums[k].
void add (const Frontiere &)
Ajoute les sommets (et faces) de la frontiere
passee en parametre a l'objet (Frontiere).
int nb_faces_virt () const
int face_virt (int i) const
int num_premiere_face () const
void fixer_num_premiere_face (int)
const ArrOfInt & get_faces_virt () const
ArrOfInt & get_faces_virt ()
const double & get_aire () const
void set_aire (double &aire)
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par face de cette frontiere
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void trace_elem_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux elements y.
virtual void trace_face_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_face_local (const DoubleVect &, DoubleVect &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_elem_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_som_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleVect &, DoubleVect &) const
virtual void trace_som_local (const DoubleTab &y, DoubleTab &x) const
Renvoie la trace sur la frontiere du tableau aux noeuds y.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Raccord_local_homogene & self_cast (Objet_U &)
static const Raccord_local_homogene & self_cast (const Objet_U &)
Static Public Member Functions inherited from Raccord_local
static const Type_info * info ()
static Raccord_local & self_cast (Objet_U &)
static const Raccord_local & self_cast (const Objet_U &)
Static Public Member Functions inherited from Raccord_base
static const Type_info * info ()
static Raccord_base & self_cast (Objet_U &)
static const Raccord_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Frontiere
static const Type_info * info ()
static Frontiere & self_cast (Objet_U &)
static const Frontiere & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Raccord_local
static const Type_info info_obj
Static Public Attributes inherited from Raccord_base
static const Type_info info_obj
Static Public Attributes inherited from Frontiere
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Raccord_local::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Raccord_local::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a: Raccord_base::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Raccord_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a: Frontiere::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Frontiere::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecrit la frontiere sur un flot de sortie.
On ecrit:
le nom de la frontiere
les faces.
Entree & readOn (Entree &) override
Lit les specification d'une frontiere
a partir d'un flot d'entree.
On lit:
le nom
les faces.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Classe Raccord_local_homogene
Cette classe represente un Raccord_local ou les maillages de part et
d'autres coincident.
Definition at line 92 of file Raccord_base.h.
Constructor & Destructor Documentation
Raccord_local_homogene()
Raccord_local_homogene::Raccord_local_homogene ()
Definition at line 21 of file Raccord_base.cpp.
~Raccord_local_homogene()
Raccord_local_homogene::~Raccord_local_homogene ()
Definition at line 21 of file Raccord_base.cpp.
Member Function Documentation
cree_instance()
Objet_U * Raccord_local_homogene::cree_instance () static
Definition at line 21 of file Raccord_base.cpp.
duplique()
int Raccord_local_homogene::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Raccord_base.cpp.
get_info()
const Type_info * Raccord_local_homogene::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Raccord_local.
Definition at line 21 of file Raccord_base.cpp.
info()
const Type_info * Raccord_local_homogene::info () static
Definition at line 21 of file Raccord_base.cpp.
printOn()
Sortie & Raccord_local_homogene::printOn (Sortie & s) const override protected virtual
Simple appel a: Raccord_local::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Raccord_local.
Definition at line 161 of file Raccord_base.cpp.
{
  return Raccord_local::printOn(s) ;
}
References Raccord_local::printOn().
readOn()
Entree & Raccord_local_homogene::readOn (Entree & s) override protected virtual
Simple appel a: Raccord_local::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Raccord_local.
Definition at line 180 of file Raccord_base.cpp.
{
  return Raccord_local::readOn(s) ;
}
References Raccord_local::readOn().
self_cast() [1/2]
const Raccord_local_homogene & Raccord_local_homogene::self_cast (const Objet_U & r) static
Definition at line 21 of file Raccord_base.cpp.
self_cast() [2/2]
Raccord_local_homogene & Raccord_local_homogene::self_cast (Objet_U & r) static
Definition at line 21 of file Raccord_base.cpp.
taille_memoire()
unsigned Raccord_local_homogene::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Raccord_base.cpp.
trace_elem_distant()
void Raccord_local_homogene::trace_elem_distant (const DoubleTab & x, DoubleTab & y) const override virtual
Reimplemented from Frontiere.
Definition at line 184 of file Raccord_base.cpp.
{
// en suppposant les numerotations des faces identiques sur le raccord des deux cotes
  return trace_elem_local(x,y);
}
References Frontiere::trace_elem_local().
trace_face_distant() [1/2]
void Raccord_local_homogene::trace_face_distant (const DoubleTab & x, DoubleTab & y) const override virtual
Reimplemented from Frontiere.
Definition at line 189 of file Raccord_base.cpp.
{
  return trace_face_local(x,y);
}
References Frontiere::trace_face_local().
trace_face_distant() [2/2]
void Raccord_local_homogene::trace_face_distant (const DoubleVect & x, DoubleVect & y) const override virtual
Reimplemented from Frontiere.
Definition at line 193 of file Raccord_base.cpp.
{
  return trace_face_local(x,y);
}
References Frontiere::trace_face_local().
Member Data Documentation
info_obj
const Type_info Raccord_local_homogene::info_obj static
Definition at line 94 of file Raccord_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raccord_base.h
src/Kernel/Geometrie/Raccord_base.cpp