TRUST: Int_ptr_trav Class Reference
Int_ptr_trav Class Reference
Une zone de travail de la Memoire TRUST composee d'elements de type int.
#include <Memoire_ptr.h>
Public Member Functions
Int_ptr_trav ()
Constructeur
La zone de travail cree est vide.
Int_ptr_trav * add (int n)
Ajout d'elements dans la zone de travail.
int unlock ()
Deverrouille la zone de travail.
~Int_ptr_trav ()
Destructeur
Supprime les donnees attachees a la zone de travail.
int * i_ptr_ () const
Retourne un pointeur sur les donnees de la zone de travail.
Private Attributes
int sz
int * data
int lock_
Int_ptr_trav * next
Detailed Description
Une zone de travail de la Memoire TRUST composee d'elements de type int.
Definition at line 82 of file Memoire_ptr.h.
Constructor & Destructor Documentation
Int_ptr_trav::Int_ptr_trav () [inline]
Constructeur
La zone de travail cree est vide.
Definition at line 255 of file Memoire_ptr.h.
Referenced by add().
                                  : sz(-1), data(0),
  lock_(0), next(0)
{
}
Int_ptr_trav::~Int_ptr_trav ()
Destructeur
Supprime les donnees attachees a la zone de travail.
Definition at line 214 of file Memoire_ptr.cpp.
References data, next, and sz.
{
  if(sz!=-1)
    {
      if (next) delete next;
      delete[] data;
    }
}
Member Function Documentation
Int_ptr_trav * Int_ptr_trav::add (int n)
Ajout d'elements dans la zone de travail.
Returns:
Int_ptr_trav*
Signification: pointeur sur le zone de travail contenant les elements crees
Contraintes:
Definition at line 150 of file Memoire_ptr.cpp.
References Cerr, data, Process::exit(), finl, Int_ptr_trav(), lock_, next, and sz.
Referenced by Memoire::add_trav_int().
{
  if(sz==-1)
    {
      sz=n;
      data=new int[sz];
      if(!data)
        {
          Cerr << "Not enough memory " << finl;
          Process::exit();
        }
      lock_=1;
      next=0;
      return this;
    }
  if ( (!lock_) && (sz==n))
    {
      lock_=1;
      return this;
    }
  Int_ptr_trav* curseur=this;
  while(curseur->next)
    {
      curseur=curseur->next;
      if ( (!curseur->lock_) && (curseur->sz==n))
        {
          curseur->lock_=1;
          return curseur;
        }
    }
  curseur->next= new Int_ptr_trav();
  if(!curseur->next)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  curseur=curseur->next;
  curseur->sz=n;
  curseur->data=new int[n];
  if(!data)
    {
      Cerr << "Not enough memory " << finl;
      Process::exit();
    }
  curseur->lock_=1;
  curseur->next=0;
  return curseur;
}
int * Int_ptr_trav::i_ptr_ () const [inline]
Retourne un pointeur sur les donnees de la zone de travail.
Returns:
int*
Signification: pointeur sur le tableau des donnees
Contraintes:
Definition at line 293 of file Memoire_ptr.h.
References data.
Referenced by VIntdata::VIntdata().
{
  return data;
}
int Int_ptr_trav::unlock () [inline]
Deverrouille la zone de travail.
Definition at line 274 of file Memoire_ptr.h.
References lock_.
Referenced by VIntdata::~VIntdata().
{
  return lock_=0;
}
Member Data Documentation
int* Int_ptr_trav::data [private]
Definition at line 92 of file Memoire_ptr.h.
Referenced by add(), i_ptr_(), and ~Int_ptr_trav().
int Int_ptr_trav::lock_ [private]
Definition at line 93 of file Memoire_ptr.h.
Referenced by add(), and unlock().
Int_ptr_trav* Int_ptr_trav::next [private]
Definition at line 94 of file Memoire_ptr.h.
Referenced by add(), and ~Int_ptr_trav().
int Int_ptr_trav::sz [private]
Definition at line 91 of file Memoire_ptr.h.
Referenced by add(), and ~Int_ptr_trav().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Memoire_ptr.h
src/Kernel/Utilitaires/Memoire_ptr.cpp