TRUST: Ref_Fluide_Dilatable_base Class Reference
Ref_Fluide_Dilatable_base Class Reference
#include <Ref_Fluide_Dilatable_base.h>
Public Member Functions
~Ref_Fluide_Dilatable_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Fluide_Dilatable_base ()
Ref_Fluide_Dilatable_base (const Fluide_Dilatable_base &)
Ref_Fluide_Dilatable_base (const Ref_Fluide_Dilatable_base &)
const Fluide_Dilatable_base & valeur () const
Fluide_Dilatable_base & valeur ()
const Fluide_Dilatable_base * operator-> () const
Fluide_Dilatable_base * operator-> ()
const Ref_Fluide_Dilatable_base & operator= (const Fluide_Dilatable_base &)
const Ref_Fluide_Dilatable_base & operator= (const Ref_Fluide_Dilatable_base &)
operator const Fluide_Dilatable_base & () const
operator Fluide_Dilatable_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Fluide_Dilatable_base & self_cast (Objet_U &)
static const
Ref_Fluide_Dilatable_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Fluide_Dilatable_base * pointeur_
Detailed Description
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
Constructor & Destructor Documentation
Ref_Fluide_Dilatable_base::~Ref_Fluide_Dilatable_base ()
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Ref_Fluide_Dilatable_base::Ref_Fluide_Dilatable_base ()
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Ref_Fluide_Dilatable_base::Ref_Fluide_Dilatable_base (const Fluide_Dilatable_base & t)
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Ref_Fluide_Dilatable_base::Ref_Fluide_Dilatable_base (const Ref_Fluide_Dilatable_base & t)
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Member Function Documentation
Objet_U * Ref_Fluide_Dilatable_base::cree_instance () [static]
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
int Ref_Fluide_Dilatable_base::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Type_info * Ref_Fluide_Dilatable_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Type_info & Ref_Fluide_Dilatable_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Type_info * Ref_Fluide_Dilatable_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Ref_Fluide_Dilatable_base::operator const Fluide_Dilatable_base & () const
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Ref_Fluide_Dilatable_base::operator Fluide_Dilatable_base & ()
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Fluide_Dilatable_base * Ref_Fluide_Dilatable_base::operator-> () const [inline]
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
Fluide_Dilatable_base * Ref_Fluide_Dilatable_base::operator-> () [inline]
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
const Ref_Fluide_Dilatable_base & Ref_Fluide_Dilatable_base::operator= (const Ref_Fluide_Dilatable_base & t)
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Ref_Fluide_Dilatable_base & Ref_Fluide_Dilatable_base::operator= (const Fluide_Dilatable_base & t)
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Sortie & Ref_Fluide_Dilatable_base::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Entree & Ref_Fluide_Dilatable_base::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Ref_Fluide_Dilatable_base & Ref_Fluide_Dilatable_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
Ref_Fluide_Dilatable_base & Ref_Fluide_Dilatable_base::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
void Ref_Fluide_Dilatable_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
unsigned Ref_Fluide_Dilatable_base::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Fluide_Dilatable_base.cpp.
const Fluide_Dilatable_base & Ref_Fluide_Dilatable_base::valeur () const [inline]
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
Referenced by Source_WC_Gravite_VEF::ajouter(), Source_WC_Gravite_VDF::ajouter(), Source_WC_Chaleur::ajouter(), Source_QC_Gravite_VEF::ajouter(), Source_QC_Gravite_VDF::ajouter(), Source_QC_Chaleur::ajouter(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_mu_wilke(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Convection_Diffusion_Espece_Binaire_QC::completer(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), EOS_Tools_VEF::le_fluide(), EOS_Tools_VDF::le_fluide(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::sauvegarder(), Convection_Diffusion_Chaleur_WC::sauvegarder(), Pb_QC_base::solve_pressure_thermo(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
Fluide_Dilatable_base & Ref_Fluide_Dilatable_base::valeur () [inline]
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
Member Data Documentation
const Type_info Ref_Fluide_Dilatable_base::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
Fluide_Dilatable_base* Ref_Fluide_Dilatable_base::pointeur_ [private]
Definition at line 28 of file Ref_Fluide_Dilatable_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Milieu/Ref_Fluide_Dilatable_base.h
src/ThHyd/Dilatable/Common/Milieu/Ref_Fluide_Dilatable_base.cpp