TRUST: Tetra_VEF Class Reference
Tetra_VEF Class Reference
#include <Tetra_VEF.h>
Public Member Functions
~Tetra_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Tetra_VEF ()
renvoie pour la facette fa7 :
pour j=0,j=1 : les numeros locaux des 2 faces qui entourent fa7
pour j=2,j=3 : les numeros locaux des sommets du tetraedre qui
appartiennent a fa7
int nb_facette () const override
void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const override
remplit le tableau face_normales dans la Zone_VEF
void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const override
remplit le tableau normales_facettes_Cl dans la Zone_Cl_VEF
pour la facette fa7 de l'element num_elem
void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const override
void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const override
void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const override
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const override
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const override
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const override
Public Member Functions inherited from Elem_VEF_base
Elem_VEF_base ()
~Elem_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int nb_facette () const =0
const IntTab & KEL () const
virtual void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const =0
virtual void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const =0
virtual void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const =0
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Tetra_VEF & self_cast (Objet_U &)
static const Tetra_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_VEF_base
static const Type_info * info ()
static Elem_VEF_base & self_cast (Objet_U &)
static const Elem_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_VEF_base
IntTab KEL_
Detailed Description
Definition at line 22 of file Tetra_VEF.h.
Constructor & Destructor Documentation
~Tetra_VEF()
Tetra_VEF::~Tetra_VEF ()
Definition at line 21 of file Tetra_VEF.cpp.
Tetra_VEF()
Tetra_VEF::Tetra_VEF ()
renvoie pour la facette fa7 :
pour j=0,j=1 : les numeros locaux des 2 faces qui entourent fa7
pour j=2,j=3 : les numeros locaux des sommets du tetraedre qui
appartiennent a fa7
Definition at line 40 of file Tetra_VEF.cpp.
{
  int tmp[4][6]=
  {
    {0, 0, 0, 1, 1, 2},
    {1, 2, 3, 2, 3, 3},
    {2, 1, 1, 3, 2, 1},
    {3, 3, 2, 0, 0, 0}
  };
  KEL_.resize(4,6);
  for (int i=0; i<4; i++)
    for (int j=0; j<6; j++)
      KEL_(i,j)=tmp[i][j];
}
References Elem_VEF_base::KEL_, and TRUSTTab< _TYPE_ >::resize().
Member Function Documentation
calcul_vc()
void Tetra_VEF::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl, const DoubleVect & porosite_face) const override virtual
< le tetraedre n'a pas de Face de Dirichlet
< le tetraedre a une Face de Dirichlet : KEL3
< le tetraedre a une Face de Dirichlet : KEL2
< le tetraedre a une Face de Dirichlet : KEL1
< le tetraedre a une Face de Dirichlet : KEL0
< le tetraedre a deux faces de Dirichlet : KEL3 et KEL2
< le tetraedre a deux faces de Dirichlet : KEL3 et KEL1
< le tetraedre a deux faces de Dirichlet : KEL1 et KEL2
< le tetraedre a deux faces de Dirichlet : KEL0 et KEL3
< le tetraedre a deux faces de Dirichlet : KEL0 et KEL2
< le tetraedre a deux faces de Dirichlet : KEL0 et KEL1
< le tetraedre a trois faces de Dirichlet : KEL1, KEL2 et KEL3
< le tetraedre a trois faces de Dirichlet : KEL0,KEL2 et KEL3
< le tetraedre a trois faces de Dirichlet : KEL0, KEL1 et KEL3
< le tetraedre a trois faces de Dirichlet : KEL0, KEL1 et KEL2
Implements Elem_VEF_base.
Definition at line 636 of file Tetra_VEF.cpp.
{
  int comp;
  switch(type_cl)
    {
    case 0: //!< le tetraedre n'a pas de Face de Dirichlet
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.25*vs[comp];
        break;
      }
    case 1: //!< le tetraedre a une Face de Dirichlet : KEL3
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vitesse(Face[3],comp)*porosite_face[Face[3]];
        break;
      }
    case 2: //!< le tetraedre a une Face de Dirichlet : KEL2
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vitesse(Face[2],comp)*porosite_face[Face[2]];
        break;
      }
    case 4: //!< le tetraedre a une Face de Dirichlet : KEL1
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vitesse(Face[1],comp)*porosite_face[Face[1]];
        break;
      }
    case 8: //!< le tetraedre a une Face de Dirichlet : KEL0
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vitesse(Face[0],comp)*porosite_face[Face[0]];
        break;
      }
    case 3: //!< le tetraedre a deux faces de Dirichlet : KEL3 et KEL2
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.5* (vsom(0,comp) + vsom(1,comp));
        break;
      }
    case 5: //!< le tetraedre a deux faces de Dirichlet : KEL3 et KEL1
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.5* (vsom(0,comp) + vsom(2,comp));
        break;
      }
    case 6: //!< le tetraedre a deux faces de Dirichlet : KEL1 et KEL2
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.5* (vsom(0,comp) + vsom(3,comp));
        break;
      }
    case 9: //!< le tetraedre a deux faces de Dirichlet : KEL0 et KEL3
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.5* (vsom(1,comp) + vsom(2,comp));
        break;
      }
    case 10: //!< le tetraedre a deux faces de Dirichlet : KEL0 et KEL2
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.5* (vsom(1,comp) + vsom(3,comp));
        break;
      }
    case 12: //!< le tetraedre a deux faces de Dirichlet : KEL0 et KEL1
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = 0.5*(vsom(2,comp) + vsom(3,comp));
        break;
      }
    case 7: //!< le tetraedre a trois faces de Dirichlet : KEL1, KEL2 et KEL3
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vsom(0,comp);
        break;
      }
    case 11: //!< le tetraedre a trois faces de Dirichlet : KEL0,KEL2 et KEL3
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vsom(1,comp);
        break;
      }
    case 13: //!< le tetraedre a trois faces de Dirichlet : KEL0, KEL1 et KEL3
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vsom(2,comp);
        break;
      }
    case 14: //!< le tetraedre a trois faces de Dirichlet : KEL0, KEL1 et KEL2
      {
        for (comp=0; comp<3; comp++)
          vc[comp] = vsom(3,comp);
        break;
      }
    } //!< fin du switch
}
calcul_xg()
void Tetra_VEF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & n2, int & n3) const override virtual
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
< le tetraedre n'a pas de Face de Dirichlet. Il a 6 Facettes
< le tetraedre a une Face de Dirichlet. Le 'centre' du tetraedre est au milieu de la Face 3 qui a pour sommets 0, 1, 2 Il a 3 Facettes reelles : 0 aux noeuds 2 3 xg 1 aux noeuds 1 3 xg 3 aux noeuds 3 0 xg les 3 autres Facettes sont sur la Face 3
< le tetraedre a une Face de Dirichlet. Le 'centre' du tetraedre est au milieu de la Face 2 qui a pour sommets 0, 1, 3 Il a 3 Facettes reelles : 0 aux noeuds 2 3 xg 2 aux noeuds 1 2 xg 4 aux noeuds 2 0 xg
< le tetraedre a une Face de Dirichlet. Le 'centre' du tetraedre est au milieu de la Face 1 qui a pour sommets 0, 2, 3 Il a 3 Facettes reelles : 1 aux noeuds 1 3 xg 2 aux noeuds 1 2 xg 5 aux noeuds 1 0 xg
< le tetraedre a une Face de Dirichlet. Le 'centre' du tetraedre est au milieu de la Face 0 qui a pour sommets 1, 2, 3 Il a 3 Facettes reelles : 3 aux noeuds 3 0 xg 4 aux noeuds 2 0 xg 5 aux noeuds 1 0 xg
< le tetraedre a deux faces de Dirichlet 2 et 3. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 0, 1. Il a 1 Facette nulle: 5
< le tetraedre a deux faces de Dirichlet 3 et 1. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 0, 2. Il a 1 Facette nulle : 4
< le tetraedre a deux faces de Dirichlet 1 et 2. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 0, 3. Il a 1 Facette nulle: 3
< le tetraedre a deux faces de Dirichlet 0 et 3. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 1, 2 Il a 1 Facette nulle: 2
< le tetraedre a deux faces de Dirichlet 0 et 2. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 1, 3. Il a 1 Facette nulle: 1
< le tetraedre a deux faces de Dirichlet 0 et 1. Le 'centre' du tetraedre est au milieu de l'arete qui a pour sommets 2, 3. Il a 1 Facette nulle
< trois faces de Dirichlet : 1,2,3. Le centre est au sommet 0 il y 3 Facettes nulles: 3,4,5
< trois faces de Dirichlet : 0,2,3. Le centre est au sommet 1 il y 3 Facettes nulles: 1, 2, 5
< trois faces de Dirichlet : 0,1,3. Le centre est au sommet 2 il y 3 Facettes nulles: 0, 2, 4
< trois faces de Dirichlet : 0,1,2. Le centre est au sommet 3 il y 3 Facettes nulles: 0, 1, 3
Implements Elem_VEF_base.
Definition at line 755 of file Tetra_VEF.cpp.
{
  int dim=xg.size();
  switch(type_elem_Cl)
    {
    case 0:  //!< le tetraedre n'a pas de Face de Dirichlet. Il a 6 Facettes
      {
        for (int j=0; j<dim; j++)
          xg[j]=0.25*(x(0,j)+x(1,j)+x(2,j)+x(3,j));
        idirichlet=0;
        break;
      }
    case 1:  //!< le tetraedre a une Face de Dirichlet.  Le 'centre' du tetraedre est au milieu de la Face 3 qui a pour sommets 0, 1, 2 Il a 3 Facettes reelles : 0   aux noeuds 2 3 xg                           1   aux noeuds 1 3 xg                           3   aux noeuds 3 0 xg les 3 autres Facettes sont sur la Face 3
//
//
//
//
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(1,j)+x(2,j))/3.;
        idirichlet=1;
        break;
      }
    case 2:  //!< le tetraedre a une Face de Dirichlet.  Le 'centre' du tetraedre est au milieu de la Face 2 qui a pour sommets 0, 1, 3 Il a 3 Facettes reelles : 0   aux noeuds 2 3 xg                           2   aux noeuds 1 2 xg                           4   aux noeuds 2 0 xg
//
//
//
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(1,j)+x(3,j))/3.;
        idirichlet=1;
        break;
      }
    case 4:  //!< le tetraedre a une Face de Dirichlet.  Le 'centre' du tetraedre est au milieu de la Face 1 qui a pour sommets 0, 2, 3 Il a 3 Facettes reelles : 1   aux noeuds 1 3 xg                           2   aux noeuds 1 2 xg                           5   aux noeuds 1 0 xg
//
//
//
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]=(x(0,j)+x(2,j)+x(3,j))/3.;
        idirichlet=1;
        break;
      }
    case 8:  //!< le tetraedre a une Face de Dirichlet.  Le 'centre' du tetraedre est au milieu de la Face 0 qui a pour sommets 1, 2, 3 Il a 3 Facettes reelles : 3   aux noeuds 3 0 xg                           4   aux noeuds 2 0 xg                           5   aux noeuds 1 0 xg
//
//
//
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]=(x(1,j)+x(2,j)+x(3,j))/3.;
        idirichlet=1;
        break;
      }
    case 3:  //!< le tetraedre a deux faces de Dirichlet 2 et 3. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 0, 1. Il a 1 Facette nulle: 5
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= 0.5*(x(0,j)+x(1,j));
        n1=5;
        idirichlet=2;
        break;
      }
    case 5:  //!< le tetraedre a deux faces de Dirichlet 3 et 1. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 0, 2. Il a 1 Facette  nulle  : 4
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= 0.5*(x(0,j)+x(2,j));
        n1=4;
        idirichlet=2;
        break;
      }
    case 6:  //!< le tetraedre a deux faces de Dirichlet 1 et 2. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 0, 3. Il a 1 Facette  nulle: 3
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= 0.5*(x(0,j)+x(3,j));
        n1=3;
        idirichlet=2;
        break;
      }
    case 9:  //!< le tetraedre a deux faces de Dirichlet 0 et 3. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 1, 2 Il a 1 Facette  nulle: 2
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= 0.5*(x(1,j)+x(2,j));
        n1=2;
        idirichlet=2;
        break;
      }
    case 10:  //!< le tetraedre a deux faces de Dirichlet 0 et 2. Le 'centre' du tetraedre est au milieu de l'arete qui a pour extremites 1, 3. Il a 1 Facette  nulle: 1
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= 0.5*(x(1,j)+x(3,j));
        n1=1;
        idirichlet=2;
        break;
      }
    case 12:  //!< le tetraedre a deux faces de Dirichlet 0 et 1. Le 'centre' du tetraedre est au milieu de l'arete qui a pour sommets 2, 3. Il a 1 Facette  nulle
//
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= 0.5*(x(2,j)+x(3,j));
        n1=0;
        idirichlet=2;
        break;
      }
    case 7:  //!< trois faces de Dirichlet : 1,2,3. Le centre est au sommet 0 il y 3 Facettes nulles: 3,4,5
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= x(0,j);
        n1=3;
        n2=4;
        n3=5;
        idirichlet=3;
        break;
      }
    case 11:  //!< trois faces de Dirichlet : 0,2,3. Le centre est au sommet 1 il y 3 Facettes nulles: 1, 2, 5
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= x(1,j);
        n1=1;
        n2=2;
        n3=5;
        idirichlet=3;
        break;
      }
    case 13:  //!< trois faces de Dirichlet : 0,1,3. Le centre est au sommet 2 il y 3 Facettes nulles: 0, 2, 4
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= x(2,j);
        n1=0;
        n2=2;
        n3=4;
        idirichlet=3;
        break;
      }
    case 14:  //!< trois faces de Dirichlet : 0,1,2. Le centre est au sommet 3 il y 3 Facettes nulles: 0, 1, 3
//
      {
        for (int j=0; j<dim; j++)
          xg[j]= x(3,j);
        n1=0;
        n2=1;
        n3=3;
        idirichlet=3;
        break;
      }
    }
}
References TRUSTVect< _TYPE_ >::size().
cree_instance()
Objet_U * Tetra_VEF::cree_instance () static
Definition at line 21 of file Tetra_VEF.cpp.
creer_facette_normales()
void Tetra_VEF::creer_facette_normales (const Zone & zone_geom, DoubleTab & facette_normales, const IntVect & rang_elem_non_std) const override virtual
remplit le tableau face_normales dans la Zone_VEF
Implements Elem_VEF_base.
Definition at line 126 of file Tetra_VEF.cpp.
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  const IntTab& les_Polys = zone_geom.les_elems();
  int nb_elem = zone_geom.nb_elem();
  int i,fa7;
  int num_som[4];
  double x[4][3];
  double xg[3];
  double xj0[3];
  double u[3];
  double v[3];
  double psc;
  double pv[3];
// Original:
// facette_normales.resize(0,6,3);
// // valgrind with MPICH says a unitialised here so we initialize:
// // zone_geom.creer_tableau_elements(facette_normales, Array_base::NOCOPY_NOINIT);
// zone_geom.creer_tableau_elements(facette_normales);
// New similar as in Tri_VEF.cpp
  if (facette_normales.get_md_vector() != zone_geom.md_vector_elements())
    {
      facette_normales.reset();
      facette_normales.resize(0,6,3);
      zone_geom.creer_tableau_elements(facette_normales);
    }
  for(i=0; i<nb_elem; i++)
    {
      if (rang_elem_non_std(i)==-1)
        {
          num_som[0]=les_Polys(i,0);
          num_som[1]=les_Polys(i,1);
          num_som[2]=les_Polys(i,2);
          num_som[3]=les_Polys(i,3);
          x[0][0]=les_coords(num_som[0],0);
          x[0][1]=les_coords(num_som[0],1);
          x[0][2]=les_coords(num_som[0],2);
          x[1][0]=les_coords(num_som[1],0);
          x[1][1]=les_coords(num_som[1],1);
          x[1][2]=les_coords(num_som[1],2);
          x[2][0]=les_coords(num_som[2],0);
          x[2][1]=les_coords(num_som[2],1);
          x[2][2]=les_coords(num_som[2],2);
          x[3][0]=les_coords(num_som[3],0);
          x[3][1]=les_coords(num_som[3],1);
          x[3][2]=les_coords(num_som[3],2);
          xg[0]=0.25*(x[0][0]+x[1][0]+x[2][0]+x[3][0]);
          xg[1]=0.25*(x[0][1]+x[1][1]+x[2][1]+x[3][1]);
          xg[2]=0.25*(x[0][2]+x[1][2]+x[2][2]+x[3][2]);
          for (fa7=0; fa7<6; fa7++)
            {
// la fa7 a pour sommets KEL_(2,fa7), KEL_(3,fa7), "G"
              u[0]=x[KEL_(2,fa7)][0]-xg[0];
              u[1]=x[KEL_(2,fa7)][1]-xg[1];
              u[2]=x[KEL_(2,fa7)][2]-xg[2];
              v[0]=x[KEL_(3,fa7)][0]-xg[0];
              v[1]=x[KEL_(3,fa7)][1]-xg[1];
              v[2]=x[KEL_(3,fa7)][2]-xg[2];
              prodvect(u,v,pv);
// Orientation des normales :
              xj0[0]= x[KEL_(0,fa7)][0]-x[KEL_(1,fa7)][0];
              xj0[1]= x[KEL_(0,fa7)][1]-x[KEL_(1,fa7)][1];
              xj0[2]= x[KEL_(0,fa7)][2]-x[KEL_(1,fa7)][2];
              psc=xj0[0]*pv[0] + xj0[1]*pv[1] + xj0[2]*pv[2] ;
              if (psc < 0)
                {
                  facette_normales(i,fa7,0) = -pv[0]/2;
                  facette_normales(i,fa7,1) = -pv[1]/2;
                  facette_normales(i,fa7,2) = -pv[2]/2;
                }
              else
                {
                  facette_normales(i,fa7,0)  = pv[0]/2;
                  facette_normales(i,fa7,1)= pv[1]/2;
                  facette_normales(i,fa7,2)= pv[2]/2;
                }
            }
        }
    }
  facette_normales.echange_espace_virtuel();
}
References Domaine::coord_sommets(), Zone::creer_tableau_elements(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::get_md_vector(), Elem_VEF_base::KEL_, Zone::les_elems(), Zone::md_vector_elements(), Zone::nb_elem(), prodvect(), TRUSTTab< _TYPE_ >::reset(), and TRUSTTab< _TYPE_ >::resize().
creer_normales_facettes_Cl()
void Tetra_VEF::creer_normales_facettes_Cl (DoubleTab & normales_facettes_Cl, int fa7, int num_elem, const DoubleTab & x, const DoubleVect & xg, const Zone & zone_geom) const override virtual
remplit le tableau normales_facettes_Cl dans la Zone_Cl_VEF
pour la facette fa7 de l'element num_elem
Implements Elem_VEF_base.
Definition at line 218 of file Tetra_VEF.cpp.
{
// x contient les coord des sommets du tetraedre
// xg contient les coord du "centre" du tetraedre
  double u[3];
  double v[3];
  double xj0[3];
  double psc;
// Cerr << "fa7 " << fa7 << " et le num_elem " << num_elem << finl;
  int i0 = KEL_(0,fa7);
  int i1 = KEL_(1,fa7);
  int i2 = KEL_(2,fa7);
  int i3 = KEL_(3,fa7);
// Cerr << "i0 " << i0 << " i1 " << i1 << " i2 " << i2 << " i3 " << i3 << finl;
  u[0]=x(i2,0)-xg[0];
  u[1]=x(i2,1)-xg[1];
  u[2]=x(i2,2)-xg[2];
  v[0]=x(i3,0)-xg[0];
  v[1]=x(i3,1)-xg[1];
  v[2]=x(i3,2)-xg[2];
  double pv[3];
  prodvect(u,v,pv);
// Orientation des normales :
  xj0[0]= x(i0,0)-x(i1,0);
  xj0[1]= x(i0,1)-x(i1,1);
  xj0[2]= x(i0,2)-x(i1,2);
  psc=xj0[0]*pv[0] + xj0[1]*pv[1] + xj0[2]*pv[2] ;
  if (psc < 0)
    {
      normales_facettes_Cl(num_elem,fa7,0) = -pv[0]/2;
      normales_facettes_Cl(num_elem,fa7,1) = -pv[1]/2;
      normales_facettes_Cl(num_elem,fa7,2) = -pv[2]/2;
    }
  else
    {
      normales_facettes_Cl(num_elem,fa7,0) = pv[0]/2;
      normales_facettes_Cl(num_elem,fa7,1) = pv[1]/2;
      normales_facettes_Cl(num_elem,fa7,2) = pv[2]/2;
    }
}
References Elem_VEF_base::KEL_, and prodvect().
duplique()
int Tetra_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Tetra_VEF.cpp.
get_info()
const Type_info * Tetra_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 21 of file Tetra_VEF.cpp.
info()
const Type_info * Tetra_VEF::info () static
Definition at line 21 of file Tetra_VEF.cpp.
modif_normales_facettes_Cl()
void Tetra_VEF::modif_normales_facettes_Cl (DoubleTab & normales_facettes_Cl, int fa7, int num_elem, int idirichlet, int n1, int n2, int n3) const override virtual
< une facette nulle n1
Implements Elem_VEF_base.
Definition at line 976 of file Tetra_VEF.cpp.
{
  switch (idirichlet)
    {
    case 0:
      break;
    case 1:
      break;
    case 2:  //!< une facette nulle n1
      {
        fa7=n1;
        normales_facettes_Cl(num_elem,fa7,0) = 0;
        normales_facettes_Cl(num_elem,fa7,1) = 0;
        normales_facettes_Cl(num_elem,fa7,2) = 0;
        break;
      }
    case 3:
      {
        fa7=n1;
        normales_facettes_Cl(num_elem,fa7,0) = 0;
        normales_facettes_Cl(num_elem,fa7,1) = 0;
        normales_facettes_Cl(num_elem,fa7,2) = 0;
        fa7=n2;
        normales_facettes_Cl(num_elem,fa7,0) = 0;
        normales_facettes_Cl(num_elem,fa7,1) = 0;
        normales_facettes_Cl(num_elem,fa7,2) = 0;
        fa7=n3;
        normales_facettes_Cl(num_elem,fa7,0) = 0;
        normales_facettes_Cl(num_elem,fa7,1) = 0;
        normales_facettes_Cl(num_elem,fa7,2) = 0;
        break;
      }
    }  //fin du switch
}
modif_volumes_entrelaces()
void Tetra_VEF::modif_volumes_entrelaces (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & volumes_entrelaces_Cl, int type_cl) const override virtual
< une Face de Dirichlet : Face 3
< une Face de Dirichlet : Face 2
< une Face de Dirichlet : Face 1
< une Face de Dirichlet : Face 0
< deux faces de Dirichlet : faces 2,3
< deux faces de Dirichlet : faces 1,3
< le tetraedre a deux faces de Dirichlet : faces 1,2
< deux faces de Dirichlet :faces 0,3
< deux faces de Dirichlet :faces 0,2
< deux faces de Dirichlet :faces 0,1
< trois faces de Dirichlet : faces 1,2,3
< trois faces de Dirichlet : faces 0,2,3
< trois faces de Dirichlet : faces 0,1,3
< trois faces de Dirichlet : faces 0,1,2
Implements Elem_VEF_base.
Definition at line 266 of file Tetra_VEF.cpp.
{
  double vol_mod;
  const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
  const IntTab& elem_faces = la_zone_VEF.elem_faces();
  switch(type_cl)
    {
// pas de Face de Dirichlet : impossible
    case 0:
      {
        Cerr << "Tetra_VEF::modif_volumes_entrelaces() type 0 impossible!\n";
        break;
      }
    case 1: //!< une Face de Dirichlet : Face 3
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        volumes_entrelaces_Cl[elem_faces(elem,0)]  += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,1)]  += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,2)]  += vol_mod;
        break;
      }
    case 2: //!< une Face de Dirichlet : Face 2
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        volumes_entrelaces_Cl[elem_faces(elem,0)]  += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,1)]  += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,3)]  += vol_mod;
        break;
      }
    case 4: //!< une Face de Dirichlet : Face 1
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        volumes_entrelaces_Cl[elem_faces(elem,0)]  += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,2)]  += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,3)]  += vol_mod;
        break;
      }
    case 8: //!< une Face de Dirichlet : Face 0
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        volumes_entrelaces_Cl[elem_faces(elem,1)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,2)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,3)] += vol_mod;
        break;
      }
    case 3: //!< deux faces de Dirichlet : faces 2,3
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,2)]
                   + volumes_entrelaces[elem_faces(elem,3)])/2;
        volumes_entrelaces_Cl[elem_faces(elem,0)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,1)] += vol_mod;
        break;
      }
    case 5: //!< deux faces de Dirichlet : faces 1,3
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,3)])/2;
        volumes_entrelaces_Cl[elem_faces(elem,0)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,2)] += vol_mod;
        break;
      }
    case 6: //!< le tetraedre a deux faces de Dirichlet : faces 1,2
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,2)])/2;
        volumes_entrelaces_Cl[elem_faces(elem,0)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,3)] += vol_mod;
        break;
      }
    case 9: //!< deux faces de Dirichlet :faces 0,3
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,3)])/2;
        volumes_entrelaces_Cl[elem_faces(elem,1)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,2)] += vol_mod;
        break;
      }
    case 10: //!< deux faces de Dirichlet :faces 0,2
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,2)])/2;
        volumes_entrelaces_Cl[elem_faces(elem,1)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,3)] += vol_mod;
        break;
      }
    case 12: //!< deux faces de Dirichlet :faces 0,1
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,1)])/2;
        volumes_entrelaces_Cl[elem_faces(elem,2)] += vol_mod;
        volumes_entrelaces_Cl[elem_faces(elem,3)] += vol_mod;
        break;
      }
    case 7:  //!< trois faces de Dirichlet : faces 1,2,3
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,2)]
                   + volumes_entrelaces[elem_faces(elem,3)];
        volumes_entrelaces_Cl[elem_faces(elem,0)] += vol_mod;
        break;
      }
    case 11: //!< trois faces de Dirichlet : faces 0,2,3
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,2)]
                   + volumes_entrelaces[elem_faces(elem,3)];
        volumes_entrelaces_Cl[elem_faces(elem,1)] += vol_mod;
        break;
      }
    case 13: //!< trois faces de Dirichlet : faces 0,1,3
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,3)];
        volumes_entrelaces_Cl[elem_faces(elem,2)] += vol_mod;
        break;
      }
    case 14: //!< trois faces de Dirichlet : faces 0,1,2
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,2)];
        volumes_entrelaces_Cl[elem_faces(elem,3)] += vol_mod;
        break;
      }
    default :
      {
        Cerr << "\n  type inconnu Tetra_VEF::modif_volumes_entrelaces: " << type_cl;
        exit();
      }
    } //!< fin du switch
}
References Cerr, Zone_VF::elem_faces(), Process::exit(), and Zone_VF::volumes_entrelaces().
modif_volumes_entrelaces_faces_joints()
void Tetra_VEF::modif_volumes_entrelaces_faces_joints (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & volumes_entrelaces_Cl, int type_cl) const override virtual
< une Face de Dirichlet : Face 3
< une Face de Dirichlet : Face 2
< une Face de Dirichlet : Face 1
< une Face de Dirichlet : Face 0
< deux faces de Dirichlet : faces 2,3
< deux faces de Dirichlet : faces 1,3
< le tetraedre a deux faces de Dirichlet : faces 1,2
< deux faces de Dirichlet :faces 0,3
< deux faces de Dirichlet :faces 0,2
< deux faces de Dirichlet :faces 0,1
< trois faces de Dirichlet : faces 1,2,3
< trois faces de Dirichlet : faces 0,2,3
< trois faces de Dirichlet : faces 0,1,3
< trois faces de Dirichlet : faces 0,1,2
Implements Elem_VEF_base.
Definition at line 422 of file Tetra_VEF.cpp.
{
  double vol_mod;
  const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
  const IntTab& elem_faces = la_zone_VEF.elem_faces();
  int face;
  int nb_faces_cl = volumes_entrelaces_Cl.size();
  switch(type_cl)
    {
// pas de Face de Dirichlet : impossible
    case 0:
      {
        Cerr << "Tetra_VEF::modif_volumes_entrelaces() type 0 impossible!\n";
        break;
      }
    case 1: //!< une Face de Dirichlet : Face 3
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 2: //!< une Face de Dirichlet : Face 2
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 4: //!< une Face de Dirichlet : Face 1
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 8: //!< une Face de Dirichlet : Face 0
      {
        vol_mod = volumes_entrelaces[j]/3 ;
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 3: //!< deux faces de Dirichlet : faces 2,3
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,2)]
                   + volumes_entrelaces[elem_faces(elem,3)])/2;
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 5: //!< deux faces de Dirichlet : faces 1,3
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,3)])/2;
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 6: //!< le tetraedre a deux faces de Dirichlet : faces 1,2
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,2)])/2;
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 9: //!< deux faces de Dirichlet :faces 0,3
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,3)])/2;
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 10: //!< deux faces de Dirichlet :faces 0,2
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,2)])/2;
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 12: //!< deux faces de Dirichlet :faces 0,1
      {
        vol_mod = (volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,1)])/2;
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 7:  //!< trois faces de Dirichlet : faces 1,2,3
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,2)]
                   + volumes_entrelaces[elem_faces(elem,3)];
        face=elem_faces(elem,0);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 11: //!< trois faces de Dirichlet : faces 0,2,3
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,2)]
                   + volumes_entrelaces[elem_faces(elem,3)];
        face=elem_faces(elem,1);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 13: //!< trois faces de Dirichlet : faces 0,1,3
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,3)];
        face=elem_faces(elem,2);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    case 14: //!< trois faces de Dirichlet : faces 0,1,2
      {
        vol_mod =  volumes_entrelaces[elem_faces(elem,0)]
                   + volumes_entrelaces[elem_faces(elem,1)]
                   + volumes_entrelaces[elem_faces(elem,2)];
        face=elem_faces(elem,3);
        if(face<nb_faces_cl)
          volumes_entrelaces_Cl[face]  += vol_mod;
        break;
      }
    default :
      {
        Cerr << "\n  type inconnu Tetra_VEF::modif_volumes_entrelaces: " << type_cl;
        exit();
      }
    } //!< fin du switch
}
References Cerr, Zone_VF::elem_faces(), Process::exit(), TRUSTVect< _TYPE_ >::size(), and Zone_VF::volumes_entrelaces().
nb_facette()
int Tetra_VEF::nb_facette () const inline override virtual
Implements Elem_VEF_base.
Definition at line 29 of file Tetra_VEF.h.
  {
    return 6;
  };
normale()
void Tetra_VEF::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const override virtual
Implements Elem_VEF_base.
Definition at line 55 of file Tetra_VEF.cpp.
{
// Cerr << " num_Face " << num_Face << finl;
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
// Cerr << "les face sommet " << Face_sommets << finl;
  double x1,y1,z1,x2,y2,z2;
  double nx,ny,nz;
  int f0,no4;
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  int n2 = Face_sommets(num_Face,2);
  x1 = les_coords(n0,0) - les_coords(n1,0);
  y1 = les_coords(n0,1) - les_coords(n1,1);
  z1 = les_coords(n0,2) - les_coords(n1,2);
  x2 = les_coords(n2,0) - les_coords(n1,0);
  y2 = les_coords(n2,1) - les_coords(n1,1);
  z2 = les_coords(n2,2) - les_coords(n1,2);
  nx = (y1*z2 - y2*z1)/2;
  ny = (-x1*z2 + x2*z1)/2;
  nz = (x1*y2 - x2*y1)/2;
// Cerr << "nx " << nx << " ny " << ny << " nz " << nz << finl;
// Orientation de la normale de elem1 vers elem2
// pour cela recherche du sommet de elem1 qui n'est pas sur la Face
  int elem1 = Face_voisins(num_Face,0);
  if ( (f0 = elem_faces(elem1,0)) == num_Face )
    f0 = elem_faces(elem1,1);
  if ( (no4 = Face_sommets(f0,0)) != n0    &&   no4 != n1
       &&   no4 != n2)
    ;
  else if ( (no4 = Face_sommets(f0,1)) != n0 && no4 != n1
            && no4 != n2 )
    ;
  else
    no4 = Face_sommets(f0,2);
  x1 = les_coords(no4,0) - les_coords(n0,0);
  y1 = les_coords(no4,1) - les_coords(n0,1);
  z1 = les_coords(no4,2) - les_coords(n0,2);
  if ( (nx*x1+ny*y1+nz*z1) > 0 )
    {
      Face_normales(num_Face,0) = - nx;
      Face_normales(num_Face,1) = - ny;
      Face_normales(num_Face,2) = - nz;
    }
  else
    {
      Face_normales(num_Face,0) = nx;
      Face_normales(num_Face,1) = ny;
      Face_normales(num_Face,2) = nz;
    }
// Cerr << "Face_normales " << Face_normales << finl;
}
References Domaine::coord_sommets(), and Zone::domaine().
printOn()
Sortie & Tetra_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 26 of file Tetra_VEF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Tetra_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 31 of file Tetra_VEF.cpp.
{
  return s ;
}
self_cast() [1/2]
const Tetra_VEF & Tetra_VEF::self_cast (const Objet_U & r) static
Definition at line 21 of file Tetra_VEF.cpp.
self_cast() [2/2]
Tetra_VEF & Tetra_VEF::self_cast (Objet_U & r) static
Definition at line 21 of file Tetra_VEF.cpp.
taille_memoire()
unsigned Tetra_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Tetra_VEF.cpp.
Member Data Documentation
info_obj
const Type_info Tetra_VEF::info_obj static
Definition at line 25 of file Tetra_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Tetra_VEF.h
src/VEF/Zones/Tetra_VEF.cpp