TRUST: Op_Diff_PolyMAC_Face Class Reference
Op_Diff_PolyMAC_Face Class Reference
: class Op_Diff_PolyMAC_Face
<Description of class Op_Diff_PolyMAC_Face>
#include <Op_Diff_PolyMAC_Face.h>
Public Member Functions
Op_Diff_PolyMAC_Face ()
~Op_Diff_PolyMAC_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int has_interface_blocs () const override
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
Public Member Functions inherited from Op_Diff_PolyMAC_base
Op_Diff_PolyMAC_base ()
~Op_Diff_PolyMAC_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
void mettre_a_jour (double t) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual int dimension_min_nu () const
virtual void modifier_nu (DoubleTab &) const
virtual void dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t &semi_impl={}) const =0
virtual void ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const =0
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
const DoubleTab & nu () const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_PolyMAC_Face & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_PolyMAC_base
static const Type_info * info ()
static Op_Diff_PolyMAC_base & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_PolyMAC_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Diff_PolyMAC_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void update_nu () const
void update_aux (double t) const
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
DoubleVect porosite_e
DoubleVect porosite_f
Protected Attributes inherited from Op_Diff_PolyMAC_base
Ref_Zone_PolyMAC la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base diffusivite_
double t_last_nu_ = -1e10
DoubleTab nu_
int nu_constant_ = 0
int nu_a_jour_ = 0
double t_last_aux_ = -1e10
int use_aux_
Matrice_Bloc mat_aux
DoubleTab var_aux
SolveurSys solv_aux
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
: class Op_Diff_PolyMAC_Face
<Description of class Op_Diff_PolyMAC_Face>
Definition at line 29 of file Op_Diff_PolyMAC_Face.h.
Constructor & Destructor Documentation
Op_Diff_PolyMAC_Face()
Op_Diff_PolyMAC_Face::Op_Diff_PolyMAC_Face ()
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
~Op_Diff_PolyMAC_Face()
Op_Diff_PolyMAC_Face::~Op_Diff_PolyMAC_Face ()
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
Member Function Documentation
ajouter_blocs_ext()
void Op_Diff_PolyMAC_Face::ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Implements Op_Diff_PolyMAC_base.
Definition at line 167 of file Op_Diff_PolyMAC_Face.cpp.
{
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, le_champ_inco.non_nul() ? le_champ_inco.valeur() : equation().inconnue().valeur());
  const Conds_lim& cls = ch.zone_Cl_dis().les_conditions_limites();
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces(), &f_s = zone.face_sommets(), &e_a = zone.zone().elem_aretes(), &fcl = ch.fcl(), &f_e = zone.face_voisins();
  const std::string& nom_inco = ch.le_nom().getString();
  Matrice_Morse* mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
  update_nu();
  int i, j, k, e, f, fb, a, ab, s, n, N = ch.valeurs().line_size(), nf_tot = zone.nb_faces_tot(), d, db, D = dimension, N_nu = nu_.line_size(), semi = semi_impl.count(nom_inco);
  double vecz[3] = { 0, 0, 1 }, v_cl[3], t = equation().schema_temps().temps_courant();
  const DoubleTab& xp = zone.xp(), &xv = zone.xv(), &xs = zone.zone().domaine().coord_sommets(), &xa = D < 3 ? xs : zone.xa(), &ta = zone.ta(), &nf = zone.face_normales(),
                   &inco = semi_impl.count(nom_inco) ? semi_impl.at(nom_inco) : ch.valeurs();
  const DoubleVect& la = zone.longueur_aretes(), &vf = zone.volumes_entrelaces(), &fs = zone.face_surfaces(), &ve = zone.volumes();
  /* que faire avec les variables auxiliaires ? */
  if (aux_only) use_aux_ = 0; /* 1) on est en train d'assembler le systeme de resolution des variables auxiliaires lui-meme */
  else if (mat && !semi) t_last_aux_ = t, use_aux_ = 0; /* 2) on est en implicite complet : pas besoin de mat_aux / var_aux */
  else if (t_last_aux_ < t) update_aux(t); /* 3) premier pas a ce temps en semi-implicite : on calcule les variables auxiliaires a t et on les stocke dans var_aux */
  ConstDoubleTab_parts p_inco(inco); /* deux parties de l'inconnue */
  const DoubleTab& omega = use_aux_ ? var_aux : p_inco[1]; /* les variables auxiliaires peuvent etre soit dans inco/semi_impl (cas 1), soit dans var_aux (cas 2) */
  /* bloc (faces, aretes) : rot [(lambda grad)^u]*/
  if (!aux_only)
    for (f = 0; f < zone.nb_faces(); f++)
      for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
        {
          a = D < 3 ? s : zone.som_arete[s].at(f_s(f, i + 1 < f_s.dimension(1) && f_s(f, i + 1) >= 0 ? i + 1 : 0)); //indice d'arete
          auto vec = zone.cross(3, D, D < 3 ? vecz : &ta(a, 0), &xv(f, 0), NULL, &xa(a, 0));
          int sgn = zone.dot(&nf(f, 0), &vec[0]) > 0 ? 1 : -1; //orientation arete-face
          for (n = 0; n < N; n++) secmem(f, n) -= sgn * vf(f) / fs(f) * (D < 3 ? 1 : la(a)) * omega(a, n);
          if (mat && !semi)
            for (n = 0; n < N; n++) (*mat)(N * f + n, N * (nf_tot + a) + n) += sgn * vf(f) / fs(f) * (D < 3 ? 1 : la(a));
        }
  /* blocs (aretes, faces) et (aretes, aretes) : avec M2 et W1 dans chaque element */
  Matrice33 L(0, 0, 0, 0, 0, 0, 0, 0, D < 3), iL; //tenseur de diffusion dans chaque element, son inverse et le carre de celui-ci
  DoubleTrav dL(N), inu, m2, w1; //determinant, inverse (au format compris par zone.nu_dot), matrices M2(iL) / W1(L)
  nu_.nb_dim() == 2 ? inu.resize(1, N) : nu_.nb_dim() == 3 ? inu.resize(1, N, D) : inu.resize(1, N, D, D);
  m2.set_smart_resize(1), w1.set_smart_resize(1);
  if (!aux_only && mat && semi)
    for (a = 0; a < xa.dimension(0); a++)
      for (n = 0; n < N; n++) /* en semi-implicite : egalites w_a^+ = var_aux */
        secmem(nf_tot + a, n) += omega(a, n) - ch.valeurs()(nf_tot + a, n), (*mat)(N * (nf_tot + a) + n, N * (nf_tot + a) + n)++;
  else if (mat && !semi)
    for (e = 0; e < zone.nb_elem_tot(); e++) /* en implicite : vraies equations */
      {
// tenseur de diffusion diagonal ou anisotrope diagonal : inverses faciles!
        if (nu_.nb_dim() == 2)
          for (n = 0; n < N; n++) inu(0, n) = 1. / nu_(e, n), dL(n) = std::pow(nu_(e, n), D);
        else if (nu_.nb_dim() == 3)
          for (n = 0; n < N; n++)
            for (d = 0, dL(n) = 1; d < D; d++) inu(0, n, d) = 1. / nu_(e, n, d), dL(n) *= nu_(e, n, d);
        if (nu_.nb_dim() < 4)
          for (i = 0; i < N_nu; i++) inu.addr()[i] = 1. / nu_.addr()[N_nu * e + i];
        else for (n = 0; n < N; n++) //sinon : une matrice a inverser par composante
            {
              for (d = 0; d < D; d++)
                for (db = 0; db < D; db++) L(d, db) = nu_(e, n, d, db);
              dL(n) = Matrice33::inverse(L, iL); //renvoie le determinant!
              for (d = 0; d < D; d++)
                for (db = 0; db < D; db++) inu(0, n, d, db) = iL(d, db);
            }
        zone.M2(&inu, e, m2);
        if (D > 2) zone.W1(&nu_, e, w1); //uniquement en 3D: en 2D, matrice diagonale
// bloc (aretes, faces): en parcourant les aretes de chaque face
        for (i = 0; i < m2.dimension(0); i++)
          for (f = e_f(e, i), j = 0; j < f_s.dimension(1) && (s = f_s(f, j)) >= 0; j++)
            if ((a = D < 3 ? s : zone.som_arete[s].at(f_s(f, j + 1 < f_s.dimension(1) && f_s(f, j + 1) >= 0 ? j + 1 : 0))) < (D < 3 ? zone.zone().nb_som() : zone.zone().nb_aretes()))
              {
                auto vec = zone.cross(3, D, D < 3 ? vecz : &ta(a, 0), &xv(f, 0), NULL, &xa(a, 0));
                int sgn = (e == f_e(f, 0) ? 1 : -1) * zone.dot(&nf(f, 0), &vec[0]) > 0 ? 1 : -1; //orientation arete-face (dans le sens sortant de e)
                for (k = 0; k < m2.dimension(1); k++)
                  for (fb = e_f(e, k), n = 0; n < N; n++)//partie x_e -> x_f avec m2 + partie x_f -> x_a avec v_e si bord de Neumann / Symetrie
                    {
                      double coeff = m2(i, k, n) + (fcl(f, 0) == 2 ? zone.nu_dot(&inu, 0, n, &xa(a, 0), &xv(fb, 0), &xv(f, 0), &xp(e, 0)) / ve(e) : 0);
                      if (!coeff) continue;
                      secmem(!aux_only * nf_tot + a, n) += sgn * coeff * inco(fb, n) * fs(fb) * (e == f_e(fb, 0) ? 1 : -1);
                      if (!aux_only) (*mat)(N * (nf_tot + a) + n, N * fb + n) -= sgn * coeff * fs(fb) * (e == f_e(fb, 0) ? 1 : -1);
                    }
                if (fcl(f, 0) == 3 && sub_type(Dirichlet, cls[fcl(f, 1)].valeur()))
                  for (n = 0; n < N; n++) //si bord de Dirichlet : partie x_f -> x_a avec la vitesse donnee par la CL
                    {
                      for (d = 0; d < D; d++) v_cl[d] = ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), N * d + n); //v impose
                      secmem(!aux_only * nf_tot + a, n) += sgn * zone.nu_dot(&inu, 0, n, &xa(a, 0), v_cl, &xv(f, 0));
                    }
              }
// bloc (aretes, aretes) : avec m1 si D = 3, diagonale * surface si D = 2
        if (D == 2)
          {
            for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
              for (j = 0; j < 2; j++)
                if ((s = f_s(f, j)) < zone.nb_som())
                  {
                    auto vec = zone.cross(D, D, &xv(f, 0), &xs(s, 0), &xp(e, 0), &xp(e, 0));
                    double surf = std::abs(vec[2]) / 2; //surface du triangle (e, f, s)
                    for (n = 0; n < N; n++) secmem(!aux_only * nf_tot + s, n) -= surf * inco(nf_tot + s, n)  / dL(n);
                    for (n = 0; n < N; n++) (*mat)(N * (!aux_only * nf_tot + s) + n, N * (!aux_only * nf_tot + s) + n) += surf / dL(n);
                  }
          }
        else for (i = 0; i < w1.dimension(0); i++)
            if ((a = e_a(e, i)) < zone.zone().nb_aretes())
              for (j = 0; j < w1.dimension(1); j++)
                for (ab = e_a(e, j), n = 0; n < N; n++)
                  if (w1(i, j, n))
                    {
                      secmem(!aux_only * nf_tot + a, n) -= w1(i, j, n) * la(ab) * inco(nf_tot + ab, n) / dL(n);
                      (*mat)(N * (!aux_only * nf_tot + a) + n, N * (!aux_only * nf_tot + ab) + n) += w1(i, j, n) * la(ab) / dL(n);
                    }
      }
  i++;
}
References TRUSTArray< _TYPE_ >::addr(), coeff, Domaine::coord_sommets(), Zone_Poly_base::cross(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_Poly_base::dot(), Zone::elem_aretes(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), Nom::getString(), Matrice33::inverse(), Op_Diff_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, Field_base::le_nom(), Zone_Cl_dis::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone_PolyMAC::longueur_aretes(), m2, Zone_PolyMAC::M2(), Zone::nb_aretes(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_som(), Zone::nb_som(), O_U_Ptr::non_nul(), Op_Diff_PolyMAC_base::nu_, Zone_Poly_base::nu_dot(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Equation_base::schema_temps(), TRUSTArray< _TYPE_ >::set_smart_resize(), sgn, Zone_PolyMAC::som_arete, sub_type, Op_Diff_PolyMAC_base::t_last_aux_, Zone_PolyMAC::ta(), Schema_Temps_base::temps_courant(), Op_Diff_PolyMAC_base::update_aux(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_base::use_aux_, Ref_Champ_Inc::valeur(), Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc_base::valeurs(), Op_Diff_PolyMAC_base::var_aux, Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), Zone_PolyMAC::W1(), Zone_VF::xa(), Zone_VF::xp(), Zone_VF::xv(), Zone_dis_base::zone(), and Champ_Inc_base::zone_Cl_dis().
calculer_dt_stab()
double Op_Diff_PolyMAC_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 68 of file Op_Diff_PolyMAC_Face.cpp.
{
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces();
  const DoubleTab& nf = zone.face_normales(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL,
                    *a_r = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.champ_conserve().passe() : (has_champ_masse_volumique() ? &get_champ_masse_volumique().valeurs() : NULL); /* produit alpha * rho */
  const DoubleVect& pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  update_nu();
  int i, e, f, n, N = equation().inconnue().valeurs().line_size();
  double dt = 1e10;
  DoubleTrav flux(N), vol(N);
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, vol = pe(e) * ve(e), i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        for (n = 0; n < N; n++)
          flux(n) += zone.nu_dot(&nu_, e, n, &nf(f, 0), &nf(f, 0)) / vf(f);
      for (n = 0; n < N; n++)
        if ((!alp || (*alp)(e, n) > 0.25) && flux(n)) /* sous 0.5e-6, on suppose que l'evanescence fait le job */
          dt = std::min(dt, vol(n) * (a_r ? (*a_r)(e, n) : 1) / flux(n));
    }
  return Process::mp_min(dt);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::face_normales(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Op_Diff_PolyMAC_base::la_zone_poly_, TRUSTVect< _TYPE_ >::line_size(), Process::mp_min(), Zone_dis_base::nb_elem(), Op_Diff_PolyMAC_base::nu_, Zone_Poly_base::nu_dot(), Zone_VF::porosite_elem(), ref_cast, sub_type, Op_Diff_PolyMAC_base::update_nu(), Ref_Zone_PolyMAC::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
check_multiphase_compatibility()
void Op_Diff_PolyMAC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 44 of file Op_Diff_PolyMAC_Face.h.
{}; //ok
completer()
void Op_Diff_PolyMAC_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 53 of file Op_Diff_PolyMAC_Face.cpp.
{
  Op_Diff_PolyMAC_base::completer();
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  Equation_base& eq = equation();
  Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, le_champ_inco.non_nul() ? le_champ_inco.valeur() : eq.inconnue().valeur());
  ch.init_auxiliary_variables(); /* ajout des inconnues auxiliaires (vorticites aux aretes) */
  flux_bords_.resize(zone.premiere_face_int(), dimension * ch.valeurs().line_size());
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Diff_PolyMAC_Face : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  porosite_e.ref(zone.porosite_elem());
  porosite_f.ref(zone.porosite_face());
  op_ext = { this };
}
References Cerr, Op_Diff_PolyMAC_base::completer(), Objet_U::dimension, Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Equation_base::inconnue(), Champ_Face_PolyMAC::init_auxiliary_variables(), Zone::joint(), Op_Diff_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, TRUSTVect< _TYPE_ >::line_size(), Zone::nb_joints(), O_U_Ptr::non_nul(), Operateur_Diff_base::op_ext, porosite_e, Zone_VF::porosite_elem(), porosite_f, Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), TRUSTVect< _TYPE_ >::ref(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Deriv_Champ_Inc_base::valeur(), Ref_Champ_Inc::valeur(), Ref_Zone_PolyMAC::valeur(), Champ_Inc_base::valeurs(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Op_Diff_PolyMAC_Face::cree_instance () static
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
dimensionner_blocs_ext()
void Op_Diff_PolyMAC_Face::dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Implements Op_Diff_PolyMAC_base.
Definition at line 93 of file Op_Diff_PolyMAC_Face.cpp.
{
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, le_champ_inco.non_nul() ? le_champ_inco.valeur() : equation().inconnue().valeur());
  const Zone_PolyMAC& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces(), &f_s = zone.face_sommets(), &e_a = zone.zone().elem_aretes(), &fcl = ch.fcl();
  const std::string& nom_inco = ch.le_nom().getString();
  if (!matrices.count(nom_inco)) return; //pas de bloc diagonal -> rien a faire
  Matrice_Morse& mat = *matrices.at(nom_inco), mat2;
  update_nu();
  ConstDoubleTab_parts p_inco(ch.valeurs());
  int i, j, k, e, f, fb, a, ab, s, n, N = ch.valeurs().line_size(), nf_tot = zone.nb_faces_tot(), d, db, D = dimension, N_nu = nu_.line_size(), semi = semi_impl.count(nom_inco);
  IntTrav stencil(0, 2);
  stencil.set_smart_resize(1);
  Cerr << "Op_Diff_PolyMAC_Face::dimensionner() : ";
  /* bloc (faces, aretes) : rot [(lambda grad)^u]*/
  if (!semi && !aux_only)
    for (f = 0; f < zone.nb_faces(); f++)
      for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
        for (a = D < 3 ? s : zone.som_arete[s].at(f_s(f, i + 1 < f_s.dimension(1) && f_s(f, i + 1) >= 0 ? i + 1 : 0)), n = 0; n < N; n++)
          stencil.append_line(N * f + n, N * (nf_tot + a) + n);
  /* blocs (aretes, faces) et (aretes, aretes) : avec M2 et W1 dans chaque element */
  Matrice33 L(0, 0, 0, 0, 0, 0, 0, 0, D < 3), iL; //tenseur de diffusion dans chaque element, son inverse
  DoubleTrav inu, m2, w1; //au format compris par zone.nu_dot
  nu_.nb_dim() == 2 ? inu.resize(1, N) : nu_.nb_dim() == 3 ? inu.resize(1, N, D) : inu.resize(1, N, D, D);
  m2.set_smart_resize(1), w1.set_smart_resize(1);
  if (!semi)
    for (e = 0; e < zone.nb_elem_tot(); e++)
      {
// tenseur de diffusion diagonal ou anisotrope diagonal : inverse faciles!
        if (nu_.nb_dim() < 4)
          for (i = 0; i < N_nu; i++) inu.addr()[i] = 1. / nu_.addr()[N_nu * e + i];
        else for (n = 0; n < N; n++) //sinon : une matrice a inverser par composante
            {
              for (d = 0; d < D; d++)
                for (db = 0; db < D; db++) L(d, db) = nu_(e, n, d, db);
              Matrice33::inverse(L, iL);
              for (d = 0; d < D; d++)
                for (db = 0; db < D; db++) inu(0, n, d, db) = iL(d, db);
            }
        zone.M2(&inu, e, m2);
        if (D > 2) zone.W1(&nu_, e, w1); //uniquement en 3D: en 2D, matrice diagonale
// bloc (aretes, faces): en parcourant les aretes de chaque face
        if (!aux_only)
          for (i = 0; i < m2.dimension(0); i++)
            for (f = e_f(e, i), j = 0; j < f_s.dimension(1) && (s = f_s(f, j)) >= 0; j++)
              if ((a = D < 3 ? s : zone.som_arete[s].at(f_s(f, j + 1 < f_s.dimension(1) && f_s(f, j + 1) >= 0 ? j + 1 : 0))) < (D < 3 ? zone.zone().nb_som() : zone.zone().nb_aretes()))
                for (k = 0; k < m2.dimension(1); k++)
                  for (fb = e_f(e, k), n = 0; n < N; n++)
                    if (fcl(f, 0) == 2 || m2(i, k, n)) //si f est Symetrie, alors il y a aussi une partie en ve -> dependance complete
                      stencil.append_line(N * (nf_tot + a) + n, N * fb + n);
// bloc (aretes, aretes) : avec m1 si D = 3 (sinon, fait ensuite)
        if (D > 2)
          for (i = 0; i < w1.dimension(0); i++)
            if ((a = e_a(e, i)) < zone.zone().nb_aretes())
              for (j = 0; j < w1.dimension(1); j++)
                for (ab = e_a(e, j), n = 0; n < N; n++)
                  if (w1(i, j, n)) stencil.append_line(N * (!aux_only * nf_tot + a) + n, N * (!aux_only * nf_tot + ab) + n);
      }
  if (semi || D < 3)
    for (s = 0; s < (D < 3 ? zone.nb_som() : zone.zone().nb_aretes()); s++)
      for (n = 0; n < N; n++) stencil.append_line(N * (!aux_only * nf_tot + s) + n, N * (!aux_only * nf_tot + s) + n);
  tableau_trier_retirer_doublons(stencil);
  Cerr << "OK" << finl;
  Matrix_tools::allocate_morse_matrix(aux_only ? p_inco[1].size_totale() : ch.valeurs().size_totale(), aux_only ? p_inco[1].size_totale() : ch.valeurs().size_totale(), stencil, mat2);
  mat.nb_colonnes() ? mat += mat2 : mat = mat2;
}
References TRUSTArray< _TYPE_ >::addr(), Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::elem_aretes(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_sommets(), Champ_Face_PolyMAC::fcl(), finl, Nom::getString(), Matrice33::inverse(), Op_Diff_PolyMAC_base::la_zone_poly_, Operateur_base::le_champ_inco, Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), m2, Zone_PolyMAC::M2(), Zone::nb_aretes(), Matrice_Morse::nb_colonnes(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_som(), Zone::nb_som(), O_U_Ptr::non_nul(), Op_Diff_PolyMAC_base::nu_, ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), Zone_PolyMAC::som_arete, tableau_trier_retirer_doublons(), Op_Diff_PolyMAC_base::update_nu(), Ref_Champ_Inc::valeur(), Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc_base::valeurs(), Zone_PolyMAC::W1(), and Zone_dis_base::zone().
duplique()
int Op_Diff_PolyMAC_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
get_info()
const Type_info * Op_Diff_PolyMAC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
has_interface_blocs()
int Op_Diff_PolyMAC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 37 of file Op_Diff_PolyMAC_Face.h.
  {
    return 1;
  };
info()
const Type_info * Op_Diff_PolyMAC_Face::info () static
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
modifier_pour_Cl()
void Op_Diff_PolyMAC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Diff_PolyMAC_Face.h.
{ };
printOn()
Sortie & Op_Diff_PolyMAC_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 41 of file Op_Diff_PolyMAC_Face.cpp.
{
  Op_Diff_PolyMAC_base::printOn( os );
  return os;
}
References Op_Diff_PolyMAC_base::printOn().
readOn()
Entree & Op_Diff_PolyMAC_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_PolyMAC_base.
Definition at line 47 of file Op_Diff_PolyMAC_Face.cpp.
{
  Op_Diff_PolyMAC_base::readOn( is );
  return is;
}
References Op_Diff_PolyMAC_base::readOn().
self_cast() [1/2]
const Op_Diff_PolyMAC_Face & Op_Diff_PolyMAC_Face::self_cast (const Objet_U & r) static
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
self_cast() [2/2]
Op_Diff_PolyMAC_Face & Op_Diff_PolyMAC_Face::self_cast (Objet_U & r) static
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
taille_memoire()
unsigned Op_Diff_PolyMAC_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 37 of file Op_Diff_PolyMAC_Face.cpp.
Member Data Documentation
info_obj
const Type_info Op_Diff_PolyMAC_Face::info_obj static
Definition at line 32 of file Op_Diff_PolyMAC_Face.h.
porosite_e
DoubleVect Op_Diff_PolyMAC_Face::porosite_e protected
Definition at line 46 of file Op_Diff_PolyMAC_Face.h.
Referenced by completer().
porosite_f
DoubleVect Op_Diff_PolyMAC_Face::porosite_f protected
Definition at line 47 of file Op_Diff_PolyMAC_Face.h.
Referenced by completer().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_Face.h
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_Face.cpp