TRUST: Verifier_Qualite_Raffinements Class Reference
Verifier_Qualite_Raffinements Class Reference
: class Verifier_Qualite_Raffinements
<Description of class Verifier_Qualite_Raffinements>
#include <Verifier_Qualite_Raffinements.h>
Public Member Functions
Verifier_Qualite_Raffinements ()
~Verifier_Qualite_Raffinements ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Verifier_Qualite_Raffinements & self_cast (Objet_U &)
static const
Verifier_Qualite_Raffinements & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void verifier_qualite_raffinements (void)
Detailed Description
: class Verifier_Qualite_Raffinements
<Description of class Verifier_Qualite_Raffinements>
Definition at line 38 of file Verifier_Qualite_Raffinements.h.
Constructor & Destructor Documentation
Verifier_Qualite_Raffinements::Verifier_Qualite_Raffinements ()
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
Verifier_Qualite_Raffinements::~Verifier_Qualite_Raffinements ()
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
Member Function Documentation
Objet_U * Verifier_Qualite_Raffinements::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
int Verifier_Qualite_Raffinements::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
const Type_info * Verifier_Qualite_Raffinements::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
const Type_info * Verifier_Qualite_Raffinements::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
Entree & Verifier_Qualite_Raffinements::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 258 of file Verifier_Qualite_Raffinements.cpp.
References Interprete_geometrique_base::associer_domaine(), and verifier_qualite_raffinements().
{
  int nb_refinements;
  is >> nb_refinements;
  for (int i=0; i<nb_refinements; ++i)
    {
      associer_domaine(is);
    }
  verifier_qualite_raffinements();
  return is;
}
Sortie & Verifier_Qualite_Raffinements::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Verifier_Qualite_Raffinements.cpp.
{
  Interprete_geometrique_base::printOn(os);
  return os;
}
Entree & Verifier_Qualite_Raffinements::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 36 of file Verifier_Qualite_Raffinements.cpp.
{
  Interprete_geometrique_base::readOn(is);
  return is;
}
const Verifier_Qualite_Raffinements & Verifier_Qualite_Raffinements::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
Verifier_Qualite_Raffinements & Verifier_Qualite_Raffinements::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
unsigned Verifier_Qualite_Raffinements::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 28 of file Verifier_Qualite_Raffinements.cpp.
void Verifier_Qualite_Raffinements::verifier_qualite_raffinements (void) [protected]
Definition at line 233 of file Verifier_Qualite_Raffinements.cpp.
References Sortie_Fichier_base::close(), compute_cell_qualities(), Interprete_geometrique_base::domaine(), Interprete_geometrique_base::domaines(), finl, liste::size(), and ArrOfDouble::size_array().
Referenced by interpreter_().
{
  const int nb_domains = domaines().size() ;
  assert( nb_domains > 1 );
  for (int i=0; i<nb_domains; ++i)
    {
      ArrOfDouble qualities;
      compute_cell_qualities(domaine(i),qualities);
      Nom filename("quality_");
      filename += Nom(i);
      filename += Nom(".gnu");
      SFichier os(filename);
      const int nb_cells = qualities.size_array();
      for (int cell=0; cell<nb_cells; ++cell)
        {
          os << qualities[cell] << finl;
        }
      os.close();
    }
}
Member Data Documentation
const Type_info Verifier_Qualite_Raffinements::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 41 of file Verifier_Qualite_Raffinements.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Verifier_Qualite_Raffinements.h
src/Kernel/Geometrie/Verifier_Qualite_Raffinements.cpp