TRUST: Convection_Diffusion_Fluide_Dilatable_base Class Reference
Convection_Diffusion_Fluide_Dilatable_base Class Reference
classe Convection_Diffusion_Fluide_Dilatable_base pour un fluide dilatable
#include <Convection_Diffusion_Fluide_Dilatable_base.h>
Public Member Functions
Convection_Diffusion_Fluide_Dilatable_base ()
~Convection_Diffusion_Fluide_Dilatable_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Dilatable_base &)
void associer_milieu_base (const Milieu_base &)
int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
const Champ_Don & diffusivite_pour_transport ()
const Fluide_Dilatable_base & fluide () const
Fluide_Dilatable_base & fluide ()
const Milieu_base & milieu () const
Milieu_base & milieu ()
virtual void set_param (Param &titi)
virtual int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void calculer_div_u_ou_div_rhou (DoubleTab &res) const =0
virtual bool is_thermal ()=0
virtual bool is_generic ()=0
const Champ_Inc & inconnue () const
Champ_Inc & inconnue ()
const Zone_Cl_dis & zone_cl_modif () const
Zone_Cl_dis & zone_cl_modif ()
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Convection_Diffusion_Fluide_Dilatable_base & self_cast (Objet_U &)
static const
Convection_Diffusion_Fluide_Dilatable_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Equation_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
Protected Attributes
Champ_Inc l_inco_ch
Zone_Cl_dis zcl_modif_
Ref_Fluide_Dilatable_base le_fluide
Detailed Description
classe Convection_Diffusion_Fluide_Dilatable_base pour un fluide dilatable
Definition at line 39 of file Convection_Diffusion_Fluide_Dilatable_base.h.
Constructor & Destructor Documentation
Convection_Diffusion_Fluide_Dilatable_base::Convection_Diffusion_Fluide_Dilatable_base ()
Definition at line 27 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
Convection_Diffusion_Fluide_Dilatable_base::~Convection_Diffusion_Fluide_Dilatable_base ()
Definition at line 27 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
Member Function Documentation
void Convection_Diffusion_Fluide_Dilatable_base::associer_fluide (const Fluide_Dilatable_base & un_fluide)
Definition at line 56 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References le_fluide.
Referenced by associer_milieu_base().
{
  le_fluide = un_fluide;
}
void Convection_Diffusion_Fluide_Dilatable_base::associer_milieu_base (const Milieu_base & un_milieu) [virtual]
Implements Equation_base.
Definition at line 50 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References associer_fluide(), and ref_cast.
{
  const Fluide_Dilatable_base& un_fluide = ref_cast(Fluide_Dilatable_base,un_milieu);
  associer_fluide(un_fluide);
}
virtual void Convection_Diffusion_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou (DoubleTab & res) const [pure virtual]
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Chaleur_WC.
const Champ_Don & Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport () [virtual]
Reimplemented from Convection_Diffusion_std.
Definition at line 66 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References Milieu_base::conductivite(), is_thermal(), le_fluide, and milieu().
Referenced by Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), and Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard().
{
  return is_thermal() ? milieu().conductivite() /* lambda */ : le_fluide->mu_sur_Schmidt() /* rho * D */;
}
virtual int Convection_Diffusion_Fluide_Dilatable_base::duplique () const [pure virtual]
Implements Convection_Diffusion_std.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
const Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::fluide () const
Definition at line 71 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References Cerr, Process::exit(), finl, le_fluide, Probleme_base::le_nom(), O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Fluide_Dilatable_base::valeur().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), and milieu().
{
  if (!le_fluide.non_nul())
    {
      Cerr << "You forgot to associate the fluid to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_fluide.valeur();
}
Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::fluide ()
Definition at line 81 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References le_fluide, O_U_Ptr::non_nul(), and Ref_Fluide_Dilatable_base::valeur().
{
  assert(le_fluide.non_nul());
  return le_fluide.valeur();
}
const Type_info * Convection_Diffusion_Fluide_Dilatable_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 27 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
int Convection_Diffusion_Fluide_Dilatable_base::impr (Sortie & os) const [virtual]
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Definition at line 61 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
{
  return Equation_base::impr(os);
}
const Champ_Inc& Convection_Diffusion_Fluide_Dilatable_base::inconnue () const [inline, virtual]
Implements Convection_Diffusion_std.
Definition at line 63 of file Convection_Diffusion_Fluide_Dilatable_base.h.
References l_inco_ch.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Convection_Diffusion_Chaleur_WC::completer(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Convection_Diffusion_Espece_Multi_base::readOn(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder().
{ return l_inco_ch; }
Champ_Inc& Convection_Diffusion_Fluide_Dilatable_base::inconnue () [inline, virtual]
Implements Convection_Diffusion_std.
Definition at line 64 of file Convection_Diffusion_Fluide_Dilatable_base.h.
References l_inco_ch.
{ return l_inco_ch; }
const Type_info * Convection_Diffusion_Fluide_Dilatable_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 27 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
virtual bool Convection_Diffusion_Fluide_Dilatable_base::is_generic () [pure virtual]
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Chaleur_WC.
virtual bool Convection_Diffusion_Fluide_Dilatable_base::is_thermal () [pure virtual]
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
Referenced by diffusivite_pour_transport().
int Convection_Diffusion_Fluide_Dilatable_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Chaleur_WC.
Definition at line 45 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
{
  return Convection_Diffusion_std::lire_motcle_non_standard(mot,is);
}
const Milieu_base & Convection_Diffusion_Fluide_Dilatable_base::milieu () const [virtual]
Implements Equation_base.
Definition at line 87 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References fluide().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), and diffusivite_pour_transport().
{
  return fluide();
}
Milieu_base & Convection_Diffusion_Fluide_Dilatable_base::milieu () [virtual]
Implements Equation_base.
Definition at line 92 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References fluide().
{
  return fluide();
}
Sortie & Convection_Diffusion_Fluide_Dilatable_base::printOn (Sortie & is) const [protected, virtual]
Simple appel a Equation_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 29 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
{
  return Convection_Diffusion_std::printOn(is);
}
Entree & Convection_Diffusion_Fluide_Dilatable_base::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 34 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
References l_inco_ch, le_fluide, and O_U_Ptr::non_nul().
{
  assert(l_inco_ch.non_nul() && le_fluide.non_nul());
  return Convection_Diffusion_std::readOn(is);
}
const Convection_Diffusion_Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 27 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
Convection_Diffusion_Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::self_cast (Objet_U & r) [static]
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 27 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
void Convection_Diffusion_Fluide_Dilatable_base::set_param (Param & titi) [virtual]
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Chaleur_WC.
Definition at line 40 of file Convection_Diffusion_Fluide_Dilatable_base.cpp.
{
  Convection_Diffusion_std::set_param(param);
}
const Zone_Cl_dis& Convection_Diffusion_Fluide_Dilatable_base::zone_cl_modif () const [inline]
Definition at line 65 of file Convection_Diffusion_Fluide_Dilatable_base.h.
References zcl_modif_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
{ return zcl_modif_ ;}
Zone_Cl_dis& Convection_Diffusion_Fluide_Dilatable_base::zone_cl_modif () [inline]
Definition at line 66 of file Convection_Diffusion_Fluide_Dilatable_base.h.
References zcl_modif_.
{ return zcl_modif_ ;}
Member Data Documentation
const Type_info Convection_Diffusion_Fluide_Dilatable_base::info_obj [static]
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Fluide_Dilatable_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 42 of file Convection_Diffusion_Fluide_Dilatable_base.h.
Champ_Inc Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch [protected]
Definition at line 69 of file Convection_Diffusion_Fluide_Dilatable_base.h.
Referenced by Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), inconnue(), readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre().
Ref_Fluide_Dilatable_base Convection_Diffusion_Fluide_Dilatable_base::le_fluide [protected]
Definition at line 71 of file Convection_Diffusion_Fluide_Dilatable_base.h.
Referenced by associer_fluide(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Convection_Diffusion_Espece_Binaire_WC::completer(), Convection_Diffusion_Espece_Binaire_QC::completer(), Convection_Diffusion_Espece_Multi_WC::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Multi_QC::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Binaire_base::diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::domaine_application(), fluide(), readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Espece_Binaire_WC::sauvegarder(), Convection_Diffusion_Chaleur_WC::sauvegarder(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder().
Zone_Cl_dis Convection_Diffusion_Fluide_Dilatable_base::zcl_modif_ [protected]
Definition at line 70 of file Convection_Diffusion_Fluide_Dilatable_base.h.
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Espece_Binaire_base::preparer_calcul(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), and zone_cl_modif().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Fluide_Dilatable_base.h
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Fluide_Dilatable_base.cpp