TRUST: Evaluateur_Source_PolyMAC_Face Class Reference
Evaluateur_Source_PolyMAC_Face Class Reference abstract
#include <Evaluateur_Source_PolyMAC_Face.h>
Public Member Functions
Evaluateur_Source_PolyMAC_Face ()
Evaluateur_Source_PolyMAC_Face (const Evaluateur_Source_PolyMAC_Face &)
void completer () override
virtual double calculer_terme_source_bord (int) const =0
virtual void calculer_terme_source_bord (int, DoubleVect &) const =0
Public Member Functions inherited from Evaluateur_Source_PolyMAC
Evaluateur_Source_PolyMAC ()
virtual ~Evaluateur_Source_PolyMAC ()
Evaluateur_Source_PolyMAC (const Evaluateur_Source_PolyMAC &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual double calculer_terme_source (int) const =0
virtual void calculer_terme_source (int, DoubleVect &) const =0
Protected Attributes
IntVect orientation
orientations des faces
DoubleVect volumes_entrelaces
DoubleVect porosite_surf
porosites surfaciques
Protected Attributes inherited from Evaluateur_Source_PolyMAC
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Detailed Description
Definition at line 22 of file Evaluateur_Source_PolyMAC_Face.h.
Constructor & Destructor Documentation
Evaluateur_Source_PolyMAC_Face() [1/2]
Evaluateur_Source_PolyMAC_Face::Evaluateur_Source_PolyMAC_Face () inline
Definition at line 25 of file Evaluateur_Source_PolyMAC_Face.h.
{}
Evaluateur_Source_PolyMAC_Face() [2/2]
Evaluateur_Source_PolyMAC_Face::Evaluateur_Source_PolyMAC_Face (const Evaluateur_Source_PolyMAC_Face & eval)
Definition at line 23 of file Evaluateur_Source_PolyMAC_Face.cpp.
  : Evaluateur_Source_PolyMAC(eval)
{
  orientation.ref(eval.orientation);
  volumes_entrelaces.ref(eval.volumes_entrelaces);
  porosite_surf.ref(eval.porosite_surf);
}
References orientation, porosite_surf, TRUSTVect< _TYPE_ >::ref(), and volumes_entrelaces.
Member Function Documentation
calculer_terme_source_bord() [1/2]
virtual double Evaluateur_Source_PolyMAC_Face::calculer_terme_source_bord (int) const pure virtual
calculer_terme_source_bord() [2/2]
virtual void Evaluateur_Source_PolyMAC_Face::calculer_terme_source_bord (int , DoubleVect &) const pure virtual
completer()
void Evaluateur_Source_PolyMAC_Face::completer (void) override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 31 of file Evaluateur_Source_PolyMAC_Face.cpp.
{
  orientation.ref(la_zone->orientation());
  volumes_entrelaces.ref(la_zone->volumes_entrelaces());
  porosite_surf.ref(la_zone->porosite_face());
}
References Evaluateur_Source_PolyMAC::la_zone, Zone_VF::orientation(), orientation, Zone_VF::porosite_face(), porosite_surf, TRUSTVect< _TYPE_ >::ref(), Zone_VF::volumes_entrelaces(), and volumes_entrelaces.
Member Data Documentation
orientation
IntVect Evaluateur_Source_PolyMAC_Face::orientation protected
orientations des faces
Definition at line 32 of file Evaluateur_Source_PolyMAC_Face.h.
Referenced by completer(), and Evaluateur_Source_PolyMAC_Face().
porosite_surf
DoubleVect Evaluateur_Source_PolyMAC_Face::porosite_surf protected
porosites surfaciques
Definition at line 33 of file Evaluateur_Source_PolyMAC_Face.h.
Referenced by completer(), and Evaluateur_Source_PolyMAC_Face().
volumes_entrelaces
DoubleVect Evaluateur_Source_PolyMAC_Face::volumes_entrelaces protected
Definition at line 33 of file Evaluateur_Source_PolyMAC_Face.h.
Referenced by completer(), and Evaluateur_Source_PolyMAC_Face().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Evaluateur_Source_PolyMAC_Face.h
src/PolyMAC/Sources/Evaluateur_Source_PolyMAC_Face.cpp