TRUST: Iterateur_PolyMAC_base Class Reference
Iterateur_PolyMAC_base Class Reference
#include <Iterateur_PolyMAC_base.h>
Public Member Functions
Iterateur_PolyMAC_base ()
~Iterateur_PolyMAC_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_PolyMAC &, const Zone_Cl_PolyMAC &, const Operateur_base &)
void associer (const Zone_dis &, const Zone_Cl_dis &, const Operateur_base &)
void associer_zone_cl_dis (const Zone_Cl_dis_base &)
Type_Cl_PolyMAC type_cl (const Cond_lim &) const
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const =0
virtual void calculer_flux_bord (const DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const =0
virtual void contribuer_au_second_membre (DoubleTab &) const =0
virtual void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const =0
virtual void ajouter_contribution_vitesse (const DoubleTab &, Matrice_Morse &) const =0
virtual Evaluateur_PolyMAC & evaluateur ()=0
virtual const Evaluateur_PolyMAC & evaluateur () const =0
const Zone_PolyMAC & zone () const
const Zone_Cl_PolyMAC & zone_Cl () const
virtual void completer_ ()=0
virtual int impr (Sortie &os) const =0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Iterateur_PolyMAC_base & self_cast (Objet_U &)
static const
Iterateur_PolyMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Ref_Operateur_base op_base
Detailed Description
Definition at line 76 of file Iterateur_PolyMAC_base.h.
Constructor & Destructor Documentation
Iterateur_PolyMAC_base::Iterateur_PolyMAC_base ()
Definition at line 26 of file Iterateur_PolyMAC_base.cpp.
Iterateur_PolyMAC_base::~Iterateur_PolyMAC_base ()
Definition at line 26 of file Iterateur_PolyMAC_base.cpp.
Member Function Documentation
virtual DoubleTab& Iterateur_PolyMAC_base::ajouter (const DoubleTab & , DoubleTab &) const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::ajouter().
virtual void Iterateur_PolyMAC_base::ajouter_contribution (const DoubleTab & , Matrice_Morse &) const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::ajouter_contribution().
virtual void Iterateur_PolyMAC_base::ajouter_contribution_vitesse (const DoubleTab & , Matrice_Morse &) const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::ajouter_contribution_vitesse().
void Iterateur_PolyMAC_base::associer (const Zone_dis & z, const Zone_Cl_dis & zcl, const Operateur_base & op)
Definition at line 62 of file Iterateur_PolyMAC_base.cpp.
References associer(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_PolyMAC& zone_vdf=ref_cast(Zone_PolyMAC, z.valeur());
  const Zone_Cl_PolyMAC& zone_cl_vdf=ref_cast(Zone_Cl_PolyMAC, zcl.valeur());
  associer(zone_vdf, zone_cl_vdf,op);
}
void Iterateur_PolyMAC_base::associer (const Zone_PolyMAC & zone_vdf, const Zone_Cl_PolyMAC & zone_cl_vdf, const Operateur_base & op)
Definition at line 75 of file Iterateur_PolyMAC_base.cpp.
References la_zcl, la_zone, and op_base.
Referenced by Iterateur_PolyMAC::associer(), and associer().
{
  la_zone=zone_vdf;
  la_zcl=zone_cl_vdf;
  op_base=op;
// completer_();
}
void Iterateur_PolyMAC_base::associer_zone_cl_dis (const Zone_Cl_dis_base & zcl)
Definition at line 69 of file Iterateur_PolyMAC_base.cpp.
References la_zcl, and ref_cast.
Referenced by Op_Conv_PolyMAC_iterateur_base::associer_zone_cl_dis().
{
  const Zone_Cl_PolyMAC& zone_cl_vdf=ref_cast(Zone_Cl_PolyMAC, zcl);
  la_zcl=zone_cl_vdf;
}
virtual DoubleTab& Iterateur_PolyMAC_base::calculer (const DoubleTab & , DoubleTab &) const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::calculer().
void Iterateur_PolyMAC_base::calculer_flux_bord (const DoubleTab & inco) const [virtual]
Reimplemented in T_It_PolyMAC_Elem< _TYPE_ >.
Definition at line 45 of file Iterateur_PolyMAC_base.cpp.
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
{
  Cerr<<que_suis_je()<<" must implement alculer_flux_bord"<<finl;
  assert(0);
  Process::exit();
}
virtual void Iterateur_PolyMAC_base::completer_ () [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::completer_().
virtual void Iterateur_PolyMAC_base::contribuer_au_second_membre (DoubleTab &) const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::contribuer_au_second_membre().
virtual int Iterateur_PolyMAC_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
virtual Evaluateur_PolyMAC& Iterateur_PolyMAC_base::evaluateur () [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::evaluateur().
virtual const Evaluateur_PolyMAC& Iterateur_PolyMAC_base::evaluateur () const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
const Type_info * Iterateur_PolyMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Iterateur_PolyMAC_base.cpp.
virtual int Iterateur_PolyMAC_base::impr (Sortie & os) const [pure virtual]
Implemented in T_It_PolyMAC_Elem< _TYPE_ >.
Referenced by Iterateur_PolyMAC::impr().
const Type_info * Iterateur_PolyMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Iterateur_PolyMAC_base.cpp.
Sortie & Iterateur_PolyMAC_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Iterateur_PolyMAC_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Iterateur_PolyMAC_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 52 of file Iterateur_PolyMAC_base.cpp.
{
  return s ;
}
Iterateur_PolyMAC_base & Iterateur_PolyMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Definition at line 26 of file Iterateur_PolyMAC_base.cpp.
const Iterateur_PolyMAC_base & Iterateur_PolyMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Definition at line 26 of file Iterateur_PolyMAC_base.cpp.
Type_Cl_PolyMAC Iterateur_PolyMAC_base::type_cl (const Cond_lim & la_cl) const [inline]
Definition at line 161 of file Iterateur_PolyMAC_base.h.
References echange_externe_impose, echange_global_impose, entree_fluide, nouvelle_Cl_PolyMAC, nscbc, paroi, paroi_adiabatique, paroi_defilante, paroi_fixe, periodique, scalaire_impose_paroi, sortie_libre, sub_type, symetrie, and Deriv_Cond_lim_base::valeur().
Referenced by Iterateur_PolyMAC::type_cl().
{
  Type_Cl_PolyMAC retour=nouvelle_Cl_PolyMAC;
  if ( sub_type(Symetrie,la_cl.valeur()) ) retour=symetrie;
  else if ( sub_type(Neumann_sortie_libre, la_cl.valeur()) ) retour=sortie_libre;
  else if ( sub_type(Dirichlet_entree_fluide, la_cl.valeur()) ) retour=entree_fluide;
  else if ( sub_type(Dirichlet_paroi_fixe, la_cl.valeur()) ) retour=paroi_fixe;
  else if ( sub_type(Dirichlet_paroi_defilante, la_cl.valeur()) ) retour=paroi_defilante;
  else if ( sub_type(Neumann_paroi_adiabatique, la_cl.valeur()) ) retour=paroi_adiabatique;
  else if ( sub_type(Neumann_paroi, la_cl.valeur()) ) retour=paroi;
  else if ( sub_type(Echange_externe_impose, la_cl.valeur()) ) retour=echange_externe_impose;
  else if ( sub_type(Echange_global_impose, la_cl.valeur()) ) retour=echange_global_impose;
  else if ( sub_type(Periodique, la_cl.valeur()) ) retour=periodique;
  else if ( sub_type(NSCBC, la_cl.valeur()) ) retour=nscbc;
  else if ( sub_type(Scalaire_impose_paroi, la_cl.valeur()) ) retour=scalaire_impose_paroi;
// else if (sub_type(Nouvelle_Cl_PolyMAC, la_cl.valeur())) retour=nouvelle_Cl_PolyMAC;
  return retour;
}
const Zone_PolyMAC & Iterateur_PolyMAC_base::zone () const [inline]
Definition at line 148 of file Iterateur_PolyMAC_base.h.
References la_zone, and Ref_Zone_PolyMAC::valeur().
Referenced by Iterateur_PolyMAC::zone().
{
  return la_zone.valeur();
}
const Zone_Cl_PolyMAC & Iterateur_PolyMAC_base::zone_Cl () const [inline]
Definition at line 153 of file Iterateur_PolyMAC_base.h.
References la_zcl, and Ref_Zone_Cl_PolyMAC::valeur().
Referenced by Iterateur_PolyMAC::zone_Cl().
{
  return la_zcl.valeur();
}
Member Data Documentation
const Type_info Iterateur_PolyMAC_base::info_obj [static]
Reimplemented from Objet_U.
Definition at line 78 of file Iterateur_PolyMAC_base.h.
Ref_Zone_Cl_PolyMAC Iterateur_PolyMAC_base::la_zcl [protected]
Definition at line 102 of file Iterateur_PolyMAC_base.h.
Referenced by associer(), associer_zone_cl_dis(), and zone_Cl().
Ref_Zone_PolyMAC Iterateur_PolyMAC_base::la_zone [protected]
Definition at line 101 of file Iterateur_PolyMAC_base.h.
Referenced by associer(), and zone().
Ref_Operateur_base Iterateur_PolyMAC_base::op_base [protected]
Definition at line 103 of file Iterateur_PolyMAC_base.h.
Referenced by associer().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Conv_iterateur/Iterateur_PolyMAC_base.h
src/PolyMAC/Operateurs/Conv_iterateur/Iterateur_PolyMAC_base.cpp