TRUST: Milieu_composite Class Reference
Milieu_composite Class Reference
Classe Milieu_composite
Cette classe represente un fluide reel ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
#include <Milieu_composite.h>
Public Member Functions
Milieu_composite ()
~Milieu_composite ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void preparer_calcul () override
void associer_equation (const Equation_base *eqn) const override
bool has_interface (int k, int l) const
Interface_base & get_interface (int k, int l) const
bool has_saturation (int k, int l) const
Saturation_base & get_saturation (int k, int l) const
void abortTimeStep () override
bool initTimeStep (double dt) override
int check_unknown_range () const override
const Fluide_base & get_medium_for_incompressible () const
Public Member Functions inherited from Fluide_base
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Milieu_composite & self_cast (Objet_U &)
static const Milieu_composite & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
List_Fluide_base fluides
Public Attributes inherited from Milieu_base
int id_composite = -1
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void mettre_a_jour_tabs ()
std::pair< std::string, int > check_fluid_name (const Nom &name)
Protected Member Functions inherited from Fluide_base
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Member Functions
static void calculer_masse_volumique (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
static void calculer_energie_interne (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
static void calculer_enthalpie (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Protected Member Functions inherited from Fluide_base
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Protected Attributes
Champ_Fonc rho_m
Champ_Fonc h_m
std::vector< std::vector< Interface_base * > > tab_interface
std::map< std::string, std::set< int > > phases_melange
double t_init_
Protected Attributes inherited from Fluide_base
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Additional Inherited Members
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Detailed Description
Classe Milieu_composite
Cette classe represente un fluide reel ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
Definition at line 41 of file Milieu_composite.h.
Constructor & Destructor Documentation
Milieu_composite()
Milieu_composite::Milieu_composite ()
Definition at line 27 of file Milieu_composite.cpp.
~Milieu_composite()
Milieu_composite::~Milieu_composite ()
Definition at line 27 of file Milieu_composite.cpp.
Member Function Documentation
abortTimeStep()
void Milieu_composite::abortTimeStep () override virtual
Reimplemented from Milieu_base.
Definition at line 395 of file Milieu_composite.cpp.
{
  Fluide_base::abortTimeStep();
  if (e_int.non_nul()) e_int->abortTimeStep();
  if (h.non_nul()) h->abortTimeStep();
}
References Milieu_base::abortTimeStep(), Fluide_base::e_int, Fluide_base::h, and O_U_Ptr::non_nul().
associer_equation()
void Milieu_composite::associer_equation (const Equation_base * eqn) const override virtual
Reimplemented from Milieu_base.
Definition at line 286 of file Milieu_composite.cpp.
{
  Fluide_base::associer_equation(eqn);
// on fait suivre aux milieux sous-jacents (les fluide_reel en ont besoin!)
  for (int i = 0; i < fluides.size(); i++)
    fluides[i].associer_equation(eqn);
}
References Milieu_base::associer_equation(), associer_equation(), fluides, and liste::size().
Referenced by associer_equation().
calculer_energie_interne()
void Milieu_composite::calculer_energie_interne (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 335 of file Milieu_composite.cpp.
{
  const Milieu_composite& mil = ref_cast(Milieu_composite, obj);
  int i, Ni = val.dimension_tot(0), Nb = bval.dimension_tot(0), n, N = mil.fluides.size();
  std::vector<const DoubleTab *> split(N);
  for (n = 0; n < N; n++) split[n] = &mil.fluides[n].energie_interne().valeurs();
  for (i = 0; i < Ni; i++)
    for (n = 0; n < N; n++) val(i, n) = (*split[n])(i * (split[n]->dimension(0) > 1), 0);
  std::vector<DoubleTab> bsplit(N);
  for (n = 0; n < N; n++) bsplit[n] = mil.fluides[n].energie_interne().valeur_aux_bords();
  for (i = 0; i < Nb; i++)
    for (n = 0; n < N; n++) bval(i, n) = bsplit[n](i * (split[n]->dimension(0) > 1), 0);
  /* derivees */
  std::vector<const tabs_t *> split_der(N);
  for (n = 0; n < N; n++) split_der[n] = sub_type(Champ_Inc_base, mil.fluides[n].energie_interne()) ? &ref_cast(Champ_Inc_base, mil.fluides[n].energie_interne()).derivees() : NULL;
  std::set<std::string> noms_der;
  for (n = 0; n < N; n++)
    if (split_der[n])
      for (auto &&n_d : *split_der[n]) noms_der.insert(n_d.first);
  for (auto &&nom : noms_der)
    {
      for (n = 0; n < N; n++) split[n] = split_der[n] && split_der[n]->count(nom) ? &split_der[n]->at(nom) : NULL;
      DoubleTab& der = deriv[nom];
      for (der.resize(Ni, N), i = 0; i < Ni; i++)
        for (n = 0; n < N; n++) der(i, n) = split[n] ? (*split[n])(i * (split[n]->dimension(0) > 1)) : 0;
    }
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), fluides, ref_cast, TRUSTTab< _TYPE_ >::resize(), liste::size(), and sub_type.
Referenced by initialiser().
calculer_enthalpie()
void Milieu_composite::calculer_enthalpie (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 365 of file Milieu_composite.cpp.
{
  const Milieu_composite& mil = ref_cast(Milieu_composite, obj);
  int i, Ni = val.dimension_tot(0), Nb = bval.dimension_tot(0), n, N = mil.fluides.size();
  std::vector<const DoubleTab *> split(N);
  for (n = 0; n < N; n++) split[n] = &mil.fluides[n].enthalpie().valeurs();
  for (i = 0; i < Ni; i++)
    for (n = 0; n < N; n++) val(i, n) = (*split[n])(i * (split[n]->dimension(0) > 1), 0);
  std::vector<DoubleTab> bsplit(N);
  for (n = 0; n < N; n++) bsplit[n] = mil.fluides[n].enthalpie().valeur_aux_bords();
  for (i = 0; i < Nb; i++)
    for (n = 0; n < N; n++) bval(i, n) = bsplit[n](i * (split[n]->dimension(0) > 1), 0);
  /* derivees */
  std::vector<const tabs_t *> split_der(N);
  for (n = 0; n < N; n++) split_der[n] = sub_type(Champ_Inc_base, mil.fluides[n].enthalpie()) ? &ref_cast(Champ_Inc_base, mil.fluides[n].enthalpie()).derivees() : NULL;
  std::set<std::string> noms_der;
  for (n = 0; n < N; n++)
    if (split_der[n])
      for (auto &&n_d : *split_der[n]) noms_der.insert(n_d.first);
  for (auto &&nom : noms_der)
    {
      for (n = 0; n < N; n++) split[n] = split_der[n] && split_der[n]->count(nom) ? &split_der[n]->at(nom) : NULL;
      DoubleTab& der = deriv[nom];
      for (der.resize(Ni, N), i = 0; i < Ni; i++)
        for (n = 0; n < N; n++) der(i, n) = split[n] ? (*split[n])(i * (split[n]->dimension(0) > 1)) : 0;
    }
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), fluides, ref_cast, TRUSTTab< _TYPE_ >::resize(), liste::size(), and sub_type.
Referenced by initialiser().
calculer_masse_volumique()
void Milieu_composite::calculer_masse_volumique (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 301 of file Milieu_composite.cpp.
{
  const Milieu_composite& mil = ref_cast(Milieu_composite, obj);
  const Zone_VF& zvf = ref_cast(Zone_VF, mil.equation_.begin()->second->zone_dis().valeur());
  int i, Ni = val.dimension_tot(0), Nb = bval.dimension_tot(0), n, N = mil.fluides.size();
  std::vector<const DoubleTab *> split(N);
  for (n = 0; n < N; n++) split[n] = &mil.fluides[n].masse_volumique().valeurs();
  for (i = 0; i < Ni; i++)
    for (n = 0; n < N; n++) val(i, n) = (*split[n])(i * (split[n]->dimension(0) > 1), 0);
  std::vector<DoubleTab> bsplit(N);
  for (n = 0; n < N; n++)
    if (mil.fluides[n].masse_volumique()->a_une_zone_dis_base())
      bsplit[n] = mil.fluides[n].masse_volumique()->valeur_aux_bords();
    else bsplit[n].resize(bval.dimension_tot(0), 1), mil.fluides[n].masse_volumique()->valeur_aux(zvf.xv_bord(), bsplit[n]);
  for (i = 0; i < Nb; i++)
    for (n = 0; n < N; n++) bval(i, n) = bsplit[n](i * (split[n]->dimension(0) > 1), 0);
  /* derivees */
  std::vector<const tabs_t *> split_der(N);
  for (n = 0; n < N; n++) split_der[n] = sub_type(Champ_Inc_base, mil.fluides[n].masse_volumique().valeur()) ? &ref_cast(Champ_Inc_base, mil.fluides[n].masse_volumique().valeur()).derivees() : NULL;
  std::set<std::string> noms_der;
  for (n = 0; n < N; n++)
    if (split_der[n])
      for (auto &&n_d : *split_der[n]) noms_der.insert(n_d.first);
  for (auto &&nom : noms_der)
    {
      for (n = 0; n < N; n++) split[n] = split_der[n] && split_der[n]->count(nom) ? &split_der[n]->at(nom) : NULL;
      DoubleTab& der = deriv[nom];
      for (der.resize(Ni, N), i = 0; i < Ni; i++)
        for (n = 0; n < N; n++) der(i, n) = split[n] ? (*split[n])(i * (split[n]->dimension(0) > 1)) : 0;
    }
}
References Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Milieu_base::equation_, fluides, ref_cast, TRUSTTab< _TYPE_ >::resize(), liste::size(), sub_type, List_Fluide_base::valeur(), and Zone_VF::xv_bord().
Referenced by initialiser().
check_fluid_name()
std::pair< std::string, int > Milieu_composite::check_fluid_name (const Nom & name) protected
Definition at line 82 of file Milieu_composite.cpp.
{
  int phase = name.finit_par("gaz");
  Nom espece = phase ? name.getPrefix("_gaz") : name.getPrefix("_liquide");
  return std::make_pair(espece.getString(), phase);
}
References Nom::finit_par(), Nom::getPrefix(), and Nom::getString().
Referenced by readOn().
check_unknown_range()
int Milieu_composite::check_unknown_range () const override virtual
Reimplemented from Milieu_base.
Definition at line 294 of file Milieu_composite.cpp.
{
  int ok = 1;
  for (int i = 0; ok && i < fluides.size(); i++) ok &= fluides[i].check_unknown_range(); //chaque fluide controle
  return ok;
}
References check_unknown_range(), fluides, and liste::size().
Referenced by check_unknown_range().
cree_instance()
Objet_U * Milieu_composite::cree_instance () static
Definition at line 27 of file Milieu_composite.cpp.
discretiser()
void Milieu_composite::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_base.
Definition at line 138 of file Milieu_composite.cpp.
{
  Cerr << "Composite medium discretization." << finl;
  const int N = fluides.size(), nc = pb.equation(0).inconnue()->nb_valeurs_temporelles();
  const Zone_dis_base& zone_dis = pb.equation(0).zone_dis();
  const double temps = pb.schema_temps().temps_courant();
// Fluide_base::discretiser(pb, dis);
  for (int n = 0; n < N; n++)
    fluides[n].discretiser(pb, dis);
  /* masse volumique, energie interne, enthalpie : champ_inc */
  Champ_Inc rho_inc, ei_inc, h_inc;
  dis.discretiser_champ("champ_elem", zone_dis,       "masse_volumique",    "kg/m^3", N, nc, temps, rho_inc);
  dis.discretiser_champ("champ_elem", zone_dis,       "energie_interne",     "J/m^3", N, nc, temps, ei_inc);
  dis.discretiser_champ("champ_elem", zone_dis,             "enthalpie",     "J/m^3", N, nc, temps, h_inc);
  rho = rho_inc, e_int = ei_inc, h = h_inc;
  /* autres champs : champ_fonc */
  dis.discretiser_champ("champ_elem", zone_dis,   "viscosite_dynamique",    "kg/m/s", N, temps,       mu);
  dis.discretiser_champ("champ_elem", zone_dis, "viscosite_cinematique",      "m2/s", N, temps,       nu);
  dis.discretiser_champ("champ_elem", zone_dis,           "diffusivite",      "m2/s", N, temps,    alpha);
  dis.discretiser_champ("champ_elem", zone_dis,          "conductivite",     "W/m/K", N, temps,   lambda);
  dis.discretiser_champ("champ_elem", zone_dis,  "capacite_calorifique",    "J/kg/K", N, temps,       Cp);
  /* champs de quantites melange */
  for (auto &&kv : phases_melange)
    {
      dis.discretiser_champ("champ_elem", zone_dis,   Nom("masse_volumique_") + kv.first + "_melange", "kg/m^3", 1, temps, rho_m);
      dis.discretiser_champ("champ_elem", zone_dis,         Nom("enthalpie_") + kv.first + "_melange",  "J/m^3", 1, temps,   h_m);
      champs_compris_.ajoute_champ(rho_m);
      champs_compris_.ajoute_champ(h_m);
    }
  champs_compris_.ajoute_champ(rho);
  champs_compris_.ajoute_champ(mu.valeur());
  champs_compris_.ajoute_champ(nu.valeur());
  champs_compris_.ajoute_champ(alpha.valeur());
  champs_compris_.ajoute_champ(lambda.valeur());
  champs_compris_.ajoute_champ(Cp.valeur());
  champs_compris_.ajoute_champ(e_int);
  champs_compris_.ajoute_champ(h);
}
References Champs_compris::ajoute_champ(), Milieu_base::alpha, Cerr, Milieu_base::champs_compris_, Milieu_base::Cp, discretiser(), Discretisation_base::discretiser_champ(), Fluide_base::e_int, Probleme_base::equation(), finl, fluides, Fluide_base::h, h_m, Equation_base::inconnue(), Milieu_base::lambda, Fluide_base::mu, Champ_Inc::nb_valeurs_temporelles(), Fluide_base::nu, phases_melange, Milieu_base::rho, rho_m, Probleme_base::schema_temps(), liste::size(), Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), and Equation_base::zone_dis().
Referenced by discretiser().
duplique()
int Milieu_composite::duplique () const override virtual
Reimplemented from Fluide_base.
Definition at line 27 of file Milieu_composite.cpp.
get_info()
const Type_info * Milieu_composite::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_base.
Definition at line 27 of file Milieu_composite.cpp.
get_interface()
Interface_base & Milieu_composite::get_interface (int k, int l) const
Definition at line 96 of file Milieu_composite.cpp.
{
  return *(tab_interface[k][l]);
}
References tab_interface.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), and Portance_interfaciale_PolyMAC_P0::ajouter_blocs().
get_medium_for_incompressible()
const Fluide_base & Milieu_composite::get_medium_for_incompressible () const inline
Definition at line 60 of file Milieu_composite.h.
{ return fluides[0]; }
References fluides.
get_saturation()
Saturation_base & Milieu_composite::get_saturation (int k, int l) const
Definition at line 107 of file Milieu_composite.cpp.
{
  return ref_cast(Saturation_base, *(tab_interface[k][l]));
}
References ref_cast, and tab_interface.
Referenced by Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs().
has_interface()
bool Milieu_composite::has_interface (int k, int l) const
Definition at line 90 of file Milieu_composite.cpp.
{
  if (tab_interface[k][l]) return true;
  return false;
}
References tab_interface.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), and Portance_interfaciale_PolyMAC_P0::ajouter_blocs().
has_saturation()
bool Milieu_composite::has_saturation (int k, int l) const
Definition at line 101 of file Milieu_composite.cpp.
{
  if (tab_interface[k][l] && sub_type(Saturation_base, *tab_interface[k][l])) return true;
  return false;
}
References sub_type, and tab_interface.
Referenced by Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs().
info()
const Type_info * Milieu_composite::info () static
Definition at line 27 of file Milieu_composite.cpp.
initialiser()
int Milieu_composite::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Fluide_base.
Definition at line 117 of file Milieu_composite.cpp.
{
  for (int i = 0; i < fluides.size(); i++)
    fluides[i].initialiser(temps);
  const Equation_base& eqn = equation("temperature");
  Champ_Inc_base& ch_rho = ref_cast(Champ_Inc_base, rho.valeur()),
                  &ch_e   = ref_cast(Champ_Inc_base, e_int.valeur()),
                   &ch_h   = ref_cast(Champ_Inc_base, h.valeur());
  ch_rho.associer_eqn(eqn), ch_rho.init_champ_calcule(*this, calculer_masse_volumique);
  ch_e.associer_eqn(eqn),   ch_e.init_champ_calcule(*this, calculer_energie_interne);
  ch_h.associer_eqn(eqn),   ch_h.init_champ_calcule(*this, calculer_enthalpie);
  t_init_ = temps;
  return 1;
}
References Champ_Inc_base::associer_eqn(), calculer_energie_interne(), calculer_enthalpie(), calculer_masse_volumique(), Fluide_base::e_int, Milieu_base::equation(), fluides, Fluide_base::h, Champ_Inc_base::init_champ_calcule(), initialiser(), ref_cast, Milieu_base::rho, liste::size(), t_init_, and Deriv_Champ_base::valeur().
Referenced by initialiser().
initTimeStep()
bool Milieu_composite::initTimeStep (double dt) override virtual
Reimplemented from Fluide_base.
Definition at line 402 of file Milieu_composite.cpp.
{
  for (int i = 0; i < fluides.size(); i++)
    fluides[i].initTimeStep(dt);
  if (!equation_.size()) return true; //pas d'equation associee -> ???
  const Schema_Temps_base& sch = equation_.begin()->second->schema_temps(); //on recupere le schema en temps par la 1ere equation
  /* champs dont on doit creer des cases */
  std::vector<Champ_Inc_base *> vch;
  if (rho.non_nul() && sub_type(Champ_Inc_base, rho.valeur())) vch.push_back(&ref_cast(Champ_Inc_base, rho.valeur()));
  if (e_int.non_nul() && sub_type(Champ_Inc_base, e_int.valeur())) vch.push_back(&ref_cast(Champ_Inc_base, e_int.valeur()));
  if (h.non_nul() && sub_type(Champ_Inc_base, h.valeur())) vch.push_back(&ref_cast(Champ_Inc_base, h.valeur()));
  for (auto &pch : vch)
    for (int i = 1; i <= sch.nb_valeurs_futures(); i++)
      pch->changer_temps_futur(sch.temps_futur(i), i), pch->futur(i) = pch->valeurs();
  return true;
}
References Fluide_base::e_int, Milieu_base::equation_, fluides, Fluide_base::h, initTimeStep(), Schema_Temps_base::nb_valeurs_futures(), O_U_Ptr::non_nul(), ref_cast, Milieu_base::rho, liste::size(), sub_type, Schema_Temps_base::temps_futur(), and Deriv_Champ_base::valeur().
Referenced by initTimeStep().
mettre_a_jour()
void Milieu_composite::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Reimplemented from Fluide_base.
Definition at line 183 of file Milieu_composite.cpp.
{
  for (int i = 0; i < fluides.size(); i++)
    fluides[i].mettre_a_jour(temps);
  rho.mettre_a_jour(temps);
  e_int.mettre_a_jour(temps);
  h.mettre_a_jour(temps);
  mu.mettre_a_jour(temps);
  nu.mettre_a_jour(temps);
  lambda.mettre_a_jour(temps);
  alpha.mettre_a_jour(temps);
  Cp.mettre_a_jour(temps);
  if (rho_m.non_nul()) rho_m.mettre_a_jour(temps);
  if (h_m.non_nul()) h_m.mettre_a_jour(temps);
  mettre_a_jour_tabs();
// Fluide_base::mettre_a_jour(temps);
}
References Milieu_base::alpha, Milieu_base::Cp, Fluide_base::e_int, fluides, Fluide_base::h, h_m, Milieu_base::lambda, Champ_Don::mettre_a_jour(), mettre_a_jour(), Champ::mettre_a_jour(), Champ_Fonc::mettre_a_jour(), mettre_a_jour_tabs(), Fluide_base::mu, O_U_Ptr::non_nul(), Fluide_base::nu, Milieu_base::rho, rho_m, and liste::size().
Referenced by mettre_a_jour(), and preparer_calcul().
mettre_a_jour_tabs()
void Milieu_composite::mettre_a_jour_tabs () protected
Definition at line 202 of file Milieu_composite.cpp.
{
  const int N = fluides.size();
  /* viscosite dynamique */
  {
    DoubleTab& tab = mu.valeurs();
    const int Nl = mu.valeurs().dimension_tot(0);
    for (int n = 0; n < N; n++)
      {
        const Champ_base& ch_n = fluides[n].viscosite_dynamique();
        const int cch = sub_type(Champ_Uniforme, ch_n);
        for (int i = 0; i < Nl; i++) tab(i, n) = ch_n.valeurs()(!cch * i, 0);
      }
  }
  /* viscosite cinematique */
  {
    DoubleTab& tab = nu.valeurs();
    const int Nl = nu.valeurs().dimension_tot(0);
    for (int n = 0; n < N; n++)
      {
        const Champ_base& ch_n = fluides[n].viscosite_cinematique();
        const int cch = sub_type(Champ_Uniforme, ch_n);
        for (int i = 0; i < Nl; i++) tab(i, n) = ch_n.valeurs()(!cch * i, 0);
      }
  }
  /* diffusivite */
  {
    DoubleTab& tab = alpha.valeurs();
    const int Nl = alpha.valeurs().dimension_tot(0);
    for (int n = 0; n < N; n++)
      {
        const Champ_base& ch_n = fluides[n].diffusivite();
        const int cch = sub_type(Champ_Uniforme, ch_n);
        for (int i = 0; i < Nl; i++) tab(i, n) = ch_n.valeurs()(!cch * i, 0);
      }
  }
  /* conductivite */
  {
    DoubleTab& tab = lambda.valeurs();
    const int Nl = lambda.valeurs().dimension_tot(0);
    for (int n = 0; n < N; n++)
      {
        const Champ_base& ch_n = fluides[n].conductivite();
        const int cch = sub_type(Champ_Uniforme, ch_n);
        for (int i = 0; i < Nl; i++) tab(i, n) = ch_n.valeurs()(!cch * i, 0);
      }
  }
  /* capacite calorifique */
  {
    DoubleTab& tab = Cp.valeurs();
    const int Nl = Cp.valeurs().dimension_tot(0);
    for (int n = 0; n < N; n++)
      {
        const Champ_base& ch_n = fluides[n].capacite_calorifique();
        const int cch = sub_type(Champ_Uniforme, ch_n);
        for (int i = 0; i < Nl; i++) tab(i, n) = ch_n.valeurs()(!cch * i, 0);
      }
  }
  if (rho_m.non_nul() && h_m.non_nul())
    {
      DoubleTab& trm = rho_m.valeurs(), &thm = h_m.valeurs();
      trm = 0, thm = 0;
      const Equation_base& eqn = equation("alpha");
      const DoubleTab& a = eqn.inconnue().valeurs(),
                       &r = rho.valeurs(), &ent = h.valeurs();
      const Nom ph = (rho_m.le_nom().getSuffix("masse_volumique_")).getPrefix("_melange");
      const int Nl = rho_m.valeurs().dimension_tot(0);
// masse volumique melange
      for (auto n : phases_melange[ph.getString()])
        for (int i = 0; i < Nl; i++) trm(i) += a(i, n) * r(i, n);
// enthalpie melange
      for (auto n : phases_melange[ph.getString()])
        for (int i = 0; i < Nl; i++) thm(i) += a(i, n) * r(i, n) * ent(i, n);
      for (int i = 0; i < Nl; i++) thm(i) /= trm(i);
    }
}
References Milieu_base::alpha, Milieu_base::Cp, TRUSTTab< _TYPE_ >::dimension_tot(), Milieu_base::equation(), fluides, Nom::getString(), Nom::getSuffix(), Fluide_base::h, h_m, Equation_base::inconnue(), Milieu_base::lambda, O_U_Ptr::le_nom(), Fluide_base::mu, O_U_Ptr::non_nul(), Fluide_base::nu, phases_melange, Milieu_base::rho, rho_m, liste::size(), sub_type, Champ::valeurs(), Champ_Don::valeurs(), Champ_Fonc::valeurs(), Champ_Inc::valeurs(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour().
preparer_calcul()
void Milieu_composite::preparer_calcul (void) override virtual
Reimplemented from Milieu_base.
Definition at line 133 of file Milieu_composite.cpp.
{
  mettre_a_jour(t_init_);
}
References mettre_a_jour(), and t_init_.
printOn()
Sortie & Milieu_composite::printOn (Sortie & os) const override protected virtual
Ecrit les proprietes du fluide sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Fluide_base.
Definition at line 112 of file Milieu_composite.cpp.
{
  return os;
}
readOn()
Entree & Milieu_composite::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< "Interface_[...]_[...]"
< pour loi en e = e0 + cp * (T - T0)
Reimplemented from Fluide_base.
Definition at line 29 of file Milieu_composite.cpp.
{
  int i = 0;
  std::vector<std::pair<std::string, int>> especes;
  Nom mot;
  is >> mot;
  if (mot != "{") Cerr << "Milieu_composite : { expected instead of " << mot << finl, Process::exit();
  for (is >> mot; mot != "}"; is >> mot)
    {
      Cerr << "Milieu_composite : ajout de " << mot << " ... ";
      if (Interprete::objet_existant(mot))
        {
          Fluide_base& fluide = ref_cast(Fluide_base, Interprete::objet(mot));
          fluide.set_id_composite(i++);
          fluides.add(fluide);
          especes.push_back(check_fluid_name(fluide.le_nom()));
          Cerr << "ok!" << finl;
        }
      else Process::exit("not found!");
    }
// interfaces
  int N = fluides.size();
  for (int n = 0; n < N; n++)
    {
      std::vector<Interface_base *> inter;
      for (int m = 0; m < N; m++)
        {
          const std::string espn = especes[n].first, espm = especes[m].first;
          const int pn = especes[n].second, pm = especes[m].second;
          Nom mot_inter = Nom((std::string("interface_") + especes[n].first + "_" + especes[m].first)), //!< "Interface_[...]_[...]"
              mot_sat   = Nom((std::string("saturation_") + especes[n].first)); //"Saturation_[...]"
          if ( pn != pm && (Interprete::objet_existant(mot_inter) || (espn == espm &&Interprete::objet_existant(mot_sat))))
            {
              Cerr << "Interface between fluid " << n << " : " << fluides[n].le_nom() << " and " << m << " : " << fluides[m].le_nom() << finl;
              phases_melange[especes[n].first].insert(n), phases_melange[especes[n].first].insert(m);
              inter.push_back(&ref_cast(Interface_base, Interprete::objet(Interprete::objet_existant(mot_sat) ? mot_sat : mot_inter)));
              const Saturation_base *sat = sub_type(Saturation_base, *inter.back()) ? &ref_cast(Saturation_base, *inter.back()) : NULL;
              if (sat && sat->get_Pref() > 0) //!< pour loi en e = e0 + cp * (T - T0)
                {
                  const double hn = pn ? sat->Hvs(sat->get_Pref()) : sat->Hls(sat->get_Pref()),
                               hm = pm ? sat->Hvs(sat->get_Pref()) : sat->Hls(sat->get_Pref()),
                               T0 = sat->Tsat(sat->get_Pref());
                  fluides[n].set_h0_T0(hn, T0), fluides[m].set_h0_T0(hm, T0);
                }
            }
          else inter.push_back(NULL);
        }
      tab_interface.push_back(inter);
    }
  return is;
}
References List_Fluide_base::add(), Cerr, check_fluid_name(), Process::exit(), finl, fluides, Saturation_base::get_Pref(), Saturation_base::Hls(), Saturation_base::Hvs(), Objet_U::le_nom(), Milieu_base::le_nom(), Interprete::objet(), Interprete::objet_existant(), phases_melange, ref_cast, Milieu_base::set_id_composite(), liste::size(), sub_type, tab_interface, and Saturation_base::Tsat().
self_cast() [1/2]
const Milieu_composite & Milieu_composite::self_cast (const Objet_U & r) static
Definition at line 27 of file Milieu_composite.cpp.
self_cast() [2/2]
Milieu_composite & Milieu_composite::self_cast (Objet_U & r) static
Definition at line 27 of file Milieu_composite.cpp.
taille_memoire()
unsigned Milieu_composite::taille_memoire () const override virtual
Reimplemented from Fluide_base.
Definition at line 27 of file Milieu_composite.cpp.
Member Data Documentation
fluides
List_Fluide_base Milieu_composite::fluides
Definition at line 59 of file Milieu_composite.h.
Referenced by associer_equation(), calculer_energie_interne(), calculer_enthalpie(), calculer_masse_volumique(), check_unknown_range(), discretiser(), get_medium_for_incompressible(), initialiser(), initTimeStep(), mettre_a_jour(), mettre_a_jour_tabs(), and readOn().
h_m
Champ_Fonc Milieu_composite::h_m protected
Definition at line 63 of file Milieu_composite.h.
Referenced by discretiser(), mettre_a_jour(), and mettre_a_jour_tabs().
info_obj
const Type_info Milieu_composite::info_obj static
Definition at line 43 of file Milieu_composite.h.
phases_melange
std::map<std::string, std::set<int> > Milieu_composite::phases_melange protected
Definition at line 70 of file Milieu_composite.h.
Referenced by discretiser(), mettre_a_jour_tabs(), and readOn().
rho_m
Champ_Fonc Milieu_composite::rho_m protected
Definition at line 63 of file Milieu_composite.h.
Referenced by discretiser(), mettre_a_jour(), and mettre_a_jour_tabs().
t_init_
double Milieu_composite::t_init_ protected
Definition at line 71 of file Milieu_composite.h.
Referenced by initialiser(), and preparer_calcul().
tab_interface
std::vector<std::vector<Interface_base *> > Milieu_composite::tab_interface protected
Definition at line 69 of file Milieu_composite.h.
Referenced by get_interface(), get_saturation(), has_interface(), has_saturation(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Milieu/Milieu_composite.h
src/ThHyd/Multiphase/Milieu/Milieu_composite.cpp