TRUST: Source_Generique_VDF_Face Class Reference
Source_Generique_VDF_Face Class Reference
class Source_Generique_VDF_Face<br>.SECTION voir Source_Generique_base
#include <Source_Generique_VDF_Face.h>
Public Member Functions
Source_Generique_VDF_Face ()
~Source_Generique_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Nom localisation_source ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_Generique_VDF_Face & self_cast (Objet_U &)
static const
Source_Generique_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zcl_VDF
Detailed Description
class Source_Generique_VDF_Face<br>.SECTION voir Source_Generique_base
Definition at line 34 of file Source_Generique_VDF_Face.h.
Constructor & Destructor Documentation
Source_Generique_VDF_Face::Source_Generique_VDF_Face ()
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
Source_Generique_VDF_Face::~Source_Generique_VDF_Face ()
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Source_Generique_VDF_Face::ajouter (DoubleTab & resu) const [virtual]
Implements Source_Generique_base.
Definition at line 44 of file Source_Generique_VDF_Face.cpp.
References Source_Generique_base::ch_source_, DoubleVect::echange_espace_virtuel(), Cond_lim::frontiere_dis(), la_zcl_VDF, la_zone_VDF, Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Champ_Proto::valeurs().
{
  Champ espace_stockage;
  const Champ_base& champ_calc = ch_source_->get_champ(espace_stockage);
  const DoubleTab& valeurs_calc = champ_calc.valeurs();
  int nb_faces = la_zone_VDF->nb_faces();
  const DoubleVect& vol_entrelaces = la_zone_VDF->volumes_entrelaces();
  const DoubleVect& poro_face = la_zone_VDF->porosite_face();
  int nb_front_cl = la_zone_VDF->nb_front_Cl();
  int premiere_face_interne = la_zone_VDF->premiere_face_int();
  int num_face;
  for (int num_cl =0; num_cl<nb_front_cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl_VDF->les_conditions_limites(num_cl);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      if ((sub_type(Dirichlet,la_cl.valeur()))
          ||
          (sub_type(Dirichlet_homogene,la_cl.valeur()))
         )
        ;
      else
        for (num_face=ndeb; num_face<nfin; num_face++)
          {
            resu(num_face) += valeurs_calc(num_face)*vol_entrelaces(num_face)*poro_face(num_face);
          }
    }
  for (num_face=premiere_face_interne; num_face<nb_faces; num_face++)
    resu(num_face) += valeurs_calc(num_face)*vol_entrelaces(num_face)*poro_face(num_face);
  resu.echange_espace_virtuel();
  return resu;
}
void Source_Generique_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zcl_dis) [virtual]
Implements Source_Generique_base.
Definition at line 82 of file Source_Generique_VDF_Face.cpp.
References la_zcl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_VDF = ref_cast(Zone_VDF,zone_dis.valeur());
  la_zcl_VDF = ref_cast(Zone_Cl_VDF,zcl_dis.valeur());
}
Objet_U * Source_Generique_VDF_Face::cree_instance () [static]
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
int Source_Generique_VDF_Face::duplique () const [virtual]
Implements Source_Generique_base.
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
const Type_info * Source_Generique_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
const Type_info * Source_Generique_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
Nom Source_Generique_VDF_Face::localisation_source () [virtual]
Implements Source_Generique_base.
Definition at line 89 of file Source_Generique_VDF_Face.cpp.
{
  return "faces";
}
Sortie & Source_Generique_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 33 of file Source_Generique_VDF_Face.cpp.
References Objet_U::que_suis_je().
{
  return os << que_suis_je() ;
}
Entree & Source_Generique_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Generique_base.
Definition at line 38 of file Source_Generique_VDF_Face.cpp.
{
  Source_Generique_base::readOn(is);
  return is;
}
Source_Generique_VDF_Face & Source_Generique_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
const Source_Generique_VDF_Face & Source_Generique_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Generique_base.
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
unsigned Source_Generique_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Source_Generique_VDF_Face.cpp.
Member Data Documentation
const Type_info Source_Generique_VDF_Face::info_obj [static]
Reimplemented from Source_Generique_base.
Definition at line 37 of file Source_Generique_VDF_Face.h.
Ref_Zone_Cl_VDF Source_Generique_VDF_Face::la_zcl_VDF [protected]
Definition at line 48 of file Source_Generique_VDF_Face.h.
Referenced by ajouter(), and associer_zones().
Ref_Zone_VDF Source_Generique_VDF_Face::la_zone_VDF [protected]
Definition at line 47 of file Source_Generique_VDF_Face.h.
Referenced by ajouter(), and associer_zones().
The documentation for this class was generated from the following files:
src/VDF/Sources/Source_Generique_VDF_Face.h
src/VDF/Sources/Source_Generique_VDF_Face.cpp