TRUST: DoubleTab_parts Class Reference
DoubleTab_parts Class Reference
#include <ConstDoubleTab_parts.h>
Public Member Functions
DoubleTab_parts ()
DoubleTab_parts (DoubleVect &)
void initialize (DoubleVect &)
void reset ()
DoubleTab & operator[] (int i)
const DoubleTab & operator[] (int i) const
int size () const
Private Member Functions
DoubleTab_parts & operator= (const DoubleTab_parts &)
Interdit !
DoubleTab_parts (const DoubleTab_parts &)
Interdit !
Private Attributes
Vect_DoubleTab parts_
Detailed Description
Definition at line 56 of file ConstDoubleTab_parts.h.
Constructor & Destructor Documentation
DoubleTab_parts::DoubleTab_parts () [inline]
Definition at line 59 of file ConstDoubleTab_parts.h.
{};
DoubleTab_parts::DoubleTab_parts (DoubleVect & vect)
Definition at line 181 of file ConstDoubleTab_parts.cpp.
References init_parts(), and parts_.
{
  init_parts(vect, parts_, (DoubleTab*) 0);
}
DoubleTab_parts::DoubleTab_parts (const DoubleTab_parts &) [private]
Interdit !
Definition at line 272 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to copy constructor DoubleTab_parts::DoubleTab_parts(const DoubleTab_parts &) is forbidden" << finl;
  Process::exit();
}
Member Function Documentation
void DoubleTab_parts::initialize (DoubleVect & vect)
Definition at line 186 of file ConstDoubleTab_parts.cpp.
References init_parts(), parts_, and reset().
{
  reset();
  init_parts(vect, parts_, (DoubleTab*) 0);
}
DoubleTab_parts & DoubleTab_parts::operator= (const DoubleTab_parts &) [private]
Interdit !
Definition at line 264 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to DoubleTab_parts::operator=(const DoubleTab_parts &) is forbidden" << finl;
  Process::exit();
  return *this;
}
const DoubleTab& DoubleTab_parts::operator[] (int i) const [inline]
Definition at line 70 of file ConstDoubleTab_parts.h.
  {
    return parts_[i];
  }
DoubleTab& DoubleTab_parts::operator[] (int i) [inline]
Definition at line 65 of file ConstDoubleTab_parts.h.
  {
    return parts_[i];
  }
void DoubleTab_parts::reset ()
Definition at line 192 of file ConstDoubleTab_parts.cpp.
References vect_impl::dimensionner_force(), and parts_.
Referenced by initialize().
{
  parts_.dimensionner_force(0);
}
int DoubleTab_parts::size () const [inline]
Definition at line 74 of file ConstDoubleTab_parts.h.
References DoubleVect::size().
Referenced by lecture_special_part2(), PrecondA::preconditionner_(), and SSOR::ssor().
  {
    return parts_.size();
  }
Member Data Documentation
Vect_DoubleTab DoubleTab_parts::parts_ [private]
Definition at line 85 of file ConstDoubleTab_parts.h.
Referenced by DoubleTab_parts(), initialize(), and reset().
The documentation for this class was generated from the following files:
src/Kernel/Math/ConstDoubleTab_parts.h
src/Kernel/Math/ConstDoubleTab_parts.cpp