TRUST: Zone_VDF Class Reference
Zone_VDF Class Reference
class Zone_VDF
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Differences Finis.
La classe porte un certain nombre d'informations concernant les faces
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes apparaissent ensuite
A chaque face on fait correspondre un int qui indique son orientation.
On suppose qu'a l'interieur de chaque famille de faces (bord,joint,interne)
on trouve:
- le bloc des faces d'equation x = cte (faces d'orientation 0)
- le bloc des faces d'equation y = cte (faces d'orientation 1)
- le bloc des faces d'equation z = cte (faces d'orientation 2)
Pour le bloc des faces de bord on conserve les sous-blocs constitues par
les faces d'un meme bord.
On n'a pas besoin d'une numerotation particuliere des elements.
On a introduit la notion d'arete pour le calcul des flux diffusifs et
convectifs dans la conservation de la quantite de mouvement.
Le tableau Qdm contient la connectivite arete/faces. Dans le tableau
Qdm les aretes apparaissent dans l'ordre suivant:
- bloc des aretes joints
- bloc des aretes bord
- bloc des aretes mixtes
- bloc des aretes internes
A l'interieur de chaque bloc les aretes apparaissent dans l'ordre
suivant: aretes XY, aretes XZ et aretes YZ.
#include <Zone_VDF.h>
Public Member Functions
Zone_VDF ()
~Zone_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
appel a Zone_VF::discretiser()
calcul des centres de gravite des elements
remplissage des connectivites elements/faces
on reordonne les connectivites faces/elements
de sorte que el1 est a gauche et el2 a droite.
calcul des porosites volumiques et surfaciques
generation des aretes
calcul des pas du maillage
Faces * creer_faces () override
renvoie un Faces_VDF* !
void reordonner (Faces &) override
reordonne les faces en fonction de l'orientation
calcule les centres de gravite des faces
calcule les surfaces
int nb_faces_X () const
int nb_faces_Y () const
int nb_faces_Z () const
int nb_aretes () const
int nb_aretes_joint () const
int nb_aretes_coin () const
int premiere_arete_coin () const
int nb_aretes_bord () const
int premiere_arete_bord () const
int nb_aretes_mixtes () const
int premiere_arete_mixte () const
int nb_aretes_internes () const
int premiere_arete_interne () const
double h_x () const
double h_y () const
double h_z () const
int Qdm (int num_arete, int) const
int orientation (int) const override
inline DoubleVect& Zone_VDF::porosite_face()
{
return porosite_face_;
}
double face_normales (int, int) const override
double dist_face (int, int, int k) const
double dist_norm (int num_face) const
double dist_norm_bord (int num_face) const
double dist_face_elem0 (int, int) const
Fonction de calcul utilisable uniquement en coordonnees cartesiennes
de la distance entre le centre d'une face et
le centre de face_voisins(face,0)
double dist_face_elem1 (int, int) const
Fonction de calcul utilisable uniquement en coordonnees cartesiennes
de la distance entre le centre d'une face et
le centre de face_voisins(face,1)
double dist_face_axi (int, int, int k) const
double dist_face_period (int, int, int) const
double dist_norm_period (int, double) const
double dist_face_elem0_period (int, int, double) const
double dist_face_elem1_period (int, int, double) const
double dist_norm_axi (int num_face) const
double dist_norm_bord_axi (int num_face) const
double dist_face_elem0_axi (int, int) const
Fonction de calcul utilisable uniquement en coordonnees cylindriques
de la distance entre le centre d'une face et
le centre de face_voisins(face,0)
double dist_face_elem1_axi (int, int) const
Fonction de calcul utilisable uniquement en coordonnees cylindriques
de la distance entre le centre d'une face et le centre
de face_voisins(face,1)
double distance_face (int, int, int k) const
double distance_normale (int num_face) const
double dist_elem (int, int, int) const
double dist_elem_period (int, int, int) const
double dim_elem (int, int) const
double dim_face (int, int) const
double delta_C (int) const
int amont_amont (int, int) const
int face_amont_princ (int, int) const
int face_amont_conj (int, int, int) const
int face_bord_amont (int, int, int) const
Determine la face voisine de notre face
en prevoyant que cette derniere puisse etre de type bord.
int elem_voisin (int, int, int) const
IntVect & orientation ()
inline double Zone_VDF::porosite_face(int i) const
{
return porosite_face_[i];
}
const IntVect & orientation () const override
IntTab & Qdm ()
const IntTab & Qdm () const
void calculer_volumes_entrelaces ()
remplissage des volumes entrelaces
void modifier_pour_Cl (const Conds_lim &cl) override
void creer_elements_fictifs (const Zone_Cl_dis_base &) override
remplit le tableau face_voisins_fictifs_
ne CREE PAS d elts fictifs!!!
DoubleVect & dist_norm_bord (DoubleVect &, const Nom &nom_bord) const
void init_virt_e_map () const
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_VDF & self_cast (Objet_U &)
static const Zone_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
std::map< std::array< int, 2 >, int > virt_e_map
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void remplir_elem_faces () override
void genere_aretes ()
generation des aretes
void calcul_h ()
calcul des pas du maillage
Private Attributes
IntVect orientation_
orientation des faces 0 si face perpendiculaire a l'axe des X 1 si face perpendiculaire a l'axe des Y 2 si face perpendiculaire a l'axe des Z
int nb_faces_X_
nombre de faces perpendiculaires a l'axe des X
int nb_faces_Y_
nombre de faces perpendiculaires a l'axe des Y
int nb_faces_Z_
nombre de faces perpendiculaires a l'axe des Z
int nb_aretes_
nombre d'aretes tous types confondus
int nb_aretes_joint_
nombre d'aretes joint
int nb_aretes_coin_
nombre d'aretes coin
int nb_aretes_bord_
nombre d'aretes bord
int nb_aretes_mixtes_
nombre d'aretes mixtes
int nb_aretes_internes_
nombre d'aretes internes
IntTab Qdm_
connectivites aretes/faces DoubleVect porosite_elem_; // Porosites volumiques pour les volumes de controle de masse DoubleVect porosite_face_; // Porosites surfaciques en masse et volumiques en quantite de mouvement
double h_x_
double h_y_
double h_z_
pas du maillage dans les trois directions d'espace;h_x_ (resp h_y_) est la plus petite distance entre deux centres de faces d'equation X = cte (resp Y= cte)
Additional Inherited Members
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
class Zone_VDF
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Differences Finis.
La classe porte un certain nombre d'informations concernant les faces
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes apparaissent ensuite
A chaque face on fait correspondre un int qui indique son orientation.
On suppose qu'a l'interieur de chaque famille de faces (bord,joint,interne)
on trouve:
- le bloc des faces d'equation x = cte (faces d'orientation 0)
- le bloc des faces d'equation y = cte (faces d'orientation 1)
- le bloc des faces d'equation z = cte (faces d'orientation 2)
Pour le bloc des faces de bord on conserve les sous-blocs constitues par
les faces d'un meme bord.
On n'a pas besoin d'une numerotation particuliere des elements.
On a introduit la notion d'arete pour le calcul des flux diffusifs et
convectifs dans la conservation de la quantite de mouvement.
Le tableau Qdm contient la connectivite arete/faces. Dans le tableau
Qdm les aretes apparaissent dans l'ordre suivant:
- bloc des aretes joints
- bloc des aretes bord
- bloc des aretes mixtes
- bloc des aretes internes
A l'interieur de chaque bloc les aretes apparaissent dans l'ordre
suivant: aretes XY, aretes XZ et aretes YZ.
Definition at line 63 of file Zone_VDF.h.
Constructor & Destructor Documentation
Zone_VDF()
Zone_VDF::Zone_VDF ()
Definition at line 29 of file Zone_VDF.cpp.
~Zone_VDF()
Zone_VDF::~Zone_VDF ()
Definition at line 29 of file Zone_VDF.cpp.
Member Function Documentation
amont_amont()
int Zone_VDF::amont_amont (int num_face, int i) const inline
Definition at line 573 of file Zone_VDF.h.
{
  int k=orientation_[num_face];
  int num_elem = face_voisins_(num_face,i);
  int face = elem_faces_(num_elem,k+i*dimension);
  return face_voisins_(face,i);
}
References Objet_U::dimension, Zone_VF::elem_faces_, Zone_VF::face_voisins_, and orientation_.
Referenced by Eval_Centre_VDF_Elem::amont_amont(), Eval_Centre4_VDF_Elem::amont_amont(), and Eval_Quick_VDF_Elem::amont_amont().
calcul_h()
void Zone_VDF::calcul_h () private
calcul des pas du maillage
Definition at line 593 of file Zone_VDF.cpp.
{
// Calcul de h_x_ , h_y_ et h_z_:
  Zone& zone_geom=zone();
  int nb_poly = zone_geom.nb_elem();
  h_x_ = 1.e30;
  h_y_ = 1.e30;
  h_z_ = 1.e30;
  double deux_pi = M_PI*2.0;
  IntVect numfa(zone_geom.nb_faces_elem());
  if (axi)
    if (dimension == 2)
      {
        double d_teta;
        for (int num_poly=0; num_poly<nb_poly; num_poly++)
          {
            for (int j=0; j<zone_geom.nb_faces_elem(); j++)
              numfa[j] = elem_faces(num_poly,j);
            h_x_ = std::min(h_x_,xv_(numfa[2],0) - xv_(numfa[0],0));
            d_teta = xv_(numfa[3],1) - xv_(numfa[1],1);
            if (d_teta < 0)
              d_teta += deux_pi;
            h_y_ = std::min(h_y_,d_teta*xv_(numfa[1],0));
          }
      }
    else
      {
        double d_teta;
        for (int num_poly=0; num_poly<nb_poly; num_poly++)
          {
            for (int j=0; j<zone_geom.nb_faces_elem(); j++)
              numfa[j] = elem_faces(num_poly,j);
            h_x_ = std::min(h_x_,xv_(numfa[3],0) - xv_(numfa[0],0));
            d_teta = xv_(numfa[4],1) - xv_(numfa[1],1);
            if (d_teta < 0)
              d_teta += deux_pi;
            h_y_ = std::min(h_y_,d_teta*xv_(numfa[1],0));
            h_z_ = std::min(h_z_,xv_(numfa[5],2) - xv_(numfa[2],2));
          }
      }
  else
    {
      if (dimension == 2)
        {
          for (int num_poly=0; num_poly<nb_poly; num_poly++)
            {
              for (int j=0; j<zone_geom.nb_faces_elem(); j++)
                numfa[j] = elem_faces(num_poly,j);
              h_x_ = std::min(h_x_,xv_(numfa[2],0) - xv_(numfa[0],0));
              h_y_ = std::min(h_y_,xv_(numfa[3],1) - xv_(numfa[1],1));
            }
        }
      else
        {
          for (int num_poly=0; num_poly<nb_poly; num_poly++)
            {
              for (int j=0; j<zone_geom.nb_faces_elem(); j++)
                numfa[j] = elem_faces(num_poly,j);
              h_x_ = std::min(h_x_,xv_(numfa[3],0) - xv_(numfa[0],0));
              h_y_ = std::min(h_y_,xv_(numfa[4],1) - xv_(numfa[1],1));
              h_z_ = std::min(h_z_,xv_(numfa[5],2) - xv_(numfa[2],2));
            }
        }
    }
// On prend le minimum de chaque processeur
  h_x_ = mp_min(h_x_);
  h_y_ = mp_min(h_y_);
  h_z_ = mp_min(h_z_);
}
References Objet_U::axi, Objet_U::dimension, Zone_VF::elem_faces(), h_x_, h_y_, h_z_, M_PI, Process::mp_min(), Zone::nb_elem(), Zone::nb_faces_elem(), Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by discretiser().
calculer_volumes_entrelaces()
void Zone_VDF::calculer_volumes_entrelaces ()
remplissage des volumes entrelaces
Definition at line 306 of file Zone_VDF.cpp.
{
  Cerr << "On calcule les volumes entrelaces" << finl;
  creer_tableau_faces(volumes_entrelaces_);
  volumes_entrelaces_dir_.resize(nb_faces(), 2);
  creer_tableau_faces(volumes_entrelaces_dir_);
  const int nb_faces_front = premiere_face_int();
  const int nbf = nb_faces();
  for (int num_face = 0; num_face<nbf; num_face++)
    {
      const double f = (num_face < nb_faces_front) ? 2. : 1.;
      for (int dir = 0; dir < 2; dir ++)
        {
          int elem = face_voisins_(num_face, dir);
          if (elem != -1)
            {
              if ((axi) && (orientation_[num_face]==0))
                volumes_entrelaces_dir_(num_face, dir) = f * 0.5 * xv_(num_face, 0) * volumes(elem) / xp(elem, 0);
              else if ((bidim_axi) && (orientation_[num_face]==0))
                {
                  const double r1 = xv(num_face, 0);
                  const double r2 = xp(elem, 0);
                  const double dz = dim_elem(elem, 1);
                  const double dr = std::fabs(r1 - r2);
                  const double r = std::min(r1, r2);
                  volumes_entrelaces_dir_(num_face, dir) = 2. * M_PI * (r * dr + 0.5 * dr * dr) * dz;
                }
              else
                volumes_entrelaces_dir_(num_face, dir) = f * 0.5 * volumes(elem);
              volumes_entrelaces_[num_face] += volumes_entrelaces_dir_(num_face, dir);
            }
        }
    }
  volumes_entrelaces_.echange_espace_virtuel();
  volumes_entrelaces_dir_.echange_espace_virtuel();
}
References Objet_U::axi, Objet_U::bidim_axi, Cerr, Zone_VF::creer_tableau_faces(), dim_elem(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_voisins_, finl, M_PI, Zone_VF::nb_faces(), orientation_, Zone_VF::premiere_face_int(), TRUSTTab< _TYPE_ >::resize(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces_, Zone_VF::volumes_entrelaces_dir_, Zone_VF::xp(), Zone_VF::xv(), and Zone_VF::xv_.
Referenced by discretiser().
cree_instance()
Objet_U * Zone_VDF::cree_instance () static
Definition at line 29 of file Zone_VDF.cpp.
creer_elements_fictifs()
void Zone_VDF::creer_elements_fictifs (const Zone_Cl_dis_base & zcldisbase) override virtual
remplit le tableau face_voisins_fictifs_
ne CREE PAS d elts fictifs!!!
Reimplemented from Zone_dis_base.
Definition at line 986 of file Zone_VDF.cpp.
{
  Cerr << "Zone_VDF::creer_elements_fictifs()" << finl;
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zcldisbase);
  if (face_voisins_fictifs_.size() == 0)
    {
      face_voisins_fictifs_.resize(nb_faces_bord(),2);
      face_voisins_fictifs_ = -1;
      int compteur = nb_elem_tot();
      int face,ndeb,nfin;
      for (int n_bord=0; n_bord<nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          if ( (sub_type(Dirichlet_entree_fluide,la_cl.valeur())) ||
               (sub_type(Neumann_sortie_libre,la_cl.valeur())) )
            {
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (face=ndeb; face<nfin; face++)
                if (face_voisins(face,0) != -1)
                  face_voisins_fictifs_(face,1) = compteur++;
                else
                  face_voisins_fictifs_(face,0) = compteur++ ;
            }
        }
    }
  Cerr << "taille "<<face_voisins_fictifs_.size()-nb_elem()<<finl;
}
References Cerr, compteur, Zone_VF::face_voisins(), Zone_VF::face_voisins_fictifs_, finl, Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), sub_type, and Deriv_Cond_lim_base::valeur().
creer_faces()
Faces * Zone_VDF::creer_faces () override virtual
renvoie un Faces_VDF* !
Reimplemented from Zone_VF.
Definition at line 75 of file Zone_VDF.cpp.
{
  Faces_VDF* les_faces_vdf=new(Faces_VDF);
  return les_faces_vdf;
}
delta_C()
double Zone_VDF::delta_C (int elem) const inline
Definition at line 564 of file Zone_VDF.h.
{
  double dist= 1;
  for (int i=0; i<dimension; i++)
    dist *= dim_elem(elem,i);
  return pow(dist,1./3.);
}
References dim_elem(), and Objet_U::dimension.
dim_elem()
double Zone_VDF::dim_elem (int n1, int k) const inline
Definition at line 551 of file Zone_VDF.h.
{
  return xv_(elem_faces_(n1,k+dimension),k)-xv_(elem_faces_(n1,k),k);
}
References Objet_U::dimension, Zone_VF::elem_faces_, and Zone_VF::xv_.
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Assembleur_P_VDF_Q4::assembler(), calcul_dscald_bord2D(), calcul_dscald_bord3D(), calcul_dscald_interne2D(), calcul_dscald_interne3D(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), calculer_volumes_entrelaces(), delta_C(), Eval_Centre_VDF_Elem::dim_elem(), Eval_Quick_VDF_Elem::dim_elem(), Eval_Centre4_VDF_Face::dim_elem(), Eval_Quick_VDF_Face::dim_elem(), dim_face(), Assembleur_P_VDF_Q4::modifier_secmem(), and EDO_Pression_th_VDF_Gaz_Reel::resoudre().
dim_face()
double Zone_VDF::dim_face (int n1, int k) const inline
Definition at line 557 of file Zone_VDF.h.
{
  int elem = std::max(face_voisins_(n1,0), face_voisins_(n1,1));
  return dim_elem(elem, k);
}
References dim_elem(), and Zone_VF::face_voisins_.
Referenced by Eval_Quick_VDF_Face::dim_face().
discretiser()
void Zone_VDF::discretiser () override virtual
appel a Zone_VF::discretiser()
calcul des centres de gravite des elements
remplissage des connectivites elements/faces
on reordonne les connectivites faces/elements
de sorte que el1 est a gauche et el2 a droite.
calcul des porosites volumiques et surfaciques
generation des aretes
calcul des pas du maillage
< Detache la structure parallele
< Sinon, grosse erreur: elements voisins non renseignes
Reimplemented from Zone_VF.
Definition at line 220 of file Zone_VDF.cpp.
{
  Zone_VF::discretiser();
  Zone& zone_geom=zone();
// Verification de la coherence entre l'element geometrique et la discretisation
  const Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  if (dimension == 2)
    {
      if (!sub_type(Rectangle,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Rectangle et Rectangle_Axi sont compatibles avec la discretisation VDF en dimension 2" << finl;
          exit();
        }
    }
  else if (dimension == 3)
    {
      if (!sub_type(Hexaedre,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Hexaedre ou Hexadre_Axi sont compatibles avec la discretisation VDF en dimension 3" << finl;
          exit();
        }
    }
// Calcul de l'orientation des faces virtuelles
// Note BM: pour compatibilite avec la version 1.5, orientation_
// n'a pas d'espace virtuel.
  MD_Vector md_nul;
  creer_tableau_faces(orientation_);
  orientation_.echange_espace_virtuel();
  orientation_.set_md_vector(md_nul); //!< Detache la structure parallele
// Application de la convention VDF sur face_voisin:
// L'element face_voisin(i,0) doit avoir une coordonnee "ori" plus petite que la face
// et l'element face_voisin(i,1) doit avoir une coordonnee plus grande.
  {
    const int nbr_faces_tot = face_voisins_.dimension_tot(0);
    for (int i_face = 0; i_face < nbr_faces_tot; i_face++)
      {
        const int elem0 = face_voisins_(i_face, 0);
        const int elem1 = face_voisins_(i_face, 1);
        const int ori = orientation_[i_face];
        const double x_face = xv(i_face, ori);
        double delta = 0.;
// L'element 0 doit avoir une coordonnee "ori" plus petite que la face
// et l'element 1 doit avoir une coordonnee plus grande.
        if (elem0 >= 0)
          {
            delta = x_face - xp(elem0, ori);
          }
        else
          {
            assert(elem1 >= 0); //!< Sinon, grosse erreur: elements voisins non renseignes
            delta = xp(elem1, ori) - x_face;
          }
        if (delta < 0)
          {
// On inverse les deux elements
            face_voisins_(i_face, 0) = elem1;
            face_voisins_(i_face, 1) = elem0;
          }
      }
  }
  calculer_volumes_entrelaces();
  Zone_VF::calculer_porosites();
  Zone_VF::calculer_diametres_hydrauliques();
  Zone_VF::calculer_coefficient_echange_thermique();
  Zone_VF::calculer_coefficient_frottement();
  genere_aretes();
  calcul_h();
  Cerr << "L'objet de type Zone_VDF a ete rempli avec succes " << finl;
}
References calcul_h(), Zone_VF::calculer_coefficient_echange_thermique(), Zone_VF::calculer_coefficient_frottement(), Zone_VF::calculer_diametres_hydrauliques(), Zone_VF::calculer_porosites(), calculer_volumes_entrelaces(), Cerr, Zone_VF::creer_tableau_faces(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Zone_VF::discretiser(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Zone_VF::face_voisins_, finl, genere_aretes(), orientation_, Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::set_md_vector(), sub_type, Zone::type_elem(), Deriv_Elem_geom_base::valeur(), Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
dist_elem()
double Zone_VDF::dist_elem (int n1, int n2, int k) const inline
Definition at line 538 of file Zone_VDF.h.
{
  return xp_(n2,k)-xp_(n1,k);
}
References Zone_VF::xp_.
Referenced by calcul_dscald_bord2D(), calcul_dscald_bord3D(), calcul_dscald_interne2D(), calcul_dscald_interne3D(), Eval_Centre_VDF_Elem::dist_elem(), and Eval_Quick_VDF_Face::dist_elem().
dist_elem_period()
double Zone_VDF::dist_elem_period (int n1, int n2, int k) const inline
Definition at line 544 of file Zone_VDF.h.
{
  return xp_(n2,k) - xv_(elem_faces(n2,k),k)
         + xv_(elem_faces(n1,k+dimension),k) - xp_(n1,k);
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::xp_, and Zone_VF::xv_.
Referenced by calcul_bord2D(), calcul_bord3D(), calcul_interne2D(), calcul_interne3D(), Eval_Centre4_VDF_Elem::dist_elem(), Eval_Quick_VDF_Elem::dist_elem(), Eval_Centre4_VDF_Face::dist_elem_period(), and Eval_Quick_VDF_Face::dist_elem_period().
dist_face()
double Zone_VDF::dist_face (int fac1, int fac2, int k) const inline
Definition at line 278 of file Zone_VDF.h.
{
// Attention cette methode n'est plus appelee par les methodes dist_face de
// Eval_Diff_VDF_Multi_inco_const.cpp et Eval_Diff_VDF_const.cpp pour optimiser les evaluateurs
  return xv_(fac2,k) - xv_(fac1,k);
}
References Zone_VF::xv_.
Referenced by Champ_Face::calcul_duidxj(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Eval_Centre4_VDF_Face::dist_face(), and Eval_Quick_VDF_Face::dist_face().
dist_face_axi()
double Zone_VDF::dist_face_axi (int fac1, int fac2, int k) const inline
Definition at line 289 of file Zone_VDF.h.
{
  if (k != 1)
    return xv_(fac2,k) - xv_(fac1,k);
  else
    {
      double d_teta = xv_(fac2,1) - xv_(fac1,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      return d_teta*xv_(fac1,0);
    }
}
References M_PI, and Zone_VF::xv_.
Referenced by Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), and Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi().
dist_face_elem0()
double Zone_VDF::dist_face_elem0 (int num_face, int n0) const inline
Fonction de calcul utilisable uniquement en coordonnees cartesiennes
de la distance entre le centre d'une face et
le centre de face_voisins(face,0)
Definition at line 667 of file Zone_VDF.h.
{
  int ori = orientation_[num_face];
  return xv_(num_face,ori) - xp_(n0,ori);
}
References orientation_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::Dist_face_elem0().
dist_face_elem0_axi()
double Zone_VDF::dist_face_elem0_axi (int num_face, int n0) const inline
Fonction de calcul utilisable uniquement en coordonnees cylindriques
de la distance entre le centre d'une face et
le centre de face_voisins(face,0)
Definition at line 688 of file Zone_VDF.h.
{
  int ori = orientation_[num_face];
  double dist;
  if (ori!=1)
    dist = xv_(num_face,ori) - xp_(n0,ori);
  else
    {
      double d_teta = xv_(num_face,1) - xp_(n0,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      dist = d_teta*xp_(n0,0);
    }
  return dist;
}
References M_PI, orientation_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::Dist_face_elem0().
dist_face_elem0_period()
double Zone_VDF::dist_face_elem0_period (int num_face, int n0, double l) const inline
Definition at line 732 of file Zone_VDF.h.
{
  int ori = orientation_[num_face];
  double dist = xv_(num_face,ori) - xp_(n0,ori);
  if (dist > 0)
    return dist;
  else
    return dist + l;
}
References orientation_, Zone_VF::xp_, and Zone_VF::xv_.
dist_face_elem1()
double Zone_VDF::dist_face_elem1 (int num_face, int n1) const inline
Fonction de calcul utilisable uniquement en coordonnees cartesiennes
de la distance entre le centre d'une face et
le centre de face_voisins(face,1)
Definition at line 678 of file Zone_VDF.h.
{
  int ori = orientation_[num_face];
  return xp_(n1,ori) - xv_(num_face,ori);
}
References orientation_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::Dist_face_elem1(), and Eval_Centre_VDF_Elem::dist_face_elem1().
dist_face_elem1_axi()
double Zone_VDF::dist_face_elem1_axi (int num_face, int n1) const inline
Fonction de calcul utilisable uniquement en coordonnees cylindriques
de la distance entre le centre d'une face et le centre
de face_voisins(face,1)
Definition at line 708 of file Zone_VDF.h.
{
  int ori = orientation_[num_face];
  double dist;
  if (ori!=1)
    dist = xp_(n1,ori) - xv_(num_face,ori);
  else
    {
      double d_teta = xp_(n1,1) - xv_(num_face,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      dist = d_teta*xp_(n1,0);
    }
  return dist;
}
References M_PI, orientation_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::Dist_face_elem1().
dist_face_elem1_period()
double Zone_VDF::dist_face_elem1_period (int num_face, int n1, double l) const inline
Definition at line 742 of file Zone_VDF.h.
{
  int ori = orientation_[num_face];
  double dist = xp_(n1,ori) - xv_(num_face,ori);
  if (dist > 0)
    return dist;
  else
    return dist + l;
}
References orientation_, Zone_VF::xp_, and Zone_VF::xv_.
dist_face_period()
double Zone_VDF::dist_face_period (int fac1, int fac2, int k) const inline
Definition at line 752 of file Zone_VDF.h.
{
  const Domaine& le_domaine = zone().domaine();
  const DoubleTab& coord_sommets = le_domaine.coord_sommets();
  double dist= std::fabs(coord_sommets(face_sommets(fac1,1),k)-xv_(fac1,k));
  dist += std::fabs(xv_(fac2,k) - coord_sommets(face_sommets(fac2,0),k));
  return dist;
}
References Domaine::coord_sommets(), Zone::domaine(), Zone_VF::face_sommets(), Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Evaluateur_VDF::dist_face_period(), Eval_Centre4_VDF_Face::dist_face_period(), and Eval_Quick_VDF_Face::dist_face_period().
dist_norm()
double Zone_VDF::dist_norm (int num_face) const inline
Definition at line 308 of file Zone_VDF.h.
{
  int n1 = face_voisins_(num_face,0);
  int n2 = face_voisins_(num_face,1);
  int k = orientation_[num_face];
  return (xp_(n2,k) - xp_(n1,k));
}
References Zone_VF::face_voisins_, orientation_, and Zone_VF::xp_.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_blocs().
dist_norm_axi()
double Zone_VDF::dist_norm_axi (int num_face) const inline
Definition at line 320 of file Zone_VDF.h.
{
  int n1 = face_voisins_(num_face,0);
  int n2 = face_voisins_(num_face,1);
  int k = orientation_[num_face];
  double dist;
  if (k != 1)
    dist = xp_(n2,k) - xp_(n1,k);
  else
    {
      double d_teta = xp_(n2,1) - xp_(n1,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      dist = d_teta*xp_(n1,0);
    }
  return dist;
}
References Zone_VF::face_voisins_, M_PI, orientation_, and Zone_VF::xp_.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_blocs().
dist_norm_bord() [1/2]
DoubleVect & Zone_VDF::dist_norm_bord (DoubleVect & dist, const Nom & nom_bord) const
Definition at line 1020 of file Zone_VDF.cpp.
{
  if (axi)
    {
      for (int n_bord=0; n_bord<les_bords_.size(); n_bord++)
        {
          const Front_VF& fr_vf = front_VF(n_bord);
          if (fr_vf.le_nom() == nom_bord)
            {
              dist.resize(fr_vf.nb_faces());
              int ndeb = fr_vf.num_premiere_face();
              for (int face=ndeb; face<ndeb+fr_vf.nb_faces(); face++)
                dist(face-ndeb) = dist_norm_bord_axi(face);
            }
        }
    }
  else
    {
      for (int n_bord=0; n_bord<les_bords_.size(); n_bord++)
        {
          const Front_VF& fr_vf = front_VF(n_bord);
          if (fr_vf.le_nom() == nom_bord)
            {
              dist.resize(fr_vf.nb_faces());
              int ndeb = fr_vf.num_premiere_face();
              for (int face=ndeb; face<ndeb+fr_vf.nb_faces(); face++)
                dist(face-ndeb) = dist_norm_bord(face);
            }
        }
    }
  return dist;
}
References Objet_U::axi, dist_norm_bord(), dist_norm_bord_axi(), Zone_VF::front_VF(), Frontiere_dis_base::le_nom(), Zone_VF::les_bords_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_ >::resize(), and vect_impl::size().
dist_norm_bord() [2/2]
double Zone_VDF::dist_norm_bord (int num_face) const inline
< Verifie que num_face est bien une face de bord reelle ou virtuelle
Definition at line 344 of file Zone_VDF.h.
{
  int n1 = face_voisins_(num_face,0);
  int n2 = face_voisins_(num_face,1);
  assert(num_face<nb_faces_bord() || n1==-1 || n2==-1); //!< Verifie que num_face est bien une face de bord reelle ou virtuelle
  int k = orientation_[num_face];
  if (n1!=-1)
    return (xv_(num_face,k) - xp_(n1,k));
  else
    return (xp_(n2,k) - xv_(num_face,k));
}
References Zone_VF::face_voisins_, Zone_VF::nb_faces_bord(), orientation_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calcul_y_plus(), calculer_h_distant(), calculer_h_local(), Echange_contact_Correlation_VDF::calculer_h_solide(), Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord(), dist_norm_bord(), Evaluateur_VDF::dist_norm_bord(), Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord_externe_(), Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord_externe_VEC(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), and Echange_interne_impose::update_inv_lambda().
dist_norm_bord_axi()
double Zone_VDF::dist_norm_bord_axi (int num_face) const inline
< Verifie que num_face est bien une face de bord reelle ou virtuelle
Definition at line 360 of file Zone_VDF.h.
{
  int n1 = face_voisins_(num_face,0);
  int n2 = face_voisins_(num_face,1);
  assert(num_face<nb_faces_bord() || n1==-1 || n2==-1); //!< Verifie que num_face est bien une face de bord reelle ou virtuelle
  int k = orientation_[num_face];
  double dist;
  if (n1!=-1)
    if (k != 1)
      dist = xv_(num_face,k) - xp_(n1,k);
    else
      {
        double d_teta = xv_(num_face,1) - xp_(n1,1);
        if (d_teta < 0)
          d_teta += 2.0*M_PI;
        dist = d_teta*xp_(n1,0);
      }
  else if (k != 1)
    dist = xp_(n2,k) - xv_(num_face,k);
  else
    {
      double d_teta = xp_(n2,1) - xv_(num_face,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      dist = d_teta*xp_(n2,0);
    }
  return dist;
}
References Zone_VF::face_voisins_, M_PI, Zone_VF::nb_faces_bord(), orientation_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Champ_Face::calcul_y_plus(), Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord(), dist_norm_bord(), Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord_externe_(), Eval_Diff_VDF_Elem< DERIVED_T >::Dist_norm_bord_externe_VEC(), and Champ_front_fonc_gradient_VDF::mettre_a_jour().
dist_norm_period()
double Zone_VDF::dist_norm_period (int num_face, double l) const inline
Definition at line 724 of file Zone_VDF.h.
{
  int n1 = face_voisins_(num_face,0);
  int n2 = face_voisins_(num_face,1);
  int k = orientation_[num_face];
  return (xp_(n2,k) + l - xp_(n1,k));
}
References Zone_VF::face_voisins_, orientation_, and Zone_VF::xp_.
distance_face()
double Zone_VDF::distance_face (int n1, int n2, int k) const inline
Definition at line 393 of file Zone_VDF.h.
{
  double dist,d_teta;
  assert ( (orientation_[n1]==orientation_[n2]) );
  if ( (axi!=1) || (k!=1) )
    dist = xv_(n2,k) - xv_(n1,k);
  else
    {
      d_teta = xv_(n2,1) - xv_(n1,1);
      if (d_teta < 0)
        d_teta += 2.0*M_PI;
      dist = d_teta*xv_(n1,0);
    }
  return dist;
}
References Objet_U::axi, M_PI, orientation_, and Zone_VF::xv_.
distance_normale()
double Zone_VDF::distance_normale (int num_face) const inline
Definition at line 413 of file Zone_VDF.h.
{
  double dist,d_teta;
  int n1 = face_voisins_(num_face,0);
  int n2 = face_voisins_(num_face,1);
  int k = orientation_[num_face];
  if ((n1!=-1) && (n2!=-1))
    {
      if ( (k!=1) || (axi!=1) )
        dist = xp_(n2,k) - xp_(n1,k);
      else
        {
          d_teta = xp_(n2,1) - xp_(n1,1);
          if (d_teta < 0)
            d_teta += 2.0*M_PI;
          dist = d_teta*xp_(n1,0);
        }
    }
  else if (n1!=-1)
    {
      if ( (k!=1) || (axi!=1) )
        dist = (xv_(num_face,k) - xp_(n1,k));
      else
        {
          d_teta = xv_(num_face,1) - xp_(n1,1);
          if (d_teta < 0)
            d_teta += 2.0*M_PI;
          dist = d_teta*xp_(n1,0);
        }
    }
  else
    {
      if ( (k!=1) || (axi!=1) )
        dist = (xp_(n2,k) - xv_(num_face,k));
      else
        {
          d_teta = xp_(n2,1) - xv_(num_face,1);
          if (d_teta < 0)
            d_teta += 2.0*M_PI;
          dist = d_teta*xp_(n2,0);
        }
    }
  return dist;
}
References Objet_U::axi, Zone_VF::face_voisins_, M_PI, orientation_, Zone_VF::xp_, and Zone_VF::xv_.
duplique()
int Zone_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Zone_VDF.cpp.
elem_voisin()
int Zone_VDF::elem_voisin (int elem, int face, int indic) const inline
Definition at line 657 of file Zone_VDF.h.
{
  int ori = orientation_(face);
  return face_voisins_(elem_faces_(elem,ori+indic*dimension),indic);
}
References Objet_U::dimension, Zone_VF::elem_faces_, Zone_VF::face_voisins_, and orientation_.
Referenced by Traitement_particulier_NS_canal_VDF::remplir_Tab_recap().
face_amont_conj()
int Zone_VDF::face_amont_conj (int num_face, int k, int i) const inline
Definition at line 592 of file Zone_VDF.h.
{
  int ori = orientation(num_face);
  int elem = face_voisins_(num_face,1);
  int face_conj=-2,face,elem_bis=-2;
  if(elem != -1)
    {
      face = elem_faces_(elem, k+i*dimension);
      elem_bis = face_voisins_(face,i);
      if (elem_bis != -1)
        face_conj = elem_faces_(elem_bis, ori);
      else
        face_conj = -1;
    }
  if ((elem==-1) || (elem_bis==-1))
    {
      elem = face_voisins_(num_face,0);
      if(elem != -1)
        {
          face = elem_faces_(elem, k+i*dimension);
          elem_bis = face_voisins_(face,i);
          if (elem_bis != -1)
            face_conj = elem_faces_(elem_bis, ori+dimension);
          else
            face_conj = -1;
        }
    }
  assert(face_conj!=-2);
  return face_conj;
}
References Objet_U::dimension, Zone_VF::elem_faces_, Zone_VF::face_voisins_, and orientation().
Referenced by Eval_Centre4_VDF_Face::face_amont_conj(), and Eval_Quick_VDF_Face::face_amont_conj().
face_amont_princ()
int Zone_VDF::face_amont_princ (int num_face, int i) const inline
Definition at line 582 of file Zone_VDF.h.
{
  int ori=orientation(num_face);
  int elem=face_voisins_(num_face,i);
  if(elem !=-1)
    elem=elem_faces_(elem,ori+i*dimension);
  return elem;
}
References Objet_U::dimension, Zone_VF::elem_faces_, Zone_VF::face_voisins_, and orientation().
Referenced by Op_VDF_Face::dimensionner(), Eval_Centre4_VDF_Face::face_amont_princ(), Eval_Quick_VDF_Face::face_amont_princ(), and Eval_Quick_VDF_Face_Axi::face_amont_princ().
face_bord_amont()
int Zone_VDF::face_bord_amont (int num_face, int k, int i) const inline
Determine la face voisine de notre face
en prevoyant que cette derniere puisse etre de type bord.
Definition at line 627 of file Zone_VDF.h.
{
  int ori = orientation(num_face);
  int elem = face_voisins_(num_face,1);
  if(elem != -1)
    {
      int face = elem_faces_(elem, k+i*dimension);
      int elem_bis = face_voisins_(face,i);
      if (elem_bis != -1)
        elem = elem_faces_(elem_bis, ori);
      else
        elem = -1;
    }
  if (elem == -1)
    {
      elem = face_voisins_(num_face,0);
      if(elem != -1)
        {
          int face = elem_faces_(elem, k+i*dimension);
          int elem_bis = face_voisins_(face,i);
          if (elem_bis != -1)
            elem = elem_faces_(elem_bis, ori+dimension);
          else
            elem = -1;
        }
    }
  return elem;
}
References Objet_U::dimension, Zone_VF::elem_faces_, Zone_VF::face_voisins_, and orientation().
Referenced by Op_VDF_Face::dimensionner().
face_normales()
double Zone_VDF::face_normales (int num_face, int k) const inline override virtual
Implements Zone_VF.
Definition at line 265 of file Zone_VDF.h.
{
  int ori = orientation(num_face);
  double surf=0;
  if (ori == k)
    surf=face_surfaces(num_face);
  return surf;
}
References Zone_VF::face_surfaces(), and orientation().
genere_aretes()
void Zone_VDF::genere_aretes () private
generation des aretes
< cf Aretes::affecter
< arete interne
< arete mixte
< arete bord
< arete bord
< arete coin
< On doit generer l'arete en bas a droite de el1 si la maille en bas de el1 n'existe pas
< arete bord
< arete mixte
< arete coin
< On doit generer l'arete en haut a gauche de el1 si la maille en haut a gauche n'existe pas
< arete bord
< arete coin
< arete coin
Definition at line 362 of file Zone_VDF.cpp.
{
  Cerr << "On genere les aretes" << finl;
  Zone& ma_zone=zone();
// int nb_poly = la_zone.nb_elem();
  int nb_poly_tot = ma_zone.nb_elem_tot();
// Estimation avec majoration du nombre d'aretes : nb_aretes_plus
  nb_aretes_=-1; //!< cf Aretes::affecter
  int nb_aretes_plus=-1;
  if (dimension == 2)
    nb_aretes_plus = ma_zone.nb_som();
  else if (dimension == 3)
    nb_aretes_plus = ma_zone.nb_som()*3;
  Cerr << "Creation des aretes " << finl;
  Aretes les_aretes(nb_aretes_plus);
// On balaie les elements :
  int el1, el2, el3, el4;
  int face12, face13, face34, face24;
  int nb_dir;
  if(dimension==2) nb_dir=1;
  else nb_dir=3;
  IntVect gauche(nb_dir);
  gauche(0)=0;
  if(dimension==3)
    {
      gauche(1)=0;
      gauche(2)=1;
    }
  IntVect droite(nb_dir);
  droite(0)=dimension;
  if(dimension==3)
    {
      droite(1)=dimension;
      droite(2)=dimension+1;
    }
  IntVect haut(nb_dir);
  haut(0)=dimension+1;
  if(dimension==3)
    {
      haut(1)=dimension+2;
      haut(2)=dimension+2;
    }
  IntVect bas(nb_dir);
  bas(0)=1;
  if(dimension==3)
    {
      bas(1)=2;
      bas(2)=2;
    }
  int coin=-1;
  int bord=0;
  int mixte=1;
  int interne=2;
// Detection des plaques (2 faces frontieres se superposent):
  IntVect est_une_plaque(nb_faces());
  creer_tableau_faces(est_une_plaque);
  est_une_plaque=0;
// Boucles sur les faces frontieres
  ArrOfDouble P1(3), P2(3);
  P1=0;
  P2=0;
  double eps = 10.0*Objet_U::precision_geom;
  for (int face=0; face<premiere_face_int(); face++)
    {
      int ori = orientation(face);
      for (int i = 0; i < dimension; i++)
        {
          P1[i] = xv(face, i) + (ori == i ? eps : 0);
          P2[i] = xv(face, i) - (ori == i ? eps : 0);
        }
      int elem1 = zone().chercher_elements(P1[0], P1[1], P1[2]);
      int elem2 = zone().chercher_elements(P2[0], P2[1], P2[2]);
      if (elem1 >= 0 && elem2 >= 0 && elem1 != elem2)
        {
// Find 2 points P1 and P2 in cells so:
          est_une_plaque(face) = 1;
          Journal() << "We detect an internal boundary on face " << face << " between elements " << elem1 << " and "
                    << elem2 << finl;
        }
    }
  est_une_plaque.echange_espace_virtuel();
  for(int dir=0; dir<nb_dir; dir++)
    for (el1=0; el1<nb_poly_tot; el1++)
      {
// On doit generer l'arete en haut a droite de el1
        face12=elem_faces(el1,droite(dir));
        face13=elem_faces(el1,haut(dir));
        el2=face_vois(*this, ma_zone, face12, 1);
        if(el2>-1)
          face24=elem_faces(el2,haut(dir));
        else
          face24=-1;
        el3=face_vois(*this, ma_zone, face13, 1);
        if(el3>-1)
          face34=elem_faces(el3,droite(dir));
        else
          face34=-1;
        if( (el2>-1) && (el3>-1))
          el4=face_vois(*this, ma_zone, face24, 1);
        else if((el2>-1))
          el4=face_vois(*this, ma_zone, face24, 1);
        else if((el3>-1))
          el4=face_vois(*this, ma_zone, face34, 1);
        else
          el4=-1;
        if ( (el2==-1) && (el4>=0) )
          face24=elem_faces(el4,bas(dir));
        if ( (el3==-1) && (el4>=0) )
          face34=elem_faces(el4,gauche(dir));
        const int nb_f = nb_faces();
        if (el2 > -1 && el3 > -1 && el4 > -1) //!< arete interne
          les_aretes.affecter(nb_aretes_, dir, interne, nb_f, face13, face24, face12, face34, est_une_plaque);
        else if ( (el3 > -1 && el4 > -1) ||
                  (el2 > -1 && el4 > -1) ||
                  (el2 > -1 && el3 > -1) ) //!< arete mixte
          les_aretes.affecter(nb_aretes_, dir, mixte, nb_f, face13, face24, face12, face34, est_une_plaque);
        else if (el2 > -1) //!< arete bord
          les_aretes.affecter(nb_aretes_, dir, bord, nb_f, face13, face24, face12, 1, est_une_plaque);
        else if (el3 > -1) //!< arete bord
          les_aretes.affecter(nb_aretes_, dir, bord, nb_f, face12, face34, face13, 1, est_une_plaque);
        else //!< arete coin
          les_aretes.affecter(nb_aretes_, dir, coin, nb_f, face13, face24, face12, face34, est_une_plaque);
// Cerr << "elements_haut_droit " << el1 << " " << el2 << " " << el3 << " " << el4 << finl;
// Journal() << "Provisoire faces arete: " << face12 << " " << face13 << " " << face24 << " " << face34 << finl;
// Pour les coins ou bords :
        face13 = elem_faces(el1, bas(dir));
        el3 = face_vois(*this, ma_zone, face13, 0);
        if (el3 < 0) //!< On doit generer l'arete en bas a droite de el1 si la maille en bas de el1 n'existe pas
//
          {
            if (el2 >= 0)
              {
                face24 = elem_faces(el2, bas(dir));
                el4 = face_vois(*this, ma_zone, face24, 0);
                if (el4 < 0) //!< arete bord
                  les_aretes.affecter(nb_aretes_, dir, bord, nb_f, face13, face24, face12, -1, est_une_plaque);
                else //!< arete mixte
                  {
                    face34 = elem_faces(el4, gauche(dir));
                    if (face_vois(*this, ma_zone, face34, 0) == -1)
                      les_aretes.affecter(nb_aretes_, dir, mixte, nb_f, face13, face24, face34, face12, est_une_plaque);
                  }
              }
            else   //!< arete coin
              les_aretes.affecter(nb_aretes_, dir, coin, nb_f, face13, -1, -1, face12, est_une_plaque);
// Cerr << "elements_bas_droit " << el1 << " " << el2 << " " << el3 << " " << el4 << finl;
          }
        face13 = elem_faces(el1, gauche(dir));
        el3 = face_vois(*this, ma_zone, face13, 0);
        if (el3 < 0) //!< On doit generer l'arete en haut a gauche de el1 si la maille en haut a gauche n'existe pas
//
          {
            face12 = elem_faces(el1, haut(dir));
            el2 = face_vois(*this, ma_zone, face12, 1);
            if (el2 >= 0)
              {
                face24 = elem_faces(el2, gauche(dir));
                el4 = face_vois(*this, ma_zone, face24, 0);
                if (el4 < 0) //!< arete bord
                  les_aretes.affecter(nb_aretes_, dir, bord, nb_f, face13, face24, face12, -1, est_une_plaque);
              }
            else   //!< arete coin
              les_aretes.affecter(nb_aretes_, dir, coin, nb_f, -1, face12, -1, face13, est_une_plaque);
// Cerr << "elements_haut_gauche " << el1 << " " << el2 << " " << el3 << " " << el4 << finl;
          }
// On doit generer l'arete en bas a gauche de el1
        face12 = elem_faces(el1, gauche(dir));
        el2 = face_vois(*this, ma_zone, face12, 0);
        face13 = elem_faces(el1, bas(dir));
        el3 = face_vois(*this, ma_zone, face13, 0);
        if ((el2 < 0) && (el3 < 0)) //!< arete coin
          {
            les_aretes.affecter(nb_aretes_, dir, coin, nb_f, face13, -1, face12, -1, est_une_plaque);
// Cerr << "elements_bas_gauche " << el1 << " " << el2 << " " << el3 << " " << el4 << finl;
          }
      }
  nb_aretes_++;
  les_aretes.dimensionner(nb_aretes_);
// Cerr << "Tri des aretes " << finl;
  les_aretes.trier(nb_aretes_coin_,
                   nb_aretes_bord_,
                   nb_aretes_mixtes_,
                   nb_aretes_internes_);
#ifdef SORT_POUR_DEBOG
  les_aretes.trier_pour_debog(nb_aretes_coin_,
                              nb_aretes_bord_,
                              nb_aretes_mixtes_,
                              nb_aretes_internes_,xv());
#endif
  nb_aretes_joint_=0;
  assert(nb_aretes_==nb_aretes_coin_+nb_aretes_bord_+nb_aretes_mixtes_
         +nb_aretes_internes_+nb_aretes_joint_);
  Qdm_.ref(les_aretes.faces());
  /*
  // Boucle pour verifier ou sont les parois internes
  for (int i=0; i<Qdm_.dimension(0); i++)
    {
      int nb_plaques = 0;
      for (int j = 0; j < Qdm_.dimension(1); j++)
        nb_plaques += Qdm_(i, j) >= 0 ? est_une_plaque(Qdm_(i, j)) : 0;
      if (nb_plaques > 0)
      Journal() << "Provisoire arete " << i << " a " << nb_plaques << " paroi internes." << finl;
    }
  Journal() << "Aretes coin   = " << nb_aretes_coin_ << finl;
    Journal() << "Aretes bord   = " << nb_aretes_bord_ << finl;
    Journal() << "Aretes mixte  = " << nb_aretes_mixtes_ << finl;
    Journal() << "Aretes interne= " << nb_aretes_internes_ << finl;
    Journal() << "Aretes joint  = " << nb_aretes_joint_ << finl;
     */
// Cerr << "Qdm : " << Qdm_ << finl;
}
References Aretes::affecter(), Cerr, Zone::chercher_elements(), Zone_VF::creer_tableau_faces(), Objet_U::dimension, Aretes::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), face_vois(), Aretes::faces(), finl, Process::Journal(), nb_aretes_, nb_aretes_bord_, nb_aretes_coin_, nb_aretes_internes_, nb_aretes_joint_, nb_aretes_mixtes_, Zone::nb_elem_tot(), Zone_VF::nb_faces(), Zone::nb_som(), orientation(), Objet_U::precision_geom, Zone_VF::premiere_face_int(), Qdm_, TRUSTTab< _TYPE_ >::ref(), Aretes::trier(), Aretes::trier_pour_debog(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by discretiser().
get_info()
const Type_info * Zone_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_VF.
Definition at line 29 of file Zone_VDF.cpp.
h_x()
double Zone_VDF::h_x () const inline
Definition at line 520 of file Zone_VDF.h.
{
  return h_x_;
}
References h_x_.
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab().
h_y()
double Zone_VDF::h_y () const inline
Definition at line 526 of file Zone_VDF.h.
{
  return h_y_;
}
References h_y_.
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab().
h_z()
double Zone_VDF::h_z () const inline
Definition at line 532 of file Zone_VDF.h.
{
  return h_z_;
}
References h_z_.
Referenced by Op_Diff_VDF_Elem_base::calculer_dt_stab().
info()
const Type_info * Zone_VDF::info () static
Definition at line 29 of file Zone_VDF.cpp.
init_virt_e_map()
void Zone_VDF::init_virt_e_map () const
Definition at line 1053 of file Zone_VDF.cpp.
{
  IntTrav p_e(0, 2);
  zone().creer_tableau_elements(p_e);
  for (int e = 0; e < nb_elem() ; e++) p_e(e, 0) = Process::me(), p_e(e, 1) = e;
  p_e.echange_espace_virtuel();
  for (int e = nb_elem() ; e < nb_elem_tot() ; e++) virt_e_map[ {{ p_e(e, 0), p_e(e, 1) }}] = e;
}
References Zone::creer_tableau_elements(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::me(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), virt_e_map, and Zone_dis_base::zone().
Referenced by Echange_contact_VDF::initialiser().
modifier_pour_Cl()
void Zone_VDF::modifier_pour_Cl (const Conds_lim & cl) override virtual
< arete de type periodicite
< arete coin perio-paroi
< arete coin perio-perio
< arete coin paroi-fluide
Reimplemented from Zone_VF.
Definition at line 666 of file Zone_VDF.cpp.
{
// Cerr << "Zone_VDF::Modifier_pour_Cl" << finl;
  Zone_VF::modifier_pour_Cl(conds_lim);
  int fac3;
  int nb_cond_lim=conds_lim.size();
  IntTab aretes_coin_traitees(nb_aretes_coin());
  aretes_coin_traitees = -1;
  for (int num_cond_lim=0; num_cond_lim<nb_cond_lim; num_cond_lim++)
    {
// for cl ...
// Journal() << "On traite la cl num : " << num_cond_lim << finl;
      const Cond_lim_base& cl = conds_lim[num_cond_lim].valeur();
      if (sub_type(Periodique, cl))
        {
// if cl perio
// Modification du tableau Qdm_ pour les aretes de type periodicite
          const Zone_Cl_VDF& zone_Cl_VDF = ref_cast(Zone_Cl_VDF,cl.zone_Cl_dis());
          int ndeb_arete = premiere_arete_bord();
          int fac1,fac2,sign,num_face,elem1,n_type;
          for (int n_arete=ndeb_arete; n_arete<ndeb_arete+nb_aretes_bord(); n_arete++)
            {
// for n_arete
              n_type=zone_Cl_VDF.type_arete_bord(n_arete-ndeb_arete);
              if (n_type == TypeAreteBordVDF::PERIO_PERIO) //!< arete de type periodicite
                {
// if arete perio
                  fac1 = Qdm_(n_arete,0);
                  fac2 = Qdm_(n_arete,1);
                  fac3 = Qdm_(n_arete,2);
                  sign = Qdm_(n_arete,3);
                  const Front_VF& la_frontiere_dis = ref_cast(Front_VF,cl.frontiere_dis());
                  int ndeb = la_frontiere_dis.num_premiere_face();
                  int nfin = ndeb + la_frontiere_dis.nb_faces();
                  if ( ( ( ndeb <= fac1) && (fac1 < nfin) ) ||
                       ( ( ndeb <= fac2) && (fac2 < nfin) )
                     )
                    {
                      if (sign == 1)
                        elem1 = face_voisins(fac1,1);
                      else
                        elem1 = face_voisins(fac1,0);
                      num_face = dimension+orientation_[fac3];
                      if (sign == -1)
{
                          Qdm_(n_arete,3) = fac3;
                          Qdm_(n_arete,2) = elem_faces(elem1,num_face);
                        }
                      else
                        Qdm_(n_arete,3) = elem_faces(elem1,num_face);
                    }
                }
            }
// prise  en compte des aretes coin
          int ndeb_arete_coin = premiere_arete_coin();
          Cerr << "Modifications de Qdm pour les aretes coins  num_cond_lim=" << num_cond_lim <<  finl;
          int fac4;
          for (int n_arete=ndeb_arete_coin; n_arete<ndeb_arete_coin+nb_aretes_coin(); n_arete++)
            {
              if (aretes_coin_traitees[n_arete] != 1)
                {
                  fac1 = Qdm_(n_arete,0);
                  fac2 = Qdm_(n_arete,1);
                  fac3 = Qdm_(n_arete,2);
                  fac4 = Qdm_(n_arete,3);
// On recupere le numero des faces qui ne sont pas egales a -1
                  IntVect f(2);
                  f = -2;
                  int i=0;
                  if (fac1 != -1)
                    {
                      f(i) = fac1;
                      i++;
                    }
                  if (fac2 != -1)
                    {
                      f(i) = fac2;
                      i++;
                    }
                  if (fac3 != -1)
                    {
                      f(i) = fac3;
                      i++;
                    }
                  if (fac4 != -1)
                    {
                      f(i) = fac4;
                      i++;
                    }
// On regarde si la face est une face de periodicite
                  const Front_VF& la_frontiere_dis = ref_cast(Front_VF,cl.frontiere_dis());
                  int ndeb = la_frontiere_dis.num_premiere_face();
                  int nfin = ndeb + la_frontiere_dis.nb_faces();
                  int  elem, fac,dim0,dim1,indic_f0=-100,indic_f1=-100;
                  n_type=zone_Cl_VDF.type_arete_coin(n_arete-ndeb_arete_coin);
                  dim1 = orientation_[f(1)];
                  dim0 = orientation_[f(0)];
                  for (int j=0; j<2; j++)
                    for (int k=0; k<2; k++)
                      if ((face_voisins(f(0),j) == face_voisins(f(1),k))  && (face_voisins(f(0),j)!=-1) )
{
                          indic_f0 = j;
                          indic_f1 = k;
                        }
                  if ((n_type == TypeAreteCoinVDF::PERIO_PAROI) || (n_type == TypeAreteCoinVDF::PERIO_FLUIDE))//!< arete coin perio-paroi
                    {
                      if ((f(0) >= ndeb)&&(f(0) < nfin))
{
                          Qdm_(n_arete,2)=f(0);
                          Qdm_(n_arete,indic_f0)=f(1);
                          elem = face_voisins(f(0),1-indic_f0);
                          fac = elem_faces(elem,dim1+(1-indic_f1)*dimension);
                          Qdm_(n_arete,1-indic_f0)=fac;
                          Qdm_(n_arete,3)=1-2*indic_f1;
// Cerr << "n_arete=" << n_arete << "  OK!!" << finl;
                          aretes_coin_traitees[n_arete] = 1;
                        }
                      else
{
                          if ((f(1) >= ndeb)&&(f(1) < nfin))
{
                              Qdm_(n_arete,2)=f(1);
                              Qdm_(n_arete,indic_f1)=f(0);
                              elem = face_voisins(f(1),1-indic_f1);
                              fac = elem_faces(elem,dim0+(1-indic_f0)*dimension);
                              Qdm_(n_arete,1-indic_f1)=fac;
                              Qdm_(n_arete,3)=1-2*indic_f0;
// Cerr << "n_arete=" << n_arete << "  OK!!" << finl;
                              aretes_coin_traitees[n_arete] = 1;
                            }
                          else
{
// Cerr<<"Attention cas non traite lors du remplissage du tableau Qdm"<<finl;
// exit();
                              ;
                            }
                        }
                    }
                  else if (n_type == TypeAreteCoinVDF::PERIO_PERIO) //!< arete coin perio-perio
                    {
                      if ((f(0) >= ndeb)&&(f(0) < nfin))
{
                          Qdm_(n_arete,2+indic_f1)=f(0);
                          Qdm_(n_arete,indic_f0)=f(1);
                          elem = face_voisins(f(0),1-indic_f0);
                          fac = elem_faces(elem,dim1+(1-indic_f1)*dimension);
                          Qdm_(n_arete,1-indic_f0)=fac;
                          elem = face_voisins(f(1),1-indic_f1);
                          fac = elem_faces(elem,dim0+(1-indic_f0)*dimension);
                          Qdm_(n_arete,3-indic_f1)=fac;
// Cerr << "n_arete=" << n_arete << "  OK!!" << finl;
                          aretes_coin_traitees[n_arete] = 1;
                        }
                      else
{
                          if ((f(1) >= ndeb)&&(f(1) < nfin))
{
                              Qdm_(n_arete,2+indic_f0)=f(1);
                              Qdm_(n_arete,indic_f1)=f(0);
                              elem = face_voisins(f(1),1-indic_f1);
                              fac = elem_faces(elem,dim0+(1-indic_f0)*dimension);
                              Qdm_(n_arete,1-indic_f1)=fac;
                              elem = face_voisins(f(0),1-indic_f0);
                              fac = elem_faces(elem,dim1+(1-indic_f1)*dimension);
                              Qdm_(n_arete,3-indic_f0)=fac;
// Cerr << "n_arete=" << n_arete << "  OK!!" << finl;
                              aretes_coin_traitees[n_arete] = 1;
                            }
                        }
                    }
                  else
                    {
                      Cerr << "Attention : les cas concernant d autres types d aretes coin "  << finl;
                      Cerr << "que perio-perio ou perio-paroi ne sont pas traites!!" << finl;
                    }
                }
            }
        }
// Modif OC 01/2005 pour traiter les coins de type paroi/fluide
      else if (sub_type(Dirichlet_entree_fluide, cl) || sub_type(Neumann_sortie_libre, cl) )
        {
// if cl de type paroi
          const Zone_Cl_VDF& zone_Cl_VDF = ref_cast(Zone_Cl_VDF,cl.zone_Cl_dis());
          int fac1,fac2,n_type;
          int ndeb_arete_coin = premiere_arete_coin();
          Cerr << "Modifications de Qdm pour les aretes coins touchant une paroi num_cond_lim=" << num_cond_lim <<  finl;
          int fac4;
          for (int n_arete=ndeb_arete_coin; n_arete<ndeb_arete_coin+nb_aretes_coin(); n_arete++)
            {
              if (aretes_coin_traitees[n_arete] != 1)
                {
                  fac1 = Qdm_(n_arete,0);
                  fac2 = Qdm_(n_arete,1);
                  fac3 = Qdm_(n_arete,2);
                  fac4 = Qdm_(n_arete,3);
// On recupere le numero des faces qui ne sont pas egales a -1
                  IntVect f(2);
                  f = -2;
                  int i=0;
                  if (fac1 != -1)
                    {
                      f(i) = fac1;
                      i++;
                    }
                  if (fac2 != -1)
                    {
                      f(i) = fac2;
                      i++;
                    }
                  if (fac3 != -1)
                    {
                      f(i) = fac3;
                      i++;
                    }
                  if (fac4 != -1)
                    {
                      f(i) = fac4;
                      i++;
                    }
// On regarde si la face est une face de type paroi
                  const Front_VF& la_frontiere_dis = ref_cast(Front_VF,cl.frontiere_dis());
                  int ndeb = la_frontiere_dis.num_premiere_face();
                  int nfin = ndeb + la_frontiere_dis.nb_faces();
                  int indic_f0=-100,indic_f1=-100;
                  n_type=zone_Cl_VDF.type_arete_coin(n_arete-ndeb_arete_coin);
                  for (int j=0; j<2; j++)
                    for (int k=0; k<2; k++)
                      if ((face_voisins(f(0),j) == face_voisins(f(1),k)) && (face_voisins(f(0),j)!=-1) )
{
                          indic_f0 = j;
                          indic_f1 = k;
                        }
                  if ((n_type == TypeAreteCoinVDF::PAROI_FLUIDE) || (n_type == TypeAreteCoinVDF::FLUIDE_PAROI) || (n_type == TypeAreteCoinVDF::FLUIDE_FLUIDE))//!< arete coin paroi-fluide
                    {
                      if ((f(0) >= ndeb)&&(f(0) < nfin))
{
                          Qdm_(n_arete,0)=f(1);
                          Qdm_(n_arete,1)=f(1);
                          Qdm_(n_arete,2)=f(0);
                          Qdm_(n_arete,3)=1-2*indic_f1;
                          aretes_coin_traitees[n_arete] = 1;
                        }
                      else
{
                          if ((f(1) >= ndeb)&&(f(1) < nfin))
{
                              Qdm_(n_arete,0)=f(0);
                              Qdm_(n_arete,1)=f(0);
                              Qdm_(n_arete,2)=f(1);
                              Qdm_(n_arete,3)=1-2*indic_f0;
                              aretes_coin_traitees[n_arete] = 1;
                            }
                          else
{
// Cerr<<"Attention cas non traite lors du remplissage du tableau Qdm"<<finl;
// exit();
                              ;
                            }
                        }
                    }
                }
            }
        }
// Cerr << "Qdm : " << Qdm_ << finl;
// Cerr << "aretes_coin_traitees : " << aretes_coin_traitees << finl;
    }
// Journal() << "la_zone apres modif pour Cl : " << *this << finl;
// PQ : 10/10/05 : les faces periodiques etant a double contribution
// l'appel a marquer_faces_double_contrib s'effectue dans cette methode
// afin de pouvoir beneficier de conds_lim.
  Zone_VF::marquer_faces_double_contrib(conds_lim);
}
References Cerr, Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_voisins(), finl, TypeAreteCoinVDF::FLUIDE_FLUIDE, TypeAreteCoinVDF::FLUIDE_PAROI, Cond_lim_base::frontiere_dis(), Zone_VF::marquer_faces_double_contrib(), Zone_VF::modifier_pour_Cl(), nb_aretes_bord(), nb_aretes_coin(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), orientation_, TypeAreteCoinVDF::PAROI_FLUIDE, TypeAreteCoinVDF::PERIO_FLUIDE, TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, premiere_arete_bord(), premiere_arete_coin(), Qdm_, ref_cast, vect_impl::size(), sub_type, Zone_Cl_VDF::type_arete_bord(), Zone_Cl_VDF::type_arete_coin(), and Cond_lim_base::zone_Cl_dis().
nb_aretes()
int Zone_VDF::nb_aretes () const inline
Definition at line 508 of file Zone_VDF.h.
{
  return nb_aretes_;
}
References nb_aretes_.
Referenced by Op_Dift_VDF_Face_Axi_base::ajouter_aretes_internes(), Op_Diff_VDF_Face_Axi_base::ajouter_aretes_mixtes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes_internes(), Champ_Face::calculer_dercov_axi(), and Champ_Face::dimensionner_tenseur_Grad().
nb_aretes_bord()
int Zone_VDF::nb_aretes_bord () const inline
Definition at line 478 of file Zone_VDF.h.
{
  return nb_aretes_bord_;
}
References nb_aretes_bord_.
Referenced by Op_Diff_VDF_Face_Axi_base::ajouter_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Zone_Cl_VDF::associer(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calculer_dercov_axi(), Zone_Cl_VDF::completer(), Op_Diff_VDF_Face_Axi_base::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), and modifier_pour_Cl().
nb_aretes_coin()
int Zone_VDF::nb_aretes_coin () const inline
Definition at line 466 of file Zone_VDF.h.
{
  return nb_aretes_coin_;
}
References nb_aretes_coin_.
Referenced by Zone_Cl_VDF::associer(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Zone_Cl_VDF::completer(), and modifier_pour_Cl().
nb_aretes_internes()
int Zone_VDF::nb_aretes_internes () const inline
Definition at line 502 of file Zone_VDF.h.
{
  return nb_aretes_internes_;
}
References nb_aretes_internes_.
Referenced by Champ_Face::calcul_duidxj(), and Champ_Face::calcul_S_barre_sans_contrib_paroi().
nb_aretes_joint()
int Zone_VDF::nb_aretes_joint () const inline
Definition at line 460 of file Zone_VDF.h.
{
  return nb_aretes_joint_;
}
References nb_aretes_joint_.
nb_aretes_mixtes()
int Zone_VDF::nb_aretes_mixtes () const inline
Definition at line 490 of file Zone_VDF.h.
{
  return nb_aretes_mixtes_;
}
References nb_aretes_mixtes_.
Referenced by Champ_Face::calcul_duidxj(), and Champ_Face::calcul_S_barre_sans_contrib_paroi().
nb_faces_X()
int Zone_VDF::nb_faces_X () const inline
Definition at line 187 of file Zone_VDF.h.
{
  return nb_faces_X_;
}
References nb_faces_X_.
Referenced by Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), and Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour().
nb_faces_Y()
int Zone_VDF::nb_faces_Y () const inline
Definition at line 193 of file Zone_VDF.h.
{
  return nb_faces_Y_;
}
References nb_faces_Y_.
Referenced by Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), and Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour().
nb_faces_Z()
int Zone_VDF::nb_faces_Z () const inline
Definition at line 199 of file Zone_VDF.h.
{
  return nb_faces_Z_;
}
References nb_faces_Z_.
Referenced by Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), and Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour().
orientation() [1/3]
IntVect & Zone_VDF::orientation () inline
inline double Zone_VDF::porosite_face(int i) const
{
return porosite_face_[i];
}
Definition at line 217 of file Zone_VDF.h.
{
  return orientation_;
}
References orientation_.
Referenced by face_amont_conj(), face_amont_princ(), face_bord_amont(), face_normales(), and genere_aretes().
orientation() [2/3]
const IntVect & Zone_VDF::orientation () const inline override virtual
Reimplemented from Zone_VF.
Definition at line 223 of file Zone_VDF.h.
{
  return orientation_;
}
References orientation_.
orientation() [3/3]
int Zone_VDF::orientation (int i) const inline override virtual
inline DoubleVect& Zone_VDF::porosite_face()
{
return porosite_face_;
}
inline const DoubleVect& Zone_VDF::porosite_face() const
{
return porosite_face_;
} inline DoubleVect& Zone_VDF::porosite_elem()
{
return porosite_elem_;
} inline const DoubleVect& Zone_VDF::porosite_elem() const
{
return porosite_elem_;
} inline double Zone_VDF::porosite_elem(int i) const
{
return porosite_elem_[i];
}
Reimplemented from Zone_VF.
Definition at line 259 of file Zone_VDF.h.
{
  return orientation_[i];
}
References orientation_.
Referenced by Champ_Face::affecter(), Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Diff_VDF_Elem_base::ajouter_blocs(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Dift_VDF_base::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Assembleur_P_VDF_Q4::assembler(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_zones(), Evaluateur_VDF::associer_zones(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calcul_y_plus(), Champ_Face::calculer_dercov_axi(), EDO_Pression_th_VDF::calculer_grad(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), Evaluateur_Source_VDF_Face::completer(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_VDF_Face::dimensionner(), Eval_Quick_VDF_Face_Axi::face_amont_conj(), face_bord_amont2(), Zone_Cl_VDF::imposer_cond_lim(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Op_VDF_Face::modifier_pour_Cl(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), and Champ_Face_implementation::trace().
premiere_arete_bord()
int Zone_VDF::premiere_arete_bord () const inline
Definition at line 484 of file Zone_VDF.h.
{
  return nb_aretes_joint_+ nb_aretes_coin_;
}
References nb_aretes_coin_, and nb_aretes_joint_.
Referenced by Op_Diff_VDF_Face_Axi_base::ajouter_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calculer_dercov_axi(), Zone_Cl_VDF::completer(), Op_Diff_VDF_Face_Axi_base::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), and modifier_pour_Cl().
premiere_arete_coin()
int Zone_VDF::premiere_arete_coin () const inline
Definition at line 472 of file Zone_VDF.h.
{
  return nb_aretes_joint_;
}
References nb_aretes_joint_.
Referenced by Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Zone_Cl_VDF::completer(), and modifier_pour_Cl().
premiere_arete_interne()
int Zone_VDF::premiere_arete_interne () const inline
Definition at line 514 of file Zone_VDF.h.
{
  return nb_aretes_ - nb_aretes_internes_;
}
References nb_aretes_, and nb_aretes_internes_.
Referenced by Op_Dift_VDF_Face_Axi_base::ajouter_aretes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_aretes_mixtes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes(), Champ_Face::calcul_duidxj(), and Champ_Face::calcul_S_barre_sans_contrib_paroi().
premiere_arete_mixte()
int Zone_VDF::premiere_arete_mixte () const inline
Definition at line 496 of file Zone_VDF.h.
{
  return nb_aretes_ - nb_aretes_mixtes_ - nb_aretes_internes_;
}
References nb_aretes_, nb_aretes_internes_, and nb_aretes_mixtes_.
Referenced by Op_Dift_VDF_Face_Axi_base::ajouter_aretes_mixtes(), Op_Diff_VDF_Face_Axi_base::ajouter_aretes_mixtes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes_internes(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), and Champ_Face::calculer_dercov_axi().
printOn()
Sortie & Zone_VDF::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
< PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
Reimplemented from Zone_VF.
Definition at line 35 of file Zone_VDF.cpp.
{
  Zone_VF::printOn(os);
  os << "orientation_"<<orientation_<< finl;
  os << "nb_faces_X_"<<nb_faces_X_<< finl;
  os << "nb_faces_Y_"<<nb_faces_Y_<< finl;
  os << "nb_faces_Z_"<<nb_faces_Z_<< finl;
  os << "nb_aretes_"<<nb_aretes_<< finl;
  os << "nb_aretes_joint_"<<nb_aretes_joint_<< finl;
  os << "nb_aretes_coin_"<<nb_aretes_coin_<< finl;
  os << "nb_aretes_bord_"<<nb_aretes_bord_<< finl;
  os << "nb_aretes_mixtes_"<<nb_aretes_mixtes_<< finl;
  os << "nb_aretes_internes_"<<nb_aretes_internes_<< finl;
  Qdm_.ecrit(os<< "Qdm : ");
  os << h_x_ << " " << h_y_ << " " << h_z_<< finl;
  return os ;
}
References TRUSTTab< _TYPE_ >::ecrit(), finl, h_x_, h_y_, h_z_, nb_aretes_, nb_aretes_bord_, nb_aretes_coin_, nb_aretes_internes_, nb_aretes_joint_, nb_aretes_mixtes_, nb_faces_X_, nb_faces_Y_, nb_faces_Z_, orientation_, Zone_VF::printOn(), and Qdm_.
Qdm() [1/3]
IntTab & Zone_VDF::Qdm () inline
Definition at line 175 of file Zone_VDF.h.
{
  return Qdm_;
}
References Qdm_.
Qdm() [2/3]
const IntTab & Zone_VDF::Qdm () const inline
Definition at line 181 of file Zone_VDF.h.
{
  return Qdm_;
}
References Qdm_.
Qdm() [3/3]
int Zone_VDF::Qdm (int num_arete, int i) const inline
Definition at line 205 of file Zone_VDF.h.
{
  return Qdm_(num_arete,i);
}
References Qdm_.
Referenced by Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calculer_dercov_axi(), and Zone_Cl_VDF::completer().
readOn()
Entree & Zone_VDF::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_VF.
Definition at line 56 of file Zone_VDF.cpp.
{
  Zone_VF::readOn(is);
  is >>  orientation_;
  is >>  nb_faces_X_;
  is >>  nb_faces_Y_;
  is >>  nb_faces_Z_;
  is >>  nb_aretes_;
  is >>  nb_aretes_joint_;
  is >>  nb_aretes_coin_;
  is >>  nb_aretes_bord_;
  is >>  nb_aretes_mixtes_;
  is >>  nb_aretes_internes_;
  Qdm_.lit(is);
  is >>  h_x_>>h_y_>>h_z_;
  return is ;
}
References h_x_, h_y_, h_z_, TRUSTTab< _TYPE_ >::lit(), nb_aretes_, nb_aretes_bord_, nb_aretes_coin_, nb_aretes_internes_, nb_aretes_joint_, nb_aretes_mixtes_, nb_faces_X_, nb_faces_Y_, nb_faces_Z_, orientation_, Qdm_, and Zone_VF::readOn().
remplir_elem_faces()
void Zone_VDF::remplir_elem_faces () override private virtual
Implements Zone_VF.
Definition at line 299 of file Zone_VDF.cpp.
{
// Deja fait dans la nouvelle version
}
reordonner()
void Zone_VDF::reordonner (Faces & les_faces) override virtual
reordonne les faces en fonction de l'orientation
calcule les centres de gravite des faces
calcule les surfaces
Reimplemented from Zone_VF.
Definition at line 196 of file Zone_VDF.cpp.
{
// Cerr << "Faces : " << les_faces << finl;
// Cerr << "On reordonne les faces " << finl;
// Calcul de l'orientation des faces reeles
  Faces_VDF& les_faces_vdf=ref_cast(Faces_VDF, les_faces);
  les_faces_vdf.calculer_orientation(orientation_, nb_faces_X_,
                                     nb_faces_Y_, nb_faces_Z_);
  Joints&      joints     = zone().faces_joint();
  reordonner_vdf(zone().nb_faces_frontiere(),
                 les_faces_vdf, elem_faces_, orientation_, joints);
}
References Faces_VDF::calculer_orientation(), Zone_VF::elem_faces_, Zone::faces_joint(), nb_faces_X_, nb_faces_Y_, nb_faces_Z_, orientation_, ref_cast, reordonner_vdf(), and Zone_dis_base::zone().
self_cast() [1/2]
const Zone_VDF & Zone_VDF::self_cast (const Objet_U & r) static
Definition at line 29 of file Zone_VDF.cpp.
self_cast() [2/2]
Zone_VDF & Zone_VDF::self_cast (Objet_U & r) static
Definition at line 29 of file Zone_VDF.cpp.
taille_memoire()
unsigned Zone_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Zone_VDF.cpp.
Member Data Documentation
h_x_
double Zone_VDF::h_x_ private
Definition at line 161 of file Zone_VDF.h.
Referenced by calcul_h(), h_x(), printOn(), and readOn().
h_y_
double Zone_VDF::h_y_ private
Definition at line 161 of file Zone_VDF.h.
Referenced by calcul_h(), h_y(), printOn(), and readOn().
h_z_
double Zone_VDF::h_z_ private
pas du maillage dans les trois directions d'espace;h_x_ (resp h_y_) est la plus petite distance entre deux centres de faces d'equation X = cte (resp Y= cte)
Definition at line 161 of file Zone_VDF.h.
Referenced by calcul_h(), h_z(), printOn(), and readOn().
info_obj
const Type_info Zone_VDF::info_obj static
Definition at line 66 of file Zone_VDF.h.
nb_aretes_
int Zone_VDF::nb_aretes_ private
nombre d'aretes tous types confondus
Definition at line 150 of file Zone_VDF.h.
Referenced by genere_aretes(), nb_aretes(), premiere_arete_interne(), premiere_arete_mixte(), printOn(), and readOn().
nb_aretes_bord_
int Zone_VDF::nb_aretes_bord_ private
nombre d'aretes bord
Definition at line 153 of file Zone_VDF.h.
Referenced by genere_aretes(), nb_aretes_bord(), printOn(), and readOn().
nb_aretes_coin_
int Zone_VDF::nb_aretes_coin_ private
nombre d'aretes coin
Definition at line 152 of file Zone_VDF.h.
Referenced by genere_aretes(), nb_aretes_coin(), premiere_arete_bord(), printOn(), and readOn().
nb_aretes_internes_
int Zone_VDF::nb_aretes_internes_ private
nombre d'aretes internes
Definition at line 155 of file Zone_VDF.h.
Referenced by genere_aretes(), nb_aretes_internes(), premiere_arete_interne(), premiere_arete_mixte(), printOn(), and readOn().
nb_aretes_joint_
int Zone_VDF::nb_aretes_joint_ private
nombre d'aretes joint
Definition at line 151 of file Zone_VDF.h.
Referenced by genere_aretes(), nb_aretes_joint(), premiere_arete_bord(), premiere_arete_coin(), printOn(), and readOn().
nb_aretes_mixtes_
int Zone_VDF::nb_aretes_mixtes_ private
nombre d'aretes mixtes
Definition at line 154 of file Zone_VDF.h.
Referenced by genere_aretes(), nb_aretes_mixtes(), premiere_arete_mixte(), printOn(), and readOn().
nb_faces_X_
int Zone_VDF::nb_faces_X_ private
nombre de faces perpendiculaires a l'axe des X
Definition at line 147 of file Zone_VDF.h.
Referenced by nb_faces_X(), printOn(), readOn(), and reordonner().
nb_faces_Y_
int Zone_VDF::nb_faces_Y_ private
nombre de faces perpendiculaires a l'axe des Y
Definition at line 148 of file Zone_VDF.h.
Referenced by nb_faces_Y(), printOn(), readOn(), and reordonner().
nb_faces_Z_
int Zone_VDF::nb_faces_Z_ private
nombre de faces perpendiculaires a l'axe des Z
Definition at line 149 of file Zone_VDF.h.
Referenced by nb_faces_Z(), printOn(), readOn(), and reordonner().
orientation_
IntVect Zone_VDF::orientation_ private
orientation des faces 0 si face perpendiculaire a l'axe des X 1 si face perpendiculaire a l'axe des Y 2 si face perpendiculaire a l'axe des Z
Definition at line 143 of file Zone_VDF.h.
Referenced by amont_amont(), calculer_volumes_entrelaces(), discretiser(), dist_face_elem0(), dist_face_elem0_axi(), dist_face_elem0_period(), dist_face_elem1(), dist_face_elem1_axi(), dist_face_elem1_period(), dist_norm(), dist_norm_axi(), dist_norm_bord(), dist_norm_bord_axi(), dist_norm_period(), distance_face(), distance_normale(), elem_voisin(), modifier_pour_Cl(), orientation(), printOn(), readOn(), and reordonner().
Qdm_
IntTab Zone_VDF::Qdm_ private
connectivites aretes/faces DoubleVect porosite_elem_; // Porosites volumiques pour les volumes de controle de masse DoubleVect porosite_face_; // Porosites surfaciques en masse et volumiques en quantite de mouvement
Definition at line 156 of file Zone_VDF.h.
Referenced by genere_aretes(), modifier_pour_Cl(), printOn(), Qdm(), and readOn().
virt_e_map
std::map<std::array<int, 2>, int> Zone_VDF::virt_e_map mutable
Definition at line 139 of file Zone_VDF.h.
Referenced by init_virt_e_map(), and Echange_contact_VDF::initialiser().
The documentation for this class was generated from the following files:
src/VDF/Zones/Zone_VDF.h
src/VDF/Zones/Zone_VDF.cpp