TRUST: Champ_Tabule_Morceaux Class Reference
Champ_Tabule_Morceaux Class Reference
: class Champ_Tabule_Morceaux
<Description of class Champ_Tabule_Morceaux>
#include <Champ_Tabule_Morceaux.h>
Public Member Functions
Champ_Tabule_Morceaux ()
~Champ_Tabule_Morceaux ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (const double &un_temps)
NE FAIT RIEN
A surcharger dans les classes derivees
Provoque l'initialisation du champ si necessaire.
virtual void mettre_a_jour (double un_temps)
NE FAIT RIEN
Mise a jour en temps.
int nb_champs_tabules () const
Champ_Fonc_Tabule & champ_tabule (int i)
const Champ_Fonc_Tabule & champ_tabule (int i) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Tabule_Morceaux & self_cast (Objet_U &)
static const
Champ_Tabule_Morceaux & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a:
Champ_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a:
Champ_base::readOn(Entree&)
void calculer_champ_tabule_morceaux ()
Protected Attributes
List_Champ_Fonc_Tabule champs_tabules
List_Ref_Sous_Zone les_sous_zones
Ref_Domaine mon_domaine
IntTab num_zone_
Detailed Description
: class Champ_Tabule_Morceaux
<Description of class Champ_Tabule_Morceaux>
Definition at line 40 of file Champ_Tabule_Morceaux.h.
Constructor & Destructor Documentation
Champ_Tabule_Morceaux::Champ_Tabule_Morceaux ()
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
Champ_Tabule_Morceaux::~Champ_Tabule_Morceaux ()
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
Member Function Documentation
void Champ_Tabule_Morceaux::calculer_champ_tabule_morceaux () [protected]
Definition at line 80 of file Champ_Tabule_Morceaux.cpp.
References champs_tabules, CONST_LIST_CURSEUR, DoubleVect::echange_espace_virtuel(), les_sous_zones, Field_base::nb_comp(), Sous_Zone::nb_elem_tot(), REF, valeur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
{
  CONST_LIST_CURSEUR(REF(Sous_Zone)) curseur1(les_sous_zones);
  CONST_LIST_CURSEUR(Champ_Fonc_Tabule) curseur2(champs_tabules);
  if (nb_comp() == 1)
    {
      DoubleVect& mes_valeurs = valeurs();
      while(curseur1)
        {
          const Sous_Zone& ssz = (curseur1.valeur()).valeur();
          const DoubleTab& vals_champ = curseur2.valeur().valeurs();
          for( int poly=0; poly<ssz.nb_elem_tot(); poly++)
            mes_valeurs(ssz(poly)) = vals_champ(ssz(poly));
          ++curseur1;
          ++curseur2;
        }
    }
  else
    {
      DoubleTab& mes_valeurs = valeurs();
      int k,dim = nb_comp();
      while(curseur1)
        {
          const Sous_Zone& ssz = (curseur1.valeur()).valeur();
          const DoubleTab& vals_champ = curseur2.valeur().valeurs();
          for(int poly=0; poly<ssz.nb_elem_tot(); poly++)
            for( k=0; k< dim; k++)
              mes_valeurs(ssz(poly),k) = vals_champ(ssz(poly),k);
          ++curseur1;
          ++curseur2;
        }
    }
  valeurs().echange_espace_virtuel();
}
Champ_Fonc_Tabule& Champ_Tabule_Morceaux::champ_tabule (int i) [inline]
Definition at line 55 of file Champ_Tabule_Morceaux.h.
References champs_tabules.
Referenced by Milieu_base::discretiser().
  {
    return champs_tabules[i] ;
  }
const Champ_Fonc_Tabule& Champ_Tabule_Morceaux::champ_tabule (int i) const [inline]
Definition at line 59 of file Champ_Tabule_Morceaux.h.
References champs_tabules.
  {
    return champs_tabules[i];
  }
Objet_U * Champ_Tabule_Morceaux::cree_instance () [static]
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
int Champ_Tabule_Morceaux::duplique () const [virtual]
Implements Champ_Don_base.
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
const Type_info * Champ_Tabule_Morceaux::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
const Type_info * Champ_Tabule_Morceaux::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
int Champ_Tabule_Morceaux::initialiser (const double & temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Provoque l'initialisation du champ si necessaire.
Reimplemented from Champ_Don_base.
Definition at line 123 of file Champ_Tabule_Morceaux.cpp.
References CONST_LIST_CURSEUR, les_sous_zones, Sous_Zone::nb_elem_tot(), num_zone_, REF, and valeur().
{
  num_zone_ = -1;
  CONST_LIST_CURSEUR(REF(Sous_Zone)) curseur1(les_sous_zones);
  int k=0;
  while(curseur1)
    {
      const Sous_Zone& ssz = (curseur1.valeur()).valeur();
      for( int poly=0; poly<ssz.nb_elem_tot(); poly++)
        {
          int elem= ssz(poly);
          num_zone_[elem] = k;
        }
      ++curseur1;
      ++k;
    }
  return Champ_Don_base::initialiser(un_temps);
}
void Champ_Tabule_Morceaux::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
Mise a jour en temps.
Reimplemented from Champ_Don_base.
Definition at line 144 of file Champ_Tabule_Morceaux.cpp.
References calculer_champ_tabule_morceaux(), champs_tabules, and nb_champs_tabules().
{
  for (int i=0; i<nb_champs_tabules(); i++)
    champs_tabules[i].mettre_a_jour(un_temps);
  calculer_champ_tabule_morceaux();
}
int Champ_Tabule_Morceaux::nb_champs_tabules () const [inline]
Definition at line 50 of file Champ_Tabule_Morceaux.h.
References champs_tabules, and liste::size().
Referenced by Milieu_base::discretiser(), mettre_a_jour(), valeur_a_elem_compo(), and valeur_aux_elems().
  {
    return champs_tabules.size();
  }
Sortie & Champ_Tabule_Morceaux::printOn (Sortie & os) const [protected, virtual]
Simple appel a:
Champ_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 34 of file Champ_Tabule_Morceaux.cpp.
{
  Champ_Don_base::printOn( os );
  return os;
}
Entree & Champ_Tabule_Morceaux::readOn (Entree & is) [protected, virtual]
Simple appel a:
Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 40 of file Champ_Tabule_Morceaux.cpp.
References List_Champ_Fonc_Tabule::add(), List_Ref_Sous_Zone::add(), Cerr, champs_tabules, Domaine::creer_tableau_elements(), Process::exit(), finl, Field_base::fixer_nb_comp(), les_sous_zones, Champ_Proto::lire_dimension(), mon_domaine, num_zone_, Interprete::objet(), Objet_U::que_suis_je(), ref_cast, DoubleTab::resize(), Domaine::ss_zone(), Ref_Domaine::valeur(), and Champ_Don_base::valeurs_.
{
  Motcle motlu;
  Nom nom;
  is >> nom;
  mon_domaine = ref_cast(Domaine, Interprete::objet(nom));
  Domaine& le_domaine=mon_domaine.valeur();
  int dim=lire_dimension(is,que_suis_je());
  fixer_nb_comp(dim);
  valeurs_.resize(0, dim);
  le_domaine.creer_tableau_elements(valeurs_);
  le_domaine.creer_tableau_elements(num_zone_);
  is >> nom;
  motlu=nom;
  if(motlu != Motcle("{") )
    {
      Cerr << "Error while reading a " << que_suis_je() << finl;
      Cerr << "We expected a { instead of " << nom << finl;
      exit();
    }
  is >> nom;
  motlu=nom;
  while (motlu != Motcle("}") )
    {
      les_sous_zones.add(le_domaine.ss_zone(nom));
      Champ_Fonc_Tabule ch_tab;
      is >> ch_tab;
      champs_tabules.add(ch_tab);
      is >> nom;
      motlu=nom;
    }
  return is;
}
const Champ_Tabule_Morceaux & Champ_Tabule_Morceaux::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
Champ_Tabule_Morceaux & Champ_Tabule_Morceaux::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Don_base.
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
unsigned Champ_Tabule_Morceaux::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Champ_Tabule_Morceaux.cpp.
double Champ_Tabule_Morceaux::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 176 of file Champ_Tabule_Morceaux.cpp.
References champs_tabules, nb_champs_tabules(), num_zone_, and liste::size().
{
  DoubleTab tab(nb_champs_tabules());
  for (int i=0; i<champs_tabules.size(); i++)
    tab[i] = champs_tabules[i].valeur_a_elem_compo(position,le_poly,ncomp);
  int izone = num_zone_[le_poly];
  return tab[izone];
}
DoubleTab & Champ_Tabule_Morceaux::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 154 of file Champ_Tabule_Morceaux.cpp.
References champs_tabules, DoubleVect::line_size(), nb_champs_tabules(), num_zone_, IntVect::size(), and liste::size().
{
  DoubleTabs tabs(nb_champs_tabules());
  for (int i=0; i<champs_tabules.size(); i++)
    tabs[i] = champs_tabules[i].valeur_aux_elems(positions,les_polys,val);
  for( int i=0; i<les_polys.size(); i++)
    {
      int elem= les_polys[i];
      int izone = num_zone_[elem];
      for (int j=0; j<val.line_size() ; j++)
        val(i,j) = tabs[izone](i,j);
    }
  return val;
}
Member Data Documentation
List_Champ_Fonc_Tabule Champ_Tabule_Morceaux::champs_tabules [protected]
Definition at line 72 of file Champ_Tabule_Morceaux.h.
Referenced by calculer_champ_tabule_morceaux(), champ_tabule(), mettre_a_jour(), nb_champs_tabules(), readOn(), valeur_a_elem_compo(), and valeur_aux_elems().
const Type_info Champ_Tabule_Morceaux::info_obj [static]
Reimplemented from Champ_Don_base.
Definition at line 43 of file Champ_Tabule_Morceaux.h.
List_Ref_Sous_Zone Champ_Tabule_Morceaux::les_sous_zones [protected]
Definition at line 74 of file Champ_Tabule_Morceaux.h.
Referenced by calculer_champ_tabule_morceaux(), initialiser(), and readOn().
Ref_Domaine Champ_Tabule_Morceaux::mon_domaine [protected]
Definition at line 75 of file Champ_Tabule_Morceaux.h.
Referenced by readOn().
IntTab Champ_Tabule_Morceaux::num_zone_ [protected]
Definition at line 78 of file Champ_Tabule_Morceaux.h.
Referenced by initialiser(), readOn(), valeur_a_elem_compo(), and valeur_aux_elems().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Tabule_Morceaux.h
src/Kernel/Champs/Champ_Tabule_Morceaux.cpp