TRUST: Deriv_Elem_PolyMAC_base Class Reference
Deriv_Elem_PolyMAC_base Class Reference
#include <Elem_PolyMAC.h>
Public Member Functions
~Deriv_Elem_PolyMAC_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Elem_PolyMAC_base ()
Deriv_Elem_PolyMAC_base (const Deriv_Elem_PolyMAC_base &)
const Elem_PolyMAC_base & valeur () const
Elem_PolyMAC_base & valeur ()
const Elem_PolyMAC_base * operator-> () const
Elem_PolyMAC_base * operator-> ()
const Deriv_Elem_PolyMAC_base & operator= (const Elem_PolyMAC_base &)
const Deriv_Elem_PolyMAC_base & operator= (const Deriv_Elem_PolyMAC_base &)
operator const Elem_PolyMAC_base & () const
operator Elem_PolyMAC_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Elem_PolyMAC_base & self_cast (Objet_U &)
static const
Deriv_Elem_PolyMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Elem_PolyMAC_base * pointeur_
Detailed Description
Definition at line 41 of file Elem_PolyMAC.h.
Constructor & Destructor Documentation
Deriv_Elem_PolyMAC_base::~Deriv_Elem_PolyMAC_base ()
Definition at line 29 of file Elem_PolyMAC.cpp.
Deriv_Elem_PolyMAC_base::Deriv_Elem_PolyMAC_base ()
Definition at line 29 of file Elem_PolyMAC.cpp.
Deriv_Elem_PolyMAC_base::Deriv_Elem_PolyMAC_base (const Deriv_Elem_PolyMAC_base & t)
Definition at line 29 of file Elem_PolyMAC.cpp.
Member Function Documentation
Objet_U * Deriv_Elem_PolyMAC_base::cree_instance () [static]
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
int Deriv_Elem_PolyMAC_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
const Type_info * Deriv_Elem_PolyMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
const Type_info & Deriv_Elem_PolyMAC_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 29 of file Elem_PolyMAC.cpp.
const Type_info * Deriv_Elem_PolyMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
Deriv_Elem_PolyMAC_base::operator const Elem_PolyMAC_base & () const
Definition at line 29 of file Elem_PolyMAC.cpp.
Deriv_Elem_PolyMAC_base::operator Elem_PolyMAC_base & ()
Definition at line 29 of file Elem_PolyMAC.cpp.
const Elem_PolyMAC_base * Deriv_Elem_PolyMAC_base::operator-> () const [inline]
Definition at line 41 of file Elem_PolyMAC.h.
: public DERIV(Elem_PolyMAC_base)
Elem_PolyMAC_base * Deriv_Elem_PolyMAC_base::operator-> () [inline]
Definition at line 41 of file Elem_PolyMAC.h.
: public DERIV(Elem_PolyMAC_base)
const Deriv_Elem_PolyMAC_base & Deriv_Elem_PolyMAC_base::operator= (const Deriv_Elem_PolyMAC_base & t)
Definition at line 29 of file Elem_PolyMAC.cpp.
const Deriv_Elem_PolyMAC_base & Deriv_Elem_PolyMAC_base::operator= (const Elem_PolyMAC_base & t)
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
Sortie & Deriv_Elem_PolyMAC_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
Entree & Deriv_Elem_PolyMAC_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
const Deriv_Elem_PolyMAC_base & Deriv_Elem_PolyMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
Deriv_Elem_PolyMAC_base & Deriv_Elem_PolyMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
void Deriv_Elem_PolyMAC_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 29 of file Elem_PolyMAC.cpp.
unsigned Deriv_Elem_PolyMAC_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Elem_PolyMAC.
Definition at line 29 of file Elem_PolyMAC.cpp.
const Elem_PolyMAC_base & Deriv_Elem_PolyMAC_base::valeur () const [inline]
Definition at line 41 of file Elem_PolyMAC.h.
Referenced by Zone_PolyMAC::discretiser(), Elem_PolyMAC::normale(), Elem_PolyMAC::printOn(), Elem_PolyMAC::typer(), and PolyMAC_discretisation::vorticite().
: public DERIV(Elem_PolyMAC_base)
Elem_PolyMAC_base & Deriv_Elem_PolyMAC_base::valeur () [inline]
Definition at line 41 of file Elem_PolyMAC.h.
: public DERIV(Elem_PolyMAC_base)
Member Data Documentation
const Type_info Deriv_Elem_PolyMAC_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Elem_PolyMAC.
Definition at line 41 of file Elem_PolyMAC.h.
Elem_PolyMAC_base* Deriv_Elem_PolyMAC_base::pointeur_ [private]
Definition at line 41 of file Elem_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Elem_PolyMAC.h
src/PolyMAC/Zones/Elem_PolyMAC.cpp