TRUST: RRK2 Class Reference
RRK2 Class Reference
classe RRK2
Cette classe represente un schema de Runge Kutta
rationel d'ordre 2 qui s'ecrit:
U(n+1) = U(n) + (2g1 (g1,b) - b(g1,g1))/(b,b)
ou : g1 = dt f(U(n))
g2 = dt f(U(n) + c2 g1)
b = b1 g1 + b2 g2
on choisit b1=2, b2=-1, c2=1/2
#include <RRK2.h>
Public Member Functions
RRK2 ()
~RRK2 ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
virtual int nb_valeurs_futures () const
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
virtual double temps_futur (int i) const
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
virtual double temps_defaut () const
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)
Effectue un pas de temps de Runge Kutta rationel d'ordre 2,
sur l'equation passee en parametre.
Le schema de Runge Kutta rationel d'ordre 2:
g1=hf(y0)
g2=hf(y0+c2g1)
y1=y0+(g1g1)/(b1g1+b2g2)
ou ab/d = (a(b,d)+b(d,a)-d(a,b)/(d,d)
y1=y0+(2g1(g1,b1g1+b2g2)-(b1g1+b2g2)(g1,g1)/(b1g1+b2g2,b1g1+b2g2)
y1=y0+(2g1(g1,"g2")-("g2")(g1,g1)/("g2","g2")
ordre2 si b2c2=-1/2
b2c2<=-1/2 A0 stabilite et I stabilite
b2c2<= 1/(2cos(alpha)(2-cos(alpha))) O<=alpha<pi/2 Aalpha stabilite.
void completer ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static RRK2 & self_cast (Objet_U &)
static const RRK2 & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Detailed Description
classe RRK2
Cette classe represente un schema de Runge Kutta
rationel d'ordre 2 qui s'ecrit:
U(n+1) = U(n) + (2g1 (g1,b) - b(g1,g1))/(b,b)
ou : g1 = dt f(U(n))
g2 = dt f(U(n) + c2 g1)
b = b1 g1 + b2 g2
on choisit b1=2, b2=-1, c2=1/2
Definition at line 62 of file RRK2.h.
Constructor & Destructor Documentation
RRK2::RRK2 ()
Definition at line 27 of file RRK2.cpp.
RRK2::~RRK2 ()
Definition at line 27 of file RRK2.cpp.
Member Function Documentation
void RRK2::completer (void) [inline, virtual]
Implements Schema_Temps_base.
Definition at line 90 of file RRK2.h.
{
}
Objet_U * RRK2::cree_instance () [static]
Definition at line 27 of file RRK2.cpp.
int RRK2::duplique () const [virtual]
Implements Schema_Temps_base.
Definition at line 27 of file RRK2.cpp.
int RRK2::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) [virtual]
Effectue un pas de temps de Runge Kutta rationel d'ordre 2,
sur l'equation passee en parametre.
Le schema de Runge Kutta rationel d'ordre 2:
g1=hf(y0)
g2=hf(y0+c2g1)
y1=y0+(g1g1)/(b1g1+b2g2)
ou ab/d = (a(b,d)+b(d,a)-d(a,b)/(d,d)
y1=y0+(2g1(g1,b1g1+b2g2)-(b1g1+b2g2)(g1,g1)/(b1g1+b2g2,b1g1+b2g2)
y1=y0+(2g1(g1,"g2")-("g2")(g1,g1)/("g2","g2")
ordre2 si b2c2=-1/2
b2c2<=-1/2 A0 stabilite et I stabilite
b2c2<= 1/(2cos(alpha)(2-cos(alpha))) O<=alpha<pi/2 Aalpha stabilite.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Implements Schema_Temps_base.
Definition at line 145 of file RRK2.cpp.
References DoubleVect::ajoute(), Cerr, Equation_base::derivee_en_temps_inco(), DMINFLOAT, Schema_Temps_base::dt_, DoubleVect::echange_espace_virtuel(), Schema_Temps_base::facsec_, finl, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), mp_carre_norme_vect(), mp_prodscal(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
{
// Warning sur les 100 premiers pas de temps si facsec est egal a 1
// pour faire reflechir l'utilisateur
  int nw = 100;
  if ( nb_pas_dt()>=0 && nb_pas_dt()<=nw && facsec_ == 1 )
    {
      Cerr << finl << "**** Advice (printed only on the first " << nw << " time steps)****" << finl;
      Cerr << "You are using Runge Kutta schema order 2 so if you wish to increase the time step, try facsec between 1 and 2." << finl;
    }
  double b1=2.0;
  double c2=0.5;
  double b2=-1;
  DoubleTab& present=eqn.inconnue().valeurs();
  DoubleTab& futur=eqn.inconnue().futur();
// g1=futur=f(y0)
  DoubleTab g1(present) ;
  DoubleTab g2(present) ;
// sauv=y0
  DoubleTrav sauv(present);
  sauv=present;
  eqn.derivee_en_temps_inco(g1);
// g1=hf(y0)
  g1*=dt_;
// present=y0+c2g1
  present.ajoute(c2, g1);
// g2=futur=f(y0+c2g1)
  eqn.derivee_en_temps_inco(g2);
// g2=b2"g2"
  g2*=(b2*dt_);
// g2=b2"g2" + b1g1
  g2.ajoute(b1, g1);
// normeg2=("g2","g2")
  double normeg2 = mp_carre_norme_vect(g2) + DMINFLOAT;
// normeg1=-(g1,g1)
  double normeg1 = - mp_carre_norme_vect(g1);
// psc1=2(g1,"g2")
  double psc1 = 2.0 * mp_prodscal(g1, g2);
// y1=y0+(2g1(g1,"g2")-("g2")(g1,g1)/("g2","g2")
  futur=g1;
  futur*=psc1;
  futur.ajoute(normeg1, g2);
  futur/=normeg2;
  present=sauv;
  futur /= dt_;
  update_critere_statio(futur, eqn);
  futur *= dt_;
  futur+=sauv;
  eqn.zone_Cl_dis().imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
  futur.echange_espace_virtuel();
  return 1;
}
const Type_info * RRK2::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 27 of file RRK2.cpp.
const Type_info * RRK2::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 27 of file RRK2.cpp.
int RRK2::nb_valeurs_futures () const [virtual]
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
Definition at line 89 of file RRK2.cpp.
{
  return 1 ;
}
int RRK2::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
Implements Schema_Temps_base.
Definition at line 81 of file RRK2.cpp.
{
  return 2 ;
}
Sortie & RRK2::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 45 of file RRK2.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
Entree & RRK2::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 66 of file RRK2.cpp.
{
  return Schema_Temps_base::readOn(s) ;
}
const RRK2 & RRK2::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Temps_base.
Definition at line 27 of file RRK2.cpp.
RRK2 & RRK2::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Temps_base.
Definition at line 27 of file RRK2.cpp.
unsigned RRK2::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file RRK2.cpp.
double RRK2::temps_defaut () const [virtual]
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 107 of file RRK2.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  return temps_courant()+pas_de_temps();
}
double RRK2::temps_futur (int i) const [virtual]
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 97 of file RRK2.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  assert(i==1);
  return temps_courant()+pas_de_temps();
}
Member Data Documentation
const Type_info RRK2::info_obj [static]
Reimplemented from Schema_Temps_base.
Definition at line 65 of file RRK2.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/RRK2.h
src/Kernel/Schemas_Temps/RRK2.cpp