TRUST: Eval_Dift_VDF_const Class Reference
Eval_Dift_VDF_const Class Reference
class Eval_Dift_VDF_const
Cette classe represente un evaluateur de flux diffusif
total (diffusion laminaire et turbulente)
avec une diffusivite constante en espace.
#include <Eval_Dift_VDF_const.h>
Public Member Functions
void mettre_a_jour () override
void associer_diff_turb (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double nu_t_impl (int i, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face2 (int i, int j, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double get_equivalent_distance (int boundary_index, int local_face) const override
Public Member Functions inherited from Eval_Diff_VDF_const
Eval_Diff_VDF_const ()
void associer (const Champ_base &) override
void mettre_a_jour () override
const Champ_base & get_diffusivite () const override
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face (int i, int j, int k, int l, int compo) const
double nu_lam_impl_face2 (int i, int j, int compo) const
double nu_t_impl (int i, int compo) const
double tau_tan_impl (int i, int j) const
bool uses_wall () const
bool uses_mod () const
const DoubleTab & get_k_elem () const
pour F5 seulement ...
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Public Member Functions inherited from Eval_Turbulence
virtual ~Eval_Turbulence ()
virtual void associer_loipar (const Turbulence_paroi_scal &loi_paroi)
virtual void init_ind_fluctu_term ()
void update_equivalent_distance ()
Protected Attributes
Ref_Champ_Fonc diffusivite_turbulente_
DoubleVect dv_diffusivite_turbulente
Protected Attributes inherited from Eval_Diff_VDF_const
Ref_Champ_Uniforme diffusivite_
double db_diffusivite
Protected Attributes inherited from Eval_Turbulence
Ref_Turbulence_paroi_scal loipar
DoubleVects equivalent_distance
Detailed Description
class Eval_Dift_VDF_const
Cette classe represente un evaluateur de flux diffusif
total (diffusion laminaire et turbulente)
avec une diffusivite constante en espace.
Definition at line 33 of file Eval_Dift_VDF_const.h.
Member Function Documentation
associer_diff_turb()
void Eval_Dift_VDF_const::associer_diff_turb (const Champ_Fonc & diff_turb) inline
Definition at line 95 of file Eval_Dift_VDF_const.h.
{
  diffusivite_turbulente_ = diff_turb;
  dv_diffusivite_turbulente.ref(diff_turb.valeurs());
}
References diffusivite_turbulente_, dv_diffusivite_turbulente, TRUSTVect< _TYPE_ >::ref(), and Champ_Fonc::valeurs().
compute_heq_impl()
double Eval_Dift_VDF_const::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
Definition at line 72 of file Eval_Dift_VDF_const.h.
  {
    const double heq_lam = Eval_Diff_VDF_const::compute_heq_impl(d0, i, d1, j, compo);
    const double heq_turb= 0.5*(dv_diffusivite_turbulente(i)+dv_diffusivite_turbulente(j))/(d1+d0);
    return heq_lam + heq_turb;
  }
References Eval_Diff_VDF_const::compute_heq_impl(), and dv_diffusivite_turbulente.
diffusivite_turbulente()
const Champ_Fonc & Eval_Dift_VDF_const::diffusivite_turbulente () const inline
Definition at line 38 of file Eval_Dift_VDF_const.h.
{ return diffusivite_turbulente_.valeur(); }
References diffusivite_turbulente_, and Ref_Champ_Fonc::valeur().
Referenced by Op_Dift_VDF_base::ajouter_blocs(), and Op_Dift_VDF_base::contribuer_au_second_membre().
get_equivalent_distance()
double Eval_Dift_VDF_const::get_equivalent_distance (int boundary_index, int local_face) const inline override virtual
Reimplemented from Eval_Diff_VDF.
Definition at line 79 of file Eval_Dift_VDF_const.h.
  {
    return equivalent_distance[boundary_index](local_face);
  }
References Eval_Turbulence::equivalent_distance.
mettre_a_jour()
void Eval_Dift_VDF_const::mettre_a_jour () inline override virtual
< from Eval_Turbulence
Reimplemented from Eval_Diff_VDF_const.
Reimplemented in Eval_Dift_VDF_const_Face.
Definition at line 89 of file Eval_Dift_VDF_const.h.
{
  Eval_Diff_VDF_const::mettre_a_jour();
  update_equivalent_distance();  //!< from Eval_Turbulence
}
References Eval_Diff_VDF_const::mettre_a_jour(), and Eval_Turbulence::update_equivalent_distance().
Referenced by Eval_Dift_VDF_const_Face::mettre_a_jour().
nu_1_impl()
double Eval_Dift_VDF_const::nu_1_impl (int i, int compo) const inline
Definition at line 41 of file Eval_Dift_VDF_const.h.
  {
    const double nu_lam = Eval_Diff_VDF_const::nu_1_impl(i,compo);
    const double nu_turb = dv_diffusivite_turbulente(i);
    return nu_lam+nu_turb;
  }
References dv_diffusivite_turbulente, and Eval_Diff_VDF_const::nu_1_impl().
nu_1_impl_face()
double Eval_Dift_VDF_const::nu_1_impl_face (int i, int j, int compo) const inline
Definition at line 51 of file Eval_Dift_VDF_const.h.
  {
    return 0.5*(dv_diffusivite_turbulente(i)+dv_diffusivite_turbulente(j));
  }
References dv_diffusivite_turbulente.
nu_2_impl()
double Eval_Dift_VDF_const::nu_2_impl (int i, int compo) const inline
Definition at line 48 of file Eval_Dift_VDF_const.h.
{ return Eval_Diff_VDF_const::nu_2_impl(i,compo); }
References Eval_Diff_VDF_const::nu_2_impl().
nu_2_impl_face()
double Eval_Dift_VDF_const::nu_2_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 56 of file Eval_Dift_VDF_const.h.
  {
    return 0.25*(dv_diffusivite_turbulente(i)+dv_diffusivite_turbulente(j)+
                 dv_diffusivite_turbulente(k)+dv_diffusivite_turbulente(l));
  }
References dv_diffusivite_turbulente.
nu_lam_impl_face()
double Eval_Dift_VDF_const::nu_lam_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 62 of file Eval_Dift_VDF_const.h.
  {
    return Eval_Diff_VDF_const::nu_2_impl_face(i,j,k,l,compo);
  }
References Eval_Diff_VDF_const::nu_2_impl_face().
nu_lam_impl_face2()
double Eval_Dift_VDF_const::nu_lam_impl_face2 (int i, int j, int compo) const inline
Definition at line 67 of file Eval_Dift_VDF_const.h.
  {
    return Eval_Diff_VDF_const::nu_1_impl_face(i,j,compo);
  }
References Eval_Diff_VDF_const::nu_1_impl_face().
nu_t_impl()
double Eval_Dift_VDF_const::nu_t_impl (int i, int compo) const inline
Definition at line 49 of file Eval_Dift_VDF_const.h.
{ return dv_diffusivite_turbulente(i);  }
References dv_diffusivite_turbulente.
Member Data Documentation
diffusivite_turbulente_
Ref_Champ_Fonc Eval_Dift_VDF_const::diffusivite_turbulente_ protected
Definition at line 85 of file Eval_Dift_VDF_const.h.
Referenced by associer_diff_turb(), and diffusivite_turbulente().
dv_diffusivite_turbulente
DoubleVect Eval_Dift_VDF_const::dv_diffusivite_turbulente protected
Definition at line 86 of file Eval_Dift_VDF_const.h.
Referenced by associer_diff_turb(), compute_heq_impl(), nu_1_impl(), nu_1_impl_face(), nu_2_impl_face(), and nu_t_impl().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Dift_VDF_const.h