TRUST: Reordonner Class Reference
Reordonner Class Reference
Classe Reordonner
Cette classe est un interprete qui sert a lire la directive Reordonner
qui reordonne les noeuds d'un domaine.
Reordonner dom.
#include <Reordonner.h>
Public Member Functions
Reordonner ()
~Reordonner ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
Fonction principale de l'interprete Mailler
Reordonne les noeuds du domaine specifie par
la directive.
Reordonner dom.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Reordonner & self_cast (Objet_U &)
static const Reordonner & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de
sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Detailed Description
Classe Reordonner
Cette classe est un interprete qui sert a lire la directive Reordonner
qui reordonne les noeuds d'un domaine.
Reordonner dom.
Definition at line 37 of file Reordonner.h.
Constructor & Destructor Documentation
Reordonner::Reordonner ()
Definition at line 26 of file Reordonner.cpp.
Reordonner::~Reordonner ()
Definition at line 26 of file Reordonner.cpp.
Member Function Documentation
Objet_U * Reordonner::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Reordonner.cpp.
int Reordonner::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 26 of file Reordonner.cpp.
const Type_info * Reordonner::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reordonner.cpp.
const Type_info * Reordonner::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reordonner.cpp.
Entree & Reordonner::interpreter_ (Entree & is) [virtual]
Fonction principale de l'interprete Mailler
Reordonne les noeuds du domaine specifie par
la directive.
Reordonner dom.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 87 of file Reordonner.cpp.
References Interprete_geometrique_base::associer_domaine(), Interprete_geometrique_base::domaine(), and Domaine::reordonner().
{
  associer_domaine(is);
  domaine().reordonner();
  return is;
}
Sortie & Reordonner::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de
sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 44 of file Reordonner.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Reordonner::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 64 of file Reordonner.cpp.
{
  return is;
}
Reordonner & Reordonner::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reordonner.cpp.
const Reordonner & Reordonner::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Reordonner.cpp.
unsigned Reordonner::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Reordonner.cpp.
Member Data Documentation
const Type_info Reordonner::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 40 of file Reordonner.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Reordonner.h
src/Kernel/Geometrie/Reordonner.cpp