TRUST: Eval_Puiss_Th_QC_VDF_Elem Class Reference
Eval_Puiss_Th_QC_VDF_Elem Class Reference
#include <Eval_Puiss_Th_QC_VDF_Elem.h>
Public Member Functions
Eval_Puiss_Th_QC_VDF_Elem ()
void associer_puissance (const Champ_Don &Q)
void mettre_a_jour ()
double calculer_terme_source (int) const
void calculer_terme_source (int, DoubleVect &) const
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
Detailed Description
Definition at line 37 of file Eval_Puiss_Th_QC_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Puiss_Th_QC_VDF_Elem::Eval_Puiss_Th_QC_VDF_Elem () [inline]
Definition at line 58 of file Eval_Puiss_Th_QC_VDF_Elem.h.
{}
Member Function Documentation
void Eval_Puiss_Th_QC_VDF_Elem::associer_puissance (const Champ_Don & Q)
Definition at line 26 of file Eval_Puiss_Th_QC_VDF_Elem.cpp.
References la_puissance, puissance, DoubleTab::ref(), and Champ_Don::valeurs().
Referenced by Terme_Puissance_Thermique_QC_VDF_Elem::associer_pb().
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
void Eval_Puiss_Th_QC_VDF_Elem::calculer_terme_source (int , DoubleVect &) const [inline, virtual]
Implements Evaluateur_Source_VDF.
Definition at line 65 of file Eval_Puiss_Th_QC_VDF_Elem.h.
{
  ;
}
double Eval_Puiss_Th_QC_VDF_Elem::calculer_terme_source (int num_elem) const [inline, virtual]
Implements Evaluateur_Source_VDF.
Definition at line 59 of file Eval_Puiss_Th_QC_VDF_Elem.h.
References Evaluateur_Source_VDF_Elem::porosite_vol, puissance, ArrOfDouble::size_array(), and Evaluateur_Source_VDF_Elem::volumes.
{
  const int k = (puissance.size_array() == 1) ? 0 : num_elem;
  return puissance(k, 0) * volumes(num_elem) * porosite_vol(num_elem);
}
void Eval_Puiss_Th_QC_VDF_Elem::mettre_a_jour () [virtual]
Implements Evaluateur_Source_VDF.
Definition at line 32 of file Eval_Puiss_Th_QC_VDF_Elem.cpp.
{
}
Member Data Documentation
Ref_Champ_Don Eval_Puiss_Th_QC_VDF_Elem::la_puissance [protected]
Definition at line 50 of file Eval_Puiss_Th_QC_VDF_Elem.h.
Referenced by associer_puissance().
DoubleTab Eval_Puiss_Th_QC_VDF_Elem::puissance [protected]
Definition at line 51 of file Eval_Puiss_Th_QC_VDF_Elem.h.
Referenced by associer_puissance(), and calculer_terme_source().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Eval_Puiss_Th_QC_VDF_Elem.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Eval_Puiss_Th_QC_VDF_Elem.cpp