TRUST: Eval_Puiss_Th_EF Class Reference
Eval_Puiss_Th_EF Class Reference
#include <Eval_Puiss_Th_EF.h>
Public Member Functions
void completer () override
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
Public Member Functions inherited from Evaluateur_Source_EF_Som
Evaluateur_Source_EF_Som ()
Evaluateur_Source_EF_Som (const Evaluateur_Source_EF_Som &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
Public Member Functions inherited from Evaluateur_Source_EF
Evaluateur_Source_EF ()
virtual ~Evaluateur_Source_EF ()
Evaluateur_Source_EF (const Evaluateur_Source_EF &)
void associer_zones (const Zone_EF &, const Zone_Cl_EF &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
Protected Attributes
Ref_Champ_Don la_puissance
DoubleTab puissance
Protected Attributes inherited from Evaluateur_Source_EF
Ref_Zone_EF la_zone
Ref_Zone_Cl_EF la_zone_cl
Detailed Description
Definition at line 33 of file Eval_Puiss_Th_EF.h.
Member Function Documentation
associer_champs()
void Eval_Puiss_Th_EF::associer_champs (const Champ_Don & Q)
Definition at line 26 of file Eval_Puiss_Th_EF.cpp.
{
  la_puissance = Q;
  puissance.ref(Q.valeurs());
}
References la_puissance, puissance, TRUSTTab< _TYPE_ >::ref(), and Champ_Don::valeurs().
Referenced by Puissance_Thermique_EF::associer_pb().
calculer_terme_source_standard() [1/2]
double Eval_Puiss_Th_EF::calculer_terme_source_standard (int num_elem) const inline override virtual
Implements Evaluateur_Source_EF_Som.
Definition at line 64 of file Eval_Puiss_Th_EF.h.
{
  double source;
  if (sub_type(Champ_Uniforme,la_puissance.valeur().valeur()))
    source = puissance(0,0);
  else
    source = puissance(num_elem,0);
  return (source);
}
References la_puissance, puissance, sub_type, Deriv_Champ_Don_base::valeur(), and Ref_Champ_Don::valeur().
Referenced by calculer_terme_source_standard().
calculer_terme_source_standard() [2/2]
void Eval_Puiss_Th_EF::calculer_terme_source_standard (int num_elem, DoubleVect & d) const inline override virtual
Implements Evaluateur_Source_EF_Som.
Definition at line 56 of file Eval_Puiss_Th_EF.h.
{
  Cerr<<"Non code"<<__FILE__<<(int)__LINE__<<finl;
  Process::exit();
  throw;
  return calculer_terme_source_standard(num_elem,d);
}
References calculer_terme_source_standard(), Cerr, Process::exit(), and finl.
completer()
void Eval_Puiss_Th_EF::completer () override virtual
Implements Evaluateur_Source_EF.
Definition at line 20 of file Eval_Puiss_Th_EF.cpp.
{
  Evaluateur_Source_EF_Som::completer();
// nb_som_elem_=(la_zone->zone().nb_som_elem());
}
References Evaluateur_Source_EF_Som::completer().
mettre_a_jour()
void Eval_Puiss_Th_EF::mettre_a_jour () override virtual
Implements Evaluateur_Source_EF.
Definition at line 32 of file Eval_Puiss_Th_EF.cpp.
{
}
Member Data Documentation
la_puissance
Ref_Champ_Don Eval_Puiss_Th_EF::la_puissance protected
Definition at line 46 of file Eval_Puiss_Th_EF.h.
Referenced by associer_champs(), and calculer_terme_source_standard().
puissance
DoubleTab Eval_Puiss_Th_EF::puissance protected
Definition at line 47 of file Eval_Puiss_Th_EF.h.
Referenced by associer_champs(), and calculer_terme_source_standard().
The documentation for this class was generated from the following files:
src/EF/Sources/Eval_Puiss_Th_EF.h
src/EF/Sources/Eval_Puiss_Th_EF.cpp