TRUST: Loi_Fermeture_base Class Reference
Loi_Fermeture_base Class Reference
: Classe de base des lois de fermetures.
Cette classe calcule des champs qui peuvent dependre
de plusieurs inconnues, de grandeurs physiques du milieu etc.
Les champs de la classe sont rendus accessibles a tout le probleme
a travers la methode get_champ() et leur mise a jour est declanchee
par le probleme, apres la mise a jour du milieu et des equations.
#include <Loi_Fermeture_base.h>
Public Member Functions
Loi_Fermeture_base ()
~Loi_Fermeture_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
La classe de base ne comprend aucun champ supplementaire.
const Champ_base & get_champ (const Motcle &nom) const override
Cette methode renvoie le champ de nom "nom" s'il est
compris par la classe, sinon appelle la methode get_champ de l'ancetre.
Dans la classe de base, on leve l'exception Champ_compris_erreur.
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void associer_pb_base (const Probleme_base &)
Cette methode est la premiere appelee par le probleme
pour construire l'objet au moment ou on l'associe au probleme.
On verifie qu'on est pas encore associe.
virtual void discretiser (const Discretisation_base &)
Cette methode est appelee par le probleme apres
la discretisation des equations et du milieu et avant
l'appel a readOn() pour lecture des parametres.
Dans les classes derivees elle doit discretiser au minimum les champs
qui seront requis dans le readOn() des equations ou des autres
lois de fermeture.
virtual void set_param (Param &param)
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour
ajouter dans "param" les differents parametres a lire
dans le jeu de donnees et appeler la methode de l'ancetre.
Dans la classe de base: aucun parametre.
virtual void completer ()
Cette methode est appelee apres avoir lu toutes les equations
et les lois de fermeture (tous les champs et les conditions aux limites
du probleme sont disponibles)
virtual void preparer_calcul ()
Cette methode est appelee par le probleme apres
preparer_calcul() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
virtual void mettre_a_jour (double temps)
Cette methode est appelee par le probleme apres
mettre_a_jour() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Loi_Fermeture_base & self_cast (Objet_U &)
static const Loi_Fermeture_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Types
enum Status {
INITIAL , PB_ASSOCIE , DISCRETISE , READON_FAIT ,
COMPLET
}
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Pour l'instant, exit()
Entree & readOn (Entree &) override
Cette methode appelle la methode set_param() pour
initialiser les parametres, puis lit les parametres.
Dans l'implementation des classes derivees on peut se contenter
d'appeler la methode de la classe de base et verifier les parametres.
const Probleme_base & mon_probleme () const
Renvoie le probleme (j'ai cree cette methode pour ne pas
donner acces au probleme en ecriture par la REF)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champs_compris champs_compris_
Status status_
Private Attributes
Nom nom_
Ref_Probleme_base mon_probleme_
Detailed Description
: Classe de base des lois de fermetures.
Cette classe calcule des champs qui peuvent dependre
de plusieurs inconnues, de grandeurs physiques du milieu etc.
Les champs de la classe sont rendus accessibles a tout le probleme
a travers la methode get_champ() et leur mise a jour est declanchee
par le probleme, apres la mise a jour du milieu et des equations.
Definition at line 34 of file Loi_Fermeture_base.h.
Member Enumeration Documentation
Status
enum Loi_Fermeture_base::Status protected
Enumerator
INITIAL
PB_ASSOCIE
DISCRETISE
READON_FAIT
COMPLET
Definition at line 64 of file Loi_Fermeture_base.h.
{ INITIAL, PB_ASSOCIE, DISCRETISE, READON_FAIT, COMPLET };
Constructor & Destructor Documentation
Loi_Fermeture_base()
Loi_Fermeture_base::Loi_Fermeture_base ()
Definition at line 26 of file Loi_Fermeture_base.cpp.
{
  status_ = INITIAL;
}
References INITIAL, and status_.
~Loi_Fermeture_base()
Loi_Fermeture_base::~Loi_Fermeture_base () override
Definition at line 23 of file Loi_Fermeture_base.cpp.
Member Function Documentation
associer_pb_base()
void Loi_Fermeture_base::associer_pb_base (const Probleme_base & pb) virtual
Cette methode est la premiere appelee par le probleme
pour construire l'objet au moment ou on l'associe au probleme.
On verifie qu'on est pas encore associe.
Definition at line 34 of file Loi_Fermeture_base.cpp.
{
  if (status_ == PB_ASSOCIE)
    {
      Cerr << "Error associating " << que_suis_je() << " " << le_nom();
      Cerr << " to problem " << pb.que_suis_je();
      Cerr  << ".\n This object is already associated to problem " << mon_probleme().le_nom() << finl;
      barrier();
      exit();
    }
  assert(status_ == INITIAL);
  mon_probleme_ = pb;
  status_ = PB_ASSOCIE;
}
References Process::barrier(), Cerr, Process::exit(), finl, INITIAL, le_nom(), Probleme_base::le_nom(), mon_probleme(), mon_probleme_, PB_ASSOCIE, Objet_U::que_suis_je(), and status_.
Referenced by Probleme_base::associer_().
completer()
void Loi_Fermeture_base::completer () virtual
Cette methode est appelee apres avoir lu toutes les equations
et les lois de fermeture (tous les champs et les conditions aux limites
du probleme sont disponibles)
Definition at line 96 of file Loi_Fermeture_base.cpp.
{
  assert(status_ == READON_FAIT);
  status_ = COMPLET;
}
References COMPLET, READON_FAIT, and status_.
Referenced by Probleme_base::completer().
creer_champ()
void Loi_Fermeture_base::creer_champ (const Motcle & motlu) override virtual
La classe de base ne comprend aucun champ supplementaire.
Implements Champs_compris_interface.
Definition at line 142 of file Loi_Fermeture_base.cpp.
{
}
Referenced by Probleme_base::creer_champ().
discretiser()
void Loi_Fermeture_base::discretiser (const Discretisation_base &) virtual
Cette methode est appelee par le probleme apres
la discretisation des equations et du milieu et avant
l'appel a readOn() pour lecture des parametres.
Dans les classes derivees elle doit discretiser au minimum les champs
qui seront requis dans le readOn() des equations ou des autres
lois de fermeture.
Reimplemented in Loi_Fermeture_Test.
Definition at line 55 of file Loi_Fermeture_base.cpp.
{
  assert(status_ == PB_ASSOCIE);
  status_ = DISCRETISE;
}
References DISCRETISE, PB_ASSOCIE, and status_.
Referenced by Probleme_base::discretiser(), and Loi_Fermeture_Test::discretiser().
get_champ()
const Champ_base & Loi_Fermeture_base::get_champ (const Motcle & nom) const override virtual
Cette methode renvoie le champ de nom "nom" s'il est
compris par la classe, sinon appelle la methode get_champ de l'ancetre.
Dans la classe de base, on leve l'exception Champ_compris_erreur.
Implements Champs_compris_interface.
Definition at line 132 of file Loi_Fermeture_base.cpp.
{
  return champs_compris_.get_champ(nom);
}
References champs_compris_, and Champs_compris::get_champ().
Referenced by Probleme_base::get_champ(), and Probleme_base::has_champ().
get_info()
const Type_info * Loi_Fermeture_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Loi_Fermeture_Test.
Definition at line 23 of file Loi_Fermeture_base.cpp.
get_noms_champs_postraitables()
void Loi_Fermeture_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Definition at line 146 of file Loi_Fermeture_base.cpp.
{
  if (opt==DESCRIPTION)
    Cerr << que_suis_je()<<": " << champs_compris_.liste_noms_compris() << finl;
  else
    noms.add(champs_compris_.liste_noms_compris());
}
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, Champs_compris::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Probleme_base::get_noms_champs_postraitables().
has_champ()
bool Loi_Fermeture_base::has_champ (const Motcle & nom, Ref_Champ_base & ref_champ) const virtual
Definition at line 136 of file Loi_Fermeture_base.cpp.
{
  return champs_compris_.has_champ(nom, ref_champ);
}
References champs_compris_, and Champs_compris::has_champ().
info()
const Type_info * Loi_Fermeture_base::info () static
Definition at line 23 of file Loi_Fermeture_base.cpp.
le_nom()
const Nom & Loi_Fermeture_base::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 43 of file Loi_Fermeture_base.h.
  {
    return nom_;
  }
References nom_.
Referenced by associer_pb_base().
mettre_a_jour()
void Loi_Fermeture_base::mettre_a_jour (double temps) virtual
Cette methode est appelee par le probleme apres
mettre_a_jour() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
Reimplemented in Loi_Fermeture_Test.
Definition at line 124 of file Loi_Fermeture_base.cpp.
{
  assert(status_ == COMPLET);
}
References COMPLET, and status_.
Referenced by Probleme_base::mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), and preparer_calcul().
mon_probleme()
const Probleme_base & Loi_Fermeture_base::mon_probleme () const protected
Renvoie le probleme (j'ai cree cette methode pour ne pas
donner acces au probleme en ecriture par la REF)
Definition at line 104 of file Loi_Fermeture_base.cpp.
{
  return mon_probleme_.valeur();
}
References mon_probleme_, and Ref_Probleme_base::valeur().
Referenced by associer_pb_base(), Loi_Fermeture_Test::discretiser(), and preparer_calcul().
nommer()
void Loi_Fermeture_base::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 39 of file Loi_Fermeture_base.h.
  {
    nom_ = nom;
  }
References nom_.
preparer_calcul()
void Loi_Fermeture_base::preparer_calcul () virtual
Cette methode est appelee par le probleme apres
preparer_calcul() des equations et du milieu. Elle doit mettre
a jour tous les champs qu'elle gere en fonction des autres
champs du probleme.
Definition at line 113 of file Loi_Fermeture_base.cpp.
{
  assert(status_ == COMPLET);
  const double temps = mon_probleme().schema_temps().temps_courant();
  mettre_a_jour(temps);
}
References COMPLET, mettre_a_jour(), mon_probleme(), Probleme_base::schema_temps(), status_, and Schema_Temps_base::temps_courant().
Referenced by Probleme_base::preparer_calcul().
printOn()
Sortie & Loi_Fermeture_base::printOn (Sortie & x) const override protected virtual
Pour l'instant, exit()
Reimplemented from Objet_U.
Reimplemented in Loi_Fermeture_Test.
Definition at line 77 of file Loi_Fermeture_base.cpp.
{
  Cerr << "Loi_Fermeture_base::printOn non code" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
Referenced by Loi_Fermeture_Test::printOn().
readOn()
Entree & Loi_Fermeture_base::readOn (Entree & is) override protected virtual
Cette methode appelle la methode set_param() pour
initialiser les parametres, puis lit les parametres.
Dans l'implementation des classes derivees on peut se contenter
d'appeler la methode de la classe de base et verifier les parametres.
Reimplemented from Objet_U.
Reimplemented in Loi_Fermeture_Test.
Definition at line 66 of file Loi_Fermeture_base.cpp.
{
  assert(status_ == DISCRETISE);
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  status_ = READON_FAIT;
  return is;
}
References DISCRETISE, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), READON_FAIT, set_param(), and status_.
Referenced by Loi_Fermeture_Test::readOn().
self_cast() [1/2]
const Loi_Fermeture_base & Loi_Fermeture_base::self_cast (const Objet_U & r) static
Definition at line 23 of file Loi_Fermeture_base.cpp.
self_cast() [2/2]
Loi_Fermeture_base & Loi_Fermeture_base::self_cast (Objet_U & r) static
Definition at line 23 of file Loi_Fermeture_base.cpp.
set_param()
void Loi_Fermeture_base::set_param (Param & param) virtual
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour
ajouter dans "param" les differents parametres a lire
dans le jeu de donnees et appeler la methode de l'ancetre.
Dans la classe de base: aucun parametre.
Reimplemented in Loi_Fermeture_Test.
Definition at line 89 of file Loi_Fermeture_base.cpp.
{
}
Referenced by readOn().
Member Data Documentation
champs_compris_
Champs_compris Loi_Fermeture_base::champs_compris_ protected
Definition at line 62 of file Loi_Fermeture_base.h.
Referenced by Loi_Fermeture_Test::discretiser(), get_champ(), get_noms_champs_postraitables(), and has_champ().
info_obj
const Type_info Loi_Fermeture_base::info_obj static
Definition at line 36 of file Loi_Fermeture_base.h.
mon_probleme_
Ref_Probleme_base Loi_Fermeture_base::mon_probleme_ private
Definition at line 71 of file Loi_Fermeture_base.h.
Referenced by associer_pb_base(), and mon_probleme().
nom_
Nom Loi_Fermeture_base::nom_ private
Definition at line 69 of file Loi_Fermeture_base.h.
Referenced by le_nom(), and nommer().
status_
Status Loi_Fermeture_base::status_ protected
Definition at line 65 of file Loi_Fermeture_base.h.
Referenced by associer_pb_base(), completer(), discretiser(), Loi_Fermeture_base(), mettre_a_jour(), Loi_Fermeture_Test::mettre_a_jour(), preparer_calcul(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Loi_Fermeture_base.h
src/Kernel/Framework/Loi_Fermeture_base.cpp