TRUST: Lire_Fichier Class Reference
Lire_Fichier Class Reference
class Lire_Fichier
Lecture d'un fichier
#include <Lire_Fichier.h>
Public Member Functions
Lire_Fichier ()
~Lire_Fichier ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Deux syntaxes possibles dans le jeu de donnees:
Lire_fichier NOM_OBJET NOM_FICHIER
(lit le contenu du fichier dans l'objet avec readOn de l'objet)
Lire_fichier NOM_FICHIER ;
(interprete le fichier dans un interprete local: les objets declares
dans le fichier sont detruits a la fin de la lecture du fichier)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Lire_Fichier & self_cast (Objet_U &)
static const Lire_Fichier & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Pas code: exit()
virtual Entree & readOn (Entree &)
Pas code: exit()
Detailed Description
class Lire_Fichier
Lecture d'un fichier
Definition at line 37 of file Lire_Fichier.h.
Constructor & Destructor Documentation
Lire_Fichier::Lire_Fichier ()
Definition at line 30 of file Lire_Fichier.cpp.
Lire_Fichier::~Lire_Fichier ()
Definition at line 30 of file Lire_Fichier.cpp.
Member Function Documentation
Objet_U * Lire_Fichier::cree_instance () [static]
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
int Lire_Fichier::duplique () const [virtual]
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
const Type_info * Lire_Fichier::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
const Type_info * Lire_Fichier::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
Entree & Lire_Fichier::interpreter (Entree & is) [virtual]
Deux syntaxes possibles dans le jeu de donnees:
Lire_fichier NOM_OBJET NOM_FICHIER
(lit le contenu du fichier dans l'objet avec readOn de l'objet)
Lire_fichier NOM_FICHIER ;
(interprete le fichier dans un interprete local: les objets declares
dans le fichier sont detruits a la fin de la lecture du fichier)
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin.
Definition at line 55 of file Lire_Fichier.cpp.
References Interprete_bloc::BLOC_EOF, Cerr, check_ICEM_ascii_file(), check_ICEM_binary_file(), Process::exit(), finl, Entree_Fichier_base::get_ifstream(), Interprete_bloc::interpreter_bloc(), is_a_binary_file(), Interprete::objet(), and Lec_Diffuse_base::set_check_types().
{
  Nom nom1, nom2;
  is >> nom1 >> nom2;
  if (nom2 != ";")
    {
      if (is_a_binary_file(nom2))
        {
          check_ICEM_binary_file(nom2,nom1);
          Cerr << "Lire_Fichier: reading binary file " << nom2 << " to object " << nom1 << finl;
          Objet_U& ob1=objet(nom1);
          EFichierBin fic(nom2);
          if(!fic.get_ifstream())
            {
              Cerr << "Unable to open the file " << nom2 << finl;
              Cerr << "Enter a different file name please ... ";
              exit();
            }
          fic >> ob1;
        }
      else
        {
          check_ICEM_ascii_file(nom2,*this);
          Cerr << "Lire_Fichier: reading ASCII file " << nom2 << " to object " << nom1 << finl;
          LecFicDiffuse fic(nom2);
// On ne peut pas activer check_types car certains fichiers geom ont un format louche
// ou tout est colle comme ceci : -0.12000000E+01-0.25000000E+00-0.25000000E+00
// (exemple croix.geom)
          fic.set_check_types(0);
          Objet_U& ob1 = objet(nom1);
          fic >> ob1;
        }
    }
  else
    {
      Cerr << "Lire_Fichier: interpreting file " << nom1 << finl;
      LecFicDiffuse_JDD data_file(nom1);
      data_file.set_check_types(1);
// On cree un nouvel interprete. A la fin de la lecture
// les objets seront detruits.
      Interprete_bloc interp;
      interp.interpreter_bloc(data_file,
                              Interprete_bloc::BLOC_EOF /* fin du bloc a la fin du fichier */,
                              0 /* verifie_sans_interpreter=0 */);
      Cerr << "Lire_Fichier: end of file " << nom1 << finl;
    }
  Cerr << "Lire_Fichier: end of file " << nom1 << finl;
  return is;
}
Sortie & Lire_Fichier::printOn (Sortie & x) const [protected, virtual]
Pas code: exit()
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 33 of file Lire_Fichier.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in Lire_Fichier::printOn()" << finl;
  exit();
  return os;
}
Entree & Lire_Fichier::readOn (Entree & is) [protected, virtual]
Pas code: exit()
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 41 of file Lire_Fichier.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Error in Lire_Fichier::readOn()" << finl;
  exit();
  return is;
}
Lire_Fichier & Lire_Fichier::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
const Lire_Fichier & Lire_Fichier::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
unsigned Lire_Fichier::taille_memoire () const [virtual]
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 30 of file Lire_Fichier.cpp.
Member Data Documentation
const Type_info Lire_Fichier::info_obj [static]
Reimplemented from Interprete.
Reimplemented in Lire_Fichier_Bin, and Read_unsupported_ASCII_file_from_ICEM.
Definition at line 39 of file Lire_Fichier.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Lire_Fichier.h
src/Kernel/Utilitaires/Lire_Fichier.cpp