TRUST: Matrice_Morse Class Reference
Matrice_Morse Class Reference
Classe Matrice_Morse
Represente une matrice M (creuse), non necessairement carree
stockee au format Morse.
--------------------------------------------------------------------—
On utilise 3 tableaux tab1(n+1), tab2(nnz) et coeff_(nnz):
On note Vi = { j differents de i / M(i,j) est non nul }
tab1[i] = rang dans tab2 de la ieme ligne
pour tab1[i] <= j < tab1[i+1], tab2[j] decrit Vi
et coeff_[j] = M(i,tab2[j])
tab1 et tab2 sont des rangs au sens fortran:
1 <= tab2[i] <= n
tab1[n+1] = nnz+1
Remarque: dans ce commentaire le [] est a prendre au sens fortran:
tab1[1] designe la premiere valeur de tab1
C'est aussi le format décrit dans la page Wikipedia :
https://fr.wikipedia.org/wiki/Matrice_creuse
en faisant un +1 sur tous les éléments des tableaux d'indices (IA et JA dans la page)
--------------------------------------------------------------------—.
#include <Matrice_Morse.h>
Public Member Functions
~Matrice_Morse ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Morse ()
Matrice_Morse (int n, int nnz)
Constructeur d'une matrice Morse carree d'ordre n
et pouvant stocker au maximum nnz elements non nuls.
Egalement constructeur par defaut car les 2 parametres
ont une valeur par defaut.
Matrice_Morse (int n, int m, int nnz)
Constructeur d'une matrice Morse avec n lignes et m colonnes
pouvant stocker au maximum nnz elements non nuls.
Matrice_Morse (const Matrice_Morse &)
Constructeur par copie d'une Matrice_Morse.
Copie de chaque membre donne du paramtre.
Matrice_Morse (int, int, const IntLists &, const DoubleLists &, const DoubleVect &)
Sortie & imprimer (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s) const override
Sortie & imprimer_formatte (Sortie &s, int symetrie) const
Sortie & imprimer_image (Sortie &s) const
Sortie & imprimer_image (Sortie &s, int symetrie) const
int largeur_de_bande () const
Retourne la largeur de bande.
void remplir (const IntLists &, const DoubleLists &, const DoubleVect &)
void remplir (const IntLists &, const DoubleLists &)
void remplir (const int, const int, const int, const int, const Matrice_Morse &)
Remplissage d'une matrice morse par une matrice morse plus petite.
void dimensionner (int n, int nnz)
Size the matrix with n lines and n columns and nnz zero-values coefficients.
void dimensionner (int n, int m, int nnz)
Size the matrix with n lines, m columns with nnz zero-values coefficients.
void dimensionner (const IntTab &)
int ordre () const override
Renvoie l'ordre de la matrice:
- le nombre de lignes si la matrice est carree
- 0 sinon.
int nb_lignes () const override
nb_lignes retourne n
int nb_colonnes () const override
nb_colonnes retourne m
int nb_coeff () const
nb_coeff retourne nnz
void set_nb_columns (const int)
void set_symmetric (const int)
int get_symmetric () const
IntVect & get_set_tab1 (void)
IntVect & get_set_tab2 (void)
DoubleVect & get_set_coeff (void)
const IntVect & get_tab1 (void) const
const IntVect & get_tab2 (void) const
const DoubleVect & get_coeff (void) const
int nb_vois (int i) const
void clean ()
Remplit la matrice avec des zeros.
double & operator() (int i, int j)
double operator() (int i, int j) const
double coef (int i, int j) const
double & coef (int i, int j)
Matrice_Morse & operator= (const Matrice_Morse &)
Operateur d'affectation d'une Matrice_Morse dans une
autre Matrice_Morse.
Matrice_Morse & operator+= (const Matrice_Morse &)
NE FAIT RIEN.
Matrice_Morse & operator*= (double)
Operateur de multiplication (de tous les elements)
d'une matrice par un scalaire.
Operation: A = x * A.
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Matrice_Morse & operator/= (double)
Operateur de division (de tous les elements)
d'une matrice par un scalaire.
Operation: A = A / x.
Matrice_Morse & operator*= (const DoubleVect &)
Operateur de multiplication d'une matrice par un vecteur:
scaling des lignes de la matrice par les coefficients
correspondants du vecteur passe en parametre.
A *= x, effectue les scaling suivants:
A(i,:) = A(i,:) * x(i), pour toutes les lignes i de A.
Matrice_Morse operator- () const
Operateur de negation unaire, renvoie l'opposee de la matrice: - A
Appelle operator*(double,const Matrice_Morse&)
virtual int inverse (const DoubleVect &, DoubleVect &, double) const
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
virtual int inverse (const DoubleVect &, DoubleVect &, double, int) const
Matrice_Morse & affecte_prod (const Matrice_Morse &A, const Matrice_Morse &B)
Affecte le produit de 2 matrices Morse A et B a l'objet (this).
Operation: this = A * B.
void compacte (int elim_coeff_nul=0)
Method to check/clean the Matrice_Morse matrix:
-Suppress coefficient defined several times
-elim_coeff_nul=0, on ne supprime pas les coefficients nuls de la matrice
-elim_coeff_nul=1, on supprime les coefficients nuls de la matrice
-elim_coeff_nul=2, on supprime les coefficients nuls et quasi-nuls de la matrice.
DoubleVect & ajouter_multvect_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
ArrOfDouble & ajouter_multvect_ (const ArrOfDouble &, ArrOfDouble &, ArrOfInt &) const
DoubleTab & ajouter_multTab_ (const DoubleTab &, DoubleTab &) const override
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice X representee par un tableau)
Operation: RESU = RESU + A*X.
DoubleVect & ajouter_multvectT_ (const DoubleVect &, DoubleVect &) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
ArrOfDouble & ajouter_multvectT_ (const ArrOfDouble &, ArrOfDouble &, ArrOfInt &) const
virtual Matrice_Morse & transpose (const Matrice_Morse &a)
*this = a transposee.
virtual Matrice_Morse & diagmulmat (const DoubleVect &x)
virtual Matrice_Morse & partie_sup (const Matrice_Morse &a)
void unite ()
void construire_sous_bloc (int nl0, int nc0, int nl1, int nc1, Matrice_Morse &result) const
void formeC ()
void formeF ()
bool has_same_morse_matrix_structure (const Matrice_Morse &) const
bool check_morse_matrix_structure (void) const
bool check_sorted_morse_matrix_structure (void) const
void assert_check_morse_matrix_structure (void) const
void assert_check_sorted_morse_matrix_structure (void) const
void sort_stencil ()
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Morse & self_cast (Objet_U &)
static const Matrice_Morse & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
int morse_matrix_structure_has_changed_
Flag if matrix structure changes.
int sorted_
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Entree & readOn (Entree &) override
NON CODE.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect tab1_
IntVect tab2_
DoubleVect coeff_
int m_
Number of columns.
int symetrique_
Pour inliner operator()(i,j) afin d'optimiser.
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Private Attributes
double zero_
Friends
Matrice_Morse operator+ (const Matrice_Morse &, const Matrice_Morse &)
Fonction (hors classe) amie de la classe Matrice_Morse
Addition de 2 matrices au format Morse.
Operation: renvoie (A+B)
Matrice_Morse operator* (double, const Matrice_Morse &)
Fonction (hors classe) amie de la classe Matrice_Morse
Scaling de la matrice par un scalaire: multiplie tous
les elements de la matrice par un scalaire.
Operation: renvoie x*A.
Detailed Description
Classe Matrice_Morse
Represente une matrice M (creuse), non necessairement carree
stockee au format Morse.
--------------------------------------------------------------------—
On utilise 3 tableaux tab1(n+1), tab2(nnz) et coeff_(nnz):
On note Vi = { j differents de i / M(i,j) est non nul }
tab1[i] = rang dans tab2 de la ieme ligne
pour tab1[i] <= j < tab1[i+1], tab2[j] decrit Vi
et coeff_[j] = M(i,tab2[j])
tab1 et tab2 sont des rangs au sens fortran:
1 <= tab2[i] <= n
tab1[n+1] = nnz+1
Remarque: dans ce commentaire le [] est a prendre au sens fortran:
tab1[1] designe la premiere valeur de tab1
C'est aussi le format décrit dans la page Wikipedia :
https://fr.wikipedia.org/wiki/Matrice_creuse
en faisant un +1 sur tous les éléments des tableaux d'indices (IA et JA dans la page)
--------------------------------------------------------------------—.
Definition at line 50 of file Matrice_Morse.h.
Constructor & Destructor Documentation
~Matrice_Morse()
Matrice_Morse::~Matrice_Morse ()
Definition at line 28 of file Matrice_Morse.cpp.
Matrice_Morse() [1/5]
Matrice_Morse::Matrice_Morse ()
Definition at line 271 of file Matrice_Morse.cpp.
{
  dimensionner(0,0);
  morse_matrix_structure_has_changed_=1;
  symetrique_ = 0;
  sorted_ = 0;
  zero_ = 0;
  is_stencil_up_to_date_ = false ;
}
References dimensionner(), Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, sorted_, symetrique_, and zero_.
Matrice_Morse() [2/5]
Matrice_Morse::Matrice_Morse (int n, int nnz)
Constructeur d'une matrice Morse carree d'ordre n
et pouvant stocker au maximum nnz elements non nuls.
Egalement constructeur par defaut car les 2 parametres
ont une valeur par defaut.
Definition at line 264 of file Matrice_Morse.cpp.
                                           :
  morse_matrix_structure_has_changed_(1), symetrique_(0), zero_(0)
{
  dimensionner(n,nnz), sorted_ = 0;
  is_stencil_up_to_date_ = false ;
}
References dimensionner(), Matrice_Base::is_stencil_up_to_date_, and sorted_.
Matrice_Morse() [3/5]
Matrice_Morse::Matrice_Morse (int n, int m, int nnz)
Constructeur d'une matrice Morse avec n lignes et m colonnes
pouvant stocker au maximum nnz elements non nuls.
Definition at line 308 of file Matrice_Morse.cpp.
                                                 :
  morse_matrix_structure_has_changed_(1), symetrique_(0), zero_(0)
{
  dimensionner(n,m,nnz);
  is_stencil_up_to_date_ = false, sorted_ = 0 ;
}
References dimensionner(), Matrice_Base::is_stencil_up_to_date_, and sorted_.
Matrice_Morse() [4/5]
Matrice_Morse::Matrice_Morse (const Matrice_Morse & acopier)
Constructeur par copie d'une Matrice_Morse.
Copie de chaque membre donne du paramtre.
Definition at line 230 of file Matrice_Morse.cpp.
                                                         :Matrice_Base(),
  tab1_(acopier.tab1_),
  tab2_(acopier.tab2_),
  coeff_(acopier.coeff_),
  m_(acopier.m_),
  symetrique_(0),
  zero_(0)
{
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  is_stencil_up_to_date_ = acopier.is_stencil_up_to_date_ ;
}
References Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, and sorted_.
Matrice_Morse() [5/5]
Matrice_Morse::Matrice_Morse (int n, int nnz, const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag)
Definition at line 316 of file Matrice_Morse.cpp.
  :  morse_matrix_structure_has_changed_(1), symetrique_(0) , zero_(0)
{
  dimensionner(n,n,nnz);
  remplir(voisins, valeurs, terme_diag);
  is_stencil_up_to_date_ = false, sorted_ = 0;
}
References dimensionner(), Matrice_Base::is_stencil_up_to_date_, remplir(), and sorted_.
Member Function Documentation
affecte_prod()
Matrice_Morse & Matrice_Morse::affecte_prod (const Matrice_Morse & a, const Matrice_Morse & b)
Affecte le produit de 2 matrices Morse A et B a l'objet (this).
Operation: this = A * B.
Returns
Matrice_Morse&
Signification: le resultat de l'operation (*this)
Contraintes:
< nb de lignes de A
< nb de colonnes de B assert(nrow==ncol); Jloi non?
< on recupere tout (tab1, tab2, coeff de matrice_resu)
< nb de valeurs maximales de la matrice resultante
< tableau de travail
Definition at line 1612 of file Matrice_Morse.cpp.
{
  int nrow= a.nb_lignes();                //!< nb de lignes de A
  int ncol= b.nb_colonnes();                //!< nb de colonnes de B assert(nrow==ncol); Jloi non?
//
//
  assert(nrow==ncol);
  tab1_.resize(nrow+1);
  int job = 1 ;                      //!< on recupere tout (tab1, tab2, coeff de matrice_resu)
  int  nzmax = nb_coeff();                //!< nb de valeurs maximales de la matrice resultante
  if(nzmax==0)
    {
      nzmax=a.nb_coeff();
      tab2_.resize(nzmax);
      coeff_.resize(nzmax);
      assert(nzmax==nb_coeff());
    }
  IntVect iw(ncol+1);                        //!< tableau de travail
// Cerr << " iao1 " << a.tab1_ << finl ;
// Cerr << " jao1 " << a.tab2_ << finl ;
// Cerr << " aao1 " << a.coeff_ << finl ;
//
// Cerr << " iao2 " << b.tab1_ << finl ;
// Cerr << " jao2 " << b.tab2_ << finl ;
// Cerr << " aao2 " << b.coeff_ << finl ;
// while(ierr=0)
// {
// F77NAME(AMUB)(&nb_lig, &nb_col, &job, A.coeff_, A.tab2_, A.tab1_,
// B.coeff_, B.tab2_, B.tab1_,
// coeff_.addr(), tab2_.addr(), tab1_.addr(), &nzmax, iw, &ierr);
//
//
// c----------------------------------------------------------------------c
// subroutine amub (nrow,ncol,job,a,ja,ia,b,jb,ib,
// *                 c,jc,ic,nzmax,iw,ierr)
// real*8 a(*), b(*), c(*)
// integer ja(*),jb(*),jc(*),ia(nrow+1),ib(ncol+1),
// *     ic(ncol+1),iw(ncol)
// c-----------------------------------------------------------------------
// c performs the matrix by matrix product C = A B
// c-----------------------------------------------------------------------
// c on entry:
// c ---------
// c nrow        = integer. The row dimension of A
// c ncol  = integer. The column dimension of B
// c job   = integer. Job indicator. When job = 0, only the structure
// c                  (i.e. the arrays jc, ic) is computed and the
// c                  real values are ignored.
// c
// c a,
// c ja,
// c ia   = Matrix A in compressed sparse row format.
// c
// c b,
// c jb,
// c ib        =  Matrix B in compressed sparse row format.
// c
// c nzmax        = integer. The  length of the arrays c and jc.
// c         amub will stop if the result matrix C  has a number
// c         of elements that exceeds exceeds nzmax. See ierr.
// c
// c on return:
// c----------
// c c,
// c jc,
// c ic        = resulting matrix C in compressed sparse row sparse format.
// c
// c ierr        = integer. serving as error message.
// c         ierr = 0 means normal return,
// c         ierr .gt. 0 means that amub stopped while computing the
// c         i-th row  of C with i=ierr, because the number
// c         of elements in C exceeds nzmax.
// c
// c work arrays:
// c------------
// c iw        = integer work array of length equal to the number of
// c         columns in A.
// c Notes:
// c-------
// c         The column dimension of B is not needed.
// c
// c-----------------------------------------------------------------
// real*8 scal
// logical values
// values = (job .ne. 0)
// len = 0
// ic(1) = 1
// ierr = 0
// c     initialize array iw.
// do 1 j=1, ncol
// iw(j) = 0
// 1    continue
// c
  double scal=0. ;
  int ii, jj ,k , ka, kb ;
  int values = 0;
  if (job != 0) values = 1 ;
  int len = -1 ;
  tab1_[0] = 1  ;
  iw = -1 ;
// do 500 ii=1, nrow
// c     row i
// do 200 ka=ia(ii), ia(ii+1)-1
// if (values) scal = a(ka)
// jj   = ja(ka)
// do 100 kb=ib(jj),ib(jj+1)-1
// jcol = jb(kb)
// jpos = iw(jcol)
// if (jpos .eq. 0) then
// len = len+1
// if (len .gt. nzmax) then
// ierr = ii
// return
// endif
// jc(len) = jcol
// iw(jcol)= len
// if (values) c(len)  = scal*b(kb)
// else
// if (values) c(jpos) = c(jpos) + scal*b(kb)
// endif
// 100            continue
// 200     continue
// do 201 k=ic(ii), len
// iw(jc(k)) = 0
// 201     continue
// ic(ii+1) = len+1
// 500  continue
// Cerr << "Matrice_Morse::affect_prod nrow " << nrow << finl;
  for(ii=0; ii< nrow; ii++)
    {
      for(ka=a.tab1_[ii]-1; ka < a.tab1_[ii+1]-1; ka++)
        {
          if (values == 1) scal = a.coeff_[ka] ;
          jj   = a.tab2_[ka] - 1 ;
          for (kb=b.tab1_[jj]-1; kb < b.tab1_[jj+1]-1; kb++)
            {
              int jcol = b.tab2_[kb] -1 ;
              int jpos = iw[jcol]  ;
              if (jpos == -1)
                {
                  len++ ;
                  if (len > nzmax-1)
                    {
// Cerr << "Matrice_Morse::affect_prod len > nzmax -1 " << nzmax << finl;
                      nzmax += nrow/ii*nzmax;
                      coeff_.resize(nzmax);
                      tab2_.resize(nzmax);
                    }
                  tab2_[len] = jcol + 1 ;
                  iw[jcol]= len ;
                  if (values == 1) coeff_[len]  = scal*b.coeff_[kb] ;
                }
              else
                {
                  if (values == 1) coeff_[jpos] += scal*b.coeff_[kb] ;
                }
            }
        }
      for (k=tab1_[ii]-1; k < len+1 ; k++) iw[tab2_[k]-1] = -1 ;
      tab1_[ii+1] = (len+1) + 1 ;
    }
// return
// c-------------end-of-amub-----------------------------------------------
// c-----------------------------------------------------------------------
//
// if(ierr)
// {
// nzmax+=nrow/ierr*nzmax;
// coeff_.resize(nzmax);
// tab2_.resize(nzmax);
// }
//
// }
  coeff_.resize(tab1_[nrow]-1);
  tab2_.resize(tab1_[nrow]-1);
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  return *this;
}
References coeff_, morse_matrix_structure_has_changed_, nb_coeff(), nb_colonnes(), nb_lignes(), TRUSTVect< _TYPE_ >::resize(), sorted_, tab1_, and tab2_.
ajouter_multTab_()
DoubleTab & Matrice_Morse::ajouter_multTab_ (const DoubleTab & x, DoubleTab & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice X representee par un tableau)
Operation: RESU = RESU + A*X.
Returns
DoubleTab&
Signification: la matrice resultat de l'operation
Contraintes:
Implements Matrice_Base.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 1001 of file Matrice_Morse.cpp.
{
  if ( (x.nb_dim() == 1) && (resu.nb_dim() == 1))
    {
      ajouter_multvect(x,resu);
      return resu;
    }
  assert_check_morse_matrix_structure( );
  int i, k;
  int nb_comp = x.dimension(1);
  assert(resu.dimension(1) == nb_comp);
  double* t= new double[nb_comp];
  int ncomp;
  int n=nb_lignes();
  for(i=0; i<n; i++)
    {
      for (ncomp=0; ncomp<nb_comp; ncomp++)
        t[ncomp] = 0.0;
      for (k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
        for (ncomp=0; ncomp<nb_comp; ncomp++)
          t[ncomp] += coeff_(k)*x(tab2_(k)-1,ncomp);
      for (ncomp=0; ncomp<nb_comp; ncomp++)
        resu(i,ncomp) += t[ncomp] ;
    }
  delete [] t;
  return resu;
}
References Matrice_Base::ajouter_multvect(), assert_check_morse_matrix_structure(), coeff_, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::nb_dim(), nb_lignes(), tab1_, and tab2_.
Referenced by Op_Diff_VEFP1NCP1B_Face::test().
ajouter_multvect_() [1/2]
ArrOfDouble & Matrice_Morse::ajouter_multvect_ (const ArrOfDouble & x, ArrOfDouble & resu, ArrOfInt & est_reel_pas_com) const
Definition at line 960 of file Matrice_Morse.cpp.
{
  assert_check_morse_matrix_structure( );
  int n = nb_lignes();
  assert(nb_colonnes()==x.size_array());
  assert(n==resu.size_array());
  for(int i=0; i<n; i++)
    {
      double t = 0.0;
      for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
        {
          int j=tab2_(k)-1;
          if (est_reel_pas_com[j]) t += coeff_(k)*x[j];
        }
      resu[i] += t ;
    }
  return resu;
}
References assert_check_morse_matrix_structure(), coeff_, nb_colonnes(), nb_lignes(), TRUSTArray< _TYPE_ >::size_array(), tab1_, and tab2_.
ajouter_multvect_() [2/2]
DoubleVect & Matrice_Morse::ajouter_multvect_ (const DoubleVect & x, DoubleVect & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + A*x.
< Pour indexer x avec un indice fortran
< indice fortran dans tab2 et coeff
< tab1_[i+1] = indice fortran dans tab2_
< indice fortran
Implements Matrice_Base.
Reimplemented in Matrice_Morse_Sym, and Matrice_Morse_Diag.
Definition at line 928 of file Matrice_Morse.cpp.
{
  assert_check_morse_matrix_structure( );
  const int n = tab1_.size_array() - 1;
  assert(x.size_array() == nb_colonnes());
// Test dans cet ordre car l'attribut size() peut etre invalide:
  assert(resu.size_array() == n || resu.size() == n);
  const int *tab1_ptr = tab1_.addr() + 1;
  const int *tab2_ptr = tab2_.addr();
  const double *coeff_ptr = coeff_.addr();
  const double * x_fortran = x.addr() - 1; //!< Pour indexer x avec un indice fortran
  int k_fortran = 1; //!< indice fortran dans tab2 et coeff
  for (int i = 0; i < n; i++, tab1_ptr++)
    {
      const int kmax = *tab1_ptr; //!< tab1_[i+1] = indice fortran dans tab2_
      assert(kmax >= k_fortran && kmax <= (tab2_.size_array()+1));
      double t = resu[i];
      assert(k_fortran == tab1_[i] && tab2_ptr == tab2_.addr()+(k_fortran-1));
      for (; k_fortran < kmax; k_fortran++, tab2_ptr++, coeff_ptr++)
        {
          int colonne = *tab2_ptr; //!< indice fortran
          assert(colonne >= 1 && colonne <= nb_colonnes());
          t += (*coeff_ptr) * x_fortran[colonne];
        }
      resu[i] = t;
    }
  return resu;
}
References TRUSTArray< _TYPE_ >::addr(), assert_check_morse_matrix_structure(), coeff_, nb_colonnes(), TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), tab1_, and tab2_.
Referenced by Matrice_Morse_Diag::ajouter_multvect_(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), and Source_PDF_EF::verif_ajouter_contrib().
ajouter_multvectT_() [1/2]
ArrOfDouble & Matrice_Morse::ajouter_multvectT_ (const ArrOfDouble & x, ArrOfDouble & resu, ArrOfInt & est_reel_pas_com) const
Definition at line 1069 of file Matrice_Morse.cpp.
{
  assert_check_morse_matrix_structure( );
  int n=nb_lignes();
  assert(n==x.size_array());
  assert(nb_colonnes()==resu.size_array());
  for(int i=0; i<n; i++)
    {
      if (est_reel_pas_com[i])
        {
          double xi = x[i];
          for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
            resu[tab2_(k)-1] += coeff_(k) * xi;
        }
    }
  return resu;
}
References assert_check_morse_matrix_structure(), coeff_, nb_colonnes(), nb_lignes(), TRUSTArray< _TYPE_ >::size_array(), tab1_, and tab2_.
ajouter_multvectT_() [2/2]
DoubleVect & Matrice_Morse::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & resu) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
Implements Matrice_Base.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 1054 of file Matrice_Morse.cpp.
{
  assert_check_morse_matrix_structure( );
  int n=nb_lignes();
  for(int i=0; i<n; i++)
    {
      double xi = x(i);
      for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
        resu(tab2_(k)-1) += coeff_(k) * xi;
    }
  return resu;
}
References assert_check_morse_matrix_structure(), coeff_, nb_lignes(), tab1_, and tab2_.
assert_check_morse_matrix_structure()
void Matrice_Morse::assert_check_morse_matrix_structure (void) const
Definition at line 2418 of file Matrice_Morse.cpp.
{
  if (!morse_matrix_structure_has_changed_) return;
#ifndef NDEBUG
  if ( ! ( check_morse_matrix_structure( ) ) )
    {
      Cerr << "Error in 'Matrice_Morse::assert_check_morse_matrix_structure( )':" << finl;
      Cerr << "  Exiting..." << finl;
      Process::exit( );
    }
  else
    morse_matrix_structure_has_changed_=0;
#endif
}
References Cerr, check_morse_matrix_structure(), Process::exit(), finl, and morse_matrix_structure_has_changed_.
Referenced by ajouter_multTab_(), ajouter_multvect_(), ajouter_multvectT_(), compacte(), get_stencil(), and get_stencil_and_coefficients().
assert_check_sorted_morse_matrix_structure()
void Matrice_Morse::assert_check_sorted_morse_matrix_structure (void) const
Definition at line 2433 of file Matrice_Morse.cpp.
{
  if (!morse_matrix_structure_has_changed_) return;
#ifndef NDEBUG
  if ( ! ( check_sorted_morse_matrix_structure( ) ) )
    {
      Cerr << "Error in 'Matrice_Morse::assert_check_sorted_morse_matrix_structure( )':" << finl;
      Cerr << "  Exiting..." << finl;
      Process::exit( );
    }
  else
    morse_matrix_structure_has_changed_=0;
#endif
}
References Cerr, check_sorted_morse_matrix_structure(), Process::exit(), finl, and morse_matrix_structure_has_changed_.
check_morse_matrix_structure()
bool Matrice_Morse::check_morse_matrix_structure (void) const
Definition at line 2296 of file Matrice_Morse.cpp.
{
  const int nb_lines   = nb_lignes( );
  const int nb_columns = nb_colonnes( );
  const int nb_coefficients = tab1_( nb_lines ) - 1;
  if ( tab2_.size( ) != nb_coefficients )
    {
      Cerr << "invalid tab2 size" << finl;
      return false;
    }
  if ( coeff_.size( ) != nb_coefficients )
    {
      Cerr << "invalid coeff size" << finl;
      return false;
    }
  ArrOfBit flags( nb_columns );
  for ( int i=0; i<nb_lines; ++i )
    {
      flags = 0;
      int k0 = tab1_( i ) - 1;
      int k1 = tab1_( i + 1 ) - 1;
      for ( int k=k0; k<k1; ++k )
        {
          int j = tab2_( k ) - 1;
          if ( j < 0 )
            {
              Cerr << "invalid column index (<0): " << j << finl;
              return false;
            }
          if ( j >= nb_columns )
            {
              Cerr << "invalid column index (>nb_cols): " << j << " > " << nb_columns << finl;
              return false;
            }
          if ( flags[ j ] )
            {
              Cerr << "invalid coefficient ( " << i << ", " << j << " ): already defined ( " << k << " )" << finl;
              return false;
            }
          flags.setbit( j );
        }
    }
  return true;
}
References Cerr, coeff_, finl, nb_colonnes(), nb_lignes(), ArrOfBit::setbit(), TRUSTVect< _TYPE_ >::size(), tab1_, and tab2_.
Referenced by assert_check_morse_matrix_structure(), and Matrice_Morse_Sym::check_symmetric_morse_matrix_structure().
check_sorted_morse_matrix_structure()
bool Matrice_Morse::check_sorted_morse_matrix_structure (void) const
Definition at line 2352 of file Matrice_Morse.cpp.
{
  const int nb_lines   = nb_lignes( );
  const int nb_columns = nb_colonnes( );
  const int nb_coefficients = tab1_( nb_lines ) - 1;
  if ( tab2_.size( ) != nb_coefficients )
    {
      Cerr << "invalid tab2 size" << finl;
      return false;
    }
  if ( coeff_.size( ) != nb_coefficients )
    {
      Cerr << "invalid coeff size" << finl;
      return false;
    }
  ArrOfBit flags( nb_columns );
  for ( int i=0; i<nb_lines; ++i )
    {
      flags = 0;
      int k0 = tab1_( i ) - 1;
      int k1 = tab1_( i + 1 ) - 1;
      int j0 = tab2_( k0 ) - 1 - 1;
      for ( int k=k0; k<k1; ++k )
        {
          int j = tab2_( k ) - 1;
          if ( j < 0 )
            {
              Cerr << "invalid column index (<0): " << j << finl;
              return false;
            }
          if ( j >= nb_columns )
            {
              Cerr << "invalid column index (>nb_cols): " << j << " > " << nb_columns << finl;
              return false;
            }
          if ( flags[ j ] )
            {
              Cerr << "invalid coefficient ( " << i << ", " << j << " ): already defined ( " << k << " )" << finl;
              return false;
            }
          if ( j <= j0 )
            {
              Cerr << "unsorted coefficient: ( " << i << ", " << j << " ) after ( " << i << ", " << j0 << " ) " << finl;;
              return false;
            }
          j0 = j;
          flags.setbit( j );
        }
    }
  return true;
}
References Cerr, coeff_, finl, nb_colonnes(), nb_lignes(), ArrOfBit::setbit(), TRUSTVect< _TYPE_ >::size(), tab1_, and tab2_.
Referenced by Matrix_tools::add_scaled_matrices(), assert_check_sorted_morse_matrix_structure(), and Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure().
clean()
void Matrice_Morse::clean ()
Remplit la matrice avec des zeros.
Definition at line 2261 of file Matrice_Morse.cpp.
{
  for (int i=0; i<nb_coeff(); i++)
    coeff_[i]=0.;
}
References coeff_, and nb_coeff().
Referenced by Equation_base::Gradient_conjugue_diff_impl().
coef() [1/2]
double & Matrice_Morse::coef (int i, int j) inline
Definition at line 130 of file Matrice_Morse.h.
{ return operator()(i,j); }
References operator()().
coef() [2/2]
double Matrice_Morse::coef (int i, int j) const inline
Definition at line 129 of file Matrice_Morse.h.
{ return operator()(i,j); }
References operator()().
Referenced by Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Assembleur_P_EF::assembler_mat(), construire_sous_bloc(), Source_PDF_EF::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Matrix_tools::matdiag_mult_matmorse(), Matrix_tools::matmorse_mult_matdiag(), Op_EF_base::modifier_pour_Cl(), and Matrix_tools::uniform_matdiag_mult_matmorse().
compacte()
void Matrice_Morse::compacte (int elim_coeff_nul = 0)
Method to check/clean the Matrice_Morse matrix:
-Suppress coefficient defined several times
-elim_coeff_nul=0, on ne supprime pas les coefficients nuls de la matrice
-elim_coeff_nul=1, on supprime les coefficients nuls de la matrice
-elim_coeff_nul=2, on supprime les coefficients nuls et quasi-nuls de la matrice.
< Le plus grand coefficient doit etre strictement positif
< On ne supprime pas un coefficient quasi-nul d'une ligne ou la diagonale peut etre mise a 1e12
< Les coefficients nuls ont deja ete trouves
< Highest column of a coefficient in the line i
< Nombre de coefficients supprimes
Definition at line 565 of file Matrice_Morse.cpp.
{
  int n=nb_lignes();
  int coeff_nuls=0;
  int coeff_quasi_nuls=0;
  IntTrav elim_coeff(tab2_);
  if (elim_coeff_nul)
    {
      DoubleTrav coeff_max(n);
// Recherche des coefficients nuls hors diagonale a supprimer de la matrice morse
      for(int i=0; i<n; i++)
        for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
          {
            if (std::fabs(coeff_(k))>coeff_max(i)) coeff_max(i)=std::fabs(coeff_(k));
            if (coeff_(k)==0)
              {
                coeff_nuls++;
                elim_coeff(k)=1;
              }
          }
      if (elim_coeff_nul==2)
        {
// Recherche des coefficients quasi nuls hors diagonale (1.e-12 plus petit que le coefficient le plus grand de la ligne) a supprimer de la matrice morse
          for(int i=0; i<n; i++)
            if (!est_egal(coeff_max(i),0)         //!< Le plus grand coefficient doit etre strictement positif
                && coeff_max(i)<1e10)          //!< On ne supprime pas un coefficient quasi-nul d'une ligne ou la diagonale peut etre mise a 1e12
              for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
                if (coeff_(k)!=0                 //!< Les coefficients nuls ont deja ete trouves
                    && est_egal(std::fabs(coeff_(k))/coeff_max(i),0))
                  {
                    coeff_quasi_nuls++;
                    elim_coeff(k)=1;
                  }
        }
    }
// Recherche des coefficients doublons
  int doublons=0;
  for(int i=0; i<n; i++)
    {
      int kmin=tab1_(i)-1;
      int kmax=tab1_(i+1)-1;
      int jmax=-1; //!< Highest column of a coefficient in the line i
      for (int k=kmin; k<kmax; k++)
        {
          int j = tab2_(k)-1;
          if (j>jmax)
            jmax=j;
          else
            {
// Found a column j lower than jmax, check if not defined before:
              for (int kk=k-1; kk>=kmin; kk--)
                {
                  int jj = tab2_(kk)-1;
                  if (jj == j)
                    {
// Already defined!
                      doublons=1;
                      elim_coeff(k)=1;
// Check if same coefficients:
                      if (coeff_(kk)!=coeff_(k))
{
                          Cerr << "Error in a Matrix Morse:" << finl;
                          Cerr << "A("<<i<<","<<j<<")="<<coeff_(k)<<" != "<<"A("<<i<<","<<jj<<")="<<coeff_(kk)<<finl;
                          exit();
                        }
                      break;
                    }
                }
            }
        }
    }
  int nnz=0;
  int kdeb = tab1_(0)-1;
  int coefficient_suppressed=0; //!< Nombre de coefficients supprimes
  if (doublons || coeff_nuls || coeff_quasi_nuls)
    {
// Suppress coefficients
      for (int i=0; i<n; i++)
        {
          int kfin = tab1_(i+1)-1;
          for (int k=kdeb; k<kfin; k++)
            {
              if (!elim_coeff(k))
                {
                  coeff_(nnz) = coeff_(k);
                  tab2_(nnz) = tab2_(k);
                  nnz++;
                }
              else
                coefficient_suppressed++;
            }
// Modification de tab1_ en fonction du nombre de coefficients deja enleves
          tab1_(i+1)-=coefficient_suppressed;
          kdeb = kfin;
        }
    }
  else
    {
      nnz = tab1_[n] - 1;
    }
// On redimensionne les tableaux
  tab2_.resize(nnz);
  coeff_.resize(nnz);
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  assert_check_morse_matrix_structure( );
}
References assert_check_morse_matrix_structure(), Cerr, coeff_, est_egal(), Process::exit(), finl, morse_matrix_structure_has_changed_, nb_lignes(), TRUSTVect< _TYPE_ >::resize(), sorted_, tab1_, and tab2_.
Referenced by Matrice_Morse_Sym::compacte(), Matrice_Bloc::remplir(), and Assembleur_P_VDF::remplir().
construire_sous_bloc()
void Matrice_Morse::construire_sous_bloc (int nl0, int nc0, int nl1, int nc1, Matrice_Morse & result) const
< maximum number of zeros that we will find
< is the coeff in the window?
Definition at line 2451 of file Matrice_Morse.cpp.
{
// count non-zero entries:
  assert(nl0 >= 0);
  assert(nc0 >= 0);
  assert(nl0 <= nl1);
  assert(nc0 <= nc1);
  int max_nnz = tab1_(nl1+1) - tab1_(nl0); //!< maximum number of zeros that we will find
  int tot=0;
  IntTab loca(max_nnz, 2);
  DoubleTab sub_coeffs(max_nnz);
  for (int li=nl0; li <= nl1; li++)
    {
      int idx_coeff = tab1_(li)-1;
      int nb_coeff_on_line = tab1_(li+1)-tab1_(li);
      for (int j=0; j < nb_coeff_on_line; j++)
        {
          int col_idx = tab2_(j+idx_coeff)-1;
          if (col_idx >= nc0 && col_idx <= nc1) //!< is the coeff in the window?
            {
              loca(tot, 0) = li - nl0;
              loca(tot, 1) = col_idx - nc0;
              sub_coeffs(tot) = coeff_(j+idx_coeff);
              tot++;
            }
        }
    }
  loca.resize(tot,2);
  sub_coeffs.resize(tot);
  result.dimensionner(loca);
// Set coefficient values:
  for (int i =0 ; i < tot; i++)
    {
      int il = loca(i, 0);
      int ic = loca(i, 1);
      result.coef(il, ic) = sub_coeffs(i);
    }
}
References coef(), coeff_, dimensionner(), TRUSTTab< _TYPE_ >::resize(), tab1_, and tab2_.
cree_instance()
Objet_U * Matrice_Morse::cree_instance () static
Definition at line 28 of file Matrice_Morse.cpp.
diagmulmat()
Matrice_Morse & Matrice_Morse::diagmulmat (const DoubleVect & x) virtual
Definition at line 856 of file Matrice_Morse.cpp.
{
  int m=nb_lignes();
  int l=0;
  int n=x.size_array();
  if(n!=m)
    {
      Cerr << "Matrice_Morse::diagmulmat bad dimensions" << finl;
      exit();
    }
#ifndef CRAY
  F77NAME(DIAMUA)(&m ,&l,
                  coeff_.addr(),tab2_.addr(),tab1_.addr(),x.addr(),
                  coeff_.addr(),tab2_.addr(),tab1_.addr());
#else
  Cerr << "Matrice_Morse::diagmulmat DIAMUA call invalid for CRAY"<<finl;
  exit();
#endif
  return(*this);
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, coeff_, Process::exit(), F77NAME, finl, nb_lignes(), TRUSTArray< _TYPE_ >::size_array(), tab1_, and tab2_.
dimensionner() [1/3]
void Matrice_Morse::dimensionner (const IntTab & Ind)
< On ne fait rien si la structure est vide
Definition at line 360 of file Matrice_Morse.cpp.
{
  if (Ind.size()==0) return; //!< On ne fait rien si la structure est vide
  int n_ancien = nb_lignes(), m_ancien = nb_colonnes();
  assert(Ind.nb_dim() == 2);
  assert(Ind.dimension(1) == 2);
// Calcul du nouveau nombre de lignes
// = max (ancien, indices de ligne des nouveaux coeffs)
//
// et du nouveau nombre de colonnes
// = max (ancien, indices de colonne des nouveaux coeffs)
  int nInd = Ind.dimension(0);
  int n = 0;
  int m = 0;
  for (int i=0; i<nInd; i++)
    {
      if (n < Ind(i,0)) n = Ind(i,0);
      if (m < Ind(i,1)) m = Ind(i,1);
    }
  n++;
  m++;
  if (n < n_ancien) n = n_ancien;
  if (m < m_ancien) m = m_ancien;
// Copies des anciens tableaux d'indices
  IntVect tab1_temp(tab1_);
// Initialisation au nombre de coefficients deja presents a chaque ligne
  tab1_.resize(n+1);
  m_ = m;
  for (int i=1; i<=n_ancien; i++)
    tab1_[i] = tab1_temp[i] - tab1_temp[i-1];
  for (int i=n_ancien+1; i<=n; i++)
    tab1_[i] = 0;
// Parcourt des indices des nouveaux coeffs pour voir s'ils sont
// deja presents
  int i_nouveaux = 0;
  for (int i=0; i<nInd; i++)
    {
      int i0 = Ind(i,0);
      int i1 = Ind(i,1) + 1;
      int test_present = 0;
      if (i0 < n_ancien)
        {
          int kmin = tab1_temp[i0]-1;
          int kmax = tab1_temp[i0+1]-1;
          for (int k=kmin; k<kmax; k++)
            if (tab2_[k] == i1)
              {
                test_present = 1;
                break;
              }
        }
      if (!test_present)
        {
          i_nouveaux++;
          tab1_[i0+1] += 1;
        }
    }
  if (i_nouveaux == 0)
    {
      tab1_=tab1_temp;
      return;
    }
// Nouveau tableau des positions des premiers coeffs de chaque ligne
  tab1_[0] = 1;
  for (int i=1; i<=n; i++)
    tab1_[i] += tab1_[i-1];
  int nnz_ancien = tab2_.size();
  int nnz = nnz_ancien + i_nouveaux;
  IntVect tab2_temp(tab2_);
  DoubleVect coeff_temp(coeff_);
  tab2_.resize(nnz);
  coeff_.resize(nnz);
// Recopie des anciens coefficients et de leurs indices
// de colonne dans les nouveaux tableaux
  tab2_ = -1;
  for (int i=0; i<n_ancien; i++)
    {
      for (int j1 = tab1_temp[i]-1, j2 = tab1_[i]-1;
           j1 < tab1_temp[i+1]-1;
           j1++, j2++)
        {
          tab2_[j2] = tab2_temp[j1];
          coeff_[j2] = coeff_temp[j1];
        }
    }
  for (int i=0; i<nInd; i++)
    {
      int j0 = Ind(i,0);
      int j1 = Ind(i,1) + 1;
      int k;
      for (k=tab1_[j0]-1; tab2_[k] >= 0; k++)
        if (tab2_[k] == j1)
          {
            break;
          }
      if (tab2_[k] < 0)
        {
          tab2_[k] = j1;
          coeff_[k] = 0.0;
        }
    }
// on remet les coeffs dans l'ordre... pas optimal mais pour voir..
  coeff_=0;
//
  {
    int nbis=nb_lignes();
    for(int i=0; i<nbis; i++)
      {
        for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
          {
            for (int  k2=k; k2<tab1_(i+1)-1; k2++)
              {
                int j1=tab2_(k);
                int j2=tab2_(k2);
                if (j1>j2)
                  {
                    tab2_(k)=j2;
                    tab2_(k2)=j1;
                  }
              }
          }
      }
  }
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
}
References coeff_, TRUSTTab< _TYPE_ >::dimension(), m_, morse_matrix_structure_has_changed_, nb_colonnes(), TRUSTTab< _TYPE_ >::nb_dim(), nb_lignes(), TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), sorted_, tab1_, and tab2_.
dimensionner() [2/3]
void Matrice_Morse::dimensionner (int n, int m, int nnz)
Size the matrix with n lines, m columns with nnz zero-values coefficients.
Definition at line 506 of file Matrice_Morse.cpp.
{
  tab2_.resize(nnz);
  coeff_.resize(nnz);
  m_=m;
// on regarde si tab1 a la bonne taille et si tab1[n1]==nnz.
  if ( tab1_.size_array()!=(n+1) || (tab1_[n]-1)!=nnz )
    {
      tab1_.resize(n+1);
      tab1_=1;
    }
  tab1_.resize(n+1);
  tab1_[n]=nnz+1;
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
}
References coeff_, m_, morse_matrix_structure_has_changed_, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), sorted_, tab1_, and tab2_.
dimensionner() [3/3]
void Matrice_Morse::dimensionner (int n, int nnz)
Size the matrix with n lines and n columns and nnz zero-values coefficients.
Definition at line 338 of file Matrice_Morse.cpp.
{
  dimensionner(n,n,nnz);
  return ;
}
References dimensionner().
Referenced by Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), assembler(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_EF::assembler_mat(), Matrix_tools::build_morse_matrix(), Matrix_tools::build_symmetric_morse_matrix(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Assembleur_P_VDF::construire(), construire_sous_bloc(), Matrice_Dense::convert_to_morse_matrix(), Matrice_Morse_Diag::dimensionne_diag(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_VDF_base::dimensionner_blocs(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Equation_base::dimensionner_termes_croises(), ILU::factorisation(), Matrice_Morse(), remplir(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), and Solv_Petsc::resoudre_systeme().
duplique()
int Matrice_Morse::duplique () const override virtual
Implements Objet_U.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 28 of file Matrice_Morse.cpp.
formeC()
void Matrice_Morse::formeC ()
Definition at line 2198 of file Matrice_Morse.cpp.
{
  int ii, k;
  int n=nb_lignes();
  for( ii=0; ii<=n; ii++)
    tab1_(ii)--;
  for( ii=0; ii<n; ii++)
    tab2_(tab1_(ii))=nb_vois(ii);
  for(k=0; k<nb_coeff(); k++)
    tab2_(k)--;
  morse_matrix_structure_has_changed_=1;
  is_stencil_up_to_date_=false;
}
References Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, nb_coeff(), nb_lignes(), nb_vois(), tab1_, and tab2_.
formeF()
void Matrice_Morse::formeF ()
Definition at line 2212 of file Matrice_Morse.cpp.
{
  int ii, k;
  int n=nb_lignes();
  for( ii=0; ii<=n; ii++)
    tab1_(ii)++;
  for(k=0; k<nb_coeff(); k++)
    tab2_(k)++;
  morse_matrix_structure_has_changed_=1;
  is_stencil_up_to_date_=false;
}
References Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, nb_coeff(), nb_lignes(), tab1_, and tab2_.
Referenced by remplir(), and Matrice_Bloc::remplir().
get_coeff()
const DoubleVect & Matrice_Morse::get_coeff (void) const inline
Definition at line 112 of file Matrice_Morse.h.
{ return coeff_ ; }
References coeff_.
Referenced by Matrice_Morse_Sym::ajouter_multvect_(), SETS::assembler(), Simpler_Base::assembler_matrice_pression_implicite(), disp_m(), ILU::factorisation(), ILU::factoriser(), inverser_par_diagonale(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Matrice_Morse_Sym::multvect_et_prodscal(), operation01(), operation11(), operator+=(), operator=(), Matrice_Morse_Sym::operator=(), Solv_GCP::prepare_data(), Matrice_Morse_Sym::renumerote(), and SSOR::ssor().
get_info()
const Type_info * Matrice_Morse::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 28 of file Matrice_Morse.cpp.
get_set_coeff()
DoubleVect & Matrice_Morse::get_set_coeff (void) inline
Definition at line 108 of file Matrice_Morse.h.
{ return coeff_ ; }
References coeff_.
Referenced by Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes_internes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem(), SETS::assembler(), Assembleur_P_VDF_Q4::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), Matrix_tools::build_morse_matrix(), Matrix_tools::build_symmetric_morse_matrix(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), coeff_opt(), Operateur_Grad_base::contribuer_a_avec(), Matrice_Dense::convert_to_morse_matrix(), T_It_VDF_Face< _TYPE_ >::corriger_coeffs_fa7_elem_periodicite_(), Op_EF_base::dimensionner(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_matrice_sans_mem(), ILU::factorisation(), Op_Diff_VDF_Face_Axi_base::fill_coeff_matrice_morse(), Op_Dift_VDF_Face_Axi_base::fill_coeff_matrice_morse(), T_It_VDF_Face< _TYPE_ >::fill_coeff_matrice_morse(), Testeur::interpreter(), Simple::iterer_eqn(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl_(), Solv_GCP::prepare_data(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), and Operateur_base::tester_contribuer_a_avec().
get_set_tab1()
IntVect & Matrice_Morse::get_set_tab1 (void) inline
Definition at line 98 of file Matrice_Morse.h.
  {
    is_stencil_up_to_date_ = false ;
    return tab1_ ;
  }
References Matrice_Base::is_stencil_up_to_date_, and tab1_.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes_internes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem(), Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), Matrix_tools::build_morse_matrix(), Matrix_tools::build_symmetric_morse_matrix(), Assembleur_P_VDF::construire(), convbisimplicite(), Matrice_Dense::convert_to_morse_matrix(), T_It_VDF_Face< _TYPE_ >::corriger_coeffs_fa7_elem_periodicite_(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_matrice_sans_mem(), Matrix_tools::extend_matrix(), ILU::factorisation(), Op_Diff_VDF_Face_Axi_base::fill_coeff_matrice_morse(), Op_Dift_VDF_Face_Axi_base::fill_coeff_matrice_morse(), T_It_VDF_Face< _TYPE_ >::fill_coeff_matrice_morse(), Testeur::interpreter(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Op_VDF_Face::modifier_pour_Cl_(), Solv_GCP::prepare_data(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), and Operateur_base::tester_contribuer_a_avec().
get_set_tab2()
IntVect & Matrice_Morse::get_set_tab2 (void) inline
Definition at line 103 of file Matrice_Morse.h.
  {
    is_stencil_up_to_date_ = false ;
    return tab2_ ;
  }
References Matrice_Base::is_stencil_up_to_date_, and tab2_.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_bords(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes_internes(), Op_Diff_VDF_Face_Axi_base::ajouter_contribution_elem(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem(), Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), Assembleur_P_VDF_Q4::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), Matrix_tools::build_morse_matrix(), Matrix_tools::build_symmetric_morse_matrix(), Assembleur_P_VDF::construire(), convbisimplicite(), Matrice_Dense::convert_to_morse_matrix(), T_It_VDF_Face< _TYPE_ >::corriger_coeffs_fa7_elem_periodicite_(), Op_VDF_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_matrice_sans_mem(), ILU::factorisation(), Op_Diff_VDF_Face_Axi_base::fill_coeff_matrice_morse(), Op_Dift_VDF_Face_Axi_base::fill_coeff_matrice_morse(), T_It_VDF_Face< _TYPE_ >::fill_coeff_matrice_morse(), Testeur::interpreter(), Simple::iterer_eqs(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Solv_GCP::prepare_data(), Matrice_Bloc::remplir(), Assembleur_P_VEF::remplir(), and Operateur_base::tester_contribuer_a_avec().
get_stencil()
void Matrice_Morse::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Morse_Sym.
Definition at line 1916 of file Matrice_Morse.cpp.
{
  assert_check_morse_matrix_structure( );
  if( is_stencil_up_to_date_ )
    {
      stencil = stencil_;
      return;
    }
  stencil.resize( 0, 2 );
  stencil.resize(tab2_.size_array(), 2);
  stencil.set_smart_resize( 1 );
  ArrOfInt tmp;
  tmp.set_smart_resize( 1 );
  int compteur = 0;
  const int nb_lines = nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0   = tab1_( i ) - 1;
      int k1   = tab1_( i + 1 ) - 1;
      int size = k1 - k0;
      tmp.resize_array( 0 );
      tmp.resize_array( size );
      for ( int k=0; k<size; ++k )
        {
          tmp[ k ] = tab2_( k + k0 ) - 1;
        }
      tmp.ordonne_array( );
      for ( int k=0; k<size; ++k )
        {
          stencil( k+compteur , 0 ) = i;
          stencil( k+compteur , 1 ) =  tmp[ k ];
        }
      compteur += size;
    }
  stencil.set_smart_resize( 0 );
}
References assert_check_morse_matrix_structure(), compteur, Matrice_Base::is_stencil_up_to_date_, nb_lignes(), TRUSTArray< _TYPE_ >::ordonne_array(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Base::stencil_, tab1_, and tab2_.
get_stencil_and_coefficients()
void Matrice_Morse::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Morse_Sym.
Definition at line 1964 of file Matrice_Morse.cpp.
{
  assert_check_morse_matrix_structure( );
  if( is_stencil_up_to_date_ )
    {
      if( coeff_.size( ) == 0 )
        {
          Cerr << "Error in Matrice_Morse::get_stencil_and_coefficients( )"<<finl;
          Cerr << "  The coefficients are not filled."<<finl;
          Cerr << "  Aborting..." << finl;
          Process::abort( );
        }
      stencil = stencil_ ;
      coefficients = coeff_ ;
      return;
    }
  stencil.resize( 0, 2 );
  stencil.resize(tab2_.size_array(), 2);
  stencil.set_smart_resize( 1 );
  coefficients.resize( 0 );
  coefficients.set_smart_resize( 1 );
  coefficients.resize(tab2_.size_array());
  IntTab tmp1(0);
  tmp1.set_smart_resize( 1 );
  ArrOfDouble tmp2;
  tmp2.set_smart_resize( 1 );
  ArrOfInt index;
  index.set_smart_resize( 1 );
  int compteur = 0;
  const int nb_lines = nb_lignes( );
  for ( int i=0; i<nb_lines; ++i )
    {
      int k0   = tab1_( i ) - 1;
      int k1   = tab1_( i + 1 ) - 1;
      int size = k1 - k0;
      tmp1.resize( 0 );
      tmp1.resize( size );
      tmp2.resize_array( 0 );
      tmp2.resize_array( size );
      index.resize_array( 0 );
      for ( int k=0; k<size; ++k )
        {
          tmp1( k ) = tab2_( k + k0 ) - 1;
          tmp2[ k ] = coeff_( k + k0 );
        }
      tri_lexicographique_tableau_indirect( tmp1, index );
      for ( int k=0; k<size; ++k )
        {
          int l = index[ k ];
          stencil( compteur + k , 0 ) = i;
          stencil( compteur + k , 1 ) = tmp1[ l ];
          coefficients[ compteur + k ] = tmp2[ l ];
        }
      compteur += size;
    }
  assert( coefficients.size_array( ) == stencil.dimension( 0 ));
  stencil.set_smart_resize( 0 );
  coefficients.set_smart_resize( 0 );
}
References Process::abort(), assert_check_morse_matrix_structure(), Cerr, coeff_, compteur, TRUSTTab< _TYPE_ >::dimension(), finl, Matrice_Base::is_stencil_up_to_date_, nb_lignes(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), Matrice_Base::stencil_, tab1_, tab2_, and tri_lexicographique_tableau_indirect().
get_symmetric()
int Matrice_Morse::get_symmetric () const inline
Definition at line 96 of file Matrice_Morse.h.
{ return symetrique_; }
References symetrique_.
Referenced by Matrice_Morse_Sym::operator=().
get_tab1()
const IntVect & Matrice_Morse::get_tab1 (void) const inline
Definition at line 110 of file Matrice_Morse.h.
{ return tab1_ ; }
References tab1_.
Referenced by Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Matrice_Morse_Sym::ajouter_multvect_(), Matrix_tools::allocate_morse_matrix(), Matrix_tools::allocate_symmetric_morse_matrix(), SETS::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Simpler_Base::assembler_matrice_pression_implicite(), Matrix_tools::build_morse_matrix(), Matrix_tools::build_symmetric_morse_matrix(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), coeff_opt(), Domain_Graph::construire_graph_from_segment(), Op_EF_base::dimensionner(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), disp_m(), SETS::eliminer(), ILU::factorisation(), ILU::factoriser(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), inverser_par_diagonale(), largeur_de_bande(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Matrix_tools::matdiag_mult_matmorse(), Matrix_tools::matmorse_mult_matdiag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Matrice_Morse_Sym::multvect_et_prodscal(), nb_vois(), operation01(), operation11(), operator=(), Matrice_Morse_Sym::operator=(), Solv_GCP::prepare_data(), Matrice_Morse_Sym::renumerote(), SSOR::ssor(), and Matrix_tools::uniform_matdiag_mult_matmorse().
get_tab2()
const IntVect & Matrice_Morse::get_tab2 (void) const inline
Definition at line 111 of file Matrice_Morse.h.
{ return tab2_ ; }
References tab2_.
Referenced by Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs(), Matrice_Morse_Sym::ajouter_multvect_(), SETS::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), coeff_opt(), Domain_Graph::construire_graph_from_segment(), Op_EF_base::dimensionner(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), disp_m(), SETS::eliminer(), ILU::factorisation(), ILU::factoriser(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), inverser_par_diagonale(), largeur_de_bande(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Matrix_tools::matdiag_mult_matmorse(), Matrix_tools::matmorse_mult_matdiag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_pour_Cl(), Matrice_Morse_Sym::multvect_et_prodscal(), operation01(), operation11(), operator=(), Matrice_Morse_Sym::operator=(), Solv_GCP::prepare_data(), Assembleur_P_VDF::remplir(), Matrice_Morse_Sym::renumerote(), SSOR::ssor(), and Matrix_tools::uniform_matdiag_mult_matmorse().
has_same_morse_matrix_structure()
bool Matrice_Morse::has_same_morse_matrix_structure (const Matrice_Morse & A) const
Definition at line 1135 of file Matrice_Morse.cpp.
{
  int nrow=A.nb_lignes();
  for (int i=0; i<nrow; i++)
    if (tab1_(i)!=A.tab1_(i))
      return false;
  return true;
}
References nb_lignes(), and tab1_.
Referenced by operator+=().
imprimer()
Sortie & Matrice_Morse::imprimer (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Definition at line 78 of file Matrice_Morse.cpp.
{
  int n=nb_lignes();
  for(int i=0; i<n; i++)
    {
      s <<i << ": " <<finl;
      s << "--------------------------------" << finl;
      for (int k=tab1_(i)-1; k<tab1_(i+1)-1; k++)
        {
          s << "("<<(tab2_(k)-1) << "),(" <<coeff_(k)<< ") "
            << " k= " << k << finl;
        }
      s <<finl;
    }
  return s;
}
References coeff_, finl, nb_lignes(), tab1_, and tab2_.
imprimer_formatte() [1/2]
Sortie & Matrice_Morse::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Morse_Sym.
Definition at line 95 of file Matrice_Morse.cpp.
{
  return imprimer_formatte(s,0);
}
References imprimer_formatte().
Referenced by Op_EF_base::dimensionner(), imprimer_formatte(), Matrice_Morse_Sym::imprimer_formatte(), and Op_Conv_EF_VEF_P1NC_Stab::test_implicite().
imprimer_formatte() [2/2]
Sortie & Matrice_Morse::imprimer_formatte (Sortie & s, int symetrie) const
Definition at line 100 of file Matrice_Morse.cpp.
{
  int numerotation_fortran=(tab1_.mp_min_vect()==1);
  for (int proc=0; proc<Process::nproc(); proc++)
    {
      if (proc==Process::me())
        {
          s << "Matrix morse on the processor " << proc << " : " << finl;
          int n=nb_lignes();
          Noms tab_imp;
          tab_imp.dimensionner(nb_colonnes());
          for(int i=0; i<n; i++)
            {
              for (int k=0; k<nb_colonnes(); k++)
                tab_imp[k]="  .  ";
              if (i<10)
                s <<i << " :" ;
              else
                s <<i << ":" ;
              if (symetrie)
                {
                  for (int j=0; j<i; j++)
                    {
                      for (int k=tab1_(j)-numerotation_fortran; k<tab1_(j+1)-numerotation_fortran; k++)
                        if (tab2_(k)-numerotation_fortran==i)
                          tab_imp[j] = coeff_(k);
                    }
                  int ligne=tab2_(tab1_(i)-numerotation_fortran)-numerotation_fortran;
                  if (i!=ligne)
                    {
                      Cerr << "Problem detected on this Matrice_Morse_Sym." << finl;
                      Cerr << "The diagonal of the line " << ligne << " must be stored even if it is null." << finl;
                      exit();
                    }
                }
              for (int k=tab1_(i)-numerotation_fortran; k<tab1_(i+1)-numerotation_fortran; k++)
                if (tab2_(k)+!numerotation_fortran==0)
                  Cerr<<"Line " <<i<< " no coefficient "<<k<<finl;
                else
                  {
                    if (coeff_(k)>=0)
                      tab_imp[tab2_(k)-numerotation_fortran]=" ";
                    else
                      tab_imp[tab2_(k)-numerotation_fortran]="";
                    tab_imp[tab2_(k)-numerotation_fortran] += (Nom)coeff_(k);
                  }
              for(int k=0; k<nb_colonnes(); k++)
                s<<tab_imp[k];
              s<<finl;
            }
        }
      Process::barrier();
    }
  return s;
}
References Cerr, coeff_, vect_impl::dimensionner(), finl, Process::me(), TRUSTVect< _TYPE_ >::mp_min_vect(), nb_colonnes(), nb_lignes(), Process::nproc(), symetrie, tab1_, and tab2_.
imprimer_image() [1/2]
Sortie & Matrice_Morse::imprimer_image (Sortie & s) const
Definition at line 157 of file Matrice_Morse.cpp.
{
  return imprimer_image(s,0);
}
References imprimer_image().
Referenced by imprimer_image().
imprimer_image() [2/2]
Sortie & Matrice_Morse::imprimer_image (Sortie & s, int symetrie) const
Definition at line 162 of file Matrice_Morse.cpp.
{
  int numerotation_fortran=(tab1_.mp_min_vect()==1);
  for (int proc=0; proc<Process::nproc(); proc++)
    {
      if (proc==Process::me())
        {
          s << "Matrix morse on the processor " << proc << " : " << finl;
          int n=nb_lignes();
          Noms tab_imp;
          tab_imp.dimensionner(nb_colonnes());
          for(int i=0; i<n; i++)
            {
              for (int k=0; k<nb_colonnes(); k++)
                tab_imp[k]="\u2588\u2588";
              if (i<10)
                s <<i << " :" ;
              else
                s <<i << ":" ;
              if (symetrie)
                {
                  for (int j=0; j<i; j++)
                    {
                      for (int k=tab1_(j)-numerotation_fortran; k<tab1_(j+1)-numerotation_fortran; k++)
                        if (tab2_(k)-numerotation_fortran==i)
                          tab_imp[j] = (coeff_(k) >= 0) ? "  " : "\u2592\u2592";
                    }
                  int ligne=tab2_(tab1_(i)-numerotation_fortran)-numerotation_fortran;
                  if (i!=ligne)
                    {
                      Cerr << "Problem detected on this Matrice_Morse_Sym." << finl;
                      Cerr << "The diagonal of the line " << ligne << " must be stored even if it is null." << finl;
                      exit();
                    }
                }
              for (int k=tab1_(i)-numerotation_fortran; k<tab1_(i+1)-numerotation_fortran; k++)
                if (tab2_(k)+!numerotation_fortran==0)
                  Cerr<<"Line " <<i<< " no coefficient "<<k<<finl;
                else
                  tab_imp[tab2_(k)-numerotation_fortran] = (coeff_(k) >= 0) ? "  " : "\u2592\u2592";
              for(int k=0; k<nb_colonnes(); k++)
                s<<tab_imp[k];
              s<<finl;
            }
        }
      Process::barrier();
    }
  return s;
}
References Process::barrier(), Cerr, coeff_, vect_impl::dimensionner(), Process::exit(), finl, Process::me(), TRUSTVect< _TYPE_ >::mp_min_vect(), nb_colonnes(), nb_lignes(), Process::nproc(), symetrie, tab1_, and tab2_.
info()
const Type_info * Matrice_Morse::info () static
Definition at line 28 of file Matrice_Morse.cpp.
inverse() [1/2]
int Matrice_Morse::inverse (const DoubleVect & secmem, DoubleVect & solution, double coeff_seuil) const virtual
Calcule la solution du systeme lineaire: A * solution = secmem.
La methode utilisee est GMRES preconditionnee avec ILUT.
ATTENTION: cette methode n'a vraisemblablement jamais ete testee en parallele.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< On ne calcul L et U que si prems =1
< nombre de termes ajouter dans L et U
< ordre de la matrice
< degre de l'espace de Krilov
< tableau pour L et U
< tableau pour L et U
< tableau pour L et U
< tableau de travail pour pgmres DoubleVect Resini(nn);
< niveau d'erreur
< nombre de termes non nuls dans LU
< filtrage des coefficents de L U
< tableau de travail pour ilut DoubleVect wl(nn); // tableau de travail pour ilut
< tableau de travail pour ilut IntVect jwu(nn); // tableau de travail pour ilut IntVect jwl(nn); // tableau de travail pour ilut coeff_[0]*=2.0; // pour rendre A non singuliere!
< fichier de sortie
Reimplemented in Matrice_Morse_Sym.
Definition at line 1176 of file Matrice_Morse.cpp.
{
// B.Mat: au 20/4/2005, DoubleVect::norme() est bugge, donc la methode n'a
// sans doute jamais ete validee en parallele. Je retire norme() et je mets
// ceci:
  if (Process::nproc() > 1)
    {
      Cerr << "Matrice_Morse::inverse(const DoubleVect& secmem, DoubleVect& solution, "
           << "coeff_seuil double) const \n has never been tested in parallel" << finl;
      Cerr << "Try 'Solveur Gmres { diag }' or 'Solveur Petsc Gmres { precond diag { } }'" << finl;
      Cerr << "instead of 'Solveur Gmres { }' which is not parallelized yet." << finl;
      exit();
    }
  DoubleVect toto(secmem);
  int prems=1;                        //!< On ne calcul L et U que si prems =1
  int lf_min = 10;
  int lf = std::min(lf_min,ordre()/2);        //!< nombre de termes ajouter dans L et U
  int nn = ordre();                //!< ordre de la matrice
  int ima = std::min(lf_min,ordre()/2);        //!< degre de l'espace de Krilov
  IntVect ju;                        //!< tableau pour L et U
  DoubleVect alu;                //!< tableau pour L et U
  IntVect jlu;                        //!< tableau pour L et U
  DoubleVect vv;                //!< tableau de travail pour pgmres  DoubleVect Resini(nn);
//
  DoubleVect Resini(toto);
  int ie=1;                                //!< niveau d'erreur
  int n2 = nb_coeff()+(2*lf*nn);        //!< nombre de termes non nuls dans LU
  double r;
  double coeff_seuilr;
precond :
  {
    if (prems)
      {
// Cerr << "  ordre de la matrice de pression = " << nn << finl;
// Cerr << "  nb termes non nuls dans la matrice de pression = "
// << coeff_.size() << finl;
        int  iw = n2 + 2;
        ju.resize(nn);
        jlu.resize(iw);
        alu.resize(iw);
        double to = 1.e-10;                //!< filtrage des coefficents de L U
        DoubleVect w(nn+1);                //!< tableau de travail pour ilut        DoubleVect wl(nn);                // tableau de travail pour ilut
//
        IntVect jw(2*nn);                        //!< tableau de travail pour ilut        IntVect jwu(nn);                        // tableau de travail pour ilut IntVect jwl(nn);                        // tableau de travail pour ilut coeff_[0]*=2.0;                        // pour rendre A non singuliere!
//
//
//
// Cerr << "  ****  Preconditionnement ILUT de la matrice de pression  ****" << finl;
#ifndef CRAY
        F77NAME(ILUT)(&nn, coeff_.addr(), tab2_.addr(), tab1_.addr(), &lf,
                      &to, alu.addr(), jlu.addr(), ju.addr(),
                      &iw, w.addr(),
                      jw.addr(), &ie);
// to=0;
// wu=0.0;
// wl=0.0;
// jr=0;
// jwu=0;
// jwl=0;
// ie=0;
#else
        Cerr << "Matrice_Morse::inverse ILUT call invalid for cray"<<finl;
        exit();
#endif
// coeff_[0]*=0.5;                        // pour rendre A singuliere!
// Cerr << "     nb termes non nuls dans LU = " << n2 << finl;
        switch(ie)
          {
          case 0 :
            /*{
              Cerr << "     printing of the L and U matrixes : " << finl;
              Nom nom_fich = "matrices_L_U.precond";
              ofstream os(nom_fich);
              os << "impression des matrices L et U :\n";
              int* tab2=jlu;
              double* coeff=alu;
              double x;
              os << "termes diagonaux :" << "\n";
              for (int num=0; num<nn; num++) {
              x=coeff[num];
              os << "(" << num+1 << " , " << num+1 << ")  =  " << x << "\n";
              }
              os << "hors diagonale : " << "\n";
              for ( num=0; num<nn; num++) {
              os << "ligne " << num+1 << " : ";
              int nb_vois=tab2[num+1]-tab2[num];
              double x=0.;
              for(int vois=0; vois<nb_vois; vois++) {
              int num_vois=tab2[tab2[num]+vois-1];
              x=coeff[tab2[num]+vois-1];
              os << "(" << num_vois << " , " << x << " ) " ;
              }
              os << "\n";
              }
              os.flush();
              }
            */
            break;
          case -1 :
            Cerr << "Error in ilut 'matrix may be wrong' dixit SAAD" << finl;
            exit();
            break;
          case  -2  :
            Cerr << "Error in ilut : overflow in L " << finl;
            exit();
            break;
          case   -3  :
            Cerr << "Error in ilut : overflow in U " << finl;
            exit();
            break;
          case    -4   :
            Cerr << "Illegal value for lfil : it may be a memory trouble " << finl;
            exit();
            break;
          case    -5  :
            Cerr << "Empty line met " << finl;
            exit();
            break;
          default :
            Cerr << "Pivot empty met ! at step " << ie << finl;;
            exit();
            break;
          }
        prems=0;
      }
  }
// resol :
  {
    vv.resize(nn*(ima+1));
// Debog::verifier("Matrice_Morse::inverse solution 0 ",solution);
    assert_espace_virtuel_vect(solution);
    multvect(solution, Resini);
    Resini -= toto;
    {
      r = mp_prodscal(Resini, Resini);
      r = sqrt(r);
    }
    Cout << " Initial residu : " << r << finl;
    if (r==0)
      coeff_seuilr=DMAXFLOAT;
    else
      coeff_seuilr=coeff_seuil/r;
    Resini=toto;
    int minits = 10;
    int maxits = std::max(minits, nn);
    int io = 0;                                //!< fichier de sortie
#ifndef CRAY
    F77NAME(PGMRES)(&nn, &ima, toto.addr(), solution.addr(), vv.addr(), &coeff_seuilr,
                    &maxits, &io, coeff_.addr(), tab2_.addr(), tab1_.addr(),
                    alu.addr(), jlu.addr(), ju.addr(), &ie);
#else
    Cerr << "Matrice_Morse::inverse PGMRES call invalid for CRAY"<<finl;
    exit();
#endif
    switch(ie)
      {
      case 0:
        Cout << "     ** PGMRES has converged **" << finl;
        break;
      case 1:
        Cout << "     ** No convergence after " << maxits << " iterations **" << finl;
        toto=Resini;
        if( lf<50)
          {
            lf +=5;
            Cerr << "  The degree of the preconditioning matrix LU is increased :   " << lf << finl;
            n2 = tab2_.size()+(2*lf*nn);
            prems=1;
            goto precond ;
          }
        /*else{
          if(ima==50)
          exit();
          Cout << "  The degree of the Krylov space for PGMRES is increased :   " << (ima+=2) << finl;
          Cout << "    (=> working array for pgmres at " << (nn*(ima+1)) << " elements.)" << finl;
          goto resol ;
          }*/
        break;
      case -1:
        Cerr << "convergence reached after " << (int)0 << "iterations !! " << finl;
        Cerr << "'stationnary state may be obtened' dixit us " << finl;
        break;
      default :
        Cerr << "Something abnormal has happened : it is preferable to stop." << finl;
        exit();
      }
  }
  return(1);
}
References TRUSTArray< _TYPE_ >::addr(), assert_espace_virtuel_vect(), Cerr, coeff_, Cout, DMAXFLOAT, Process::exit(), F77NAME, finl, mp_prodscal(), Matrice_Base::multvect(), nb_coeff(), Process::nproc(), ordre(), TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), tab1_, and tab2_.
Referenced by Solv_Gmres::Gmres().
inverse() [2/2]
int Matrice_Morse::inverse (const DoubleVect & secmem, DoubleVect & solution, double coeff_seuil, int max_iter) const virtual
< On ne calcul L et U que si prems =1
< nombre de termes ajouter dans L et U
< ordre de la matrice
< degre de l'espace de Krilov
< tableau pour L et U
< tableau pour L et U
< tableau pour L et U
< tableau de travail pour pgmres
< niveau d'erreur
< nombre de termes non nuls dans LU
< filtrage des coefficents de L U
< tableau de travail pour ilut
< tableau de travail pour ilut IntVect jwl(nn); // tableau de travail pour ilut coeff_[0]*=2.0; // pour rendre A non singuliere!
< fichier de sortie
Reimplemented in Matrice_Morse_Sym.
Definition at line 1376 of file Matrice_Morse.cpp.
{
// B.Mat: au 20/4/2005, DoubleVect::norme() est bugge, donc la methode n'a
// sans doute jamais ete validee en parallele. Je retire norme() et je mets
// ceci:
  if (Process::nproc() > 1)
    {
      Cerr << "Matrice_Morse::inverse(const DoubleVect& secmem, DoubleVect& solution, "
           << "double coeff_seuil) const \n has never been tested in parallel" << finl;
      assert(0);
      exit();
    }
  DoubleVect toto(secmem);
  int prems=1;                        //!< On ne calcul L et U que si prems =1
  int lf_min = 10;
  int lf = std::min(lf_min,ordre()/2);        //!< nombre de termes ajouter dans L et U
  int nn = ordre();                //!< ordre de la matrice
  int ima = std::min(lf_min,ordre()/2);        //!< degre de l'espace de Krilov
  IntVect ju;                        //!< tableau pour L et U
  DoubleVect alu;                //!< tableau pour L et U
  IntVect jlu;                        //!< tableau pour L et U
  DoubleVect vv;                //!< tableau de travail pour pgmres
  DoubleVect Resini(nn);
  int ie=1;                                //!< niveau d'erreur
  int n2 = nb_coeff()+(2*lf*nn);        //!< nombre de termes non nuls dans LU
  double r;
  double coeff_seuilr;
// precond :
  {
    if (prems)
      {
// Cerr << "  ordre de la matrice de pression = " << nn << finl;
// Cerr << "  nb termes non nuls dans la matrice de pression = "
// << tab2_.size() << finl;
        int  iw = n2 + 2;
        ju.resize(nn);
        jlu.resize(iw);
        alu.resize(iw);
        double to = 1.e-10;                //!< filtrage des coefficents de L U
        DoubleVect w(nn+1);                //!< tableau de travail pour ilut
// IntVect jr(nn);                        // tableau de travail pour ilut
        IntVect jw(2*nn);                        //!< tableau de travail pour ilut        IntVect jwl(nn);                        // tableau de travail pour ilut coeff_[0]*=2.0;                        // pour rendre A non singuliere!
//
//
// Cerr << "  ****  Preconditionnement ILUT de la matrice de pression  ****" << finl;
#ifndef CRAY
        F77NAME(ILUT)(&nn, coeff_.addr(), tab2_.addr(), tab1_.addr(), &lf,
                      &to, alu.addr(), jlu.addr(), ju.addr(),
                      &iw, w.addr(),
                      jw.addr(), &ie);
#else
        Cerr << "Matrice_Morse::inverse ILUT call invalid for CRAY"<<finl;
        exit();
#endif
// coeff_[0]*=0.5;                        // pour rendre A singuliere!
// Cerr << "     nb termes non nuls dans LU = " << n2 << finl;
        switch(ie)
          {
          case 0 :
            /*{
              Cerr << "     printing of L and U matrixes : " << finl;
              Nom nom_fich = "matrices_L_U.precond";
              ofstream os(nom_fich);
              os << "impression des matrices L et U :\n";
              int* tab2=jlu;
              double* coeff=alu;
              double x;
              os << "termes diagonaux :" << "\n";
              for (int num=0; num<nn; num++) {
              x=coeff[num];
              os << "(" << num+1 << " , " << num+1 << ")  =  " << x << "\n";
              }
              os << "hors diagonale : " << "\n";
              for ( num=0; num<nn; num++) {
              os << "ligne " << num+1 << " : ";
              int nb_vois=tab2[num+1]-tab2[num];
              double x=0.;
              for(int vois=0; vois<nb_vois; vois++) {
              int num_vois=tab2[tab2[num]+vois-1];
              x=coeff[tab2[num]+vois-1];
              os << "(" << num_vois << " , " << x << " ) " ;
              }
              os << "\n";
              }
              os.flush();
              }
            */
// Cerr << "     matrices L et U :  OK" << finl;
            break;
          case -1 :
            Cerr << "Error in ilut 'matrix may be wrong' dixit SAAD" << finl;
            exit();
            break;
          case  -2  :
            Cerr << "Error in ilut : overflow in L " << finl;
            exit();
            break;
          case   -3  :
            Cerr << "Error in ilut : overflow in U " << finl;
            exit();
            break;
          case    -4   :
            Cerr << "Illegal value for lfil : it may be a memory trouble " << finl;
            exit();
            break;
          case    -5  :
            Cerr << "Empty line met " << finl;
            exit();
            break;
          default :
            Cerr << "Pivot null met ! at step " << ie << finl;;
            exit();
            break;
          }
        prems=0;
      }
  }
// resol :
  {
    vv.resize(nn*(ima+1));
    multvect(solution, Resini);
    Resini -= toto;
    r = mp_norme_vect(Resini);
    Cout << " Initial residu : " << r << finl;
    coeff_seuilr=coeff_seuil/r;
    Resini=toto;
    int minits = 10;
    int maxits = std::max(minits, max_iter);
    int io = 0;                                //!< fichier de sortie
#ifndef CRAY
    F77NAME(PGMRES)(&nn, &ima, toto.addr(), solution.addr(), vv.addr(), &coeff_seuilr,
                    &maxits, &io, coeff_.addr(), tab2_.addr(), tab1_.addr(),
                    alu.addr(), jlu.addr(), ju.addr(), &ie);
#else
    Cerr << "Matrice_Morse::inverse PGMRES call invalid for CRAY"<<finl;
    exit();
#endif
// multvect(solution, Resini);
// Resini -= secmem;
// r=Resini.norme();
// Cerr << " Residu final : " << r <<" coeff "<<coeff_seuilr*r<<" Its "<<maxits<< finl;
    switch(ie)
      {
      case 0:
        Cout << "     ** PGMRES has converged ** " << finl;
        break;
      case 1:
        Cout << "     ** No convergence after " << maxits << " iterations **" << finl;
        return(0);
        /*else{
          if(ima==50)
          exit();
          Cerr << "  The degree of the Krylov space for PGMRES is increased :   " << (ima+=2) << finl;
          Cerr << "    (=> working array for pgmres at " << (nn*(ima+1)) << " elements.)" << finl;
          goto resol ;
// (DoubleVect&) toto=Resini;
// if(lf<50){
// lf +=5;
// Cerr << "  J'augmente le degre de la matrice de precondition. LU:   " << lf << finl;
// n2 = coeff_.size()+(2*lf*nn);
// prems=1;
// goto precond ;
// }
          }*/
      case -1:
        Cerr << "Convergence after " << (int)0 << "iterations !! " << finl;
        Cerr << "'stationnary state may be obtened' dixit us " << finl;
        break;
      default :
        Cerr << "Something abnormal has happened : it is preferable to stop." << finl;
        exit();
      }
  }
  return(1);
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, coeff_, Cout, Process::exit(), F77NAME, finl, mp_norme_vect(), Matrice_Base::multvect(), nb_coeff(), Process::nproc(), ordre(), TRUSTVect< _TYPE_ >::resize(), tab1_, and tab2_.
largeur_de_bande()
int Matrice_Morse::largeur_de_bande () const
Retourne la largeur de bande.
Calcule la largeur de bande d'une matrice morse.
Definition at line 2277 of file Matrice_Morse.cpp.
{
  int ldist,min = 0;
  const int* p_tab1_ = get_tab1().addr();
  const int* p_tab2_ = get_tab2().addr();
  int N=ordre();
  for(int i=0; i<N; i++)
    for(int k = p_tab1_[i]; k < p_tab1_[i+1]; k++)
      {
        if (p_tab2_[k-1]-1<N)
          {
            ldist = p_tab2_[k-1] - i;
            if( min < ldist ) min = ldist;
          }
      };
  return min;
}
References TRUSTArray< _TYPE_ >::addr(), get_tab1(), get_tab2(), and ordre().
Referenced by Solv_Cholesky::Fact_Cholesky(), and Matrice_Morse_Sym::renumerote().
nb_coeff()
int Matrice_Morse::nb_coeff () const inline
nb_coeff retourne nnz
Definition at line 92 of file Matrice_Morse.h.
References coeff_, and TRUSTVect< _TYPE_ >::size().
Referenced by affecte_prod(), clean(), ILU::factoriser(), formeC(), formeF(), inverse(), operator+=(), and remplir().
nb_colonnes()
int Matrice_Morse::nb_colonnes (void) const inline override virtual
nb_colonnes retourne m
Implements Matrice_Base.
Definition at line 91 of file Matrice_Morse.h.
References m_.
Referenced by affecte_prod(), ajouter_multvect_(), ajouter_multvectT_(), SETS::assembler(), Assembleur_P_VDF::assembler_QC(), check_morse_matrix_structure(), check_sorted_morse_matrix_structure(), coeff_opt(), dimensionner(), Op_EF_base::dimensionner(), Sources::dimensionner(), Masse_PolyMAC_Face::dimensionner_blocs(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_VDF_Face_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Face_base::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Perte_Charge_Singuliere_VDF_Face::dimensionner_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Div_PolyMAC::dimensionner_blocs(), Op_Grad_PolyMAC_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Force_Tchen_PolyMAC_P0::dimensionner_blocs(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), Travail_pression_PolyMAC::dimensionner_blocs(), Op_Conv_Quick_VDF_Elem::dimensionner_blocs(), Op_Conv_Amont_VDF_Face::dimensionner_blocs(), Op_Conv_Centre_VDF_Face::dimensionner_blocs(), Op_Conv_Quick_VDF_Face::dimensionner_blocs(), Op_Diff_PolyMAC_Face::dimensionner_blocs_ext(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_matrice_sans_mem(), Equation_base::dimensionner_termes_croises(), disp_m(), imprimer_formatte(), imprimer_image(), Testeur::interpreter(), inverser_par_diagonale(), Op_VEF_Face::modifier_pour_Cl(), operation01(), operation11(), operator()(), operator=(), Matrice_Morse_Sym::operator=(), ordre(), Op_Diff_VEFP1NCP1B_Face::test(), and transpose().
nb_lignes()
int Matrice_Morse::nb_lignes (void) const inline override virtual
nb_lignes retourne n
Implements Matrice_Base.
Definition at line 90 of file Matrice_Morse.h.
References TRUSTVect< _TYPE_ >::size(), and tab1_.
Referenced by Matrix_tools::add_scaled_matrices(), Matrix_tools::add_symmetric_scaled_matrices(), affecte_prod(), Solveur_Masse_base::ajouter_masse_dt_local(), ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), ajouter_multvectT_(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Assembleur_P_VDF::assembler_QC(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som(), check_morse_matrix_structure(), check_sorted_morse_matrix_structure(), Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure(), Matrice_Morse_Sym::check_symmetric_morse_matrix_structure(), coeff_opt(), compacte(), Matrice_Morse_Sym::compacte(), diagmulmat(), dimensionner(), Op_Evanescence_Homogene_PolyMAC_Elem::dimensionner_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs(), disp_m(), ILU::factoriser(), Champ_P1NC_implementation::filtrer_resu(), formeC(), formeF(), get_stencil(), Matrice_Morse_Sym::get_stencil(), get_stencil_and_coefficients(), Matrice_Morse_Sym::get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), has_same_morse_matrix_structure(), imprimer(), imprimer_formatte(), imprimer_image(), Solveur_U_P::iterer_NS(), Matrix_tools::matdiag_mult_matmorse(), Matrix_tools::matmorse_mult_matdiag(), Matrice_Morse_Sym::multvect_et_prodscal(), operation01(), operation11(), operator()(), operator*=(), ordre(), partie_sup(), remplir(), Op_Diff_VEFP1NCP1B_Face::test(), transpose(), and Matrix_tools::uniform_matdiag_mult_matmorse().
nb_vois()
int Matrice_Morse::nb_vois (int i) const inline
< nb_vois(i) : nombre d'elements non nuls de la ligne i
Definition at line 114 of file Matrice_Morse.h.
  {
    return get_tab1()(i+1)-get_tab1()(i); //!< nb_vois(i) : nombre d'elements non nuls de la ligne i
  }
References get_tab1().
Referenced by formeC().
operator()() [1/2]
double & Matrice_Morse::operator() (int i, int j) inline
< Pour Matrice_Morse_Diag, on ne verifie pas si la case est definie et l'on renvoie 0
< On ne passe jamais ici
Definition at line 223 of file Matrice_Morse.h.
{
  assert( (symetrique_==0 && que_suis_je()=="Matrice_Morse")
          || (symetrique_==1 && que_suis_je()=="Matrice_Morse_Sym")
          || (symetrique_==2 && que_suis_je()=="Matrice_Morse_Diag") );
// if (symetrique_==1 && j<i) std::swap(i,j); // Do not use, possible error during compile: "signed overflow does not occur when assuming that (X + c) < X is always false"
  if ((symetrique_==1) && ((j-i)<0)) std::swap(i,j);
  int k1=tab1_[i]-1;
  int k2=tab1_[i+1]-1, k;
  if (sorted_ && (k = std::lower_bound(tab2_.addr() + k1, tab2_.addr() + k2, j + 1) - tab2_.addr()) < k2 && tab2_[k] == j + 1)
    return coeff_[k];
  else if (!sorted_)
    for (k=k1; k<k2; k++)
      if (tab2_[k]-1 == j) return(coeff_[k]);
  if (symetrique_==2) return zero_; //!< Pour Matrice_Morse_Diag, on ne verifie pas si la case est definie et l'on renvoie 0
#ifndef NDEBUG
// Uniquement en debug afin de permettre l'inline en optimise
  Cerr << "i or j are not suitable " << finl;
  Cerr << "i=" << i << finl;
  Cerr << "j=" << j << finl;
  Cerr << "n_lignes=" << nb_lignes() << finl;
  Cerr << "n_colonnes=" << nb_colonnes() << finl;
#endif
// This message happens when you try to fill a coefficient in a matrix whereas is was not scheduled
// If it is a symmetric matrix, it -may- be a parallelism default. Check it by running a PETSc solver
// in debug mode: there is a test to check the parallelism of the symmetric matrix...
  Cerr << "Error Matrice_Morse::operator("<< i << "," << j << ") not defined!" << finl;
  exit();
  return coeff_[0];     //!< On ne passe jamais ici
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, coeff_, Process::exit(), finl, nb_colonnes(), nb_lignes(), Objet_U::que_suis_je(), sorted_, swap(), symetrique_, tab1_, tab2_, and zero_.
Referenced by coef().
operator()() [2/2]
double Matrice_Morse::operator() (int i, int j) const inline
Definition at line 206 of file Matrice_Morse.h.
{
  assert( (symetrique_==0 && que_suis_je()=="Matrice_Morse")
          || (symetrique_==1 && que_suis_je()=="Matrice_Morse_Sym")
          || (symetrique_==2 && que_suis_je()=="Matrice_Morse_Diag") );
  if ((symetrique_==1) && ((j-i)<0)) std::swap(i,j);
  int k1=tab1_[i]-1;
  int k2=tab1_[i+1]-1, k;
  if (sorted_ && (k = std::lower_bound(tab2_.addr() + k1, tab2_.addr() + k2, j + 1) - tab2_.addr()) < k2 && tab2_[k] == j + 1)
    return coeff_[k];
  else if (!sorted_)
    for (k=k1; k<k2; k++)
      if (tab2_[k]-1 == j) return(coeff_[k]);
// Si coefficient non trouve c'est qu'il est nul:
  return(0);
}
References TRUSTArray< _TYPE_ >::addr(), coeff_, Objet_U::que_suis_je(), sorted_, swap(), symetrique_, tab1_, and tab2_.
operator*=() [1/2]
Matrice_Morse & Matrice_Morse::operator*= (const DoubleVect & x)
Operateur de multiplication d'une matrice par un vecteur:
scaling des lignes de la matrice par les coefficients
correspondants du vecteur passe en parametre.
A *= x, effectue les scaling suivants:
A(i,:) = A(i,:) * x(i), pour toutes les lignes i de A.
Returns
Matrice_Morse&
Signification: le resultat de l'operation (*this)
Contraintes:
Definition at line 1581 of file Matrice_Morse.cpp.
{
  int i,k;
  for(i = 0; i<nb_lignes(); i++)
    for(k = tab1_(i)-1; k<tab1_(i+1)-1; k++)
      coeff_(k) *= x(i);
  return *this;
}
References coeff_, nb_lignes(), and tab1_.
operator*=() [2/2]
Matrice_Morse & Matrice_Morse::operator*= (double x)
Operateur de multiplication (de tous les elements)
d'une matrice par un scalaire.
Operation: A = x * A.
Returns
Matrice_Morse&
Signification: le resultat de l'operation (*this)
Contraintes:
Definition at line 1905 of file Matrice_Morse.cpp.
{
  scale( x );
  return(*this);
}
References scale().
operator+=()
Matrice_Morse & Matrice_Morse::operator+= (const Matrice_Morse & A)
NE FAIT RIEN.
Returns
Matrice_Morse&
Signification: renvoie toujours *this
Contraintes:
Definition at line 1869 of file Matrice_Morse.cpp.
{
// PL: Avant de verifier de faire des operations couteuses en RAM, on verifie
// si ce n'est pas la meme structure:
  if (has_same_morse_matrix_structure(A))
    {
      int size = A.nb_coeff();
      const DoubleVect& coeff = A.get_coeff();
      for (int i=0; i<size; i++)
        coeff_(i)+=coeff(i);
    }
  else
    {
      *this = *this + A;
      morse_matrix_structure_has_changed_ = 1, sorted_ = 0;
    }
  return *this;
}
References coeff, coeff_, get_coeff(), has_same_morse_matrix_structure(), morse_matrix_structure_has_changed_, nb_coeff(), and sorted_.
operator-()
Matrice_Morse Matrice_Morse::operator- () const
Operateur de negation unaire, renvoie l'opposee de la matrice: - A
Appelle operator*(double,const Matrice_Morse&)
Returns
Matrice_Morse
Signification: le resultat de l'appel a operator*(double,const Matrice_Morse&)
Contraintes:
Definition at line 1849 of file Matrice_Morse.cpp.
{
  return((-1)*(*this));
}
operator/=()
Matrice_Morse & Matrice_Morse::operator/= (double x)
Operateur de division (de tous les elements)
d'une matrice par un scalaire.
Operation: A = A / x.
Returns
Matrice_Morse&
Signification: le resultat de l'operation (*this)
Contraintes:
Definition at line 2058 of file Matrice_Morse.cpp.
{
  coeff_/=x;
  return(*this);
}
References coeff_.
operator=()
Matrice_Morse & Matrice_Morse::operator= (const Matrice_Morse & a)
Operateur d'affectation d'une Matrice_Morse dans une
autre Matrice_Morse.
Definition at line 693 of file Matrice_Morse.cpp.
{
  tab1_.reset(), tab1_.copy(a.get_tab1());
  tab2_.reset(), tab2_.copy(a.get_tab2());
  coeff_.reset(), coeff_.copy(a.get_coeff());
  m_=a.nb_colonnes();
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  is_stencil_up_to_date_=a.is_stencil_up_to_date();
  return(*this);
}
References coeff_, TRUSTVect< _TYPE_ >::copy(), get_coeff(), get_tab1(), get_tab2(), Matrice_Base::is_stencil_up_to_date(), Matrice_Base::is_stencil_up_to_date_, m_, morse_matrix_structure_has_changed_, nb_colonnes(), TRUSTVect< _TYPE_ >::reset(), sorted_, tab1_, and tab2_.
ordre()
int Matrice_Morse::ordre (void) const override virtual
Renvoie l'ordre de la matrice:
- le nombre de lignes si la matrice est carree
- 0 sinon.
Returns
int
Signification: l'ordre de la matrice
Contraintes:
Implements Matrice_Base.
Definition at line 551 of file Matrice_Morse.cpp.
{
  if(nb_lignes()==nb_colonnes())
    return nb_lignes();
  else
    return 0;
}
References nb_colonnes(), and nb_lignes().
Referenced by Simple::calculer_correction_en_vitesse(), Op_Diff_RotRot::calculer_vorticite(), Solv_Cholesky::Cholesky(), Equation_base::Gradient_conjugue_diff_impl(), inverse(), largeur_de_bande(), MorseSymToMorse(), remplir(), Matrice_Morse_Sym::renumerote(), Op_Diff_RotRot::tester(), and unite().
partie_sup()
Matrice_Morse & Matrice_Morse::partie_sup (const Matrice_Morse & a) virtual
Definition at line 879 of file Matrice_Morse.cpp.
{
  int m=nb_lignes();
  int n=a.nb_lignes();
  if(m!=n)
    {
      Cerr << "Matrice_Morse::partie_sup : bad dimensions m!=n." << finl;
      exit();
    }
  double t ;
  int ko, k, i, kdiag, kfirst ;
  ko = -1 ;
  for( i=0; i< n; i++)
    {
      kfirst = ko + 1 ;
      kdiag = -1 ;
      for( k = a.tab1_[i]-1; k< a.tab1_[i+1]-1; k++)
        {
          if (a.tab2_[k]-1 >= i)
            {
              ko++ ;
              coeff_[ko] = a.coeff_[k] ;
              tab2_[ko] = a.tab2_[k] ;
              if (a.tab2_[k] == i) kdiag = ko ;
            }
        }
      if (kdiag != -1 && kdiag != kfirst)
        {
          t = coeff_[kdiag] ;
          coeff_[kdiag] = coeff_[kfirst] ;
          coeff_[kfirst] = t ;
          k = tab2_[kdiag] ;
          tab2_[kdiag] = tab2_[kfirst] ;
          tab2_[kfirst] = k ;
        }
      tab1_[i] = kfirst+1 ;
    }
  int nnz = (ko + 1) ;
  tab1_[n] = (nnz) + 1 ;
  tab2_.resize( nnz );
  coeff_.resize( nnz );
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  return(*this);
}
References Cerr, coeff_, Process::exit(), finl, morse_matrix_structure_has_changed_, nb_lignes(), TRUSTVect< _TYPE_ >::resize(), sorted_, tab1_, and tab2_.
Referenced by Matrice_Morse_Sym::Matrice_Morse_Sym(), Matrice_Morse_Sym::operator=(), and Matrice_Morse_Sym::renumerote().
printOn()
Sortie & Matrice_Morse::printOn (Sortie & s) const override protected virtual
Ecrit les trois tableaux de la structure de stockage
Morse sur un flot de sortie.
Returns
Sortie& s
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 45 of file Matrice_Morse.cpp.
{
  s << tab1_;
  s << tab2_;
  s << coeff_;
  s << m_ << finl;
  return s;
}
References coeff_, finl, m_, tab1_, and tab2_.
Referenced by Matrice_Morse_Diag::printOn(), and Matrice_Morse_Sym::printOn().
readOn()
Entree & Matrice_Morse::readOn (Entree & s) override protected virtual
NON CODE.
Returns
Entree& s
Signification: le flot d'entree
Contraintes:
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 68 of file Matrice_Morse.cpp.
{
  s >> tab1_;
  s >> tab2_;
  s >> coeff_;
  s >> m_;
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  return s;
}
References coeff_, m_, morse_matrix_structure_has_changed_, sorted_, tab1_, and tab2_.
Referenced by Matrice_Morse_Diag::readOn(), and Matrice_Morse_Sym::readOn().
remplir() [1/3]
void Matrice_Morse::remplir (const int ideb, const int jdeb, const int n, const int m, const Matrice_Morse & mat)
Remplissage d'une matrice morse par une matrice morse plus petite.
Definition at line 2150 of file Matrice_Morse.cpp.
{
// Verification
  assert(ideb<=n);
  assert(jdeb<=m);
// On va construire une matrice locale
  Matrice_Morse matrice_locale(mat);
// Cas ou la matrice locale est symetrique
  if (sub_type(Matrice_Morse_Sym,mat))
    {
// Creation de la partie inferieure L
      Matrice_Morse L(matrice_locale);
      L.transpose(matrice_locale);
      int lordre = L.ordre();
      for (int i=0; i<lordre; i++)
        L(i, i) = 0.;
// On ajoute M=U+L
      matrice_locale += L;
    }
// Dimensionnement de la matrice globale
  int nnz=matrice_locale.nb_coeff();
  dimensionner(n,m,nnz);
// Remplissage de la matrice globale par la matrice locale:
// Remplissage de tab1_ avec le decalage par ideb:
  int mon_nb_lignes=matrice_locale.nb_lignes();
  assert(mon_nb_lignes+ideb<=n);
  for (int i=0; i<ideb; i++)
    tab1_(i)=1;
  for (int i=0; i<mon_nb_lignes; i++)
    tab1_(i+ideb)=matrice_locale.tab1_(i);
  for (int i=mon_nb_lignes+ideb; i<n+1; i++)
    tab1_(i)=matrice_locale.tab1_(mon_nb_lignes);
// Remplissage de tab2_ avec le decalage par jdeb:
  for (int i=0; i<nnz; i++)
    tab2_(i)=matrice_locale.tab2_(i)+jdeb;
// Remplissage de coeff_:
  for (int i=0; i<nnz; i++)
    coeff_(i)=matrice_locale.coeff_(i);
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  is_stencil_up_to_date_=false;
}
References coeff_, dimensionner(), Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, nb_coeff(), nb_lignes(), ordre(), sorted_, sub_type, tab1_, tab2_, and transpose().
remplir() [2/3]
void Matrice_Morse::remplir (const IntLists & voisins, const DoubleLists & valeurs)
Definition at line 2108 of file Matrice_Morse.cpp.
{
  int num_elem;
  int compteur,rang =0;
// Remplissage des tableaux tab1, tab2 et coeff_ :
  int* p_tab1 = tab1_.addr();
  int* p_tab2 = tab2_.addr();
  double* p_coeff = coeff_.addr();
  int* tab2_ptr = p_tab2;
  int n=nb_lignes();
  for (num_elem=0; num_elem<n; num_elem++)
    {
      IntList_Curseur liste_vois(voisins[num_elem]);
      DoubleList_Curseur liste_val(valeurs[num_elem]);
      compteur =0;
      *p_tab1++ = rang;
      while  (liste_vois)
        {
          *tab2_ptr++ = liste_vois.valeur();
          *p_coeff++ = liste_val.valeur();
          ++liste_vois;
          ++liste_val;
          compteur++;
        }
// tab2[rang] = compteur;
      rang += (compteur);
    }
  tab1_(num_elem)=rang;
  formeF();
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  is_stencil_up_to_date_=false;
}
References TRUSTArray< _TYPE_ >::addr(), coeff_, compteur, formeF(), Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, nb_lignes(), sorted_, tab1_, tab2_, and TRUSTList_Curseur< _TYPE_ >::valeur().
remplir() [3/3]
void Matrice_Morse::remplir (const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag)
Definition at line 2064 of file Matrice_Morse.cpp.
{
  int num_elem;
  int compteur,rang =0;
// Remplissage des tableaux tab1, tab2 et coeff_ :
  int* p_tab1 = tab1_.addr();
  int* p_tab2 = tab2_.addr();
  double* p_coeff = coeff_.addr();
  int* tab2_ptr = p_tab2;
  int n=nb_lignes();
  for (num_elem=0; num_elem<n; num_elem++)
    {
      IntList_Curseur liste_vois(voisins[num_elem]);
      DoubleList_Curseur liste_val(valeurs[num_elem]);
      compteur =0;
      *p_tab1++ = rang;
      *tab2_ptr++=num_elem;
      *p_coeff++ = terme_diag[num_elem];
      while  (liste_vois)
        {
          *tab2_ptr++ = liste_vois.valeur();
          *p_coeff++ = liste_val.valeur();
          ++liste_vois;
          ++liste_val;
          compteur++;
        }
// tab2[rang] = compteur;
      rang += (compteur + 1);
    }
  tab1_(num_elem)=rang;
  formeF();
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  is_stencil_up_to_date_=false;
}
References TRUSTArray< _TYPE_ >::addr(), coeff_, compteur, formeF(), Matrice_Base::is_stencil_up_to_date_, morse_matrix_structure_has_changed_, nb_lignes(), sorted_, tab1_, tab2_, and TRUSTList_Curseur< _TYPE_ >::valeur().
Referenced by assembler(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Matrice_Morse(), and Matrice_Morse_Sym::Matrice_Morse_Sym().
scale()
void Matrice_Morse::scale (const double x) override virtual
Implements Matrice_Base.
Reimplemented in Matrice_Morse_Sym.
Definition at line 1911 of file Matrice_Morse.cpp.
{
  coeff_ *= x;
}
References coeff_.
Referenced by operator*=().
self_cast() [1/2]
const Matrice_Morse & Matrice_Morse::self_cast (const Objet_U & r) static
Definition at line 28 of file Matrice_Morse.cpp.
self_cast() [2/2]
Matrice_Morse & Matrice_Morse::self_cast (Objet_U & r) static
Definition at line 28 of file Matrice_Morse.cpp.
set_nb_columns()
void Matrice_Morse::set_nb_columns (const int nb_col)
Definition at line 326 of file Matrice_Morse.cpp.
{
  m_ = nb_col;
}
References m_.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_matrice_sans_mem(), Matrix_tools::extend_matrix(), Testeur::interpreter(), and Solv_GCP::prepare_data().
set_symmetric()
void Matrice_Morse::set_symmetric (const int symmetric)
Definition at line 331 of file Matrice_Morse.cpp.
{
  symetrique_ = symmetric ;
}
References symetrique_.
Referenced by Matrix_tools::allocate_symmetric_morse_matrix(), and Matrix_tools::build_symmetric_morse_matrix().
sort_stencil()
void Matrice_Morse::sort_stencil ()
Definition at line 2492 of file Matrice_Morse.cpp.
{
  if (sorted_) return; //deja fait
  for (int i = 0; i + 1 < tab1_.size(); i++) //indice de ligne
    std::sort(tab2_.addr() + tab1_(i) - 1, tab2_.addr() + tab1_(i + 1) - 1);
  morse_matrix_structure_has_changed_ = sorted_ = 1;
}
References TRUSTArray< _TYPE_ >::addr(), morse_matrix_structure_has_changed_, TRUSTVect< _TYPE_ >::size(), sort(), sorted_, tab1_, and tab2_.
Referenced by Assembleur_P_PolyMAC_P0::assembler_mat(), and Equation_base::dimensionner_matrice().
taille_memoire()
unsigned Matrice_Morse::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Matrice_Morse_Diag, and Matrice_Morse_Sym.
Definition at line 28 of file Matrice_Morse.cpp.
transpose()
Matrice_Morse & Matrice_Morse::transpose (const Matrice_Morse & a) virtual
*this = a transposee.
Definition at line 718 of file Matrice_Morse.cpp.
{
  int n=a.nb_lignes();
  int jk=nb_lignes();
  int job=1;
  int ipos=1;
  int m=a.nb_colonnes();
  int l=nb_lignes();
  if(m!=jk)
    {
      Cerr << "Matrice_Morse::transpose bad dimensions" << finl;
      exit();
    }
  m=a.nb_lignes();
  l=nb_colonnes();
  if(m!=l)
    {
      Cerr << "Matrice_Morse::transpose bad dimensions" << finl;
      exit();
    }
  {
    int i, j, k , next;
// F77NAME(CSRCSC)(&n,&o,&k,&k,a.coeff_,a.tab2_,a.tab1_,coeff_.addr(),tab2_.addr(),tab1_.addr());
// subroutine csrcsc (n,jk,job,ipos,a,ja,ia,ao,jao,iao)
// integer ia(n+1),iao(n+1),ja(*),jao(*)
// real*8  a(*),ao(*)
// c-----------------------------------------------------------------------
// c Compressed Sparse Row     to      Compressed Sparse Column
// c
// c on entry:
// c----------
// c n        = dimension of A.
// c jk     = dimensoin of Ao
// c job        = integer to indicate whether to fill the values (job.eq.1) of the
// c         matrix ao or only the pattern., i.e.,ia, and ja (job .ne.1)
// c
// c ipos  = starting position in ao, jao of the transposed matrix.
// c         the iao array takes this into account (thus iao(1) is set to ipos.)
// c         Note: this may be useful if one needs to append the data structure
// c         of the transpose to that of A. In this case use for example
// c                call csrcsc (n,1,n+2,a,ja,ia,a,ja,ia(n+2))
// c          for any other normal usage, enter ipos=1.
// c a        = real array of length nnz (nnz=number of nonzero elements in input
// c         matrix) containing the nonzero elements.
// c ja        = integer array of length nnz containing the column positions
// c           of the corresponding elements in a.
// c ia        = integer of size n+1. ia(k) contains the position in a, ja of
// c          the beginning of the k-th row.
// c
// c on return:
// c ----------
// c output arguments:
// c ao        = real array of size nzz containing the "a" part of the transpose
// c jao        = integer array of size nnz containing the column indices.
// c iao        = integer array of size n+1 containing the "ia" index array of
// c          the transpose.
// c
// c-----------------------------------------------------------------------
// c----------------- compute lengths of rows of transp(A) ----------------
// do 1 i=1,jk+1
// iao(i) = 0
// 1    continue
    for (i=0; i<=jk; i++ ) tab1_[i] = 0 ;
// do 3 i=1, n
// do 2 k=ia(i), ia(i+1)-1
// j = ja(k)+1
// iao(j) = iao(j)+1
// 2       continue
// 3    continue
    for(i=0; i<n; i++)
      {
        for(k=a.tab1_[i]-1; k<a.tab1_[i+1]-1; k++)
          {
            j = a.tab2_[k] ;
            tab1_[j] = tab1_[j] +1 ;
          }
      }
// c---------- compute pointers from lengths ------------------------------
// iao(1) = ipos
// do 4 i=1,jk
// iao(i+1) = iao(i) + iao(i+1)
// 4    continue
    tab1_[0] = ipos ;
    for(i=0; i<jk; i++) tab1_[i+1] = tab1_[i] + tab1_[i+1] ;
// c--------------- now do the actual copying -----------------------------
// do 6 i=1,n
// do 62 k=ia(i),ia(i+1)-1
// j = ja(k)
// next = iao(j)
// if (job .eq. 1)  ao(next) = a(k)
// jao(next) = i
// iao(j) = next+1
// 62      continue
// 6    continue
    for(i=0; i<n; i++)
      {
        for(k=a.tab1_[i]-1; k<a.tab1_[i+1]-1; k++)
          {
            j    = a.tab2_[k]-1 ;
            next = tab1_[j] ;
            if (job == 1)  coeff_[next-1] = a.coeff_[k] ;
            tab2_[next-1] = i+1 ;
            tab1_[j]    = next+1 ;
          }
      }
// c-------------------------- reshift iao and leave ----------------------
// do 7 i=jk,1,-1
// iao(i+1) = iao(i)
// 7    continue
// iao(1) = ipos
    for(i=jk-1; i>=0; i--)  tab1_[i+1] = tab1_[i] ;
    tab1_[0] = ipos ;
// c--------------- end of csrcsc -----------------------------------------
// c-----------------------------------------------------------------------
// end
// c-----------------------------------------------------------------------
  }
  morse_matrix_structure_has_changed_=1, sorted_ = 0;
  return(*this);
}
References Cerr, coeff_, Process::exit(), finl, morse_matrix_structure_has_changed_, nb_colonnes(), nb_lignes(), next(), sorted_, tab1_, and tab2_.
Referenced by MorseSymToMorse(), remplir(), and Matrice_Morse_Sym::renumerote().
unite()
void Matrice_Morse::unite ()
Definition at line 527 of file Matrice_Morse.cpp.
{
  coeff_ = 0.0;
  int i,n  = ordre();
  for (i=0; i<n; i++)
    operator()(i,i) = 1.0;
}
References coeff_, and ordre().
Friends And Related Function Documentation
operator*
Matrice_Morse operator* (double , const Matrice_Morse &) friend
Fonction (hors classe) amie de la classe Matrice_Morse
Scaling de la matrice par un scalaire: multiplie tous
les elements de la matrice par un scalaire.
Operation: renvoie x*A.
Returns
Matrice_Morse
Signification: le resultat de l'operation
Contraintes: la matrice resultat est allouee par la fonction
Definition at line 1827 of file Matrice_Morse.cpp.
{
  Matrice_Morse mat_res(A);
  mat_res.coeff_*=x;
  return(mat_res);
}
operator+
Matrice_Morse operator+ (const Matrice_Morse & , const Matrice_Morse &) friend
Fonction (hors classe) amie de la classe Matrice_Morse
Addition de 2 matrices au format Morse.
Operation: renvoie (A+B)
Returns
Matrice_Morse
Signification: le resultat de l'operation
Contraintes: la matrice resultat est allouee par la fonction
Definition at line 1109 of file Matrice_Morse.cpp.
{
  int nrow=A.nb_lignes();
  int ncol=A.nb_colonnes();
  int job=1;
  int ierr;
  IntVect iw(ncol);
  Matrice_Morse C;
// PL: avant de dimensionner a nzmax on verifie si A et B n'ont pas la meme structure par hasard...
// Cela evite un pic memoire provoque par l'addition de matrices dans Equation_base::dimensionner_matrice
// Sinon, APLB n'est pas optimal, voir une autre implementation genre MKL:
// https://software.intel.com/en-us/mkl-developer-reference-c-mkl-sparse-add
  int nzmax = A.has_same_morse_matrix_structure(B) ? A.nb_coeff() : A.nb_coeff()+B.nb_coeff();
  C.dimensionner(nrow, ncol, nzmax);
  F77NAME(APLB) (&nrow, &ncol, &job, A.get_coeff().addr(), A.get_tab2().addr(), A.get_tab1().addr(),
                 B.get_coeff().addr(), B.get_tab2().addr(), B.get_tab1().addr(), C.get_set_coeff().addr(),
                 C.get_set_tab2().addr(), C.get_set_tab1().addr(),
                 &nzmax,iw.addr(),&ierr);
  const int nnz = C.tab1_[nrow] - 1;
  C.get_set_tab2().resize( nnz );
  C.get_set_coeff().resize( nnz );
  C.morse_matrix_structure_has_changed_=1, C.sorted_ = 0;
  return(C);
}
Member Data Documentation
coeff_
DoubleVect Matrice_Morse::coeff_ protected
Definition at line 195 of file Matrice_Morse.h.
Referenced by affecte_prod(), ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), ajouter_multvectT_(), check_morse_matrix_structure(), check_sorted_morse_matrix_structure(), clean(), compacte(), Matrice_Morse_Sym::compacte(), construire_sous_bloc(), diagmulmat(), dimensionner(), get_coeff(), get_set_coeff(), get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), imprimer(), imprimer_formatte(), imprimer_image(), inverse(), nb_coeff(), operator()(), operator*=(), operator+=(), operator/=(), operator=(), Matrice_Morse_Sym::operator=(), partie_sup(), printOn(), readOn(), remplir(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), scale(), Matrice_Morse_Sym::scale(), transpose(), and unite().
info_obj
const Type_info Matrice_Morse::info_obj static
Definition at line 53 of file Matrice_Morse.h.
m_
int Matrice_Morse::m_ protected
Number of columns.
Definition at line 197 of file Matrice_Morse.h.
Referenced by Matrice_Morse_Sym::ajouter_multvect_(), dimensionner(), Matrice_Morse_Sym::multvect_et_prodscal(), nb_colonnes(), operator=(), Matrice_Morse_Sym::operator=(), printOn(), readOn(), and set_nb_columns().
morse_matrix_structure_has_changed_
int Matrice_Morse::morse_matrix_structure_has_changed_ mutable
Flag if matrix structure changes.
Definition at line 189 of file Matrice_Morse.h.
Referenced by affecte_prod(), assert_check_morse_matrix_structure(), assert_check_sorted_morse_matrix_structure(), Matrice_Morse_Sym::assert_check_sorted_symmetric_morse_matrix_structure(), Matrice_Morse_Sym::assert_check_symmetric_morse_matrix_structure(), compacte(), Matrice_Morse_Sym::compacte(), dimensionner(), formeC(), formeF(), Matrice_Morse(), Matrice_Morse_Sym::Matrice_Morse_Sym(), operator+=(), operator=(), Matrice_Morse_Sym::operator=(), partie_sup(), readOn(), remplir(), Matrice_Morse_Sym::renumerote(), sort_stencil(), and transpose().
sorted_
int Matrice_Morse::sorted_ mutable
Definition at line 190 of file Matrice_Morse.h.
Referenced by affecte_prod(), compacte(), dimensionner(), Equation_base::dimensionner_matrice(), Matrice_Morse(), operator()(), operator+=(), operator=(), partie_sup(), readOn(), remplir(), sort_stencil(), and transpose().
symetrique_
int Matrice_Morse::symetrique_ protected
Pour inliner operator()(i,j) afin d'optimiser.
Definition at line 198 of file Matrice_Morse.h.
Referenced by get_symmetric(), Matrice_Morse(), Matrice_Morse_Diag::Matrice_Morse_Diag(), Matrice_Morse_Sym::Matrice_Morse_Sym(), operator()(), Matrice_Morse_Sym::operator=(), and set_symmetric().
tab1_
IntVect Matrice_Morse::tab1_ protected
Definition at line 193 of file Matrice_Morse.h.
Referenced by affecte_prod(), ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), ajouter_multvectT_(), check_morse_matrix_structure(), check_sorted_morse_matrix_structure(), Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure(), Matrice_Morse_Sym::check_symmetric_morse_matrix_structure(), compacte(), Matrice_Morse_Sym::compacte(), construire_sous_bloc(), diagmulmat(), dimensionner(), formeC(), formeF(), get_set_tab1(), get_stencil(), get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), get_tab1(), has_same_morse_matrix_structure(), imprimer(), imprimer_formatte(), imprimer_image(), inverse(), nb_lignes(), operator()(), operator*=(), operator=(), Matrice_Morse_Sym::operator=(), partie_sup(), printOn(), readOn(), remplir(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), sort_stencil(), and transpose().
tab2_
IntVect Matrice_Morse::tab2_ protected
Definition at line 194 of file Matrice_Morse.h.
Referenced by affecte_prod(), ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), ajouter_multvectT_(), check_morse_matrix_structure(), check_sorted_morse_matrix_structure(), Matrice_Morse_Sym::check_sorted_symmetric_morse_matrix_structure(), Matrice_Morse_Sym::check_symmetric_morse_matrix_structure(), compacte(), Matrice_Morse_Sym::compacte(), construire_sous_bloc(), diagmulmat(), dimensionner(), formeC(), formeF(), get_set_tab2(), get_stencil(), get_stencil_and_coefficients(), Matrice_Morse_Sym::get_symmetric_stencil(), Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients(), get_tab2(), imprimer(), imprimer_formatte(), imprimer_image(), inverse(), operator()(), operator=(), Matrice_Morse_Sym::operator=(), partie_sup(), printOn(), readOn(), remplir(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), sort_stencil(), and transpose().
zero_
double Matrice_Morse::zero_ private
Definition at line 201 of file Matrice_Morse.h.
Referenced by Matrice_Morse(), and operator()().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Morse.h
src/Kernel/Math/Matrices/Matrice_Morse.cpp