TRUST: Op_Diff_PolyMAC_P0_Elem Class Reference
Op_Diff_PolyMAC_P0_Elem Class Reference
: class Op_Diff_PolyMAC_P0_Elem
<Description of class Op_Diff_PolyMAC_P0_Elem>
#include <Op_Diff_PolyMAC_P0_Elem.h>
Public Member Functions
~Op_Diff_PolyMAC_P0_Elem ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_PolyMAC_P0_Elem ()
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
int has_interface_blocs () const override
double calculer_dt_stab () const override
Calcul dt_stab.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void mettre_a_jour (double t) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
const DoubleTab & d_nucleation () const
Public Member Functions inherited from Op_Diff_PolyMAC_P0_base
Op_Diff_PolyMAC_P0_base ()
~Op_Diff_PolyMAC_P0_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
void mettre_a_jour (double t) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual int dimension_min_nu () const
virtual void modifier_nu (DoubleTab &) const
const DoubleTab & nu () const
void update_phif (int full_stencil=0) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_PolyMAC_P0_Elem & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_P0_Elem & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_PolyMAC_P0_base
static const Type_info * info ()
static Op_Diff_PolyMAC_P0_base & self_cast (Objet_U &)
static const Op_Diff_PolyMAC_P0_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_PolyMAC_P0_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Diff_PolyMAC_P0_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void update_nu () const
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Private Member Functions
void init_s_dist () const
void init_som_ext () const
Private Attributes
std::map< int, std::map< const Operateur_Diff_base *, int > > s_dist
int s_dist_init_ = 0
IntTab som_mix
IntTab som_ext_d
IntTab som_ext_pe
IntTab som_ext_pf
int som_ext_init_ = 0
DoubleTab d_nuc_
int d_nuc_a_jour_ = 0
Additional Inherited Members
Public Attributes inherited from Op_Diff_PolyMAC_P0_base
IntTab pe_ext
tableau aux faces de bord : (indice dans op_ext, indice d'element) pour les faces de type Echange_contact
IntTab phif_d
IntTab phif_e
DoubleTab phif_c
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Diff_PolyMAC_P0_base
Ref_Zone_PolyMAC_P0 la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base diffusivite_
double t_last_maj_ = -1e10
DoubleTab nu_
IntTab som_ext
int nu_constant_ = 0
int nu_a_jour_ = 0
int s_dist_init_ = 0
int som_ext_init_ = 0
int phif_a_jour_ = 0
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
: class Op_Diff_PolyMAC_P0_Elem
<Description of class Op_Diff_PolyMAC_P0_Elem>
Definition at line 30 of file Op_Diff_PolyMAC_P0_Elem.h.
Constructor & Destructor Documentation
~Op_Diff_PolyMAC_P0_Elem()
Op_Diff_PolyMAC_P0_Elem::~Op_Diff_PolyMAC_P0_Elem ()
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
Op_Diff_PolyMAC_P0_Elem()
Op_Diff_PolyMAC_P0_Elem::Op_Diff_PolyMAC_P0_Elem ()
Definition at line 43 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  declare_support_masse_volumique(1);
}
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
ajouter_blocs()
void Op_Diff_PolyMAC_P0_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
< d_nuc depends on the temperature so must only be updated once when the temperature input of the wall flux correlation is the old temperature
Reimplemented from Operateur_base.
Definition at line 273 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  init_som_ext(), update_phif();
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  int i, i_eq, i_s, il, j, k, k1, k2, kb, l, e, eb, f, fb, s, sb, sp, m, n, M, n_ext = op_ext.size(), p, pb, n_e, n_ef, nc, nl, n_m, d, db, D = dimension, sgn, sgn_l, nw, un = 1, rk, infoo, it, cv, nonlinear;
  std::vector<Matrice_Morse *> mat(n_ext); //matrices
  std::vector<int> N; //composantes
  std::vector<std::reference_wrapper<const Zone_PolyMAC_P0>> zone; //zones
  std::vector<std::reference_wrapper<const Conds_lim>> cls; //conditions aux limites
  std::vector<std::reference_wrapper<const IntTab>> fcl, e_f, f_e, f_s; //tableaux "fcl", "elem_faces", "faces_voisins"
  std::vector<std::reference_wrapper<const DoubleVect>> fs; //surfaces
  std::vector<std::reference_wrapper<const DoubleTab>> inco, nf, xp, xs, xv, diffu; //inconnues, normales aux faces, positions elems / faces / sommets
  for (i = 0, M = 0; i < n_ext; M = std::max(M, N[i]), i++)
    {
      std::string nom_mat = i ? nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString() : nom_inco;
      mat[i] = !semi_impl.count(nom_inco) && matrices.count(nom_mat) ? matrices.at(nom_mat) : NULL;
      zone.push_back(std::ref(ref_cast(Zone_PolyMAC_P0, op_ext[i]->equation().zone_dis().valeur())));
      f_e.push_back(std::ref(zone[i].get().face_voisins())), e_f.push_back(std::ref(zone[i].get().elem_faces())), f_s.push_back(std::ref(zone[i].get().face_sommets()));
      fs.push_back(std::ref(zone[i].get().face_surfaces())), nf.push_back(std::ref(zone[i].get().face_normales()));
      xp.push_back(std::ref(zone[i].get().xp())), xv.push_back(std::ref(zone[i].get().xv())), xs.push_back(std::ref(zone[i].get().zone().domaine().coord_sommets()));
      cls.push_back(std::ref(op_ext[i]->equation().zone_Cl_dis().les_conditions_limites()));
      diffu.push_back(ref_cast(Op_Diff_PolyMAC_P0_Elem, *op_ext[i]).nu());
      const Champ_Inc& ch_inc = op_ext[i]->has_champ_inco() ? op_ext[i]->mon_inconnue() : op_ext[i]->equation().inconnue();
      const Champ_Elem_PolyMAC_P0& ch = ref_cast(Champ_Elem_PolyMAC_P0, ch_inc.valeur());
      inco.push_back(std::ref(semi_impl.count(nom_mat) ? semi_impl.at(nom_mat) : ch.valeurs()));
      N.push_back(inco[i].get().line_size()), fcl.push_back(std::ref(ch.fcl()));
    }
  const Zone_PolyMAC_P0& zone0 = zone[0];
  DoubleTab *pqpi = equation().sources().size() && sub_type(Flux_interfacial_PolyMAC, equation().sources().dernier().valeur().valeur()) ? &ref_cast(Flux_interfacial_PolyMAC, equation().sources().dernier().valeur().valeur()).qpi() : NULL;
  d_nuc_ = 0; //remise a zero du diametre de nucleation
  /* avec phif : flux hors Echange_contact -> mat[0] seulement */
  DoubleTrav flux(N[0]);
  for (f = 0; f < zone0.nb_faces(); f++)
    {
      for (flux = 0, i = phif_d(f); i < phif_d(f + 1); i++)
        if ((fb = (eb = phif_e(i)) - zone0.nb_elem_tot()) < 0) //element
          {
            for (n = 0; n < N[0]; n++) flux(n) += phif_c(i, n) * fs[0](f) * inco[0](eb, n);
            if (mat[0])
              for (j = 0; j < 2 && (e = f_e[0](f, j)) >= 0; j++)
                if (e < zone[0].get().nb_elem())
                  for (n = 0; n < N[0]; n++) //derivees
                    (*mat[0])(N[0] * e + n, N[0] * eb + n) += (j ? 1 : -1) * phif_c(i, n) * fs[0](f);
          }
        else if (fcl[0](fb, 0) == 1 || fcl[0](fb, 0) == 2)
          for (n = 0; n < N[0]; n++) //Echange_impose_base
            flux(n) += (phif_c(i, n) ? phif_c(i, n) * fs[0](f) * ref_cast(Echange_impose_base, cls[0].get()[fcl[0](fb, 1)].valeur()).T_ext(fcl[0](fb, 2), n) : 0);
        else if (fcl[0](fb, 0) == 4)
          for (n = 0; n < N[0]; n++) //Neumann non homogene
            flux(n) += (phif_c(i, n) ? phif_c(i, n) * fs[0](f) * ref_cast(Neumann_paroi, cls[0].get()[fcl[0](fb, 1)].valeur()).flux_impose(fcl[0](fb, 2), n) : 0);
        else if (fcl[0](fb, 0) == 6)
          for (n = 0; n < N[0]; n++) //Dirichlet
            flux(n) += (phif_c(i, n) ? phif_c(i, n) * fs[0](f) * ref_cast(Dirichlet, cls[0].get()[fcl[0](fb, 1)].valeur()).val_imp(fcl[0](fb, 2), n) : 0);
      for (j = 0; j < 2 && (e = f_e[0](f, j)) >= 0; j++)
        if (e < zone[0].get().nb_elem())
          for (n = 0; n < N[0]; n++) //second membre -> amont/aval
            secmem(e, n) += (j ? -1 : 1) * flux(n);
      if (f < zone0.premiere_face_int())
        for (n = 0; n < N[0]; n++) flux_bords_(f, n) = flux(n); //flux aux bords
    }
  /* avec som_ext : flux autour des sommets affectes par des Echange_contact */
  double vol_s, i3[3][3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 }}, eps = 1e-8, eps_g = 1e-6, fac[3];
  std::vector<std::array<int, 2>> s_pe, s_pf; //listes { probleme, elements/bord}, { probleme, face } autour du sommet
  std::map<std::array<int, 2>, std::array<int, 2>> m_pf; //connections Echange_contact : m_pf[{pb1, f1}] = { pb2, f2 }
  std::vector<double> surf_fs, vol_es; //surfaces partielles des faces connectees au sommet (meme ordre que s_f)
  std::vector<std::array<std::array<double, 3>,2>> vec_fs;//pour chaque facette, base de (D-1) vecteurs permettant de la parcourir
  std::vector<std::vector<int>> se_f; /* se_f[i][.] : faces connectees au i-eme element connecte au sommet s */
  std::vector<int> type_f; //type_f[i] : type de la face i (numerotation du tableau fcl)
  IntTrav i_efs, i_e, i_eq_flux, i_eq_cont, i_eq_pbm, piv(1); //indices dans les matrices : i_efs(i, j, n) -> composante n de la face j de l'elem i dans s_pe, i_e(i, n) -> indice de la phase n de l'elem i de s_pe
// i_eq_{flux,cont}(i, n) -> n-ieme equation de flux/de continuite a la face i de s_pf
// i_eq_pbm(i_efs(i, j, n)) -> n-ieme equation "flux = correlation" a la face j de l'elem i de s_pe (seulement si Pb_Multiphase)
  DoubleTrav A, B, mA, mB, Ff, Fec, Qf, Qec, Tefs, C, X, Y, W(1), S, x_fs;
  i_efs.set_smart_resize(1), i_e.set_smart_resize(1), i_eq_flux.set_smart_resize(1), i_eq_cont.set_smart_resize(1), i_eq_pbm.set_smart_resize(1);
  A.set_smart_resize(1), B.set_smart_resize(1), Ff.set_smart_resize(1), Fec.set_smart_resize(1), C.set_smart_resize(1), X.set_smart_resize(1);
  Y.set_smart_resize(1), piv.set_smart_resize(1), W.set_smart_resize(1), x_fs.set_smart_resize(1), Tefs.set_smart_resize(1), S.set_smart_resize(1);
  mA.set_smart_resize(1), mB.set_smart_resize(1), Qf.set_smart_resize(1), Qec.set_smart_resize(1);
  for (i_s = 0; i_s < som_ext.dimension(0); i_s++)
    if ((s = som_ext(i_s)) < zone0.nb_som())
      {
        /* (pb, elem) connectes a s -> avec som_ext_pe (deja classes) */
        for (s_pe.clear(), n_e = 0, i = som_ext_d(i_s, 0); i < som_ext_d(i_s + 1, 0); i++, n_e++) s_pe.push_back({{ som_ext_pe(i, 0), som_ext_pe(i, 1)}});
        /* m_pf : correspondances par parois contact */
        for (m_pf.clear(), i = som_ext_d(i_s, 1); i < som_ext_d(i_s + 1, 1); i++)
          for (j = 0; j < 2; j++)
            m_pf[ {{ som_ext_pf(i, j ? 2 : 0), som_ext_pf(i, j ? 3 : 1) }}] = {{ som_ext_pf(i, j ? 0 : 2), som_ext_pf(i, j ? 1 : 3) }};
        /* faces, leurs surfaces partielles */
        for (s_pf.clear(), surf_fs.clear(), vec_fs.clear(), se_f.resize(std::max(int(se_f.size()), n_e)), i = 0; i < n_e; i++)
          for (se_f[i].clear(), p = s_pe[i][0], e = s_pe[i][1], sp = p ? s_dist[s].at(op_ext[p]) : s, j = 0; j < e_f[p].get().dimension(1) && (f = e_f[p](e, j)) >= 0; j++)
            {
              for (k = 0, sb = 0; k < f_s[p].get().dimension(1) && (sb = f_s[p](f, k)) >= 0; k++)
                if (sb == sp) break;
              if (sb != sp) continue; /* face de e non connectee a s -> on saute */
              se_f[i].push_back(f); //faces connectees a (p, e)
// couple (p, f) de la face : si la face est un Echange_contact, alors on choisit le couple du pb d'indice le plus bas
              std::array<int, 2> pf0 = {{ p, f }}, pf = m_pf.count(pf0) && m_pf[pf0] < pf0 ? m_pf[pf0] : pf0;
              if ((l = std::lower_bound(s_pf.begin(), s_pf.end(), pf) - s_pf.begin()) == (int) s_pf.size() || s_pf[l] != pf) /* si (p, f) n'est pas dans s_pf, on l'ajoute */
                {
                  s_pf.insert(s_pf.begin() + l, pf); //(pb, face) -> dans s_pf
                  if (D < 3) surf_fs.insert(surf_fs.begin() + l, fs[p](f) / 2), vec_fs.insert(vec_fs.begin() + l, {{{ xs[p](sp, 0) - xv[p](f, 0), xs[p](sp, 1) - xv[p](f, 1), 0 }, { 0, 0, 0 }}}); //2D -> facile
                  else for (surf_fs.insert(surf_fs.begin() + l, 0), vec_fs.insert(vec_fs.begin() + l, {{{ 0, 0, 0}, {0, 0, 0 }}}), m = 0; m < 2; m++) //3D -> deux sous-triangles
                  {
                    if (m == 1 || k > 0) sb = f_s[p](f, m ? (k + 1 < f_s[p].get().dimension(1) && f_s[p](f, k + 1) >= 0 ? k + 1 : 0) : k - 1); //sommet suivant (m = 1) ou precedent avec k > 0 -> facile
                    else for (n = f_s[p].get().dimension(1) - 1; (sb = f_s[p](f, n)) == -1; ) n--; //sommet precedent avec k = 0 -> on cherche a partir de la fin
                    auto v = zone0.cross(D, D, &xs[p](sp, 0), &xs[p](sb, 0), &xv[p](f, 0), &xv[p](f, 0));//produit vectoriel (xs - xf)x(xsb - xf)
                    surf_fs[l] += std::fabs(zone0.dot(&v[0], &nf[p](f, 0))) / fs[p](f) / 4; //surface a ajouter
                    for (d = 0; d < D; d++) vec_fs[l][m][d] = (xs[p](sp, d) + xs[p](sb, d)) / 2 - xv[p](f, d); //vecteur face -> arete
                  }
                }
            }
        int n_f = s_pf.size(); //nombre de faces
        /* conversion de se_f en indices dans s_f */
        for (i = 0; i < n_e; i++)
          for (p = s_pe[i][0], j = 0; j < (int) se_f[i].size(); j++)
            {
              std::array<int, 2> pf0 = { p, se_f[i][j] }, pf = m_pf.count(pf0) && m_pf[pf0] < pf0 ? m_pf[pf0] : pf0;
              se_f[i][j] = std::lower_bound(s_pf.begin(), s_pf.end(), pf) - s_pf.begin();
            }
        /* volumes */
        for (vol_es.resize(n_e), vol_s = 0, i = 0; i < n_e; vol_s += vol_es[i], i++)
          for (p = s_pe[i][0], e = s_pe[i][1], vol_es[i] = 0, j = 0; j < (int) se_f[i].size(); j++)
            k = se_f[i][j], pb = s_pf[k][0], f = s_pf[k][1], vol_es[i] += surf_fs[k] * std::fabs(zone0.dot(&xp[p](e, 0), &nf[pb](f, 0), &xv[pb](f, 0))) / fs[pb](f) / D;
        /* inconnues en paroi (i_efs), aux elements (i_e). On alloues toutes les composantes si som_mix = 1, une seule sinon */
        int mix = som_mix(i_s), Nm = mix ? 1 : N[s_pe[0][0]], t_eq, t_e, t_ec; //nombre total d'equations/variables aux faces, nombre total de variables aux elements, t_ec = t_e + 1, nombres divises par Nl
        for (n_ef = 0, i = 0; i < n_e; i++) n_ef = std::max(n_ef, int(se_f[i].size()));//nombre max de faces par elem
        for (i_efs.resize(n_e, n_ef, 1 + M * mix), i_efs = -1, i = 0, t_eq = 0; i < n_e; i++)
          for (p = s_pe[i][0], e = s_pe[i][1], j = 0; j < (int) se_f[i].size(); j++)
            {
              for (k = se_f[i][j], n = 0; n < (mix ? N[p] : 1); n++, t_eq++) i_efs(i, j, n) = t_eq; //une temperature de paroi par phase
// si face de bord d'un Pb_Multiphase (hors frontiere ouverte), une inconnue supplementaire : la Tparoi (dans ce cas, mix = 1)
              f = s_pf[k][0] == p && (e == f_e[p](s_pf[k][1], 0) || e == f_e[p](s_pf[k][1], 1)) ? s_pf[k][1] : m_pf.at(s_pf[k])[1]; //numero de face cote e
              if (sub_type(Energie_Multiphase, op_ext[p]->equation()) && ref_cast(Pb_Multiphase, op_ext[p]->equation().probleme()).has_correlation("flux_parietal") && fcl[p](f, 0) && fcl[p](f, 0) != 5)
                i_efs(i, j, M) = t_eq++;
            }
        for (i_e.resize(n_e, mix ? M : 1), i_e = -1, i = 0, t_e = 0, t_ec = 1; i < n_e; i++)
          for (p = s_pe[i][0], n = 0; n < (mix ? N[p] : 1); n++, t_e++, t_ec++) i_e(i, n) = t_e;
        /* equations */
        for (type_f.resize(n_f), i_eq_flux.resize(n_f, mix ? M : 1), i_eq_flux = -1, i_eq_cont.resize(n_f, mix ? M : 1), i_eq_cont = -1, i = 0, k = 0; i < n_f; i++)
          {
            int p1 = s_pf[i][0], p2 = m_pf.count(s_pf[i]) ? m_pf[s_pf[i]][0] : p1, p12[2] = { p1, p2}, n12[2] = { N[p1], N[p2] }; //nombres de composantes de chaque cote
            f = s_pf[i][1], type_f[i] = fcl[p1](f, 0); //type de face
            if (type_f[i] && type_f[i] != 5)
              for (j = 0; j < 2; j++)
                if (sub_type(Energie_Multiphase, op_ext[p12[j]]->equation()) //si flux parietal et CL non Neumann, il n'y a qu'une valeur en paroi
                    && ref_cast(Pb_Multiphase, op_ext[p12[j]]->equation().probleme()).has_correlation("flux_parietal")) n12[j] = 1;
            if (n12[0] != n12[1]) Cerr << "Op_Diff_PolyMAC_P0_Elem : incompatibility between " << op_ext[p1]->equation().probleme().le_nom()
                                         << " and " << op_ext[p2]->equation().probleme().le_nom() << " ( " << n12[0] << " vs " << n12[1] << " components)!" << finl, Process::exit();
// equations de flux : tous types sauf Dirichlet et Echange_impose_base
            if (type_f[i] != 6 && type_f[i] != 7 && type_f[i] != 1 && type_f[i] != 2)
              for (n = 0; n < (mix ? n12[0] : 1); n++) i_eq_flux(i, n) = k, k++;
// equations de continuite : tous types sauf Neumann
            if (type_f[i] != 4 && type_f[i] != 5)
              for (n = 0; n < (mix ? n12[0] : 1); n++) i_eq_cont(i, n) = k, k++;
          }
// si inconnues de paroi de Pb_Multiphase : equations dues aux correlations de flux (dans ce cas mix = 1)
        if (mix)
          for (i_eq_pbm.resize(t_eq), i_eq_pbm = -1, i = 0; i < n_e; i++)
            for (p = s_pe[i][0], j = 0; j < (int) se_f[i].size(); j++)
              if (i_efs(i, j, M) >= 0)
                for (n = 0; n < N[p]; n++) i_eq_pbm(i_efs(i, j, n)) = k, k++;
        assert(k == t_eq); //a-ton bien autant d'equations que d'inconnues?
        for (int essai = 0; essai < 3; essai++) /* essai 0 : MPFA O -> essai 1 : MPFA O avec x_fs mobiles -> essai 2 : MPFA symetrique (corecive, mais pas tres consistante) */
          {
            if (essai == 1) /* essai 1 : tentative de symmetrisation en deplacant les x_fs. Si mix = 1, on ne peut pas les deplacer independamment */
              {
                /* systeme lineaire */
                for (C.resize(Nm, nc = (D - 1) * n_f, nl = D * (D - 1) / 2 * t_e), Y.resize(Nm, n_m = std::max(nc, nl)), C = 0, Y = 0, i = 0, il = 0; i < n_e; i++)
                  for (p = s_pe[i][0], e = s_pe[i][1], d = 0; d < D; d++)
                    for (db = 0; db < d; db++, il += !mix)
                      for (n = 0; n < N[p]; n++, il += mix)
                        for (j = 0; j < (int) se_f[i].size(); j++)
{
                            k = se_f[i][j], f = s_pf[k][0] == p ? s_pf[k][1] : m_pf[s_pf[k]][1], sgn = e == f_e[p](f, 0) ? 1 : -1; //indice de face, num dans le probleme courant, amont/aval
                            for (l = 0; l < D; l++) fac[l] = sgn * zone0.nu_dot(&diffu[p].get(), e, n, &nf[p](f, 0), i3[l]) * surf_fs[k] / fs[p](f) / vol_es[i]; //vecteur lambda_e nf sortant * facteur commun
                            Y(!mix * n, il) += fac[d] * (xv[p](f, db) - xp[p](e, db)) - fac[db] * (xv[p](f, d) - xp[p](e, d)); //second membre
                            for (l = 0; l < D - 1; l++) C(!mix * n, (D - 1) * k + l, il) += fac[db] * vec_fs[k][l][d] - fac[d] * vec_fs[k][l][db]; //matrice
                          }
                /* resolution -> DEGLSY */
                nw = -1, F77NAME(dgelsy)(&nl, &nc, &un, &C(0, 0, 0), &nl, &Y(0, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                for (W.resize(nw = W(0)), piv.resize(nc), n = 0; n < Nm; n++)
                  piv = 0, F77NAME(dgelsy)(&nl, &nc, &un, &C(n, 0, 0), &nl, &Y(n, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                /* x_fs = xf + corrections */
                for (x_fs.resize(Nm, n_f, D), n = 0; n < Nm; n++)
                  for (i = 0; i < n_f; i++)
                    for (p = s_pf[i][0], f = s_pf[i][1], d = 0; d < D; d++)
                      for (x_fs(n, i, d) = xv[p](f, d), k = 0; k < D - 1; k++) x_fs(n, i, d) += std::min(std::max(Y(n, (D - 1) * i + k), 0.), 0.5) * vec_fs[i][k][d];
              }
            A.resize(Nm, t_eq, t_eq), B.resize(Nm, t_ec = t_e + 1, t_eq), Ff.resize(Nm, t_eq, t_eq), Fec.resize(Nm, t_eq, t_ec); //systeme A.dT_efs = B.{dT_eb, 1}, flux sortant a chaque face
            if (mix) Qf.resize(n_e, t_eq, M, M), Qec.resize(n_e, t_ec, M, M); //si Pb_Multiphase : flux paroi-interface
            /* debut du Newton sur les T_efs : initialisation aux temperatures de mailles */
            for (Tefs.resize(Nm, t_eq), i = 0; i < n_e; i++)
              for (p = s_pe[i][0], e = s_pe[i][1], j = 0; j < (int) se_f[i].size(); j++)
                {
                  for (n = 0; n < N[p]; n++) Tefs(!mix * n, i_efs(i, j, mix * n)) = inco[p](e, n); //Tefs de chaque phase
                  if (mix && i_efs(i, j, M) >= 0) Tefs(0, i_efs(i, j, M)) = inco[p](e, 0); //Tparoi : on prend la temperature de la phase 0 faute de mieux
                }
            for (it = 0, nonlinear = 0, cv = 0; !cv && it < 10; it++) //Newton sur les Tefs. Si mix = 0 (pas de Pb_Multi), une seule iteration suffit
              {
                for (A = 0, B = 0, Ff = 0, Fec = 0, Qf = 0, Qec = 0, i = 0; i < n_e; i++)
                  {
                    p = s_pe[i][0], e = s_pe[i][1], n_ef = se_f[i].size();
                    C.resize(Nm, n_ef, D), Y.resize(Nm, D, n_m = std::max(D, n_ef)), X.resize(Nm, n_ef, D);
                    /* gradient dans e */
                    if (essai < 2) /* essais 0 et 1 : gradient consistant */
                      {
                        /* gradient dans (e, s) -> matrice / second membre M.x = Y du systeme (grad u)_i = sum_f b_{fi} (x_fs_i - x_e), avec x_fs le pt de continuite de u_fs */
                        for (n = 0; n < Nm; n++)
                          for (j = 0; j < n_ef; j++)
                            for (k = se_f[i][j], pb = s_pf[k][0], f = s_pf[k][1], d = 0; d < D; d++) C(n, j, d) = (essai ? x_fs(n, k, d) : xv[pb](f, d)) - xp[p](e, d);
                        for (Y = 0, n = 0; n < Nm; n++)
                          for (d = 0; d < D; d++) Y(n, d, d) = 1;
                        nw = -1, F77NAME(dgelsy)(&D, &n_ef, &D, &C(0, 0, 0), &D, &Y(0, 0, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                        for (W.resize(nw = W(0)), piv.resize(n_m), n = 0; n < Nm; n++)
                          piv = 0, F77NAME(dgelsy)(&D, &n_ef, &D, &C(n, 0, 0), &D, &Y(n, 0, 0), &n_m, &piv(0), &eps_g, &rk, &W(0), &nw, &infoo);
                        for (n = 0; n < Nm; n++)
                          for (j = 0; j < n_ef; j++)
                            for (d = 0; d < D; d++) X(n, j, d) = Y(n, d, j); /* pour pouvoir utiliser nu_dot */
                      }
                    else for (n = 0; n < Nm; n++)
                        for (j = 0; j < n_ef; j++)
                          for (k = se_f[i][j], pb = s_pf[k][0], f = s_pf[k][1], sgn = pb == p && e == f_e[p](f, 0) ? 1 : -1, d = 0; d < D; d++)
                            X(n, j, d) = surf_fs[k] / vol_es[i] * sgn * nf[pb](f, d) / fs[pb](f); /* essai 2 : gradient non consistant */
                    /* remplissage de A, B, Ff, Fec */
                    for (j = 0; j < n_ef; j++)
                      {
                        k = se_f[i][j], f = s_pf[k][0] == p && (e == f_e[p](s_pf[k][1], 0) || e == f_e[p](s_pf[k][1], 1)) ? s_pf[k][1] : m_pf[s_pf[k]][1]; //indice de face, numero de face local
                        sgn_l = e == f_e[p](f, 0) ? 1 : -1, sgn = p == s_pf[k][0] && f == s_pf[k][1] ? sgn_l : -1; //orientation de la face locale, de la face globale
                        /* flux : remplit Ff / Fec (format standard) dans tous les cas, et les equations de A/B donnees par i_eq_flux / i_eq_cont (format LAPACK) */
                        for (l = 0; l < n_ef; l++)
                          for (kb = se_f[i][l], fb = s_pf[kb][0] == p ? s_pf[kb][1] : m_pf[s_pf[kb]][1], n = 0; n < N[p]; n++)
{
                              double x = sgn_l * zone0.nu_dot(&diffu[p].get(), e, n, &nf[p](f, 0), &X(!mix * n, l, 0)) / fs[p](f), y = x * surf_fs[k];
                              /* stockage du flux sortant dans Ff / Fec */
                              Fec(!mix * n, i_efs(i, j, mix * n), t_e) += y * (Tefs(!mix * n, i_efs(i, l, mix * n)) - inco[p](e, n));
                              Ff(!mix * n, i_efs(i, j, mix * n), i_efs(i, l, mix * n)) += y, Fec(!mix * n, i_efs(i, j, mix * n), i_e(i, mix * n)) -= y;
                              /* equations de flux : on contribue a celle de la phase (si elle existe), ou a defaut a celle de la phase 0 */
                              if ((i_eq = i_eq_flux(k, mix * n)) >= 0 || (i_eq = i_eq_flux(k, 0)) >= 0)
                                B(!mix * n, t_e, i_eq) += x * (Tefs(!mix * n, i_efs(i, l, mix * n)) - inco[p](e, n)), A(!mix * n, i_efs(i, l, mix * n), i_eq) -= x, B(!mix * n, i_e(i, mix * n), i_eq) -= x;
                              /* equations de continuite : on y contribue si on est l'amont d'un Echange_contact pour prendre en compte son coeff d'echange */
                              if (sgn > 0 && (type_f[k] && type_f[k] < 4) && ((i_eq = i_eq_cont(k, mix * n)) >= 0 || (i_eq = i_eq_cont(k, 0)) >= 0))
{
                                  double h = type_f[k] == 3 ? -1 /* inutile */ : ref_cast(Echange_impose_base, cls[p].get()[fcl[p](f, 1)].valeur()).h_imp(fcl[p](f, 1), !mix || i_eq == i_eq_cont(k, n) ? n : 0),
                                         invh = type_f[k] == 3 ? ref_cast(Echange_contact_PolyMAC_P0, cls[p].get()[fcl[p](f, 1)].valeur()).invh_paroi : 1. / std::max(h, 1e-10);
                                  B(!mix * n, t_e, i_eq) += invh * x * (Tefs(!mix * n, i_efs(i, l, mix * n)) - inco[p](e, n));
                                  A(!mix * n, i_efs(i, l, mix * n), i_eq) -= invh * x, B(!mix * n, i_e(i, mix * n), i_eq) -= invh * x;
                                }
                              /* si Pb_Multiphase : partie "flux" de l'equation sur la correlation */
                              if (mix && (i_eq = i_eq_pbm(i_efs(i, j, mix * n))) >= 0)
{
                                  B(!mix * n, t_e, i_eq) += x * (Tefs(!mix * n, i_efs(i, l, mix * n)) - inco[p](e, n));
                                  A(!mix * n, i_efs(i, l, mix * n), i_eq) -= x, B(!mix * n, i_e(i, mix * n), i_eq) -= x;
                                }
                            }
                        /* autres equations : continuite, correlations */
                        if (mix && i_efs(i, j, M) >= 0) /* inconnue de Tparoi -> Pb_Multiphase */
{
// equation de continuite : avec la Tparoi
                            if ((i_eq = i_eq_cont(k, 0)) >= 0) B(0, t_e, i_eq) += sgn * Tefs(0, i_efs(i, j, M)), A(0, i_efs(i, j, M), i_eq) -= sgn;
// equations sur les correlations
                            const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, op_ext[p]->equation().probleme());
                            const Flux_parietal_base& corr = ref_cast(Flux_parietal_base, pbm.get_correlation("Flux_parietal").valeur());
                            const DoubleTab& alpha = pbm.eq_masse.inconnue().passe(), &dh = zone[p].get().diametre_hydraulique_elem(), &press = pbm.eq_qdm.pression().passe(),
                                             &vit = pbm.eq_qdm.inconnue().passe(), &lambda = pbm.milieu().conductivite().passe(), &mu = ref_cast(Fluide_base, pbm.milieu()).viscosite_dynamique().passe(),
                                              &rho = pbm.milieu().masse_volumique().passe(), &Cp = pbm.milieu().capacite_calorifique().passe();
                            DoubleTrav qpk(N[p]), dTf_qpk(N[p], N[p]), dTp_qpk(N[p]), qpi(N[p], N[p]), dTf_qpi(N[p], N[p], N[p]), dTp_qpi(N[p], N[p]), nv(N[p]), d_nuc(N[p]);
                            for (d = 0; d < D; d++)
                              for (n = 0; n < N[p]; n++) nv(n) += std::pow(vit(zone[p].get().nb_faces_tot() + D * e + d, n), 2);
                            for (n = 0; n < N[p]; n++) nv(n) = sqrt(nv(n));
// appel : on n'est implicite qu'en les temperatures
                            corr.qp(N[p], f, dh(e), dh(e), &alpha(e, 0), &Tefs(0, i_efs(i, j, 0)), press(e), nv.addr(), Tefs(0, i_efs(i, j, M)), &lambda(e, 0), &mu(e, 0), &rho(e, 0), &Cp(e, 0),
                                    &qpk, NULL, NULL, NULL, &dTf_qpk, &dTp_qpk, &qpi, NULL, NULL, NULL, &dTf_qpi, &dTp_qpi,  &d_nuc, nonlinear);
                            /* qpk : contributions aux equations sur les Tkp */
                            for (n = 0; n < N[p]; n++)
                              for (i_eq = i_eq_pbm(i_efs(i, j, n)), B(0, t_e, i_eq) -= qpk(n), A(0, i_efs(i, j, M), i_eq) += dTp_qpk(n), m = 0; m < N[p]; m++)
                                A(0, i_efs(i, j, m), i_eq) += dTf_qpk(n, m);
                            /* qpi : contribution a l'equation de flux a la face (si elle existe), contributions au tableau de flux paroi-interface */
                            if ((i_eq = i_eq_flux(k, 0)) >= 0)
                              for (k1 = 0; k1 < N[p]; k1++)
                                for (k2 = k1 + 1; k2 < N[p]; k2++) //partie constante, derivee en Tp
                                  for (B(0, t_e, i_eq) -= qpi(k1, k2), A(0, i_efs(i, j, M), i_eq) += dTp_qpi(k1, k2), n = 0; n < N[p]; n++)
                                    A(0, i_efs(i, j, n), i_eq) += dTf_qpi(k1, k2, n);
                            for (k1 = 0; k1 < N[p]; k1++)
                              for (k2 = k1 + 1; k2 < N[p]; k2++) //partie constante, derivee en Tp
                                for (Qec(i, t_e, k1, k2) += surf_fs[k] * qpi(k1, k2), Qf(i, i_efs(i, j, M), k1, k2) += surf_fs[k] * dTp_qpi(k1, k2), m = 0; m < N[p]; m++)
                                  Qf(i, i_efs(i, j, m), k1, k2) += surf_fs[k] * dTf_qpi(k1, k2, m); //derivees en Tf
                            if (d_nuc_.dimension(0) && !d_nuc_a_jour_)
                              for (k1 = 0; k1 < N[p]; k1++) //!< d_nuc depends on the temperature so must only be updated once when the temperature input of the wall flux correlation is the old temperature
                                d_nuc_(e, k1) += d_nuc(k1), d_nuc_a_jour_ = 1;
                          }
                        else for (n = 0; n < N[p]; n++)
                            if ((i_eq = i_eq_cont(k, mix * n)) >= 0) /* pas d'inconnue de Tparoi -> continuite composante par composante */
                              B(!mix * n, t_e, i_eq) += sgn * Tefs(!mix * n, i_efs(i, j, mix * n)), A(!mix * n, i_efs(i, j, mix * n), i_eq) -= sgn;
                        /* contributions CLs : aux equations de flux si Neumann, a celles de continuite si Dirichlet ou Echange_impose */
                        if (type_f[k] == 1 || type_f[k] == 2)
                          for (n = 0; n < N[p]; n++)
                            if ((i_eq = i_eq_cont(k, mix * n)) >= 0) //Echange_impose_base
                              B(!mix * n, t_e, i_eq) -= ref_cast(Echange_impose_base, cls[p].get()[fcl[p](f, 1)].valeur()).T_ext(fcl[p](f, 2), n);
                        if (type_f[k] == 6)
                          for (n = 0; n < N[p]; n++)
                            if ((i_eq = i_eq_cont(k, mix * n)) >= 0) //Dirichlet (non homogene)
                              B(!mix * n, t_e, i_eq) -= ref_cast(Dirichlet, cls[p].get()[fcl[p](f, 1)].valeur()).val_imp(fcl[p](f, 2), n);
                        if (type_f[k] == 4)
                          for (n = 0; n < N[p]; n++)
                            if ((i_eq = i_eq_flux(k, mix * n)) >= 0) //Neumann
                              B(!mix * n, t_e, i_eq) -= ref_cast(Neumann, cls[p].get()[fcl[p](f, 1)].valeur()).flux_impose(fcl[p](f, 2), n);
                      }
                  }
                /* resolution(s) -> DGELSY */
                nw = -1, F77NAME(dgelsy)(&t_eq, &t_eq, &t_ec, &A(0, 0, 0), &t_eq, &B(0, 0, 0), &t_eq, &piv(0), &eps, &rk, &W(0), &nw, &infoo);
                for (piv.resize(t_eq), W.resize(nw = W(0)), n = 0; n < Nm; n++)
                  piv = 0, F77NAME(dgelsy)(&t_eq, &t_eq, &t_ec, &A(n, 0, 0), &t_eq, &B(n, 0, 0), &t_eq, &piv(0), &eps, &rk, &W(0), &nw, &infoo);
                /* mise a jour des Tefs et convergence. Si nonlinear = 0, tout est lineaire -> pas besoin d'autres iterations */
                for (n = 0; n < Nm; n++)
                  for (i = 0, cv = 1; i < t_eq; i++) Tefs(n, i) += B(n, t_e, i), cv &= !nonlinear || std::fabs(B(n, t_e, i)) < 1e-3;
              }
            if (!cv && essai < 2) continue; //T_efs pas converge avec flux non coercif -> on essaie de stabiliser
            else if (!cv) Cerr << "non-convergence des T_efs!" << finl, Process::exit();
            /* subbstitution dans des u_efs^n dans Fec et Qec */
            for (n = 0; n < Nm; n++)
              for (i = 0; i < t_eq; i++)
                for (j = 0; j < t_ec; j++)
                  for (k = 0; k < t_eq; k++)
                    Fec(n, i, j) += Ff(n, i, k) * B(n, j, k);
            if (mix)
              for (i = 0; i < n_e; i++)
                for (j = 0; j < t_ec; j++)
                  for (k = 0; k < t_eq; k++)
                    for (k1 = 0; k1 < M; k1++)
                      for (k2 = k1 + 1; k2 < M; k2++) Qec(i, j, k1, k2) += Qf(i, k, k1, k2) * B(0, j, k);
            /* A : forme(s) bilineaire */
            if (essai == 2) break;//pas la peine pour VFSYM
            for (A.resize(Nm, t_e, t_e), A = 0, m = 0; m < Nm; m++)
              for (i = 0; i < n_e; i++)
                for (p = s_pe[i][0], e = s_pe[i][1], j = 0; j < (int) se_f[i].size(); j++)
                  for (n = 0; n < (mix ? N[p] : 1); n++)
                    for (l = 0; l < t_e; l++) A(m, i_e(i, n), l) -= Fec(m, i_efs(i, j, n), l);
            /* symmetrisation */
            for (n = 0; n < Nm; n++)
              for (i = 0; i < t_e; i++)
                for (j = 0; j <= i; j++) A(n, i, j) = A(n, j, i) = (A(n, i, j) + A(n, j, i)) / 2;
            /* v.p. la plus petite : DSYEV */
            nw = -1, F77NAME(DSYEV)("N", "U", &t_e, &A(0, 0, 0), &t_e, S.addr(), &W(0), &nw, &infoo);
            for (W.resize(nw = W(0)), S.resize(t_e), cv = 1, n = 0; n < Nm; n++)
              F77NAME(DSYEV)("N", "U", &t_e, &A(n, 0, 0), &t_e, &S(0), &W(0), &nw, &infoo), cv &= S(0) > -1e-8 * vol_s;
            if (cv) break;
          }
        /* contributions aux flux et aux matrices */
        for (i = 0; i < n_e; i++)
          if (s_pe[i][0] == 0 && (e = s_pe[i][1]) < zone[0].get().nb_elem())
            for (j = 0; j < (int) se_f[i].size(); j++)
              for (k = se_f[i][j], f = s_pf[k][0] ? m_pf[s_pf[k]][1] : s_pf[k][1], n = 0; n < N[0]; n++) //seulement celles du probleme courant
                {
                  secmem(e, n) += Fec(!mix * n, i_efs(i, j, mix * n), t_e); //partie constante
                  if (f < zone0.premiere_face_int()) flux_bords_(f, n) += Fec(!mix * n, i_efs(i, j, mix * n), t_e);
                  for (k = 0; k < n_e; k++)
                    if (mat[p = s_pe[k][0]])
                      for (eb = s_pe[k][1], m = (mix ? 0 : n); m < (mix ? N[p] : n + 1); m++) //derivees : si on a la matrice
                        (*mat[p])(N[0] * e + n, N[p] * eb + m) -= Fec(!mix * n, i_efs(i, j, mix * n), i_e(k, mix * m));
                }
        /* contributions a qpi : partie constante seulement pour le moment */
        if (pqpi)
          for (i = 0; i < n_e; i++)
            if (s_pe[i][0] == 0)
              for (e = s_pe[i][1], k1 = 0; k1 < N[0]; k1++)
                for (k2 = k1 + 1; k2 < N[0]; k2++)
                  (*pqpi)(e, k1, k2) += Qec(i, t_e, k1, k2);
      }
}
References d_nuc_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Champ_Elem_PolyMAC::fcl(), Operateur_base::flux_bords_, Nom::getString(), Equation_base::inconnue(), init_som_ext(), O_U_Ptr::le_nom(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Operateur_Diff_base::op_ext, Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, Zone_VF::premiere_face_int(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), sgn, liste::size(), Op_Diff_PolyMAC_P0_base::som_ext, som_ext_d, som_ext_pe, Equation_base::sources(), sub_type, Op_Diff_PolyMAC_P0_base::update_phif(), Deriv_Champ_Inc_base::valeur(), valeur(), and Champ_Inc_base::valeurs().
calculer_dt_stab()
double Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 194 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  const Zone_PolyMAC_P0& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces();
  const DoubleTab& nf = zone.face_normales(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : (has_champ_masse_volumique() ? &get_champ_masse_volumique().valeurs() : NULL),
                    &diffu = diffusivite_pour_pas_de_temps().valeurs(), &lambda = diffusivite().valeurs();
  const DoubleVect& pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  update_nu();
  int i, e, f, n, N = equation().inconnue().valeurs().dimension(1), cD = diffu.dimension(0) == 1, cL = lambda.dimension(0) == 1;
  double dt = 1e10;
  DoubleTrav flux(N);
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        for (n = 0; n < N; n++)
          flux(n) += zone.nu_dot(&nu_, e, n, &nf(f, 0), &nf(f, 0)) / vf(f);
      for (n = 0; n < N; n++)
        if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) /* sous 0.5e-6, on suppose que l'evanescence fait le job */
          dt = std::min(dt, pe(e) * ve(e) * (alp ? (*alp)(e, n) : 1) * (lambda(!cL * e, n) / diffu(!cD * e, n)) / flux(n));
      if (dt < 0) abort();
    }
  return Process::mp_min(dt);
}
References Process::abort(), Op_Diff_PolyMAC_P0_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::face_normales(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Op_Diff_PolyMAC_P0_base::la_zone_poly_, Process::mp_min(), Zone_dis_base::nb_elem(), Op_Diff_PolyMAC_P0_base::nu_, Zone_Poly_base::nu_dot(), Zone_VF::porosite_elem(), ref_cast, sub_type, Op_Diff_PolyMAC_P0_base::update_nu(), Ref_Zone_PolyMAC_P0::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
completer()
void Op_Diff_PolyMAC_P0_Elem::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 68 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  Op_Diff_PolyMAC_P0_base::completer();
  const Equation_base& eq = equation();
  const Champ_Elem_PolyMAC_P0& ch = ref_cast(Champ_Elem_PolyMAC_P0, eq.inconnue().valeur());
  const Zone_PolyMAC_P0& zone = la_zone_poly_.valeur();
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Diff_PolyMAC_P0_Elem : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  flux_bords_.resize(zone.premiere_face_int(), ch.valeurs().line_size());
  const Pb_Multiphase* pbm = sub_type(Pb_Multiphase, eq.probleme()) ? &ref_cast(Pb_Multiphase, eq.probleme()) : NULL;
  if (sub_type(Energie_Multiphase, eq))
    if (pbm)
      if (pbm->has_correlation("Flux_parietal"))
        if (ref_cast(Flux_parietal_base, pbm->get_correlation("Flux_parietal").valeur()).calculates_bubble_nucleation_diameter())
          d_nuc_.resize(0, ch.valeurs().line_size()), zone.zone().creer_tableau_elements(d_nuc_);
}
References Cerr, Op_Diff_PolyMAC_P0_base::completer(), Zone::creer_tableau_elements(), d_nuc_, Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Pb_Multiphase::get_correlation(), Pb_Multiphase::has_correlation(), Equation_base::inconnue(), Zone::joint(), Op_Diff_PolyMAC_P0_base::la_zone_poly_, TRUSTVect< _TYPE_ >::line_size(), Zone::nb_joints(), Zone_VF::premiere_face_int(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, Deriv_Champ_Inc_base::valeur(), Ref_Zone_PolyMAC_P0::valeur(), Deriv_Correlation_base::valeur(), Champ_Inc_base::valeurs(), and Zone_dis_base::zone().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::completer().
cree_instance()
Objet_U * Op_Diff_PolyMAC_P0_Elem::cree_instance () static
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
d_nucleation()
const DoubleTab & Op_Diff_PolyMAC_P0_Elem::d_nucleation () const
Definition at line 662 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  if (!d_nuc_a_jour_) Cerr << "Op_Diff_PolyMAC_P0_Elem : attempt to access d_nucleation (nucleate bubble diameter) before ajouter_blocs() has been called!" << finl
                             << "Please call assembler_blocs() on Energie_Multiphase before calling it on Masse_Multiphase." << finl, Process::exit();
  return d_nuc_;
}
References Cerr, d_nuc_, d_nuc_a_jour_, Process::exit(), and finl.
dimensionner_blocs()
void Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 220 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  init_som_ext(), update_phif(!nu_constant_); //calcul de (nf.nu.grad T) : si nu variable, stencil complet
  const std::string nom_inco = equation().inconnue().le_nom().getString();
  if (semi_impl.count(nom_inco)) return; //semi-implicite -> rien a dimensionner
  const Zone_PolyMAC_P0& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins();
  int i, j, k, e, e_s, p_s, f, m, n, n_sten = 0;
  std::vector<Matrice_Morse *> mat(op_ext.size());
  for (i = 0; i < (int) op_ext.size(); i++) //une matrice potentielle a remplir par operateur de op_ext
    mat[i] = matrices.count(i ? nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString() : nom_inco) ?
             matrices.at(i ? nom_inco + "/" + op_ext[i]->equation().probleme().le_nom().getString() : nom_inco) : NULL;
  std::vector<int> N(op_ext.size()); //nombre de composantes par probleme de op_ext
  std::vector<IntTrav> stencil(op_ext.size()); //stencils par matrice
  for (i = 0; i < (int) op_ext.size(); i++)
    stencil[i].resize(0, 2), stencil[i].set_smart_resize(1), N[i] = op_ext[i]->equation().inconnue().valeurs().line_size();
  IntTrav tpfa(0, N[0]); //pour suivre quels flux sont a deux points
  zone.creer_tableau_faces(tpfa), tpfa = 1;
  Cerr << "Op_Diff_PolyMAC_P0_Elem::dimensionner() : ";
// avec fgrad : parties hors Echange_contact (ne melange ni les problemes, ni les composantes)
  for (f = 0; f < zone.nb_faces(); f++)
    for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
      if (e < zone.nb_elem()) //stencil a l'element e
        for (j = phif_d(f); j < phif_d(f + 1); j++)
          if ((e_s = phif_e(j)) < zone.nb_elem_tot())
            for (n = 0; n < N[0]; n++)
              stencil[0].append_line(N[0] * e + n, N[0] * e_s + n), tpfa(f, n) &= e_s == f_e(f, 0) || e_s == f_e(f, 1) || phif_c(j, n) == 0;
// avec som_ext : partie Echange_contact -> melange toutes les composantes si som_mix = 1
  for (i = 0; i < som_ext.dimension(0); i++)
    for (j = som_ext_d(i, 0); j < som_ext_d(i + 1, 0); j++)
      if (!som_ext_pe(j, 0) && (e = som_ext_pe(j, 1)) < zone.nb_elem())
        for (k = som_ext_d(i, 0); k < som_ext_d(i + 1, 0); k++)
          for (p_s = som_ext_pe(k, 0), e_s = som_ext_pe(k, 1), n = 0; n < N[0]; n++)
            for (m = (som_mix(i) ? 0 : n); m < (som_mix(i) ? N[p_s] : n + 1); m++) stencil[p_s].append_line(N[0] * e + n, N[p_s] * e_s + m);
  for (i = 0; i < (int) op_ext.size(); i++)
    if (mat[i])
      {
        tableau_trier_retirer_doublons(stencil[i]);
        Matrice_Morse mat2;
        Matrix_tools::allocate_morse_matrix(N[0] * zone.nb_elem_tot(), N[i] * op_ext[i]->equation().zone_dis()->nb_elem_tot(), stencil[i], mat2);
        mat[i]->nb_colonnes() ? *mat[i] += mat2 : *mat[i] = mat2;
      }
  for (auto &&st : stencil) n_sten += st.dimension(0); //n_sten : nombre total de points du stencil de l'operateur
  Cerr << "width " << Process::mp_sum(n_sten) * 1. / (N[0] * zone.zone().md_vector_elements().valeur().nb_items_seq_tot())
       << " " << mp_somme_vect(tpfa) * 100. / (N[0] * zone.md_vector_faces().valeur().nb_items_seq_tot()) << "% TPFA " << finl;
}
References Matrix_tools::allocate_morse_matrix(), Cerr, Zone_VF::creer_tableau_faces(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Zone_VF::face_voisins(), finl, Nom::getString(), Equation_base::inconnue(), init_som_ext(), Op_Diff_PolyMAC_P0_base::la_zone_poly_, O_U_Ptr::le_nom(), Zone::md_vector_elements(), Zone_VF::md_vector_faces(), mp_somme_vect(), Process::mp_sum(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), MD_Vector_base::nb_items_seq_tot(), Op_Diff_PolyMAC_P0_base::nu_constant_, Operateur_Diff_base::op_ext, Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, Op_Diff_PolyMAC_P0_base::som_ext, som_ext_d, som_ext_pe, som_mix, tableau_trier_retirer_doublons(), Op_Diff_PolyMAC_P0_base::update_phif(), MD_Vector::valeur(), Ref_Zone_PolyMAC_P0::valeur(), and Zone_dis_base::zone().
duplique()
int Op_Diff_PolyMAC_P0_Elem::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_PolyMAC_P0_Elem, and Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
get_info()
const Type_info * Op_Diff_PolyMAC_P0_Elem::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Dift_PolyMAC_P0_Elem, and Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
has_interface_blocs()
int Op_Diff_PolyMAC_P0_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 41 of file Op_Diff_PolyMAC_P0_Elem.h.
{ return 1; }
info()
const Type_info * Op_Diff_PolyMAC_P0_Elem::info () static
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
init_s_dist()
void Op_Diff_PolyMAC_P0_Elem::init_s_dist () const private
Definition at line 87 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  if (s_dist_init_) return; //deja fait
  const Conds_lim& cls = la_zcl_poly_->les_conditions_limites();
  for (int i = 0; i < cls.size(); i++)
    if (sub_type(Echange_contact_PolyMAC_P0, cls[i].valeur()))
      {
        const Echange_contact_PolyMAC_P0& cl = ref_cast(Echange_contact_PolyMAC_P0, cls[i].valeur());
        cl.init_op();
        const Op_Diff_PolyMAC_P0_Elem *o_diff = &cl.o_diff.valeur();
        cl.init_fs_dist();
        for (auto &s_sb : cl.s_dist) s_dist[s_sb.first][o_diff] = s_sb.second;
      }
  s_dist_init_ = 1;
}
References Echange_contact_PolyMAC_P0::init_fs_dist(), Echange_contact_PolyMAC_P0::init_op(), Op_Diff_PolyMAC_P0_base::la_zcl_poly_, Zone_Cl_dis_base::les_conditions_limites(), Echange_contact_PolyMAC_P0::o_diff, ref_cast, Echange_contact_PolyMAC_P0::s_dist, s_dist, s_dist_init_, vect_impl::size(), sub_type, Ref_Op_Diff_PolyMAC_P0_Elem::valeur(), and valeur().
Referenced by init_som_ext().
init_som_ext()
void Op_Diff_PolyMAC_P0_Elem::init_som_ext () const private
< (pb, el)
< (pb1, f1, pb2, f2)
Definition at line 103 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  if (som_ext_init_) return; //deja fait
  const Zone_PolyMAC_P0& zone = la_zone_poly_.valeur();
  int i, j, k, s, sb, s_l, iop, e, f, ok;
  /* remplissage de op_ext : de proche en proche */
  op_ext = { this };
  init_s_dist();
  auto s_dist_full = s_dist;
  for (std::set<const Op_Diff_PolyMAC_P0_Elem *> op_ext_tbd = { this }; op_ext_tbd.size();)
    {
      const Op_Diff_PolyMAC_P0_Elem *op = *op_ext_tbd.begin();
      op_ext_tbd.erase(op_ext_tbd.begin());
// elargissement de op_ext
      const Conds_lim& cls = op->equation().zone_Cl_dis()->les_conditions_limites();
      for (i = 0; i < cls.size(); i++)
        if (sub_type(Echange_contact_PolyMAC_P0, cls[i].valeur()))
          {
            const Echange_contact_PolyMAC_P0& cl = ref_cast(Echange_contact_PolyMAC_P0, cls[i].valeur());
            cl.init_op();
            const Op_Diff_PolyMAC_P0_Elem *o_diff = &cl.o_diff.valeur();
            if (std::find(op_ext.begin(), op_ext.end(), o_diff) == op_ext.end())
              op_ext.push_back(o_diff), op_ext_tbd.insert(o_diff);
          }
// elargissement de s_dist_full : aargh...
      op->init_s_dist();
      if (op != this)
        for (auto && s_op_sb : s_dist_full)
          if (s_op_sb.second.count(op))
            for (auto && op_sc : op->s_dist[s_op_sb.second[op]])
              if (!s_op_sb.second.count(op_sc.first)) s_op_sb.second[op_sc.first] = op_sc.second;
    }
  /* construction de som_ext_{d, e, f} */
  som_ext.set_smart_resize(1), som_ext_d.resize(0, 2), som_ext_d.set_smart_resize(1), som_ext_d.append_line(0, 0);
  som_ext_pe.resize(0, 2), som_ext_pf.resize(0, 4), som_ext_pe.set_smart_resize(1), som_ext_pf.set_smart_resize(1);
  std::set<std::array<int, 2>> s_pe; //!< (pb, el)
  std::set<std::array<int, 4>> s_pf; //!< (pb1, f1, pb2, f2)
  std::vector<std::reference_wrapper<const Zone_PolyMAC_P0>> zones;
  std::vector<std::reference_wrapper<const IntTab>> fcl, e_f, f_s;
  for (auto &&op : op_ext) zones.push_back(std::ref(ref_cast(Zone_PolyMAC_P0, op->equation().zone_dis().valeur())));
  for (auto &&op : op_ext) fcl.push_back(std::ref(ref_cast(Champ_Elem_PolyMAC_P0, op->equation().inconnue().valeur()).fcl()));
  for (auto &&zo : zones) zo.get().init_som_elem(), e_f.push_back(std::ref(zo.get().elem_faces())), f_s.push_back(std::ref(zo.get().face_sommets()));
  /* autres CLs (hors Echange_contact) devant etre traitees par som_ext : Echange_impose_base, tout si Pb_Multiphase avec Flux_parietal_base */
  const Conds_lim& cls = equation().zone_Cl_dis()->les_conditions_limites();
  int has_flux = sub_type(Energie_Multiphase, equation()) && ref_cast(Pb_Multiphase, equation().probleme()).has_correlation("flux_parietal");
  for (i = 0; i < cls.size(); i++)
    if (has_flux || sub_type(Echange_contact_PolyMAC_P0, cls[i].valeur()))
      for (j = 0; j < ref_cast(Front_VF, cls[i]->frontiere_dis()).nb_faces(); j++)
        for (f = ref_cast(Front_VF, cls[i]->frontiere_dis()).num_face(j), k = 0; k < f_s[0].get().dimension(1) && (s = f_s[0](f, k)) >= 0; k++)
          if (!s_dist_full.count(s)) s_dist_full[s] = { }; //dans le std::map, mais pas d'operateurs distants!
  for (auto &&s_op_sb : s_dist_full)
    if ((s = s_op_sb.first) < zone.nb_som())
      {
// elements
        for (i = 0; i < zone.som_elem.get_list_size(s); i++)
          {
            std::array<int, 2> arr = { 0, zone.som_elem(s, i) };
            s_pe.insert({arr}); //cote local
          }
        for (auto &&op_sb : s_op_sb.second) //cotes distants
          {
            const Zone_PolyMAC_P0& o_zone = ref_cast(Zone_PolyMAC_P0, op_sb.first->equation().zone_dis().valeur());
            for (iop = std::find(op_ext.begin(), op_ext.end(), op_sb.first) - op_ext.begin(), i = 0; i < o_zone.som_elem.get_list_size(op_sb.second); i++)
              {
                std::array<int, 2> arr = { iop, o_zone.som_elem(op_sb.second, i) };
                s_pe.insert({arr});
              }
          }
// faces : celles des elements de s_pe
        for (auto && iop_e : s_pe)
          for (iop = iop_e[0], e = iop_e[1], s_l = iop ? s_op_sb.second.at(op_ext[iop]) : s, i = 0; i < e_f[iop].get().dimension(1) && (f = e_f[iop](e, i)) >= 0; i++)
            {
              for (ok = 0, j = 0; !ok && j < f_s[iop].get().dimension(1) && (sb = f_s[iop](f, j)) >= 0; j++) ok |= sb == s_l;
              if (!ok || fcl[iop](f, 0) != 3) continue; //face ne touchant pas le sommet ou non Echange_contact
              const Echange_contact_PolyMAC_P0& cl = ref_cast(Echange_contact_PolyMAC_P0, op_ext[iop]->equation().zone_Cl_dis()->les_conditions_limites()[fcl[iop](f, 1)].valeur());
              int o_iop = std::find(op_ext.begin(), op_ext.end(), &cl.o_diff.valeur()) - op_ext.begin(), o_f = cl.f_dist(fcl[iop](f, 2)); //operateur / face de l'autre cote
              std::array<int, 4> arr = { iop < o_iop ? iop : o_iop, iop < o_iop ? f : o_f, iop < o_iop ? o_iop : iop, iop < o_iop ? o_f : f};
              s_pf.insert({arr}); //stocke dans l'ordre
            }
        int mix = 0; //melange-t-on les composantes autour de ce sommet? oui si une equation Energie_Multiphase avec correlation de flux parietal est presente autour
        for (auto &&pe : s_pe) som_ext_pe.append_line(pe[0], pe[1]), mix |= sub_type(Energie_Multiphase, op_ext[pe[0]]->equation()) && ref_cast(Pb_Multiphase, op_ext[pe[0]]->equation().probleme()).has_correlation("flux_parietal");
        for (auto &&pf : s_pf) som_ext_pf.append_line(pf[0], pf[1], pf[2], pf[3]);
        som_ext.append_line(s), som_mix.append_line(mix), som_ext_d.append_line(som_ext_pe.dimension(0), som_ext_pf.dimension(0)), s_pe.clear(), s_pf.clear();
      }
  som_ext_init_ = 1;
}
References TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Echange_contact_PolyMAC_P0::f_dist, Static_Int_Lists::get_list_size(), Equation_base::inconnue(), Echange_contact_PolyMAC_P0::init_op(), init_s_dist(), Op_Diff_PolyMAC_P0_base::la_zone_poly_, Zone_Cl_dis::les_conditions_limites(), Zone_dis_base::nb_som(), Echange_contact_PolyMAC_P0::o_diff, Operateur_Diff_base::op_ext, ref_cast, TRUSTTab< _TYPE_ >::resize(), s_dist, TRUSTArray< _TYPE_ >::set_smart_resize(), vect_impl::size(), Zone_Poly_base::som_elem, Op_Diff_PolyMAC_P0_base::som_ext, som_ext_d, som_ext_init_, som_ext_pe, som_ext_pf, som_mix, sub_type, Deriv_Champ_Inc_base::valeur(), Ref_Op_Diff_PolyMAC_P0_Elem::valeur(), Ref_Zone_PolyMAC_P0::valeur(), valeur(), and Equation_base::zone_Cl_dis().
Referenced by ajouter_blocs(), and dimensionner_blocs().
mettre_a_jour()
void Op_Diff_PolyMAC_P0_Elem::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 669 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  Op_Diff_PolyMAC_P0_base::mettre_a_jour(t);
  d_nuc_a_jour_ = 0;
}
References d_nuc_a_jour_, and Op_Diff_PolyMAC_P0_base::mettre_a_jour().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::mettre_a_jour().
modifier_pour_Cl()
void Op_Diff_PolyMAC_P0_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 45 of file Op_Diff_PolyMAC_P0_Elem.h.
{ };
printOn()
Sortie & Op_Diff_PolyMAC_P0_Elem::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Dift_PolyMAC_P0_Elem, and Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 48 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  return Op_Diff_PolyMAC_P0_base::printOn( os );
}
References Op_Diff_PolyMAC_P0_base::printOn().
readOn()
Entree & Op_Diff_PolyMAC_P0_Elem::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Dift_PolyMAC_P0_Elem, and Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 58 of file Op_Diff_PolyMAC_P0_Elem.cpp.
{
  return Op_Diff_PolyMAC_P0_base::readOn( is );
}
References Op_Diff_PolyMAC_P0_base::readOn().
self_cast() [1/2]
const Op_Diff_PolyMAC_P0_Elem & Op_Diff_PolyMAC_P0_Elem::self_cast (const Objet_U & r) static
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
self_cast() [2/2]
Op_Diff_PolyMAC_P0_Elem & Op_Diff_PolyMAC_P0_Elem::self_cast (Objet_U & r) static
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
taille_memoire()
unsigned Op_Diff_PolyMAC_P0_Elem::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_PolyMAC_P0_Elem, and Op_Diff_Turbulent_PolyMAC_P0_Elem.
Definition at line 39 of file Op_Diff_PolyMAC_P0_Elem.cpp.
Member Data Documentation
d_nuc_
DoubleTab Op_Diff_PolyMAC_P0_Elem::d_nuc_ mutable private
Definition at line 64 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by ajouter_blocs(), completer(), and d_nucleation().
d_nuc_a_jour_
int Op_Diff_PolyMAC_P0_Elem::d_nuc_a_jour_ = 0 mutable private
Definition at line 65 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by d_nucleation(), and mettre_a_jour().
info_obj
const Type_info Op_Diff_PolyMAC_P0_Elem::info_obj static
Definition at line 33 of file Op_Diff_PolyMAC_P0_Elem.h.
s_dist
std::map<int, std::map<const Operateur_Diff_base *, int> > Op_Diff_PolyMAC_P0_Elem::s_dist mutable private
Definition at line 54 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by init_s_dist(), and init_som_ext().
s_dist_init_
int Op_Diff_PolyMAC_P0_Elem::s_dist_init_ = 0 mutable private
Definition at line 55 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by init_s_dist().
som_ext_d
IntTab Op_Diff_PolyMAC_P0_Elem::som_ext_d private
Definition at line 59 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by ajouter_blocs(), dimensionner_blocs(), and init_som_ext().
som_ext_init_
int Op_Diff_PolyMAC_P0_Elem::som_ext_init_ = 0 mutable private
Definition at line 61 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by init_som_ext().
som_ext_pe
IntTab Op_Diff_PolyMAC_P0_Elem::som_ext_pe private
Definition at line 59 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by ajouter_blocs(), dimensionner_blocs(), and init_som_ext().
som_ext_pf
IntTab Op_Diff_PolyMAC_P0_Elem::som_ext_pf private
Definition at line 59 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by init_som_ext().
som_mix
IntTab Op_Diff_PolyMAC_P0_Elem::som_mix mutable private
Definition at line 59 of file Op_Diff_PolyMAC_P0_Elem.h.
Referenced by dimensionner_blocs(), and init_som_ext().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_P0_Elem.h
src/PolyMAC/Operateurs/Op_Diff_PolyMAC_P0_Elem.cpp