TRUST: Op_Grad_VEF_P1B_Face Class Reference
Op_Grad_VEF_P1B_Face Class Reference
#include <Op_Grad_VEF_P1B_Face.h>
Public Member Functions
Op_Grad_VEF_P1B_Face ()
~Op_Grad_VEF_P1B_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Zone_VEF_PreP1b & zone_Vef () const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & modifier_grad_pour_Cl (DoubleTab &) const
DoubleTab & ajouter_elem (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_som (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_aretes (const DoubleTab &, DoubleTab &) const
int impr (Sortie &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Op_Grad_VEF_Face
Op_Grad_VEF_Face ()
~Op_Grad_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Public Member Functions inherited from Operateur_Grad_base
Operateur_Grad_base ()
~Operateur_Grad_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
virtual DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
Calcul sans les conditions aux limites ?
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_VEF_P1B_Face & self_cast (Objet_U &)
static const Op_Grad_VEF_P1B_Face & self_cast (const Objet_U &)
static double calculer_coef_som (int elem, const Zone_Cl_VEF &zcl, const Zone_VEF_PreP1b &zone_VEF)
Static Public Member Functions inherited from Op_Grad_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_VEF_Face & self_cast (Objet_U &)
static const Op_Grad_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Grad_base
static const Type_info * info ()
static Operateur_Grad_base & self_cast (Objet_U &)
static const Operateur_Grad_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Grad_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Grad_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Grad_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Grad_VEF_Face
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_P0_VEF la_pression_P0
DoubleVect porosite_surf
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 47 of file Op_Grad_VEF_P1B_Face.h.
Constructor & Destructor Documentation
Op_Grad_VEF_P1B_Face()
Op_Grad_VEF_P1B_Face::Op_Grad_VEF_P1B_Face ()
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
~Op_Grad_VEF_P1B_Face()
Op_Grad_VEF_P1B_Face::~Op_Grad_VEF_P1B_Face ()
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter (const DoubleTab & pre, DoubleTab & grad) const override virtual
Reimplemented from Operateur_Grad_base.
Definition at line 608 of file Op_Grad_VEF_P1B_Face.cpp.
{
// pre doit avoir son espace virtuel a jour
  assert_espace_virtuel_vect(pre);
// on va faire += sur l'espace virtuel, mais sans utiliser les valeurs
  assert_invalide_items_non_calcules(grad);
// Debog::verifier("Op_Grad_VEF_P1B_Face::ajouter pre", pre);
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  static int init=1;
  if(!init)
    verifier(*this, init, zone_VEF, pre, grad);
  if (zone_VEF.get_alphaE()) ajouter_elem(pre, grad);
  if (zone_VEF.get_alphaS()) ajouter_som(pre, grad);
  if (zone_VEF.get_alphaA()) ajouter_aretes(pre, grad);
  modifier_grad_pour_Cl(grad);
// Optimisation car pas necessaire:
// grad.echange_espace_virtuel();
// Debog::verifier("Op_Grad_VEF_P1B_Face::ajouter grad en sortie:", grad);
  return grad;
}
References ajouter_aretes(), ajouter_elem(), ajouter_som(), assert_espace_virtuel_vect(), assert_invalide_items_non_calcules(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Op_Grad_VEF_Face::la_zone_vef, modifier_grad_pour_Cl(), ref_cast, Ref_Zone_VEF::valeur(), and verifier().
Referenced by verifier().
ajouter_aretes()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter_aretes (const DoubleTab & pre, DoubleTab & grad) const
Definition at line 404 of file Op_Grad_VEF_P1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF =
    ref_cast(Zone_VEF_PreP1b, la_zone_vef.valeur());
  assert(zone_VEF.get_alphaA());
  const Zone& zone = zone_VEF.zone();
// const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleVect& porosite_face=zone_VEF.porosite_face();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& aretes_som=zone_VEF.zone().aretes_som();
  const IntTab& elem_aretes=zone_VEF.zone().elem_aretes();
  const ArrOfInt& renum_arete_perio=zone_VEF.get_renum_arete_perio();
  const ArrOfInt& ok_arete=zone_VEF.get_ok_arete();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
// int nps=zone_VEF.numero_premier_sommet();
  int npa=zone_VEF.numero_premiere_arete();
  int indice;
  ArrOfDouble sigma(dimension);
  for(int elem=0; elem<nb_elem_tot; elem++)
    {
      for(indice=0; indice<nfe; indice++)
        {
// som = nps+dom.get_renum_som_perio(som_elem(elem,indice));
          int face = elem_faces(elem,indice);
          double signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(int comp=0; comp<dimension; comp++)
            sigma[comp]=signe*face_normales(face,comp);
        }
      for(int isom=0; isom<3; isom++)
        {
          int somi = som_elem(elem,isom);
          int facei = elem_faces(elem,isom);
          double signei=1.;
          if (face_voisins(facei,0) != elem)
            signei=-1.;
          for(int jsom=isom+1; jsom<4; jsom++)
            {
              int somj = som_elem(elem,jsom);
              int facej = elem_faces(elem,jsom);
              double signej=1.;
              if (face_voisins(facej,0) != elem)
                signej=-1.;
              int arete = chercher_arete(elem, somi, somj,
                                         elem_aretes, aretes_som);
              arete=renum_arete_perio[arete];
              if(ok_arete[arete])
                {
                  double pa=pre(npa+arete);
                  int niinij=0;
                  for(int ksom=0; ksom<4; ksom++)
                    {
                      int face2=elem_faces(elem,ksom);
                      if((ksom==isom)||(ksom==jsom))
{
                          if(niinij==ksom)
                            niinij++;
                          for(int comp=0; comp<3; comp++)
                            grad(face2,comp)+=porosite_face(face2)*1./15.*
                                              (signei*face_normales(facei,comp)+
                                               signej*face_normales(facej,comp))*pa;
                        }
                      else
{
                          if(niinij==ksom)
                            niinij++;
                          while((niinij==jsom)||(niinij==isom))
                            niinij++;
                          assert(niinij<4);
                          int facek = elem_faces(elem,niinij);
                          double signek=1.;
                          if (face_voisins(facek,0) != elem)
                            signek=-1.;
                          for(int comp=0; comp<3; comp++)
                            grad(face2,comp)+=porosite_face(face2)*2./15.*
                                              signek*face_normales(facek,comp)*pa;
                          niinij=ksom;
                        }
                    }
                }
            }
        }
    }
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  int nb_bords =les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      {
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int num1 = le_bord.num_premiere_face();
        int num2 = num1 + le_bord.nb_faces();
        if(sub_type(Neumann_sortie_libre,la_cl.valeur()))
          {
            for (int face=num1; face<num2; face++)
              {
                int elem=face_voisins(face,0);
                for(int i=0; i<2; i++)
                  {
                    int somi=face_sommets(face,i);
                    for(int j=i+1; j<3; j++)
                      {
                        int somj=face_sommets(face,j);
                        int arete=chercher_arete(elem, somi, somj,
                                                 elem_aretes, aretes_som);
                        arete=renum_arete_perio[arete];
                        for (int comp=0; comp<dimension; comp++)
                          grad(face,comp)-= porosite_face(face)*0*
                                            face_normales(face,comp)*pre(npa+arete);
                      }
                  }
              }
          }
      }
    }
  return grad;
}
References Zone::aretes_som(), chercher_arete(), Objet_U::dimension, Zone::elem_aretes(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Op_Grad_VEF_Face::la_zcl_vef, Op_Grad_VEF_Face::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::num_premiere_face(), Zone_VEF_PreP1b::numero_premiere_arete(), Zone_VF::porosite_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_elem()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter_elem (const DoubleTab & pre, DoubleTab & grad) const
Definition at line 278 of file Op_Grad_VEF_P1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  assert(zone_VEF.get_alphaE());
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleVect& porosite_face=zone_VEF.porosite_face();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
// Si pas de support P1, on impose Neumann sur P0
  if (zone_VEF.get_alphaS()==0)
    {
      const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
      const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
      int nb_bords =les_cl.size();
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
            {
              const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre,la_cl.valeur());
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int num1 = le_bord.num_premiere_face();
              int num2 = num1 + le_bord.nb_faces();
              for (int face=num1; face<num2; face++)
                {
                  double P_imp = la_sortie_libre.flux_impose(face-num1);
                  double diff = P_imp;
                  for (int comp=0; comp<dimension; comp++)
                    grad(face,comp) += diff*face_normales(face,comp)*porosite_face(face);
                }
            }
        }
    }
  int elem,indice,face,comp;
  ArrOfDouble sigma(dimension);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      for(indice=0; indice<nfe; indice++)
        {
          double pe=pre(elem);
          face = elem_faces(elem,indice);
          double signe=1;
          if(elem!=face_voisins(face,0)) signe=-1;
          for(comp=0; comp<dimension; comp++)
            grad(face, comp) -= pe*signe*face_normales(face,comp)*porosite_face(face);
        }
    }
  return grad;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Neumann::flux_impose(), Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Op_Grad_VEF_Face::la_zcl_vef, Op_Grad_VEF_Face::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_som()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter_som (const DoubleTab & pre, DoubleTab & grad) const
Definition at line 333 of file Op_Grad_VEF_P1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  assert(zone_VEF.get_alphaS());
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleVect& porosite_face=zone_VEF.porosite_face();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nps=zone_VEF.numero_premier_sommet();
  int nb_elem_tot=zone.nb_elem_tot();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  ArrOfDouble sigma(dimension);
  for(int elem=0; elem<nb_elem_tot; elem++)
    {
      double coeff_som=calculer_coef_som(elem, zone_Cl_VEF, zone_VEF);
      for(int indice=0; indice<nfe; indice++)
        {
          int som = nps+dom.get_renum_som_perio(som_elem(elem,indice));
          double ps=pre(som);
          int face = elem_faces(elem,indice);
          double signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(int comp=0; comp<dimension; comp++)
            sigma[comp]=signe*face_normales(face,comp);
          for(int indice2=0; indice2<nfe; indice2++)
            {
              int face2 = elem_faces(elem,indice2);
              for(int comp=0; comp<dimension; comp++)
                grad(face2,comp)-=coeff_som*ps*sigma[comp]*porosite_face(face2);
            }
        }
    }
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  int nb_bords = les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if(sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          const Neumann_sortie_libre& sortie_libre = ref_cast(Neumann_sortie_libre,la_cl.valeur());
          int num1 = le_bord.num_premiere_face();
          int num2 = num1 + le_bord.nb_faces();
          for (int face=num1; face<num2; face++)
            {
              const double P_imp = sortie_libre.flux_impose(face-num1);
              for(int indice=0; indice<(nfe-1); indice++)
                {
                  int som=nps+dom.get_renum_som_perio(face_sommets(face,indice));
                  for (int comp=0; comp<dimension; comp++)
                    grad(face,comp)-=
                      1./dimension*face_normales(face,comp)*(pre(som)-P_imp)
                      *porosite_face(face);
                }
            } //fin du if sur "Neumann_sortie_libre"
        }
    }
  return grad;
}
References calculer_coef_som(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaS(), Domaine::get_renum_som_perio(), Op_Grad_VEF_Face::la_zcl_vef, Op_Grad_VEF_Face::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::num_premiere_face(), Zone_VEF_PreP1b::numero_premier_sommet(), Zone_VF::porosite_face(), ref_cast, vect_impl::size(), sortie_libre, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_coef_som()
double Op_Grad_VEF_P1B_Face::calculer_coef_som (int elem, const Zone_Cl_VEF & zcl, const Zone_VEF_PreP1b & zone_VEF) static
Definition at line 531 of file Op_Grad_VEF_P1B_Face.cpp.
{
  double coef_std=1./(Objet_U::dimension*(Objet_U::dimension+1));
  if (zone_VEF.get_modif_div_face_dirichlet()==0)
    return coef_std;
  int type_elem=0;
  int rang_elem=zone_VEF.rang_elem_non_std()(elem);
  if (rang_elem!=-1)
    type_elem=zcl.type_elem_Cl(rang_elem);
  double coef;
  if (type_elem==0)
    return coef_std;
  if (Objet_U::dimension==2)
    {
      switch(type_elem)
        {
        case 0:
          coef=3;
          break;
        case 1:
        case 2:
        case 4:
          coef=2;
          break;
        case 3:
        case 5:
        case 6:
          coef=1;
          break;
        default:
          coef=-1;
          Process::exit();
          break;
        }
    }
  else if (Objet_U::dimension==3)
    {
      switch(type_elem)
        {
        case 0:
          coef=4;
          break;
        case 1:
        case 2:
        case 4:
        case 8:
          coef=3;
          break;
        case 3:
        case 5:
        case 6:
        case 9:
        case 10:
        case 12:
          coef=2;
          break;
        case 7:
        case 11:
        case 13:
        case 14:
          coef=1;
          break;
        default:
          coef=-1;
          Process::exit();
          break;
        }
    }
  else
    {
      coef=-1;
      Process::exit();
    }
  return 1./(Objet_U::dimension*coef);
}
References Objet_U::dimension, Process::exit(), Zone_VEF_PreP1b::get_modif_div_face_dirichlet(), Zone_VEF::rang_elem_non_std(), type_elem(), and Zone_Cl_VEF::type_elem_Cl().
Referenced by ajouter_som(), and Assembleur_P_VEFPreP1B::assembler_mat().
cree_instance()
Objet_U * Op_Grad_VEF_P1B_Face::cree_instance () static
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
duplique()
int Op_Grad_VEF_P1B_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
get_info()
const Type_info * Op_Grad_VEF_P1B_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
impr()
int Op_Grad_VEF_P1B_Face::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 632 of file Op_Grad_VEF_P1B_Face.cpp.
{
  const int impr_mom=la_zone_vef->zone().Moments_a_imprimer();
  const int impr_sum=(la_zone_vef->zone().Bords_a_imprimer_sum().est_vide() ? 0:1);
  const int impr_bord=(la_zone_vef->zone().Bords_a_imprimer().est_vide() ? 0:1);
  const Schema_Temps_base& sch = equation().probleme().schema_temps();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF_PreP1b& zone_VEF = zone_Vef();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& som_elem=la_zone_vef->zone().les_elems();
  const Equation_base& eqn = equation();
  const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,eqn);
  const Champ_P1_isoP1Bulle& la_pression_P1B = ref_cast(Champ_P1_isoP1Bulle,eqn_hydr.pression_pa().valeur());
// Si on filtre:
  la_pression_P1B.filtrage(zone_VEF,la_pression_P1B);
  const DoubleVect& pression_P1B = la_pression_P1B.champ_filtre();
  Debog::verifier("la pression filtree dans Op_Grad_VEF_P1B_Face::impr=",pression_P1B);
  double pres_som, pres_arete, pres_tot ;
  double n0, n1, n2 ;
  const int nb_faces =  zone_VEF.nb_faces_tot();
  int nse=zone_VEF.zone().nb_som_elem();
  int nps=zone_VEF.numero_premier_sommet();
  int npa=zone_VEF.numero_premiere_arete();
  int elem ;
  int face;
  int som_opp, som, som_glob;
  DoubleTab xgr(nb_faces,dimension);
  xgr=0.;
// DoubleVect moment(dimension);
  if (impr_mom)
    {
      const DoubleTab& xgrav = zone_VEF.xv();
      const ArrOfDouble& c_grav=la_zone_vef->zone().cg_moments();
      for (int num_face=0; num_face <nb_faces; num_face++)
        for (int i=0; i<dimension; i++)
          xgr(num_face,i)=xgrav(num_face,i)-c_grav[i];
    }
  flux_bords_.resize(zone_VEF.nb_faces_bord(),dimension);
  flux_bords_ = 0.;
  DoubleTrav tab_flux_bords(3,zone_VEF.nb_front_Cl(),dimension);
  tab_flux_bords=0.;
  /*
    fluxx_s       ->   flux_bords2(0,num_cl,0)
    fluxy_s       ->   flux_bords2(0,num_cl,1)
    fluxz_s       ->   flux_bords2(0,num_cl,2)
    fluxx_sum_s   ->   flux_bords2(1,num_cl,0)
    fluxy_sum_s   ->   flux_bords2(1,num_cl,1)
    fluxz_sum_s   ->   flux_bords2(1,num_cl,2)
    moment(0)     ->   flux_bords2(2,num_cl,0)
    moment(1)     ->   flux_bords2(2,num_cl,1)
    moment(2)     ->   flux_bords2(2,num_cl,2)
  */
  double coeff_P1 = 1./dimension;
  double coeff_Pa = 1./dimension;
  int nb_bord = zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int impr_boundary = (zone_VEF.zone().Bords_a_imprimer_sum().contient(le_bord.le_nom()) ? 1 : 0);
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      for (face=ndeb; face<nfin; face++)
        {
          int voisin = 0;
          elem = face_voisins(face,voisin);
          if (zone_VEF.get_num_fac_loc(face, voisin)==-1)
            {
              voisin = 1;
              elem = face_voisins(face,voisin);
            }
          int signe=zone_VEF.oriente_normale(face,elem);
          som_opp = la_zone_vef->get_num_fac_loc(face, voisin);
          som_opp = som_elem(elem, som_opp);
          pres_tot = 0. ;
// Contribution de la pression P0
          if (zone_VEF.get_alphaE())
            pres_tot += pression_P1B(elem);
// Contribution de la pression P1
          if (zone_VEF.get_alphaS())
            {
              pres_som = 0.;
              for(som=0; som<nse; som++)
                {
                  som_glob = som_elem(elem, som);
                  if (som_glob != som_opp)
                    pres_som += pression_P1B(nps+som_glob);
                }
              pres_tot += coeff_P1 * pres_som;
            }
// Contribution de la pression Pa
// GF descativation car bilan incorret
          if (zone_VEF.get_alphaA()*0!=0)
            {
              pres_arete = 0.;
              const IntTab& elem_aretes=la_zone_vef->zone().elem_aretes();
              const IntTab& aretes_som=la_zone_vef->zone().aretes_som();
              for(int arete=0; arete<6; arete++)
                {
                  int arete_glob = elem_aretes(elem, arete);
                  if (aretes_som(arete_glob,0)!=som_opp && aretes_som(arete_glob,1)!=som_opp)
                    pres_arete += pression_P1B(npa+arete_glob);
                }
              pres_tot += coeff_Pa * pres_arete;
            }
// Calcul de la resultante et du couple de pression
          if (dimension == 2)
            {
              n0 = signe*face_normales(face,0) ;
              n1 = signe*face_normales(face,1) ;
              flux_bords_(face,0) = pres_tot*n0  ;
              flux_bords_(face,1) = pres_tot*n1  ;
              tab_flux_bords(0,n_bord,0) += flux_bords_(face,0) ;
              tab_flux_bords(0,n_bord,1) += flux_bords_(face,1) ;
// Calcul du moment exerce par le fluide sur le bord (OM/\F)
              if (impr_mom)
                tab_flux_bords(2,n_bord,0)+=flux_bords_(face,1)*xgr(face,0)-flux_bords_(face,0)*xgr(face,1);
              if (impr_boundary)
                {
                  tab_flux_bords(1,n_bord,0) += flux_bords_(face,0) ;
                  tab_flux_bords(1,n_bord,1) += flux_bords_(face,1) ;
                }
            }
          else if (dimension == 3)
            {
              n0   = signe*face_normales(face,0) ;
              n1   = signe*face_normales(face,1) ;
              n2   = signe*face_normales(face,2) ;
              flux_bords_(face,0) = pres_tot*n0 ;
              flux_bords_(face,1) = pres_tot*n1 ;
              flux_bords_(face,2) = pres_tot*n2 ;
              tab_flux_bords(0,n_bord,0) += flux_bords_(face,0) ;
              tab_flux_bords(0,n_bord,1) += flux_bords_(face,1) ;
              tab_flux_bords(0,n_bord,2) += flux_bords_(face,2) ;
              if (impr_mom)
                {
// Calcul du moment exerce par le fluide sur le bord (OM/\F)
                  tab_flux_bords(2,n_bord,0)+=flux_bords_(face,2)*xgr(face,1)-flux_bords_(face,1)*xgr(face,2);
                  tab_flux_bords(2,n_bord,1)+=flux_bords_(face,0)*xgr(face,2)-flux_bords_(face,2)*xgr(face,0);
                  tab_flux_bords(2,n_bord,2)+=flux_bords_(face,1)*xgr(face,0)-flux_bords_(face,0)*xgr(face,1);
                }
              if (impr_boundary)
                {
                  tab_flux_bords(1,n_bord,0) += flux_bords_(face,0) ;
                  tab_flux_bords(1,n_bord,1) += flux_bords_(face,1) ;
                  tab_flux_bords(1,n_bord,2) += flux_bords_(face,2) ;
                }
            }
        }
    } //!< fin for n_bord
// On somme les contributions de chaque processeur
  mp_sum_for_each_item(tab_flux_bords);
  if (je_suis_maitre())
    {
// Open files if needed
      SFichier Flux_grad;
      ouvrir_fichier(Flux_grad,"",1);
      SFichier Flux_grad_moment;
      ouvrir_fichier(Flux_grad_moment,"moment",impr_mom);
      SFichier Flux_grad_sum;
      ouvrir_fichier(Flux_grad_sum,"sum",impr_sum);
// Write time
      Flux_grad.add_col(sch.temps_courant());
      if (impr_sum) Flux_grad_sum.add_col(sch.temps_courant());
      if (impr_mom) Flux_grad_moment.add_col(sch.temps_courant());
// Write flux on boundaries
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          if (dimension == 2)
            {
              Flux_grad.add_col(tab_flux_bords(0,n_bord,0));
              Flux_grad.add_col(tab_flux_bords(0,n_bord,1));
              if (impr_sum)
                {
                  Flux_grad_sum.add_col(tab_flux_bords(1,n_bord,0));
                  Flux_grad_sum.add_col(tab_flux_bords(1,n_bord,1));
                }
              if (impr_mom) Flux_grad_moment.add_col(tab_flux_bords(2,n_bord,0));
            }
          else if (dimension == 3)
            {
              Flux_grad.add_col(tab_flux_bords(0,n_bord,0));
              Flux_grad.add_col(tab_flux_bords(0,n_bord,1));
              Flux_grad.add_col(tab_flux_bords(0,n_bord,2));
              if (impr_sum)
                {
                  Flux_grad_sum.add_col(tab_flux_bords(1,n_bord,0));
                  Flux_grad_sum.add_col(tab_flux_bords(1,n_bord,1));
                  Flux_grad_sum.add_col(tab_flux_bords(1,n_bord,2));
                }
              if (impr_mom)
                {
                  Flux_grad_moment.add_col(tab_flux_bords(2,n_bord,0));
                  Flux_grad_moment.add_col(tab_flux_bords(2,n_bord,1));
                  Flux_grad_moment.add_col(tab_flux_bords(2,n_bord,2));
                }
            }
        }
      Flux_grad << finl;
      if (impr_sum) Flux_grad_sum << finl;
      if (impr_mom) Flux_grad_moment << finl;
    }
  const LIST(Nom)& Liste_Bords_a_imprimer = zone_VEF.zone().Bords_a_imprimer();
  if (!Liste_Bords_a_imprimer.est_vide())
    {
      EcrFicPartage Flux_grad_face;
      ouvrir_fichier_partage(Flux_grad_face,"",impr_bord);
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          if (zone_VEF.zone().Bords_a_imprimer().contient(le_bord.le_nom()))
            {
              if (je_suis_maitre())
                {
                  Flux_grad_face << "# Force par face sur " << le_bord.le_nom() << " au temps ";
                  sch.imprimer_temps_courant(Flux_grad_face);
                  Flux_grad_face << " : " << finl;
                }
              for (face=ndeb; face<nfin; face++)
                {
                  Flux_grad_face << "# Face a x= " << zone_VEF.xv(face,0) << " y= " << zone_VEF.xv(face,1);
                  if (dimension==3) Flux_grad_face << " z= " << zone_VEF.xv(face,2);
                  Flux_grad_face << " : Fx= " << flux_bords_(face,0) << " Fy= " << flux_bords_(face,1);
                  if (dimension==3) Flux_grad_face << " Fz= " << flux_bords_(face,2);
                  Flux_grad_face << finl;
                }
              Flux_grad_face.syncfile();
            }
        }
    }
  return 1;
}
References Sortie::add_col(), Zone::aretes_som(), Zone::Bords_a_imprimer(), Zone::Bords_a_imprimer_sum(), Zone::cg_moments(), Champ_P1iP1B_implementation::champ_filtre(), List_Nom::contient(), Objet_U::dimension, Zone::elem_aretes(), MorEqn::equation(), liste::est_vide(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Champ_P1iP1B_implementation::filtrage(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VF::get_num_fac_loc(), Schema_Temps_base::imprimer_temps_courant(), Process::je_suis_maitre(), Op_Grad_VEF_Face::la_zcl_vef, Op_Grad_VEF_Face::la_zone_vef, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), LIST, Zone::Moments_a_imprimer(), mp_sum_for_each_item(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Front_VF::num_premiere_face(), Zone_VEF_PreP1b::numero_premier_sommet(), Zone_VEF_PreP1b::numero_premiere_arete(), Zone_VEF::oriente_normale(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Navier_Stokes_std::pression_pa(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Debog::verifier(), Zone_VF::xv(), Zone_dis_base::zone(), and zone_Vef().
info()
const Type_info * Op_Grad_VEF_P1B_Face::info () static
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
modifier_grad_pour_Cl()
DoubleTab & Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl (DoubleTab & grad) const
Definition at line 211 of file Op_Grad_VEF_P1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  int nb_bords =les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      {
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int num1 = le_bord.num_premiere_face();
        int num2 = num1 + le_bord.nb_faces();
        if (sub_type(Periodique,la_cl.valeur()))
          {
// periodicite
            const Periodique& la_cl_perio = ref_cast(Periodique,
                                                     la_cl.valeur());
            ArrOfInt fait(le_bord.nb_faces());
            for (int face=num1; face<num2; face++)
              {
                if(!fait[face-num1])
                  {
                    int face_associee=num1+la_cl_perio.face_associee(face-num1);
                    fait[face-num1]=(fait[face_associee-num1]=1);
                    for (int comp=0; comp<dimension; comp++)
                      grad(face_associee,comp) =
                        (grad(face,comp)+= grad(face_associee,comp));
                  }
              }
          }
        else
          {
            if(sub_type(Symetrie,la_cl.valeur()))
              {
                for (int face=num1; face<num2; face++)
                  {
                    double psc=0;
                    double norm=0;
                    int comp;
                    for (comp=0; comp<dimension; comp++)
                      {
                        psc += grad(face,comp)*face_normales(face,comp);
                        norm += face_normales(face,comp)*face_normales(face,comp);
                      }
// psc/=norm; // Fixed bug: Arithmetic exception
                    if (std::fabs(norm)>=DMINFLOAT) psc/=norm;
                    for (comp=0; comp<dimension; comp++)
                      grad(face,comp)-=psc*face_normales(face,comp);
                  }
              }
            else if(sub_type(Dirichlet,la_cl.valeur())||sub_type(Dirichlet_homogene,la_cl.valeur()))
              {
                for (int face=num1; face<num2; face++)
                  {
                    for (int comp=0; comp<dimension; comp++)
                      grad(face,comp)=0;
                  }
              }
          }
      }
    }
  return grad;
}
References Objet_U::dimension, DMINFLOAT, Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Cond_lim::frontiere_dis(), Op_Grad_VEF_Face::la_zcl_vef, Op_Grad_VEF_Face::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
printOn()
Sortie & Op_Grad_VEF_P1B_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 37 of file Op_Grad_VEF_P1B_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_VEF_P1B_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 45 of file Op_Grad_VEF_P1B_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Grad_VEF_P1B_Face & Op_Grad_VEF_P1B_Face::self_cast (const Objet_U & r) static
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
self_cast() [2/2]
Op_Grad_VEF_P1B_Face & Op_Grad_VEF_P1B_Face::self_cast (Objet_U & r) static
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
taille_memoire()
unsigned Op_Grad_VEF_P1B_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 32 of file Op_Grad_VEF_P1B_Face.cpp.
zone_Vef()
const Zone_VEF_PreP1b & Op_Grad_VEF_P1B_Face::zone_Vef () const
Definition at line 50 of file Op_Grad_VEF_P1B_Face.cpp.
{
  return ref_cast(Zone_VEF_PreP1b, la_zone_vef.valeur());
}
References Op_Grad_VEF_Face::la_zone_vef, ref_cast, and Ref_Zone_VEF::valeur().
Referenced by impr().
Member Data Documentation
info_obj
const Type_info Op_Grad_VEF_P1B_Face::info_obj static
Definition at line 50 of file Op_Grad_VEF_P1B_Face.h.
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Grad_VEF_P1B_Face.h
src/P1NCP1B/Operateurs/Op_Grad_VEF_P1B_Face.cpp