TRUST: Op_VDF_Elem Class Reference
Op_VDF_Elem Class Reference
#include <Op_VDF_Elem.h>
Public Member Functions
void dimensionner (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void dimensionner_bloc_vitesse (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &, DoubleTab &) const
Detailed Description
Definition at line 24 of file Op_VDF_Elem.h.
Member Function Documentation
dimensionner()
void Op_VDF_Elem::dimensionner (const Zone_VDF & la_zone, const Zone_Cl_VDF & la_zone_cl, Matrice_Morse & la_matrice) const
Definition at line 26 of file Op_VDF_Elem.cpp.
{
// Dimensionnement de la matrice qui devra recevoir les coefficients provenant de la convection, de la diffusion pour le cas des elements.
// Cette matrice a une structure de matrice morse.
// Nous commencons par calculer les tailles des tableaux tab1 et tab2.
  const IntTab& face_voisins = la_zone.face_voisins();
  const Conds_lim& les_cl = la_zone_cl.les_conditions_limites();
  const DoubleTab& champ_inconnue = la_zone_cl.equation().inconnue().valeurs();
  const int n1 = la_zone.zone().nb_elem_tot(), nb_comp = champ_inconnue.line_size();
  la_matrice.dimensionner(n1*nb_comp, n1*nb_comp, 0);
  IntVect& tab1 = la_matrice.get_set_tab1(), &tab2 = la_matrice.get_set_tab2();
  DoubleVect& coeff = la_matrice.get_set_coeff();
  const int ndeb = la_zone.premiere_face_int(), nfin = la_zone.nb_faces();
  coeff = 0;
  IntVect rang_voisin(n1*nb_comp);
  rang_voisin = 1;
  for (int num_face = ndeb; num_face < nfin; num_face++)
    {
      const int elem1 = face_voisins(num_face,0), elem2 = face_voisins(num_face,1);
      (rang_voisin(elem2))++;
      (rang_voisin(elem1))++;
    }
// Prise en compte des conditions de type periodicite
  for (int i = 0; i < les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          const int numdeb = la_front_dis.num_premiere_face(), nfaces = la_front_dis.nb_faces();
          int ind_face_global;
          IntVect fait(nfaces);
          fait = 0;
          for (int face = 0; face < nfaces; face++)
            {
              if (fait[face] == 0)
                {
                  fait[face] = 1;
                  fait[la_cl_perio.face_associee(face)] = 1;
                  ind_face_global = face+numdeb;
                  const int elem1 = face_voisins(ind_face_global,0), elem2 = face_voisins(ind_face_global,1);
                  (rang_voisin(elem2))++;
                  (rang_voisin(elem1))++;
                }
            }
        }
    }
// on balaye les elements pour dimensionner tab1 et tab2
  tab1(0) = 1;
  for(int i = 0; i < n1; i++)
    for (int k = 0; k < nb_comp; k++) tab1(i*nb_comp+1+k) = rang_voisin(i) +  tab1(i*nb_comp+k);
  la_matrice.dimensionner(n1*nb_comp,tab1(n1*nb_comp)-1);
  for (int i = 0; i < n1*nb_comp; i++)
    {
      tab2[tab1[i]-1] = i+1;
      rang_voisin[i] = tab1[i];
    }
// on traite les faces internes pour les voisins
  for (int num_face = ndeb; num_face < nfin; num_face++)
    {
      const int elem1 = face_voisins(num_face,0), elem2 = face_voisins(num_face,1);
      for (int k = 0; k < nb_comp; k++)
        {
          tab2[rang_voisin[elem2*nb_comp+k]] = elem1*nb_comp+1+k;
          rang_voisin[elem2*nb_comp+k]++;
          tab2[rang_voisin[elem1*nb_comp+k]] = elem2*nb_comp+1+k;
          rang_voisin[elem1*nb_comp+k]++;
        }
    }
// on traite la condition de periodicite
  for (int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      if (sub_type(Periodique,la_cl.valeur()) )
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          const int numdeb = la_front_dis.num_premiere_face(), nfaces = la_front_dis.nb_faces();
          IntVect fait(nfaces);
          fait = 0;
          for (int ind_face_local = 0; ind_face_local < nfaces; ind_face_local++)
            {
              if (fait[ind_face_local] == 0)
                {
                  const int num_face = numdeb + ind_face_local;
                  fait[ind_face_local] = 1;
                  fait[la_cl_perio.face_associee(ind_face_local)] = 1;
                  const int elem1 = face_voisins(num_face,0), elem2 = face_voisins(num_face,1);
                  for (int k = 0; k < nb_comp; k++)
                    {
                      tab2[rang_voisin[elem2*nb_comp+k]] = elem1*nb_comp+1+k;
                      rang_voisin[elem2*nb_comp+k]++;
                      tab2[rang_voisin[elem1*nb_comp+k]] = elem2*nb_comp+1+k;
                      rang_voisin[elem1*nb_comp+k]++;
                    }
                }
            }
        }
    }
}
References coeff, Matrice_Morse::dimensionner(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Equation_base::inconnue(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
Referenced by Op_Diff_VDF_Elem_base::dimensionner_blocs(), Op_Dift_VDF_Elem_base::dimensionner_blocs(), and Op_Conv_VDF< OP_TYPE >::dimensionner_elem().
dimensionner_bloc_vitesse()
void Op_VDF_Elem::dimensionner_bloc_vitesse (const Zone_VDF & la_zone, const Zone_Cl_VDF & la_zone_cl, Matrice_Morse & matrice) const
Definition at line 146 of file Op_VDF_Elem.cpp.
{
  const int nb_faces = la_zone.nb_faces(), nb_faces_tot = la_zone.nb_faces_tot(), nb_elem_tot = la_zone.nb_elem_tot();
  const IntTab& face_voisins = la_zone.face_voisins();
  IntTab stencyl(0,2);
  stencyl.set_smart_resize(1);
  int nb_coef = 0;
  for (int face = 0; face < nb_faces; face++)
    for (int dir = 0; dir < 2; dir++)
      {
        const int elem = face_voisins(face,dir);
        if (elem != -1)
          {
            stencyl.resize(nb_coef+1,2);
            stencyl(nb_coef,0) = elem;
            stencyl(nb_coef,1) = face;
            nb_coef++;
          }
      }
  tableau_trier_retirer_doublons(stencyl);
  Matrix_tools::allocate_morse_matrix(nb_elem_tot,nb_faces_tot,stencyl,matrice);
}
References Matrix_tools::allocate_morse_matrix(), Zone_VF::face_voisins(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::set_smart_resize(), and tableau_trier_retirer_doublons().
Referenced by Op_Conv_VDF< OP_TYPE >::dimensionner_bloc_vitesse_elem().
modifier_pour_Cl()
void Op_VDF_Elem::modifier_pour_Cl (const Zone_VDF & , const Zone_Cl_VDF & , Matrice_Morse & , DoubleTab &) const
Definition at line 171 of file Op_VDF_Elem.cpp.
{ /* Do nothing */ }
Referenced by Op_Diff_VDF_Elem_base::modifier_pour_Cl(), Op_Dift_VDF_Elem_base::modifier_pour_Cl(), and Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_elem().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Divers/Op_VDF_Elem.h
src/VDF/Operateurs/Op_Divers/Op_VDF_Elem.cpp