TRUST: Traitement_particulier_Solide_canal_VDF Class Reference
Traitement_particulier_Solide_canal_VDF Class Reference
classe Traitement_particulier_Solide_canal_VDF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan dans le cas d'un calcul Thermohydraulique
avec couplage avec le Solide ou l'on cherche a faire des statistiques
sur le champs de temperature solide (moyenne, ecart-types...)
#include <Traitement_particulier_Solide_canal_VDF.h>
Public Member Functions
Traitement_particulier_Solide_canal_VDF ()
~Traitement_particulier_Solide_canal_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (Entree &) override
void ecriture_fichier_moy_spat_thermo (const DoubleVect &, const DoubleVect &, const DoubleVect &)
void ecriture_fichier_moy_temp_thermo (const DoubleVect &, const DoubleVect &, const DoubleVect &, const double)
void calculer_moyennes_spatiales_thermo (DoubleVect &tmoy, DoubleVect &trms, const DoubleVect &Y, IntVect &corresp, IntVect &compt)
void post_traitement_particulier () override
void calculer_integrales_temporelles (DoubleVect &moy_temp, const DoubleVect &moy_spat)
void init_calcul_moyenne (void) override
void init_calcul_stats (void)
Public Member Functions inherited from Traitement_particulier_Solide_canal
Traitement_particulier_Solide_canal ()
~Traitement_particulier_Solide_canal () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void preparer_calcul_particulier (void) override
void post_traitement_particulier (void) override=0
Entree & lire (Entree &) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_Solide_base
Traitement_particulier_Solide_base ()
~Traitement_particulier_Solide_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_Solide_canal_VDF & self_cast (Objet_U &)
static const Traitement_particulier_Solide_canal_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_Solide_canal
static const Type_info * info ()
static Traitement_particulier_Solide_canal & self_cast (Objet_U &)
static const Traitement_particulier_Solide_canal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_Solide_base
static const Type_info * info ()
static Traitement_particulier_Solide_base & self_cast (Objet_U &)
static const Traitement_particulier_Solide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_Solide_canal
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_Solide_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Traitement_particulier_Solide_canal
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void init_calcul_stats (void)
virtual void init_calcul_moyenne (void)=0
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Traitement_particulier_Solide_canal
DoubleVect Y
DoubleVect Tmoy_temp
DoubleVect T2_moy_temp
IntVect corresp
IntVect compt
double temps_deb
double temps_fin
double dt_post_stat
double dt_post_inst
int N
Protected Attributes inherited from Traitement_particulier_Solide_base
Ref_Conduction mon_equation
Detailed Description
classe Traitement_particulier_Solide_canal_VDF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan dans le cas d'un calcul Thermohydraulique
avec couplage avec le Solide ou l'on cherche a faire des statistiques
sur le champs de temperature solide (moyenne, ecart-types...)
Definition at line 37 of file Traitement_particulier_Solide_canal_VDF.h.
Constructor & Destructor Documentation
Traitement_particulier_Solide_canal_VDF()
Traitement_particulier_Solide_canal_VDF::Traitement_particulier_Solide_canal_VDF ()
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
~Traitement_particulier_Solide_canal_VDF()
Traitement_particulier_Solide_canal_VDF::~Traitement_particulier_Solide_canal_VDF ()
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
Member Function Documentation
calculer_integrales_temporelles()
void Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles (DoubleVect & moy_temp, const DoubleVect & moy_spat)
Definition at line 187 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  double dt_v = mon_equation->schema_temps().pas_de_temps();
  if(je_suis_maitre())
//
    moy_temp.ajoute_sans_ech_esp_virt(dt_v,moy_spat);
}
References TRUSTVect< _TYPE_ >::ajoute_sans_ech_esp_virt(), Process::je_suis_maitre(), Traitement_particulier_Solide_base::mon_equation, Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
Referenced by post_traitement_particulier().
calculer_moyennes_spatiales_thermo()
void Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo (DoubleVect & tmoy, DoubleVect & trms, const DoubleVect & Y, IntVect & corresp, IntVect & compt)
Definition at line 104 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
// Le nombre d'elements de la zone VDF.
  int nb_elems = zone_VDF.zone().nb_elem();
// On veut acceder aux valeurs de la temperature a partir de mon_equation_NRJ.
  const DoubleTab& Temp = mon_equation.valeur().inconnue().valeurs();
// t2moy correspond
  DoubleTrav t2moy(N);
  t2moy = 0.;
  int num_elem,j;
// tmoy est la moyenne de T : <T>(y,t)
  tmoy = 0.;
// trms est l'ecart-type de la temperature : sqrt(<Tp*Tp>)(y,t)=<T*T>-<T*T>
  trms = 0.;
// On parcourt tous les elements pour faire toutes les moyennes au centre des elements.
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
// <T>
      tmoy[tab_corresp[num_elem]] += Temp[num_elem];
// Trms : en fait ici on calcule <T*T> mais ensuite on va soustraire la partie <T*T>
      trms[tab_corresp[num_elem]] += Temp[num_elem]*Temp[num_elem];
    }
// POUR LE PARALLELE !!
  IntVect compt_p(tab_compt);
  envoyer(compt_p,Process::me(),0,Process::me());
  DoubleVect tmoy_p(tmoy);
  envoyer(tmoy_p,Process::me(),0,Process::me());
  DoubleVect trms_p(trms);
  envoyer(trms_p,Process::me(),0,Process::me());
  if(je_suis_maitre())
    {
      IntVect compt_tot(tab_compt);
      DoubleVect tmoy_tot(tmoy);
      DoubleVect trms_tot(trms);
      compt_tot=0;
      tmoy_tot=0.;
      trms_tot=0.;
      for(int p=0; p<Process::nproc(); p++)
        {
          recevoir(compt_p,p,0,p);
          compt_tot+=compt_p;
          recevoir(tmoy_p,p,0,p);
          tmoy_tot+=tmoy_p;
          recevoir(trms_p,p,0,p);
          trms_tot+=trms_p;
        }
// compt[j] correspond au nombre d'elements qui ont ete utilises pour calculer une meme valeur de temperature moyenne,
// ie le nombre d'elements ayant la meme coordonnee Y.
      for (j=0; j<N; j++)
        {
          tmoy[j] = tmoy_tot[j] / compt_tot[j];
          trms[j] = trms_tot[j] / compt_tot[j];
          trms[j] -= tmoy[j]*tmoy[j];
        }
    }
}
References envoyer(), Conduction::inconnue(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_Solide_base::mon_equation, Traitement_particulier_Solide_canal::N, Zone::nb_elem(), Process::nproc(), recevoir(), ref_cast, Ref_Conduction::valeur(), Champ_Inc::valeurs(), Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
Referenced by post_traitement_particulier().
cree_instance()
Objet_U * Traitement_particulier_Solide_canal_VDF::cree_instance () static
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
duplique()
int Traitement_particulier_Solide_canal_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
ecriture_fichier_moy_spat_thermo()
void Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo (const DoubleVect & Tmoy, const DoubleVect & Trms, const DoubleVect & tabY)
Definition at line 201 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  Nom nom_fic = "Solid_spat_";
  double tps = mon_equation->inconnue().temps();
  Nom temps = Nom(tps);
  nom_fic+= temps;
  nom_fic+=".dat";
  if(je_suis_maitre())
    {
      SFichier fic (nom_fic);
      fic << "# Space Averaged Statistics in the Solid" << finl ;
      fic << "# Y     <T>     Trms    " << finl ;
      fic.precision(6);
      for (int j=0; j<N  ; j++)
        fic << tabY[j] << " " << Tmoy[j] << " " << sqrt(Trms[j]) << finl;
      fic.flush();
      fic.close();
    } //!< FIN du maitre
}
References Sortie_Fichier_base::close(), finl, Sortie_Fichier_base::flush(), Conduction::inconnue(), Process::je_suis_maitre(), Traitement_particulier_Solide_base::mon_equation, Traitement_particulier_Solide_canal::N, Sortie_Fichier_base::precision(), and Champ_Inc::temps().
Referenced by post_traitement_particulier().
ecriture_fichier_moy_temp_thermo()
void Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo (const DoubleVect & Tmoy, const DoubleVect & Trms, const DoubleVect & tabY, const double dt)
Definition at line 231 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  Nom nom_fic = "Solid_temp_";
  double tps = mon_equation->inconnue().temps();
  Nom temps = Nom(tps);
  nom_fic+= temps;
  nom_fic+=".dat";
  if(je_suis_maitre())
    {
      SFichier fic (nom_fic);
      fic << "# Time Averaged Statistics in the Solid" << finl ;
      fic << "# Y     <T>     Trms     " << finl ;
      fic.precision(6);
      for (int j=0; j<N  ; j++)
        fic << tabY[j] << " " << Tmoy[j]/dt << " " << sqrt(Trms[j]/dt) << finl;
      fic.flush();
      fic.close();
    } //!< FIN du maitre
}
References Sortie_Fichier_base::close(), finl, Sortie_Fichier_base::flush(), Conduction::inconnue(), Process::je_suis_maitre(), Traitement_particulier_Solide_base::mon_equation, Traitement_particulier_Solide_canal::N, Sortie_Fichier_base::precision(), and Champ_Inc::temps().
Referenced by post_traitement_particulier().
get_info()
const Type_info * Traitement_particulier_Solide_canal_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_Solide_canal.
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
info()
const Type_info * Traitement_particulier_Solide_canal_VDF::info () static
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
init_calcul_moyenne()
void Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne (void) override virtual
< nombre de y pour Temperature
Implements Traitement_particulier_Solide_canal.
Definition at line 267 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VDF& zone_VDF=ref_cast(Zone_VDF, zdisbase);
  const DoubleTab& xp = zone_VDF.xp();
  int nb_elems = zone_VDF.zone().nb_elem();
  int num_elem,j,indic,trouve;
  double y;
  j=0;
  indic = 0;
// dimensionnement aux valeurs rentrees dans le jeu de donnees
  Y.resize(N);
  compt.resize(N);
  corresp.resize(nb_elems);
  Y = -100.;
  compt = 0;
  corresp = -1;
  for (num_elem=0; num_elem<nb_elems; num_elem++)
    {
      y = xp(num_elem,1);
      trouve = 0;
      for (j=0; j<indic+1; j++)
        {
          if(y==Y[j])
            {
              corresp[num_elem] = j;
              compt[j] ++;
              j=indic+1;
              trouve = 1;
              break;
            }
        }
      if (trouve==0)
        {
          corresp[num_elem] = indic;
          Y[indic]=y;
          compt[indic] ++;
          indic++;
        }
    }
  N = indic;  //!< nombre de y pour Temperature
  Y.resize(N);
  compt.resize(N);
}
References Traitement_particulier_Solide_canal::compt, Traitement_particulier_Solide_canal::corresp, Conduction::inconnue(), Traitement_particulier_Solide_base::mon_equation, Traitement_particulier_Solide_canal::N, Zone::nb_elem(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Zone_VF::xp(), Traitement_particulier_Solide_canal::Y, Zone_dis_base::zone(), and Champ_Inc::zone_dis_base().
init_calcul_stats()
void Traitement_particulier_Solide_canal_VDF::init_calcul_stats (void)
Definition at line 257 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  Tmoy_temp.resize(N);
  Tmoy_temp=0;
  T2_moy_temp.resize(N);
  T2_moy_temp=0;
}
References Traitement_particulier_Solide_canal::N, TRUSTVect< _TYPE_ >::resize(), Traitement_particulier_Solide_canal::T2_moy_temp, and Traitement_particulier_Solide_canal::Tmoy_temp.
lire()
Entree & Traitement_particulier_Solide_canal_VDF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_Solide_canal.
Definition at line 38 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  return Traitement_particulier_Solide_canal::lire(is);
}
References Traitement_particulier_Solide_canal::lire().
post_traitement_particulier()
void Traitement_particulier_Solide_canal_VDF::post_traitement_particulier (void) override virtual
Implements Traitement_particulier_Solide_canal.
Definition at line 53 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  DoubleTrav Tmoy(N);
  Tmoy=0.;
  DoubleTrav Trms(N);
  Trms=0.;
  double tps = mon_equation->inconnue().temps();
// Moyennes spatiales :
  calculer_moyennes_spatiales_thermo(Tmoy,Trms,Y,corresp,compt);
  static double temps_dern_post_inst = -100.;
  if (std::fabs(tps-temps_dern_post_inst)>=dt_post_inst)
    {
      ecriture_fichier_moy_spat_thermo(Tmoy,Trms,Y);
      temps_dern_post_inst = tps;
    }
// Moyennes temporelles :
  if ((tps>=temps_deb)&&(tps<=temps_fin))
    {
      static int init_stat_temps = 0;
      if(init_stat_temps==0)
        {
          double dt_v = mon_equation->schema_temps().pas_de_temps();
          temps_deb = tps-dt_v;
          init_stat_temps++;
        }
      calculer_integrales_temporelles(Tmoy_temp,Tmoy);
      calculer_integrales_temporelles(T2_moy_temp,Trms);
      static double temps_dern_post_stat = -100.;
      if (std::fabs(tps-temps_dern_post_stat)>=dt_post_stat)
        {
          double dt = tps-temps_deb;
          ecriture_fichier_moy_temp_thermo(Tmoy_temp,T2_moy_temp,Y,dt);
          temps_dern_post_stat = tps;
        }
    }
}
References calculer_integrales_temporelles(), calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal::compt, Traitement_particulier_Solide_canal::corresp, Traitement_particulier_Solide_canal::dt_post_inst, Traitement_particulier_Solide_canal::dt_post_stat, ecriture_fichier_moy_spat_thermo(), ecriture_fichier_moy_temp_thermo(), Conduction::inconnue(), Traitement_particulier_Solide_base::mon_equation, Traitement_particulier_Solide_canal::N, Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Traitement_particulier_Solide_canal::T2_moy_temp, Champ_Inc::temps(), Traitement_particulier_Solide_canal::temps_deb, Traitement_particulier_Solide_canal::temps_fin, Traitement_particulier_Solide_canal::Tmoy_temp, and Traitement_particulier_Solide_canal::Y.
printOn()
Sortie & Traitement_particulier_Solide_canal_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_Solide_canal.
Definition at line 27 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_Solide_canal_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_Solide_canal.
Definition at line 33 of file Traitement_particulier_Solide_canal_VDF.cpp.
{
  return is;
}
self_cast() [1/2]
const Traitement_particulier_Solide_canal_VDF & Traitement_particulier_Solide_canal_VDF::self_cast (const Objet_U & r) static
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
self_cast() [2/2]
Traitement_particulier_Solide_canal_VDF & Traitement_particulier_Solide_canal_VDF::self_cast (Objet_U & r) static
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
taille_memoire()
unsigned Traitement_particulier_Solide_canal_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 47 of file Traitement_particulier_Solide_canal_VDF.cpp.
Member Data Documentation
info_obj
const Type_info Traitement_particulier_Solide_canal_VDF::info_obj static
Definition at line 39 of file Traitement_particulier_Solide_canal_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Traitement_particulier/Traitement_particulier_Solide_canal_VDF.h
src/VDF/Traitement_particulier/Traitement_particulier_Solide_canal_VDF.cpp