TRUST: Champ_som_lu_VDF Class Reference
Champ_som_lu_VDF Class Reference
#include <Champ_som_lu_VDF.h>
Public Member Functions
Champ_som_lu_VDF ()
~Champ_som_lu_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_base & affecter (const Champ_base &ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
DoubleVect & valeur_a (const DoubleVect &positions, DoubleTab &valeurs) const
Renvoie la valeur en un point.
DoubleVect & valeur_a (const DoubleVect &positions, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
DoubleVect & valeur_a (const DoubleVect &positions, DoubleVect &valeurs, int ncomp) const
DoubleVect & valeur_a (const DoubleVect &positions, DoubleVect &valeurs, int le_poly, int ncomp) const
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_som_lu_VDF & self_cast (Objet_U &)
static const Champ_som_lu_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a:
Champ_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
Simple appel a:
Champ_base::readOn(Entree&)
Detailed Description
Definition at line 37 of file Champ_som_lu_VDF.h.
Constructor & Destructor Documentation
Champ_som_lu_VDF::Champ_som_lu_VDF ()
Definition at line 28 of file Champ_som_lu_VDF.cpp.
Champ_som_lu_VDF::~Champ_som_lu_VDF ()
Definition at line 28 of file Champ_som_lu_VDF.cpp.
Member Function Documentation
Champ_base & Champ_som_lu_VDF::affecter (const Champ_base & ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
Returns:
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 45 of file Champ_som_lu_VDF.cpp.
References Champ_base::affecter_erreur().
{
  Champ_base::affecter_erreur();
  return *this;
}
Objet_U * Champ_som_lu_VDF::cree_instance () [static]
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
int Champ_som_lu_VDF::duplique () const [virtual]
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
const Type_info * Champ_som_lu_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
const Type_info * Champ_som_lu_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
Sortie & Champ_som_lu_VDF::printOn (Sortie & os) const [protected, virtual]
Simple appel a:
Champ_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 30 of file Champ_som_lu_VDF.cpp.
{
  Champ_som_lu::printOn(os);
  return os;
}
Entree & Champ_som_lu_VDF::readOn (Entree & is) [protected, virtual]
Simple appel a:
Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
< nombre de composantes du champ
< tolerance en metres pour la recherche des coordonnees
< nom du fichier a lire
Reimplemented from Champ_som_lu.
Definition at line 36 of file Champ_som_lu_VDF.cpp.
{
  Champ_som_lu::readOn(is);
  return is;
}
Champ_som_lu_VDF & Champ_som_lu_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
const Champ_som_lu_VDF & Champ_som_lu_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
unsigned Champ_som_lu_VDF::taille_memoire () const [virtual]
Reimplemented from Champ_som_lu.
Definition at line 28 of file Champ_som_lu_VDF.cpp.
DoubleVect & Champ_som_lu_VDF::valeur_a (const DoubleVect & positions, DoubleVect & valeurs, int ncomp) const
Reimplemented from Champ_som_lu.
Definition at line 78 of file Champ_som_lu_VDF.cpp.
References Cerr, Process::exit(), finl, and Field_base::nb_compo_.
{
  if (ncomp > nb_compo_)
    {
      Cerr << "Erreur TRUST dans Champ_Don_lu::valeur_a()" << finl;
      Cerr << "l'entier ncomp est superieur au nombre de composantes du champ" << finl;
      exit();
    }
// const DoubleTab& ch = valeurs();
// a coder
  assert(0);
  return val;
}
DoubleVect & Champ_som_lu_VDF::valeur_a (const DoubleVect & positions, DoubleVect & valeurs, int le_poly, int ncomp) const
Reimplemented from Champ_som_lu.
Definition at line 100 of file Champ_som_lu_VDF.cpp.
References valeur_a().
{
// a coder
  assert(0);
  throw;
  return valeur_a(positions, tab_valeurs, le_poly, ncomp);
}
DoubleVect & Champ_som_lu_VDF::valeur_a (const DoubleVect & positions, DoubleTab & valeurs) const
Renvoie la valeur en un point.
Reimplemented from Champ_som_lu.
Definition at line 53 of file Champ_som_lu_VDF.cpp.
References Cerr, Zone::chercher_elements(), finl, Champ_som_lu::mon_domaine, and valeur_aux_elems().
Referenced by valeur_a().
{
  Cerr << "On passe dans Champ_som_lu_VDF::valeur_a(const DoubleVect& positions,DoubleTab& valeurs) " << finl;
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect le_poly(1);
  la_zone.chercher_elements(positions,le_poly);
  DoubleTab positions2;
  positions2=positions;
  return valeur_aux_elems(positions2,le_poly[0],tab_valeurs);
}
DoubleVect & Champ_som_lu_VDF::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const [virtual]
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns:
reference a "valeurs"
Reimplemented from Champ_som_lu.
Definition at line 65 of file Champ_som_lu_VDF.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "On passe dans Champ_som_lu_VDF::valeur_a(const DoubleVect& positions,DoubleVect& valeurs) " << finl;
  assert(0);
  Cerr << "Il ne vaudrait mieux pas appeler Champ_som_lu_VDF::valeur_a avec Valeur DoubleVect" << finl;
  exit();
  return tab_valeurs;
}
DoubleTab & Champ_som_lu_VDF::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const [virtual]
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 112 of file Champ_som_lu_VDF.cpp.
References Zone::chercher_elements(), Champ_som_lu::mon_domaine, Zone::nb_elem(), and valeur_aux_elems().
{
  const Zone& la_zone = mon_domaine->zone(0);
// B.M.: IntVect obligatoire pour l'instant a cause du prototype de valeur_aux_elems
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(positions,les_polys);
  return valeur_aux_elems(positions,les_polys,val);
}
DoubleVect & Champ_som_lu_VDF::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const [virtual]
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns:
reference au tableau les_valeurs
Reimplemented from Champ_som_lu.
Definition at line 125 of file Champ_som_lu_VDF.cpp.
References Cerr, Zone::chercher_elements(), finl, Champ_som_lu::mon_domaine, Zone::nb_elem(), and valeur_aux_elems_compo().
{
  const Zone& la_zone = mon_domaine->zone(0);
// B.M.: IntVect obligatoire pour l'instant a cause du prototype de valeur_aux_elems
  IntVect les_polys(la_zone.nb_elem());
  Cerr << "Nb elem : " << la_zone.nb_elem() << finl;
  Cerr << "Lespolys : " << les_polys.size_array() << finl;
  la_zone.chercher_elements(positions,les_polys);
  Cerr << "Nb elem : " << la_zone.nb_elem() << finl;
  Cerr << "Lespolys : " << les_polys.size_array() << finl;
  return valeur_aux_elems_compo(positions,les_polys,tab_valeurs,ncomp);
}
DoubleTab & Champ_som_lu_VDF::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 143 of file Champ_som_lu_VDF.cpp.
References Cerr, DoubleTab::dimension(), Process::exit(), finl, Champ_som_lu::mon_domaine, Field_base::nb_compo_, DoubleTab::nb_dim(), ArrOfInt::size_array(), Zone::sommet_elem(), and Champ_Don_base::valeurs().
Referenced by valeur_a(), and valeur_aux().
{
  if (val.nb_dim() == 2)
    {
      assert(val.dimension(0) == les_polys.size_array());
      assert(val.dimension(1) == nb_compo_);
    }
  else
    {
      Cerr << "Erreur TRUST dans Champ_som_lu_VDF::valeur_aux_elems()" << finl;
      Cerr << "Le DoubleTab val n'a pas 2 entrees" << finl;
      exit();
    }
  const DoubleTab& coord=mon_domaine->coord_sommets();
  const Zone& zone=mon_domaine->zone(0);
  int le_poly;
  {
    const DoubleTab& ch = valeurs();
    for(int rang_poly=0; rang_poly<les_polys.size_array(); rang_poly++)
      {
        le_poly=les_polys(rang_poly);
        if (le_poly == -1)
          for(int ncomp=0; ncomp<nb_compo_; ncomp++)
            val(rang_poly, ncomp) = 0;
        else
          {
            for(int ncomp=0; ncomp<nb_compo_; ncomp++)
              {
                int som1=zone.sommet_elem(le_poly , 0 );
                int som2=zone.sommet_elem(le_poly , 1 );
                int som3=zone.sommet_elem(le_poly , 2 );
                int som4=zone.sommet_elem(le_poly , 3 );
                int som5=zone.sommet_elem(le_poly , 4 );
                int som6=zone.sommet_elem(le_poly , 5 );
                int som7=zone.sommet_elem(le_poly , 6 );
                int som8=zone.sommet_elem(le_poly , 7 );
                double xmin=coord(som1,0);
                double xmax=coord(som2,0);
                double ymin=coord(som1,1);
                double ymax=coord(som3,1);
                double zmin=coord(som1,2);
                double zmax=coord(som5,2);
                double hx=xmax - xmin;
                double hy=ymax - ymin;
                double hh=zmax - zmin;
                val(rang_poly, ncomp) =
                  ch(som1,ncomp)*(xmax-positions(rang_poly,0))
                  *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) +=ch(som2,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) +=ch(som3,ncomp)*(xmax-positions(rang_poly,0))
                                        *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) +=ch(som4,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
                val(rang_poly, ncomp) += ch(som5,ncomp)*(xmax-positions(rang_poly,0))
                                         *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp) +=ch(som6,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp) +=ch(som7,ncomp)*(xmax-positions(rang_poly,0))
                                        *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp) +=ch(som8,ncomp)*(positions(rang_poly,0)-xmin)
                                        *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
                val(rang_poly, ncomp)/=(hx*hy*hh);
              }
          }
      }
  }
  return val;
}
DoubleVect & Champ_som_lu_VDF::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_som_lu.
Definition at line 234 of file Champ_som_lu_VDF.cpp.
References Champ_som_lu::mon_domaine, DoubleVect::size(), ArrOfInt::size_array(), Zone::sommet_elem(), and Champ_Don_base::valeurs().
Referenced by valeur_aux_compo().
{
  assert(val.size() == les_polys.size_array());
  const DoubleTab& coord=mon_domaine->coord_sommets();
  const Zone& zone=mon_domaine->zone(0);
  int le_poly;
  const DoubleTab& ch = valeurs();
  for(int rang_poly=0; rang_poly<les_polys.size_array(); rang_poly++)
    {
      le_poly=les_polys(rang_poly);
      if (le_poly == -1)
        val(rang_poly) = 0;
      else
        {
          int som1=zone.sommet_elem(le_poly , 0 );
          int som2=zone.sommet_elem(le_poly , 1 );
          int som3=zone.sommet_elem(le_poly , 2 );
          int som4=zone.sommet_elem(le_poly , 3 );
          int som5=zone.sommet_elem(le_poly , 4 );
          int som6=zone.sommet_elem(le_poly , 5 );
          int som7=zone.sommet_elem(le_poly , 6 );
          int som8=zone.sommet_elem(le_poly , 7 );
          double xmin=coord(som1,0);
          double xmax=coord(som2,0);
          double ymin=coord(som1,1);
          double ymax=coord(som3,1);
          double zmin=coord(som1,2);
          double zmax=coord(som5,2);
          double hx=xmax - xmin;
          double hy=ymax - ymin;
          double hh=zmax - zmin;
          val(rang_poly) =
            ch(som1,ncomp)*(xmax-positions(rang_poly,0))
            *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
          val(rang_poly) +=ch(som2,ncomp)*(positions(rang_poly,0)-xmin)
                           *(ymax-positions(rang_poly,1))*(zmax-positions(rang_poly,2));
          val(rang_poly) +=ch(som3,ncomp)*(xmax-positions(rang_poly,0))
                           *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
          val(rang_poly) +=ch(som4,ncomp)*(positions(rang_poly,0)-xmin)
                           *(positions(rang_poly,1)-ymin)*(zmax-positions(rang_poly,2));
          val(rang_poly) += ch(som5,ncomp)*(xmax-positions(rang_poly,0))
                            *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
          val(rang_poly) +=ch(som6,ncomp)*(positions(rang_poly,0)-xmin)
                           *(ymax-positions(rang_poly,1))*(positions(rang_poly,2)-zmin);
          val(rang_poly) +=ch(som7,ncomp)*(xmax-positions(rang_poly,0))
                           *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
          val(rang_poly) +=ch(som8,ncomp)*(positions(rang_poly,0)-xmin)
                           *(positions(rang_poly,1)-ymin)*(positions(rang_poly,2)-zmin);
          val(rang_poly)/=(hx*hy*hh);
        }
    }
  return val;
}
Member Data Documentation
const Type_info Champ_som_lu_VDF::info_obj [static]
Reimplemented from Champ_som_lu.
Definition at line 39 of file Champ_som_lu_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_som_lu_VDF.h
src/VDF/Champs/Champ_som_lu_VDF.cpp