TRUST: Ref_Zone_VDF Class Reference
Ref_Zone_VDF Class Reference
#include <Ref_Zone_VDF.h>
Public Member Functions
~Ref_Zone_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_VDF ()
Ref_Zone_VDF (const Zone_VDF &)
Ref_Zone_VDF (const Ref_Zone_VDF &)
const Zone_VDF & valeur () const
Zone_VDF & valeur ()
const Zone_VDF * operator-> () const
Zone_VDF * operator-> ()
const Ref_Zone_VDF & operator= (const Zone_VDF &)
const Ref_Zone_VDF & operator= (const Ref_Zone_VDF &)
operator const Zone_VDF & () const
operator Zone_VDF & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_VDF & self_cast (Objet_U &)
static const Ref_Zone_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_VDF * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_VDF.h.
Constructor & Destructor Documentation
Ref_Zone_VDF::~Ref_Zone_VDF ()
Definition at line 25 of file Ref_Zone_VDF.cpp.
Ref_Zone_VDF::Ref_Zone_VDF ()
Definition at line 25 of file Ref_Zone_VDF.cpp.
Ref_Zone_VDF::Ref_Zone_VDF (const Zone_VDF & t)
Definition at line 25 of file Ref_Zone_VDF.cpp.
Ref_Zone_VDF::Ref_Zone_VDF (const Ref_Zone_VDF & t)
Definition at line 25 of file Ref_Zone_VDF.cpp.
Member Function Documentation
Objet_U * Ref_Zone_VDF::cree_instance () [static]
Definition at line 25 of file Ref_Zone_VDF.cpp.
int Ref_Zone_VDF::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Type_info * Ref_Zone_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Type_info & Ref_Zone_VDF::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Type_info * Ref_Zone_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
Ref_Zone_VDF::operator const Zone_VDF & () const
Definition at line 25 of file Ref_Zone_VDF.cpp.
Ref_Zone_VDF::operator Zone_VDF & ()
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Zone_VDF * Ref_Zone_VDF::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_VDF.h.
Zone_VDF * Ref_Zone_VDF::operator-> () [inline]
Definition at line 28 of file Ref_Zone_VDF.h.
const Ref_Zone_VDF & Ref_Zone_VDF::operator= (const Ref_Zone_VDF & t)
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Ref_Zone_VDF & Ref_Zone_VDF::operator= (const Zone_VDF & t)
Definition at line 25 of file Ref_Zone_VDF.cpp.
Sortie & Ref_Zone_VDF::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
Entree & Ref_Zone_VDF::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Ref_Zone_VDF & Ref_Zone_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
Ref_Zone_VDF & Ref_Zone_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VDF.cpp.
void Ref_Zone_VDF::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_VDF.cpp.
unsigned Ref_Zone_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_VDF.cpp.
const Zone_VDF & Ref_Zone_VDF::valeur () const [inline]
Definition at line 28 of file Ref_Zone_VDF.h.
Referenced by Champ_Face::affecter(), Champ_Fonc_Face::affecter_(), Champ_Face::affecter_(), Terme_Source_Qdm_VDF_Face::ajouter(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), Terme_Source_Coriolis_VDF_Face::ajouter(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter(), Terme_Source_Canal_perio_VDF_P0::ajouter(), Terme_Source_Canal_perio_VDF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter(), Terme_Boussinesq_VDF_Face::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Diff_VDF_var_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter(), Op_Grad_VDF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter(), Force_Centrifuge_VDF_Face_Axi::ajouter(), Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Op_Diff_VDF_Face_Axi::ajouter_bord(), Op_Dift_VDF_var_Face_Axi::ajouter_contribution(), Op_Dift_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_var_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution_bord(), Masse_VDF_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_VDF::assembler(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_VDF::assembler_rho_variable(), Eval_Darcy_VDF_Face::associer(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Champ_Face::calcul_critere_Q(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_grad_u(), Champ_Face::calcul_S_barre(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calcul_y_plus(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Champ_Face::calculer_dercov_axi(), Champ_Face::calculer_dscald_centre_element(), Op_Dift_VDF_var_Face_Axi::calculer_dt_stab(), Op_Dift_VDF_Face_Axi::calculer_dt_stab(), Op_Diff_VDF_var_Face_Axi::calculer_dt_stab(), Op_Diff_VDF_Face_Axi::calculer_dt_stab(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Champ_Face::calculer_rotationnel_ordre2_centre_element(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Champ_Face::compo_normale_sortante(), Assembleur_P_VDF::construire(), Op_Dift_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::contribuer_a_avec(), Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec(), Op_Grad_VDF_Face::contribuer_a_avec(), Op_Grad_VDF_Face::dimensionner(), Op_Grad_VDF_Face::impr(), Champ_P0_VDF::integrale_espace(), Assembleur_P_VDF::liste_faces_periodiques(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Eval_Dirac_VDF_Elem::mettre_a_jour(), Eval_Darcy_VDF_Face::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Op_Dift_VDF_var_Face_Axi::modifier_pour_Cl(), Op_Dift_VDF_Face_Axi::modifier_pour_Cl(), Op_Diff_VDF_var_Face_Axi::modifier_pour_Cl(), Op_Diff_VDF_Face_Axi::modifier_pour_Cl(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Assembleur_P_VDF::modifier_solution(), Terme_Source_Canal_RANS_LES_VDF_Face::moy_spat(), Champ_P0_VDF::moyenne(), Champ_Fonc_P0_VDF::moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::norme_vit(), Assembleur_P_VDF::remplir(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Champ_P0_VDF::valeur_au_bord(), Champ_Fonc_P0_VDF::valeur_au_bord(), Op_Div_VDF_Elem::volumique(), Iterateur_VDF_base::zone(), Assembleur_P_VDF_Q4::zone_dis_base(), Assembleur_P_VDF::zone_dis_base(), Champ_P0_VDF::zone_dis_base(), Champ_Ostwald_VDF::zone_dis_base(), Champ_Fonc_P1_VDF::zone_dis_base(), Champ_Fonc_P0_VDF::zone_dis_base(), Champ_Fonc_Face::zone_dis_base(), Champ_Face::zone_dis_base(), Op_Grad_VDF_Face::zone_VDF(), Op_Grad_P0_to_Face::zone_VDF(), Faces_VDF::zone_VDF(), and Champ_Face::zone_vdf().
Zone_VDF & Ref_Zone_VDF::valeur () [inline]
Definition at line 28 of file Ref_Zone_VDF.h.
Member Data Documentation
const Type_info Ref_Zone_VDF::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_VDF.h.
Zone_VDF* Ref_Zone_VDF::pointeur_ [private]
Definition at line 28 of file Ref_Zone_VDF.h.
The documentation for this class was generated from the following files:
src/VDF/Zones/Ref_Zone_VDF.h
src/VDF/Zones/Ref_Zone_VDF.cpp