TRUST: Octree_Int Class Reference
Octree_Int Class Reference
: Un octree permettant de retrouver des objets ponctuels ou
parallelipipediques dans un espace 1D, 2D ou 3D et des coordonnees entieres
#include <Octree_Int.h>
Public Member Functions
void build (const int dimension, const IntTab &elements_boxes)
construction de l'octree. On donne la dimension (1, 2 ou 3)
et un tableau d'elements a stocker dans l'octree. Deux possibilites:
1) les elements sont ponctuels si elements_boxes.dimension(1) == dimension.
Dans ce cas, chaque element se trouve dans un et un seul octree_floor
2) les elements sont des parallelipipedes, si elements_boxes.dimension(1) == dimension*2
Les "dimension" premieres colonnes sont les coordonnees inferieures,
les "dimension" suivantes sont les coordonnees superieures.
Un parallelipipede peut etre affecte a plusieurs octree_floor.
Les coordonnees stockees dans elements_boxes peuvent aller de 0 a coord_max_ inclus.
Il vaut mieux utiliser toute la plage des entiers en multipliant par un facteur adequat.
int search_elements (int x, int y, int z, int &floor_elements_index) const
renvoie la liste des elements contenant potentiellement le point (x,y,z)
On renvoie n=nombre d'elements de la liste et les elements sont dans
floor_elements()[index+i] pour 0 <= i < n.
En realite on renvoie tous les elements qui ont une intersection non vide avec l'octree_floor
contenant le point (x,y,z)
int search_elements_box (int xmin, int ymin, int zmin, int xmax, int ymax, int zmax, ArrOfInt &elements) const
cherche les elements ayant potentiellement une intersection non vide avec la
boite xmin..zmax. Le tableau elements doit etre de type smart_resize(1).
Les elements peuvent apparaitre plusieurs fois dans le tableau "elements"
void reset ()
const ArrOfInt & floor_elements () const
Static Public Attributes
static const int coord_max_ = 2147483647
static const int root_octree_half_width_ = 1073741824
Protected Types
enum Octree_Type { EMPTY , OCTREE , FLOOR }
Protected Member Functions
int build_octree_recursively (const int octree_center_x, const int octree_center_y, const int octree_center_z, const int octree_half_width, const IntTab &elements_boxes, ArrsOfInt &vect_elements_list, const int level, ArrsOfInt &tmp_elem_flags)
octree_center_i est le premier int de la moitie superieure de l'octree dans la direction i.
octree_half_width est une puissance de 2 egale a octree_center_i-octree_min_i (octree_min_i
est le premier int inclu dans cet octree dans la direction i)
Valeur de retour: octree_id de l'octree construit (void octree_structure_)
int build_octree_floor (const ArrOfInt &elements_list)
construit un octree_floor avec la liste d'elements donnee et
renvoie l'octree_id de cet octree_floor
int search_octree_floor (int x_pos, int y_pos, int z_pos) const
renvoie l'octree_id de l'octree_floor contenant le sommet (x,y,z)
(peut renvoyer l'octree EMPTY)
void search_elements_box_floor (IntBoxData &boxdata, int octree_floor_id) const
ajoute des elements de l'octree_floor a boxdata.elements_
void search_elements_box_recursively (IntBoxData &boxdata, int octree_id, int cx, int cy, int cz, int half_width) const
cherche recursivement les elements inclus dans la boite
boxdata pour l'octree_id donne, de centre cx, cy, cz.
Static Protected Member Functions
static int octree_id (int index, Octree_Type type)
construction d'un octree_id (voir octree_structure_)
Si type==EMPTY, on l'octree_id est 0
Si type==OCTREE, on suppose que index est un indice dans octree_structure_
Si type==FLOOR, on suppose que index est un indice dans floor_elements_
static int octree_index (int octree_id, Octree_Type type)
calcul de l'index de l'octree dans octree_structure ou floor_elements
en fonction du type de l'octree et de son octree_id.
En general on a deja determine le type avant, on le passe en parametre pour optimiser.
static Octree_Type octree_type (int octree_id)
Renvoie le type d'un octree en fonction de son octree_id.
Protected Attributes
int root_octree_id_
int nb_elements_
IntTab octree_structure_
ArrOfInt floor_elements_
Detailed Description
: Un octree permettant de retrouver des objets ponctuels ou
parallelipipediques dans un espace 1D, 2D ou 3D et des coordonnees entieres
Definition at line 26 of file Octree_Int.h.
Member Enumeration Documentation
Octree_Type
enum Octree_Int::Octree_Type protected
Enumerator
EMPTY
OCTREE
FLOOR
Definition at line 54 of file Octree_Int.h.
{ EMPTY, OCTREE, FLOOR };
Member Function Documentation
build()
void Octree_Int::build (const int dimension, const IntTab & elements_boxes)
construction de l'octree. On donne la dimension (1, 2 ou 3)
et un tableau d'elements a stocker dans l'octree. Deux possibilites:
1) les elements sont ponctuels si elements_boxes.dimension(1) == dimension.
Dans ce cas, chaque element se trouve dans un et un seul octree_floor
2) les elements sont des parallelipipedes, si elements_boxes.dimension(1) == dimension*2
Les "dimension" premieres colonnes sont les coordonnees inferieures,
les "dimension" suivantes sont les coordonnees superieures.
Un parallelipipede peut etre affecte a plusieurs octree_floor.
Les coordonnees stockees dans elements_boxes peuvent aller de 0 a coord_max_ inclus.
Il vaut mieux utiliser toute la plage des entiers en multipliant par un facteur adequat.
Definition at line 81 of file Octree_Int.cpp.
{
  assert(dimension >= 1 && dimension <= 3);
  assert(elements_boxes.dimension(1) == dimension
         || elements_boxes.dimension(1) == dimension * 2 );
  const int nb_elems = elements_boxes.dimension(0);
  nb_elements_ = nb_elems;
  octree_structure_.set_smart_resize(1);
  floor_elements_.set_smart_resize(1);
  floor_elements_.resize_array(0);
  const int nb_octrees = 1 << dimension;
  octree_structure_.resize(0, nb_octrees);
  assert(elements_boxes.size_array() == 0
         || (min_array(elements_boxes) >= 0 && max_array(elements_boxes) <= coord_max_));
  ArrsOfInt tmp_elem_flags(max_levels_);
  ArrsOfInt tmp_elem_list(max_levels_);
  for (int i = 0; i < max_levels_; i++)
    {
      tmp_elem_flags[i].set_smart_resize(1);
      tmp_elem_list[i].set_smart_resize(1);
    }
  ArrOfInt& elements_list = tmp_elem_list[0];
  elements_list.resize_array(nb_elems, ArrOfInt::NOCOPY_NOINIT);
  for (int i = 0; i < nb_elems; i++)
    elements_list[i] = i;
  root_octree_id_ = build_octree_recursively(root_octree_half_width_,root_octree_half_width_,root_octree_half_width_,
                                             root_octree_half_width_,
                                             elements_boxes,
                                             tmp_elem_list,
                                             0,
                                             tmp_elem_flags);
}
References build_octree_recursively(), coord_max_, TRUSTTab< _TYPE_ >::dimension(), floor_elements_, max_array(), max_levels_, min_array(), nb_elements_, Array_base::NOCOPY_NOINIT, octree_structure_, TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), root_octree_half_width_, root_octree_id_, TRUSTArray< _TYPE_ >::set_smart_resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Octree_Double::build_elements(), and Octree_Double::build_nodes().
build_octree_floor()
int Octree_Int::build_octree_floor (const ArrOfInt & elements_list) protected
construit un octree_floor avec la liste d'elements donnee et
renvoie l'octree_id de cet octree_floor
Definition at line 293 of file Octree_Int.cpp.
{
  const int nb_elems = elements_list.size_array();
  const int index = floor_elements_.size_array();
  floor_elements_.resize_array(index + nb_elems + 1, ArrOfInt::COPY_NOINIT);
  floor_elements_[index] = nb_elems;
  for (int i = 0; i < nb_elems; i++)
    floor_elements_[index + 1 + i] = elements_list[i];
  return octree_id(index, FLOOR);
}
References Array_base::COPY_NOINIT, FLOOR, floor_elements_, octree_id(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by build_octree_recursively().
build_octree_recursively()
int Octree_Int::build_octree_recursively (const int octree_center_x, const int octree_center_y, const int octree_center_z, const int octree_half_width, const IntTab & elements_boxes, ArrsOfInt & vect_elements_list, const int level, ArrsOfInt & tmp_elem_flags) protected
octree_center_i est le premier int de la moitie superieure de l'octree dans la direction i.
octree_half_width est une puissance de 2 egale a octree_center_i-octree_min_i (octree_min_i
est le premier int inclu dans cet octree dans la direction i)
Valeur de retour: octree_id de l'octree construit (void octree_structure_)
< non -> on retire les flags des cubes de la partie inferieure
< non -> on retire les flags des cubes de la partie superieure
< l'element coupe les deux parties !
Definition at line 309 of file Octree_Int.cpp.
{
// Criteres d'arret de la subdivision:
// Nombre maximal d'elements dans un sous-cube floor
  static const int octree_floor_max_elems = 8;
// S'il y a beaucoup d'elements dupliques, mais pas trop, et que le nombre d'elements
// dans l'octree est superieur a cette valeur, on subdivise quand-meme
  static const int octree_duplicate_elements_limit = 64;
  const ArrOfInt& elements_list = vect_elements_list[level];
// Si le nombre d'elements est inferieur a la limite, on cree un floor_element,
// sinon on subdivise
  const int nb_elems = elements_list.size_array();
  if (nb_elems == 0)
    return octree_id(0, EMPTY);
  if (nb_elems < octree_floor_max_elems || octree_half_width == 1 /* dernier niveau */)
    {
      const int the_octree_id = build_octree_floor(elements_list);
      return the_octree_id;
    }
  ArrOfInt& elem_flags = tmp_elem_flags[level];
  elem_flags.resize_array(nb_elems, ArrOfInt::NOCOPY_NOINIT);
  const int nb_octrees = octree_structure_.dimension(1);
  assert(nb_octrees == 2 || nb_octrees == 4 || nb_octrees == 8);
  const int elem_box_dim = elements_boxes.dimension(1);
// Soit elements_boxes contient dimension colonnes, soit dimension*2
  const int box_delta = (elem_box_dim > 3) ? (elem_box_dim >> 1) : 0;
// Nombre d'elements stockes en double dans l'octree (a cause des elements a cheval
// sur plusieurs sous-octrees)
  int nb_duplicate_elements = 0;
// On range les elements de la liste dans 8 sous-cubes (remplissage de elem_flags)
  for (int i_elem = 0; i_elem < nb_elems; i_elem++)
    {
      const int elem = elements_list[i_elem];
// dir_flag vaut 1 pour la direction x, 2 pour y et 4 pour z
      int dir_flag = 1;
// sub_cube_flags contient 2^dim drapeaux binaires (1 par sous-cube),
// et indique les sous-cubes coupes par l'element
      int octree_flags = 255;
// dans combien de sous-octree cet element est-il stocke ?
      int nb_duplicates = 1;
      for (int direction = 0; direction < 3; direction++)
        {
          const int elem_min = elements_boxes(elem, direction);
          const int elem_max = elements_boxes(elem, box_delta+direction);
          assert(elem_max >= elem_min);
// coordonnee du centre du cube dans la direction j:
          const int center = (direction==0) ? octree_center_x : ((direction==1) ? octree_center_y : octree_center_z);
// L'element coupe-t-il la partie inferieure et la partie superieure du cube dans la "direction" ?
          if (elem_min >= center) //!< non -> on retire les flags des cubes de la partie inferieure
            octree_flags &= sub_cube_flags_max[direction];
          else if (elem_max < center) //!< non -> on retire les flags des cubes de la partie superieure
            octree_flags &= sub_cube_flags_min[direction];
          else
            nb_duplicates <<= 1; //!< l'element coupe les deux parties !
          dir_flag = dir_flag << 1;
          if (dir_flag == nb_octrees)
            break;
        }
      elem_flags[i_elem] = octree_flags;
      nb_duplicate_elements += nb_duplicates - 1;
    }
// Critere un peu complique : s'il y a vraiment beaucoup d'elements
// dans cet octree, on autorise jusqu'a dupliquer tous les elements,
// ce qui permet de ranger des elements tres alonges qui sont forcement
// dupliques dans une direction (>octree_duplicate_elements_limit).
  if ((nb_duplicate_elements * 2 >= nb_elems && nb_elems < octree_duplicate_elements_limit)
      || nb_duplicate_elements > nb_elems)
    {
      const int the_octree_id = build_octree_floor(elements_list);
// On renvoie un index d'octreefloor
      return the_octree_id;
    }
// On reserve une case a la fin de octree_structure pour stocker cet octree:
  const int index_octree = octree_structure_.dimension(0);
  octree_structure_.resize_dim0(index_octree + 1, ArrOfInt::COPY_NOINIT);
  ArrOfInt& new_liste_elems = vect_elements_list[level+1];
  new_liste_elems.resize_array(0);
  const int width = octree_half_width >> 1;
  const int m_width = - width;
// Traitement recursif des sous-cubes de l'octree:
  int i_cube;
  for (i_cube = 0; i_cube < nb_octrees; i_cube++)
    {
      const int octree_flag = 1 << i_cube;
      new_liste_elems.resize_array(nb_elems, ArrOfInt::NOCOPY_NOINIT);
      int count = 0;
// Liste des elements inclus dans le sous-cube:
      for (int i_elem = 0; i_elem < nb_elems; i_elem++)
        if ((elem_flags[i_elem] & octree_flag) != 0)
          new_liste_elems[count++] = elements_list[i_elem];
      new_liste_elems.resize_array(count);
      int sub_octree_id;
      if (new_liste_elems.size_array() == 0)
        {
          sub_octree_id = octree_id(-1, EMPTY);
        }
      else
        {
// Coordonnees du nouveau sous-cube
          const int cx = octree_center_x + ((i_cube&1) ? width : m_width);
          const int cy = octree_center_y + ((i_cube&2) ? width : m_width);
          const int cz = octree_center_z + ((i_cube&4) ? width : m_width);
          sub_octree_id = build_octree_recursively(cx, cy, cz, width,
                                                   elements_boxes,
                                                   vect_elements_list,
                                                   level+1,
                                                   tmp_elem_flags);
        }
      octree_structure_(index_octree, i_cube) = sub_octree_id;
    }
  return octree_id(index_octree, OCTREE);
}
References build_octree_floor(), build_octree_recursively(), Array_base::COPY_NOINIT, TRUSTTab< _TYPE_ >::dimension(), EMPTY, Array_base::NOCOPY_NOINIT, OCTREE, octree_id(), octree_structure_, TRUSTArray< _TYPE_ >::resize_array(), TRUSTTab< _TYPE_ >::resize_dim0(), TRUSTArray< _TYPE_ >::size_array(), sub_cube_flags_max, and sub_cube_flags_min.
Referenced by build(), and build_octree_recursively().
floor_elements()
const ArrOfInt & Octree_Int::floor_elements () const inline
Definition at line 34 of file Octree_Int.h.
{ return floor_elements_; }
References floor_elements_.
Referenced by Octree_Double::floor_elements().
octree_id()
int Octree_Int::octree_id (int index, Octree_Type type) inline static protected
construction d'un octree_id (voir octree_structure_)
Si type==EMPTY, on l'octree_id est 0
Si type==OCTREE, on suppose que index est un indice dans octree_structure_
Si type==FLOOR, on suppose que index est un indice dans floor_elements_
Definition at line 28 of file Octree_Int.cpp.
{
  switch(type)
    {
    case EMPTY:
      return 0;
    case OCTREE:
      return index + 1;
    case FLOOR:
      return - index - 1;
    }
  return -1;
}
References EMPTY, FLOOR, and OCTREE.
Referenced by build_octree_floor(), build_octree_recursively(), octree_index(), octree_type(), and reset().
octree_index()
int Octree_Int::octree_index (int octree_id, Octree_Type type) inline static protected
calcul de l'index de l'octree dans octree_structure ou floor_elements
en fonction du type de l'octree et de son octree_id.
En general on a deja determine le type avant, on le passe en parametre pour optimiser.
Definition at line 45 of file Octree_Int.cpp.
{
  assert(type==octree_type(octree_id));
  switch(type)
    {
    case EMPTY:
      return -1;
    case OCTREE:
      return octree_id - 1;
    case FLOOR:
      return - octree_id - 1;
    }
  return -1;
}
References EMPTY, FLOOR, OCTREE, octree_id(), and octree_type().
Referenced by search_elements(), search_elements_box_floor(), search_elements_box_recursively(), and search_octree_floor().
octree_type()
Octree_Int::Octree_Type Octree_Int::octree_type (int octree_id) inline static protected
Renvoie le type d'un octree en fonction de son octree_id.
Definition at line 61 of file Octree_Int.cpp.
{
  if (octree_id > 0)
    return OCTREE;
  else if (octree_id == 0)
    return EMPTY;
  else
    return FLOOR;
}
References EMPTY, FLOOR, OCTREE, and octree_id().
Referenced by octree_index(), search_elements(), search_elements_box(), search_elements_box_recursively(), and search_octree_floor().
reset()
void Octree_Int::reset ()
Definition at line 283 of file Octree_Int.cpp.
{
  root_octree_id_ = octree_id(0, EMPTY);
  nb_elements_ = 0;
  octree_structure_.reset();
  floor_elements_.reset();
}
References EMPTY, floor_elements_, nb_elements_, octree_id(), octree_structure_, TRUSTArray< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::reset(), and root_octree_id_.
Referenced by Octree_Double::build_elements(), Octree_Double::build_nodes(), and Octree_Double::reset().
search_elements()
int Octree_Int::search_elements (int x, int y, int z, int & floor_elements_index) const
renvoie la liste des elements contenant potentiellement le point (x,y,z)
On renvoie n=nombre d'elements de la liste et les elements sont dans
floor_elements()[index+i] pour 0 <= i < n.
En realite on renvoie tous les elements qui ont une intersection non vide avec l'octree_floor
contenant le point (x,y,z)
< important pour ne pas tomber sur des cubes inexistants
< idem
Definition at line 124 of file Octree_Int.cpp.
{
  const int nb_octrees = octree_structure_.dimension(1);
  if (nb_octrees == 2)
    y = 0; //!< important pour ne pas tomber sur des cubes inexistants
  if (nb_octrees <= 4)
    z = 0; //!< idem
  assert(x >= 0 && x <= coord_max_);
  assert(y >= 0 && y <= coord_max_);
  assert(z >= 0 && z <= coord_max_);
  const int my_octree_id = search_octree_floor(x, y, z);
  if (octree_type(my_octree_id) == EMPTY)
    {
      return 0;
    }
  const int idx = octree_index(my_octree_id, FLOOR);
  const int n = floor_elements_[idx];
  index = idx + 1;
  return n;
}
References coord_max_, TRUSTTab< _TYPE_ >::dimension(), EMPTY, FLOOR, floor_elements_, octree_index(), octree_structure_, octree_type(), and search_octree_floor().
Referenced by Octree_Double::search_elements().
search_elements_box()
int Octree_Int::search_elements_box (int xmin, int ymin, int zmin, int xmax, int ymax, int zmax, ArrOfInt & elements) const
cherche les elements ayant potentiellement une intersection non vide avec la
boite xmin..zmax. Le tableau elements doit etre de type smart_resize(1).
Les elements peuvent apparaitre plusieurs fois dans le tableau "elements"
< important pour ne pas tomber sur des cubes inexistants
< idem
Definition at line 166 of file Octree_Int.cpp.
{
  const int nb_octrees = octree_structure_.dimension(1);
  if (nb_octrees == 2)
    ymin = ymax = 0; //!< important pour ne pas tomber sur des cubes inexistants
  if (nb_octrees <= 4)
    zmin = zmax = 0; //!< idem
  assert(xmin >= 0 && xmin <= coord_max_);
  assert(ymin >= 0 && ymin <= coord_max_);
  assert(zmin >= 0 && zmin <= coord_max_);
  assert(xmax >= 0 && xmax <= coord_max_);
  assert(ymax >= 0 && ymax <= coord_max_);
  assert(zmax >= 0 && zmax <= coord_max_);
  elements.resize_array(0);
  IntBoxData boxdata(xmin, ymin, zmin, xmax, ymax, zmax, elements, 0);
  switch(octree_type(root_octree_id_))
    {
    case FLOOR:
      search_elements_box_floor(boxdata, root_octree_id_);
      break;
    case OCTREE:
      search_elements_box_recursively(boxdata, root_octree_id_,
                                      root_octree_half_width_,root_octree_half_width_,root_octree_half_width_,
                                      root_octree_half_width_);
      break;
    case EMPTY:
      break;
    }
  const int n = elements.size_array();
  return n;
}
References coord_max_, TRUSTTab< _TYPE_ >::dimension(), EMPTY, FLOOR, OCTREE, octree_structure_, octree_type(), TRUSTArray< _TYPE_ >::resize_array(), root_octree_half_width_, root_octree_id_, search_elements_box_floor(), search_elements_box_recursively(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Octree_Double::search_elements_box().
search_elements_box_floor()
void Octree_Int::search_elements_box_floor (IntBoxData & boxdata, int octree_floor_id) const protected
ajoute des elements de l'octree_floor a boxdata.elements_
Definition at line 202 of file Octree_Int.cpp.
{
  const int idx = octree_index(octree_floor_id, FLOOR);
  const int n = floor_elements_[idx];
  if (boxdata.markers_)
    for (int i = 0; i < n; i++)
      {
        const int elem = floor_elements_[idx+1+i];
        if (!boxdata.markers_->testsetbit(elem))
          boxdata.elements_.append_array(elem);
      }
  else
    for (int i = 0; i < n; i++)
      {
        const int elem = floor_elements_[idx+1+i];
        boxdata.elements_.append_array(elem);
      }
}
References TRUSTArray< _TYPE_ >::append_array(), IntBoxData::elements_, FLOOR, floor_elements_, IntBoxData::markers_, octree_index(), and ArrOfBit::testsetbit().
Referenced by search_elements_box(), and search_elements_box_recursively().
search_elements_box_recursively()
void Octree_Int::search_elements_box_recursively (IntBoxData & boxdata, int octree_id, int cx, int cy, int cz, int half_width) const protected
cherche recursivement les elements inclus dans la boite
boxdata pour l'octree_id donne, de centre cx, cy, cz.
< les cubes superieurs en x ne sont pas dedans
< les cubes inferieurs ne sont pas dedans
Definition at line 235 of file Octree_Int.cpp.
{
  int flags = 255;
  if (cx > boxdata.xmax_) //!< les cubes superieurs en x ne sont pas dedans
    flags &= sub_cube_flags_min[0];
  if (cx <= boxdata.xmin_) //!< les cubes inferieurs ne sont pas dedans
    flags &= sub_cube_flags_max[0];
  if (cy > boxdata.ymax_)
    flags &= sub_cube_flags_min[1];
  if (cy <= boxdata.ymin_)
    flags &= sub_cube_flags_max[1];
  if (cz > boxdata.zmax_)
    flags &= sub_cube_flags_min[2];
  if (cz <= boxdata.zmin_)
    flags &= sub_cube_flags_max[2];
  int test_flag = 1;
  const int idx = octree_index(the_octree_id, OCTREE);
  const int half_width_2 = half_width >> 1;
  const int mhalf_width = - half_width_2;
  int cx2, cy2, cz2;
  for (int i = 0; i < 8; i++, test_flag <<= 1)
    {
      if ((flags & test_flag) != 0)
        {
          const int id = octree_structure_(idx, i);
          switch(octree_type(id))
            {
            case FLOOR:
              search_elements_box_floor(boxdata, id);
              break;
            case OCTREE:
              cx2 = cx + ((i & 1) ? half_width_2 : mhalf_width);
              cy2 = cy + ((i & 2) ? half_width_2 : mhalf_width);
              cz2 = cz + ((i & 4) ? half_width_2 : mhalf_width);
              search_elements_box_recursively(boxdata, id,
                                              cx2, cy2, cz2,
                                              half_width_2);
              break;
            case EMPTY:
              break;
            }
        }
    }
}
References EMPTY, FLOOR, OCTREE, octree_index(), octree_structure_, octree_type(), search_elements_box_floor(), search_elements_box_recursively(), sub_cube_flags_max, sub_cube_flags_min, IntBoxData::xmax_, IntBoxData::xmin_, IntBoxData::ymax_, IntBoxData::ymin_, IntBoxData::zmax_, and IntBoxData::zmin_.
Referenced by search_elements_box(), and search_elements_box_recursively().
search_octree_floor()
int Octree_Int::search_octree_floor (int x_pos, int y_pos, int z_pos) const protected
renvoie l'octree_id de l'octree_floor contenant le sommet (x,y,z)
(peut renvoyer l'octree EMPTY)
< On n'arrive jamais ici !
Definition at line 439 of file Octree_Int.cpp.
{
  if (octree_type(root_octree_id_) != OCTREE)
    return root_octree_id_;
// Le test pour savoir si on est dans la partie superieure ou
// inferieure d'un octree au niveau i consiste simplement a tester
// le i-ieme bit de la position.
  int flag = root_octree_half_width_;
  int index = octree_index(root_octree_id_, OCTREE);
// Descendre dans la hierarchie d'octree subdivises jusqu'au cube
// le plus petit
  while (1)
    {
// Numero du sous-cube dans lequel se trouve le sommet x,y,z
      const int ix = (x & flag) ? 1 : 0;
      const int iy = (y & flag) ? 2 : 0;
      const int iz = (z & flag) ? 4 : 0;
      int i_sous_cube = ix + iy + iz;
// On entre dans le sous-cube :
      const int the_octree_id = octree_structure_(index, i_sous_cube);
      if (octree_type(the_octree_id) != OCTREE)
        return the_octree_id;
      index = octree_index(the_octree_id, OCTREE);
      flag >>= 1;
    }
  return -1; //!< On n'arrive jamais ici !
}
References OCTREE, octree_index(), octree_structure_, octree_type(), root_octree_half_width_, and root_octree_id_.
Referenced by search_elements().
Member Data Documentation
coord_max_
const int Octree_Int::coord_max_ = 2147483647 static
Definition at line 37 of file Octree_Int.h.
Referenced by build(), Octree_Double::compute_origin_factors(), Octree_Double::integer_position(), Octree_Double::integer_position_clip(), search_elements(), and search_elements_box().
floor_elements_
ArrOfInt Octree_Int::floor_elements_ protected
Definition at line 76 of file Octree_Int.h.
Referenced by build(), build_octree_floor(), floor_elements(), reset(), search_elements(), and search_elements_box_floor().
nb_elements_
int Octree_Int::nb_elements_ protected
Definition at line 63 of file Octree_Int.h.
Referenced by build(), and reset().
octree_structure_
IntTab Octree_Int::octree_structure_ protected
Definition at line 70 of file Octree_Int.h.
Referenced by build(), build_octree_recursively(), reset(), search_elements(), search_elements_box(), search_elements_box_recursively(), and search_octree_floor().
root_octree_half_width_
const int Octree_Int::root_octree_half_width_ = 1073741824 static
Definition at line 39 of file Octree_Int.h.
Referenced by build(), search_elements_box(), and search_octree_floor().
root_octree_id_
int Octree_Int::root_octree_id_ protected
Definition at line 61 of file Octree_Int.h.
Referenced by build(), reset(), search_elements_box(), and search_octree_floor().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Octree_Int.h
src/Kernel/Geometrie/Octree_Int.cpp