TRUST: ModPerm_ErgunPourForch Class Reference
ModPerm_ErgunPourForch Class Reference
Cette classe represente la correlation de Ergun
associe au terme de Forchheimer,
pour la permeabilite d'un lit de particule de diametre donne.
#include <ModPerm_ErgunPourForch.h>
Public Member Functions
~ModPerm_ErgunPourForch ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
ModPerm_ErgunPourForch ()
double getK (double porosite) const
void setDiametre (double d)
double getDiametre () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static ModPerm_ErgunPourForch & self_cast (Objet_U &)
static const
ModPerm_ErgunPourForch & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le type du modele sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Protected Attributes
double diam
double C
Detailed Description
Cette classe represente la correlation de Ergun
associe au terme de Forchheimer,
pour la permeabilite d'un lit de particule de diametre donne.
Definition at line 36 of file ModPerm_ErgunPourForch.h.
Constructor & Destructor Documentation
ModPerm_ErgunPourForch::~ModPerm_ErgunPourForch ()
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
ModPerm_ErgunPourForch::ModPerm_ErgunPourForch ()
Definition at line 28 of file ModPerm_ErgunPourForch.cpp.
: diam(1.),C(1.75) { }
Member Function Documentation
Objet_U * ModPerm_ErgunPourForch::cree_instance () [static]
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
int ModPerm_ErgunPourForch::duplique () const [virtual]
Implements Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
const Type_info * ModPerm_ErgunPourForch::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
double ModPerm_ErgunPourForch::getDiametre () const [inline]
Definition at line 55 of file ModPerm_ErgunPourForch.h.
References diam.
  {
    return diam;
  } ;
double ModPerm_ErgunPourForch::getK (double porosite) const [inline, virtual]
Renvoie la valeur de la permeabilite en fonction de la porosite (d'une face par exemple).
Parameters:
porosite la porosite
Implements Modele_Permeabilite_base.
Definition at line 66 of file ModPerm_ErgunPourForch.h.
References C, and diam.
{
// assert(porosite != 1.);
// Cout << " Dans ModPerm_ErgunPourForch C = " << C << finl;
  double tmp = diam *porosite*porosite*porosite /(1.-porosite)/C;
  return tmp*tmp;
}
const Type_info * ModPerm_ErgunPourForch::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
Sortie & ModPerm_ErgunPourForch::printOn (Sortie & s) const [protected, virtual]
Imprime le type du modele sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 45 of file ModPerm_ErgunPourForch.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & ModPerm_ErgunPourForch::readOn (Entree & is) [protected, virtual]
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Definition at line 67 of file ModPerm_ErgunPourForch.cpp.
References Cerr, diam, Process::exit(), finl, Objet_U::que_suis_je(), and Motcles::search().
{
  Motcles les_mots(1);
  {
    les_mots[0] = "diametre";
  }
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> diam;
            break;
          }
        default :
          {
            Cerr << "Mot cle inconnu dans ModPerm_ErgunPourForch  " << finl;
            exit();
          }
        }
      is >> motlu;
    }
// Cout << "<<<<<<<<<<<<<<Dans ModPerm_ErgunPourForch diam = " << diam << finl;
  return is;
}
const ModPerm_ErgunPourForch & ModPerm_ErgunPourForch::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
ModPerm_ErgunPourForch & ModPerm_ErgunPourForch::self_cast (Objet_U & r) [static]
Reimplemented from Modele_Permeabilite_base.
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
void ModPerm_ErgunPourForch::setDiametre (double d) [inline]
Definition at line 51 of file ModPerm_ErgunPourForch.h.
References diam.
  {
    diam = d;
  } ;
unsigned ModPerm_ErgunPourForch::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file ModPerm_ErgunPourForch.cpp.
Member Data Documentation
double ModPerm_ErgunPourForch::C [protected]
Definition at line 63 of file ModPerm_ErgunPourForch.h.
Referenced by getK().
double ModPerm_ErgunPourForch::diam [protected]
Definition at line 58 of file ModPerm_ErgunPourForch.h.
Referenced by getDiametre(), getK(), readOn(), and setDiametre().
const Type_info ModPerm_ErgunPourForch::info_obj [static]
Reimplemented from Modele_Permeabilite_base.
Definition at line 39 of file ModPerm_ErgunPourForch.h.
The documentation for this class was generated from the following files:
src/VDF/Sources/ModPerm_ErgunPourForch.h
src/VDF/Sources/ModPerm_ErgunPourForch.cpp