TRUST: Champ_Face_implementation Class Reference
Champ_Face_implementation Class Reference abstract
#include <Champ_Face_implementation.h>
Public Member Functions
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_Face (Sortie &, int) const
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Protected Member Functions
virtual const Zone_VDF & zone_vdf () const =0
double interpolation (const double, const double, const double) const
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Detailed Description
Definition at line 25 of file Champ_Face_implementation.h.
Member Function Documentation
imprime_Face()
int Champ_Face_implementation::imprime_Face (Sortie & os, int ncomp) const
Definition at line 372 of file Champ_Face_implementation.cpp.
{
  const Champ_base& champ=le_champ();
  int ni,nj,nk=-1;
  IntVect m(3);
  int i,j,k;
  int np,elem;
  int cmax=7;
  DoubleVect xi,yj,zk;
  DoubleTab Grille;
// Lecture de xi,yj,zk dans un fichier .xiyjzk
  Nom nomfic(Objet_U::nom_du_cas());
  nomfic+=".xiyjzk";
  LecFicDiffuse ficijk(nomfic);
  ficijk >> xi;
  ni=xi.size();
  ficijk >> yj;
  nj=yj.size();
  if (Objet_U::dimension==3)
    {
      ficijk >> zk;
      nk=zk.size();
    }
  m=1;
  m(ncomp)=0;
  if (Objet_U::dimension==3)
    {
// Grille ordonnee sur les faces des elements
      ni-=m(0);
      nj-=m(1);
      nk-=m(2);
      np=ni*nj*nk;
      Grille.resize(np,Objet_U::dimension);
      for(k=0; k<nk; k++)
        for(i=0; i<ni; i++)
          for(j=0; j<nj; j++)
            {
              elem=j+nj*(i+k*ni);
              if (ncomp==0)
                Grille(elem,0)=xi(i);
              else
                Grille(elem,0)=0.5*(xi(i)+xi(i+1));
              if (ncomp==1)
                Grille(elem,1)=yj(j);
              else
                Grille(elem,1)=0.5*(yj(j)+yj(j+1));
              if (ncomp==2)
                Grille(elem,2)=zk(k);
              else
                Grille(elem,2)=0.5*(zk(k)+zk(k+1));
            }
      DoubleVect valeurs(np);
      champ.valeur_aux_compo(Grille, valeurs, ncomp);
      for(k=0; k<nk; k++)
        {
          os << finl;
          os << "Coupe a K= " << k << finl;
          int n1=0,n2=0;
          while (n2<ni)
            {
              n1=n2;
              n2=std::min(ni,n2+cmax);
              os << finl;
              os << "I=     ";
              for(i=n1; i<n2; i++)
                os << i << "              ";
              os << finl;
              for(j=nj-1; j>-1; j--)
                {
                  os << "J= " << j << " ";
                  for(i=n1; i<n2; i++)
                    {
                      elem=j+nj*(i+k*ni);
                      os << valeurs(elem) << " ";
                    }
                  os << finl;
                }
            }
        }
    }
  else if (Objet_U::dimension==2)
    {
      ni-=m(0);
      nj-=m(1);
      np=ni*nj;
      Grille.resize(np,Objet_U::dimension);
      for(i=0; i<ni; i++)
        for(j=0; j<nj; j++)
          {
            elem=j+nj*i;
            if (ncomp==0)
              Grille(elem,0)=xi(i);
            else
              Grille(elem,0)=0.5*(xi(i)+xi(i+1));
            if (ncomp==1)
              Grille(elem,1)=yj(j);
            else
              Grille(elem,1)=0.5*(yj(j)+yj(j+1));
          }
      DoubleVect valeurs(np);
      champ.valeur_aux_compo(Grille, valeurs, ncomp);
      int n1=0,n2=0;
      while (n2<ni)
        {
          n1=n2;
          n2=std::min(ni,n2+cmax);
          os << finl;
          os << "I=     ";
          for(i=n1; i<n2; i++)
            os << i << "              ";
          os << finl;
          for(j=nj-1; j>-1; j--)
            {
              os << "J= " << j << " ";
              for(i=n1; i<n2; i++)
                {
                  elem=j+nj*i;
                  os << valeurs(elem) << " ";
                }
              os << finl;
            }
        }
    }
  return 1;
}
References Objet_U::dimension, finl, Champ_implementation::le_champ(), Objet_U::nom_du_cas(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), and Champ_base::valeur_aux_compo().
Referenced by Champ_Face::imprime(), and Champ_Fonc_Face::imprime().
interpolation()
double Champ_Face_implementation::interpolation (const double val1, const double val2, const double psi) const protected
Definition at line 102 of file Champ_Face_implementation.cpp.
{
  double epsilon=1.e-12;
  if (std::fabs(psi) < epsilon)
    return val1 ;
  else if (std::fabs(1.-psi) < epsilon)
    return val2 ;
  else
    return val1 + psi * (val2-val1) ;
}
Referenced by valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), and valeur_aux_elems_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Face_implementation::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 342 of file Champ_Face_implementation.cpp.
{
  const Zone_VDF& la_zone_vdf = ref_cast(Zone_VDF,zone_dis_base());
  const DoubleTab& xv = la_zone_vdf.xv();
  int nb_fac = la_zone_vdf.nb_faces_tot();
  if ( (xv.dimension(0) == nb_fac ) && (xv.dimension(1) == Objet_U::dimension) )
    positions.ref(xv);
  else
    {
      Cerr << "Erreur dans Champ_Face::remplir_coord_noeuds()" << finl;
      Cerr << "Les centres de gravite des faces n'ont pas ete calcules" << finl;
      Process::exit();
    }
  return positions;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, Zone_VF::nb_faces_tot(), TRUSTTab< _TYPE_ >::ref(), ref_cast, Zone_VF::xv(), and Champ_implementation::zone_dis_base().
Referenced by Champ_Face::remplir_coord_noeuds(), Champ_Fonc_Face::remplir_coord_noeuds(), and remplir_coord_noeuds_et_polys().
remplir_coord_noeuds_et_polys()
int Champ_Face_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 358 of file Champ_Face_implementation.cpp.
{
  const IntTab& face_voisins = zone_vdf().face_voisins();
  int nb_faces=zone_vdf().nb_faces();
  remplir_coord_noeuds(positions);
  polys.resize(nb_faces);
  for(int face=0; face<nb_faces; face++)
    if( (polys(face)=face_voisins(face,0)) == -1)
      polys(face)=face_voisins(face,1);
  return 1;
}
References Zone_VF::face_voisins(), Zone_VF::nb_faces(), remplir_coord_noeuds(), TRUSTVect< _TYPE_ >::resize(), and zone_vdf().
Referenced by Champ_Face::remplir_coord_noeuds_et_polys(), and Champ_Fonc_Face::remplir_coord_noeuds_et_polys().
trace()
DoubleTab & Champ_Face_implementation::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const protected
< ori[face] = 2
< elem1 = -1
< ori[face] = 2
Definition at line 498 of file Champ_Face_implementation.cpp.
{
  assert(distant==0);
  const Front_VF& fr_vf=ref_cast(Front_VF, fr);
  const Zone_VDF& zvdf=zone_vdf();
  const IntVect& ori = zvdf.orientation();
  const IntTab& face_voisins = zvdf.face_voisins();
  const IntTab& elem_faces = zvdf.elem_faces();
  int elem1,elem2;
  int face,i,f1,f2,f3,f4;
  int nb_faces = fr_vf.nb_faces();
  if (x.dimension(0)!=nb_faces)
    {
      Cerr << "The number of faces " << nb_faces << " on the remote boundary " << fr.le_nom() << finl;
      Cerr << "does not match the number of faces " << x.dimension(0) << " on the local boundary." << finl;
      Cerr << "Please, check if the boundary condition is not applied on wrong boundaries." << finl;
      Process::exit();
    }
// assert(x.dimension(1)==Objet_U::dimension);
  if (x.dimension(1) == 1)
    {
      for (i=0; i<fr_vf.nb_faces(); i++)
        {
          face=fr_vf.num_premiere_face()+i;
          x(i,0)=y(face);
        }
      return x;
    }
  for (i=0; i<fr_vf.nb_faces(); i++)
    {
      face=fr_vf.num_premiere_face()+i;
      x(i,ori[face])=y(face);
    }
  for (i=0; i<fr_vf.nb_faces(); i++)
    {
      face=fr_vf.num_premiere_face()+i;
      elem1 = face_voisins(face,0);
      if (elem1 != -1)
        {
          if (Objet_U::dimension == 2)
            {
              if (ori[face] == 0)
                {
                  f1 = elem_faces(elem1,1);
                  f2 = elem_faces(elem1,3);
                  x(i,1)= 0.5*(y[f1] + y[f2]);
                }
              else
                {
                  f1 = elem_faces(elem1,0);
                  f2 = elem_faces(elem1,2);
                  x(i,0)= 0.5*(y[f1] + y[f2]);
                }
            }
          else if (Objet_U::dimension == 3)
            {
              if (ori[face] == 0)
                {
                  f1 = elem_faces(elem1,1);
                  f2 = elem_faces(elem1,4);
                  f3 = elem_faces(elem1,2);
                  f4 = elem_faces(elem1,5);
                  x(i,1)= 0.5*(y[f1] + y[f2]);
                  x(i,2)= 0.5*(y[f3] + y[f4]);
                }
              else if (ori[face] == 1)
                {
                  f1 = elem_faces(elem1,0);
                  f2 = elem_faces(elem1,3);
                  f3 = elem_faces(elem1,2);
                  f4 = elem_faces(elem1,5);
                  x(i,0)= 0.5*(y[f1] + y[f2]);
                  x(i,2)= 0.5*(y[f3] + y[f4]);
                }
              else //!< ori[face] = 2
                {
                  f1 = elem_faces(elem1,0);
                  f2 = elem_faces(elem1,3);
                  f3 = elem_faces(elem1,1);
                  f4 = elem_faces(elem1,4);
                  x(i,0)= 0.5*(y[f1] + y[f2]);
                  x(i,1)= 0.5*(y[f3] + y[f4]);
                }
            }
        }
      else  //!< elem1 = -1
        {
          elem2 = face_voisins(face,1);
          if (Objet_U::dimension == 2)
            {
              if (ori[face] == 0)
                {
                  f1 = elem_faces(elem2,1);
                  f2 = elem_faces(elem2,3);
                  x(i,1)= 0.5*(y[f1] + y[f2]);
                }
              else
                {
                  f1 = elem_faces(elem2,0);
                  f2 = elem_faces(elem2,2);
                  x(i,0)= 0.5*(y[f1] + y[f2]);
                }
            }
          else if (Objet_U::dimension == 3)
            {
              if (ori[face] == 0)
                {
                  f1 = elem_faces(elem2,1);
                  f2 = elem_faces(elem2,4);
                  f3 = elem_faces(elem2,2);
                  f4 = elem_faces(elem2,5);
                  x(i,1)= 0.5*(y[f1] + y[f2]);
                  x(i,2)= 0.5*(y[f3] + y[f4]);
                }
              else if (ori[face] == 1)
                {
                  f1 = elem_faces(elem2,0);
                  f2 = elem_faces(elem2,3);
                  f3 = elem_faces(elem2,2);
                  f4 = elem_faces(elem2,5);
                  x(i,0)= 0.5*(y[f1] + y[f2]);
                  x(i,2)= 0.5*(y[f3] + y[f4]);
                }
              else //!< ori[face] = 2
                {
                  f1 = elem_faces(elem2,0);
                  f2 = elem_faces(elem2,3);
                  f3 = elem_faces(elem2,1);
                  f4 = elem_faces(elem2,4);
                  x(i,0)= 0.5*(y[f1] + y[f2]);
                  x(i,1)= 0.5*(y[f3] + y[f4]);
                }
            }
        }
    }
// Useless ?x.echange_espace_virtuel();
  return x;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), f1, f2, Zone_VF::face_voisins(), finl, Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), ref_cast, and zone_vdf().
Referenced by Champ_Face::trace(), and Champ_Fonc_Face::trace().
valeur_a_elem()
DoubleVect & Champ_Face_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const override virtual
< (nb_compo_ != 1)
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 158 of file Champ_Face_implementation.cpp.
{
  const Zone_VDF& zone_VDF = zone_vdf();
  const Zone& zone_geom = zone();
  const IntTab& face_sommets = zone_VDF.face_sommets();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const Champ_base& cha=le_champ();
  double psi,val1,val2;
  int som0,som1;
  const DoubleTab& ch = cha.valeurs();
  int nb_compo_=cha.nb_comp();
  const Domaine& dom=zone_geom.domaine();
  if (nb_compo_ == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_a_elem"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  else //!< (nb_compo_ != 1)
    {
      if (le_poly == -1)
        for(int ncomp=0; ncomp<nb_compo_; ncomp++)
          val(ncomp) = 0;
      else
        for(int ncomp=0; ncomp<nb_compo_; ncomp++)
          {
            val1 = ch(elem_faces(le_poly,ncomp));
            val2 = ch(elem_faces(le_poly,Objet_U::dimension+ncomp));
            som0 = face_sommets(elem_faces(le_poly,ncomp),0);
            som1 = face_sommets(elem_faces(le_poly,Objet_U::dimension+ncomp),0);
            psi = ( position(ncomp) - dom.coord(som0,ncomp) )
                  / ( dom.coord(som1,ncomp) - dom.coord(som0,ncomp) ) ;
            val(ncomp) = interpolation(val1,val2,psi);
          }
    }
  return val;
}
References Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_sommets(), finl, interpolation(), Champ_implementation::le_champ(), Field_base::nb_comp(), Champ_Proto::valeurs(), Champ_implementation::zone(), and zone_vdf().
Referenced by Champ_Face::valeur_a_elem(), and Champ_Fonc_Face::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Face_implementation::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
< (nb_compo_ != 1)
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 202 of file Champ_Face_implementation.cpp.
{
  const Zone_VDF& zone_VDF = zone_vdf();
  const Zone& zone_geom = zone();
  const IntTab& face_sommets = zone_VDF.face_sommets();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const Champ_base& cha = le_champ();
  int nb_compo_ = cha.nb_comp();
  double psi,val1,val2;
  double val = 0.;
  int som0,som1;
  const DoubleTab& ch = cha.valeurs();
  const Domaine& dom=zone_geom.domaine();
  if (nb_compo_ == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_a_elem_compo"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  else //!< (nb_compo_ != 1)
    {
      if (le_poly == -1)
        return 0;
      else
        {
          val1 = ch(elem_faces(le_poly,ncomp));
          val2 = ch(elem_faces(le_poly,Objet_U::dimension+ncomp));
          som0 = face_sommets(elem_faces(le_poly,ncomp),0);
          som1 = face_sommets(elem_faces(le_poly,Objet_U::dimension+ncomp),0);
          psi = ( position(ncomp) - dom.coord(som0,ncomp) )
                / ( dom.coord(som1,ncomp) - dom.coord(som0,ncomp) ) ;
          val = interpolation(val1,val2,psi);
        }
    }
  return val;
}
References Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_sommets(), finl, interpolation(), Champ_implementation::le_champ(), Field_base::nb_comp(), Champ_Proto::valeurs(), Champ_implementation::zone(), and zone_vdf().
Referenced by Champ_Face::valeur_a_elem_compo(), Champ_Fonc_Face::valeur_a_elem_compo(), valeur_aux_sommets(), and valeur_aux_sommets_compo().
valeur_aux_elems()
DoubleTab & Champ_Face_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
< (nb_compo_ != 1) *‍/
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 23 of file Champ_Face_implementation.cpp.
{
  const Champ_base& cha=le_champ();
  int nb_compo_=cha.nb_comp();
  if (val.nb_dim() == 2)
    {
      assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
      assert(val.dimension(1) == nb_compo_);
    }
  else
    {
      Cerr << "Erreur TRUST dans Champ_Face_implementation::valeur_aux_elems()" << finl;
      Cerr << "Le DoubleTab val n'a pas 2 entrees" << finl;
      Process::exit();
    }
  const Zone_VDF& zone_VDF = zone_vdf();
// const Zone& zone_geom = zone_VDF.zone();
  const IntTab& face_sommets = zone_VDF.face_sommets();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  double psi,val1,val2;
  int som0,som1;
  int le_poly;
  const DoubleTab& ch = cha.valeurs();
  const Domaine& dom=zone().domaine();
  if (nb_compo_ == 1)
    {
      for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
        {
          le_poly=les_polys(rang_poly);
          if (le_poly == -1)
            val(rang_poly, 0) = 0;
          else
            for(int dir=0; dir<Objet_U::dimension; dir++)
              {
                int face1 = elem_faces(le_poly,dir);
                int face2 = elem_faces(le_poly,Objet_U::dimension+dir);
                val1 = ch(face1);
                val2 = ch(face2);
                som0 = face_sommets(face1,0);
                som1 = face_sommets(face2,0);
                psi = ( positions(rang_poly,dir) - dom.coord(som0,dir) )
                      / ( dom.coord(som1,dir) - dom.coord(som0,dir) ) ;
                if (est_egal(psi,0) || est_egal(psi,1))
                  val(rang_poly,0) = interpolation(val1,val2,psi);
              }
        }
    }
  else //!< (nb_compo_ != 1) */
    {
      for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
        {
          le_poly=les_polys(rang_poly);
          if (le_poly == -1)
            for(int ncomp=0; ncomp<nb_compo_; ncomp++)
              val(rang_poly,ncomp) = 0;
          else
            for(int ncomp=0; ncomp<nb_compo_; ncomp++)
              {
                val1 = ch(elem_faces(le_poly,ncomp));
                val2 = ch(elem_faces(le_poly,Objet_U::dimension+ncomp));
                som0 = face_sommets(elem_faces(le_poly,ncomp),0);
                som1 = face_sommets(elem_faces(le_poly,Objet_U::dimension+ncomp),0);
                psi = ( positions(rang_poly,ncomp) - dom.coord(som0,ncomp) )
                      / ( dom.coord(som1,ncomp) - dom.coord(som0,ncomp) ) ;
                val(rang_poly,ncomp) = interpolation(val1,val2,psi);
              }
        }
    }
  return val;
}
References Cerr, Domaine::coord(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Zone::domaine(), Zone_VF::elem_faces(), est_egal(), Process::exit(), Zone_VF::face_sommets(), finl, interpolation(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTVect< _TYPE_ >::size(), Champ_Proto::valeurs(), Champ_implementation::zone(), and zone_vdf().
Referenced by Champ_Face::valeur_aux_elems(), and Champ_Fonc_Face::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Face_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
< (nb_compo_ != 1)
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 113 of file Champ_Face_implementation.cpp.
{
  const Champ_base& cha = le_champ();
  int nb_compo_ = cha.nb_comp();
  assert(val.size() == les_polys.size());
  int le_poly;
  double psi,val1,val2;
  int som0,som1;
  const Zone_VDF& zone_VDF = zone_vdf();
// const Zone& zone_geom = zone_VDF.zone();
  const IntTab& face_sommets = zone_VDF.face_sommets();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const DoubleTab& ch = cha.valeurs();
  const Domaine& dom=zone().domaine();
  if (nb_compo_ == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_aux_elems_compo"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  else //!< (nb_compo_ != 1)
    {
      for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
        {
          le_poly=les_polys(rang_poly);
          if (le_poly == -1)
            val(rang_poly) = 0;
          else
            {
              val1 = ch(elem_faces(le_poly,ncomp));
              val2 = ch(elem_faces(le_poly,Objet_U::dimension+ncomp));
              som0 = face_sommets(elem_faces(le_poly,ncomp),0);
              som1 = face_sommets(elem_faces(le_poly,Objet_U::dimension+ncomp),0);
              psi = ( positions(rang_poly,ncomp) - dom.coord(som0,ncomp) )
                    / ( dom.coord(som1,ncomp) - dom.coord(som0,ncomp) ) ;
              val(rang_poly) = interpolation(val1,val2,psi);
            }
        }
    }
  return val;
}
References Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_sommets(), finl, interpolation(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), Champ_Proto::valeurs(), Champ_implementation::zone(), and zone_vdf().
Referenced by Champ_Face::valeur_aux_elems_compo(), and Champ_Fonc_Face::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Face_implementation::valeur_aux_sommets (const Domaine & dom, DoubleTab & ch_som) const override virtual
< (nb_compo_ != 1)
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 243 of file Champ_Face_implementation.cpp.
{
// const Champ_base& cha_tmp=le_champ();
// const DoubleTab& ch_tmp = cha_tmp.valeurs();
  const Champ_base& cha=le_champ();
  int nb_compo_=cha.nb_comp();
  const Zone& mazone = dom.zone(0);
// int nb_elem = mazone.nb_elem();
  int nb_elem_tot = mazone.nb_elem_tot();
  int nb_som = mazone.nb_som();
  int nb_som_elem = mazone.nb_som_elem();
// const DoubleTab& ch = cha.valeurs();
  IntVect compteur(nb_som);
  int ncomp;
  int num_elem,num_som,j;
  ch_som = 0;
  compteur = 0;
  if (nb_compo_ == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_aux_sommets"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  else //!< (nb_compo_ != 1)
    {
      DoubleVect position(Objet_U::dimension);
      for (num_elem=0; num_elem<nb_elem_tot; num_elem++)
        for (j=0; j<nb_som_elem; j++)
          {
            num_som = mazone.sommet_elem(num_elem,j);
            for(int k=0; k<Objet_U::dimension; k++)
              position(k)=dom.coord(num_som,k);
            if(num_som < nb_som)
              {
                compteur[num_som]++;
                for (ncomp=0; ncomp<nb_compo_; ncomp++)
                  {
                    ch_som(num_som,ncomp) += valeur_a_elem_compo(position,num_elem,ncomp);
                  }
              }
          }
      for (num_som=0; num_som<nb_som; num_som++)
        for (ncomp=0; ncomp<nb_compo_; ncomp++)
          ch_som(num_som,ncomp) /= compteur[num_som];
    }
  return ch_som;
}
References Cerr, compteur, Domaine::coord(), Objet_U::dimension, Process::exit(), finl, Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), Zone::sommet_elem(), valeur_a_elem_compo(), and Domaine::zone().
Referenced by Champ_Face::valeur_aux_sommets(), and Champ_Fonc_Face::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Face_implementation::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & ch_som, int ncomp) const override virtual
< (nb_compo_ != 1)
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face.
Definition at line 296 of file Champ_Face_implementation.cpp.
{
  const Champ_base& cha=le_champ();
  int nb_compo_=cha.nb_comp();
  const Zone& mazone = dom.zone(0);
// int nb_elem = mazone.nb_elem();
  int nb_elem_tot = mazone.nb_elem_tot();
  int nb_som = mazone.nb_som();
  int nb_som_elem = mazone.nb_som_elem();
// const DoubleTab& ch = cha.valeurs();
  IntVect compteur(nb_som);
  int num_elem,num_som,j;
  ch_som = 0;
  compteur = 0;
  if (nb_compo_ == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_aux_sommets_compo"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  else //!< (nb_compo_ != 1)
    {
      DoubleVect position(Objet_U::dimension);
      for (num_elem=0; num_elem<nb_elem_tot; num_elem++)
        for (j=0; j<nb_som_elem; j++)
          {
            num_som = mazone.sommet_elem(num_elem,j);
            for(int k=0; k<Objet_U::dimension; k++)
              position(k)=dom.coord(num_som,k);
            if(num_som < nb_som)
              {
                compteur[num_som]++;
                ch_som(num_som) += valeur_a_elem_compo(position,num_elem,ncomp);
              }
          }
      for (num_som=0; num_som<nb_som; num_som++)
        ch_som(num_som) /= compteur[num_som];
    }
  return ch_som;
}
References Cerr, compteur, Domaine::coord(), Objet_U::dimension, Process::exit(), finl, Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), Zone::sommet_elem(), valeur_a_elem_compo(), and Domaine::zone().
Referenced by Champ_Face::valeur_aux_sommets_compo(), and Champ_Fonc_Face::valeur_aux_sommets_compo().
zone_vdf()
virtual const Zone_VDF & Champ_Face_implementation::zone_vdf () const protected pure virtual
Implemented in Champ_Face, and Champ_Fonc_Face.
Referenced by remplir_coord_noeuds_et_polys(), trace(), valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), and valeur_aux_elems_compo().
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_Face_implementation.h
src/VDF/Champs/Champ_Face_implementation.cpp