TRUST: Fichier_Lata Class Reference
Fichier_Lata Class Reference
#include <Fichier_Lata.h>
Public Types
enum Mode { ERASE , APPEND }
Public Member Functions
Fichier_Lata (const char *basename, const char *extension, Mode mode_append, Format_Post_Lata::Format format, Format_Post_Lata::Options_Para parallel)
Construit un fichier de type EcrFicPartage(Bin) ou EcrFicPrive(Bin),
binaire ou pas selon le parametre "format".
Si parallel==MULTIPLE_FILES, le fichier est de type EcrFicPrive(Bin).
Dans ce cas, chaque processeur ouvre un fichier different, dont
le nom est "basename_XXXXXextension", ou XXXXX est egal a Process::me().
Tous les processeurs renverront is_master() == 1.
Si parallel==SINGLE_FILE est non nul, le fichier est de type EcrFicPartage(Bin).
Seul le processeur maitre ouvre le fichier, le nom du fichier est
"basenameextension".
is_master() renverra 1 sur le maitre, 0 sur les autres processeurs.
Parametre: basename
Signification: debut du nom du fichier
Parametre: extension
Signification: fin du nom du fichier
Parametre: mode_append
Signification: Si mode_append==ERASE, on ouvre en mode ecriture,
si mode_append==APPEND, on ouvre en mode append.
Parametre: format
Signification: Determine si on ouvre en binaire ou pas.
(valeurs possibles: Format_Post_Lata::ASCII ou Format_Post_Lata::BINAIRE)
Parametre: parallel
Signification: fichier unique partage ou plusieurs fichiers prives...
virtual ~Fichier_Lata ()
virtual SFichier & get_SFichier ()
virtual const Nom & get_filename () const
Renvoie le nom du fichier avec le path.
virtual int is_master () const
Si le fichier est de type partage, renvoie 1 si me() est egal au master
du groupe et 0 sinon,
Si le fichier est prive, renvoie 1 sur tous les processeurs.
virtual void syncfile ()
Si le fichier est de type partage, appelle la methode syncfile(),
sinon ne fait rien.
Protected Attributes
Nom filename_
SFichier * fichier_
int is_parallel_
Detailed Description
Definition at line 26 of file Fichier_Lata.h.
Member Enumeration Documentation
Mode
enum Fichier_Lata::Mode
Enumerator
ERASE
APPEND
Definition at line 29 of file Fichier_Lata.h.
{ERASE, APPEND};
Constructor & Destructor Documentation
Fichier_Lata()
Fichier_Lata::Fichier_Lata (const char * basename, const char * extension, Mode mode_append, Format_Post_Lata::Format format, Format_Post_Lata::Options_Para parallel)
Construit un fichier de type EcrFicPartage(Bin) ou EcrFicPrive(Bin),
binaire ou pas selon le parametre "format".
Si parallel==MULTIPLE_FILES, le fichier est de type EcrFicPrive(Bin).
Dans ce cas, chaque processeur ouvre un fichier different, dont
le nom est "basename_XXXXXextension", ou XXXXX est egal a Process::me().
Tous les processeurs renverront is_master() == 1.
Si parallel==SINGLE_FILE est non nul, le fichier est de type EcrFicPartage(Bin).
Seul le processeur maitre ouvre le fichier, le nom du fichier est
"basenameextension".
is_master() renverra 1 sur le maitre, 0 sur les autres processeurs.
Parametre: basename
Signification: debut du nom du fichier
Parametre: extension
Signification: fin du nom du fichier
Parametre: mode_append
Signification: Si mode_append==ERASE, on ouvre en mode ecriture,
si mode_append==APPEND, on ouvre en mode append.
Parametre: format
Signification: Determine si on ouvre en binaire ou pas.
(valeurs possibles: Format_Post_Lata::ASCII ou Format_Post_Lata::BINAIRE)
Parametre: parallel
Signification: fichier unique partage ou plusieurs fichiers prives...
Definition at line 52 of file Format_Post_Lata.cpp.
                                                                  :
  filename_(""),
  fichier_(0),
  is_parallel_(0)
{
  char s[20] = "";
  switch(parallel)
    {
    case Format_Post_Lata::SINGLE_FILE_MPIIO:
    case Format_Post_Lata::SINGLE_FILE:
      {
        is_parallel_ = 1;
        filename_ = basename;
        filename_ += extension;
// Pour un calcul sequentiel, on ouvre un fichier SFichier
// pour ne pas bufferiser en memoire
        if  (Process::nproc() == 1)
          fichier_ = new SFichier;
        else
          {
            if (format == Format_Post_Lata::BINAIRE && parallel == Format_Post_Lata::SINGLE_FILE_MPIIO)
              fichier_ = new EcrFicPartageMPIIO;
            else
              fichier_ = new EcrFicPartage;
          }
        break;
      }
    case Format_Post_Lata::MULTIPLE_FILES:
      {
        is_parallel_ = 0;
        fichier_ = new SFichier;
        const int moi = Process::me();
        sprintf(s, "_%05d", (True_int)moi);
        break;
      }
    default:
      Cerr << "Fichier_Lata::Fichier_Lata: parallel option not supported " << (int)parallel << finl;
      Process::exit();
    }
  filename_ = basename;
  filename_ += s;
  filename_ += extension;
  switch(format)
    {
    case Format_Post_Lata::ASCII:
      fichier_->set_bin(0);
      break;
    case Format_Post_Lata::BINAIRE:
      fichier_->set_bin(1);
      break;
    default:
      Cerr << "Fichier_Lata::Fichier_Lata: format not supported " << (int)format << finl;
      Process::exit();
    }
  IOS_OPEN_MODE mode = ios::out;
  switch(mode_append)
    {
    case ERASE:
      mode = ios::out;
      break;
    case APPEND:
      mode = ios::out | ios::app;
      break;
    default:
      Cerr << "Fichier_Lata::Fichier_Lata: open mode not supported " << (int)mode_append << finl;
      Process::exit();
    }
// if (Process::je_suis_maitre() || parallel==Format_Post_Lata::MULTIPLE_FILES)
  {
    int ok = fichier_->ouvrir(filename_, mode);
    if (!ok)
      {
        Cerr << "Error in Fichier_Lata::Fichier_Lata\n"
             << " Error while opening file : " << filename_
             << finl;
        Process::exit();
      }
    fichier_->setf(ios::scientific);
    fichier_->precision(8);
  }
}
References APPEND, Format_Post_Lata::ASCII, Format_Post_Lata::BINAIRE, Cerr, ERASE, Process::exit(), fichier_, filename_, finl, IOS_OPEN_MODE, is_parallel_, Process::me(), Format_Post_Lata::MULTIPLE_FILES, Process::nproc(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Sortie::set_bin(), Sortie_Fichier_base::setf(), Format_Post_Lata::SINGLE_FILE, and Format_Post_Lata::SINGLE_FILE_MPIIO.
~Fichier_Lata()
Fichier_Lata::~Fichier_Lata () virtual
Definition at line 141 of file Format_Post_Lata.cpp.
{
  if (fichier_)
    {
      delete fichier_;
      fichier_ = 0;
    }
}
References fichier_.
Member Function Documentation
get_filename()
const Nom & Fichier_Lata::get_filename () const virtual
Renvoie le nom du fichier avec le path.
Definition at line 158 of file Format_Post_Lata.cpp.
{
  return filename_;
}
References filename_.
Referenced by Format_Post_Lata::ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), and Format_Post_Lata::ecrire_item_int().
get_SFichier()
SFichier & Fichier_Lata::get_SFichier () virtual
Definition at line 150 of file Format_Post_Lata.cpp.
{
  assert(fichier_);
  return *fichier_;
}
References fichier_.
Referenced by Format_Post_Lata::ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata::ecrire_entete_lata(), Format_Post_Lata_V1::ecrire_entete_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Format_Post_Lata::ecrire_item_int(), Format_Post_Lata::ecrire_temps_lata(), Format_Post_Lata::finir(), Format_Post_Lata_V1::finir_lata_V1(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
is_master()
int Fichier_Lata::is_master () const virtual
Si le fichier est de type partage, renvoie 1 si me() est egal au master
du groupe et 0 sinon,
Si le fichier est prive, renvoie 1 sur tous les processeurs.
Definition at line 167 of file Format_Post_Lata.cpp.
{
  int resu = 0;
  if (is_parallel_ == 0)
    {
// Execution sequentielle, fichiers prives chaque processeur est maitre
      resu = 1;
    }
  else
    {
// Execution parallele : un seul maitre
      if (Process::je_suis_maitre())
        resu = 1;
    }
  return resu;
}
References is_parallel_, and Process::je_suis_maitre().
Referenced by Format_Post_Lata::ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata::ecrire_entete_lata(), Format_Post_Lata_V1::ecrire_entete_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Format_Post_Lata::ecrire_item_int(), Format_Post_Lata::ecrire_temps_lata(), Format_Post_Lata::finir(), Format_Post_Lata_V1::finir_lata_V1(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
syncfile()
void Fichier_Lata::syncfile () virtual
Si le fichier est de type partage, appelle la methode syncfile(),
sinon ne fait rien.
Definition at line 187 of file Format_Post_Lata.cpp.
{
  if (is_parallel_ && Process::nproc() > 1)
    fichier_->syncfile();
}
References fichier_, is_parallel_, Process::nproc(), and Sortie::syncfile().
Referenced by Format_Post_Lata::ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata::ecrire_entete_lata(), Format_Post_Lata_V1::ecrire_entete_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Format_Post_Lata::ecrire_item_int(), Format_Post_Lata::ecrire_temps_lata(), Format_Post_Lata::finir(), Format_Post_Lata_V1::finir_lata_V1(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
Member Data Documentation
fichier_
SFichier* Fichier_Lata::fichier_ protected
Definition at line 41 of file Fichier_Lata.h.
Referenced by Fichier_Lata(), Fichier_Lata_maitre::Fichier_Lata_maitre(), get_SFichier(), syncfile(), and ~Fichier_Lata().
filename_
Nom Fichier_Lata::filename_ protected
Definition at line 40 of file Fichier_Lata.h.
Referenced by Fichier_Lata(), and get_filename().
is_parallel_
int Fichier_Lata::is_parallel_ protected
Definition at line 42 of file Fichier_Lata.h.
Referenced by Fichier_Lata(), is_master(), and syncfile().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Fichier_Lata.h
src/Kernel/Framework/Format_Post_Lata.cpp