TRUST: Eval_Amont_VDF_Face Class Reference
Eval_Amont_VDF_Face Class Reference
class Eval_Amont_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection Amont
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif pour l'EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure
dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en
ce qui concerne les termes pour la matrice, par contre pour le second membre nous
procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies
par les conditions limites.
#include <Eval_Amont_VDF_Face.h>
Public Member Functions
Eval_Amont_VDF_Face ()
int calculer_arete_fluide () const
int calculer_arete_paroi () const
int calculer_arete_paroi_fluide () const
int calculer_arete_coin_fluide () const
int calculer_arete_symetrie () const
int calculer_arete_interne () const
int calculer_arete_mixte () const
int calculer_fa7_sortie_libre () const
int calculer_arete_periodicite () const
int calculer_arete_symetrie_paroi () const
int calculer_arete_symetrie_fluide () const
double flux_fa7_elem (const DoubleTab &, int, int, int) const
double flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_arete_interne (const DoubleTab &, int, int, int, int) const
double flux_arete_mixte (const DoubleTab &, int, int, int, int) const
double flux_arete_paroi (const DoubleTab &, int, int, int, int) const
double flux_arete_symetrie (const DoubleTab &, int, int, int, int) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_coin_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, double &, double &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, double &, double &) const
double flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int) const
void flux_fa7_elem (const DoubleTab &, int, int, int, DoubleVect &flux) const
void flux_fa7_sortie_libre (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_arete_interne (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_mixte (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void flux_arete_symetrie (const DoubleTab &, int, int, int, int, DoubleVect &) const
void flux_arete_paroi (const DoubleTab &, int, int, int, int, DoubleVect &) const
void flux_arete_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_paroi_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_coin_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_periodicite (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_fluide (const DoubleTab &, int, int, int, int, DoubleVect &, DoubleVect &) const
void flux_arete_symetrie_paroi (const DoubleTab &, int, int, int, int, DoubleVect &flux) const
void coeffs_fa7_elem (int, int, int, double &aii, double &ajj) const
void coeffs_fa7_sortie_libre (int, const Neumann_sortie_libre &, double &aii, double &ajj) const
void coeffs_arete_interne (int, int, int, int, double &aii, double &ajj) const
void coeffs_arete_mixte (int, int, int, int, double &aii, double &ajj) const
void coeffs_arete_symetrie (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_paroi (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_paroi_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_coin_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_periodicite (int, int, int, int, double &aii, double &ajj) const
void coeffs_arete_symetrie_fluide (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
void coeffs_arete_symetrie_paroi (int, int, int, int, double &aii1_2, double &aii3_4, double &ajj1_2) const
double secmem_fa7_elem (int, int, int) const
double secmem_fa7_sortie_libre (int, const Neumann_sortie_libre &, int) const
double secmem_arete_interne (int, int, int, int) const
double secmem_arete_mixte (int, int, int, int) const
double secmem_arete_symetrie (int, int, int, int) const
double secmem_arete_paroi (int, int, int, int) const
void secmem_arete_fluide (int, int, int, int, double &, double &) const
void secmem_arete_paroi_fluide (int, int, int, int, double &, double &) const
void secmem_arete_coin_fluide (int, int, int, int, double &, double &) const
void secmem_arete_periodicite (int, int, int, int, double &, double &) const
void secmem_arete_symetrie_fluide (int, int, int, int, double &, double &) const
double secmem_arete_symetrie_paroi (int, int, int, int) const
void coeffs_fa7_elem (int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_fa7_sortie_libre (int, const Neumann_sortie_libre &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_interne (int, int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_mixte (int, int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_symetrie (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_paroi (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_paroi_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_coin_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_periodicite (int, int, int, int, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_arete_symetrie_fluide (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void coeffs_arete_symetrie_paroi (int, int, int, int, DoubleVect &aii1_2, DoubleVect &aii3_4, DoubleVect &ajj1_2) const
void secmem_fa7_elem (int, int, int, DoubleVect &flux) const
void secmem_fa7_sortie_libre (int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void secmem_arete_interne (int, int, int, int, DoubleVect &flux) const
void secmem_arete_mixte (int, int, int, int, DoubleVect &flux) const
void secmem_arete_symetrie (int, int, int, int, DoubleVect &) const
void secmem_arete_paroi (int, int, int, int, DoubleVect &) const
void secmem_arete_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_paroi_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_coin_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_periodicite (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_symetrie_fluide (int, int, int, int, DoubleVect &, DoubleVect &) const
void secmem_arete_symetrie_paroi (int, int, int, int, DoubleVect &) const
Detailed Description
class Eval_Amont_VDF_Face
Evaluateur VDF pour la convection
Le champ convecte est un Champ_Face
Schema de convection Amont
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif pour l'EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure
dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en
ce qui concerne les termes pour la matrice, par contre pour le second membre nous
procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies
par les conditions limites.
See also:
Eval_Conv_VDF
Definition at line 52 of file Eval_Amont_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Amont_VDF_Face::Eval_Amont_VDF_Face () [inline]
Definition at line 185 of file Eval_Amont_VDF_Face.h.
{
}
Member Function Documentation
int Eval_Amont_VDF_Face::calculer_arete_coin_fluide () const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 218 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_fluide () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 192 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_interne () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 242 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_mixte () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 250 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_paroi () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 201 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
int Eval_Amont_VDF_Face::calculer_arete_paroi_fluide () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 210 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_periodicite () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 226 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_symetrie () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 234 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
int Eval_Amont_VDF_Face::calculer_arete_symetrie_fluide () const [inline]
Reimplemented from Eval_VDF_Face.
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 274 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
int Eval_Amont_VDF_Face::calculer_arete_symetrie_paroi () const [inline]
Reimplemented from Eval_VDF_Face.
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 266 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
int Eval_Amont_VDF_Face::calculer_fa7_sortie_libre () const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 258 of file Eval_Amont_VDF_Face.h.
{
  return 1;
}
void Eval_Amont_VDF_Face::coeffs_arete_coin_fluide (int fac1, int , int fac3, int signe, DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1147 of file Eval_Amont_VDF_Face.h.
References Cerr, Process::exit(), and finl.
{
  Cerr << "ToDo: code like Eval_Amont_VDF_Face::coeffs_arete_coin_fluide for a scalar inco" << finl;
  Process::exit();
}
void Eval_Amont_VDF_Face::coeffs_arete_coin_fluide (int fac1, int , int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 396 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc;
// Calcul de flux3:
  psc = 0.5*dt_vitesse[fac1]*porosite[fac1]*surface(fac1);
  if ((psc*signe)>0)
    aii3_4 = psc ;
  else
    aii3_4 = 0;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      aii1_2 = psc;
      ajj1_2 = 0;
    }
  else
    {
      ajj1_2 = -psc;
      aii1_2 = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_fluide (int fac1, int fac2, int fac3, int signe, DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1115 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<aii3_4.size(); k++)
      aii3_4(k) = psc ;
  else
    for (k=0; k<aii3_4.size(); k++)
      aii3_4(k) = 0 ;
// Calcul des coefficients entre 1 et 2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      for (k=0; k<aii1_2.size(); k++)
        aii1_2(k) = psc;
      for (k=0; k<ajj1_2.size(); k++)
        ajj1_2(k) = 0;
    }
  else
    {
      for (k=0; k<aii1_2.size(); k++)
        aii1_2(k) = 0;
      for (k=0; k<ajj1_2.size(); k++)
        ajj1_2(k) = -psc;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_fluide (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 362 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    aii3_4 = psc ;
  else
    aii3_4 = 0;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      aii1_2 = psc;
      ajj1_2 = 0;
    }
  else
    {
      ajj1_2 = -psc;
      aii1_2 = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_interne (int fac1, int fac2, int fac3, int fac4, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 503 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    {
      aii = psc;
      ajj=0;
    }
  else
    {
      ajj = -psc;
      aii=0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_interne (int fac1, int fac2, int fac3, int fac4, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1216 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = psc;
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for (k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_mixte (int fac1, int fac2, int fac3, int fac4, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 554 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    {
      aii = psc;
      ajj = 0;
    }
  else
    {
      ajj = -psc;
      aii = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_mixte (int fac1, int fac2, int fac3, int fac4, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1271 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = psc;
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for (k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_paroi (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1317 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::coeffs_arete_paroi (int , int , int , int , double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 596 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::coeffs_arete_paroi_fluide (int fac1, int fac2, int fac3, int signe, DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1371 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<aii3_4.size(); k++)
      aii3_4(k) = psc ;
  else
    for (k=0; k<aii3_4.size(); k++)
      aii3_4(k) = 0;
// Calcul des coefficients entre 1 et 2
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      for (k=0; k<aii1_2.size(); k++)
        aii1_2(k) = psc;
      for (k=0; k<ajj1_2.size(); k++)
        ajj1_2(k) = 0;
    }
  else
    {
      for (k=0; k<aii1_2.size(); k++)
        aii1_2(k) = 0;
      for (k=0; k<ajj1_2.size(); k++)
        ajj1_2(k) = -psc;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_paroi_fluide (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 650 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    aii3_4 = psc ;
  else
    aii3_4 = 0 ;
// Calcul des coefficients entre les faces 1 et 2.
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      aii1_2 = psc;
      ajj1_2 = 0;
    }
  else
    {
      ajj1_2 = -psc;
      aii1_2 = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_periodicite (int fac1, int fac2, int fac3, int fac4, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1476 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc;
  int k;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  if (psc>0)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = psc;
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for (k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_periodicite (int fac1, int fac2, int fac3, int fac4, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 748 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  if (psc>0)
    {
      aii = psc;
      ajj = 0;
    }
  else
    {
      ajj = -psc;
      aii = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_symetrie (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1525 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::coeffs_arete_symetrie (int , int , int , int , double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 794 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::coeffs_arete_symetrie_fluide (int fac1, int fac2, int fac3, int signe, DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1713 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<aii3_4.size(); k++)
      aii3_4(k) = psc ;
  else
    for (k=0; k<aii3_4.size(); k++)
      aii3_4(k) = 0 ;
// Calcul des coefficients entre 1 et 2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      for (k=0; k<aii1_2.size(); k++)
        aii1_2(k) = psc;
      for (k=0; k<ajj1_2.size(); k++)
        ajj1_2(k) = 0;
    }
  else
    {
      for (k=0; k<aii1_2.size(); k++)
        aii1_2(k) = 0;
      for (k=0; k<ajj1_2.size(); k++)
        ajj1_2(k) = -psc;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_symetrie_fluide (int fac1, int fac2, int fac3, int signe, double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 972 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    aii3_4 = psc ;
  else
    aii3_4 = 0;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    {
      aii1_2 = psc;
      ajj1_2 = 0;
    }
  else
    {
      ajj1_2 = -psc;
      aii1_2 = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_arete_symetrie_paroi (int , int , int , int , DoubleVect & aii1_2, DoubleVect & aii3_4, DoubleVect & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1794 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::coeffs_arete_symetrie_paroi (int , int , int , int , double & aii1_2, double & aii3_4, double & ajj1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1049 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::coeffs_fa7_elem (int , int fac1, int fac2, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 827 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2]) *
               (surface[fac1]+surface[fac2]);
  if (psc>0)
    {
      aii = psc*porosite[fac1];
      ajj = 0;
    }
  else
    {
      ajj = -psc*porosite[fac2];
      aii = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_fa7_elem (int , int fac1, int fac2, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1559 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*
               (surface[fac1]+surface[fac2]);
  if (psc>0)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = psc*porosite[fac1];
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
      for (k=0; k<ajj.size(); k++)
        ajj(k) = -psc*porosite[fac2];
    }
}
void Eval_Amont_VDF_Face::coeffs_fa7_sortie_libre (int face, const Neumann_sortie_libre & la_cl, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 877 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double psc = dt_vitesse[face]*surface(face);
  if (psc > 0)
    {
      aii = psc*porosite[face];
      ajj = 0;
    }
  else
    {
      ajj = -psc*porosite[face];
      aii = 0;
    }
}
void Eval_Amont_VDF_Face::coeffs_fa7_sortie_libre (int face, const Neumann_sortie_libre & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1619 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc = dt_vitesse[face]*surface(face);
// int i = elem(face,0);
// int j = elem(face,1);
  int k;
  if (psc>0)
    {
      for (k=0; k<aii.size(); k++)
        aii(k) = psc*porosite[face];
      for (k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for (k=0; k<ajj.size(); k++)
        ajj(k) = -psc*porosite[face];
      for (k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_VDF_Face::flux_arete_coin_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1104 of file Eval_Amont_VDF_Face.h.
References Cerr, Process::exit(), and finl.
{
  Cerr << "ToDo: code like Eval_Amont_VDF_Face::flux_arete_coin_fluide for a scalar inco" << finl;
  Process::exit();
}
void Eval_Amont_VDF_Face::flux_arete_coin_fluide (const DoubleTab & inco, int fac1, int , int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 323 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux, psc;
// Calcul de flux3:
  psc = 0.5 * dt_vitesse[fac1] * porosite[fac1] * surface(fac1);
  if ((psc * signe) > 0)
    flux = inco[fac3] * psc;
  else
    {
      int rang1 = (fac1 - premiere_face_bord);
      int ori = orientation(fac3);
      flux = Champ_Face_get_val_imp_face_bord(inconnue->temps(), rang1, ori, la_zcl) * psc;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5 * dt_vitesse(fac3) * surface(fac3) * porosite(fac3);
  if (psc > 0)
    flux = psc * inco[fac1];
  else
    {
      int rang3 = (fac3 - premiere_face_bord);
      int ori = orientation(fac1);
      flux = psc * Champ_Face_get_val_imp_face_bord(inconnue->temps(), rang3, ori, la_zcl);
    }
  flux1_2 = -flux;
}
void Eval_Amont_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 286 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  flux3 =  -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Amont_VDF_Face::flux_arete_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1070 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Amont_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1196 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac4,k);
}
double Eval_Amont_VDF_Face::flux_arete_interne (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 484 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  return -flux;
}
void Eval_Amont_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1252 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac4,k);
}
double Eval_Amont_VDF_Face::flux_arete_mixte (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 534 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                        dt_vitesse[fac2]*porosite[fac2] ) *
               ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  return -flux;
}
double Eval_Amont_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 587 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
void Eval_Amont_VDF_Face::flux_arete_paroi (const DoubleTab & , int , int , int , int , DoubleVect &) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1307 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 614 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double psc,flux;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  flux3 = -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Amont_VDF_Face::flux_arete_paroi_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1334 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Amont_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, DoubleVect & flux3_4, DoubleVect & flux1_2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1438 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc;
  int k;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  if (psc>0)
    for (k=0; k<flux3_4.size(); k++)
      flux3_4(k) = -psc*inco(fac3,k);
  else
    for (k=0; k<flux3_4.size(); k++)
      flux3_4(k) = -psc*inco(fac4,k);
// On calcule le flux convectifs entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25 * ( dt_vitesse[fac3]*porosite[fac3] +
                 dt_vitesse[fac4]*porosite[fac4] ) *
        ( surface[fac3] + surface[fac4] );
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux3_4.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Amont_VDF_Face::flux_arete_periodicite (const DoubleTab & inco, int fac1, int fac2, int fac3, int fac4, double & flux3_4, double & flux1_2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 708 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc;
// On calcule le flux convectif entre les volumes de controle associes a fac3 et fac4:
  psc = 0.25 * ( dt_vitesse[fac1]*porosite[fac1] +
                 dt_vitesse[fac2]*porosite[fac2] ) *
        ( surface[fac1] + surface[fac2] );
  if (psc>0)
    flux = psc*inco[fac3];
  else
    flux = psc*inco[fac4];
  flux3_4 = -flux;
// On calcule le flux convectif entre les volumes de controle associes a fac1 et fac2:
  psc = 0.25 * ( dt_vitesse[fac3]*porosite[fac3] +
                 dt_vitesse[fac4]*porosite[fac4] ) *
        ( surface[fac3] + surface[fac4] );
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
double Eval_Amont_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 786 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
void Eval_Amont_VDF_Face::flux_arete_symetrie (const DoubleTab & , int , int , int , int , DoubleVect &) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1517 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1676 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    for (k=0; k<flux3.size(); k++)
      flux3(k) = -inco(fac3,k)*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac1,k);
  else
    for (k=0; k<flux1_2.size(); k++)
      flux1_2(k) = -psc*inco(fac2,k);
}
void Eval_Amont_VDF_Face::flux_arete_symetrie_fluide (const DoubleTab & inco, int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 923 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord_sym(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double flux,psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)>0)
    flux=inco[fac3]*psc ;
  else
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord_sym(inco,inconnue->temps(),rang2,ori,la_zcl))* psc ;
      /*
      double flux2 = 0.5*(Champ_Face_get_val_imp_face_bord_sym(inconnue->valeurs(),inconnue->temps(),rang1,ori,la_zcl)
                  +  Champ_Face_get_val_imp_face_bord_sym(inconnue->valeurs(),inconnue->temps(),rang2,ori,la_zcl))* psc ;
      if ( !(flux == flux2))
      {
      Cerr<<"iii" << flux<<" "<<flux2<<finl;
      }
      */
    }
  flux3 =  -flux;
// Calcul de flux1_2:
  psc = 0.5*dt_vitesse(fac3)*surface(fac3)*porosite(fac3);
  if (psc>0)
    flux = psc*inco[fac1];
  else
    flux = psc*inco[fac2];
  flux1_2 = -flux;
}
void Eval_Amont_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Face.
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1784 of file Eval_Amont_VDF_Face.h.
{
  ;
}
double Eval_Amont_VDF_Face::flux_arete_symetrie_paroi (const DoubleTab & , int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1040 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
double Eval_Amont_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int , int fac1, int fac2) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 810 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  double flux;
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2]) *
               (surface[fac1]+surface[fac2]);
  if (psc>0)
    flux = psc * inco[fac1]*porosite[fac1];
  else
    flux = psc * inco[fac2]*porosite[fac2];
  return -flux;
}
void Eval_Amont_VDF_Face::flux_fa7_elem (const DoubleTab & inco, int , int fac1, int fac2, DoubleVect & flux) const [inline]
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1541 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = 0.25 * (dt_vitesse[fac1]+dt_vitesse[fac2])*
               (surface[fac1]+surface[fac2]);
  if (psc>0)
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac1,k)*porosite[fac1];
  else
    for (k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(fac2,k)*porosite[fac2];
}
void Eval_Amont_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< (elem2 != -1)
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 1593 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  int k;
  if (elem1 != -1)
    if (psc > 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k)*porosite[face];
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
  else //!< (elem2 != -1)
    if (psc < 0)
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*inco(face,k)*porosite[face];
    else
      for (k=0; k<flux.size(); k++)
        flux(k) = -psc*la_cl.val_ext(face-num1,k);
}
double Eval_Amont_VDF_Face::flux_fa7_sortie_libre (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< (elem2 != -1)
Reimplemented in Eval_Quick_VDF_Face.
Definition at line 854 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  double psc = dt_vitesse[face]*surface(face);
  int elem1 = elem_(face,0);
  if (elem1 != -1)
    if (psc > 0)
      flux = psc*inco[face]*porosite[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  else //!< (elem2 != -1)
    if (psc < 0)
      flux = psc*inco[face]*porosite[face];
    else
      flux = psc*la_cl.val_ext(face-num1,orientation(face));
  return -flux;
}
void Eval_Amont_VDF_Face::secmem_arete_coin_fluide (int fac1, int , int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1186 of file Eval_Amont_VDF_Face.h.
References Cerr, Process::exit(), and finl.
{
  Cerr << "ToDo: code like Eval_Amont_VDF_Face::secmem_arete_coin_fluide for a scalar inco" <<finl;
  Process::exit();
}
void Eval_Amont_VDF_Face::secmem_arete_coin_fluide (int fac1, int , int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 458 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double psc;
// Calcul de flux3:
  psc = 0.5*dt_vitesse[fac1]*porosite[fac1]*surface(fac1);
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int ori = orientation(fac3);
      flux3 = - Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl) * psc ;
    }
  else
    {
      flux3 = 0;
    }
  flux1_2 = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_fluide (int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1157 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc;
  int k;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         + Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
  else
    for (k=0; k<flux3.size(); k++)
      flux3(k) = 0;
  for (k=0; k<flux1_2.size(); k++)
    flux1_2(k) = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_fluide (int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 431 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux3 = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                    + Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  else
    {
      flux3 = 0;
    }
  flux1_2 = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_interne (int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1243 of file Eval_Amont_VDF_Face.h.
{
  ;
}
double Eval_Amont_VDF_Face::secmem_arete_interne (int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 524 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
double Eval_Amont_VDF_Face::secmem_arete_mixte (int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 577 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
void Eval_Amont_VDF_Face::secmem_arete_mixte (int , int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1298 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::secmem_arete_paroi (int , int , int , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1326 of file Eval_Amont_VDF_Face.h.
{
  ;
}
double Eval_Amont_VDF_Face::secmem_arete_paroi (int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 605 of file Eval_Amont_VDF_Face.h.
References Cerr, and finl.
{
  Cerr << " dans secmem_arete_paroi de la convection " << finl;
  return 0;
}
void Eval_Amont_VDF_Face::secmem_arete_paroi_fluide (int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1409 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
// Calcul de flux3
  int k;
  double psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                        dt_vitesse[fac2]*porosite[fac2] )  *
                       (surface(fac1) + surface(fac2))  );
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
  else
    for (k=0; k<flux3.size(); k++)
      flux3(k) = 0;
  for (k=0; k<flux1_2.size(); k++)
    flux1_2(k) = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_paroi_fluide (int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 682 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double psc;
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux3 = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                    +  Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  else
    flux3 = 0;
  flux1_2 = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_periodicite (int , int , int , int , DoubleVect & , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1508 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::secmem_arete_periodicite (int fac1, int fac2, int fac3, int fac4, double & flux3_4, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 776 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::secmem_arete_symetrie (int , int , int , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1533 of file Eval_Amont_VDF_Face.h.
{
  ;
}
double Eval_Amont_VDF_Face::secmem_arete_symetrie (int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 802 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
void Eval_Amont_VDF_Face::secmem_arete_symetrie_fluide (int fac1, int fac2, int fac3, int signe, double & flux3, double & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1009 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, and Evaluateur_VDF::surface.
{
  double psc;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      flux3 = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori,la_zcl)
                    + Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori,la_zcl))* psc ;
    }
  else
    {
      flux3 = 0;
    }
  flux1_2 = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_symetrie_fluide (int fac1, int fac2, int fac3, int signe, DoubleVect & flux3, DoubleVect & flux1_2) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1751 of file Eval_Amont_VDF_Face.h.
References Champ_Face_get_val_imp_face_bord(), Eval_Conv_VDF::dt_vitesse, Eval_VDF_Face::inconnue, Evaluateur_VDF::la_zcl, Evaluateur_VDF::orientation, Evaluateur_VDF::porosite, Evaluateur_VDF::premiere_face_bord, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  double psc;
  int k;
// Calcul de flux3:
  psc = 0.25 * ((dt_vitesse[fac1]*porosite[fac1]    +
                 dt_vitesse[fac2]*porosite[fac2] )  *
                (surface(fac1) + surface(fac2))  );
  if ((psc*signe)<0)
    {
      int rang1 = (fac1-premiere_face_bord);
      int rang2 = (fac2-premiere_face_bord);
      int ori = orientation(fac3);
      for (k=0; k<flux3.size(); k++)
        flux3(k) = -0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,k,ori,la_zcl)
                         + Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,k,ori,la_zcl))* psc ;
    }
  else
    for (k=0; k<flux3.size(); k++)
      flux3(k) = 0;
  for (k=0; k<flux1_2.size(); k++)
    flux1_2(k) = 0;
}
void Eval_Amont_VDF_Face::secmem_arete_symetrie_paroi (int , int , int , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1803 of file Eval_Amont_VDF_Face.h.
{
  ;
}
double Eval_Amont_VDF_Face::secmem_arete_symetrie_paroi (int , int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1058 of file Eval_Amont_VDF_Face.h.
{
  return 0.;
}
double Eval_Amont_VDF_Face::secmem_fa7_elem (int , int , int) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 846 of file Eval_Amont_VDF_Face.h.
{
  return 0;
}
void Eval_Amont_VDF_Face::secmem_fa7_elem (int , int , int , DoubleVect & flux) const [inline]
Reimplemented from Eval_VDF_Face.
Definition at line 1584 of file Eval_Amont_VDF_Face.h.
{
  ;
}
void Eval_Amont_VDF_Face::secmem_fa7_sortie_libre (int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< (elem2 != -1)
Reimplemented from Eval_VDF_Face.
Definition at line 1645 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double psc = dt_vitesse[face]*surface(face);
  int i = elem_(face,0);
// int j = elem(face,1);
  int k;
  if (i != -1)
    {
      if (psc < 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
  else   //!< (elem2 != -1)
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
}
double Eval_Amont_VDF_Face::secmem_fa7_sortie_libre (int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< (elem2 != -1)
Reimplemented from Eval_VDF_Face.
Definition at line 897 of file Eval_Amont_VDF_Face.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::orientation, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  double psc = dt_vitesse[face]*surface(face);
  int i = elem_(face,0);
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*la_cl.val_ext(face-num1,orientation(face));
      else
        flux = 0;
    }
  else   //!< (elem2 != -1)
    {
      if (psc > 0)
        flux = psc*la_cl.val_ext(face-num1,orientation(face));
      else
        flux = 0;
    }
  return -flux;
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_Amont_VDF_Face.h