TRUST: Eval_Amont_PolyMAC_Elem Class Reference
Eval_Amont_PolyMAC_Elem Class Reference
class Eval_Amont_PolyMAC_Elem
Evaluateur PolyMAC pour la convection
Le champ convecte est scalaire (Champ_P0_PolyMAC)
Schema de convection Amont
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif pour la methode EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure
dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en
ce qui concerne les termes pour la matrice, par contre pour le second membre nous
procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies
par les conditions limites.
#include <Eval_Amont_PolyMAC_Elem.h>
Public Member Functions
Eval_Amont_PolyMAC_Elem ()
int calculer_flux_faces_echange_externe_impose () const
int calculer_flux_faces_echange_global_impose () const
int calculer_flux_faces_entree_fluide () const
int calculer_flux_faces_paroi () const
int calculer_flux_faces_paroi_adiabatique () const
int calculer_flux_faces_paroi_defilante () const
int calculer_flux_faces_paroi_fixe () const
int calculer_flux_faces_sortie_libre () const
int calculer_flux_faces_symetrie () const
int calculer_flux_faces_periodique () const
int calculer_flux_faces_NSCBC () const
double flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double flux_face (const DoubleTab &, int, const Echange_global_impose &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_face (const DoubleTab &, int, const Symetrie &, int) const
double flux_face (const DoubleTab &, int, const Periodique &, int) const
double flux_face (const DoubleTab &, int, const NSCBC &, int) const
double flux_faces_interne (const DoubleTab &, int) const
void flux_face (const DoubleTab &, int, const Symetrie &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Periodique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Echange_global_impose &, int, DoubleVect &flux) const
void flux_faces_interne (const DoubleTab &, int, DoubleVect &flux) const
void coeffs_face (int, int, const Symetrie &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, double &aii, double &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Periodique &, double &aii, double &ajj) const
void coeffs_face (int, int, const NSCBC &, double &aii, double &ajj) const
void coeffs_faces_interne (int, double &aii, double &ajj) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Echange_global_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Symetrie &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Periodique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const NSCBC &, int) const
double coeffs_faces_interne_bloc_vitesse (const DoubleTab &, int) const
double secmem_face (int, const Symetrie &, int) const
double secmem_face (int, const Neumann_sortie_libre &, int) const
double secmem_face (int, const Dirichlet_entree_fluide &, int) const
double secmem_face (int, const Dirichlet_paroi_fixe &, int) const
double secmem_face (int, const Dirichlet_paroi_defilante &, int) const
double secmem_face (int, const Neumann_paroi_adiabatique &, int) const
double secmem_face (int, const Neumann_paroi &, int) const
double secmem_face (int, int, int, const Echange_externe_impose &, int) const
double secmem_face (int, const Echange_global_impose &, int) const
double secmem_face (int, const Periodique &, int) const
double secmem_face (int, const NSCBC &, int) const
double secmem_faces_interne (int) const
void coeffs_face (int, int, const Symetrie &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Periodique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_faces_interne (int, DoubleVect &aii, DoubleVect &ajj) const
void secmem_face (int, const Symetrie &, int, DoubleVect &) const
void secmem_face (int, const Neumann_sortie_libre &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_entree_fluide &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_fixe &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_defilante &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi_adiabatique &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi &, int, DoubleVect &) const
void secmem_face (int, int, int, const Echange_externe_impose &, int, DoubleVect &) const
void secmem_face (int, const Echange_global_impose &, int, DoubleVect &) const
void secmem_face (int, const Periodique &, int, DoubleVect &) const
void secmem_faces_interne (int, DoubleVect &flux) const
Detailed Description
class Eval_Amont_PolyMAC_Elem
Evaluateur PolyMAC pour la convection
Le champ convecte est scalaire (Champ_P0_PolyMAC)
Schema de convection Amont
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif pour la methode EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure
dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en
ce qui concerne les termes pour la matrice, par contre pour le second membre nous
procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies
par les conditions limites.
See also:
Eval_Conv_PolyMAC
Definition at line 52 of file Eval_Amont_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Eval_Amont_PolyMAC_Elem::Eval_Amont_PolyMAC_Elem () [inline]
Definition at line 204 of file Eval_Amont_PolyMAC_Elem.h.
{
}
Member Function Documentation
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_echange_externe_impose () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 211 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_echange_global_impose () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 220 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_entree_fluide () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 229 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 1;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_NSCBC () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 300 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 1;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 238 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi_adiabatique () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 247 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi_defilante () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 256 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi_fixe () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 265 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_periodique () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 292 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 1;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_sortie_libre () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 274 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 1;
}
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_symetrie () const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 283 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Symetrie & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 759 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Symetrie & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 962 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Neumann_sortie_libre & la_cl, double & aii, double & ajj) const [inline, virtual]
< j != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 659 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        {
          aii = psc;
          ajj = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          ajj = -psc;
          aii = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Echange_global_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1397 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1369 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1342 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Neumann_sortie_libre & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
< j != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1067 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), and Evaluateur_PolyMAC::surface.
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = psc;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
      else
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = -psc;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
      else
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
< j != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1174 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), and Evaluateur_PolyMAC::surface.
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = psc;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
      else
        {
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = -psc;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
      else
        {
          for(k=0; k<ajj.size(); k++)
            ajj(k) = 0;
          for(k=0; k<aii.size(); k++)
            aii(k) = 0;
        }
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, double & aii, double & ajj) const [inline, virtual]
< j != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 345 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (i != -1)
    {
      if (psc > 0)
        {
          aii = psc;
          ajj = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
  else   //!< j != -1
    {
      if (psc<0)
        {
          ajj = -psc;
          aii = 0;
        }
      else
        {
          aii = 0;
          ajj = 0;
        }
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1260 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1288 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 481 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1315 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 449 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 607 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Periodique & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 999 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, DoubleVect::size(), and Evaluateur_PolyMAC::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
// int i = elem(face,0);
// int j = elem(face,1);
  if (psc > 0)
    {
      for(k=0; k<aii.size(); k++)
        aii(k) = psc;
      for(k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for(k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for(k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 576 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 513 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Echange_global_impose & , double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 544 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Periodique & la_cl, double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 797 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
// int i = elem(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (psc > 0)
    {
      aii = psc;
      ajj = 0;
    }
  else
    {
      ajj = -psc;
      aii = 0;
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const NSCBC & la_cl, double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 855 of file Eval_Amont_PolyMAC_Elem.h.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Eval_Amont_PolyMAC_Elem::coeffs_face n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline, virtual]
< n1 != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 380 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = surface[face]*porosite[face];
  double flux;
  double val_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (dt_vitesse[face] > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_imp;
    }
  else   //!< n1 != -1
    {
      if (dt_vitesse[face]>0)
        flux = psc*val_imp;
      else
        flux = psc*inco[n1];
    }
  return flux;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 454 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 486 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 518 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Echange_global_impose & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 549 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 581 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 612 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline, virtual]
< n1 != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 694 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = surface(face)*porosite(face);
  double val_ext = la_cl.val_ext(face-num1);
  if (n0 != -1)
    {
      if (dt_vitesse[face] > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_ext;
    }
  else   //!< n1 != -1
    {
      if (dt_vitesse[face] > 0)
        flux = psc*val_ext;
      else
        flux = psc*inco[n1];
    }
  return flux;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Symetrie & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 764 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 816 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
  double psc = surface(face)*porosite(face);
  double flux;
  if (dt_vitesse[face] > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return flux;
}
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const NSCBC & la_cl, int num1) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 863 of file Eval_Amont_PolyMAC_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0.;
  Cerr<<"Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
void Eval_Amont_PolyMAC_Elem::coeffs_faces_interne (int face, DoubleVect & aii, DoubleVect & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1433 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, DoubleVect::size(), and Evaluateur_PolyMAC::surface.
{
  int k;
// int i = elem(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (psc > 0)
    {
      for(k=0; k<aii.size(); k++)
        aii(k) = psc;
      for(k=0; k<ajj.size(); k++)
        ajj(k) = 0;
    }
  else
    {
      for(k=0; k<ajj.size(); k++)
        ajj(k) = -psc;
      for(k=0; k<aii.size(); k++)
        aii(k) = 0;
    }
}
void Eval_Amont_PolyMAC_Elem::coeffs_faces_interne (int face, double & aii, double & ajj) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 906 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
// int i = elem(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (psc > 0)
    {
      aii = psc;
      ajj = 0;
    }
  else
    {
      ajj = -psc;
      aii = 0;
    }
}
double Eval_Amont_PolyMAC_Elem::coeffs_faces_interne_bloc_vitesse (const DoubleTab & inco, int face) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 923 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
  double psc = surface(face)*porosite(face);
  double flux;
  if (dt_vitesse[face] > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return flux;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 535 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1359 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1387 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 567 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 750 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 598 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline, virtual]
< n1 != -1
Implements Eval_PolyMAC_Elem.
Definition at line 629 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double val_ext = la_cl.val_ext(face-num1);
  if (n0 != -1)
    {
      if (psc > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_ext;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        flux = psc*val_ext;
      else
        flux = psc*inco[n1];
    }
  return -flux;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 782 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double flux;
  if (psc > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return -flux;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const NSCBC & la_cl, int num1) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 842 of file Eval_Amont_PolyMAC_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0.;
  Cerr<<"Eval_Amont_PolyMAC_Elem::flux_face n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 952 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline, virtual]
< n1 != -1
Implements Eval_PolyMAC_Elem.
Definition at line 313 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  double flux;
  double val_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (psc > 0)
        flux = psc*inco[n0];
      else
        flux = psc*val_imp;
    }
  else   //!< n1 != -1
    {
      if (psc>0)
        flux = psc*val_imp;
      else
        flux = psc*inco[n1];
    }
  return -flux;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int num1, DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 979 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), and Evaluateur_PolyMAC::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int elem1 = elem_(face,0);
  int elem2 = elem_(face,1);
  if (psc > 0)
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(elem1,k);
  else
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(elem2,k);
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 472 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1277 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline, virtual]
< n1 != -1
Implements Eval_PolyMAC_Elem.
Definition at line 1143 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (n0 != -1)
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
    }
  else   //!< n1 != -1
    {
      if (psc>0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline, virtual]
< n1 != -1
Implements Eval_PolyMAC_Elem.
Definition at line 1036 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1332 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1305 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1250 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 440 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 504 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 1414 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), and Evaluateur_PolyMAC::surface.
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (psc > 0)
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(n0,k);
  else
    for(k=0; k<flux.size(); k++)
      flux(k) = -psc*inco(n1,k);
}
double Eval_Amont_PolyMAC_Elem::flux_faces_interne (const DoubleTab & inco, int face) const [inline, virtual]
Implements Eval_PolyMAC_Elem.
Definition at line 892 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
{
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double flux;
  if (psc > 0)
    flux = psc*inco(elem_(face,0));
  else
    flux = psc*inco(elem_(face,1));
  return -flux;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Periodique & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1026 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1350 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1268 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 495 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int face, const NSCBC & la_cl, int num1) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 876 of file Eval_Amont_PolyMAC_Elem.h.
References Cerr, Process::exit(), and finl.
{
  double flux=0;
  Cerr<<"Eval_Amont_PolyMAC_Elem::secmem_face n'est pas encore codee"<<finl;
  Cerr<<"pour la condition NSCBC"<<finl;
  Process::exit();
  return -flux;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Symetrie & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 970 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 590 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Echange_global_impose & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 558 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Symetrie & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 773 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 527 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline, virtual]
< n1 != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1114 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline, virtual]
< n1 != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1220 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, DoubleVect::size(), Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1,k);
      else
        for(k=0; k<flux.size(); k++)
          flux(k) = 0;
    }
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1323 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline, virtual]
< j != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 412 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  double flux;
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*la_cl.val_imp(face-num1);
      else
        flux = 0;
    }
  else   //!< j != -1
    {
      if (psc>0)
        flux = psc*la_cl.val_imp(face-num1);
      else
        flux = 0;
    }
  return -flux;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1) const [inline, virtual]
< n1 != -1
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 724 of file Eval_Amont_PolyMAC_Elem.h.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
{
  double flux;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*la_cl.val_ext(face-num1);
      else
        flux = 0;
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        flux = psc*la_cl.val_ext(face-num1);
      else
        flux = 0;
    }
  return -flux;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 463 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Periodique & la_cl, int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 831 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1296 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1377 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Echange_global_impose & , int , DoubleVect &) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1405 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 621 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
void Eval_Amont_PolyMAC_Elem::secmem_faces_interne (int , DoubleVect & flux) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 1458 of file Eval_Amont_PolyMAC_Elem.h.
{
  ;
}
double Eval_Amont_PolyMAC_Elem::secmem_faces_interne (int) const [inline, virtual]
Reimplemented from Eval_PolyMAC_Elem.
Definition at line 937 of file Eval_Amont_PolyMAC_Elem.h.
{
  return 0;
}
The documentation for this class was generated from the following file:
src/PolyMAC/Operateurs/Conv_iterateur/Eval_Amont_PolyMAC_Elem.h