TRUST: Champ_base Class Reference
Champ_base Class Reference abstract
classe Champ_base
Cette classe est la base de la hierarchie des champs.
Ses membres sont les attributs et les methodes communs
a toutes les classes qui representent des champs.
Champ_base derive de Champ_Proto, afin d'avoir une interface conforme
a tous les champs, et d'heriter des operations courantes sur les
Champs.
Un champ possede un nom, une unite et des valeurs.
#include <Champ_base.h>
Public Member Functions
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_base
Cette classe est la base de la hierarchie des champs.
Ses membres sont les attributs et les methodes communs
a toutes les classes qui representent des champs.
Champ_base derive de Champ_Proto, afin d'avoir une interface conforme
a tous les champs, et d'heriter des operations courantes sur les
Champs.
Un champ possede un nom, une unite et des valeurs.
Definition at line 49 of file Champ_base.h.
Constructor & Destructor Documentation
~Champ_base()
Champ_base::~Champ_base () override
Definition at line 32 of file Champ_base.cpp.
Champ_base()
Champ_base::Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
< Par defaut, champ scalaire
Definition at line 93 of file Champ_base.cpp.
{
  changer_temps(0.);
  fixer_unite(".");
  nommer("anonyme");
  fixer_nature_du_champ(scalaire);
  nb_compo_ = 1; //!< Par defaut, champ scalaire
}
References changer_temps(), Field_base::fixer_nature_du_champ(), Field_base::fixer_unite(), Field_base::nb_compo_, Field_base::nommer(), and scalaire.
Member Function Documentation
a_une_zone_dis_base()
virtual int Champ_base::a_une_zone_dis_base () const inline virtual
Par defaut, on ne sait pas si une zone_dis_base sera definie.
Reimplemented in Champ_Fonc_base, and Champ_Inc_base.
Definition at line 76 of file Champ_base.h.
Referenced by Champ_implementation_P0::affecter_(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), and Champ_Generique_Transformation::completer().
abortTimeStep()
void Champ_base::abortTimeStep () virtual
Reimplemented in Champ_P1NC.
Definition at line 458 of file Champ_base.cpp.
{
}
affecter()
Champ_base & Champ_base::affecter (const Champ_base & ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
Returns
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Definition at line 476 of file Champ_base.cpp.
{
  affecter_(ch);
  valeurs().echange_espace_virtuel();
  return *this;
}
References affecter_(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), and Champ_Proto::valeurs().
Referenced by Champ::affecter(), TRUSTChamp_Divers_generique< _TYPE_ >::affecter(), Champ_Don::affecter_(), Op_Grad_EF::associer(), Source_PDF_EF::associer_pb(), Interpolation_IBM_hybrid::discretise(), Interpolation_IBM_elem_fluid::discretise(), Interpolation_IBM_mean_gradient::discretise(), Diametre_hyd_champ::interpreter(), Porosites_champ::interpreter(), Terme_Puissance_Thermique::lire_donnees(), Terme_Puissance_Thermique::mettre_a_jour(), Source_Scalaire_EF::readOn(), and Source_PDF_base::updateChampRho().
affecter_()
virtual Champ_base & Champ_base::affecter_ (const Champ_base &) pure virtual
Implemented in Champ_Fonc_Tabule, Ch_input_uniforme, Champ_Fonc_P0_base, Champ_Inc_P0_base, Champ_Don_base, Champ_Fonc_base, Champ_Inc_base, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Fonc_Face_PolyMAC, Champ_Ostwald, Champ_Face, Champ_Fonc_Face, Champ_P1NC, Champ_Uniforme, Champ_Uniforme_Morceaux, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, and Champ_Fonc_Elem_PolyMAC.
Referenced by affecter(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), and Loi_Etat_rhoT_GP_QC::initialiser_rho().
affecter_compo()
virtual Champ_base & Champ_base::affecter_compo (const Champ_base & , int compo) pure virtual
Implemented in Champ_Fonc_base, Champ_Inc_base, and Champ_Don_base.
Referenced by Champ::affecter_compo().
affecter_erreur()
void Champ_base::affecter_erreur ()
Definition at line 485 of file Champ_base.cpp.
{
  Nom message;
  message ="The method ";
  message += que_suis_je();
  message += "::affecter has no sense.\n";
  message += "TRUST has caused an error and will stop.\nUnexpected error during TRUST calculation.";
  Process::exit(message);
}
References Process::exit(), message(), and Objet_U::que_suis_je().
Referenced by TRUSTChamp_Divers_generique< _TYPE_ >::affecter(), and TRUSTChamp_Don_generique< _TYPE_ >::affecter().
associer_zone_dis_base()
void Champ_base::associer_zone_dis_base (const Zone_dis_base & zone_dis) virtual
Reimplemented in Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Champ_Fonc_Tabule, Champ_Fonc_P0_base, Champ_Fonc_MED, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Elem_PolyMAC, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Som_PolyMAC, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_P0_VDF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_input_P0, Champ_Ostwald, Champ_Ostwald_VDF, and Champ_Ostwald_VEF.
Definition at line 1126 of file Champ_base.cpp.
{
  Cerr << "Error in Champ_base::associer_zone_dis_base\n";
  Cerr << " (field name : " << le_nom() << ")\n";
  Cerr << " The method " << que_suis_je();
  Cerr << "::associer_zone_dis_base is not coded\n";
  Cerr << " or the field does not possess a zone_dis_base." << finl;
  exit();
}
References Cerr, Process::exit(), finl, Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Champ_Fonc::associer_zone_dis_base(), Champ_Inc::associer_zone_dis_base(), Discretisation_base::champ_fixer_membres_communs(), Champ_Fonc_MED::creer(), and Champ_Fonc_MED_Table_Temps::lire_donnees_champ().
calculer_valeurs_elem_compo_post()
int Champ_base::calculer_valeurs_elem_compo_post (DoubleTab & valeurs, int ncomp, int nbelem, Nom & nom_post, const Domaine & dom) const
Definition at line 597 of file Champ_base.cpp.
{
  const Zone& zone=dom.zone(0);
// nom_post=nom_compo(ncomp);
  Nom nom_dom=dom.le_nom();
  Nom nom_dom_inc= dom.le_nom();
  if(sub_type(Champ_Inc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Inc_base, *this).domaine().le_nom();
    }
  else if(sub_type(Champ_Fonc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Fonc_base, *this).domaine().le_nom();
    }
  int nb_elem_PE = mppartial_sum(nb_elem);
  DoubleTab centres_de_gravites(nb_elem, dimension);
  les_valeurs.resize(nb_elem);
  if(nom_dom==nom_dom_inc)
    {
      if(sub_type(Champ_Inc_base, *this) )
        {
          const Zone_VF& zvf = ref_cast(Zone_VF,ref_cast(Champ_Inc_base, *this).equation().zone_dis().valeur());
// Pour eviter un resize par nb_elem_tot par appel a xp()
          for (int i=0; i<nb_elem; i++)
            for (int k=0; k<dimension; k++)
              centres_de_gravites(i,k) = zvf.xp(i,k);
        }
      else
        zone.calculer_centres_gravite(centres_de_gravites);
      IntVect les_polys(nb_elem);
      {
        for(int elem=0; elem<nb_elem; elem++)
          {
            les_polys(elem)=elem;
          }
      }
      valeur_aux_elems_compo(centres_de_gravites, les_polys, les_valeurs, ncomp);
    }
  else
    {
      zone.calculer_centres_gravite(centres_de_gravites);
      valeur_aux_compo(centres_de_gravites, les_valeurs, ncomp);
    }
  nom_post+= Nom("_elem_");
  nom_post+= nom_dom;
//
  return nb_elem_PE;
}
References Zone::calculer_centres_gravite(), Objet_U::dimension, Domaine::le_nom(), mppartial_sum(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, valeur(), valeur_aux_compo(), valeur_aux_elems_compo(), Zone_VF::xp(), and Domaine::zone().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
calculer_valeurs_elem_post()
int Champ_base::calculer_valeurs_elem_post (DoubleTab & valeurs, int nbelem, Nom & nom_post, const Domaine & dom) const
Definition at line 535 of file Champ_base.cpp.
{
  const Zone& zone=dom.zone(0);
// nom_post=le_nom();
  Nom nom_dom=dom.le_nom();
  Nom nom_dom_inc= dom.le_nom();
  if(sub_type(Champ_Inc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Inc_base, *this).domaine().le_nom();
    }
  else if(sub_type(Champ_Fonc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Fonc_base, *this).domaine().le_nom();
    }
  int nb_elem_PE = mppartial_sum(nb_elem);
  DoubleTab centres_de_gravites(nb_elem, dimension);
  les_valeurs.resize(nb_elem, nb_compo_);
  if(nom_dom==nom_dom_inc)
    {
      if(sub_type(Champ_Inc_base, *this) )
        {
          const Zone_VF& zvf = ref_cast(Zone_VF,ref_cast(Champ_Inc_base, *this).zone_dis_base());
// Pour eviter un resize par nb_elem_tot par appel a xp()
          for (int i=0; i<nb_elem; i++)
            for (int k=0; k<dimension ; k++)
              centres_de_gravites(i,k) = zvf.xp(i,k);
        }
      else
        zone.calculer_centres_gravite(centres_de_gravites);
      valeur_aux_centres_de_gravite(centres_de_gravites,les_valeurs);
    }
  else
    {
      zone.calculer_centres_gravite(centres_de_gravites);
      valeur_aux(centres_de_gravites, les_valeurs);
    }
  if((axi) && (nb_compo_==dimension))
    {
      double teta, vR, vT;
      for (int num_elem=0; num_elem<nb_elem; num_elem++)
        {
          teta = centres_de_gravites(num_elem,1);
          vR=les_valeurs(num_elem, 0);
          vT=les_valeurs(num_elem, 1);
          les_valeurs(num_elem, 0) =vR*cos(teta)-vT*sin(teta);
          les_valeurs(num_elem, 1) =vR*sin(teta)+vT*cos(teta);
        }
    }
  nom_post+= Nom("_elem_");
  nom_post+= nom_dom;
  return nb_elem_PE;
}
References Objet_U::axi, Zone::calculer_centres_gravite(), Objet_U::dimension, Domaine::le_nom(), mppartial_sum(), Field_base::nb_compo_, ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, valeur_aux(), valeur_aux_centres_de_gravite(), Zone_VF::xp(), Domaine::zone(), and zone_dis_base().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
calculer_valeurs_som_compo_post()
int Champ_base::calculer_valeurs_som_compo_post (DoubleTab & valeurs, int ncomp, int nbsom, Nom & nom_post, const Domaine & dom, int appliquer_cl = 0) const
< GF je ne suis pas sur de l'assert c'est pour voir
Definition at line 945 of file Champ_base.cpp.
{
  Nom nom_dom=dom.le_nom();
  Nom nom_dom_inc= dom.le_nom();
  int nb_som_PE = mppartial_sum(nb_som);
  if(sub_type(Champ_Inc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Inc_base, *this).domaine().le_nom();
    }
  else if(sub_type(Champ_Fonc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Fonc_base, *this).domaine().le_nom();
    }
  const DoubleTab& coord_sommets=dom.coord_sommets() ;
  les_valeurs.resize(nb_som);
  if(nom_dom==nom_dom_inc)
    {
      valeur_aux_sommets_compo(dom,les_valeurs, ncomp);
    }
  else
    {
      valeur_aux_compo(coord_sommets, les_valeurs, ncomp);
    }
// int impose_cl_diri=1;
  {
    char* theValue = getenv("TRUST_POST_SOM_NO_DIRICHLET");
    if (theValue != NULL)
      {
        appliquer_cl=0;
      }
  }
  if (appliquer_cl)
    {
// Liste des sommets de bord au contact d'une face de Dirichlet:
// Prise en compte des conditions aux limites :
      if (sub_type(Champ_Inc_base, *this))
        {
          const Champ_Inc_base& chi=ref_cast(Champ_Inc_base, *this);
          const Equation_base& eqn=chi.equation();
          if((eqn.inconnue().le_nom() == le_nom())
              && (sub_type(Champ_Inc_base, *this))
              && (dom==(ref_cast(Champ_Inc_base, *this).equation().probleme().domaine() ) ) )
            {
              IntTab compteur(dom.nb_som());
              compteur = 0;
              int num_cl;
              const Zone_Cl_dis& zcl=eqn.zone_Cl_dis();
              int nb_cond_lim=zcl.nb_cond_lim();
              for (num_cl=0; num_cl<nb_cond_lim; num_cl++)
                {
                  const Cond_lim& la_cl=zcl.les_conditions_limites(num_cl);
                  const Frontiere_dis_base& frontiere_dis=la_cl->frontiere_dis();
                  const Frontiere& frontiere=frontiere_dis.frontiere();
                  const Faces& faces=frontiere.faces();
                  int nb_faces=faces.nb_faces_tot();
                  int nb_som_faces=faces.nb_som_faces();
                  if(sub_type(Dirichlet, la_cl.valeur()))
                    {
                      const Dirichlet& diri=ref_cast(Dirichlet, la_cl.valeur());
                      for(int num_face=0; num_face<nb_faces ; num_face++)
{
                          for(int num_som=0; num_som<nb_som_faces; num_som++)
{
                              int sommet=faces.sommet(num_face, num_som);
                              if (compteur(sommet) == 0)
                                les_valeurs(sommet) = 0;
                              les_valeurs(sommet) += diri.val_imp(num_face,ncomp);
                              compteur(sommet) += 1;
                            }
                        }
                    }
                  else if(sub_type(Dirichlet_homogene, la_cl.valeur()))
                    {
                      const Dirichlet_homogene& diri=ref_cast(Dirichlet_homogene, la_cl.valeur());
                      for(int num_face=0; num_face<nb_faces ; num_face++)
{
                          for(int num_som=0; num_som<nb_som_faces; num_som++)
{
                              int sommet=faces.sommet(num_face, num_som);
                              les_valeurs(sommet) = diri.val_imp(num_face,ncomp);
                              compteur(sommet) += 1;
                            }
                        }
                    }
                }
// Ajoute la contribution des autres processeurs a les_valeurs et compteur
              add_sommets_communs(dom, les_valeurs, compteur);
// On termine le calcul de la moyenne pour les cas qui ont ete modifies
// par une condition de type Dirichlet
              int nb_som_l = dom.nb_som();
              assert (nb_som==nb_som_l); //!< GF je ne suis pas sur de l'assert c'est pour voir
              for (int sommet = 0; sommet<nb_som_l; sommet++)
                if (compteur(sommet) != 0)
                  les_valeurs(sommet) /= compteur(sommet);
            }
        }
    }
  nom_post+= Nom("_som_");
  nom_post+= nom_dom;
  return  nb_som_PE;
}
References add_sommets_communs(), compteur, Domaine::coord_sommets(), MorEqn::equation(), Frontiere::faces(), Frontiere_dis_base::frontiere(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), Field_base::le_nom(), Domaine::le_nom(), O_U_Ptr::le_nom(), Zone_Cl_dis::les_conditions_limites(), mppartial_sum(), Zone_Cl_dis::nb_cond_lim(), Faces::nb_faces_tot(), Domaine::nb_som(), Faces::nb_som_faces(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), sub_type, Dirichlet::val_imp(), Dirichlet_homogene::val_imp(), Deriv_Cond_lim_base::valeur(), valeur_aux_compo(), valeur_aux_sommets_compo(), and Equation_base::zone_Cl_dis().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
calculer_valeurs_som_post()
int Champ_base::calculer_valeurs_som_post (DoubleTab & valeurs, int nbsom, Nom & nom_post, const Domaine & dom) const
< Sommet reel
Definition at line 746 of file Champ_base.cpp.
{
  Nom nom_dom=dom.le_nom();
  Nom nom_dom_inc= dom.le_nom();
  if(sub_type(Champ_Inc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Inc_base, *this).domaine().le_nom();
    }
  else if(sub_type(Champ_Fonc_base, *this) )
    {
      nom_dom_inc=ref_cast(Champ_Fonc_base, *this).domaine().le_nom();
    }
  int nb_som_PE = mppartial_sum(nb_som);
  const DoubleTab& coord_sommets=dom.coord_sommets() ;
  les_valeurs.resize(nb_som, nb_compo_);
  if(nom_dom==nom_dom_inc)
    {
      valeur_aux_sommets(dom,les_valeurs);
    }
  else
    {
      valeur_aux(coord_sommets, les_valeurs);
    }
  int old_traitement_symetrie=0;
  {
    char* theValue = getenv("TRUST_POST_SOM_SYMETRIE_ERREUR");
    if (theValue != NULL)
      {
        Cerr<<"results depend on order of bc or faces in bc ..."<<finl;
        old_traitement_symetrie=1;
      }
  }
  int impose_cl_diri=1;
  {
    char* theValue = getenv("TRUST_POST_SOM_NO_DIRICHLET");
    if (theValue != NULL)
      {
        impose_cl_diri=0;
      }
  }
// Prise en compte des conditions aux limites :
  if (sub_type(Champ_Inc_base, *this)&&impose_cl_diri)
    {
      const Champ_Inc_base& chi=ref_cast(Champ_Inc_base, *this);
      if (!chi.mon_equation_non_nul())
        {
          Cerr<<"no equation assocuate to "<<que_suis_je()<<finl;
          impose_cl_diri=0;
        }
    }
  if (sub_type(Champ_Inc_base, *this)&&impose_cl_diri)
    {
      const Champ_Inc_base& chi=ref_cast(Champ_Inc_base, *this);
      const Equation_base& eqn=chi.equation();
// GF on ne veut pas prendre en compte les CL en EF
      if (eqn.discretisation().que_suis_je()!="EF")
        if((eqn.inconnue().le_nom() == le_nom())
            && (sub_type(Champ_Inc_base, *this))
            && (dom==(ref_cast(Champ_Inc_base, *this).equation().probleme().domaine() ) ) )
          {
            IntTab compteur(dom.nb_som());
            compteur = 0;
            const Zone_Cl_dis& zcl=eqn.zone_Cl_dis();
            int nb_cond_lim=zcl.nb_cond_lim(),num_cl;
            for (num_cl=0; num_cl<nb_cond_lim; num_cl++)
              {
                const Cond_lim& la_cl=zcl.les_conditions_limites(num_cl);
                const Frontiere_dis_base& frontiere_dis=la_cl->frontiere_dis();
                const Frontiere& frontiere=frontiere_dis.frontiere();
                const Faces& faces=frontiere.faces();
// modif bm: les faces frontieres ont maintenant des faces virtuelles,
// il ne faut pas boucler sur les faces virtuelles (ancien code: nb_faces_tot())
                int nb_faces=faces.nb_faces();
                int nb_som_faces=faces.nb_som_faces();
                if(sub_type(Dirichlet, la_cl.valeur()))
                  {
                    const Dirichlet& diri=ref_cast(Dirichlet, la_cl.valeur());
                    for(int num_face=0; num_face<nb_faces ; num_face++)
                      for(int num_som=0; num_som<nb_som_faces; num_som++)
{
                          int sommet=faces.sommet(num_face, num_som);
                          for(int compo=0; compo<nb_compo_; compo++)
{
                              if (compteur(sommet) == 0)
                                les_valeurs(sommet, compo) = 0;
                              les_valeurs(sommet, compo) += diri.val_imp(num_face, compo);
                            }
                          compteur(sommet) += 1;
                        }
                  }
                else if(sub_type(Dirichlet_homogene, la_cl.valeur()))
                  {
                    for(int num_face=0; num_face<nb_faces ; num_face++)
                      for(int num_som=0; num_som<nb_som_faces; num_som++)
{
                          int sommet=faces.sommet(num_face, num_som);
                          for(int compo=0; compo<nb_compo_; compo++)
{
                              if (compteur(sommet) == 0)
                                les_valeurs(sommet, compo) = 0;
                              les_valeurs(sommet, compo) += 0;
                            }
                          compteur(sommet) += 1;
                        }
                  }
                else if((sub_type(Symetrie, la_cl.valeur()))&&old_traitement_symetrie)
                  {
                    if(nb_compo_==dimension)
                      {
                        ArrOfDouble normale(dimension);
                        DoubleTab delta(dimension-1,dimension);
                        int nb_faces_tot=faces.nb_faces_tot();
                        for(int num_face=0; num_face<nb_faces_tot ; num_face++)
{
// calcul de la normale :
                            int sommet0=faces.sommet(num_face, 0);
                            for (int k=1; k<dimension; k++)
{
                                int sommet=faces.sommet(num_face, k);
                                for(int compo=0; compo<dimension; compo++)
                                  delta(k-1,compo)=coord_sommets(sommet,compo)-coord_sommets(sommet0,compo);
                              }
                            if(dimension==2)
{
                                normale[0]=-delta(0,1);
                                normale[1]=delta(0,0);
                              }
                            else if(dimension==3)
{
                                normale[0]=delta(0,1)*delta(1,2) - delta(0,2)*delta(1,1);
                                normale[1]=delta(0,2)*delta(1,0) - delta(0,0)*delta(1,2);
                                normale[2]=delta(0,0)*delta(1,1) - delta(0,1)*delta(1,0);
                              }
                            else
{
                                Cerr << "We do not know treating the dimension : " << dimension << finl;
                                exit();
                              }
                            normale *= 1. / norme_array(normale);
                            for(int num_som=0; num_som<nb_som_faces; num_som++)
{
                                int sommet=faces.sommet(num_face, num_som);
                                if (sommet<dom.nb_som()) //!< Sommet reel
{
                                    double psc=0;
                                    for(int k=0; k< dimension; k++)
                                      psc+=normale[k]*les_valeurs(sommet,k);
                                    for(int compo=0; compo<nb_compo_; compo++)
                                      les_valeurs(sommet, compo) -= psc*normale[compo];
                                  }
                              }
                          }
                      }
                  }
              }
// Ajoute la contribution des autres processeurs a valeurs et compteur
            add_sommets_communs(dom, les_valeurs, compteur);
// On termine le calcul de la moyenne pour les cas qui ont ete modifies
// par une condition de type Dirichlet
            int nb_som_l = dom.nb_som();
// assert (nb_som_l==nb_som_l); // GF je ne suis pas sur de l'assert c'est pour voir
            for (int sommet = 0; sommet<nb_som_l; sommet++)
              for(int compo=0; compo<nb_compo_; compo++)
                if (compteur(sommet) != 0)
                  les_valeurs(sommet,compo) /= compteur(sommet);
          }
    }
// Prise en compte de l'axi:
  if((axi) && (nb_compo_==dimension))
    {
      double teta, vR, vT;
      for(int sommet=0; sommet<nb_som; sommet++)
        {
          teta = coord_sommets(sommet,1);
          vR=les_valeurs(sommet, 0);
          vT=les_valeurs(sommet, 1);
          les_valeurs(sommet, 0) =vR*cos(teta)-vT*sin(teta);
          les_valeurs(sommet, 1) =vR*sin(teta)+vT*cos(teta);
        }
    }
  nom_post+= Nom("_som_");
  nom_post+= nom_dom;
  return nb_som_PE;
}
References add_sommets_communs(), Objet_U::axi, Cerr, compteur, Domaine::coord_sommets(), Objet_U::dimension, Equation_base::discretisation(), MorEqn::equation(), Process::exit(), Frontiere::faces(), finl, Frontiere_dis_base::frontiere(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), Field_base::le_nom(), Domaine::le_nom(), O_U_Ptr::le_nom(), Zone_Cl_dis::les_conditions_limites(), MorEqn::mon_equation_non_nul(), mppartial_sum(), Field_base::nb_compo_, Zone_Cl_dis::nb_cond_lim(), Faces::nb_faces(), Faces::nb_faces_tot(), Domaine::nb_som(), Faces::nb_som_faces(), norme_array(), Objet_U::que_suis_je(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), sub_type, Dirichlet::val_imp(), Deriv_Cond_lim_base::valeur(), valeur_aux(), valeur_aux_sommets(), and Equation_base::zone_Cl_dis().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
changer_temps()
double Champ_base::changer_temps (const double t) virtual
Fixe le temps auquel se situe le champ.
Returns
double
Signification: le nouveau temps auquel se situe le champ
Contraintes:
Reimplemented in Champ_Inc_base.
Definition at line 1090 of file Champ_base.cpp.
{
  return temps_ = t ;
}
References temps_.
Referenced by Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Champ_base(), Discretisation_base::champ_fixer_membres_communs(), Champ::changer_temps(), Champ_Fonc::changer_temps(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), EF_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), VEF_discretisation::h_conv(), Milieu_base::initialiser(), Milieu_base::mettre_a_jour(), Champ_Don_base::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Loi_Fermeture_Test::mettre_a_jour(), Champ_Ostwald_VDF::mettre_a_jour(), Champ_Ostwald_VEF::mettre_a_jour(), Rotationnel_Champ_P1_EF::mettre_a_jour(), Rotationnel_Champ_Q1_EF::mettre_a_jour(), Champ_Uniforme_inst::mettre_a_jour(), Champ_Uniforme_Morceaux_inst::mettre_a_jour(), Fluide_base::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Critere_Q_Champ_Face::mettre_a_jour(), grad_U_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Rotationnel_Champ_Face::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Y_plus_Champ_Face::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Critere_Q_Champ_P1NC::mettre_a_jour(), grad_T_Champ_P1NC::mettre_a_jour(), grad_U_Champ_P1NC::mettre_a_jour(), h_conv_Champ_P1NC::mettre_a_jour(), Rotationnel_Champ_P1NC::mettre_a_jour(), Rotationnel_Champ_Q1NC::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Y_plus_Champ_P1NC::mettre_a_jour(), VDF_discretisation::modifier_champ_tabule(), VEF_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Champ_Tabule_Temps::readOn(), VDF_discretisation::reynolds_maille(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), and VEF_discretisation::y_plus().
completer()
void Champ_base::completer (const Zone_Cl_dis_base & zcl) virtual
Reimplemented in Champ_Fonc_P1_isoP1Bulle, and Champ_P1_isoP1Bulle.
Definition at line 1072 of file Champ_base.cpp.
{
}
completer_post_champ()
int Champ_base::completer_post_champ (const Domaine & dom, const int axi, const Nom & loc_post, const Nom & le_nom_champ_post, Format_Post_base & format) const virtual
Definition at line 1057 of file Champ_base.cpp.
{
  const Nature_du_champ& la_nature = nature_du_champ();
  const int nb_compo = nb_comp();
  const Noms& noms_composante = noms_compo();
  format.completer_post(dom,is_axi,la_nature,nb_compo,noms_composante,loc_post,le_nom_champ_post);
  return 1;
}
References Format_Post_base::completer_post(), Field_base::nature_du_champ(), Field_base::nb_comp(), and Field_base::noms_compo().
Referenced by Champ_Generique_Statistiques_base::completer_post_statistiques(), and Operateur_Statistique_tps_base::completer_post_statistiques().
corriger_unite_nom_compo()
void Champ_base::corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
Definition at line 498 of file Champ_base.cpp.
{
  if(unite_.size() != nb_compo_)
    {
      Noms& unit=ref_cast_non_const(Noms,unite_);
      Nom nom=unite_[0];
      unit.dimensionner_force(nb_compo_);
      for(int compo=0; compo<nb_compo_; compo++)
        unit[compo] = nom;
    }
  int compo_nommees=(nom_compo(0) != Nom());
  if((!compo_nommees)&&(nb_compo_ != 1))
    {
      Noms ext(nb_compo_);
      if (nb_compo_<=3)
        {
          if(!axi)
            {
              ext[0]=le_nom()+"X";
              if (nb_compo_> 1) ext[1]=le_nom()+"Y";
              if (nb_compo_> 2) ext[2]=le_nom()+"Z";
            }
          else
            {
              ext[0]=le_nom()+"R";
              if (nb_compo_> 1) ext[1]=le_nom()+"teta";
              if (nb_compo_> 2) ext[2]=le_nom()+"Z";
            }
        }
      else for (int c=0; c<nb_compo_; c++)
          ext[c]=le_nom()+"_"+Nom(c);
      Champ_base& ch=ref_cast_non_const(Champ_base,*this);
      ch.fixer_noms_compo(ext);
    }
}
References Objet_U::axi, vect_impl::dimensionner_force(), Field_base::fixer_noms_compo(), Field_base::le_nom(), Field_base::nb_compo_, Field_base::nom_compo(), ref_cast_non_const, vect_impl::size(), and Field_base::unite_.
Referenced by Pb_MED::creer_champ(), Ecrire_Champ_MED::interpreter(), Champ_Generique_refChamp::lire_motcle_non_standard(), and Champ_Fonc_MED::readOn().
fixer_nb_valeurs_nodales()
int Champ_base::fixer_nb_valeurs_nodales (int n) virtual
Reimplemented in Champ_Fonc_P0_base, Champ_Inc_P0_base, Champ_Elem_PolyMAC, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Fonc_Face_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Q1NC, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Don_base, Champ_Fonc_base, Champ_Ostwald, Champ_P1NC, Champ_Inc_base, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, and Champ_Fonc_Q1NC.
Definition at line 1116 of file Champ_base.cpp.
{
  Cerr << "Champ_base::fixer_nb_valeurs_nodales\n ";
  Cerr << que_suis_je() << " does not have nb_valeurs_nodales" << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Discretisation_base::champ_fixer_membres_communs().
get_info()
const Type_info * Champ_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Don_base, Champ_Fonc_base, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Som_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 32 of file Champ_base.cpp.
imprime()
virtual int Champ_base::imprime (Sortie & , int) const pure virtual
Implemented in Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Champ_Fonc_P0_base, Champ_Don_base, Champ_Inc_base, Champ_Elem_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Som_PolyMAC, Champ_Face, Champ_Fonc_P0_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_P0_VEF, Champ_P1NC, Champ_P0_VDF, and Champ_Fonc_Face.
info()
const Type_info * Champ_base::info () static
Definition at line 32 of file Champ_base.cpp.
mettre_a_jour()
void Champ_base::mettre_a_jour (double) virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented in Champ_Fonc_Tabule_Morceaux, Champ_Don_base, Champ_Fonc_base, Champ_Inc_base, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_MED_Tabule, Champ_Ostwald, Champ_Face, Champ_Ostwald_VDF, Champ_Ostwald_VEF, Champ_P1NC, Champ_Elem_PolyMAC_P0, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Tabule, Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Uniforme_inst, Champ_Uniforme_Morceaux_inst, Champ_Fonc_P0_base, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_Fonc_MED, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Fonc_Face, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 454 of file Champ_base.cpp.
{
}
Referenced by Sonde::mettre_a_jour(), and Champ::mettre_a_jour().
nb_valeurs_nodales()
virtual int Champ_base::nb_valeurs_nodales () const inline virtual
Reimplemented in Champ_Don_base, Champ_Inc_base, Champ_Elem_PolyMAC, and Champ_Face_PolyMAC.
Definition at line 59 of file Champ_base.h.
  {
    Cerr<<"We do not have to pass here "<<__FILE__<<(int)__LINE__<<finl;
    exit();
    return -1;
  };
References Cerr, Process::exit(), and finl.
printOn()
Sortie & Champ_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_Don_base, Champ_Fonc_base, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Som_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 49 of file Champ_base.cpp.
{
  return os << le_nom() << finl;
}
References finl, and Field_base::le_nom().
Referenced by Champ_Don_base::printOn(), and Champ_Inc_base::printOn().
readOn()
Entree & Champ_base::readOn (Entree & is) override protected virtual
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Don_base, Champ_Fonc_base, Champ_Inc_base, Champ_Fonc_MED, Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, Champ_Fonc_MED_Tabule, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Elem_PolyMAC, Champ_Elem_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Fonc_Elem_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Som_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Ostwald, Champ_Don_Face_lu, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P0_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_som_lu_VDF, Champ_val_tot_sur_vol_VDF, Correlation_Vec_Sca_VDF, Courant_maille_Champ_Face, Critere_Q_Champ_Face, grad_U_Champ_Face, Reynolds_maille_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_val_tot_sur_vol_VEF, Correlation_Vec_Sca_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 71 of file Champ_base.cpp.
{
  return is >> nom_;
}
References Field_base::nom_.
Referenced by Champ_Don_base::readOn(), and Champ_Inc_base::readOn().
self_cast() [1/2]
const Champ_base & Champ_base::self_cast (const Objet_U & r) static
Definition at line 32 of file Champ_base.cpp.
self_cast() [2/2]
Champ_base & Champ_base::self_cast (Objet_U & r) static
Definition at line 32 of file Champ_base.cpp.
temps()
double Champ_base::temps () const
Renvoie le temps du champ.
Returns
double
Signification: le temps du champ
Contraintes:
Definition at line 1109 of file Champ_base.cpp.
{
  return temps_ ;
}
References temps_.
Referenced by Op_Diff_VDF_Face_Axi_base::ajouter_aretes_bords(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Op_Diff_VDF_Face_Axi_base::contribue_au_second_membre(), Milieu_base::discretiser(), Champ_P1iP1B_implementation::filtrage(), Equation_base::get_champ(), Pb_MED::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Champ_Generique_refChamp::get_time(), Champ_Fonc_Tabule_P0_EF::initialiser(), Champ_Fonc_Tabule_Elem_PolyMAC::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Ecrire_Champ_MED::interpreter(), Champ_Tabule_Temps::me_calculer(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_Inc_base::mettre_a_jour(), Champ_Elem_PolyMAC_P0::mettre_a_jour(), Champ_Fonc_Elem_PolyMAC_P0_rot::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour(), Champ_Fonc_Elem_PolyMAC_P0_TC::mettre_a_jour(), grad_Champ_Face_PolyMAC_P0::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Champ_Don_Fonc_txyz::readOn(), Champ::temps(), Champ_Fonc::temps(), Champ_Inc::temps(), Champ_Face::val_imp_face_bord_private(), and Champ_Inc_base::valeurs().
trace()
DoubleTab & Champ_base::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const virtual
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Returns
DoubleTab&
Signification: les valeurs du champ sur la frontiere au temps tps
Contraintes:
Reimplemented in Champ_Fonc_P0_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_base, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, and Champ_Elem_PolyMAC.
Definition at line 1185 of file Champ_base.cpp.
{
  Cerr << que_suis_je() << "did not overloaded Champ_base::trace" << finl;
  exit();
  return x;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_Generique_Extraction::get_champ(), and Champ_Front_Fonction::mettre_a_jour().
valeur_a()
DoubleVect & Champ_base::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns
reference a "valeurs"
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, champ_init_canal_sinal, Champ_Inc_base, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_MED, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, and Champ_som_lu.
Definition at line 112 of file Champ_base.cpp.
{
// assert(les_valeurs.size() == nb_comp());
  DoubleTrav values(1,les_valeurs.size());
  int taille=pos.size();
  DoubleTrav pos2(1,taille);
  for (int dir=0; dir<taille; dir++) pos2(0,dir)=pos(dir);
  valeur_aux(pos2,values);
  for (int comp=0; comp<les_valeurs.size(); comp++)
    les_valeurs(comp)=values(0,comp);
  return les_valeurs;
}
References TRUSTVect< _TYPE_ >::size(), and valeur_aux().
Referenced by Perte_Charge_Anisotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Directionnelle_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Anisotrope_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Directionnelle_VEF_P1NC::coeffs_perte_charge(), Champ::valeur_a(), valeur_a_compo(), Champ_Fonc_MED::valeur_a_elem(), and valeur_a_sommet().
valeur_a_compo()
double Champ_base::valeur_a_compo (const DoubleVect & pos, int compo) const virtual
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
Returns
double
Reimplemented in TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_som_lu_VEF, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >.
Definition at line 173 of file Champ_base.cpp.
{
  DoubleVect values(nb_comp());
  valeur_a(pos, values);
  const double x = values[compo];
  return x;
}
References Field_base::nb_comp(), and valeur_a().
Referenced by TRUSTChamp_Don_generique< _TYPE_ >::valeur_a_compo(), and TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a_compo().
valeur_a_elem()
DoubleVect & Champ_base::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Fonc_Tabule, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_MED, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >.
Definition at line 154 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_a_elem(...) is not coded " << finl ;
  exit();
  return les_valeurs;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_Inc_base::valeur_a(), Champ_Fonc_MED::valeur_a(), Champ::valeur_a_elem(), and Champ_Fonc::valeur_a_elem().
valeur_a_elem_compo()
double Champ_base::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, Champ_Fonc_Tabule, champ_init_canal_sinal, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_som_lu_VEF, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Face_PolyMAC, and Champ_Fonc_Face_PolyMAC.
Definition at line 185 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_a_elem_compo(...) is not coded " << finl ;
  exit();
  return 0;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ::valeur_a_elem_compo(), and Champ_Fonc::valeur_a_elem_compo().
valeur_a_sommet()
DoubleVect & Champ_base::valeur_a_sommet (int sommet, const Domaine & dom, DoubleVect & val) const virtual
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
Definition at line 393 of file Champ_base.cpp.
{
  DoubleVect position(dimension);
  for(int i=0; i<dimension; i++)
    {
      position(i)=dom.coord(sommet,i);
    }
  return valeur_a(position, val);
}
References Domaine::coord(), Objet_U::dimension, and valeur_a().
valeur_a_sommet_compo()
double Champ_base::valeur_a_sommet_compo (int sommet, int le_poly, int compo) const virtual
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
Reimplemented in Champ_P1NC, and Champ_Q1NC.
Definition at line 405 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_a_sommet_compo(...) is not coded " << finl ;
  exit();
  return -1;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::remplir_fluent(), and Champ::valeur_a_sommet_compo().
valeur_aux()
DoubleTab & Champ_base::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const virtual
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented in Champ_Fonc_base, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, champ_init_canal_sinal, Init_par_partie, Tayl_Green, Champ_Inc_base, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, and TRUSTChamp_Don_generique< Champ_Don_Type::LU >.
Definition at line 216 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_aux(const DoubleTab& ,DoubleTab& ) is not coded " << finl ;
  exit();
  return les_valeurs;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_Fonc_base::affecter_(), Champ_Inc_base::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Ostwald::affecter_(), Champ_P1NC::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Fonc_Elem_PolyMAC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), calculer_valeurs_elem_post(), calculer_valeurs_som_post(), Champ_Generique_Transformation::get_champ(), Perte_Charge_Singuliere::lire_surfaces(), valeur_a(), Champ_front_MED::valeur_au_temps_et_au_point(), Champ::valeur_aux(), valeur_aux_bords(), valeur_aux_compo(), valeur_aux_faces(), and Champ_implementation_base::valeur_aux_sommets().
valeur_aux_bords()
DoubleTab Champ_base::valeur_aux_bords () const virtual
renvoie la valeur du champ aux faces de bord
Reimplemented in Champ_Inc_base.
Definition at line 445 of file Champ_base.cpp.
{
  const DoubleTab& xv_bord = ref_cast(Zone_VF, zone_dis_base()).xv_bord();
  DoubleTrav result(xv_bord.dimension_tot(0), valeurs().line_size());
  return valeur_aux(xv_bord, result);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), ref_cast, valeur_aux(), Champ_Proto::valeurs(), and zone_dis_base().
Referenced by Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Fluide_base::calculer_e_int(), and Champ_front_debit_massique::update_coeff().
valeur_aux_centres_de_gravite()
DoubleTab & Champ_base::valeur_aux_centres_de_gravite (const DoubleTab & positions, DoubleTab & valeurs) const virtual
Definition at line 225 of file Champ_base.cpp.
{
  IntVect les_polys(positions.dimension(0));
  int sz = positions.dimension(0);
  for (int i=0; i<sz; i++)
    les_polys(i) = i;
  return valeur_aux_elems(positions, les_polys, les_valeurs);
}
References TRUSTTab< _TYPE_ >::dimension(), and valeur_aux_elems().
Referenced by calculer_valeurs_elem_post(), and Correlation_Vec_Sca_VDF::mettre_a_jour().
valeur_aux_compo()
DoubleVect & Champ_base::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns
reference au tableau les_valeurs
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, Champ_Fonc_Face, champ_init_canal_sinal, Tayl_Green, Champ_Inc_base, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, and Champ_Fonc_reprise.
Definition at line 251 of file Champ_base.cpp.
{
// Pas optimal mais fonctionne
  int nb_val=pos.dimension(0);
// Le tableau les_valeurs doit avoir la bonne taille en entree:
  assert(les_valeurs.size() == nb_val);
  DoubleTrav prov(nb_val,nb_comp());
  valeur_aux(pos,prov);
  for (int i=0; i<nb_val; i++)
    les_valeurs(i)=prov(i,compo);
  return les_valeurs;
}
References TRUSTTab< _TYPE_ >::dimension(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), and valeur_aux().
Referenced by Champ_Face::affecter_(), Champ_Fonc_Face::affecter_(), Champ_Fonc_base::affecter_compo(), Champ_Inc_base::affecter_compo(), calculer_valeurs_elem_compo_post(), calculer_valeurs_som_compo_post(), Champ_Face_implementation::imprime_Face(), Champ::valeur_aux_compo(), and Champ_implementation_base::valeur_aux_sommets_compo().
valeur_aux_elems()
DoubleTab & Champ_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Fonc_Tabule, Champ_som_lu, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_MED, Champ_P1_isoP1Bulle, Champ_som_lu_VEF, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, and Champ_Fonc_Face_PolyMAC.
Definition at line 296 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_aux_elems(...) is not coded " << finl ;
  exit();
  return les_valeurs;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_implementation_P0::affecter_(), Champ_Ostwald::affecter_(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Champ_front_recyclage::mettre_a_jour(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Moyenne_volumique::traiter_champs(), Champ_Fonc_base::valeur_aux(), Champ_Inc_base::valeur_aux(), valeur_aux_centres_de_gravite(), Champ::valeur_aux_elems(), Champ_Fonc::valeur_aux_elems(), Champ_Fonc_reprise::valeur_aux_elems(), Champ_Fonc_MED::valeur_aux_elems(), and valeur_aux_sommets().
valeur_aux_elems_compo()
DoubleVect & Champ_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_som_lu, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, Champ_Fonc_MED, Champ_P1_isoP1Bulle, Champ_som_lu_VEF, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Face_PolyMAC, Champ_Face_PolyMAC_P0, and Champ_Fonc_Face_PolyMAC.
Definition at line 343 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_aux_elems_compo(...) is not coded " << finl ;
  exit();
  return les_valeurs;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_Fonc_base::affecter_compo(), Champ_Inc_base::affecter_compo(), calculer_valeurs_elem_compo_post(), Champ_Inc_base::valeur_aux_compo(), Champ::valeur_aux_elems_compo(), Champ_Fonc_reprise::valeur_aux_elems_compo(), Champ_Fonc_MED::valeur_aux_elems_compo(), and valeur_aux_sommets_compo().
valeur_aux_elems_compo_smooth()
DoubleVect & Champ_base::valeur_aux_elems_compo_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) virtual
Reimplemented in Champ_Fonc_P1NC, and Champ_P1NC.
Definition at line 365 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_aux_elems_compo_smooth(...) is not coded " << finl ;
  Cerr << "The chsom option of probes does apply for the moment only for the field of type P1NC in VEF " << finl ;
  exit();
  return les_valeurs;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Sonde::postraiter().
valeur_aux_elems_smooth()
DoubleTab & Champ_base::valeur_aux_elems_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) virtual
Reimplemented in Champ_Fonc_P1NC, and Champ_P1NC.
Definition at line 354 of file Champ_base.cpp.
{
  Cerr << que_suis_je();
  Cerr << "::valeur_aux_elems_smooth(...) is not coded " << finl ;
  Cerr << "The chsom option of probes does apply for the moment only for the field of type P1NC in VEF " << finl ;
  exit();
  return les_valeurs;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Sonde::postraiter().
valeur_aux_faces()
DoubleTab & Champ_base::valeur_aux_faces (DoubleTab & result) const virtual
renvoie la valeur du champ aux faces
Reimplemented in Champ_Face_PolyMAC, and Champ_Elem_PolyMAC.
Definition at line 438 of file Champ_base.cpp.
{
  return valeur_aux(ref_cast(Zone_VF, zone_dis_base()).xv(), result);
}
References ref_cast, valeur_aux(), and zone_dis_base().
Referenced by Champ_Generique_Transformation::get_champ(), and Postraitement::postraiter_champs().
valeur_aux_sommets()
DoubleTab & Champ_base::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented in Champ_Fonc_Tabule, Champ_Fonc_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, and Champ_Fonc_Face_PolyMAC.
Definition at line 415 of file Champ_base.cpp.
{
  const DoubleTab& positions=dom.coord_sommets();
  const Zone& zone=dom.zone(0);
  IntVect les_polys(positions.dimension(0));
  zone.chercher_elements(positions, les_polys);
  return valeur_aux_elems(positions, les_polys, val);
}
References Zone::chercher_elements(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), valeur_aux_elems(), and Domaine::zone().
Referenced by calculer_valeurs_som_post(), Champ_Fonc::valeur_aux_sommets(), Champ_Fonc_MED::valeur_aux_sommets(), and Champ_Fonc_reprise::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_base::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented in Champ_Fonc_Tabule, Champ_Fonc_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, and Champ_Fonc_Face_PolyMAC.
Definition at line 426 of file Champ_base.cpp.
{
  const DoubleTab& positions=dom.coord_sommets();
  const Zone& zone=dom.zone(0);
  IntVect les_polys(positions.dimension(0));
  zone.chercher_elements(positions, les_polys);
  return valeur_aux_elems_compo(positions, les_polys, val, compo);
}
References Zone::chercher_elements(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), valeur_aux_elems_compo(), and Domaine::zone().
Referenced by calculer_valeurs_som_compo_post(), Champ_Fonc::valeur_aux_sommets_compo(), Champ_Fonc_MED::valeur_aux_sommets_compo(), and Champ_Fonc_reprise::valeur_aux_sommets_compo().
zone_dis_base()
const Zone_dis_base & Champ_base::zone_dis_base () const virtual
Reimplemented in Champ_Fonc_P1_EF, Champ_Fonc_Q1_EF, Champ_P0_EF, Champ_P1_EF, Champ_Q1_EF, Champ_Fonc_Tabule, Champ_input_P0, Champ_Fonc_P0_base, Champ_Fonc_MED, Champ_Fonc_P0_MED, Champ_Fonc_P1_MED, Champ_Fonc_Q1_MED, Champ_Fonc_reprise, Champ_Fonc_P1_isoP1Bulle, Champ_P1_isoP1Bulle, Champ_Elem_PolyMAC, Champ_Face_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Som_PolyMAC, Champ_Ostwald, Champ_Face, Champ_Fonc_Face, Champ_Fonc_P1_VDF, Champ_Fonc_Q1_VDF, Champ_Ostwald_VDF, Champ_P0_VDF, Champ_Fonc_P1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_Q1NC, Champ_Ostwald_VEF, Champ_P0_VEF, Champ_P1NC, and Champ_Q1NC.
Definition at line 1138 of file Champ_base.cpp.
{
  Cerr << "Error in Champ_base::zone_dis_base\n";
  Cerr << " (field name : " << le_nom() << ")\n";
  Cerr << " The method " << que_suis_je();
  Cerr << "::zone_dis_base is not coded\n";
  Cerr << " or the field does not possess a zone_dis_base." << finl;
  exit();
  throw;
  return zone_dis_base();
}
References Cerr, Process::exit(), finl, Field_base::le_nom(), Objet_U::que_suis_je(), and zone_dis_base().
Referenced by Champ_implementation_P0::affecter_(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Segment_poly::calcul_vc(), Tetra_poly::calcul_vc(), Point_EF::calcul_vc(), Segment_EF::calcul_vc(), Tetra_EF::calcul_vc(), Tri_EF::calcul_vc(), Fluide_base::calculer_e_int(), calculer_valeurs_elem_post(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Champ_Generique_Transformation::completer(), Champ_Fonc_base::domaine(), Champ_Inc_base::domaine(), EcritureLectureSpecial::ecriture_special(), Discretisation_tools::faces_to_cells(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales(), grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Generique_refChamp::get_ref_connectivity(), Champ_implementation_base::get_zone_dis(), Champ_Inc_base::init_champ_calcule(), Ch_front_var_instationnaire_dep::initialiser(), EcritureLectureSpecial::lecture_special(), multiplier_diviser_rho(), Discretisation_tools::nodes_to_cells(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Precond_local::res_syst_loc_hybride(), Champ_Fonc_base::sauvegarder(), Champ_front_contact_VEF::test_faces_coin(), Moyenne_volumique::traiter_champs(), Champ_Inc_base::valeur_a(), Champ_Fonc_base::valeur_aux(), Champ_Inc_base::valeur_aux(), valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_compo(), valeur_aux_faces(), Champ_front_calc::zone_dis(), Champ_front_contact_VEF::zone_dis(), Champ_implementation::zone_dis_base(), zone_dis_base(), Champ_Fonc::zone_dis_base(), and Champ_Inc::zone_dis_base().
Member Data Documentation
info_obj
const Type_info Champ_base::info_obj static
Definition at line 51 of file Champ_base.h.
temps_
double Champ_base::temps_ protected
Definition at line 120 of file Champ_base.h.
Referenced by Champ_Inc_base::avancer(), changer_temps(), Champ_Inc_base::changer_temps(), Champ_Ostwald_VDF::me_calculer(), Champ_Ostwald_VEF::me_calculer(), h_conv_Champ_P1NC::me_calculer(), Champ_Inc_base::mettre_a_jour(), Champ_Inc_base::reculer(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), temps(), and Champ_P1_isoP1Bulle::trace().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_base.h
src/Kernel/Framework/Champ_base.cpp