TRUST: Champ_front_t Class Reference
Champ_front_t Class Reference
classe Champ_front_t
Classe derivee de Champ_front_var qui represente les
champs aux frontieres analytiques en espace et constants dans
le temps
Nouveau champ frontiere
il permet de mettre en champ frontiere un parametre qui depend d'une
fonction. Cette fonction est rentree dans le jeu de donnees sous
la forme d'une chaine de caracteres. Pas besoin de recompilation
comme avec la classe Champ_front_analytique qui utilise une
fonction codee en dur.
#include <Champ_front_t.h>
Public Member Functions
Champ_front_t ()
~Champ_front_t ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Renvoie l'objet upcaste en Champ_front_base&.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual double valeur_au_temps (double temps, int som, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_t & self_cast (Objet_U &)
static const Champ_front_t & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
virtual Entree & readOn (Entree &)
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_t nb_compo vrel_1 ... [vrel_i].
Private Attributes
Vect_Parser_U f_t
Detailed Description
classe Champ_front_t
Classe derivee de Champ_front_var qui represente les
champs aux frontieres analytiques en espace et constants dans
le temps
Nouveau champ frontiere
il permet de mettre en champ frontiere un parametre qui depend d'une
fonction. Cette fonction est rentree dans le jeu de donnees sous
la forme d'une chaine de caracteres. Pas besoin de recompilation
comme avec la classe Champ_front_analytique qui utilise une
fonction codee en dur.
Definition at line 46 of file Champ_front_t.h.
Constructor & Destructor Documentation
Champ_front_t::Champ_front_t ()
Definition at line 30 of file Champ_front_t.cpp.
Champ_front_t::~Champ_front_t ()
Definition at line 30 of file Champ_front_t.cpp.
Member Function Documentation
Champ_front_base & Champ_front_t::affecter_ (const Champ_front_base & ch) [virtual]
Renvoie l'objet upcaste en Champ_front_base&.
Returns:
Champ_front_base&
Signification: (*this) upcaste en Champ_front_base&
Contraintes:
Implements Champ_front_base.
Definition at line 118 of file Champ_front_t.cpp.
{
  return *this;
}
Objet_U * Champ_front_t::cree_instance () [static]
Definition at line 30 of file Champ_front_t.cpp.
int Champ_front_t::duplique () const [virtual]
Implements Ch_front_var_instationnaire_indep.
Definition at line 30 of file Champ_front_t.cpp.
const Type_info * Champ_front_t::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 30 of file Champ_front_t.cpp.
const Type_info * Champ_front_t::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 30 of file Champ_front_t.cpp.
void Champ_front_t::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Reimplemented from Champ_front_base.
Definition at line 124 of file Champ_front_t.cpp.
References DoubleVect::echange_espace_virtuel(), f_t, Champ_front_base::frontiere_dis(), Field_base::nb_comp(), ref_cast, and Champ_front_var_instationnaire::valeurs_au_temps().
{
  int dim=nb_comp();
  const Frontiere_dis_base& fr_dis=frontiere_dis();
  int nb_faces=ref_cast(Front_VF, fr_dis).nb_faces();
  int i,k;
  DoubleTab& tab=valeurs_au_temps(temps);
  for( i=0; i<nb_faces; i++)
    {
      for( k=0; k<dim; k++)
        {
          f_t[k].setVar("t",temps);
          tab(i,k)=f_t[k].eval();
        }
    }
  tab.echange_espace_virtuel();
}
Sortie & Champ_front_t::printOn (Sortie & os) const [protected, virtual]
Imprime le champ sur flot de sortie.
Imprime la taille du champ et la valeur (constante) sur
la frontiere.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 51 of file Champ_front_t.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_t::readOn (Entree & is) [protected, virtual]
Lit le champ a partir d'un flot d'entree.
Format:
Champ_front_t nb_compo vrel_1 ... [vrel_i].
Returns:
Entree& is
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 78 of file Champ_front_t.cpp.
References Cerr, vect_impl::dimensionner(), f_t, finl, Field_base::fixer_nb_comp(), Champ_Proto::lire_dimension(), and Objet_U::que_suis_je().
{
  int dim;
  dim=lire_dimension(is,que_suis_je());
  fixer_nb_comp(dim);
  f_t.dimensionner(dim);
  for (int i = 0; i<dim; i++)
    {
      Nom tmp;
      is >> tmp;
      Cerr << "Reading and interpretation of the function " << tmp << finl;
      f_t[i].setNbVar(1);
      f_t[i].setString(tmp);
      f_t[i].addVar("t");
      f_t[i].parseString();
      Cerr << "Interpretation of function " << tmp << " Ok" << finl;
    }
  return is;
}
const Champ_front_t & Champ_front_t::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 30 of file Champ_front_t.cpp.
Champ_front_t & Champ_front_t::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 30 of file Champ_front_t.cpp.
unsigned Champ_front_t::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Champ_front_t.cpp.
double Champ_front_t::valeur_au_temps (double temps, int som, int comp) const [virtual]
Definition at line 142 of file Champ_front_t.cpp.
References Parser_U::eval(), f_t, and Parser_U::setVar().
{
  Parser_U& f_tk=f_t[k];
  f_tk.setVar("t",temps);
  return f_tk.eval();
}
virtual int Champ_front_t::valeur_au_temps_et_au_point_disponible () const [inline, virtual]
Reimplemented from Champ_front_var_instationnaire.
Definition at line 55 of file Champ_front_t.h.
  {
    return 1;
  };
Member Data Documentation
Vect_Parser_U Champ_front_t::f_t [mutable, private]
Definition at line 58 of file Champ_front_t.h.
Referenced by mettre_a_jour(), readOn(), and valeur_au_temps().
const Type_info Champ_front_t::info_obj [static]
Reimplemented from Ch_front_var_instationnaire_indep.
Definition at line 48 of file Champ_front_t.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_t.h
src/Kernel/Champs/Champ_front_t.cpp