TRUST: Eval_Darcy_VDF_Face Class Reference
Eval_Darcy_VDF_Face Class Reference
#include <Eval_Darcy_VDF_Face.h>
Public Member Functions
Eval_Darcy_VDF_Face ()
Eval_Darcy_VDF_Face (const Eval_Darcy_VDF_Face &eval)
double & getPorosite ()
template<typename Type_Double >
void calculer_terme_source (const int, Type_Double &) const
template<typename Type_Double >
void calculer_terme_source_bord (int num_face, Type_Double &source) const
void mettre_a_jour () override
void associer (const Champ_Don &)
associe le champ de diffusivite
void associer (const Champ_Inc &vit)
Public Member Functions inherited from Evaluateur_Source_VDF_Face
Evaluateur_Source_VDF_Face ()
Evaluateur_Source_VDF_Face (const Evaluateur_Source_VDF_Face &)
void completer () override
template<typename Type_Double >
void calculer_terme_source_bord (int, Type_Double &) const
Public Member Functions inherited from Evaluateur_Source_VDF
Evaluateur_Source_VDF ()
Evaluateur_Source_VDF (const Evaluateur_Source_VDF &eval)
virtual ~Evaluateur_Source_VDF ()
template<typename Type_Double >
void calculer_terme_source (int, Type_Double &) const
virtual void mettre_a_jour ()=0
virtual void completer ()=0
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
Public Attributes
Modele_Permeabilite modK
Protected Attributes
Ref_Champ_Inc vitesse
Ref_Champ_Don_base diffusivite_
DoubleTab db_diffusivite
double porosite
Protected Attributes inherited from Evaluateur_Source_VDF_Face
IntVect orientation
orientations des faces
DoubleVect volumes_entrelaces
DoubleVect porosite_surf
porosites surfaciques
Protected Attributes inherited from Evaluateur_Source_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_VDF la_zcl
Detailed Description
Definition at line 25 of file Eval_Darcy_VDF_Face.h.
Constructor & Destructor Documentation
Eval_Darcy_VDF_Face() [1/2]
Eval_Darcy_VDF_Face::Eval_Darcy_VDF_Face () inline
Definition at line 28 of file Eval_Darcy_VDF_Face.h.
: porosite(1) { }
Eval_Darcy_VDF_Face() [2/2]
Eval_Darcy_VDF_Face::Eval_Darcy_VDF_Face (const Eval_Darcy_VDF_Face & eval) inline
Definition at line 29 of file Eval_Darcy_VDF_Face.h.
: Evaluateur_Source_VDF_Face(eval), porosite(1) { }
Member Function Documentation
associer() [1/2]
void Eval_Darcy_VDF_Face::associer (const Champ_Don & diffu) inline
associe le champ de diffusivite
Definition at line 48 of file Eval_Darcy_VDF_Face.h.
{
  const int nb_faces_tot = la_zone.valeur().nb_faces_tot();
  db_diffusivite.resize(nb_faces_tot,Array_base::NOCOPY_NOINIT);
  diffusivite_ = diffu.valeur();
  mettre_a_jour();
}
References db_diffusivite, diffusivite_, Evaluateur_Source_VDF::la_zone, mettre_a_jour(), Zone_VF::nb_faces_tot(), Array_base::NOCOPY_NOINIT, TRUSTTab< _TYPE_ >::resize(), Deriv_Champ_Don_base::valeur(), and Ref_Zone_VDF::valeur().
Referenced by Source_Darcy_VDF_Face::associer_pb().
associer() [2/2]
void Eval_Darcy_VDF_Face::associer (const Champ_Inc & vit) inline
Definition at line 35 of file Eval_Darcy_VDF_Face.h.
{ vitesse = vit; }
References vitesse.
calculer_terme_source()
template<typename Type_Double > void Eval_Darcy_VDF_Face::calculer_terme_source (const int num_face, Type_Double & source) const
< -mu.vol.psi.U/K
Definition at line 88 of file Eval_Darcy_VDF_Face.h.
{
  const int size = source.size_array();
  for (int i = 0; i < size; i++) source[i] = -db_diffusivite(num_face)/modK->getK(porosite)*volumes_entrelaces(num_face)*porosite_surf(num_face)*(vitesse->valeurs())(num_face,i); //!< -mu.vol.psi.U/K
}
References db_diffusivite, Modele_Permeabilite::getK(), modK, porosite, Evaluateur_Source_VDF_Face::porosite_surf, Champ_Inc::valeurs(), vitesse, and Evaluateur_Source_VDF_Face::volumes_entrelaces.
Referenced by calculer_terme_source_bord().
calculer_terme_source_bord()
template<typename Type_Double > void Eval_Darcy_VDF_Face::calculer_terme_source_bord (int num_face, Type_Double & source) const inline
Definition at line 32 of file Eval_Darcy_VDF_Face.h.
{ calculer_terme_source(num_face,source); }
References calculer_terme_source().
getPorosite()
double & Eval_Darcy_VDF_Face::getPorosite () inline
Definition at line 30 of file Eval_Darcy_VDF_Face.h.
{ return porosite; }
References porosite.
Referenced by Source_Darcy_VDF_Face::readOn().
mettre_a_jour()
void Eval_Darcy_VDF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VDF.
Definition at line 56 of file Eval_Darcy_VDF_Face.h.
{
  const int nb_faces_tot = la_zone.valeur().nb_faces_tot();
  if (sub_type(Champ_Uniforme,diffusivite_.valeur())) db_diffusivite = diffusivite_.valeur()(0,0);
  else
    {
      const DoubleTab& val_diff = diffusivite_.valeur().valeurs();
      const IntTab& face_vois = la_zone.valeur().face_voisins();
      const ArrOfDouble& volumes = la_zone.valeur().volumes();
      db_diffusivite = 0.;
// Compute nu(fac)=(nu(elem1).vol(elem1)+nu(elem2).vol(elem2))/(vol(elem1)+vol(elem2))
// Viscosity at face is the volume weighted average of viscosity on elements
      for (int fac = 0; fac < nb_faces_tot; fac++)
        {
          const int elem1 = face_vois(fac,0), elem2 = face_vois(fac,1);
          double vol = 0;
          if (elem1!=-1)
            {
              db_diffusivite(fac) += val_diff(elem1)*volumes[elem1];
              vol += volumes[elem1];
            }
          if (elem2!=-1)
            {
              db_diffusivite(fac) += val_diff(elem2)*volumes[elem2];
              vol += volumes[elem2];
            }
          db_diffusivite(fac) /= vol;
        }
    }
}
References db_diffusivite, diffusivite_, face_vois(), Zone_VF::face_voisins(), Evaluateur_Source_VDF::la_zone, Zone_VF::nb_faces_tot(), sub_type, Ref_Champ_Don_base::valeur(), Ref_Zone_VDF::valeur(), Champ_Don_base::valeurs(), and Zone_VF::volumes().
Referenced by associer().
Member Data Documentation
db_diffusivite
DoubleTab Eval_Darcy_VDF_Face::db_diffusivite protected
Definition at line 42 of file Eval_Darcy_VDF_Face.h.
Referenced by associer(), calculer_terme_source(), and mettre_a_jour().
diffusivite_
Ref_Champ_Don_base Eval_Darcy_VDF_Face::diffusivite_ protected
Definition at line 41 of file Eval_Darcy_VDF_Face.h.
Referenced by associer(), and mettre_a_jour().
modK
Modele_Permeabilite Eval_Darcy_VDF_Face::modK
Definition at line 37 of file Eval_Darcy_VDF_Face.h.
Referenced by calculer_terme_source(), and Source_Darcy_VDF_Face::readOn().
porosite
double Eval_Darcy_VDF_Face::porosite protected
Definition at line 43 of file Eval_Darcy_VDF_Face.h.
Referenced by calculer_terme_source(), and getPorosite().
vitesse
Ref_Champ_Inc Eval_Darcy_VDF_Face::vitesse protected
Definition at line 40 of file Eval_Darcy_VDF_Face.h.
Referenced by associer(), and calculer_terme_source().
The documentation for this class was generated from the following file:
src/VDF/Sources/Evaluateurs/Eval_Darcy_VDF_Face.h