TRUST: EcrFicPartage Class Reference
EcrFicPartage Class Reference
#include <EcrFicPartage.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EcrFicPartage ()
EcrFicPartage (const char *name, std::_Ios_Openmode mode=ios::out)
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out) override
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
~EcrFicPartage () override
ferme le fichier
void close ()
Sortie & lockfile () override
Permet au processus appelant de bloquer en attente de la ressource commune a tous les processus qui est le fichier partage.
Si le processus appelant cette methode n'est pas le premier, il atend du processus precedent l'endroit ou il doit se positionner dans le fichier pour effectuer sa prochaine ecriture.
Cette methode est systematiquement appelee avant toute nouvelle ecriture dans le fichier.
Sortie & unlockfile () override
Permet de debloquer la ressource critique pour leprocessus suivant.
Le processus appelant, sauf si c'est le premier processus du groupe, envoie
sa position courante au precessus suivant dans le groupe. Cette methode est
a appeler apres chaque ecriture dans le fichier.
Sortie & syncfile () override
Provoque l'ecriture sur disque des donnees accumulees sur les differents processeurs
depuis le dernier appel a syncfile().
Les donnees sont ecrites dans l'ordre croissant des processeurs.
Cette fonction doit etre appelee le meme nombre de fois sur tous les processeurs !
Exemple:
processeur 0: processeur 1:
file << "pe0 : 1" << finl; file << "pe1 : 1" << finl;
file << "pe0 : 2" << finl; file << "pe1 : 2" << finl;
file.syncfile(); file.syncfile();
file << "pe0 : 3" << finl; file << "pe1 : 3" << finl;
file << "pe0 : 4" << finl;
file.syncfile(); file.syncfile();
file << "pe0 : end" << finl; // le processeur 1 n'ecrit pas de donnees
file.syncfile(); file.syncfile();
Contenu du fichier :
pe0 : 1
pe0 : 2
pe1 : 1
pe1 : 2
pe0 : 3
pe0 : 4
pe1 : 3
pe0 : end.
void precision (int) override
int get_precision () override
Sortie & flush () override
int set_bin (int bin) override
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Sortie & operator<< (const char *ob) override
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Sortie & operator<< (const Objet_U &ob) override
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
Sortie & operator<< (const std::string &ob) override
Sortie & operator<< (const Separateur &) override
Sortie & operator<< (const unsigned ob) override
Sortie & operator<< (const int ob) override
Sortie & operator<< (const float ob) override
Sortie & operator<< (const double ob) override
Sortie & operator<< (const long ob) override
int put (const unsigned *ob, int n, int pas) override
int put (const int *ob, int n, int pas) override
int put (const float *ob, int n, int pas) override
int put (const double *ob, int n, int pas) override
int put (const long *ob, int n, int pas) override
Public Member Functions inherited from SFichier
SFichier ()
~SFichier ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SFichier (const char *name, std::_Ios_Openmode mode=ios::out)
Public Member Functions inherited from Sortie_Fichier_base
~Sortie_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sortie_Fichier_base ()
Sortie_Fichier_base (const Sortie_Fichier_base &)=default
Sortie_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::out)
ofstream & get_ofstream ()
void close ()
void precision (int pre) override
virtual int get_precision ()
void setf (std::_Ios_Fmtflags code) override
bool is_open ()
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out)
Sortie & flush () override
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcrFicPartage & self_cast (Objet_U &)
static const EcrFicPartage & self_cast (const Objet_U &)
Static Public Member Functions inherited from SFichier
static Objet_U * cree_instance ()
static const Type_info * info ()
static SFichier & self_cast (Objet_U &)
static const SFichier & self_cast (const Objet_U &)
Static Public Member Functions inherited from Sortie_Fichier_base
static const Type_info * info ()
static Sortie_Fichier_base & self_cast (Objet_U &)
static const Sortie_Fichier_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from SFichier
static const Type_info info_obj
Static Public Attributes inherited from Sortie_Fichier_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom_fic_
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Private Member Functions
OBuffer & get_obuffer ()
template<typename _TYPE_ >
int put_template (const _TYPE_ *ob, int n, int pas)
template<typename _TYPE_ >
Sortie & operator_template (const _TYPE_ &ob)
Private Attributes
OBuffer * obuffer_ptr_
Pointeur : permet de ne pas inclure OBuffer.h.
Detailed Description
Definition at line 38 of file EcrFicPartage.h.
Constructor & Destructor Documentation
EcrFicPartage() [1/2]
EcrFicPartage::EcrFicPartage ()
Definition at line 36 of file EcrFicPartage.cpp.
                             : SFichier()
{
  obuffer_ptr_ = new OBuffer;
  set_bin(0);
}
References obuffer_ptr_, and set_bin().
EcrFicPartage() [2/2]
EcrFicPartage::EcrFicPartage (const char * name, std::_Ios_Openmode mode = ios::out)
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
Definition at line 45 of file EcrFicPartage.cpp.
{
  obuffer_ptr_ = new OBuffer;
  set_bin(0);
  ouvrir(name, mode);
}
References obuffer_ptr_, ouvrir(), and set_bin().
~EcrFicPartage()
EcrFicPartage::~EcrFicPartage () override
ferme le fichier
Definition at line 95 of file EcrFicPartage.cpp.
{
  close();
  delete obuffer_ptr_;
  obuffer_ptr_ = 0;
}
References close(), and obuffer_ptr_.
Member Function Documentation
close()
void EcrFicPartage::close ()
Definition at line 102 of file EcrFicPartage.cpp.
{
// Verification sanitaire : tout le monde est la ?
  barrier();
  const int buflen = get_obuffer().len();
  if(buflen > 0)
    {
      Cerr << "***** WARNING : EcrFicPartage::close() ******* "<<nom_fic_
           << "\non PE " << me() << " the buffer is not empty\n"
           << "  (Missing syncfile) : one makes a last syncfile" << finl;
      Cerr<<get_obuffer().str()<<finl;
    }
#ifndef NDEBUG
// Y a-t-il un processeur sur lequel il reste des donnees
  const int maxbuflen = mp_sum(buflen);
  if (maxbuflen > 0)
    syncfile();
#endif
  if(je_suis_maitre())
    SFichier::close();
#ifndef NDEBUG
  if (maxbuflen > 0)
    {
      Cerr<<"It missed a syncfile somewhere"<<finl;
      Cerr<<"Indeed, maxbuflen =" << maxbuflen << finl;
      Cerr<<"GF prefers to stop the calculation to correct "<<finl;
      exit();
    }
#endif
}
References Process::barrier(), Cerr, Sortie_Fichier_base::close(), Process::exit(), finl, get_obuffer(), Process::je_suis_maitre(), OBuffer::len(), Process::me(), Process::mp_sum(), nom_fic_, OBuffer::str(), and syncfile().
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Zone_VEF_PreP1b::construire_ok_arete(), Equation_base::ecrire_fichier_xyz(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and ~EcrFicPartage().
cree_instance()
Objet_U * EcrFicPartage::cree_instance () static
Definition at line 24 of file EcrFicPartage.cpp.
duplique()
int EcrFicPartage::duplique () const override virtual
Implements Objet_U.
Reimplemented in EcrFicPartageBin.
Definition at line 24 of file EcrFicPartage.cpp.
flush()
Sortie & EcrFicPartage::flush () override virtual
Reimplemented from Sortie.
Definition at line 321 of file EcrFicPartage.cpp.
{ return (*this); }
Referenced by Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_entete_lml(), Format_Post_Lml::ecrire_item_int_lml(), Format_Post_Lml::ecrire_temps_lml(), and Format_Post_Lml::finir_lml().
get_info()
const Type_info * EcrFicPartage::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrFicPartageBin.
Definition at line 24 of file EcrFicPartage.cpp.
get_obuffer()
OBuffer & EcrFicPartage::get_obuffer () inline private
Definition at line 53 of file EcrFicPartage.cpp.
{
  assert(obuffer_ptr_);
  return *obuffer_ptr_;
}
References obuffer_ptr_.
Referenced by close(), get_precision(), operator<<(), operator_template(), ouvrir(), precision(), put_template(), set_bin(), and syncfile().
get_precision()
int EcrFicPartage::get_precision () override virtual
Reimplemented from Sortie_Fichier_base.
Definition at line 284 of file EcrFicPartage.cpp.
{ return get_obuffer().get_precision(); }
References get_obuffer(), and OBuffer::get_precision().
info()
const Type_info * EcrFicPartage::info () static
Definition at line 24 of file EcrFicPartage.cpp.
lockfile()
Sortie & EcrFicPartage::lockfile () override virtual
Permet au processus appelant de bloquer en attente de la ressource commune a tous les processus qui est le fichier partage.
Si le processus appelant cette methode n'est pas le premier, il atend du processus precedent l'endroit ou il doit se positionner dans le fichier pour effectuer sa prochaine ecriture.
Cette methode est systematiquement appelee avant toute nouvelle ecriture dans le fichier.
Returns
Sortie&
Signification: *this
Reimplemented from Sortie.
Definition at line 138 of file EcrFicPartage.cpp.
{
  return *this;
}
Referenced by Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), Equation_base::ecrire_fichier_xyz(), and Format_Post_Lml::ecrire_item_int_lml().
operator<<() [1/9]
Sortie & EcrFicPartage::operator<< (const char * ob) override virtual
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Reimplemented from Sortie.
Definition at line 286 of file EcrFicPartage.cpp.
{
  get_obuffer() << ob;
  return *this;
}
References get_obuffer().
operator<<() [2/9]
Sortie & EcrFicPartage::operator<< (const double ob) override virtual
Reimplemented from Sortie.
Definition at line 298 of file EcrFicPartage.cpp.
{ return operator_template<double>(ob);}
operator<<() [3/9]
Sortie & EcrFicPartage::operator<< (const float ob) override virtual
Reimplemented from Sortie.
Definition at line 297 of file EcrFicPartage.cpp.
{ return operator_template<float>(ob);}
operator<<() [4/9]
Sortie & EcrFicPartage::operator<< (const int ob) override virtual
Reimplemented from Sortie.
Definition at line 295 of file EcrFicPartage.cpp.
{ return operator_template<int>(ob);}
operator<<() [5/9]
Sortie & EcrFicPartage::operator<< (const long ob) override virtual
Reimplemented from Sortie.
Definition at line 301 of file EcrFicPartage.cpp.
{ return operator_template<long>(ob);}
operator<<() [6/9]
Sortie & EcrFicPartage::operator<< (const Objet_U & ob) override virtual
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
Reimplemented from Sortie.
Definition at line 294 of file EcrFicPartage.cpp.
{ return operator_template<Objet_U>(ob);}
operator<<() [7/9]
Sortie & EcrFicPartage::operator<< (const Separateur & s) override virtual
Reimplemented from Sortie.
Definition at line 293 of file EcrFicPartage.cpp.
{ return operator_template<Separateur>(s);}
operator<<() [8/9]
Sortie & EcrFicPartage::operator<< (const std::string & ob) override virtual
Reimplemented from Sortie.
Definition at line 292 of file EcrFicPartage.cpp.
{ return operator_template<std::string>(str);}
operator<<() [9/9]
Sortie & EcrFicPartage::operator<< (const unsigned ob) override virtual
Reimplemented from Sortie.
Definition at line 296 of file EcrFicPartage.cpp.
{ return operator_template<unsigned>(ob);}
operator_template()
template<typename _TYPE_ > Sortie & EcrFicPartage::operator_template (const _TYPE_ & ob) inline private
Definition at line 93 of file EcrFicPartage.h.
  {
    get_obuffer() << ob;
    return *this;
  }
References get_obuffer().
ouvrir()
int EcrFicPartage::ouvrir (const char * name, std::_Ios_Openmode mode = ios::out) override virtual
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
Reimplemented from Sortie_Fichier_base.
Definition at line 64 of file EcrFicPartage.cpp.
{
// Verification sanitaire : tous les processeurs sont la ?
  barrier();
  int ok = 1;
  if(je_suis_maitre())
    {
#ifdef FILESYSTEM_NON_GLOBAL
      nom_fic_ = pwd();
      nom_fic_ += "/";
      nom_fic_ += name;
#else
      nom_fic_ = name;
#endif
// Seul le maitre ouvre le fichier
      ok = SFichier::ouvrir((const char *)nom_fic_, mode);
    }
  syncfile();
// Modif B.Math. 22/09/2004: tous les processeurs passent par le buffer,
// y compris le maitre.
  get_obuffer().new_buffer();
  return ok;
}
References Process::barrier(), get_obuffer(), Process::je_suis_maitre(), OBuffer::new_buffer(), nom_fic_, Sortie_Fichier_base::ouvrir(), pwd(), and syncfile().
Referenced by Zone_VEF_PreP1b::construire_ok_arete(), EcrFicPartage(), EcrFicPartageBin::EcrFicPartageBin(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_entete_lml(), Equation_base::ecrire_fichier_xyz(), Format_Post_Lml::ecrire_item_int_lml(), Format_Post_Lml::ecrire_temps_lml(), Format_Post_Lml::finir_lml(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), and Operateur_base::ouvrir_fichier_partage().
precision()
void EcrFicPartage::precision (int i) override virtual
Reimplemented from Sortie.
Definition at line 282 of file EcrFicPartage.cpp.
{ get_obuffer().precision(i); }
References get_obuffer(), and OBuffer::precision().
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Equation_base::ecrire_fichier_xyz(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and Operateur_base::ouvrir_fichier_partage().
printOn()
Sortie & EcrFicPartage::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrFicPartageBin.
Definition at line 31 of file EcrFicPartage.cpp.
{
  throw;
  return s;
}
put() [1/5]
int EcrFicPartage::put (const double * ob, int n, int pas) override virtual
Reimplemented from Sortie.
Definition at line 307 of file EcrFicPartage.cpp.
{ return put_template<double>(ob,n,pas); }
put() [2/5]
int EcrFicPartage::put (const float * ob, int n, int pas) override virtual
Reimplemented from Sortie.
Definition at line 306 of file EcrFicPartage.cpp.
{ return put_template<float>(ob,n,pas); }
put() [3/5]
int EcrFicPartage::put (const int * ob, int n, int pas) override virtual
Reimplemented from Sortie.
Definition at line 305 of file EcrFicPartage.cpp.
{ return put_template<int>(ob,n,pas); }
put() [4/5]
int EcrFicPartage::put (const long * ob, int n, int pas) override virtual
Reimplemented from Sortie.
Definition at line 310 of file EcrFicPartage.cpp.
{ return put_template<long>(ob,n,pas); }
put() [5/5]
int EcrFicPartage::put (const unsigned * ob, int n, int pas) override virtual
Reimplemented from Sortie.
Definition at line 304 of file EcrFicPartage.cpp.
{ return put_template<unsigned>(ob,n,pas); }
put_template()
template<typename _TYPE_ > int EcrFicPartage::put_template (const _TYPE_ * ob, int n, int pas) inline private
Definition at line 86 of file EcrFicPartage.h.
  {
    get_obuffer().put(ob,n,pas);
    return 1;
  }
References get_obuffer(), and Sortie::put().
readOn()
Entree & EcrFicPartage::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrFicPartageBin.
Definition at line 25 of file EcrFicPartage.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const EcrFicPartage & EcrFicPartage::self_cast (const Objet_U & r) static
Definition at line 24 of file EcrFicPartage.cpp.
self_cast() [2/2]
EcrFicPartage & EcrFicPartage::self_cast (Objet_U & r) static
Definition at line 24 of file EcrFicPartage.cpp.
set_bin()
int EcrFicPartage::set_bin (int bin) override virtual
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Reimplemented from Sortie.
Definition at line 313 of file EcrFicPartage.cpp.
{
  assert(bin==0 || bin==1);
  bin_ = bin;
  get_obuffer().set_bin(bin_);
  return bin_;
}
References Sortie::bin_, get_obuffer(), and OBuffer::set_bin().
Referenced by EcrFicPartage(), EcrFicPartageBin::EcrFicPartageBin(), and Equation_base::ecrire_fichier_xyz().
syncfile()
Sortie & EcrFicPartage::syncfile () override virtual
Provoque l'ecriture sur disque des donnees accumulees sur les differents processeurs
depuis le dernier appel a syncfile().
Les donnees sont ecrites dans l'ordre croissant des processeurs.
Cette fonction doit etre appelee le meme nombre de fois sur tous les processeurs !
Exemple:
processeur 0: processeur 1:
file << "pe0 : 1" << finl; file << "pe1 : 1" << finl;
file << "pe0 : 2" << finl; file << "pe1 : 2" << finl;
file.syncfile(); file.syncfile();
file << "pe0 : 3" << finl; file << "pe1 : 3" << finl;
file << "pe0 : 4" << finl;
file.syncfile(); file.syncfile();
file << "pe0 : end" << finl; // le processeur 1 n'ecrit pas de donnees
file.syncfile(); file.syncfile();
Contenu du fichier :
pe0 : 1
pe0 : 2
pe1 : 1
pe1 : 2
pe0 : 3
pe0 : 4
pe1 : 3
pe0 : end.
< Faire coucou au processeur p pour qu'il envoie ses donnees
Reimplemented from Sortie.
Definition at line 182 of file EcrFicPartage.cpp.
{
// En mode ascii, les donnees sont converties en ascii lors de l'ecriture dans
// le buffer. Une deuxieme conversion a lieu lors de l'ecriture sur disque
// (selon le systeme d'exploitation, '\n' est code differemment par exemple)
// Donc, en ascii, on utilisera
// file << buffer;
// et en binaire
// file.write(buffer, size);
// Or file << buffer determine la longueur du buffer en cherchant de caractere '\0'
// Par consequent, en ascii, il faut que le buffer finisse par un caractere '\0'
// que l'on ajoute ici:
  if (! bin_)
    {
      get_obuffer().put_null_char();
    }
  const Comm_Group& group = PE_Groups::current_group();
  if(je_suis_maitre())
    {
      int p;
      const int nb_proc = nproc();
      for(p=0; p<nb_proc; p++)
        {
          const char * buffer_data = 0;
          char * allocated_buffer = 0;
          int buf_size;
// On recupere les donnees du processeur p, soit directement (p==me()),
// soit par communication :
          if (p == me())
            {
// Ecriture de mes propres donnees : je les prends dans le buffer.
// Ce pointeur peut etre nul:
              buffer_data = get_obuffer().str();
              buf_size = get_obuffer().len();
            }
          else
            {
// Ecriture des donnees d'un autre processeur, je les recupere.
              int dummy = 0;
              envoyer(dummy, p, 100); //!< Faire coucou au processeur p pour qu'il envoie ses donnees
              recevoir(buf_size, p, 100);
              if (buf_size > 0)
                {
                  buffer_data = allocated_buffer = new char[buf_size];
                  group.recv(p, allocated_buffer, buf_size, 100);
                }
            }
// Ecriture dans le fichier disque
          if (buf_size > 0)
            {
              assert(buffer_data);
              ostream& os = get_ostream();
              if (bin_)
                {
// Ecriture binaire sans conversion :
                  statistiques().begin_count(IO_EcrireFicPartageBin_counter_);
                  os.write(buffer_data, buf_size);
                  statistiques().end_count(IO_EcrireFicPartageBin_counter_, buf_size);
                }
              else
                {
// On verifie que le buffer finit bien par un caractere 0 :
                  assert(buffer_data[buf_size-1] == 0);
// Ecriture de buffer_data comme une chaine
// (conversion des \n sur certains systemes, etc...)
                  os << buffer_data;
                }
            }
          if (allocated_buffer)
            delete[] allocated_buffer;
        }
// Force a tout ecrire sur le disque tout de suite:
// (appel a la fonction flush de bas niveau, pas celle de trio).
      get_ostream().flush();
    }
  else
    {
// Envoi du buffer au processeur maitre:
// On attend qu'il demande les donnees pour ne pas engorger le reseau :
// (sinon tous les processeurs envoient simultanement leurs donnees)
      int dummy;
      recevoir(dummy, 0, 100);
      int buf_size = get_obuffer().len();
      envoyer(buf_size, 0, 100);
// Si la taille est non nulle, on envoie le buffer :
      if (buf_size > 0)
        {
          const char * buffer_data = get_obuffer().str();
          group.send(0, buffer_data, buf_size, 100);
        }
    }
// On vide le buffer :
  get_obuffer().new_buffer();
  return *this;
}
References Statistiques::begin_count(), Sortie::bin_, PE_Groups::current_group(), Statistiques::end_count(), envoyer(), get_obuffer(), Sortie::get_ostream(), IO_EcrireFicPartageBin_counter_, Process::je_suis_maitre(), OBuffer::len(), Process::me(), OBuffer::new_buffer(), Process::nproc(), OBuffer::put_null_char(), recevoir(), Comm_Group::recv(), Comm_Group::send(), statistiques(), and OBuffer::str().
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), close(), Zone_VEF_PreP1b::construire_ok_arete(), Statistiques::dump(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Lml::ecrire_entete_lml(), Equation_base::ecrire_fichier_xyz(), Format_Post_Lml::ecrire_item_int_lml(), Format_Post_Lml::ecrire_temps_lml(), Format_Post_Lml::finir_lml(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and ouvrir().
taille_memoire()
unsigned EcrFicPartage::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in EcrFicPartageBin.
Definition at line 24 of file EcrFicPartage.cpp.
unlockfile()
Sortie & EcrFicPartage::unlockfile () override virtual
Permet de debloquer la ressource critique pour leprocessus suivant.
Le processus appelant, sauf si c'est le premier processus du groupe, envoie
sa position courante au precessus suivant dans le groupe. Cette methode est
a appeler apres chaque ecriture dans le fichier.
Returns
Sortie&
Signification: *this
Reimplemented from Sortie.
Definition at line 151 of file EcrFicPartage.cpp.
{
  return *this;
}
Referenced by Format_Post_Lml::ecrire_champ_lml(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Equation_base::ecrire_fichier_xyz(), and Format_Post_Lml::ecrire_item_int_lml().
Member Data Documentation
info_obj
const Type_info EcrFicPartage::info_obj static
Definition at line 41 of file EcrFicPartage.h.
nom_fic_
Nom EcrFicPartage::nom_fic_ protected
Definition at line 79 of file EcrFicPartage.h.
Referenced by close(), and ouvrir().
obuffer_ptr_
OBuffer* EcrFicPartage::obuffer_ptr_ private
Pointeur : permet de ne pas inclure OBuffer.h.
Definition at line 83 of file EcrFicPartage.h.
Referenced by EcrFicPartage(), get_obuffer(), and ~EcrFicPartage().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EcrFicPartage.h
src/Kernel/Utilitaires/EcrFicPartage.cpp