TRUST: Format_Post_Lml Class Reference
Format_Post_Lml Class Reference
:
Classe de postraitement des champs euleriens au format lml.
#include <Format_Post_Lml.h>
Public Member Functions
~Format_Post_Lml ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void reset () override
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
void set_param (Param &param) override
int initialize_by_default (const Nom &file_basename) override
Initialisation de la classe avec des parametres par
defaut.
int initialize (const Nom &file_basename, const int format, const Nom &option_para) override
int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override
int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post) override
int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override
int finir (int &est_le_dernier_post) override
int ecrire_domaine (const Domaine &domaine, const int est_le_premie_post) override
voir Format_Post_base::ecrire_domaine
int ecrire_temps (const double temps) override
commence l'ecriture d'un nouveau pas de temps
En l'occurence pour le format Lml:
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx"
int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data) override
voir Format_Post_base::ecrire_champ
int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size) override
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
Format_Post_Lml ()
Constructeur par defaut:
Specifier dans commentaire ce qui est fixe par defaut.
Public Member Functions inherited from Format_Post_base
Format_Post_base ()
~Format_Post_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void reset ()=0
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int initialize_by_default (const Nom &file_basename)
Initialise le fichier avec des parametres appropries pour son
format (exemple: format ascii, efface le fichier existant, un
fichier unique pour tous les processeurs etc...)
Methode a surcharger dans les classes derivees.
Valeur de retour: 1 si l'operation a reussi, 0 sinon.
virtual int initialize (const Nom &file_basename, const int format, const Nom &option_para)
virtual int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit)
virtual int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post)
virtual int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post)
virtual int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init)
virtual int test_coherence (const int champs, const int stat, const double dt_ch, const double dt_stat)
virtual int init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine &domaine)
virtual int finir_ecriture (double temps_courant)
virtual int finir (int &est_le_dernier_post)
virtual int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post)
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
virtual int ecrire_domaine_dis (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const int est_le_premier_post)
virtual int ecrire_temps (const double temps)
Commence l'ecriture d'un pas de temps. La classe derivee doit accepter
de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
virtual int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data)
Ecriture d'un champ dans le fichier de postraitement.
Parametre: id_du_champ
Signification:
identifiant du champ (permet d'identifier un champ unique si on donne
en plus un numero de pas de temps)
Parametre: id_du_domaine
Signification:
identifiant du domaine sur lequel le champ est defini
Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
Parametre: localisation
Signification:
localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de
tableau deja ecrit)
(tout n'est pas obligatoirement supporte par tous les postraitements)
Parametre: data
Signification:
tableau de valeurs a postraiter. Le nombre de lignes du tableau
doit etre egal au nombre de lignes du tableau "localisation"
(nombre de sommets, d'elements ou de faces ou autre).
Valeur de retour: 1 si operation reussie, 0 sinon (par exemple,
preconditions non remplies ou fonctionnalite non supportee par le
format).
virtual int ecrire_champ2 (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data, const DoubleTab &coord)
virtual int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size)
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
void postraiter_debug_valeurs_un_instant (const Nom &nom_fich, const Domaine &dom, const Zone_dis_base &zone_dis, double temps_champ, double temps_courant, const Nom &id_champ_post, const Nature_du_champ &nature_champ, const Noms &noms_compos, const Noms &unites, const Motcle &loc_post, const DoubleTab &data, int ncomp=-1, int axi=0, int champ=1, int stat=0, double dt_ch=1., double dt_stat=1., int reprise=0, int est_le_premier_post=1, int est_le_dernier_post=1, double t_init=0., double temps_post=-2)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Format_Post_Lml & self_cast (Objet_U &)
static const Format_Post_Lml & self_cast (const Objet_U &)
static int ecrire_domaine_lml (const Domaine &domaine, Nom &nom_fic)
static int ecrire_temps_lml (const double temps, Nom &nom_fic)
static int ecrire_champ_lml (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const DoubleTab &data, Nom &nom_fic)
static int ecrire_item_int_lml (const Nom &id_item, const Nom &id_zone, const IntVect &data, const Nom &nom_fic)
static int ecrire_entete_lml (Nom &nom_fic, const int est_le_premier_post)
static int finir_lml (Nom &nom_fic, const int est_le_dernier_post)
static int completer_post_lml ()
static int preparer_post_lml ()
Static Public Member Functions inherited from Format_Post_base
static const Type_info * info ()
static Format_Post_base & self_cast (Objet_U &)
static const Format_Post_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Format_Post_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier basename_sans_extension
}.
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom lml_basename_
Detailed Description
:
Classe de postraitement des champs euleriens au format lml.
Definition at line 45 of file Format_Post_Lml.h.
Constructor & Destructor Documentation
~Format_Post_Lml()
Format_Post_Lml::~Format_Post_Lml ()
Definition at line 19 of file Format_Post_Lml.cpp.
Format_Post_Lml()
Format_Post_Lml::Format_Post_Lml ()
Constructeur par defaut:
Specifier dans commentaire ce qui est fixe par defaut.
Definition at line 35 of file Format_Post_Lml.cpp.
{
  reset();
}
References reset().
Member Function Documentation
completer_post()
int Format_Post_Lml::completer_post (const Domaine & dom, const int axi, const Nature_du_champ & nature, const int nb_compo, const Noms & noms_compo, const Motcle & loc_post, const Nom & le_nom_champ_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 112 of file Format_Post_Lml.cpp.
{
  completer_post_lml();
  return 1;
}
References completer_post_lml().
completer_post_lml()
int Format_Post_Lml::completer_post_lml () static
Definition at line 249 of file Format_Post_Lml.cpp.
{
  return 1;
}
Referenced by completer_post().
cree_instance()
Objet_U * Format_Post_Lml::cree_instance () static
Definition at line 19 of file Format_Post_Lml.cpp.
duplique()
int Format_Post_Lml::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Format_Post_Lml.cpp.
ecrire_champ()
int Format_Post_Lml::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, double temps_courant, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) override virtual
voir Format_Post_base::ecrire_champ
Reimplemented from Format_Post_base.
Definition at line 164 of file Format_Post_Lml.cpp.
{
// Appel de la methode statique specifique au format lml
  Nom nom_fich(lml_basename_);
  nom_fich +=".";
  Nom format="lml";
  nom_fich += format;
  ecrire_champ_lml(domaine,unite_,noms_compo,ncomp,temps_,id_champ,id_du_domaine,localisation,valeurs,nom_fich);
  return 1;
}
References ecrire_champ_lml(), and lml_basename_.
ecrire_champ_lml()
int Format_Post_Lml::ecrire_champ_lml (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const DoubleTab & data, Nom & nom_fic) static
Definition at line 457 of file Format_Post_Lml.cpp.
{
  EcrFicPartage os;
  os.ouvrir(nom_fich,ios::app);
  Nom nom_top("Topologie_");
  nom_top+= domaine.zone(0).le_nom();
  nom_top+="_";
  nom_top+=domaine.le_nom();
  int dim = domaine.les_sommets().dimension(1);
  Nom nom_post = id_du_champ;
  Nom nom_dom= domaine.le_nom();
  if (ncomp==-1)
    {
      int nb_compo_ = data.nb_dim()>1 ? data.dimension(1) : 1;
      if(localisation=="SOM")
        {
          int nb_som = domaine.nb_som();
          int nb_som_tot = Process::mp_sum(nb_som);
          int nb_som_PE = mppartial_sum(nb_som);
          if (dim==2)
            {
              nb_som_tot*=2;
              nb_som_PE*=2;
            }
          int nb_compo_dv = (nb_compo_==2 ? 3 : nb_compo_);
          if(je_suis_maitre())
            {
              os << "CHAMPPOINT " << nom_post << " " << nom_top << " " << temps_ << finl;
              os << nom_post << " " << nb_compo_dv << " " << unite_[0] << " "
                 << "type0" << " " << nb_som_tot << finl;
            }
          os.lockfile();
          for (int i=0; i<4-dim; i++)
            for (int j = 0; j < nb_som; j++)
              {
                os << i * nb_som + j + 1 + nb_som_PE << " ";
                for (int comp = 0; comp < nb_compo_; comp++)
                  os << data(j, comp) << " ";
                if (nb_compo_ == 2) os << "0.";
                os << finl;
              }
          os.unlockfile();
          os.syncfile();
        }
      else if(localisation=="ELEM")
        {
          const Zone& zone=domaine.zone(0);
          int nb_elem=zone.nb_elem();
          int nb_elem_tot = Process::mp_sum(nb_elem);
          int nb_elem_PE = mppartial_sum(nb_elem);
          for (int comp=0; comp<nb_compo_; comp++)
            {
              if (je_suis_maitre())
                {
                  os << "CHAMPMAILLE ";
                  os << (nb_compo_ == 1 ? nom_post : noms_compo[comp]) << " " << nom_top << " " << temps_ << finl;
                  os << (nb_compo_ == 1 ? nom_post : noms_compo[comp]) << " " << (int)1 << " " << unite_[comp] << " " ;
                  os << "type0" << " " << nb_elem_tot << finl;
                }
              os.lockfile();
              for (int j=0; j<nb_elem; j++)
                os << j+1+nb_elem_PE << " " << data(j,comp) << finl;
              os.unlockfile();
              os.syncfile();
            }
        }
      else
        {
          Cerr << "We do not know to postprocess " <<  id_du_champ
               << " with the keyword " << localisation << finl;
          return -1;
        }
    }
  else
    {
      if(localisation=="SOM")
        {
          int nb_som=domaine.nb_som();
          int nb_som_tot = Process::mp_sum(nb_som);
          int nb_som_PE = mppartial_sum(nb_som);
          if (dim==2)
            {
              nb_som_tot*=2;
              nb_som_PE*=2;
            }
          if(je_suis_maitre())
            {
              os << "CHAMPPOINT ";
              os << nom_post << " " << nom_top << " " << temps_ << finl;
              os << nom_post << " " << (int)1 << " " << unite_[ncomp] << " "
                 << "type0" << " " << nb_som_tot << finl;
            }
          os.lockfile();
          for (int i=0; i<4-dim; i++)
            for (int j=0; j<nb_som; j++)
              os << i*nb_som+j+1+nb_som_PE << " " << data(j) << finl;
          os.unlockfile();
          os.syncfile();
        }
      else if(localisation=="ELEM")
        {
          const Zone& zone=domaine.zone(0);
          int nb_elem=zone.nb_elem();
          int nb_elem_tot = Process::mp_sum(nb_elem);
          int nb_elem_PE = mppartial_sum(nb_elem);
          if(je_suis_maitre())
            {
              os << "CHAMPMAILLE ";
              os << nom_post << " " << nom_top << " " << temps_ << finl;
              os << nom_post << " " << (int)1 << " " << unite_[ncomp] << " " ;
              os << "type0" << " " << nb_elem_tot << finl;
            }
          os.lockfile();
          for (int j=0; j<nb_elem; j++)
            os << j+1+nb_elem_PE << " " << data(j) << finl;
          os.unlockfile();
          os.syncfile();
        }
      else
        {
          Cerr << "We do not know to postprocess " << id_du_champ
               << " with the keyword " << localisation << finl;
          return -1;
        }
    }
  return 1;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), finl, Process::je_suis_maitre(), Domaine::le_nom(), Zone::le_nom(), Domaine::les_sommets(), EcrFicPartage::lockfile(), Process::mp_sum(), mppartial_sum(), TRUSTTab< _TYPE_ >::nb_dim(), Zone::nb_elem(), Domaine::nb_som(), EcrFicPartage::ouvrir(), EcrFicPartage::syncfile(), EcrFicPartage::unlockfile(), and Domaine::zone().
Referenced by ecrire_champ().
ecrire_domaine()
int Format_Post_Lml::ecrire_domaine (const Domaine & domaine, const int est_le_premie_post) override virtual
voir Format_Post_base::ecrire_domaine
< ok tout va bien
Reimplemented from Format_Post_base.
Definition at line 134 of file Format_Post_Lml.cpp.
{
// Appel de la methode statique specifique au format lml
  Nom nom_fich(lml_basename_);
  nom_fich +=".";
  Nom format="lml";
  nom_fich += format;
  ecrire_domaine_lml(domaine,nom_fich);
  return 1; //!< ok tout va bien
}
References ecrire_domaine_lml(), and lml_basename_.
ecrire_domaine_lml()
int Format_Post_Lml::ecrire_domaine_lml (const Domaine & domaine, Nom & nom_fic) static
Definition at line 259 of file Format_Post_Lml.cpp.
{
// Actuellement copie identique de la methode Domaine::postraiter_lml()
  EcrFicPartage s;
  s.ouvrir(nom_fich,ios::app);
  Nom nom_grille("Grille_");
  nom_grille+= domaine.le_nom();
  if(je_suis_maitre())
    s << "GRILLE" << finl;
  int nb_som_tot = Process::mp_sum(domaine.nb_som());
  int dim = domaine.les_sommets().dimension(1);
// Ecriture des coordonnees des noeuds
// Toutes les grandeurs qui apparaissent dans le .lml doivent
// etre exprimees dans le repere des coordonnees cartesiennes
// Si l'option Axi a ete choisie on recalcule les coordonnees
// cartesiennes a partir des coordonnees cylindriques.
  if (axi)
    {
// Ecriture des noeuds du maillage
      if ( dim == 3)
        {
          if(je_suis_maitre())
            s << nom_grille << " " << "3 " << nb_som_tot << "" << finl;
          s.lockfile();
          for (int nsom=0; nsom<domaine.nb_som(); nsom++)
            {
              s << domaine.coord(nsom,0)*cos(domaine.coord(nsom,1)) << " "
                << domaine.coord(nsom,0)*sin(domaine.coord(nsom,1)) << " "
                << domaine.coord(nsom,2) << "" << finl;
            }
          s.unlockfile();
          s.syncfile();
        }
      else if ( dim == 2)
        {
          if(je_suis_maitre())
            s << nom_grille << " " << "3 " << 2*nb_som_tot << "" << finl;
          s.lockfile();
// Ecriture des noeuds du maillage
          int nsom;
          for (nsom=0; nsom<domaine.nb_som(); nsom++)
            {
              s << domaine.coord(nsom,0)*cos(domaine.coord(nsom,1)) << " "
                << domaine.coord(nsom,0)*sin(domaine.coord(nsom,1)) << " "
                <<  0. << "" << finl;
            }
          for (nsom=0; nsom<domaine.nb_som(); nsom++)
            {
              s << domaine.coord(nsom,0)*cos(domaine.coord(nsom,1)) << " "
                << domaine.coord(nsom,0)*sin(domaine.coord(nsom,1)) << " "
                << 1. << "" << finl;
            }
          s.unlockfile();
          s.syncfile();
        }
    }
  else
    {
// Ecriture des noeuds du maillage
      if ( dim == 3)
        {
          if(je_suis_maitre())
            s << nom_grille << " " << "3 " << nb_som_tot << "" << finl;
          s.lockfile();
          for (int nsom=0; nsom<domaine.nb_som(); nsom++)
            {
              for (int j=0; j<3; j++)
                s << domaine.coord(nsom, j) << " " ;
              s << "" << finl;
            }
          s.unlockfile();
          s.syncfile();
        }
      else if ( dim == 2)
        {
          if(je_suis_maitre())
            s << nom_grille << " " << "3 " << 2*nb_som_tot << "" << finl;
          s.lockfile();
// Ecriture des noeuds du maillage
          int nsom;
          for (nsom=0; nsom<domaine.nb_som(); nsom++)
            {
              s << domaine.coord(nsom,0) << " "
                << domaine.coord(nsom,1) << " "
                << 0. << "" << finl;
            }
          for (nsom=0; nsom<domaine.nb_som(); nsom++)
            {
              s << domaine.coord(nsom,0) << " "
                << domaine.coord(nsom,1) << " "
                << 1. << "" << finl;
            }
          s.unlockfile();
          s.syncfile();
        }
    }
// Actuellement copie identique de la methode Zone::postraiter_lml()
//
  int j;
  int nsom = domaine.nb_som();
  int nb_elem_tot = Process::mp_sum(domaine.zone(0).nb_elem());
  Nom nom_top("Topologie_");
  nom_top+= domaine.zone(0).le_nom();
  nom_top+="_";
  nom_top+=domaine.le_nom();
  Nom type_maille=domaine.zone(0).type_elem().nom_lml();
// Ajout pour modification syntaxe ci-dessous
  int nb_elem = domaine.zone(0).nb_elem() ;
  int nb_som_elem = domaine.zone(0).nb_som_elem();
  const IntTab& sommet_elem = domaine.zone(0).les_elems();
  int nb_som_PE = mppartial_sum(nsom);
  if(je_suis_maitre())
    {
      s << "TOPOLOGIE" << finl;
      s << nom_top << " " << nom_grille << "" << finl;
      s <<  "MAILLE" << finl;
      s << nb_elem_tot << "" << finl;
    }
// Ecriture des elements du maillage
  if (dim == 3 )
    {
      s.lockfile();
      for (int nelem=0; nelem<nb_elem; nelem++)
        {
          s << type_maille << " ";
          for (j=0; j<nb_som_elem; j++)
            s << sommet_elem(nelem,j)+1+nb_som_PE << " " ;
          s << "" << finl;
        }
      s.unlockfile();
      s.syncfile();
    }
  else if ( dim == 2)
    {
      s.lockfile();
      for (int nelem=0; nelem<nb_elem; nelem++)
        {
          s << type_maille << " ";
          int count = 0;
          for (j=0; j<nb_som_elem && (sommet_elem( nelem,j) > -1); j++)
            s << sommet_elem( nelem,j)+1+2*nb_som_PE << " ", count++;
          for (j=0; j<nb_som_elem && (sommet_elem( nelem,j) > -1); j++)
            s << sommet_elem( nelem,j)+1+2*nb_som_PE+nsom << " ", count++;
          for (int k = count; k < 2 * nb_som_elem; k++) s << (int)0 << " ";
          s << "" << finl;
          s.flush();
        }
      s.unlockfile();
      s.syncfile();
    }
  if(je_suis_maitre())
    {
      s <<  "FACE" << finl ;
      s << (int)0 << "" << finl;
    }
//
  s.flush();
  s.syncfile();
  return 1;
}
References Objet_U::axi, Domaine::coord(), TRUSTTab< _TYPE_ >::dimension(), finl, EcrFicPartage::flush(), Process::je_suis_maitre(), Domaine::le_nom(), Zone::le_nom(), Zone::les_elems(), Domaine::les_sommets(), EcrFicPartage::lockfile(), Process::mp_sum(), mppartial_sum(), Zone::nb_elem(), Domaine::nb_som(), Zone::nb_som_elem(), Elem_geom::nom_lml(), EcrFicPartage::ouvrir(), EcrFicPartage::syncfile(), Zone::type_elem(), EcrFicPartage::unlockfile(), and Domaine::zone().
Referenced by ecrire_domaine().
ecrire_entete()
int Format_Post_Lml::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 86 of file Format_Post_Lml.cpp.
{
  Nom nom_fich(lml_basename_);
  nom_fich +=".";
  Nom format="lml";
  nom_fich += format;
  ecrire_entete_lml(nom_fich,est_le_premier_post);
  return 1;
}
References ecrire_entete_lml(), and lml_basename_.
ecrire_entete_lml()
int Format_Post_Lml::ecrire_entete_lml (Nom & nom_fic, const int est_le_premier_post) static
Definition at line 207 of file Format_Post_Lml.cpp.
{
  if (est_le_premier_post)
    {
      EcrFicPartage s;
      s.ouvrir(nom_fich);
      if (Process::je_suis_maitre())
        {
          s << "Trio_U" << " " << "Version "  << "1" << finl;
          s << nom_du_cas() << finl;
          s << "Trio_U" << finl;
        }
      s.flush();
      s.syncfile();
    }
  return 1;
}
References finl, EcrFicPartage::flush(), Process::je_suis_maitre(), Objet_U::nom_du_cas(), EcrFicPartage::ouvrir(), and EcrFicPartage::syncfile().
Referenced by ecrire_entete().
ecrire_item_int()
int Format_Post_Lml::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_zone, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) override virtual
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
Reimplemented from Format_Post_base.
Definition at line 186 of file Format_Post_Lml.cpp.
{
  Nom nom_fich(lml_basename_);
  nom_fich +=".";
  Nom format="lml";
  nom_fich += format;
  Nom id_zone_dom(id_zone);
  id_zone_dom+="_";
  id_zone_dom+=id_du_domaine;
  ecrire_item_int_lml(id_item,id_zone,valeurs,nom_fich);
  return 1;
}
References ecrire_item_int_lml(), and lml_basename_.
ecrire_item_int_lml()
int Format_Post_Lml::ecrire_item_int_lml (const Nom & id_item, const Nom & id_zone, const IntVect & data, const Nom & nom_fic) static
Definition at line 594 of file Format_Post_Lml.cpp.
{
  EcrFicPartage os;
  os.ouvrir(nom_fic,ios::app);
  Nom nom_vect(id_item);
  nom_vect += "_elem_dom";
  Nom nom_topologie("Topologie_");
  nom_topologie+= id_zone;
// Actuellement temp_courant n est pas passe en argument
//
  const IntTab* intT = dynamic_cast<const IntTab*>(&vect);
  if (intT)
    {
      const IntTab& tab = *intT;
      os.lockfile();
      os << nom_vect << tab.dimension(1) << " 1 " << " type0 " << tab.dimension(0) << finl;
      os.unlockfile();
      os.syncfile();
      {
        int tab_dimension0_opt=tab.dimension(0);
        os.lockfile();
        for (int i=0; i<tab_dimension0_opt; i++)
          {
            for (int j=0; j<tab.dimension(1); j++)
              {
                int tab_dimension1_opt=tab.dimension(1);
                for (int j2=0; j2<tab_dimension1_opt; j2++)
                  os << i+1 << " " << tab(i,j2) << " ";
              }
            os << finl;
          }
        os.unlockfile();
        os.syncfile();
      }
    }
  else
    {
      os.lockfile();
      os << nom_vect << " 1" << " 1 " << " type0 " << vect.size() << finl;
      for (int i=0; i<vect.size(); i++)
        os << i+1 << " " << vect(i) << finl;
      os.unlockfile();
      os.syncfile();
    }
  os.flush();
  os.syncfile();
  return 1;
}
References TRUSTTab< _TYPE_ >::dimension(), finl, EcrFicPartage::flush(), EcrFicPartage::lockfile(), EcrFicPartage::ouvrir(), TRUSTVect< _TYPE_ >::size(), EcrFicPartage::syncfile(), and EcrFicPartage::unlockfile().
Referenced by ecrire_item_int().
ecrire_temps()
int Format_Post_Lml::ecrire_temps (const double temps) override virtual
commence l'ecriture d'un nouveau pas de temps
En l'occurence pour le format Lml:
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx"
Reimplemented from Format_Post_base.
Definition at line 149 of file Format_Post_Lml.cpp.
{
  Nom nom_fich(lml_basename_);
  nom_fich +=".";
  Nom format="lml";
  nom_fich += format;
  ecrire_temps_lml(temps,nom_fich);
  return 1;
}
References ecrire_temps_lml(), and lml_basename_.
ecrire_temps_lml()
int Format_Post_Lml::ecrire_temps_lml (const double temps, Nom & nom_fic) static
Definition at line 444 of file Format_Post_Lml.cpp.
{
  EcrFicPartage s;
  s.ouvrir(nom_fich,ios::app);
  if (je_suis_maitre())
    s << "TEMPS " << temps << finl;
  s.flush();
  s.syncfile();
  return 1;
}
References finl, EcrFicPartage::flush(), Process::je_suis_maitre(), EcrFicPartage::ouvrir(), and EcrFicPartage::syncfile().
Referenced by ecrire_temps().
finir()
int Format_Post_Lml::finir (int & est_le_dernier_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 99 of file Format_Post_Lml.cpp.
{
  Nom nom_fich(lml_basename_);
  nom_fich +=".";
  Nom format="lml";
  nom_fich += format;
  finir_lml(nom_fich,est_le_dernier_post);
  return 1;
}
References finir_lml(), and lml_basename_.
finir_lml()
int Format_Post_Lml::finir_lml (Nom & nom_fic, const int est_le_dernier_post) static
Definition at line 229 of file Format_Post_Lml.cpp.
{
  EcrFicPartage s;
  s.ouvrir(nom_fich,ios::app);
  if (est_le_dernier_post)
    {
      if (Process::je_suis_maitre())
        {
          s << "FIN" << finl;
        }
    }
  s.flush();
  s.syncfile();
  return 1;
}
References finl, EcrFicPartage::flush(), Process::je_suis_maitre(), EcrFicPartage::ouvrir(), and EcrFicPartage::syncfile().
Referenced by finir().
get_info()
const Type_info * Format_Post_Lml::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Format_Post_base.
Definition at line 19 of file Format_Post_Lml.cpp.
info()
const Type_info * Format_Post_Lml::info () static
Definition at line 19 of file Format_Post_Lml.cpp.
initialize()
int Format_Post_Lml::initialize (const Nom & file_basename, const int format, const Nom & option_para) override virtual
Reimplemented from Format_Post_base.
Definition at line 79 of file Format_Post_Lml.cpp.
{
  lml_basename_= file_basename;
  return 1;
}
References lml_basename_.
initialize_by_default()
int Format_Post_Lml::initialize_by_default (const Nom & file_basename) override virtual
Initialisation de la classe avec des parametres par
defaut.
Reimplemented from Format_Post_base.
Definition at line 73 of file Format_Post_Lml.cpp.
{
  lml_basename_= file_basename;
  return 1;
}
References lml_basename_.
preparer_post()
int Format_Post_Lml::preparer_post (const Nom & id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override virtual
Reimplemented from Format_Post_base.
Definition at line 122 of file Format_Post_Lml.cpp.
{
  preparer_post_lml();
  return 1;
}
References preparer_post_lml().
preparer_post_lml()
int Format_Post_Lml::preparer_post_lml () static
Definition at line 254 of file Format_Post_Lml.cpp.
{
  return 1;
}
Referenced by preparer_post().
printOn()
Sortie & Format_Post_Lml::printOn (Sortie & x) const override protected virtual
erreur => exit
Reimplemented from Format_Post_base.
Definition at line 48 of file Format_Post_Lml.cpp.
{
  Cerr << "Format_Post_Lml::printOn : error" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Format_Post_Lml::readOn (Entree & is) override protected virtual
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier basename_sans_extension
}.
Reimplemented from Format_Post_base.
Definition at line 60 of file Format_Post_Lml.cpp.
{
  Format_Post_base::readOn(is);
  return is;
}
References Format_Post_base::readOn().
reset()
void Format_Post_Lml::reset () override virtual
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
Implements Format_Post_base.
Definition at line 42 of file Format_Post_Lml.cpp.
{
  lml_basename_ = "??";
}
References lml_basename_.
Referenced by Format_Post_Lml().
self_cast() [1/2]
const Format_Post_Lml & Format_Post_Lml::self_cast (const Objet_U & r) static
Definition at line 19 of file Format_Post_Lml.cpp.
self_cast() [2/2]
Format_Post_Lml & Format_Post_Lml::self_cast (Objet_U & r) static
Definition at line 19 of file Format_Post_Lml.cpp.
set_param()
void Format_Post_Lml::set_param (Param & param) override virtual
Implements Format_Post_base.
Definition at line 66 of file Format_Post_Lml.cpp.
{
  param.ajouter("nom_fichier",&lml_basename_,Param::REQUIRED);
}
References Param::ajouter(), lml_basename_, and Param::REQUIRED.
taille_memoire()
unsigned Format_Post_Lml::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Format_Post_Lml.cpp.
Member Data Documentation
info_obj
const Type_info Format_Post_Lml::info_obj static
Definition at line 47 of file Format_Post_Lml.h.
lml_basename_
Nom Format_Post_Lml::lml_basename_ protected
Definition at line 86 of file Format_Post_Lml.h.
Referenced by ecrire_champ(), ecrire_domaine(), ecrire_entete(), ecrire_item_int(), ecrire_temps(), finir(), initialize(), initialize_by_default(), reset(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Format_Post_Lml.h
src/Kernel/Framework/Format_Post_Lml.cpp