TRUST: Op_Diff_CoviMAC_Elem Class Reference
Op_Diff_CoviMAC_Elem Class Reference
: class Op_Diff_CoviMAC_Elem
<Description of class Op_Diff_CoviMAC_Elem>
#include <Op_Diff_CoviMAC_Elem.h>
Public Member Functions
~Op_Diff_CoviMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Diff_CoviMAC_Elem ()
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
int has_interface_blocs () const
double calculer_dt_stab () const
Calcul dt_stab.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_CoviMAC_Elem & self_cast (Objet_U &)
static const Op_Diff_CoviMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
: class Op_Diff_CoviMAC_Elem
<Description of class Op_Diff_CoviMAC_Elem>
Definition at line 37 of file Op_Diff_CoviMAC_Elem.h.
Constructor & Destructor Documentation
Op_Diff_CoviMAC_Elem::~Op_Diff_CoviMAC_Elem ()
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
Op_Diff_CoviMAC_Elem::Op_Diff_CoviMAC_Elem ()
Definition at line 49 of file Op_Diff_CoviMAC_Elem.cpp.
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
{
  declare_support_masse_volumique(1);
}
Member Function Documentation
void Op_Diff_CoviMAC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Operateur_base.
double Op_Diff_CoviMAC_Elem::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 113 of file Op_Diff_CoviMAC_Elem.cpp.
References Process::abort(), Op_Diff_CoviMAC_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), IntTab::dimension(), DoubleTab::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_CoviMAC::face_normales(), Equation_base::inconnue(), Op_Diff_CoviMAC_base::la_zone_poly_, min(), Process::mp_min(), Zone_dis_base::nb_elem(), Op_Diff_CoviMAC_base::nu_, Zone_CoviMAC::nu_dot(), Zone_VF::porosite_elem(), ref_cast, sub_type, Op_Diff_CoviMAC_base::update_nu_invh(), Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces();
  const DoubleTab& nf = zone.face_normales(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL,
                    &diffu = diffusivite_pour_pas_de_temps().valeurs(), &lambda = diffusivite().valeurs();
  const DoubleVect& pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  update_nu_invh();
  int i, e, f, n, N = equation().inconnue().valeurs().dimension(1), cD = diffu.dimension(0) == 1, cL = lambda.dimension(0) == 1;
  double dt = 1e10;
  DoubleTrav flux(N);
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++) for (n = 0; n < N; n++)
          flux(n) += zone.nu_dot(&nu_, e, n, &nf(f, 0), &nf(f, 0)) / vf(f);
      for (n = 0; n < N; n++) if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) /* sous 0.5e-6, on suppose que l'evanescence fait le job */
          dt = min(dt, pe(e) * ve(e) * (alp ? (*alp)(e, n) : 1) * (lambda(!cL * e, n) / diffu(!cD * e, n)) / flux(n));
      if (dt < 0) abort();
    }
  return Process::mp_min(dt);
}
void Op_Diff_CoviMAC_Elem::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_CoviMAC_base.
Definition at line 94 of file Op_Diff_CoviMAC_Elem.cpp.
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente(), Cerr, Modele_turbulence_scal_base::conductivite_turbulente(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Equation_base::get_modele(), Equation_base::inconnue(), Op_Diff_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), O_U_Ptr::non_nul(), ref_cast, DoubleTab::resize(), TURBULENCE, Ref_Objet_U::valeur(), Ref_Zone_CoviMAC::valeur(), Deriv_Champ_Inc_base::valeur(), and Champ_Inc_base::valeurs().
{
  Op_Diff_CoviMAC_base::completer();
  const Equation_base& eq = equation();
  const Champ_P0_CoviMAC& ch = ref_cast(Champ_P0_CoviMAC, eq.inconnue().valeur());
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Diff_CoviMAC_Elem : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  flux_bords_.resize(zone.premiere_face_int(), ch.valeurs().line_size());
  const RefObjU& modele_turbulence = eq.get_modele(TURBULENCE);
  if (modele_turbulence.non_nul())
    {
      const Modele_turbulence_scal_base& mod_turb = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
      const Champ_Fonc& lambda_t = mod_turb.conductivite_turbulente();
      associer_diffusivite_turbulente(lambda_t);
    }
}
Objet_U * Op_Diff_CoviMAC_Elem::cree_instance () [static]
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
void Op_Diff_CoviMAC_Elem::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Operateur_base.
int Op_Diff_CoviMAC_Elem::duplique () const [virtual]
Implements Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
const Type_info * Op_Diff_CoviMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
int Op_Diff_CoviMAC_Elem::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 48 of file Op_Diff_CoviMAC_Elem.h.
  {
    return 1;
  };
const Type_info * Op_Diff_CoviMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
void Op_Diff_CoviMAC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 57 of file Op_Diff_CoviMAC_Elem.h.
{ };
Sortie & Op_Diff_CoviMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 54 of file Op_Diff_CoviMAC_Elem.cpp.
{
  return Op_Diff_CoviMAC_base::printOn( os );
}
Entree & Op_Diff_CoviMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 74 of file Op_Diff_CoviMAC_Elem.cpp.
{
  return Op_Diff_CoviMAC_base::readOn( is );
}
Op_Diff_CoviMAC_Elem & Op_Diff_CoviMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
const Op_Diff_CoviMAC_Elem & Op_Diff_CoviMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
unsigned Op_Diff_CoviMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 44 of file Op_Diff_CoviMAC_Elem.cpp.
Member Data Documentation
const Type_info Op_Diff_CoviMAC_Elem::info_obj [static]
Reimplemented from Op_Diff_CoviMAC_base.
Reimplemented in Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, and Op_Dift_Nonlinear_CoviMAC_Elem.
Definition at line 40 of file Op_Diff_CoviMAC_Elem.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_Elem.h
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_Elem.cpp