TRUST: Ref_Zones_dis Class Reference
Ref_Zones_dis Class Reference
#include <Domaine_dis.h>
Public Member Functions
~Ref_Zones_dis ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zones_dis ()
Ref_Zones_dis (const Zones_dis &)
Ref_Zones_dis (const Ref_Zones_dis &)
const Zones_dis & valeur () const
Zones_dis & valeur ()
const Zones_dis * operator-> () const
Zones_dis * operator-> ()
const Ref_Zones_dis & operator= (const Zones_dis &)
const Ref_Zones_dis & operator= (const Ref_Zones_dis &)
operator const Zones_dis & () const
operator Zones_dis & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zones_dis & self_cast (Objet_U &)
static const Ref_Zones_dis & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zones_dis * pointeur_
Detailed Description
Definition at line 44 of file Domaine_dis.h.
Constructor & Destructor Documentation
Ref_Zones_dis::~Ref_Zones_dis ()
Definition at line 31 of file Domaine_dis.cpp.
Ref_Zones_dis::Ref_Zones_dis ()
Definition at line 31 of file Domaine_dis.cpp.
Ref_Zones_dis::Ref_Zones_dis (const Zones_dis & t)
Definition at line 31 of file Domaine_dis.cpp.
Ref_Zones_dis::Ref_Zones_dis (const Ref_Zones_dis & t)
Definition at line 31 of file Domaine_dis.cpp.
Member Function Documentation
Objet_U * Ref_Zones_dis::cree_instance () [static]
Definition at line 31 of file Domaine_dis.cpp.
int Ref_Zones_dis::duplique () const [virtual]
Implements Ref_.
Definition at line 31 of file Domaine_dis.cpp.
const Type_info * Ref_Zones_dis::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 31 of file Domaine_dis.cpp.
const Type_info & Ref_Zones_dis::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 31 of file Domaine_dis.cpp.
const Type_info * Ref_Zones_dis::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 31 of file Domaine_dis.cpp.
Ref_Zones_dis::operator const Zones_dis & () const
Definition at line 31 of file Domaine_dis.cpp.
Ref_Zones_dis::operator Zones_dis & ()
Definition at line 31 of file Domaine_dis.cpp.
const Zones_dis * Ref_Zones_dis::operator-> () const [inline]
Definition at line 44 of file Domaine_dis.h.
: public Objet_U
Zones_dis * Ref_Zones_dis::operator-> () [inline]
Definition at line 44 of file Domaine_dis.h.
: public Objet_U
const Ref_Zones_dis & Ref_Zones_dis::operator= (const Ref_Zones_dis & t)
Definition at line 31 of file Domaine_dis.cpp.
const Ref_Zones_dis & Ref_Zones_dis::operator= (const Zones_dis & t)
Definition at line 31 of file Domaine_dis.cpp.
Sortie & Ref_Zones_dis::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 31 of file Domaine_dis.cpp.
Entree & Ref_Zones_dis::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 31 of file Domaine_dis.cpp.
const Ref_Zones_dis & Ref_Zones_dis::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 31 of file Domaine_dis.cpp.
Ref_Zones_dis & Ref_Zones_dis::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 31 of file Domaine_dis.cpp.
void Ref_Zones_dis::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 31 of file Domaine_dis.cpp.
unsigned Ref_Zones_dis::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Domaine_dis.cpp.
const Zones_dis & Ref_Zones_dis::valeur () const [inline]
Definition at line 44 of file Domaine_dis.h.
Referenced by Domaine_dis::printOn(), Domaine_dis::readOn(), and Domaine_dis::zone_dis().
: public Objet_U
Zones_dis & Ref_Zones_dis::valeur () [inline]
Definition at line 44 of file Domaine_dis.h.
: public Objet_U
Member Data Documentation
const Type_info Ref_Zones_dis::info_obj [static]
Reimplemented from Ref_.
Definition at line 44 of file Domaine_dis.h.
Zones_dis* Ref_Zones_dis::pointeur_ [private]
Definition at line 44 of file Domaine_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Domaine_dis.h
src/Kernel/Framework/Domaine_dis.cpp