TRUST: Matrice_Diagonale Class Reference
Matrice_Diagonale Class Reference
Classe Matrice_Diagonale
Represente une matrice diagonale.
#include <Matrice_Diagonale.h>
Public Member Functions
~Matrice_Diagonale ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int ordre (void) const override
int nb_lignes (void) const override
int nb_colonnes (void) const override
DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const override
DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const override
DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const override
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void get_symmetric_stencil (IntTab &stencil) const override
void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const override
Matrice_Diagonale (void)
Matrice_Diagonale (int size)
Matrice_Diagonale (const DoubleVect &coefficients)
DoubleVect & get_coefficients (void)
const DoubleVect & get_coefficients (void) const
void dimensionner (int size)
double coeff (int i, int j) const
double & coeff (int i, int j)
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Diagonale & self_cast (Objet_U &)
static const Matrice_Diagonale & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleVect coefficients_
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Detailed Description
Classe Matrice_Diagonale
Represente une matrice diagonale.
Definition at line 31 of file Matrice_Diagonale.h.
Constructor & Destructor Documentation
~Matrice_Diagonale()
Matrice_Diagonale::~Matrice_Diagonale ()
Definition at line 19 of file Matrice_Diagonale.cpp.
Matrice_Diagonale() [1/3]
Matrice_Diagonale::Matrice_Diagonale (void)
Definition at line 171 of file Matrice_Diagonale.cpp.
                                           : Matrice_Base( ), coefficients_( )
{
  is_stencil_up_to_date_ = false ;
}
References Matrice_Base::is_stencil_up_to_date_.
Matrice_Diagonale() [2/3]
Matrice_Diagonale::Matrice_Diagonale (int size)
Definition at line 176 of file Matrice_Diagonale.cpp.
                                               : Matrice_Base( ), coefficients_( size )
{
  is_stencil_up_to_date_ = false ;
}
References Matrice_Base::is_stencil_up_to_date_.
Matrice_Diagonale() [3/3]
Matrice_Diagonale::Matrice_Diagonale (const DoubleVect & coefficients)
Definition at line 181 of file Matrice_Diagonale.cpp.
                                                                   : Matrice_Base( ), coefficients_( coefficients )
{
  is_stencil_up_to_date_ = false ;
}
References Matrice_Base::is_stencil_up_to_date_.
Member Function Documentation
ajouter_multTab_()
DoubleTab & Matrice_Diagonale::ajouter_multTab_ (const DoubleTab & x, DoubleTab & r) const override virtual
Implements Matrice_Base.
Definition at line 76 of file Matrice_Diagonale.cpp.
{
  if ( ( x.nb_dim() == 1 ) && ( r.nb_dim() == 1 ) )
    {
      ajouter_multvect_( x, r );
      return r;
    }
  assert( x.nb_dim( ) == 2 );
  assert( r.nb_dim( ) == 2 );
  const int size = coefficients_.size( );
  assert( x.dimension( 0 ) == size );
  assert( r.dimension( 0 ) == size );
  const int nb_components = x.dimension( 1 );
  assert( r.dimension( 1 ) == nb_components );
  for ( int i=0; i<size; ++i )
    {
      const double coefficient = coefficients_( i );
      for ( int j=0; j<nb_components; ++j )
        {
          r( i, j ) += x( i, j ) * coefficient;
        }
    }
  return r;
}
References ajouter_multvect_(), coefficients_, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::nb_dim(), and TRUSTVect< _TYPE_ >::size().
ajouter_multvect_()
DoubleVect & Matrice_Diagonale::ajouter_multvect_ (const DoubleVect & x, DoubleVect & r) const override virtual
Implements Matrice_Base.
Definition at line 48 of file Matrice_Diagonale.cpp.
{
  int count = coefficients_.size( );
  assert( x.size( ) ==count );
  assert( r.size( ) ==count );
  const double* c_ptr = coefficients_.addr( );
  const double* x_ptr = x.addr( );
  double* r_ptr = r.addr( );
  for ( ; count; count-- )
    {
      const double x_ = *x_ptr;
      const double c_ = *c_ptr;
      double& r_ = *( r_ptr++ );
      r_ += c_ * x_;
      x_ptr++;
    }
  return r;
}
References TRUSTArray< _TYPE_ >::addr(), coefficients_, and TRUSTVect< _TYPE_ >::size().
Referenced by ajouter_multTab_(), and ajouter_multvectT_().
ajouter_multvectT_()
DoubleVect & Matrice_Diagonale::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & r) const override virtual
Implements Matrice_Base.
Definition at line 71 of file Matrice_Diagonale.cpp.
{
  return ajouter_multvect_( x, r );
}
References ajouter_multvect_().
coeff() [1/2]
double & Matrice_Diagonale::coeff (int i, int j)
Definition at line 213 of file Matrice_Diagonale.cpp.
{
  if ( i==j )
    {
      return coefficients_[ i ];
    }
  Cerr << "Error in 'Matrice_Diagonale::coeff()':" << finl;
  Cerr << "  non-const access is only allowed for diagonal coefficients" << finl;
  Process::exit( );
  return coefficients_[ 0];
}
References Cerr, coefficients_, Process::exit(), and finl.
coeff() [2/2]
double Matrice_Diagonale::coeff (int i, int j) const
Definition at line 201 of file Matrice_Diagonale.cpp.
{
  if ( i==j )
    {
      return coefficients_[ i ];
    }
  else
    {
      return 0.0;
    }
}
References coefficients_.
Referenced by Solveur_U_P::iterer_NS().
cree_instance()
Objet_U * Matrice_Diagonale::cree_instance () static
Definition at line 19 of file Matrice_Diagonale.cpp.
dimensionner()
void Matrice_Diagonale::dimensionner (int size)
Definition at line 196 of file Matrice_Diagonale.cpp.
{
  coefficients_.resize( size );
}
References coefficients_, and TRUSTVect< _TYPE_ >::resize().
Referenced by Matrix_tools::allocate_from_stencil(), and Solveur_U_P::iterer_NS().
duplique()
int Matrice_Diagonale::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Matrice_Diagonale.cpp.
get_coefficients() [1/2]
DoubleVect & Matrice_Diagonale::get_coefficients (void)
Definition at line 186 of file Matrice_Diagonale.cpp.
{
  return coefficients_;
}
References coefficients_.
get_coefficients() [2/2]
const DoubleVect & Matrice_Diagonale::get_coefficients (void) const
Definition at line 191 of file Matrice_Diagonale.cpp.
{
  return coefficients_;
}
References coefficients_.
get_info()
const Type_info * Matrice_Diagonale::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Base.
Definition at line 19 of file Matrice_Diagonale.cpp.
get_stencil()
void Matrice_Diagonale::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Definition at line 111 of file Matrice_Diagonale.cpp.
{
  if( is_stencil_up_to_date_ )
    {
      stencil = stencil_;
      return;
    }
  const int size = ordre( );
  stencil.resize( size, 2 );
  for ( int i=0; i<size; ++i )
    {
      stencil( i, 0 ) = i;
      stencil( i, 1 ) = i;
    }
}
References Matrice_Base::is_stencil_up_to_date_, ordre(), TRUSTTab< _TYPE_ >::resize(), and Matrice_Base::stencil_.
Referenced by get_symmetric_stencil().
get_stencil_and_coefficients()
void Matrice_Diagonale::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Definition at line 135 of file Matrice_Diagonale.cpp.
{
  if( is_stencil_up_to_date_ )
    {
      if( coefficients_.size( ) == 0 )
        {
          Cerr << "Error in Matrice_Morse::get_stencil_and_coefficients( )"<<finl;
          Cerr << "  The coefficients are not filled."<<finl;
          Cerr << "  Aborting..." << finl;
          Process::abort( );
        }
      stencil = stencil_;
      coefficients  = coefficients_;
      return;
    }
  const int size = ordre( );
  stencil.resize( size, 2 );
  coefficients.resize_array( size );
  for ( int i=0; i<size; ++i )
    {
      stencil( i, 0 ) = i;
      stencil( i, 1 ) = i;
      coefficients[ i ] = coefficients_( i );
    }
}
References Process::abort(), Cerr, coefficients_, finl, Matrice_Base::is_stencil_up_to_date_, ordre(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTVect< _TYPE_ >::size(), and Matrice_Base::stencil_.
Referenced by get_symmetric_stencil_and_coefficients().
get_symmetric_stencil()
void Matrice_Diagonale::get_symmetric_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Definition at line 130 of file Matrice_Diagonale.cpp.
{
  get_stencil( stencil );
}
References get_stencil().
get_symmetric_stencil_and_coefficients()
void Matrice_Diagonale::get_symmetric_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Definition at line 164 of file Matrice_Diagonale.cpp.
{
  get_stencil_and_coefficients( stencil,
                                coefficients );
}
References get_stencil_and_coefficients().
info()
const Type_info * Matrice_Diagonale::info () static
Definition at line 19 of file Matrice_Diagonale.cpp.
nb_colonnes()
int Matrice_Diagonale::nb_colonnes (void) const override virtual
Implements Matrice_Base.
Definition at line 43 of file Matrice_Diagonale.cpp.
{
  return coefficients_.size( );
}
References coefficients_, and TRUSTVect< _TYPE_ >::size().
nb_lignes()
int Matrice_Diagonale::nb_lignes (void) const override virtual
Implements Matrice_Base.
Definition at line 38 of file Matrice_Diagonale.cpp.
{
  return coefficients_.size( );
}
References coefficients_, and TRUSTVect< _TYPE_ >::size().
ordre()
int Matrice_Diagonale::ordre (void) const override virtual
Implements Matrice_Base.
Definition at line 33 of file Matrice_Diagonale.cpp.
{
  return coefficients_.size();
}
References coefficients_, and TRUSTVect< _TYPE_ >::size().
Referenced by get_stencil(), and get_stencil_and_coefficients().
printOn()
Sortie & Matrice_Diagonale::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Base.
Definition at line 21 of file Matrice_Diagonale.cpp.
{
  os << coefficients_ << finl;
  return os;
}
References coefficients_, and finl.
readOn()
Entree & Matrice_Diagonale::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Matrice_Base.
Definition at line 27 of file Matrice_Diagonale.cpp.
{
  is >> coefficients_;
  return is;
}
References coefficients_.
scale()
void Matrice_Diagonale::scale (const double x) override virtual
Implements Matrice_Base.
Definition at line 106 of file Matrice_Diagonale.cpp.
{
  coefficients_ *= x;
}
References coefficients_.
self_cast() [1/2]
const Matrice_Diagonale & Matrice_Diagonale::self_cast (const Objet_U & r) static
Definition at line 19 of file Matrice_Diagonale.cpp.
self_cast() [2/2]
Matrice_Diagonale & Matrice_Diagonale::self_cast (Objet_U & r) static
Definition at line 19 of file Matrice_Diagonale.cpp.
taille_memoire()
unsigned Matrice_Diagonale::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Matrice_Diagonale.cpp.
Member Data Documentation
coefficients_
DoubleVect Matrice_Diagonale::coefficients_ protected
Definition at line 62 of file Matrice_Diagonale.h.
Referenced by ajouter_multTab_(), ajouter_multvect_(), coeff(), dimensionner(), get_coefficients(), get_stencil_and_coefficients(), nb_colonnes(), nb_lignes(), ordre(), printOn(), readOn(), and scale().
info_obj
const Type_info Matrice_Diagonale::info_obj static
Definition at line 33 of file Matrice_Diagonale.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Diagonale.h
src/Kernel/Math/Matrices/Matrice_Diagonale.cpp