TRUST: Op_Div_CoviMAC Class Reference
Op_Div_CoviMAC Class Reference
class Op_Div_CoviMAC
Cette classe represente l'operateur de divergence
La discretisation est CoviMAC
On calcule la divergence d'un champ_P1NC (la vitesse)
#include <Op_Div_CoviMAC.h>
Public Member Functions
Op_Div_CoviMAC ()
~Op_Div_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void volumique (DoubleTab &) const
void dimensionner (Matrice_Morse &matrice) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &matrice) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Div_CoviMAC & self_cast (Objet_U &)
static const Op_Div_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
Protected Attributes
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zcl_CoviMAC
Detailed Description
class Op_Div_CoviMAC
Cette classe represente l'operateur de divergence
La discretisation est CoviMAC
On calcule la divergence d'un champ_P1NC (la vitesse)
Definition at line 52 of file Op_Div_CoviMAC.h.
Constructor & Destructor Documentation
Op_Div_CoviMAC::Op_Div_CoviMAC ()
Definition at line 38 of file Op_Div_CoviMAC.cpp.
Op_Div_CoviMAC::~Op_Div_CoviMAC ()
Definition at line 38 of file Op_Div_CoviMAC.cpp.
Member Function Documentation
DoubleTab & Op_Div_CoviMAC::ajouter (const DoubleTab & vit, DoubleTab & div) const [virtual]
Reimplemented from Operateur_base.
Definition at line 85 of file Op_Div_CoviMAC.cpp.
References DoubleVect::echange_espace_virtuel(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_base::flux_bords_, la_zone_CoviMAC, DoubleVect::line_size(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, and Ref_Zone_CoviMAC::valeur().
Referenced by calculer().
{
  const Zone_CoviMAC& zone = la_zone_CoviMAC.valeur();
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face();
  const IntTab& f_e = zone.face_voisins();
  int i, e, f, n, N = vit.line_size();
  assert(div.line_size() == N);
  DoubleTab& tab_flux_bords = ref_cast(DoubleTab,flux_bords_);
  tab_flux_bords.resize(zone.nb_faces_bord(),1);
  tab_flux_bords=0;
  for (f = 0; f < zone.nb_faces(); f++)
    {
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) for (n = 0; n < N; n++)
          div(e, n) += (i ? -1 : 1) * fs(f) * pf(f) * vit(f, n);
      if (f < zone.premiere_face_int()) for (n = 0; n < N; n++) tab_flux_bords(f, n) = fs(f) * pf(f) * vit(f, n);
    }
  div.echange_espace_virtuel();
  return div;
}
void Op_Div_CoviMAC::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc &) [virtual]
Implements Operateur_base.
Definition at line 60 of file Op_Div_CoviMAC.cpp.
References la_zcl_CoviMAC, la_zone_CoviMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_CoviMAC& zCoviMAC = ref_cast(Zone_CoviMAC, zone_dis.valeur());
  const Zone_Cl_CoviMAC& zclCoviMAC = ref_cast(Zone_Cl_CoviMAC, zone_Cl_dis.valeur());
  la_zone_CoviMAC = zCoviMAC;
  la_zcl_CoviMAC = zclCoviMAC;
}
DoubleTab & Op_Div_CoviMAC::calculer (const DoubleTab & vit, DoubleTab & div) const [virtual]
Reimplemented from Operateur_base.
Definition at line 120 of file Op_Div_CoviMAC.cpp.
References ajouter().
{
  div = 0;
  return ajouter(vit,div);
}
void Op_Div_CoviMAC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 108 of file Op_Div_CoviMAC.cpp.
References MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), la_zone_CoviMAC, DoubleVect::line_size(), Zone_VF::nb_faces(), Zone_VF::porosite_face(), ref_cast, valeur(), Ref_Zone_CoviMAC::valeur(), and Champ_Inc_base::valeurs().
{
  const Zone_CoviMAC& zone = la_zone_CoviMAC.valeur();
  const Champ_Face_CoviMAC& ch = ref_cast(Champ_Face_CoviMAC, equation().inconnue().valeur());
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face();
  const IntTab& f_e = zone.face_voisins();
  int i, e, f, n, N = ch.valeurs().line_size();
  for (f = 0; f < zone.nb_faces(); f++) for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
      for (n = 0; n < N; n++) mat(N * e + n, N * f + n) += (i ? 1 : -1) * fs(f) * pf(f);
}
Objet_U * Op_Div_CoviMAC::cree_instance () [static]
Definition at line 38 of file Op_Div_CoviMAC.cpp.
void Op_Div_CoviMAC::dimensionner (Matrice_Morse & mat) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 70 of file Op_Div_CoviMAC.cpp.
References Matrix_tools::allocate_morse_matrix(), IntTab::append_line(), Objet_U::dimension, MorEqn::equation(), Zone_VF::face_voisins(), Equation_base::inconnue(), la_zone_CoviMAC, DoubleVect::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ArrOfInt::set_smart_resize(), tableau_trier_retirer_doublons(), Ref_Zone_CoviMAC::valeur(), and Champ_Inc::valeurs().
{
  const Zone_CoviMAC& zone = la_zone_CoviMAC.valeur();
  const IntTab& f_e = zone.face_voisins();
  int i, e, f, n, ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot(), N = equation().inconnue().valeurs().line_size(), D = dimension;
  IntTab stencil(0,2);
  stencil.set_smart_resize(1);
  for (f = 0; f < zone.nb_faces(); f++) for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
      for (n = 0; n < N; n++) stencil.append_line(N * e + n, N * f + n);
  tableau_trier_retirer_doublons(stencil);
  Matrix_tools::allocate_morse_matrix(N * ne_tot, N * (nf_tot + D * ne_tot), stencil, matrice);
}
int Op_Div_CoviMAC::duplique () const [virtual]
Implements Operateur_Div_base.
Definition at line 38 of file Op_Div_CoviMAC.cpp.
const Type_info * Op_Div_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 38 of file Op_Div_CoviMAC.cpp.
int Op_Div_CoviMAC::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 127 of file Op_Div_CoviMAC.cpp.
References Sortie::add_col(), Objet_U::dimension, DoubleTab::dimension(), MorEqn::equation(), finl, Operateur_base::flux_bords_, Cond_lim::frontiere_dis(), Process::je_suis_maitre(), la_zcl_CoviMAC, la_zone_CoviMAC, Frontiere_dis_base::le_nom(), Process::mp_sum(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), ref_cast, Probleme_base::schema_temps(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
{
  const int impr_bord=(la_zone_CoviMAC->zone().Bords_a_imprimer().est_vide() ? 0:1);
  SFichier Flux_div;
  ouvrir_fichier(Flux_div,"",je_suis_maitre());
  EcrFicPartage Flux_face;
  ouvrir_fichier_partage(Flux_face,"",impr_bord);
  const Schema_Temps_base& sch = equation().probleme().schema_temps();
  double temps = sch.temps_courant();
  if (je_suis_maitre()) Flux_div.add_col(temps);
  int nb_compo=flux_bords_.dimension(1);
// On parcours les frontieres pour sommer les flux par frontiere dans le tableau flux_bord
  DoubleVect flux_bord(nb_compo);
  DoubleVect bilan(nb_compo);
  bilan = 0;
  for (int num_cl=0; num_cl<la_zone_CoviMAC->nb_front_Cl(); num_cl++)
    {
      flux_bord=0;
      const Cond_lim& la_cl = la_zcl_CoviMAC->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      for (int face=ndeb; face<nfin; face++)
        for(int k=0; k<nb_compo; k++)
          flux_bord(k)+=flux_bords_(face, k);
      for(int k=0; k<nb_compo; k++)
        flux_bord(k)=Process::mp_sum(flux_bord(k));
      if(je_suis_maitre())
        {
          for(int k=0; k<nb_compo; k++)
            {
// Ajout pour impression sur fichiers separes
              Flux_div.add_col(flux_bord(k));
              bilan(k)+=flux_bord(k);
            }
        }
    }
  if(je_suis_maitre())
    {
      for(int k=0; k<nb_compo; k++)
        {
          Flux_div.add_col(bilan(k));
        }
      Flux_div << finl;
    }
  for (int num_cl=0; num_cl<la_zone_CoviMAC->nb_front_Cl(); num_cl++)
    {
      const Frontiere_dis_base& la_fr = la_zcl_CoviMAC->les_conditions_limites(num_cl).frontiere_dis();
      const Cond_lim& la_cl = la_zcl_CoviMAC->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      if (la_zone_CoviMAC->zone().Bords_a_imprimer().contient(la_fr.le_nom()))
        {
          Flux_face << "# Flux par face sur " << la_fr.le_nom() << " au temps " << temps << " : " << finl;
          for (int face=ndeb; face<nfin; face++)
            {
              if (dimension==2)
                Flux_face << "# Face a x= " << la_zone_CoviMAC->xv(face,0) << " y= " << la_zone_CoviMAC->xv(face,1) << " flux=" ;
              else if (dimension==3)
                Flux_face << "# Face a x= " << la_zone_CoviMAC->xv(face,0) << " y= " << la_zone_CoviMAC->xv(face,1) << " z= " << la_zone_CoviMAC->xv(face,2) << " flux=" ;
              for(int k=0; k<nb_compo; k++)
                Flux_face << " " << flux_bords_(face, k);
              Flux_face << finl;
            }
          Flux_face.syncfile();
        }
    }
  return 1;
}
const Type_info * Op_Div_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 38 of file Op_Div_CoviMAC.cpp.
Sortie & Op_Div_CoviMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 44 of file Op_Div_CoviMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Div_CoviMAC::readOn (Entree & is) [protected, virtual]
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Div_base.
Definition at line 52 of file Op_Div_CoviMAC.cpp.
{
  return s ;
}
const Op_Div_CoviMAC & Op_Div_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Div_base.
Definition at line 38 of file Op_Div_CoviMAC.cpp.
Op_Div_CoviMAC & Op_Div_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Div_base.
Definition at line 38 of file Op_Div_CoviMAC.cpp.
unsigned Op_Div_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 38 of file Op_Div_CoviMAC.cpp.
void Op_Div_CoviMAC::volumique (DoubleTab & div) const [virtual]
Implements Operateur_Div_base.
Definition at line 205 of file Op_Div_CoviMAC.cpp.
References la_zone_CoviMAC, Zone::nb_elem_tot(), Ref_Zone_CoviMAC::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
{
  const Zone_CoviMAC& zone_CoviMAC = la_zone_CoviMAC.valeur();
  const DoubleVect& vol = zone_CoviMAC.volumes();
  int nb_elem=zone_CoviMAC.zone().nb_elem_tot();
  int num_elem;
  for(num_elem=0; num_elem<nb_elem; num_elem++)
    div(num_elem)/=vol(num_elem);
}
Member Data Documentation
const Type_info Op_Div_CoviMAC::info_obj [static]
Reimplemented from Operateur_Div_base.
Definition at line 55 of file Op_Div_CoviMAC.h.
Ref_Zone_Cl_CoviMAC Op_Div_CoviMAC::la_zcl_CoviMAC [protected]
Definition at line 71 of file Op_Div_CoviMAC.h.
Referenced by associer(), and impr().
Ref_Zone_CoviMAC Op_Div_CoviMAC::la_zone_CoviMAC [protected]
Definition at line 70 of file Op_Div_CoviMAC.h.
Referenced by ajouter(), associer(), contribuer_a_avec(), dimensionner(), impr(), and volumique().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Div_CoviMAC.h
src/CoviMAC/Operateurs/Op_Div_CoviMAC.cpp