TRUST: Zone_EF_axi Class Reference
Zone_EF_axi Class Reference
: class Zone_EF_axi
<Description of class Zone_EF_axi>
#include <Zone_EF_axi.h>
Public Member Functions
Zone_EF_axi ()
~Zone_EF_axi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_IPhi () override
void calculer_Bij_gen (DoubleTab &bij_) override
void remplir_tableau_origine ()
void discretiser () override
const DomaineAxi1d & domaine_axi () const
DomaineAxi1d & domaine_axi ()
void verifie_compatibilite_domaine () override
Public Member Functions inherited from Zone_EF
Zone_EF ()
~Zone_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void typer_elem (Zone &zone_geom) override
void discretiser () override
void swap (int, int, int)
void reordonner (Faces &) override
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &) override
const Elem_EF & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const override
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_volumes_entrelaces ()
void calculer_volumes_sommets ()
virtual void calculer_IPhi ()
virtual void calculer_Bij (DoubleTab &bij_)
virtual void calculer_Bij_gen (DoubleTab &bij)
const DoubleVect & volumes_thilde () const
const DoubleVect & volumes_sommets_thilde () const
const DoubleVect & porosite_sommet () const
DoubleVect & set_porosite_sommet ()
void calculer_h_carre ()
void calculer_porosites_sommets ()
const DoubleTab & Bij () const
const DoubleTab & Bij_thilde () const
const DoubleTab & IPhi () const
const DoubleTab & IPhi_thilde () const
virtual void verifie_compatibilite_domaine ()
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_EF_axi & self_cast (Objet_U &)
static const Zone_EF_axi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_EF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_EF & self_cast (Objet_U &)
static const Zone_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_EF
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Zone_VF
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleTab origine_repere_
Protected Attributes inherited from Zone_EF
DoubleTab IPhi_
DoubleTab IPhi_thilde_
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
: class Zone_EF_axi
<Description of class Zone_EF_axi>
Definition at line 30 of file Zone_EF_axi.h.
Constructor & Destructor Documentation
Zone_EF_axi()
Zone_EF_axi::Zone_EF_axi ()
Definition at line 19 of file Zone_EF_axi.cpp.
~Zone_EF_axi()
Zone_EF_axi::~Zone_EF_axi ()
Definition at line 19 of file Zone_EF_axi.cpp.
Member Function Documentation
calculer_Bij_gen()
void Zone_EF_axi::calculer_Bij_gen (DoubleTab & bij_) override virtual
Reimplemented from Zone_EF.
Definition at line 33 of file Zone_EF_axi.cpp.
{
  const IntTab& les_elems=zone().les_elems() ;
  int nbsom_face=nb_som_face();
  int nbelem=nb_elem_tot();
  int nbsom_elem=zone().nb_som_elem();
  const IntTab& elemfaces=elem_faces_;
  int nbface_elem=zone().nb_faces_elem();
  const DoubleTab& les_coords = domaine_axi().coord_sommets();
  const DoubleVect& surf = face_surfaces();
  for (int elem=0; elem<nbelem; elem++)
    {
      double x0 = origine_repere_(elem,0);
      double y0 = origine_repere_(elem,1);
      for (int i=0; i<nbsom_elem; i++)
        {
// on cherche les faces contribuantes ,ce n'est pas optimal
          for (int f=0; f<nbface_elem; f++)
            {
              int face=elemfaces(elem,f);
              for (int s=0; s<nbsom_face; s++)
                {
// on cherche les faces contribuantes ,ce n'est pas optimal
                  if (face_sommets_(face,s)==les_elems(elem,i))
                    {
                      double x1 = les_coords(les_elems(elem,0),0);
                      double x2 = les_coords(les_elems(elem,1),0);
                      double y1 = les_coords(les_elems(elem,0),1);
                      double y2 = les_coords(les_elems(elem,1),1);
                      double r1 = sqrt((x1-x0)*(x1-x0)+(y1-y0)*(y1-y0));
                      double r2 = sqrt((x2-x0)*(x2-x0)+(y2-y0)*(y2-y0));
                      for (int j=0; j<dimension; j++)
{
                          if (surf(face)>0)
                            bij(elem,i,j)+=face_normales(face,j)*oriente_normale(face,elem)*(r1+r2)*M_PI/surf(face);
                          else
                            bij(elem,i,j)+=face_normales(face,j)*oriente_normale(face,elem)*(r1+r2)*M_PI;
                        }
                    }
                }
            }
        }
    }
}
References Domaine::coord_sommets(), Objet_U::dimension, domaine_axi(), Zone_VF::elem_faces_, Zone_EF::face_normales(), Zone_VF::face_sommets_, Zone_VF::face_surfaces(), Zone::les_elems(), M_PI, Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), Zone_EF::oriente_normale(), origine_repere_, and Zone_dis_base::zone().
calculer_IPhi()
void Zone_EF_axi::calculer_IPhi () override virtual
Reimplemented from Zone_EF.
Definition at line 84 of file Zone_EF_axi.cpp.
{
  int nbelem=zone().nb_elem();
  int nb_som_elem=zone().nb_som_elem();
  assert(nb_som_elem==2);
  IPhi_.resize(nbelem,nb_som_elem);
  domaine_axi().creer_tableau_elements(IPhi_);
// Scatter::creer_tableau_distribue(zone().domaine(), Joint::ELEMENT, IPhi_);
  IPhi_thilde_=IPhi_;
  const IntTab& les_elems=zone().les_elems() ;
  const DoubleTab& les_coords = domaine_axi().coord_sommets();
  for (int elem=0; elem<nbelem; elem++)
    {
      double x1 = les_coords(les_elems(elem,0),0);
      double x2 = les_coords(les_elems(elem,1),0);
      double y1 = les_coords(les_elems(elem,0),1);
      double y2 = les_coords(les_elems(elem,1),1);
      double x0 = origine_repere_(elem,0);
      double y0 = origine_repere_(elem,1);
      double r1 = sqrt((x1-x0)*(x1-x0)+(y1-y0)*(y1-y0));
      double r2 = sqrt((x2-x0)*(x2-x0)+(y2-y0)*(y2-y0));
      IPhi_(elem,0) = (M_PI/3.)*(r2*r2+r1*r2-2.*r1*r1);
      IPhi_(elem,1) = (M_PI/3.)*(2.*r2*r2-r1*r2-r1*r1);
      for (int s=0; s<nb_som_elem; s++)
        IPhi_thilde_(elem,s)=IPhi_(elem,s)*porosite_elem_(elem);
    }
  IPhi_.echange_espace_virtuel();
  IPhi_thilde_.echange_espace_virtuel();
}
References Domaine::coord_sommets(), Domaine::creer_tableau_elements(), domaine_axi(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_EF::IPhi_, Zone_EF::IPhi_thilde_, Zone::les_elems(), M_PI, Zone::nb_elem(), Zone::nb_som_elem(), origine_repere_, Zone_VF::porosite_elem_, TRUSTTab< _TYPE_ >::resize(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Zone_EF_axi::cree_instance () static
Definition at line 19 of file Zone_EF_axi.cpp.
discretiser()
void Zone_EF_axi::discretiser () override virtual
Reimplemented from Zone_EF.
Definition at line 160 of file Zone_EF_axi.cpp.
{
  verifie_compatibilite_domaine();
  typer_elem(zone());
  remplir_tableau_origine();
  Zone_EF::discretiser();
}
References Zone_EF::discretiser(), remplir_tableau_origine(), Zone_EF::typer_elem(), verifie_compatibilite_domaine(), and Zone_dis_base::zone().
domaine_axi() [1/2]
DomaineAxi1d & Zone_EF_axi::domaine_axi ()
Definition at line 174 of file Zone_EF_axi.cpp.
{
  return ref_cast(DomaineAxi1d,zone().domaine());
}
References ref_cast, and Zone_dis_base::zone().
domaine_axi() [2/2]
const DomaineAxi1d & Zone_EF_axi::domaine_axi () const
Definition at line 169 of file Zone_EF_axi.cpp.
{
  return ref_cast(DomaineAxi1d,zone().domaine());
}
References ref_cast, and Zone_dis_base::zone().
Referenced by calculer_Bij_gen(), calculer_IPhi(), and remplir_tableau_origine().
duplique()
int Zone_EF_axi::duplique () const override virtual
Reimplemented from Zone_EF.
Definition at line 19 of file Zone_EF_axi.cpp.
get_info()
const Type_info * Zone_EF_axi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_EF.
Definition at line 19 of file Zone_EF_axi.cpp.
info()
const Type_info * Zone_EF_axi::info () static
Definition at line 19 of file Zone_EF_axi.cpp.
printOn()
Sortie & Zone_EF_axi::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Zone_EF.
Definition at line 21 of file Zone_EF_axi.cpp.
{
  Zone_EF::printOn( os );
  return os;
}
References Zone_EF::printOn().
readOn()
Entree & Zone_EF_axi::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Zone_EF.
Definition at line 27 of file Zone_EF_axi.cpp.
{
  Zone_EF::readOn( is );
  return is;
}
References Zone_EF::readOn().
remplir_tableau_origine()
void Zone_EF_axi::remplir_tableau_origine ()
Definition at line 122 of file Zone_EF_axi.cpp.
{
  DomaineAxi1d& domax = domaine_axi();
  const Champ& orig = domax.champ_origine();
  origine_repere_.resize(0,Objet_U::dimension-1);
  domax.creer_tableau_elements(origine_repere_);
  if (orig.non_nul())
    {
      const DoubleTab& positions = xp();
      IntVect les_polys(nb_elem());
      for(int e = 0; e < nb_elem(); e++)
        les_polys(e) = e;
      orig->valeur_aux_elems(positions, les_polys, origine_repere_);
    }
  else
    origine_repere_=0.;
  domax.associer_origine_repere(origine_repere_);
}
References DomaineAxi1d::associer_origine_repere(), DomaineAxi1d::champ_origine(), Domaine::creer_tableau_elements(), Objet_U::dimension, domaine_axi(), Zone_dis_base::nb_elem(), O_U_Ptr::non_nul(), origine_repere_, TRUSTTab< _TYPE_ >::resize(), Champ::valeur_aux_elems(), and Zone_VF::xp().
Referenced by discretiser().
self_cast() [1/2]
const Zone_EF_axi & Zone_EF_axi::self_cast (const Objet_U & r) static
Definition at line 19 of file Zone_EF_axi.cpp.
self_cast() [2/2]
Zone_EF_axi & Zone_EF_axi::self_cast (Objet_U & r) static
Definition at line 19 of file Zone_EF_axi.cpp.
taille_memoire()
unsigned Zone_EF_axi::taille_memoire () const override virtual
Reimplemented from Zone_EF.
Definition at line 19 of file Zone_EF_axi.cpp.
verifie_compatibilite_domaine()
void Zone_EF_axi::verifie_compatibilite_domaine () override virtual
Reimplemented from Zone_EF.
Definition at line 146 of file Zone_EF_axi.cpp.
{
  if (!zone().domaine().Axi1d())
    {
      Cerr << "*****************************************************************************" << finl;
      Cerr << " Error in " << que_suis_je() << " : the type of domain " << zone().domaine().que_suis_je();
      Cerr << " is not compatible" << finl;
      Cerr << " with the discretisation EF_axi. " << finl;
      Cerr << " Please use the discretization EF or define a domain of type DomaineAxi1d." << finl;
      Cerr << "*****************************************************************************" << finl;
      Process::exit();
    }
}
References Cerr, Zone::domaine(), Process::exit(), finl, Objet_U::que_suis_je(), and Zone_dis_base::zone().
Referenced by discretiser().
Member Data Documentation
info_obj
const Type_info Zone_EF_axi::info_obj static
Definition at line 33 of file Zone_EF_axi.h.
origine_repere_
DoubleTab Zone_EF_axi::origine_repere_ protected
Definition at line 49 of file Zone_EF_axi.h.
Referenced by calculer_Bij_gen(), calculer_IPhi(), and remplir_tableau_origine().
The documentation for this class was generated from the following files:
src/EF/Zones/Zone_EF_axi.h
src/EF/Zones/Zone_EF_axi.cpp