TRUST: Schema_Temps_base Class Reference
Schema_Temps_base Class Reference abstract
classe Schema_Temps_base
#include <Schema_Temps_base.h>
Public Member Functions
~Schema_Temps_base () override
< necessaire pour visual
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
virtual void terminate ()
virtual double computeTimeStep (bool &stop) const
virtual bool initTimeStep (double dt)
virtual void validateTimeStep ()
virtual bool isStationary () const
Retourne 1 si lors du dernier pas de temps, le probleme n'a pas evolue.
virtual void abortTimeStep ()
virtual bool iterateTimeStep (bool &converged)
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int limpr () const
Renvoie 1 s'il y a lieu d'effectuer une impression (cf dt_impr)
Renvoie 0 sinon.
virtual int nb_valeurs_temporelles () const =0
virtual int nb_valeurs_futures () const =0
virtual double temps_futur (int i) const =0
virtual double temps_defaut () const =0
Schema_Temps_base ()
Constructeur par defaut d'un schema en temps.
Initialise differents membres de la classe.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au shema en temps
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du shema en temps
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)=0
virtual void set_param (Param &titi)
int sauvegarder (Sortie &) const override
Sauvegarde le temps courant et le nombre de pas de temps
sur un flot de sortie.
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
virtual int mettre_a_jour ()
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
virtual void mettre_a_jour_dt (double toto)
virtual void mettre_a_jour_dt_stab ()
double pas_de_temps () const
Renvoie le pas de temps (delta_t) courant.
const DoubleTab & pas_de_temps_locaux () const
virtual bool corriger_dt_calcule (double &dt) const
Corrige le pas de temps calcule que l'on passe en parametre
et verifie qu'il n'est pas "trop" petit (< dt-min_).
La correction est la suivante:
delta_t = min((facteur de securite * dt_calc), dt_max)
Et on verifie que delta_t est "suffisamment" plus grand que dt_min_.
virtual void imprimer (Sortie &os) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
virtual int impr (Sortie &os) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
void imprimer (Sortie &os, Probleme_base &pb) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
void imprimer (Sortie &os, const Probleme_base &pb) const
virtual int impr (Sortie &os, Probleme_base &pb) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
virtual int impr (Sortie &os, const Probleme_base &pb) const
void imprimer_temps_courant (SFichier &) const
double pas_temps_min () const
Renvoie le pas de temps minimum.
(version const)
double & pas_temps_min ()
Renvoie une reference sur le pas de temps minimum.
double pas_temps_max () const
Renvoie le pas de temps maximum.
(version const)
double & pas_temps_max ()
Renvoie une reference sur le pas de temps maximum.
int nb_impr () const
Renvoie le nombre d'impressions effectuees.
double temps_courant () const
Renvoie le temps courant.
double temps_precedent () const
Renvoie le temps courant.
double temps_calcul () const
Renvoie le temps de calcul ecoule i.e. (temps courant - temps initial).
virtual void changer_temps_courant (const double)
Change le temps courant.
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
//Actualisation de stationnaire_atteint_ et residu_
(critere residu_<seuil_statio_)
double facteur_securite_pas () const
Renvoie le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
(version const)
double & facteur_securite_pas ()
Renvoie une reference sur le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
virtual int stop () const
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier (voir int Schema_Temps_base::stop_lu())
Renvoie 0 sinon.
int lsauv () const
int temps_final_atteint () const
Renvoie 1 si le temps final est atteint (ou depasse).
Renvoie 1 si temps_courant_ >= tmax
Renvoie 0 sinon.
int nb_pas_dt_max_atteint () const
Renvoie 1 si (le nombre de pas de temps >= nombre de pas de temps maximum).
Renvoie 0 sinon.
int temps_cpu_max_atteint () const
int stationnaire_atteint () const
int stop_lu () const
Renvoie 1 si le fichier (d'extension) .stop contient un 1
Renvoie 0 sinon.
int diffusion_implicite () const
Renvoie 1 si le schema en temps a ete lu diffusion_implicite.
double seuil_diffusion_implicite () const
int impr_diffusion_implicite () const
Seuil pour implicitation de la diffusion par GC.
int impr_extremums () const
Impression ou non de GC implicitation.
int niter_max_diffusion_implicite () const
int no_conv_subiteration_diffusion_implicite () const
Iterations maximale pour GC implicitation.
int no_error_if_not_converged_diffusion_implicite () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_nb_pas_dt_max (Entree &)
virtual Entree & lire_periode_sauvegarde_securite_en_heures (Entree &)
virtual Entree & lire_temps_cpu_max (Entree &)
virtual void completer ()=0
double temps_init () const
Renvoie le temps initial.
double temps_max () const
Renvoie une reference sur le temps maximum.
double temps_sauv () const
Renvoie une reference sur le temps de sauvegarde.
double temps_impr () const
Renvoie une reference sur le temps d'impression.
int precision_impr () const
int wcol () const
int gnuplot_header () const
double seuil_statio () const
Renvoie une reference sur le seuil stationnaire.
int nb_pas_dt_max () const
Renvoie une reference sur le nombre de pas maxi.
int nb_pas_dt () const
Renvoie le nombre de pas de temps effectues.
double mode_dt_start () const
int indice_tps_final_atteint () const
int indice_nb_pas_dt_max_atteint () const
int lu () const
int file_allocation () const
double & set_temps_init ()
double & set_temps_max ()
double & set_temps_courant ()
double & set_temps_precedent ()
int & set_nb_pas_dt ()
int & set_nb_pas_dt_max ()
double & set_dt_min ()
double & set_dt_max ()
double & set_dt_sauv ()
double & set_dt_impr ()
int & set_precision_impr ()
double & set_dt ()
double & set_facsec ()
double & set_seuil_statio ()
int & set_stationnaire_atteint ()
void set_stationnaires_atteints (bool flag)
int & set_diffusion_implicite ()
double & set_seuil_diffusion_implicite ()
int & set_niter_max_diffusion_implicite ()
double & set_mode_dt_start ()
int & set_indice_tps_final_atteint ()
int & set_indice_nb_pas_dt_max_atteint ()
int & set_lu ()
const double & residu () const
double & residu ()
int & schema_impr ()
const int & schema_impr () const
virtual void associer_pb (const Probleme_base &)
Probleme_base & pb_base ()
const Probleme_base & pb_base () const
virtual void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem)
virtual void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const Equation_base &eqn, const tabs_t &semi_impl={}) const
int disable_progress () const
int disable_dt_ev () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Schema_Temps_base & self_cast (Objet_U &)
static const Schema_Temps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Probleme_base mon_probleme
Nom nom_
double dt_
Pas de temps de calcul.
DoubleTab dt_locaux_
Local time steps: Vector of size nb faces of the mesh.
double temps_courant_
double temps_precedent_
double dt_failed_
double dt_gf_
double tinit_
double tmax_
double tcpumax_
int nb_pas_dt_
int nb_pas_dt_max_
int nb_impr_
double dt_min_
Pas de temps min fixe par l'utilisateur.
double dt_max_
Pas de temps max fixe par l'utilisateur.
Nom dt_max_str_
Parser_U dt_max_fn_
double dt_stab_
Pas de temps de stabilite.
double facsec_
double seuil_statio_
int seuil_statio_relatif_deconseille_
Drapeau pour specifier si seuil_statio_ est une valeur absolue (defaut) ou relative.
double dt_sauv_
double limite_cpu_sans_sauvegarde_
double periode_cpu_sans_sauvegarde_
double temps_cpu_ecoule_
double dt_impr_
Pas de temps d'impression.
int precision_impr_
Nombre de chiffres significatifs impression.
double mode_dt_start_
mode calcul du pas de temps de depart
double residu_
Residu.
double residu_old_slope_
double cumul_slope_
int gnuplot_header_
int ind_tps_final_atteint
int ind_nb_pas_dt_max_atteint
int ind_temps_cpu_max_atteint
int lu_
int ind_diff_impl_
double seuil_diff_impl_
int impr_diff_impl_
int impr_extremums_
int niter_max_diff_impl_
int no_conv_subiteration_diff_impl_
int no_error_if_not_converged_diff_impl_
int schema_impr_
1 si le schema a le droit d'imprimer dans le .out et dt_ev
int file_allocation_
1 = allocation espace disque (par defaut), 0 sinon
int max_length_cl_
Private Attributes
int stationnaire_atteint_
Stationary reached by the problem using this scheme.
bool stationnaires_atteints_
Stationary reached by the calculation (means all the problems reach stationary)
SFichier progress_
int disable_progress_
Flag to disable the writing of the .progress file.
int disable_dt_ev_
Flag to disable the writing of the .dt_ev file.
Detailed Description
classe Schema_Temps_base
Definition at line 65 of file Schema_Temps_base.h.
Constructor & Destructor Documentation
~Schema_Temps_base()
Schema_Temps_base::~Schema_Temps_base () override
< necessaire pour visual
Definition at line 31 of file Schema_Temps_base.cpp.
Schema_Temps_base()
Schema_Temps_base::Schema_Temps_base ()
Constructeur par defaut d'un schema en temps.
Initialise differents membres de la classe.
< Par defaut 23 heures
< Nouveau 1.5.6 : desormais le premier pas de temps est calcule et ne vaut donc plus dt_min (par defaut, donc est equivalent a dt_start dt_calc)
< Above 100 iterations, diffusion implicit algorithm is may be diverging
< Desactive car pose probleme sur platine sur les gros maillages
Definition at line 555 of file Schema_Temps_base.cpp.
{
  lu_=0;
  dt_ = 0;
  tinit_ = -DMAXFLOAT;
  dt_min_ = 1.e-16;
  dt_sauv_ = dt_impr_ = tmax_ = dt_max_ = tcpumax_ = 1.e30;
  periode_cpu_sans_sauvegarde_ = 23 * 3600; //!< Par defaut 23 heures
  limite_cpu_sans_sauvegarde_ = periode_cpu_sans_sauvegarde_;
  temps_cpu_ecoule_ = 0;
  precision_impr_ = 8;
  stationnaire_atteint_=0;
  stationnaires_atteints_=0;
  residu_=0;
  mode_dt_start_=-2; //!< Nouveau 1.5.6 : desormais le premier pas de temps est calcule et ne vaut donc plus dt_min (par defaut, donc est equivalent a dt_start dt_calc)
  nb_pas_dt_ = 0;
  nb_impr_ = 0;
  nb_pas_dt_max_ = (int)(pow(2.0,(double)((sizeof(True_int)*8)-1))-1);
  seuil_statio_ = 1.e-12;
  seuil_statio_relatif_deconseille_ = 0;
  facsec_ = 1.;
  ind_tps_final_atteint=0;
  ind_nb_pas_dt_max_atteint=0;
  ind_temps_cpu_max_atteint=0;
  ind_diff_impl_=0 ;
  seuil_diff_impl_=1.e-6 ;
  impr_diff_impl_=0;
  impr_extremums_=0;
  no_conv_subiteration_diff_impl_=0;
  no_error_if_not_converged_diff_impl_=0;
  niter_max_diff_impl_ = 1000; //!< Above 100 iterations, diffusion implicit algorithm is may be diverging
  schema_impr_=1;
  file_allocation_=0; //!< Desactive car pose probleme sur platine sur les gros maillages
  residu_old_slope_=-1000;
  cumul_slope_=1e-20;
  disable_progress_ = 0;
  disable_dt_ev_ = 0;
  gnuplot_header_ = 0;
  dt_gf_ = DMAXFLOAT;
}
References cumul_slope_, disable_dt_ev_, disable_progress_, DMAXFLOAT, dt_, dt_gf_, dt_impr_, dt_max_, dt_min_, dt_sauv_, facsec_, file_allocation_, gnuplot_header_, impr_diff_impl_, impr_extremums_, ind_diff_impl_, ind_nb_pas_dt_max_atteint, ind_temps_cpu_max_atteint, ind_tps_final_atteint, limite_cpu_sans_sauvegarde_, lu_, mode_dt_start_, nb_impr_, nb_pas_dt_, nb_pas_dt_max_, niter_max_diff_impl_, no_conv_subiteration_diff_impl_, no_error_if_not_converged_diff_impl_, periode_cpu_sans_sauvegarde_, precision_impr_, residu_, residu_old_slope_, schema_impr_, seuil_diff_impl_, seuil_statio_, seuil_statio_relatif_deconseille_, stationnaire_atteint_, stationnaires_atteints_, tcpumax_, temps_cpu_ecoule_, tinit_, and tmax_.
Member Function Documentation
abortTimeStep()
void Schema_Temps_base::abortTimeStep () virtual
Definition at line 311 of file Schema_Temps_base.cpp.
{
  Probleme_base& prob=pb_base();
  for(int i=0; i<prob.nombre_d_equations(); i++)
    prob.equation(i).abortTimeStep();
  dt_ = prob.calculer_pas_de_temps();
}
References Equation_base::abortTimeStep(), Probleme_base::calculer_pas_de_temps(), dt_, Probleme_base::equation(), Probleme_base::nombre_d_equations(), and pb_base().
Referenced by Probleme_base::abortTimeStep().
ajouter_blocs()
void Schema_Temps_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const Equation_base & eqn, const tabs_t & semi_impl = {}) const virtual
Definition at line 1043 of file Schema_Temps_base.cpp.
{
  eqn.solv_masse().valeur().ajouter_blocs(matrices, secmem, pas_de_temps(), semi_impl, 1);
}
References Solveur_Masse_base::ajouter_blocs(), pas_de_temps(), Equation_base::solv_masse(), and Deriv_Solveur_Masse_base::valeur().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), and Equation_base::assembler_blocs_avec_inertie().
ajouter_inertie()
void Schema_Temps_base::ajouter_inertie (Matrice_Base & mat_morse, DoubleTab & secmem, const Equation_base & eqn) const virtual
Reimplemented in Schema_Implicite_Multi_TimeStep_base.
Definition at line 1032 of file Schema_Temps_base.cpp.
{
// codage pour euler_implicite
  double dt=pas_de_temps();
// On ne penalise pas les matrices et les secmems meme dans les cas
// dirichlet , symetrie
  int pen=0;
  eqn.solv_masse().ajouter_masse(dt,mat_morse,pen); //ordre important pour PolyMAC_P0
  eqn.solv_masse().ajouter_masse(dt,secmem,eqn.inconnue().passe(),pen);
}
References Solveur_Masse::ajouter_masse(), Equation_base::inconnue(), pas_de_temps(), Champ_Inc::passe(), and Equation_base::solv_masse().
Referenced by Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Equation_base::assembler_avec_inertie(), and Equation_base::Gradient_conjugue_diff_impl().
associer_pb()
void Schema_Temps_base::associer_pb (const Probleme_base & un_probleme) virtual
Reimplemented in Schema_Adams_Bashforth_base, and Schema_Adams_Moulton_base.
Definition at line 320 of file Schema_Temps_base.cpp.
{
// assert(!mon_probleme.non_nul());
  mon_probleme=un_probleme;
}
References mon_probleme.
Referenced by Schema_Adams_Bashforth_base::associer_pb(), Schema_Adams_Moulton_base::associer_pb(), and Probleme_base::associer_sch_tps_base().
changer_temps_courant()
void Schema_Temps_base::changer_temps_courant (const double t) inline virtual
Change le temps courant.
Reimplemented in Multi_Sch_ThHyd.
Definition at line 790 of file Schema_Temps_base.h.
{
  temps_courant_ = t;
}
References temps_courant_.
Referenced by Schema_Temps::changer_temps_courant(), Multi_Sch_ThHyd::changer_temps_courant(), and Pbc_MED::readOn().
completer()
virtual void Schema_Temps_base::completer () pure virtual
Implemented in TRUSTSchema_RK< _ORDRE_ >, TRUSTSchema_RK< Ordre_RK::DEUX_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::DEUX_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::TROIS_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::TROIS_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE_3_8 >, TRUSTSchema_RK< Ordre_RK::RATIO_DEUX >, TRUSTSchema_RK< Ordre_RK::UN >, Leap_frog, Pred_Cor, Schema_Explicite_Multi_TimeStep_base, Multi_Sch_ThHyd, Sch_CN_iteratif, Schema_Euler_Implicite, and Schema_Implicite_Multi_TimeStep_base.
Referenced by Equation_base::completer().
computeTimeStep()
double Schema_Temps_base::computeTimeStep (bool & stop) const virtual
< Change le contenu de dt
Definition at line 91 of file Schema_Temps_base.cpp.
{
// reevaluation de dt_max_ si fonction du temps
  if (dt_max_str_ != Nom())
    {
      dt_max_fn_.setVar(0, temps_courant());
      dt_max_ = dt_max_fn_.eval();
    }
  is_stop=false;
// Correction en premier du pas de temps
  double dt = dt_stab_;
  if (!corriger_dt_calcule(dt)) //!< Change le contenu de dt
    is_stop=true;
  dt = std::min(dt, dt_failed_ / sqrt(2)); //pour provoquer une baisse de dt en cas d'echec a la resolution precedente
  if (temps_courant_ > temps_precedent_)
    dt = std::min(dt, (temps_courant_ - temps_precedent_) * dt_gf_); //pour ne pas remonter dt trop vite (comme facsec)
// Mise a jour immediate de l'attribut dt_ afin que pas_de_temps()
// soit a jour tout le temps (en particulier au moment du postraitement)
// Ce n'etait pas le cas pour les versions <= 1.6.3 et les champs dependant
// de dt n'etaient pas juste si facsec<>1
// dt_ = dt;
  if (this->stop())
    {
      is_stop=true;
      return 0;
    }
  else
    return dt;
}
References corriger_dt_calcule(), dt_failed_, dt_gf_, dt_max_, dt_max_fn_, dt_max_str_, dt_stab_, Parser_U::eval(), Parser_U::setVar(), stop(), temps_courant(), temps_courant_, and temps_precedent_.
Referenced by Probleme_base::computeTimeStep().
corriger_dt_calcule()
bool Schema_Temps_base::corriger_dt_calcule (double & dt) const virtual
Corrige le pas de temps calcule que l'on passe en parametre
et verifie qu'il n'est pas "trop" petit (< dt-min_).
La correction est la suivante:
delta_t = min((facteur de securite * dt_calc), dt_max)
Et on verifie que delta_t est "suffisamment" plus grand que dt_min_.
Reimplemented in Multi_Sch_ThHyd.
Definition at line 927 of file Schema_Temps_base.cpp.
{
// Print the RAM
  if (limpr())
    {
      Cout << finl;
      imprimer_ram_totale();
    }
// Compute the time step dt as the minimal value between dt_max_ and stability time step (dt_stab) * security factor (facsec)
  double dt = std::min (dt_max_, dt_stab_ * facsec_);
  if ((dt - dt_min_)/(dt+DMINFLOAT) < -1.e-6)
    {
// Calculation stops if time step dt is less than dt_min
      Cerr << "---------------------------------------------------------" << finl;
      Cerr << "Problem with the time step " << dt << " which is less than dt_min " << dt_min_ << finl;
      Cerr << "Lower dt_min value or check why the time step decreases..." << finl;
      Cerr << "Results are saved to provide help." << finl;
      Cerr << "---------------------------------------------------------" << finl;
      Probleme_base& pb = ref_cast_non_const(Probleme_base, mon_probleme.valeur());
      pb.postraiter(1);
      pb.sauver();
      Process::exit();
    }
  dt_calc=dt;
  return 1;
}
References Cerr, Cout, DMINFLOAT, dt_max_, dt_min_, dt_stab_, Process::exit(), facsec_, finl, Process::imprimer_ram_totale(), limpr(), mon_probleme, Probleme_base::postraiter(), ref_cast_non_const, Probleme_base::sauver(), and Ref_Probleme_base::valeur().
Referenced by computeTimeStep(), Schema_Temps::corriger_dt_calcule(), and Multi_Sch_ThHyd::corriger_dt_calcule().
diffusion_implicite()
int Schema_Temps_base::diffusion_implicite () const inline
Renvoie 1 si le schema en temps a ete lu diffusion_implicite.
Returns
int
Signification: 1 si le schema en temps a ete lu 0 sinon.
Contraintes:
Definition at line 900 of file Schema_Temps_base.h.
{
  return ind_diff_impl_;
}
References ind_diff_impl_.
Referenced by Equation_base::calculer_pas_de_temps(), Multi_Sch_ThHyd::completer(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Navier_Stokes_std::initTimeStep(), iterer_eqn_expl_diffusion_implicite(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Schema_Euler_Implicite::readOn(), and Schema_Implicite_Multi_TimeStep_base::readOn().
disable_dt_ev()
int Schema_Temps_base::disable_dt_ev () const inline
Definition at line 352 of file Schema_Temps_base.h.
  {
    return disable_dt_ev_ ;
  };
References disable_dt_ev_.
Referenced by initialize(), and validateTimeStep().
disable_progress()
int Schema_Temps_base::disable_progress () const inline
Definition at line 347 of file Schema_Temps_base.h.
  {
    return disable_progress_ ;
  };
References disable_progress_.
Referenced by initialize(), terminate(), and validateTimeStep().
facteur_securite_pas() [1/2]
double & Schema_Temps_base::facteur_securite_pas () inline
Renvoie une reference sur le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
Returns
double&
Signification: le facteur de securite du schema en temps
Contraintes:
Definition at line 833 of file Schema_Temps_base.h.
{
  return facsec_;
}
References facsec_.
facteur_securite_pas() [2/2]
double Schema_Temps_base::facteur_securite_pas () const inline
Renvoie le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
(version const)
Returns
double
Signification: le facteur de securite du schema en temps
Contraintes:
Definition at line 812 of file Schema_Temps_base.h.
{
  return facsec_;
}
References facsec_.
Referenced by Multi_Sch_ThHyd::completer(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Schema_Temps::facteur_securite_pas(), Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base(), and Probleme_Couple::solveTimeStep().
faire_un_pas_de_temps_eqn_base()
virtual int Schema_Temps_base::faire_un_pas_de_temps_eqn_base (Equation_base &) pure virtual
Implemented in Leap_frog, Pred_Cor, Schema_Euler_explicite, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_Multi_TimeStep_base, RRK2, Multi_Sch_ThHyd, Sch_CN_iteratif, TRUSTSchema_RK< _ORDRE_ >, TRUSTSchema_RK< Ordre_RK::DEUX_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::DEUX_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::TROIS_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::TROIS_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE_3_8 >, TRUSTSchema_RK< Ordre_RK::RATIO_DEUX >, and TRUSTSchema_RK< Ordre_RK::UN >.
Referenced by Schema_Temps::faire_un_pas_de_temps_eqn_base(), iterateTimeStep(), and Pb_Dilatable_base::iterateTimeStep().
file_allocation()
int Schema_Temps_base::file_allocation () const inline
Definition at line 217 of file Schema_Temps_base.h.
  {
    return file_allocation_;
  } ;
References file_allocation_.
Referenced by Probleme_base::preparer_calcul().
get_info()
const Type_info * Schema_Temps_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Leap_frog, Pred_Cor, Schema_Adams_Bashforth_base, Schema_Adams_Bashforth_order_2, Schema_Adams_Bashforth_order_3, Schema_Adams_Moulton_base, Schema_Adams_Moulton_order_2, Schema_Adams_Moulton_order_3, Schema_Euler_explicite, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_base, Schema_Implicite_Multi_TimeStep_base, RK2_Classique, RK3_Classique, RK4_Classique, RK4_Classique_3_8, RRK2, RK2, RK3, RK4, Multi_Sch_ThHyd, Sch_CN_EX_iteratif, Sch_CN_iteratif, Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 31 of file Schema_Temps_base.cpp.
gnuplot_header()
int Schema_Temps_base::gnuplot_header () const inline
Definition at line 194 of file Schema_Temps_base.h.
  {
    return gnuplot_header_;
  };
References gnuplot_header_.
Referenced by Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), and Source_base::ouvrir_fichier().
impr() [1/3]
int Schema_Temps_base::impr (Sortie & os) const virtual
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Definition at line 610 of file Schema_Temps_base.cpp.
{
  os << finl;
  os << "-------------------------------------------------------------------" << finl;
  os << "We finished treating the time step number "<< nb_pas_dt_ << " , for the time scheme ..." << finl
     << "   stable dt used = " << dt_ << finl /* dt_stab_ peut etre ? c'est pareil je pense */
     << "   time achieved (in seconds) = " << temps_courant_ << finl;
  return 0;
}
References dt_, finl, nb_pas_dt_, and temps_courant_.
Referenced by Schema_Temps::impr(), and imprimer().
impr() [2/3]
int Schema_Temps_base::impr (Sortie & os, const Probleme_base & pb) const virtual
Definition at line 645 of file Schema_Temps_base.cpp.
{
  os << finl;
  os << " Problem : " << pb.le_nom() << finl;
  os << "We treat the time step number "<< nb_pas_dt_ << finl;
  os << "   dt = " << dt_ << finl;
  os << "   time = " << temps_courant_ << finl;
  os << "   time scheme : " << pb.schema_temps() << finl;
  return 0;
}
References dt_, finl, Probleme_base::le_nom(), nb_pas_dt_, Probleme_base::schema_temps(), and temps_courant_.
impr() [3/3]
int Schema_Temps_base::impr (Sortie & os, Probleme_base & pb) const virtual
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Definition at line 635 of file Schema_Temps_base.cpp.
{
  os << finl;
  os << " Problem : " << pb.le_nom() << finl;
  os << "We treat the time step number "<< nb_pas_dt_ << finl;
  os << "   dt = " << dt_ << finl;
  os << "   time = " << temps_courant_ << finl;
  os << "   time scheme : " << pb.schema_temps() << finl;
  return 0;
}
References dt_, finl, Probleme_base::le_nom(), nb_pas_dt_, Probleme_base::schema_temps(), and temps_courant_.
impr_diffusion_implicite()
int Schema_Temps_base::impr_diffusion_implicite () const inline
Seuil pour implicitation de la diffusion par GC.
Definition at line 153 of file Schema_Temps_base.h.
  {
    return impr_diff_impl_;
  };        //!< Impression ou non de GC implicitation
References impr_diff_impl_.
Referenced by Equation_base::Gradient_conjugue_diff_impl().
impr_extremums()
int Schema_Temps_base::impr_extremums () const inline
Impression ou non de GC implicitation.
Definition at line 157 of file Schema_Temps_base.h.
  {
    return impr_extremums_;
  };
References impr_extremums_.
imprimer() [1/3]
void Schema_Temps_base::imprimer (Sortie & os) const virtual
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
Reimplemented in Multi_Sch_ThHyd.
Definition at line 783 of file Schema_Temps_base.cpp.
{
  if (limpr())
    {
      nb_impr_++;
      if (je_suis_maitre() && schema_impr())
        {
          impr(os);
        }
    }
}
References impr(), Process::je_suis_maitre(), limpr(), nb_impr_, and schema_impr().
Referenced by Multi_Sch_ThHyd::imprimer(), Schema_Temps::imprimer(), mettre_a_jour_dt_stab(), and Sch_CN_EX_iteratif::mettre_a_jour_dt_stab().
imprimer() [2/3]
void Schema_Temps_base::imprimer (Sortie & os, const Probleme_base & pb) const
Definition at line 814 of file Schema_Temps_base.cpp.
{
  if (limpr() && je_suis_maitre())
    impr(os,pb);
}
References impr(), Process::je_suis_maitre(), and limpr().
imprimer() [3/3]
void Schema_Temps_base::imprimer (Sortie & os, Probleme_base & pb) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
Definition at line 809 of file Schema_Temps_base.cpp.
{
  if (limpr() && je_suis_maitre())
    impr(os,pb);
}
References impr(), Process::je_suis_maitre(), and limpr().
imprimer_temps_courant()
void Schema_Temps_base::imprimer_temps_courant (SFichier & os) const
Definition at line 1125 of file Schema_Temps_base.cpp.
{
  int precision_actuelle=os.get_precision();
  int precision_temps;
  if (!est_egal(temps_courant(),0.))
    precision_temps=std::max( precision_actuelle, (int)(2+log10(1/std::fabs(pas_de_temps()))+(int)(log10(std::fabs(temps_courant())))) );
  else
    precision_temps=std::max( precision_actuelle, (int)(2+log10(1/std::fabs(pas_de_temps()))) );
  os.precision(precision_temps);
  os << temps_courant();
  os.precision(precision_actuelle);
}
References est_egal(), Sortie_Fichier_base::get_precision(), pas_de_temps(), Sortie_Fichier_base::precision(), and temps_courant().
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), T_It_VDF_Face< _TYPE_ >::impr(), and Op_Grad_VDF_Face::impr().
indice_nb_pas_dt_max_atteint()
int Schema_Temps_base::indice_nb_pas_dt_max_atteint () const inline
Definition at line 209 of file Schema_Temps_base.h.
  {
    return ind_nb_pas_dt_max_atteint;
  } ;
References ind_nb_pas_dt_max_atteint.
Referenced by Multi_Sch_ThHyd::completer().
indice_tps_final_atteint()
int Schema_Temps_base::indice_tps_final_atteint () const inline
Definition at line 205 of file Schema_Temps_base.h.
  {
    return ind_tps_final_atteint;
  } ;
References ind_tps_final_atteint.
Referenced by Multi_Sch_ThHyd::completer().
info()
const Type_info * Schema_Temps_base::info () static
Definition at line 31 of file Schema_Temps_base.cpp.
initialize()
void Schema_Temps_base::initialize () virtual
Definition at line 35 of file Schema_Temps_base.cpp.
{
// GF je remets le calculer_pas_de_temps car des schemas en temps implicites s'en servent pour dimensionner (en particulier ovap)
  pb_base().calculer_pas_de_temps();
// je le mets une deuxieme fois pour alternant....
  pb_base().calculer_pas_de_temps();
  if (je_suis_maitre())
    {
      if (!disable_dt_ev())
        {
          Nom fichier(nom_du_cas()+".dt_ev");
          struct stat f;
// On initialise le fichier .dt_ev s'il n'existe pas ou si c'est un demarrage de calcul sans reprise
          if ((nb_pas_dt_==0) && ((stat(fichier,&f)) || !(pb_base().reprise_effectuee()==1)))
            {
              if (schema_impr())
                {
                  dt_ev_.ouvrir(fichier, ios::out);
                  dt_ev_.setf(ios::scientific);
                  dt_ev_ << "# temps\t\t dt\t\t facsec\t\t residu=max|Ri|\t dt_stab\t ";
                }
              for (int i=0; i<pb_base().nombre_d_equations(); i++)
                dt_ev_ << pb_base().equation(i).expression_residu();
            }
          else
            {
              if (schema_impr())
                {
                  dt_ev_.ouvrir(fichier, ios::app);
                  dt_ev_.setf(ios::scientific);
                }
            }
        }
      if (!disable_progress() && !progress_.is_open())
        progress_.ouvrir(nom_du_cas()+".progress");
    }
  if ((nb_pas_dt_==0) && ( ((mode_dt_start_==0) && est_egal(tinit_,0.)) || (mode_dt_start_==-1)) )
    {
// On divise par facsec_ car multiplication par facsec_ dans corriger_dt_calcule()
// quel que soit le mode d initialisation de dt_
      dt_=dt_min_/facsec_;
    }
  else if (mode_dt_start_>0)
    {
      dt_=mode_dt_start_/facsec_;
    }
  else
    {
      mettre_a_jour_dt_stab();
      dt_=dt_stab_;
    }
  dt_stab_=dt_;
  dt_failed_ = DBL_MAX;
}
References Probleme_base::calculer_pas_de_temps(), disable_dt_ev(), disable_progress(), dt_, dt_ev_, dt_failed_, dt_min_, dt_stab_, Probleme_base::equation(), est_egal(), Equation_base::expression_residu(), facsec_, Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), mettre_a_jour_dt_stab(), mode_dt_start_, nb_pas_dt_, Objet_U::nom_du_cas(), Probleme_base::nombre_d_equations(), Sortie_Fichier_base::ouvrir(), pb_base(), progress_, schema_impr(), Sortie_Fichier_base::setf(), and tinit_.
Referenced by Probleme_base::initialize().
initTimeStep()
bool Schema_Temps_base::initTimeStep (double dt) virtual
Reimplemented in Schema_Euler_Implicite, Schema_Implicite_Multi_TimeStep_base, and Sch_CN_iteratif.
Definition at line 124 of file Schema_Temps_base.cpp.
{
  dt_=dt;
  stationnaire_atteint_ = -1;
  residu_=0;
  return true;
}
References dt_, residu_, and stationnaire_atteint_.
Referenced by Schema_Temps::initTimeStep(), Probleme_base::initTimeStep(), Schema_Implicite_Multi_TimeStep_base::initTimeStep(), and Sch_CN_iteratif::initTimeStep().
isStationary()
bool Schema_Temps_base::isStationary () const virtual
Retourne 1 si lors du dernier pas de temps, le probleme n'a pas evolue.
Returns
1 si le probleme n'a pas evolue, 0 sinon.
Signification:
Contraintes:
Definition at line 297 of file Schema_Temps_base.cpp.
{
  if (stationnaire_atteint_ && (nb_pas_dt_ >= 2))
    {
      Cerr << "---------------------------------------------------------"
           << finl
           << "The problem " << pb_base().le_nom()
           << " has reached the steady state"
           << finl << finl;
      return true;
    }
  return false;
}
References Cerr, finl, Probleme_base::le_nom(), nb_pas_dt_, pb_base(), and stationnaire_atteint_.
Referenced by Multi_Sch_ThHyd::completer(), Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base(), and Probleme_base::isStationary().
iterateTimeStep()
bool Schema_Temps_base::iterateTimeStep (bool & converged) virtual
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
Reimplemented in Schema_Euler_Implicite, Schema_Implicite_Multi_TimeStep_base, Multi_Sch_ThHyd, and Sch_CN_iteratif.
Definition at line 136 of file Schema_Temps_base.cpp.
{
// Loop on the equations of the problem:
  for(int i=0; i<pb_base().nombre_d_equations(); i++)
    {
      Equation_base& equation=pb_base().equation(i);
// Calculate (if equation is solved) the unknown equation U(n+1)
// according to the selected time scheme:
      if (!equation.equation_non_resolue())
        faire_un_pas_de_temps_eqn_base(equation);
      else
        {
          Cout<< "====================================================" << finl;
          Cout<< equation.que_suis_je()<<" equation is not solved."<<finl;
          Cout<< "====================================================" << finl;
// On calcule une fois la derivee pour avoir les flux bord
          if (equation.schema_temps().nb_pas_dt()==0)
            {
              DoubleTab inconnue_valeurs(equation.inconnue().valeurs());
              equation.derivee_en_temps_inco(inconnue_valeurs);
            }
        }
    }
  converged=true;
  return true;
}
References Cout, Equation_base::derivee_en_temps_inco(), Probleme_base::equation(), Equation_base::equation_non_resolue(), faire_un_pas_de_temps_eqn_base(), finl, Equation_base::inconnue(), nb_pas_dt(), Probleme_base::nombre_d_equations(), pb_base(), Objet_U::que_suis_je(), Equation_base::schema_temps(), and Champ_Inc::valeurs().
Referenced by Schema_Temps::iterateTimeStep(), and Probleme_base::iterateTimeStep().
le_nom()
const Nom & Schema_Temps_base::le_nom () const inline override virtual
surcharge Objet_U::le_nom()
Renvoie le nom du shema en temps
Returns
Nom&
Signification: le nom du shema en temps
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 452 of file Schema_Temps_base.h.
{
  return nom_;
}
References nom_.
Referenced by Probleme_base::associer_sch_tps_base().
limpr()
int Schema_Temps_base::limpr () const
Renvoie 1 s'il y a lieu d'effectuer une impression (cf dt_impr)
Renvoie 0 sinon.
Returns
int
Signification: 1 si il y lieu d'effectuer une impression 0 sinon
Contraintes:
< Negative value for dt_impr : we never print
< No solve cause 0 time step : we print nothing
< We print every time step if dt_impr is lower than dt
< We print the first time step
< We print the last time step
Definition at line 178 of file Schema_Temps_base.cpp.
{
  if (dt_impr_<=0)
    return 0; //!< Negative value for dt_impr : we never print
  if (nb_pas_dt_==0)
    return 0; //!< No solve cause 0 time step : we print nothing
  if (dt_impr_<=dt_)
    return 1; //!< We print every time step if dt_impr is lower than dt
  if (nb_pas_dt_<=1)
    return 1; //!< We print the first time step
  if (tmax_<=temps_courant_ || nb_pas_dt_max_<=nb_pas_dt_ || stationnaires_atteints_)
    return 1; //!< We print the last time step
// 26/01/2010 : On utilise desormais la fonction "modf(operation , & partie entiere)" de math.h
// Cette fonction decompose le resultat de "operation" en une partie entiere et une partie decimale.
// Ainsi, on ne transforme plus un double en int avec tout les risques que cela comporte.
// ex : modf(9/7,&i) donne 1.000000 pour la partie entiere et 0.285714 pour le partie decimale
//
// epsilon permet d'assurer que le resultat de l'operation est independant de la precision machine :
// ex : 0.99999999/1.00000000 peut donner 0.99999999 ou 1.00000000 suivant les machines
// alors que
// ex : 0.99999999/1.00000000 + 1.e-8 donne tjrs 1.00000000.
  double i, j, epsilon = 1.e-8;
  modf(temps_courant_/dt_impr_ + epsilon, &i);
  modf(temps_precedent_/dt_impr_ + epsilon, &j);
  return ( i>j );
}
References dt_, dt_impr_, nb_pas_dt_, nb_pas_dt_max_, stationnaires_atteints_, temps_courant_, temps_precedent_, and tmax_.
Referenced by Equation_base::calculer_pas_de_temps(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), corriger_dt_calcule(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), imprimer(), Equation_base::limpr(), Probleme_base::limpr(), mettre_a_jour(), and validateTimeStep().
lire_motcle_non_standard()
int Schema_Temps_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Reimplemented in Schema_Euler_Implicite.
Definition at line 459 of file Schema_Temps_base.cpp.
{
  Motcle motlu;
  if (mot=="dt_start")
    {
      is>>motlu;
      Motcles les_mots2(4);
      les_mots2[0]="dt_std";
      les_mots2[1]="dt_min";
      les_mots2[2]="dt_calc";
      les_mots2[3]="dt_fixe";
      int rang2=les_mots2.search(motlu);
      switch(rang2)
        {
        case 0:
        case 1:
        case 2:
          {
            mode_dt_start_=-rang2;
            break;
          }
        case 3:
          {
            is >>mode_dt_start_;
            break;
          }
        default:
          {
            Cerr<<" We do not understand "<<motlu <<"in Schema_Temps_base::lire_motcle_non_standard"<<finl;
            Cerr<<"keywords understood "<<les_mots2<<finl;
            exit();
          }
        }
      return 1;
    }
  else if (mot=="nb_pas_dt_max")
    lire_nb_pas_dt_max(is);
  else if (mot=="periode_sauvegarde_securite_en_heures")
    lire_periode_sauvegarde_securite_en_heures(is);
  else if (mot=="tcpumax")
    lire_temps_cpu_max(is);
  else if (mot=="no_check_disk_space")
    file_allocation_=0;
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References Cerr, Process::exit(), file_allocation_, finl, lire_nb_pas_dt_max(), lire_periode_sauvegarde_securite_en_heures(), lire_temps_cpu_max(), mode_dt_start_, Objet_U::que_suis_je(), and Motcles::search().
lire_nb_pas_dt_max()
Entree & Schema_Temps_base::lire_nb_pas_dt_max (Entree & is) virtual
Definition at line 512 of file Schema_Temps_base.cpp.
{
  if (Process::je_suis_maitre())
    Cerr << "Reading of the maximum number of time steps"  << finl;
  is >> nb_pas_dt_max_;
  return is;
}
References Cerr, finl, Process::je_suis_maitre(), and nb_pas_dt_max_.
Referenced by lire_motcle_non_standard().
lire_periode_sauvegarde_securite_en_heures()
Entree & Schema_Temps_base::lire_periode_sauvegarde_securite_en_heures (Entree & is) virtual
< Conversion en secondes
Definition at line 520 of file Schema_Temps_base.cpp.
{
  if (Process::je_suis_maitre())
    Cerr << "Reading of the safety backup period in hours"  << finl;
  is >> periode_cpu_sans_sauvegarde_;
  periode_cpu_sans_sauvegarde_*=3600; //!< Conversion en secondes
  limite_cpu_sans_sauvegarde_ = periode_cpu_sans_sauvegarde_;
  return is;
}
References Cerr, finl, Process::je_suis_maitre(), limite_cpu_sans_sauvegarde_, and periode_cpu_sans_sauvegarde_.
Referenced by lire_motcle_non_standard().
lire_temps_cpu_max()
Entree & Schema_Temps_base::lire_temps_cpu_max (Entree & is) virtual
< Conversion en secondes
Definition at line 531 of file Schema_Temps_base.cpp.
{
  if (Process::je_suis_maitre())
    Cerr << "Reading the max cpu time allowed"  << finl;
  is >> tcpumax_;
  tcpumax_*=3600; //!< Conversion en secondes
  return is;
}
References Cerr, finl, Process::je_suis_maitre(), and tcpumax_.
Referenced by lire_motcle_non_standard().
lsauv()
int Schema_Temps_base::lsauv () const
Definition at line 734 of file Schema_Temps_base.cpp.
{
  if (dt_sauv_ <= 0.)
    return 0;
  else
    {
      if ( temps_cpu_ecoule_ > limite_cpu_sans_sauvegarde_ )
        {
          Cerr << "After these " << limite_cpu_sans_sauvegarde_/3600 << " hours of calculation, a backup will be made by security." << finl;
          return 1;
        }
      else
        {
          if (dt_sauv_<=dt_)
            return 1;
          else if (tmax_<=temps_courant_ || nb_pas_dt_max_<=nb_pas_dt_ || stationnaires_atteints_ || ind_temps_cpu_max_atteint || stop_lu())
            return 1;
          else
            {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
              double i, j, epsilon = 1.e-8;
              modf(temps_courant_/dt_sauv_ + epsilon, &i);
              modf(temps_precedent_/dt_sauv_ + epsilon, &j);
              return ( i>j ) ;
            }
        }
    }
  return 0;
}
References Cerr, dt_, dt_sauv_, finl, ind_temps_cpu_max_atteint, limite_cpu_sans_sauvegarde_, nb_pas_dt_, nb_pas_dt_max_, stationnaires_atteints_, stop_lu(), temps_courant_, temps_cpu_ecoule_, temps_precedent_, and tmax_.
Referenced by Schema_Temps::lsauv(), and Probleme_base::lsauv().
lu()
int Schema_Temps_base::lu () const inline
Definition at line 213 of file Schema_Temps_base.h.
  {
    return lu_;
  } ;
References lu_.
Referenced by Multi_Sch_ThHyd::completer(), and Discretiser::interpreter().
mettre_a_jour()
int Schema_Temps_base::mettre_a_jour () virtual
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
Returns
int
Signification: retourne toujours 1
Contraintes:
Reimplemented in Schema_Euler_Implicite, Schema_Implicite_Multi_TimeStep_base, and Multi_Sch_ThHyd.
Definition at line 674 of file Schema_Temps_base.cpp.
{
  temps_precedent_ = temps_courant_;
  temps_courant_ += dt_;
  nb_pas_dt_++;
// Compute next time step stability:
  mettre_a_jour_dt_stab();
  assert_parallel(dt_stab_);
  assert_parallel(temps_courant_);
  if (!ind_tps_final_atteint)
    ind_tps_final_atteint = (temps_courant_ >= tmax_);
  if (!ind_nb_pas_dt_max_atteint)
    ind_nb_pas_dt_max_atteint = (nb_pas_dt_ >= nb_pas_dt_max_);
  if (!ind_temps_cpu_max_atteint)
    ind_temps_cpu_max_atteint = (temps_cpu_ecoule_ >= tcpumax_);
// On incremente limite_cpu_sans_sauvegarde_
  if ( temps_cpu_ecoule_ > limite_cpu_sans_sauvegarde_ )
    {
      limite_cpu_sans_sauvegarde_ += periode_cpu_sans_sauvegarde_;
// Finalement, on double la limite, ainsi par defaut sauvegarde de securite 10h, 20h, 40h, 80h, 160h,....
// limite_cpu_sans_sauvegarde_ = 2 * limite_cpu_sans_sauvegarde_;
      if (dt_sauv_ <= 0.)
        Cerr << "NO next backup, by security, because dt_sauv = " << dt_sauv_ << finl;
      else
        Cerr << "The next backup, by security, will take place after " << limite_cpu_sans_sauvegarde_/3600 << " hours of calculation." << finl;
    }
// GF pour etre sur que tous les proc aient le meme temps ecoule
  if (je_suis_maitre())
    {
      temps_cpu_ecoule_ = statistiques().last_time(temps_total_execution_counter_);
    }
  envoyer_broadcast(temps_cpu_ecoule_,0);
#ifdef LIBCCC_USER
  if (je_suis_maitre() && limpr())
    {
      Cout << "[CCRT] ";
      double second_remain;
      int error = ccc_tremain(&second_remain);
      if(!error)
        {
          int hour_remain = (int)(second_remain/3600);
          second_remain-=hour_remain*3600;
          int minute_remain = (int)(second_remain/60);
          second_remain-=minute_remain*60;
          Cout << hour_remain <<"h"<<minute_remain<<"mn"<<second_remain<<"s before job is killed on CCRT." << finl;
        }
      else
        Cout << "Error." << finl;
    }
#endif
  return 1;
}
References assert_parallel(), ccc_tremain(), Cerr, Cout, dt_, dt_sauv_, dt_stab_, envoyer_broadcast(), finl, ind_nb_pas_dt_max_atteint, ind_temps_cpu_max_atteint, ind_tps_final_atteint, Process::je_suis_maitre(), Statistiques::last_time(), limite_cpu_sans_sauvegarde_, limpr(), mettre_a_jour_dt_stab(), nb_pas_dt_, nb_pas_dt_max_, periode_cpu_sans_sauvegarde_, statistiques(), tcpumax_, temps_courant_, temps_cpu_ecoule_, temps_precedent_, temps_total_execution_counter_, and tmax_.
Referenced by Schema_Temps::mettre_a_jour(), Schema_Implicite_Multi_TimeStep_base::mettre_a_jour(), Multi_Sch_ThHyd::mettre_a_jour(), Pbc_MED::readOn(), and validateTimeStep().
mettre_a_jour_dt()
virtual void Schema_Temps_base::mettre_a_jour_dt (double toto) inline virtual
Definition at line 108 of file Schema_Temps_base.h.
  {
    abort();
  };
References Process::abort().
mettre_a_jour_dt_stab()
void Schema_Temps_base::mettre_a_jour_dt_stab () virtual
Reimplemented in Sch_CN_EX_iteratif.
Definition at line 764 of file Schema_Temps_base.cpp.
{
  imprimer(Cout);
  dt_stab_=pb_base().calculer_pas_de_temps();
}
References Probleme_base::calculer_pas_de_temps(), Cout, dt_stab_, imprimer(), and pb_base().
Referenced by initialize(), Sch_CN_iteratif::initTimeStep(), and mettre_a_jour().
mode_dt_start()
double Schema_Temps_base::mode_dt_start () const inline
Definition at line 201 of file Schema_Temps_base.h.
  {
    return mode_dt_start_;
  } ;
References mode_dt_start_.
Referenced by Multi_Sch_ThHyd::completer().
modifier_second_membre()
virtual void Schema_Temps_base::modifier_second_membre (const Equation_base & eqn, DoubleTab & secmem) inline virtual
Reimplemented in Schema_Adams_Bashforth_base, Schema_Implicite_Multi_TimeStep_base, and Schema_Explicite_Multi_TimeStep_base.
Definition at line 338 of file Schema_Temps_base.h.
{ };
Referenced by Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
nb_impr()
int Schema_Temps_base::nb_impr () const inline
Renvoie le nombre d'impressions effectuees.
Returns
int
Signification: le nombre d'impressions effectuees
Contraintes:
Definition at line 769 of file Schema_Temps_base.h.
{
  return nb_impr_;
}
References nb_impr_.
Referenced by Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Loi_horaire::imprimer(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), and ouvrir_fichier_pena_th().
nb_pas_dt()
int Schema_Temps_base::nb_pas_dt () const inline
Renvoie le nombre de pas de temps effectues.
Returns
int
Signification: le nombre de pas de temps effectues
Contraintes:
Definition at line 750 of file Schema_Temps_base.h.
{
  return nb_pas_dt_;
}
References nb_pas_dt_.
Referenced by Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Equation_base::calculer_pas_de_temps(), Multi_Sch_ThHyd::completer(), Schema_Adams_Bashforth_order_3::compute_adams_bashforth_coefficients(), Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients(), Equation_base::ecrire_fichier_xyz(), RRK2::faire_un_pas_de_temps_eqn_base(), Navier_Stokes_std::impr(), Sch_CN_iteratif::initTimeStep(), iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Simple::iterer_eqn(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Source_Neutronique::limpr(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Modele_turbulence_scal_base::limpr_nusselt(), Mod_turb_hyd_base::limpr_ustar(), Schema_Adams_Bashforth_base::modifier_second_membre(), Schema_Adams_Moulton_base::modifier_second_membre_full_impl(), Schema_Backward_Differentiation_base::modify_equation_parameters(), Schema_Temps::nb_pas_dt(), Traitement_particulier_NS_canal::post_traitement_particulier(), Probleme_base::postraiter(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Schema_Backward_Differentiation_base::store_equation_parameters(), Postraitement::traiter_champs(), update_critere_statio(), and validateTimeStep().
nb_pas_dt_max()
int Schema_Temps_base::nb_pas_dt_max () const inline
Renvoie une reference sur le nombre de pas maxi.
Returns
double&
Signification:
Contraintes:
Definition at line 472 of file Schema_Temps_base.h.
{
  return nb_pas_dt_max_;
}
References nb_pas_dt_max_.
Referenced by Multi_Sch_ThHyd::completer(), Equation_base::ecrire_fichier_xyz(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Traitement_particulier_NS_canal::post_traitement_particulier(), Probleme_base::postraiter(), and validateTimeStep().
nb_pas_dt_max_atteint()
int Schema_Temps_base::nb_pas_dt_max_atteint () const inline
Renvoie 1 si (le nombre de pas de temps >= nombre de pas de temps maximum).
Renvoie 0 sinon.
Returns
int
Signification: 1 si le nombre de pas de temps maximum est depasse 0 sinon
Contraintes:
Definition at line 876 of file Schema_Temps_base.h.
{
  return ind_nb_pas_dt_max_atteint;
}
References ind_nb_pas_dt_max_atteint.
Referenced by Source_Neutronique::limpr(), Modele_turbulence_scal_base::limpr_nusselt(), Mod_turb_hyd_base::limpr_ustar(), and stop().
nb_valeurs_futures()
virtual int Schema_Temps_base::nb_valeurs_futures () const pure virtual
Implemented in TRUSTSchema_RK< _ORDRE_ >, TRUSTSchema_RK< Ordre_RK::DEUX_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::DEUX_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::TROIS_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::TROIS_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE_3_8 >, TRUSTSchema_RK< Ordre_RK::RATIO_DEUX >, TRUSTSchema_RK< Ordre_RK::UN >, Leap_frog, Pred_Cor, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_Multi_TimeStep_base, Multi_Sch_ThHyd, and Sch_CN_iteratif.
Referenced by Probleme_base::futureTime(), Equation_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), Fluide_base::initTimeStep(), QDM_Multiphase::initTimeStep(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Multi_Sch_ThHyd::nb_valeurs_futures(), and Equation_base::updateGivenFields().
nb_valeurs_temporelles()
virtual int Schema_Temps_base::nb_valeurs_temporelles () const pure virtual
Implemented in TRUSTSchema_RK< _ORDRE_ >, TRUSTSchema_RK< Ordre_RK::DEUX_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::DEUX_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::TROIS_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::TROIS_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE_3_8 >, TRUSTSchema_RK< Ordre_RK::RATIO_DEUX >, TRUSTSchema_RK< Ordre_RK::UN >, Leap_frog, Pred_Cor, Schema_Adams_Bashforth_order_2, Schema_Adams_Bashforth_order_3, Schema_Adams_Moulton_order_2, Schema_Adams_Moulton_order_3, Schema_Euler_Implicite, Multi_Sch_ThHyd, Sch_CN_iteratif, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Referenced by Echange_contact_VDF::completer(), Discret_Thyd::concentration(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Aire_interfaciale::discretiser(), Masse_Multiphase::discretiser(), Discret_Thermique::Fluctu_Temperature(), Discret_Thermique::Flux_Chaleur_Turb(), Discret_Thermique::flux_neutronique(), Schema_Adams_Bashforth_base::modifier_second_membre(), Multi_Sch_ThHyd::nb_valeurs_temporelles(), Schema_Implicite_Multi_TimeStep_base::nb_valeurs_temporelles_effectives(), Discret_Thermique::temperature(), VEF_1D::vitesse(), and Discret_Thyd::vitesse().
niter_max_diffusion_implicite()
int Schema_Temps_base::niter_max_diffusion_implicite () const inline
Definition at line 161 of file Schema_Temps_base.h.
  {
    return niter_max_diff_impl_;
  };//!< Iterations maximale pour GC implicitation
References niter_max_diff_impl_.
Referenced by Multi_Sch_ThHyd::completer(), and Equation_base::Gradient_conjugue_diff_impl().
no_conv_subiteration_diffusion_implicite()
int Schema_Temps_base::no_conv_subiteration_diffusion_implicite () const inline
Iterations maximale pour GC implicitation.
Definition at line 166 of file Schema_Temps_base.h.
  {
    return no_conv_subiteration_diff_impl_;
  };
References no_conv_subiteration_diff_impl_.
Referenced by Equation_base::derivee_en_temps_conv().
no_error_if_not_converged_diffusion_implicite()
int Schema_Temps_base::no_error_if_not_converged_diffusion_implicite () const inline
Definition at line 170 of file Schema_Temps_base.h.
  {
    return no_error_if_not_converged_diff_impl_;
  };
References no_error_if_not_converged_diff_impl_.
Referenced by Equation_base::Gradient_conjugue_diff_impl().
nommer()
void Schema_Temps_base::nommer (const Nom & name) inline override virtual
surcharge Objet_U::nommer(const Nom&)
Donne un nom au shema en temps
Reimplemented from Objet_U.
Definition at line 431 of file Schema_Temps_base.h.
{
  nom_=name;
}
References nom_.
pas_de_temps()
double Schema_Temps_base::pas_de_temps () const inline
Renvoie le pas de temps (delta_t) courant.
Returns
double
Signification: le pas de temps courant
Contraintes:
Definition at line 572 of file Schema_Temps_base.h.
{
  return dt_;
}
References dt_.
Referenced by Schema_Adams_Moulton_base::add_multi_timestep_data(), Schema_Backward_Differentiation_base::add_multi_timestep_data(), Operateur::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), ajouter_inertie(), Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), Echange_contact_Correlation_VDF::calculer_Tfluide(), Echange_contact_Correlation_VEF::calculer_Tfluide(), Op_Conv_EF::coefficient_btd(), Multi_Sch_ThHyd::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_pond(), Navier_Stokes_Fluide_Dilatable_Proto::correct_and_compute_u_np1(), Navier_Stokes_std::corriger_derivee_impl(), Equation_base::derivee_en_temps_conv(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Equation_base::ecrire_fichier_xyz(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), Equation_base::Gradient_conjugue_diff_impl(), Source_PDF_EF::impr(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Mod_turb_hyd_base::imprimer(), Modele_turbulence_scal_base::imprimer(), imprimer_temps_courant(), Equation_base::initTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Chimie::mettre_a_jour(), Postraitement::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Navier_Stokes_std::mettre_a_jour(), Sonde::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Schema_Adams_Bashforth_base::modifier_second_membre(), Champ_P1NC::norme_L2_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2_H1(), Schema_Temps::pas_de_temps(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), Traitement_particulier_Solide_canal_VDF::post_traitement_particulier(), Traitement_particulier_NS_chmoy_faceperio::post_traitement_particulier(), Traitement_particulier_NS_Profils_VDF::post_traitement_particulier(), Navier_Stokes_Fluide_Dilatable_Proto::prepare_and_solve_u_star(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projection_a_faire(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d(), Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Terme_Source_Canal_perio::source(), TRUSTSchema_RK< _ORDRE_ >::temps_defaut(), Leap_frog::temps_defaut(), Pred_Cor::temps_defaut(), Schema_Explicite_Multi_TimeStep_base::temps_defaut(), Schema_Implicite_Multi_TimeStep_base::temps_defaut(), TRUSTSchema_RK< _ORDRE_ >::temps_futur(), Leap_frog::temps_futur(), Pred_Cor::temps_futur(), Schema_Explicite_Multi_TimeStep_base::temps_futur(), Schema_Implicite_Multi_TimeStep_base::temps_futur(), Sch_CN_iteratif::temps_futur(), test_imposer_cond_lim(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Perte_Charge_Singuliere::update_K(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), Equation_base::updateGivenFields(), validateTimeStep(), and Terme_Source_Canal_perio::write_flow_rate().
pas_de_temps_locaux()
const DoubleTab & Schema_Temps_base::pas_de_temps_locaux () const inline
Definition at line 576 of file Schema_Temps_base.h.
{
  return dt_locaux_;
}
References dt_locaux_.
Referenced by Terme_Source_Canal_perio::source().
pas_temps_max() [1/2]
double & Schema_Temps_base::pas_temps_max () inline
Renvoie une reference sur le pas de temps maximum.
Returns
double&
Signification: le pas de temps maximum du schema en temps
Contraintes:
Definition at line 653 of file Schema_Temps_base.h.
{
  return dt_max_;
}
References dt_max_.
pas_temps_max() [2/2]
double Schema_Temps_base::pas_temps_max () const inline
Renvoie le pas de temps maximum.
(version const)
Returns
double
Signification: le pas de temps maximum du schema en temps
Contraintes:
Definition at line 634 of file Schema_Temps_base.h.
{
  return dt_max_;
}
References dt_max_.
Referenced by Equation_base::calculer_pas_de_temps(), Probleme_base::calculer_pas_de_temps(), Multi_Sch_ThHyd::completer(), Navier_Stokes_std::initTimeStep(), Schema_Temps::pas_temps_max(), Navier_Stokes_std::preparer_calcul(), and Navier_Stokes_std::projeter().
pas_temps_min() [1/2]
double & Schema_Temps_base::pas_temps_min () inline
Renvoie une reference sur le pas de temps minimum.
Returns
double&
Signification: le pas de temps minimum du schema en temps
Contraintes:
Definition at line 614 of file Schema_Temps_base.h.
{
  return dt_min_;
}
References dt_min_.
pas_temps_min() [2/2]
double Schema_Temps_base::pas_temps_min () const inline
Renvoie le pas de temps minimum.
(version const)
Returns
double
Signification: le pas de temps minimum du schema en temps
Contraintes:
Definition at line 595 of file Schema_Temps_base.h.
{
  return dt_min_;
}
References dt_min_.
Referenced by Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Multi_Sch_ThHyd::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_pond(), Traitement_particulier_NS_EC::lire(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Schema_Temps::pas_temps_min(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), and Terme_Source_Canal_perio::source().
pb_base() [1/2]
Probleme_base & Schema_Temps_base::pb_base ()
Definition at line 1022 of file Schema_Temps_base.cpp.
{
  return mon_probleme.valeur();
}
References mon_probleme, and Ref_Probleme_base::valeur().
Referenced by abortTimeStep(), Schema_Adams_Bashforth_base::associer_pb(), Schema_Adams_Moulton_base::associer_pb(), Loi_horaire::imprimer(), initialize(), isStationary(), iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), mettre_a_jour_dt_stab(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), stop(), update_critere_statio(), and validateTimeStep().
pb_base() [2/2]
const Probleme_base & Schema_Temps_base::pb_base () const
Definition at line 1027 of file Schema_Temps_base.cpp.
{
  return mon_probleme.valeur();
}
References mon_probleme, and Ref_Probleme_base::valeur().
precision_impr()
int Schema_Temps_base::precision_impr () const inline
Definition at line 184 of file Schema_Temps_base.h.
  {
    return precision_impr_;
  };
References precision_impr_.
Referenced by Loi_horaire::imprimer(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), and ouvrir_fichier_pena_th().
printOn()
Sortie & Schema_Temps_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Leap_frog, Pred_Cor, Schema_Adams_Bashforth_base, Schema_Adams_Bashforth_order_2, Schema_Adams_Bashforth_order_3, Schema_Adams_Moulton_base, Schema_Adams_Moulton_order_2, Schema_Adams_Moulton_order_3, Schema_Euler_explicite, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_base, Schema_Implicite_Multi_TimeStep_base, RK2_Classique, RK3_Classique, RK4_Classique, RK4_Classique_3_8, RRK2, RK2, RK3, RK4, Multi_Sch_ThHyd, Sch_CN_EX_iteratif, Sch_CN_iteratif, Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 375 of file Schema_Temps_base.cpp.
{
  os << "dt " << dt_ << finl;
  os << "temps_courant " << temps_courant_ << finl ;
  os << "tinit " << tinit_ << finl;
  os << "tmax " << tmax_ << finl ;
  os << "tcpumax " << tcpumax_ << finl ;
  os << "nb_pas_dt " << nb_pas_dt_ << finl;
  os << "nb_pas_dt_max " <<  nb_pas_dt_max_ << finl;
  os << "dt_min " << dt_min_ << finl;
  os << "dt_max " << dt_max_ << finl;
  os << "facsec " << facsec_ << finl;
  os << "seuil_statio" << seuil_statio_ << finl;
  os << "seuil_statio_relatif_deconseille" << seuil_statio_relatif_deconseille_ << finl;
  os << "dt_sauv " << dt_sauv_ << finl;
  os << "limite_cpu_sans_sauvegarde " << limite_cpu_sans_sauvegarde_ << finl;
  os << "dt_impr " << dt_impr_ << finl;
  os << "precision_impr " << precision_impr_ << finl;
  os << "stationnaire_atteint " << stationnaire_atteint_ << finl;
  os << "diffusion_implicite " << ind_diff_impl_ << finl ;
  os << "seuil_diffusion_implicite " << seuil_diff_impl_ << finl ;
  os << "impr_diffusion_implicite " << impr_diff_impl_ << finl ;
  os << "impr_extremums " << impr_extremums_ << finl ;
  os << "niter_max_diffusion_implicite " << niter_max_diff_impl_ << finl ;
  os << "no_file_allocation " << file_allocation_ << finl ;
  os << "disable_progress " << disable_progress_ << finl ;
  os << "disable_dt_ev " << disable_dt_ev_ << finl ;
  os << "fin " << finl;
  return os ;
}
References disable_dt_ev_, disable_progress_, dt_, dt_impr_, dt_max_, dt_min_, dt_sauv_, facsec_, file_allocation_, finl, impr_diff_impl_, impr_extremums_, ind_diff_impl_, limite_cpu_sans_sauvegarde_, nb_pas_dt_, nb_pas_dt_max_, niter_max_diff_impl_, precision_impr_, seuil_diff_impl_, seuil_statio_, seuil_statio_relatif_deconseille_, stationnaire_atteint_, tcpumax_, temps_courant_, tinit_, and tmax_.
Referenced by Leap_frog::printOn(), Pred_Cor::printOn(), Schema_Euler_explicite::printOn(), Schema_Explicite_Multi_TimeStep_base::printOn(), Schema_Implicite_base::printOn(), RK2_Classique::printOn(), RK3_Classique::printOn(), RK4_Classique::printOn(), RK4_Classique_3_8::printOn(), RRK2::printOn(), RK2::printOn(), RK3::printOn(), RK4::printOn(), Multi_Sch_ThHyd::printOn(), and Sch_CN_iteratif::printOn().
readOn()
Entree & Schema_Temps_base::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Leap_frog, Pred_Cor, Schema_Adams_Bashforth_base, Schema_Adams_Bashforth_order_2, Schema_Adams_Bashforth_order_3, Schema_Adams_Moulton_base, Schema_Adams_Moulton_order_2, Schema_Adams_Moulton_order_3, Schema_Euler_explicite, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_base, Schema_Implicite_Multi_TimeStep_base, RK2_Classique, RK3_Classique, RK4_Classique, RK4_Classique_3_8, RRK2, RK2, RK3, RK4, Multi_Sch_ThHyd, Sch_CN_EX_iteratif, Sch_CN_iteratif, Schema_Backward_Differentiation_base, Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 429 of file Schema_Temps_base.cpp.
{
  Cerr<<"Reading of data for a "<<que_suis_je()<<" time scheme"<<finl;
  Param param(que_suis_je());
  set_param(param);
  param.lire_avec_accolades_depuis(is);
  if (dt_min_==0)
    {
      Cerr<<"dt_min has not been read or is set to 0."<<finl;
      Cerr<<"Assign a value strictly positive to dt_min."<<finl;
      exit();
    }
  temps_courant_=tinit_;
  temps_precedent_=tinit_;
  lu_=1;
  if (dt_sauv_ <= 0.)
    Cerr << "NO next backup, by security, because dt_sauv = " << dt_sauv_ << finl;
  else
    Cerr << "The next backup, by security, will take place after " << limite_cpu_sans_sauvegarde_/3600 << " hours of calculation." << finl;
  if (dt_max_str_ != Nom())
    {
      dt_max_fn_.setNbVar(1);
      dt_max_fn_.setString(dt_max_str_);
      dt_max_fn_.addVar("t");
      dt_max_fn_.parseString();
      dt_max_ = dt_max_fn_.eval();
    }
  return is ;
}
References Parser_U::addVar(), Cerr, dt_max_, dt_max_fn_, dt_max_str_, dt_min_, dt_sauv_, Parser_U::eval(), Process::exit(), finl, limite_cpu_sans_sauvegarde_, Param::lire_avec_accolades_depuis(), lu_, Parser_U::parseString(), Objet_U::que_suis_je(), set_param(), Parser_U::setNbVar(), Parser_U::setString(), temps_courant_, temps_precedent_, and tinit_.
Referenced by Leap_frog::readOn(), Pred_Cor::readOn(), Schema_Euler_explicite::readOn(), Schema_Explicite_Multi_TimeStep_base::readOn(), Schema_Implicite_base::readOn(), RK2_Classique::readOn(), RK3_Classique::readOn(), RK4_Classique::readOn(), RK4_Classique_3_8::readOn(), RRK2::readOn(), RK2::readOn(), RK3::readOn(), RK4::readOn(), Multi_Sch_ThHyd::readOn(), Sch_CN_EX_iteratif::readOn(), and Sch_CN_iteratif::readOn().
reprendre()
int Schema_Temps_base::reprendre (Entree & is) override virtual
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Schema_Euler_Implicite, and Schema_Implicite_Multi_TimeStep_base.
Definition at line 855 of file Schema_Temps_base.cpp.
{
  return 1;
}
Referenced by Probleme_base::reprendre(), and Schema_Temps::reprendre().
residu() [1/2]
double & Schema_Temps_base::residu () inline
Definition at line 321 of file Schema_Temps_base.h.
  {
    return residu_ ;
  };
References residu_.
residu() [2/2]
const double & Schema_Temps_base::residu () const inline
Definition at line 317 of file Schema_Temps_base.h.
  {
    return residu_ ;
  };
References residu_.
Referenced by Probleme_Couple::solveTimeStep().
sauvegarder()
int Schema_Temps_base::sauvegarder (Sortie & os) const override virtual
Sauvegarde le temps courant et le nombre de pas de temps
sur un flot de sortie.
Reimplemented from Objet_U.
Definition at line 835 of file Schema_Temps_base.cpp.
{
  return 1;
}
Referenced by Probleme_base::sauvegarder(), and Schema_Temps::sauvegarder().
schema_impr() [1/2]
int & Schema_Temps_base::schema_impr () inline
Definition at line 325 of file Schema_Temps_base.h.
  {
    return schema_impr_ ;
  };
References schema_impr_.
Referenced by Probleme_Couple::associer_sch_tps_base(), imprimer(), initialize(), Probleme_Couple::initialize(), and validateTimeStep().
schema_impr() [2/2]
const int & Schema_Temps_base::schema_impr () const inline
Definition at line 329 of file Schema_Temps_base.h.
  {
    return schema_impr_ ;
  };
References schema_impr_.
self_cast() [1/2]
const Schema_Temps_base & Schema_Temps_base::self_cast (const Objet_U & r) static
Definition at line 31 of file Schema_Temps_base.cpp.
self_cast() [2/2]
Schema_Temps_base & Schema_Temps_base::self_cast (Objet_U & r) static
Definition at line 31 of file Schema_Temps_base.cpp.
set_diffusion_implicite()
int & Schema_Temps_base::set_diffusion_implicite () inline
Definition at line 289 of file Schema_Temps_base.h.
  {
    return ind_diff_impl_;
  } ;
References ind_diff_impl_.
Referenced by Multi_Sch_ThHyd::completer(), and iterer_eqn_expl_diffusion_implicite().
set_dt()
double & Schema_Temps_base::set_dt () inline
Definition at line 267 of file Schema_Temps_base.h.
  {
    return dt_;
  } ;
References dt_.
Referenced by Multi_Sch_ThHyd::completer(), and Navier_Stokes_std::preparer_calcul().
set_dt_impr()
double & Schema_Temps_base::set_dt_impr () inline
Definition at line 259 of file Schema_Temps_base.h.
  {
    return dt_impr_;
  } ;
References dt_impr_.
Referenced by Multi_Sch_ThHyd::completer().
set_dt_max()
double & Schema_Temps_base::set_dt_max () inline
Definition at line 250 of file Schema_Temps_base.h.
  {
    dt_max_str_ = Nom(); //desactive la fonction dt_max = f(t)
    return dt_max_;
  } ;
References dt_max_, and dt_max_str_.
Referenced by Multi_Sch_ThHyd::completer().
set_dt_min()
double & Schema_Temps_base::set_dt_min () inline
Definition at line 246 of file Schema_Temps_base.h.
  {
    return dt_min_;
  } ;
References dt_min_.
Referenced by Multi_Sch_ThHyd::completer().
set_dt_sauv()
double & Schema_Temps_base::set_dt_sauv () inline
Definition at line 255 of file Schema_Temps_base.h.
  {
    return dt_sauv_;
  } ;
References dt_sauv_.
Referenced by Multi_Sch_ThHyd::completer().
set_facsec()
double & Schema_Temps_base::set_facsec () inline
Definition at line 271 of file Schema_Temps_base.h.
  {
    return facsec_;
  } ;
References facsec_.
Referenced by Multi_Sch_ThHyd::completer().
set_indice_nb_pas_dt_max_atteint()
int & Schema_Temps_base::set_indice_nb_pas_dt_max_atteint () inline
Definition at line 309 of file Schema_Temps_base.h.
  {
    return ind_nb_pas_dt_max_atteint;
  } ;
References ind_nb_pas_dt_max_atteint.
Referenced by Multi_Sch_ThHyd::completer(), and Probleme_base::postraiter().
set_indice_tps_final_atteint()
int & Schema_Temps_base::set_indice_tps_final_atteint () inline
Definition at line 305 of file Schema_Temps_base.h.
  {
    return ind_tps_final_atteint;
  } ;
References ind_tps_final_atteint.
Referenced by Multi_Sch_ThHyd::completer(), and Probleme_base::postraiter().
set_lu()
int & Schema_Temps_base::set_lu () inline
Definition at line 313 of file Schema_Temps_base.h.
  {
    return lu_;
  } ;
References lu_.
Referenced by Multi_Sch_ThHyd::completer().
set_mode_dt_start()
double & Schema_Temps_base::set_mode_dt_start () inline
Definition at line 301 of file Schema_Temps_base.h.
  {
    return mode_dt_start_;
  } ;
References mode_dt_start_.
Referenced by Multi_Sch_ThHyd::completer().
set_nb_pas_dt()
int & Schema_Temps_base::set_nb_pas_dt () inline
Definition at line 238 of file Schema_Temps_base.h.
  {
    return nb_pas_dt_;
  } ;
References nb_pas_dt_.
Referenced by Multi_Sch_ThHyd::completer().
set_nb_pas_dt_max()
int & Schema_Temps_base::set_nb_pas_dt_max () inline
Definition at line 242 of file Schema_Temps_base.h.
  {
    return nb_pas_dt_max_;
  } ;
References nb_pas_dt_max_.
Referenced by Multi_Sch_ThHyd::completer().
set_niter_max_diffusion_implicite()
int & Schema_Temps_base::set_niter_max_diffusion_implicite () inline
Definition at line 297 of file Schema_Temps_base.h.
  {
    return niter_max_diff_impl_;
  } ;
References niter_max_diff_impl_.
Referenced by Multi_Sch_ThHyd::completer().
set_param()
void Schema_Temps_base::set_param (Param & titi) virtual
< XD_ADD_P double Value of initial calculation time (0 by default).
< XD_ADD_P double Time during which the calculation will be stopped (1e30s by default).
< XD_ADD_P double CPU time limit (must be specified in hours) for which the calculation is stopped (1e30s by default).
< XD_ADD_P double Minimum calculation time step (1e-16s by default).
< XD_ADD_P chaine Maximum calculation time step as function of time (1e30s by default).
< XD_ADD_P double Save time step value (1e30s by default). Every dt_sauv, fields are saved in the .sauv file. The file contains all the information saved over time. If this instruction is not entered, results are saved only upon calculation completion. To disable the writing of the .sauv files, you must specify 0. Note that dt_sauv is in terms of physical time (not cpu time).
< XD_ADD_P double Scheme parameter printing time step in time (1e30s by default). The time steps and the flux balances are printed (incorporated onto every side of processed domains) into the .out file.
< XD_ADD_P double Value assigned to the safety factor for the time step (1. by default). The time step calculated is multiplied by the safety factor. The first thing to try when a calculation does not converge with an explicit time scheme is to reduce the facsec to 0.5. NL2 Warning: Some schemes needs a facsec lower than 1 (0.5 is a good start), for example Schema_Adams_Bashforth_order_3.
< XD_ADD_P double Value of the convergence threshold (1e-12 by default). Problems using this type of time scheme converge when the derivatives dGi/dt NL1 of all the unknown transported values Gi have a combined absolute value less than this value. This is the keyword used to set the permanent rating threshold.
< XD_ADD_P int not_set
< XD_ADD_P int Keyword to make the diffusive term in the Navier-Stokes equations implicit (in this case, it should be set to 1). The stability time step is then only based on the convection time step (dt=facsec*dt_convection). Thus, in some circumstances, an important gain is achieved with respect to the time step (large diffusion with respect to convection on tightened meshes). Caution: It is however recommended that the user avoids exceeding the convection time step by selecting a too large facsec value. Start with a facsec value of 1 and then increase it gradually if you wish to accelerate calculation. In addition, for a natural convection calculation with a zero initial velocity, in the first time step, the convection time is infinite and therefore dt=facsec*dt_max.
< XD_ADD_P double This keyword changes the default value (1e-6) of convergency criteria for the resolution by conjugate gradient used for implicit diffusion.
< XD_ADD_P int Unactivate (default) or not the printing of the convergence during the resolution of the conjugate gradient.
< XD_ADD_P int Print unknowns extremas
< XD_ADD_P int not_set
< XD_ADD_P int not_set
< XD attr dt_start dt_start dt_start 1 dt_start dt_min : the first iteration is based on dt_min. NL2 dt_start dt_calc : the time step at first iteration is calculated in agreement with CFL condition. NL2 dt_start dt_fixe value : the first time step is fixed by the user (recommended when resuming calculation with Crank Nicholson temporal scheme to ensure continuity). NL2 By default, the first iteration is based on dt_calc. param.ajouter("nb_pas_dt_max",&nb_pas_dt_max_); nb_pas_dt_max non standard pour valgrind
< XD_ADD_P int Maximum number of calculation time steps (1e9 by default).
< XD_ADD_P int This keyword changes the default value (number of unknowns) of the maximal iterations number in the conjugate gradient method used for implicit diffusion.
< XD_ADD_P int Optional keyword to define the digit number for flux values printed into .out files (by default 3).
< XD_ADD_P double To change the default period (23 hours) between the save of the fields in .sauv file.
< XD_ADD_P flag To disable the check of the available amount of disk space during the calculation.
< XD_ADD_P flag To disable the writing of the .progress file.
< XD_ADD_P flag To disable the writing of the .dt_ev file.
< XD_ADD_P int Optional keyword to modify the header of the .out files. Allows to use the column title instead of columns number.
Reimplemented in Schema_Euler_Implicite, Schema_Implicite_Multi_TimeStep_base, Schema_Implicite_base, Multi_Sch_ThHyd, Sch_CN_EX_iteratif, and Sch_CN_iteratif.
Definition at line 328 of file Schema_Temps_base.cpp.
{
  param.ajouter("tinit",&tinit_); //!< XD_ADD_P double Value of initial calculation time (0 by default).
  param.ajouter( "tmax",&tmax_); //!< XD_ADD_P double Time during which the calculation will be stopped (1e30s by default).
  param.ajouter_non_std( "tcpumax",(this)); //!< XD_ADD_P double CPU time limit (must be specified in hours) for which the calculation is stopped (1e30s by default).
  param.ajouter( "dt_min",&dt_min_); //!< XD_ADD_P double Minimum calculation time step (1e-16s by default).
  param.ajouter( "dt_max",&dt_max_str_); //!< XD_ADD_P chaine Maximum calculation time step as function of time (1e30s by default).
  param.ajouter( "dt_sauv",&dt_sauv_); //!< XD_ADD_P double Save time step value (1e30s by default). Every dt_sauv, fields are saved in the .sauv file. The file contains all the information saved over time. If this instruction is not entered, results are saved only upon calculation completion. To disable the writing of the .sauv files, you must specify 0. Note that dt_sauv is in terms of physical time (not cpu time).
  param.ajouter( "dt_impr",&dt_impr_); //!< XD_ADD_P double Scheme parameter printing time step in time (1e30s by default). The time steps and the flux balances are printed (incorporated onto every side of processed domains) into the .out file.
  param.ajouter( "facsec",&facsec_); //!< XD_ADD_P double Value assigned to the safety factor for the time step (1. by default). The time step calculated is multiplied by the safety factor. The first thing to try when a calculation does not converge with an explicit time scheme is to reduce the facsec to 0.5. NL2 Warning: Some schemes needs a facsec lower than 1 (0.5 is a good start), for example Schema_Adams_Bashforth_order_3.
  param.ajouter( "seuil_statio",&seuil_statio_); //!< XD_ADD_P double Value of the convergence threshold (1e-12 by default). Problems using this type of time scheme converge when the derivatives dGi/dt NL1 of all the unknown transported values Gi have a combined absolute value less than this value. This is the keyword used to set the permanent rating threshold.
  param.ajouter( "seuil_statio_relatif_deconseille",&seuil_statio_relatif_deconseille_); //!< XD_ADD_P int not_set
  param.ajouter( "diffusion_implicite",&ind_diff_impl_); //!< XD_ADD_P int Keyword to make the diffusive term in the Navier-Stokes equations implicit (in this case, it should be set to 1). The stability time step is then only based on the convection time step (dt=facsec*dt_convection). Thus, in some circumstances, an important gain is achieved with respect to the time step (large diffusion with respect to convection on tightened meshes). Caution: It is however recommended that the user avoids exceeding the convection time step by selecting a too large facsec value. Start with a facsec value of 1 and then increase it gradually if you wish to accelerate calculation. In addition, for a natural convection calculation with a zero initial velocity, in the first time step, the convection time is infinite and therefore dt=facsec*dt_max.
  param.ajouter( "seuil_diffusion_implicite",&seuil_diff_impl_); //!< XD_ADD_P double This keyword changes the default value (1e-6) of convergency criteria for the resolution by conjugate gradient used for implicit diffusion.
  param.ajouter( "impr_diffusion_implicite",&impr_diff_impl_); //!< XD_ADD_P int Unactivate (default) or not the printing of the convergence during the resolution of the conjugate gradient.
  param.ajouter( "impr_extremums",&impr_extremums_); //!< XD_ADD_P int Print unknowns extremas
  param.ajouter( "no_error_if_not_converged_diffusion_implicite",&no_error_if_not_converged_diff_impl_); //!< XD_ADD_P int not_set
  param.ajouter( "no_conv_subiteration_diffusion_implicite",&no_conv_subiteration_diff_impl_); //!< XD_ADD_P int not_set
  param.ajouter_non_std( "dt_start",(this)); //!< XD attr dt_start dt_start dt_start 1 dt_start dt_min : the first iteration is based on dt_min. NL2 dt_start dt_calc : the time step at first iteration is calculated in agreement with CFL condition. NL2 dt_start dt_fixe value : the first time step is fixed by the user (recommended when resuming calculation with Crank Nicholson temporal scheme to ensure continuity). NL2 By default, the first iteration is based on dt_calc. param.ajouter( "nb_pas_dt_max",&nb_pas_dt_max_); nb_pas_dt_max non standard pour valgrind
//
//
  param.ajouter_non_std( "nb_pas_dt_max",(this)); //!< XD_ADD_P int Maximum number of calculation time steps (1e9 by default).
  param.ajouter( "niter_max_diffusion_implicite",&niter_max_diff_impl_); //!< XD_ADD_P int This keyword changes the default value (number of unknowns) of the maximal iterations number in the conjugate gradient method used for implicit diffusion.
  param.ajouter( "precision_impr",&precision_impr_); //!< XD_ADD_P int Optional keyword to define the digit number for flux values printed into .out files (by default 3).
  param.ajouter_non_std( "periode_sauvegarde_securite_en_heures",(this)); //!< XD_ADD_P double To change the default period (23 hours) between the save of the fields in .sauv file.
  param.ajouter_non_std( "no_check_disk_space",(this)); //!< XD_ADD_P flag To disable the check of the available amount of disk space during the calculation.
  param.ajouter_flag( "disable_progress",&disable_progress_); //!< XD_ADD_P flag To disable the writing of the .progress file.
  param.ajouter_flag( "disable_dt_ev",&disable_dt_ev_); //!< XD_ADD_P flag To disable the writing of the .dt_ev file.
  param.ajouter( "gnuplot_header",&gnuplot_header_); //!< XD_ADD_P int Optional keyword to modify the header of the .out files. Allows to use the column title instead of columns number.
}
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), disable_dt_ev_, disable_progress_, dt_impr_, dt_max_str_, dt_min_, dt_sauv_, facsec_, gnuplot_header_, impr_diff_impl_, impr_extremums_, ind_diff_impl_, niter_max_diff_impl_, no_conv_subiteration_diff_impl_, no_error_if_not_converged_diff_impl_, precision_impr_, seuil_diff_impl_, seuil_statio_, seuil_statio_relatif_deconseille_, tinit_, and tmax_.
Referenced by readOn(), Schema_Implicite_base::set_param(), Multi_Sch_ThHyd::set_param(), and Sch_CN_iteratif::set_param().
set_precision_impr()
int & Schema_Temps_base::set_precision_impr () inline
Definition at line 263 of file Schema_Temps_base.h.
  {
    return precision_impr_;
  } ;
References precision_impr_.
set_seuil_diffusion_implicite()
double & Schema_Temps_base::set_seuil_diffusion_implicite () inline
Definition at line 293 of file Schema_Temps_base.h.
  {
    return seuil_diff_impl_;
  } ;
References seuil_diff_impl_.
Referenced by Multi_Sch_ThHyd::completer(), and iterer_eqn_expl_diffusion_implicite().
set_seuil_statio()
double & Schema_Temps_base::set_seuil_statio () inline
Definition at line 275 of file Schema_Temps_base.h.
  {
    return seuil_statio_;
  } ;
References seuil_statio_.
Referenced by Multi_Sch_ThHyd::completer().
set_stationnaire_atteint()
int & Schema_Temps_base::set_stationnaire_atteint () inline
Definition at line 279 of file Schema_Temps_base.h.
  {
    if (stationnaire_atteint_==-1)
      stationnaire_atteint_=1;
    return stationnaire_atteint_;
  } ;
References stationnaire_atteint_.
Referenced by Multi_Sch_ThHyd::completer(), Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), and update_critere_statio().
set_stationnaires_atteints()
void Schema_Temps_base::set_stationnaires_atteints (bool flag) inline
Definition at line 285 of file Schema_Temps_base.h.
  {
    stationnaires_atteints_=flag;
  } ;
References stationnaires_atteints_.
Referenced by Probleme_base::setStationary().
set_temps_courant()
double & Schema_Temps_base::set_temps_courant () inline
Definition at line 230 of file Schema_Temps_base.h.
  {
    return temps_courant_;
  } ;
References temps_courant_.
Referenced by Multi_Sch_ThHyd::completer(), and Probleme_base::readOn().
set_temps_init()
double & Schema_Temps_base::set_temps_init () inline
Definition at line 222 of file Schema_Temps_base.h.
  {
    return tinit_;
  } ;
References tinit_.
Referenced by Multi_Sch_ThHyd::completer(), and Probleme_base::readOn().
set_temps_max()
double & Schema_Temps_base::set_temps_max () inline
Definition at line 226 of file Schema_Temps_base.h.
  {
    return tmax_;
  } ;
References tmax_.
Referenced by Multi_Sch_ThHyd::completer().
set_temps_precedent()
double & Schema_Temps_base::set_temps_precedent () inline
Definition at line 234 of file Schema_Temps_base.h.
  {
    return temps_precedent_;
  } ;
References temps_precedent_.
Referenced by Probleme_base::readOn().
seuil_diffusion_implicite()
double Schema_Temps_base::seuil_diffusion_implicite () const inline
Definition at line 149 of file Schema_Temps_base.h.
  {
    return seuil_diff_impl_;
  };        //!< Seuil pour implicitation de la diffusion par GC
References seuil_diff_impl_.
Referenced by Multi_Sch_ThHyd::completer(), Equation_base::Gradient_conjugue_diff_impl(), and iterer_eqn_expl_diffusion_implicite().
seuil_statio()
double Schema_Temps_base::seuil_statio () const inline
Renvoie une reference sur le seuil stationnaire.
Returns
double&
Signification:
Contraintes:
Definition at line 492 of file Schema_Temps_base.h.
{
  return seuil_statio_;
}
References seuil_statio_.
Referenced by Multi_Sch_ThHyd::completer().
stationnaire_atteint()
int Schema_Temps_base::stationnaire_atteint () const inline
Definition at line 142 of file Schema_Temps_base.h.
  {
    assert(stationnaire_atteint_!=-1);
    return stationnaire_atteint_;
  };
References stationnaire_atteint_.
Referenced by Equation_base::ecrire_fichier_xyz(), Source_Neutronique::limpr(), Modele_turbulence_scal_base::limpr_nusselt(), Mod_turb_hyd_base::limpr_ustar(), Traitement_particulier_NS_canal::post_traitement_particulier(), and Probleme_Couple::solveTimeStep().
stop()
int Schema_Temps_base::stop () const virtual
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier (voir int Schema_Temps_base::stop_lu())
Renvoie 0 sinon.
Returns
int
Signification: 1 si il y a lieu de stopper le calcul 0 sinon.
Contraintes:
Reimplemented in Multi_Sch_ThHyd.
Definition at line 974 of file Schema_Temps_base.cpp.
{
  if (temps_final_atteint())
    {
      Cerr << "---------------------------------------------------------"
           << finl
           << "The problem " << pb_base().le_nom()
           << " wants to stop : final time reached"
           << finl << finl;
      return 1;
    }
  if ((nb_pas_dt_max_atteint()) || nb_pas_dt_max_==0)
    {
      Cerr << "---------------------------------------------------------"
           << finl
           << "The problem " << pb_base().le_nom()
           << " wants to stop : the maximum number of time steps reached"
           << finl << finl;
      return 1;
    }
  if (temps_cpu_max_atteint())
    {
      Cerr << "---------------------------------------------------------"
           << finl
           << "The problem " << pb_base().le_nom()
           << " wants to stop : max cpu time reached"
           << finl << finl;
      return 1;
    }
  if (!get_disable_stop())
    {
      if (stop_lu())
        {
          Cerr << "---------------------------------------------------------"
               << finl
               << "The problem " << pb_base().le_nom()
               << " wants to stop : stop file detected"
               << finl << finl;
          return 1;
        }
    }
  return 0;
}
References Cerr, finl, get_disable_stop(), Probleme_base::le_nom(), nb_pas_dt_max_, nb_pas_dt_max_atteint(), pb_base(), stop_lu(), temps_cpu_max_atteint(), and temps_final_atteint().
Referenced by computeTimeStep(), Schema_Temps::stop(), Multi_Sch_ThHyd::stop(), and ICoCo::ProblemTrio::validateTimeStep().
stop_lu()
int Schema_Temps_base::stop_lu () const
Renvoie 1 si le fichier (d'extension) .stop contient un 1
Renvoie 0 sinon.
Returns
int
Signification: 1 si le fichier (d'extension) .stop contient 1, 0 sinon
Contraintes:
Definition at line 875 of file Schema_Temps_base.cpp.
{
  int stop_lu_l = 0;
  Nom nomfic(nom_du_cas());
  nomfic+=".stop";
  if (nb_pas_dt_ < 1)
    {
      if(je_suis_maitre())
        {
          SFichier ficstop(nomfic);
          ficstop << stop_lu_l;
        }
    }
  else
    {
      LecFicDiffuse ficstop(nomfic);
// On verifie s'il reste de la place
// sur le disque en fonction de la
// taille du probleme estimee
// int ram=
#ifdef HPPA
      Nom command("bdf");
#else
      Nom command("df -k");
#endif
// Essayer avec stat -f -t . | awk '{print 4*$8}' ? Ca semble plus rapide...
// Mieux : stat -f -t . | cut -d " " -f8
      command+=" . | awk '/\\//!< && /%/ {print $(NF-2)\" Kbytes available sur \" $NF}'"; Cerr << system(command) << finl;
//
      ficstop >> stop_lu_l;
    }
  return stop_lu_l;
}
References Cerr, finl, Process::je_suis_maitre(), nb_pas_dt_, and Objet_U::nom_du_cas().
Referenced by Equation_base::ecrire_fichier_xyz(), Mod_turb_hyd_base::limpr_ustar(), lsauv(), and stop().
temps_calcul()
double Schema_Temps_base::temps_calcul () const inline
Renvoie le temps de calcul ecoule i.e. (temps courant - temps initial).
Returns
double
Signification: le temps de calcul ecoule
Contraintes:
Definition at line 711 of file Schema_Temps_base.h.
{
  return temps_courant_ - tinit_;
}
References temps_courant_, and tinit_.
Referenced by Schema_Temps::temps_calcul(), and Postraitement::traiter_sondes().
temps_courant()
double Schema_Temps_base::temps_courant () const inline
Renvoie le temps courant.
Returns
double
Signification: le temps courant du schema en temps
Contraintes:
Definition at line 672 of file Schema_Temps_base.h.
{
  return temps_courant_;
}
References temps_courant_.
Referenced by Op_Dift_VDF_Face_Axi_base::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Terme_Source_Canal_RANS_LES_VDF_Elem::ajouter_blocs(), Terme_Source_Canal_RANS_LES_VDF_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Op_Dift_VDF_Face_Axi_base::ajouter_contribution(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Champ_P1NC::calcul_h_conv(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Multi_Sch_ThHyd::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_Correlation_VEF::completer(), Fluide_Dilatable_base::completer(), Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), computeTimeStep(), Discret_Thyd::concentration(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), Perte_Charge_VEF::contribuer_a_avec(), EF_discretisation::creer_champ_vorticite(), PolyMAC_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Discret_Thyd::diametre_hydraulique_elem(), Discret_Thyd::diametre_hydraulique_face(), Mod_turb_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser(), Aire_interfaciale::discretiser(), Masse_Multiphase::discretiser(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Mod_turb_hyd_base::discretiser_corr_visc_turb(), Mod_turb_hyd_base::discretiser_K(), Mod_turb_hyd_base::discretiser_visc_turb(), EF_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), Discret_Thyd::divergence_U(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Equation_base::ecrire_fichier_xyz(), Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_spat(), Terme_Source_Canal_RANS_LES_VDF_Face::ecriture_moy_temp(), Discret_Thyd::entcor(), Equation_base::equation_non_resolue(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Discret_Thermique::Fluctu_Temperature(), Discret_Thermique::Flux_Chaleur_Turb(), Discret_Thermique::flux_neutronique(), Source_PDF_base::fonct_coeff(), Pb_MED::get_champ(), Navier_Stokes_std::get_champ(), Turbulence_paroi_base::get_champ(), Discret_Thyd::gradient_P(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Loi_horaire::imprimer(), Mod_turb_hyd_base::imprimer(), Modele_turbulence_scal_base::imprimer(), imprimer_temps_courant(), Terme_Source_Canal_RANS_LES_VDF_Elem::init(), Terme_Source_Canal_RANS_LES_VDF_Face::init(), Terme_Source_Canal_RANS_LES_VEF_Face::init(), Postraitement::init(), Loi_Etat_base::initialiser_inco_ch(), Equation_base::initTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Terme_Source_Acceleration::lire_data(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Fluide_Weakly_Compressible::mettre_a_jour_bis(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Discret_Thyd::porosite_volumique(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde::postraiter(), Probleme_base::postraiter(), Postraitement::postraiter(), Postraitement::postraiter_champs(), Postraitement::postraiter_sondes(), Postraitement::postraiter_tableaux(), Fluide_Quasi_Compressible::prepare_pressure_edo(), Equation_base::preparer_calcul(), Loi_Fermeture_base::preparer_calcul(), Probleme_base::preparer_calcul(), Loi_Etat_base::preparer_calcul(), Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Concentration::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Pb_Multiphase::preparer_calcul(), Fluide_Dilatable_base::preparer_pas_temps(), Probleme_base::presentTime(), Discret_Thyd::pression(), Discret_Thyd::pression_en_pa(), Navier_Stokes_std::projection_a_faire(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Equation_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Convection_Diffusion_Chaleur_WC::reprendre(), Convection_Diffusion_Espece_Binaire_WC::reprendre(), Navier_Stokes_std::reprendre(), Postraitement::reprendre(), Operateurs_Statistique_tps::reprendre(), Champ_Inc_base::sauvegarder(), Modele_turbulence_hyd_nul::sauvegarder(), Postraitement::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), Discret_Thyd::section_passage(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), Terme_Source_Canal_perio::source(), Discret_Thermique::temperature(), Schema_Temps::temps_courant(), TRUSTSchema_RK< _ORDRE_ >::temps_defaut(), Leap_frog::temps_defaut(), Pred_Cor::temps_defaut(), Schema_Explicite_Multi_TimeStep_base::temps_defaut(), Schema_Implicite_Multi_TimeStep_base::temps_defaut(), TRUSTSchema_RK< _ORDRE_ >::temps_futur(), Leap_frog::temps_futur(), Pred_Cor::temps_futur(), Schema_Explicite_Multi_TimeStep_base::temps_futur(), Schema_Implicite_Multi_TimeStep_base::temps_futur(), Sch_CN_iteratif::temps_futur(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), test_imposer_cond_lim(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Postraitement::traiter_champs(), Postraitement::traiter_sondes(), Postraitement::traiter_tableaux(), Discret_Thyd::translation(), Perte_Charge_Singuliere::update_K(), Equation_base::updateGivenFields(), validateTimeStep(), VEF_1D::vitesse(), Discret_Thyd::vitesse(), Discretisation_base::volume_maille(), and Terme_Source_Canal_perio::write_flow_rate().
temps_cpu_max_atteint()
int Schema_Temps_base::temps_cpu_max_atteint () const inline
Definition at line 881 of file Schema_Temps_base.h.
{
  return ind_temps_cpu_max_atteint;
}
References ind_temps_cpu_max_atteint.
Referenced by Mod_turb_hyd_base::limpr_ustar(), and stop().
temps_defaut()
virtual double Schema_Temps_base::temps_defaut () const pure virtual
Implemented in TRUSTSchema_RK< _ORDRE_ >, TRUSTSchema_RK< Ordre_RK::DEUX_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::DEUX_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::TROIS_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::TROIS_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE_3_8 >, TRUSTSchema_RK< Ordre_RK::RATIO_DEUX >, TRUSTSchema_RK< Ordre_RK::UN >, Leap_frog, Pred_Cor, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_Multi_TimeStep_base, Multi_Sch_ThHyd, and Sch_CN_iteratif.
Referenced by Equation_base::initTimeStep(), Probleme_base::initTimeStep(), Probleme_base::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Probleme_base::solveTimeStep(), and Multi_Sch_ThHyd::temps_defaut().
temps_final_atteint()
int Schema_Temps_base::temps_final_atteint () const inline
Renvoie 1 si le temps final est atteint (ou depasse).
Renvoie 1 si temps_courant_ >= tmax
Renvoie 0 sinon.
Returns
int
Signification: 1 si le temps final est atteint 0 sinon
Contraintes:
Definition at line 855 of file Schema_Temps_base.h.
{
  return ind_tps_final_atteint;
}
References ind_tps_final_atteint.
Referenced by Source_Neutronique::limpr(), Modele_turbulence_scal_base::limpr_nusselt(), Mod_turb_hyd_base::limpr_ustar(), and stop().
temps_futur()
virtual double Schema_Temps_base::temps_futur (int i) const pure virtual
Implemented in TRUSTSchema_RK< _ORDRE_ >, TRUSTSchema_RK< Ordre_RK::DEUX_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::DEUX_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::TROIS_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::TROIS_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_WILLIAMSON >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE >, TRUSTSchema_RK< Ordre_RK::QUATRE_CLASSIQUE_3_8 >, TRUSTSchema_RK< Ordre_RK::RATIO_DEUX >, TRUSTSchema_RK< Ordre_RK::UN >, Leap_frog, Pred_Cor, Schema_Euler_Implicite, Schema_Explicite_Multi_TimeStep_base, Schema_Implicite_Multi_TimeStep_base, Multi_Sch_ThHyd, and Sch_CN_iteratif.
Referenced by Probleme_base::futureTime(), Equation_base::initTimeStep(), Navier_Stokes_std::initTimeStep(), Fluide_base::initTimeStep(), QDM_Multiphase::initTimeStep(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Multi_Sch_ThHyd::temps_futur(), and Equation_base::updateGivenFields().
temps_impr()
double Schema_Temps_base::temps_impr () const inline
Renvoie une reference sur le temps d'impression.
Returns
double&
Signification:
Contraintes:
Definition at line 512 of file Schema_Temps_base.h.
{
  return dt_impr_;
}
References dt_impr_.
Referenced by Multi_Sch_ThHyd::completer(), and Mod_turb_hyd_base::limiter_viscosite_turbulente().
temps_init()
double Schema_Temps_base::temps_init () const inline
Renvoie le temps initial.
Returns
double
Signification: le temps de calcul ecoule
Contraintes:
Definition at line 730 of file Schema_Temps_base.h.
{
  return tinit_;
}
References tinit_.
Referenced by Multi_Sch_ThHyd::completer(), Marqueur_Lagrange_base::discretiser(), Equation_base::get_champ(), Convection_Diffusion_Temperature::get_champ(), Navier_Stokes_std::get_champ(), Postraitement::init(), Probleme_base::postraiter(), Probleme_base::readOn(), Terme_Source_Canal_perio::source(), Loi_horaire::tester(), and Terme_Source_Canal_perio::write_flow_rate().
temps_max()
double Schema_Temps_base::temps_max () const inline
Renvoie une reference sur le temps maximum.
Returns
double&
Signification:
Contraintes:
Definition at line 552 of file Schema_Temps_base.h.
{
  return tmax_;
}
References tmax_.
Referenced by Multi_Sch_ThHyd::completer(), Equation_base::ecrire_fichier_xyz(), Echange_contact_Correlation_VDF::limpr(), Echange_contact_Correlation_VEF::limpr(), Traitement_particulier_NS_canal::post_traitement_particulier(), Probleme_base::postraiter(), Loi_horaire::tester(), and validateTimeStep().
temps_precedent()
double Schema_Temps_base::temps_precedent () const inline
Renvoie le temps courant.
Returns
double
Signification: le temps courant du schema en temps
Contraintes:
Definition at line 692 of file Schema_Temps_base.h.
{
  return temps_precedent_;
}
References temps_precedent_.
Referenced by Source_QC_Chaleur::ajouter_(), Source_WC_Chaleur::ajouter_(), Mod_turb_hyd_base::imprimer(), and Modele_turbulence_scal_base::imprimer().
temps_sauv()
double Schema_Temps_base::temps_sauv () const inline
Renvoie une reference sur le temps de sauvegarde.
Returns
double&
Signification:
Contraintes:
Definition at line 532 of file Schema_Temps_base.h.
{
  return dt_sauv_;
}
References dt_sauv_.
Referenced by Multi_Sch_ThHyd::completer().
terminate()
void Schema_Temps_base::terminate () virtual
Definition at line 277 of file Schema_Temps_base.cpp.
{
  if (je_suis_maitre() && !disable_progress())
    progress_<< (int)100<< finl;
}
References disable_progress(), finl, Process::je_suis_maitre(), and progress_.
Referenced by Probleme_base::terminate().
update_critere_statio()
void Schema_Temps_base::update_critere_statio (const DoubleTab & tab_critere, Equation_base & equation)
//Actualisation de stationnaire_atteint_ et residu_
(critere residu_<seuil_statio_)
Definition at line 1063 of file Schema_Temps_base.cpp.
{
  DoubleVect& residu_equation = equation.get_residu();
// En fonction de la taille du tableau residu_equation
// on prend le max de tab_critere sur tout le tableau ou par colonne
  int size = residu_equation.size_array();
  if (size==0)
    {
      Cerr << "Error in Schema_Temps_base::update_critere_statio" << finl;
      Cerr << "Array residu_equation has a null size" << finl;
      for (int i=0; i<pb_base().nombre_d_equations(); i++)
        if (pb_base().equation(i).get_residu().size_array()==0)
          {
            Cerr << "The equation of kind " << pb_base().equation(i).que_suis_je() << " didn't size the array." << finl;
            Cerr << "Please, contact TRUST support." << finl;
            exit();
          }
    }
  else if (size==1)
    residu_equation(0) = mp_max_abs_vect(tab_critere);
  else
    mp_max_abs_tab(tab_critere, residu_equation);
  DoubleTab tab_critere_abs(tab_critere);
  const int n = tab_critere_abs.dimension_tot(0);
  if(size == 1)
    for(int i=0; i< n; i++)
      tab_critere_abs(i) = std::fabs(tab_critere_abs(i));
  else
    for(int j=0; j<size; j++)
      for(int i=0; i< n; i++)
        tab_critere_abs(i,j) = std::fabs(tab_critere_abs(i,j));
  equation.set_residuals(tab_critere_abs);
// On calcule le residu_initial_equation sur les 5 premiers pas de temps
  if (seuil_statio_relatif_deconseille_)
    {
      DoubleVect& residu_initial_equation = equation.residu_initial();
      if (nb_pas_dt()<6)
        {
          for (int i=0; i<size; i++)
            residu_initial_equation(i) = residu_equation(i);
// On ne prend plus le max car celui ci est parfois grand au premier pas de temps:
// residu_initial_equation(i) = std::max(residu_initial_equation(i), residu_equation(i));
        }
// On normalise residu_equation par residu_initial_equation
      for (int i=0; i<size; i++)
        if (residu_initial_equation(i)>0)
          residu_equation(i) /= residu_initial_equation(i);
    }
  if (!equation.disable_equation_residual())
    {
// double equation_residual = mp_max_abs_vect(residu_equation);
      double equation_residual = local_max_abs_vect(residu_equation);
      residu_ = std::max(residu_, equation_residual);
      set_stationnaire_atteint() *= (equation_residual < seuil_statio_);
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), Equation_base::disable_equation_residual(), Probleme_base::equation(), Process::exit(), finl, Equation_base::get_residu(), local_max_abs_vect(), mp_max_abs_tab(), mp_max_abs_vect(), nb_pas_dt(), Probleme_base::nombre_d_equations(), pb_base(), Objet_U::que_suis_je(), residu_, Equation_base::residu_initial(), Equation_base::set_residuals(), set_stationnaire_atteint(), seuil_statio_, seuil_statio_relatif_deconseille_, and TRUSTArray< _TYPE_ >::size_array().
Referenced by Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), and Schema_Implicite_Multi_TimeStep_base::test_stationnaire().
validateTimeStep()
void Schema_Temps_base::validateTimeStep () virtual
< marche meme si c'est ltemps max qui limite si la pente est >0 on diverge ....
< dans un pb_couple on peut avoir (seuil_statio_ > residu) pour un des problemes
Definition at line 206 of file Schema_Temps_base.cpp.
{
  statistiques().begin_count(mettre_a_jour_counter_);
// Update the problem:
  Probleme_base& problem=pb_base();
  problem.mettre_a_jour(temps_courant_+dt_);
  if (je_suis_maitre())
    {
      if (!disable_dt_ev())
        {
          if (schema_impr())
            dt_ev_ << finl << temps_courant_ << "\t " << dt_ << "\t " << facsec_ <<"\t " << residu_ << "\t " << dt_stab_ << "\t ";
          for (int i=0; i<pb_base().nombre_d_equations(); i++)
            pb_base().equation(i).imprime_residu(dt_ev_);
        }
// Impression du temps CPU estime restant
      if (schema_impr())
        {
          if ((residu_>0)&&(residu_old_slope_>0))
            cumul_slope_+=(log(residu_)-log(residu_old_slope_))/dt_;
          residu_old_slope_=residu_;
        }
      if (schema_impr()&&(nb_pas_dt()>0 && pas_de_temps()>0))
        {
// On calcule le temps CPU moyen par pas de temps, inconvenient il peut varier fortement au cours du temps si divergence du calcul ou au contraire acceleration
// Mais Statistiques ne permet pas d'avoir le temps CPU du dernier pas de temps (last_time appele ici renverrait le temps CPU depuis le debut du pas de temps)
// double cpu_per_timestep           = statistiques().last_time(temps_total_execution_counter_) / nb_pas_dt();
          double nb_pas_selon_tmax          = (temps_max()-temps_courant()) / pas_de_temps();
          double nb_pas_selon_nb_pas_dt_max = nb_pas_dt_max() - nb_pas_dt();
          double nb_pas_avant_fin= std::min(nb_pas_selon_tmax,nb_pas_selon_nb_pas_dt_max);
// double seconds_to_finish  = nb_pas_avant_fin * cpu_per_timestep;
          double dpercent=(1.-nb_pas_avant_fin/(nb_pas_avant_fin+ nb_pas_dt()));    //!< marche meme si c'est ltemps max qui limite si la pente est >0 on diverge ....
//
          if ((seuil_statio_>0)&&(cumul_slope_<-1e-20) && seuil_statio_ < residu_) //!< dans un pb_couple on peut avoir (seuil_statio_ > residu) pour un des problemes
            {
              double distance= (-log(residu_+1e-20)+log(seuil_statio_))/(cumul_slope_)* nb_pas_dt();
// Cerr<<distance<<" DDDDDD"<<finl;
              double dpercent2=temps_courant()/(temps_courant()+distance);
              dpercent=std::max(dpercent,dpercent2);
            }
          int percent=int(dpercent*100);
          if (limpr() )
            {
              double seconds_to_finish  =  statistiques().last_time(temps_total_execution_counter_)*(1.-dpercent)/dpercent;
              int integer_limit=(int)(pow(2.0,(double)((sizeof(True_int)*8)-1))-1);
              if (seconds_to_finish<integer_limit)
                {
                  int h  = int(seconds_to_finish/3600);
                  int mn = int((seconds_to_finish-3600*h)/60);
                  int s  = int(seconds_to_finish-3600*h-60*mn);
                  Cout << finl << "Estimated CPU time to finish the run (according to " << (nb_pas_selon_tmax<nb_pas_selon_nb_pas_dt_max?"tmax":"nb_pas_dt_max") << " value) : ";
                  if (seconds_to_finish<1)
                    Cout << seconds_to_finish << " s";
                  else
                    Cout << h << "h" << mn << "mn" << s << "s";
                  Cout << ". Progress: "<<(percent)<< finl;
                }
            }
          if (!disable_progress() && Process::je_suis_maitre())
            progress_<< (percent)<< finl;
        }
    }
// Update time scheme:
  mettre_a_jour();
  statistiques().end_count(mettre_a_jour_counter_);
  dt_failed_ = DBL_MAX;
}
References Statistiques::begin_count(), Cout, cumul_slope_, disable_dt_ev(), disable_progress(), dt_, dt_ev_, dt_failed_, dt_stab_, Statistiques::end_count(), Probleme_base::equation(), facsec_, finl, Equation_base::imprime_residu(), Process::je_suis_maitre(), Statistiques::last_time(), limpr(), mettre_a_jour(), Probleme_base::mettre_a_jour(), mettre_a_jour_counter_, nb_pas_dt(), nb_pas_dt_max(), Probleme_base::nombre_d_equations(), pas_de_temps(), pb_base(), progress_, residu_, residu_old_slope_, schema_impr(), seuil_statio_, statistiques(), temps_courant(), temps_courant_, temps_max(), and temps_total_execution_counter_.
Referenced by Probleme_base::validateTimeStep().
wcol()
int Schema_Temps_base::wcol () const inline
Definition at line 188 of file Schema_Temps_base.h.
  {
// largeur minimale des colonnes des fichiers .out
// precision_impr_ + 9 car : -1.000e+150 on ajoute la longueur de "-1." et de "e+150" plus un espace
    return precision_impr_ + 9;
  };
References precision_impr_.
Referenced by Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), and Source_base::ouvrir_fichier().
Member Data Documentation
cumul_slope_
double Schema_Temps_base::cumul_slope_ protected
Definition at line 390 of file Schema_Temps_base.h.
Referenced by Schema_Temps_base(), and validateTimeStep().
disable_dt_ev_
int Schema_Temps_base::disable_dt_ev_ private
Flag to disable the writing of the .dt_ev file.
Definition at line 412 of file Schema_Temps_base.h.
Referenced by disable_dt_ev(), printOn(), Schema_Temps_base(), and set_param().
disable_progress_
int Schema_Temps_base::disable_progress_ private
Flag to disable the writing of the .progress file.
Definition at line 411 of file Schema_Temps_base.h.
Referenced by disable_progress(), printOn(), Schema_Temps_base(), and set_param().
dt_
double Schema_Temps_base::dt_ protected
Pas de temps de calcul.
Definition at line 360 of file Schema_Temps_base.h.
Referenced by abortTimeStep(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), impr(), initialize(), initTimeStep(), Schema_Implicite_Multi_TimeStep_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), limpr(), lsauv(), mettre_a_jour(), pas_de_temps(), printOn(), Schema_Temps_base(), set_dt(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), and validateTimeStep().
dt_failed_
double Schema_Temps_base::dt_failed_ protected
Definition at line 365 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), initialize(), and validateTimeStep().
dt_gf_
double Schema_Temps_base::dt_gf_ protected
Definition at line 366 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), Schema_Euler_Implicite::readOn(), and Schema_Temps_base().
dt_impr_
double Schema_Temps_base::dt_impr_ protected
Pas de temps d'impression.
Definition at line 385 of file Schema_Temps_base.h.
Referenced by limpr(), printOn(), Schema_Temps_base(), set_dt_impr(), set_param(), and temps_impr().
dt_locaux_
DoubleTab Schema_Temps_base::dt_locaux_ protected
Local time steps: Vector of size nb faces of the mesh.
Definition at line 361 of file Schema_Temps_base.h.
Referenced by pas_de_temps_locaux().
dt_max_
double Schema_Temps_base::dt_max_ mutable protected
Pas de temps max fixe par l'utilisateur.
Definition at line 374 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), corriger_dt_calcule(), pas_temps_max(), printOn(), readOn(), Schema_Temps_base(), and set_dt_max().
dt_max_fn_
Parser_U Schema_Temps_base::dt_max_fn_ mutable protected
Definition at line 376 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), and readOn().
dt_max_str_
Nom Schema_Temps_base::dt_max_str_ protected
Definition at line 375 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), readOn(), set_dt_max(), and set_param().
dt_min_
double Schema_Temps_base::dt_min_ protected
Pas de temps min fixe par l'utilisateur.
Definition at line 373 of file Schema_Temps_base.h.
Referenced by corriger_dt_calcule(), initialize(), pas_temps_min(), printOn(), readOn(), Schema_Temps_base(), set_dt_min(), and set_param().
dt_sauv_
double Schema_Temps_base::dt_sauv_ protected
Definition at line 381 of file Schema_Temps_base.h.
Referenced by lsauv(), mettre_a_jour(), printOn(), readOn(), Schema_Temps_base(), set_dt_sauv(), set_param(), and temps_sauv().
dt_stab_
double Schema_Temps_base::dt_stab_ protected
Pas de temps de stabilite.
Definition at line 377 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), corriger_dt_calcule(), initialize(), mettre_a_jour(), mettre_a_jour_dt_stab(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), and validateTimeStep().
facsec_
double Schema_Temps_base::facsec_ protected
Definition at line 378 of file Schema_Temps_base.h.
Referenced by Sch_CN_iteratif::ajuster_facsec(), Sch_CN_EX_iteratif::ajuster_facsec(), corriger_dt_calcule(), facteur_securite_pas(), RRK2::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), initialize(), Sch_CN_iteratif::initTimeStep(), Schema_Implicite_Multi_TimeStep_base::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::mettre_a_jour(), printOn(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Schema_Temps_base(), set_facsec(), set_param(), and validateTimeStep().
file_allocation_
int Schema_Temps_base::file_allocation_ protected
1 = allocation espace disque (par defaut), 0 sinon
Definition at line 405 of file Schema_Temps_base.h.
Referenced by file_allocation(), lire_motcle_non_standard(), printOn(), and Schema_Temps_base().
gnuplot_header_
int Schema_Temps_base::gnuplot_header_ protected
Definition at line 391 of file Schema_Temps_base.h.
Referenced by gnuplot_header(), Schema_Temps_base(), and set_param().
impr_diff_impl_
int Schema_Temps_base::impr_diff_impl_ protected
Definition at line 399 of file Schema_Temps_base.h.
Referenced by impr_diffusion_implicite(), printOn(), Schema_Temps_base(), and set_param().
impr_extremums_
int Schema_Temps_base::impr_extremums_ protected
Definition at line 400 of file Schema_Temps_base.h.
Referenced by impr_extremums(), printOn(), Schema_Temps_base(), and set_param().
ind_diff_impl_
int Schema_Temps_base::ind_diff_impl_ protected
Definition at line 397 of file Schema_Temps_base.h.
Referenced by diffusion_implicite(), printOn(), Schema_Temps_base(), set_diffusion_implicite(), and set_param().
ind_nb_pas_dt_max_atteint
int Schema_Temps_base::ind_nb_pas_dt_max_atteint protected
Definition at line 394 of file Schema_Temps_base.h.
Referenced by indice_nb_pas_dt_max_atteint(), mettre_a_jour(), nb_pas_dt_max_atteint(), Schema_Temps_base(), and set_indice_nb_pas_dt_max_atteint().
ind_temps_cpu_max_atteint
int Schema_Temps_base::ind_temps_cpu_max_atteint protected
Definition at line 395 of file Schema_Temps_base.h.
Referenced by lsauv(), mettre_a_jour(), Schema_Temps_base(), and temps_cpu_max_atteint().
ind_tps_final_atteint
int Schema_Temps_base::ind_tps_final_atteint protected
Definition at line 393 of file Schema_Temps_base.h.
Referenced by indice_tps_final_atteint(), mettre_a_jour(), Schema_Temps_base(), set_indice_tps_final_atteint(), and temps_final_atteint().
info_obj
const Type_info Schema_Temps_base::info_obj static
Definition at line 67 of file Schema_Temps_base.h.
limite_cpu_sans_sauvegarde_
double Schema_Temps_base::limite_cpu_sans_sauvegarde_ protected
Definition at line 382 of file Schema_Temps_base.h.
Referenced by lire_periode_sauvegarde_securite_en_heures(), lsauv(), mettre_a_jour(), printOn(), readOn(), and Schema_Temps_base().
lu_
int Schema_Temps_base::lu_ protected
Definition at line 396 of file Schema_Temps_base.h.
Referenced by lu(), readOn(), Schema_Temps_base(), and set_lu().
max_length_cl_
int Schema_Temps_base::max_length_cl_ protected
Definition at line 406 of file Schema_Temps_base.h.
mode_dt_start_
double Schema_Temps_base::mode_dt_start_ protected
mode calcul du pas de temps de depart
Definition at line 387 of file Schema_Temps_base.h.
Referenced by initialize(), lire_motcle_non_standard(), mode_dt_start(), Schema_Temps_base(), and set_mode_dt_start().
mon_probleme
Ref_Probleme_base Schema_Temps_base::mon_probleme protected
Definition at line 358 of file Schema_Temps_base.h.
Referenced by associer_pb(), corriger_dt_calcule(), and pb_base().
nb_impr_
int Schema_Temps_base::nb_impr_ mutable protected
Definition at line 372 of file Schema_Temps_base.h.
Referenced by imprimer(), nb_impr(), and Schema_Temps_base().
nb_pas_dt_
int Schema_Temps_base::nb_pas_dt_ protected
Definition at line 370 of file Schema_Temps_base.h.
Referenced by Leap_frog::faire_un_pas_de_temps_eqn_base(), impr(), initialize(), isStationary(), limpr(), lsauv(), mettre_a_jour(), nb_pas_dt(), printOn(), Schema_Temps_base(), set_nb_pas_dt(), and stop_lu().
nb_pas_dt_max_
int Schema_Temps_base::nb_pas_dt_max_ protected
Definition at line 371 of file Schema_Temps_base.h.
Referenced by limpr(), lire_nb_pas_dt_max(), lsauv(), mettre_a_jour(), nb_pas_dt_max(), printOn(), Schema_Temps_base(), set_nb_pas_dt_max(), and stop().
niter_max_diff_impl_
int Schema_Temps_base::niter_max_diff_impl_ protected
Definition at line 401 of file Schema_Temps_base.h.
Referenced by niter_max_diffusion_implicite(), printOn(), Schema_Temps_base(), set_niter_max_diffusion_implicite(), and set_param().
no_conv_subiteration_diff_impl_
int Schema_Temps_base::no_conv_subiteration_diff_impl_ protected
Definition at line 402 of file Schema_Temps_base.h.
Referenced by no_conv_subiteration_diffusion_implicite(), Schema_Temps_base(), and set_param().
no_error_if_not_converged_diff_impl_
int Schema_Temps_base::no_error_if_not_converged_diff_impl_ protected
Definition at line 403 of file Schema_Temps_base.h.
Referenced by no_error_if_not_converged_diffusion_implicite(), Schema_Temps_base(), and set_param().
nom_
Nom Schema_Temps_base::nom_ protected
Definition at line 359 of file Schema_Temps_base.h.
Referenced by le_nom(), and nommer().
periode_cpu_sans_sauvegarde_
double Schema_Temps_base::periode_cpu_sans_sauvegarde_ protected
Definition at line 383 of file Schema_Temps_base.h.
Referenced by lire_periode_sauvegarde_securite_en_heures(), mettre_a_jour(), and Schema_Temps_base().
precision_impr_
int Schema_Temps_base::precision_impr_ protected
Nombre de chiffres significatifs impression.
Definition at line 386 of file Schema_Temps_base.h.
Referenced by precision_impr(), printOn(), Schema_Temps_base(), set_param(), set_precision_impr(), and wcol().
progress_
SFichier Schema_Temps_base::progress_ private
Definition at line 410 of file Schema_Temps_base.h.
Referenced by initialize(), terminate(), and validateTimeStep().
residu_
double Schema_Temps_base::residu_ protected
Residu.
Definition at line 388 of file Schema_Temps_base.h.
Referenced by Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), initTimeStep(), Schema_Implicite_Multi_TimeStep_base::initTimeStep(), Schema_Implicite_Multi_TimeStep_base::mettre_a_jour(), Schema_Implicite_Multi_TimeStep_base::reprendre(), residu(), Schema_Temps_base(), update_critere_statio(), and validateTimeStep().
residu_old_slope_
double Schema_Temps_base::residu_old_slope_ protected
Definition at line 389 of file Schema_Temps_base.h.
Referenced by Schema_Temps_base(), and validateTimeStep().
schema_impr_
int Schema_Temps_base::schema_impr_ protected
1 si le schema a le droit d'imprimer dans le .out et dt_ev
Definition at line 404 of file Schema_Temps_base.h.
Referenced by schema_impr(), and Schema_Temps_base().
seuil_diff_impl_
double Schema_Temps_base::seuil_diff_impl_ protected
Definition at line 398 of file Schema_Temps_base.h.
Referenced by printOn(), Schema_Temps_base(), set_param(), set_seuil_diffusion_implicite(), and seuil_diffusion_implicite().
seuil_statio_
double Schema_Temps_base::seuil_statio_ protected
Definition at line 379 of file Schema_Temps_base.h.
Referenced by printOn(), Schema_Temps_base(), set_param(), set_seuil_statio(), seuil_statio(), update_critere_statio(), and validateTimeStep().
seuil_statio_relatif_deconseille_
int Schema_Temps_base::seuil_statio_relatif_deconseille_ protected
Drapeau pour specifier si seuil_statio_ est une valeur absolue (defaut) ou relative.
Definition at line 380 of file Schema_Temps_base.h.
Referenced by printOn(), Schema_Temps_base(), set_param(), and update_critere_statio().
stationnaire_atteint_
int Schema_Temps_base::stationnaire_atteint_ private
Stationary reached by the problem using this scheme.
Definition at line 408 of file Schema_Temps_base.h.
Referenced by initTimeStep(), isStationary(), printOn(), Schema_Temps_base(), set_stationnaire_atteint(), and stationnaire_atteint().
stationnaires_atteints_
bool Schema_Temps_base::stationnaires_atteints_ private
Stationary reached by the calculation (means all the problems reach stationary)
Definition at line 409 of file Schema_Temps_base.h.
Referenced by limpr(), lsauv(), Schema_Temps_base(), and set_stationnaires_atteints().
tcpumax_
double Schema_Temps_base::tcpumax_ protected
Definition at line 369 of file Schema_Temps_base.h.
Referenced by lire_temps_cpu_max(), mettre_a_jour(), printOn(), and Schema_Temps_base().
temps_courant_
double Schema_Temps_base::temps_courant_ protected
Definition at line 363 of file Schema_Temps_base.h.
Referenced by changer_temps_courant(), computeTimeStep(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), impr(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), Schema_Implicite_Multi_TimeStep_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), limpr(), lsauv(), mettre_a_jour(), printOn(), readOn(), set_temps_courant(), temps_calcul(), temps_courant(), and validateTimeStep().
temps_cpu_ecoule_
double Schema_Temps_base::temps_cpu_ecoule_ protected
Definition at line 384 of file Schema_Temps_base.h.
Referenced by lsauv(), mettre_a_jour(), and Schema_Temps_base().
temps_precedent_
double Schema_Temps_base::temps_precedent_ protected
Definition at line 364 of file Schema_Temps_base.h.
Referenced by computeTimeStep(), limpr(), lsauv(), mettre_a_jour(), readOn(), set_temps_precedent(), and temps_precedent().
tinit_
double Schema_Temps_base::tinit_ protected
Definition at line 367 of file Schema_Temps_base.h.
Referenced by initialize(), printOn(), readOn(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Schema_Temps_base(), set_param(), set_temps_init(), temps_calcul(), and temps_init().
tmax_
double Schema_Temps_base::tmax_ protected
Definition at line 368 of file Schema_Temps_base.h.
Referenced by limpr(), lsauv(), mettre_a_jour(), printOn(), Schema_Temps_base(), set_param(), set_temps_max(), and temps_max().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Schema_Temps_base.h
src/Kernel/Framework/Schema_Temps_base.cpp