TRUST: Sous_Zone Class Reference
Sous_Zone Class Reference
Classe Sous_Zone
Represente une sous zone volumique i.e un sous ensemble
de polyedres d'un objet de type Zone.
Un objet Sous_Zone porte une reference vers la zone qu'il
subdivise.
#include <Sous_Zone.h>
Public Member Functions
Sous_Zone ()
~Sous_Zone ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Sous_Zone (const Zone &)
Constructeur d'une sous-zone a partir d'une zone.
const Nom & le_nom () const override
Renvoie le nom de la sous-zone.
int operator() (int) const
Renvoie le numero du i-ieme polyedre de la sous-zone.
int operator[] (int) const
Renvoie le numero du i-ieme polyedre de la sous-zone.
int nb_elem_tot () const
Returns the subzone number of elements (real+virtual elements in parallel)
void associer_zone (const Zone &)
Associe une zone a la sous-zone.
La sous-zone sera une sous-zone de la Zone specifiee.
int associer_ (Objet_U &) override
Associe un Objet_U a la sous-zone.
On controle le type de l'objet a associer
dynamiquement.
void nommer (const Nom &) override
Donne un nom a la sous-zone.
Zone & zone ()
const Zone & zone () const
int add_poly (const int poly)
Ajoute un polyedre a la sous-zone.
int remove_poly (const int poly)
Enleve un polyedre a la sous-zone.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sous_Zone & self_cast (Objet_U &)
static const Sous_Zone & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit la liste des polyedres de la sous-zone
sur un flot de sortie.
Format:
Liste n1 n2 .. Ni.
Entree & readOn (Entree &) override
Lit les specifications d'une sous-zone dans le jeu
de donnee a partir d'un flot d'entree.
Format:
{ Rectangle Origine x0 y0 Cotes lx ly } en dimension 2
{ Boite Origine x0 y0 z0 Cotes lx ly lz} en dimension 3
ou
{ Liste n n1 ni nn }
ou
{ Intervalle n1 n2 }
ou
{ Polynomes {bloc_lecture_poly1 et bloc_lecture_poly_i
et bloc_lecture_poly_n}
}.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect les_polys_
Ref_Zone la_zone_
Nom nom_
Detailed Description
Classe Sous_Zone
Represente une sous zone volumique i.e un sous ensemble
de polyedres d'un objet de type Zone.
Un objet Sous_Zone porte une reference vers la zone qu'il
subdivise.
Definition at line 35 of file Sous_Zone.h.
Constructor & Destructor Documentation
Sous_Zone() [1/2]
Sous_Zone::Sous_Zone ()
Definition at line 24 of file Sous_Zone.cpp.
~Sous_Zone()
Sous_Zone::~Sous_Zone ()
Definition at line 24 of file Sous_Zone.cpp.
Sous_Zone() [2/2]
Sous_Zone::Sous_Zone (const Zone & azone) inline
Constructeur d'une sous-zone a partir d'une zone.
Definition at line 82 of file Sous_Zone.h.
                                             : la_zone_(azone)
{}
Member Function Documentation
add_poly()
int Sous_Zone::add_poly (const int poly)
Ajoute un polyedre a la sous-zone.
Returns
int
Signification:
Contraintes:
Definition at line 1001 of file Sous_Zone.cpp.
{
  assert(0<=poly);
  int nb_poly=les_polys_.size();
  int OK=1;
  for(int i=0; i<nb_poly; i++)
    if(les_polys_(i)==poly)
      OK=0;
  if(OK==1)
    {
      les_polys_.resize(nb_poly+1);
      les_polys_(nb_poly)=poly;
    }
  return 1;
}
References les_polys_, TRUSTVect< _TYPE_ >::resize(), and TRUSTVect< _TYPE_ >::size().
Referenced by Interprete_geometrique_base::mettre_a_jour_sous_zone().
associer_()
int Sous_Zone::associer_ (Objet_U & ob) override virtual
Associe un Objet_U a la sous-zone.
On controle le type de l'objet a associer
dynamiquement.
Returns
int
Signification: renvoie 1 si l'association a reussi
0 sinon.
Contraintes:
Reimplemented from Objet_U.
Definition at line 1091 of file Sous_Zone.cpp.
{
  if( sub_type(Domaine, ob))
    {
// MONOZONE pour le moment
      if(la_zone_.non_nul()) return 1;
      associer_zone(ref_cast(Domaine, ob).zone(0));
      ob.associer_(*this);
      return 1;
    }
  return 0;
}
References Objet_U::associer_(), associer_zone(), la_zone_, O_U_Ptr::non_nul(), ref_cast, sub_type, and zone().
associer_zone()
void Sous_Zone::associer_zone (const Zone & une_zone)
Associe une zone a la sous-zone.
La sous-zone sera une sous-zone de la Zone specifiee.
Definition at line 1068 of file Sous_Zone.cpp.
{
  la_zone_=une_zone;
}
References la_zone_.
Referenced by associer_().
cree_instance()
Objet_U * Sous_Zone::cree_instance () static
Definition at line 24 of file Sous_Zone.cpp.
duplique()
int Sous_Zone::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Sous_Zone.cpp.
get_info()
const Type_info * Sous_Zone::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Sous_Zone.cpp.
info()
const Type_info * Sous_Zone::info () static
Definition at line 24 of file Sous_Zone.cpp.
le_nom()
const Nom & Sous_Zone::le_nom () const inline override virtual
Renvoie le nom de la sous-zone.
Returns
Nom&
Signification: le nom de la sous-zone
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 100 of file Sous_Zone.h.
{
  return nom_;
}
References nom_.
Referenced by Partitionneur_Sous_Zones::construire_partition(), Sous_zone_VF::discretiser(), Postraiter_domaine::ecrire(), DomaineCutter::ecrire_zones(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Champ_Fonc_Tabule_Morceaux::readOn(), and readOn().
lire_motcle_non_standard()
int Sous_Zone::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 978 of file Sous_Zone.cpp.
{
  return 0;
}
Referenced by readOn().
nb_elem_tot()
int Sous_Zone::nb_elem_tot () const inline
Returns the subzone number of elements (real+virtual elements in parallel)
Renvoie le nombre de polyedre de la sous-zone.
Returns
int
Signification: le nombre de polyedre de la sous-zone
Contraintes:
Definition at line 160 of file Sous_Zone.h.
{
  return les_polys_.size();
}
References les_polys_, and TRUSTVect< _TYPE_ >::size().
Referenced by Perte_Charge_PolyMAC::ajouter_blocs(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Refine_Mesh::build_new_sub_zones_descriptions(), TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Union::construire_partition(), Sous_zone_VF::discretiser(), Postraiter_domaine::ecrire(), DomaineCutter::ecrire_zones(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_base::evaluer(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_input_P0::getTemplate(), Porosites::interpreter(), Create_domain_from_sous_zone::interpreter_(), Extraire_domaine::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Sous_zone_dis_base::nb_elem_tot(), Champ_input_P0::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_Uniforme_Morceaux::readOn(), readOn(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), and Champ_input_P0::setValue().
nommer()
void Sous_Zone::nommer (const Nom & nom) override virtual
Donne un nom a la sous-zone.
Reimplemented from Objet_U.
Definition at line 1120 of file Sous_Zone.cpp.
{
  nom_=nom;
}
References nom_.
operator()()
int Sous_Zone::operator() (int i) const inline
Renvoie le numero du i-ieme polyedre de la sous-zone.
Returns
int
Signification: le numero du i-ieme polyedre de la sous-zone
Contraintes:
Definition at line 120 of file Sous_Zone.h.
{
  return les_polys_[i];
}
References les_polys_.
operator[]()
int Sous_Zone::operator[] (int i) const inline
Renvoie le numero du i-ieme polyedre de la sous-zone.
Returns
int
Signification: le numero du i-ieme polyedre de la sous-zone
Contraintes:
Definition at line 140 of file Sous_Zone.h.
{
  return les_polys_[i];
}
References les_polys_.
printOn()
Sortie & Sous_Zone::printOn (Sortie & os) const override protected virtual
Ecrit la liste des polyedres de la sous-zone
sur un flot de sortie.
Format:
Liste n1 n2 .. Ni.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 44 of file Sous_Zone.cpp.
{
  os << "{" << finl;
  os << "Liste" << finl;
  os << les_polys_;
  os << "}" << finl;
  return os;
}
References finl, and les_polys_.
readOn()
Entree & Sous_Zone::readOn (Entree & is) override protected virtual
Lit les specifications d'une sous-zone dans le jeu
de donnee a partir d'un flot d'entree.
Format:
{ Rectangle Origine x0 y0 Cotes lx ly } en dimension 2
{ Boite Origine x0 y0 z0 Cotes lx ly lz} en dimension 3
ou
{ Liste n n1 ni nn }
ou
{ Intervalle n1 n2 }
ou
{ Polynomes {bloc_lecture_poly1 et bloc_lecture_poly_i
et bloc_lecture_poly_n}
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< Internal radius^2
< External radius^2
< Center of gravity of the cell
Reimplemented from Objet_U.
Definition at line 89 of file Sous_Zone.cpp.
{
  Motcles les_mots(12);
  {
    les_mots[0] = "Liste";
    les_mots[1] = "Polynomes";
    les_mots[2] = "Boite";
    les_mots[3] = "Rectangle";
    les_mots[4] = "Intervalle";
    les_mots[5] = "Fichier";
    les_mots[6] = "Plaque";
    les_mots[7] = "Segment";
    les_mots[8] = "Couronne";
    les_mots[9] = "Tube";
    les_mots[10]= "Tube_Hexagonal";
    les_mots[11]= "fonction_sous_zone";
  }
  if (!la_zone_.non_nul())
    {
      Cerr << "You have not associated one of the objects of type Sous_Zone " << finl;
      Cerr << "to the object of type Domain " << finl;
      exit();
    }
  const Zone& lazone=la_zone_.valeur();
  const Domaine& dom=lazone.domaine();
  ArrOfInt les_polys_possibles_;
// GF de prendre nb_elem_tot au lieu de nb_elem permet de ne plus avoir besoin de decouper les sous zones..
  int nb_pol_possible=lazone.nb_elem_tot();
  les_polys_possibles_.resize_array(nb_pol_possible);
  for (int i=0; i<nb_pol_possible; i++)
    les_polys_possibles_[i]=i;
  Motcle motlu;
  is >>  motlu;
  if(motlu != Motcle("{"))
    {
      Cerr << "We expected a { to the reading of the subarea" << finl;
      Cerr << "instead of " << motlu << finl;
      exit();
    }
  is >> motlu;
  if (motlu=="restriction")
    {
      Nom nom_ss_zone;
      is >> nom_ss_zone;
      const Sous_Zone& ssz=ref_cast(Sous_Zone,interprete().objet(nom_ss_zone));
      nb_pol_possible=ssz.nb_elem_tot();
      les_polys_possibles_.resize_array(nb_pol_possible);
      for (int i=0; i<nb_pol_possible; i++)
        les_polys_possibles_[i]=ssz(i);
      is>>motlu;
    }
  int rang = les_mots.search(motlu);
  if (rang==-1)
    {
      int ok=lire_motcle_non_standard(motlu,is);
      if (!ok)
        {
          Cerr << motlu << " is not understood " << finl;
          Cerr << "The understood keywords are " << les_mots;
          exit();
        }
    }
  if ((rang == 0) && (Process::nproc()>1))
    {
      Cerr << "When the subareas are defined as lists of elements" << finl;
      Cerr << "it is necessary to split them for parallel computing." << finl;
      exit();
    }
  switch(rang)
    {
    case 0 :
      is >> les_polys_;
      break;
    case 1 :
      {
        Cerr<<"Sous_Zone::readOn : Reading of the polynomials"<<finl;
        LIST(Polynome) les_polynomes;
        is >> motlu;
        if(motlu!=Motcle("{"))
          {
            Cerr << "We expected a { " << finl;
            exit();
          }
        while (1)
          {
            Polynome un_poly;
            is >> un_poly;
            les_polynomes.add(un_poly);
            is >> motlu;
            Motcle Et("et");
            if(motlu==Motcle("}")) break;
            if(motlu!=Motcle("et"))
              {
                Cerr << "We expected " << Et << " or } " << finl;
                exit();
              }
          }
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          DoubleVect x(dimension);
          int compteur=0;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              x=0;
              for(int le_som=0; le_som<nbsom; le_som++)
                {
                  for(int k=0; k<dimension; k++)
                    x(k)+=dom.coord(lazone.sommet_elem(le_poly,le_som),k);
                }
              x/=((double)(nbsom));
              LIST_CURSEUR(Polynome) curseur=les_polynomes;
              int test = 1;
              while(curseur)
                {
                  if (dimension==2)
                    {
                      if (curseur.valeur()(x(0), x(1)) <0) test = -1;
                    }
                  if (dimension==3)
                    {
                      if (curseur.valeur()(x(0), x(1),x(2)) <0) test = -1;
                    }
                  ++curseur;
                }
              if(test > 0)
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 2 :
      {
// Boite
        if(dimension!=3)
          {
// Une Boite est un volume
            Cerr << "In 2 dimensions, you must use \"Rectangle\" " << finl;
            exit();
          }
        is >> motlu;
        if (motlu != Motcle("Origine"))
          {
            Cerr << "We expected the keyword \"Origine\"" << finl;
            exit();
          }
        double deux_pi=M_PI*2.0 ;
        double ox, oy, oz;
        is >> ox >> oy >> oz ;
        is >> motlu;
        if (motlu != Motcle("Cotes"))
          {
            Cerr << "We expected the keyword \"Cotes\"" << finl;
            exit();
          }
        double lx, ly, lz;
        is >> lx >> ly >>lz;
        lx+= ox;
        ly+=oy;
        lz+=oz;
        if(axi)
          {
            oy*=deux_pi;
            ly*=deux_pi;
          }
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          double x, y, z;
          int compteur=0;
// int nb_poly=la_zone.nb_elem();
          Cerr << "Construction of the subarea " << le_nom()<< finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              x=y=z=0;
              int s, nb_som_poly = 0;
              for(int le_som = 0; le_som < nbsom && ((s = lazone.sommet_elem(le_poly,le_som)) >= 0); le_som++)
                {
                  x+=dom.coord(s, 0);
                  y+=dom.coord(s, 1);
                  z+=dom.coord(s, 2);
                  nb_som_poly++;
                }
              x/=((double)(nb_som_poly));
              y/=((double)(nb_som_poly));
              z/=((double)(nb_som_poly));
              if ( sup_strict(x,ox)
                   && sup_strict(lx,x)
                   && sup_strict(y,oy)
                   && sup_strict(ly,y)
                   && sup_strict(z,oz)
                   && sup_strict(lz,z) )
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 3 :
      {
// Rectangle
        if(dimension!=2)
          {
// Un Rectangle est une surface
            Cerr << "In 3 dimensions, you must use \"Boite\" " << finl;
            exit();
          }
        is >> motlu;
        if (motlu != Motcle("Origine"))
          {
            Cerr << "We expected the keyword \"Origine\"" << finl;
            exit();
          }
        double ox, oy;
        is >> ox >> oy ;
        is >> motlu;
        if (motlu != Motcle("Cotes"))
          {
            Cerr << "We expected the keyword \"Cotes\"" << finl;
            exit();
          }
        double lx, ly;
        is >> lx >> ly ;
        lx+= ox;
        ly+=oy;
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          double x, y;
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom() << finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              x=y=0;
              for(int le_som=0; le_som<nbsom; le_som++)
                {
                  x+=dom.coord(lazone.sommet_elem(le_poly,le_som),0);
                  y+=dom.coord(lazone.sommet_elem(le_poly,le_som),1);
                }
              x/=((double)(nbsom));
              y/=((double)(nbsom));
              if ( sup_strict(x,ox)
                   && sup_strict(lx,x)
                   && sup_strict(y,oy)
                   && sup_strict(ly,y) )
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 4 :
      {
// Intervalle (only be used in sequential calculation)
        if (Process::nproc()>1)
          {
            Cerr << "You can't use Intervalle option for parallel calculation." << finl;
            exit();
          }
        int prems, nombre;
        is >> prems >> nombre;
        les_polys_.resize(nombre);
        for(int i=0; i<nombre; i++)
          les_polys_[i]=prems+i;
        break;
      }
    case 5 :
      {
// Lecture de la sous-zone dans un fichier ascii.
// Le fichier contient, pour chaque processeur dans l'ordre croissant,
// un IntVect contenant les indices dans la zone(0) des elements reels
// qui constituent la sous-zone.
        Nom nomfic;
        is >> nomfic;
        if(je_suis_maitre())
          {
            IntVect tab;
            EFichier fic;
            Cerr << "Reading of a subarea in the file " << nomfic << finl;
            if (!fic.ouvrir(nomfic))
              {
                Cerr << " Error while opening file." << finl;
                exit();
              }
            fic >> les_polys_;
            for(int p=1; p<nproc(); p++)
              {
                fic >> tab;
                envoyer(tab,0,p,p);
              }
          }
        else
          {
            recevoir(les_polys_,0,me(),me());
          }
// Ajout a la liste "les_polys_" des indices des elements virtuels
// de la sous-zone.
// On cree un tableau distribue de marqueurs des elements de la sous-zone
        const int nb_elem = lazone.nb_elem();
        IntVect marqueurs;
        dom.creer_tableau_elements(marqueurs);
        const int nb_polys_reels = les_polys_.size();
        for (int i = 0; i < nb_polys_reels; i++)
          {
            const int elem = les_polys_[i];
            marqueurs[elem] = 1;
          }
        marqueurs.echange_espace_virtuel();
// Compter les elements virtuels dans la sous-zone:
        const int zone_nb_elem_tot = lazone.nb_elem_tot();
        int nb_polys = nb_polys_reels;
        for (int i = nb_elem; i < zone_nb_elem_tot; i++)
          nb_polys += marqueurs[i];
// Ajouter les indices des elements virtuels a "les_polys_"
        les_polys_.resize(nb_polys);
        nb_polys = nb_polys_reels;
        for (int i = nb_elem; i < zone_nb_elem_tot; i++)
          if (marqueurs[i])
            les_polys_[nb_polys++] = i;
        break;
      }
    case 6 :
      {
// Plaque
        if(dimension!=3)
          {
            Cerr << "In 2 dimensions, you must use something else like a segment."<< finl;
            exit();
          }
        is >> motlu;
        if (motlu != Motcle("Origine"))
          {
            Cerr << "We expected the keyword \"Origine\"" << finl;
            exit();
          }
        double deux_pi=M_PI*2.0 ;
        double ox, oy, oz;
        is >> ox >> oy >> oz ;
        is >> motlu;
        if (motlu != Motcle("Cotes"))
          {
            Cerr << "We expected the keyword \"Cotes\"" << finl;
            exit();
          }
        double lx, ly, lz;
        is >> lx >> ly >>lz;
        if ((lx!=0)&&(ly!=0)&&(lz!=0))
          {
            Cerr << "We expected at least one quotation to zero" << finl;
            exit();
          }
        lx+=ox;
        ly+=oy;
        lz+=oz;
        if(axi)
          {
            oy*=deux_pi;
            ly*=deux_pi;
          }
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          double x, y, z;
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom() << finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              int le_som, s, nb_som_poly = 0;
              x=y=z=0;
              for(le_som=0; le_som<nbsom && ((s = lazone.sommet_elem(le_poly,le_som)) >= 0); le_som++)
                {
                  x+=dom.coord(s, 0);
                  y+=dom.coord(s, 1);
                  z+=dom.coord(s, 2);
                  nb_som_poly++;
                }
              le_som=0;
              double xmin,xmax,ymin,ymax,zmin,zmax;
              xmin=dom.coord(lazone.sommet_elem(le_poly,le_som),0);
              ymin=dom.coord(lazone.sommet_elem(le_poly,le_som),1);
              zmin=dom.coord(lazone.sommet_elem(le_poly,le_som),2);
              xmax=xmin;
              ymax=ymin;
              zmax=zmin;
              for(le_som=1; le_som<nbsom && ((s = lazone.sommet_elem(le_poly,le_som)) >= 0); le_som++)
                {
                  xmin=std::min(xmin,dom.coord(s, 0));
                  ymin=std::min(ymin,dom.coord(s, 1));
                  zmin=std::min(zmin,dom.coord(s, 2));
                  xmax=std::max(xmax,dom.coord(s, 0));
                  ymax=std::max(ymax,dom.coord(s, 1));
                  zmax=std::max(zmax,dom.coord(s, 2));
                }
              x/=((double)(nb_som_poly));
              y/=((double)(nb_som_poly));
              z/=((double)(nb_som_poly));
              if (
                (    sup_strict(x,ox)    && sup_strict(lx,x)
                     && sup_strict(y,oy)    && sup_strict(ly,y)
                     && sup_strict(oz,zmin) && inf_ou_egal(oz,zmax) )
                || ( sup_strict(x,ox)    && sup_strict(lx,x)
                     && sup_strict(z,oz)    && sup_strict(lz,z)
                     && sup_strict(oy,ymin) && inf_ou_egal(oy,ymax) )
                || ( sup_strict(y,oy)    && sup_strict(ly,y)
                     && sup_strict(z,oz)    && sup_strict(lz,z)
                     && sup_strict(ox,xmin) && inf_ou_egal(ox,xmax) )
              )
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 7:
      {
// Segment
        if(dimension!=2)
          {
            Cerr << "In 3 dimensions, you must use something else like a plaque."<< finl;
            exit();
          }
        is >> motlu;
        if (motlu != Motcle("Origine"))
          {
            Cerr << "We expected the keyword \"Origine\"" << finl;
            exit();
          }
// double deux_pi=M_PI*2.0 ;
        double ox, oy;
        is >> ox >> oy  ;
        is >> motlu;
        if (motlu != Motcle("Cotes"))
          {
            Cerr << "We expected the keyword \"Cotes\"" << finl;
            exit();
          }
        double lx, ly;
        is >> lx >> ly ;
        if ((lx!=0)&&(ly!=0))
          {
            Cerr << "We expected at least one quotation to zero" << finl;
            exit();
          }
        lx+= ox;
        ly+=oy;
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          double x, y;
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom() << finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              int le_som;
              x=y=0;
              for(le_som=0; le_som<nbsom; le_som++)
                {
                  x+=dom.coord(lazone.sommet_elem(le_poly,le_som),0);
                  y+=dom.coord(lazone.sommet_elem(le_poly,le_som),1);
                }
              le_som=0;
              double xmin,xmax,ymin,ymax;
              xmin=dom.coord(lazone.sommet_elem(le_poly,le_som),0);
              ymin=dom.coord(lazone.sommet_elem(le_poly,le_som),1);
              xmax=xmin;
              ymax=ymin;//zmax=zmin;
              for(le_som=1; le_som<nbsom; le_som++)
                {
                  xmin=std::min(xmin,dom.coord(lazone.sommet_elem(le_poly,le_som),0));
                  ymin=std::min(ymin,dom.coord(lazone.sommet_elem(le_poly,le_som),1));
                  xmax=std::max(xmax,dom.coord(lazone.sommet_elem(le_poly,le_som),0));
                  ymax=std::max(ymax,dom.coord(lazone.sommet_elem(le_poly,le_som),1));
                }
              x/=((double)(nbsom));
              y/=((double)(nbsom));
              if (
                ( sup_strict(x,ox)    && sup_strict(lx,x)
                  && sup_strict(oy,ymin) && inf_ou_egal(oy,ymax) )
                || ( sup_strict(y,oy)    && sup_strict(ly,y)
                     && sup_strict(ox,xmin) && inf_ou_egal(ox,xmax) )
              )
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 8 :
      {
// Couronne
        if(dimension!=2)
          {
// Une Couronne en 2D seulement !
            Cerr << "A crown is only in 2D : in 3 dimensions it is a tube \"Tube\" "<< finl;
            exit();
          }
        is >> motlu;
        if(motlu!=Motcle("Origine"))
          {
            Cerr << "We expected the keyword \"ORIGINE\" " << finl;
            exit();
          }
        double xo,yo;
        is >> xo >> yo ;
        is >> motlu;
        if(motlu!=Motcle("RI"))
          {
            Cerr << "We expected the internal radius \"RI\" " << finl;
            exit();
          }
        double ri,re;
        is >> ri;
        is >> motlu;
        if(motlu!=Motcle("RE"))
          {
            Cerr << "We expected the external radius \"RE\" " << finl;
            exit();
          }
        is >> re;
        {
          double ri2=ri*ri; //!< Internal radius^2
          double re2=re*re; //!< External radius^2
          const Zone& la_zone=la_zone_.valeur();
          int nbsom=la_zone.nb_som_elem();
          DoubleVect x(dimension);
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom() << finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              int le_poly=les_polys_possibles_[n_pol];
              x=0;
              for(int som=0; som<nbsom; som++)
                {
                  for(int k=0; k<dimension; k++)
                    x(k)+=dom.coord(lazone.sommet_elem(le_poly,som),k);
                }
              x/=((double)(nbsom)); //!< Center of gravity of the cell
              if ( sup_strict((x(0)-xo)*(x(0)-xo)+(x(1)-yo)*(x(1)-yo),ri2) && sup_strict(re2,(x(0)-xo)*(x(0)-xo)+ (x(1)-yo)*(x(1)-yo)) )
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 9 :
      {
// Tube
        if(dimension!=3)
          {
// Un tube en 3D seulement !
            Cerr << "A tube is only in 3D : in 2 dimensions it is a crown \"Couronne\" "<< finl;
            exit();
          }
        is >> motlu;
        if(motlu!=Motcle("Origine"))
          {
            Cerr << "We expected the keyword \"ORIGINE\" " << finl;
            exit();
          }
        double xo,yo,zo;
        is >> xo >> yo >> zo;
        is >> motlu;
        if(motlu!=Motcle("DIR"))
          {
            Cerr << "We expected the tube direction, keyword \"DIR\" " << finl;
            exit();
          }
        Motcles coords(3);
        {
          coords[0] = "X";
          coords[1] = "Y";
          coords[2] = "Z";
        }
        Nom coord;
        is >> coord;
        motlu=coord;
        int idir = coords.search(motlu);
        int dir[3];
        dir[0]=dir[1]=dir[2]=0;
        double h0=0;
        switch(idir)
          {
          case 0:
            dir[0]=0;
            dir[1]=dir[2]=1;
            h0=xo;
            break;
          case 1:
            dir[1]=0;
            dir[0]=dir[2]=1;
            h0=yo;
            break;
          case 2:
            dir[2]=0;
            dir[1]=dir[0]=1;
            h0=zo;
            break;
          default:
            h0=-1;
            Cerr << "DIR is equal to X for a tube parallel to OX ; Y for a tube parallel to OY and Z for a tube parallel to OZ" << finl;
            Cerr << "Currently, DIR is equal to " << coord << finl;
            exit();
          }
        is >> motlu;
        if(motlu!=Motcle("RI"))
          {
            Cerr << "We expected the internal radius, keyword \"RI\" " << finl;
            exit();
          }
        double ri,re,h;
        is >> ri;
        is >> motlu;
        if(motlu!=Motcle("RE"))
          {
            Cerr << "We expected the external radius, keyword \"RE\" " << finl;
            exit();
          }
        is >> re;
        is >> motlu;
        if(motlu!=Motcle("Hauteur"))
          {
            Cerr << "We expected the height of tube, keyword \"Hauteur\" " << finl;
            exit();
          }
        is >> h;
        h+=h0;
        {
          double ri2 = ri*ri, re2=re*re;
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          DoubleVect x(dimension);
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom() << finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              x=0;
              for(int le_som=0; le_som<nbsom; le_som++)
                {
                  for(int k=0; k<dimension; k++)
                    x(k)+=dom.coord(lazone.sommet_elem(le_poly,le_som),k);
                }
              x/=((double)(nbsom));
              double tmp = dir[0]*(x(0)-xo)*(x(0)-xo)+ dir[1]*(x(1)-yo)*(x(1)-yo) + dir[2]*(x(2)-zo)*(x(2)-zo);
              if ( sup_ou_egal(tmp,ri2) && inf_ou_egal(tmp,re2) && inf_ou_egal(x(idir),h) && sup_ou_egal(x(idir),h0) )
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 10 :
      {
        if(dimension!=3)
          {
// Un tube en 3D seulement !
            Cerr << "An hexagonal tube \"Tube_hexagonal\" is only in 3D "<< finl;
            exit();
          }
// PQ : 17/09/08 : on suppose le tube hexagonal centre sur l'origine, porte par l'axe z
// et pour lequel l'entreplat est entre y=-ep/2 et y=+ep/2
        double ep;
        bool in=1;
        is >> motlu;
        if(motlu!=Motcle("ENTREPLAT"))
          {
            Cerr << "We expected the entreplat of the tube, keyword \"ENTREPLAT\"" << finl;
            exit();
          }
        is >> ep;
        is >> motlu;
        if(motlu==Motcle("IN"))       in=1;
        else if(motlu==Motcle("OUT")) in=0;
        else
          {
            Cerr << "We expected the keyword \"IN\" or \"OUT\" " << finl;
            exit();
          }
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          DoubleVect x(dimension);
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom()<< finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              x=0;
              for(int le_som=0; le_som<nbsom; le_som++)
                {
                  for(int k=0; k<dimension; k++)
                    x(k)+=dom.coord(lazone.sommet_elem(le_poly,le_som),k);
                }
              x/=((double)(nbsom));
              if ( sup_ou_egal(x(1),-ep/2.) && sup_ou_egal(x(1),-ep-x(0)*sqrt(3.)) && sup_ou_egal(x(1),-ep+x(0)*sqrt(3.))
                   &&  inf_ou_egal(x(1), ep/2.) && inf_ou_egal(x(1), ep-x(0)*sqrt(3.)) && inf_ou_egal(x(1), ep+x(0)*sqrt(3.)) )
                {
                  if(in==1)
                    {
                      les_polys_(compteur)=le_poly;
                      compteur++;
                    }
                }
              else
                {
                  if(in==0)
                    {
                      les_polys_(compteur)=le_poly;
                      compteur++;
                    }
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case 11 :
      {
        Parser_U F;
        F.setNbVar(dimension);
        Nom fct;
        is>> fct;
        F.setString(fct);
        F.addVar("x");
        F.addVar("y");
        if (dimension==3)
          F.addVar("z");
        F.parseString();
        {
          const Zone& la_zone=la_zone_.valeur();
          int le_poly, nbsom=la_zone.nb_som_elem();
          DoubleVect x(dimension);
          int compteur=0;
          Cerr << "Construction of the subarea " << le_nom()<< finl;
          les_polys_.resize(nb_pol_possible);
          for (int n_pol=0; n_pol<nb_pol_possible; n_pol++)
            {
              le_poly=les_polys_possibles_[n_pol];
              x=0;
              int nbsom_loc = 0;
              for(int le_som=0; le_som<nbsom; le_som++)
                if (lazone.sommet_elem(le_poly,le_som) >= 0)
                  {
                    for(int k=0; k<dimension; k++)
                      x(k)+=dom.coord(lazone.sommet_elem(le_poly,le_som),k);
                    nbsom_loc++;
                  }
              x *= 1. / nbsom_loc;
              F.setVar(0,x[0]);
              F.setVar(1,x[1]);
              if (dimension==3)
                F.setVar(2,x[2]);
              double test=F.eval();
// attention le test absolu est voulu
// si on fait une fonction qui vaut 0 ou 1 ....
              if (test>0)
                {
                  les_polys_(compteur)=le_poly;
                  compteur++;
                }
            }
          les_polys_.resize(compteur);
          Cerr << "Construction of the subarea OK" << finl;
        }
        break;
      }
    case -1:
// traite avant
      break;
    default :
      {
        Cerr << "TRUST error" << finl;
        exit();
      }
      break;
    }
  is >> motlu;
  if (motlu=="union")
    {
      Nom nom_ss_zone;
      is >> nom_ss_zone;
      const Sous_Zone& ssz=ref_cast(Sous_Zone,interprete().objet(nom_ss_zone));
      nb_pol_possible=ssz.nb_elem_tot();
      les_polys_possibles_.resize_array(nb_pol_possible);
      int compt=0;
// on cherche dans ces polys ceux que l'on n a pas
      for (int i=0; i<nb_pol_possible; i++)
        {
          int poly_i=ssz(i);
          int trouve=0;
          for (int j=0; j<nb_elem_tot(); j++)
            if ((les_polys_(j))==poly_i)
              {
                trouve=1;
                break;
              }
          if (!trouve)
            les_polys_possibles_[compt++]=poly_i;
        }
// on rajoute ces polys a la fin
      int old_size=les_polys_.size();
      les_polys_.resize(old_size+compt);
      Journal()<<les_polys_<<finl;
      for (int i=0; i<compt; i++)
        les_polys_(old_size+i)=les_polys_possibles_[i];
      is >>motlu;
    }
  if(motlu != Motcle("}"))
    {
      Cerr << "We expected a } to the reading of the subarea" << finl;
      Cerr << "instead of " << motlu << finl;
      exit();
    }
  return is;
}
References Parser_U::addVar(), Objet_U::axi, Cerr, compteur, Domaine::coord(), Domaine::creer_tableau_elements(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), envoyer(), Parser_U::eval(), Process::exit(), finl, inf_ou_egal(), Objet_U::interprete(), Process::je_suis_maitre(), Process::Journal(), la_zone_, le_nom(), les_polys_, lire_motcle_non_standard(), LIST, LIST_CURSEUR, M_PI, Process::me(), Zone::nb_elem(), nb_elem_tot(), Zone::nb_elem_tot(), Zone::nb_som_elem(), O_U_Ptr::non_nul(), Process::nproc(), Entree_Fichier_base::ouvrir(), Parser_U::parseString(), recevoir(), ref_cast, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), TRUSTVect< _TYPE_ >::size(), Zone::sommet_elem(), sup_ou_egal(), sup_strict(), test(), and Ref_Zone::valeur().
remove_poly()
int Sous_Zone::remove_poly (const int poly)
Enleve un polyedre a la sous-zone.
Returns
int
Signification:
Contraintes:
Definition at line 1032 of file Sous_Zone.cpp.
{
  assert(0<=poly);
  assert(poly<=la_zone_.valeur().nb_elem());
  int nb_poly=les_polys_.size();
  IntVect les_polys_tmp;
  les_polys_tmp.resize(la_zone_.valeur().nb_elem());
  int compteur=0;
  for(int i=0; i<nb_poly; i++)
    if(les_polys_(i)!=poly)
      {
        les_polys_tmp(compteur)=les_polys_(i);
        compteur++;
      }
  les_polys_tmp.resize(compteur);
  les_polys_.resize(compteur);
  les_polys_=les_polys_tmp;
  return 1;
}
References compteur, la_zone_, les_polys_, Zone::nb_elem(), TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), and Ref_Zone::valeur().
self_cast() [1/2]
const Sous_Zone & Sous_Zone::self_cast (const Objet_U & r) static
Definition at line 24 of file Sous_Zone.cpp.
self_cast() [2/2]
Sous_Zone & Sous_Zone::self_cast (Objet_U & r) static
Definition at line 24 of file Sous_Zone.cpp.
taille_memoire()
unsigned Sous_Zone::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Sous_Zone.cpp.
zone() [1/2]
Zone & Sous_Zone::zone () inline
Definition at line 50 of file Sous_Zone.h.
  {
    return la_zone_.valeur();
  }
References la_zone_, and Ref_Zone::valeur().
Referenced by associer_(), and Domaine_dis::discretiser().
zone() [2/2]
const Zone & Sous_Zone::zone () const inline
Definition at line 54 of file Sous_Zone.h.
  {
    return la_zone_.valeur();
  }
References la_zone_, and Ref_Zone::valeur().
Member Data Documentation
info_obj
const Type_info Sous_Zone::info_obj static
Definition at line 37 of file Sous_Zone.h.
la_zone_
Ref_Zone Sous_Zone::la_zone_ protected
Definition at line 64 of file Sous_Zone.h.
Referenced by associer_(), associer_zone(), readOn(), remove_poly(), and zone().
les_polys_
IntVect Sous_Zone::les_polys_ protected
Definition at line 63 of file Sous_Zone.h.
Referenced by add_poly(), nb_elem_tot(), operator()(), operator[](), printOn(), readOn(), and remove_poly().
nom_
Nom Sous_Zone::nom_ protected
Definition at line 65 of file Sous_Zone.h.
Referenced by le_nom(), and nommer().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Sous_Zone.h
src/Kernel/Geometrie/Sous_Zone.cpp