TRUST: CSR_Builder Class Reference
CSR_Builder Class Reference
This class is a helper to build CSR stored matrices.
#include <CSR_Builder.h>
Public Member Functions
CSR_Builder ()
initialize (int nb_lines)
void add_coeff (int line, int column, double coeff)
build_matrix (Matrice_Bloc &)
Protected Attributes
int nb_lines_
ArrOfInt list_head_
ArrOfInt list_tail_
ArrOfInt list_data_
ArrOfDouble coeff_data_
Detailed Description
This class is a helper to build CSR stored matrices.
Definition at line 20 of file CSR_Builder.h.
Constructor & Destructor Documentation
CSR_Builder()
CSR_Builder::CSR_Builder ()
Member Function Documentation
add_coeff()
void CSR_Builder::add_coeff (int line, int column, double coeff) inline
< mixing calls with and without "coeff" is forbidden
< new end of list
Definition at line 47 of file CSR_Builder.h.
{
  assert(line >= 0 && line < nb_lines_);
// We put the new coefficient here:
  const int n = coeff_data_.size_array();
  assert(list_data_.size_array() == n*2); //!< mixing calls with and without "coeff" is forbidden
  list_data_.resize_array(n*2+2);
  list_data_[n*2] = column;
  list_data_[n*2+1] = -1; //!< new end of list
  coeff_data_.append_array(coeff);
  const int tail = list_tail_[line];
  if (tail < 0)
    {
// this line is empty, initialize list_head_
      list_head_[line] = n;
    }
  else
    {
// update the last next_index of the line:
      list_data_[2*tail+1] = n;
    }
  list_tail_[line] = n;
}
References TRUSTArray< _TYPE_ >::append_array(), coeff, coeff_data_, list_data_, list_head_, list_tail_, nb_lines_, TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
build_matrix()
CSR_Builder::build_matrix (Matrice_Bloc &)
initialize()
CSR_Builder::initialize (int nb_lines)
Member Data Documentation
coeff_data_
ArrOfDouble CSR_Builder::coeff_data_ protected
Definition at line 44 of file CSR_Builder.h.
Referenced by add_coeff().
list_data_
ArrOfInt CSR_Builder::list_data_ protected
Definition at line 43 of file CSR_Builder.h.
Referenced by add_coeff().
list_head_
ArrOfInt CSR_Builder::list_head_ protected
Definition at line 39 of file CSR_Builder.h.
Referenced by add_coeff().
list_tail_
ArrOfInt CSR_Builder::list_tail_ protected
Definition at line 42 of file CSR_Builder.h.
Referenced by add_coeff().
nb_lines_
int CSR_Builder::nb_lines_ protected
Definition at line 28 of file CSR_Builder.h.
Referenced by add_coeff().
The documentation for this class was generated from the following file:
src/Kernel/Math/Matrices/CSR_Builder.h