TRUST: T_It_Sou_VDF_Elem< _TYPE_ > Class Template Reference
T_It_Sou_VDF_Elem< _TYPE_ > Class Template Reference
#include <T_It_Sou_VDF_Elem.h>
Public Member Functions
Evaluateur_Source_VDF & evaluateur ()
DoubleTab & calculer (DoubleTab &) const
DoubleTab & ajouter (DoubleTab &) const
void completer_ ()
Protected Member Functions
DoubleTab & ajouter_ (DoubleTab &) const
DoubleTab & ajouter_ (DoubleTab &, int) const
Protected Attributes
_TYPE_ evaluateur_source_elem
int nb_elem_
Private Member Functions
int duplique () const
unsigned taille_memoire () const
Detailed Description
template<class _TYPE_>
class T_It_Sou_VDF_Elem< _TYPE_ >
Definition at line 37 of file T_It_Sou_VDF_Elem.h.
Member Function Documentation
template<class _TYPE_ > DoubleTab & T_It_Sou_VDF_Elem< _TYPE_ >::ajouter (DoubleTab & resu) const [virtual]
Implements Iterateur_Source_VDF_base.
Definition at line 97 of file T_It_Sou_VDF_Elem.h.
References DoubleVect::line_size(), and DoubleTab::nb_dim().
{
  ((_TYPE_&) (evaluateur_source_elem)).mettre_a_jour( );
  assert(resu.nb_dim() < 3);
  const int ncomp = resu.line_size();
  DoubleVect& bilan = so_base->bilan();
  bilan=0;
  if( ncomp == 1)
    ajouter_(resu) ;
  else
    ajouter_(resu, ncomp) ;
  return resu;
}
template<class _TYPE_ > DoubleTab & T_It_Sou_VDF_Elem< _TYPE_ >::ajouter_ (DoubleTab & resu, int ncomp) const [protected]
Definition at line 121 of file T_It_Sou_VDF_Elem.h.
{
  DoubleVect source(ncomp);
  DoubleVect& bilan = so_base->bilan();
  for (int num_elem=0; num_elem<nb_elem_; num_elem++)
    {
      evaluateur_source_elem.calculer_terme_source(num_elem, source);
      for (int k=0; k<ncomp; k++)
        {
          resu(num_elem,k) += source(k);
          bilan(k) += source(k);
        }
    }
  return resu;
}
template<class _TYPE_ > DoubleTab & T_It_Sou_VDF_Elem< _TYPE_ >::ajouter_ (DoubleTab & resu) const [protected]
Definition at line 110 of file T_It_Sou_VDF_Elem.h.
{
  DoubleVect& bilan = so_base->bilan();
  for (int num_elem=0; num_elem<nb_elem_; num_elem++)
    {
      double source = evaluateur_source_elem.calculer_terme_source(num_elem);
      resu[num_elem] += source;
      bilan(0) += source;
    }
  return resu;
}
template<class _TYPE_ > DoubleTab & T_It_Sou_VDF_Elem< _TYPE_ >::calculer (DoubleTab & resu) const [virtual]
Implements Iterateur_Source_VDF_base.
Definition at line 136 of file T_It_Sou_VDF_Elem.h.
References ajouter().
{
  resu=0;
  return ajouter(resu);
}
template<class _TYPE_ > void T_It_Sou_VDF_Elem< _TYPE_ >::completer_ () [inline, virtual]
Implements Iterateur_Source_VDF_base.
Definition at line 74 of file T_It_Sou_VDF_Elem.h.
{
  nb_elem_=la_zone->nb_elem();
}
template<class _TYPE_ > int T_It_Sou_VDF_Elem< _TYPE_ >::duplique () const [inline, private, virtual]
Implements Iterateur_Source_VDF_base.
Definition at line 40 of file T_It_Sou_VDF_Elem.h.
References Cerr, Process::exit(), finl, and Objet_U::numero().
  {
    T_It_Sou_VDF_Elem* xxx = new  T_It_Sou_VDF_Elem(*this);
    if(!xxx)
      {
        Cerr << "Not enough memory " << finl;
        exit();
      }
    return xxx->numero();
  };
template<class _TYPE_ > Evaluateur_Source_VDF & T_It_Sou_VDF_Elem< _TYPE_ >::evaluateur () [inline, virtual]
Implements Iterateur_Source_VDF_base.
Definition at line 78 of file T_It_Sou_VDF_Elem.h.
{
  Evaluateur_Source_VDF& eval = (Evaluateur_Source_VDF&) evaluateur_source_elem;
  return eval;
}
template<class _TYPE_ > unsigned T_It_Sou_VDF_Elem< _TYPE_ >::taille_memoire () const [inline, private, virtual]
Implements Objet_U.
Definition at line 50 of file T_It_Sou_VDF_Elem.h.
  {
    throw;
  };
Member Data Documentation
template<class _TYPE_ > _TYPE_ T_It_Sou_VDF_Elem< _TYPE_ >::evaluateur_source_elem [protected]
Definition at line 64 of file T_It_Sou_VDF_Elem.h.
template<class _TYPE_ > int T_It_Sou_VDF_Elem< _TYPE_ >::nb_elem_ [protected]
Definition at line 69 of file T_It_Sou_VDF_Elem.h.
The documentation for this class was generated from the following file:
src/VDF/Sources/Iterateurs/T_It_Sou_VDF_Elem.h