TRUST: Op_Diff_P1NC_barprim Class Reference
Op_Diff_P1NC_barprim Class Reference
class Op_Diff_VEF_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
#include <Op_Diff_P1NC_barprim.h>
Public Member Functions
Op_Diff_P1NC_barprim ()
~Op_Diff_P1NC_barprim ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
void associer_diffusivite (const Champ_base &)
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
double calculer_dt_stab () const
Calcul dt_stab.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_P1NC_barprim & self_cast (Objet_U &)
static const Op_Diff_P1NC_barprim & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
void calculer_divergence (const DoubleTab &, const DoubleVect &, DoubleTab &) const
Protected Attributes
Ref_Zone_VEF_PreP1b la_zone_vef
Ref_Zone_Cl_VEFP1B la_zcl_vef
Ref_Champ_Uniforme diffusivite_
Detailed Description
class Op_Diff_VEF_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
Definition at line 49 of file Op_Diff_P1NC_barprim.h.
Constructor & Destructor Documentation
Op_Diff_P1NC_barprim::Op_Diff_P1NC_barprim ()
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
Op_Diff_P1NC_barprim::~Op_Diff_P1NC_barprim ()
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
Member Function Documentation
DoubleTab & Op_Diff_P1NC_barprim::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const [virtual]
Reimplemented from Operateur_base.
Definition at line 187 of file Op_Diff_P1NC_barprim.cpp.
References calculer().
{
  DoubleTab tmp(resu);
  calculer(inconnue,tmp);
  resu += tmp;
  return resu;
}
void Op_Diff_P1NC_barprim::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_diffuse) [virtual]
Implements Operateur_base.
Definition at line 64 of file Op_Diff_P1NC_barprim.cpp.
References la_zcl_vef, la_zone_vef, REF, ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VEF_PreP1b& zvef = ref_cast(Zone_VEF_PreP1b,zone_dis.valeur());
  const Zone_Cl_VEFP1B& zclvef = ref_cast(Zone_Cl_VEFP1B,zone_cl_dis.valeur());
  if (sub_type(Champ_P1NC,ch_diffuse.valeur()))
    {
      const Champ_P1NC& inco = ref_cast(Champ_P1NC,ch_diffuse.valeur());
      REF(Champ_P1NC) inconnue;
      inconnue = inco;
    }
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
}
void Op_Diff_P1NC_barprim::associer_diffusivite (const Champ_base & diffu) [virtual]
Implements Operateur_Diff_base.
Definition at line 82 of file Op_Diff_P1NC_barprim.cpp.
References diffusivite_, and ref_cast.
{
  diffusivite_ = ref_cast(Champ_Uniforme, diffu);
}
DoubleTab & Op_Diff_P1NC_barprim::calculer (const DoubleTab & inconnue, DoubleTab & resu) const [virtual]
Reimplemented from Operateur_base.
Definition at line 200 of file Op_Diff_P1NC_barprim.cpp.
References calculer_divergence(), calculer_gradientP1NC(), diffusivite(), DoubleVect::echange_espace_virtuel(), MorEqn::equation(), Champ_P1NC::filtrer_L2(), Champ_P1NC::filtrer_resu(), la_zcl_vef, la_zone_vef, Op_VEF_Face::modifier_flux(), ref_cast, DoubleVect::resize(), Ref_Zone_Cl_VEFP1B::valeur(), Ref_Zone_VEF_PreP1b::valeur(), valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by ajouter().
{
// Cerr << "Op_Diff_P1NC_barprim::calculer" << finl;
  int nb_elem = la_zone_vef->zone().nb_elem_tot();
// const DoubleTab& xp=la_zone_vef->xp();
  DoubleVect nu;
  {
    nu.resize(nb_elem);
    nu=(diffusivite().valeurs())(0,0);
  }
  resu=0;
  const Champ_P1NC& ch=ref_cast(Champ_P1NC,(equation().inconnue().valeur()));
  DoubleTab gradient_bar;
  DoubleTab ubar(ch.valeurs());
  ch.filtrer_L2(ubar);
  calculer_gradientP1NC(ubar, la_zone_vef.valeur(),la_zcl_vef.valeur() ,
                        gradient_bar);
  DoubleTab resu_bar(resu);
  calculer_divergence(gradient_bar, nu, resu_bar);
  ch.filtrer_resu(resu_bar);
  resu+=resu_bar;
  resu.echange_espace_virtuel();
  modifier_flux(*this);
  return resu;
}
void Op_Diff_P1NC_barprim::calculer_divergence (const DoubleTab & grad, const DoubleVect & nu, DoubleTab & resu) const [protected]
Definition at line 112 of file Op_Diff_P1NC_barprim.cpp.
References Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), la_zcl_vef, la_zone_vef, Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_VEF_PreP1b::valeur(), and Zone_dis_base::zone().
Referenced by calculer().
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int elem,indice,face,comp,comp2;
  ArrOfDouble sigma(dimension);
  double normale;
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      for(indice=0; indice<nfe; indice++)
        {
          face = elem_faces(elem,indice);
          double signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(comp2=0; comp2<dimension; comp2++)
            {
              normale=signe*face_normales(face,comp2);
              for(comp=0; comp<dimension; comp++)
                resu(face, comp)-=nu(elem)*grad(elem,comp,comp2)*normale;
            }
        }
    }
  {
    int nb_bords=la_zone_vef->nb_front_Cl();
    for (int n_bord=0; n_bord<nb_bords; n_bord++)
      {
        const Cond_lim& la_cl = la_zcl_vef->les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// Cerr << "la_cl = " << la_cl.valeur() << finl;
        int num1 = le_bord.num_premiere_face();
        int num2 = num1 + le_bord.nb_faces();
        if ((la_cl->que_suis_je() == "Paroi_fixe"))
          {
// Cerr << "Paroi_fixe" << finl;
            for (face=num1; face<num2; face++)
              {
                for(comp2=0; comp2<dimension; comp2++)
                  {
                    normale=face_normales(face,comp2);
                    for(comp=0; comp<dimension; comp++)
                      resu(face, comp)=0.;
                  }
              }
          }
        else if (sub_type(Periodique,la_cl.valeur()))
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,
                                                     la_cl.valeur());
            ArrOfInt fait(le_bord.nb_faces());
            for (face=num1; face<num2; face++)
              {
                if(!fait(face-num1))
                  {
                    int face_associee=num1+la_cl_perio.face_associee(face-num1);
                    fait(face-num1)=(fait(face_associee-num1)=1);
                    for (comp=0; comp<dimension; comp++)
                      resu(face_associee,comp) =
                        (resu(face,comp)+= resu(face_associee,comp));
                  }
              }
          }
      }
  }
}
double Op_Diff_P1NC_barprim::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 99 of file Op_Diff_P1NC_barprim.cpp.
References Zone_VEF::carre_pas_du_maillage(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, DMINFLOAT, la_zone_vef, local_max_vect(), and Ref_Zone_VEF_PreP1b::valeur().
{
  double dt_stab;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  double alpha = 1.e-38;
// pas mp_max ?
  if (diffusivite_pour_pas_de_temps().valeurs().size() > 0)
    alpha = local_max_vect(diffusivite_pour_pas_de_temps().valeurs());
  dt_stab = zone_VEF.carre_pas_du_maillage()/(2.*dimension*(alpha+DMINFLOAT));
  return dt_stab;
}
void Op_Diff_P1NC_barprim::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 87 of file Op_Diff_P1NC_barprim.cpp.
{
  Operateur_base::completer();
}
void Op_Diff_P1NC_barprim::contribue_au_second_membre (DoubleTab &) const
void Op_Diff_P1NC_barprim::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 105 of file Op_Diff_P1NC_barprim.h.
{
  /*    ajouter_contribution(inco, matrice);    */
}
void Op_Diff_P1NC_barprim::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 114 of file Op_Diff_P1NC_barprim.h.
{
// contribue_au_second_membre(resu);
}
Objet_U * Op_Diff_P1NC_barprim::cree_instance () [static]
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
const Champ_base & Op_Diff_P1NC_barprim::diffusivite () const [virtual]
Implements Operateur_Diff_base.
Definition at line 93 of file Op_Diff_P1NC_barprim.cpp.
References diffusivite_.
Referenced by calculer().
{
  return diffusivite_;
}
void Op_Diff_P1NC_barprim::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Definition at line 89 of file Op_Diff_P1NC_barprim.h.
{
// Op_VEF_Face::dimensionner(la_zone_vef.valeur(), la_zcl_vef.valeur(), matrice);
  return;
}
int Op_Diff_P1NC_barprim::duplique () const [virtual]
Implements Operateur_Diff_base.
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
const Type_info * Op_Diff_P1NC_barprim::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
const Type_info * Op_Diff_P1NC_barprim::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
void Op_Diff_P1NC_barprim::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 95 of file Op_Diff_P1NC_barprim.h.
{
// Op_VEF_Face::modifier_pour_Cl(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice, secmem);
  return;
}
Sortie & Op_Diff_P1NC_barprim::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 48 of file Op_Diff_P1NC_barprim.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Diff_P1NC_barprim::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 55 of file Op_Diff_P1NC_barprim.cpp.
{
  return s;
}
const Op_Diff_P1NC_barprim & Op_Diff_P1NC_barprim::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Diff_base.
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
Op_Diff_P1NC_barprim & Op_Diff_P1NC_barprim::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Diff_base.
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
unsigned Op_Diff_P1NC_barprim::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 43 of file Op_Diff_P1NC_barprim.cpp.
Member Data Documentation
Ref_Champ_Uniforme Op_Diff_P1NC_barprim::diffusivite_ [protected]
Definition at line 81 of file Op_Diff_P1NC_barprim.h.
Referenced by associer_diffusivite(), and diffusivite().
const Type_info Op_Diff_P1NC_barprim::info_obj [static]
Reimplemented from Operateur_Diff_base.
Definition at line 51 of file Op_Diff_P1NC_barprim.h.
Ref_Zone_Cl_VEFP1B Op_Diff_P1NC_barprim::la_zcl_vef [protected]
Definition at line 80 of file Op_Diff_P1NC_barprim.h.
Referenced by associer(), calculer(), and calculer_divergence().
Ref_Zone_VEF_PreP1b Op_Diff_P1NC_barprim::la_zone_vef [protected]
Definition at line 79 of file Op_Diff_P1NC_barprim.h.
Referenced by associer(), calculer(), calculer_divergence(), and calculer_dt_stab().
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Diff_P1NC_barprim.h
src/P1NCP1B/Operateurs/Op_Diff_P1NC_barprim.cpp