TRUST: Traitement_particulier_NS_chmoy_faceperio Class Reference
Traitement_particulier_NS_chmoy_faceperio Class Reference abstract
classe Traitement_particulier_chmoy_faceperio
Cette classe permet de faire les traitements particuliers
pour les calculs de l'energie cinetique totale
#include <Traitement_particulier_NS_chmoy_faceperio.h>
Public Member Functions
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
~Traitement_particulier_NS_chmoy_faceperio () override
Traitement_particulier_NS_chmoy_faceperio ()
Entree & lire (Entree &) override
void preparer_calcul_particulier (void) override
void post_traitement_particulier (void) override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
void sauver_stat (void) const override
void reprendre_stat (void) override
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Traitement_particulier_NS_chmoy_faceperio & self_cast (Objet_U &)
static const Traitement_particulier_NS_chmoy_faceperio & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
virtual void init_calcul_stats ()=0
virtual void calcul_chmoy_faceperio (double, double, double)=0
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
DoubleTab chmoy_faceperio
double temps_deb
double temps_fin
int oui_stat
SFichier * le_fichier
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_chmoy_faceperio
Cette classe permet de faire les traitements particuliers
pour les calculs de l'energie cinetique totale
Definition at line 35 of file Traitement_particulier_NS_chmoy_faceperio.h.
Constructor & Destructor Documentation
~Traitement_particulier_NS_chmoy_faceperio()
Traitement_particulier_NS_chmoy_faceperio::~Traitement_particulier_NS_chmoy_faceperio () inline override
Definition at line 79 of file Traitement_particulier_NS_chmoy_faceperio.h.
{
}
Traitement_particulier_NS_chmoy_faceperio()
Traitement_particulier_NS_chmoy_faceperio::Traitement_particulier_NS_chmoy_faceperio () inline
Definition at line 76 of file Traitement_particulier_NS_chmoy_faceperio.h.
                                                                                           :le_fichier(0)
{
}
Member Function Documentation
calcul_chmoy_faceperio()
virtual void Traitement_particulier_NS_chmoy_faceperio::calcul_chmoy_faceperio (double , double , double) protected pure virtual
Implemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Referenced by post_traitement_particulier().
en_cours_de_resolution()
void Traitement_particulier_NS_chmoy_faceperio::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 62 of file Traitement_particulier_NS_chmoy_faceperio.h.
{
}
get_info()
const Type_info * Traitement_particulier_NS_chmoy_faceperio::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Definition at line 22 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
info()
const Type_info * Traitement_particulier_NS_chmoy_faceperio::info () static
Definition at line 22 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
init_calcul_stats()
virtual void Traitement_particulier_NS_chmoy_faceperio::init_calcul_stats () protected pure virtual
Implemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Referenced by preparer_calcul_particulier().
lire()
Entree & Traitement_particulier_NS_chmoy_faceperio::lire (Entree & is) override virtual
< temps de debut de calcul des stats temp.
< temps de fin de calcul des stats temp. initialisation pour le calcul des stats temp.
< =1 : on calcul des stats temp.
Implements Traitement_particulier_NS_base.
Definition at line 64 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
{
// Initialisation
  oui_stat = 0;
// FIN Initialisation
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcle motbidon, motlu;
  is >> motbidon ;
  if (motbidon == accouverte)
    {
      Motcles les_mots(1);
      les_mots[0] = "stats";
      is >> motlu;
      while(motlu != accfermee)
        {
          int rang=les_mots.search(motlu);
          switch(rang)
            {
            case 0 :
              {
// Pour stats
                is >> temps_deb;     //!< temps de debut de calcul des stats temp.
                is >> temps_fin;     //!< temps de fin de calcul des stats temp. initialisation pour le calcul des stats temp.
//
                oui_stat=1;          //!< =1 : on calcul des stats temp.
                Cerr << "Reading time statitics parameters..." << finl;
                Cerr << "Initial time : " << temps_deb << " End time : " << temps_fin << finl;
// Verif ensuite pour voir si on a rentrer les valeurs specifiques aux calculs des stats spat.
                break;
              }
            default :
              {
                Cerr << "Default case..." << finl;
                Cerr << "Les mots cles possibles sont "<< les_mots <<" { et }" << finl;
                Cerr << "Vous avez lu :" << motlu << finl;
                break;
              }
            }
          is >> motlu;
        }
      is >> motlu;
      if (motlu != accfermee)
        {
          Cerr << "Error while reading in Traitement_particulier_NS_canal" << finl;;
          Cerr << "We were expecting a }" << finl;
          exit();
        }
    }
  else
    {
      Cerr << "Error while reading in Traitement_particulier_NS_canal" << finl;
      Cerr << "We were expecting a {" << finl;
      exit();
    }
  return is;
}
References Cerr, Process::exit(), finl, oui_stat, Motcles::search(), temps_deb, and temps_fin.
post_traitement_particulier()
void Traitement_particulier_NS_chmoy_faceperio::post_traitement_particulier (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 160 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
{
  double temps = mon_equation->inconnue().temps();
  double dt = mon_equation->schema_temps().pas_de_temps();
  if (temps>temps_deb && temps<temps_fin)
    calcul_chmoy_faceperio(temps_deb,temps,dt);
}
References calcul_chmoy_faceperio(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Champ_Inc::temps(), temps_deb, and temps_fin.
preparer_calcul_particulier()
void Traitement_particulier_NS_chmoy_faceperio::preparer_calcul_particulier (void) override virtual
Implements Traitement_particulier_NS_base.
Definition at line 125 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
{
  if(Objet_U::dimension!=3)
    {
      Cerr << " Traitement_particulier_NS_chmoy_faceperio : non prevu pour des calculs autres que 3D " << finl;
      exit();
    }
  if (oui_stat != 0)
    init_calcul_stats();
  double temps = mon_equation->inconnue().temps();
  int Nbfaces,num_face;
  if (temps>temps_deb)
    {
      Nom fichier = "chmoy_face_perio";
      ifstream fic(fichier);
      if (!fic)
        {
          Cerr << " pas de fichier : chmoy_face_perio  - reprise des calculs impossible" << finl;
          exit();
        }
      else
        {
          LecFicDistribue fic2(fichier);
          fic2 >> Nbfaces;
          for (int i=0; i<Nbfaces; i++)
            fic2 >> num_face >> chmoy_faceperio(num_face,0) >> chmoy_faceperio(num_face,1) >> chmoy_faceperio(num_face,2);
        }
    }
}
References Cerr, chmoy_faceperio, Objet_U::dimension, Process::exit(), finl, Navier_Stokes_std::inconnue(), init_calcul_stats(), Traitement_particulier_NS_base::mon_equation, oui_stat, Champ_Inc::temps(), and temps_deb.
printOn()
Sortie & Traitement_particulier_NS_chmoy_faceperio::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Definition at line 39 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_chmoy_faceperio::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_base.
Reimplemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Definition at line 59 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
{
  return is;
}
reprendre_stat()
void Traitement_particulier_NS_chmoy_faceperio::reprendre_stat (void) inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 71 of file Traitement_particulier_NS_chmoy_faceperio.h.
{
  ;
}
sauver_stat()
void Traitement_particulier_NS_chmoy_faceperio::sauver_stat (void) const inline override virtual
Implements Traitement_particulier_NS_base.
Definition at line 66 of file Traitement_particulier_NS_chmoy_faceperio.h.
{
  ;
}
self_cast() [1/2]
const Traitement_particulier_NS_chmoy_faceperio & Traitement_particulier_NS_chmoy_faceperio::self_cast (const Objet_U & r) static
Definition at line 22 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
self_cast() [2/2]
Traitement_particulier_NS_chmoy_faceperio & Traitement_particulier_NS_chmoy_faceperio::self_cast (Objet_U & r) static
Definition at line 22 of file Traitement_particulier_NS_chmoy_faceperio.cpp.
Member Data Documentation
chmoy_faceperio
DoubleTab Traitement_particulier_NS_chmoy_faceperio::chmoy_faceperio protected
Definition at line 54 of file Traitement_particulier_NS_chmoy_faceperio.h.
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and preparer_calcul_particulier().
info_obj
const Type_info Traitement_particulier_NS_chmoy_faceperio::info_obj static
Definition at line 37 of file Traitement_particulier_NS_chmoy_faceperio.h.
le_fichier
SFichier* Traitement_particulier_NS_chmoy_faceperio::le_fichier protected
Definition at line 57 of file Traitement_particulier_NS_chmoy_faceperio.h.
oui_stat
int Traitement_particulier_NS_chmoy_faceperio::oui_stat protected
Definition at line 56 of file Traitement_particulier_NS_chmoy_faceperio.h.
Referenced by lire(), and preparer_calcul_particulier().
temps_deb
double Traitement_particulier_NS_chmoy_faceperio::temps_deb protected
Definition at line 55 of file Traitement_particulier_NS_chmoy_faceperio.h.
Referenced by lire(), post_traitement_particulier(), and preparer_calcul_particulier().
temps_fin
double Traitement_particulier_NS_chmoy_faceperio::temps_fin protected
Definition at line 55 of file Traitement_particulier_NS_chmoy_faceperio.h.
Referenced by lire(), and post_traitement_particulier().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_chmoy_faceperio.h
src/ThHyd/Incompressible/Traitement_particulier/Traitement_particulier_NS_chmoy_faceperio.cpp