TRUST: Reordonner_faces_periodiques Class Reference
Reordonner_faces_periodiques Class Reference
Cet interprete permet de reordonner les faces d'un bord periodique selon la convention
utilisee dans le decoupeur (d'abord les faces d'une extremite du domaine, puis dans le
meme ordre, les faces jumelles sur le bord oppose).
#include <Reordonner_faces_periodiques.h>
Static Public Member Functions
static int reordonner_faces_periodiques (const Domaine &domaine, IntTab &faces, const ArrOfDouble &direction_perio, const double epsilon)
Reordonne le tableau "faces" selon la convention des faces periodiques:
D'abord les faces d'une extremite, puis dans le meme ordre, les faces jumelles.
Attention, l'algorithme est en n carre (lent), et ne fonctionne qu'en sequentiel.
Parametre: zone
Signification: la zone a laquelle appartiennent les faces
Parametre: direction_perio
Signification: le vecteur qui separe le centre d'une face au centre de la face opposee
Parametre: faces
Signification: le tableau des faces (pour chaque face, indices de ses sommets) a reordonner
Valeur de retour: 1 si ok, 0 si on n'a pas trouve de face jumelle a une face a precision_geom pres.
static int check_faces_periodiques (const Frontiere &frontiere, ArrOfDouble &vecteur_delta, ArrOfDouble &erreur, const int verbose=0)
essaie de verifier si les faces du bord num_bord sont ordonnees suivant la convention
des faces periodiques. On stocke dans vecteur_delta la direction de periodicite presumee (intervalle
mesure entre la premiere face et la face jumelle), et erreur le max de l'erreur par rapport a cette
mesure pour les autres faces.
En parallele, l'erreur est le max sur tous les processeurs
Valeur de retour: 1 si ok, 0 si l'erreur est superieure a precision_geom.
static void renum_som_perio (const Domaine &, const Noms &liste_bords_periodiques, ArrOfInt &renum_som_perio, const int calculer_espace_virtuel)
static void chercher_direction_perio (ArrOfDouble &direction_perio, const Domaine &dom, const Nom &bord)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Additional Inherited Members
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Cet interprete permet de reordonner les faces d'un bord periodique selon la convention
utilisee dans le decoupeur (d'abord les faces d'une extremite du domaine, puis dans le
meme ordre, les faces jumelles sur le bord oppose).
Definition at line 28 of file Reordonner_faces_periodiques.h.
Member Function Documentation
check_faces_periodiques()
int Reordonner_faces_periodiques::check_faces_periodiques (const Frontiere & frontiere, ArrOfDouble & vecteur_delta, ArrOfDouble & erreur, const int verbose = 0) static
essaie de verifier si les faces du bord num_bord sont ordonnees suivant la convention
des faces periodiques. On stocke dans vecteur_delta la direction de periodicite presumee (intervalle
mesure entre la premiere face et la face jumelle), et erreur le max de l'erreur par rapport a cette
mesure pour les autres faces.
En parallele, l'erreur est le max sur tous les processeurs
Valeur de retour: 1 si ok, 0 si l'erreur est superieure a precision_geom.
Definition at line 209 of file Reordonner_faces_periodiques.cpp.
{
  const int dim = Objet_U::dimension;
  vecteur_delta.resize_array(dim);
  vecteur_delta = 0.;
  erreur.resize_array(dim);
  erreur = 0.;
  if (verbose && Process::je_suis_maitre())
    {
      Cerr << "Check periodic faces to the boundary : " << frontiere.le_nom() << finl;
    }
  const IntTab& faces = frontiere.faces().les_sommets();
  const int nb_faces = faces.dimension(0);
  if (nb_faces % 2 != 0)
    {
      Cerr << "Error in Check_faces_periodiques to the boundary " << frontiere.le_nom()
           << "\n The number of faces is odd : " << nb_faces << finl;
      Process::exit();
    }
  const int n = nb_faces / 2;
  const DoubleTab coord = frontiere.zone().domaine().les_sommets();
  int i;
// Calculer un vecteur delta (tous les procs n'ont pas forcement des faces de ce bord)
  vecteur_delta = -1.e37;
  if (n > 0)
    calculer_vecteur_2faces(coord, faces, 0, n, vecteur_delta);
  for (i = 0; i < dim; i++)
    vecteur_delta[i] = Process::mp_max(vecteur_delta[i]);
// Calculer pour chaque face l'erreur par rapport a ce vecteur delta.
  ArrOfDouble vect(dim);
  for (i = 0; i < n; i++)
    {
      calculer_vecteur_2faces(coord, faces, i, i+n, vect);
// Calcul de la difference entre vect et vecteur_delta:
      for (int compo = 0; compo < dim; compo++)
        erreur[compo] = std::max(erreur[compo], std::fabs(vecteur_delta[compo] - vect[compo]));
    }
  double maxerr = 0.;
// Calcul du max sur tous les procs:
  for (i = 0; i < dim; i++)
    {
      erreur[i] = Process::mp_max(erreur[i]);
      maxerr = std::max(maxerr, erreur[i]);
    }
  if (verbose && Process::je_suis_maitre())
    {
      Cerr << " Delta vector = [ ";
      for (i = 0; i < dim; i++) Cerr << vecteur_delta[i] << " ";
      Cerr << "]  error = [ ";
      for (i = 0; i < dim; i++) Cerr << erreur[i] << " ";
      Cerr << "]" << finl;
    }
  if (!(maxerr < Objet_U::precision_geom))
    {
      if (Process::je_suis_maitre())
        {
          Cerr << " This boundary is not detected as periodic (geometric error > precision_geom)" << finl;
          message();
          if (Process::nproc()>1) Cerr << "Or you forgot to define the periodic boundary in the Decouper keyword." << finl;
        } //!< attendre qu'on ait ecrit pour continuer (sinon risque de exit() avant d'avoir affiche le message)
      Process::barrier();
      return 0;
    }
  return 1;
}
References Process::barrier(), calculer_vecteur_2faces(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), erreur(), Process::exit(), Frontiere::faces(), finl, Process::je_suis_maitre(), Frontiere::le_nom(), Domaine::les_sommets(), Faces::les_sommets(), message(), Process::mp_max(), Process::nproc(), Objet_U::precision_geom, TRUSTArray< _TYPE_ >::resize_array(), and Frontiere::zone().
Referenced by Partitionneur_base::calculer_graphe_connexions_periodiques(), Partitionneur_Tranche::chercher_direction_perio(), Periodique::completer(), and renum_som_perio().
chercher_direction_perio()
void Reordonner_faces_periodiques::chercher_direction_perio (ArrOfDouble & direction_perio, const Domaine & dom, const Nom & bord) static
Definition at line 58 of file Reordonner_faces_periodiques.cpp.
{
  const DoubleTab& sommets = dom.coord_sommets();
  const int dim = sommets.dimension(1);
  direction_perio.resize_array(dim);
  direction_perio = 0.;
  const Frontiere& front = dom.zone(0).frontiere(bord);
  const int nb_faces = front.nb_faces();
  if (nb_faces == 0)
    return;
  const IntTab& faces = front.faces().les_sommets();
  const int nb_som_face = faces.dimension(1);
  DoubleTab normale(1, dim);
  IntTab une_face(1, nb_som_face);
  int i;
  for (i = 0; i < nb_som_face; i++)
    une_face(0, i) = faces(0, i);
  dom.zone(0).type_elem().calculer_normales(une_face, normale);
  normale /= local_norme_vect(normale);
  ArrOfDouble delta(nb_faces);
  ArrOfDouble vect(dim);
  for (i = 1; i < nb_faces; i++)
    {
      calculer_vecteur_2faces(sommets, faces, 0, i, vect);
      double x = 0.;
      for (int j = 0; j < dim; j++)
        x += vect[j] * normale(0,j);
      delta[i] = x;
    }
  const double min = min_array(delta);
  const double max = max_array(delta);
  double facteur = (std::fabs(min) > std::fabs(max)) ? min : max;
  for (i = 0; i < dim; i++)
    direction_perio[i] = normale(0, i) * facteur;
  Cerr << "Periodicity direction for " << dom.le_nom() << "/" << bord << " " << direction_perio;
}
References Elem_geom::calculer_normales(), calculer_vecteur_2faces(), Cerr, Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Frontiere::faces(), Zone::frontiere(), Domaine::le_nom(), Faces::les_sommets(), local_norme_vect(), max_array(), min_array(), Frontiere::nb_faces(), TRUSTArray< _TYPE_ >::resize_array(), Zone::type_elem(), and Domaine::zone().
Referenced by Corriger_frontiere_periodique::interpreter_(), and Scatter::lire_domaine().
renum_som_perio()
void Reordonner_faces_periodiques::renum_som_perio (const Domaine & domaine, const Noms & liste_bords_periodiques, ArrOfInt & renum_som_perio, const int calculer_espace_virtuel) static
Definition at line 282 of file Reordonner_faces_periodiques.cpp.
{
  int i;
  const int nb_som = domaine.nb_som();
  IntTab renum(nb_som);
  for (i = 0; i < nb_som; i++)
    renum[i] = renum_som_perio[i];
  const DoubleTab coord = domaine.coord_sommets();
  const int dim = coord.dimension(1);
// Etape 1: pour chaque sommet reel, trouver un sommet associe (si plusieurs directions
// de periodicite, un sommet peut etre associe a plusieurs autres).
  const int nb_bords_perio = liste_bords_periodiques.size();
  for (int i_bord = 0; i_bord < nb_bords_perio; i_bord++)
    {
      const Nom& nom_bord = liste_bords_periodiques[i_bord];
      const Frontiere& front = domaine.zone(0).bord(nom_bord);
// Direction periodique de ce bord:
      ArrOfDouble delta;
      ArrOfDouble erreur;
      if (!check_faces_periodiques(front, delta, erreur, 1 /* verbose */))
        exit();
// Tableau pointant vers tous les sommets de toutes les faces
// (on cast le IntTab en ArrOfInt)
      const IntTab& faces_sommets = front.les_sommets_des_faces();
      const int nb_som_face = faces_sommets.dimension(1);
      const int nb_faces = faces_sommets.dimension(0) / 2;
// Boucle sur les faces d'un cote du domaine (premiere moitie des faces)
      for (int i_face = 0; i_face < nb_faces; i_face++)
        {
          for (int i_som = 0; i_som < nb_som_face; i_som++)
            {
              const int sommet = faces_sommets(i_face, i_som);
// Trouver le sommet associe
// Comme les frontieres sont ordonnees (voir check_faces_periodiques),
// le sommet est forcement un des sommets de la face opposee.
// Le vecteur qui va de "sommet" a "sommet_oppose" doit etre egal a "delta"
// la direction de periodicite.
              const int i_face_opposee = i_face + nb_faces;
              int sommet_opp = -1;
              int i_som_opp;
              for (i_som_opp = 0; i_som_opp < nb_som_face; i_som_opp++)
                {
                  sommet_opp = faces_sommets(i_face_opposee, i_som_opp);
                  for (i = 0; i < dim; i++)
                    {
                      double epsilon = std::fabs((coord(sommet_opp, i) - coord(sommet, i)) - delta[i]);
                      if (epsilon > Objet_U::precision_geom)
                        break;
                    }
                  if (i == dim)
// On a trouve le sommet oppose
                    break;
                }
              if (i_som_opp >= nb_som_face)
                {
                  Cerr << "[PE" << Process::me() << "] Error in Reordonner_faces_periodiques::renum_som_perio\n"
                       << " An opposite node has not been found\n"
                       << " Boundary " << nom_bord << "\n Face 1: " << i_face << "\n Node: " << sommet << finl;
                  Cerr << " May be you should define the periodic boundary " << nom_bord << finl;
                  message();
                  exit();
                }
              renum[sommet_opp] = sommet;
            }
        }
    }
// Deuxieme etape: faire pointer tous les sommets periodiques lies entre eux vers le meme sommet
  for (i = 0; i < nb_som; i++)
    {
      int j = renum[i];
// Parcourir les sommet relies pour cette chaine:
      while (j != renum[j])
        j = renum[j];
      renum[i] = j;
    }
// Calcul des valeurs pour les sommets virtuels.
// Les sommets opposes aux sommets virtuels doivent etre connus, donc erreurs fatales.
  if (calculer_espace_virtuel)
    {
      const MD_Vector& md_sommets = domaine.les_sommets().get_md_vector();
      Scatter::construire_espace_virtuel_traduction(md_sommets, md_sommets, renum, 1 /* erreurs fatales */);
    }
// Recopie du resultat dans le tableau renum_som_perio
  assert(renum.dimension_tot(0) == domaine.nb_som_tot());
  renum_som_perio = renum;
}
References Zone::bord(), Cerr, check_faces_periodiques(), Scatter::construire_espace_virtuel_traduction(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Interprete_geometrique_base::domaine(), erreur(), Process::exit(), finl, TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::les_sommets(), Frontiere::les_sommets_des_faces(), Process::me(), message(), Domaine::nb_som(), Domaine::nb_som_tot(), Objet_U::precision_geom, renum_som_perio(), vect_impl::size(), and Domaine::zone().
Referenced by Scatter::calculer_espace_distant_sommets(), Domaine::construire_renum_som_perio(), Partitionneur_base::corriger_bords_avec_graphe(), and renum_som_perio().
reordonner_faces_periodiques()
int Reordonner_faces_periodiques::reordonner_faces_periodiques (const Domaine & domaine, IntTab & faces, const ArrOfDouble & direction_perio, const double epsilon) static
Reordonne le tableau "faces" selon la convention des faces periodiques:
D'abord les faces d'une extremite, puis dans le meme ordre, les faces jumelles.
Attention, l'algorithme est en n carre (lent), et ne fonctionne qu'en sequentiel.
Parametre: zone
Signification: la zone a laquelle appartiennent les faces
Parametre: direction_perio
Signification: le vecteur qui separe le centre d'une face au centre de la face opposee
Parametre: faces
Signification: le tableau des faces (pour chaque face, indices de ses sommets) a reordonner
Valeur de retour: 1 si ok, 0 si on n'a pas trouve de face jumelle a une face a precision_geom pres.
< Face deja traitee, on passe Cherche la face opposee dans les deux directions (-1. et +1.)
Definition at line 107 of file Reordonner_faces_periodiques.cpp.
{
// Modif B.M. 04/06/2010: j'autorise l'operation en parallele car c'est utilise par
// l'interprete MaillerParallel...
// PL 18/11/2010: Je deplace neanmoins l'interdiction de l'utilisation de l'interprete en // dans le jeu de donnees (voir ::interpreter_)
  const int nb_faces = faces.dimension(0);
  const int nb_som_faces = faces.dimension(1);
  const int dim = domaine.les_sommets().dimension(1);
// Calcul des coordonnees des centres des faces:
  DoubleTab centres(nb_faces, 3);
  {
    const DoubleTab& coord = domaine.les_sommets();
    const double inv_nb_som = 1. / (double) nb_som_faces;
    for (int i = 0; i < nb_faces; i++)
      {
        for (int j = 0; j < nb_som_faces; j++)
          {
            const int sommet = faces(i, j);
            for (int k = 0; k < dim; k++)
              centres(i, k) += coord(sommet, k) * inv_nb_som;
          }
      }
  }
// Construction d'un octree contenant les centres des faces:
  Octree_Double octree;
  octree.build_nodes(centres, 0 /* do not include virtual nodes */);
// Pour chaque face, on cherche sa face periodique associee (dont le centre
// est decale de direction_perio).
// Pour chaque face, son nouvel indice dans le tableau des faces
  ArrOfInt renum_faces(nb_faces);
  renum_faces= -1;
  ArrOfInt nodes_list;
  nodes_list.set_smart_resize(1);
  ArrOfDouble coord(dim);
  int count = 0;
  for (int i_face = 0; i_face < nb_faces; i_face++)
    {
      if (renum_faces[i_face] >= 0)
        continue; //!< Face deja traitee, on passe Cherche la face opposee dans les deux directions (-1. et +1.)
//
      double facteur;
      int i_face2 = -1;
      for (facteur = -1.; facteur < 1.5; facteur += 2.)
        {
          for (int i = 0; i < dim; i++)
            coord[i] = centres(i_face, i) + facteur * direction_perio[i];
          octree.search_elements_box(coord, epsilon, nodes_list);
          i_face2 = octree.search_nodes_close_to(coord, centres, nodes_list, epsilon);
          if (i_face2 >= 0)
            break;
        }
      if (i_face2 >= 0)
        {
          if (renum_faces[i_face2] >= 0)
            {
              Cerr << "====================================================" << finl;
              Cerr << "Error in reordonner_faces_periodiques: the face " << i_face
                   << " of " << centres(i_face,0) << " " << centres(i_face,1) << " "
                   << ((dim==3)?centres(i_face,2):0.)
                   << " center already has a face twin."
                   << finl;
              Cerr << "Possible problem: the boundary is not periodic. Check your mesh." << finl;
              return 0;
            }
          int f0 = (facteur > 0.) ? i_face : i_face2;
          int f1 = (facteur > 0.) ? i_face2: i_face;
          renum_faces[f0] = count;
          renum_faces[f1] = count + nb_faces / 2;
          count++;
        }
      else
        {
          Cerr << "====================================================" << finl;
          Cerr << "Error in reordonner_faces_periodiques: the face " << i_face << " of " << centres(i_face,0) << " " << centres(i_face,1) << " "
               << ((dim==3)?centres(i_face,2):0.) << finl;
          Cerr << "center has no face twin into the specified direction in the list of faces." << finl;
          return 0;
        }
    }
// Reordonner les faces:
  const IntTab oldfaces(faces);
  for (int i = 0; i < nb_faces; i++)
    {
      const int new_i = renum_faces[i];
      for (int j = 0; j < nb_som_faces; j++)
        faces(new_i, j) = oldfaces(i, j);
    }
  return 1;
}
References Octree_Double::build_nodes(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), f1, finl, Domaine::les_sommets(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), and TRUSTArray< _TYPE_ >::set_smart_resize().
Referenced by MaillerParallel::interpreter(), Corriger_frontiere_periodique::interpreter_(), and Scatter::lire_domaine().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Reordonner_faces_periodiques.h
src/Kernel/Geometrie/Reordonner_faces_periodiques.cpp