TRUST: Op_Diff_CoviMAC_base Class Reference
Op_Diff_CoviMAC_base Class Reference
class Op_Diff_CoviMAC_base
Classe de base des operateurs de diffusion CoviMAC
#include <Op_Diff_CoviMAC_base.h>
Public Member Functions
Op_Diff_CoviMAC_base ()
~Op_Diff_CoviMAC_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
void associer_diffusivite (const Champ_base &)
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const
void mettre_a_jour (double t)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual int dimension_min_nu () const
virtual void modifier_nu (DoubleTab &) const
const DoubleTab & nu () const
const DoubleTab & invh () const
const DoubleTab & xh () const
const DoubleTab & wh () const
const DoubleTab & whm () const
void update_phif (int full_stencil=0) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
calcule la contribution de la diffusion, la range dans resu
renvoie resu
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_CoviMAC_base & self_cast (Objet_U &)
static const Op_Diff_CoviMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
IntTab pe_ext
tableau aux faces de bord : (indice dans op_ext, indice d'element) pour les faces de type Echange_contact
IntTab phif_d
IntTab phif_e
IntTab phif_pe
DoubleTab phif_w
DoubleTab phif_c
DoubleTab phif_pc
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
void update_nu_invh () const
void init_op_ext () const
void update_xwh () const
Protected Attributes
Ref_Zone_CoviMAC la_zone_poly_
Ref_Zone_Cl_CoviMAC la_zcl_poly_
Ref_Champ_base diffusivite_
double t_last_maj_ = -1e10
DoubleTab nu_
DoubleTab invh_
DoubleTab xh_
DoubleTab wh_
DoubleTab whm_
int nu_constant_
int nu_a_jour_ = 0
int op_ext_init_ = 0
int xwh_a_jour_ = 0
int phif_a_jour_ = 0
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Detailed Description
class Op_Diff_CoviMAC_base
Classe de base des operateurs de diffusion CoviMAC
Definition at line 54 of file Op_Diff_CoviMAC_base.h.
Constructor & Destructor Documentation
Op_Diff_CoviMAC_base::Op_Diff_CoviMAC_base ()
Definition at line 50 of file Op_Diff_CoviMAC_base.cpp.
Op_Diff_CoviMAC_base::~Op_Diff_CoviMAC_base ()
Definition at line 50 of file Op_Diff_CoviMAC_base.cpp.
Member Function Documentation
void Op_Diff_CoviMAC_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zcl, const Champ_Inc &) [virtual]
Implements Operateur_base.
Definition at line 256 of file Op_Diff_CoviMAC_base.cpp.
References la_zcl_poly_, la_zone_poly_, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_poly_ = ref_cast(Zone_CoviMAC,zone_dis.valeur());
  la_zcl_poly_ = ref_cast(Zone_Cl_CoviMAC,zcl.valeur());
}
void Op_Diff_CoviMAC_base::associer_diffusivite (const Champ_base & diffu) [virtual]
Implements Operateur_Diff_base.
Definition at line 272 of file Op_Diff_CoviMAC_base.cpp.
References diffusivite_.
{
  diffusivite_ = diffu;
}
DoubleTab & Op_Diff_CoviMAC_base::calculer (const DoubleTab & inco, DoubleTab & resu) const [virtual]
calcule la contribution de la diffusion, la range dans resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 265 of file Op_Diff_CoviMAC_base.cpp.
References Operateur_base::ajouter().
{
  resu =0;
  return ajouter(inco, resu);
}
void Op_Diff_CoviMAC_base::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 80 of file Op_Diff_CoviMAC_base.cpp.
References Zone::creer_tableau_elements(), Zone_VF::creer_tableau_faces_bord(), diffusivite(), Objet_U::dimension, dimension_min_nu(), MorEqn::equation(), Process::exit(), Op_Diff_Turbulent_base::has_diffusivite_turbulente(), Equation_base::inconnue(), invh_, la_zone_poly_, DoubleVect::line_size(), max(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), nu_, nu_constant_, phif_w, DoubleTab::resize(), sub_type, Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), wh_, xh_, and Zone_dis_base::zone().
{
  Operateur_base::completer();
  const Equation_base& eq = equation();
  int N = eq.inconnue().valeurs().line_size(), D = dimension, N_nu = max(N * dimension_min_nu(), diffusivite().valeurs().line_size());
  if (N_nu == N) nu_.resize(0, N); //isotrope
  else if (N_nu == N * D) nu_.resize(0, N, D); //diagonal
  else if (N_nu == N * D * D) nu_.resize(0, N, D, D); //complet
  else Process::exit(Nom("Op_Diff_CoviMAC_base : diffusivity component count ") + Nom(N_nu) + "not among (" + Nom(N) + ", " + Nom(N * D) + ", " + Nom(N * D * D)  + ")!");
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  zone.zone().creer_tableau_elements(nu_);
  invh_.resize(0, N), zone.creer_tableau_faces_bord(invh_);
  xh_.resize(zone.nb_faces_tot(), N, dimension); //position des points harmoniques, poids de l'amont
  wh_.resize(zone.nb_faces_tot(), N);
  int f_max = sub_type(Op_Diff_CoviMAC_Face, *this) ? zone.nb_faces_tot() : zone.nb_faces(); //en Op_.._Face, on doit aussi faire les faces virtuelles
  phif_w.resize(f_max, N); //tableaux phif_* statiques
  nu_constant_ = (sub_type(Champ_Uniforme, diffusivite()) || sub_type(Champ_Don_Fonc_xyz, diffusivite())) && !has_diffusivite_turbulente();
}
const Champ_base & Op_Diff_CoviMAC_base::diffusivite () const [virtual]
Implements Operateur_Diff_base.
Definition at line 277 of file Op_Diff_CoviMAC_base.cpp.
References diffusivite_, and Ref_Champ_base::valeur().
Referenced by Op_Diff_CoviMAC_Elem::calculer_dt_stab(), completer(), and update_nu_invh().
{
  return diffusivite_.valeur();
}
virtual int Op_Diff_CoviMAC_base::dimension_min_nu () const [inline, virtual]
Definition at line 72 of file Op_Diff_CoviMAC_base.h.
Referenced by completer().
  {
    return 1;
  };
virtual int Op_Diff_CoviMAC_base::duplique () const [pure virtual]
Implements Operateur_Diff_base.
Implemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
const Type_info * Op_Diff_CoviMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 50 of file Op_Diff_CoviMAC_base.cpp.
int Op_Diff_CoviMAC_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 123 of file Op_Diff_CoviMAC_base.cpp.
References Sortie::add_col(), Zone::Bords_a_imprimer(), Zone::Bords_a_imprimer_sum(), Zone::cg_moments(), List_Nom::contient(), Objet_U::dimension, DoubleTab::dimension(), liste::est_vide(), finl, Flux, Operateur_base::flux_bords(), Flux_moment, Flux_sum, Cond_lim::frontiere_dis(), Schema_Temps_base::imprimer_temps_courant(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), la_zcl_poly_, la_zone_poly_, Frontiere_dis_base::le_nom(), LIST, Zone::Moments_a_imprimer(), mp_sum_for_each_item(), DoubleTab::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), ref_cast, EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
{
  const Zone& ma_zone=la_zone_poly_->zone();
  const int& impr_mom=ma_zone.Moments_a_imprimer();
  const int impr_sum=(ma_zone.Bords_a_imprimer_sum().est_vide() ? 0:1);
  const int impr_bord=(ma_zone.Bords_a_imprimer().est_vide() ? 0:1);
  const Schema_Temps_base& sch = la_zcl_poly_->equation().probleme().schema_temps();
  DoubleTab& tab_flux_bords= flux_bords();
  int nb_comp = tab_flux_bords.nb_dim() > 1 ? tab_flux_bords.dimension(1) : 0;
  DoubleVect bilan(nb_comp);
  const int nb_faces = la_zone_poly_->nb_faces_tot();
  DoubleTab xgr(nb_faces,dimension);
  xgr=0.;
  if (impr_mom)
    {
      const DoubleTab& xgrav = la_zone_poly_->xv();
      const ArrOfDouble& c_grav=ma_zone.cg_moments();
      for (int num_face=0; num_face <nb_faces; num_face++)
        for (int i=0; i<dimension; i++)
          xgr(num_face,i)=xgrav(num_face,i)-c_grav(i);
    }
  int k,face;
  int nb_front_Cl=la_zone_poly_->nb_front_Cl();
  DoubleTrav flux_bords2( 5, nb_front_Cl , nb_comp) ;
  flux_bords2=0;
  for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl_poly_->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      for (face=ndeb; face<nfin; face++)
        {
          for(k=0; k<nb_comp; k++)
            {
              flux_bords2(0,num_cl,k)+=tab_flux_bords(face, k);
              if (ma_zone.Bords_a_imprimer_sum().contient(frontiere_dis.le_nom()))
                flux_bords2(3,num_cl,k)+=tab_flux_bords(face, k);
            }  /* fin for k */
          if (impr_mom)
            {
              if (dimension==2)
                {
                  flux_bords2(4,num_cl,0)+=tab_flux_bords(face,1)*xgr(face,0)-tab_flux_bords(face,0)*xgr(face,1);
                }
              else
                {
                  flux_bords2(4,num_cl,0)+=tab_flux_bords(face,2)*xgr(face,1)-tab_flux_bords(face,1)*xgr(face,2);
                  flux_bords2(4,num_cl,1)+=tab_flux_bords(face,0)*xgr(face,2)-tab_flux_bords(face,2)*xgr(face,0);
                  flux_bords2(4,num_cl,2)+=tab_flux_bords(face,1)*xgr(face,0)-tab_flux_bords(face,0)*xgr(face,1);
                }
            }
        } /* fin for face */
    }
  mp_sum_for_each_item(flux_bords2);
  if (je_suis_maitre() && nb_comp > 0)
    {
// SFichier Flux;
      if (!Flux.is_open()) ouvrir_fichier(Flux,"",1);
// SFichier Flux_moment;
      if (!Flux_moment.is_open()) ouvrir_fichier(Flux_moment,"moment",impr_mom);
// SFichier Flux_sum;
      if (!Flux_sum.is_open()) ouvrir_fichier(Flux_sum,"sum",impr_sum);
      Flux.add_col(sch.temps_courant());
      if (impr_mom) Flux_moment.add_col(sch.temps_courant());
      if (impr_sum) Flux_sum.add_col(sch.temps_courant());
      for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
        {
          for(k=0; k<nb_comp; k++)
            {
              Flux.add_col(flux_bords2(0,num_cl,k));
              if (impr_sum) Flux_sum.add_col(flux_bords2(3,num_cl,k));
              bilan(k)+=flux_bords2(0,num_cl,k);
            }
          if (dimension==3)
            {
              for (k=0; k<nb_comp; k++)
                if (impr_mom) Flux_moment.add_col(flux_bords2(4,num_cl,k));
            }
          else
            {
              if (impr_mom) Flux_moment.add_col(flux_bords2(4,num_cl,0));
            }
        } /* fin for num_cl */
      for(k=0; k<nb_comp; k++)
        Flux.add_col(bilan(k));
      Flux << finl;
      if (impr_sum) Flux_sum << finl;
      if (impr_mom) Flux_moment << finl;
    }
  const LIST(Nom)& Liste_Bords_a_imprimer = la_zone_poly_->zone().Bords_a_imprimer();
  if (!Liste_Bords_a_imprimer.est_vide() && nb_comp > 0)
    {
      EcrFicPartage Flux_face;
      ouvrir_fichier_partage(Flux_face,"",impr_bord);
      for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
        {
          const Frontiere_dis_base& la_fr = la_zcl_poly_->les_conditions_limites(num_cl).frontiere_dis();
          const Cond_lim& la_cl = la_zcl_poly_->les_conditions_limites(num_cl);
          const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = frontiere_dis.num_premiere_face();
          int nfin = ndeb + frontiere_dis.nb_faces();
          if (ma_zone.Bords_a_imprimer().contient(la_fr.le_nom()))
            {
              if(je_suis_maitre())
                {
                  Flux_face << "# Flux par face sur " << la_fr.le_nom() << " au temps ";
                  sch.imprimer_temps_courant(Flux_face);
                  Flux_face << " : " << finl;
                }
              for (face=ndeb; face<nfin; face++)
                {
                  if (dimension == 2)
                    Flux_face << "# Face a x= " << la_zone_poly_->xv(face,0) << " y= " << la_zone_poly_->xv(face,1) << " : ";
                  else if (dimension == 3)
                    Flux_face << "# Face a x= " << la_zone_poly_->xv(face,0) << " y= " << la_zone_poly_->xv(face,1) << " z= " << la_zone_poly_->xv(face,2) << " : ";
                  for(k=0; k<nb_comp; k++)
                    Flux_face << tab_flux_bords(face, k) << " ";
                  Flux_face << finl;
                }
              Flux_face.syncfile();
            }
        }
    }
  return 1;
}
const Type_info * Op_Diff_CoviMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 50 of file Op_Diff_CoviMAC_base.cpp.
void Op_Diff_CoviMAC_base::init_op_ext () const [protected]
Definition at line 101 of file Op_Diff_CoviMAC_base.cpp.
References Zone_VF::creer_tableau_faces_bord(), MorEqn::equation(), Zone_VF::fbord(), Echange_contact_CoviMAC::fe_dist(), Equation_base::inconnue(), la_zcl_poly_, la_zone_poly_, DoubleVect::line_size(), max(), Echange_contact_CoviMAC::o_diff, Operateur_Diff_base::op_ext, pe_ext, ref_cast, DoubleTab::resize(), IntTab::resize(), vect_impl::size(), sub_type, Ref_Op_Diff_CoviMAC_base::valeur(), valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), and whm_.
Referenced by update_xwh().
{
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const Conds_lim& cls = la_zcl_poly_->les_conditions_limites();
  int i, j, fb, M, N = equation().inconnue().valeurs().line_size(), n_mono, idx;
  op_ext = { this };//le premier op_ext est l'operateur local
  pe_ext.resize(0, 3), zone.creer_tableau_faces_bord(pe_ext);
  for (pe_ext = -1, i = 0, n_mono = 0, M = N; i < cls.size(); i++) if (sub_type(Echange_contact_CoviMAC, cls[i].valeur())) //on ajoute ceux des Echange_contact
      {
        const Echange_contact_CoviMAC& cl = ref_cast(Echange_contact_CoviMAC, cls[i].valeur());
        const Op_Diff_CoviMAC_base *o_diff = &cl.o_diff.valeur();
        if (std::find(op_ext.begin(), op_ext.end(), o_diff) == op_ext.end()) op_ext.push_back(o_diff);
        M = max(M, o_diff->equation().inconnue().valeurs().line_size()); //M -> nb de composantes maximal
        const Front_VF& fvf = ref_cast(Front_VF, cls[i].frontiere_dis());
        const IntTab& fe_dist = cl.fe_dist();
        for (j = 0, idx = std::find(op_ext.begin(), op_ext.end(), o_diff) - op_ext.begin(); j < fvf.nb_faces_tot(); j++, n_mono++)
          fb = zone.fbord(fvf.num_face(j)), pe_ext(fb, 0) = idx, pe_ext(fb, 1) = fe_dist(j, 1), pe_ext(fb, 2) = n_mono;
      }
  whm_.resize(n_mono, N, M, 2);
}
const DoubleTab& Op_Diff_CoviMAC_base::invh () const [inline]
Definition at line 84 of file Op_Diff_CoviMAC_base.h.
References invh_, nu_a_jour_, and update_nu_invh().
Referenced by update_phif(), and update_xwh().
  {
    if (!nu_a_jour_) update_nu_invh();
    return invh_;
  }
void Op_Diff_CoviMAC_base::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Operateur_base.
Definition at line 70 of file Op_Diff_CoviMAC_base.cpp.
References nu_a_jour_, nu_constant_, phif_a_jour_, t_last_maj_, and xwh_a_jour_.
{
  Operateur_base::mettre_a_jour(t);
// si le champ est constant en temps, alors pas besoin de recalculer nu_ et les interpolations
  if (t <= t_last_maj_) return;
  if (!nu_constant_) nu_a_jour_ = 0, xwh_a_jour_ = 0, phif_a_jour_ = 0;
  t_last_maj_ = t;
}
virtual void Op_Diff_CoviMAC_base::modifier_nu (DoubleTab &) const [inline, virtual]
Definition at line 76 of file Op_Diff_CoviMAC_base.h.
Referenced by update_nu_invh().
{ };
const DoubleTab& Op_Diff_CoviMAC_base::nu () const [inline]
Definition at line 79 of file Op_Diff_CoviMAC_base.h.
References nu_, nu_a_jour_, and update_nu_invh().
Referenced by update_phif(), and update_xwh().
  {
    if (!nu_a_jour_) update_nu_invh();
    return nu_;
  }
Sortie & Op_Diff_CoviMAC_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 56 of file Op_Diff_CoviMAC_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Diff_CoviMAC_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 65 of file Op_Diff_CoviMAC_base.cpp.
{
  return s ;
}
Op_Diff_CoviMAC_base & Op_Diff_CoviMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 50 of file Op_Diff_CoviMAC_base.cpp.
const Op_Diff_CoviMAC_base & Op_Diff_CoviMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 50 of file Op_Diff_CoviMAC_base.cpp.
void Op_Diff_CoviMAC_base::update_nu_invh () const [protected]
Definition at line 282 of file Op_Diff_CoviMAC_base.cpp.
References Process::abort(), ArrOfDouble::addr(), Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), diffusivite(), Op_Diff_Turbulent_base::diffusivite_turbulente(), DoubleTab::dimension(), Objet_U::dimension, DoubleTab::dimension_tot(), Zone_CoviMAC::dist_norm_bord(), Pb_Multiphase::eq_masse, Pb_Multiphase::eq_qdm, MorEqn::equation(), Turbulence_paroi_scal_base::equivalent_distance(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::fbord(), Flux_parietal_base::flux_chaleur(), Equation_base::get_modele(), Op_Diff_Turbulent_base::has_diffusivite_turbulente(), Navier_Stokes_std::inconnue(), Masse_Multiphase::inconnue(), Equation_base::inconnue(), invh_, la_zcl_poly_, la_zone_poly_, DoubleVect::line_size(), Milieu_base::masse_volumique(), max(), modifier_nu(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), O_U_Ptr::non_nul(), nu_, nu_a_jour_, Zone_CoviMAC::nu_dot(), Front_VF::num_face(), Zone_VF::porosite_elem(), Navier_Stokes_std::pression(), ref_cast, vect_impl::size(), sub_type, TURBULENCE, Turbulence_paroi_scal_base::use_equivalent_distance(), valeur(), Ref_Objet_U::valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Don::valeurs(), Champ_Fonc::valeurs(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), and Fluide_base::viscosite_dynamique().
Referenced by Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), invh(), and nu().
{
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const IntTab& f_e = zone.face_voisins();
  const Conds_lim& cls = la_zcl_poly_->les_conditions_limites();
  const DoubleTab& nu_src = diffusivite().valeurs(), &nf = zone.face_normales();
  const DoubleVect& fs = zone.face_surfaces();
  int e, i, j, k, f, fb, m, n, N = equation().inconnue().valeurs().line_size(), N_nu = nu_.line_size(), N_nu_src = nu_src.line_size(), mult = N_nu / N,
                               c_nu = nu_src.dimension_tot(0) == 1, d, db, D = dimension, nf_tot = zone.nb_faces_tot();
  assert(N_nu % N == 0);
  /* nu_ : si necessaire, on doit etendre la champ source */
  if (N_nu == N_nu_src) for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0; n < N_nu; n++) nu_.addr()[N_nu * e +  n] = nu_src(!c_nu * e, n); //facile
  else if (N_nu == N * D && N_nu_src == N) for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0; n < N; n++) for (d = 0; d < D; d++) //diagonal
          nu_(e, n, d) = nu_src(!c_nu * e, n);
  else if (N_nu == N * D * D && (N_nu_src == N || N_nu_src == N * D)) for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0; n < N; n++) //complet
        for (d = 0; d < D; d++) for (db = 0; db < D; db++) nu_(e, n, d, db) = (d == db) * nu_src(!c_nu * e, N_nu_src == N ? n : D * n + d);
  else abort();
  if (has_diffusivite_turbulente()) /* prise en compte de la turbulence */
    {
      const DoubleTab& nut_src = diffusivite_turbulente().valeurs();
      int c_nut = (nut_src.dimension_tot(0) == 1), N_nut_src = nut_src.line_size();
      if (N_nu == N_nut_src) for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0; n < N_nu; n++) nu_.addr()[N_nu * e + n] += nut_src(!c_nut * e, n); //facile
      else if (N_nu == N * D && N_nut_src == N) for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0; n < N; n++) for (d = 0; d < D; d++) //diagonal
              nu_(e, n, d) += nut_src(!c_nut * e, n);
      else if (N_nu == N * D * D && (N_nut_src == N || N_nut_src == N * D)) for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0; n < N; n++) //complet
            for (d = 0; d < D; d++) for (db = 0; db < D; db++) nu_(e, n, d, db) += (d == db) * nut_src(!c_nut * e, N_nut_src == N ? n : D * n + d);
      else abort();
    }
  /* ponderation de nu par la porosite et par alpha (si pb_Multiphase) */
  const DoubleTab *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  for (e = 0; e < zone.nb_elem_tot(); e++) for (n = 0, i = 0; n < N; n++) for (m = 0; m < mult; m++, i++)
        nu_.addr()[N_nu * e + i] *= zone.porosite_elem()(e) * (alp ? max((*alp)(e, n), 1e-8) : 1);
  /* modification par une classe fille */
  modifier_nu(nu_);
  /* resistivite (1 / h) aux faces de bord */
  const RefObjU* modele_turbulence = has_diffusivite_turbulente() ? &equation().get_modele(TURBULENCE) : NULL;
  const Turbulence_paroi_scal_base *loi_par = modele_turbulence && modele_turbulence->non_nul() && sub_type(Modele_turbulence_scal_base,modele_turbulence->valeur()) ?
                                              &ref_cast(Modele_turbulence_scal_base,modele_turbulence->valeur()).loi_paroi().valeur() : NULL;
  /* si Pb_Multiphase et correlation de flux parietal -> invh par la correlation */
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  if (pbm && sub_type(Energie_Multiphase, equation()) && ref_cast(Pb_Multiphase, equation().probleme()).has_correlation("flux_parietal"))
    {
      const Flux_parietal_base& flux = ref_cast(Flux_parietal_base, ref_cast(Pb_Multiphase, equation().probleme()).get_correlation("flux_parietal").valeur());
      const Fluide_base& mil = ref_cast(Fluide_base, equation().milieu());
      const DoubleTab& temp = equation().inconnue().valeurs(), &press = pbm->eq_qdm.pression().valeurs(), &alpha = pbm->eq_masse.inconnue().valeurs(),
                       &vit = pbm->eq_qdm.inconnue().valeurs(), &lambda = mil.conductivite().valeurs(),
                        &mu = mil.viscosite_dynamique().valeurs(), &rho = mil.masse_volumique().valeurs(), &Cp = mil.capacite_calorifique().valeurs();
      int c_lambda = lambda.dimension(0) == 1, c_mu = mu.dimension(0) == 1, c_rho = rho.dimension(0) == 1, c_Cp = Cp.dimension(0) == 1;
      DoubleTrav nv(N); //normes des vitesses
      for (i = 0; i < cls.size(); i++)
        {
          const Front_VF& fvf = ref_cast(Front_VF, cls[i].frontiere_dis());
          for (j = 0; j < fvf.nb_faces_tot(); j++)
            {
              /* FIXME: ne marche que pour les flux lineaires */
              f = fvf.num_face(j), e = f_e(f, 0), fb = zone.fbord(f);
              for (nv = 0, d = 0, k = nf_tot + D * e; d < D; d++, k++) for (n = 0; n < N; n++) nv(n) += std::pow(vit(k, n), 2);
              for (n = 0; n < N; n++) nv(n) = sqrt(nv(n));
              flux.flux_chaleur(N, zone.dist_norm_bord(f), zone.dist_norm_bord(f), &alpha(e, 0), &temp(e, 0), press(e, 0), nv.addr(), 0,
                                &lambda(!c_lambda * e, 0), &mu(!c_mu * e, 0), &rho(!c_rho * e, 0), &Cp(!c_Cp * e, 0),
                                NULL, NULL, NULL, NULL, NULL, &invh_(fb, 0)); //stocke le coefficient d'echange dans invh_
              for (n = 0; n < N; n++) invh_(fb, n) = 1. / max(invh_(fb, n), 1e-10); //pour eviter invh_ = +inf
            }
        }
    }
  else if (loi_par && loi_par->use_equivalent_distance()) for (i = 0; i < cls.size(); i++) /* si loi de paroi : invh par equivalent_distance */
      {
        const Front_VF& fvf = ref_cast(Front_VF, cls[i].frontiere_dis());
        for (j = 0; j < fvf.nb_faces_tot(); j++) for (f = fvf.num_face(j), fb = zone.fbord(f), n = 0; n < N; n++)
            invh_(fb, n) = (loi_par->equivalent_distance(i, j) - zone.dist_norm_bord(f)) * fs(f) * fs(f) / zone.nu_dot(&nu_, f_e(f, 0), n, &nf(f, 0), &nf(f, 0));
      }
  else invh_ = 0;
  nu_a_jour_ = 1;
}
void Op_Diff_CoviMAC_base::update_phif (int full_stencil = 0) const
Definition at line 371 of file Op_Diff_CoviMAC_base.cpp.
References MorEqn::equation(), Equation_base::inconnue(), invh(), la_zcl_poly_, la_zone_poly_, nu(), pe_ext, phif_a_jour_, phif_c, phif_d, phif_e, phif_pc, phif_pe, phif_w, ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), wh(), whm(), and xh().
{
  if (!full_stencil && phif_a_jour_) return; //deja fait, sauf si on demande tout le stencil
  const Champ_Inc_base& ch = equation().inconnue().valeur();
  const IntTab& fcl = sub_type(Champ_Face_CoviMAC, ch) ? ref_cast(Champ_Face_CoviMAC, ch).fcl() : ref_cast(Champ_P0_CoviMAC, ch).fcl();
  la_zone_poly_->fgrad(la_zcl_poly_->les_conditions_limites(), fcl, &nu(), &invh(), xh(), wh(), &whm(),
                       &pe_ext, 1, full_stencil, phif_w, phif_d, phif_e, phif_c, &phif_pe, &phif_pc);
  phif_a_jour_ = 1;
}
void Op_Diff_CoviMAC_base::update_xwh () const [protected]
Definition at line 364 of file Op_Diff_CoviMAC_base.cpp.
References init_op_ext(), invh(), la_zcl_poly_, la_zone_poly_, nu(), op_ext_init_, wh_, whm_, xh_, and xwh_a_jour_.
Referenced by wh(), whm(), and xh().
{
  if (!op_ext_init_) init_op_ext(), op_ext_init_ = 1;
  la_zone_poly_->harmonic_points(la_zcl_poly_->les_conditions_limites(), 0, 1, &nu(), &invh(), xh_, wh_, &whm_);
  xwh_a_jour_ = 1;
}
const DoubleTab& Op_Diff_CoviMAC_base::wh () const [inline]
Definition at line 96 of file Op_Diff_CoviMAC_base.h.
References update_xwh(), wh_, and xwh_a_jour_.
Referenced by update_phif().
  {
    if (!xwh_a_jour_) update_xwh();
    return wh_;
  }
const DoubleTab& Op_Diff_CoviMAC_base::whm () const [inline]
Definition at line 101 of file Op_Diff_CoviMAC_base.h.
References update_xwh(), whm_, and xwh_a_jour_.
Referenced by update_phif().
  {
    if (!xwh_a_jour_) update_xwh();
    return whm_;
  }
const DoubleTab& Op_Diff_CoviMAC_base::xh () const [inline]
Definition at line 91 of file Op_Diff_CoviMAC_base.h.
References update_xwh(), xh_, and xwh_a_jour_.
Referenced by update_phif().
  {
    if (!xwh_a_jour_) update_xwh();
    return xh_;
  }
Member Data Documentation
Ref_Champ_base Op_Diff_CoviMAC_base::diffusivite_ [protected]
Definition at line 119 of file Op_Diff_CoviMAC_base.h.
Referenced by associer_diffusivite(), and diffusivite().
SFichier Op_Diff_CoviMAC_base::Flux [mutable, protected]
Definition at line 136 of file Op_Diff_CoviMAC_base.h.
Referenced by impr().
SFichier Op_Diff_CoviMAC_base::Flux_moment [mutable, protected]
Definition at line 136 of file Op_Diff_CoviMAC_base.h.
Referenced by impr().
SFichier Op_Diff_CoviMAC_base::Flux_sum [mutable, protected]
Definition at line 136 of file Op_Diff_CoviMAC_base.h.
Referenced by impr().
const Type_info Op_Diff_CoviMAC_base::info_obj [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, and Op_Diff_CoviMAC_Face.
Definition at line 58 of file Op_Diff_CoviMAC_base.h.
DoubleTab Op_Diff_CoviMAC_base::invh_ [mutable, protected]
Definition at line 125 of file Op_Diff_CoviMAC_base.h.
Referenced by completer(), invh(), and update_nu_invh().
Ref_Zone_Cl_CoviMAC Op_Diff_CoviMAC_base::la_zcl_poly_ [protected]
Definition at line 118 of file Op_Diff_CoviMAC_base.h.
Referenced by associer(), impr(), init_op_ext(), update_nu_invh(), update_phif(), and update_xwh().
Ref_Zone_CoviMAC Op_Diff_CoviMAC_base::la_zone_poly_ [protected]
Definition at line 117 of file Op_Diff_CoviMAC_base.h.
Referenced by associer(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), completer(), impr(), init_op_ext(), update_nu_invh(), update_phif(), and update_xwh().
DoubleTab Op_Diff_CoviMAC_base::nu_ [mutable, protected]
Definition at line 125 of file Op_Diff_CoviMAC_base.h.
Referenced by Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), completer(), nu(), and update_nu_invh().
int Op_Diff_CoviMAC_base::nu_a_jour_ = 0 [mutable, protected]
Definition at line 134 of file Op_Diff_CoviMAC_base.h.
Referenced by invh(), mettre_a_jour(), nu(), and update_nu_invh().
int Op_Diff_CoviMAC_base::nu_constant_ [mutable, protected]
Definition at line 134 of file Op_Diff_CoviMAC_base.h.
Referenced by completer(), and mettre_a_jour().
int Op_Diff_CoviMAC_base::op_ext_init_ = 0 [mutable, protected]
Definition at line 134 of file Op_Diff_CoviMAC_base.h.
Referenced by update_xwh().
IntTab Op_Diff_CoviMAC_base::pe_ext [mutable]
tableau aux faces de bord : (indice dans op_ext, indice d'element) pour les faces de type Echange_contact
Definition at line 66 of file Op_Diff_CoviMAC_base.h.
Referenced by init_op_ext(), and update_phif().
int Op_Diff_CoviMAC_base::phif_a_jour_ = 0 [mutable, protected]
Definition at line 134 of file Op_Diff_CoviMAC_base.h.
Referenced by mettre_a_jour(), and update_phif().
DoubleTab Op_Diff_CoviMAC_base::phif_c [mutable]
Definition at line 111 of file Op_Diff_CoviMAC_base.h.
Referenced by update_phif().
IntTab Op_Diff_CoviMAC_base::phif_d [mutable]
Definition at line 110 of file Op_Diff_CoviMAC_base.h.
Referenced by update_phif().
IntTab Op_Diff_CoviMAC_base::phif_e [mutable]
Definition at line 110 of file Op_Diff_CoviMAC_base.h.
Referenced by update_phif().
DoubleTab Op_Diff_CoviMAC_base::phif_pc [mutable]
Definition at line 111 of file Op_Diff_CoviMAC_base.h.
Referenced by update_phif().
IntTab Op_Diff_CoviMAC_base::phif_pe [mutable]
Definition at line 110 of file Op_Diff_CoviMAC_base.h.
Referenced by update_phif().
DoubleTab Op_Diff_CoviMAC_base::phif_w [mutable]
Definition at line 111 of file Op_Diff_CoviMAC_base.h.
Referenced by completer(), and update_phif().
double Op_Diff_CoviMAC_base::t_last_maj_ = -1e10 [protected]
Definition at line 121 of file Op_Diff_CoviMAC_base.h.
Referenced by mettre_a_jour().
DoubleTab Op_Diff_CoviMAC_base::wh_ [mutable, protected]
Definition at line 132 of file Op_Diff_CoviMAC_base.h.
Referenced by completer(), update_xwh(), and wh().
DoubleTab Op_Diff_CoviMAC_base::whm_ [mutable, protected]
Definition at line 132 of file Op_Diff_CoviMAC_base.h.
Referenced by init_op_ext(), update_xwh(), and whm().
DoubleTab Op_Diff_CoviMAC_base::xh_ [mutable, protected]
Definition at line 132 of file Op_Diff_CoviMAC_base.h.
Referenced by completer(), update_xwh(), and xh().
int Op_Diff_CoviMAC_base::xwh_a_jour_ = 0 [mutable, protected]
Definition at line 134 of file Op_Diff_CoviMAC_base.h.
Referenced by mettre_a_jour(), update_xwh(), wh(), whm(), and xh().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_base.h
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_base.cpp