TRUST: TRUST_Vector< _TRUST_TABL_, _TYPE_ > Class Template Reference
TRUST_Vector< _TRUST_TABL_, _TYPE_ > Class Template Reference
#include <TRUST_Vector.h>
Public Member Functions
TRUST_Vector ()
TRUST_Vector (int i)
TRUST_Vector (const TRUST_Vector &avect)
const _TRUST_TABL_< _TYPE_ > & operator[] (int i) const
_TRUST_TABL_< _TYPE_ > & operator[] (int i)
const _TRUST_TABL_< _TYPE_ > & operator() (int i) const
_TRUST_TABL_< _TYPE_ > & operator() (int i)
TRUST_Vector & operator= (const TRUST_Vector &avect)
Entree & lit (Entree &s)
_TRUST_TABL_< _TYPE_ > & add (const _TRUST_TABL_< _TYPE_ > &data_to_add)
_TRUST_TABL_< _TYPE_ > & add ()
void add (const TRUST_Vector &data_to_add)
Public Member Functions inherited from vect_impl
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
vect_impl ()
int size () const
void build_vect_impl (int)
const Objet_U & operator[] (int) const
Objet_U & operator[] (int)
vect_impl (const vect_impl &)
~vect_impl () override
vect_impl & operator= (const vect_impl &)
void dimensionner (int)
void dimensionner_force (int)
void reset ()
vect_impl & add (const Objet_U &)
vect_impl & add (const vect_impl &)
Entree & lit (Entree &)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Protected Member Functions
unsigned taille_memoire () const override
int duplique () const override
Objet_U * cree_une_instance () const override
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Sortie & printOn (Sortie &s) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &s) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from vect_impl
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual Objet_U * cree_une_instance () const
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Static Public Member Functions inherited from vect_impl
static Objet_U * cree_instance ()
static const Type_info * info ()
static vect_impl & self_cast (Objet_U &)
static const vect_impl & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from vect_impl
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Attributes inherited from vect_impl
int sz
DerObjU * data
Detailed Description
template<template< typename > class _TRUST_TABL_, typename _TYPE_>
class TRUST_Vector< _TRUST_TABL_, _TYPE_ >
Definition at line 27 of file TRUST_Vector.h.
Constructor & Destructor Documentation
TRUST_Vector() [1/3]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > TRUST_Vector< _TRUST_TABL_, _TYPE_ >::TRUST_Vector () inline
Definition at line 55 of file TRUST_Vector.h.
: vect_impl() { }
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::duplique().
TRUST_Vector() [2/3]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > TRUST_Vector< _TRUST_TABL_, _TYPE_ >::TRUST_Vector (int i) inline
Definition at line 56 of file TRUST_Vector.h.
{ build_vect_impl(i); }
References vect_impl::build_vect_impl().
TRUST_Vector() [3/3]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > TRUST_Vector< _TRUST_TABL_, _TYPE_ >::TRUST_Vector (const TRUST_Vector< _TRUST_TABL_, _TYPE_ > & avect) inline
Definition at line 57 of file TRUST_Vector.h.
: vect_impl(avect) { }
Member Function Documentation
add() [1/3]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > _TRUST_TABL_< _TYPE_ > & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add () inline
Definition at line 80 of file TRUST_Vector.h.
{ return add(_TRUST_TABL_<_TYPE_>()); }
References TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add().
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add().
add() [2/3]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > _TRUST_TABL_< _TYPE_ > & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add (const _TRUST_TABL_< _TYPE_ > & data_to_add) inline
Definition at line 74 of file TRUST_Vector.h.
  {
    vect_impl::add(data_to_add);
    return (*this)[size() - 1];
  }
References vect_impl::add(), and vect_impl::size().
Referenced by Debog_Pb::add_renum_item(), Zone::chercher_elements(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Champ_Fonc_Tabule::readOn(), and Champ_Fonc_Tabule_Morceaux::readOn().
add() [3/3]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > void TRUST_Vector< _TRUST_TABL_, _TYPE_ >::add (const TRUST_Vector< _TRUST_TABL_, _TYPE_ > & data_to_add) inline
Definition at line 81 of file TRUST_Vector.h.
{ vect_impl::add(data_to_add); }
References vect_impl::add().
cree_une_instance()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > Objet_U * TRUST_Vector< _TRUST_TABL_, _TYPE_ >::cree_une_instance () const inline override protected virtual
methhode surcharge par les classes filles pour fournir la bonne
instance aux constructeurs au readOn....
Reimplemented from vect_impl.
Definition at line 44 of file TRUST_Vector.h.
  {
    _TRUST_TABL_<_TYPE_> *instan = new _TRUST_TABL_<_TYPE_>();
    return instan;
  }
duplique()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > int TRUST_Vector< _TRUST_TABL_, _TYPE_ >::duplique () const inline override protected virtual
Implements Objet_U.
Definition at line 33 of file TRUST_Vector.h.
  {
    TRUST_Vector *xxx = new TRUST_Vector(*this);
    if (!xxx)
      {
        Cerr << "Not enough memory " << finl;
        Process::exit();
      }
    return xxx->numero();
  }
References Cerr, Process::exit(), finl, Objet_U::numero(), and TRUST_Vector< _TRUST_TABL_, _TYPE_ >::TRUST_Vector().
lit()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > Entree & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::lit (Entree & s) inline
Definition at line 72 of file TRUST_Vector.h.
{ return vect_impl::lit(s); }
References vect_impl::lit().
operator()() [1/2]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > _TRUST_TABL_< _TYPE_ > & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator() (int i) inline
Definition at line 64 of file TRUST_Vector.h.
{ return operator[](i); }
References TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator[]().
operator()() [2/2]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > const _TRUST_TABL_< _TYPE_ > & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator() (int i) const inline
Definition at line 63 of file TRUST_Vector.h.
{ return operator[](i); }
References TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator[]().
operator=()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > TRUST_Vector & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator= (const TRUST_Vector< _TRUST_TABL_, _TYPE_ > & avect) inline
Definition at line 66 of file TRUST_Vector.h.
  {
    vect_impl::operator=(avect);
    return *this;
  }
References vect_impl::operator=().
operator[]() [1/2]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > _TRUST_TABL_< _TYPE_ > & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator[] (int i) inline
Definition at line 61 of file TRUST_Vector.h.
{ return static_cast<_TRUST_TABL_<_TYPE_>&>(vect_impl::operator[](i)); }
References vect_impl::operator[]().
operator[]() [2/2]
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > const _TRUST_TABL_< _TYPE_ > & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator[] (int i) const inline
Definition at line 60 of file TRUST_Vector.h.
{ return static_cast<const _TRUST_TABL_<_TYPE_>&>(vect_impl::operator[](i)); }
References vect_impl::operator[]().
Referenced by TRUST_Vector< _TRUST_TABL_, _TYPE_ >::operator()().
printOn()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > Sortie & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 50 of file TRUST_Vector.h.
{ return vect_impl::printOn(s); }
References vect_impl::printOn().
readOn()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > Entree & TRUST_Vector< _TRUST_TABL_, _TYPE_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 52 of file TRUST_Vector.h.
{ return vect_impl::readOn(s); }
References vect_impl::readOn().
taille_memoire()
template<template< typename > class _TRUST_TABL_, typename _TYPE_ > unsigned TRUST_Vector< _TRUST_TABL_, _TYPE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
Definition at line 31 of file TRUST_Vector.h.
{ throw; }
The documentation for this class was generated from the following file:
src/Kernel/Math/TRUST_Vector.h