TRUST: Ref_Mod_turb_hyd_base Class Reference
Ref_Mod_turb_hyd_base Class Reference
#include <Ref_Mod_turb_hyd_base.h>
Public Member Functions
~Ref_Mod_turb_hyd_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Mod_turb_hyd_base ()
Ref_Mod_turb_hyd_base (const Mod_turb_hyd_base &)
Ref_Mod_turb_hyd_base (const Ref_Mod_turb_hyd_base &)
const Mod_turb_hyd_base & valeur () const
Mod_turb_hyd_base & valeur ()
const Mod_turb_hyd_base * operator-> () const
Mod_turb_hyd_base * operator-> ()
const Ref_Mod_turb_hyd_base & operator= (const Mod_turb_hyd_base &)
const Ref_Mod_turb_hyd_base & operator= (const Ref_Mod_turb_hyd_base &)
operator const Mod_turb_hyd_base & () const
operator Mod_turb_hyd_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Mod_turb_hyd_base & self_cast (Objet_U &)
static const
Ref_Mod_turb_hyd_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Mod_turb_hyd_base * pointeur_
Detailed Description
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
Constructor & Destructor Documentation
Ref_Mod_turb_hyd_base::~Ref_Mod_turb_hyd_base ()
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Ref_Mod_turb_hyd_base::Ref_Mod_turb_hyd_base ()
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Ref_Mod_turb_hyd_base::Ref_Mod_turb_hyd_base (const Mod_turb_hyd_base & t)
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Ref_Mod_turb_hyd_base::Ref_Mod_turb_hyd_base (const Ref_Mod_turb_hyd_base & t)
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Member Function Documentation
Objet_U * Ref_Mod_turb_hyd_base::cree_instance () [static]
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
int Ref_Mod_turb_hyd_base::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Type_info * Ref_Mod_turb_hyd_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Type_info & Ref_Mod_turb_hyd_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Type_info * Ref_Mod_turb_hyd_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Ref_Mod_turb_hyd_base::operator const Mod_turb_hyd_base & () const
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Ref_Mod_turb_hyd_base::operator Mod_turb_hyd_base & ()
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Mod_turb_hyd_base * Ref_Mod_turb_hyd_base::operator-> () const [inline]
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
Mod_turb_hyd_base * Ref_Mod_turb_hyd_base::operator-> () [inline]
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
const Ref_Mod_turb_hyd_base & Ref_Mod_turb_hyd_base::operator= (const Ref_Mod_turb_hyd_base & t)
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Ref_Mod_turb_hyd_base & Ref_Mod_turb_hyd_base::operator= (const Mod_turb_hyd_base & t)
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Sortie & Ref_Mod_turb_hyd_base::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Entree & Ref_Mod_turb_hyd_base::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Ref_Mod_turb_hyd_base & Ref_Mod_turb_hyd_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
Ref_Mod_turb_hyd_base & Ref_Mod_turb_hyd_base::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
void Ref_Mod_turb_hyd_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
unsigned Ref_Mod_turb_hyd_base::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Mod_turb_hyd_base.cpp.
const Mod_turb_hyd_base & Ref_Mod_turb_hyd_base::valeur () const [inline]
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_base::mettre_a_jour(), Op_Dift_VDF_Face_Axi::mettre_a_jour(), Eval_Dift_VDF_var_Face::mettre_a_jour(), Turbulence_paroi::readOn(), Eval_Dift_VDF_var_Face::uses_wall(), and Eval_Dift_VDF_const_Face::uses_wall().
Mod_turb_hyd_base & Ref_Mod_turb_hyd_base::valeur () [inline]
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
Member Data Documentation
const Type_info Ref_Mod_turb_hyd_base::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
Mod_turb_hyd_base* Ref_Mod_turb_hyd_base::pointeur_ [private]
Definition at line 28 of file Ref_Mod_turb_hyd_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Ref_Mod_turb_hyd_base.h
src/ThHyd/Modele_turbulence_base/Ref_Mod_turb_hyd_base.cpp