TRUST: Champ_Gen_de_Champs_Gen Class Reference
Champ_Gen_de_Champs_Gen Class Reference
Classe de base des champs generiques ayant comme source d'autres champs generiques
L'utilisation des methodes de la classe repose sur un principe de recursivite
Une instruction sera de maniere generale appliquee (ou deleguer) a un champ generique
source qui lui meme appliquera (ou deleguera) l action.
#include <Champ_Gen_de_Champs_Gen.h>
Public Member Functions
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
virtual void reset ()
virtual int sauvegarder (Sortie &os) const
sauvegarde des differentes sources
virtual int reprendre (Entree &is)
reprise des differentes sources
virtual void completer (const Postraitement_base &post)
virtual void mettre_a_jour (double temps)
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int &nb_comp, Champ_Fonc &es_tmp) const
virtual const
Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
void nommer_sources ()
virtual void nommer_source ()
virtual int get_info_type_post () const
virtual const
Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual void fixer_serie (const double &t1, const double &t2)
virtual void fixer_tstat_deb (const double &t1, const double &t2)
virtual void lire_bidon (Entree &is) const
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const
Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Private Attributes
List_Champ_Generique sources_
Detailed Description
Classe de base des champs generiques ayant comme source d'autres champs generiques
L'utilisation des methodes de la classe repose sur un principe de recursivite
Une instruction sera de maniere generale appliquee (ou deleguer) a un champ generique
source qui lui meme appliquera (ou deleguera) l action.
Definition at line 45 of file Champ_Gen_de_Champs_Gen.h.
Constructor & Destructor Documentation
Champ_Gen_de_Champs_Gen::Champ_Gen_de_Champs_Gen ()
Definition at line 29 of file Champ_Gen_de_Champs_Gen.cpp.
Champ_Gen_de_Champs_Gen::~Champ_Gen_de_Champs_Gen ()
Definition at line 29 of file Champ_Gen_de_Champs_Gen.cpp.
Member Function Documentation
void Champ_Gen_de_Champs_Gen::completer (const Postraitement_base & post) [virtual]
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, and Champ_Generique_modifier_pour_QC.
Definition at line 232 of file Champ_Gen_de_Champs_Gen.cpp.
References List_Ref_Champ_Generique_base::add(), Champ_Generique_base::completer(), Postraitement::get_champ_post(), get_nb_sources(), get_ref_pb_base(), Probleme_base::le_nom(), Champ_Generique_base::nom_pb_, nommer_source(), noms_sources_ref_, REF, ref_cast, set_source(), liste::size(), sources_reference_, and liste::vide().
{
  int n_sources_ref=noms_sources_ref_.size();
  if ( n_sources_ref!=sources_reference_.size())
    {
      sources_reference_.vide();
      for (int i=0; i<n_sources_ref; i++)
        {
          REF(Champ_Generique_base)& source_ref=sources_reference_.add(REF(Champ_Generique_base)());
          const Postraitement& postraitement =ref_cast(Postraitement,post);
// const Probleme_base& pb = ref_cast(Postraitement,post).probleme();
          source_ref = postraitement.get_champ_post(noms_sources_ref_[i]);
        }
    }
  const int n = get_nb_sources();
  for (int i = n_sources_ref ; i < n; i++)
    {
      Champ_Generique_base& source_a_completer = ref_cast(Champ_Generique_base,set_source(i));
      source_a_completer.completer(post);
    }
  const Probleme_base& pb = get_ref_pb_base();
  const Nom& nom_pb = pb.le_nom();
  nom_pb_ = nom_pb;
  nommer_source();
}
int Champ_Gen_de_Champs_Gen::comprend_champ_post (const Motcle & identifiant) const [virtual]
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Moyenne.
Definition at line 473 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::comprend_champ_post(), and get_source().
Referenced by Champ_Generique_Moyenne::comprend_champ_post().
{
  if (Champ_Generique_base::comprend_champ_post(identifiant))
    return 1;
  else if (get_source(0).comprend_champ_post(identifiant))
    return 1;
  return 0;
}
Champ_Fonc & Champ_Gen_de_Champs_Gen::creer_espace_stockage (const Nature_du_champ & nature, const int & nb_comp, Champ_Fonc & es_tmp) const [virtual]
Reimplemented in Champ_Generique_Morceau_Equation.
Definition at line 145 of file Champ_Gen_de_Champs_Gen.cpp.
References Vect_Nom::add(), Discretisation_base::discretiser_champ(), get_directive_pour_discr(), get_discretisation(), get_ref_zcl_dis_base(), get_ref_zone_dis_base(), and get_time().
Referenced by Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Transformation::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Gradient::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), and Champ_Generique_Divergence::get_champ_without_evaluation().
{
  Noms noms;
  Noms unites;
  for (int c=0; c<nb_comp; c++)
    {
// noms.add("bidon");
      unites.add("bidon");
    }
  noms.add("bidon");
  double temps;
  temps = get_time();
  const Discretisation_base&  discr = get_discretisation();
  Motcle directive = get_directive_pour_discr();
  const Zone_dis_base& zone_dis = get_ref_zone_dis_base();
  discr.discretiser_champ(directive,zone_dis,nature,noms,unites,nb_comp,temps,es_tmp);
  if (directive=="pression")
    {
      const  Zone_Cl_dis_base& zcl = get_ref_zcl_dis_base();
      es_tmp->completer(zcl);
    }
  return es_tmp;
}
virtual int Champ_Gen_de_Champs_Gen::duplique () const [pure virtual]
Implements Champ_Generique_base.
Implemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
void Champ_Gen_de_Champs_Gen::fixer_serie (const double & t1, const double & t2) [virtual]
Reimplemented in Champ_Generique_Statistiques_base.
Definition at line 410 of file Champ_Gen_de_Champs_Gen.cpp.
References fixer_serie(), get_nb_sources(), get_source(), ref_cast, set_source(), and sub_type.
Referenced by fixer_serie(), and Postraitement::postraiter().
{
  const int n = get_nb_sources();;
  for (int i = 0; i < n; i++)
    {
      if (sub_type(Champ_Gen_de_Champs_Gen,get_source(i)))
        {
          Champ_Gen_de_Champs_Gen& source = ref_cast(Champ_Gen_de_Champs_Gen,set_source(i));
          source.fixer_serie(t1,t2);
        }
    }
}
void Champ_Gen_de_Champs_Gen::fixer_tstat_deb (const double & t1, const double & t2) [virtual]
Reimplemented in Champ_Generique_Statistiques_base.
Definition at line 423 of file Champ_Gen_de_Champs_Gen.cpp.
References fixer_tstat_deb(), get_nb_sources(), get_source(), ref_cast, set_source(), and sub_type.
Referenced by fixer_tstat_deb(), and Postraitement::reprendre().
{
  const int n = get_nb_sources();;
  for (int i = 0; i < n; i++)
    {
      if (sub_type(Champ_Gen_de_Champs_Gen,get_source(i)))
        {
          Champ_Gen_de_Champs_Gen& source = ref_cast(Champ_Gen_de_Champs_Gen,set_source(i));
          source.fixer_tstat_deb(t1,t2);
        }
    }
}
const Champ_Generique_base & Champ_Gen_de_Champs_Gen::get_champ_post (const Motcle & nom) const [virtual]
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Moyenne.
Definition at line 450 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_champ_post(), get_source(), and REF.
{
  REF(Champ_Generique_base) ref_champ;
  try
    {
      return Champ_Generique_base::get_champ_post(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  try
    {
      return get_source(0).get_champ_post(nom);
    }
  catch (Champs_compris_erreur)
    {
    }
  throw Champs_compris_erreur();
  return ref_champ;
}
void Champ_Gen_de_Champs_Gen::get_copy_connectivity (Entity index1, Entity index2, IntTab & tab) const [virtual]
Reimplemented from Champ_Generique_base.
Definition at line 347 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_copy_connectivity(), and get_source().
{
  get_source(0).get_copy_connectivity(index1,index2,tab);
}
void Champ_Gen_de_Champs_Gen::get_copy_coordinates (DoubleTab & coordinates) const [virtual]
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Interpolation.
Definition at line 337 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_copy_coordinates(), and get_source().
{
  get_source(0).get_copy_coordinates(coordinates);
}
void Champ_Gen_de_Champs_Gen::get_copy_domain (Domaine & domain) const [virtual]
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Extraction, and Champ_Generique_Interpolation.
Definition at line 317 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_copy_domain(), and get_source().
{
  return get_source(0).get_copy_domain(domain);
}
void Champ_Gen_de_Champs_Gen::get_copy_values (DoubleTab & values) const [virtual]
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Interpolation.
Definition at line 300 of file Champ_Gen_de_Champs_Gen.cpp.
References get_ref_values().
{
  const DoubleTab& val = get_ref_values();
// Cree une copie du tableau
  values = val;
}
int Champ_Gen_de_Champs_Gen::get_dimension () const [virtual]
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
Reimplemented from Champ_Generique_base.
Definition at line 261 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_dimension(), and get_source().
{
  return get_source(0).get_dimension();
}
const Motcle Champ_Gen_de_Champs_Gen::get_directive_pour_discr () const [virtual]
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, and Champ_Generique_Transformation.
Definition at line 367 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_directive_pour_discr(), and get_source().
Referenced by creer_espace_stockage(), Champ_Generique_Tparoi_VEF::get_champ(), and Champ_Generique_Tparoi_VEF::get_champ_without_evaluation().
{
  return get_source(0).get_directive_pour_discr();
}
const Discretisation_base & Champ_Gen_de_Champs_Gen::get_discretisation () const [virtual]
Reimplemented from Champ_Generique_base.
Definition at line 362 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_discretisation(), and get_source().
Referenced by Champ_Generique_Morceau_Equation::creer_espace_stockage(), creer_espace_stockage(), Champ_Generique_Tparoi_VEF::get_champ(), and Champ_Generique_Tparoi_VEF::get_champ_without_evaluation().
{
  return get_source(0).get_discretisation();
}
const Type_info * Champ_Gen_de_Champs_Gen::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 29 of file Champ_Gen_de_Champs_Gen.cpp.
int Champ_Gen_de_Champs_Gen::get_info_type_post () const [virtual]
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation.
Definition at line 403 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_info_type_post(), and get_source().
{
  return get_source(0).get_info_type_post();
}
Entity Champ_Gen_de_Champs_Gen::get_localisation (const int index = -1) const [virtual]
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Divergence, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Transformation, and Champ_Post_Operateur_Eqn.
Definition at line 290 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_localisation(), and get_source().
Referenced by Champ_Generique_Statistiques_base::completer_post_statistiques().
{
  return get_source(0).get_localisation(index);
}
int Champ_Gen_de_Champs_Gen::get_nb_sources () const [virtual]
Definition at line 208 of file Champ_Gen_de_Champs_Gen.cpp.
References liste::size(), sources_, and sources_reference_.
Referenced by Postraitement::cherche_stat_dans_les_sources(), Champ_Generique_Transformation::completer(), Champ_Generique_Interpolation::completer(), completer(), fixer_serie(), fixer_tstat_deb(), Champ_Generique_Transformation::get_champ(), lire_bidon(), nommer_sources(), Champ_Generique_Transformation::preparer_macro(), and Champ_Generique_Extraction::readOn().
{
  return sources_reference_.size()+sources_.size();
}
const Noms Champ_Gen_de_Champs_Gen::get_property (const Motcle & query) const [virtual]
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, and Champ_Generique_Tparoi_VEF.
Definition at line 272 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_property(), get_source(), Champ_Generique_base::nom_post_, and Motcles::search().
{
  Motcles motcles(1);
  motcles[0] = "nom";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms mots(1);
        mots[0] = nom_post_;
        return mots;
        break;
      }
    }
  return get_source(0).get_property(query);
}
void Champ_Gen_de_Champs_Gen::get_property_names (Motcles & list) const [virtual]
Renvoie la liste des "query" possibles pour le champ.
Reimplemented from Champ_Generique_base.
Definition at line 266 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_property_names(), and get_source().
{
  get_source(0).get_property_names(list);
}
const IntTab & Champ_Gen_de_Champs_Gen::get_ref_connectivity (Entity index1, Entity index2) const [virtual]
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
Reimplemented from Champ_Generique_base.
Definition at line 342 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_connectivity(), and get_source().
{
  return get_source(0).get_ref_connectivity(index1,index2);
}
const DoubleTab & Champ_Gen_de_Champs_Gen::get_ref_coordinates () const [virtual]
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Interpolation.
Definition at line 332 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_coordinates(), and get_source().
{
  return get_source(0).get_ref_coordinates();
}
const Domaine & Champ_Gen_de_Champs_Gen::get_ref_domain () const [virtual]
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Extraction, and Champ_Generique_Interpolation.
Definition at line 312 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_domain(), and get_source().
Referenced by Champ_Generique_Transformation::get_champ().
{
  return get_source(0).get_ref_domain();
}
const Probleme_base & Champ_Gen_de_Champs_Gen::get_ref_pb_base () const [virtual]
Reimplemented from Champ_Generique_base.
Definition at line 357 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_pb_base(), and get_source().
Referenced by Champ_Generique_Moyenne::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Divergence::completer(), Champ_Generique_Correlation::completer(), completer(), Champ_Generique_Interpolation::discretiser_domaine(), and Champ_Generique_Extraction::discretiser_domaine().
{
  return get_source(0).get_ref_pb_base();
}
const DoubleTab & Champ_Gen_de_Champs_Gen::get_ref_values () const [virtual]
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Interpolation.
Definition at line 295 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_values(), and get_source().
Referenced by get_copy_values().
{
  return get_source(0).get_ref_values();
}
const Zone_Cl_dis_base & Champ_Gen_de_Champs_Gen::get_ref_zcl_dis_base () const [virtual]
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
Reimplemented from Champ_Generique_base.
Definition at line 327 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_zcl_dis_base(), and get_source().
Referenced by Champ_Generique_Morceau_Equation::creer_espace_stockage(), and creer_espace_stockage().
{
  return get_source(0).get_ref_zcl_dis_base();
}
const Zone_dis_base & Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base () const [virtual]
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Extraction, and Champ_Generique_Interpolation.
Definition at line 322 of file Champ_Gen_de_Champs_Gen.cpp.
References Champ_Generique_base::get_ref_zone_dis_base(), and get_source().
Referenced by Champ_Generique_Moyenne::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Morceau_Equation::creer_espace_stockage(), creer_espace_stockage(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), and Champ_Generique_Transformation::preparer_macro().
{
  return get_source(0).get_ref_zone_dis_base();
}
Champ_Generique & Champ_Gen_de_Champs_Gen::get_set_source () [virtual]
Definition at line 126 of file Champ_Gen_de_Champs_Gen.cpp.
References List_Champ_Generique::add(), liste::size(), and sources_.
{
  if (sources_.size() < 1)
    sources_.add(Champ_Generique());
  return sources_[0];
}
List_Champ_Generique & Champ_Gen_de_Champs_Gen::get_set_sources () [virtual]
Definition at line 121 of file Champ_Gen_de_Champs_Gen.cpp.
References sources_.
Referenced by Champ_Generique_Transformation::completer().
{
  return sources_;
}
const Champ_Generique_base & Champ_Gen_de_Champs_Gen::get_source (int i) const [virtual]
Reimplemented in Champ_Generique_Predefini.
Definition at line 175 of file Champ_Gen_de_Champs_Gen.cpp.
References Cerr, Process::exit(), finl, noms_sources_ref_, Objet_U::que_suis_je(), liste::size(), sources_, sources_reference_, List_Champ_Generique::valeur(), and List_Ref_Champ_Generique_base::valeur().
Referenced by Postraitement::cherche_stat_dans_les_sources(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Transformation::completer(), Champ_Generique_Moyenne::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Interpolation::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Divergence::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Moyenne::comprend_champ_post(), comprend_champ_post(), Postraitement::creer_champ_post_stat(), Champ_Generique_Transformation::creer_expression_macro(), fixer_serie(), fixer_tstat_deb(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Moyenne::get_champ_post(), get_champ_post(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Gradient::get_champ_without_evaluation(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Generique_Divergence::get_champ_without_evaluation(), get_copy_connectivity(), get_copy_coordinates(), get_copy_domain(), get_dimension(), get_directive_pour_discr(), get_discretisation(), get_info_type_post(), get_localisation(), Champ_Generique_Tparoi_VEF::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Divergence::get_property(), get_property(), get_property_names(), get_ref_connectivity(), get_ref_coordinates(), Champ_Generique_Interpolation::get_ref_domain(), get_ref_domain(), get_ref_pb_base(), get_ref_values(), get_ref_zcl_dis_base(), get_ref_zone_dis_base(), get_time(), Postraitement::init(), lire_bidon(), Champ_Generique_Tparoi_VEF::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Transformation::preparer_macro(), and set_source().
{
// Si sources_ et source_ref sont vide, on n'a pas a etre ici
  if ((sources_reference_.size()==0) && (sources_.size()==0))
    {
      Cerr << finl;
      Cerr << "Error : The field \"" << noms_sources_ref_ << "\" is not recognized in the sources_reference option of the " << que_suis_je() << " keyword." << finl;
      Cerr << "\"" << noms_sources_ref_ << "\" should be defined before." << finl;
      exit();
    }
  int n_sources_ref=sources_reference_.size();
  if (i<n_sources_ref)
    {
      if ( ! sources_reference_[i].non_nul())
        {
          Cerr << finl;
          Cerr << "Error : The field \"" << noms_sources_ref_[0] << "\" is not recognized in the sources_reference option of the " << que_suis_je() << " keyword." << finl;
          Cerr << "\"" << noms_sources_ref_[0] << "\" should be defined before." << finl;
          exit();
        }
      return sources_reference_[i].valeur();
    }
  else
    return sources_[i-n_sources_ref].valeur();
}
double Champ_Gen_de_Champs_Gen::get_time () const [virtual]
Renvoie le temps du Champ_Generique.
Reimplemented from Champ_Generique_base.
Definition at line 352 of file Champ_Gen_de_Champs_Gen.cpp.
References get_source(), and Champ_Generique_base::get_time().
Referenced by Champ_Generique_Morceau_Equation::creer_espace_stockage(), creer_espace_stockage(), and Champ_Generique_Transformation::get_champ().
{
  return get_source(0).get_time();
}
void Champ_Gen_de_Champs_Gen::get_xyz_values (const DoubleTab & coords, DoubleTab & values, ArrOfBit & validity_flag) const [virtual]
Calcule la valeur ponctuelle du champ aux coordonnees donnees dans coords et
les met dans values. validity_flag est rempli avec 1 si la valeur est valide
(coordonnees a l'interieur du domaine), 0 sinon. < Attention en parallele: Chaque processeur traite le tableau coords qui lui est fourni : on peut soit faire calculer le meme tableau a tout le monde: dans ce cas, validity_flag indique sur chaque processeur quelles valeurs chaque processeur a pu calculer, soit on sait par avance quelles coordonnees sont calculable par chaque processeur et on donne au processeur local uniquement des coordonnees qu'il possede. Si une meme coordonnee est demandee a plusieurs processeurs, on ne garantit pas que tous donnent le meme resultat. En general, un seul aura le validity_flag mis pour cette coordonnee. Exceptions: - GenericFieldError::NOT_IMPLEMENTED : le paresseux n'a pas code les methodes d'interpolation il faut se debrouiller avec le maillage et les valeurs discretes. - GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie
Reimplemented from Champ_Generique_base.
Definition at line 307 of file Champ_Gen_de_Champs_Gen.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
}
const Type_info * Champ_Gen_de_Champs_Gen::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 29 of file Champ_Gen_de_Champs_Gen.cpp.
void Champ_Gen_de_Champs_Gen::lire_bidon (Entree & is) const [virtual]
Reimplemented in Champ_Generique_Statistiques_base.
Definition at line 436 of file Champ_Gen_de_Champs_Gen.cpp.
References get_nb_sources(), get_source(), lire_bidon(), ref_cast, and sub_type.
Referenced by lire_bidon(), and Postraitement::reprendre().
{
  const int n = get_nb_sources();;
  for (int i = 0; i < n; i++)
    {
      if (sub_type(Champ_Gen_de_Champs_Gen,get_source(i)))
        {
          const Champ_Gen_de_Champs_Gen& source = ref_cast(Champ_Gen_de_Champs_Gen,get_source(i));
          source.lire_bidon(is);
        }
    }
}
int Champ_Gen_de_Champs_Gen::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Moyenne, Champ_Generique_Predefini, and Champ_Generique_Transformation.
Definition at line 57 of file Champ_Gen_de_Champs_Gen.cpp.
References List_Nom::add(), List_Champ_Generique::add(), Cerr, Process::exit(), finl, Process::Journal(), Champ_Generique_base::nommer(), noms_sources_ref_, sources_, Deriv_::typer(), and Deriv_Champ_Generique_base::valeur().
{
  if (mot=="source")
    {
      Champ_Generique& new_src = sources_.add(Champ_Generique());
      Nom typ;
      is >> typ;
      Journal() << "Reading a source type " << typ << finl;
      new_src.typer(typ);
      is >> new_src.valeur();
      return 1;
    }
  else if (mot=="source_reference")
    {
      Nom& new_s = noms_sources_ref_.add(Nom());
      is >> new_s;
      Cerr<<"WARNING : obsolete option. Use now sources_reference { " << new_s<< " } instead of source_reference "<<new_s<<finl;
      return 1;
    }
  else if (mot=="sources")
    {
      Nom accouverte="{";
      Nom accfermee="}";
      Nom virgule=",";
      Nom typ;
      is >> typ;
      assert (typ==accouverte);
      is >> typ;
      if(typ==accfermee)
        {
          Cerr<<"We should not use the keyword \"sources\" to specify a generic field"<<finl;
          Cerr<<"of type Champ_Gen_de_Champs_Gen without specifying sources"<<finl;
          exit();
        }
      while(1)
        {
          Champ_Generique& new_src = sources_.add(Champ_Generique());
          Journal() << "Reading a source type " << typ << finl;
          new_src.typer(typ);
          is >> new_src.valeur();
          is >> typ;
          if(typ==accfermee)
            break;
          if(typ!=virgule)
            {
              Cerr << typ << " : We expected a ',' or '}'" << finl;
              exit();
            }
          is >> typ;
        }
      return 1;
    }
  else if (mot=="nom_source")
    {
      Nom id_source;
      is >> id_source;
      nommer(id_source);
      return 1;
    }
  else
    return Champ_Generique_base::lire_motcle_non_standard(mot,is);
  return 1;
}
void Champ_Gen_de_Champs_Gen::mettre_a_jour (double temps) [virtual]
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_Statistiques_base.
Definition at line 138 of file Champ_Gen_de_Champs_Gen.cpp.
References liste::size(), sources_, and valeur().
{
  const int n = sources_.size();
  for (int i = 0; i < n; i++)
    sources_[i].valeur().mettre_a_jour(temps);
}
void Champ_Gen_de_Champs_Gen::nommer_source () [virtual]
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 398 of file Champ_Gen_de_Champs_Gen.cpp.
Referenced by completer(), and nommer_sources().
{
}
void Champ_Gen_de_Champs_Gen::nommer_sources ()
Definition at line 372 of file Champ_Gen_de_Champs_Gen.cpp.
References Cerr, Process::exit(), finl, get_nb_sources(), Champ_Generique_refChamp::nommer_source(), nommer_source(), nommer_sources(), ref_cast, sources_, sub_type, and valeur().
Referenced by Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), and nommer_sources().
{
  int nb_sources = get_nb_sources();
  for (int i=0; i<nb_sources; i++)
    {
      if (sub_type(Champ_Gen_de_Champs_Gen,sources_[i].valeur()))
        {
          Champ_Gen_de_Champs_Gen& champ = ref_cast(Champ_Gen_de_Champs_Gen,sources_[i].valeur());
          champ.nommer_sources();
          champ.nommer_source();
        }
      else if (sub_type(Champ_Generique_refChamp,sources_[i].valeur()))
        {
          Champ_Generique_refChamp& champ = ref_cast(Champ_Generique_refChamp,sources_[i].valeur());
          champ.nommer_source();
        }
      else
        {
          Cerr<<"There is no method nommer_source() for this type of field "<<finl;
          Cerr<<"sources_[i].valeur().que_suis_je()"<<finl;
          exit();
        }
    }
}
Sortie & Champ_Gen_de_Champs_Gen::printOn (Sortie & os) const [protected, virtual]
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 38 of file Champ_Gen_de_Champs_Gen.cpp.
References Process::exit().
{
  exit();
  return os;
}
Entree & Champ_Gen_de_Champs_Gen::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 32 of file Champ_Gen_de_Champs_Gen.cpp.
{
  Champ_Generique_base::readOn(is);
  return is;
}
int Champ_Gen_de_Champs_Gen::reprendre (Entree & is) [virtual]
reprise des differentes sources
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_Statistiques_base.
Definition at line 224 of file Champ_Gen_de_Champs_Gen.cpp.
References liste::size(), sources_, and valeur().
{
  const int n = sources_.size();
  for (int i = 0; i < n; i++)
    sources_[i].valeur().reprendre(is);
  return 1;
}
void Champ_Gen_de_Champs_Gen::reset () [virtual]
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_Interpolation.
Definition at line 133 of file Champ_Gen_de_Champs_Gen.cpp.
References sources_, and liste::vide().
Referenced by Champ_Generique_Extraction::Champ_Generique_Extraction().
{
  sources_.vide();
}
int Champ_Gen_de_Champs_Gen::sauvegarder (Sortie & os) const [virtual]
sauvegarde des differentes sources
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_Statistiques_base.
Definition at line 214 of file Champ_Gen_de_Champs_Gen.cpp.
References liste::size(), sources_, and valeur().
{
  const int n = sources_.size();
  int bytes = 0;
  for (int i = 0; i < n; i++)
    bytes += sources_[i].valeur().sauvegarder(os);
  return bytes;
}
const Champ_Gen_de_Champs_Gen & Champ_Gen_de_Champs_Gen::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 29 of file Champ_Gen_de_Champs_Gen.cpp.
Champ_Gen_de_Champs_Gen & Champ_Gen_de_Champs_Gen::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 29 of file Champ_Gen_de_Champs_Gen.cpp.
void Champ_Gen_de_Champs_Gen::set_param (Param & param) [virtual]
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_Extraction, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, and Champ_Generique_modifier_pour_QC.
Definition at line 48 of file Champ_Gen_de_Champs_Gen.cpp.
References Param::ajouter(), Param::ajouter_non_std(), and noms_sources_ref_.
{
  param.ajouter_non_std("source",(this));
  param.ajouter_non_std("sources",(this));
  param.ajouter_non_std("nom_source",(this));
  param.ajouter_non_std("source_reference",(this));
  param.ajouter("sources_reference",&noms_sources_ref_);
}
Champ_Generique_base & Champ_Gen_de_Champs_Gen::set_source (int i) [virtual]
Definition at line 201 of file Champ_Gen_de_Champs_Gen.cpp.
References get_source(), and ref_cast_non_const.
Referenced by completer(), Postraitement::creer_champ_post_stat(), fixer_serie(), and fixer_tstat_deb().
{
// POur eviter de recoder la meme chose que get_source
  return ref_cast_non_const(Champ_Generique_base,get_source(i));
}
Member Data Documentation
const Type_info Champ_Gen_de_Champs_Gen::info_obj [static]
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_Correlation, Champ_Generique_Divergence, Champ_Generique_Ecart_Type, Champ_Generique_Extraction, Champ_Generique_Gradient, Champ_Generique_Interpolation, Champ_Generique_Morceau_Equation, Champ_Generique_Moyenne, Champ_Generique_Operateur_base, Champ_Generique_Predefini, Champ_Generique_Reduction_0D, Champ_Generique_Statistiques_base, Champ_Generique_Transformation, Champ_Post_Operateur_Eqn, Champ_Generique_modifier_pour_QC, and Champ_Generique_Tparoi_VEF.
Definition at line 47 of file Champ_Gen_de_Champs_Gen.h.
List_Nom Champ_Gen_de_Champs_Gen::noms_sources_ref_ [protected]
Definition at line 109 of file Champ_Gen_de_Champs_Gen.h.
Referenced by completer(), get_source(), lire_motcle_non_standard(), and set_param().
List_Champ_Generique Champ_Gen_de_Champs_Gen::sources_ [private]
Definition at line 114 of file Champ_Gen_de_Champs_Gen.h.
Referenced by get_nb_sources(), get_set_source(), get_set_sources(), get_source(), lire_motcle_non_standard(), mettre_a_jour(), nommer_sources(), reprendre(), reset(), and sauvegarder().
List_Ref_Champ_Generique_base Champ_Gen_de_Champs_Gen::sources_reference_ [protected]
Definition at line 110 of file Champ_Gen_de_Champs_Gen.h.
Referenced by completer(), get_nb_sources(), and get_source().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Gen_de_Champs_Gen.h
src/Kernel/Champs/Champ_Gen_de_Champs_Gen.cpp