TRUST: Pb_Thermohydraulique Class Reference
Pb_Thermohydraulique Class Reference
classe Pb_Thermohydraulique
Cette classe represente un probleme de thermohydraulique standard:
- Equations de Navier_Stokes en regime laminaire
pour un fluide incompressible
- Equation d'energie en regime laminaire
En general, on couple les 2 equations par l'intermediaire du terme
source des forces de volume de Navier_Stokes dans lequel on prend en
compte de petites variations de la masse volumique en fonction de
la temperature<br>(le fluide est incompressible et faiblement dilalatable)
#include <Pb_Thermohydraulique.h>
Public Member Functions
Pb_Thermohydraulique ()
~Pb_Thermohydraulique ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int nombre_d_equations () const override
Renvoie le nombre d'equation,
Renvoie 2 car il y a 2 equations a un probleme de
thermo-hydraulique standard:
l'equation de Navier Stokes
l' equation de la thermique de type Convection_Diffusion_Temperature.
const Equation_base & equation (int) const override
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1
(version const)
Equation_base & equation (int) override
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1.
void associer_milieu_base (const Milieu_base &) override
Associe le milieu au probleme
Le milieu doit etre de type fluide incompressible
Parametre: Milieu_base& mil
Signification: le milieu physique a associer au probleme
Valeurs par defaut:
Contraintes: doit etre de type fluide incompressible
reference constante
Acces: entree.
int verifier () override
Teste la compatibilite des equations de la thermique
et de l'hydraulique. Le test se fait sur les conditions
aux limites discretisees de chaque equation.
Appel la fonction de librairie hors classe:
tester_compatibilite_hydr_thermique(const Zone_Cl_dis&,const Zone_Cl_dis&)
Public Member Functions inherited from Pb_Fluide_base
Pb_Fluide_base ()
~Pb_Fluide_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int expression_predefini (const Motcle &motlu, Nom &expression) override
Public Member Functions inherited from Probleme_base
~Probleme_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
bool solveTimeStep () override
pour recodage eventuel et appel unifie en python
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Si force=1, effectue le postraitement sans tenir compte des
frequences de postraitement.
Le postraitement est mis a jour et les traitements eventuels sur
les sondes, champs et statistiques sont effectues.
Si force=0, tient compte des frequences d'impression demandees.
int limpr () const override
Demande au schema en temps s'il faut faire une impression.
int lsauv () const override
Demande au schema en temps s'il faut faire une sauvegarde.
void sauver () const override
Ecriture sur fichier en vue d'une reprise (sauvegarde)
virtual void allocation () const
Verifie que la place necessaire existe sur le disque dur.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
Probleme_base ()
virtual void associer ()
Associe le probleme a toutes ses equations.
virtual Entree & lire_equations (Entree &is, Motcle &dernier_mot)
Lecture des equations du probleme.
virtual void completer ()
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
virtual int verifier ()
Verifie que l'objet est complet, coherent, ...
NON DEVELOPPE RENVOIE TOUJOURS 1.
virtual int nombre_d_equations () const =0
virtual const Equation_base & equation (int) const =0
virtual Equation_base & equation (int)=0
const Equation_base & equation (const Nom &) const
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
(version const)
Equation_base & equation (const Nom &)
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
virtual const Equation_base & get_equation_by_name (const Nom &) const
virtual Equation_base & getset_equation_by_name (const Nom &)
virtual const Milieu_base & milieu () const
Renvoie le milieu physique associe au probleme.
(version const)
On renvoie le milieu associe a la premiere equation.
virtual Milieu_base & milieu ()
Renvoie le milieu physique associe au probleme.
On renvoie le milieu associe a la premiere equation.
int sauvegarder (Sortie &) const override
Ecriture du probleme sur fichier en vue d'une reprise.
Ecrit le nom du probleme et sauvegarde les equations.
int reprendre (Entree &) override
Lecture d'un flot d'entree (fichier) pour reprise apres
une sauvegarde avec Probleme_base::sauvegarder(Sortie& os).
virtual void imprimer (Sortie &os) const
Appelle imprimer sur chaque equation.
virtual double calculer_pas_de_temps () const
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees
au probleme.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
virtual void preparer_calcul ()
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
virtual void associer_domaine (const Domaine &)
Associe un domaine au probleme.
Prend un_domaine comme support.
apelle Domaine_dis::associer_dom(const Domaine&)
virtual void associer_milieu_base (const Milieu_base &)
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
int associer_ (Objet_U &) override
surcharge Objet_U::associer_(Objet_U& ob)
Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
virtual void discretiser (const Discretisation_base &)
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
virtual void finir ()
Finit le postraitement et sauve le probleme dans un fichier.
Fermeture du fichier associe au postraitement.(Postraitement::finir())
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe au probleme. (si il est non nul)
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe au probleme. (si il est non nul)
const Domaine & domaine () const
Renvoie le domaine associe au probleme.
(version const)
Domaine & domaine ()
Renvoie le domaine associe au probleme.
const Domaine_dis & domaine_dis () const
Renvoie le domaine discretise associe au probleme.
(version const)
Domaine_dis & domaine_dis ()
Renvoie le domaine discretise associe au probleme.
int is_dilatable () const
virtual int allocate_file_size (long int &size) const
Verifie que la place necessaire existe sur le disque dur.
virtual int file_size_xyz () const
Ecrit le probleme dans un fichier *.calcul_xyz
et calcul la place disque prise par ce fichier.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au probleme
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du probleme
const Discretisation_base & discretisation () const
Renvoie la discretisation associee au probleme.
Postraitements & postraitements ()
const Postraitements & postraitements () const
void init_postraitements ()
virtual int expression_predefini (const Motcle &motlu, Nom &expression)
const char * reprise_format_temps () const
int & reprise_effectuee ()
int reprise_effectuee () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual bool has_champ (const Motcle &nom) const
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &nom) const
virtual int verifie_tdeb_tfin (const Motcle &nom) const
On verifie que le temps de debut et de fin des statistiques est identique sur tous les champsde tous les postraitements.
virtual int a_pour_IntVect (const Motcle &, Ref_IntVect &) const
virtual void lire_postraitement_interfaces (Entree &is)
virtual void postraiter_interfaces (const Nom &nom_fich, Sortie &s, const Nom &format, double temps)
virtual void addInputField (Field_base &f)
void sauver_xyz (int) const
void set_coupled (int i)
int get_coupled () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Pb_Thermohydraulique & self_cast (Objet_U &)
static const Pb_Thermohydraulique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Pb_Fluide_base
static const Type_info * info ()
static Pb_Fluide_base & self_cast (Objet_U &)
static const Pb_Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_base
static const Type_info * info ()
static Probleme_base & self_cast (Objet_U &)
static const Probleme_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Pb_Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Probleme_base
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Pb_Fluide_base::printOn(Sortie&)
Ecrit le probleme sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a: Pb_Fluide_base::readOn(Entree&)
Lit le probleme a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Navier_Stokes_std eq_hydraulique
Convection_Diffusion_Temperature eq_thermique
Protected Attributes inherited from Probleme_base
Domaine_dis le_domaine_dis
Postraitements les_postraitements
Ref_Schema_Temps_base le_schema_en_temps
Ref_Discretisation_base la_discretisation
List_Ref_Field_base input_fields
List of input fields inside this problem.
Deriv_Sortie_Fichier_base ficsauv_
Sortie_Brute * osauv_hdf_
int reprise_effectuee_
int reprise_version_
Nom nom_fich
Nom format_sauv
int restart_file
bool initialized
true if initialize was called
bool terminated
true if terminate was called
bool dt_defined
true if computation interval is defined set to true by initTimeStep, to false by validateTimeStep & abortTimeStep
bool dt_validated
true if last computation was validated set to true by validateTimeStep, to false by initTimeStep
double tstat_deb_
double tstat_fin_
Nom error
Erreur d'allocation.
int coupled_
Flag to indicate it is a part of a coupled problem.
List_Ref_Loi_Fermeture_base liste_loi_fermeture_
liste des fermetures associees au probleme
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Additional Inherited Members
Static Protected Attributes inherited from Probleme_base
static long int file_size =0
Espace disque pris par les sauvegarde XYZ.
static int bad_allocate =1
1 si allocation reussi, 0 sinon
static int nb_pb_total =0
Nombre total de probleme.
static int num_pb =1
numero du probleme
Detailed Description
classe Pb_Thermohydraulique
Cette classe represente un probleme de thermohydraulique standard:
- Equations de Navier_Stokes en regime laminaire
pour un fluide incompressible
- Equation d'energie en regime laminaire
En general, on couple les 2 equations par l'intermediaire du terme
source des forces de volume de Navier_Stokes dans lequel on prend en
compte de petites variations de la masse volumique en fonction de
la temperature<br>(le fluide est incompressible et faiblement dilalatable)
Definition at line 42 of file Pb_Thermohydraulique.h.
Constructor & Destructor Documentation
Pb_Thermohydraulique()
Pb_Thermohydraulique::Pb_Thermohydraulique ()
Definition at line 20 of file Pb_Thermohydraulique.cpp.
~Pb_Thermohydraulique()
Pb_Thermohydraulique::~Pb_Thermohydraulique ()
Definition at line 20 of file Pb_Thermohydraulique.cpp.
Member Function Documentation
associer_milieu_base()
void Pb_Thermohydraulique::associer_milieu_base (const Milieu_base & mil) override virtual
Associe le milieu au probleme
Le milieu doit etre de type fluide incompressible
Parametre: Milieu_base& mil
Signification: le milieu physique a associer au probleme
Valeurs par defaut:
Contraintes: doit etre de type fluide incompressible
reference constante
Acces: entree.
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 162 of file Pb_Thermohydraulique.cpp.
{
  if (sub_type(Fluide_Incompressible,mil))
    {
      eq_hydraulique.associer_milieu_base(mil);
      eq_thermique.associer_milieu_base(mil);
    }
  else if (sub_type(Fluide_Ostwald,mil))
    {
      eq_hydraulique.associer_milieu_base(mil);
      eq_thermique.associer_milieu_base(mil);
      Cerr << "Fluide non newtonien" << finl;
    }
  else
    {
      Cerr << "Un milieu de type " << mil.que_suis_je() << " ne peut etre associe a "<< finl;
      Cerr << "un probleme de type Pb_Thermohydraulique " << finl;
      exit();
    }
}
References Convection_Diffusion_Temperature::associer_milieu_base(), Navier_Stokes_std::associer_milieu_base(), Cerr, eq_hydraulique, eq_thermique, Process::exit(), finl, Objet_U::que_suis_je(), and sub_type.
cree_instance()
Objet_U * Pb_Thermohydraulique::cree_instance () static
Definition at line 20 of file Pb_Thermohydraulique.cpp.
duplique()
int Pb_Thermohydraulique::duplique () const override virtual
Implements Objet_U.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 20 of file Pb_Thermohydraulique.cpp.
equation() [1/2]
const Equation_base & Pb_Thermohydraulique::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1
(version const)
Returns
Equation_base&
Signification: l'equation correspondante a l'index
Contraintes: reference constante
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 104 of file Pb_Thermohydraulique.cpp.
{
  if ( !( i==0 || i==1 ) )
    {
      Cerr << "\nError in Pb_Thermohydraulique::equation() : Wrong number of equation !" << finl;
      Process::exit();
    }
  if (i == 0)
    return eq_hydraulique;
  else
    return eq_thermique;
}
References Cerr, eq_hydraulique, eq_thermique, Process::exit(), and finl.
equation() [2/2]
Equation_base & Pb_Thermohydraulique::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0
Renvoie l'equation de la thermique de type
Convection_Diffusion_Temperature si i=1.
Returns
Equation_base&
Signification: l'equation correspondante a l'index
Contraintes:
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 133 of file Pb_Thermohydraulique.cpp.
{
  if ( !( i==0 || i==1 ) )
    {
      Cerr << "\nError in Pb_Thermohydraulique::equation() : Wrong number of equation !" << finl;
      Process::exit();
    }
  if (i == 0)
    return eq_hydraulique;
  else
    return eq_thermique;
}
References Cerr, eq_hydraulique, eq_thermique, Process::exit(), and finl.
get_info()
const Type_info * Pb_Thermohydraulique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 20 of file Pb_Thermohydraulique.cpp.
info()
const Type_info * Pb_Thermohydraulique::info () static
Definition at line 20 of file Pb_Thermohydraulique.cpp.
nombre_d_equations()
int Pb_Thermohydraulique::nombre_d_equations () const override virtual
Renvoie le nombre d'equation,
Renvoie 2 car il y a 2 equations a un probleme de
thermo-hydraulique standard:
l'equation de Navier Stokes
l' equation de la thermique de type Convection_Diffusion_Temperature.
Returns
int
Signification: le nombre d'equation
Contraintes: toujours 2 car il y a 2 equations au probleme
Implements Probleme_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 82 of file Pb_Thermohydraulique.cpp.
{
  return 2;
}
printOn()
Sortie & Pb_Thermohydraulique::printOn (Sortie & os) const override protected virtual
Simple appel a: Pb_Fluide_base::printOn(Sortie&)
Ecrit le probleme sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 38 of file Pb_Thermohydraulique.cpp.
{
  return Pb_Fluide_base::printOn(os);
}
References Pb_Fluide_base::printOn().
readOn()
Entree & Pb_Thermohydraulique::readOn (Entree & is) override protected virtual
Simple appel a: Pb_Fluide_base::readOn(Entree&)
Lit le probleme a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 59 of file Pb_Thermohydraulique.cpp.
{
  return Pb_Fluide_base::readOn(is);
}
References Pb_Fluide_base::readOn().
self_cast() [1/2]
const Pb_Thermohydraulique & Pb_Thermohydraulique::self_cast (const Objet_U & r) static
Definition at line 20 of file Pb_Thermohydraulique.cpp.
self_cast() [2/2]
Pb_Thermohydraulique & Pb_Thermohydraulique::self_cast (Objet_U & r) static
Definition at line 20 of file Pb_Thermohydraulique.cpp.
taille_memoire()
unsigned Pb_Thermohydraulique::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Pb_Thermohydraulique_Scalaires_Passifs.
Definition at line 20 of file Pb_Thermohydraulique.cpp.
verifier()
int Pb_Thermohydraulique::verifier () override virtual
Teste la compatibilite des equations de la thermique
et de l'hydraulique. Le test se fait sur les conditions
aux limites discretisees de chaque equation.
Appel la fonction de librairie hors classe:
tester_compatibilite_hydr_thermique(const Zone_Cl_dis&,const Zone_Cl_dis&)
Returns
int
Signification: code de retour propage
Contraintes:
Reimplemented from Probleme_base.
Definition at line 203 of file Pb_Thermohydraulique.cpp.
{
  const Zone_Cl_dis& zone_Cl_hydr = eq_hydraulique.zone_Cl_dis();
  const Zone_Cl_dis& zone_Cl_th = eq_thermique.zone_Cl_dis();
  return tester_compatibilite_hydr_thermique(zone_Cl_hydr,zone_Cl_th);
}
References eq_hydraulique, eq_thermique, tester_compatibilite_hydr_thermique(), and Equation_base::zone_Cl_dis().
Member Data Documentation
eq_hydraulique
Navier_Stokes_std Pb_Thermohydraulique::eq_hydraulique protected
Definition at line 57 of file Pb_Thermohydraulique.h.
Referenced by associer_milieu_base(), equation(), and verifier().
eq_thermique
Convection_Diffusion_Temperature Pb_Thermohydraulique::eq_thermique protected
Definition at line 58 of file Pb_Thermohydraulique.h.
Referenced by associer_milieu_base(), equation(), and verifier().
info_obj
const Type_info Pb_Thermohydraulique::info_obj static
Definition at line 45 of file Pb_Thermohydraulique.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Problems/Pb_Thermohydraulique.h
src/ThHyd/Incompressible/Problems/Pb_Thermohydraulique.cpp