TRUST: Deriv_Champ_Inc_base Class Reference
Deriv_Champ_Inc_base Class Reference
classe Champ_Inc
Classe generique de la hierarchie des champs inconnue, un objet
Champ_Inc peut referencer n'importe quel objet derivant de
Champ_Inc_base.
La plupart des methodes appellent les methodes de l'objet champ
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Champ_Inc.h>
Public Member Functions
~Deriv_Champ_Inc_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Inc_base ()
Deriv_Champ_Inc_base (const Deriv_Champ_Inc_base &)
const Champ_Inc_base & valeur () const
Champ_Inc_base & valeur ()
const Champ_Inc_base * operator-> () const
Champ_Inc_base * operator-> ()
const Deriv_Champ_Inc_base & operator= (const Champ_Inc_base &)
const Deriv_Champ_Inc_base & operator= (const Deriv_Champ_Inc_base &)
operator const Champ_Inc_base & () const
operator Champ_Inc_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_Inc_base & self_cast (Objet_U &)
static const Deriv_Champ_Inc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Champ_Inc_base * pointeur_
Detailed Description
classe Champ_Inc
Classe generique de la hierarchie des champs inconnue, un objet
Champ_Inc peut referencer n'importe quel objet derivant de
Champ_Inc_base.
La plupart des methodes appellent les methodes de l'objet champ
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 35 of file Champ_Inc.h.
Constructor & Destructor Documentation
~Deriv_Champ_Inc_base()
Deriv_Champ_Inc_base::~Deriv_Champ_Inc_base ()
Definition at line 18 of file Champ_Inc.cpp.
Deriv_Champ_Inc_base() [1/2]
Deriv_Champ_Inc_base::Deriv_Champ_Inc_base ()
Definition at line 18 of file Champ_Inc.cpp.
Deriv_Champ_Inc_base() [2/2]
Deriv_Champ_Inc_base::Deriv_Champ_Inc_base (const Deriv_Champ_Inc_base & t)
Definition at line 18 of file Champ_Inc.cpp.
Member Function Documentation
cree_instance()
Objet_U * Deriv_Champ_Inc_base::cree_instance () static
Definition at line 18 of file Champ_Inc.cpp.
duplique()
int Deriv_Champ_Inc_base::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_Inc.
Definition at line 18 of file Champ_Inc.cpp.
get_info()
const Type_info * Deriv_Champ_Inc_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Inc.
Definition at line 18 of file Champ_Inc.cpp.
get_info_ptr()
const Type_info & Deriv_Champ_Inc_base::get_info_ptr () const override virtual
Implements O_U_Ptr.
Definition at line 18 of file Champ_Inc.cpp.
info()
const Type_info * Deriv_Champ_Inc_base::info () static
Definition at line 18 of file Champ_Inc.cpp.
operator Champ_Inc_base &()
Deriv_Champ_Inc_base::operator Champ_Inc_base & ()
Definition at line 18 of file Champ_Inc.cpp.
operator const Champ_Inc_base &()
Deriv_Champ_Inc_base::operator const Champ_Inc_base & () const
Definition at line 18 of file Champ_Inc.cpp.
operator->() [1/2]
Champ_Inc_base * Deriv_Champ_Inc_base::operator-> () inline
Definition at line 35 of file Champ_Inc.h.
: public DERIV(Champ_Inc_base), public Champ_Proto
operator->() [2/2]
const Champ_Inc_base * Deriv_Champ_Inc_base::operator-> () const inline
Definition at line 35 of file Champ_Inc.h.
: public DERIV(Champ_Inc_base), public Champ_Proto
operator=() [1/2]
const Deriv_Champ_Inc_base & Deriv_Champ_Inc_base::operator= (const Champ_Inc_base & t)
Definition at line 18 of file Champ_Inc.cpp.
operator=() [2/2]
const Deriv_Champ_Inc_base & Deriv_Champ_Inc_base::operator= (const Deriv_Champ_Inc_base & t)
Definition at line 18 of file Champ_Inc.cpp.
printOn()
Sortie & Deriv_Champ_Inc_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Inc.
Definition at line 18 of file Champ_Inc.cpp.
readOn()
Entree & Deriv_Champ_Inc_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Inc.
Definition at line 18 of file Champ_Inc.cpp.
self_cast() [1/2]
const Deriv_Champ_Inc_base & Deriv_Champ_Inc_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Champ_Inc.cpp.
self_cast() [2/2]
Deriv_Champ_Inc_base & Deriv_Champ_Inc_base::self_cast (Objet_U & r) static
Definition at line 18 of file Champ_Inc.cpp.
set_O_U_Ptr()
void Deriv_Champ_Inc_base::set_O_U_Ptr (Objet_U * ptr) override protected virtual
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 18 of file Champ_Inc.cpp.
taille_memoire()
unsigned Deriv_Champ_Inc_base::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_Inc.
Definition at line 18 of file Champ_Inc.cpp.
valeur() [1/2]
Champ_Inc_base & Deriv_Champ_Inc_base::valeur () inline
Definition at line 35 of file Champ_Inc.h.
: public DERIV(Champ_Inc_base), public Champ_Proto
valeur() [2/2]
const Champ_Inc_base & Deriv_Champ_Inc_base::valeur () const inline
Definition at line 35 of file Champ_Inc.h.
: public DERIV(Champ_Inc_base), public Champ_Proto
Referenced by Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Op_Diff_VDF_Face_base::ajouter_blocs(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_base::ajouter_blocs(), Perte_Charge_Reguliere_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Schema_Implicite_Multi_TimeStep_base::ajouter_inertie(), Solveur_Masse_EF::ajouter_masse(), Masse_VEF_P1NC::ajouter_masse(), Solveur_Masse_base::appliquer(), Assembleur_P_PolyMAC::assembler_continuite(), Assembleur_P_PolyMAC::assembler_mat(), Op_Diff_P1NC_barprim::associer(), Op_Diff_RotRot::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Conv_Centre_old_VEF_Face::associer(), Op_Diff_VEF_base::associer(), Champ_Inc::associer_eqn(), Op_Diff_Dift_VDF< OP_TYPE >::associer_impl(), Op_Conv_VDF< OP_TYPE >::associer_impl(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Champ_Inc::associer_zone_dis_base(), Champ_Inc::avancer(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Fluide_base::calculer_e_int(), Fluide_reel_base::calculer_energie_interne(), Fluide_reel_base::calculer_enthalpie(), Fluide_reel_base::calculer_masse_volumique(), Fluide_Dilatable_base::calculer_pression_tot(), Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Equation_base::champ_conserve(), Equation_base::champ_convecte(), Energie_Multiphase::champ_convecte(), Champ_Inc::changer_temps(), Schema_Adams_Moulton_base::changer_temps(), Schema_Backward_Differentiation_base::changer_temps(), Source_base::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Masse_PolyMAC_P0_Face::completer(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Op_Dift_VDF_Face_Axi_base::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Chimie::completer(), Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec(), Op_Diff_VEF_Face::contribuer_a_avec(), Op_Diff_VEF_Face_Stab::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), VDF_discretisation::courant_maille(), Discretisation_base::creer_champ(), EF_discretisation::creer_champ_vorticite(), PolyMAC_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::critere_Q(), EF_discretisation::critere_Q(), PolyMAC_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Assembleur_P_PolyMAC::dimensionner_continuite(), Equation_base::discretiser(), Navier_Stokes_Fluide_Dilatable_base::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Masse_Multiphase::discretiser(), EF_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), Champ_Inc::fixer_nb_valeurs_nodales(), Champ_Inc::fixer_nb_valeurs_temporelles(), Discret_Thermique::Fluctu_Temperature(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Inc::futur(), Navier_Stokes_Fluide_Dilatable_base::get_champ(), Champ_Post_Operateur_Eqn::get_property(), EF_discretisation::grad_T(), PolyMAC_discretisation::grad_T(), VEF_discretisation::grad_T(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), EF_discretisation::h_conv(), PolyMAC_discretisation::h_conv(), VEF_discretisation::h_conv(), Zone_Cl_VEFP1B::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_Grad_VDF_Face::impr(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Champ_Inc::integrale_espace(), Simple::iterer_eqs(), SETS::iterer_NS(), Champ_Fonc_reprise::le_champ(), Champ_Inc::lire_donnees(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Champ_Inc::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_Elem::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Schema_Adams_Bashforth_base::modifier_second_membre(), multiplier_diviser_rho(), Champ_Inc::nb_valeurs_nodales(), Champ_Inc::nb_valeurs_temporelles(), Champ_Inc::passe(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Source_Scalaire_EF::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Convection_Diffusion_Espece_Multi_base::readOn(), Champ_Inc::reculer(), Zone_Cl_EF::remplir_type_elem_Cl(), Champ_Inc::reprendre(), Equation_base::reprendre(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), VDF_discretisation::residu(), PolyMAC_discretisation::residu(), VDF_discretisation::reynolds_maille(), Champ_Inc::sauvegarder(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), Champ_Inc::temps(), Champ_Inc::trace(), Op_Diff_PolyMAC_base::update_aux(), Op_Grad_PolyMAC_P0_Face::update_grad(), Op_Diff_PolyMAC_P0_base::update_phif(), Champ_Inc::valeurs(), Champ_Post_Operateur_Eqn::verification_cas_compo(), VEF_1D::vitesse(), EF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), VEF_discretisation::y_plus(), and Champ_Inc::zone_dis_base().
Member Data Documentation
info_obj
const Type_info Deriv_Champ_Inc_base::info_obj static
Definition at line 35 of file Champ_Inc.h.
pointeur_
Champ_Inc_base* Deriv_Champ_Inc_base::pointeur_ private
Definition at line 35 of file Champ_Inc.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Inc.h
src/Kernel/Framework/Champ_Inc.cpp