TRUST: Parametre_implicite Class Reference
Parametre_implicite Class Reference
classe Parametre_implicite
Un objet Parametre_implicite est un objet regroupant les differentes
options specifiques pour piso ou simpler
#include <Parametre_implicite.h>
Public Member Functions
Parametre_implicite ()
~Parametre_implicite ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys & solveur ()
const SolveurSys & solveur () const
double & seuil_generation_solveur ()
double & seuil_verification_solveur ()
double & seuil_test_preliminaire_solveur ()
double & seuil_convergence_implicite ()
double & seuil_diffusion_implicite ()
int & nb_it_max ()
int & calcul_explicite ()
int equation_frequence_resolue (double t)
void set_seuil_solveur_avec_seuil_convergence_solveur (double)
permet de mettre les seuils equivalents a ceux de la 161
pour l'instant warning ensuite ereur.
int seuil_test_preliminaire_lu () const
Public Member Functions inherited from Parametre_equation_base
Parametre_equation_base ()
~Parametre_equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Parametre_implicite & self_cast (Objet_U &)
static const Parametre_implicite & self_cast (const Objet_U &)
Static Public Member Functions inherited from Parametre_equation_base
static const Type_info * info ()
static Parametre_equation_base & self_cast (Objet_U &)
static const Parametre_equation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Parametre_equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
SolveurSys le_solveur_
double seuil_generation_solveur_
double seuil_test_preliminaire_solveur_
double seuil_verification_solveur_
int seuil_test_preliminaire_lu_
double seuil_convergence_implicite_
int nb_it_max_
int calcul_explicite_
double seuil_diffusion_implicite_
Parser_U equation_frequence_resolue_
Detailed Description
classe Parametre_implicite
Un objet Parametre_implicite est un objet regroupant les differentes
options specifiques pour piso ou simpler
Definition at line 35 of file Parametre_implicite.h.
Constructor & Destructor Documentation
Parametre_implicite()
Parametre_implicite::Parametre_implicite ()
Definition at line 22 of file Parametre_implicite.cpp.
{
  seuil_convergence_implicite()=-1.;
// seuil_convergence_solveur()=-1.;
  seuil_generation_solveur_=-1;
  seuil_verification_solveur_=-1;
  seuil_test_preliminaire_solveur_=-1;
  seuil_test_preliminaire_lu_=0;
  seuil_diffusion_implicite_=-1;
  nb_it_max_=1000000;
  calcul_explicite_=0;
  Nom eq_freq_resolue="0";
  equation_frequence_resolue_.setNbVar(1);
  equation_frequence_resolue_.setString(eq_freq_resolue);
  equation_frequence_resolue_.addVar("t");
  equation_frequence_resolue_.parseString();
}
References Parser_U::addVar(), calcul_explicite_, equation_frequence_resolue_, nb_it_max_, Parser_U::parseString(), Parser_U::setNbVar(), Parser_U::setString(), seuil_convergence_implicite(), seuil_diffusion_implicite_, seuil_generation_solveur_, seuil_test_preliminaire_lu_, seuil_test_preliminaire_solveur_, and seuil_verification_solveur_.
~Parametre_implicite()
Parametre_implicite::~Parametre_implicite ()
Definition at line 19 of file Parametre_implicite.cpp.
Member Function Documentation
calcul_explicite()
int & Parametre_implicite::calcul_explicite () inline
Definition at line 72 of file Parametre_implicite.h.
  {
    return calcul_explicite_ ;
  };
References calcul_explicite_.
Referenced by Simple::iterer_eqn().
cree_instance()
Objet_U * Parametre_implicite::cree_instance () static
Definition at line 19 of file Parametre_implicite.cpp.
duplique()
int Parametre_implicite::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Parametre_implicite.cpp.
equation_frequence_resolue()
int Parametre_implicite::equation_frequence_resolue (double t) inline
Definition at line 76 of file Parametre_implicite.h.
  {
    equation_frequence_resolue_.setVar("t",t);
    return (int)equation_frequence_resolue_.eval() ;
  };
References equation_frequence_resolue_, Parser_U::eval(), and Parser_U::setVar().
Referenced by Simple::iterer_eqn().
get_info()
const Type_info * Parametre_implicite::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 19 of file Parametre_implicite.cpp.
info()
const Type_info * Parametre_implicite::info () static
Definition at line 19 of file Parametre_implicite.cpp.
nb_it_max()
int & Parametre_implicite::nb_it_max () inline
Definition at line 68 of file Parametre_implicite.h.
  {
    return  nb_it_max_ ;
  };
References nb_it_max_.
Referenced by Simpler_Base::readOn().
printOn()
Sortie & Parametre_implicite::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 40 of file Parametre_implicite.cpp.
{
  return os;
}
readOn()
Entree & Parametre_implicite::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Parametre_equation_base.
Definition at line 52 of file Parametre_implicite.cpp.
{
  Nom eq_freq_resolue="0";
  double seuil_convergence_solveur_prov=-1;
  Param param(que_suis_je());
  param.ajouter("solveur",&le_solveur_);
  param.ajouter( "seuil_convergence_implicite",&seuil_convergence_implicite_);
  param.ajouter( "seuil_convergence_solveur",&seuil_convergence_solveur_prov);
  param.ajouter("seuil_generation_solveur",&seuil_generation_solveur_);
  param.ajouter("seuil_test_preliminaire_solveur",&seuil_test_preliminaire_solveur_);
  param.ajouter("seuil_verification_solveur",&seuil_verification_solveur_);
  param.ajouter( "resolution_explicite_diffusion_implicite",&seuil_diffusion_implicite_);
  param.ajouter_flag( "resolution_explicite",&calcul_explicite_);
  param.ajouter( "equation_frequence_resolue",&eq_freq_resolue);
  param.lire_avec_accolades_depuis(is);
  if (param.get_list_mots_lus().rang("seuil_test_preliminaire_solveur")>0)
    seuil_test_preliminaire_lu_=1;
  if (seuil_convergence_solveur_prov>0)
    set_seuil_solveur_avec_seuil_convergence_solveur(seuil_convergence_solveur_prov);
  if (seuil_diffusion_implicite_>0)
    calcul_explicite_=1;
  equation_frequence_resolue_.setString(eq_freq_resolue);
  equation_frequence_resolue_.parseString();
  le_solveur_.nommer("solveur_implicite");
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), calcul_explicite_, equation_frequence_resolue_, Param::get_list_mots_lus(), le_solveur_, Param::lire_avec_accolades_depuis(), SolveurSys::nommer(), Parser_U::parseString(), Objet_U::que_suis_je(), List_Nom::rang(), set_seuil_solveur_avec_seuil_convergence_solveur(), Parser_U::setString(), seuil_convergence_implicite_, seuil_diffusion_implicite_, seuil_generation_solveur_, seuil_test_preliminaire_lu_, seuil_test_preliminaire_solveur_, and seuil_verification_solveur_.
self_cast() [1/2]
const Parametre_implicite & Parametre_implicite::self_cast (const Objet_U & r) static
Definition at line 19 of file Parametre_implicite.cpp.
self_cast() [2/2]
Parametre_implicite & Parametre_implicite::self_cast (Objet_U & r) static
Definition at line 19 of file Parametre_implicite.cpp.
set_seuil_solveur_avec_seuil_convergence_solveur()
void Parametre_implicite::set_seuil_solveur_avec_seuil_convergence_solveur (double seuil_convergence_solveur)
permet de mettre les seuils equivalents a ceux de la 161
pour l'instant warning ensuite ereur.
Definition at line 83 of file Parametre_implicite.cpp.
{
  if (seuil_convergence_solveur<0)
    return;
  Cerr<< "Warning: using of seuil_convergence_solveur is obsolete, use seuil_generation_solveur,seuil_test_preliminaire_solveur,seuil_verification_solveur "<<finl;
  /*
    #ifndef NDEBUG
    Cerr << "This warning is an error when using a debug TRUST version." << finl;
    Process::exit();
    #endif
  */
  if (seuil_generation_solveur_<0)
    seuil_generation_solveur_=seuil_convergence_solveur;
  else
    {
      Cerr<< "You can not use seuil_generation_solveur and seuil_convergence_solveur in the same block" <<finl;
      exit();
    }
  if (seuil_verification_solveur_<0)
    seuil_verification_solveur_=seuil_convergence_solveur;
  else
    {
      Cerr<< "You can not use seuil_verification_solveur and seuil_convergence_solveur in the same block" <<finl;
      exit();
    }
  if (seuil_test_preliminaire_solveur_<0)
    seuil_test_preliminaire_solveur_=seuil_convergence_solveur;
  else
    {
      Cerr<< "You can not use seuil_test_preliminaire_solveur and seuil_convergence_solveur in the same block" <<finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, seuil_generation_solveur_, seuil_test_preliminaire_solveur_, and seuil_verification_solveur_.
Referenced by readOn(), and Simpler_Base::readOn().
seuil_convergence_implicite()
double & Parametre_implicite::seuil_convergence_implicite () inline
Definition at line 60 of file Parametre_implicite.h.
  {
    return  seuil_convergence_implicite_ ;
  };
References seuil_convergence_implicite_.
Referenced by Simpler_Base::get_and_set_parametre_equation(), Simple::iterer_eqn(), Simple::iterer_eqs(), Parametre_implicite(), and Simpler_Base::readOn().
seuil_diffusion_implicite()
double & Parametre_implicite::seuil_diffusion_implicite () inline
Definition at line 64 of file Parametre_implicite.h.
  {
    return  seuil_diffusion_implicite_ ;
  };
References seuil_diffusion_implicite_.
Referenced by Simple::iterer_eqn().
seuil_generation_solveur()
double & Parametre_implicite::seuil_generation_solveur () inline
Definition at line 47 of file Parametre_implicite.h.
  {
    return  seuil_generation_solveur_ ;
  };
References seuil_generation_solveur_.
Referenced by Simpler_Base::readOn().
seuil_test_preliminaire_lu()
int Parametre_implicite::seuil_test_preliminaire_lu () const inline
Definition at line 83 of file Parametre_implicite.h.
  {
    return seuil_test_preliminaire_lu_;
  };
References seuil_test_preliminaire_lu_.
Referenced by Simpler_Base::get_and_set_parametre_equation().
seuil_test_preliminaire_solveur()
double & Parametre_implicite::seuil_test_preliminaire_solveur () inline
Definition at line 55 of file Parametre_implicite.h.
  {
    return  seuil_test_preliminaire_solveur_ ;
  };
References seuil_test_preliminaire_solveur_.
Referenced by Simpler_Base::get_and_set_parametre_equation(), Simple::iterer_eqn(), and Simpler_Base::readOn().
seuil_verification_solveur()
double & Parametre_implicite::seuil_verification_solveur () inline
Definition at line 51 of file Parametre_implicite.h.
  {
    return  seuil_verification_solveur_ ;
  } ;
References seuil_verification_solveur_.
Referenced by Simpler_Base::get_and_set_parametre_equation(), Simple::iterer_eqn(), and Simpler_Base::readOn().
solveur() [1/2]
SolveurSys & Parametre_implicite::solveur () inline
Definition at line 39 of file Parametre_implicite.h.
  {
    return le_solveur_ ;
  };
References le_solveur_.
Referenced by Simpler_Base::get_and_set_parametre_equation(), Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), and Simpler_Base::readOn().
solveur() [2/2]
const SolveurSys & Parametre_implicite::solveur () const inline
Definition at line 43 of file Parametre_implicite.h.
  {
    return le_solveur_ ;
  };
References le_solveur_.
taille_memoire()
unsigned Parametre_implicite::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Parametre_implicite.cpp.
Member Data Documentation
calcul_explicite_
int Parametre_implicite::calcul_explicite_ protected
Definition at line 92 of file Parametre_implicite.h.
Referenced by calcul_explicite(), Parametre_implicite(), and readOn().
equation_frequence_resolue_
Parser_U Parametre_implicite::equation_frequence_resolue_ protected
Definition at line 94 of file Parametre_implicite.h.
Referenced by equation_frequence_resolue(), Parametre_implicite(), and readOn().
info_obj
const Type_info Parametre_implicite::info_obj static
Definition at line 37 of file Parametre_implicite.h.
le_solveur_
SolveurSys Parametre_implicite::le_solveur_ protected
Definition at line 88 of file Parametre_implicite.h.
Referenced by readOn(), and solveur().
nb_it_max_
int Parametre_implicite::nb_it_max_ protected
Definition at line 92 of file Parametre_implicite.h.
Referenced by nb_it_max(), and Parametre_implicite().
seuil_convergence_implicite_
double Parametre_implicite::seuil_convergence_implicite_ protected
Definition at line 91 of file Parametre_implicite.h.
Referenced by readOn(), and seuil_convergence_implicite().
seuil_diffusion_implicite_
double Parametre_implicite::seuil_diffusion_implicite_ protected
Definition at line 93 of file Parametre_implicite.h.
Referenced by Parametre_implicite(), readOn(), and seuil_diffusion_implicite().
seuil_generation_solveur_
double Parametre_implicite::seuil_generation_solveur_ protected
Definition at line 89 of file Parametre_implicite.h.
Referenced by Parametre_implicite(), readOn(), set_seuil_solveur_avec_seuil_convergence_solveur(), and seuil_generation_solveur().
seuil_test_preliminaire_lu_
int Parametre_implicite::seuil_test_preliminaire_lu_ protected
Definition at line 90 of file Parametre_implicite.h.
Referenced by Parametre_implicite(), readOn(), and seuil_test_preliminaire_lu().
seuil_test_preliminaire_solveur_
double Parametre_implicite::seuil_test_preliminaire_solveur_ protected
Definition at line 89 of file Parametre_implicite.h.
Referenced by Parametre_implicite(), readOn(), set_seuil_solveur_avec_seuil_convergence_solveur(), and seuil_test_preliminaire_solveur().
seuil_verification_solveur_
double Parametre_implicite::seuil_verification_solveur_ protected
Definition at line 89 of file Parametre_implicite.h.
Referenced by Parametre_implicite(), readOn(), set_seuil_solveur_avec_seuil_convergence_solveur(), and seuil_verification_solveur().
The documentation for this class was generated from the following files:
src/Kernel/Solveurs/Parametre_implicite.h
src/Kernel/Solveurs/Parametre_implicite.cpp