TRUST: Polynome Class Reference
Polynome Class Reference
Polynome a n variables, n <= 4
Implementation des coefficients a l'aide d'un DoubleTab.
#include <Polynome.h>
Public Member Functions
Polynome ()
~Polynome ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Polynome (int n1)
Construction d'un polynome a une variable de degre n1.
Polynome (int n1, int n2)
Construction d'un polynome a 2 variables de degres n1 et n2.
Polynome (int n1, int n2, int n3)
Construction d'un polynome a 3 variables de degres n1, n2 et n3.
Polynome (int n1, int n2, int n3, int n4)
Construction d'un polynome a 4 variables de degres n1, n2, n3 et n4.
Polynome (const DoubleTab &)
Construction d'un polynome a partir du tableau de ses coefficients.
int degre (int) const
Retourne le degre du polynome par rapport a la ieme variable.
double & coeff (int n1)
Retourne le coefficient du terme de degre n1.
double & coeff (int n1, int n2)
Retourne le coefficient du terme de degre n1,n2.
double & coeff (int n1, int n2, int n3)
Retourne le coefficient du terme de degre n1,n2,n3.
double & coeff (int n1, int n2, int n3, int n4)
Retourne le coefficient du terme de degre n1,n2,n3,n4.
double coeff (int n1) const
Retourne le coefficient du terme de degre n1.
double coeff (int n1, int n2) const
Retourne le coefficient du terme de degre n1,n2.
double coeff (int n1, int n2, int n3) const
Retourne le coefficient du terme de degre n1,n2,n3.
double coeff (int n1, int n2, int n3, int n4) const
Retourne le coefficient du terme de degre n1,n2,n3,n4.
double operator() (double x1) const
Calcul de la valeur du polynome au point x1.
double operator() (double x1, double x2) const
Calcul de la valeur du polynome au point x1,x2.
double operator() (double x1, double x2, double x3) const
Calcul de la valeur du polynome au point x1,x2,x3.
double operator() (double x1, double x2, double x3, double x4) const
Calcul de la valeur du polynome au point x1,x2,x3,x4.
void derive (int=0)
Non code. Ne fait rien.
void integre (int=0)
Non code. Ne fait rien.
double derive (double x1) const
Non code. retourne 0.
double derive (double x1, double x2) const
Non code. retourne 0.
double derive (double x1, double x2, double x3) const
Non code. retourne 0.
double derive (double x1, double x2, double x3, double x4) const
Non code. retourne 0.
double integre (double x1) const
Non code. retourne 0.
double integre (double x1, double x2) const
Non code. retourne 0.
double integre (double x1, double x2, double x3) const
Non code. retourne 0.
double integre (double x1, double x2, double x3, double x4) const
Non code. retourne 0.
Polynome & operator+= (const Polynome &)
Non code. Ne fait rien. Retourne *this.
Polynome & operator-= (const Polynome &)
Non code. Ne fait rien. Retourne *this.
Polynome & operator*= (const Polynome &)
Non code. Ne fait rien. Retourne *this.
Polynome & operator*= (double)
Non code. Ne fait rien. Retourne *this.
Polynome & operator/= (double)
Non code. Ne fait rien. Retourne *this.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Polynome & self_cast (Objet_U &)
static const Polynome & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture sur un flot de sortie
Ecrit le tableau des coefficients.
Entree & readOn (Entree &) override
Lecture dans un flot d'entree
Lecture du tableau des coefficients.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
DoubleTab coeff_
Detailed Description
Polynome a n variables, n <= 4
Implementation des coefficients a l'aide d'un DoubleTab.
Definition at line 29 of file Polynome.h.
Constructor & Destructor Documentation
Polynome() [1/6]
Polynome::Polynome ()
Definition at line 18 of file Polynome.cpp.
~Polynome()
Polynome::~Polynome ()
Definition at line 18 of file Polynome.cpp.
Polynome() [2/6]
Polynome::Polynome (int n1) inline
Construction d'un polynome a une variable de degre n1.
Definition at line 92 of file Polynome.h.
: coeff_(++n1) {}
Polynome() [3/6]
Polynome::Polynome (int n1, int n2) inline
Construction d'un polynome a 2 variables de degres n1 et n2.
Definition at line 113 of file Polynome.h.
: coeff_(++n1, ++n2) {}
Polynome() [4/6]
Polynome::Polynome (int n1, int n2, int n3) inline
Construction d'un polynome a 3 variables de degres n1, n2 et n3.
Definition at line 139 of file Polynome.h.
: coeff_(++n1, ++n2, ++n3) {}
Polynome() [5/6]
Polynome::Polynome (int n1, int n2, int n3, int n4) inline
Construction d'un polynome a 4 variables de degres n1, n2, n3 et n4.
Definition at line 170 of file Polynome.h.
: coeff_(++n1, ++n2, ++n3, ++n4) {}
Polynome() [6/6]
Polynome::Polynome (const DoubleTab & t) inline
Construction d'un polynome a partir du tableau de ses coefficients.
Definition at line 186 of file Polynome.h.
: coeff_(t) {}
Member Function Documentation
coeff() [1/8]
double & Polynome::coeff (int n1) inline
Retourne le coefficient du terme de degre n1.
Returns
double&
Signification: coefficient
Contraintes:
Definition at line 221 of file Polynome.h.
{
  return coeff_(n1);
}
References coeff_.
coeff() [2/8]
double Polynome::coeff (int n1) const inline
Retourne le coefficient du terme de degre n1.
Returns
double
Signification: coefficient
Contraintes:
Definition at line 327 of file Polynome.h.
{
  return coeff_(n1);
}
References coeff_.
coeff() [3/8]
double & Polynome::coeff (int n1, int n2) inline
Retourne le coefficient du terme de degre n1,n2.
Returns
double&
Signification: coefficient
Contraintes:
Definition at line 245 of file Polynome.h.
{
  return coeff_(n1, n2);
}
References coeff_.
coeff() [4/8]
double Polynome::coeff (int n1, int n2) const inline
Retourne le coefficient du terme de degre n1,n2.
Returns
double
Signification: coefficient
Contraintes:
Definition at line 351 of file Polynome.h.
{
  return coeff_(n1, n2);
}
References coeff_.
coeff() [5/8]
double & Polynome::coeff (int n1, int n2, int n3) inline
Retourne le coefficient du terme de degre n1,n2,n3.
Returns
double&
Signification: coefficient
Contraintes:
Definition at line 274 of file Polynome.h.
{
  return coeff_(n1, n2, n3);
}
References coeff_.
coeff() [6/8]
double Polynome::coeff (int n1, int n2, int n3) const inline
Retourne le coefficient du terme de degre n1,n2,n3.
Returns
double
Signification: coefficient
Contraintes:
Definition at line 380 of file Polynome.h.
{
  return coeff_(n1, n2, n3);
}
References coeff_.
coeff() [7/8]
double & Polynome::coeff (int n1, int n2, int n3, int n4) inline
Retourne le coefficient du terme de degre n1,n2,n3,n4.
Returns
double&
Signification: coefficient
Contraintes:
Definition at line 308 of file Polynome.h.
{
  return coeff_(n1, n2, n3, n4);
}
References coeff_.
coeff() [8/8]
double Polynome::coeff (int n1, int n2, int n3, int n4) const inline
Retourne le coefficient du terme de degre n1,n2,n3,n4.
Returns
double
Signification: coefficient
Contraintes:
Definition at line 414 of file Polynome.h.
{
  return coeff_(n1, n2, n3, n4);
}
References coeff_.
cree_instance()
Objet_U * Polynome::cree_instance () static
Definition at line 18 of file Polynome.cpp.
degre()
int Polynome::degre (int i) const inline
Retourne le degre du polynome par rapport a la ieme variable.
Returns
int
Signification: degre du polynome
Contraintes:
Definition at line 202 of file Polynome.h.
{
  return coeff_.dimension(i)-1;
}
References coeff_, and TRUSTTab< _TYPE_ >::dimension().
derive() [1/5]
double Polynome::derive (double x1) const
Non code. retourne 0.
Definition at line 326 of file Polynome.cpp.
{
  return 0;
}
derive() [2/5]
double Polynome::derive (double x1, double x2) const
Non code. retourne 0.
Definition at line 345 of file Polynome.cpp.
{
  return 0;
}
derive() [3/5]
double Polynome::derive (double x1, double x2, double x3) const
Non code. retourne 0.
Definition at line 364 of file Polynome.cpp.
{
  return 0;
}
derive() [4/5]
double Polynome::derive (double x1, double x2, double x3, double x4) const
Non code. retourne 0.
Definition at line 383 of file Polynome.cpp.
{
  return 0;
}
derive() [5/5]
void Polynome::derive (int = 0)
Non code. Ne fait rien.
Definition at line 289 of file Polynome.cpp.
{
}
duplique()
int Polynome::duplique () const override virtual
Implements Objet_U.
Definition at line 18 of file Polynome.cpp.
get_info()
const Type_info * Polynome::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 18 of file Polynome.cpp.
info()
const Type_info * Polynome::info () static
Definition at line 18 of file Polynome.cpp.
integre() [1/5]
double Polynome::integre (double x1) const
Non code. retourne 0.
Definition at line 403 of file Polynome.cpp.
{
  return 0;
}
integre() [2/5]
double Polynome::integre (double x1, double x2) const
Non code. retourne 0.
Definition at line 422 of file Polynome.cpp.
{
  return 0;
}
integre() [3/5]
double Polynome::integre (double x1, double x2, double x3) const
Non code. retourne 0.
Definition at line 441 of file Polynome.cpp.
{
  return 0;
}
integre() [4/5]
double Polynome::integre (double x1, double x2, double x3, double x4) const
Non code. retourne 0.
Definition at line 460 of file Polynome.cpp.
{
  return 0;
}
integre() [5/5]
void Polynome::integre (int = 0)
Non code. Ne fait rien.
Definition at line 307 of file Polynome.cpp.
{
}
operator()() [1/4]
double Polynome::operator() (double x1) const
Calcul de la valeur du polynome au point x1.
Returns
double
Signification: valeur du polynome
Contraintes:
Definition at line 80 of file Polynome.cpp.
{
  int n=coeff_.dimension(0);
  int i=0;
  double xi=1;
  double sum=0;
  while(n--)
    {
      sum+=coeff_(i++)*xi;
      xi*=x1;
    }
  return sum;
}
References coeff_, and TRUSTTab< _TYPE_ >::dimension().
operator()() [2/4]
double Polynome::operator() (double x1, double x2) const
Calcul de la valeur du polynome au point x1,x2.
Returns
double
Signification: valeur du polynome
Contraintes:
Definition at line 113 of file Polynome.cpp.
{
  int n1=coeff_.dimension(0);
  int n2=coeff_.dimension(1);
  int i=0;
  int j=0;
  double xi=1;
  double xj=1;
  double sum=0;
  while(n1--)
    {
      xj=1.;
      n2=coeff_.dimension(1);
      j=0;
      while(n2--)
        {
          sum+=coeff_(i,j++)*xj*xi;
          xj*=x2;
        }
      xi*=x1;
      i++;
    }
  return sum;
}
References coeff_, and TRUSTTab< _TYPE_ >::dimension().
operator()() [3/4]
double Polynome::operator() (double x1, double x2, double x3) const
Calcul de la valeur du polynome au point x1,x2,x3.
Returns
double
Signification: valeur du polynome
Contraintes:
Definition at line 162 of file Polynome.cpp.
{
  int n1=coeff_.dimension(0);
  int n2=coeff_.dimension(1);
  int n3=coeff_.dimension(2);
  int i=0;
  int j=0;
  int k=0;
  double xi=1;
  double xj=1;
  double xk=1;
  double sum=0;
  while(n1--)
    {
      xj=1.;
      n2=coeff_.dimension(1);
      j=0;
      while(n2--)
        {
          xk=1.;
          n3=coeff_.dimension(2);
          k=0;
          while(n3--)
            {
              sum+=coeff_(i,j,k++)*xk*xj*xi;
              xk*=x3;
            }
          xj*=x2;
          j++;
        }
      xi*=x1;
      i++;
    }
  return sum;
}
References coeff_, and TRUSTTab< _TYPE_ >::dimension().
operator()() [4/4]
double Polynome::operator() (double x1, double x2, double x3, double x4) const
Calcul de la valeur du polynome au point x1,x2,x3,x4.
Returns
double
Signification: valeur du polynome
Contraintes:
Definition at line 227 of file Polynome.cpp.
{
  int n1=coeff_.dimension(0);
  int n2=coeff_.dimension(1);
  int n3=coeff_.dimension(2);
  int n4=coeff_.dimension(3);
  int i=0;
  int j=0;
  int k=0;
  int l=0;
  double xi=1;
  double xj=1;
  double xk=1;
  double xl=1;
  double sum=0;
  while(n1--)
    {
      xj=1.;
      n2=coeff_.dimension(1);
      j=0;
      while(n2--)
        {
          xk=1.;
          n3=coeff_.dimension(2);
          k=0;
          while(n3--)
            {
              xl=1.;
              n4=coeff_.dimension(3);
              l=0;
              while(n4--)
                {
                  sum+=coeff_(i,j,k,l++)*xl*xk*xj*xi;
                  xl*=x4;
                }
              xk*=x3;
              k++;
            }
          xj*=x2;
          j++;
        }
      xi*=x1;
      i++;
    }
  return sum;
}
References coeff_, and TRUSTTab< _TYPE_ >::dimension().
operator*=() [1/2]
Polynome & Polynome::operator*= (const Polynome &)
Non code. Ne fait rien. Retourne *this.
Definition at line 518 of file Polynome.cpp.
{
  return *this;
}
operator*=() [2/2]
Polynome & Polynome::operator*= (double)
Non code. Ne fait rien. Retourne *this.
Definition at line 537 of file Polynome.cpp.
{
  return *this;
}
operator+=()
Polynome & Polynome::operator+= (const Polynome &)
Non code. Ne fait rien. Retourne *this.
Definition at line 480 of file Polynome.cpp.
{
  return *this;
}
operator-=()
Polynome & Polynome::operator-= (const Polynome &)
Non code. Ne fait rien. Retourne *this.
Definition at line 499 of file Polynome.cpp.
{
  return *this;
}
operator/=()
Polynome & Polynome::operator/= (double)
Non code. Ne fait rien. Retourne *this.
Definition at line 556 of file Polynome.cpp.
{
  return *this;
}
printOn()
Sortie & Polynome::printOn (Sortie & os) const override protected virtual
Ecriture sur un flot de sortie
Ecrit le tableau des coefficients.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 37 of file Polynome.cpp.
{
  os << coeff_;
  return os;
}
References coeff_.
readOn()
Entree & Polynome::readOn (Entree & is) override protected virtual
Lecture dans un flot d'entree
Lecture du tableau des coefficients.
Returns
Entree& le flot d'entree modifie
Signification:
Contraintes:
Reimplemented from Objet_U.
Definition at line 59 of file Polynome.cpp.
{
  is >> coeff_;
  return is;
}
References coeff_.
self_cast() [1/2]
const Polynome & Polynome::self_cast (const Objet_U & r) static
Definition at line 18 of file Polynome.cpp.
self_cast() [2/2]
Polynome & Polynome::self_cast (Objet_U & r) static
Definition at line 18 of file Polynome.cpp.
taille_memoire()
unsigned Polynome::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 18 of file Polynome.cpp.
Member Data Documentation
coeff_
DoubleTab Polynome::coeff_ private
Definition at line 73 of file Polynome.h.
Referenced by coeff(), degre(), operator()(), printOn(), and readOn().
info_obj
const Type_info Polynome::info_obj static
Definition at line 31 of file Polynome.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Polynome.h
src/Kernel/Math/Polynome.cpp