TRUST: Op_Diff_VDF_var_Face_Axi Class Reference
Op_Diff_VDF_var_Face_Axi Class Reference
class Op_Diff_VDF_var_Face_Axi
Cette classe represente l'operateur de diffusion associe aux
equations de quantite de mouvement en coordonnees cylindriques.
La discretisation est VDF
Le champ diffuse est un Champ_Face
Le champ de diffusivite n'est pas uniforme
Cette classe n'utilise ni iterateur ni evaluateur (il y avait
trop de termes supplementaires dus aux coordonnees cylindriques)
#include <Op_Diff_VDF_var_Face_Axi.h>
Public Member Functions
Op_Diff_VDF_var_Face_Axi ()
~Op_Diff_VDF_var_Face_Axi ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
complete l'iterateur et l'evaluateur
void associer_diffusivite (const Champ_base &)
associe le champ de diffusivite a l'evaluateur
const Champ_base & diffusivite () const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
ajoute la contribution de la diffusion au second membre resu
renvoie resu
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
calcule la contribution de la diffusion, la range dans resu
renvoie resu
double calculer_dt_stab () const
Calcul dt_stab.
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_VDF_var_Face_Axi & self_cast (Objet_U &)
static const
Op_Diff_VDF_var_Face_Axi & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_Face inconnue
Ref_Zone_VDF la_zone_vdf
Ref_Zone_Cl_VDF la_zcl_vdf
Ref_Champ_base diffusivite_
DoubleVect surface
DoubleVect volumes_entrelaces
IntVect orientation
DoubleVect porosite
DoubleTab xp
DoubleTab xv
IntTab Qdm
IntTab face_voisins
IntTab elem_faces
IntVect type_arete_bord
Detailed Description
class Op_Diff_VDF_var_Face_Axi
Cette classe represente l'operateur de diffusion associe aux
equations de quantite de mouvement en coordonnees cylindriques.
La discretisation est VDF
Le champ diffuse est un Champ_Face
Le champ de diffusivite n'est pas uniforme
Cette classe n'utilise ni iterateur ni evaluateur (il y avait
trop de termes supplementaires dus aux coordonnees cylindriques)
Definition at line 51 of file Op_Diff_VDF_var_Face_Axi.h.
Constructor & Destructor Documentation
Op_Diff_VDF_var_Face_Axi::Op_Diff_VDF_var_Face_Axi ()
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
Op_Diff_VDF_var_Face_Axi::~Op_Diff_VDF_var_Face_Axi ()
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
Member Function Documentation
DoubleTab & Op_Diff_VDF_var_Face_Axi::ajouter (const DoubleTab & inco, DoubleTab & resu) const [virtual]
ajoute la contribution de la diffusion au second membre resu
renvoie resu
< bord d'equation R = cte
< flux de tau12 a travers le bord
< bord d'equation teta = cte
< flux de tau21 a travers le bord
< flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
< flux de tau31 a travers le bord
< if (ori3 == 1) flux de tau32 a travers le bord
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Reimplemented from Op_Diff_VDF_base.
Definition at line 75 of file Op_Diff_VDF_var_Face_Axi.cpp.
References Cerr, Champ_Face_get_val_imp_face_bord(), compteur, diffusivite_, Objet_U::dimension, elem_faces, est_egal(), Process::exit(), face_voisins, finl, TypeAreteBordVDF::FLUIDE_FLUIDE, inconnue, la_zcl_vdf, la_zone_vdf, M_PI, Zone_VDF::nb_aretes(), Zone_VDF::nb_aretes_bord(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_mixte(), Zone_VF::premiere_face_bord(), Qdm, surface, type_arete_bord, Ref_Zone_VDF::valeur(), volumes_entrelaces, xp, and xv.
Referenced by calculer().
{
  if (inco.nb_dim() > 1)
    {
      Cerr << "Erreur dans Op_Diff_VDF_var_Face_Axi::ajouter" << finl;
      Cerr << "On ne sait pas traiter la diffusion d'un Champ_Face a plusieurs inconnues" << finl;
      exit();
    }
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const DoubleVect& tab_diffusivite = diffusivite_->valeurs();
  double db_diffusivite;
  double d_teta;
  double tau11, tau22, tau12, tau21, R;
  double tau13, tau31, tau23, tau32, tau33;
  int fac1,fac2,fac3,fac4,signe;
  int n_type;
  double coef_laplacien_axi;
// int nb_faces_elem = zvdf.zone().nb_faces_elem();
  double deux_pi = M_PI*2.0;
// Boucle sur les elements
  int fx0,fx1,fy0,fy1;
  double flux_X,flux_Y;
  for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
    {
      fx0 = elem_faces(num_elem,0);
      fx1 = elem_faces(num_elem,dimension);
      fy0 = elem_faces(num_elem,1);
      fy1 = elem_faces(num_elem,1+dimension);
// Calcul de tau11
      tau11 = (inco[fx1]-inco[fx0])/(xv(fx1,0) - xv(fx0,0));
// Calcul de tau22
      R = xp(num_elem,0);
      d_teta = xv(fy1,1) - xv(fy0,1);
      if (d_teta < 0)
        d_teta += deux_pi;
      tau22 =  (inco[fy1]-inco[fy0])/(R*d_teta);
// termes supplementaires en axi
      tau22 += 0.5*(inco[fx0]+inco[fx1])/R;
      flux_X = tau11*tab_diffusivite(num_elem)*0.5*(surface(fx0)+surface(fx1));
      flux_Y = tau22*tab_diffusivite(num_elem)*0.5*(surface(fy0)+surface(fy1));
      resu[fx0] += flux_X;
      resu[fx1] -= flux_X;
      resu[fy0] += flux_Y;
      resu[fy1] -= flux_Y;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
      coef_laplacien_axi = +0.5*tau22*tab_diffusivite(num_elem);
      resu[fx0] -= coef_laplacien_axi*volumes_entrelaces(fx0)*porosite(fx0)/xv(fx0,0);
      resu[fx1] -= coef_laplacien_axi*volumes_entrelaces(fx1)*porosite(fx1)/xv(fx1,0);
    }
  if (dimension == 3)
    {
      int fz0,fz1;
      double flux_Z;
      for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
        {
          fz0 = elem_faces(num_elem,2);
          fz1 = elem_faces(num_elem,2+dimension);
// Calcul de tau33
          tau33 = (inco[fz1]-inco[fz0])/(xv(fz1,2) - xv(fz0,2));
          flux_Z = tau33*tab_diffusivite(num_elem)*0.5*(surface(fz0)+surface(fz1));
          resu[fz0] += flux_Z;
          resu[fz1] -= flux_Z;
        }
    }
// Boucle sur les aretes bord
  int n_arete;
  int ndeb = zvdf.premiere_arete_bord();
  int nfin = ndeb + zvdf.nb_aretes_bord();
  double dist3;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI:
// paroi-paroi
        case TypeAreteBordVDF::FLUIDE_FLUIDE:
// fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE:
// paroi-fluide
          {
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            int ori1 = orientation(fac1);
            int ori3 = orientation(fac3);
            int rang1 = fac1 - zvdf.premiere_face_bord();
            int rang2 = fac2 - zvdf.premiere_face_bord();
            double vit_imp;
            if (n_type == TypeAreteBordVDF::PAROI_FLUIDE)
// arete paroi_fluide :il faut determiner qui est la face fluide
              {
                if (est_egal(inco[fac1],0))
                  vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori3,la_zcl_vdf);
                else
                  vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori3,la_zcl_vdf);
              }
            else
              vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori3,la_zcl_vdf)+
                             Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori3,la_zcl_vdf));
            db_diffusivite =0.5*(tab_diffusivite(face_voisins(fac3,0))+tab_diffusivite(face_voisins(fac3,1)));
            if (ori1 == 0) //!< bord d'equation R = cte
              {
                double flux1;
                if (ori3 == 1)  //!< flux de tau12 a travers le bord
                  {
                    dist3 = xv(fac3,0)-xv(fac1,0);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau12 = (inco[fac3]-vit_imp)/dist3;
                    flux1 = db_diffusivite*tau12*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 2)  flux de tau13 a travers le bord
                  {
                    assert(ori3 == 2);
                    dist3 = xv(fac3,0)-xv(fac1,0);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau13 =   (inco[fac3]-vit_imp)/dist3;
                    flux1 = db_diffusivite*tau13*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3]+=signe*flux1;
// Calcul de flux1_2 a coder
// resu[fac1] += flux1_2;
// resu[fac2] -= flux1_2;
              }
            else if (ori1 == 1) //!< bord d'equation teta = cte
              {
                R = xv(fac3,0);
                d_teta = xv(fac3,1) - xv(fac1,1);
                if (d_teta < 0)
                  d_teta += deux_pi;
                dist3  = R*d_teta;
                if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                  dist3 *= 1;
                if (ori3 == 0) //!< flux de tau21 a travers le bord
                  {
                    tau21 = (inco[fac3]-vit_imp)/dist3;
// Terme supplementaire en axi
                    tau21 -= 0.5*(inco[fac1]+inco[fac2])/R;
                    double flux2;
                    flux2 = db_diffusivite*tau21*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                    resu[fac3]+=signe*flux2;
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
                    coef_laplacien_axi = 0.5*db_diffusivite*tau21;
                    resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                    resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                  }
                else if (ori3 == 2) //!< flux de tau23 a travers le bord
                  {
                    double flux3;
                    tau23 = (inco[fac3]-vit_imp)/dist3;
                    flux3 = db_diffusivite*tau23*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                    resu[fac3]+=signe*flux3;
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                double flux3;
                if (ori3 == 0)  //!< flux de tau31 a travers le bord
                  {
                    dist3 = xv(fac3,2)-xv(fac1,2);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau31 = (inco[fac3]-vit_imp)/dist3;
                    flux3 = db_diffusivite*tau31*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                else //!< if (ori3 == 1)  flux de tau32 a travers le bord
                  {
                    assert(ori3 == 1) ;
                    dist3 = xv(fac3,2)-xv(fac1,2);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau32 = (inco[fac3]-vit_imp)/dist3;
                    flux3 = db_diffusivite*tau32*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3] += signe*flux3;
              }
            break;
          }
        case 3:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
// Boucle sur les aretes mixtes et internes
  ndeb = zvdf.premiere_arete_mixte();
  nfin = zvdf.nb_aretes();
  int ori1, ori3;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
      db_diffusivite = 0;
      int element,compteur =0;
      if ((element=face_voisins(fac3,0)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      if ((element=face_voisins(fac3,1)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      if ((element=face_voisins(fac4,0)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      if ((element=face_voisins(fac4,1)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      db_diffusivite/=compteur;
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          double flux1;
// Calcul de tau21
          R = xv(fac3,0);
          d_teta = xv(fac4,1) - xv(fac3,1);
          if (d_teta < 0)
            d_teta += deux_pi;
          tau21 = (inco(fac4)-inco(fac3))/(R*d_teta);
// Terme supplementaire en axi
          tau21 -= 0.5*(inco[fac1]+inco[fac2])/R;
// flux de tau21 sur la facette a cheval sur les faces fac1 et fac2
          flux1 = db_diffusivite*tau21*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux1;
          resu(fac4) -= flux1;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
          coef_laplacien_axi = 0.5*db_diffusivite*tau21;
          resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
// Calcul de tau12
          tau12 = (inco(fac2)-inco(fac1))/(xv(fac2,0) - xv(fac1,0));
// flux de tau12 sur la facette a cheval sur les faces fac3 et fac4
          flux1 = db_diffusivite*tau12*0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux1;
          resu(fac2) -= flux1;
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          double flux2;
// Calcul de tau32
          tau32 = (inco(fac4)-inco(fac3))/(xv(fac4,2) - xv(fac3,2));
// flux de tau32 sur la facette a cheval sur les faces fac1 et fac2
          flux2 = db_diffusivite*tau32*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux2;
          resu(fac4) -= flux2;
// Calcul de tau23
          R = xv(fac1,0);
          d_teta = xv(fac2,1) - xv(fac1,1);
          if (d_teta < 0)
            d_teta += deux_pi;
          tau23 = (inco(fac2)-inco(fac1))/(R*d_teta);
// flux de tau23 sur la facette a cheval sur les faces fac3 et fac4
          flux2 = db_diffusivite*tau23*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux2;
          resu(fac2) -= flux2;
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
          double flux3;
// Calcul de tau31
          tau31 = (inco(fac4)-inco(fac3))/(xv(fac4,2) - xv(fac3,2));
// flux de tau31 sur la facette a cheval sur les faces fac1 et fac2
          flux3 = db_diffusivite*tau31*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          resu(fac3) += flux3;
          resu(fac4) -= flux3;
// Calcul de tau13
          tau13 = (inco(fac2)-inco(fac1))/(xv(fac2,0) - xv(fac1,0));
// flux de tau13 sur la facette a cheval sur les faces fac3 et fac4
          flux3 = db_diffusivite*tau13*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          resu(fac1) += flux3;
          resu(fac2) -= flux3;
        }
    }
  return resu;
}
void Op_Diff_VDF_var_Face_Axi::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const
< bord d'equation R = cte
< flux de tau12 a travers le bord
< bord d'equation teta = cte
< flux de tau21 a travers le bord
< flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
< flux de tau31 a travers le bord
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Definition at line 479 of file Op_Diff_VDF_var_Face_Axi.cpp.
References Cerr, coeff, compteur, diffusivite_, Objet_U::dimension, elem_faces, Process::exit(), face_voisins, finl, TypeAreteBordVDF::FLUIDE_FLUIDE, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_zone_vdf, M_PI, Zone_VDF::nb_aretes(), Zone_VDF::nb_aretes_bord(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_mixte(), Qdm, surface, type_arete_bord, Ref_Zone_VDF::valeur(), volumes_entrelaces, xp, and xv.
Referenced by contribuer_a_avec().
{
  if (inco.nb_dim() > 1)
    {
      Cerr << "Erreur dans Op_Diff_VDF_var_Face_Axi::ajouter" << finl;
      Cerr << "On ne sait pas traiter la diffusion d'un Champ_Face a plusieurs inconnues" << finl;
      exit();
    }
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const DoubleVect& tab_diffusivite = diffusivite_->valeurs();
  double db_diffusivite;
  double d_teta;
  double tau11, tau22, tau12, tau21, R;
  double tau13, tau31, tau23, tau32, tau33;
  int fac1,fac2,fac3,fac4,signe;
  int n_type,k;
  double coef_laplacien_axi;
// int nb_faces_elem = zvdf.zone().nb_faces_elem();
  IntVect& tab1 = matrice.get_set_tab1();
  IntVect& tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
  double deux_pi = M_PI*2.0;
// Boucle sur les elements
  int fx0,fx1,fy0,fy1;
  double flux_X,flux_Y;
  for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
    {
      fx0 = elem_faces(num_elem,0);
      fx1 = elem_faces(num_elem,dimension);
      fy0 = elem_faces(num_elem,1);
      fy1 = elem_faces(num_elem,1+dimension);
// Calcul de tau11
      tau11 = 1/(xv(fx1,0) - xv(fx0,0));
// Calcul de tau22
      R = xp(num_elem,0);
      d_teta = xv(fy1,1) - xv(fy0,1);
      if (d_teta < 0)
        d_teta += deux_pi;
      tau22 = 1/(R*d_teta);
// termes supplementaires en axi
      tau22 += 0.5/R;
      flux_X = tau11*tab_diffusivite(num_elem)*0.5*(surface(fx0)+surface(fx1));
      flux_Y = tau22*tab_diffusivite(num_elem)*0.5*(surface(fy0)+surface(fy1));
      for (k=tab1[fx0]-1; k<tab1[fx0+1]-1; k++)
        {
          if (tab2[k]-1==fx0)
            coeff[k]+=flux_X;
          if (tab2[k]-1==fx1)
            coeff[k]-=flux_X;
        }
      for (k=tab1[fx1]-1; k<tab1[fx1+1]-1; k++)
        {
          if (tab2[k]-1==fx0)
            coeff[k]-=flux_X;
          if (tab2[k]-1==fx1)
            coeff[k]+=flux_X;
        }
      for (k=tab1[fy0]-1; k<tab1[fy0+1]-1; k++)
        {
          if (tab2[k]-1==fy0)
            coeff[k]+=flux_Y;
          if (tab2[k]-1==fy1)
            coeff[k]-=flux_Y;
        }
      for (k=tab1[fy1]-1; k<tab1[fy1+1]-1; k++)
        {
          if (tab2[k]-1==fy0)
            coeff[k]-=flux_Y;
          if (tab2[k]-1==fy1)
            coeff[k]+=flux_Y;
        }
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
      coef_laplacien_axi = +0.5*tau22*tab_diffusivite(num_elem);
      for (k=tab1[fx0]-1; k<tab1[fx0+1]-1; k++)
        {
          if (tab2[k]-1==fx0)
            coeff[k]+=coef_laplacien_axi*volumes_entrelaces(fx0)*porosite(fx0)/xv(fx0,0);
        }
      for (k=tab1[fx1]-1; k<tab1[fx1+1]-1; k++)
        {
          if (tab2[k]-1==fx1)
            coeff[k]+=
              coef_laplacien_axi*volumes_entrelaces(fx1)*porosite(fx1)/xv(fx1,0);
        }
    }
  if (dimension == 3)
    {
      int fz0,fz1;
      double flux_Z;
      for (int num_elem=0; num_elem<zvdf.nb_elem(); num_elem++)
        {
          fz0 = elem_faces(num_elem,2);
          fz1 = elem_faces(num_elem,2+dimension);
// Calcul de tau33
          tau33 = 1/(xv(fz1,2) - xv(fz0,2));
          flux_Z = tau33*tab_diffusivite(num_elem)*0.5*(surface(fz0)+surface(fz1));
          for (k=tab1[fz0]-1; k<tab1[fz0+1]-1; k++)
            {
              if (tab2[k]-1==fz0)
                coeff[k]+=flux_Z;
              if (tab2[k]-1==fz1)
                coeff[k]-=flux_Z;
            }
          for (k=tab1[fz1]-1; k<tab1[fz1+1]-1; k++)
            {
              if (tab2[k]-1==fz0)
                coeff[k]-=flux_Z;
              if (tab2[k]-1==fz1)
                coeff[k]+=flux_Z;
            }
        }
    }
// Boucle sur les aretes bord
  int n_arete;
  int ndeb = zvdf.premiere_arete_bord();
  int nfin = ndeb + zvdf.nb_aretes_bord();
  double dist3;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI:
// paroi-paroi
        case TypeAreteBordVDF::FLUIDE_FLUIDE:
// fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE:
// paroi-fluide
          {
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            int ori1 = orientation(fac1);
            int ori3 = orientation(fac3);
            db_diffusivite =0.5*(tab_diffusivite(face_voisins(fac3,0))+tab_diffusivite(face_voisins(fac3,1)));
            if (ori1 == 0) //!< bord d'equation R = cte
              {
                double flux1;
                if (ori3 == 1)  //!< flux de tau12 a travers le bord
                  {
                    dist3 = xv(fac3,0)-xv(fac1,0);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau12 = 1/dist3;
                    flux1 = db_diffusivite*tau12*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 2)  flux de tau13 a travers le bord
                  {
                    assert (ori3 == 2);
                    dist3 = xv(fac3,0)-xv(fac1,0);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau13 =  1/dist3;
                    flux1 = db_diffusivite*tau13*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
                  {
                    if (tab2[k]-1==fac3)
                      coeff[k]+=signe*flux1;
                  }
// Calcul de flux1_2 a coder
// remplir les coeff des face fac1 et fac2
              }
            else if (ori1 == 1) //!< bord d'equation teta = cte
              {
                R = xv(fac3,0);
                d_teta = xv(fac3,1) - xv(fac1,1);
                if (d_teta < 0)
                  d_teta += deux_pi;
                dist3  = R*d_teta;
                if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                  dist3 *= 1;
                if (ori3 == 0) //!< flux de tau21 a travers le bord
                  {
                    double flux2;
                    tau21 = 1/dist3;
// Terme supplementaire en axi
                    tau21 -= 0.5/R;
                    flux2 = db_diffusivite*tau21*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                    for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
                      {
                        if (tab2[k]-1==fac3)
                          coeff[k]+=signe*flux2;
                      }
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
                    coef_laplacien_axi = 0.5*db_diffusivite*tau21;
                    for (k=tab1[fac1]-1; k<tab1[fac1+1]-1; k++)
                      {
                        if (tab2[k]-1==fac1)
                          coeff[k]+=coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                      }
                    for (k=tab1[fac2]-1; k<tab1[fac2+1]-1; k++)
                      {
                        if (tab2[k]-1==fac2)
                          coeff[k]+=coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                      }
                  }
                else if (ori3 == 2) //!< flux de tau23 a travers le bord
                  {
                    double flux3;
                    tau23 = 1/dist3;
                    flux3 = db_diffusivite*tau23*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                    for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
                      {
                        if (tab2[k]-1==fac3)
                          coeff[k]+=signe*flux3;
                      }
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                double flux4;
                if (ori3 == 0)  //!< flux de tau31 a travers le bord
                  {
                    dist3 = xv(fac3,2)-xv(fac1,2);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau31 = 1/dist3;
                    flux4 = db_diffusivite*tau31*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 1)  flux de tau32 a travers le bord
                  {
                    assert(ori3 == 1);
                    dist3 = xv(fac3,2)-xv(fac1,2);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau32 = 1/dist3;
                    flux4 = db_diffusivite*tau32*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
                  {
                    if (tab2[k]-1==fac3)
                      coeff[k]+=signe*flux4;
                  }
              }
            break;
          }
        case 3:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
// Boucle sur les aretes mixtes et internes
  ndeb = zvdf.premiere_arete_mixte();
  nfin = zvdf.nb_aretes();
  int ori1, ori3;
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      fac1=Qdm(n_arete,0);
      fac2=Qdm(n_arete,1);
      fac3=Qdm(n_arete,2);
      fac4=Qdm(n_arete,3);
      ori1 = orientation(fac1);
      ori3 = orientation(fac3);
      db_diffusivite = 0;
      int element,compteur =0;
      if ((element=face_voisins(fac3,0)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      if ((element=face_voisins(fac3,1)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      if ((element=face_voisins(fac4,0)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      if ((element=face_voisins(fac4,1)) != -1)
        {
          db_diffusivite+=tab_diffusivite(element);
          compteur++;
        }
      db_diffusivite/=compteur;
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          double flux1;
// Calcul de tau21
          R = xv(fac3,0);
          d_teta = xv(fac4,1) - xv(fac3,1);
          if (d_teta < 0)
            d_teta += deux_pi;
          tau21 = 1/(R*d_teta);
// Terme supplementaire en axi
          tau21 -= 0.5/R;
// flux de tau21 sur la facette a cheval sur les faces fac1 et fac2
          flux1 = db_diffusivite*tau21*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
            {
              if (tab2[k]-1==fac3)
                coeff[k]+=flux1;
              if (tab2[k]-1==fac4)
                coeff[k]-=flux1;
            }
          for (k=tab1[fac4]-1; k<tab1[fac4+1]-1; k++)
            {
              if (tab2[k]-1==fac3)
                coeff[k]-=flux1;
              if (tab2[k]-1==fac4)
                coeff[k]+=flux1;
            }
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
          coef_laplacien_axi = 0.5*db_diffusivite*tau21;
          for (k=tab1[fac1]-1; k<tab1[fac1+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]+=coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
            }
          for (k=tab1[fac2]-1; k<tab1[fac2+1]-1; k++)
            {
              if (tab2[k]-1==fac2)
                coeff[k]+=coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
            }
// Calcul de tau12
          tau12 = 1/(xv(fac2,0) - xv(fac1,0));
// flux de tau12 sur la facette a cheval sur les faces fac3 et fac4
          flux1 = db_diffusivite*tau12*0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          for (k=tab1[fac1]-1; k<tab1[fac1+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]+=flux1;
              if (tab2[k]-1==fac2)
                coeff[k]-=flux1;
            }
          for (k=tab1[fac2]-1; k<tab1[fac2+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]-=flux1;
              if (tab2[k]-1==fac2)
                coeff[k]+=flux1;
            }
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          double flux2;
// Calcul de tau32
          tau32 = 1/(xv(fac4,2) - xv(fac3,2));
// flux de tau32 sur la facette a cheval sur les faces fac1 et fac2
          flux2 = db_diffusivite*tau32*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
            {
              if (tab2[k]-1==fac3)
                coeff[k]+=flux2;
              if (tab2[k]-1==fac4)
                coeff[k]-=flux2;
            }
          for (k=tab1[fac4]-1; k<tab1[fac4+1]-1; k++)
            {
              if (tab2[k]-1==fac3)
                coeff[k]-=flux2;
              if (tab2[k]-1==fac4)
                coeff[k]+=flux2;
            }
// Calcul de tau23
          R = xv(fac1,0);
          d_teta = xv(fac2,1) - xv(fac1,1);
          if (d_teta < 0)
            d_teta += deux_pi;
          tau23 = 1/(R*d_teta);
// flux de tau23 sur la facette a cheval sur les faces fac3 et fac4
          flux2 = db_diffusivite*tau23*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          for (k=tab1[fac1]-1; k<tab1[fac1+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]+=flux2;
              if (tab2[k]-1==fac2)
                coeff[k]-=flux2;
            }
          for (k=tab1[fac2]-1; k<tab1[fac2+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]-=flux2;
              if (tab2[k]-1==fac2)
                coeff[k]+=flux2;
            }
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
          double flux3;
// Calcul de tau31
          tau31 =1/(xv(fac4,2) - xv(fac3,2));
// flux de tau31 sur la facette a cheval sur les faces fac1 et fac2
          flux3 = db_diffusivite*tau31*0.25*(surface(fac1)+surface(fac2))
                  *(porosite(fac1)+porosite(fac2));
          for (k=tab1[fac3]-1; k<tab1[fac3+1]-1; k++)
            {
              if (tab2[k]-1==fac3)
                coeff[k]+=flux3;
              if (tab2[k]-1==fac4)
                coeff[k]-=flux3;
            }
          for (k=tab1[fac4]-1; k<tab1[fac4+1]-1; k++)
            {
              if (tab2[k]-1==fac3)
                coeff[k]-=flux3;
              if (tab2[k]-1==fac4)
                coeff[k]+=flux3;
            }
// Calcul de tau13
          tau13 = 1/(xv(fac2,0) - xv(fac1,0));
// flux de tau13 sur la facette a cheval sur les faces fac3 et fac4
          flux3 = db_diffusivite*tau13*0.25*(surface(fac3)+surface(fac4))
                  *(porosite(fac3)+porosite(fac4));
          for (k=tab1[fac1]-1; k<tab1[fac1+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]+=flux3;
              if (tab2[k]-1==fac2)
                coeff[k]-=flux3;
            }
          for (k=tab1[fac2]-1; k<tab1[fac2+1]-1; k++)
            {
              if (tab2[k]-1==fac1)
                coeff[k]-=flux3;
              if (tab2[k]-1==fac2)
                coeff[k]+=flux3;
            }
        }
    }
}
void Op_Diff_VDF_var_Face_Axi::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) [virtual]
complete l'iterateur et l'evaluateur
< Evaluateur_VDF::associer_zones (dynamic_cast<Eval_VDF_Face2&>(eval_diff)).associer_inconnue(inco); // Eval_VDF_Face2::associer_inconnue
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 41 of file Op_Diff_VDF_var_Face_Axi.cpp.
References Zone_VF::elem_faces(), elem_faces, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), face_voisins, inconnue, la_zcl_vdf, la_zone_vdf, Zone_VDF::orientation(), orientation, porosite, Zone_VF::porosite_face(), Zone_VDF::Qdm(), Qdm, IntTab::ref(), DoubleTab::ref(), IntVect::ref(), DoubleVect::ref(), ref_cast, surface, type_arete_bord, Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Zone_VF::volumes_entrelaces(), volumes_entrelaces, Zone_VF::xp(), xp, Zone_VF::xv(), and xv.
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  const Champ_Face& inco = ref_cast(Champ_Face,ch_transporte.valeur());
  la_zone_vdf = zvdf;
  la_zcl_vdf = zclvdf;
  inconnue = inco;
  surface.ref(zvdf.face_surfaces());
  volumes_entrelaces.ref(zvdf.volumes_entrelaces());
  orientation.ref(zvdf.orientation());
  porosite.ref(zvdf.porosite_face());
  xp.ref(zvdf.xp());
  xv.ref(zvdf.xv());
  Qdm.ref(zvdf.Qdm());
  face_voisins.ref(zvdf.face_voisins());
  elem_faces.ref(zvdf.elem_faces());
  type_arete_bord.ref(zclvdf.type_arete_bord());
}
void Op_Diff_VDF_var_Face_Axi::associer_diffusivite (const Champ_base & ch_diff) [virtual]
associe le champ de diffusivite a l'evaluateur
< Eval_Diff_VDF::associer
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 65 of file Op_Diff_VDF_var_Face_Axi.cpp.
References diffusivite_.
{
  diffusivite_ = diffu;
}
DoubleTab & Op_Diff_VDF_var_Face_Axi::calculer (const DoubleTab & inco, DoubleTab & resu) const [virtual]
calcule la contribution de la diffusion, la range dans resu
renvoie resu
Reimplemented from Op_Diff_VDF_base.
Definition at line 469 of file Op_Diff_VDF_var_Face_Axi.cpp.
References ajouter().
{
  resu=0;
  return ajouter(inco,resu);
}
double Op_Diff_VDF_var_Face_Axi::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 463 of file Op_Diff_VDF_var_Face_Axi.cpp.
References la_zone_vdf, and Ref_Zone_VDF::valeur().
{
  return Op_Diff_VDF_Face_base::calculer_dt_stab(la_zone_vdf.valeur()) ;
}
void Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre (DoubleTab & resu) const
< bord d'equation R = cte
< flux de tau12 a travers le bord
< if (ori3 == 2) flux de tau13 a travers le bord
< bord d'equation teta = cte
< flux de tau21 a travers le bord
< flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
< flux de tau31 a travers le bord
Definition at line 984 of file Op_Diff_VDF_var_Face_Axi.cpp.
References Cerr, Champ_Face_get_val_imp_face_bord(), diffusivite_, est_egal(), Process::exit(), face_voisins, TypeAreteBordVDF::FLUIDE_FLUIDE, inconnue, la_zcl_vdf, la_zone_vdf, M_PI, Zone_VDF::nb_aretes_bord(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Zone_VF::premiere_face_bord(), Qdm, surface, type_arete_bord, Ref_Champ_Face::valeur(), Ref_Zone_VDF::valeur(), volumes_entrelaces, and xv.
Referenced by contribuer_au_second_membre().
{
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const DoubleVect& tab_diffusivite = diffusivite_->valeurs();
  double db_diffusivite;
// int nb_faces_elem = zvdf.zone().nb_faces_elem();
  double deux_pi = M_PI*2.0;
  double d_teta, coef_laplacien_axi,  dist3;
  double tau12, tau21,R;
  double tau13, tau31, tau23, tau32;
  int fac1,fac2,fac3,signe;
  int n_type;
  int n_arete;
  int ndeb = zvdf.premiere_arete_bord();
  int nfin = ndeb + zvdf.nb_aretes_bord();
  for (n_arete=ndeb; n_arete<nfin; n_arete++)
    {
      n_type=type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI:
// paroi-paroi
        case TypeAreteBordVDF::FLUIDE_FLUIDE:
// fluide-fluide
        case TypeAreteBordVDF::PAROI_FLUIDE:
// paroi-fluide
          {
            fac1 = Qdm(n_arete,0);
            fac2 = Qdm(n_arete,1);
            fac3 = Qdm(n_arete,2);
            signe  = Qdm(n_arete,3);
            int ori1 = orientation(fac1);
            int ori3 = orientation(fac3);
            int rang1 = fac1 - zvdf.premiere_face_bord();
            int rang2 = fac2 - zvdf.premiere_face_bord();
            double vit_imp;
            if (n_type == TypeAreteBordVDF::PAROI_FLUIDE)
// arete paroi_fluide :il faut determiner qui est la face fluide
              {
                if (est_egal(inconnue.valeur()(fac1),0))
                  vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori3,la_zcl_vdf);
                else
                  vit_imp = Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori3,la_zcl_vdf);
              }
            else
              vit_imp = 0.5*(Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang1,ori3,la_zcl_vdf)+
                             Champ_Face_get_val_imp_face_bord(inconnue->temps(),rang2,ori3,la_zcl_vdf));
            db_diffusivite =0.5*(tab_diffusivite(face_voisins(fac3,0))+tab_diffusivite(face_voisins(fac3,1)));
            if (ori1 == 0) //!< bord d'equation R = cte
              {
                double flux1;
                if (ori3 == 1)  //!< flux de tau12 a travers le bord
                  {
                    dist3 = xv(fac3,0)-xv(fac1,0);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau12 = (-vit_imp)/dist3;
                    flux1 = db_diffusivite*tau12*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                else//!< if (ori3 == 2)  flux de tau13 a travers le bord
                  {
                    assert(ori3 == 2);
                    dist3 = xv(fac3,0)-xv(fac1,0);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau13 = (-vit_imp)/dist3;
                    flux1 = db_diffusivite*tau13*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3]+=signe*flux1;
// Calcul de flux1_2 a coder
// resu[fac1] += flux1_2;
// resu[fac2] -= flux1_2;
              }
            else if (ori1 == 1) //!< bord d'equation teta = cte
              {
                double flux2;
                R = xv(fac3,0);
                d_teta = xv(fac3,1) - xv(fac1,1);
                if (d_teta < 0)
                  d_teta += deux_pi;
                dist3  = R*d_teta;
                if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                  dist3 *= 1;
                if (ori3 == 0) //!< flux de tau21 a travers le bord
                  {
                    tau21 = (-vit_imp)/dist3;
// Terme supplementaire en axi
                    flux2 = db_diffusivite*tau21*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                    resu[fac3]+=signe*flux2;
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
// Termes supplementaires dans le laplacien en axi
// Ils sont integres comme des termes sources
                    coef_laplacien_axi = 0.5*db_diffusivite*tau21;
                    resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                    resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                  }
                else if (ori3 == 2) //!< flux de tau23 a travers le bord
                  {
                    double flux3;
                    tau23 = (-vit_imp)/dist3;
                    flux3 = db_diffusivite*tau23*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                    resu[fac3]+=signe*flux3;
// Calcul de flux1_2 a coder
// resu[fac1]+= flux1_2;
// resu[fac2]-= flux1_2;
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                double flux4;
                if (ori3 == 0)  //!< flux de tau31 a travers le bord
                  {
                    dist3 = xv(fac3,2)-xv(fac1,2);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau31 = (-vit_imp)/dist3;
                    flux4 = db_diffusivite*tau31*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 1)  flux de tau32 a travers le bord
                  {
                    assert(ori3 == 1);
                    dist3 = xv(fac3,2)-xv(fac1,2);
                    if (n_type != TypeAreteBordVDF::PAROI_PAROI)
                      dist3 *= 1;
                    tau32 = (-vit_imp)/dist3;
                    flux4 = db_diffusivite*tau32*0.25*(surface(fac1)+surface(fac2))
                            *(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3] += signe*flux4;
              }
            break;
          }
        case 3:
          {
// symetrie-symetrie
// pas de flux diffusif calcule
            break;
          }
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu\n";
            Cerr << "num arete : " << n_arete;
            Cerr << " type : " << n_type;
            exit();
            break;
          }
        }
    }
}
void Op_Diff_VDF_var_Face_Axi::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice.
Reimplemented from Op_Diff_VDF_base.
Definition at line 109 of file Op_Diff_VDF_var_Face_Axi.h.
References ajouter_contribution().
{
  ajouter_contribution(inco, matrice);
}
void Op_Diff_VDF_var_Face_Axi::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Op_Diff_VDF_base.
Definition at line 118 of file Op_Diff_VDF_var_Face_Axi.h.
References contribue_au_second_membre().
{
  contribue_au_second_membre(resu);
}
Objet_U * Op_Diff_VDF_var_Face_Axi::cree_instance () [static]
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
const Champ_base & Op_Diff_VDF_var_Face_Axi::diffusivite () const [virtual]
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 70 of file Op_Diff_VDF_var_Face_Axi.cpp.
References diffusivite_.
{
  return diffusivite_;
}
void Op_Diff_VDF_var_Face_Axi::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice.
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 97 of file Op_Diff_VDF_var_Face_Axi.h.
{
  Op_VDF_Face::dimensionner(la_zone_vdf.valeur(), la_zcl_vdf.valeur(), matrice);
}
int Op_Diff_VDF_var_Face_Axi::duplique () const [virtual]
Implements Op_Diff_VDF_Face_base.
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
const Type_info * Op_Diff_VDF_var_Face_Axi::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
const Type_info * Op_Diff_VDF_var_Face_Axi::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
void Op_Diff_VDF_var_Face_Axi::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 73 of file Op_Diff_VDF_var_Face_Axi.h.
{}
void Op_Diff_VDF_var_Face_Axi::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 101 of file Op_Diff_VDF_var_Face_Axi.h.
References la_zcl_vdf, la_zone_vdf, Ref_Zone_Cl_VDF::valeur(), and Ref_Zone_VDF::valeur().
{
  Op_VDF_Face::modifier_pour_Cl( la_zone_vdf.valeur(), la_zcl_vdf.valeur(), matrice,  secmem);
}
Sortie & Op_Diff_VDF_var_Face_Axi::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 31 of file Op_Diff_VDF_var_Face_Axi.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Diff_VDF_var_Face_Axi::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 36 of file Op_Diff_VDF_var_Face_Axi.cpp.
{
  return s ;
}
Op_Diff_VDF_var_Face_Axi & Op_Diff_VDF_var_Face_Axi::self_cast (Objet_U & r) [static]
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
const Op_Diff_VDF_var_Face_Axi & Op_Diff_VDF_var_Face_Axi::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
unsigned Op_Diff_VDF_var_Face_Axi::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Op_Diff_VDF_var_Face_Axi.cpp.
Member Data Documentation
Ref_Champ_base Op_Diff_VDF_var_Face_Axi::diffusivite_ [protected]
Definition at line 80 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer_diffusivite(), contribue_au_second_membre(), and diffusivite().
IntTab Op_Diff_VDF_var_Face_Axi::elem_faces [protected]
Definition at line 90 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
IntTab Op_Diff_VDF_var_Face_Axi::face_voisins [protected]
Definition at line 89 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
Ref_Champ_Face Op_Diff_VDF_var_Face_Axi::inconnue [protected]
Definition at line 77 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), associer(), and contribue_au_second_membre().
const Type_info Op_Diff_VDF_var_Face_Axi::info_obj [static]
Reimplemented from Op_Diff_VDF_Face_base.
Definition at line 54 of file Op_Diff_VDF_var_Face_Axi.h.
Ref_Zone_Cl_VDF Op_Diff_VDF_var_Face_Axi::la_zcl_vdf [protected]
Definition at line 79 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), associer(), contribue_au_second_membre(), and modifier_pour_Cl().
Ref_Zone_VDF Op_Diff_VDF_var_Face_Axi::la_zone_vdf [protected]
Definition at line 78 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), calculer_dt_stab(), contribue_au_second_membre(), and modifier_pour_Cl().
IntVect Op_Diff_VDF_var_Face_Axi::orientation [protected]
Definition at line 84 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleVect Op_Diff_VDF_var_Face_Axi::porosite [protected]
Definition at line 85 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
IntTab Op_Diff_VDF_var_Face_Axi::Qdm [protected]
Definition at line 88 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleVect Op_Diff_VDF_var_Face_Axi::surface [protected]
Definition at line 82 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
IntVect Op_Diff_VDF_var_Face_Axi::type_arete_bord [protected]
Definition at line 91 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleVect Op_Diff_VDF_var_Face_Axi::volumes_entrelaces [protected]
Definition at line 83 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
DoubleTab Op_Diff_VDF_var_Face_Axi::xp [protected]
Definition at line 86 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
DoubleTab Op_Diff_VDF_var_Face_Axi::xv [protected]
Definition at line 87 of file Op_Diff_VDF_var_Face_Axi.h.
Referenced by ajouter(), ajouter_contribution(), associer(), and contribue_au_second_membre().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Operateurs_Diff/Op_Diff_VDF_var_Face_Axi.h
src/VDF/Operateurs/Operateurs_Diff/Op_Diff_VDF_var_Face_Axi.cpp