TRUST: Echange_EV_Options Class Reference
Echange_EV_Options Class Reference
#include <Echange_EV_Options.h>
Public Types
enum Operation { SYNC , SUM , MAX , MINCOL1 }
enum Items_Communs { ITEMS_COMMUNS_YES , ITEMS_COMMUNS_NO }
enum Items_Virtuels { ITEMS_VIRTUELS_YES , ITEMS_VIRTUELS_NO }
Public Member Functions
Echange_EV_Options (Operation op=SYNC, Items_Communs items_communs=ITEMS_COMMUNS_YES, Items_Virtuels items_virtuels=ITEMS_VIRTUELS_YES)
Operation get_op () const
Items_Communs get_items_communs () const
Items_Virtuels get_items_virtuels () const
int operator== (const Echange_EV_Options &x) const
Protected Attributes
Operation op_
Items_Communs items_communs_
Items_Virtuels items_virtuels_
Detailed Description
Definition at line 19 of file Echange_EV_Options.h.
Member Enumeration Documentation
Items_Communs
enum Echange_EV_Options::Items_Communs
Enumerator
ITEMS_COMMUNS_YES
ITEMS_COMMUNS_NO
Definition at line 31 of file Echange_EV_Options.h.
{ ITEMS_COMMUNS_YES, ITEMS_COMMUNS_NO };
Items_Virtuels
enum Echange_EV_Options::Items_Virtuels
Enumerator
ITEMS_VIRTUELS_YES
ITEMS_VIRTUELS_NO
Definition at line 32 of file Echange_EV_Options.h.
{ ITEMS_VIRTUELS_YES, ITEMS_VIRTUELS_NO };
Operation
enum Echange_EV_Options::Operation
Enumerator
SYNC
SUM
MAX
MINCOL1
Definition at line 30 of file Echange_EV_Options.h.
{ SYNC, SUM, MAX, MINCOL1 };
Constructor & Destructor Documentation
Echange_EV_Options()
Echange_EV_Options::Echange_EV_Options (Operation op = SYNC, Items_Communs items_communs = ITEMS_COMMUNS_YES, Items_Virtuels items_virtuels = ITEMS_VIRTUELS_YES)
Definition at line 18 of file Echange_EV_Options.cpp.
                                                                                                               :
  op_(op), items_communs_(items_communs), items_virtuels_(items_virtuels) { }
Member Function Documentation
get_items_communs()
Items_Communs Echange_EV_Options::get_items_communs () const inline
Definition at line 39 of file Echange_EV_Options.h.
{ return items_communs_; }
References items_communs_.
get_items_virtuels()
Items_Virtuels Echange_EV_Options::get_items_virtuels () const inline
Definition at line 40 of file Echange_EV_Options.h.
{ return items_virtuels_; }
References items_virtuels_.
get_op()
Operation Echange_EV_Options::get_op () const inline
Definition at line 38 of file Echange_EV_Options.h.
{ return op_; }
References op_.
Referenced by MD_Vector_std::initialize_comm_template(), MD_Vector_std::prepare_send_data_template(), and MD_Vector_std::process_recv_data_template().
operator==()
int Echange_EV_Options::operator== (const Echange_EV_Options & x) const inline
Definition at line 42 of file Echange_EV_Options.h.
  {
    return op_==x.op_ && items_communs_==x.items_communs_ && items_virtuels_==x.items_virtuels_;
  }
References items_communs_, items_virtuels_, and op_.
Member Data Documentation
items_communs_
Items_Communs Echange_EV_Options::items_communs_ protected
Definition at line 49 of file Echange_EV_Options.h.
Referenced by get_items_communs(), and operator==().
items_virtuels_
Items_Virtuels Echange_EV_Options::items_virtuels_ protected
Definition at line 50 of file Echange_EV_Options.h.
Referenced by get_items_virtuels(), and operator==().
op_
Operation Echange_EV_Options::op_ protected
Definition at line 47 of file Echange_EV_Options.h.
Referenced by get_op(), and operator==().
The documentation for this class was generated from the following files:
src/Kernel/Math/Echange_EV_Options.h
src/Kernel/Math/Echange_EV_Options.cpp