TRUST: Travail_pression_PolyMAC Class Reference
Travail_pression_PolyMAC Class Reference
Classe Travail_pression_PolyMAC
Cette classe implemente dans PolyMAC le travail de la pression
- p (d alpha_k / dt + div(alpha_k v_k))
dans l'equation d'energie ecrite en energie interne (cf. CATHARE 3D)
#include <Travail_pression_PolyMAC.h>
Public Member Functions
Travail_pression_PolyMAC ()
~Travail_pression_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Travail_pression_PolyMAC & self_cast (Objet_U &)
static const Travail_pression_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Classe Travail_pression_PolyMAC
Cette classe implemente dans PolyMAC le travail de la pression
- p (d alpha_k / dt + div(alpha_k v_k))
dans l'equation d'energie ecrite en energie interne (cf. CATHARE 3D)
Definition at line 31 of file Travail_pression_PolyMAC.h.
Constructor & Destructor Documentation
Travail_pression_PolyMAC()
Travail_pression_PolyMAC::Travail_pression_PolyMAC ()
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
~Travail_pression_PolyMAC()
Travail_pression_PolyMAC::~Travail_pression_PolyMAC ()
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
Member Function Documentation
ajouter_blocs()
void Travail_pression_PolyMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Definition at line 68 of file Travail_pression_PolyMAC.cpp.
{
  const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, equation().probleme());
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, equation().zone_dis().valeur());
  const DoubleVect& pe = zone.porosite_elem(), &pf = zone.porosite_face(), &fs = zone.face_surfaces(), &ve = zone.volumes();
  const Champ_Inc_base& ch_a = pbm.eq_masse.inconnue().valeur(), &ch_v = pbm.eq_qdm.inconnue().valeur(), &ch_p = pbm.eq_qdm.pression().valeur();
  /* trois tableaux de alpha : present / passe et champ convecte (peut etre semi-implicite) */
  const DoubleTab& alpha = ch_a.valeurs(), &c_alpha = semi_impl.count("alpha") ? semi_impl.at("alpha") : alpha, &p_alpha = ch_a.passe(), &press = ch_p.valeurs(), &vit = ch_v.valeurs();
  const IntTab& fcl = ref_cast(Champ_Elem_PolyMAC, ch_a).fcl(), &f_e = zone.face_voisins();
  DoubleTab b_alpha = ch_a.valeur_aux_bords();
  Matrice_Morse *Mp = matrices.count("pression") ? matrices.at("pression") : NULL,
                 *Ma = matrices.count("alpha") && !semi_impl.count("alpha") ? matrices.at("alpha") : NULL,
                  *Mv = matrices.count("vitesse") ? matrices.at("vitesse") : NULL;
  int i, j, e, eb, f, n, N = alpha.line_size(), m, M = press.line_size();
  const Op_Conv_EF_Stab_PolyMAC_Elem *op_conv = sub_type(Op_Conv_EF_Stab_PolyMAC_Elem, equation().operateur(1).l_op_base()) ? &ref_cast(Op_Conv_EF_Stab_PolyMAC_Elem, equation().operateur(1).l_op_base()) : NULL;
  double dt = equation().schema_temps().pas_de_temps(), alp = op_conv ? op_conv->alpha : 1; /* meme decentrement que l'operateur de convection si il existe, amont sinon */
// partie -p d alpha_k / dt et ses derivees
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (n = 0, m = 0; n < N; n++, m += (M > 1)) secmem(e, n) -= pe(e) * ve(e) * press(e, m) * (alpha(e, n) - p_alpha(e, n)) / dt;
      if (Mp)
        for (n = 0, m = 0; n < N; n++, m += (M > 1)) (*Mp)(N * e + n, M * e + m) += pe(e) * ve(e) * (alpha(e, n) - p_alpha(e, n)) / dt;
      if (Ma)
        for (n = 0, m = 0; n < N; n++, m += (M > 1)) (*Ma)(N * e + n, N * e + n) += pe(e) * ve(e) * press(e, m) / dt;
    }
// partie -p div (alpha_k v_k)
  DoubleTrav dv_flux(N), dc_flux(2, N); //derivees du flux convectif a la face par rapport a la vitesse / au champ convecte amont / aval
  /* convection aux faces internes (fcl(f, 0) == 0), de Neumann_val_ext ou de Dirichlet */
  for (f = 0; f < zone.nb_faces(); f++)
    if (!fcl(f, 0) || (fcl(f, 0) > 4 && fcl(f, 0) < 7))
      {
        for (dv_flux = 0, dc_flux = 0, i = 0; i < 2; i++)
          for (e = f_e(f, i), n = 0; n < N; n++)
            {
              double v = vit(f, n) ? vit(f, n) : DBL_MIN, fac = pf(f) * fs(f) * (1. + (v * (i ? -1 : 1) > 0 ? 1. : -1) * alp) / 2;
              dv_flux(n) += fac * (e >= 0 ? c_alpha(e, n) : b_alpha(f, n)); //f est reelle -> indice trivial dans b_alpha
              dc_flux(i, n) = e >= 0 ? fac * vit(f, n) : 0;
            }
// second membre
        for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
          if (e < zone.nb_elem())
            for (n = 0, m = 0; n < N; n++, m += (M > 1))
              secmem(e, n) -= (i ? -1 : 1) * press(e, m) * dv_flux(n) * vit(f, n);
// derivees : vitesse
        if (Mv)
          for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
            if (e < zone.nb_elem())
              for (n = 0, m = 0; n < N; n++, m += (M > 1))
                (*Mv)(N * e + n, N * f + n) += (i ? -1 : 1) * press(e, m) * dv_flux(n);
// derivees : pression
        if (Mp)
          for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
            if (e < zone.nb_elem())
              for (n = 0, m = 0; n < N; n++, m += (M > 1))
                (*Mp)(N * e + n, M * e + m) += (i ? -1 : 1) * dv_flux(n) * vit(f, n);
// derivees : alpha
        if (Ma)
          for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
            if (e < zone.nb_elem())
              for (j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
                for (n = 0, m = 0; n < N; n++, m += (M > 1)) (*Ma)(N * e + n, N * eb + n) += (i ? -1 : 1) * press(e, m) * dc_flux(j, n);
      }
}
References Op_Conv_EF_Stab_PolyMAC_Elem::alpha, Pb_Multiphase::eq_masse, Pb_Multiphase::eq_qdm, MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Navier_Stokes_std::inconnue(), Masse_Multiphase::inconnue(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::passe(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Navier_Stokes_std::pression(), ref_cast, Equation_base::schema_temps(), sub_type, Deriv_Champ_Inc_base::valeur(), valeur(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and Zone_VF::volumes().
associer_pb()
void Travail_pression_PolyMAC::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
Definition at line 44 of file Travail_pression_PolyMAC.h.
{ };
associer_zones()
void Travail_pression_PolyMAC::associer_zones (const Zone_dis & , const Zone_Cl_dis &) inline override virtual
Implements Source_base.
Definition at line 43 of file Travail_pression_PolyMAC.h.
{ };
check_multiphase_compatibility()
void Travail_pression_PolyMAC::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 41 of file Travail_pression_PolyMAC.h.
{}; //of course
cree_instance()
Objet_U * Travail_pression_PolyMAC::cree_instance () static
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
dimensionner_blocs()
void Travail_pression_PolyMAC::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Definition at line 38 of file Travail_pression_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, equation().zone_dis().valeur());
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  const DoubleTab& inco = equation().inconnue().valeurs();
  int i, j, e, eb, ne = zone.nb_elem(), f,n, N = inco.line_size(), m, M = ref_cast(Pb_Multiphase, equation().probleme()).eq_qdm.pression().valeurs().line_size();
  for (auto &&n_m : matrices)
    if (n_m.first == "pression" || (n_m.first == "alpha" && !semi_impl.count("alpha")) || n_m.first == "vitesse")
      {
        Matrice_Morse& mat = *n_m.second, mat2;
        IntTrav sten(0, 2);
        sten.set_smart_resize(1);
        if (n_m.first == "pression") /* pression : dependance locale, implicite */
          for (e = 0; e < ne; e++)
            for (n = 0, m = 0; n < N; n++, m += (M > 1)) sten.append_line(N * e + n, M * e + m);
        else if (n_m.first == "vitesse")
          for (e = 0; e < ne; e++)
            for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
              for (n = 0; n < N; n++) sten.append_line(N * e + n, N * f + n);
        else for (e = 0; e < ne; e++)
            for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
              for (j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
                for (n = 0; n < N; n++) sten.append_line(N * e + n, N * eb + n);
        tableau_trier_retirer_doublons(sten);
        Matrix_tools::allocate_morse_matrix(inco.size_totale(), equation().probleme().get_champ(n_m.first).valeurs().size_totale(), sten, mat2);
        mat.nb_colonnes() ? mat += mat2 : mat = mat2;
      }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_voisins(), Source_base::get_champ(), Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), tableau_trier_retirer_doublons(), valeur(), Champ_Inc::valeurs(), and Champ_Proto::valeurs().
duplique()
int Travail_pression_PolyMAC::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
get_info()
const Type_info * Travail_pression_PolyMAC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
has_interface_blocs()
int Travail_pression_PolyMAC::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 35 of file Travail_pression_PolyMAC.h.
  {
    return 1;
  }
info()
const Type_info * Travail_pression_PolyMAC::info () static
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
mettre_a_jour()
void Travail_pression_PolyMAC::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 45 of file Travail_pression_PolyMAC.h.
{ };
printOn()
Sortie & Travail_pression_PolyMAC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 28 of file Travail_pression_PolyMAC.cpp.
{
  return os;
}
readOn()
Entree & Travail_pression_PolyMAC::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 33 of file Travail_pression_PolyMAC.cpp.
{
  return is;
}
self_cast() [1/2]
const Travail_pression_PolyMAC & Travail_pression_PolyMAC::self_cast (const Objet_U & r) static
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
self_cast() [2/2]
Travail_pression_PolyMAC & Travail_pression_PolyMAC::self_cast (Objet_U & r) static
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
taille_memoire()
unsigned Travail_pression_PolyMAC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Travail_pression_PolyMAC.cpp.
Member Data Documentation
info_obj
const Type_info Travail_pression_PolyMAC::info_obj static
Definition at line 33 of file Travail_pression_PolyMAC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/PolyMAC/Travail_pression_PolyMAC.h
src/ThHyd/Multiphase/PolyMAC/Travail_pression_PolyMAC.cpp