TRUST: SolveurSys_base Class Reference
SolveurSys_base Class Reference
#include <SolveurSys_base.h>
Public Member Functions
~SolveurSys_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Private Attributes
int limpr_
Drapeau pour impression ou non de la convergence du solveur.
int schema_temps_limpr_
Authorization printing flag set by the time scheme.
int echange_ev_resu_
User set flag to tell if the solver must do echange_espace_virtuel() on the result.
Detailed Description
Definition at line 30 of file SolveurSys_base.h.
Constructor & Destructor Documentation
SolveurSys_base::~SolveurSys_base ()
Definition at line 30 of file SolveurSys_base.cpp.
SolveurSys_base::SolveurSys_base ()
Definition at line 31 of file SolveurSys_base.cpp.
References echange_ev_resu_, limpr_, nouvelle_matrice_, save_matrice_, and schema_temps_limpr_.
{
  limpr_=0;
  schema_temps_limpr_=1;
  nouvelle_matrice_=1;
// By default: result will have an updated virtual space:
  echange_ev_resu_ = 1;
  save_matrice_=0;
}
Member Function Documentation
virtual int SolveurSys_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
void SolveurSys_base::fixer_limpr (int l) [inline]
Definition at line 47 of file SolveurSys_base.h.
References limpr_.
Referenced by SolveurPP1B::associer(), Solv_Petsc::create_solver(), Solv_Optimal::readOn(), Solv_Gmres::readOn(), Solv_Gen::readOn(), Solv_GCP_NS::readOn(), Solv_GCP::readOn(), Solv_Cholesky::readOn(), and Precond_local::readOn().
  {
    limpr_=l;
  };
void SolveurSys_base::fixer_nouvelle_matrice (int i) [inline]
Definition at line 70 of file SolveurSys_base.h.
References nouvelle_matrice_.
Referenced by Solv_Cholesky::Cholesky(), and Solv_Petsc::resoudre_systeme().
  {
    nouvelle_matrice_=i;
  };
virtual void SolveurSys_base::fixer_schema_temps_limpr (int l) [inline, virtual]
Reimplemented in SolveurPP1B.
Definition at line 43 of file SolveurSys_base.h.
References schema_temps_limpr_.
Referenced by SolveurPP1B::fixer_schema_temps_limpr().
  {
    schema_temps_limpr_=l;
  }
virtual int SolveurSys_base::get_flag_updated_input () const [inline, virtual]
Reimplemented in Solv_GCP.
Definition at line 82 of file SolveurSys_base.h.
  {
    return 1;
  }
int SolveurSys_base::get_flag_updated_result () const [inline]
Definition at line 91 of file SolveurSys_base.h.
References echange_ev_resu_.
Referenced by Solv_GCP::resoudre_().
  {
    return echange_ev_resu_;
  }
const Type_info * SolveurSys_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 30 of file SolveurSys_base.cpp.
const Type_info * SolveurSys_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 30 of file SolveurSys_base.cpp.
int SolveurSys_base::limpr () const [inline]
Definition at line 56 of file SolveurSys_base.h.
References limpr_, and schema_temps_limpr_.
Referenced by Solv_Petsc::create_solver(), Solv_Gmres::Gmres(), Solv_Optimal::prepare_resol(), Solv_Gmres::printOn(), Solv_Gen::printOn(), Solv_GCP::printOn(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), and Solv_Gen::solve().
  {
    if (!schema_temps_limpr_)
      return 0;
    return  limpr_;
  };
int SolveurSys_base::nouvelle_matrice () const [inline]
Definition at line 66 of file SolveurSys_base.h.
References nouvelle_matrice_.
Referenced by Solv_Cholesky::Cholesky(), Solv_Petsc::resoudre_systeme(), and Solv_Cholesky::resoudre_systeme().
  {
    return nouvelle_matrice_;
  };
Sortie & SolveurSys_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 43 of file SolveurSys_base.cpp.
References Objet_U::que_suis_je().
{
  return s  << que_suis_je();
}
Entree & SolveurSys_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 51 of file SolveurSys_base.cpp.
{
  return is;
}
virtual void SolveurSys_base::reinit () [inline, virtual]
Reimplemented in Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Optimal, and SolveurPP1B.
Definition at line 62 of file SolveurSys_base.h.
References nouvelle_matrice_.
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), construire_matrice_implicite(), Simple::iterer_eqn(), Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Simpler::iterer_NS(), Simple::iterer_NS(), Piso::iterer_NS(), Piso::iterer_NS_PolyMAC(), PrecondSolv::prepare_(), Precond_local::prepare_(), SolveurPP1B::reinit(), and Solv_GCP_NS::reinit().
  {
    nouvelle_matrice_=1;
  };
virtual int SolveurSys_base::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x) [pure virtual]
Implemented in Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, Solv_Optimal, Solv_Petsc, and SolveurPP1B.
Referenced by Solveur_U_P::iterer_NS(), resoudre_systeme(), and SolveurSys::resoudre_systeme().
int SolveurSys_base::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x, int niter_max) [virtual]
Reimplemented in Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, Solv_Optimal, Solv_Petsc, and SolveurPP1B.
Definition at line 56 of file SolveurSys_base.cpp.
References resoudre_systeme(), and save_matrice_secmem_conditionnel().
{
  save_matrice_secmem_conditionnel(A, b, x);
  return resoudre_systeme(A,b,x);
}
void SolveurSys_base::save_matrice_secmem_conditionnel (const Matrice_Base & la_matrice, const DoubleVect & secmem, const DoubleVect & solution, int binaire = 1)
Definition at line 66 of file SolveurSys_base.cpp.
References Cout, MD_Vector_tools::dump_vector_with_md(), finl, EcrFicCollecte::ouvrir(), Objet_U::que_suis_je(), save_matrice_, and Sortie::set_bin().
Referenced by resoudre_systeme(), and SolveurSys::resoudre_systeme().
{
  int binaire=binaire2;
  if (save_matrice_)
    {
// on simule l'ecriture d'une Matrice et non d'une Matrice_Base
// pour aider a la relecture
      {
        EcrFicCollecte sortie;
        sortie.set_bin(binaire);
        sortie.ouvrir("Matrice.sa");
        sortie<<la_matrice.que_suis_je()<<finl;
        sortie<<la_matrice;
      }
// on sauvegarde le Secmem avec les espaces virtuels !!!!!
      {
        EcrFicCollecte sortie;
        sortie.set_bin(binaire);
        sortie.ouvrir("Secmem.sa");
        MD_Vector_tools::dump_vector_with_md(secmem, sortie);
      }
// on sauvegarde la solution avec les espaces virtuels !!!!!
      {
        EcrFicCollecte sortie;
        sortie.set_bin(binaire);
        sortie.ouvrir("Solution.sa");
        MD_Vector_tools::dump_vector_with_md(solution, sortie);
      }
      Cout <<"Saving of the matrix, secmem and solution ended."<<finl;
    }
}
const SolveurSys_base & SolveurSys_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 30 of file SolveurSys_base.cpp.
SolveurSys_base & SolveurSys_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 30 of file SolveurSys_base.cpp.
void SolveurSys_base::set_flag_updated_result (int flag) [inline]
Definition at line 87 of file SolveurSys_base.h.
References echange_ev_resu_.
  {
    echange_ev_resu_ = (flag!=0);
  }
void SolveurSys_base::set_return_on_error (int ret) [inline]
Definition at line 51 of file SolveurSys_base.h.
References return_on_error_.
  {
    return_on_error_ = ret;
  }
virtual int SolveurSys_base::solveur_direct () const [pure virtual]
Implemented in Solv_Cholesky, solv_iteratif, Solv_Petsc, and SolveurPP1B.
Referenced by SolveurPP1B::solveur_direct().
virtual int SolveurSys_base::supporte_matrice_morse_sym () [inline, virtual]
Reimplemented in Solv_GCP, and Solv_GCP_NS.
Definition at line 75 of file SolveurSys_base.h.
Referenced by SolveurSys::supporte_matrice_morse_sym(), and PrecondSolv::supporte_matrice_morse_sym().
  {
    return 1;
  };
Member Data Documentation
int SolveurSys_base::echange_ev_resu_ [private]
User set flag to tell if the solver must do echange_espace_virtuel() on the result.
Definition at line 104 of file SolveurSys_base.h.
Referenced by get_flag_updated_result(), set_flag_updated_result(), and SolveurSys_base().
const Type_info SolveurSys_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Solv_AMGX, Solv_Cholesky, Solv_GCP, Solv_GCP_NS, Solv_Gen, Solv_Gmres, solv_iteratif, Solv_Optimal, Solv_Petsc, Solv_Petsc_GPU, and SolveurPP1B.
Definition at line 33 of file SolveurSys_base.h.
int SolveurSys_base::limpr_ [private]
Drapeau pour impression ou non de la convergence du solveur.
Definition at line 102 of file SolveurSys_base.h.
Referenced by fixer_limpr(), limpr(), and SolveurSys_base().
int SolveurSys_base::nouvelle_matrice_ [protected]
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
Definition at line 98 of file SolveurSys_base.h.
Referenced by fixer_nouvelle_matrice(), nouvelle_matrice(), reinit(), and SolveurSys_base().
int SolveurSys_base::return_on_error_ = 0 [protected]
Definition at line 100 of file SolveurSys_base.h.
Referenced by Solv_Gen::readOn(), set_return_on_error(), and Solv_Gen::solve().
int SolveurSys_base::save_matrice_ [protected]
Drapeau pour savoir si un stockage disque est a refaire.
Definition at line 99 of file SolveurSys_base.h.
Referenced by Solv_Petsc::create_solver(), Solv_Gmres::printOn(), Solv_GCP::printOn(), Solv_Optimal::readOn(), Solv_Gmres::readOn(), Solv_Gen::readOn(), Solv_GCP::readOn(), Solv_Cholesky::readOn(), save_matrice_secmem_conditionnel(), and SolveurSys_base().
int SolveurSys_base::schema_temps_limpr_ [private]
Authorization printing flag set by the time scheme.
Definition at line 103 of file SolveurSys_base.h.
Referenced by fixer_schema_temps_limpr(), limpr(), and SolveurSys_base().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/SolveurSys_base.h
src/Kernel/Math/SolvSys/SolveurSys_base.cpp