TRUST: Format_Post_Lata Class Reference
Format_Post_Lata Class Reference
:
Classe de postraitement des champs euleriens au format lata.
#include <Format_Post_Lata.h>
Public Types
enum Format { ASCII , BINAIRE }
enum Options_Para { SINGLE_FILE , SINGLE_FILE_MPIIO , MULTIPLE_FILES }
enum Status { RESET , INITIALIZED , WRITING_TIME }
Public Member Functions
~Format_Post_Lata ()
< Necessaire avec xlC pour std::getline
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void reset () override
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int initialize_by_default (const Nom &file_basename) override
Initialisation de la classe avec des parametres par
defaut (format ASCII, SINGLE_FILE)
int initialize (const Nom &file_basename, const int format, const Nom &option_para) override
int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit) override
Modification du nom du fichier de postraitement.
virtual int reconstruct (const Nom file_basename, const Nom, const double tinit)
virtual int finir_sans_reprise (const Nom file_basename)
int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override
Ouvre le fichier maitre en mode ERASE et ecrit l'entete du fichier lata<br>(sur le processeur maitre seulement).
int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post) override
int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override
int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post) override
voir Format_Post_base::ecrire_domaine
On accepte l'ecriture d'un domaine dans un pas de temps, mais
les id_domaines doivent etre tous distincts.
Ecrit le fichier "basename(_XXXXX).lata.nom_domaine", qui contient
la liste des sommets et la liste des elements.
Si le PE est maitre, ouvre le fichier maitre en mode APPEND et
ajoute une reference a ce fichier.
int ecrire_temps (const double temps) override
commence l'ecriture d'un nouveau pas de temps
En l'occurence pour le format LATA:
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx" si ce temps n'a pas encore ete ecrit
int finir (int &est_le_dernier_post) override
int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data) override
voir Format_Post_base::ecrire_champ
int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size) override
voir Format_Post_base::ecrire_champ
ATTENTION: si "reference" est non vide on ajoute 1 a toutes les
valeurs pour passer en numerotation fortran, et si de plus on
ecrit un fichier lata unique pour tous les processeurs, on ajoute un
decalage a toutes les valeurs (renumerotation des indices pour
passer en numerotation globale, voir le codage de ecrire_domaine
par exemple)
Format_Post_Lata ()
Constructeur par defaut: format_ ASCII et options_para_ = SINGLE_FILE.
virtual int initialize_lata (const Nom &file_basename, const Format format=ASCII, const Options_Para options_para=SINGLE_FILE)
Initialisation de la classe, ouverture du fichier et ecriture
de l'entete.
Public Member Functions inherited from Format_Post_base
Format_Post_base ()
~Format_Post_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void reset ()=0
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int initialize_by_default (const Nom &file_basename)
Initialise le fichier avec des parametres appropries pour son
format (exemple: format ascii, efface le fichier existant, un
fichier unique pour tous les processeurs etc...)
Methode a surcharger dans les classes derivees.
Valeur de retour: 1 si l'operation a reussi, 0 sinon.
virtual int initialize (const Nom &file_basename, const int format, const Nom &option_para)
virtual int modify_file_basename (const Nom file_basename, const int a_faire, const double tinit)
virtual int ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post)
virtual int completer_post (const Domaine &dom, const int axi, const Nature_du_champ &nature, const int nb_compo, const Noms &noms_compo, const Motcle &loc_post, const Nom &le_nom_champ_post)
virtual int preparer_post (const Nom &id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init)
virtual int test_coherence (const int champs, const int stat, const double dt_ch, const double dt_stat)
virtual int init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine &domaine)
virtual int finir_ecriture (double temps_courant)
virtual int finir (int &est_le_dernier_post)
virtual int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post)
Ecriture d'un maillage. L'ecriture du domaine a lieu soit au debut,
avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique),
mais ce n'est pas forcement supporte par le postraitement.
Parametre: id_domaine
Signification: le nom affecte au domaine dans le fichier lata.
Parametre: type_elem
Signification: le type de l'element geometrique (un type supporte par
la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE",
"TRIANGLE" et "RECTANGLE")
Parametre: dimension
Signification: la dimension du domaine (nombre de coordonnees des sommets)
On peut avoir un domaine de dimension 3 et des elements de type triangle
(postraitement d'une interface ou du bord d'un domaine volumique).
Parametre: sommets
Signification:
Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
Parametre: elements
Signification:
Indices des sommets de chaque element. dimension(1) doit correspondre au type
de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
virtual int ecrire_domaine_dis (const Domaine &domaine, const Ref_Zone_dis_base &zone_dis_base, const int est_le_premier_post)
virtual int ecrire_temps (const double temps)
Commence l'ecriture d'un pas de temps. La classe derivee doit accepter
de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
virtual int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data)
Ecriture d'un champ dans le fichier de postraitement.
Parametre: id_du_champ
Signification:
identifiant du champ (permet d'identifier un champ unique si on donne
en plus un numero de pas de temps)
Parametre: id_du_domaine
Signification:
identifiant du domaine sur lequel le champ est defini
Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
Parametre: localisation
Signification:
localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de
tableau deja ecrit)
(tout n'est pas obligatoirement supporte par tous les postraitements)
Parametre: data
Signification:
tableau de valeurs a postraiter. Le nombre de lignes du tableau
doit etre egal au nombre de lignes du tableau "localisation"
(nombre de sommets, d'elements ou de faces ou autre).
Valeur de retour: 1 si operation reussie, 0 sinon (par exemple,
preconditions non remplies ou fonctionnalite non supportee par le
format).
virtual int ecrire_champ2 (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, double temps_courant, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data, const DoubleTab &coord)
virtual int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_zone, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size)
Ecriture d'un tableau d'entiers dans le fichier de postraitement
Voir aussi ecrire_champ
Parametre: reference
Signification: Nom d'un autre tableau deja ecrit. data[i] est un
indice dans ce tableau (exemple: on peut ecrire le tableau
FACES_VOISINS, localisation=FACES, reference=ELEMENTS
car le tableau est indexe par un numero de face et contient
des indices d'elements)
L'ecriture d'un domaine entraine automatiquement l'existence
d'une tableau SOMMETS et d'un tableau ELEMENTS
Parametre: reference_size
Signification: la taille (locale) du tableau cite en reference<br>(dimension(0) du tableau). Cette dimension est utilisee pour
renumeroter le contenu du tableau data afin de creer une numerotation
globale lorsque tous les processeurs ecrivent dans un fichier unique.
void postraiter_debug_valeurs_un_instant (const Nom &nom_fich, const Domaine &dom, const Zone_dis_base &zone_dis, double temps_champ, double temps_courant, const Nom &id_champ_post, const Nature_du_champ &nature_champ, const Noms &noms_compos, const Noms &unites, const Motcle &loc_post, const DoubleTab &data, int ncomp=-1, int axi=0, int champ=1, int stat=0, double dt_ch=1., double dt_stat=1., int reprise=0, int est_le_premier_post=1, int est_le_dernier_post=1, double t_init=0., double temps_post=-2)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Format_Post_Lata & self_cast (Objet_U &)
static const Format_Post_Lata & self_cast (const Objet_U &)
static int ecrire_entete_lata (const Nom &base_name, const Options_Para &option, const Format &format, const int est_le_premier_post)
static int ecrire_temps_lata (const double temps, double &temps_format, const Nom &base_name, Status &stat, const Options_Para &option)
static const char * extension_lata ()
Renvoie l'extension conventionnelle des fichiers lata : ".lata".
static const char * remove_path (const char *filename)
Renvoie le nom d'un fichier sans le path :
on enleve les caracteres avant le dernier /.
Static Public Member Functions inherited from Format_Post_base
static const Type_info * info ()
static Format_Post_base & self_cast (Objet_U &)
static const Format_Post_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Format_Post_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier nom champ obligatoire
[ format ascii|binaire ] valeur par defaut : ascii
[ parallel single_file|multiple_files ] valeur par defaut : single_file
}.
Sortie & printOn (Sortie &x) const override
erreur => exit
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Member Functions
static int write_doubletab (Fichier_Lata &fichier, const DoubleTab &tab, int &nb_colonnes, const Options_Para &option, const int bloc_number=0, const int nb_blocs=1)
fichier est un fichier lata de donnees (pas le fichier maitre)
on y ecrit le tableau tab tel quel (en binaire ou ascii et sur un ou
plusieurs fichiers en parallel).
nb_colonnes est rempli avec le produit des tab.dimension(i) pour i>0
bloc_number et nb_blocs sont utilises pour les valeurs aux sommets en 2D
pour le format lataV1 : on ecrit deux fois le nombre de sommets dans le meme bloc
(bloc_number = le numero du bloc courant en cours d'ecriture,
nb_blocs = le nombre total de blocs ecrits. Le tag de debut et de fin
est ecrit au debut du premier bloc et a la fin du dernier et le nombre est
la taille du tableau multiplie par le nombre de blocs (on suppose que tous
les blocs sont identiques)).
static int write_inttab (Fichier_Lata &fichier, int decalage, int decalage_partiel, const IntTab &tab, int &nb_colonnes, const Options_Para &option)
Ecriture d'un tableau d'entiers dans le fichier fourni.
Les valeurs ecrites sont les valeurs du tableau auquelles ont ajoute
"decalage". Cette valeur est utilisee pour passer en numerotation
fortran (ajouter 1), ou pour passer en numerotation globale (ajouter
le nombre d'elements sur les processeurs precedents).
On renvoie dans nb_colonnes la somme des dimension(i) pour i>0.
Valeur de retour: somme des dimension(0) ecrits (selon que tous les
processeurs ecrivent sur le meme fichier ou pas).
Protected Attributes
int deja_fait_
int file_existe_
double tinit_
Nom lata_basename_
Format format_
Options_Para options_para_
Status status
double temps_courant_
Detailed Description
:
Classe de postraitement des champs euleriens au format lata.
Definition at line 49 of file Format_Post_Lata.h.
Member Enumeration Documentation
Format
enum Format_Post_Lata::Format
Enumerator
ASCII
BINAIRE
Definition at line 99 of file Format_Post_Lata.h.
{ ASCII, BINAIRE };
Options_Para
enum Format_Post_Lata::Options_Para
Enumerator
SINGLE_FILE
SINGLE_FILE_MPIIO
MULTIPLE_FILES
Definition at line 100 of file Format_Post_Lata.h.
{ SINGLE_FILE, SINGLE_FILE_MPIIO, MULTIPLE_FILES };
Status
enum Format_Post_Lata::Status
Enumerator
RESET
INITIALIZED
WRITING_TIME
Definition at line 101 of file Format_Post_Lata.h.
{ RESET, INITIALIZED, WRITING_TIME };
Constructor & Destructor Documentation
~Format_Post_Lata()
Format_Post_Lata::~Format_Post_Lata ()
< Necessaire avec xlC pour std::getline
Definition at line 25 of file Format_Post_Lata.cpp.
Format_Post_Lata()
Format_Post_Lata::Format_Post_Lata ()
Constructeur par defaut: format_ ASCII et options_para_ = SINGLE_FILE.
Definition at line 529 of file Format_Post_Lata.cpp.
{
  reset();
}
References reset().
Member Function Documentation
completer_post()
int Format_Post_Lata::completer_post (const Domaine & dom, const int axi, const Nature_du_champ & nature, const int nb_compo, const Noms & noms_compo, const Motcle & loc_post, const Nom & le_nom_champ_post) override virtual
Reimplemented from Format_Post_base.
Definition at line 288 of file Format_Post_Lata.cpp.
{
  return 1;
}
cree_instance()
Objet_U * Format_Post_Lata::cree_instance () static
Definition at line 25 of file Format_Post_Lata.cpp.
duplique()
int Format_Post_Lata::duplique () const override virtual
Implements Objet_U.
Reimplemented in Format_Post_Lata_V1.
Definition at line 25 of file Format_Post_Lata.cpp.
ecrire_champ()
int Format_Post_Lata::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, double temps_courant, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) override virtual
voir Format_Post_base::ecrire_champ
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 979 of file Format_Post_Lata.cpp.
{
// recup de lata_v1
  Motcle id_du_champ_modifie(id_du_champ);
  Motcle iddomaine(id_du_domaine);
// On utilise prefix avec un argument en majuscule
  if ((Motcle)localisation=="SOM")
    {
      id_du_champ_modifie.prefix(id_du_domaine);
      id_du_champ_modifie.prefix(iddomaine);
//
      id_du_champ_modifie.prefix("_SOM_");
    }
  else if ((Motcle)localisation=="ELEM")
    {
      id_du_champ_modifie.prefix(id_du_domaine);
      id_du_champ_modifie.prefix(iddomaine);
//
      id_du_champ_modifie.prefix("_ELEM_");
    }
  else if ((Motcle)localisation=="FACES")
    {
      id_du_champ_modifie.prefix(id_du_domaine);
      id_du_champ_modifie.prefix(iddomaine);
      id_du_champ_modifie.prefix("_FACES_");
    }
  Nom& id_champ=id_du_champ_modifie;
// Construction du nom du fichier
  Nom basename_champ(lata_basename_);
  Nom extension_champ(extension_lata());
  extension_champ += ".";
  extension_champ += id_champ;
  extension_champ += ".";
  extension_champ += localisation;
  extension_champ += ".";
  extension_champ += id_du_domaine;
  extension_champ += ".";
  char str_temps[100] = "0.0";
  if (temps >= 0.)
    sprintf(str_temps, "%.10f", temps);
  extension_champ += str_temps;
  Nom filename_champ;
  int size_tot, nb_compo;
  {
    Fichier_Lata fichier_champ(basename_champ, extension_champ,
                               Fichier_Lata::ERASE, format_, options_para_);
    filename_champ = fichier_champ.get_filename();
    size_tot = write_doubletab(fichier_champ, valeurs, nb_compo, options_para_);
  }
// Ouverture du fichier .lata en mode append.
// Ajout de la reference au champ
  Fichier_Lata_maitre fichier(lata_basename_, extension_lata(),
                              Fichier_Lata::APPEND, options_para_);
  SFichier& sfichier = fichier.get_SFichier();
  if (fichier.is_master())
    {
      sfichier << "Champ " << id_champ << " ";
      sfichier << remove_path(filename_champ);
      sfichier << " geometrie=" << id_du_domaine;
#ifdef INT_is_64_
      sfichier << " file_offset=6";
#endif
      sfichier << " localisation=" << localisation;
      sfichier << " size=" << size_tot;
      sfichier << " nature=" << nature;
      sfichier << " noms_compo="<<noms_compo[0];
      for (int k=1; k<noms_compo.size(); k++)
        sfichier << ","<<noms_compo[k];
      sfichier << " composantes=" << nb_compo<<finl;
// sfichier << " type=REAL32" << finl;
    }
  fichier.syncfile();
  return 1;
}
References Fichier_Lata::APPEND, Fichier_Lata::ERASE, extension_lata(), finl, format_, Fichier_Lata::get_filename(), Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), lata_basename_, options_para_, Nom::prefix(), remove_path(), Fichier_Lata::syncfile(), and write_doubletab().
ecrire_domaine()
int Format_Post_Lata::ecrire_domaine (const Domaine & domaine, const int est_le_premier_post) override virtual
voir Format_Post_base::ecrire_domaine
On accepte l'ecriture d'un domaine dans un pas de temps, mais
les id_domaines doivent etre tous distincts.
Ecrit le fichier "basename(_XXXXX).lata.nom_domaine", qui contient
la liste des sommets et la liste des elements.
Si le PE est maitre, ouvre le fichier maitre en mode APPEND et
ajoute une reference a ce fichier.
< Nombre de sommets dans le fichier
< Nombre d'elements dans le fichier
< ok tout va bien
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 791 of file Format_Post_Lata.cpp.
{
  if (status == RESET)
    {
      Cerr << "Error in Format_Post_Lata::ecrire_domaine\n"
           << " status = RESET. Uninitialized object" << finl;
      exit();
    }
  const Nom& id_domaine = domaine.le_nom();
  const DoubleTab& sommets = domaine.les_sommets();
  const IntTab& elements = domaine.zone(0).les_elems();
  Motcle type_elem = domaine.zone(0).type_elem().valeur().que_suis_je();
// GF Pour assuerer la lecture avec le plugin lata
  if (type_elem=="PRISME") type_elem="PRISM6" ;
  int dim = domaine.les_sommets().dimension(1);
  int nb_som_tot;  //!< Nombre de sommets dans le fichier
  int nb_elem_tot; //!< Nombre d'elements dans le fichier
// Construction du nom du fichier de geometrie
  Nom basename_geom(lata_basename_);
  Nom extension_geom(extension_lata());
  extension_geom += ".";
  extension_geom += id_domaine;
  extension_geom += ".";
  char str_temps[100] = "0.0";
  if (temps_courant_ >= 0.)
    sprintf(str_temps, "%.10f", temps_courant_);
  extension_geom += Nom(str_temps);
  Nom nom_fichier_geom;
  int decalage_sommets = 1;
  int decalage_elements = 1;
#undef un_seul_fichier_data
#ifdef un_seul_fichier_data
  long int offset_elem = -1;
#endif
  {
    Fichier_Lata fichier_geom(basename_geom, extension_geom,
                              Fichier_Lata::ERASE, format_, options_para_);
    nom_fichier_geom = fichier_geom.get_filename();
    int nb_col;
// Coordonnees des sommets
//
    if (axi)
      {
        DoubleTab sommets2(sommets);
        int ns=sommets2.dimension_tot(0);
        for (int s=0; s<ns; s++)
          {
            double r = sommets(s,0);
            double theta = sommets(s,1);
            sommets2(s,0) = r*cos(theta);
            sommets2(s,1) = r*sin(theta);
          }
        nb_som_tot = write_doubletab(fichier_geom, sommets2, nb_col,options_para_);
      }
    else
      nb_som_tot = write_doubletab(fichier_geom, sommets, nb_col,options_para_);
#ifdef un_seul_fichier_data
    if (fichier_geom.is_master())
      {
        offset_elem = fichier_geom.get_SFichier(). get_ofstream().tellp();
// if (fichier_geom.get_SFichier().is_bin()==0) offset_elem-=1;
      }
#else
    Fichier_Lata fichier_geom_elem(basename_geom, extension_geom+Nom(".elem"),
                                   Fichier_Lata::ERASE, format_, options_para_);
#endif
    assert(nb_som_tot == 0 || nb_col == dim);
// Elements
// Les indices de sommets, elements et autres dans le fichier lata commencent a 1 :
    if (options_para_ == SINGLE_FILE || options_para_ == SINGLE_FILE_MPIIO)
      {
// Tous les processeurs ecrivent dans un fichier unique, il faut
// renumeroter les indices pour passer en numerotation globale.
// Le processeur 0 numerote ses sommets de 1 a n0
// Le processeur 1 numerote ses sommets de n0+1 a n0+n1
// etc...
// Decalage a ajouter aux indices pour avoir une numerotation globale.
        const int nbsom = sommets.dimension(0);
        decalage_sommets += mppartial_sum(nbsom);
        const int nbelem = elements.dimension(0);
        decalage_elements += mppartial_sum(nbelem);
      }
#ifdef un_seul_fichier_data
    nb_elem_tot = write_inttab(fichier_geom, 1 , decalage_sommets, elements, nb_col,options_para_);
#else
    nb_elem_tot = write_inttab(fichier_geom_elem, 1, decalage_sommets,elements, nb_col,options_para_);
#endif
  }
  {
// Attention, il faut refermer le fichier avant d'appeler ecrire_item_int
// qui va ouvrir a nouveau le fichier.
    Fichier_Lata_maitre fichier_lata(lata_basename_, extension_lata(),
                                     Fichier_Lata::APPEND, options_para_);
    SFichier& sfichier = fichier_lata.get_SFichier();
    if (fichier_lata.is_master())
      {
        sfichier << "GEOM " << id_domaine;
        sfichier << " type_elem=" << type_elem<<finl;
        sfichier << "CHAMP SOMMETS "<< remove_path(nom_fichier_geom);
        sfichier << " geometrie="<<id_domaine;
#ifdef INT_is_64_
        sfichier << " file_offset=6";
#endif
        sfichier << " size=" << nb_som_tot;
        sfichier << " composantes=" << dim << finl;
        sfichier << "CHAMP ELEMENTS "<< remove_path(nom_fichier_geom);
#ifndef un_seul_fichier_data
        sfichier<<".elem";
#endif
        sfichier << " geometrie="<<id_domaine;
#ifdef INT_is_64_
        sfichier << " file_offset=6";
#endif
        sfichier << " size=" << nb_elem_tot<<" composantes="<<elements.dimension(1);
#ifdef un_seul_fichier_data
        sfichier<<" file_offset="<<offset_elem;
#endif
        switch(sizeof(_LATA_INT_TYPE_))
          {
          case 4:
            sfichier << " format=INT32"<<finl;;
            break;
          case 8:
            sfichier << " format=INT64"<<finl;
            break;
          default:
            Cerr << "Error in Format_Post_Lata::ecrire_entete\n"
                 << " sizeof(int) not supported" << finl;
            exit();
          }
      }
    fichier_lata.syncfile();
  }
// En mode parallele, on ecrit en plus des fichiers contenant les donnees paralleles
// sur les sommets, les elements et les faces...
  if (Process::nproc() > 1)
    if (options_para_ == SINGLE_FILE || options_para_ == SINGLE_FILE_MPIIO)
      {
        IntTab data(1,2);
        data(0, 0) = decalage_sommets;
        data(0, 1) = sommets.dimension(0);
        ecrire_item_int("JOINTS_SOMMETS",
                        id_domaine,
                        "", /* id_zone */
                        "", /* localisation */
                        "", /* reference */
                        data,
                        0); /* reference_size */
        data(0, 0) = decalage_elements;
        data(0, 1) = elements.dimension(0);
        ecrire_item_int("JOINTS_ELEMENTS",
                        id_domaine,
                        "", /* id_zone */
                        "", /* localisation */
                        "", /* reference */
                        data,
                        0); /* reference_size */
      }
// Si on a des frontieres domaine, on les ecrit egalement
  const LIST(REF(Domaine)) bords= domaine.domaines_frontieres();
  for (int i=0; i<bords.size(); i++)
    ecrire_domaine(bords[i].valeur(),est_le_premier_post);
  return 1; //!< ok tout va bien
}
References _LATA_INT_TYPE_, Fichier_Lata::APPEND, Objet_U::axi, Cerr, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Domaine::domaines_frontieres(), ecrire_domaine(), ecrire_item_int(), Fichier_Lata::ERASE, Process::exit(), extension_lata(), finl, format_, Fichier_Lata::get_filename(), Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), lata_basename_, Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), LIST, mppartial_sum(), Process::nproc(), options_para_, Objet_U::que_suis_je(), REF, remove_path(), RESET, SINGLE_FILE, SINGLE_FILE_MPIIO, status, Fichier_Lata::syncfile(), temps_courant_, Zone::type_elem(), type_elem(), Deriv_Elem_geom_base::valeur(), valeur(), write_doubletab(), write_inttab(), and Domaine::zone().
Referenced by ecrire_domaine().
ecrire_entete()
int Format_Post_Lata::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override virtual
Ouvre le fichier maitre en mode ERASE et ecrit l'entete du fichier lata<br>(sur le processeur maitre seulement).
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 230 of file Format_Post_Lata.cpp.
{
  ecrire_entete_lata(lata_basename_,options_para_,format_,est_le_premier_post);
  /*
  // Determination du format binaire:
  //  big endian => l'entier 32 bits "1" s'ecrit 0x00 0x00 0x00 0x01
  //  little endian =>                           0x01 0x00 0x00 0x00
  const unsigned int one = 1;
  const int big_endian = (* ((unsigned char *)&one) == 0) ? 1 : 0;
  // Effacement du fichier .lata et ecriture de l'entete
  Fichier_Lata_maitre fichier(lata_basename_, extension_lata(),
  Fichier_Lata::ERASE,
  options_para_);
  SFichier & sfichier = fichier.get_SFichier();
  if (fichier.is_master()) {
  sfichier << "LataV2.0 Trio_U Version1.4.9 06/2005" << finl;
  sfichier << Objet_U::nom_du_cas() << finl;
  sfichier << "Trio_U" << finl;
  sfichier << "Format ";
  switch(format_) {
  case ASCII:
  sfichier << "ASCII ";
  break;
  case BINAIRE:
  sfichier << "BINAIRE ";
  if (big_endian)
  sfichier << "big_endian ";
  else
  sfichier << "little_endian ";
  break;
  default:
  Cerr << "Error in Format_Post_Lata::ecrire_entete\n"
  << " format not supported" << finl;
  exit();
  }
  switch(sizeof(_LATA_INT_TYPE_)) {
  case 4:
  sfichier << "int32 ";
  break;
  case 8:
  sfichier << "int64 ";
  break;
  default:
  Cerr << "Error in Format_Post_Lata::ecrire_entete\n"
  << " sizeof(int) not supported" << finl;
  exit();
  }
  sfichier << "real32" << finl;
  }
  fichier.syncfile();
  */
  return 1;
}
References ecrire_entete_lata(), format_, lata_basename_, and options_para_.
ecrire_entete_lata()
int Format_Post_Lata::ecrire_entete_lata (const Nom & base_name, const Options_Para & option, const Format & format, const int est_le_premier_post) static
Definition at line 1180 of file Format_Post_Lata.cpp.
{
  if (est_le_premier_post)
    {
// Determination du format binaire:
// big endian => l'entier 32 bits "1" s'ecrit 0x00 0x00 0x00 0x01
// little endian =>                           0x01 0x00 0x00 0x00
      const unsigned int one = 1;
      const int big_endian = (* ((unsigned char *)&one) == 0) ? 1 : 0;
// Effacement du fichier .lata et ecriture de l'entete
//
      ////!<                              Fichier_Lata::ERASE,
      ////!<                              options_para_);
      Fichier_Lata_maitre fichier(base_name, extension_lata(),
                                  Fichier_Lata::ERASE,
                                  option);
      SFichier& sfichier = fichier.get_SFichier();
      if (fichier.is_master())
        {
          sfichier << "LATA_V2.1 Trio_U Version1.6 or later" << finl;
          sfichier << Objet_U::nom_du_cas() << finl;
          sfichier << "Trio_U verbosity=0" << finl;
          sfichier << "Format ";
//
          switch(format)
            {
            case ASCII:
              sfichier << "ASCII,";
              break;
            case BINAIRE:
              sfichier << "BINAIRE,";
              if (big_endian)
                sfichier << "BIG_ENDIAN,";
              else
                sfichier << "LITTLE_ENDIAN,";
              break;
            default:
              Cerr << "Error in Format_Post_Lata::ecrire_entete\n"
                   << " format not supported" << finl;
              exit();
            }
          switch(sizeof(_LATA_INT_TYPE_))
            {
            case 4:
              sfichier << "INT32,";
              break;
            case 8:
              sfichier << "INT64,";
              break;
            default:
              Cerr << "Error in Format_Post_Lata::ecrire_entete\n"
                   << " sizeof(int) not supported" << finl;
              exit();
            }
          sfichier << "F_INDEXING,C_ORDERING,F_MARKERS_SINGLE,REAL32" << finl;
        }
      fichier.syncfile();
    }
  return 1;
}
References _LATA_INT_TYPE_, ASCII, BINAIRE, Cerr, Fichier_Lata::ERASE, Process::exit(), extension_lata(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), Objet_U::nom_du_cas(), and Fichier_Lata::syncfile().
Referenced by ecrire_entete().
ecrire_item_int()
int Format_Post_Lata::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_zone, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) override virtual
voir Format_Post_base::ecrire_champ
ATTENTION: si "reference" est non vide on ajoute 1 a toutes les
valeurs pour passer en numerotation fortran, et si de plus on
ecrit un fichier lata unique pour tous les processeurs, on ajoute un
decalage a toutes les valeurs (renumerotation des indices pour
passer en numerotation globale, voir le codage de ecrire_domaine
par exemple)
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 1072 of file Format_Post_Lata.cpp.
{
// Construction du nom du fichier
  Nom basename_champ(lata_basename_);
  Nom extension_champ(extension_lata());
  extension_champ += ".";
// extension_champ += id_champ;
  extension_champ += id_item;
  extension_champ += ".";
  extension_champ += localisation;
  extension_champ += ".";
  extension_champ += id_du_domaine;
  extension_champ += ".";
  extension_champ += Nom(temps_courant_);
  Nom filename_champ;
  int size_tot, nb_compo;
  const IntTab& valeurs = static_cast<const IntTab&>(val);
  {
    Fichier_Lata fichier_champ(basename_champ, extension_champ,
                               Fichier_Lata::ERASE, format_, options_para_);
    filename_champ = fichier_champ.get_filename();
// On suppose que si reference est non vide, c'est un indice
// dans un autre tableau, donc numerotation fortran :
    int decal = 0;
    int decal_partiel=0;
    if (reference != "")
      {
        decal = 1;
        decal_partiel=1;
        if (options_para_ == SINGLE_FILE || options_para_ == SINGLE_FILE_MPIIO)
          {
// Tous les processeurs ecrivent dans un fichier unique, il faut
// renumeroter les indices pour passer en numerotation globale.
// Decalage a ajouter aux indices pour avoir une numerotation globale.
            decal_partiel += mppartial_sum(reference_size);
          }
      }
//
    size_tot = write_inttab(fichier_champ, decal,decal_partiel, valeurs, nb_compo,options_para_);
  }
  {
// Ouverture du fichier .lata en mode append.
// Ajout de la reference au champ
    Fichier_Lata_maitre fichier(lata_basename_, extension_lata(),
                                Fichier_Lata::APPEND, options_para_);
    SFichier& sfichier = fichier.get_SFichier();
    if (fichier.is_master())
      {
// sfichier << "Champ " << id_champ << " ";
        sfichier << "Champ " << id_item << " ";
        sfichier << remove_path(filename_champ);
        sfichier << " geometrie=" << id_du_domaine;
#ifdef INT_is_64_
        sfichier << " file_offset=6";
#endif
        if (localisation!="")
          sfichier << " localisation=" << localisation;
        sfichier << " size=" << size_tot;
        sfichier << " composantes=" << nb_compo;
        if (reference != "")
          sfichier << " reference=" << reference;
        const int sz = sizeof(_LATA_INT_TYPE_);
        switch(sz)
          {
          case 4:
            sfichier << " format=int32";
            break;
          case 8:
            sfichier << " format=int64";
            break;
          default:
            Cerr << "Error in Format_Post_Lata::ecrire_champ_lata\n"
                 << " Integer type not supported: size=" << sz << finl;
            exit();
          }
        sfichier << finl;
      }
    fichier.syncfile();
  }
// Astuce pour les donnees paralleles des faces:
  if ((id_item == "FACES" && Process::nproc() > 1) && (options_para_ == SINGLE_FILE || options_para_ == SINGLE_FILE_MPIIO))
    {
      const int n = valeurs.dimension(0);
      IntTab data(1,2);
      data(0, 0) = 1 + mppartial_sum(n);
      data(0, 1) = n;
      ecrire_item_int("JOINTS_FACES",
                      id_du_domaine,
                      "", /* id_zone */
                      "", /* localisation */
                      "", /* reference */
                      data,
                      0); /* reference_size */
    }
  return 1;
}
References _LATA_INT_TYPE_, Fichier_Lata::APPEND, Cerr, TRUSTTab< _TYPE_ >::dimension(), ecrire_item_int(), Fichier_Lata::ERASE, Process::exit(), extension_lata(), finl, format_, Fichier_Lata::get_filename(), Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), lata_basename_, mppartial_sum(), Process::nproc(), options_para_, remove_path(), SINGLE_FILE, SINGLE_FILE_MPIIO, Fichier_Lata::syncfile(), temps_courant_, and write_inttab().
Referenced by ecrire_domaine(), and ecrire_item_int().
ecrire_temps()
int Format_Post_Lata::ecrire_temps (const double temps) override virtual
commence l'ecriture d'un nouveau pas de temps
En l'occurence pour le format LATA:
Ouvre le fichier maitre en mode APPEND et ajoute une ligne
"TEMPS xxxxx" si ce temps n'a pas encore ete ecrit
Reimplemented from Format_Post_base.
Definition at line 971 of file Format_Post_Lata.cpp.
{
  ecrire_temps_lata(temps,temps_courant_,lata_basename_,status,options_para_);
  return 1;
}
References ecrire_temps_lata(), lata_basename_, options_para_, status, and temps_courant_.
ecrire_temps_lata()
int Format_Post_Lata::ecrire_temps_lata (const double temps, double & temps_format, const Nom & base_name, Status & stat, const Options_Para & option) static
Definition at line 1248 of file Format_Post_Lata.cpp.
{
  assert(stat != RESET);
// On ecrit le temps que si ce n'est pas le meme...
  if (stat != WRITING_TIME || temps_format != temps)
    {
      temps_format = temps;
// Ouverture du fichier .lata en mode append
      Fichier_Lata_maitre fichier(base_name,extension_lata(), Fichier_Lata::APPEND,option);
      if (fichier.is_master())
        {
          fichier.get_SFichier() << "TEMPS " << temps << finl;
        }
      fichier.syncfile();
      stat = WRITING_TIME;
    }
  return 1;
}
References Fichier_Lata::APPEND, extension_lata(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), RESET, Fichier_Lata::syncfile(), and WRITING_TIME.
Referenced by ecrire_temps(), and Postraitement_lata::ecrire_temps().
extension_lata()
const char * Format_Post_Lata::extension_lata () static
Renvoie l'extension conventionnelle des fichiers lata : ".lata".
Definition at line 209 of file Format_Post_Lata.cpp.
{
  static const char * ext = ".lata";
  return ext;
}
Referenced by ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), ecrire_entete_lata(), Format_Post_Lata_V1::ecrire_entete_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), ecrire_item_int(), ecrire_temps_lata(), finir(), Format_Post_Lata_V1::finir_lata_V1(), finir_sans_reprise(), and modify_file_basename().
finir()
int Format_Post_Lata::finir (int & est_le_dernier_post) override virtual
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 1266 of file Format_Post_Lata.cpp.
{
  if (est_le_dernier_post)
    {
      Fichier_Lata_maitre fichier(lata_basename_, extension_lata(),
                                  Fichier_Lata::APPEND,
                                  options_para_);
      SFichier& sfichier = fichier.get_SFichier();
      if (fichier.is_master())
        {
          sfichier << "FIN" << finl;
        }
      fichier.syncfile();
    }
  return 1;
}
References Fichier_Lata::APPEND, extension_lata(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), lata_basename_, options_para_, and Fichier_Lata::syncfile().
finir_sans_reprise()
int Format_Post_Lata::finir_sans_reprise (const Nom file_basename) virtual
< je lis le premier mot de la ligne dans .lata
< Si le mot suivant n'est pas TEMPS
< Si le temps trouvee = tinit alors
< je peux commencer a ecrire
< je lis le reste du .lata
< et j'ecris le tout dans le after_restart.lata
Definition at line 740 of file Format_Post_Lata.cpp.
{
  Nom post_file;
  post_file=lata_basename_+extension_lata();
  if (Process::je_suis_maitre())
    {
      struct stat f;
      if (stat(post_file,&f)==0)
        {
          EFichier Lata(file_basename);
          SFichier LataRep(post_file, ios::app);
          LataRep.setf(ios::scientific);
          LataRep.precision(8);
          std::string line;
          Nom mot;
          double temps;
          while (!Lata.eof())
            {
              Lata >> mot;                                                                //!< je lis le premier mot de la ligne dans .lata
              if (mot=="TEMPS")                                                        //!< Si le mot suivant n'est pas TEMPS
                {
                  Lata >> temps;
                  if (temps==tinit_)                                                        //!< Si le temps trouvee = tinit alors
                    {
                      std::getline(Lata.get_ifstream(), line) ;
                      LataRep.get_ofstream() << mot << " " << temps << line << std::endl;        //!< je peux commencer a ecrire
                      break;
                    }
                }
            }
          while (!Lata.eof())
            {
              std::getline(Lata.get_ifstream(), line);                                //!< je lis le reste du .lata
              LataRep.get_ofstream() << line << std::endl;                                        //!< et j'ecris le tout dans le after_restart.lata
            }
          Lata.close();
          LataRep.close();
          Cerr << "File " << post_file << " is built with times from tinit=" << tinit_ << finl;
        }
    }
  return 1;
}
References Cerr, Entree_Fichier_base::close(), Sortie_Fichier_base::close(), Entree_Fichier_base::eof(), extension_lata(), finl, Entree_Fichier_base::get_ifstream(), Sortie_Fichier_base::get_ofstream(), Process::je_suis_maitre(), lata_basename_, Sortie_Fichier_base::precision(), Sortie_Fichier_base::setf(), and tinit_.
Referenced by modify_file_basename().
get_info()
const Type_info * Format_Post_Lata::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 25 of file Format_Post_Lata.cpp.
info()
const Type_info * Format_Post_Lata::info () static
Definition at line 25 of file Format_Post_Lata.cpp.
initialize()
int Format_Post_Lata::initialize (const Nom & file_basename, const int format, const Nom & option_para) override virtual
Reimplemented from Format_Post_base.
Definition at line 593 of file Format_Post_Lata.cpp.
{
  assert(status == RESET);
// Changement du format LATA (par defaut binaire)
  format_=BINAIRE;
  if (format==0)
    format_=ASCII;
  if (Motcle(option_para)=="MPI-IO")
    options_para_ = SINGLE_FILE_MPIIO;
  else if (Motcle(option_para)=="SIMPLE")
    options_para_ = SINGLE_FILE;
  else if (Motcle(option_para)=="MULTIPLE")
    options_para_ = MULTIPLE_FILES;
  else
    {
      Cerr<<"The option " << option_para << " for lata format for the parallel is not correct."<<finl;
      exit();
    }
  initialize_lata(file_basename,format_,options_para_);
  return 1;
}
References ASCII, BINAIRE, Cerr, Process::exit(), finl, format_, initialize_lata(), MULTIPLE_FILES, options_para_, RESET, SINGLE_FILE, SINGLE_FILE_MPIIO, and status.
initialize_by_default()
int Format_Post_Lata::initialize_by_default (const Nom & file_basename) override virtual
Initialisation de la classe avec des parametres par
defaut (format ASCII, SINGLE_FILE)
Reimplemented from Format_Post_base.
Definition at line 586 of file Format_Post_Lata.cpp.
{
  assert(status == RESET);
  initialize_lata(file_basename, ASCII, SINGLE_FILE);
  return 1;
}
References ASCII, initialize_lata(), RESET, SINGLE_FILE, and status.
initialize_lata()
int Format_Post_Lata::initialize_lata (const Nom & file_basename, const Format format = ASCII, const Options_Para options_para = SINGLE_FILE) virtual
Initialisation de la classe, ouverture du fichier et ecriture
de l'entete.
Definition at line 620 of file Format_Post_Lata.cpp.
{
  assert(status == RESET);
  lata_basename_ = file_basename;
  format_ = format;
  options_para_ = options_para;
  status = INITIALIZED;
  return 1;
}
References format_, INITIALIZED, lata_basename_, options_para_, RESET, and status.
Referenced by initialize(), and initialize_by_default().
lire_motcle_non_standard()
int Format_Post_Lata::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Format_Post_base.
Definition at line 577 of file Format_Post_Lata.cpp.
{
  Cerr << "Format_Post_Lata::lire_motcle_non_standard: Not implemented." << finl;
  Process::exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
modify_file_basename()
int Format_Post_Lata::modify_file_basename (const Nom file_basename, const int a_faire, const double tinit) override virtual
Modification du nom du fichier de postraitement.
Reimplemented from Format_Post_base.
Definition at line 634 of file Format_Post_Lata.cpp.
{
  assert(a_faire==0||a_faire==1||a_faire==2);
  Nom post_file;
  post_file=file_basename+extension_lata();
// On verifie que le fichier maitre existe et a une entete correcte
  file_existe_=0;
  if (Process::je_suis_maitre())
    {
      struct stat f;
      if (stat(post_file,&f)==0)
        {
          EFichier tmp(post_file);
          Nom cle;
          tmp >> cle;
          if (cle.debute_par("LATA"))
            {
              if (tinit==-1)
                {
                  file_existe_=1;
                }
              else
                {
                  tmp >> cle;
                  while (!tmp.eof() && cle!="TEMPS") tmp >> cle;
                  if (cle=="TEMPS")
                    {
                      double temps;
                      tmp >> temps;
// On verifie le temps du fichier de reprise
                      if (temps<tinit)
                        file_existe_=1;
                    }
                }
            }
          tmp.close();
        }
    }
// Point de synchronisation necessaire:
  file_existe_ = (int)Process::mp_max(file_existe_);
  if (Process::je_suis_maitre() && file_existe_ && deja_fait_==0 && a_faire)
    {
      Nom before_restart;
      before_restart=file_basename+".before_restart"+extension_lata();
      rename(post_file,before_restart);
      Cerr << "File " << post_file << " is moved to " << before_restart << " with times<=tinit=" << tinit << finl;
      reconstruct(post_file,before_restart,tinit);
    }
  deja_fait_=1;
// On attend tous les processeurs (prudence excessive?)
  Process::barrier();
  if (file_existe_)
    {
      if (a_faire==0)
        lata_basename_ = file_basename;
      else
        {
          lata_basename_ = file_basename+".after_restart";
          if (tinit==-1) finir_sans_reprise(post_file);
        }
    }
  return 1;
}
References Process::barrier(), Cerr, Entree_Fichier_base::close(), Nom::debute_par(), deja_fait_, Entree_Fichier_base::eof(), extension_lata(), file_existe_, finir_sans_reprise(), finl, Process::je_suis_maitre(), lata_basename_, Process::mp_max(), and reconstruct().
preparer_post()
int Format_Post_Lata::preparer_post (const Nom & id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) override virtual
Reimplemented from Format_Post_base.
Definition at line 294 of file Format_Post_Lata.cpp.
{
  return 1;
}
printOn()
Sortie & Format_Post_Lata::printOn (Sortie & x) const override protected virtual
erreur => exit
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 549 of file Format_Post_Lata.cpp.
{
  Cerr << "Format_Post_Lata::printOn : error" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
Referenced by Format_Post_Lata_V1::printOn().
readOn()
Entree & Format_Post_Lata::readOn (Entree & is) override protected virtual
Lecture des parametres du postraitement au format "jeu de donnees"
Le format attendu est le suivant:
{
nom_fichier nom champ obligatoire
[ format ascii|binaire ] valeur par defaut : ascii
[ parallel single_file|multiple_files ] valeur par defaut : single_file
}.
Reimplemented from Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 563 of file Format_Post_Lata.cpp.
{
  assert(status == RESET);
  Format_Post_base::readOn(is);
  status = INITIALIZED;
  return is;
}
References INITIALIZED, Format_Post_base::readOn(), RESET, and status.
Referenced by Format_Post_Lata_V1::readOn().
reconstruct()
int Format_Post_Lata::reconstruct (const Nom file_basename, const Nom before_restart, const double tinit) virtual
< je lis le premier mot de la ligne dans .before_restart.lata
< Si le mot n'est pas FIN
< Si le mot suivant est TEMPS
< Si le temps trouvee = tinit alors j'arrete
< je lis le reste de la ligne
< et j'ecris le tout dans le lata
< je lis le reste de la ligne
< et j'ecris le tout dans le lata
< Sinon j'arrete
Definition at line 700 of file Format_Post_Lata.cpp.
{
  EFichier LataOld(before_restart);
  SFichier LataNew(post_file);
  LataNew.setf(ios::scientific);
  LataNew.precision(8);
  std::string line;
  Nom mot;
  double temps;
  tinit_=tinit;
  while (!LataOld.eof())
    {
      LataOld >> mot;                                                        //!< je lis le premier mot de la ligne dans .before_restart.lata
      if (mot!="FIN")                                                        //!< Si le mot n'est pas FIN
        {
          if (mot=="TEMPS")                                                        //!< Si le mot suivant est TEMPS
            {
              LataOld >> temps;
              if (temps==tinit)                                                //!< Si le temps trouvee = tinit alors j'arrete
                break;
              std::getline(LataOld.get_ifstream(), line) ;                        //!< je lis le reste de la ligne
              LataNew.get_ofstream() << mot << " " << temps << line << std::endl;        //!< et j'ecris le tout dans le lata
            }
          else
            {
              std::getline(LataOld.get_ifstream(), line) ;                        //!< je lis le reste de la ligne
              LataNew.get_ofstream() << mot << line << std::endl;                        //!< et j'ecris le tout dans le lata
            }
        }
      else
        {
          break;                                                                //!< Sinon j'arrete
        }
    }
  LataNew.close();
  LataOld.close();
  Cerr << "File " << post_file << " is rebuilt but truncated to times<tinit=" << tinit << finl;
  return 1;
}
References Cerr, Entree_Fichier_base::close(), Sortie_Fichier_base::close(), Entree_Fichier_base::eof(), finl, Entree_Fichier_base::get_ifstream(), Sortie_Fichier_base::get_ofstream(), Sortie_Fichier_base::precision(), Sortie_Fichier_base::setf(), and tinit_.
Referenced by modify_file_basename().
remove_path()
const char * Format_Post_Lata::remove_path (const char * filename) static
Renvoie le nom d'un fichier sans le path :
on enleve les caracteres avant le dernier /.
Definition at line 218 of file Format_Post_Lata.cpp.
{
  int i = strlen(filename);
  while (i > 0 && filename[i-1] != '/')
    i--;
  return filename + i;
}
Referenced by ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), and ecrire_item_int().
reset()
void Format_Post_Lata::reset () override virtual
Remet l'objet dans l'etat obtenu par le constructeur par defaut.
Implements Format_Post_base.
Reimplemented in Format_Post_Lata_V1.
Definition at line 536 of file Format_Post_Lata.cpp.
{
  lata_basename_ = "??";
  format_ = ASCII;
  options_para_ = SINGLE_FILE;
  status = RESET;
  temps_courant_ = -1.;
  deja_fait_=0;
  tinit_=-1.;
  file_existe_=0;
}
References ASCII, deja_fait_, file_existe_, format_, lata_basename_, options_para_, RESET, SINGLE_FILE, status, temps_courant_, and tinit_.
Referenced by Format_Post_Lata().
self_cast() [1/2]
const Format_Post_Lata & Format_Post_Lata::self_cast (const Objet_U & r) static
Definition at line 25 of file Format_Post_Lata.cpp.
self_cast() [2/2]
Format_Post_Lata & Format_Post_Lata::self_cast (Objet_U & r) static
Definition at line 25 of file Format_Post_Lata.cpp.
set_param()
void Format_Post_Lata::set_param (Param & param) override virtual
Implements Format_Post_base.
Definition at line 571 of file Format_Post_Lata.cpp.
{
  Cerr << "Format_Post_Lata::set_param: Not implemented." << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
taille_memoire()
unsigned Format_Post_Lata::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Format_Post_Lata_V1.
Definition at line 25 of file Format_Post_Lata.cpp.
write_doubletab()
int Format_Post_Lata::write_doubletab (Fichier_Lata & fichier, const DoubleTab & tab, int & nb_colonnes, const Options_Para & option, const int bloc_number = 0, const int nb_blocs = 1) static protected
fichier est un fichier lata de donnees (pas le fichier maitre)
on y ecrit le tableau tab tel quel (en binaire ou ascii et sur un ou
plusieurs fichiers en parallel).
nb_colonnes est rempli avec le produit des tab.dimension(i) pour i>0
bloc_number et nb_blocs sont utilises pour les valeurs aux sommets en 2D
pour le format lataV1 : on ecrit deux fois le nombre de sommets dans le meme bloc
(bloc_number = le numero du bloc courant en cours d'ecriture,
nb_blocs = le nombre total de blocs ecrits. Le tag de debut et de fin
est ecrit au debut du premier bloc et a la fin du dernier et le nombre est
la taille du tableau multiplie par le nombre de blocs (on suppose que tous
les blocs sont identiques)).
< Zut. Pas de mp_max(int) !!!
< No ArrOfFloat in TRUST
Definition at line 312 of file Format_Post_Lata.cpp.
{
  int line_size = 1;
  int nb_lignes = tab.dimension(0);
  const int nb_dim = tab.nb_dim();
  for (int i = 1; i < nb_dim; i++)
    line_size *= tab.dimension(i);
  int nb_lignes_tot = 0;
  const int tab_size = line_size * nb_lignes;
  int nb_octets = tab_size * sizeof(float);
  switch(option)
    {
    case Format_Post_Lata::SINGLE_FILE_MPIIO:
    case Format_Post_Lata::SINGLE_FILE:
      nb_lignes_tot = Process::mp_sum(nb_lignes);
// En parallele, tous les tableaux doivent avoir le meme nombre
// de colonnes (ou etre vides).
      nb_colonnes = (int) Process::mp_max(line_size); //!< Zut. Pas de mp_max(int) !!!
      nb_octets = nb_colonnes*nb_lignes_tot * sizeof(float);
      assert(nb_lignes == 0 || line_size == nb_colonnes);
      break;
    case Format_Post_Lata::MULTIPLE_FILES:
      nb_lignes_tot = nb_lignes;
      nb_colonnes = line_size;
      break;
    default:
      Cerr << "Format_Post_Lata_write_tab: error nb_lignes_tot" << finl;
      Process::exit();
    }
  SFichier& sfichier = fichier.get_SFichier();
// Debut de bloc fortran
  if (fichier.is_master() && bloc_number == 0)
    sfichier << nb_octets * nb_blocs << finl;
// Ecriture des donnees.
  if (sub_type(EcrFicPartageMPIIO, sfichier))
    {
      auto *tmp = new float[tab_size]; //!< No ArrOfFloat in TRUST
      const double *data = tab.addr();
      for (int i = 0; i < tab_size; i++)
        tmp[i] = data[i];
      sfichier.put(tmp, tab_size, line_size);
      delete[] tmp;
// Fin de bloc fortran
      if (fichier.is_master() && bloc_number == nb_blocs - 1)
        sfichier << nb_octets * nb_blocs << finl;
    }
  else
    {
// On convertit le tout en float par paquet de N valeurs
// Buffer dont la taille est un multiple de line_size:
      const int N = 16384;
      int bufsize = (N / line_size + 1) * line_size;
      float *tmp = new float[bufsize];
      const double *data = tab.addr();
      for (int i = 0; i < tab_size; i += bufsize)
        {
          int j_max = bufsize;
          if (j_max > tab_size - i)
            j_max = tab_size - i;
// Conversion du bloc en float:
          for (int j = 0; j < j_max; j++)
            tmp[j] = data[i + j];
// Ecriture avec retour a la ligne a chaque ligne du tableau
          sfichier.put(tmp, j_max, line_size);
        }
      delete[] tmp;
      fichier.syncfile();
// Fin de bloc fortran
      if (fichier.is_master() && bloc_number == nb_blocs - 1)
        sfichier << nb_octets * nb_blocs << finl;
      fichier.syncfile();
    }
  return nb_lignes_tot;
}
References TRUSTArray< _TYPE_ >::addr(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), Process::mp_max(), Process::mp_sum(), MULTIPLE_FILES, TRUSTTab< _TYPE_ >::nb_dim(), Sortie::put(), SINGLE_FILE, SINGLE_FILE_MPIIO, sub_type, and Fichier_Lata::syncfile().
Referenced by ecrire_champ(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), ecrire_domaine(), and Format_Post_Lata_V1::ecrire_domaine_lata_V1().
write_inttab()
int Format_Post_Lata::write_inttab (Fichier_Lata & fichier, int decalage, int decalage_partiel, const IntTab & tab, int & nb_colonnes, const Options_Para & option) static protected
Ecriture d'un tableau d'entiers dans le fichier fourni.
Les valeurs ecrites sont les valeurs du tableau auquelles ont ajoute
"decalage". Cette valeur est utilisee pour passer en numerotation
fortran (ajouter 1), ou pour passer en numerotation globale (ajouter
le nombre d'elements sur les processeurs precedents).
On renvoie dans nb_colonnes la somme des dimension(i) pour i>0.
Valeur de retour: somme des dimension(0) ecrits (selon que tous les
processeurs ecrivent sur le meme fichier ou pas).
< Zut. Pas de mp_max(int) !!!
Definition at line 402 of file Format_Post_Lata.cpp.
{
  assert(decalage_partiel>=decalage);
  assert((decalage==0)||(decalage==1));
  int nb_lignes = 0;
  int line_size = 1;
  int i;
  nb_lignes = tab.dimension(0);
  const int nb_dim = tab.nb_dim();
  for (i = 1; i < nb_dim; i++)
    line_size *= tab.dimension(i);
  int nb_lignes_tot = 0;
  const int tab_size = line_size * nb_lignes;
  int nb_octets = tab_size * sizeof(_LATA_INT_TYPE_);
  switch(option)
    {
    case Format_Post_Lata::SINGLE_FILE_MPIIO:
    case Format_Post_Lata::SINGLE_FILE:
      nb_lignes_tot = Process::mp_sum(nb_lignes);
// En parallele, tous les tableaux doivent avoir le meme nombre
// de colonnes (ou etre vides).
      nb_colonnes = (int) Process::mp_max(line_size); //!< Zut. Pas de mp_max(int) !!!
      nb_octets = nb_colonnes*nb_lignes_tot * sizeof(_LATA_INT_TYPE_);
      assert(nb_lignes == 0 || line_size == nb_colonnes);
      break;
    case Format_Post_Lata::MULTIPLE_FILES:
      nb_lignes_tot = nb_lignes;
      nb_colonnes = line_size;
      break;
    default:
      Cerr << "Format_Post_Lata_write_tab: error nb_lignes_tot" << finl;
      exit();
    }
  SFichier& sfichier = fichier.get_SFichier();
// Debut de bloc fortran
  if (fichier.is_master())
    sfichier << nb_octets << finl;
  int erreurs = 0;
// Ecriture des donnees.
  if (sub_type(EcrFicPartageMPIIO, sfichier))
    {
// On convertit le tout en _INT_TYPE_
      _LATA_INT_TYPE_ *tmp = new _LATA_INT_TYPE_[tab_size];
      const int *data = tab.addr();
      for (i = 0; i < tab_size; i++)
        {
// valeur a ecrire (conversion en numerotation fortran si besoin)
          int x = data[i];
          if (x > -1)
            x += decalage_partiel;
          else
            x += decalage;
// conversion en type int pour ecriture
          _LATA_INT_TYPE_ y = (_LATA_INT_TYPE_) x;
// reconversion en int pour comparaison
          int z = (int) y;
          if (x != z)
            erreurs++;
          tmp[i] = y;
        }
      sfichier.put(tmp, tab_size, line_size);
      delete[] tmp;
// Fin de bloc fortran
      if (fichier.is_master())
        sfichier << nb_octets << finl;
    }
  else
    {
// On convertit le tout en _INT_TYPE_ par paquet de N valeurs
// Buffer dont la taille est un multiple de line_size:
      const int N = 16384;
      int bufsize = (N / line_size + 1) * line_size;
      _LATA_INT_TYPE_ *tmp = new _LATA_INT_TYPE_[bufsize];
      const int *data = tab.addr();
      for (i = 0; i < tab_size; i += bufsize)
        {
          int j;
          int j_max = bufsize;
          if (j_max > tab_size - i)
            j_max = tab_size - i;
// Conversion du bloc en int_type:
          for (j = 0; j < j_max; j++)
            {
// valeur a ecrire (conversion en numerotation fortran si besoin)
              int x = data[i + j];
              if (x > -1)
                x += decalage_partiel;
              else
                x += decalage;
// conversion en type int pour ecriture
              _LATA_INT_TYPE_ y = (_LATA_INT_TYPE_) x;
// reconversion en int pour comparaison
              int z = (int) y;
              if (x != z)
                erreurs++;
              tmp[j] = y;
            }
// Ecriture avec retour a la ligne a chaque ligne du tableau
          sfichier.put(tmp, j_max, line_size);
        }
      delete[] tmp;
      fichier.syncfile();
// Fin de bloc fortran
      if (fichier.is_master())
        sfichier << nb_octets << finl;
      fichier.syncfile();
    }
  if (erreurs > 0)
    {
      Cerr << "Error in Format_Post_Lata::write_inttab\n"
           << " Some integers were truncated\n"
           << " Recompile the code with #define _LATA_INT_TYPE_ entier" << finl;
      exit();
    }
  return nb_lignes_tot;
}
References _LATA_INT_TYPE_, TRUSTArray< _TYPE_ >::addr(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Fichier_Lata::get_SFichier(), Fichier_Lata::is_master(), Process::mp_max(), Process::mp_sum(), MULTIPLE_FILES, TRUSTTab< _TYPE_ >::nb_dim(), Sortie::put(), SINGLE_FILE, SINGLE_FILE_MPIIO, sub_type, and Fichier_Lata::syncfile().
Referenced by ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), and ecrire_item_int().
Member Data Documentation
deja_fait_
int Format_Post_Lata::deja_fait_ protected
Definition at line 116 of file Format_Post_Lata.h.
Referenced by modify_file_basename(), and reset().
file_existe_
int Format_Post_Lata::file_existe_ protected
Definition at line 116 of file Format_Post_Lata.h.
Referenced by modify_file_basename(), and reset().
format_
Format Format_Post_Lata::format_ protected
Definition at line 119 of file Format_Post_Lata.h.
Referenced by ecrire_champ(), Format_Post_Lata_V1::ecrire_champ(), ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), ecrire_entete(), ecrire_item_int(), Format_Post_Lata_V1::ecrire_item_int(), initialize(), initialize_lata(), and reset().
info_obj
const Type_info Format_Post_Lata::info_obj static
Definition at line 51 of file Format_Post_Lata.h.
lata_basename_
Nom Format_Post_Lata::lata_basename_ protected
Definition at line 118 of file Format_Post_Lata.h.
Referenced by ecrire_champ(), Format_Post_Lata_V1::ecrire_champ(), ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), ecrire_entete(), Format_Post_Lata_V1::ecrire_entete(), ecrire_item_int(), Format_Post_Lata_V1::ecrire_item_int(), ecrire_temps(), finir(), Format_Post_Lata_V1::finir(), finir_sans_reprise(), initialize_lata(), modify_file_basename(), and reset().
options_para_
Options_Para Format_Post_Lata::options_para_ protected
Definition at line 120 of file Format_Post_Lata.h.
Referenced by ecrire_champ(), Format_Post_Lata_V1::ecrire_champ(), ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), ecrire_entete(), Format_Post_Lata_V1::ecrire_entete(), ecrire_item_int(), Format_Post_Lata_V1::ecrire_item_int(), ecrire_temps(), finir(), Format_Post_Lata_V1::finir(), initialize(), initialize_lata(), and reset().
status
Status Format_Post_Lata::status protected
Definition at line 121 of file Format_Post_Lata.h.
Referenced by ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), ecrire_temps(), initialize(), initialize_by_default(), initialize_lata(), readOn(), and reset().
temps_courant_
double Format_Post_Lata::temps_courant_ protected
Definition at line 131 of file Format_Post_Lata.h.
Referenced by ecrire_domaine(), ecrire_item_int(), ecrire_temps(), and reset().
tinit_
double Format_Post_Lata::tinit_ protected
Definition at line 117 of file Format_Post_Lata.h.
Referenced by finir_sans_reprise(), reconstruct(), and reset().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Format_Post_Lata.h
src/Kernel/Framework/Format_Post_Lata.cpp