TRUST: Assembleur_P_PolyMAC_P0 Class Reference
Assembleur_P_PolyMAC_P0 Class Reference
#include <Assembleur_P_PolyMAC_P0.h>
Public Member Functions
Assembleur_P_PolyMAC_P0 ()
~Assembleur_P_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u) override
void dimensionner_continuite (matrices_t matrices, int aux_only=0) const override
void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const override
void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const override
Public Member Functions inherited from Assembleur_P_PolyMAC
Assembleur_P_PolyMAC ()
~Assembleur_P_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
int assembler_QC (const DoubleTab &, Matrice &) override
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u) override
void dimensionner_continuite (matrices_t matrices, int aux_only=0) const override
void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const override
DoubleTab norme_continuite () const override
int modifier_secmem (DoubleTab &) override
void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const override
int modifier_solution (DoubleTab &) override
void completer (const Equation_base &) override
const Equation_base & equation () const
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_PolyMAC_P0 & self_cast (Objet_U &)
static const Assembleur_P_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_P_PolyMAC
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_PolyMAC & self_cast (Objet_U &)
static const Assembleur_P_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_P_PolyMAC
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Assembleur_P_PolyMAC
Ref_Equation_base mon_equation
Ref_Zone_PolyMAC la_zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_zone_Cl_PolyMAC
int has_P_ref
int stencil_done
IntVect tab1
IntVect tab2
Detailed Description
Definition at line 27 of file Assembleur_P_PolyMAC_P0.h.
Constructor & Destructor Documentation
Assembleur_P_PolyMAC_P0()
Assembleur_P_PolyMAC_P0::Assembleur_P_PolyMAC_P0 ()
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
~Assembleur_P_PolyMAC_P0()
Assembleur_P_PolyMAC_P0::~Assembleur_P_PolyMAC_P0 ()
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
Member Function Documentation
assembler_continuite()
void Assembleur_P_PolyMAC_P0::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const override virtual
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 124 of file Assembleur_P_PolyMAC_P0.cpp.
{
  if (aux_only) return;
  const DoubleTab& alpha = ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().valeurs();
  Matrice_Morse& mat = *matrices.at("alpha");
  const DoubleVect& ve = la_zone_PolyMAC->volumes(), &pe = la_zone_PolyMAC->porosite_elem();
  int e, n, N = alpha.line_size();
  /* second membre : on multiplie par porosite * volume pour que le systeme en P soit symetrique en cartesien */
  for (e = 0; e < la_zone_PolyMAC->nb_elem(); e++)
    for (secmem(e) = -pe(e) * ve(e), n = 0; n < N; n++) secmem(e) += pe(e) * ve(e) * alpha(e, n);
  /* matrice */
  for (e = 0; e < la_zone_PolyMAC->nb_elem(); e++)
    for (n = 0; n < N; n++) mat(e, N * e + n) = -pe(e) * ve(e);
}
References Assembleur_P_PolyMAC::equation(), Assembleur_P_PolyMAC::la_zone_PolyMAC, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), ref_cast, and Zone_VF::volumes().
assembler_mat()
int Assembleur_P_PolyMAC_P0::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 52 of file Assembleur_P_PolyMAC_P0.cpp.
{
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  la_matrice.typer("Matrice_Morse");
  Matrice_Morse& mat = ref_cast(Matrice_Morse, la_matrice.valeur());
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, la_zone_PolyMAC.valeur());
  const Op_Grad_PolyMAC_P0_Face& grad = ref_cast(Op_Grad_PolyMAC_P0_Face, ref_cast(Navier_Stokes_std, equation()).operateur_gradient().valeur());
  grad.update_grad();
  const DoubleTab& fgrad_c = grad.fgrad_c;
  const IntTab& f_e = zone.face_voisins(), &fgrad_d = grad.fgrad_d, &fgrad_e = grad.fgrad_e;
  const DoubleVect& pf = zone.porosite_face(), &fs = zone.face_surfaces();
  int i, j, e, eb, f, ne = zone.nb_elem(), ne_tot = zone.nb_elem_tot();
// en l'absence de CLs en pression, on ajoute P(0) = 0 sur le process 0
  has_P_ref=0;
  for (int n_bord=0; n_bord<la_zone_PolyMAC->nb_front_Cl(); n_bord++)
    if (sub_type(Neumann_sortie_libre, la_zone_Cl_PolyMAC->les_conditions_limites(n_bord).valeur()) )
      has_P_ref=1;
  /* 1. stencil de la matrice en pression : seulement au premier passage */
  if (!stencil_done)
    {
      IntTrav stencil(0, 2);
      stencil.set_smart_resize(1);
      for (f = 0; f < zone.nb_faces(); f++)
        for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
          if (e < ne)
            for (j = fgrad_d(f); j < fgrad_d(f + 1); j++)
              if ((eb = fgrad_e(j)) < ne_tot) stencil.append_line(e, eb);
      tableau_trier_retirer_doublons(stencil);
      Matrix_tools::allocate_morse_matrix(ne_tot, ne_tot, stencil, mat);
      mat.sort_stencil();
      tab1.ref_array(mat.get_set_tab1()), tab2.ref_array(mat.get_set_tab2());
      stencil_done = 1;
    }
  else //sinon, on recycle
    {
      mat.get_set_tab1().ref_array(tab1);
      mat.get_set_tab2().ref_array(tab2);
      mat.get_set_coeff().resize(tab2.size());
      mat.set_nb_columns(ne_tot);
    }
  /* 2. remplissage des coefficients : style Op_Diff_PolyMAC_Elem */
  for (f = 0; f < zone.nb_faces(); f++)
    for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
      if (e < ne)
        for (j = fgrad_d(f); j < fgrad_d(f + 1); j++)
          if ((eb = fgrad_e(j)) < ne_tot)
            mat(e, eb) += (i ? 1 : -1) * pf(f) * fs(f) * fgrad_c(j, 0);
  if (!has_P_ref && !Process::me()) mat(0, 0) *= 2;
  return 1;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Assembleur_P_PolyMAC::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Op_Grad_PolyMAC_P0_Face::fgrad_c, Op_Grad_PolyMAC_P0_Face::fgrad_d, Op_Grad_PolyMAC_P0_Face::fgrad_e, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Assembleur_P_PolyMAC::has_P_ref, Assembleur_P_PolyMAC::la_zone_Cl_PolyMAC, Assembleur_P_PolyMAC::la_zone_PolyMAC, Zone_Cl_dis_base::les_conditions_limites(), Process::me(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Zone_VF::porosite_face(), TRUSTVect< _TYPE_ >::ref_array(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size(), Matrice_Morse::sort_stencil(), Assembleur_P_PolyMAC::stencil_done, sub_type, Assembleur_P_PolyMAC::tab1, Assembleur_P_PolyMAC::tab2, tableau_trier_retirer_doublons(), Deriv_::typer(), Op_Grad_PolyMAC_P0_Face::update_grad(), Deriv_Cond_lim_base::valeur(), Deriv_Matrice_Base::valeur(), Ref_Zone_PolyMAC::valeur(), and valeur().
cree_instance()
Objet_U * Assembleur_P_PolyMAC_P0::cree_instance () static
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
dimensionner_continuite()
void Assembleur_P_PolyMAC_P0::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const override virtual
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 113 of file Assembleur_P_PolyMAC_P0.cpp.
{
  if (aux_only) return; //rien a faire
  int e, n, N = ref_cast(Pb_Multiphase, equation().probleme()).nb_phases(), ne_tot = la_zone_PolyMAC->nb_elem_tot();
  IntTrav stencil(0, 2);
  stencil.set_smart_resize(1);
  for (e = 0; e < la_zone_PolyMAC->nb_elem(); e++)
    for (n = 0; n < N; n++) stencil.append_line(e, N * e + n);
  Matrix_tools::allocate_morse_matrix(ne_tot, N * ne_tot, stencil, *matrices.at("alpha"));
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Assembleur_P_PolyMAC::equation(), Assembleur_P_PolyMAC::la_zone_PolyMAC, Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), ref_cast, and TRUSTArray< _TYPE_ >::set_smart_resize().
duplique()
int Assembleur_P_PolyMAC_P0::duplique () const override virtual
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
get_info()
const Type_info * Assembleur_P_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
info()
const Type_info * Assembleur_P_PolyMAC_P0::info () static
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
modifier_secmem_pour_incr_p()
void Assembleur_P_PolyMAC_P0::modifier_secmem_pour_incr_p (const DoubleTab & press, const double fac, DoubleTab & incr) const inline override virtual
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 35 of file Assembleur_P_PolyMAC_P0.h.
{ } //rien a faire
printOn()
Sortie & Assembleur_P_PolyMAC_P0::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 42 of file Assembleur_P_PolyMAC_P0.cpp.
{
  return s << que_suis_je() << " " << le_nom() ;
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_PolyMAC_P0::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 47 of file Assembleur_P_PolyMAC_P0.cpp.
{
  return Assembleur_P_PolyMAC::readOn(s);
}
References Assembleur_P_PolyMAC::readOn().
self_cast() [1/2]
const Assembleur_P_PolyMAC_P0 & Assembleur_P_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
self_cast() [2/2]
Assembleur_P_PolyMAC_P0 & Assembleur_P_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
taille_memoire()
unsigned Assembleur_P_PolyMAC_P0::taille_memoire () const override virtual
Reimplemented from Assembleur_P_PolyMAC.
Definition at line 40 of file Assembleur_P_PolyMAC_P0.cpp.
Member Data Documentation
info_obj
const Type_info Assembleur_P_PolyMAC_P0::info_obj static
Definition at line 29 of file Assembleur_P_PolyMAC_P0.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Solveurs/Assembleur_P_PolyMAC_P0.h
src/PolyMAC/Solveurs/Assembleur_P_PolyMAC_P0.cpp