TRUST: Ch_front_input_P1 Class Reference
Ch_front_input_P1 Class Reference
class Ch_front_input
Cette classe represente un champ accessible par setInputField
defini sur une frontiere avec une valeur par face.
#include <Ch_front_input_P1.h>
Public Member Functions
Ch_front_input_P1 ()
~Ch_front_input_P1 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const override
int valeur_au_temps_et_au_point_disponible () const override
void setValue (const TrioField &afield) override
void getTemplate (TrioField &afield) const override
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Public Member Functions inherited from Ch_front_input
Ch_front_input ()
~Ch_front_input ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &) override
void getTemplate (TrioField &afield) const override
void setValue (const TrioField &afield) override
void setDoubleValue (const double val) override
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
void buildSommetsFaces () const
const because used in Ch_Front_input_ALE::getTemplate() which is const - actually updates the 2 members below due to ALE mesh movement:
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Public Member Functions inherited from Champ_Input_Proto
virtual ~Champ_Input_Proto ()
virtual void getTemplate (TrioField &afield) const =0
virtual void setValue (const TrioField &afield)=0
void setInitialValue (const ArrOfDouble &vo)
virtual void setDoubleValue (const double val)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_input_P1 & self_cast (Objet_U &)
static const Ch_front_input_P1 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_input
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_input & self_cast (Objet_U &)
static const Ch_front_input & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_input
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Ch_front_input
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_nb_comp (int i) override
calls fixer_nb_comp
void set_name (const Nom &) override
calls nommer
virtual const Nom & get_name () const
calls le_nom
Protected Member Functions inherited from Ch_front_var_instationnaire_dep
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_front_var_instationnaire
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Champ_Input_Proto
void read (Entree &is)
Lecture d'un champ input dans un flot d'entree
Factorisation des readOn des differents Champ_input
Format:
{ nb_comp nombre_de_composantes_du_champ
nom nom_du_champ
probleme nom_du_probleme_base_associe
[sous_zone nom_de_la_sous_zone_associee] }.
void setValueOnTab (const TrioField &afield, DoubleTab &tab)
virtual void set_nb_comp (int i)=0
calls fixer_nb_comp
virtual void set_name (const Nom &name)=0
calls nommer
Protected Attributes
Roue_ptr les_valeurs_som
Protected Attributes inherited from Ch_front_input
DoubleTab sommets_
mutable because of buildSommetsFaces function used in ALE
IntTab faces_
mutable because of buildSommetsFaces function used in ALE
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Protected Attributes inherited from Champ_Input_Proto
Ref_Probleme_base mon_pb
bool sous_zone_ok
This fields knows how to deal with a sous_zone.
Ref_Sous_Zone ma_sous_zone
ArrOfDouble initial_value_
Detailed Description
class Ch_front_input
Cette classe represente un champ accessible par setInputField
defini sur une frontiere avec une valeur par face.
Definition at line 34 of file Ch_front_input_P1.h.
Constructor & Destructor Documentation
Ch_front_input_P1()
Ch_front_input_P1::Ch_front_input_P1 ()
Definition at line 27 of file Ch_front_input_P1.cpp.
~Ch_front_input_P1()
Ch_front_input_P1::~Ch_front_input_P1 ()
Definition at line 27 of file Ch_front_input_P1.cpp.
Member Function Documentation
cree_instance()
Objet_U * Ch_front_input_P1::cree_instance () static
Definition at line 27 of file Ch_front_input_P1.cpp.
duplique()
int Ch_front_input_P1::duplique () const override virtual
Reimplemented from Ch_front_input.
Definition at line 27 of file Ch_front_input_P1.cpp.
get_info()
const Type_info * Ch_front_input_P1::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_input.
Definition at line 27 of file Ch_front_input_P1.cpp.
getTemplate()
void Ch_front_input_P1::getTemplate (TrioField & afield) const override virtual
Reimplemented from Ch_front_input.
Definition at line 118 of file Ch_front_input_P1.cpp.
{
  afield.clear();
  afield.setName(le_nom().getChar());
  afield._type=1;
  afield._time1=mon_pb->presentTime();
  afield._time2=mon_pb->futureTime();
  afield._nb_field_components=nb_comp();
  const DoubleTab& sommets=sommets_;
  const IntTab& faces=faces_;
  assert(sommets.nb_dim()==2);
  assert(faces.nb_dim()==2);
  afield._space_dim=sommets.dimension(1);
  afield._mesh_dim=afield._space_dim-1;
  afield._nbnodes=sommets.dimension(0);
  afield._nodes_per_elem=::mp_max(faces.dimension(1));
  afield._nb_elems=faces.dimension(0);
// Includes all the nodes, even those not used in connectivity
// order is  x y z  x y z  x y z
  affecte_double_avec_doubletab(&afield._coords,sommets);
  affecte_int_avec_inttab(&afield._connectivity,faces);
}
References affecte_double_avec_doubletab(), affecte_int_avec_inttab(), TRUSTTab< _TYPE_ >::dimension(), Ch_front_input::faces_, Probleme_base::futureTime(), Field_base::le_nom(), Champ_Input_Proto::mon_pb, Process::mp_max(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), Probleme_base::presentTime(), and Ch_front_input::sommets_.
info()
const Type_info * Ch_front_input_P1::info () static
Definition at line 27 of file Ch_front_input_P1.cpp.
initialiser()
int Ch_front_input_P1::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Ch_front_input.
Definition at line 40 of file Ch_front_input_P1.cpp.
{
  if (!Ch_front_input::initialiser(temps,inco))
    return 0;
  /* mis sans ch_fr_input ...
     const DoubleTab& sommets_org=(mon_pb->domaine().les_sommets());
     DoubleTab& sommets=sommets_;
     sommets=sommets_org;
     sommets.set_smart_resize(1);
     IntTab& faces=faces_;
     faces=(frontiere_dis().frontiere().faces().les_sommets());
     int ntot=0;
     ArrOfInt marqueur(sommets_org.dimension(0));
     marqueur=-1;
     for (int f=0;f<faces.dimension(0);f++)
     {
     for (int s=0;s<faces.dimension(1);s++)
     {
     int som=faces(f,s);
     if (marqueur(som)==-1)
     {
     marqueur(som)=ntot;
     for (int dir=0;dir<dimension;dir++)
     {
     sommets(ntot,dir)=sommets_org(som,dir);
     }
     ntot++;
     }
     }
     }
     sommets.resize(ntot,dimension);
     // on refait les faces
     for (int f=0;f<faces.dimension(0);f++)
     for (int s=0;s<faces.dimension(1);s++)
     faces(f,s)=faces(f,marqueur(s));
  */
  int ntot=sommets_.dimension(0);
  les_valeurs_som->fixer_nb_cases(les_valeurs->nb_cases());
  for (int i=0; i<les_valeurs_som->nb_cases(); i++)
    les_valeurs_som[i].valeurs().resize(ntot,nb_comp());
// Cerr<<" ici "<< les_valeurs->valeurs()<<finl;
  if (initial_value_.size_array()!=0)
    {
      for (int i=0; i<les_valeurs_som->nb_cases(); i++)
        for (int j=0; j<ntot; j++)
          for (int c=0; c<nb_comp(); c++)
            les_valeurs_som[i].valeurs()(j,c)=initial_value_[c];
    }
  ;
  return 1;
}
References TRUSTTab< _TYPE_ >::dimension(), Roue::fixer_nb_cases(), Champ_Input_Proto::initial_value_, Ch_front_input::initialiser(), Champ_front_base::les_valeurs, les_valeurs_som, Roue::nb_cases(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), Ch_front_input::sommets_, and Champ_front_base::valeurs().
printOn()
Sortie & Ch_front_input_P1::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_input.
Definition at line 35 of file Ch_front_input_P1.cpp.
{
  return  Ch_front_input::printOn(os);
}
References Ch_front_input::printOn().
readOn()
Entree & Ch_front_input_P1::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_input.
Definition at line 30 of file Ch_front_input_P1.cpp.
{
  return Ch_front_input::readOn(is);
}
References Ch_front_input::readOn().
self_cast() [1/2]
const Ch_front_input_P1 & Ch_front_input_P1::self_cast (const Objet_U & r) static
Definition at line 27 of file Ch_front_input_P1.cpp.
self_cast() [2/2]
Ch_front_input_P1 & Ch_front_input_P1::self_cast (Objet_U & r) static
Definition at line 27 of file Ch_front_input_P1.cpp.
setValue()
void Ch_front_input_P1::setValue (const TrioField & afield) override virtual
Reimplemented from Ch_front_input.
Definition at line 148 of file Ch_front_input_P1.cpp.
{
// exit();
// Cerr<<afield._nb_elems<<" cii "<<les_valeurs_som[1].valeurs().dimension(0)<<finl;
  for (int i=1; i<les_valeurs_som->nb_cases(); i++)
    Champ_Input_Proto::setValueOnTab(afield,les_valeurs_som[i].valeurs());
// Cout<<" IIIIIIII "<<les_valeurs_som[1].valeurs()<<finl;
  Gpoint(afield._time1,afield._time2);
}
References Champ_front_var_instationnaire::Gpoint(), les_valeurs_som, Roue::nb_cases(), Champ_Input_Proto::setValueOnTab(), and Champ_front_base::valeurs().
taille_memoire()
unsigned Ch_front_input_P1::taille_memoire () const override virtual
Reimplemented from Ch_front_input.
Definition at line 27 of file Ch_front_input_P1.cpp.
valeur_au_temps_et_au_point()
double Ch_front_input_P1::valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const override virtual
Reimplemented from Champ_front_var_instationnaire.
Definition at line 100 of file Ch_front_input_P1.cpp.
{
  const DoubleTab& sommets=sommets_;
  for (int som2=0; som2<sommets.dimension(0); som2++)
    {
      if ((dimension<3)||(est_egal(sommets(som2,2),z)))
        if ((dimension<2)||(est_egal(sommets(som2,1),y)))
          if (est_egal(sommets(som2,0),x))
            return les_valeurs_som[1].valeurs()(som2,comp);
    }
  Cerr<<" point non trouve "<<finl;
  exit();
  return -1.;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, est_egal(), Process::exit(), finl, les_valeurs_som, and Ch_front_input::sommets_.
valeur_au_temps_et_au_point_disponible()
int Ch_front_input_P1::valeur_au_temps_et_au_point_disponible () const inline override virtual
Reimplemented from Champ_front_var_instationnaire.
Definition at line 41 of file Ch_front_input_P1.h.
  {
    return 1;
  };
Member Data Documentation
info_obj
const Type_info Ch_front_input_P1::info_obj static
Definition at line 36 of file Ch_front_input_P1.h.
les_valeurs_som
Roue_ptr Ch_front_input_P1::les_valeurs_som protected
Definition at line 50 of file Ch_front_input_P1.h.
Referenced by initialiser(), setValue(), and valeur_au_temps_et_au_point().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Ch_front_input_P1.h
src/Kernel/Champs_dis/Ch_front_input_P1.cpp