TRUST: Neumann_paroi_flux_nul Class Reference
Neumann_paroi_flux_nul Class Reference
Classe Neumann_paroi_flux_nul
Cette condition limite flux nul a la frontiere.
#include <Neumann_paroi_flux_nul.h>
Public Member Functions
Neumann_paroi_flux_nul ()
~Neumann_paroi_flux_nul ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_paroi_flux_nul sont compatibles
avec une equation dont le domaine est la Concentration, la Fraction_massique
le Transport_Keps, le Transport_Keps_V2, le Transport_V2, le Diphasique_moyenne
ou bien indetermine.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Neumann_paroi_flux_nul & self_cast (Objet_U &)
static const
Neumann_paroi_flux_nul & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Neumann_homogene::readOn(Entree&)
Detailed Description
Classe Neumann_paroi_flux_nul
Cette condition limite flux nul a la frontiere.
Definition at line 37 of file Neumann_paroi_flux_nul.h.
Constructor & Destructor Documentation
Neumann_paroi_flux_nul::Neumann_paroi_flux_nul ()
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
Neumann_paroi_flux_nul::~Neumann_paroi_flux_nul ()
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
Member Function Documentation
int Neumann_paroi_flux_nul::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Neumann_paroi_flux_nul sont compatibles
avec une equation dont le domaine est la Concentration, la Fraction_massique
le Transport_Keps, le Transport_Keps_V2, le Transport_V2, le Diphasique_moyenne
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 89 of file Neumann_paroi_flux_nul.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Concentration      ="Concentration";
  Motcle Fraction_massique  ="Fraction_massique";
  Motcle K_Eps              ="Transport_Keps";
  Motcle K_Eps_V2           ="Transport_Keps_V2";
  Motcle K_Eps_Rea          ="Transport_Keps_Rea";
  Motcle V2                 ="Transport_V2";
  Motcle Diphasique         ="Diphasique_moyenne";
  Motcle Fraction_volumique ="Fraction_volumique";
  Motcle indetermine        ="indetermine";
  if ( (dom_app==Concentration) || (dom_app==K_Eps) || (dom_app==K_Eps_Rea) || (dom_app==K_Eps_V2) || (dom_app==V2) || (dom_app==Diphasique) || (dom_app==indetermine) || (dom_app==Fraction_massique) || (dom_app==Fraction_volumique))
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Neumann_paroi_flux_nul::cree_instance () [static]
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
int Neumann_paroi_flux_nul::duplique () const [virtual]
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
const Type_info * Neumann_paroi_flux_nul::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
const Type_info * Neumann_paroi_flux_nul::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
Sortie & Neumann_paroi_flux_nul::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 44 of file Neumann_paroi_flux_nul.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Neumann_paroi_flux_nul::readOn (Entree & s) [protected, virtual]
Simple appel a: Neumann_homogene::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 63 of file Neumann_paroi_flux_nul.cpp.
{
  return Neumann_homogene::readOn(s) ;
}
const Neumann_paroi_flux_nul & Neumann_paroi_flux_nul::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
Neumann_paroi_flux_nul & Neumann_paroi_flux_nul::self_cast (Objet_U & r) [static]
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
unsigned Neumann_paroi_flux_nul::taille_memoire () const [virtual]
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 27 of file Neumann_paroi_flux_nul.cpp.
Member Data Documentation
const Type_info Neumann_paroi_flux_nul::info_obj [static]
Reimplemented from Neumann_paroi_adiabatique.
Definition at line 40 of file Neumann_paroi_flux_nul.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Neumann_paroi_flux_nul.h
src/ThHyd/Incompressible/Cond_Lim/Neumann_paroi_flux_nul.cpp