TRUST: Solveur_Implicite_Base Class Reference
Solveur_Implicite_Base Class Reference abstract
#include <Solveur_Implicite_Base.h>
Public Member Functions
Solveur_Implicite_Base ()
~Solveur_Implicite_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual bool iterer_eqn (Equation_base &equation, const DoubleTab &inconnue, DoubleTab &result, double dt, int numero_iteration, int &ok)=0
virtual bool iterer_eqs (List_Ref_Equation_base eqs, int n, int &ok)
virtual bool est_compatible_avec_th_mono () const
virtual int nb_valeurs_temporelles_pression () const
virtual double get_default_facsec_max () const
virtual double get_default_growth_factor () const
virtual Parametre_equation & get_and_set_parametre_equation (Equation_base &eqn)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Solveur_Implicite_Base & self_cast (Objet_U &)
static const Solveur_Implicite_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Definition at line 27 of file Solveur_Implicite_Base.h.
Constructor & Destructor Documentation
Solveur_Implicite_Base()
Solveur_Implicite_Base::Solveur_Implicite_Base ()
Definition at line 19 of file Solveur_Implicite_Base.cpp.
~Solveur_Implicite_Base()
Solveur_Implicite_Base::~Solveur_Implicite_Base () override
Definition at line 19 of file Solveur_Implicite_Base.cpp.
Member Function Documentation
est_compatible_avec_th_mono()
virtual bool Solveur_Implicite_Base::est_compatible_avec_th_mono () const inline virtual
Reimplemented in ICE.
Definition at line 34 of file Solveur_Implicite_Base.h.
  {
    return 1; /* par defaut oui */
  }
get_and_set_parametre_equation()
virtual Parametre_equation & Solveur_Implicite_Base::get_and_set_parametre_equation (Equation_base & eqn) inline virtual
Reimplemented in Simpler_Base.
Definition at line 50 of file Solveur_Implicite_Base.h.
  {
    return eqn.parametre_equation(); /* par defaut : ne fait rien */
  }
References Equation_base::parametre_equation().
get_default_facsec_max()
virtual double Solveur_Implicite_Base::get_default_facsec_max () const inline virtual
Reimplemented in ICE.
Definition at line 42 of file Solveur_Implicite_Base.h.
  {
    return DMAXFLOAT; /* par defaut pas de limite : on est en implicite */
  }
References DMAXFLOAT.
get_default_growth_factor()
virtual double Solveur_Implicite_Base::get_default_growth_factor () const inline virtual
Reimplemented in SETS.
Definition at line 46 of file Solveur_Implicite_Base.h.
  {
    return DMAXFLOAT; /* par defaut pas de limite : on est en implicite */
  }
References DMAXFLOAT.
get_info()
const Type_info * Solveur_Implicite_Base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solveur_lineaire, Solveur_Lineaire_Std, Solveur_non_lineaire, SETS, ICE, Piso, Implicite, Simple, Simpler, Simpler_Base, and Solveur_U_P.
Definition at line 19 of file Solveur_Implicite_Base.cpp.
info()
const Type_info * Solveur_Implicite_Base::info () static
Definition at line 19 of file Solveur_Implicite_Base.cpp.
iterer_eqn()
virtual bool Solveur_Implicite_Base::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) pure virtual
Implemented in Solveur_Lineaire_Std, SETS, Simple, and Simpler_Base.
Referenced by Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), and Schema_Implicite_Multi_TimeStep_base::Iterer_Pb().
iterer_eqs()
bool Solveur_Implicite_Base::iterer_eqs (List_Ref_Equation_base eqs, int n, int & ok) virtual
Reimplemented in Simple.
Definition at line 31 of file Solveur_Implicite_Base.cpp.
{
  Cerr << "iterer_eqs non code" << finl;
  Process::exit();
  return false;
}
References Cerr, Process::exit(), and finl.
nb_valeurs_temporelles_pression()
virtual int Solveur_Implicite_Base::nb_valeurs_temporelles_pression () const inline virtual
Reimplemented in SETS.
Definition at line 38 of file Solveur_Implicite_Base.h.
  {
    return 1; /* par defaut 1 */
  }
printOn()
Sortie & Solveur_Implicite_Base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solveur_lineaire, Solveur_Lineaire_Std, Solveur_non_lineaire, SETS, ICE, Piso, Implicite, Simple, Simpler, Simpler_Base, and Solveur_U_P.
Definition at line 21 of file Solveur_Implicite_Base.cpp.
{
  return os;
}
Referenced by Solveur_lineaire::printOn(), and Solveur_non_lineaire::printOn().
readOn()
Entree & Solveur_Implicite_Base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solveur_lineaire, Solveur_Lineaire_Std, Solveur_non_lineaire, SETS, ICE, Piso, Implicite, Simple, Simpler, Simpler_Base, and Solveur_U_P.
Definition at line 26 of file Solveur_Implicite_Base.cpp.
{
  return is;
}
Referenced by Solveur_lineaire::readOn(), and Solveur_non_lineaire::readOn().
self_cast() [1/2]
const Solveur_Implicite_Base & Solveur_Implicite_Base::self_cast (const Objet_U & r) static
Definition at line 19 of file Solveur_Implicite_Base.cpp.
self_cast() [2/2]
Solveur_Implicite_Base & Solveur_Implicite_Base::self_cast (Objet_U & r) static
Definition at line 19 of file Solveur_Implicite_Base.cpp.
Member Data Documentation
info_obj
const Type_info Solveur_Implicite_Base::info_obj static
Definition at line 29 of file Solveur_Implicite_Base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Solveur_Implicite_Base.h
src/Kernel/Framework/Solveur_Implicite_Base.cpp