TRUST: SolveurSys Class Reference
SolveurSys Class Reference
#include <SolveurSys.h>
Public Member Functions
SolveurSys ()
~SolveurSys ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int resoudre_systeme (const Matrice_Base &matrice, const DoubleVect &secmem, DoubleVect &solution)
int resoudre_systeme (const Matrice_Base &matrice, const DoubleVect &secmem, DoubleVect &solution, int niter_max)
int supporte_matrice_morse_sym ()
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from Deriv_SolveurSys_base
~Deriv_SolveurSys_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_SolveurSys_base ()
Deriv_SolveurSys_base (const Deriv_SolveurSys_base &)
const SolveurSys_base & valeur () const
SolveurSys_base & valeur ()
const SolveurSys_base * operator-> () const
SolveurSys_base * operator-> ()
const Deriv_SolveurSys_base & operator= (const SolveurSys_base &)
const Deriv_SolveurSys_base & operator= (const Deriv_SolveurSys_base &)
operator const SolveurSys_base & () const
operator SolveurSys_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static SolveurSys & self_cast (Objet_U &)
static const SolveurSys & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_SolveurSys_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_SolveurSys_base & self_cast (Objet_U &)
static const Deriv_SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Deriv_SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Nom nom_
Detailed Description
Definition at line 32 of file SolveurSys.h.
Constructor & Destructor Documentation
SolveurSys()
SolveurSys::SolveurSys ()
Definition at line 22 of file SolveurSys.cpp.
~SolveurSys()
SolveurSys::~SolveurSys ()
Definition at line 22 of file SolveurSys.cpp.
Member Function Documentation
cree_instance()
Objet_U * SolveurSys::cree_instance () static
Definition at line 22 of file SolveurSys.cpp.
duplique()
int SolveurSys::duplique () const override virtual
Reimplemented from Deriv_SolveurSys_base.
Definition at line 22 of file SolveurSys.cpp.
get_info()
const Type_info * SolveurSys::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_SolveurSys_base.
Definition at line 22 of file SolveurSys.cpp.
info()
const Type_info * SolveurSys::info () static
Definition at line 22 of file SolveurSys.cpp.
le_nom()
const Nom & SolveurSys::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 40 of file SolveurSys.h.
{ return nom_; }
References nom_.
Referenced by resoudre_systeme().
nommer()
void SolveurSys::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 41 of file SolveurSys.h.
{ nom_ = nom; }
References nom_.
Referenced by Op_Dift_VEF_P1NCP1B_Face::associer(), Champ_P1NC_implementation::Champ_P1NC_implementation(), corriger(), Parametre_diffusion_implicite::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), PrecondSolv::readOn(), Solv_GCP_NS::readOn(), Parametre_implicite::readOn(), Solveur_Lineaire_Std::readOn(), Simpler_Base::readOn(), test_un_solveur(), and Navier_Stokes_std::uzawa().
printOn()
Sortie & SolveurSys::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Deriv_SolveurSys_base.
Definition at line 24 of file SolveurSys.cpp.
{
  return DERIV(SolveurSys_base)::printOn(s);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & SolveurSys::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Deriv_SolveurSys_base.
Definition at line 29 of file SolveurSys.cpp.
{
  Param param(que_suis_je());
  Nom solver_name;
  param.ajouter("solveur_pression",&solver_name,Param::REQUIRED);
  param.lire_sans_accolade(is);
  Nom type_solv_sys("Solv_");
  type_solv_sys+=solver_name;
  typer(type_solv_sys);
  return is >> valeur();
}
References Param::ajouter(), Param::lire_sans_accolade(), Objet_U::que_suis_je(), Param::REQUIRED, Deriv_::typer(), and Deriv_SolveurSys_base::valeur().
resoudre_systeme() [1/2]
int SolveurSys::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution)
Definition at line 45 of file SolveurSys.cpp.
{
  valeur().save_matrice_secmem_conditionnel(matrice, secmem, solution);
// Cas de solveurs emboites: n'afficher que le temps du solveur "exterieur"
// temporaire : test issu du baltik IJK_FT en commentaire car sinon erreur dans .TU avec PETSC (solveurs Ax=B => 0%)
// if (nested_solver == 0)
  statistiques().begin_count(solv_sys_counter_);
  nested_solver++;
  int nb_iter = valeur().resoudre_systeme(matrice,secmem,solution);
  nested_solver--;
// temporaire : test issu du baltik IJK_FT en commentaire car sinon erreur avec script Check_solver.sh pour test PETSC_VEF
// if (nested_solver == 0)
// {
  statistiques().end_count(solv_sys_counter_, nb_iter);
// Si limpr vaut -1, on n'imprime pas
  if (valeur().limpr()>=0)
    {
      Cout << " Convergence in " << nb_iter << " iterations for " << le_nom() << finl;
    }
  if (valeur().limpr()==1)
    {
      Cout << "clock Ax=B: " << statistiques().last_time(solv_sys_counter_) << " s for " << le_nom() << finl;
    }
// }
  return nb_iter;
}
References Statistiques::begin_count(), Cout, Statistiques::end_count(), finl, Statistiques::last_time(), le_nom(), nested_solver, SolveurSys_base::resoudre_systeme(), SolveurSys_base::save_matrice_secmem_conditionnel(), solv_sys_counter_, statistiques(), and Deriv_SolveurSys_base::valeur().
Referenced by corriger(), Navier_Stokes_std::corriger_derivee_impl(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Champ_P1NC_implementation::filtrer_resu(), Equation_base::Gradient_conjugue_diff_impl(), Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Precond_local::precond(), PrecondSolv::preconditionner_(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), Solv_Optimal::resoudre_systeme(), SolveurPP1B::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), test_un_solveur(), Op_Diff_PolyMAC_base::update_aux(), and Navier_Stokes_std::uzawa().
resoudre_systeme() [2/2]
int SolveurSys::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int niter_max)
Definition at line 81 of file SolveurSys.cpp.
{
  return valeur().resoudre_systeme(matrice,secmem,solution,niter_max);
}
References SolveurSys_base::resoudre_systeme(), and Deriv_SolveurSys_base::valeur().
self_cast() [1/2]
const SolveurSys & SolveurSys::self_cast (const Objet_U & r) static
Definition at line 22 of file SolveurSys.cpp.
self_cast() [2/2]
SolveurSys & SolveurSys::self_cast (Objet_U & r) static
Definition at line 22 of file SolveurSys.cpp.
supporte_matrice_morse_sym()
int SolveurSys::supporte_matrice_morse_sym () inline
Definition at line 39 of file SolveurSys.h.
{ return valeur().supporte_matrice_morse_sym(); }
References SolveurSys_base::supporte_matrice_morse_sym(), and Deriv_SolveurSys_base::valeur().
taille_memoire()
unsigned SolveurSys::taille_memoire () const override virtual
Reimplemented from Deriv_SolveurSys_base.
Definition at line 22 of file SolveurSys.cpp.
Member Data Documentation
info_obj
const Type_info SolveurSys::info_obj static
Definition at line 34 of file SolveurSys.h.
nom_
Nom SolveurSys::nom_ private
Definition at line 44 of file SolveurSys.h.
Referenced by le_nom(), and nommer().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/SolveurSys.h
src/Kernel/Math/SolvSys/SolveurSys.cpp