TRUST: Champ_front_tangentiel Class Reference
Champ_front_tangentiel Class Reference
class Champ_front_tangentiel
#include <Champ_front_tangentiel.h>
Public Member Functions
Champ_front_tangentiel ()
~Champ_front_tangentiel ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Pas code !!
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_tangentiel & self_cast (Objet_U &)
static const
Champ_front_tangentiel & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
double vit_tang
Detailed Description
class Champ_front_tangentiel
Definition at line 32 of file Champ_front_tangentiel.h.
Constructor & Destructor Documentation
Champ_front_tangentiel::Champ_front_tangentiel ()
Definition at line 28 of file Champ_front_tangentiel.cpp.
Champ_front_tangentiel::~Champ_front_tangentiel ()
Definition at line 28 of file Champ_front_tangentiel.cpp.
Member Function Documentation
Champ_front_base & Champ_front_tangentiel::affecter_ (const Champ_front_base & ch) [virtual]
Pas code !!
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 66 of file Champ_front_tangentiel.cpp.
{
// Cerr<<"avant de retourner"<<finl;
  return *this;
}
Objet_U * Champ_front_tangentiel::cree_instance () [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
int Champ_front_tangentiel::duplique () const [virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
const Type_info * Champ_front_tangentiel::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
const Type_info * Champ_front_tangentiel::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
Sortie & Champ_front_tangentiel::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 31 of file Champ_front_tangentiel.cpp.
References DoubleVect::size(), and Champ_front_base::valeurs().
{
// Cerr<<"printon";
  const DoubleTab& tab=valeurs();
  os << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    os << tab(0,i);
  return os;
}
Entree & Champ_front_tangentiel::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 42 of file Champ_front_tangentiel.cpp.
References Cerr, Objet_U::dimension, Process::exit(), finl, Field_base::fixer_nb_comp(), and vit_tang.
{
  Cerr<<"Reading Champ_front_tangentiel: " << finl;
  Motcle motlu;
  Motcles les_mots(1);
  les_mots[0]="vitesse_tangentielle";
  is>>motlu;
  if (motlu != les_mots[0])
    {
      Cerr << "Error while reading a Champ_front_tangentiel" << finl;
      Cerr << "We expected vitesse_tangentielle instead of " << motlu << finl;
      exit();
    }
  is >> vit_tang;
  fixer_nb_comp(dimension);
  return is;
}
const Champ_front_tangentiel & Champ_front_tangentiel::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
Champ_front_tangentiel & Champ_front_tangentiel::self_cast (Objet_U & r) [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
unsigned Champ_front_tangentiel::taille_memoire () const [virtual]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 28 of file Champ_front_tangentiel.cpp.
Member Data Documentation
const Type_info Champ_front_tangentiel::info_obj [static]
Reimplemented from Ch_front_var_instationnaire_dep.
Reimplemented in Champ_front_fonc_gradient, Champ_front_fonc_gradient_VDF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 34 of file Champ_front_tangentiel.h.
double Champ_front_tangentiel::vit_tang [protected]
Definition at line 42 of file Champ_front_tangentiel.h.
Referenced by Champ_front_tangentiel_VEF::initialiser(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_tangentiel.h
src/Kernel/Champs/Champ_front_tangentiel.cpp