TRUST: Perte_Charge_Circulaire_CoviMAC_Face Class Reference
Perte_Charge_Circulaire_CoviMAC_Face Class Reference
#include <Perte_Charge_Circulaire_CoviMAC_Face.h>
Public Member Functions
Perte_Charge_Circulaire_CoviMAC_Face ()
~Perte_Charge_Circulaire_CoviMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Circulaire_CoviMAC_Face & self_cast (Objet_U &)
static const
Perte_Charge_Circulaire_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const
Private Attributes
Champ_Don diam_hydr_ortho
Parser_U lambda
Parser_U lambda_ortho
DoubleVect v_valeur
Champ_Don v
Vecteur directeur de la perte de charge.
Detailed Description
Correspond a la somme d'une perte de charge d'intensite lambda dans la direction de v, et d'une perte de charge d'intensite lambda_ortho pour toute direction orthogonale a v.
Ou de facon equivalente a la somme d'une perte de charge isotrope d'intensite lambda_ortho, et d'une perte de charge directionnelle de vecteur v et d'intensite lamba - lambda_ortho. C'est ainsi que le calcul est code.
du/dt =
lambda_ortho(Re,x,y,z,t) * u * ||u|| / 2 Dh
(lambda(Re,x,y,z,t)-lambda_ortho(Re,x,y,z,t)) u.v * v * ||u|| / 2 Dh ||v||^2
Lecture des arguments :
Perte_Charge_Circulaire_CoviMAC_Face diametre_hydraulique { lambda expression(Re,x,y,z,t) lambda_ortho expression(Re,x,y,z,t) diam_hydr champ_don direction champ_don [sous_zone nom] }
! Perte de charge anisotrope (selon un vecteur unitaire v et dans le plan orthogonal a ce vecteur)
Definition at line 58 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
Constructor & Destructor Documentation
Perte_Charge_Circulaire_CoviMAC_Face::Perte_Charge_Circulaire_CoviMAC_Face ()
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
Perte_Charge_Circulaire_CoviMAC_Face::~Perte_Charge_Circulaire_CoviMAC_Face ()
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
Member Function Documentation
void Perte_Charge_Circulaire_CoviMAC_Face::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const [protected, virtual]
Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds Retourne le resultat calcule dans p_charge.
Avantage : bonne factorisation. Inconvenient : cout de l'appel d'une methode virtuelle a l'interieur d'une boucle.
Parameters:
u La vitesse a la face courante. 2 ou 3 composantes
pos toto
t titi
norme_u La norme de la vitesse a la face courante
dh Le diametre hydraulique a la face courante (tire de diam_hydr)
nu la viscosite cinematique
reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
coeff_ortho coefficient dans la direction orthogonale
coeff_long coefficient dans la direction longitudinale
u_l vitesse dans la direction longitudinale
v_valeur direction_longitudinale p_charge a 2 ou 3 composantes La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur) ! Appele pour chaque face par ajouter()
< Pour ne pas evaluer 2 fois le parser
Implements Perte_Charge_CoviMAC.
Definition at line 188 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
References dabs(), diam_hydr_ortho, Objet_U::dimension, Parser_U::eval(), lambda, lambda_ortho, DoubleVect::resize(), Parser_U::setVar(), v, Deriv_Champ_Don_base::valeur(), and Champ_base::valeur_a().
{
// calcul de dh_ortho
  double dh_ortho=diam_hydr_ortho->valeur_a_compo(pos,0);
// calcul de u.d/||d||
// Calcul de v et ||v||^2
  av_valeur.resize(dimension);
  v.valeur().valeur_a(pos,av_valeur);
// on norme v
  {
    double vcarre=0;
    for (int dim=0; dim<dimension; dim++)
      vcarre+=av_valeur[dim]*av_valeur[dim];
    av_valeur/=sqrt(vcarre);
  }
// Calcul de u.v/||v||
  u_l=0;
  for (int dim=0; dim<dimension; dim++)
    u_l+=u[dim]*av_valeur[dim];
  double u_ortho=sqrt(norme_u*norme_u-u_l*u_l);
  /* PL: To avoid a possible division by zero, we replace:
     double nu=norme_u*dh/reynolds;
// calcule de Re_l et Re_ortho
// Calcul du reynolds
     double Re_l=dabs(u_l)*dh/nu; */
// By:
  double Re_l=dh*dabs(u_l)/nu;
  if(Re_l<1e-10) Re_l=1e-10;
// PL: To avoid a possible division by zero, we replace:
  /* double Re_ortho=u_ortho*dh_ortho/nu; */
// By:
  double Re_ortho=dh_ortho*u_ortho/nu;
  if (Re_ortho<1e-10) Re_ortho=1e-10;
// Calcul de lambda
  lambda.setVar(0,reynolds);
  lambda.setVar(1,Re_l);
  lambda.setVar(2,t);
  lambda.setVar(3,pos[0]);
  if (dimension>1)
    lambda.setVar(4,pos[1]);
  if (dimension>2)
    lambda.setVar(5,pos[2]);
// Calcul de lambda_ortho
  lambda_ortho.setVar(0,reynolds);
  lambda_ortho.setVar(1,Re_ortho);
  lambda_ortho.setVar(2,t);
  lambda_ortho.setVar(3,pos[0]);
  if (dimension>1)
    lambda_ortho.setVar(4,pos[1]);
  if (dimension>2)
    lambda_ortho.setVar(5,pos[2]);
  double l_ortho=lambda_ortho.eval(); //!< Pour ne pas evaluer 2 fois le parser
  double l_long=lambda.eval();
  coeff_ortho=l_ortho*u_ortho/2./dh_ortho;
  coeff_long=l_long *dabs(u_l)    /2./dh    ;
}
Objet_U * Perte_Charge_Circulaire_CoviMAC_Face::cree_instance () [static]
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
int Perte_Charge_Circulaire_CoviMAC_Face::duplique () const [virtual]
Implements Perte_Charge_CoviMAC.
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
const Type_info * Perte_Charge_Circulaire_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
const Type_info * Perte_Charge_Circulaire_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
void Perte_Charge_Circulaire_CoviMAC_Face::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 64 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
References Perte_Charge_CoviMAC::diam_hydr, diam_hydr_ortho, Champ_Don::mettre_a_jour(), and v.
  {
    diam_hydr->mettre_a_jour(temps);
    diam_hydr_ortho->mettre_a_jour(temps);
    v.mettre_a_jour(temps);
  }
Sortie & Perte_Charge_Circulaire_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 40 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
References finl, and Objet_U::que_suis_je().
{
  return s << que_suis_je() << finl;
}
Entree & Perte_Charge_Circulaire_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
< lambda
< diam_hydr
< diam_hydr_ortho
< sous_zone
< direction
< lambda_ortho
< non compris
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 51 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
References Parser_U::addVar(), Cerr, Perte_Charge_CoviMAC::diam_hydr, diam_hydr_ortho, Objet_U::dimension, Process::exit(), finl, Perte_Charge_CoviMAC::implicite_, lambda, lambda_ortho, Champ_Don::nb_comp(), Perte_Charge_CoviMAC::nom_sous_zone, O_U_Ptr::non_nul(), Parser_U::parseString(), Objet_U::que_suis_je(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Perte_Charge_CoviMAC::sous_zone, and v.
{
  Cerr << "Perte_Charge_Circulaire_CoviMAC_Face::readOn " << finl;
  sous_zone=false;
  int lambda_ortho_ok=0;
  int lambda_ok=0;
// Definition des mots-cles
  Motcles les_mots(7);
  les_mots[0] = "lambda";
  les_mots[1] = "diam_hydr";
  les_mots[2] = "sous_zone";
  les_mots[3] = "direction";
  les_mots[4] = "lambda_ortho";
  les_mots[5] = "diam_hydr_ortho";
  les_mots[6] = "implicite";
// Lecture et interpretation
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  s >> motlu;
  while (motlu != accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'un " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  s >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :   //!< lambda
          {
            lambda_ok=1;
            Nom tmp;
            s >> tmp;
            Cerr << "Lecture et interpretation de la fonction " << tmp << " ... ";
            lambda.setNbVar(3+dimension);
            lambda.setString(tmp);
            lambda.addVar("Re_tot");
            lambda.addVar("Re_long");
            lambda.addVar("t");
            lambda.addVar("x");
            if (dimension>1)
              lambda.addVar("y");
            if (dimension>2)
              lambda.addVar("z");
            lambda.parseString();
            Cerr << " Ok" << finl;
            break;
          }
        case 1: //!< diam_hydr
          s >> diam_hydr;
          break;
        case 5: //!< diam_hydr_ortho
          s >> diam_hydr_ortho;
          break;
        case 2: //!< sous_zone
          s >> nom_sous_zone;
          sous_zone=true;
          break;
        case 3: //!< direction
          s >> v;
          break;
        case 4:   //!< lambda_ortho
          {
            lambda_ortho_ok=1;
            Nom tmp;
            s >> tmp;
            Cerr << "Lecture et interpretation de la fonction " << tmp << " ... ";
            lambda_ortho.setNbVar(3+dimension);
            lambda_ortho.setString(tmp);
            lambda_ortho.addVar("Re_tot");
            lambda_ortho.addVar("Re_ortho");
            lambda_ortho.addVar("t");
            lambda_ortho.addVar("x");
            if (dimension>1)
              lambda_ortho.addVar("y");
            if (dimension>2)
              lambda_ortho.addVar("z");
            lambda_ortho.parseString();
            Cerr << " Ok" << finl;
            break;
          }
        case 6:
          {
            s>>implicite_;
            break;
          }
        default : //!< non compris
          Cerr << "Mot cle \"" << motlu << "\" non compris lors de la lecture d'un "
               << que_suis_je() << finl;
          exit();
        }
      s >> motlu;
    }
// Verification de la coherence
  if (lambda_ok==0)
    {
      Cerr << "Il faut definir l'expression lamba(Re_long,Re_tot)" << finl;
      exit();
    }
  if (lambda_ortho_ok==0)
    {
      Cerr << "Il faut definir l'expression lamba_ortho(Re_ortho,Re_tot)" << finl;
      exit();
    }
  if  ((!diam_hydr.non_nul())|| (diam_hydr->nb_comp()!=1))
    {
      Cerr << "Il faut definir le champ diam_hydr a une composante" << finl;
      exit();
    }
  if ((!diam_hydr_ortho.non_nul())|| (diam_hydr_ortho->nb_comp()!=1))
    {
      Cerr << "Il faut definir le champ diam_hydr_ortho a une composante" << finl;
      exit();
    }
  if (v->nb_comp()!=dimension)
    {
      Cerr << "Il faut definir le champ direction a " << dimension << " composantes" << finl;
      exit();
    }
  Cerr << "Fin de Perte_Charge_Circulaire_CoviMAC_Face::readOn" << finl;
  return s;
}
Perte_Charge_Circulaire_CoviMAC_Face & Perte_Charge_Circulaire_CoviMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
const Perte_Charge_Circulaire_CoviMAC_Face & Perte_Charge_Circulaire_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
unsigned Perte_Charge_Circulaire_CoviMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 37 of file Perte_Charge_Circulaire_CoviMAC_Face.cpp.
Member Data Documentation
Champ_Don Perte_Charge_Circulaire_CoviMAC_Face::diam_hydr_ortho [private]
Definition at line 79 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
Referenced by coeffs_perte_charge(), mettre_a_jour(), and readOn().
const Type_info Perte_Charge_Circulaire_CoviMAC_Face::info_obj [static]
Reimplemented from Perte_Charge_CoviMAC.
Definition at line 60 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
Parser_U Perte_Charge_Circulaire_CoviMAC_Face::lambda [mutable, private]
Definition at line 80 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
Referenced by coeffs_perte_charge(), and readOn().
Parser_U Perte_Charge_Circulaire_CoviMAC_Face::lambda_ortho [mutable, private]
Definition at line 81 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
Referenced by coeffs_perte_charge(), and readOn().
Champ_Don Perte_Charge_Circulaire_CoviMAC_Face::v [private]
Vecteur directeur de la perte de charge.
Definition at line 83 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
Referenced by coeffs_perte_charge(), mettre_a_jour(), and readOn().
DoubleVect Perte_Charge_Circulaire_CoviMAC_Face::v_valeur [mutable, private]
Definition at line 82 of file Perte_Charge_Circulaire_CoviMAC_Face.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Perte_Charge_Circulaire_CoviMAC_Face.h
src/CoviMAC/Sources/Perte_Charge_Circulaire_CoviMAC_Face.cpp