TRUST: Op_Dift_VDF_Face Class Reference
Op_Dift_VDF_Face Class Reference
#include <Op_Dift_VDF_Face.h>
Public Member Functions
~Op_Dift_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Dift_VDF_Face ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Eval_VDF_Face2 & get_eval_face ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Dift_VDF_Face & self_cast (Objet_U &)
static const Op_Dift_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
Definition at line 40 of file Op_Dift_VDF_Face.h.
Constructor & Destructor Documentation
Op_Dift_VDF_Face::~Op_Dift_VDF_Face ()
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
Op_Dift_VDF_Face::Op_Dift_VDF_Face ()
Definition at line 66 of file Op_Dift_VDF_Face.cpp.
                                   :
  Op_Dift_VDF_Face_base(It_VDF_Face(Eval_Dift_VDF_const_Face)())
{
}
Member Function Documentation
void Op_Dift_VDF_Face::associer_diffusivite_turbulente (const Champ_Fonc & visc_turb)
Reimplemented from Op_Diff_Turbulent_base.
Definition at line 40 of file Op_Dift_VDF_Face.cpp.
References Eval_Dift_VDF_const::associer_diff_turb(), Iterateur_VDF::evaluateur(), and Op_Diff_VDF_base::iter.
Referenced by completer().
{
  Op_Diff_Turbulent_base::associer_diffusivite_turbulente(visc_turb);
  Evaluateur_VDF& eval = iter.evaluateur();
  Eval_Dift_VDF_const_Face& eval_diff_turb = dynamic_cast<Eval_Dift_VDF_const_Face&> (eval);
  eval_diff_turb.associer_diff_turb(visc_turb);
}
void Op_Dift_VDF_Face::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_VDF_base.
Definition at line 48 of file Op_Dift_VDF_Face.cpp.
References associer_diffusivite_turbulente(), Eval_Dift_VDF_const_Face::associer_modele_turbulence(), MorEqn::equation(), Iterateur_VDF::evaluateur(), Equation_base::get_modele(), Op_Diff_VDF_base::iter, ref_cast, TURBULENCE, Ref_Objet_U::valeur(), and Mod_turb_hyd_base::viscosite_turbulente().
{
// Cerr << "Op_Dift_VDF_Face::completer() " << finl;
  Op_Dift_VDF_base::completer();
  const RefObjU& modele_turbulence = equation().get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  const Champ_Fonc& visc_turb = mod_turb.viscosite_turbulente();
  associer_diffusivite_turbulente(visc_turb);
  Evaluateur_VDF& eval = iter.evaluateur();
  Eval_Dift_VDF_const_Face& eval_diff_turb = dynamic_cast<Eval_Dift_VDF_const_Face&> (eval);
  eval_diff_turb.associer_modele_turbulence(mod_turb);
}
Objet_U * Op_Dift_VDF_Face::cree_instance () [static]
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
int Op_Dift_VDF_Face::duplique () const [virtual]
Implements Op_Dift_VDF_Face_base.
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
Eval_VDF_Face2 & Op_Dift_VDF_Face::get_eval_face () [inline, virtual]
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 52 of file Op_Dift_VDF_Face.h.
References Iterateur_VDF::evaluateur(), and Op_Diff_VDF_base::iter.
{
  Eval_Dift_VDF_const_Face& eval_diff = dynamic_cast<Eval_Dift_VDF_const_Face&> (iter.evaluateur());
  return eval_diff;
}
const Type_info * Op_Dift_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
const Type_info * Op_Dift_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
Sortie & Op_Dift_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 30 of file Op_Dift_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
Entree & Op_Dift_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 35 of file Op_Dift_VDF_Face.cpp.
{
  return s ;
}
const Op_Dift_VDF_Face & Op_Dift_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
Op_Dift_VDF_Face & Op_Dift_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
unsigned Op_Dift_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Op_Dift_VDF_Face.cpp.
Member Data Documentation
const Type_info Op_Dift_VDF_Face::info_obj [static]
Reimplemented from Op_Dift_VDF_Face_base.
Definition at line 42 of file Op_Dift_VDF_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_Face.h
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_Face.cpp