TRUST: Zone_Cl_VEFP1B Class Reference
Zone_Cl_VEFP1B Class Reference
#include <Zone_Cl_VEFP1B.h>
Public Member Functions
Zone_Cl_VEFP1B ()
~Zone_Cl_VEFP1B ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void remplir_volumes_entrelaces_Cl (const Zone_VEF &) override
appele par completer() : remplissage de type_elem_Cl_ et
volumes_entrelaces_Cl_
void imposer_cond_lim (Champ_Inc &, double) override
Public Member Functions inherited from Zone_Cl_VEF
Zone_Cl_VEF ()
~Zone_Cl_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_VEF &)
etape de discretisation : dimensionnement des tableaux
void completer (const Zone_dis &) override
remplissage des tableaux
int initialiser (double temps) override
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void imposer_cond_lim (Champ_Inc &, double) override
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
virtual void remplir_volumes_entrelaces_Cl (const Zone_VEF &)
appele par completer() : remplissage de type_elem_Cl_ et
volumes_entrelaces_Cl_
void remplir_normales_facettes_Cl (const Zone_VEF &)
appele par completer() : remplissage de normales_facettes_Cl_
et vecteur_face_caette_Cl_
CHANGER LE NOM
void remplir_vecteur_face_facette_Cl (const Zone_VEF &)
DoubleVect & volumes_entrelaces_Cl ()
const DoubleVect & volumes_entrelaces_Cl () const
const double & volumes_entrelaces_Cl (int) const
double & volumes_entrelaces_Cl (int)
DoubleTab & normales_facettes_Cl ()
const DoubleTab & normales_facettes_Cl () const
const double & normales_facettes_Cl (int, int, int) const
double & normales_facettes_Cl (int, int, int)
DoubleTab & vecteur_face_facette_Cl ()
const DoubleTab & vecteur_face_facette_Cl () const
int type_elem_Cl (int) const
int nb_faces_sortie_libre () const
Zone_VEF & zone_VEF ()
const Zone_VEF & zone_VEF () const
int nb_bord_periodicite () const
Public Member Functions inherited from Zone_Cl_dis_base
Zone_Cl_dis_base ()
~Zone_Cl_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Cond_lim & les_conditions_limites (int) const
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
int nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de toutes les conditions
aux limites.
virtual void mettre_a_jour_ss_pas_dt (double temps)
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
void completer ()
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
int contient_Cl (const Nom &)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Zone_dis & zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
const Zone_dis & zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Zone & zone ()
const Zone & zone () const
virtual int calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour les problemes couples thermiques.
virtual void imposer_cond_lim (Champ_Inc &, double)=0
int nb_faces_Cl () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
void Gpoint (double t1, double t2)
void set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
int avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
int reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void associer_inconnue (const Champ_Inc &)
virtual const Champ_Inc & inconnue () const
virtual Champ_Inc & inconnue ()
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_VEFP1B & self_cast (Objet_U &)
static const Zone_Cl_VEFP1B & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Cl_VEF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_VEF & self_cast (Objet_U &)
static const Zone_Cl_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Cl_dis_base
static const Type_info * info ()
static Zone_Cl_dis_base & self_cast (Objet_U &)
static const Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_Cl_VEF
static const Type_info info_obj
Static Public Attributes inherited from Zone_Cl_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Protected Member Functions inherited from Zone_Cl_VEF
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
void remplir_type_elem_Cl (const Zone_VEF &)
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
virtual void completer (const Zone_dis &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Zone_Cl_VEF
DoubleVect volumes_entrelaces_Cl_
DoubleTab normales_facettes_Cl_
DoubleTab vecteur_face_facette_Cl_
IntVect type_elem_Cl_
int modif_perio_fait_
Protected Attributes inherited from Zone_Cl_dis_base
Nom nom_
Conds_lim les_conditions_limites_
Ref_Champ_Inc mon_inconnue
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 22 of file Zone_Cl_VEFP1B.h.
Constructor & Destructor Documentation
Zone_Cl_VEFP1B()
Zone_Cl_VEFP1B::Zone_Cl_VEFP1B ()
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
~Zone_Cl_VEFP1B()
Zone_Cl_VEFP1B::~Zone_Cl_VEFP1B ()
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
Member Function Documentation
cree_instance()
Objet_U * Zone_Cl_VEFP1B::cree_instance () static
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
duplique()
int Zone_Cl_VEFP1B::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
get_info()
const Type_info * Zone_Cl_VEFP1B::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
imposer_cond_lim()
void Zone_Cl_VEFP1B::imposer_cond_lim (Champ_Inc & ch, double temps) override virtual
Implements Zone_Cl_dis_base.
Definition at line 37 of file Zone_Cl_VEFP1B.cpp.
{
  Zone_Cl_VEF::imposer_cond_lim(ch,temps);
// dans le cas Navier stokes et si la condition est forte en pression aux sommets on impose la valeur aux sommets
  if (sub_type(Navier_Stokes_std,ch.valeur().equation()))
    {
      const Zone_VEF_PreP1b& zone_vef=ref_cast(Zone_VEF_PreP1b,equation().zone_dis().valeur());
      if ((zone_vef.get_cl_pression_sommet_faible()==0) && (zone_vef.get_alphaS()))
        {
          int nps=zone_vef.numero_premier_sommet();
          DoubleTab& pression=ref_cast(Navier_Stokes_std,ch->equation()).pression().valeurs();
          int nbsom_tot = zone_vef.nb_som_tot();
          ArrOfDouble surf_loc(nbsom_tot);
          int nb_cond_lims = nb_cond_lim();
// On boucle une premiere fois pour mettre a zero la pression aux sommets
          for(int i=0; i<nb_cond_lims; i++)
            {
              const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
              if (sub_type(Neumann_sortie_libre,la_cl))
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  const IntTab& faces = zone_vef.face_sommets();
                  int nbsf = faces.dimension(1);
                  int num2 = le_bord.nb_faces_tot();
                  for (int ind_face=0; ind_face<num2; ind_face++)
                    {
                      int face = le_bord.num_face(ind_face);
                      for(int som=0; som<nbsf; som++)
{
                          int som_glob = faces(face,som);
                          pression(nps+som_glob) = 0;
                        }
                    }
                }
            }
// On boucle une deuxieme fois pour ajouter la contribution de chaque face
          for(int i=0; i<nb_cond_lims; i++)
            {
              const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
              if (sub_type(Neumann_sortie_libre,la_cl))
                {
                  const Neumann_sortie_libre& la_sortie_libre = ref_cast(Neumann_sortie_libre, la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  const IntTab& faces = zone_vef.face_sommets();
                  int nbsf = faces.dimension(1);
                  int num2 = le_bord.nb_faces_tot();
                  for (int ind_face=0; ind_face<num2; ind_face++)
                    {
                      int face = le_bord.num_face(ind_face);
                      double P_imp = la_sortie_libre.flux_impose(ind_face);
                      double face_surf = zone_vef.face_surfaces(face);
                      for(int som=0; som<nbsf; som++)
{
                          int som_glob = faces(face,som);
                          pression(nps+som_glob) += P_imp*face_surf;
                          surf_loc[som_glob] += face_surf;
                        }
                    }
                }
            }
// On boucle une troisieme fois pour diviser par la surface
          for(int i=0; i<nb_cond_lims; i++)
            {
              const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
              if (sub_type(Neumann_sortie_libre,la_cl))
                {
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  const IntTab& faces = zone_vef.face_sommets();
                  int nbsf = faces.dimension(1);
                  int num2 = le_bord.nb_faces_tot();
                  for (int ind_face=0; ind_face<num2; ind_face++)
                    {
                      int face = le_bord.num_face(ind_face);
                      for(int som=0; som<nbsf; som++)
{
                          int som_glob = faces(face,som);
                          double& surf = surf_loc[som_glob];
                          if (surf>0)
{
                              pression(nps+som_glob) /= surf;
                              surf = -1;
                            }
                        }
                    }
                }
            }
          pression.echange_espace_virtuel();
          Debog::verifier("pression dans Zone_Cl_VEFP1B::imposer_cond_lim",pression);
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Neumann::flux_impose(), Cond_lim_base::frontiere_dis(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_cl_pression_sommet_faible(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_som_tot(), Front_VF::num_face(), Zone_VEF_PreP1b::numero_premier_sommet(), ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), valeur(), Debog::verifier(), and Zone_Cl_dis_base::zone_dis().
info()
const Type_info * Zone_Cl_VEFP1B::info () static
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
printOn()
Sortie & Zone_Cl_VEFP1B::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 27 of file Zone_Cl_VEFP1B.cpp.
{
  return Zone_Cl_VEF::printOn(s) ;
}
References Zone_Cl_VEF::printOn().
readOn()
Entree & Zone_Cl_VEFP1B::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 32 of file Zone_Cl_VEFP1B.cpp.
{
  return Zone_Cl_VEF::readOn(is)  ;
}
References Zone_Cl_VEF::readOn().
remplir_volumes_entrelaces_Cl()
void Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl (const Zone_VEF & la_zone_VEF) override virtual
appele par completer() : remplissage de type_elem_Cl_ et
volumes_entrelaces_Cl_
Reimplemented from Zone_Cl_VEF.
Definition at line 131 of file Zone_Cl_VEFP1B.cpp.
{
  Cerr << "On passe dans Zone_Cl_VEFP1B::remplir_volumes_entrelaces" << finl;
// On rappelle la methode de la classe mere pour etendre les volumes de controles sur les faces non standard.
// Uniquement en conduction pour l'instant ou en P0 seul
  const Zone_VEF_PreP1b& z=ref_cast(Zone_VEF_PreP1b, la_zone_VEF);
  if ((z.get_modif_div_face_dirichlet())||sub_type(Conduction, equation()) || (z.get_alphaE() && !z.get_alphaS() && !z.get_alphaA()))
    return Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(la_zone_VEF);
  else
    {
      const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
// Initialisation du tableau volumes_entrelaces_Cl
// a priori les faces non standard ne sont pas touchees par les C.L
      for (int i=0; i<la_zone_VEF.nb_faces_non_std(); i++)
        volumes_entrelaces_Cl(i) = volumes_entrelaces(i);
      Cerr << "Fin creation esp. virtuel volumes_entrelaces_Cl_" << finl;
    }
}
References Cerr, MorEqn::equation(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_modif_div_face_dirichlet(), Zone_VEF::nb_faces_non_std(), ref_cast, Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), sub_type, Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
self_cast() [1/2]
const Zone_Cl_VEFP1B & Zone_Cl_VEFP1B::self_cast (const Objet_U & r) static
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
self_cast() [2/2]
Zone_Cl_VEFP1B & Zone_Cl_VEFP1B::self_cast (Objet_U & r) static
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
taille_memoire()
unsigned Zone_Cl_VEFP1B::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Zone_Cl_VEFP1B.cpp.
Member Data Documentation
info_obj
const Type_info Zone_Cl_VEFP1B::info_obj static
Definition at line 24 of file Zone_Cl_VEFP1B.h.
The documentation for this class was generated from the following files:
src/P1NCP1B/Zones/Zone_Cl_VEFP1B.h
src/P1NCP1B/Zones/Zone_Cl_VEFP1B.cpp