TRUST: Convection_Diffusion_Espece_Fluide_Dilatable_base Class Reference
Convection_Diffusion_Espece_Fluide_Dilatable_base Class Reference
classe Convection_Diffusion_Espece_Fluide_Dilatable_base
Cas particulier de Convection_Diffusion_std pour un fluide dilatable
quand le scalaire subissant le transport est la fraction massique
#include <Convection_Diffusion_Espece_Fluide_Dilatable_base.h>
Public Member Functions
Convection_Diffusion_Espece_Fluide_Dilatable_base ()
~Convection_Diffusion_Espece_Fluide_Dilatable_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
void calculer_div_u_ou_div_rhou (DoubleTab &res) const
virtual int sauvegarder (Sortie &) const
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
virtual int reprendre (Entree &)
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual const Motcle & domaine_application () const
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)=0
virtual const Champ_base & diffusivite_pour_pas_de_temps ()=0
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)=0
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
bool is_thermal ()
bool is_generic ()
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Convection_Diffusion_Espece_Fluide_Dilatable_base & self_cast (Objet_U &)
static const
Convection_Diffusion_Espece_Fluide_Dilatable_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Equation_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
Detailed Description
classe Convection_Diffusion_Espece_Fluide_Dilatable_base
Cas particulier de Convection_Diffusion_std pour un fluide dilatable
quand le scalaire subissant le transport est la fraction massique
Definition at line 40 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.h.
Constructor & Destructor Documentation
Convection_Diffusion_Espece_Fluide_Dilatable_base::Convection_Diffusion_Espece_Fluide_Dilatable_base ()
Definition at line 28 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
Convection_Diffusion_Espece_Fluide_Dilatable_base::~Convection_Diffusion_Espece_Fluide_Dilatable_base ()
Definition at line 28 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
Member Function Documentation
virtual void Convection_Diffusion_Espece_Fluide_Dilatable_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) [pure virtual]
Reimplemented from Equation_base.
Implemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
void Convection_Diffusion_Espece_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou (DoubleTab & res) const [virtual]
Implements Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 75 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
References Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
{
  Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(Div,*this);
}
virtual DoubleTab& Convection_Diffusion_Espece_Fluide_Dilatable_base::derivee_en_temps_inco (DoubleTab & derivee) [pure virtual]
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
< Change secmem for some schemes (eg: Adams_Bashforth)
< Add specific term for an equation (eg: -gradP for Navier Stokes)
< M-1 * secmem
< Solve specific implicit term for an equation (eg: pressure for Navier Stokes)
Reimplemented from Equation_base.
Implemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
virtual const Champ_base& Convection_Diffusion_Espece_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps () [pure virtual]
Reimplemented from Convection_Diffusion_std.
Implemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Multi_WC.
Referenced by Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard().
void Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser () [virtual]
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
Reimplemented from Equation_base.
Definition at line 62 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
References Cerr, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), finl, Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch, Schema_Temps_base::nb_valeurs_temporelles(), ref_cast, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Equation_base::zone_dis().
{
  int nb_valeurs_temp = schema_temps().nb_valeurs_temporelles();
  double temps = schema_temps().temps_courant();
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  Cerr << "Massic fraction equation discretization ..." << finl;
// On utilise temperature pour la directive car discretisation identique
  dis.discretiser_champ("temperature",zone_dis(),"fraction_massique","sans_dimension",
                        1 /* nb_composantes */,nb_valeurs_temp,temps,l_inco_ch);
  Equation_base::discretiser();
  Cerr << "Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser() ok" << finl;
}
const Motcle & Convection_Diffusion_Espece_Fluide_Dilatable_base::domaine_application () const [virtual]
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns:
Motcle&
Signification: le nom du domaine d'application de l'equation
Contraintes: toujours egal a "Thermique"
Reimplemented from Equation_base.
Definition at line 108 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
{
  static Motcle domaine ="Fraction_massique";
  return domaine;
}
virtual int Convection_Diffusion_Espece_Fluide_Dilatable_base::duplique () const [pure virtual]
Implements Convection_Diffusion_Fluide_Dilatable_base.
Implemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
const Type_info * Convection_Diffusion_Espece_Fluide_Dilatable_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
const Type_info * Convection_Diffusion_Espece_Fluide_Dilatable_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
bool Convection_Diffusion_Espece_Fluide_Dilatable_base::is_generic () [inline, virtual]
Implements Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 59 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.h.
{ return true; }
bool Convection_Diffusion_Espece_Fluide_Dilatable_base::is_thermal () [inline, virtual]
Implements Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 58 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.h.
{ return false; }
int Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul (void) [virtual]
Tout ce qui ne depend pas des autres problemes eventuels.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base.
Definition at line 40 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
References Zone_Cl_dis::les_conditions_limites(), Zone_Cl_dis_base::les_conditions_limites(), ref_cast, Cond_lim::set_modifier_val_imp(), vect_impl::size(), sub_type, valeur(), Deriv_Zone_Cl_dis_base::valeur(), Convection_Diffusion_Fluide_Dilatable_base::zcl_modif_, and Equation_base::zone_Cl_dis().
{
  Convection_Diffusion_Fluide_Dilatable_base::preparer_calcul();
// remplissage de la zone cl modifiee avec 1 partout au bord...
  zcl_modif_=(zone_Cl_dis());
  Conds_lim& condlims=zcl_modif_.valeur().les_conditions_limites();
  int nb=condlims.size();
  for (int i=0; i<nb; i++)
    {
// pour chaque condlim on recupere le champ_front et on met 1
// meme si la cond lim est un flux (dans ce cas la convection restera nullle.)
      DoubleTab& T=condlims[i].valeur().champ_front().valeurs();
      T=1.;
      if (sub_type(Neumann_sortie_libre,condlims[i].valeur()))
        ref_cast(Neumann_sortie_libre,condlims[i].valeur()).tab_ext()=1;
    }
  zcl_modif_.les_conditions_limites().set_modifier_val_imp(0);
  return 1;
}
Sortie & Convection_Diffusion_Espece_Fluide_Dilatable_base::printOn (Sortie & is) const [protected, virtual]
Simple appel a Equation_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 30 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
{
  return Convection_Diffusion_Fluide_Dilatable_base::printOn(is);
}
Entree & Convection_Diffusion_Espece_Fluide_Dilatable_base::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 35 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
{
  return Convection_Diffusion_Fluide_Dilatable_base::readOn(is);
}
int Convection_Diffusion_Espece_Fluide_Dilatable_base::reprendre (Entree & fich) [virtual]
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_WC.
Definition at line 87 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
{
  Convection_Diffusion_Fluide_Dilatable_base::reprendre(is);
  return 1;
}
int Convection_Diffusion_Espece_Fluide_Dilatable_base::sauvegarder (Sortie & os) const [virtual]
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Returns:
int
Signification: le code de retour de Champ_Inc::sauvegarder()
Contraintes:
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_WC.
Definition at line 80 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
{
  int bytes=0;
  bytes += Equation_base::sauvegarder(os);
  return bytes;
}
Convection_Diffusion_Espece_Fluide_Dilatable_base & Convection_Diffusion_Espece_Fluide_Dilatable_base::self_cast (Objet_U & r) [static]
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
const Convection_Diffusion_Espece_Fluide_Dilatable_base & Convection_Diffusion_Espece_Fluide_Dilatable_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 28 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp.
Member Data Documentation
const Type_info Convection_Diffusion_Espece_Fluide_Dilatable_base::info_obj [static]
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_base, Convection_Diffusion_Espece_Multi_base, Convection_Diffusion_Espece_Binaire_QC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_WC, and Convection_Diffusion_Espece_Multi_WC.
Definition at line 42 of file Convection_Diffusion_Espece_Fluide_Dilatable_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Espece_Fluide_Dilatable_base.h
src/ThHyd/Dilatable/Common/Equations/Convection_Diffusion_Espece_Fluide_Dilatable_base.cpp