TRUST: Decouper_multi Class Reference
Decouper_multi Class Reference
Interprete Decouper_multi. Decoupage simultane de plusieurs domaine
avec renseignement des sommets connectes par des Raccords (pour extension
des espaces virtuels)
#include <Decouper_multi.h>
Public Member Functions
Decouper_multi ()
~Decouper_multi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &is) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Decouper_multi & self_cast (Objet_U &)
static const Decouper_multi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
std::map< std::string, Decouper > decoupeurs
double tolerance = 1e-8
Detailed Description
Interprete Decouper_multi. Decoupage simultane de plusieurs domaine
avec renseignement des sommets connectes par des Raccords (pour extension
des espaces virtuels)
Definition at line 29 of file Decouper_multi.h.
Constructor & Destructor Documentation
Decouper_multi()
Decouper_multi::Decouper_multi ()
Definition at line 28 of file Decouper_multi.cpp.
~Decouper_multi()
Decouper_multi::~Decouper_multi ()
Definition at line 28 of file Decouper_multi.cpp.
Member Function Documentation
cree_instance()
Objet_U * Decouper_multi::cree_instance () static
Definition at line 28 of file Decouper_multi.cpp.
duplique()
int Decouper_multi::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Decouper_multi.cpp.
get_info()
const Type_info * Decouper_multi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 28 of file Decouper_multi.cpp.
info()
const Type_info * Decouper_multi::info () static
Definition at line 28 of file Decouper_multi.cpp.
interpreter()
Entree & Decouper_multi::interpreter (Entree & is) override virtual
< * heavier lifting *
Reimplemented from Interprete.
Definition at line 67 of file Decouper_multi.cpp.
{
  int i, j, k, l, d, s, ns, count = 0;
// lecture des domaines et des raccords
  Param param(que_suis_je());
  param.ajouter_non_std("domaine",(this),Param::REQUIRED);
  param.ajouter("tolerance", &tolerance);
  param.lire_avec_accolades_depuis(is);
  /* partition des domaines */
  std::vector<IntVect> v_proc; //partition de chaque domaine
  std::vector<Decouper*> v_dec; //decoupeurs
  std::vector<const Domaine*> v_dom; //domaines
  std::vector<Static_Int_Lists> v_se; //connectivites
  std::vector<MCAuto<DataArrayDouble>> v_da; //DataArrayDouble de coordonnes
  std::vector<const DataArrayDouble*> v_pda; //et des pointeurs (ppur Aggregate)
  std::vector<int> off = { 0 }; //offset des sommets de chaque domaine dans le tableau aggrege
  for (auto &&n_d : decoupeurs)
    {
      const Domaine& dom = n_d.second.ref_domaine.valeur();
      const DoubleTab& coord = dom.coord_sommets();
      v_proc.push_back(IntVect()), v_dec.push_back(&n_d.second), v_dom.push_back(&dom);
      v_se.push_back(Static_Int_Lists()), v_da.push_back(DataArrayDouble::New());
      v_da.back()->useExternalArrayWithRWAccess((double *) coord.addr(), coord.dimension(0), coord.dimension(1));
      v_pda.push_back(v_da.back()), off.push_back(off.back() + coord.dimension(0));
      Partitionneur_base& partitionneur = n_d.second.deriv_partitionneur.valeur();
      partitionneur.declarer_bords_periodiques(n_d.second.liste_bords_periodiques);
      partitionneur.construire_partition(v_proc.back(), n_d.second.nb_parts_tot);
      construire_connectivite_som_elem(dom.nb_som(), dom.zone(0).les_elems(), v_se.back(), 1);
    }
#ifdef MEDCOUPLING_
  /* concatenation des coordonnees et recherche de sommets coincidents */
  Cerr << "Decouper_multi: searching for coinciding vertices ... ";
  MCAuto<DataArrayDouble> da(DataArrayDouble::Aggregate(v_pda)); //tous les sommets!
  DataArrayInt* S_i = NULL, *S = NULL; //groupes de sommets coincidants : S([S_i(i), S_i(i + 1)[)
  da->findCommonTuples(tolerance, -1, S, S_i); //!< * heavy lifting *
  /* pour chaque groupe de sommets, recherche de tous les procs les touchant et ajout a chaque sommet des procs qui ne le possedent pas encore */
  std::vector<std::map<int, std::set<int>>> v_sp(v_dec.size()); //v_sp[d][s] = { processeurs supplementaires ayant besoin du sommet s du domaine d }
  std::vector<std::set<int>> procs; //processeurs possedant chaque sommet du groupe...
  std::set<int> u_procs; //et leur union
  std::vector<std::array<int, 2>> v_ds; //liste (domaine, sommet)
  for (i = 0; i + 1 < S_i->getNumberOfTuples(); i++)
    if ((ns = S_i->getIJ(i + 1, 0) - S_i->getIJ(i, 0)) > 1) //pas besoin de traiter les sommets seuls
      {
        for (count++, procs.resize(ns), v_ds.resize(ns), j = S_i->getIJ(i, 0), k = 0; j < S_i->getIJ(i + 1, 0); j++, k++)
          {
            for (s = S->getIJ(j, 0), d = 0; s >= off[d + 1]; ) d++; //d : indice du domaine contenant s
            s -= off[d], v_ds[k] = {{ d, s }}; //stockage du couple (d, s)
            for (procs[k].clear(), l = 0; l < v_se[d].get_list_size(s); l++) procs[k].insert(v_proc[d](v_se[d](s, l))); //processeurs connectes
          }
        for (u_procs.clear(), k = 0; k < ns; k++)
          for (auto &&pr : procs[k]) u_procs.insert(pr); //union
        for (k = 0; k < ns; k++)  /* on ajoute a chaque sommet les procs auxquels il n'est pas deja connecte */
          if (procs[k].size() < u_procs.size())
            {
              std::set<int>& dest = v_sp[v_ds[k][0]][v_ds[k][1]]; //ou on doit inserer
              std::set_difference(u_procs.begin(), u_procs.end(), procs[k].begin(), procs[k].end(), std::inserter(dest, dest.end()));
            }
      }
  S_i->decrRef(), S->decrRef();
  Cerr << count << " sommets trouves!" << finl;
#else
  Process::exit("Decouper_multi requires MEDCoupling!");
#endif
  /* ecriture des domaines avec les sommets raccord qu'on a trouves */
  for (d = 0; d < (int) v_dec.size(); d++)
    {
      Static_Int_Lists som_raccord;
      ArrOfInt sizes(v_dom[d]->nb_som()); //tailles des listes par sommet
      sizes = 0;
      for (auto && s_p : v_sp[d]) sizes[s_p.first] = s_p.second.size();
      som_raccord.set_list_sizes(sizes);
      for (auto && s_p : v_sp[d])
        {
          i = 0;
          for (auto &&p : s_p.second) som_raccord.set_value(s_p.first, i, p), i++;
        }
      v_dec[d]->ecrire(v_proc[d], &som_raccord); //!< * heavier lifting *
    }
  return is;
}
References TRUSTArray< _TYPE_ >::addr(), Param::ajouter(), Param::ajouter_non_std(), Cerr, construire_connectivite_som_elem(), Partitionneur_base::construire_partition(), Domaine::coord_sommets(), Partitionneur_base::declarer_bords_periodiques(), decoupeurs, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, Zone::les_elems(), Param::lire_avec_accolades_depuis(), Domaine::nb_som(), Objet_U::que_suis_je(), Param::REQUIRED, Static_Int_Lists::set_list_sizes(), Static_Int_Lists::set_value(), tolerance, and Domaine::zone().
lire_motcle_non_standard()
int Decouper_multi::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 52 of file Decouper_multi.cpp.
{
  if (mot=="domaine") //parametres de decoupage d'un domaine
    {
      Decouper decoup;
      decoup.lire(is);
      if (decoupeurs.count(decoup.nom_domaine.getString())) //decoupeur deja lu
        Process::exit(Nom("Decouper_multi: domain ") + decoup.nom_domaine + "already read!");
      else decoupeurs[decoup.nom_domaine.getString()] = decoup; //sinon, on l'ajoute
    }
  else return -1;
  return 0;
}
References decoupeurs, Process::exit(), Nom::getString(), Decouper::lire(), and Decouper::nom_domaine.
printOn()
Sortie & Decouper_multi::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 40 of file Decouper_multi.cpp.
{
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Decouper_multi::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 46 of file Decouper_multi.cpp.
{
  exit();
  return is;
}
References Process::exit().
self_cast() [1/2]
const Decouper_multi & Decouper_multi::self_cast (const Objet_U & r) static
Definition at line 28 of file Decouper_multi.cpp.
self_cast() [2/2]
Decouper_multi & Decouper_multi::self_cast (Objet_U & r) static
Definition at line 28 of file Decouper_multi.cpp.
taille_memoire()
unsigned Decouper_multi::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Decouper_multi.cpp.
Member Data Documentation
decoupeurs
std::map<std::string, Decouper> Decouper_multi::decoupeurs private
Definition at line 38 of file Decouper_multi.h.
Referenced by interpreter(), and lire_motcle_non_standard().
info_obj
const Type_info Decouper_multi::info_obj static
Definition at line 31 of file Decouper_multi.h.
tolerance
double Decouper_multi::tolerance = 1e-8 private
Definition at line 39 of file Decouper_multi.h.
Referenced by interpreter().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Decouper_multi.h
src/Kernel/Geometrie/Decoupeur/Decouper_multi.cpp