TRUST: Force_Centrifuge_VDF_Face_Axi Class Reference
Force_Centrifuge_VDF_Face_Axi Class Reference
class Force_Centrifuge_VDF_Face_Axi
Cette classe represente la force centrifuge
a prendre en compte dans les equations de Navier-Stokes
en coordonnees cylindriques pour une dicretisation VDF
#include <Force_Centrifuge_VDF_Face_Axi.h>
Public Member Functions
Force_Centrifuge_VDF_Face_Axi ()
~Force_Centrifuge_VDF_Face_Axi ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Force_Centrifuge_VDF_Face_Axi & self_cast (Objet_U &)
static const Force_Centrifuge_VDF_Face_Axi & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Ref_Champ_Face la_vitesse
IntTab elem_faces
IntVect orientation
DoubleTab xp
DoubleTab xv
DoubleVect volume_entrelaces
DoubleVect porosite_surf
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Force_Centrifuge_VDF_Face_Axi
Cette classe represente la force centrifuge
a prendre en compte dans les equations de Navier-Stokes
en coordonnees cylindriques pour une dicretisation VDF
Definition at line 46 of file Force_Centrifuge_VDF_Face_Axi.h.
Constructor & Destructor Documentation
Force_Centrifuge_VDF_Face_Axi()
Force_Centrifuge_VDF_Face_Axi::Force_Centrifuge_VDF_Face_Axi ()
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
~Force_Centrifuge_VDF_Face_Axi()
Force_Centrifuge_VDF_Face_Axi::~Force_Centrifuge_VDF_Face_Axi ()
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
Member Function Documentation
ajouter_blocs()
void Force_Centrifuge_VDF_Face_Axi::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Definition at line 75 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  const Zone_VDF& zvdf = la_zone_VDF.valeur();
  const Zone_Cl_VDF& zclvdf = la_zone_Cl_VDF.valeur();
  const DoubleTab& vitesse = la_vitesse->valeurs();
  int nb_elem = zvdf.nb_elem();
  int nb_faces = zvdf.nb_faces();
  DoubleTrav vit_sum(nb_faces);
  vit_sum =0;
  double U,V,coef;
  int fac0,fac1,fac2,fac3;
// Boucle sur les elements pour calculer vit_sum
  for (int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      fac0 = elem_faces(num_elem,0);
      fac1 = elem_faces(num_elem,1);
      fac2 = elem_faces(num_elem,dimension);
      fac3 = elem_faces(num_elem,1+dimension);
      V = 0.5*(vitesse(fac1)+vitesse(fac3));
      U = 0.5*(vitesse(fac0)+vitesse(fac2));
      vit_sum(fac0) += 0.5*(V*V);
      vit_sum(fac2) += 0.5*(V*V);
      vit_sum(fac1) += 0.5*(U*V);
      vit_sum(fac3) += 0.5*(U*V);
    }
// Boucle sur les conditions limites pour traiter les faces de bord
  int ndeb,nfin,ori,num_face;
  for (int n_bord=0; n_bord<zvdf.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
// Si face de Dirichlet ou de Symetrie on ne fait rien
// Si face de Neumann on calcule la contribution au terme source
      const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (num_face=ndeb; num_face<nfin; num_face++)
            {
              ori = orientation(num_face);
              if (ori == 0)
                {
                  coef = volume_entrelaces(num_face)*porosite_surf(num_face)/xv(num_face,0);
                  secmem(num_face) += 0.5*(vit_sum(num_face)*coef);
                }
              else if (ori == 1)
                {
                  coef = volume_entrelaces(num_face)*porosite_surf(num_face)/xv(num_face,0);
                  secmem(num_face) -= 0.5*(vit_sum(num_face)*coef);
                }
            }
        }
      else if (sub_type(Symetrie,la_cl.valeur()))
        ;
      else if ( (sub_type(Dirichlet,la_cl.valeur()))
                ||
                (sub_type(Dirichlet_homogene,la_cl.valeur()))
              )
        {
// do nothing
          ;
        }
    }
// Boucle sur les faces internes
  ndeb = zvdf.premiere_face_int();
  nfin = zvdf.nb_faces();
  for (num_face=ndeb; num_face<nfin; num_face++)
    {
      ori = orientation(num_face);
      if (ori == 0)
        {
          coef = volume_entrelaces(num_face)*porosite_surf(num_face)/xv(num_face,0);
          secmem(num_face) += 0.5*(vit_sum(num_face)*coef);
        }
      else if (ori == 1)
        {
          coef = volume_entrelaces(num_face)*porosite_surf(num_face)/xv(num_face,0);
          secmem(num_face) -= 0.5*(vit_sum(num_face)*coef);
        }
    }
}
References Objet_U::dimension, elem_faces, Cond_lim::frontiere_dis(), la_vitesse, la_zone_Cl_VDF, la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), orientation, porosite_surf, Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Inc_base::valeurs(), volume_entrelaces, and xv.
associer_pb()
void Force_Centrifuge_VDF_Face_Axi::associer_pb (const Probleme_base &) override virtual
Implements Source_base.
Definition at line 55 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  Cerr << "Force_Centrifuge_VDF_Face_Axi::associer_pb" << finl;
}
References Cerr, and finl.
associer_zones()
void Force_Centrifuge_VDF_Face_Axi::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 60 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF, zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
  la_zone_VDF = zvdf;
  la_zone_Cl_VDF = zclvdf;
  elem_faces.ref(zvdf.elem_faces());
  orientation.ref(zvdf.orientation());
  xp.ref(zvdf.xp());
  xv.ref(zvdf.xv());
  volume_entrelaces.ref(zvdf.volumes_entrelaces());
  porosite_surf.ref(zvdf.porosite_face());
}
References Zone_VF::elem_faces(), elem_faces, la_zone_Cl_VDF, la_zone_VDF, orientation, Zone_VDF::orientation(), Zone_VF::porosite_face(), porosite_surf, TRUSTTab< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::ref(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), volume_entrelaces, Zone_VF::volumes_entrelaces(), Zone_VF::xp(), xp, Zone_VF::xv(), and xv.
calculer()
DoubleTab & Force_Centrifuge_VDF_Face_Axi::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 174 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  resu=0;
  ajouter(resu);
  return resu;
}
References Source_base::ajouter().
completer()
void Force_Centrifuge_VDF_Face_Axi::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 181 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  Source_base::completer();
  la_vitesse = ref_cast(Champ_Face,equation().inconnue().valeur());
}
References Source_base::completer(), MorEqn::equation(), la_vitesse, ref_cast, and valeur().
cree_instance()
Objet_U * Force_Centrifuge_VDF_Face_Axi::cree_instance () static
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
dimensionner_blocs()
void Force_Centrifuge_VDF_Face_Axi::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 61 of file Force_Centrifuge_VDF_Face_Axi.h.
{}
duplique()
int Force_Centrifuge_VDF_Face_Axi::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
get_info()
const Type_info * Force_Centrifuge_VDF_Face_Axi::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
has_interface_blocs()
int Force_Centrifuge_VDF_Face_Axi::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 63 of file Force_Centrifuge_VDF_Face_Axi.h.
  {
    return 1;
  };
info()
const Type_info * Force_Centrifuge_VDF_Face_Axi::info () static
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
mettre_a_jour()
void Force_Centrifuge_VDF_Face_Axi::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 56 of file Force_Centrifuge_VDF_Face_Axi.h.
  {
    ;
  }
printOn()
Sortie & Force_Centrifuge_VDF_Face_Axi::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 33 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Force_Centrifuge_VDF_Face_Axi::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 41 of file Force_Centrifuge_VDF_Face_Axi.cpp.
{
  return s ;
}
self_cast() [1/2]
const Force_Centrifuge_VDF_Face_Axi & Force_Centrifuge_VDF_Face_Axi::self_cast (const Objet_U & r) static
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
self_cast() [2/2]
Force_Centrifuge_VDF_Face_Axi & Force_Centrifuge_VDF_Face_Axi::self_cast (Objet_U & r) static
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
taille_memoire()
unsigned Force_Centrifuge_VDF_Face_Axi::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Force_Centrifuge_VDF_Face_Axi.cpp.
Member Data Documentation
elem_faces
IntTab Force_Centrifuge_VDF_Face_Axi::elem_faces protected
Definition at line 74 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
info_obj
const Type_info Force_Centrifuge_VDF_Face_Axi::info_obj static
Definition at line 49 of file Force_Centrifuge_VDF_Face_Axi.h.
la_vitesse
Ref_Champ_Face Force_Centrifuge_VDF_Face_Axi::la_vitesse protected
Definition at line 72 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and completer().
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Force_Centrifuge_VDF_Face_Axi::la_zone_Cl_VDF protected
Definition at line 71 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
la_zone_VDF
Ref_Zone_VDF Force_Centrifuge_VDF_Face_Axi::la_zone_VDF protected
Definition at line 70 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
orientation
IntVect Force_Centrifuge_VDF_Face_Axi::orientation protected
Definition at line 75 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
porosite_surf
DoubleVect Force_Centrifuge_VDF_Face_Axi::porosite_surf protected
Definition at line 79 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
volume_entrelaces
DoubleVect Force_Centrifuge_VDF_Face_Axi::volume_entrelaces protected
Definition at line 78 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
xp
DoubleTab Force_Centrifuge_VDF_Face_Axi::xp protected
Definition at line 76 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by associer_zones().
xv
DoubleTab Force_Centrifuge_VDF_Face_Axi::xv protected
Definition at line 77 of file Force_Centrifuge_VDF_Face_Axi.h.
Referenced by ajouter_blocs(), and associer_zones().
The documentation for this class was generated from the following files:
src/VDF/Axi/Sources/Force_Centrifuge_VDF_Face_Axi.h
src/VDF/Axi/Sources/Force_Centrifuge_VDF_Face_Axi.cpp