TRUST: MD_Vector_std Class Reference
MD_Vector_std Class Reference
C'est le plus simple des descripteurs, utilise pour les tableaux de valeurs aux sommets, elements,
faces, aretes, faces de bord, etc...
Il supporte la notion d'items "communs" (sommets du maillage partages entre plusieurs processeurs)
et d'items "distants" et "virtuels" (sommets, elements dans l'epaisseur de joint).
Voir aussi MD_Vector_composite (descripteur compose d'une reunion de plusieurs descripteurs, pour le P1Bulle
par exemple)
#include <MD_Vector_std.h>
Public Member Functions
~MD_Vector_std ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
MD_Vector_std ()
MD_Vector_std (int nb_items_tot, int nb_items_reels, const ArrOfInt &pe_voisins, const ArrsOfInt &items_to_send, const ArrsOfInt &items_to_recv, const ArrsOfInt &blocs_to_recv)
Constructeur.
Si nb_items_reels >= 0, items_to_compute contiendra un bloc avec les items reels,
sinon, items_to_compute prendra tous les items (jusqu'a nb_items_tot).
Parametre: nb_items_tot
Signification: valeur que prendra nb_items_tot_ (doit etre >= 0)
Parametre: nb_items_reels
Signification: valeur que prendra nb_items_reels_ (doit etre >= -1,
-1 signifie qu'il n'y a pas d'items "reels" groupes au debut du tableau
Parametre: pe_voisins
Signification: liste des processeurs voisins, classes dans l'ordre croissant<br>(les tableaux ArrsOfInt doivent avoir la meme taille).
Cette liste n'est pas reprise integralement: on retire les processeurs
pour lesquels toutes les trois listes d'items sont vides.
Parametre: items_to_send
Signification: pour chaque pe_voisin, liste des items a envoyer (communs et virtuels).
count_items_to_send_to_items_ est calcule par une communication a partir de items_to_recv.
Parametre: items_to_recv
Signification: liste d'items individuels a recevoir des differents procs
(souvent des items communs mais ce n'est pas obligatoire, ex front-tracking)
Parametre: blocs_to_recv
Signification: liste de blocs d'items a recevoir (voir MD_Vector_std::blocs_to_recv_)
(souvent les items virtuels...)
void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &sc, DoubleVect &v) const override
void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &sc, IntVect &v) const override
void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &sc, DoubleVect &v) const override
void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &sc, IntVect &v) const override
void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &sc, DoubleVect &v) const override
void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &sc, IntVect &v) const override
Public Member Functions inherited from MD_Vector_base2
~MD_Vector_base2 () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
MD_Vector_base2 ()
int get_nb_items_reels () const override
int get_nb_items_tot () const override
const ArrOfInt & get_items_to_compute () const override
const ArrOfInt & get_items_to_sum () const override
int nb_items_seq_tot () const override
int nb_items_seq_local () const override
Public Member Functions inherited from MD_Vector_base
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
MD_Vector_base ()
MD_Vector_base (const MD_Vector_base &)
~MD_Vector_base () override
virtual int get_nb_items_reels () const =0
virtual int get_nb_items_tot () const =0
virtual void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual const ArrOfInt & get_items_to_compute () const =0
virtual const ArrOfInt & get_items_to_sum () const =0
virtual int nb_items_seq_tot () const =0
virtual int nb_items_seq_local () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static MD_Vector_std & self_cast (Objet_U &)
static const MD_Vector_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from MD_Vector_base2
static const Type_info * info ()
static MD_Vector_base2 & self_cast (Objet_U &)
static const MD_Vector_base2 & self_cast (const Objet_U &)
static void append_item_to_blocs (ArrOfInt &blocs, int item)
methode outil pour ajouter un item a un tableau du genre "blocs" contenant
des series de blocs... alonge le bloc precedent ou commence un nouveau bloc si l'item n'est pas contigu avec le bloc precedent.
Static Public Member Functions inherited from MD_Vector_base
static const Type_info * info ()
static MD_Vector_base & self_cast (Objet_U &)
static const MD_Vector_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
ArrOfInt pe_voisins_
Static_Int_Lists items_to_send_
ArrOfInt nb_items_to_items_
Static_Int_Lists items_to_recv_
Static_Int_Lists blocs_to_recv_
ArrOfInt blocs_items_count_
Public Attributes inherited from MD_Vector_base2
int nb_items_tot_
int nb_items_reels_
int nb_items_seq_tot_
int nb_items_seq_local_
ArrOfInt blocs_items_to_sum_
ArrOfInt blocs_items_to_compute_
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from MD_Vector_base2
static const Type_info info_obj
Static Public Attributes inherited from MD_Vector_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::dump_vector_with_md()
Entree & readOn (Entree &) override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::restore_vector_with_md()
Sortie & printOn (Sortie &x) const override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::dump_vector_with_md()
Entree & readOn (Entree &) override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::restore_vector_with_md()
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
template<typename _TYPE_ >
void initialize_comm_template (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, TRUSTVect< _TYPE_ > &) const
template<typename _TYPE_ >
void prepare_send_data_template (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, TRUSTVect< _TYPE_ > &) const
This is the first part of the echange_espace_virtuel() process.
We take the data that has to be sent to other processors in "vect" and put it in appropriate send buffers in "buffers". The data taken depends on "opt".
Preconditon: The buffers must have been initialized to the appropriate size and neighbour processors.
template<typename _TYPE_ >
void process_recv_data_template (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, TRUSTVect< _TYPE_ > &) const
Detailed Description
C'est le plus simple des descripteurs, utilise pour les tableaux de valeurs aux sommets, elements,
faces, aretes, faces de bord, etc...
Il supporte la notion d'items "communs" (sommets du maillage partages entre plusieurs processeurs)
et d'items "distants" et "virtuels" (sommets, elements dans l'epaisseur de joint).
Voir aussi MD_Vector_composite (descripteur compose d'une reunion de plusieurs descripteurs, pour le P1Bulle
par exemple)
Definition at line 35 of file MD_Vector_std.h.
Constructor & Destructor Documentation
~MD_Vector_std()
MD_Vector_std::~MD_Vector_std ()
Definition at line 19 of file MD_Vector_std.cpp.
MD_Vector_std() [1/2]
MD_Vector_std::MD_Vector_std ()
Definition at line 21 of file MD_Vector_std.cpp.
{
  nb_items_seq_tot_ = -1;
  nb_items_seq_local_ = -1;
  nb_items_tot_ = -1;
  nb_items_reels_ = -1;
}
References MD_Vector_base2::nb_items_reels_, MD_Vector_base2::nb_items_seq_local_, MD_Vector_base2::nb_items_seq_tot_, and MD_Vector_base2::nb_items_tot_.
MD_Vector_std() [2/2]
MD_Vector_std::MD_Vector_std (int nb_items_tot, int nb_items_reels, const ArrOfInt & pe_voisins, const ArrsOfInt & items_to_send, const ArrsOfInt & items_to_recv, const ArrsOfInt & blocs_to_recv)
Constructeur.
Si nb_items_reels >= 0, items_to_compute contiendra un bloc avec les items reels,
sinon, items_to_compute prendra tous les items (jusqu'a nb_items_tot).
Parametre: nb_items_tot
Signification: valeur que prendra nb_items_tot_ (doit etre >= 0)
Parametre: nb_items_reels
Signification: valeur que prendra nb_items_reels_ (doit etre >= -1,
-1 signifie qu'il n'y a pas d'items "reels" groupes au debut du tableau
Parametre: pe_voisins
Signification: liste des processeurs voisins, classes dans l'ordre croissant<br>(les tableaux ArrsOfInt doivent avoir la meme taille).
Cette liste n'est pas reprise integralement: on retire les processeurs
pour lesquels toutes les trois listes d'items sont vides.
Parametre: items_to_send
Signification: pour chaque pe_voisin, liste des items a envoyer (communs et virtuels).
count_items_to_send_to_items_ est calcule par une communication a partir de items_to_recv.
Parametre: items_to_recv
Signification: liste d'items individuels a recevoir des differents procs
(souvent des items communs mais ce n'est pas obligatoire, ex front-tracking)
Parametre: blocs_to_recv
Signification: liste de blocs d'items a recevoir (voir MD_Vector_std::blocs_to_recv_)
(souvent les items virtuels...)
< sinon, c'est qu'on recoit deux fois le meme items
< sinon, c'est qu'on recoit deux fois le meme items
Definition at line 51 of file MD_Vector_std.cpp.
{
  assert(nb_items_tot >= 0);
  assert(nb_items_reels >= -1 && nb_items_reels <= nb_items_tot);
  nb_items_tot_ = nb_items_tot;
  nb_items_reels_ = nb_items_reels;
  const int nb_voisins = pe_voisins.size_array();
  assert(items_to_send.size() == nb_voisins);
  assert(items_to_recv.size() == nb_voisins);
  assert(blocs_to_recv.size() == nb_voisins);
// selection: liste des indices des pe a conserver dans pe_voisins
// (procs avec qui on echange effectivement des donnees)
  ArrOfInt tmp, selection;
  tmp.set_smart_resize(1);
  selection.set_smart_resize(1);
  int i;
  for (i = 0; i < nb_voisins; i++)
    if (items_to_send[i].size_array() > 0 || items_to_recv[i].size_array() > 0 || blocs_to_recv[i].size_array() > 0)
      {
        tmp.append_array(pe_voisins[i]);
        selection.append_array(i);
      }
  const int nb_voisins2 = tmp.size_array();
// ** pe_voisins_ **
  pe_voisins_ = tmp;
  {
    ArrsOfInt tmpbis(nb_voisins2);
    for (i = 0; i < nb_voisins2; i++)
      tmpbis[i] = items_to_send[selection[i]];
    items_to_send_.set(tmpbis);
    for (i = 0; i < nb_voisins2; i++)
      tmpbis[i] = items_to_recv[selection[i]];
    items_to_recv_.set(tmpbis);
    for (i = 0; i < nb_voisins2; i++)
      tmpbis[i] = blocs_to_recv[selection[i]];
    blocs_to_recv_.set(tmpbis);
  }
// Calcul de nb_items_to_items_
  {
    nb_items_to_items_.resize_array(nb_voisins2, Array_base::NOCOPY_NOINIT);
    tmp.resize_array(nproc(), Array_base::NOCOPY_NOINIT);
    tmp = 0;
    for (i = 0; i < nb_voisins2; i++)
      tmp[pe_voisins_[i]] = items_to_recv[selection[i]].size_array();
    ;
    envoyer_all_to_all(tmp, tmp);
    for (i = 0; i < nb_voisins2; i++)
      {
        int n = tmp[pe_voisins_[i]];
        assert(n <= items_to_send_.get_list_size(i));
        nb_items_to_items_[i] = n;
      }
  }
// Calcul de blocs_items_count_
  {
    blocs_items_count_.resize_array(nb_voisins2, Array_base::NOCOPY_NOINIT);
    for (i = 0; i < nb_voisins2; i++)
      {
        const int nblocs = blocs_to_recv_.get_list_size(i) / 2;
        int count = 0;
        for (int j = 0; j < nblocs; j++)
          {
            int deb = blocs_to_recv_(i, j * 2);
            int fin = blocs_to_recv_(i, j * 2 + 1);
            assert(deb >= 0 && fin > deb && fin <= nb_items_tot_);
            count += fin - deb;
          }
        blocs_items_count_[i] = count;
      }
  }
// Calcul des blocs d'items sequentiels (items non recus d'un autre proc)
  tmp.resize_array(nb_items_tot, Array_base::NOCOPY_NOINIT);
  {
// Marquage des items recus a zero
    tmp = 1;
    const ArrOfInt& items = items_to_recv_.get_data();
    int n = items.size_array();
    for (i = 0; i < n; i++)
      {
        assert(tmp[items[i]] == 1); //!< sinon, c'est qu'on recoit deux fois le meme items
        tmp[items[i]] = 0;
      }
    const ArrOfInt& items2 = blocs_to_recv_.get_data();
    assert(items2.size_array() % 2 == 0);
    n = items2.size_array() / 2;
    for (i = 0; i < n; i++)
      {
        const int start = items2[i * 2];
        const int end = items2[i * 2 + 1];
        for (int j = start; j < end; j++)
          {
            assert(tmp[j] == 1); //!< sinon, c'est qu'on recoit deux fois le meme items
            tmp[j] = 0;
          }
      }
// Construction d'une liste de blocs d'items sequentiels (ceux qui sont restes a 1)
    ArrOfInt blocs;
    blocs.set_smart_resize(1);
    int nb_seq = 0;
    for (i = 0; i < nb_items_tot; i++)
      {
        if (tmp[i])
          {
            if (nb_items_reels >= 0 && i >= nb_items_reels)
              {
// On a un item non recu parmi les items virtuels !
                Cerr << "Error in MD_Vector_std::MD_Vector_std(...) [pe " << me() << "]\n "
                     "an item i(" << i << ") > nb_items_reels(" << nb_items_reels << ") is not received from any other processor" << finl;
                Process::exit();
              }
            append_item_to_blocs(blocs, i);
            nb_seq++;
          }
      }
    blocs_items_to_sum_ = blocs;
    nb_items_seq_local_ = nb_seq;
    nb_items_seq_tot_ = mp_sum(nb_seq);
  }
// Bloc items to compute:
// Par defaut: un seul bloc
  if (nb_items_reels_ >= 0)
    {
// Les operateurs sur les tableaux calculent tous les items reels
      blocs_items_to_compute_.resize(2, Array_base::NOCOPY_NOINIT);
      blocs_items_to_compute_[0] = 0;
      blocs_items_to_compute_[1] = nb_items_reels_;
    }
  else
    {
// Les operateurs sur les tableaux calculent tout
      blocs_items_to_compute_.resize(2, Array_base::NOCOPY_NOINIT);
      blocs_items_to_compute_[0] = 0;
      blocs_items_to_compute_[1] = nb_items_tot_;
    }
}
References TRUSTArray< _TYPE_ >::append_array(), MD_Vector_base2::append_item_to_blocs(), blocs_items_count_, MD_Vector_base2::blocs_items_to_compute_, MD_Vector_base2::blocs_items_to_sum_, blocs_to_recv_, Cerr, envoyer_all_to_all(), Process::exit(), finl, Static_Int_Lists::get_data(), Static_Int_Lists::get_list_size(), items_to_recv_, items_to_send_, Process::me(), Process::mp_sum(), MD_Vector_base2::nb_items_reels_, MD_Vector_base2::nb_items_seq_local_, MD_Vector_base2::nb_items_seq_tot_, nb_items_to_items_, MD_Vector_base2::nb_items_tot_, Array_base::NOCOPY_NOINIT, Process::nproc(), pe_voisins_, TRUSTArray< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Static_Int_Lists::set(), TRUSTArray< _TYPE_ >::set_smart_resize(), vect_impl::size(), and TRUSTArray< _TYPE_ >::size_array().
Member Function Documentation
cree_instance()
Objet_U * MD_Vector_std::cree_instance () static
Definition at line 19 of file MD_Vector_std.cpp.
duplique()
int MD_Vector_std::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file MD_Vector_std.cpp.
get_info()
const Type_info * MD_Vector_std::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from MD_Vector_base2.
Definition at line 19 of file MD_Vector_std.cpp.
info()
const Type_info * MD_Vector_std::info () static
Definition at line 19 of file MD_Vector_std.cpp.
initialize_comm() [1/2]
void MD_Vector_std::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & sc, DoubleVect & v) const inline override virtual
Implements MD_Vector_base.
Definition at line 43 of file MD_Vector_std.h.
{ initialize_comm_template<double>(opt,sc,v); }
Referenced by MD_Vector_composite::initialize_comm().
initialize_comm() [2/2]
void MD_Vector_std::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & sc, IntVect & v) const inline override virtual
Implements MD_Vector_base.
Definition at line 44 of file MD_Vector_std.h.
{ initialize_comm_template<int>(opt,sc,v); }
initialize_comm_template()
template<typename _TYPE_ > void MD_Vector_std::initialize_comm_template (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm_, TRUSTVect< _TYPE_ > & v) const private
Definition at line 82 of file MD_Vector_std.h.
{
  const int reverse = (opt.get_op() != Echange_EV_Options::SYNC);
  const int have_items_to_recv = (items_to_recv_.get_data().size_array() > 0);
  const int have_blocs_to_recv = (blocs_to_recv_.get_data().size_array() > 0);
  const int nprocs = pe_voisins_.size_array();
  for (int i = 0; i < nprocs; i++)
    {
      const int pe = pe_voisins_[i];
      int sz1 = items_to_send_.get_list_size(i), sz2 = 0;
      if (have_items_to_recv) sz2 = items_to_recv_.get_list_size(i);
      if (have_blocs_to_recv) sz2 += blocs_items_count_[i];
      if (reverse)
        {
// Schema a l'envers: lecture dans les items to recv, ecriture dans les items to send
          int tmp = sz1;
          sz1 = sz2;
          sz2 = tmp;
        }
      comm_.add_send_area_template < _TYPE_ > (pe, sz1 * v.line_size());
      comm_.add_recv_area_template < _TYPE_ > (pe, sz2 * v.line_size());
    }
}
References Schema_Comm_Vecteurs::add_recv_area_template(), Schema_Comm_Vecteurs::add_send_area_template(), blocs_items_count_, blocs_to_recv_, Static_Int_Lists::get_data(), Static_Int_Lists::get_list_size(), Echange_EV_Options::get_op(), items_to_recv_, items_to_send_, TRUSTVect< _TYPE_ >::line_size(), pe_voisins_, TRUSTArray< _TYPE_ >::size_array(), and Echange_EV_Options::SYNC.
prepare_send_data() [1/2]
void MD_Vector_std::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & sc, DoubleVect & v) const inline override virtual
Implements MD_Vector_base.
Definition at line 45 of file MD_Vector_std.h.
{ prepare_send_data_template<double>(opt,sc,v); }
Referenced by MD_Vector_composite::prepare_send_data().
prepare_send_data() [2/2]
void MD_Vector_std::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & sc, IntVect & v) const inline override virtual
Implements MD_Vector_base.
Definition at line 46 of file MD_Vector_std.h.
{ prepare_send_data_template<int>(opt,sc,v); }
prepare_send_data_template()
template<typename _TYPE_ > void MD_Vector_std::prepare_send_data_template (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & buffers, TRUSTVect< _TYPE_ > & vect) const private
This is the first part of the echange_espace_virtuel() process.
We take the data that has to be sent to other processors in "vect" and put it in appropriate send buffers in "buffers". The data taken depends on "opt".
Preconditon: The buffers must have been initialized to the appropriate size and neighbour processors.
Definition at line 111 of file MD_Vector_std.h.
{
  const int line_size = vect.line_size();
  switch(opt.get_op())
    {
    case Echange_EV_Options::SYNC:
      read_from_vect_items(line_size, pe_voisins_, items_to_send_, vect, buffers);
      break;
    case Echange_EV_Options::SUM:
    case Echange_EV_Options::MAX:
    case Echange_EV_Options::MINCOL1:
      if (items_to_recv_.get_data().size_array() > 0)
        read_from_vect_items(line_size, pe_voisins_, items_to_recv_, vect, buffers);
      if (blocs_to_recv_.get_data().size_array() > 0)
        read_from_vect_blocs(line_size, pe_voisins_, blocs_to_recv_, blocs_items_count_, vect, buffers);
      break;
    default:
      Cerr << "Error in MD_Vector_std.tpp prepare_send_data_template : operation not implemented" << finl;
      Process::exit();
    }
}
References blocs_items_count_, blocs_to_recv_, Cerr, Process::exit(), finl, Static_Int_Lists::get_data(), Echange_EV_Options::get_op(), items_to_recv_, items_to_send_, TRUSTVect< _TYPE_ >::line_size(), Echange_EV_Options::MAX, Echange_EV_Options::MINCOL1, pe_voisins_, read_from_vect_blocs(), read_from_vect_items(), TRUSTArray< _TYPE_ >::size_array(), Echange_EV_Options::SUM, and Echange_EV_Options::SYNC.
printOn()
Sortie & MD_Vector_std::printOn (Sortie & x) const override protected virtual
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::dump_vector_with_md()
Reimplemented from MD_Vector_base2.
Definition at line 224 of file MD_Vector_std.cpp.
{
  MD_Vector_base2::printOn(os);
  os << "{" << finl;
  os << "pe_voisins" << space << pe_voisins_ << finl;
  os << "items_to_send_index" << space << items_to_send_.get_index() << finl;
  os << "items_to_send_data" << space << items_to_send_.get_data() << finl;
  os << "nb_items_to_items" << space << nb_items_to_items_ << finl;
  os << "items_to_recv_index" << space << items_to_recv_.get_index();
  os << "items_to_recv_data" << space << items_to_recv_.get_data();
  os << "blocs_to_recv_index" << space << blocs_to_recv_.get_index() << finl;
  os << "blocs_to_recv_data" << space << blocs_to_recv_.get_data();
  os << "blocs_items_count" << space << blocs_items_count_ << finl;
  os << "}" << finl;
  return os;
}
References blocs_items_count_, blocs_to_recv_, finl, Static_Int_Lists::get_data(), Static_Int_Lists::get_index(), items_to_recv_, items_to_send_, nb_items_to_items_, pe_voisins_, MD_Vector_base2::printOn(), and space.
process_recv_data() [1/2]
void MD_Vector_std::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & sc, DoubleVect & v) const inline override virtual
Implements MD_Vector_base.
Definition at line 47 of file MD_Vector_std.h.
{ process_recv_data_template<double>(opt,sc,v); }
Referenced by MD_Vector_composite::process_recv_data().
process_recv_data() [2/2]
void MD_Vector_std::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & sc, IntVect & v) const inline override virtual
Implements MD_Vector_base.
Definition at line 48 of file MD_Vector_std.h.
{ process_recv_data_template<int>(opt,sc,v); }
process_recv_data_template()
template<typename _TYPE_ > void MD_Vector_std::process_recv_data_template (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & buffers, TRUSTVect< _TYPE_ > & vect) const private
Definition at line 134 of file MD_Vector_std.h.
{
  const int line_size = vect.line_size();
  switch(opt.get_op())
    {
    case Echange_EV_Options::SYNC:
      if (items_to_recv_.get_data().size_array() > 0)
        write_to_vect_items(line_size, pe_voisins_, items_to_recv_, vect, buffers);
      if (blocs_to_recv_.get_data().size_array() > 0)
        write_to_vect_blocs(line_size, pe_voisins_, blocs_to_recv_, blocs_items_count_, vect, buffers);
      break;
    case Echange_EV_Options::SUM:
      add_to_vect_items(line_size, pe_voisins_, items_to_send_, vect, buffers);
      break;
    case Echange_EV_Options::MAX:
      max_to_vect_items(line_size, pe_voisins_, items_to_send_, vect, buffers);
      break;
    case Echange_EV_Options::MINCOL1:
      mincol1_to_vect_items(line_size, pe_voisins_, items_to_send_, vect, buffers);
      break;
    default:
      Cerr << "Error in MD_Vector_std.tpp process_recv_data_template : operation not implemented" << finl;
      Process::exit();
    }
}
References add_to_vect_items(), blocs_items_count_, blocs_to_recv_, Cerr, Process::exit(), finl, Static_Int_Lists::get_data(), Echange_EV_Options::get_op(), items_to_recv_, items_to_send_, TRUSTVect< _TYPE_ >::line_size(), Echange_EV_Options::MAX, max_to_vect_items(), Echange_EV_Options::MINCOL1, mincol1_to_vect_items(), pe_voisins_, TRUSTArray< _TYPE_ >::size_array(), Echange_EV_Options::SUM, Echange_EV_Options::SYNC, write_to_vect_blocs(), and write_to_vect_items().
readOn()
Entree & MD_Vector_std::readOn (Entree & is) override protected virtual
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::restore_vector_with_md()
Reimplemented from MD_Vector_base2.
Definition at line 198 of file MD_Vector_std.cpp.
{
  MD_Vector_base2::readOn(is);
  Param p(que_suis_je());
  ArrOfInt items_send_index, items_send_data, items_index, items_data, blocs_index, blocs_data;
  p.ajouter("pe_voisins", &pe_voisins_);
  p.ajouter("items_to_send_index", &items_send_index);
  p.ajouter("items_to_send_data", &items_send_data);
  p.ajouter("nb_items_to_items", &nb_items_to_items_);
  p.ajouter("items_to_recv_index", &items_index);
  p.ajouter("items_to_recv_data", &items_data);
  p.ajouter("blocs_to_recv_index", &blocs_index);
  p.ajouter("blocs_to_recv_data", &blocs_data);
  p.ajouter("blocs_items_count", &blocs_items_count_);
  p.lire_avec_accolades(is);
  if (items_send_data.size_array())
    items_to_send_.set_index_data(items_send_index, items_send_data);
  if (items_data.size_array())
    items_to_recv_.set_index_data(items_index, items_data);
  if (blocs_data.size_array())
    blocs_to_recv_.set_index_data(blocs_index, blocs_data);
  return is;
}
References Param::ajouter(), blocs_items_count_, blocs_to_recv_, items_to_recv_, items_to_send_, Param::lire_avec_accolades(), nb_items_to_items_, pe_voisins_, Objet_U::que_suis_je(), MD_Vector_base2::readOn(), Static_Int_Lists::set_index_data(), and TRUSTArray< _TYPE_ >::size_array().
self_cast() [1/2]
const MD_Vector_std & MD_Vector_std::self_cast (const Objet_U & r) static
Definition at line 19 of file MD_Vector_std.cpp.
self_cast() [2/2]
MD_Vector_std & MD_Vector_std::self_cast (Objet_U & r) static
Definition at line 19 of file MD_Vector_std.cpp.
taille_memoire()
unsigned MD_Vector_std::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file MD_Vector_std.cpp.
Member Data Documentation
blocs_items_count_
ArrOfInt MD_Vector_std::blocs_items_count_
Definition at line 66 of file MD_Vector_std.h.
Referenced by append_global_md(), creer_md_vect_renum(), initialize_comm_template(), MD_Vector_std(), prepare_send_data_template(), printOn(), process_recv_data_template(), and readOn().
blocs_to_recv_
Static_Int_Lists MD_Vector_std::blocs_to_recv_
Definition at line 64 of file MD_Vector_std.h.
Referenced by append_global_md(), creer_md_vect_renum(), MD_Vector_tools::extend(), initialize_comm_template(), MD_Vector_std(), prepare_send_data_template(), printOn(), process_recv_data_template(), and readOn().
info_obj
const Type_info MD_Vector_std::info_obj static
Definition at line 37 of file MD_Vector_std.h.
items_to_recv_
Static_Int_Lists MD_Vector_std::items_to_recv_
Definition at line 60 of file MD_Vector_std.h.
Referenced by append_global_md(), creer_md_vect_renum(), MD_Vector_tools::extend(), initialize_comm_template(), MD_Vector_std(), prepare_send_data_template(), printOn(), process_recv_data_template(), and readOn().
items_to_send_
Static_Int_Lists MD_Vector_std::items_to_send_
Definition at line 56 of file MD_Vector_std.h.
Referenced by append_global_md(), creer_md_vect_renum(), MD_Vector_tools::extend(), initialize_comm_template(), MD_Vector_std(), prepare_send_data_template(), printOn(), process_recv_data_template(), and readOn().
nb_items_to_items_
ArrOfInt MD_Vector_std::nb_items_to_items_
Definition at line 58 of file MD_Vector_std.h.
Referenced by append_global_md(), creer_md_vect_renum(), MD_Vector_std(), printOn(), and readOn().
pe_voisins_
ArrOfInt MD_Vector_std::pe_voisins_
Definition at line 51 of file MD_Vector_std.h.
Referenced by append_global_md(), creer_md_vect_renum(), MD_Vector_tools::extend(), initialize_comm_template(), MD_Vector_std(), prepare_send_data_template(), printOn(), process_recv_data_template(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Math/MD_Vector_std.h
src/Kernel/Math/MD_Vector_std.cpp