TRUST: Op_Grad_VDF_Face Class Reference
Op_Grad_VDF_Face Class Reference
class Op_Grad_VDF_Face
Cette classe represente l'operateur de gradient
La discretisation est VDF. On calcule le gradient d'un champ_P0_VDF (la pression)
#include <Op_Grad_VDF_Face.h>
Public Member Functions
Op_Grad_VDF_Face ()
~Op_Grad_VDF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
Public Member Functions inherited from Op_Grad_VDF_Face_base
Op_Grad_VDF_Face_base ()
~Op_Grad_VDF_Face_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int has_interface_blocs () const override
Zone_VDF & zone_VDF ()
const Zone_VDF & zone_VDF () const
Zone_Cl_VDF & zone_Cl_VDF ()
const Zone_Cl_VDF & zone_Cl_VDF () const
int & face_voisins_ (int i, int j)
const int & face_voisins_ (int i, int j) const
double volume_entrelaces_ (int i)
const double & volume_entrelaces_ (int i) const
double porosite_surf_ (int i)
const double & porosite_surf_ (int i) const
int orientation_ (int face)
const int & orientation_ (int face) const
double xp_ (int elem, int ori)
const double & xp_ (int elem, int ori) const
Public Member Functions inherited from Operateur_Grad_base
Operateur_Grad_base ()
~Operateur_Grad_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
virtual DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
Calcul sans les conditions aux limites ?
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_VDF_Face & self_cast (Objet_U &)
static const Op_Grad_VDF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Grad_VDF_Face_base
static const Type_info * info ()
static Op_Grad_VDF_Face_base & self_cast (Objet_U &)
static const Op_Grad_VDF_Face_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Grad_base
static const Type_info * info ()
static Operateur_Grad_base & self_cast (Objet_U &)
static const Operateur_Grad_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Grad_VDF_Face_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Grad_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Grad_VDF_Face_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
SFichier Flux_grad
SFichier Flux_grad_moment
SFichier Flux_grad_sum
Protected Attributes inherited from Op_Grad_VDF_Face_base
Ref_Zone_VDF la_zone_vdf
Ref_Zone_Cl_VDF la_zcl_vdf
IntVect orientation
IntTab face_voisins
DoubleVect porosite_surf
DoubleVect volume_entrelaces
DoubleTab xp
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Grad_VDF_Face
Cette classe represente l'operateur de gradient
La discretisation est VDF. On calcule le gradient d'un champ_P0_VDF (la pression)
Definition at line 26 of file Op_Grad_VDF_Face.h.
Constructor & Destructor Documentation
Op_Grad_VDF_Face()
Op_Grad_VDF_Face::Op_Grad_VDF_Face ()
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
~Op_Grad_VDF_Face()
Op_Grad_VDF_Face::~Op_Grad_VDF_Face ()
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Grad_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
< Correction periodicite
Reimplemented from Operateur_base.
Definition at line 260 of file Op_Grad_VDF_Face.cpp.
{
  statistiques().begin_count(gradient_counter_);
  Matrice_Morse *mat = matrices.count("pression") ? matrices.at("pression") : NULL;
  const DoubleTab& inco = semi_impl.count("pression") ? semi_impl.at("pression") : (le_champ_inco.non_nul() ? le_champ_inco->valeurs() : ref_cast(Navier_Stokes_std, equation()).pression().valeurs());
  assert_espace_virtuel_vect(inco);
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
  const DoubleVect& face_surfaces = zvdf.face_surfaces();
  double coef;
  int n0, n1;
// Boucle sur les bords pour traiter les conditions aux limites
  for (int n_bord = 0; n_bord < zvdf.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
      if ( sub_type(Neumann_sortie_libre,la_cl.valeur()) )
        {
          const Neumann_sortie_libre& la_cl_typee = ref_cast(Neumann_sortie_libre, la_cl.valeur());
          for (int num_face = ndeb; num_face < nfin; num_face++)
            {
              const double P_imp = la_cl_typee.flux_impose(num_face-ndeb);
              n0 = face_voisins(num_face,0);
              if (n0 != -1)
                {
                  coef = face_surfaces(num_face)*porosite_surf(num_face) * Option_VDF::coeff_P_neumann;
                  if(mat) (*mat)(num_face, n0) += coef;
                  secmem(num_face) += (coef*(P_imp - inco(n0)));
                }
              else
                {
                  n1 = face_voisins(num_face,1);
                  coef = face_surfaces(num_face)*porosite_surf(num_face) * Option_VDF::coeff_P_neumann;
                  if(mat) (*mat)(num_face, n1) -= coef;
                  secmem(num_face) += (coef*(inco(n1) - P_imp));
                }
            }
        }
      else if (sub_type(Periodique,la_cl.valeur())) //!< Correction periodicite
        {
          for (int num_face = ndeb; num_face < nfin; num_face++)
            {
              n0 = face_voisins(num_face,0), n1 = face_voisins(num_face,1);
              coef = face_surfaces(num_face)*porosite_surf(num_face);
              secmem(num_face) += (coef*(inco(n1) - inco(n0)));
            }
        }
      else if (sub_type(Symetrie,la_cl.valeur())) { /* Do nothing */ }
      else if ( (sub_type(Dirichlet,la_cl.valeur())) || (sub_type(Dirichlet_homogene,la_cl.valeur())) ) { /* Do nothing */ }
    }
// Boucle sur les faces internes
  for (int num_face = zvdf.premiere_face_int(); num_face < zvdf.nb_faces(); num_face++)
    {
      n0 = face_voisins(num_face,0), n1 = face_voisins(num_face,1);
      coef = face_surfaces(num_face)*porosite_surf(num_face);
      if(mat) (*mat)(num_face, n0) += coef;
      if(mat) (*mat)(num_face, n1) -= coef;
      secmem(num_face) += coef*(inco(n1)-inco(n0));
    }
  secmem.echange_espace_virtuel();
  statistiques().end_count(gradient_counter_);
}
References assert_espace_virtuel_vect(), Statistiques::begin_count(), Option_VDF::coeff_P_neumann, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Statistiques::end_count(), MorEqn::equation(), Zone_VF::face_surfaces(), Op_Grad_VDF_Face_base::face_voisins, Neumann::flux_impose(), Cond_lim::frontiere_dis(), gradient_counter_, Op_Grad_VDF_Face_base::la_zcl_vdf, Op_Grad_VDF_Face_base::la_zone_vdf, Operateur_base::le_champ_inco, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Op_Grad_VDF_Face_base::porosite_surf, Zone_VF::premiere_face_int(), ref_cast, statistiques(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), and Champ_Inc::valeurs().
cree_instance()
Objet_U * Op_Grad_VDF_Face::cree_instance () static
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
dimensionner_blocs()
void Op_Grad_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
Definition at line 238 of file Op_Grad_VDF_Face.cpp.
{
  Matrice_Morse *mat_p = matrices.count("pression") ? matrices.at("pression") : NULL, mat2_p;
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  IntTab stencil_p(0, 2);
  stencil_p.set_smart_resize(1);
  int e;
  for (int f = 0; f < zvdf.nb_faces(); f++)
    for (int i = 0; i < 2; i++)
      if ((e = zvdf.face_voisins(f, i)) >= 0) stencil_p.append_line(f, e);
  tableau_trier_retirer_doublons(stencil_p);
  if (mat_p)
    {
      Matrix_tools::allocate_morse_matrix(zvdf.nb_faces_tot(), zvdf.nb_elem_tot(), stencil_p, mat2_p);
      mat_p->nb_colonnes() ? *mat_p += mat2_p : *mat_p = mat2_p;
    }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Zone_VF::face_voisins(), Op_Grad_VDF_Face_base::la_zone_vdf, Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), TRUSTArray< _TYPE_ >::set_smart_resize(), tableau_trier_retirer_doublons(), and Ref_Zone_VDF::valeur().
duplique()
int Op_Grad_VDF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
get_info()
const Type_info * Op_Grad_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
impr()
int Op_Grad_VDF_Face::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 43 of file Op_Grad_VDF_Face.cpp.
{
  const int impr_mom=la_zone_vdf->zone().Moments_a_imprimer();
  const int impr_sum=(la_zone_vdf->zone().Bords_a_imprimer_sum().est_vide() ? 0:1);
  const int impr_bord=(la_zone_vdf->zone().Bords_a_imprimer().est_vide() ? 0:1);
  const Schema_Temps_base& sch = equation().probleme().schema_temps();
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
  const DoubleVect& face_surfaces = zvdf.face_surfaces();
  const Equation_base& eqn = equation();
  const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,eqn);
  const Champ_P0_VDF& la_pression_P0 = ref_cast(Champ_P0_VDF,eqn_hydr.pression_pa().valeur());
  const DoubleTab& pression_P0 = la_pression_P0.valeurs();
  int elem0, elem1, face, ori;
  double n0;
  const int nb_faces =  zvdf.nb_faces_tot();
  DoubleTab xgr(nb_faces,dimension);
  xgr=0.;
  if (impr_mom)
    {
      const DoubleTab& xgrav = zvdf.xv();
      const ArrOfDouble& c_grav=zvdf.zone().cg_moments();
      for (int num_face=0; num_face <nb_faces; num_face++)
        for (int i=0; i<dimension; i++) xgr(num_face,i)=xgrav(num_face,i)-c_grav[i];
    }
  flux_bords_.resize(zvdf.nb_faces_bord(),dimension);
  flux_bords_ = 0.;
// flux_bords contains the sum of flux on each boundary:
  DoubleTrav tab_flux_bords(3,zvdf.nb_front_Cl(),3);
  tab_flux_bords=0.;
  /*  flux_bord(k)          ->   flux_bords2(0,num_cl,k)
      flux_bord_perio1(k)   ->   flux_bords2(1,num_cl,k)
      flux_bord_perio2(k)   ->   flux_bords2(2,num_cl,k)
      moment(k)             ->   flux_bords2(3,num_cl,k) */
  int nb_bord =  zvdf.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bord; n_bord++)
    {
      const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int impr_boundary = (zvdf.zone().Bords_a_imprimer_sum().contient(le_bord.le_nom()) ? 1 : 0);
      int ndeb = le_bord.num_premiere_face();
      int nfin = ndeb + le_bord.nb_faces();
      for (face=ndeb; face<nfin; face++)
        {
          elem0 = face_voisins(face,0);
          ori = orientation(face);
          n0 = face_surfaces(face)*porosite_surf(face);
          if (ori == 0)
            {
              if (elem0 != -1) flux_bords_(face,0) = (pression_P0(elem0))*n0 ;
              else
                {
                  elem1 = face_voisins(face,1);
                  flux_bords_(face,0) = -(pression_P0(elem1))*n0 ;
                }
              tab_flux_bords(0, n_bord, 0) += flux_bords_(face,0) ;
            }
          else if (ori == 1)
            {
              if (elem0 != -1) flux_bords_(face,1) = (pression_P0(elem0))*n0 ;
              else
                {
                  elem1 = face_voisins(face,1);
                  flux_bords_(face,1) = -(pression_P0(elem1))*n0 ;
                }
              tab_flux_bords(0, n_bord, 1) += flux_bords_(face,1) ;
            }
          else if (ori == 2)
            {
              if (elem0 != -1) flux_bords_(face,2) = (pression_P0(elem0))*n0 ;
              else
                {
                  elem1 = face_voisins(face,1);
                  flux_bords_(face,2) = -(pression_P0(elem1))*n0 ;
                }
              tab_flux_bords(0, n_bord, 2) += flux_bords_(face,2) ;
            }
          if (dimension == 2)
            {
              if (impr_mom)
                tab_flux_bords(2, n_bord, 2) +=flux_bords_(face,1)*xgr(face,0)-flux_bords_(face,0)*xgr(face,1);
              if (impr_boundary)
                {
                  tab_flux_bords(1, n_bord, 0) += flux_bords_(face,0) ;
                  tab_flux_bords(1, n_bord, 1) += flux_bords_(face,1) ;
                }
            }
          else if (dimension == 3)
            {
              if (impr_mom)
                {
                  tab_flux_bords(2, n_bord, 0) +=flux_bords_(face,2)*xgr(face,1)-flux_bords_(face,1)*xgr(face,2);
                  tab_flux_bords(2, n_bord, 1) +=flux_bords_(face,0)*xgr(face,2)-flux_bords_(face,2)*xgr(face,0);
                  tab_flux_bords(2, n_bord, 2) +=flux_bords_(face,1)*xgr(face,0)-flux_bords_(face,0)*xgr(face,1);
                }
              if (impr_boundary)
                {
                  tab_flux_bords(1, n_bord, 0) += flux_bords_(face,0) ;
                  tab_flux_bords(1, n_bord, 1) += flux_bords_(face,1) ;
                  tab_flux_bords(1, n_bord, 2) += flux_bords_(face,2) ;
                }
            }
        } //!< fin for face
    } //!< fin for n_bord
// Sum on all process:
  mp_sum_for_each_item(tab_flux_bords);
// Write the boundary fluxes:
  if (je_suis_maitre())
    {
// SFichier Flux_grad;
      if (!Flux_grad.is_open()) ouvrir_fichier(Flux_grad,"",1);
// SFichier Flux_grad_moment;
      if (!Flux_grad_moment.is_open()) ouvrir_fichier(Flux_grad_moment,"moment",impr_mom);
// SFichier Flux_grad_sum;
      if (!Flux_grad_sum.is_open()) ouvrir_fichier(Flux_grad_sum,"sum",impr_sum);
      Flux_grad.add_col(sch.temps_courant());
      if (impr_mom) Flux_grad_moment.add_col(sch.temps_courant());
      if (impr_sum) Flux_grad_sum.add_col(sch.temps_courant());
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          if (dimension == 2)
            {
              Flux_grad.add_col(tab_flux_bords(0, n_bord, 0));
              Flux_grad.add_col(tab_flux_bords(0, n_bord, 1));
              if (impr_sum)
                {
                  Flux_grad_sum.add_col(tab_flux_bords(1, n_bord, 0));
                  Flux_grad_sum.add_col(tab_flux_bords(1, n_bord, 1));
                }
              if (impr_mom) Flux_grad_moment.add_col(tab_flux_bords(2, n_bord, 2));
            }
          if (dimension == 3)
            {
              Flux_grad.add_col(tab_flux_bords(0, n_bord, 0));
              Flux_grad.add_col(tab_flux_bords(0, n_bord, 1));
              Flux_grad.add_col(tab_flux_bords(0, n_bord, 2));
              if (impr_sum)
                {
                  Flux_grad_sum.add_col(tab_flux_bords(1, n_bord, 0));
                  Flux_grad_sum.add_col(tab_flux_bords(1, n_bord, 1));
                  Flux_grad_sum.add_col(tab_flux_bords(1, n_bord, 2));
                }
              if (impr_mom)
                {
                  Flux_grad_moment.add_col(tab_flux_bords(2, n_bord, 0));
                  Flux_grad_moment.add_col(tab_flux_bords(2, n_bord, 1));
                  Flux_grad_moment.add_col(tab_flux_bords(2, n_bord, 2));
                }
            }
        }
      Flux_grad << finl;
      if (impr_sum) Flux_grad_sum << finl;
      if (impr_mom) Flux_grad_moment << finl;
    }
  const LIST(Nom)& Liste_Bords_a_imprimer = zvdf.zone().Bords_a_imprimer();
  if (!Liste_Bords_a_imprimer.est_vide())
    {
      EcrFicPartage Flux_grad_face;
      ouvrir_fichier_partage(Flux_grad_face,"",impr_bord);
      for (int n_bord=0; n_bord<nb_bord; n_bord++)
        {
          const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          if (zvdf.zone().Bords_a_imprimer().contient(le_bord.le_nom()))
            {
              if (je_suis_maitre())
                {
                  Flux_grad_face << "# Force par face sur " << le_bord.le_nom() << " au temps ";
                  sch.imprimer_temps_courant(Flux_grad_face);
                  Flux_grad_face << " : " << finl;
                }
              for (face=ndeb; face<nfin; face++)
                {
                  Flux_grad_face << "# Face a x= " << zvdf.xv(face,0) << " y= " << zvdf.xv(face,1);
                  if (dimension==3) Flux_grad_face << " z= " << zvdf.xv(face,2);
                  Flux_grad_face << " : Fx= " << flux_bords_(face, 0) << " Fy= " << flux_bords_(face, 1);
                  if (dimension==3) Flux_grad_face << " Fz= " << flux_bords_(face, 2);
                  Flux_grad_face << finl;
                }
              Flux_grad_face.syncfile();
            }
        }
    }
  return 1;
}
References Sortie::add_col(), Zone::Bords_a_imprimer(), Zone::Bords_a_imprimer_sum(), Zone::cg_moments(), List_Nom::contient(), Objet_U::dimension, MorEqn::equation(), liste::est_vide(), Zone_VF::face_surfaces(), Op_Grad_VDF_Face_base::face_voisins, finl, Operateur_base::flux_bords_, Flux_grad, Flux_grad_moment, Flux_grad_sum, Cond_lim::frontiere_dis(), Schema_Temps_base::imprimer_temps_courant(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), Op_Grad_VDF_Face_base::la_zcl_vdf, Op_Grad_VDF_Face_base::la_zone_vdf, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), LIST, Zone::Moments_a_imprimer(), mp_sum_for_each_item(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Op_Grad_VDF_Face_base::orientation, Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Op_Grad_VDF_Face_base::porosite_surf, Navier_Stokes_std::pression_pa(), Equation_base::probleme(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Inc_base::valeurs(), Zone_VF::xv(), and Zone_dis_base::zone().
info()
const Type_info * Op_Grad_VDF_Face::info () static
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
printOn()
Sortie & Op_Grad_VDF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 40 of file Op_Grad_VDF_Face.cpp.
{ return s << que_suis_je(); }
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_VDF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 41 of file Op_Grad_VDF_Face.cpp.
{ return s; }
self_cast() [1/2]
const Op_Grad_VDF_Face & Op_Grad_VDF_Face::self_cast (const Objet_U & r) static
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
self_cast() [2/2]
Op_Grad_VDF_Face & Op_Grad_VDF_Face::self_cast (Objet_U & r) static
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
taille_memoire()
unsigned Op_Grad_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 38 of file Op_Grad_VDF_Face.cpp.
Member Data Documentation
Flux_grad
SFichier Op_Grad_VDF_Face::Flux_grad mutable protected
Definition at line 35 of file Op_Grad_VDF_Face.h.
Referenced by impr().
Flux_grad_moment
SFichier Op_Grad_VDF_Face::Flux_grad_moment protected
Definition at line 35 of file Op_Grad_VDF_Face.h.
Referenced by impr().
Flux_grad_sum
SFichier Op_Grad_VDF_Face::Flux_grad_sum protected
Definition at line 35 of file Op_Grad_VDF_Face.h.
Referenced by impr().
info_obj
const Type_info Op_Grad_VDF_Face::info_obj static
Definition at line 28 of file Op_Grad_VDF_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Divers/Op_Grad_VDF_Face.h
src/VDF/Operateurs/Op_Divers/Op_Grad_VDF_Face.cpp