TRUST: Source_QC_Gravite_VDF Class Reference
Source_QC_Gravite_VDF Class Reference
class Source_QC_Gravite_VDF
Cette classe represente un terme source supplementaire a prendre en compte
dans les equations de quantite de mouvement dans le cas ou le fluide est
quasi compressible, en cas de gravite, et pour une discretisation VDF.
#include <Source_QC_Gravite_VDF.h>
Public Member Functions
Source_QC_Gravite_VDF ()
~Source_QC_Gravite_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_QC_Gravite_VDF & self_cast (Objet_U &)
static const
Source_QC_Gravite_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &zone, const Zone_Cl_dis &)
Detailed Description
class Source_QC_Gravite_VDF
Cette classe represente un terme source supplementaire a prendre en compte
dans les equations de quantite de mouvement dans le cas ou le fluide est
quasi compressible, en cas de gravite, et pour une discretisation VDF.
Definition at line 43 of file Source_QC_Gravite_VDF.h.
Constructor & Destructor Documentation
Source_QC_Gravite_VDF::Source_QC_Gravite_VDF ()
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
Source_QC_Gravite_VDF::~Source_QC_Gravite_VDF ()
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
Member Function Documentation
DoubleTab & Source_QC_Gravite_VDF::ajouter (DoubleTab & resu) const [virtual]
Implements Source_Gravite_Fluide_Dilatable_base.
Definition at line 41 of file Source_QC_Gravite_VDF.cpp.
References Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Gravite_Fluide_Dilatable_base::g, Fluide_Quasi_Compressible::get_traitement_rho_gravite(), Source_Gravite_Fluide_Dilatable_base::le_fluide, Milieu_base::masse_volumique(), Fluide_Dilatable_base::moyenne_vol(), ref_cast, Fluide_Dilatable_base::rho_discvit(), Ref_Fluide_Dilatable_base::valeur(), and Champ_Proto::valeurs().
{
  const Fluide_Quasi_Compressible& fluide = ref_cast(Fluide_Quasi_Compressible,le_fluide.valeur());
  const DoubleTab& tab_rho = fluide.rho_discvit(), rho_elem=fluide.masse_volumique().valeurs();
  const double rho_m = fluide.get_traitement_rho_gravite() ? fluide.moyenne_vol(rho_elem) : 0.0;
  ajouter_impl(g,rho_m,tab_rho,resu);
  return resu;
}
void Source_QC_Gravite_VDF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) [protected, virtual]
Implements Source_Gravite_Fluide_Dilatable_base.
Definition at line 36 of file Source_QC_Gravite_VDF.cpp.
References Source_Fluide_Dilatable_VDF_Proto::associer_zones_impl().
{
  associer_zones_impl(zone,zone_cl);
}
Objet_U * Source_QC_Gravite_VDF::cree_instance () [static]
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
int Source_QC_Gravite_VDF::duplique () const [virtual]
Implements Source_Gravite_Fluide_Dilatable_base.
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
const Type_info * Source_QC_Gravite_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
const Type_info * Source_QC_Gravite_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
Sortie & Source_QC_Gravite_VDF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 28 of file Source_QC_Gravite_VDF.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Source_QC_Gravite_VDF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 34 of file Source_QC_Gravite_VDF.cpp.
{ return is; }
const Source_QC_Gravite_VDF & Source_QC_Gravite_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
Source_QC_Gravite_VDF & Source_QC_Gravite_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
unsigned Source_QC_Gravite_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Source_QC_Gravite_VDF.cpp.
Member Data Documentation
const Type_info Source_QC_Gravite_VDF::info_obj [static]
Reimplemented from Source_Gravite_Fluide_Dilatable_base.
Definition at line 46 of file Source_QC_Gravite_VDF.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Source_QC_Gravite_VDF.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/Source_QC_Gravite_VDF.cpp