TRUST: ConstIntTab_parts Class Reference
ConstIntTab_parts Class Reference
#include <ConstDoubleTab_parts.h>
Public Member Functions
ConstIntTab_parts ()
ConstIntTab_parts (const IntVect &)
void initialize (const IntVect &)
void reset ()
const IntTab & operator[] (int i) const
int size () const
Private Member Functions
ConstIntTab_parts & operator= (const ConstIntTab_parts &)
Interdit !
ConstIntTab_parts (const ConstIntTab_parts &)
Interdit !
Private Attributes
Vect_IntTab parts_
Detailed Description
Definition at line 88 of file ConstDoubleTab_parts.h.
Constructor & Destructor Documentation
ConstIntTab_parts::ConstIntTab_parts () [inline]
Definition at line 91 of file ConstDoubleTab_parts.h.
{};
ConstIntTab_parts::ConstIntTab_parts (const IntVect & vect)
Definition at line 198 of file ConstDoubleTab_parts.cpp.
References init_parts(), parts_, and ref_cast_non_const.
{
// Cast en non const: pour remplir les ref dans parts_.
// Pas grave, ensuite les sous parties ne seront accessibles qu'en const de l'exterieur.
  IntVect& vect2=ref_cast_non_const(IntVect, vect);
  init_parts(vect2, parts_, (IntTab*) 0);
}
ConstIntTab_parts::ConstIntTab_parts (const ConstIntTab_parts &) [private]
Interdit !
Definition at line 287 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to copy constructor ConstIntTab_parts::ConstIntTab_parts(const ConstIntTab_parts &) is forbidden" << finl;
  Process::exit();
}
Member Function Documentation
void ConstIntTab_parts::initialize (const IntVect & vect)
Definition at line 206 of file ConstDoubleTab_parts.cpp.
References init_parts(), parts_, ref_cast_non_const, and reset().
Referenced by SSOR::ssor().
{
  reset();
// Cast en non const: pour remplir les ref dans parts_.
// Pas grave, ensuite les sous parties ne seront accessibles qu'en const de l'exterieur.
  IntVect& vect2=ref_cast_non_const(IntVect, vect);
  init_parts(vect2, parts_, (IntTab*) 0);
}
ConstIntTab_parts & ConstIntTab_parts::operator= (const ConstIntTab_parts &) [private]
Interdit !
Definition at line 279 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to ConstIntTab_parts::operator=(const ConstIntTab_parts &) is forbidden" << finl;
  Process::exit();
  return *this;
}
const IntTab& ConstIntTab_parts::operator[] (int i) const [inline]
Definition at line 95 of file ConstDoubleTab_parts.h.
  {
    return parts_[i];
  }
void ConstIntTab_parts::reset ()
Definition at line 215 of file ConstDoubleTab_parts.cpp.
References vect_impl::dimensionner_force(), and parts_.
Referenced by initialize().
{
  parts_.dimensionner_force(0);
}
int ConstIntTab_parts::size () const [inline]
Definition at line 99 of file ConstDoubleTab_parts.h.
References DoubleVect::size().
Referenced by Debog_Pb::ecrire_partie(), and Debog_Pb::verifier_partie().
  {
    return parts_.size();
  }
Member Data Documentation
Vect_IntTab ConstIntTab_parts::parts_ [private]
Definition at line 109 of file ConstDoubleTab_parts.h.
Referenced by ConstIntTab_parts(), initialize(), and reset().
The documentation for this class was generated from the following files:
src/Kernel/Math/ConstDoubleTab_parts.h
src/Kernel/Math/ConstDoubleTab_parts.cpp