TRUST: Assembleur_P_EF Class Reference
Assembleur_P_EF Class Reference
#include <Assembleur_P_EF.h>
Public Member Functions
Assembleur_P_EF ()
~Assembleur_P_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
int assembler_QC (const DoubleTab &, Matrice &) override
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u) override
int modifier_secmem (DoubleTab &) override
int modifier_solution (DoubleTab &) override
void completer (const Equation_base &) override
const Equation_base & equation () const
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_EF & self_cast (Objet_U &)
static const Assembleur_P_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Assembleur_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Equation_base mon_equation
Ref_Zone_EF la_zone_EF
Ref_Zone_Cl_EF la_zone_Cl_EF
DoubleTab les_coeff_pression
int has_P_ref
Detailed Description
Definition at line 30 of file Assembleur_P_EF.h.
Constructor & Destructor Documentation
Assembleur_P_EF()
Assembleur_P_EF::Assembleur_P_EF ()
Definition at line 31 of file Assembleur_P_EF.cpp.
~Assembleur_P_EF()
Assembleur_P_EF::~Assembleur_P_EF ()
Definition at line 31 of file Assembleur_P_EF.cpp.
Member Function Documentation
assembler()
int Assembleur_P_EF::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
Definition at line 101 of file Assembleur_P_EF.cpp.
{
  const Zone_EF& zone_EF = ref_cast(Zone_EF, la_zone_EF.valeur());
  const DoubleVect& volumes_som=zone_EF.volumes_sommets_thilde();
  return assembler_mat(la_matrice,volumes_som,1,1);
}
References assembler_mat(), la_zone_EF, ref_cast, Ref_Zone_EF::valeur(), and Zone_EF::volumes_sommets_thilde().
Referenced by assembler_QC().
assembler_mat()
int Assembleur_P_EF::assembler_mat (Matrice & la_matrice, const DoubleVect & volumes_som, int incr_pression, int resoudre_en_u) override virtual
< elem2 > elem1
< elem2 > elem1
Reimplemented from Assembleur_base.
Definition at line 130 of file Assembleur_P_EF.cpp.
{
  DoubleTab inv_volumes_som;
  calculer_inv_volume(inv_volumes_som, la_zone_Cl_EF.valeur(), volumes_som);
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  Cerr << "Assemblage de la matrice de pression en cours..." << finl;
// Matrice de pression :matrice creuse de taille nb_poly x nb_poly
// Cette fonction range la matrice dans une structure de matrice morse
// bien adaptee aux matrices creuses.
// On commence par calculer les tailles des tableaux tab1 et tab2
// (coeff_ a la meme taille que tab2)
// A chaque polyedre on associe :
// - une liste d'ints voisins[i] = {j>i t.q Mij est non nul }
// - une liste de reels  valeurs[i] = {Mij pour j dans Voisins[i]}
// - un reel terme_diag
// Implementation temporaire:
// On assemble une matrice de pression pour une equation d'hydraulique
// On injecte dans cette matrice les conditions aux limites
// On peut faire cela car a priori la matrice de pression n'est pas
// partagee par plusieurs equations sur une meme zone.
  const Zone_EF& la_zone = la_zone_EF.valeur();
  const Zone_Cl_EF& la_zone_cl = la_zone_Cl_EF.valeur();
  les_coeff_pression.resize(la_zone_cl.nb_faces_Cl());
  int n1 = la_zone.zone().nb_elem_tot();
  int n2 = la_zone.zone().nb_elem();
// Journal() << "n1= " << n1 << " n2= " << n2 << finl;
  int elem2;
  has_P_ref=0;
// on construit la connectivite som_elem
  int nb_sommets_tot=la_zone.zone().nb_som_tot();
  Static_Int_Lists som_elem;
  construire_connectivite_som_elem(nb_sommets_tot,la_zone.zone().les_elems(),som_elem,1);
// const IntTab& face_voisins = la_zone.face_voisins();
// const DoubleTab& face_normales = la_zone.face_normales();
// const Conds_lim& les_cl = la_zone_cl.les_conditions_limites();
// int premiere_face_std=la_zone.premiere_face_std();
// Rajout des porosites.
// const DoubleVect& porosite_face = la_zone.porosite_face();
// const DoubleVect& porosite_face = la_zone.porosite_face();
  la_matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice=ref_cast(Matrice_Bloc, la_matrice.valeur());
  matrice.dimensionner(1,2);
  matrice.get_bloc(0,0).typer("Matrice_Morse_Sym");
  matrice.get_bloc(0,1).typer("Matrice_Morse");
  Matrice_Morse_Sym& MBrr =  ref_cast(Matrice_Morse_Sym,matrice.get_bloc(0,0).valeur());
  Matrice_Morse& MBrv = ref_cast (Matrice_Morse,matrice.get_bloc(0,1).valeur());
  MBrr.dimensionner(n2,0);
  MBrv.dimensionner(n2,n1-n2,0);
// On parcourt les sommets
  const IntTab& sommets_elem=la_zone.zone().les_elems();
  int nb_coeff_rr=0;
  int nb_coeff_rv=0;
// int nb_elem=n2;
  int nb_som_elem=sommets_elem.dimension(1);
  for (int elem1=0; elem1<n1; elem1++)
    for (int s=0; s<nb_som_elem; s++)
      {
        int num_som=sommets_elem(elem1,s);
        int nb_voisin=som_elem.get_list_size(num_som);
        for (int i2=0; i2<nb_voisin; i2++)
          {
            elem2 = som_elem(num_som,i2);
            if (elem1 >= elem2)
              {
                if(elem1<n2)
                  nb_coeff_rr++;
                else if(elem2<n2)
                  nb_coeff_rv++;
              }
            else //!< elem2 > elem1
              {
                if(elem2<n2)
                  nb_coeff_rr++;
                else
                  if(elem1<n2)
                    nb_coeff_rv++;
              }
          }
      }
// on a surevalue  nb_coeff mais bon....
  IntTab indice_rr(nb_coeff_rr,2);
  IntTab indice_rv(nb_coeff_rv,2);
  nb_coeff_rr=0;
  nb_coeff_rv=0;
  for (int elem1=0; elem1<n1; elem1++)
    for (int s=0; s<nb_som_elem; s++)
      {
        int num_som=sommets_elem(elem1,s);
        int nb_voisin=som_elem.get_list_size(num_som);
        for (int i2=0; i2<nb_voisin; i2++)
          {
            elem2 = som_elem(num_som,i2);
            if (elem1 >= elem2)
              {
                if(elem1<n2)
                  {
                    indice_rr(nb_coeff_rr,0)=elem2;
                    indice_rr(nb_coeff_rr,1)=elem1;
                    nb_coeff_rr++;
                  }
                else if(elem2<n2)
                  {
                    indice_rv(nb_coeff_rv,0)=elem2;
                    indice_rv(nb_coeff_rv,1)=elem1;
                    nb_coeff_rv++;
                  }
              }
            else //!< elem2 > elem1
              {
                if(elem2<n2)
                  {
                    indice_rr(nb_coeff_rr,0)=elem1;
                    indice_rr(nb_coeff_rr,1)=elem2;
                    nb_coeff_rr++;
                  }
                else
                  if(elem1<n2)
                    {
                      indice_rv(nb_coeff_rv,0)=elem1;
                      indice_rv(nb_coeff_rv,1)=elem2;
                      nb_coeff_rv++;
                    }
              }
          }
      }
  tableau_trier_retirer_doublons(indice_rr);
  tableau_trier_retirer_doublons(indice_rv);
  for (int ii=0; ii<indice_rv.dimension(0); ii++) indice_rv(ii,1)-=n2;
  MBrr.dimensionner(indice_rr);
  if (indice_rv.size()>0)
    MBrv.dimensionner(indice_rv);
  MBrr.get_set_coeff() = 0;
  MBrv.get_set_coeff() = 0;
  const DoubleTab& Bthilde=la_zone.Bij_thilde();
  for (int elem1=0; elem1<n1; elem1++)
    for (int s=0; s<nb_som_elem; s++)
      {
        int num_som=sommets_elem(elem1,s);
        int nb_voisin=som_elem.get_list_size(num_som);
        for (int i2=0; i2<nb_voisin; i2++)
          {
            elem2 = som_elem(num_som,i2);
            int s2=0;
            while ((s2<nb_som_elem)&&(num_som!=sommets_elem(elem2,s2))) s2++;
            assert(num_som==sommets_elem(elem2,s2));
            double val=0;
            for (int dir=0; dir<dimension; dir++)
              val+=Bthilde(elem1,s,dir)*Bthilde(elem2,s2,dir)*inv_volumes_som(num_som,dir);
            if (elem1 <= elem2)
              {
// Cerr<<"ici "<<elem1 <<" "<<elem2 << " "<<s<<finl;
                if(elem2<n2)
                  MBrr(elem1,elem2)+=val;
                else
                  if(elem1<n2)
                    MBrv.coef(elem1,elem2-n2)+=val;
              }
          }
      }
  if (0)
    {
      DoubleTab test(n1),res(n2);
      test=1;
      res=10;
      matrice.multvect(test,res);
      Cerr<<" laplacien 1 "<<mp_max_abs_vect(res)<<finl;
      Cerr<<res<<finl;
// matrice.imprimer(Cerr);
      MBrr.imprimer_formatte(Cerr);
    }
// Debog::verifier_Mat_elems("Assemblage EF avt bord ",matrice);
// correction due aux bors
// const IntTab& faces_sommets=la_zone.face_sommets();
// int nb_som_face=faces_sommets.dimension(1);
// const IntTab& face_voisins = la_zone.face_voisins();
// const DoubleTab& face_normales = la_zone.face_normales();
  const Zone_Cl_EF& zone_Cl_EF  = la_zone_Cl_EF.valeur();
// prise en compte des " cl " ajout du temr - int P sur le bord
// int elem_ref=-2;
  for (int n_bord=0; n_bord<la_zone.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_EF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur()) )
        {
          MBrr.set_est_definie(1);
          /*
          if (has_P_ref==0)
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int face=le_bord.num_premiere_face();
              assert(le_bord.nb_faces()>0);
              elem_ref=face_voisins(face,0);
            }
          */
          has_P_ref=1;
        }
    }
  /*
       else {
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int num1 = 0;//le_bord.num_premiere_face();
        int num2 =  le_bord.nb_faces_tot();
        // test..........
        //num2=0;
        // ppovisoire !!!!!!
        for (int ind_face=num1; ind_face<num2; ind_face++)
         {
           int face=le_bord.num_face(ind_face);
          for (int sf=0;sf<nb_som_face;sf++)
            {
              int num_som=faces_sommets(face,sf);
    */
  int nb_som=la_zone.zone().nb_som();
  const ArrOfInt& type_sommet=zone_Cl_EF.get_type_sommet();
  for (int num_som=0; num_som<nb_som; num_som++)
    {
      int nb_voisin=som_elem.get_list_size(num_som);
// if (type_sommet(num_som)==0) ???
      if (type_sommet[num_som]==1)
        for (int i2=0; i2<nb_voisin; i2++)
          {
            elem2 =  som_elem(num_som,i2);
// ne marche qu'en 2D !!!!!!!
// int nb_voisin=som_elem.get_list_size(num_som);
            for (int i1=0; i1<nb_voisin; i1++)
              {
                int elem1 = som_elem(num_som,i1);
                int s1=0;
                while ((s1<nb_som_elem)&&(num_som!=sommets_elem(elem1,s1))) s1++;
                int s2=0;
                while ((s2<nb_som_elem)&&(num_som!=sommets_elem(elem2,s2))) s2++;
                assert(num_som==sommets_elem(elem2,s2));
                assert(num_som==sommets_elem(elem1,s1));
                double val=0;
                ArrOfDouble grad_mod(dimension),grad(dimension);
// double grad_n=0;
                for (int comp=0; comp<dimension; comp++)
                  {
// grad_n+=Bthilde(elem2,s2,comp)*face_normales(face,comp);
                    grad[comp]=Bthilde(elem2,s2,comp);
                  }
// grad_n/=(la_zone.surface(face)*la_zone.surface(face));
                zone_Cl_EF.modifie_gradient(grad_mod,grad,num_som);
                for (int dir=0; dir<dimension; dir++)
                  val-=Bthilde(elem1,s1,dir)*grad_mod[dir]*inv_volumes_som(num_som,dir);
// val-=Bthilde(elem1,s1,dir)*face_normales(face,dir)*grad_n*inv_volumes_som(num_som,dir);
// val=0;
// for (int dir=0;dir<dimension;dir++)
// val-=Bthilde(elem1,s1,dir)*Bthilde(elem2,s2,dir);
// val*=-1;
// assert(val==0);
                if (elem1 <= elem2)
                  {
                    if(elem2<n2)
                      MBrr(elem1,elem2)+=val;
                    else
                      if(elem1<n2)
                        MBrv.coef(elem1,elem2-n2)+=val;
                  }
              }
          }
    }
  /*
    }
    }
  */
  has_P_ref=(int)mp_max(has_P_ref);
// if (je_suis_maitre()) MBrr(elem_ref,elem_ref)*=2;
  if (0)
    if (!(has_P_ref))
      {
        Cerr<<"Pas de pression imposee  --> P(0)=0"<<finl;
        if (je_suis_maitre())
          MBrr(0,0) *= 2;
        MBrr.set_est_definie(1);
        has_P_ref=1;
      }
// test
  if (0)
    {
      DoubleTab test(n1),res(n2);
      test=1;
      res=10;
      matrice.multvect(test,res);
      Cerr<<" laplacien 1 "<<mp_max_abs_vect(res)<<finl;
      Cerr<<res<<finl;
// matrice.imprimer(Cerr);
      MBrr.imprimer_formatte(Cerr);
    }
// Debog::verifier_Mat_elems("Asse",matrice);
// MBrr.coeff_*=-1;
// matrice.imprimer(Cerr);exit();
// exit();
  Cerr << "Fin de l'assemblage de la matrice de pression" << finl;
  return 1;
}
References Zone_EF::Bij_thilde(), calculer_inv_volume(), Cerr, Matrice_Morse::coef(), construire_connectivite_som_elem(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), finl, Matrice_Bloc::get_bloc(), Static_Int_Lists::get_list_size(), Matrice_Morse::get_set_coeff(), Zone_Cl_EF::get_type_sommet(), has_P_ref, Matrice_Morse_Sym::imprimer_formatte(), Process::je_suis_maitre(), la_zone_Cl_EF, la_zone_EF, les_coeff_pression, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_Cl_EF::modifie_gradient(), Process::mp_max(), mp_max_abs_vect(), Matrice_Base::multvect(), Zone::nb_elem(), Zone::nb_elem_tot(), Zone_Cl_dis_base::nb_faces_Cl(), Zone_dis_base::nb_front_Cl(), Zone::nb_som(), Zone::nb_som_tot(), ref_cast, TRUSTTab< _TYPE_ >::resize(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTVect< _TYPE_ >::size(), sub_type, tableau_trier_retirer_doublons(), test(), Deriv_::typer(), Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Matrice_Base::valeur(), and Zone_dis_base::zone().
Referenced by assembler(), and assembler_rho_variable().
assembler_QC()
int Assembleur_P_EF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 468 of file Assembleur_P_EF.cpp.
{
  Cerr << "Assemblage de la matrice de pression pour Quasi Compressible en cours..." << finl;
  assembler(matrice);
  set_resoudre_increment_pression(1);
  set_resoudre_en_u(0);
  Matrice_Bloc& matrice_bloc= ref_cast(Matrice_Bloc,matrice.valeur());
  Matrice_Morse_Sym& la_matrice =ref_cast(Matrice_Morse_Sym,matrice_bloc.get_bloc(0,0).valeur());
  if ((la_matrice.get_est_definie()!=1)&&(1))
    {
      Cerr<<"Pas de pression imposee  --> P(0)=0"<<finl;
      if (je_suis_maitre())
        la_matrice(0,0) *= 2;
      la_matrice.set_est_definie(1);
    }
  Cerr << "Fin de l'assemblage de la matrice de pression" << finl;
  return 1;
}
References assembler(), Cerr, finl, Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Process::je_suis_maitre(), ref_cast, Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), and Deriv_Matrice_Base::valeur().
assembler_rho_variable()
int Assembleur_P_EF::assembler_rho_variable (Matrice & mat, const Champ_Don_base & rho) override virtual
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
Reimplemented from Assembleur_base.
Definition at line 110 of file Assembleur_P_EF.cpp.
{
// On multiplie par la masse volumique aux sommets
  if (!sub_type(Champ_Fonc_Q1_EF, rho))
    {
      Cerr << "La masse volumique n'est pas aux sommets dans Assembleur_P_EF::assembler_rho_variable." << finl;
      Process::exit();
    }
  const DoubleVect& volumes_som=ref_cast(Zone_EF, la_zone_EF.valeur()).volumes_sommets_thilde();
  const DoubleVect& masse_volumique=rho.valeurs();
  DoubleVect quantitee_som(volumes_som);
  int size=quantitee_som.size_array();
  for (int i=0; i<size; i++)
    quantitee_som(i)=(volumes_som(i)*masse_volumique(i));
// On assemble la matrice
  return assembler_mat(la_matrice,quantitee_som,1,1);
}
References assembler_mat(), Cerr, Process::exit(), finl, la_zone_EF, ref_cast, TRUSTArray< _TYPE_ >::size_array(), sub_type, Ref_Zone_EF::valeur(), and Champ_Don_base::valeurs().
associer_zone_cl_dis_base()
void Assembleur_P_EF::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis) override virtual
Implements Assembleur_base.
Definition at line 610 of file Assembleur_P_EF.cpp.
{
  la_zone_Cl_EF = ref_cast(Zone_Cl_EF, la_zone_Cl_dis);
}
References la_zone_Cl_EF, and ref_cast.
associer_zone_dis_base()
void Assembleur_P_EF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis) override virtual
Implements Assembleur_base.
Definition at line 605 of file Assembleur_P_EF.cpp.
{
  la_zone_EF = ref_cast(Zone_EF,la_zone_dis);
}
References la_zone_EF, and ref_cast.
completer()
void Assembleur_P_EF::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
Definition at line 615 of file Assembleur_P_EF.cpp.
{
  mon_equation=Eqn;
}
References mon_equation.
cree_instance()
Objet_U * Assembleur_P_EF::cree_instance () static
Definition at line 31 of file Assembleur_P_EF.cpp.
duplique()
int Assembleur_P_EF::duplique () const override virtual
Implements Objet_U.
Definition at line 31 of file Assembleur_P_EF.cpp.
equation()
const Equation_base & Assembleur_P_EF::equation () const inline
Definition at line 56 of file Assembleur_P_EF.h.
{
  if (mon_equation.non_nul()==0)
    {
      Cerr << "\nError in Assembleur_P_EF::equation() : The equation is unknown !" << finl;
      Process::exit();
    }
  return  mon_equation.valeur();
}
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Equation_base::valeur().
get_info()
const Type_info * Assembleur_P_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 31 of file Assembleur_P_EF.cpp.
info()
const Type_info * Assembleur_P_EF::info () static
Definition at line 31 of file Assembleur_P_EF.cpp.
modifier_secmem()
int Assembleur_P_EF::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
Definition at line 488 of file Assembleur_P_EF.cpp.
{
  Debog::verifier("secmem dans modifier secmem",secmem);
  const Zone_EF& la_zone = la_zone_EF.valeur();
  const Zone_Cl_EF& la_zone_cl = la_zone_Cl_EF.valeur();
  int nb_cond_lim = la_zone_cl.nb_cond_lim();
  const IntTab& face_voisins = la_zone.face_voisins();
// Modification du second membre :
  int i;
  for (i=0; i<nb_cond_lim; i++)
    {
      const Cond_lim_base& la_cl_base = la_zone_cl.les_conditions_limites(i).valeur();
      const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
      int ndeb = la_front_dis.num_premiere_face();
      int nfin = ndeb + la_front_dis.nb_faces();
// GF on est passe en increment de pression
      if ((sub_type(Neumann_sortie_libre,la_cl_base)) && (!get_resoudre_increment_pression()))
        {
          double Pimp, coef;
          const Neumann_sortie_libre& la_cl_Neumann = ref_cast(Neumann_sortie_libre, la_cl_base);
// const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl_base.frontiere_dis());
// int ndeb = la_front_dis.num_premiere_face();
// int nfin = ndeb + la_front_dis.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              Pimp = la_cl_Neumann.flux_impose(num_face-ndeb);
              coef = les_coeff_pression[num_face]*Pimp;
              secmem[face_voisins(num_face,0)] += coef;
            }
        }
      else if (sub_type(Champ_front_instationnaire_base,
                        la_cl_base.champ_front().valeur())&&(get_resoudre_en_u()))
        {
          if (sub_type(Dirichlet,la_cl_base))
            {
// Cas Dirichlet variable dans le temps
// N'est utile que pour des champs front. variables dans le temps
              const Champ_front_instationnaire_base& le_ch_front =
                ref_cast( Champ_front_instationnaire_base,
                          la_cl_base.champ_front().valeur());
              const DoubleTab& Gpt = le_ch_front.Gpoint();
              for (int num_face=ndeb; num_face<nfin; num_face++)
                {
// for num_face
                  double Stt = 0.;
                  for (int k=0; k<dimension; k++)
                    Stt -= Gpt(k) * la_zone.face_normales(num_face, k);
                  secmem(face_voisins(num_face,0)) += Stt;
                }
            }
        }
      else if (sub_type(Champ_front_var_instationnaire,
                        la_cl_base.champ_front().valeur())&&(get_resoudre_en_u()))
        {
          if (sub_type(Dirichlet,la_cl_base))
            {
// cas instationaire et variable
              const Champ_front_var_instationnaire& le_ch_front =
                ref_cast( Champ_front_var_instationnaire, la_cl_base.champ_front().valeur());
              const DoubleTab& Gpt = le_ch_front.Gpoint();
              for (int num_face=ndeb; num_face<nfin; num_face++)
                {
                  double Stt = 0.;
                  for (int k=0; k<dimension; k++)
                    Stt -= Gpt(num_face - ndeb, k) *
                           la_zone.face_normales(num_face, k);
                  secmem(face_voisins(num_face,0)) += Stt;
                }
            }
        }
    }
  secmem.echange_espace_virtuel();
  Debog::verifier("secmem dans modifier secmem fin",secmem);
  return 1;
}
References Cond_lim_base::champ_front(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_EF::face_normales(), Zone_VF::face_voisins(), Neumann::flux_impose(), Cond_lim_base::frontiere_dis(), Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Champ_front_instationnaire_base::Gpoint(), Champ_front_var_instationnaire::Gpoint(), la_zone_Cl_EF, la_zone_EF, les_coeff_pression, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, sub_type, Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), and Debog::verifier().
modifier_solution()
int Assembleur_P_EF::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Definition at line 570 of file Assembleur_P_EF.cpp.
{
  Debog::verifier("pression dans modifier solution in",pression);
// Projection :
  double press_0;
  if(!has_P_ref)
    {
// abort();
// On prend la pression minimale comme pression de reference
// afin d'avoir la meme pression de reference en sequentiel et parallele
      press_0=DMAXFLOAT;
      int n,nb_elem=la_zone_EF.valeur().zone().nb_elem();
      for(n=0; n<nb_elem; n++)
        if (pression[n] < press_0)
          press_0 = pression[n];
      press_0 = Process::mp_min(press_0);
      for(n=0; n<nb_elem; n++)
        pression[n] -=press_0;
      pression.echange_espace_virtuel();
    }
  return 1;
}
References DMAXFLOAT, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), has_P_ref, la_zone_EF, Process::mp_min(), Zone::nb_elem(), Ref_Zone_EF::valeur(), Debog::verifier(), and Zone_dis_base::zone().
printOn()
Sortie & Assembleur_P_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Assembleur_P_EF.cpp.
{
  return s << que_suis_je() << " " << le_nom() ;
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Assembleur_P_EF.cpp.
{
  return Assembleur_base::readOn(s);
}
References Assembleur_base::readOn().
self_cast() [1/2]
const Assembleur_P_EF & Assembleur_P_EF::self_cast (const Objet_U & r) static
Definition at line 31 of file Assembleur_P_EF.cpp.
self_cast() [2/2]
Assembleur_P_EF & Assembleur_P_EF::self_cast (Objet_U & r) static
Definition at line 31 of file Assembleur_P_EF.cpp.
taille_memoire()
unsigned Assembleur_P_EF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 31 of file Assembleur_P_EF.cpp.
zone_Cl_dis_base()
const Zone_Cl_dis_base & Assembleur_P_EF::zone_Cl_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 600 of file Assembleur_P_EF.cpp.
{
  return la_zone_Cl_EF.valeur();
}
References la_zone_Cl_EF, and Ref_Zone_Cl_EF::valeur().
zone_dis_base()
const Zone_dis_base & Assembleur_P_EF::zone_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 595 of file Assembleur_P_EF.cpp.
{
  return la_zone_EF.valeur();
}
References la_zone_EF, and Ref_Zone_EF::valeur().
Member Data Documentation
has_P_ref
int Assembleur_P_EF::has_P_ref protected
Definition at line 53 of file Assembleur_P_EF.h.
Referenced by assembler_mat(), and modifier_solution().
info_obj
const Type_info Assembleur_P_EF::info_obj static
Definition at line 32 of file Assembleur_P_EF.h.
la_zone_Cl_EF
Ref_Zone_Cl_EF Assembleur_P_EF::la_zone_Cl_EF protected
Definition at line 51 of file Assembleur_P_EF.h.
Referenced by assembler_mat(), associer_zone_cl_dis_base(), modifier_secmem(), and zone_Cl_dis_base().
la_zone_EF
Ref_Zone_EF Assembleur_P_EF::la_zone_EF protected
Definition at line 50 of file Assembleur_P_EF.h.
Referenced by assembler(), assembler_mat(), assembler_rho_variable(), associer_zone_dis_base(), modifier_secmem(), modifier_solution(), and zone_dis_base().
les_coeff_pression
DoubleTab Assembleur_P_EF::les_coeff_pression protected
Definition at line 52 of file Assembleur_P_EF.h.
Referenced by assembler_mat(), and modifier_secmem().
mon_equation
Ref_Equation_base Assembleur_P_EF::mon_equation protected
Definition at line 49 of file Assembleur_P_EF.h.
Referenced by completer(), and equation().
The documentation for this class was generated from the following files:
src/EF/Operateurs/Assembleur_P_EF.h
src/EF/Operateurs/Assembleur_P_EF.cpp