TRUST: Op_Moyenne Class Reference
Op_Moyenne Class Reference
#include <Op_Moyenne.h>
Public Member Functions
Op_Moyenne ()
~Op_Moyenne ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
double temps () const override
Champ_Don & moyenne_convergee ()
const Integrale_tps_Champ & integrale () const override
const DoubleTab & valeurs () const
DoubleTab & valeurs ()
double dt_integration () const
void mettre_a_jour (double temps) override
void initialiser (double val) override
void associer (const Zone_dis_base &une_zdis, const Champ_Generique_base &le_champ, double t1, double t2) override
void fixer_tstat_deb (double, double) override
void fixer_tstat_fin (double tps) override
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
void completer (const Probleme_base &) override
DoubleTab calculer_valeurs () const override
Public Member Functions inherited from Operateur_Statistique_tps_base
Operateur_Statistique_tps_base ()
~Operateur_Statistique_tps_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Nom & localisation_post () const
void associer (const Nom &loc_post)
virtual void associer_op_stat (const Operateur_Statistique_tps_base &)
virtual void associer (const Zone_dis_base &, const Champ_Generique_base &, double, double)=0
virtual void fixer_tstat_deb (double, double)=0
virtual void fixer_tstat_fin (double)=0
virtual void mettre_a_jour (double temps)=0
const Nom & le_nom () const override=0
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual double temps () const =0
virtual const Integrale_tps_Champ & integrale () const =0
virtual void initialiser (double val)=0
virtual void completer (const Probleme_base &)=0
virtual DoubleTab calculer_valeurs () const =0
virtual int completer_post_statistiques (const Domaine &dom, const int is_axi, Format_Post_base &format)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Moyenne & self_cast (Objet_U &)
static const Op_Moyenne & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Statistique_tps_base
static const Type_info * info ()
static Operateur_Statistique_tps_base & self_cast (Objet_U &)
static const Operateur_Statistique_tps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Statistique_tps_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Operateur_Statistique_tps_base
Sortie & printOn (Sortie &x) const override
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Integrale_tps_Champ integrale_champ
Champ_Don ch_moyenne_convergee_
Protected Attributes inherited from Operateur_Statistique_tps_base
Nom localisation_post_
Detailed Description
Definition at line 23 of file Op_Moyenne.h.
Constructor & Destructor Documentation
Op_Moyenne()
Op_Moyenne::Op_Moyenne ()
Definition at line 20 of file Op_Moyenne.cpp.
~Op_Moyenne()
Op_Moyenne::~Op_Moyenne ()
Definition at line 20 of file Op_Moyenne.cpp.
Member Function Documentation
associer()
void Op_Moyenne::associer (const Zone_dis_base & une_zdis, const Champ_Generique_base & le_champ, double t1, double t2) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 91 of file Op_Moyenne.h.
{
  Champ espace_stockage_source;
  const Champ_base& source = le_champ.get_champ(espace_stockage_source);
  Nom type_le_champ = source.que_suis_je();
  int renomme;
  renomme=0;
  if (type_le_champ.debute_par("Champ"))
    renomme=1;
  type_le_champ.suffix("Champ_");
  type_le_champ.suffix("Fonc_");
  Nom type("Champ_Fonc_");
  if (renomme==1)
    type+=type_le_champ;
  else
    type = type_le_champ;
  integrale_champ.typer(type);
  integrale_champ.associer_zone_dis_base(une_zdis);
  integrale_champ.associer(le_champ,1,t1,t2);
}
References Integrale_tps_Champ::associer(), Champ_Fonc::associer_zone_dis_base(), Nom::debute_par(), Champ_Generique_base::get_champ(), integrale_champ, Objet_U::que_suis_je(), Nom::suffix(), and Deriv_::typer().
Referenced by Champ_Generique_Moyenne::completer(), and Champ_Fonc_reprise::readOn().
calculer_valeurs()
DoubleTab Op_Moyenne::calculer_valeurs () const override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 76 of file Op_Moyenne.cpp.
{
  double dt = dt_integration();
  DoubleTab moyenne(valeurs());
  if (dt > 0)
    moyenne /= dt;
  return moyenne;
}
References dt_integration(), and valeurs().
Referenced by Champ_Generique_Moyenne::get_champ(), and Champ_Fonc_reprise::readOn().
completer()
void Op_Moyenne::completer (const Probleme_base & Pb) override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 44 of file Op_Moyenne.cpp.
{
  Nom nom_pour_post("Moyenne_");
  const REF(Champ_Generique_base)& mon_champ=integrale_champ.le_champ();
  const Noms noms = mon_champ->get_property("nom");
  nom_pour_post += Motcle(noms[0]);
  integrale_champ->nommer(nom_pour_post);
// Dimensionnement du champ integrale_champ a la meme taille que mon_champ
  Champ espace_stockage_source;
  const Champ_base& source = mon_champ->get_champ(espace_stockage_source);
  const DoubleTab& tab1 = source.valeurs();
// La methode valeurs pour cette classe est surchargee et renvoie
// integrale_champ->valeurs(). Il n'y a pas de stockage en memoire
// de la moyenne. On stocke l'integrale en temps et on postraite la moyenne
// Copie de la structure du vecteur, initialisation a zero.
  valeurs().copy(tab1, ArrOfDouble::NOCOPY_NOINIT);
  if (!ch_moyenne_convergee_.non_nul())
    valeurs() = 0.;
  int nb_comp = source.nb_comp();
  integrale_champ->associer_zone_dis_base(Pb.domaine_dis().zone_dis(0).valeur());
  integrale_champ->fixer_nb_comp(nb_comp);
  if (nb_comp == 1)
    integrale_champ->fixer_unite(source.unite());
  else
    integrale_champ->fixer_unites(source.unites());
  integrale_champ->changer_temps(Pb.schema_temps().temps_courant());
}
References Champ_Fonc::associer_zone_dis_base(), ch_moyenne_convergee_, Champ_Fonc::changer_temps(), TRUSTTab< _TYPE_ >::copy(), Probleme_base::domaine_dis(), integrale_champ, Integrale_tps_Champ::le_champ(), Field_base::nb_comp(), Array_base::NOCOPY_NOINIT, Champ_Fonc::nommer(), O_U_Ptr::non_nul(), REF, Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), Field_base::unite(), Field_base::unites(), Deriv_Zone_dis_base::valeur(), valeurs(), Champ_Proto::valeurs(), and Domaine_dis::zone_dis().
Referenced by Champ_Generique_Moyenne::completer(), and Champ_Fonc_reprise::readOn().
cree_instance()
Objet_U * Op_Moyenne::cree_instance () static
Definition at line 20 of file Op_Moyenne.cpp.
dt_integration()
double Op_Moyenne::dt_integration () const inline
Definition at line 54 of file Op_Moyenne.h.
  {
    return integrale_champ.dt_integration();
  };
References Integrale_tps_Champ::dt_integration(), and integrale_champ.
Referenced by calculer_valeurs(), Champ_Generique_Ecart_Type::dt_integration(), and mettre_a_jour().
duplique()
int Op_Moyenne::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Op_Moyenne.cpp.
fixer_tstat_deb()
void Op_Moyenne::fixer_tstat_deb (double tdeb, double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 125 of file Op_Moyenne.h.
{
  integrale_champ.fixer_t_debut(tdeb);
  integrale_champ.fixer_tps_integrale(tps);
  integrale_champ.fixer_dt_integr(tps-tdeb);
}
References Integrale_tps_Champ::fixer_dt_integr(), Integrale_tps_Champ::fixer_t_debut(), Integrale_tps_Champ::fixer_tps_integrale(), and integrale_champ.
Referenced by Champ_Fonc_reprise::readOn().
fixer_tstat_fin()
void Op_Moyenne::fixer_tstat_fin (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 132 of file Op_Moyenne.h.
{
  integrale_champ.fixer_t_fin(tps);
}
References Integrale_tps_Champ::fixer_t_fin(), and integrale_champ.
get_info()
const Type_info * Op_Moyenne::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 20 of file Op_Moyenne.cpp.
info()
const Type_info * Op_Moyenne::info () static
Definition at line 20 of file Op_Moyenne.cpp.
initialiser()
void Op_Moyenne::initialiser (double val) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 86 of file Op_Moyenne.h.
{
  integrale_champ.valeurs()= val_init;
}
References integrale_champ, and Champ_Fonc::valeurs().
integrale()
const Integrale_tps_Champ & Op_Moyenne::integrale () const inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 41 of file Op_Moyenne.h.
  {
    return integrale_champ;
  };
References integrale_champ.
Referenced by Op_Correlation::completer(), Op_Ecart_type::completer(), Champ_Generique_Correlation::get_directive_pour_discr(), Champ_Generique_Moyenne::integrale(), Champ_Generique_Moyenne::temps(), and Champ_Generique_Ecart_Type::valeurs().
le_nom()
const Nom & Op_Moyenne::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Implements Operateur_Statistique_tps_base.
Definition at line 29 of file Op_Moyenne.h.
  {
    return integrale_champ.le_nom();
  };
References integrale_champ, and O_U_Ptr::le_nom().
Referenced by printOn().
mettre_a_jour()
void Op_Moyenne::mettre_a_jour (double temps) inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 74 of file Op_Moyenne.h.
{
  integrale_champ.mettre_a_jour(tps);
  if (ch_moyenne_convergee_.non_nul())
    {
// const Champ_Fonc_reprise& ch_moy = ref_cast(Champ_Fonc_reprise,ch_moyenne_convergee_.valeur());
      DoubleTab& valeurs_integrale = valeurs();
      valeurs_integrale = ch_moyenne_convergee_.valeurs();
      valeurs_integrale *= dt_integration();
    }
}
References ch_moyenne_convergee_, dt_integration(), integrale_champ, Integrale_tps_Champ::mettre_a_jour(), O_U_Ptr::non_nul(), valeurs(), and Champ_Don::valeurs().
moyenne_convergee()
Champ_Don & Op_Moyenne::moyenne_convergee () inline
Definition at line 37 of file Op_Moyenne.h.
  {
    return ch_moyenne_convergee_;
  };
References ch_moyenne_convergee_.
Referenced by Champ_Generique_Moyenne::lire_motcle_non_standard().
printOn()
Sortie & Op_Moyenne::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Op_Moyenne.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Op_Moyenne::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Op_Moyenne.cpp.
{
  return s ;
}
reprendre()
int Op_Moyenne::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 120 of file Op_Moyenne.h.
{
  return integrale_champ.reprendre(is);
}
References integrale_champ, and Champ_Fonc::reprendre().
Referenced by Champ_Fonc_reprise::readOn().
sauvegarder()
int Op_Moyenne::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 115 of file Op_Moyenne.h.
{
  return integrale_champ.sauvegarder(os);
}
References integrale_champ, and Champ_Fonc::sauvegarder().
self_cast() [1/2]
const Op_Moyenne & Op_Moyenne::self_cast (const Objet_U & r) static
Definition at line 20 of file Op_Moyenne.cpp.
self_cast() [2/2]
Op_Moyenne & Op_Moyenne::self_cast (Objet_U & r) static
Definition at line 20 of file Op_Moyenne.cpp.
taille_memoire()
unsigned Op_Moyenne::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Op_Moyenne.cpp.
temps()
double Op_Moyenne::temps () const inline override virtual
Implements Operateur_Statistique_tps_base.
Definition at line 33 of file Op_Moyenne.h.
  {
    return integrale_champ.temps();
  };
References integrale_champ, and Champ_Fonc::temps().
valeurs() [1/2]
DoubleTab & Op_Moyenne::valeurs () inline
Definition at line 49 of file Op_Moyenne.h.
  {
    return integrale_champ.valeurs();
  };
References integrale_champ, and Champ_Fonc::valeurs().
valeurs() [2/2]
const DoubleTab & Op_Moyenne::valeurs () const inline
Definition at line 45 of file Op_Moyenne.h.
  {
    return integrale_champ.valeurs();
  };
References integrale_champ, and Champ_Fonc::valeurs().
Referenced by calculer_valeurs(), completer(), and mettre_a_jour().
Member Data Documentation
ch_moyenne_convergee_
Champ_Don Op_Moyenne::ch_moyenne_convergee_ protected
Definition at line 71 of file Op_Moyenne.h.
Referenced by completer(), mettre_a_jour(), and moyenne_convergee().
info_obj
const Type_info Op_Moyenne::info_obj static
Definition at line 25 of file Op_Moyenne.h.
integrale_champ
Integrale_tps_Champ Op_Moyenne::integrale_champ protected
Definition at line 70 of file Op_Moyenne.h.
Referenced by associer(), completer(), dt_integration(), fixer_tstat_deb(), fixer_tstat_fin(), initialiser(), integrale(), le_nom(), mettre_a_jour(), reprendre(), sauvegarder(), temps(), and valeurs().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Op_Moyenne.h
src/Kernel/Statistiques_temps/Op_Moyenne.cpp