TRUST: Ref_Sous_zones_dis Class Reference
Ref_Sous_zones_dis Class Reference
classe Domaine_dis
Cette classe represente la notion de domaine discretise
Elle contient l'ensemble des objets de type Zone_dis
qui correspondent a la discretisation des objets
de type Zone contenus dans l'objet Domaine associe au
domaine discretise.
#include <Domaine_dis.h>
Public Member Functions
~Ref_Sous_zones_dis ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Sous_zones_dis ()
Ref_Sous_zones_dis (const Sous_zones_dis &)
Ref_Sous_zones_dis (const Ref_Sous_zones_dis &)
const Sous_zones_dis & valeur () const
Sous_zones_dis & valeur ()
const Sous_zones_dis * operator-> () const
Sous_zones_dis * operator-> ()
const Ref_Sous_zones_dis & operator= (const Sous_zones_dis &)
const Ref_Sous_zones_dis & operator= (const Ref_Sous_zones_dis &)
operator const Sous_zones_dis & () const
operator Sous_zones_dis & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Sous_zones_dis & self_cast (Objet_U &)
static const Ref_Sous_zones_dis & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Sous_zones_dis * pointeur_
Detailed Description
classe Domaine_dis
Cette classe represente la notion de domaine discretise
Elle contient l'ensemble des objets de type Zone_dis
qui correspondent a la discretisation des objets
de type Zone contenus dans l'objet Domaine associe au
domaine discretise.
Definition at line 43 of file Domaine_dis.h.
Constructor & Destructor Documentation
Ref_Sous_zones_dis::~Ref_Sous_zones_dis ()
Definition at line 30 of file Domaine_dis.cpp.
Ref_Sous_zones_dis::Ref_Sous_zones_dis ()
Definition at line 30 of file Domaine_dis.cpp.
Ref_Sous_zones_dis::Ref_Sous_zones_dis (const Sous_zones_dis & t)
Definition at line 30 of file Domaine_dis.cpp.
Ref_Sous_zones_dis::Ref_Sous_zones_dis (const Ref_Sous_zones_dis & t)
Definition at line 30 of file Domaine_dis.cpp.
Member Function Documentation
Objet_U * Ref_Sous_zones_dis::cree_instance () [static]
Definition at line 30 of file Domaine_dis.cpp.
int Ref_Sous_zones_dis::duplique () const [virtual]
Implements Ref_.
Definition at line 30 of file Domaine_dis.cpp.
const Type_info * Ref_Sous_zones_dis::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 30 of file Domaine_dis.cpp.
const Type_info & Ref_Sous_zones_dis::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 30 of file Domaine_dis.cpp.
const Type_info * Ref_Sous_zones_dis::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 30 of file Domaine_dis.cpp.
Ref_Sous_zones_dis::operator const Sous_zones_dis & () const
Definition at line 30 of file Domaine_dis.cpp.
Ref_Sous_zones_dis::operator Sous_zones_dis & ()
Definition at line 30 of file Domaine_dis.cpp.
const Sous_zones_dis * Ref_Sous_zones_dis::operator-> () const [inline]
Definition at line 43 of file Domaine_dis.h.
: public Objet_U
Sous_zones_dis * Ref_Sous_zones_dis::operator-> () [inline]
Definition at line 43 of file Domaine_dis.h.
: public Objet_U
const Ref_Sous_zones_dis & Ref_Sous_zones_dis::operator= (const Ref_Sous_zones_dis & t)
Definition at line 30 of file Domaine_dis.cpp.
const Ref_Sous_zones_dis & Ref_Sous_zones_dis::operator= (const Sous_zones_dis & t)
Definition at line 30 of file Domaine_dis.cpp.
Sortie & Ref_Sous_zones_dis::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 30 of file Domaine_dis.cpp.
Entree & Ref_Sous_zones_dis::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 30 of file Domaine_dis.cpp.
const Ref_Sous_zones_dis & Ref_Sous_zones_dis::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 30 of file Domaine_dis.cpp.
Ref_Sous_zones_dis & Ref_Sous_zones_dis::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 30 of file Domaine_dis.cpp.
void Ref_Sous_zones_dis::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 30 of file Domaine_dis.cpp.
unsigned Ref_Sous_zones_dis::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Domaine_dis.cpp.
const Sous_zones_dis & Ref_Sous_zones_dis::valeur () const [inline]
Definition at line 43 of file Domaine_dis.h.
Referenced by Domaine_dis::printOn(), Domaine_dis::readOn(), and Domaine_dis::sous_zone_dis().
: public Objet_U
Sous_zones_dis & Ref_Sous_zones_dis::valeur () [inline]
Definition at line 43 of file Domaine_dis.h.
: public Objet_U
Member Data Documentation
const Type_info Ref_Sous_zones_dis::info_obj [static]
Reimplemented from Ref_.
Definition at line 43 of file Domaine_dis.h.
Sous_zones_dis* Ref_Sous_zones_dis::pointeur_ [private]
Definition at line 43 of file Domaine_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Domaine_dis.h
src/Kernel/Framework/Domaine_dis.cpp