TRUST: Champ_Generique_Ecart_Type Class Reference
Champ_Generique_Ecart_Type Class Reference
class Champ_Generique_Ecart_Type
Champ destine a post-traiter un Ecart_Type d un champ generique
La classe porte un operateur statistique "Op_Ecart_Type" /!< Syntaxe a respecter pour jdd "nom_champ" Ecart_Type { t_deb "val_tdeb" t_fin "val_tfin" source "type_champ_gen" { ...source ref_Champ { Pb_champ "nom_pb" "nom_champ_discret" } } } "nom_champ" fixe par utilisateur sera le nom du champ generique "val_tdeb" et "val_tfin" valeur de debut et fin des statistiques pour ce champ "type_champ_gen" type d'un champ generique
#include <Champ_Generique_Ecart_Type.h>
Public Member Functions
Champ_Generique_Ecart_Type ()
~Champ_Generique_Ecart_Type ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
double temps () const
const Integrale_tps_Champ & integrale () const
const DoubleTab & valeurs () const
const DoubleTab & valeurs_carre () const
double dt_integration () const
double dt_integration_carre () const
Operateur_Statistique_tps_base & Operateur_Statistique ()
const
Operateur_Statistique_tps_base & Operateur_Statistique () const
virtual const Champ_base & get_champ (Champ &espace_stockage) const
void completer (const Postraitement_base &post)
void nommer_source ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Generique_Ecart_Type & self_cast (Objet_U &)
static const
Champ_Generique_Ecart_Type & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom et le type de l'operateur sur
un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Op_Ecart_type Op_Ecart_Type_
Detailed Description
class Champ_Generique_Ecart_Type
Champ destine a post-traiter un Ecart_Type d un champ generique
La classe porte un operateur statistique "Op_Ecart_Type" /!< Syntaxe a respecter pour jdd "nom_champ" Ecart_Type { t_deb "val_tdeb" t_fin "val_tfin" source "type_champ_gen" { ...source ref_Champ { Pb_champ "nom_pb" "nom_champ_discret" } } } "nom_champ" fixe par utilisateur sera le nom du champ generique "val_tdeb" et "val_tfin" valeur de debut et fin des statistiques pour ce champ "type_champ_gen" type d'un champ generique
Definition at line 48 of file Champ_Generique_Ecart_Type.h.
Constructor & Destructor Documentation
Champ_Generique_Ecart_Type::Champ_Generique_Ecart_Type ()
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
Champ_Generique_Ecart_Type::~Champ_Generique_Ecart_Type ()
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
Member Function Documentation
void Champ_Generique_Ecart_Type::completer (const Postraitement_base & post) [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 43 of file Champ_Generique_Ecart_Type.cpp.
References Op_Ecart_type::associer(), Op_Ecart_type::associer_op_stat(), Cerr, Op_Ecart_type::completer(), Postraitement::comprend_champ_post(), Process::exit(), finl, Postraitement::get_champ_post(), get_property(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Op_Ecart_Type_, ref_cast, Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Probleme_base& Pb = get_ref_pb_base();
  const Champ_Generique_base& ch_integre = get_source(0);
  const Zone_dis_base& zdis = get_ref_zone_dis_base();
  Op_Ecart_Type_.associer(zdis,ch_integre,tstat_deb_,tstat_fin_);
  Noms nom = get_source(0).get_property("nom");
  Motcle nom_champ = nom[0];
  Motcle nom_champ_moyenne("Moyenne_");
  nom_champ_moyenne += nom_champ;
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_deb_,"%e");
  nom_champ_moyenne += "_";
  nom_champ_moyenne += Nom(tstat_fin_,"%e");
  const Postraitement& mon_post = ref_cast(Postraitement,post);
  if (mon_post.comprend_champ_post(nom_champ_moyenne))
    {
      const Champ_Generique_base& champ_stat_base = mon_post.get_champ_post(nom_champ_moyenne);
      const Operateur_Statistique_tps_base& operateur = ref_cast(Champ_Generique_Moyenne,champ_stat_base).Operateur_Statistique();
      const Op_Moyenne& op_moyenne = ref_cast(Op_Moyenne,operateur);
      Op_Ecart_Type_.associer_op_stat(op_moyenne);
      Op_Ecart_Type_.completer(Pb);
    }
  else
    {
      Cerr<<"The specification of the post-processing rms field "<<finl;
      Cerr<<get_property("nom")[0]<<finl;
      Cerr<<"implies to specify before the corresponding "<<finl;
      Cerr<<"post-processing statistics average field."<<finl;
      Cerr<<"Please, modify your data set to specify the post-processing statistics"<<finl;
      Cerr<<"average field before (instead of after) the rms field "<<finl;
      Cerr<<get_property("nom")[0]<<finl;
      exit();
    }
}
Objet_U * Champ_Generique_Ecart_Type::cree_instance () [static]
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
double Champ_Generique_Ecart_Type::dt_integration () const [inline]
Definition at line 74 of file Champ_Generique_Ecart_Type.h.
References Op_Moyenne::dt_integration(), Op_Ecart_type::moyenne(), and Op_Ecart_Type_.
  {
    return Op_Ecart_Type_.moyenne().dt_integration();
  };
double Champ_Generique_Ecart_Type::dt_integration_carre () const [inline]
Definition at line 78 of file Champ_Generique_Ecart_Type.h.
References Op_Ecart_type::dt_integration_carre(), and Op_Ecart_Type_.
  {
    return Op_Ecart_Type_.dt_integration_carre();
  };
int Champ_Generique_Ecart_Type::duplique () const [virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
const Champ_base & Champ_Generique_Ecart_Type::get_champ (Champ & espace_stockage) const [virtual]
Implements Champ_Generique_base.
Definition at line 83 of file Champ_Generique_Ecart_Type.cpp.
References Op_Ecart_type::calculer_valeurs(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), DoubleVect::echange_espace_virtuel(), integrale(), Integrale_tps_Champ::le_champ(), Field_base::nature_du_champ(), Field_base::nb_comp(), Op_Ecart_Type_, REF, Deriv_Champ_base::valeur(), and Champ::valeurs().
{
  const REF(Champ_Generique_base)& mon_champ = integrale().le_champ();
  Champ espace_stockage_source;
  const Champ_base& source = mon_champ->get_champ(espace_stockage_source);
  Nature_du_champ nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  DoubleTab& tab_ecart_type = espace_stockage.valeurs();
  tab_ecart_type = Op_Ecart_Type_.calculer_valeurs();
  tab_ecart_type.echange_espace_virtuel();
  return espace_stockage.valeur();
}
const Type_info * Champ_Generique_Ecart_Type::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
const Noms Champ_Generique_Ecart_Type::get_property (const Motcle & query) const [virtual]
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 99 of file Champ_Generique_Ecart_Type.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, Motcles::search(), and vect_impl::size().
Referenced by completer().
{
// Creation des composantes serait a faire de maniere dynamique (Ecart_Type_...)
  Motcles motcles(1);
  motcles[0] = "composantes";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
// On fixe les composantes specifiques pour le Champ_Generique_Ecart_Type
// car dans Format_Post_Lml::ecrire_champ_lml() dans le cas d une localisation ELEM
// elles sont utilisees
        /*
          const Noms compo_cibles = get_source(0).get_property("composantes");
          int size = compo_cibles.size();
          Noms mots(size);
          for (int i=0; i<size; i++) {
          mots[i] = "Ecart_Type_";
          mots[i] += compo_cibles[i];
          }
          return mots;
          break;
// Actuellement choix fait d ajouter simplement numero de composante
        */
        const Noms source_compos = get_source(0).get_property("composantes");
        int nb_comp = source_compos.size();
        Noms compo(nb_comp);
        for (int i=0; i<nb_comp; i++)
          {
            Nom nume(i);
            compo[i] = nom_post_+nume;
          }
        return compo;
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
const Type_info * Champ_Generique_Ecart_Type::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
const Integrale_tps_Champ& Champ_Generique_Ecart_Type::integrale () const [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 61 of file Champ_Generique_Ecart_Type.h.
References Op_Ecart_type::integrale(), and Op_Ecart_Type_.
Referenced by get_champ().
  {
    return Op_Ecart_Type_.integrale();
  };
void Champ_Generique_Ecart_Type::nommer_source () [virtual]
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 150 of file Champ_Generique_Ecart_Type.cpp.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source;
      const Noms nom = get_source(0).get_property("nom");
      nom_champ_source = nom[0];
      nom_post_source =  "Ecart_Type_";
      nom_post_source +=  nom_champ_source;
      nommer(nom_post_source);
    }
}
Operateur_Statistique_tps_base & Champ_Generique_Ecart_Type::Operateur_Statistique () [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 96 of file Champ_Generique_Ecart_Type.h.
References Op_Ecart_Type_.
{
  return Op_Ecart_Type_;
}
const Operateur_Statistique_tps_base & Champ_Generique_Ecart_Type::Operateur_Statistique () const [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 101 of file Champ_Generique_Ecart_Type.h.
References Op_Ecart_Type_.
{
  return Op_Ecart_Type_;
}
Sortie & Champ_Generique_Ecart_Type::printOn (Sortie & s) const [protected, virtual]
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 32 of file Champ_Generique_Ecart_Type.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Generique_Ecart_Type::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 37 of file Champ_Generique_Ecart_Type.cpp.
{
  Champ_Generique_Statistiques_base::readOn(s);
  return s ;
}
const Champ_Generique_Ecart_Type & Champ_Generique_Ecart_Type::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
Champ_Generique_Ecart_Type & Champ_Generique_Ecart_Type::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
unsigned Champ_Generique_Ecart_Type::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Champ_Generique_Ecart_Type.cpp.
double Champ_Generique_Ecart_Type::temps () const [inline, virtual]
Implements Champ_Generique_Statistiques_base.
Definition at line 57 of file Champ_Generique_Ecart_Type.h.
References Op_Ecart_type::integrale(), Op_Ecart_Type_, and Champ_Fonc::temps().
  {
    return Op_Ecart_Type_.integrale().temps();
  };
const DoubleTab& Champ_Generique_Ecart_Type::valeurs () const [inline]
Definition at line 66 of file Champ_Generique_Ecart_Type.h.
References Op_Moyenne::integrale(), Op_Ecart_type::moyenne(), Op_Ecart_Type_, and Champ_Fonc::valeurs().
  {
    return Op_Ecart_Type_.moyenne().integrale()->valeurs();
  };
const DoubleTab& Champ_Generique_Ecart_Type::valeurs_carre () const [inline]
Definition at line 70 of file Champ_Generique_Ecart_Type.h.
References Op_Ecart_type::integrale(), Op_Ecart_Type_, and Champ_Fonc::valeurs().
  {
    return Op_Ecart_Type_.integrale().valeurs();
  };
Member Data Documentation
const Type_info Champ_Generique_Ecart_Type::info_obj [static]
Reimplemented from Champ_Generique_Statistiques_base.
Definition at line 51 of file Champ_Generique_Ecart_Type.h.
Op_Ecart_type Champ_Generique_Ecart_Type::Op_Ecart_Type_ [protected]
Definition at line 92 of file Champ_Generique_Ecart_Type.h.
Referenced by completer(), dt_integration(), dt_integration_carre(), get_champ(), integrale(), Operateur_Statistique(), temps(), valeurs(), and valeurs_carre().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Ecart_Type.h
src/Kernel/Champs/Champ_Generique_Ecart_Type.cpp