TRUST: Loi_Etat_Mono_GP_base Class Reference
Loi_Etat_Mono_GP_base Class Reference
classe Loi_Etat_Mono_GP_base
Cette classe represente la loi d'etat base pour les gaz parfaits.
Elle definit un fluide dilatable dont la loi d'etat est :
Pth = rho*R*T
#include <Loi_Etat_Mono_GP_base.h>
Public Member Functions
Loi_Etat_Mono_GP_base ()
~Loi_Etat_Mono_GP_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Loi_Etat_Mono_GP_base & self_cast (Objet_U &)
static const
Loi_Etat_Mono_GP_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Champ rho_constant_pour_debug_
Detailed Description
classe Loi_Etat_Mono_GP_base
Cette classe represente la loi d'etat base pour les gaz parfaits.
Elle definit un fluide dilatable dont la loi d'etat est :
Pth = rho*R*T
Definition at line 41 of file Loi_Etat_Mono_GP_base.h.
Constructor & Destructor Documentation
Loi_Etat_Mono_GP_base::Loi_Etat_Mono_GP_base ()
Definition at line 27 of file Loi_Etat_Mono_GP_base.cpp.
Loi_Etat_Mono_GP_base::~Loi_Etat_Mono_GP_base ()
Definition at line 27 of file Loi_Etat_Mono_GP_base.cpp.
Member Function Documentation
virtual int Loi_Etat_Mono_GP_base::duplique () const [pure virtual]
Implements Loi_Etat_GP_base.
Implemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
const Type_info * Loi_Etat_Mono_GP_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 27 of file Loi_Etat_Mono_GP_base.cpp.
const Type_info * Loi_Etat_Mono_GP_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 27 of file Loi_Etat_Mono_GP_base.cpp.
Sortie & Loi_Etat_Mono_GP_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 29 of file Loi_Etat_Mono_GP_base.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Loi_Etat_Mono_GP_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 35 of file Loi_Etat_Mono_GP_base.cpp.
References Process::abort(), Param::ajouter(), Cerr, Loi_Etat_GP_base::Cp_, Loi_Etat_base::debug, finl, Param::lire_avec_accolades_depuis(), Loi_Etat_base::Pr_, Objet_U::que_suis_je(), Loi_Etat_GP_base::R_, Param::REQUIRED, and rho_constant_pour_debug_.
{
  double Cv_ = -1, gamma_ = -1;
  Param param(que_suis_je());
  param.ajouter("Cp",&Cp_,Param::REQUIRED);
  param.ajouter("Prandtl",&Pr_,Param::REQUIRED);
  param.ajouter("Cv",&Cv_);
  param.ajouter("gamma",&gamma_);
  param.ajouter("rho_constant_pour_debug",&rho_constant_pour_debug_);
  param.lire_avec_accolades_depuis(is);
  debug = gamma_<0 ? 1 : 0;
  if (gamma_<0) gamma_ = -gamma_;
  if (Cv_!=-1) R_ = Cp_ - Cv_;
  else if (gamma_!=-1) R_ = Cp_ *(1.-1./gamma_);
  else
    {
      Cerr<<"ERREUR : on attendait la definition du Cv (constante en gaz parfaits)"<<finl;
      Cerr<<"ou de la constante gamma (constante en gaz parfaits)"<<finl;
      abort();
    }
  return is;
}
const Loi_Etat_Mono_GP_base & Loi_Etat_Mono_GP_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 27 of file Loi_Etat_Mono_GP_base.cpp.
Loi_Etat_Mono_GP_base & Loi_Etat_Mono_GP_base::self_cast (Objet_U & r) [static]
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 27 of file Loi_Etat_Mono_GP_base.cpp.
Member Data Documentation
const Type_info Loi_Etat_Mono_GP_base::info_obj [static]
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_GP_QC, and Loi_Etat_GP_WC.
Definition at line 43 of file Loi_Etat_Mono_GP_base.h.
Champ Loi_Etat_Mono_GP_base::rho_constant_pour_debug_ [protected]
Definition at line 45 of file Loi_Etat_Mono_GP_base.h.
Referenced by Loi_Etat_GP_QC::calculer_masse_volumique(), Loi_Etat_GP_WC::readOn(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Mono_GP_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Mono_GP_base.cpp