TRUST: Frottement_interfacial_bulles Class Reference
Frottement_interfacial_bulles Class Reference
classe Frottement_interfacial_bulles
coefficients de frottement interfacial d'un ecoulement a bulles
parametres (a lire dans les Op_FI_*_bulles) :
- r_bulle_ -> rayon de bulle
- C_d_ -> coefficient de friction
#include <Frottement_interfacial_bulles.h>
Public Member Functions
Frottement_interfacial_bulles ()
~Frottement_interfacial_bulles ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void coefficient (const DoubleTab &alpha, const DoubleTab &p, const DoubleTab &T, const DoubleTab &rho, const DoubleTab &mu, double Dh, const DoubleTab &ndv, DoubleTab &coeff) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Frottement_interfacial_bulles & self_cast (Objet_U &)
static const
Frottement_interfacial_bulles & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double r_bulle_
double C_d_
Detailed Description
classe Frottement_interfacial_bulles
coefficients de frottement interfacial d'un ecoulement a bulles
parametres (a lire dans les Op_FI_*_bulles) :
- r_bulle_ -> rayon de bulle
- C_d_ -> coefficient de friction
Definition at line 37 of file Frottement_interfacial_bulles.h.
Constructor & Destructor Documentation
Frottement_interfacial_bulles::Frottement_interfacial_bulles ()
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
Frottement_interfacial_bulles::~Frottement_interfacial_bulles ()
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
Member Function Documentation
void Frottement_interfacial_bulles::coefficient (const DoubleTab & alpha, const DoubleTab & p, const DoubleTab & T, const DoubleTab & rho, const DoubleTab & mu, double Dh, const DoubleTab & ndv, DoubleTab & coeff) const [virtual]
Implements Frottement_interfacial_base.
Definition at line 41 of file Frottement_interfacial_bulles.cpp.
References C_d_, coeff, DoubleTab::dimension(), and r_bulle_.
{
  int k, l, N = ndv.dimension(0);
  double rho_m = 0;
  for (k = 0; k < N; k++) rho_m += alpha(k) * rho(k);
  for (k = 0; k < N; k++) for (l = 0; l < N; l++) if (l != k)
        coeff(k, l, 0) = (coeff(k, l, 1) = 1. / 8 * C_d_ * 3 * alpha(k) * alpha(l) / r_bulle_ * rho_m) * ndv(k, l);
}
Objet_U * Frottement_interfacial_bulles::cree_instance () [static]
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
int Frottement_interfacial_bulles::duplique () const [virtual]
Implements Frottement_interfacial_base.
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
const Type_info * Frottement_interfacial_bulles::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
const Type_info * Frottement_interfacial_bulles::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
Sortie & Frottement_interfacial_bulles::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 27 of file Frottement_interfacial_bulles.cpp.
{
  return os;
}
Entree & Frottement_interfacial_bulles::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 32 of file Frottement_interfacial_bulles.cpp.
References Param::ajouter(), C_d_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), r_bulle_, and Param::REQUIRED.
{
  Param param(que_suis_je());
  param.ajouter("rayon_bulle", &r_bulle_, Param::REQUIRED);
  param.ajouter("coeff_derive", &C_d_, Param::REQUIRED);
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Frottement_interfacial_bulles & Frottement_interfacial_bulles::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Frottement_interfacial_base.
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
Frottement_interfacial_bulles & Frottement_interfacial_bulles::self_cast (Objet_U & r) [static]
Reimplemented from Frottement_interfacial_base.
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
unsigned Frottement_interfacial_bulles::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Frottement_interfacial_bulles.cpp.
Member Data Documentation
double Frottement_interfacial_bulles::C_d_ [protected]
Definition at line 45 of file Frottement_interfacial_bulles.h.
Referenced by coefficient(), and readOn().
const Type_info Frottement_interfacial_bulles::info_obj [static]
Reimplemented from Frottement_interfacial_base.
Definition at line 39 of file Frottement_interfacial_bulles.h.
double Frottement_interfacial_bulles::r_bulle_ [protected]
Definition at line 45 of file Frottement_interfacial_bulles.h.
Referenced by coefficient(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Frottement_interfacial_bulles.h
src/ThHyd/Multiphase/Correlations/Frottement_interfacial_bulles.cpp