TRUST: Pb_Dilatable_Proto Class Reference
Pb_Dilatable_Proto Class Reference
#include <Pb_Dilatable_Proto.h>
Protected Member Functions
const Equation_base & equation_impl (int i, const Equation_base &eq1, const Equation_base &eq2) const
Equation_base & equation_impl (int i, Equation_base &eq1, Equation_base &eq2)
int verifier_impl (const Equation_base &eq1, const Equation_base &eq2, const bool is_thermal)
Detailed Description
Definition at line 21 of file Pb_Dilatable_Proto.h.
Member Function Documentation
equation_impl() [1/2]
const Equation_base & Pb_Dilatable_Proto::equation_impl (int i, const Equation_base & eq1, const Equation_base & eq2) const protected
Definition at line 19 of file Pb_Dilatable_Proto.cpp.
{
  if ( !( i==0 || i==1 ) )
    {
      Cerr << "Error in Pb_Dilatable_Proto::equation() : Wrong number of equation !" << finl;
      Process::exit();
    }
  return (i == 0) ? eq1 : eq2;
}
References Cerr, Process::exit(), and finl.
Referenced by Pb_Hydraulique_Melange_Binaire_QC::equation(), Pb_Thermohydraulique_QC::equation(), Pb_Hydraulique_Melange_Binaire_WC::equation(), and Pb_Thermohydraulique_WC::equation().
equation_impl() [2/2]
Equation_base & Pb_Dilatable_Proto::equation_impl (int i, Equation_base & eq1, Equation_base & eq2) protected
Definition at line 29 of file Pb_Dilatable_Proto.cpp.
{
  if ( !( i==0 || i==1 ) )
    {
      Cerr << "Error in Pb_Dilatable_Proto::equation() : Wrong number of equation !" << finl;
      Process::exit();
    }
  return (i == 0) ? eq1 : eq2;
}
References Cerr, Process::exit(), and finl.
verifier_impl()
int Pb_Dilatable_Proto::verifier_impl (const Equation_base & eq1, const Equation_base & eq2, const bool is_thermal) protected
Definition at line 39 of file Pb_Dilatable_Proto.cpp.
{
  const Zone_Cl_dis& zone_Cl_1 = eq1.zone_Cl_dis(), zone_Cl_2 = eq2.zone_Cl_dis();
  return is_thermal == true ? tester_compatibilite_hydr_thermique(zone_Cl_1,zone_Cl_2) :
         tester_compatibilite_hydr_fraction_massique(zone_Cl_1, zone_Cl_2);
}
References tester_compatibilite_hydr_fraction_massique(), tester_compatibilite_hydr_thermique(), and Equation_base::zone_Cl_dis().
Referenced by Pb_Hydraulique_Melange_Binaire_QC::verifier(), Pb_Thermohydraulique_QC::verifier(), Pb_Hydraulique_Melange_Binaire_WC::verifier(), and Pb_Thermohydraulique_WC::verifier().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Problems/Pb_Dilatable_Proto.h
src/ThHyd/Dilatable/Common/Problems/Pb_Dilatable_Proto.cpp