TRUST: Echange_externe_impose_H Class Reference
Echange_externe_impose_H Class Reference
Classe Echange_externe_impose_H:
Cette classe represente le cas particulier de la classe
Echange_externe_impose pour une equation en enthalpie..
#include <Echange_externe_impose_H.h>
Public Member Functions
Echange_externe_impose_H ()
~Echange_externe_impose_H ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void completer ()
Complete les conditions aux limites.
int compatible_avec_eqn (const Equation_base &) const
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique_H (thermique avec inconnue = enthalpie)
double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Echange_externe_impose_H & self_cast (Objet_U &)
static const
Echange_externe_impose_H & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Protected Attributes
Ref_Fluide_Dilatable_base le_fluide
Detailed Description
Classe Echange_externe_impose_H:
Cette classe represente le cas particulier de la classe
Echange_externe_impose pour une equation en enthalpie..
Definition at line 39 of file Echange_externe_impose_H.h.
Constructor & Destructor Documentation
Echange_externe_impose_H::Echange_externe_impose_H ()
Definition at line 28 of file Echange_externe_impose_H.cpp.
Echange_externe_impose_H::~Echange_externe_impose_H ()
Definition at line 28 of file Echange_externe_impose_H.cpp.
Member Function Documentation
int Echange_externe_impose_H::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique_H (thermique avec inconnue = enthalpie)
Returns:
int
Signification: valeur booleenne, 1 si compatible 0 sinon
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 186 of file Echange_externe_impose_H.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Thermique="Thermique_H";
  if ( (dom_app==Thermique))
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
void Echange_externe_impose_H::completer (void) [virtual]
Complete les conditions aux limites.
Reimplemented from Cond_lim_base.
Definition at line 84 of file Echange_externe_impose_H.cpp.
References le_fluide, Cond_lim_base::ma_zone_cl_dis, Cond_lim_base::modifier_val_imp, and ref_cast.
{
  Echange_impose_base::completer();
  le_fluide = ref_cast(Fluide_Dilatable_base,ma_zone_cl_dis->equation().milieu());
  modifier_val_imp = 1;
}
Objet_U * Echange_externe_impose_H::cree_instance () [static]
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
int Echange_externe_impose_H::duplique () const [virtual]
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
const Type_info * Echange_externe_impose_H::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
const Type_info * Echange_externe_impose_H::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
Sortie & Echange_externe_impose_H::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 44 of file Echange_externe_impose_H.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Echange_externe_impose_H::readOn (Entree & s) [protected, virtual]
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_externe_impose.
Definition at line 65 of file Echange_externe_impose_H.cpp.
{
  return Echange_externe_impose::readOn(s) ;
}
Echange_externe_impose_H & Echange_externe_impose_H::self_cast (Objet_U & r) [static]
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
const Echange_externe_impose_H & Echange_externe_impose_H::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
const Champ_front& Echange_externe_impose_H::T_ext () const [inline]
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
Returns:
Champ_front&
Signification: le champ T_ext de temperature imposee a la frontiere
Contraintes: reference constante
Reimplemented from Echange_impose_base.
Definition at line 52 of file Echange_externe_impose_H.h.
References Cond_lim_base::le_champ_front.
{ return le_champ_front; }
double Echange_externe_impose_H::T_ext (int i) const [virtual]
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
Returns:
double
Signification:
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 107 of file Echange_externe_impose_H.cpp.
References Process::abort(), Cerr, DoubleTab::dimension(), finl, Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, DoubleVect::size(), and Champ_front::valeurs().
{
  if (le_champ_front.valeurs().size()==1)
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(0,0));
      else
        return le_champ_front(0,0);
    }
  else if (le_champ_front.valeurs().dimension(1)==1)
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(i,0));
      else
        return le_champ_front(i,0);
    }
  else
    Cerr << "Echange_impose_base::T_ext erreur" << finl;
  abort();
  return 0.;
}
Champ_front& Echange_externe_impose_H::T_ext () [inline]
Renvoie le champ T_ext de temperature imposee a la frontiere.
Returns:
Champ_front&
Signification: le champ T_ext de temperature imposee a la frontiere
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 51 of file Echange_externe_impose_H.h.
References Cond_lim_base::le_champ_front.
{ return le_champ_front; }
double Echange_externe_impose_H::T_ext (int i, int j) const [virtual]
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
Returns:
double
Signification:
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 150 of file Echange_externe_impose_H.cpp.
References DoubleTab::dimension(), Cond_lim_base::le_champ_front, le_fluide, Cond_lim_base::modifier_val_imp, and Champ_front::valeurs().
{
  if (le_champ_front.valeurs().dimension(0)==1)
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(0,j));
      else
        return le_champ_front(0,j);
    }
  else
    {
      if (modifier_val_imp==1)
        return le_fluide->calculer_H(le_champ_front(i,j));
      else
        return le_champ_front(i,j);
    }
}
unsigned Echange_externe_impose_H::taille_memoire () const [virtual]
Reimplemented from Echange_externe_impose.
Definition at line 28 of file Echange_externe_impose_H.cpp.
Member Data Documentation
const Type_info Echange_externe_impose_H::info_obj [static]
Reimplemented from Echange_externe_impose.
Definition at line 41 of file Echange_externe_impose_H.h.
Ref_Fluide_Dilatable_base Echange_externe_impose_H::le_fluide [protected]
Definition at line 55 of file Echange_externe_impose_H.h.
Referenced by completer(), and T_ext().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Cond_Lim/Echange_externe_impose_H.h
src/ThHyd/Dilatable/Common/Cond_Lim/Echange_externe_impose_H.cpp