TRUST: Champ_front_contact_VEF Class Reference
Champ_front_contact_VEF Class Reference
classe Champ_front_contact_VEF
Permet le couplage scalaire (temperature ou concentration) entre problemes en calculant
la valeur a la paroi qui permet d'egaliser les flux.
calculer_coeffs_echange stocke grad_num_local et grad_fro_local tels que (aux signes pres?)
flux = grad_num_local + Scal_paroi*grad_fro_local
mettre_a_jour recupere les grad* d'en face et calcule Scal_paroi de
facon a egaliser les flux.
#include <Champ_front_contact_VEF.h>
Public Member Functions
Champ_front_contact_VEF ()
~Champ_front_contact_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
void mettre_a_jour (double temps) override
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
void calculer_coeffs_echange (double temps) override
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
void creer (const Nom &, const Nom &, const Nom &, const Nom &, const Motcle &)
const Champ_Inc_base & inconnue () const
const Equation_base & equation () const
const Zone_dis_base & zone_dis () const
const Zone_Cl_dis_base & zone_Cl_dis () const
const Frontiere_dis_base & front_dis () const
void associer_ch_inc_base (const Champ_Inc_base &)
const Nom & nom_bord_oppose () const
const Milieu_base & milieu () const
virtual void calcul_grads_transf (double temps)
virtual void calcul_grads_locaux (double temps)
void calcul_coeff_amort ()
void recupere_gradients_autre_pb (const Front_VF &, DoubleVect &, DoubleVect &)
DoubleVect & trace_face_raccord (const Front_VF &fr_vf, const DoubleVect &y, DoubleVect &x)
void remplir_connect_bords ()
void verifier_scalaire_bord (double temps)
void associer_front_vf_et_ch_front_autre_pb ()
void connectivity_failed (const Zone_VEF &, int &, int &, const Zone_VEF &, int &, int &, Nom &, Nom &)
void remplir_faces_coin ()
void remplir_elems_voisin_bord ()
void test_faces_coin ()
DoubleVect & set_gradient_num_local ()
const DoubleVect & get_gradient_num_local () const
DoubleVect & set_gradient_fro_local ()
const DoubleVect & get_gradient_fro_local () const
DoubleVect & set_gradient_num_transf ()
const DoubleVect & get_gradient_num_transf () const
DoubleVect & set_gradient_fro_transf ()
const DoubleVect & get_gradient_fro_transf () const
DoubleVect & set_coeff_amort_num ()
const DoubleVect & get_coeff_amort_num () const
DoubleVect & set_coeff_amort_denum ()
const DoubleVect & get_coeff_amort_denum () const
const IntVect & get_elems_voisin_bord () const
const Nom & get_nom_bord1 () const
const IntVect & get_connect_bords () const
const IntVect & get_faces_coin () const
Public Member Functions inherited from Ch_front_var_instationnaire_dep
Ch_front_var_instationnaire_dep ()
~Ch_front_var_instationnaire_dep ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Champ_front_base & affecter_ (const Champ_front_base &ch) override
Public Member Functions inherited from Champ_front_var_instationnaire
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front_contact_VEF & self_cast (Objet_U &)
static const Champ_front_contact_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Ch_front_var_instationnaire_dep
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ch_front_var_instationnaire_dep & self_cast (Objet_U &)
static const Ch_front_var_instationnaire_dep & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var_instationnaire
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Ch_front_var_instationnaire_dep
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var_instationnaire
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int is_conduction
Est-on dans un probleme conduction ?
Ref_Champ_Inc_base l_inconnue1
Ref_Champ_Inc_base l_inconnue2
Ref_Champ_Inc_base l_inconnue
Ref_Front_VF fr_vf_autre_pb
Ref_Champ_front_contact_VEF ch_fr_autre_pb
Nom nom_bord1
Nom nom_bord2
Nom nom_bord
Nom nom_pb1
Nom nom_pb2
IntVect connect_bords
Tableau de connectivite des faces de bord des deux bord conjugues (en sequentiel)
int connect_est_remplit
DoubleVect gradient_num_local
DoubleVect gradient_fro_local
DoubleVect gradient_num_transf
DoubleVect gradient_fro_transf
DoubleVect Scal_moy
DoubleVect coeff_amort_num
DoubleVect coeff_amort_denum
IntVect elems_voisin_bord_
IntVect faces_coin
int verification_faces_coin
Protected Attributes inherited from Champ_front_var_instationnaire
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_contact_VEF
Permet le couplage scalaire (temperature ou concentration) entre problemes en calculant
la valeur a la paroi qui permet d'egaliser les flux.
calculer_coeffs_echange stocke grad_num_local et grad_fro_local tels que (aux signes pres?)
flux = grad_num_local + Scal_paroi*grad_fro_local
mettre_a_jour recupere les grad* d'en face et calcule Scal_paroi de
facon a egaliser les flux.
Definition at line 47 of file Champ_front_contact_VEF.h.
Constructor & Destructor Documentation
Champ_front_contact_VEF()
Champ_front_contact_VEF::Champ_front_contact_VEF ()
Definition at line 41 of file Champ_front_contact_VEF.cpp.
~Champ_front_contact_VEF()
Champ_front_contact_VEF::~Champ_front_contact_VEF ()
Definition at line 41 of file Champ_front_contact_VEF.cpp.
Member Function Documentation
affecter_()
Champ_front_base & Champ_front_contact_VEF::affecter_ (const Champ_front_base & ch) override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 189 of file Champ_front_contact_VEF.cpp.
{
  return *this;
}
associer_ch_inc_base()
void Champ_front_contact_VEF::associer_ch_inc_base (const Champ_Inc_base & inco)
Definition at line 182 of file Champ_front_contact_VEF.cpp.
{
  l_inconnue = inco;
}
References l_inconnue.
Referenced by calcul_grads_locaux(), completer(), and remplir_connect_bords().
associer_front_vf_et_ch_front_autre_pb()
void Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb ()
Definition at line 542 of file Champ_front_contact_VEF.cpp.
{
  const Champ_Inc_base& temp_autre = l_inconnue2.valeur();
  const Equation_base& eqn = temp_autre.equation();
  const Zone_Cl_dis_base& zcl = eqn.zone_Cl_dis().valeur();
  int num_cl;
  for (num_cl = 0; num_cl<zcl.nb_cond_lim(); num_cl++)
    {
      const Cond_lim_base& la_cl = zcl.les_conditions_limites(num_cl);
      const Nom& le_nom_cl = la_cl.frontiere_dis().le_nom();
      if (le_nom_cl == nom_bord2)
        {
          if (sub_type(Champ_front_contact_VEF,la_cl.champ_front().valeur()))
            {
              ch_fr_autre_pb = ref_cast(Champ_front_contact_VEF,la_cl.champ_front().valeur());
// Test de securite pour verifier que l'on a bien saisit le champ
// front_contact_VEF.
              if (ch_fr_autre_pb->nom_pb1 == nom_pb1)
                if (!(sub_type(Champ_front_contact_fictif_VEF,(*this))))
                  {
                    Cerr<<"Attention, erreur lors de la lecture du Champ_Front_Contact_VEF"<<finl;
                    Cerr<<"La syntaxe a utiliser est : nom_pb_local nom_bord_local nom_pb_distant nom_bord_distant"<<finl;
                    exit();
                  }
              fr_vf_autre_pb=ref_cast(Front_VF, la_cl.frontiere_dis());
            }
        }
    }
}
References Cerr, ch_fr_autre_pb, Cond_lim_base::champ_front(), MorEqn::equation(), Process::exit(), finl, fr_vf_autre_pb, Cond_lim_base::frontiere_dis(), l_inconnue2, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), nom_bord2, nom_pb1, ref_cast, sub_type, Deriv_Champ_front_base::valeur(), Ref_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Equation_base::zone_Cl_dis().
Referenced by initialiser().
calcul_coeff_amort()
void Champ_front_contact_VEF::calcul_coeff_amort ()
Definition at line 500 of file Champ_front_contact_VEF.cpp.
{
  const Zone_VEF& la_zone_dis=ref_cast(Zone_VEF, l_inconnue1->equation().zone_dis().valeur());
  int rang_front = la_zone_dis.rang_frontiere(nom_bord1);
  const Front_VF& la_front_vf=ref_cast(Front_VF, la_zone_dis.frontiere_dis(rang_front));
  const DoubleVect& vol = la_zone_dis.volumes();
  const IntTab& face_voisins = la_zone_dis.face_voisins();
  const DoubleTab& face_normales = la_zone_dis.face_normales();
  const Milieu_base& le_milieu = l_inconnue1->equation().milieu();
  int nb_faces = la_front_vf.nb_faces();
  int ndeb = la_front_vf.num_premiere_face();
  int fac_front;
  for (fac_front = 0; fac_front<nb_faces; fac_front++)
    {
      int fac = fac_front + ndeb;
      int num = face_voisins(fac,0);
      if (num < 0) num = face_voisins(fac,1);
// calcul de la surface de la face courante
      double ratio = 0.;
      for (int i=0; i<dimension; i++) ratio += (face_normales(fac,i) * face_normales(fac,i));
      ratio = sqrt(ratio);
      double alpha;
      if(sub_type(Champ_Uniforme,le_milieu.diffusivite().valeur()))
        alpha=le_milieu.diffusivite()(0,0);
      else
        {
          const DoubleTab& tab_alpha = le_milieu.diffusivite().valeurs();
          alpha=tab_alpha(num);
        }
      double volume = vol(num);
      coeff_amort_num(fac_front) = volume/ratio;
      coeff_amort_denum(fac_front) = (alpha*ratio)/volume;
    }
}
References coeff_amort_denum, coeff_amort_num, Milieu_base::diffusivite(), Objet_U::dimension, MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VF::frontiere_dis(), l_inconnue1, Equation_base::milieu(), Front_VF::nb_faces(), nom_bord1, Front_VF::num_premiere_face(), Zone_dis_base::rang_frontiere(), ref_cast, sub_type, Deriv_Champ_Don_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don::valeurs(), Zone_VF::volumes(), and Equation_base::zone_dis().
calcul_grads_locaux()
void Champ_front_contact_VEF::calcul_grads_locaux (double temps) virtual
Definition at line 205 of file Champ_front_contact_VEF.cpp.
{
// collection information problem local
  nom_bord = nom_bord1 ;
  associer_ch_inc_base(l_inconnue1.valeur()) ;
  const Champ_Inc_base& inco = l_inconnue.valeur();
  const DoubleTab& inco_valeurs = l_inconnue->valeurs(temps);
// const Equation_base& eq=l_inconnue->equation();
  assert (nom_bord != "??") ;
  const Zone_VEF& la_zone_dis=ref_cast(Zone_VEF, zone_dis());
  const Front_VF& la_front_vf=ref_cast(Front_VF, front_dis());
  const DoubleVect& vol = la_zone_dis.volumes();
  const IntTab& face_voisins = la_zone_dis.face_voisins();
  const IntTab& elem_faces = la_zone_dis.elem_faces();
  const DoubleTab& face_normales = la_zone_dis.face_normales();
  int ndeb = la_front_vf.num_premiere_face();
  const Milieu_base& le_milieu = milieu();
  DoubleTab coeff_lam, coeff_turb;
// On test si le probleme local est un probleme thermohydraulique turbulent
// Et si le modele de turbulence utilise necessite l'utilisation d'une loi de paroi
  int ind_loi_paroi=0;
  DoubleVect d_equiv;
// DoubleTab positions_Pf;
  if (!sub_type(Convection_Diffusion_Concentration,inco.equation()))
    coeff_lam = le_milieu.conductivite().valeurs();
  else
    coeff_lam = ref_cast(Constituant,le_milieu).diffusivite_constituant().valeurs();
  int dim = coeff_lam.nb_dim();
  const RefObjU& mod = inco.equation().get_modele(TURBULENCE);
  if (mod.non_nul())
    {
      const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,mod.valeur());
      coeff_turb = mod_turb_scal.conductivite_turbulente().valeurs();
      const Turbulence_paroi_scal& loipar = mod_turb_scal.loi_paroi();
      if (loipar.non_nul())
        {
          if( loipar.valeur().use_equivalent_distance() )
            {
              ind_loi_paroi=1;
// const Paroi_scal_hyd_base_VEF& paroi_vef = ref_cast(Paroi_scal_hyd_base_VEF,loipar.valeur());
              int nb_faces = la_front_vf.nb_faces();
              d_equiv.resize(nb_faces);
// Recherche du bord correspondant
              int i_bord=-1;
              for (int n_bord=0; n_bord<la_zone_dis.zone().nb_front_Cl(); n_bord++)
                if (la_zone_dis.front_VF(n_bord).le_nom() == la_front_vf.le_nom()) i_bord=n_bord;
// Copie des donnees d'un bord dans les tableaux locaux temporaires positions_Pf et d_equiv
              for (int ind_face=0; ind_face<nb_faces; ind_face++)
                {
// d_equiv(ind_face) = paroi_vef.equivalent_distance(i_bord,ind_face);
                  d_equiv(ind_face) = loipar.valeur().equivalent_distance(i_bord,ind_face);
                }
            }
        }
    }
  int i, j, num, fac_glob ;
  int fac_front, fac_loc;
  double coeff;
  int signe;
  double surface_pond, surface_face;
  int nb_faces_elem = la_zone_dis.zone().nb_faces_elem();
  const DoubleTab& face_normale = la_zone_dis.face_normales();
// calcul de grad_num_local et grad_fro_local
  int nb_faces = la_front_vf.nb_faces();
  for ( fac_front = 0 ; fac_front<nb_faces ; fac_front++)
    {
      gradient_num_local(fac_front) = 0.;
      gradient_fro_local(fac_front) = 0.;
      fac_glob = fac_front +  ndeb ;
      num = face_voisins(fac_glob,0);
      if (num < 0 ) num = face_voisins(fac_glob,1);
      if(dim!=1) coeff = coeff_lam(0,0) ;
      else       coeff = coeff_lam(num) ;
// GF PQ
// ajout de lambda_t cote fluide egalite des flux entre lambda_s *DT_s/dy =(lambda+lambda_t)_f *DT_f/dy
      if (mod.non_nul())
        coeff += coeff_turb(num);
      Scal_moy(fac_front) = 0. ;
      double ratio = 0. ;
      for (i=0; i<dimension; i++) ratio += (face_normales(fac_glob,i) * face_normales(fac_glob,i));
      ratio = sqrt(ratio) ;
      int fac;
      surface_face=la_zone_dis.face_surfaces(fac_glob);
// Calcul de la temperature moyenne dans la maille
      for (i=0; i<nb_faces_elem; i++)
        {
// On ne tient pas compte de la temperature de paroi
// pour calculer la temperature moyenne dans la maille.
          if ( (j= elem_faces(num,i)) != fac_glob )
            {
// On pondere la moyenne par la surface
              surface_pond = 0.;
              for (int kk=0; kk<dimension; kk++)
                surface_pond -= (face_normale(j,kk)*la_zone_dis.oriente_normale(j,num)*face_normale(fac_glob,kk)*
                                 la_zone_dis.oriente_normale(fac_glob,num))/(surface_face*surface_face);
              Scal_moy(fac_front) += inco_valeurs(j)*surface_pond;
            }
        }
      for (fac=0; fac<dimension+1; fac++)
        for (i=0; i<dimension; i++)
          {
            fac_loc = elem_faces(num,fac) ;
            signe = la_zone_dis.oriente_normale(fac_loc, num);
            if (fac_loc != fac_glob) gradient_num_local(fac_front) += (signe * face_normales(fac_glob,i) / ratio *
                                                                         face_normales(fac_loc,i)*inco_valeurs(fac_loc)) ;
            else                 gradient_fro_local(fac_front) += (signe * face_normales(fac_loc,i) / ratio *
                                                                     face_normales(fac_loc,i)) ;
          }
      gradient_num_local(fac_front) *= (coeff / vol(num));
      gradient_fro_local(fac_front) *= (coeff / vol(num));
// On recalcul gradient_num_local et gradient_fro_local si l'ecoulement dans le domaine local est turbulent
      if (ind_loi_paroi==1)
        {
          gradient_num_local(fac_front) = 0.;
          gradient_fro_local(fac_front) = 0.;
          gradient_num_local(fac_front) = -Scal_moy(fac_front);
          double coeff_equiv = coeff/d_equiv(fac_front);
          gradient_num_local(fac_front) *=coeff_equiv;
          gradient_fro_local(fac_front) = coeff_equiv;
        }
    }
}
References associer_ch_inc_base(), coeff, Milieu_base::conductivite(), Modele_turbulence_scal_base::conductivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Turbulence_paroi_scal_base::equivalent_distance(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), front_dis(), Zone_VF::front_VF(), Equation_base::get_modele(), gradient_fro_local, gradient_num_local, l_inconnue, l_inconnue1, Frontiere_dis_base::le_nom(), Modele_turbulence_scal_base::loi_paroi(), milieu(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone::nb_faces_elem(), nom_bord, nom_bord1, O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Zone_VEF::oriente_normale(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Scal_moy, sub_type, TURBULENCE, Turbulence_paroi_scal_base::use_equivalent_distance(), Ref_Champ_Inc_base::valeur(), Ref_Objet_U::valeur(), Deriv_Turbulence_paroi_scal_base::valeur(), Champ_Don::valeurs(), Champ_Fonc::valeurs(), Champ_Inc_base::valeurs(), Zone_VF::volumes(), Zone_dis_base::zone(), and zone_dis().
Referenced by calculer_coeffs_echange().
calcul_grads_transf()
void Champ_front_contact_VEF::calcul_grads_transf (double temps) virtual
Definition at line 195 of file Champ_front_contact_VEF.cpp.
{
// Dans le cas de raccords homogenes, c'est a dire parfaitement coincidents
// au niveau du maillage, gradient_num_local = gradient_num_transf et
// gradient_fro_local = gradient_fro_transf
  gradient_num_transf.copy_array(gradient_num_local);
  gradient_fro_transf.copy_array(gradient_fro_local);
}
References TRUSTArray< _TYPE_ >::copy_array(), gradient_fro_local, gradient_fro_transf, gradient_num_local, and gradient_num_transf.
Referenced by calculer_coeffs_echange().
calculer_coeffs_echange()
void Champ_front_contact_VEF::calculer_coeffs_echange (double temps) override virtual
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
Reimplemented from Champ_front_base.
Definition at line 445 of file Champ_front_contact_VEF.cpp.
{
// Calcul de la temperature imposee
  calcul_grads_locaux(temps);
  calcul_grads_transf(temps);
}
References calcul_grads_locaux(), and calcul_grads_transf().
Referenced by initialiser().
completer()
void Champ_front_contact_VEF::completer (void) override virtual
Reimplemented from Champ_front_base.
Definition at line 72 of file Champ_front_contact_VEF.cpp.
{
// Check/initialize Raccord boundaries in parallel:
  if (Process::nproc()>1)
    {
      nom_bord = nom_bord2;
      associer_ch_inc_base(l_inconnue2.valeur()) ;
      const Zone_dis_base& zone_dis_opposee = front_dis().zone_dis();
      const Zone_dis_base& zone_dis_locale = frontiere_dis().zone_dis();
      const Frontiere& frontiere_opposee = front_dis().frontiere();
      const Frontiere& frontiere_locale = frontiere_dis().frontiere();
      if (!sub_type(Raccord_distant_homogene, frontiere_opposee))
        {
          const Nom& nom_domaine_oppose = zone_dis_opposee.zone().domaine().le_nom();
          Cerr << "Error, the boundary " << frontiere_opposee.le_nom() << " should be a Raccord." << finl;
          Cerr << "Add in your data file between the definition and the partition of the domain " << nom_domaine_oppose << " :" << finl;
          Cerr << "Modif_bord_to_raccord " << nom_domaine_oppose << " " << frontiere_opposee.le_nom() << finl;
          exit();
        }
      Raccord_distant_homogene& raccord_distant = ref_cast_non_const(Raccord_distant_homogene, frontiere_opposee);
      raccord_distant.initialise(frontiere_locale, zone_dis_locale, zone_dis_opposee);
    }
}
References associer_ch_inc_base(), Cerr, Zone::domaine(), Process::exit(), finl, front_dis(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Raccord_distant_homogene::initialise(), l_inconnue2, Domaine::le_nom(), Frontiere::le_nom(), nom_bord, nom_bord2, Process::nproc(), ref_cast_non_const, sub_type, Ref_Champ_Inc_base::valeur(), Zone_dis_base::zone(), and Frontiere_dis_base::zone_dis().
connectivity_failed()
void Champ_front_contact_VEF::connectivity_failed (const Zone_VEF & zvef1, int & nb_faces1, int & ndeb1, const Zone_VEF & zvef2, int & nb_faces2, int & ndeb2, Nom & fichier, Nom & fichier_med)
< nombre de faces par element
Definition at line 951 of file Champ_front_contact_VEF.cpp.
{
  const IntTab& face_voisin2 = zvef2.face_voisins();
  const IntTab& elem_faces2  = zvef2.elem_faces();
  int nb_elem2 = zvef2.nb_elem();
  const DoubleTab& xv1  = zvef1.xv();
  int nbf = dimension+1; //!< nombre de faces par element
  int fac,elem,face1,face2,elem2,trouve;
  int j;
// Creation du champ P0
  Champ_Fonc_P0_VEF chp;
  chp.associer_zone_dis_base(zvef2);
  chp.dimensionner(nb_elem2,1);
  chp.fixer_nb_comp(1);
  chp.nommer("Raccord_Homard");
  DoubleTab& chp_val = chp.valeurs();
  chp_val=0.;
  for (fac=0; fac<nb_faces1; fac++)
    {
      face1=fac+ndeb1;
      elem2=-1;
      if (dimension==2)  elem2 = zvef2.zone().chercher_elements(xv1(face1,0),xv1(face1,1));
      else                 elem2 = zvef2.zone().chercher_elements(xv1(face1,0),xv1(face1,1),xv1(face1,2));
      if(elem2==-1)
        {
          Cerr << "Probleme dans la recherche de l'element associe !" << finl;
          exit();
        }
      chp_val(elem2)++;
    }
//
// Ecriture du fichier Connectivity_failed pour decoupage
// a l'aide de l'interprete  Decouper_Bord_coincident
//
  SFichier fic(fichier);
  fic << nb_faces2 << finl;
  fic << nb_faces1 << finl;
  for (fac=0; fac<nb_faces2; fac++)
    {
      face2=fac+ndeb2;
      elem2=face_voisin2(face2,0);
      if (elem2==-1) elem2=face_voisin2(face2,1);
// recherche de l'indice locale de la face
      trouve=0;
      for(j=0; j<nbf; j++)
        if(face2==elem_faces2(elem2,j))
          {
            trouve=1;
            break;
          }
      if(trouve==0)
        {
          Cerr << "Probleme dans la recherche de l'indice local !" << finl;
          exit();
        }
      fic << chp_val(elem2) << " " << fac << " " << elem2 << " " << j << finl;
    }
  fic <<(int) -1;
// pour forcer l ecriture
  fic.close();
//
// Ecriture du fichier MED pour decoupage suivant HOMARD
//
// renormalisation de chp_val
  for (elem=0; elem<nb_elem2; elem++)
    {
      if(chp_val(elem)==(2*(dimension-1))) chp_val(elem)=1;
      else                                   chp_val(elem)=0;
    }
  Nom bis(fichier_med);
  bis+="_index";
  fichier_med.prefix(".med");
  const Domaine& dom2 = zvef2.zone().domaine();
  Noms unites_(1);
  unites_[0]="1";
  Noms nom_compos(1);
  nom_compos[0]=chp.le_nom();
  Format_Post_Med post;
  post.initialize_by_default(fichier_med);
  post.ecrire_domaine(dom2,1);
  post.ecrire_champ(dom2,unites_,nom_compos,-1,0., 0., chp.le_nom(), dom2.le_nom(), Motcle("elem"), "scalar",chp_val);
  post.ecrire_champ(dom2,unites_,nom_compos,-1,0., 0., chp.le_nom(), dom2.le_nom(), Motcle("elem"), "scalar",chp_val);
}
References Champ_Fonc_P0_base::associer_zone_dis_base(), Cerr, Zone::chercher_elements(), Sortie_Fichier_base::close(), Objet_U::dimension, Champ_Don_base::dimensionner(), Zone::domaine(), Format_Post_Med::ecrire_champ(), Format_Post_Med::ecrire_domaine(), Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), finl, Field_base::fixer_nb_comp(), Format_Post_Med::initialize_by_default(), Field_base::le_nom(), Domaine::le_nom(), Zone_dis_base::nb_elem(), Field_base::nommer(), Nom::prefix(), Champ_Don_base::valeurs(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by remplir_connect_bords().
cree_instance()
Objet_U * Champ_front_contact_VEF::cree_instance () static
Definition at line 41 of file Champ_front_contact_VEF.cpp.
creer()
void Champ_front_contact_VEF::creer (const Nom & nompb1, const Nom & nom1, const Nom & nompb2, const Nom & nom2, const Motcle & nom_inco)
Definition at line 142 of file Champ_front_contact_VEF.cpp.
{
  nom_bord1 = nom1;
  nom_bord2 = nom2;
  Nom nom_inco1, nom_inco2;
  nom_inco1 = nom_inco;
  nom_inco2 = nom_inco;
  REF(Champ_base) rch1;
  Probleme_base& pb1=ref_cast(Probleme_base, Interprete::objet(nompb1));
  if (!sub_type(Pb_Conduction,pb1))
    if (pb1.equation(1).inconnue().le_nom()!="temperature")
      nom_inco1 = "concentration";
  rch1 = pb1.get_champ(nom_inco1);
  l_inconnue1=ref_cast(Champ_Inc_base, rch1.valeur()) ;
  REF(Champ_base) rch2 ;
  Probleme_base& pb2=ref_cast(Probleme_base, Interprete::objet(nompb2));
  if (!sub_type(Pb_Conduction,pb2))
    if (pb2.equation(1).inconnue().le_nom()!="temperature")
      nom_inco2 = "concentration";
  rch2 = pb2.get_champ(nom_inco2);
  l_inconnue2=ref_cast(Champ_Inc_base, rch2.valeur()) ;
  if (nom_inco1!=nom_inco2)
    {
      Cerr<<"Une condition limite de contact est mal specifiee"<<finl;
      Cerr<<"Il existe une incoherence sur l'inconnue mise en jeu de part et d'autre de la frontiere de contact"<<finl;
      exit();
    }
}
References Cerr, Probleme_base::equation(), Process::exit(), finl, Probleme_base::get_champ(), Equation_base::inconnue(), l_inconnue1, l_inconnue2, O_U_Ptr::le_nom(), nom_bord1, nom_bord2, Interprete::objet(), REF, ref_cast, and sub_type.
Referenced by readOn().
duplique()
int Champ_front_contact_VEF::duplique () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 41 of file Champ_front_contact_VEF.cpp.
equation()
const Equation_base & Champ_front_contact_VEF::equation () const
Definition at line 465 of file Champ_front_contact_VEF.cpp.
{
  if (l_inconnue.non_nul()==0)
    {
      Cerr << "\nError in Champ_front_contact_VEF::equation() : not able to return the equation !" << finl;
      Process::exit();
    }
  return inconnue().equation();
}
References Cerr, MorEqn::equation(), Process::exit(), finl, inconnue(), l_inconnue, and O_U_Ptr::non_nul().
Referenced by milieu(), and zone_Cl_dis().
front_dis()
const Frontiere_dis_base & Champ_front_contact_VEF::front_dis () const
Definition at line 494 of file Champ_front_contact_VEF.cpp.
{
  return zone_dis().frontiere_dis(nom_bord);
}
References Zone_dis_base::frontiere_dis(), nom_bord, and zone_dis().
Referenced by calcul_grads_locaux(), and completer().
get_coeff_amort_denum()
const DoubleVect & Champ_front_contact_VEF::get_coeff_amort_denum () const inline
Definition at line 194 of file Champ_front_contact_VEF.h.
{
  return coeff_amort_denum;
}
References coeff_amort_denum.
get_coeff_amort_num()
const DoubleVect & Champ_front_contact_VEF::get_coeff_amort_num () const inline
Definition at line 184 of file Champ_front_contact_VEF.h.
{
  return coeff_amort_num;
}
References coeff_amort_num.
get_connect_bords()
const IntVect & Champ_front_contact_VEF::get_connect_bords () const inline
Definition at line 209 of file Champ_front_contact_VEF.h.
{
  return connect_bords;
}
References connect_bords.
get_elems_voisin_bord()
const IntVect & Champ_front_contact_VEF::get_elems_voisin_bord () const inline
Definition at line 199 of file Champ_front_contact_VEF.h.
{
  return elems_voisin_bord_;
}
References elems_voisin_bord_.
Referenced by remplir_faces_coin().
get_faces_coin()
const IntVect & Champ_front_contact_VEF::get_faces_coin () const inline
Definition at line 214 of file Champ_front_contact_VEF.h.
{
  return faces_coin;
}
References faces_coin.
Referenced by test_faces_coin().
get_gradient_fro_local()
const DoubleVect & Champ_front_contact_VEF::get_gradient_fro_local () const inline
Definition at line 153 of file Champ_front_contact_VEF.h.
{
  return gradient_fro_local;
}
References gradient_fro_local.
get_gradient_fro_transf()
const DoubleVect & Champ_front_contact_VEF::get_gradient_fro_transf () const inline
Definition at line 174 of file Champ_front_contact_VEF.h.
{
  return gradient_fro_transf;
}
References gradient_fro_transf.
Referenced by Champ_front_contact_fictif_VEF::mettre_a_jour().
get_gradient_num_local()
const DoubleVect & Champ_front_contact_VEF::get_gradient_num_local () const inline
Definition at line 143 of file Champ_front_contact_VEF.h.
{
  return gradient_num_local;
}
References gradient_num_local.
get_gradient_num_transf()
const DoubleVect & Champ_front_contact_VEF::get_gradient_num_transf () const inline
Definition at line 164 of file Champ_front_contact_VEF.h.
{
  return gradient_num_transf;
}
References gradient_num_transf.
Referenced by Champ_front_contact_fictif_VEF::mettre_a_jour().
get_info()
const Type_info * Champ_front_contact_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 41 of file Champ_front_contact_VEF.cpp.
get_nom_bord1()
const Nom & Champ_front_contact_VEF::get_nom_bord1 () const inline
Definition at line 204 of file Champ_front_contact_VEF.h.
{
  return nom_bord1;
}
References nom_bord1.
Referenced by remplir_faces_coin(), and test_faces_coin().
inconnue()
const Champ_Inc_base & Champ_front_contact_VEF::inconnue () const
Definition at line 453 of file Champ_front_contact_VEF.cpp.
{
  return l_inconnue.valeur();
}
References l_inconnue, and Ref_Champ_Inc_base::valeur().
Referenced by equation(), and zone_dis().
info()
const Type_info * Champ_front_contact_VEF::info () static
Definition at line 41 of file Champ_front_contact_VEF.cpp.
initialiser()
int Champ_front_contact_VEF::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
< sur instant present
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 96 of file Champ_front_contact_VEF.cpp.
{
  if (!Ch_front_var_instationnaire_dep::initialiser(temps,inco))
    return 0;
// WEC : code repris de calculer_coeffs_echange qui faisait des
// iniialisations au premier pas de temps.
// remplissage du tableau de connectivite des numeros de faces de bord
// entre les deux problemes couples.
  if (connect_est_remplit==0)
    {
      remplir_connect_bords();
      connect_est_remplit = 1;
// Les elems_voisin_bord_ ont ete remplis pour chaque frontiere portant un Champ_Front_contact_VEF
// On peut remplir faces_coin
      remplir_faces_coin();
    }
  verification_faces_coin=0;
// On initialise les references au ch_fr_autre_pb et fr_vf_autre_pb
  associer_front_vf_et_ch_front_autre_pb();
// Dimensionnement des tableaux
  int nb_faces=frontiere_dis().frontiere().nb_faces();
  gradient_num_transf.resize(nb_faces);
  gradient_fro_transf.resize(nb_faces);
  Scal_moy.resize(nb_faces);
  gradient_num_local.resize(nb_faces);
  gradient_fro_local.resize(nb_faces);
  coeff_amort_num.resize(nb_faces);
  coeff_amort_denum.resize(nb_faces);
// Est-on dans le probleme conduction ?
// (utilise en rayo trans et semi_transp => factorisation)
  const Probleme_base& pb = l_inconnue1->equation().probleme();
  if (sub_type(Pb_Conduction,pb))
    is_conduction=1;
  else
    is_conduction=0;
// Initialisation des tableaux de gradients
  calculer_coeffs_echange(temps); //!< sur instant present
  return 1;
}
References associer_front_vf_et_ch_front_autre_pb(), calculer_coeffs_echange(), coeff_amort_denum, coeff_amort_num, connect_est_remplit, MorEqn::equation(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), gradient_fro_local, gradient_fro_transf, gradient_num_local, gradient_num_transf, Ch_front_var_instationnaire_dep::initialiser(), is_conduction, l_inconnue1, Frontiere::nb_faces(), Equation_base::probleme(), remplir_connect_bords(), remplir_faces_coin(), TRUSTVect< _TYPE_ >::resize(), Scal_moy, sub_type, and verification_faces_coin.
mettre_a_jour()
void Champ_front_contact_VEF::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Reimplemented from Champ_front_base.
Definition at line 347 of file Champ_front_contact_VEF.cpp.
{
  if (!verification_faces_coin)
    {
      test_faces_coin();
      verification_faces_coin=1;
    }
  const Frontiere& la_front=la_frontiere_dis->frontiere();
  int nb_faces=la_front.nb_faces();
  DoubleTab& tab=valeurs_au_temps(temps);
// On recupere les coefficients gradient_num_transf et gradient_fro_transf de l'autre probleme
  DoubleVect gradient_num_transf_autre_pb(nb_faces);
  DoubleVect gradient_fro_transf_autre_pb(nb_faces);
  if (!ch_fr_autre_pb.non_nul())
    {
      Cerr << "Attention: Vous utilisez une condition de contact Champ_front_contact_VEF sur le bord " << nom_bord1 << " sur le probleme "<< nom_pb1 <<" " << finl;
      Cerr << "Vous devez avoir un Champ_front_contact_VEF equivalent sur le bord " << nom_bord2 << " du probleme "<<nom_pb2<<" " << finl;
      exit();
    }
  trace_face_raccord(fr_vf_autre_pb.valeur(),ch_fr_autre_pb->gradient_num_transf,gradient_num_transf_autre_pb);
  trace_face_raccord(fr_vf_autre_pb.valeur(),ch_fr_autre_pb->gradient_fro_transf,gradient_fro_transf_autre_pb);
//
//
// gradient_fro_ h
// gradient_num_ -h*T
// Calcul de la temperature imposee
  for (int fac_front=0; fac_front<nb_faces; fac_front++)
    {
      tab(fac_front,0)= -(gradient_num_local(fac_front) + gradient_num_transf_autre_pb(fac_front))
                        / ( gradient_fro_transf_autre_pb(fac_front) + gradient_fro_local(fac_front)) ;
    }
// Verification de la coherence des temperatures de bord calculees
// verifier_scalaire_bord();
}
References Cerr, ch_fr_autre_pb, Process::exit(), finl, fr_vf_autre_pb, Frontiere_dis_base::frontiere(), gradient_fro_local, gradient_fro_transf, gradient_num_local, gradient_num_transf, Champ_front_base::la_frontiere_dis, Frontiere::nb_faces(), nom_bord1, nom_bord2, nom_pb1, nom_pb2, O_U_Ptr::non_nul(), test_faces_coin(), trace_face_raccord(), Ref_Front_VF::valeur(), Champ_front_var_instationnaire::valeurs_au_temps(), and verification_faces_coin.
milieu()
const Milieu_base & Champ_front_contact_VEF::milieu () const
Definition at line 476 of file Champ_front_contact_VEF.cpp.
{
  return equation().milieu();
}
References equation(), and Equation_base::milieu().
Referenced by calcul_grads_locaux().
nom_bord_oppose()
const Nom & Champ_front_contact_VEF::nom_bord_oppose () const
Definition at line 459 of file Champ_front_contact_VEF.cpp.
{
  return nom_bord;
}
References nom_bord.
printOn()
Sortie & Champ_front_contact_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 44 of file Champ_front_contact_VEF.cpp.
{
  return os;
}
readOn()
Entree & Champ_front_contact_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< prevu pour la temperature.
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 50 of file Champ_front_contact_VEF.cpp.
{
  Motcle nom_inco;
  nom_inco = "temperature";
  is >> nom_pb1 >> nom_bord1 >> nom_pb2 >> nom_bord2 ;
  creer(nom_pb1, nom_bord1, nom_pb2, nom_bord2, nom_inco);
  Cerr << "Champ_front_contact_VEF::readOn : " << nom_pb1 << nom_bord1 << nom_inco << finl;
  Cerr << "      connecte a                : " << nom_pb2 << nom_bord2 << nom_inco << finl;
  fixer_nb_comp(1); //!< prevu pour la temperature.
  if (Process::nproc() > 1)
    connect_est_remplit = 1;
  else
    connect_est_remplit = 0;
  remplir_elems_voisin_bord();
  return is;
}
References Cerr, connect_est_remplit, creer(), finl, Field_base::fixer_nb_comp(), nom_bord1, nom_bord2, nom_pb1, nom_pb2, Process::nproc(), and remplir_elems_voisin_bord().
Referenced by Champ_front_contact_fictif_VEF::readOn().
recupere_gradients_autre_pb()
void Champ_front_contact_VEF::recupere_gradients_autre_pb (const Front_VF & , DoubleVect & , DoubleVect &)
remplir_connect_bords()
void Champ_front_contact_VEF::remplir_connect_bords ()
if (j==1) { Cout << "connect i j " << i << " " << j << finl; Cout << "xv i j " << xv1(ndeb1+i,0) << " " << xv2(ndeb2+j,0) << finl; Cout << "xv i j " << xv1(ndeb1+i,1) << " " << xv2(ndeb2+j,1) << finl; Cout << "xv i j " << xv1(ndeb1+i,2) << " " << xv2(ndeb2+j,2) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,0) - xv2(ndeb2+j,0)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,1) - xv2(ndeb2+j,1)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,2) - xv2(ndeb2+j,2)) << finl; Cout << "erreur " << erreur << finl; }
if (j==1) { Cout << "connect i j " << i << " " << j << finl; Cout << "xv i j " << xv1(ndeb1+i,0) << " " << xv2(ndeb2+j,0) << finl; Cout << "xv i j " << xv1(ndeb1+i,1) << " " << xv2(ndeb2+j,1) << finl; Cout << "xv i j " << xv1(ndeb1+i,2) << " " << xv2(ndeb2+j,2) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,0) - xv2(ndeb2+j,0)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,1) - xv2(ndeb2+j,1)) << finl; Cout << "err i j " << std::fabs(xv1(ndeb1+i,2) - xv2(ndeb2+j,2)) << finl; Cout << "erreur " << erreur << finl; }
Definition at line 599 of file Champ_front_contact_VEF.cpp.
{
// Par convention, les grandeurs notees sans indice ainsi que celle notees
// avec un indice 1 correspondent au probleme courant, celle notees avec
// un indice 2 correspondent aux grandeurs du probleme couple avec le probleme
// courant
  const Frontiere& la_front = la_frontiere_dis->frontiere();
  int nb_faces = la_front.nb_faces();
//
// collection des informations du probleme 1
//
  nom_bord = nom_bord1 ;
  associer_ch_inc_base(l_inconnue1.valeur()) ;
  assert (nom_bord != "??") ;
  const Zone_VEF& la_zone_dis1=ref_cast(Zone_VEF, l_inconnue1->equation().zone_dis().valeur());
  int rang_front1 = la_zone_dis1.rang_frontiere(nom_bord1);
  const Front_VF& la_front_vf1=ref_cast(Front_VF, la_zone_dis1.frontiere_dis(rang_front1));
  const DoubleTab& xv1 = la_zone_dis1.xv();
  const IntTab& face_voisin=la_zone_dis1.face_voisins();
  const IntTab& elem_faces = la_zone_dis1.elem_faces();
  int ndeb1 = la_front_vf1.num_premiere_face();
//
// collection des informations du probleme 2
//
  nom_bord = nom_bord2 ;
  associer_ch_inc_base(l_inconnue2.valeur()) ;
  assert (nom_bord != "??") ;
  const Zone_VEF& la_zone_dis2=ref_cast(Zone_VEF, l_inconnue2->equation().zone_dis().valeur());
  int rang_front2 = la_zone_dis2.rang_frontiere(nom_bord2);
  const Front_VF& la_front_vf2=ref_cast(Front_VF, la_zone_dis2.frontiere_dis(rang_front2));
  const DoubleTab& xv2 = la_zone_dis2.xv();
  int ndeb2 = la_front_vf2.num_premiere_face();
// On verifie que les numerotations des faces sur ce bord sont bien compatibles
// pour les deux problemes consideres.
  int i,j,k,temoin,temoin_tot;
  double erreur = 0.;
  int ii;
  for (ii=0; ii<dimension; ii++)
    if (std::fabs(xv1(ndeb1,ii) - xv1(ndeb1+nb_faces,ii)) > erreur )
      erreur = std::fabs(xv1(ndeb1,ii) - xv1(ndeb1+nb_faces,ii));
//
// L'erreur est 1.e-5 fois la distance maximale entre deux faces de bord
  erreur *=1.e-5;
// GF la reference pour calculer l'erreur ne correspondait a rien
// distance entre la premiere face du bord et la face apres le bord ?????
// Version PAT
// erreur = Objet_U::precision_geom
  connect_bords.resize(nb_faces);
// assert(la_front_vf2.nb_faces()==la_front_vf1.nb_faces());
// Cout << "nb faces = " << la_front_vf2.nb_faces() << finl;
// Cout << "nb faces = " << la_front_vf1.nb_faces() << finl;
// PQ : 06/08/07
  int nb_faces1 = la_front_vf1.nb_faces();
  int nb_faces2 = la_front_vf2.nb_faces();
  if(nb_faces1!=nb_faces2)
    {
      Cerr << "Warning, the number of faces (" << nb_faces1 << ") on the boundary " << la_front_vf1.le_nom();
      Cerr << " of the domain " << la_zone_dis1.zone().domaine().le_nom() << finl;
      Cerr << "is different of the number of faces (" << nb_faces2 << ") on the boundary " << la_front_vf2.le_nom();
      Cerr << " of the domain " << la_zone_dis2.zone().domaine().le_nom() << " ..." << finl;
      Cerr << "The exchange condition with the paroi_contact can't succeed!" << finl;
      Nom fichier="connectivity_failed_";
      Nom fichier_med="connectivity_failed_";
      Nom nom_pb;
      if(nb_faces1>nb_faces2)
        {
          nom_pb=nom_pb2;
          fichier+=nom_bord2;
          fichier_med+=nom_pb;
          fichier_med+=".med";
          connectivity_failed(la_zone_dis1, nb_faces1, ndeb1, la_zone_dis2, nb_faces2, ndeb2, fichier, fichier_med);
        }
      else
        {
          nom_pb=nom_pb1;
          fichier+=nom_bord1;
          fichier_med+=nom_pb;
          fichier_med+=".med";
          connectivity_failed(la_zone_dis2, nb_faces2, ndeb2, la_zone_dis1, nb_faces1, ndeb1, fichier, fichier_med);
        }
      Cerr << "Boundaries " << nom_bord1 << " from problem " << nom_pb1 << finl;
      Cerr << "       and " << nom_bord2 << " from problem " << nom_pb2 << finl;
      Cerr << "have not the same number of faces." << finl;
      Cerr << "Coincidence between meshes may be recovered " << finl;
      Cerr << "by cutting mesh associated to " << nom_pb << finl;
      Cerr << "thanks to decouper_bord_coincident keyword or HOMARD tool (see reference manual)." << finl;
      exit();
    }
// PQ : 03/03 : redefinition du tableau de connectivite
// processus "optimise" et applicable a tout type de configuration
  temoin_tot=0;
  for (i=0; i<nb_faces; i++)
    {
// on redefinit erreur pour chaque face comme etant:
// on cherche l'elt associe a la face, on calcule le min du centre
// de gravite de l'elem a ses faces -> d1
// d1*1e-2
      int elem_voisin=face_voisin(ndeb1+i,0);
      if (elem_voisin==-1)
        elem_voisin=face_voisin(ndeb1+i,1);
      int nbf=elem_faces.dimension(1);
      double d1=DMAXFLOAT;
      for (int f=0; f<nbf; f++)
        {
          int f2=elem_faces(elem_voisin,f);
          if (dimension==2)
            d1=std::min(d1,distance_2D(f2,elem_voisin,la_zone_dis1));
          else
            d1=std::min(d1,distance_3D(f2,elem_voisin,la_zone_dis1));
        }
      erreur=d1*1e-2;
      temoin=0;
      for (j=i; j<nb_faces; j++)
        {
// O.C. : dimension plutot que dim1 dans la boucle suivante :
// for (k=0 ; k<dim1 ; k++)
          for (k=0 ; k<dimension ; k++)
            if (std::fabs(xv1(ndeb1+i,k) - xv2(ndeb2+j,k)) > erreur) break;
// Si on a passe le test ci-dessus, c'est que les dim coordonnees de la face
// sont les memes (d == dim)
          if (k==dimension)
            {
              /** if (j==1)
                  {
                  Cout << "connect i j " << i << " " << j << finl;
                  Cout << "xv i j " << xv1(ndeb1+i,0) << " " << xv2(ndeb2+j,0) << finl;
                  Cout << "xv i j " << xv1(ndeb1+i,1) << " " << xv2(ndeb2+j,1) << finl;
                  Cout << "xv i j " << xv1(ndeb1+i,2) << " " << xv2(ndeb2+j,2) << finl;
                  Cout << "err i j " << std::fabs(xv1(ndeb1+i,0) - xv2(ndeb2+j,0)) << finl;
                  Cout << "err i j " << std::fabs(xv1(ndeb1+i,1) - xv2(ndeb2+j,1)) << finl;
                  Cout << "err i j " << std::fabs(xv1(ndeb1+i,2) - xv2(ndeb2+j,2)) << finl;
                  Cout << "erreur " << erreur << finl;
                  }*/
              connect_bords(i)=j;
              temoin=1;
              break;
            }
        }
      if(temoin==0)
        for (j=0; j<i; j++)
          {
            for (k=0 ; k<dimension ; k++)
              if (std::fabs(xv1(ndeb1+i,k) - xv2(ndeb2+j,k)) > erreur) break;
// Si on a passe le test ci-dessus, c'est que les dim coordonnees de la face
// sont les memes (d == dim)
            if (k==dimension)
              {
                /**  if (j==1)
                     {
                     Cout << "connect i j " << i << " " << j << finl;
                     Cout << "xv i j " << xv1(ndeb1+i,0) << " " << xv2(ndeb2+j,0) << finl;
                     Cout << "xv i j " << xv1(ndeb1+i,1) << " " << xv2(ndeb2+j,1) << finl;
                     Cout << "xv i j " << xv1(ndeb1+i,2) << " " << xv2(ndeb2+j,2) << finl;
                     Cout << "err i j " << std::fabs(xv1(ndeb1+i,0) - xv2(ndeb2+j,0)) << finl;
                     Cout << "err i j " << std::fabs(xv1(ndeb1+i,1) - xv2(ndeb2+j,1)) << finl;
                     Cout << "err i j " << std::fabs(xv1(ndeb1+i,2) - xv2(ndeb2+j,2)) << finl;
                     Cout << "erreur " << erreur << finl;
                     }*/
                connect_bords(i)=j;
                temoin=1;
                break;
              }
          }
      if(temoin==0)
        {
          temoin_tot=1;
          if(dimension==2)
            Cerr<<" no connectivity found for face : "<<ndeb1+i<<" located at : x= "<<xv1(ndeb1+i,0)<<" y= "<<xv1(ndeb1+i,1)<<finl;
          else
            Cerr<<" no connectivity found for face : "<<ndeb1+i<<" located at : x= "<<xv1(ndeb1+i,0)<<" y= "<<xv1(ndeb1+i,1)<< " z= "<<xv1(ndeb1+i,2)<<finl;
        }
    }
  if(temoin_tot==1)
    {
      Cerr<<" Process stopped at Champ_front_contact_VEF::remplir_connect_bords() "<<finl;
      exit();
    }
// on verifie que l'on a bien cree une bijection
  ArrOfInt inv_connect_bords;
  inv_connect_bords.resize_array(nb_faces, Array_base::NOCOPY_NOINIT);
  inv_connect_bords=-1;
  for (i=0; i<nb_faces; i++)
    {
      inv_connect_bords[connect_bords(i)]=i;
    }
  if (min_array(inv_connect_bords) < 0)
    {
      Cerr<<"Pb a la creation de connect_bord, ce n'est pas une bijection"<<finl;
      Cerr<<"tableau inverse "<<inv_connect_bords<<finl;
      Cerr<<"tableau connect "<<connect_bords<<finl;
      exit();
    }
}
References associer_ch_inc_base(), Cerr, connect_bords, connectivity_failed(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, distance_2D(), distance_3D(), DMAXFLOAT, Zone::domaine(), Zone_VF::elem_faces(), MorEqn::equation(), erreur(), Process::exit(), f2, Zone_VF::face_voisins(), finl, Frontiere_dis_base::frontiere(), Zone_VF::frontiere_dis(), l_inconnue1, l_inconnue2, Champ_front_base::la_frontiere_dis, Frontiere_dis_base::le_nom(), Domaine::le_nom(), min_array(), Frontiere::nb_faces(), Front_VF::nb_faces(), Array_base::NOCOPY_NOINIT, nom_bord, nom_bord1, nom_bord2, nom_pb1, nom_pb2, Front_VF::num_premiere_face(), Zone_dis_base::rang_frontiere(), ref_cast, TRUSTVect< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Ref_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), Zone_VF::xv(), Zone_dis_base::zone(), and Equation_base::zone_dis().
Referenced by initialiser().
remplir_elems_voisin_bord()
void Champ_front_contact_VEF::remplir_elems_voisin_bord ()
Definition at line 880 of file Champ_front_contact_VEF.cpp.
{
  const Zone_VEF& la_zone_dis1=ref_cast(Zone_VEF, l_inconnue1->zone_dis_base());
  int rang_front1 = la_zone_dis1.rang_frontiere(nom_bord1);
  const Front_VF& la_front_vf1=ref_cast(Front_VF, la_zone_dis1.frontiere_dis(rang_front1));
  const IntTab& face_voisins1 = la_zone_dis1.face_voisins();
  int nb_faces = la_front_vf1.nb_faces();
  int ndeb = la_front_vf1.num_premiere_face();
  int voisin_0, voisin_1;
  int elem_vois;
  elems_voisin_bord_.resize(nb_faces);
  elems_voisin_bord_=-1;
  for (int face=0; face<nb_faces; face++)
    {
      elem_vois=-1;
      voisin_0 = face_voisins1(ndeb+face,0);
      voisin_1 = face_voisins1(ndeb+face,1);
      if (voisin_0!=-1)
        elem_vois=voisin_0;
      else
        elem_vois=voisin_1;
      elems_voisin_bord_(face) = elem_vois;
    }
}
References elems_voisin_bord_, Zone_VF::face_voisins(), Zone_VF::frontiere_dis(), l_inconnue1, Front_VF::nb_faces(), nom_bord1, Front_VF::num_premiere_face(), Zone_dis_base::rang_frontiere(), ref_cast, TRUSTVect< _TYPE_ >::resize(), and Champ_base::zone_dis_base().
Referenced by readOn().
remplir_faces_coin()
void Champ_front_contact_VEF::remplir_faces_coin ()
Definition at line 822 of file Champ_front_contact_VEF.cpp.
{
  const Zone_Cl_VEF& la_zcl_dis1=ref_cast(Zone_Cl_VEF, l_inconnue1->equation().zone_Cl_dis().valeur());
  const Conds_lim& conds_lim = la_zcl_dis1.les_conditions_limites();
  int size_cl = conds_lim.size();
  int size = elems_voisin_bord_.size();
  int elem_vois, elem_vois_autre_fr;
// Parcours des faces de la frontiere
  int elem_vois_face_1, elem_vois_face_2;
  faces_coin.resize(size);
  for (int ind_face_1=0; ind_face_1<size; ind_face_1++)
    {
      elem_vois_face_1 = elems_voisin_bord_[ind_face_1];
      for (int ind_face_2 =0; ind_face_2<size; ind_face_2++)
        {
          if (ind_face_1!=ind_face_2)
            {
              elem_vois_face_2 = elems_voisin_bord_[ind_face_2];
              if ((elem_vois_face_1==elem_vois_face_2) && (elem_vois_face_1!=-1))
                faces_coin(ind_face_1)=1;
            }
        }
    }
// On tient compte ensuite des faces appaartenant a d autres fontieres
// pouvant appartenir a un element coin
  for (int num_cl=0; num_cl<size_cl; num_cl++)
    {
      const Champ_front& ch_front = conds_lim[num_cl]->champ_front();
      if (sub_type(Champ_front_contact_VEF,ch_front.valeur()))
        {
          const Champ_front_contact_VEF& ch_front_contact = ref_cast(Champ_front_contact_VEF,ch_front.valeur());
          const Nom& nom_bord_autre_fr = ch_front_contact.get_nom_bord1();
          if (nom_bord1!=nom_bord_autre_fr)
            {
              const IntVect& elems_autre_fr =  ch_front_contact.get_elems_voisin_bord();
              int size_autre_fr = elems_autre_fr.size();
              for (int ind_face =0; ind_face<size; ind_face++)
                {
                  elem_vois = elems_voisin_bord_[ind_face];
                  for (int ind_face_autre_fr =0; ind_face_autre_fr<size_autre_fr; ind_face_autre_fr++)
                    {
                      elem_vois_autre_fr = elems_autre_fr[ind_face_autre_fr];
                      if ((elem_vois==elem_vois_autre_fr) && (elem_vois!=-1))
                        faces_coin(ind_face)=1;
                    }
                }
            }
        }
    }
}
References elems_voisin_bord_, MorEqn::equation(), faces_coin, get_elems_voisin_bord(), get_nom_bord1(), l_inconnue1, Zone_Cl_dis_base::les_conditions_limites(), nom_bord1, ref_cast, TRUSTVect< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), vect_impl::size(), sub_type, Deriv_Champ_front_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Equation_base::zone_Cl_dis().
Referenced by initialiser().
self_cast() [1/2]
const Champ_front_contact_VEF & Champ_front_contact_VEF::self_cast (const Objet_U & r) static
Definition at line 41 of file Champ_front_contact_VEF.cpp.
self_cast() [2/2]
Champ_front_contact_VEF & Champ_front_contact_VEF::self_cast (Objet_U & r) static
Definition at line 41 of file Champ_front_contact_VEF.cpp.
set_coeff_amort_denum()
DoubleVect & Champ_front_contact_VEF::set_coeff_amort_denum () inline
Definition at line 189 of file Champ_front_contact_VEF.h.
{
  return coeff_amort_denum;
}
References coeff_amort_denum.
set_coeff_amort_num()
DoubleVect & Champ_front_contact_VEF::set_coeff_amort_num () inline
Definition at line 179 of file Champ_front_contact_VEF.h.
{
  return coeff_amort_num;
}
References coeff_amort_num.
set_gradient_fro_local()
DoubleVect & Champ_front_contact_VEF::set_gradient_fro_local () inline
Definition at line 148 of file Champ_front_contact_VEF.h.
{
  return gradient_fro_local;
}
References gradient_fro_local.
set_gradient_fro_transf()
DoubleVect & Champ_front_contact_VEF::set_gradient_fro_transf () inline
Definition at line 169 of file Champ_front_contact_VEF.h.
{
  return gradient_fro_transf;
}
References gradient_fro_transf.
set_gradient_num_local()
DoubleVect & Champ_front_contact_VEF::set_gradient_num_local () inline
Definition at line 138 of file Champ_front_contact_VEF.h.
{
  return gradient_num_local;
}
References gradient_num_local.
set_gradient_num_transf()
DoubleVect & Champ_front_contact_VEF::set_gradient_num_transf () inline
Definition at line 159 of file Champ_front_contact_VEF.h.
{
  return gradient_num_transf;
}
References gradient_num_transf.
taille_memoire()
unsigned Champ_front_contact_VEF::taille_memoire () const override virtual
Reimplemented from Ch_front_var_instationnaire_dep.
Definition at line 41 of file Champ_front_contact_VEF.cpp.
test_faces_coin()
void Champ_front_contact_VEF::test_faces_coin ()
Definition at line 908 of file Champ_front_contact_VEF.cpp.
{
  const Zone_VEF& la_zone_dis1=ref_cast(Zone_VEF, l_inconnue1->zone_dis_base());
  const DoubleTab& xv1 = la_zone_dis1.xv();
  const Zone_Cl_VEF& la_zcl_dis1=ref_cast(Zone_Cl_VEF, l_inconnue1->equation().zone_Cl_dis().valeur());
  const Conds_lim& conds_lim = la_zcl_dis1.les_conditions_limites();
  int size_cl = conds_lim.size();
  const Nom& nom_dom = l_inconnue1->equation().probleme().domaine().le_nom();
  int erreur = 0;
  for (int num_cl=0; num_cl<size_cl; num_cl++)
    {
      const Champ_front& ch_front = conds_lim[num_cl]->champ_front();
      if (sub_type(Champ_front_contact_VEF,ch_front.valeur()))
        {
          const Champ_front_contact_VEF& ch_front_contact = ref_cast(Champ_front_contact_VEF,ch_front.valeur());
          const Nom& nom_bord_fr = ch_front_contact.get_nom_bord1();
          int rang_front_fr = la_zone_dis1.rang_frontiere(nom_bord_fr);
          const Front_VF& la_front_vf_fr = ref_cast(Front_VF, la_zone_dis1.frontiere_dis(rang_front_fr));
          int ndeb_fr = la_front_vf_fr.num_premiere_face();
          const IntVect& faces_coin_fr = ch_front_contact.get_faces_coin();
          for (int i=0; i<faces_coin_fr.size(); i++)
            {
              if (faces_coin_fr(i)!=0)
                {
                  erreur =1;
                  Cerr<<"La face suivante du bord "<<nom_bord_fr<<" est une face de coin pour le domaine "<<nom_dom<<finl;
                  for (int k=0; k<dimension; k++)
                    Cerr<<"x_"<<k<<" "<<xv1(ndeb_fr+i,k)<<finl;
                }
            }
        }
    }
  if (erreur)
    {
      Cerr<<"Le codage de Champ_front_contact_VEF n est pas disponible pour cette situation"<<finl;
      Cerr<<"Decouper la (ou les) maille concernee en utilisant l interprete VerifierCoin"<<finl;
      Cerr<<"ou en utilisant Trianguler_H en 2D ou Tetraedriser_homogene en 3D"<<finl;
// exit();
    }
}
References Cerr, Objet_U::dimension, Probleme_base::domaine(), MorEqn::equation(), erreur(), finl, Zone_VF::frontiere_dis(), get_faces_coin(), get_nom_bord1(), l_inconnue1, Domaine::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::num_premiere_face(), Equation_base::probleme(), Zone_dis_base::rang_frontiere(), ref_cast, TRUSTVect< _TYPE_ >::size(), vect_impl::size(), sub_type, Deriv_Champ_front_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Zone_VF::xv(), Equation_base::zone_Cl_dis(), and Champ_base::zone_dis_base().
Referenced by mettre_a_jour().
trace_face_raccord()
DoubleVect & Champ_front_contact_VEF::trace_face_raccord (const Front_VF & fr_vf, const DoubleVect & y, DoubleVect & x)
Definition at line 573 of file Champ_front_contact_VEF.cpp.
{
// On verifie que la frontiere est de type Raccord_distant_homogene
  if (sub_type(Raccord_distant_homogene,fr_vf.frontiere()))
    fr_vf.frontiere().trace_face_distant(y,x);
  else
    {
      if (Process::nproc()>1)
        {
// On teste si on a bien un raccord distant homogene car sinon le tableau connect n'est pas rempli en parallele
// En effet remplir_connect_bords n'est fait qu'en sequentiel
          Cerr << "The boundary named " << fr_vf.frontiere().le_nom() << " is not a 'Raccord Distant Homogene'" << finl;
          Cerr << "Use keyword modif_bord_to_raccord to change the boundary of kind Paroi into a boundary of kind Raccord" << finl;
          Cerr << "after you read the meshes during the partitioning." << finl;
          exit();
        }
// On traite un raccord local
      int nb_fac_front=x.size();
      for(int fac_front=0; fac_front<nb_fac_front; fac_front++)
        x(fac_front) = y(connect_bords(fac_front));
    }
  return x;
}
References Cerr, connect_bords, Process::exit(), finl, Frontiere_dis_base::frontiere(), Frontiere::le_nom(), Process::nproc(), TRUSTVect< _TYPE_ >::size(), sub_type, and Frontiere::trace_face_distant().
Referenced by Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), and verifier_scalaire_bord().
verifier_scalaire_bord()
void Champ_front_contact_VEF::verifier_scalaire_bord (double temps)
Definition at line 385 of file Champ_front_contact_VEF.cpp.
{
// Cette methode a pour but de verifier que la temperature de bord calculee pour chaque
// face num_face est bien comprise entre les temperatures moyennes sur les elements entourant
// num_face dans chaque milieu.
  const Frontiere& la_front=la_frontiere_dis->frontiere();
  int nb_faces=la_front.nb_faces();
  DoubleVect Scal_moy_autre_pb(nb_faces);
  trace_face_raccord(fr_vf_autre_pb.valeur(),ch_fr_autre_pb->Scal_moy,Scal_moy_autre_pb);
  DoubleTab& tab=valeurs_au_temps(temps);
// Verification sur les temperatures
  for (int fac_front=0; fac_front<nb_faces; fac_front++)
    {
      if (Scal_moy(fac_front) > Scal_moy_autre_pb(fac_front))
        {
          if ((tab(fac_front,0)>Scal_moy(fac_front)) || (tab(fac_front,0)<Scal_moy_autre_pb(fac_front)))
            {
              if (tab(fac_front,0)>Scal_moy(fac_front))
                {
                  Cerr<<"Attention, Tp n'est pas compris entre les temperatures"<<finl;
                  Cerr<<"fluide et solide au voisinage de la paroi"<<finl;
                  Cerr<<"Tp("<<fac_front<<") = "<<tab(fac_front,0)<<" est trop elevee"<<finl;
                  Cerr<<"de DT = "<<tab(fac_front,0)-Scal_moy(fac_front)<<" K"<<finl;
                }
              else
                {
                  Cerr<<"Attention, Tp n'est pas compris entre les temperatures"<<finl;
                  Cerr<<"fluide et solide au voisinage de la paroi"<<finl;
                  Cerr<<"Tp("<<fac_front<<") = "<<tab(fac_front,0)<<" est trop basse "<<finl;
                  Cerr<<"de DT = "<<Scal_moy_autre_pb(fac_front)-tab(fac_front,0)<<" K"<<finl;
                }
            }
        }
      else
        {
          if ((tab(fac_front,0)<Scal_moy(fac_front)) || (tab(fac_front,0)>Scal_moy_autre_pb(fac_front)))
            {
              if (tab(fac_front,0)<Scal_moy(fac_front))
                {
                  Cerr<<"Attention, Tp n'est pas compris entre les temperatures"<<finl;
                  Cerr<<"fluide et solide au voisinage de la paroi"<<finl;
                  Cerr<<"Tp("<<fac_front<<") = "<<tab(fac_front,0)<<" est trop basse"<<finl;
                  Cerr<<"de DT = "<<Scal_moy(fac_front)-tab(fac_front,0)<<" K"<<finl;
                }
              else
                {
                  Cerr<<"Attention, Tp n'est pas compris entre les temperatures"<<finl;
                  Cerr<<"fluide et solide au voisinage de la paroi"<<finl;
                  Cerr<<"Tp("<<fac_front<<") = "<<tab(fac_front,0)<<" est trop elevee"<<finl;
                  Cerr<<"de DT = "<<tab(fac_front,0)-Scal_moy_autre_pb(fac_front)<<" K"<<finl;
                }
            }
        }
    }
}
References Cerr, ch_fr_autre_pb, finl, fr_vf_autre_pb, Frontiere_dis_base::frontiere(), Champ_front_base::la_frontiere_dis, Frontiere::nb_faces(), Scal_moy, trace_face_raccord(), Ref_Front_VF::valeur(), and Champ_front_var_instationnaire::valeurs_au_temps().
zone_Cl_dis()
const Zone_Cl_dis_base & Champ_front_contact_VEF::zone_Cl_dis () const
Definition at line 488 of file Champ_front_contact_VEF.cpp.
{
  return equation().zone_Cl_dis().valeur();
}
References equation(), Deriv_Zone_Cl_dis_base::valeur(), and Equation_base::zone_Cl_dis().
zone_dis()
const Zone_dis_base & Champ_front_contact_VEF::zone_dis () const
Definition at line 482 of file Champ_front_contact_VEF.cpp.
{
  return inconnue().zone_dis_base();
}
References inconnue(), and Champ_base::zone_dis_base().
Referenced by calcul_grads_locaux(), and front_dis().
Member Data Documentation
ch_fr_autre_pb
Ref_Champ_front_contact_VEF Champ_front_contact_VEF::ch_fr_autre_pb protected
Definition at line 109 of file Champ_front_contact_VEF.h.
Referenced by associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), and verifier_scalaire_bord().
coeff_amort_denum
DoubleVect Champ_front_contact_VEF::coeff_amort_denum protected
Definition at line 127 of file Champ_front_contact_VEF.h.
Referenced by calcul_coeff_amort(), get_coeff_amort_denum(), initialiser(), and set_coeff_amort_denum().
coeff_amort_num
DoubleVect Champ_front_contact_VEF::coeff_amort_num protected
Definition at line 126 of file Champ_front_contact_VEF.h.
Referenced by calcul_coeff_amort(), get_coeff_amort_num(), initialiser(), and set_coeff_amort_num().
connect_bords
IntVect Champ_front_contact_VEF::connect_bords protected
Tableau de connectivite des faces de bord des deux bord conjugues (en sequentiel)
Definition at line 117 of file Champ_front_contact_VEF.h.
Referenced by get_connect_bords(), remplir_connect_bords(), and trace_face_raccord().
connect_est_remplit
int Champ_front_contact_VEF::connect_est_remplit protected
Definition at line 118 of file Champ_front_contact_VEF.h.
Referenced by initialiser(), and readOn().
elems_voisin_bord_
IntVect Champ_front_contact_VEF::elems_voisin_bord_ protected
Definition at line 129 of file Champ_front_contact_VEF.h.
Referenced by get_elems_voisin_bord(), remplir_elems_voisin_bord(), and remplir_faces_coin().
faces_coin
IntVect Champ_front_contact_VEF::faces_coin protected
Definition at line 130 of file Champ_front_contact_VEF.h.
Referenced by get_faces_coin(), and remplir_faces_coin().
fr_vf_autre_pb
Ref_Front_VF Champ_front_contact_VEF::fr_vf_autre_pb protected
Definition at line 108 of file Champ_front_contact_VEF.h.
Referenced by associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), and verifier_scalaire_bord().
gradient_fro_local
DoubleVect Champ_front_contact_VEF::gradient_fro_local protected
Definition at line 121 of file Champ_front_contact_VEF.h.
Referenced by calcul_grads_locaux(), calcul_grads_transf(), get_gradient_fro_local(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), and set_gradient_fro_local().
gradient_fro_transf
DoubleVect Champ_front_contact_VEF::gradient_fro_transf protected
Definition at line 123 of file Champ_front_contact_VEF.h.
Referenced by calcul_grads_transf(), get_gradient_fro_transf(), initialiser(), mettre_a_jour(), and set_gradient_fro_transf().
gradient_num_local
DoubleVect Champ_front_contact_VEF::gradient_num_local protected
Definition at line 120 of file Champ_front_contact_VEF.h.
Referenced by calcul_grads_locaux(), calcul_grads_transf(), get_gradient_num_local(), initialiser(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), and set_gradient_num_local().
gradient_num_transf
DoubleVect Champ_front_contact_VEF::gradient_num_transf protected
Definition at line 122 of file Champ_front_contact_VEF.h.
Referenced by calcul_grads_transf(), get_gradient_num_transf(), initialiser(), mettre_a_jour(), and set_gradient_num_transf().
info_obj
const Type_info Champ_front_contact_VEF::info_obj static
Definition at line 50 of file Champ_front_contact_VEF.h.
is_conduction
int Champ_front_contact_VEF::is_conduction protected
Est-on dans un probleme conduction ?
Definition at line 104 of file Champ_front_contact_VEF.h.
Referenced by initialiser().
l_inconnue
Ref_Champ_Inc_base Champ_front_contact_VEF::l_inconnue protected
Definition at line 107 of file Champ_front_contact_VEF.h.
Referenced by associer_ch_inc_base(), calcul_grads_locaux(), equation(), and inconnue().
l_inconnue1
Ref_Champ_Inc_base Champ_front_contact_VEF::l_inconnue1 protected
Definition at line 105 of file Champ_front_contact_VEF.h.
Referenced by calcul_coeff_amort(), calcul_grads_locaux(), creer(), initialiser(), remplir_connect_bords(), remplir_elems_voisin_bord(), remplir_faces_coin(), and test_faces_coin().
l_inconnue2
Ref_Champ_Inc_base Champ_front_contact_VEF::l_inconnue2 protected
Definition at line 106 of file Champ_front_contact_VEF.h.
Referenced by associer_front_vf_et_ch_front_autre_pb(), completer(), creer(), and remplir_connect_bords().
nom_bord
Nom Champ_front_contact_VEF::nom_bord protected
Definition at line 113 of file Champ_front_contact_VEF.h.
Referenced by calcul_grads_locaux(), completer(), front_dis(), nom_bord_oppose(), and remplir_connect_bords().
nom_bord1
Nom Champ_front_contact_VEF::nom_bord1 protected
Definition at line 111 of file Champ_front_contact_VEF.h.
Referenced by calcul_coeff_amort(), calcul_grads_locaux(), creer(), get_nom_bord1(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_fictif_VEF::readOn(), readOn(), remplir_connect_bords(), remplir_elems_voisin_bord(), and remplir_faces_coin().
nom_bord2
Nom Champ_front_contact_VEF::nom_bord2 protected
Definition at line 112 of file Champ_front_contact_VEF.h.
Referenced by associer_front_vf_et_ch_front_autre_pb(), completer(), creer(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_fictif_VEF::readOn(), readOn(), and remplir_connect_bords().
nom_pb1
Nom Champ_front_contact_VEF::nom_pb1 protected
Definition at line 114 of file Champ_front_contact_VEF.h.
Referenced by associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_fictif_VEF::readOn(), readOn(), and remplir_connect_bords().
nom_pb2
Nom Champ_front_contact_VEF::nom_pb2 protected
Definition at line 115 of file Champ_front_contact_VEF.h.
Referenced by Champ_front_contact_fictif_VEF::mettre_a_jour(), mettre_a_jour(), Champ_front_contact_fictif_VEF::readOn(), readOn(), and remplir_connect_bords().
Scal_moy
DoubleVect Champ_front_contact_VEF::Scal_moy protected
Definition at line 124 of file Champ_front_contact_VEF.h.
Referenced by calcul_grads_locaux(), initialiser(), and verifier_scalaire_bord().
verification_faces_coin
int Champ_front_contact_VEF::verification_faces_coin protected
Definition at line 131 of file Champ_front_contact_VEF.h.
Referenced by initialiser(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_front_contact_VEF.h
src/VEF/Champs/Champ_front_contact_VEF.cpp