TRUST: Op_Diff_VEF_Face_Penalise Class Reference
Op_Diff_VEF_Face_Penalise Class Reference
#include <Op_Diff_VEF_Face_Penalise.h>
Public Member Functions
Op_Diff_VEF_Face_Penalise ()
~Op_Diff_VEF_Face_Penalise ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &inconnue, DoubleTab &resu) const override
methode qui calcule la vitesse au temps n+1 lorsque le
schema explicite est utilise.
DoubleTab & calculer (const DoubleTab &inconnue, DoubleTab &resu) const override
methode qui calcule la contribution de l'operateur.
Public Member Functions inherited from Op_Diff_VEF_Face
Op_Diff_VEF_Face ()
~Op_Diff_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
associe le champ de diffusivite
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void verifier () const
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEF_Face_Penalise & self_cast (Objet_U &)
static const Op_Diff_VEF_Face_Penalise & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEF_Face & self_cast (Objet_U &)
static const Op_Diff_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void voisinage (const int Numero_face, IntList &Voisinage) const
methode qui calcule le voisinage d'une face.
void voisinage (const IntList &Ensemble_faces, IntList &Voisinage) const
methode qui calcule le voisinage d'une liste de faces.
double signe (const int Face1, const int Face2) const
double coefficient_penalisation (const int Numero_face) const
fonction membre qui retourne le coefficient de
penalisation associee a chaque face du maillage primaire.
void faces_communes (const int Face1, const int Face2, IntList &Face_commune) const
fonction membre qui renvoie la liste des faces appartenant
au voisinage de Face1 ET de Face2.
void reduction (const IntList &Liste1, const IntList &Liste2, IntList &Liste_reduite) const
int element_commun (const int Face1, const int Face2) const
fonction membre qui renvoie le numero de l'element contenant Face1 et Face2
s'il existe et renvoie -1 sinon.
int autre_face (const int Face1, const int Face2) const
fonction membre qui retourne la 3eme face de l'element Element si
Face1 et Face2 appartiennent au meme element.
Sinon retourne -1.
double diametre (const int Element) const
double longueur (const int Face) const
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Private Member Functions
const Zone_VEF & zone_vef () const
const Domaine & domaine () const
const Zone & zone () const
const Zone_Cl_VEF & zone_cl () const
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Diff_VEF_Face
Ref_Champ_base diffusivite_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 24 of file Op_Diff_VEF_Face_Penalise.h.
Constructor & Destructor Documentation
Op_Diff_VEF_Face_Penalise()
Op_Diff_VEF_Face_Penalise::Op_Diff_VEF_Face_Penalise ()
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
~Op_Diff_VEF_Face_Penalise()
Op_Diff_VEF_Face_Penalise::~Op_Diff_VEF_Face_Penalise ()
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_VEF_Face_Penalise::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
methode qui calcule la vitesse au temps n+1 lorsque le
schema explicite est utilise.
Reimplemented from Op_Diff_VEF_Face.
Definition at line 79 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans ajouter() de penalisation" << finl;
  int nb_composante,numero_global_face,local;
  int face_penalisation,face;
  double coeff;
  IntList voisinage_ordre1,voisinage_ordre1_strict;
  IntList voisinage_ordre2,voisinage_ordre2_strict;
  IntList ensemble_faces;
  /* On calcule le resultat du a la matrice de penalisation
   * i.e. somme_j U_j P_i,j ou P_i,j est le terme de la matrice
   * de penalisation.
   */
  for (nb_composante = 0; nb_composante < dimension; nb_composante++)
    {
      for (numero_global_face = 0; numero_global_face < zone_vef().nb_faces();
           numero_global_face++)
        {
          /* Calcul des voisinages de numero_global_face */
          voisinage(numero_global_face,voisinage_ordre1);
          voisinage(voisinage_ordre1,voisinage_ordre2);
          reduction(voisinage_ordre1,voisinage_ordre2,voisinage_ordre2_strict);
// Cerr << "Nombre iterations " << numero_global_face << finl;
// Cerr << "Nombre de faces " << zone_vef().nb_faces() << finl;
          /* Calcul de resu(numero_face_global,nb_comp)
           * pour le voisinage_ordre2_strict
           */
          for (local = 0 ; local < voisinage_ordre2_strict.size(); local++)
            {
              face = voisinage_ordre2_strict[local];
              faces_communes(numero_global_face,face,ensemble_faces);
// Cerr << "Taille voisinage_ordre_1 " << voisinage_ordre1.size()
// << finl;
// Cerr << "Taille voisinage_ordre2 " << voisinage_ordre2.size()
// << finl;
// Cerr << "Taille voisinage_ordre2_strict " << voisinage_ordre2_strict.size() << finl;
// Cerr << "Taille ensemble_faces " << ensemble_faces.size() << finl;
// if (ensemble_faces.size() != 1)
// {
// Cerr << "Erreur dans ajouter() de la penalisation." << finl;
// Process::exit();
// }
              for (int mm = 0; mm < ensemble_faces.size(); mm++)
                {
                  face_penalisation = ensemble_faces[mm];
                  resu(numero_global_face,nb_composante) +=
                    inconnue(face,nb_composante)*
                    signe(numero_global_face,face)*
                    coefficient_penalisation(face_penalisation)*
                    longueur(face_penalisation)*
                    1./3.;
                }
            }
          /* Calcul de resu(numero_global_face,nb_comp)
           * pour le voisinage_ordre1_strict
           */
          for (local = 0 ; local < voisinage_ordre1_strict.size(); local++)
            {
              assert(voisinage_ordre1_strict.size() == 2
                     || voisinage_ordre1_strict.size() == 4);
              face = voisinage_ordre1_strict[local];
              face_penalisation = autre_face(numero_global_face,face);
              resu(numero_global_face,nb_composante) +=
                inconnue(face,nb_composante)*
                coefficient_penalisation(face_penalisation)*
                longueur(face_penalisation)*
                (-1./3.);
            }
          /* Cas 1: la face consideree est au bord du domaine.
           * et numero_global_face = face
           */
          if (numero_global_face < zone_vef().nb_faces_bord())
            for (local = 0; local < voisinage_ordre1.size(); local++)
              {
                assert(voisinage_ordre1.size() == 3);
                face_penalisation = voisinage_ordre1[local];
                if (numero_global_face == face_penalisation)
                  coeff = 1.;
                else
                  coeff = 1./3.;
                resu(numero_global_face,nb_composante) +=
                  inconnue(numero_global_face,nb_composante) *
                  coeff *
                  coefficient_penalisation(face_penalisation)*
                  longueur(face_penalisation);
              }
          /* Cas 2: la face est interne et numero_global_face = face */
          else
            for (local = 0; local < voisinage_ordre1_strict.size(); local++)
              {
                assert( voisinage_ordre1_strict.size() == 4);
                face_penalisation = voisinage_ordre1_strict[local];
                resu(numero_global_face,nb_composante) +=
                  inconnue(numero_global_face,nb_composante) *
                  coefficient_penalisation(face_penalisation)*
                  longueur(face_penalisation)*
                  1./3.;
              }
        }
    }
  /* Ajout de la matrice de diffusion classique */
  Op_Diff_VEF_Face::ajouter(inconnue,resu);
// Cerr << "Je sors de calcul_matrice_de_penalisation_" << finl;
  return resu;
}
References Op_Diff_VEF_Face::ajouter(), autre_face(), coeff, coefficient_penalisation(), Objet_U::dimension, faces_communes(), longueur(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), reduction(), signe(), TRUSTList< _TYPE_ >::size(), voisinage(), and zone_vef().
Referenced by calculer().
autre_face()
int Op_Diff_VEF_Face_Penalise::autre_face (const int Face1, const int Face2) const protected
fonction membre qui retourne la 3eme face de l'element Element si
Face1 et Face2 appartiennent au meme element.
Sinon retourne -1.
Definition at line 580 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans autre_face" << finl;
  /* Declaration des variables locales */
  int numero_local,lautre_face=-1;
  int elem_commun = element_commun(Face1,Face2);
  /* Le nombre de faces des elements constituant la zone
   * de discretisation.
   * REM: on suppose que l'on ne travaille pas sur des prismes.
   */
  if (elem_commun == -1)
    {
      Cerr << "Fonction element_commun" << finl;
      Cerr << "Les 2 faces n'appartiennent pas au meme element." << finl;
      Process::exit();
      return lautre_face;
    }
  const int nb_faces_element = zone().nb_faces_elem();
  for (numero_local = 0; numero_local < nb_faces_element; numero_local++)
    {
      /* On recupere le numero global de chacune des
       * faces de Element
       */
      const int numero_global_face =
        zone_vef().elem_faces(elem_commun,numero_local);
      if ( numero_global_face != Face1 && numero_global_face != Face2)
        {
          lautre_face = numero_global_face;
          break;
        }
    }//fin du for
// Cerr << "Je sors de autre_face" << finl;
  return lautre_face;
}
References Cerr, Zone_VF::elem_faces(), element_commun(), Process::exit(), finl, Zone::nb_faces_elem(), zone(), and zone_vef().
Referenced by ajouter().
calculer()
DoubleTab & Op_Diff_VEF_Face_Penalise::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
methode qui calcule la contribution de l'operateur.
Reimplemented from Op_Diff_VEF_Face.
Definition at line 61 of file Op_Diff_VEF_Face_Penalise.cpp.
{
  resu = 0.;
  return ajouter(inconnue,resu);
}
References ajouter().
coefficient_penalisation()
double Op_Diff_VEF_Face_Penalise::coefficient_penalisation (const int Numero_face) const protected
fonction membre qui retourne le coefficient de
penalisation associee a chaque face du maillage primaire.
Definition at line 389 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans coefficient_penalisation" << finl;
  /* Initialisation de parametres locaux */
  double eta=0.;
  double coefficientpenalisation = 0.;
  const int voisin1 =
    zone_vef().face_voisins(Numero_face,1);
  const int voisin2 =
    zone_vef().face_voisins(Numero_face,0);
  if (voisin1 == -1 && voisin2 == -1)
    {
      Cerr << "Erreur dans Op_Dift_standard_Face_VEF_penalise::"
           << "coefficient_penalisation()" << finl;
      Process::exit();
    }
  if (voisin1 != -1 && voisin2 != -1)
    {
      /* Calcul des coefficients de penalisation proprement dit */
      coefficientpenalisation = 1./diametre(voisin1);
      eta = 1./diametre(voisin2);
      coefficientpenalisation = std::min(coefficientpenalisation,eta);
    }
  if (voisin1 == -1)
    coefficientpenalisation = 1./diametre(voisin2);
  if (voisin2 == -1)
    coefficientpenalisation = 1./diametre(voisin1);
  return coefficientpenalisation;
// Cerr << "Je sors de coefficient_penalisation" << finl;
}
References Cerr, diametre(), Process::exit(), Zone_VF::face_voisins(), finl, and zone_vef().
Referenced by ajouter().
cree_instance()
Objet_U * Op_Diff_VEF_Face_Penalise::cree_instance () static
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
diametre()
double Op_Diff_VEF_Face_Penalise::diametre (const int Element) const inline protected
Definition at line 135 of file Op_Diff_VEF_Face_Penalise.h.
{
  int face1,face2,face3;
  double longueur_face1,longueur_face2,longueur_face3;
  double longueur_max,diametre_element;
  face1 = zone_vef().elem_faces(Element,0);
  face2 = zone_vef().elem_faces(Element,1);
  face3 = zone_vef().elem_faces(Element,2);
  longueur_face1 = longueur(face1);
  longueur_face2 = longueur(face2);
  longueur_face3 = longueur(face3);
  longueur_max = longueur_face1 >= longueur_face2 ? longueur_face1 :
                 longueur_face2;
  diametre_element = longueur_face3 >= longueur_max ? longueur_face3 :
                     longueur_max;
  return diametre_element;
}
References Zone_VF::elem_faces(), longueur(), and zone_vef().
Referenced by coefficient_penalisation().
domaine()
const Domaine & Op_Diff_VEF_Face_Penalise::domaine () const inline private
Definition at line 172 of file Op_Diff_VEF_Face_Penalise.h.
{
  return zone().domaine();
}
References Zone::domaine(), and zone().
Referenced by longueur().
duplique()
int Op_Diff_VEF_Face_Penalise::duplique () const override virtual
Reimplemented from Op_Diff_VEF_Face.
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
element_commun()
int Op_Diff_VEF_Face_Penalise::element_commun (const int Face1, const int Face2) const protected
fonction membre qui renvoie le numero de l'element contenant Face1 et Face2
s'il existe et renvoie -1 sinon.
Definition at line 538 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans element_commun" << finl;
  /* Les elements voisins de Face1 */
  const int voisin1_Face1 = zone_vef().face_voisins(Face1,1);
  const int voisin2_Face1 = zone_vef().face_voisins(Face1,0);
  /* Les elements voisins de Face2 */
  const int voisin1_Face2 = zone_vef().face_voisins(Face2,1);
  const int voisin2_Face2 = zone_vef().face_voisins(Face2,0);
  /* On cherche l'element commun */
  if (voisin1_Face1 != -1)
    if (voisin1_Face1 == voisin1_Face2 || voisin1_Face1 == voisin2_Face2)
      return voisin1_Face1;
  if (voisin2_Face1 != -1)
    if (voisin2_Face1 == voisin1_Face2 || voisin2_Face1 == voisin2_Face2)
      return voisin2_Face1;
  Cerr << " Op_Diff_VEF_Face_Penalise::element_commun()" << finl;
  Cerr << "Attention: la face " << Face1 << " et la face " << Face2
       << "n'ont pas d'element commun" << finl;
  Cerr << "Je sors de elements_communs" << finl;
  return -1;
}
References Cerr, Zone_VF::face_voisins(), finl, and zone_vef().
Referenced by autre_face().
faces_communes()
void Op_Diff_VEF_Face_Penalise::faces_communes (const int Face1, const int Face2, IntList & Face_commune) const protected
fonction membre qui renvoie la liste des faces appartenant
au voisinage de Face1 ET de Face2.
Definition at line 440 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr <<"J'entre dans faces_communes" << finl;
  /* On vide d'abord Faces_commnunes pour eviter les erreurs. */
  if (! Faces_communes.est_vide() ) Faces_communes.vide();
  /* Declaration des parametres locaux a la procedure */
  IntList voisinage_Face1,voisinage_Face2;
  int nb_element_voisinage_Face2;
  /* On calcule chacun des voisinages de Face1 et Face2 */
  voisinage(Face1,voisinage_Face1);
  voisinage(Face2,voisinage_Face2);
  /* Ensuite, on retrouve les faces communes a ces 2 voisinages. */
  for (nb_element_voisinage_Face2 = 0;
       nb_element_voisinage_Face2 < voisinage_Face2.size();
       nb_element_voisinage_Face2++)
    {
      const int numero_face_voisinage_Face2 =
        voisinage_Face2[nb_element_voisinage_Face2];
      if (voisinage_Face1.contient(numero_face_voisinage_Face2))
        Faces_communes.add_if_not(numero_face_voisinage_Face2);
    }//fin du for
// Cerr << "Je sors de faces_communes" << finl;
}
References TRUSTList< _TYPE_ >::add_if_not(), TRUSTList< _TYPE_ >::contient(), TRUSTListElem< _TYPE_ >::est_vide(), TRUSTList< _TYPE_ >::size(), TRUSTList< _TYPE_ >::vide(), and voisinage().
Referenced by ajouter().
get_info()
const Type_info * Op_Diff_VEF_Face_Penalise::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_Face.
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
info()
const Type_info * Op_Diff_VEF_Face_Penalise::info () static
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
longueur()
double Op_Diff_VEF_Face_Penalise::longueur (const int Face) const inline protected
Definition at line 118 of file Op_Diff_VEF_Face_Penalise.h.
{
  double x_sommet1,x_sommet2;
  double y_sommet1,y_sommet2;
  int sommet1 = zone_vef().face_sommets(Face,0);
  int sommet2 = zone_vef().face_sommets(Face,1);
  x_sommet1 = domaine().coord(sommet1,0);
  y_sommet1 = domaine().coord(sommet1,1);
  x_sommet2 = domaine().coord(sommet2,0);
  y_sommet2 = domaine().coord(sommet2,1);
  return sqrt( pow(x_sommet1 - x_sommet2,2) + pow(y_sommet1 - y_sommet2,2) );
}
References Domaine::coord(), domaine(), Zone_VF::face_sommets(), and zone_vef().
Referenced by ajouter(), and diametre().
printOn()
Sortie & Op_Diff_VEF_Face_Penalise::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VEF_Face.
Definition at line 22 of file Op_Diff_VEF_Face_Penalise.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VEF_Face_Penalise::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VEF_Face.
Definition at line 29 of file Op_Diff_VEF_Face_Penalise.cpp.
{
  /* REMARQUE IMPORTANTE: on a cree cette classe par derivation mais
   * mais elle doit uniquement s'appliquer sur des equations de
   * Navier-Stokes non turbulentes d'ou les tests suivants
   */
  Cerr<<"je suis dans Op_Diff_VEF_Face_Penalise::readOn()"<<finl;
  /* On teste la dimension du probleme car la theorie n'a ete validee
   * que sur du 2D
   */
  if (dimension != 2)
    {
      Cerr << "Erreur dans Op_Diff_VEF_Face_Penalise::readOn()" << finl;
      Cerr << "La dimension du probleme doit etre 2" << finl;
      Process::exit();
    }
  return is ;
}
References Cerr, Objet_U::dimension, Process::exit(), and finl.
reduction()
void Op_Diff_VEF_Face_Penalise::reduction (const IntList & Liste1, const IntList & Liste2, IntList & Liste_reduite) const protected
Definition at line 481 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans reduction" << finl;
  /* On nettoie Liste_reduite afin d'eviter les erreurs */
  if (! Liste_reduite.est_vide() ) Liste_reduite.vide();
  /* Declaration des parametres locaux a la procedure */
  const IntList *liste_de_plus_petite_taille,*liste_de_plus_grande_taille;
  int nb_element_dans_liste;
  /* On teste la taille des listes passees en parametres puis
   * on effectue l'allocation en fonction du resultat.
   */
  if (Liste1.size() >= Liste2.size())
    {
      liste_de_plus_petite_taille = &Liste2;
      liste_de_plus_grande_taille = &Liste1;
    }
  else
    {
      liste_de_plus_petite_taille = &Liste1;
      liste_de_plus_grande_taille = &Liste2;
    }
  /* Enfin, on supprime de la liste_de_plus_grande_taille,
   * les elements de la liste_de_plus_petite_taille si ceux-ci
   * sont bien dans la liste_de_plus_grande_taille.
   */
  for (int ll = 0 ; ll < (*liste_de_plus_grande_taille).size() ; ll++)
    Liste_reduite.add( (*liste_de_plus_grande_taille)[ll] );
  for (nb_element_dans_liste = 0;
       nb_element_dans_liste < (*liste_de_plus_petite_taille).size();
       nb_element_dans_liste++)
    if
    (Liste_reduite.contient( (*liste_de_plus_petite_taille)
                             [nb_element_dans_liste] ) )
      Liste_reduite.suppr( (*liste_de_plus_petite_taille)
                           [nb_element_dans_liste] );
// Cerr << "Je sors de reduction" << finl;
}
References TRUSTList< _TYPE_ >::add(), TRUSTList< _TYPE_ >::contient(), TRUSTListElem< _TYPE_ >::est_vide(), TRUSTList< _TYPE_ >::size(), TRUSTList< _TYPE_ >::suppr(), and TRUSTList< _TYPE_ >::vide().
Referenced by ajouter().
self_cast() [1/2]
const Op_Diff_VEF_Face_Penalise & Op_Diff_VEF_Face_Penalise::self_cast (const Objet_U & r) static
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
self_cast() [2/2]
Op_Diff_VEF_Face_Penalise & Op_Diff_VEF_Face_Penalise::self_cast (Objet_U & r) static
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
signe()
double Op_Diff_VEF_Face_Penalise::signe (const int Face1, const int Face2) const protected
Definition at line 345 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans signe" << finl;
  /* Parametres locaux a la procedure */
  int numero_local;
  /* On recupere le nombre de sommets des faces
   * des elements constituant la zone discretisee.
   * REM: on exclut le prisme par convention.
   */
  const int nb_sommets_par_face = zone_vef().nb_som_face();
  /* On cree une liste qui contient les sommets de la Face2 */
  IntList sommets_Face2;
  for (numero_local = 0 ; numero_local < nb_sommets_par_face ; numero_local++)
    sommets_Face2.add(zone_vef().face_sommets(Face2,numero_local));
  /* Enfin, on regarde si des sommets de la Face2 appartiennent
   * a la Face1.
   * Si oui, alors on retourne 1 sinon on retourne -1
   */
  for (numero_local = 0; numero_local < nb_sommets_par_face ; numero_local++)
    if ( sommets_Face2.contient(zone_vef().face_sommets(Face1,numero_local)))
      return 1.;
  return -1.;
// Cerr << "Je sors de signe" << finl;
}
References TRUSTList< _TYPE_ >::add(), TRUSTList< _TYPE_ >::contient(), Zone_VF::nb_som_face(), and zone_vef().
Referenced by ajouter().
taille_memoire()
unsigned Op_Diff_VEF_Face_Penalise::taille_memoire () const override virtual
Reimplemented from Op_Diff_VEF_Face.
Definition at line 19 of file Op_Diff_VEF_Face_Penalise.cpp.
voisinage() [1/2]
void Op_Diff_VEF_Face_Penalise::voisinage (const int Numero_face, IntList & Voisinage) const protected
methode qui calcule le voisinage d'une face.
Definition at line 215 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans voisinage pour un numero face" << finl;
  /* On vide la liste Voisinage pour eviter les mauvaises surprises */
  if (! Voisinage.est_vide() ) Voisinage.vide();
  /* Declaration des principaux parametres locaux. */
  int numero_local;
  /* Le nombre de faces des elements constituant la zone
   * de discretisation.
   * REM: on suppose que l'on ne travaille pas sur des prismes.
   */
  const int nb_faces_element = zone().nb_faces_elem();
  /* Les elements voisins de Numero_face */
  const int voisin1 = zone_vef().face_voisins(Numero_face,1);
  const int voisin2 = zone_vef().face_voisins(Numero_face,0);
  /* Ici, on recupere les faces de voisin*
   * que l'on injecte dans la liste Voisinage.
   * Il faut donc que l'element existe d'ou le premier test realise.
   */
  if (voisin1 != -1)
    {
      for (numero_local = 0; numero_local < nb_faces_element; numero_local++)
        {
          /* On recupere le numero global de chacune des
           * faces de voisin*
           */
          const int numero_global_face =
            zone_vef().elem_faces(voisin1,numero_local);
          /* Puis on place ce numero dans la liste Voisinage. */
          Voisinage.add_if_not(numero_global_face);
        }//fin du for
    }//fin du if
  if (voisin2 != -1)
    {
      for (numero_local = 0; numero_local < nb_faces_element; numero_local++)
        {
          /* On recupere le numero global de chacune des
           * faces de numero_element_*
           */
          const int numero_global_face =
            zone_vef().elem_faces(voisin2,numero_local);
          /* Puis on place ce numero dans la liste Voisinage. */
          Voisinage.add_if_not(numero_global_face);
        }//!< fin du for
    }//fin du if
// Cerr << "Je sors de voisinage pour un numero de face" << finl;
}
References TRUSTList< _TYPE_ >::add_if_not(), Zone_VF::elem_faces(), TRUSTListElem< _TYPE_ >::est_vide(), Zone_VF::face_voisins(), Zone::nb_faces_elem(), TRUSTList< _TYPE_ >::vide(), zone(), and zone_vef().
Referenced by ajouter(), faces_communes(), and voisinage().
voisinage() [2/2]
void Op_Diff_VEF_Face_Penalise::voisinage (const IntList & Ensemble_faces, IntList & Voisinage) const protected
methode qui calcule le voisinage d'une liste de faces.
Definition at line 287 of file Op_Diff_VEF_Face_Penalise.cpp.
{
// Cerr << "J'entre dans voisinage pour un ensemble de face" << finl;
  /* On vide la liste Voisinage pour eviter les mauvaises surprises */
  if (! Voisinage.est_vide() ) Voisinage.vide();
  /* Declaration des principaux parametres locaux. */
  int nb_elements_Ensemble_faces,nb_elements_liste_temporaire;
  IntList liste_temporaire;
  for (nb_elements_Ensemble_faces = 0;
       nb_elements_Ensemble_faces < Ensemble_faces.size();
       nb_elements_Ensemble_faces++)
    {
      /* Parametre interne a la boucle */
      const int numero_face_dans_Ensemble_faces =
        Ensemble_faces[nb_elements_Ensemble_faces];
      /* On vide la liste temporaire a chaque fois que l'on change de face */
      if (! liste_temporaire.est_vide() ) liste_temporaire.vide();
      /* Dans la liste temporaire, on place le voisinage
       * de numero_face_dans_Ensemble_faces
       */
      voisinage(numero_face_dans_Ensemble_faces,liste_temporaire);
// Cerr << "Taille liste temporaire " << liste_temporaire.size() << finl;
      for (nb_elements_liste_temporaire = 0;
           nb_elements_liste_temporaire < liste_temporaire.size();
           nb_elements_liste_temporaire++)
        {
// Cerr << "les elements " << liste_temporaire[nb_elements_liste_temporaire] << finl;
          /* Parametre interne a la deuxieme boucle */
          const int numero_face_dans_liste_temporaire =
            liste_temporaire[nb_elements_liste_temporaire];
          /* Enfin, on stoke dans Voisinage */
          Voisinage.add_if_not(numero_face_dans_liste_temporaire);
        }//fin du deuxieme for
    }//fin du premier for
// Cerr << "Je sors de voisinage pour un ensemble face" << finl;
}
References TRUSTList< _TYPE_ >::add_if_not(), TRUSTListElem< _TYPE_ >::est_vide(), TRUSTList< _TYPE_ >::size(), TRUSTList< _TYPE_ >::vide(), and voisinage().
zone()
const Zone & Op_Diff_VEF_Face_Penalise::zone () const inline private
Definition at line 167 of file Op_Diff_VEF_Face_Penalise.h.
{
  return zone_vef().zone();
}
References Zone_dis_base::zone(), and zone_vef().
Referenced by autre_face(), domaine(), and voisinage().
zone_cl()
const Zone_Cl_VEF & Op_Diff_VEF_Face_Penalise::zone_cl () const inline private
Definition at line 162 of file Op_Diff_VEF_Face_Penalise.h.
{
  return la_zcl_vef.valeur();
}
References Op_Diff_VEF_base::la_zcl_vef, and Ref_Zone_Cl_VEF::valeur().
zone_vef()
const Zone_VEF & Op_Diff_VEF_Face_Penalise::zone_vef () const inline private
Definition at line 157 of file Op_Diff_VEF_Face_Penalise.h.
{
  return la_zone_vef.valeur();
}
References Op_Diff_VEF_base::la_zone_vef, and Ref_Zone_VEF::valeur().
Referenced by ajouter(), autre_face(), coefficient_penalisation(), diametre(), element_commun(), longueur(), signe(), voisinage(), and zone().
Member Data Documentation
info_obj
const Type_info Op_Diff_VEF_Face_Penalise::info_obj static
Definition at line 27 of file Op_Diff_VEF_Face_Penalise.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Diff_VEF_Face_Penalise.h
src/VEF/Operateurs/Op_Diff_VEF_Face_Penalise.cpp