TRUST: grad_Champ_Face_PolyMAC_P0 Class Reference
grad_Champ_Face_PolyMAC_P0 Class Reference
class grad_Champ_Face_PolyMAC_P0 for the calculation of the gradient
This field is a Champ_Fonc_Face_PolyMAC_P0 that calculates the gradient of a velocity field
grad_u(f, n*D + dU) returns the gradient of the dU velocity component in the phase n at face f
grad_u(nf_tot + e*D + dX, n*D + dU) returns the gradient of the dU velocity component in the phase n in element e along the dX component
(i.e. = dU/dX)
In 2D, the gradient at the element e in phase n is equal to :
| grad_u(nf_tot + e*D + 0, n*D + 0) grad_u(nf_tot + e*D + 1, n*D + 0) |
grad_u = | |
| grad_u(nf_tot + e*D + 0, n*D + 1) grad_u(nf_tot + e*D + 1, n*D + 1) |
The gradient is calculated using past values of the velocity
We compute the gradient at the faces for all velocity components,
then interpolate it to obtain the gradient at the elements
#include <grad_Champ_Face_PolyMAC_P0.h>
Public Member Functions
grad_Champ_Face_PolyMAC_P0 ()
~grad_Champ_Face_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int fixer_nb_valeurs_nodales (int n) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
void mettre_a_jour (double) override
Mise a jour en temps du champ.
void associer_champ (const Champ_Face_PolyMAC_P0 &)
void me_calculer (double)
void associer_zone_Cl_dis_base (const Zone_Cl_dis_base &)
virtual Champ_Face_PolyMAC_P0 & champ_a_deriver ()
virtual const Champ_Face_PolyMAC_P0 & champ_a_deriver () const
void update_tab_grad (int full_stencil)
Mise a jour des tables utilisees dans fgrad.
void calc_gradfve ()
Mise a jour du gradient aux faces de la vitesse aux elements.
void update_ge ()
Calcul du gradient aux elements a partir du gradient aux faces ; base sur la methode similaire de Champ_Face_PolyMAC_P0.
void init_grad ()
Public Member Functions inherited from Champ_Fonc_Face_PolyMAC
Champ_Fonc_Face_PolyMAC ()
~Champ_Fonc_Face_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double) override
Mise a jour en temps du champ.
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const override
renvoie les valeurs aux sommets du Domaine dom
DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const override
renvoie la compo eme valeur aux sommets de dom.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
const Zone_VF & zone_vf () const
int fixer_nb_valeurs_nodales (int n) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
Public Member Functions inherited from Champ_Fonc_base
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static grad_Champ_Face_PolyMAC_P0 & self_cast (Objet_U &)
static const grad_Champ_Face_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_Face_PolyMAC
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc_Face_PolyMAC & self_cast (Objet_U &)
static const Champ_Fonc_Face_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_base
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
IntTab gradve_d
IntTab gradve_e
Tables utilisees dans fgrad pour obtenir le grad aux faces de la vitesse aux elems.
DoubleTab gradve_w
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_Face_PolyMAC
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Champ_Fonc_Face_PolyMAC
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Champ_base & le_champ (void)
virtual const Champ_base & le_champ (void) const
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_Cl_PolyMAC la_Zone_Cl_PolyMAC
Ref_Champ_Face_PolyMAC_P0 champ_
Conds_lim cls_g
IntTab fcl_g
int is_init = 0
Protected Attributes inherited from Champ_Fonc_Face_PolyMAC
Ref_Zone_VF ref_zone_vf_
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
class grad_Champ_Face_PolyMAC_P0 for the calculation of the gradient
This field is a Champ_Fonc_Face_PolyMAC_P0 that calculates the gradient of a velocity field
grad_u(f, n*D + dU) returns the gradient of the dU velocity component in the phase n at face f
grad_u(nf_tot + e*D + dX, n*D + dU) returns the gradient of the dU velocity component in the phase n in element e along the dX component
(i.e. = dU/dX)
In 2D, the gradient at the element e in phase n is equal to :
| grad_u(nf_tot + e*D + 0, n*D + 0) grad_u(nf_tot + e*D + 1, n*D + 0) |
grad_u = | |
| grad_u(nf_tot + e*D + 0, n*D + 1) grad_u(nf_tot + e*D + 1, n*D + 1) |
The gradient is calculated using past values of the velocity
We compute the gradient at the faces for all velocity components,
then interpolate it to obtain the gradient at the elements
Definition at line 49 of file grad_Champ_Face_PolyMAC_P0.h.
Constructor & Destructor Documentation
grad_Champ_Face_PolyMAC_P0()
grad_Champ_Face_PolyMAC_P0::grad_Champ_Face_PolyMAC_P0 ()
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
~grad_Champ_Face_PolyMAC_P0()
grad_Champ_Face_PolyMAC_P0::~grad_Champ_Face_PolyMAC_P0 ()
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
Member Function Documentation
associer_champ()
void grad_Champ_Face_PolyMAC_P0::associer_champ (const Champ_Face_PolyMAC_P0 & ch) inline
Definition at line 91 of file grad_Champ_Face_PolyMAC_P0.h.
{
  Cerr << "On associe le gradient de U au champ de vitesse " << finl ;
  champ_= ch;
}
References Cerr, champ_, and finl.
Referenced by PolyMAC_P0_discretisation::grad_u().
associer_zone_Cl_dis_base()
void grad_Champ_Face_PolyMAC_P0::associer_zone_Cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) inline
Definition at line 97 of file grad_Champ_Face_PolyMAC_P0.h.
{
  la_Zone_Cl_PolyMAC  = (const Zone_Cl_PolyMAC&) la_zone_Cl_dis_base;
}
References la_Zone_Cl_PolyMAC.
Referenced by PolyMAC_P0_discretisation::grad_u().
calc_gradfve()
void grad_Champ_Face_PolyMAC_P0::calc_gradfve ()
Mise a jour du gradient aux faces de la vitesse aux elements.
< Coordonnees de la vitesse et phase
Definition at line 107 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  const Zone_PolyMAC_P0&            zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  const Champ_Face_PolyMAC_P0&        ch = ref_cast(Champ_Face_PolyMAC_P0, champ_a_deriver());
  const IntTab&                   fcl = fcl_g;
  const Conds_lim&                cls = cls_g;
  int f, n;
  int d_U ; //coordonnee de la vitesse
  int D = dimension;
  int N = champ_a_deriver().valeurs().line_size(); //nombre phases
  int ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot(), nf = zone.nb_faces();
  const DoubleTab& tab_ch = ch.passe();
  DoubleTab&          val = valeurs();
  for (f = 0; f < nf; f++)
    {
      for (d_U = 0; d_U < D; d_U++)
        for (n = 0; n < N; n++) //!< Coordonnees de la vitesse et phase
          {
            val(f, d_U + n*D) = 0;
            for (int j = gradve_d(f); j < gradve_d(f+1) ; j++)
              {
                int e = gradve_e(j);
                int f_bord;
                if ( e < ne_tot) //contrib d'un element
                  {
                    double val_e = tab_ch(nf_tot+ d_U + e * D, n);
                    val(f, d_U + n*D) += gradve_w(j, n) * val_e;
                  }
                else if (fcl(f_bord = e - ne_tot, 0) == 3) //contrib d'un bord : seul Dirichlet contribue
                  {
                    double val_f_bord = ref_cast(Dirichlet, cls[fcl(f_bord, 1)].valeur()).val_imp(fcl(f_bord, 2), N * d_U + n);
                    val(f, d_U + n*D) += gradve_w(j, n) * val_f_bord;
                  }
              }
          }
    }
}
References champ_a_deriver(), cls_g, Objet_U::dimension, fcl_g, gradve_d, gradve_e, gradve_w, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Champ_Inc_base::passe(), ref_cast, valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Fonc_Face_PolyMAC::zone_vf().
Referenced by me_calculer().
champ_a_deriver() [1/2]
Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::champ_a_deriver () inline virtual
Definition at line 102 of file grad_Champ_Face_PolyMAC_P0.h.
{
  return champ_.valeur();
}
References champ_, and Ref_Champ_Face_PolyMAC_P0::valeur().
Referenced by calc_gradfve(), init_grad(), and update_tab_grad().
champ_a_deriver() [2/2]
const Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::champ_a_deriver () const inline virtual
Definition at line 106 of file grad_Champ_Face_PolyMAC_P0.h.
{
  return champ_.valeur();
}
References champ_, and Ref_Champ_Face_PolyMAC_P0::valeur().
cree_instance()
Objet_U * grad_Champ_Face_PolyMAC_P0::cree_instance () static
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
duplique()
int grad_Champ_Face_PolyMAC_P0::duplique () const override virtual
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
fixer_nb_valeurs_nodales()
int grad_Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 48 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  const Champ_Fonc_base& self = ref_cast(Champ_Fonc_base, *this);
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,self.zone_dis_base());
  assert(n < 0);
  const MD_Vector& md = zone.mdv_ch_face;
// Probleme: nb_comp vaut 2 mais on ne veut qu'une dimension !!!
// HACK :
  int old_nb_compo = nb_compo_;
  nb_compo_ /= dimension;
  creer_tableau_distribue(md);
  nb_compo_ = old_nb_compo;
  return n;
}
References Champ_Fonc_base::creer_tableau_distribue(), Objet_U::dimension, Zone_PolyMAC_P0::mdv_ch_face, Field_base::nb_compo_, ref_cast, and Champ_base::zone_dis_base().
Referenced by PolyMAC_P0_discretisation::grad_u().
get_info()
const Type_info * grad_Champ_Face_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
info()
const Type_info * grad_Champ_Face_PolyMAC_P0::info () static
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
init_grad()
void grad_Champ_Face_PolyMAC_P0::init_grad ()
< CAL du champ a deriver
< volontairement une copie
< volontairement une copie
Definition at line 66 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  const IntTab&                fcl = champ_a_deriver().fcl();
// const Zone_PolyMAC_P0&      zone = ref_cast(Zone_PolyMAC_P0, zone_vf());
// int nf_tot = zone.nb_faces_tot();
  const Champ_Face_PolyMAC_P0&   ch = ref_cast(Champ_Face_PolyMAC_P0, champ_a_deriver());
  const Conds_lim&              cls = ch.zone_Cl_dis().les_conditions_limites(); //!< CAL du champ a deriver
  cls_g = cls ; //!< volontairement une copie
  fcl_g = fcl ; //!< volontairement une copie
  for (int j = 0 ; j<cls.size(); j++)
    {
      Cond_lim& cond_lim_loc = cls_g(j);
      if sub_type(Frottement_impose_base, cond_lim_loc.valeur()) ref_cast(Frottement_impose_base, cond_lim_loc.valeur()).is_grad_v();
    }
  is_init = 1 ;
  return ;
}
References champ_a_deriver(), cls_g, Champ_Face_PolyMAC::fcl(), fcl_g, is_init, Zone_Cl_dis::les_conditions_limites(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), and Champ_Inc_base::zone_Cl_dis().
Referenced by me_calculer().
me_calculer()
void grad_Champ_Face_PolyMAC_P0::me_calculer (double tps)
< calcule les coefficients de fgrad requis pour le calcul du champ aux faces
< calcule le champ aux elements a partir du champ aux faces
Definition at line 88 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  if (!is_init) init_grad();
  for (int j = 0 ; j<cls_g.size(); j++)
    cls_g(j)->mettre_a_jour(tps);
  update_tab_grad(0); //!< calcule les coefficients de fgrad requis pour le calcul du champ aux faces
  calc_gradfve();
  update_ge(); //!< calcule le champ aux elements a partir du champ aux faces
  valeurs().echange_espace_virtuel();
}
References calc_gradfve(), cls_g, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), init_grad(), is_init, Conds_lim::mettre_a_jour(), vect_impl::size(), update_ge(), update_tab_grad(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
mettre_a_jour()
void grad_Champ_Face_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 85 of file grad_Champ_Face_PolyMAC_P0.h.
{
  if (temps()!=tps) me_calculer(tps) ;
  Champ_Fonc_base::mettre_a_jour(tps);
}
References me_calculer(), Champ_Fonc_base::mettre_a_jour(), and Champ_base::temps().
printOn()
Sortie & grad_Champ_Face_PolyMAC_P0::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 35 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & grad_Champ_Face_PolyMAC_P0::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 43 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  return s ;
}
self_cast() [1/2]
const grad_Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
self_cast() [2/2]
grad_Champ_Face_PolyMAC_P0 & grad_Champ_Face_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
taille_memoire()
unsigned grad_Champ_Face_PolyMAC_P0::taille_memoire () const override virtual
Reimplemented from Champ_Fonc_Face_PolyMAC.
Definition at line 29 of file grad_Champ_Face_PolyMAC_P0.cpp.
update_ge()
void grad_Champ_Face_PolyMAC_P0::update_ge ()
Calcul du gradient aux elements a partir du gradient aux faces ; base sur la methode similaire de Champ_Face_PolyMAC_P0.
Definition at line 148 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  DoubleTab& val = valeurs() ;
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0,zone_vf());
  const DoubleVect& ve = zone.volumes(), &fs = zone.face_surfaces();
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins();
  const DoubleTab& xp = zone.xp(), &xv = zone.xv();
  int e, f, j, d, D = dimension, n, N = val.line_size(), ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot();
  double fac;
  for (e = 0; e < ne_tot; e++)
    {
      for (d = 0; d < D; d++)
        for (n = 0; n < N; n++) val(nf_tot + D * e + d, n) = 0;
      for (j = 0; j < e_f.dimension(1) && (f = e_f(e, j)) >= 0; j++)
        for (fac = (e == f_e(f, 0) ? 1 : -1) * fs(f) / ve(e), d = 0; d < D; d++)
          for (n = 0; n < N; n++)
            val(nf_tot + D * e + d, n) += fac * (xv(f, d) - xp(e, d)) * val(f, n);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), ref_cast, Champ_Don_base::valeurs(), Zone_VF::volumes(), Zone_VF::xp(), Zone_VF::xv(), and Champ_Fonc_Face_PolyMAC::zone_vf().
Referenced by me_calculer().
update_tab_grad()
void grad_Champ_Face_PolyMAC_P0::update_tab_grad (int full_stencil)
Mise a jour des tables utilisees dans fgrad.
< CAL du champ a deriver
Definition at line 99 of file grad_Champ_Face_PolyMAC_P0.cpp.
{
  const IntTab&                f_cl = fcl_g;
  const Zone_PolyMAC_P0&       zone = ref_cast(Zone_PolyMAC_P0, zone_vf());
  const Conds_lim&              cls = cls_g; //!< CAL du champ a deriver
  zone.fgrad(champ_a_deriver().valeurs().line_size(), 0, cls, f_cl, NULL, NULL, 1, full_stencil, gradve_d, gradve_e, gradve_w);
}
References champ_a_deriver(), cls_g, fcl_g, Zone_PolyMAC_P0::fgrad(), gradve_d, gradve_e, gradve_w, ref_cast, Champ_Don_base::valeurs(), and Champ_Fonc_Face_PolyMAC::zone_vf().
Referenced by me_calculer().
Member Data Documentation
champ_
Ref_Champ_Face_PolyMAC_P0 grad_Champ_Face_PolyMAC_P0::champ_ protected
Definition at line 78 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by associer_champ(), and champ_a_deriver().
cls_g
Conds_lim grad_Champ_Face_PolyMAC_P0::cls_g protected
Definition at line 80 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by calc_gradfve(), init_grad(), me_calculer(), and update_tab_grad().
fcl_g
IntTab grad_Champ_Face_PolyMAC_P0::fcl_g protected
Definition at line 81 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by calc_gradfve(), init_grad(), and update_tab_grad().
gradve_d
IntTab grad_Champ_Face_PolyMAC_P0::gradve_d mutable
Definition at line 68 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by calc_gradfve(), and update_tab_grad().
gradve_e
IntTab grad_Champ_Face_PolyMAC_P0::gradve_e
Tables utilisees dans fgrad pour obtenir le grad aux faces de la vitesse aux elems.
Definition at line 68 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by calc_gradfve(), and update_tab_grad().
gradve_w
DoubleTab grad_Champ_Face_PolyMAC_P0::gradve_w mutable
Definition at line 69 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by calc_gradfve(), and update_tab_grad().
info_obj
const Type_info grad_Champ_Face_PolyMAC_P0::info_obj static
Definition at line 53 of file grad_Champ_Face_PolyMAC_P0.h.
is_init
int grad_Champ_Face_PolyMAC_P0::is_init = 0 protected
Definition at line 82 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by init_grad(), and me_calculer().
la_Zone_Cl_PolyMAC
Ref_Zone_Cl_PolyMAC grad_Champ_Face_PolyMAC_P0::la_Zone_Cl_PolyMAC protected
Definition at line 77 of file grad_Champ_Face_PolyMAC_P0.h.
Referenced by associer_zone_Cl_dis_base().
The documentation for this class was generated from the following files:
src/PolyMAC/Champs/grad_Champ_Face_PolyMAC_P0.h
src/PolyMAC/Champs/grad_Champ_Face_PolyMAC_P0.cpp