TRUST: Echange_contact_PolyMAC_P0 Class Reference
Echange_contact_PolyMAC_P0 Class Reference
#include <Echange_contact_PolyMAC_P0.h>
Public Member Functions
Echange_contact_PolyMAC_P0 ()
~Echange_contact_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void init_op () const
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
void init_fs_dist () const
Public Member Functions inherited from Echange_externe_impose
Echange_externe_impose ()
~Echange_externe_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Echange_impose_base
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_contact_PolyMAC_P0 & self_cast (Objet_U &)
static const Echange_contact_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_externe_impose
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_externe_impose & self_cast (Objet_U &)
static const Echange_externe_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_impose_base
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Ref_Front_VF fvf
Ref_Front_VF o_fvf
int i_fvf
int i_o_fvf
Ref_Op_Diff_PolyMAC_P0_Elem diff
Ref_Op_Diff_PolyMAC_P0_Elem o_diff
IntTab f_dist
std::map< int, int > s_dist
int fs_dist_init_ = 0
double invh_paroi
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Echange_externe_impose
static const Type_info info_obj
Static Public Attributes inherited from Echange_impose_base
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
Protected Member Functions inherited from Echange_externe_impose
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void verifie_ch_init_nb_comp () const override
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Protected Member Functions inherited from Echange_impose_base
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom nom_autre_pb_
Nom nom_bord_
Nom nom_champ_
Protected Attributes inherited from Echange_impose_base
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
Definition at line 40 of file Echange_contact_PolyMAC_P0.h.
Constructor & Destructor Documentation
Echange_contact_PolyMAC_P0()
Echange_contact_PolyMAC_P0::Echange_contact_PolyMAC_P0 ()
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
~Echange_contact_PolyMAC_P0()
Echange_contact_PolyMAC_P0::~Echange_contact_PolyMAC_P0 ()
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
Member Function Documentation
cree_instance()
Objet_U * Echange_contact_PolyMAC_P0::cree_instance () static
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
duplique()
int Echange_contact_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
get_info()
const Type_info * Echange_contact_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
info()
const Type_info * Echange_contact_PolyMAC_P0::info () static
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
init_fs_dist()
void Echange_contact_PolyMAC_P0::init_fs_dist () const
Definition at line 71 of file Echange_contact_PolyMAC_P0.cpp.
{
  if (fs_dist_init_) return; //deja fait
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, fvf->zone_dis()), &o_zone = ref_cast(Zone_PolyMAC_P0, o_fvf->zone_dis());
  const DoubleTab& xv = zone.xv(), &o_xv = o_zone.xv(), &xs = zone.zone().domaine().coord_sommets(), &o_xs = o_zone.zone().domaine().coord_sommets();
  const IntTab& f_s = zone.face_sommets(), &o_f_s = o_zone.face_sommets();
  int i, j, f, o_f, s, o_s, nf_tot = fvf->nb_faces_tot(), o_nf_tot = o_fvf->nb_faces_tot(), d, D = dimension;
  f_dist.resize(nf_tot);
  std::set<int> s_som, s_o_som; //sommets de chaque cote
  for (i = 0; i <   nf_tot; i++)
    for (f =   fvf->num_face(i), j = 0; j <   f_s.dimension(1) && (s =   f_s(f, j)) >= 0; j++)   s_som.insert(s);
  for (i = 0; i < o_nf_tot; i++)
    for (f = o_fvf->num_face(i), j = 0; j < o_f_s.dimension(1) && (s = o_f_s(f, j)) >= 0; j++) s_o_som.insert(s);
  std::vector<int> som(s_som.begin(), s_som.end()), o_som(s_o_som.begin(), s_o_som.end()); //en vecteur
  int ns_tot = som.size(), o_ns_tot = o_som.size();
  DoubleTrav xvf(nf_tot, D), o_xvf(o_nf_tot, D), xsf(ns_tot, D), o_xsf(o_ns_tot, D); //positions locales/distantes -> pour calcul de correspondance
  for (i = 0; i <   nf_tot; i++)
    for (d = 0; d < D; d++)   xvf(i, d) =   xv(  fvf->num_face(i), d);
  for (i = 0; i < o_nf_tot; i++)
    for (d = 0; d < D; d++) o_xvf(i, d) = o_xv(o_fvf->num_face(i), d);
  for (i = 0; i <   ns_tot; i++)
    for (d = 0; d < D; d++)   xsf(i, d) =   xs(  som[i], d);
  for (i = 0; i < o_ns_tot; i++)
    for (d = 0; d < D; d++) o_xsf(i, d) = o_xs(o_som[i], d);
#ifdef MEDCOUPLING_
  MCAuto<DataArrayDouble> fdad(DataArrayDouble::New()), o_fdad(DataArrayDouble::New()), sdad(DataArrayDouble::New()), o_sdad(DataArrayDouble::New());
  fdad->useExternalArrayWithRWAccess(xvf.addr(), nf_tot, D), o_fdad->useExternalArrayWithRWAccess(o_xvf.addr(), o_nf_tot, D);
  sdad->useExternalArrayWithRWAccess(xsf.addr(), ns_tot, D), o_sdad->useExternalArrayWithRWAccess(o_xsf.addr(), o_ns_tot, D);
// point de o_{f,s}dad le plus proche de chaque point de {f,s}dad
  MCAuto<DataArrayInt> f_idx(nf_tot && o_nf_tot ? o_fdad->findClosestTupleId(fdad) : NULL), s_idx(ns_tot && o_ns_tot ? o_sdad->findClosestTupleId(sdad) : NULL);
  for (i = 0; i < nf_tot; i++) //remplissage de f_dist : face distante si coincidence, -1 sinon
    {
      f = fvf->num_face(i), o_f = o_nf_tot ? o_fvf->num_face(f_idx->getIJ(i, 0)) : -1;
      double d2 = o_f >= 0 ? zone.dot(&xv(f, 0), &xv(f, 0), &o_xv(o_f, 0), &o_xv(o_f, 0)) : 1e8;
      if (d2 < 1e-12) f_dist(i) = o_f;
      else f_dist(i) = -1;
      if (i < fvf->nb_faces() && d2 >= 1e-12)
        Process::exit(Nom("Echange_contact_PolyMAC_P0: missing opposite faces detected between ") + fvf->le_nom() + " and " + o_fvf->le_nom()
                      + " ! Have you used Decouper_multi?");
    }
  for (i = 0; i < ns_tot; i++) //remplissage de s_dist
    {
      s = som[i], o_s = o_ns_tot ? o_som[s_idx->getIJ(i, 0)] : -1;
      if (o_s >= 0 && zone.dot(&xs(s, 0), &xs(s, 0), &o_xs(o_s, 0), &o_xs(o_s, 0)) < 1e-12) s_dist[s] = o_s;
    }
#else
  Process::exit("Echange_contact_PolyMAC_P0 : MEDCoupling is required!");
#endif
  fs_dist_init_ = 1;
}
References TRUSTArray< _TYPE_ >::addr(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_Poly_base::dot(), Process::exit(), f_dist, Zone_VF::face_sommets(), fs_dist_init_, fvf, Frontiere_dis_base::le_nom(), Front_VF::nb_faces_tot(), Front_VF::num_face(), o_fvf, ref_cast, TRUSTTab< _TYPE_ >::resize(), s_dist, Zone_VF::xv(), Zone_dis_base::zone(), and Frontiere_dis_base::zone_dis().
Referenced by Op_Diff_PolyMAC_P0_Elem::init_s_dist().
init_op()
void Echange_contact_PolyMAC_P0::init_op () const
Definition at line 49 of file Echange_contact_PolyMAC_P0.cpp.
{
  if (o_diff.non_nul()) return;
  Champ_front_calc ch;
  ch.creer(nom_autre_pb_, nom_bord_, nom_champ_);
  fvf = ref_cast(Front_VF, frontiere_dis()), o_fvf = ref_cast(Front_VF, ch.front_dis()); //frontieres
  const Equation_base& eqn = zone_Cl_dis().equation(), &o_eqn = ch.equation(); //equations
  i_fvf = eqn.zone_dis()->rang_frontiere(fvf.le_nom()), i_o_fvf = o_eqn.zone_dis()->rang_frontiere(nom_bord_);
  int i_op = -1, o_i_op = -1, i; //indice de l'operateur de diffusion dans l'autre equation
  for (i = 0; i < eqn.nombre_d_operateurs(); i++)
    if (sub_type(Op_Diff_PolyMAC_P0_Elem, eqn.operateur(i).l_op_base())) i_op = i;
  if (i_op < 0) Process::exit(le_nom() + " : no diffusion operator found in " + eqn.probleme().le_nom() + " !");
  for (i = 0; i < o_eqn.nombre_d_operateurs(); i++)
    if (sub_type(Op_Diff_PolyMAC_P0_Elem, o_eqn.operateur(i).l_op_base())) o_i_op = i;
  if (o_i_op < 0) Process::exit(le_nom() + " : no diffusion operator found in " + o_eqn.probleme().le_nom() + " !");
  diff = ref_cast(Op_Diff_PolyMAC_P0_Elem, eqn.operateur(i_op).l_op_base());
  o_diff = ref_cast(Op_Diff_PolyMAC_P0_Elem, o_eqn.operateur(o_i_op).l_op_base());
}
References Champ_front_calc::creer(), diff, Champ_front_calc::equation(), MorEqn::equation(), Process::exit(), Champ_front_calc::front_dis(), Cond_lim_base::frontiere_dis(), fvf, i_fvf, i_o_fvf, Operateur::l_op_base(), Objet_U::le_nom(), Probleme_base::le_nom(), Nom::le_nom(), O_U_Ptr::le_nom(), nom_autre_pb_, nom_bord_, nom_champ_, Equation_base::nombre_d_operateurs(), O_U_Ptr::non_nul(), o_diff, o_fvf, Equation_base::operateur(), Equation_base::probleme(), ref_cast, sub_type, Cond_lim_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Op_Diff_PolyMAC_P0_Elem::init_s_dist(), and Op_Diff_PolyMAC_P0_Elem::init_som_ext().
mettre_a_jour()
void Echange_contact_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Cond_lim_base.
Definition at line 45 of file Echange_contact_PolyMAC_P0.h.
{ }; //non utilise
printOn()
Sortie & Echange_contact_PolyMAC_P0::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 33 of file Echange_contact_PolyMAC_P0.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Echange_contact_PolyMAC_P0::readOn (Entree & s) override protected virtual
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 38 of file Echange_contact_PolyMAC_P0.cpp.
{
  Nom nom_bord;
  Motcle nom_champ;
  s >> nom_autre_pb_ >> nom_bord_ >> nom_champ_ >> invh_paroi;
  invh_paroi = invh_paroi > 1e8 ? 0 : 1. / invh_paroi;
  T_ext().typer("Ch_front_var_instationnaire_dep");
  T_ext()->fixer_nb_comp(1);
  return s;
}
References invh_paroi, nom_autre_pb_, nom_bord_, nom_champ_, Echange_impose_base::T_ext(), and Deriv_::typer().
self_cast() [1/2]
const Echange_contact_PolyMAC_P0 & Echange_contact_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
self_cast() [2/2]
Echange_contact_PolyMAC_P0 & Echange_contact_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
taille_memoire()
unsigned Echange_contact_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 30 of file Echange_contact_PolyMAC_P0.cpp.
verifie_ch_init_nb_comp()
void Echange_contact_PolyMAC_P0::verifie_ch_init_nb_comp () const inline override virtual
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
Reimplemented from Cond_lim_base.
Definition at line 46 of file Echange_contact_PolyMAC_P0.h.
{ }; //pas de contrainte sur les composantes de chaque cote
Member Data Documentation
diff
Ref_Op_Diff_PolyMAC_P0_Elem Echange_contact_PolyMAC_P0::diff mutable
Definition at line 50 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op().
f_dist
IntTab Echange_contact_PolyMAC_P0::f_dist mutable
Definition at line 54 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_fs_dist(), and Op_Diff_PolyMAC_P0_Elem::init_som_ext().
fs_dist_init_
int Echange_contact_PolyMAC_P0::fs_dist_init_ = 0 mutable
Definition at line 56 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_fs_dist().
fvf
Ref_Front_VF Echange_contact_PolyMAC_P0::fvf mutable
Definition at line 48 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_fs_dist(), and init_op().
i_fvf
int Echange_contact_PolyMAC_P0::i_fvf mutable
Definition at line 49 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op().
i_o_fvf
int Echange_contact_PolyMAC_P0::i_o_fvf
Definition at line 49 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op().
info_obj
const Type_info Echange_contact_PolyMAC_P0::info_obj static
Definition at line 42 of file Echange_contact_PolyMAC_P0.h.
invh_paroi
double Echange_contact_PolyMAC_P0::invh_paroi
Definition at line 58 of file Echange_contact_PolyMAC_P0.h.
Referenced by readOn().
nom_autre_pb_
Nom Echange_contact_PolyMAC_P0::nom_autre_pb_ protected
Definition at line 61 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op(), and readOn().
nom_bord_
Nom Echange_contact_PolyMAC_P0::nom_bord_ protected
Definition at line 61 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op(), and readOn().
nom_champ_
Nom Echange_contact_PolyMAC_P0::nom_champ_ protected
Definition at line 61 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op(), and readOn().
o_diff
Ref_Op_Diff_PolyMAC_P0_Elem Echange_contact_PolyMAC_P0::o_diff
Definition at line 50 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_op(), Op_Diff_PolyMAC_P0_Elem::init_s_dist(), and Op_Diff_PolyMAC_P0_Elem::init_som_ext().
o_fvf
Ref_Front_VF Echange_contact_PolyMAC_P0::o_fvf
Definition at line 48 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_fs_dist(), and init_op().
s_dist
std::map<int, int> Echange_contact_PolyMAC_P0::s_dist mutable
Definition at line 55 of file Echange_contact_PolyMAC_P0.h.
Referenced by init_fs_dist(), and Op_Diff_PolyMAC_P0_Elem::init_s_dist().
The documentation for this class was generated from the following files:
src/PolyMAC/Cond_Lim/Echange_contact_PolyMAC_P0.h
src/PolyMAC/Cond_Lim/Echange_contact_PolyMAC_P0.cpp