TRUST: Eval_Diff_VDF Class Reference
Eval_Diff_VDF Class Reference
#include <Eval_Diff_VDF.h>
Public Member Functions
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Detailed Description
Definition at line 29 of file Eval_Diff_VDF.h.
Constructor & Destructor Documentation
virtual Eval_Diff_VDF::~Eval_Diff_VDF () [inline, virtual]
Definition at line 32 of file Eval_Diff_VDF.h.
{}
Member Function Documentation
virtual void Eval_Diff_VDF::associer (const Champ_base &) [pure virtual]
Implemented in Eval_Diff_VDF_const, Eval_Diff_VDF_Multi_inco_const, Eval_Diff_VDF_Multi_inco_var, Eval_Diff_VDF_var, and Eval_Diff_VDF_var_aniso.
Referenced by Op_Dift_VDF_Face_base::associer_diffusivite(), Op_Diff_VDF_Face_base::associer_diffusivite(), and Op_Diff_VDF_Elem_base::associer_diffusivite().
virtual const Champ_base& Eval_Diff_VDF::get_diffusivite () const [pure virtual]
Implemented in Eval_Diff_VDF_const, Eval_Diff_VDF_Multi_inco_const, Eval_Diff_VDF_Multi_inco_var, Eval_Diff_VDF_var, and Eval_Diff_VDF_var_aniso.
Referenced by Op_Dift_VDF_base::ajouter(), Op_Diff_VDF_base::ajouter(), Op_Dift_VDF_base::contribuer_a_avec(), Op_Diff_VDF_base::contribuer_a_avec(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_base::contribuer_au_second_membre(), Op_Dift_VDF_Face_base::diffusivite(), Op_Diff_VDF_Face_base::diffusivite(), and Op_Diff_VDF_Elem_base::diffusivite().
virtual double Eval_Diff_VDF::get_equivalent_distance (int boundary_index, int local_face) const [inline, virtual]
Reimplemented in Eval_Dift_VDF_const, Eval_Dift_VDF_Multi_inco_const, Eval_Dift_VDF_Multi_inco_var, and Eval_Dift_VDF_var.
Definition at line 40 of file Eval_Diff_VDF.h.
{ return 0; }
int Eval_Diff_VDF::get_ind_Fluctu_Term () const [inline]
Reimplemented in Eval_Dift_VDF_const_Elem, and Eval_Dift_VDF_var_Elem.
Definition at line 39 of file Eval_Diff_VDF.h.
{ return 0; }
virtual void Eval_Diff_VDF::mettre_a_jour () [inline, virtual]
Reimplemented in Eval_Diff_VDF_const, Eval_Diff_VDF_Multi_inco_const, Eval_Diff_VDF_Multi_inco_var, Eval_Diff_VDF_var, Eval_Diff_VDF_var_aniso, Eval_Dift_VDF_const, Eval_Dift_VDF_const_Face, Eval_Dift_VDF_Multi_inco_const, Eval_Dift_VDF_Multi_inco_var, Eval_Dift_VDF_var, and Eval_Dift_VDF_var_Face.
Definition at line 35 of file Eval_Diff_VDF.h.
Referenced by Op_Diff_VDF_Face_base::mettre_a_jour().
{ }
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_Diff_VDF.h