TRUST: Eval_Source_C_PolyMAC_Elem Class Reference
Eval_Source_C_PolyMAC_Elem Class Reference
#include <Eval_Source_C_PolyMAC_Elem.h>
Public Member Functions
Eval_Source_C_PolyMAC_Elem ()
void associer_champs (const Champ_Don &)
void mettre_a_jour () override
double calculer_terme_source (int) const override
void calculer_terme_source (int, DoubleVect &) const override
Public Member Functions inherited from Evaluateur_Source_PolyMAC_Elem
Evaluateur_Source_PolyMAC_Elem ()
Evaluateur_Source_PolyMAC_Elem (const Evaluateur_Source_PolyMAC_Elem &)
void completer () override
Public Member Functions inherited from Evaluateur_Source_PolyMAC
Evaluateur_Source_PolyMAC ()
virtual ~Evaluateur_Source_PolyMAC ()
Evaluateur_Source_PolyMAC (const Evaluateur_Source_PolyMAC &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual double calculer_terme_source (int) const =0
virtual void calculer_terme_source (int, DoubleVect &) const =0
Protected Attributes
Ref_Champ_Don la_source_constituant
DoubleTab source_constituant
Protected Attributes inherited from Evaluateur_Source_PolyMAC_Elem
DoubleVect volumes
DoubleVect porosite_vol
porosites volumiques
Protected Attributes inherited from Evaluateur_Source_PolyMAC
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Detailed Description
Definition at line 32 of file Eval_Source_C_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Eval_Source_C_PolyMAC_Elem()
Eval_Source_C_PolyMAC_Elem::Eval_Source_C_PolyMAC_Elem () inline
Definition at line 54 of file Eval_Source_C_PolyMAC_Elem.h.
{}
Member Function Documentation
associer_champs()
void Eval_Source_C_PolyMAC_Elem::associer_champs (const Champ_Don & Q)
Definition at line 19 of file Eval_Source_C_PolyMAC_Elem.cpp.
{
  la_source_constituant = Q;
  source_constituant.ref(Q.valeurs());
}
References la_source_constituant, TRUSTTab< _TYPE_ >::ref(), source_constituant, and Champ_Don::valeurs().
Referenced by Terme_Source_Constituant_PolyMAC_Elem::associer_pb().
calculer_terme_source() [1/2]
double Eval_Source_C_PolyMAC_Elem::calculer_terme_source (int num_elem) const inline override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 56 of file Eval_Source_C_PolyMAC_Elem.h.
{
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    return source_constituant(0,0)*volumes(num_elem)*porosite_vol(num_elem);
  else if (source_constituant.nb_dim()==2)
    return source_constituant(num_elem,0)*volumes(num_elem)*porosite_vol(num_elem);
  else
    return source_constituant(num_elem)*volumes(num_elem)*porosite_vol(num_elem);
}
References la_source_constituant, TRUSTTab< _TYPE_ >::nb_dim(), Evaluateur_Source_PolyMAC_Elem::porosite_vol, source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_PolyMAC_Elem::volumes.
calculer_terme_source() [2/2]
void Eval_Source_C_PolyMAC_Elem::calculer_terme_source (int num_elem, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 66 of file Eval_Source_C_PolyMAC_Elem.h.
{
  int size=source.size();
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    for (int i=0; i<size; i++)
      source(i) = source_constituant(0,i)*volumes(num_elem)*porosite_vol(num_elem);
  else
    for (int i=0; i<size; i++)
      source(i) = source_constituant(num_elem,i)*volumes(num_elem)*porosite_vol(num_elem);
}
References la_source_constituant, Evaluateur_Source_PolyMAC_Elem::porosite_vol, TRUSTVect< _TYPE_ >::size(), source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_PolyMAC_Elem::volumes.
mettre_a_jour()
void Eval_Source_C_PolyMAC_Elem::mettre_a_jour () override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 25 of file Eval_Source_C_PolyMAC_Elem.cpp.
{
}
Member Data Documentation
la_source_constituant
Ref_Champ_Don Eval_Source_C_PolyMAC_Elem::la_source_constituant protected
Definition at line 45 of file Eval_Source_C_PolyMAC_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
source_constituant
DoubleTab Eval_Source_C_PolyMAC_Elem::source_constituant protected
Definition at line 46 of file Eval_Source_C_PolyMAC_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Eval_Source_C_PolyMAC_Elem.h
src/PolyMAC/Sources/Eval_Source_C_PolyMAC_Elem.cpp