TRUST: Terme_Source_Constituant_CoviMAC_Elem Class Reference
Terme_Source_Constituant_CoviMAC_Elem Class Reference
class Terme_Source_Constituant_CoviMAC_Elem
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique uniforme sur une zone<br>.SECTION
voir aussi Terme_Source_Constituant, Terme_Source_CoviMAC_base
#include <Terme_Source_Constituant_CoviMAC_Elem.h>
Public Member Functions
~Terme_Source_Constituant_CoviMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Source_Constituant_CoviMAC_Elem ()
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void associer_pb (const Probleme_base &)
void mettre_a_jour (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Constituant_CoviMAC_Elem & self_cast (Objet_U &)
static const
Terme_Source_Constituant_CoviMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
class Terme_Source_Constituant_CoviMAC_Elem
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique uniforme sur une zone<br>.SECTION
voir aussi Terme_Source_Constituant, Terme_Source_CoviMAC_base
Definition at line 43 of file Terme_Source_Constituant_CoviMAC_Elem.h.
Constructor & Destructor Documentation
Terme_Source_Constituant_CoviMAC_Elem::~Terme_Source_Constituant_CoviMAC_Elem ()
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
Terme_Source_Constituant_CoviMAC_Elem::Terme_Source_Constituant_CoviMAC_Elem () [inline]
Definition at line 64 of file Terme_Source_Constituant_CoviMAC_Elem.h.
  : Terme_Source_Constituant(),Terme_Source_CoviMAC_base(It_Sou_CoviMAC_Elem(Eval_Source_C_CoviMAC_Elem)())
{
}
Member Function Documentation
void Terme_Source_Constituant_CoviMAC_Elem::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 65 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
References Eval_Source_C_CoviMAC_Elem::associer_champs(), Equation_base::discretisation(), Probleme_base::equation(), Iterateur_Source_CoviMAC::evaluateur(), Terme_Source_CoviMAC_base::iter, Terme_Source_Constituant::la_source_constituant, O_U_Ptr::le_nom(), Discretisation_base::nommer_completer_champ_physique(), and Equation_base::zone_dis().
{
  const Equation_base& eqn = pb.equation(0);
  eqn.discretisation().nommer_completer_champ_physique(eqn.zone_dis(),la_source_constituant.le_nom(),"",la_source_constituant,pb);
  Eval_Source_C_CoviMAC_Elem& eval_puis = (Eval_Source_C_CoviMAC_Elem&) iter.evaluateur();
  eval_puis.associer_champs(la_source_constituant);
}
void Terme_Source_Constituant_CoviMAC_Elem::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Implements Source_base.
Definition at line 52 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
References Evaluateur_Source_CoviMAC::associer_zones(), Iterateur_Source_CoviMAC::evaluateur(), Terme_Source_CoviMAC_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_CoviMAC& zvdf = ref_cast(Zone_CoviMAC,zone_dis.valeur());
  const Zone_Cl_CoviMAC& zclvdf = ref_cast(Zone_Cl_CoviMAC,zone_cl_dis.valeur());
  iter->associer_zones(zvdf, zclvdf);
  Eval_Source_C_CoviMAC_Elem& eval_puis = (Eval_Source_C_CoviMAC_Elem&) iter.evaluateur();
  eval_puis.associer_zones(zvdf, zclvdf );
}
Objet_U * Terme_Source_Constituant_CoviMAC_Elem::cree_instance () [static]
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
int Terme_Source_Constituant_CoviMAC_Elem::duplique () const [virtual]
Implements Terme_Source_CoviMAC_base.
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
const Type_info * Terme_Source_Constituant_CoviMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
const Type_info * Terme_Source_Constituant_CoviMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
void Terme_Source_Constituant_CoviMAC_Elem::mettre_a_jour (double temps) [inline]
Reimplemented from Terme_Source_Constituant.
Definition at line 53 of file Terme_Source_Constituant_CoviMAC_Elem.h.
References Terme_Source_Constituant::mettre_a_jour().
  {
    Terme_Source_Constituant::mettre_a_jour(temps);
  }
Sortie & Terme_Source_Constituant_CoviMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 35 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_Constituant_CoviMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 43 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
References Terme_Source_Constituant::lire_donnees(), Source_base::set_description(), and Source_base::set_fichier().
{
  Terme_Source_Constituant::lire_donnees(s);
  set_fichier("Source_Constituant");
  set_description("Injection rate = Integral(source_C*dv) [mol/s]");
  return s;
}
Terme_Source_Constituant_CoviMAC_Elem & Terme_Source_Constituant_CoviMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
const Terme_Source_Constituant_CoviMAC_Elem & Terme_Source_Constituant_CoviMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
unsigned Terme_Source_Constituant_CoviMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Terme_Source_Constituant_CoviMAC_Elem.cpp.
Member Data Documentation
const Type_info Terme_Source_Constituant_CoviMAC_Elem::info_obj [static]
Reimplemented from Terme_Source_CoviMAC_base.
Definition at line 46 of file Terme_Source_Constituant_CoviMAC_Elem.h.
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Terme_Source_Constituant_CoviMAC_Elem.h
src/CoviMAC/Sources/Terme_Source_Constituant_CoviMAC_Elem.cpp