TRUST: Rotationnel_Champ_Q1NC Class Reference
Rotationnel_Champ_Q1NC Class Reference
#include <Rotationnel_Champ_Q1NC.h>
Public Member Functions
Rotationnel_Champ_Q1NC ()
~Rotationnel_Champ_Q1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_Q1NC & mon_champ () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Q1NC &)
void me_calculer (double)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Rotationnel_Champ_Q1NC & self_cast (Objet_U &)
static const
Rotationnel_Champ_Q1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_Q1NC mon_champ_
Detailed Description
Definition at line 32 of file Rotationnel_Champ_Q1NC.h.
Constructor & Destructor Documentation
Rotationnel_Champ_Q1NC::Rotationnel_Champ_Q1NC ()
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
Rotationnel_Champ_Q1NC::~Rotationnel_Champ_Q1NC ()
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
Member Function Documentation
void Rotationnel_Champ_Q1NC::associer_champ (const Champ_Q1NC & un_champ)
Definition at line 45 of file Rotationnel_Champ_Q1NC.cpp.
References mon_champ_.
{
  mon_champ_= un_champ;
}
Objet_U * Rotationnel_Champ_Q1NC::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
int Rotationnel_Champ_Q1NC::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
const Type_info * Rotationnel_Champ_Q1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
const Type_info * Rotationnel_Champ_Q1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
void Rotationnel_Champ_Q1NC::me_calculer (double tps) [virtual]
Implements Champ_Rotationnel.
Definition at line 50 of file Rotationnel_Champ_Q1NC.cpp.
References mon_champ_, and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
{
// mon_champ_->calculer_rotationnel_ordre2_centre_element(valeurs());
  mon_champ_->cal_rot_ordre1(valeurs());
}
void Rotationnel_Champ_Q1NC::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 54 of file Rotationnel_Champ_Q1NC.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
}
const Champ_Q1NC & Rotationnel_Champ_Q1NC::mon_champ () const [inline]
Definition at line 49 of file Rotationnel_Champ_Q1NC.h.
{
  return mon_champ_.valeur();
}
Sortie & Rotationnel_Champ_Q1NC::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 32 of file Rotationnel_Champ_Q1NC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Rotationnel_Champ_Q1NC::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 40 of file Rotationnel_Champ_Q1NC.cpp.
{
  return s ;
}
const Rotationnel_Champ_Q1NC & Rotationnel_Champ_Q1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
Rotationnel_Champ_Q1NC & Rotationnel_Champ_Q1NC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
unsigned Rotationnel_Champ_Q1NC::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 26 of file Rotationnel_Champ_Q1NC.cpp.
Member Data Documentation
const Type_info Rotationnel_Champ_Q1NC::info_obj [static]
Reimplemented from Champ_Fonc_P0_VEF.
Definition at line 35 of file Rotationnel_Champ_Q1NC.h.
Ref_Champ_Q1NC Rotationnel_Champ_Q1NC::mon_champ_ [protected]
Definition at line 46 of file Rotationnel_Champ_Q1NC.h.
Referenced by associer_champ(), and me_calculer().
The documentation for this class was generated from the following files:
src/VEF/Champs/Rotationnel_Champ_Q1NC.h
src/VEF/Champs/Rotationnel_Champ_Q1NC.cpp