TRUST: Fluide_base Class Reference
Fluide_base Class Reference
classe Fluide_base
Cette classe represente un d'un fluide incompressible ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
#include <Fluide_base.h>
Public Member Functions
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Static Protected Member Functions
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Protected Attributes
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Additional Inherited Members
Public Attributes inherited from Milieu_base
int id_composite = -1
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Detailed Description
classe Fluide_base
Cette classe represente un d'un fluide incompressible ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
Definition at line 39 of file Fluide_base.h.
Constructor & Destructor Documentation
~Fluide_base()
Fluide_base::~Fluide_base ()
Definition at line 29 of file Fluide_base.cpp.
Fluide_base()
Fluide_base::Fluide_base ()
Definition at line 35 of file Fluide_base.cpp.
{ }
Member Function Documentation
beta_c() [1/2]
Champ_Don & Fluide_base::beta_c () inline
Renvoie la dilatabilite du constituant, beta_co.
Returns
Champ_Don&
Signification: la dilatabilite du constituant, beta_co
Contraintes:
Definition at line 223 of file Fluide_base.h.
{
  return beta_co;
}
References beta_co.
beta_c() [2/2]
const Champ_Don & Fluide_base::beta_c () const inline
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Returns
Champ_Don&
Signification: la dilatabilite du constituant, beta_co
Contraintes: reference constante
Definition at line 203 of file Fluide_base.h.
{
  return beta_co;
}
References beta_co.
Referenced by Terme_Boussinesq_base::associer_pb().
calculer_e_int()
void Fluide_base::calculer_e_int (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
Definition at line 490 of file Fluide_base.cpp.
{
  const Fluide_base& fl = ref_cast(Fluide_base, obj);
  const Champ_base& ch_T = fl.equation("temperature").inconnue().valeur(), &ch_Cp = fl.capacite_calorifique();
  const DoubleTab& T = ch_T.valeurs(), &Cp = ch_Cp.valeurs();
  int i, zero = 0, Ni = T.dimension_tot(0), Nb = bval.dimension_tot(0), n, N = fl.id_composite >= 0 ? 1 : Cp.dimension(1),
         n0 = std::max(fl.id_composite, zero), cCp = Cp.dimension_tot(0) == 1;
  for (i = 0; i < Ni; i++)
    for (n = 0; n < N; n++) val(i, n) = fl.h0_ + Cp(!cCp * i, n) * (T(i, n0 + n) - fl.T0_);
  DoubleTab bT = ch_T.valeur_aux_bords(), bCp;
  if (ch_Cp.a_une_zone_dis_base()) bCp = ch_Cp.valeur_aux_bords();
  else bCp.resize(bval.dimension_tot(0), N), ch_Cp.valeur_aux(ref_cast(Zone_VF, ch_T.zone_dis_base()).xv_bord() , bCp);
  for (i = 0; i < Nb; i++)
    for (n = 0; n < N; n++) bval(i, n) = fl.h0_ + bCp(i, n) * (bT(i, n0 + n) - fl.T0_);
  DoubleTab& der_T = deriv[ch_T.le_nom().getString()];
  for (der_T.resize(Ni, N), i = 0; i < Ni; i++)
    for (n = 0; n < N; n++) der_T(i, n) = Cp(!cCp * i, n);
}
References Milieu_base::capacite_calorifique(), Milieu_base::Cp, Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Milieu_base::equation(), Nom::getString(), h0_, Milieu_base::id_composite, Equation_base::inconnue(), Field_base::le_nom(), ref_cast, TRUSTTab< _TYPE_ >::resize(), T0_, Deriv_Champ_Inc_base::valeur(), Champ_base::valeur_aux_bords(), Champ_Don::valeurs(), Champ_Proto::valeurs(), zero(), and Champ_base::zone_dis_base().
Referenced by creer_e_int().
calculer_nu()
void Fluide_base::calculer_nu () protected virtual
Reimplemented in Fluide_Dilatable_base.
Definition at line 311 of file Fluide_base.cpp.
{
  const DoubleTab& tabmu = mu.valeurs();
  const DoubleTab& tabrho = rho.valeurs();
  DoubleTab& tabnu = nu.valeurs();
  int cRho = sub_type(Champ_Uniforme, rho.valeur()), cMu = sub_type(Champ_Uniforme, mu.valeur()),
      i, j, n, Nl = tabnu.dimension_tot(0), N = tabnu.line_size();
  /* valeurs : mu / rho */
  for (i = j = 0; i < Nl; i++)
    for (n = 0; n < N; n++, j++) tabnu.addr()[j] = tabmu.addr()[cMu ? n : j] / tabrho.addr()[cRho ? n : j];
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::line_size(), mu, nu, Milieu_base::rho, sub_type, Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), Champ::valeurs(), and Champ_Don::valeurs().
Referenced by initialiser(), and mettre_a_jour().
cree_instance()
Objet_U * Fluide_base::cree_instance () static
Definition at line 29 of file Fluide_base.cpp.
creer_champs_non_lus()
void Fluide_base::creer_champs_non_lus () override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Ostwald.
Definition at line 108 of file Fluide_base.cpp.
{
  Milieu_base::creer_champs_non_lus();
  creer_nu();
}
References Milieu_base::creer_champs_non_lus(), and creer_nu().
creer_e_int()
void Fluide_base::creer_e_int () const protected
Definition at line 478 of file Fluide_base.cpp.
{
  Champ_Inc e_int_inc;
  const Equation_base& eq = equation("temperature");
  eq.discretisation().discretiser_champ("champ_elem", eq.zone_dis(), "energie_interne", "J/kg", 1,
                                        eq.inconnue()->nb_valeurs_temporelles(), eq.inconnue()->temps(), e_int_inc);
  e_int_inc.associer_eqn(eq), e_int_inc->init_champ_calcule(*this, calculer_e_int);
  e_int = e_int_inc;
  e_int.mettre_a_jour(eq.inconnue()->temps());
  e_int_auto_ = 1;
}
References Champ_Inc::associer_eqn(), calculer_e_int(), Equation_base::discretisation(), Discretisation_base::discretiser_champ(), e_int, e_int_auto_, Milieu_base::equation(), Equation_base::inconnue(), Champ::mettre_a_jour(), Champ_Inc::nb_valeurs_temporelles(), Champ_Inc::temps(), and Equation_base::zone_dis().
Referenced by energie_interne(), and enthalpie().
creer_nu()
void Fluide_base::creer_nu () protected
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
Definition at line 301 of file Fluide_base.cpp.
{
  assert(mu.non_nul());
  assert(rho.non_nul());
  nu=mu;
  if (sub_type(Champ_Uniforme, mu.valeur()) && !sub_type(Champ_Uniforme, rho.valeur()))
    nu.valeurs().resize(rho.valeurs().dimension_tot(0), rho.valeurs().line_size());
  nu->nommer("nu");
}
References TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::line_size(), mu, Objet_U::nommer(), O_U_Ptr::non_nul(), nu, TRUSTTab< _TYPE_ >::resize(), Milieu_base::rho, sub_type, Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), Champ::valeurs(), and Champ_Don::valeurs().
Referenced by creer_champs_non_lus().
discretiser()
void Fluide_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Ostwald, Fluide_reel_base, and Milieu_composite.
Definition at line 114 of file Fluide_base.cpp.
{
  const Zone_dis_base& zone_dis=pb.equation(0).zone_dis();
// mu rho nu  revoir
  double temps=pb.schema_temps().temps_courant();
  if (mu.non_nul())
    if (sub_type(Champ_Fonc_MED,mu.valeur()))
      {
        Cerr<<" on convertit le champ_fonc_med en champ_don"<<finl;
        Champ_Don mu_prov;
        dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,mu_prov);
        mu_prov.affecter_(mu.valeur());
        mu.detach();
        nu.detach();
        dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,mu);
        mu.valeur().valeurs()=mu_prov.valeur().valeurs();
      }
  if (!mu.non_nul())
    {
      dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,mu);
      dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,nu);
    }
  if (mu.non_nul())
    {
      dis.nommer_completer_champ_physique(zone_dis,"viscosite_dynamique","kg/m/s",mu.valeur(),pb);
      champs_compris_.ajoute_champ(mu.valeur());
    }
  if (sub_type(Champ_Fonc_Tabule,mu.valeur()))
    {
      dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,nu);
    }
  if (!nu.non_nul())
    dis.discretiser_champ("champ_elem",zone_dis,"neant","neant",1,temps,nu);
  if (nu.non_nul())
    {
      dis.nommer_completer_champ_physique(zone_dis,"viscosite_cinematique","m2/s",nu.valeur(),pb);
      champs_compris_.ajoute_champ(nu.valeur());
    }
  if (beta_co.non_nul())
    {
      dis.nommer_completer_champ_physique(zone_dis,"dilatabilite_solutale",".",beta_co.valeur(),pb);
      champs_compris_.ajoute_champ(beta_co.valeur());
    }
  Milieu_base::discretiser(pb,dis);
}
References Champ_Don::affecter_(), Champs_compris::ajoute_champ(), beta_co, Cerr, Milieu_base::champs_compris_, Deriv_::detach(), Milieu_base::discretiser(), Discretisation_base::discretiser_champ(), Probleme_base::equation(), finl, mu, Discretisation_base::nommer_completer_champ_physique(), O_U_Ptr::non_nul(), nu, Probleme_base::schema_temps(), sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_Don_base::valeur(), Champ_Don_base::valeurs(), and Equation_base::zone_dis().
Referenced by Fluide_Dilatable_base::discretiser(), and Fluide_Ostwald::discretiser().
duplique()
int Fluide_base::duplique () const override virtual
Implements Objet_U.
Reimplemented in Fluide_Incompressible, Fluide_Ostwald, Fluide_sodium_gaz, Fluide_sodium_liquide, Milieu_composite, and StiffenedGas.
Definition at line 29 of file Fluide_base.cpp.
energie_interne() [1/2]
Champ_base & Fluide_base::energie_interne () virtual
Definition at line 517 of file Fluide_base.cpp.
{
  if (!e_int.non_nul()) creer_e_int();
  return e_int;
}
References creer_e_int(), e_int, and O_U_Ptr::non_nul().
energie_interne() [2/2]
const Champ_base & Fluide_base::energie_interne () const virtual
Definition at line 511 of file Fluide_base.cpp.
{
  if (!e_int.non_nul()) creer_e_int();
  return e_int;
}
References creer_e_int(), e_int, and O_U_Ptr::non_nul().
Referenced by Energie_Multiphase::calculer_alpha_rho_e().
enthalpie() [1/2]
Champ_base & Fluide_base::enthalpie () virtual
Definition at line 530 of file Fluide_base.cpp.
{
  if (!h.non_nul() && !e_int.non_nul()) creer_e_int();
  return h.non_nul() ? h : e_int;
}
References creer_e_int(), e_int, h, and O_U_Ptr::non_nul().
enthalpie() [2/2]
const Champ_base & Fluide_base::enthalpie () const virtual
Definition at line 524 of file Fluide_base.cpp.
{
  if (!h.non_nul() && !e_int.non_nul()) creer_e_int();
  return h.non_nul() ? h : e_int;
}
References creer_e_int(), e_int, h, and O_U_Ptr::non_nul().
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs(), and Energie_Multiphase::calculer_alpha_rho_h().
fixer_type_rayo()
void Fluide_base::fixer_type_rayo ()
Definition at line 458 of file Fluide_base.cpp.
{
  if ((coeff_absorption_.non_nul()) && (indice_refraction_.non_nul()))
    indic_rayo_ = SEMITRANSP;
  else
    indic_rayo_ = TRANSP;
}
References coeff_absorption_, Milieu_base::indic_rayo_, indice_refraction_, O_U_Ptr::non_nul(), Milieu_base::SEMITRANSP, and Milieu_base::TRANSP.
get_info()
const Type_info * Fluide_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Milieu_base.
Reimplemented in Fluide_Incompressible, Fluide_Ostwald, Fluide_reel_base, Fluide_sodium_gaz, Fluide_sodium_liquide, Milieu_composite, and StiffenedGas.
Definition at line 29 of file Fluide_base.cpp.
indice() [1/2]
Champ_Don & Fluide_base::indice () inline
Renvoie l'indice de refraction du fluide.
Returns
Champ_Don&
Signification: l'indice de refraction du fluide
Contraintes:
Definition at line 281 of file Fluide_base.h.
{
  return indice_refraction_;
}
References indice_refraction_.
indice() [2/2]
const Champ_Don & Fluide_base::indice () const inline
Renvoie l'indice de refraction du fluide.
Returns
Champ_Don&
Signification: l'indice de refraction du fluide
Contraintes: reference constante
Definition at line 300 of file Fluide_base.h.
{
  return indice_refraction_;
}
References indice_refraction_.
info()
const Type_info * Fluide_base::info () static
Definition at line 29 of file Fluide_base.cpp.
initialiser()
int Fluide_base::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Milieu_base.
Reimplemented in Fluide_Ostwald, Fluide_reel_base, and Milieu_composite.
Definition at line 406 of file Fluide_base.cpp.
{
  Cerr << "Fluide_base::initialiser()" << finl;
  Milieu_base::initialiser(temps);
  mu.initialiser(temps);
  if (beta_co.non_nul())
    beta_co.initialiser(temps);
  calculer_nu();
  nu->valeurs().echange_espace_virtuel();
  nu->changer_temps(temps);
// Initialisation des proprietes radiatives du fluide incompressible
// (Pour un fluide incompressible semi transparent).
  if (coeff_absorption_.non_nul() && indice_refraction_.non_nul())
    {
      Cerr<<"Semi transparent fluid properties initialization."<<finl;
      coeff_absorption_.initialiser(temps);
      indice_refraction_.initialiser(temps);
// Initialisation de longueur_rayo
      longueur_rayo_.initialiser(temps);
      if (sub_type(Champ_Uniforme,kappa().valeur()))
        {
          longueur_rayo()->valeurs()(0,0)=1/(3*kappa()(0,0));
        }
      else
        {
          DoubleTab& l_rayo = longueur_rayo_.valeurs();
          const DoubleTab& K = kappa().valeurs();
          for (int i=0; i<kappa().nb_valeurs_nodales(); i++)
            l_rayo[i] = 1/(3*K[i]);
        }
    }
  return 1;
}
References beta_co, calculer_nu(), Cerr, coeff_absorption_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, indice_refraction_, Champ_Don::initialiser(), Milieu_base::initialiser(), kappa(), longueur_rayo(), longueur_rayo_, mu, Champ_Don::nb_valeurs_nodales(), O_U_Ptr::non_nul(), nu, sub_type, valeur(), and Champ_Don::valeurs().
Referenced by Fluide_Ostwald::initialiser().
initTimeStep()
bool Fluide_base::initTimeStep (double dt) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_reel_base, and Milieu_composite.
Definition at line 325 of file Fluide_base.cpp.
{
  if (!equation_.size() || !e_int_auto_) return true; //pas d'equation associee ou pas de e_int a gerer
  const Schema_Temps_base& sch = equation_.begin()->second->schema_temps(); //on recupere le schema en temps par la 1ere equation
  Champ_Inc_base& ch = ref_cast(Champ_Inc_base, e_int.valeur());
  for (int i = 1; i <= sch.nb_valeurs_futures(); i++)
    ch.changer_temps_futur(sch.temps_futur(i), i), ch.futur(i) = ch.valeurs();
  return true;
}
References Champ_Inc_base::changer_temps_futur(), e_int, e_int_auto_, Milieu_base::equation_, Champ_Inc_base::futur(), Schema_Temps_base::nb_valeurs_futures(), ref_cast, Schema_Temps_base::temps_futur(), Deriv_Champ_base::valeur(), and Champ_Inc_base::valeurs().
is_rayo_semi_transp()
int Fluide_base::is_rayo_semi_transp () const override virtual
Reimplemented from Milieu_base.
Definition at line 444 of file Fluide_base.cpp.
{
  return int(indic_rayo_ == SEMITRANSP);
}
References Milieu_base::indic_rayo_, and Milieu_base::SEMITRANSP.
is_rayo_transp()
int Fluide_base::is_rayo_transp () const override virtual
Reimplemented from Milieu_base.
Definition at line 449 of file Fluide_base.cpp.
{
  return int(indic_rayo_ == TRANSP);
}
References Milieu_base::indic_rayo_, and Milieu_base::TRANSP.
kappa() [1/2]
Champ_Don & Fluide_base::kappa () inline
Renvoie le coefficient d'absorbtion du fluide.
Returns
Champ_Don&
Signification: le coefficient d'absorbtion du fluide
Contraintes:
Definition at line 243 of file Fluide_base.h.
{
  return coeff_absorption_;
}
References coeff_absorption_.
Referenced by initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), and mettre_a_jour().
kappa() [2/2]
const Champ_Don & Fluide_base::kappa () const inline
Renvoie le coefficient d'absorbtion du fluide.
Returns
Champ_Don&
Signification: le coefficient d'absorbtion du fluide
Contraintes: reference constante
Definition at line 262 of file Fluide_base.h.
{
  return coeff_absorption_;
}
References coeff_absorption_.
longeur_rayo()
const Champ_Don & Fluide_base::longeur_rayo () const inline
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
Returns
Champ_Don&
Signification: la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
Contraintes: reference constante
Definition at line 343 of file Fluide_base.h.
{
  return longueur_rayo_;
}
References longueur_rayo_.
longueur_rayo()
Champ_Don & Fluide_base::longueur_rayo () inline
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
Returns
Champ_Don&
Signification: la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
Contraintes:
Definition at line 321 of file Fluide_base.h.
{
  return longueur_rayo_;
}
References longueur_rayo_.
Referenced by initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), and mettre_a_jour().
longueur_rayo_is_discretised()
int Fluide_base::longueur_rayo_is_discretised ()
Definition at line 467 of file Fluide_base.cpp.
{
  return longueur_rayo_.non_nul();
}
References longueur_rayo_, and O_U_Ptr::non_nul().
mettre_a_jour()
void Fluide_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Reimplemented from Milieu_base.
Reimplemented in Fluide_reel_base, Milieu_composite, and Fluide_Ostwald.
Definition at line 353 of file Fluide_base.cpp.
{
  Milieu_base::mettre_a_jour(temps);
  if (beta_co.non_nul())
    beta_co.mettre_a_jour(temps);
  mu.mettre_a_jour(temps);
  calculer_nu();
  nu.valeur().changer_temps(temps);
  nu->valeurs().echange_espace_virtuel();
  if (e_int_auto_) e_int.mettre_a_jour(temps);
// Mise a jour des proprietes radiatives du fluide incompressible
// (Pour un fluide incompressible semi transparent).
  if (coeff_absorption_.non_nul() && indice_refraction_.non_nul())
    {
      coeff_absorption_.mettre_a_jour(temps);
      indice_refraction_.mettre_a_jour(temps);
// Mise a jour de longueur_rayo
      longueur_rayo_.mettre_a_jour(temps);
      if (sub_type(Champ_Uniforme,kappa().valeur()))
        {
          longueur_rayo()->valeurs()(0,0)=1/(3*kappa()(0,0));
          longueur_rayo()->valeurs().echange_espace_virtuel();
        }
      else
        {
          DoubleTab& l_rayo = longueur_rayo_.valeurs();
          const DoubleTab& K = kappa().valeurs();
          for (int i=0; i<kappa().nb_valeurs_nodales(); i++)
            l_rayo[i] = 1/(3*K[i]);
          l_rayo.echange_espace_virtuel();
        }
    }
}
References beta_co, calculer_nu(), Champ_base::changer_temps(), coeff_absorption_, e_int, e_int_auto_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), indice_refraction_, kappa(), longueur_rayo(), longueur_rayo_, Champ_Don::mettre_a_jour(), Milieu_base::mettre_a_jour(), Champ::mettre_a_jour(), mu, Champ_Don::nb_valeurs_nodales(), O_U_Ptr::non_nul(), nu, sub_type, Deriv_Champ_Don_base::valeur(), valeur(), and Champ_Don::valeurs().
Referenced by Fluide_Ostwald::mettre_a_jour().
printOn()
Sortie & Fluide_base::printOn (Sortie & os) const override protected virtual
Ecrit les proprietes du fluide sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Milieu_base.
Reimplemented in Fluide_Incompressible, Fluide_Ostwald, Fluide_reel_base, Fluide_sodium_gaz, Fluide_sodium_liquide, Milieu_composite, and StiffenedGas.
Definition at line 51 of file Fluide_base.cpp.
{
  os << "{" << finl;
  os << "kappa "<<coeff_absorption_ << finl;
  os << "indice "<<indice_refraction_ << finl;
  os << "longueur_rayo "<<longueur_rayo_ << finl;
  os << "mu " << mu << finl;
  os << "beta_co " << beta_co << finl;
  Milieu_base::ecrire(os);
  os << "}" << finl;
  return os;
}
References beta_co, coeff_absorption_, Milieu_base::ecrire(), finl, indice_refraction_, longueur_rayo_, and mu.
Referenced by Fluide_Incompressible::printOn().
readOn()
Entree & Fluide_base::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Milieu_base.
Reimplemented in Fluide_Incompressible, Fluide_Ostwald, Fluide_reel_base, Fluide_sodium_gaz, Fluide_sodium_liquide, Milieu_composite, and StiffenedGas.
Definition at line 91 of file Fluide_base.cpp.
{
  Milieu_base::readOn(is);
  return is;
}
References Milieu_base::readOn().
Referenced by Fluide_Dilatable_base::readOn(), and Fluide_Incompressible::readOn().
reset_type_rayo()
void Fluide_base::reset_type_rayo ()
Definition at line 454 of file Fluide_base.cpp.
{
  indic_rayo_=NONRAYO;
}
References Milieu_base::indic_rayo_, and Milieu_base::NONRAYO.
self_cast() [1/2]
const Fluide_base & Fluide_base::self_cast (const Objet_U & r) static
Definition at line 29 of file Fluide_base.cpp.
self_cast() [2/2]
Fluide_base & Fluide_base::self_cast (Objet_U & r) static
Definition at line 29 of file Fluide_base.cpp.
set_h0_T0()
void Fluide_base::set_h0_T0 (double h0, double T0) virtual
Definition at line 472 of file Fluide_base.cpp.
{
  T0_ = T0;
  h0_ = h0;
}
References h0_, and T0_.
set_param()
void Fluide_base::set_param (Param & param) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Ostwald, Fluide_reel_base, and StiffenedGas.
Definition at line 97 of file Fluide_base.cpp.
{
  Milieu_base::set_param(param);
// La lecture de rho n est pas specifiee obligatoire ici car ce
// champ ne doit pas etre lu pour un fluide dilatable
  param.ajouter("mu",&mu,Param::REQUIRED);
  param.ajouter("beta_co",&beta_co);
  param.ajouter("kappa",&coeff_absorption_);
  param.ajouter("indice",&indice_refraction_);
}
References Param::ajouter(), beta_co, coeff_absorption_, indice_refraction_, mu, Param::REQUIRED, and Milieu_base::set_param().
Referenced by Fluide_Dilatable_base::set_param(), and Fluide_Ostwald::set_param().
taille_memoire()
unsigned Fluide_base::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Fluide_Incompressible, Fluide_Ostwald, Fluide_sodium_gaz, Fluide_sodium_liquide, Milieu_composite, and StiffenedGas.
Definition at line 29 of file Fluide_base.cpp.
verifier_coherence_champs()
void Fluide_base::verifier_coherence_champs (int & err, Nom & message) override virtual
Verifie que les champs lus l'ont ete correctement.
< Fluide anisotherme
Reimplemented from Milieu_base.
Reimplemented in Fluide_Incompressible.
Definition at line 184 of file Fluide_base.cpp.
{
  msg="";
  if (rho.non_nul())
    {
      if (mp_min_vect(rho.valeurs()) <= 0)
        {
          msg += "The density rho is not striclty positive. \n";
          err = 1;
        }
    }
  else
    {
      msg += "The density rho has not been specified. \n";
      err = 1;
    }
  if  (  (Cp.non_nul()) && ( (lambda.non_nul()) && (beta_th.non_nul()) ) ) //!< Fluide anisotherme
    {
// if (mp_min_vect(Cp.valeurs()) <= 0)
// {
// msg += "The heat capacity Cp is not striclty positive. \n";
// err = 1;
// }
// if (mp_min_vect(lambda.valeurs()) <= 0)
// {
// msg += "The conductivity lambda is not positive. \n";
// err = 1;
// }
      if (sub_type(Champ_Uniforme,Cp.valeur()))
        {
          if  (Cp(0,0) <= 0)
            {
              msg += "The heat capacity Cp is not striclty positive. \n";
              err = 1;
            }
        }
      else
        {
          msg += "The heat capacity Cp is not of type Champ_Uniforme. \n";
          err = 1;
        }
      if (sub_type(Champ_Uniforme,lambda.valeur()))
        {
          if (lambda(0,0) < 0)
            {
              msg += "The conductivity lambda is not positive. \n";
              err = 1;
            }
        }
    }
  if  ( ( (Cp.non_nul()) || (beta_th.non_nul()) ) && (!lambda.non_nul()) )
    {
      msg += " Physical properties for an anisotherm case : \n";
      msg += "the conductivity lambda has not been specified. \n";
      err = 2;
    }
  if  ( ( (lambda.non_nul()) || (beta_th.non_nul()) ) && (!Cp.non_nul()) )
    {
      msg += " Physical properties for an anisotherm case : \n";
      msg += "the heat capacity Cp has not been specified. \n";
      err = 2;
    }
  if ( ( (lambda.non_nul()) || (Cp.non_nul()) ) && (!beta_th.non_nul()) )
    {
      msg += " Physical properties for an anisotherm case : \n";
      msg += "the thermal expansion coefficient beta_th has not been specified. \n";
      err = 2;
    }
// Test de la coherence des proprietees radiatives du fluide incompressible
// (pour un milieu semi transparent
  if ( (coeff_absorption_.non_nul()) && (!indice_refraction_.non_nul()) )
    {
      msg += " Physical properties for semi tranparent radiation case : \n";
      msg += "Refraction index has not been specfied while it has been done for absorption coefficient. \n";
      err = 1;
    }
  if ( (!coeff_absorption_.non_nul()) && (indice_refraction_.non_nul()) )
    {
      msg += " Physical properties for semi tranparent radiation case : \n";
      msg += "Absorption coefficient has not been specfied while it has been done for refraction index. \n";
      err = 1;
    }
  if ( (coeff_absorption_.non_nul()) && indice_refraction_.non_nul() )
    {
      if (sub_type(Champ_Uniforme,coeff_absorption_.valeur()))
        {
          if (coeff_absorption_(0,0) <= 0)
            {
              msg += "The absorption coefficient kappa is not striclty positive. \n";
              err = 1;
            }
        }
    }
  Milieu_base::verifier_coherence_champs(err,msg);
}
References Milieu_base::beta_th, coeff_absorption_, Milieu_base::Cp, indice_refraction_, Milieu_base::lambda, mp_min_vect(), O_U_Ptr::non_nul(), Milieu_base::rho, sub_type, Deriv_Champ_Don_base::valeur(), Champ::valeurs(), and Milieu_base::verifier_coherence_champs().
Referenced by Fluide_Incompressible::verifier_coherence_champs().
viscosite_cinematique() [1/2]
Champ_Don & Fluide_base::viscosite_cinematique () inline
Renvoie la viscosite cinematique, nu.
Returns
Champ_Don&
Signification: la viscosite cinematique, nu
Contraintes:
Definition at line 182 of file Fluide_base.h.
{
  return nu;
}
References nu.
viscosite_cinematique() [2/2]
const Champ_Don & Fluide_base::viscosite_cinematique () const inline
Renvoie la viscosite cinematique, nu.
(vesrion const)
Returns
Champ_Don&
Signification: la viscosite cinematique, nu
Contraintes: reference constante
Definition at line 162 of file Fluide_base.h.
{
  return nu;
}
References nu.
Referenced by Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Perte_Charge_PolyMAC::ajouter_blocs(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Loi_Etat_base::calculer_nu(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), QDM_Multiphase::diffusivite_pour_pas_de_temps(), Navier_Stokes_std::diffusivite_pour_transport(), and VDF_discretisation::reynolds_maille().
viscosite_dynamique() [1/2]
Champ_Don & Fluide_base::viscosite_dynamique () inline
Renvoie la viscosite dynamique, mu.
Returns
Champ_Don&
Signification: la viscosite dynamique, mu
Contraintes:
Definition at line 141 of file Fluide_base.h.
{
  return mu;
}
References mu.
viscosite_dynamique() [2/2]
const Champ_Don & Fluide_base::viscosite_dynamique () const inline
Renvoie la viscosite dynamique, mu.
(version const)
Returns
Champ_Don&
Signification: la viscosite dynamique, mu
Contraintes: reference constante
Definition at line 121 of file Fluide_base.h.
{
  return mu;
}
References mu.
Referenced by Perte_Charge_PolyMAC::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Loi_Etat_base::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_base::calculer_nu(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Navier_Stokes_Fluide_Dilatable_base::diffusivite_pour_transport(), QDM_Multiphase::diffusivite_pour_transport(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), and VEF_discretisation::proprietes_physiques_fluide_Ostwald().
Member Data Documentation
beta_co
Champ_Don Fluide_base::beta_co protected
Definition at line 90 of file Fluide_base.h.
Referenced by beta_c(), discretiser(), initialiser(), mettre_a_jour(), printOn(), and set_param().
coeff_absorption_
Champ_Don Fluide_base::coeff_absorption_ protected
Definition at line 94 of file Fluide_base.h.
Referenced by fixer_type_rayo(), Fluide_Dilatable_base::initialiser(), initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), kappa(), mettre_a_jour(), printOn(), set_param(), and verifier_coherence_champs().
e_int
Champ Fluide_base::e_int mutable protected
Definition at line 88 of file Fluide_base.h.
Referenced by Fluide_reel_base::abortTimeStep(), Milieu_composite::abortTimeStep(), creer_e_int(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), energie_interne(), enthalpie(), Fluide_reel_base::initialiser(), Milieu_composite::initialiser(), initTimeStep(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), and mettre_a_jour().
e_int_auto_
int Fluide_base::e_int_auto_ = 0 mutable protected
Definition at line 85 of file Fluide_base.h.
Referenced by creer_e_int(), initTimeStep(), and mettre_a_jour().
h
Champ Fluide_base::h protected
Definition at line 89 of file Fluide_base.h.
Referenced by Fluide_reel_base::abortTimeStep(), Milieu_composite::abortTimeStep(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), enthalpie(), Fluide_reel_base::initialiser(), Milieu_composite::initialiser(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), and Milieu_composite::mettre_a_jour_tabs().
h0_
double Fluide_base::h0_ = 0 protected
Definition at line 91 of file Fluide_base.h.
Referenced by calculer_e_int(), and set_h0_T0().
indice_refraction_
Champ_Don Fluide_base::indice_refraction_ protected
Definition at line 95 of file Fluide_base.h.
Referenced by fixer_type_rayo(), indice(), Fluide_Dilatable_base::initialiser(), initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), mettre_a_jour(), printOn(), set_param(), and verifier_coherence_champs().
info_obj
const Type_info Fluide_base::info_obj static
Definition at line 41 of file Fluide_base.h.
longueur_rayo_
Champ_Don Fluide_base::longueur_rayo_ protected
Definition at line 99 of file Fluide_base.h.
Referenced by initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), longeur_rayo(), longueur_rayo(), longueur_rayo_is_discretised(), mettre_a_jour(), and printOn().
mu
Champ_Don Fluide_base::mu protected
Definition at line 90 of file Fluide_base.h.
Referenced by calculer_nu(), Fluide_Dilatable_base::creer_champs_non_lus(), creer_nu(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Fluide_Dilatable_base::initialiser(), initialiser(), Fluide_reel_base::initialiser(), Fluide_Dilatable_base::lire_motcle_non_standard(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), printOn(), Espece::set_param(), set_param(), Fluide_Dilatable_base::verifier_coherence_champs(), and viscosite_dynamique().
nu
Champ_Don Fluide_base::nu protected
Definition at line 90 of file Fluide_base.h.
Referenced by calculer_nu(), creer_nu(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), initialiser(), Fluide_reel_base::initialiser(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), and viscosite_cinematique().
T0_
double Fluide_base::T0_ = 0 protected
Definition at line 91 of file Fluide_base.h.
Referenced by calculer_e_int(), and set_h0_T0().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Milieu/Fluide_base.h
src/ThHyd/Incompressible/Milieu/Fluide_base.cpp