TRUST: Ref_Navier_Stokes_std Class Reference
Ref_Navier_Stokes_std Class Reference
#include <Ref_Navier_Stokes_std.h>
Public Member Functions
~Ref_Navier_Stokes_std ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Navier_Stokes_std ()
Ref_Navier_Stokes_std (const Navier_Stokes_std &)
Ref_Navier_Stokes_std (const Ref_Navier_Stokes_std &)
const Navier_Stokes_std & valeur () const
Navier_Stokes_std & valeur ()
const Navier_Stokes_std * operator-> () const
Navier_Stokes_std * operator-> ()
const Ref_Navier_Stokes_std & operator= (const Navier_Stokes_std &)
const Ref_Navier_Stokes_std & operator= (const Ref_Navier_Stokes_std &)
operator const Navier_Stokes_std & () const
operator Navier_Stokes_std & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Navier_Stokes_std & self_cast (Objet_U &)
static const
Ref_Navier_Stokes_std & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Navier_Stokes_std * pointeur_
Detailed Description
Definition at line 28 of file Ref_Navier_Stokes_std.h.
Constructor & Destructor Documentation
Ref_Navier_Stokes_std::~Ref_Navier_Stokes_std ()
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Ref_Navier_Stokes_std::Ref_Navier_Stokes_std ()
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Ref_Navier_Stokes_std::Ref_Navier_Stokes_std (const Navier_Stokes_std & t)
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Ref_Navier_Stokes_std::Ref_Navier_Stokes_std (const Ref_Navier_Stokes_std & t)
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Member Function Documentation
Objet_U * Ref_Navier_Stokes_std::cree_instance () [static]
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
int Ref_Navier_Stokes_std::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Type_info * Ref_Navier_Stokes_std::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Type_info & Ref_Navier_Stokes_std::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Type_info * Ref_Navier_Stokes_std::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Ref_Navier_Stokes_std::operator const Navier_Stokes_std & () const
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Ref_Navier_Stokes_std::operator Navier_Stokes_std & ()
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Navier_Stokes_std * Ref_Navier_Stokes_std::operator-> () const [inline]
Definition at line 28 of file Ref_Navier_Stokes_std.h.
Navier_Stokes_std * Ref_Navier_Stokes_std::operator-> () [inline]
Definition at line 28 of file Ref_Navier_Stokes_std.h.
const Ref_Navier_Stokes_std & Ref_Navier_Stokes_std::operator= (const Ref_Navier_Stokes_std & t)
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Ref_Navier_Stokes_std & Ref_Navier_Stokes_std::operator= (const Navier_Stokes_std & t)
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Sortie & Ref_Navier_Stokes_std::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Entree & Ref_Navier_Stokes_std::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Ref_Navier_Stokes_std & Ref_Navier_Stokes_std::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
Ref_Navier_Stokes_std & Ref_Navier_Stokes_std::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
void Ref_Navier_Stokes_std::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
unsigned Ref_Navier_Stokes_std::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Navier_Stokes_std.cpp.
const Navier_Stokes_std & Ref_Navier_Stokes_std::valeur () const [inline]
Definition at line 28 of file Ref_Navier_Stokes_std.h.
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_Ostwald_VEF::calculer_dscald(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Terme_Source_Coriolis::eq_hydraulique(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Traitement_particulier_NS_Profils::lire(), Traitement_particulier_NS_canal::lire(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VDF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), and Traitement_particulier_NS_canal::preparer_calcul_particulier().
Navier_Stokes_std & Ref_Navier_Stokes_std::valeur () [inline]
Definition at line 28 of file Ref_Navier_Stokes_std.h.
Member Data Documentation
const Type_info Ref_Navier_Stokes_std::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Navier_Stokes_std.h.
Navier_Stokes_std* Ref_Navier_Stokes_std::pointeur_ [private]
Definition at line 28 of file Ref_Navier_Stokes_std.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Equations/Ref_Navier_Stokes_std.h
src/ThHyd/Incompressible/Equations/Ref_Navier_Stokes_std.cpp