TRUST: EFichierBin Class Reference
EFichierBin Class Reference
Lecture dans un fichier d'objets ecrits au format binaire.
#include <EFichierBin.h>
Public Member Functions
~EFichierBin ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
EFichierBin ()
EFichierBin (const char *name, std::_Ios_Openmode mode=ios::in)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static EFichierBin & self_cast (Objet_U &)
static const EFichierBin & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Lecture dans un fichier d'objets ecrits au format binaire.
Definition at line 39 of file EFichierBin.h.
Constructor & Destructor Documentation
EFichierBin::~EFichierBin ()
Definition at line 25 of file EFichierBin.cpp.
EFichierBin::EFichierBin () [inline]
Definition at line 43 of file EFichierBin.h.
References Entree::set_bin().
               :EFichier()
  {
    set_bin(1);
  };
EFichierBin::EFichierBin (const char * name, std::_Ios_Openmode mode = ios::in) [inline]
Definition at line 47 of file EFichierBin.h.
References Cerr, Process::exit(), finl, Entree_Fichier_base::ifstream_, Entree_Fichier_base::ouvrir(), and Entree::set_bin().
  {
    ifstream_=0;
    set_bin(1);
    ouvrir(name,mode);
    if(ifstream_->fail())
      {
        Cerr << "Error while opening the file " << name << finl;
        Process::exit();
      }
  };
Member Function Documentation
Objet_U * EFichierBin::cree_instance () [static]
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
int EFichierBin::duplique () const [virtual]
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
const Type_info * EFichierBin::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
const Type_info * EFichierBin::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
Sortie & EFichierBin::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EFichier.
Definition at line 33 of file EFichierBin.cpp.
{
  throw;
  return s;
}
Entree & EFichierBin::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EFichier.
Definition at line 27 of file EFichierBin.cpp.
{
  throw;
  return s;
}
const EFichierBin & EFichierBin::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
EFichierBin & EFichierBin::self_cast (Objet_U & r) [static]
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
unsigned EFichierBin::taille_memoire () const [virtual]
Reimplemented from EFichier.
Definition at line 25 of file EFichierBin.cpp.
Member Data Documentation
const Type_info EFichierBin::info_obj [static]
Reimplemented from EFichier.
Definition at line 41 of file EFichierBin.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EFichierBin.h
src/Kernel/Utilitaires/EFichierBin.cpp