TRUST: Eval_Diff_VDF_var_aniso Class Reference
Eval_Diff_VDF_var_aniso Class Reference
class Eval_Diff_VDF_var_aniso
Cette classe represente un evaluateur de flux diffusif
avec un coefficient de diffusivite qui n'est pas constant en espace.
#include <Eval_Diff_VDF_var_aniso.h>
Public Member Functions
void associer (const Champ_base &) override
associe le champ de diffusivite
void mettre_a_jour () override
const Champ_base & get_diffusivite () const override
double nu_1_impl (int i, int compo) const
double nu_2_impl (int i, int compo) const
double compute_heq_impl (double d0, int i, double d1, int j, int compo) const
double nu_1_impl_face (int i, int j, int compo) const
double nu_2_impl_face (int i, int j, int k, int l, int compo) const
Public Member Functions inherited from Eval_Diff_VDF
virtual ~Eval_Diff_VDF ()
virtual const Champ_base & get_diffusivite () const =0
virtual void associer (const Champ_base &)=0
virtual void mettre_a_jour ()
int get_ind_Fluctu_Term () const
double get_dv_mvol (const int i) const
virtual double get_equivalent_distance (int boundary_index, int local_face) const
Protected Attributes
Ref_Champ_base diffusivite_
DoubleTab dt_diffusivite
Detailed Description
class Eval_Diff_VDF_var_aniso
Cette classe represente un evaluateur de flux diffusif
avec un coefficient de diffusivite qui n'est pas constant en espace.
See also
Evaluateur_VDF
Definition at line 29 of file Eval_Diff_VDF_var_aniso.h.
Member Function Documentation
associer()
void Eval_Diff_VDF_var_aniso::associer (const Champ_base & diffu) inline override virtual
associe le champ de diffusivite
Implements Eval_Diff_VDF.
Definition at line 75 of file Eval_Diff_VDF_var_aniso.h.
{
// ONLY AVAILABLE FOR TRUST : conduction problem
// TODO : generalize ME
  if (diffu.le_nom() == "conductivite" && diffu.nb_comp() != Objet_U::dimension)
    {
      Cerr << "Error in Eval_Diff_VDF_var_aniso::associer (anisotropic diffusion VDF operator) !" << finl;
      Cerr << "Ensure that the dimension of the conductivity field is equal to the dimension of the domain !" << finl;
      Cerr << "A general conductivity tensor with non-zero cross-corellation terms is not yet supported (switch to VEF) !" << finl;
      Process::exit();
    }
  diffusivite_ = diffu;
  dt_diffusivite.ref(diffu.valeurs());
}
References Cerr, diffusivite_, Objet_U::dimension, dt_diffusivite, Process::exit(), finl, Field_base::le_nom(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::ref(), and Champ_Proto::valeurs().
compute_heq_impl()
double Eval_Diff_VDF_var_aniso::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
Definition at line 39 of file Eval_Diff_VDF_var_aniso.h.
  {
    return 1./(d0/dt_diffusivite(i,compo) + d1/dt_diffusivite(j,compo));
  }
References dt_diffusivite.
get_diffusivite()
const Champ_base & Eval_Diff_VDF_var_aniso::get_diffusivite () const inline override virtual
Implements Eval_Diff_VDF.
Definition at line 67 of file Eval_Diff_VDF_var_aniso.h.
{
  assert(diffusivite_.non_nul());
  return diffusivite_.valeur();
}
References diffusivite_, O_U_Ptr::non_nul(), and Ref_Champ_base::valeur().
mettre_a_jour()
void Eval_Diff_VDF_var_aniso::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
Definition at line 61 of file Eval_Diff_VDF_var_aniso.h.
{
  diffusivite_->valeurs().echange_espace_virtuel();
  dt_diffusivite.ref(diffusivite_->valeurs());
}
References diffusivite_, dt_diffusivite, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTTab< _TYPE_ >::ref(), and Champ_Proto::valeurs().
nu_1_impl()
double Eval_Diff_VDF_var_aniso::nu_1_impl (int i, int compo) const inline
Definition at line 37 of file Eval_Diff_VDF_var_aniso.h.
{ return dt_diffusivite(i,compo); }
References dt_diffusivite.
nu_1_impl_face()
double Eval_Diff_VDF_var_aniso::nu_1_impl_face (int i, int j, int compo) const inline
Definition at line 45 of file Eval_Diff_VDF_var_aniso.h.
  {
    return 0.5*(dt_diffusivite(i,compo)+dt_diffusivite(j,compo));
  }
References dt_diffusivite.
nu_2_impl()
double Eval_Diff_VDF_var_aniso::nu_2_impl (int i, int compo) const inline
Definition at line 38 of file Eval_Diff_VDF_var_aniso.h.
{ return dt_diffusivite(i,compo); }
References dt_diffusivite.
nu_2_impl_face()
double Eval_Diff_VDF_var_aniso::nu_2_impl_face (int i, int j, int k, int l, int compo) const inline
Definition at line 50 of file Eval_Diff_VDF_var_aniso.h.
  {
    return 0.25*(dt_diffusivite(i,compo)+dt_diffusivite(j,compo)+
                 dt_diffusivite(k,compo)+dt_diffusivite(l,compo));
  }
References dt_diffusivite.
Member Data Documentation
diffusivite_
Ref_Champ_base Eval_Diff_VDF_var_aniso::diffusivite_ protected
Definition at line 57 of file Eval_Diff_VDF_var_aniso.h.
Referenced by associer(), get_diffusivite(), and mettre_a_jour().
dt_diffusivite
DoubleTab Eval_Diff_VDF_var_aniso::dt_diffusivite protected
Definition at line 58 of file Eval_Diff_VDF_var_aniso.h.
Referenced by associer(), compute_heq_impl(), mettre_a_jour(), nu_1_impl(), nu_1_impl_face(), nu_2_impl(), and nu_2_impl_face().
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Diff_VDF_var_aniso.h