TRUST: Equation Class Reference
Equation Class Reference
classe Equation
Classe generique de la hierarchie des equations. Un objet Equation peut
referencer n'importe quel objet derivant de Equation_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Equation.h>
Public Member Functions
Equation ()
~Equation ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int nombre_d_operateurs () const
Appel a l'objet sous-jacent.
Renvoie le nombre d'operateurs de l'equation.
const Operateur & operateur (int) const
Appel a l'objet sous-jacent.
Renvoie le i-eme operateur.
(version const)
Operateur & operateur (int)
Appel a l'objet sous-jacent.
Renvoie le i-eme operateur.
const Champ_Inc & inconnue () const
Appel a l'objet sous-jacent.
Renvoie le champ inconnue.
(version const)
Champ_Inc & inconnue ()
Appel a l'objet sous-jacent.
Renvoie le champ inconnue.
void discretiser ()
Appel a l'objet sous-jacent.
Discretise l'equation: type l'inconnue.
int sauvegarder (Sortie &) const
Appel a l'objet sous-jacent.
Effectue une sauvegarde des inconnues de l'equation.
int reprendre (Entree &)
Appel a l'objet sous-jacent.
Effectue une reprise apres une sauvegarde.
void associer_sch_tps_base (const Schema_Temps_base &)
Appel a l'objet sous-jacent.
Associe un schema en temps a l'equation.
void associer_milieu_base (const Milieu_base &)
Appel a l'objet sous-jacent.
Associe un milieu physique a l'equation.
NOTE: cette methode est abstraite dans Equation_base et prend un
dans ses derivees. Voir par exemple: Navier_Stokes_std.
const Milieu_base & milieu () const
Appel a l'objet sous-jacent.
Renvoie le milieu physique de l'equation.
(version const)
Milieu_base & milieu ()
Appel a l'objet sous-jacent.
Renvoie le milieu physique de l'equation.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Equation & self_cast (Objet_U &)
static const Equation & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime l'equation et ses composants sur un flot de sortie.
virtual Entree & readOn (Entree &)
Imprime l'equation et ses composants sur un flot de sortie.
Detailed Description
classe Equation
Classe generique de la hierarchie des equations. Un objet Equation peut
referencer n'importe quel objet derivant de Equation_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 45 of file Equation.h.
Constructor & Destructor Documentation
Equation::Equation ()
Definition at line 26 of file Equation.cpp.
Equation::~Equation ()
Definition at line 26 of file Equation.cpp.
Member Function Documentation
void Equation::associer_milieu_base (const Milieu_base & mil) [inline]
Appel a l'objet sous-jacent.
Associe un milieu physique a l'equation.
NOTE: cette methode est abstraite dans Equation_base et prend un
dans ses derivees. Voir par exemple: Navier_Stokes_std.
Definition at line 270 of file Equation.h.
References Equation_base::associer_milieu_base(), and Deriv_Equation_base::valeur().
{
  valeur().associer_milieu_base(mil);
}
void Equation::associer_sch_tps_base (const Schema_Temps_base & un_schema_temps) [inline]
Appel a l'objet sous-jacent.
Associe un schema en temps a l'equation.
Definition at line 249 of file Equation.h.
References Equation_base::associer_sch_tps_base(), and Deriv_Equation_base::valeur().
{
  valeur().associer_sch_tps_base(un_schema_temps);
}
Objet_U * Equation::cree_instance () [static]
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
void Equation::discretiser () [inline]
Appel a l'objet sous-jacent.
Discretise l'equation: type l'inconnue.
Definition at line 170 of file Equation.h.
References Equation_base::discretiser(), and Deriv_Equation_base::valeur().
{
  valeur().discretiser();
}
int Equation::duplique () const [virtual]
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
const Type_info * Equation::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
const Champ_Inc & Equation::inconnue () const [inline]
Appel a l'objet sous-jacent.
Renvoie le champ inconnue.
(version const)
Returns:
Champ_Inc&
Signification: le champ inconnue de l'equation
Contraintes: reference constante
Definition at line 150 of file Equation.h.
References Equation_base::inconnue(), and Deriv_Equation_base::valeur().
Referenced by List_Equations_Scalaires_Passifs_Especes::inconnue().
{
  return valeur().inconnue();
}
Champ_Inc & Equation::inconnue () [inline]
Appel a l'objet sous-jacent.
Renvoie le champ inconnue.
Returns:
Champ_Inc&
Signification: le champ inconnue de l'equation
Contraintes:
Definition at line 189 of file Equation.h.
References Equation_base::inconnue(), and Deriv_Equation_base::valeur().
{
  return valeur().inconnue();
}
const Type_info * Equation::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
Milieu_base & Equation::milieu () [inline]
Appel a l'objet sous-jacent.
Renvoie le milieu physique de l'equation.
Returns:
Milieu_base&
Signification: le milieu physique de l'equation
Contraintes:
Definition at line 309 of file Equation.h.
References Equation_base::milieu(), and Deriv_Equation_base::valeur().
{
  return valeur().milieu();
}
const Milieu_base & Equation::milieu () const [inline]
Appel a l'objet sous-jacent.
Renvoie le milieu physique de l'equation.
(version const)
Returns:
Milieu_base&
Signification: le milieu physique de l'equation
Contraintes: reference constante
Definition at line 290 of file Equation.h.
References Equation_base::milieu(), and Deriv_Equation_base::valeur().
{
  return valeur().milieu();
}
int Equation::nombre_d_operateurs () const [inline]
Appel a l'objet sous-jacent.
Renvoie le nombre d'operateurs de l'equation.
Returns:
int
Signification: le nombre d'operateur de l'equation
Contraintes:
Definition at line 88 of file Equation.h.
References Equation_base::nombre_d_operateurs(), and Deriv_Equation_base::valeur().
{
  return valeur().nombre_d_operateurs();
}
const Operateur & Equation::operateur (int i) const [inline]
Appel a l'objet sous-jacent.
Renvoie le i-eme operateur.
(version const)
Returns:
Operateur&
Signification: i-eme operateur de l'equation
Contraintes: reference constante
Definition at line 109 of file Equation.h.
References Equation_base::operateur(), and Deriv_Equation_base::valeur().
Referenced by List_Equations_Scalaires_Passifs_Especes::operateur().
{
  return valeur().operateur(i);
}
Operateur & Equation::operateur (int i) [inline]
Appel a l'objet sous-jacent.
Renvoie le i-eme operateur.
Returns:
Operateur&
Signification: le i-eme operateur de l'equation
Contraintes:
Definition at line 129 of file Equation.h.
References Equation_base::operateur(), and Deriv_Equation_base::valeur().
{
  return valeur().operateur(i);
}
Sortie & Equation::printOn (Sortie & os) const [protected, virtual]
Imprime l'equation et ses composants sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Equation_base.
Definition at line 43 of file Equation.cpp.
References DERIV.
{
  return DERIV(Equation_base)::printOn(os);
}
Entree & Equation::readOn (Entree & is) [protected, virtual]
Imprime l'equation et ses composants sur un flot de sortie.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Equation_base.
Definition at line 63 of file Equation.cpp.
References DERIV.
{
  return DERIV(Equation_base)::readOn(is);
}
int Equation::reprendre (Entree & is) [inline, virtual]
Appel a l'objet sous-jacent.
Effectue une reprise apres une sauvegarde.
Returns:
int
Signification: code de retour propage (1 si reprise OK)
Contraintes:
Reimplemented from Objet_U.
Definition at line 229 of file Equation.h.
References Equation_base::reprendre(), and Deriv_Equation_base::valeur().
{
  return valeur().reprendre(is);
}
int Equation::sauvegarder (Sortie & os) const [inline, virtual]
Appel a l'objet sous-jacent.
Effectue une sauvegarde des inconnues de l'equation.
Returns:
int
Signification: code de retour propage
Contraintes:
Reimplemented from Objet_U.
Definition at line 209 of file Equation.h.
References Equation_base::sauvegarder(), and Deriv_Equation_base::valeur().
{
  return valeur().sauvegarder(os);
}
Equation & Equation::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
const Equation & Equation::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
unsigned Equation::taille_memoire () const [virtual]
Reimplemented from Deriv_Equation_base.
Definition at line 26 of file Equation.cpp.
Member Data Documentation
const Type_info Equation::info_obj [static]
Reimplemented from Deriv_Equation_base.
Definition at line 47 of file Equation.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Equation.h
src/Kernel/Framework/Equation.cpp