TRUST: Solv_Gmres Class Reference
Solv_Gmres Class Reference
#include <Solv_Gmres.h>
Public Member Functions
~Solv_Gmres ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solv_Gmres ()
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &M, const DoubleVect &A, DoubleVect &B, int niter_max) override
Public Member Functions inherited from solv_iteratif
~solv_iteratif () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
solv_iteratif ()
void set_seuil (double s)
double get_seuil () const
int solveur_direct () const override
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solv_Gmres & self_cast (Objet_U &)
static const Solv_Gmres & self_cast (const Objet_U &)
Static Public Member Functions inherited from solv_iteratif
static const Type_info * info ()
static solv_iteratif & self_cast (Objet_U &)
static const solv_iteratif & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from solv_iteratif
static const Type_info info_obj
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int Gmres (const Matrice_Morse &, const DoubleVect &, DoubleVect &)
Protected Member Functions inherited from solv_iteratif
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleVects v
int is_local_gmres
int precond_diag
int nb_it_max_
int controle_residu_
int dim_espace_Krilov_
Protected Attributes inherited from solv_iteratif
double seuil_
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 25 of file Solv_Gmres.h.
Constructor & Destructor Documentation
~Solv_Gmres()
Solv_Gmres::~Solv_Gmres ()
Definition at line 25 of file Solv_Gmres.cpp.
Solv_Gmres()
Solv_Gmres::Solv_Gmres ()
Definition at line 27 of file Solv_Gmres.cpp.
{
  seuil_ = 1.e-12;
  is_local_gmres=0;
  precond_diag=0;
  nb_it_max_ = 1000000;
  controle_residu_ =0;
  dim_espace_Krilov_=10;
}
References controle_residu_, dim_espace_Krilov_, is_local_gmres, nb_it_max_, precond_diag, and solv_iteratif::seuil_.
Member Function Documentation
cree_instance()
Objet_U * Solv_Gmres::cree_instance () static
Definition at line 25 of file Solv_Gmres.cpp.
duplique()
int Solv_Gmres::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Solv_Gmres.cpp.
get_info()
const Type_info * Solv_Gmres::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Solv_Gmres.cpp.
Gmres()
int Solv_Gmres::Gmres (const Matrice_Morse & matrice, const DoubleVect & secmem, DoubleVect & solution) protected
Definition at line 410 of file Solv_Gmres.cpp.
{
  if (!is_local_gmres)
    return matrice.inverse(secmem, solution, seuil_);
  else
    return gmres_local(matrice,secmem,solution,seuil_,precond_diag,nb_it_max_,controle_residu_,v,dim_espace_Krilov_,limpr());
}
References controle_residu_, dim_espace_Krilov_, gmres_local(), Matrice_Morse::inverse(), is_local_gmres, SolveurSys_base::limpr(), nb_it_max_, precond_diag, solv_iteratif::seuil_, and v.
Referenced by resoudre_systeme().
info()
const Type_info * Solv_Gmres::info () static
Definition at line 25 of file Solv_Gmres.cpp.
printOn()
Sortie & Solv_Gmres::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Solv_Gmres.cpp.
{
  s<<" { seuil "<<seuil_;
  if (precond_diag)
    s <<" diag ";
  else if (is_local_gmres) s<<" sans_precond ";
  if (controle_residu_) s<< " controle_residu "<<controle_residu_;
  if (nb_it_max_!=1000000) s<<" nb_it_max "<<nb_it_max_;
  if (limpr()==1) s<<" impr ";
  if (limpr()==-1) s<<" quiet ";
  if (save_matrice_) s<< " save_matrice ";
  s<<" dim_espace_krilov "<<dim_espace_Krilov_;
  s<<" } ";
  return s;
}
References controle_residu_, dim_espace_Krilov_, is_local_gmres, SolveurSys_base::limpr(), nb_it_max_, precond_diag, SolveurSys_base::save_matrice_, and solv_iteratif::seuil_.
readOn()
Entree & Solv_Gmres::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 55 of file Solv_Gmres.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcles les_parametres(9);
  {
    les_parametres[0] = "impr";
    les_parametres[1] = "seuil";
    les_parametres[2] = "diag";
    les_parametres[3] = "sans_precond";
    les_parametres[4] = "nb_it_max";
    les_parametres[5] = "controle_residu";
    les_parametres[6] = "save_matrice|save_matrix";
    les_parametres[7] = "dim_espace_krilov";
    les_parametres[8] = "quiet";
  }
  int rang;
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error when reading the GMRES parameters " << finl;
      Cerr << "One expected " << accolade_ouverte
           << " instead of : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      rang = les_parametres.search(motlu);
      switch(rang)
        {
        case 0:
          {
            fixer_limpr(1);
            break;
          }
        case 8:
          {
            fixer_limpr(-1);
            break;
          }
        case 1:
          {
            is >> seuil_;
            break;
          }
        case 2:
          {
            is_local_gmres=1;
            precond_diag=1;
            break;
          }
        case 3:
          {
            is_local_gmres=1;
            precond_diag=0;
            break;
          }
        case 4:
          {
            is>>nb_it_max_;
            break;
          }
        case 5:
          {
            is>>controle_residu_;
            break;
          }
        case 6:
          {
            save_matrice_=1;
            break;
          }
        case 7:
          {
            is >>dim_espace_Krilov_;
            break;
          }
        default :
          {
            Cerr << "Error when reading the Gmres parameters " << finl;
            Cerr << "One expected a word among " << les_parametres
                 << " instead of " << motlu << finl;
            exit();
          }
        }
      is >> motlu;
    }
  return is;
}
References Cerr, controle_residu_, dim_espace_Krilov_, Process::exit(), finl, SolveurSys_base::fixer_limpr(), is_local_gmres, nb_it_max_, precond_diag, SolveurSys_base::save_matrice_, Motcles::search(), and solv_iteratif::seuil_.
resoudre_systeme() [1/2]
int Solv_Gmres::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
Definition at line 151 of file Solv_Gmres.cpp.
{
  if(sub_type(Matrice_Morse,la_matrice))
    {
      const Matrice_Morse& matrice = ref_cast(Matrice_Morse, la_matrice);
      int retour= Gmres(matrice,secmem,solution);
      DoubleVect b(secmem);
      matrice.multvect(solution, b);
// Cerr << " b :" << b<< finl;
// Cerr << " secmem :" << secmem<< finl;
      b-=secmem;
// Cerr << "||residu|| = " << b.norme() << finl;
      return retour;
    }
  else
    {
      if(sub_type(Matrice_Bloc,la_matrice))
        {
          const Matrice_Bloc& matrice = ref_cast(Matrice_Bloc,la_matrice);
          if(matrice.nb_bloc_lignes()>1)
            {
              Cerr<<"Solv_Gmres : WARNING : one is not able to carry out Gmres by blocks"<<finl;
              exit();
              return(-1);
            }
          if (Process::nproc() > 1)
            {
              Cerr<<"Solv_Gmres : WARNING : one is not able to carry out parallel calculation with Gmres"<<finl;
              exit();
              return(-1);
            }
          const Matrice_Morse& MB00 = ref_cast(Matrice_Morse,matrice.get_bloc(0,0).valeur());
          int retour= Gmres(MB00,secmem,solution);
          return retour;
        }
      else
        {
          Cerr<<"Solv_Gmres : WARNING : only linear systems based on Matrice_Morse_Sym or Matrice_Bloc type matrixes can be solved"<<finl;
          exit();
          return(-1);
        }
    }
}
References Cerr, Process::exit(), finl, Matrice_Bloc::get_bloc(), Gmres(), Matrice_Base::multvect(), Matrice_Bloc::nb_bloc_lignes(), Process::nproc(), ref_cast, sub_type, and Deriv_Matrice_Base::valeur().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Gmres::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 33 of file Solv_Gmres.h.
  {
    return resoudre_systeme(M, A, B);
  }
References resoudre_systeme().
self_cast() [1/2]
const Solv_Gmres & Solv_Gmres::self_cast (const Objet_U & r) static
Definition at line 25 of file Solv_Gmres.cpp.
self_cast() [2/2]
Solv_Gmres & Solv_Gmres::self_cast (Objet_U & r) static
Definition at line 25 of file Solv_Gmres.cpp.
taille_memoire()
unsigned Solv_Gmres::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Solv_Gmres.cpp.
Member Data Documentation
controle_residu_
int Solv_Gmres::controle_residu_ protected
Definition at line 43 of file Solv_Gmres.h.
Referenced by Gmres(), printOn(), readOn(), and Solv_Gmres().
dim_espace_Krilov_
int Solv_Gmres::dim_espace_Krilov_ protected
Definition at line 43 of file Solv_Gmres.h.
Referenced by Gmres(), printOn(), readOn(), and Solv_Gmres().
info_obj
const Type_info Solv_Gmres::info_obj static
Definition at line 27 of file Solv_Gmres.h.
is_local_gmres
int Solv_Gmres::is_local_gmres protected
Definition at line 42 of file Solv_Gmres.h.
Referenced by Gmres(), printOn(), readOn(), and Solv_Gmres().
nb_it_max_
int Solv_Gmres::nb_it_max_ protected
Definition at line 43 of file Solv_Gmres.h.
Referenced by Gmres(), printOn(), readOn(), and Solv_Gmres().
precond_diag
int Solv_Gmres::precond_diag protected
Definition at line 42 of file Solv_Gmres.h.
Referenced by Gmres(), printOn(), readOn(), and Solv_Gmres().
v
DoubleVects Solv_Gmres::v protected
Definition at line 41 of file Solv_Gmres.h.
Referenced by Gmres().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_Gmres.h
src/Kernel/Math/SolvSys/Solv_Gmres.cpp