TRUST: Zone_VEF Class Reference
Zone_VEF Class Reference
class Zone_VEF
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
#include <Zone_VEF.h>
Public Member Functions
Zone_VEF ()
~Zone_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser () override
Genere les faces
construits les frontieres.
void swap (int, int, int)
void reordonner (Faces &) override
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &) override
void typer_elem (Zone &) override
const Elem_VEF & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
int premiere_face_std () const
int nb_faces_non_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const override
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
DoubleTab & facette_normales ()
const DoubleTab & facette_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
DoubleTab & vecteur_face_facette ()
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_volumes_entrelaces ()
void calculer_h_carre ()
Public Member Functions inherited from Zone_VF
Zone_VF ()
~Zone_VF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double face_normales (int, int) const =0
void calculer_face_surfaces (const DoubleVect &surfaces)
virtual const DoubleVect & face_surfaces () const
virtual double face_surfaces (int i) const
virtual double surface (int i) const
void discretiser () override
Genere les faces
construits les frontieres.
void infobord ()
void info_elem_som ()
void calculer_porosites ()
void calculer_diametres_hydrauliques ()
void calculer_sections_passage ()
void calculer_coefficient_echange_thermique ()
void calculer_coefficient_frottement ()
void marquer_faces_double_contrib (const Conds_lim &)
virtual void typer_elem (Zone &)
virtual void remplir_face_voisins_fictifs (const Zone_Cl_dis_base &)
virtual Faces * creer_faces ()
renvoie new(Faces) !
elle est surchargee par Zone_VDF par ex.
virtual void reordonner (Faces &)
cette methode ne fait rien
elle est surchargee par Zone_VDF par ex.
int nb_joints () const
renvoie le nombre de joints
int premiere_face_int () const
une face est interne ssi elle separe deux elements.
renvoie le numero de la premiere face interne.
int nb_faces () const
renvoie le nombre global de faces.
int nb_faces_tot () const
renvoie le nombre total de faces.
C'est-a-dire faces reelles + faces virtuelles
int nb_som_face () const
renvoie le nombre de sommets par face.
Rque : on a suppose que toutes les faces avait
le meme nombre de sommet ce qui exclue des elements
comme le prisme.
int nb_faces_bord () const
renvoie le nombre de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_bord_tot () const
renvoie le nombre total de faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int premiere_face_bord () const
renvoie le numero de la premiere des faces sur lesquelles
sont appliquees les conditions limites :
bords, raccords, plaques.
int nb_faces_internes () const
une face est interne ssi elle separe deux elements.
renvoie le nombre de faces internes.
double xv (int, int) const
double xp (int, int) const
double xa (int, int) const
double porosite_face (int) const
double porosite_elem (int) const
double diametre_hydraulique_face (int) const
double section_passage_face (int) const
double coefficient_frottement (int) const
double coefficient_echange_thermique (int) const
int face_numero_bord (int num_face) const
IntTab & face_numero_bord ()
const IntTab & face_numero_bord () const
void remplir_face_numero_bord ()
virtual const IntVect & orientation () const
virtual int orientation (int) const
virtual int orientation_si_definie (int) const
DoubleTab normalized_boundaries_outward_vector (int global_face_number, double scale_factor) const
Compute the normalized boundary outward vector associated to the face global_face_number
and eventually scaled by scale_factor.
DoubleTab & xv ()
const DoubleTab & xv () const
DoubleTab & xp ()
const DoubleTab & xp () const
DoubleTab & xa ()
const DoubleTab & xa () const
DoubleVect & volumes_entrelaces ()
const DoubleVect & volumes_entrelaces () const
double volumes_entrelaces (int num_face) const
const DoubleTab & volumes_entrelaces_dir () const
DoubleTab & volumes_entrelaces_dir ()
DoubleVect & porosite_face ()
const DoubleVect & porosite_face () const
DoubleVect & porosite_elem ()
const DoubleVect & porosite_elem () const
DoubleVect & diametre_hydraulique_face ()
const DoubleVect & diametre_hydraulique_face () const
const DoubleVect section_passage_face () const
DoubleTab & diametre_hydraulique_elem ()
const DoubleTab & diametre_hydraulique_elem () const
DoubleVect & coefficient_frottement ()
const DoubleVect & coefficient_frottement () const
DoubleVect & coefficient_echange_thermique ()
const DoubleVect & coefficient_echange_thermique () const
const Joint & joint (int i) const
renvoie le ieme joint.
Joint & joint (int i)
renvoie le ieme joint.
Frontiere_dis_base & frontiere_dis (int) override
renvoie la ieme frontiere_discrete.
const Frontiere_dis_base & frontiere_dis (int) const override
renvoie la ieme frontiere_discrete.
int nb_frontiere_dis () const
const Front_VF & front_VF (int) const
renvoie la ieme frontiere_discrete.
double volumes (int i) const
renvoie le volume de la maille i.
double inverse_volumes (int i) const
int face_voisins (int num_face, int i) const
renvoie l'element voisin de numface dans la direction i.
i=0 : dans le sens oppose de l'axe orthogonal a la face numface.
i=1 : dans le sens de l'axe orthogonal a la face numface.
exemple :
| 0 | 1 |
numface
renvoie -1 si l'element n'existe pas (au bord).
int elem_faces (int i, int j) const
renvoie le numero de le ieme face de la maille num_elem
la facon dont ces faces sont numerotees est
laisse a la responsabilite des classes derivees
int face_sommets (int i, int j) const
renvoie le numero du ieme sommet de la face num_face.
DoubleVect & volumes ()
renvoie le tableaux des volumes des mailles.
DoubleVect & inverse_volumes ()
Tableau pour optimiser le code.
const DoubleVect & volumes () const
renvoie le tableaux des volumes des mailles.
const DoubleVect & inverse_volumes () const
Tableau pour optimiser le code.
IntTab & face_voisins () override
renvoie le tableaux des volumes des connectivites face elements
cf au dessus.
const IntTab & face_voisins () const override
cf au dessus.
const IntTab & face_voisins_fictifs () const
void face_voisins_reel_fictif (int face, int &el0, int &elf) const
renvoie dans el0 le numero de l'elt a l'interieur
renvoie dans elf le numero de l'elt fictif (-1 si il n'existe pas)
IntTab & elem_faces ()
renvoie le tableau de connectivite element/faces
const IntTab & elem_faces () const
cf au dessus.
ArrOfInt & faces_doubles ()
renvoie 1 pour les faces appartenant a un bord perio ou un item commun, 0 par defaut
const ArrOfInt & faces_doubles () const
cf au dessus
IntTab & face_sommets () override
renvoie le tableau de connectivite faces/sommets.
const IntTab & face_sommets () const override
cf au dessus.
void modifier_pour_Cl (const Conds_lim &) override
int numero_face_local (int face, int elem) const
int numero_sommet_local (int som, int elem) const
const IntTab & get_num_fac_loc () const
int get_num_fac_loc (int, int) const
void construire_num_fac_loc ()
const ArrOfInt & ind_faces_virt_bord () const
int est_une_face_virt_bord (int) const
renvoie 1 si face est une face virtuelle de bord, 0 sinon
int fbord (int f) const
void construire_face_virt_pe_num ()
Remplissage du tableau face_virt_pe_num_ (voir commentaire dans Zone_VF.h)
const IntTab & face_virt_pe_num () const
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_aretes (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual void creer_tableau_faces_bord (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
virtual const MD_Vector & md_vector_faces_bord () const
virtual const MD_Vector & md_vector_faces () const
virtual const MD_Vector & md_vector_aretes () const
virtual const DoubleTab & xv_bord () const
Public Member Functions inherited from Zone_dis_base
Zone_dis_base ()
~Zone_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe une Zone a l'objet.
const Zone & zone () const
Renvoie la Zone associee a l'objet.
(version const)
Zone & zone ()
Renvoie la Zone associee a l'objet.
void associer_domaine_dis (const Domaine_dis &)
Associe un Domaine_dis a l'objet.
const Domaine_dis & domaine_dis () const
Domaine_dis & domaine_dis ()
virtual void discretiser ()=0
virtual void creer_elements_fictifs (const Zone_Cl_dis_base &)
virtual Frontiere_dis_base & frontiere_dis (int)=0
virtual const Frontiere_dis_base & frontiere_dis (int) const =0
int rang_frontiere (const Nom &)
int rang_frontiere (const Nom &) const
Renvoie le rang de la frontiere de Nom nom
Renvoie -1 si aucune frontiere ne s'appelle nom.
Frontiere_dis_base & frontiere_dis (const Nom &)
const Frontiere_dis_base & frontiere_dis (const Nom &) const
Renvoie la frontiere de Nom nom.
(On indexe les frontiere avec leur nom)
void ecrire_noms_bords (Sortie &) const
Ecriture des noms des bords sur un flot de sortie.
virtual void modifier_pour_Cl (const Conds_lim &)=0
virtual IntTab & face_sommets ()
virtual const IntTab & face_sommets () const
virtual IntTab & face_voisins ()
virtual const IntTab & face_voisins () const
int nb_elem () const
int nb_elem_tot () const
int nb_som () const
int nb_som_tot () const
int nb_front_Cl () const
virtual void init_dist_paroi_globale (const Conds_lim &conds_lim)
virtual const DoubleTab & y_elem () const
virtual const DoubleTab & y_faces () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_VEF & self_cast (Objet_U &)
static const Zone_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_VF
static const Type_info * info ()
static Zone_VF & self_cast (Objet_U &)
static const Zone_VF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_dis_base
static const Type_info * info ()
static Zone_dis_base & self_cast (Objet_U &)
static const Zone_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_VF
static const Type_info info_obj
Static Public Attributes inherited from Zone_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
virtual void remplir_elem_faces ()=0
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void remplir_elem_faces () override
Sortie & ecrit (Sortie &os) const
void creer_faces_virtuelles_non_std ()
creation de l'espace distant pour les faces virtuelles;
creation du tableau des faces virtuelles de bord
Private Attributes
double h_carre
carre du pas du maillage
DoubleVect h_carre_
carre du pas d'une maille
Elem_VEF type_elem_
type de l'element de discretisation
DoubleTab face_normales_
normales aux faces
DoubleTab facette_normales_
normales aux faces des volumes entrelaces
DoubleTab vecteur_face_facette_
vecteur centre face->centre facette
int nb_faces_std_
nombre de faces standard
int nb_elem_std_
nombre d'elements standard
IntVect rang_elem_non_std_
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
ArrOfInt ind_faces_virt_non_std_
contient les indices des faces virtuelles non standard
IntVect orientation_
Additional Inherited Members
Protected Attributes inherited from Zone_VF
DoubleVect volumes_
volumes des elements
DoubleVect inverse_volumes_
inverse du volumes des elements
DoubleVect volumes_entrelaces_
volumes entrelaces pour l'integration des Qdm
DoubleTab volumes_entrelaces_dir_
volumes entrelaces par cote
DoubleVect porosite_elem_
Porosites volumiques pour les volumes de controle de masse.
DoubleVect porosite_face_
Porosites surfaciques en masse et volumiques.
DoubleVect diametre_hydraulique_face_
DoubleTab diametre_hydraulique_elem_
DoubleVect coefficient_echange_thermique_
remplissage des coefficients d'echange_thermique
DoubleVect coefficient_frottement_
remplissage des coefficient de frottement
IntTab face_voisins_
connectivite face/elements
IntTab face_voisins_fictifs_
connectivite face/elements fictifs
DoubleTab xp_
centres de gravite des elements
DoubleTab xv_
centres de gravite des faces
DoubleTab xv_bord_
IntTab elem_faces_
connectivite element/faces
IntTab face_sommets_
sommets des faces
DoubleTab xa_
centres de gravite des aretes
IntTab face_numero_bord_
connectivite face/numero_bord
MD_Vector md_vector_faces_
MD_Vector md_vector_faces_front_
MD_Vector md_vector_aretes_
Vect_Front_VF les_bords_
IntTab num_fac_loc_
ArrOfInt faces_doubles_
faces a double contribution (faces periodiques et items communs)
IntTab face_virt_pe_num_
Protected Attributes inherited from Zone_dis_base
Ref_Zone la_zone
Ref_Domaine_dis le_domaine_dis
DoubleTab y_elem_
DoubleTab y_faces_
int dist_paroi_initialisee_ = 0
Detailed Description
class Zone_VEF
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Definition at line 61 of file Zone_VEF.h.
Constructor & Destructor Documentation
Zone_VEF()
Zone_VEF::Zone_VEF ()
Definition at line 32 of file Zone_VEF.cpp.
~Zone_VEF()
Zone_VEF::~Zone_VEF ()
Definition at line 32 of file Zone_VEF.cpp.
Member Function Documentation
calculer_h_carre()
void Zone_VEF::calculer_h_carre ()
Definition at line 384 of file Zone_VEF.cpp.
{
  const int nbe=nb_elem();
// Calcul de h_carre
  h_carre = 1.e30;
  h_carre_.resize(nbe);
// Calcul des surfaces
  const DoubleVect& surfaces=face_surfaces();
  const int nb_faces_elem=zone().nb_faces_elem();
  for (int num_elem=0; num_elem<nbe; num_elem++)
    {
      double surf_max = 0;
      for (int i=0; i<nb_faces_elem; i++)
        {
          double surf = surfaces(elem_faces(num_elem,i));
          surf_max = (surf > surf_max)? surf : surf_max;
        }
      double vol = volumes(num_elem)/surf_max;
      vol *= vol;
      h_carre_(num_elem) = vol;
      h_carre = ( vol < h_carre )? vol : h_carre;
    }
// Modif BM: je pense qu'avec mp_min(h_carre) on va eviter beaucoup de differences seq/par
  h_carre = mp_min(h_carre);
  Cerr << "Lowest cell size h=(Volume/max(Surface))= " << sqrt(h_carre) << finl;
  double moyenne = 0.;
  for (int i = 0; i < nbe; i++)
    moyenne += h_carre_(i);
  moyenne = mp_sum(moyenne);
  double h_carre_moyen = moyenne / mp_sum((double)nbe);
  Cerr << "Average cell size <h>= " << sqrt(h_carre_moyen) << finl;
  if (h_carre*1e6<h_carre_moyen)
    Cerr << "Warning, a cell size is more than 1000 times smaller than the average cell size of the domain. Check your mesh." << finl;
  Cerr<<"=============================================="<<finl;
}
References Cerr, Zone_VF::elem_faces(), Zone_VF::face_surfaces(), finl, h_carre, h_carre_, Process::mp_min(), Process::mp_sum(), Zone_dis_base::nb_elem(), Zone::nb_faces_elem(), TRUSTVect< _TYPE_ >::resize(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by discretiser().
calculer_volumes_entrelaces()
void Zone_VEF::calculer_volumes_entrelaces ()
Definition at line 420 of file Zone_VEF.cpp.
{
// Cerr << "les normales aux faces " << face_normales() << finl;
// On calcule les volumes entrelaces;
// Si domaine dynamique, le tableau peut eventuellement deja avoir la bonne structure, ou pas.
// S'il n'est pas deformable, on n'est pas cense passer ici deux fois.
  assert(zone().domaine().deformable()
         || !(volumes_entrelaces_.get_md_vector().non_nul()));
  if (!(volumes_entrelaces_.get_md_vector() == md_vector_faces()))
    {
      volumes_entrelaces_.reset();
      creer_tableau_faces(volumes_entrelaces_, Array_base::NOCOPY_NOINIT);
    }
  int nb_faces_elem=zone().nb_faces_elem();
  int num_face;
  int nmax = premiere_face_int();
  const double facteur = 1. / nb_faces_elem;
  for (num_face = 0; num_face < nmax; num_face++)
    {
      int elem1 = face_voisins_(num_face,0);
      volumes_entrelaces_[num_face] = volumes(elem1) * facteur;
    }
  nmax = nb_faces();
  for ( ; num_face < nmax; num_face++)
    {
      int elem1 = face_voisins_(num_face,0);
      int elem2 = face_voisins_(num_face,1);
      volumes_entrelaces_[num_face] = (volumes(elem1) + volumes(elem2)) * facteur;
    }
  volumes_entrelaces_.echange_espace_virtuel();
}
References Zone_VF::creer_tableau_faces(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::face_voisins_, TRUSTVect< _TYPE_ >::get_md_vector(), Zone_VF::md_vector_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), Zone_VF::premiere_face_int(), TRUSTVect< _TYPE_ >::reset(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces_, and Zone_dis_base::zone().
Referenced by discretiser().
carre_pas_du_maillage()
double Zone_VEF::carre_pas_du_maillage () const inline
Definition at line 207 of file Zone_VEF.h.
{
  return h_carre;
}
References h_carre.
Referenced by Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), and Op_Diff_VEF_Face_Q1::calculer_dt_stab().
carre_pas_maille()
double Zone_VEF::carre_pas_maille (int i) const inline
Definition at line 82 of file Zone_VEF.h.
  {
    return h_carre_(i);
  };
References h_carre_.
Referenced by Op_Dift_VEF_base::calculer_borne_locale(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_pour_post(), and Op_Dift_VEF_Face::calculer_pour_post().
cree_instance()
Objet_U * Zone_VEF::cree_instance () static
Definition at line 32 of file Zone_VEF.cpp.
creer_faces_virtuelles_non_std()
void Zone_VEF::creer_faces_virtuelles_non_std () private
creation de l'espace distant pour les faces virtuelles;
creation du tableau des faces virtuelles de bord
Definition at line 558 of file Zone_VEF.cpp.
{
  ind_faces_virt_non_std_.resize_array(314);
  ind_faces_virt_non_std_ = -999;
#if 0
  int i,j,id_joint;
  int nb_faces_front=premiere_face_int();
  int nb_faces_virt=zone().ind_faces_virt_bord().size_array();
// Constitution du tableau des indices de faces
// virtuelles non standards.
  int prem_face_std=premiere_face_std();
  IntVect ind_faces_nstd(nb_faces_non_std());
  IntVect ind_faces(nb_faces_);
  const VectEsp_Virt& vev_id_f = ind_faces.renvoi_espaces_virtuels();
  for(j=0; j<nb_faces_; j++)
    ind_faces[j]=j;
  for(j=premiere_face_int(); j<prem_face_std; j++)
    ind_faces_nstd[j]=j;
  for(id_joint=0; id_joint<nb_joints(); id_joint++)
    {
      Joint& le_joint = joint(id_joint);
      int PEvoisin=le_joint.PEvoisin();
      const ArrOfInt& edf=le_joint.esp_dist_faces();
      int nbfd = edf.size_array();
      ind_faces.ajoute_espace_distant(PEvoisin,edf);
      ArrOfInt tempo(nbfd);
      int cpt=0;
      for(i=0; i<nbfd; i++)
        if((edf[i]<prem_face_std)&&(edf[i]>=nb_faces_front))
          tempo[cpt++]=edf[i];
      tempo.resize_array(cpt);
      ind_faces_nstd.ajoute_espace_distant(PEvoisin,tempo);
    }
  ind_faces.echange_espace_virtuel();
  ind_faces_nstd.echange_espace_virtuel();
  const VectEsp_Virt& vev_id_fnstd =
    ind_faces_nstd.renvoi_espaces_virtuels();
  ind_faces_virt_non_std_.resize_array(nb_faces_virt);
  for(id_joint=0; id_joint<nb_joints(); id_joint++)
    {
      int deb=vev_id_f[id_joint].deb();
      int fin=deb+vev_id_f[id_joint].nb();
      int deb_b=vev_id_fnstd[id_joint].deb();
      int fin_b=deb_b+vev_id_fnstd[id_joint].nb();
      for(i=deb_b; i<fin_b; i++)
        {
          for(j=deb; j<fin; j++)
            if(ind_faces[j]==ind_faces_nstd[i])
              break;
          assert(j<fin);
          ind_faces_virt_non_std_[j-nb_faces_]=i;
        }
    }
#endif
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Joint::esp_dist_faces(), Zone::ind_faces_virt_bord(), ind_faces_virt_non_std_, Zone_VF::joint(), nb_faces_non_std(), Zone_VF::nb_joints(), Joint::PEvoisin(), Zone_VF::premiere_face_int(), premiere_face_std(), TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), and Zone_dis_base::zone().
Referenced by remplir_elem_faces().
discretiser()
void Zone_VEF::discretiser () override virtual
Genere les faces
construits les frontieres.
< Detache la structure parallele
< Extremas du domaine et volumes
< Aires des bords
< Nombre elements et sommets
Reimplemented from Zone_VF.
Definition at line 266 of file Zone_VEF.cpp.
{
  Zone& zone_geom=zone();
  typer_elem(zone_geom);
  Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  Zone_VF::discretiser();
// Correction du tableau face_voisins:
// A l'issue de Zone_VF::discretiser(), les elements voisins 0 et 1 d'une
// face sont les memes sur tous les processeurs qui possedent la face.
// Si la face est virtuelle et qu'un des deux elements voisins n'est
// pas connu (il n'est pas dans l'epaisseur du joint), l'element voisin
// vaut -1. Cela peut etre un voisin 0 ou un voisin 1.
// On corrige les faces virtuelles pour que, si un element voisin n'est
// pas connu, alors il est voisin1. Le voisin0 est donc toujours valide.
  {
    IntTab& face_vois = face_voisins();
    const int debut = nb_faces();
    const int fin   = nb_faces_tot();
    for (int i = debut; i < fin; i++)
      {
        if (face_voisins(i, 0) == -1)
          {
            face_vois(i, 0) = face_vois(i, 1);
            face_vois(i, 1) = -1;
          }
      }
  }
// Verification de la coherence entre l'element geometrique et
// l'elemnt de discretisation
  if (sub_type(Tri_VEF,type_elem_.valeur()))
    {
      if (!sub_type(Triangle,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " <<
               elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Triangle est compatible avec la discretisation VEF en dimension 2" << finl;
          Cerr << " Il faut trianguler le domaine lorsqu'on utilise le mailleur interne" ;
          Cerr << " en utilisant l'instruction: Trianguler nom_dom" <<
               finl;
          exit();
        }
    }
  else if (sub_type(Tetra_VEF,type_elem_.valeur()))
    {
      if (!sub_type(Tetraedre,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " <<
               elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Tetraedre est compatible avec la discretisation VEF en dimension 3" << finl;
          Cerr << " Il faut tetraedriser le domaine lorsqu'on utilise le mailleur interne";
          Cerr << " en utilisant l'instruction: Tetraedriser nom_dom" <<
               finl;
          exit();
        }
    }
  else if (sub_type(Quadri_VEF,type_elem_.valeur()))
    {
      if (!sub_type(Quadrangle_VEF,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  else if (sub_type(Hexa_VEF,type_elem_.valeur()))
    {
      if (!sub_type(Hexaedre_VEF,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  int num_face;
// On remplit le tableau face_normales_;
// Attention : le tableau face_voisins n'est pas exactement un
// tableau distribue. Une face n'a pas ses deux voisins dans le
// meme ordre sur tous les processeurs qui possedent la face.
// Donc la normale a la face peut changer de direction d'un
// processeur a l'autre, y compris pour les faces de joint.
  {
    const int n = nb_faces();
    face_normales_.resize(n, dimension);
    creer_tableau_faces(face_normales_, Array_base::NOCOPY_NOINIT);
    const IntTab& face_som = face_sommets();
    const IntTab& face_vois = face_voisins();
    const IntTab& elem_face = elem_faces();
    const int n_tot = nb_faces_tot();
    for (num_face = 0; num_face < n_tot; num_face++)
      {
        type_elem_.normale(num_face,
                           face_normales_,
                           face_som, face_vois, elem_face, zone_geom);
      }
  }
// Calcul de facette_normales_
  type_elem_.creer_facette_normales(zone_geom,
                                    facette_normales(),
                                    rang_elem_non_std());
  calculer_volumes_entrelaces();
  Cerr << "Informations of the Zone VEF of the domain " << zone().domaine().le_nom() << " : " << finl;
  calculer_h_carre();
// Calcul des porosites
  Zone_VF::calculer_porosites();
}
References calculer_h_carre(), Zone_VF::calculer_porosites(), calculer_volumes_entrelaces(), Cerr, Elem_VEF::creer_facette_normales(), Zone_VF::creer_tableau_faces(), Objet_U::dimension, Zone_VF::discretiser(), Zone::domaine(), Zone_VF::elem_faces(), Process::exit(), face_normales_, Zone_VF::face_sommets(), face_vois(), Zone_VF::face_voisins(), facette_normales(), finl, Domaine::le_nom(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Array_base::NOCOPY_NOINIT, Elem_VEF::normale(), Objet_U::que_suis_je(), rang_elem_non_std(), TRUSTTab< _TYPE_ >::resize(), sub_type, Zone::type_elem(), type_elem_, typer_elem(), Deriv_Elem_geom_base::valeur(), Deriv_Elem_VEF_base::valeur(), and Zone_dis_base::zone().
Referenced by Zone_VEF_PreP1b::discretiser().
duplique()
int Zone_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 32 of file Zone_VEF.cpp.
ecrit()
Sortie & Zone_VEF::ecrit (Sortie & os) const private
Definition at line 38 of file Zone_VEF.cpp.
{
  Zone_VF::printOn(os);
  os << "____ h_carre "<<finl;
  os << h_carre << finl;
  os << "____ type_elem_ "<<finl;
  os << type_elem_ << finl;
  os << "____ nb_elem_std_ "<<finl;
  os << nb_elem_std_ << finl;
  os << "____ volumes_entrelaces_ "<<finl;
  volumes_entrelaces_.ecrit(os);
  os << "____ face_normales_ "<<finl;
  face_normales_.ecrit(os);
  os << "____ facette_normales_ "<<finl;
  facette_normales_.ecrit(os);
  os << "____ nb_faces_std_ "<<finl;
  os << nb_faces_std_ << finl;
  os << "____ rang_elem_non_std_ "<<finl;
  rang_elem_non_std_.ecrit(os);
  return os;
}
References TRUSTVect< _TYPE_ >::ecrit(), TRUSTTab< _TYPE_ >::ecrit(), face_normales_, facette_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, Zone_VF::printOn(), rang_elem_non_std_, type_elem_, and Zone_VF::volumes_entrelaces_.
face_normales() [1/3]
DoubleTab & Zone_VEF::face_normales () inline
Definition at line 87 of file Zone_VEF.h.
  {
    return face_normales_;
  };
References face_normales_.
face_normales() [2/3]
const DoubleTab & Zone_VEF::face_normales () const inline
Definition at line 91 of file Zone_VEF.h.
  {
    return face_normales_;
  };
References face_normales_.
face_normales() [3/3]
double Zone_VEF::face_normales (int face, int comp) const inline override virtual
Implements Zone_VF.
Definition at line 137 of file Zone_VEF.h.
{
  return face_normales_(face,comp);
}
References face_normales_.
Referenced by Op_Dift_Stab_VEF_Face::aij_extradiag(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_partie_compressible(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Masse_VEF_P1NC::appliquer_impl(), Champ_front_contact_VEF::calcul_coeff_amort(), Op_Dift_standard_VEF_Face::calcul_divergence(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_Stab_VEF_Face::calculer_coefficients(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), calculer_gradientP1NC(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Op_Dift_Stab_VEF_Face::calculer_gradients(), Traitement_particulier_NS_Brech_VEF::calculer_terme_destruction_K(), Champ_P1NC::compo_normale_sortante(), Champ_Q1NC::compo_normale_sortante(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), contribuer_matrice_NeumannP0P1(), contribuer_matrice_NeumannP0Pa(), contribuer_matrice_NeumannP1P1(), contribuer_matrice_NeumannP1Pa(), contribuer_matrice_NeumannPaPa(), contribuer_matrice_SymetrieP1P1(), contribuer_matrice_SymetrieP1Pa(), contribuer_matrice_SymetriePaPa(), contribuer_matriceP0P1(), contribuer_matriceP0Pa(), contribuer_matriceP1P1(), contribuer_matriceP1Pa(), contribuer_matricePaPa(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), distance_2D(), distance_3D(), distance_face(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Q1NC::gradient(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Zone_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Champ_front_tangentiel_VEF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), norm_2D_vit1(), norm_2D_vit1_k(), norm_2D_vit1_lp(), norm_2D_vit2(), norm_2D_vit2_k(), norm_3D_vit1(), norm_3D_vit1_lp(), norm_3D_vit2(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Echange_contact_Correlation_VEF::pdt_scal(), Echange_contact_Correlation_VEF::pdt_scalSqrt(), Op_Conv_EF_VEF_P1NC_Stab::reinit_conv_pour_Cl(), Assembleur_P_VEF::remplir(), Op_Conv_EF_VEF_P1NC_Stab::remplir_fluent(), Op_Conv_Muscl_New_VEF_Face::remplir_fluent(), Op_Conv_VEF_Face::remplir_fluent(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), Echange_contact_Correlation_VEF::surfacesVEF(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), update_matrice_NeumannP0P1(), update_matrice_NeumannP0Pa(), update_matrice_NeumannP1P1(), update_matrice_NeumannP1Pa(), update_matrice_NeumannPaPa(), update_matrice_SymetrieP1P1(), update_matrice_SymetrieP1Pa(), update_matrice_SymetriePaPa(), update_matriceP0P1(), update_matriceP0Pa(), update_matriceP1P1(), update_matriceP1Pa(), update_matricePaPa(), Op_Curl_VEFP1B::vecteur_normal(), Op_Diff_RotRot::vecteur_normal(), Op_Rot_VEFP1B::vecteur_normal(), visc_Q1(), Op_Diff_VEF_base::viscA(), and viscA_Q1().
facette_normales() [1/2]
DoubleTab & Zone_VEF::facette_normales () inline
Definition at line 144 of file Zone_VEF.h.
{
  return facette_normales_;
}
References facette_normales_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), discretiser(), and Op_Conv_VEF_Face::remplir_fluent().
facette_normales() [2/2]
const DoubleTab & Zone_VEF::facette_normales () const inline
Definition at line 151 of file Zone_VEF.h.
{
  return facette_normales_;
}
References facette_normales_.
get_info()
const Type_info * Zone_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_VF.
Definition at line 32 of file Zone_VEF.cpp.
ind_faces_virt_non_std()
const ArrOfInt & Zone_VEF::ind_faces_virt_non_std () const inline
Definition at line 230 of file Zone_VEF.h.
{
  return ind_faces_virt_non_std_;
}
References ind_faces_virt_non_std_.
info()
const Type_info * Zone_VEF::info () static
Definition at line 32 of file Zone_VEF.cpp.
modifier_pour_Cl()
void Zone_VEF::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Reimplemented from Zone_VF.
Definition at line 458 of file Zone_VEF.cpp.
{
  Journal() << "Zone_VEF::Modifier_pour_Cl" << finl;
  int nb_cond_lim=conds_lim.size();
  int num_cond_lim=0;
  for (; num_cond_lim<nb_cond_lim; num_cond_lim++)
    {
// for cl
      const Cond_lim_base& cl = conds_lim[num_cond_lim].valeur();
      if (sub_type(Periodique, cl))
        {
// if Perio
          const Periodique& la_cl_period = ref_cast(Periodique,cl);
          int nb_faces_elem = zone().nb_faces_elem();
          const Front_VF& la_front_dis = ref_cast(Front_VF,cl.frontiere_dis());
          int ndeb = 0;
          int nfin = la_front_dis.nb_faces_tot();
#ifndef NDEBUG
          int num_premiere_face = la_front_dis.num_premiere_face();
          int num_derniere_face = num_premiere_face+nfin;
#endif
          int nbr_faces_bord = la_front_dis.nb_faces();
          assert((nb_faces()==0)||(ndeb<nb_faces()));
          assert(nfin>=ndeb);
          int elem1,elem2,k;
          int face;
// Modification des tableaux face_voisins_ , face_normales_ , volumes_entrelaces_
// On change l'orientation de certaines normales
// de sorte que les normales aux faces de periodicite soient orientees
// de face_voisins(la_face_en_question,0) vers face_voisins(la_face_en_question,1)
// comme le sont les faces internes d'ailleurs
          DoubleVect C1C2(dimension);
          double vol,psc=0;
          for (int ind_face=ndeb; ind_face<nfin; ind_face++)
            {
// for ind_face
              face = la_front_dis.num_face(ind_face);
              if  ( (face_voisins_(face,0) == -1) || (face_voisins_(face,1) == -1) )
                {
                  int faassociee = la_front_dis.num_face(la_cl_period.face_associee(ind_face));
                  if (ind_face<nbr_faces_bord)
                    {
                      assert(faassociee>=num_premiere_face);
                      assert(faassociee<num_derniere_face);
                    }
                  elem1 = face_voisins_(face,0);
                  elem2 = face_voisins_(faassociee,0);
                  vol = (volumes(elem1) + volumes(elem2))/nb_faces_elem;
                  volumes_entrelaces_[face] = vol;
                  volumes_entrelaces_[faassociee] = vol;
                  face_voisins_(face,1) = elem2;
                  face_voisins_(faassociee,0) = elem1;
                  face_voisins_(faassociee,1) = elem2;
                  psc = 0;
                  for (k=0; k<dimension; k++)
                    {
                      C1C2[k] = xv_(face,k) - xp_(face_voisins_(face,0),k);
                      psc += face_normales_(face,k)*C1C2[k];
                    }
                  if (psc < 0)
                    for (k=0; k<dimension; k++)
                      face_normales_(face,k) *= -1;
                  for (k=0; k<dimension; k++)
                    face_normales_(faassociee,k) = face_normales_(face,k);
                }
            }
        }
    }
// PQ : 10/10/05 : les faces periodiques etant a double contribution
// l'appel a marquer_faces_double_contrib s'effectue dans cette methode
// afin de pouvoir beneficier de conds_lim.
  Zone_VF::marquer_faces_double_contrib(conds_lim);
// Construction du tableau num_fac_loc_
  construire_num_fac_loc();
}
References Zone_VF::construire_num_fac_loc(), Objet_U::dimension, Periodique::face_associee(), face_normales_, Zone_VF::face_voisins_, finl, Cond_lim_base::frontiere_dis(), Process::Journal(), Zone_VF::marquer_faces_double_contrib(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), ref_cast, vect_impl::size(), sub_type, Zone_VF::volumes(), Zone_VF::volumes_entrelaces_, Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by Zone_VEF_PreP1b::modifier_pour_Cl().
nb_elem_Cl()
int Zone_VEF::nb_elem_Cl () const inline
Definition at line 189 of file Zone_VEF.h.
{
  return nb_elem() - nb_elem_std_;
}
References Zone_dis_base::nb_elem(), and nb_elem_std_.
nb_elem_std()
int Zone_VEF::nb_elem_std () const inline
Definition at line 183 of file Zone_VEF.h.
{
  return nb_elem_std_;
}
References nb_elem_std_.
nb_faces_joint()
int Zone_VEF::nb_faces_joint () const inline
Definition at line 170 of file Zone_VEF.h.
{
  return 0;
// return nb_faces_joint_;    A FAIRE
}
Referenced by EDO_Pression_th_VEF::calculer_grad().
nb_faces_non_std()
int Zone_VEF::nb_faces_non_std () const inline
Definition at line 201 of file Zone_VEF.h.
{
  return nb_faces() - nb_faces_std_;
}
References Zone_VF::nb_faces(), and nb_faces_std_.
Referenced by Zone_Cl_VEF::associer(), creer_faces_virtuelles_non_std(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), and Zone_Cl_VEFP1B::remplir_volumes_entrelaces_Cl().
nb_faces_std()
int Zone_VEF::nb_faces_std () const inline
Definition at line 177 of file Zone_VEF.h.
{
  return nb_faces_std_;
}
References nb_faces_std_.
oriente_normale()
int Zone_VEF::oriente_normale (int face_opp, int elem2) const inline
Definition at line 213 of file Zone_VEF.h.
{
  if(face_voisins(face_opp,0)==elem2)
    return 1;
  else return -1;
}
References Zone_VF::face_voisins().
Referenced by Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_Generique_Tparoi_VEF::get_champ(), Op_Grad_VEF_P1B_Face::impr(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Champ_P1NC::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Op_Curl_VEFP1B::vecteur_normal(), Op_Diff_RotRot::vecteur_normal(), and Op_Rot_VEFP1B::vecteur_normal().
premiere_face_std()
int Zone_VEF::premiere_face_std () const inline
Definition at line 195 of file Zone_VEF.h.
{
  return nb_faces() - nb_faces_std_;
}
References Zone_VF::nb_faces(), and nb_faces_std_.
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Rappel_T_VEF_Face::ajouter(), Masse_VEF_P1NC::appliquer_impl(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_stab(), EDO_Pression_th_VEF::calculer_grad(), Op_Conv_VEF_base::calculer_pour_post(), creer_faces_virtuelles_non_std(), EOS_Tools_VEF::divu_discvit(), and Champ_val_tot_sur_vol_VEF::eval_contrib_loc().
printOn()
Sortie & Zone_VEF::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
< PQ : 12/10/05 : a voir ce qu'il faut faire ici ???
Reimplemented from Zone_VF.
Definition at line 63 of file Zone_VEF.cpp.
{
  Zone_VF::printOn(os);
  os << h_carre << finl;
  os << type_elem_ << finl;
  os << nb_elem_std_ << finl;
  os << volumes_entrelaces_ << finl;
  os << face_normales_ << finl;
  os << facette_normales_ << finl;
  os << xp_ << finl;
  os << xv_ << finl;
  os << nb_faces_std_ << finl;
  os << rang_elem_non_std_ << finl;
  return os;
}
References face_normales_, facette_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, Zone_VF::printOn(), rang_elem_non_std_, type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Zone_VEF_PreP1b::printOn().
rang_elem_non_std() [1/2]
IntVect & Zone_VEF::rang_elem_non_std () inline
Definition at line 157 of file Zone_VEF.h.
{
  return rang_elem_non_std_;
}
References rang_elem_non_std_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Zone_Cl_VEF::associer(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), calculer_coef_som(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_data_pour_dirichlet(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), discretiser(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), and Zone_Cl_VEF::remplir_volumes_entrelaces_Cl().
rang_elem_non_std() [2/2]
const IntVect & Zone_VEF::rang_elem_non_std () const inline
Definition at line 163 of file Zone_VEF.h.
{
  return rang_elem_non_std_;
}
References rang_elem_non_std_.
readOn()
Entree & Zone_VEF::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_VF.
Definition at line 83 of file Zone_VEF.cpp.
{
  Zone_VF::readOn(is);
  is >> h_carre;
  is >> type_elem_;
  is >> nb_elem_std_ ;
  is >> volumes_entrelaces_ ;
  is >> face_normales_ ;
  is >> facette_normales_ ;
  is >> xp_;
  is >> xv_;
  is >> nb_faces_std_ ;
  is >> rang_elem_non_std_ ;
  return is;
}
References face_normales_, facette_normales_, h_carre, nb_elem_std_, nb_faces_std_, rang_elem_non_std_, Zone_VF::readOn(), type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Zone_VEF_PreP1b::readOn().
remplir_elem_faces()
void Zone_VEF::remplir_elem_faces () override private virtual
Implements Zone_VF.
Definition at line 453 of file Zone_VEF.cpp.
{
  creer_faces_virtuelles_non_std();
}
References creer_faces_virtuelles_non_std().
reordonner()
void Zone_VEF::reordonner (Faces & les_faces) override virtual
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
< renum_items_communs rempli ?
< ancien indice local
Reimplemented from Zone_VF.
Definition at line 111 of file Zone_VEF.cpp.
{
  if (Process::je_suis_maitre())
    Cerr << "Zone_VEF::reordonner les_faces " << finl;
// Construction de rang_elem_non_std_ :
// C'est un vecteur indexe par les elements du domaine.
// size() = nb_elem()
// size_tot() = nb_elem_tot()
// Valeurs dans le tableau :
// rang_elem_non_std_[i] = -1 si l'element i est standard,
// sinon
// rang_elem_non_std_[i] = j, ou j est l'indice de l'element dans
// les tableaux indexes par les elements non standards (par exemple
// le tableau Zone_Cl_VEF::type_elem_Cl_).
// Un element est non standard s'il est voisin d'une face frontiere.
  {
    const int nb_faces_front = zone().nb_faces_frontiere();
    zone().creer_tableau_elements(rang_elem_non_std_, ArrOfInt::NOCOPY_NOINIT);
    rang_elem_non_std_ = -1;
// D'abord on marque les elements non standards avec rang_elem_non_std_[i] = 0
    for (int i_face = 0; i_face < nb_faces_front; i_face++)
      {
        const int elem = les_faces.voisin(i_face, 0);
        rang_elem_non_std_[elem] = 0;
      }
    rang_elem_non_std_.echange_espace_virtuel();
// On construit le md_vector des elements non standards, mais il n'est pas utilise.
// L'important, c'est que rang_elem_non_std_ soit rempli correctement pour etre
// utilise par creer_md_vect_renum() dans Zone_Cl_VEF::associer()
    MD_Vector md_vect_elems_non_std;
    MD_Vector_tools::creer_md_vect_renum_auto(rang_elem_non_std_, md_vect_elems_non_std);
  }
// Construction du tableau de renumerotation des faces. Ce tableau,
// une fois trie dans l'ordre croissant donne l'ordre des faces dans
// la zone_VF. La cle de tri est construite de sorte a pouvoir retrouver
// l'indice de la face a partir de la cle par la formule :
// indice_face = cle % nb_faces
  const int nbr_faces = les_faces.nb_faces();
  ArrOfInt sort_key(nbr_faces);
  {
    nb_faces_std_ =0;
    const int nb_faces_front = zone().nb_faces_frontiere();
// Attention : face_voisins_ n'est pas encore initialise, il
// faut passer par les_faces.voisins() :
    const IntTab& facevoisins = les_faces.voisins();
// On place en premier les faces de bord:
    int i_face;
    for (i_face = 0; i_face < nbr_faces; i_face++)
      {
        int key = -1;
        if (i_face < nb_faces_front)
          {
// Si la face est au bord, elle doit etre placee au debut
// (en fait elle ne doit pas etre renumerotee)
            key = i_face;
          }
        else
          {
            const int elem0 = facevoisins(i_face, 0);
            const int elem1 = facevoisins(i_face, 1);
// Ces faces ont toujours deux voisins.
            assert(elem0 >= 0 && elem1 >= 0);
            if (rang_elem_non_std_[elem0] >= 0 || rang_elem_non_std_[elem1] >= 0)
              {
// Si la face est voisine d'un element non standard, elle
// doit etre classee juste apres les faces de bord:
                key = i_face;
              }
            else
              {
// Face standard : a la fin du tableau
                key = i_face + nbr_faces;
                nb_faces_std_++;
              }
          }
        sort_key[i_face] = key;
      }
    sort_key.ordonne_array();
// On transforme a nouveau la cle en numero de face:
    for (i_face = 0; i_face < nbr_faces; i_face++)
      {
        const int key = sort_key[i_face] % nbr_faces;
        sort_key[i_face] = key;
      }
  }
// On reordonne les faces:
  {
    IntTab& faces_sommets = les_faces.les_sommets();
    IntTab old_tab(faces_sommets);
    const int nb_som_faces = faces_sommets.line_size();
    for (int i = 0; i < nbr_faces; i++)
      {
        const int old_i = sort_key[i];
        for (int j = 0; j < nb_som_faces; j++)
          faces_sommets(i, j) = old_tab(old_i, j);
      }
  }
  {
    IntTab& faces_voisins = les_faces.voisins();
    IntTab old_tab(faces_voisins);
    for (int i = 0; i < nbr_faces; i++)
      {
        const int old_i = sort_key[i];
        faces_voisins(i, 0) = old_tab(old_i, 0);
        faces_voisins(i, 1) = old_tab(old_i, 1);
      }
  }
// Calcul de la table inversee: reverse_index[ancien_numero] = nouveau numero
  ArrOfInt reverse_index(nbr_faces);
  {
    for (int i = 0; i < nbr_faces; i++)
      {
        const int j = sort_key[i];
        reverse_index[j] = i;
      }
  }
// Renumerotation de elem_faces:
  {
// Nombre d'indices de faces dans le tableau
    const int nb_items = elem_faces_.size();
    ArrOfInt& array = elem_faces_;
    for (int i = 0; i < nb_items; i++)
      {
        const int old = array[i];
        array[i] = reverse_index[old];
      }
  }
// Mise a jour des indices des faces de joint:
  {
    Joints&      joints    = zone().faces_joint();
    const int nbr_joints = joints.size();
    for (int i_joint = 0; i_joint < nbr_joints; i_joint++)
      {
        Joint&     un_joint         = joints[i_joint];
        ArrOfInt& indices_faces = un_joint.set_joint_item(Joint::FACE).set_items_communs();
        const int nbr_indfaces    = indices_faces.size_array();
        assert(nbr_indfaces == un_joint.nb_faces()); //!< renum_items_communs rempli ?
        for (int i = 0; i < nbr_indfaces; i++)
          {
            const int old = indices_faces[i]; //!< ancien indice local
            indices_faces[i] = reverse_index[old];
          }
// Les faces de joint ne sont plus consecutives dans le
// tableau: num_premiere_face n'a plus ne sens
        un_joint.fixer_num_premiere_face(-1);
      }
  }
}
References Cerr, MD_Vector_tools::creer_md_vect_renum_auto(), Zone::creer_tableau_elements(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces_, Joint::FACE, Zone::faces_joint(), finl, Frontiere::fixer_num_premiere_face(), Process::je_suis_maitre(), Faces::les_sommets(), TRUSTVect< _TYPE_ >::line_size(), Faces::nb_faces(), Frontiere::nb_faces(), Zone::nb_faces_frontiere(), nb_faces_std_, Array_base::NOCOPY_NOINIT, TRUSTArray< _TYPE_ >::ordonne_array(), rang_elem_non_std_, Joint_Items::set_items_communs(), Joint::set_joint_item(), TRUSTVect< _TYPE_ >::size(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), Faces::voisin(), Faces::voisins(), and Zone_dis_base::zone().
self_cast() [1/2]
const Zone_VEF & Zone_VEF::self_cast (const Objet_U & r) static
Definition at line 32 of file Zone_VEF.cpp.
self_cast() [2/2]
Zone_VEF & Zone_VEF::self_cast (Objet_U & r) static
Definition at line 32 of file Zone_VEF.cpp.
swap()
void Zone_VEF::swap (int fac1, int fac2, int nb_som_faces)
Definition at line 99 of file Zone_VEF.cpp.
{
}
taille_memoire()
unsigned Zone_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 32 of file Zone_VEF.cpp.
type_elem()
const Elem_VEF & Zone_VEF::type_elem () const inline
Definition at line 130 of file Zone_VEF.h.
{
  return type_elem_;
}
References type_elem_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v1(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion_v2(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_Muscl_New_VEF_Face::ajouter_diffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_operateur_centre(), Zone_Cl_VEF::associer(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), VEF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ_fonc_don(), Op_Conv_Muscl_New_VEF_Face::modifier_flux_operateur_centre(), Op_Conv_VEF_Face::remplir_fluent(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Zone_Cl_VEF::remplir_type_elem_Cl(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), vecteur_face_facette(), VEF_1D::vitesse(), and VEF_discretisation::vorticite().
typer_elem()
void Zone_VEF::typer_elem (Zone & zone_geom) override virtual
Reimplemented from Zone_VF.
Definition at line 541 of file Zone_VEF.cpp.
{
  const Elem_geom_base& type_elem_geom = zone_geom.type_elem().valeur();
  if (sub_type(Rectangle,type_elem_geom))
    {
      zone_geom.typer("Quadrangle");
    }
  else if (sub_type(Hexaedre,type_elem_geom))
    zone_geom.typer("Hexaedre_VEF");
  const Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  type_elem_.typer(elem_geom.que_suis_je());
}
References Objet_U::que_suis_je(), sub_type, Zone::type_elem(), type_elem_, Zone::typer(), Elem_VEF::typer(), and Deriv_Elem_geom_base::valeur().
Referenced by discretiser().
vecteur_face_facette()
DoubleTab & Zone_VEF::vecteur_face_facette ()
Definition at line 621 of file Zone_VEF.cpp.
{
// On construit si de taille nul
// ou si le maillage est deformable
  if (vecteur_face_facette_.size()==0 || zone().domaine().deformable())
    {
// Taille 8*n*4*3*2=192n
      const int nfa7 = type_elem().nb_facette();
      const int nb_poly_tot = nb_elem_tot();
      vecteur_face_facette_.resize(nb_poly_tot,nfa7,dimension,2);
      const IntTab& KEL=type_elem().valeur().KEL();
      const IntTab& les_Polys = zone().les_elems();
      const DoubleTab& coord =  zone().domaine().coord_sommets();
      const DoubleTab& xg = xp();
// const int nb_som_facette = zone().type_elem().nb_som_face();
      int nb_som_facette=dimension;
      int num1,num2;
      for (int poly=0; poly<nb_poly_tot; poly++)
        {
// Boucle sur les facettes du polyedre non standard:
          for (int fa7=0; fa7<nfa7; fa7++)
            {
              num1 = elem_faces(poly,KEL(0,fa7));
              num2 = elem_faces(poly,KEL(1,fa7));
// Calcul des rx0 et rx1 :
              for (int i=0; i<dimension; i++)
                {
// Calcul de la ieme coordonnee du centre de la fa7
                  double coord_centre_fa7 = xg(poly,i);
                  for (int num_som_fa7=0; num_som_fa7<nb_som_facette-1; num_som_fa7++)
                    {
                      int isom_loc = KEL(num_som_fa7+2,fa7);
                      int isom_glob = les_Polys(poly,isom_loc);
                      coord_centre_fa7 += coord(isom_glob,i);
                    }
                  coord_centre_fa7 /= nb_som_facette;
// Fin calcul de la ieme coordonnee du centre de la fa7
// Calcul de la ieme coordonnee du centre des faces num1 et num2
                  double coord_centre_num1 = 0;
                  double coord_centre_num2 = 0;
                  for (int num_som_face=0; num_som_face<nb_som_facette; num_som_face++)
                    {
                      int s1 = face_sommets(num1,num_som_face);
                      int s2 = face_sommets(num2,num_som_face);
                      coord_centre_num1 += coord(s1,i);
                      coord_centre_num2 += coord(s2,i);
                    }
                  coord_centre_num1 /= nb_som_facette;
                  coord_centre_num2 /= nb_som_facette;
// Fin de Calcul de la ieme coordonnee du centre des faces num1 et num2
                  vecteur_face_facette_(poly,fa7,i,0) = coord_centre_fa7 - coord_centre_num1;
                  vecteur_face_facette_(poly,fa7,i,1) = coord_centre_fa7 - coord_centre_num2;
                }
// Fin de Calcul des rx0 et rx1
            }
        }
    }
  return vecteur_face_facette_;
}
References Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), Elem_VEF_base::KEL(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Elem_VEF::nb_facette(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), type_elem(), Deriv_Elem_VEF_base::valeur(), vecteur_face_facette_, Zone_VF::xp(), and Zone_dis_base::zone().
Member Data Documentation
face_normales_
DoubleTab Zone_VEF::face_normales_ private
normales aux faces
Definition at line 110 of file Zone_VEF.h.
Referenced by discretiser(), ecrit(), face_normales(), modifier_pour_Cl(), printOn(), and readOn().
facette_normales_
DoubleTab Zone_VEF::facette_normales_ private
normales aux faces des volumes entrelaces
Definition at line 111 of file Zone_VEF.h.
Referenced by ecrit(), facette_normales(), printOn(), and readOn().
h_carre
double Zone_VEF::h_carre private
carre du pas du maillage
Definition at line 107 of file Zone_VEF.h.
Referenced by calculer_h_carre(), carre_pas_du_maillage(), ecrit(), printOn(), and readOn().
h_carre_
DoubleVect Zone_VEF::h_carre_ private
carre du pas d'une maille
Definition at line 108 of file Zone_VEF.h.
Referenced by calculer_h_carre(), and carre_pas_maille().
ind_faces_virt_non_std_
ArrOfInt Zone_VEF::ind_faces_virt_non_std_ private
contient les indices des faces virtuelles non standard
Definition at line 119 of file Zone_VEF.h.
Referenced by creer_faces_virtuelles_non_std(), and ind_faces_virt_non_std().
info_obj
const Type_info Zone_VEF::info_obj static
Definition at line 64 of file Zone_VEF.h.
nb_elem_std_
int Zone_VEF::nb_elem_std_ private
nombre d'elements standard
Definition at line 114 of file Zone_VEF.h.
Referenced by ecrit(), nb_elem_Cl(), nb_elem_std(), printOn(), and readOn().
nb_faces_std_
int Zone_VEF::nb_faces_std_ private
nombre de faces standard
Definition at line 113 of file Zone_VEF.h.
Referenced by ecrit(), nb_faces_non_std(), nb_faces_std(), premiere_face_std(), printOn(), readOn(), and reordonner().
orientation_
IntVect Zone_VEF::orientation_ private
Definition at line 123 of file Zone_VEF.h.
rang_elem_non_std_
IntVect Zone_VEF::rang_elem_non_std_ private
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
Definition at line 115 of file Zone_VEF.h.
Referenced by ecrit(), printOn(), rang_elem_non_std(), readOn(), and reordonner().
type_elem_
Elem_VEF Zone_VEF::type_elem_ private
type de l'element de discretisation
Definition at line 109 of file Zone_VEF.h.
Referenced by discretiser(), ecrit(), printOn(), readOn(), type_elem(), and typer_elem().
vecteur_face_facette_
DoubleTab Zone_VEF::vecteur_face_facette_ private
vecteur centre face->centre facette
Definition at line 112 of file Zone_VEF.h.
Referenced by vecteur_face_facette().
The documentation for this class was generated from the following files:
src/VEF/Zones/Zone_VEF.h
src/VEF/Zones/Zone_VEF.cpp