TRUST: EDO_Pression_th_VDF Class Reference
EDO_Pression_th_VDF Class Reference
classe EDO_Pression_th_VDF
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VDF.
#include <EDO_Pression_th_VDF.h>
Public Member Functions
~EDO_Pression_th_VDF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EDO_Pression_th_VDF ()
const Fluide_Quasi_Compressible & le_fluide () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void completer () override
Complete l'EDO : calcule rho sur les faces.
void calculer_grad (const DoubleTab &, DoubleTab &)
double masse_totale (double P, const DoubleTab &T) override
Renvoie la valeur de la pression calculee pour conserver la masse.
void mettre_a_jour_CL (double P) override
double getM0 ()
Public Member Functions inherited from EDO_Pression_th_base
EDO_Pression_th_base ()
~EDO_Pression_th_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Quasi_Compressible &)
Associe le fluide a l'EDO.
virtual void completer ()=0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void mettre_a_jour_CL (double)=0
virtual double masse_totale (double P, const DoubleTab &T)=0
virtual double resoudre (double)=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static EDO_Pression_th_VDF & self_cast (Objet_U &)
static const EDO_Pression_th_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_base
static const Type_info * info ()
static EDO_Pression_th_base & self_cast (Objet_U &)
static const EDO_Pression_th_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone
Ref_Zone_Cl_dis la_zone_Cl
double M0
la masse totale initiale
Protected Attributes inherited from EDO_Pression_th_base
Ref_Fluide_Quasi_Compressible le_fluide_
Detailed Description
classe EDO_Pression_th_VDF
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VDF.
Definition at line 37 of file EDO_Pression_th_VDF.h.
Constructor & Destructor Documentation
~EDO_Pression_th_VDF()
EDO_Pression_th_VDF::~EDO_Pression_th_VDF () override
Definition at line 30 of file EDO_Pression_th_VDF.cpp.
EDO_Pression_th_VDF()
EDO_Pression_th_VDF::EDO_Pression_th_VDF ()
Definition at line 32 of file EDO_Pression_th_VDF.cpp.
: M0(-1.) { }
Member Function Documentation
associer_zones()
void EDO_Pression_th_VDF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) override virtual
Implements EDO_Pression_th_base.
Definition at line 43 of file EDO_Pression_th_VDF.cpp.
{
  la_zone = ref_cast(Zone_VDF,zone.valeur());
  la_zone_Cl = zone_cl;
}
References la_zone, la_zone_Cl, ref_cast, and Deriv_Zone_dis_base::valeur().
calculer_grad()
void EDO_Pression_th_VDF::calculer_grad (const DoubleTab & inco, DoubleTab & resu)
Definition at line 115 of file EDO_Pression_th_VDF.cpp.
{
  int face, n0, n1, ori;
  double coef;
  IntTab& face_voisins = la_zone->face_voisins();
  IntVect& orientation = la_zone->orientation();
  DoubleVect& porosite_surf = la_zone->porosite_face();
  DoubleTab& xp = la_zone->xp();
  DoubleVect& volume_entrelaces = la_zone->volumes_entrelaces();
// Boucle sur les faces internes
  for (face=la_zone->premiere_face_int(); face<la_zone->nb_faces(); face++)
    {
      n0 = face_voisins(face,0);
      n1 = face_voisins(face,1);
      ori = orientation(face);
      coef = volume_entrelaces(face)*porosite_surf(face);
      coef=1;
      resu(face) += coef*(inco(n1)-inco(n0))/(xp(n1,ori)- xp(n0,ori));
    }
}
References Zone_VF::face_voisins(), la_zone, Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Zone_VF::volumes_entrelaces(), and Zone_VF::xp().
Referenced by EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VDF_Gaz_Reel::resoudre().
completer()
void EDO_Pression_th_VDF::completer (void) override virtual
Complete l'EDO : calcule rho sur les faces.
Implements EDO_Pression_th_base.
Definition at line 63 of file EDO_Pression_th_VDF.cpp.
{
  const DoubleTab& tab_ICh = le_fluide_->inco_chaleur().valeurs();
  double Pth=le_fluide_->pression_th();
  M0=masse_totale(Pth,tab_ICh);
  le_fluide_->checkTraitementPth(la_zone_Cl);
}
References Fluide_Quasi_Compressible::checkTraitementPth(), Fluide_Dilatable_base::inco_chaleur(), la_zone_Cl, EDO_Pression_th_base::le_fluide_, M0, masse_totale(), Fluide_Dilatable_base::pression_th(), and Champ_Inc::valeurs().
get_info()
const Type_info * EDO_Pression_th_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VDF_Gaz_Parfait, and EDO_Pression_th_VDF_Gaz_Reel.
Definition at line 30 of file EDO_Pression_th_VDF.cpp.
getM0()
double EDO_Pression_th_VDF::getM0 () inline
Definition at line 48 of file EDO_Pression_th_VDF.h.
{ return M0; }
References M0.
info()
const Type_info * EDO_Pression_th_VDF::info () static
Definition at line 30 of file EDO_Pression_th_VDF.cpp.
le_fluide()
const Fluide_Quasi_Compressible & EDO_Pression_th_VDF::le_fluide () const inline
Definition at line 42 of file EDO_Pression_th_VDF.h.
{ return le_fluide_.valeur(); };
References EDO_Pression_th_base::le_fluide_, and Ref_Fluide_Quasi_Compressible::valeur().
masse_totale()
double EDO_Pression_th_VDF::masse_totale (double P, const DoubleTab & T) override virtual
Renvoie la valeur de la pression calculee pour conserver la masse.
Returns
Double
Signification: pression calculee
Contraintes:
Implements EDO_Pression_th_base.
Definition at line 85 of file EDO_Pression_th_VDF.cpp.
{
  int elem, nb_elem=la_zone->nb_elem();
  const DoubleVect& volumes = la_zone->volumes();
  const Loi_Etat_base& loi_ = ref_cast(Loi_Etat_base,le_fluide_->loi_etat().valeur());
  double M=0;
  if (!sub_type(Loi_Etat_Multi_GP_QC,loi_))
    {
      for (elem=0 ; elem<nb_elem ; elem++)
        {
          double v = volumes(elem);
          M += v*loi_.calculer_masse_volumique(P,T[elem]);
        }
    }
  else
    {
      const Loi_Etat_Multi_GP_QC& loi_mel_GP = ref_cast(Loi_Etat_Multi_GP_QC,loi_);
      const DoubleTab& Masse_mol_mel = loi_mel_GP.masse_molaire();
      for (elem=0 ; elem<nb_elem ; elem++)
        {
          double v = volumes(elem);
          double r = 8.3143/Masse_mol_mel(elem);
          M += v*loi_mel_GP.calculer_masse_volumique(P,T[elem],r);
        }
    }
  M=Process::mp_sum(M);
  return M;
}
References Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), la_zone, EDO_Pression_th_base::le_fluide_, Fluide_Dilatable_base::loi_etat(), Loi_Etat_Multi_GP_base::masse_molaire(), Process::mp_sum(), Zone_dis_base::nb_elem(), ref_cast, sub_type, Deriv_Loi_Etat_base::valeur(), and Zone_VF::volumes().
Referenced by completer().
mettre_a_jour_CL()
void EDO_Pression_th_VDF::mettre_a_jour_CL (double P) override virtual
Implements EDO_Pression_th_base.
Definition at line 137 of file EDO_Pression_th_VDF.cpp.
{
  for (int n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
      if (sub_type(Sortie_libre_pression_imposee_QC, la_cl.valeur()))
        {
          Sortie_libre_pression_imposee_QC& cl = ref_cast_non_const(Sortie_libre_pression_imposee_QC,la_cl.valeur());
          cl.set_Pth(P);
        }
    }
}
References la_zone, la_zone_Cl, Zone_Cl_dis::les_conditions_limites(), Zone_dis_base::nb_front_Cl(), ref_cast_non_const, Sortie_libre_pression_imposee_QC::set_Pth(), sub_type, and Deriv_Cond_lim_base::valeur().
printOn()
Sortie & EDO_Pression_th_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VDF_Gaz_Parfait, and EDO_Pression_th_VDF_Gaz_Reel.
Definition at line 34 of file EDO_Pression_th_VDF.cpp.
{
  return EDO_Pression_th_base::printOn(os);
}
References EDO_Pression_th_base::printOn().
readOn()
Entree & EDO_Pression_th_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from EDO_Pression_th_base.
Reimplemented in EDO_Pression_th_VDF_Gaz_Parfait, and EDO_Pression_th_VDF_Gaz_Reel.
Definition at line 38 of file EDO_Pression_th_VDF.cpp.
{
  return EDO_Pression_th_base::readOn(is);
}
References EDO_Pression_th_base::readOn().
self_cast() [1/2]
const EDO_Pression_th_VDF & EDO_Pression_th_VDF::self_cast (const Objet_U & r) static
Definition at line 30 of file EDO_Pression_th_VDF.cpp.
self_cast() [2/2]
EDO_Pression_th_VDF & EDO_Pression_th_VDF::self_cast (Objet_U & r) static
Definition at line 30 of file EDO_Pression_th_VDF.cpp.
Member Data Documentation
info_obj
const Type_info EDO_Pression_th_VDF::info_obj static
Definition at line 39 of file EDO_Pression_th_VDF.h.
la_zone
Ref_Zone_VDF EDO_Pression_th_VDF::la_zone protected
Definition at line 51 of file EDO_Pression_th_VDF.h.
Referenced by associer_zones(), calculer_grad(), masse_totale(), mettre_a_jour_CL(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VDF_Gaz_Reel::resoudre().
la_zone_Cl
Ref_Zone_Cl_dis EDO_Pression_th_VDF::la_zone_Cl protected
Definition at line 52 of file EDO_Pression_th_VDF.h.
Referenced by associer_zones(), completer(), mettre_a_jour_CL(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VDF_Gaz_Reel::resoudre().
M0
double EDO_Pression_th_VDF::M0 protected
la masse totale initiale
Definition at line 53 of file EDO_Pression_th_VDF.h.
Referenced by completer(), and getM0().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/EDO_Pression_th_VDF.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/EDO_Pression_th_VDF.cpp