TRUST: Partitionneur_Fichier_Decoupage Class Reference
Partitionneur_Fichier_Decoupage Class Reference
Partition d'un domaine a partir d'un fichier disque contenant, pour chaque
element, le numero du processeur auquel cet element est attache.
Le fichier doit contenir un tableau au format ArrOfInt<br>(nombre n de valeurs suivi des valeurs).
La taille du tableau doit etre egale au nombre d'elements
du domaine a decouper et chaque valeur du tableau indique
sur quel processeur cet element doit etre place.
#include <Partitionneur_Fichier_Decoupage.h>
Public Member Functions
Partitionneur_Fichier_Decoupage ()
~Partitionneur_Fichier_Decoupage ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
void associer_domaine (const Domaine &domaine) override
void initialiser (const char *filename)
void construire_partition (IntVect &elem_part, int &nb_parts_tot) const override
Lit le contenu du fichier "filename_" et stocke le resultat dans elem_part.
Public Member Functions inherited from Partitionneur_base
Partitionneur_base ()
~Partitionneur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void associer_domaine (const Domaine &domaine)=0
virtual void declarer_bords_periodiques (const Noms &noms_bords_periodiques)
virtual void construire_partition (IntVect &elem_part, int &nb_parts_tot) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Partitionneur_Fichier_Decoupage & self_cast (Objet_U &)
static const Partitionneur_Fichier_Decoupage & self_cast (const Objet_U &)
Static Public Member Functions inherited from Partitionneur_base
static const Type_info * info ()
static Partitionneur_base & self_cast (Objet_U &)
static const Partitionneur_base & self_cast (const Objet_U &)
static void corriger_elem0_sur_proc0 (IntVect &elem_part)
corrige la partition pour que l'element 0 du domaine initial
se trouve sur le premier sous-domaine de la partition.
On echange le premier sous-domaine et celui qui contient l'element 0.
static int calculer_graphe_connexions_periodiques (const Zone &zone, const Noms &liste_bords_periodiques, const Static_Int_Lists &som_elem, const int my_offset, Static_Int_Lists &graph)
Calcul d'un graphe de connectivite entre les elements lies par des faces periodiques.
Si l'element i est voisin de l'element j par une face periodique, alors il existe
k tel que graph(i,k)==j et il existe k2 tel que graph(j,k2)==i.
Parametre: zone
Signification: la zone a traiter
Parametre: liste_bords_periodiques
Signification: liste des noms des bords periodiques. ATTENTION: on suppose que les
faces des bords periodiques sont rangees selon la convention des bords periodiques.
Voir check_faces_periodiques().
Parametre: som_elem
Signification: la connectivite sommets-elements pour la zone donnee.
Parametre: graph
Signification: On y stocke le resultat.
Valeur de retour: nombre d'elements dans le graphe (egal au nombre de faces periodiques)
static int corriger_bords_avec_graphe (const Static_Int_Lists &graph_elements_perio, const Static_Int_Lists &som_elem, const Domaine &domaine, const Noms &liste_bords_perio, IntVect &elem_part)
corrige la partition elem_part pour qu'un element i se trouve sur la meme
partition elem_part[i] que tous les elements auxquels il est lie dans le graphe
(elements d'indices graph_elements_perio(i, j) pour tout j).
Parametre: graph_elements_perio
Signification: graphe calcule par la methode calculer_graphe_connexions_periodiques
Parametre: elem_part
Signification: pour chaque element, a quelle partie appartient-il.
Valeur de retour: nombre d'elements dont la partition a ete corrigee.
static void corriger_bords_avec_liste (const Domaine &dom, const Noms &liste_bords_periodiques, const int my_offset, IntVect &elem_part)
Calcul des graphes de connectivite elements periodiques et appel a
corriger_periodique_avec_graphe. (Methode a utiliser quand on ne dispose
pas encore du graphe de de connectivite, si on a le graphe sous la main,
appeler directement corriger_periodique_avec_graphe)
static int corriger_sommets_bord (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
Modifie elem_part pour assurer les proprietes suivantes :
1) Les elements possedant un sommet de bord sont associes
a un processeur possedant une face de bord adjacente a ce sommet.
2) Si un processeur possede un sommet periodique reel, il
possede forcement le renum_som_perio associe (donc un element
qui possede ce sommet et un face periodique).
Cette propriete est indispensable pour le periodique (existence
de renum_som_perio pour tous les sommets).
Pour les autres bords, cette correction est peut-etre inutile, mais
pas sur. Sans cette correction, il peut exister des sommets de bord
isoles (un processeur possede un sommet de bord mais aucune face).
Si on cherche les sommets de bord en parcourant les faces de bord,
c'est faux. Avec cette correction, cet algorithme est correct.
static int corriger_multiperiodique (const Domaine &domaine, const Noms &liste_bords_perio, const ArrOfInt &renum_som_perio, const Static_Int_Lists &som_elem, IntVect &elem_part)
applique des corrections a elem_part pour que le
multi-periodique soit correct :
Si un sommet appartient a plusieurs frontieres periodiques,
tous les elements adjacents sont rattaches au meme processeur.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Partitionneur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture des parametres du partitionneur sur disque.
Fomat attendu:
{ fichier FILENAME }
FILENAME est le nom d'un fichier existant au format ArrOfInt ascii.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Domaine ref_domaine_
Nom filename_
int corriger_partition_
Protected Attributes inherited from Partitionneur_base
Noms liste_bords_periodiques_
Detailed Description
Partition d'un domaine a partir d'un fichier disque contenant, pour chaque
element, le numero du processeur auquel cet element est attache.
Le fichier doit contenir un tableau au format ArrOfInt<br>(nombre n de valeurs suivi des valeurs).
La taille du tableau doit etre egale au nombre d'elements
du domaine a decouper et chaque valeur du tableau indique
sur quel processeur cet element doit etre place.
Definition at line 31 of file Partitionneur_Fichier_Decoupage.h.
Constructor & Destructor Documentation
Partitionneur_Fichier_Decoupage()
Partitionneur_Fichier_Decoupage::Partitionneur_Fichier_Decoupage ()
Definition at line 22 of file Partitionneur_Fichier_Decoupage.cpp.
{
  filename_ = "";
  corriger_partition_ = 0;
}
References corriger_partition_, and filename_.
~Partitionneur_Fichier_Decoupage()
Partitionneur_Fichier_Decoupage::~Partitionneur_Fichier_Decoupage ()
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
Member Function Documentation
associer_domaine()
void Partitionneur_Fichier_Decoupage::associer_domaine (const Domaine & domaine) override virtual
Implements Partitionneur_base.
Definition at line 55 of file Partitionneur_Fichier_Decoupage.cpp.
{
  ref_domaine_ = domaine;
}
References ref_domaine_.
construire_partition()
void Partitionneur_Fichier_Decoupage::construire_partition (IntVect & elem_part, int & nb_parts_tot) const override virtual
Lit le contenu du fichier "filename_" et stocke le resultat dans elem_part.
Implements Partitionneur_base.
Definition at line 69 of file Partitionneur_Fichier_Decoupage.cpp.
{
  if (! ref_domaine_.non_nul())
    {
      Cerr << "Error in Partitionneur_Fichier_Decoupage::construire_partition\n";
      Cerr << " The domain has not been associated" << finl;
      exit();
    }
  if (filename_ == "")
    {
      Cerr << "Error in Partitionneur_Fichier_Decoupage::construire_partition\n";
      Cerr << " The file name has not been initialized" << finl;
      exit();
    }
  Cerr << "Reading of splitting file : " << filename_ << finl;
  EFichier file;
  file.ouvrir(filename_);
  if (!file.good())
    {
      Cerr << "Error in Partitionneur_Fichier_Decoupage::construire_partition\n";
      Cerr << " Failed to open file " << filename_ << finl;
      exit();
    }
  file >> elem_part;
  file >> nb_parts_tot;
  file.close();
  const int sz = elem_part.size_array();
  const int nelem = ref_domaine_.valeur().zone(0).nb_elem();
  if (nelem != sz)
    {
      Cerr << "Error in Partitionneur_Fichier_Decoupage::construire_partition\n";
      Cerr << " The file contains an array of " << sz << " values.\n";
      Cerr << " The area contains " << nelem << " elements" << finl;
      exit();
    }
  if (corriger_partition_)
    {
      Cerr << " Correction of the partition." << finl;
      if (liste_bords_periodiques_.size() > 0)
        corriger_bords_avec_liste(ref_domaine_.valeur(),
                                  liste_bords_periodiques_,
                                  0,
                                  elem_part);
      corriger_elem0_sur_proc0(elem_part);
    }
}
References Cerr, Entree_Fichier_base::close(), Partitionneur_base::corriger_bords_avec_liste(), Partitionneur_base::corriger_elem0_sur_proc0(), corriger_partition_, Process::exit(), filename_, finl, Entree_Fichier_base::good(), Partitionneur_base::liste_bords_periodiques_, Zone::nb_elem(), O_U_Ptr::non_nul(), Entree_Fichier_base::ouvrir(), ref_domaine_, vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), Ref_Domaine::valeur(), and Domaine::zone().
cree_instance()
Objet_U * Partitionneur_Fichier_Decoupage::cree_instance () static
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
duplique()
int Partitionneur_Fichier_Decoupage::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
get_info()
const Type_info * Partitionneur_Fichier_Decoupage::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
info()
const Type_info * Partitionneur_Fichier_Decoupage::info () static
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
initialiser()
void Partitionneur_Fichier_Decoupage::initialiser (const char * filename)
Definition at line 60 of file Partitionneur_Fichier_Decoupage.cpp.
{
  filename_ = filename;
}
References filename_.
printOn()
Sortie & Partitionneur_Fichier_Decoupage::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Partitionneur_base.
Definition at line 42 of file Partitionneur_Fichier_Decoupage.cpp.
{
  Cerr << "Partitionneur_Metis::printOn invalid\n" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Partitionneur_Fichier_Decoupage::readOn (Entree & is) override protected virtual
Lecture des parametres du partitionneur sur disque.
Fomat attendu:
{ fichier FILENAME }
FILENAME est le nom d'un fichier existant au format ArrOfInt ascii.
Reimplemented from Partitionneur_base.
Definition at line 33 of file Partitionneur_Fichier_Decoupage.cpp.
{
  Partitionneur_base::readOn(is);
  Cerr << " filename : " << filename_ << finl;
  if (corriger_partition_ == 1)
    Cerr << " corriger_partition => partition will be corrected (periodic + elem0_on_proc0)" << finl;
  return is;
}
References Cerr, corriger_partition_, filename_, finl, and Partitionneur_base::readOn().
self_cast() [1/2]
const Partitionneur_Fichier_Decoupage & Partitionneur_Fichier_Decoupage::self_cast (const Objet_U & r) static
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
self_cast() [2/2]
Partitionneur_Fichier_Decoupage & Partitionneur_Fichier_Decoupage::self_cast (Objet_U & r) static
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
set_param()
void Partitionneur_Fichier_Decoupage::set_param (Param & param) override virtual
Implements Partitionneur_base.
Definition at line 49 of file Partitionneur_Fichier_Decoupage.cpp.
{
  param.ajouter("fichier",&filename_,Param::REQUIRED);
  param.ajouter_flag("corriger_partition",&corriger_partition_);
}
References Param::ajouter(), Param::ajouter_flag(), corriger_partition_, filename_, and Param::REQUIRED.
taille_memoire()
unsigned Partitionneur_Fichier_Decoupage::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Partitionneur_Fichier_Decoupage.cpp.
Member Data Documentation
corriger_partition_
int Partitionneur_Fichier_Decoupage::corriger_partition_ protected
Definition at line 44 of file Partitionneur_Fichier_Decoupage.h.
Referenced by construire_partition(), Partitionneur_Fichier_Decoupage(), readOn(), and set_param().
filename_
Nom Partitionneur_Fichier_Decoupage::filename_ protected
Definition at line 43 of file Partitionneur_Fichier_Decoupage.h.
Referenced by construire_partition(), initialiser(), Partitionneur_Fichier_Decoupage(), readOn(), and set_param().
info_obj
const Type_info Partitionneur_Fichier_Decoupage::info_obj static
Definition at line 33 of file Partitionneur_Fichier_Decoupage.h.
ref_domaine_
Ref_Domaine Partitionneur_Fichier_Decoupage::ref_domaine_ protected
Definition at line 42 of file Partitionneur_Fichier_Decoupage.h.
Referenced by associer_domaine(), and construire_partition().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Partitionneur_Fichier_Decoupage.h
src/Kernel/Geometrie/Decoupeur/Partitionneur_Fichier_Decoupage.cpp