TRUST: Associer Class Reference
Associer Class Reference
classe Associer
Interprete qui associe deux objets obj1 et obj2:
[DANS LE JEU DE DONNEES] Associer ob1 ob2
#include <Associer.h>
Public Member Functions
Associer ()
~Associer ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Fonction principale de l'interprete Associer:
associer deux objets.
On essaye d'associer 1 a 2 et 2 a 1, provoque une
erreur si cela echoue.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Associer & self_cast (Objet_U &)
static const Associer & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a:
Interprete::readOn(Entree&)
Ecrit l'interprete sur un flot d'entree.
Detailed Description
classe Associer
Interprete qui associe deux objets obj1 et obj2:
[DANS LE JEU DE DONNEES] Associer ob1 ob2
Definition at line 40 of file Associer.h.
Constructor & Destructor Documentation
Associer::Associer ()
Definition at line 25 of file Associer.cpp.
Associer::~Associer ()
Definition at line 25 of file Associer.cpp.
Member Function Documentation
Objet_U * Associer::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
int Associer::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
const Type_info * Associer::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
const Type_info * Associer::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
Entree & Associer::interpreter (Entree & is) [virtual]
Fonction principale de l'interprete Associer:
associer deux objets.
On essaye d'associer 1 a 2 et 2 a 1, provoque une
erreur si cela echoue.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 89 of file Associer.cpp.
References Objet_U::associer_(), Cerr, Entree::eof(), Process::exit(), finl, Interprete::objet(), and Objet_U::que_suis_je().
{
// Acquisition des parametres :
  Nom nom1, nom2;
  is >> nom1 >> nom2;
  if(is.eof())
    {
      Cerr << "Reading problem in Associer" << finl;
      exit();
    }
  Objet_U& ob1=objet(nom1);
  Objet_U& ob2=objet(nom2);
  int association12,association21;
  association12=ob1.associer_(ob2);
  association21=0;
  if (!association12)
    {
      association21=ob2.associer_(ob1);
      if(!association21)
        {
          Cerr << "It is not known associate " << ob1.que_suis_je()
               << " and " << ob2.que_suis_je()  << finl;
          exit();
        }
    }
  if (association12==2)
    {
      Cerr << finl;
      Cerr << "The medium " << ob2.que_suis_je() << " \"" << nom2
           << "\" can not be associated to the problem" << finl;
      Cerr << ob1.que_suis_je() << " \"" << nom1
           << "\" because it is already associated with another problem." << finl;
      exit();
    }
  if (association21==2)
    {
      Cerr << finl;
      Cerr << "The medium " << ob1.que_suis_je() << " \"" << nom1
           << "\" can not be associated to the problem" << finl;
      Cerr << ob2.que_suis_je() << " \"" << nom2
           << "\" because it is already associated with another problem." << finl;
      exit();
    }
  return is;
}
Sortie & Associer::printOn (Sortie & os) const [protected, virtual]
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 44 of file Associer.cpp.
{
  return Interprete::printOn(os);
}
Entree & Associer::readOn (Entree & is) [protected, virtual]
Simple appel a:
Interprete::readOn(Entree&)
Ecrit l'interprete sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 66 of file Associer.cpp.
{
  return Interprete::readOn(is);
}
Associer & Associer::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
const Associer & Associer::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
unsigned Associer::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file Associer.cpp.
Member Data Documentation
const Type_info Associer::info_obj [static]
Reimplemented from Interprete.
Definition at line 42 of file Associer.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Associer.h
src/Kernel/Framework/Associer.cpp