TRUST: Assembleur_P_CoviMAC Class Reference
Assembleur_P_CoviMAC Class Reference
#include <Assembleur_P_CoviMAC.h>
Public Member Functions
Assembleur_P_CoviMAC ()
~Assembleur_P_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
const Zone_dis_base & zone_dis_base () const
const Zone_Cl_dis_base & zone_Cl_dis_base () const
int assembler (Matrice &)
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
int modifier_secmem (DoubleTab &)
int modifier_solution (DoubleTab &)
void completer (const Equation_base &)
const Equation_base & equation () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Assembleur_P_CoviMAC & self_cast (Objet_U &)
static const Assembleur_P_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Ref_Equation_base mon_equation
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zone_Cl_CoviMAC
int has_P_ref
int stencil_done
IntVect tab1
IntVect tab2
Detailed Description
Definition at line 38 of file Assembleur_P_CoviMAC.h.
Constructor & Destructor Documentation
Assembleur_P_CoviMAC::Assembleur_P_CoviMAC ()
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
Assembleur_P_CoviMAC::~Assembleur_P_CoviMAC ()
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
Member Function Documentation
int Assembleur_P_CoviMAC::assembler (Matrice & la_matrice) [virtual]
Implements Assembleur_base.
Definition at line 62 of file Assembleur_P_CoviMAC.cpp.
References assembler_mat().
{
  DoubleVect rien;
  return assembler_mat(la_matrice,rien,1,1);
}
int Assembleur_P_CoviMAC::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) [virtual]
Reimplemented from Assembleur_base.
Definition at line 68 of file Assembleur_P_CoviMAC.cpp.
References Matrix_tools::allocate_morse_matrix(), IntTab::append_line(), equation(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), has_P_ref, la_zone_Cl_CoviMAC, la_zone_CoviMAC, Process::me(), IntVect::ref_array(), ref_cast, DoubleVect::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), ArrOfInt::set_smart_resize(), IntVect::size(), stencil_done, sub_type, tab1, tab2, tableau_trier_retirer_doublons(), Deriv_::typer(), Ref_Zone_Cl_CoviMAC::valeur(), valeur(), Ref_Zone_CoviMAC::valeur(), and Deriv_Matrice_Base::valeur().
Referenced by assembler().
{
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  la_matrice.typer("Matrice_Morse");
  Matrice_Morse& mat = ref_cast(Matrice_Morse, la_matrice.valeur());
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC, la_zone_CoviMAC.valeur());
  const Op_Grad_CoviMAC_Face& grad = ref_cast(Op_Grad_CoviMAC_Face, ref_cast(Navier_Stokes_std, equation()).operateur_gradient().valeur());
  const DoubleTab& mu_f = grad.mu_f(), &fgrad_c = grad.fgrad_c;
  const IntTab& f_e = zone.face_voisins(), &fgrad_d = grad.fgrad_d, &fgrad_e = grad.fgrad_e;
  const DoubleVect& pf = zone.porosite_face(), &fs = zone.face_surfaces();
  int i, j, e, eb, f, ne = zone.nb_elem(), ne_tot = zone.nb_elem_tot();
// en l'absence de CLs en pression, on ajoute P(0) = 0 sur le process 0
  has_P_ref=0;
  for (int n_bord=0; n_bord<la_zone_CoviMAC->nb_front_Cl(); n_bord++)
    if (sub_type(Neumann_sortie_libre, la_zone_Cl_CoviMAC->les_conditions_limites(n_bord).valeur()) )
      has_P_ref=1;
  /* 1. stencil de la matrice en pression : seulement au premier passage */
  if (!stencil_done)
    {
      IntTrav stencil(0, 2);
      stencil.set_smart_resize(1);
      for (f = 0; f < zone.nb_faces(); f++) for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) if (e < ne) for (j = fgrad_d(f); j < fgrad_d(f + 1); j++)
              if ((eb = fgrad_e(j)) < ne_tot) stencil.append_line(e, eb);
      tableau_trier_retirer_doublons(stencil);
      Matrix_tools::allocate_morse_matrix(ne_tot, ne_tot, stencil, mat);
      tab1.ref_array(mat.get_set_tab1()), tab2.ref_array(mat.get_set_tab2());
      stencil_done = 1;
    }
  else //sinon, on recycle
    {
      mat.get_set_tab1().ref_array(tab1);
      mat.get_set_tab2().ref_array(tab2);
      mat.get_set_coeff().resize(tab2.size());
      mat.set_nb_columns(ne_tot);
    }
  /* 2. remplissage des coefficients : style Op_Diff_PolyMAC_Elem */
  for (f = 0; f < zone.nb_faces(); f++) for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) if (e < ne) for (j = fgrad_d(f); j < fgrad_d(f + 1); j++) if ((eb = fgrad_e(j)) < ne_tot)
            mat(e, eb) += (i ? 1 : -1) * pf(f) * fs(f) * (mu_f(f, 0, 0) * fgrad_c(j, 0, 0) + mu_f(f, 0, 1) * fgrad_c(j, 0, 1));
  if (!has_P_ref && !Process::me()) mat(0, 0) *= 2;
  return 1;
}
void Assembleur_P_CoviMAC::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis) [virtual]
Implements Assembleur_base.
Definition at line 158 of file Assembleur_P_CoviMAC.cpp.
References la_zone_Cl_CoviMAC, and ref_cast.
{
  la_zone_Cl_CoviMAC = ref_cast(Zone_Cl_CoviMAC, la_zone_Cl_dis);
}
void Assembleur_P_CoviMAC::associer_zone_dis_base (const Zone_dis_base & la_zone_dis) [virtual]
Implements Assembleur_base.
Definition at line 153 of file Assembleur_P_CoviMAC.cpp.
References la_zone_CoviMAC, and ref_cast.
{
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC,la_zone_dis);
}
void Assembleur_P_CoviMAC::completer (const Equation_base & Eqn) [virtual]
Implements Assembleur_base.
Definition at line 163 of file Assembleur_P_CoviMAC.cpp.
References mon_equation, and stencil_done.
{
  mon_equation=Eqn;
  stencil_done = 0;
}
Objet_U * Assembleur_P_CoviMAC::cree_instance () [static]
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
int Assembleur_P_CoviMAC::duplique () const [virtual]
Implements Assembleur_base.
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
const Equation_base & Assembleur_P_CoviMAC::equation () const [inline]
Definition at line 66 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat().
{
  return  mon_equation.valeur();
}
const Type_info * Assembleur_P_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
const Type_info * Assembleur_P_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
int Assembleur_P_CoviMAC::modifier_secmem (DoubleTab &) [inline, virtual]
Implements Assembleur_base.
Definition at line 49 of file Assembleur_P_CoviMAC.h.
  {
    return 1;
  }
int Assembleur_P_CoviMAC::modifier_solution (DoubleTab & pression) [virtual]
Implements Assembleur_base.
Definition at line 118 of file Assembleur_P_CoviMAC.cpp.
References DMAXFLOAT, DoubleVect::echange_espace_virtuel(), has_P_ref, la_zone_CoviMAC, Process::mp_min(), Zone::nb_elem(), Ref_Zone_CoviMAC::valeur(), verifier(), and Zone_dis_base::zone().
{
  Debog::verifier("pression dans modifier solution in",pression);
// Projection :
  double press_0;
  if(!has_P_ref)
    {
// abort();
// On prend la pression minimale comme pression de reference
// afin d'avoir la meme pression de reference en sequentiel et parallele
      press_0=DMAXFLOAT;
      int n,nb_elem=la_zone_CoviMAC.valeur().zone().nb_elem();
      for(n=0; n<nb_elem; n++)
        if (pression[n] < press_0)
          press_0 = pression[n];
      press_0 = Process::mp_min(press_0);
      for(n=0; n<nb_elem; n++)
        pression[n] -=press_0;
      pression.echange_espace_virtuel();
    }
  return 1;
}
Sortie & Assembleur_P_CoviMAC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 52 of file Assembleur_P_CoviMAC.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom() ;
}
Entree & Assembleur_P_CoviMAC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 57 of file Assembleur_P_CoviMAC.cpp.
{
  return Assembleur_base::readOn(s);
}
const Assembleur_P_CoviMAC & Assembleur_P_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Assembleur_base.
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
Assembleur_P_CoviMAC & Assembleur_P_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Assembleur_base.
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
unsigned Assembleur_P_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 50 of file Assembleur_P_CoviMAC.cpp.
const Zone_Cl_dis_base & Assembleur_P_CoviMAC::zone_Cl_dis_base () const [virtual]
Implements Assembleur_base.
Definition at line 148 of file Assembleur_P_CoviMAC.cpp.
References la_zone_Cl_CoviMAC, and Ref_Zone_Cl_CoviMAC::valeur().
{
  return la_zone_Cl_CoviMAC.valeur();
}
const Zone_dis_base & Assembleur_P_CoviMAC::zone_dis_base () const [virtual]
Implements Assembleur_base.
Definition at line 143 of file Assembleur_P_CoviMAC.cpp.
References la_zone_CoviMAC, and Ref_Zone_CoviMAC::valeur().
{
  return la_zone_CoviMAC.valeur();
}
Member Data Documentation
int Assembleur_P_CoviMAC::has_P_ref [protected]
Definition at line 61 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat(), and modifier_solution().
const Type_info Assembleur_P_CoviMAC::info_obj [static]
Reimplemented from Assembleur_base.
Definition at line 40 of file Assembleur_P_CoviMAC.h.
Ref_Zone_Cl_CoviMAC Assembleur_P_CoviMAC::la_zone_Cl_CoviMAC [protected]
Definition at line 60 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat(), associer_zone_cl_dis_base(), and zone_Cl_dis_base().
Ref_Zone_CoviMAC Assembleur_P_CoviMAC::la_zone_CoviMAC [protected]
Definition at line 59 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat(), associer_zone_dis_base(), modifier_solution(), and zone_dis_base().
Ref_Equation_base Assembleur_P_CoviMAC::mon_equation [protected]
Definition at line 58 of file Assembleur_P_CoviMAC.h.
Referenced by completer().
int Assembleur_P_CoviMAC::stencil_done [protected]
Definition at line 62 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat(), and completer().
IntVect Assembleur_P_CoviMAC::tab1 [protected]
Definition at line 63 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat().
IntVect Assembleur_P_CoviMAC::tab2 [protected]
Definition at line 63 of file Assembleur_P_CoviMAC.h.
Referenced by assembler_mat().
The documentation for this class was generated from the following files:
src/CoviMAC/Solveurs/Assembleur_P_CoviMAC.h
src/CoviMAC/Solveurs/Assembleur_P_CoviMAC.cpp