TRUST: Chimie Class Reference
Chimie Class Reference
#include <Chimie.h>
Public Member Functions
Chimie ()
~Chimie ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer (const Probleme_base &pb)
virtual int preparer_calcul ()
void mettre_a_jour (double temps)
double calculer_pas_de_temps () const
void discretiser (const Probleme_base &)
virtual const Champ_base & get_champ (const Motcle &nom) const
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const
int sauvegarder (Sortie &) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Chimie & self_cast (Objet_U &)
static const Chimie & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Reaction reactions_
Ref_Probleme_base pb_
Motcles alias
Vect_Ref_Champ_Inc_base liste_Y_
Vect_Ref_Champ_Inc_base liste_ai_
Vect_Ref_Champ_Inc_base liste_nd10_
Vect_Ref_Champ_Inc_base liste_ngrains_
Vect_Ref_Champ_Inc_base liste_C_
int nb_grains_
DoubleTab Puissance_volumique_
int modele_micro_melange_
double constante_modele_micro_melange_
Motcle espece_en_competition_micro_melange_
int marqueur_espece_en_competition_micro_melange_
Detailed Description
Definition at line 33 of file Chimie.h.
Constructor & Destructor Documentation
Chimie()
Chimie::Chimie ()
Definition at line 29 of file Chimie.cpp.
~Chimie()
Chimie::~Chimie ()
Definition at line 29 of file Chimie.cpp.
Member Function Documentation
calculer_pas_de_temps()
double Chimie::calculer_pas_de_temps () const
< boucle sur l'ensemble des reactions
Definition at line 59 of file Chimie.cpp.
{
  double dt=1e30;
  double dt_reaction;
  for (int i=0; i<reactions_.size(); i++) //!< boucle sur l'ensemble des reactions
    {
      dt_reaction=reactions_[i].calculer_pas_de_temps();
      if(i==0) Cout<<"Pour le(s) reaction(s), dt_max = ";
      Cout<<dt_reaction<<" ";
      if (i==(reactions_.size()-1)) Cout<<finl;
      dt=std::min(dt,dt_reaction);
    }
// double dt_n=pb_->schema_temps().pas_de_temps();
// filtre Butterworth :
// alpha=1    -> pas de filtre
// alpha->0   -> tres filtre
// double alpha_Butterworth=1.;
// return (dt_n*(1.-alpha_Butterworth)+alpha_Butterworth*dt);
  return dt;
}
References Cout, finl, reactions_, and liste::size().
completer()
void Chimie::completer (const Probleme_base & pb) virtual
< dimensionnement du tableau...
Definition at line 82 of file Chimie.cpp.
{
// si pas de reaction on ne fait rien
  if (reactions_.size()==0)
    return;
  pb_=pb;
// 1) determination du nombre de FM
  int nb_fm=0;
  int nb_grains=0;
  int nb_concentration=0;
// Motcles alias;
  ArrOfDouble masses_molaires;
  for (int n=0; n<pb.nombre_d_equations(); n ++)
    {
      if (sub_type(Convection_Diffusion_Concentration,pb.equation(n)))
        nb_concentration++;
    }
// 2 stockage des alias et des masses molaires
  masses_molaires.resize_array(nb_grains+nb_fm+nb_concentration);
  alias.dimensionner(nb_grains+nb_fm+nb_concentration);
  nb_grains_=nb_grains;
  int nb=0;
  for (int n=0; n<pb.nombre_d_equations(); n ++)
    {
      if (sub_type(Convection_Diffusion_Concentration,pb.equation(n)))
        {
          const Convection_Diffusion_Concentration& eq= ref_cast(Convection_Diffusion_Concentration,pb.equation(n));
          masses_molaires[nb]=eq.masse_molaire();
          alias[nb]=eq.inconnue().valeur().le_nom();
          REF(Champ_Inc_base) inco;
          inco = eq.inconnue().valeur();
          liste_C_.add(inco);
          nb++;
        }
    }
  assert(liste_ai_.size()==nb_grains_);
// verification de l'unicite des  alias
  marqueur_espece_en_competition_micro_melange_=-1;
  {
    LIST(Nom) test;
    for (int n=0; n<alias.size(); n++)
      {
        int deja=test.contient(alias[n]);
        if (!deja)
          test.add(alias[n]);
        else
          {
            Cerr<<alias[n] <<" defini plusieurs fois !!!!!"<<finl;
// Cerr<<test<< " "<<alias<<finl;
            exit();
          }
        if (espece_en_competition_micro_melange_!=Nom())
          {
            if (espece_en_competition_micro_melange_==alias[n])
              marqueur_espece_en_competition_micro_melange_=n;
          }
      }
    assert(test.size()==nb_fm+nb_grains_+nb_concentration);
  }
  if (espece_en_competition_micro_melange_!=Nom())
    {
      if (marqueur_espece_en_competition_micro_melange_==-1)
        {
          Cerr<<" espece_en_competition_micro_melange non trouve: "<< espece_en_competition_micro_melange_<<finl;
          exit();
        }
      else
        Cerr<<" marqueur_espece_en_competition_micro_melange "<<marqueur_espece_en_competition_micro_melange_<<finl;
    }
  if(min_array(masses_molaires)<0)
    {
      Cerr<< "pb avec les masses_molaires "<<masses_molaires<<finl;
      exit();
    }
  if (liste_Y_.size()>0)
    {
      Puissance_volumique_=(liste_Y_[0].valeur().valeurs()); //!< dimensionnement du tableau...
      Puissance_volumique_=0.;
    }
  else
    {
      assert(liste_C_.size()!=0);
    }
// alias_=alias;
  for (int i=0; i<reactions_.size(); i++)
    {
      reactions_[i].completer(alias,masses_molaires);
    }
}
References Vect_Ref_Champ_Inc_base::add(), alias, Cerr, vect_impl::dimensionner(), Probleme_base::equation(), espece_en_competition_micro_melange_, Process::exit(), finl, Convection_Diffusion_Concentration::inconnue(), Field_base::le_nom(), LIST, liste_ai_, liste_C_, liste_Y_, marqueur_espece_en_competition_micro_melange_, Convection_Diffusion_Concentration::masse_molaire(), min_array(), nb_grains_, Probleme_base::nombre_d_equations(), pb_, Puissance_volumique_, reactions_, REF, ref_cast, TRUSTArray< _TYPE_ >::resize_array(), liste::size(), vect_impl::size(), sub_type, test(), and Deriv_Champ_Inc_base::valeur().
cree_instance()
Objet_U * Chimie::cree_instance () static
Definition at line 29 of file Chimie.cpp.
discretiser()
void Chimie::discretiser (const Probleme_base & pb)
Definition at line 175 of file Chimie.cpp.
{
  for (int i=0; i<reactions_.size(); i++)
    {
      Nom test("omega_");
      test+=Nom(i);
      reactions_[i].discretiser_omega(pb,test);
    }
}
References reactions_, liste::size(), and test().
duplique()
int Chimie::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Chimie.cpp.
get_champ()
const Champ_base & Chimie::get_champ (const Motcle & nom) const virtual
Definition at line 545 of file Chimie.cpp.
{
  int nb_reac=reactions_.size();
  for (int i=0; i<nb_reac; i++)
    {
      Nom test("omega_");
      test+=Nom(i);
      if (nom==test)
        return reactions_[i].get_omega();
    }
  throw Champs_compris_erreur();
  return get_champ(nom);
}
References get_champ(), reactions_, liste::size(), and test().
Referenced by get_champ().
get_info()
const Type_info * Chimie::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 29 of file Chimie.cpp.
get_noms_champs_postraitables()
void Chimie::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const virtual
Definition at line 560 of file Chimie.cpp.
{
  if (opt==DESCRIPTION)
    Cerr<<" Chimie :";
  int nb_reac=reactions_.size();
  for (int i=0; i<nb_reac; i++)
    {
      Nom test("omega_");
      test+=Nom(i);
      if (opt==DESCRIPTION)
        Cerr<< test;
      else
        nom.add(test);
    }
  if (opt==DESCRIPTION)
    Cerr<<finl;
}
References Vect_Nom::add(), Cerr, DESCRIPTION, finl, reactions_, liste::size(), and test().
info()
const Type_info * Chimie::info () static
Definition at line 29 of file Chimie.cpp.
mettre_a_jour()
void Chimie::mettre_a_jour (double temps)
< pas de reaction
< c'est un reactif ou un produit
Definition at line 192 of file Chimie.cpp.
{
  if (reactions_.size()==0) //!< pas de reaction
    return;
  double dt=pb_->schema_temps().pas_de_temps();
  if (liste_C_.size())
    {
// On suppose qu'il n'y a pas de temperature pour l'instant...
      int old=0;
      int nbr=reactions_.size();
      if (old)
        {
          for (int i=0; i<nbr; i++)
            {
              Reaction& reaction=reactions_[i];
              int nb_sous_pas_de_temps_reaction=reaction.nb_sous_pas_de_temps_reaction();
              const double dt_chimie=dt/nb_sous_pas_de_temps_reaction;
              for (int n=0; n<nb_sous_pas_de_temps_reaction; n++)
                reaction.reagir(liste_C_,dt_chimie);
            }
          for (int i=0; i<liste_C_.size(); i++)
            liste_C_[i].valeur().valeurs().echange_espace_virtuel();
          return;
        }
      int vef=0;
      Zone_VF& zvf = ref_cast(Zone_VF,liste_C_[0].valeur().equation().zone_dis().valeur());
// if (sub_type(Zone_VEF, zvf))
      if (zvf.que_suis_je().debute_par("Zone_VEF"))
        vef=1;
      const IntTab& face_voisins = zvf.face_voisins();
      const ArrOfDouble& volume=zvf.volumes();
      int newd=1;
      if (newd)
        {
          int nbrtot=0;
          ArrOfInt marq_contre(2*nbr);
          for (int i=0; i<nbr; i++)
            {
              Reaction& reaction=reactions_[i];
              marq_contre[nbrtot++]=i+1;
              if (reaction.contre_reaction_>0)
                marq_contre[nbrtot++]=-(i+1);
              if ((reaction.beta_!=0)||(reaction.Ea_!=0)||((reaction.c_r_Ea_!=0)&&(reaction.contre_reaction_>0)))
                {
                  Cerr<<"Reaction :  Donnees incompatibles avec le fait que l on n a pas de temperature"<<finl;
                  Cerr<<reaction<<finl;
                  exit();
                }
            }
          marq_contre.resize_array(nbrtot);
          int nbc=liste_C_.size();
          F77NAME(INITTAILLECOMMON)(&nbrtot,&nbc);
          ArrOfDouble pstochio(nbc);
          ArrOfInt pactivite(nbc);
          F77NAME(SETMARQUEUR)(&marqueur_espece_en_competition_micro_melange_);
          for (int i=0; i<nbrtot; i++)
            {
              int ir=marq_contre[i];
              int ir2=ir;
              if (ir<0) ir2=-ir2;
              ir2-=1;
              Reaction& reaction=reactions_[ir2];
              pstochio=reaction.coeff_stoechio_;
              pactivite=0;
              double cw=reaction.constante_taux_reaction_;
              if (ir<0)
                {
                  pstochio*=-1;
                  assert(reaction.contre_reaction_>0);
                  cw/=reaction.contre_reaction_;
                }
              for (int ic=0; ic<nbc; ic++)
                {
                  if (pstochio[ic]>0)
                    pactivite[ic]=(int)reaction.coeff_activite_[ic];
                }
              int ii=i+1;
              int avec_contre_reaction=(reaction.contre_reaction_>0);
              F77NAME(INITREACTIONCOMMON)(&(ii), pstochio.addr(), pactivite.addr(),&avec_contre_reaction) ;
              F77NAME(SETCWREACTION)(&(ii), &cw);
            }
// F77NAME(PRINT_COMMON)();
// abort();
          int mf=21;
          int lrw;
          int liw;
          if (mf==21)
            {
              liw=20+nbc;
              lrw=22+9*nbc+nbc*nbc;
            }
          else
            throw;
          assert(mf==21);
          ArrOfDouble rwork(lrw);
          ArrOfInt iwork(liw);
          DoubleTab tau_mel;
          if (modele_micro_melange_>0)
            {
              const DoubleTab& visc_turb=liste_C_[0].valeur().equation().probleme().get_champ("viscosite_turbulente").valeurs();
              tau_mel=visc_turb;
              const DoubleTab& D_moleculaire = ref_cast(Convection_Diffusion_Concentration,liste_C_[0].valeur().equation()).constituant().diffusivite_constituant().valeurs();
              double D_mol=0.;
              if (D_moleculaire.dimension(0) == 1)
                D_mol = D_moleculaire(0, 0);
              else
                {
                  Cerr << "D_mol pas code pour champ non uniforme" << finl;
                  exit();
                }
              double invsct=1./0.9;
              for (int element=0; element<visc_turb.dimension(0); element++)
                {
                  double delta=exp(log(volume[element])/double(dimension));
// Cerr<<" iii "<<delta<<" "<<D_mol<<finl;
                  tau_mel(element)=constante_modele_micro_melange_*delta*delta/(D_mol+visc_turb(element)*invsct);
                }
              tau_mel.echange_espace_virtuel();
            }
          int nb_elem=liste_C_[0].valeur().valeurs().size();
          ArrOfDouble C(nbc);
          for (int elem=0; elem<nb_elem; elem++)
            {
              double tau_melange=-1;
              if (modele_micro_melange_>0)
                {
                  if (vef==0)
                    tau_melange=tau_mel(elem);
                  else
                    {
                      if (face_voisins(elem,1)!=-1)
                        tau_melange = 0.5*(tau_mel(face_voisins(elem,0))+tau_mel(face_voisins(elem,1)));
                      else
                        tau_melange = (tau_mel(face_voisins(elem,0)));
                    }
                }
// tau_melange <0 pas pris en compte
// recuperation des valeurs initiales
              for (int i=0; i<nbc; i++)
                {
                  C[i]=liste_C_[i].valeur().valeurs()(elem);
                }
              for (int i=0; i<nbc; i++)
                {
                  if (C[i]<0)
                    {
                      if (C[i]<-1e-5)
{
                          Cerr<<" on rabote C_"<<i<<" dans la maille "<<elem<<" dans la chimie !!!!!! "<<C[i]<<finl;
                          exit();
                        }
                      C[i]=0;
                    }
                }
              int init=1;
              if (init)
                {
                }
              double t=0,tout=dt;
              int itol=1;
              double rtol=0;
              double atol=1e-10;
              F77NAME(DLSODECHIMIES)(&nbc, C.addr(),&t, &tout,&tau_melange, &itol, &rtol, &atol, rwork.addr(), &lrw, iwork.addr(), &liw);
// mise a jour des inconnues
              for (int i=0; i<liste_C_.size(); i++)
                liste_C_[i].valeur().valeurs()(elem)=C[i];
            }
          for (int i=0; i<liste_C_.size(); i++)
            liste_C_[i].valeur().valeurs().echange_espace_virtuel();
          return;
        }
// on calcule le nb_sous_pas_temps_max
      int nb_sous_pas_de_temps_reaction_max=1;
      int nbr_directe=0;
      ArrOfInt marq_directe(nbr);
      for (int i=0; i<nbr; i++)
        {
          Reaction& reaction=reactions_[i];
          int nb_sous_pas_de_temps_reaction=reaction.nb_sous_pas_de_temps_reaction();
          if (nb_sous_pas_de_temps_reaction>nb_sous_pas_de_temps_reaction_max)
            nb_sous_pas_de_temps_reaction_max=nb_sous_pas_de_temps_reaction;
          if (reaction.contre_reaction_<=0)
            marq_directe[nbr_directe++]=i;
          if ((reaction.beta_!=0)||(reaction.Ea_!=0)||((reaction.c_r_Ea_!=0)&&(reaction.contre_reaction_>0)))
            {
              Cerr<<"Reaction :  Donnees incompatibles avec le fait que l on n a pas de temperature"<<finl;
              Cerr<<reaction<<finl;
              exit();
            }
        }
      const double dt_chimie=dt/nb_sous_pas_de_temps_reaction_max;
      int nbc=liste_C_.size();
// double R_gaz_parfait=8.3143;
      ArrOfDouble C(nbc),C_tmp(nbc), proportion_eq(nbr_directe);
      int nb_elem=liste_C_[0].valeur().valeurs().size();
      for (int elem=0; elem<nb_elem; elem++)
        {
// recuperation des valeurs initiales
          for (int i=0; i<nbc; i++)
            {
              C[i]=liste_C_[i].valeur().valeurs()(elem);
            }
          for (int n=0; n<nb_sous_pas_de_temps_reaction_max; n++)
            {
// rabotage eventuel
              for (int i=0; i<nbc; i++)
                if (C[i]<0)
                  {
                    if (C[i]<-1e-5)
                      {
                        Cerr<<" on rabote C_"<<i<<" dans la maille "<<elem<<" dans la chimie !!!!!! "<<C[i]<<finl;
                        exit();
                      }
                    C[i]=0;
                  }
// calcul des proportions initiales des reactions non equilibre
              for (int i=0; i<nbr_directe; i++)
                {
                  Reaction& reaction=reactions_[marq_directe[i]];
                  assert(reaction.contre_reaction_<=0);
                  double proportion_directe;
                  reaction.calcul_proportion_implicite(C_tmp,C,dt_chimie,1e-7,proportion_directe);
                  if (0)
                    {
                      double proportion_directe2;
                      reaction.calcul_proportion_implicite(C_tmp,C,dt_chimie,1e9,proportion_directe2);
                      if (proportion_directe==proportion_directe2)
{
                          exit();
                        }
                    }
// on utilise proportion_directe pour ne pas avoir la limitation par la securite
                  proportion_eq[i]=proportion_directe;
                }
// pour chaque consitutant on regarde si il faut limiter ....
              double securite=1-1e-6;
              for (int c=0; c<nbc; c++)
                {
                  double St=0;
                  for (int i=0; i<nbr_directe; i++)
                    {
                      Reaction& reaction=reactions_[marq_directe[i]];
                      assert(reaction.contre_reaction_<=0);
                      if (reaction.coeff_Y_[c]>0.)
                        St+=proportion_eq[i]*reaction.coeff_stoechio_[c];
                    }
                  double rapport=St/(securite);
// Cerr<< c<<" ici0b "<< rapport <<" st "<<St<<" "<<C(c)<<finl;
                  if (rapport>C[c])
                    {
// on risque de trop consommer .... on limite.
                      Cerr<< c<<" limite ici0 "<< rapport <<" st "<<St<<" "<<C[c]<<" "<<C[c]/rapport<<finl;
// exit();
                      for (int i=0; i<nbr_directe; i++)
{
                          Reaction& reaction=reactions_[marq_directe[i]];
                          assert(reaction.contre_reaction_<=0);
                          if (reaction.coeff_Y_[c]>0.)
                            proportion_eq[i]*=C[c]/rapport;
                        }
                    }
                }
// on fait reagir les reactions directes C(c)-=St;
              for (int c=0; c<nbc; c++)
                {
                  double St=0;
                  for (int i=0; i<nbr_directe; i++)
                    {
                      Reaction& reaction=reactions_[marq_directe[i]];
                      assert(reaction.contre_reaction_<=0);
                      if (reaction.coeff_Y_[c]!=0.)
                        St+=proportion_eq[i]*reaction.coeff_stoechio_[c];
                    }
// Cerr<<C(c)<<" "<< c<< " la  st "<<St<<" ";
// assert(St<=(C(c)*securite));
                  C[c]-=St;
                  assert(C[c]>=0);
// Cerr<< C(c)<<finl;
                }
// on taite maintenant les reactions equilibrees les unes apres les autres
              securite=0.5;
              for (int reac=0; reac<nbr; reac++)
                {
                  Reaction& reaction=reactions_[reac];
                  if (reaction.contre_reaction_>0)
                    {
                      double proportion_directe;
                      double proportion=reaction.calcul_proportion_implicite(C_tmp, C,dt_chimie,1e-7,proportion_directe);
                      for (int i=0; i<nbc; i++)
                        if (reaction.coeff_Y_[i]!=0.) //!< c'est un reactif ou un produit
{
                            C[i]=C[i]-proportion*reaction.coeff_stoechio_[i];
                          }
                    }
                }
            }
// reaction.reagir(liste_C_,dt_chimie);
          for (int i=0; i<liste_C_.size(); i++)
            liste_C_[i].valeur().valeurs()(elem)=C[i];
        }
      for (int i=0; i<liste_C_.size(); i++)
        liste_C_[i].valeur().valeurs().echange_espace_virtuel();
      return;
    }
  Cerr<<"Chimie dispo qu'avec des concentrations"<<finl;
  exit();
}
References TRUSTArray< _TYPE_ >::addr(), Reaction::beta_, Reaction::calcul_proportion_implicite(), Cerr, Reaction::coeff_activite_, Reaction::coeff_stoechio_, Reaction::coeff_Y_, constante_modele_micro_melange_, Reaction::constante_taux_reaction_, Reaction::contre_reaction_, Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DLSODECHIMIES(), Reaction::Ea_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), F77NAME, Zone_VF::face_voisins(), finl, INITREACTIONCOMMON(), INITTAILLECOMMON(), liste_C_, marqueur_espece_en_competition_micro_melange_, modele_micro_melange_, Reaction::nb_sous_pas_de_temps_reaction(), Schema_Temps_base::pas_de_temps(), pb_, Objet_U::que_suis_je(), reactions_, Reaction::reagir(), ref_cast, TRUSTArray< _TYPE_ >::resize_array(), Probleme_base::schema_temps(), SETCWREACTION(), SETMARQUEUR(), liste::size(), vect_impl::size(), valeur(), and Zone_VF::volumes().
preparer_calcul()
int Chimie::preparer_calcul (void) virtual
Definition at line 185 of file Chimie.cpp.
{
  return 1;
}
printOn()
Sortie & Chimie::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 38 of file Chimie.cpp.
{
  os<<(*this).le_nom()<<finl;
  os<<reactions_<<finl;
  return os;
}
References finl, and reactions_.
readOn()
Entree & Chimie::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 45 of file Chimie.cpp.
{
  modele_micro_melange_=0;
  constante_modele_micro_melange_=1.;
  Param param(que_suis_je());
  param.ajouter("reactions",&reactions_,Param::REQUIRED);
  param.ajouter("modele_micro_melange",&modele_micro_melange_);
  param.ajouter("constante_modele_micro_melange",&constante_modele_micro_melange_);
  param.ajouter("espece_en_competition_micro_melange",&espece_en_competition_micro_melange_);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter(), constante_modele_micro_melange_, espece_en_competition_micro_melange_, Param::lire_avec_accolades_depuis(), modele_micro_melange_, Objet_U::que_suis_je(), reactions_, and Param::REQUIRED.
reprendre()
int Chimie::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 586 of file Chimie.cpp.
{
  return 1;
}
sauvegarder()
int Chimie::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 579 of file Chimie.cpp.
{
  return 1;
}
self_cast() [1/2]
const Chimie & Chimie::self_cast (const Objet_U & r) static
Definition at line 29 of file Chimie.cpp.
self_cast() [2/2]
Chimie & Chimie::self_cast (Objet_U & r) static
Definition at line 29 of file Chimie.cpp.
taille_memoire()
unsigned Chimie::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Chimie.cpp.
Member Data Documentation
alias
Motcles Chimie::alias protected
Definition at line 50 of file Chimie.h.
Referenced by completer().
constante_modele_micro_melange_
double Chimie::constante_modele_micro_melange_ protected
Definition at line 55 of file Chimie.h.
Referenced by mettre_a_jour(), and readOn().
espece_en_competition_micro_melange_
Motcle Chimie::espece_en_competition_micro_melange_ protected
Definition at line 56 of file Chimie.h.
Referenced by completer(), and readOn().
info_obj
const Type_info Chimie::info_obj static
Definition at line 35 of file Chimie.h.
liste_ai_
Vect_Ref_Champ_Inc_base Chimie::liste_ai_ protected
Definition at line 51 of file Chimie.h.
Referenced by completer().
liste_C_
Vect_Ref_Champ_Inc_base Chimie::liste_C_ protected
Definition at line 51 of file Chimie.h.
Referenced by completer(), and mettre_a_jour().
liste_nd10_
Vect_Ref_Champ_Inc_base Chimie::liste_nd10_ protected
Definition at line 51 of file Chimie.h.
liste_ngrains_
Vect_Ref_Champ_Inc_base Chimie::liste_ngrains_ protected
Definition at line 51 of file Chimie.h.
liste_Y_
Vect_Ref_Champ_Inc_base Chimie::liste_Y_ protected
Definition at line 51 of file Chimie.h.
Referenced by completer().
marqueur_espece_en_competition_micro_melange_
int Chimie::marqueur_espece_en_competition_micro_melange_ protected
Definition at line 57 of file Chimie.h.
Referenced by completer(), and mettre_a_jour().
modele_micro_melange_
int Chimie::modele_micro_melange_ protected
Definition at line 54 of file Chimie.h.
Referenced by mettre_a_jour(), and readOn().
nb_grains_
int Chimie::nb_grains_ protected
Definition at line 52 of file Chimie.h.
Referenced by completer().
pb_
Ref_Probleme_base Chimie::pb_ protected
Definition at line 49 of file Chimie.h.
Referenced by completer(), and mettre_a_jour().
Puissance_volumique_
DoubleTab Chimie::Puissance_volumique_ protected
Definition at line 53 of file Chimie.h.
Referenced by completer().
reactions_
List_Reaction Chimie::reactions_ protected
Definition at line 48 of file Chimie.h.
Referenced by calculer_pas_de_temps(), completer(), discretiser(), get_champ(), get_noms_champs_postraitables(), mettre_a_jour(), printOn(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Chimie/Chimie.h
src/ThHyd/Chimie/Chimie.cpp