TRUST: Op_Conv_EF_VEF_P1NC Class Reference
Op_Conv_EF_VEF_P1NC Class Reference
class Op_Conv_EF_VEF_P1NC
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Amont
Les methodes pour l'implicite sont codees.
#include <Op_Conv_EF_VEF_P1NC.h>
Public Member Functions
Op_Conv_EF_VEF_P1NC ()
~Op_Conv_EF_VEF_P1NC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice au moyen de la methode dimensionner de la classe
Op_VEF_Face.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
On modifie le second membre et la matrice dans le cas des
conditions de dirichlet.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice des inconnues implicite.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
Public Member Functions inherited from Op_Conv_VEF_base
Op_Conv_VEF_base ()
~Op_Conv_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_vitesse (const Champ_base &) override
const Champ_Inc_base & vitesse () const
Champ_Inc_base & vitesse ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void abortTimeStep () override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_dt_local (DoubleTab &) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_fluent (DoubleVect &) const
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
int phi_u_transportant (const Equation_base &eq) const
definit si l'on convecte psi avec phi*u ou avec u
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_EF_VEF_P1NC & self_cast (Objet_U &)
static const Op_Conv_EF_VEF_P1NC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_VEF_base
static const Type_info * info ()
static Op_Conv_VEF_base & self_cast (Objet_U &)
static const Op_Conv_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Conv_VEF_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
int transportant_bar
int transporte_bar
int filtrer_resu
int antisym
Protected Attributes inherited from Op_Conv_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base vitesse_
DoubleVect fluent
tableau qui sert pour le calcul du pas de temps de stabilite
int jeton
int roue
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Conv_EF_VEF_P1NC
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Amont
Les methodes pour l'implicite sont codees.
Definition at line 38 of file Op_Conv_EF_VEF_P1NC.h.
Constructor & Destructor Documentation
Op_Conv_EF_VEF_P1NC()
Op_Conv_EF_VEF_P1NC::Op_Conv_EF_VEF_P1NC ()
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
~Op_Conv_EF_VEF_P1NC()
Op_Conv_EF_VEF_P1NC::~Op_Conv_EF_VEF_P1NC ()
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_EF_VEF_P1NC::ajouter (const DoubleTab & transporte_2, DoubleTab & resu) const override virtual
< Ui Uj,i Vj - Ui Vj,i Uj
< Ui Uj,i Vj
Reimplemented from Operateur_base.
Definition at line 104 of file Op_Conv_EF_VEF_P1NC.cpp.
{
// Cerr << "Op_Conv_EF_VEF_P1NC::ajouter" << finl;
  DoubleTab sauv(resu);
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Champ_P1NC& la_vitesse=ref_cast( Champ_P1NC, vitesse_.valeur());
  const DoubleTab& vitesse_face_absolue=la_vitesse.valeurs();
  const Champ_P1NC& ch=ref_cast(Champ_P1NC,mon_equation->inconnue().valeur());
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const int nb_faces_elem=elem_faces.dimension(1);
  assert(nb_faces_elem==(dimension+1));
  {
// calcul de la CFL.
    DoubleVect& fluent_ = fluent;
    double psc;
// On remet a zero le tableau qui sert pour
// le calcul du pas de temps de stabilite
    fluent_ = 0;
    const int nb_faces = zone_VEF.nb_faces();
    for(int num_face=0; num_face<nb_faces; num_face++)
      {
        psc=0.;
        for (int i=0; i<dimension; i++)
          psc+=vitesse_face_absolue(num_face,i)*face_normales(num_face,i);
        fluent_(num_face)=std::fabs(psc);
      }
  }
  int marq=phi_u_transportant(equation());
  DoubleTab transporte_;
  DoubleTab vitesse_face_;
// soit on a transporte=phi*transporte_ et vitesse_face=vitesse_
// soit transporte=transporte_ et vitesse_face=phi*vitesse_
// cela d~pend si on transporte avec phi u ou avec u.
  const DoubleTab& transporte=modif_par_porosite_si_flag(transporte_2,transporte_,!marq,porosite_face);
  const DoubleTab& tab_vitesse=modif_par_porosite_si_flag(vitesse_face_absolue,vitesse_face_,marq,porosite_face);
// DoubleTab ubar(transporte);
// la_vitesse.filtrer_L2(ubar);
// DoubleTab uprime(transporte);
// uprime-=ubar;
  DoubleTab uT(transporte);
  DoubleTab u(tab_vitesse);
  if (transporte_bar) ch.filtrer_L2(uT);
  if (transportant_bar) la_vitesse.filtrer_L2(u);
  const int nb_comp =resu.line_size();
  DoubleTab grad_uT(nb_comp, dimension);
  DoubleTab grad_phi(nb_faces_elem,dimension);
  int elem, num_face, j, i, face;
  double d_inv=(1./nb_faces_elem);
  resu=0;
  DoubleTab sigma(dimension, dimension);
  DoubleTab contrib_elem(nb_faces_elem, nb_comp);
  for (elem=0; elem<nb_elem_tot; elem++)
    {
// for elem
      sigma=0, contrib_elem=0, grad_uT=0., grad_phi=0.;
      for(num_face=0; num_face<nb_faces_elem; num_face++)
        {
// for num_face
          face=elem_faces(elem, num_face);
          double cc=1.;
          if(face_voisins(face,0)!=elem)
            cc*=-1;
          for (i=0; i<dimension; i++)
            {
              grad_phi(num_face,i)=face_normales(face,i)*cc;
              for (j=0; j<nb_comp; j++)
                {
                  sigma(i,j)+=u(face,i)*uT(face,j);
                  grad_uT(j,i)+=uT(face,j)*grad_phi(num_face,i);
                }
            }
        }
      if(antisym==1)
        {
          for(num_face=0; num_face<nb_faces_elem; num_face++)
            {
// for num_face
              face=elem_faces(elem, num_face);
              for (i=0; i<dimension; i++)
                for (j=0; j<nb_comp; j++)
                  contrib_elem(num_face,j)-=0.5*d_inv*(u(face,i)*grad_uT(j,i)-sigma(i,j)*grad_phi(num_face,i));//!< Ui Uj,i Vj - Ui Vj,i Uj
            }
        }
      else
        {
          for(num_face=0; num_face<nb_faces_elem; num_face++)
            {
// for num_face
              face=elem_faces(elem, num_face);
              for (i=0; i<dimension; i++)
                for (j=0; j<nb_comp; j++)
                  contrib_elem(num_face,j)-=d_inv*(u(face,i)*grad_uT(j, i));//!< Ui Uj,i Vj
            }
        }
      for(num_face=0; num_face<nb_faces_elem; num_face++)
        {
          face=elem_faces(elem, num_face);
          for (i=0; i<nb_comp; i++)
            resu(face,i)+=contrib_elem(num_face,i);
        }
    }
  for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int nb_faces_bord_tot=le_bord.nb_faces_tot();
      int num10 = 0, num20 = le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int face_associee;
          IntVect fait(nb_faces_bord_tot);
          fait = 0;
          for (int ind_face=num10; ind_face<num20; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              if (fait(ind_face) == 0)
                {
                  fait(ind_face) = 1;
                  face_associee=la_cl_perio.face_associee(ind_face);
                  fait(face_associee) = 1;
                  face_associee = le_bord.num_face(face_associee);
                  for (int comp=0; comp<nb_comp; comp++)
                    {
                      double som;
                      som=resu(face_associee,comp)+resu(face,comp);
                      resu(face,comp)=resu(face_associee,comp)=som;
                    }
                }//!< if fait
            }//!< for face
        }//!< sub_type Perio
      else if ((antisym==1) && (!sub_type(Symetrie,la_cl.valeur())) )
        {
// Cerr << "Ajout des termes de bords :" << finl;
          int num1 = le_bord.num_premiere_face();
          int nb_faces=le_bord.nb_faces();
          int num2 = num1 + nb_faces;
          for (face=num1; face<num2; face++)
            {
              int comp;
              double psc = 0;
              for (comp=0; comp<nb_comp; comp++)
                psc += face_normales(face,comp)*u(face, comp);
              psc *=0.5;
              for (comp=0; comp<nb_comp; comp++)
                resu(face, comp)-=psc*uT(face, comp);
            }
        }
    }//!< for nbord
  if(filtrer_resu)
    ch.filtrer_resu(resu);
// On desactive le calcul et l'impression des energies u'......
// on garde le codage au cas ou..
  if (0)
    {
      Cerr << "filtrage petites echelles : " << finl;
      DoubleTab ubar(transporte);
      ch.filtrer_L2(ubar);
      DoubleTab uprime(transporte);
      uprime-=ubar;
      const int nb_faces = zone_VEF.nb_faces();
      const DoubleVect& volumes_entrelaces=zone_VEF.volumes_entrelaces();
      int face2, k;
      double psc=0., pscprim=0., ec=0., ecprime=0.;
      int deb=zone_VEF.premiere_face_int();
      for(face2=deb; face2<nb_faces; face2++)
        for(k=0; k< dimension; k++)
          {
            double v=volumes_entrelaces(face2);
            double up, u2, r;
            if(nb_comp>1)
              {
                up=uprime(face2,k);
                uprime(face2,k)*=v;
                u2=ubar(face2,k);
                r=resu(face2,k);
              }
            else
              {
                up=uprime(face2);
                uprime(face2)*=v;
                u2=ubar(face2);
                r=resu(face2);
              }
            pscprim+=r*up;
            psc+=r*u2;
            ec+=u2*u2*v;
            ecprime+=up*up*v;
          }
      for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = le_bord.num_premiere_face();
          int nb_faces_b=le_bord.nb_faces();
          int num2 = num1 + nb_faces_b;
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
              int face_associee;
              IntVect fait(nb_faces_b);
              fait = 0;
              for (face2=num1; face2<num2; face2++)
                {
                  if (fait(face2-num1) == 0)
                    {
                      fait(face2-num1) = 1;
                      face_associee=la_cl_perio.face_associee(face2-num1);
                      fait(face_associee) = 1;
                      face_associee+=num1;
                      double v=volumes_entrelaces(face2);
                      double up, u2, r;
                      for(k=0; k< dimension; k++)
{
                          if(nb_comp>1)
{
                              up=(uprime(face2,k));
                              uprime(face2,k)*=v;
                              uprime(face_associee,k)=uprime(face2,k);
                              u2=ubar(face2,k);
                              r=resu(face2,k);
                            }
                          else
{
                              up=uprime(face2);
                              uprime(face2)*=v;
                              uprime(face_associee)=uprime(face2);
                              u2=ubar(face2);
                              r=resu(face2);
                            }
                          pscprim+=r*up;
                          psc+=r*u2;
                          ec+=u2*u2*v;
                          ecprime+=up*up*v;
                        }
                    }
                }
            }
          else
            {
              for (face2=num1; face2<num2; face2++)
                {
                  double v=volumes_entrelaces(face2);
                  double up, u2, r;
                  for(k=0; k< dimension; k++)
                    {
                      if(nb_comp>1)
{
                          up=(uprime(face2,k));
                          uprime(face2,k)*=v;
                          u2=ubar(face2,k);
                          r=resu(face2,k);
                        }
                      else
{
                          up=uprime(face2);
                          uprime(face2)*=v;
                          u2=ubar(face2);
                          r=resu(face2);
                        }
                      pscprim+=r*up;
                      psc+=r*u2;
                      ec+=u2*u2*v;
                      ecprime+=up*up*v;
                    }
                }
            }
        }
      Cerr << "(u,u) "<< ec <<finl;
      Cerr << "(u',u') "<< ecprime <<finl;
      Cerr << "(u grad u ,u) "<< psc <<finl;
      Cerr << "(u grad u ,u') "<< pscprim <<finl;
      double pourcent=0;
      if (!est_egal(ec,0))
        pourcent=100*sqrt(ecprime/ec);
      Cerr << "||u'||/||u|| :  " << pourcent << " %" << finl;
    }
  resu+=sauv;
  modifier_flux(*this);
  return resu;
}
References antisym, Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), est_egal(), Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Champ_P1NC::filtrer_L2(), Champ_P1NC::filtrer_resu(), filtrer_resu, finl, Op_Conv_VEF_base::fluent, Cond_lim::frontiere_dis(), Equation_base::inconnue(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), MorEqn::mon_equation, Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Op_Conv_VEF_base::phi_u_transportant(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, transportant_bar, transporte_, transporte_bar, Deriv_Champ_Inc_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), Op_Conv_VEF_base::vitesse_, and Zone_VF::volumes_entrelaces().
ajouter_contribution()
void Op_Conv_EF_VEF_P1NC::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Definition at line 419 of file Op_Conv_EF_VEF_P1NC.cpp.
{
  Cerr << "Op_Conv_EF_VEF_P1NC::ajouter_contribution non code." << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by contribuer_a_avec().
contribue_au_second_membre()
void Op_Conv_EF_VEF_P1NC::contribue_au_second_membre (DoubleTab & resu) const
Definition at line 425 of file Op_Conv_EF_VEF_P1NC.cpp.
{
  Cerr << "Op_Conv_EF_VEF_P1NC::contribue_au_second_membre non code." << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by contribuer_au_second_membre().
contribuer_a_avec()
void Op_Conv_EF_VEF_P1NC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice des inconnues implicite.
Reimplemented from Operateur_base.
Definition at line 86 of file Op_Conv_EF_VEF_P1NC.h.
{
  ajouter_contribution(inco, matrice);
}
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Conv_EF_VEF_P1NC::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 95 of file Op_Conv_EF_VEF_P1NC.h.
{
  contribue_au_second_membre(resu);
}
References contribue_au_second_membre().
cree_instance()
Objet_U * Op_Conv_EF_VEF_P1NC::cree_instance () static
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
dimensionner()
void Op_Conv_EF_VEF_P1NC::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice au moyen de la methode dimensionner de la classe
Op_VEF_Face.
Reimplemented from Operateur_base.
Definition at line 67 of file Op_Conv_EF_VEF_P1NC.h.
{
  Op_VEF_Face::dimensionner(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice);
}
References Op_VEF_Face::dimensionner(), Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
duplique()
int Op_Conv_EF_VEF_P1NC::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
get_info()
const Type_info * Op_Conv_EF_VEF_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
info()
const Type_info * Op_Conv_EF_VEF_P1NC::info () static
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
modifier_pour_Cl()
void Op_Conv_EF_VEF_P1NC::modifier_pour_Cl (Matrice_Morse & matrice, DoubleTab & secmem) const inline override virtual
On modifie le second membre et la matrice dans le cas des
conditions de dirichlet.
Reimplemented from Operateur_base.
Definition at line 77 of file Op_Conv_EF_VEF_P1NC.h.
{
  Op_VEF_Face::modifier_pour_Cl(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice, secmem);
}
References Op_Conv_VEF_base::la_zcl_vef, Op_Conv_VEF_base::la_zone_vef, Op_VEF_Face::modifier_pour_Cl(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
printOn()
Sortie & Op_Conv_EF_VEF_P1NC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 29 of file Op_Conv_EF_VEF_P1NC.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Conv_EF_VEF_P1NC::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Definition at line 37 of file Op_Conv_EF_VEF_P1NC.cpp.
{
  transportant_bar=0;
  transporte_bar=1;
  filtrer_resu=1;
  antisym=1;
  Motcle motlu;
  for (int i=0; i<4; i++)
    {
      s >> motlu;
      if (motlu=="defaut_bar")
        break;
      else if (motlu=="transportant_bar")
        s >> transportant_bar;
      else if (motlu=="transporte_bar")
        s >> transporte_bar;
      else if (motlu=="filtrer_resu")
        s >> filtrer_resu;
      else if (motlu=="antisym")
        s >> antisym;
      else
        {
          Cerr << motlu << "n'est pas compris par "
               << que_suis_je() << finl;
          exit();
        }
    }
  if (transportant_bar <0)
    {
      Cerr << "il manque le mot cle transportant_bar" << finl;
      exit();
    }
  if (transporte_bar <0)
    {
      Cerr << "il manque le mot cle transporte_bar" << finl;
      exit();
    }
  if (filtrer_resu <0)
    {
      Cerr << "il manque le mot cle filtrer_resu" << finl;
      exit();
    }
  if (antisym <0)
    {
      Cerr << "il manque le mot cle antisym" << finl;
      exit();
    }
  return s ;
}
References antisym, Cerr, Process::exit(), filtrer_resu, finl, Objet_U::que_suis_je(), transportant_bar, and transporte_bar.
self_cast() [1/2]
const Op_Conv_EF_VEF_P1NC & Op_Conv_EF_VEF_P1NC::self_cast (const Objet_U & r) static
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
self_cast() [2/2]
Op_Conv_EF_VEF_P1NC & Op_Conv_EF_VEF_P1NC::self_cast (Objet_U & r) static
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
taille_memoire()
unsigned Op_Conv_EF_VEF_P1NC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Op_Conv_EF_VEF_P1NC.cpp.
Member Data Documentation
antisym
int Op_Conv_EF_VEF_P1NC::antisym protected
Definition at line 59 of file Op_Conv_EF_VEF_P1NC.h.
Referenced by ajouter(), and readOn().
filtrer_resu
int Op_Conv_EF_VEF_P1NC::filtrer_resu protected
Definition at line 58 of file Op_Conv_EF_VEF_P1NC.h.
Referenced by ajouter(), and readOn().
info_obj
const Type_info Op_Conv_EF_VEF_P1NC::info_obj static
Definition at line 41 of file Op_Conv_EF_VEF_P1NC.h.
transportant_bar
int Op_Conv_EF_VEF_P1NC::transportant_bar protected
Definition at line 56 of file Op_Conv_EF_VEF_P1NC.h.
Referenced by ajouter(), and readOn().
transporte_bar
int Op_Conv_EF_VEF_P1NC::transporte_bar protected
Definition at line 57 of file Op_Conv_EF_VEF_P1NC.h.
Referenced by ajouter(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_EF_VEF_P1NC.h
src/VEF/Operateurs/Op_Conv_EF_VEF_P1NC.cpp