TRUST: Op_Conv_SUPG_EF Class Reference
Op_Conv_SUPG_EF Class Reference
: class Op_Conv_SUPG_EF
<Description of class Op_Conv_SUPG_EF>
#include <Op_Conv_SUPG_EF.h>
Public Member Functions
Op_Conv_SUPG_EF ()
~Op_Conv_SUPG_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
double coefficient_btd () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_SUPG_EF & self_cast (Objet_U &)
static const Op_Conv_SUPG_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
double ksupg_
Detailed Description
: class Op_Conv_SUPG_EF
<Description of class Op_Conv_SUPG_EF>
Definition at line 36 of file Op_Conv_SUPG_EF.h.
Constructor & Destructor Documentation
Op_Conv_SUPG_EF::Op_Conv_SUPG_EF ()
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
Op_Conv_SUPG_EF::~Op_Conv_SUPG_EF ()
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
Member Function Documentation
double Op_Conv_SUPG_EF::coefficient_btd () const [virtual]
Reimplemented from Op_Conv_BTD_EF.
Definition at line 44 of file Op_Conv_SUPG_EF.cpp.
References ksupg_, Op_Conv_EF::max_ue_, and Op_Conv_EF::min_dx_.
{
// double dt=equation().schema_temps().pas_de_temps();
// double f=btd*dt/2;
// f *  (2.0/DT) * (min_dx_/max_ue_);
  double f=ksupg_*(min_dx_/max_ue_);
  return f;
}
Objet_U * Op_Conv_SUPG_EF::cree_instance () [static]
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
int Op_Conv_SUPG_EF::duplique () const [virtual]
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
const Type_info * Op_Conv_SUPG_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
const Type_info * Op_Conv_SUPG_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
Sortie & Op_Conv_SUPG_EF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_BTD_EF.
Definition at line 28 of file Op_Conv_SUPG_EF.cpp.
{
  Op_Conv_BTD_EF::printOn( os );
  return os;
}
Entree & Op_Conv_SUPG_EF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
< utilise dans calculer_pas_de_temps
< XD convection_supg convection_deriv supg 1 Only for EF discretization.
< XD_ADD_P double not_set
< XD convection_btd convection_deriv btd 1 Only for EF discretization.
< XD_ADD_P double not_set
< XD_ADD_P double not_set
Reimplemented from Op_Conv_BTD_EF.
Definition at line 34 of file Op_Conv_SUPG_EF.cpp.
References Param::ajouter(), Op_Conv_EF::btd_, ksupg_, Param::lire_avec_accolades(), Objet_U::que_suis_je(), and Param::REQUIRED.
{
  btd_=3; //!< utilise dans calculer_pas_de_temps
  Param param(que_suis_je()); //!< XD convection_supg convection_deriv supg 1 Only for EF discretization.
  param.ajouter("facteur",&ksupg_,Param::REQUIRED); //!< XD_ADD_P double not_set
  param.lire_avec_accolades(is);
  return is;
}
const Op_Conv_SUPG_EF & Op_Conv_SUPG_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
Op_Conv_SUPG_EF & Op_Conv_SUPG_EF::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
unsigned Op_Conv_SUPG_EF::taille_memoire () const [virtual]
Reimplemented from Op_Conv_BTD_EF.
Definition at line 26 of file Op_Conv_SUPG_EF.cpp.
Member Data Documentation
const Type_info Op_Conv_SUPG_EF::info_obj [static]
Reimplemented from Op_Conv_BTD_EF.
Definition at line 39 of file Op_Conv_SUPG_EF.h.
double Op_Conv_SUPG_EF::ksupg_ [protected]
Definition at line 44 of file Op_Conv_SUPG_EF.h.
Referenced by coefficient_btd(), and readOn().
The documentation for this class was generated from the following files:
src/EF/Operateurs/Op_Conv_SUPG_EF.h
src/EF/Operateurs/Op_Conv_SUPG_EF.cpp