TRUST: Terme_Source_Qdm_Face_PolyMAC Class Reference
Terme_Source_Qdm_Face_PolyMAC Class Reference
class Terme_Source_Qdm_Face_PolyMAC
#include <Terme_Source_Qdm_Face_PolyMAC.h>
Public Member Functions
Terme_Source_Qdm_Face_PolyMAC ()
~Terme_Source_Qdm_Face_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &)
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Qdm_Face_PolyMAC & self_cast (Objet_U &)
static const
Terme_Source_Qdm_Face_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Zone_PolyMAC la_zone_PolyMAC
Ref_Zone_Cl_PolyMAC la_zone_Cl_PolyMAC
Detailed Description
class Terme_Source_Qdm_Face_PolyMAC
See also:
Source_base
Definition at line 42 of file Terme_Source_Qdm_Face_PolyMAC.h.
Constructor & Destructor Documentation
Terme_Source_Qdm_Face_PolyMAC::Terme_Source_Qdm_Face_PolyMAC ()
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
Terme_Source_Qdm_Face_PolyMAC::~Terme_Source_Qdm_Face_PolyMAC ()
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
Member Function Documentation
DoubleTab & Terme_Source_Qdm_Face_PolyMAC::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 80 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
References Objet_U::dimension, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Terme_Source_Qdm::la_source, la_zone_Cl_PolyMAC, la_zone_PolyMAC, Zone_Cl_dis_base::les_conditions_limites(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Champ_Don_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_PolyMAC::valeur(), Ref_Zone_PolyMAC::valeur(), Champ_Don::valeurs(), Zone_VF::xp(), and Zone_VF::xv().
Referenced by calculer().
{
  const Zone_PolyMAC& zone_PolyMAC = la_zone_PolyMAC.valeur();
  const Zone_Cl_PolyMAC& zone_Cl_PolyMAC = la_zone_Cl_PolyMAC.valeur();
  /* 1. faces de bord -> on ne contribue qu'aux faces de Neumann */
  for (int n_bord=0; n_bord<zone_PolyMAC.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_PolyMAC.les_conditions_limites(n_bord);
      if (!sub_type(Neumann,la_cl.valeur()) && !sub_type(Neumann_homogene,la_cl.valeur()) && !sub_type(Neumann_val_ext,la_cl.valeur())) continue;
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      for (int f = le_bord.num_premiere_face(); f < le_bord.num_premiere_face() + le_bord.nb_faces(); f++)
        {
          int e = zone_PolyMAC.face_voisins(f, 0);
          double fac = zone_PolyMAC.porosite_face(f) * zone_PolyMAC.face_surfaces(f);
          for (int r = 0; r < dimension; r++)
            resu(f) += fac * la_source->valeurs()(sub_type(Champ_Uniforme,la_source.valeur()) ? 0 : e, r)
                       * (zone_PolyMAC.xv(f, r) - zone_PolyMAC.xp(e, r));
        }
    }
  /* 2. faces internes -> contributions amont/aval */
  for (int f = zone_PolyMAC.premiere_face_int(); f < zone_PolyMAC.nb_faces(); f++)
    {
      double fac = zone_PolyMAC.porosite_face(f) * zone_PolyMAC.face_surfaces(f);
      for (int i = 0; i < 2; i++) for (int r = 0, e = zone_PolyMAC.face_voisins(f, i); r < dimension; r++)
          resu(f) += fac * la_source->valeurs()(sub_type(Champ_Uniforme,la_source.valeur()) ? 0 : e, r)
                     * (zone_PolyMAC.xv(f, r) - zone_PolyMAC.xp(e, r)) * (i ? -1 : 1);
    }
  return resu;
}
void Terme_Source_Qdm_Face_PolyMAC::associer_pb (const Probleme_base &) [virtual]
Implements Source_base.
Definition at line 67 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
{
  ;
}
void Terme_Source_Qdm_Face_PolyMAC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 72 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
References la_zone_Cl_PolyMAC, la_zone_PolyMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_PolyMAC = ref_cast(Zone_PolyMAC, zone_dis.valeur());
  la_zone_Cl_PolyMAC = ref_cast(Zone_Cl_PolyMAC, zone_Cl_dis.valeur());
}
DoubleTab & Terme_Source_Qdm_Face_PolyMAC::calculer (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 111 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
References ajouter().
{
  resu = 0;
  return ajouter(resu);
}
Objet_U * Terme_Source_Qdm_Face_PolyMAC::cree_instance () [static]
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
int Terme_Source_Qdm_Face_PolyMAC::duplique () const [virtual]
Implements Source_base.
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
const Type_info * Terme_Source_Qdm_Face_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
const Type_info * Terme_Source_Qdm_Face_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
void Terme_Source_Qdm_Face_PolyMAC::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 117 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
References Terme_Source_Qdm::la_source, and Champ_Don::mettre_a_jour().
{
  la_source->mettre_a_jour(temps);
}
Sortie & Terme_Source_Qdm_Face_PolyMAC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_Qdm_Face_PolyMAC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 55 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
References Cerr, Objet_U::dimension, Process::exit(), finl, Terme_Source_Qdm::la_source, and Objet_U::que_suis_je().
{
  s >> la_source;
  if (la_source->nb_comp() != dimension)
    {
      Cerr << "Erreur a la lecture du terme source de type " << que_suis_je() << finl;
      Cerr << "le champ source doit avoir " << dimension << " composantes" << finl;
      exit();
    }
  return s ;
}
Terme_Source_Qdm_Face_PolyMAC & Terme_Source_Qdm_Face_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
const Terme_Source_Qdm_Face_PolyMAC & Terme_Source_Qdm_Face_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
unsigned Terme_Source_Qdm_Face_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 39 of file Terme_Source_Qdm_Face_PolyMAC.cpp.
Member Data Documentation
const Type_info Terme_Source_Qdm_Face_PolyMAC::info_obj [static]
Reimplemented from Source_base.
Definition at line 45 of file Terme_Source_Qdm_Face_PolyMAC.h.
Ref_Zone_Cl_PolyMAC Terme_Source_Qdm_Face_PolyMAC::la_zone_Cl_PolyMAC [protected]
Definition at line 57 of file Terme_Source_Qdm_Face_PolyMAC.h.
Referenced by ajouter(), and associer_zones().
Ref_Zone_PolyMAC Terme_Source_Qdm_Face_PolyMAC::la_zone_PolyMAC [protected]
Definition at line 56 of file Terme_Source_Qdm_Face_PolyMAC.h.
Referenced by ajouter(), and associer_zones().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Terme_Source_Qdm_Face_PolyMAC.h
src/PolyMAC/Sources/Terme_Source_Qdm_Face_PolyMAC.cpp