TRUST: Champ_front_var Class Reference
Champ_front_var Class Reference
classe Champ_front_var
Classe derivee de Champ_front_base qui represente un champ sur
une frontiere variable en espace (non uniforme).
Le DoubleTab est dimensionne au nombre de faces de la frontiere
par la methode initialiser et possede un espace virtuel.
Chaque modification du tableau de valeurs doit donc etre suivie
d'un appel a echange_espace_virtuel().
Les Champ_front_var sont classes suivant qu'ils sont
stationnaires (Champ_front_var_stationnaire) ou non<br>(Champ_front_var_instationnaire).
Dans le premier cas, le tableau de valeurs est rempli une fois
pour toutes par la methode initialiser. Dans le deuxieme, il
est aussi recalcule a chaque appel a mettre_a_jour.
#include <Champ_front_var.h>
Public Member Functions
Champ_front_var ()
~Champ_front_var ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Detailed Description
classe Champ_front_var
Classe derivee de Champ_front_base qui represente un champ sur
une frontiere variable en espace (non uniforme).
Le DoubleTab est dimensionne au nombre de faces de la frontiere
par la methode initialiser et possede un espace virtuel.
Chaque modification du tableau de valeurs doit donc etre suivie
d'un appel a echange_espace_virtuel().
Les Champ_front_var sont classes suivant qu'ils sont
stationnaires (Champ_front_var_stationnaire) ou non<br>(Champ_front_var_instationnaire).
Dans le premier cas, le tableau de valeurs est rempli une fois
pour toutes par la methode initialiser. Dans le deuxieme, il
est aussi recalcule a chaque appel a mettre_a_jour.
Definition at line 48 of file Champ_front_var.h.
Constructor & Destructor Documentation
Champ_front_var::Champ_front_var ()
Definition at line 26 of file Champ_front_var.cpp.
Champ_front_var::~Champ_front_var ()
Definition at line 26 of file Champ_front_var.cpp.
Member Function Documentation
virtual int Champ_front_var::duplique () const [pure virtual]
Implements Champ_front_base.
Implemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
const Type_info * Champ_front_var::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 26 of file Champ_front_var.cpp.
const Type_info * Champ_front_var::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 26 of file Champ_front_var.cpp.
int Champ_front_var::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Ch_front_input, Ch_front_Vortex, Champ_front_calc, Champ_front_debit, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Champ_front_var_instationnaire, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, and Champ_front_tangentiel_VEF.
Definition at line 88 of file Champ_front_var.cpp.
References Frontiere::creer_tableau_faces(), DoubleTab::dimension(), DoubleVect::echange_espace_virtuel(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Champ_front_base::les_valeurs, Field_base::nb_comp(), and DoubleTab::resize().
Referenced by Champ_front_softanalytique::initialiser(), Champ_front_var_instationnaire::initialiser(), Champ_front_lu::initialiser(), Champ_front_fonc_pois_tube::initialiser(), and Champ_front_fonc_pois_ipsn::initialiser().
{
  const Frontiere& frontiere = frontiere_dis().frontiere();
  const int n = les_valeurs->nb_cases();
  const int nbc = nb_comp();
  for(int i = 0; i < n; i++)
    {
      DoubleTab& tab = les_valeurs[i].valeurs();
// B.M. la methode completer dimensionne parfois le tableau.
// On a un peut tout et n'importe quoi en entree: parfois tableau vide,
// parfois nb_dim==1, etc...
// Attention, les valeurs existantes doivent etre conservees s'il y en a !
      tab.resize(tab.dimension(0), nbc);
      frontiere.creer_tableau_faces(tab);
      tab.echange_espace_virtuel();
    }
  return 1;
}
Sortie & Champ_front_var::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 43 of file Champ_front_var.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_front_var::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 65 of file Champ_front_var.cpp.
References Field_base::fixer_nb_comp().
{
  fixer_nb_comp(1);
  return s ;
}
const Champ_front_var & Champ_front_var::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 26 of file Champ_front_var.cpp.
Champ_front_var & Champ_front_var::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 26 of file Champ_front_var.cpp.
Member Data Documentation
const Type_info Champ_front_var::info_obj [static]
Reimplemented from Champ_front_base.
Reimplemented in Boundary_field_inward, Champ_front_normal_VEF, Ch_front_input, Ch_front_Vortex, Champ_front_bruite, Champ_front_calc, Champ_front_calc_interne, Champ_front_debit, Champ_front_debit_massique, Champ_front_fonc, Champ_front_fonc_gradient, Champ_front_fonc_pois_ipsn, Champ_front_fonc_pois_tube, Champ_Front_Fonction, Champ_front_lu, Champ_front_normal, Champ_front_t, Champ_front_tangentiel, Champ_front_txyz, Champ_front_xyz_debit, Ch_front_input_P1, Ch_front_var_instationnaire_dep, Ch_front_var_instationnaire_indep, Ch_front_var_stationnaire, Champ_front_var_instationnaire, Champ_front_MED, Champ_front_recyclage, Champ_front_softanalytique, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 50 of file Champ_front_var.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_front_var.h
src/Kernel/Framework/Champ_front_var.cpp