TRUST: Op_Grad_P0_to_Face Class Reference
Op_Grad_P0_to_Face Class Reference
class Op_Grad_P0_to_Face
Cette classe represente l'operateur de gradient
La discretisation est VDF. On calcule le gradient d'un champ_P0 (autre que la pression)
et le champ de sortie est aux Faces
#include <Op_Grad_P0_to_Face.h>
Public Member Functions
Op_Grad_P0_to_Face ()
~Op_Grad_P0_to_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
Public Member Functions inherited from Op_Grad_VDF_Face_base
Op_Grad_VDF_Face_base ()
~Op_Grad_VDF_Face_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int has_interface_blocs () const override
Zone_VDF & zone_VDF ()
const Zone_VDF & zone_VDF () const
Zone_Cl_VDF & zone_Cl_VDF ()
const Zone_Cl_VDF & zone_Cl_VDF () const
int & face_voisins_ (int i, int j)
const int & face_voisins_ (int i, int j) const
double volume_entrelaces_ (int i)
const double & volume_entrelaces_ (int i) const
double porosite_surf_ (int i)
const double & porosite_surf_ (int i) const
int orientation_ (int face)
const int & orientation_ (int face) const
double xp_ (int elem, int ori)
const double & xp_ (int elem, int ori) const
Public Member Functions inherited from Operateur_Grad_base
Operateur_Grad_base ()
~Operateur_Grad_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
virtual DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
Calcul sans les conditions aux limites ?
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_P0_to_Face & self_cast (Objet_U &)
static const Op_Grad_P0_to_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Grad_VDF_Face_base
static const Type_info * info ()
static Op_Grad_VDF_Face_base & self_cast (Objet_U &)
static const Op_Grad_VDF_Face_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Grad_base
static const Type_info * info ()
static Operateur_Grad_base & self_cast (Objet_U &)
static const Operateur_Grad_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Grad_VDF_Face_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Grad_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Grad_VDF_Face_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Op_Grad_VDF_Face_base
Ref_Zone_VDF la_zone_vdf
Ref_Zone_Cl_VDF la_zcl_vdf
IntVect orientation
IntTab face_voisins
DoubleVect porosite_surf
DoubleVect volume_entrelaces
DoubleTab xp
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Grad_P0_to_Face
Cette classe represente l'operateur de gradient
La discretisation est VDF. On calcule le gradient d'un champ_P0 (autre que la pression)
et le champ de sortie est aux Faces
Definition at line 26 of file Op_Grad_P0_to_Face.h.
Constructor & Destructor Documentation
Op_Grad_P0_to_Face()
Op_Grad_P0_to_Face::Op_Grad_P0_to_Face ()
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
~Op_Grad_P0_to_Face()
Op_Grad_P0_to_Face::~Op_Grad_P0_to_Face ()
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Grad_P0_to_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
< Correction periodicite
Reimplemented from Operateur_base.
Definition at line 34 of file Op_Grad_P0_to_Face.cpp.
{
  statistiques().begin_count(gradient_counter_);
  const DoubleTab& inco = semi_impl.count("pression") ? semi_impl.at("pression") : equation().inconnue().valeur().valeurs();
  assert_espace_virtuel_vect(inco);
  const Zone_VDF& zvdf = la_zone_vdf.valeur();
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
  const DoubleVect& face_surfaces = zvdf.face_surfaces();
  double dist;
  int n0, n1, ori;
// Boucle sur les bords pour traiter les conditions aux limites
  for (int n_bord = 0; n_bord<zvdf.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zclvdf.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur())) //!< Correction periodicite
        {
          for (int num_face = ndeb; num_face < nfin; num_face++)
            {
              n0 = face_voisins(num_face,0), n1 = face_voisins(num_face,1);
              dist = volume_entrelaces(num_face) / face_surfaces(num_face);
              secmem(num_face) += ((inco(n1) - inco(n0)))/dist;
            }
        }
      else
        {
          for (int num_face = ndeb; num_face < nfin; num_face++)
            {
              n0 = face_voisins(num_face,0);
              if (n0<0) n0 = face_voisins(num_face,1);
              ori = orientation(num_face);
              int face_opposee = zvdf.elem_faces(n0,ori);
              if (face_opposee == num_face) face_opposee = zvdf.elem_faces(n0,ori+dimension);
              n1 = face_voisins(face_opposee,0);
              if (n1==n0) n1 = face_voisins(face_opposee,1);
              secmem(num_face) += (inco(n1)-inco(n0)) / (xp(n1,ori)- xp(n0,ori));
            }
        }
    }
// Boucle sur les faces internes
  for (int num_face = zvdf.premiere_face_int(); num_face < zvdf.nb_faces(); num_face++)
    {
      n0 = face_voisins(num_face,0), n1 = face_voisins(num_face,1), ori = orientation(num_face);
      secmem(num_face) += (inco(n1)-inco(n0))/(xp(n1,ori)- xp(n0,ori));
    }
  secmem.echange_espace_virtuel();
  statistiques().end_count(gradient_counter_);
}
References assert_espace_virtuel_vect(), Statistiques::begin_count(), Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Statistiques::end_count(), MorEqn::equation(), Zone_VF::face_surfaces(), Op_Grad_VDF_Face_base::face_voisins, Cond_lim::frontiere_dis(), gradient_counter_, Equation_base::inconnue(), Op_Grad_VDF_Face_base::la_zcl_vdf, Op_Grad_VDF_Face_base::la_zone_vdf, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Op_Grad_VDF_Face_base::orientation, Zone_VF::premiere_face_int(), ref_cast, statistiques(), sub_type, Deriv_Champ_Inc_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), Champ_Inc_base::valeurs(), Op_Grad_VDF_Face_base::volume_entrelaces, and Op_Grad_VDF_Face_base::xp.
cree_instance()
Objet_U * Op_Grad_P0_to_Face::cree_instance () static
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
dimensionner_blocs()
void Op_Grad_P0_to_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
Definition at line 29 of file Op_Grad_P0_to_Face.cpp.
{
  return;
}
duplique()
int Op_Grad_P0_to_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
get_info()
const Type_info * Op_Grad_P0_to_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
info()
const Type_info * Op_Grad_P0_to_Face::info () static
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
printOn()
Sortie & Op_Grad_P0_to_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 26 of file Op_Grad_P0_to_Face.cpp.
{ return s << que_suis_je(); }
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_P0_to_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 27 of file Op_Grad_P0_to_Face.cpp.
{ return s; }
self_cast() [1/2]
const Op_Grad_P0_to_Face & Op_Grad_P0_to_Face::self_cast (const Objet_U & r) static
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
self_cast() [2/2]
Op_Grad_P0_to_Face & Op_Grad_P0_to_Face::self_cast (Objet_U & r) static
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
taille_memoire()
unsigned Op_Grad_P0_to_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Op_Grad_P0_to_Face.cpp.
Member Data Documentation
info_obj
const Type_info Op_Grad_P0_to_Face::info_obj static
Definition at line 28 of file Op_Grad_P0_to_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Divers/Op_Grad_P0_to_Face.h
src/VDF/Operateurs/Op_Divers/Op_Grad_P0_to_Face.cpp