TRUST: Eval_centre_VDF_Elem Class Reference
Eval_centre_VDF_Elem Class Reference
class Eval_centre_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Centre
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
#include <Eval_centre_VDF_Elem.h>
Public Member Functions
Eval_centre_VDF_Elem ()
int calculer_flux_faces_echange_externe_impose () const
int calculer_flux_faces_echange_global_impose () const
int calculer_flux_faces_entree_fluide () const
int calculer_flux_faces_paroi () const
int calculer_flux_faces_paroi_adiabatique () const
int calculer_flux_faces_paroi_defilante () const
int calculer_flux_faces_paroi_fixe () const
int calculer_flux_faces_sortie_libre () const
int calculer_flux_faces_symetrie () const
int calculer_flux_faces_periodique () const
int calculer_flux_faces_NSCBC () const
double flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double flux_face (const DoubleTab &, int, const Echange_global_impose &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi &, int) const
double flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double flux_face (const DoubleTab &, int, const Symetrie &, int) const
double flux_face (const DoubleTab &, int, const Periodique &, int) const
double flux_face (const DoubleTab &, int, const NSCBC &, int) const
double flux_faces_interne (const DoubleTab &, int) const
void flux_face (const DoubleTab &, int, const Symetrie &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Periodique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_sortie_libre &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_entree_fluide &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Neumann_paroi &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, int, int, const Echange_externe_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const Echange_global_impose &, int, DoubleVect &flux) const
void flux_face (const DoubleTab &, int, const NSCBC &, int, DoubleVect &flux) const
void flux_faces_interne (const DoubleTab &, int, DoubleVect &flux) const
void coeffs_face (int, int, const Symetrie &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, double &aii, double &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, double &aii, double &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, double &aii, double &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, double &aii, double &ajj) const
void coeffs_face (int, int, const Periodique &, double &aii, double &ajj) const
void coeffs_face (int, int, const NSCBC &, double &aii, double &ajj) const
void coeffs_faces_interne (int, double &aii, double &ajj) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_entree_fluide &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_defilante &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Dirichlet_paroi_fixe &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, int, int, const Echange_externe_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Echange_global_impose &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_paroi_adiabatique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Neumann_sortie_libre &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Symetrie &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const Periodique &, int) const
double coeffs_face_bloc_vitesse (const DoubleTab &, int, const NSCBC &, int) const
double coeffs_faces_interne_bloc_vitesse (const DoubleTab &, int) const
double secmem_face (int, const Symetrie &, int) const
double secmem_face (int, const Neumann_sortie_libre &, int) const
double secmem_face (int, const Dirichlet_entree_fluide &, int) const
double secmem_face (int, const Dirichlet_paroi_fixe &, int) const
double secmem_face (int, const Dirichlet_paroi_defilante &, int) const
double secmem_face (int, const Neumann_paroi_adiabatique &, int) const
double secmem_face (int, const Neumann_paroi &, int) const
double secmem_face (int, int, int, const Echange_externe_impose &, int) const
double secmem_face (int, const Echange_global_impose &, int) const
double secmem_face (int, const Periodique &, int) const
double secmem_face (int, const NSCBC &, int) const
double secmem_faces_interne (int) const
void coeffs_face (int, int, const Symetrie &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_sortie_libre &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_entree_fluide &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_fixe &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Dirichlet_paroi_defilante &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi_adiabatique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Neumann_paroi &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, int, int, const Echange_externe_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Echange_global_impose &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const Periodique &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_face (int, int, const NSCBC &, DoubleVect &aii, DoubleVect &ajj) const
void coeffs_faces_interne (int, DoubleVect &aii, DoubleVect &ajj) const
void secmem_face (int, const Symetrie &, int, DoubleVect &) const
void secmem_face (int, const Neumann_sortie_libre &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_entree_fluide &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_fixe &, int, DoubleVect &) const
void secmem_face (int, const Dirichlet_paroi_defilante &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi_adiabatique &, int, DoubleVect &) const
void secmem_face (int, const Neumann_paroi &, int, DoubleVect &) const
void secmem_face (int, int, int, const Echange_externe_impose &, int, DoubleVect &) const
void secmem_face (int, const Echange_global_impose &, int, DoubleVect &) const
void secmem_face (int, const Periodique &, int, DoubleVect &) const
void secmem_face (int, const NSCBC &, int, DoubleVect &) const
void secmem_faces_interne (int, DoubleVect &) const
Protected Member Functions
double dim_elem (int, int) const
double dist_elem (int, int, int) const
int amont_amont (int, int) const
double dist_face_elem1 (int, int) const
double qcentre (const double &, const int, const int, const int, const int, const int, const DoubleTab &) const
void qcentre (const double &, const int, const int, const int, const int, const int, const DoubleTab &, ArrOfDouble &) const
Detailed Description
class Eval_centre_VDF_Elem
Evaluateur VDF pour la convection
Le champ convecte est scalaire (Champ_P0_VDF)
Schema de convection Centre
Rq:Les evaluateurs de flux convectifs calculent en fait le terme
convectif qui figure au second membre de l'equation d'evolution
c.a.d l'oppose du flux convectif
See also:
Eval_Conv_VDF
Definition at line 46 of file Eval_centre_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_centre_VDF_Elem::Eval_centre_VDF_Elem () [inline]
Definition at line 214 of file Eval_centre_VDF_Elem.h.
{
}
Member Function Documentation
int Eval_centre_VDF_Elem::amont_amont (int face, int i) const [inline, protected]
Definition at line 1419 of file Eval_centre_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
Referenced by coeffs_face(), coeffs_face_bloc_vitesse(), coeffs_faces_interne(), coeffs_faces_interne_bloc_vitesse(), flux_face(), and flux_faces_interne().
{
  return la_zone->amont_amont(face, i);
}
int Eval_centre_VDF_Elem::calculer_flux_faces_echange_externe_impose () const [inline]
Definition at line 222 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_echange_global_impose () const [inline]
Definition at line 231 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_entree_fluide () const [inline]
Definition at line 240 of file Eval_centre_VDF_Elem.h.
{
  return 1;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_NSCBC () const [inline]
Definition at line 311 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_paroi () const [inline]
Definition at line 249 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_paroi_adiabatique () const [inline]
Definition at line 258 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_paroi_defilante () const [inline]
Definition at line 267 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_paroi_fixe () const [inline]
Definition at line 276 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_periodique () const [inline]
Definition at line 302 of file Eval_centre_VDF_Elem.h.
{
  return 1;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_sortie_libre () const [inline]
Definition at line 285 of file Eval_centre_VDF_Elem.h.
{
  return 1;
}
int Eval_centre_VDF_Elem::calculer_flux_faces_symetrie () const [inline]
Definition at line 294 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Symetrie & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 718 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Symetrie & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1231 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int face, int num1, const Neumann_sortie_libre & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 1174 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        for(k=0; k<aii.size(); k++)
          aii(k) = -psc;
    }
  else   //!< n1 != -1
    {
      if (psc < 0)
        for(k=0; k<ajj.size(); k++)
          ajj(k) = -psc;
    }
}
void Eval_centre_VDF_Elem::coeffs_face (int face, int num1, const Neumann_sortie_libre & la_cl, double & aii, double & ajj) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 640 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        aii = -psc;
    }
  else   //!< n1 != -1
    {
      if (psc < 0)
        ajj = -psc;
    }
}
void Eval_centre_VDF_Elem::coeffs_face (int face, int num1, const Dirichlet_entree_fluide & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 934 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc > 0)
        for(k=0; k<aii.size(); k++)
          aii(k) = -psc;
    }
  else   //!< j != -1
    {
      if (psc < 0)
        for(k=0; k<ajj.size(); k++)
          ajj(k) = -psc;
    }
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1018 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int face, int num1, const Dirichlet_entree_fluide & la_cl, double & aii, double & ajj) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 352 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, and Evaluateur_VDF::surface.
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if (i != -1)
    {
      if (psc > 0)
        aii = -psc;
    }
  else   //!< j != -1
    {
      if (psc<0)
        ajj = -psc;
    }
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 991 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const NSCBC & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Definition at line 1259 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1126 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 466 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Neumann_paroi & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1099 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1045 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 435 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Echange_global_impose & , DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1072 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int face, int , const Periodique & la_cl, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1297 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Eval_VDF_Elem::inconnue, Evaluateur_VDF::porosite, qcentre(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int i = elem_(face,0);
  int j = elem_(face,1);
  int i0_0 = amont_amont(face,0);
  int j1_1 = amont_amont(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  ArrOfDouble flux(aii.size());
// on applique le schema centre2
  qcentre(psc,i,j,i0_0,j1_1,face,inconnue->valeurs(),flux);
  if (psc > 0)
    for (k=0; k<aii.size(); k++)
      aii(k) = -flux(k);
  else
    for (k=0; k<ajj.size(); k++)
      ajj(k) = -flux(k);
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 591 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Neumann_paroi & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 560 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 498 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const Echange_global_impose & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 529 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::coeffs_face (int face, int , const Periodique & la_cl, double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 791 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Eval_VDF_Elem::inconnue, Evaluateur_VDF::porosite, qcentre(), and Evaluateur_VDF::surface.
{
// 30/05/2002 : Codage Periodicite.
// // ALEX C.
  int i = elem_(face,0);
  int j = elem_(face,1);
  int i0_0 = amont_amont(face,0);
  int j1_1 = amont_amont(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
// on applique le schema centre
  if (psc > 0)
    aii = -qcentre(psc,i,j,i0_0,j1_1,face,inconnue->valeurs());
  else
    ajj = -qcentre(psc,i,j,i0_0,j1_1,face,inconnue->valeurs());
}
void Eval_centre_VDF_Elem::coeffs_face (int , int , const NSCBC & , double & aii, double & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 750 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 371 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  double psc = surface(face)*porosite(face);
  double T_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (dt_vitesse[face] > 0)
        flux= psc*inco[n0];
      else
        flux= psc*T_imp;
    }
  else   //!< n1 != -1
    {
      if (dt_vitesse[face]>0)
        flux= psc*T_imp;
      else
        flux= psc*inco[n1];
    }
  return flux;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 440 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 471 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 503 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Echange_global_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 534 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 565 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 596 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< n1 != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 658 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  double psc = surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (dt_vitesse[face] > 0)
        flux= psc*inco[n0];
      else
        flux= psc*la_cl.val_ext(face-num1);
    }
  else   //!< n1 != -1
    {
      if (dt_vitesse[face] > 0)
        flux=psc*la_cl.val_ext(face-num1);
      else
        flux= psc*inco[n1];
    }
  return flux;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Symetrie & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 723 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 808 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, qcentre(), and Evaluateur_VDF::surface.
{
// 30/05/2002 : Codage Periodicite.
// ALEX C.
  double flux;
  double psc = surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
// on applique le schema centre2
  flux = qcentre(psc,n0,n1,n0_0,n1_1,face,inco);
  return flux;
}
double Eval_centre_VDF_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const NSCBC & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 755 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::coeffs_faces_interne (int face, DoubleVect & aii, DoubleVect & ajj) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1358 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Eval_VDF_Elem::inconnue, Evaluateur_VDF::porosite, qcentre(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  int i = elem_(face,0);
  int j = elem_(face,1);
  int i0_0 = amont_amont(face,0);
  int j1_1 = amont_amont(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  ArrOfDouble flux(aii.size());
  /*   if ( (i0_0 == -1) || (j1_1 == -1) ) //!< on applique le schema amont  */
  /*     if (psc > 0) */
  /*       for (k=0; k<aii.size(); k++) */
  /*         aii(k) = -psc; */
  /*     else */
  /*       for (k=0; k<ajj.size(); k++) */
  /*         ajj(k) = -psc; */
  /*   else  //!< on applique le schema centre_Fram4 */
  /*     { */
  qcentre(psc,i,j,i0_0,j1_1,face,inconnue->valeurs(),flux);
  if (psc > 0)
    for (k=0; k<aii.size(); k++)
      aii(k) = -flux(k);
  else
    for (k=0; k<ajj.size(); k++)
      ajj(k) = -flux(k);
  /*     } */
}
void Eval_centre_VDF_Elem::coeffs_faces_interne (int face, double & aii, double & ajj) const [inline]
< on applique le schema amont
< on applique le schema centre
Reimplemented from Eval_VDF_Elem.
Definition at line 852 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Eval_VDF_Elem::inconnue, Evaluateur_VDF::porosite, qcentre(), and Evaluateur_VDF::surface.
{
  int i = elem_(face,0);
  int j = elem_(face,1);
  int i0_0 = amont_amont(face,0);
  int j1_1 = amont_amont(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  if ( (i0_0 == -1) || (j1_1 == -1) ) //!< on applique le schema amont
    if (psc > 0)
      aii = -psc;
    else
      ajj = -psc;
  else  //!< on applique le schema centre
    if (psc > 0)
      aii = -qcentre(psc,i,j,i0_0,j1_1,face,inconnue->valeurs());
    else
      ajj = -qcentre(psc,i,j,i0_0,j1_1,face,inconnue->valeurs());
}
double Eval_centre_VDF_Elem::coeffs_faces_interne_bloc_vitesse (const DoubleTab & inco, int face) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 873 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, qcentre(), and Evaluateur_VDF::surface.
{
  double flux;
  double psc = surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
  flux = qcentre(psc,n0,n1,n0_0,n1_1,face,inco);
  return flux;
}
double Eval_centre_VDF_Elem::dim_elem (int n1, int k) const [inline, protected]
Definition at line 1494 of file Eval_centre_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
{
  return la_zone->dim_elem(n1,k);
}
double Eval_centre_VDF_Elem::dist_elem (int n1, int n2, int k) const [inline, protected]
Definition at line 1500 of file Eval_centre_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
{
  return la_zone->dist_elem(n1,n2,k);
}
double Eval_centre_VDF_Elem::dist_face_elem1 (int num_face, int n1) const [inline, protected]
Definition at line 1505 of file Eval_centre_VDF_Elem.h.
References Evaluateur_VDF::la_zone.
{
  return la_zone->dist_face_elem1(num_face, n1);
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< n1 != -1
Definition at line 323 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  double T_imp = la_cl.val_imp(face-num1);
  if (n0 != -1)
    {
      if (psc > 0)
        flux= psc*inco[n0];
      else
        flux= psc*T_imp;
    }
  else   //!< n1 != -1
    {
      if (psc>0)
        flux= psc*T_imp;
      else
        flux= psc*inco[n1];
    }
  return -flux;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int) const [inline]
Definition at line 520 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int , DoubleVect & flux) const [inline]
Definition at line 1035 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int , DoubleVect & flux) const [inline]
Definition at line 1062 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int) const [inline]
Definition at line 551 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const NSCBC & , int , DoubleVect & flux) const [inline]
Definition at line 1249 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const [inline]
Definition at line 582 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int) const [inline]
Definition at line 708 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< n1 != -1
Definition at line 613 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        flux= psc*inco[n0];
      else
        flux= psc*la_cl.val_ext(face-num1);
    }
  else   //!< n1 != -1
    {
      if (psc > 0)
        flux=psc*la_cl.val_ext(face-num1);
      else
        flux= psc*inco[n1];
    }
  return -flux;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int , DoubleVect & flux) const [inline]
Definition at line 1221 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int) const [inline]
Definition at line 772 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, qcentre(), and Evaluateur_VDF::surface.
{
// 30/05/2002 : Codage Periodicite.
// ALEX C.
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
// on applique le schema centre2
  flux = qcentre(psc,n0,n1,n0_0,n1_1,face,inco);
  return -flux;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const NSCBC & , int) const [inline]
Definition at line 740 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int , DoubleVect & flux) const [inline]
Definition at line 1276 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, qcentre(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
// on applique le schema centre
  qcentre(psc,n0,n1,n0_0,n1_1,face,inco,flux);
  for (k=0; k<flux.size(); k++)
    flux(k) *= -1;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Definition at line 1143 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
    }
  else  //!< n1 != -1
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n1,k);
    }
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const [inline]
Definition at line 425 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
< n1 != -1
Definition at line 902 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int k;
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  double psc = dt_vitesse(face)*surface(face)*porosite(face);
  if (n0 != -1)
    {
      if (psc > 0)
        for (k=0; k<flux.size(); k++)
          flux(k) = -psc*inco(n0,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k)= -psc*la_cl.val_imp(face-num1,k);
    }
  else //!< n1 != -1
    {
      if (psc>0)
        for (k=0; k<flux.size(); k++)
          flux(k)= -psc*la_cl.val_imp(face-num1,k);
      else
        for (k=0; k<flux.size(); k++)
          flux(k)= -psc*inco(n1,k);
    }
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const [inline]
Definition at line 1008 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const [inline]
Definition at line 457 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const [inline]
Definition at line 981 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const [inline]
Definition at line 489 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int , DoubleVect & flux) const [inline]
Definition at line 1116 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int , DoubleVect & flux) const [inline]
Definition at line 1089 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const [inline]
Definition at line 1330 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, qcentre(), DoubleVect::size(), and Evaluateur_VDF::surface.
{
  int k;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
  /*   if ( (n0_0 == -1) || (n1_1 == -1) ) //!< on applique le schema amont */
  /*     if (psc > 0) */
  /*       for (k=0; k<flux.size(); k++) */
  /*         flux(k) = -psc*inco(n0,k); */
  /*     else */
  /*       for (k=0; k<flux.size(); k++) */
  /*         flux(k) = -psc*inco(n1,k); */
  /*   else //!< on applique le schema centre */
  /*     { */
  qcentre(psc,n0,n1,n0_0,n1_1,face,inco,flux);
  for (k=0; k<flux.size(); k++)
    flux(k) *= -1;
  /*     } */
}
double Eval_centre_VDF_Elem::flux_faces_interne (const DoubleTab & inco, int face) const [inline]
Definition at line 836 of file Eval_centre_VDF_Elem.h.
References amont_amont(), Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, qcentre(), and Evaluateur_VDF::surface.
{
  double flux;
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  int n0 = elem_(face,0);
  int n1 = elem_(face,1);
  int n0_0 = amont_amont(face,0);
  int n1_1 = amont_amont(face,1);
  flux = qcentre(psc,n0,n1,n0_0,n1_1,face,inco);
  return -flux;
}
void Eval_centre_VDF_Elem::qcentre (const double & psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte, ArrOfDouble & flux) const [inline, protected]
Definition at line 1454 of file Eval_centre_VDF_Elem.h.
References ArrOfDouble::size_array().
{
  int k;
  int ncomp = flux.size_array();
// int ori = orientation(face);
// double dx = dist_elem(num0, num1, ori);
// double dxam=dist_elem(num0_0, num0, ori);
// double dxav=dist_elem(num1, num1_1, ori);
  ArrOfDouble T0(ncomp);
  ArrOfDouble T1(ncomp);
  for (k=0; k<ncomp; k++)
    {
      T0(k) = transporte(num0,k);
      T1(k) = transporte(num1,k);
    }
// double g1 = -dx*dx*(dx/2+dxav)/(4*(dx+dxam+dxav)*(dx+dxam)*dxam);
// double g2 =  (dx+2*dxam)*(dx+2*dxav)/(8*dxam*(dx+dxav));
// double g3 = (dx+2*dxam)*(dx+2*dxav)/(8*dxav*(dx+dxam));
// double g4 = -dx*dx*(dx/2+dxam)/(4*(dx+dxam+dxav)*dxav*(dx+dxav));
  for (k=0; k<ncomp; k++)
    {
      flux(k) =0.5*(  T0(k) + T1(k))   *   psc ;
    }
// On applique le filtre Fram4:
// for (k=0; k<ncomp; k++)
// {
// fr = Fram4(T0_0(k),T0(k),T1(k),T1_1(k));
// flux(k) = ((1.-fr)*flux(k) + fr*trans_amont(k))*psc;
}
double Eval_centre_VDF_Elem::qcentre (const double & psc, const int num0, const int num1, const int num0_0, const int num1_1, const int face, const DoubleTab & transporte) const [inline, protected]
Definition at line 1428 of file Eval_centre_VDF_Elem.h.
Referenced by coeffs_face(), coeffs_face_bloc_vitesse(), coeffs_faces_interne(), coeffs_faces_interne_bloc_vitesse(), flux_face(), and flux_faces_interne().
{
  double flux;
// int ori = orientation(face);
  double T0 = transporte[num0];
  double T1 = transporte[num1];
  flux =  0.5*(T0+T1);
// On applique le filtre Fram4:
// fr = Fram4(T0_0,T0,T1,T1_1);
// flux = ((1.-fr)*flux + fr*trans_amont)*psc;
  return flux*psc;
}
double Eval_centre_VDF_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 449 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 605 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Neumann_paroi & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1107 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 1198 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1);
    }
  else   //!< j != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_ext(face-num1);
    }
}
double Eval_centre_VDF_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 686 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Neumann_sortie_libre::val_ext().
{
  double flux=0;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*la_cl.val_ext(face-num1);
    }
  else   //!< j != -1
    {
      if (psc > 0)
        flux = psc*la_cl.val_ext(face-num1);
    }
  return -flux;
}
double Eval_centre_VDF_Elem::secmem_face (int , const Neumann_paroi & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 574 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::secmem_face (int , const NSCBC & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 764 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Symetrie & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1239 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Periodique & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1321 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::secmem_face (int , const NSCBC & , int , DoubleVect &) const [inline]
Definition at line 1267 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::secmem_face (int , const Periodique & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 828 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
double Eval_centre_VDF_Elem::secmem_face (int , const Symetrie & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 732 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Echange_global_impose & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1080 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 480 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 999 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1053 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 512 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1026 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 401 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface[face]*porosite[face];
  double flux=0;
  double T_imp = la_cl.val_imp(face-num1);
  if (i != -1)
    {
      if (psc < 0)
        flux = psc*T_imp;
    }
  else   //!< j != -1
    {
      if (psc>0)
        flux = psc*T_imp;
    }
  return -flux;
}
void Eval_centre_VDF_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1134 of file Eval_centre_VDF_Elem.h.
{
  ;
}
void Eval_centre_VDF_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const [inline]
< j != -1
Reimplemented from Eval_VDF_Elem.
Definition at line 958 of file Eval_centre_VDF_Elem.h.
References Eval_Conv_VDF::dt_vitesse, Evaluateur_VDF::elem_, Evaluateur_VDF::porosite, DoubleVect::size(), Evaluateur_VDF::surface, and Dirichlet::val_imp().
{
  int k;
  int i = elem_(face,0);
// int j = elem(face,1);
  double psc = dt_vitesse[face]*surface(face)*porosite(face);
  if (i != -1)
    {
      if (psc < 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1);
    }
  else   //!< j != -1
    {
      if (psc > 0)
        for(k=0; k<flux.size(); k++)
          flux(k) = -psc*la_cl.val_imp(face-num1);
    }
}
double Eval_centre_VDF_Elem::secmem_face (int , const Echange_global_impose & , int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 543 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
void Eval_centre_VDF_Elem::secmem_faces_interne (int , DoubleVect &) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 1392 of file Eval_centre_VDF_Elem.h.
{
  ;
}
double Eval_centre_VDF_Elem::secmem_faces_interne (int) const [inline]
Reimplemented from Eval_VDF_Elem.
Definition at line 889 of file Eval_centre_VDF_Elem.h.
{
  return 0;
}
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs/Eval_centre_VDF_Elem.h