TRUST: Terme_Source_PolyMAC_base Class Reference
Terme_Source_PolyMAC_base Class Reference
PolyMAC implementation of Source_base class.
#include <Terme_Source_PolyMAC_base.h>
Public Member Functions
Terme_Source_PolyMAC_base ()
~Terme_Source_PolyMAC_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Source_PolyMAC_base (const Iterateur_Source_PolyMAC_base &)
constructeur
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Terme_Source_PolyMAC_base & self_cast (Objet_U &)
static const
Terme_Source_PolyMAC_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
Iterateur_Source_PolyMAC iter
Detailed Description
PolyMAC implementation of Source_base class.
Definition at line 38 of file Terme_Source_PolyMAC_base.h.
Constructor & Destructor Documentation
Terme_Source_PolyMAC_base::Terme_Source_PolyMAC_base ()
Definition at line 25 of file Terme_Source_PolyMAC_base.cpp.
Terme_Source_PolyMAC_base::~Terme_Source_PolyMAC_base ()
Definition at line 25 of file Terme_Source_PolyMAC_base.cpp.
Terme_Source_PolyMAC_base::Terme_Source_PolyMAC_base (const Iterateur_Source_PolyMAC_base & iter_base) [inline]
constructeur
Definition at line 61 of file Terme_Source_PolyMAC_base.h.
                                                                                                          :
  iter(iter_base)
{}
Member Function Documentation
DoubleTab & Terme_Source_PolyMAC_base::ajouter (DoubleTab & resu) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 65 of file Terme_Source_PolyMAC_base.h.
References Iterateur_Source_PolyMAC::ajouter(), and iter.
{
  return iter.ajouter(resu);
}
DoubleTab & Terme_Source_PolyMAC_base::calculer (DoubleTab & resu) const [inline, virtual]
Reimplemented from Source_base.
Definition at line 70 of file Terme_Source_PolyMAC_base.h.
References Iterateur_Source_PolyMAC::calculer(), and iter.
{
  return iter.calculer(resu);
}
void Terme_Source_PolyMAC_base::completer (void) [virtual]
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 45 of file Terme_Source_PolyMAC_base.cpp.
References Iterateur_Source_PolyMAC::associer(), Iterateur_Source_PolyMAC::completer_(), and iter.
{
  Source_base::completer();
  iter.associer(*this);
  iter.completer_();
}
virtual int Terme_Source_PolyMAC_base::duplique () const [pure virtual]
Implements Source_base.
Implemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
const Type_info * Terme_Source_PolyMAC_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 25 of file Terme_Source_PolyMAC_base.cpp.
const Type_info * Terme_Source_PolyMAC_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 25 of file Terme_Source_PolyMAC_base.cpp.
Sortie & Terme_Source_PolyMAC_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 31 of file Terme_Source_PolyMAC_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_PolyMAC_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 40 of file Terme_Source_PolyMAC_base.cpp.
{
  return s ;
}
const Terme_Source_PolyMAC_base & Terme_Source_PolyMAC_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 25 of file Terme_Source_PolyMAC_base.cpp.
Terme_Source_PolyMAC_base & Terme_Source_PolyMAC_base::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 25 of file Terme_Source_PolyMAC_base.cpp.
Member Data Documentation
const Type_info Terme_Source_PolyMAC_base::info_obj [static]
Reimplemented from Source_base.
Reimplemented in Terme_Puissance_Thermique_PolyMAC_base, Terme_Puissance_Thermique_PolyMAC_Elem, and Terme_Source_Constituant_PolyMAC_Elem.
Definition at line 41 of file Terme_Source_PolyMAC_base.h.
Iterateur_Source_PolyMAC Terme_Source_PolyMAC_base::iter [protected]
Definition at line 52 of file Terme_Source_PolyMAC_base.h.
Referenced by ajouter(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_zones(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_zones(), Terme_Puissance_Thermique_PolyMAC_base::associer_zones(), calculer(), and completer().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Terme_Source_PolyMAC_base.h
src/PolyMAC/Sources/Terme_Source_PolyMAC_base.cpp