TRUST: Convection_Diffusion_Espece_Binaire_WC Class Reference
Convection_Diffusion_Espece_Binaire_WC Class Reference
classe Convection_Diffusion_Espece_Binaire_WC
Cas particulier de Convection_Diffusion_Espece_Binaire_base
pour un fluide weakly conpressible iso-therme et iso-bar
#include <Convection_Diffusion_Espece_Binaire_WC.h>
Public Member Functions
Convection_Diffusion_Espece_Binaire_WC ()
~Convection_Diffusion_Espece_Binaire_WC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual int sauvegarder (Sortie &) const
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
virtual int reprendre (Entree &)
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Convection_Diffusion_Espece_Binaire_WC & self_cast (Objet_U &)
static const
Convection_Diffusion_Espece_Binaire_WC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Equation_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
Detailed Description
classe Convection_Diffusion_Espece_Binaire_WC
Cas particulier de Convection_Diffusion_Espece_Binaire_base
pour un fluide weakly conpressible iso-therme et iso-bar
Definition at line 38 of file Convection_Diffusion_Espece_Binaire_WC.h.
Constructor & Destructor Documentation
Convection_Diffusion_Espece_Binaire_WC::Convection_Diffusion_Espece_Binaire_WC ()
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
Convection_Diffusion_Espece_Binaire_WC::~Convection_Diffusion_Espece_Binaire_WC ()
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
Member Function Documentation
void Convection_Diffusion_Espece_Binaire_WC::completer (void) [virtual]
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
< [ABN]: In case of Front-Tracking, mass solver mass might be uninitialized ...
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 41 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
References Convection_Diffusion_Fluide_Dilatable_base::le_fluide, and Objet_U::que_suis_je().
{
  assert(le_fluide->loi_etat()->que_suis_je() == "Loi_Etat_Binaire_Gaz_Parfait_WC");
  Convection_Diffusion_Espece_Binaire_base::completer();
}
Objet_U * Convection_Diffusion_Espece_Binaire_WC::cree_instance () [static]
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
int Convection_Diffusion_Espece_Binaire_WC::duplique () const [virtual]
Implements Convection_Diffusion_Espece_Binaire_base.
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
const Type_info * Convection_Diffusion_Espece_Binaire_WC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
const Type_info * Convection_Diffusion_Espece_Binaire_WC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
Sortie & Convection_Diffusion_Espece_Binaire_WC::printOn (Sortie & is) const [protected, virtual]
Simple appel a Equation_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 31 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
{
  return Convection_Diffusion_Espece_Binaire_base::printOn(is);
}
Entree & Convection_Diffusion_Espece_Binaire_WC::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 36 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
{
  return Convection_Diffusion_Espece_Binaire_base::readOn(is);
}
int Convection_Diffusion_Espece_Binaire_WC::reprendre (Entree & fich) [virtual]
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 53 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
References Convection_Diffusion_Fluide_Dilatable_base::l_inco_ch, Convection_Diffusion_Fluide_Dilatable_base::le_fluide, Equation_base::probleme(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Ref_Fluide_Dilatable_base::valeur().
{
  double temps = schema_temps().temps_courant();
  return Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(is,temps,*this, le_fluide.valeur(),l_inco_ch,probleme());
}
int Convection_Diffusion_Espece_Binaire_WC::sauvegarder (Sortie & os) const [virtual]
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Returns:
int
Signification: le code de retour de Champ_Inc::sauvegarder()
Contraintes:
Reimplemented from Convection_Diffusion_Espece_Fluide_Dilatable_base.
Definition at line 47 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
References Convection_Diffusion_Fluide_Dilatable_base::le_fluide, ref_cast_non_const, Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), and Ref_Fluide_Dilatable_base::valeur().
{
  Fluide_Weakly_Compressible& FWC = ref_cast_non_const(Fluide_Weakly_Compressible,le_fluide.valeur());
  return Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(os,*this,FWC);
}
const Convection_Diffusion_Espece_Binaire_WC & Convection_Diffusion_Espece_Binaire_WC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
Convection_Diffusion_Espece_Binaire_WC & Convection_Diffusion_Espece_Binaire_WC::self_cast (Objet_U & r) [static]
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
unsigned Convection_Diffusion_Espece_Binaire_WC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Convection_Diffusion_Espece_Binaire_WC.cpp.
Member Data Documentation
const Type_info Convection_Diffusion_Espece_Binaire_WC::info_obj [static]
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
Definition at line 40 of file Convection_Diffusion_Espece_Binaire_WC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/Equations/Convection_Diffusion_Espece_Binaire_WC.h
src/ThHyd/Dilatable/Weakly_Compressible/Equations/Convection_Diffusion_Espece_Binaire_WC.cpp