TRUST: Leap_frog Class Reference
Leap_frog Class Reference
classe Leap_frog
Cette classe represente un schema en temps Leap_Frog.
Si (n<=4)
U(n+1) = 2*dt*(dU/dt)(n) + U(n)
Si(n>4)
U(n+1) = dt*(dU/dt)(n) + gamma*U(n) + (1-2*gamma)*U(n-1)
+ gamma*U(n-2)
#include <Leap_frog.h>
Public Member Functions
Leap_frog ()
~Leap_frog ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n-2, n-1, n, et n+1, donc 4.
virtual int nb_valeurs_futures () const
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
virtual double temps_futur (int i) const
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
virtual double temps_defaut () const
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)
Effectue un pas de temps Leap_frog, sur l'equation
passee en parametre.
void completer ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Leap_frog & self_cast (Objet_U &)
static const Leap_frog & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Detailed Description
classe Leap_frog
Cette classe represente un schema en temps Leap_Frog.
Si (n<=4)
U(n+1) = 2*dt*(dU/dt)(n) + U(n)
Si(n>4)
U(n+1) = dt*(dU/dt)(n) + gamma*U(n) + (1-2*gamma)*U(n-1)
+ gamma*U(n-2)
Definition at line 42 of file Leap_frog.h.
Constructor & Destructor Documentation
Leap_frog::Leap_frog ()
Definition at line 26 of file Leap_frog.cpp.
Leap_frog::~Leap_frog ()
Definition at line 26 of file Leap_frog.cpp.
Member Function Documentation
void Leap_frog::completer (void) [inline, virtual]
Implements Schema_Temps_base.
Definition at line 70 of file Leap_frog.h.
{
}
Objet_U * Leap_frog::cree_instance () [static]
Definition at line 26 of file Leap_frog.cpp.
int Leap_frog::duplique () const [virtual]
Implements Schema_Temps_base.
Definition at line 26 of file Leap_frog.cpp.
int Leap_frog::faire_un_pas_de_temps_eqn_base (Equation_base & eq) [virtual]
Effectue un pas de temps Leap_frog, sur l'equation
passee en parametre.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Implements Schema_Temps_base.
Definition at line 138 of file Leap_frog.cpp.
References DoubleVect::ajoute(), Equation_base::derivee_en_temps_inco(), Schema_Temps_base::dt_, DoubleVect::echange_espace_virtuel(), Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Schema_Temps_base::nb_pas_dt_, Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), Champ_Inc::valeurs(), VECT_REAL_ITEMS, and Equation_base::zone_Cl_dis().
{
// EXEMPLE POUR UN SCHEMA EXPLICITE UTILISANT U(n) et U(n+1)
// Un+1=Un+dt*F
// Un
  DoubleTab& present = eq.inconnue().valeurs();
// Un+1
  DoubleTab& futur = eq.inconnue().futur();
// Un+1=F
  eq.derivee_en_temps_inco(futur);
  futur.echange_espace_virtuel();
// ECRIRE ICI LE CALCUL de U(n+1) EN FONCTION DE U(n) ET DE derivee
// futur*=dt; Un+1=dt*F
// futur+=present; Un+1=Un+dt*F
// SI IL S'AGISSAIT D'UN SCHEMA QUI FAIT INTERVENIR U(n-1)
// if ((nb_pas_dt_>4) && ((nb_pas_dt_ % 10) != 0)) {
// if (nb_pas_dt_>4) {
  if ((nb_pas_dt_>4) && ((nb_pas_dt_ % 10) != 0))
    {
      DoubleTab& passe = eq.inconnue().passe();
      double gamma=0.2;
      DoubleTab& passe2 = eq.inconnue().passe(2);
      DoubleTab& correcteur=passe;
      correcteur*=(1.-2.*gamma);
      correcteur.ajoute(gamma, present, VECT_REAL_ITEMS);
      correcteur.ajoute(gamma, passe2, VECT_REAL_ITEMS);
      futur*=(2*dt_);
      futur+=correcteur;
    }
  else
    {
      futur*=dt_;
      futur+=present;
    }
  eq.zone_Cl_dis().imposer_cond_lim(eq.inconnue(),temps_courant()+pas_de_temps());
  DoubleTab tmp(futur);
  tmp -= present;
  tmp /= dt_;
  update_critere_statio(tmp, eq);
  futur.echange_espace_virtuel();
  return 1;
}
const Type_info * Leap_frog::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Leap_frog.cpp.
const Type_info * Leap_frog::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Leap_frog.cpp.
int Leap_frog::nb_valeurs_futures () const [virtual]
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
Definition at line 92 of file Leap_frog.cpp.
{
  return 1 ;
}
int Leap_frog::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n-2, n-1, n, et n+1, donc 4.
Implements Schema_Temps_base.
Definition at line 84 of file Leap_frog.cpp.
{
  return 4;
}
Sortie & Leap_frog::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 44 of file Leap_frog.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
Entree & Leap_frog::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 65 of file Leap_frog.cpp.
{
//
// VERIFIER ICI QU'ON A BIEN TOUT LU;
//
  return Schema_Temps_base::readOn(s) ;
}
const Leap_frog & Leap_frog::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Leap_frog.cpp.
Leap_frog & Leap_frog::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Temps_base.
Definition at line 26 of file Leap_frog.cpp.
unsigned Leap_frog::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Leap_frog.cpp.
double Leap_frog::temps_defaut () const [virtual]
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 110 of file Leap_frog.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  return temps_courant()+pas_de_temps();
}
double Leap_frog::temps_futur (int i) const [virtual]
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 100 of file Leap_frog.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  assert(i==1);
  return temps_courant()+pas_de_temps();
}
Member Data Documentation
const Type_info Leap_frog::info_obj [static]
Reimplemented from Schema_Temps_base.
Definition at line 45 of file Leap_frog.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Leap_frog.h
src/Kernel/Schemas_Temps/Leap_frog.cpp