TRUST: Ref_Zone_Cl_PolyMAC Class Reference
Ref_Zone_Cl_PolyMAC Class Reference
#include <Ref_Zone_Cl_PolyMAC.h>
Public Member Functions
~Ref_Zone_Cl_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_Cl_PolyMAC ()
Ref_Zone_Cl_PolyMAC (const Zone_Cl_PolyMAC &)
Ref_Zone_Cl_PolyMAC (const Ref_Zone_Cl_PolyMAC &)
const Zone_Cl_PolyMAC & valeur () const
Zone_Cl_PolyMAC & valeur ()
const Zone_Cl_PolyMAC * operator-> () const
Zone_Cl_PolyMAC * operator-> ()
const Ref_Zone_Cl_PolyMAC & operator= (const Zone_Cl_PolyMAC &)
const Ref_Zone_Cl_PolyMAC & operator= (const Ref_Zone_Cl_PolyMAC &)
operator const Zone_Cl_PolyMAC & () const
operator Zone_Cl_PolyMAC & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_Cl_PolyMAC & self_cast (Objet_U &)
static const Ref_Zone_Cl_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_Cl_PolyMAC * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
Constructor & Destructor Documentation
Ref_Zone_Cl_PolyMAC::~Ref_Zone_Cl_PolyMAC ()
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Ref_Zone_Cl_PolyMAC::Ref_Zone_Cl_PolyMAC ()
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Ref_Zone_Cl_PolyMAC::Ref_Zone_Cl_PolyMAC (const Zone_Cl_PolyMAC & t)
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Ref_Zone_Cl_PolyMAC::Ref_Zone_Cl_PolyMAC (const Ref_Zone_Cl_PolyMAC & t)
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Member Function Documentation
Objet_U * Ref_Zone_Cl_PolyMAC::cree_instance () [static]
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
int Ref_Zone_Cl_PolyMAC::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Type_info * Ref_Zone_Cl_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Type_info & Ref_Zone_Cl_PolyMAC::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Type_info * Ref_Zone_Cl_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Ref_Zone_Cl_PolyMAC::operator const Zone_Cl_PolyMAC & () const
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Ref_Zone_Cl_PolyMAC::operator Zone_Cl_PolyMAC & ()
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Zone_Cl_PolyMAC * Ref_Zone_Cl_PolyMAC::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
Zone_Cl_PolyMAC * Ref_Zone_Cl_PolyMAC::operator-> () [inline]
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
const Ref_Zone_Cl_PolyMAC & Ref_Zone_Cl_PolyMAC::operator= (const Ref_Zone_Cl_PolyMAC & t)
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Ref_Zone_Cl_PolyMAC & Ref_Zone_Cl_PolyMAC::operator= (const Zone_Cl_PolyMAC & t)
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Sortie & Ref_Zone_Cl_PolyMAC::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Entree & Ref_Zone_Cl_PolyMAC::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Ref_Zone_Cl_PolyMAC & Ref_Zone_Cl_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
Ref_Zone_Cl_PolyMAC & Ref_Zone_Cl_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
void Ref_Zone_Cl_PolyMAC::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
unsigned Ref_Zone_Cl_PolyMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_Cl_PolyMAC.cpp.
const Zone_Cl_PolyMAC & Ref_Zone_Cl_PolyMAC::valeur () const [inline]
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
Referenced by Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Assembleur_P_PolyMAC::assembler_mat(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Grad_PolyMAC_Face::impr(), Assembleur_P_PolyMAC::modifier_secmem(), Iterateur_PolyMAC_base::zone_Cl(), Assembleur_P_PolyMAC::zone_Cl_dis_base(), and Op_Grad_PolyMAC_Face::zone_Cl_PolyMAC().
Zone_Cl_PolyMAC & Ref_Zone_Cl_PolyMAC::valeur () [inline]
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
Member Data Documentation
const Type_info Ref_Zone_Cl_PolyMAC::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
Zone_Cl_PolyMAC* Ref_Zone_Cl_PolyMAC::pointeur_ [private]
Definition at line 28 of file Ref_Zone_Cl_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/Ref_Zone_Cl_PolyMAC.h
src/PolyMAC/Zones/Ref_Zone_Cl_PolyMAC.cpp