TRUST: Champ_Generique_Predefini Class Reference
Champ_Generique_Predefini Class Reference
class Champ_Generique_Predefini
#include <Champ_Generique_Predefini.h>
Public Member Functions
Champ_Generique_Predefini ()
~Champ_Generique_Predefini ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void completer (const Postraitement_base &post) override
const Champ_Generique_base & get_source (int i) const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
const Champ_base & get_champ (Champ &espace_stockage) const override
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & get_nom_post () const override
void nommer_source () override
Nom construit_expression ()
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_Predefini & self_cast (Objet_U &)
static const Champ_Generique_Predefini & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom type_champ_
Nom nom_pb_
Champ_Generique champ_
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
class Champ_Generique_Predefini
Definition at line 38 of file Champ_Generique_Predefini.h.
Constructor & Destructor Documentation
Champ_Generique_Predefini()
Champ_Generique_Predefini::Champ_Generique_Predefini ()
Definition at line 20 of file Champ_Generique_Predefini.cpp.
~Champ_Generique_Predefini()
Champ_Generique_Predefini::~Champ_Generique_Predefini ()
Definition at line 20 of file Champ_Generique_Predefini.cpp.
Member Function Documentation
completer()
void Champ_Generique_Predefini::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 63 of file Champ_Generique_Predefini.cpp.
{
  champ_->completer(post);
}
References champ_.
construit_expression()
Nom Champ_Generique_Predefini::construit_expression ()
Definition at line 144 of file Champ_Generique_Predefini.cpp.
{
  Motcles les_mots(15);
  {
    les_mots[0] = "energie_cinetique_totale";
    les_mots[1] = "energie_cinetique_elem";
    les_mots[2] = "viscosite_turbulente";
    les_mots[3] = "viscous_force_x";
    les_mots[4] = "viscous_force_y";
    les_mots[5] = "viscous_force_z";
    les_mots[6] = "pressure_force_x";
    les_mots[7] = "pressure_force_y";
    les_mots[8] = "pressure_force_z";
    les_mots[9] = "total_force_x";
    les_mots[10] = "total_force_y";
    les_mots[11] = "total_force_z";
    les_mots[12] = "viscous_force";
    les_mots[13] = "pressure_force";
    les_mots[14] = "total_force";
  }
  Nom expression("");
// on recupere la dimension du problem
  int dim=Objet_U::dimension;
  int rang = les_mots.search(type_champ_);
  switch(rang)
    {
    case 0:
      {
        expression  = " Reduction_0D { methode somme_ponderee ";
        expression += " source Transformation { methode formule expression 1 0.5*rho*norme_u*norme_u ";
        expression += " sources { Transformation { methode norme  localisation elem  source RefChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse }  nom_source norme_u } , refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " masse_volumique nom_source rho } } } } ";
        break;
      }
    case 1:
      {
        expression  = " Transformation { methode formule expression 1 0.5*rho*norme_u*norme_u ";
        expression += " sources { Transformation { methode norme  localisation elem  source RefChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse }  nom_source norme_u } , refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " masse_volumique nom_source rho } } } ";
        break;
      }
    case 2:
      {
        expression  = " modifier_pour_QC { division source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " viscosite_dynamique_turbulente } } ";
        break;
      }
    case 3:
      {
        expression  = " Morceau_equation { type operateur numero 0 option flux_bords compo 0 ";
        expression += "  source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } }";
        break;
      }
    case 4:
      {
        expression  = " Morceau_equation { type operateur numero 0 option flux_bords compo 1 ";
        expression += "  source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } }";
        break;
      }
    case 5:
      {
        expression  = " Morceau_equation { type operateur numero 0 option flux_bords compo 2 ";
        expression += "  source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } }";
        break;
      }
    case 6:
      {
        expression  = " Morceau_equation { type operateur numero 2 option flux_bords compo 0 ";
        expression += "  source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } }";
        break;
      }
    case 7:
      {
        expression  = " Morceau_equation { type operateur numero 2 option flux_bords compo 1 ";
        expression += "  source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } }";
        break;
      }
    case 8:
      {
        expression  = " Morceau_equation { type operateur numero 2 option flux_bords compo 2 ";
        expression += "  source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } }";
        break;
      }
    case 9:
      {
        expression  = " Transformation { methode formule expression 1 viscousFX+pressureFX sources { ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 0 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousFX } , ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 0 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureFX } ";
        expression += " } }";
        break;
      }
    case 10:
      {
        expression  = " Transformation { methode formule expression 1 viscousFY+pressureFY sources { ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 1 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousFY } , ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 1 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureFY } ";
        expression += " } }";
        break;
      }
    case 11:
      {
        expression  = " Transformation { methode formule expression 1 viscousFZ+pressureFZ sources { ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 2 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousFZ } , ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 2 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureFZ } ";
        expression += " } }";
        break;
      }
    case 12:
      {
        if (dim==3)
          {
            expression  = " Transformation { methode vecteur expression 3 viscousX viscousY viscousZ sources { ";
            expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 2 source refChamp { Pb_champ ";
            expression += nom_pb_;
            expression += " vitesse } nom_source viscousZ } , ";
          }
        else
          expression  = " Transformation { methode vecteur expression 2 viscousX viscousY sources { ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 0 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousX } , ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 1 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousY } ";
        expression += " } }";
        break;
      }
    case 13:
      {
        if (dim==3)
          {
            expression  = " Transformation { methode vecteur expression 3 pressureX pressureY pressureZ sources { ";
            expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 2 source refChamp { Pb_champ ";
            expression += nom_pb_;
            expression += " vitesse } nom_source pressureZ } , ";
          }
        else
          expression  = " Transformation { methode vecteur expression 2 pressureX pressureY sources { ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 0 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureX } , ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 1 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureY } ";
        expression += " } }";
        break;
      }
    case 14:
      {
        if (dim==3)
          {
            expression  = " Transformation { methode vecteur expression 3 viscousX+pressureX viscousY+pressureY viscousZ+pressureZ sources { ";
            expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 2 source refChamp { Pb_champ ";
            expression += nom_pb_;
            expression += " vitesse } nom_source viscousZ } , ";
            expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 2 source refChamp { Pb_champ ";
            expression += nom_pb_;
            expression += " vitesse } nom_source pressureZ } , ";
          }
        else
          expression  = " Transformation { methode vecteur expression 2 viscousX+pressureX viscousY+pressureY sources { ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 0 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousX } , ";
        expression += " Morceau_equation { type operateur numero 0 option flux_bords compo 1 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source viscousY } , ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 0 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureX } , ";
        expression += " Morceau_equation { type operateur numero 2 option flux_bords compo 1 source refChamp { Pb_champ ";
        expression += nom_pb_;
        expression += " vitesse } nom_source pressureY } ";
        expression += " } }";
        break;
      }
    default :
      {
        Cerr<<"Only keywords among "<<les_mots<<" are allowed."<<finl;
        exit();
      }
    }
  return expression;
}
References Cerr, Objet_U::dimension, Process::exit(), finl, nom_pb_, Motcles::search(), and type_champ_.
Referenced by readOn().
cree_instance()
Objet_U * Champ_Generique_Predefini::cree_instance () static
Definition at line 20 of file Champ_Generique_Predefini.cpp.
duplique()
int Champ_Generique_Predefini::duplique () const override virtual
Implements Objet_U.
Definition at line 20 of file Champ_Generique_Predefini.cpp.
get_champ()
const Champ_base & Champ_Generique_Predefini::get_champ (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 77 of file Champ_Generique_Predefini.cpp.
{
  return champ_->get_champ(espace_stockage);
}
References champ_.
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Predefini::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 73 of file Champ_Generique_Predefini.cpp.
{
  return champ_->get_champ_without_evaluation(espace_stockage);
}
References champ_.
get_info()
const Type_info * Champ_Generique_Predefini::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 20 of file Champ_Generique_Predefini.cpp.
get_nom_post()
const Nom & Champ_Generique_Predefini::get_nom_post () const override virtual
Reimplemented from Champ_Generique_base.
Definition at line 134 of file Champ_Generique_Predefini.cpp.
{
  return champ_->get_nom_post();
}
References champ_.
get_property()
const Noms Champ_Generique_Predefini::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 82 of file Champ_Generique_Predefini.cpp.
{
  Motcles motcles(1);
  motcles[0] = "unites";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms mots(1);
        if (Motcle(type_champ_)=="ENERGIE_CINETIQUE_TOTALE")
          mots[0] = "kg.m2/s2";
        else if (Motcle(type_champ_)=="ENERGIE_CINETIQUE_ELEM")
          mots[0] = "kg/(m.s2)";
        else if (Motcle(type_champ_)=="VISCOSITE_TURBULENTE")
          mots[0] = "m2/s";
        else if (Motcle(type_champ_)=="VISCOUS_FORCE_X")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="VISCOUS_FORCE_Y")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="VISCOUS_FORCE_Z")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="PRESSURE_FORCES_X")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="PRESSURE_FORCES_Y")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="PRESSURE_FORCES_Z")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="TOTAL_FORCE_X")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="TOTAL_FORCE_Y")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="TOTAL_FORCE_Z")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="VISCOUS_FORCE")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="PRESSURE_FORCE")
          mots[0] = "kg.m2/s";
        else if (Motcle(type_champ_)=="TOTAL_FORCE")
          mots[0] = "kg.m2/s";
        return mots;
        break;
      }
    }
  return champ_->get_property(query);
}
References champ_, Motcles::search(), and type_champ_.
get_source()
const Champ_Generique_base & Champ_Generique_Predefini::get_source (int i) const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 68 of file Champ_Generique_Predefini.cpp.
{
  return ref_cast(Champ_Gen_de_Champs_Gen,champ_.valeur()).get_source(i);
}
References champ_, ref_cast, and Deriv_Champ_Generique_base::valeur().
info()
const Type_info * Champ_Generique_Predefini::info () static
Definition at line 20 of file Champ_Generique_Predefini.cpp.
lire_motcle_non_standard()
int Champ_Generique_Predefini::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 50 of file Champ_Generique_Predefini.cpp.
{
  if (mot=="Pb_champ")
    {
// Lecture du nom du probleme et du champ a construire
      is >> nom_pb_ >> type_champ_;
      return 1;
    }
  else
    return Champ_Generique_base::lire_motcle_non_standard(mot,is);
  return 1;
}
References Champ_Generique_base::lire_motcle_non_standard(), nom_pb_, and type_champ_.
nommer()
void Champ_Generique_Predefini::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 129 of file Champ_Generique_Predefini.cpp.
{
  champ_->nommer(nom);
}
References champ_, and Objet_U::nommer().
nommer_source()
void Champ_Generique_Predefini::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 139 of file Champ_Generique_Predefini.cpp.
{
  ref_cast(Champ_Gen_de_Champs_Gen,champ_.valeur()).nommer_source();
}
References champ_, ref_cast, and Deriv_Champ_Generique_base::valeur().
printOn()
Sortie & Champ_Generique_Predefini::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 24 of file Champ_Generique_Predefini.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Generique_Predefini::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 32 of file Champ_Generique_Predefini.cpp.
{
  Champ_Gen_de_Champs_Gen::readOn(s);
  Nom expression;
  expression = construit_expression();
  Entree_complete s_complete(expression,s);
  s_complete>>champ_;
  return s ;
}
References champ_, construit_expression(), and Champ_Gen_de_Champs_Gen::readOn().
self_cast() [1/2]
const Champ_Generique_Predefini & Champ_Generique_Predefini::self_cast (const Objet_U & r) static
Definition at line 20 of file Champ_Generique_Predefini.cpp.
self_cast() [2/2]
Champ_Generique_Predefini & Champ_Generique_Predefini::self_cast (Objet_U & r) static
Definition at line 20 of file Champ_Generique_Predefini.cpp.
set_param()
void Champ_Generique_Predefini::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 45 of file Champ_Generique_Predefini.cpp.
{
  param.ajouter_non_std("Pb_champ",(this),Param::REQUIRED);
}
References Param::ajouter_non_std(), and Param::REQUIRED.
taille_memoire()
unsigned Champ_Generique_Predefini::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 20 of file Champ_Generique_Predefini.cpp.
Member Data Documentation
champ_
Champ_Generique Champ_Generique_Predefini::champ_ protected
Definition at line 61 of file Champ_Generique_Predefini.h.
Referenced by completer(), get_champ(), get_champ_without_evaluation(), get_nom_post(), get_property(), get_source(), nommer(), nommer_source(), and readOn().
info_obj
const Type_info Champ_Generique_Predefini::info_obj static
Definition at line 41 of file Champ_Generique_Predefini.h.
nom_pb_
Nom Champ_Generique_Predefini::nom_pb_ protected
Definition at line 60 of file Champ_Generique_Predefini.h.
Referenced by construit_expression(), and lire_motcle_non_standard().
type_champ_
Nom Champ_Generique_Predefini::type_champ_ protected
Definition at line 59 of file Champ_Generique_Predefini.h.
Referenced by construit_expression(), get_property(), and lire_motcle_non_standard().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Predefini.h
src/Kernel/Champs/Champ_Generique_Predefini.cpp