TRUST: Elem_EF Class Reference
Elem_EF Class Reference
#include <Elem_EF.h>
Public Member Functions
Elem_EF ()
~Elem_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Elem_EF & operator= (const Elem_EF_base &)
void typer (Nom)
determination du type
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Elem_EF & self_cast (Objet_U &)
static const Elem_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 42 of file Elem_EF.h.
Constructor & Destructor Documentation
Elem_EF::Elem_EF ()
Definition at line 30 of file Elem_EF.cpp.
Elem_EF::~Elem_EF ()
Definition at line 30 of file Elem_EF.cpp.
Member Function Documentation
void Elem_EF::calcul_vc (const ArrOfInt & face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl) const [inline]
Definition at line 86 of file Elem_EF.h.
References Elem_EF_base::calcul_vc(), and Deriv_Elem_EF_base::valeur().
{
  valeur().calcul_vc(face,vc,vs,vsom,vitesse,type_cl);
}
void Elem_EF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & n2, int & n3) const [inline]
Definition at line 94 of file Elem_EF.h.
References Elem_EF_base::calcul_xg(), and Deriv_Elem_EF_base::valeur().
{
  valeur().calcul_xg(xg,x,type_elem_Cl,idirichlet,n1,n2,n3);
}
Objet_U * Elem_EF::cree_instance () [static]
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
int Elem_EF::duplique () const [virtual]
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
const Type_info * Elem_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
const Type_info * Elem_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
void Elem_EF::normale (int num_face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const [inline]
Definition at line 73 of file Elem_EF.h.
References Elem_EF_base::normale(), and Deriv_Elem_EF_base::valeur().
Referenced by Zone_EF::discretiser().
{
  valeur().normale(num_face,Face_normales,Face_sommets,Face_voisins,
                   elem_faces,zone_geom);
}
Elem_EF & Elem_EF::operator= (const Elem_EF_base & elem_base) [inline]
Reimplemented from Deriv_Elem_EF_base.
Definition at line 65 of file Elem_EF.h.
References DERIV.
{
  DERIV(Elem_EF_base)::operator=(elem_base);
  return *this;
}
Sortie & Elem_EF::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Elem_EF_base.
Definition at line 36 of file Elem_EF.cpp.
References Deriv_Elem_EF_base::valeur().
{
  return s << valeur() ;
}
Entree & Elem_EF::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Elem_EF_base.
Definition at line 41 of file Elem_EF.cpp.
References Cerr, Process::exit(), and finl.
{
  Nom type;
  s >> type;
  if(type == "Tri_EF")
    *this =  Tri_EF();
  else if(type == "Tetra_EF")
    *this =  Tetra_EF();
  else if(type == "Quadri_EF")
    *this =  Quadri_EF();
  else if(type == "Hexa_EF")
    *this =  Hexa_EF();
  else
    {
      Cerr << type << " n'est pas un Elem_EF" << finl;
      exit();
    }
  return s ;
}
Elem_EF & Elem_EF::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
const Elem_EF & Elem_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
unsigned Elem_EF::taille_memoire () const [virtual]
Reimplemented from Deriv_Elem_EF_base.
Definition at line 30 of file Elem_EF.cpp.
void Elem_EF::typer (Nom type_elem_geom)
determination du type
Definition at line 63 of file Elem_EF.cpp.
References Cerr, DERIV, Process::exit(), and finl.
Referenced by Zone_EF::typer_elem().
{
// Cerr << "Elem_EF::typer()" << finl ;
  Nom type;
  if(type_elem_geom=="Triangle")
    type="Tri_EF";
  else if(type_elem_geom=="Tetraedre")
    type="Tetra_EF";
  else if(type_elem_geom=="Quadrangle")
    type="Quadri_EF";
  else if(type_elem_geom=="Hexaedre_VEF")
    type="Hexa_EF";
  else if(type_elem_geom=="Segment")
    type="Segment_EF";
  else if(type_elem_geom=="Segment_axi")
    type="Segment_EF_axi";
  else if(type_elem_geom=="Point")
    type="Point_EF";
  else
    {
      Cerr << "probleme de typage dans Elem_EF::typer" << finl;
      Cerr << "type geometrique : " << type_elem_geom << finl;
      exit();
    }
  DERIV(Elem_EF_base)::typer(type);
// Cerr << "type retenu : " << valeur().que_suis_je() << finl ;
}
Member Data Documentation
const Type_info Elem_EF::info_obj [static]
Reimplemented from Deriv_Elem_EF_base.
Definition at line 44 of file Elem_EF.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Elem_EF.h
src/EF/Zones/Elem_EF.cpp