TRUST: mon_main Class Reference
mon_main Class Reference
Classe creee et executee par main() et lors d'une execution TRUST a
travers Python. Il faut
- creer une instance mon_main
- initialiser le parallele
- appeler dowork(nom_du_cas) (lecture et interpretation du jdd)
A cet instant on peut jouer avec les objets crees en python<br>(voir Interprete_bloc::objet_global(nom))
- detruire l'instance mon_main
L'interprete principal conserve ses objets jusqu'a la destruction
de l'instance mon_main.
#include <mon_main.h>
Public Member Functions
mon_main (int verbose_level=9, int journal_master=0, int journal_shared=0, bool apply_verification=true, int disable_stop=0)
void init_parallel (const int argc, char **argv, int with_mpi, int check_enabled=0, int with_petsc=1)
void finalize ()
void dowork (const Nom &nom_du_cas)
~mon_main ()
Private Attributes
int verbose_level_
int journal_master_
int journal_shared_
int trio_began_mpi_
bool apply_verification_
int disable_stop_
Deriv_Comm_Group groupe_trio_
Interprete_bloc interprete_principal_
Detailed Description
Classe creee et executee par main() et lors d'une execution TRUST a
travers Python. Il faut
- creer une instance mon_main
- initialiser le parallele
- appeler dowork(nom_du_cas) (lecture et interpretation du jdd)
A cet instant on peut jouer avec les objets crees en python<br>(voir Interprete_bloc::objet_global(nom))
- detruire l'instance mon_main
L'interprete principal conserve ses objets jusqu'a la destruction
de l'instance mon_main.
Definition at line 39 of file mon_main.h.
Constructor & Destructor Documentation
mon_main()
mon_main::mon_main (int verbose_level = 9, int journal_master = 0, int journal_shared = 0, bool apply_verification = true, int disable_stop = 0)
Definition at line 38 of file mon_main.cpp.
{
  verbose_level_ = verbose_level;
  journal_master_ = journal_master;
  journal_shared_ = journal_shared;
  apply_verification_ = apply_verification;
// Creation d'un journal temporaire qui ecrit dans Cerr
  init_journal_file(verbose_level, 0, 0 /* filename = 0 => Cerr */, 0 /* append */);
  trio_began_mpi_=0;
  disable_stop_=disable_stop;
  change_disable_stop(disable_stop);
}
References apply_verification_, change_disable_stop(), disable_stop_, init_journal_file(), journal_master_, journal_shared_, trio_began_mpi_, and verbose_level_.
~mon_main()
mon_main::~mon_main ()
Definition at line 419 of file mon_main.cpp.
{
// On peut arreter le journal apres les communications:
// EDIT 12/02/2020: journal needs communication to be turned on if it's written in HDF5 format
  Process::Journal() << "End of Journal logging" << finl;
  end_journal(verbose_level_);
  end_stat_counters();
// Destruction de l'interprete principal avant d'arreter le parallele
  interprete_principal_.vide();
// PetscFinalize/MPI_Finalize
  finalize();
// on peut arreter maintenant que l'on a arrete les journaux
  PE_Groups::finalize();
  groupe_trio_.detach();
}
References Deriv_::detach(), end_journal(), end_stat_counters(), PE_Groups::finalize(), finalize(), finl, groupe_trio_, interprete_principal_, Process::Journal(), verbose_level_, and liste::vide().
Member Function Documentation
dowork()
void mon_main::dowork (const Nom & nom_du_cas)
< Into _comm.TU file
Definition at line 271 of file mon_main.cpp.
{
// Initialisation des compteurs pour les statistiques
// avant tout appel a envoyer, recevoir, ...
  if (!les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe)
    {
      declare_stat_counters();
    }
  statistiques().begin_count(temps_total_execution_counter_);
// Ce compteur est arrete dans Resoudre*
  statistiques().begin_count(initialisation_calcul_counter_);
// Le processeur maitre envoie le nom du cas a tous les processeurs
// car avec une distribution MPICH 1.2.7 (Debian)
// la ligne de commande recuperee avec argv ne contient
// pas le nom du jeu de donnees pour les processeurs autres
// que le processeur maitre
  Nom tmp = nom_du_cas;
  envoyer(tmp, 0, -1, 0);
  recevoir(tmp, 0, -1, 0);
  Objet_U::get_set_nom_du_cas() = tmp;
// ******************* Journal ***************************
// Initialisation du journal parallele (maintenant qu'on connait le rang
// du processeur et le nom du cas)
  {
    Nom filename(nom_du_cas);
    if (Process::nproc() > 1 && !journal_shared_)
      {
        filename += "_";
        char s[20];
        sprintf(s, "%05d", (True_int)Process::me());
        filename += s;
      }
    filename += ".log";
// Si journal_master_, seul le process maitre ecrit dans le journal:
    if (journal_master_ && !Process::je_suis_maitre())
      verbose_level_ = 0;
// Si un journal unique n'est pas active, alors desactive les journaux logs au dela d'un certain nombre de rangs MPI:
    if (!journal_shared_ && !journal_master_ && Process::force_single_file(Process::nproc(), nom_du_cas+".log"))
      verbose_level_ = 0;
    init_journal_file(verbose_level_, journal_shared_,filename, 0 /* append=0 */);
    if(journal_shared_) Process::Journal() << "\n[Proc " << Process::me() << "] : ";
    Process::Journal() << "Journal logging started" << finl;
  }
  Nom nomfic( nom_du_cas );
  nomfic += ".stop";
  if (!get_disable_stop() && Process::je_suis_maitre())
    {
      SFichier ficstop( nomfic );
      ficstop << "Running..."<<finl;
    }
// ---------------------------------------------//
// Chargement des modules : //
// on ne les charges que pour le cas nul, pour verifier avec valgrind
  if (Objet_U::nom_du_cas()=="nul")
    {
      Cerr<<"Chargement des modules:"<<finl;
#include <instancie_appel_c.h>
      Cerr<<"Fin chargement des modules "<<finl;
    }
  Cout<< " " << finl;
  Cout<< " * * * * * * * * * * * * * * * * * * * * * * * * * * * *     " << finl;
  Cout<< " *  _________  _______             _______  _________  *     " << finl;
  Cout<< " *  \\__   __/ (  ____ ) |\\     /| (  ____ \\ \\__   __/  * " << finl;
  Cout<< " *     ) (    | (    )| | )   ( | | (    \\/    ) (     *    " << finl;
  Cout<< " *     | |    | (____)| | |   | | | (_____     | |     *     " << finl;
  Cout<< " *     | |    |     __) | |   | | (_____  )    | |     *     " << finl;
  Cout<< " *     | |    | (\\ (    | |   | |       ) |    | |     *    " << finl;
  Cout<< " *     | |    | ) \\ \\__ | (___) | /\\____) |    | |     *  " << finl;
  Cout<< " *     )_(    |/   \\__/ (_______) \\_______)    )_(     *   " << finl;
  Cout<< " *                                                     *     " << finl;
  Cout<< " *                  version : 1.9.0               *     "  << finl;
  Cout<< " *                       CEA - DES                     *     " << finl;
  Cout<< " *                                                     *     " << finl;
  Cout<< " * * * * * * * * * * * * * * * * * * * * * * * * * * * * " << finl;
  Cout<< " " << finl;
  info_atelier(Cout);
  Cout<<" " << finl;
  Cout<<"  Vous traitez le cas " << Objet_U::nom_du_cas() << "\n";
  Cout<<" " << finl;
// GF on ecrit la hierarchie que si on a un erreur
// ---------------------------------------------//
  Cerr<<"Debut de l'execution " << finl;
  {
    Nom nomentree = nom_du_cas;
    nomentree+=".data";
#ifndef NDEBUG
    if (Process::je_suis_maitre())
      {
        SFichier es("convert_jdd");
      }
#endif
// La verfication est faite maintenant dans LecFicDiffuse_JDD
// mias je garde les lignes au cas ou
    if (0)
      {
        Cerr << "MAIN: Checking data file for matching { and }" << finl;
        {
          LecFicDiffuse_JDD verifie_entree(nomentree, ios::in, apply_verification_);
          interprete_principal_.interpreter_bloc(verifie_entree,
                                                 Interprete_bloc::FIN /* on attend FIN a la fin */,
                                                 1 /* verifie_sans_interpreter */);
        }
      }
    Cerr << "MAIN: Reading and executing data file" << finl;
    {
      LecFicDiffuse_JDD lit_entree(nomentree, ios::in, apply_verification_);
      lit_entree.set_check_types(1);
      interprete_principal_.interpreter_bloc(lit_entree,
                                             Interprete_bloc::FIN /* on attend FIN a la fin */,
                                             0 /* interprete pour de vrai */);
    }
  }
  Cerr << "MAIN: End of data file" << finl;
  Process::imprimer_ram_totale(1);
// pour les cas ou on ne fait pas de resolution
  int mode_append=1;
  if (!Objet_U::disable_TU)
    {
      if(GET_COMM_DETAILS)
        statistiques().print_communciation_tracking_details("Statistiques de post resolution", 1);               //!< Into _comm.TU file
      statistiques().dump("Statistiques de post resolution", mode_append);
      print_statistics_analyse("Statistiques de post resolution", 1);
    }
  double temps = statistiques().get_total_time();
  Cout << finl;
  Cout << "--------------------------------------------" << finl;
  Cout << "clock: Total execution: " << temps << " s" << finl;
  if (!get_disable_stop() && Process::je_suis_maitre())
    {
      SFichier ficstop ( nomfic);
      ficstop  << "Finished correctly"<<finl;
    }
// end_stat_counters();
}
References apply_verification_, Statistiques::begin_count(), Cerr, Cout, declare_stat_counters(), Objet_U::disable_TU, Statistiques::dump(), envoyer(), Interprete_bloc::FIN, finl, Process::force_single_file(), GET_COMM_DETAILS, get_disable_stop(), Objet_U::get_set_nom_du_cas(), Statistiques::get_total_time(), Process::imprimer_ram_totale(), info_atelier(), init_journal_file(), initialisation_calcul_counter_, interprete_principal_, Interprete_bloc::interpreter_bloc(), Process::je_suis_maitre(), Process::Journal(), journal_master_, journal_shared_, les_statistiques_trio_U_nom_long_pour_decourager_l_utilisation_directe, Process::me(), Objet_U::nom_du_cas(), Process::nproc(), Statistiques::print_communciation_tracking_details(), print_statistics_analyse(), recevoir(), Lec_Diffuse_base::set_check_types(), statistiques(), temps_total_execution_counter_, and verbose_level_.
Referenced by main_TRUST().
finalize()
void mon_main::finalize ()
Definition at line 234 of file mon_main.cpp.
{
#ifdef MPI_
// MPI_Group_free before MPI_Finalize
  if (sub_type(Comm_Group_MPI,groupe_trio_.valeur()))
    ref_cast(Comm_Group_MPI,groupe_trio_.valeur()).free();
#endif
#ifdef PETSCKSP_H
// On PetscFinalize que si c'est necessaire
  PetscBool isInitialized;
  PetscInitialized(&isInitialized);
  if (isInitialized==PETSC_TRUE)
    {
      PetscPopErrorHandler(); //!< Removes the latest error handler that was pushed with PetscPushErrorHandler in init_petsc
#ifdef MPI_
      if (sub_type(Comm_Group_MPI,PE_Groups::current_group()))
        PETSC_COMM_WORLD = ref_cast(Comm_Group_MPI,PE_Groups::current_group()).get_mpi_comm();
#endif
      PetscFinalize();
    }
#endif
#ifdef MPI_
  if (trio_began_mpi_)
    {
// On MPI_Finalize si MPI_Initialized and not MPI_Finalized
      True_int flag;
      MPI_Initialized(&flag);
      if (flag)
        {
          MPI_Finalized(&flag);
          if (!flag)
            MPI_Finalize();
        }
    }
#endif
}
References PE_Groups::current_group(), groupe_trio_, ref_cast, sub_type, trio_began_mpi_, and Deriv_Comm_Group::valeur().
Referenced by ~mon_main().
init_parallel()
void mon_main::init_parallel (const int argc, char ** argv, int with_mpi, int check_enabled = 0, int with_petsc = 1)
< Deja fait par Petsc
Definition at line 171 of file mon_main.cpp.
{
#ifdef PETSC_HAVE_CUDA
// Necessaire sur JeanZay pour utiliser GPU Direct (http://www.idris.fr/jean-zay/gpu/jean-zay-gpu-mpi-cuda-aware-gpudirect.html)
// mais performances moins bonnes (trust PAR_gpu_3D 2) donc desactive en attendant d'autres tests:
// Absolument necessaire sur JeanZay (si OpenMPU-Cuda car sinon plantages lors des IO)
// Voir: https://www.open-mpi.org/faq/?category=runcuda#mpi-cuda-aware-support pour activer ou non a la compilation !
#if defined(MPIX_CUDA_AWARE_SUPPORT) && MPIX_CUDA_AWARE_SUPPORT
  init_cuda();
#endif /* MPIX_CUDA_AWARE_SUPPORT */
#endif
  Nom arguments_info="";
  int must_mpi_initialize = 1;
  if (with_petsc != 0)
    {
      if (init_petsc(argc, argv, with_mpi,trio_began_mpi_))
        {
          must_mpi_initialize = 0; //!< Deja fait par Petsc
          arguments_info += "Petsc initialization succeeded.\n";
        }
      else
        {
          arguments_info += "Petsc initialization failed (not compiled ?). Not fatal...\n";
        }
    }
  else
    {
      arguments_info += "Petsc initialization skipped (-petsc=0).\n";
    }
#ifdef MPI_
  Comm_Group_MPI::set_must_mpi_initialize(must_mpi_initialize);
#else
// GF pour eviter warning
  if (must_mpi_initialize>10) abort();
#endif
// ***************** Initialisation du parallele *************************
  Comm_Group::set_check_enabled(check_enabled);
  if (with_mpi)
    {
      if (!init_parallel_mpi(groupe_trio_))
        {
          Cerr << "MPI initialization failed (not compiled ?). Fatal." << finl;
          Process::exit();
        }
    }
  else
    {
      groupe_trio_.typer("Comm_Group_NoParallel");
    }
// Initialisation des groupes de communication.
  PE_Groups::initialize(groupe_trio_);
  arguments_info += "Parallel engine initialized : ";
  arguments_info += groupe_trio_.valeur().que_suis_je();
  arguments_info += " with ";
  arguments_info += Nom(Process::nproc());
  arguments_info += " processors\n";
  if (Process::je_suis_maitre())
    Cerr << arguments_info;
}
References Cerr, Process::exit(), finl, groupe_trio_, init_parallel_mpi(), init_petsc(), PE_Groups::initialize(), Process::je_suis_maitre(), Process::nproc(), Objet_U::que_suis_je(), Comm_Group::set_check_enabled(), Comm_Group_MPI::set_must_mpi_initialize(), trio_began_mpi_, Deriv_::typer(), and Deriv_Comm_Group::valeur().
Referenced by main_TRUST().
Member Data Documentation
apply_verification_
bool mon_main::apply_verification_ private
Definition at line 53 of file mon_main.h.
Referenced by dowork(), and mon_main().
disable_stop_
int mon_main::disable_stop_ private
Definition at line 54 of file mon_main.h.
Referenced by mon_main().
groupe_trio_
Deriv_Comm_Group mon_main::groupe_trio_ private
Definition at line 55 of file mon_main.h.
Referenced by finalize(), init_parallel(), and ~mon_main().
interprete_principal_
Interprete_bloc mon_main::interprete_principal_ private
Definition at line 56 of file mon_main.h.
Referenced by dowork(), and ~mon_main().
journal_master_
int mon_main::journal_master_ private
Definition at line 50 of file mon_main.h.
Referenced by dowork(), and mon_main().
journal_shared_
int mon_main::journal_shared_ private
Definition at line 51 of file mon_main.h.
Referenced by dowork(), and mon_main().
trio_began_mpi_
int mon_main::trio_began_mpi_ private
Definition at line 52 of file mon_main.h.
Referenced by finalize(), init_parallel(), and mon_main().
verbose_level_
int mon_main::verbose_level_ private
Definition at line 49 of file mon_main.h.
Referenced by dowork(), mon_main(), and ~mon_main().
The documentation for this class was generated from the following files:
src/MAIN/mon_main.h
src/MAIN/mon_main.cpp