TRUST: Sortie_Fichier_base Class Reference
Sortie_Fichier_base Class Reference
#include <Sortie_Fichier_base.h>
Public Member Functions
~Sortie_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sortie_Fichier_base ()
Sortie_Fichier_base (const Sortie_Fichier_base &)=default
Sortie_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::out)
ofstream & get_ofstream ()
void close ()
void precision (int pre) override
virtual int get_precision ()
void setf (std::_Ios_Fmtflags code) override
bool is_open ()
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out)
Sortie & flush () override
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Sortie_Fichier_base & self_cast (Objet_U &)
static const Sortie_Fichier_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ofstream * ofstream_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Private Member Functions
void set_buffer ()
void set_toFlush ()
int toFlush ()
Sortie_Fichier_base & operator= (const Sortie_Fichier_base &)
Private Attributes
char * internalBuff_
int toFlush_
Detailed Description
Definition at line 27 of file Sortie_Fichier_base.h.
Constructor & Destructor Documentation
~Sortie_Fichier_base()
Sortie_Fichier_base::~Sortie_Fichier_base () override
Definition at line 65 of file Sortie_Fichier_base.cpp.
{
// il est important de ne pas detruire ofstream_
  Sortie_Fichier_base::close();
}
References close().
Sortie_Fichier_base() [1/3]
Sortie_Fichier_base::Sortie_Fichier_base ()
Definition at line 35 of file Sortie_Fichier_base.cpp.
{
  bin_=0;
  ofstream_=0;
  set_ostream(ofstream_);
  internalBuff_=0;
  set_toFlush();
}
References Sortie::bin_, internalBuff_, ofstream_, Sortie::set_ostream(), and set_toFlush().
Sortie_Fichier_base() [2/3]
Sortie_Fichier_base::Sortie_Fichier_base (const Sortie_Fichier_base &) default
Sortie_Fichier_base() [3/3]
Sortie_Fichier_base::Sortie_Fichier_base (const char * name, std::_Ios_Openmode mode = ios::out)
Definition at line 44 of file Sortie_Fichier_base.cpp.
{
  bin_=0;
  internalBuff_=0;
  ofstream_ = 0;
  ouvrir(name,mode);
  /*
  new ofstream(name,mode);
  set_toFlush();
  set_buffer();
  set_ostream(ofstream_);
  #ifdef ver_file
  if (Process::me()!=0)
    {
      Cerr<<Process::me()<<name<<" :"<<__FILE__<<(int)__LINE__<<finl;
      ::abort();
    }
  #endif
  */
}
References Sortie::bin_, internalBuff_, ofstream_, and ouvrir().
Member Function Documentation
close()
void Sortie_Fichier_base::close ()
Definition at line 120 of file Sortie_Fichier_base.cpp.
{
  if(ofstream_)
    {
      ofstream_->flush();
      ofstream_->close();
// Destruction faite dans ~Sortie :
// delete ofstream_;
// ofstream_=0;
    }
  if (internalBuff_)
    {
      delete[] internalBuff_;
      internalBuff_=0;
    }
}
References internalBuff_, and ofstream_.
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), check_ICEM_binary_file(), EcrFicPartage::close(), Champ_front_contact_VEF::connectivity_failed(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_naif(), DecoupeBord::Decouper(), Op_Div_VEFP1B_Elem::degres_liberte(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), end_journal(), ExtrudeBord::extruder_hexa_old(), Sonde::fermer_fichier(), Format_Post_Lata::finir_sans_reprise(), Loi_horaire::imprimer(), Sch_CN_iteratif::iterateTimeStep(), Champ_front_recyclage::lire_fichier_format3(), Navier_Stokes_std::lire_motcle_non_standard(), Format_Post_Lata::reconstruct(), Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat(), Verifier_Qualite_Raffinements::verifier_qualite_raffinements(), EcrFicCollecte::~EcrFicCollecte(), EcrFicCollecteBin::~EcrFicCollecteBin(), and ~Sortie_Fichier_base().
flush()
Sortie & Sortie_Fichier_base::flush () override virtual
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Returns
Sortie&
Signification: *this
Contraintes:
Reimplemented from Sortie.
Definition at line 247 of file Sortie_Fichier_base.cpp.
{
  if (toFlush()) ofstream_->flush();
  return *this;
}
References ofstream_, and toFlush().
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Sonde::postraiter(), Sonde_Int::postraiter(), and Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat().
get_info()
const Type_info * Sortie_Fichier_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 22 of file Sortie_Fichier_base.cpp.
get_ofstream()
ofstream & Sortie_Fichier_base::get_ofstream ()
Definition at line 115 of file Sortie_Fichier_base.cpp.
{
  return *ofstream_;
}
References ofstream_.
Referenced by check_ICEM_binary_file(), Format_Post_Lata::finir_sans_reprise(), Ecrire_Fichier::interpreter_(), is_open(), and Format_Post_Lata::reconstruct().
get_precision()
int Sortie_Fichier_base::get_precision () virtual
Reimplemented in EcrFicPartage.
Definition at line 143 of file Sortie_Fichier_base.cpp.
{
  return ofstream_->precision();
}
References ofstream_.
Referenced by Schema_Temps_base::imprimer_temps_courant().
info()
const Type_info * Sortie_Fichier_base::info () static
Definition at line 22 of file Sortie_Fichier_base.cpp.
is_open()
bool Sortie_Fichier_base::is_open ()
Definition at line 252 of file Sortie_Fichier_base.cpp.
{
  return (ofstream_&&get_ofstream().is_open()) ;
}
References get_ofstream(), is_open(), and ofstream_.
Referenced by Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Grad_VDF_Face::impr(), Schema_Temps_base::initialize(), is_open(), Sonde::ouvrir_fichier(), Terme_Source_Canal_perio::source(), and Terme_Source_Canal_perio::write_flow_rate().
operator=()
Sortie_Fichier_base & Sortie_Fichier_base::operator= (const Sortie_Fichier_base &) private
ouvrir()
int Sortie_Fichier_base::ouvrir (const char * name, std::_Ios_Openmode mode = ios::out) virtual
Reimplemented in EcrFicCollecte, EcrFicPartage, and EcrFicPartageMPIIO.
Definition at line 155 of file Sortie_Fichier_base.cpp.
{
#ifdef ver_file
  if (Process::me()!=0)
    {
      char* marq=strrchr(name,'_');
      int error=0;
      if (!marq)
        error=1;
      else
        {
          Nom test(name);
          test.prefix(marq);
          Nom suf(name);
          marq=strrchr(name,'.');
          if (!marq)
            error=1;
          else
            {
              int l=strlen(name);
              int deb=l-strlen(marq)+1;
              suf=suf.substr(deb,l);
              test+=suf;
              test=test.nom_me(Process::me());
              if (test!=name) error=1;
            }
        }
      if (error)
        {
          Cerr<<Process::me()<<name<<" strange :"<<__FILE__<<(int)__LINE__<<finl;
          Cerr<<name<<finl;
          ::abort();
        }
    }
#endif
  if (++counters[name]%1000==0) Cerr << "Warning, file " << name << " has been opened/closed " << counters[name] << " times..." << finl;
  if(ofstream_)
    delete ofstream_;
  IOS_OPEN_MODE ios_mod=mode;
  int new_bin=0;
  if (bin_)
    {
      if (ios_mod==ios::out)
        {
          new_bin=1;
        }
      else
        assert((ios_mod==ios::app)||(ios_mod==(ios::app|ios::out)));
      ios_mod=ios_mod|ios::binary;
    }
  ofstream_ = new ofstream(name,ios_mod);
  set_toFlush();
  set_buffer();
  set_ostream(ofstream_);
  if (!ofstream_->good())
    {
      Cerr << "Error when opening the file " << name << finl;
      Cerr << "Check if this file can be opened." << finl;
      Process::exit();
    }
  if (new_bin)
    {
      Nom marq("INT64");
#ifdef INT_is_64_
      (*this)<<marq;
#endif
    }
  return 1;
}
References Process::abort(), Sortie::bin_, Cerr, counters, Process::exit(), finl, IOS_OPEN_MODE, Process::me(), ofstream_, set_buffer(), Sortie::set_ostream(), set_toFlush(), and test().
Referenced by Format_Post_Med::completer_post_med(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_med(), ecrire_fichier_decoupage(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Format_Post_Med::ecrire_temps_med(), DomaineCutter::ecrire_zones(), Fichier_Lata::Fichier_Lata(), Format_Post_Med::finir_med(), Loi_horaire::imprimer(), init_journal_file(), Schema_Temps_base::initialize(), DecoupeBord::interpreter_(), Ecrire_Fichier::interpreter_(), Sch_CN_iteratif::iterateTimeStep(), EcrFicCollecte::ouvrir(), EcrFicPartage::ouvrir(), Sonde::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), ouvrir_fichier_pena_th(), Format_Post_Med::preparer_post_med(), Debog_Pb::readOn(), Sonde::readOn(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), SFichierBin::SFichierBin(), Sortie_Fichier_base(), Terme_Source_Canal_perio::source(), and Terme_Source_Canal_perio::write_flow_rate().
precision()
void Sortie_Fichier_base::precision (int pre) override virtual
Reimplemented from Sortie.
Definition at line 137 of file Sortie_Fichier_base.cpp.
{
  if(ofstream_)
    ofstream_->precision(pre);
}
References ofstream_.
Referenced by DecoupeBord::Decouper(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Fichier_Lata::Fichier_Lata(), Fichier_Lata_maitre::Fichier_Lata_maitre(), Format_Post_Lata::finir_sans_reprise(), Loi_horaire::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Schema_Temps_base::imprimer_temps_courant(), Raffiner_isotrope_parallele::interpreter(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), ouvrir_fichier_pena_th(), Debog_Pb::readOn(), Format_Post_Lata::reconstruct(), Solv_Petsc::resoudre_systeme(), and Debog_Pb::write_geometry_data().
printOn()
Sortie & Sortie_Fichier_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 30 of file Sortie_Fichier_base.cpp.
{
  throw;
  return s;
}
readOn()
Entree & Sortie_Fichier_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Sortie_Fichier_base.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const Sortie_Fichier_base & Sortie_Fichier_base::self_cast (const Objet_U & r) static
Definition at line 22 of file Sortie_Fichier_base.cpp.
self_cast() [2/2]
Sortie_Fichier_base & Sortie_Fichier_base::self_cast (Objet_U & r) static
Definition at line 22 of file Sortie_Fichier_base.cpp.
set_buffer()
void Sortie_Fichier_base::set_buffer () private
Definition at line 93 of file Sortie_Fichier_base.cpp.
{
  if (!toFlush_)
    {
      char* theValue = getenv("TRIOU_BUFFSIZE");
// On fixe une valeur a 3000000 par defaut pour buffSize
// Elle peut etre changee par la variable d'environnement
      int buffSize = 3000000;
      if (theValue != NULL)
        {
          buffSize = atoi(theValue);
        }
      if (buffSize>=0)
        {
          size_t internalBuffSize = buffSize;
          internalBuff_ = new char[internalBuffSize];
          ofstream_->rdbuf()->pubsetbuf(internalBuff_,internalBuffSize);
          toFlush_ = 0;
        }
    }
}
References internalBuff_, ofstream_, and toFlush_.
Referenced by ouvrir().
set_toFlush()
void Sortie_Fichier_base::set_toFlush () private
Definition at line 71 of file Sortie_Fichier_base.cpp.
{
  char* theValue = getenv("TRIOU_FLUSHFILES");
// On fixe une valeur a 0 par defaut pour toFlush_
// Elle peut etre changee par la variable d'environnement
// On bufferize sur DEC pour accelerer les ecritures .lml, .lata, ...
#ifdef DECalpha
  toFlush_ = 0;
#else
  toFlush_ = 1;
#endif
// Les acces disques ont ete optimises depuis
// donc par defaut on flushe a nouveau car
// sinon les sondes pas ecrites...
// Si lent, mettre export TRIOU_FLUSHFILES=0 dans son sub_file
  toFlush_ = 1;
  if (theValue != NULL)
    {
      toFlush_=atoi(theValue);
    }
}
References toFlush_.
Referenced by ouvrir(), and Sortie_Fichier_base().
setf()
void Sortie_Fichier_base::setf (std::_Ios_Fmtflags code) override virtual
Reimplemented from Sortie.
Definition at line 148 of file Sortie_Fichier_base.cpp.
{
  if(ofstream_)
    ofstream_->setf(code);
}
References ofstream_.
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_P1NC::calcul_h_conv(), DecoupeBord::Decouper(), Equation_base::ecrire_fichier_xyz(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Fichier_Lata::Fichier_Lata(), Fichier_Lata_maitre::Fichier_Lata_maitre(), Format_Post_Lata::finir_sans_reprise(), Loi_horaire::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Schema_Temps_base::initialize(), Raffiner_isotrope_parallele::interpreter(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), ouvrir_fichier_pena_th(), Debog_Pb::readOn(), Format_Post_Lata::reconstruct(), Solv_Petsc::resoudre_systeme(), Ch_front_Vortex::sauvegarder_vortex(), Probleme_base::sauver(), Traitement_particulier_NS_canal::sauver_stat_canal(), Terme_Source_Canal_perio::source(), and Terme_Source_Canal_perio::write_flow_rate().
toFlush()
int Sortie_Fichier_base::toFlush () inline private
Definition at line 54 of file Sortie_Fichier_base.h.
  {
    return toFlush_;
  }
References toFlush_.
Referenced by flush().
Member Data Documentation
info_obj
const Type_info Sortie_Fichier_base::info_obj static
Definition at line 29 of file Sortie_Fichier_base.h.
internalBuff_
char* Sortie_Fichier_base::internalBuff_ private
Definition at line 49 of file Sortie_Fichier_base.h.
Referenced by close(), set_buffer(), and Sortie_Fichier_base().
ofstream_
ofstream* Sortie_Fichier_base::ofstream_ protected
Definition at line 46 of file Sortie_Fichier_base.h.
Referenced by close(), flush(), get_ofstream(), get_precision(), is_open(), ouvrir(), precision(), set_buffer(), setf(), SFichierBin::SFichierBin(), and Sortie_Fichier_base().
toFlush_
int Sortie_Fichier_base::toFlush_ private
Definition at line 50 of file Sortie_Fichier_base.h.
Referenced by set_buffer(), set_toFlush(), and toFlush().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Sortie_Fichier_base.h
src/Kernel/Utilitaires/Sortie_Fichier_base.cpp