TRUST: Op_Conv_Muscl3_VEF_Face Class Reference
Op_Conv_Muscl3_VEF_Face Class Reference
class Op_Conv_Muscl3_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Muscl
#include <Op_Conv_Muscl3_VEF_Face.h>
Public Member Functions
~Op_Conv_Muscl3_VEF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Conv_Muscl3_VEF_Face & self_cast (Objet_U &)
static const
Op_Conv_Muscl3_VEF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
class Op_Conv_Muscl3_VEF_Face
Cette classe represente l'operateur de convection associe a une equation de
transport d'un scalaire.
La discretisation est VEF
Le champ convecte est scalaire ou vecteur de type Champ_P1NC
Le schema de convection est du type Muscl
Definition at line 43 of file Op_Conv_Muscl3_VEF_Face.h.
Constructor & Destructor Documentation
Op_Conv_Muscl3_VEF_Face::~Op_Conv_Muscl3_VEF_Face ()
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
Member Function Documentation
Objet_U * Op_Conv_Muscl3_VEF_Face::cree_instance () [static]
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
int Op_Conv_Muscl3_VEF_Face::duplique () const [virtual]
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
const Type_info * Op_Conv_Muscl3_VEF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
const Type_info * Op_Conv_Muscl3_VEF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
Sortie & Op_Conv_Muscl3_VEF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_VEF_Face.
Definition at line 31 of file Op_Conv_Muscl3_VEF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_Muscl3_VEF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Conv_VEF_Face.
Definition at line 38 of file Op_Conv_Muscl3_VEF_Face.cpp.
References Op_Conv_VEF_Face::alpha_, Cerr, chakravarthy(), Process::exit(), finl, Op_Conv_VEF_Face::LIMITEUR, minmod(), Op_Conv_VEF_Face::muscl, Op_Conv_VEF_Face::ordre, Motcles::search(), superbee(), Op_Conv_VEF_Face::type_op, vanalbada(), and vanleer().
{
  type_op=muscl;
  LIMITEUR=&vanleer;
  ordre=3;
  alpha_=1;
// Lecture eventuelle de alpha_
  Motcle motlu, accouverte = "{" , accfermee = "}" ;
  Motcles les_mots(6);
  {
    les_mots[0] = "alpha";
    les_mots[1] = "minmod";
    les_mots[2] = "vanleer";
    les_mots[3] = "vanalbada";
    les_mots[4] = "chakravarthy";
    les_mots[5] = "superbee";
  }
  s >> motlu;
  if (motlu!=accouverte)
    {
      Cerr << "We wait for a { after reading muscl3 keyword." << finl;
      Process::exit();
    }
  s >> motlu;
  while(motlu!=accfermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          s >> alpha_;
          break;
        case 1 :
          LIMITEUR=&minmod;
          break;
        case 2 :
          LIMITEUR=&vanleer;
          break;
        case 3 :
          LIMITEUR=&vanalbada;
          break;
        case 4 :
          LIMITEUR=&chakravarthy;
          break;
        case 5 :
          LIMITEUR=&superbee;
          break;
        default:
          Cerr << "Keyword " << motlu << " not recognized. List of keywords available:" << finl;
          Cerr << les_mots << finl;
          exit();
          break;
        }
      s >> motlu;
    }
  return s ;
}
const Op_Conv_Muscl3_VEF_Face & Op_Conv_Muscl3_VEF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
Op_Conv_Muscl3_VEF_Face & Op_Conv_Muscl3_VEF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
unsigned Op_Conv_Muscl3_VEF_Face::taille_memoire () const [virtual]
Reimplemented from Op_Conv_VEF_Face.
Definition at line 26 of file Op_Conv_Muscl3_VEF_Face.cpp.
Member Data Documentation
const Type_info Op_Conv_Muscl3_VEF_Face::info_obj [static]
Reimplemented from Op_Conv_VEF_Face.
Definition at line 45 of file Op_Conv_Muscl3_VEF_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Conv_Muscl3_VEF_Face.h
src/VEF/Operateurs/Op_Conv_Muscl3_VEF_Face.cpp