TRUST: Modele_turbulence_scal Class Reference
Modele_turbulence_scal Class Reference
#include <Modele_turbulence_scal.h>
Public Member Functions
Modele_turbulence_scal ()
~Modele_turbulence_scal ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Modele_turbulence_scal & operator= (const Modele_turbulence_scal_base &)
int preparer_calcul ()
void completer ()
void mettre_a_jour (double)
const Champ_Fonc & conductivite_turbulente () const
const Turbulence_paroi_scal & loi_paroi () const
int loi_paroi_non_nulle () const
int sauvegarde (Sortie &) const
int reprise (Entree &)
void discretiser ()
int sauvegarder (Sortie &) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
void imprimer (Sortie &os) const
Appel a l'objet sous-jacent.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Deriv_Modele_turbulence_scal_base
~Deriv_Modele_turbulence_scal_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Modele_turbulence_scal_base ()
Deriv_Modele_turbulence_scal_base (const Deriv_Modele_turbulence_scal_base &)
const Modele_turbulence_scal_base & valeur () const
Modele_turbulence_scal_base & valeur ()
const Modele_turbulence_scal_base * operator-> () const
Modele_turbulence_scal_base * operator-> ()
const Deriv_Modele_turbulence_scal_base & operator= (const Modele_turbulence_scal_base &)
const Deriv_Modele_turbulence_scal_base & operator= (const Deriv_Modele_turbulence_scal_base &)
operator const Modele_turbulence_scal_base & () const
operator Modele_turbulence_scal_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Modele_turbulence_scal & self_cast (Objet_U &)
static const Modele_turbulence_scal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Modele_turbulence_scal_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Modele_turbulence_scal_base & self_cast (Objet_U &)
static const Deriv_Modele_turbulence_scal_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Modele_turbulence_scal_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Deriv_Modele_turbulence_scal_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 29 of file Modele_turbulence_scal.h.
Constructor & Destructor Documentation
Modele_turbulence_scal()
Modele_turbulence_scal::Modele_turbulence_scal ()
Definition at line 21 of file Modele_turbulence_scal.cpp.
~Modele_turbulence_scal()
Modele_turbulence_scal::~Modele_turbulence_scal ()
Definition at line 21 of file Modele_turbulence_scal.cpp.
Member Function Documentation
completer()
void Modele_turbulence_scal::completer (void) inline
Definition at line 69 of file Modele_turbulence_scal.h.
{
  valeur().completer();
}
References Modele_turbulence_scal_base::completer(), and Deriv_Modele_turbulence_scal_base::valeur().
conductivite_turbulente()
const Champ_Fonc & Modele_turbulence_scal::conductivite_turbulente () const inline
Definition at line 79 of file Modele_turbulence_scal.h.
{
  return valeur().conductivite_turbulente();
}
References Modele_turbulence_scal_base::conductivite_turbulente(), and Deriv_Modele_turbulence_scal_base::valeur().
cree_instance()
Objet_U * Modele_turbulence_scal::cree_instance () static
Definition at line 21 of file Modele_turbulence_scal.cpp.
discretiser()
void Modele_turbulence_scal::discretiser () inline
Definition at line 99 of file Modele_turbulence_scal.h.
{
  valeur().discretiser();
}
References Modele_turbulence_scal_base::discretiser(), and Deriv_Modele_turbulence_scal_base::valeur().
duplique()
int Modele_turbulence_scal::duplique () const override virtual
Reimplemented from Deriv_Modele_turbulence_scal_base.
Definition at line 21 of file Modele_turbulence_scal.cpp.
get_info()
const Type_info * Modele_turbulence_scal::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Modele_turbulence_scal_base.
Definition at line 21 of file Modele_turbulence_scal.cpp.
imprimer()
void Modele_turbulence_scal::imprimer (Sortie & os) const inline
Appel a l'objet sous-jacent.
Definition at line 128 of file Modele_turbulence_scal.h.
{
  valeur().imprimer(os);
}
References Modele_turbulence_scal_base::imprimer(), and Deriv_Modele_turbulence_scal_base::valeur().
info()
const Type_info * Modele_turbulence_scal::info () static
Definition at line 21 of file Modele_turbulence_scal.cpp.
loi_paroi()
const Turbulence_paroi_scal & Modele_turbulence_scal::loi_paroi () const inline
Definition at line 84 of file Modele_turbulence_scal.h.
{
  return valeur().loi_paroi();
}
References Modele_turbulence_scal_base::loi_paroi(), and Deriv_Modele_turbulence_scal_base::valeur().
loi_paroi_non_nulle()
int Modele_turbulence_scal::loi_paroi_non_nulle () const inline
Definition at line 89 of file Modele_turbulence_scal.h.
{
  return valeur().loi_paroi_non_nulle();
}
References Modele_turbulence_scal_base::loi_paroi_non_nulle(), and Deriv_Modele_turbulence_scal_base::valeur().
mettre_a_jour()
void Modele_turbulence_scal::mettre_a_jour (double temps) inline
Definition at line 74 of file Modele_turbulence_scal.h.
{
  valeur().mettre_a_jour(temps);
}
References Modele_turbulence_scal_base::mettre_a_jour(), and Deriv_Modele_turbulence_scal_base::valeur().
operator=()
Modele_turbulence_scal & Modele_turbulence_scal::operator= (const Modele_turbulence_scal_base &) inline
preparer_calcul()
int Modele_turbulence_scal::preparer_calcul (void) inline
Definition at line 94 of file Modele_turbulence_scal.h.
{
  return valeur().preparer_calcul();
}
References Modele_turbulence_scal_base::preparer_calcul(), and Deriv_Modele_turbulence_scal_base::valeur().
printOn()
Sortie & Modele_turbulence_scal::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Modele_turbulence_scal_base.
Definition at line 38 of file Modele_turbulence_scal.cpp.
{
  return s << valeur().que_suis_je() << finl;
}
References finl, Objet_U::que_suis_je(), and Deriv_Modele_turbulence_scal_base::valeur().
readOn()
Entree & Modele_turbulence_scal::readOn (Entree & s) override protected virtual
Lit les specifications d'un modele de turbulence
a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Modele_turbulence_scal_base.
Definition at line 58 of file Modele_turbulence_scal.cpp.
{
  Motcle typ;
  s >> typ;
  Motcle nom1("Modele_turbulence_scal_");
  nom1 += typ;
  if (typ == "sous_maille_dyn")
    {
      nom1 += "_";
      Nom disc = equation().discretisation().que_suis_je();
      if(disc=="VEFPreP1B")
        disc="VEF";
      nom1 +=disc;
    }
  Cerr << nom1 << finl;
  DERIV(Modele_turbulence_scal_base)::typer(nom1);
  valeur().associer_eqn(equation());
  valeur().associer(equation().zone_dis(), equation().zone_Cl_dis());
  s >> valeur();
  return s;
}
References Modele_turbulence_scal_base::associer(), Modele_turbulence_scal_base::associer_eqn(), Cerr, DERIV, Equation_base::discretisation(), MorEqn::equation(), finl, Objet_U::que_suis_je(), Deriv_::typer(), and Deriv_Modele_turbulence_scal_base::valeur().
reprendre()
int Modele_turbulence_scal::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 109 of file Modele_turbulence_scal.h.
{
  return valeur().reprendre(is);
}
References Modele_turbulence_scal_base::reprendre(), and Deriv_Modele_turbulence_scal_base::valeur().
reprise()
int Modele_turbulence_scal::reprise (Entree &) inline
sauvegarde()
int Modele_turbulence_scal::sauvegarde (Sortie &) const inline
sauvegarder()
int Modele_turbulence_scal::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 104 of file Modele_turbulence_scal.h.
{
  return valeur().sauvegarder(os);
}
References Modele_turbulence_scal_base::sauvegarder(), and Deriv_Modele_turbulence_scal_base::valeur().
self_cast() [1/2]
const Modele_turbulence_scal & Modele_turbulence_scal::self_cast (const Objet_U & r) static
Definition at line 21 of file Modele_turbulence_scal.cpp.
self_cast() [2/2]
Modele_turbulence_scal & Modele_turbulence_scal::self_cast (Objet_U & r) static
Definition at line 21 of file Modele_turbulence_scal.cpp.
taille_memoire()
unsigned Modele_turbulence_scal::taille_memoire () const override virtual
Reimplemented from Deriv_Modele_turbulence_scal_base.
Definition at line 21 of file Modele_turbulence_scal.cpp.
Member Data Documentation
info_obj
const Type_info Modele_turbulence_scal::info_obj static
Definition at line 32 of file Modele_turbulence_scal.h.
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Modele_turbulence_scal.h
src/ThHyd/Modele_turbulence_base/Modele_turbulence_scal.cpp