TRUST: Interpolation_IBM_hybrid Class Reference
Interpolation_IBM_hybrid Class Reference
: class Interpolation_IBM_hybrid
<Description of class Interpolation_IBM_hybrid>
#include <Interpolation_IBM_hybrid.h>
Public Member Functions
Interpolation_IBM_hybrid ()
~Interpolation_IBM_hybrid ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void discretise (const Discretisation_base &, Zone_dis_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Interpolation_IBM_hybrid & self_cast (Objet_U &)
static const
Interpolation_IBM_hybrid & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Friends
class Source_PDF_EF
Detailed Description
: class Interpolation_IBM_hybrid
<Description of class Interpolation_IBM_hybrid>
Definition at line 39 of file Interpolation_IBM_hybrid.h.
Constructor & Destructor Documentation
Interpolation_IBM_hybrid::Interpolation_IBM_hybrid ()
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
Interpolation_IBM_hybrid::~Interpolation_IBM_hybrid ()
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
Member Function Documentation
Objet_U * Interpolation_IBM_hybrid::cree_instance () [static]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
void Interpolation_IBM_hybrid::discretise (const Discretisation_base & dis, Zone_dis_base & la_zone_EF) [virtual]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 48 of file Interpolation_IBM_hybrid.cpp.
References Champ_base::affecter(), Cerr, Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Interpolation_IBM_base::corresp_elems_, Discretisation_base::discretiser_champ(), finl, Interpolation_IBM_mean_gradient_proto::is_dirichlet_, Interpolation_IBM_mean_gradient_proto::is_dirichlet_lu_, Interpolation_IBM_mean_gradient_proto::solid_elems_, Interpolation_IBM_mean_gradient_proto::solid_elems_lu_, Interpolation_IBM_base::solid_points_, and Deriv_Champ_Don_base::valeur().
{
  Cerr << "(IBM) Warning! Interpolation IBM_hybrid has no validation test case." << finl;
  Interpolation_IBM_elem_fluid::discretise(dis,la_zone_EF);
  dis.discretiser_champ("champ_sommets",la_zone_EF,"solid_elems","none",1,0., solid_elems_);
  solid_elems_.valeur().affecter(solid_elems_lu_);
  dis.discretiser_champ("champ_sommets",la_zone_EF,"is_dirichlet","none",1,0., is_dirichlet_);
  is_dirichlet_.valeur().affecter(is_dirichlet_lu_);
  computeSommetsVoisins(la_zone_EF, solid_points_, corresp_elems_);
}
int Interpolation_IBM_hybrid::duplique () const [virtual]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
const Type_info * Interpolation_IBM_hybrid::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
const Type_info * Interpolation_IBM_hybrid::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
Sortie & Interpolation_IBM_hybrid::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 31 of file Interpolation_IBM_hybrid.cpp.
{
  Objet_U::printOn( os );
  return os;
}
Entree & Interpolation_IBM_hybrid::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
< XD_ADD_P field_base Node field of booleans indicating whether the node belong to an element where the interface is
< XD_ADD_P field_base Node field giving the element number containing the solid point
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 37 of file Interpolation_IBM_hybrid.cpp.
References Param::ajouter(), Interpolation_IBM_mean_gradient_proto::is_dirichlet_lu_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Interpolation_IBM_elem_fluid::set_param(), and Interpolation_IBM_mean_gradient_proto::solid_elems_lu_.
{
// Interpolation_IBM_elem_fluid::readOn(is);
  Param param(que_suis_je());
  Interpolation_IBM_elem_fluid::set_param(param);
  param.ajouter("est_dirichlet",&is_dirichlet_lu_,Param::REQUIRED);   //!< XD_ADD_P field_base Node field of booleans indicating whether the node belong to an element where the interface is
  param.ajouter("elements_solides",&solid_elems_lu_,Param::REQUIRED); //!< XD_ADD_P field_base Node field giving the element number containing the solid point
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Interpolation_IBM_hybrid & Interpolation_IBM_hybrid::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
Interpolation_IBM_hybrid & Interpolation_IBM_hybrid::self_cast (Objet_U & r) [static]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
unsigned Interpolation_IBM_hybrid::taille_memoire () const [virtual]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 28 of file Interpolation_IBM_hybrid.cpp.
Friends And Related Function Documentation
friend class Source_PDF_EF [friend]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 47 of file Interpolation_IBM_hybrid.h.
Member Data Documentation
const Type_info Interpolation_IBM_hybrid::info_obj [static]
Reimplemented from Interpolation_IBM_elem_fluid.
Definition at line 41 of file Interpolation_IBM_hybrid.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_hybrid.h
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM_hybrid.cpp