TRUST: Champ_Uniforme_Morceaux_inst Class Reference
Champ_Uniforme_Morceaux_inst Class Reference
Classe Champ_Uniforme_Morceaux_inst
Representent un champ constant par morceaux dans l'espace et dependant
du temps.
#include <Champ_Uniforme_Morceaux_inst.h>
Public Member Functions
Champ_Uniforme_Morceaux_inst ()
~Champ_Uniforme_Morceaux_inst ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double)
Effectue une mise a jour en temps du champ.
virtual void me_calculer (double t)=0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Champ_Uniforme_Morceaux_inst & self_cast (Objet_U &)
static const
Champ_Uniforme_Morceaux_inst & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Detailed Description
Classe Champ_Uniforme_Morceaux_inst
Representent un champ constant par morceaux dans l'espace et dependant
du temps.
Definition at line 42 of file Champ_Uniforme_Morceaux_inst.h.
Constructor & Destructor Documentation
Champ_Uniforme_Morceaux_inst::Champ_Uniforme_Morceaux_inst ()
Definition at line 26 of file Champ_Uniforme_Morceaux_inst.cpp.
Champ_Uniforme_Morceaux_inst::~Champ_Uniforme_Morceaux_inst ()
Definition at line 26 of file Champ_Uniforme_Morceaux_inst.cpp.
Member Function Documentation
virtual int Champ_Uniforme_Morceaux_inst::duplique () const [pure virtual]
Reimplemented from Champ_Uniforme_Morceaux.
Implemented in Champ_Uniforme_Morceaux_Tabule_Temps.
const Type_info * Champ_Uniforme_Morceaux_inst::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 26 of file Champ_Uniforme_Morceaux_inst.cpp.
const Type_info * Champ_Uniforme_Morceaux_inst::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 26 of file Champ_Uniforme_Morceaux_inst.cpp.
virtual void Champ_Uniforme_Morceaux_inst::me_calculer (double t) [pure virtual]
Implemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Referenced by mettre_a_jour().
void Champ_Uniforme_Morceaux_inst::mettre_a_jour (double un_temps) [inline, virtual]
Effectue une mise a jour en temps du champ.
Reimplemented from Champ_Don_base.
Definition at line 72 of file Champ_Uniforme_Morceaux_inst.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(un_temps);
  changer_temps(un_temps);
}
Sortie & Champ_Uniforme_Morceaux_inst::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 44 of file Champ_Uniforme_Morceaux_inst.cpp.
{
  return os ;
}
Entree & Champ_Uniforme_Morceaux_inst::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 64 of file Champ_Uniforme_Morceaux_inst.cpp.
{
  return is;
}
const Champ_Uniforme_Morceaux_inst & Champ_Uniforme_Morceaux_inst::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 26 of file Champ_Uniforme_Morceaux_inst.cpp.
Champ_Uniforme_Morceaux_inst & Champ_Uniforme_Morceaux_inst::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 26 of file Champ_Uniforme_Morceaux_inst.cpp.
Member Data Documentation
const Type_info Champ_Uniforme_Morceaux_inst::info_obj [static]
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_Uniforme_Morceaux_Tabule_Temps.
Definition at line 45 of file Champ_Uniforme_Morceaux_inst.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Uniforme_Morceaux_inst.h
src/Kernel/Champs/Champ_Uniforme_Morceaux_inst.cpp