TRUST: SSOR Class Reference
SSOR Class Reference
#include <SSOR.h>
Public Member Functions
~SSOR ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SSOR ()
double get_omega ()
void set_omega (double x)
int get_flag_updated_input () const override
Public Member Functions inherited from Precond_base
~Precond_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Precond_base ()
void reinit (Init_Status x=REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
void set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
void prepare (const Matrice_Base &, const DoubleVect &src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
virtual int supporte_matrice_morse_sym ()
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Init_Status get_status ()
virtual int get_flag_updated_input () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static SSOR & self_cast (Objet_U &)
static const SSOR & self_cast (const Objet_U &)
Static Public Member Functions inherited from Precond_base
static const Type_info * info ()
static Precond_base & self_cast (Objet_U &)
static const Precond_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Precond_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int preconditionner_ (const Matrice_Base &, const DoubleVect &secmem, DoubleVect &solution) override
Calcule la solution du systeme lineaire: A * solution = b avec la methode de relaxation SSOR.
void prepare_ (const Matrice_Base &, const DoubleVect &secmem) override
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
void ssor (const Matrice_Morse_Sym &, DoubleVect &)
void ssor (const Matrice_Bloc_Sym &, DoubleVect &)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)=0
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double omega_
int algo_fortran_
int avec_assert_
IntTab items_a_traiter_
int algo_items_communs_
MD_Vector md_secmem_
int line_size_
ArrOfDouble omega_diag_
Protected Attributes inherited from Precond_base
int echange_ev_solution_
Additional Inherited Members
Public Types inherited from Precond_base
enum Init_Status { READY = 0 , REINIT_COEFF = 1 , REINIT_ALL = 2 }
Detailed Description
Definition at line 25 of file SSOR.h.
Constructor & Destructor Documentation
~SSOR()
SSOR::~SSOR ()
Definition at line 25 of file SSOR.cpp.
SSOR()
SSOR::SSOR ()
Definition at line 27 of file SSOR.cpp.
: omega_(1.6), algo_fortran_(-1), avec_assert_(-1), algo_items_communs_(-1), line_size_(0) { }
Member Function Documentation
cree_instance()
Objet_U * SSOR::cree_instance () static
Definition at line 25 of file SSOR.cpp.
duplique()
int SSOR::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file SSOR.cpp.
get_flag_updated_input()
int SSOR::get_flag_updated_input () const inline override virtual
Reimplemented from Precond_base.
Definition at line 39 of file SSOR.h.
{ return 0; }
get_info()
const Type_info * SSOR::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Precond_base.
Definition at line 25 of file SSOR.cpp.
get_omega()
double SSOR::get_omega () inline
Definition at line 31 of file SSOR.h.
{ return omega_; }
References omega_.
info()
const Type_info * SSOR::info () static
Definition at line 25 of file SSOR.cpp.
preconditionner_()
int SSOR::preconditionner_ (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override protected virtual
Calcule la solution du systeme lineaire: A * solution = b avec la methode de relaxation SSOR.
Implements Precond_base.
Definition at line 89 of file SSOR.cpp.
{
// pour compatibilite historique:
  if (omega_ <= 0. || omega_ >= 2)
    {
      operator_egal(solution, b);
      return 1;
    }
  operator_egal(solution, b);
  if (sub_type(Matrice_Morse_Sym, la_matrice))
    {
      const Matrice_Morse_Sym& matrice = ref_cast(Matrice_Morse_Sym, la_matrice);
      ssor(matrice, solution);
    }
  else if (sub_type(Matrice_Bloc_Sym, la_matrice))
    {
// Matrice correspondant a un vecteur multi-localisation (MD_Vector_composite)
      const Matrice_Bloc_Sym& matrice = ref_cast(Matrice_Bloc_Sym, la_matrice);
      ssor(matrice, solution);
    }
  else if (sub_type(Matrice_Bloc, la_matrice))
    {
// On suppose une matrice reelle-reelle et une matrice reelle-virtuelle
      const Matrice_Bloc& mat = ref_cast(Matrice_Bloc, la_matrice);
      const Matrice_Morse_Sym& matrice = ref_cast(Matrice_Morse_Sym, mat.get_bloc(0, 0).valeur());
      ssor(matrice, solution);
    }
  else
    {
      Cerr << "SSOR::preconditionner not coded for type " << la_matrice.que_suis_je() << finl;
      exit();
    }
  if (echange_ev_solution_) solution.echange_espace_virtuel();
  return 1;
}
References Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Precond_base::echange_ev_solution_, Process::exit(), finl, Matrice_Bloc::get_bloc(), operator_egal(), Objet_U::que_suis_je(), ref_cast, ssor(), sub_type, and Deriv_Matrice_Base::valeur().
prepare_()
void SSOR::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
< size() est invalide, les items reels ne sont pas groupes a debut !
< Il y a des items partages parmi les items reels
Reimplemented from Precond_base.
Definition at line 48 of file SSOR.cpp.
{
  if (get_status() >= REINIT_ALL)
    {
      md_secmem_ = secmem.get_md_vector();
      line_size_ = secmem.line_size();
// Pour le prochain preconditionnement, verifier la matrice
      avec_assert_ = 1;
      if (nproc() == 1 || !(md_secmem_.non_nul())) algo_items_communs_ = 0;
      else
        {
// Nombre d'items sequentiels sur ce proc
          const int sz_tot = secmem.size_totale();
          items_a_traiter_.reset();
          items_a_traiter_.resize(sz_tot / line_size_, line_size_, Array_base::NOCOPY_NOINIT);
          items_a_traiter_.set_md_vector(md_secmem_);
          int n = MD_Vector_tools::get_sequential_items_flags(md_secmem_, items_a_traiter_, line_size_);
          int sz = md_secmem_.valeur().get_nb_items_reels();
          if (sz < 0) //!< size() est invalide, les items reels ne sont pas groupes a debut !
            algo_items_communs_ = 1;
          else
            {
              assert(sz >= n);
              if (mp_sum(sz) > mp_sum(n)) algo_items_communs_ = 1; //!< Il y a des items partages parmi les items reels
              else
                {
                  algo_items_communs_ = 0;
                  items_a_traiter_.reset();
                }
            }
        }
    }
  if (get_status() >= REINIT_COEFF) { /* Do nothing */ }
  Precond_base::prepare_(la_matrice, secmem);
}
References algo_items_communs_, avec_assert_, TRUSTVect< _TYPE_ >::get_md_vector(), MD_Vector_base::get_nb_items_reels(), MD_Vector_tools::get_sequential_items_flags(), Precond_base::get_status(), items_a_traiter_, TRUSTVect< _TYPE_ >::line_size(), line_size_, md_secmem_, Process::mp_sum(), Array_base::NOCOPY_NOINIT, MD_Vector::non_nul(), Process::nproc(), Precond_base::prepare_(), Precond_base::REINIT_ALL, Precond_base::REINIT_COEFF, TRUSTTab< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::resize(), TRUSTTab< _TYPE_ >::set_md_vector(), TRUSTVect< _TYPE_ >::size_totale(), and MD_Vector::valeur().
printOn()
Sortie & SSOR::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 29 of file SSOR.cpp.
{
  s << " { omega  "<<omega_ << " } ";
  return s;
}
References omega_.
readOn()
Entree & SSOR::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 35 of file SSOR.cpp.
{
  Param param(que_suis_je());
  param.ajouter("omega", &omega_);
  param.lire_avec_accolades(is);
  if (omega_ <= 0. || omega_ >= 2.)
    {
      Cerr << "SSOR::readOn, omega is not within [0, 2]: SSOR not activated (you should use precond nul instead) "  << finl;
    }
  return is;
}
References Param::ajouter(), Cerr, finl, Param::lire_avec_accolades(), omega_, and Objet_U::que_suis_je().
self_cast() [1/2]
const SSOR & SSOR::self_cast (const Objet_U & r) static
Definition at line 25 of file SSOR.cpp.
self_cast() [2/2]
SSOR & SSOR::self_cast (Objet_U & r) static
Definition at line 25 of file SSOR.cpp.
set_omega()
void SSOR::set_omega (double x) inline
Definition at line 32 of file SSOR.h.
  {
    omega_ = x;
    reinit(REINIT_COEFF);
  }
References omega_, Precond_base::reinit(), and Precond_base::REINIT_COEFF.
ssor() [1/2]
void SSOR::ssor (const Matrice_Bloc_Sym & matrice, DoubleVect & solution) protected
Definition at line 729 of file SSOR.cpp.
{
  DoubleTab_parts s_parts(solution);
  ConstIntTab_parts items_parts;
  if (algo_items_communs_) items_parts.initialize(items_a_traiter_);
  const int nb_parts = s_parts.size();
  assert(s_parts.size() == nb_parts);
  assert(matrice.nb_bloc_lignes() == nb_parts);
// Descente
  int i_part;
  for (i_part = 0; i_part < nb_parts; i_part++)
    {
      const Matrice_Bloc& matrice0 = ref_cast(Matrice_Bloc, matrice.get_bloc(i_part, i_part).valeur());
      const Matrice_Morse_Sym& MB00 = ref_cast(Matrice_Morse_Sym, matrice0.get_bloc(0, 0).valeur());
      DoubleVect& partie = s_parts[i_part];
      if (algo_items_communs_) descente_diag_ok_assert(omega_, MB00.get_tab1(), MB00.get_tab2(), MB00.get_coeff(), partie, items_parts[i_part]);
      else descente_diag_ok_assert(omega_, MB00.get_tab1(), MB00.get_tab2(), MB00.get_coeff(), partie);
// blocs extra-diagonaux
      for (int j_part = i_part + 1; j_part < nb_parts; j_part++)
        {
          const Matrice_Bloc& Aij = ref_cast(Matrice_Bloc, matrice.get_bloc(i_part, j_part).valeur());
          const Matrice_Morse& MB00bis = ref_cast(Matrice_Morse, Aij.get_bloc(0, 0).valeur());
          DoubleVect& partie_j = s_parts[j_part];
// Attention: le test sur les items communs concerne les lignes de la matrice, pas les colonnes (on passe items_parts[i_part], pas j_part)
// (note BM: je crois que la version precedente etait buggee mais ca ne s'est pas vu parce que la matrice elem-elem arrive en premier et qu'il n'y a pas d'items communs sur les elements)
          if (algo_items_communs_) descente_bloc_extradiag_assert(MB00bis.get_tab1(), MB00bis.get_tab2(), MB00bis.get_coeff(), partie, partie_j, items_parts[i_part]);
          else descente_bloc_extradiag_assert(MB00bis.get_tab1(), MB00bis.get_tab2(), MB00bis.get_coeff(), partie, partie_j);
        }
    }
// Traitement de la diagonale
  for (i_part = 0; i_part < nb_parts; i_part++)
    {
      const Matrice_Bloc& matrice0 = ref_cast(Matrice_Bloc, matrice.get_bloc(i_part, i_part).valeur());
      const Matrice_Morse_Sym& MB00 = ref_cast(Matrice_Morse_Sym, matrice0.get_bloc(0, 0).valeur());
      DoubleVect& partie = s_parts[i_part];
      traite_diagonale(omega_, MB00.get_tab1(), MB00.get_tab2(), MB00.get_coeff(), partie);
    }
// Remontee
  for (i_part = nb_parts - 1; i_part >= 0; i_part--)
    {
      const Matrice_Bloc& matrice0 = ref_cast(Matrice_Bloc, matrice.get_bloc(i_part, i_part).valeur());
      const Matrice_Morse_Sym& MB00bis = ref_cast(Matrice_Morse_Sym, matrice0.get_bloc(0, 0).valeur());
      DoubleVect& partie = s_parts[i_part];
      if (algo_items_communs_) remontee_diag_ok_assert(omega_, MB00bis.get_tab1(), MB00bis.get_tab2(), MB00bis.get_coeff(), partie, items_parts[i_part]);
      else remontee_diag_ok_assert(omega_, MB00bis.get_tab1(), MB00bis.get_tab2(), MB00bis.get_coeff(), partie);
// Blocs extra-diagonaux (parcours horizontal au lieu de vertical)
      for (int j_part = 0; j_part < i_part; j_part++)
        {
          const Matrice_Bloc& Aij = ref_cast(Matrice_Bloc, matrice.get_bloc(j_part, i_part).valeur());
          const Matrice_Morse& MB00 = ref_cast(Matrice_Morse, Aij.get_bloc(0, 0).valeur());
          DoubleVect& partie_j = s_parts[j_part];
// Attention: le test sur les items communs concerne les lignes de la matrice, pas les colonnes (on passe items_parts[i_part], pas j_part)
          if (algo_items_communs_) remontee_bloc_extradiag_assert(MB00.get_tab1(), MB00.get_tab2(), MB00.get_coeff(), partie_j, partie, items_parts[j_part]);
          else remontee_bloc_extradiag_assert(MB00.get_tab1(), MB00.get_tab2(), MB00.get_coeff(), partie_j, partie);
        }
    }
}
References algo_items_communs_, descente_bloc_extradiag_assert(), descente_diag_ok_assert(), Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), ConstTRUSTTab_parts< _TYPE_ >::initialize(), items_a_traiter_, Matrice_Bloc::nb_bloc_lignes(), omega_, ref_cast, remontee_bloc_extradiag_assert(), remontee_diag_ok_assert(), TRUSTTab_parts< _TYPE_ >::size(), traite_diagonale(), and Deriv_Matrice_Base::valeur().
ssor() [2/2]
void SSOR::ssor (const Matrice_Morse_Sym & matrice, DoubleVect & solution) protected
< Ne pas reverifier au prochain preconditionnement...
Definition at line 661 of file SSOR.cpp.
{
  const ArrOfInt& tab1 = matrice.get_tab1(), &tab2 = matrice.get_tab2();
  const ArrOfDouble& coeff = matrice.get_coeff();
  if (tab2.size_array() > 0 && tab2[0] == 1)
    {
// La diagonale est presente dans la matrice
      if (avec_assert_)
        {
          if (algo_items_communs_)
            {
              descente_assert(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
              remontee_assert(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
            }
          else
            {
              descente_assert(omega_, tab1, tab2, coeff, solution);
              remontee_assert(omega_, tab1, tab2, coeff, solution);
            }
        }
      else
        {
          if (algo_items_communs_)
            {
              descente(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
              remontee(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
            }
          else
            {
              descente(omega_, tab1, tab2, coeff, solution);
              remontee(omega_, tab1, tab2, coeff, solution);
            }
        }
    }
  else
    {
// Pas de diagonale stockee, on suppose qu'on a que des 1 sur la diagonale (preconditionnement diagonal)
      if (avec_assert_)
        {
          if (algo_items_communs_)
            {
              descente_assert_precond_diag(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
              remontee_assert_precond_diag(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
            }
          else
            {
              descente_assert_precond_diag(omega_, tab1, tab2, coeff, solution);
              remontee_assert_precond_diag(omega_, tab1, tab2, coeff, solution);
            }
        }
      else
        {
          if (algo_items_communs_)
            {
              descente_precond_diag(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
              remontee_precond_diag(omega_, tab1, tab2, coeff, solution, items_a_traiter_);
            }
          else
            {
              descente_precond_diag(omega_, tab1, tab2, coeff, solution);
              remontee_precond_diag(omega_, tab1, tab2, coeff, solution);
            }
        }
    }
  avec_assert_ = 0; //!< Ne pas reverifier au prochain preconditionnement...
}
References algo_items_communs_, avec_assert_, coeff, descente(), descente_assert(), descente_assert_precond_diag(), descente_precond_diag(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), items_a_traiter_, omega_, remontee(), remontee_assert(), remontee_assert_precond_diag(), and remontee_precond_diag().
Referenced by preconditionner_().
taille_memoire()
unsigned SSOR::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file SSOR.cpp.
Member Data Documentation
algo_fortran_
int SSOR::algo_fortran_ protected
Definition at line 49 of file SSOR.h.
algo_items_communs_
int SSOR::algo_items_communs_ protected
Definition at line 54 of file SSOR.h.
Referenced by prepare_(), and ssor().
avec_assert_
int SSOR::avec_assert_ protected
Definition at line 49 of file SSOR.h.
Referenced by prepare_(), and ssor().
info_obj
const Type_info SSOR::info_obj static
Definition at line 27 of file SSOR.h.
items_a_traiter_
IntTab SSOR::items_a_traiter_ protected
Definition at line 52 of file SSOR.h.
Referenced by prepare_(), and ssor().
line_size_
int SSOR::line_size_ protected
Definition at line 57 of file SSOR.h.
Referenced by prepare_().
md_secmem_
MD_Vector SSOR::md_secmem_ protected
Definition at line 56 of file SSOR.h.
Referenced by prepare_().
omega_
double SSOR::omega_ protected
Definition at line 48 of file SSOR.h.
Referenced by get_omega(), printOn(), readOn(), set_omega(), and ssor().
omega_diag_
ArrOfDouble SSOR::omega_diag_ protected
Definition at line 59 of file SSOR.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/SSOR.h
src/Kernel/Math/SolvSys/SSOR.cpp