TRUST: Matrice_SuperMorse Class Reference
Matrice_SuperMorse Class Reference
: Matrice avec un stockage encore plus creux que Matrice_Morse:
On stocke uniquement les lignes non vides (economie sur la taille de tab1_,
tab2_ et coeff_ restent identiques)
#include <Matrice_SuperMorse.h>
Public Member Functions
const int & tab1 (int i) const
i de 0 a n
int & tab1 (int i)
const int & tab2 (int i) const
i de 0 a nnz-1
int & tab2 (int i)
const double & coeff (int i) const
i de 0 a nnz-1
double & coeff (int i)
ArrOfInt & get_set_tab1 (void)
ArrOfInt & get_set_tab2 (void)
ArrOfDouble & get_set_coeff (void)
const ArrOfInt & get_tab1 (void) const
const ArrOfInt & get_tab2 (void) const
const ArrOfDouble & get_coeff (void) const
double ajouter_mult_vect_et_prodscal (const DoubleVect &x, DoubleVect &resu) const
Calcul de "resu += MATRICE * x" et d'un produit scalaire
(c'est une brique de base pour le gradient conjugue, voir class Solv_GCP)
Valeur de retour:
partie locale a ce processeur de "(MATRICE * x) scalaire x"
(attention: le produit scalaire compte toutes les lignes de la matrice
les items communs ne sont pas supprimes !)
(attention: c'est different de resu scalaire x !)
Public Attributes
ArrOfInt lignes_non_vides_
Protected Attributes
ArrOfInt tab1_
ArrOfInt tab2_
ArrOfDouble coeff_
Detailed Description
: Matrice avec un stockage encore plus creux que Matrice_Morse:
On stocke uniquement les lignes non vides (economie sur la taille de tab1_,
tab2_ et coeff_ restent identiques)
Definition at line 23 of file Matrice_SuperMorse.h.
Member Function Documentation
ajouter_mult_vect_et_prodscal()
double Matrice_SuperMorse::ajouter_mult_vect_et_prodscal (const DoubleVect & x, DoubleVect & resu) const
Calcul de "resu += MATRICE * x" et d'un produit scalaire
(c'est une brique de base pour le gradient conjugue, voir class Solv_GCP)
Valeur de retour:
partie locale a ce processeur de "(MATRICE * x) scalaire x"
(attention: le produit scalaire compte toutes les lignes de la matrice
les items communs ne sont pas supprimes !)
(attention: c'est different de resu scalaire x !)
< decalage de 1 car on va indexer par des indices fortran
< idem
< indice du coeff courant dans tab2 et coeff
Definition at line 25 of file Matrice_SuperMorse.cpp.
{
  assert(resu.size() == x.size());
  const int nb_lignes = lignes_non_vides_.size_array();
  const int *tab_lignes = lignes_non_vides_.addr();
// Le premier indice de tab1_ qui va nous interesser est le deuxieme du tableau
// (le premier du tableau est forcement 1)
  assert(tab1_[0] == 1);
  const int *tab1_ptr = tab1_.addr() + 1;
  assert(tab1_.size_array() == nb_lignes + 1);
  const int *tab2_ptr = tab2_.addr();
  const double *coeff_ptr = coeff_.addr();
  const double *x_ptr = x.addr() - 1; //!< decalage de 1 car on va indexer par des indices fortran
  double *resu_ptr = resu.addr() - 1; //!< idem
  int n = 1; //!< indice du coeff courant dans tab2 et coeff
  double prod_scal_local = 0;
  for (int i = 0; i < nb_lignes; i++)
    {
// Numero de la ligne de la matrice:
      const int i_ligne = *(tab_lignes++);
      assert(i_ligne >= 1 && i_ligne <= resu.size_array());
      double r = 0.;
// Indice de fin des coeffs de cette ligne dans tab2 et coeff
      const int n_fin = *(tab1_ptr++);
      for (; n < n_fin; n++)
        {
          const int colonne = *(tab2_ptr++);
          assert(colonne >= 1 && colonne <= x.size_array());
          const double coef = *(coeff_ptr++);
          const double xb = x_ptr[colonne];
          r += coef * xb;
        }
      resu_ptr[i_ligne] += r;
// attention: on ne veut calculer que le produit scalaire entre x et la partie ajoutee a resu
// (pas avec les valeurs existantes de resu avant l'appel)
      prod_scal_local += r * x_ptr[i_ligne];
    }
  return prod_scal_local;
}
References TRUSTArray< _TYPE_ >::addr(), coeff_, lignes_non_vides_, TRUSTVect< _TYPE_ >::size(), TRUSTArray< _TYPE_ >::size_array(), tab1_, and tab2_.
Referenced by Solv_GCP::resoudre_().
coeff() [1/2]
double & Matrice_SuperMorse::coeff (int i) inline
Definition at line 31 of file Matrice_SuperMorse.h.
{ return coeff_[i]; }
References coeff_.
coeff() [2/2]
const double & Matrice_SuperMorse::coeff (int i) const inline
i de 0 a nnz-1
Definition at line 30 of file Matrice_SuperMorse.h.
References coeff_.
get_coeff()
const ArrOfDouble & Matrice_SuperMorse::get_coeff (void) const inline
Definition at line 39 of file Matrice_SuperMorse.h.
{ return coeff_ ; }
References coeff_.
get_set_coeff()
ArrOfDouble & Matrice_SuperMorse::get_set_coeff (void) inline
Definition at line 35 of file Matrice_SuperMorse.h.
{ return coeff_ ; }
References coeff_.
Referenced by Solv_GCP::prepare_data().
get_set_tab1()
ArrOfInt & Matrice_SuperMorse::get_set_tab1 (void) inline
Definition at line 33 of file Matrice_SuperMorse.h.
{ return tab1_ ; }
References tab1_.
Referenced by Solv_GCP::prepare_data().
get_set_tab2()
ArrOfInt & Matrice_SuperMorse::get_set_tab2 (void) inline
Definition at line 34 of file Matrice_SuperMorse.h.
{ return tab2_ ; }
References tab2_.
Referenced by Solv_GCP::prepare_data().
get_tab1()
const ArrOfInt & Matrice_SuperMorse::get_tab1 (void) const inline
Definition at line 37 of file Matrice_SuperMorse.h.
{ return tab1_ ; }
References tab1_.
get_tab2()
const ArrOfInt & Matrice_SuperMorse::get_tab2 (void) const inline
Definition at line 38 of file Matrice_SuperMorse.h.
{ return tab2_ ; }
References tab2_.
tab1() [1/2]
int & Matrice_SuperMorse::tab1 (int i) inline
Definition at line 27 of file Matrice_SuperMorse.h.
{ return tab1_[i]; }
References tab1_.
tab1() [2/2]
const int & Matrice_SuperMorse::tab1 (int i) const inline
i de 0 a n
Definition at line 26 of file Matrice_SuperMorse.h.
References tab1_.
tab2() [1/2]
int & Matrice_SuperMorse::tab2 (int i) inline
Definition at line 29 of file Matrice_SuperMorse.h.
{ return tab2_[i]; }
References tab2_.
tab2() [2/2]
const int & Matrice_SuperMorse::tab2 (int i) const inline
i de 0 a nnz-1
Definition at line 28 of file Matrice_SuperMorse.h.
References tab2_.
Member Data Documentation
coeff_
ArrOfDouble Matrice_SuperMorse::coeff_ protected
Definition at line 49 of file Matrice_SuperMorse.h.
Referenced by ajouter_mult_vect_et_prodscal(), coeff(), get_coeff(), and get_set_coeff().
lignes_non_vides_
ArrOfInt Matrice_SuperMorse::lignes_non_vides_
Definition at line 43 of file Matrice_SuperMorse.h.
Referenced by ajouter_mult_vect_et_prodscal(), and Solv_GCP::prepare_data().
tab1_
ArrOfInt Matrice_SuperMorse::tab1_ protected
Definition at line 48 of file Matrice_SuperMorse.h.
Referenced by ajouter_mult_vect_et_prodscal(), get_set_tab1(), get_tab1(), and tab1().
tab2_
ArrOfInt Matrice_SuperMorse::tab2_ protected
Definition at line 48 of file Matrice_SuperMorse.h.
Referenced by ajouter_mult_vect_et_prodscal(), get_set_tab2(), get_tab2(), and tab2().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_SuperMorse.h
src/Kernel/Math/Matrices/Matrice_SuperMorse.cpp