TRUST: Eval_Turbulence Class Reference
Eval_Turbulence Class Reference
class Eval_Turbulence
Implements all stuff related to turbulence for VDF evaluators.
#include <Eval_Turbulence.h>
Public Member Functions
virtual ~Eval_Turbulence ()
virtual void associer_loipar (const Turbulence_paroi_scal &loi_paroi)
virtual void init_ind_fluctu_term ()
void update_equivalent_distance ()
Protected Attributes
Ref_Turbulence_paroi_scal loipar
DoubleVects equivalent_distance
Detailed Description
class Eval_Turbulence
Implements all stuff related to turbulence for VDF evaluators.
Definition at line 25 of file Eval_Turbulence.h.
Constructor & Destructor Documentation
~Eval_Turbulence()
virtual Eval_Turbulence::~Eval_Turbulence () inline virtual
Definition at line 29 of file Eval_Turbulence.h.
{}
Member Function Documentation
associer_loipar()
virtual void Eval_Turbulence::associer_loipar (const Turbulence_paroi_scal & loi_paroi) inline virtual
Reimplemented in Eval_Dift_VDF_const_Elem, and Eval_Dift_VDF_var_Elem.
Definition at line 30 of file Eval_Turbulence.h.
{ loipar = loi_paroi; }
References loipar.
Referenced by Eval_Dift_VDF_const_Elem::associer_loipar(), and Eval_Dift_VDF_var_Elem::associer_loipar().
init_ind_fluctu_term()
virtual void Eval_Turbulence::init_ind_fluctu_term () inline virtual
Reimplemented in Eval_Dift_VDF_const_Elem, and Eval_Dift_VDF_var_Elem.
Definition at line 31 of file Eval_Turbulence.h.
{ /* do nothing */}
update_equivalent_distance()
void Eval_Turbulence::update_equivalent_distance ()
Definition at line 22 of file Eval_Turbulence.cpp.
{
  if (loipar.non_nul())
    {
      int s=loipar->tab_equivalent_distance_size();
      equivalent_distance.dimensionner(s);
      for(int i=0; i<s; i++) equivalent_distance[i].ref(loipar->tab_equivalent_distance(i));
    }
}
References vect_impl::dimensionner(), equivalent_distance, loipar, O_U_Ptr::non_nul(), Turbulence_paroi_scal::tab_equivalent_distance(), and Turbulence_paroi_scal::tab_equivalent_distance_size().
Referenced by Eval_Dift_VDF_const::mettre_a_jour(), Eval_Dift_VDF_Multi_inco_const::mettre_a_jour(), Eval_Dift_VDF_Multi_inco_var::mettre_a_jour(), and Eval_Dift_VDF_var::mettre_a_jour().
Member Data Documentation
equivalent_distance
DoubleVects Eval_Turbulence::equivalent_distance protected
Definition at line 36 of file Eval_Turbulence.h.
Referenced by Eval_Dift_VDF_const::get_equivalent_distance(), Eval_Dift_VDF_Multi_inco_const::get_equivalent_distance(), Eval_Dift_VDF_Multi_inco_var::get_equivalent_distance(), Eval_Dift_VDF_var::get_equivalent_distance(), and update_equivalent_distance().
loipar
Ref_Turbulence_paroi_scal Eval_Turbulence::loipar protected
Definition at line 35 of file Eval_Turbulence.h.
Referenced by associer_loipar(), Eval_Dift_VDF_const_Elem::init_ind_fluctu_term(), Eval_Dift_VDF_var_Elem::init_ind_fluctu_term(), and update_equivalent_distance().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Turbulence.h
src/VDF/Operateurs/Eval_Diff_Dift/Eval_Turbulence.cpp