TRUST: Champ_val_tot_sur_vol_base Class Reference
Champ_val_tot_sur_vol_base Class Reference
classe Champ_val_tot_sur_vol_base
Classe de base derivee de Champ_Uniforme_Morceaux qui represente les champs
dont on veut une evaluation exprimee par val_lue_loc/(Somme_vol_poro_loc)
val_lue_loc designe la valeur lue pour une localisation de l espace (sous zone ou domaine par defaut)
cas VDF : Somme_vol_poro_loc exprime la sommation de vol_element*poro_volumique
pour les elements contenus dans la localisation loc
cas VEF : Somme_vol_poro_loc exprime la sommation de vol_entrelaces*poro_surface
pour les faces contenues dans la localisation loc
Somme_vol_poro_loc est evalue par la methode eval_contrib_loc() des classes derivees
La syntaxe utilisateur a respecter est la suivante :
Valeur_totale_sur_volume nom_domaine nb_comp { defaut val_lue_dom ...zonei val_lue_szi ... }
nom_domaine : nom du domaine de calcul
nb_comp : nombre de composantes du champ
val_lue_dom : valeur lue pour le domaine par defaut
val_lue_szi : valeur lue pour la sous zone zonei
#include <Champ_val_tot_sur_vol_base.h>
Public Member Functions
Champ_val_tot_sur_vol_base ()
~Champ_val_tot_sur_vol_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void evaluer (const Zone_dis_base &zdis, const Zone_Cl_dis_base &zcldis)
virtual DoubleVect & eval_contrib_loc (const Zone_dis_base &zdis, const Zone_Cl_dis_base &zcldis, DoubleVect &vol)=0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_val_tot_sur_vol_base & self_cast (Objet_U &)
static const
Champ_val_tot_sur_vol_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime les valeurs du champs sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les valeurs du champ uniforme par morceaux
a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de
composantes du champ (nb_comp) la valeur par defaut
du champ ainsi que les valeurs sur les sous zones.
Format:
Champ_Uniforme_Morceaux nom_domaine nb_comp
{ Defaut val_def sous_zone_1 val_1 ... sous_zone_i val_i }.
Detailed Description
classe Champ_val_tot_sur_vol_base
Classe de base derivee de Champ_Uniforme_Morceaux qui represente les champs
dont on veut une evaluation exprimee par val_lue_loc/(Somme_vol_poro_loc)
val_lue_loc designe la valeur lue pour une localisation de l espace (sous zone ou domaine par defaut)
cas VDF : Somme_vol_poro_loc exprime la sommation de vol_element*poro_volumique
pour les elements contenus dans la localisation loc
cas VEF : Somme_vol_poro_loc exprime la sommation de vol_entrelaces*poro_surface
pour les faces contenues dans la localisation loc
Somme_vol_poro_loc est evalue par la methode eval_contrib_loc() des classes derivees
La syntaxe utilisateur a respecter est la suivante :
Valeur_totale_sur_volume nom_domaine nb_comp { defaut val_lue_dom ...zonei val_lue_szi ... }
nom_domaine : nom du domaine de calcul
nb_comp : nombre de composantes du champ
val_lue_dom : valeur lue pour le domaine par defaut
val_lue_szi : valeur lue pour la sous zone zonei
Definition at line 54 of file Champ_val_tot_sur_vol_base.h.
Constructor & Destructor Documentation
Champ_val_tot_sur_vol_base::Champ_val_tot_sur_vol_base ()
Definition at line 29 of file Champ_val_tot_sur_vol_base.cpp.
Champ_val_tot_sur_vol_base::~Champ_val_tot_sur_vol_base ()
Definition at line 29 of file Champ_val_tot_sur_vol_base.cpp.
Member Function Documentation
virtual int Champ_val_tot_sur_vol_base::duplique () const [pure virtual]
Reimplemented from Champ_Uniforme_Morceaux.
Implemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
virtual DoubleVect& Champ_val_tot_sur_vol_base::eval_contrib_loc (const Zone_dis_base & zdis, const Zone_Cl_dis_base & zcldis, DoubleVect & vol) [pure virtual]
Implemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Referenced by evaluer().
void Champ_val_tot_sur_vol_base::evaluer (const Zone_dis_base & zdis, const Zone_Cl_dis_base & zcldis)
Definition at line 52 of file Champ_val_tot_sur_vol_base.cpp.
References DoubleVect::echange_espace_virtuel(), eval_contrib_loc(), Champ_Uniforme_Morceaux::les_sous_zones, LIST_CURSEUR, Field_base::nb_compo_, Zone_dis_base::nb_elem(), Sous_Zone::nb_elem_tot(), REF, sz, Champ_Don_base::valeurs(), and Champ_Don_base::valeurs_.
Referenced by Terme_Puissance_Thermique::initialiser_champ_puissance().
{
  const int nb_elem = zdis.nb_elem();
  DoubleVect vol_glob_pond;
  vol_glob_pond = eval_contrib_loc(zdis,zcldis,vol_glob_pond);
  for(int elem=0; elem<nb_elem; elem++)
    for (int k=0; k<nb_compo_; k++)
      valeurs_(elem,k) /= vol_glob_pond(0);
  int cpt=1;
  LIST_CURSEUR(REF(Sous_Zone)) curseur1 = les_sous_zones;
  while(curseur1)
    {
      const Sous_Zone& sz = curseur1.valeur().valeur();
      int size_sz = sz.nb_elem_tot();
      int el;
      for (int elem=0; elem<size_sz; elem++)
        {
          el = sz(elem);
          for (int k=0; k<nb_compo_; k++)
            {
              valeurs_(el,k) *= vol_glob_pond(0);
              valeurs_(el,k) /= vol_glob_pond(cpt);
            }
        }
      cpt++;
      ++curseur1;
    }
  valeurs().echange_espace_virtuel();
}
const Type_info * Champ_val_tot_sur_vol_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 29 of file Champ_val_tot_sur_vol_base.cpp.
const Type_info * Champ_val_tot_sur_vol_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 29 of file Champ_val_tot_sur_vol_base.cpp.
Sortie & Champ_val_tot_sur_vol_base::printOn (Sortie & os) const [protected, virtual]
Imprime les valeurs du champs sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 32 of file Champ_val_tot_sur_vol_base.cpp.
{
  return Champ_Uniforme_Morceaux::printOn(os);
}
Entree & Champ_val_tot_sur_vol_base::readOn (Entree & is) [protected, virtual]
Lit les valeurs du champ uniforme par morceaux
a partir d'un flot d'entree.
On lit le nom du domaine (nom_domaine) le nombre de
composantes du champ (nb_comp) la valeur par defaut
du champ ainsi que les valeurs sur les sous zones.
Format:
Champ_Uniforme_Morceaux nom_domaine nb_comp
{ Defaut val_def sous_zone_1 val_1 ... sous_zone_i val_i }.
Returns:
Entree&
Signification: le champ d'entree modifie
Contraintes:
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 37 of file Champ_val_tot_sur_vol_base.cpp.
{
  Champ_Uniforme_Morceaux::readOn(is);
  return is;
}
const Champ_val_tot_sur_vol_base & Champ_val_tot_sur_vol_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 29 of file Champ_val_tot_sur_vol_base.cpp.
Champ_val_tot_sur_vol_base & Champ_val_tot_sur_vol_base::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 29 of file Champ_val_tot_sur_vol_base.cpp.
Member Data Documentation
const Type_info Champ_val_tot_sur_vol_base::info_obj [static]
Reimplemented from Champ_Uniforme_Morceaux.
Reimplemented in Champ_val_tot_sur_vol_VDF, and Champ_val_tot_sur_vol_VEF.
Definition at line 57 of file Champ_val_tot_sur_vol_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_val_tot_sur_vol_base.h
src/Kernel/Champs/Champ_val_tot_sur_vol_base.cpp