TRUST: Deriv_Precond_base Class Reference
Deriv_Precond_base Class Reference
class Precond
Un Precond represente n'importe qu'elle classe
derivee de la classe Precond_base
#include <Precond.h>
Public Member Functions
~Deriv_Precond_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Precond_base ()
Deriv_Precond_base (const Deriv_Precond_base &)
const Precond_base & valeur () const
Precond_base & valeur ()
const Precond_base * operator-> () const
Precond_base * operator-> ()
const Deriv_Precond_base & operator= (const Precond_base &)
const Deriv_Precond_base & operator= (const Deriv_Precond_base &)
operator const Precond_base & () const
operator Precond_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Precond_base & self_cast (Objet_U &)
static const Deriv_Precond_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Precond_base * pointeur_
Detailed Description
class Precond
Un Precond represente n'importe qu'elle classe
derivee de la classe Precond_base
Definition at line 38 of file Precond.h.
Constructor & Destructor Documentation
Deriv_Precond_base::~Deriv_Precond_base ()
Definition at line 25 of file Precond.cpp.
Deriv_Precond_base::Deriv_Precond_base ()
Definition at line 25 of file Precond.cpp.
Deriv_Precond_base::Deriv_Precond_base (const Deriv_Precond_base & t)
Definition at line 25 of file Precond.cpp.
Member Function Documentation
Objet_U * Deriv_Precond_base::cree_instance () [static]
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
int Deriv_Precond_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
const Type_info * Deriv_Precond_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
const Type_info & Deriv_Precond_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Precond.cpp.
const Type_info * Deriv_Precond_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
Deriv_Precond_base::operator const Precond_base & () const
Definition at line 25 of file Precond.cpp.
Deriv_Precond_base::operator Precond_base & ()
Definition at line 25 of file Precond.cpp.
const Precond_base * Deriv_Precond_base::operator-> () const [inline]
Definition at line 38 of file Precond.h.
: public DERIV(Precond_base)
Precond_base * Deriv_Precond_base::operator-> () [inline]
Definition at line 38 of file Precond.h.
: public DERIV(Precond_base)
const Deriv_Precond_base & Deriv_Precond_base::operator= (const Deriv_Precond_base & t)
Definition at line 25 of file Precond.cpp.
const Deriv_Precond_base & Deriv_Precond_base::operator= (const Precond_base & t)
Definition at line 25 of file Precond.cpp.
Sortie & Deriv_Precond_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
Entree & Deriv_Precond_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
const Deriv_Precond_base & Deriv_Precond_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
Deriv_Precond_base & Deriv_Precond_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
void Deriv_Precond_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Precond.cpp.
unsigned Deriv_Precond_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Precond.
Definition at line 25 of file Precond.cpp.
const Precond_base & Deriv_Precond_base::valeur () const [inline]
Definition at line 38 of file Precond.h.
Referenced by Precond::preconditionner(), prepare_precond(), Solv_Gen::reinit(), Solv_GCP::reinit(), Solv_GCP::resoudre_(), Solv_Gen::solve(), and Precond::supporte_matrice_morse_sym().
: public DERIV(Precond_base)
Precond_base & Deriv_Precond_base::valeur () [inline]
Definition at line 38 of file Precond.h.
: public DERIV(Precond_base)
Member Data Documentation
const Type_info Deriv_Precond_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Precond.
Definition at line 38 of file Precond.h.
Precond_base* Deriv_Precond_base::pointeur_ [private]
Definition at line 38 of file Precond.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Precond.h
src/Kernel/Math/SolvSys/Precond.cpp