TRUST: Source_WC_Chaleur_VDF Class Reference
Source_WC_Chaleur_VDF Class Reference
class Source_WC_Chaleur_VDF
Cette classe represente un terme source supplementaire
a prendre en compte dans les equations de la chaleur
dans le cas ou le fluide est weakly compressible et pour
une discretisation VDF
#include <Source_WC_Chaleur_VDF.h>
Public Member Functions
Source_WC_Chaleur_VDF ()
~Source_WC_Chaleur_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_WC_Chaleur_VDF & self_cast (Objet_U &)
static const
Source_WC_Chaleur_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &zone, const Zone_Cl_dis &zcl)
void compute_interpolate_gradP (DoubleTab &gradP, const DoubleTab &Ptot) const
Private Member Functions
void face_to_elem (const Zone_VF &zone, const DoubleTab &UgradP, DoubleTab &UgradP_elem) const
void compute_interpolate_gradP_old (DoubleTab &gradP, const DoubleTab &Ptot) const
Detailed Description
class Source_WC_Chaleur_VDF
Cette classe represente un terme source supplementaire
a prendre en compte dans les equations de la chaleur
dans le cas ou le fluide est weakly compressible et pour
une discretisation VDF
Definition at line 45 of file Source_WC_Chaleur_VDF.h.
Constructor & Destructor Documentation
Source_WC_Chaleur_VDF::Source_WC_Chaleur_VDF ()
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
Source_WC_Chaleur_VDF::~Source_WC_Chaleur_VDF ()
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
Member Function Documentation
void Source_WC_Chaleur_VDF::associer_zones (const Zone_dis & zone, const Zone_Cl_dis & zcl) [protected, virtual]
Implements Source_Chaleur_Fluide_Dilatable_base.
Definition at line 40 of file Source_WC_Chaleur_VDF.cpp.
References Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl(), Source_Chaleur_Fluide_Dilatable_base::porosites, and Source_Chaleur_Fluide_Dilatable_base::volumes.
{
  associer_volume_porosite_impl(zone,volumes,porosites);
}
void Source_WC_Chaleur_VDF::compute_interpolate_gradP (DoubleTab & gradP, const DoubleTab & Ptot) const [protected, virtual]
< initialise avec grad(P) car face
< compute grad(P_tot)
< field on faces
Implements Source_WC_Chaleur.
Definition at line 45 of file Source_WC_Chaleur_VDF.cpp.
References Operateur_Grad::calculer(), Source_WC_Chaleur::correct_grad_boundary(), DoubleTab::dimension_tot(), face_to_elem(), Navier_Stokes_std::grad_P(), MorEqn::mon_equation, Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), Objet_U::que_suis_je(), ref_cast, Ref_Equation_base::valeur(), Champ_Inc::valeurs(), and Navier_Stokes_std::vitesse().
{
  /*
   * NOTA BENE :
   * On a discretisé P_EOS avec une directive = temperature qui donne en VDF :
   * Ptot => aux elems
   * la_vitesse => faces car vdf
   * grad_Ptot => faces car vdf
   *
   * Donc u*grad(P_tot) => faces
   * L'equation est une equation de scalaire => aux elems car vdf
   * On a d P_tot / d t = del P / del t + u.grad(P_tot)
   *
   * del P / del t => aux elem
   * u.grad(P_tot) !!! faut l'interpoler aux elems
   */
  const Navier_Stokes_WC& eqHyd = ref_cast(Navier_Stokes_WC,mon_equation->probleme().equation(0));
  const DoubleTab& la_vitesse = eqHyd.vitesse().valeurs();
  DoubleTab grad_Ptot(eqHyd.grad_P().valeurs()); //!< initialise avec grad(P) car face
  const Convection_Diffusion_Chaleur_WC& eq_chal = ref_cast(Convection_Diffusion_Chaleur_WC,mon_equation.valeur());
  const Operateur_Grad& Op_Grad = eq_chal.operateur_gradient_WC();
  Op_Grad.calculer(Ptot,grad_Ptot); //!< compute grad(P_tot)
  const Zone_dis_base& zone_dis = mon_equation->inconnue().zone_dis_base();
  const Zone_VF& zone = ref_cast(Zone_VF, zone_dis);
  assert (zone_dis.que_suis_je() == "Zone_VDF");
// grad should be zero at boundary
  correct_grad_boundary(zone,grad_Ptot);
// We compute u*grad(P_tot) on each face
  DoubleTab UgradP(grad_Ptot); //!< field on faces
  const int n = la_vitesse.dimension_tot(0);
  assert ( n == zone.nb_faces_tot() && la_vitesse.line_size() == 1);
  assert ( Ptot.dimension_tot(0) == zone.nb_elem_tot() );
  for (int i=0 ; i <n ; i++) UgradP(i,0) = la_vitesse(i,0) * grad_Ptot(i,0);
  face_to_elem(zone,UgradP,UgradP_elem);
}
void Source_WC_Chaleur_VDF::compute_interpolate_gradP_old (DoubleTab & gradP, const DoubleTab & Ptot) const [private]
< initialise avec grad(P) car face
< recuperer op grad de NS
< compute grad(P_tot)
< field on faces
Definition at line 101 of file Source_WC_Chaleur_VDF.cpp.
References Solveur_Masse::appliquer(), Operateur_Grad::calculer(), DoubleTab::dimension(), face_to_elem(), Cond_lim::frontiere_dis(), Navier_Stokes_std::grad_P(), Navier_Stokes_std::inconnue(), Zone_Cl_dis::les_conditions_limites(), MorEqn::mon_equation, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Navier_Stokes_std::operateur_gradient(), Objet_U::que_suis_je(), ref_cast, Equation_base::solv_masse(), sub_type, Deriv_Cond_lim_base::valeur(), Champ_Inc::valeurs(), Navier_Stokes_std::vitesse(), Equation_base::zone_Cl_dis(), and Champ_Inc::zone_dis_base().
{
// compute the grad
  const Navier_Stokes_WC& eqHyd = ref_cast(Navier_Stokes_WC,mon_equation->probleme().equation(0));
  const DoubleTab& la_vitesse = eqHyd.vitesse().valeurs();
  DoubleTab grad_Ptot(eqHyd.grad_P().valeurs()); //!< initialise avec grad(P) car face
  const Operateur_Grad& gradient = eqHyd.operateur_gradient(); //!< recuperer op grad de NS
  gradient.calculer(Ptot,grad_Ptot); //!< compute grad(P_tot)
// XXX : very important : sinon we have values * V !
  const Solveur_Masse& solv_mass = eqHyd.solv_masse();
  solv_mass.appliquer(grad_Ptot);
  /*
   * XXX XXX XXX
   * READ CAREFULLY : We use the grad operator from Navier_Stokes_std
   *    => created for the pressure normally
   * There is a special treatement for Neumann bc (Neumann_sortie_libre)
   * because we use explicitly the prescribed pressure.
   * So if we calculate the grad of Ptot or rho for example, we will use
   * P_ext defined in data file which is wrong !
   *
   * Now we do the following : we assume open bd as a wall => null gradient
   */
// We use that of NS because we test the CL too (attention mon_equation is Chaleur...)
  const Zone_dis_base& zone_dis = eqHyd.inconnue().zone_dis_base();
  const Zone_VF& zone = ref_cast(Zone_VF, zone_dis);
  const Zone_Cl_dis& zone_cl = eqHyd.zone_Cl_dis();
  assert (zone_dis.que_suis_je() == "Zone_VDF");
  for (int n_bord=0; n_bord<zone.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_cl.les_conditions_limites(n_bord);
// corrige si Neumann_sortie_libre
      if ( sub_type(Neumann_sortie_libre,la_cl.valeur()) )
        {
// recuperer face et remplace gradient par 0
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          const int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++) grad_Ptot(num_face,0) = 0.;
        }
    }
// We compute u*grad(P_tot) on each face
  DoubleTab UgradP(grad_Ptot); //!< field on faces
  const int n = la_vitesse.dimension(0);
  assert ( n == zone.nb_faces() );
  assert ( Ptot.dimension(0) == zone.nb_elem() );
  for (int i=0 ; i <n ; i++) UgradP(i,0) = la_vitesse(i,0) * grad_Ptot(i,0);
  face_to_elem(zone,UgradP,UgradP_elem);
}
Objet_U * Source_WC_Chaleur_VDF::cree_instance () [static]
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
int Source_WC_Chaleur_VDF::duplique () const [virtual]
Implements Source_WC_Chaleur.
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
void Source_WC_Chaleur_VDF::face_to_elem (const Zone_VF & zone, const DoubleTab & UgradP, DoubleTab & UgradP_elem) const [private]
Definition at line 87 of file Source_WC_Chaleur_VDF.cpp.
References DoubleTab::dimension_tot(), Zone_VF::elem_faces(), IntVect::line_size(), Zone_dis_base::nb_elem_tot(), and Zone_VF::nb_faces_tot().
Referenced by compute_interpolate_gradP(), and compute_interpolate_gradP_old().
{
  const IntTab& elem_faces = zone.elem_faces();
  const int nb_face_elem = elem_faces.line_size(), nb_elem_tot= zone.nb_elem_tot();
  assert (UgradP_elem.dimension_tot(0) == nb_elem_tot && UgradP.dimension_tot(0) == zone.nb_faces_tot());
  UgradP_elem = 0.;
  for (int ele=0; ele<nb_elem_tot; ele++)
    for (int s=0; s<nb_face_elem; s++) UgradP_elem(ele,0) += UgradP(elem_faces(ele,s),0);
  UgradP_elem *= 0.5;
}
const Type_info * Source_WC_Chaleur_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
const Type_info * Source_WC_Chaleur_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
Sortie & Source_WC_Chaleur_VDF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 32 of file Source_WC_Chaleur_VDF.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Source_WC_Chaleur_VDF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_WC_Chaleur.
Definition at line 38 of file Source_WC_Chaleur_VDF.cpp.
{ return is; }
Source_WC_Chaleur_VDF & Source_WC_Chaleur_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Source_WC_Chaleur.
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
const Source_WC_Chaleur_VDF & Source_WC_Chaleur_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_WC_Chaleur.
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
unsigned Source_WC_Chaleur_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Source_WC_Chaleur_VDF.cpp.
Member Data Documentation
const Type_info Source_WC_Chaleur_VDF::info_obj [static]
Reimplemented from Source_WC_Chaleur.
Definition at line 47 of file Source_WC_Chaleur_VDF.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Weakly_Compressible/VDF/Source_WC_Chaleur_VDF.h
src/ThHyd/Dilatable/Weakly_Compressible/VDF/Source_WC_Chaleur_VDF.cpp