TRUST: Frottement_interfacial_PolyMAC_P0 Class Reference
Frottement_interfacial_PolyMAC_P0 Class Reference
Classe Frottement_interfacial_PolyMAC_P0
Cette classe implemente dans PolyMAC_P0 un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
le calcul de C_{kl} est realise par la hierarchie Coefficient_Frottement_interfacial_base.
#include <Frottement_interfacial_PolyMAC_P0.h>
Public Member Functions
Frottement_interfacial_PolyMAC_P0 ()
~Frottement_interfacial_PolyMAC_P0 ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Frottement_interfacial_PolyMAC_P0 & self_cast (Objet_U &)
static const Frottement_interfacial_PolyMAC_P0 & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Correlation correlation_
Additional Inherited Members
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Classe Frottement_interfacial_PolyMAC_P0
Cette classe implemente dans PolyMAC_P0 un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
le calcul de C_{kl} est realise par la hierarchie Coefficient_Frottement_interfacial_base.
Definition at line 32 of file Frottement_interfacial_PolyMAC_P0.h.
Constructor & Destructor Documentation
Frottement_interfacial_PolyMAC_P0()
Frottement_interfacial_PolyMAC_P0::Frottement_interfacial_PolyMAC_P0 ()
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
~Frottement_interfacial_PolyMAC_P0()
Frottement_interfacial_PolyMAC_P0::~Frottement_interfacial_PolyMAC_P0 ()
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
Member Function Documentation
ajouter_blocs()
void Frottement_interfacial_PolyMAC_P0::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Definition at line 79 of file Frottement_interfacial_PolyMAC_P0.cpp.
{
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  Matrice_Morse *mat = matrices.count(ch.le_nom().getString()) ? matrices.at(ch.le_nom().getString()) : NULL;
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, equation().zone_dis().valeur());
  const IntTab& f_e = zone.face_voisins(), &fcl = ch.fcl();
  const DoubleVect& pe = zone.porosite_elem(), &pf = zone.porosite_face(), &ve = zone.volumes(), &vf = zone.volumes_entrelaces(), &dh_e = zone.diametre_hydraulique_elem();
  const DoubleTab& inco = ch.valeurs(), &pvit = ch.passe(), &vfd = zone.volumes_entrelaces_dir(),
                   &alpha = ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe(),
                    &press = ref_cast(QDM_Multiphase, equation()).pression().passe(),
                     &temp  = ref_cast(Pb_Multiphase, equation().probleme()).eq_energie.inconnue().passe(),
                      &rho   = equation().milieu().masse_volumique().passe(),
                       &mu    = ref_cast(Fluide_base, equation().milieu()).viscosite_dynamique().passe();
  const Milieu_composite& milc = ref_cast(Milieu_composite, equation().milieu());
  DoubleTab const * d_bulles = (equation().probleme().has_champ("diametre_bulles")) ? &equation().probleme().get_champ("diametre_bulles").valeurs() : NULL ;
  int e, f, c, i, j, k, l, n, N = inco.line_size(), Np = press.line_size(), d, D = dimension, nf_tot = zone.nb_faces_tot(),
                              cR = (rho.dimension_tot(0) == 1), cM = (mu.dimension_tot(0) == 1), exp_res = 2;
  DoubleTrav a_l(N), p_l(N), T_l(N), rho_l(N), mu_l(N), sigma_l(N,N), dv(N, N), ddv(N, N, 4), ddv_c(4), d_bulles_l(N), coeff(N, N, 2); //arguments pour coeff
  double dv_min = 0.1, dh, a_res = 1e-2;
  const Frottement_interfacial_base& correlation_fi = ref_cast(Frottement_interfacial_base, correlation_.valeur());
  /* faces */
  for (f = 0; f < zone.nb_faces(); f++)
    if (fcl(f, 0) < 2)
      {
        for (a_l = 0, p_l = 0, T_l = 0, rho_l = 0, mu_l = 0, dh = 0, sigma_l = 0, dv = dv_min, ddv = 0, d_bulles_l=0, c = 0; c < 2 && (e = f_e(f, c)) >= 0; c++)
          {
            for (n = 0; n < N; n++) a_l(n)   += vfd(f, c) / vf(f) * alpha(e, n);
            for (n = 0; n < N; n++) p_l(n)   += vfd(f, c) / vf(f) * press(e, n * (Np > 1));
            for (n = 0; n < N; n++) T_l(n)   += vfd(f, c) / vf(f) * temp(e, n);
            for (n = 0; n < N; n++) rho_l(n) += vfd(f, c) / vf(f) * rho(!cR * e, n);
            for (n = 0; n < N; n++) mu_l(n)  += vfd(f, c) / vf(f) * mu(!cM * e, n);
            for (n = 0; n < N; n++)
              for (k = 0; k < N; k++)
                if (milc.has_interface(n,k))
                  {
                    Interface_base& sat = milc.get_interface(n, k);
                    sigma_l(n,k) += vfd(f, c) / vf(f) * sat.sigma_(temp(e,n),press(e,n * (Np > 1)));
                  }
            for (n = 0; n < N; n++) dh += vfd(f, c) / vf(f) * alpha(e, n) * dh_e(e);
            for (k = 0; k < N; k++)
              for (l = 0; l < N; l++)
                {
                  double dv_c = ch.v_norm(pvit, pvit, e, f, k, l, NULL, &ddv_c(0));
                  if (dv_c > dv(k, l))
                    for (dv(k, l) = dv_c, i = 0; i < 4; i++) ddv(k, l, i) = ddv_c(i);
                }
            for (n=0; n<N; n++) d_bulles_l(n) += (d_bulles) ? vfd(f, c) / vf(f) * (*d_bulles)(e,n) : 0;
          }
        correlation_fi.coefficient(a_l, p_l, T_l, rho_l, mu_l, sigma_l, dh, dv, d_bulles_l, coeff);
        for (k = 0; k < N; k++)
          for (l = 0; l < N; l++)
            for (j = 0; j < 2; j++)
              coeff(k, l, j) *= 1 + (a_l(k) > 1e-8 ? std::pow(a_l(k) / a_res, -exp_res) : 0) + (a_l(l) > 1e-8 ? std::pow(a_l(l) / a_res, -exp_res) : 0);
        /* contributions : on prend le max entre les deux cotes */
        for (k = 0; k < N; k++)
          for (l = 0; l < N; l++)
            if (k != l)
              {
                double fac = pf(f) * vf(f);
                /* on essaie d'impliciter coeff sans ralentir la convergence en en faisant un developpement limite autour de pvit (dans la direction d'interet seulement) */
                secmem(f, k) -= fac * (coeff(k, l, 0) * (inco(f, k) - inco(f, l)) + coeff(k, l, 1) * ddv(k, l, 3) * (pvit(f, k) - pvit(f, l)) * ((inco(f, k) - inco(f, l)) - (pvit(f, k) - pvit(f, l))));
                if (mat)
                  for (j = 0; j < 2; j++) (*mat)(N * f + k, N * f + (j ? l : k)) += fac * (j ? -1 : 1) * (coeff(k, l, 0) + coeff(k, l, 1) * ddv(k, l, 3) * (pvit(f, k) - pvit(f, l)));
              }
      }
  /* elements */
  for (e = 0; e < zone.nb_elem_tot(); e++)
    {
      /* arguments de coeff */
      for (n = 0; n < N; n++) a_l(n)   = alpha(e, n);
      for (n = 0; n < N; n++) p_l(n)   = press(e, n * (Np > 1));
      for (n = 0; n < N; n++) T_l(n)   =  temp(e, n);
      for (n = 0; n < N; n++) rho_l(n) =   rho(!cR * e, n);
      for (n = 0; n < N; n++) mu_l(n)  =    mu(!cM * e, n);
      for (n = 0; n < N; n++)
        {
          for (k = 0; k < N; k++)
            if(milc.has_interface(n, k))
              {
                Interface_base& sat = milc.get_interface(n, k);
                sigma_l(n,k) = sat.sigma_(temp(e,n), press(e,n * (Np > 1)));
              }
        }
      for (n=0; n<N; n++) d_bulles_l(n) = (d_bulles) ? (*d_bulles)(e,n) : 0;
      for (k = 0; k < N; k++)
        for (l = 0; l < N; l++) dv(k, l) = std::max(ch.v_norm(pvit, pvit, e, -1, k, l, NULL, &ddv(k, l, 0)), dv_min);
      correlation_fi.coefficient(a_l, p_l, T_l, rho_l, mu_l, sigma_l, dh_e(e), dv, d_bulles_l, coeff);
      for (k = 0; k < N; k++)
        for (l = 0; l < N; l++) coeff(k, l, 1) *= (dv(k, l) > dv_min); //pas de derivee si dv < dv_min
      for (k = 0; k < N; k++)
        for (l = 0; l < N; l++)
          for (j = 0; j < 2; j++)
            coeff(k, l, j) *= 1 + (a_l(k) > 1e-8 ? std::pow(a_l(k) / a_res, -exp_res) : 0) + (a_l(l) > 1e-8 ? std::pow(a_l(l) / a_res, -exp_res) : 0);
      for (d = 0, i = nf_tot + D * e; d < D; d++, i++)
        for (k = 0; k < N; k++)
          for (l = 0; l < N; l++)
            if (k != l)
              {
                double fac = pe(e) * ve(e);
                /* on essaie d'impliciter coeff sans ralentir la convergence en en faisant un developpement limite autour de pvit (dans la direction d'interet seulement) */
                secmem(i, k) -= fac * (coeff(k, l, 0) * (inco(i, k) - inco(i, l)) + coeff(k, l, 1) * ddv(k, l, d) * (pvit(i, k) - pvit(i, l)) * ((inco(i, k) - inco(i, l)) - (pvit(i, k) - pvit(i, l))));
                if (mat)
                  for (j = 0; j < 2; j++) (*mat)(N * i + k, N * i + (j ? l : k)) += fac * (j ? -1 : 1) * (coeff(k, l, 0) + coeff(k, l, 1) * ddv(k, l, d) * (pvit(i, k) - pvit(i, l)));
              }
    }
}
References coeff, Frottement_interfacial_base::coefficient(), correlation_, Zone_VF::diametre_hydraulique_elem(), Objet_U::dimension, MorEqn::equation(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), Probleme_base::get_champ(), Milieu_composite::get_interface(), Nom::getString(), Probleme_base::has_champ(), Milieu_composite::has_interface(), Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Champ_Proto::passe(), Champ_Inc_base::passe(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Equation_base::probleme(), ref_cast, Interface_base::sigma_(), Champ_Face_PolyMAC_P0::v_norm(), Deriv_Correlation_base::valeur(), valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Zone_Poly_base::volumes_entrelaces_dir().
associer_pb()
void Frottement_interfacial_PolyMAC_P0::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
Definition at line 45 of file Frottement_interfacial_PolyMAC_P0.h.
{ };
associer_zones()
void Frottement_interfacial_PolyMAC_P0::associer_zones (const Zone_dis & , const Zone_Cl_dis &) inline override virtual
Implements Source_base.
Definition at line 44 of file Frottement_interfacial_PolyMAC_P0.h.
{ };
check_multiphase_compatibility()
void Frottement_interfacial_PolyMAC_P0::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 42 of file Frottement_interfacial_PolyMAC_P0.h.
{}; //of course
cree_instance()
Objet_U * Frottement_interfacial_PolyMAC_P0::cree_instance () static
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
dimensionner_blocs()
void Frottement_interfacial_PolyMAC_P0::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Definition at line 45 of file Frottement_interfacial_PolyMAC_P0.cpp.
{
  const Champ_Face_PolyMAC_P0& ch = ref_cast(Champ_Face_PolyMAC_P0, equation().inconnue().valeur());
  if (!matrices.count(ch.le_nom().getString())) return; //rien a faire
  Matrice_Morse& mat = *matrices.at(ch.le_nom().getString()), mat2;
  const Zone_PolyMAC_P0& zone = ref_cast(Zone_PolyMAC_P0, equation().zone_dis().valeur());
  const DoubleTab& inco = ch.valeurs();
  const IntTab& fcl = ch.fcl();
  /* stencil : diagonal par bloc pour les vitesses aux faces, puis chaque composante des vitesses aux elems */
  IntTrav stencil(0, 2);
  stencil.set_smart_resize(1);
  int i, j, e, f, k, l, N = inco.line_size(), d, db, D = dimension, nf_tot = zone.nb_faces_tot();
  /* faces */
  for (f = 0; f < zone.nb_faces(); f++)
    if (fcl(f, 0) < 2)
      {
        for (k = 0; k < N; k++)
          for (l = 0; l < N; l++) stencil.append_line(N * f + k, N * f + l);
// for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) for (d = 0, j = nf_tot + D * e; d < D; d++, j++)
// for (k = 0; k < N; k++) for (l = 0; l < N; l++) stencil.append_line(N * f + k, N * j + l);
      }
  /* elements */
  for (e = 0, i = nf_tot; e < zone.nb_elem_tot(); e++)
    for (d = 0; d < D; d++, i++)
      for (db = 0, j = nf_tot + D * e; db < D; db++, j++)
        for (k = 0; k < N; k++)
          for (l = 0; l < N; l++) stencil.append_line(N * i + k, N * j + l);
  tableau_trier_retirer_doublons(stencil);
  Matrix_tools::allocate_morse_matrix(inco.size_totale(), inco.size_totale(), stencil, mat2);
  mat.nb_colonnes() ? mat += mat2 : mat = mat2;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Champ_Face_PolyMAC::fcl(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), tableau_trier_retirer_doublons(), valeur(), and Champ_Inc_base::valeurs().
duplique()
int Frottement_interfacial_PolyMAC_P0::duplique () const override virtual
Implements Objet_U.
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
get_info()
const Type_info * Frottement_interfacial_PolyMAC_P0::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
has_interface_blocs()
int Frottement_interfacial_PolyMAC_P0::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 36 of file Frottement_interfacial_PolyMAC_P0.h.
  {
    return 1;
  };
info()
const Type_info * Frottement_interfacial_PolyMAC_P0::info () static
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
mettre_a_jour()
void Frottement_interfacial_PolyMAC_P0::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 46 of file Frottement_interfacial_PolyMAC_P0.h.
{ };
printOn()
Sortie & Frottement_interfacial_PolyMAC_P0::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Frottement_interfacial_PolyMAC_P0.cpp.
{
  return os;
}
readOn()
Entree & Frottement_interfacial_PolyMAC_P0::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 37 of file Frottement_interfacial_PolyMAC_P0.cpp.
{
  const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, equation().probleme());
  if (pbm.has_correlation("frottement_interfacial")) correlation_ = pbm.get_correlation("frottement_interfacial"); //correlation fournie par le bloc correlation
  else correlation_.typer_lire(pbm, "frottement_interfacial", is); //sinon -> on la lit
  return is;
}
References correlation_, MorEqn::equation(), Pb_Multiphase::get_correlation(), Pb_Multiphase::has_correlation(), ref_cast, and Correlation::typer_lire().
self_cast() [1/2]
const Frottement_interfacial_PolyMAC_P0 & Frottement_interfacial_PolyMAC_P0::self_cast (const Objet_U & r) static
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
self_cast() [2/2]
Frottement_interfacial_PolyMAC_P0 & Frottement_interfacial_PolyMAC_P0::self_cast (Objet_U & r) static
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
taille_memoire()
unsigned Frottement_interfacial_PolyMAC_P0::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 30 of file Frottement_interfacial_PolyMAC_P0.cpp.
Member Data Documentation
correlation_
Correlation Frottement_interfacial_PolyMAC_P0::correlation_ private
Definition at line 48 of file Frottement_interfacial_PolyMAC_P0.h.
Referenced by ajouter_blocs(), and readOn().
info_obj
const Type_info Frottement_interfacial_PolyMAC_P0::info_obj static
Definition at line 34 of file Frottement_interfacial_PolyMAC_P0.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/PolyMAC/Frottement_interfacial_PolyMAC_P0.h
src/ThHyd/Multiphase/PolyMAC/Frottement_interfacial_PolyMAC_P0.cpp