TRUST: Echange_couplage_thermique Class Reference
Echange_couplage_thermique Class Reference
: class Echange_couplage_thermique
<Description of class Echange_couplage_thermique>
#include <Echange_couplage_thermique.h>
Public Member Functions
Echange_couplage_thermique ()
~Echange_couplage_thermique ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_eqn (const Equation_base &) const override
int compatible_avec_discr (const Discretisation_base &discr) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
double champ_exterieur (int i, int j, const Champ_front &champ_ext) const override
double champ_exterieur (int i, const Champ_front &champ_ext) const override
double flux_exterieur_impose (int i) const override
double flux_exterieur_impose (int i, int j) const override
Champ_front & T_p ()
const Champ_front & T_p () const
bool reprise () const
Champ_front & a_p ()
const Champ_front & a_p () const
Champ_front & s_p ()
const Champ_front & s_p () const
Champ_front & h_eff ()
const Champ_front & h_eff () const
Champ_front & T_eff ()
const Champ_front & T_eff () const
Public Member Functions inherited from Echange_global_impose
Echange_global_impose ()
~Echange_global_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_discr (const Discretisation_base &discr) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Champ_front & derivee_phi_ext ()
const Champ_front & derivee_phi_ext () const
Champ_front & phi_ext ()
const Champ_front & phi_ext () const
virtual double champ_exterieur (int i, int j, const Champ_front &champ_ext) const
virtual double champ_exterieur (int i, const Champ_front &champ_ext) const
virtual double flux_exterieur_impose (int i) const
virtual double flux_exterieur_impose (int i, int j) const
virtual double derivee_flux_exterieur_imposee (int i) const
virtual double derivee_flux_exterieur_imposee (int i, int j) const
const bool & has_phi_ext () const
Public Member Functions inherited from Echange_impose_base
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_couplage_thermique & self_cast (Objet_U &)
static const Echange_couplage_thermique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_global_impose
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_global_impose & self_cast (Objet_U &)
static const Echange_global_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_impose_base
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Echange_global_impose
static const Type_info info_obj
Static Public Attributes inherited from Echange_impose_base
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void get_dRho_dCp (int i, double &dRho, double &dCp) const
Protected Member Functions inherited from Echange_global_impose
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Protected Member Functions inherited from Echange_impose_base
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double couplage_
Champ_front coeff_ap
Champ_front coeff_sp
Champ_front coeff_heff
Champ_front temperature_Teff
Lecture_Champ lec_champs
bool reprise_
Protected Attributes inherited from Echange_global_impose
bool phi_ext_lu_
Champ_front derivee_phi_ext_
Champ_front phi_ext_
Protected Attributes inherited from Echange_impose_base
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
: class Echange_couplage_thermique
<Description of class Echange_couplage_thermique>
Definition at line 30 of file Echange_couplage_thermique.h.
Constructor & Destructor Documentation
Echange_couplage_thermique()
Echange_couplage_thermique::Echange_couplage_thermique ()
Definition at line 33 of file Echange_couplage_thermique.cpp.
{
  couplage_=-1.;
  reprise_ = false;
  phi_ext_lu_ = true;
}
References couplage_, Echange_global_impose::phi_ext_lu_, and reprise_.
~Echange_couplage_thermique()
Echange_couplage_thermique::~Echange_couplage_thermique ()
Definition at line 24 of file Echange_couplage_thermique.cpp.
Member Function Documentation
a_p() [1/2]
Champ_front & Echange_couplage_thermique::a_p () inline
Definition at line 102 of file Echange_couplage_thermique.h.
{
  return coeff_ap;
}
References coeff_ap.
a_p() [2/2]
const Champ_front & Echange_couplage_thermique::a_p () const inline
Definition at line 97 of file Echange_couplage_thermique.h.
{
  return coeff_ap;
}
References coeff_ap.
avancer()
int Echange_couplage_thermique::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Definition at line 218 of file Echange_couplage_thermique.cpp.
{
  coeff_ap->avancer(temps);
  coeff_sp->avancer(temps);
  coeff_heff->avancer(temps);
  temperature_Teff->avancer(temps);
  return  Echange_global_impose::avancer(temps);
}
References Echange_global_impose::avancer(), coeff_ap, coeff_heff, coeff_sp, and temperature_Teff.
champ_exterieur() [1/2]
double Echange_couplage_thermique::champ_exterieur (int i, const Champ_front & champ_ext) const override virtual
Reimplemented from Echange_global_impose.
Definition at line 149 of file Echange_couplage_thermique.cpp.
{
  if (ma_zone_cl_dis->equation().que_suis_je()!="Convection_Diffusion_Concentration")
    {
      double d_rho, d_Cp;
      get_dRho_dCp(i, d_rho, d_Cp);
      if (champ_ext.valeurs().size()==1)
        return champ_ext(0,0)/(d_rho*d_Cp);
      else if (champ_ext.valeurs().dimension(1)==1)
        return champ_ext(i,0)/(d_rho*d_Cp);
      else
        Cerr << "Echange_couplage_thermique::flux_impose erreur" << finl;
      exit();
      return 0.;
    }
  else
    {
      if (champ_ext.valeurs().size()==1)
        return champ_ext(0,0);
      else if (champ_ext.valeurs().dimension(1)==1)
        return champ_ext(i,0);
      else
        Cerr << "Echange_couplage_thermique::flux_impose erreur" << finl;
      exit();
      return 0.;
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), Process::exit(), finl, get_dRho_dCp(), Cond_lim_base::ma_zone_cl_dis, Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::size(), and Champ_front::valeurs().
champ_exterieur() [2/2]
double Echange_couplage_thermique::champ_exterieur (int i, int j, const Champ_front & champ_ext) const override virtual
Reimplemented from Echange_global_impose.
Definition at line 179 of file Echange_couplage_thermique.cpp.
{
  if (ma_zone_cl_dis->equation().que_suis_je()!="Convection_Diffusion_Concentration")
    {
      double d_rho, d_Cp;
      get_dRho_dCp(i, d_rho, d_Cp);
      if (champ_ext.valeurs().dimension(0)==1)
        return champ_ext(0,j)/(d_rho*d_Cp);
      else
        return champ_ext(i,j)/(d_rho*d_Cp);
    }
  else
    {
      if (champ_ext.valeurs().dimension(0)==1)
        return champ_ext(0,j);
      else
        return champ_ext(i,j);
    }
}
References TRUSTTab< _TYPE_ >::dimension(), MorEqn::equation(), get_dRho_dCp(), Cond_lim_base::ma_zone_cl_dis, Objet_U::que_suis_je(), and Champ_front::valeurs().
Referenced by flux_exterieur_impose().
changer_temps_futur()
void Echange_couplage_thermique::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Cond_lim_base.
Definition at line 209 of file Echange_couplage_thermique.cpp.
{
  Echange_global_impose::changer_temps_futur(temps,i);
  coeff_ap->changer_temps_futur(temps,i);
  coeff_sp->changer_temps_futur(temps,i);
  coeff_heff->changer_temps_futur(temps,i);
  temperature_Teff->changer_temps_futur(temps,i);
}
References Echange_global_impose::changer_temps_futur(), coeff_ap, coeff_heff, coeff_sp, and temperature_Teff.
compatible_avec_discr()
int Echange_couplage_thermique::compatible_avec_discr (const Discretisation_base &) const override virtual
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 78 of file Echange_couplage_thermique.cpp.
{
  if (discr.que_suis_je() == "EF" || discr.que_suis_je() == "EF_axi" || discr.que_suis_je() == "VDF" || discr.que_suis_je() == "VEFPreP1B")
    return 1;
  else
    {
      err_pas_compatible(discr);
      return 0;
    }
}
References Cond_lim_base::err_pas_compatible(), and Objet_U::que_suis_je().
compatible_avec_eqn()
int Echange_couplage_thermique::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Implements Cond_lim_base.
Definition at line 65 of file Echange_couplage_thermique.cpp.
{
  Motcle dom_app = eqn.domaine_application();
  if ( (dom_app=="Thermique"))
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
completer()
void Echange_couplage_thermique::completer (void) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
Definition at line 89 of file Echange_couplage_thermique.cpp.
{
  Echange_global_impose::completer();
  coeff_ap.typer("Ch_front_var_instationnaire_dep");
  coeff_ap->fixer_nb_comp(1);
  coeff_ap->associer_fr_dis_base(frontiere_dis());
  coeff_ap->fixer_nb_valeurs_temporelles(3);
  coeff_sp.typer("Ch_front_var_instationnaire_dep");
  coeff_sp->fixer_nb_comp(1);
  coeff_sp->associer_fr_dis_base(frontiere_dis());
  coeff_sp->fixer_nb_valeurs_temporelles(3);
  coeff_heff.typer("Ch_front_var_instationnaire_dep");
  coeff_heff->fixer_nb_comp(1);
  coeff_heff->associer_fr_dis_base(frontiere_dis());
  coeff_heff->fixer_nb_valeurs_temporelles(3);
  temperature_Teff.typer("Ch_front_var_instationnaire_dep");
  temperature_Teff->fixer_nb_comp(1);
  temperature_Teff->associer_fr_dis_base(frontiere_dis());
  temperature_Teff->fixer_nb_valeurs_temporelles(3);
}
References Champ_front::associer_fr_dis_base(), coeff_ap, coeff_heff, coeff_sp, Echange_global_impose::completer(), Cond_lim_base::frontiere_dis(), temperature_Teff, and Deriv_::typer().
cree_instance()
Objet_U * Echange_couplage_thermique::cree_instance () static
Definition at line 24 of file Echange_couplage_thermique.cpp.
duplique()
int Echange_couplage_thermique::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Echange_couplage_thermique.cpp.
flux_exterieur_impose() [1/2]
double Echange_couplage_thermique::flux_exterieur_impose (int i) const override virtual
Reimplemented from Echange_global_impose.
Definition at line 204 of file Echange_couplage_thermique.cpp.
{
  return couplage_*champ_exterieur(i,phi_ext());
}
References champ_exterieur(), couplage_, and Echange_global_impose::phi_ext().
Referenced by Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), and Op_Diff_VEF_Face::ajouter_cas_scalaire().
flux_exterieur_impose() [2/2]
double Echange_couplage_thermique::flux_exterieur_impose (int i, int j) const override virtual
Reimplemented from Echange_global_impose.
Definition at line 199 of file Echange_couplage_thermique.cpp.
{
  return couplage_*champ_exterieur(i,j,phi_ext());
}
References champ_exterieur(), couplage_, and Echange_global_impose::phi_ext().
get_dRho_dCp()
void Echange_couplage_thermique::get_dRho_dCp (int i, double & dRho, double & dCp) const protected
Definition at line 114 of file Echange_couplage_thermique.cpp.
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  Nom nom_pb=ma_zone_cl_dis->equation().probleme().que_suis_je();
  const Champ_base& rho=mil.masse_volumique().valeur();
  if ((nom_pb.debute_par("Probleme_Interface")|| nom_pb==Nom("Probleme_Thermo_Front_Tracking"))||!sub_type(Champ_Uniforme,rho)
      ||nom_pb==Nom("Pb_Conduction") || nom_pb.debute_par("Pb_Conduction_Combustible"))
    {
// Pour le front tracking, QC, et conduc_variable, on ne divise pas par Rho*Cp:
      d_rho=1.;
      d_Cp=1.;
    }
  else
    {
      const Champ_Don& Cp =mil.capacite_calorifique();
      if (sub_type(Champ_Uniforme,rho))
        {
          d_rho= rho(0,0);
        }
      else
        {
          d_rho= rho(i);
        }
      if (sub_type(Champ_Uniforme,Cp.valeur()))
        {
          d_Cp= Cp(0,0);
        }
      else
        {
          d_Cp= Cp.valeur()(i);
        }
    }
}
References Milieu_base::capacite_calorifique(), Nom::debute_par(), MorEqn::equation(), Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Equation_base::milieu(), Equation_base::probleme(), Objet_U::que_suis_je(), sub_type, Deriv_Champ_base::valeur(), and Deriv_Champ_Don_base::valeur().
Referenced by champ_exterieur().
get_info()
const Type_info * Echange_couplage_thermique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 24 of file Echange_couplage_thermique.cpp.
h_eff() [1/2]
Champ_front & Echange_couplage_thermique::h_eff () inline
Definition at line 122 of file Echange_couplage_thermique.h.
{
  return coeff_heff;
}
References coeff_heff.
h_eff() [2/2]
const Champ_front & Echange_couplage_thermique::h_eff () const inline
Definition at line 117 of file Echange_couplage_thermique.h.
{
  return coeff_heff;
}
References coeff_heff.
info()
const Type_info * Echange_couplage_thermique::info () static
Definition at line 24 of file Echange_couplage_thermique.cpp.
initialiser()
int Echange_couplage_thermique::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 254 of file Echange_couplage_thermique.cpp.
{
  Echange_global_impose::initialiser(temps);
  if (reprise_)
    {
      Champ_Inc ch = zone_Cl_dis().equation().inconnue();
      ch->affecter(lec_champs.champ_lu("temperature_paroi"));
      DoubleTab& vals1 =le_champ_front->valeurs();
      ch->trace(frontiere_dis(),vals1,temps,0);
      ch->affecter(lec_champs.champ_lu("flux_paroi"));
      DoubleTab& vals = phi_ext_->valeurs();
      ch->trace(frontiere_dis(),vals,temps,0);
    }
  coeff_ap->initialiser(temps,zone_Cl_dis().inconnue());
  coeff_sp->initialiser(temps,zone_Cl_dis().inconnue());
  coeff_heff->initialiser(temps,zone_Cl_dis().inconnue());
  temperature_Teff->initialiser(temps,zone_Cl_dis().inconnue());
  return 1;
}
References Lecture_Champ::champ_lu(), coeff_ap, coeff_heff, coeff_sp, MorEqn::equation(), Cond_lim_base::frontiere_dis(), Equation_base::inconnue(), Echange_global_impose::initialiser(), Cond_lim_base::le_champ_front, lec_champs, Echange_global_impose::phi_ext_, reprise_, temperature_Teff, Champ_Inc::trace(), Champ_front::valeurs(), and Cond_lim_base::zone_Cl_dis().
mettre_a_jour()
void Echange_couplage_thermique::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Cond_lim_base.
Definition at line 245 of file Echange_couplage_thermique.cpp.
{
  Echange_global_impose::mettre_a_jour(temps);
  coeff_ap->mettre_a_jour(temps);
  coeff_sp->mettre_a_jour(temps);
  coeff_heff->mettre_a_jour(temps);
  temperature_Teff->mettre_a_jour(temps);
}
References coeff_ap, coeff_heff, coeff_sp, Champ_front::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), and temperature_Teff.
printOn()
Sortie & Echange_couplage_thermique::printOn (Sortie & s) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 40 of file Echange_couplage_thermique.cpp.
{
  Echange_global_impose::printOn( os );
  return os;
}
References Echange_global_impose::printOn().
readOn()
Entree & Echange_couplage_thermique::readOn (Entree & s) override protected virtual
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 46 of file Echange_couplage_thermique.cpp.
{
  Cerr << "Reading of coupled boundary\n";
  EChaine ech1("Ch_front_var_instationnaire_dep 1");
  EChaine ech2("Ch_front_var_instationnaire_dep 1");
  ech1 >>  h_imp_;
  ech2 >>  T_ext();
  List_Nom noms;
  noms.add("temperature_paroi");
  noms.add("flux_paroi");
  lec_champs.lire_champs(is,noms);
  reprise_ = lec_champs.champs_lus();
  return is;
}
References List_Nom::add(), Cerr, Lecture_Champ::champs_lus(), Echange_impose_base::h_imp_, lec_champs, Lecture_Champ::lire_champs(), reprise_, and Echange_impose_base::T_ext().
reculer()
int Echange_couplage_thermique::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Definition at line 227 of file Echange_couplage_thermique.cpp.
{
  coeff_ap->reculer(temps);
  coeff_sp->reculer(temps);
  coeff_heff->reculer(temps);
  temperature_Teff->reculer(temps);
  return  Echange_global_impose::reculer(temps);
}
References coeff_ap, coeff_heff, coeff_sp, Echange_global_impose::reculer(), and temperature_Teff.
reprise()
bool Echange_couplage_thermique::reprise () const inline
Definition at line 57 of file Echange_couplage_thermique.h.
  {
    return reprise_;
  }
References reprise_.
s_p() [1/2]
Champ_front & Echange_couplage_thermique::s_p () inline
Definition at line 112 of file Echange_couplage_thermique.h.
{
  return coeff_sp;
}
References coeff_sp.
s_p() [2/2]
const Champ_front & Echange_couplage_thermique::s_p () const inline
Definition at line 107 of file Echange_couplage_thermique.h.
{
  return coeff_sp;
}
References coeff_sp.
self_cast() [1/2]
const Echange_couplage_thermique & Echange_couplage_thermique::self_cast (const Objet_U & r) static
Definition at line 24 of file Echange_couplage_thermique.cpp.
self_cast() [2/2]
Echange_couplage_thermique & Echange_couplage_thermique::self_cast (Objet_U & r) static
Definition at line 24 of file Echange_couplage_thermique.cpp.
set_temps_defaut()
void Echange_couplage_thermique::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Cond_lim_base.
Definition at line 236 of file Echange_couplage_thermique.cpp.
{
  Echange_global_impose::set_temps_defaut(temps);
  coeff_ap->set_temps_defaut(temps);
  coeff_sp->set_temps_defaut(temps);
  coeff_heff->set_temps_defaut(temps);
  temperature_Teff->set_temps_defaut(temps);
}
References coeff_ap, coeff_heff, coeff_sp, Echange_global_impose::set_temps_defaut(), and temperature_Teff.
T_eff() [1/2]
Champ_front & Echange_couplage_thermique::T_eff () inline
Definition at line 132 of file Echange_couplage_thermique.h.
{
  return temperature_Teff;
}
References temperature_Teff.
T_eff() [2/2]
const Champ_front & Echange_couplage_thermique::T_eff () const inline
Definition at line 127 of file Echange_couplage_thermique.h.
{
  return temperature_Teff;
}
References temperature_Teff.
T_p() [1/2]
Champ_front & Echange_couplage_thermique::T_p () inline
Definition at line 92 of file Echange_couplage_thermique.h.
{
  return T_ext();
}
References Echange_impose_base::T_ext().
T_p() [2/2]
const Champ_front & Echange_couplage_thermique::T_p () const inline
Definition at line 87 of file Echange_couplage_thermique.h.
{
  return T_ext();
}
References Echange_impose_base::T_ext().
taille_memoire()
unsigned Echange_couplage_thermique::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Echange_couplage_thermique.cpp.
Member Data Documentation
coeff_ap
Champ_front Echange_couplage_thermique::coeff_ap protected
Definition at line 79 of file Echange_couplage_thermique.h.
Referenced by a_p(), avancer(), changer_temps_futur(), completer(), initialiser(), mettre_a_jour(), reculer(), and set_temps_defaut().
coeff_heff
Champ_front Echange_couplage_thermique::coeff_heff protected
Definition at line 81 of file Echange_couplage_thermique.h.
Referenced by avancer(), changer_temps_futur(), completer(), h_eff(), initialiser(), mettre_a_jour(), reculer(), and set_temps_defaut().
coeff_sp
Champ_front Echange_couplage_thermique::coeff_sp protected
Definition at line 80 of file Echange_couplage_thermique.h.
Referenced by avancer(), changer_temps_futur(), completer(), initialiser(), mettre_a_jour(), reculer(), s_p(), and set_temps_defaut().
couplage_
double Echange_couplage_thermique::couplage_ protected
Definition at line 78 of file Echange_couplage_thermique.h.
Referenced by Echange_couplage_thermique(), and flux_exterieur_impose().
info_obj
const Type_info Echange_couplage_thermique::info_obj static
Definition at line 33 of file Echange_couplage_thermique.h.
lec_champs
Lecture_Champ Echange_couplage_thermique::lec_champs protected
Definition at line 83 of file Echange_couplage_thermique.h.
Referenced by initialiser(), and readOn().
reprise_
bool Echange_couplage_thermique::reprise_ protected
Definition at line 84 of file Echange_couplage_thermique.h.
Referenced by Echange_couplage_thermique(), initialiser(), readOn(), and reprise().
temperature_Teff
Champ_front Echange_couplage_thermique::temperature_Teff protected
Definition at line 82 of file Echange_couplage_thermique.h.
Referenced by avancer(), changer_temps_futur(), completer(), initialiser(), mettre_a_jour(), reculer(), set_temps_defaut(), and T_eff().
The documentation for this class was generated from the following files:
src/ThSol/Echange_couplage_thermique.h
src/ThSol/Echange_couplage_thermique.cpp