TRUST: Calculer_Moments Class Reference
Calculer_Moments Class Reference
#include <Calculer_Moments.h>
Public Member Functions
Calculer_Moments ()
~Calculer_Moments ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const ArrOfDouble & centre_de_gravite () const
Entree & interpreter_ (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Calculer_Moments & self_cast (Objet_U &)
static const Calculer_Moments & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Private Attributes
ArrOfDouble c
Detailed Description
Definition at line 29 of file Calculer_Moments.h.
Constructor & Destructor Documentation
Calculer_Moments::Calculer_Moments ()
Definition at line 27 of file Calculer_Moments.cpp.
Calculer_Moments::~Calculer_Moments ()
Definition at line 27 of file Calculer_Moments.cpp.
Member Function Documentation
const ArrOfDouble& Calculer_Moments::centre_de_gravite () const [inline]
Definition at line 35 of file Calculer_Moments.h.
References c.
  {
    return c;
  };
Objet_U * Calculer_Moments::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 27 of file Calculer_Moments.cpp.
int Calculer_Moments::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 27 of file Calculer_Moments.cpp.
const Type_info * Calculer_Moments::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Calculer_Moments.cpp.
const Type_info * Calculer_Moments::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Calculer_Moments.cpp.
Entree & Calculer_Moments::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 41 of file Calculer_Moments.cpp.
References Interprete_geometrique_base::associer_domaine(), c, Zone::calculer_mon_centre_de_gravite(), Cerr, Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), Zone::exporter_mon_centre_de_gravite(), finl, Zone::Moments_a_imprimer(), ArrOfDouble::resize_array(), and Domaine::zone().
{
  Motcle nom_var;
  associer_domaine(is);
  c.resize_array(dimension);
  Domaine& dom=domaine();
  is >> nom_var;
  Cerr << nom_var << finl;
  dom.zone(0).Moments_a_imprimer()=1;
  if(nom_var=="calcul")
    {
      Cerr << "Calculation of center of gravity " << nom_var<< finl;
      dom.zone(0).calculer_mon_centre_de_gravite(c);
    }
  else if (nom_var=="centre_de_gravite")
    {
      Cerr << "Center of gravity imposed, of dimension " << dimension << finl;
      is >> c[0];
      is >> c[1];
      if (dimension==3)
        is >> c[2];
      dom.zone(0).exporter_mon_centre_de_gravite(c);
    }
  else
    {
      Cerr << nom_var << " is not recognized." << finl;
      exit();
    }
  return is;
}
Sortie & Calculer_Moments::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Calculer_Moments.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Calculer_Moments::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 36 of file Calculer_Moments.cpp.
{
  return is;
}
Calculer_Moments & Calculer_Moments::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Calculer_Moments.cpp.
const Calculer_Moments & Calculer_Moments::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file Calculer_Moments.cpp.
unsigned Calculer_Moments::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 27 of file Calculer_Moments.cpp.
Member Data Documentation
ArrOfDouble Calculer_Moments::c [private]
Definition at line 41 of file Calculer_Moments.h.
Referenced by centre_de_gravite(), and interpreter_().
const Type_info Calculer_Moments::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 32 of file Calculer_Moments.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Calculer_Moments.h
src/Kernel/Geometrie/Calculer_Moments.cpp