TRUST: ConstDoubleTab_parts Class Reference
ConstDoubleTab_parts Class Reference
This class allows to acces to individual sub-parts of const DoubleTab
objects that have a MD_Vector_composite descriptor. It is designed
to preserve the const-ness of the object.
#include <ConstDoubleTab_parts.h>
Public Member Functions
ConstDoubleTab_parts ()
ConstDoubleTab_parts (const DoubleVect &)
void initialize (const DoubleVect &)
void reset ()
const DoubleTab & operator[] (int i) const
int size () const
Private Member Functions
ConstDoubleTab_parts & operator= (const ConstDoubleTab_parts &)
ATTENTION: les operateurs suivants sont interdits !
Si une classe contient ceci:
class Toto {
DoubleVect x;
ConstDoubleTab_parts x_parts; // pointe sur x
};
Alors l'operateur= et le constructeur par copie devraient faire pointer
la classe x_parts sur la copie de x. Ce n'est pas possible avec un
constructeur par defaut qui appellerait les methodes ci-dessous.
Donc pour empecher une erreur, j'interdit ces methodes !
(note: probleme identique avec les REF, mais en general on n'a aucun
interet a mettre une REF qui pointe a l'interieur de la classe...)
ConstDoubleTab_parts (const ConstDoubleTab_parts &)
Interdit !
Private Attributes
Vect_DoubleTab parts_
Detailed Description
This class allows to acces to individual sub-parts of const DoubleTab
objects that have a MD_Vector_composite descriptor. It is designed
to preserve the const-ness of the object.
Definition at line 32 of file ConstDoubleTab_parts.h.
Constructor & Destructor Documentation
ConstDoubleTab_parts::ConstDoubleTab_parts () [inline]
Definition at line 35 of file ConstDoubleTab_parts.h.
{};
ConstDoubleTab_parts::ConstDoubleTab_parts (const DoubleVect & vect)
Definition at line 159 of file ConstDoubleTab_parts.cpp.
References init_parts(), parts_, and ref_cast_non_const.
{
// Cast en non const: pour remplir les ref dans parts_.
// Pas grave, ensuite les sous parties ne seront accessibles qu'en const de l'exterieur.
  DoubleVect& vect2=ref_cast_non_const(DoubleVect, vect);
  init_parts( vect2, parts_, (DoubleTab*) 0);
}
ConstDoubleTab_parts::ConstDoubleTab_parts (const ConstDoubleTab_parts &) [private]
Interdit !
Definition at line 257 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to copy constructor ConstDoubleTab_parts::ConstDoubleTab_parts(const ConstDoubleTab_parts &) is forbidden" << finl;
  Process::exit();
}
Member Function Documentation
void ConstDoubleTab_parts::initialize (const DoubleVect & vect)
Definition at line 167 of file ConstDoubleTab_parts.cpp.
References init_parts(), parts_, ref_cast_non_const, and reset().
{
  reset();
// Cast en non const: pour remplir les ref dans parts_.
// Pas grave, ensuite les sous parties ne seront accessibles qu'en const de l'exterieur.
  DoubleVect& vect2=ref_cast_non_const(DoubleVect, vect);
  init_parts( vect2, parts_, (DoubleTab*) 0);
}
ConstDoubleTab_parts & ConstDoubleTab_parts::operator= (const ConstDoubleTab_parts &) [private]
ATTENTION: les operateurs suivants sont interdits !
Si une classe contient ceci:
class Toto {
DoubleVect x;
ConstDoubleTab_parts x_parts; // pointe sur x
};
Alors l'operateur= et le constructeur par copie devraient faire pointer
la classe x_parts sur la copie de x. Ce n'est pas possible avec un
constructeur par defaut qui appellerait les methodes ci-dessous.
Donc pour empecher une erreur, j'interdit ces methodes !
(note: probleme identique avec les REF, mais en general on n'a aucun
interet a mettre une REF qui pointe a l'interieur de la classe...)
Definition at line 249 of file ConstDoubleTab_parts.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr << "Internal error: call to ConstDoubleTab_parts::operator=(const ConstDoubleTab_parts &) is forbidden" << finl;
  Process::exit();
  return *this;
}
const DoubleTab& ConstDoubleTab_parts::operator[] (int i) const [inline]
Definition at line 39 of file ConstDoubleTab_parts.h.
References parts_.
  {
    return parts_[i];
  }
void ConstDoubleTab_parts::reset ()
Definition at line 176 of file ConstDoubleTab_parts.cpp.
References vect_impl::dimensionner_force(), and parts_.
Referenced by initialize().
{
  parts_.dimensionner_force(0);
}
int ConstDoubleTab_parts::size () const [inline]
Definition at line 43 of file ConstDoubleTab_parts.h.
References parts_, and vect_impl::size().
Referenced by Debog_Pb::ecrire_partie(), ecriture_special_part2(), SETS::eliminer(), PrecondA::prepare_(), and Debog_Pb::verifier_partie().
  {
    return parts_.size();
  }
Member Data Documentation
Vect_DoubleTab ConstDoubleTab_parts::parts_ [private]
Definition at line 53 of file ConstDoubleTab_parts.h.
Referenced by ConstDoubleTab_parts(), initialize(), operator[](), reset(), and size().
The documentation for this class was generated from the following files:
src/Kernel/Math/ConstDoubleTab_parts.h
src/Kernel/Math/ConstDoubleTab_parts.cpp