TRUST: Phases Class Reference
Phases Class Reference
#include <Phases.h>
Public Member Functions
Phases ()
~Phases ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Fonction principale de l'interprete Phases
Lit la dimension d'espace du probleme.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Phases & self_cast (Objet_U &)
static const Phases & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 30 of file Phases.h.
Constructor & Destructor Documentation
Phases::Phases ()
Definition at line 28 of file Phases.cpp.
Phases::~Phases ()
Definition at line 28 of file Phases.cpp.
Member Function Documentation
Objet_U * Phases::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
int Phases::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
const Type_info * Phases::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
const Type_info * Phases::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
Entree & Phases::interpreter (Entree & is) [virtual]
Fonction principale de l'interprete Phases
Lit la dimension d'espace du probleme.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 55 of file Phases.cpp.
References Vect_Nom::add(), Cerr, Pb_Multiphase::creer_milieu(), Process::exit(), finl, Interprete::objet(), ref_cast, and Pb_Multiphase::set_noms_phases().
{
  Nom nom_pb, mot, nom_phase, nom_milieu;
  is >> nom_pb;
  Pb_Multiphase& pb = ref_cast(Pb_Multiphase, objet(nom_pb));
  Noms noms_phases;
  is >> mot;
  if (mot != "{") Cerr << "Phases : { expected instead of " << mot << finl, Process::exit();
  Noms noms_milieux;
  for (is >> mot; mot != "}"; is >> mot)
    {
      nom_phase = mot;
      if (mot.debute_par("liquide"))  nom_milieu = "liquide";
      else if (mot.debute_par("gaz")) nom_milieu = "gaz";
      else Process::exit("Phases : the names must begin with liquide or gaz");
      is >> mot;
      if (mot != "{") Cerr << "Phases : { expected instead of " << mot << finl, Process::exit();
      for (is >> mot; mot != "}"; is >> mot)
        noms_milieux.add(mot + "_" + nom_milieu), noms_phases.add(nom_phase + "_" + mot);
    }
  pb.set_noms_phases(noms_phases);
  pb.creer_milieu(noms_milieux);
  return is;
}
Sortie & Phases::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 30 of file Phases.cpp.
{
  return Interprete::printOn(os);
}
Entree & Phases::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 35 of file Phases.cpp.
{
  return Interprete::readOn(is);
}
Phases & Phases::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
const Phases & Phases::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
unsigned Phases::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 28 of file Phases.cpp.
Member Data Documentation
const Type_info Phases::info_obj [static]
Reimplemented from Interprete.
Definition at line 32 of file Phases.h.
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Phases.h
src/ThHyd/Multiphase/Phases.cpp