TRUST: Probleme_base Class Reference
Probleme_base Class Reference abstract
classe Probleme_base
C'est un Probleme_U qui n'est pas un couplage.
Le role d'un Probleme_base est la resolution sur un domaine des
equations qui le compose.
Ses membres sont les attributs et les methodes communs
a toutes les classes qui representent des problemes.
Un certains nombre d'objets sont associes au probleme pour
le constituer:
- 1 ou plusieurs equations: objet Equation
- 1 Domaine discretise: objet Domaine_Dis
- un postraitement: objet Postraitement
- Une discretisation: objet Discretistaion
- un schema en temps: objet Schema_temp
#include <Probleme_base.h>
Public Member Functions
~Probleme_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
bool solveTimeStep () override
pour recodage eventuel et appel unifie en python
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Si force=1, effectue le postraitement sans tenir compte des
frequences de postraitement.
Le postraitement est mis a jour et les traitements eventuels sur
les sondes, champs et statistiques sont effectues.
Si force=0, tient compte des frequences d'impression demandees.
int limpr () const override
Demande au schema en temps s'il faut faire une impression.
int lsauv () const override
Demande au schema en temps s'il faut faire une sauvegarde.
void sauver () const override
Ecriture sur fichier en vue d'une reprise (sauvegarde)
virtual void allocation () const
Verifie que la place necessaire existe sur le disque dur.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
Probleme_base ()
virtual void associer ()
Associe le probleme a toutes ses equations.
virtual Entree & lire_equations (Entree &is, Motcle &dernier_mot)
Lecture des equations du probleme.
virtual void completer ()
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
virtual int verifier ()
Verifie que l'objet est complet, coherent, ...
NON DEVELOPPE RENVOIE TOUJOURS 1.
virtual int nombre_d_equations () const =0
virtual const Equation_base & equation (int) const =0
virtual Equation_base & equation (int)=0
const Equation_base & equation (const Nom &) const
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
(version const)
Equation_base & equation (const Nom &)
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
virtual const Equation_base & get_equation_by_name (const Nom &) const
virtual Equation_base & getset_equation_by_name (const Nom &)
virtual const Milieu_base & milieu () const
Renvoie le milieu physique associe au probleme.
(version const)
On renvoie le milieu associe a la premiere equation.
virtual Milieu_base & milieu ()
Renvoie le milieu physique associe au probleme.
On renvoie le milieu associe a la premiere equation.
int sauvegarder (Sortie &) const override
Ecriture du probleme sur fichier en vue d'une reprise.
Ecrit le nom du probleme et sauvegarde les equations.
int reprendre (Entree &) override
Lecture d'un flot d'entree (fichier) pour reprise apres
une sauvegarde avec Probleme_base::sauvegarder(Sortie& os).
virtual void imprimer (Sortie &os) const
Appelle imprimer sur chaque equation.
virtual double calculer_pas_de_temps () const
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees
au probleme.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
virtual void preparer_calcul ()
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
virtual void associer_domaine (const Domaine &)
Associe un domaine au probleme.
Prend un_domaine comme support.
apelle Domaine_dis::associer_dom(const Domaine&)
virtual void associer_milieu_base (const Milieu_base &)
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
int associer_ (Objet_U &) override
surcharge Objet_U::associer_(Objet_U& ob)
Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
virtual void discretiser (const Discretisation_base &)
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
virtual void finir ()
Finit le postraitement et sauve le probleme dans un fichier.
Fermeture du fichier associe au postraitement.(Postraitement::finir())
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe au probleme. (si il est non nul)
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe au probleme. (si il est non nul)
const Domaine & domaine () const
Renvoie le domaine associe au probleme.
(version const)
Domaine & domaine ()
Renvoie le domaine associe au probleme.
const Domaine_dis & domaine_dis () const
Renvoie le domaine discretise associe au probleme.
(version const)
Domaine_dis & domaine_dis ()
Renvoie le domaine discretise associe au probleme.
int is_dilatable () const
virtual int allocate_file_size (long int &size) const
Verifie que la place necessaire existe sur le disque dur.
virtual int file_size_xyz () const
Ecrit le probleme dans un fichier *.calcul_xyz
et calcul la place disque prise par ce fichier.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au probleme
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du probleme
const Discretisation_base & discretisation () const
Renvoie la discretisation associee au probleme.
Postraitements & postraitements ()
const Postraitements & postraitements () const
void init_postraitements ()
virtual int expression_predefini (const Motcle &motlu, Nom &expression)
const char * reprise_format_temps () const
int & reprise_effectuee ()
int reprise_effectuee () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual bool has_champ (const Motcle &nom) const
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &nom) const
virtual int verifie_tdeb_tfin (const Motcle &nom) const
On verifie que le temps de debut et de fin des statistiques est identique sur tous les champsde tous les postraitements.
virtual int a_pour_IntVect (const Motcle &, Ref_IntVect &) const
virtual void lire_postraitement_interfaces (Entree &is)
virtual void postraiter_interfaces (const Nom &nom_fich, Sortie &s, const Nom &format, double temps)
virtual void addInputField (Field_base &f)
void sauver_xyz (int) const
void set_coupled (int i)
int get_coupled () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Probleme_base & self_cast (Objet_U &)
static const Probleme_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Entree & readOn (Entree &) override
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Protected Member Functions inherited from Probleme_U
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Domaine_dis le_domaine_dis
Postraitements les_postraitements
Ref_Schema_Temps_base le_schema_en_temps
Ref_Discretisation_base la_discretisation
List_Ref_Field_base input_fields
List of input fields inside this problem.
Deriv_Sortie_Fichier_base ficsauv_
Sortie_Brute * osauv_hdf_
int reprise_effectuee_
int reprise_version_
Nom nom_fich
Nom format_sauv
int restart_file
bool initialized
true if initialize was called
bool terminated
true if terminate was called
bool dt_defined
true if computation interval is defined set to true by initTimeStep, to false by validateTimeStep & abortTimeStep
bool dt_validated
true if last computation was validated set to true by validateTimeStep, to false by initTimeStep
double tstat_deb_
double tstat_fin_
Nom error
Erreur d'allocation.
int coupled_
Flag to indicate it is a part of a coupled problem.
List_Ref_Loi_Fermeture_base liste_loi_fermeture_
liste des fermetures associees au probleme
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Static Protected Attributes
static long int file_size =0
Espace disque pris par les sauvegarde XYZ.
static int bad_allocate =1
1 si allocation reussi, 0 sinon
static int nb_pb_total =0
Nombre total de probleme.
static int num_pb =1
numero du probleme
Detailed Description
classe Probleme_base
C'est un Probleme_U qui n'est pas un couplage.
Le role d'un Probleme_base est la resolution sur un domaine des
equations qui le compose.
Ses membres sont les attributs et les methodes communs
a toutes les classes qui representent des problemes.
Un certains nombre d'objets sont associes au probleme pour
le constituer:
- 1 ou plusieurs equations: objet Equation
- 1 Domaine discretise: objet Domaine_Dis
- un postraitement: objet Postraitement
- Une discretisation: objet Discretistaion
- un schema en temps: objet Schema_temp
See also
Probleme
Classe abstraite dont tous les problemes doivent deriver.
Methodes abstraites:
int nombre_d_equations() const
const Equation_base& equation(int) const
Equation_base& equation(int)
Definition at line 62 of file Probleme_base.h.
Constructor & Destructor Documentation
~Probleme_base()
Probleme_base::~Probleme_base () override
Definition at line 74 of file Probleme_base.cpp.
{
  glob_noms_fichiers.vide();
  glob_derniers_posts.vide();
}
References glob_derniers_posts, glob_noms_fichiers, and liste::vide().
Probleme_base()
Probleme_base::Probleme_base ()
Definition at line 359 of file Probleme_base.cpp.
                             :
// ficsauv(0),
  osauv_hdf_(0),
  reprise_effectuee_(0),
  reprise_version_(155),
  restart_file(0),
  initialized(false),
  terminated(false),
  dt_defined(false),
  dt_validated(false),
  coupled_(0)
{
  tstat_deb_=tstat_fin_=-1;
}
References tstat_deb_, and tstat_fin_.
Member Function Documentation
a_pour_IntVect()
int Probleme_base::a_pour_IntVect (const Motcle & , Ref_IntVect &) const virtual
Definition at line 1814 of file Probleme_base.cpp.
{
  return 0;
}
Referenced by Postraitement::lire_tableaux_a_postraiter(), and Sonde_Int::readOn().
abortTimeStep()
void Probleme_base::abortTimeStep () override virtual
Aborts the resolution of the current time step.
Reimplemented from Probleme_U.
Definition at line 321 of file Probleme_base.cpp.
{
  if (!dt_defined)
    throw WrongContext(le_nom().getChar(),"abortTimeStep","initTimeStep should have been called");
  schema_temps().abortTimeStep();
  milieu().abortTimeStep();
  dt_defined=false;
}
References Milieu_base::abortTimeStep(), Schema_Temps_base::abortTimeStep(), dt_defined, le_nom(), milieu(), and schema_temps().
Referenced by Schema_Implicite_Multi_TimeStep_base::iterateTimeStep().
addInputField()
void Probleme_base::addInputField (Field_base & f) virtual
Definition at line 2110 of file Probleme_base.cpp.
{
  const Nom& name= f.le_nom();
  for (int i=0; i<input_fields.size(); i++)
    {
      if (input_fields[i]->le_nom()==name)
        throw WrongContext(name.getChar(),"addInputField", "Field with this name is already in list");
    }
  input_fields.add(f);
}
References List_Ref_Field_base::add(), Nom::getChar(), input_fields, Field_base::le_nom(), le_nom(), and liste::size().
Referenced by Ch_front_input::readOn(), Ch_front_input_uniforme::readOn(), Champ_input_P0::readOn(), and Ch_input_uniforme::readOn().
allocate_file_size()
int Probleme_base::allocate_file_size (long int & size) const virtual
Verifie que la place necessaire existe sur le disque dur.
Returns
int
Signification: retourne 1 si l'espace disque est suffisant, 0 sinon
Contraintes:
< Fichier d'allocation if (size<1048576) // Si size est trop petit on le fixe a 1 Mo size=1048576;
< Convertion de la taille du fichier 2*size
< Ouverture du fichier File_size
< Erreur d'ouverture
< Erreur sur l'ouverture
< fermeture du fichier
< Destruction du fichier File_size
< Echec d'allocation car fichier pas ouvert
< Erreur d'allocation de l'espace disque
< Erreur sur l'allocation
< fermeture du fichier
< Destruction du fichier File_size
< Echec d'allocation car pas assez de place
< fermeture du fichier
< Destruction du fichier File_size
Definition at line 2033 of file Probleme_base.cpp.
{
#ifndef MICROSOFT
#ifndef __APPLE__
#ifndef RS6000
#ifdef CHECK_ALLOCATE
  Nom Fichier_File_size(Objet_U::nom_du_cas());
  Fichier_File_size+="_File_size";
  const char *file = Fichier_File_size;                        //!< Fichier d'allocation  if (size<1048576)                                        // Si size est trop petit on le fixe a 1 Mo     size=1048576;
//
//
  off_t taille = off_t(size+size);                        //!< Convertion de la taille du fichier 2*size
  int fichier = open(file, O_WRONLY | O_CREAT, 0666);        //!< Ouverture du fichier File_size
  if (fichier == -1)                                        //!< Erreur d'ouverture
    {
      error="Open of ";
      error+=file;
      error+=" : ";
      error+=strerror(errno);                                //!< Erreur sur l'ouverture
      close(fichier);                                        //!< fermeture du fichier
      remove(file);                                        //!< Destruction du fichier File_size
      return 0;                                                //!< Echec d'allocation car fichier pas ouvert
    }
  if (posix_fallocate(fichier, 0, taille) != 0)                //!< Erreur d'allocation de l'espace disque
    {
      error="Allocation of ";
      error+=file;
      error+=" : ";
      error+=strerror(errno);                                //!< Erreur sur l'allocation
      close(fichier);                                        //!< fermeture du fichier
      remove(file);                                        //!< Destruction du fichier File_size
      return 0;                                                //!< Echec d'allocation car pas assez de place
    }
  close(fichier);                                        //!< fermeture du fichier
  remove(file);                                                //!< Destruction du fichier File_size
#endif
#endif
#endif
#endif
  return 1;
}
References error, and Objet_U::nom_du_cas().
Referenced by allocation().
allocation()
void Probleme_base::allocation () const virtual
Verifie que la place necessaire existe sur le disque dur.
< Permet de tester l'allocation d'espace disque
< Si l'allocation n'a pas eut lieu
< Qu'avec le proc maitre
< Si le probleme est le premier
< je tente une allocation d'espace disque de taille 2*file_size
< Si cela echoue, j'indique au code que l'allocation a deja eut lieu et n'a pas fonctionner
< Si OK, je modifie num_pb pour que les autres pb ne tentent pas d'allocation
< Si le probleme n'est pas le premier, je decremente le numero de probleme
< le processeur maitre envoi bad_allocate a tout le monde
< Si l'allocation a echoue
< Si le numero de probleme correspond au nombre total de probleme
< j'arrete le code de facon claire
< et je sort l'erreur du code
< j'incremente le numero de probleme
Definition at line 1975 of file Probleme_base.cpp.
{
  if(schema_temps().file_allocation() && EcritureLectureSpecial::Active)        //!< Permet de tester l'allocation d'espace disque
    {
      if (bad_allocate==1)                                        //!< Si l'allocation n'a pas eut lieu
        if (Process::je_suis_maitre())                                //!< Qu'avec le proc maitre
          {
            if (num_pb==1)                                                //!< Si le probleme est le premier
              if (!allocate_file_size(file_size))                        //!< je tente une allocation d'espace disque de taille 2*file_size
                bad_allocate=0;                                        //!< Si cela echoue, j'indique au code que l'allocation a deja eut lieu et n'a pas fonctionner
              else
                num_pb=nb_pb_total;                                        //!< Si OK, je modifie num_pb pour que les autres pb ne tentent pas d'allocation
            else
              num_pb-=1;                                                //!< Si le probleme n'est pas le premier, je decremente le numero de probleme
          }
      const int canal = 2007;
      if (Process::je_suis_maitre())                                //!< le processeur maitre envoi bad_allocate a tout le monde
        for (int p=1; p<Process::nproc(); p++)
          envoyer(bad_allocate,p,canal);
      else
        recevoir(bad_allocate,0,canal);
      if (bad_allocate==0)                                        //!< Si l'allocation a echoue
        {
          sauver_xyz(1);
          if (num_pb==nb_pb_total)                                        //!< Si le numero de probleme correspond au nombre total de probleme
            {
              if (Process::je_suis_maitre())
                {
                  Cerr << finl;                                                //!< j'arrete le code de facon claire
                  Cerr << "***Error*** " << error << finl;                //!< et je sort l'erreur du code
                  Cerr << "A xyz backup was made because you do not have enough disk space" << finl;
                  Cerr << "to continue the current calculation. Free up disk space and" << finl;
                  Cerr << "restart the calculation thanks to the backup just made." << finl;
                  Cerr << finl;
                }
              barrier();
              exit();
            }
          num_pb+=1;                                                //!< j'incremente le numero de probleme
        }
    }
}
References EcritureLectureSpecial::Active, allocate_file_size(), bad_allocate, Process::barrier(), Cerr, envoyer(), error, Process::exit(), file_size, finl, Process::je_suis_maitre(), nb_pb_total, Process::nproc(), num_pb, recevoir(), sauver_xyz(), and schema_temps().
Referenced by validateTimeStep().
associer()
void Probleme_base::associer () virtual
Associe le probleme a toutes ses equations.
Definition at line 760 of file Probleme_base.cpp.
{
  int nb_eqn=nombre_d_equations();
  for(int i=0; i<nb_eqn; i++)
    equation(i).associer_pb_base(*this);
}
References Equation_base::associer_pb_base(), equation(), and nombre_d_equations().
Referenced by discretiser().
associer_()
int Probleme_base::associer_ (Objet_U & ob) override virtual
surcharge Objet_U::associer_(Objet_U& ob)
Associe differents objets au probleme en controlant
le type de l'objet a associer a l'execution.
On peut ainsi associer: un schema en temps, un domaine de calcul ou
un milieu physique.
Utilise les routine de la classe Type_Info (Utilitaires)
Returns
int
Signification: 1 si association reussie 0 sinon
2 si le milieu est deja associe a un autre probleme
Contraintes:
Reimplemented from Objet_U.
Definition at line 789 of file Probleme_base.cpp.
{
// Schema_Temps_base Domaine Milieu_base
  if( sub_type(Schema_Temps_base, ob))
    {
      associer_sch_tps_base(ref_cast(Schema_Temps_base, ob));
      return 1;
    }
  if( sub_type(Domaine, ob))
    {
      associer_domaine(ref_cast(Domaine, ob));
      return 1;
    }
  if( sub_type(Milieu_base, ob))
    {
      if (!ref_cast(Milieu_base, ob).est_deja_associe())
        return 2;
      associer_milieu_base(ref_cast(Milieu_base, ob));
      return 1;
    }
  if (sub_type(Loi_Fermeture_base,ob))
    {
      Loi_Fermeture_base& loi=ref_cast(Loi_Fermeture_base,ob);
      liste_loi_fermeture_.add(loi);
      loi.associer_pb_base(*this);
      return 1;
    }
  return 0;
}
References List_Ref_Loi_Fermeture_base::add(), associer_domaine(), associer_milieu_base(), Loi_Fermeture_base::associer_pb_base(), associer_sch_tps_base(), liste_loi_fermeture_, ref_cast, and sub_type.
associer_domaine()
void Probleme_base::associer_domaine (const Domaine & un_domaine) virtual
Associe un domaine au probleme.
Prend un_domaine comme support.
apelle Domaine_dis::associer_dom(const Domaine&)
Definition at line 888 of file Probleme_base.cpp.
{
  le_domaine_dis.associer_domaine(un_domaine);
}
References Domaine_dis::associer_domaine(), and le_domaine_dis.
Referenced by associer_(), and Pb_MED::readOn().
associer_milieu_base()
void Probleme_base::associer_milieu_base (const Milieu_base & mil) virtual
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
Reimplemented in Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_QC_base, Pb_WC_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, and Pb_Multiphase.
Definition at line 1462 of file Probleme_base.cpp.
{
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).associer_milieu_base(mil);
}
References Equation_base::associer_milieu_base(), equation(), and nombre_d_equations().
Referenced by associer_(), and Pb_Dilatable_base::associer_milieu_base().
associer_sch_tps_base()
void Probleme_base::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) virtual
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
Reimplemented in Pb_Dilatable_base.
Definition at line 1304 of file Probleme_base.cpp.
{
  if (le_schema_en_temps.non_nul())
    {
      Cerr << finl;
      Cerr<<"Error: Problem "<<le_nom()<<" was already associated with the scheme "<< le_schema_en_temps.valeur().le_nom()<<" and we try to associate it with "<<un_schema_en_temps.le_nom() << "." <<finl;
      exit();
    }
  le_schema_en_temps=un_schema_en_temps;
  le_schema_en_temps->associer_pb(*this);
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).associer_sch_tps_base(un_schema_en_temps);
}
References Schema_Temps_base::associer_pb(), Equation_base::associer_sch_tps_base(), Cerr, equation(), Process::exit(), finl, le_nom(), Schema_Temps_base::le_nom(), le_schema_en_temps, nombre_d_equations(), O_U_Ptr::non_nul(), and Ref_Schema_Temps_base::valeur().
Referenced by associer_(), Pb_Dilatable_base::associer_sch_tps_base(), Probleme_Couple::associer_sch_tps_base(), and Pbc_MED::readOn().
calculer_pas_de_temps()
double Probleme_base::calculer_pas_de_temps () const virtual
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees
au probleme.
Returns
double
Signification: le pas de temps maximum autorise pour ce probleme
Contraintes:
Definition at line 1926 of file Probleme_base.cpp.
{
  Debog::set_nom_pb_actuel(le_nom());
  double dt=schema_temps().pas_temps_max();
  for(int i=0; i<nombre_d_equations(); i++)
    dt=std::min(dt,equation(i).calculer_pas_de_temps());
  return dt;
}
References Equation_base::calculer_pas_de_temps(), equation(), le_nom(), nombre_d_equations(), Schema_Temps_base::pas_temps_max(), schema_temps(), and Debog::set_nom_pb_actuel().
Referenced by Schema_Temps_base::abortTimeStep(), Schema_Temps_base::initialize(), and Schema_Temps_base::mettre_a_jour_dt_stab().
completer()
void Probleme_base::completer () virtual
Complete les equations associees au probleme.
Remplissage des references, deleguee aux equations.
Reimplemented in Pb_Multiphase.
Definition at line 835 of file Probleme_base.cpp.
{
// Cerr << "Probleme_base::completer()" << finl;
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).completer();
  LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.completer();
      ++curseur;
    }
  les_postraitements.completer();
}
References Equation_base::completer(), Loi_Fermeture_base::completer(), Postraitements::completer(), equation(), les_postraitements, LIST_CURSEUR, liste_loi_fermeture_, nombre_d_equations(), and REF.
Referenced by Pb_Multiphase::completer(), and readOn().
comprend_champ_post()
int Probleme_base::comprend_champ_post (const Motcle & nom) const virtual
Definition at line 1735 of file Probleme_base.cpp.
{
  if (un_nom=="TEMPERATURE_PHYSIQUE")
    return 0;
  CONST_LIST_CURSEUR(DERIV(Postraitement_base)) curseur_post = postraitements();
  while (curseur_post)
    {
      const Postraitement& post = ref_cast(Postraitement,curseur_post.valeur().valeur());
      if (post.comprend_champ_post(un_nom))
        return 1;
      ++curseur_post;
    }
  return 0;
}
References Postraitement::comprend_champ_post(), CONST_LIST_CURSEUR, DERIV, postraitements(), and ref_cast.
Referenced by findOutputField(), and Postraitement::verifie_nom_et_sources().
computeTimeStep()
double Probleme_base::computeTimeStep (bool & stop) const override virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
Returns
double
Signification: The desired time step
Contraintes:
Reimplemented from Probleme_U.
Definition at line 293 of file Probleme_base.cpp.
{
  if (!initialized)
    throw WrongContext(le_nom().getChar(),"computeTimeStep","initialize should have been called");
  if (terminated)
    throw WrongContext(le_nom().getChar(),"computeTimeStep","terminate should not have been called");
  Debog::set_nom_pb_actuel(le_nom());
  double dt=schema_temps().computeTimeStep(stop);
  return dt;
}
References Schema_Temps_base::computeTimeStep(), initialized, le_nom(), schema_temps(), Debog::set_nom_pb_actuel(), and terminated.
creer_champ()
void Probleme_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
Reimplemented in Pb_MED.
Definition at line 1605 of file Probleme_base.cpp.
{
  milieu().creer_champ(motlu);
  int nb_eq = nombre_d_equations();
  for (int i=0; i<nb_eq; i++)
    equation(i).creer_champ(motlu);
  LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.creer_champ(motlu);
      ++curseur;
    }
}
References Equation_base::creer_champ(), Loi_Fermeture_base::creer_champ(), Milieu_base::creer_champ(), equation(), LIST_CURSEUR, liste_loi_fermeture_, milieu(), nombre_d_equations(), and REF.
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Elem::completer(), Op_Diff_Turbulent_PolyMAC_P0_Face::completer(), Postraitement_lata::lire_champs(), Postraitement::lire_champs_a_postraiter(), Champ_Generique_refChamp::lire_motcle_non_standard(), Equation_base::lire_motcle_non_standard(), Sonde::readOn(), and Portance_interfaciale_PolyMAC_P0::readOn().
discretisation()
const Discretisation_base & Probleme_base::discretisation () const inline
Renvoie la discretisation associee au probleme.
Returns
Discretisation_base&
Signification: discretisation associee au probleme
Contraintes: reference constante
Definition at line 307 of file Probleme_base.h.
{
  if(!la_discretisation.non_nul())
    {
      Cerr << que_suis_je() << " has not been discretized!" << finl;
      exit();
    }
  return la_discretisation.valeur();
}
References Cerr, Process::exit(), finl, la_discretisation, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and Ref_Discretisation_base::valeur().
Referenced by Equation_base::assembler(), Convection_Diffusion_Temperature::assembler(), Op_Grad_EF::associer(), Source_PDF_EF::associer_pb(), Op_Correlation::completer(), Turbulence_paroi_base::creer_champ(), Equation_base::discretisation(), Champ_Generique_Extraction::discretiser_domaine(), Champ_Generique_Interpolation::discretiser_domaine(), get_champ(), Champ_Generique_base::get_discretisation(), Diametre_hyd_champ::interpreter(), Porosites_champ::interpreter(), Terme_Puissance_Thermique::lire_donnees(), Postraitement_lata::postraiter(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), and Zone_Cl_EF::remplir_type_elem_Cl().
discretiser()
void Probleme_base::discretiser (const Discretisation_base & une_discretisation) virtual
Affecte une discretisation au probleme
Discretise le Domaine associe au probleme avec la discretisation
Associe la premiere zone du Domaine aux equations du probleme
Discretise les equations associees au probleme
NOTE: TRUST V1 une seule Zone_dis pas Domaine_dis est traitee.
Reimplemented in Pb_Multiphase.
Definition at line 911 of file Probleme_base.cpp.
{
  associer();
  la_discretisation=une_discretisation;
  Cerr << "Discretization of the domain associated with the problem " << le_nom() << finl;
  une_discretisation.discretiser(le_domaine_dis);
  Cerr << "Discretization of equations" << finl;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      equation(i).associer_zone_dis(domaine_dis().zone_dis(0));
      equation(i).discretiser();
// remontee de l'inconnue vers le milieu
      equation(i).associer_milieu_equation();
    }
// Discretisation du milieu:
// ATTENTION (BM): il faudra faire quelque chose ici car si on associe deux
// milieux au probleme (fluide_incompressible + constituant), seul
// le premier est discretise.
// Cette facon de faire n'est pas propre !
// Solution probable: gros nettoyage et on met le milieu dans le probleme
  Noms milieux_deja_discretises;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      const Nom& le_milieu = equation(i).milieu().que_suis_je();
      if (!milieux_deja_discretises.contient_(le_milieu))
        {
          equation(i).milieu().discretiser((*this),une_discretisation);
          milieux_deja_discretises.add(le_milieu);
        }
    }
  LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.discretiser(une_discretisation);
      ++curseur;
    }
}
References Vect_Nom::add(), associer(), Equation_base::associer_milieu_equation(), Equation_base::associer_zone_dis(), Cerr, Noms::contient_(), Equation_base::discretiser(), Loi_Fermeture_base::discretiser(), Milieu_base::discretiser(), Discretisation_base::discretiser(), domaine_dis(), equation(), finl, la_discretisation, le_domaine_dis, le_nom(), LIST_CURSEUR, liste_loi_fermeture_, Equation_base::milieu(), nombre_d_equations(), Objet_U::que_suis_je(), and REF.
Referenced by Probleme_Couple::discretiser(), Pb_Multiphase::discretiser(), and Discretiser::interpreter().
domaine() [1/2]
Domaine & Probleme_base::domaine ()
Renvoie le domaine associe au probleme.
Returns
Domaine&
Signification: un domaine
Contraintes:
Definition at line 1403 of file Probleme_base.cpp.
{
  return le_domaine_dis.domaine();
}
References Domaine_dis::domaine(), and le_domaine_dis.
domaine() [2/2]
const Domaine & Probleme_base::domaine () const
Renvoie le domaine associe au probleme.
(version const)
Returns
Domaine&
Signification: un domaine
Contraintes: reference constante
Definition at line 1384 of file Probleme_base.cpp.
{
  return le_domaine_dis.domaine();
}
References Domaine_dis::domaine(), and le_domaine_dis.
Referenced by Mod_turb_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Ch_front_input::buildSommetsFaces(), Terme_Boussinesq_base::check(), Equation_base::completer(), Sonde::completer(), Perte_Charge_PolyMAC::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), Pb_MED::creer_champ(), Marqueur_Lagrange_base::discretiser(), Ch_front_input::getTemplate(), Champ_input_P0::getTemplate(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), initialize(), initTimeStep(), Mod_turb_hyd_base::lire_distance_paroi(), Mod_turb_hyd_base::lire_motcle_non_standard(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Sonde::mettre_a_jour(), Postraitement_lata::postraiter(), Postraitement_lata::postraiter_liste_champs(), Champ_Input_Proto::read(), Debog_Pb::read_geometry_data(), Champ_input_P0::readOn(), Postraitement::readOn(), Sonde::readOn(), Sonde_Int::readOn(), Pb_MED::readOn(), Champ_Fonc_reprise::readOn(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Equation_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_nul::sauvegarder(), Postraitement::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), Champ_front_contact_VEF::test_faces_coin(), and Debog_Pb::write_geometry_data().
domaine_dis() [1/2]
Domaine_dis & Probleme_base::domaine_dis ()
Renvoie le domaine discretise associe au probleme.
Returns
Domaine_dis&
Signification: un domaine discretise
Contraintes:
Definition at line 1442 of file Probleme_base.cpp.
{
  return le_domaine_dis;
}
References le_domaine_dis.
domaine_dis() [2/2]
const Domaine_dis & Probleme_base::domaine_dis () const
Renvoie le domaine discretise associe au probleme.
(version const)
Returns
Domaine_dis&
Signification: un domaine discretise
Contraintes: reference constante
Definition at line 1423 of file Probleme_base.cpp.
{
  return le_domaine_dis;
}
References le_domaine_dis.
Referenced by Op_Ecart_type::completer(), Op_Moyenne::completer(), discretiser(), Loi_Fermeture_Test::discretiser(), Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_zone_dis_base(), initialize(), Postraitement_lata::lire_champs(), Pb_Multiphase::lire_equations(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Postraitement_lata::postraiter(), Postraitement_lata::postraiter_liste_champs(), Debog_Pb::read_geometry_data(), Champ_input_P0::readOn(), Debog_Pb::readOn(), Champ_Fonc_reprise::readOn(), Diametre_bulles_champ::readOn(), Diametre_bulles_constant::readOn(), Champ_Don_Face_lu::readOn(), and Debog_Pb::write_geometry_data().
equation() [1/4]
Equation_base & Probleme_base::equation (const Nom & type)
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
Returns
Equation_base&
Signification: une equation
Contraintes: reference constante
Definition at line 1584 of file Probleme_base.cpp.
{
  Motcle Type(type);
  Motcle Type_eqn;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      Type_eqn = equation(i).que_suis_je();
      if(Type_eqn==Type)
        return equation(i);
    }
  Cerr << que_suis_je() << " does not contain any equation of type: " << type << finl;
  Cerr << "Here is the list of possible equations for a " << que_suis_je() << " problem: " << finl;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      Cerr << "\t- " << equation(i).que_suis_je() << finl;
    }
  exit();
// Pour les compilos;
  return equation(0);
}
References Cerr, equation(), Process::exit(), finl, nombre_d_equations(), and Objet_U::que_suis_je().
equation() [2/4]
const Equation_base & Probleme_base::equation (const Nom & type) const
Renvoie l'equation dont le nom est specifie.
On indexe les equations avec leur nom associe.
On cherche dans toutes les equations du probleme celle
qui porte le nom specifie.
(version const)
Returns
Equation_base&
Signification: une equation
Contraintes: reference constante
Definition at line 1527 of file Probleme_base.cpp.
{
  Motcle Type(type);
  Motcle Type_eqn;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      Type_eqn = equation(i).que_suis_je();
      if(Type_eqn==Type)
        return equation(i);
    }
  Cerr << que_suis_je() << " does not contain any equation of type: " << type << finl;
  Cerr << "Here is the list of possible equations for a " << que_suis_je() << " problem: " << finl;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      Cerr << "\t- " << equation(i).que_suis_je() << finl;
    }
  exit();
// Pour les compilos;
  return equation(0);
}
References Cerr, equation(), Process::exit(), finl, nombre_d_equations(), and Objet_U::que_suis_je().
equation() [3/4]
virtual const Equation_base & Probleme_base::equation (int) const pure virtual
Implemented in Pb_MED, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, and Pb_Conduction.
Referenced by Schema_Temps_base::abortTimeStep(), associer(), Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), associer_milieu_base(), Puissance_Thermique_EF::associer_pb(), Schema_Adams_Bashforth_base::associer_pb(), Schema_Adams_Moulton_base::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Source_QC_QDM_Gen::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Source_Darcy_VDF_Face::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Source_Forchheimer_VDF_Face::associer_pb(), Terme_Source_Constituant_VDF_Elem::associer_pb(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Terme_Source_inc_th_VDF_Face::associer_pb(), Terme_Source_inc_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Source_Darcy_VEF_Face::associer_pb(), Source_Forchheimer_VEF_Face::associer_pb(), Terme_Source_Constituant_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Terme_Source_Th_TdivU_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), associer_sch_tps_base(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), calculer_pas_de_temps(), completer(), Champ_Generique_Divergence::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_modifier_pour_QC::completer(), Fluide_Dilatable_base::completer(), Fluide_Weakly_Compressible::completer(), Chimie::completer(), Fluide_Quasi_Compressible::completer_edo(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Champ_front_contact_VEF::creer(), creer_champ(), Postraitement::creer_champ_post_moreqn(), discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Constituant::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Reaction::discretiser_omega(), equation(), Pb_MED::equation(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), get_champ(), Convection_Diffusion_Espece_Multi_base::get_champ(), get_equation_by_name(), get_noms_champs_postraitables(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), getset_equation_by_name(), has_champ(), Implicite_Multi_TimeStep_recommencer_pb(), imprimer(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), Fluide_Weakly_Compressible::initialiser_pth_xyz(), Schema_Temps_base::initialize(), initTimeStep(), Diametre_hyd_champ::interpreter(), Porosites::interpreter(), Porosites_champ::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), Schema_Temps_base::iterateTimeStep(), iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Postraitement::lire_champs_a_postraiter(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), milieu(), Op_Diff_Turbulent_PolyMAC_P0_Elem::modifier_nu(), postraiter(), preparer_calcul(), Pb_Dilatable_base::preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), printOn(), Champ_front_debit_QC::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Modele_turbulence_scal_base::readOn(), Turbulence_paroi_scal::readOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), reprendre(), sauvegarder(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), solveTimeStep(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Schema_Temps_base::update_critere_statio(), updateGivenFields(), Schema_Temps_base::validateTimeStep(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport(), and Convection_Diffusion_Chaleur_QC::vitesse_pour_transport().
equation() [4/4]
virtual Equation_base & Probleme_base::equation (int) pure virtual
Implemented in Pb_MED, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, and Pb_Conduction.
expression_predefini()
int Probleme_base::expression_predefini (const Motcle & motlu, Nom & expression) virtual
Reimplemented in Pb_Fluide_base.
Definition at line 1005 of file Probleme_base.cpp.
{
  expression = "";
  return 0;
}
Referenced by Pb_Fluide_base::expression_predefini(), Postraitement::lire_champs_a_postraiter(), Postraitement::lire_champs_operateurs(), and Sonde::readOn().
file_size_xyz()
int Probleme_base::file_size_xyz () const virtual
Ecrit le probleme dans un fichier *.calcul_xyz
et calcul la place disque prise par ce fichier.
Returns
int
Signification: retourne toujours 1
Contraintes:
< Calcul de l'espace disque pris par le fichier XYZ du probleme courant
< Incremente l'espace disque deja necessaire
< Permet de connaitre le nombre de probleme total a la fin du preparer_calcul
Definition at line 2092 of file Probleme_base.cpp.
{
#ifndef RS6000
  Nom nom_fich_xyz(".xyz");
  sauver_xyz(0);
  if (Process::je_suis_maitre())
    {
      ifstream fichier(nom_fich_xyz);                        //!< Calcul de l'espace disque pris par le fichier XYZ du probleme courant
      fichier.seekg(0,std::ios_base::end);
      file_size+=fichier.tellg();                                //!< Incremente l'espace disque deja necessaire
      fichier.close();
      remove(nom_fich_xyz);
    }
  nb_pb_total+=1;                                        //!< Permet de connaitre le nombre de probleme total a la fin du preparer_calcul
#endif
  return 1;
}
References file_size, Process::je_suis_maitre(), nb_pb_total, and sauver_xyz().
Referenced by preparer_calcul().
findInputField()
Ref_Field_base Probleme_base::findInputField (const Nom & name) const override virtual
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Returns
REF(Field_base)
Signification: found <=> non_nul(), then points to a Champ_Input_Proto of that name.
Contraintes:
Reimplemented from Probleme_U.
Definition at line 331 of file Probleme_base.cpp.
{
// WEC : there should be a better way to scan the list
  for (int i=0; i<input_fields.size(); i++)
    {
      if (input_fields[i]->le_nom()==name)
        return input_fields[i];
    }
  REF(Field_base) ch;
  return ch;
}
References input_fields, le_nom(), REF, and liste::size().
findOutputField()
Ref_Champ_Generique_base Probleme_base::findOutputField (const Nom & name) const override virtual
Reimplemented from Probleme_U.
Definition at line 343 of file Probleme_base.cpp.
{
  REF(Champ_Generique_base) ch;
  if (comprend_champ_post(name))
    {
      ch=get_champ_post(name);
    }
  return ch;
}
References comprend_champ_post(), get_champ_post(), and REF.
Referenced by Testeur_MEDCoupling::interpreter().
finir()
void Probleme_base::finir () virtual
Finit le postraitement et sauve le probleme dans un fichier.
Fermeture du fichier associe au postraitement.(Postraitement::finir())
Definition at line 1126 of file Probleme_base.cpp.
{
  Debog::set_nom_pb_actuel(le_nom());
  les_postraitements.finir();
  if (schema_temps().temps_sauv() > 0.0)
    sauver();
// On ferme proprement le fichier de sauvegarde
// Si c'est une sauvegarde_simple, le fin a ete mis a chaque appel a ::sauver()
  if (restart_file!=1 && (ficsauv_.non_nul() || osauv_hdf_) )
    {
      if (Motcle(format_sauv)=="xyz")
        {
          if (Process::je_suis_maitre())
            ficsauv_.valeur() << Nom("fin");
          (ficsauv_.valeur()).flush();
          (ficsauv_.valeur()).syncfile();
        }
      else if(Motcle(format_sauv) == "single_hdf")
        {
          *osauv_hdf_ << Nom("fin");
          FichierHDFPar fic_hdf;
          fic_hdf.create(nom_fich);
          fic_hdf.create_and_fill_dataset_MW("/sauv", *osauv_hdf_);
          fic_hdf.close();
          delete osauv_hdf_;
          osauv_hdf_ = 0;
        }
      else
        {
          ficsauv_.valeur() << Nom("fin");
          (ficsauv_.valeur()).flush();
        }
      ficsauv_.detach();
    }
// Si la sauvegarde est classique et que l'utilisateur n'a pas desactive la sauvegarde finale xyz
// alors on effectue la sauvegarde finale xyz
  if (Motcle(format_sauv)!="xyz" && (EcritureLectureSpecial::Active))
    sauver_xyz(1);
}
References EcritureLectureSpecial::Active, FichierHDF::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), Deriv_::detach(), ficsauv_, Postraitements::finir(), format_sauv, Process::je_suis_maitre(), le_nom(), les_postraitements, nom_fich, O_U_Ptr::non_nul(), osauv_hdf_, restart_file, sauver(), sauver_xyz(), schema_temps(), Debog::set_nom_pb_actuel(), and Deriv_Sortie_Fichier_base::valeur().
Referenced by terminate().
futureTime()
double Probleme_base::futureTime () const override virtual
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Returns
double
Signification: future time
Contraintes:
Reimplemented from Probleme_U.
Definition at line 2121 of file Probleme_base.cpp.
{
  if (!dt_defined)
    throw WrongContext(le_nom().getChar(),"futureTime","initTimeStep should have been called");
  int i=schema_temps().nb_valeurs_futures();
  return schema_temps().temps_futur(i);
}
References dt_defined, le_nom(), Schema_Temps_base::nb_valeurs_futures(), schema_temps(), and Schema_Temps_base::temps_futur().
Referenced by Ch_front_input::getTemplate(), Ch_front_input_uniforme::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), and Ch_front_input_P1::getTemplate().
get_champ()
const Champ_base & Probleme_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Pb_MED, and Pb_Multiphase.
Definition at line 1662 of file Probleme_base.cpp.
{
  int nb_eq = nombre_d_equations();
  for (int i=0; i<nb_eq; i++)
    {
      try
        {
          return equation(i).get_champ(un_nom);
        }
      catch (Champs_compris_erreur)
        {
        }
      try
        {
          return equation(i).milieu().get_champ(un_nom);
        }
      catch (Champs_compris_erreur)
        {
        }
    }
  CONST_LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      const Loi_Fermeture_base& loi=curseur.valeur().valeur();
      try
        {
          return loi.get_champ(un_nom);
        }
      catch(Champs_compris_erreur)
        {
        }
      ++curseur;
    }
  if (discretisation().que_suis_je()=="VDF")
    {
      Cerr << "\n" << un_nom << " is not available for VDF discretization" << finl;
      exit();
    }
  Cerr<<"The field of name "<<un_nom<<" do not correspond to a field understood by the problem."<<finl;
  Cerr<<"It may be a field dedicated only to post-process and defined in the Definition_champs set."<<finl;
  Cerr<<"1) If you have request the post-processing of "<<un_nom<<" in the Champs set"<<finl;
  Cerr<<"please remove the localisation elem or som that you may have specified."<<finl;
  Cerr<<"2) If you have used "<<un_nom<<" in Definition_champs, please use 'sources_reference { "<<un_nom<<" }'"<<finl;
  Cerr<<"instead of 'source refchamp { pb_champ "<<le_nom()<<" "<<un_nom<<" }'"<<finl;
  Cerr<<"3) Check reference manual." << finl;
  Cerr<<"4) Contact TRUST support." << finl;
  exit();
// Pour compilation
  REF(Champ_base) ref_champ;
  return ref_champ;
}
References Cerr, CONST_LIST_CURSEUR, discretisation(), equation(), Process::exit(), finl, Equation_base::get_champ(), Loi_Fermeture_base::get_champ(), Milieu_base::get_champ(), le_nom(), liste_loi_fermeture_, Equation_base::milieu(), nombre_d_equations(), Objet_U::que_suis_je(), and REF.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), Assembleur_P_PolyMAC::assembler_continuite(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Op_Conv_EF::calculer_dt_stab(), Flux_interfacial_Ranz_Marshall::coeffs(), Sonde::completer(), Champ_front_contact_VEF::creer(), Postraitement::creer_champ_post(), Op_Conv_EF_Stab_PolyMAC_Elem::dimensionner_blocs(), Masse_PolyMAC_Elem::dimensionner_blocs(), Flux_interfacial_PolyMAC::dimensionner_blocs(), Equation_base::ecrire_fichier_xyz(), Champ_Generique_refChamp::get_champ(), Champ_Generique_refChamp_special::get_champ(), Pb_Multiphase::get_champ(), Moyenne_volumique::get_champ(), Sonde::init_bords(), Champ_Fonc_Tabule_Morceaux::initialiser(), Postraitement_lata::lire_champs(), Postraitement::lire_champs_a_postraiter(), Champ_Generique_refChamp::lire_motcle_non_standard(), Champ_Front_Fonction::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Assembleur_P_PolyMAC::modifier_secmem_pour_incr_p(), Discretisation_base::nommer_completer_champ_physique(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_Richardson(), Postraitement_lata::postraiter_liste_champs(), Sonde::readOn(), Champ_Fonc_reprise::readOn(), Source_PDF_EF::rotate_imposed_velocity(), and Convection_Diffusion_std::vitesse_pour_transport().
get_champ_post()
const Champ_Generique_base & Probleme_base::get_champ_post (const Motcle & nom) const virtual
Definition at line 1785 of file Probleme_base.cpp.
{
  REF(Champ_Generique_base) ref_champ;
  CONST_LIST_CURSEUR(DERIV(Postraitement_base)) curseur_post = postraitements();
  while (curseur_post)
    {
      if (sub_type(Postraitement,curseur_post.valeur().valeur()))
        {
          const Postraitement& post = ref_cast(Postraitement,curseur_post.valeur().valeur());
          try
            {
              return post.get_champ_post(un_nom);
            }
          catch (Champs_compris_erreur) { }
        }
      ++curseur_post;
    }
  Cerr<<" "<<finl;
  Cerr<<"The field named "<<un_nom<<" do not correspond to a field understood by the problem."<<finl;
  Cerr<<"Check the name of the field indicated into the postprocessing block of the data file " << finl;
  Cerr<<"or in the list of post-processed fields above (in the block 'Reading of fields to be postprocessed')."<<finl;
  exit();
// Pour compilation
  return ref_champ;
}
References Cerr, CONST_LIST_CURSEUR, DERIV, Process::exit(), finl, Postraitement::get_champ_post(), postraitements(), REF, ref_cast, and sub_type.
Referenced by findOutputField(), and Postraitement::lire_champs_a_postraiter().
get_coupled()
int Probleme_base::get_coupled () const inline
Definition at line 210 of file Probleme_base.h.
  {
    return coupled_;
  };
References coupled_.
Referenced by Equation_base::completer(), and Simpler_Base::get_and_set_parametre_equation().
get_equation_by_name()
const Equation_base & Probleme_base::get_equation_by_name (const Nom & un_nom) const virtual
Definition at line 1552 of file Probleme_base.cpp.
{
  return equation(un_nom);
}
References equation().
get_info()
const Type_info * Probleme_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Pb_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_HEM, and Pb_Conduction.
Definition at line 48 of file Probleme_base.cpp.
get_noms_champs_postraitables()
void Probleme_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
Reimplemented in Pb_MED.
Definition at line 1718 of file Probleme_base.cpp.
{
  milieu().get_noms_champs_postraitables(noms,opt);
  int nb_eq = nombre_d_equations();
  for (int i=0; i<nb_eq; i++)
    equation(i).get_noms_champs_postraitables(noms,opt);
  CONST_LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      const Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.get_noms_champs_postraitables(noms,opt);
      ++curseur;
    }
}
References CONST_LIST_CURSEUR, equation(), Equation_base::get_noms_champs_postraitables(), Loi_Fermeture_base::get_noms_champs_postraitables(), Milieu_base::get_noms_champs_postraitables(), liste_loi_fermeture_, milieu(), nombre_d_equations(), and REF.
Referenced by Postraitement_lata::lire_champs(), Postraitement::lire_champs_a_postraiter(), Postraitement::lire_champs_stat_a_postraiter(), Champ_Generique_refChamp::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Postraitement::lire_tableaux_a_postraiter(), Postraitement::readOn(), Sonde_Int::readOn(), Sondes::set_noms_champs_postraitables(), and Postraitement::verifie_nom_et_sources().
getInputFieldsNames()
void Probleme_base::getInputFieldsNames (Noms & noms) const override virtual
This method is used to find the names of input fields understood by the Problem.
Reimplemented from Probleme_U.
Definition at line 214 of file Probleme_base.cpp.
{
  int n=input_fields.size();
  Noms nouveaux_noms(n);
  for (int i=0; i<n; i++)
    nouveaux_noms[i]=input_fields[i]->le_nom();
// GF pour contourner un bug dans add() si vecteur null
  if (n)
    noms.add(nouveaux_noms);
}
References Vect_Nom::add(), input_fields, le_nom(), and liste::size().
getOutputFieldsNames()
void Probleme_base::getOutputFieldsNames (Noms & noms) const override virtual
This method is used to find the names of output fields understood by the Problem.
Reimplemented from Probleme_U.
Definition at line 226 of file Probleme_base.cpp.
{
  for (int i=0; i<postraitements().size(); i++)
    {
      if (sub_type(Postraitement,postraitements()(i).valeur()))
        {
// LIST(Nom) suite;
          const Liste_Champ_Generique& liste_champ= ref_cast(Postraitement,postraitements()(i).valeur()).champs_post_complet();
          for (int ii=0; ii<liste_champ.size(); ii++)
            noms.add(liste_champ(ii).valeur().get_nom_post() );
        }
    }
}
References Vect_Nom::add(), postraitements(), ref_cast, liste::size(), sub_type, and valeur().
getset_equation_by_name()
Equation_base & Probleme_base::getset_equation_by_name (const Nom & un_nom) virtual
Definition at line 1562 of file Probleme_base.cpp.
{
  return equation(un_nom);
}
References equation().
Referenced by lire_equations(), and Pb_Multiphase::lire_equations().
has_champ()
bool Probleme_base::has_champ (const Motcle & nom) const virtual
Reimplemented in Pb_Multiphase.
Definition at line 1621 of file Probleme_base.cpp.
{
  Champ_base const * champ = NULL ;
  int nb_eq = nombre_d_equations();
  for (int i=0; i<nb_eq; i++)
    {
      try
        {
          champ = &equation(i).get_champ(un_nom);
        }
      catch (Champs_compris_erreur)
        {
        }
      try
        {
          champ = &equation(i).milieu().get_champ(un_nom);
        }
      catch (Champs_compris_erreur)
        {
        }
    }
  CONST_LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      const Loi_Fermeture_base& loi=curseur.valeur().valeur();
      try
        {
          champ = &loi.get_champ(un_nom);
        }
      catch(Champs_compris_erreur)
        {
        }
      ++curseur;
    }
  if (champ) return true ;
  return false;
}
References CONST_LIST_CURSEUR, equation(), Equation_base::get_champ(), Loi_Fermeture_base::get_champ(), Milieu_base::get_champ(), liste_loi_fermeture_, Equation_base::milieu(), nombre_d_equations(), and REF.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_Tomiyama::completer(), and Pb_Multiphase::has_champ().
imprimer()
void Probleme_base::imprimer (Sortie & os) const virtual
Appelle imprimer sur chaque equation.
Imprime les equations associees au probleme si le schema en
temps associe indique que c'est necessaire.
Definition at line 1282 of file Probleme_base.cpp.
{
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).imprimer(os);
}
References equation(), Equation_base::imprimer(), and nombre_d_equations().
Referenced by postraiter().
info()
const Type_info * Probleme_base::info () static
Definition at line 48 of file Probleme_base.cpp.
init_postraitements()
void Probleme_base::init_postraitements ()
< Pour chaque postraitement
< C'est la premiere fois qu'on rencontre ce nom
< On a deja vu ce nom
Definition at line 955 of file Probleme_base.cpp.
{
  LIST_CURSEUR(DERIV(Postraitement_base)) curseur = les_postraitements;
  while(curseur)   //!< Pour chaque postraitement
    {
      DERIV(Postraitement_base)& der_post = curseur.valeur();
// S'il est de type Postraitement, initialiser premier/dernier _pour_nom_fich
      if (sub_type(Postraitement,der_post.valeur()))
        {
          Postraitement& post=ref_cast(Postraitement,der_post.valeur());
          Nom nom_fichier=post.nom_fich();
          int rg=glob_noms_fichiers.rang(nom_fichier);
          if (rg==-1)   //!< C'est la premiere fois qu'on rencontre ce nom
            {
              glob_noms_fichiers.add(nom_fichier);
              glob_derniers_posts.add(post);
              post.est_le_premier_postraitement_pour_nom_fich()=1;
            }
          else   //!< On a deja vu ce nom
            {
              post.est_le_premier_postraitement_pour_nom_fich()=0;
              Postraitement& autre_post=glob_derniers_posts[rg];
              autre_post.est_le_dernier_postraitement_pour_nom_fich()=0;
              glob_derniers_posts[rg]=post;
// On verifie au passage que les intervalles de postraitements
// sont bien les memes pour tout ce qui ecrit dans le meme
// fichier  .
              if (post.champs_demande() && autre_post.dt_post_ch()!=post.dt_post_ch())
                {
                  Cerr << "Error, the values of dt_post (" << autre_post.dt_post_ch()
                       << " and " << post.dt_post_ch()
                       << ") of two postprocessing blocks writing in the same file"
                       << post.nom_fich() << " are different!" << finl;
                  Cerr << "Specify the same dt_post, or use two different files for postprocessing." << finl;
                  exit();
                }
            }
          post.est_le_dernier_postraitement_pour_nom_fich()=1;
        }
      ++curseur;
    }
  les_postraitements.init();
}
References List_Nom::add(), List_Ref_Postraitement::add(), Cerr, Postraitement::champs_demande(), DERIV, Postraitement::dt_post_ch(), Postraitement::est_le_dernier_postraitement_pour_nom_fich(), Postraitement::est_le_premier_postraitement_pour_nom_fich(), Process::exit(), finl, glob_derniers_posts, glob_noms_fichiers, Postraitements::init(), les_postraitements, LIST_CURSEUR, Postraitement::nom_fich(), nom_fichier(), List_Nom::rang(), ref_cast, and sub_type.
Referenced by initialize().
initialize()
void Probleme_base::initialize () override virtual
This method is called once at the beginning, before any other one of
the interface Problem.
< Pour le cas de geometries variables (ex. ALE) on initialise le schema en temps avant le postraitement ainsi les sources qui dependent du pas de temps fonctionnent
Reimplemented from Probleme_U.
Definition at line 86 of file Probleme_base.cpp.
{
  if (initialized)
    throw WrongContext(le_nom().getChar(),"initialize","initialize should not have been called");
  Debog::set_nom_pb_actuel(le_nom());
  preparer_calcul();
  domaine().initialiser(0,domaine_dis(),*this); //!< Pour le cas de geometries variables (ex. ALE) on initialise le schema en temps avant le postraitement ainsi les sources qui dependent du pas de temps fonctionnent
//
//
  schema_temps().initialize();
  init_postraitements();
  initialized=true;
}
References domaine(), domaine_dis(), init_postraitements(), Domaine::initialiser(), Schema_Temps_base::initialize(), initialized, le_nom(), preparer_calcul(), schema_temps(), and Debog::set_nom_pb_actuel().
initTimeStep()
bool Probleme_base::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
Returns
bool
Signification: true=OK, false=error, not able to tackle this dt
Contraintes:
Reimplemented from Probleme_U.
Reimplemented in Pb_Dilatable_base.
Definition at line 113 of file Probleme_base.cpp.
{
  if (!initialized)
    throw WrongContext(le_nom().getChar(),"initTimeStep","initialize should have been called");
  if (terminated)
    throw WrongContext(le_nom().getChar(),"initTimeStep","terminate should not have been called");
  if (dt_defined)
    throw WrongContext(le_nom().getChar(),"initTimeStep","initTimeStep should not have been called");
  if (dt<=0)
    throw WrongArgument(le_nom().getChar(),"initTimeStep","dt","dt should be a positive real number");
  Debog::set_nom_pb_actuel(le_nom());
  bool ok=schema_temps().initTimeStep(dt);
  domaine().set_dt(dt);
  milieu().initTimeStep(dt);
  for(int i=0; i<nombre_d_equations(); i++)
    ok = ok && equation(i).initTimeStep(dt);
// Calculs coeffs echange sur l'instant sur lequel doivent agir les operateurs.
  double tps=schema_temps().temps_defaut();
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).zone_Cl_dis()->calculer_coeffs_echange(tps);
  dt_validated=false;
  dt_defined=true;
  return ok;
}
References domaine(), dt_defined, dt_validated, equation(), initialized, Equation_base::initTimeStep(), Milieu_base::initTimeStep(), Schema_Temps_base::initTimeStep(), le_nom(), milieu(), nombre_d_equations(), schema_temps(), Domaine::set_dt(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_defaut(), terminated, and Equation_base::zone_Cl_dis().
Referenced by Pb_Dilatable_base::initTimeStep(), and Schema_Implicite_Multi_TimeStep_base::iterateTimeStep().
is_dilatable()
int Probleme_base::is_dilatable () const
Definition at line 1949 of file Probleme_base.cpp.
{
  return (milieu().que_suis_je()=="Fluide_Quasi_Compressible" || milieu().que_suis_je()=="Fluide_Weakly_Compressible");
}
References milieu(), and Objet_U::que_suis_je().
Referenced by DP_Impose_PolyMAC_Face::ajouter_blocs(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Mod_turb_hyd_base::discretiser_visc_turb(), Discretisation_base::get_name_of_type_for(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), and Op_VEF_Face::modifier_flux().
isStationary()
bool Probleme_base::isStationary () const override virtual
Tells if the Problem unknowns have changed during the last time step.
Returns
bool
Signification: true=stationary, false=not stationary
Contraintes:
Reimplemented from Probleme_U.
Definition at line 306 of file Probleme_base.cpp.
{
  if (!dt_validated)
    throw WrongContext(le_nom().getChar(),"isStationary","validateTimeStep should have been called");
  if (terminated)
    throw WrongContext(le_nom().getChar(),"isStationary","terminate should not have been called");
  return schema_temps().isStationary();
}
References dt_validated, Schema_Temps_base::isStationary(), le_nom(), schema_temps(), and terminated.
iterateTimeStep()
bool Probleme_base::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
Returns
bool
Signification: true=OK, false=unable to converge
Contraintes:
Reimplemented from Probleme_U.
Reimplemented in Pb_Dilatable_base.
Definition at line 159 of file Probleme_base.cpp.
{
  if (!dt_defined)
    throw WrongContext(le_nom().getChar(),"iterateTimeStep","initTimeStep should have been called");
  Debog::set_nom_pb_actuel(le_nom());
  bool ok=schema_temps().iterateTimeStep(converged);
// Calculs coeffs echange sur l'instant sur lequel doivent agir les operateurs.
  double tps=schema_temps().temps_defaut();
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).zone_Cl_dis()->calculer_coeffs_echange(tps);
  return ok;
}
References dt_defined, equation(), Schema_Temps_base::iterateTimeStep(), le_nom(), nombre_d_equations(), schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_defaut(), and Equation_base::zone_Cl_dis().
le_nom()
const Nom & Probleme_base::le_nom () const inline override virtual
surcharge Objet_U::le_nom()
Renvoie le nom du probleme
Returns
Nom&
Signification: le nom du probleme
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 288 of file Probleme_base.h.
{
  return nom;
}
References Probleme_U::nom.
Referenced by abortTimeStep(), addInputField(), Equation_base::associer_pb_base(), Loi_Fermeture_base::associer_pb_base(), associer_sch_tps_base(), calculer_pas_de_temps(), paroi_contact::complement(), paroi_contact_fictif::complement(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Transformation::completer(), Fluide_Quasi_Compressible::completer_edo(), computeTimeStep(), Convection_Diffusion_Concentration::constituant(), Operateur_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Postraitement::creer_champ_post_moreqn(), Operateur_base::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), discretiser(), Pb_Multiphase::discretiser(), Pb_Fluide_base::expression_predefini(), Equation_base::expression_residu(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), findInputField(), finir(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Energie_Multiphase::fluide(), Masse_Multiphase::fluide(), futureTime(), get_champ(), getInputFieldsNames(), Equation_base::Gradient_conjugue_diff_impl(), Navier_Stokes_std::impr(), Schema_Temps_base::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Echange_contact_PolyMAC::init_op(), Echange_contact_PolyMAC_P0::init_op(), initialize(), initTimeStep(), Discretiser::interpreter(), Schema_Temps_base::isStationary(), isStationary(), iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), SETS::iterer_eqn(), Simple::iterer_eqs(), Postraitement_lata::lire_champs(), Postraitement::lire_champs_operateurs(), Mod_turb_hyd_base::lire_motcle_non_standard(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Navier_Stokes_std::milieu(), nom_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), postraiter(), Postraitement_lata::postraiter_liste_champs(), presentTime(), Postraitement::readOn(), readOn(), Zone_Cl_dis_base::readOn(), Champ_Fonc_reprise::readOn(), reprendre(), sauvegarder(), sauver(), sauver_xyz(), schema_temps(), Postraitement::set_expression_champ(), Operateur_base::set_fichier(), Source_base::set_fichier(), Conduction::solide(), solveTimeStep(), Terme_Source_Canal_perio::source(), Schema_Temps_base::stop(), terminate(), updateGivenFields(), validateTimeStep(), and Postraitement::verifie_nom_et_sources().
limpr()
int Probleme_base::limpr () const override virtual
Demande au schema en temps s'il faut faire une impression.
Returns
int
Signification: 1 il faut faire une impression, 0 il ne faut pas.
Contraintes:
Reimplemented from Probleme_U.
Definition at line 1243 of file Probleme_base.cpp.
{
  return schema_temps().limpr();
}
References Schema_Temps_base::limpr(), and schema_temps().
lire_equations()
Entree & Probleme_base::lire_equations (Entree & is, Motcle & dernier_mot) virtual
Lecture des equations du probleme.
Reimplemented in Pb_Multiphase.
Definition at line 730 of file Probleme_base.cpp.
{
  Nom un_nom;
  int nb_eq= nombre_d_equations();
  Cerr << "Reading of the equations" << finl;
  for(int i=0; i<nb_eq; i++)
    {
      is >> un_nom ;
      is >> getset_equation_by_name(un_nom);
    }
  is >> dernier_mot;
  return is;
}
References Cerr, finl, getset_equation_by_name(), and nombre_d_equations().
Referenced by readOn().
lire_postraitement_interfaces()
void Probleme_base::lire_postraitement_interfaces (Entree & is) virtual
Definition at line 1935 of file Probleme_base.cpp.
{
  Cerr<<"The postprocessing of interfaces is only possible for"<<finl;
  Cerr<<"a problem type Pb_Front_Tracking, not a "<<que_suis_je()<<finl;
  exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
lsauv()
int Probleme_base::lsauv () const override virtual
Demande au schema en temps s'il faut faire une sauvegarde.
Returns
int
Signification: 1 il faut faire une sauvegarde, 0 il ne faut pas.
Contraintes:
Reimplemented from Probleme_U.
Definition at line 1262 of file Probleme_base.cpp.
{
  return schema_temps().lsauv();
}
References Schema_Temps_base::lsauv(), and schema_temps().
mettre_a_jour()
void Probleme_base::mettre_a_jour (double temps) virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Reimplemented in Pb_Dilatable_base, and Pb_Multiphase.
Definition at line 1834 of file Probleme_base.cpp.
{
// Update the name of the problem being debugged
  Debog::set_nom_pb_actuel(le_nom());
// Update the equations:
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).mettre_a_jour(temps);
// Update the media:
  milieu().mettre_a_jour(temps);
// Update the conserved fields in the equations (must be done after the media):
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).mettre_a_jour_champs_conserves(temps);
// Update the post-processing:
  les_postraitements.mettre_a_jour(temps);
// Update the domain:
  domaine().mettre_a_jour(temps,domaine_dis(),*this);
  LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.mettre_a_jour(temps);
      ++curseur;
    }
}
References domaine(), domaine_dis(), equation(), le_nom(), les_postraitements, LIST_CURSEUR, liste_loi_fermeture_, Equation_base::mettre_a_jour(), Loi_Fermeture_base::mettre_a_jour(), Milieu_base::mettre_a_jour(), Postraitements::mettre_a_jour(), Domaine::mettre_a_jour(), Equation_base::mettre_a_jour_champs_conserves(), milieu(), nombre_d_equations(), REF, and Debog::set_nom_pb_actuel().
Referenced by Simple::iterer_eqn(), Pb_Multiphase::mettre_a_jour(), and Schema_Temps_base::validateTimeStep().
milieu() [1/2]
Milieu_base & Probleme_base::milieu () virtual
Renvoie le milieu physique associe au probleme.
On renvoie le milieu associe a la premiere equation.
Returns
Milieu_base&
Signification: un milieu physique
Contraintes:
Definition at line 1504 of file Probleme_base.cpp.
{
  return equation(0).milieu();
}
References equation(), and Equation_base::milieu().
milieu() [2/2]
const Milieu_base & Probleme_base::milieu () const virtual
Renvoie le milieu physique associe au probleme.
(version const)
On renvoie le milieu associe a la premiere equation.
Returns
Milieu_base&
Signification: un milieu physique
Contraintes: reference constante
Definition at line 1484 of file Probleme_base.cpp.
{
  return equation(0).milieu();
}
References equation(), and Equation_base::milieu().
Referenced by abortTimeStep(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), Source_Darcy_VDF_Face::associer_pb(), Terme_Gravite_VDF_Face::associer_pb(), Source_Darcy_VEF_Face::associer_pb(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Echange_interne_impose::completer(), creer_champ(), get_noms_champs_postraitables(), initTimeStep(), is_dilatable(), Cond_lim_utilisateur_base::is_pb_rayo(), Pb_Multiphase::lire_equations(), mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), preparer_calcul(), Pb_Dilatable_base::preparer_calcul(), and Frottement_interfacial_Tomiyama::readOn().
nombre_d_equations()
virtual int Probleme_base::nombre_d_equations () const pure virtual
Implemented in Pb_MED, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, and Pb_Conduction.
Referenced by Schema_Temps_base::abortTimeStep(), associer(), Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), associer_milieu_base(), Schema_Adams_Bashforth_base::associer_pb(), Schema_Adams_Moulton_base::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Terme_Source_inc_th_VDF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Terme_Source_Th_TdivU_VEF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), associer_sch_tps_base(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), calculer_pas_de_temps(), completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Post_Operateur_Eqn::completer(), Chimie::completer(), creer_champ(), discretiser(), equation(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_pb_couple(), get_champ(), get_noms_champs_postraitables(), ICoCo::ProblemTrio::getDirectAccessToUnknown(), has_champ(), Implicite_Multi_TimeStep_recommencer_pb(), imprimer(), Schema_Implicite_Multi_TimeStep_base::Initialiser_Champs(), Schema_Temps_base::initialize(), initTimeStep(), Schema_Temps_base::iterateTimeStep(), iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), Multi_Sch_ThHyd::iterateTimeStep(), Sch_CN_iteratif::iterateTimeStep(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Postraitement::lire_champs_a_postraiter(), lire_equations(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), Sch_CN_EX_iteratif::mettre_a_jour_dt_stab(), postraiter(), preparer_calcul(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), printOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), reprendre(), sauvegarder(), Navier_Stokes_Fluide_Dilatable_Proto::solve_pressure_increment(), solveTimeStep(), Schema_Implicite_Multi_TimeStep_base::test_stationnaire(), Schema_Temps_base::update_critere_statio(), updateGivenFields(), and Schema_Temps_base::validateTimeStep().
nommer()
void Probleme_base::nommer (const Nom & name) inline override virtual
surcharge Objet_U::nommer(const Nom&)
Donne un nom au probleme
Reimplemented from Objet_U.
Definition at line 268 of file Probleme_base.h.
{
  nom=name;
}
References Probleme_U::nom.
Referenced by Pbc_MED::readOn().
postraitements() [1/2]
Postraitements & Probleme_base::postraitements () inline
Definition at line 166 of file Probleme_base.h.
  {
    return les_postraitements;
  };
References les_postraitements.
Referenced by comprend_champ_post(), Equation_base::ecrire_fichier_xyz(), Moyenne_volumique::get_champ(), get_champ_post(), getOutputFieldsNames(), Mod_turb_hyd_base::preparer_calcul(), and verifie_tdeb_tfin().
postraitements() [2/2]
const Postraitements & Probleme_base::postraitements () const inline
Definition at line 170 of file Probleme_base.h.
  {
    return les_postraitements;
  };
References les_postraitements.
postraiter()
int Probleme_base::postraiter (int force = 1) override virtual
Si force=1, effectue le postraitement sans tenir compte des
frequences de postraitement.
Le postraitement est mis a jour et les traitements eventuels sur
les sondes, champs et statistiques sont effectues.
Si force=0, tient compte des frequences d'impression demandees.
Reimplemented from Probleme_U.
Definition at line 248 of file Probleme_base.cpp.
{
  statistiques().begin_count(postraitement_counter_);
  Schema_Temps_base& sch = schema_temps();
  Debog::set_nom_pb_actuel(le_nom());
  if (sch.nb_pas_dt()!=0)
    imprimer(Cout);
  if (force)
    {
// Les sources postraitables (Terme_Source_Acceleration) ne sont pas mis a jour
// pour le temps final et ne font pas partie des champs_crees_ du postraitement
// qui eux sont mis a jour par les_postraitements.mettre_a_jour.
// On les met donc a jour ici
      const int nb_pas_dt_max = sch.nb_pas_dt_max();
      int& indice_nb_pas_dt = sch.set_indice_nb_pas_dt_max_atteint();
      int& indice_tps_final = sch.set_indice_tps_final_atteint();
      const double t_init = sch.temps_init();
      const double t_max = sch.temps_max();
// Test pour eviter de repeter le postraitement a l instant initial
// Cela evite un plantage dans le cas d un postraitement au format meshtv
      if (!((indice_nb_pas_dt) && (nb_pas_dt_max==0))
          && (!((indice_tps_final) && (est_egal(t_init,t_max)))))
        {
          for (int i=0; i<nombre_d_equations(); i++)
            equation(i).sources().mettre_a_jour(schema_temps().temps_courant());
          les_postraitements.mettre_a_jour(schema_temps().temps_courant());
          les_postraitements.postraiter();
          if (nb_pas_dt_max==0) indice_nb_pas_dt=1;
          if (est_egal(t_init,t_max)) indice_tps_final = 1;
        }
    }
  else
    {
      les_postraitements.traiter_postraitement();
    }
  statistiques().end_count(postraitement_counter_);
  return 1;
}
References Statistiques::begin_count(), Cout, Statistiques::end_count(), equation(), est_egal(), imprimer(), le_nom(), les_postraitements, Postraitements::mettre_a_jour(), Sources::mettre_a_jour(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), nombre_d_equations(), postraitement_counter_, Postraitements::postraiter(), schema_temps(), Schema_Temps_base::set_indice_nb_pas_dt_max_atteint(), Schema_Temps_base::set_indice_tps_final_atteint(), Debog::set_nom_pb_actuel(), Equation_base::sources(), statistiques(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), Schema_Temps_base::temps_max(), and Postraitements::traiter_postraitement().
Referenced by Schema_Temps_base::corriger_dt_calcule(), Equation_base::Gradient_conjugue_diff_impl(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
postraiter_interfaces()
void Probleme_base::postraiter_interfaces (const Nom & nom_fich, Sortie & s, const Nom & format, double temps) virtual
Definition at line 1942 of file Probleme_base.cpp.
{
  Cerr<<que_suis_je()<<" must overloaded :postraiter_interfaces"<<finl;
// exit();
}
References Cerr, finl, and Objet_U::que_suis_je().
preparer_calcul()
void Probleme_base::preparer_calcul (void) virtual
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
Reimplemented in Pb_Dilatable_base, and Pb_Multiphase.
Definition at line 1882 of file Probleme_base.cpp.
{
  const double temps = schema_temps().temps_courant();
// Modification du tableau Qdm porte par la zone_dis() dans le cas
// ou il y a des conditions aux limites periodiques.
// Rq : Si l'une des equations porte la condition a la limite periodique
// alors les autres doivent forcement la porter.
  equation(0).zone_dis()->modifier_pour_Cl(equation(0).zone_Cl_dis().les_conditions_limites());
  milieu().initialiser(temps);
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).preparer_calcul();
  milieu().preparer_calcul();
  for(int i=0; i<nombre_d_equations(); i++) /* on peut maintenant remplir les champs conserves */
    equation(i).mettre_a_jour_champs_conserves(temps);
  if(schema_temps().file_allocation() && EcritureLectureSpecial::Active)
    file_size_xyz();
  LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.preparer_calcul();
      ++curseur;
    }
}
References EcritureLectureSpecial::Active, equation(), Schema_Temps_base::file_allocation(), file_size_xyz(), Milieu_base::initialiser(), LIST_CURSEUR, liste_loi_fermeture_, Equation_base::mettre_a_jour_champs_conserves(), milieu(), nombre_d_equations(), Equation_base::preparer_calcul(), Loi_Fermeture_base::preparer_calcul(), Milieu_base::preparer_calcul(), REF, schema_temps(), Schema_Temps_base::temps_courant(), and Equation_base::zone_dis().
Referenced by initialize(), Pb_Dilatable_base::preparer_calcul(), and Pb_Multiphase::preparer_calcul().
presentTime()
double Probleme_base::presentTime () const override virtual
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
Returns
double
Signification: present time
Contraintes:
Reimplemented from Probleme_U.
Definition at line 102 of file Probleme_base.cpp.
{
  if (!initialized)
    throw WrongContext(le_nom().getChar(),"presentTime","initialize should have been called");
  if (terminated)
    throw WrongContext(le_nom().getChar(),"presentTime","terminate should not have been called");
  Debog::set_nom_pb_actuel(le_nom());
  return schema_temps().temps_courant();
}
References initialized, le_nom(), schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_courant(), and terminated.
Referenced by Ch_front_input::getTemplate(), Ch_front_input_uniforme::getTemplate(), Champ_input_P0::getTemplate(), Ch_input_uniforme::getTemplate(), and Ch_front_input_P1::getTemplate().
printOn()
Sortie & Probleme_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Pb_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_HEM, and Pb_Conduction.
Definition at line 392 of file Probleme_base.cpp.
{
  for(int i=0; i<nombre_d_equations(); i++)
    os << equation(i).que_suis_je() << " " << equation(i) << finl;
  os << les_postraitements;
  os << le_domaine_dis;
  return os;
}
References equation(), finl, le_domaine_dis, les_postraitements, nombre_d_equations(), and Objet_U::que_suis_je().
Referenced by Pb_Hydraulique_Melange_Binaire_QC::printOn(), Pb_Thermohydraulique_QC::printOn(), Pb_Hydraulique_Melange_Binaire_WC::printOn(), Pb_Thermohydraulique_WC::printOn(), and Pb_Fluide_base::printOn().
readOn()
Entree & Probleme_base::readOn (Entree & is) override protected virtual
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Returns
Entree&
Signification: le flot d'entre modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Pb_MED, Pb_Dilatable_base, Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_WC_base, Pb_Fluide_base, Pb_Hydraulique, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, Pb_Thermohydraulique_Concentration_Scalaires_Passifs, Pb_Hydraulique_Concentration_Scalaires_Passifs, Pb_Thermohydraulique_Scalaires_Passifs, Pb_Conduction_Scalaires_Passifs, Pb_Multiphase, Pb_HEM, and Pb_Conduction.
Definition at line 436 of file Probleme_base.cpp.
{
  Cerr << "Reading of the problem " << le_nom() << finl;
  format_sauv="binaire";
  nom_fich=Objet_U::nom_du_cas();
// Desormais les fichiers de sauvegarde sont nommes par defaut nomducas_nomdupb.sauv
  nom_fich+="_";
  nom_fich+=le_nom();
  nom_fich+= ".sauv";
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "We expected { to start to read the problem" << finl;
      exit();
    }
  lire_equations(is, motlu); //"motlu" contient le premier mot apres la lecture des equations
// Si le postraitement comprend le mot, on en lit un autre...
  while (les_postraitements.lire_postraitements(is, motlu, *this))
    {
      is >> motlu;
    }
  completer();
  Cerr << "Step verification of data being read in progress..." << finl;
  verifier();
  Cerr << "The read data are coherent" << finl;
  int resume_last_time = 0;
  while(1)
    {
//
// Lecture des options de reprise d'un calcul
//
      if ((motlu == "reprise") || (motlu == "resume_last_time"))
        {
          resume_last_time = (motlu == "resume_last_time" ? 1 : 0 );
// remise a defaut a zero pour pouvoir faire une reprise std apres une reprise xyz
          EcritureLectureSpecial::mode_lec=0;
          Motcle format_rep;
          is >> format_rep;
          if ((format_rep != "formatte") && (format_rep != "binaire")
              && (format_rep!="xyz") && (format_rep!="single_hdf") )
            {
              Cerr << "Restarting calculation... : keyword " << format_rep << " not understood. Waiting for:" << finl
                   << motlu << " formatte|binaire|xyz|single_hdf Filename" << finl;
              exit();
            }
// Read the filename:
          Nom nomfic;
          is >> nomfic;
// Force reprise hdf au dela d'un certain nombre de rangs MPI:
          if (format_rep!="xyz" && Process::force_single_file(Process::nproc(), nomfic)) format_rep = "single_hdf";
// Open the file:
          DERIV(Entree_Fichier_base) fic;
#ifdef MPI_
          Entree_Brute input_data;
          FichierHDFPar fic_hdf; //FichierHDF fic_hdf;
#endif
          if (format_rep == "formatte")
            fic.typer("LecFicDistribue");
          else if (format_rep == "binaire")
            fic.typer("LecFicDistribueBin");
          else if (format_rep == "xyz")
            {
              EcritureLectureSpecial::mode_lec=1;
              fic.typer(EcritureLectureSpecial::Input);
            }
          if( format_rep == "single_hdf")
            {
#ifdef MPI_
              LecFicDiffuse test;
              if (!test.ouvrir(nomfic))
                {
                  Cerr << "Error! " << nomfic << " file not found ! " << finl;
                  Process::exit();
                }
              fic_hdf.open(nomfic, true);
              fic_hdf.read_dataset("/sauv", Process::me(),input_data);
#endif
            }
          else
            {
              fic->ouvrir(nomfic);
              if(fic->fail())
                {
                  Cerr<<"Error during the opening of the restart file : " <<nomfic<<finl;
                  exit();
                }
            }
// Restart from the last time
          if (resume_last_time)
            {
// Resume_last_time is supported with xyz format
// if (format_rep == "xyz")
// {
// Cerr << "Resume_last_time is not supported with xyz format yet." << finl;
// exit();
// }
// Look for the last time and set it to tinit if tinit not set
              double last_time = -1.;
              if(format_rep == "single_hdf")
                {
#ifdef MPI_
                  last_time = get_last_time(input_data);
#endif
                }
              else
                last_time = get_last_time(fic);
// Set the time to restart the calculation
              schema_temps().set_temps_courant()=last_time;
// Initialize tinit and current time according last_time
              if (schema_temps().temps_init()>-DMAXFLOAT)
                {
                  Cerr<<"tinit was defined in .data file to "<< schema_temps().temps_init()<< ". The value is fixed to "<<last_time<<" accroding to resume_last_time_option" <<finl;
                }
              schema_temps().set_temps_init()=last_time;
              schema_temps().set_temps_precedent()=last_time;
              Cerr << "==================================================================================================" << finl;
              Cerr << "In the " << nomfic << " file, we find the last time: " << last_time << " and read the fields." << finl;
              if( format_rep != "single_hdf")
                {
                  fic->close();
                  fic->ouvrir(nomfic);
                }
              else
                {
#ifdef MPI_
                  fic_hdf.read_dataset("/sauv", Process::me(), input_data);
#endif
                }
            }
// Lecture de la version du format de sauvegarde si c'est une reprise classique
// Depuis la 1.5.1, on marque le format de sauvegarde en tete des fichiers de sauvegarde
// afin de pouvoir faire evoluer plus facilement ce format dans le futur
// En outre avec la 1.5.1, les faces etant numerotees differemment, il est faux
// de faire une reprise d'un fichier de sauvegarde anterieur et c'est donc un moyen
// de prevenir les utilisateurs: il leur faudra faire une reprise xyz pour poursuivre
// avec la 1.5.1 un calcul lance avec une version anterieure
// Depuis la 1.5.5, Il y a pas une version de format pour le xyz
          if(format_rep != "single_hdf")
            fic.valeur() >> motlu;
          else
            {
#ifdef MPI_
              input_data >> motlu;
#endif
            }
          if (motlu!="FORMAT_SAUVEGARDE:")
            {
              if (format_rep == "xyz")
                {
// We close and re-open the file:
                  fic->close();
                  fic->ouvrir(nomfic);
                  reprise_version_ = 151;
                }
              else
                {
                  Cerr << "-------------------------------------------------------------------------------------" << finl;
                  Cerr << "The resumption file " << nomfic << " can not be read by this version of TRUST" << finl;
                  Cerr << "which is a later version than 1.5. Indeed, the numbering of the faces have changed" << finl;
                  Cerr << "and it would produce an erroneous resumption. If you want to use this version," << finl;
                  Cerr << "you must do a resumption of the file .xyz saved during the previous calculation" << finl;
                  Cerr << "because this file is independent of the numbering of the faces." << finl;
                  Cerr << "The next backup will be made in a format compatible with the new" << finl;
                  Cerr << "numbering of the faces and you can then redo classical resumptions." << finl;
                  Cerr << "-------------------------------------------------------------------------------------" << finl;
                  exit();
                }
            }
          else
            {
// Lecture du format de Lsauvegarde
              if(format_rep != "single_hdf")
                fic.valeur() >> reprise_version_;
              else
                {
#ifdef MPI_
                  input_data >> reprise_version_;
#endif
                }
              if (mp_min(reprise_version_)!=mp_max(reprise_version_))
                {
                  Cerr << "The version of the format backup/resumption is not the same in the resumption files " << nomfic << finl;
                  exit();
                }
              if (reprise_version_>version_format_sauvegarde())
                {
                  Cerr << "The format " << reprise_version_ << " of the resumption file " << nomfic << " is posterior" << finl;
                  Cerr << "to the format "<<version_format_sauvegarde()<<" recognized by this version of TRUST." << finl;
                  Cerr << "Please use a more recent version." << finl;
                  exit();
                }
            }
// Ecriture du format de reprise
          Cerr << "The version of the resumption format of file " << nomfic << " is " << reprise_version_ << finl;
          if(format_rep != "single_hdf")
            reprendre(fic.valeur());
          else
            {
#ifdef MPI_
              reprendre(input_data);
              fic_hdf.close();
#endif
            }
          reprise_effectuee_=1;
        }
//
// Lecture des options de sauvegarde d'un calcul
//
      else if (motlu == "sauvegarde" || motlu == "sauvegarde_simple")
        {
// restart_file=1: le fichier est ecrasee a chaque sauvegarde (et ne donc contient qu'un seul instant)
          if (motlu == "sauvegarde_simple") restart_file=1;
          is >> format_sauv;
          if( (Motcle(format_sauv) != "binaire")
              && (Motcle(format_sauv) != "formatte")
              && (Motcle(format_sauv) != "xyz")
              && (Motcle(format_sauv) != "single_hdf") )
            {
              nom_fich=format_sauv;
              format_sauv="binaire";
            }
          else
            is >> nom_fich;
        }
      else if (motlu == accolade_fermee)
        break;
      else
        {
          Cerr << "Error in Probleme_base::lire_donnees" << finl;
          Cerr << "We expected } instead of " << motlu << " to mark the end of the data set" << finl;
          exit();
        }
      is >> motlu;
    }
  ficsauv_.detach();
// Force sauvegarde hdf au dela d'un certain nombre de rangs MPI:
  if (format_sauv!="xyz" && Process::force_single_file(Process::nproc(), nom_fich))
    format_sauv = "single_hdf";
  if ( (Motcle(format_sauv) != "binaire")
       && (Motcle(format_sauv) != "formatte")
       && (Motcle(format_sauv) != "xyz")
       && (Motcle(format_sauv) != "single_hdf") )
    {
      Cerr << "Error of backup format" << finl;
      Cerr << "We expected formatte, binaire, xyz, or single_hdf." << finl;
      exit();
    }
  if (schema_temps().temps_init()<=-DMAXFLOAT)
    {
      schema_temps().set_temps_init()=0;
      schema_temps().set_temps_courant()=0;
    }
  if (reprise_effectuee())
    {
// on teste si dt_ev existe sinon on met reprise a 2
// on recrera l'entete dans dt_ev sinon l'entete est fausse en reprise de pb_couple
      Nom fichier(nom_du_cas());
      fichier+=".dt_ev";
      struct stat f;
      if (stat(fichier,&f))
        reprise_effectuee()=2;
    }
  return is ;
}
References Cerr, FichierHDF::close(), completer(), DERIV, Deriv_::detach(), DMAXFLOAT, Process::exit(), ficsauv_, finl, Process::force_single_file(), format_sauv, get_last_time(), EcritureLectureSpecial::Input, le_nom(), les_postraitements, lire_equations(), Postraitements::lire_postraitements(), Process::me(), EcritureLectureSpecial::mode_lec, Process::mp_max(), Process::mp_min(), Objet_U::nom_du_cas(), nom_fich, Process::nproc(), FichierHDF::open(), FichierHDF::read_dataset(), reprendre(), reprise_effectuee(), reprise_effectuee_, reprise_version_, restart_file, schema_temps(), Schema_Temps_base::set_temps_courant(), Schema_Temps_base::set_temps_init(), Schema_Temps_base::set_temps_precedent(), Schema_Temps_base::temps_init(), test(), verifier(), and version_format_sauvegarde().
Referenced by Pb_MED::readOn(), Pb_Hydraulique_Melange_Binaire_QC::readOn(), Pb_Thermohydraulique_QC::readOn(), Pb_Hydraulique_Melange_Binaire_WC::readOn(), Pb_Thermohydraulique_WC::readOn(), Pb_Fluide_base::readOn(), and Pb_Conduction::readOn().
reprendre()
int Probleme_base::reprendre (Entree & is) override virtual
Lecture d'un flot d'entree (fichier) pour reprise apres
une sauvegarde avec Probleme_base::sauvegarder(Sortie& os).
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Objet_U.
Definition at line 1215 of file Probleme_base.cpp.
{
  statistiques().begin_count(temporary_counter_);
  Debog::set_nom_pb_actuel(le_nom());
  schema_temps().reprendre(is);
  Cerr << "Resuming the problem " << le_nom() << finl;
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).reprendre(is);
  les_postraitements.reprendre(is);
  statistiques().end_count(temporary_counter_);
  Cerr << "End of resuming the problem " << le_nom() << " after " << statistiques().last_time(temporary_counter_) << " s" << finl;
  return 1;
}
References Statistiques::begin_count(), Cerr, Statistiques::end_count(), equation(), finl, Statistiques::last_time(), le_nom(), les_postraitements, nombre_d_equations(), Equation_base::reprendre(), Schema_Temps_base::reprendre(), Postraitements::reprendre(), schema_temps(), Debog::set_nom_pb_actuel(), statistiques(), and temporary_counter_.
Referenced by readOn().
reprise_effectuee() [1/2]
int & Probleme_base::reprise_effectuee () inline
Definition at line 177 of file Probleme_base.h.
  {
    return reprise_effectuee_;
  };
References reprise_effectuee_.
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), Postraitement::finir(), Loi_horaire::imprimer(), Postraitement::init(), Sonde::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Operateur_base::ouvrir_fichier_partage(), ouvrir_fichier_pena_th(), readOn(), Terme_Source_Canal_perio::source(), and Terme_Source_Canal_perio::write_flow_rate().
reprise_effectuee() [2/2]
int Probleme_base::reprise_effectuee () const inline
Definition at line 181 of file Probleme_base.h.
  {
    return reprise_effectuee_;
  };
References reprise_effectuee_.
reprise_format_temps()
const char * Probleme_base::reprise_format_temps () const inline
Definition at line 328 of file Probleme_base.h.
{
  return time_format_from(reprise_version_);
}
References reprise_version_, and time_format_from().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
sauvegarder()
int Probleme_base::sauvegarder (Sortie & os) const override virtual
Ecriture du probleme sur fichier en vue d'une reprise.
Ecrit le nom du probleme et sauvegarde les equations.
Returns
int
Signification: renvoie toujours 1
Contraintes:
< To detect a sauvegarder() method which returns 1 instead of the number of bytes saved.
Reimplemented from Objet_U.
Definition at line 1184 of file Probleme_base.cpp.
{
  Debog::set_nom_pb_actuel(le_nom());
  schema_temps().sauvegarder(os);
  Cerr << "Backup of problem " << le_nom() << finl;
  int bytes=0;
  for(int i=0; i<nombre_d_equations(); i++)
    {
      bytes += equation(i).sauvegarder(os);
      assert(bytes % 4 == 0);
    }
  bytes += les_postraitements.sauvegarder(os);
  assert(bytes % 4 == 0); //!< To detect a sauvegarder() method which returns 1 instead of the number of bytes saved.
  return bytes;
}
References Cerr, equation(), finl, le_nom(), les_postraitements, nombre_d_equations(), Equation_base::sauvegarder(), Schema_Temps_base::sauvegarder(), Postraitements::sauvegarder(), schema_temps(), and Debog::set_nom_pb_actuel().
Referenced by sauver(), and sauver_xyz().
sauver()
void Probleme_base::sauver () const override virtual
Ecriture sur fichier en vue d'une reprise (sauvegarde)
Reimplemented from Probleme_U.
Definition at line 1025 of file Probleme_base.cpp.
{
  statistiques().begin_count(sauvegarde_counter_);
// Si le fichier de sauvegarde n'a pas ete ouvert alors on cree le fichier de sauvegarde:
  if ( !ficsauv_.non_nul() && !osauv_hdf_ )
    {
      if (Motcle(format_sauv) == "formatte")
        {
          ficsauv_.typer("EcrFicCollecte");
          ficsauv_->ouvrir(nom_fich);
          ficsauv_->setf(ios::scientific);
        }
      else if (Motcle(format_sauv) == "binaire")
        {
          ficsauv_.typer("EcrFicCollecteBin");
          ficsauv_->ouvrir(nom_fich);
        }
      else if (Motcle(format_sauv) == "xyz")
        {
          ficsauv_.typer(EcritureLectureSpecial::get_Output());
          ficsauv_->ouvrir(nom_fich);
        }
      else if (Motcle(format_sauv) == "single_hdf")
        osauv_hdf_ = new Sortie_Brute;
      else
        {
          Cerr << "Error in Probleme_base::sauver() " << finl;
          Cerr << "The format for the backup file must be either binary or formatted" << finl;
          Cerr << "But it is :" << format_sauv << finl;
          exit();
        }
// Si c'est la premiere sauvegarde, on note en en-tete le format de sauvegarde
      if (Motcle(format_sauv) == "xyz")
        {
          if (Process::je_suis_maitre())
            ficsauv_.valeur() << "format_sauvegarde:" << finl << version_format_sauvegarde() << finl;
        }
      else if((Motcle(format_sauv) == "single_hdf"))
        *osauv_hdf_ << "format_sauvegarde:" << finl << version_format_sauvegarde() << finl;
      else
        ficsauv_.valeur() << "format_sauvegarde:" << finl << version_format_sauvegarde() << finl;
    }
// On realise l'ecriture de la sauvegarde
  int bytes;
  EcritureLectureSpecial::mode_ecr=(Motcle(format_sauv)=="xyz");
  if(Motcle(format_sauv) != "single_hdf")
    bytes = sauvegarder(ficsauv_.valeur());
  else
    bytes = sauvegarder(*osauv_hdf_);
  EcritureLectureSpecial::mode_ecr=-1;
// Si c'est une sauvegarde simple, on referme immediatement et proprement le fichier
  if (restart_file==1)
    {
      if (Motcle(format_sauv)=="xyz")
        {
          if (Process::je_suis_maitre())
            ficsauv_.valeur() << Nom("fin");
          (ficsauv_.valeur()).flush();
          (ficsauv_.valeur()).syncfile();
        }
      else if(Motcle(format_sauv)=="single_hdf")
        {
          *osauv_hdf_ << Nom("fin");
          FichierHDFPar fic_hdf;
          fic_hdf.create(nom_fich);
          fic_hdf.create_and_fill_dataset_MW("/sauv", *osauv_hdf_);
          fic_hdf.close();
          delete osauv_hdf_;
          osauv_hdf_ = 0;
        }
      else
        {
          ficsauv_.valeur() << Nom("fin");
          (ficsauv_.valeur()).flush();
        }
      ficsauv_.detach();
    }
  Debog::set_nom_pb_actuel(le_nom());
  statistiques().end_count(sauvegarde_counter_, bytes);
  Cout << "[IO] " << statistiques().last_time(sauvegarde_counter_) << " s to write save file." << finl;
}
References Statistiques::begin_count(), Cerr, FichierHDF::close(), Cout, FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), Deriv_::detach(), Statistiques::end_count(), Process::exit(), ficsauv_, finl, format_sauv, EcritureLectureSpecial::get_Output(), Process::je_suis_maitre(), Statistiques::last_time(), le_nom(), EcritureLectureSpecial::mode_ecr, nom_fich, O_U_Ptr::non_nul(), osauv_hdf_, Sortie_Fichier_base::ouvrir(), restart_file, sauvegarde_counter_, sauvegarder(), Debog::set_nom_pb_actuel(), Sortie_Fichier_base::setf(), statistiques(), Deriv_::typer(), Deriv_Sortie_Fichier_base::valeur(), and version_format_sauvegarde().
Referenced by Schema_Temps_base::corriger_dt_calcule(), finir(), Equation_base::Gradient_conjugue_diff_impl(), and Loi_Etat_Multi_GP_WC::update_Yn_values().
sauver_xyz()
void Probleme_base::sauver_xyz (int verbose) const
Definition at line 2129 of file Probleme_base.cpp.
{
  statistiques().begin_count(sauvegarde_counter_);
  Nom nom_fich_xyz("");
  if (verbose)
    {
      nom_fich_xyz+=Objet_U::nom_du_cas();
      nom_fich_xyz+="_";
      nom_fich_xyz+=le_nom();
      nom_fich_xyz+=".xyz";
      if (Process::je_suis_maitre())
        Cerr <<"Creation of "<<nom_fich_xyz<< " (" << EcritureLectureSpecial::get_Output() << ") for resumption of a calculation with a different number of processors."<<finl;
    }
  else
    {
      nom_fich_xyz=".xyz";
    }
// Creation du fichier XYZ du probleme courant
  ficsauv_.typer(EcritureLectureSpecial::get_Output());
  ficsauv_->ouvrir(nom_fich_xyz);
// Nouveau pour le xyz depuis la 155: on note en en-tete le format de sauvegarde
  if (Process::je_suis_maitre())
    ficsauv_.valeur() << "format_sauvegarde:" << finl << version_format_sauvegarde() << finl;
  EcritureLectureSpecial::mode_ecr=1;
  int bytes = sauvegarder(ficsauv_.valeur());
  EcritureLectureSpecial::mode_ecr=-1;
  if (Process::je_suis_maitre())
    ficsauv_.valeur() << Nom("fin");
  (ficsauv_.valeur()).flush();
  (ficsauv_.valeur()).syncfile();
  ficsauv_.detach();
  Cout << "[IO] " << statistiques().last_time(sauvegarde_counter_) << " s to write xyz file." << finl;
  statistiques().end_count(sauvegarde_counter_, bytes);
}
References Statistiques::begin_count(), Cerr, Cout, Deriv_::detach(), Statistiques::end_count(), ficsauv_, finl, EcritureLectureSpecial::get_Output(), Process::je_suis_maitre(), Statistiques::last_time(), le_nom(), EcritureLectureSpecial::mode_ecr, Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), sauvegarde_counter_, sauvegarder(), statistiques(), Deriv_::typer(), Deriv_Sortie_Fichier_base::valeur(), and version_format_sauvegarde().
Referenced by allocation(), file_size_xyz(), and finir().
schema_temps() [1/2]
Schema_Temps_base & Probleme_base::schema_temps ()
Renvoie le schema en temps associe au probleme. (si il est non nul)
Returns
Schema_Temps_base&
Signification: le schema en temps associe au probleme
Contraintes:
Definition at line 1358 of file Probleme_base.cpp.
{
  if(!le_schema_en_temps.non_nul())
    {
      Cerr << le_nom() << " has not been associated to a time scheme !" << finl;
      exit();
    }
  return le_schema_en_temps.valeur();
}
References Cerr, Process::exit(), finl, le_nom(), le_schema_en_temps, O_U_Ptr::non_nul(), and Ref_Schema_Temps_base::valeur().
schema_temps() [2/2]
const Schema_Temps_base & Probleme_base::schema_temps () const
Renvoie le schema en temps associe au probleme. (si il est non nul)
(version const)
Returns
Schema_Temps_base&
Signification: le schema en temps associe au probleme
Contraintes: reference constante
Definition at line 1333 of file Probleme_base.cpp.
{
  if(!le_schema_en_temps.non_nul())
    {
      Cerr << le_nom() << " has not been associated to a time scheme !" << finl;
      exit();
    }
  return le_schema_en_temps.valeur();
}
References Cerr, Process::exit(), finl, le_nom(), le_schema_en_temps, O_U_Ptr::non_nul(), and Ref_Schema_Temps_base::valeur().
Referenced by abortTimeStep(), Force_Tchen_PolyMAC_P0::ajouter_blocs(), allocation(), Probleme_Couple::associer_sch_tps_base(), calculer_pas_de_temps(), Fluide_Dilatable_base::completer(), Op_Correlation::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice_pression(), Source_PDF_EF::compute_pond(), computeTimeStep(), Navier_Stokes_std::corriger_derivee_impl(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Quasi_Compressible::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), finir(), Source_PDF_base::fonct_coeff(), futureTime(), Pb_MED::get_champ(), Source_PDF_EF::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Schema_Temps_base::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Postraitement::init(), Loi_Etat_base::initialiser_inco_ch(), initialize(), Probleme_Couple::initialize(), initTimeStep(), Discretiser::interpreter(), isStationary(), iterateTimeStep(), Pb_Dilatable_base::iterateTimeStep(), iterer_eqn_expl_diffusion_implicite(), limpr(), Traitement_particulier_NS_EC::lire(), lsauv(), Chimie::mettre_a_jour(), Postraitement::mettre_a_jour(), Sonde::mettre_a_jour(), Fluide_Weakly_Compressible::mettre_a_jour_bis(), Operateur_base::modifier_pour_Cl(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Turbulence_paroi_base::ouvrir_fichier_partage(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Operateur_base::ouvrir_fichier_partage(), ouvrir_fichier_pena_th(), Sonde::postraiter(), postraiter(), Postraitement::postraiter(), Postraitement::postraiter_champs(), Postraitement::postraiter_sondes(), Postraitement::postraiter_tableaux(), Fluide_Quasi_Compressible::prepare_pressure_edo(), Loi_Fermeture_base::preparer_calcul(), preparer_calcul(), Loi_Etat_base::preparer_calcul(), Fluide_Dilatable_base::preparer_calcul(), Pb_Multiphase::preparer_calcul(), Fluide_Dilatable_base::preparer_pas_temps(), presentTime(), readOn(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), reprendre(), Postraitement::reprendre(), Operateurs_Statistique_tps::reprendre(), Champ_Inc_base::sauvegarder(), sauvegarder(), Postraitement::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), Probleme_Couple::schema_temps(), setStationary(), solveTimeStep(), terminate(), test_imposer_cond_lim(), Postraitement::traiter_champs(), Postraitement::traiter_sondes(), Postraitement::traiter_tableaux(), Perte_Charge_Singuliere::update_K(), validateTimeStep(), and ICoCo::ProblemTrio::validateTimeStep().
self_cast() [1/2]
const Probleme_base & Probleme_base::self_cast (const Objet_U & r) static
Definition at line 48 of file Probleme_base.cpp.
self_cast() [2/2]
Probleme_base & Probleme_base::self_cast (Objet_U & r) static
Definition at line 48 of file Probleme_base.cpp.
set_coupled()
void Probleme_base::set_coupled (int i) inline
Definition at line 206 of file Probleme_base.h.
  {
    coupled_=i;
  };
References coupled_.
Referenced by Probleme_Couple::ajouter().
setStationary()
void Probleme_base::setStationary (bool) override virtual
Tells to the Problem that stationary is reached or not.
Reimplemented from Probleme_U.
Definition at line 316 of file Probleme_base.cpp.
{
  schema_temps().set_stationnaires_atteints(flag);
}
References schema_temps(), and Schema_Temps_base::set_stationnaires_atteints().
solveTimeStep()
bool Probleme_base::solveTimeStep (void) override virtual
pour recodage eventuel et appel unifie en python
Reimplemented from Probleme_U.
Definition at line 142 of file Probleme_base.cpp.
{
  if (!dt_defined)
    throw WrongContext(le_nom().getChar(),"solveTimeStep","initTimeStep should have been called");
  Debog::set_nom_pb_actuel(le_nom());
  bool ok=Probleme_U::solveTimeStep();
// Calculs coeffs echange sur l'instant sur lequel doivent agir les operateurs.
  double tps=schema_temps().temps_defaut();
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).zone_Cl_dis()->calculer_coeffs_echange(tps);
  return ok;
}
References dt_defined, equation(), le_nom(), nombre_d_equations(), schema_temps(), Debog::set_nom_pb_actuel(), Probleme_U::solveTimeStep(), Schema_Temps_base::temps_defaut(), and Equation_base::zone_Cl_dis().
terminate()
void Probleme_base::terminate () override virtual
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Reimplemented from Probleme_U.
Definition at line 197 of file Probleme_base.cpp.
{
  if (!initialized)
    throw WrongContext(le_nom().getChar(),"terminate","initialize should have been called");
  if (terminated)
    throw WrongContext(le_nom().getChar(),"terminate","terminate should not have been called");
  if (dt_defined)
    throw WrongContext(le_nom().getChar(),"terminate","time step should be validated or aborted first");
  Debog::set_nom_pb_actuel(le_nom());
  finir();
  schema_temps().terminate();
  terminated=true;
}
References dt_defined, finir(), initialized, le_nom(), schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::terminate(), and terminated.
updateGivenFields()
bool Probleme_base::updateGivenFields () override virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
true=OK, false=error
Signification:
Contraintes:
Reimplemented from Probleme_U.
Definition at line 175 of file Probleme_base.cpp.
{
  Debog::set_nom_pb_actuel(le_nom());
  bool ok=true;
  for(int i=0; i<nombre_d_equations(); i++)
    ok = ok && equation(i).updateGivenFields();
  return ok;
}
References equation(), le_nom(), nombre_d_equations(), Debog::set_nom_pb_actuel(), and Equation_base::updateGivenFields().
Referenced by Schema_Implicite_Multi_TimeStep_base::iterateTimeStep().
validateTimeStep()
void Probleme_base::validateTimeStep () override virtual
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
Reimplemented from Probleme_U.
Definition at line 184 of file Probleme_base.cpp.
{
  if (!dt_defined)
    throw WrongContext(le_nom().getChar(),"validateTimeStep","initTimeStep should have been called");
  Debog::set_nom_pb_actuel(le_nom());
  schema_temps().validateTimeStep();
  allocation();
  dt_defined=false;
  dt_validated=true;
}
References allocation(), dt_defined, dt_validated, le_nom(), schema_temps(), Debog::set_nom_pb_actuel(), and Schema_Temps_base::validateTimeStep().
verifie_tdeb_tfin()
int Probleme_base::verifie_tdeb_tfin (const Motcle & nom) const virtual
On verifie que le temps de debut et de fin des statistiques est identique sur tous les champsde tous les postraitements.
Definition at line 1752 of file Probleme_base.cpp.
{
  CONST_LIST_CURSEUR(DERIV(Postraitement_base)) curseur_post = postraitements();
  while (curseur_post)
    {
      const Postraitement& post = ref_cast(Postraitement,curseur_post.valeur().valeur());
      if (tstat_deb_==-1)
        tstat_deb_ = post.tstat_deb();
      else if (!est_egal(tstat_deb_,post.tstat_deb()) && post.tstat_deb()!=-1)
        {
// Cerr << finl;
// Cerr << "Error in " << un_nom << finl;
// Cerr << "Your beginning time of statistics t_deb=" << post.tstat_deb() << " must be equal" << finl;
// Cerr << "to the previous beginning time already read t_deb=" << tstat_deb_ << finl;
          Cerr << "Beginning times of statistics t_deb are differents but the calculation continues" << finl;
// exit();
        }
      if (tstat_fin_==-1)
        tstat_fin_ = post.tstat_fin();
      else if (!est_egal(tstat_fin_,post.tstat_fin()) && post.tstat_fin()!=-1)
        {
// Cerr << finl;
// Cerr << "Error in " << un_nom << finl;
// Cerr << "Your ending time of statistics t_fin=" << post.tstat_fin() << " must be equal" << finl;
// Cerr << "to the previous ending time already read t_fin=" << tstat_fin_ << finl;
          Cerr << "Ending times of statistics t_fin are differents but the calculation continues" << finl;
// exit();
        }
      ++curseur_post;
    }
  return 1;
}
References Cerr, CONST_LIST_CURSEUR, DERIV, est_egal(), finl, postraitements(), ref_cast, Postraitement::tstat_deb(), tstat_deb_, Postraitement::tstat_fin(), and tstat_fin_.
Referenced by Postraitement::cherche_stat_dans_les_sources(), and Postraitement::lire_champs_stat_a_postraiter().
verifier()
int Probleme_base::verifier () virtual
Verifie que l'objet est complet, coherent, ...
NON DEVELOPPE RENVOIE TOUJOURS 1.
Returns
int
Signification: 1 si l'objet est correct
Contraintes:
Reimplemented in Pb_Hydraulique_Melange_Binaire_QC, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, Pb_Hydraulique_Concentration, Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, and Pb_Multiphase.
Definition at line 867 of file Probleme_base.cpp.
{
  return 1;
}
Referenced by readOn().
Member Data Documentation
bad_allocate
int Probleme_base::bad_allocate =1 static protected
1 si allocation reussi, 0 sinon
bad_allocate est un int qui permet de savoir si l'allocation a deja eut lieu
Definition at line 243 of file Probleme_base.h.
Referenced by allocation().
coupled_
int Probleme_base::coupled_ protected
Flag to indicate it is a part of a coupled problem.
Definition at line 247 of file Probleme_base.h.
Referenced by Pb_Dilatable_base::associer_sch_tps_base(), get_coupled(), and set_coupled().
dt_defined
bool Probleme_base::dt_defined protected
true if computation interval is defined set to true by initTimeStep, to false by validateTimeStep & abortTimeStep
Definition at line 235 of file Probleme_base.h.
Referenced by abortTimeStep(), futureTime(), initTimeStep(), iterateTimeStep(), solveTimeStep(), terminate(), and validateTimeStep().
dt_validated
bool Probleme_base::dt_validated protected
true if last computation was validated set to true by validateTimeStep, to false by initTimeStep
Definition at line 237 of file Probleme_base.h.
Referenced by initTimeStep(), isStationary(), and validateTimeStep().
error
Nom Probleme_base::error mutable protected
Erreur d'allocation.
Definition at line 246 of file Probleme_base.h.
Referenced by allocate_file_size(), and allocation().
ficsauv_
Deriv_Sortie_Fichier_base Probleme_base::ficsauv_ mutable protected
Definition at line 223 of file Probleme_base.h.
Referenced by finir(), readOn(), sauver(), and sauver_xyz().
file_size
long int Probleme_base::file_size =0 static protected
Espace disque pris par les sauvegarde XYZ.
Initialisation de file_size, bad_allocate, nb_pb_total, num_pb.
file_size est l'espace disque en octet necessaire pour ecrire les fichiers XYZ
Definition at line 242 of file Probleme_base.h.
Referenced by allocation(), and file_size_xyz().
format_sauv
Nom Probleme_base::format_sauv protected
Definition at line 229 of file Probleme_base.h.
Referenced by finir(), readOn(), and sauver().
info_obj
const Type_info Probleme_base::info_obj static
Definition at line 64 of file Probleme_base.h.
initialized
bool Probleme_base::initialized protected
true if initialize was called
Definition at line 233 of file Probleme_base.h.
Referenced by computeTimeStep(), initialize(), initTimeStep(), presentTime(), and terminate().
input_fields
List_Ref_Field_base Probleme_base::input_fields protected
List of input fields inside this problem.
Definition at line 221 of file Probleme_base.h.
Referenced by addInputField(), findInputField(), and getInputFieldsNames().
la_discretisation
Ref_Discretisation_base Probleme_base::la_discretisation protected
Definition at line 220 of file Probleme_base.h.
Referenced by discretisation(), discretiser(), and Pb_MED::readOn().
le_domaine_dis
Domaine_dis Probleme_base::le_domaine_dis protected
Definition at line 217 of file Probleme_base.h.
Referenced by associer_domaine(), discretiser(), domaine(), domaine_dis(), printOn(), and Pb_MED::readOn().
le_schema_en_temps
Ref_Schema_Temps_base Probleme_base::le_schema_en_temps protected
Definition at line 219 of file Probleme_base.h.
Referenced by associer_sch_tps_base(), Pb_Multiphase::lire_equations(), and schema_temps().
les_postraitements
Postraitements Probleme_base::les_postraitements protected
Definition at line 218 of file Probleme_base.h.
Referenced by completer(), finir(), init_postraitements(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), postraitements(), postraiter(), printOn(), readOn(), reprendre(), and sauvegarder().
liste_loi_fermeture_
List_Ref_Loi_Fermeture_base Probleme_base::liste_loi_fermeture_ protected
liste des fermetures associees au probleme
Definition at line 249 of file Probleme_base.h.
Referenced by associer_(), completer(), creer_champ(), discretiser(), get_champ(), get_noms_champs_postraitables(), has_champ(), mettre_a_jour(), Pb_Dilatable_base::mettre_a_jour(), and preparer_calcul().
nb_pb_total
int Probleme_base::nb_pb_total =0 static protected
Nombre total de probleme.
nb_pb_total est le nombre total de probleme
Definition at line 244 of file Probleme_base.h.
Referenced by allocation(), and file_size_xyz().
nom_fich
Nom Probleme_base::nom_fich protected
Definition at line 228 of file Probleme_base.h.
Referenced by finir(), readOn(), and sauver().
num_pb
int Probleme_base::num_pb =1 static protected
numero du probleme
num_pb est le numero du probleme courant
Definition at line 245 of file Probleme_base.h.
Referenced by allocation().
osauv_hdf_
Sortie_Brute* Probleme_base::osauv_hdf_ mutable protected
Definition at line 224 of file Probleme_base.h.
Referenced by finir(), and sauver().
reprise_effectuee_
int Probleme_base::reprise_effectuee_ protected
Definition at line 226 of file Probleme_base.h.
Referenced by readOn(), and reprise_effectuee().
reprise_version_
int Probleme_base::reprise_version_ protected
Definition at line 227 of file Probleme_base.h.
Referenced by readOn(), and reprise_format_temps().
restart_file
int Probleme_base::restart_file protected
Definition at line 230 of file Probleme_base.h.
Referenced by finir(), readOn(), and sauver().
terminated
bool Probleme_base::terminated protected
true if terminate was called
Definition at line 234 of file Probleme_base.h.
Referenced by computeTimeStep(), initTimeStep(), isStationary(), presentTime(), and terminate().
tstat_deb_
double Probleme_base::tstat_deb_ mutable protected
Definition at line 240 of file Probleme_base.h.
Referenced by Probleme_base(), and verifie_tdeb_tfin().
tstat_fin_
double Probleme_base::tstat_fin_ protected
Definition at line 240 of file Probleme_base.h.
Referenced by Probleme_base(), and verifie_tdeb_tfin().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Probleme_base.h
src/Kernel/Framework/Probleme_base.cpp