TRUST: Zone_Cl_dis Class Reference
Zone_Cl_dis Class Reference
classe Zone_Cl_dis
Classe generique de la hierarchie des conditions aux limites
discretisees. Un objet Zone_Cl_dis peut referencer n'importe quel
derivant de Zone_Cl_dis_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Zone_Cl_dis.h>
Public Member Functions
Zone_Cl_dis ()
~Zone_Cl_dis ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_eqn (const Equation_base &)
Appel a l'objet sous-jacent.
Associe l'equation dont l'objet represente les conditions aux limites.
void imposer_cond_lim (Champ_Inc &, double)
Appel a l'objet sous-jacent.
Impose les conditions aux limites a un temps donne du Champ_Inc.
void mettre_a_jour (double temps)
Appel a l'objet sous-jacent
Effectue une mise a jour en temps des conditions aux limites.
const Cond_lim & les_conditions_limites (int) const
Appel a l'objet sous-jacent
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Appel a l'objet sous-jacent
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Appel a l'objet sous-jacent
Renvoie le tableau des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Appel a l'objet sous-jacent
Renvoie le tableau des conditions aux limites.
(version const)
int nb_cond_lim () const
Appel a l'objet sous-jacent
Renvoie le nombre de conditions aux limites.
Zone & zone ()
const Zone & zone () const
int nb_faces_Cl () const
Public Member Functions inherited from Deriv_Zone_Cl_dis_base
~Deriv_Zone_Cl_dis_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Zone_Cl_dis_base ()
Deriv_Zone_Cl_dis_base (const Deriv_Zone_Cl_dis_base &)
const Zone_Cl_dis_base & valeur () const
Zone_Cl_dis_base & valeur ()
const Zone_Cl_dis_base * operator-> () const
Zone_Cl_dis_base * operator-> ()
const Deriv_Zone_Cl_dis_base & operator= (const Zone_Cl_dis_base &)
const Deriv_Zone_Cl_dis_base & operator= (const Deriv_Zone_Cl_dis_base &)
operator const Zone_Cl_dis_base & () const
operator Zone_Cl_dis_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_dis & self_cast (Objet_U &)
static const Zone_Cl_dis & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Zone_Cl_dis_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Zone_Cl_dis_base & self_cast (Objet_U &)
static const Deriv_Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Zone_Cl_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Deriv_Zone_Cl_dis_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Zone_Cl_dis
Classe generique de la hierarchie des conditions aux limites
discretisees. Un objet Zone_Cl_dis peut referencer n'importe quel
derivant de Zone_Cl_dis_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 41 of file Zone_Cl_dis.h.
Constructor & Destructor Documentation
Zone_Cl_dis()
Zone_Cl_dis::Zone_Cl_dis ()
Definition at line 19 of file Zone_Cl_dis.cpp.
~Zone_Cl_dis()
Zone_Cl_dis::~Zone_Cl_dis ()
Definition at line 19 of file Zone_Cl_dis.cpp.
Member Function Documentation
associer_eqn()
void Zone_Cl_dis::associer_eqn (const Equation_base & equation) inline
Appel a l'objet sous-jacent.
Associe l'equation dont l'objet represente les conditions aux limites.
Definition at line 79 of file Zone_Cl_dis.h.
{
  valeur().associer_eqn(equation);
}
References MorEqn::associer_eqn(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by Equation_base::discretiser().
cree_instance()
Objet_U * Zone_Cl_dis::cree_instance () static
Definition at line 19 of file Zone_Cl_dis.cpp.
duplique()
int Zone_Cl_dis::duplique () const override virtual
Reimplemented from Deriv_Zone_Cl_dis_base.
Definition at line 19 of file Zone_Cl_dis.cpp.
get_info()
const Type_info * Zone_Cl_dis::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Zone_Cl_dis_base.
Definition at line 19 of file Zone_Cl_dis.cpp.
imposer_cond_lim()
void Zone_Cl_dis::imposer_cond_lim (Champ_Inc & ch, double temps) inline
Appel a l'objet sous-jacent.
Impose les conditions aux limites a un temps donne du Champ_Inc.
Definition at line 101 of file Zone_Cl_dis.h.
{
  valeur().imposer_cond_lim(ch,temps);
}
References Zone_Cl_dis_base::imposer_cond_lim(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Schema_Implicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), TRUSTSchema_RK< _ORDRE_ >::faire_un_pas_de_temps_eqn_base_generique(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqs(), Schema_Implicite_Multi_TimeStep_base::Iterer_Pb(), Equation_base::preparer_calcul(), test_imposer_cond_lim(), and Schema_Implicite_Multi_TimeStep_base::test_stationnaire().
info()
const Type_info * Zone_Cl_dis::info () static
Definition at line 19 of file Zone_Cl_dis.cpp.
les_conditions_limites() [1/4]
Conds_lim & Zone_Cl_dis::les_conditions_limites () inline
Appel a l'objet sous-jacent
Renvoie le tableau des conditions aux limites.
Returns
Conds_lim&
Signification: le tableau des conditions aux limites
Contraintes:
Definition at line 165 of file Zone_Cl_dis.h.
{
  return valeur().les_conditions_limites();
}
References Zone_Cl_dis_base::les_conditions_limites(), and Deriv_Zone_Cl_dis_base::valeur().
les_conditions_limites() [2/4]
const Conds_lim & Zone_Cl_dis::les_conditions_limites () const inline
Appel a l'objet sous-jacent
Renvoie le tableau des conditions aux limites.
(version const)
Returns
Conds_lim&
Signification: le tableau des conditions aux limites
Contraintes: reference constante
Definition at line 187 of file Zone_Cl_dis.h.
{
  return valeur().les_conditions_limites();
}
References Zone_Cl_dis_base::les_conditions_limites(), and Deriv_Zone_Cl_dis_base::valeur().
les_conditions_limites() [3/4]
Cond_lim & Zone_Cl_dis::les_conditions_limites (int i) inline
Appel a l'objet sous-jacent
Renvoie la i-ieme condition aux limites.
Returns
Cond_lim&
Signification: la i-ieme condition aux limites
Contraintes:
Definition at line 144 of file Zone_Cl_dis.h.
{
  return valeur().les_conditions_limites(i);
}
References Zone_Cl_dis_base::les_conditions_limites(), and Deriv_Zone_Cl_dis_base::valeur().
les_conditions_limites() [4/4]
const Cond_lim & Zone_Cl_dis::les_conditions_limites (int i) const inline
Appel a l'objet sous-jacent
Renvoie la i-ieme condition aux limites.
(version const)
Returns
Cond_lim&
Signification: la i-ieme condition aux limites
Contraintes: reference constante
Definition at line 123 of file Zone_Cl_dis.h.
{
  return valeur().les_conditions_limites(i);
}
References Zone_Cl_dis_base::les_conditions_limites(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Masse_PolyMAC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Champ_Elem_PolyMAC_P0::calc_grad(), EDO_Pression_th_VEF::calculer_grad(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Fluide_Weakly_Compressible::checkTraitementPth(), Fluide_Quasi_Compressible::checkTraitementPth(), Operateur_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Source_WC_Chaleur_VDF::compute_interpolate_gradP_old(), Source_WC_Chaleur::correct_grad_boundary(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Champ_Generique_Extraction::get_champ(), Turbulence_paroi_base::get_champ(), Op_EF_base::impr(), Op_VEF_Face::impr(), Sonde::init_bords(), Champ_Elem_PolyMAC::init_fcl(), Champ_Face_PolyMAC::init_fcl(), grad_Champ_Face_PolyMAC_P0::init_grad(), Champ_Elem_PolyMAC_P0::init_grad(), Op_Diff_PolyMAC_Elem::init_op_ext(), Op_Diff_PolyMAC_P0_Elem::init_som_ext(), SETS::iterer_NS(), Solveur_U_P::iterer_NS(), Sonde::mettre_a_jour_bords(), EDO_Pression_th_VDF::mettre_a_jour_CL(), EDO_Pression_th_VEF::mettre_a_jour_CL(), Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl(), Convection_Diffusion_Espece_Binaire_base::preparer_calcul(), Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Reel::resoudre(), tester_compatibilite_hydr_concentration(), tester_compatibilite_hydr_fraction_massique(), tester_compatibilite_hydr_thermique(), Champ_Face_PolyMAC_P0::update_ve2(), Navier_Stokes_Fluide_Dilatable_Proto::update_vpoint_on_boundaries(), and Equation_base::verif_Cl().
mettre_a_jour()
void Zone_Cl_dis::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent
Effectue une mise a jour en temps des conditions aux limites.
Definition at line 229 of file Zone_Cl_dis.h.
{
  valeur().mettre_a_jour(temps);
}
References Zone_Cl_dis_base::mettre_a_jour(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by Multi_Sch_ThHyd::iterateTimeStep(), Navier_Stokes_std::preparer_calcul(), and Equation_base::updateGivenFields().
nb_cond_lim()
int Zone_Cl_dis::nb_cond_lim () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de conditions aux limites.
Returns
int
Signification: le nombre de conditions aux limites
Contraintes:
Definition at line 208 of file Zone_Cl_dis.h.
{
  return valeur().nb_cond_lim();
}
References Zone_Cl_dis_base::nb_cond_lim(), and Deriv_Zone_Cl_dis_base::valeur().
Referenced by Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Equation_base::completer(), Equation_base::ecrire_fichier_xyz(), Sonde::init_bords(), SETS::iterer_NS(), tester_compatibilite_hydr_concentration(), tester_compatibilite_hydr_fraction_massique(), and tester_compatibilite_hydr_thermique().
nb_faces_Cl()
int Zone_Cl_dis::nb_faces_Cl () const inline
Definition at line 241 of file Zone_Cl_dis.h.
{
  return valeur().nb_faces_Cl();
}
References Zone_Cl_dis_base::nb_faces_Cl(), and Deriv_Zone_Cl_dis_base::valeur().
printOn()
Sortie & Zone_Cl_dis::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Zone_Cl_dis_base.
Definition at line 36 of file Zone_Cl_dis.cpp.
{
  return os;
}
readOn()
Entree & Zone_Cl_dis::readOn (Entree & is) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Zone_Cl_dis_base.
Definition at line 56 of file Zone_Cl_dis.cpp.
{
  return is;
}
self_cast() [1/2]
const Zone_Cl_dis & Zone_Cl_dis::self_cast (const Objet_U & r) static
Definition at line 19 of file Zone_Cl_dis.cpp.
self_cast() [2/2]
Zone_Cl_dis & Zone_Cl_dis::self_cast (Objet_U & r) static
Definition at line 19 of file Zone_Cl_dis.cpp.
taille_memoire()
unsigned Zone_Cl_dis::taille_memoire () const override virtual
Reimplemented from Deriv_Zone_Cl_dis_base.
Definition at line 19 of file Zone_Cl_dis.cpp.
zone() [1/2]
Zone & Zone_Cl_dis::zone () inline
Definition at line 233 of file Zone_Cl_dis.h.
{
  return valeur().zone();
}
References Deriv_Zone_Cl_dis_base::valeur(), and Zone_Cl_dis_base::zone().
zone() [2/2]
const Zone & Zone_Cl_dis::zone () const inline
Definition at line 237 of file Zone_Cl_dis.h.
{
  return valeur().zone();
}
References Deriv_Zone_Cl_dis_base::valeur(), and Zone_Cl_dis_base::zone().
Member Data Documentation
info_obj
const Type_info Zone_Cl_dis::info_obj static
Definition at line 44 of file Zone_Cl_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Zone_Cl_dis.h
src/Kernel/Framework/Zone_Cl_dis.cpp