TRUST: PolyMAC_discretisation Class Reference
PolyMAC_discretisation Class Reference
#include <PolyMAC_discretisation.h>
Public Member Functions
PolyMAC_discretisation ()
~PolyMAC_discretisation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const override
Discretisation d'un champ pour le PolyMAC en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s) et nature du champ) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const override
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const override
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
void zone_Cl_dis (Zone_dis &z, Zone_Cl_dis &zcl) const override
void distance_paroi_globale (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const override
void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const override
discretise en PolyMAC le fluide incompressible, donc K e N
void residu (const Zone_dis &z, const Champ_Inc &ch_inco, Champ_Fonc &champ) const override
void vorticite (Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void critere_Q (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &vitesse, Champ_Fonc &ch) const override
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void y_plus (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &vitesse, Champ_Fonc &ch) const override
void grad_T (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch) const override
void grad_u (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &ch_vitesse, Champ_Fonc &ch) const override
void h_conv (const Zone_dis &z, const Zone_Cl_dis &, const Champ_Inc &temperature, Champ_Fonc &ch, Motcle &nom, int temp_ref) const override
type_calcul_du_residu codage_du_calcul_du_residu (void) const override
Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operateur, const Equation_base &eqn, const Ref_Champ_base &champ_sup) const override
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Discret_Thyd
Discret_Thyd ()
~Discret_Thyd () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void vitesse (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void translation (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void entcor (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
void pression (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void pression_en_pa (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void divergence_U (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void gradient_P (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void concentration (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int=1, const Nom nom_champ="concentration") const
void porosite_volumique (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
void diametre_hydraulique_elem (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void diametre_hydraulique_face (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
void section_passage (const Zone_dis &, const Schema_Temps_base &, Champ_Fonc &) const
virtual void creer_champ_vorticite (const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void grad_u (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void proprietes_physiques_fluide_Ostwald (const Zone_dis &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void distance_paroi_globale (const Schema_Temps_base &, Zone_dis &, Champ_Fonc &) const
virtual void y_plus (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual void grad_T (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch) const
virtual void h_conv (const Zone_dis &z, const Zone_Cl_dis &zcl, const Champ_Inc &eqn, Champ_Fonc &ch, Motcle &nom, int temp_ref) const
virtual void critere_Q (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
virtual void reynolds_maille (const Zone_dis &, const Fluide_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void courant_maille (const Zone_dis &, const Schema_Temps_base &, const Champ_Inc &, Champ_Fonc &) const
virtual void estimateur_aposteriori (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, const Champ_Inc &, const Champ_Don &, Champ_Fonc &) const
virtual void taux_cisaillement (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &, Champ_Fonc &) const
Public Member Functions inherited from Discret_Thermique
Discret_Thermique ()
~Discret_Thermique () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &, int nb_comp=1) const
void flux_neutronique (const Schema_Temps_base &sch, Zone_dis &z, Champ_Inc &ch, int nb_comp=1) const
void Fluctu_Temperature (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
void Flux_Chaleur_Turb (const Schema_Temps_base &, Zone_dis &, Champ_Inc &) const
Public Member Functions inherited from Discretisation_base
Discretisation_base ()
~Discretisation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual type_calcul_du_residu codage_du_calcul_du_residu (void) const
virtual void discretiser_variables () const
virtual void discretiser_Zone_Cl_dis (const Zone_dis &, Zone_Cl_dis &) const
virtual void discretiser (Domaine_dis &) const
virtual void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const =0
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Fonc &champ) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Don &champ) const
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
idem
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
idem
void nommer_completer_champ_physique (const Zone_dis_base &zone_vdf, const Nom &nom_champ, const Nom &unite, Champ_base &champ, const Probleme_base &pbi) const
int verifie_sous_type (Nom &type, const Nom &sous_type, const Motcle &directive) const
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
virtual void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const Ref_Champ_base &champ_supp=Ref_Champ_base()) const
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static PolyMAC_discretisation & self_cast (Objet_U &)
static const PolyMAC_discretisation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thyd
static const Type_info * info ()
static Discret_Thyd & self_cast (Objet_U &)
static const Discret_Thyd & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discret_Thermique
static const Type_info * info ()
static Discret_Thermique & self_cast (Objet_U &)
static const Discret_Thermique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discretisation_base
static const Type_info * info ()
static Discretisation_base & self_cast (Objet_U &)
static const Discretisation_base & self_cast (const Objet_U &)
static void creer_champ (Champ_Inc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Fonc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Don &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thyd
static const Type_info info_obj
Static Public Attributes inherited from Discret_Thermique
static const Type_info info_obj
Static Public Attributes inherited from Discretisation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Discret_Thyd
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Discret_Thermique
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void discretiser_champ_fonc_don (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Objet_U &champ) const
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
void modifier_champ_tabule (const Zone_dis_base &zone_vdf, Champ_Fonc_Tabule &lambda_tab, const Vect_Ref_Champ_base &ch_temper) const override
Additional Inherited Members
Public Types inherited from Discretisation_base
enum type_calcul_du_residu { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0 , VIA_AJOUTER = 1 }
Static Protected Attributes inherited from Discretisation_base
static const Motcle demande_description = Motcle("demande_description")
static const Nom nom_vide = Nom("-")
Detailed Description
Definition at line 41 of file PolyMAC_discretisation.h.
Constructor & Destructor Documentation
PolyMAC_discretisation()
PolyMAC_discretisation::PolyMAC_discretisation ()
Definition at line 35 of file PolyMAC_discretisation.cpp.
~PolyMAC_discretisation()
PolyMAC_discretisation::~PolyMAC_discretisation ()
Definition at line 35 of file PolyMAC_discretisation.cpp.
Member Function Documentation
codage_du_calcul_du_residu()
type_calcul_du_residu PolyMAC_discretisation::codage_du_calcul_du_residu (void) const inline override virtual
Reimplemented from Discretisation_base.
Definition at line 66 of file PolyMAC_discretisation.h.
  {
    return VIA_AJOUTER;
  }
References Discretisation_base::VIA_AJOUTER.
cree_instance()
Objet_U * PolyMAC_discretisation::cree_instance () static
Definition at line 35 of file PolyMAC_discretisation.cpp.
creer_champ_vorticite()
void PolyMAC_discretisation::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc & , Champ_Fonc &) const override virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Discret_Thyd.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 351 of file PolyMAC_discretisation.cpp.
{
#ifdef dependance
  if (sub_type(Champ_Som_PolyMAC,ch_vitesse.valeur()))
    {
      ch.typer("Rotationnel_Champ_Som_PolyMAC");
      const Champ_Som_PolyMAC& vit = ref_cast(Champ_Som_PolyMAC,ch_vitesse.valeur());
      const Zone_PolyMAC& zone_PolyMAC = ref_cast(Zone_PolyMAC,vit.zone_dis_base());
      Rotationnel_Champ_Som_PolyMAC& ch_W = ref_cast(Rotationnel_Champ_Som_PolyMAC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_PolyMAC);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0, "vorticitex");
          ch_W.fixer_nom_compo(1, "vorticitey");
          ch_W.fixer_nom_compo(2, "vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(sch.temps_courant());
    }
  else if (sub_type(Champ_Q1_PolyMAC,ch_vitesse.valeur()))
    {
      ch.typer("Rotationnel_Champ_Q1_PolyMAC");
      const Champ_Q1_PolyMAC& vit = ref_cast(Champ_Q1_PolyMAC,ch_vitesse.valeur());
      const Zone_PolyMAC& zone_PolyMAC = ref_cast(Zone_PolyMAC,vit.zone_dis_base());
      Rotationnel_Champ_Q1_PolyMAC& ch_W = ref_cast(Rotationnel_Champ_Q1_PolyMAC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_PolyMAC);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0, "vorticitex");
          ch_W.fixer_nom_compo(1, "vorticitey");
          ch_W.fixer_nom_compo(2, "vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(sch.temps_courant());
    }
  else
    {
      Cerr << "Pb dans le typage des elements dans PolyMAC_discretisation::creer_champ_vorticite" << finl;
      exit();
    }
#endif
}
References Cerr, Objet_U::dimension, Process::exit(), finl, Zone_dis_base::nb_elem(), ref_cast, sub_type, Schema_Temps_base::temps_courant(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), and Champ_Som_PolyMAC::zone_dis_base().
critere_Q()
void PolyMAC_discretisation::critere_Q (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & , Champ_Fonc &) const override virtual
NE FAIT RIEN, provoque une erreur
A surcharger dans les classes derivees.
Reimplemented from Discret_Thyd.
Definition at line 490 of file PolyMAC_discretisation.cpp.
{
#ifdef dependance
// On passe la zcl, pour qu'il n y ait qu une methode qqsoit la dsicretisation
// mais on ne s'en sert pas!!!
  Cerr << "Discretisation du critere Q " << finl;
  const Champ_Som_PolyMAC& vit = ref_cast(Champ_Som_PolyMAC,ch_vitesse.valeur());
  const Zone_PolyMAC& zone_PolyMAC=ref_cast(Zone_PolyMAC, z.valeur());
  ch.typer("Critere_Q_Champ_Som_PolyMAC");
  Critere_Q_Champ_Som_PolyMAC& ch_cQ=ref_cast(Critere_Q_Champ_Som_PolyMAC,ch.valeur());
  ch_cQ.associer_zone_dis_base(zone_PolyMAC);
  ch_cQ.associer_champ(vit);
  ch_cQ.nommer("Critere_Q");
  ch_cQ.fixer_nb_comp(1);
  ch_cQ.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
  ch_cQ.fixer_unite("s-2");
  ch_cQ.changer_temps(ch_vitesse.temps());
#endif
}
References Cerr, finl, Zone_dis_base::nb_elem(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), and Deriv_Zone_dis_base::valeur().
discretiser_champ() [1/3]
void PolyMAC_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Don & champ) const override virtual
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
Reimplemented from Discretisation_base.
Definition at line 161 of file PolyMAC_discretisation.cpp.
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
References discretiser_champ_fonc_don().
discretiser_champ() [2/3]
void PolyMAC_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Fonc & champ) const override virtual
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
Reimplemented from Discretisation_base.
Definition at line 147 of file PolyMAC_discretisation.cpp.
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
References discretiser_champ_fonc_don().
discretiser_champ() [3/3]
void PolyMAC_discretisation::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const override virtual
Discretisation d'un champ pour le PolyMAC en fonction d'une directive
de discretisation. La directive est un Motcle comme "vitesse", "pression",
"temperature", "champ_elem" (cree un champ de type P0), ...
Cette methode determine le type du champ a creer en fonction du type d'element
et de la directive de discretisation. Elle determine ensuite le nombre de ddl
et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt,
nom(s), unite(s) et nature du champ) et associe la Zone_dis au champ.
Voir le code pour avoir la correspondance entre les directives et
le type de champ cree.
< Choix standard pour la vitesse
< Choix standard pour la pression
< Choix standard pour la temperature
< Le type de champ obtenu en calculant div v
< Le type de champ obtenu en calculant grad P
< Creer un champ aux elements (de type P0)
< Creer un champ aux sommets (type P1)
< Valeur par defaut du nombre de composantes
Reimplemented from Discretisation_base.
Definition at line 59 of file PolyMAC_discretisation.cpp.
{
  const Zone_PolyMAC& zone_PolyMAC = ref_cast(Zone_PolyMAC, z);
  Motcles motcles(7);
  motcles[0] = "vitesse";     //!< Choix standard pour la vitesse
  motcles[1] = "pression";    //!< Choix standard pour la pression
  motcles[2] = "temperature"; //!< Choix standard pour la temperature
  motcles[3] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  motcles[4] = "gradient_pression";  //!< Le type de champ obtenu en calculant grad P
  motcles[5] = "champ_elem";    //!< Creer un champ aux elements (de type P0)
  motcles[6] = "champ_sommets"; //!< Creer un champ aux sommets (type P1)
// Le type de champ de vitesse depend du type d'element :
  Nom type_champ_vitesse = Nom("Champ_Face_") + que_suis_je();
  Nom type_elem = Nom("Champ_Elem_") + que_suis_je();
  Nom type;
  int default_nb_comp = 0; //!< Valeur par defaut du nombre de composantes
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
    case 4:
      type = type_champ_vitesse;
      default_nb_comp = 3;
      break;
    case 1:
    case 2:
    case 3:
    case 5:
      type = type_elem;
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "PolyMAC_discretisation : " << motcles;
  if (sous_type != nom_vide)
    rang = verifie_sous_type(type,sous_type,directive);
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      Discret_Thyd::discretiser_champ(directive, z,
                                      nature, noms, unites,
                                      nb_comp, nb_pas_dt, temps, champ);
      return;
    }
// Calcul du nombre de ddl
  int nb_ddl = 0;
  if (type.debute_par(type_elem)) nb_ddl = z.nb_elem();
  else if (type.debute_par(type_champ_vitesse)) nb_ddl = zone_PolyMAC.nb_faces();
  else if (type.debute_par("Champ_P1_PolyMAC")) nb_ddl = zone_PolyMAC.nb_som();
  else assert(0);
  /* if (nature == multi_scalaire) {
    // Pas encore code
    Cerr << "Champ multi_scalaire pas code" << finl;
    assert(0); exit();
// Si c'est un champ multiscalaire, uh !
    } else {*/
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  assert(nb_comp > 0);
  creer_champ(champ, z, type, noms[0], unites[0], nb_comp, nb_ddl, nb_pas_dt, temps,
              directive, que_suis_je());
  if (nature == multi_scalaire)
    {
      champ.valeur().fixer_nature_du_champ(nature);
      champ.valeur().fixer_unites(unites);
      champ.valeur().fixer_noms_compo(noms);
    }
}
References Cerr, Discretisation_base::creer_champ(), Nom::debute_par(), Discretisation_base::demande_description, Discretisation_base::discretiser_champ(), Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), multi_scalaire, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Discretisation_base::nom_vide, Objet_U::que_suis_je(), ref_cast, Motcles::search(), type_elem(), Deriv_Champ_Inc_base::valeur(), and Discretisation_base::verifie_sous_type().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::creer_champ(), distance_paroi_globale(), residu(), and y_plus().
discretiser_champ_fonc_don()
void PolyMAC_discretisation::discretiser_champ_fonc_don (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Objet_U & champ) const private
Idem que PolyMAC_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
< Choix standard pour la pression
< Choix standard pour la temperature
< Le type de champ obtenu en calculant div v
< Creer un champ aux elements (de type P0)
< Creer un champ aux elements (de type P1)
< Choix standard pour la vitesse
< Choix standard pour la vitesse
< Le type de champ obtenu en calculant grad P
< Valeur par defaut du nombre de composantes
Definition at line 177 of file PolyMAC_discretisation.cpp.
{
// Deux pointeurs pour acceder facilement au champ_don ou au champ_fonc,
// suivant le type de l'objet champ.
  Champ_Fonc * champ_fonc = 0;
  Champ_Don * champ_don = 0;
  if (sub_type(Champ_Fonc, champ))
    champ_fonc = & ref_cast(Champ_Fonc, champ);
  else
    champ_don  = & ref_cast(Champ_Don, champ);
  const Zone_PolyMAC& zone_PolyMAC = ref_cast(Zone_PolyMAC, z);
  Motcles motcles(8);
  motcles[0] = "pression";    //!< Choix standard pour la pression
  motcles[1] = "temperature"; //!< Choix standard pour la temperature
  motcles[2] = "divergence_vitesse"; //!< Le type de champ obtenu en calculant div v
  motcles[3] = "champ_elem";  //!< Creer un champ aux elements (de type P0)
  motcles[6] = "champ_sommets";  //!< Creer un champ aux elements (de type P1)
  motcles[4] = "vitesse";     //!< Choix standard pour la vitesse
  motcles[7] = "champ_face";     //!< Choix standard pour la vitesse
  motcles[5] = "gradient_pression";  //!< Le type de champ obtenu en calculant grad P
// Le type de champ de vitesse depend du type d'element :
  Nom type_champ_vitesse("Champ_Fonc_Face_PolyMAC");
  Nom type_elem("Champ_Fonc_Elem_PolyMAC");
  Nom type;
  int default_nb_comp = 0; //!< Valeur par defaut du nombre de composantes
  int rang = motcles.search(directive);
  switch(rang)
    {
    case 0:
    case 1:
    case 2:
    case 3:
      type = type_elem;
      default_nb_comp = 1;
      break;
    case 4:
    case 5:
    case 7:
      type = type_champ_vitesse;
      default_nb_comp = 3;
      break;
    case 6:
      type = "Champ_Fonc_Som_PolyMAC";
      default_nb_comp = 1;
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "PolyMAC_discretisation : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      if (champ_fonc)
        Discret_Thyd::discretiser_champ(directive, z, nature, noms, unites,
                                        nb_comp, temps, *champ_fonc);
      else
        Discret_Thyd::discretiser_champ(directive, z, nature, noms, unites,
                                        nb_comp, temps, *champ_don);
      return;
    }
// Calcul du nombre de ddl
  int nb_ddl = 0;
  if (type == "Champ_Fonc_Elem_PolyMAC")
    nb_ddl = z.nb_elem();
  else if (type == type_champ_vitesse)
    nb_ddl = zone_PolyMAC.nb_faces();
  else if (type == "Champ_Fonc_Som_PolyMAC")
    nb_ddl = zone_PolyMAC.nb_som();
  else
    assert(0);
// Si c'est un champ multiscalaire, uh !
  if (nb_comp < 0)
    nb_comp = default_nb_comp;
  if (champ_fonc)
    creer_champ(*champ_fonc, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  else
    creer_champ(*champ_don, z, type, noms[0], unites[0], nb_comp, nb_ddl, temps,
                directive, que_suis_je());
  if ((nature == multi_scalaire) && (champ_fonc))
    {
      champ_fonc->valeur().fixer_nature_du_champ(nature);
      champ_fonc->valeur().fixer_unites(unites);
      champ_fonc->valeur().fixer_noms_compo(noms);
    }
  else if ((nature == multi_scalaire) && (champ_don))
    {
      Cerr<<"There is no field of type Champ_Don with a multi_scalaire nature."<<finl;
      exit();
    }
}
References Cerr, Discretisation_base::creer_champ(), Discretisation_base::demande_description, Discretisation_base::discretiser_champ(), Process::exit(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_noms_compo(), Field_base::fixer_unites(), multi_scalaire, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone_dis_base::nb_som(), Objet_U::que_suis_je(), ref_cast, Motcles::search(), sub_type, type_elem(), and Deriv_Champ_Fonc_base::valeur().
Referenced by discretiser_champ().
distance_paroi_globale()
void PolyMAC_discretisation::distance_paroi_globale (const Schema_Temps_base & sch, Zone_dis & z, Champ_Fonc & ch) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 285 of file PolyMAC_discretisation.cpp.
{
  Cerr << "Discretisation de distance paroi globale" << finl;
  Noms noms(1), unites(1);
  noms[0] = Nom("distance_paroi_globale");
  unites[0] = Nom("m");
  discretiser_champ(Motcle("champ_elem"), z.valeur(), scalaire, noms , unites, 1, 0, ch);
}
References Cerr, discretiser_champ(), finl, scalaire, and Deriv_Zone_dis_base::valeur().
duplique()
int PolyMAC_discretisation::duplique () const override virtual
Implements Objet_U.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 35 of file PolyMAC_discretisation.cpp.
get_info()
const Type_info * PolyMAC_discretisation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 35 of file PolyMAC_discretisation.cpp.
get_name_of_type_for()
Nom PolyMAC_discretisation::get_name_of_type_for (const Nom & class_operateur, const Nom & type_operteur, const Equation_base & eqn, const Ref_Champ_base & champ_supp) const override virtual
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Reimplemented from Discretisation_base.
Definition at line 584 of file PolyMAC_discretisation.cpp.
{
  Nom type;
  Nom type_ch=eqn.inconnue()->que_suis_je();
  if (type_ch.debute_par("Champ_Elem"))
    type_ch = "_Elem";
  if (type_ch.debute_par("Champ_Face"))
    type_ch = "_Face";
  if (class_operateur=="Source")
    type = type_operateur + type_ch +  "_" + que_suis_je();
  else if (class_operateur=="Solveur_Masse")
    type = Nom("Masse_") + que_suis_je() + type_ch;
  else if (class_operateur=="Operateur_Grad")
    type = Nom("Op_Grad_") + que_suis_je() + "_Face";
  else if (class_operateur=="Operateur_Div")
    type = Nom("Op_Div_") + que_suis_je();
  else if (class_operateur=="Operateur_Diff")
    type = Nom("Op_Diff") + (type_operateur != "" ? "_" : "") + type_operateur + "_" + que_suis_je() + type_ch;
  else if (class_operateur=="Operateur_Conv")
    type = Nom("Op_Conv_") + type_operateur + "_" + que_suis_je() + type_ch;
  else if (class_operateur=="Operateur_Evanescence")
    type = Nom("Op_Evanescence") + (type_operateur != "" ? "_" : "") + type_operateur + "_" + que_suis_je() + type_ch;
  else return Discret_Thyd::get_name_of_type_for(class_operateur,type_operateur,eqn);
  return type;
}
References Nom::debute_par(), Discretisation_base::get_name_of_type_for(), Equation_base::inconnue(), and Objet_U::que_suis_je().
grad_T()
void PolyMAC_discretisation::grad_T (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & temperature, Champ_Fonc & ch) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 523 of file PolyMAC_discretisation.cpp.
{
#ifdef dependance
  Cerr << "Discretisation de gradient_temperature" << finl;
  const Champ_Som_PolyMAC& temp = ref_cast(Champ_Som_PolyMAC,ch_temperature.valeur());
  const Zone_PolyMAC& zone_PolyMAC=ref_cast(Zone_PolyMAC, z.valeur());
  const Zone_Cl_PolyMAC& zone_cl_PolyMAC=ref_cast(Zone_Cl_PolyMAC, zcl.valeur());
  ch.typer("gradient_temperature_Champ_Som_PolyMAC");
  grad_T_Champ_Som_PolyMAC& ch_gt=ref_cast(grad_T_Champ_Som_PolyMAC,ch.valeur());
  ch_gt.associer_zone_dis_base(zone_PolyMAC);
  ch_gt.associer_zone_Cl_dis_base(zone_cl_PolyMAC);
  ch_gt.associer_champ(temp);
  ch_gt.nommer("gradient_temperature");
  ch_gt.fixer_nb_comp(dimension);
  ch_gt.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
  ch_gt.fixer_unite("K/m");
  ch_gt.changer_temps(ch_temperature.temps());
#endif
}
References Cerr, Objet_U::dimension, finl, Zone_dis_base::nb_elem(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
grad_u()
void PolyMAC_discretisation::grad_u (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const override virtual
Reimplemented from Discret_Thyd.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 543 of file PolyMAC_discretisation.cpp.
{
  abort();
}
References Process::abort().
h_conv()
void PolyMAC_discretisation::h_conv (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & temperature, Champ_Fonc & ch, Motcle & nom, int temp_ref) const override virtual
Reimplemented from Discret_Thyd.
Definition at line 548 of file PolyMAC_discretisation.cpp.
{
#ifdef dependance
  Cerr << "Discretisation de h_conv" << finl;
  const Champ_Som_PolyMAC& temp = ref_cast(Champ_Som_PolyMAC,ch_temperature.valeur());
  const Zone_PolyMAC& zone_PolyMAC=ref_cast(Zone_PolyMAC, z.valeur());
  const Zone_Cl_PolyMAC& zone_cl_PolyMAC=ref_cast(Zone_Cl_PolyMAC, zcl.valeur());
  ch.typer("h_conv_Champ_Som_PolyMAC");
  h_conv_Champ_Som_PolyMAC& ch_gt=ref_cast(h_conv_Champ_Som_PolyMAC,ch.valeur());
  ch_gt.associer_zone_dis_base(zone_PolyMAC);
  ch_gt.associer_zone_Cl_dis_base(zone_cl_PolyMAC);
  ch_gt.associer_champ(temp);
  ch_gt.temp_ref()=temp_ref;
//
  ch_gt.nommer(nom);
  ch_gt.fixer_nb_comp(1);
  ch_gt.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
  ch_gt.fixer_unite("W/m2.K");
  ch_gt.changer_temps(ch_temperature.temps());
#endif
}
References Cerr, finl, Zone_dis_base::nb_elem(), ref_cast, Champ_Inc::temps(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
info()
const Type_info * PolyMAC_discretisation::info () static
Definition at line 35 of file PolyMAC_discretisation.cpp.
modifier_champ_tabule()
void PolyMAC_discretisation::modifier_champ_tabule (const Zone_dis_base & zone_vdf, Champ_Fonc_Tabule & lambda_tab, const Vect_Ref_Champ_base & ch_temper) const override private virtual
Reimplemented from Discretisation_base.
Definition at line 569 of file PolyMAC_discretisation.cpp.
{
  Champ_Fonc& lambda_tab_dis = lambda_tab.le_champ_tabule_discretise();
  lambda_tab_dis.typer("Champ_Fonc_Tabule_Elem_PolyMAC");
  Champ_Fonc_Tabule_Elem_PolyMAC& ch_tab_lambda_dis =
    ref_cast(Champ_Fonc_Tabule_Elem_PolyMAC,lambda_tab_dis.valeur());
// ch_tab_lambda_dis.nommer(nom_champ);
  ch_tab_lambda_dis.associer_zone_dis_base(zone_vdf);
  ch_tab_lambda_dis.associer_param(champs_param, lambda_tab.table());
  ch_tab_lambda_dis.fixer_nb_comp(lambda_tab.nb_comp());
  ch_tab_lambda_dis.fixer_nb_valeurs_nodales(zone_vdf.nb_elem());
// ch_tab_lambda_dis.fixer_unite(unite);
  ch_tab_lambda_dis.changer_temps(champs_param[0].valeur().temps());
}
References Champ_Fonc_Tabule_Elem_PolyMAC::associer_param(), Champ_Fonc_P0_base::associer_zone_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), Field_base::nb_comp(), Zone_dis_base::nb_elem(), ref_cast, Champ_Fonc_Tabule::table(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), and valeur().
printOn()
Sortie & PolyMAC_discretisation::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 44 of file PolyMAC_discretisation.cpp.
{
  return s ;
}
proprietes_physiques_fluide_Ostwald()
void PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald (const Zone_dis & z, Fluide_Ostwald & le_fluide, const Navier_Stokes_std & eqn_hydr, const Champ_Inc & ch_temper) const override virtual
discretise en PolyMAC le fluide incompressible, donc K e N
Reimplemented from Discret_Thyd.
Definition at line 440 of file PolyMAC_discretisation.cpp.
{
#ifdef dependance
  Cerr << "Discretisation PolyMAC du fluide_Ostwald" << finl;
  const Zone_PolyMAC& zone_PolyMAC=ref_cast(Zone_PolyMAC, z.valeur());
  const Champ_Inc& ch_vitesse = eqn_hydr.inconnue();
  const Champ_Som_PolyMAC& vit = ref_cast(Champ_Som_PolyMAC,ch_vitesse.valeur());
  Champ_Don& mu = le_fluide.viscosite_dynamique();
// mu est toujours un champ_Ostwald_PolyMAC , il faut toujours faire ce qui suit
  mu.typer("Champ_Ostwald_PolyMAC");
  Champ_Ostwald_PolyMAC& ch_mu = ref_cast(Champ_Ostwald_PolyMAC,mu.valeur());
  Cerr<<"associe zonedisbase PolyMAC"<<finl;
  ch_mu.associer_zone_dis_base(zone_PolyMAC);
  ch_mu.associer_fluide(le_fluide);
  ch_mu.associer_champ(vit);
  ch_mu.associer_eqn(eqn_hydr);
  Cerr<<"associations finies zone dis base, fluide, champ PolyMAC"<<finl;
  ch_mu.fixer_nb_comp(1);
  Cerr<<"fait fixer_nb_valeurs_nodales"<<finl;
  Cerr<<"nb_valeurs_nodales PolyMAC = "<<zone_PolyMAC.nb_elem()<<finl;
  ch_mu.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
  Cerr<<"fait changer_temps"<<finl;
  ch_mu.changer_temps(vit.temps());
  Cerr<<"mu PolyMAC est discretise "<<finl;
#endif
}
References Cerr, finl, Navier_Stokes_std::inconnue(), Zone_dis_base::nb_elem(), ref_cast, Champ_base::temps(), Deriv_::typer(), Deriv_Champ_Don_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Fluide_base::viscosite_dynamique().
readOn()
Entree & PolyMAC_discretisation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Discretisation_base.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 39 of file PolyMAC_discretisation.cpp.
{
  return s ;
}
residu()
void PolyMAC_discretisation::residu (const Zone_dis & z, const Champ_Inc & ch_inco, Champ_Fonc & champ) const override virtual
Reimplemented from Discretisation_base.
Definition at line 613 of file PolyMAC_discretisation.cpp.
{
  Nom ch_name(ch_inco.le_nom());
  ch_name += "_residu";
  Cerr << "Discretization of " << ch_name << finl;
  Nom type_ch = ch_inco.valeur().que_suis_je();
  if (type_ch.debute_par("Champ_Face"))
    {
      Motcle loc = "champ_face";
      Noms nom(1), unites(1);
      nom[0] = ch_name;
      unites[0] = "units_not_defined";
      int nb_comp = ch_inco.valeurs().line_size()*dimension;
      discretiser_champ(loc,z.valeur(), vectoriel, nom ,unites,nb_comp,ch_inco.temps(),champ);
    }
  else
    {
      Motcle loc = "champ_elem";
      Noms nom(1), unites(1);
      nom[0] = ch_name;
      unites[0] = "units_not_defined";
      int nb_comp = ch_inco.valeurs().line_size();
      discretiser_champ(loc,z.valeur(), scalaire, nom ,unites,nb_comp,ch_inco.temps(),champ);
    }
  Champ_Fonc_base& ch_fonc = ref_cast(Champ_Fonc_base,champ.valeur());
  DoubleTab& tab=ch_fonc.valeurs();
  tab = -10000.0 ;
  Cerr << "[Information] Discretisation_base::residu : the residue is set to -10000.0 at initial time" <<finl;
}
References Cerr, Nom::debute_par(), Objet_U::dimension, discretiser_champ(), finl, O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Objet_U::que_suis_je(), ref_cast, scalaire, Champ_Inc::temps(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), and vectoriel.
self_cast() [1/2]
const PolyMAC_discretisation & PolyMAC_discretisation::self_cast (const Objet_U & r) static
Definition at line 35 of file PolyMAC_discretisation.cpp.
self_cast() [2/2]
PolyMAC_discretisation & PolyMAC_discretisation::self_cast (Objet_U & r) static
Definition at line 35 of file PolyMAC_discretisation.cpp.
taille_memoire()
unsigned PolyMAC_discretisation::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in PolyMAC_P0_discretisation.
Definition at line 35 of file PolyMAC_discretisation.cpp.
vorticite()
void PolyMAC_discretisation::vorticite (Zone_dis & z, const Champ_Inc & ch_vitesse, Champ_Fonc & ch) const
Definition at line 294 of file PolyMAC_discretisation.cpp.
{
#ifdef dependance
  Cerr << "Discretisation de la vorticite " << finl;
  const Zone_PolyMAC& zone_PolyMAC=ref_cast(Zone_PolyMAC, z.valeur());
  if (sub_type(Tri_PolyMAC,zone_PolyMAC.type_elem().valeur()) || sub_type(Segment_PolyMAC,zone_PolyMAC.type_elem().valeur()) || sub_type(Tetra_PolyMAC,zone_PolyMAC.type_elem().valeur()))
    {
      ch.typer("Rotationnel_Champ_Som_PolyMAC");
      const Champ_Som_PolyMAC& vit = ref_cast(Champ_Som_PolyMAC,ch_vitesse.valeur());
      Rotationnel_Champ_Som_PolyMAC& ch_W=ref_cast(Rotationnel_Champ_Som_PolyMAC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_PolyMAC);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0,"vorticitex");
          ch_W.fixer_nom_compo(1,"vorticitey");
          ch_W.fixer_nom_compo(2,"vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(ch_vitesse.temps());
    }
  else if (sub_type(Quadri_PolyMAC,zone_PolyMAC.type_elem().valeur()) || sub_type(Hexa_PolyMAC,zone_PolyMAC.type_elem().valeur()))
    {
      ch.typer("Rotationnel_Champ_Q1_PolyMAC");
      const Champ_Q1_PolyMAC& vit = ref_cast(Champ_Q1_PolyMAC,ch_vitesse.valeur());
      Rotationnel_Champ_Q1_PolyMAC& ch_W=ref_cast(Rotationnel_Champ_Q1_PolyMAC,ch.valeur());
      ch_W.associer_zone_dis_base(zone_PolyMAC);
      ch_W.associer_champ(vit);
      ch_W.nommer("vorticite");
      if (dimension == 2)
        ch_W.fixer_nb_comp(1);
      else
        {
          ch_W.fixer_nb_comp(dimension);
          ch_W.fixer_nom_compo(0,"vorticitex");
          ch_W.fixer_nom_compo(1,"vorticitey");
          ch_W.fixer_nom_compo(2,"vorticitez");
        }
      ch_W.fixer_nb_valeurs_nodales(zone_PolyMAC.nb_elem());
      ch_W.fixer_unite("s-1");
      ch_W.changer_temps(ch_vitesse.temps());
    }
  else
    {
      Cerr << "Pb dans le typage des elements dans PolyMAC_discretisation::vorticite" << finl;
      exit();
    }
#endif
}
References Cerr, Objet_U::dimension, Process::exit(), finl, Zone_dis_base::nb_elem(), ref_cast, sub_type, Champ_Inc::temps(), Zone_Poly_base::type_elem(), Deriv_::typer(), Deriv_Champ_Fonc_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_dis_base::valeur(), and Deriv_Elem_poly_base::valeur().
y_plus()
void PolyMAC_discretisation::y_plus (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & vitesse, Champ_Fonc & ch) const override virtual
< Utilise comme modele distance paroi globale
Reimplemented from Discret_Thyd.
Definition at line 511 of file PolyMAC_discretisation.cpp.
{
  Cerr << "Discretisation de y plus" << finl; //!< Utilise comme modele distance paroi globale
  Noms noms(1), unites(1);
  noms[0] = Nom("y_plus");
  unites[0] = Nom("m");
  discretiser_champ(Motcle("champ_elem"), z.valeur(), scalaire, noms , unites, 1, 0, ch);
  DoubleTab& tab_y_p = ch->valeurs();
  for (int i = 0 ; i < tab_y_p.dimension_tot(0) ; i++)
    for (int n = 0 ; n < tab_y_p.dimension_tot(1) ; n++) tab_y_p(i,n) = -1.;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension_tot(), discretiser_champ(), finl, scalaire, Deriv_Zone_dis_base::valeur(), and Champ_Fonc::valeurs().
zone_Cl_dis()
void PolyMAC_discretisation::zone_Cl_dis (Zone_dis & z, Zone_Cl_dis & zcl) const override virtual
Implements Discretisation_base.
Definition at line 476 of file PolyMAC_discretisation.cpp.
{
  Cerr << "discretisation des conditions limites" << finl;
  assert(z.non_nul());
  Zone_PolyMAC& zone_PolyMAC=ref_cast(Zone_PolyMAC, z.valeur());
  zcl.typer("Zone_Cl_PolyMAC");
  assert(zcl.non_nul());
  Zone_Cl_PolyMAC& zone_cl_PolyMAC=ref_cast(Zone_Cl_PolyMAC, zcl.valeur());
  zone_cl_PolyMAC.associer(zone_PolyMAC);
  Cerr << "discretisation des conditions limites OK" << finl;
}
References Zone_Cl_PolyMAC::associer(), Cerr, finl, O_U_Ptr::non_nul(), ref_cast, Deriv_::typer(), Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Member Data Documentation
info_obj
const Type_info PolyMAC_discretisation::info_obj static
Definition at line 43 of file PolyMAC_discretisation.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Zones/PolyMAC_discretisation.h
src/PolyMAC/Zones/PolyMAC_discretisation.cpp