TRUST: Frontiere_dis_base Class Reference
Frontiere_dis_base Class Reference
classe Frontiere_dis_base
Classe representant une frontiere discretisee. Les objets
Frontiere_dis_base contiennent un reference vers l'objet
geometrique Frontiere.
#include <Frontiere_dis_base.h>
Public Member Functions
Frontiere_dis_base ()
~Frontiere_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_frontiere (const Frontiere &)
Associe l'objet frontiere geometrique a la
frontiere discretisee.
void associer_Zone_dis (const Zone_dis_base &)
const Frontiere & frontiere () const
Renvoie la frontiere geometrique associee.
(version const)
Frontiere & frontiere ()
Renvoie la frontiere geometrique associee.
const Zone_dis_base & zone_dis () const
const Nom & le_nom () const override
Renvoie le nom de la frontiere geometrique.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Frontiere_dis_base & self_cast (Objet_U &)
static const Frontiere_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la frontiere discretisee sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une frontiere discretisee a partir d'un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Frontiere la_frontiere
Ref_Zone_dis_base la_zone_dis
Detailed Description
classe Frontiere_dis_base
Classe representant une frontiere discretisee. Les objets
Frontiere_dis_base contiennent un reference vers l'objet
geometrique Frontiere.
Definition at line 35 of file Frontiere_dis_base.h.
Constructor & Destructor Documentation
Frontiere_dis_base()
Frontiere_dis_base::Frontiere_dis_base ()
Definition at line 18 of file Frontiere_dis_base.cpp.
~Frontiere_dis_base()
Frontiere_dis_base::~Frontiere_dis_base () override
Definition at line 18 of file Frontiere_dis_base.cpp.
Member Function Documentation
associer_frontiere()
void Frontiere_dis_base::associer_frontiere (const Frontiere & fr)
Associe l'objet frontiere geometrique a la
frontiere discretisee.
Definition at line 81 of file Frontiere_dis_base.cpp.
{
  la_frontiere=fr;
}
References la_frontiere.
associer_Zone_dis()
void Frontiere_dis_base::associer_Zone_dis (const Zone_dis_base & z)
Definition at line 144 of file Frontiere_dis_base.cpp.
{
  la_zone_dis=z;
}
References la_zone_dis.
frontiere() [1/2]
Frontiere & Frontiere_dis_base::frontiere ()
Renvoie la frontiere geometrique associee.
Returns
Frontiere&
Signification: la frontiere geometrique associee
Contraintes:
Definition at line 120 of file Frontiere_dis_base.cpp.
{
  return la_frontiere.valeur();
}
References la_frontiere, and Ref_Frontiere::valeur().
frontiere() [2/2]
const Frontiere & Frontiere_dis_base::frontiere () const
Renvoie la frontiere geometrique associee.
(version const)
Returns
Frontiere&
Signification: la frontiere geometrique associee
Contraintes: reference constante
Definition at line 101 of file Frontiere_dis_base.cpp.
{
  return la_frontiere.valeur();
}
References la_frontiere, and Ref_Frontiere::valeur().
Referenced by Ch_front_input::buildSommetsFaces(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_EC::calculer_Ec(), Echange_contact_VDF::calculer_h_autre_pb(), calculer_h_distant(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Operateur_base::calculer_pour_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Equation_base::completer(), Champ_front_calc::completer(), Periodique::completer(), Terme_Source_Canal_perio::completer(), Echange_interne_global_impose::completer(), Champ_front_contact_VEF::completer(), Champ_Generique_Extraction::completer(), Zone_Cl_VDF::completer(), Equation_base::ecrire_fichier_xyz(), Extraire_surface::extraire_surface(), Champ_Generique_Extraction::get_champ(), Ch_front_input::getTemplate(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_VDF::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_var::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_contact_VEF::initialiser(), Zone_Cl_dis_base::la_cl_de_la_face(), Champ_front_bruite::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_MED::remplir_tab(), Zone_Cl_VEF::remplir_volumes_entrelaces_Cl(), Champ_implementation_P0::trace(), Champ_implementation_sommet_base::trace(), Champ_P1NC_implementation::trace(), Champ_Q1NC_impl::trace(), Champ_Elem_PolyMAC::trace(), Champ_front_contact_VEF::trace_face_raccord(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Champ_front_base::valeurs_face(), and Champ_front_contact_VEF::verifier_scalaire_bord().
get_info()
const Type_info * Frontiere_dis_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Front_VF.
Definition at line 18 of file Frontiere_dis_base.cpp.
info()
const Type_info * Frontiere_dis_base::info () static
Definition at line 18 of file Frontiere_dis_base.cpp.
le_nom()
const Nom & Frontiere_dis_base::le_nom () const override virtual
Renvoie le nom de la frontiere geometrique.
Returns
Nom&
Signification: le nom de la frontiere geometrique
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 139 of file Frontiere_dis_base.cpp.
{
  return la_frontiere->le_nom();
}
References la_frontiere, and Frontiere::le_nom().
Referenced by T_It_VDF_Elem< _TYPE_ >::ajouter_bords(), T_It_VDF_Elem< _TYPE_ >::ajouter_bords_(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords_(), T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse_(), Op_Diff_VEFP1NCP1B_Face::associer(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord2(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord_(), calculer_h_local(), Operateur_base::completer(), Terme_Source_Canal_perio::completer(), Champ_front_fonc_gradient::condition_limite(), T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_bords_(), Zone_Poly_base::dist_norm_bord(), Zone_VDF::dist_norm_bord(), Zone_Cl_EF::imposer_symetrie_partiellement(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_base::impr(), Op_Diff_PolyMAC_P0_base::impr(), Op_Div_PolyMAC::impr(), Op_Div_PolyMAC_P0::impr(), T_It_VDF_Elem< _TYPE_ >::impr(), T_It_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEF_Elem::impr(), Echange_contact_PolyMAC::init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Echange_contact_VDF::initialiser(), Champ_front_recyclage::lire_fichier_format3(), message_erreur_conc(), message_erreur_fraction_massique(), message_erreur_therm(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Operateur_base::ouvrir_fichier(), Zone_dis_base::rang_frontiere(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_implementation::trace(), and Echange_contact_VDF::verifier_correspondance().
printOn()
Sortie & Frontiere_dis_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la frontiere discretisee sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Front_VF.
Definition at line 38 of file Frontiere_dis_base.cpp.
{
  return os;
}
readOn()
Entree & Frontiere_dis_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une frontiere discretisee a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Front_VF.
Definition at line 60 of file Frontiere_dis_base.cpp.
{
  return is;
}
self_cast() [1/2]
const Frontiere_dis_base & Frontiere_dis_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Frontiere_dis_base.cpp.
self_cast() [2/2]
Frontiere_dis_base & Frontiere_dis_base::self_cast (Objet_U & r) static
Definition at line 18 of file Frontiere_dis_base.cpp.
zone_dis()
const Zone_dis_base & Frontiere_dis_base::zone_dis () const
Definition at line 149 of file Frontiere_dis_base.cpp.
{
  return la_zone_dis.valeur();
}
References la_zone_dis, and Ref_Zone_dis_base::valeur().
Referenced by Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_calc::completer(), Champ_front_calc_interne::completer(), Champ_front_contact_VEF::completer(), Champ_front_recyclage::get_coord_faces(), Echange_contact_PolyMAC::init_f_dist(), Echange_contact_PolyMAC_P0::init_fs_dist(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Champ_front_txyz::mettre_a_jour(), and Champ_front_base::zone_dis().
Member Data Documentation
info_obj
const Type_info Frontiere_dis_base::info_obj static
Definition at line 37 of file Frontiere_dis_base.h.
la_frontiere
Ref_Frontiere Frontiere_dis_base::la_frontiere protected
Definition at line 50 of file Frontiere_dis_base.h.
Referenced by associer_frontiere(), frontiere(), and le_nom().
la_zone_dis
Ref_Zone_dis_base Frontiere_dis_base::la_zone_dis protected
Definition at line 51 of file Frontiere_dis_base.h.
Referenced by associer_Zone_dis(), and zone_dis().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Frontiere_dis_base.h
src/Kernel/Framework/Frontiere_dis_base.cpp