TRUST: Lire_Tgrid Class Reference
Lire_Tgrid Class Reference
class Lire_Fichier
Lecture d'un fichier
#include <Lire_Tgrid.h>
Public Member Functions
Lire_Tgrid ()
~Lire_Tgrid ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Lecture d'un fichier
Avec 2 arguments nom1 et nom2 , lit l'objet du fichier nom2 dans l'objet nom1
Avec un seul argument nom1, interprete le fichier de nom nom1.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Lire_Tgrid & self_cast (Objet_U &)
static const Lire_Tgrid & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
appel a la methode printOn de la classe Interprete
Entree & readOn (Entree &) override
appel a la methode readOn de la classe Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
class Lire_Fichier
Lecture d'un fichier
Definition at line 30 of file Lire_Tgrid.h.
Constructor & Destructor Documentation
Lire_Tgrid()
Lire_Tgrid::Lire_Tgrid ()
Definition at line 39 of file Lire_Tgrid.cpp.
~Lire_Tgrid()
Lire_Tgrid::~Lire_Tgrid ()
Definition at line 39 of file Lire_Tgrid.cpp.
Member Function Documentation
cree_instance()
Objet_U * Lire_Tgrid::cree_instance () static
Definition at line 39 of file Lire_Tgrid.cpp.
duplique()
int Lire_Tgrid::duplique () const override virtual
Implements Objet_U.
Definition at line 39 of file Lire_Tgrid.cpp.
get_info()
const Type_info * Lire_Tgrid::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 39 of file Lire_Tgrid.cpp.
info()
const Type_info * Lire_Tgrid::info () static
Definition at line 39 of file Lire_Tgrid.cpp.
interpreter_()
Entree & Lire_Tgrid::interpreter_ (Entree & is) override virtual
Lecture d'un fichier
Avec 2 arguments nom1 et nom2 , lit l'objet du fichier nom2 dans l'objet nom1
Avec un seul argument nom1, interprete le fichier de nom nom1.
Returns
Entree&
Signification:
Contraintes:
< Numero premier element
< Nombre d'element
< Type de la zone (0=dead zone; 1=active zone; 32=inactive zone) ou 0))
< On saut le type s'il existe
< evite de lire la description de la balise (12
< Numero premier element
< Nombre d'element
< Type de zone (1:fluid ou 0x11:solid)
< Type des elements
< Numero du premier sommet
< Nombre de sommets
< Debut
< Fin
<))
< Numero premier element
< Nombre d'element
< Type de la zone (0=dead zone; 1=active zone; 32=inactive zone) ou 0))
< On saut le type s'il existe
< Debut int ideb=htoi(motlu);
< Fin int ifin=htoi(motlu);
< Type (1:fluid, Ox11:solid)
< Type cell (0:mixed,1:tri,2:tetra,3:quad,4:hexa,5:pyramid,6:wedge)
< Numero de la premiere face
< Nombre de faces
< Type de face ou 0))
< On saut le type s'il existe
< Debut
< Fin
< Type (2: interior, >2: boundary condition): ne semble pas vrai (voir page C-8)!
< Type face (0:mixed, 2:linear, 3:triangular, 4:quadrilateral) Depend du format:
< (
< On va lire des elements mixtes en esperant qu'ils sont de meme type
< On lit la premiere ligne
< On va lire des triangles donc les elements sont des tetras (4 sommets)
< On va lire des quadrangles donc les elements sont des hexas (8 sommets)
< On va lire des segments dont les elements sont des triangles (3 sommets)
< On va lire des segments dont les elements sont des quadrangles (4 sommets)
< premier element voisin de la face (nul si frontiere)
< deuxieme element voisin de la face (nul si frontiere) Debut Rajout Cyril MALOD : 15-06-2006
< Ce compteur sert a ne pas lire le "motlu" suivant
< Ce compteur sert a lire le "motlu" suivant
< Ce compteur sert a lire le "motlu" suivant
< On ne traite pas les elements -1 voisins des faces frontieres
<) ou))
<)
< Numero de la zone Attention le numero de la zone est en decimal ! int izone=htoi(motlu.suffix("("));
< Type de la zone
< Nom de la zone)())
Implements Interprete_geometrique_base.
Definition at line 237 of file Lire_Tgrid.cpp.
{
  Cerr << "Reading a mesh which comes from Tgrid" << finl;
  associer_domaine(is);
  Domaine& dom=domaine();
  DoubleTab& coord_sommets=dom.les_sommets();
// Declaration des variables
  int dim = -1;
  int nb_som = 0;
  int nb_elem = 0;
  int nb_face = 0;
  int nb_som_elem = 0;
  int type_elements = 0;
  int compteur = 0;
// Tableau de travail
  ArrOfInt nb_som_lu_elem;
  Motcle motlu;
// Gestion fichier
  Nom nom_fichier;
  is >> nom_fichier;
  decompression(nom_fichier);
  Cerr << "Reading of the file " << nom_fichier << " ..." << finl;
  EFichier lecture(nom_fichier);
// On teste tout de suite l'existence du fichier car s'il
// n'existe pas, cela bloque dans le eof();
  if (!lecture.good())
    {
      Cerr << "Problem to open the file " << nom_fichier << finl;
      Cerr << "There is maybe an error in the filename." << finl;
      exit();
    }
// Premiere lecture du fichier .msh
// pour trouver le nombre d'element car
// il est parfois place en fin de fichier !
  while (!lecture.eof())
    {
      lecture >> motlu;
      if (motlu=="(12")
        {
          lecture >> motlu;
          if (motlu=="(0")
            {
              lecture >> motlu;        //!< Numero premier element
              lecture >> motlu;        //!< Nombre d'element
              nb_elem=htoi(motlu);
              Cerr << "The total number of elements to read is " << nb_elem << finl;
              lecture >> motlu;        //!< Type de la zone (0=dead zone; 1=active zone; 32=inactive zone) ou 0))
              if (motlu!="0))") lecture >> motlu; //!< On saut le type s'il existe
              Zone une_zone;
              Zone& la_zone=dom.add(une_zone);
              la_zone.associer_domaine(dom);
            }
          else if (motlu=="(id") lecture >> motlu;        //!< evite de lire la description de la balise (12
          else
            {
              lecture >> motlu;        //!< Numero premier element
              lecture >> motlu;        //!< Nombre d'element
              lecture >> motlu;        //!< Type de zone (1:fluid ou 0x11:solid)
              lecture >> motlu;        //!< Type des elements
              if (motlu=="1))")
                {
// On lit des triangles
                  type_elements=1;
                  Cerr << "2D elements of type Triangle" << finl;
                }
              else if (motlu=="3))")
                {
// On lit des quadrangles
                  type_elements=3;
                  Cerr << "2D elements of type Quadrangle" << finl;
                }
              else if (motlu=="2))")
                {
// On lit des tetraedres
                  type_elements=2;
                  Cerr << "3D elements of type Tetrahedron" << finl;
                }
              else if (motlu=="4))")
                {
// On lit des hexaedres
                  type_elements=4;
                  Cerr << "3D elements of type Hexahedron" << finl;
                }
              else
                {
// On ne sait pas ce qu'on lit
                  Cerr << "Elements unknown !" << finl;
                  Cerr << "It should probably crashed !!!!!" << finl;
                }
              lecture.close();
            }
        }
    }
// Deuxieme lecture du fichier .msh
  EFichier fic(nom_fichier);
  while (!fic.eof())
    {
      fic >> motlu;
      if (motlu=="(0")
        {
          Cerr << "Reading a comment:" << finl;
          Cerr << motlu;
          va_a_la_parenthese_fermante(fic);
          Cerr << finl << finl;
        }
      else if (motlu=="(1")
        {
          Cerr << "Reading a header:" << finl;
          Cerr << motlu;
          va_a_la_parenthese_fermante(fic);
          Cerr << finl << finl;
        }
      else if (motlu=="(2")
        {
          Cerr << "Reading of the dimension of the case:" << finl;
          fic >> motlu;
          dim=atoi(motlu.prefix(")"));
          if (dim==3) Cerr << "Dimension 3." << finl;
          else if (dim==2) Cerr << "Dimension 2." << finl;
          else
            {
              Cerr << "Dimension " << dim << " of the mesh not provided." << finl;
              exit();
            }
          Cerr << finl;
        }
      else if (motlu=="(10")
        {
          fic >> motlu;
          if (motlu=="(0")
            {
              fic >> motlu;        //!< Numero du premier sommet
              fic >> motlu;        //!< Nombre de sommets
              nb_som=htoi(motlu);
              Cerr << "The total number of nodes to read is " << nb_som << finl;
// On dimensionne le tableau des sommets
              coord_sommets.resize(nb_som,dim);
// Depend du format
              fic >> motlu;
              Nom tmp=motlu;
              if (tmp==motlu.prefix("))"))
                fic >> motlu;
            }
          else
            {
              int izone=htoi(motlu.suffix("("));
              fic >> motlu;        //!< Debut
              int ideb=htoi(motlu);
              fic >> motlu;        //!< Fin
              int ifin=htoi(motlu);
              Cerr << ifin-ideb+1 << " nodes are read in the area " << izone << finl;
// Depend du format, on va donc a la paranthese ouvrante
              va_a_la_parenthese_ouvrante(fic);
              /*
                fic >> motlu;        // Type (0: virtual, 1:any, 2:boundary)
                if (motlu.prefix(")"))
                fic >> motlu;        // Dimension
                assert(htoi(motlu.prefix(")"))==dim);
                fic >> motlu;        //!< ( */
              for (int i=ideb-1; i<ifin; i++)
                for (int j=0; j<dim; j++)
                  fic >> coord_sommets(i,j);
              fic >> motlu;        //!< ))
            }
          Cerr << finl;
        }
      else if (motlu=="(12")
        {
          fic >> motlu;
          if (motlu=="(0")
            {
// Informations obtenues lors de la premiere lecture
              fic >> motlu;        //!< Numero premier element
              fic >> motlu;        //!< Nombre d'element
              fic >> motlu;        //!< Type de la zone (0=dead zone; 1=active zone; 32=inactive zone) ou 0))
              if (motlu!="0))") fic >> motlu; //!< On saut le type s'il existe
            }
          else
            {
              int izone=htoi(motlu.suffix("("));
              dom.zone(0).nommer((Nom)izone);
              fic >> motlu;        //!< Debut int ideb=htoi(motlu);
//
              fic >> motlu;        //!< Fin int ifin=htoi(motlu);
//
              fic >> motlu;        //!< Type (1:fluid, Ox11:solid)
              int type=htoi(motlu);
              Cerr << "The type of area " << izone << " is " << type << " (1:fluid, 17:solid)" << finl;
              fic >> motlu;        //!< Type cell (0:mixed,1:tri,2:tetra,3:quad,4:hexa,5:pyramid,6:wedge)
              if (motlu=="2))")
                {
// On lit bien des tetraedres
                  dom.zone(0).type_elem().typer("Tetraedre");
                }
              else if (motlu=="4))")
                {
// On lit bien des hexaedres
                  dom.zone(0).type_elem().typer("Hexaedre_VEF");
                }
              else if (motlu=="1))")
                {
// On lit bien des triangles
                  dom.zone(0).type_elem().typer("Triangle");
                }
              else if (motlu=="3))")
                {
// On lit bien des quadrangles
                  dom.zone(0).type_elem().typer("Quadrangle");
                }
              else
                {
                  Cerr << "Reading the elements is not provided in this interpreter." << finl;
                  Cerr << "Indeed, we read faces to reconstruct the elements." << finl;
                  Cerr << "Contact TRUST support." << finl;
                  exit();
                }
              dom.zone(0).type_elem().associer_zone(dom.zone(0));
            }
          Cerr << finl;
        }
      else if (motlu.debute_par("(13"))
        {
          motlu.suffix("(13");
          if (motlu=="")
            fic >> motlu;
          if (motlu=="(0")
            {
              fic >> motlu;        //!< Numero de la premiere face
              fic >> motlu;        //!< Nombre de faces
              nb_face=htoi(motlu);
              Cerr << "The total number of faces to read is " << nb_face << finl;
              fic >> motlu;        //!< Type de face ou 0))
              if (motlu != "0))") fic >> motlu;        //!< On saut le type s'il existe
            }
          else
            {
              int izone=htoi(motlu.suffix("("));
              fic >> motlu;        //!< Debut
              int ideb=htoi(motlu);
              fic >> motlu;        //!< Fin
              int ifin=htoi(motlu);
              fic >> motlu;        //!< Type (2: interior, >2: boundary condition): ne semble pas vrai (voir page C-8)!
              int type=htoi(motlu);
              fic >> motlu;        //!< Type face (0:mixed, 2:linear, 3:triangular, 4:quadrilateral) Depend du format:
//
              Nom tmp=motlu;
              int nb_som_face,mixte=0;
              if (tmp!=motlu.prefix(")"))
                fic >> tmp;        //!< (
              else
                motlu.prefix(")(");
              nb_som_face=htoi(motlu);
              if (nb_som_face==0)
                {
                  mixte=1;                //!< On va lire des elements mixtes en esperant qu'ils sont de meme type
                  fic >> motlu;        //!< On lit la premiere ligne
                  nb_som_face=htoi(motlu);
                }
              if (nb_som_face==3)
                nb_som_elem=4;         //!< On va lire des triangles donc les elements sont des tetras (4 sommets)
              else if (nb_som_face==4)
                nb_som_elem=8;        //!< On va lire des quadrangles donc les elements sont des hexas (8 sommets)
              else if (nb_som_face==2 && type_elements==1)
                nb_som_elem=3;        //!< On va lire des segments dont les elements sont des triangles (3 sommets)
              else if (nb_som_face==2 && type_elements==3)
                nb_som_elem=4;        //!< On va lire des segments dont les elements sont des quadrangles (4 sommets)
              else
                {
                  if (nb_som_face==0)
                    Cerr << "It seems that we try to read faces with different types..." << finl;
// if (nb_som_face==2)                                                        // N'est plus necessaire, vu qu'on sait lire
// Cerr << "Il semble que l'on essaie de lire un segment..." << finl;        // maintenant des segments
                  Cerr << "The case of faces that are not triangles or quadrangles" << finl;
                  Cerr << "or a mixture of several types of faces" << finl;
                  Cerr << "is not yet provided. Your mesh is not only composed" << finl;
                  Cerr << "of tetrahedra, hexahedra, triangles or quadrangles." << finl;
                  exit();
                }
// Tableaux de travail
              IntTab& les_elems=dom.zone(0).les_elems();
              if (les_elems.size()==0)
                {
// Si les_elems n'est pas dimensionne (1ere lecture de faces)
                  les_elems.resize(nb_elem,nb_som_elem);
// On initialise a -1 pour voir les sommets non definis
                  les_elems=-1;
                  nb_som_lu_elem.resize_array(nb_elem);
                  nb_som_lu_elem=0;
                }
              ArrOfInt elem(2),som(nb_som_face);
              int nb_face_lu=ifin-ideb+1;
              REF(Frontiere) nouveau_bord;
// On lit les sommets de la face et les 2 elements au contact de la face
              for (int i=0; i<nb_face_lu; i++)
                {
                  if (mixte && i>0)
                    {
                      fic >> motlu;
                      if (htoi(motlu)!=nb_som_face)
{
                          Cerr << "We read an element to " << htoi(motlu) << " faces." << finl;
                          Cerr << "So it was planned to read elements to " << nb_som_face << " faces."<< finl;
                          exit();
                        }
                    }
                  for (int j=0; j<nb_som_face; j++)
                    {
                      fic >> motlu;
                      som[j]=htoi(motlu)-1;
                    }
// Pour les hexaedres a cause de la numerotation TRUST, on inverse les sommets 2 et 3
                  if (nb_som_face==4)
                    {
                      int tmp2=som[2];
                      som[2]=som[3];
                      som[3]=tmp2;
                    }
                  fic >> motlu;        //!< premier element voisin de la face (nul si frontiere)
                  elem[0]=htoi(motlu)-1;
                  fic >> motlu;        //!< deuxieme element voisin de la face (nul si frontiere) Debut Rajout Cyril MALOD : 15-06-2006
//
                  Nom tmp2=motlu;
                  if (tmp2!=motlu.prefix("))"))
                    {
                      tmp2=motlu.prefix("))");
                      elem[1]=htoi(tmp2)-1;
                      compteur=1; //!< Ce compteur sert a ne pas lire le "motlu" suivant
                    }
                  else
                    {
                      if (tmp2!=motlu.prefix(")"))
{
                          tmp2=motlu.prefix(")");
                          elem[1]=htoi(motlu)-1;
                          compteur=-1; //!< Ce compteur sert a lire le "motlu" suivant
                        }
                      else
{
                          elem[1]=htoi(motlu)-1;
                          compteur=0; //!< Ce compteur sert a lire le "motlu" suivant
                        }
                    }
// elem(1)=htoi(motlu)-1;
// Fin Rajout Cyril MALOD : 15-06-2006
// Premier passage, on verifie bien qu'on lit une frontiere
                  if (i==0)
                    {
                      if (elem[0]<0 || elem[1]<0)
{
// C'est bien une frontiere donc on dimensionne le necessaire
                          type=3;
                          Cerr << nb_face_lu << " faces are read from the boundary number " << izone << finl;
                          nouveau_bord=dom.zone(0).faces_bord().add(Bord());
                          nouveau_bord->nommer((Nom)izone);
                          if (nb_som_face==3)
                            nouveau_bord->faces().typer(Faces::triangle_3D);
                          else if (nb_som_face==4)
                            nouveau_bord->faces().typer(Faces::quadrangle_3D);
                          else if (nb_som_face==2)
                            nouveau_bord->faces().typer(Faces::segment_2D);
                          else
{
                              Cerr << "Type of boundary face not provided for nb_som_face=" << nb_som_face << finl;
                              exit();
                            }
                          nouveau_bord->faces().dimensionner(nb_face_lu);
                        }
                      else
{
                          type=2;
                          Cerr << nb_face_lu << " internal faces are read in the area " << izone << finl;
                        }
                    }
// Les faces internes sont lues mais pas stockees, les faces frontieres sont stockees
                  if (type!=2)
                    for (int j=0; j<nb_som_face; j++)
                      nouveau_bord->faces().sommet(i,j)=som[j];
// On construit le tableau les_elems a partir des faces lues
                  for (int i2=0; i2<2; i2++)
                    {
                      if (elem[i2]>=0) //!< On ne traite pas les elements -1 voisins des faces frontieres
{
// Premier remplissage de elem(i)
                          if (nb_som_lu_elem[elem[i2]]==0)
{
                              for (int j=0; j<nb_som_face; j++)
                                les_elems(elem[i2],nb_som_lu_elem[elem[i2]]++)=som[j];
                            }
                          else
{
                              int face_opposee=1;
                              for (int j=0; j<nb_som_face; j++)
{
// On ajoute le sommet s'il n'est pas deja dans les_elems
                                  int k=0,trouve=0;
                                  while (k<nb_som_lu_elem[elem[i2]] && trouve==0)
{
                                      if (les_elems(elem[i2],k)==som[j])
{
                                          face_opposee=0;
                                          trouve=1;
                                        }
                                      else
                                        k++;
                                    }
// On ne complete que pour les tetraedres ou les triangles
                                  if ((trouve==0 && nb_som_face==3) || (trouve==0 && nb_som_face==2 && type_elements==1))
                                    les_elems(elem[i2],nb_som_lu_elem[elem[i2]]++)=som[j];
                                  assert(elem[i2]<nb_elem);
                                  if (nb_som_lu_elem[elem[i2]]>nb_som_elem)
{
                                      Cerr << "Problem on reading the element " << elem[i2] << finl;
                                      Cerr << "There is more than " << nb_som_elem << " nodes !" << finl;
                                      Cerr << "Check that the read file contains only tetrahedra or triangles" << finl;
                                      Cerr << "or contact TRUST support." << finl;
                                      exit();
                                    }
                                }
// On complete la face opposee de l'hexaedre ou du quadrangle
                              if ((nb_som_face==4 && face_opposee==1) || (nb_som_face==2 && face_opposee==1 && type_elements==3))
{
                                  for (int j=0; j<nb_som_face; j++)
                                    les_elems(elem[i2],nb_som_lu_elem[elem[i2]]++)=som[j];
                                }
                            }
                        }
                    }
                }
              if (compteur==0 || compteur==-1)
                {
                  fic >> motlu;        //!< ) ou ))
                  if (motlu==")" && compteur==0)
                    fic >> motlu;        //!< )
                }
            }
          Cerr << finl;
        }
      else if ((motlu=="(45") || (motlu=="(39"))
        {
          Cerr << "Reading of a name:" << finl;
          fic >> motlu;        //!< Numero de la zone Attention le numero de la zone est en decimal ! int izone=htoi(motlu.suffix("("));
//
//
          int izone=atoi(motlu.suffix("("));
          fic >> motlu;        //!< Type de la zone
          Nom Nomzone;
          fic >> Nomzone;        //!< Nom de la zone)())
          Nom nom_zone=Nomzone;
          nom_zone.prefix(")())");
          if (nom_zone==Nomzone)
            if (1)
              {
// retour a la ligne ?
                Nom app;
                fic >> app;
                Nomzone+=app;
                nom_zone=Nomzone;
                nom_zone.prefix(")())");
              }
          Cerr << "The area " << izone << " is called " << nom_zone << finl;
// On parcourt les bords pour renommer
          Bords& les_bords=dom.zone(0).faces_bord();
          les_bords.associer_zone(dom.zone(0));
          if (les_bords.est_vide())
            {
              Cerr << "Reading a name before reading the boundaries..." << finl;
              Cerr << "Case not provided, contact TRUST support." << finl;
              exit();
            }
          LIST_CURSEUR(Bord) curseur=les_bords;
          while (curseur)
            {
              if (curseur->le_nom()==(Nom)izone) curseur->nommer(nom_zone);
              ++curseur;
            }
// On parcourt les zones pour renommer
          Zones& les_zones=dom.zones();
          LIST_CURSEUR(Zone) curseur2=les_zones;
          while (curseur2)
            {
              if (curseur2->le_nom()==(Nom)izone)
                ref_cast(Zone,curseur2.valeur()).nommer(nom_zone);
              ++curseur2;
            }
          Cerr << finl;
        }
      else
        {
          if (motlu.debute_par("("))
            {
              Cerr << "Reading a tag:" << finl;
              Cerr << motlu;
              va_a_la_parenthese_fermante(fic);
              Cerr << finl << finl;
            }
          else if ( (motlu==" ") || (motlu=="") )
            {
              Cerr << "End of file ?" << finl;
            }
          else if (motlu!="??")
            {
              Cerr << "Tag " << motlu << " unrecognized." << finl;
              exit();
            }
        }
    }
// Verification si le tableau les_elems a ete rempli completement
  IntTab& les_elems=dom.zone(0).les_elems();
  for (int i=0; i<nb_elem; i++)
    for (int j=0; j<nb_som_elem; j++)
      if (les_elems(i,j)==-1)
        {
          Cerr << "The array of connectivity elements-nodes is wrong filled in Lire_Tgrid::interpreter." << finl;
          Cerr << "Contact TRUST support." << finl;
          exit();
        }
// On reordonne le domaine (utile surtout pour les hexaedres)
  dom.zone(0).type_elem().reordonner();
// Nettoie le domaine pour enlever les noeuds inutiles
// Mettre une methode a Domaine::nettoie
// Attention: les lignes suivantes pas compatibles avec TRUST < v1.4.6
  if ( (Process::nproc()==1) && (NettoieNoeuds::NettoiePasNoeuds==0) )
    NettoieNoeuds::nettoie(dom);
  return is;
}
References List_Bord::add(), Domaine::add(), Zone::associer_domaine(), Interprete_geometrique_base::associer_domaine(), Bords::associer_zone(), Elem_geom::associer_zone(), Cerr, Entree_Fichier_base::close(), compteur, decompression(), Interprete_geometrique_base::domaine(), Entree_Fichier_base::eof(), liste::est_vide(), Process::exit(), Zone::faces_bord(), finl, Entree_Fichier_base::good(), htoi(), Zone::les_elems(), Domaine::les_sommets(), LIST_CURSEUR, NettoieNoeuds::nettoie(), NettoieNoeuds::NettoiePasNoeuds, nom_fichier(), Objet_U::nommer(), Frontiere::nommer(), Zone::nommer(), Process::nproc(), Nom::prefix(), Faces::quadrangle_3D, REF, ref_cast, Elem_geom::reordonner(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::resize_array(), Faces::segment_2D, TRUSTVect< _TYPE_ >::size(), Faces::triangle_3D, Zone::type_elem(), Deriv_::typer(), va_a_la_parenthese_fermante(), va_a_la_parenthese_ouvrante(), Domaine::zone(), and Domaine::zones().
printOn()
Sortie & Lire_Tgrid::printOn (Sortie & x) const override protected virtual
appel a la methode printOn de la classe Interprete
Reimplemented from Interprete_geometrique_base.
Definition at line 54 of file Lire_Tgrid.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Lire_Tgrid::readOn (Entree & is) override protected virtual
appel a la methode readOn de la classe Interprete
Reimplemented from Interprete_geometrique_base.
Definition at line 73 of file Lire_Tgrid.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Lire_Tgrid & Lire_Tgrid::self_cast (const Objet_U & r) static
Definition at line 39 of file Lire_Tgrid.cpp.
self_cast() [2/2]
Lire_Tgrid & Lire_Tgrid::self_cast (Objet_U & r) static
Definition at line 39 of file Lire_Tgrid.cpp.
taille_memoire()
unsigned Lire_Tgrid::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 39 of file Lire_Tgrid.cpp.
Member Data Documentation
info_obj
const Type_info Lire_Tgrid::info_obj static
Definition at line 32 of file Lire_Tgrid.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Lire_Tgrid.h
src/Kernel/Geometrie/Lire_Tgrid.cpp