TRUST: IntListElem Class Reference
IntListElem Class Reference
#include <IntListElem.h>
Public Member Functions
IntListElem ()
Construit une liste vide.
IntListElem (const int x)
Construit le singleton (x).
IntListElem (const IntListElem &)
Constructeur par copie.
~IntListElem ()
destructeur
IntListElem & suivant ()
renvoie le suivant.
const IntListElem & suivant () const
renvoie le suivant.
int est_vide () const
renvoie 1 si la liste est vide
renvoie 0 sinon.
int est_dernier () const
renvoie 1 si il n'y a pas de suivant
renvoie 0 sinon.
int & valeur ()
renvoie le reel int precision.
int valeur () const
renvoie le reel int precision.
IntListElem & add (int)
insertion en queue
Protected Attributes
int data
IntListElem * suivant_
Friends
class IntList
int operator== (const IntListElem &, const IntListElem &)
Operateur de comparaison de deux listes.
Detailed Description
Definition at line 46 of file IntListElem.h.
Constructor & Destructor Documentation
IntListElem::IntListElem () [inline]
Construit une liste vide.
Definition at line 84 of file IntListElem.h.
References suivant_.
Referenced by add(), IntList::add(), IntList::IntList(), and IntListElem().
{
  suivant_=this;
}
IntListElem::IntListElem (const int x) [inline]
Construit le singleton (x).
Definition at line 103 of file IntListElem.h.
                                           : data(x), suivant_(0)
{}
IntListElem::IntListElem (const IntListElem & list)
Constructeur par copie.
Definition at line 43 of file IntListElem.cpp.
References data, est_vide(), IntListElem(), next(), and suivant_.
{
  if(list.est_vide() )
    {
      suivant_=this;
    }
  else
    {
      data=list.data;
      if(list.suivant_)
        {
          IntListElem* next = new IntListElem(*list.suivant_); //Recursif !!
          suivant_ = next;
        }
      else
        suivant_ =0;
    }
}
IntListElem::~IntListElem ()
destructeur
Definition at line 76 of file IntListElem.cpp.
References est_vide(), and suivant_.
{
// Cout << "Destruction de IntList" << finl;
  if (est_vide())
    suivant_=0;
  if(suivant_)
    {
// On ne garde pas la version delete suivant_ car sinon on est limite par le nombre d'appel recursif possible
// delete suivant_;
      IntListElem *poignee, *pr;
      pr=suivant_;
      suivant_=0;
      while(pr)
        {
          poignee=pr->suivant_;
          pr->suivant_=0;
          delete pr ;
          pr=poignee;
        }
    }
}
Member Function Documentation
IntListElem & IntListElem::add (int int_to_add)
insertion en queue
Returns:
Int_ListElem&
Signification: *this
Contraintes:
Reimplemented in IntList.
Definition at line 113 of file IntListElem.cpp.
References est_dernier(), IntListElem(), next(), and suivant_.
Referenced by IntList::add().
{
  assert(est_dernier());
  IntListElem* next=new IntListElem(int_to_add);
  suivant_ = next;
  return *this;
}
int IntListElem::est_dernier () const [inline]
renvoie 1 si il n'y a pas de suivant
renvoie 0 sinon.
Returns:
int
Signification: 1 si il n'y a pas de suivant, 0 sinon
Contraintes:
Definition at line 142 of file IntListElem.h.
References est_vide(), and suivant_.
Referenced by add(), IntList::add(), IntList_Curseur::operator++(), operator==(), and IntList::printOn().
{
  return ((est_vide()) || (suivant_==0) );
}
int IntListElem::est_vide () const [inline]
renvoie 1 si la liste est vide
renvoie 0 sinon.
Returns:
int
Signification: 1 si la liste est vide, 0 sinon
Contraintes:
Definition at line 121 of file IntListElem.h.
References suivant_.
Referenced by IntList::add(), Op_Rot_VEFP1B::ajouter(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), IntList::contient(), Op_Diff_RotRot::elements_pour_sommet(), est_dernier(), Op_Diff_VEF_Face_Penalise::faces_communes(), IntList::IntList(), IntList_Curseur::IntList_Curseur(), IntListElem(), IntList_Curseur::operator=(), IntList::operator=(), IntList::rang(), Op_Diff_VEF_Face_Penalise::reduction(), IntList::size(), Op_Diff_RotRot::sommets_pour_element(), Op_Diff_RotRot::Tri(), IntList::vide(), Op_Diff_VEF_Face_Penalise::voisinage(), and ~IntListElem().
{
  return suivant_==this;
}
const IntListElem & IntListElem::suivant () const [inline]
renvoie le suivant.
Returns:
const IntList&
Signification: liste sur l'element suivant
Contraintes:
Definition at line 202 of file IntListElem.h.
References suivant_.
{
  return *suivant_;
}
IntListElem & IntListElem::suivant () [inline]
renvoie le suivant.
Returns:
IntList&
Signification: liste sur l'element suivant
Contraintes: IntList_H
Definition at line 222 of file IntListElem.h.
References suivant_.
Referenced by IntList::add(), IntList_Curseur::operator++(), and IntList::suppr().
int IntListElem::valeur () const [inline]
renvoie le reel int precision.
Returns:
int&
Signification:
Contraintes:
Definition at line 182 of file IntListElem.h.
References data.
{
  return data;
}
int & IntListElem::valeur () [inline]
renvoie le reel int precision.
Returns:
int&
Signification:
Contraintes:
Definition at line 162 of file IntListElem.h.
References data.
Referenced by IntList::suppr(), and IntList_Curseur::valeur().
{
  return data;
}
Friends And Related Function Documentation
friend class IntList [friend]
Definition at line 50 of file IntListElem.h.
int operator== (const IntListElem & list1, const IntListElem & list2) [friend]
Operateur de comparaison de deux listes.
Returns:
int
Signification: 1 si les listes sont egales, 0 sinon
Contraintes:
Definition at line 140 of file IntListElem.cpp.
{
  int retour=1;
  if(list1.data != list2.data)
    retour= 0;
  if( (!list1.est_dernier()) && (list2.est_dernier()) )
    retour= 0;
  if( (list1.est_dernier()) && (!list2.est_dernier()) )
    retour= 0;
  if( (!list1.est_dernier()) && (!list2.est_dernier()) )
    retour= (*list1.suivant_ == *list2.suivant_);
  return retour;
}
Member Data Documentation
int IntListElem::data [protected]
Definition at line 66 of file IntListElem.h.
Referenced by IntList::add(), IntList::IntList(), IntListElem(), operator==(), IntList::suppr(), and valeur().
IntListElem* IntListElem::suivant_ [protected]
Definition at line 67 of file IntListElem.h.
Referenced by add(), IntList::add(), est_dernier(), est_vide(), IntList::IntList(), IntListElem(), IntList::operator=(), operator==(), suivant(), IntList::suppr(), IntList::vide(), and ~IntListElem().
The documentation for this class was generated from the following files:
src/Kernel/Math/IntListElem.h
src/Kernel/Math/IntListElem.cpp