TRUST: Reynolds_maille_Champ_Face Class Reference
Reynolds_maille_Champ_Face Class Reference
classe Reynolds_maille_Champ_Face
#include <Reynolds_maille_Champ_Face.h>
Public Member Functions
Reynolds_maille_Champ_Face ()
~Reynolds_maille_Champ_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_Face & vitesse () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Face &, const Champ_Don &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Reynolds_maille_Champ_Face & self_cast (Objet_U &)
static const
Reynolds_maille_Champ_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_Face vitesse_
Ref_Champ_Don nu_
Detailed Description
classe Reynolds_maille_Champ_Face
Definition at line 34 of file Reynolds_maille_Champ_Face.h.
Constructor & Destructor Documentation
Reynolds_maille_Champ_Face::Reynolds_maille_Champ_Face ()
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
Reynolds_maille_Champ_Face::~Reynolds_maille_Champ_Face ()
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
Member Function Documentation
void Reynolds_maille_Champ_Face::associer_champ (const Champ_Face & la_vitesse, const Champ_Don & la_viscosite_cinematique)
Definition at line 47 of file Reynolds_maille_Champ_Face.cpp.
References nu_, and vitesse_.
Referenced by VDF_discretisation::reynolds_maille().
{
  vitesse_= la_vitesse;
  nu_ = la_viscosite_cinematique;
}
Objet_U * Reynolds_maille_Champ_Face::cree_instance () [static]
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
int Reynolds_maille_Champ_Face::duplique () const [virtual]
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
const Type_info * Reynolds_maille_Champ_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
const Type_info * Reynolds_maille_Champ_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
void Reynolds_maille_Champ_Face::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
< Reynolds de maille Boucle sur les faces
< Reynolds_maille = |Uface| * taille_maille / nu_face
Reimplemented from Champ_Fonc_Face.
Definition at line 68 of file Reynolds_maille_Champ_Face.cpp.
References Champ_base::changer_temps(), dabs(), Zone_VF::face_surfaces(), Zone_VF::nb_faces(), nu_, valeur(), Champ_Don_base::valeurs(), vitesse_, Zone_VF::volumes_entrelaces(), and Champ_Fonc_Face::zone_vdf().
{
  const int& nb_faces = zone_vdf().nb_faces();
  DoubleTab& re = valeurs(); //!< Reynolds de maille Boucle sur les faces
//
  for (int face=0; face<nb_faces; face++)
    {
// Calcul de la viscosite face
      double nu_face = valeur(nu_->valeurs(), face, 0, zone_vdf());
// Calcul de la taille de maille entourant la face
      double taille_maille = zone_vdf().volumes_entrelaces()(face) / zone_vdf().face_surfaces(face);
// Calcul du Reynolds de maille
      re(face) = dabs(vitesse_->valeurs()(face)) * taille_maille / nu_face; //!< Reynolds_maille = |Uface| * taille_maille / nu_face
    }
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
Sortie & Reynolds_maille_Champ_Face::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Face.
Definition at line 34 of file Reynolds_maille_Champ_Face.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Reynolds_maille_Champ_Face::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Face.
Definition at line 42 of file Reynolds_maille_Champ_Face.cpp.
{
  return s ;
}
const Reynolds_maille_Champ_Face & Reynolds_maille_Champ_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
Reynolds_maille_Champ_Face & Reynolds_maille_Champ_Face::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
unsigned Reynolds_maille_Champ_Face::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_Face.
Definition at line 28 of file Reynolds_maille_Champ_Face.cpp.
const Champ_Face& Reynolds_maille_Champ_Face::vitesse () const [inline]
Definition at line 42 of file Reynolds_maille_Champ_Face.h.
References Ref_Champ_Face::valeur(), and vitesse_.
  {
    return vitesse_.valeur();
  };
Member Data Documentation
const Type_info Reynolds_maille_Champ_Face::info_obj [static]
Reimplemented from Champ_Fonc_Face.
Definition at line 38 of file Reynolds_maille_Champ_Face.h.
Ref_Champ_Don Reynolds_maille_Champ_Face::nu_ [protected]
Definition at line 52 of file Reynolds_maille_Champ_Face.h.
Referenced by associer_champ(), and mettre_a_jour().
Ref_Champ_Face Reynolds_maille_Champ_Face::vitesse_ [protected]
Definition at line 51 of file Reynolds_maille_Champ_Face.h.
Referenced by associer_champ(), mettre_a_jour(), and vitesse().
The documentation for this class was generated from the following files:
src/VDF/Champs/Reynolds_maille_Champ_Face.h
src/VDF/Champs/Reynolds_maille_Champ_Face.cpp