TRUST: Sortie_libre_pression_imposee_QC Class Reference
Sortie_libre_pression_imposee_QC Class Reference
classe Sortie_libre_pression_imposee
Cette classe derive de Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition de pression imposee.
L'objet de type Champ_bord le_champ_bord contient la pression et la
fonction flux_impose() renvoie les valeurs de cette pression.
champ_ext contient une valeur de la vitesse du fluide a l'exterieur
accessible par la methode val_ext()
#include <Sortie_libre_pression_imposee_QC.h>
Public Member Functions
~Sortie_libre_pression_imposee_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Sortie_libre_pression_imposee_QC ()
void completer ()
Complete les conditions aux limites.
Impose la masse volumique constante du milieu
physique de l'equation a d_rho.
int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_pression_imposee_QC sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
double flux_impose (int i) const
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere est considere constant sur tous
les elements de la frontiere.
La valeur du flux impose a la frontiere est egale
a la valeur du champ (considere constant) a la frontiere divise par d_rho.
double flux_impose (int i, int j) const
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere n'est PAS constant sur tous les elements
la frontiere.
double get_Pth ()
retourne la pression thermohydraulique
void set_Pth (double P)
fixe la pression thermohydraulique
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Sortie_libre_pression_imposee_QC & self_cast (Objet_U &)
static const
Sortie_libre_pression_imposee_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le champ de frontiere a partir d'un flot d'entree.
Type le_champ_ext en "Champ_front_uniforme".
Redimmensionne le_champ_ext en fonction de la dimension
de l'espace (dimension)
Protected Attributes
double Pthn
double d_rho
pression thermohydraulique au temps n, rho out
Detailed Description
classe Sortie_libre_pression_imposee
Cette classe derive de Neumann_sortie_libre
Elle represente une frontiere ouverte avec condition de pression imposee.
L'objet de type Champ_bord le_champ_bord contient la pression et la
fonction flux_impose() renvoie les valeurs de cette pression.
champ_ext contient une valeur de la vitesse du fluide a l'exterieur
accessible par la methode val_ext()
Definition at line 41 of file Sortie_libre_pression_imposee_QC.h.
Constructor & Destructor Documentation
Sortie_libre_pression_imposee_QC::~Sortie_libre_pression_imposee_QC ()
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
Sortie_libre_pression_imposee_QC::Sortie_libre_pression_imposee_QC ()
Definition at line 31 of file Sortie_libre_pression_imposee_QC.cpp.
: Pthn(1.e5), d_rho(-1) {}
Member Function Documentation
int Sortie_libre_pression_imposee_QC::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Sortie_libre_pression_imposee_QC sont compatibles
avec une equation dont le domaine est l'hydraulique (Navier_Stokes)
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 72 of file Sortie_libre_pression_imposee_QC.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Hydraulique="Hydraulique";
  Motcle indetermine="indetermine";
  if ( (dom_app==Hydraulique) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
void Sortie_libre_pression_imposee_QC::completer (void) [virtual]
Complete les conditions aux limites.
Impose la masse volumique constante du milieu
physique de l'equation a d_rho.
Reimplemented from Cond_lim_base.
Definition at line 128 of file Sortie_libre_pression_imposee_QC.cpp.
References d_rho, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), ref_cast, and sub_type.
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  if (sub_type(Champ_Uniforme,mil.masse_volumique()))
    {
      const Champ_Uniforme& rho=ref_cast(Champ_Uniforme,mil.masse_volumique());
      d_rho = rho(0,0);
    }
  else
    d_rho = -1;
}
Objet_U * Sortie_libre_pression_imposee_QC::cree_instance () [static]
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
int Sortie_libre_pression_imposee_QC::duplique () const [virtual]
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
double Sortie_libre_pression_imposee_QC::flux_impose (int i, int j) const [virtual]
Renvoie la valeur du flux impose sur la (i,j)-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere n'est PAS constant sur tous les elements
la frontiere.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 200 of file Sortie_libre_pression_imposee_QC.cpp.
References d_rho, DoubleTab::dimension(), Cond_lim_base::le_champ_front, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Pthn, and Champ_front::valeurs().
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  const Champ_base& rho=mil.masse_volumique();
  double rho_;
  if (d_rho==-1) rho_ = rho(i);
  else rho_ = d_rho;
  if (le_champ_front.valeurs().dimension(0)==1)
    return ( le_champ_front(0,j) - Pthn ) / rho_;
  else
    return ( le_champ_front(i,j) - Pthn ) / rho_;
}
double Sortie_libre_pression_imposee_QC::flux_impose (int i) const [virtual]
Renvoie la valeur du flux impose sur la i-eme composante
du champ representant le flux a la frontiere.
Le champ a la frontiere est considere constant sur tous
les elements de la frontiere.
La valeur du flux impose a la frontiere est egale
a la valeur du champ (considere constant) a la frontiere divise par d_rho.
Returns:
double
Signification: la valeur imposee sur la composante du champ specifiee
Contraintes:
Reimplemented from Neumann.
Definition at line 159 of file Sortie_libre_pression_imposee_QC.cpp.
References Cerr, d_rho, DoubleTab::dimension(), Process::exit(), finl, Cond_lim_base::le_champ_front, Cond_lim_base::ma_zone_cl_dis, Milieu_base::masse_volumique(), Pthn, DoubleVect::size(), and Champ_front::valeurs().
{
  const Milieu_base& mil=ma_zone_cl_dis->equation().milieu();
  const Champ_base& rho=mil.masse_volumique();
  double rho_;
  if (d_rho==-1) rho_ = rho(i);
  else rho_ = d_rho;
  if (le_champ_front.valeurs().size()==1)
    return ( le_champ_front(0,0) - Pthn ) / rho_;
  else if (le_champ_front.valeurs().dimension(1)==1)
    return ( le_champ_front(i,0) - Pthn ) / rho_;
  else
    Cerr << "Neumann::flux_impose erreur" << finl;
  Process::exit();
  return 0.;
}
const Type_info * Sortie_libre_pression_imposee_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
double Sortie_libre_pression_imposee_QC::get_Pth () [inline]
retourne la pression thermohydraulique
Definition at line 53 of file Sortie_libre_pression_imposee_QC.h.
References Pthn.
const Type_info * Sortie_libre_pression_imposee_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
Sortie & Sortie_libre_pression_imposee_QC::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 47 of file Sortie_libre_pression_imposee_QC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Sortie_libre_pression_imposee_QC::readOn (Entree & s) [protected, virtual]
Lit le champ de frontiere a partir d'un flot d'entree.
Type le_champ_ext en "Champ_front_uniforme".
Redimmensionne le_champ_ext en fonction de la dimension
de l'espace (dimension)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Neumann_sortie_libre.
Definition at line 103 of file Sortie_libre_pression_imposee_QC.cpp.
References Objet_U::dimension, Neumann_sortie_libre::le_champ_ext, Cond_lim_base::le_champ_front, DoubleTab::resize(), Deriv_::typer(), and Champ_front::valeurs().
{
  s >> le_champ_front;
  le_champ_ext.typer("Champ_front_uniforme");
  le_champ_ext.valeurs().resize(1,dimension);
  return s ;
}
const Sortie_libre_pression_imposee_QC & Sortie_libre_pression_imposee_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
Sortie_libre_pression_imposee_QC & Sortie_libre_pression_imposee_QC::self_cast (Objet_U & r) [static]
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
void Sortie_libre_pression_imposee_QC::set_Pth (double P) [inline]
fixe la pression thermohydraulique
Definition at line 54 of file Sortie_libre_pression_imposee_QC.h.
References Pthn.
Referenced by EDO_Pression_th_VEF::mettre_a_jour_CL(), and EDO_Pression_th_VDF::mettre_a_jour_CL().
unsigned Sortie_libre_pression_imposee_QC::taille_memoire () const [virtual]
Reimplemented from Neumann_sortie_libre.
Definition at line 29 of file Sortie_libre_pression_imposee_QC.cpp.
Member Data Documentation
double Sortie_libre_pression_imposee_QC::d_rho [protected]
pression thermohydraulique au temps n, rho out
Definition at line 57 of file Sortie_libre_pression_imposee_QC.h.
Referenced by completer(), and flux_impose().
const Type_info Sortie_libre_pression_imposee_QC::info_obj [static]
Reimplemented from Neumann_sortie_libre.
Definition at line 43 of file Sortie_libre_pression_imposee_QC.h.
double Sortie_libre_pression_imposee_QC::Pthn [protected]
Definition at line 57 of file Sortie_libre_pression_imposee_QC.h.
Referenced by flux_impose(), get_Pth(), and set_Pth().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Cond_Lim/Sortie_libre_pression_imposee_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Cond_Lim/Sortie_libre_pression_imposee_QC.cpp