TRUST: Masse_VDF_Face Class Reference
Masse_VDF_Face Class Reference
#include <Masse_VDF_Face.h>
Public Member Functions
Masse_VDF_Face ()
~Masse_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
DoubleTab & appliquer_impl (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Masse_VDF_Face & self_cast (Objet_U &)
static const Masse_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Private Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Detailed Description
Definition at line 37 of file Masse_VDF_Face.h.
Constructor & Destructor Documentation
Masse_VDF_Face::Masse_VDF_Face ()
Definition at line 31 of file Masse_VDF_Face.cpp.
Masse_VDF_Face::~Masse_VDF_Face ()
Definition at line 31 of file Masse_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Masse_VDF_Face::appliquer_impl (DoubleTab & sm) const [virtual]
Implements Solveur_Masse_base.
Definition at line 58 of file Masse_VDF_Face.cpp.
References Cerr, DoubleTab::dimension(), Process::exit(), finl, Cond_lim::frontiere_dis(), la_zone_Cl_VDF, la_zone_VDF, DoubleVect::line_size(), Front_VF::nb_faces(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Ref_Zone_VDF::valeur().
{
  assert(la_zone_VDF.non_nul());
  assert(la_zone_Cl_VDF.non_nul());
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const DoubleVect& porosite_face = zone_VDF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const int nb_faces = zone_VDF.nb_faces(), N = sm.line_size();
  if (sm.dimension(0) != nb_faces)
    {
      Cerr << "Masse_VDF_Face::appliquer :  erreur dans la taille de sm" << finl;
      exit();
    }
// Boucle sur les faces joint
// Boucle sur les bords
// Sur les faces qui portent des conditions aux limites de Dirichlet ou de Symetrie
// la vitesse normale reste egale a sa valeur initiale.
// Donc sur ces faces vpoint doit rester a 0.
  for (int n_bord=0; n_bord<zone_VDF.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
      const Cond_lim& la_cl = la_zone_Cl_VDF->les_conditions_limites(n_bord);
      const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = la_front_dis.num_premiere_face();
      const int nfin = ndeb + la_front_dis.nb_faces();
      if ( sub_type(Dirichlet,la_cl.valeur()) || sub_type(Dirichlet_homogene,la_cl.valeur()) )
// Pour les faces de Dirichlet on met sm a 0
        for (int f = ndeb; f < nfin; f++)
          for (int n = 0; n < N; n++)
            sm(f, n) = 0;
      else if (sub_type(Symetrie,la_cl.valeur()))
// Pour les faces de Symetrie on met vpoint a 0
        for (int f = ndeb; f < nfin; f++)
          for (int n = 0; n < N; n++)
            sm(f, n) = 0;
      else
        for (int f = ndeb; f < nfin; f++)
          for (int n = 0; n < N; n++)
            sm(f, n) /= (volumes_entrelaces(f) * porosite_face(f));
    }
// Boucle sur les faces internes
  const int ndeb = zone_VDF.premiere_face_int();
  for (int f = ndeb; f < nb_faces; f++)
    for (int n = 0; n < N; n++)
      sm(f, n) /= (volumes_entrelaces(f) * porosite_face(f));
// sm.echange_espace_virtuel();
// Debog::verifier("Masse_VDF_Face::appliquer sm",sm);
  return sm;
}
void Masse_VDF_Face::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 123 of file Masse_VDF_Face.cpp.
References la_zone_Cl_VDF, and ref_cast.
{
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, la_zone_Cl_dis_base);
}
void Masse_VDF_Face::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [virtual]
Implements Solveur_Masse_base.
Definition at line 118 of file Masse_VDF_Face.cpp.
References la_zone_VDF, and ref_cast.
{
  la_zone_VDF = ref_cast(Zone_VDF, la_zone_dis_base);
}
Objet_U * Masse_VDF_Face::cree_instance () [static]
Definition at line 31 of file Masse_VDF_Face.cpp.
int Masse_VDF_Face::duplique () const [virtual]
Implements Solveur_Masse_base.
Definition at line 31 of file Masse_VDF_Face.cpp.
const Type_info * Masse_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 31 of file Masse_VDF_Face.cpp.
const Type_info * Masse_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 31 of file Masse_VDF_Face.cpp.
Sortie & Masse_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 37 of file Masse_VDF_Face.cpp.
References Objet_U::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Masse_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Definition at line 45 of file Masse_VDF_Face.cpp.
{
  return s ;
}
const Masse_VDF_Face & Masse_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Solveur_Masse_base.
Definition at line 31 of file Masse_VDF_Face.cpp.
Masse_VDF_Face & Masse_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Solveur_Masse_base.
Definition at line 31 of file Masse_VDF_Face.cpp.
unsigned Masse_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 31 of file Masse_VDF_Face.cpp.
Member Data Documentation
const Type_info Masse_VDF_Face::info_obj [static]
Reimplemented from Solveur_Masse_base.
Definition at line 40 of file Masse_VDF_Face.h.
Ref_Zone_Cl_VDF Masse_VDF_Face::la_zone_Cl_VDF [private]
Definition at line 52 of file Masse_VDF_Face.h.
Referenced by appliquer_impl(), and associer_zone_cl_dis_base().
Ref_Zone_VDF Masse_VDF_Face::la_zone_VDF [private]
Definition at line 51 of file Masse_VDF_Face.h.
Referenced by appliquer_impl(), and associer_zone_dis_base().
The documentation for this class was generated from the following files:
src/VDF/Solveurs/Masse_VDF_Face.h
src/VDF/Solveurs/Masse_VDF_Face.cpp