TRUST: Source_Fluide_Dilatable_VDF_Proto Class Reference
Source_Fluide_Dilatable_VDF_Proto Class Reference
#include <Source_Fluide_Dilatable_VDF_Proto.h>
Protected Member Functions
void associer_zones_impl (const Zone_dis &zone, const Zone_Cl_dis &zone_cl)
void associer_volume_porosite_impl (const Zone_dis &zone, DoubleVect &volumes, DoubleVect &porosites)
void ajouter_impl (const DoubleVect &g, const double rho_m, const DoubleTab &tab_rho, DoubleTab &resu) const
Protected Attributes
Ref_Zone_Cl_VDF la_zone_Cl
Ref_Zone_VDF la_zone
Detailed Description
Definition at line 27 of file Source_Fluide_Dilatable_VDF_Proto.h.
Member Function Documentation
ajouter_impl()
void Source_Fluide_Dilatable_VDF_Proto::ajouter_impl (const DoubleVect & g, const double rho_m, const DoubleTab & tab_rho, DoubleTab & resu) const protected
Definition at line 36 of file Source_Fluide_Dilatable_VDF_Proto.cpp.
{
  const int nb_faces = la_zone->nb_faces(), premiere_face_interne = la_zone->premiere_face_int();
  const IntVect& orientation = la_zone->orientation();
  const DoubleVect& volumes_entrelaces = la_zone->volumes_entrelaces(), porosite_surf=la_zone->porosite_face();
  for (int num_cl=0 ; num_cl<la_zone->nb_front_Cl() ; num_cl++)
    {
      const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(num_cl);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      const int ndeb = le_bord.num_premiere_face(), nfin = ndeb + le_bord.nb_faces();
      if (sub_type(Dirichlet,la_cl.valeur()) || sub_type(Dirichlet_homogene,la_cl.valeur())) { /* Do nothing */ }
      else
        {
          for (int face=ndeb ; face<nfin ; face++)
            resu(face) += (tab_rho(face)-rho_m)*g(orientation(face)) * volumes_entrelaces(face)*porosite_surf(face);
        }
    }
  for (int face=premiere_face_interne ; face<nb_faces; face++)
    resu(face) += (tab_rho(face)-rho_m)*g(orientation(face)) * volumes_entrelaces(face)*porosite_surf(face);
}
References Cond_lim::frontiere_dis(), la_zone, la_zone_Cl, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Zone_VF::volumes_entrelaces().
Referenced by Source_QC_Gravite_VDF::ajouter_blocs(), and Source_WC_Gravite_VDF::ajouter_blocs().
associer_volume_porosite_impl()
void Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl (const Zone_dis & zone, DoubleVect & volumes, DoubleVect & porosites) protected
Definition at line 30 of file Source_Fluide_Dilatable_VDF_Proto.cpp.
{
  volumes.ref(ref_cast(Zone_VF,zone.valeur()).volumes());
  porosites.ref(ref_cast(Zone_VF,zone.valeur()).porosite_elem());
}
References TRUSTVect< _TYPE_ >::ref(), ref_cast, and Deriv_Zone_dis_base::valeur().
Referenced by Source_QC_Chaleur_VDF::associer_zones(), and Source_WC_Chaleur_VDF::associer_zones().
associer_zones_impl()
void Source_Fluide_Dilatable_VDF_Proto::associer_zones_impl (const Zone_dis & zone, const Zone_Cl_dis & zone_cl) protected
Definition at line 24 of file Source_Fluide_Dilatable_VDF_Proto.cpp.
{
  la_zone = ref_cast(Zone_VDF,zone.valeur());
  la_zone_Cl = ref_cast(Zone_Cl_VDF,zone_cl.valeur());
}
References la_zone, la_zone_Cl, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by Source_QC_Gravite_VDF::associer_zones(), and Source_WC_Gravite_VDF::associer_zones().
Member Data Documentation
la_zone
Ref_Zone_VDF Source_Fluide_Dilatable_VDF_Proto::la_zone protected
Definition at line 35 of file Source_Fluide_Dilatable_VDF_Proto.h.
Referenced by ajouter_impl(), and associer_zones_impl().
la_zone_Cl
Ref_Zone_Cl_VDF Source_Fluide_Dilatable_VDF_Proto::la_zone_Cl protected
Definition at line 34 of file Source_Fluide_Dilatable_VDF_Proto.h.
Referenced by ajouter_impl(), and associer_zones_impl().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/VDF/Source_Fluide_Dilatable_VDF_Proto.h
src/ThHyd/Dilatable/Common/VDF/Source_Fluide_Dilatable_VDF_Proto.cpp