TRUST: Changement_phase_Silver_Simpson Class Reference
Changement_phase_Silver_Simpson Class Reference
Correlation de changement de phase de Silver et Simpson (1949)
G_{kl} = lambda A_i alpha_k alpha_l sqrt(M / 2 pi R) (psat(T_k) / sqrt(T_k) - p / sqrt(T_l))
#include <Changement_phase_Silver_Simpson.h>
Public Member Functions
Changement_phase_Silver_Simpson ()
~Changement_phase_Silver_Simpson ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual double calculer (int k, int l, const double &dh, const double *alpha, const double *T, const double p, const double *nv, const double *lambda, const double *mu, const double *rho, const double *Cp, const Saturation_base &sat, DoubleTab &dT_G, DoubleTab &da_G, double &dp_G) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Changement_phase_Silver_Simpson & self_cast (Objet_U &)
static const
Changement_phase_Silver_Simpson & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double lambda_ec [2] = { 1, 1 }
double M
double alpha_min = 0.1
Detailed Description
Correlation de changement de phase de Silver et Simpson (1949)
G_{kl} = lambda A_i alpha_k alpha_l sqrt(M / 2 pi R) (psat(T_k) / sqrt(T_k) - p / sqrt(T_l))
Definition at line 35 of file Changement_phase_Silver_Simpson.h.
Constructor & Destructor Documentation
Changement_phase_Silver_Simpson::Changement_phase_Silver_Simpson ()
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
Changement_phase_Silver_Simpson::~Changement_phase_Silver_Simpson ()
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
Member Function Documentation
double Changement_phase_Silver_Simpson::calculer (int k, int l, const double & dh, const double * alpha, const double * T, const double p, const double * nv, const double * lambda, const double * mu, const double * rho, const double * Cp, const Saturation_base & sat, DoubleTab & dT_G, DoubleTab & da_G, double & dp_G) const [virtual]
Implements Changement_phase_base.
Definition at line 44 of file Changement_phase_Silver_Simpson.cpp.
References alpha_min, Saturation_base::dT_Psat(), lambda_ec, M, M_PI, max(), and Saturation_base::Psat().
{
  double T0 = 273.15,
         var_ak = max(alpha[k], alpha_min), var_al = std::pow(max(alpha[l], alpha_min), 1.5), var_a = var_ak * var_al, //partie variable en alpha
         var_T = sat.Psat(T[k]) / sqrt(T[k] + T0) - p / sqrt(T[l] + T0), //partie variable en (T, p)
         fac = lambda_ec[var_T < 0] * 4 / dh * sqrt(M / (2 * M_PI * 8.314)); //partie constante -> G = fac * var
  dT_G = 0, da_G = 0;
  dT_G(k) = fac * var_a * (sat.dT_Psat(T[k]) - 0.5 * sat.Psat(T[k]) / (T[k] + T0)) / sqrt(T[k] + T0);
  dT_G(l) = fac * var_a * 0.5 * p * std::pow(T[l] + T0, -1.5);
  da_G(k) = alpha[k] > alpha_min ? fac * var_T * var_al : 0;
  da_G(l) = alpha[l] > alpha_min ? fac * var_T * var_ak * 1.5 * sqrt(alpha[l]) : 0;
  dp_G = - fac * var_a / sqrt(T[l] + T0);
  return fac * var_a * var_T;
}
Objet_U * Changement_phase_Silver_Simpson::cree_instance () [static]
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
int Changement_phase_Silver_Simpson::duplique () const [virtual]
Implements Changement_phase_base.
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
const Type_info * Changement_phase_Silver_Simpson::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Changement_phase_base.
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
const Type_info * Changement_phase_Silver_Simpson::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Changement_phase_base.
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
Sortie & Changement_phase_Silver_Simpson::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Changement_phase_base.
Definition at line 28 of file Changement_phase_Silver_Simpson.cpp.
{
  return os;
}
Entree & Changement_phase_Silver_Simpson::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Changement_phase_base.
Definition at line 33 of file Changement_phase_Silver_Simpson.cpp.
References Param::ajouter(), alpha_min, lambda_ec, Param::lire_avec_accolades_depuis(), M, Objet_U::que_suis_je(), and Param::REQUIRED.
{
  Param param(que_suis_je());
  param.ajouter("lambda_e", &lambda_ec[0]);
  param.ajouter("lambda_c", &lambda_ec[1]);
  param.ajouter("alpha_min", &alpha_min);
  param.ajouter("M", &M, Param::REQUIRED);
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Changement_phase_Silver_Simpson & Changement_phase_Silver_Simpson::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Changement_phase_base.
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
Changement_phase_Silver_Simpson & Changement_phase_Silver_Simpson::self_cast (Objet_U & r) [static]
Reimplemented from Changement_phase_base.
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
unsigned Changement_phase_Silver_Simpson::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Changement_phase_Silver_Simpson.cpp.
Member Data Documentation
double Changement_phase_Silver_Simpson::alpha_min = 0.1 [protected]
Definition at line 45 of file Changement_phase_Silver_Simpson.h.
Referenced by calculer(), and readOn().
const Type_info Changement_phase_Silver_Simpson::info_obj [static]
Reimplemented from Changement_phase_base.
Definition at line 37 of file Changement_phase_Silver_Simpson.h.
double Changement_phase_Silver_Simpson::lambda_ec[2] = { 1, 1 } [protected]
Definition at line 43 of file Changement_phase_Silver_Simpson.h.
Referenced by calculer(), and readOn().
double Changement_phase_Silver_Simpson::M [protected]
Definition at line 44 of file Changement_phase_Silver_Simpson.h.
Referenced by calculer(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Changement_phase_Silver_Simpson.h
src/ThHyd/Multiphase/Correlations/Changement_phase_Silver_Simpson.cpp