TRUST: Op_Diff_VEF_Face Class Reference
Op_Diff_VEF_Face Class Reference
class Op_Diff_VEF_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
#include <Op_Diff_VEF_Face.h>
Public Member Functions
Op_Diff_VEF_Face ()
~Op_Diff_VEF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &)
associe le champ de diffusivite
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
void verifier () const
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_VEF_Face & self_cast (Objet_U &)
static const Op_Diff_VEF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_base diffusivite_
Detailed Description
class Op_Diff_VEF_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
Definition at line 43 of file Op_Diff_VEF_Face.h.
Constructor & Destructor Documentation
Op_Diff_VEF_Face::Op_Diff_VEF_Face ()
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
Op_Diff_VEF_Face::~Op_Diff_VEF_Face ()
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
Member Function Documentation
DoubleTab & Op_Diff_VEF_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const [virtual]
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEF_Face_Penalise, and Op_Diff_VEF_Face_Stab.
Definition at line 616 of file Op_Diff_VEF_Face.cpp.
References ajouter_cas_multi_scalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), DoubleTab::dimension(), MorEqn::equation(), Operateur_base::flux_bords_, Equation_base::inconnue(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), multi_scalaire, Field_base::nature_du_champ(), DoubleTab::nb_dim(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), scalaire, Deriv_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Ref_Zone_Cl_VEF::valeur(), and vectoriel.
Referenced by calculer().
{
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  int nb_comp = 1;
  int nb_dim = resu.nb_dim();
  if(nb_dim==2)
    nb_comp=resu.dimension(1);
  DoubleTab nu;
  DoubleTab tab_inconnue;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  const DoubleTab& inconnue=modif_par_porosite_si_flag(inconnue_org,tab_inconnue,marq,porosite_face);
  const Champ_base& inco = equation().inconnue().valeur();
  const Nature_du_champ nature_champ = inco.nature_du_champ();
  if(nature_champ==scalaire)
    ajouter_cas_scalaire(inconnue, resu, flux_bords_, nu, zone_Cl_VEF, zone_VEF);
  else if (nature_champ==vectoriel)
    ajouter_cas_vectoriel(inconnue, resu, flux_bords_, nu, zone_Cl_VEF, zone_VEF,nb_comp);
  else if (nature_champ==multi_scalaire)
    ajouter_cas_multi_scalaire(inconnue, resu, flux_bords_, nu, zone_Cl_VEF, zone_VEF,nb_comp);
  modifier_flux(*this);
  return resu;
}
void Op_Diff_VEF_Face::ajouter_cas_multi_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, int nb_comp) const
< face reelle
< face reelle
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 422 of file Op_Diff_VEF_Face.cpp.
References Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, DoubleTab::resize(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by ajouter().
{
  const IntTab& elemfaces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i0,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  int n_bord;
  double valA,flux0;
  DoubleVect n(Objet_U::dimension);
  DoubleTrav Tgrad(Objet_U::dimension,Objet_U::dimension);
// On dimensionne et initialise le tableau des bilans de flux:
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nb_comp);
  tab_flux_bords=0.;
  assert(nb_comp>1);
  int nb_bords=zone_VEF.nb_front_Cl();
  int ind_face;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elemfaces = zone_VEF.elem_faces();
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (ind_face=num1; ind_face<nb_faces_bord_reel; ind_face++)
            {
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              num_face = le_bord.num_face(ind_face);
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face, kk);
                  for (i0=0; i0<nb_faces_elem; i0++)
                    {
                      if ( ( (j= elemfaces(elem,i0)) > num_face ) && (j != fac_asso ) )
{
                          for (int nc=0; nc<nb_comp; nc++)
{
                              valA = viscA(num_face,j,elem,nu(elem,nc));
                              resu(num_face,nc)+=valA*inconnue(j,nc);
                              resu(num_face,nc)-=valA*inconnue(num_face,nc);
                              if(j<nb_faces) //!< face reelle
{
//
                                  resu(j,nc)+=0.5*valA*inconnue(num_face,nc);
                                  resu(j,nc)-=0.5*valA*inconnue(j,nc);
                                }
                            }
                        }
                    }
                }
            }
        }//!< fin if periodique
      else
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem=face_voisins(num_face,0);
// Boucle sur les faces :
              for (int i=0; i<nb_faces_elem; i++)
                if (( (j= elemfaces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                  {
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        valA = viscA(num_face,j,elem,nu(elem,nc));
                        if (ind_face<nb_faces_bord_reel)
{
                            double flux=valA*(inconnue(j,nc)-inconnue(num_face,nc));
                            resu(num_face,nc)+=flux;
                            tab_flux_bords(num_face,nc)-=flux;
                          }
                        if(j<nb_faces) //!< face reelle
{
                            resu(j,nc)+=valA*inconnue(num_face,nc);
                            resu(j,nc)-=valA*inconnue(j,nc);
                          }
                      }
                  }
            }
        }
    }//Fin for n_bord
// On traite les faces internes
  for (num_face=zone_VEF.premiere_face_int(); num_face<nb_faces; num_face++)
    {
      for (int k=0; k<2; k++)
        {
          int elem = face_voisins(num_face,k);
          for (i0=0; i0<nb_faces_elem; i0++)
            {
              if ( (j= elemfaces(elem,i0)) > num_face )
                {
                  int el1,el2;
                  int contrib=1;
                  if(j>=nb_faces) //!< C'est une face virtuelle
                    {
                      el1 = face_voisins(j,0);
                      el2 = face_voisins(j,1);
                      if((el1==-1)||(el2==-1))
                        contrib=0;
                    }
                  if(contrib)
                    {
                      for (int nc=0; nc<nb_comp; nc++)
{
                          valA = viscA(num_face,j,elem,nu(elem,nc));
                          resu(num_face,nc)+=valA*inconnue(j,nc);
                          resu(num_face,nc)-=valA*inconnue(num_face,nc);
                          if(j<nb_faces) //!< On traite les faces reelles
{
                              resu(j,nc)+=valA*inconnue(num_face,nc);
                              resu(j,nc)-=valA*inconnue(j,nc);
                            }
                          else
{
// La face j est virtuelle
                            }
                        }
                    }
                }
            }
        }
    }//!< Fin faces internes
// On se base sur ce qui est fait pour le cas scalaire
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  flux0=la_cl_paroi.flux_impose(face-ndeb,nc)*zone_VEF.surface(face);
                  resu(face,nc) += flux0;
                  tab_flux_bords(face,nc) = flux0;
                }
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  flux0=la_cl_paroi.h_imp(face-ndeb,nc)*(la_cl_paroi.T_ext(face-ndeb,nc)-inconnue(face,nc))*zone_VEF.surface(face);
                  resu(face,nc) += flux0;
                  tab_flux_bords(face,nc) = flux0;
                }
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            for (int nc=0; nc<nb_comp; nc++)
              tab_flux_bords(face,nc) = 0.;
        }
    }
}
void Op_Diff_VEF_Face::ajouter_cas_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF) const
< face reelle
< Il n'y a qu'une seule composante, donc on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
< face reelle
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 79 of file Op_Diff_VEF_Face.cpp.
References Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, DoubleTab::resize(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by ajouter().
{
  const IntTab& elemfaces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double valA,flux;
  int n_bord, ind_face;
  int nb_bords=zone_VEF.nb_front_Cl();
// On dimensionne et initialise le tableau des bilans de flux:
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),1);
  tab_flux_bords=0.;
  const int& premiere_face_int=zone_VEF.premiere_face_int();
// On traite les faces bord
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elemfaces = zone_VEF.elem_faces();
      int num1=0;
      int num2=le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (ind_face=num1; ind_face<nb_faces_bord_reel; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face,kk);
                  for (i=0; i<nb_faces_elem; i++)
                    {
                      if ( ( (j= elemfaces(elem,i)) > num_face ) && (j != fac_asso) )
{
                          valA = viscA(num_face,j,elem,nu(elem));
                          resu(num_face)+=valA*inconnue(j);
                          resu(num_face)-=valA*inconnue(num_face);
                          if(j<nb_faces) //!< face reelle
{
                              resu(j)+=0.5*valA*inconnue(num_face);
                              resu(j)-=0.5*valA*inconnue(j);
                            }
                        }
                    }
                }
            }
        }
      else   //!< Il n'y a qu'une seule composante, donc on traite une equation scalaire (pas la vitesse) on a pas a utiliser le tau tangentiel (les lois de paroi thermiques ne calculent pas d'echange turbulent a la paroi pour l'instant
//
//
//
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if (( (j= elemfaces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                    {
                      valA = viscA(num_face,j,elem,nu(elem));
                      if (ind_face<nb_faces_bord_reel)
{
                          flux=valA*(inconnue(j)-inconnue(num_face));
// PL : c'est bien un - ici pour flux_bords. Cette valeur est ensuite
// ecrasee pour les bords avec Neumann et ne sert donc que pour les bords
// avec Dirichlet ou le volume de controle est nul
                          tab_flux_bords(num_face,0)-=flux;
                          resu(num_face)+=flux;
                        }
                      if(j<nb_faces) //!< face reelle
{
                          flux=valA*(inconnue(num_face)-inconnue(j));
                          if (j<premiere_face_int)
                            tab_flux_bords(j,0)-=flux;
                          resu(j)+=flux;
                        }
                    }
                }
            }
        }
    }
// Faces internes :
  for (num_face=premiere_face_int; num_face<nb_faces; num_face++)
    {
      for (int k=0; k<2; k++)
        {
          int elem = face_voisins(num_face,k);
          {
            for (i=0; i<nb_faces_elem; i++)
              {
                j=elemfaces(elem,i);
                if ( j  > num_face )
                  {
                    int el1,el2;
                    int contrib=1;
                    if(j>=nb_faces) //!< C'est une face virtuelle
                      {
                        el1 = face_voisins(j,0);
                        el2 = face_voisins(j,1);
                        if((el1==-1)||(el2==-1))
                          contrib=0;
                      }
                    if(contrib)
                      {
                        valA = viscA(num_face,j,elem,nu(elem));
                        resu(num_face)+=valA*inconnue(j);
                        resu(num_face)-=valA*inconnue(num_face);
                        if(j<nb_faces) //!< On traite les faces reelles
{
                            resu(j)+=valA*inconnue(num_face);
                            resu(j)-=valA*inconnue(j);
                          }
                      }
                  }
              }
          }
        }
    }
// Neumann :
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              flux=la_cl_paroi.flux_impose(face-ndeb)*zone_VEF.surface(face);
              resu[face] += flux;
              tab_flux_bords(face,0) = flux;
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              flux=la_cl_paroi.h_imp(face-ndeb)*(la_cl_paroi.T_ext(face-ndeb)-inconnue(face))*zone_VEF.surface(face);
              resu[face] += flux;
              tab_flux_bords(face,0) = flux;
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            tab_flux_bords(face,0) = 0.;
        }
    }
}
void Op_Diff_VEF_Face::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Zone_Cl_VEF & zone_Cl_VEF, const Zone_VEF & zone_VEF, int nb_comp) const
< face reelle
< face reelle
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 258 of file Op_Diff_VEF_Face.cpp.
References Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_bord(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, DoubleTab::resize(), sub_type, Deriv_Cond_lim_base::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by ajouter().
{
  const IntTab& elemfaces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int i0,j,num_face;
  int nb_faces = zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  int n_bord0;
  double valA;//,flux;
  DoubleVect n(Objet_U::dimension);
  DoubleTrav Tgrad(Objet_U::dimension,Objet_U::dimension);
// On dimensionne et initialise le tableau des bilans de flux:
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nb_comp);
  tab_flux_bords=0.;
  assert(nb_comp>1);
  int nb_bords=zone_VEF.nb_front_Cl();
  int ind_face;
  for (n_bord0=0; n_bord0<nb_bords; n_bord0++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord0);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elemfaces = zone_VEF.elem_faces();
      int num1 = 0;
      int num2 = le_bord.nb_faces_tot();
      int nb_faces_bord_reel = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (ind_face=num1; ind_face<nb_faces_bord_reel; ind_face++)
            {
              fac_asso = la_cl_perio.face_associee(ind_face);
              fac_asso = le_bord.num_face(fac_asso);
              num_face = le_bord.num_face(ind_face);
              for (int kk=0; kk<2; kk++)
                {
                  int elem = face_voisins(num_face, kk);
                  for (i0=0; i0<nb_faces_elem; i0++)
                    {
                      if ( ( (j= elemfaces(elem,i0)) > num_face ) && (j != fac_asso ) )
{
                          valA = viscA(num_face,j,elem,nu(elem));
                          for (int nc=0; nc<nb_comp; nc++)
{
                              resu(num_face,nc)+=valA*inconnue(j,nc);
                              resu(num_face,nc)-=valA*inconnue(num_face,nc);
// resu(num_face,nc)+=valA*inconnue(j,nc)*porosite_face(num_face);
// resu(num_face,nc)-=valA*inconnue(num_face,nc)*porosite_face(num_face);
                              if(j<nb_faces) //!< face reelle
{
//
                                  resu(j,nc)+=0.5*valA*inconnue(num_face,nc);
                                  resu(j,nc)-=0.5*valA*inconnue(j,nc);
// resu(j,nc)+=0.5*valA*inconnue(num_face,nc)*porosite_face(j);
// resu(j,nc)-=0.5*valA*inconnue(j,nc)*porosite_face(j);
                                }
                            }
                        }
                    }
                }
            }
        }//!< fin if periodique
      else
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              num_face = le_bord.num_face(ind_face);
              int elem=face_voisins(num_face,0);
// Boucle sur les faces :
              for (int i=0; i<nb_faces_elem; i++)
                if (( (j= elemfaces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                  {
                    valA = viscA(num_face,j,elem,nu(elem));
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        double flux=valA*(inconnue(j,nc)-inconnue(num_face,nc));
                        if (ind_face<nb_faces_bord_reel)
{
                            resu(num_face,nc)+=flux;
                            tab_flux_bords(num_face,nc)+=flux;
                          }
                        if(j<nb_faces) //!< face reelle
{
                            resu(j,nc)-=flux;
                          }
                      }
                  }
            }
        }
    }//Fin for n_bord
// On traite les faces internes
  for (num_face=zone_VEF.premiere_face_int(); num_face<nb_faces; num_face++)
    {
      for (int k=0; k<2; k++)
        {
          int elem = face_voisins(num_face,k);
          for (i0=0; i0<nb_faces_elem; i0++)
            {
              if ( (j= elemfaces(elem,i0)) > num_face )
                {
                  int el1,el2;
                  int contrib=1;
                  if(j>=nb_faces) //!< C'est une face virtuelle
                    {
                      el1 = face_voisins(j,0);
                      el2 = face_voisins(j,1);
                      if((el1==-1)||(el2==-1))
                        contrib=0;
                    }
                  if(contrib)
                    {
                      valA = viscA(num_face,j,elem,nu(elem));
                      for (int nc=0; nc<nb_comp; nc++)
{
// resu(num_face,nc)+=valA*inconnue(j,nc)*porosite_face(num_face);
// resu(num_face,nc)-=valA*inconnue(num_face,nc)*porosite_face(num_face);
                          resu(num_face,nc)+=valA*inconnue(j,nc);
                          resu(num_face,nc)-=valA*inconnue(num_face,nc);
                          if(j<nb_faces) //!< On traite les faces reelles
{
// resu(j,nc)+=valA*inconnue(num_face,nc)*porosite_face(j);
// resu(j,nc)-=valA*inconnue(j,nc)*porosite_face(j);
                              resu(j,nc)+=valA*inconnue(num_face,nc);
                              resu(j,nc)-=valA*inconnue(j,nc);
                            }
                          else
{
// La face j est virtuelle
                            }
                        }
                    }
                }
            }
        }
    }//!< Fin faces internes
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Symetrie,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            tab_flux_bords(face,0) = 0.;
        }
    }
}
void Op_Diff_VEF_Face::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
Reimplemented in Op_Diff_VEFP1NCP1B_Face, and Op_Diff_VEF_Face_Stab.
Definition at line 658 of file Op_Diff_VEF_Face.cpp.
References DoubleTab::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), DoubleTab::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_VEF::valeur(), Ref_Zone_Cl_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
{
  modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int n1 = zone_VEF.nb_faces();
  int nb_comp = 1;
  int nb_dim = transporte.nb_dim();
  DoubleTab nu;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
  if (!marq)
    porosite_eventuelle=1;
  if(nb_dim==2)
    nb_comp=transporte.dimension(1);
  int i,j,num_face;
  int elem1,elem2;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double val;
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
          int num2b=num1+le_bord.nb_faces()/2;
          for (num_face=num1; num_face<num2b; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              elem2 = face_voisins(num_face,1);
              fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j=elem_faces(elem1,i)) > num_face )
                    {
                      val = viscA(num_face,j,elem1,nu(elem1));
                      for (int nc=0; nc<nb_comp; nc++)
{
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                          matrice(n0,j0)-=val*porosite_eventuelle(j);
                          matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                          matrice(j0,j0)+=val*porosite_eventuelle(j);
                        }
                    }
                  if (elem2!=-1)
                    if ( (j=elem_faces(elem2,i)) > num_face )
                      {
                        val= viscA(num_face,j,elem2,nu(elem2));
                        for (int nc=0; nc<nb_comp; nc++)
{
                            int n0=num_face*nb_comp+nc;
                            int j0=j*nb_comp+nc;
                            int  n0perio=fac_asso*nb_comp+nc;
                            matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                            matrice(n0,j0)-=val*porosite_eventuelle(j);
                            matrice(j0,n0perio)-=val*porosite_eventuelle(num_face);
                            matrice(j0,j0)+=val*porosite_eventuelle(j);
                          }
                      }
                }
            }
        }
      else
        {
          for (num_face=num1; num_face<num2; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem1,i)) > num_face )
                    {
                      val = viscA(num_face,j,elem1,nu(elem1));
                      for (int nc=0; nc<nb_comp; nc++)
{
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                          matrice(n0,j0)-=val*porosite_eventuelle(j);
                          matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                          matrice(j0,j0)+=val*porosite_eventuelle(j);
                        }
                    }
                }
            }
        }
    }
  int n0 = zone_VEF.premiere_face_int();
  for (num_face=n0; num_face<n1; num_face++)
    {
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
      for (i=0; i<nb_faces_elem; i++)
        {
          if ( (j=elem_faces(elem1,i)) > num_face )
            {
              val = viscA(num_face,j,elem1,nu(elem1));
              for (int nc=0; nc<nb_comp; nc++)
                {
                  int nn0=num_face*nb_comp+nc;
                  int j0=j*nb_comp+nc;
                  matrice(nn0,nn0)+=val*porosite_eventuelle(num_face);
                  matrice(nn0,j0)-=val*porosite_eventuelle(j);
                  matrice(j0,nn0)-=val*porosite_eventuelle(num_face);
                  matrice(j0,j0)+=val*porosite_eventuelle(j);
                }
            }
          if (elem2!=-1)
            if ( (j=elem_faces(elem2,i)) > num_face )
              {
                val= viscA(num_face,j,elem2,nu(elem2));
                for (int nc=0; nc<nb_comp; nc++)
                  {
                    int nn0=num_face*nb_comp+nc;
                    int j0=j*nb_comp+nc;
                    matrice(nn0,nn0)+=val*porosite_eventuelle(num_face);
                    matrice(nn0,j0)-=val*porosite_eventuelle(j);
                    matrice(j0,nn0)-=val*porosite_eventuelle(num_face);
                    matrice(j0,j0)+=val*porosite_eventuelle(j);
                  }
              }
        }
    }
// Neumann :
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = le_bord.num_premiere_face();
          int nfin = ndeb + le_bord.nb_faces();
          for (int face=ndeb; face<nfin; face++)
            {
              matrice(face,face) += la_cl_paroi.h_imp(face-ndeb)*zone_VEF.face_surfaces(face);
            }
        }
      else if (sub_type(Neumann_homogene,la_cl.valeur())
               || sub_type(Symetrie,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
        }
    }
  modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
}
void Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
Reimplemented in Op_Diff_VEF_Face_Stab.
Definition at line 848 of file Op_Diff_VEF_Face.cpp.
References DoubleTab::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), DoubleTab::nb_dim(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_VEF::valeur(), Ref_Zone_Cl_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
{
  modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
  remplir_nu(nu_);
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int n1 = zone_VEF.nb_faces();
  int nb_comp = 1;
  int nb_dim = transporte.nb_dim();
  DoubleTab nu;
  int marq=phi_psi_diffuse(equation());
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
  if (!marq)
    porosite_eventuelle=1;
  if(nb_dim==2)
    nb_comp=transporte.dimension(1);
  int i,j,num_face;
  int elem1,elem2;
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  double val;
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
// on ne parcourt que la moitie des faces periodiques
// on copiera a la fin le resultat dans la face associe..
          int num2b=num1+le_bord.nb_faces()/2;
          for (num_face=num1; num_face<num2b; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              elem2 = face_voisins(num_face,1);
              fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j=elem_faces(elem1,i)) > num_face )
                    {
                      for (int nc=0; nc<nb_comp; nc++)
{
                          val = viscA(num_face,j,elem1,nu(elem1,nc));
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                          matrice(n0,j0)-=val*porosite_eventuelle(j);
                          matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                          matrice(j0,j0)+=val*porosite_eventuelle(j);
                        }
                    }
                  if (elem2!=-1)
                    if ( (j=elem_faces(elem2,i)) > num_face )
                      {
                        for (int nc=0; nc<nb_comp; nc++)
{
                            val = viscA(num_face,j,elem2,nu(elem1,nc));
                            int n0=num_face*nb_comp+nc;
                            int j0=j*nb_comp+nc;
                            int  n0perio=fac_asso*nb_comp+nc;
                            matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                            matrice(n0,j0)-=val*porosite_eventuelle(j);
                            matrice(j0,n0perio)-=val*porosite_eventuelle(num_face);
                            matrice(j0,j0)+=val*porosite_eventuelle(j);
                          }
                      }
                }
            }
        }
      else
        {
          for (num_face=num1; num_face<num2; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                {
                  if ( (j= elem_faces(elem1,i)) > num_face )
                    {
                      for (int nc=0; nc<nb_comp; nc++)
{
                          val = viscA(num_face,j,elem1,nu(elem1,nc));
                          int n0=num_face*nb_comp+nc;
                          int j0=j*nb_comp+nc;
                          matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                          matrice(n0,j0)-=val*porosite_eventuelle(j);
                          matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                          matrice(j0,j0)+=val*porosite_eventuelle(j);
                        }
                    }
                }
            }
        }
    }
  for (num_face=zone_VEF.premiere_face_int(); num_face<n1; num_face++)
    {
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
      for (i=0; i<nb_faces_elem; i++)
        {
          if ( (j=elem_faces(elem1,i)) > num_face )
            {
              for (int nc=0; nc<nb_comp; nc++)
                {
                  val = viscA(num_face,j,elem1,nu(elem1,nc));
                  int n0=num_face*nb_comp+nc;
                  int j0=j*nb_comp+nc;
                  matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                  matrice(n0,j0)-=val*porosite_eventuelle(j);
                  matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                  matrice(j0,j0)+=val*porosite_eventuelle(j);
                }
            }
          if (elem2!=-1)
            if ( (j=elem_faces(elem2,i)) > num_face )
              {
                for (int nc=0; nc<nb_comp; nc++)
                  {
                    val= viscA(num_face,j,elem2,nu(elem2,nc));
                    int n0=num_face*nb_comp+nc;
                    int j0=j*nb_comp+nc;
                    matrice(n0,n0)+=val*porosite_eventuelle(num_face);
                    matrice(n0,j0)-=val*porosite_eventuelle(j);
                    matrice(j0,n0)-=val*porosite_eventuelle(num_face);
                    matrice(j0,j0)+=val*porosite_eventuelle(j);
                  }
              }
        }
    }
  modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
}
void Op_Diff_VEF_Face::associer_diffusivite (const Champ_base & diffu) [virtual]
associe le champ de diffusivite
Implements Operateur_Diff_base.
Definition at line 64 of file Op_Diff_VEF_Face.cpp.
References diffusivite_.
{
  diffusivite_ = diffu;
}
DoubleTab & Op_Diff_VEF_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const [virtual]
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, and Op_Diff_VEF_Face_Penalise.
Definition at line 650 of file Op_Diff_VEF_Face.cpp.
References ajouter().
Referenced by verifier().
{
  resu = 0;
  return ajouter(inconnue,resu);
}
void Op_Diff_VEF_Face::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, and Op_Diff_VEF_Face_Stab.
Definition at line 69 of file Op_Diff_VEF_Face.cpp.
{
  Operateur_base::completer();
}
void Op_Diff_VEF_Face::contribue_au_second_membre (DoubleTab & resu) const
Definition at line 1011 of file Op_Diff_VEF_Face.cpp.
References Cerr, DoubleTab::dimension(), finl, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), DoubleTab::nb_dim(), Zone_dis_base::nb_front_Cl(), ref_cast, sub_type, Zone_VF::surface(), Deriv_Cond_lim_base::valeur(), Ref_Zone_VEF::valeur(), and Ref_Zone_Cl_VEF::valeur().
Referenced by contribuer_au_second_membre(), and Op_Diff_VEFP1NCP1B_Face::contribuer_au_second_membre().
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  int nb_comp = 1;
  int nb_dim = resu.nb_dim();
  int nb_bords=zone_VEF.nb_front_Cl();
  if(nb_dim==2)
    nb_comp=resu.dimension(1);
// Partie imposee :
  if (nb_dim == 1)
    {
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          if (sub_type(Neumann_paroi,la_cl.valeur()))
            {
              const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = le_bord.num_premiere_face();
              int nfin = ndeb + le_bord.nb_faces();
              for (int face=ndeb; face<nfin; face++)
                resu[face] += la_cl_paroi.flux_impose(face-ndeb)*zone_VEF.surface(face);
            }
          else if (sub_type(Echange_externe_impose,la_cl.valeur()))
            {
              Cerr << "Non code pour Echange_externe_impose" << finl;
              assert(0);
            }
        }
    }
  else
    {
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          if (sub_type(Neumann_paroi,la_cl.valeur()))
            {
              const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi, la_cl.valeur());
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = le_bord.num_premiere_face();
              int nfin = ndeb + le_bord.nb_faces();
              for (int face=ndeb; face<nfin; face++)
                for (int comp=0; comp<nb_comp; comp++)
                  resu(face,comp) += la_cl_paroi.flux_impose(face-ndeb,comp)*zone_VEF.surface(face);
            }
        }
    }
}
void Op_Diff_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice.
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, and Op_Diff_VEF_Face_Stab.
Definition at line 113 of file Op_Diff_VEF_Face.h.
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), MorEqn::equation(), Equation_base::inconnue(), multi_scalaire, Field_base::nature_du_champ(), and Deriv_Champ_Inc_base::valeur().
{
  const Champ_base& inconnue = equation().inconnue().valeur();
  const Nature_du_champ nature_champ = inconnue.nature_du_champ();
  if (nature_champ!=multi_scalaire)
    ajouter_contribution(inco, matrice);
  else
    ajouter_contribution_multi_scalaire(inco, matrice);
}
void Op_Diff_VEF_Face::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face.
Definition at line 127 of file Op_Diff_VEF_Face.h.
References contribue_au_second_membre().
{
  contribue_au_second_membre(resu);
}
Objet_U * Op_Diff_VEF_Face::cree_instance () [static]
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
const Champ_base & Op_Diff_VEF_Face::diffusivite () const [virtual]
Implements Operateur_Diff_base.
Definition at line 74 of file Op_Diff_VEF_Face.cpp.
References diffusivite_, and Ref_Champ_base::valeur().
Referenced by Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som().
{
  return diffusivite_.valeur();
}
void Op_Diff_VEF_Face::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face.
Definition at line 99 of file Op_Diff_VEF_Face.h.
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
{
  Op_VEF_Face::dimensionner(la_zone_vef.valeur(), la_zcl_vef.valeur(), matrice);
}
int Op_Diff_VEF_Face::duplique () const [virtual]
Implements Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
const Type_info * Op_Diff_VEF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
const Type_info * Op_Diff_VEF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
void Op_Diff_VEF_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 104 of file Op_Diff_VEF_Face.h.
References Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
{
  Op_VEF_Face::modifier_pour_Cl(la_zone_vef.valeur(),la_zcl_vef.valeur(), matrice, secmem);
}
Sortie & Op_Diff_VEF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 49 of file Op_Diff_VEF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Diff_VEF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 57 of file Op_Diff_VEF_Face.cpp.
{
  return s ;
}
Op_Diff_VEF_Face & Op_Diff_VEF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
const Op_Diff_VEF_Face & Op_Diff_VEF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
unsigned Op_Diff_VEF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 43 of file Op_Diff_VEF_Face.cpp.
void Op_Diff_VEF_Face::verifier () const
Definition at line 1069 of file Op_Diff_VEF_Face.cpp.
References calculer(), Cerr, dabs(), DoubleTab::dimension(), Objet_U::dimension, MorEqn::equation(), finl, Op_Diff_VEF_base::la_zone_vef, Ref_Zone_VEF::valeur(), Zone_VF::volumes_entrelaces(), and Zone_VF::xv().
Referenced by Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), and Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl().
{
  static int testee=0;
  if(testee)
    return;
  testee=1;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
// const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
// const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleTab& xv=zone_VEF.xv();
  DoubleTab vit(equation().inconnue().valeurs());
  DoubleTab resu(vit);
  int i, comp;
  if(dimension==2)
    {
      const int nbf = vit.dimension(0);
      Cerr << " Verification de delta(x,0) " << finl;
      for(i=0; i<nbf; i++)
        {
          vit(i,0)=xv(i,0);
          vit(i,1)=0;
        }
      calculer(vit, resu);
      for(i=0; i<nbf; i++)
        for(comp=0; comp<dimension; comp++)
          resu(i,comp)/=(volumes_entrelaces(i));
      for(i=0; i<nbf; i++)
        {
          if(dabs(resu(i,0))>1.e-10)
            {
              Cerr << " delta(x,0) ("<<i<<") = "
                   << resu(i,0);
              Cerr << finl;
            }
        }
      Cerr << " Verification de delta(y(1-y),0) " << finl;
      for(i=0; i<nbf; i++)
        {
          vit(i,0)=xv(i,1)*(1-xv(i,1));
          vit(i,1)=0;
        }
      calculer(vit, resu);
      for(i=0; i<nbf; i++)
        for(comp=0; comp<dimension; comp++)
          resu(i,comp)/=(volumes_entrelaces(i));
      for(i=0; i<nbf; i++)
        {
          if(dabs(2-resu(i,0))>1.e-10)
            {
              Cerr << " delta(y(1-y),0) ("<<i<<") = "
                   << resu(i,0);
              Cerr << finl;
            }
        }
    }
}
Member Data Documentation
Ref_Champ_base Op_Diff_VEF_Face::diffusivite_ [protected]
Definition at line 91 of file Op_Diff_VEF_Face.h.
Referenced by associer_diffusivite(), and diffusivite().
const Type_info Op_Diff_VEF_Face::info_obj [static]
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, and Op_Diff_VEF_Face_Var.
Definition at line 45 of file Op_Diff_VEF_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Diff_VEF_Face.h
src/VEF/Operateurs/Op_Diff_VEF_Face.cpp