TRUST: Perte_Charge Class Reference
Perte_Charge Class Reference
Classe Perte_Charge
Cette classe represente un terme de perte de charge quiest introduit
dans les equations de Navier-Stokes pour modeliser la presence d'un
certain type d'obstacle dans l'ecoulement.
On utilise la notion de perte de charge pour des obstacles sur lesquels
on ne calcule pas le frottement (obstacles internes aux mailles, ou
grilles par exemple)
Un objet de type Perte_Charge s'applique sur
une seule direction d'espace (direction_perte_charge() >= 0)
ou sur toutes (direction_perte_charge() == -1)
#include <Perte_Charge.h>
Public Member Functions
int direction_perte_charge () const
Renvoie la direction de perte de charge.
(X,Y ou Z), ou -1 si toutes les directions.
Protected Attributes
int direction_perte_charge_
Detailed Description
Classe Perte_Charge
Cette classe represente un terme de perte de charge quiest introduit
dans les equations de Navier-Stokes pour modeliser la presence d'un
certain type d'obstacle dans l'ecoulement.
On utilise la notion de perte de charge pour des obstacles sur lesquels
on ne calcule pas le frottement (obstacles internes aux mailles, ou
grilles par exemple)
Un objet de type Perte_Charge s'applique sur
une seule direction d'espace (direction_perte_charge() >= 0)
ou sur toutes (direction_perte_charge() == -1)
Definition at line 46 of file Perte_Charge.h.
Member Function Documentation
int Perte_Charge::direction_perte_charge () const [inline]
Renvoie la direction de perte de charge.
(X,Y ou Z), ou -1 si toutes les directions.
Returns:
int
Signification: la direction de perte de charge
Contraintes: -1 <= valeur <= dimension
Definition at line 74 of file Perte_Charge.h.
References direction_perte_charge_.
Referenced by Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_Singuliere::lire_surfaces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), and Perte_Charge_Reguliere_VDF_Face::remplir_num_faces().
{
  return direction_perte_charge_;
}
Member Data Documentation
int Perte_Charge::direction_perte_charge_ [protected]
Definition at line 55 of file Perte_Charge.h.
Referenced by direction_perte_charge(), Perte_Charge_Singuliere::lire_donnees(), and Perte_Charge_Reguliere::lire_donnees().
The documentation for this class was generated from the following file:
src/ThHyd/Incompressible/Sources/Perte_Charge.h