TRUST: EcrFicCollecte Class Reference
EcrFicCollecte Class Reference
Ecriture dans un fichier
Cette classe implemente les operateurs et les methodes virtuelles de la clase SFichier de la facon suivante :
Il y a autant de fichiers que de processus, physiquement localises sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
Le processus maitre recoit chaque item a ecrire de chacun des processus et dans chacun chacun des fichiers.
il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
#include <EcrFicCollecte.h>
Public Member Functions
~EcrFicCollecte ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EcrFicCollecte ()
EcrFicCollecte (const char *name, std::_Ios_Openmode mode=ios::out)
Constructeur
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out) override
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
Public Member Functions inherited from SFichier
SFichier ()
~SFichier ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SFichier (const char *name, std::_Ios_Openmode mode=ios::out)
Public Member Functions inherited from Sortie_Fichier_base
~Sortie_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sortie_Fichier_base ()
Sortie_Fichier_base (const Sortie_Fichier_base &)=default
Sortie_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::out)
ofstream & get_ofstream ()
void close ()
void precision (int pre) override
virtual int get_precision ()
void setf (std::_Ios_Fmtflags code) override
bool is_open ()
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::out)
Sortie & flush () override
Force l'ecriture sur disque des donnees dans le tampon
Utilise l'implementation de la classe ofstream.
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EcrFicCollecte & self_cast (Objet_U &)
static const EcrFicCollecte & self_cast (const Objet_U &)
Static Public Member Functions inherited from SFichier
static Objet_U * cree_instance ()
static const Type_info * info ()
static SFichier & self_cast (Objet_U &)
static const SFichier & self_cast (const Objet_U &)
Static Public Member Functions inherited from Sortie_Fichier_base
static const Type_info * info ()
static Sortie_Fichier_base & self_cast (Objet_U &)
static const Sortie_Fichier_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from SFichier
static const Type_info info_obj
Static Public Attributes inherited from Sortie_Fichier_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SFichier
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Sortie_Fichier_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
EcrFicCollecte (int)
Additional Inherited Members
Protected Attributes inherited from Sortie_Fichier_base
ofstream * ofstream_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
Ecriture dans un fichier
Cette classe implemente les operateurs et les methodes virtuelles de la clase SFichier de la facon suivante :
Il y a autant de fichiers que de processus, physiquement localises sur le disque de la machine hebergeant la tache maitre de l'application Trio-U (le processus de rang 0 dans le groupe "tous")
Le processus maitre recoit chaque item a ecrire de chacun des processus et dans chacun chacun des fichiers.
il en est de meme pour les methodes d'inspection de l'etat d'un fichier.
Definition at line 35 of file EcrFicCollecte.h.
Constructor & Destructor Documentation
~EcrFicCollecte()
EcrFicCollecte::~EcrFicCollecte ()
Definition at line 31 of file EcrFicCollecte.cpp.
{
  SFichier::close();
}
References Sortie_Fichier_base::close().
EcrFicCollecte() [1/3]
EcrFicCollecte::EcrFicCollecte (int) inline private
Definition at line 41 of file EcrFicCollecte.h.
{};
EcrFicCollecte() [2/3]
EcrFicCollecte::EcrFicCollecte () inline
Definition at line 44 of file EcrFicCollecte.h.
{};
EcrFicCollecte() [3/3]
EcrFicCollecte::EcrFicCollecte (const char * name, std::_Ios_Openmode mode = ios::out)
Constructeur
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
Definition at line 61 of file EcrFicCollecte.cpp.
{
  EcrFicCollecte::ouvrir(name, mode);
}
References ouvrir().
Member Function Documentation
cree_instance()
Objet_U * EcrFicCollecte::cree_instance () static
Definition at line 19 of file EcrFicCollecte.cpp.
duplique()
int EcrFicCollecte::duplique () const override virtual
Implements Objet_U.
Reimplemented in EcrFicCollecteBin.
Definition at line 19 of file EcrFicCollecte.cpp.
get_info()
const Type_info * EcrFicCollecte::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrFicCollecteBin.
Definition at line 19 of file EcrFicCollecte.cpp.
info()
const Type_info * EcrFicCollecte::info () static
Definition at line 19 of file EcrFicCollecte.cpp.
ouvrir()
int EcrFicCollecte::ouvrir (const char * name, std::_Ios_Openmode mode = ios::out) override virtual
Ouvre le fichier avec les parametres mode et prot donnes
Ces parametres sont les parametres de la methode open standard.
Reimplemented from Sortie_Fichier_base.
Definition at line 92 of file EcrFicCollecte.cpp.
{
  Nom nom_fic(name);
  if(Process::nproc()>1)
    nom_fic=nom_fic.nom_me(me());
#ifdef FILESYSTEM_NON_GLOBAL
  Nom localisation;
  if (je_suis_maitre())
    localisation = pwd();
  envoyer_broadcast(localisation, 0);
  nom_fic = localisation + "/" + nom_fic;
#endif
  if (je_suis_maitre())
    Cerr << "Opening the files of type EcrFicColl : " << name <<finl;
  return SFichier::ouvrir((const char *)nom_fic,mode);
}
References Cerr, envoyer_broadcast(), finl, Process::je_suis_maitre(), Process::me(), Nom::nom_me(), Process::nproc(), Sortie_Fichier_base::ouvrir(), and pwd().
Referenced by EcrFicCollecte(), EcrFicCollecteBin::EcrFicCollecteBin(), Raffiner_isotrope_parallele::interpreter(), Debog_Pb::readOn(), and SolveurSys_base::save_matrice_secmem_conditionnel().
printOn()
Sortie & EcrFicCollecte::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrFicCollecteBin.
Definition at line 26 of file EcrFicCollecte.cpp.
{
  throw;
  return s;
}
readOn()
Entree & EcrFicCollecte::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in EcrFicCollecteBin.
Definition at line 20 of file EcrFicCollecte.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const EcrFicCollecte & EcrFicCollecte::self_cast (const Objet_U & r) static
Definition at line 19 of file EcrFicCollecte.cpp.
self_cast() [2/2]
EcrFicCollecte & EcrFicCollecte::self_cast (Objet_U & r) static
Definition at line 19 of file EcrFicCollecte.cpp.
taille_memoire()
unsigned EcrFicCollecte::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in EcrFicCollecteBin.
Definition at line 19 of file EcrFicCollecte.cpp.
Member Data Documentation
info_obj
const Type_info EcrFicCollecte::info_obj static
Definition at line 37 of file EcrFicCollecte.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/EcrFicCollecte.h
src/Kernel/Utilitaires/EcrFicCollecte.cpp