TRUST: Entree_Fichier_base Class Reference
Entree_Fichier_base Class Reference
Fichier en lecture
Cette classe est a la classe C++ ifstream ce que la classe Entree est a la
classe C++ istream. Elle redefinit de facon virtuelle les operateurs de lecture dans un fichier.
#include <Entree_Fichier_base.h>
Public Member Functions
~Entree_Fichier_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree_Fichier_base ()
Entree_Fichier_base (const Entree_Fichier_base &)=default
Entree_Fichier_base (const char *name, std::_Ios_Openmode mode=ios::in)
ifstream & get_ifstream ()
void close ()
int eof () override
int fail () override
int good () override
void precision (int pre)
void setf (std::_Ios_Fmtflags code)
virtual int ouvrir (const char *name, std::_Ios_Openmode mode=ios::in)
Public Member Functions inherited from Entree
Entree ()
Entree (istream &is)
Entree (const Entree &is)
Entree & operator= (istream &is)
Entree & operator= (Entree &is)
virtual istream & get_istream ()
virtual const istream & get_istream () const
void set_istream (istream *is)
void set_different_int_size (bool is_different_int_size)
Entree & operator>> (Entree &(*f)(Entree &))
Entree & operator>> (istream &(*f)(istream &))
Entree & operator>> (ios &(*f)(ios &))
virtual Entree & operator>> (int &ob)
virtual Entree & operator>> (long &ob)
virtual Entree & operator>> (float &ob)
virtual Entree & operator>> (double &ob)
virtual int get (int *ob, int n)
virtual int get (long *ob, int n)
virtual int get (float *ob, int n)
virtual int get (double *ob, int n)
virtual int get (char *buf, int bufsize)
Lecture d'une chaine dans ostream_
bufsize est la taille du buffer alloue pour ob (y compris
le caractere 0 final).
La chaine contient toujours un 0 meme en cas d'echec.
La methode renvoie 1 si la lecture est bonne, 0 sinon.
Si le buffer est trop petit, pour l'instant on fait exit() mais
par la suite on pourra tester: si strlen(ob)==bufsize-1, alors
refaire lire() jusqu'a arriver au bout. Si le lire() suivant
renvoie une chaine de longueur nulle, cela signifie que la taille de la
chaine etait exactement bufsize-1.
Attention: le comportement est different en binaire et en ascii.
En binaire, on lit la chaine jusqu'au prochain '\0'.
En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
virtual int eof ()
virtual int fail ()
virtual int good ()
virtual ~Entree ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
int is_bin () const
virtual void set_check_types (int flag)
indique si le stream doit verifier les types des objets lus<br>(ints et nombres flottants). Exemple : l'entree contient 123.456 123.456
int i;
check_types(0);
is >> i; // i contient 123
check_types(1);
is >> i; // Erreur : on lit la chaine 123.456 et on essaye de la convertir en int
Voir operator>>(int &)
int check_types () const
renvoie la valeur actuelle du drapeau, voir set_check_types()
virtual void set_error_action (Error_Action)
Change le comportement en cas d'erreur de l'entree,
voir error_handle_() et get_error_action()
Error_Action get_error_action ()
renvoie error_action_ pour cette entree<br>(permet de la modifier et de restaurer ensuite la valeur anterieure)
operator istream & ()
istream & putback (char ch)
istream & ignore (int n=1, int delim=EOF)
int get_diffuse ()
virtual void set_diffuse (int diffuse)
ToDo TMA : commenter.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Entree_Fichier_base & self_cast (Objet_U &)
static const Entree_Fichier_base & self_cast (const Objet_U &)
static bool Can_be_read (const char *name)
Return True if the file can be opened for reading, false otherwise.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Entree
int error_handle (int fail_flag)
virtual int error_handle_ (int fail_flag)
Cette fonction est appellee par operateur>>, get, get_nom
ouvrir, fermer, lire, etc... en cas d'echec (lorsque fail() est mis)
Elle renvoie 0 s'il y a eu une erreur (passer par error_handle() qui
traite en inline le cas ou il n'y a pas d'erreur), et 1 s'il n'y a pas
d'erreur.
(par commodite de codage des methodes qui l'utilisent, on
ecrira "return error_handle(fail());"
Elle peut etre configuree pour
- renvoyer "0" en cas d'erreur et continuer l'execution du code
(cas d'un ancien code qui ne gere pas les exceptions mais teste
le drapeau fail() de temps en temps)
Dans ce cas les methodes operator>> continuent l'execution du code
meme en cas d'echec, le contenu des variables lues est indefini !
- faire Process::exit() (cas d'une portion de code dans laquelle
on ne veut pas faire de gestion d'erreur du tout et ou on suppose
que tout va toujours bien)
- lever une exception (permet une gestion rigoureuse des erreurs
et une information utilisateur optimale en fonction du contexte)
Voir aussi set_error_action()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ifstream * ifstream_
Protected Attributes inherited from Entree
int bin_
bool is_different_int_size_
File with int32 (or int64) whereas version is int64 (or int32)
int check_types_
Error_Action error_action_
int diffuse_
By default 1, but some child classes (eg: LecFicDiffuse) could set temporary to 0 to not diffuse to other processes.
Private Member Functions
Entree_Fichier_base & operator= (const Entree_Fichier_base &)
copy is forbidden
Additional Inherited Members
Public Types inherited from Entree
enum Error_Action { ERROR_EXIT , ERROR_CONTINUE , ERROR_EXCEPTION }
Detailed Description
Fichier en lecture
Cette classe est a la classe C++ ifstream ce que la classe Entree est a la
classe C++ istream. Elle redefinit de facon virtuelle les operateurs de lecture dans un fichier.
Definition at line 36 of file Entree_Fichier_base.h.
Constructor & Destructor Documentation
~Entree_Fichier_base()
Entree_Fichier_base::~Entree_Fichier_base () override
Definition at line 55 of file Entree_Fichier_base.cpp.
{
  Entree_Fichier_base::close();
}
References close().
Entree_Fichier_base() [1/3]
Entree_Fichier_base::Entree_Fichier_base ()
Definition at line 34 of file Entree_Fichier_base.cpp.
{
  ifstream_=0;
}
References ifstream_.
Entree_Fichier_base() [2/3]
Entree_Fichier_base::Entree_Fichier_base (const Entree_Fichier_base &) default
Entree_Fichier_base() [3/3]
Entree_Fichier_base::Entree_Fichier_base (const char * name, std::_Ios_Openmode mode = ios::in)
Definition at line 39 of file Entree_Fichier_base.cpp.
{
  ifstream_ = new ifstream(name, mode);
  if(ifstream_->fail())
    {
      Cerr << "Error while opening the file " << name << finl;
      Process::exit();
    }
  set_istream(ifstream_);
}
References Cerr, Process::exit(), finl, ifstream_, and Entree::set_istream().
Member Function Documentation
Can_be_read()
bool Entree_Fichier_base::Can_be_read (const char * name) static
Return True if the file can be opened for reading, false otherwise.
Definition at line 159 of file Entree_Fichier_base.cpp.
{
  std::ifstream ifs(name,ios::in);
  return ifs.good();
}
close()
void Entree_Fichier_base::close ()
Definition at line 111 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    {
      ifstream_->close();
// on ne detruit pas ifstream ca sera fait par entree
// delete ifstream_;
    }
}
References ifstream_.
Referenced by Op_Diff_RotRot::assembler_matrice(), check_ICEM_binary_file(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Union::construire_partition(), ExtrudeBord::extruder_hexa_old(), Format_Post_Lata::finir_sans_reprise(), Lire_Tgrid::interpreter_(), Zone_VEF_PreP1b::lecture_ok_arete(), Scatter::lire_domaine(), Postraitement::lire_fichier(), Sondes::lire_fichier(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Format_Post_Lata::modify_file_basename(), Format_Post_Lata::reconstruct(), Champ_front_recyclage::UPb(), ~Entree_Fichier_base(), and LecFicDistribue::~LecFicDistribue().
eof()
int Entree_Fichier_base::eof () override virtual
Reimplemented from Entree.
Reimplemented in Lec_Diffuse_base.
Definition at line 121 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    return ifstream_->eof();
  else
    return -1;
}
References ifstream_.
Referenced by Solv_Petsc::create_solver(), Format_Post_Med::finir_med(), Format_Post_Lata::finir_sans_reprise(), Lire_Tgrid::interpreter_(), Format_Post_Lata::modify_file_basename(), LecFicDiffuse_JDD::ouvrir(), Format_Post_Lata::reconstruct(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Champ_front_recyclage::UPb(), and Terme_Source_Canal_perio::write_flow_rate().
fail()
int Entree_Fichier_base::fail () override virtual
Reimplemented from Entree.
Reimplemented in Lec_Diffuse_base.
Definition at line 129 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    return ifstream_->fail();
  else
    return -1;
}
References ifstream_.
Referenced by Traitement_particulier_NS_canal::reprendre_stat_canal(), and Ch_front_Vortex::reprendre_vortex().
get_ifstream()
ifstream & Entree_Fichier_base::get_ifstream ()
Definition at line 50 of file Entree_Fichier_base.cpp.
{
  return *ifstream_;
}
References ifstream_.
Referenced by Solv_Petsc::create_solver(), Format_Post_Lata::finir_sans_reprise(), Lire_Fichier::interpreter(), Format_Post_Lata::reconstruct(), Schema_Implicite_Multi_TimeStep_base::reprendre(), and Terme_Source_Canal_perio::write_flow_rate().
get_info()
const Type_info * Entree_Fichier_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Lec_Diffuse_base, LecFicDiffuse, LecFicDiffuse_JDD, LecFicDiffuseBin, LecFicDistribue, and LecFicDistribueBin.
Definition at line 21 of file Entree_Fichier_base.cpp.
good()
int Entree_Fichier_base::good () override virtual
Reimplemented from Entree.
Reimplemented in Lec_Diffuse_base.
Definition at line 137 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    return ifstream_->good();
  else
    return -1;
}
References ifstream_.
Referenced by Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), DecoupeBord::Decouper(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Lire_Tgrid::interpreter_(), read_write_string_from(), Champ_Fonc_MED::readOn(), and va_a_la_parenthese_fermante().
info()
const Type_info * Entree_Fichier_base::info () static
Definition at line 21 of file Entree_Fichier_base.cpp.
operator=()
Entree_Fichier_base & Entree_Fichier_base::operator= (const Entree_Fichier_base &) private
copy is forbidden
ouvrir()
int Entree_Fichier_base::ouvrir (const char * name, std::_Ios_Openmode mode = ios::in) virtual
Reimplemented in LecFicDiffuse, LecFicDiffuse_JDD, and LecFicDistribue.
Definition at line 60 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    delete ifstream_;
  IOS_OPEN_MODE ios_mod=mode;
  if (bin_)
    {
      ios_mod=ios_mod|ios::binary;
    }
  ifstream_ = new ifstream(name,ios_mod);
  int ok = ifstream_->good();
  set_istream(ifstream_);
#ifdef INT_is_64_
  if (bin_)
    {
      Nom test;
      (*this) >> test;
      if (test!="INT64")
        {
          Cerr<<"Opening " <<name<< " which is an int32 binary file..."<<finl;
          delete ifstream_;
// on recharge le fichier
          ifstream_ = new ifstream(name,ios_mod);
          is_different_int_size_=true;
          ok = ifstream_->good();
          set_istream(ifstream_);
        }
    }
#else
  if (bin_)
    {
      Nom test;
      (*this) >> test;
      if (test=="INT64")
        {
          Cerr<<"Opening " << name<< " which is an int64 binary file..."<<finl;
          is_different_int_size_=true;
        }
      else
        {
          delete ifstream_;
// on recharge le fichier
          ifstream_ = new ifstream(name,ios_mod);
          ok = ifstream_->good();
          set_istream(ifstream_);
        }
    }
#endif
  return ok;
}
References Entree::bin_, Cerr, finl, ifstream_, IOS_OPEN_MODE, Entree::is_different_int_size_, Entree::set_istream(), and test().
Referenced by Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Union::construire_partition(), EFichierBin::EFichierBin(), Zone_VEF_PreP1b::lecture_ok_arete(), Scatter::lire_domaine(), LecFicDiffuse::ouvrir(), LecFicDiffuse_JDD::ouvrir(), LecFicDistribue::ouvrir(), Debog_Pb::readOn(), Sous_Zone::readOn(), Champ_Fonc_MED::readOn(), Schema_Implicite_Multi_TimeStep_base::reprendre(), and Terme_Source_Canal_perio::write_flow_rate().
precision()
void Entree_Fichier_base::precision (int pre)
Definition at line 145 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    ifstream_->precision(pre);
}
References ifstream_.
Referenced by Debog_Pb::read_geometry_data().
printOn()
Sortie & Entree_Fichier_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Lec_Diffuse_base, LecFicDiffuse, LecFicDiffuse_JDD, LecFicDiffuseBin, LecFicDistribue, and LecFicDistribueBin.
Definition at line 29 of file Entree_Fichier_base.cpp.
{
  throw;
  return s;
}
readOn()
Entree & Entree_Fichier_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Lec_Diffuse_base, LecFicDiffuse, LecFicDiffuse_JDD, LecFicDiffuseBin, LecFicDistribue, and LecFicDistribueBin.
Definition at line 23 of file Entree_Fichier_base.cpp.
{
  throw;
  return s;
}
self_cast() [1/2]
const Entree_Fichier_base & Entree_Fichier_base::self_cast (const Objet_U & r) static
Definition at line 21 of file Entree_Fichier_base.cpp.
self_cast() [2/2]
Entree_Fichier_base & Entree_Fichier_base::self_cast (Objet_U & r) static
Definition at line 21 of file Entree_Fichier_base.cpp.
setf()
void Entree_Fichier_base::setf (std::_Ios_Fmtflags code)
Definition at line 151 of file Entree_Fichier_base.cpp.
{
  if(ifstream_)
    ifstream_->setf(code);
}
References ifstream_.
Referenced by Traitement_particulier_NS_canal::reprendre_stat_canal(), and Ch_front_Vortex::reprendre_vortex().
Member Data Documentation
ifstream_
ifstream* Entree_Fichier_base::ifstream_ protected
Definition at line 56 of file Entree_Fichier_base.h.
Referenced by close(), EFichierBin::EFichierBin(), Entree_Fichier_base(), eof(), fail(), get_ifstream(), good(), ouvrir(), precision(), and setf().
info_obj
const Type_info Entree_Fichier_base::info_obj static
Definition at line 38 of file Entree_Fichier_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Entree_Fichier_base.h
src/Kernel/Utilitaires/Entree_Fichier_base.cpp