TRUST: Source_PDF_EF Class Reference
Source_PDF_EF Class Reference
class Source_PDF_EF
Source term for the penalisation of the momentum in the Immersed Boundary Method (IBM)
#include <Source_PDF_EF.h>
Public Member Functions
Source_PDF_EF ()
~Source_PDF_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &) const override
DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &, const int) const override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
contribution a la matrice implicite des termes sources
par defaut pas de contribution
void verif_ajouter_contrib (const DoubleTab &vitesse, Matrice_Morse &matrice) const
DoubleVect diag_coeff_elem (ArrOfDouble &, const DoubleTab &, int) const override
DoubleTab compute_coeff_elem () const override
DoubleTab compute_coeff_matrice_pression () const override
void multiply_coeff_volume (DoubleTab &) const override
void correct_pressure (const DoubleTab &, DoubleTab &, const DoubleTab &) const override
void correct_incr_pressure (const DoubleTab &, DoubleTab &) const override
void correct_vitesse (const DoubleTab &, DoubleTab &) const override
void calculer_vitesse_imposee ()
void test (Matrice &) const
void updateChampRho ()
int impr (Sortie &) const override
Public Member Functions inherited from Source_PDF_base
Source_PDF_base ()
~Source_PDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int getInterpolationBool ()
bool get_matrice_pression_variable_bool_ ()
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &) const override
virtual DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &, const int) const
DoubleTab & calculer (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &, const int) const
DoubleTab & calculer_pdf (DoubleTab &) const
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
contribution a la matrice implicite des termes sources
par defaut pas de contribution
double fonct_coeff (const double, const double, const double) const
virtual DoubleVect diag_coeff_elem (ArrOfDouble &, const DoubleTab &, int) const
virtual DoubleTab compute_coeff_elem () const
virtual DoubleTab compute_coeff_matrice_pression () const
virtual void multiply_coeff_volume (DoubleTab &) const
virtual void correct_pressure (const DoubleTab &, DoubleTab &, const DoubleTab &) const
virtual void correct_incr_pressure (const DoubleTab &, DoubleTab &) const
virtual void correct_vitesse (const DoubleTab &, DoubleTab &) const
void calculer_vitesse_imposee ()
void updateChampRho ()
const PDF_model & get_modele () const
int impr (Sortie &) const override
void ouvrir_fichier (SFichier &, const Nom &, const int) const override
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
const DoubleTab & get_sec_mem_pdf () const
void set_sec_mem_pdf (DoubleTab &it)
Public Member Functions inherited from Source_dep_inco_base
Source_dep_inco_base ()
~Source_dep_inco_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &resu) const override
virtual DoubleTab & ajouter_ (const DoubleTab &inco, DoubleTab &resu) const =0
DoubleTab & calculer (DoubleTab &resu) const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Source_PDF_EF & self_cast (Objet_U &)
static const Source_PDF_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_PDF_base
static const Type_info * info ()
static Source_PDF_base & self_cast (Objet_U &)
static const Source_PDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_dep_inco_base
static const Type_info * info ()
static Source_dep_inco_base & self_cast (Objet_U &)
static const Source_dep_inco_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_PDF_base
static const Type_info info_obj
Static Public Attributes inherited from Source_dep_inco_base
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void compute_vitesse_imposee_projete (const DoubleTab &, const DoubleTab &, double, double) override
void calculer_vitesse_imposee_hybrid () override
void calculer_vitesse_imposee_elem_fluid () override
void calculer_vitesse_imposee_mean_grad () override
void calculer_vitesse_imposee_power_law_tbl () override
void rotate_imposed_velocity (DoubleTab &) override
DoubleTab compute_pond (const DoubleTab &, const DoubleTab &, const DoubleVect &, int &, int &) const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void compute_indicateur_nodal_champ_aire () override
Protected Member Functions inherited from Source_PDF_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void compute_vitesse_imposee_projete (const DoubleTab &, const DoubleTab &, double, double)
virtual void calculer_vitesse_imposee_hybrid ()
virtual void calculer_vitesse_imposee_elem_fluid ()
virtual void calculer_vitesse_imposee_mean_grad ()
virtual void calculer_vitesse_imposee_power_law_tbl ()
virtual void rotate_imposed_velocity (DoubleTab &)
ArrOfDouble get_tuvw_local () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
virtual void compute_indicateur_nodal_champ_aire ()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Don champ_nodal_
Ref_Zone_EF la_zone_EF
Ref_Zone_Cl_EF la_zone_Cl_EF
Protected Attributes inherited from Source_PDF_base
int type_vitesse_imposee_
Champ_Don champ_rotation_lu_
Champ_Don champ_rotation_
Champ_Don champ_aire_lu_
Champ_Don champ_aire_
Champ_Don champ_rho_
int transpose_rotation_
DoubleTab indicateur_nodal_champ_aire_
DoubleTab vitesse_imposee_
PDF_model modele_lu_
double temps_relax_
double echelle_relax_
bool matrice_pression_variable_bool_
bool penalized_
DoubleTab sec_mem_pdf
part of the source term computed with the imposed velocity FOR THE INTERPOLATION
Interpolation_IBM interpolation_lue_
int interpolation_bool_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Source_PDF_EF
Source term for the penalisation of the momentum in the Immersed Boundary Method (IBM)
See also
Source_PDF_base
Definition at line 36 of file Source_PDF_EF.h.
Constructor & Destructor Documentation
Source_PDF_EF()
Source_PDF_EF::Source_PDF_EF ()
Definition at line 37 of file Source_PDF_EF.cpp.
~Source_PDF_EF()
Source_PDF_EF::~Source_PDF_EF ()
Definition at line 37 of file Source_PDF_EF.cpp.
Member Function Documentation
ajouter_() [1/2]
DoubleTab & Source_PDF_EF::ajouter_ (const DoubleTab & vitesse, DoubleTab & resu) const override virtual
Implements Source_dep_inco_base.
Definition at line 583 of file Source_PDF_EF.cpp.
{
  const int i_traitement_special = 0 ;
  ajouter_(vitesse, resu, i_traitement_special) ;
  return resu;
}
References ajouter_().
Referenced by ajouter_(), and verif_ajouter_contrib().
ajouter_() [2/2]
DoubleTab & Source_PDF_EF::ajouter_ (const DoubleTab & vitesse, DoubleTab & resu, const int i_traitement_special) const override virtual
Reimplemented from Source_PDF_base.
Definition at line 500 of file Source_PDF_EF.cpp.
{
  /* i_traitement_special = 0 => traitement classique; coefficient (1/eta) */
  /* i_traitement_special = 1 => coefficient (1/eta -> 1) */
  /* i_traitement_special = 2 => coefficient (1/eta -> 1 + 1/eta) */
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems() ;
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int nb_elems=zone_EF.zone().nb_elem_tot();
  const DoubleVect& volume_thilde=zone_EF.volumes_thilde();
  int ncomp=dimension;
  ArrOfDouble tuvw(dimension);
  const DoubleTab& rotation=champ_rotation_.valeurs();
  const DoubleTab& aire=champ_aire_.valeurs();
  Champ_Don rho_test;
// champ_rho_.valeur().affecter(equation().probleme().get_champ("masse_volumique"));
  const DoubleTab& rho_m=champ_rho_.valeurs();
  DoubleTab pond;
  pond = compute_pond(rho_m, aire, volume_thilde, nb_som_elem, nb_elems);
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      if (aire(num_elem)>0.)
        {
          if (i_traitement_special == 0)
            {
              tuvw[0] =  1.0 / modele_lu_.eta_;
              tuvw[1] =  1.0 / modele_lu_.eta_;
              tuvw[2] =  1.0 / modele_lu_.eta_;
            }
          else if (i_traitement_special == 1) //terme temps en rho v
            {
              tuvw[0] =  1.0;
              tuvw[1] =  1.0;
              tuvw[2] =  1.0;
            }
          else if (i_traitement_special == 101) //terme temps en v
            {
              tuvw[0] =  1.0 / rho_m(num_elem);
              tuvw[1] =  1.0 / rho_m(num_elem);
              tuvw[2] =  1.0 / rho_m(num_elem);
            }
          else if (i_traitement_special == 2)
            {
              tuvw[0] =  1.0 + 1.0 / modele_lu_.eta_;
              tuvw[1] =  1.0 + 1.0 / modele_lu_.eta_;
              tuvw[2] =  1.0 + 1.0 / modele_lu_.eta_;
            }
          else if (i_traitement_special == 102)
            {
              tuvw[0] =  1.0 / rho_m(num_elem) + 1.0 / modele_lu_.eta_;
              tuvw[1] =  1.0 / rho_m(num_elem) + 1.0 / modele_lu_.eta_;
              tuvw[2] =  1.0 / rho_m(num_elem) + 1.0 / modele_lu_.eta_;
            }
          else
            {
              Cerr << "Source_PDF_EF::ajouter_ : i_traitement_special should be 0, 1, 2, 101 or 102" << finl;
              exit();
            }
          for (int comp=0; comp<ncomp; comp++)
            {
              double tijvj=0;
              for (int c=0; c<ncomp; c++)
                {
                  double coeff_im=0;
                  for(int k=0; k<ncomp; k++)
                    {
                      coeff_im+=rotation(num_elem,3*k+comp)*tuvw[k]*rotation(num_elem,3*k+c);
                    }
                  tijvj+=coeff_im ;
                }
              for (int i=0; i<nb_som_elem; i++)
                {
                  resu(elems(num_elem,i),comp)-=pond(num_elem)*nb_som_elem*tijvj*vitesse(elems(num_elem,i),comp);
                }
            }
        }
    }
  return resu;
}
References Cerr, Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, compute_pond(), Objet_U::dimension, PDF_model::eta_, Process::exit(), finl, la_zone_EF, Zone::les_elems(), Source_PDF_base::modele_lu_, Zone::nb_elem_tot(), Zone::nb_som_elem(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
associer_pb()
void Source_PDF_EF::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 63 of file Source_PDF_EF.cpp.
{
  assert(Objet_U::dimension==3);
  int nb_comp=dimension*dimension;
  nb_comp=9;
  Noms nom_c(nb_comp);
  Noms unites(nb_comp);
  pb.discretisation().discretiser_champ("champ_elem",la_zone_EF,vectoriel,nom_c,unites,nb_comp,0.,champ_rotation_);
  champ_rotation_.valeur().affecter(champ_rotation_lu_);
  nb_comp=3;
  Noms nom_c1(nb_comp);
  Noms unites1(nb_comp);
  pb.discretisation().discretiser_champ("champ_elem",la_zone_EF,"aire","m-1",1,0., champ_aire_);
  champ_aire_.valeur().affecter(champ_aire_lu_);
  pb.discretisation().discretiser_champ("champ_elem",la_zone_EF,"rho","kg.m-3",1,0., champ_rho_);
  champ_rho_.valeur().affecter(champ_aire_lu_);
  if (transpose_rotation_)
    {
      DoubleTab& val=champ_rotation_.valeurs();
      int nb_case=val.dimension_tot(0);
      int nb_dim=dimension;
      for (int ele=0; ele<nb_case; ele++)
        for (int k=0; k<nb_dim; k++)
          for (int i=k+1; i<nb_dim; i++)
            {
              double tmp=val(ele,3*k+i);
              val(ele,3*k+i)=val(ele,3*i+k);
              val(ele,3*i+k)=tmp;
            }
    }
  temps_relax_ = modele_lu_.temps_relax_;
  echelle_relax_ = modele_lu_.echelle_relax_;
  matrice_pression_variable_bool_ = false;
  if (temps_relax_ != 1.0e+12) matrice_pression_variable_bool_ = true;
  type_vitesse_imposee_ = modele_lu_.type_vitesse_imposee_;
  pb.discretisation().discretiser_champ("vitesse",la_zone_EF,vectoriel,nom_c1,unites1,nb_comp,0.,modele_lu_.vitesse_imposee_);
  if (interpolation_bool_)
    {
      Zone_dis_base& la_zone_dis_base = ref_cast(Zone_dis_base,la_zone_EF.valeur());
      interpolation_lue_.valeur().discretise(pb.discretisation(),la_zone_dis_base);
      if (type_vitesse_imposee_ == 1)
        {
          if (interpolation_lue_.valeur().que_suis_je() == "Interpolation_IBM_gradient_moyen")
            {
              const Interpolation_IBM_mean_gradient& interp = ref_cast(Interpolation_IBM_mean_gradient,interpolation_lue_.valeur());
              this->compute_vitesse_imposee_projete(interp.solid_elems_.valeur().valeurs(), interp.solid_points_.valeur().valeurs(), -2.0, 1e-6);
            }
          else
            {
              const Interpolation_IBM_elem_fluid& interp = ref_cast(Interpolation_IBM_elem_fluid,interpolation_lue_.valeur());
              compute_vitesse_imposee_projete(interp.fluid_elems_.valeur().valeurs(), interp.solid_points_.valeur().valeurs(), -2.0, 1e-6);
            }
        }
      else
        {
          modele_lu_.vitesse_imposee_.valeur().affecter(modele_lu_.vitesse_imposee_lu_);
        }
    }
  else
    {
      if (type_vitesse_imposee_ != 1)
        {
          modele_lu_.vitesse_imposee_.valeur().affecter(modele_lu_.vitesse_imposee_lu_);
        }
      else
        {
          const DoubleTab& coords = la_zone_EF.valeur().zone().domaine().coord_sommets();
          modele_lu_.affecter_vitesse_imposee(la_zone_EF, coords);
        }
    }
  if (modele_lu_.local_ == 1)
    {
      rotate_imposed_velocity(modele_lu_.vitesse_imposee_.valeur().valeurs());
    }
  /*pb.discretisation().discretiser_champ("vitesse",la_zone_EF,vectoriel,nom_c1,unites1,nb_comp,0.,vitesse_imposee_);
  vitesse_imposee_.valeur().affecter(mod_.vitesse_imposee_);*/
  vitesse_imposee_ = modele_lu_.vitesse_imposee_.valeur().valeurs();
  pb.discretisation().discretiser_champ("champ_sommets",la_zone_EF,"","",1,0., champ_nodal_);
  compute_indicateur_nodal_champ_aire();
}
References Champ_base::affecter(), PDF_model::affecter_vitesse_imposee(), Source_PDF_base::champ_aire_, Source_PDF_base::champ_aire_lu_, champ_nodal_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, Source_PDF_base::champ_rotation_lu_, compute_indicateur_nodal_champ_aire(), compute_vitesse_imposee_projete(), Domaine::coord_sommets(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Probleme_base::discretisation(), Interpolation_IBM_base::discretise(), Discretisation_base::discretiser_champ(), Zone::domaine(), PDF_model::echelle_relax_, Source_PDF_base::echelle_relax_, Interpolation_IBM_elem_fluid::fluid_elems_, Source_PDF_base::interpolation_bool_, Source_PDF_base::interpolation_lue_, la_zone_EF, PDF_model::local_, Source_PDF_base::matrice_pression_variable_bool_, Source_PDF_base::modele_lu_, Objet_U::que_suis_je(), ref_cast, rotate_imposed_velocity(), Interpolation_IBM_mean_gradient_proto::solid_elems_, Interpolation_IBM_base::solid_points_, PDF_model::temps_relax_, Source_PDF_base::temps_relax_, Source_PDF_base::transpose_rotation_, PDF_model::type_vitesse_imposee_, Source_PDF_base::type_vitesse_imposee_, Ref_Zone_EF::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Interpolation_IBM_base::valeur(), Champ_Don::valeurs(), Champ_Don_base::valeurs(), vectoriel, PDF_model::vitesse_imposee_, Source_PDF_base::vitesse_imposee_, PDF_model::vitesse_imposee_lu_, and Zone_dis_base::zone().
associer_zones()
void Source_PDF_EF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 268 of file Source_PDF_EF.cpp.
{
  la_zone_EF = ref_cast(Zone_EF, zone_dis.valeur());
  la_zone_Cl_EF = ref_cast(Zone_Cl_EF, zone_Cl_dis.valeur());
}
References la_zone_Cl_EF, la_zone_EF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer_vitesse_imposee()
void Source_PDF_EF::calculer_vitesse_imposee ()
calculer_vitesse_imposee_elem_fluid()
void Source_PDF_EF::calculer_vitesse_imposee_elem_fluid () override protected virtual
Reimplemented from Source_PDF_base.
Definition at line 692 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int nb_som=zone_EF.zone().nb_som();
  int nb_comp = dimension;
  const Domaine& dom = zone_EF.zone().domaine();
// const IntTab& elems= zone_EF.zone().les_elems();
  DoubleTab& vitesse_imposee_mod = modele_lu_.vitesse_imposee_.valeur().valeurs();
  DoubleTab& vitesse_imposee_calculee = vitesse_imposee_;
  Interpolation_IBM_elem_fluid& interp = ref_cast(Interpolation_IBM_elem_fluid,interpolation_lue_.valeur());
  DoubleTab& fluid_points = interp.fluid_points_.valeur().valeurs();
  DoubleTab& solid_points = interp.solid_points_.valeur().valeurs();
  DoubleTab& fluid_elems = interp.fluid_elems_.valeur().valeurs();
  Champ_Q1_EF& champ_vitesse_inconnue = ref_cast(Champ_Q1_EF,equation().inconnue().valeur());
  DoubleTab& val_vitesse_inconnue = champ_vitesse_inconnue.valeurs();
  DoubleTab xf(1, nb_comp);
  DoubleTab vf(1, nb_comp);
  ArrOfInt cells(1);
  double eps = 1e-12;
  for (int i = 0; i < nb_som; i++)
    {
      if (fluid_elems(i) >= 0.0)
        {
          double d1 = 0.0;
          double d2 = 0.0;
          for(int j = 0; j < nb_comp; j++)
            {
              double xj = dom.coord(i,j);
              double xjf = fluid_points(i,j);
              xf(0, j) = xjf;
              double xjs = solid_points(i,j);
              d1 += (xj-xjs)*(xj-xjs);
              d2 += (xjf-xj)*(xjf-xj);
            }
          d1 = sqrt(d1);
          d2 = sqrt(d2);
          double inv_d ;
          if ( (d1 + d2) > eps ) inv_d = 1.0 / (d1 + d2);
          else inv_d = 0. ;
          cells[0] = int(fluid_elems(i));
          champ_vitesse_inconnue.value_interpolation(xf,cells, val_vitesse_inconnue, vf);
          for (int j = 0; j < nb_comp; j++)
            {
              double vjs = vitesse_imposee_mod(i,j);
              vitesse_imposee_calculee(i,j) = vjs + (vf(0, j)-vjs)*inv_d*d1;
            }
        }
      else
        {
          for(int j = 0; j < nb_comp; j++)
            {
              vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j);
            }
        }
    }
// vitesse_imposee_calculee.echange_espace_virtuel();
}
References Domaine::coord(), Objet_U::dimension, Zone::domaine(), MorEqn::equation(), Interpolation_IBM_elem_fluid::fluid_elems_, Interpolation_IBM_elem_fluid::fluid_points_, Source_PDF_base::interpolation_lue_, la_zone_EF, Source_PDF_base::modele_lu_, Zone::nb_som(), ref_cast, Interpolation_IBM_base::solid_points_, Ref_Zone_EF::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Interpolation_IBM_base::valeur(), valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_implementation_Q1::value_interpolation(), PDF_model::vitesse_imposee_, Source_PDF_base::vitesse_imposee_, and Zone_dis_base::zone().
calculer_vitesse_imposee_hybrid()
void Source_PDF_EF::calculer_vitesse_imposee_hybrid () override protected virtual
Reimplemented from Source_PDF_base.
Definition at line 829 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int nb_som=zone_EF.zone().nb_som();
  int nb_comp = dimension;
  const Domaine& dom = zone_EF.zone().domaine();
// const IntTab& elems= zone_EF.zone().les_elems();
  DoubleTab& vitesse_imposee_mod = modele_lu_.vitesse_imposee_.valeur().valeurs();
  DoubleTab& vitesse_imposee_calculee = vitesse_imposee_;
  Interpolation_IBM_hybrid& interp = ref_cast(Interpolation_IBM_hybrid,interpolation_lue_.valeur());
  DoubleTab& solid_points = interp.solid_points_.valeur().valeurs();
  DoubleTab& fluid_elems = interp.fluid_elems_.valeur().valeurs();
  DoubleTab& fluid_points = interp.fluid_points_.valeur().valeurs();
  double eps = 1e-12;
  Champ_Q1_EF& champ_vitesse_inconnue = ref_cast(Champ_Q1_EF,equation().inconnue().valeur());
  DoubleTab& vitesse_inconnue = champ_vitesse_inconnue.valeurs();
  DoubleTab xf(1, nb_comp);
  DoubleTab vf(1, nb_comp);
  ArrOfInt cells(1);
  for (int i = 0; i < nb_som; i++)
    {
      if (fluid_elems(i) >= 0.0)
        {
          double d1 = 0.0;
          double d2 = 0.0;
          for(int j = 0; j < nb_comp; j++)
            {
              double xj = dom.coord(i,j);
              double xjf = fluid_points(i,j);
              xf(0, j) = xjf;
              double xjs = solid_points(i,j);
              d1 += (xj-xjs)*(xj-xjs);
              d2 += (xjf-xj)*(xjf-xj);
            }
          d1 = sqrt(d1);
          d2 = sqrt(d2);
          double inv_d = 1.0 / (d1 + d2);
          cells[0] = int(fluid_elems(i));
          champ_vitesse_inconnue.value_interpolation(xf,cells, vitesse_inconnue, vf);
          for (int j = 0; j < nb_comp; j++)
            {
              double vjs = vitesse_imposee_mod(i,j);
              vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j) + (vf(0, j)-vjs)*inv_d*d1;
            }
        }
      else if (fluid_elems(i) > -1.5 && fluid_elems(i) < -0.5)
        {
          double d2 = 0.0;
          for(int j = 0; j < nb_comp; j++)
            {
              vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j);
              double x = dom.coord(i,j);
              double xp = solid_points(i,j);
              d2 += (x - xp)*(x - xp);
            }
          d2 = sqrt(d2);
          if (d2 > eps)
            {
              IntList& voisins = interp.getSommetsVoisinsOf(i);
              if (!(voisins.est_vide()))
                {
                  ArrOfDouble mean_grad(nb_comp);
                  mean_grad = 0.0;
                  int taille = voisins.size();
                  int nb_contrib = 0;
                  for (int k = 0; k < taille; k++)
                    {
                      int num_som = voisins[k];
                      double d1 = 0.0;
                      for (int j = 0; j < nb_comp; j++)
{
                          double xjf = dom.coord(num_som,j);
                          double xpf = solid_points(num_som,j);
                          d1 += (xjf - xpf)*(xjf - xpf);
                        }
                      d1 = sqrt(d1);
                      if (d1 > eps)
{
                          for (int j = 0; j < nb_comp; j++)
{
                              double vpf = vitesse_imposee_mod(num_som,j);
                              double vjf = vitesse_inconnue(num_som,j);
                              mean_grad[j] += (vjf - vpf)/d1;
                            }
                          nb_contrib += 1;
                        }
                    }
                  for (int j = 0; j < nb_comp; j++)
                    {
                      mean_grad[j] /= nb_contrib;
                      vitesse_imposee_calculee(i,j) += mean_grad[j]*d2;
                    }
                }
            }
        }
      else
        {
          for(int j = 0; j < nb_comp; j++)
            {
              vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j);
            }
        }
    }
// vitesse_imposee_calculee.echange_espace_virtuel();
}
References Domaine::coord(), Objet_U::dimension, Zone::domaine(), MorEqn::equation(), TRUSTListElem< _TYPE_ >::est_vide(), Interpolation_IBM_elem_fluid::fluid_elems_, Interpolation_IBM_elem_fluid::fluid_points_, Interpolation_IBM_hybrid::getSommetsVoisinsOf(), Source_PDF_base::interpolation_lue_, la_zone_EF, Source_PDF_base::modele_lu_, Zone::nb_som(), ref_cast, TRUSTList< _TYPE_ >::size(), Interpolation_IBM_base::solid_points_, Ref_Zone_EF::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Interpolation_IBM_base::valeur(), valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_implementation_Q1::value_interpolation(), PDF_model::vitesse_imposee_, Source_PDF_base::vitesse_imposee_, and Zone_dis_base::zone().
calculer_vitesse_imposee_mean_grad()
void Source_PDF_EF::calculer_vitesse_imposee_mean_grad () override protected virtual
Reimplemented from Source_PDF_base.
Definition at line 753 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int nb_som=zone_EF.zone().nb_som();
  int nb_comp = dimension;
  const Domaine& dom = zone_EF.zone().domaine();
// const IntTab& elems= zone_EF.zone().les_elems();
  DoubleTab& vitesse_imposee_mod = modele_lu_.vitesse_imposee_.valeur().valeurs();
  DoubleTab& vitesse_imposee_calculee = vitesse_imposee_;
  Interpolation_IBM_mean_gradient& interp = ref_cast(Interpolation_IBM_mean_gradient,interpolation_lue_.valeur());
  DoubleTab& solid_points = interp.solid_points_.valeur().valeurs();
  DoubleTab& is_dirichlet = interp.is_dirichlet_.valeur().valeurs();
  double eps = 1e-12;
  DoubleTab& vitesse_inconnue = equation().inconnue().valeur().valeurs();
  vitesse_imposee_mod.echange_espace_virtuel();
  DoubleTrav nb_vois(is_dirichlet);
  for (int i = 0; i < nb_som; i++)
    {
      if (is_dirichlet(i) > 0.0)
        {
          double d2 = 0.0;
          for(int j = 0; j < nb_comp; j++)
            {
              vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j);
              double x = dom.coord(i,j);
              double xp = solid_points(i,j);
              d2 += (x - xp)*(x - xp);
            }
          d2 = sqrt(d2);
          if (d2 > eps)
            {
              IntList& voisins = interp.getSommetsVoisinsOf(i);
              if (!(voisins.est_vide()))
                {
                  ArrOfDouble mean_grad(nb_comp);
                  mean_grad = 0.0;
                  int taille = voisins.size();
                  nb_vois(i) = taille * 1.0 ;
                  int nb_contrib = 0;
                  for (int k = 0; k < taille; k++)
                    {
                      int num_som = voisins[k];
                      double d1 = 0.0;
                      for (int j = 0; j < nb_comp; j++)
{
                          double xf = dom.coord(num_som,j);
                          double xpf = solid_points(num_som,j);
                          d1 += (xf - xpf)*(xf - xpf);
                        }
                      d1 = sqrt(d1);
                      if (d1 > eps)
{
                          for (int j = 0; j < nb_comp; j++)
{
                              double vpf = vitesse_imposee_mod(num_som,j);
                              double vf = vitesse_inconnue(num_som,j);
                              mean_grad[j] += (vf - vpf)/d1;
                            }
                          nb_contrib += 1;
                        }
                    }
                  for (int j = 0; j < nb_comp; j++)
                    {
                      mean_grad[j] /= nb_contrib;
                      vitesse_imposee_calculee(i,j) += mean_grad[j]*d2;
                    }
                }
            }
        }
    }
// vitesse_imposee_calculee.echange_espace_virtuel();
// Cerr<<"Min/max/norme : nb_vois "<< mp_min_vect(nb_vois) << " " << mp_max_vect(nb_vois) << " " << mp_norme_vect(nb_vois) << finl;
}
References Domaine::coord(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), TRUSTListElem< _TYPE_ >::est_vide(), Interpolation_IBM_mean_gradient::getSommetsVoisinsOf(), Equation_base::inconnue(), Source_PDF_base::interpolation_lue_, Interpolation_IBM_mean_gradient_proto::is_dirichlet_, la_zone_EF, Source_PDF_base::modele_lu_, Zone::nb_som(), ref_cast, TRUSTList< _TYPE_ >::size(), Interpolation_IBM_base::solid_points_, Ref_Zone_EF::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Interpolation_IBM_base::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), PDF_model::vitesse_imposee_, Source_PDF_base::vitesse_imposee_, and Zone_dis_base::zone().
calculer_vitesse_imposee_power_law_tbl()
void Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl () override protected virtual
< l on met la norme unit tout en gardant la direction, on normalise quoi
< vf la vitesse totale
< partir de l commence l'expression de la loi de paroi polynomiale turbulente
< ici on effectue le test pour savoir si le noeud de frontire et le point fluide se trouvent dans la mme zone: si oui ok, si non on impose la vitesse
Reimplemented from Source_PDF_base.
Definition at line 937 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int nb_som=zone_EF.zone().nb_som();
  int nb_comp = dimension;
  const Domaine& dom = zone_EF.zone().domaine();
// const IntTab& elems= zone_EF.zone().les_elems();
  DoubleTab& vitesse_imposee_mod = modele_lu_.vitesse_imposee_.valeur().valeurs();
  DoubleTab& vitesse_imposee_calculee = vitesse_imposee_;
  Interpolation_IBM_power_law_tbl& interp = ref_cast(Interpolation_IBM_power_law_tbl,interpolation_lue_.valeur());
  DoubleTab& fluid_points = interp.fluid_points_.valeur().valeurs();
  DoubleTab& solid_points = interp.solid_points_.valeur().valeurs();
  DoubleTab& fluid_elems = interp.fluid_elems_.valeur().valeurs();
  double A_pwl = interp.get_A_pwl();
  double B_pwl = interp.get_B_pwl();
  double y_c_p_pwl = interp.get_y_c_p_pwl();
  int impr_yplus = interp.get_impr() ;
  Champ_Q1_EF& champ_vitesse_inconnue = ref_cast(Champ_Q1_EF,equation().inconnue().valeur());
  DoubleTab& val_vitesse_inconnue = champ_vitesse_inconnue.valeurs();
  DoubleTab xf(1, nb_comp);
  DoubleTab vf(1, nb_comp);
  ArrOfInt cells(1);
// operateur(0) : diffusivite
  if (equation().nombre_d_operateurs()<1)
    {
      Cerr << "Source_PDF_EF : nombre_d_operateurs = "<<equation().nombre_d_operateurs()<<" < 1"<<finl;
      exit();
    }
  int flag = 0;
  const Op_Diff_EF_base& opdiffu = ref_cast(Op_Diff_EF_base,equation().operateur(0).l_op_base());
  flag = opdiffu.diffusivite().valeurs().dimension(0)>1 ? 1 : 0;
  double eps = 1e-12;
  double d1_min = 1.0e+10;
  double d1_max = 0.0;
  double d1_mean = 0.0;
  double yplus_min = 1.0e+10;
  double yplus_max = 0.0;
  double yplus_mean = 0.0;
  double u_tau_min = 1.0e+10;
  double u_tau_max = 0.0;
  double u_tau_mean = 0.0;
  double yplus_ref_min = 1.0e+10;
  double yplus_ref_max = 0.0;
  double yplus_ref_mean = 0.0;
  int yplus_count=0 ;
  for (int i = 0; i < nb_som; i++)
    {
      int itisok = 1;
      if (fluid_elems(i) >= 0.0)
        {
          double d1 = 0.0;
          double d2 = 0.0;
          DoubleTab normale(1, nb_comp);
          double norme_de_la_normale= 0.0;
          for(int j = 0; j < nb_comp; j++)
            {
              double xj = dom.coord(i,j);
              double xjf = fluid_points(i,j);
              xf(0, j) = xjf;
              double xjs = solid_points(i,j);
              d1 += (xj-xjs)*(xj-xjs);
              d2 += (xjf-xj)*(xjf-xj);
              normale(0,j) = xjf - xjs;
              norme_de_la_normale += normale(0,j)*normale(0,j);
            }
          d1 = sqrt(d1);
          d2 = sqrt(d2);
          norme_de_la_normale = sqrt(norme_de_la_normale);
          if ( norme_de_la_normale > eps )
            for(int j = 0; j < nb_comp; j++) normale(0,j) /= norme_de_la_normale; //!< l on met la norme unit tout en gardant la direction, on normalise quoi
          else
            {
              for(int j = 0; j < nb_comp; j++) normale(0,j) = 0.;
              itisok = 0;
            }
          double y_ref= d1+d2;
          if ( y_ref < eps )
            {
              y_ref = 1.;
              itisok = 0;
            }
          cells(0) = int(fluid_elems(i));
          champ_vitesse_inconnue.value_interpolation(xf,cells, val_vitesse_inconnue, vf); //!< vf la vitesse totale
          double Vn = 0.;
          for(int j = 0; j < nb_comp; j++) Vn +=vf(0, j) * normale(0,j);
          DoubleTab v_ref_t(1, nb_comp);
          for(int j = 0; j < nb_comp; j++) v_ref_t(0, j) =vf(0, j) - Vn*normale(0,j);
          double norme_v_ref_t = 0.;
          for(int j = 0; j < nb_comp; j++) norme_v_ref_t +=  v_ref_t(0, j)*v_ref_t(0,j)  ;
          norme_v_ref_t = sqrt ( norme_v_ref_t );
          double nu = (flag ? opdiffu.diffusivite().valeurs()(cells) : opdiffu.diffusivite().valeurs()(0,0));
// On calcule U_tau pour pouvoir calculer les quantite adimensiones (y+ ...)
          double u_tau = pow ( norme_v_ref_t , (1/(1+B_pwl)) ) * pow ( A_pwl, (-1/(1+B_pwl)) )  * pow ( y_ref , (-B_pwl/(1+B_pwl)) ) * pow ( nu,(B_pwl/(1+B_pwl)) ) ;
          double y_plus = u_tau * d1 / nu;
// Cerr<<"u_tau  d1  nu ="<<u_tau<<" "<<d1<<" "<<nu<<finl;;
          double y_ref_p = y_ref * u_tau  / nu;  //l on a enfin tout ce qu'il faut pour tablir la loi polynomiale pour y r+
          double test_ref;
          if ( y_ref_p > y_c_p_pwl)  //!<  partir de l commence l'expression de la loi de paroi polynomiale turbulente
            {
              for(int j = 0; j < nb_comp; j++) vitesse_imposee_calculee(i,j) =  v_ref_t(0,j) * pow ( d1 / y_ref , B_pwl )  ;
              test_ref = 1.;
// Cerr << "zone log/sous-couche inertielle" << finl;
            }
          else
            {
              for(int j = 0; j < nb_comp; j++) vitesse_imposee_calculee(i,j) =  v_ref_t(0,j) * ( d1 / y_ref )   ;
              test_ref = -1. ;
// Cerr << "zone lineaire/sous-couche visqueuse" << finl;
            }                   //!< Fin LdPturb
          if (impr_yplus && itisok && (indicateur_nodal_champ_aire_(i)==1.))
            {
              if (d1 > d1_max) d1_max = d1;
              if (d1 < d1_min) d1_min = d1;
              d1_mean +=  d1;
              if (y_plus > yplus_max) yplus_max = y_plus;
              if (y_plus < yplus_min) yplus_min = y_plus;
              yplus_mean +=  y_plus;
              if (y_ref_p > yplus_ref_max) yplus_ref_max = y_ref_p;
              if (y_ref_p < yplus_ref_min) yplus_ref_min = y_ref_p;
              yplus_ref_mean += y_ref_p;
              if (u_tau > u_tau_max) u_tau_max = u_tau;
              if (u_tau < u_tau_min) u_tau_min = u_tau;
              u_tau_mean += u_tau;
              yplus_count += 1;
            }
          double test_;  //!< ici on effectue le test pour savoir si le noeud de frontire et le point fluide se trouvent dans la mme zone: si oui ok, si non on impose la vitesse
          if (y_plus > y_c_p_pwl )
            {
              test_ = 1.;
            }
          else
            {
              test_ = -1.        ;
            }
// Traitement des exceptions
          if ( (test_ * test_ref < 0) || (itisok == 0) )  //si non on impose la vitesse
            {
              for(int j = 0; j < nb_comp; j++)  vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j);
// Cerr << "erreur" << finl;
            }
        }
      else
        {
          for(int j = 0; j < nb_comp; j++)
            {
              vitesse_imposee_calculee(i,j) = vitesse_imposee_mod(i,j);
            }
        }
    }
// vitesse_imposee_calculee.echange_espace_virtuel();
  if (impr_yplus && (yplus_count >= 1) )
    {
      d1_mean /= yplus_count;
      yplus_mean /= yplus_count;
      yplus_ref_mean /= yplus_count;
      u_tau_mean /= yplus_count;
      Cerr<<"min mean max y  = "<<d1_min<<" "<<d1_mean<<" "<<d1_max<<finl;
      Cerr<<"min mean max y+ = "<<yplus_min<<" "<<yplus_mean<<" "<<yplus_max<<finl;
      Cerr<<"min mean max y+_ref = "<<yplus_ref_min<<" "<<yplus_ref_mean<<" "<<yplus_ref_max<<finl;
      Cerr<<"min mean u_tau = "<<u_tau_min<<" "<<u_tau_mean<<" "<<u_tau_max<<finl;
      Cerr<<"Moyenne sur "<<yplus_count<<" points"<<finl;
    }
}
References Cerr, Domaine::coord(), Operateur_Diff_base::diffusivite(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), MorEqn::equation(), Process::exit(), finl, Interpolation_IBM_elem_fluid::fluid_elems_, Interpolation_IBM_elem_fluid::fluid_points_, Interpolation_IBM_power_law_tbl::get_A_pwl(), Interpolation_IBM_power_law_tbl::get_B_pwl(), Interpolation_IBM_base::get_impr(), Interpolation_IBM_power_law_tbl::get_y_c_p_pwl(), Source_PDF_base::indicateur_nodal_champ_aire_, Source_PDF_base::interpolation_lue_, la_zone_EF, Source_PDF_base::modele_lu_, Zone::nb_som(), Equation_base::nombre_d_operateurs(), ref_cast, Interpolation_IBM_base::solid_points_, Ref_Zone_EF::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Interpolation_IBM_base::valeur(), valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Champ_implementation_Q1::value_interpolation(), PDF_model::vitesse_imposee_, Source_PDF_base::vitesse_imposee_, and Zone_dis_base::zone().
compute_coeff_elem()
DoubleTab Source_PDF_EF::compute_coeff_elem () const override virtual
Reimplemented from Source_PDF_base.
Definition at line 301 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems() ;
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int nb_elems=zone_EF.zone().nb_elem_tot();
  ArrOfDouble vitesse_elem(dimension);
  const DoubleTab& rotation=champ_rotation_.valeurs();
  const DoubleTab& aire = champ_aire_.valeurs();
  int dim_esp = Objet_U::dimension ;
  DoubleTab coeff(nb_elems, dim_esp);
  const double dt_ref = equation().probleme().schema_temps().pas_de_temps();
  const double dt_min = equation().probleme().schema_temps().pas_temps_min();
  double dt = std::max(dt_ref,dt_min);
  const DoubleTab& rho_m=champ_rho_.valeurs();
  if (equation().probleme().schema_temps().temps_courant()==0)
    {
      dt = 1.0;
    }
// Cerr<<"dt pour compute_coeff_elem : "<< dt <<finl;
  double val_coeff ;
  DoubleVect val_diag_coef(dim_esp);
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      if (aire(num_elem)<=0.)
        {
          for (int comp=0; comp<dim_esp; comp++) coeff(num_elem, comp) = 1. ;
        }
      else
        {
          const DoubleTab& vitesse=equation().inconnue().valeurs();
          vitesse_elem=0;
          for (int s=0; s<nb_som_elem; s++)
            {
              int som_glob=elems(num_elem,s);
              for (int comp=0; comp<dimension; comp++)
                vitesse_elem[comp]+=vitesse(som_glob,comp);
            }
          val_coeff = fonct_coeff(rho_m(num_elem), aire(num_elem), dt) ;
          val_diag_coef = diag_coeff_elem(vitesse_elem, rotation, num_elem) ;
          for (int comp=0; comp<dim_esp; comp++)
            coeff(num_elem, comp) = 1.+ val_coeff * val_diag_coef(comp) * dt / rho_m(num_elem) ;
        }
    }
  return coeff;
}
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, coeff, diag_coeff_elem(), Objet_U::dimension, MorEqn::equation(), Source_PDF_base::fonct_coeff(), Equation_base::inconnue(), la_zone_EF, Zone::les_elems(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), Probleme_base::schema_temps(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
compute_coeff_matrice_pression()
DoubleTab Source_PDF_EF::compute_coeff_matrice_pression () const override virtual
Reimplemented from Source_PDF_base.
Definition at line 351 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int nb_elems=zone_EF.zone().nb_elem_tot();
  int nb_som_tot=zone_EF.zone().nb_som_tot();
  ArrOfDouble vitesse_elem(dimension);
  const DoubleTab& rotation=champ_rotation_.valeurs();
  const DoubleTab& aire = champ_aire_.valeurs();
  int dim_esp = Objet_U::dimension ;
  const DoubleTab& vitesse=equation().inconnue().valeurs();
  DoubleTab coeff(vitesse);
  IntTab contrib(nb_som_tot, dim_esp);
  contrib = 0;
  coeff = 0.;
  const double dt_ref = equation().probleme().schema_temps().pas_de_temps();
  const double dt_min = equation().probleme().schema_temps().pas_temps_min();
  double dt = std::max(dt_ref,dt_min);
  const DoubleTab& rho_m=champ_rho_.valeurs();
  if (equation().probleme().schema_temps().temps_courant()==0)
    {
      dt = 1.0;
    }
// Cerr<<"dt pour compute_coeff_matrice_pression : "<< dt <<finl;
  double val_coeff ;
  DoubleVect val_diag_coef(dim_esp), coeff_el(dim_esp) ;
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      if (aire(num_elem)<=0.)
        {
          for (int comp=0; comp<dim_esp; comp++) coeff_el(comp) = 0. ;
        }
      else
        {
          vitesse_elem=0.;
          for (int s=0; s<nb_som_elem; s++)
            {
              int som_glob=elems(num_elem,s);
              for (int comp=0; comp<dimension; comp++)
                vitesse_elem[comp]+=vitesse(som_glob,comp);
            }
          val_coeff = fonct_coeff(rho_m(num_elem), aire(num_elem), dt) ;
          val_diag_coef = diag_coeff_elem(vitesse_elem, rotation, num_elem) ;
          for (int comp=0; comp<dim_esp; comp++)
            coeff_el(comp) = val_coeff * val_diag_coef(comp) * dt / rho_m(num_elem) ;
        }
      for (int i = 0; i<nb_som_elem; i++)
        {
          int s = elems(num_elem,i);
          for (int comp=0; comp<dim_esp; comp++)
            {
              if (coeff_el(comp) > 0.)
                {
                  coeff(s,comp)+= coeff_el(comp);
                  contrib(s, comp) += 1;
                }
            }
        }
    }
  double val = 0.;
  for (int s = 0; s<nb_som_tot; s++)
    {
      for (int comp=0; comp<dim_esp; comp++)
        {
          val = 1.;
          if (contrib(s,comp) != 0)
            {
              val += coeff(s,comp)/contrib(s,comp);
            }
          coeff(s,comp) = val;
        }
    }
  return coeff;
}
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, coeff, diag_coeff_elem(), Objet_U::dimension, MorEqn::equation(), Source_PDF_base::fonct_coeff(), Equation_base::inconnue(), la_zone_EF, Zone::les_elems(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Zone::nb_som_tot(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), Probleme_base::schema_temps(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
compute_indicateur_nodal_champ_aire()
void Source_PDF_EF::compute_indicateur_nodal_champ_aire () override protected virtual
Reimplemented from Source_PDF_base.
Definition at line 152 of file Source_PDF_EF.cpp.
{
  const DoubleTab& aire=champ_aire_.valeurs();
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int nb_elems=zone_EF.zone().nb_elem_tot();
  int nb_nodes=zone_EF.zone().nb_som_tot();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  const IntTab& elems= zone_EF.zone().les_elems() ;
  DoubleTab indic(nb_nodes);
  indic = 0.;
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      if (aire(num_elem)>0.)
        {
          for (int i=0; i<nb_som_elem; i++)
            {
              int s1=elems(num_elem,i);
              indic(s1) = 1.;
            }
        }
    }
  indicateur_nodal_champ_aire_ = indic;
}
References Source_PDF_base::champ_aire_, Source_PDF_base::indicateur_nodal_champ_aire_, la_zone_EF, Zone::les_elems(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Zone::nb_som_tot(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
Referenced by associer_pb().
compute_pond()
DoubleTab Source_PDF_EF::compute_pond (const DoubleTab & rho_m, const DoubleTab & aire, const DoubleVect & volume_thilde, int & nb_som_elem, int & nb_elems) const protected
Definition at line 448 of file Source_PDF_EF.cpp.
{
  DoubleTab pond = rho_m;
  double inv_nb_som = 1. / nb_som_elem;
  const double dt_ref = equation().probleme().schema_temps().pas_de_temps();
  const double dt_min = equation().probleme().schema_temps().pas_temps_min();
  double dt = std::max(dt_ref,dt_min);
  if (equation().probleme().schema_temps().temps_courant()==0)
    {
      dt = 1.0;
    }
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      pond(num_elem) = fonct_coeff(rho_m(num_elem), aire(num_elem), dt) ;
      pond(num_elem) *= volume_thilde(num_elem)*inv_nb_som*inv_nb_som;
    }
  return pond;
}
References MorEqn::equation(), Source_PDF_base::fonct_coeff(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), and Probleme_base::schema_temps().
Referenced by ajouter_(), and contribuer_a_avec().
compute_vitesse_imposee_projete()
void Source_PDF_EF::compute_vitesse_imposee_projete (const DoubleTab & marqueur, const DoubleTab & points, double val, double eps) override protected virtual
Reimplemented from Source_PDF_base.
Definition at line 177 of file Source_PDF_EF.cpp.
{
  int nb_som=la_zone_EF.valeur().zone().nb_som();
  int dim = Objet_U::dimension;
  const DoubleTab& coords = la_zone_EF.valeur().zone().domaine().coord_sommets();
  ArrOfDouble x(dim);
  for (int i = 0; i < nb_som; i++)
    {
      if ((marqueur(i) >= val + eps) || (marqueur(i) <= val - eps))
        {
          for (int j = 0; j < dim; j++)
            {
              x[j] = points(i,j);
            }
          for (int j = 0; j < dim; j++)
            {
              modele_lu_.vitesse_imposee_(i,j) = modele_lu_.get_vitesse_imposee(x,j);
            }
        }
      else
        {
          for (int j = 0; j < dim; j++)
            {
              x[j] = coords(i,j);
            }
          for (int j = 0; j < dim; j++)
            {
              modele_lu_.vitesse_imposee_(i,j) = modele_lu_.get_vitesse_imposee(x,j);
            }
        }
    }
}
References Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), PDF_model::get_vitesse_imposee(), la_zone_EF, Source_PDF_base::modele_lu_, Zone::nb_som(), Ref_Zone_EF::valeur(), PDF_model::vitesse_imposee_, and Zone_dis_base::zone().
Referenced by associer_pb().
contribuer_a_avec()
void Source_PDF_EF::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 600 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int nb_elems=zone_EF.zone().nb_elem_tot();
  const DoubleVect& volume_thilde=zone_EF.volumes_thilde();
  int ncomp=dimension;
  ArrOfDouble tuvw(dimension);
// const DoubleTab& vitesse=equation().inconnue().valeurs();
  const DoubleTab& rotation=champ_rotation_.valeurs();
  const DoubleTab& aire=champ_aire_.valeurs();
// champ_rho_.valeur().affecter(equation().probleme().get_champ("masse_volumique"));
  const DoubleTab& rho_m=champ_rho_.valeurs();
  DoubleTab pond ;
  pond = compute_pond(rho_m, aire, volume_thilde, nb_som_elem, nb_elems);
  for (int num_elem=0; num_elem<nb_elems; num_elem++) //elements loop
    {
      if (aire(num_elem)>0.)
        {
          tuvw[0] = 1.0 / modele_lu_.eta_;
          tuvw[1] = 1.0 / modele_lu_.eta_;
          tuvw[2] = 1.0 / modele_lu_.eta_;
          for (int comp=0; comp<ncomp; comp++)
            {
              for (int comp2=0; comp2<ncomp; comp2++)
                {
                  for (int i=0; i<nb_som_elem; i++)
                    {
                      for (int j=0; j<nb_som_elem; j++)
{
                          int s1=elems(num_elem,i);
                          double coeff_im=0;
                          for (int k=0; k<3; k++)
{
                              coeff_im+=rotation(num_elem,3*k+comp)*tuvw[k]*rotation(num_elem,3*k+comp2);
                            }
                          int c1=s1*ncomp+comp;
                          matrice.coef(c1,c1)+=pond(num_elem)*coeff_im;
                        }
                    }
                }
            }
        }
    }
// verif_ajouter_contrib(vitesse, matrice) ;
}
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, Matrice_Morse::coef(), compute_pond(), Objet_U::dimension, PDF_model::eta_, la_zone_EF, Zone::les_elems(), Source_PDF_base::modele_lu_, Zone::nb_elem_tot(), Zone::nb_som_elem(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), Zone_EF::volumes_thilde(), and Zone_dis_base::zone().
correct_incr_pressure()
void Source_PDF_EF::correct_incr_pressure (const DoubleTab & coeff_node, DoubleTab & correction_en_pression) const override virtual
Reimplemented from Source_PDF_base.
Definition at line 1122 of file Source_PDF_EF.cpp.
{
  const DoubleTab& aire=champ_aire_.valeurs();
  int nb_elem = correction_en_pression.size();
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int ncomp = coeff_node.dimension(1) ;
  DoubleTrav coef_elem(nb_elem);
  const Zone_Cl_EF& la_zone_cl = la_zone_Cl_EF.valeur();
  int nb_cond_lim = la_zone_cl.nb_cond_lim();
  const IntTab& faces_sommets=zone_EF.face_sommets();
  int nb_som_face=faces_sommets.dimension(1);
  DoubleTrav flag_cl(coeff_node);
  flag_cl = 1.;
  for (int ij=0; ij<nb_cond_lim; ij++)
    {
      const Cond_lim_base& la_cl_base = la_zone_cl.les_conditions_limites(ij).valeur();
      const Front_VF& le_bord = ref_cast(Front_VF,la_zone_cl.les_conditions_limites(ij).frontiere_dis());
      int nfaces = le_bord.nb_faces_tot();
      if (sub_type(Dirichlet,la_cl_base))
        {
          for (int ind_face=0; ind_face < nfaces; ind_face++)
            {
              for (int s=0; s<nb_som_face; s++)
                {
                  int face=le_bord.num_face(ind_face);
                  int som=faces_sommets(face,s);
                  for (int comp=0; comp<ncomp; comp++) flag_cl(som,comp) = 0. ;
                }
            }
        }
    }
  la_zone_cl.imposer_symetrie(flag_cl,0);
// int nb_som=zone_EF.zone().nb_som();
// for(int som=0; som<nb_som; som++)Cerr<<"som flag_c = "<<som<<" "<<flag_cl(som,0)<<" "<<flag_cl(som,1)<<" "<<flag_cl(som,2)<<finl;
  for(int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      if (aire(num_elem)>0.)
        {
          correction_en_pression(num_elem) = 0.;
        }
      else
        {
          coef_elem(num_elem) = 0. ;
          for (int i=0; i<nb_som_elem; i++)
            {
              int sii=elems(num_elem,i);
              for (int comp=0; comp<ncomp; comp++)
                {
                  if ((coeff_node(sii,comp)!= 1.0) || (flag_cl(sii,comp) != 1.0)) coef_elem(num_elem) += 1. ;
                }
            }
          if (coef_elem(num_elem) == (ncomp*nb_som_elem)) correction_en_pression(num_elem) = 0.;
        }
    }
}
References Source_PDF_base::champ_aire_, TRUSTTab< _TYPE_ >::dimension(), Zone_VF::face_sommets(), Cond_lim::frontiere_dis(), Zone_Cl_EF::imposer_symetrie(), la_zone_Cl_EF, la_zone_EF, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Zone::nb_som_elem(), Front_VF::num_face(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Cond_lim_base::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
correct_pressure()
void Source_PDF_EF::correct_pressure (const DoubleTab & coeff_node, DoubleTab & pression, const DoubleTab & correction_en_pression) const override virtual
Reimplemented from Source_PDF_base.
Definition at line 1183 of file Source_PDF_EF.cpp.
{
  const DoubleTab& aire=champ_aire_.valeurs();
  int nb_elem = pression.size();
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int ncomp = coeff_node.dimension(1) ;
  DoubleTrav coef_elem(nb_elem);
  const Zone_Cl_EF& la_zone_cl = la_zone_Cl_EF.valeur();
  int nb_cond_lim = la_zone_cl.nb_cond_lim();
  const IntTab& faces_sommets=zone_EF.face_sommets();
  int nb_som_face=faces_sommets.dimension(1);
  DoubleTrav flag_cl(coeff_node);
  flag_cl = 1.;
  for (int ij=0; ij<nb_cond_lim; ij++)
    {
      const Cond_lim_base& la_cl_base = la_zone_cl.les_conditions_limites(ij).valeur();
      const Front_VF& le_bord = ref_cast(Front_VF,la_zone_cl.les_conditions_limites(ij).frontiere_dis());
      int nfaces = le_bord.nb_faces_tot();
      if (sub_type(Dirichlet,la_cl_base))
        {
          for (int ind_face=0; ind_face < nfaces; ind_face++)
            {
              for (int s=0; s<nb_som_face; s++)
                {
                  int face=le_bord.num_face(ind_face);
                  int som=faces_sommets(face,s);
                  for (int comp=0; comp<ncomp; comp++) flag_cl(som,comp) = 0. ;
                }
            }
        }
    }
  la_zone_cl.imposer_symetrie(flag_cl,0);
  for(int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      if (aire(num_elem)<=0.)
        {
          coef_elem(num_elem) = 0. ;
          for (int i=0; i<nb_som_elem; i++)
            {
              int sii=elems(num_elem,i);
              for (int comp=0; comp<ncomp; comp++)
                {
                  if ((coeff_node(sii,comp)!= 1.0) || (flag_cl(sii,comp) != 1.0)) coef_elem(num_elem) += 1. ;
                }
            }
          if (coef_elem(num_elem) != (ncomp*nb_som_elem)) pression(num_elem)+=correction_en_pression(num_elem);
        }
    }
}
References Source_PDF_base::champ_aire_, TRUSTTab< _TYPE_ >::dimension(), Zone_VF::face_sommets(), Cond_lim::frontiere_dis(), Zone_Cl_EF::imposer_symetrie(), la_zone_Cl_EF, la_zone_EF, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Zone::nb_som_elem(), Front_VF::num_face(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Ref_Zone_Cl_EF::valeur(), Ref_Zone_EF::valeur(), Deriv_Cond_lim_base::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
correct_vitesse()
void Source_PDF_EF::correct_vitesse (const DoubleTab & coeff_node, DoubleTab & vitesse) const override virtual
Reimplemented from Source_PDF_base.
Definition at line 1238 of file Source_PDF_EF.cpp.
{
  int nb_data_vit = vitesse.size();
  int nb_node_2 = coeff_node.dimension(0) ;
  int ncomp = coeff_node.dimension(1) ;
  if (nb_data_vit != nb_node_2 * ncomp)
    {
      Cerr<<"Source_PDF: numbers of nodes are different for vitesse and champ_coeff_tfsdia_gb_som_"<<finl;
      abort();
    }
  const DoubleTab& vit_dir=vitesse_imposee_;
  for(int i=0; i<nb_node_2; i++)
    {
      for (int j=0; j<ncomp; j++)
        {
          if (coeff_node(i,j)!= 1.0)
            {
              vitesse(i,j)=vit_dir(i,j);
            }
        }
    }
}
References Process::abort(), Cerr, TRUSTTab< _TYPE_ >::dimension(), finl, TRUSTVect< _TYPE_ >::size(), and Source_PDF_base::vitesse_imposee_.
cree_instance()
Objet_U * Source_PDF_EF::cree_instance () static
Definition at line 37 of file Source_PDF_EF.cpp.
diag_coeff_elem()
DoubleVect Source_PDF_EF::diag_coeff_elem (ArrOfDouble & vitesse_elem, const DoubleTab & rotation, int num_elem) const override virtual
Reimplemented from Source_PDF_base.
Definition at line 275 of file Source_PDF_EF.cpp.
{
  assert(Objet_U::dimension==3);
  ArrOfDouble tuvw(dimension);
  tuvw = get_tuvw_local();
  ArrOfDouble sum_dir_loc(dimension) ;
  for (int i=0; i<dimension; i++)
    {
      sum_dir_loc[i]=0.;
      for (int k=0; k<dimension; k++)
        sum_dir_loc[i]+=rotation(num_elem,3*i+k);
    }
  DoubleVect diag_coef(dimension);
  for (int comp=0; comp<dimension; comp++)
    {
      diag_coef(comp) = 0. ;
      for (int k=0; k<dimension; k++)
        diag_coef(comp)+=tuvw[k]*sum_dir_loc[k]*rotation(num_elem,3*k+comp);
    }
  return diag_coef ;
}
References Objet_U::dimension, and Source_PDF_base::get_tuvw_local().
Referenced by compute_coeff_elem(), and compute_coeff_matrice_pression().
duplique()
int Source_PDF_EF::duplique () const override virtual
Implements Objet_U.
Definition at line 37 of file Source_PDF_EF.cpp.
get_info()
const Type_info * Source_PDF_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 37 of file Source_PDF_EF.cpp.
impr()
int Source_PDF_EF::impr (Sortie & os) const override virtual
Reimplemented from Source_base.
Definition at line 1261 of file Source_PDF_EF.cpp.
{
  if (out_=="??")
    {
      Cerr << __FILE__ << (int)__LINE__ << " ERROR / Source_PDF_EF::impr" << finl;
      Cerr << "No balance printed for " << que_suis_je() << finl;
      Cerr << "Because output file name is not specified." << finl;
      return 0;
    }
  else
    {
      int nb_compo=bilan_.size();
      if (nb_compo==0)
        {
          Cerr << __FILE__ << (int)__LINE__ << " ERROR / Source_PDF_EF::impr" << finl;
          Cerr << "No balance printed for " << que_suis_je() << finl;
          Cerr << "Because bilan_ array is not filled." << finl;
          return 0;
        }
      else
        {
          const Schema_Temps_base& sch=equation().probleme().schema_temps();
          double temps=sch.temps_courant();
          double pdtps = sch.pas_de_temps();
          if (temps == pdtps) return 0;
          const DoubleTab& vitesse=equation().inconnue().valeurs();
          int nb_som=la_zone_EF.valeur().zone().nb_som();
          Nom espace=" \t";
          Navier_Stokes_std& eq_NS = ref_cast_non_const(Navier_Stokes_std, equation());
          DoubleTrav secmem_conv(vitesse);
          int transport_rhou=0;
          if (eq_NS.nombre_d_operateurs() > 1)
            {
              transport_rhou= (eq_NS.vitesse_pour_transport().le_nom()=="rho_u"?1:0);
              eq_NS.derivee_en_temps_conv(secmem_conv , vitesse);
            }
          int pdf_dt_conv = 0;
          if (!pdf_dt_conv) secmem_conv *= 0.;
          int i_traitement_special = (pdf_dt_conv==1?(transport_rhou==1?2:102):0);
          DoubleTrav resu(vitesse);
          calculer(resu, i_traitement_special);
          DoubleVect source_term[3];
          bilan_ = 0.0;
          for (int i=0; i<dimension; i++)
            {
              source_term[i] = champ_nodal_.valeurs();
              source_term[i] = 0.;
              for (int j=0; j<nb_som; j++)
                {
                  int filter = (std::fabs(resu(j,i)) > 1.e-6?1:0);
                  source_term[i](j) = resu(j,i) - sec_mem_pdf(j,i) + secmem_conv(j,i)*filter;
                }
              bilan_(i) = mp_somme_vect(source_term[i]);
            }
          int flag = Process::je_suis_maitre();
          if(flag)
            {
              SFichier Flux;
              ouvrir_fichier(Flux,"",flag);
              Flux << temps << espace << bilan_(0) << espace << bilan_(1) << espace << bilan_(2) << finl;
            }
        }
      return 1;
    }
}
References Source_base::bilan_, Source_PDF_base::calculer(), Cerr, champ_nodal_, Equation_base::derivee_en_temps_conv(), Objet_U::dimension, MorEqn::equation(), finl, Equation_base::inconnue(), Process::je_suis_maitre(), la_zone_EF, Field_base::le_nom(), mp_somme_vect(), Zone::nb_som(), Navier_Stokes_std::nombre_d_operateurs(), Source_base::out_, Source_PDF_base::ouvrir_fichier(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast_non_const, Probleme_base::schema_temps(), Source_PDF_base::sec_mem_pdf, TRUSTVect< _TYPE_ >::size(), Schema_Temps_base::temps_courant(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), Champ_Inc::valeurs(), Navier_Stokes_std::vitesse_pour_transport(), and Zone_dis_base::zone().
info()
const Type_info * Source_PDF_EF::info () static
Definition at line 37 of file Source_PDF_EF.cpp.
multiply_coeff_volume()
void Source_PDF_EF::multiply_coeff_volume (DoubleTab & coeff) const override virtual
Reimplemented from Source_PDF_base.
Definition at line 431 of file Source_PDF_EF.cpp.
{
  const DoubleVect& vol_som=ref_cast(Zone_EF, la_zone_EF.valeur()).volumes_sommets_thilde();
  int n = vol_som.size_totale();
  int nc = coeff.dimension_tot(0) ;
  if (n != nc)
    {
      Cerr<<" dimensions differentes n nc = "<<n<<" "<<nc<<finl;
      exit();
    }
  int ndim = coeff.dimension(1) ;
  for (int i=0; i<n; i++)
    {
      for (int comp=0; comp<ndim; comp++) coeff(i,comp) = coeff(i,comp)*vol_som(i);
    }
}
References Cerr, coeff, Process::exit(), finl, la_zone_EF, ref_cast, TRUSTVect< _TYPE_ >::size_totale(), and Ref_Zone_EF::valeur().
printOn()
Sortie & Source_PDF_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 52 of file Source_PDF_EF.cpp.
{
  return s << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Source_PDF_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 46 of file Source_PDF_EF.cpp.
{
  Source_PDF_base::readOn(s);
  return s;
}
References Source_PDF_base::readOn().
rotate_imposed_velocity()
void Source_PDF_EF::rotate_imposed_velocity (DoubleTab & vitesse_imposee) override protected virtual
Reimplemented from Source_PDF_base.
Definition at line 210 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int nb_elem_tot=zone_EF.zone().nb_elem_tot();
  DoubleTab& rotation = champ_rotation_.valeurs();
  int nb_som_tot=zone_EF.zone().nb_som_tot();
// COPIES
  DoubleTab vitesse = vitesse_imposee;
// vitesse_imposee.echange_espace_virtuel();
  DoubleTrav marqueur=equation().probleme().get_champ("vitesse").valeurs();
  vitesse_imposee = 0.;
  marqueur = 0.;
  for (int num_elem=0; num_elem<nb_elem_tot; num_elem++)
    {
      double norm =  sqrt(rotation(num_elem,0)*rotation(num_elem,0)
                          +rotation(num_elem,1)*rotation(num_elem,1)
                          +rotation(num_elem,2)*rotation(num_elem,2)
                          +rotation(num_elem,3)*rotation(num_elem,3)
                          +rotation(num_elem,4)*rotation(num_elem,4)
                          +rotation(num_elem,5)*rotation(num_elem,5)
                          +rotation(num_elem,6)*rotation(num_elem,6)
                          +rotation(num_elem,7)*rotation(num_elem,7)
                          +rotation(num_elem,8)*rotation(num_elem,8));
      if (norm > 1e-6)
        {
          for (int i=0; i<nb_som_elem; i++)
            {
              int s = elems(num_elem,i);
              for (int c=0; c<3; c++)
                {
                  for (int k=0; k<3; k++)
                    {
                      vitesse_imposee(s,c) += rotation(num_elem,3*c+k)*vitesse(s,k);
// Cerr << "k = " << k << ", c = " << c << ", 3*c+k = " << 3*c+k << ", rotation = " << rotation(num_elem,3*c+k) << finl;
                    }
                }
              marqueur(s,0) += 1.0;
            }
        }
    }
  for (int i=0; i<nb_som_tot; i++)
    {
      if(marqueur(i,0) > 0.)
        {
          for (int c=0; c<3; c++)
            {
              vitesse_imposee(i,c) /= marqueur(i,0);
            }
        }
    }
}
References Source_PDF_base::champ_rotation_, MorEqn::equation(), Probleme_base::get_champ(), la_zone_EF, Zone::les_elems(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Zone::nb_som_tot(), Equation_base::probleme(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
Referenced by associer_pb().
self_cast() [1/2]
const Source_PDF_EF & Source_PDF_EF::self_cast (const Objet_U & r) static
Definition at line 37 of file Source_PDF_EF.cpp.
self_cast() [2/2]
Source_PDF_EF & Source_PDF_EF::self_cast (Objet_U & r) static
Definition at line 37 of file Source_PDF_EF.cpp.
taille_memoire()
unsigned Source_PDF_EF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 37 of file Source_PDF_EF.cpp.
test()
void Source_PDF_EF::test (Matrice &) const
updateChampRho()
void Source_PDF_EF::updateChampRho ()
verif_ajouter_contrib()
void Source_PDF_EF::verif_ajouter_contrib (const DoubleTab & vitesse, Matrice_Morse & matrice) const
Definition at line 653 of file Source_PDF_EF.cpp.
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  const IntTab& elems= zone_EF.zone().les_elems() ;
  int nb_elems=zone_EF.zone().nb_elem_tot();
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  const DoubleTab& aire=champ_aire_.valeurs();
  DoubleTrav force(vitesse);
  ajouter_(vitesse,force);
  DoubleTrav force2(vitesse);
  matrice.ajouter_multvect_(vitesse, force2) ;
  DoubleTab diforce(force);
  diforce += force2 ;
  double difmax = 0.;
  for (int num_elem=0; num_elem<nb_elems; num_elem++)
    {
      if (aire(num_elem)>0.)
        {
          for (int i=0; i<nb_som_elem; i++)
            {
              int s1=elems(num_elem,i);
              double difmod2 = diforce(s1,0)*diforce(s1,0) + diforce(s1,1)*diforce(s1,1) + diforce(s1,2)*diforce(s1,2);
              if (difmod2 > 1.0e-5)
                {
                  if (difmod2 > difmax) difmax = difmod2 ;
// Cerr << " ajouter multvect diforce x = "<< force(s1,0) << " "<< force2(s1,0) << " " << diforce(s1,0)<<endl;
// Cerr << " ajouter multvect diforce y = "<< force(s1,1) << " "<< force2(s1,1) << " " << diforce(s1,1)<<endl;
// Cerr << " ajouter multvect diforce z = "<< force(s1,2) << " "<< force2(s1,2) << " " << diforce(s1,2)<<endl;
                }
            }
        }
    }
  if (difmax > 0.)
    {
      Cerr<< "Source_PDF: Max norme caree diff. force absolue = "<<difmax<<endl;
    }
}
References ajouter_(), Matrice_Morse::ajouter_multvect_(), Cerr, Source_PDF_base::champ_aire_, la_zone_EF, Zone::les_elems(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Ref_Zone_EF::valeur(), Champ_Don::valeurs(), and Zone_dis_base::zone().
Member Data Documentation
champ_nodal_
Champ_Don Source_PDF_EF::champ_nodal_ protected
Definition at line 59 of file Source_PDF_EF.h.
Referenced by associer_pb(), and impr().
info_obj
const Type_info Source_PDF_EF::info_obj static
Definition at line 39 of file Source_PDF_EF.h.
la_zone_Cl_EF
Ref_Zone_Cl_EF Source_PDF_EF::la_zone_Cl_EF protected
Definition at line 68 of file Source_PDF_EF.h.
Referenced by associer_zones(), correct_incr_pressure(), and correct_pressure().
la_zone_EF
Ref_Zone_EF Source_PDF_EF::la_zone_EF protected
Definition at line 67 of file Source_PDF_EF.h.
Referenced by ajouter_(), associer_pb(), associer_zones(), calculer_vitesse_imposee_elem_fluid(), calculer_vitesse_imposee_hybrid(), calculer_vitesse_imposee_mean_grad(), calculer_vitesse_imposee_power_law_tbl(), compute_coeff_elem(), compute_coeff_matrice_pression(), compute_indicateur_nodal_champ_aire(), compute_vitesse_imposee_projete(), contribuer_a_avec(), correct_incr_pressure(), correct_pressure(), impr(), multiply_coeff_volume(), rotate_imposed_velocity(), and verif_ajouter_contrib().
The documentation for this class was generated from the following files:
src/EF/Sources/Source_PDF_EF.h
src/EF/Sources/Source_PDF_EF.cpp