TRUST: Deriv_Interpolation_IBM_base Class Reference
Deriv_Interpolation_IBM_base Class Reference
#include <Interpolation_IBM.h>
Public Member Functions
~Deriv_Interpolation_IBM_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Interpolation_IBM_base ()
Deriv_Interpolation_IBM_base (const Deriv_Interpolation_IBM_base &)
const Interpolation_IBM_base & valeur () const
Interpolation_IBM_base & valeur ()
const Interpolation_IBM_base * operator-> () const
Interpolation_IBM_base * operator-> ()
const
Deriv_Interpolation_IBM_base & operator= (const Interpolation_IBM_base &)
const
Deriv_Interpolation_IBM_base & operator= (const Deriv_Interpolation_IBM_base &)
operator const Interpolation_IBM_base & () const
operator Interpolation_IBM_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Interpolation_IBM_base & self_cast (Objet_U &)
static const
Deriv_Interpolation_IBM_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Interpolation_IBM_base * pointeur_
Detailed Description
Definition at line 29 of file Interpolation_IBM.h.
Constructor & Destructor Documentation
Deriv_Interpolation_IBM_base::~Deriv_Interpolation_IBM_base ()
Definition at line 26 of file Interpolation_IBM.cpp.
Deriv_Interpolation_IBM_base::Deriv_Interpolation_IBM_base ()
Definition at line 26 of file Interpolation_IBM.cpp.
Deriv_Interpolation_IBM_base::Deriv_Interpolation_IBM_base (const Deriv_Interpolation_IBM_base & t)
Definition at line 26 of file Interpolation_IBM.cpp.
Member Function Documentation
Objet_U * Deriv_Interpolation_IBM_base::cree_instance () [static]
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
int Deriv_Interpolation_IBM_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
const Type_info * Deriv_Interpolation_IBM_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
const Type_info & Deriv_Interpolation_IBM_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Interpolation_IBM.cpp.
const Type_info * Deriv_Interpolation_IBM_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
Deriv_Interpolation_IBM_base::operator const Interpolation_IBM_base & () const
Definition at line 26 of file Interpolation_IBM.cpp.
Deriv_Interpolation_IBM_base::operator Interpolation_IBM_base & ()
Definition at line 26 of file Interpolation_IBM.cpp.
const Interpolation_IBM_base * Deriv_Interpolation_IBM_base::operator-> () const [inline]
Definition at line 29 of file Interpolation_IBM.h.
: public DERIV(Interpolation_IBM_base)
Interpolation_IBM_base * Deriv_Interpolation_IBM_base::operator-> () [inline]
Definition at line 29 of file Interpolation_IBM.h.
: public DERIV(Interpolation_IBM_base)
const Deriv_Interpolation_IBM_base & Deriv_Interpolation_IBM_base::operator= (const Deriv_Interpolation_IBM_base & t)
Definition at line 26 of file Interpolation_IBM.cpp.
const Deriv_Interpolation_IBM_base & Deriv_Interpolation_IBM_base::operator= (const Interpolation_IBM_base & t)
Definition at line 26 of file Interpolation_IBM.cpp.
Sortie & Deriv_Interpolation_IBM_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
Entree & Deriv_Interpolation_IBM_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
const Deriv_Interpolation_IBM_base & Deriv_Interpolation_IBM_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
Deriv_Interpolation_IBM_base & Deriv_Interpolation_IBM_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
void Deriv_Interpolation_IBM_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Interpolation_IBM.cpp.
unsigned Deriv_Interpolation_IBM_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Interpolation_IBM.
Definition at line 26 of file Interpolation_IBM.cpp.
const Interpolation_IBM_base & Deriv_Interpolation_IBM_base::valeur () const [inline]
Definition at line 29 of file Interpolation_IBM.h.
Referenced by Source_PDF_EF::associer_pb(), Source_PDF_base::calculer_vitesse_imposee(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), and Source_PDF_base::readOn().
: public DERIV(Interpolation_IBM_base)
Interpolation_IBM_base & Deriv_Interpolation_IBM_base::valeur () [inline]
Definition at line 29 of file Interpolation_IBM.h.
: public DERIV(Interpolation_IBM_base)
Member Data Documentation
const Type_info Deriv_Interpolation_IBM_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Interpolation_IBM.
Definition at line 29 of file Interpolation_IBM.h.
Interpolation_IBM_base* Deriv_Interpolation_IBM_base::pointeur_ [private]
Definition at line 29 of file Interpolation_IBM.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM.h
src/Kernel/Geometrie/Interpolation_IBM/Interpolation_IBM.cpp