TRUST: Periodique Class Reference
Periodique Class Reference
classe Periodique
Cette classe represente une condition aux limites periodique.
On peut specifier une periodicite en X, Y ou Z.
Toutes les faces de la frontiere associee a cette condition doivent
avoir la meme orientation
#include <Periodique.h>
Public Member Functions
Periodique ()
~Periodique ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
int face_associee (int i) const
double distance () const
const ArrOfDouble & direction_perio () const
int direction_periodicite () const
int est_periodique_selon_un_axe () const
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Periodique & self_cast (Objet_U &)
static const Periodique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
int compatible_avec_eqn (const Equation_base &) const override
Renvoie toujours 1.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ArrOfInt face_front_associee_
ArrOfDouble direction_perio_
double distance_
int direction_xyz_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
classe Periodique
Cette classe represente une condition aux limites periodique.
On peut specifier une periodicite en X, Y ou Z.
Toutes les faces de la frontiere associee a cette condition doivent
avoir la meme orientation
Definition at line 38 of file Periodique.h.
Constructor & Destructor Documentation
Periodique()
Periodique::Periodique ()
Definition at line 23 of file Periodique.cpp.
~Periodique()
Periodique::~Periodique ()
Definition at line 23 of file Periodique.cpp.
Member Function Documentation
compatible_avec_eqn()
int Periodique::compatible_avec_eqn (const Equation_base &) const override protected virtual
Renvoie toujours 1.
Implements Cond_lim_base.
Definition at line 56 of file Periodique.cpp.
{
  return 1;
}
completer()
void Periodique::completer (void) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
< Indice d'une face de la zone
< Indice dans les frontieres
< Indice de la face de la zone
< Indice dans les frontieres Indice de la face associee dans le tableau face_associee:
Reimplemented from Cond_lim_base.
Definition at line 65 of file Periodique.cpp.
{
  Frontiere& frontiere = frontiere_dis().frontiere();
  Cerr << "Initialization for periodic on " << frontiere.le_nom() << finl;
// Recherche de la direction de periodicite:
  ArrOfDouble erreur;
  int ok = Reordonner_faces_periodiques::check_faces_periodiques(frontiere,
                                                                 direction_perio_,
                                                                 erreur,
                                                                 1 /* verbose */);
  if (!ok)
    exit();
  distance_ = norme_array(direction_perio_);
  int i;
  const int dim = direction_perio_.size_array();
  direction_xyz_ = -2;
  for (i = 0; i < dim; i++)
    {
      if (std::fabs(direction_perio_[i]) > precision_geom)
        {
          if (direction_xyz_ == -2)
            direction_xyz_ = i;
          else
// Deuxieme coordonnee non nulle, vecteur direction n'est pas aligne sur un axe
            direction_xyz_ = -1;
        }
    }
  if (direction_xyz_ < 0)
    Cerr << "Periodic direction not aligned on an axis" << finl;
  else
    Cerr << "Periodic direction aligned on the axis " << direction_xyz_ << finl;
  const Zone& zone = frontiere.zone();
// Creation d'un tableau d'indices parallele sur toutes les faces frontieres
  IntTab tab_face_associee;
  const Zone_VF& zonevf = ref_cast(Zone_VF, zone_Cl_dis().zone_dis().valeur());
  zonevf.creer_tableau_faces_bord(tab_face_associee, Array_base::NOCOPY_NOINIT);
  tab_face_associee = -1;
// Nombre de faces virtuelles de cette frontiere:
  const int nb_faces = frontiere.nb_faces();
  const int nb_faces_2_ = nb_faces / 2;
  const ArrOfInt& faces_virt = frontiere.get_faces_virt();
  const int nb_faces_virt = faces_virt.size_array();
// On remplit la partie reele du tableau face_associee pour la frontiere qui nous interesse:
// et la partie reele du tableau "associee"
  const int i_premiere_face = frontiere.num_premiere_face();
  for (i = 0; i < nb_faces_2_; i++)
    {
      const int i1 = i_premiere_face + i;
      const int i2 = i_premiere_face + i + nb_faces_2_;
      tab_face_associee[i1] = i2;
      tab_face_associee[i2] = i1;
    }
  const MD_Vector& md_faces_front = tab_face_associee.get_md_vector();
// On echange espace virtuel avec traduction des indices:
  Scatter::construire_espace_virtuel_traduction(md_faces_front,
                                                md_faces_front,
                                                tab_face_associee,
                                                1 /* erreurs fatales */);
// Tableau qui donne pour chaque face virtuelle de la zone, -1 si ce n'est pas une
// face frontiere, sinon son indice dans les les frontieres.
  const ArrOfInt& ind_faces_virt_bord = zone.ind_faces_virt_bord();
// Creation d'un tableau qui donne, pour chaque face virtuelle des frontieres (toutes frontieres)
// l'indice de la face dans la frontiere periodique courante (-1 sinon)
  const int nb_faces_front_tot = tab_face_associee.size_totale();
  ArrOfInt index(nb_faces_front_tot);
  index= -2;
  const int nb_faces_zone = zone_Cl_dis().zone_dis().valeur().face_sommets().dimension(0);
  for (i = 0; i < nb_faces_virt; i++)
    {
      const int face_zone = frontiere.face_virt(i); //!< Indice d'une face de la zone
      const int face_front = ind_faces_virt_bord[face_zone - nb_faces_zone]; //!< Indice dans les frontieres
      index[face_front] = nb_faces + i;
    }
// Remplissage du tableau "face_front_associee_"
  face_front_associee_.resize_array(nb_faces + nb_faces_virt);
  for (i = 0; i < nb_faces + nb_faces_virt; i++)
    {
      int resu = -1;
      if (i < nb_faces_2_)
        resu = i + nb_faces_2_;
      else if (i < nb_faces)
        resu = i - nb_faces_2_;
      else
        {
// Face virtuelle :
          const int face_zone = frontiere.face_virt(i - nb_faces); //!< Indice de la face de la zone
          const int face_front = ind_faces_virt_bord[face_zone - nb_faces_zone]; //!< Indice dans les frontieres Indice de la face associee dans le tableau face_associee:
//
          const int face_front_associee = tab_face_associee[face_front];
          if (face_front_associee >= 0)
            {
// Indice de la face associee dans la frontiere:
              const int face_asso = index[face_front_associee];
              assert(face_asso >= 0);
              resu = face_asso;
            }
          else
            {
// La face virtuelle associee n'est pas dans le domaine
              Cerr << "Error in Periodique::completer()" << finl;
              exit();
            }
        }
      face_front_associee_[i] = resu;
    }
}
References Cerr, Reordonner_faces_periodiques::check_faces_periodiques(), Scatter::construire_espace_virtuel_traduction(), Zone_VF::creer_tableau_faces_bord(), TRUSTTab< _TYPE_ >::dimension(), direction_perio_, direction_xyz_, distance_, erreur(), Process::exit(), face_front_associee_, Zone_dis_base::face_sommets(), Frontiere::face_virt(), finl, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Frontiere::get_faces_virt(), TRUSTVect< _TYPE_ >::get_md_vector(), Zone::ind_faces_virt_bord(), Frontiere::le_nom(), Frontiere::nb_faces(), Array_base::NOCOPY_NOINIT, norme_array(), Frontiere::num_premiere_face(), Objet_U::precision_geom, ref_cast, TRUSTArray< _TYPE_ >::resize_array(), TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_totale(), Deriv_Zone_dis_base::valeur(), valeur(), Frontiere::zone(), Cond_lim_base::zone_Cl_dis(), and Zone_Cl_dis_base::zone_dis().
cree_instance()
Objet_U * Periodique::cree_instance () static
Definition at line 23 of file Periodique.cpp.
direction_perio()
const ArrOfDouble & Periodique::direction_perio () const inline
Definition at line 51 of file Periodique.h.
  {
    return direction_perio_;
  };
References direction_perio_.
Referenced by Terme_Source_Canal_perio::completer().
direction_periodicite()
int Periodique::direction_periodicite () const
Definition at line 184 of file Periodique.cpp.
{
  if (!est_periodique_selon_un_axe())
    {
      Cerr << "Error in Periodique::direction_periodicite():\n"
           << " An algorithm seems to assume that the periodic direction is aligned in X, Y or Z\n"
           << " and this is not the case !" << finl;
      exit();
    }
  return direction_xyz_;
}
References Cerr, direction_xyz_, est_periodique_selon_un_axe(), Process::exit(), and finl.
Referenced by Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio::completer(), and Zone_VEF_PreP1b::construire_renum_arete_perio().
distance()
double Periodique::distance () const
Definition at line 179 of file Periodique.cpp.
{
  return distance_;
}
References distance_.
Referenced by Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face(), and Eval_Diff_VDF_Elem< DERIVED_T >::flux_face().
duplique()
int Periodique::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Periodique.cpp.
est_periodique_selon_un_axe()
int Periodique::est_periodique_selon_un_axe () const inline
Definition at line 56 of file Periodique.h.
  {
    return  direction_xyz_ >= 0;
  };
References direction_xyz_.
Referenced by Terme_Source_Canal_perio::completer(), and direction_periodicite().
face_associee()
int Periodique::face_associee (int i) const inline
Definition at line 46 of file Periodique.h.
  {
    return face_front_associee_[i];
  }
References face_front_associee_.
Referenced by Op_Div_VEFP1B_Elem::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Op_Dift_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Dift_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_antidiffusion(), Op_Dift_VEF_Face::ajouter_contribution_cl(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_diffusion(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution_partie_compressible(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_old(), Op_Div_VEFP1B_Elem::ajouter_som(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Op_Dift_standard_VEF_Face::calcul_divergence(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Dift_Stab_VEF_Face::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Op_Dift_Stab_VEF_Face::calculer_min(), Zone_VEF_PreP1b::construire_renum_arete_perio(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Op_VDF_Elem::dimensionner(), Champ_P1NC_implementation::filtrer_resu(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_VEF::initialiser(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Assembleur_P_VDF::liste_faces_periodiques(), Op_Conv_Muscl_New_VEF_Face::mettre_a_jour_pour_periodicite(), Op_Conv_EF_VEF_P1NC_Stab::mettre_a_jour_pour_periodicite(), modif_matrice_pour_periodique_apres_contribuer(), modif_matrice_pour_periodique_avant_contribuer(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Zone_EF::modifier_pour_Cl(), Zone_VF::modifier_pour_Cl(), Zone_VEF::modifier_pour_Cl(), okface(), Assembleur_P_VEF::remplir(), Op_Diff_VEFP1NCP1B_Face::test(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), Champ_Face::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), and Champ_Q1NC::verifie_valeurs_cl().
get_info()
const Type_info * Periodique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 23 of file Periodique.cpp.
info()
const Type_info * Periodique::info () static
Definition at line 23 of file Periodique.cpp.
mettre_a_jour()
void Periodique::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Reimplemented from Cond_lim_base.
Definition at line 61 of file Periodique.cpp.
{
}
printOn()
Sortie & Periodique::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 40 of file Periodique.cpp.
{
  return s << que_suis_je() << finl ;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Periodique::readOn (Entree & s) override protected virtual
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 48 of file Periodique.cpp.
{
  le_champ_front.typer("Champ_front_uniforme");
  return s;
}
References Cond_lim_base::le_champ_front, and Deriv_::typer().
self_cast() [1/2]
const Periodique & Periodique::self_cast (const Objet_U & r) static
Definition at line 23 of file Periodique.cpp.
self_cast() [2/2]
Periodique & Periodique::self_cast (Objet_U & r) static
Definition at line 23 of file Periodique.cpp.
taille_memoire()
unsigned Periodique::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Periodique.cpp.
Member Data Documentation
direction_perio_
ArrOfDouble Periodique::direction_perio_ protected
Definition at line 66 of file Periodique.h.
Referenced by completer(), and direction_perio().
direction_xyz_
int Periodique::direction_xyz_ protected
Definition at line 69 of file Periodique.h.
Referenced by completer(), direction_periodicite(), and est_periodique_selon_un_axe().
distance_
double Periodique::distance_ protected
Definition at line 67 of file Periodique.h.
Referenced by completer(), and distance().
face_front_associee_
ArrOfInt Periodique::face_front_associee_ protected
Definition at line 65 of file Periodique.h.
Referenced by completer(), and face_associee().
info_obj
const Type_info Periodique::info_obj static
Definition at line 41 of file Periodique.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Periodique.h
src/Kernel/Geometrie/Periodique.cpp