TRUST: Convection_Diffusion_Chaleur_QC Class Reference
Convection_Diffusion_Chaleur_QC Class Reference
classe Convection_Diffusion_Chaleur_QC
Cas particulier de Convection_Diffusion_Chaleur_Fluide_Dilatable_base pour un fluide quasi conpressible
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
#include <Convection_Diffusion_Chaleur_QC.h>
Public Member Functions
~Convection_Diffusion_Chaleur_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Convection_Diffusion_Chaleur_QC ()
void set_param (Param &titi)
void calculer_div_u_ou_div_rhou (DoubleTab &res) const
encore une fois desole
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
const Champ_base & vitesse_pour_transport ()
bool is_generic ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Convection_Diffusion_Chaleur_QC & self_cast (Objet_U &)
static const
Convection_Diffusion_Chaleur_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a Equation_base::printOn(Sortie&)
virtual Entree & readOn (Entree &)
cf Equation_base::readOn(Entree&)
Protected Attributes
int mode_convection_
0 par divergence u 1 par conv(u) 2 par conv(rho u)
Detailed Description
classe Convection_Diffusion_Chaleur_QC
Cas particulier de Convection_Diffusion_Chaleur_Fluide_Dilatable_base pour un fluide quasi conpressible
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
Definition at line 40 of file Convection_Diffusion_Chaleur_QC.h.
Constructor & Destructor Documentation
Convection_Diffusion_Chaleur_QC::~Convection_Diffusion_Chaleur_QC ()
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
Convection_Diffusion_Chaleur_QC::Convection_Diffusion_Chaleur_QC ()
Definition at line 36 of file Convection_Diffusion_Chaleur_QC.cpp.
:mode_convection_(2) { }
Member Function Documentation
void Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou (DoubleTab & res) const [virtual]
encore une fois desole
< VEF
< VDF (temperature and pressure nodes are the same):
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 118 of file Convection_Diffusion_Chaleur_QC.cpp.
References Operateur_Div::calculer(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), DoubleTab::dimension_tot(), DoubleVect::echange_espace_virtuel(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Navier_Stokes_std::inconnue(), Convection_Diffusion_Fluide_Dilatable_base::le_fluide, DoubleVect::line_size(), mode_convection_, Convection_Diffusion_std::operateur(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::pression(), Equation_base::probleme(), ref_cast, ref_cast_non_const, sub_type, Ref_Fluide_Dilatable_base::valeur(), and Champ_Inc::valeurs().
{
// No convective operator:
  if (sub_type(Op_Conv_negligeable,operateur(1).l_op_base()))
    {
      Div=0;
      return;
    }
  if (mode_convection_!=0)
    Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(Div,*this);
  else
    {
// Compute Div([rho]u) with Divergence operator
      const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,probleme().equation(0));
      const DoubleTab& pression = eqn_hydr.pression().valeurs();
      const Champ_Inc& vitesse = eqn_hydr.inconnue();
// Div = Div([rho]u) located on pressure nodes:
      DoubleTab Div_on_pressure_nodes(pression);
      eqn_hydr.operateur_divergence().calculer(vitesse.valeurs(),Div_on_pressure_nodes);
// Test on the discretization:
      if (vitesse.valeurs().line_size() > 1) //!< VEF
        {
// VEF (temperature and pressure are not the same) =>  Div extrapolated on velocity nodes:
          DoubleTab Div_on_temperature_nodes(inconnue().valeurs());
          Div_on_pressure_nodes.echange_espace_virtuel();
          ref_cast_non_const(Fluide_Quasi_Compressible,le_fluide.valeur()).divu_discvit(Div_on_pressure_nodes,Div_on_temperature_nodes);
          const int nsom = Div_on_temperature_nodes.dimension_tot(0);
          for (int i=0 ; i<nsom ; i++) Div(i)=Div_on_temperature_nodes(i);
        }
      else//!< VDF (temperature and pressure nodes are the same):
        Div = Div_on_pressure_nodes;
      Div *= -1;
    }
}
Objet_U * Convection_Diffusion_Chaleur_QC::cree_instance () [static]
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
int Convection_Diffusion_Chaleur_QC::duplique () const [virtual]
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
const Type_info * Convection_Diffusion_Chaleur_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
const Type_info * Convection_Diffusion_Chaleur_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
bool Convection_Diffusion_Chaleur_QC::is_generic () [inline, virtual]
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 53 of file Convection_Diffusion_Chaleur_QC.h.
References mode_convection_.
{ return mode_convection_ == 2 ? true : false;}
int Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
< Default mode before 1.6.8 (wrong in VEF)
< OK in VDF and VEF
< Default mode after 1.6.8 (better)
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 55 of file Convection_Diffusion_Chaleur_QC.cpp.
References List_Source::add(), Cerr, Equation_base::discretisation(), Process::exit(), finl, Equation_base::les_sources, mode_convection_, O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Motcles::search(), Convection_Diffusion_std::terme_convectif, and Source::typer_direct().
{
  if (mot=="convection")
    {
      Convection_Diffusion_Chaleur_Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
// l'equation de la chaleur en quasi compressible contient un terme source dP/dt
      Cerr << "Source term creation of the energy equation :"<< finl;
      Source t;
      Source& so=les_sources.add(t);
      Nom type_so = "Source_QC_Chaleur_";
      Nom disc = discretisation().que_suis_je();
      if (disc=="VEFPreP1B") disc = "VEF";
      type_so += disc;
      so.typer_direct(type_so);
      so->associer_eqn(*this);
      Cerr<<so->que_suis_je()<<finl;
      Cerr << "Typing of the convection operator : ";
      return 1;
    }
  else if (mot=="mode_calcul_convection")
    {
      if (terme_convectif.non_nul())
        {
          Cerr<<" The option "<<mot<<" must be indicated before the convection operator."<<finl;
          Cerr<<" Please modify your data set."<<finl;
          exit();
        }
      Motcles modes(3);
      modes[0]="ancien"; //!< Default mode before 1.6.8 (wrong in VEF)
      modes[1]="divuT_moins_Tdivu"; //!< OK in VDF and VEF
      modes[2]="divrhouT_moins_Tdivrhou"; //!< Default mode after 1.6.8 (better)
      Motcle mot2;
      is>>mot2;
      mode_convection_=modes.search(mot2);
      if (mode_convection_==0)
        {
          Cerr << "WARNING! This mode is not supported anymore." << finl;
        }
      if (mode_convection_==-1)
        {
          Cerr<<" Allowed keywords for option mode_calcul_convection are :"<<finl;
          Cerr<<modes<<finl;
          exit();
        }
      return 1;
    }
  else
    return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::lire_motcle_non_standard(mot,is);
  return 1;
}
int Convection_Diffusion_Chaleur_QC::preparer_calcul (void) [virtual]
Tout ce qui ne depend pas des autres problemes eventuels.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 157 of file Convection_Diffusion_Chaleur_QC.cpp.
References mode_convection_, and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee().
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul();
  return mode_convection_ == 0 ? 1 :
         Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee();
}
Sortie & Convection_Diffusion_Chaleur_QC::printOn (Sortie & is) const [protected, virtual]
Simple appel a Equation_base::printOn(Sortie&)
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 38 of file Convection_Diffusion_Chaleur_QC.cpp.
{
  return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::printOn(is);
}
Entree & Convection_Diffusion_Chaleur_QC::readOn (Entree & is) [protected, virtual]
cf Equation_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 43 of file Convection_Diffusion_Chaleur_QC.cpp.
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::readOn(is);
  return is;
}
Convection_Diffusion_Chaleur_QC & Convection_Diffusion_Chaleur_QC::self_cast (Objet_U & r) [static]
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
const Convection_Diffusion_Chaleur_QC & Convection_Diffusion_Chaleur_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
void Convection_Diffusion_Chaleur_QC::set_param (Param & titi) [virtual]
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
Definition at line 49 of file Convection_Diffusion_Chaleur_QC.cpp.
References Param::ajouter_non_std().
{
  Convection_Diffusion_Chaleur_Fluide_Dilatable_base::set_param(param);
  param.ajouter_non_std("mode_calcul_convection",(this));
}
unsigned Convection_Diffusion_Chaleur_QC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 32 of file Convection_Diffusion_Chaleur_QC.cpp.
const Champ_base & Convection_Diffusion_Chaleur_QC::vitesse_pour_transport () [virtual]
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 107 of file Convection_Diffusion_Chaleur_QC.cpp.
References Probleme_base::equation(), Navier_Stokes_std::inconnue(), mode_convection_, Equation_base::probleme(), and ref_cast.
{
  if (mode_convection_==2) return Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport();
  else
    {
      const Probleme_base& pb = probleme();
      const Navier_Stokes_std& eqn_hydr = ref_cast(Navier_Stokes_std,pb.equation(0));
      return eqn_hydr.inconnue() /* u */ ;
    }
}
Member Data Documentation
const Type_info Convection_Diffusion_Chaleur_QC::info_obj [static]
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Definition at line 42 of file Convection_Diffusion_Chaleur_QC.h.
int Convection_Diffusion_Chaleur_QC::mode_convection_ [protected]
0 par divergence u 1 par conv(u) 2 par conv(rho u)
Definition at line 56 of file Convection_Diffusion_Chaleur_QC.h.
Referenced by calculer_div_u_ou_div_rhou(), is_generic(), lire_motcle_non_standard(), preparer_calcul(), and vitesse_pour_transport().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Equations/Convection_Diffusion_Chaleur_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Equations/Convection_Diffusion_Chaleur_QC.cpp