TRUST: Decouper Class Reference
Decouper Class Reference
Interprete Decouper. Aucun algorithme ici, uniquement lecture
de parametres dans le fichier .data et execution du partitionneur
et du decoupeur. Voir la methode interprete()
#include <Decouper.h>
Public Types
enum ZonesFileOutputType { BINARY_MULTIPLE , HDF5_SINGLE }
Public Member Functions
Decouper ()
~Decouper ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &is) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Entree & lire (Entree &is)
void ecrire (IntVect &elem_part, const Static_Int_Lists *som_raccord=NULL)
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Decouper & self_cast (Objet_U &)
static const Decouper & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Nom nom_domaine
Deriv_Partitionneur_base deriv_partitionneur
Ref_Domaine ref_domaine
int nb_parts_tot = -1
Noms liste_bords_periodiques
Static Public Attributes
static const Type_info info_obj
static int print_more_infos = 0
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
const Domaine & find_domain (const Nom &nom)
Cherche le domaine de nom "le_nom_domaine" parmi les objets connus
de l'interprete et renvoie une ref a ce domaine.
Private Attributes
int epaisseur_joint = 1
Nom nom_zones_decoup = "?"
Nom nom_fichier_decoupage = "?"
Nom nom_fichier_lata = "?"
int format_binaire = 1
int format_hdf = 0
int reorder = 0
Detailed Description
Interprete Decouper. Aucun algorithme ici, uniquement lecture
de parametres dans le fichier .data et execution du partitionneur
et du decoupeur. Voir la methode interprete()
Definition at line 30 of file Decouper.h.
Member Enumeration Documentation
ZonesFileOutputType
enum Decouper::ZonesFileOutputType
Enumerator
BINARY_MULTIPLE
HDF5_SINGLE
Definition at line 34 of file Decouper.h.
{ BINARY_MULTIPLE, HDF5_SINGLE };
Constructor & Destructor Documentation
Decouper()
Decouper::Decouper ()
Definition at line 24 of file Decouper.cpp.
~Decouper()
Decouper::~Decouper ()
Definition at line 24 of file Decouper.cpp.
Member Function Documentation
cree_instance()
Objet_U * Decouper::cree_instance () static
Definition at line 24 of file Decouper.cpp.
duplique()
int Decouper::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Decouper.cpp.
ecrire()
void Decouper::ecrire (IntVect & elem_part, const Static_Int_Lists * som_raccord = NULL)
Definition at line 217 of file Decouper.cpp.
{
// Calcul du nombre de parties generees par le partitionneur
  int nb_parties = 0;
  if (elem_part.size_array() > 0)
    nb_parties = max_array(elem_part) + 1;
  nb_parties = mp_max(nb_parties);
  Cerr << "The partitioner has generated " << nb_parties << " parts." << finl;
// Prise en compte de la directive nb_parts_tot
  if (nb_parts_tot >= 0)
    {
      if (nb_parties > nb_parts_tot)
        {
          Cerr << "Error: nb_parts_tot is less than the number of parts generated by the partitioner."
               << finl;
          exit();
        }
      Cerr << "Number of parts requested : " << nb_parts_tot
           << "\nGeneration of " << nb_parts_tot - nb_parties << " empty parts." << finl;
      nb_parties = nb_parts_tot;
    }
// Force un seul fichier .Zones au dela d'un certain nombre de rangs MPI:
  if (Process::force_single_file(nb_parties, nom_zones_decoup+".Zones"))
    format_hdf = 1;
  if (nom_fichier_decoupage != "?")
    ecrire_fichier_decoupage(nom_fichier_decoupage, elem_part, nb_parts_tot);
  if (nom_zones_decoup != "?")
    {
      Decouper::ZonesFileOutputType typ;
      if (format_binaire) typ = BINARY_MULTIPLE;
      if (format_hdf) typ = HDF5_SINGLE;
      ecrire_sous_zones(nom_zones_decoup, typ,
                        ref_domaine.valeur(), elem_part, nb_parties, epaisseur_joint, reorder,
                        liste_bords_periodiques, som_raccord);
    }
  if (nom_fichier_lata != "?")
    postraiter_decoupage(nom_fichier_lata, ref_domaine.valeur(), elem_part);
  Cout << "\nQuality of partitioning --------------------------------------------" << finl;
  int total_elem = Process::mp_sum(elem_part.size_reelle());
  Cout << "\nTotal number of elements = " << total_elem << finl;
  Cout << "Number of Zones : " << nb_parties << finl;
  if (Decouper::print_more_infos)
    {
      DoubleVect A(nb_parties);
      A = 0;
      for (int i = 0; i < elem_part.size_reelle(); i++)
        A(elem_part[i]) = A(elem_part[i]) + 1;
      if(Process::je_suis_maitre())
        {
          for(int proc=1; proc<Process::nproc(); proc++)
            {
              DoubleVect tmp(nb_parties);
              tmp = 0;
              recevoir(tmp, proc, 0, proc+2005);
              for(int i_part=0; i_part<nb_parties; i_part++)
                A(i_part) += tmp(i_part);
            }
          double mean_element_zone = total_elem/nb_parties;
          if (mean_element_zone>0)
            {
              double load_imbalance = double(local_max_vect(A) / mean_element_zone);
              Cout << "Number of cells per Zone (min/mean/max) : " << local_min_vect(A) << " / " << mean_element_zone << " / "
                   << local_max_vect(A) << " Load imbalance: " << load_imbalance << "\n" << finl;
            }
        }
      else
        envoyer(A, Process::me(), 0, Process::me()+2005);
// we could do it as below, but if nb_parties is big, it would involve a lot of collective communication
// for (int i = 0; i < nb_parties; i++)
// A[i] = Process::mp_sum(A[i]);
    }
  Cerr << "End of the interpreter Decouper" << finl;
  if (reorder==0 && nb_parties>128)
    {
      Cerr << "Performance tip: You could add \"reorder 1\" option to have less distance between communicating processes on the network." << finl;
      Cerr << "Add also \"Ecrire_lata filename\" to post-process the partition numeration and see the difference." << finl;
    }
}
References BINARY_MULTIPLE, Cerr, Cout, ecrire_fichier_decoupage(), ecrire_sous_zones(), envoyer(), epaisseur_joint, Process::exit(), finl, Process::force_single_file(), format_binaire, format_hdf, HDF5_SINGLE, Process::je_suis_maitre(), liste_bords_periodiques, local_max_vect(), local_min_vect(), max_array(), Process::me(), Process::mp_max(), Process::mp_sum(), nb_parts_tot, nom_fichier_decoupage, nom_fichier_lata, nom_zones_decoup, Process::nproc(), postraiter_decoupage(), print_more_infos, recevoir(), ref_domaine, reorder, TRUSTArray< _TYPE_ >::size_array(), TRUSTVect< _TYPE_ >::size_reelle(), and Ref_Domaine::valeur().
Referenced by interpreter().
find_domain()
const Domaine & Decouper::find_domain (const Nom & nom) private
Cherche le domaine de nom "le_nom_domaine" parmi les objets connus
de l'interprete et renvoie une ref a ce domaine.
Definition at line 42 of file Decouper.cpp.
{
  const Domaine * domaine_ptr = 0;
  if (objet_existant(le_nom_domaine))
    {
      const Objet_U& objet_domaine = objet(le_nom_domaine);
      if (sub_type(Domaine, objet_domaine))
        domaine_ptr = & ref_cast(Domaine, objet_domaine);
    }
  if (domaine_ptr == 0)
    {
      Cerr << "Error in Decouper::interpreter\n "
           << " Syntax:\n Decouper DOMAINNAME { ... }\n ";
      Cerr << le_nom_domaine << " is not a domain known" << finl;
      Process::exit();
    }
  return *domaine_ptr;
}
References Cerr, Process::exit(), finl, Interprete::objet(), Interprete::objet_existant(), ref_cast, and sub_type.
Referenced by lire(), and lire_motcle_non_standard().
get_info()
const Type_info * Decouper::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 24 of file Decouper.cpp.
info()
const Type_info * Decouper::info () static
Definition at line 24 of file Decouper.cpp.
interpreter()
Entree & Decouper::interpreter (Entree & is) override virtual
Reimplemented from Interprete.
Definition at line 171 of file Decouper.cpp.
{
  Cerr << "Decouper : Splitting of a domain" << finl;
// lecture des parametres
  lire(is);
// generation de la partition
  IntVect elem_part;
  Partitionneur_base& partitionneur = deriv_partitionneur.valeur();
  partitionneur.declarer_bords_periodiques(liste_bords_periodiques);
  partitionneur.construire_partition(elem_part,nb_parts_tot);
// ecriture
  ecrire(elem_part, {});
  Cerr << "End of the interpreter Decouper" << finl;
  return is;
}
References Cerr, Partitionneur_base::construire_partition(), Partitionneur_base::declarer_bords_periodiques(), deriv_partitionneur, ecrire(), finl, lire(), liste_bords_periodiques, nb_parts_tot, and Deriv_Partitionneur_base::valeur().
lire()
Entree & Decouper::lire (Entree & is)
Definition at line 191 of file Decouper.cpp.
{
// Lecture du nom du domaine a decouper:
  is >> nom_domaine;
  Cerr << " Domain name to split : " << nom_domaine << finl;
  ref_domaine = find_domain(nom_domaine);
// Avant de decouper on imprime des infos
  ref_domaine->imprimer();
  Param param(que_suis_je());
  param.ajouter_non_std("partitionneur|partition_tool",(this),Param::REQUIRED);
  param.ajouter("larg_joint",&epaisseur_joint);
  param.ajouter_condition("value_of_larg_joint_ge_1","The joint thickness must greater or equal to 1.");
  param.ajouter("nom_zones|zones_name",&nom_zones_decoup);
  param.ajouter("ecrire_decoupage",&nom_fichier_decoupage);
  param.ajouter("ecrire_lata",&nom_fichier_lata);
  param.ajouter("nb_parts_tot",&nb_parts_tot);
  param.ajouter("reorder",&reorder);
  param.ajouter_flag("single_hdf",&format_hdf);
  param.ajouter("periodique",&liste_bords_periodiques);
  param.ajouter("print_more_infos",&Decouper::print_more_infos);
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), Cerr, epaisseur_joint, find_domain(), finl, format_hdf, Domaine::imprimer(), Param::lire_avec_accolades_depuis(), liste_bords_periodiques, nb_parts_tot, nom_domaine, nom_fichier_decoupage, nom_fichier_lata, nom_zones_decoup, print_more_infos, Objet_U::que_suis_je(), ref_domaine, reorder, and Param::REQUIRED.
Referenced by interpreter(), and Decouper_multi::lire_motcle_non_standard().
lire_motcle_non_standard()
int Decouper::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 312 of file Decouper.cpp.
{
  Motcle motlu;
  if (mot=="partitionneur|partition_tool")
    {
      Cerr<<"domaine = "<<nom_domaine<<finl;
      const Domaine& domaine = find_domain(nom_domaine);
      lire_partitionneur(deriv_partitionneur,domaine,is);
      return 1;
    }
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References Cerr, deriv_partitionneur, Process::exit(), find_domain(), finl, lire_partitionneur(), nom_domaine, and Objet_U::que_suis_je().
printOn()
Sortie & Decouper::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file Decouper.cpp.
{
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Decouper::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 32 of file Decouper.cpp.
{
  exit();
  return is;
}
References Process::exit().
self_cast() [1/2]
const Decouper & Decouper::self_cast (const Objet_U & r) static
Definition at line 24 of file Decouper.cpp.
self_cast() [2/2]
Decouper & Decouper::self_cast (Objet_U & r) static
Definition at line 24 of file Decouper.cpp.
taille_memoire()
unsigned Decouper::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Decouper.cpp.
Member Data Documentation
deriv_partitionneur
Deriv_Partitionneur_base Decouper::deriv_partitionneur
Definition at line 47 of file Decouper.h.
Referenced by interpreter(), and lire_motcle_non_standard().
epaisseur_joint
int Decouper::epaisseur_joint = 1 private
Definition at line 57 of file Decouper.h.
Referenced by ecrire(), and lire().
format_binaire
int Decouper::format_binaire = 1 private
Definition at line 61 of file Decouper.h.
Referenced by ecrire().
format_hdf
int Decouper::format_hdf = 0 private
Definition at line 62 of file Decouper.h.
Referenced by ecrire(), and lire().
info_obj
const Type_info Decouper::info_obj static
Definition at line 32 of file Decouper.h.
liste_bords_periodiques
Noms Decouper::liste_bords_periodiques
Definition at line 50 of file Decouper.h.
Referenced by ecrire(), interpreter(), and lire().
nb_parts_tot
int Decouper::nb_parts_tot = -1
Definition at line 49 of file Decouper.h.
Referenced by ecrire(), interpreter(), and lire().
nom_domaine
Nom Decouper::nom_domaine
Definition at line 46 of file Decouper.h.
Referenced by lire(), lire_motcle_non_standard(), and Decouper_multi::lire_motcle_non_standard().
nom_fichier_decoupage
Nom Decouper::nom_fichier_decoupage = "?" private
Definition at line 59 of file Decouper.h.
Referenced by ecrire(), and lire().
nom_fichier_lata
Nom Decouper::nom_fichier_lata = "?" private
Definition at line 60 of file Decouper.h.
Referenced by ecrire(), and lire().
nom_zones_decoup
Nom Decouper::nom_zones_decoup = "?" private
Definition at line 58 of file Decouper.h.
Referenced by ecrire(), and lire().
print_more_infos
int Decouper::print_more_infos = 0 static
Definition at line 38 of file Decouper.h.
Referenced by DomaineCutter::construire_sous_domaine(), ecrire(), DomaineCutter::ecrire_zones(), and lire().
ref_domaine
Ref_Domaine Decouper::ref_domaine
Definition at line 48 of file Decouper.h.
Referenced by ecrire(), and lire().
reorder
int Decouper::reorder = 0 private
Definition at line 63 of file Decouper.h.
Referenced by ecrire(), and lire().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decoupeur/Decouper.h
src/Kernel/Geometrie/Decoupeur/Decouper.cpp