TRUST: Op_Dift_VEF_base Class Reference
Op_Dift_VEF_base Class Reference
class Op_Dift_VEF_base
#include <Op_Dift_VEF_base.h>
Public Member Functions
Op_Dift_VEF_base ()
~Op_Dift_VEF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void calculer_borne_locale (DoubleVect &, double, double) const
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Dift_VEF_base & self_cast (Objet_U &)
static const Op_Dift_VEF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Detailed Description
class Op_Dift_VEF_base
Definition at line 39 of file Op_Dift_VEF_base.h.
Constructor & Destructor Documentation
Op_Dift_VEF_base::Op_Dift_VEF_base ()
Definition at line 30 of file Op_Dift_VEF_base.cpp.
Op_Dift_VEF_base::~Op_Dift_VEF_base ()
Definition at line 30 of file Op_Dift_VEF_base.cpp.
Member Function Documentation
void Op_Dift_VEF_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) [virtual]
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
Definition at line 66 of file Op_Dift_VEF_base.cpp.
References Op_Diff_VEF_base::inconnue_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF,zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF,zone_cl_dis.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
  inconnue_ = ch_transporte;
}
void Op_Dift_VEF_base::associer_modele_turbulence (const Mod_turb_hyd_base & mod)
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
Definition at line 43 of file Op_Dift_VEF_base.cpp.
References le_modele_turbulence.
Referenced by completer().
{
  le_modele_turbulence    = mod;
}
void Op_Dift_VEF_base::calculer_borne_locale (DoubleVect & borne_visco_turb, double dt_conv, double dt_diff_sur_dt_conv) const [virtual]
Reimplemented from Operateur_Diff_base.
Definition at line 104 of file Op_Dift_VEF_base.cpp.
References Zone_VEF::carre_pas_maille(), Operateur_Diff_base::diffusivite(), Objet_U::dimension, DoubleTab::dimension(), DMINFLOAT, Op_Diff_VEF_base::la_zone_vef, Zone_dis_base::nb_elem(), Ref_Zone_VEF::valeur(), and Champ_Proto::valeurs().
{
  const Zone_VEF& la_zone_VEF = la_zone_vef.valeur();
  int nb_elem = la_zone_VEF.nb_elem();
  int flag = diffusivite().valeurs().dimension(0)>1 ? 1 : 0;
  for (int elem=0; elem<nb_elem; elem++)
    {
      double h_inv = 1./la_zone_VEF.carre_pas_maille(elem);
// C'est pas tres propre pour recuperer diffu mais ca evite de coder cette methode dans plusieurs classes:
      double diffu = (flag ? diffusivite().valeurs()(elem) : diffusivite().valeurs()(0,0));
//
      double coef = 1./(2*(dt_conv+DMINFLOAT)*dimension*h_inv*dt_diff_sur_dt_conv) - diffu;
      if (coef>0 && coef<borne_visco_turb(elem))
        borne_visco_turb(elem) = coef;
    }
}
void Op_Dift_VEF_base::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_Stab_VEF_Face.
Definition at line 77 of file Op_Dift_VEF_base.cpp.
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente(), associer_modele_turbulence(), Cerr, Modele_turbulence_scal_base::conductivite_turbulente(), MorEqn::equation(), Process::exit(), finl, Equation_base::get_modele(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), ref_cast, sub_type, TURBULENCE, Ref_Objet_U::valeur(), and Mod_turb_hyd_base::viscosite_turbulente().
{
  Operateur_base::completer();
  const RefObjU& modele_turbulence = equation().get_modele(TURBULENCE);
  if (modele_turbulence.non_nul() && sub_type(Mod_turb_hyd_base,modele_turbulence.valeur()))
    {
      const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
      const Champ_Fonc& viscosite_turbulente = mod_turb.viscosite_turbulente();
      associer_diffusivite_turbulente(viscosite_turbulente);
      associer_modele_turbulence(mod_turb);
    }
  else if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
    {
      const Modele_turbulence_scal_base& modele_turbulence_scalaire = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
      const Champ_Fonc& conductivite_turbulente = modele_turbulence_scalaire.conductivite_turbulente();
      associer_diffusivite_turbulente(conductivite_turbulente);
    }
  else
    {
      Cerr << "Error in Op_Dift_VEF_Face::completer() " << finl;
      Cerr <<  que_suis_je() <<" operator is presently associated to "<<equation().que_suis_je()<<finl;
      Cerr << "instead of being associated to an equation dedicated to a turbulent flow."<<finl;
      exit();
    }
}
virtual int Op_Dift_VEF_base::duplique () const [pure virtual]
Implements Op_Diff_VEF_base.
Implemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
const Type_info * Op_Dift_VEF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 30 of file Op_Dift_VEF_base.cpp.
const Type_info * Op_Dift_VEF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 30 of file Op_Dift_VEF_base.cpp.
void Op_Dift_VEF_base::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
< on traite l'hydraulique
Reimplemented from Operateur_base.
Definition at line 50 of file Op_Dift_VEF_base.cpp.
References MorEqn::equation(), le_modele_turbulence, O_U_Ptr::non_nul(), DoubleTab::ref(), ArrOfDouble::size_array(), sub_type, tau_tan_, and Ref_Mod_turb_hyd_base::valeur().
{
  if (sub_type(Navier_Stokes_std,equation())) //!< on traite l'hydraulique
    {
      if ( le_modele_turbulence->loi_paroi().non_nul())
        if (le_modele_turbulence->loi_paroi()->use_shear())
          {
// Modif BM: on ne prend la ref que si le tableau a ete initialise, sinon ca bloque
// l'initialisation
            const DoubleTab& tab = le_modele_turbulence->loi_paroi().valeur().Cisaillement_paroi();
            if (tab.size_array() > 0)
              tau_tan_.ref(tab);
          }
    }
}
Sortie & Op_Dift_VEF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 32 of file Op_Dift_VEF_base.cpp.
{
  return Op_Diff_VEF_base::printOn(is);
}
Entree & Op_Dift_VEF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 37 of file Op_Dift_VEF_base.cpp.
{
  Op_Diff_VEF_base::readOn(is);
  return is;
}
const Op_Dift_VEF_base & Op_Dift_VEF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 30 of file Op_Dift_VEF_base.cpp.
Op_Dift_VEF_base & Op_Dift_VEF_base::self_cast (Objet_U & r) [static]
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 30 of file Op_Dift_VEF_base.cpp.
Member Data Documentation
const Type_info Op_Dift_VEF_base::info_obj [static]
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_VEF_P1NCP1B_Face, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, and Op_Dift_VEF_Face_Var.
Definition at line 41 of file Op_Dift_VEF_base.h.
Ref_Mod_turb_hyd_base Op_Dift_VEF_base::le_modele_turbulence [protected]
A deplacer dans Op_Diff_turb ?
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
Definition at line 52 of file Op_Dift_VEF_base.h.
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), associer_modele_turbulence(), Op_Dift_VEF_Face::contribue_au_second_membre(), and mettre_a_jour().
DoubleTab Op_Dift_VEF_base::tau_tan_ [protected]
Definition at line 53 of file Op_Dift_VEF_base.h.
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribue_au_second_membre(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Dift_VEF_base.h
src/VEF/Operateurs/Op_Dift_VEF_base.cpp