TRUST: Iterateur_PolyMAC Class Reference
Iterateur_PolyMAC Class Reference
#include <Iterateur_PolyMAC_base.h>
Public Member Functions
Iterateur_PolyMAC ()
~Iterateur_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Iterateur_PolyMAC (const Iterateur_PolyMAC_base &)
void associer (const Zone_PolyMAC &, const Zone_Cl_PolyMAC &, const Operateur_base &)
void associer (const Zone_dis &, const Zone_Cl_dis &, const Operateur_base &)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
void contribuer_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_vitesse (const DoubleTab &, Matrice_Morse &) const
Evaluateur_PolyMAC & evaluateur ()
const Evaluateur_PolyMAC & evaluateur () const
const Zone_PolyMAC & zone () const
const Zone_Cl_PolyMAC & zone_Cl () const
void completer_ ()
int impr (Sortie &os) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Iterateur_PolyMAC & self_cast (Objet_U &)
static const Iterateur_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Type_Cl_PolyMAC type_cl (const Cond_lim &) const
Detailed Description
Definition at line 115 of file Iterateur_PolyMAC_base.h.
Constructor & Destructor Documentation
Iterateur_PolyMAC::Iterateur_PolyMAC ()
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
Iterateur_PolyMAC::~Iterateur_PolyMAC ()
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
Iterateur_PolyMAC::Iterateur_PolyMAC (const Iterateur_PolyMAC_base & Opb) [inline]
Definition at line 184 of file Iterateur_PolyMAC_base.h.
References DERIV, and Deriv_Iterateur_PolyMAC_base::operator=().
  : DERIV(Iterateur_PolyMAC_base)()
{
  DERIV(Iterateur_PolyMAC_base)::operator=(Opb);
}
Member Function Documentation
DoubleTab & Iterateur_PolyMAC::ajouter (const DoubleTab & inco, DoubleTab & resu) const [inline]
Definition at line 215 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::ajouter(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::ajouter().
{
  return valeur().ajouter(inco,resu);
}
void Iterateur_PolyMAC::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const [inline]
Definition at line 228 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::ajouter_contribution(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::contribuer_a_avec().
{
  valeur().ajouter_contribution(inco, matrice);
}
void Iterateur_PolyMAC::ajouter_contribution_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [inline]
Definition at line 232 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::ajouter_contribution_vitesse(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::contribuer_bloc_vitesse().
{
  valeur().ajouter_contribution_vitesse(inco, matrice);
}
void Iterateur_PolyMAC::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Operateur_base & op) [inline]
Definition at line 243 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::associer(), and Deriv_Iterateur_PolyMAC_base::valeur().
{
  valeur().associer(zone_dis,zone_cl_dis,op);
}
void Iterateur_PolyMAC::associer (const Zone_PolyMAC & zone_vdf, const Zone_Cl_PolyMAC & zone_cl_vdf, const Operateur_base & op) [inline]
Definition at line 237 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::associer(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_Centre_PolyMAC_Elem::associer(), and Op_Conv_Amont_PolyMAC_Elem::associer().
{
  valeur().associer(zone_vdf,zone_cl_vdf,op);
}
DoubleTab & Iterateur_PolyMAC::calculer (const DoubleTab & inco, DoubleTab & resu) const [inline]
Definition at line 220 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::calculer(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::calculer().
{
  return valeur().calculer(inco, resu);
}
void Iterateur_PolyMAC::completer_ () [inline]
Definition at line 249 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::completer_(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::completer().
{
  valeur().completer_();
}
void Iterateur_PolyMAC::contribuer_au_second_membre (DoubleTab & resu) const [inline]
Definition at line 224 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::contribuer_au_second_membre(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::contribuer_au_second_membre().
{
  valeur().contribuer_au_second_membre(resu);
}
Objet_U * Iterateur_PolyMAC::cree_instance () [static]
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
int Iterateur_PolyMAC::duplique () const [virtual]
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
Evaluateur_PolyMAC & Iterateur_PolyMAC::evaluateur () [inline]
Definition at line 190 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::evaluateur(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_Centre_PolyMAC_Elem::associer(), Op_Conv_Amont_PolyMAC_Elem::associer(), Op_Conv_Centre_PolyMAC_Elem::associer_vitesse(), Op_Conv_Amont_PolyMAC_Elem::associer_vitesse(), Op_Conv_Centre_PolyMAC_Elem::vitesse(), and Op_Conv_Amont_PolyMAC_Elem::vitesse().
{
  return valeur().evaluateur();
}
const Evaluateur_PolyMAC & Iterateur_PolyMAC::evaluateur () const [inline]
Definition at line 195 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::evaluateur(), and Deriv_Iterateur_PolyMAC_base::valeur().
{
  return valeur().evaluateur();
}
const Type_info * Iterateur_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
int Iterateur_PolyMAC::impr (Sortie & os) const [inline]
Definition at line 253 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::impr(), and Deriv_Iterateur_PolyMAC_base::valeur().
Referenced by Op_Conv_PolyMAC_iterateur_base::impr().
{
  return valeur().impr(os);
}
const Type_info * Iterateur_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
Sortie & Iterateur_PolyMAC::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 33 of file Iterateur_PolyMAC_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Iterateur_PolyMAC::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 56 of file Iterateur_PolyMAC_base.cpp.
{
  return s ;
}
const Iterateur_PolyMAC & Iterateur_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
Iterateur_PolyMAC & Iterateur_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
unsigned Iterateur_PolyMAC::taille_memoire () const [virtual]
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 27 of file Iterateur_PolyMAC_base.cpp.
Type_Cl_PolyMAC Iterateur_PolyMAC::type_cl (const Cond_lim & cl) const [inline, protected]
Definition at line 210 of file Iterateur_PolyMAC_base.h.
References Iterateur_PolyMAC_base::type_cl(), and Deriv_Iterateur_PolyMAC_base::valeur().
{
  return valeur().type_cl(cl);
}
const Zone_PolyMAC & Iterateur_PolyMAC::zone () const [inline]
Definition at line 200 of file Iterateur_PolyMAC_base.h.
References Deriv_Iterateur_PolyMAC_base::valeur(), and Iterateur_PolyMAC_base::zone().
Referenced by Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_Centre_PolyMAC_Elem::dimensionner(), Op_Conv_Amont_PolyMAC_Elem::dimensionner(), Op_Conv_Centre_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Centre_PolyMAC_Elem::modifier_pour_Cl(), and Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl().
{
  return valeur().zone();
}
const Zone_Cl_PolyMAC & Iterateur_PolyMAC::zone_Cl () const [inline]
Definition at line 205 of file Iterateur_PolyMAC_base.h.
References Deriv_Iterateur_PolyMAC_base::valeur(), and Iterateur_PolyMAC_base::zone_Cl().
Referenced by Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_Centre_PolyMAC_Elem::dimensionner(), Op_Conv_Amont_PolyMAC_Elem::dimensionner(), Op_Conv_Centre_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Centre_PolyMAC_Elem::modifier_pour_Cl(), and Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl().
{
  return valeur().zone_Cl();
}
Member Data Documentation
const Type_info Iterateur_PolyMAC::info_obj [static]
Reimplemented from Deriv_Iterateur_PolyMAC_base.
Definition at line 117 of file Iterateur_PolyMAC_base.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Conv_iterateur/Iterateur_PolyMAC_base.h
src/PolyMAC/Operateurs/Conv_iterateur/Iterateur_PolyMAC_base.cpp