TRUST: Masse_VDF_base Class Reference
Masse_VDF_base Class Reference
#include <Masse_VDF_base.h>
Public Member Functions
Masse_VDF_base ()
~Masse_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const override
Public Member Functions inherited from Solveur_Masse_base
Solveur_Masse_base ()
~Solveur_Masse_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & appliquer (DoubleTab &) const
renvoie appliquer_impl(x/coeffient_temporelle)
si on a un coefficient temporelle
sinon renvoie appliquer_impl(x)
Return M-1.x
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du solveur de masse.
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual void assembler ()
NE FAIT RIEN
Eventuellement a surcharger dans les classes derivees
si la matrice de masse necessite un assemblage.
Assemble le solveur de masse (en general la matrice de masse)
virtual Matrice_Base & ajouter_masse (double dt, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse (double dt, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual Matrice_Base & ajouter_masse_dt_local (DoubleVect &dt_locaux, Matrice_Base &matrice, int penalisation=1) const
virtual DoubleTab & ajouter_masse_dt_local (DoubleVect &dt_locaux, DoubleTab &x, const DoubleTab &y, int penalisation=1) const
virtual void get_masse_dt_local (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual void get_masse_divide_by_local_dt (DoubleVect &m_dt_locaux, DoubleVect &dt_locaux, int penalisation=1)
virtual DoubleTab & corriger_solution (DoubleTab &x, const DoubleTab &y, int incr=0) const
void set_name_of_coefficient_temporel (const Nom &)
permet de choisir le nom du coefficient temporelle
que l'on veut utiliser pour appliquer
verifie que le champ exsite bien
int has_coefficient_temporel () const
const Nom & get_name_of_coefficient_temporel () const
virtual DoubleTab & appliquer_impl (DoubleTab &x) const =0
virtual void dimensionner (Matrice_Morse &matrix) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, double dt, const tabs_t &semi_impl, int resoudre_en_increments) const
virtual void completer (void)
virtual void preparer_calcul (void)
void set_penalisation_flag (int pen)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Static Public Member Functions
static const Type_info * info ()
static Masse_VDF_base & self_cast (Objet_U &)
static const Masse_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Solveur_Masse_base
static const Type_info * info ()
static Solveur_Masse_base & self_cast (Objet_U &)
static const Solveur_Masse_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Solveur_Masse_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
double penalisation_matrice_
double penalisation_secmem_
Protected Attributes inherited from Solveur_Masse_base
Nom name_of_coefficient_temporel_
nom du coefficient temporelle
int has_coefficient_temporel_
int penalisation_flag_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 30 of file Masse_VDF_base.h.
Constructor & Destructor Documentation
Masse_VDF_base()
Masse_VDF_base::Masse_VDF_base ()
Definition at line 27 of file Masse_VDF_base.cpp.
: penalisation_matrice_(0),penalisation_secmem_(0) {}
~Masse_VDF_base()
Masse_VDF_base::~Masse_VDF_base () override
Definition at line 26 of file Masse_VDF_base.cpp.
Member Function Documentation
ajouter_blocs()
void Masse_VDF_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
< M-1
< M/dt
Reimplemented from Solveur_Masse_base.
Definition at line 70 of file Masse_VDF_base.cpp.
{
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  const DoubleTab& passe = semi_impl.count(nom_inco) ? semi_impl.at(nom_inco) : equation().inconnue().passe();
  const DoubleTab& inco = equation().inconnue().valeurs();
  Matrice_Morse *mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
  DoubleTrav diag(inco);
  const int sz = equation().inconnue().valeurs().dimension_tot(0) * diag.line_size();
  diag = 1.;
  appliquer(diag); //!< M-1
  int prems = 0;
  if (penalisation_flag_)
    {
      if (mat && penalisation_matrice_ == 0)
        {
          double penal = 0;
          for (int i = 0; i < sz; i++)
            penal = std::max(penal, (*mat)(i, i));
          penal = mp_max(penal);
          penalisation_matrice_ = (mp_max_vect(diag) / dt + penal) * 1.e3;
          prems = 1;
        }
      if (penalisation_secmem_ == 0)
        penalisation_secmem_ = mp_max_vect(diag) * 1.e3;
    }
  else
    {
      penalisation_matrice_ = 0;
      penalisation_secmem_ = 1;
    }
  for (int i = 0; i < sz; i++)
    {
      if (diag.addr()[i])
        {
          if (mat)
            (*mat)(i, i) += 1. / (diag.addr()[i] * dt); //!< M/dt
          secmem.addr()[i] += 1. / (diag.addr()[i] * dt) * passe.addr()[i];
        }
      else
        {
          if (prems)
            {
              if (mat)
                (*mat)(i, i) += penalisation_matrice_;
              prems = 0;
            }
          if (mat)
            (*mat)(i, i) += penalisation_matrice_ / dt;
          secmem.addr()[i] = penalisation_secmem_ * passe.addr()[i];
        }
    }
}
References TRUSTArray< _TYPE_ >::addr(), Solveur_Masse_base::appliquer(), TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Process::mp_max(), mp_max_vect(), Champ_Inc::passe(), Solveur_Masse_base::penalisation_flag_, penalisation_matrice_, penalisation_secmem_, and Champ_Inc::valeurs().
associer_zone_cl_dis_base()
void Masse_VDF_base::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 130 of file Masse_VDF_base.cpp.
{
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, la_zone_Cl_dis_base);
}
References la_zone_Cl_VDF, and ref_cast.
associer_zone_dis_base()
void Masse_VDF_base::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) override virtual
Implements Solveur_Masse_base.
Definition at line 125 of file Masse_VDF_base.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, la_zone_dis_base);
}
References la_zone_VDF, and ref_cast.
dimensionner_blocs()
void Masse_VDF_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 53 of file Masse_VDF_base.cpp.
{
  const std::string& nom_inc = equation().inconnue().le_nom().getString();
  if (!matrices.count(nom_inc)) return; //rien a faire
  Matrice_Morse& mat = *matrices.at(nom_inc), mat2;
  const DoubleTab& champ_inconnue = equation().inconnue().valeurs();
  int size = champ_inconnue.dimension_tot(0) * champ_inconnue.line_size();
  IntTab indice(size, 2);
  for(int i=0; i<size; ++i)
    {
      indice(i,0) = indice(i,1) = i;
    }
  mat.dimensionner(indice);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), Matrice_Morse::dimensionner(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), O_U_Ptr::le_nom(), TRUSTVect< _TYPE_ >::line_size(), and Champ_Inc::valeurs().
get_info()
const Type_info * Masse_VDF_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_VDF_Elem, and Masse_VDF_Face.
Definition at line 26 of file Masse_VDF_base.cpp.
has_interface_blocs()
int Masse_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Solveur_Masse_base.
Definition at line 39 of file Masse_VDF_base.h.
  {
    return 1;
  };
info()
const Type_info * Masse_VDF_base::info () static
Definition at line 26 of file Masse_VDF_base.cpp.
printOn()
Sortie & Masse_VDF_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime le solveur de masse sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_VDF_Elem, and Masse_VDF_Face.
Definition at line 33 of file Masse_VDF_base.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Masse_VDF_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un solveur de masse sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_VDF_Elem, and Masse_VDF_Face.
Definition at line 41 of file Masse_VDF_base.cpp.
{
  return s ;
}
self_cast() [1/2]
const Masse_VDF_base & Masse_VDF_base::self_cast (const Objet_U & r) static
Definition at line 26 of file Masse_VDF_base.cpp.
self_cast() [2/2]
Masse_VDF_base & Masse_VDF_base::self_cast (Objet_U & r) static
Definition at line 26 of file Masse_VDF_base.cpp.
Member Data Documentation
info_obj
const Type_info Masse_VDF_base::info_obj static
Definition at line 33 of file Masse_VDF_base.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Masse_VDF_base::la_zone_Cl_VDF protected
Definition at line 49 of file Masse_VDF_base.h.
Referenced by Masse_VDF_Face::appliquer_impl(), and associer_zone_cl_dis_base().
la_zone_VDF
Ref_Zone_VDF Masse_VDF_base::la_zone_VDF protected
Definition at line 48 of file Masse_VDF_base.h.
Referenced by Masse_VDF_Elem::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), and associer_zone_dis_base().
penalisation_matrice_
double Masse_VDF_base::penalisation_matrice_ mutable protected
Definition at line 50 of file Masse_VDF_base.h.
Referenced by ajouter_blocs().
penalisation_secmem_
double Masse_VDF_base::penalisation_secmem_ mutable protected
Definition at line 51 of file Masse_VDF_base.h.
Referenced by ajouter_blocs().
The documentation for this class was generated from the following files:
src/VDF/Solveurs/Masse_VDF_base.h
src/VDF/Solveurs/Masse_VDF_base.cpp