TRUST: Postraitement Class Reference
Postraitement Class Reference
classe Postraitement
La classe est dotee -d une liste de champs generiques champs_post_complet_ qui contient
tous les champs generiques du post-traitement
-d une liste d identifiants noms_champs_a_post_ qui contient l identifiant
des champs a post-traiter
-Lecture des champs generiques declares dans le bloc "definition_champs" (ajoutes dans champs_post_complet_)
et ajout dans cette liste des champs crees par macro (declenche par ancienne syntaxe dans "champs" et "statistiques")
Construction de la liste des identifiants noms_champs_a_post_ au cours des operations de lecture
-Mise a jour des champs generiques, en realite mise a jour des operateurs statistiques pour les champs qui en porte
-postraitement realise dans postraiter_champs()
Parcours des identifiants
Le champ generique correspondant a un identifiant est recupere par : get_champ_post("identifiant")
Pour ce champ generique : on calcul les valeurs a ecrire par : get_champ(espace_stockage)
on recupere les informations complementaires par : get_property(), get_time() ...
Ecriture des valeurs calculees : postraiter(...)
Les macros utilises pour la creation des champs generiques sont detaillees dans le .cpp de la classe
Voir creer_champ_post() et creer_champ_post_stat()
#include <Postraitement.h>
Public Member Functions
~Postraitement ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_nom_et_pb_base (const Nom &, const Probleme_base &) override
void postraiter (int forcer) override
void mettre_a_jour (double temps) override
void finir () override
Finalise le postraitement
Ferme le fichier associe.
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
void completer () override
Postraitement ()
Constructeur par defaut.
Les frequences de postraitement prennent la valeur
par defaut 1e6. Et aucun postraitement n'est demande.
void lire_fichier (const Nom &nom_fichier)
const Sondes & les_sondes () const
Sondes & les_sondes ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
void init () override
Initialise le postraitement.
Cree le fichier associe au postraitement, ecrit
des infos sur TrioU. Ecrit le probleme sur
le fichier.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int postraiter_sondes ()
Effectue le postraitement lie au sondes de facon imperative.
int traiter_sondes ()
Mets a jour (en temps) le sondes.
int postraiter_champs ()
Effectue le postraitement des Champs de facon imperative.
Mets a jour les champs crees.
int traiter_champs ()
Effectue le postraitement des Champs si cela est necessaire.
int lire_champs_a_postraiter (Entree &)
Lit le nom des champs a postraiter sur un flot d'entree.
Format:
{
???
}.
int lire_champs_stat_a_postraiter (Entree &)
int lire_champs_operateurs (Entree &is)
Lit les champs a postraiter sur un flot d'entree.
void complete_champ (Champ_Generique &champ, const Motcle &motlu)
int postraiter_tableaux ()
int traiter_tableaux ()
int lire_tableaux_a_postraiter (Entree &)
int lpost (double, double) const
int lpost_champ (double) const
Test de postraitement en tenant compte de l'evolution en temps
du champ.
Renvoie VRAI si le champ necessite un postraitement, vu
le temps courant et le pas de temps fourni.
int lpost_stat (double) const
int ind_post (int nb_pas_dt)
double dt_post_ch () const
Nom nom_fich () const
int lpost_tab (double) const
int & est_le_premier_postraitement_pour_nom_fich ()
int & est_le_dernier_postraitement_pour_nom_fich ()
Operateurs_Statistique_tps & les_statistiques ()
int sondes_demande ()
int champs_demande ()
int stat_demande () const
int stat_demande_definition_champs () const
int tableaux_demande ()
bool besoin_postraiter_champs ()
List_Nom & noms_champs_a_post ()
const Liste_Champ_Generique & champs_post_complet () const
int postraiter (const Domaine &dom, const Noms &unites, const Noms &noms_compo, const int ncomp, const double temps_champs, double &temps_courant, Nom nom_post, const Nom &localisation, const Nom &nature, const DoubleTab &valeurs, int tenseur)
int postraiter_tableau (const Domaine &dom, const Noms &unites, const Noms &noms_compo, const int ncomp, const double temps_champs, double &temps_courant, Nom nom_post, const Nom &localisation, const Nom &nature, const DoubleTab &valeurs)
int postraiter_tenseur (const Domaine &dom, const Noms &unites, const Noms &noms_compo, const int ncomp, const double temps_champs, double &temps_courant, Nom nom_post, const Nom &localisation, const Nom &nature, const DoubleTab &valeurs)
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
Nom set_expression_champ (const Motcle &motlu1, const Motcle &motlu2, const Motcle &motlu3, const Motcle &motlu4, const int trouve)
void creer_champ_post (const Motcle &motlu1, const Motcle &motlu2, Entree &s)
void creer_champ_post_stat (const Motcle &motlu1, const Motcle &motlu2, const Motcle &motlu3, const Motcle &motlu4, const double t_deb, const double t_fin, Entree &s)
void creer_champ_post_moreqn (const Motcle &type, const Motcle &option, const int num_eq, const int num_morceau, const int compo, Entree &s)
void creer_champ_post_med (const Motcle &motlu1, const Motcle &motlu2, Entree &s)
int comprend_champ_post (const Motcle &identifiant) const
void verifie_nom_et_sources (const Champ_Generique &champ)
int champ_fonc (Motcle &nom_champ, Ref_Champ_base &mon_champ, Ref_Operateur_Statistique_tps_base &operateur_statistique) const
int & compteur_champ_stat ()
const double & tstat_deb () const
const double & tstat_fin () const
int cherche_stat_dans_les_sources (const Champ_Gen_de_Champs_Gen &ch, Motcle nom)
On recherche les champs statistiques dans les sources du champ courant.
Public Member Functions inherited from Postraitement_base
~Postraitement_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Postraitement_base ()
virtual void associer_nom_et_pb_base (const Nom &, const Probleme_base &)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void postraiter (int forcer)=0
virtual void mettre_a_jour (double temps)
virtual void init ()
virtual void finir ()
int sauvegarder (Sortie &os) const override
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
int reprendre (Entree &is) override
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual void completer ()=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Postraitement & self_cast (Objet_U &)
static const Postraitement & self_cast (const Objet_U &)
static List_Nom & noms_fichiers_sondes ()
static Nom get_nom_localisation (const Entity &loc)
Static Public Member Functions inherited from Postraitement_base
static const Type_info * info ()
static Postraitement_base & self_cast (Objet_U &)
static const Postraitement_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
int DeprecatedKeepDuplicatedProbes =0
Ancien format des sondes dans les .son qui autorise les sondes dupliquees.
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Postraitement_base
static const Type_info info_obj
static const char *const demande_description = "DESCRIPTION"
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les directives de postraitement sur un flot d'entree.
Format:
Postraitement
{
Sondes bloc de lecture des sondes |
Champs bloc de lecture des champs a postraiter |
Statistiques bloc de lecture objet statistique |
Fichier
}.
Protected Member Functions inherited from Postraitement_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int est_le_premier_postraitement_pour_nom_fich_
int est_le_dernier_postraitement_pour_nom_fich_
double dt_post_ch_
ecriture des champs sur fichier nom_du_cas.lml tous les dt_post
double dt_post_stat_
ecriture des statistiques sur fichier nom_du_cas.lml tous les dt_stat
double dt_post_tab
ecriture des tableaux d'entiers sur fichier nom_du_cas.lml
int nb_pas_dt_post_
Parser_U fdt_post
Sondes les_sondes_
Sondes a traiter.
Sondes_Int les_sondes_int_
Sondes pour des tableaux d'entiers.
Operateurs_Statistique_tps les_statistiques_
Liste d'operateurs statistiques a traiter.
List_Nom noms_champs_a_post_
Liste_Champ_Generique champs_post_complet_
int nb_champs_stat_
double tstat_deb_
double tstat_fin_
double tstat_dernier_calcul_
int lserie_
double dt_integr_serie_
List_Ref_IntVect tableaux_a_postraiter_
Liste de references a des tableaux a post-traiter.
List_Nom noms_tableaux_
Format_Post format_post
Protected Attributes inherited from Postraitement_base
Nom le_nom_
Ref_Probleme_base mon_probleme
double temps_
Private Attributes
int sondes_demande_
int champs_demande_
int stat_demande_
int stat_demande_definition_champs_
int binaire
int tableaux_demande_
Nom nom_fich_
Nom format
Nom option_para
double temps_
double dernier_temps
temps du precedent appel a postraiter()
Ref_Domaine le_domaine
Ref_Zone_dis_base zone_dis_pour_faces
Static Private Attributes
static List_Nom noms_fichiers_sondes_ = List_Nom ()
static Motcles formats_supportes =Motcles(0)
Additional Inherited Members
Public Types inherited from Postraitement_base
enum Format { ASCII , BINAIRE }
enum Type_Champ { CHAMP =0 , STATISTIQUE =1 }
enum Localisation { SOMMETS =0 , ELEMENTS =1 , FACES =2 }
enum Type_Post { ERREUR =-1 , ENTIER =0 , REEL =1 , DOUBLE =2 }
Detailed Description
classe Postraitement
La classe est dotee -d une liste de champs generiques champs_post_complet_ qui contient
tous les champs generiques du post-traitement
-d une liste d identifiants noms_champs_a_post_ qui contient l identifiant
des champs a post-traiter
-Lecture des champs generiques declares dans le bloc "definition_champs" (ajoutes dans champs_post_complet_)
et ajout dans cette liste des champs crees par macro (declenche par ancienne syntaxe dans "champs" et "statistiques")
Construction de la liste des identifiants noms_champs_a_post_ au cours des operations de lecture
-Mise a jour des champs generiques, en realite mise a jour des operateurs statistiques pour les champs qui en porte
-postraitement realise dans postraiter_champs()
Parcours des identifiants
Le champ generique correspondant a un identifiant est recupere par : get_champ_post("identifiant")
Pour ce champ generique : on calcul les valeurs a ecrire par : get_champ(espace_stockage)
on recupere les informations complementaires par : get_property(), get_time() ...
Ecriture des valeurs calculees : postraiter(...)
Les macros utilises pour la creation des champs generiques sont detaillees dans le .cpp de la classe
Voir creer_champ_post() et creer_champ_post_stat()
Definition at line 86 of file Postraitement.h.
Constructor & Destructor Documentation
~Postraitement()
Postraitement::~Postraitement ()
Definition at line 35 of file Postraitement.cpp.
{
// Cerr<<"remise a zero des noms des sondes" <<finl;
// quand on detruit un postraitement on detruit la liste des noms des sondes pour pouvoir refaire initialize
  Postraitement::noms_fichiers_sondes_=LIST(Nom)();
}
References LIST, and noms_fichiers_sondes_.
Postraitement()
Postraitement::Postraitement ()
Constructeur par defaut.
Les frequences de postraitement prennent la valeur
par defaut 1e6. Et aucun postraitement n'est demande.
Definition at line 576 of file Postraitement.cpp.
{
  est_le_premier_postraitement_pour_nom_fich_=-1;
  est_le_dernier_postraitement_pour_nom_fich_=-1;
  temps_=-1;
  dt_post_ch_=dt_post_stat_=dt_post_tab=dt_integr_serie_=1.e6;
  nb_pas_dt_post_ = (int)(pow(2.0,(double)((sizeof(True_int)*8)-1))-1);
  sondes_demande_ = champs_demande_ = stat_demande_ = stat_demande_definition_champs_ =tableaux_demande_=0;
  binaire=-1;
  tstat_deb_=tstat_fin_=tstat_dernier_calcul_=-1;
  nb_champs_stat_=0;
  lserie_=0;
  option_para="SIMPLE";
  nom_fich_ = nom_du_cas();
  format="lml";
}
References binaire, champs_demande_, dt_integr_serie_, dt_post_ch_, dt_post_stat_, dt_post_tab, est_le_dernier_postraitement_pour_nom_fich_, est_le_premier_postraitement_pour_nom_fich_, format, lserie_, nb_champs_stat_, nb_pas_dt_post_, Objet_U::nom_du_cas(), nom_fich_, option_para, sondes_demande_, stat_demande_, stat_demande_definition_champs_, tableaux_demande_, temps_, tstat_deb_, tstat_dernier_calcul_, and tstat_fin_.
Member Function Documentation
associer_nom_et_pb_base()
void Postraitement::associer_nom_et_pb_base (const Nom & nom, const Probleme_base & pb) override virtual
Reimplemented from Postraitement_base.
Definition at line 42 of file Postraitement.cpp.
{
  Postraitement_base::associer_nom_et_pb_base(nom, pb);
}
References Postraitement_base::associer_nom_et_pb_base().
Referenced by Source_Generique_base::completer().
besoin_postraiter_champs()
bool Postraitement::besoin_postraiter_champs () inline
Definition at line 145 of file Postraitement.h.
{ return (champs_demande_) || (stat_demande_) || (stat_demande_definition_champs_); }
References champs_demande_, stat_demande_, and stat_demande_definition_champs_.
Referenced by finir(), init(), postraiter(), and postraiter_champs().
champ_fonc()
int Postraitement::champ_fonc (Motcle & nom_champ, Ref_Champ_base & mon_champ, Ref_Operateur_Statistique_tps_base & operateur_statistique) const
Definition at line 201 of file Postraitement.cpp.
{
  if (comprend_champ_post(nom_champ))
    {
      const REF(Champ_Generique_base)& champ = get_champ_post(nom_champ);
      if (sub_type(Champ_Generique_Statistiques_base,champ.valeur()))
        {
          const Champ_Generique_Statistiques_base& champ_stat = ref_cast(Champ_Generique_Statistiques_base,champ.valeur());
          mon_champ = champ_stat.integrale();
          operateur_statistique = champ_stat.Operateur_Statistique();
          return 1;
        }
    }
  return 0;
}
References comprend_champ_post(), get_champ_post(), Champ_Generique_Statistiques_base::integrale(), Champ_Generique_Statistiques_base::Operateur_Statistique(), REF, ref_cast, and sub_type.
Referenced by Equation_base::ecrire_fichier_xyz().
champs_demande()
int Postraitement::champs_demande () inline
Definition at line 141 of file Postraitement.h.
{ return champs_demande_; }
References champs_demande_.
Referenced by Probleme_base::init_postraitements().
champs_post_complet()
const Liste_Champ_Generique & Postraitement::champs_post_complet () const inline
Definition at line 147 of file Postraitement.h.
{ return champs_post_complet_; }
References champs_post_complet_.
cherche_stat_dans_les_sources()
int Postraitement::cherche_stat_dans_les_sources (const Champ_Gen_de_Champs_Gen & ch, Motcle nom)
On recherche les champs statistiques dans les sources du champ courant.
Definition at line 978 of file Postraitement.cpp.
{
  if (sub_type(Champ_Generique_Statistiques_base,ch))
    {
// Activer pour lancer la sauvegarde et la reprise des statistiques
      stat_demande_definition_champs_ = 1;
      const Champ_Generique_Statistiques_base& champ_stat = ref_cast(Champ_Generique_Statistiques_base,ch);
      tstat_deb_ = champ_stat.tstat_deb();
      tstat_fin_ = champ_stat.tstat_fin();
      probleme().verifie_tdeb_tfin(nom);
    }
  else
    for (int i=0; i<ch.get_nb_sources(); i++)
      {
        const Champ_Generique_base& source = ch.get_source(i);
        if (sub_type(Champ_Gen_de_Champs_Gen,source))
          {
            const Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,source);
            cherche_stat_dans_les_sources(champ_post,nom);
          }
      }
  return 1;
}
References cherche_stat_dans_les_sources(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Gen_de_Champs_Gen::get_source(), probleme(), ref_cast, stat_demande_definition_champs_, sub_type, Champ_Generique_Statistiques_base::tstat_deb(), tstat_deb_, Champ_Generique_Statistiques_base::tstat_fin(), tstat_fin_, and Probleme_base::verifie_tdeb_tfin().
Referenced by cherche_stat_dans_les_sources(), and complete_champ().
complete_champ()
void Postraitement::complete_champ (Champ_Generique & champ, const Motcle & motlu)
Definition at line 1063 of file Postraitement.cpp.
{
  if (sub_type(Champ_Gen_de_Champs_Gen,champ.valeur()))
    {
      const Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,champ.valeur());
      cherche_stat_dans_les_sources(champ_post,motlu);
      if (sub_type(Champ_Generique_Statistiques_base,champ_post))
        nb_champs_stat_ += 1;
    }
  champ->nommer(motlu);
// On teste le nom du champ et de ses sources si elles ont ete specifiees par l utilisateur
// Methode suivante a reviser ou a ne pas utiliser
  verifie_nom_et_sources(champ);
  Champ_Generique& champ_a_completer = champs_post_complet_.add_if_not(champ);
  champ_a_completer->completer(*this);
}
References List_Champ_Generique::add_if_not(), champs_post_complet_, cherche_stat_dans_les_sources(), nb_champs_stat_, Objet_U::nommer(), ref_cast, sub_type, Deriv_Champ_Generique_base::valeur(), and verifie_nom_et_sources().
Referenced by lire_champs_a_postraiter(), lire_champs_operateurs(), lire_fichier(), and Sonde::readOn().
completer()
void Postraitement::completer () override virtual
Implements Postraitement_base.
Definition at line 747 of file Postraitement.cpp.
{
  les_sondes_.init_bords();
}
References Sondes::init_bords(), and les_sondes_.
comprend_champ_post()
int Postraitement::comprend_champ_post (const Motcle & identifiant) const
Definition at line 2224 of file Postraitement.cpp.
{
  CONST_LIST_CURSEUR(Champ_Generique) curseur_liste_champs = champs_post_complet_;
  while (curseur_liste_champs)
    {
      if (curseur_liste_champs.valeur().valeur().comprend_champ_post(identifiant))
        return 1;
      ++curseur_liste_champs;
    }
  return 0;
}
References champs_post_complet_, and CONST_LIST_CURSEUR.
Referenced by champ_fonc(), Sonde::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), Probleme_base::comprend_champ_post(), creer_champ_post(), lire_champs_a_postraiter(), readOn(), and Sonde::readOn().
compteur_champ_stat()
int & Postraitement::compteur_champ_stat () inline
Definition at line 283 of file Postraitement.h.
{ return nb_champs_stat_; }
References nb_champs_stat_.
cree_instance()
Objet_U * Postraitement::cree_instance () static
Definition at line 33 of file Postraitement.cpp.
creer_champ_post()
void Postraitement::creer_champ_post (const Motcle & motlu1, const Motcle & motlu2, Entree & s)
Definition at line 1746 of file Postraitement.cpp.
{
  Champ_Generique champ;
  Nom ajout;
  Nom nom_champ, nom_champ_a_post;
// Le postraitement aux faces concerne actuellement les champs dont la discretisation "natif" est aux faces
// On construit dans ce cas la un Champ_Generique_refChamp
// on essaye avant dans les champs_posts...
  int trouve=comprend_champ_post(motlu1);
  if ((trouve) && ((motlu2=="natif") || (motlu2=="faces")))
    {
      ajout="";
      noms_champs_a_post_.add_if_not(motlu1);
      return;
    }
  ajout = set_expression_champ(motlu1,motlu2,"","",trouve);
  /*
  //////////////////////////////////////////////////////////////////////////////////////////////////
  if ((motlu1=="divergence_U") || (motlu1=="gradient_pression") || (motlu1=="gradient_temperature"))
  {
  Motcle motlu1_corrige;
  if (motlu1=="gradient_pression") motlu1_corrige="pression";
  if (motlu1=="gradient_temperature") motlu1_corrige="temperature";
  if (motlu1=="divergence_U") motlu1_corrige="vitesse";
  if ((motlu1=="gradient_pression") || (motlu1=="gradient_temperature")) {
  ajout = "Interpolation { localisation ";
  ajout +=   motlu2;
  ajout += " source Gradient { source refChamp { Pb_champ ";
  ajout += mon_probleme->le_nom();
  ajout += " ";
  ajout += motlu1_corrige;
  ajout += " } } }";
  }
  if (motlu1=="divergence_U") {
  ajout = "Interpolation { localisation ";
  ajout +=   motlu2;
  ajout += " source Divergence { source refChamp { Pb_champ ";
  ajout += mon_probleme->le_nom();
  ajout += " ";
  ajout += motlu1_corrige;
  ajout += " } } }";
  }
  }
  ////////////////////////////////////////////////////////////////////////////////////////////
// A decommenter si choix fait de desactiver les champs discrets correspondants
// Meme procedure a faire pour creer_champ_post_stat()
// En fait seul gradient_temperature n est cree que pour le postraitement
  */
  Entree_complete s_complete(ajout,s);
  s_complete>>champ;
// if ((le_domaine.valeur().le_nom()!=mon_probleme.valeur().domaine().le_nom()) && ((motlu2!="natif"))) {
  {
    if ((motlu2!="natif")&&(motlu2!="faces"))
      {
        Champ_Generique_Interpolation& champ_interp = ref_cast(Champ_Generique_Interpolation,champ.valeur());
        champ_interp.set_domaine(le_domaine.valeur().le_nom());
// champ_interp.discretiser_domaine(*this);
      }
  }
  Nom nom_champ_ref;
  /*
    if ((motlu1=="divergence_U") || (motlu1=="gradient_pression") || (motlu1=="gradient_temperature"))
    {
    nom_champ_ref=motlu1;
    }
    else {
// A decommenter si suppression champs discrets correspondants
  */
  Noms composantes;
  Noms source_compos,source_syno;
  if (trouve==0)
    {
      REF(Champ_base) champ_ref;
      champ_ref = mon_probleme->get_champ(motlu1);
      nom_champ_ref = champ_ref->le_nom();
      source_compos = champ_ref->noms_compo();
      composantes = champ_ref->noms_compo();
      source_syno = champ_ref->get_synonyms();
      if ((source_compos.size()==1) && (source_compos[0]==motlu1))
        {
          nom_champ_ref=motlu1;
        }
      for (int i=0; i<source_syno.size(); i++)
        if (source_syno[i]==motlu1)
          nom_champ_ref=motlu1;
    }
  else
    {
      REF(Champ_Generique_base) champ_ref;
      champ_ref=get_champ_post(motlu1);
      nom_champ_ref = champ_ref->get_nom_post();
      source_compos = champ_ref->get_property("composantes");
      source_syno = champ_ref->get_property("synonyms");
      composantes =source_compos;
    }
  nom_champ = Motcle(nom_champ_ref)+"_"+motlu2+"_"+le_domaine.valeur().le_nom();
  champ->nommer(nom_champ);
// On nomme la source d un Champ_Generique_Interpolation cree par macro
  if ((motlu2!="natif") && (motlu2!="faces"))
    {
      Champ_Generique_Interpolation& champ_post = ref_cast(Champ_Generique_Interpolation,champ.valeur());
      champ_post.nommer_sources();
// On fixe l attribut compo_ pour le Champ_Generique_Interpolation cree par cette macro
      /*
        if ((motlu1=="divergence_U") || (motlu1=="gradient_pression") || (motlu1=="gradient_temperature"))
        ////Noms source_compos = champ_ref->noms_compo();
        {
        if ((motlu1=="gradient_pression") || (motlu1=="gradient_temperature"))
        {
        source_compos.dimensionner(dimension);
        source_compos[0]=nom_champ_ref+"X";
        source_compos[1]=nom_champ_ref+"Y";
        if (dimension>2)
        source_compos[2]=nom_champ_ref+"Z";
        }
        }
        else
// A decommenter si suppression des champs discrets
      */
      const Nom& nom_dom = champ_post.get_ref_domain().le_nom();
      int nb_comp = source_compos.size();
      Noms compo(nb_comp);
      Nom loc;
      if (motlu2=="ELEM")
        loc = "elem";
      else if (motlu2=="SOM")
        loc = "som";
      for (int i=0; i<nb_comp; i++)
        compo[i] = source_compos[i] +"_"+loc+"_"+nom_dom;
      champ_post.fixer_noms_compo(compo);
      {
        Noms les_synonyms(source_syno.size());
        for (int i=0; i<source_syno.size(); i++)
          les_synonyms[i] = source_syno[i] +"_"+loc+"_"+nom_dom;
        champ_post.fixer_noms_synonyms(les_synonyms);
      }
    }
  Champ_Generique& champ_a_completer = champs_post_complet_.add_if_not(champ);
  champ_a_completer->completer(*this);
  if (motlu2!="natif")
    {
      if (motlu2!="faces")
        nom_champ_a_post = motlu1+"_"+motlu2+"_"+le_domaine.valeur().le_nom();
      else
// Dans le cas d une localisation aux faces on test s il s agit d une composante ou du champ
        {
          int ncomp = Champ_Generique_base::composante(motlu1,nom_champ_ref,composantes,source_syno);
          if (ncomp==-1)
            nom_champ_a_post = motlu1+"_"+motlu2+"_"+le_domaine.valeur().le_nom();
          else
            {
// On determine le numero de composante
              Nom nume(ncomp);
              nom_champ_a_post = nom_champ_ref+"_"+motlu2+"_"+le_domaine.valeur().le_nom()+nume;
            }
        }
      if (noms_champs_a_post_.contient(nom_champ_a_post))
        {
          Cerr << "Postraitement::lire_champs_a_postraiter : duplicate field " << nom_champ_a_post << finl;
          Cerr<<" existing names "<<noms_champs_a_post_<<finl;
          exit();
        }
      else
        noms_champs_a_post_.add(nom_champ_a_post);
    }
}
References List_Nom::add(), List_Champ_Generique::add_if_not(), List_Nom::add_if_not(), Cerr, champs_post_complet_, Champ_Generique_base::composante(), comprend_champ_post(), List_Nom::contient(), Process::exit(), finl, Champ_Generique_Interpolation::fixer_noms_compo(), Champ_Generique_Interpolation::fixer_noms_synonyms(), Probleme_base::get_champ(), get_champ_post(), Champ_Generique_Interpolation::get_ref_domain(), le_domaine, Domaine::le_nom(), Nom::le_nom(), Postraitement_base::mon_probleme, Objet_U::nommer(), Champ_Gen_de_Champs_Gen::nommer_sources(), noms_champs_a_post_, REF, ref_cast, Champ_Generique_Interpolation::set_domaine(), set_expression_champ(), vect_impl::size(), Deriv_Champ_Generique_base::valeur(), and Ref_Domaine::valeur().
Referenced by creer_champ_post_med(), lire_champs_a_postraiter(), and Sonde::readOn().
creer_champ_post_med()
void Postraitement::creer_champ_post_med (const Motcle & motlu1, const Motcle & motlu2, Entree & s)
Definition at line 2196 of file Postraitement.cpp.
{
  creer_champ_post(motlu1,motlu2,s);
  Motcle test_loc(motlu1);
  Motcle loc2("_");
  loc2+=motlu2;
  Motcle test_loc_bis(test_loc);
  test_loc_bis.prefix(loc2);
  if (test_loc_bis!=test_loc)
    {
      Cerr<< "we must change the name "<< motlu1;
// Cerr<<test_loc_bis<< " "<<test_loc<<finl;
      int ss=champs_post_complet_.size();
      Nom ancien=champs_post_complet_(ss-1).valeur().get_nom_post();
      ancien.suffix(test_loc);
// Cerr<<ancien<<" ";
      Nom Nouveau(test_loc_bis);
      Nouveau+=ancien;
      Cerr<<" to " <<Nouveau<<finl;
      champs_post_complet_(ss-1).valeur().nommer(Nouveau);
      noms_champs_a_post_(noms_champs_a_post_.size()-1)=Nouveau;
    }
// int ss=champs_post_complet_.size();
// Cerr<<champs_post_complet_(ss-1).valeur().get_nom_post()<<finl;
// ss=noms_champs_a_post_.size();
// Cerr<<noms_champs_a_post_(ss-1)<<finl; //exit();
}
References Cerr, champs_post_complet_, creer_champ_post(), finl, Objet_U::nommer(), noms_champs_a_post_, Nom::prefix(), liste::size(), Nom::suffix(), and List_Champ_Generique::valeur().
Referenced by lire_champs_a_postraiter().
creer_champ_post_moreqn()
void Postraitement::creer_champ_post_moreqn (const Motcle & type, const Motcle & option, const int num_eq, const int num_morceau, const int compo, Entree & s)
Definition at line 2084 of file Postraitement.cpp.
{
  Champ_Generique champ;
  Nom ajout("");
  Nom nom_champ, nom_champ_a_post;
  const Champ_Inc& ch_inco = mon_probleme->equation(num_eq).inconnue();
  const Motcle& nom_inco = ch_inco->le_nom();
  Nom nume(num_morceau);
  ajout = "Morceau_Equation { type ";
  ajout += type;
  ajout += " numero ";
  ajout += nume;
  ajout += " option ";
  ajout += option;
  if (compo!=-1)
    {
      Nom numc(compo);
      ajout +=" compo ";
      ajout += numc;
    }
  ajout += " source refChamp { Pb_champ ";
  ajout += mon_probleme->le_nom();
  ajout += " ";
  ajout += nom_inco;
  ajout += " } }";
  Entree_complete s_complete(ajout,s);
  s_complete>>champ;
  const Motcle& nom_eq = mon_probleme->equation(num_eq).le_nom();
  Motcle type_morceau;
  Motcle type_option;
  if (type=="operateur")
    {
      if (num_morceau==0)
        type_morceau = "diffusion";
      else if (num_morceau==1)
        type_morceau = "convection";
      else if (num_morceau==2)
        type_morceau = "gradient";
      else if (num_morceau==3)
        type_morceau = "divergence";
      else
        {
          Cerr<<"Only two numbers of operators are available."<<finl;
          Cerr<<"0 for the diffusive operator and 1 for the convective operator."<<finl;
          exit();
        }
    }
  else
    {
      Cerr<<"Currently the only pieces of equations considered for the postprocessing"<<finl;
      Cerr<<"are of type operator"<<finl;
      exit();
    }
  if (option=="stabilite")
    {
      nom_champ = nom_eq;
      nom_champ += "_";
      nom_champ += type_morceau;
      nom_champ += "_";
      nom_champ += "dt";
    }
  else if (option=="flux_bords" || option=="flux_surfacique_bords")
    {
      int nb_op = mon_probleme->equation(num_eq).nombre_d_operateurs();
      if (num_morceau >= nb_op)
        nom_champ = mon_probleme->equation(num_eq).operateur_fonctionnel(num_morceau-nb_op).l_op_base().fichier();
      else
        nom_champ = mon_probleme->equation(num_eq).operateur(num_morceau).l_op_base().fichier();
      if (compo!=-1)
        {
          Nom nume2(compo);
          nom_champ += nume2;
        }
    }
  champ->nommer(nom_champ);
  Champ_Generique& champ_a_completer = champs_post_complet_.add_if_not(champ);
  champ_a_completer->completer(*this);
  Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,champ.valeur());
  champ_post.nommer_sources();
  nom_champ_a_post = nom_champ;
  if (noms_champs_a_post_.contient(nom_champ_a_post))
    {
      Cerr << "Postraitement::lire_champs_a_postraiter : duplicate field " << nom_champ_a_post << finl;
      Cerr<<" existing names "<<noms_champs_a_post_<<finl;
      exit();
    }
  else
    noms_champs_a_post_.add(nom_champ_a_post);
}
References List_Nom::add(), List_Champ_Generique::add_if_not(), Cerr, champs_post_complet_, List_Nom::contient(), Probleme_base::equation(), Process::exit(), Operateur_base::fichier(), finl, Equation_base::inconnue(), Operateur::l_op_base(), Equation_base::le_nom(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), Postraitement_base::mon_probleme, Equation_base::nombre_d_operateurs(), Objet_U::nommer(), Champ_Gen_de_Champs_Gen::nommer_sources(), noms_champs_a_post_, Equation_base::operateur(), Equation_base::operateur_fonctionnel(), ref_cast, and Deriv_Champ_Generique_base::valeur().
Referenced by lire_champs_a_postraiter().
creer_champ_post_stat()
void Postraitement::creer_champ_post_stat (const Motcle & motlu1, const Motcle & motlu2, const Motcle & motlu3, const Motcle & motlu4, const double t_deb, const double t_fin, Entree & s)
Definition at line 1950 of file Postraitement.cpp.
{
  Champ_Generique champ;
  Nom ajout;
  Nom nom_champ;
  if (((motlu3=="Moyenne") || (motlu3=="Ecart_type")) || (motlu3=="Correlation"))
    {
      ajout = set_expression_champ(motlu1,motlu2,motlu3,motlu4,0);
      Entree_complete s_complete(ajout,s);
      s_complete>>champ;
// if (le_domaine.valeur().le_nom()!=mon_probleme.valeur().domaine().le_nom()) {
      Champ_Generique_Interpolation& champ_interp = ref_cast(Champ_Generique_Interpolation,champ.valeur());
      champ_interp.set_domaine(le_domaine.valeur().le_nom());
// champ_interp.discretiser_domaine(*this);
// }
      if (motlu3!="Correlation")
        nom_champ = motlu3+"_"+motlu1+"_"+motlu2+"_"+le_domaine.valeur().le_nom();
      else
        nom_champ = motlu3+"_"+motlu1+"_"+motlu4+"_"+motlu2+"_"+le_domaine.valeur().le_nom();
      champ->nommer(nom_champ);
// On nomme les sources du Champ_Generique_Interpolation cree par macro
      Champ_Generique_Interpolation& champ_post = ref_cast(Champ_Generique_Interpolation,champ.valeur());
      champ_post.nommer_sources();
// On fixe l attribut compo_ pour le Champ_Generique_Interpolation cree par cette macro
      Champ_Generique_Statistiques_base& champ_stat = ref_cast(Champ_Generique_Statistiques_base,champ_post.set_source(0));
      const Champ_Generique_refChamp& champ_ref = ref_cast(Champ_Generique_refChamp,champ_stat.get_source(0));
      Champ espace_stockage;
      const Champ_base& champ_discret = champ_ref.get_champ(espace_stockage);
      const Noms& source_compos = champ_discret.noms_compo();
      const Nom& nom_dom = champ_post.get_ref_domain().le_nom();
      int nb_comp = source_compos.size();
      Noms compo(nb_comp);
      Nom loc;
      if (motlu2=="ELEM")
        loc = "elem";
      else if (motlu2=="SOM")
        loc = "som";
      else if (motlu2=="FACES")
        loc = "faces";
      for (int i=0; i<nb_comp; i++)
        {
          if (motlu3=="Moyenne")
            {
              compo[i] = "Moyenne_";
              compo[i] += source_compos[i] +"_"+loc+"_"+nom_dom;
            }
          else if (motlu3=="Ecart_Type")
            {
              compo[i] = "Ecart_Type_";
              compo[i] += source_compos[i] +"_"+loc+"_"+nom_dom;
            }
        }
      champ_post.fixer_noms_compo(compo);
      champ_stat.fixer_tdeb_tfin(t_deb,t_fin);
      Champ_Generique& champ_a_completer = champs_post_complet_.add_if_not(champ);
      champ_a_completer->completer(*this);
// On fixe l attribut compo_ pour le Champ_Generique_Interpolation d une Correlation cree par cette macro
//
      if (motlu3=="Correlation")
        {
          Champ_Generique_Interpolation& champ_post_corr = ref_cast(Champ_Generique_Interpolation,champ_a_completer.valeur());
          const Champ_Generique_Correlation& champ_corr = ref_cast(Champ_Generique_Correlation,champ_post_corr.get_source(0));
          const Noms& source_compos_corr = champ_corr.integrale()->noms_compo();
// const Nom& nom_dom = champ_post.get_ref_domain().le_nom();
          int nb_comp_corr = source_compos_corr.size();
          Noms compo_corr(nb_comp_corr);
          Nom loc_corr;
          if (motlu2=="ELEM")
            loc_corr = "elem";
          else if (motlu2=="SOM")
            loc_corr = "som";
          else if (motlu2=="FACES")
            loc_corr = "faces";
          for (int i=0; i<nb_comp_corr; i++)
            {
              compo_corr[i] = source_compos_corr[i] +"_"+loc_corr+"_"+nom_dom;
            }
          champ_post_corr.fixer_noms_compo(compo_corr);
        }
//
      const Noms nom = champ_a_completer->get_property("nom");
      if (noms_champs_a_post_.contient(nom[0]))
        {
          Cerr << "Postraitement::lire_champs_a_postraiter : duplicate field " << nom[0] << finl;
          exit();
        }
      else
        noms_champs_a_post_.add(nom[0]);
    }
  else
    {
      Cerr<<"Verify the syntax of the wanted statistical fields for the postprocessing"<<finl;
      exit();
    }
}
References List_Nom::add(), List_Champ_Generique::add_if_not(), Cerr, champs_post_complet_, List_Nom::contient(), Process::exit(), finl, Champ_Generique_Interpolation::fixer_noms_compo(), Champ_Generique_Statistiques_base::fixer_tdeb_tfin(), Champ_Generique_refChamp::get_champ(), Champ_Generique_Interpolation::get_ref_domain(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_Correlation::integrale(), le_domaine, Domaine::le_nom(), Objet_U::nommer(), Champ_Gen_de_Champs_Gen::nommer_sources(), noms_champs_a_post_, Field_base::noms_compo(), ref_cast, Champ_Generique_Interpolation::set_domaine(), set_expression_champ(), Champ_Gen_de_Champs_Gen::set_source(), vect_impl::size(), Deriv_Champ_Generique_base::valeur(), and Ref_Domaine::valeur().
Referenced by lire_champs_stat_a_postraiter().
dt_post_ch()
double Postraitement::dt_post_ch () const inline
Definition at line 132 of file Postraitement.h.
{ return dt_post_ch_; }
References dt_post_ch_.
Referenced by Probleme_base::init_postraitements().
duplique()
int Postraitement::duplique () const override virtual
Implements Objet_U.
Definition at line 33 of file Postraitement.cpp.
est_le_dernier_postraitement_pour_nom_fich()
int & Postraitement::est_le_dernier_postraitement_pour_nom_fich () inline
Definition at line 138 of file Postraitement.h.
{ return est_le_dernier_postraitement_pour_nom_fich_; }
References est_le_dernier_postraitement_pour_nom_fich_.
Referenced by init(), and Probleme_base::init_postraitements().
est_le_premier_postraitement_pour_nom_fich()
int & Postraitement::est_le_premier_postraitement_pour_nom_fich () inline
Definition at line 137 of file Postraitement.h.
{ return est_le_premier_postraitement_pour_nom_fich_; }
References est_le_premier_postraitement_pour_nom_fich_.
Referenced by init(), and Probleme_base::init_postraitements().
finir()
void Postraitement::finir () override virtual
Finalise le postraitement
Ferme le fichier associe.
Reimplemented from Postraitement_base.
Definition at line 1330 of file Postraitement.cpp.
{
// Fermeture du fichier si le postraitement des champs etait demande
  if (est_le_dernier_postraitement_pour_nom_fich_ && besoin_postraiter_champs())
    {
      format_post->finir(est_le_dernier_postraitement_pour_nom_fich_);
      Nom name=nom_fich().prefix(format);
      name.prefix(".");
      format_post->modify_file_basename(name,mon_probleme->reprise_effectuee(),-1);
    }
}
References besoin_postraiter_champs(), est_le_dernier_postraitement_pour_nom_fich_, format, format_post, Postraitement_base::mon_probleme, nom_fich(), Nom::prefix(), and Probleme_base::reprise_effectuee().
get_champ_post()
const Champ_Generique_base & Postraitement::get_champ_post (const Motcle & nom) const virtual
Definition at line 2239 of file Postraitement.cpp.
{
  REF(Champ_Generique_base) ref_champ;
  CONST_LIST_CURSEUR(Champ_Generique) curseur_liste_champs = champs_post_complet_;
  while (curseur_liste_champs)
    {
      try
        {
          return curseur_liste_champs.valeur().valeur().get_champ_post(nom);
        }
      catch (Champs_compris_erreur)
        {
        }
      ++curseur_liste_champs;
    }
  Cerr<<"Field " <<nom<<" not found."<< finl;
  throw Champs_compris_erreur();
// Pour compilation
  return ref_champ;
}
References Cerr, champs_post_complet_, CONST_LIST_CURSEUR, finl, Champ_Generique_base::get_champ_post(), REF, List_Champ_Generique::valeur(), and Deriv_Champ_Generique_base::valeur().
Referenced by champ_fonc(), Sonde::completer(), Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), creer_champ_post(), Probleme_base::get_champ_post(), init(), and postraiter_champs().
get_info()
const Type_info * Postraitement::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file Postraitement.cpp.
get_nom_localisation()
Nom Postraitement::get_nom_localisation (const Entity & loc) static
Definition at line 182 of file Postraitement.cpp.
{
  Nom loc_post;
  if (loc==ELEMENT)
    loc_post = "ELEM";
  else if (loc==NODE)
    loc_post = "SOM";
  else if (loc==FACE)
    loc_post = "FACES";
  else
    {
      Cerr<<"This location is not valid for the postprocessing"<<finl;
      exit();
    }
  return loc_post;
}
References Cerr, ELEMENT, Process::exit(), FACE, finl, and NODE.
Referenced by init(), and postraiter_champs().
ind_post()
int Postraitement::ind_post (int nb_pas_dt) inline
Definition at line 130 of file Postraitement.h.
{ return (nb_pas_dt%nb_pas_dt_post_==0) ? 1 : 0; }
References nb_pas_dt_post_.
Referenced by traiter_champs().
info()
const Type_info * Postraitement::info () static
Definition at line 33 of file Postraitement.cpp.
init()
void Postraitement::init () override virtual
Initialise le postraitement.
Cree le fichier associe au postraitement, ecrit
des infos sur TrioU. Ecrit le probleme sur
le fichier.
< format est deja dans nom_fich_ (xxx.lml, lata ou med)
< on ajoute dans la liste !
Reimplemented from Postraitement_base.
Definition at line 1154 of file Postraitement.cpp.
{
  assert(est_le_premier_postraitement_pour_nom_fich()!=-1);
  assert(est_le_dernier_postraitement_pour_nom_fich()!=-1);
  Schema_Temps_base& sch = mon_probleme->schema_temps();
  double temps_courant = sch.temps_courant();
  double tinit = sch.temps_init();
  Postraitement::formats_supportes=Motcles(5);
  assert(formats_supportes.size()==5);
  if(formats_supportes[0]!="lml")
    {
      formats_supportes[0]="lml";
      formats_supportes[1]="lata";
      formats_supportes[2]="meshtv";
      formats_supportes[3]="med";
      formats_supportes[4]="xyz";
    }
  const Domaine& dom=le_domaine.valeur();
  const Nom& nom_du_domaine = dom.le_nom();
  Nom name=nom_fich().prefix(format);
  name.prefix(".");
  if (besoin_postraiter_champs())
    {
      int reprise = mon_probleme->reprise_effectuee();
      format_post->modify_file_basename(name, reprise && est_le_premier_postraitement_pour_nom_fich_, tinit);
      format_post->ecrire_entete(temps_courant, reprise, est_le_premier_postraitement_pour_nom_fich_);
      format_post->preparer_post(nom_du_domaine, est_le_premier_postraitement_pour_nom_fich_, reprise, tinit);
    }
//
// S'il existe un champ a postraiter aux faces, on stocke ici une ref a la zone dis base du champ
// PQ : 13/06/13 : mis en attribut de la classe pour gerer les champs FACES en maillage deformable
// REF(Zone_dis_base) zone_dis_pour_faces;
  {
    LIST_CURSEUR(Nom) curseur1 = noms_champs_a_post_;
    Nom le_nom_champ_post;
    while(curseur1)
      {
        const Nom& nom_post = curseur1.valeur();
        const REF(Champ_Generique_base)& champ = get_champ_post(nom_post);
        int indic_correlation=0;
        if ((sub_type(Champ_Gen_de_Champs_Gen,champ.valeur())))
          {
            const Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,champ.valeur());
            if (sub_type(Champ_Generique_Correlation,champ_post.get_source(0)))
              indic_correlation=1;
          }
        if (!indic_correlation)
          {
            Champ espace_stockage;
            const Champ_base& champ_ecriture = champ->get_champ(espace_stockage);
            Entity loc = champ->get_localisation();
            const Nom loc_post = get_nom_localisation(loc);
            const Noms nom = champ->get_property("nom");
            const Noms composantes = champ->get_property("composantes");
            if (Motcle(loc_post) == "FACES" && Motcle(format).debute_par("lata")==0 && Motcle(format).debute_par("med")==0 && Motcle(format).debute_par("xyz")==0)
              {
                Cerr<<"The field "<<nom[0]<<" can not be postprocessed to the faces in the format "<<format<<finl;
                Cerr<<"The postprocessing to the faces is allowed only in the format lata or med"<<finl;
                exit();
              }
// PL: Ajout automatique du postraitement aux faces pour PolyMAC seul, sinon doit etre specifie par FACES
            if (Motcle(loc_post) == "FACES" || champ->get_ref_zone_dis_base().que_suis_je().debute_par("Zone_PolyMAC"))
              {
                REF(Zone_dis_base) ref_zone_dis = champ->get_ref_zone_dis_base();
                if (ref_zone_dis.non_nul())
                  zone_dis_pour_faces = ref_zone_dis;
              }
            const Nature_du_champ& nature = champ_ecriture.nature_du_champ();
            if (Motcle(nom_post)== Motcle(nom[0]))
              {
                le_nom_champ_post = nom[0];
                /* Sinon le cas Reprise_grossier_fin ne passe pas, en effet on doit pouvoir postraiter K_Eps
                   if (nature==multi_scalaire)
                   {
                   Cerr<<"The field "<<nom[0]<<" is of multi scalar nature."<<finl;
                   Cerr<<"Only the components of this field may be post-processed."<<finl;
                   exit();
                   } */
              }
            else
              {
                const Noms& noms_comp = composantes;
                int n = noms_comp.size();
                for (int i=0; i<n; i++)
                  if (Motcle(nom_post)==Motcle(noms_comp[i]))
                    le_nom_champ_post = noms_comp[i];
              }
// il n'existe pas d'interpolation aux faces pour les champs qui ne sont pas naturellement localises aux faces
// test pour gerer la problematique du post-traitement aux faces non pris en compte
            Nom nomposttmp(le_nom_champ_post) ;
            Nom& locpostjdd=nomposttmp.prefix(nom_du_domaine);
            locpostjdd.prefix("_");
            if (locpostjdd.finit_par("FACES") && Motcle(loc_post) != "FACES")
              {
                Cerr<<"The field "<< le_nom_champ_post <<" can not be postprocessed to the faces because this interpolation is not implemented in the code." <<finl;
                Cerr<<"The postprocessing to the faces is allowed only for the field naturally localized at the faces."<<finl;
                exit();
              }
            const int nb_compo = champ_ecriture.nb_comp();
            format_post->completer_post(dom,axi,nature,nb_compo,composantes,loc_post,le_nom_champ_post);
          }
        ++curseur1;
      }
  }
  const Nom token = nom_du_domaine+"_"+nom_fich_; //!< format est deja dans nom_fich_ (xxx.lml, lata ou med)
  const bool already_written_domain = liste_dom_ecrit.contient_(token);
//
// If domain is not time dependant, we write it in the ::init() method
// else we write it at each postraiter_champs() call
// PL: On ecrit le domaine que si le postraitement des champs est demande
  if(!dom.deformable() && besoin_postraiter_champs() && !already_written_domain)
    {
      liste_dom_ecrit.add(token); //!< on ajoute dans la liste !
      format_post->ecrire_domaine_dis(dom,zone_dis_pour_faces,est_le_premier_postraitement_pour_nom_fich_);
// zone_dis_pour_faces non_nul() si on demande un postraitement d'un champ aux faces:
      if (zone_dis_pour_faces.non_nul() && Motcle(format) != "LML")
        {
          const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis_pour_faces.valeur());
          const IntTab& faces_sommets = zone_vf.face_sommets();
          const int nb_sommets = dom.nb_som();
          const int nb_faces = faces_sommets.dimension(0);
          format_post->ecrire_item_int("FACES", /* Identifiant */
                                       dom.le_nom(),
                                       dom.zone(0).le_nom(),
                                       "FACES", /* localisation */
                                       "SOMMETS", /* reference */
                                       faces_sommets,
                                       nb_sommets);
          const IntTab& elem_faces = zone_vf.elem_faces();
          format_post->ecrire_item_int("ELEM_FACES", /* Identifiant */
                                       dom.le_nom(),
                                       dom.zone(0).le_nom(),
                                       "ELEMENTS", /* localisation */
                                       "FACES", /* reference */
                                       elem_faces,
                                       nb_faces);
        }
    }
  dernier_temps=mon_probleme->schema_temps().temps_init();
  format_post->modify_file_basename(name,0,tinit);
}
References Vect_Nom::add(), Objet_U::axi, besoin_postraiter_champs(), Cerr, Noms::contient_(), Nom::debute_par(), Domaine::deformable(), dernier_temps, TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), est_le_dernier_postraitement_pour_nom_fich(), est_le_premier_postraitement_pour_nom_fich(), est_le_premier_postraitement_pour_nom_fich_, Process::exit(), Zone_VF::face_sommets(), Nom::finit_par(), finl, format, format_post, formats_supportes, get_champ_post(), get_nom_localisation(), Champ_Gen_de_Champs_Gen::get_source(), le_domaine, Domaine::le_nom(), Zone::le_nom(), LIST_CURSEUR, liste_dom_ecrit, Postraitement_base::mon_probleme, Field_base::nature_du_champ(), Field_base::nb_comp(), Domaine::nb_som(), nom_fich(), nom_fich_, noms_champs_a_post_, O_U_Ptr::non_nul(), Nom::prefix(), Objet_U::que_suis_je(), REF, ref_cast, Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), vect_impl::size(), sub_type, Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), Ref_Zone_dis_base::valeur(), Ref_Domaine::valeur(), Domaine::zone(), and zone_dis_pour_faces.
les_sondes() [1/2]
Sondes & Postraitement::les_sondes () inline
Definition at line 108 of file Postraitement.h.
{ return les_sondes_; }
References les_sondes_.
les_sondes() [2/2]
const Sondes & Postraitement::les_sondes () const inline
Definition at line 107 of file Postraitement.h.
{ return les_sondes_; }
References les_sondes_.
Referenced by Sonde::completer(), Sonde::mettre_a_jour(), Sonde::postraiter(), and Sonde::readOn().
les_statistiques()
Operateurs_Statistique_tps & Postraitement::les_statistiques () inline
Definition at line 139 of file Postraitement.h.
{ return les_statistiques_; }
References les_statistiques_.
Referenced by Moyenne_volumique::get_champ().
lire_champs_a_postraiter()
int Postraitement::lire_champs_a_postraiter (Entree & s)
Lit le nom des champs a postraiter sur un flot d'entree.
Format:
{
???
}.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 770 of file Postraitement.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  Motcle motlu2;
  s >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "We expected { to start to read the fields of postprocessing with the simplified syntax" << finl;
      exit();
    }
  s >> motlu;
  Noms liste_noms;
  mon_probleme->get_noms_champs_postraitables(liste_noms);
// Cerr<<"liste_noms="<<liste_noms<<finl;
  while (motlu != accolade_fermee)
    {
// GF pour tester le creer_champ
      for (int i=0; i<liste_noms.size()*0; i++)
        {
          Motcle toto(liste_noms[i]);
          mon_probleme->creer_champ(toto);
          Cerr<<" get "<<toto<<" ";
          Cerr<<mon_probleme->get_champ(toto)<<finl;
        }
      Nom expression;
      int is_champ_predefini = probleme().expression_predefini(motlu,expression);
      if ((is_champ_predefini) && (!comprend_champ_post(motlu)))
        {
          Champ_Generique champ;
          Entree_complete s_complete(expression,s);
          s_complete>>champ;
          complete_champ(champ,motlu);
        }
      s>>motlu2;
      if ((motlu2=="elem") || (motlu2=="som") || (motlu2=="faces"))
        {
// Prise en compte des pb_med
          if (mon_probleme.valeur().que_suis_je()!="Pb_MED")
            creer_champ_post(motlu,motlu2,s);
          else
            creer_champ_post_med(motlu,motlu2,s);
          s>>motlu;
        }
      else
        {
// On teste la distinction entre un Champ_Generique a creer par macro (sans som specifie)
// et l ajout d un Champ_Generique deja cree (existant dans champs_post_complet_)
// On va tester si le motlu correpond au nom d un champ porte par le probleme
// Si c est le cas on cree un Champ_Generique par macro sinon on va recuperer le Champ_Generique dans la liste complete
// et on l ajoute dans la liste des champs a postraiter
          Motcles mots_compare(liste_noms.size());
          for (int i=0; i<liste_noms.size(); i++)
            mots_compare[i] = liste_noms[i];
          if (mots_compare.contient_(motlu))
            creer_champ_post(motlu,"som",s);
          else
            {
              if (motlu=="pas_de_temps")
                {
                  int nb_eq = probleme().nombre_d_equations();
                  for (int i=0; i<nb_eq; i++)
                    {
                      int nb_morceaux = probleme().equation(i).nombre_d_operateurs();
                      for (int j=0; j<nb_morceaux; j++)
                        creer_champ_post_moreqn("operateur","stabilite",i,j,-1,s);
                    }
                }
              else if (motlu=="flux_bords" || motlu=="flux_surfacique_bords")
                {
                  int nb_eq = probleme().nombre_d_equations();
                  for (int i=0; i<nb_eq; i++)
                    {
                      int nb_morceaux = probleme().equation(i).nombre_d_operateurs_tot();
                      const Champ_Inc& ch_inco = probleme().equation(i).inconnue();
                      int nb_compo = ch_inco->nb_comp();
                      int compo;
                      for (int j=0; j<nb_morceaux; j++)
{
                          if (j==3)
                            nb_compo = 1;
                          for (int comp=0; comp<nb_compo; comp++)
{
                              if (nb_compo==1)
                                compo=-1;
                              else
                                compo=comp;
                              creer_champ_post_moreqn("operateur",motlu,i,j,compo,s);
                            }
                        }
                    }
                }
              else
                {
                  const Champ_Generique_base& champ_op = probleme().get_champ_post(motlu);
                  const Noms nom = champ_op.get_property("nom");
                  if (noms_champs_a_post_.contient(nom[0]))
                    {
                      Cerr << "Postraitement::lire_champs_a_postraiter : duplicate field " << nom[0] << finl;
                      exit();
                    }
                  else
                    noms_champs_a_post_.add(nom[0]);
                }
            }
          motlu=motlu2;
        }
    }
  return 1;
}
References List_Nom::add(), Cerr, complete_champ(), comprend_champ_post(), List_Nom::contient(), Motcles::contient_(), Probleme_base::creer_champ(), creer_champ_post(), creer_champ_post_med(), creer_champ_post_moreqn(), Probleme_base::equation(), Process::exit(), Probleme_base::expression_predefini(), finl, Probleme_base::get_champ(), Probleme_base::get_champ_post(), Probleme_base::get_noms_champs_postraitables(), Champ_Generique_base::get_property(), Equation_base::inconnue(), Postraitement_base::mon_probleme, Probleme_base::nombre_d_equations(), Equation_base::nombre_d_operateurs(), Equation_base::nombre_d_operateurs_tot(), noms_champs_a_post_, probleme(), Objet_U::que_suis_je(), vect_impl::size(), and Ref_Probleme_base::valeur().
Referenced by lire_motcle_non_standard().
lire_champs_operateurs()
int Postraitement::lire_champs_operateurs (Entree & is)
Lit les champs a postraiter sur un flot d'entree.
Definition at line 1004 of file Postraitement.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  Champ_Generique champ;
  s>>motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "We expected { to start to read the postprocessing fields" << finl;
      exit();
    }
  s>>motlu;
  Nom expression;
  int is_champ_predefini = probleme().expression_predefini(motlu,expression);
  if (is_champ_predefini)
    {
      Cerr<<"The name "<<motlu<<" of a post-processing field of the problem "<<probleme().le_nom()<<finl;
      Cerr<<"is identical to the name of one of this problem pre-defined post-processing fields."<<finl;
      Cerr<<"Please change the name of this post-processing field."<<finl;
      exit();
    }
  while (motlu != accolade_fermee)
    {
      Cerr <<"Reading definition of field "<<motlu<<finl;
      s>>champ;
      complete_champ(champ,motlu);
      s>>motlu;
    }
  return 1;
}
References Cerr, complete_champ(), Process::exit(), Probleme_base::expression_predefini(), finl, Probleme_base::le_nom(), and probleme().
Referenced by lire_motcle_non_standard(), and readOn().
lire_champs_stat_a_postraiter()
int Postraitement::lire_champs_stat_a_postraiter (Entree & s)
Definition at line 894 of file Postraitement.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu,motlu2,motlu3,motlu4,indic_corr;
  Motcle elem("elem");
  Motcle som("som");
  indic_corr="non_correlation";
  s >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "We expected { to start to read the data to create the statistical fields" << finl;
      exit();
    }
  Noms liste_noms;
  mon_probleme->get_noms_champs_postraitables(liste_noms);
// Cerr<<"liste_noms="<<liste_noms<<finl;
  s >> motlu;
  if (motlu == Motcle("t_deb"))
    s >> tstat_deb_;
  else
    {
      Cerr << "Error while reading the statistics in the postprocessing" << finl;
      Cerr << "We expected the keyword t_deb instead of " << motlu << finl;
      exit();
    }
  s >> motlu;
  if (motlu == Motcle("t_fin"))
    s >> tstat_fin_;
  else
    {
      Cerr << "Error while reading the statistics in the postprocessing" << finl;
      Cerr << "We expected the keyword t_fin instead of " << motlu << finl;
      exit();
    }
  probleme().verifie_tdeb_tfin("statistics block");
  s >> motlu;
  while (motlu != accolade_fermee)
    {
      s>>motlu2;
      s>>motlu3;
      if (motlu!="correlation")
        {
          if ((motlu3=="elem") || (motlu3=="som") || (motlu3=="faces"))
            {
              creer_champ_post_stat(motlu2,motlu3,motlu,indic_corr,tstat_deb_,tstat_fin_,s);
              s>>motlu;
            }
          else
            {
              creer_champ_post_stat(motlu2,"som",motlu,indic_corr,tstat_deb_,tstat_fin_,s);
              motlu=motlu3;
            }
        }
      else
        {
          s>>motlu4;
          if ((motlu4=="elem") || (motlu4=="som") || (motlu4=="faces"))
            {
              creer_champ_post_stat(motlu2,motlu4,motlu,motlu3,tstat_deb_,tstat_fin_,s);
              s>>motlu;
            }
          else
            {
              creer_champ_post_stat(motlu2,"som",motlu,motlu3,tstat_deb_,tstat_fin_,s);
              motlu=motlu4;
            }
        }
      nb_champs_stat_ += 1;
    }
  return 1;
}
References Cerr, creer_champ_post_stat(), Process::exit(), finl, Probleme_base::get_noms_champs_postraitables(), Postraitement_base::mon_probleme, nb_champs_stat_, probleme(), tstat_deb_, tstat_fin_, and Probleme_base::verifie_tdeb_tfin().
Referenced by lire_motcle_non_standard().
lire_fichier()
void Postraitement::lire_fichier (const Nom & nom_fichier)
Definition at line 1040 of file Postraitement.cpp.
{
  LecFicDiffuse_JDD f(nom_fichier);
  Motcle motlu;
  Champ_Generique champ;
  if (!f.good())
    {
      Cerr << "Cannot open the file " << nom_fichier << finl;
      Process::exit();
    }
  f >> motlu;
  while (!f.eof())
    {
      Cerr <<"Reading definition of field "<<motlu<<finl;
      f >> champ;
      complete_champ(champ,motlu);
      f >> motlu;
    }
  f.close();
}
References Cerr, Entree_Fichier_base::close(), complete_champ(), Lec_Diffuse_base::eof(), Process::exit(), finl, Lec_Diffuse_base::good(), and nom_fichier().
Referenced by lire_motcle_non_standard().
lire_motcle_non_standard()
int Postraitement::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
< XD_ADD_P chaine name of file
< XD_ADD_P chaine name of file containing the definition of advanced fields
Reimplemented from Objet_U.
Definition at line 376 of file Postraitement.cpp.
{
  Motcle motlu;
  if (mot=="Sondes|Probes")
    {
      Cerr << "Reading of probes" << finl;
      les_sondes_.associer_post(*this);
      s >> les_sondes_;
      sondes_demande_ = 1;
      return 1;
    }
  if (mot=="Sondes_fichier|Probes_file")
    {
      Nom file;
      Param param2("probes_files");
// XD sondes_fichier objet_lecture nul 1 not_set
      param2.ajouter("fichier|file",&file,Param::REQUIRED); //!< XD_ADD_P chaine name of file
      param2.lire_avec_accolades_depuis(s);
      Cerr << "Reading of probes" << finl;
      les_sondes_.associer_post(*this);
      les_sondes_.lire_fichier(file);
      sondes_demande_ = 1;
      return 1;
    }
  else if (mot=="champs|fields")
    {
      Cerr << "Reading of fields to be postprocessed" << finl;
      Noms liste_noms;
      Option opt=DESCRIPTION;
      mon_probleme->get_noms_champs_postraitables(liste_noms,opt);
      s >> motlu;
      if (motlu == "binaire")
        {
          binaire=1;
          s >> motlu;
        }
      else if (motlu == "formatte")
        {
          binaire=0;
          s >> motlu;
        }
      if (motlu == "dt_post")
        {
          Nom expression;
          s >> expression;
          fdt_post.setNbVar(1);
          fdt_post.setString(expression);
          fdt_post.addVar("t");
          fdt_post.parseString();
          dt_post_ch_ = fdt_post.eval();
        }
      else if (motlu == "nb_pas_dt_post")
        s >> nb_pas_dt_post_;
      else
        {
          Cerr << "Error while reading the input data for postprocessing :" << finl;
          Cerr << "We expected the keyword dt_post or nb_pas_dt_post" << finl;
          exit();
        }
// La methode lire_champs_a_postraiter() va generer auatomatiquement un Champ_Generique
// en fonction des indications du jeu de donnees (ancienne formulation)
      lire_champs_a_postraiter(s);
      champs_demande_ = 1;
      return 1;
    }
  else if (mot=="Statistiques")
    {
      Cerr << "Reading of the statistics block" << finl;
      s >> motlu;
      if (motlu == "dt_post")
        {
          Nom expression;
          s >> expression;
          fdt_post.setNbVar(1);
          fdt_post.setString(expression);
          fdt_post.addVar("t");
          fdt_post.parseString();
          dt_post_stat_ = fdt_post.eval();
        }
      else if (motlu == "nb_pas_dt_post")
        s >> nb_pas_dt_post_;
      else
        {
          Cerr << "Error while reading the input data for statistics postprocessing :" << finl;
          Cerr << "We expected the keyword dt_post or nb_pas_dt_post" << finl;
          exit();
        }
// La methode lire_champs_stat_a_postraiter() va generer auatomatiquement un Champ_Generique
// en fonction des indications du jeu de donnees (ancienne formulation)
      lire_champs_stat_a_postraiter(s);
// Activer pour lancer la sauvegarde et la reprise des statistiques
      stat_demande_ = 1;
      return 1;
    }
  else if (mot=="Domaine")
    {
      if ((champs_demande_) || (stat_demande_))
        {
          Cerr<<"The domain must be specified before reading Champs and Statistiques blocks "<<finl;
          exit();
        }
      Nom nom_du_domaine;
      s >> nom_du_domaine;
      le_domaine=ref_cast(Domaine,Interprete::objet(nom_du_domaine));
      return 1;
    }
  else if (mot=="Sondes_Int")
    {
      Cerr << "Reading of probes related to integers arrays" << finl;
      les_sondes_int_.associer_post(*this);
      s >> les_sondes_int_;
      les_sondes_int_.ouvrir_fichiers();
      sondes_demande_ = 1;
      return 1;
    }
  else if (mot=="Tableaux_Int")
    {
      Cerr << "Reading of integers arrays to be postprocessed "<< finl;
      s >> motlu;
      if (motlu != "dt_post")
        {
          Cerr << "Error while reading the statistics block:" << finl;
          Cerr << "We expected the keyword dt_post " << finl;
          exit();
        }
      s >> dt_post_tab;
      lire_tableaux_a_postraiter(s);
      tableaux_demande_ = 1;
      return 1;
    }
  else if (mot=="Statistiques_en_serie")
    {
      Cerr << "Reading of the serial statistics block" << finl;
      s >> motlu;
      if (motlu != "dt_integr")
        {
          Cerr << "Error while reading the statistics block:" << finl;
          Cerr << "We expected the keyword dt_integr " << finl;
          exit();
        }
      s >> dt_integr_serie_;
      dt_post_stat_ = dt_post_ch_;
      lire_champs_stat_a_postraiter(s);
      stat_demande_ = 1;
      lserie_=1;
      return 1;
    }
  else if (mot=="Definition_champs")
    {
// La methode lire_champs_operateurs() permet la lecture d un champ a postraiter avec
// la nouvelle formulation dans le jeu de donnees
      lire_champs_operateurs(s);
      return 1;
    }
  else if (mot=="Definition_champs_fichier|Definition_champs_file")
    {
// bool depuisFichier = false;
      Nom file;
      Param param("definition_champ_files");
// XD Definition_champs_fichier objet_lecture nul 1 Keyword to read definition_champs from a file
      param.ajouter("fichier|file",&file,Param::REQUIRED); //!< XD_ADD_P chaine name of file containing the definition of advanced fields
      param.lire_avec_accolades_depuis(s);
      Cerr << "Reading of Definition_champs from file " << file << finl;
      lire_fichier(file);
      return 1;
    }
  else
    {
      Cerr << mot << " is not a keyword understood by " << que_suis_je() << " in lire_motcle_non_standard"<< finl;
      exit();
    }
  return -1;
}
References Parser_U::addVar(), Param::ajouter(), Sondes::associer_post(), Sondes_Int::associer_post(), binaire, Cerr, champs_demande_, DESCRIPTION, dt_integr_serie_, dt_post_ch_, dt_post_stat_, dt_post_tab, Parser_U::eval(), Process::exit(), fdt_post, finl, Probleme_base::get_noms_champs_postraitables(), le_domaine, les_sondes_, les_sondes_int_, Param::lire_avec_accolades_depuis(), lire_champs_a_postraiter(), lire_champs_operateurs(), lire_champs_stat_a_postraiter(), lire_fichier(), Sondes::lire_fichier(), lire_tableaux_a_postraiter(), lserie_, Postraitement_base::mon_probleme, nb_pas_dt_post_, Interprete::objet(), Sondes_Int::ouvrir_fichiers(), Parser_U::parseString(), Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, Parser_U::setNbVar(), Parser_U::setString(), sondes_demande_, stat_demande_, and tableaux_demande_.
lire_tableaux_a_postraiter()
int Postraitement::lire_tableaux_a_postraiter (Entree & s)
Definition at line 1082 of file Postraitement.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
  Nom nom_tab;
  s >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "We expected { to start to read the postprocessing data" << finl;
      exit();
    }
  s >> nom_tab;
  motlu = nom_tab;
  while (motlu != accolade_fermee)
    {
// Recherche du tableau a postraiter
      REF(IntVect) ch_tab;
      Noms liste_noms;
      mon_probleme->get_noms_champs_postraitables(liste_noms);
//
// if (liste_noms.contient(motlu))
      for (int i=0; i<liste_noms.size(); i++)
        if (liste_noms[i]==motlu)
          {
            if (mon_probleme->a_pour_IntVect(motlu,ch_tab))
              {
                noms_tableaux_.add(nom_tab);
                tableaux_a_postraiter_.add(ch_tab);;
              }
            else
              {
                Cerr << "The problem do not have the array " << motlu << finl;
                exit();
              }
          }
        else if (i==liste_noms.size()-1)
          {
            Cerr << "The problem does not understand the word " << motlu << finl;
            exit();
          }
      s >> nom_tab;
      motlu = nom_tab;
    }
  return 1;
}
References Probleme_base::a_pour_IntVect(), List_Nom::add(), List_Ref_IntVect::add(), Cerr, Process::exit(), finl, Probleme_base::get_noms_champs_postraitables(), Postraitement_base::mon_probleme, noms_tableaux_, REF, vect_impl::size(), and tableaux_a_postraiter_.
Referenced by lire_motcle_non_standard().
lpost()
int Postraitement::lpost (double temps_courant, double dt_post) const inline
Definition at line 241 of file Postraitement.h.
{
  double epsilon = 1.e-8;
  if (dt_post<=temps_courant - dernier_temps)
    return 1;
  else
    {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      double i, j;
      modf(temps_courant/dt_post + epsilon, &i);
      modf(dernier_temps/dt_post + epsilon, &j);
      return ( i>j );
    }
}
References dernier_temps.
Referenced by lpost_champ(), lpost_stat(), and lpost_tab().
lpost_champ()
int Postraitement::lpost_champ (double temps_courant) const inline
Test de postraitement en tenant compte de l'evolution en temps
du champ.
Renvoie VRAI si le champ necessite un postraitement, vu
le temps courant et le pas de temps fourni.
Returns
int
Signification: valeur booleenne, VRAI si le pas de temp et le temps
courant fournis indique qu'un postraitement est
necessaire, FAUX sinon.
Contraintes:
Definition at line 280 of file Postraitement.h.
{ return lpost(temps_courant, dt_post_ch_); }
References dt_post_ch_, and lpost().
Referenced by traiter_champs().
lpost_stat()
int Postraitement::lpost_stat (double temps_courant) const inline
Definition at line 281 of file Postraitement.h.
{ return lpost(temps_courant, dt_post_stat_); }
References dt_post_stat_, and lpost().
Referenced by traiter_champs().
lpost_tab()
int Postraitement::lpost_tab (double temps_courant) const inline
Definition at line 282 of file Postraitement.h.
{ return lpost(temps_courant, dt_post_tab); }
References dt_post_tab, and lpost().
Referenced by traiter_tableaux().
mettre_a_jour()
void Postraitement::mettre_a_jour (double temps) override virtual
< Il y a eu mise a jour effective des integrales
< si reprise du calcul apres la fin des stats
< si dt cst !!!
< pour eviter une division par 0
Reimplemented from Postraitement_base.
Definition at line 89 of file Postraitement.cpp.
{
// Mise a jour des operateurs statistiques portes par les Champ_Generique_Statistiques
  LIST_CURSEUR(Champ_Generique) curseur2 = champs_post_complet_ ;
  while(curseur2)
    {
      curseur2.valeur()->mettre_a_jour(temps);
      ++curseur2;
    }
  if ( inf_ou_egal(tstat_deb_,temps) &&  inf_ou_egal(temps,tstat_fin_) )
    tstat_dernier_calcul_ =  temps;//!< Il y a eu mise a jour effective des integrales
  if ( sup_ou_egal(temps, tstat_fin_))  //!< si reprise du calcul apres la fin des stats
    {
      double dt=probleme().schema_temps().pas_de_temps(); //!< si dt cst !!!
      if (sup_strict(dt,0)) //!< pour eviter une division par 0
        tstat_dernier_calcul_ =  floor(tstat_fin_/dt)*dt;
    }
}
References champs_post_complet_, inf_ou_egal(), LIST_CURSEUR, Schema_Temps_base::pas_de_temps(), probleme(), Probleme_base::schema_temps(), sup_ou_egal(), sup_strict(), tstat_deb_, tstat_dernier_calcul_, tstat_fin_, and List_Champ_Generique::valeur().
nom_fich()
Nom Postraitement::nom_fich () const inline
Definition at line 133 of file Postraitement.h.
{ return nom_fich_; };
References nom_fich_.
Referenced by finir(), init(), and Probleme_base::init_postraitements().
noms_champs_a_post()
List_Nom & Postraitement::noms_champs_a_post () inline
Definition at line 146 of file Postraitement.h.
{ return noms_champs_a_post_; }
References noms_champs_a_post_.
Referenced by Mod_turb_hyd_base::preparer_calcul().
noms_fichiers_sondes()
static List_Nom & Postraitement::noms_fichiers_sondes () inline static
Definition at line 136 of file Postraitement.h.
{ return noms_fichiers_sondes_; }
References noms_fichiers_sondes_.
Referenced by Sonde::associer_post(), and Sonde_Int::associer_post().
postraiter() [1/2]
int Postraitement::postraiter (const Domaine & dom, const Noms & unites, const Noms & noms_compo, const int ncomp, const double temps_champs, double & temps_courant, Nom nom_post, const Nom & localisation, const Nom & nature, const DoubleTab & valeurs, int tenseur)
Definition at line 1574 of file Postraitement.cpp.
{
  if (!tenseur)
    postraiter_tableau(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,nom_post,localisation,nature,valeurs);
  else
    postraiter_tenseur(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,nom_post,localisation,nature,valeurs);
  return 1;
}
References postraiter_tableau(), and postraiter_tenseur().
postraiter() [2/2]
void Postraitement::postraiter (int forcer) override virtual
Implements Postraitement_base.
Definition at line 51 of file Postraitement.cpp.
{
  if (forcer)
    {
      if (sondes_demande_)   postraiter_sondes();
      if (besoin_postraiter_champs())   postraiter_champs();
      if (tableaux_demande_) postraiter_tableaux();
    }
  else
    {
      if (sondes_demande_)   traiter_sondes();
      if (besoin_postraiter_champs())   traiter_champs();
      if (tableaux_demande_) traiter_tableaux();
    }
  dernier_temps=mon_probleme->schema_temps().temps_courant();
// Cas des statistiques en serie, il faut traiter APRES le postraitement
  if (lserie_)
    {
      if (sup_ou_egal(dernier_temps-tstat_deb_,dt_integr_serie_))
        {
          tstat_deb_ = dernier_temps;
          tstat_dernier_calcul_ = tstat_deb_;
          tstat_fin_ = tstat_deb_ + dt_integr_serie_;
          LIST_CURSEUR(Champ_Generique) curseur2 = champs_post_complet_ ;
          while(curseur2)
            {
              if (sub_type(Champ_Gen_de_Champs_Gen,curseur2.valeur().valeur()))
                {
                  Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,curseur2.valeur().valeur());
                  champ_post.fixer_serie(tstat_deb_,tstat_fin_);
                }
              ++curseur2;
            }
        }
    }
}
References besoin_postraiter_champs(), champs_post_complet_, dernier_temps, dt_integr_serie_, Champ_Gen_de_Champs_Gen::fixer_serie(), LIST_CURSEUR, lserie_, Postraitement_base::mon_probleme, postraiter_champs(), postraiter_sondes(), postraiter_tableaux(), ref_cast, Probleme_base::schema_temps(), sondes_demande_, sub_type, sup_ou_egal(), tableaux_demande_, Schema_Temps_base::temps_courant(), traiter_champs(), traiter_sondes(), traiter_tableaux(), tstat_deb_, tstat_dernier_calcul_, and tstat_fin_.
Referenced by postraiter_champs().
postraiter_champs()
int Postraitement::postraiter_champs ()
Effectue le postraitement des Champs de facon imperative.
Mets a jour les champs crees.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 1357 of file Postraitement.cpp.
{
  double temps_courant = mon_probleme->schema_temps().temps_courant();
  const Domaine& dom=le_domaine.valeur();
  if (temps_ < temps_courant)
    {
      if (est_le_premier_postraitement_pour_nom_fich_)
        format_post->ecrire_temps(temps_courant);
    }
// We write the time dependant domain here. PL: we write only if fields list is not empty
  if (dom.deformable() && besoin_postraiter_champs())
    {
      format_post->ecrire_domaine_dis(dom,zone_dis_pour_faces,est_le_premier_postraitement_pour_nom_fich_);
      if (zone_dis_pour_faces.non_nul())
        {
          const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis_pour_faces.valeur());
          const IntTab& faces_sommets = zone_vf.face_sommets();
          const int nb_sommets = dom.nb_som();
          const int nb_faces = faces_sommets.dimension(0);
          format_post->ecrire_item_int("FACES", /* Identifiant */
                                       dom.le_nom(),
                                       dom.zone(0).le_nom(),
                                       "FACES", /* localisation */
                                       "SOMMETS", /* reference */
                                       faces_sommets,
                                       nb_sommets);
          const IntTab& elem_faces = zone_vf.elem_faces();
          format_post->ecrire_item_int("ELEM_FACES", /* Identifiant */
                                       dom.le_nom(),
                                       dom.zone(0).le_nom(),
                                       "ELEMENTS", /* localisation */
                                       "FACES", /* reference */
                                       elem_faces,
                                       nb_faces);
        }
    }
  format_post->init_ecriture(temps_courant,temps_,est_le_premier_postraitement_pour_nom_fich_,dom);
  if (temps_ < temps_courant)
    temps_=temps_courant;
  LIST_CURSEUR(Nom) curseur1 = noms_champs_a_post_;
  while(curseur1)
    {
      const Champ_Generique_base& champ = get_champ_post(curseur1.valeur());
// Etape de calcul
// Le champ cree est rendu dans champ_ecriture
      Champ espace_stockage;
      const Champ_base& champ_ecriture = champ.get_champ(espace_stockage);
      DoubleTab val_vec;
      bool isChamp_Face_PolyMAC = (champ_ecriture.que_suis_je()=="Champ_Face_PolyMAC" || champ_ecriture.que_suis_je()=="Champ_Face_PolyMAC_P0");
      if (isChamp_Face_PolyMAC)
        champ_ecriture.valeur_aux_faces(val_vec);
      const DoubleTab& valeurs_post = isChamp_Face_PolyMAC ? val_vec : champ_ecriture.valeurs();
// Etape de recuperation des informations specifiques au champ a postraiter
      Entity loc = champ.get_localisation();
      const Nom localisation = get_nom_localisation(loc);
      const Noms nom_post = champ.get_property("nom");
      const Noms& unites = champ.get_property("unites");
      const Noms& noms_compo = champ.get_property("composantes");
      const double temps_champ = champ.get_time();
      int tenseur = champ.get_info_type_post();
// Etape pour savoir si on doit postraiter un champ ou une de ses composantes
      int ncomp = Champ_Generique_base::composante(curseur1.valeur(),nom_post[0],noms_compo,champ.get_property("synonyms"));
// La distinction du type de postraitement (tableau ou tenseur) est fait dans la methode postraiter par la valeur de tenseur
      Nom nature("scalar");
      if (champ_ecriture.nature_du_champ()==vectoriel) nature="vector";
      postraiter(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,curseur1.valeur(),localisation,nature,valeurs_post,tenseur);
      ++curseur1;
    }
  format_post->finir_ecriture(temps_courant);
  return 1;
}
References besoin_postraiter_champs(), Champ_Generique_base::composante(), Domaine::deformable(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), est_le_premier_postraitement_pour_nom_fich_, Zone_VF::face_sommets(), format_post, Champ_Generique_base::get_champ(), get_champ_post(), Champ_Generique_base::get_info_type_post(), Champ_Generique_base::get_localisation(), get_nom_localisation(), Champ_Generique_base::get_property(), Champ_Generique_base::get_time(), le_domaine, Domaine::le_nom(), Zone::le_nom(), LIST_CURSEUR, Postraitement_base::mon_probleme, Field_base::nature_du_champ(), Domaine::nb_som(), noms_champs_a_post_, O_U_Ptr::non_nul(), postraiter(), Objet_U::que_suis_je(), ref_cast, Probleme_base::schema_temps(), temps_, Schema_Temps_base::temps_courant(), Ref_Zone_dis_base::valeur(), Ref_Domaine::valeur(), Champ_base::valeur_aux_faces(), Champ_Proto::valeurs(), vectoriel, Domaine::zone(), and zone_dis_pour_faces.
Referenced by postraiter(), and traiter_champs().
postraiter_sondes()
int Postraitement::postraiter_sondes ()
Effectue le postraitement lie au sondes de facon imperative.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 1544 of file Postraitement.cpp.
{
  les_sondes_.postraiter();
  les_sondes_int_.postraiter(mon_probleme->schema_temps().temps_courant());
  return 1;
}
References les_sondes_, les_sondes_int_, Postraitement_base::mon_probleme, Sondes::postraiter(), Sondes_Int::postraiter(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by postraiter().
postraiter_tableau()
int Postraitement::postraiter_tableau (const Domaine & dom, const Noms & unites, const Noms & noms_compo, const int ncomp, const double temps_champs, double & temps_courant, Nom nom_post, const Nom & localisation, const Nom & nature, const DoubleTab & valeurs)
Definition at line 1588 of file Postraitement.cpp.
{
  const Nom& id_du_domaine = dom.le_nom();
  const Nom& id_champ_ecrit = nom_post;
  const int dim0 = valeurs.dimension(0);
  const int N = valeurs.line_size();
  DoubleTab valeurs_tmp(dim0, ncomp == -1 ? N : 1);
  for (int i = 0; i < dim0; i++)
    if (ncomp == -1)
      for (int j = 0; j < N; j++)
        valeurs_tmp(i, j) = valeurs(i, j);
    else
      valeurs_tmp(i, 0) = valeurs(i, ncomp);
  const DoubleTab& val_post_ecrit = valeurs_tmp;
  if (Motcle(format)=="XYZ")
    {
      if (localisation == "SOM")
        {
          const DoubleTab coord = dom.coord_sommets();
          format_post->ecrire_champ2(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,id_champ_ecrit,id_du_domaine,localisation,nature,val_post_ecrit,coord);
        }
      else if (localisation == "ELEM")
        {
          /*  Cerr << "Coucou Lamia 1" << finl;
            const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis_pour_faces.valeur());
            Cerr << "Coucou Lamia 2" << finl;
            const DoubleTab coord = zone_vf.xp();
            Cerr << "Coucou Lamia 3" << finl;
          */
          const Zone& zone=dom.zone(0);
          DoubleTab coord;
          zone.calculer_centres_gravite(coord);
          format_post->ecrire_champ2(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,id_champ_ecrit,id_du_domaine,localisation,nature,val_post_ecrit,coord);
        }
      else if (localisation == "FACES")
        {
          const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis_pour_faces.valeur());
          const DoubleTab coord = zone_vf.xv();
          format_post->ecrire_champ2(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,id_champ_ecrit,id_du_domaine,localisation,nature,val_post_ecrit,coord);
        }
    }
  else
    format_post->ecrire_champ(dom,unites,noms_compo,ncomp,temps_champ,temps_courant,id_champ_ecrit,id_du_domaine,localisation,nature,val_post_ecrit);
  return 1;
}
References Zone::calculer_centres_gravite(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), format, format_post, Domaine::le_nom(), TRUSTVect< _TYPE_ >::line_size(), ref_cast, Ref_Zone_dis_base::valeur(), Zone_VF::xv(), Domaine::zone(), and zone_dis_pour_faces.
Referenced by postraiter(), and postraiter_tenseur().
postraiter_tableaux()
int Postraitement::postraiter_tableaux ()
Definition at line 1444 of file Postraitement.cpp.
{
  double temps_courant = mon_probleme->schema_temps().temps_courant();
  const Domaine& dom=le_domaine.valeur();
// Methode ecrire_item_int codee uniquement pour les formats lml et lata
// Sans doute pas testee par les cas de non regression
// Signature a revoir (supprimer id_zone)
// Si codage de la methode pour meshtv, ajouter init_ecriture() et finir_ecriture()
  if (temps_ < temps_courant)
    {
      temps_=temps_courant;
      if (est_le_premier_postraitement_pour_nom_fich_)
        format_post->ecrire_temps(temps_courant);
    }
  LIST_CURSEUR(REF(IntVect)) curseur1 = tableaux_a_postraiter_;
  LIST_CURSEUR(Nom) curseur2 = noms_tableaux_;
  while(curseur1)
    {
      const Nom& id_item = curseur2.valeur();
      const Nom& id_du_domaine = dom.le_nom();
      const Nom& id_zone = dom.zone(0).le_nom();
      const Nom localisation="";
      const Nom reference="";
      const IntVect& val =  curseur1->valeur();
      const int ref_size =0;
      format_post->ecrire_item_int(id_item,id_du_domaine,id_zone,localisation,reference,val,ref_size);
      ++curseur1;
      ++curseur2;
    }
  return 1;
}
References est_le_premier_postraitement_pour_nom_fich_, format_post, le_domaine, Domaine::le_nom(), Zone::le_nom(), LIST_CURSEUR, Postraitement_base::mon_probleme, noms_tableaux_, REF, Probleme_base::schema_temps(), tableaux_a_postraiter_, temps_, Schema_Temps_base::temps_courant(), Ref_Domaine::valeur(), and Domaine::zone().
Referenced by postraiter(), and traiter_tableaux().
postraiter_tenseur()
int Postraitement::postraiter_tenseur (const Domaine & dom, const Noms & unites, const Noms & noms_compo, const int ncomp, const double temps_champs, double & temps_courant, Nom nom_post, const Nom & localisation, const Nom & nature, const DoubleTab & valeurs)
Definition at line 1639 of file Postraitement.cpp.
{
  int nb_comp = noms_compo.size();
  for (int comp=0; comp<nb_comp; comp++)
    postraiter_tableau(dom,unites,noms_compo,comp,temps_champ,temps_courant,noms_compo[comp],localisation,nature,valeurs);
  return 1;
}
References postraiter_tableau(), and vect_impl::size().
Referenced by postraiter().
printOn()
Sortie & Postraitement::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 232 of file Postraitement.cpp.
{
  s << que_suis_je() << finl;
  return s << finl;
}
References finl, and Objet_U::que_suis_je().
probleme() [1/2]
Probleme_base & Postraitement::probleme () inline
Definition at line 109 of file Postraitement.h.
{ return mon_probleme.valeur(); }
References Postraitement_base::mon_probleme, and Ref_Probleme_base::valeur().
Referenced by cherche_stat_dans_les_sources(), Sonde::completer(), Champ_Generique_modifier_pour_QC::completer(), Sonde::init_bords(), lire_champs_a_postraiter(), lire_champs_operateurs(), lire_champs_stat_a_postraiter(), mettre_a_jour(), Sonde::mettre_a_jour(), Sonde::mettre_a_jour_bords(), nom_fichier(), Sonde::ouvrir_fichier(), Sonde::postraiter(), readOn(), Sonde::readOn(), Sonde_Int::readOn(), reprendre(), Operateurs_Statistique_tps::reprendre(), sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), set_expression_champ(), Sondes::set_noms_champs_postraitables(), traiter_tableaux(), and verifie_nom_et_sources().
probleme() [2/2]
const Probleme_base & Postraitement::probleme () const inline
Definition at line 110 of file Postraitement.h.
{ return mon_probleme.valeur(); }
References Postraitement_base::mon_probleme, and Ref_Probleme_base::valeur().
readOn()
Entree & Postraitement::readOn (Entree & s) override protected virtual
Lit les directives de postraitement sur un flot d'entree.
Format:
Postraitement
{
Sondes bloc de lecture des sondes |
Champs bloc de lecture des champs a postraiter |
Statistiques bloc de lecture objet statistique |
Fichier
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 264 of file Postraitement.cpp.
{
  Cerr << "Reading guidelines of postprocessing" << finl;
  assert(mon_probleme.non_nul());
  const Nom& le_nom_du_post =le_nom();
  Nom vide;
  if ((le_nom_du_post!="neant")&&(le_nom_du_post!=vide))
    {
      nom_fich_+="_";
      nom_fich_+=le_nom_du_post;
    }
  Probleme_base& le_pb = mon_probleme.valeur();
  le_domaine=le_pb.domaine();
//
// Creation d'alias pour certains champs
//
  Noms liste_noms;
  const Probleme_base& Pb = probleme();
  Pb.get_noms_champs_postraitables(liste_noms);
// On ajoute temperature_physique aux champs definis
  if ( liste_noms.rang("temperature")!=-1 && !comprend_champ_post("temperature_physique") )
    {
      Motcle disc(probleme().discretisation().que_suis_je());
      if ((disc=="VEF")||(disc=="VEFPreP1b"))
        {
          Nom in("{ temperature_physique ");
          in+="Tparoi_VEF { source  refChamp { Pb_champ ";
          in+=probleme().le_nom();
          in+=" temperature } } }";
          Cerr<<" Building of temperature_physique  "<<in<<finl;
          EChaine IN(in);
          lire_champs_operateurs(IN);
        }
    }
  Postraitement_base::readOn(s);
  if (Motcle(format)=="MED") format="med";
  if (Motcle(format)=="MEDFILE") format="medfile";
  if (Motcle(format)=="MED_MAJOR") format="med_major";
  if ((Motcle(format)!="LML")
      && (Motcle(format)!="MESHTV")
      && (Motcle(format)!="MED")
      && (Motcle(format)!="MEDFILE")
      && (Motcle(format)!="MED_MAJOR")
      && (Motcle(format)!="LATA")
      && (Motcle(format)!="LATA_V1")
      && (Motcle(format)!="LATA_V2")
      && (Motcle(format)!="XYZ"))
    {
      Cerr<<"The postprocessing format " << format << " is not recognized"<<finl;
      Cerr<<"The recognized formats are lml, meshtv, med, medfile, med_major, xyz, lata, lata_V1 and lata_V2"<<finl;
      exit();
    }
// Changement pour la 1.6.4, le format LATA par defaut est LATA_V2
  if (Motcle(format)=="LATA") format="lata_V2";
  if (Motcle(format)=="LATA_V1") format="lata";
  nom_fich_+=".";
  nom_fich_+=format;
// Les sondes sont completees (en effet, si les sondes
// ont des champs statistiques, on n'a besoin d'avoir
// lu le bloc statistiques ET le bloc sondes)
  les_sondes_.completer();
// On type l objet Format_Post
  Nom type_format = "Format_Post_";
  type_format += format;
  if (Motcle(format)=="LATA")
    type_format +="_V1";
  format_post.typer_direct(type_format);
  Nom base_name(nom_fich_);
  base_name.prefix(format);
  base_name.prefix(".");
// format_post->initialize_by_default(base_name);
  format_post->initialize(base_name,binaire,option_para);
// Le test de verification a ete simplifie entre la v1.5.1 et la v1.5.2
// On simplifie donc la methode test_coherence
  format_post->test_coherence(champs_demande_,stat_demande_,dt_post_ch_,dt_post_stat_);
  return s;
}
References binaire, Cerr, champs_demande_, Sondes::completer(), comprend_champ_post(), Probleme_base::domaine(), dt_post_ch_, dt_post_stat_, Process::exit(), finl, format, format_post, Probleme_base::get_noms_champs_postraitables(), le_domaine, Postraitement_base::le_nom(), Probleme_base::le_nom(), les_sondes_, lire_champs_operateurs(), Postraitement_base::mon_probleme, nom_fich_, O_U_Ptr::non_nul(), option_para, Nom::prefix(), probleme(), Objet_U::que_suis_je(), Noms::rang(), Postraitement_base::readOn(), stat_demande_, Format_Post::typer_direct(), and Ref_Probleme_base::valeur().
reprendre()
int Postraitement::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
< tinit=>temps_derniere_mise_a_jour_stats : on fait la reprise
< lecture pour sauter le bloc
Reimplemented from Objet_U.
Definition at line 632 of file Postraitement.cpp.
{
// Nouvelle formulation
//
  Cerr << "Postraitement::reprendre() " << finl;
  if ((stat_demande_) || (stat_demande_definition_champs_))
    {
      Schema_Temps_base& sch = mon_probleme->schema_temps();
      double temps_courant = sch.temps_courant();
      double tinit = probleme().schema_temps().temps_courant();
      if (temps_courant>tstat_deb_)
        {
          if (nb_champs_stat_!=0)
            {
              Nom bidon;
              is >> bidon;
              if (bidon=="fin")
                {
// Ce test evite un beau segmentation fault a la lecture
// du deuxieme bidon lors d'une sauvegarde/reprise au format binaire
                  Cerr << "End of the resumption file reached...." << finl;
                  Cerr << "This file contains no statistics." << finl;
                  Cerr << "The tinit time of resumption (= " << tinit << " ) must be less" << finl;
                  Cerr << "than the beginning time, t_deb (= " << tstat_deb_ << " ), of statistics calculation." << finl;
                  exit();
                }
              is >> bidon;
              int n;
              is >> n;
              double tstat_deb_sauv,temps_derniere_mise_a_jour_stats;
              is >> tstat_deb_sauv;
              is >> temps_derniere_mise_a_jour_stats;
// Plusieurs cas possibles:
              if (inf_strict(tinit,temps_derniere_mise_a_jour_stats,1.e-5))
                {
                  Cerr << "The initial time " << tinit << " of the resumed calculation is less" << finl;
                  Cerr << "than the time of the last update of statistics " << temps_derniere_mise_a_jour_stats << finl;
                  Cerr << "We do not know how to treat this case." << finl;
                  exit();
                }
              else if ((!est_egal(tstat_deb_sauv,tstat_deb_)) && (!lserie_))
                {
// t_deb est modifie : on refait une statistique sans reprendre dans certains cas
                  if (inf_strict(tstat_deb_,tinit,1.e-5))
                    {
                      Cerr << "You have changed t_deb (old= " << tstat_deb_sauv << " new= " << tstat_deb_ << " ) to make a new statistical computing without resumption" << finl;
                      Cerr << "but t_deb (= " << tstat_deb_ << " ) is less than tinit (= "<< tinit << " ) : this is not possible." << finl;
                      exit();
                    }
                  Cerr << "We do not resume the statistics and thus the statistics calculation" << finl;
                  Cerr << "will restart at t_deb=" << tstat_deb_ << finl;
                  LIST_CURSEUR(Champ_Generique) curseur = champs_post_complet_;
                  while(curseur)
                    {
                      if (sub_type(Champ_Gen_de_Champs_Gen,curseur.valeur().valeur()))
{
                          const Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,curseur.valeur().valeur());
                          champ_post.lire_bidon(is);
                        }
                      ++curseur;
                    }
                }
              else //!< tinit=>temps_derniere_mise_a_jour_stats : on fait la reprise
                {
                  champs_post_complet_.reprendre(is);
// On modifie l'attribut tstat_deb_ et l'attribut t_debut_ des champs
// pour tenir compte de la reprise
                  tstat_deb_ = tstat_deb_sauv;
                  LIST_CURSEUR(Champ_Generique) curseur = champs_post_complet_;
                  while(curseur)
                    {
                      if (sub_type(Champ_Gen_de_Champs_Gen,curseur.valeur().valeur()))
{
                          Champ_Gen_de_Champs_Gen& champ_post = ref_cast(Champ_Gen_de_Champs_Gen,curseur.valeur().valeur());
                          champ_post.fixer_tstat_deb(tstat_deb_,temps_derniere_mise_a_jour_stats);
                        }
                      ++curseur;
                    }
                }
            }
          else  //!< lecture pour sauter le bloc
            {
              Motcle tmp;
              is >> tmp >> tmp;
              int n;
              is >> n;
              double tstat_deb_sauv,temps_derniere_mise_a_jour_stats;
              is >> tstat_deb_sauv;
              is >> temps_derniere_mise_a_jour_stats;
              Nom bidon;
              double dbidon;
              DoubleTab tab_bidon;
              for (int i=0; i<n; i++)
                {
                  is >> bidon >> bidon;
                  is >> dbidon;
                  tab_bidon.jump(is);
                }
            }
        }
    }
  return 1;
//
}
References Cerr, champs_post_complet_, est_egal(), Process::exit(), finl, Champ_Gen_de_Champs_Gen::fixer_tstat_deb(), inf_strict(), TRUSTTab< _TYPE_ >::jump(), Champ_Gen_de_Champs_Gen::lire_bidon(), LIST_CURSEUR, lserie_, Postraitement_base::mon_probleme, nb_champs_stat_, probleme(), ref_cast, Liste_Champ_Generique::reprendre(), Probleme_base::schema_temps(), stat_demande_, stat_demande_definition_champs_, sub_type, Schema_Temps_base::temps_courant(), and tstat_deb_.
sauvegarder()
int Postraitement::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
Returns
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 593 of file Postraitement.cpp.
{
  int bytes = 0;
  if ((stat_demande_) || (stat_demande_definition_champs_))
    {
      const Schema_Temps_base& sch = mon_probleme->schema_temps();
      double temps_courant = sch.temps_courant();
// le test est necessaire pour avoir une ecriture lecture symetrique
      if (temps_courant>tstat_deb_)
        {
// en mode ecriture special seul le maitre ecrit l'entete
          int a_faire,special;
          EcritureLectureSpecial::is_ecriture_special(special,a_faire);
          if (a_faire)
            {
// On veut retrouver le nom precedent pour relecture des statistiques (format xyz)
              Nom mon_ident("Operateurs_Statistique_tps");
              mon_ident += probleme().domaine().le_nom();
              double temps = probleme().schema_temps().temps_courant();
              mon_ident += Nom(temps,"%e");
              os << mon_ident << finl;
// On veut retrouver le nom precedent pour relecture des statistiques (format xyz)
              os << "Operateurs_Statistique_tps" << finl;
              os << nb_champs_stat_ << finl;
              os << tstat_deb_ << finl;
              os << tstat_dernier_calcul_ << finl ;
            }
          bytes += champs_post_complet_.sauvegarder(os);
          if (a_faire) os.flush();
        }
    }
  return bytes;
//
}
References champs_post_complet_, Probleme_base::domaine(), finl, Sortie::flush(), EcritureLectureSpecial::is_ecriture_special(), Domaine::le_nom(), Postraitement_base::mon_probleme, nb_champs_stat_, probleme(), Liste_Champ_Generique::sauvegarder(), Probleme_base::schema_temps(), stat_demande_, stat_demande_definition_champs_, Schema_Temps_base::temps_courant(), tstat_deb_, and tstat_dernier_calcul_.
self_cast() [1/2]
const Postraitement & Postraitement::self_cast (const Objet_U & r) static
Definition at line 33 of file Postraitement.cpp.
self_cast() [2/2]
Postraitement & Postraitement::self_cast (Objet_U & r) static
Definition at line 33 of file Postraitement.cpp.
set_expression_champ()
Nom Postraitement::set_expression_champ (const Motcle & motlu1, const Motcle & motlu2, const Motcle & motlu3, const Motcle & motlu4, const int trouve)
Definition at line 1650 of file Postraitement.cpp.
{
  Nom ajout("");
  if (((motlu2!="natif") && (motlu2!="faces") && (motlu3==""))
      || ((motlu2!="natif") && (motlu3!="")) )
    {
      ajout = "Interpolation { localisation ";
      ajout += motlu2;
      if (motlu3=="Moyenne")
        ajout += " source Moyenne { ";
      else if (motlu3=="Ecart_type")
        ajout += " source Ecart_Type { ";
      else if (motlu3=="Correlation")
        ajout += " source Correlation { ";
      if (trouve==1)
        {
          ajout += " sources_reference { ";
          ajout += motlu1;
          ajout += " } }";
        }
      else
        {
          if (motlu3!="Correlation")
            ajout += " source ";
          else
            ajout += " sources { ";
          ajout += " refChamp { Pb_champ ";
          ajout += probleme().le_nom();
          ajout += " ";
          ajout += motlu1;
          ajout += " } ";
          if (motlu3!="Correlation")
            ajout += " } ";
          else
            {
              ajout += " , ";
              ajout += " refChamp { Pb_champ ";
              ajout += probleme().le_nom();
              ajout += " ";
              ajout += motlu4;
              ajout += " } ";
              ajout += " } } ";
            }
          if ((motlu3=="Moyenne") || (motlu3=="Ecart_type") || (motlu3=="Correlation"))
            ajout += " } ";
        }
    }
  else
    {
      if(!trouve)
        {
          ajout += " refChamp { Pb_champ ";
          ajout += probleme().le_nom();
          ajout += " ";
          ajout += motlu1;
          ajout += " }";
        }
    }
  return ajout;
}
References Probleme_base::le_nom(), and probleme().
Referenced by creer_champ_post(), and creer_champ_post_stat().
set_param()
void Postraitement::set_param (Param & param) override virtual
< XD_ADD_P chaine Name of file.
< XD_ADD_P chaine(into=["lml","lata","lata_v1","lata_v2","med","med_major"]) This optional parameter specifies the format of the output file. The basename used for the output file is the basename of the data file. For the fmt parameter, choices are lml or lata. A short description of each format can be found below. The default value is lml.
< XD_ADD_P chaine This optional parameter specifies the domain on which the data should be interpolated before it is written in the output file. The default is to write the data on the domain of the current problem (no interpolation).
< XD_ADD_P chaine(into=["simple","multiple","mpi-io"]) Select simple (single file, sequential write), multiple (several files, parallel write), or mpi-io (single file, parallel write) for LATA format
< XD_ADD_P definition_champs Keyword to create new or more complex field for advanced postprocessing.
< XD_ADD_P Definition_champs_fichier Definition_champs read from file.
< XD_ADD_P sondes Probe.
< XD_ADD_P sondes_fichier Probe read in a file.
< XD_ADD_P entier Flag to not remove duplicated probes in .son files (1: keep duplicate probes, 0: remove duplicate probes)
< XD_ADD_P champs_posts Field\'s write mode.
< XD_ADD_P stats_posts Statistics between two points fixed : start of integration time and end of integration time.
< XD_ADD_P stats_serie_posts Statistics between two points not fixed : on period of integration.
Implements Postraitement_base.
Definition at line 356 of file Postraitement.cpp.
{
// XD postraitement postraitement_base postraitement -1 An object of post-processing (without name).
// attr interfaces champs_posts interfaces 1 Keyword to read all the caracteristics of the interfaces. Different kind of interfaces exist as well as different interface intitialisations.
  param.ajouter("Fichier",&nom_fich_); //!< XD_ADD_P chaine Name of file.
  param.ajouter("Format",&format); //!< XD_ADD_P chaine(into=["lml","lata","lata_v1","lata_v2","med","med_major"]) This optional parameter specifies the format of the output file. The basename used for the output file is the basename of the data file. For the fmt parameter, choices are lml or lata. A short description of each format can be found below. The default value is lml.
  param.ajouter_non_std("Domaine",(this)); //!< XD_ADD_P chaine This optional parameter specifies the domain on which the data should be interpolated before it is written in the output file. The default is to write the data on the domain of the current problem (no interpolation).
  param.ajouter("Parallele",&option_para); //!< XD_ADD_P chaine(into=["simple","multiple","mpi-io"]) Select simple (single file, sequential write), multiple (several files, parallel write), or mpi-io (single file, parallel write) for LATA format
  param.ajouter_non_std("Definition_champs",(this));//!< XD_ADD_P definition_champs  Keyword to create new or more complex field for advanced postprocessing.
  param.ajouter_non_std("Definition_champs_fichier|Definition_champs_file",(this));//!< XD_ADD_P Definition_champs_fichier  Definition_champs read from file.
  param.ajouter_non_std("Sondes|Probes",(this)); //!< XD_ADD_P sondes Probe.
  param.ajouter_non_std("Sondes_fichier|Probes_file",(this)); //!< XD_ADD_P sondes_fichier Probe read in a file.
  param.ajouter("DeprecatedKeepDuplicatedProbes",&DeprecatedKeepDuplicatedProbes); //!< XD_ADD_P entier Flag to not remove duplicated probes in .son files (1: keep duplicate probes, 0: remove duplicate probes)
  param.ajouter_non_std("champs|fields",(this)); //!< XD_ADD_P champs_posts Field\'s write mode.
  param.ajouter_non_std("Statistiques",(this));  //!< XD_ADD_P stats_posts Statistics between two points fixed : start of integration time and end of integration time.
  param.ajouter_non_std("Sondes_Int",(this));
  param.ajouter_non_std("Tableaux_Int",(this));
  param.ajouter_non_std("Statistiques_en_serie",(this));//!< XD_ADD_P stats_serie_posts Statistics between two points not fixed : on period of integration.
}
References Param::ajouter(), Param::ajouter_non_std(), DeprecatedKeepDuplicatedProbes, format, nom_fich_, and option_para.
sondes_demande()
int Postraitement::sondes_demande () inline
Definition at line 140 of file Postraitement.h.
{ return sondes_demande_; }
References sondes_demande_.
stat_demande()
int Postraitement::stat_demande () const inline
Definition at line 142 of file Postraitement.h.
{ return stat_demande_; }
References stat_demande_.
stat_demande_definition_champs()
int Postraitement::stat_demande_definition_champs () const inline
Definition at line 143 of file Postraitement.h.
{ return stat_demande_definition_champs_; }
References stat_demande_definition_champs_.
tableaux_demande()
int Postraitement::tableaux_demande () inline
Definition at line 144 of file Postraitement.h.
{ return tableaux_demande_; }
References tableaux_demande_.
taille_memoire()
unsigned Postraitement::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 33 of file Postraitement.cpp.
traiter_champs()
int Postraitement::traiter_champs ()
Effectue le postraitement des Champs si cela est necessaire.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 1499 of file Postraitement.cpp.
{
  Schema_Temps_base& sch = mon_probleme->schema_temps();
  double temps_courant = sch.temps_courant();
  int nb_pas_dt = sch.nb_pas_dt();
  int ind_pas_dt_post = ind_post(nb_pas_dt);
  if (lpost_champ(temps_courant) || lpost_stat(temps_courant) || ind_pas_dt_post)
    {
      postraiter_champs();
      if (!ind_pas_dt_post)
        {
          fdt_post.setVar("t",temps_courant);
          dt_post_ch_ = fdt_post.eval();
          dt_post_stat_ = dt_post_ch_;
        }
    }
  return 1;
}
References dt_post_ch_, dt_post_stat_, Parser_U::eval(), fdt_post, ind_post(), lpost_champ(), lpost_stat(), Postraitement_base::mon_probleme, Schema_Temps_base::nb_pas_dt(), postraiter_champs(), Probleme_base::schema_temps(), Parser_U::setVar(), and Schema_Temps_base::temps_courant().
Referenced by postraiter().
traiter_sondes()
int Postraitement::traiter_sondes ()
Mets a jour (en temps) le sondes.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Definition at line 1566 of file Postraitement.cpp.
{
  double temps=mon_probleme->schema_temps().temps_courant();
  double tinit=temps-mon_probleme->schema_temps().temps_calcul();
  les_sondes_.mettre_a_jour(temps,tinit);
  return 1;
}
References les_sondes_, Sondes::mettre_a_jour(), Postraitement_base::mon_probleme, Probleme_base::schema_temps(), Schema_Temps_base::temps_calcul(), and Schema_Temps_base::temps_courant().
Referenced by postraiter().
traiter_tableaux()
int Postraitement::traiter_tableaux ()
Definition at line 1520 of file Postraitement.cpp.
{
  Schema_Temps_base& sch = probleme().schema_temps();
  double temps_courant = sch.temps_courant();
  if ( lpost_tab(temps_courant) )
    postraiter_tableaux();
  return 1;
}
References lpost_tab(), postraiter_tableaux(), probleme(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by postraiter().
tstat_deb()
const double & Postraitement::tstat_deb () const inline
Definition at line 284 of file Postraitement.h.
{ return tstat_deb_; }
References tstat_deb_.
Referenced by Probleme_base::verifie_tdeb_tfin().
tstat_fin()
const double & Postraitement::tstat_fin () const inline
Definition at line 285 of file Postraitement.h.
{ return tstat_fin_; }
References tstat_fin_.
Referenced by Probleme_base::verifie_tdeb_tfin().
verifie_nom_et_sources()
void Postraitement::verifie_nom_et_sources (const Champ_Generique & champ)
Definition at line 2265 of file Postraitement.cpp.
{
  Noms liste_noms;
  const Probleme_base& Pb = probleme();
  Pb.get_noms_champs_postraitables(liste_noms);
  Motcles mots_compare(liste_noms.size());
  for (int i=0; i<liste_noms.size(); i++)
    mots_compare[i] = liste_noms[i];
  const Noms nom = champ->get_property("nom");
  const Motcle& nom_champ = nom[0];
  if (mots_compare.contient_(nom_champ))
    {
      Cerr<<"The name "<<nom_champ<<" of a post-processing field of the problem "<<Pb.le_nom()<<finl;
      Cerr<<"is identical to the name of one of this problem discrete fields."<<finl;
      Cerr<<"Please change the name of this post-processing field."<<finl;
      exit();
    }
  if (Pb.comprend_champ_post(nom_champ))
    {
      Cerr<<"The name "<<nom_champ<<" of a post-processing field of the problem "<<Pb.le_nom()<<finl;
      Cerr<<"is identical to the name of another post-processing field, to one of his components or one of his sources."<<finl;
      Cerr<<"Please change the name of this post-processing field."<<finl;
      exit();
    }
}
References Cerr, Probleme_base::comprend_champ_post(), Motcles::contient_(), Process::exit(), finl, Probleme_base::get_noms_champs_postraitables(), Probleme_base::le_nom(), probleme(), and vect_impl::size().
Referenced by complete_champ().
Member Data Documentation
binaire
int Postraitement::binaire private
Definition at line 233 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), Postraitement(), and readOn().
champs_demande_
int Postraitement::champs_demande_ private
Definition at line 232 of file Postraitement.h.
Referenced by besoin_postraiter_champs(), champs_demande(), lire_motcle_non_standard(), Postraitement(), and readOn().
champs_post_complet_
Liste_Champ_Generique Postraitement::champs_post_complet_ protected
Definition at line 213 of file Postraitement.h.
Referenced by champs_post_complet(), complete_champ(), comprend_champ_post(), creer_champ_post(), creer_champ_post_med(), creer_champ_post_moreqn(), creer_champ_post_stat(), get_champ_post(), mettre_a_jour(), postraiter(), reprendre(), and sauvegarder().
DeprecatedKeepDuplicatedProbes
int Postraitement::DeprecatedKeepDuplicatedProbes =0
Ancien format des sondes dans les .son qui autorise les sondes dupliquees.
Definition at line 196 of file Postraitement.h.
Referenced by Sonde::initialiser(), and set_param().
dernier_temps
double Postraitement::dernier_temps private
temps du precedent appel a postraiter()
Definition at line 235 of file Postraitement.h.
Referenced by init(), lpost(), and postraiter().
dt_integr_serie_
double Postraitement::dt_integr_serie_ protected
Definition at line 223 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), Postraitement(), and postraiter().
dt_post_ch_
double Postraitement::dt_post_ch_ protected
ecriture des champs sur fichier nom_du_cas.lml tous les dt_post
Definition at line 201 of file Postraitement.h.
Referenced by dt_post_ch(), lire_motcle_non_standard(), lpost_champ(), Postraitement(), readOn(), and traiter_champs().
dt_post_stat_
double Postraitement::dt_post_stat_ protected
ecriture des statistiques sur fichier nom_du_cas.lml tous les dt_stat
Definition at line 202 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), lpost_stat(), Postraitement(), readOn(), and traiter_champs().
dt_post_tab
double Postraitement::dt_post_tab protected
ecriture des tableaux d'entiers sur fichier nom_du_cas.lml
Definition at line 203 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), lpost_tab(), and Postraitement().
est_le_dernier_postraitement_pour_nom_fich_
int Postraitement::est_le_dernier_postraitement_pour_nom_fich_ protected
Definition at line 200 of file Postraitement.h.
Referenced by est_le_dernier_postraitement_pour_nom_fich(), finir(), and Postraitement().
est_le_premier_postraitement_pour_nom_fich_
int Postraitement::est_le_premier_postraitement_pour_nom_fich_ protected
Definition at line 200 of file Postraitement.h.
Referenced by est_le_premier_postraitement_pour_nom_fich(), init(), Postraitement(), postraiter_champs(), and postraiter_tableaux().
fdt_post
Parser_U Postraitement::fdt_post protected
Definition at line 206 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), and traiter_champs().
format
Nom Postraitement::format private
Definition at line 234 of file Postraitement.h.
Referenced by finir(), init(), Postraitement(), postraiter_tableau(), readOn(), and set_param().
format_post
Format_Post Postraitement::format_post protected
Definition at line 228 of file Postraitement.h.
Referenced by finir(), init(), postraiter_champs(), postraiter_tableau(), postraiter_tableaux(), and readOn().
formats_supportes
Motcles Postraitement::formats_supportes =Motcles(0) static private
Definition at line 236 of file Postraitement.h.
Referenced by init().
info_obj
const Type_info Postraitement::info_obj static
Definition at line 88 of file Postraitement.h.
le_domaine
Ref_Domaine Postraitement::le_domaine private
Definition at line 237 of file Postraitement.h.
Referenced by creer_champ_post(), creer_champ_post_stat(), init(), lire_motcle_non_standard(), postraiter_champs(), postraiter_tableaux(), and readOn().
les_sondes_
Sondes Postraitement::les_sondes_ protected
Sondes a traiter.
Definition at line 208 of file Postraitement.h.
Referenced by completer(), les_sondes(), lire_motcle_non_standard(), postraiter_sondes(), readOn(), and traiter_sondes().
les_sondes_int_
Sondes_Int Postraitement::les_sondes_int_ protected
Sondes pour des tableaux d'entiers.
Definition at line 209 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), and postraiter_sondes().
les_statistiques_
Operateurs_Statistique_tps Postraitement::les_statistiques_ protected
Liste d'operateurs statistiques a traiter.
Definition at line 210 of file Postraitement.h.
Referenced by les_statistiques().
lserie_
int Postraitement::lserie_ protected
Definition at line 222 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), Postraitement(), postraiter(), and reprendre().
nb_champs_stat_
int Postraitement::nb_champs_stat_ protected
Definition at line 218 of file Postraitement.h.
Referenced by complete_champ(), compteur_champ_stat(), lire_champs_stat_a_postraiter(), Postraitement(), reprendre(), and sauvegarder().
nb_pas_dt_post_
int Postraitement::nb_pas_dt_post_ protected
Definition at line 205 of file Postraitement.h.
Referenced by ind_post(), lire_motcle_non_standard(), and Postraitement().
nom_fich_
Nom Postraitement::nom_fich_ private
Definition at line 234 of file Postraitement.h.
Referenced by init(), nom_fich(), Postraitement(), readOn(), and set_param().
noms_champs_a_post_
List_Nom Postraitement::noms_champs_a_post_ protected
Definition at line 212 of file Postraitement.h.
Referenced by creer_champ_post(), creer_champ_post_med(), creer_champ_post_moreqn(), creer_champ_post_stat(), init(), lire_champs_a_postraiter(), noms_champs_a_post(), and postraiter_champs().
noms_fichiers_sondes_
List_Nom Postraitement::noms_fichiers_sondes_ = List_Nom () static private
Definition at line 231 of file Postraitement.h.
Referenced by noms_fichiers_sondes(), and ~Postraitement().
noms_tableaux_
List_Nom Postraitement::noms_tableaux_ protected
Definition at line 226 of file Postraitement.h.
Referenced by lire_tableaux_a_postraiter(), and postraiter_tableaux().
option_para
Nom Postraitement::option_para private
Definition at line 234 of file Postraitement.h.
Referenced by Postraitement(), readOn(), and set_param().
sondes_demande_
int Postraitement::sondes_demande_ private
Definition at line 232 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), Postraitement(), postraiter(), and sondes_demande().
stat_demande_
int Postraitement::stat_demande_ private
Definition at line 232 of file Postraitement.h.
Referenced by besoin_postraiter_champs(), lire_motcle_non_standard(), Postraitement(), readOn(), reprendre(), sauvegarder(), and stat_demande().
stat_demande_definition_champs_
int Postraitement::stat_demande_definition_champs_ private
Definition at line 232 of file Postraitement.h.
Referenced by besoin_postraiter_champs(), cherche_stat_dans_les_sources(), Postraitement(), reprendre(), sauvegarder(), and stat_demande_definition_champs().
tableaux_a_postraiter_
List_Ref_IntVect Postraitement::tableaux_a_postraiter_ protected
Liste de references a des tableaux a post-traiter.
Definition at line 225 of file Postraitement.h.
Referenced by lire_tableaux_a_postraiter(), and postraiter_tableaux().
tableaux_demande_
int Postraitement::tableaux_demande_ private
Definition at line 233 of file Postraitement.h.
Referenced by lire_motcle_non_standard(), Postraitement(), postraiter(), and tableaux_demande().
temps_
double Postraitement::temps_ private
Definition at line 235 of file Postraitement.h.
Referenced by Postraitement(), postraiter_champs(), and postraiter_tableaux().
tstat_deb_
double Postraitement::tstat_deb_ protected
Definition at line 219 of file Postraitement.h.
Referenced by cherche_stat_dans_les_sources(), lire_champs_stat_a_postraiter(), mettre_a_jour(), Postraitement(), postraiter(), reprendre(), sauvegarder(), and tstat_deb().
tstat_dernier_calcul_
double Postraitement::tstat_dernier_calcul_ protected
Definition at line 219 of file Postraitement.h.
Referenced by mettre_a_jour(), Postraitement(), postraiter(), and sauvegarder().
tstat_fin_
double Postraitement::tstat_fin_ protected
Definition at line 219 of file Postraitement.h.
Referenced by cherche_stat_dans_les_sources(), lire_champs_stat_a_postraiter(), mettre_a_jour(), Postraitement(), postraiter(), and tstat_fin().
zone_dis_pour_faces
Ref_Zone_dis_base Postraitement::zone_dis_pour_faces private
Definition at line 238 of file Postraitement.h.
Referenced by init(), postraiter_champs(), and postraiter_tableau().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Postraitement.h
src/Kernel/Framework/Postraitement.cpp