TRUST: Loi_Etat_GR_base Class Reference
Loi_Etat_GR_base Class Reference abstract
classe Loi_Etat_GR_base
Cette classe represente la loi d'etat base pour les gaz reels.
Elle definit un fluide dilatable dont la loi d'etat est :
rho=rho(Pth,H)
T = T(Pth,H)
#include <Loi_Etat_GR_base.h>
Public Member Functions
~Loi_Etat_GR_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_GR_base ()
void initialiser_inco_ch () override
Initialise l'enthalpie.
void calculer_lambda () override
Calcule la conductivite /Cp : equivlent a k*dT/dh
pour utiliser l'enthalpie dans l'operatur de diffusion.
void initialiser () override
Initialise la loi d'etat : calcul Pth.
void remplir_T () override
Remplit le tableau de la temperature : T=temp+273.15.
void calculer_Cp () override
Calcule le Cp avec le polynome PolyCp_.
const Nom type_fluide () const override
Renvoie le type de fluide associe.
double De_DP (double, double) const override
double De_DT (double, double) const override
double Cp_calc (double, double) const
Calcule le Cp en fonction des grandeurs physiques P, T, rho
Cp = dh/dT = de/dT - 1/rho^2*drho/dT.
double inverser_Pth (double, double) override
Calcule la pression avec la temperature et la masse volumique.
void calculer_masse_volumique () override
Recalcule la masse volumique.
virtual double calculer_temperature (double, double)=0
double calculer_H (double, double) const override=0
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
double Drho_DP (double, double) const override=0
double Drho_DT (double, double) const override=0
virtual double DT_DH (double, double) const =0
double calculer_masse_volumique (double, double) const override=0
double masse_molaire () const
Public Member Functions inherited from Loi_Etat_base
~Loi_Etat_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Loi_Etat_base ()
void assoscier_probleme (const Probleme_base &pb)
Associe le probleme a la loi d'etat.
void mettre_a_jour (double)
Met a jour la loi d'etat et le champ rho.
void calculer_nu ()
Calcule la viscosite cinematique.
Champ_Don & ch_temperature ()
const Champ_Don & ch_temperature () const
Renvoie le champ de le temperature.
virtual void associer_fluide (const Fluide_Dilatable_base &)
Associe le fluide a la loi d'etat.
virtual void preparer_calcul ()
Prepare le fluide au calcul.
virtual void abortTimeStep ()
virtual void initialiser_inco_ch ()
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
virtual void calculer_mu ()
Calcule la viscosite.
virtual void calculer_lambda ()
Calcule la conductivite.
virtual void calculer_alpha ()
Calcule la diffusivite.
virtual void calculer_mu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_GP.
virtual void calculer_nu_sur_Sc ()
Ne fait rien
Surcharge dans Loi_Etat_Melange_Binaire.
virtual void calculer_masse_volumique ()
Recalcule la masse volumique.
virtual double calculer_H (double, double) const
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
virtual double Drho_DP (double, double) const
virtual double Drho_DT (double, double) const
virtual double De_DP (double, double) const
virtual double De_DT (double, double) const
const Champ_base & get_champ (const Motcle &nom) const override
void creer_champ (const Motcle &motlu) override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Nom type_fluide () const =0
virtual void initialiser ()=0
virtual void remplir_T ()=0
virtual void calculer_Cp ()=0
virtual double calculer_masse_volumique (double, double) const =0
virtual double inverser_Pth (double, double)=0
Champs_compris & champs_compris ()
const DoubleTab & temperature () const
const DoubleTab & rho_n () const
const DoubleTab & rho_np1 () const
double Prandt () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static const Type_info * info ()
static Loi_Etat_GR_base & self_cast (Objet_U &)
static const Loi_Etat_GR_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Loi_Etat_base
static const Type_info * info ()
static Loi_Etat_base & self_cast (Objet_U &)
static const Loi_Etat_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Loi_Etat_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double MMole_
double Cp_
double R
DoubleTab tab_TempC
DoubleTab tab_Cp
Protected Attributes inherited from Loi_Etat_base
Ref_Fluide_Dilatable_base le_fluide
Ref_Probleme_base le_prob_
Champ_Don temperature_
DoubleTab tab_rho_n
DoubleTab tab_rho_np1
double Pr_
int debug
Detailed Description
classe Loi_Etat_GR_base
Cette classe represente la loi d'etat base pour les gaz reels.
Elle definit un fluide dilatable dont la loi d'etat est :
rho=rho(Pth,H)
T = T(Pth,H)
Definition at line 38 of file Loi_Etat_GR_base.h.
Constructor & Destructor Documentation
~Loi_Etat_GR_base()
Loi_Etat_GR_base::~Loi_Etat_GR_base () override
Definition at line 21 of file Loi_Etat_GR_base.cpp.
Loi_Etat_GR_base()
Loi_Etat_GR_base::Loi_Etat_GR_base ()
Definition at line 24 of file Loi_Etat_GR_base.cpp.
: MMole_(-1),Cp_(-1),R(-1) { }
Member Function Documentation
calculer_Cp()
void Loi_Etat_GR_base::calculer_Cp () override virtual
Calcule le Cp avec le polynome PolyCp_.
Implements Loi_Etat_base.
Definition at line 202 of file Loi_Etat_GR_base.cpp.
{
  double Pth = le_fluide->pression_th();
  const DoubleTab& tab_h = le_fluide->inco_chaleur().valeurs();
  for (int i=0; i<tab_Cp.size(); i++) tab_Cp(i) = Cp_calc(Pth,tab_h(i,0));
}
References Cp_calc(), Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, Fluide_Dilatable_base::pression_th(), TRUSTVect< _TYPE_ >::size(), tab_Cp, and Champ_Inc::valeurs().
Referenced by initialiser().
calculer_H()
double Loi_Etat_GR_base::calculer_H (double Pth_, double T_) const override pure virtual
Cas gaz parfait : ne fait rien
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
Reimplemented from Loi_Etat_base.
Implemented in Loi_Etat_rhoT_GR_QC.
Referenced by initialiser_inco_ch().
calculer_lambda()
void Loi_Etat_GR_base::calculer_lambda () override virtual
Calcule la conductivite /Cp : equivlent a k*dT/dh
pour utiliser l'enthalpie dans l'operatur de diffusion.
Reimplemented from Loi_Etat_base.
Definition at line 224 of file Loi_Etat_GR_base.cpp.
{
  const Champ_Don& mu = le_fluide->viscosite_dynamique();
  const DoubleTab& tab_mu = mu.valeurs();
  Champ_Don& lambda = le_fluide->conductivite();
  DoubleTab& tab_lambda = lambda.valeurs();
  int i, n=tab_lambda.size();
  if (!sub_type(Champ_Uniforme,lambda.valeur()))
    {
      if (sub_type(Champ_Uniforme,mu.valeur()))
        {
          for (i=0 ; i<n ; i++) tab_lambda(i,0) = tab_mu(0,0) * tab_Cp(i) / Pr_;
        }
      else
        {
          for (i=0 ; i<n ; i++) tab_lambda(i,0) = tab_mu(i,0) * tab_Cp(i) / Pr_;
        }
    }
}
References Milieu_base::conductivite(), Loi_Etat_base::le_fluide, Loi_Etat_base::Pr_, TRUSTVect< _TYPE_ >::size(), sub_type, tab_Cp, Deriv_Champ_Don_base::valeur(), Champ_Don::valeurs(), and Fluide_base::viscosite_dynamique().
calculer_masse_volumique() [1/2]
void Loi_Etat_GR_base::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_rhoT_GR_QC.
Definition at line 294 of file Loi_Etat_GR_base.cpp.
{
  Loi_Etat_base::calculer_masse_volumique();
}
References Loi_Etat_base::calculer_masse_volumique().
Referenced by Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), initialiser_inco_ch(), and inverser_Pth().
calculer_masse_volumique() [2/2]
double Loi_Etat_GR_base::calculer_masse_volumique (double , double) const override pure virtual
Implements Loi_Etat_base.
Implemented in Loi_Etat_rhoT_GR_QC.
calculer_temperature()
virtual double Loi_Etat_GR_base::calculer_temperature (double , double) pure virtual
Implemented in Loi_Etat_rhoT_GR_QC.
Referenced by initialiser(), and remplir_T().
Cp_calc()
double Loi_Etat_GR_base::Cp_calc (double P, double h) const
Calcule le Cp en fonction des grandeurs physiques P, T, rho
Cp = dh/dT = de/dT - 1/rho^2*drho/dT.
Definition at line 179 of file Loi_Etat_GR_base.cpp.
{
  double res;
  if (R==-1) res = 1./(DT_DH(P,h));
  else res = Cp_;
  return res;
}
References Cp_, DT_DH(), and R.
Referenced by calculer_Cp().
De_DP()
double Loi_Etat_GR_base::De_DP (double P, double T) const override virtual
Reimplemented from Loi_Etat_base.
Definition at line 245 of file Loi_Etat_GR_base.cpp.
{
  double res = 0;
  Cerr<<"Loi_Etat_GR_base::De_DP non accede normalement"<<finl;
  abort();
  return res;
}
References Process::abort(), Cerr, and finl.
De_DT()
double Loi_Etat_GR_base::De_DT (double P, double T) const override virtual
Reimplemented from Loi_Etat_base.
Definition at line 252 of file Loi_Etat_GR_base.cpp.
{
  double res = 0;
  Cerr<<"Loi_Etat_GR_base::De_DP non accede normalement"<<finl;
  abort();
  return res;
}
References Process::abort(), Cerr, and finl.
Drho_DP()
double Loi_Etat_GR_base::Drho_DP (double , double) const override pure virtual
Reimplemented from Loi_Etat_base.
Implemented in Loi_Etat_rhoT_GR_QC.
Referenced by inverser_Pth().
Drho_DT()
double Loi_Etat_GR_base::Drho_DT (double , double) const override pure virtual
Reimplemented from Loi_Etat_base.
Implemented in Loi_Etat_rhoT_GR_QC.
DT_DH()
virtual double Loi_Etat_GR_base::DT_DH (double , double) const pure virtual
Implemented in Loi_Etat_rhoT_GR_QC.
Referenced by Cp_calc().
get_info()
const Type_info * Loi_Etat_GR_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_rhoT_GR_QC.
Definition at line 21 of file Loi_Etat_GR_base.cpp.
info()
const Type_info * Loi_Etat_GR_base::info () static
Definition at line 21 of file Loi_Etat_GR_base.cpp.
initialiser()
void Loi_Etat_GR_base::initialiser () override virtual
Initialise la loi d'etat : calcul Pth.
Implements Loi_Etat_base.
Definition at line 70 of file Loi_Etat_GR_base.cpp.
{
  le_fluide->inco_chaleur()->nommer("enthalpie");
  const DoubleTab& tab_H = le_fluide->inco_chaleur().valeurs();
  const DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  int i, n = tab_H.dimension(0);
  DoubleTab& tab_T = temperature_.valeurs();
  tab_TempC.resize(n);
  double Pth = le_fluide->pression_th();
  for (i=0 ; i<n ; i++)
    {
      tab_rho_n(i) = tab_rho(i,0);
      tab_TempC(i) = calculer_temperature(Pth,tab_H(i,0));
      tab_T(i) = tab_TempC(i);
    }
  tab_Cp.ref(le_fluide->capacite_calorifique().valeurs());
  calculer_Cp();
}
References calculer_Cp(), calculer_temperature(), Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_ >::dimension(), Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, Milieu_base::masse_volumique(), Objet_U::nommer(), Fluide_Dilatable_base::pression_th(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), tab_Cp, Loi_Etat_base::tab_rho_n, tab_TempC, Loi_Etat_base::temperature_, Champ::valeurs(), Champ_Don::valeurs(), and Champ_Inc::valeurs().
initialiser_inco_ch()
void Loi_Etat_GR_base::initialiser_inco_ch () override virtual
Initialise l'enthalpie.
Reimplemented from Loi_Etat_base.
Definition at line 104 of file Loi_Etat_GR_base.cpp.
{
  /*
   * XXX XXX XXX
   * l'inconnue inco_chaleur est d'abord remplie avec la temperature initiale.
   * il faut la transfomer en enthalpie ;
   * les donnes sont la masse volumique et la temperature
   * on doit donc calculer l'enthalpie et la pression
   */
  DoubleTab& tab_TH = le_fluide->inco_chaleur().valeurs();
  double Pth = le_fluide->pression_th();
  int som,n = tab_TH.dimension(0);
  tab_rho_n.resize(n);
  tab_rho_np1.resize(n);
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  if (le_fluide->inco_chaleur()->le_nom() == "enthalpie")
    {
      for (som=0 ; som<n ; som++)
        tab_rho_np1(som) = tab_rho(som,0) = tab_rho_n(som) = calculer_masse_volumique(Pth,tab_TH(som,0));
    }
  else
    {
      for (som=0 ; som<n ; som++)
        {
          tab_TH(som,0) = calculer_H(Pth,tab_TH(som,0));
          tab_rho_np1(som) = tab_rho(som,0) = tab_rho_n(som) = calculer_masse_volumique(Pth,tab_TH(som,0));
        }
    }
  Cerr<<"FIN Loi_Etat_GR_base::initialiser_H Pth = "<<Pth<<"  H = "<<tab_TH(0,0)<<finl;
}
References calculer_H(), calculer_masse_volumique(), Cerr, TRUSTTab< _TYPE_ >::dimension(), finl, Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, O_U_Ptr::le_nom(), Milieu_base::masse_volumique(), Fluide_Dilatable_base::pression_th(), TRUSTTab< _TYPE_ >::resize(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, Champ::valeurs(), and Champ_Inc::valeurs().
inverser_Pth()
double Loi_Etat_GR_base::inverser_Pth (double H, double rho) override virtual
Calcule la pression avec la temperature et la masse volumique.
Implements Loi_Etat_base.
Definition at line 274 of file Loi_Etat_GR_base.cpp.
{
  double P = le_fluide->pression_th();
  double acc = (calculer_masse_volumique(P,H) - rho) / Drho_DP(P,H);
  int i=0;
  while (std::fabs(acc)>1e-8 && i<1000)
    {
      P = P-acc;
      acc = (calculer_masse_volumique(P,H) - rho) / Drho_DP(P,H);
      i++;
    }
  if (std::fabs(acc)>1e-8)
    {
      Cerr<<"Probleme dans l'inversion de la pression : nb_iter="<<i<<finl;
      Cerr<<" Pth="<<P<<" H="<<H<<" rho="<<rho<<finl;
      abort();
    }
  return P;
}
References Process::abort(), calculer_masse_volumique(), Cerr, Drho_DP(), finl, Loi_Etat_base::le_fluide, and Fluide_Dilatable_base::pression_th().
masse_molaire()
double Loi_Etat_GR_base::masse_molaire () const inline
Definition at line 65 of file Loi_Etat_GR_base.h.
{ return MMole_; }
References MMole_.
printOn()
Sortie & Loi_Etat_GR_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_rhoT_GR_QC.
Definition at line 26 of file Loi_Etat_GR_base.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Loi_Etat_GR_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_rhoT_GR_QC.
Definition at line 32 of file Loi_Etat_GR_base.cpp.
{
  return is;
}
remplir_T()
void Loi_Etat_GR_base::remplir_T () override virtual
Remplit le tableau de la temperature : T=temp+273.15.
Implements Loi_Etat_base.
Definition at line 151 of file Loi_Etat_GR_base.cpp.
{
  const DoubleTab& tab_H = le_fluide->inco_chaleur().valeurs();
  int i, n = tab_TempC.dimension(0);
  DoubleTab& tab_T = temperature_.valeurs();
  double Pth = le_fluide->pression_th();
  for (i=0 ; i<n ; i++)
    {
      tab_TempC(i) = calculer_temperature(Pth,tab_H(i,0));
      tab_T(i,0) = tab_TempC(i);
    }
}
References calculer_temperature(), TRUSTTab< _TYPE_ >::dimension(), Fluide_Dilatable_base::inco_chaleur(), Loi_Etat_base::le_fluide, Fluide_Dilatable_base::pression_th(), tab_TempC, Loi_Etat_base::temperature_, Champ_Don::valeurs(), and Champ_Inc::valeurs().
self_cast() [1/2]
const Loi_Etat_GR_base & Loi_Etat_GR_base::self_cast (const Objet_U & r) static
Definition at line 21 of file Loi_Etat_GR_base.cpp.
self_cast() [2/2]
Loi_Etat_GR_base & Loi_Etat_GR_base::self_cast (Objet_U & r) static
Definition at line 21 of file Loi_Etat_GR_base.cpp.
type_fluide()
const Nom Loi_Etat_GR_base::type_fluide () const override virtual
Renvoie le type de fluide associe.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Implements Loi_Etat_base.
Definition at line 51 of file Loi_Etat_GR_base.cpp.
{
  return "Gaz_Reel";
}
Member Data Documentation
Cp_
double Loi_Etat_GR_base::Cp_ protected
Definition at line 68 of file Loi_Etat_GR_base.h.
Referenced by Loi_Etat_rhoT_GR_QC::calculer_H(), Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GR_QC::calculer_temperature(), Cp_calc(), Loi_Etat_rhoT_GR_QC::Drho_DP(), Loi_Etat_rhoT_GR_QC::Drho_DT(), Loi_Etat_rhoT_GR_QC::DT_DH(), and Loi_Etat_rhoT_GR_QC::readOn().
info_obj
const Type_info Loi_Etat_GR_base::info_obj static
Definition at line 40 of file Loi_Etat_GR_base.h.
MMole_
double Loi_Etat_GR_base::MMole_ protected
Definition at line 68 of file Loi_Etat_GR_base.h.
Referenced by masse_molaire(), and Loi_Etat_rhoT_GR_QC::readOn().
R
double Loi_Etat_GR_base::R protected
Definition at line 68 of file Loi_Etat_GR_base.h.
Referenced by Loi_Etat_rhoT_GR_QC::calculer_H(), Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GR_QC::calculer_temperature(), Cp_calc(), Loi_Etat_rhoT_GR_QC::Drho_DP(), Loi_Etat_rhoT_GR_QC::Drho_DT(), Loi_Etat_rhoT_GR_QC::DT_DH(), and Loi_Etat_rhoT_GR_QC::readOn().
tab_Cp
DoubleTab Loi_Etat_GR_base::tab_Cp protected
Definition at line 69 of file Loi_Etat_GR_base.h.
Referenced by calculer_Cp(), calculer_lambda(), and initialiser().
tab_TempC
DoubleTab Loi_Etat_GR_base::tab_TempC protected
Definition at line 69 of file Loi_Etat_GR_base.h.
Referenced by initialiser(), and remplir_T().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_GR_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_GR_base.cpp