TRUST: Op_Dift_VDF_Multi_inco_var_Elem Class Reference
Op_Dift_VDF_Multi_inco_var_Elem Class Reference
#include <Op_Dift_VDF_Multi_inco_var_Elem.h>
Public Member Functions
~Op_Dift_VDF_Multi_inco_var_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Dift_VDF_Multi_inco_var_Elem ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
complete l'iterateur et l'evaluateur
void associer_diffusivite (const Champ_base &)
associe le champ de diffusivite a l'evaluateur
void associer_diffusivite_turbulente (const Champ_Fonc &)
void dimensionner (Matrice_Morse &) const
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void associer_loipar (const Turbulence_paroi_scal &)
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const
double calculer_dt_stab () const
Calcul dt_stab.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Op_Dift_VDF_Multi_inco_var_Elem & self_cast (Objet_U &)
static const
Op_Dift_VDF_Multi_inco_var_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Detailed Description
Definition at line 43 of file Op_Dift_VDF_Multi_inco_var_Elem.h.
Constructor & Destructor Documentation
Op_Dift_VDF_Multi_inco_var_Elem::~Op_Dift_VDF_Multi_inco_var_Elem ()
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
Op_Dift_VDF_Multi_inco_var_Elem::Op_Dift_VDF_Multi_inco_var_Elem ()
Definition at line 170 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
                                                                 :
  Op_Dift_VDF_base(It_VDF_Elem(Eval_Dift_VDF_Multi_inco_var_Elem)())
{
}
Member Function Documentation
void Op_Dift_VDF_Multi_inco_var_Elem::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_diffuse) [virtual]
complete l'iterateur et l'evaluateur
Implements Operateur_base.
Definition at line 48 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References Iterateur_VDF::associer(), Eval_VDF_Elem2::associer_inconnue(), Evaluateur_VDF::associer_zones(), Iterateur_VDF::evaluateur(), Op_Diff_VDF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Deriv_Champ_Inc_base::valeur().
{
  const Champ_P0_VDF& inco = ref_cast(Champ_P0_VDF,ch_diffuse.valeur());
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  iter.associer(zvdf, zclvdf, *this);
  Eval_Dift_VDF_Multi_inco_var_Elem& eval_diff_turb =
    dynamic_cast<Eval_Dift_VDF_Multi_inco_var_Elem&> (iter.evaluateur());
  eval_diff_turb.associer_zones(zvdf, zclvdf );
  eval_diff_turb.associer_inconnue(inco );
}
void Op_Dift_VDF_Multi_inco_var_Elem::associer_diffusivite (const Champ_base & ch_diff) [virtual]
associe le champ de diffusivite a l'evaluateur
Implements Operateur_Diff_base.
Definition at line 66 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References Eval_Diff_VDF_Multi_inco_var::associer(), Iterateur_VDF::evaluateur(), and Op_Diff_VDF_base::iter.
{
  Eval_Dift_VDF_Multi_inco_var_Elem& eval_diff_turb =
    dynamic_cast<Eval_Dift_VDF_Multi_inco_var_Elem&> (iter.evaluateur());
  eval_diff_turb.associer(ch_diff);
}
void Op_Dift_VDF_Multi_inco_var_Elem::associer_diffusivite_turbulente (const Champ_Fonc & diff_turb)
Reimplemented from Op_Diff_Turbulent_base.
Definition at line 80 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References Eval_Dift_VDF_Multi_inco_var::associer_diff_turb(), Iterateur_VDF::evaluateur(), and Op_Diff_VDF_base::iter.
Referenced by completer().
{
  Op_Diff_Turbulent_base::associer_diffusivite_turbulente(diff_turb);
  Evaluateur_VDF& eval = iter.evaluateur();
  Eval_Dift_VDF_Multi_inco_var_Elem& eval_diff_turb =
    dynamic_cast<Eval_Dift_VDF_Multi_inco_var_Elem&> (eval);
  eval_diff_turb.associer_diff_turb(diff_turb);
}
void Op_Dift_VDF_Multi_inco_var_Elem::associer_loipar (const Turbulence_paroi_scal & loi_paroi)
Definition at line 90 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References Eval_Turbulence::associer_loipar(), Iterateur_VDF::evaluateur(), and Op_Diff_VDF_base::iter.
Referenced by completer().
{
// loipar = loi_paroi;
  Evaluateur_VDF& eval = iter.evaluateur();
  Eval_Dift_VDF_Multi_inco_var_Elem& eval_diff_turb =
    dynamic_cast<Eval_Dift_VDF_Multi_inco_var_Elem&> (eval);
  eval_diff_turb.associer_loipar(loi_paroi);
}
double Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 110 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References Nom::debute_par(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), DoubleTab::dimension(), Objet_U::dimension, Zone_VDF::dist_face(), DMINFLOAT, Zone_VF::elem_faces(), MorEqn::equation(), Op_Diff_VDF_base::iter, max(), MorEqn::mon_equation, Process::mp_max(), Zone_dis_base::nb_elem(), Objet_U::que_suis_je(), sub_type, Ref_Equation_base::valeur(), Champ_Fonc::valeurs(), Champ_Proto::valeurs(), and Iterateur_VDF::zone().
{
  double coef = -1e10;
  const Zone_VDF& zone_VDF = iter.zone();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const DoubleTab& alpha = diffusivite_pour_pas_de_temps().valeurs();
  const DoubleVect& alpha_t = diffusivite_turbulente()->valeurs();
  bool is_concentration = (equation().que_suis_je().debute_par("Convection_Diffusion_Concentration") || equation().que_suis_je().debute_par("Convection_Diffusion_Espece"));
// Calcul du pas de temps de stabilite :
//
//
// - La diffusivite laminaire est variable
// - La diffusivite turbulente est variable
//
// dt_stab = Min (1/(2*(Max(diffu1(i),diffu2(i),....)+diff_turb(i))*coeff(elem))
//
// avec :
// diffu1(i),diffu2(i) ...: diffusivites des differents constituants
// sur l'element
// coeff =  1/(dx*dx) + 1/(dy*dy) + 1/(dz*dz)
//
// i decrivant l'ensemble des elements du maillage
//
  ArrOfInt numfa(2*dimension);
  for (int elem = 0; elem < zone_VDF.nb_elem(); elem++)
    {
      double alpha_lam = alpha(elem,0);
      for (int k = 1; k < alpha.dimension(1); k++)
        alpha_lam = max(alpha_lam, alpha(elem, k));
// choix du facteur
      double rcp = 1.;
      if (!is_concentration)
        {
          const int Ccp = sub_type(Champ_Uniforme, mon_equation->milieu().capacite_calorifique().valeur());
          const int Cr = sub_type(Champ_Uniforme, mon_equation->milieu().masse_volumique());
          const DoubleTab& tab_Cp = mon_equation->milieu().capacite_calorifique().valeurs(), tab_r = mon_equation->milieu().masse_volumique().valeurs();
          rcp = tab_r(Cr ? 0 : elem, 0) * tab_Cp(Ccp ? 0 : elem, 0);
        }
      double moy = 0.;
      for (int i = 0; i < 2 * dimension; i++) numfa[i] = elem_faces(elem, i);
      for (int d = 0; d < dimension; d++) moy += 1. / (zone_VDF.dist_face(numfa[d], numfa[dimension + d], d));
      const double alpha_local = (alpha_lam + alpha_t(elem)) / rcp * moy;
      coef = max(coef, alpha_local);
    }
  coef = Process::mp_max(coef);
  double dt_stab = 1. / (2. * (coef + DMINFLOAT));
  return dt_stab;
}
void Op_Dift_VDF_Multi_inco_var_Elem::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_VDF_base.
Definition at line 99 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References associer_diffusivite_turbulente(), associer_loipar(), Modele_turbulence_scal_base::conductivite_turbulente(), MorEqn::equation(), Equation_base::get_modele(), Modele_turbulence_scal_base::loi_paroi(), ref_cast, TURBULENCE, and Ref_Objet_U::valeur().
{
  Op_Dift_VDF_base::completer();
  const RefObjU& modele_turbulence = equation().get_modele(TURBULENCE);
  const Modele_turbulence_scal_base& mod_turb = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
  const Champ_Fonc& lambda_t = mod_turb.conductivite_turbulente();
  associer_diffusivite_turbulente(lambda_t);
  const Turbulence_paroi_scal& loipar = mod_turb.loi_paroi();
  associer_loipar(loipar);
}
Objet_U * Op_Dift_VDF_Multi_inco_var_Elem::cree_instance () [static]
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
const Champ_base & Op_Dift_VDF_Multi_inco_var_Elem::diffusivite () const [virtual]
Implements Operateur_Diff_base.
Definition at line 73 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
References Iterateur_VDF::evaluateur(), Eval_Diff_VDF_Multi_inco_var::get_diffusivite(), and Op_Diff_VDF_base::iter.
{
  const Eval_Dift_VDF_Multi_inco_var_Elem& eval_diff_turb =
    dynamic_cast<const Eval_Dift_VDF_Multi_inco_var_Elem&> (iter.evaluateur());
  return eval_diff_turb.get_diffusivite();
}
void Op_Dift_VDF_Multi_inco_var_Elem::dimensionner (Matrice_Morse & matrice) const [inline, virtual]
on dimensionne notre matrice.
Reimplemented from Operateur_base.
Definition at line 64 of file Op_Dift_VDF_Multi_inco_var_Elem.h.
References Op_Diff_VDF_base::iter, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  Op_VDF_Elem::dimensionner(iter.zone(), iter.zone_Cl(), matrice);
}
int Op_Dift_VDF_Multi_inco_var_Elem::duplique () const [virtual]
Implements Op_Dift_VDF_base.
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
const Type_info * Op_Dift_VDF_Multi_inco_var_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
const Type_info * Op_Dift_VDF_Multi_inco_var_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
void Op_Dift_VDF_Multi_inco_var_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 69 of file Op_Dift_VDF_Multi_inco_var_Elem.h.
References Op_Diff_VDF_base::iter, Iterateur_VDF::zone(), and Iterateur_VDF::zone_Cl().
{
  Op_VDF_Elem::modifier_pour_Cl(iter.zone(), iter.zone_Cl(), matrice, secmem);
}
Sortie & Op_Dift_VDF_Multi_inco_var_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Definition at line 30 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
{
  return s << que_suis_je() ;
}
Entree & Op_Dift_VDF_Multi_inco_var_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Definition at line 35 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
{
  return s ;
}
const Op_Dift_VDF_Multi_inco_var_Elem & Op_Dift_VDF_Multi_inco_var_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Dift_VDF_base.
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
Op_Dift_VDF_Multi_inco_var_Elem & Op_Dift_VDF_Multi_inco_var_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Op_Dift_VDF_base.
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
unsigned Op_Dift_VDF_Multi_inco_var_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Op_Dift_VDF_Multi_inco_var_Elem.cpp.
Member Data Documentation
const Type_info Op_Dift_VDF_Multi_inco_var_Elem::info_obj [static]
Reimplemented from Op_Dift_VDF_base.
Definition at line 46 of file Op_Dift_VDF_Multi_inco_var_Elem.h.
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_Multi_inco_var_Elem.h
src/VDF/Operateurs/Operateurs_Diff/Op_Dift_VDF_Multi_inco_var_Elem.cpp