TRUST: Terme_Source_Canal_perio Class Reference
Terme_Source_Canal_perio Class Reference abstract
Source term to keep a constant flow rate in a channel with periodic boundary conditions.
#include <Terme_Source_Canal_perio.h>
Public Member Functions
Terme_Source_Canal_perio ()
~Terme_Source_Canal_perio () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
DoubleTab & calculer (DoubleTab &resu) const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Terme_Source_Canal_perio & self_cast (Objet_U &)
static const Terme_Source_Canal_perio & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Entree & lire_donnees (Entree &)
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void calculer_debit (double &) const =0
ArrOfDouble source () const
Term source calculation (called by VDF and VEF implementations)
TODO: returning an ArrOfDouble is baaad.
void write_flow_rate (const Nom &ext_nom_source, double debit) const
double compute_heat_flux () const
virtual ArrOfDouble source_convection_diffusion (double debit_e) const
Protected Member Functions inherited from Source_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ArrOfDouble dir_source_
int direction_ecoulement_
int velocity_weighting_
Nom bord_periodique_
double surface_bord_
double h
double coeff
double u_etoile
int deb_
double source_
double debnm1_
double debit_ref_
double dernier_temps_calc_
int is_debit_impose_
double debit_impose_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Attributes
SFichier flow_rate_file_
SFichier pressure_gradient_file_
SFichier restart_file_
Detailed Description
Source term to keep a constant flow rate in a channel with periodic boundary conditions.
Definition at line 28 of file Terme_Source_Canal_perio.h.
Constructor & Destructor Documentation
Terme_Source_Canal_perio()
Terme_Source_Canal_perio::Terme_Source_Canal_perio ()
Definition at line 34 of file Terme_Source_Canal_perio.cpp.
                                                  :
  direction_ecoulement_(-1),
  velocity_weighting_(0),
  bord_periodique_(""),
  surface_bord_(0.0),
  h(0.0), coeff(0.0), u_etoile(0.0),
  deb_(0.0),
  source_(0.0),
  debnm1_(0.0),
  debit_ref_(0.0),
  dernier_temps_calc_(-1.0),  //!< why??
  is_debit_impose_(0),
  debit_impose_(0.0)
{
}
~Terme_Source_Canal_perio()
Terme_Source_Canal_perio::~Terme_Source_Canal_perio () override
Definition at line 50 of file Terme_Source_Canal_perio.cpp.
{}
Member Function Documentation
associer_pb()
void Terme_Source_Canal_perio::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 67 of file Terme_Source_Canal_perio.cpp.
{}
calculer()
DoubleTab & Terme_Source_Canal_perio::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 531 of file Terme_Source_Canal_perio.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References Source_base::ajouter().
calculer_debit()
virtual void Terme_Source_Canal_perio::calculer_debit (double &) const protected pure virtual
Implemented in Terme_Source_Canal_perio_VDF_Face, and Terme_Source_Canal_perio_VEF_P1NC.
Referenced by source().
completer()
void Terme_Source_Canal_perio::completer (void) override protected virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
< Le bord periodique est specifie
Reimplemented from Source_base.
Definition at line 169 of file Terme_Source_Canal_perio.cpp.
{
  Source_base::completer();
  if (sub_type(Convection_Diffusion_std,equation()))
    {
      set_fichier("Canal_perio");
      set_description("Energy source term = Integral(P*dv) [W]");
    }
  int nb_bords = equation().zone_dis().valeur().nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = equation().zone_Cl_dis().valeur().les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          if ( bord_periodique_ == le_bord.le_nom() ) //!< Le bord periodique est specifie
            {
              if (perio.est_periodique_selon_un_axe())
                {
// Cas ou le bord est periodique selon un axe, alors on fixe la direction de l'ecoulement (VDF)
                  direction_ecoulement_ = perio.direction_periodicite();
                }
              else
                {
// Cas general ou le bord periodique n'est pas oriente selon un axe:
                  dir_source_ = perio.direction_perio();
                  dir_source_ *= -1;
// On adimensionnalise:
                  double norme = norme_array(dir_source_);
                  dir_source_ /= norme;
                }
// On recupere la surface
              surface_bord_ = 0.5 * le_bord.frontiere().get_aire();
              return;
            }
        }
    }
  Cerr << "********************************************************" << finl;
  Cerr << "Error for the definition of the Canal_perio source term." << finl;
  if (bord_periodique_=="")
    {
      Cerr << "It seems the channel is not parallel to an axis. Direction_ecoulement keyword is useless in this case." << finl;
      Cerr << "So try to use the following syntax to specify the name of the periodic boundary:" << finl;
      Cerr << "Canal_perio { bord name }" << finl;
    }
  else
    {
      Cerr << bord_periodique_ << " is not a boundary with a periodic boundary condition." << finl;
    }
  exit();
}
References bord_periodique_, Cerr, Source_base::completer(), dir_source_, direction_ecoulement_, Periodique::direction_perio(), Periodique::direction_periodicite(), MorEqn::equation(), Periodique::est_periodique_selon_un_axe(), Process::exit(), finl, Frontiere_dis_base::frontiere(), Cond_lim::frontiere_dis(), Frontiere::get_aire(), Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_front_Cl(), norme(), norme_array(), ref_cast, Source_base::set_description(), Source_base::set_fichier(), sub_type, surface_bord_, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
compute_heat_flux()
double Terme_Source_Canal_perio::compute_heat_flux () const protected
< Diffusion operator
< Check
Definition at line 315 of file Terme_Source_Canal_perio.cpp.
{
// On recupere flux_bords operateur de diffusion
  const Operateur_base& op_base = equation().operateur(0).l_op_base(); //!< Diffusion operator
  assert(sub_type(Operateur_Diff_base,op_base)); //!< Check
  const DoubleTab& flux_bords = op_base.flux_bords();
// If flux_bords is not build (diffusion_implicit algorithm for example, we calculate it):
  if (flux_bords.size()==0)
    {
      DoubleTab dummy(equation().inconnue().valeurs());
      equation().operateur(0).ajouter(equation().inconnue(), dummy);
    }
// Loop on boundaries to evaluate total heat flux:
  double heat_flux=0;
  int nb_bords = equation().zone_dis().valeur().nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = equation().zone_Cl_dis().valeur().les_conditions_limites(n_bord);
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
// Loop on boundary faces with imposed flux condition (Neumann)
          const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = frontiere_dis.num_premiere_face();
          int nfin = ndeb + frontiere_dis.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            heat_flux += flux_bords(num_face,0);
        }
    }
  heat_flux=mp_sum(heat_flux);
  return heat_flux;
}
References Operateur::ajouter(), MorEqn::equation(), Operateur_base::flux_bords(), Cond_lim::frontiere_dis(), Operateur::l_op_base(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::operateur(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by source_convection_diffusion(), and Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion().
get_info()
const Type_info * Terme_Source_Canal_perio::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_perio_VEF_P1NC, and Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 31 of file Terme_Source_Canal_perio.cpp.
info()
const Type_info * Terme_Source_Canal_perio::info () static
Definition at line 31 of file Terme_Source_Canal_perio.cpp.
lire_donnees()
Entree & Terme_Source_Canal_perio::lire_donnees (Entree & is) protected
< Obsolete
< Energy source term algorithm 0 | 1
Definition at line 70 of file Terme_Source_Canal_perio.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcle motlu;
// Valeurs par defaut
  u_etoile = 0.;
  h = 1.;
  coeff = 10.;
  velocity_weighting_ = 0;
// FIN valeurs par defaut
  int verif = 0;
  Motcles les_mots(7);
  Motcle mot_lu;
  {
    les_mots[0]="direction_ecoulement"; //!< Obsolete
    les_mots[1]="u_etoile";
    les_mots[2]="coeff";
    les_mots[3]="h";
    les_mots[4]="bord";
    les_mots[5]="velocity_weighting"; //!< Energy source term algorithm 0 | 1
    les_mots[6]="debit_impose";
  }
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  is >> mot_lu;
  if(mot_lu != acc_ouverte)
    {
      Cerr << "We were expecting a { instead of " << mot_lu << finl;
    }
  is >> mot_lu;
  dir_source_.resize(dimension);
  dir_source_=0;
  while(mot_lu != acc_fermee)
    {
      int rang=les_mots.search(mot_lu);
      switch(rang)
        {
        case 0 :
          Cerr <<"The direction_ecoulement option is obsolete, you must now use the bord option to specify the boundary where periodicity is applied."<<finl;
          exit();
          break;
        case 1  :
          is >> u_etoile;
          Cerr << "Friction Velocity : " << u_etoile  << finl;
          Cerr<<"L'option u_etoile est obsolete, supprimer la du jeu de donnees"<<finl;
          exit();
          break;
        case 2  :
          is >> coeff;
          Cerr << "Damping Coefficient is now set : " << coeff << finl;
          break;
        case 3  :
          is >> h;
          Cerr << "Channel Half-height : " << h << finl;
          break;
        case 4  :
          is >> bord_periodique_;
          Cerr << "Periodic flow according the " << bord_periodique_ << " boundary." << finl;
          verif = 1;
          break;
        case 6  :
          is >> debit_impose_;
          is_debit_impose_=1;
          break;
        case 5  :
          is >> velocity_weighting_;
          if (velocity_weighting_!=0 && velocity_weighting_!=1)
            {
              Cerr << "velocity_weighting value should be 0 or 1." << finl;
              exit();
            }
          if (!sub_type(Convection_Diffusion_std,equation()))
            {
              Cerr << "velocity_weighting option is available only for a Canal_perio source term in the energy equation." << finl;
              exit();
            }
          break;
        default :
          {
            Cerr << mot_lu << " is not expected by Terme_Source_Canal_perio" << finl;
            Cerr << "The possible keywords are : " << les_mots << finl;
            exit();
          }
        }
      is >> mot_lu;
    }
  if (verif != 1)
    {
      Cerr << "User did not specify flow direction." << finl;
      Cerr << "trust will now stop !" << finl;
      exit();
    }
  return is;
}
References bord_periodique_, Cerr, coeff, debit_impose_, Objet_U::dimension, dir_source_, MorEqn::equation(), Process::exit(), finl, h, is_debit_impose_, TRUSTArray< _TYPE_ >::resize(), Motcles::search(), sub_type, u_etoile, and velocity_weighting_.
Referenced by readOn(), Terme_Source_Canal_perio_VDF_Face::readOn(), Terme_Source_Canal_perio_QC_VDF_Face::readOn(), Terme_Source_Canal_perio_VDF_Front_Tracking::readOn(), Terme_Source_Canal_perio_VEF_P1NC::readOn(), and Terme_Source_Canal_perio_QC_VEF_P1NC::readOn().
mettre_a_jour()
void Terme_Source_Canal_perio::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 35 of file Terme_Source_Canal_perio.h.
{}
printOn()
Sortie & Terme_Source_Canal_perio::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_perio_VEF_P1NC, and Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 53 of file Terme_Source_Canal_perio.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Canal_perio::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Canal_perio_VDF_Face, Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, Terme_Source_Canal_perio_VDF_P0, Terme_Source_Canal_perio_VEF_P1NC, and Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 62 of file Terme_Source_Canal_perio.cpp.
{
  return lire_donnees(s);
}
References lire_donnees().
self_cast() [1/2]
const Terme_Source_Canal_perio & Terme_Source_Canal_perio::self_cast (const Objet_U & r) static
Definition at line 31 of file Terme_Source_Canal_perio.cpp.
self_cast() [2/2]
Terme_Source_Canal_perio & Terme_Source_Canal_perio::self_cast (Objet_U & r) static
Definition at line 31 of file Terme_Source_Canal_perio.cpp.
source()
ArrOfDouble Terme_Source_Canal_perio::source () const protected
Term source calculation (called by VDF and VEF implementations)
TODO: returning an ArrOfDouble is baaad.
< Ecoulement selon un axe
< Cas general
Definition at line 389 of file Terme_Source_Canal_perio.cpp.
{
  double tps = equation().schema_temps().temps_courant();
  double tps_init = equation().schema_temps().temps_init();
  double dt = equation().schema_temps().pas_de_temps();
  int premiere_ecriture = (!equation().probleme().reprise_effectuee() && deb_==0 ? 1 : 0);
  Nom ext_nom_source_  = equation().probleme().le_nom();
  ext_nom_source_ +=  "_" ;
  ext_nom_source_ +=  bord_periodique_ ;
// Pourquoi ?
  if (est_different(dernier_temps_calc_,tps))
    {
// Compte flow rate:
      double debit_e= 0.;
      calculer_debit(debit_e);
      if (je_suis_maitre())
        {
          if (sub_type(Convection_Diffusion_std,equation()))
            {
// Write nothing if equation is Energy
            }
          else
            write_flow_rate(ext_nom_source_, debit_e);
        }
      if (sub_type(Convection_Diffusion_std,equation()))
        {
          if (equation().probleme().is_dilatable())
            {
              Cerr << "Source term not validated yet for Quasi Compressible formulation." << finl;
              Cerr << "Contact TRUST support." << finl;
              exit();
            }
          if(equation().schema_temps().pas_de_temps_locaux().size()>0)
            {
              Cerr << "Source term not validated yet for steady option for the Convection_Diffusion_std equation." << finl;
              Cerr << "Contact TRUST support." << finl;
              exit();
            }
          return source_convection_diffusion(debit_e);
        }
      else if (sub_type(Navier_Stokes_std,equation()))
        {
// Compute source term for Navier Stokes
// Master process sends values to all processes:
          envoyer_broadcast(debit_ref_, 0);
          envoyer_broadcast(debnm1_, 0);
          envoyer_broadcast(source_, 0);
// On conserve le test (avec dt_min) car appel a t=0 (dt=0) au cours de preparer calculer pour loi de paroi TBLE
          double dt_min = equation().schema_temps().pas_temps_min();
          const DoubleVect& dt_locaux = equation().schema_temps().pas_de_temps_locaux();
          double si = 0;
          if (sup_ou_egal(dt,dt_min))
            {
// si = [ 2*(Q(0)-Q(t(n))) - (Q(0)-Q(t(n-1))) ] / [ coeff * dt * aire(bord) ]
              if( dt_locaux.size()>0)
                {
                  Cerr << "Periodic BC plus source term not validated yet for steady option." << finl;
                  Cerr << "Contact TRUST support." << finl;
                  exit();
// du au fait que ce calcul implique une division par dt, dans le cas ou le dt est variable par face,
// calculer_debit(debit_e) renvoye [ 2*(Q(0)-Q(t(n))) - (Q(0)-Q(t(n-1))) ]/dt_locaux
                  si = debit_e/(coeff*surface_bord_);
                }
              else
                {
                  si = (2.*(debit_ref_-debit_e)-(debit_ref_-debnm1_))/(coeff*dt*surface_bord_);
                  debnm1_ = debit_e;
                }
            }
          source_ += si;
          dernier_temps_calc_ = tps;
          if (je_suis_maitre())
            {
// Write the pressure gradient file if equation is Navier Stokes
              Nom filename(nom_du_cas());
              filename+="_Pressure_Gradient_";
              filename+= ext_nom_source_ ;
              if (!pressure_gradient_file_.is_open())
                {
                  pressure_gradient_file_.ouvrir(filename, (premiere_ecriture?ios::out:ios::app));
                  pressure_gradient_file_.setf(ios::scientific);
                }
              if ((tps <= (tps_init+dt)) && premiere_ecriture)
                {
                  if (equation().probleme().is_dilatable()==1)
                    pressure_gradient_file_ << "# Time t     gradP(t)      gradP(t)-gradP(t-dt) in [kg.s-2.m-2] if SI units used" << finl;
                  else
                    pressure_gradient_file_ << "# Time t     gradP(t)      gradP(t)-gradP(t-dt) in [m.s-2] if SI units used" << finl;
                }
              pressure_gradient_file_ << tps+dt << " " << source_ << "  " << si << finl;
// Write the restart file:
              filename=nom_du_cas();
              filename+="_Channel_Flow_Rate_repr_";
              filename+=ext_nom_source_;
              if (!restart_file_.is_open())
                {
                  restart_file_.ouvrir(filename, (premiere_ecriture?ios::out:ios::app));
                  restart_file_.setf(ios::scientific);
                }
              if ((tps <= (tps_init+dt)) && premiere_ecriture)
                {
                  if (equation().probleme().is_dilatable()==1)
                    restart_file_ << "# Time t       Flow rate Q(t)    Flow rate Q(0) in [kg.s-1]   gradP(t) in [kg.s-2.m-2] if SI units used" << finl;
                  else
                    restart_file_ << "# Time t       Flow rate Q(t)    Flow rate Q(0) in [m3.s-1]   gradP(t) in [m.s-2] if SI units used" << finl;
                }
              restart_file_ << tps+dt << "   " <<  debit_e << "      " << debit_ref_ << "                 " << source_ << finl;
            }
        }
      else
        {
          Cerr << "You can't use canal_perio on the equation " << equation().que_suis_je() << finl;
          exit();
        }
    }
  if (sub_type(Convection_Diffusion_std,equation()))
    {
      Cerr << "Error! Contact TRUST support." << finl;
      exit();
    }
// Essayer de virer direction_ecoulement_ (attention assert en VDF et ecarts possibles)
  ArrOfDouble s;
  s.resize(dimension);
  s = 0.;
  if (direction_ecoulement_>=0) //!< Ecoulement selon un axe
    s[direction_ecoulement_] = source_;
  else //!< Cas general
    for (int i=0; i<dimension; i++)
      s[i] = source_ * dir_source_[i];
  return s;
}
References bord_periodique_, calculer_debit(), Cerr, coeff, deb_, debit_ref_, debnm1_, dernier_temps_calc_, Objet_U::dimension, dir_source_, direction_ecoulement_, envoyer_broadcast(), MorEqn::equation(), est_different(), Process::exit(), finl, Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), Probleme_base::le_nom(), Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_de_temps_locaux(), Schema_Temps_base::pas_temps_min(), pressure_gradient_file_, Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), TRUSTArray< _TYPE_ >::resize(), restart_file_, Equation_base::schema_temps(), Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_ >::size(), source_, source_convection_diffusion(), sub_type, sup_ou_egal(), surface_bord_, Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_init(), and write_flow_rate().
Referenced by Terme_Source_Canal_perio_VEF_P1NC::ajouter(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), and Terme_Source_Canal_perio_VDF_P0::ajouter_blocs().
source_convection_diffusion()
ArrOfDouble Terme_Source_Canal_perio::source_convection_diffusion (double debit_e) const protected virtual
< It seems this algorithm do not imply dT/dt -> 0
< Ecoulement selon un axe
< Cas general
Reimplemented in Terme_Source_Canal_perio_VDF_P0.
Definition at line 347 of file Terme_Source_Canal_perio.cpp.
{
// Compute heat_flux:
  double heat_flux = compute_heat_flux();
  const Zone_VF& zone_vf = ref_cast(Zone_VF,equation().zone_dis().valeur());
  const double volume = zone_vf.zone().volume_total();
  int size = zone_vf.nb_faces();
  ArrOfDouble s(size);
  if (velocity_weighting_) //!< It seems this algorithm do not imply dT/dt -> 0
    {
// Compute source term for Energy
// Expression from TU Delft Master Thesis
// Source = -u*Sum(imposed_heat_flux)/(Volume*Ubulk)
// Ubulk=FlowRate/Area(PeriodicBoundary)
// Loop on the faces
      const DoubleTab& vitesse = ref_cast(Convection_Diffusion_std,equation()).vitesse_transportante().valeurs();
      for (int num_face=0; num_face<size; num_face++)
        {
          double velocity = 0;
          if (direction_ecoulement_>=0) //!< Ecoulement selon un axe
            velocity = vitesse(num_face,direction_ecoulement_);
          else //!< Cas general
            for (int i=0; i<dimension; i++)
              velocity += vitesse(num_face,i) * dir_source_[i];
          s[num_face]=-velocity*heat_flux/(volume*debit_e/surface_bord_);
        }
    }
  else
    {
// Compute source term with
// Source = -Sum(imposed_heat_flux)/Volume
// Loop on the faces
      for (int num_face=0; num_face<size; num_face++)
        s[num_face]=-heat_flux/volume;
    }
  return s;
}
References compute_heat_flux(), Objet_U::dimension, dir_source_, direction_ecoulement_, MorEqn::equation(), Zone_VF::nb_faces(), ref_cast, surface_bord_, valeur(), velocity_weighting_, Zone::volume_total(), and Zone_dis_base::zone().
Referenced by source().
write_flow_rate()
void Terme_Source_Canal_perio::write_flow_rate (const Nom & ext_nom_source, double debit) const protected
Definition at line 222 of file Terme_Source_Canal_perio.cpp.
{
  double tps = equation().schema_temps().temps_courant();
  double tps_init = equation().schema_temps().temps_init();
  double dt = equation().schema_temps().pas_de_temps();
  int premiere_ecriture = (!equation().probleme().reprise_effectuee() && deb_==0 ? 1 : 0);
// Write the flow rate file if equation is Navier Stokes:
  Nom filename(nom_du_cas());
  filename+="_Channel_Flow_Rate_";
  filename+=ext_nom_source_ ;
  if (!flow_rate_file_.is_open())
    {
      flow_rate_file_.ouvrir(filename, (premiere_ecriture?ios::out:ios::app));
      flow_rate_file_.setf(ios::scientific);
    }
// on met des commentaires dans l'entete du fichier
  if ((tps <= (tps_init+dt)) && premiere_ecriture)
    {
      if (equation().probleme().is_dilatable()==1)
        flow_rate_file_ << "# Time t     Flow rate Q(t) in [kg.s-1] if SI units used" << finl;
      else
        flow_rate_file_ << "# Time t     Flow rate Q(t) in [m3.s-1] if SI units used" << finl;
    }
  flow_rate_file_ << tps+dt << " " << debit_e << finl;
  if (deb_==0)
    {
      deb_ = 1;
      debit_ref_ = debit_e;
      if (is_debit_impose_)
        debit_ref_=debit_impose_;
      debnm1_ = debit_ref_;
      source_ = 0.;
// Deplacer dans completer ?
// Read the restart file:
      if (equation().probleme().reprise_effectuee())
        {
          Nom filename2(nom_du_cas());
          filename2+="_Channel_Flow_Rate_repr_";
          filename2+=ext_nom_source_ ;
          EFichier fichier_reprise;
          if (!fichier_reprise.ouvrir(filename2))
            {
              Cerr << "File " << filename2 << " not found !" << finl;
              Cerr << "Since the 1.6.8 version, you absolutly need this file to restart the calculation." << finl;
              Cerr << "Look for a file named *Channel_Flow_Rate_repr* and renamed it for example." << finl;
              exit();
            }
          else
            {
// Check header
              Nom str;
              fichier_reprise >> str;
              if (str=="#")
                {
// Read the whole line:
                  std::string line;
                  std::getline(fichier_reprise.get_ifstream(), line);
                }
              else
                {
// Reopen:
                  fichier_reprise.ouvrir(filename);
                }
// Read up to the time:
              int time_found = 0;
              while (!fichier_reprise.eof() && !time_found)
                {
                  double temps_ecrit;
                  fichier_reprise >> temps_ecrit;
                  fichier_reprise >> debnm1_;
                  fichier_reprise >> debit_ref_;
                  fichier_reprise >> source_;
// std::getline(fichier_reprise.get_ifstream(), line);
                  if (est_egal(temps_ecrit,tps_init,1e-5))
                    {
                      Cerr << "Source canal_perio read values in the file " << filename << " for the time t= " << temps_ecrit << finl;
                      time_found = 1;
                    }
                }
              if (time_found==0)
                {
                  Cerr << "Sorry, we didn't find the time " << tps_init << " in the file " << filename << finl;
                  Cerr << "We can't restart the calculation." << finl;
                  exit();
                }
            }
        }
    }
}
References Cerr, deb_, debit_impose_, debit_ref_, debnm1_, Entree_Fichier_base::eof(), MorEqn::equation(), est_egal(), Process::exit(), finl, flow_rate_file_, Entree_Fichier_base::get_ifstream(), is_debit_impose_, Sortie_Fichier_base::is_open(), Objet_U::nom_du_cas(), Entree_Fichier_base::ouvrir(), Sortie_Fichier_base::ouvrir(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Equation_base::schema_temps(), Sortie_Fichier_base::setf(), source_, Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_init().
Referenced by source().
Member Data Documentation
bord_periodique_
Nom Terme_Source_Canal_perio::bord_periodique_ protected
Definition at line 54 of file Terme_Source_Canal_perio.h.
Referenced by Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), completer(), lire_donnees(), and source().
coeff
double Terme_Source_Canal_perio::coeff protected
Definition at line 56 of file Terme_Source_Canal_perio.h.
Referenced by lire_donnees(), and source().
deb_
int Terme_Source_Canal_perio::deb_ mutable protected
Definition at line 58 of file Terme_Source_Canal_perio.h.
Referenced by source(), and write_flow_rate().
debit_impose_
double Terme_Source_Canal_perio::debit_impose_ protected
Definition at line 64 of file Terme_Source_Canal_perio.h.
Referenced by lire_donnees(), and write_flow_rate().
debit_ref_
double Terme_Source_Canal_perio::debit_ref_ mutable protected
Definition at line 61 of file Terme_Source_Canal_perio.h.
Referenced by source(), and write_flow_rate().
debnm1_
double Terme_Source_Canal_perio::debnm1_ mutable protected
Definition at line 60 of file Terme_Source_Canal_perio.h.
Referenced by source(), and write_flow_rate().
dernier_temps_calc_
double Terme_Source_Canal_perio::dernier_temps_calc_ mutable protected
Definition at line 62 of file Terme_Source_Canal_perio.h.
Referenced by source().
dir_source_
ArrOfDouble Terme_Source_Canal_perio::dir_source_ protected
Definition at line 51 of file Terme_Source_Canal_perio.h.
Referenced by completer(), lire_donnees(), source(), and source_convection_diffusion().
direction_ecoulement_
int Terme_Source_Canal_perio::direction_ecoulement_ protected
Definition at line 52 of file Terme_Source_Canal_perio.h.
Referenced by Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), completer(), source(), and source_convection_diffusion().
flow_rate_file_
SFichier Terme_Source_Canal_perio::flow_rate_file_ mutable private
Definition at line 67 of file Terme_Source_Canal_perio.h.
Referenced by write_flow_rate().
h
double Terme_Source_Canal_perio::h protected
Definition at line 56 of file Terme_Source_Canal_perio.h.
Referenced by lire_donnees().
info_obj
const Type_info Terme_Source_Canal_perio::info_obj static
Definition at line 31 of file Terme_Source_Canal_perio.h.
is_debit_impose_
int Terme_Source_Canal_perio::is_debit_impose_ protected
Definition at line 63 of file Terme_Source_Canal_perio.h.
Referenced by lire_donnees(), and write_flow_rate().
pressure_gradient_file_
SFichier Terme_Source_Canal_perio::pressure_gradient_file_ mutable private
Definition at line 68 of file Terme_Source_Canal_perio.h.
Referenced by source().
restart_file_
SFichier Terme_Source_Canal_perio::restart_file_ mutable private
Definition at line 69 of file Terme_Source_Canal_perio.h.
Referenced by source().
source_
double Terme_Source_Canal_perio::source_ mutable protected
Definition at line 59 of file Terme_Source_Canal_perio.h.
Referenced by source(), and write_flow_rate().
surface_bord_
double Terme_Source_Canal_perio::surface_bord_ protected
Definition at line 55 of file Terme_Source_Canal_perio.h.
Referenced by completer(), source(), and source_convection_diffusion().
u_etoile
double Terme_Source_Canal_perio::u_etoile protected
Definition at line 56 of file Terme_Source_Canal_perio.h.
Referenced by lire_donnees().
velocity_weighting_
int Terme_Source_Canal_perio::velocity_weighting_ protected
Definition at line 53 of file Terme_Source_Canal_perio.h.
Referenced by lire_donnees(), source_convection_diffusion(), and Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Terme_Source_Canal_perio.h
src/ThHyd/Incompressible/Sources/Terme_Source_Canal_perio.cpp