TRUST: Rectify_Mesh Class Reference
Rectify_Mesh Class Reference
: class Rectify_Mesh
<Description of class Rectify_Mesh>
#include <Rectify_Mesh.h>
Public Member Functions
Rectify_Mesh ()
~Rectify_Mesh ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &is) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Rectify_Mesh & self_cast (Objet_U &)
static const Rectify_Mesh & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void apply (void)
void check_dimension (void) const
void check_nb_zones (void) const
void check_cell_type (void) const
void apply_2D (void)
void apply_3D (void)
void check_cell_orientation_2D (void)
void check_cell_orientation_3D (void)
void check_cell_enumeration_3D (void)
void swap_nodes (IntTab &cells, int cell, int node0, int node1)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
: class Rectify_Mesh
<Description of class Rectify_Mesh>
Definition at line 31 of file Rectify_Mesh.h.
Constructor & Destructor Documentation
Rectify_Mesh()
Rectify_Mesh::Rectify_Mesh ()
Definition at line 22 of file Rectify_Mesh.cpp.
~Rectify_Mesh()
Rectify_Mesh::~Rectify_Mesh ()
Definition at line 22 of file Rectify_Mesh.cpp.
Member Function Documentation
apply()
void Rectify_Mesh::apply (void) protected
Definition at line 44 of file Rectify_Mesh.cpp.
{
  Cerr << "Rectifying domain " << domaine().le_nom() << finl;
  check_dimension();
  check_nb_zones();
  check_cell_type();
  if ( Objet_U::dimension == 2 )
    {
      apply_2D();
    }
  else
    {
      apply_3D();
    }
  Cerr << "Rectification... OK" << finl;
}
References apply_2D(), apply_3D(), Cerr, check_cell_type(), check_dimension(), check_nb_zones(), Objet_U::dimension, Interprete_geometrique_base::domaine(), finl, and Domaine::le_nom().
Referenced by interpreter_().
apply_2D()
void Rectify_Mesh::apply_2D (void) protected
Definition at line 99 of file Rectify_Mesh.cpp.
{
  Domaine& domain = domaine();
  Scatter::uninit_sequential_domain(domain);
  assert( domain.zone(0).type_elem().valeur().que_suis_je() == Motcle("Triangle") );
  check_cell_orientation_2D();
  Scatter::init_sequential_domain(domain);
}
References check_cell_orientation_2D(), Interprete_geometrique_base::domaine(), Scatter::init_sequential_domain(), Objet_U::que_suis_je(), Zone::type_elem(), Scatter::uninit_sequential_domain(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by apply().
apply_3D()
void Rectify_Mesh::apply_3D (void) protected
Definition at line 112 of file Rectify_Mesh.cpp.
{
  Domaine& domain = domaine();
  Scatter::uninit_sequential_domain(domain);
  assert( domain.zone(0).type_elem().valeur().que_suis_je() == Motcle("Tetraedre") );
  check_cell_orientation_3D();
  check_cell_enumeration_3D();
  Scatter::init_sequential_domain(domain);
}
References check_cell_enumeration_3D(), check_cell_orientation_3D(), Interprete_geometrique_base::domaine(), Scatter::init_sequential_domain(), Objet_U::que_suis_je(), Zone::type_elem(), Scatter::uninit_sequential_domain(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by apply().
check_cell_enumeration_3D()
void Rectify_Mesh::check_cell_enumeration_3D (void) protected
Definition at line 213 of file Rectify_Mesh.cpp.
{
  const DoubleTab& nodes = domaine().les_sommets();
  IntTab&          cells = domaine().zone(0).les_elems();
  const int nb_cells = cells.dimension(0);
  ArrOfDouble lengths(3);
  int nb_swaps = 0;
  for (int c=0; c<nb_cells; ++c)
    {
      const int n0 = cells(c,0);
      const int n1 = cells(c,1);
      const int n2 = cells(c,2);
      const int n3 = cells(c,3);
      const double x0 = nodes(n0,0);
      const double x1 = nodes(n1,0);
      const double x2 = nodes(n2,0);
      const double x3 = nodes(n3,0);
      const double y0 = nodes(n0,1);
      const double y1 = nodes(n1,1);
      const double y2 = nodes(n2,1);
      const double y3 = nodes(n3,1);
      const double z0 = nodes(n0,2);
      const double z1 = nodes(n1,2);
      const double z2 = nodes(n2,2);
      const double z3 = nodes(n3,2);
      lengths[0] =   ((x0+x1)-(x2+x3))*((x0+x1)-(x2+x3))
                     + ((y0+y1)-(y2+y3))*((y0+y1)-(y2+y3))
                     + ((z0+z1)-(z2+z3))*((z0+z1)-(z2+z3));
      lengths[1] =   ((x0+x2)-(x1+x3))*((x0+x2)-(x1+x3))
                     + ((y0+y2)-(y1+y3))*((y0+y2)-(y1+y3))
                     + ((z0+z2)-(z1+z3))*((z0+z2)-(z1+z3));
      lengths[2] =   ((x0+x3)-(x1+x2))*((x0+x3)-(x1+x2))
                     + ((y0+y3)-(y1+y2))*((y0+y3)-(y1+y2))
                     + ((z0+z3)-(z1+z2))*((z0+z3)-(z1+z2));
      const int id = imin_array(lengths);
// const int id = imax_array(lengths);
      if ( (id == 0) && (lengths[0] < lengths[1]) )
        {
          swap_nodes(cells,c,1,2);
          swap_nodes(cells,c,1,3);
          ++nb_swaps;
        }
      if (id == 1)
        {
// nothing to do
        }
      if ( (id == 2) && (lengths[2] < lengths[1]) )
        {
          swap_nodes(cells,c,2,3);
          swap_nodes(cells,c,1,3);
          ++nb_swaps;
        }
    }
  Cerr << "************************************************" << finl;
  Cerr << "Rectify_Mesh::check_cell_enumeration_3D report :" << finl;
  Cerr << "  " << nb_swaps << " swap" << ((nb_swaps ==1) ? "" : "s") << " were performed" << finl;
  Cerr << "************************************************" << finl;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), finl, imin_array(), Zone::les_elems(), Domaine::les_sommets(), swap_nodes(), and Domaine::zone().
Referenced by apply_3D().
check_cell_orientation_2D()
void Rectify_Mesh::check_cell_orientation_2D (void) protected
Definition at line 125 of file Rectify_Mesh.cpp.
{
  const DoubleTab& nodes = domaine().les_sommets();
  IntTab&          cells = domaine().zone(0).les_elems();
  const int nb_cells = cells.dimension(0);
  int nb_swaps = 0;
  for (int c=0; c<nb_cells; ++c)
    {
      const int n0 = cells(c,0);
      const int n1 = cells(c,1);
      const int n2 = cells(c,2);
      const double x0 = nodes(n0,0);
      const double x1 = nodes(n1,0);
      const double x2 = nodes(n2,0);
      const double y0 = nodes(n0,1);
      const double y1 = nodes(n1,1);
      const double y2 = nodes(n2,1);
      const double area = (x1-x0)*(y2-y0) - (x2-x0)*(y1-y0);
      if ( area < 0.)
        {
          swap_nodes(cells,c,1,2);
          ++nb_swaps;
        }
    }
  Cerr << "************************************************" << finl;
  Cerr << "Rectify_Mesh::check_cell_orientation_2D report :" << finl;
  Cerr << "  " << nb_swaps << " swap" << ((nb_swaps ==1) ? "" : "s") << " were performed" << finl;
  Cerr << "************************************************" << finl;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), finl, Zone::les_elems(), Domaine::les_sommets(), swap_nodes(), and Domaine::zone().
Referenced by apply_2D().
check_cell_orientation_3D()
void Rectify_Mesh::check_cell_orientation_3D (void) protected
Definition at line 162 of file Rectify_Mesh.cpp.
{
  const DoubleTab& nodes = domaine().les_sommets();
  IntTab&          cells = domaine().zone(0).les_elems();
  const int nb_cells = cells.dimension(0);
  int nb_swaps = 0;
  for (int c=0; c<nb_cells; ++c)
    {
      const int n0 = cells(c,0);
      const int n1 = cells(c,1);
      const int n2 = cells(c,2);
      const int n3 = cells(c,3);
      const double x0 = nodes(n0,0);
      const double x1 = nodes(n1,0);
      const double x2 = nodes(n2,0);
      const double x3 = nodes(n3,0);
      const double y0 = nodes(n0,1);
      const double y1 = nodes(n1,1);
      const double y2 = nodes(n2,1);
      const double y3 = nodes(n3,1);
      const double z0 = nodes(n0,2);
      const double z1 = nodes(n1,2);
      const double z2 = nodes(n2,2);
      const double z3 = nodes(n3,2);
      const double volume =   (x1-x0) * (y2-y0) * (z3-z0)
                              + (x2-x0) * (y3-y0) * (z1-z0)
                              + (x3-x0) * (y1-y0) * (z2-z0)
                              - (z1-z0) * (y2-y0) * (x3-x0)
                              - (x2-x0) * (z3-z0) * (y1-y0)
                              - (y3-y0) * (x1-x0) * (z2-z0);
      if (volume < 0.)
        {
          swap_nodes(cells,c,2,3);
          ++nb_swaps;
        }
    }
  Cerr << "************************************************" << finl;
  Cerr << "Rectify_Mesh::check_cell_orientation_3D report :" << finl;
  Cerr << "  " << nb_swaps << " swap" << ((nb_swaps ==1) ? "" : "s") << " were performed" << finl;
  Cerr << "************************************************" << finl;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Interprete_geometrique_base::domaine(), finl, Zone::les_elems(), Domaine::les_sommets(), swap_nodes(), and Domaine::zone().
Referenced by apply_3D().
check_cell_type()
void Rectify_Mesh::check_cell_type (void) const protected
Definition at line 86 of file Rectify_Mesh.cpp.
{
  const Nom& cell_type = domaine().zone(0).type_elem().valeur().que_suis_je();
  if ( ! ( (cell_type == Motcle("Triangle")) || (cell_type == Motcle("Tetraedre")) ) )
    {
      Cerr << "Error in 'Rectify_Mesh::check_cell_type()':" << finl;
      Cerr << "  Invalid cell type: " << cell_type << finl;
      Cerr << "  Rectify_Mesh can only deal with triangles and tetrahedrons" << finl;
      Process::exit();
    }
}
References Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, Objet_U::que_suis_je(), Zone::type_elem(), Deriv_Elem_geom_base::valeur(), and Domaine::zone().
Referenced by apply().
check_dimension()
void Rectify_Mesh::check_dimension (void) const protected
Definition at line 64 of file Rectify_Mesh.cpp.
{
  if ( ! ( (Objet_U::dimension == 2) || (Objet_U::dimension == 3) ) )
    {
      Cerr << "Error in 'Rectify_Mesh::check_dimension()':" << finl;
      Cerr << "  Invalid dimension: " << Objet_U::dimension << finl;
      Cerr << "  Rectify_Mesh can only deal 2D or 3D domains" << finl;
      Process::exit();
    }
}
References Cerr, Objet_U::dimension, Process::exit(), and finl.
Referenced by apply().
check_nb_zones()
void Rectify_Mesh::check_nb_zones (void) const protected
Definition at line 75 of file Rectify_Mesh.cpp.
{
  if ( domaine().nb_zones() != 1 )
    {
      Cerr << "Error in 'Rectify_Mesh::check_nb_zones()':" << finl;
      Cerr << "  Invalid number of zones: " << domaine().nb_zones() << finl;
      Cerr << "  Rectify_Mesh cannot deal with domains having more than one zone" << finl;
      Process::exit();
    }
}
References Cerr, Interprete_geometrique_base::domaine(), Process::exit(), finl, and Domaine::nb_zones().
Referenced by apply().
cree_instance()
Objet_U * Rectify_Mesh::cree_instance () static
Definition at line 22 of file Rectify_Mesh.cpp.
duplique()
int Rectify_Mesh::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file Rectify_Mesh.cpp.
get_info()
const Type_info * Rectify_Mesh::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 22 of file Rectify_Mesh.cpp.
info()
const Type_info * Rectify_Mesh::info () static
Definition at line 22 of file Rectify_Mesh.cpp.
interpreter_()
Entree & Rectify_Mesh::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 37 of file Rectify_Mesh.cpp.
{
  associer_domaine(is);
  apply();
  return is;
}
References apply(), and Interprete_geometrique_base::associer_domaine().
printOn()
Sortie & Rectify_Mesh::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file Rectify_Mesh.cpp.
{
  Interprete::printOn(os);
  return os;
}
References Interprete::printOn().
readOn()
Entree & Rectify_Mesh::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Rectify_Mesh.cpp.
{
  Interprete::readOn(is);
  return is;
}
References Interprete::readOn().
self_cast() [1/2]
const Rectify_Mesh & Rectify_Mesh::self_cast (const Objet_U & r) static
Definition at line 22 of file Rectify_Mesh.cpp.
self_cast() [2/2]
Rectify_Mesh & Rectify_Mesh::self_cast (Objet_U & r) static
Definition at line 22 of file Rectify_Mesh.cpp.
swap_nodes()
void Rectify_Mesh::swap_nodes (IntTab & cells, int cell, int node0, int node1) protected
Definition at line 288 of file Rectify_Mesh.cpp.
{
  const int tmp  = cells(cell,node0);
  cells(cell,node0) = cells(cell,node1);
  cells(cell,node1) = tmp;
}
Referenced by check_cell_enumeration_3D(), check_cell_orientation_2D(), and check_cell_orientation_3D().
taille_memoire()
unsigned Rectify_Mesh::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file Rectify_Mesh.cpp.
Member Data Documentation
info_obj
const Type_info Rectify_Mesh::info_obj static
Definition at line 34 of file Rectify_Mesh.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Rectify_Mesh.h
src/Kernel/Geometrie/Rectify_Mesh.cpp