TRUST: Op_Grad_CoviMAC_Face Class Reference
Op_Grad_CoviMAC_Face Class Reference
class Op_Grad_CoviMAC_Face
Cette classe represente l'operateur de gradient
La discretisation est CoviMAC
On calcule le gradient d'un champ_P0_CoviMAC (la pression)
#include <Op_Grad_CoviMAC_Face.h>
Public Member Functions
Op_Grad_CoviMAC_Face ()
~Op_Grad_CoviMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
const DoubleTab & mu_f (int full_stencil=0) const
void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Grad_CoviMAC_Face & self_cast (Objet_U &)
static const Op_Grad_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
IntTab fgrad_d
IntTab fgrad_e
DoubleTab fgrad_c
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Private Attributes
double last_gradp_
DoubleTab mu_f_
Ref_Zone_CoviMAC ref_zone
Ref_Zone_Cl_CoviMAC ref_zcl
Detailed Description
class Op_Grad_CoviMAC_Face
Cette classe represente l'operateur de gradient
La discretisation est CoviMAC
On calcule le gradient d'un champ_P0_CoviMAC (la pression)
Definition at line 45 of file Op_Grad_CoviMAC_Face.h.
Constructor & Destructor Documentation
Op_Grad_CoviMAC_Face::Op_Grad_CoviMAC_Face ()
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
Op_Grad_CoviMAC_Face::~Op_Grad_CoviMAC_Face ()
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
Member Function Documentation
virtual void Op_Grad_CoviMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Operateur_base.
void Op_Grad_CoviMAC_Face::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch) [virtual]
Implements Operateur_base.
Definition at line 69 of file Op_Grad_CoviMAC_Face.cpp.
References ref_cast, ref_zcl, ref_zone, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  ref_zone = ref_cast(Zone_CoviMAC, zone_dis.valeur());
  ref_zcl = ref_cast(Zone_Cl_CoviMAC, zone_cl_dis.valeur());
}
void Op_Grad_CoviMAC_Face::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 72 of file Op_Grad_CoviMAC_Face.h.
{ }; //ok
void Op_Grad_CoviMAC_Face::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 75 of file Op_Grad_CoviMAC_Face.cpp.
References Cerr, Joint::epaisseur(), Process::exit(), finl, Zone::joint(), last_gradp_, Zone::nb_joints(), ref_zone, Ref_Zone_CoviMAC::valeur(), and Zone_dis_base::zone().
{
  Operateur_Grad_base::completer();
  /* dimensionnement de fgrad_c (gradient aux faces internes) */
  const Zone_CoviMAC& zone = ref_zone.valeur();
  /* besoin d'un joint de 1 */
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Grad_CoviMAC_Face : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  last_gradp_ = -DBL_MAX;
}
Objet_U * Op_Grad_CoviMAC_Face::cree_instance () [static]
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
virtual void Op_Grad_CoviMAC_Face::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Operateur_base.
int Op_Grad_CoviMAC_Face::duplique () const [virtual]
Implements Operateur_Grad_base.
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
const Type_info * Op_Grad_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
int Op_Grad_CoviMAC_Face::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 56 of file Op_Grad_CoviMAC_Face.h.
  {
    return 1;
  };
int Op_Grad_CoviMAC_Face::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 247 of file Op_Grad_CoviMAC_Face.cpp.
{
  return 0;
}
const Type_info * Op_Grad_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
const DoubleTab & Op_Grad_CoviMAC_Face::mu_f (int full_stencil = 0) const
Definition at line 88 of file Op_Grad_CoviMAC_Face.cpp.
References Objet_U::dimension, MorEqn::equation(), Champ_Face_CoviMAC::fcl(), Zone_CoviMAC::fgrad(), fgrad_c, fgrad_d, fgrad_e, Zone_CoviMAC::harmonic_points(), Equation_base::inconnue(), last_gradp_, DoubleVect::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), mu_f_, Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), Champ_Proto::passe(), Champ_Inc_base::recuperer_temps_passe(), ref_cast, ref_zcl, ref_zone, DoubleTab::resize(), sub_type, Deriv_Champ_Inc_base::valeur(), valeur(), Ref_Zone_CoviMAC::valeur(), and Champ_Inc_base::valeurs().
{
  const Zone_CoviMAC& zone = ref_zone.valeur();
  const Champ_Face_CoviMAC& ch = ref_cast(Champ_Face_CoviMAC, equation().inconnue().valeur());
  const DoubleTab& press = ref_cast(Navier_Stokes_std, equation()).pression().valeurs(), &rho = equation().milieu().masse_volumique().passe(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  int i, e, f, n, ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot(), N = ch.valeurs().line_size(), m, M = press.line_size(), cR = rho.dimension_tot(0) == 1, D = dimension;
  double t_past = equation().inconnue().valeur().recuperer_temps_passe();
  if (!full_stencil && (alp ? (last_gradp_ >= t_past) : (last_gradp_ != -DBL_MAX))) return mu_f_; //deja calcule a ce temps -> rien a faire
  DoubleTrav nu(alp ? ne_tot : 0, M), xh(nf_tot, M, D), wh(nf_tot, M), fgrad_w(nf_tot, M); /* diffusivite, donnees des points harmoniques, poids de l'amont */
  /* diffusivite : rien hors Pb_Mutliphase, 1 / rho_m en 6 equations, 1 / (alpha_k rho_k) en 7 equations */
  if (alp && M == N) for (e = 0; e < ne_tot; e++) for (m = 0; m < M; m++) nu(e, m) = 1. / rho(!cR * e, m);
  else if (alp && M == 1) for (e = 0; e < ne_tot; nu(e, 0) = 1. / nu(e, 0), e++)
      for (n = 0; n < N; n++) nu(e, 0) += (alp ? (*alp)(e, n) : 1) * rho(!cR * e, n);
  /* points harmoniques, puis gradient */
  zone.harmonic_points(ref_zcl->les_conditions_limites(), 1, 0, alp ? &nu : NULL, NULL, xh, wh, NULL);
  zone.fgrad(ref_zcl->les_conditions_limites(), ch.fcl(), alp ? &nu : NULL, NULL, xh, wh, NULL, NULL, 0, full_stencil, fgrad_w, fgrad_d, fgrad_e, fgrad_c, NULL, NULL);
  /* mu_f_ : fgrad_w etendu a N composantes et separe en amont/aval */
  for (mu_f_.resize(nf_tot, N, 2), f = 0; f < nf_tot; f++) for (n = 0, m = 0; n < N; n++, m += (M > 1))
      for (i = 0; i < 2; i++) mu_f_(f, n, i) = i ? 1 - fgrad_w(f, m) : fgrad_w(f, m);
  last_gradp_ = t_past;
  return mu_f_;
}
Sortie & Op_Grad_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 53 of file Op_Grad_CoviMAC_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Grad_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 61 of file Op_Grad_CoviMAC_Face.cpp.
{
  return s ;
}
Op_Grad_CoviMAC_Face & Op_Grad_CoviMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Grad_base.
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
const Op_Grad_CoviMAC_Face & Op_Grad_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Grad_base.
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
unsigned Op_Grad_CoviMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 47 of file Op_Grad_CoviMAC_Face.cpp.
Member Data Documentation
DoubleTab Op_Grad_CoviMAC_Face::fgrad_c [mutable]
Definition at line 70 of file Op_Grad_CoviMAC_Face.h.
Referenced by mu_f().
IntTab Op_Grad_CoviMAC_Face::fgrad_d [mutable]
Definition at line 69 of file Op_Grad_CoviMAC_Face.h.
Referenced by mu_f().
IntTab Op_Grad_CoviMAC_Face::fgrad_e [mutable]
Definition at line 69 of file Op_Grad_CoviMAC_Face.h.
Referenced by mu_f().
const Type_info Op_Grad_CoviMAC_Face::info_obj [static]
Reimplemented from Operateur_Grad_base.
Definition at line 48 of file Op_Grad_CoviMAC_Face.h.
double Op_Grad_CoviMAC_Face::last_gradp_ [mutable, private]
Definition at line 72 of file Op_Grad_CoviMAC_Face.h.
Referenced by completer(), and mu_f().
DoubleTab Op_Grad_CoviMAC_Face::mu_f_ [mutable, private]
Definition at line 77 of file Op_Grad_CoviMAC_Face.h.
Referenced by mu_f().
Ref_Zone_Cl_CoviMAC Op_Grad_CoviMAC_Face::ref_zcl [private]
Definition at line 79 of file Op_Grad_CoviMAC_Face.h.
Referenced by associer(), and mu_f().
Ref_Zone_CoviMAC Op_Grad_CoviMAC_Face::ref_zone [private]
Definition at line 78 of file Op_Grad_CoviMAC_Face.h.
Referenced by associer(), completer(), and mu_f().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Grad_CoviMAC_Face.h
src/CoviMAC/Operateurs/Op_Grad_CoviMAC_Face.cpp