TRUST: Deriv_Elem_EF_base Class Reference
Deriv_Elem_EF_base Class Reference
#include <Elem_EF.h>
Public Member Functions
~Deriv_Elem_EF_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Elem_EF_base ()
Deriv_Elem_EF_base (const Deriv_Elem_EF_base &)
const Elem_EF_base & valeur () const
Elem_EF_base & valeur ()
const Elem_EF_base * operator-> () const
Elem_EF_base * operator-> ()
const Deriv_Elem_EF_base & operator= (const Elem_EF_base &)
const Deriv_Elem_EF_base & operator= (const Deriv_Elem_EF_base &)
operator const Elem_EF_base & () const
operator Elem_EF_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Elem_EF_base & self_cast (Objet_U &)
static const Deriv_Elem_EF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Elem_EF_base * pointeur_
Detailed Description
Definition at line 41 of file Elem_EF.h.
Constructor & Destructor Documentation
Deriv_Elem_EF_base::~Deriv_Elem_EF_base ()
Definition at line 29 of file Elem_EF.cpp.
Deriv_Elem_EF_base::Deriv_Elem_EF_base ()
Definition at line 29 of file Elem_EF.cpp.
Deriv_Elem_EF_base::Deriv_Elem_EF_base (const Deriv_Elem_EF_base & t)
Definition at line 29 of file Elem_EF.cpp.
Member Function Documentation
Objet_U * Deriv_Elem_EF_base::cree_instance () [static]
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
int Deriv_Elem_EF_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
const Type_info * Deriv_Elem_EF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
const Type_info & Deriv_Elem_EF_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 29 of file Elem_EF.cpp.
const Type_info * Deriv_Elem_EF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
Deriv_Elem_EF_base::operator const Elem_EF_base & () const
Definition at line 29 of file Elem_EF.cpp.
Deriv_Elem_EF_base::operator Elem_EF_base & ()
Definition at line 29 of file Elem_EF.cpp.
const Elem_EF_base * Deriv_Elem_EF_base::operator-> () const [inline]
Definition at line 41 of file Elem_EF.h.
: public DERIV(Elem_EF_base)
Elem_EF_base * Deriv_Elem_EF_base::operator-> () [inline]
Definition at line 41 of file Elem_EF.h.
: public DERIV(Elem_EF_base)
const Deriv_Elem_EF_base & Deriv_Elem_EF_base::operator= (const Deriv_Elem_EF_base & t)
Definition at line 29 of file Elem_EF.cpp.
const Deriv_Elem_EF_base & Deriv_Elem_EF_base::operator= (const Elem_EF_base & t)
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
Sortie & Deriv_Elem_EF_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
Entree & Deriv_Elem_EF_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
const Deriv_Elem_EF_base & Deriv_Elem_EF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
Deriv_Elem_EF_base & Deriv_Elem_EF_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
void Deriv_Elem_EF_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 29 of file Elem_EF.cpp.
unsigned Deriv_Elem_EF_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Elem_EF.
Definition at line 29 of file Elem_EF.cpp.
const Elem_EF_base & Deriv_Elem_EF_base::valeur () const [inline]
Definition at line 41 of file Elem_EF.h.
Referenced by Elem_EF::calcul_vc(), Elem_EF::calcul_xg(), Zone_EF::discretiser(), EF_discretisation::discretiser_champ(), EF_discretisation::discretiser_champ_fonc_don(), Elem_EF::normale(), Elem_EF::printOn(), and EF_discretisation::vorticite().
: public DERIV(Elem_EF_base)
Elem_EF_base & Deriv_Elem_EF_base::valeur () [inline]
Definition at line 41 of file Elem_EF.h.
: public DERIV(Elem_EF_base)
Member Data Documentation
const Type_info Deriv_Elem_EF_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Elem_EF.
Definition at line 41 of file Elem_EF.h.
Elem_EF_base* Deriv_Elem_EF_base::pointeur_ [private]
Definition at line 41 of file Elem_EF.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Elem_EF.h
src/EF/Zones/Elem_EF.cpp