TRUST: Elem_geom_base Class Reference
Elem_geom_base Class Reference abstract
Classe Elem_geom_base
Cette classe est la classe de base pour la definition d'elements
geometriques constituant un maillage (i.e. une Zone geometrique)
Un element geometrique a une Zone associe a laquelle il fournit
les routines de base pour la manipulation des ses elements.
(Une zone n'a qu'un seul type d'element geometrique)
#include <Elem_geom_base.h>
Public Member Functions
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone ma_zone
Detailed Description
Classe Elem_geom_base
Cette classe est la classe de base pour la definition d'elements
geometriques constituant un maillage (i.e. une Zone geometrique)
Un element geometrique a une Zone associe a laquelle il fournit
les routines de base pour la manipulation des ses elements.
(Une zone n'a qu'un seul type d'element geometrique)
Definition at line 49 of file Elem_geom_base.h.
Constructor & Destructor Documentation
Elem_geom_base()
Elem_geom_base::Elem_geom_base ()
Definition at line 19 of file Elem_geom_base.cpp.
~Elem_geom_base()
Elem_geom_base::~Elem_geom_base () override
Definition at line 19 of file Elem_geom_base.cpp.
Member Function Documentation
associer_zone()
void Elem_geom_base::associer_zone (const Zone & une_zone) inline
Associe l'element geometrique a sa zone.
Definition at line 93 of file Elem_geom_base.h.
{
  ma_zone=une_zone;
}
References ma_zone.
Referenced by Elem_geom::associer_zone(), Domaine_bord::extraire_domaine_bord(), and MaillerParallel::interpreter().
calculer_centres_gravite()
void Elem_geom_base::calculer_centres_gravite (DoubleTab & xp) const virtual
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
Reimplemented in Hexaedre_axi, Rectangle_2D_axi, Rectangle_axi, Polyedre, and Polygone.
Definition at line 176 of file Elem_geom_base.cpp.
{
  const IntTab& les_Polys = ma_zone->les_elems();
  const Domaine& le_domaine = ma_zone->domaine();
  int nb_elem;
  if(xp.dimension(0)==0)
    {
      nb_elem = ma_zone->nb_elem_tot();
      xp.resize(nb_elem,dimension);
    }
  else
    nb_elem=xp.dimension(0);
  int num_som;
  xp=0;
  for (int num_elem=0; num_elem<nb_elem; num_elem++)
    {
      int nb_som_reel=nb_som();
      while (les_Polys(num_elem,nb_som_reel-1)==-1)  nb_som_reel--;
      for(int s=0; s<nb_som_reel; s++)
        {
          num_som = les_Polys(num_elem,s);
          for(int i=0; i<dimension; i++)
            xp(num_elem,i) += le_domaine.coord(num_som,i)/nb_som_reel;
        }
    }
}
References Domaine::coord(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone::les_elems(), ma_zone, Zone::nb_elem_tot(), nb_som(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Elem_geom::calculer_centres_gravite(), Rectangle_2D_axi::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), and Debog_Pb::read_geometry_data().
calculer_normales()
void Elem_geom_base::calculer_normales (const IntTab & faces_sommets, DoubleTab & face_normales) const virtual
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
Reimplemented in Hexaedre, Rectangle, Tetraedre, and Triangle.
Definition at line 221 of file Elem_geom_base.cpp.
{
  Cerr << "calculer_normales method is not coded for an element " << finl;
  Cerr << "of type que_suis_je() " << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by Elem_geom::calculer_normales().
calculer_volumes()
virtual void Elem_geom_base::calculer_volumes (DoubleVect &) const pure virtual
Implemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, Segment, Segment_axi, Tetraedre, and Triangle.
Referenced by Elem_geom::calculer_volumes().
contient() [1/2]
virtual int Elem_geom_base::contient (const ArrOfDouble & , int) const pure virtual
Implemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_axi, Segment, Tetraedre, and Triangle.
Referenced by Elem_geom::contient().
contient() [2/2]
virtual int Elem_geom_base::contient (const ArrOfInt & , int) const pure virtual
Implemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_axi, Segment, Tetraedre, and Triangle.
creer_faces_elem() [1/2]
void Elem_geom_base::creer_faces_elem (Faces & faces, int elem) const inline
Cree les faces de l'element de la zone specifie.
Definition at line 119 of file Elem_geom_base.h.
{
  assert(nb_type_face() == 1);
  creer_faces_elem(faces, elem, type_face());
}
References creer_faces_elem(), nb_type_face(), and type_face().
creer_faces_elem() [2/2]
void Elem_geom_base::creer_faces_elem (Faces & les_faces, int num_elem, Type_Face type) const virtual
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
Definition at line 136 of file Elem_geom_base.cpp.
{
  int type_id=0;
  for(; ((type_id<nb_type_face())
         &&(type!=type_face(type_id))); type_id++)
    ;
  const IntTab& les_Polys = ma_zone->les_elems();
  assert(les_Polys.dimension_tot(0) > num_elem);
  int face, i;
  les_faces.dimensionner(nb_faces(type_id));
  les_faces.associer_zone(ma_zone.valeur());
  for(face=0; face<nb_faces(type_id); face++)
    {
      int face_id=num_face(face, type);
      for (i=0; i<nb_som_face(type_id); i++)
        les_faces.sommet(face_id,i) = les_Polys(num_elem,face_sommet(face_id, i));
      les_faces.completer(face_id, num_elem);
    }
}
References Faces::associer_zone(), Faces::completer(), TRUSTTab< _TYPE_ >::dimension_tot(), Faces::dimensionner(), face_sommet(), Zone::les_elems(), ma_zone, nb_faces(), nb_som_face(), nb_type_face(), num_face(), Faces::sommet(), type_face(), and Ref_Zone::valeur().
Referenced by Elem_geom::creer_faces_elem(), and creer_faces_elem().
est_structure()
virtual int Elem_geom_base::est_structure () const pure virtual
Implemented in Hexaedre, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Segment, Tetraedre, and Triangle.
Referenced by Elem_geom::est_structure().
face_sommet()
virtual int Elem_geom_base::face_sommet (int i, int j) const pure virtual
Implemented in Hexaedre, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Segment, Tetraedre, and Triangle.
Referenced by creer_faces_elem(), and Elem_geom::face_sommet().
get_info()
const Type_info * Elem_geom_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Poly_geom_base, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, Segment, Segment_axi, Tetraedre, and Triangle.
Definition at line 19 of file Elem_geom_base.cpp.
get_tab_aretes_sommets_locaux()
void Elem_geom_base::get_tab_aretes_sommets_locaux (IntTab & aretes_som_local) const virtual
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Reimplemented in Tetraedre.
Definition at line 271 of file Elem_geom_base.cpp.
{
  Cerr << "Elem_geom_base::aretes_sommets_locaux : error.\n"
       << " Method not implemented for the object "
       << que_suis_je() << finl;
  exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
get_tab_faces_sommets_locaux()
int Elem_geom_base::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const virtual
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Reimplemented in Hexaedre, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Segment, Tetraedre, Triangle, and Poly_geom_base.
Definition at line 258 of file Elem_geom_base.cpp.
{
  Cerr << "Elem_geom_base::faces_sommets_locaux : error.\n"
       << " Method not implemented for the object "
       << que_suis_je() << finl;
  exit();
  return 0;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Zone::creer_aretes(), Faces_builder::creer_faces_reeles(), and find_joint_faces().
info()
const Type_info * Elem_geom_base::info () static
Definition at line 19 of file Elem_geom_base.cpp.
nb_faces()
virtual int Elem_geom_base::nb_faces (int = 0) const pure virtual
Implemented in Hexaedre, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Segment, Tetraedre, and Triangle.
Referenced by creer_faces_elem(), and Elem_geom::nb_faces().
nb_som()
virtual int Elem_geom_base::nb_som () const pure virtual
Implemented in Hexaedre, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Segment, Tetraedre, and Triangle.
Referenced by calculer_centres_gravite(), and Elem_geom::nb_som().
nb_som_face()
virtual int Elem_geom_base::nb_som_face (int = 0) const pure virtual
Implemented in Hexaedre, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Segment, Tetraedre, and Triangle.
Referenced by creer_faces_elem(), Champ_Generique_Interpolation::discretiser_domaine(), find_joint_faces(), and Elem_geom::nb_som_face().
nb_type_face()
int Elem_geom_base::nb_type_face () const virtual
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented in Polyedre, Polygone, and Prisme.
Definition at line 245 of file Elem_geom_base.cpp.
{
  return 1;
}
Referenced by creer_faces_elem(), and Elem_geom::nb_type_face().
nom_lml()
virtual const Nom & Elem_geom_base::nom_lml () const pure virtual
Implemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, Segment, Tetraedre, and Triangle.
Referenced by Elem_geom::nom_lml().
num_face()
int Elem_geom_base::num_face (int face, Type_Face & type) const virtual
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
Definition at line 104 of file Elem_geom_base.cpp.
{
  assert(type==type_face());
  return face;
}
References type_face().
Referenced by creer_faces_elem().
printOn()
Sortie & Elem_geom_base::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Poly_geom_base, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, Segment, Segment_axi, Tetraedre, and Triangle.
Definition at line 36 of file Elem_geom_base.cpp.
{
  return s;
}
Referenced by Poly_geom_base::printOn().
readOn()
Entree & Elem_geom_base::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Poly_geom_base, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, Segment, Segment_axi, Tetraedre, and Triangle.
Definition at line 57 of file Elem_geom_base.cpp.
{
  return s;
}
Referenced by Poly_geom_base::readOn().
reordonner()
void Elem_geom_base::reordonner () virtual
NE FAIT RIEN:
A surcharger dans les classes derivees.
Reimplemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, and Segment.
Definition at line 78 of file Elem_geom_base.cpp.
{
}
Referenced by Elem_geom::reordonner().
self_cast() [1/2]
const Elem_geom_base & Elem_geom_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Elem_geom_base.cpp.
self_cast() [2/2]
Elem_geom_base & Elem_geom_base::self_cast (Objet_U & r) static
Definition at line 19 of file Elem_geom_base.cpp.
type_face()
virtual Type_Face Elem_geom_base::type_face (int = 0) const pure virtual
Implemented in Hexaedre, Hexaedre_axi, Hexaedre_VEF, Point, Polyedre, Polygone, Prisme, Quadrangle_VEF, Rectangle, Rectangle_2D_axi, Rectangle_axi, Segment, Segment_axi, Tetraedre, and Triangle.
Referenced by auto_build_joints(), creer_faces_elem(), Domaine_bord::extraire_domaine_bord(), MaillerParallel::interpreter(), num_face(), and Elem_geom::type_face().
Member Data Documentation
info_obj
const Type_info Elem_geom_base::info_obj static
Definition at line 51 of file Elem_geom_base.h.
ma_zone
Ref_Zone Elem_geom_base::ma_zone protected
Definition at line 75 of file Elem_geom_base.h.
Referenced by associer_zone(), Polygone::build_reduced(), calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), Rectangle_axi::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), Hexaedre::calculer_normales(), Rectangle::calculer_normales(), Tetraedre::calculer_normales(), Triangle::calculer_normales(), Polyedre::calculer_un_centre_gravite(), Polygone::calculer_un_centre_gravite(), Hexaedre::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Polyedre::calculer_volumes(), Polygone::calculer_volumes(), Prisme::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Rectangle::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Rectangle_axi::calculer_volumes(), Segment::calculer_volumes(), Segment_axi::calculer_volumes(), Tetraedre::calculer_volumes(), Triangle::calculer_volumes(), Polyedre::compute_virtual_index(), Hexaedre::contient(), Hexaedre_axi::contient(), Hexaedre_VEF::contient(), Point::contient(), Polyedre::contient(), Polygone::contient(), Prisme::contient(), Quadrangle_VEF::contient(), Rectangle::contient(), Rectangle_axi::contient(), Segment::contient(), Tetraedre::contient(), Triangle::contient(), creer_faces_elem(), Polyedre::get_nb_som_elem_max(), Polygone::get_nb_som_elem_max(), Polyedre::get_somme_nb_faces_elem(), Polygone::get_somme_nb_faces_elem(), Polygone::rebuild_index(), Hexaedre_VEF::reordonner(), Quadrangle_VEF::reordonner(), Segment::reordonner(), Hexaedre::reordonner_elem(), and Rectangle::reordonner_elem().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Elem_geom_base.h
src/Kernel/Geometrie/Elem_geom_base.cpp