TRUST: Raffiner_Simplexes Class Reference
Raffiner_Simplexes Class Reference
: class Raffiner_Simplexes
<Description of class Raffiner_Simplexes>
#include <Raffiner_Simplexes.h>
Public Member Functions
Raffiner_Simplexes ()
~Raffiner_Simplexes ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &is) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Raffiner_Simplexes & self_cast (Objet_U &)
static const Raffiner_Simplexes & self_cast (const Objet_U &)
static void refine_domain (const Domaine &src, Domaine &dest)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
: class Raffiner_Simplexes
<Description of class Raffiner_Simplexes>
Definition at line 31 of file Raffiner_Simplexes.h.
Constructor & Destructor Documentation
Raffiner_Simplexes()
Raffiner_Simplexes::Raffiner_Simplexes ()
Definition at line 28 of file Raffiner_Simplexes.cpp.
~Raffiner_Simplexes()
Raffiner_Simplexes::~Raffiner_Simplexes ()
Definition at line 28 of file Raffiner_Simplexes.cpp.
Member Function Documentation
cree_instance()
Objet_U * Raffiner_Simplexes::cree_instance () static
Definition at line 28 of file Raffiner_Simplexes.cpp.
duplique()
int Raffiner_Simplexes::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Raffiner_Simplexes.cpp.
get_info()
const Type_info * Raffiner_Simplexes::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Raffiner_Simplexes.cpp.
info()
const Type_info * Raffiner_Simplexes::info () static
Definition at line 28 of file Raffiner_Simplexes.cpp.
interpreter_()
Entree & Raffiner_Simplexes::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 1064 of file Raffiner_Simplexes.cpp.
{
  associer_domaine(is);
  Domaine& domain = domaine();
  Scatter::uninit_sequential_domain(domain);
  Domaine initial_domain(domain);
  refine_domain(initial_domain,domain);
  Scatter::init_sequential_domain(domain);
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Interprete_geometrique_base::domaine(), Scatter::init_sequential_domain(), refine_domain(), and Scatter::uninit_sequential_domain().
printOn()
Sortie & Raffiner_Simplexes::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 31 of file Raffiner_Simplexes.cpp.
{
  Interprete::printOn(os);
  return os;
}
References Interprete::printOn().
Referenced by Raffiner_isotrope_parallele::printOn().
readOn()
Entree & Raffiner_Simplexes::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 37 of file Raffiner_Simplexes.cpp.
{
  Interprete::readOn(is);
  return is;
}
References Interprete::readOn().
Referenced by Raffiner_isotrope_parallele::readOn().
refine_domain()
void Raffiner_Simplexes::refine_domain (const Domaine & src, Domaine & dest) static
< (n1-n0);
Definition at line 781 of file Raffiner_Simplexes.cpp.
{
  const Nom&        cell_type          = src.zone(0).type_elem().valeur().que_suis_je();
  const IntTab&     nodes_of_cells_src = src.zone(0).les_elems();
  const DoubleTab& nodes_src          = src.les_sommets();
  IntTab edges_pattern;
  build_edges_pattern(edges_pattern,cell_type);
  IntTab faces_pattern;
  build_faces_pattern(faces_pattern,cell_type);
  IntTab cell_refinement_pattern;
  build_cell_refinement_pattern(cell_refinement_pattern,cell_type);
  IntTab face_refinement_pattern;
  build_face_refinement_pattern(face_refinement_pattern,cell_type);
  Static_Int_Lists cells_of_nodes_src;
  construire_connectivite_som_elem(src.nb_som(), nodes_of_cells_src, cells_of_nodes_src,0);
  IntTab edges_of_cells_src;
  IntTab nodes_of_edges_src;
  build_edges(nodes_of_cells_src, edges_pattern, edges_of_cells_src, nodes_of_edges_src);
  DoubleTab& nodes_dest = dest.les_sommets();
  build_nodes(nodes_src,nodes_of_edges_src,nodes_dest);
  IntTab& nodes_of_cells_dest = dest.zone(0).les_elems();
  build_cells(nodes_of_cells_src,edges_of_cells_src,cell_refinement_pattern,nodes_src.dimension(0),nodes_of_cells_dest);
  {
    const Bords& boundaries_src  = src.zone(0).faces_bord();
    Bords&        boundaries_dest = dest.zone(0).faces_bord();
    boundaries_dest.vide();
    const int nb_boundaries = boundaries_src.size();
    for (int boundary=0; boundary<nb_boundaries; ++boundary)
      {
        boundaries_dest.add(Bord());
        const Type_Face& face_type = boundaries_src[boundary].faces().type_face();
        build_frontier(boundaries_src[boundary],
                       face_type,
                       nodes_of_cells_src,
                       cells_of_nodes_src,
                       edges_of_cells_src,
                       faces_pattern,
                       face_refinement_pattern,
                       dest.zone(0),
                       boundaries_dest[boundary]);
      }
  }
  {
    const Raccords& boundaries_src  = src.zone(0).faces_raccord();
    Raccords&        boundaries_dest = dest.zone(0).faces_raccord();
    boundaries_dest.vide();
    const int nb_boundaries = boundaries_src.size();
    for (int boundary=0; boundary<nb_boundaries; ++boundary)
      {
        boundaries_dest.add(Raccord());
        boundaries_dest[boundary].typer(boundaries_src[boundary].valeur().que_suis_je());
        const Type_Face& face_type = boundaries_src[boundary].valeur().faces().type_face();
        build_frontier(boundaries_src[boundary].valeur(),
                       face_type,
                       nodes_of_cells_src,
                       cells_of_nodes_src,
                       edges_of_cells_src,
                       faces_pattern,
                       face_refinement_pattern,
                       dest.zone(0),
                       boundaries_dest[boundary].valeur());
      }
  }
  {
    const Faces_Internes& boundaries_src  = src.zone(0).faces_int();
    Faces_Internes&        boundaries_dest = dest.zone(0).faces_int();
    boundaries_dest.vide();
    const int nb_boundaries = boundaries_src.size();
    for (int boundary=0; boundary<nb_boundaries; ++boundary)
      {
        boundaries_dest.add(Faces_Interne());
        const Type_Face& face_type = boundaries_src[boundary].faces().type_face();
        build_frontier(boundaries_src[boundary],
                       face_type,
                       nodes_of_cells_src,
                       cells_of_nodes_src,
                       edges_of_cells_src,
                       faces_pattern,
                       face_refinement_pattern,
                       dest.zone(0),
                       boundaries_dest[boundary]);
      }
  }
// marq_front_nodes=0;
  {
    const Joints& boundaries_src  = src.zone(0).faces_joint();
    Joints&       boundaries_dest = dest.zone(0).faces_joint();
    boundaries_dest.vide();
    const int nb_boundaries = boundaries_src.size();
    for (int boundary=0; boundary<nb_boundaries; ++boundary)
      {
        boundaries_dest.add(Joint());
        const Type_Face& face_type = boundaries_src[boundary].faces().type_face();
        build_frontier(boundaries_src[boundary],
                       face_type,
                       nodes_of_cells_src,
                       cells_of_nodes_src,
                       edges_of_cells_src,
                       faces_pattern,
                       face_refinement_pattern,
                       dest.zone(0),
                       boundaries_dest[boundary]);
      }
    for (int boundary=0; boundary<nb_boundaries; ++boundary)
      {
        Joint& joint_dest=boundaries_dest[boundary];
        joint_dest.affecte_PEvoisin(boundaries_src[boundary].PEvoisin());
        joint_dest.affecte_epaisseur(boundaries_src[boundary].epaisseur());
// creation des SOMMETS communs
        ArrOfInt& liste_sommets = joint_dest.set_joint_item(Joint::SOMMET).set_items_communs();
        joint_dest.set_joint_item(Joint::ELEMENT).set_items_distants();
        liste_sommets.set_smart_resize(1);
// On prend tous les sommets des faces de joint:
        const IntTab& som_faces = joint_dest.faces().les_sommets();
        liste_sommets = som_faces;
// on ajoute les sommets du joint d'origine pour
// les sommets isoles
        const ArrOfInt& som_isoles = boundaries_src[boundary].joint_item(Joint::SOMMET).items_communs();
        const int n = som_isoles.size_array();
        array_trier_retirer_doublons(liste_sommets);
        int n0=liste_sommets.size_array();
        ArrOfInt liste_sommets_old(liste_sommets);
        for (int i = 0; i < n; i++)
          liste_sommets.append_array(som_isoles[i]);
// Retirer les doublons de la liste
        array_trier_retirer_doublons(liste_sommets);
        int n1=liste_sommets.size_array();
        Journal()<<" du boulot "<<boundaries_src[boundary].PEvoisin()<<finl;
// if (n0!=liste_sommets.size_array())
        {
          ArrOfInt sommets_to_find(2);
          ArrOfInt incident_cells;
          incident_cells.set_smart_resize(1);
// on doit trouver tous les sommets oublies, c'est ceux en plus.
          ArrOfInt oublie;//!< (n1-n0);
          const ArrOfInt& liste_sommets_org= som_isoles;
          int norg=som_isoles.size_array();
// les liste sont tries
// if (n0==0)
          if (1)
            {
              oublie=liste_sommets;
            }
          else
            {
              Cerr<<liste_sommets<<finl;
              Cerr<<liste_sommets_old<<finl;
              Cerr<<" a trier" <<finl;
              int i=0;
              int i_old=0;
              int t=0;
              while (t<n1-n0)
                {
                  if (liste_sommets[i]!=liste_sommets_old[i_old])
                    {
                      Cerr<<"iiiii"<<i<<finl;
                      oublie[t++]=liste_sommets[i];
                      i++;
                    }
                  else
                    {
                      i++;
                      i_old++;
                    }
                }
              Cerr<<oublie<<finl;
// abort();
            }
// pour chaque sommet oblie on regarde si on a une arrete commune en regardant tous les sommets de la liste
          for (int nio=0; nio<n1; nio++)
            {
              int io=oublie[nio];
              sommets_to_find[0]=io;
// if (marq_front_nodes(io)==0)         continue;
              for (int ns=nio+1; ns<norg; ns++)
                {
                  int s=liste_sommets_org[ns];
                  if (s==io)
                    continue;
// if (marq_front_nodes(s)==0) continue;
                  sommets_to_find[1]=s;
                  find_adjacent_elements(cells_of_nodes_src,sommets_to_find,incident_cells);
// Cerr<<"uuuuu"<<incident_cells<<finl;
// Cerr<<"pos "<<nodes_dest(io,0)<<" "<<nodes_dest(io,1)<<" "<<nodes_dest(io,2)<<finl;
// Cerr<<"pos "<<nodes_dest(s,0)<<" "<<nodes_dest(s,1)<<" "<<nodes_dest(s,2)<<finl;
                  int         nb_nodes_src               = cells_of_nodes_src.get_nb_lists();
                  if (incident_cells.size_array()>0)
                    {
                      for (int ne=0; ne<incident_cells.size_array(); ne++)
{
                          int elem=incident_cells[ne];
                          int nb_nodes_per_cells=nodes_of_cells_src.dimension(1);
                          int local0=-1,local1=-1;
                          for (int i=0; i<nb_nodes_per_cells; i++)
{
                              if (nodes_of_cells_src(elem,i)==io)
                                local0=i;
                              if (nodes_of_cells_src(elem,i)==s)
                                local1=i;
                            }
                          if ((local0==-1)||(local1==-1))
{
                              Cerr<<" pB arrete ?"<<finl;
                              exit();
                            }
                          if (local1<local0)
{
                              std::swap(local0,local1);
                            }
                          int nb_edges_pattern=edges_pattern.dimension(0);
                          int nb_nodes_per_edge_max = edges_pattern.dimension(1);
                          int ok=-1;
                          for (int e=0; e<nb_edges_pattern; e++)
{
// const int node  = find_refined_node_index(nodes_of_cells_src,edges_of_cells_src,nb_nodes_src,elem,-e);
                              for (int c=0; c<nb_nodes_per_edge_max-1; c++)
{
                                  if ((local0==edges_pattern(e,c))&&(local1==edges_pattern(e,c+1)))
{
                                      ok=e;
                                      break;
                                    }
                                }
                            }
                          if (ok==-1)
{
                              Cerr<<" pB edge ?"<<finl;
                              exit();
                            }
                          const int node  = find_refined_node_index(nodes_of_cells_src,edges_of_cells_src,nb_nodes_src,elem,-(ok+1));
                          for (int dir=0; dir<dimension; dir++)
{
                              double test=nodes_dest(node,dir)-(nodes_dest(io,dir)+nodes_dest(s,dir))*0.5;
                              if (std::fabs(test)>1e-7)
{
                                  Cerr<<" pB position ?"<<test <<finl;
                                  exit();
                                }
                            }
                          Journal()<<io<<" sommets "<<s<<" Node "<<node ;
                          for (int dir=0; dir<dimension; dir++)
                            Journal()<<" "<<nodes_dest(node,dir);
                          Journal()<<finl;
                          liste_sommets.append_array(node);
                        }
                    }
                }
            }
          array_trier_retirer_doublons(liste_sommets);
          Journal()<<liste_sommets<<" old "<<liste_sommets_old<<finl;
// abort();
        }
      }
  }
}
References List_Bord::add(), List_Faces_Interne::add(), List_Joint::add(), List_Raccord::add(), Joint::affecte_epaisseur(), Joint::affecte_PEvoisin(), TRUSTArray< _TYPE_ >::append_array(), array_trier_retirer_doublons(), build_cell_refinement_pattern(), build_cells(), build_edges(), build_edges_pattern(), build_face_refinement_pattern(), build_faces_pattern(), build_frontier(), build_nodes(), Cerr, construire_connectivite_som_elem(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Joint::ELEMENT, Process::exit(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_int(), Zone::faces_joint(), Zone::faces_raccord(), find_adjacent_elements(), find_refined_node_index(), finl, Static_Int_Lists::get_nb_lists(), Process::Journal(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), Domaine::nb_som(), Objet_U::que_suis_je(), Joint_Items::set_items_communs(), Joint_Items::set_items_distants(), Joint::set_joint_item(), TRUSTArray< _TYPE_ >::set_smart_resize(), liste::size(), TRUSTArray< _TYPE_ >::size_array(), Joint::SOMMET, swap(), test(), Zone::type_elem(), List_Raccord::valeur(), Deriv_Elem_geom_base::valeur(), valeur(), liste::vide(), and Domaine::zone().
Referenced by Raffiner_isotrope_parallele::interpreter(), and interpreter_().
self_cast() [1/2]
const Raffiner_Simplexes & Raffiner_Simplexes::self_cast (const Objet_U & r) static
Definition at line 28 of file Raffiner_Simplexes.cpp.
self_cast() [2/2]
Raffiner_Simplexes & Raffiner_Simplexes::self_cast (Objet_U & r) static
Definition at line 28 of file Raffiner_Simplexes.cpp.
taille_memoire()
unsigned Raffiner_Simplexes::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Raffiner_Simplexes.cpp.
Member Data Documentation
info_obj
const Type_info Raffiner_Simplexes::info_obj static
Definition at line 34 of file Raffiner_Simplexes.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raffiner_Simplexes.h
src/Kernel/Geometrie/Raffiner_Simplexes.cpp