TRUST: Pilote_ICoCo Class Reference
Pilote_ICoCo Class Reference
classe Pilote_ICoCo
Exemple de pilotage de Trio via ICoCo en C++
#include <Pilote_ICoCo.h>
Public Member Functions
Pilote_ICoCo ()
~Pilote_ICoCo ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Pilote_ICoCo & self_cast (Objet_U &)
static const Pilote_ICoCo & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a:
Interprete::readOn(Entree&)
Detailed Description
classe Pilote_ICoCo
Exemple de pilotage de Trio via ICoCo en C++
Definition at line 35 of file Pilote_ICoCo.h.
Constructor & Destructor Documentation
Pilote_ICoCo::Pilote_ICoCo ()
Definition at line 39 of file Pilote_ICoCo.cpp.
Pilote_ICoCo::~Pilote_ICoCo ()
Definition at line 39 of file Pilote_ICoCo.cpp.
Member Function Documentation
Objet_U * Pilote_ICoCo::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
int Pilote_ICoCo::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
const Type_info * Pilote_ICoCo::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
const Type_info * Pilote_ICoCo::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
Entree & Pilote_ICoCo::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Definition at line 379 of file Pilote_ICoCo.cpp.
References Param::ajouter(), Cerr, Param::dictionnaire(), Process::exit(), finl, Param::lire_avec_accolades_depuis(), main_abort(), main_pilote_icoco_1(), main_pilote_icoco_2(), Interprete::objet(), Objet_U::que_suis_je(), ref_cast, and Param::REQUIRED.
{
  Param param(que_suis_je());
  Nom nom1;
  param.ajouter("pb_name",&nom1,Param::REQUIRED);
  int methode=-1;
  param.ajouter("main",&methode,Param::REQUIRED);
  param.dictionnaire("abort_time_step",0);
  param.dictionnaire("Pilote_ICoCo_1",1);
  param.dictionnaire("Pilote_ICoCo_2",2);
  param.lire_avec_accolades_depuis(is);
  Probleme_U& pb_to_solve=ref_cast(Probleme_U,objet(nom1));
  switch (methode)
    {
    case 0:
      main_abort(pb_to_solve);
      break;
    case 1:
      main_pilote_icoco_1(pb_to_solve);
      break;
    case 2:
      main_pilote_icoco_2(pb_to_solve);
      break;
    default:
      {
        Cerr<<que_suis_je()<<" main numero "<<methode<<" not implemnted"<<finl;
        exit();
      }
    }
  return is;
}
Sortie & Pilote_ICoCo::printOn (Sortie & os) const [protected, virtual]
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 58 of file Pilote_ICoCo.cpp.
{
  return Interprete::printOn(os);
}
Entree & Pilote_ICoCo::readOn (Entree & is) [protected, virtual]
Simple appel a:
Interprete::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 79 of file Pilote_ICoCo.cpp.
{
  return Interprete::readOn(is);
}
Pilote_ICoCo & Pilote_ICoCo::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
const Pilote_ICoCo & Pilote_ICoCo::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
unsigned Pilote_ICoCo::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 39 of file Pilote_ICoCo.cpp.
Member Data Documentation
const Type_info Pilote_ICoCo::info_obj [static]
Reimplemented from Interprete.
Definition at line 37 of file Pilote_ICoCo.h.
The documentation for this class was generated from the following files:
src/Kernel/ICoCo/Pilote_ICoCo.h
src/Kernel/ICoCo/Pilote_ICoCo.cpp