TRUST: Deriv_ Class Reference
Deriv_ Class Reference
Type de base de tous les types DERIV(__TYPE__).
La classe est vide, elle sert de couche intermediaire pour
verifier si un objet est de type DERIV.
30/06/2004, B.Mathieu : la template version n'est plus a jour. DERIV__H.
#include <Deriv_.h>
Public Member Functions
Deriv_ ()
~Deriv_ ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Type de base de tous les types DERIV(__TYPE__).
La classe est vide, elle sert de couche intermediaire pour
verifier si un objet est de type DERIV.
30/06/2004, B.Mathieu : la template version n'est plus a jour. DERIV__H.
Definition at line 40 of file Deriv_.h.
Constructor & Destructor Documentation
Deriv_::Deriv_ ()
Definition at line 29 of file Deriv_.cpp.
Deriv_::~Deriv_ ()
Definition at line 31 of file Deriv_.cpp.
{
// Rien, la destruction est faite au-dessus
// (pas de pointeur disponible)
}
Member Function Documentation
int Deriv_::associer_ (Objet_U &) [virtual]
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Returns:
int
Signification: code de retour
Contraintes:
Reimplemented from Objet_U.
Definition at line 146 of file Deriv_.cpp.
References Objet_U::associer_(), and O_U_Ptr::get_O_U_Ptr_check().
{
  Objet_U * ptr = get_O_U_Ptr_check();
  assert(ptr != 0);
  int resu = ptr->associer_(objet);
  return resu;
}
void Deriv_::detach ()
Definition at line 77 of file Deriv_.cpp.
References O_U_Ptr::get_O_U_Ptr(), and O_U_Ptr::set_O_U_Ptr().
Referenced by Cond_lim::adopt(), Fluide_base::discretiser(), Milieu_base::discretiser(), Probleme_base::finir(), Zone::invalide_octree(), Simple::iterer_eqn(), readOn(), Solv_GCP::readOn(), Probleme_base::readOn(), Champ_Generique_Champ::reset(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), typer(), and mon_main::~mon_main().
{
  Objet_U * ptr = get_O_U_Ptr();
  if (ptr)
    delete ptr;
  set_O_U_Ptr((Objet_U *) 0);
}
virtual int Deriv_::duplique () const [pure virtual]
Implements O_U_Ptr.
Implemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
const Type_info * Deriv_::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 29 of file Deriv_.cpp.
const Type_info * Deriv_::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 29 of file Deriv_.cpp.
Sortie & Deriv_::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 37 of file Deriv_.cpp.
References finl, O_U_Ptr::get_O_U_Ptr(), and Objet_U::le_type().
{
  const Objet_U * objet = get_O_U_Ptr();
  if (objet)
    {
      os << objet->le_type() << finl;
      os << (*objet);
    }
  else
    {
      os << "vide" << finl;
    }
  return os;
}
Entree & Deriv_::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 52 of file Deriv_.cpp.
References detach(), Process::exit(), O_U_Ptr::set_O_U_Ptr(), and typer().
{
// Efface l'objet existant :
  detach();
// static pour le pas creer un Objet_U a chaque fois.
  static Nom nom_type;
  is >> nom_type;
  Objet_U * objet = (Objet_U*) 0;
  if (nom_type != "vide")
    {
      objet = typer(nom_type);
      if (! objet)
        {
          assert(0);
          exit();
        }
    }
// Appel a la methode virtuelle : met a jour le pointeur_
  set_O_U_Ptr(objet);
// Lecture de l'objet derive
  if (objet)
    is >> (*objet);
  return is;
}
Deriv_ & Deriv_::self_cast (Objet_U & r) [static]
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 29 of file Deriv_.cpp.
const Deriv_ & Deriv_::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 29 of file Deriv_.cpp.
Objet_U * Deriv_::typer (const char * nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
Definition at line 91 of file Deriv_.cpp.
References Cerr, detach(), Process::exit(), Nom::find(), finl, O_U_Ptr::get_info_ptr(), O_U_Ptr::get_O_U_Ptr(), Type_info::has_base(), Type_info::instance(), Type_info::instanciable(), Type_info::name(), Synonyme_info::org_name_(), O_U_Ptr::set_O_U_Ptr(), Synonyme_info::synonyme_info_from_name(), and Type_info::type_info_from_name().
Referenced by Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrix_tools::allocate_from_stencil(), Assembleur_P_VDF_Q4::assembler(), assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_EF::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Op_Diff_RotRot::assembler_matrice(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), Op_Dift_VEF_P1NCP1B_Face::associer(), Op_Diff_RotRot::associer(), Op_Moyenne::associer(), Op_Ecart_type::associer(), Op_Correlation::associer(), avancer_fichier(), Polygone::build_reduced(), Polyedre::build_reduced(), Champ_P1NC_implementation::Champ_P1NC_implementation(), Paroi_Knudsen_non_negligeable::completer(), Assembleur_P_VEFPreP1B::completer(), Op_Correlation::completer(), Assembleur_P_VDF::construire(), DomaineCutter::construire_faces_raccords_ssdom(), construire_matrice_implicite(), Zone::construit_octree(), corriger(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), Pb_MED::creer_champ(), Discretisation_base::creer_champ(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), PolyMAC_discretisation::creer_champ_vorticite(), EF_discretisation::creer_champ_vorticite(), CoviMAC_discretisation::creer_champ_vorticite(), Fluide_Dilatable_base::creer_champs_non_lus(), Domaine::creer_mes_domaines_frontieres(), Pb_Multiphase::creer_milieu(), VEF_discretisation::critere_Q(), VDF_discretisation::critere_Q(), PolyMAC_discretisation::critere_Q(), EF_discretisation::critere_Q(), CoviMAC_discretisation::critere_Q(), DecoupeBord::Decouper(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Domaine_dis::discretiser(), Navier_Stokes_std::discretiser_assembleur_pression(), Discr_inst::discretiser_champ_fonc_don(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), EF_discretisation::distance_paroi(), CoviMAC_discretisation::distance_paroi(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Simpler_Base::get_and_set_parametre_implicite(), Champ_Generique_Extraction::get_champ(), PolyMAC_discretisation::grad_T(), EF_discretisation::grad_T(), CoviMAC_discretisation::grad_T(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), PolyMAC_discretisation::h_conv(), EF_discretisation::h_conv(), CoviMAC_discretisation::h_conv(), mon_main::init_parallel(), Echange_contact_VDF::initialiser(), Echange_contact_PolyMAC::initialiser(), Typer_Lire::interpreter(), Lire::interpreter(), MaillerParallel::interpreter(), TroisDto2D::interpreter_(), Modif_bord_to_raccord::interpreter_(), Lire_Tgrid::interpreter_(), Lire_Ideas::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Interprete_bloc::interpreter_bloc(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Terme_Puissance_Thermique::lire_donnees(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Conduction::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Fluide_Dilatable_base::lire_motcle_non_standard(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), PlaqThVDF::mettre_a_jour(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), CoviMAC_discretisation::modifier_champ_tabule(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), CoviMAC_discretisation::proprietes_physiques_fluide_Ostwald(), Source_Forchheimer_VEF_Face::readOn(), Source_Darcy_VEF_Face::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Echange_contact_Correlation_VEF::readOn(), Source_Forchheimer_VDF_Face::readOn(), Source_Darcy_VDF_Face::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), PlaqThVDF::readOn(), Echange_contact_VDF::readOn(), Echange_contact_Correlation_VDF::readOn(), Modele_turbulence_hyd_nul::readOn(), Saturation::readOn(), Turbulence_paroi_scal::readOn(), Turbulence_paroi::readOn(), Modele_turbulence_scal::readOn(), Mod_turb_hyd::readOn(), Sortie_libre_Text_H_ext::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_pression_imposee::readOn(), Paroi_Knudsen_non_negligeable::readOn(), Entree_fluide_T_h_imposee::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Echange_contact_PolyMAC::readOn(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Champ_Fonc_reprise::readOn(), readOn(), Solveur_Lineaire_Std::readOn(), Pb_MED::readOn(), Pbc_MED::readOn(), SolveurSys::readOn(), Periodique::readOn(), Pave::readOn(), Symetrie::readOn(), Neumann_homogene::readOn(), Dirichlet_homogene::readOn(), Source_Scalaire_EF::readOn(), Assembleur_P_VEF::remplir(), Matrice_Bloc::remplir(), Matrice_Morse_Sym::renumerote(), VDF_discretisation::reynolds_maille(), Probleme_base::sauver(), Probleme_base::sauver_xyz(), Fluide_Dilatable_base::set_Cp(), VEF_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), Transformer::transformation_complete(), Zone::typer(), Format_Post::typer_direct(), Correlation::typer_lire(), VEF_1D::vitesse(), VEF_discretisation::vorticite(), VDF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), EF_discretisation::vorticite(), CoviMAC_discretisation::vorticite(), VEF_discretisation::y_plus(), VDF_discretisation::y_plus(), PolyMAC_discretisation::y_plus(), EF_discretisation::y_plus(), CoviMAC_discretisation::y_plus(), VEF_discretisation::zone_Cl_dis(), VDF_discretisation::zone_Cl_dis(), PolyMAC_discretisation::zone_Cl_dis(), VEFPreP1B::zone_Cl_dis(), EF_discretisation::zone_Cl_dis(), and CoviMAC_discretisation::zone_Cl_dis().
{
// Type_info du type demande
  const Type_info * type_info = Type_info::type_info_from_name(type);
// Type de base du DERIV:
  const Type_info& type_base = get_info_ptr();
  if ( get_O_U_Ptr())
    {
// Cerr<<"on avait deja typer ???"<<finl;
      detach();
    }
  Objet_U * instance = 0;
  if (type_info == 0)
    {
      const Synonyme_info* syn_info= Synonyme_info::synonyme_info_from_name(type);
      if (syn_info!=0)
        {
          return typer(syn_info->org_name_());
        }
      else
        {
          Cerr << "Error in Deriv_::typer_(const char* const type)\n";
          Cerr << type << " is not a type." << finl;
          Cerr << "Type required : derived from " << type_base.name() << finl;
          Cerr << finl;
          Cerr << type << " is not a recognized keyword." << finl;
          Cerr << "Check your data set." << finl;
          Nom nompb = type;
          if (nompb.find("TURBULENT")!=-1 )
            Cerr << "Since TRUST V1.8.0, turbulence models are in TrioCFD and not anymore in TRUST.\nTry using TrioCFD executable or contact trust support." << finl;
          exit();
        }
    }
  if (! type_info->instanciable())
    {
      Cerr << "Error in Deriv_::typer_(const char* const type)\n ";
      Cerr << type << " is not instanciable." << finl;
      assert(0);
      exit();
    }
  if (! type_info->has_base(&type_base))
    {
      Cerr << "Error in Deriv_::typer_(const char* const type)\n ";
      Cerr << type << " is not a subtype of " << type_base.name() << finl;
    }
  else
    {
// Cree une instance du type decrit dans type_info
      instance = type_info->instance();
    }
  set_O_U_Ptr(instance);
  return instance;
}
Member Data Documentation
const Type_info Deriv_::info_obj [static]
Reimplemented from O_U_Ptr.
Reimplemented in Deriv_Iterateur_Source_CoviMAC_base, Iterateur_Source_CoviMAC, Deriv_Elem_CoviMAC_base, Elem_CoviMAC, Deriv_Iterateur_Source_EF_base, Iterateur_Source_EF, Deriv_Elem_EF_base, Elem_EF, Deriv_Champ_Generique_Statistiques_base, Champ_Generique_Statistiques, Deriv_Assembleur_base, Assembleur, Deriv_Champ_base, Champ, Deriv_Champ_Don_base, Champ_Don, Deriv_Champ_Fonc_base, Champ_Fonc, Deriv_Champ_front_base, Champ_front, Deriv_Champ_Generique_base, Champ_Generique, Deriv_Champ_Inc_base, Champ_Inc, Deriv_Cond_lim_base, Cond_lim, Deriv_Loi_Fermeture_base, Deriv_Discretisation_base, Discretisation, Deriv_Equation_base, Equation, Deriv_Format_Post_base, Format_Post, Deriv_Parametre_equation_base, Parametre_equation, Deriv_Postraitement_base, Deriv_Schema_Temps_base, Schema_Temps, Deriv_Solveur_Implicite_Base, Solveur_Implicite, Deriv_Solveur_Masse_base, Solveur_Masse, Deriv_Source_base, Source, Deriv_Sous_zone_dis_base, Sous_zone_dis, Deriv_Zone_Cl_dis_base, Zone_Cl_dis, Deriv_Zone_dis_base, Zone_dis, Deriv_Partitionneur_base, Deriv_OctreeRoot, Deriv_Zone, Deriv_Elem_geom_base, Elem_geom, Deriv_Interpolation_IBM_base, Interpolation_IBM, Deriv_Raccord_base, Raccord, Deriv_MD_Vector_base, Deriv_UnaryFunction, Deriv_Matrice_Base, Matrice, Deriv_Precond_base, Precond, Deriv_SolvElem_base, SolvElem, Deriv_SolveurSys_base, SolveurSys, Deriv_Operateur_Conv_base, Operateur_Conv, Deriv_Operateur_Diff_base, Operateur_Diff, Deriv_Operateur_Div_base, Operateur_Div, Deriv_Operateur_Grad_base, Operateur_Grad, Integrale_tps_Champ, Integrale_tps_produit_champs, Deriv_Operateur_Statistique_tps_base, Operateur_Statistique_tps, Deriv_Comm_Group, Deriv_Entree_Fichier_base, Deriv_Sortie_Fichier_base, Deriv_Objet_U, Deriv_Iterateur_PolyMAC_base, Iterateur_PolyMAC, Deriv_Iterateur_Source_PolyMAC_base, Iterateur_Source_PolyMAC, Deriv_Elem_PolyMAC_base, Elem_PolyMAC, Deriv_EOS_Tools_base, EOS_Tools, Deriv_Loi_Etat_base, Loi_Etat, Deriv_EDO_Pression_th_base, EDO_Pression_th, Deriv_Modele_Permeabilite_base, Modele_Permeabilite, Deriv_Traitement_particulier_NS_base, Traitement_particulier_NS, Deriv_Mod_turb_hyd_base, Mod_turb_hyd, Deriv_Modele_turbulence_scal_base, Modele_turbulence_scal, Deriv_Turbulence_paroi_base, Turbulence_paroi, Deriv_Turbulence_paroi_scal_base, Turbulence_paroi_scal, Deriv_Correlation_base, Correlation, Deriv_Saturation_base, Saturation, Operateur_Evanescence, Deriv_Operateur_Evanescence_base, Deriv_Traitement_particulier_Solide_base, Traitement_particulier_Solide, Deriv_Iterateur_VDF_base, Iterateur_VDF, Deriv_Iterateur_Source_VDF_base, Iterateur_Source_VDF, Deriv_Iterateur_Source_VEF_base, Iterateur_Source_VEF, Deriv_Elem_VEF_base, and Elem_VEF.
Definition at line 42 of file Deriv_.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Deriv_.h
src/Kernel/Utilitaires/Deriv_.cpp