TRUST: Loi_horaire Class Reference
Loi_horaire Class Reference
#include <Loi_horaire.h>
Public Member Functions
Loi_horaire ()
~Loi_horaire ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
ArrOfDouble position (const double t, const double t0, const ArrOfDouble &position_a_t0)
ArrOfDouble vitesse (const double t, const ArrOfDouble &position_a_t)
void imprimer (const Schema_Temps_base &, const ArrOfDouble &)
void nommer (const Nom &un_nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Loi_horaire & self_cast (Objet_U &)
static const Loi_horaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void verifier_derivee (const double t)
void tester (const Schema_Temps_base &)
Private Attributes
Champ_Fonc_t position_
Champ_Fonc_t vitesse_
Champ_Fonc_t rotation_
Champ_Fonc_t derivee_rotation_
int verification_derivee_
int impr_
Nom nom_
Detailed Description
Definition at line 27 of file Loi_horaire.h.
Constructor & Destructor Documentation
Loi_horaire()
Loi_horaire::Loi_horaire ()
Definition at line 25 of file Loi_horaire.cpp.
~Loi_horaire()
Loi_horaire::~Loi_horaire ()
Definition at line 25 of file Loi_horaire.cpp.
Member Function Documentation
cree_instance()
Objet_U * Loi_horaire::cree_instance () static
Definition at line 25 of file Loi_horaire.cpp.
duplique()
int Loi_horaire::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Loi_horaire.cpp.
get_info()
const Type_info * Loi_horaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Loi_horaire.cpp.
imprimer()
void Loi_horaire::imprimer (const Schema_Temps_base & sch, const ArrOfDouble & coord_barycentre)
< * os=NULL;
< xG(t)
< Barycentre des noeuds de l'interface
Definition at line 323 of file Loi_horaire.cpp.
{
  if (Process::je_suis_maitre())
    {
// Ouverture du fichier
      Nom nom_fichier(nom_du_cas());
      nom_fichier+="_loi_horaire_";
      nom_fichier+=le_nom();
      nom_fichier+=".out";
      SFichier fic; //!< * os=NULL;
      struct stat f;
// On cree le fichier a la premiere impression avec l'en tete ou si le fichier n'existe pas
      if (stat(nom_fichier,&f) || (sch.nb_impr()==1 && !sch.pb_base().reprise_effectuee()))
        {
          tester(sch);
          fic.ouvrir(nom_fichier);
// Ecriture en tete
          fic << "# (xG,yG,...):Position du centre de gravite dont le mouvement est defini par la loi horaire " << le_nom() << finl;
          fic << "# (moy(xi),moy(yi),...):Position du barycentre des noeuds du maillage de l'interface." << finl;
          fic << "# Les trajectoires de ces 2 points doivent etre proches." << finl;
          fic << "# Pour visualiser dans gnuplot ces trajectoires, faire: " << finl;
          if (dimension==3)
            {
              fic << "# set param;splot '" << nom_fichier << "' using 2:3:4 with lines,'" << nom_fichier << "' using 5:6:7 with points" << finl;
              fic << "# Temps     xG(t)     yG(t)     zG(t)     moy(xi)   moy(yi)   moy(zi)" << finl;
            }
          else
            {
              fic << "# set param;plot '" << nom_fichier << "' using 2:3 with lines,'" << nom_fichier << "' using 4:5 with points" << finl;
              fic << "# Temps     xG(t)     yG(t)     moy(xi)   moy(yi)" << finl;
            }
        }
      else
        fic.ouvrir(nom_fichier,ios::app);
      fic.precision(sch.precision_impr());
      fic.setf(ios::scientific);
// Ecriture de t,xG(t),coord_barycentre
      double t=sch.temps_courant();
      fic << t;
      position_.me_calculer(t);
      for (int i=0; i<dimension; i++)
        fic << " " << position_.valeurs()(0,i);        //!< xG(t)
      for (int i=0; i<dimension; i++)
        fic << " " << coord_barycentre[i];                 //!< Barycentre des noeuds de l'interface
      fic << finl;
// Fermeture du fichier
      fic.close();
    }
}
References Sortie_Fichier_base::close(), Objet_U::dimension, finl, Process::je_suis_maitre(), le_nom(), Champ_Fonc_t::me_calculer(), Schema_Temps_base::nb_impr(), Objet_U::nom_du_cas(), nom_fichier(), Sortie_Fichier_base::ouvrir(), Schema_Temps_base::pb_base(), position_, Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Probleme_base::reprise_effectuee(), Sortie_Fichier_base::setf(), Schema_Temps_base::temps_courant(), tester(), and Champ_Don_base::valeurs().
info()
const Type_info * Loi_horaire::info () static
Definition at line 25 of file Loi_horaire.cpp.
le_nom()
const Nom & Loi_horaire::le_nom () const inline override virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 40 of file Loi_horaire.h.
  {
    return nom_;
  };
References nom_.
Referenced by imprimer(), readOn(), and verifier_derivee().
nommer()
void Loi_horaire::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
Reimplemented from Objet_U.
Definition at line 36 of file Loi_horaire.h.
  {
    nom_ = un_nom;
  };
References nom_.
position()
ArrOfDouble Loi_horaire::position (const double t, const double t0, const ArrOfDouble & position_a_t0)
< xM(t0)
< xG(t0)
< xM(t0)-xG(t0)
< R(t0)
< R-1(t0)(xM(t0)-xG(t0))
< R(t)
< R(t)R-1(t0)(xM(t0)-xG(t0))
< xG(t)
< xM(t) = xG(t)+R(t)R-1(t0)(xM(t0)-xG(t0))
Definition at line 208 of file Loi_horaire.cpp.
{
  ArrOfDouble xMt(xMt0);                //!< xM(t0)
  position_.me_calculer(t0);                //!< xG(t0)
  xMt -= position_.valeurs();                //!< xM(t0)-xG(t0)
  rotation_.me_calculer(t0);                //!< R(t0)
  inverse(rotation_.valeurs(),xMt);        //!< R-1(t0)(xM(t0)-xG(t0))
  rotation_.me_calculer(t);                //!< R(t)
  multiplie(rotation_.valeurs(),xMt);        //!< R(t)R-1(t0)(xM(t0)-xG(t0))
  position_.me_calculer(t);                //!< xG(t)
  xMt += position_.valeurs();                //!< xM(t) = xG(t)+R(t)R-1(t0)(xM(t0)-xG(t0))
  return xMt;
}
References inverse(), Champ_Fonc_t::me_calculer(), multiplie(), position_, rotation_, and Champ_Don_base::valeurs().
Referenced by tester().
printOn()
Sortie & Loi_horaire::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 41 of file Loi_horaire.cpp.
{
  return os;
}
readOn()
Entree & Loi_horaire::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< Vecteur position
< Vecteur vitesse
< Matrice de passage
< Derivee matrice de passage
Reimplemented from Objet_U.
Definition at line 59 of file Loi_horaire.cpp.
{
// Initialisations
  verification_derivee_=1;
  impr_=1;
  EChaine x(dimension==3?"3 0. 0. 0.":"2 0. 0.");
  x >> position_;
  EChaine v(dimension==3?"3 0. 0. 0.":"2 0. 0.");
  v >> vitesse_;
  EChaine r(dimension==3?"9 1. 0. 0. 0. 1. 0. 0. 0. 1.":"4 1. 0. 0. 1.");
  r >> rotation_;
  EChaine drdt(dimension==3?"9 0. 0. 0. 0. 0. 0. 0. 0. 0.":"4 0. 0. 0. 0.");
  drdt >> derivee_rotation_;
// Lecture de jeu de donnees
  Param param(que_suis_je());
  param.ajouter("position",&position_);                                //!< Vecteur position
  param.ajouter("vitesse",&vitesse_);                //!< Vecteur vitesse
  param.ajouter("rotation",&rotation_);                                        //!< Matrice de passage
  param.ajouter("derivee_rotation",&derivee_rotation_);                        //!< Derivee matrice de passage
  param.ajouter("verification_derivee",&verification_derivee_);
  param.ajouter("impr",&impr_);
  param.lire_avec_accolades_depuis(is);
// Verification de ce qui a ete lu: (pourquoi le_nom() retourne neant ???
  if (position_.valeurs().size_array()!=dimension)
    {
      Cerr << "The position vector of the schedule law " << le_nom() << " must have " << dimension << " components." << finl;
      Process::exit();
    }
  if (vitesse_.valeurs().size_array()!=dimension)
    {
      Cerr << "The velocity vector of the schedule law " << le_nom() << " must have " << dimension << " components." << finl;
      Process::exit();
    }
  if (rotation_.valeurs().size_array()!=dimension*dimension)
    {
      Cerr << "The matrix rotation of the schedule law " << le_nom() << " must be read" << finl;
      Cerr << "as a vector of " << dimension*dimension << " components." << finl;
      Process::exit();
    }
  if (derivee_rotation_.valeurs().size_array()!=dimension*dimension)
    {
      Cerr << "The matrix derivee_rotation of the schedule law " << le_nom() << " must be read" << finl;
      Cerr << "as a vector of " << dimension*dimension << " components." << finl;
      Process::exit();
    }
  return is;
}
References Param::ajouter(), Cerr, derivee_rotation_, Objet_U::dimension, Process::exit(), finl, impr_, le_nom(), Param::lire_avec_accolades_depuis(), position_, Objet_U::que_suis_je(), rotation_, TRUSTArray< _TYPE_ >::size_array(), Champ_Don_base::valeurs(), verification_derivee_, and vitesse_.
self_cast() [1/2]
const Loi_horaire & Loi_horaire::self_cast (const Objet_U & r) static
Definition at line 25 of file Loi_horaire.cpp.
self_cast() [2/2]
Loi_horaire & Loi_horaire::self_cast (Objet_U & r) static
Definition at line 25 of file Loi_horaire.cpp.
taille_memoire()
unsigned Loi_horaire::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Loi_horaire.cpp.
tester()
void Loi_horaire::tester (const Schema_Temps_base & sch) private
Definition at line 375 of file Loi_horaire.cpp.
{
// Test de produit et d'inversion de matrice
  for (int dim=2; dim<=3; dim++)
    {
      DoubleTab mat(1,dim*dim);
      for (int i=0; i<dim; i++)
        for (int j=0; j<dim; j++)
          mat(0,i*dim+j)=(i>j?1+i+j:-2*j);
      ArrOfDouble vect(dim);
      for (int i=0; i<dim; i++)
        vect[i]=i;
      ArrOfDouble tmp(vect);
      multiplie(mat,vect);
      inverse(mat,vect);
      for (int i=0; i<dim; i++)
        if (!est_egal(tmp[i],vect[i]))
          {
            Cerr << "Loi_horaire::inverse is not validated for dim=" << dim << finl;
            Cerr << "A=" << mat << finl;
            Cerr << "x=" << tmp << finl;
            Cerr << "Inv(A)Ax=" << vect << finl;
            Cerr << "Contact TRUST support." << finl;
            Process::exit();
          }
    }
// Verification entre tinit et tmax
  double tinit=sch.temps_init();
  double tmax=sch.temps_max();
// Test des derivees:
  int n=100;
  for (int i=1; i<n; i++)
    {
      double temps=tinit+(tmax-tinit)*(i+1)/n;
// Cerr << "Verification a t=" << temps << finl;
      verifier_derivee(temps);
    }
// Test de position et vitesse:
  double t=0.5*(tinit+tmax);
  double eps=1e-8;
  double dt=eps*t;
  ArrOfDouble pos(dimension);
  pos[0]=dimension*2;
  pos[1]=dimension*3;
  if (dimension==3) pos[2]=-dimension;
// Verification que position(t,t,pos)=pos
  ArrOfDouble tmp(position(t,t,pos));
  for (int i=0; i<dimension; i++)
    if (!est_egal(tmp[i],pos[i]))
      {
        Cerr << "Loi_horaire::position is not validated for pos=position(t,t,pos):" << finl;
        Cerr << pos << finl;
        Cerr << tmp << finl;
        Cerr << "Contact TRUST support." << finl;
        Process::exit();
      }
// Verification que vitesse(t,pos)~(position(t+dt,t,pos)-pos)/dt;
  tmp=position(t+dt,t,pos);
  tmp-=pos;
  tmp/=dt;
  ArrOfDouble vit(vitesse(t,pos));
  ArrOfDouble relative_error(vit);
  relative_error-=tmp;
  relative_error/=(norme_array(tmp)!=0?norme_array(tmp):1);
  for (int i=0; i<dimension; i++)
    if (!est_egal(relative_error[i],0,0.001))
      {
        Cerr << "Loi_horaire::position is not validated for velocity(t,pos):" << finl;
        Cerr << "t=" << t << finl;
        Cerr << "dt=" << dt << finl;
        Cerr << "vit=" << vit << finl;
        Cerr << "tmp=" << tmp << finl;
        Cerr << "relative_error=" << relative_error << finl;
        Cerr << "Contact TRUST support." << finl;
        Process::exit();
      }
  Cerr << "Loi_horaire::tester() OK" << finl;
}
References Cerr, Objet_U::dimension, est_egal(), Process::exit(), finl, inverse(), multiplie(), norme_array(), position(), Schema_Temps_base::temps_init(), Schema_Temps_base::temps_max(), verifier_derivee(), and vitesse().
Referenced by imprimer().
verifier_derivee()
void Loi_horaire::verifier_derivee (const double t) private
< xG(t+dt)
< xG(t+dt)
< xG(t)
< xG(t+dt)-xG(t)
< vG(t)
< xG(t+dt)-xG(t)-dt*vG(t) Evaluation d'un seuil avec la derivee seconde xG'' cad vG'
< vG(t+dt)
< vG(t)
< ~vG'(t)*dt*dt
< R(t+dt)
< R(t+dt)
< R(t)
< R(t+dt)-R(t)
< R'(t)
< R(t+dt)-R(t)-dt*R'(t) Evaluation d'un seuil avec la derivee seconde de R cad R''
< R'(t+dt)
< R'(t)
< R'(t+dt)-R'(t)
< ~R''(t)*dt*dt
Definition at line 250 of file Loi_horaire.cpp.
{
  if (verification_derivee_)
    {
      double dt=0.001*t;
      DoubleVect err_t(position_.valeurs());
      position_.me_calculer(t+dt);                        //!< xG(t+dt)
      err_t=position_.valeurs();                        //!< xG(t+dt)
      position_.me_calculer(t);                                //!< xG(t)
      err_t-=position_.valeurs();                        //!< xG(t+dt)-xG(t)
      vitesse_.me_calculer(t);                                //!< vG(t)
      err_t.ajoute(-dt, vitesse_.valeurs());                        //!< xG(t+dt)-xG(t)-dt*vG(t) Evaluation d'un seuil avec la derivee seconde xG'' cad vG'
//
      ArrOfDouble seuil_t(position_.valeurs());
      vitesse_.me_calculer(t+dt);                        //!< vG(t+dt)
      seuil_t=vitesse_.valeurs();
      vitesse_.me_calculer(t);                                //!< vG(t)
      seuil_t-=vitesse_.valeurs();
      seuil_t*=100*dt;                                        //!< ~vG'(t)*dt*dt
      int n=err_t.size_array();
      for (int i=0; i<n; i++)
        {
          double seuil=std::fabs(seuil_t[i]);
          if (!est_egal(seuil,0) && std::fabs(err_t(i))>seuil)
            {
              if (Process::je_suis_maitre())
                {
                  Cerr << "At time " << t << ", inconsistency in the schedule law " << le_nom() << finl;
                  Cerr << "The expression of the component " << i << " of velocity does not appear" << finl;
                  Cerr << "to be the time derivative of the position expression." << finl;
                  Cerr << "Verify the expressions of this schedule law in your data set." << finl;
                  Cerr << "If the expressions are correct after all, add the option 'verification_derivee 0'" << finl;
                  Cerr << "in the law to not to make this verification." << finl;
                }
              Process::exit();
            }
        }
      DoubleTab err_r(rotation_.valeurs());
      rotation_.me_calculer(t+dt);                        //!< R(t+dt)
      err_r=rotation_.valeurs();                        //!< R(t+dt)
      rotation_.me_calculer(t);                                //!< R(t)
      err_r-=rotation_.valeurs();                        //!< R(t+dt)-R(t)
      derivee_rotation_.me_calculer(t);                        //!< R'(t)
      err_r.ajoute(-dt, derivee_rotation_.valeurs());                //!< R(t+dt)-R(t)-dt*R'(t) Evaluation d'un seuil avec la derivee seconde de R cad R''
//
      DoubleTab seuil_r(rotation_.valeurs());
      derivee_rotation_.me_calculer(t+dt);                //!< R'(t+dt)
      seuil_r=derivee_rotation_.valeurs();
      derivee_rotation_.me_calculer(t);                        //!< R'(t)
      seuil_r-=derivee_rotation_.valeurs();                //!< R'(t+dt)-R'(t)
      seuil_r*=100*dt;                                        //!< ~R''(t)*dt*dt
      int ni=err_r.dimension(0);
      int nj=err_r.dimension(1);
      for (int i=0; i<ni; i++)
        for (int j=0; j<nj; j++)
          {
            double seuil=std::fabs(seuil_r(i,j));
            if (!est_egal(seuil,0) && std::fabs(err_r(i,j))>seuil)
              {
                if (Process::je_suis_maitre())
                  {
                    Cerr << "At time " << t << ", inconsistency in the schedule law " << le_nom() << finl;
                    Cerr << "The expression of the component " << i*ni+j << " of derivee_rotation does not appear" << finl;
                    Cerr << "to be the time derivative of the rotation expression." << finl;
                    Cerr << "Verify the expressions of this schedule law in your data set" << finl;
                    Cerr << "or add the option 'verification_derivee 0' in this law." << finl;
                  }
                Process::exit();
              }
          }
    }
}
References TRUSTVect< _TYPE_ >::ajoute(), Cerr, derivee_rotation_, TRUSTTab< _TYPE_ >::dimension(), est_egal(), Process::exit(), finl, Process::je_suis_maitre(), le_nom(), Champ_Fonc_t::me_calculer(), position_, rotation_, TRUSTArray< _TYPE_ >::size_array(), Champ_Don_base::valeurs(), verification_derivee_, and vitesse_.
Referenced by tester().
vitesse()
ArrOfDouble Loi_horaire::vitesse (const double t, const ArrOfDouble & position_a_t)
< xM(t)
< xG(t)
< xM(t)-xG(t)
< R(t)
< R-1(t)(xM(t)-xG(t))
< R'(t)
< R'(t)R-1(t)(xM(t)-xG(t))
< vG(t)
< vM(t) = vG(t)+R'(t)R-1(t)(xM(t)-xG(t))
Definition at line 232 of file Loi_horaire.cpp.
{
  ArrOfDouble vMt(xMt);                        //!< xM(t)
  position_.me_calculer(t);                        //!< xG(t)
  vMt -= position_.valeurs();                        //!< xM(t)-xG(t)
  rotation_.me_calculer(t);                        //!< R(t)
  inverse(rotation_.valeurs(),vMt);                //!< R-1(t)(xM(t)-xG(t))
  derivee_rotation_.me_calculer(t);                //!< R'(t)
  multiplie(derivee_rotation_.valeurs(),vMt);        //!< R'(t)R-1(t)(xM(t)-xG(t))
  vitesse_.me_calculer(t);                        //!< vG(t)
  vMt += vitesse_.valeurs();                        //!< vM(t) = vG(t)+R'(t)R-1(t)(xM(t)-xG(t))
  return vMt;
}
References derivee_rotation_, inverse(), Champ_Fonc_t::me_calculer(), multiplie(), position_, rotation_, Champ_Don_base::valeurs(), and vitesse_.
Referenced by tester().
Member Data Documentation
derivee_rotation_
Champ_Fonc_t Loi_horaire::derivee_rotation_ private
Definition at line 51 of file Loi_horaire.h.
Referenced by readOn(), verifier_derivee(), and vitesse().
impr_
int Loi_horaire::impr_ private
Definition at line 53 of file Loi_horaire.h.
Referenced by readOn().
info_obj
const Type_info Loi_horaire::info_obj static
Definition at line 30 of file Loi_horaire.h.
nom_
Nom Loi_horaire::nom_ private
Definition at line 54 of file Loi_horaire.h.
Referenced by le_nom(), and nommer().
position_
Champ_Fonc_t Loi_horaire::position_ private
Definition at line 48 of file Loi_horaire.h.
Referenced by imprimer(), position(), readOn(), verifier_derivee(), and vitesse().
rotation_
Champ_Fonc_t Loi_horaire::rotation_ private
Definition at line 50 of file Loi_horaire.h.
Referenced by position(), readOn(), verifier_derivee(), and vitesse().
verification_derivee_
int Loi_horaire::verification_derivee_ private
Definition at line 52 of file Loi_horaire.h.
Referenced by readOn(), and verifier_derivee().
vitesse_
Champ_Fonc_t Loi_horaire::vitesse_ private
Definition at line 49 of file Loi_horaire.h.
Referenced by readOn(), verifier_derivee(), and vitesse().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Loi_horaire.h
src/Kernel/Framework/Loi_horaire.cpp