TRUST: Frottement_interfacial_Tomiyama Class Reference
Frottement_interfacial_Tomiyama Class Reference
classe Frottement_interfacial_Tomiyama
coefficients de frottement interfacial d'un ecoulement a bulles
#include <Frottement_interfacial_Tomiyama.h>
Public Member Functions
Frottement_interfacial_Tomiyama ()
~Frottement_interfacial_Tomiyama ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void coefficient (const DoubleTab &alpha, const DoubleTab &p, const DoubleTab &T, const DoubleTab &rho, const DoubleTab &mu, const DoubleTab &sigma, double Dh, const DoubleTab &ndv, const DoubleTab &d_bulles, DoubleTab &coeff) const override
void completer () override
Public Member Functions inherited from Frottement_interfacial_base
Frottement_interfacial_base ()
~Frottement_interfacial_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void coefficient (const DoubleTab &alpha, const DoubleTab &p, const DoubleTab &T, const DoubleTab &rho, const DoubleTab &mu, const DoubleTab &sigma, double Dh, const DoubleTab &ndv, const DoubleTab &d_bulles, DoubleTab &coeff) const =0
Public Member Functions inherited from Correlation_base
Correlation_base ()
~Correlation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & lire (Entree &is)
void associer_pb (const Probleme_base &pb)
virtual void mettre_a_jour (double temps)
virtual void completer ()
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Frottement_interfacial_Tomiyama & self_cast (Objet_U &)
static const Frottement_interfacial_Tomiyama & self_cast (const Objet_U &)
Static Public Member Functions inherited from Frottement_interfacial_base
static const Type_info * info ()
static Frottement_interfacial_base & self_cast (Objet_U &)
static const Frottement_interfacial_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Correlation_base
static const Type_info * info ()
static Correlation_base & self_cast (Objet_U &)
static const Correlation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Frottement_interfacial_base
static const Type_info info_obj
Static Public Attributes inherited from Correlation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double g_ =9.81
int contamination_ = 0
contamination 0 for pure system, 1 for moderate contamination, 2 for high contamination
int n_l = -1
Protected Attributes inherited from Correlation_base
Ref_Probleme_base pb_
Champs_compris champs_compris_
Detailed Description
classe Frottement_interfacial_Tomiyama
coefficients de frottement interfacial d'un ecoulement a bulles
Definition at line 27 of file Frottement_interfacial_Tomiyama.h.
Constructor & Destructor Documentation
Frottement_interfacial_Tomiyama()
Frottement_interfacial_Tomiyama::Frottement_interfacial_Tomiyama ()
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
~Frottement_interfacial_Tomiyama()
Frottement_interfacial_Tomiyama::~Frottement_interfacial_Tomiyama ()
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
Member Function Documentation
coefficient()
void Frottement_interfacial_Tomiyama::coefficient (const DoubleTab & alpha, const DoubleTab & p, const DoubleTab & T, const DoubleTab & rho, const DoubleTab & mu, const DoubleTab & sigma, double Dh, const DoubleTab & ndv, const DoubleTab & d_bulles, DoubleTab & coeff) const override virtual
Implements Frottement_interfacial_base.
Definition at line 56 of file Frottement_interfacial_Tomiyama.cpp.
{
  int N = ndv.dimension(0);
  coeff = 0;
  for (int k = 0; k < N; k++)
    if (k!=n_l)
      {
        double Re = rho(n_l) * ndv(n_l,k) * d_bulles(k)/mu(n_l) + 1.e-6;
        double Eo = g_ * std::abs(rho(n_l)-rho(k)) * d_bulles(k)*d_bulles(k)/sigma(n_l,k);
        double Cd = -1;
        if (contamination_==0) Cd = std::max( std::min( 16./Re*(1+0.15*std::pow(Re, 0.687)) , 48./Re )   , 8.*Eo/(3.*(Eo+4.)));
        if (contamination_==1) Cd = std::max( std::min( 24./Re*(1+0.15*std::pow(Re, 0.687)) , 72./Re )   , 8.*Eo/(3.*(Eo+4.)));
        if (contamination_==2) Cd = std::max(           24./Re*(1+0.15*std::pow(Re, 0.687))              , 8.*Eo/(3.*(Eo+4.)));
        coeff(k, n_l, 1) = 3./4.*Cd/d_bulles(k) * alpha(k) * rho(n_l);
        coeff(k, n_l, 0) = coeff(k, n_l, 1) * ndv(n_l,k);
        coeff(n_l, k, 0) =  coeff(k, n_l, 0);
        coeff(n_l, k, 1) =  coeff(k, n_l, 1);
      }
}
References coeff, contamination_, TRUSTTab< _TYPE_ >::dimension(), g_, and n_l.
completer()
void Frottement_interfacial_Tomiyama::completer (void) override virtual
Reimplemented from Correlation_base.
Definition at line 50 of file Frottement_interfacial_Tomiyama.cpp.
{
  if (!pb_->has_champ("diametre_bulles")) Process::exit("Frottement_interfacial_Tomiyama : there must be a bubble diameter field !");
}
References Process::exit(), Probleme_base::has_champ(), and Correlation_base::pb_.
cree_instance()
Objet_U * Frottement_interfacial_Tomiyama::cree_instance () static
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
duplique()
int Frottement_interfacial_Tomiyama::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
get_info()
const Type_info * Frottement_interfacial_Tomiyama::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
info()
const Type_info * Frottement_interfacial_Tomiyama::info () static
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
printOn()
Sortie & Frottement_interfacial_Tomiyama::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 23 of file Frottement_interfacial_Tomiyama.cpp.
{
  return os;
}
readOn()
Entree & Frottement_interfacial_Tomiyama::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Frottement_interfacial_base.
Definition at line 28 of file Frottement_interfacial_Tomiyama.cpp.
{
  Param param(que_suis_je());
  param.ajouter("constante_gravitation", &g_);
  param.ajouter("contamination", &contamination_);
  param.lire_avec_accolades_depuis(is);
  if (! ((contamination_==0)|(contamination_==1)|(contamination_==2) )) Process::exit("Frottement_interfacial_Tomiyama : only 3 contamination levels exist : 0,1,2 !");
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, pb_.valeur()) ? &ref_cast(Pb_Multiphase, pb_.valeur()) : NULL;
  if (!pbm || pbm->nb_phases() == 1) Process::exit(que_suis_je() + " : not needed for single-phase flow!");
  for (int n = 0; n < pbm->nb_phases(); n++) //recherche de n_l, n_g : phase {liquide,gaz}_continu en priorite
    if (pbm->nom_phase(n).debute_par("liquide") && (n_l < 0 || pbm->nom_phase(n).finit_par("continu")))  n_l = n;
  if (n_l < 0) Process::exit(que_suis_je() + " : liquid phase not found!");
  for (int k = 0; k < pbm->nb_phases(); k++)
    if (k != n_l)
      if (!(ref_cast(Milieu_composite, pbm->milieu()).has_interface(n_l, k))) Process::exit("Frottement_interfacial_Tomiyama : one must define an interface and have a surface tension !");
  return is;
}
References Param::ajouter(), contamination_, Nom::debute_par(), Process::exit(), g_, Param::lire_avec_accolades_depuis(), Probleme_base::milieu(), n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), ref_cast, sub_type, and Ref_Probleme_base::valeur().
self_cast() [1/2]
const Frottement_interfacial_Tomiyama & Frottement_interfacial_Tomiyama::self_cast (const Objet_U & r) static
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
self_cast() [2/2]
Frottement_interfacial_Tomiyama & Frottement_interfacial_Tomiyama::self_cast (Objet_U & r) static
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
taille_memoire()
unsigned Frottement_interfacial_Tomiyama::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Frottement_interfacial_Tomiyama.cpp.
Member Data Documentation
contamination_
int Frottement_interfacial_Tomiyama::contamination_ = 0 protected
contamination 0 for pure system, 1 for moderate contamination, 2 for high contamination
Definition at line 39 of file Frottement_interfacial_Tomiyama.h.
Referenced by coefficient(), and readOn().
g_
double Frottement_interfacial_Tomiyama::g_ =9.81 protected
Definition at line 38 of file Frottement_interfacial_Tomiyama.h.
Referenced by coefficient(), and readOn().
info_obj
const Type_info Frottement_interfacial_Tomiyama::info_obj static
Definition at line 29 of file Frottement_interfacial_Tomiyama.h.
n_l
int Frottement_interfacial_Tomiyama::n_l = -1 protected
Definition at line 40 of file Frottement_interfacial_Tomiyama.h.
Referenced by coefficient(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Frottement_interfacial_Tomiyama.h
src/ThHyd/Multiphase/Correlations/Frottement_interfacial_Tomiyama.cpp