TRUST: Champ_Fonc_Q1_CoviMAC Class Reference
Champ_Fonc_Q1_CoviMAC Class Reference
#include <Champ_Fonc_Q1_CoviMAC.h>
Public Member Functions
Champ_Fonc_Q1_CoviMAC ()
~Champ_Fonc_Q1_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Zone_CoviMAC & zone_CoviMAC () const
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
int imprime (Sortie &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees
Sauvegarder sur un flot de sortie.
virtual void mettre_a_jour (double)
Mise a jour en temps du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_Q1_CoviMAC & self_cast (Objet_U &)
static const
Champ_Fonc_Q1_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_VF la_zone_VF
Detailed Description
Definition at line 31 of file Champ_Fonc_Q1_CoviMAC.h.
Constructor & Destructor Documentation
Champ_Fonc_Q1_CoviMAC::Champ_Fonc_Q1_CoviMAC ()
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
Champ_Fonc_Q1_CoviMAC::~Champ_Fonc_Q1_CoviMAC ()
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
Member Function Documentation
void Champ_Fonc_Q1_CoviMAC::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Returns:
z_dis
Signification: la zone discretise
Contraintes:
Implements Champ_Fonc_base.
Definition at line 77 of file Champ_Fonc_Q1_CoviMAC.cpp.
References la_zone_VF, and ref_cast.
{
  la_zone_VF=ref_cast(Zone_VF, z_dis);
}
Objet_U * Champ_Fonc_Q1_CoviMAC::cree_instance () [static]
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
int Champ_Fonc_Q1_CoviMAC::duplique () const [virtual]
Implements Champ_Fonc_Q1_base.
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
const Type_info * Champ_Fonc_Q1_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
int Champ_Fonc_Q1_CoviMAC::imprime (Sortie & os, int ncomp) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Sauvegarder sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Champ_Don_base.
Definition at line 105 of file Champ_Fonc_Q1_CoviMAC.cpp.
References Domaine::coord_sommets(), Cout, Objet_U::dimension, Zone::domaine(), finl, Field_base::nb_compo_, Domaine::nb_som(), Champ_Don_base::valeurs(), Zone_dis_base::zone(), and zone_dis_base().
{
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& zone = zone_dis.zone();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  const int nb_som = zone.domaine().nb_som();
  const DoubleTab& val = valeurs();
  int som;
  os << nb_som << finl;
  for (som=0; som<nb_som; som++)
    {
      if (dimension==3)
        os << coord(som,0) << " " << coord(som,1) << " " << coord(som,2) << " " ;
      if (dimension==2)
        os << coord(som,0) << " " << coord(som,1) << " " ;
      if (nb_compo_ == 1)
        os << val(som) << finl;
      else
        os << val(som,ncomp) << finl;
    }
  os << finl;
  Cout << "Champ_Fonc_Q1_CoviMAC::imprime FIN >>>>>>>>>> " << finl;
  return 1;
}
const Type_info * Champ_Fonc_Q1_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
void Champ_Fonc_Q1_CoviMAC::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Implements Champ_Fonc_base.
Definition at line 100 of file Champ_Fonc_Q1_CoviMAC.cpp.
{
  Champ_Fonc_base::mettre_a_jour(t);
}
Sortie & Champ_Fonc_Q1_CoviMAC::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 33 of file Champ_Fonc_Q1_CoviMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Fonc_Q1_CoviMAC::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 41 of file Champ_Fonc_Q1_CoviMAC.cpp.
{
  return s ;
}
const Champ_Fonc_Q1_CoviMAC & Champ_Fonc_Q1_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
Champ_Fonc_Q1_CoviMAC & Champ_Fonc_Q1_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
unsigned Champ_Fonc_Q1_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Champ_Fonc_Q1_CoviMAC.cpp.
const Zone_CoviMAC & Champ_Fonc_Q1_CoviMAC::zone_CoviMAC () const
Returns:
la_zone_CoviMAC_P1.valeur()
Signification:
Contraintes:
Definition at line 95 of file Champ_Fonc_Q1_CoviMAC.cpp.
References la_zone_VF, ref_cast, and Ref_Zone_VF::valeur().
{
  return ref_cast(Zone_CoviMAC, la_zone_VF.valeur());
}
const Zone_dis_base & Champ_Fonc_Q1_CoviMAC::zone_dis_base () const [virtual]
Implements Champ_Fonc_base.
Definition at line 60 of file Champ_Fonc_Q1_CoviMAC.cpp.
References la_zone_VF, and Ref_Zone_VF::valeur().
Referenced by imprime().
{
  return la_zone_VF.valeur();
}
Member Data Documentation
const Type_info Champ_Fonc_Q1_CoviMAC::info_obj [static]
Reimplemented from Champ_Fonc_Q1_base.
Definition at line 33 of file Champ_Fonc_Q1_CoviMAC.h.
Ref_Zone_VF Champ_Fonc_Q1_CoviMAC::la_zone_VF [protected]
Definition at line 44 of file Champ_Fonc_Q1_CoviMAC.h.
Referenced by associer_zone_dis_base(), zone_CoviMAC(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/CoviMAC/Champs/Champ_Fonc_Q1_CoviMAC.h
src/CoviMAC/Champs/Champ_Fonc_Q1_CoviMAC.cpp