TRUST: Masse_Multiphase Class Reference
Masse_Multiphase Class Reference
classe Masse_Multiphase
Cas particulier de Convection_Diffusion_std pour un fluide quasi conpressible
quand le scalaire subissant le transport est la fraction massique
#include <Masse_Multiphase.h>
Public Member Functions
~Masse_Multiphase ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Masse_Multiphase ()
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
void associer_fluide (const Fluide_base &)
Associe un fluide de type Fluide_base a l'equation.
const Champ_Inc & inconnue () const override
Renvoie le champ inconnue representant l'inconnue (T ou H)
(version const)
Champ_Inc & inconnue () override
Renvoie le champ inconnue representant l'inconnue (T ou H)
void discretiser () override
Discretise l'equation.
const Milieu_base & milieu () const override
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
(version const)
const Fluide_base & fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Fluide_base & fluide ()
Renvoie le fluide incompressible associe a l'equation.
Milieu_base & milieu () override
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
void associer_milieu_base (const Milieu_base &) override
Associe un milieu physique a l'equation,
le milieu est en fait caste en Fluide_base.
void completer () override
Associe l inconnue de l equation a la loi d etat,.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void dimensionner_matrice_sans_mem (Matrice_Morse &matrice) override
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) override
std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const override
const Motcle & domaine_application () const override
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Public Member Functions inherited from Convection_Diffusion_std
Convection_Diffusion_std ()
~Convection_Diffusion_std () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &titi) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int nombre_d_operateurs () const override
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
const Operateur & operateur (int) const override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Operateur & operateur (int) override
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
void associer_vitesse (const Champ_base &)
Associe la vitesse transportante a l'equation.
const Champ_Inc_base & vitesse_transportante () const
Renvoie une reference sur le champ representant
la vitesse transportante.
const Champ_Inc & inconnue () const override=0
Champ_Inc & inconnue () override=0
virtual const Champ_Don & diffusivite_pour_transport () const
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
virtual const Champ_base & vitesse_pour_transport () const
int sauvegarder_base (Sortie &) const
int reprendre_base (Entree &)
Public Member Functions inherited from Equation_base
Equation_base ()
~Equation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Methode appelee lorsqu'on cree l'instance de l'objet dans
le jeu de donnees (Interprete::ajouter)
virtual void avancer (int i=1)
virtual void reculer (int i=1)
virtual int nombre_d_operateurs () const =0
virtual int nombre_d_operateurs_tot () const
virtual const Operateur & operateur (int) const =0
virtual Operateur & operateur (int)=0
virtual const Operateur & operateur_fonctionnel (int) const
virtual Operateur & operateur_fonctionnel (int)
virtual const Champ_Inc & inconnue () const =0
virtual Champ_Inc & inconnue ()=0
virtual void associer_milieu_base (const Milieu_base &)=0
virtual const Milieu_base & milieu () const =0
virtual Milieu_base & milieu ()=0
int sauvegarder (Sortie &) const override
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
int reprendre (Entree &) override
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM]
[ON LIT L'INCONNUE]
Voir Champ_Inc::reprendre(Entree&)
int limpr () const
Demande au schema en temps si il faut effectuer une impression.
Renvoie 1 si il faut effectuer une impression.
Appel simple a Schema_Temps_base::limpr()
virtual void imprimer (Sortie &os) const
Imprime les operateurs de l'equation si le schema en temps
indique que c'est necessaire.
[SI limpr() ALORS impr(os)].
virtual int impr (Sortie &os) const
Imprime les operateurs de l'equation sur un flot de sortie,
de facon inconditionnelle.
appelle Operateur_base::impr(os)
virtual void associer_milieu_equation ()
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
Returns the time derivative of the unknown I of the equation:
dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0)
Out: derivee contains dI/dt.
virtual DoubleTab & derivee_en_temps_inco_transport (DoubleTab &derivee)
virtual DoubleTab & corriger_derivee_expl (DoubleTab &)
virtual DoubleTab & corriger_derivee_impl (DoubleTab &)
virtual void mettre_a_jour (double temps)
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre.
Elle met aussi a jour les proprietes du milieu.
virtual void abortTimeStep ()
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne,
par exemple parce que le calcul a diverge.
Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
virtual void valider_iteration ()
virtual int preparer_calcul ()
Tout ce qui ne depend pas des autres problemes eventuels.
virtual bool initTimeStep (double dt)
Allocation et initialisation de l'inconnue et des CLs
jusqu'a present+dt.
+ autres initialisations pour les calculs sur le prochain
pas de temps : operateurs, solveur_masse.
virtual bool updateGivenFields ()
virtual void discretiser ()
Discretise l'equation.
Type la zone_Cl_dis, la formatte, l'associe a l'equation.
Type le solveur masse, lui associe la zone discretisee et
la zone des conditions aux limites discretisees.
virtual void associer_pb_base (const Probleme_base &)
S'associe au Probleme passe en parametre.
Associe egalement les sources, les operateurs et le solveur
de masse a l'equation.
virtual void completer ()
Complete la construction (initialisation) des objets associes a
l'equation.
Complete les sources, associe l'equation a l'inconnue complete les
operateurs, complete les conditions aux limites discretisees.
Voir les methodes Source_base::completer(),
Operateur_base::completer()
Zone_Cl_dis_base::completer()
Zone_Cl_dis_base::completer(const Zone_dis&)
virtual double calculer_pas_de_temps () const
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des
pas de temps calcules par les operateurs.
Ces pas de temps sont ceux pour le schema d'Euler explicite.
Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule.
void calculer_pas_de_temps_locaux (DoubleTab &) const
Sources & sources ()
Renvoie les termes sources asssocies a l'equation.
const Sources & sources () const
Renvoie les termes sources asssocies a l'equation<br>(version const)
Solveur_Masse & solv_masse ()
Renvoie le solveur de masse associe a l'equation.
const Solveur_Masse & solv_masse () const
Renvoie le solveur de masse associe a l'equation.
(version const)
Probleme_base & probleme ()
Renvoie le probleme associe a l'equation.
const Probleme_base & probleme () const
Renvoie le probleme associe a l'equation.
(version const)
Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe a l'equation.
const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe a l'equation.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
S'associe au schema_en_temps.
virtual void associer_zone_dis (const Zone_dis &)
Associe la zone discretisee a l'equation.
const Discretisation_base & discretisation () const
Renvoie la discretisation associee a l'equation.
virtual Zone_Cl_dis & zone_Cl_dis ()
Renvoie la zone des conditions aux limite discretisee
associee a l'equation.
virtual const Zone_Cl_dis & zone_Cl_dis () const
Renvoie la zone des conditions aux limite discretisee
associee a l'equation<br>(version const)
Zone_dis & zone_dis ()
Renvoie la zone discretisee associee a l'equation.
const Zone_dis & zone_dis () const
Renvoie la zone discretisee associee a l'equation.
(version const)
const Nom & le_nom () const override
Renvoie le nom de l'equation.
DoubleVect & get_residu ()
DoubleVect & residu_initial ()
void initialise_residu (int=0)
virtual void imprime_residu (SFichier &)
virtual Nom expression_residu ()
virtual void dimensionner_matrice (Matrice_Morse &mat_morse)
virtual void dimensionner_matrice_sans_mem (Matrice_Morse &mat_morse)
virtual void assembler (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void modifier_pour_Cl (Matrice_Morse &mat_morse, DoubleTab &secmem) const
virtual void assembler_avec_inertie (Matrice_Morse &mat_morse, const DoubleTab &present, DoubleTab &secmem)
virtual void dimensionner_termes_croises (Matrice_Morse &matrice, const Probleme_base &autre_pb, int nl, int nc)
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void assembler_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={})
Champ_Inc_base & champ_conserve () const
int has_champ_conserve () const
void init_champ_conserve () const
virtual std::pair< std::string, fonc_calc_t > get_fonc_champ_conserve () const
virtual Champ_Inc_base & champ_convecte () const
virtual int has_champ_convecte () const
virtual void init_champ_convecte () const
virtual void mettre_a_jour_champs_conserves (double temps, int reset=0)
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual const Motcle & domaine_application () const
Renvoie "indetermine"
Navier_Stokes_standard par exemple surcharge cette methode
pour renvoyer "Hydraulique".
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Verification du nombre de composantes lues pour la specification d un champ.
Actuellement utilise pour la lecture d un condition initiale ou limite.
virtual void verifie_ch_init_nb_comp_cl (const Champ_Inc_base &ch_ref, const int nb_comp, const Cond_lim_base &cl) const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
Add convection term
In: solution is the unknown I
Out: secmem is increased by convection(I)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution)
void Gradient_conjugue_diff_impl (DoubleTrav &secmem, DoubleTab &solution, const DoubleTab &terme_mul)
Parametre_equation & parametre_equation ()
const Parametre_equation & parametre_equation () const
virtual const Ref_Objet_U & get_modele (Type_modele type) const
virtual int equation_non_resolue () const
int disable_equation_residual () const
virtual const Champ_Inc & derivee_en_temps () const
virtual Champ_Inc & derivee_en_temps ()
void set_calculate_time_derivative (int i)
int calculate_time_derivative () const
void set_residuals (DoubleTab r)
virtual int positive_unkown ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Masse_Multiphase & self_cast (Objet_U &)
static const Masse_Multiphase & self_cast (const Objet_U &)
static void calculer_alpha_rho (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Convection_Diffusion_std
static const Type_info * info ()
static Convection_Diffusion_std & self_cast (Objet_U &)
static const Convection_Diffusion_std & self_cast (const Objet_U &)
Static Public Member Functions inherited from Equation_base
static const Type_info * info ()
static Equation_base & self_cast (Objet_U &)
static const Equation_base & self_cast (const Objet_U &)
static void calculer_champ_conserve (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Convection_Diffusion_std
static const Type_info info_obj
Static Public Attributes inherited from Equation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Simple appel a Equation_base::printOn(Sortie&)
Entree & readOn (Entree &) override
cf Equation_base::readOn(Entree&)
Protected Member Functions inherited from Equation_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime l'equation et ses composants sur un flot de sortie.
Imprime le nom de l'equation, le solveur masse, les termes sources
les conditions aux limites discretisees, les inconnues et les operateurs.
Entree & readOn (Entree &) override
Lecture d'une equation sur un flot d'entree.
Le format est le suivant:
{
[Source { [sou_1], [sour_2], ...} ]
Conditions_limites { [cl_1] [cl_2] ... }
Conditions_initiales { [cl_init] }
}.
virtual void set_param (Param &titi)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_sources (Entree &)
Lecture des termes sources dans un flot d'entree.
virtual Entree & lire_cond_init (Entree &)
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant:
{
Nom [DOIT ETRE LE NOM DE L'INCONNUE]
[LIRE UN CHAMP DONNE]
}.
virtual Entree & lire_cl (Entree &)
Lecture des conditions limites sur un flot d'entree.
voir Zone_Cl_dis_base::readOn.
virtual int verif_Cl () const
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
virtual void lire ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ_Inc l_inco_ch
Ref_Fluide_base le_fluide
Operateur_Evanescence evanescence
Protected Attributes inherited from Convection_Diffusion_std
Ref_Champ_Inc_base la_vitesse_transportante
Operateur_Conv terme_convectif
Operateur_Diff terme_diffusif
Protected Attributes inherited from Equation_base
Nom nom_
Solveur_Masse solveur_masse
Sources les_sources
Ref_Schema_Temps_base le_schema_en_temps
Ref_Zone_dis la_zone_dis
Zone_Cl_dis la_zone_Cl_dis
Ref_Probleme_base mon_probleme
DoubleList dt_op_bak
int sys_invariant_
int implicite_
Parametre_equation parametre_equation_
Champ_Fonc volume_maille
List_RefObjU liste_modeles_
Champs_compris champs_compris_
Champs_Fonc list_champ_combi
Matrice_Morse matrice_stockee
int matrice_init
Champ_Inc champ_conserve_
Champ_Inc champ_convecte_
Detailed Description
classe Masse_Multiphase
Cas particulier de Convection_Diffusion_std pour un fluide quasi conpressible
quand le scalaire subissant le transport est la fraction massique
Definition at line 33 of file Masse_Multiphase.h.
Constructor & Destructor Documentation
~Masse_Multiphase()
Masse_Multiphase::~Masse_Multiphase ()
Definition at line 29 of file Masse_Multiphase.cpp.
Masse_Multiphase()
Masse_Multiphase::Masse_Multiphase ()
Definition at line 32 of file Masse_Multiphase.cpp.
{
  /*  Noms& nom=champs_compris_.liste_noms_compris();
      nom.dimensionner(1);
      nom[0]="fraction_massique";
  */
}
Member Function Documentation
assembler_blocs_avec_inertie()
void Masse_Multiphase::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) override virtual
Reimplemented from Equation_base.
Definition at line 126 of file Masse_Multiphase.cpp.
{
  Equation_base::assembler_blocs_avec_inertie(matrices, secmem, semi_impl);
  if (evanescence.non_nul()) evanescence.valeur().ajouter_blocs(matrices, secmem, semi_impl);
}
References Operateur_base::ajouter_blocs(), Equation_base::assembler_blocs_avec_inertie(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
associer_fluide()
void Masse_Multiphase::associer_fluide (const Fluide_base & un_fluide)
Associe un fluide de type Fluide_base a l'equation.
Definition at line 329 of file Masse_Multiphase.cpp.
{
  assert(sub_type(Fluide_base,un_fluide));
  le_fluide = ref_cast(Fluide_base,un_fluide);
}
References le_fluide, ref_cast, and sub_type.
Referenced by associer_milieu_base().
associer_milieu_base()
void Masse_Multiphase::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation,
le milieu est en fait caste en Fluide_base.
Implements Equation_base.
Definition at line 148 of file Masse_Multiphase.cpp.
{
  const Fluide_base& un_fluide = ref_cast(Fluide_base,un_milieu);
  associer_fluide(un_fluide);
}
References associer_fluide(), and ref_cast.
Referenced by Pb_Multiphase::associer_milieu_base().
calculer_alpha_rho()
void Masse_Multiphase::calculer_alpha_rho (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
Definition at line 335 of file Masse_Multiphase.cpp.
{
  const Equation_base& eqn = ref_cast(Equation_base, obj);
  const Champ_base& ch_rho = eqn.milieu().masse_volumique().valeur();
  const Champ_Inc_base& ch_alpha = eqn.inconnue(), *pch_rho = sub_type(Champ_Inc_base, ch_rho) ? &ref_cast(Champ_Inc_base, ch_rho) : NULL;
  const DoubleTab& alpha = ch_alpha.valeurs(), &rho = ch_rho.valeurs();
  int i, nl = val.dimension_tot(0), n, N = val.line_size(), cR = sub_type(Champ_Uniforme, ch_rho);
  /* valeurs du champ */
  for (i = 0; i < nl; i++)
    for (n = 0; n < N; n++) val(i, n) = alpha(i, n) * rho(!cR * i, n);
  /* valeur aux bords */
  /* on ne peut utiliser valeur_aux_bords que si ch_rho a une zone_dis_base */
  ch_rho.a_une_zone_dis_base() ? bval = ch_rho.valeur_aux_bords() : ch_rho.valeur_aux(ref_cast(Zone_VF, eqn.zone_dis().valeur()).xv_bord(), bval);
  tab_multiply_any_shape(bval, ch_alpha.valeur_aux_bords());
  /* derivees */
  DoubleTab& d_a = deriv["alpha"]; //derivee en alpha : rho
  for (d_a.resize(nl, N), i = 0; i < nl; i++)
    for (n = 0; n < N; n++) d_a(i, n) = rho(!cR * i , n);
  if (pch_rho)
    for (auto &&d_c : pch_rho->derivees()) //derivees en les dependances de rho
      {
        DoubleTab& der = deriv[d_c.first];
        for (der.resize(nl, N), i = 0; i < nl; i++)
          for (n = 0; n < N; n++) der(i, n) = d_c.second(i, n) * alpha(i, n);
      }
}
References Champ_base::a_une_zone_dis_base(), TRUSTTab< _TYPE_ >::dimension_tot(), Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, tab_multiply_any_shape(), Deriv_Champ_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_base::valeur_aux(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Equation_base::zone_dis().
Referenced by get_fonc_champ_conserve().
completer()
void Masse_Multiphase::completer (void) override virtual
Associe l inconnue de l equation a la loi d etat,.
Reimplemented from Equation_base.
Definition at line 168 of file Masse_Multiphase.cpp.
{
  Equation_base::completer();
  terme_convectif.valeur().check_multiphase_compatibility();
}
References MorEqn::check_multiphase_compatibility(), Equation_base::completer(), Convection_Diffusion_std::terme_convectif, and Deriv_Operateur_Conv_base::valeur().
cree_instance()
Objet_U * Masse_Multiphase::cree_instance () static
Definition at line 29 of file Masse_Multiphase.cpp.
dimensionner_blocs()
void Masse_Multiphase::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
Definition at line 120 of file Masse_Multiphase.cpp.
{
  Equation_base::dimensionner_blocs(matrices, semi_impl);
  if (evanescence.non_nul()) evanescence.valeur().dimensionner_blocs(matrices, semi_impl);
}
References Equation_base::dimensionner_blocs(), Operateur_base::dimensionner_blocs(), evanescence, O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
dimensionner_matrice_sans_mem()
void Masse_Multiphase::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Equation_base.
Definition at line 106 of file Masse_Multiphase.cpp.
{
  Equation_base::dimensionner_matrice_sans_mem(matrice);
  evanescence.valeur().dimensionner(matrice);
}
References Operateur_base::dimensionner(), Equation_base::dimensionner_matrice_sans_mem(), evanescence, and Deriv_Operateur_Evanescence_base::valeur().
discretiser()
void Masse_Multiphase::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
Definition at line 188 of file Masse_Multiphase.cpp.
{
  int nb_valeurs_temp = schema_temps().nb_valeurs_temporelles();
  double temps = schema_temps().temps_courant();
  const Discret_Thyd& dis=ref_cast(Discret_Thyd, discretisation());
  Cerr << "Volume fraction discretization" << finl;
// On utilise temperature pour la directive car discretisation identique
  const Pb_Multiphase& pb = ref_cast(Pb_Multiphase, probleme());
  dis.discretiser_champ("temperature",zone_dis(),"alpha","sans_dimension", pb.nb_phases(),nb_valeurs_temp,temps,l_inco_ch);
  l_inco_ch.valeur().fixer_nature_du_champ(pb.nb_phases() == 1 ? scalaire : pb.nb_phases() == dimension ? vectoriel : multi_scalaire); //pfft
  Equation_base::discretiser();
  for (int i = 0; i < pb.nb_phases(); i++)
    l_inco_ch.valeur().fixer_nom_compo(i, Nom("alpha_") + pb.nom_phase(i));
  Cerr << "Masse_Multiphase::discretiser() ok" << finl;
}
References Cerr, Objet_U::dimension, Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), finl, Field_base::fixer_nature_du_champ(), Field_base::fixer_nom_compo(), l_inco_ch, multi_scalaire, Pb_Multiphase::nb_phases(), Schema_Temps_base::nb_valeurs_temporelles(), Pb_Multiphase::nom_phase(), Equation_base::probleme(), ref_cast, scalaire, Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Deriv_Champ_Inc_base::valeur(), vectoriel, and Equation_base::zone_dis().
domaine_application()
const Motcle & Masse_Multiphase::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
Motcle&
Signification: le nom du domaine d'application de l'equation
Contraintes: toujours egal a "Thermique"
Reimplemented from Equation_base.
Definition at line 309 of file Masse_Multiphase.cpp.
{
  static Motcle domaine ="Fraction_volumique";
  return domaine;
}
duplique()
int Masse_Multiphase::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Masse_Multiphase.cpp.
fluide() [1/2]
Fluide_base & Masse_Multiphase::fluide ()
Renvoie le fluide incompressible associe a l'equation.
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes:
Definition at line 288 of file Masse_Multiphase.cpp.
{
  assert(le_fluide.non_nul());
  return le_fluide.valeur();
}
References le_fluide, O_U_Ptr::non_nul(), and Ref_Fluide_base::valeur().
fluide() [2/2]
const Fluide_base & Masse_Multiphase::fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Returns
Fluide_base&
Signification: le fluide incompressible associe a l'equation
Contraintes: reference constante
Definition at line 263 of file Masse_Multiphase.cpp.
{
  if (!le_fluide.non_nul())
    {
      Cerr << "You forgot to associate the fluid to the problem named " << probleme().le_nom() << finl;
      Process::exit();
    }
  return le_fluide.valeur();
}
References Cerr, Process::exit(), finl, le_fluide, Probleme_base::le_nom(), O_U_Ptr::non_nul(), Equation_base::probleme(), and Ref_Fluide_base::valeur().
Referenced by milieu().
get_fonc_champ_conserve()
std::pair< std::string, fonc_calc_t > Masse_Multiphase::get_fonc_champ_conserve () const inline override virtual
Reimplemented from Equation_base.
Definition at line 73 of file Masse_Multiphase.h.
  {
    return { "alpha_rho", calculer_alpha_rho };
  }
References calculer_alpha_rho().
get_info()
const Type_info * Masse_Multiphase::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 29 of file Masse_Multiphase.cpp.
has_interface_blocs()
int Masse_Multiphase::has_interface_blocs () const override virtual
Reimplemented from Equation_base.
Definition at line 112 of file Masse_Multiphase.cpp.
{
  int ok = Convection_Diffusion_std::has_interface_blocs();
  if (evanescence.non_nul()) ok &= evanescence.valeur().has_interface_blocs();
  return ok;
}
References evanescence, Equation_base::has_interface_blocs(), Operateur_base::has_interface_blocs(), O_U_Ptr::non_nul(), and Deriv_Operateur_Evanescence_base::valeur().
inconnue() [1/2]
const Champ_Inc & Masse_Multiphase::inconnue () const inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H)
(version const)
Returns
Champ_Inc&
Signification: le champ inconnue representant la temperature (GP)
ou l'enthalpie (GR)
Contraintes: reference constante
Implements Convection_Diffusion_std.
Definition at line 106 of file Masse_Multiphase.h.
{
  return l_inco_ch;
}
References l_inco_ch.
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter_blocs(), Flux_interfacial_PolyMAC::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_Elem::ajouter_blocs(), Travail_pression_PolyMAC::ajouter_blocs(), Masse_PolyMAC_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Diff_PolyMAC_Elem::ajouter_blocs_ext(), and Assembleur_P_PolyMAC::assembler_continuite().
inconnue() [2/2]
Champ_Inc & Masse_Multiphase::inconnue () inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H)
Returns
Champ_Inc&
Signification: le champ inconnue representant la temperature (GP)
ou l'enthalpie (GR)
Contraintes:
Implements Convection_Diffusion_std.
Definition at line 127 of file Masse_Multiphase.h.
{
  return l_inco_ch;
}
References l_inco_ch.
info()
const Type_info * Masse_Multiphase::info () static
Definition at line 29 of file Masse_Multiphase.cpp.
lire_motcle_non_standard()
int Masse_Multiphase::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Convection_Diffusion_std.
Definition at line 87 of file Masse_Multiphase.cpp.
{
  if (mot=="evanescence") is >> evanescence;
  else return Convection_Diffusion_std::lire_motcle_non_standard(mot, is);
  return 1;
}
References evanescence, and Convection_Diffusion_std::lire_motcle_non_standard().
milieu() [1/2]
const Milieu_base & Masse_Multiphase::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
(version const)
Returns
Milieu_base&
Signification: le Fluide_base upcaste en Milieu_base
Contraintes: reference constante
Implements Equation_base.
Definition at line 221 of file Masse_Multiphase.cpp.
{
  return fluide();
}
References fluide().
milieu() [2/2]
Milieu_base & Masse_Multiphase::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
Returns
Milieu_base&
Signification: le Fluide_base upcaste en Milieu_base
Contraintes:
Implements Equation_base.
Definition at line 242 of file Masse_Multiphase.cpp.
{
  return fluide();
}
References fluide().
nombre_d_operateurs()
int Masse_Multiphase::nombre_d_operateurs () const inline override virtual
Renvoie le nombre d'operateurs de l'equation:
2 pour une equation de diffusion.
Returns
int
Signification: le nombre d'operateurs de l'equation
Contraintes: toujours egal a 2
Reimplemented from Convection_Diffusion_std.
Definition at line 54 of file Masse_Multiphase.h.
  {
    return 1;
  }
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs().
operateur() [1/2]
const Operateur & Masse_Multiphase::operateur (int i) const override virtual
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Returns
Operateur&
Signification: l'operateur specifie
Contraintes: reference constante
Reimplemented from Convection_Diffusion_std.
Definition at line 94 of file Masse_Multiphase.cpp.
{
  if (i) Cerr << "Masse_Multiphase : wrong operator number " << i << finl, Process::exit();
  return terme_convectif;
}
References Cerr, Process::exit(), finl, and Convection_Diffusion_std::terme_convectif.
Referenced by Flux_interfacial_PolyMAC::ajouter_blocs().
operateur() [2/2]
Operateur & Masse_Multiphase::operateur (int i) override virtual
Renvoie l'operateur specifie par son index:
renvoie terme_diffusif si i = 0
renvoie terme_convectif si i = 1
exit si i>1.
Returns
Operateur&
Signification: l'operateur specifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 100 of file Masse_Multiphase.cpp.
{
  if (i) Cerr << "Masse_Multiphase : wrong operator number " << i << finl, Process::exit();
  return terme_convectif;
}
References Cerr, Process::exit(), finl, and Convection_Diffusion_std::terme_convectif.
printOn()
Sortie & Masse_Multiphase::printOn (Sortie & is) const override protected virtual
Simple appel a Equation_base::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 41 of file Masse_Multiphase.cpp.
{
  return Equation_base::printOn(is);
}
References Equation_base::printOn().
readOn()
Entree & Masse_Multiphase::readOn (Entree & is) override protected virtual
cf Equation_base::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Convection_Diffusion_std.
Definition at line 46 of file Masse_Multiphase.cpp.
{
  assert(l_inco_ch.non_nul());
  assert(le_fluide.non_nul());
  terme_convectif.associer_eqn(*this), evanescence.associer_eqn(*this);
  Equation_base::readOn(is);
  terme_convectif.set_fichier("Debit");
  terme_convectif.set_description((Nom)"Mass flow rate=Integral(-alpha*rho*u*ndS) [kg/s] if SI units used");
  champs_compris_.ajoute_champ(l_inco_ch);
// Special treatment for Pb_HEM
// We enforce the presence of a source term related to the
// interfacial flux automatically defined in the Pb_HEM class.
  if (probleme().que_suis_je() == "Pb_HEM")
    {
      int check_source_FICC(0);
      for (int ii = 0; ii < sources().size(); ii++)
        if (sources()(ii).valeur().que_suis_je().debute_par("Flux_interfacial"))
          check_source_FICC = 1;
      if (check_source_FICC == 0)
        {
          EChaine source_FI("{ flux_interfacial }");
          lire_sources(source_FI);
        }
    }
// End of Pb_HEM special treatment
  return is;
}
References Champs_compris::ajoute_champ(), MorEqn::associer_eqn(), Equation_base::champs_compris_, evanescence, l_inco_ch, le_fluide, Equation_base::lire_sources(), O_U_Ptr::non_nul(), Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::readOn(), Operateur::set_description(), Operateur::set_fichier(), liste::size(), Equation_base::sources(), Convection_Diffusion_std::terme_convectif, and valeur().
self_cast() [1/2]
const Masse_Multiphase & Masse_Multiphase::self_cast (const Objet_U & r) static
Definition at line 29 of file Masse_Multiphase.cpp.
self_cast() [2/2]
Masse_Multiphase & Masse_Multiphase::self_cast (Objet_U & r) static
Definition at line 29 of file Masse_Multiphase.cpp.
set_param()
void Masse_Multiphase::set_param (Param & param) override virtual
Reimplemented from Convection_Diffusion_std.
Definition at line 79 of file Masse_Multiphase.cpp.
{
  Equation_base::set_param(param);
  param.ajouter_non_std("convection",(this));
  param.ajouter_non_std("evanescence|vanishing",(this));
  param.ajouter_condition("is_read_convection","The convection operator must be read, select negligeable type if you want to neglect it.");
}
References Param::ajouter_condition(), Param::ajouter_non_std(), and Equation_base::set_param().
taille_memoire()
unsigned Masse_Multiphase::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Masse_Multiphase.cpp.
Member Data Documentation
evanescence
Operateur_Evanescence Masse_Multiphase::evanescence protected
Definition at line 86 of file Masse_Multiphase.h.
Referenced by assembler_blocs_avec_inertie(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), has_interface_blocs(), lire_motcle_non_standard(), and readOn().
info_obj
const Type_info Masse_Multiphase::info_obj static
Definition at line 35 of file Masse_Multiphase.h.
l_inco_ch
Champ_Inc Masse_Multiphase::l_inco_ch protected
Definition at line 83 of file Masse_Multiphase.h.
Referenced by discretiser(), inconnue(), and readOn().
le_fluide
Ref_Fluide_base Masse_Multiphase::le_fluide protected
Definition at line 84 of file Masse_Multiphase.h.
Referenced by associer_fluide(), fluide(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Equations/Masse_Multiphase.h
src/ThHyd/Multiphase/Equations/Masse_Multiphase.cpp