TRUST: Pb_Hydraulique Class Reference
Pb_Hydraulique Class Reference
classe Pb_Hydraulique
Cette classe represente un probleme hydraulique standard dans lequel
on resout les equations de Navier Stokes en regime laminaire
pour un fluide incompressible
La formulation est de type vitesse pression
#include <Pb_Hydraulique.h>
Public Member Functions
Pb_Hydraulique ()
~Pb_Hydraulique ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int nombre_d_equations () const
Renvoie le nombre d'equation,
Renvoie 1 car il y a seulement 1 equation a un probleme
hydraulique standard: l'equation de Navier Stokes.
const Equation_base & equation (int) const
Renvoie l'equation d'hydraulique de type Navier_Stokes_std
si i=0, sort (exit) sinon.
(version const)
Equation_base & equation (int)
Renvoie l'equation d'hydraulique de type Navier_Stokes_std
si i=0, sort (exit) sinon.
void associer_milieu_base (const Milieu_base &)
Associe le milieu au probleme.
Le milieu doit etre de type fluide incompressible.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Pb_Hydraulique & self_cast (Objet_U &)
static const Pb_Hydraulique & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Pb_Fluide_base::printOn(Sortie&)
Ecrit le probleme sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Pb_Fluide_base::readOn(Entree&)
Lit le probleme a partir d'un flot d'entree.
Protected Attributes
Navier_Stokes_std eq_hydraulique
Detailed Description
classe Pb_Hydraulique
Cette classe represente un probleme hydraulique standard dans lequel
on resout les equations de Navier Stokes en regime laminaire
pour un fluide incompressible
La formulation est de type vitesse pression
Definition at line 43 of file Pb_Hydraulique.h.
Constructor & Destructor Documentation
Pb_Hydraulique::Pb_Hydraulique ()
Definition at line 26 of file Pb_Hydraulique.cpp.
Pb_Hydraulique::~Pb_Hydraulique ()
Definition at line 26 of file Pb_Hydraulique.cpp.
Member Function Documentation
void Pb_Hydraulique::associer_milieu_base (const Milieu_base & mil) [virtual]
Associe le milieu au probleme.
Le milieu doit etre de type fluide incompressible.
Reimplemented from Probleme_base.
Definition at line 160 of file Pb_Hydraulique.cpp.
References Navier_Stokes_std::associer_milieu_base(), Cerr, eq_hydraulique, Process::exit(), finl, Objet_U::que_suis_je(), and sub_type.
{
  if (sub_type(Fluide_base,mil))
    eq_hydraulique.associer_milieu_base(mil);
  else if (sub_type(Fluide_Ostwald,mil))
    {
      Cerr << "Je suis non newto" << finl;
      eq_hydraulique.associer_milieu_base(mil);
    }
  else
    {
      Cerr << "Un milieu de type " << mil.que_suis_je() << " ne peut etre associe a "
           << finl;
      Cerr << "un probleme de type Pb_Hydraulique " << finl;
      exit();
    }
}
Objet_U * Pb_Hydraulique::cree_instance () [static]
Definition at line 26 of file Pb_Hydraulique.cpp.
int Pb_Hydraulique::duplique () const [virtual]
Implements Pb_Fluide_base.
Definition at line 26 of file Pb_Hydraulique.cpp.
const Equation_base & Pb_Hydraulique::equation (int i) const [virtual]
Renvoie l'equation d'hydraulique de type Navier_Stokes_std
si i=0, sort (exit) sinon.
(version const)
Returns:
Equation_base&
Signification: l'equation d'hydraulique de type Navier_Stokes_std
Contraintes: reference constante
Implements Probleme_base.
Definition at line 107 of file Pb_Hydraulique.cpp.
References Cerr, eq_hydraulique, Process::exit(), and finl.
{
  if (i!=0)
    {
      Cerr << "\nError in Pb_Hydraulique::equation() : The problem has only one equation !" << finl;
      Process::exit();
    }
  return eq_hydraulique;
}
Equation_base & Pb_Hydraulique::equation (int i) [virtual]
Renvoie l'equation d'hydraulique de type Navier_Stokes_std
si i=0, sort (exit) sinon.
Returns:
Equation_base&
Signification: l'equation d'hydraulique de type Navier_Stokes_std
Contraintes: reference constante
Implements Probleme_base.
Definition at line 132 of file Pb_Hydraulique.cpp.
References Cerr, eq_hydraulique, Process::exit(), and finl.
{
  if (i!=0)
    {
      Cerr << "\nPb_Hydraulique::equation() : The problem has only one equation !" << finl;
      Process::exit();
    }
  return eq_hydraulique;
}
const Type_info * Pb_Hydraulique::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Definition at line 26 of file Pb_Hydraulique.cpp.
const Type_info * Pb_Hydraulique::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Definition at line 26 of file Pb_Hydraulique.cpp.
int Pb_Hydraulique::nombre_d_equations () const [virtual]
Renvoie le nombre d'equation,
Renvoie 1 car il y a seulement 1 equation a un probleme
hydraulique standard: l'equation de Navier Stokes.
Returns:
int
Signification: le nombre d'equation
Contraintes: toujours 1 car il n'y qu'une seule equation (Navier Stokes)
Implements Probleme_base.
Definition at line 86 of file Pb_Hydraulique.cpp.
{
  return 1;
}
Sortie & Pb_Hydraulique::printOn (Sortie & os) const [protected, virtual]
Simple appel a: Pb_Fluide_base::printOn(Sortie&)
Ecrit le probleme sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Definition at line 44 of file Pb_Hydraulique.cpp.
{
  return Pb_Fluide_base::printOn(os);
}
Entree & Pb_Hydraulique::readOn (Entree & is) [protected, virtual]
Simple appel a: Pb_Fluide_base::readOn(Entree&)
Lit le probleme a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Definition at line 65 of file Pb_Hydraulique.cpp.
{
  return Pb_Fluide_base::readOn(is);
}
Pb_Hydraulique & Pb_Hydraulique::self_cast (Objet_U & r) [static]
Reimplemented from Pb_Fluide_base.
Definition at line 26 of file Pb_Hydraulique.cpp.
const Pb_Hydraulique & Pb_Hydraulique::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Pb_Fluide_base.
Definition at line 26 of file Pb_Hydraulique.cpp.
unsigned Pb_Hydraulique::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Pb_Hydraulique.cpp.
Member Data Documentation
Navier_Stokes_std Pb_Hydraulique::eq_hydraulique [protected]
Definition at line 56 of file Pb_Hydraulique.h.
Referenced by associer_milieu_base(), and equation().
const Type_info Pb_Hydraulique::info_obj [static]
Reimplemented from Pb_Fluide_base.
Definition at line 45 of file Pb_Hydraulique.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Problems/Pb_Hydraulique.h
src/ThHyd/Incompressible/Problems/Pb_Hydraulique.cpp