TRUST: Loi_Etat_Binaire_GP_QC Class Reference
Loi_Etat_Binaire_GP_QC Class Reference
classe Loi_Etat_Binaire_GP_QC
Cette classe represente la loi d'etat pour les melanges binaires.
Associe a un fluide dilatable, elle definit un fluide binaire quasi compressible
dont la loi d'eata est :
Pth = rho*R*T*(Y1/M1+Y2/M2)
#include <Loi_Etat_Binaire_GP_QC.h>
Public Member Functions
Loi_Etat_Binaire_GP_QC ()
~Loi_Etat_Binaire_GP_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void calculer_masse_volumique ()
Recalcule la masse volumique.
double calculer_masse_volumique (double P, double Y1) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Loi_Etat_Binaire_GP_QC & self_cast (Objet_U &)
static const
Loi_Etat_Binaire_GP_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
classe Loi_Etat_Binaire_GP_QC
Cette classe represente la loi d'etat pour les melanges binaires.
Associe a un fluide dilatable, elle definit un fluide binaire quasi compressible
dont la loi d'eata est :
Pth = rho*R*T*(Y1/M1+Y2/M2)
Definition at line 40 of file Loi_Etat_Binaire_GP_QC.h.
Constructor & Destructor Documentation
Loi_Etat_Binaire_GP_QC::Loi_Etat_Binaire_GP_QC ()
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
Loi_Etat_Binaire_GP_QC::~Loi_Etat_Binaire_GP_QC ()
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
Member Function Documentation
void Loi_Etat_Binaire_GP_QC::calculer_masse_volumique () [virtual]
Recalcule la masse volumique.
Implements Loi_Etat_Binaire_GP_base.
Definition at line 67 of file Loi_Etat_Binaire_GP_QC.cpp.
References DoubleVect::echange_espace_virtuel(), Loi_Etat_base::le_fluide, ref_cast_non_const, DoubleVect::size(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, Champ_Proto::valeurs(), and verifier().
Referenced by calculer_masse_volumique().
{
  const DoubleTab& tab_Y1 = le_fluide->inco_chaleur().valeurs();
  DoubleTab& tab_rho = le_fluide->masse_volumique().valeurs();
  double Pth = le_fluide->pression_th();
  const int n = tab_rho.size();
  for (int som=0 ; som<n ; som++)
    {
      tab_rho_np1(som) = calculer_masse_volumique(Pth,tab_Y1(som,0));
      tab_rho(som,0) = 0.5 * ( tab_rho_n(som) + tab_rho_np1(som) );
    }
  const Champ_base& rho_m=le_fluide->get_champ("rho_gaz");
  ref_cast_non_const(DoubleTab,rho_m.valeurs()) = tab_rho_np1;
  tab_rho.echange_espace_virtuel();
  tab_rho_np1.echange_espace_virtuel();
  le_fluide->calculer_rho_face(tab_rho_np1);
  Debog::verifier("Loi_Etat_Binaire_GP_QC::calculer_masse_volumique, tab_rho_np1",tab_rho_np1);
  Debog::verifier("Loi_Etat_Binaire_GP_QC::calculer_masse_volumique, tab_rho",tab_rho);
}
double Loi_Etat_Binaire_GP_QC::calculer_masse_volumique (double P, double Y1) const [virtual]
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 48 of file Loi_Etat_Binaire_GP_QC.cpp.
References calculer_masse_volumique().
{
  return Loi_Etat_Binaire_GP_base::calculer_masse_volumique(P,Y1);
}
Objet_U * Loi_Etat_Binaire_GP_QC::cree_instance () [static]
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
int Loi_Etat_Binaire_GP_QC::duplique () const [virtual]
Implements Loi_Etat_Binaire_GP_base.
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
const Type_info * Loi_Etat_Binaire_GP_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
const Type_info * Loi_Etat_Binaire_GP_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
Sortie & Loi_Etat_Binaire_GP_QC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 36 of file Loi_Etat_Binaire_GP_QC.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Loi_Etat_Binaire_GP_QC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 42 of file Loi_Etat_Binaire_GP_QC.cpp.
References Cerr, and finl.
{
  Cerr<<"Lecture de la loi d'etat Melange Binaire QC ... "<<finl;
  return Loi_Etat_Binaire_GP_base::readOn(is);
}
const Loi_Etat_Binaire_GP_QC & Loi_Etat_Binaire_GP_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
Loi_Etat_Binaire_GP_QC & Loi_Etat_Binaire_GP_QC::self_cast (Objet_U & r) [static]
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
unsigned Loi_Etat_Binaire_GP_QC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Loi_Etat_Binaire_GP_QC.cpp.
Member Data Documentation
const Type_info Loi_Etat_Binaire_GP_QC::info_obj [static]
Reimplemented from Loi_Etat_Binaire_GP_base.
Definition at line 42 of file Loi_Etat_Binaire_GP_QC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_Binaire_GP_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_Binaire_GP_QC.cpp