TRUST: Critere_Q_Champ_Face Class Reference
Critere_Q_Champ_Face Class Reference
classe Critere_Q_Champ_Face
#include <Critere_Q_Champ_Face.h>
Public Member Functions
Critere_Q_Champ_Face ()
~Critere_Q_Champ_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_Face & mon_champ () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ (const Champ_Face &)
void me_calculer (double)
void associer_zone_Cl_dis_base (const Zone_Cl_dis_base &)
const Zone_Cl_dis_base & zone_Cl_dis_base () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Critere_Q_Champ_Face & self_cast (Objet_U &)
static const Critere_Q_Champ_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_Face mon_champ_
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Detailed Description
classe Critere_Q_Champ_Face
Definition at line 38 of file Critere_Q_Champ_Face.h.
Constructor & Destructor Documentation
Critere_Q_Champ_Face::Critere_Q_Champ_Face ()
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
Critere_Q_Champ_Face::~Critere_Q_Champ_Face ()
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
Member Function Documentation
void Critere_Q_Champ_Face::associer_champ (const Champ_Face & un_champ)
Definition at line 46 of file Critere_Q_Champ_Face.cpp.
References mon_champ_.
Referenced by VDF_discretisation::critere_Q().
{
  mon_champ_= un_champ;
}
void Critere_Q_Champ_Face::associer_zone_Cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis_base) [inline]
Definition at line 74 of file Critere_Q_Champ_Face.h.
References la_zone_Cl_VDF.
Referenced by VDF_discretisation::critere_Q().
{
  la_zone_Cl_VDF  = (const Zone_Cl_VDF&) la_zone_Cl_dis_base;
}
Objet_U * Critere_Q_Champ_Face::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
int Critere_Q_Champ_Face::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
const Type_info * Critere_Q_Champ_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
const Type_info * Critere_Q_Champ_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
void Critere_Q_Champ_Face::me_calculer (double tps) [virtual]
Implements Champ_Critere_Q.
Definition at line 51 of file Critere_Q_Champ_Face.cpp.
References la_zone_Cl_VDF, mon_champ_, Ref_Zone_Cl_VDF::valeur(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
{
  mon_champ_->calcul_critere_Q(valeurs(), la_zone_Cl_VDF.valeur());
}
void Critere_Q_Champ_Face::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 67 of file Critere_Q_Champ_Face.h.
References Champ_base::changer_temps(), and me_calculer().
{
  me_calculer(tps);
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
const Champ_Face & Critere_Q_Champ_Face::mon_champ () const [inline]
Definition at line 62 of file Critere_Q_Champ_Face.h.
{
  return mon_champ_.valeur();
}
Sortie & Critere_Q_Champ_Face::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 33 of file Critere_Q_Champ_Face.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Critere_Q_Champ_Face::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 41 of file Critere_Q_Champ_Face.cpp.
{
  return s ;
}
const Critere_Q_Champ_Face & Critere_Q_Champ_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
Critere_Q_Champ_Face & Critere_Q_Champ_Face::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
unsigned Critere_Q_Champ_Face::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 27 of file Critere_Q_Champ_Face.cpp.
const Zone_Cl_dis_base & Critere_Q_Champ_Face::zone_Cl_dis_base () const
Definition at line 56 of file Critere_Q_Champ_Face.cpp.
References la_zone_Cl_VDF, and Ref_Zone_Cl_VDF::valeur().
{
  return la_zone_Cl_VDF.valeur();
}
Member Data Documentation
const Type_info Critere_Q_Champ_Face::info_obj [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 43 of file Critere_Q_Champ_Face.h.
Ref_Zone_Cl_VDF Critere_Q_Champ_Face::la_zone_Cl_VDF [protected]
Definition at line 59 of file Critere_Q_Champ_Face.h.
Referenced by associer_zone_Cl_dis_base(), me_calculer(), and zone_Cl_dis_base().
Ref_Champ_Face Critere_Q_Champ_Face::mon_champ_ [protected]
Definition at line 58 of file Critere_Q_Champ_Face.h.
Referenced by associer_champ(), and me_calculer().
The documentation for this class was generated from the following files:
src/VDF/Champs/Critere_Q_Champ_Face.h
src/VDF/Champs/Critere_Q_Champ_Face.cpp