TRUST: Diametre_hyd_champ Class Reference
Diametre_hyd_champ Class Reference
Diametre_hyd_champ nom_pb champ affecte le champ champ au diametre hydraulique aux elements du domaine du probleme de nom_pb.
#include <Diametre_hyd_champ.h>
Public Member Functions
Diametre_hyd_champ ()
~Diametre_hyd_champ ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Diametre_hyd_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfacqiues comme moyenne harmonique.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Diametre_hyd_champ & self_cast (Objet_U &)
static const Diametre_hyd_champ & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Diametre_hyd_champ nom_pb champ affecte le champ champ au diametre hydraulique aux elements du domaine du probleme de nom_pb.
Definition at line 30 of file Diametre_hyd_champ.h.
Constructor & Destructor Documentation
Diametre_hyd_champ::Diametre_hyd_champ ()
Definition at line 32 of file Diametre_hyd_champ.cpp.
Diametre_hyd_champ::~Diametre_hyd_champ ()
Definition at line 32 of file Diametre_hyd_champ.cpp.
Member Function Documentation
Objet_U * Diametre_hyd_champ::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
int Diametre_hyd_champ::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
const Type_info * Diametre_hyd_champ::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
const Type_info * Diametre_hyd_champ::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
Entree & Diametre_hyd_champ::interpreter (Entree & is) [virtual]
Diametre_hyd_champ nom_pb champ affecte le champ champ a la porosite volumique du domaine du probleme de nom_pb, puis calcule les porosites surfacqiues comme moyenne harmonique.
Reimplemented from Interprete.
Definition at line 45 of file Diametre_hyd_champ.cpp.
References Champ_base::affecter(), Cerr, Zone_VF::diametre_hydraulique_elem(), Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Probleme_base::equation(), Process::exit(), finl, Interprete::objet(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Champ_Don_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don::valeurs(), Champ_Don_base::valeurs(), and Equation_base::zone_dis().
{
  Nom nom_pb;
  is >> nom_pb;
  if(! sub_type(Probleme_base, objet(nom_pb)))
    {
      Cerr << nom_pb << " is of type " << objet(nom_pb).que_suis_je() << finl;
      Cerr << "We waited an object of type Probleme_base" << finl;
      Process::exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base, objet(nom_pb));
  Champ le_champ;
  is>>le_champ;
// On passe par la zone_VF
  Zone_VF& zvf=ref_cast(Zone_VF, pb.equation(0).zone_dis().valeur());
  DoubleTab& dh_elem = zvf.diametre_hydraulique_elem();
// on discretise des champs equivalents pour pouvoir faire affecter
// puis on recopie les valeurs
  Champ_Don dh_elem_p;
  pb.discretisation().discretiser_champ("CHAMP_ELEM", pb.equation(0).zone_dis(), "pp", "1",1,0., dh_elem_p);
  dh_elem_p.valeur().valeurs()=0;
  dh_elem_p.valeur().affecter(le_champ);
  dh_elem = dh_elem_p.valeurs();
  return is;
}
Sortie & Diametre_hyd_champ::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 34 of file Diametre_hyd_champ.cpp.
{
  return Interprete::printOn(os);
}
Entree & Diametre_hyd_champ::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 39 of file Diametre_hyd_champ.cpp.
{
  return Interprete::readOn(is);
}
Diametre_hyd_champ & Diametre_hyd_champ::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
const Diametre_hyd_champ & Diametre_hyd_champ::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
unsigned Diametre_hyd_champ::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.cpp.
Member Data Documentation
const Type_info Diametre_hyd_champ::info_obj [static]
Reimplemented from Interprete.
Definition at line 32 of file Diametre_hyd_champ.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Diametre_hyd_champ.h
src/Kernel/Framework/Diametre_hyd_champ.cpp