TRUST: Solv_Petsc Class Reference
Solv_Petsc Class Reference
#include <Solv_Petsc.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solv_Petsc ()
~Solv_Petsc () override
int solveur_direct () const override
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &M, const DoubleVect &A, DoubleVect &B, int niter_max) override
void create_solver (Entree &)
void reset ()
bool read_matrix () const
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solv_Petsc & self_cast (Objet_U &)
static const Solv_Petsc & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
static int instance =-1
Nombre d'instances en cours de la classe.
static int numero_solveur =0
Compte les solveurs crees et utilises pour le prefix des options.
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
const Nom config ()
Nom du fichier de config eventuel.
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int solveur_direct_
Pour savoir si l'on manipule un solveur direct et non iteratif.
Nom chaine_lue_
Chaine des mots cles lus.
int read_matrix_
Read constant matrix in a file.
bool gpu_
Utilisation des solveurs GPU de PETSc.
bool amgx_
Utilisation des solveurs GPU de AMGX.
bool amgx_initialized_
Amgx initialise Options dev:
bool ignore_new_nonzero_
bool rebuild_matrix_
bool allow_realloc_
bool clean_matrix_
bool verbose = false
Timing.
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 36 of file Solv_Petsc.h.
Constructor & Destructor Documentation
Solv_Petsc()
Solv_Petsc::Solv_Petsc () inline
Definition at line 176 of file Solv_Petsc.h.
{
  read_matrix_=0;
#ifdef PETSCKSP_H
  initialize();
  instance++;
// Journal()<<"creation solv_petsc "<<instance<<finl;
#endif
}
References instance, and read_matrix_.
~Solv_Petsc()
Solv_Petsc::~Solv_Petsc () inline override
Definition at line 186 of file Solv_Petsc.h.
{
  reset();
  instance--;
// Journal()<<" destr solv_petsc "<<instance<<finl;
}
References instance, and reset().
Member Function Documentation
config()
const Nom Solv_Petsc::config () protected
Nom du fichier de config eventuel.
Definition at line 1327 of file Solv_Petsc.cpp.
{
  Nom str(Objet_U::nom_du_cas());
#ifdef PETSCKSP_H
  str+=option_prefix_.prefix("_");
#else
  Process::exit("ToDo fix Solv_Petsc::config(): build config filename with numero_solve in the constructor!");
#endif
  str+=amgx_ ? ".amgx" : ".petsc";
  return str;
}
References amgx_, Process::exit(), Objet_U::nom_du_cas(), and Nom::prefix().
Referenced by create_solver().
create_solver()
void Solv_Petsc::create_solver (Entree & entree)
Definition at line 80 of file Solv_Petsc.cpp.
{
  if (amgx_ || std::getenv("TRUST_PETSC_VERBOSE")) verbose = true;
#ifdef PETSCKSP_H
  lecture(entree);
  EChaine is(get_chaine_lue());
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Nom pc("");
  Nom motlu;
  Nom ksp;
  is >> ksp;   //!< On lit le solveur en premier puis les options du solveur: PETSC ksp { ... }
  is >> motlu; //!< On lit l'accolade
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error while reading the parameters of the solver of PETSC " << ksp << " { ... }" << finl;
      Cerr << "We expected " << accolade_ouverte << " instead of " << motlu << finl;
      exit();
    }
// Verification si Petsc est bien initialise (permet d'eviter un crash en sequentiel sur les machines batch)
  PetscBool isInitialized;
  PetscInitialized(&isInitialized);
  if (!isInitialized)
    {
      Cerr << "On this queuing system cluster, you need to use mpirun even on sequential mode" << finl;
      Cerr << "(mpirun -np 1 ...) with a PETSc solver or the calculation will crash. " << finl;
      Cerr << "You can use the trust script as a workaround:" << finl;
      Cerr << "trust " << nom_du_cas() << finl;
      exit();
    }
// Creation du solveur et association avec le preconditionneur
  if (option_prefix_=="??") //!< Prefix non fixe
    {
      numero_solveur++;
      option_prefix_="";
      if (numero_solveur > 1)
        {
// On cree un prefix pour les options si plus d'un solveur pour les differencier. Exemple:
// premier solveur -ksp_type ... -pc_type ...
// deuxieme solveur -solver2_ksp_type ... -solver2_pc-type ...
// troisieme solveur -solveur3_ksp_type ...
          option_prefix_ += "solver";
          option_prefix_ += (Nom) numero_solveur;
          option_prefix_ += "_";
        }
    }
  /************************/
  /* Set PETSC_COMM_WORLD */
  /************************/
// Recuperation du communicateur du groupe courant
#ifdef MPI_
  if (sub_type(Comm_Group_MPI,PE_Groups::current_group()))
    PETSC_COMM_WORLD = ref_cast(Comm_Group_MPI,PE_Groups::current_group()).get_mpi_comm();
#endif
  KSPCreate(PETSC_COMM_WORLD, &SolveurPetsc_);
  KSPGetPC(SolveurPetsc_, &PreconditionneurPetsc_);
// Add options if PETSc solver is used:
  if (PE_Groups::get_nb_groups()==1 && !disable_TU )
    {
// _petsc.TU is only printed if one group calculation (e.g. Execute_parallel failed)
      Nom petsc_TU(":");
      petsc_TU+=nom_du_cas();
      petsc_TU+="_petsc.TU";
      add_option("log_view",petsc_TU);  //!< Monitor performances at the end of the calculation
      PetscLogAllBegin();               //!< Necessary cause if not Event logs not printed in petsc_TU file ... I don't know why...
    }
#ifdef NDEBUG
// PETSc 3.14 active par defaut les exceptions, on desactive en production ?
// PetscSetFPTrap(PETSC_FP_TRAP_OFF);
// Utiliser -fp_trap 0 a l'execution plutot: Segfault vu sur petsc gmres { precond diag ... }
#endif
// add_option("on_error_abort",""); // ne marche pas semble t'il
// On doit pouvoir lire des mots cles de base (GCP, GMRES, CHOLESKY)
// mais egalement pouvoir appeler les options Petsc avec une chaine { -ksp_type cg -pc_type sor ... }
// Les options non reconnues doivent arreter le code
// Reprendre le formalisme de GCP { precond ssor { omega val } seuil val }
  Motcles les_solveurs(20);
  {
    les_solveurs[0] = "CLI";
    les_solveurs[1] = "GCP";
    les_solveurs[2] = "GMRES";
    les_solveurs[3] = "CHOLESKY";
    les_solveurs[4] = "CHOLESKY_OUT_OF_CORE";
    les_solveurs[5] = "BICGSTAB";
    les_solveurs[6] = "IBICGSTAB";
    les_solveurs[7] = "CHOLESKY_SUPERLU";
    les_solveurs[8] = "PGMRES";
    les_solveurs[9] = "LU";
    les_solveurs[10] = "PIPECG";
    les_solveurs[11] = "CHOLESKY_LAPACK";
    les_solveurs[12] = "CHOLESKY_UMFPACK";
    les_solveurs[13] = "CHOLESKY_PASTIX";
    les_solveurs[14] = "CLI_VERBOSE";
    les_solveurs[15] = "CLI_QUIET";
    les_solveurs[16] = "CHOLESKY_MUMPS_BLR";
    les_solveurs[17] = "CHOLESKY_CHOLMOD";
    les_solveurs[18] = "PIPECG2";
    les_solveurs[19] = "FGMRES";
  }
  int solver_supported_on_gpu_by_petsc=0;
  int solver_supported_on_gpu_by_amgx=0;
  Nom amgx_option="";
  int rang=les_solveurs.search(ksp);
  nommer(les_solveurs[rang]);
  switch(rang)
    {
    case 0:
    case 14:
    case 15:
      {
        if (rang == 15) fixer_limpr(-1);  //!< Quiet
        else fixer_limpr(1); //!< On imprime le residu
        solver_supported_on_gpu_by_petsc=1; //!< Not really, reserved to expert...
        solver_supported_on_gpu_by_amgx=1;  //!< Not really, reserved to expert...
        if (limpr() >= 0) Cerr << "Reading of the " << (amgx_ ? "AmgX" : "Petsc") << " commands:" << finl;
        Nom valeur;
        is >> motlu;
        if (amgx_)
          {
            while (motlu!=accolade_fermee)
              {
// -config file.json
                if (motlu == "-file")
                  {
                    is >> motlu;
                    if (Process::je_suis_maitre())
                      {
                        Cerr << "Reading AmgX config file " << motlu << " :" << finl;
                        EFichier config_amgx(motlu);
                        std::string line;
                        while (!config_amgx.eof())
{
                            std::getline(config_amgx.get_ifstream(), line);
                            if (line.find("#") && line.find("config_version"))
{
                                Cerr << line << finl;
                                amgx_option+=line;
                                amgx_option+="\n";
                              }
                          }
                      }
                  }
                else
                  {
                    amgx_option += motlu;
                    amgx_option += "\n";
                  }
                is >> motlu;
              }
          }
        else
          while (motlu!=accolade_fermee)
            {
              is >> valeur;
// "-option val" ou "-option" ?
              if (valeur.debute_par("-") || valeur==accolade_fermee)
                {
                  add_option(motlu.suffix("-"), "", 1);
                  motlu = valeur;
                }
              else
                {
                  if (motlu == "-ksp_type" && valeur=="preonly") solveur_direct_=cli; //!< Activate direct solveur if using -ksp_preonly ...
                  if (motlu == "-ksp_max_it") ignore_nb_it_max_ = 1; //pour un comportement similaire a l'option nb_it_max
                  add_option(motlu.suffix("-"), valeur, 1);
                  is >> motlu;
                }
            }
// Pour faciliter le debugage:
        if (rang == 14) //!< Verbose
          {
            add_option("ksp_view", "");
            add_option("options_view", "");
            add_option("options_left", "");
          }
        break;
      }
    case 1:
      {
        KSPSetType(SolveurPetsc_, KSPCG);
// Residu=||Ax-b|| comme dans TRUST pour GCP sinon on ne peut comparer les convergences
        KSPSetNormType(SolveurPetsc_, KSP_NORM_UNPRECONDITIONED);
// Merge the two inner products needed in CG into a single MPI_Allreduce() call:
// Gain interessant a partir de 4000 coeurs
        if (Process::nproc()>=4000)
          {
// add_option("ksp_cg_single_reduction",""); Pour Petsc < 3.3, la fonction KSPCGUseSingleReduction n'etait pas disponible
            KSPCGUseSingleReduction(SolveurPetsc_,(PetscBool)1);
          }
// But It requires two extra work vectors than the conventional implementation in PETSc.
        solver_supported_on_gpu_by_petsc=1;
        solver_supported_on_gpu_by_amgx=1;
        if (amgx_) amgx_option+="solver(s)=PCG\n"; //!< CG avec preconditionnement if (amgx_) amgx_option+="solver(s)=PCGF\n"; // Flexible CG avec preconditionnement
//
        break;
      }
    case 10:
      {
        KSPSetType(SolveurPetsc_, KSPPIPECG);
// Residu=||Ax-b|| comme dans TRUST pour GCP sinon on ne peut comparer les convergences
        KSPSetNormType(SolveurPetsc_, KSP_NORM_UNPRECONDITIONED);
        break;
      }
    case 18:
      {
        KSPSetType(SolveurPetsc_, KSPPIPECG2);
// Residu=||Ax-b|| comme dans TRUST pour GCP sinon on ne peut comparer les convergences
        KSPSetNormType(SolveurPetsc_, KSP_NORM_UNPRECONDITIONED);
        break;
      }
    case 2:
      {
        KSPSetType(SolveurPetsc_, KSPGMRES);
// Le preconditionnement a droite permet que le residu utilise pour la convergence
// soit le residu reel ||Ax-b|| et non le residu preconditionne pour certains solveurs
// avec un preconditionnement a gauche (ex: GMRES). Ainsi, on peut comparer strictement
// les performances des solveurs (TRUST ou PETSC) entre eux
        KSPSetPCSide(SolveurPetsc_, PC_RIGHT);
        KSPSetNormType(SolveurPetsc_, KSP_NORM_UNPRECONDITIONED);
        solver_supported_on_gpu_by_petsc=1;
        solver_supported_on_gpu_by_amgx=1;
        if (amgx_)
          {
            amgx_option+="solver(s)=GMRES\n"; //!< GMRES
            Process::exit("Gmres solver on GPU with AmgX fails to return a valid solution. Try GCP, BiCGSTAB or FGMRES solvers.");
          }
        break;
      }
    case 19:
      {
        KSPSetType(SolveurPetsc_, KSPFGMRES);
        KSPSetPCSide(SolveurPetsc_, PC_RIGHT);
        KSPSetNormType(SolveurPetsc_, KSP_NORM_UNPRECONDITIONED);
        solver_supported_on_gpu_by_petsc=1;
        solver_supported_on_gpu_by_amgx=1;
        if (amgx_) amgx_option+="solver(s)=FGMRES\n"; //!< FGMRES
        break;
      }
    case 8:
      {
        KSPSetType(SolveurPetsc_, KSPPGMRES);
// PGMRES ne peut etre que preconditionne a gauche (CAx=Cb)
// et on ne peut avoir que le residu preconditionne (||CAx-Cb||)
// -> on ne peut comparer la convergence avec le GMRES...
        KSPSetPCSide(SolveurPetsc_, PC_LEFT);
// KSPSetNormType(SolveurPetsc, KSP_NORM_UNPRECONDITIONED);
        solver_supported_on_gpu_by_petsc=1;
        break;
      }
    case 3:
    case 4:
    case 9:
    case 16:
      {
// Si MUMPS est present, on le prend par defaut (solveur_direct_=1) sinon SuperLU (solveur_direct_=2):
#ifdef PETSC_HAVE_MUMPS
        solveur_direct_ = mumps;
// Ajout de l'option
// Par defaut le cas PAR_Canal_incline_VEF plante sur 4 processeurs si -mat_mumps_icntl_14 inferieur a 35...
// On revient a 75 car parfois VEF_258 plante... C'est pas clair au niveau memoire...
// Passage a Petsc 3.3 necessite d'augmenter a plus de 75 car sinon Aero_192 crashe...
// A 90, le cas les_Re180Pr071_T0Q_jdd2 plante sur forchat (32bits)
// On differencie sequentiel (peu de memoire, mais estimation juste)
// et le calcul parallele (voir peut etre une separation entre plus et moins de 16 processeurs...)
// Peut etre equiper le script trust d'une detection des erreurs INFO(1)=-9 ...
// On passe de 35 a 40 pour faire passer le cas cavite_entrainee_2D_jdd2 (suite passage a MUMPS 5.2.0)
        if (Process::nproc() == 1)
          add_option("mat_mumps_icntl_14", "40");
        else
          add_option("mat_mumps_icntl_14", "90");
// Option out_of_core
        if (rang == 4) add_option("mat_mumps_icntl_22", "1");
// Option BLR
        if (rang == 16)
          {
            Cerr
                << "Activating BLR factorization. For more info, see http://mumps.enseeiht.fr/doc/userguide_5.1.2.pdf (page 18, 51, 52)."
                << finl;
            add_option("mat_mumps_icntl_35", "1");
          }
#else
        solveur_direct_=superlu_dist;
#endif
        KSPSetType(SolveurPetsc_, KSPPREONLY);
        break;
      }
    case 5:
      {
        KSPSetType(SolveurPetsc_, KSPBCGS);
        solver_supported_on_gpu_by_petsc=1;
        solver_supported_on_gpu_by_amgx=1;
// if (amgx_) amgx_option+="solver(s)=BICGSTAB\n"; // BICGSTAB sans preconditionnement
        if (amgx_) amgx_option+="solver(s)=PBICGSTAB\n"; //!< BICGSTAB avec precondtionnement
        break;
      }
    case 6:
      {
        KSPSetType(SolveurPetsc_, KSPIBCGS); //!< 1 point de synchro au lieu de 3 pour KSPBCGS Pour optimiser encore les comms, voir: http://www.mcs.anl.gov/petsc/petsc-as/snapshots/petsc-3.0.0/docs/manualpages/KSP/KSPIBCGS.html
//
//
        KSPSetLagNorm(SolveurPetsc_, PETSC_TRUE);
        break;
      }
    case 7:
      {
        solveur_direct_=superlu_dist;
// SuperLU_dist, parallel but not faster than MUMPS
#ifdef PETSC_HAVE_OPENMP
// Version GPU disponible de SuperLU si OpenMP active (necessaire)
        solver_supported_on_gpu_by_petsc=1;
#endif
        KSPSetType(SolveurPetsc_, KSPPREONLY);
        break;
      }
    case 11:
      {
        if (Process::nproc()>1) Process::exit("Cholesky_lapack can't be used for parallel calculation.");
        solveur_direct_=petsc;
// Lapack, old and slow (non pas vrai sur petites matrices d'ordre 100 - 10000 !)
        add_option("pc_factor_nonzeros_along_diagonal", ""); //!< Moins robuste que MUMPS pour un pivot nul donc on reordonne pour eviter
        KSPSetType(SolveurPetsc_, KSPPREONLY);
        break;
      }
    case 12:
      {
        if (Process::nproc()>1) Process::exit("Cholesky_umfpack can't be used for parallel calculation.");
        solveur_direct_=umfpack;
// Umfpack, sequential only but fast...
        KSPSetType(SolveurPetsc_, KSPPREONLY);
// more robustness
        add_option("mat_umfpack_pivot_tolerance","1.0");
        break;
      }
    case 13:
      {
        solveur_direct_=pastix;
// Pastix supports sbaij but seems slow...
        KSPSetType(SolveurPetsc_, KSPPREONLY);
        break;
      }
    case 17:
      {
        if (Process::nproc()>1) Process::exit("Cholesky_cholmod can't be used for parallel calculation.");
        solveur_direct_=cholmod;
// Cholmod Cholesky (pas LU), sequentiel, supporte multi-GPU
        if (!matrice_symetrique_)
          {
            Cerr << ksp << " is only supported for symmetric linear system." << finl;
            Process::exit();
          }
        solver_supported_on_gpu_by_petsc=1;
        KSPSetType(SolveurPetsc_, KSPPREONLY);
        break;
      }
    default:
      {
        Cerr << ksp << " : solver not officially recognized by TRUST among those possible for the moment:" << finl;
        Cerr << les_solveurs << finl;
        Cerr << "You can try to access directly to Petsc solvers with the command line:" << finl;
        Cerr << "PETSC CLI { -ksp_type solver_name -pc_type preconditioning_name -ksp_atol threshold -ksp_monitor }" << finl;
        Cerr << "See the reference manual for all Petsc options." << finl;
        Process::exit();
      }
    }
// On verifie que le solveur est supporte sur GPU:
  if (gpu_)
    {
#ifdef PETSC_HAVE_CUDA
      Cerr << "GPU capabilities of PETSc will be used." << finl;
#else
      Cerr << "You can not use petsc_gpu keyword cause GPU" << finl;
      Cerr << "capabilities will not work on your workstation with PETSc." << finl;
      Cerr << "Check if you have a NVidia video card and its driver up to date." << finl;
      Cerr << "Check petsc.log file under $TRUST_ROOT/lib/src/LIBPETSC for more details." << finl;
      Process::exit();
#endif
      if (solver_supported_on_gpu_by_petsc==0)
        {
          Cerr << les_solveurs[rang] << " is not supported yet by PETSc on GPU." << finl;
          Process::exit();
        }
    }
  if (amgx_)
    {
#ifdef PETSC_HAVE_CUDA
      Cerr << "GPU capabilities of AmgX will be used." << finl;
#else
      Cerr << "You can not use amgx keyword cause GPU" << finl;
      Cerr << "capabilities will not work on your workstation with AmgX." << finl;
      Cerr << "Check if you have a NVidia video card and its driver up to date." << finl;
      Cerr << "Check petsc.log file under $TRUST_ROOT/lib/src/LIBPETSC for more details." << finl;
      Process::exit();
#endif
      if (solver_supported_on_gpu_by_amgx==0)
        {
          Cerr << les_solveurs[rang] << " is not supported yet by AmgX on GPU." << finl;
          Process::exit();
        }
    }
  int convergence_with_seuil=0; //!< Keyword to check the convergence via seuil or nb_it_max On continue a lire
//
  if (motlu==accolade_ouverte)
    {
// Temporaire essayer de faire converger les noms de parametres des differentes solveurs (GCP, GMRES,...)
      Motcles les_parametres_solveur(28);
      {
        les_parametres_solveur[0] = "impr";
        les_parametres_solveur[1] = "seuil"; //!< Seuil absolu (atol)
        les_parametres_solveur[2] = "precond";
        les_parametres_solveur[3] = "precond_nul"; //!< To accept the TRUST syntax
        les_parametres_solveur[4] = "nb_it_max";
        les_parametres_solveur[5] = "save_matrix_petsc_format";
        les_parametres_solveur[6] = "factored_matrix"; //!< Experimental
        les_parametres_solveur[7] = "read_matrix";
        les_parametres_solveur[8] = "controle_residu";
        les_parametres_solveur[9] = "cli";
        les_parametres_solveur[10] = "ordering";
        les_parametres_solveur[11] = "petsc_decide"; //!< Experimental
        les_parametres_solveur[12] = "aij";
        les_parametres_solveur[13] = "nb_cpus";
        les_parametres_solveur[14] = "divtol";
        les_parametres_solveur[15] = "save_matrice|save_matrix";
        les_parametres_solveur[16] = "quiet";
        les_parametres_solveur[17] = "restart";
        les_parametres_solveur[18] = "cli_verbose";
        les_parametres_solveur[19] = "dropping_parameter";
        les_parametres_solveur[20] = "rtol"; //!< Seuil relatif
        les_parametres_solveur[21] = "atol"; //!< Seuil absolu <=> seuil
        les_parametres_solveur[22] = "ignore_new_nonzero";
        les_parametres_solveur[23] = "rebuild_matrix";
        les_parametres_solveur[24] = "allow_realloc";
        les_parametres_solveur[25] = "clean_matrix";
        les_parametres_solveur[26] = "save_matrix_mtx_format";
        les_parametres_solveur[27] = "reuse_precond";
      }
      option_double omega("omega",amgx_ ? 0.9 : 1.5);
      option_int    level("level",1);
      option_double epsilon("epsilon",0.1);
      option_string ordering("ordering",(Nom)"");
      controle_residu_=0;
      is >> motlu;
      while (motlu!=accolade_fermee)
        {
          switch(les_parametres_solveur.search(motlu))
            {
            case 16:
              {
                fixer_limpr(-1);
                break;
              }
            case 0:
              {
                fixer_limpr(1);
// Si MUMPS on ajoute des impressions sur la decomposition
                if (solveur_direct_==mumps)
                  add_option("mat_mumps_icntl_4","3");
                else if (solveur_direct_==superlu_dist)
                  add_option("mat_superlu_dist_statprint","");
                else if (solveur_direct_==petsc)
                  {}
                else if (solveur_direct_==umfpack)
                  add_option("mat_umfpack_prl","2");
                else if (solveur_direct_==pastix)
                  add_option("mat_pastix_verbose","2");
                else if (solveur_direct_==cholmod)
                  add_option("mat_cholmod_print","3");
                else if (solveur_direct_)
                  {
                    Cerr << "impr not coded yet for this direct solver." << finl;
                    Process::exit();
                  }
                break;
              }
            case 1:
            case 21:
              {
                if (solveur_direct_)
                  {
                    Cerr << "Definition of " << les_parametres_solveur(les_parametres_solveur.search(motlu)) << " is useless for a direct method." << finl;
                    Cerr << "Suppress the keyword." << finl;
                    exit();
                  }
                is >> seuil_;
                convergence_with_seuil=1;
                if (amgx_)
                  {
                    amgx_option+="s:convergence=ABSOLUTE\ns:tolerance=";
                    amgx_option+=Nom(seuil_,"%e")+"\n";
                  }
                break;
              }
            case 2:
              {
                is >> pc;
                is >> motlu;
                if (motlu != accolade_ouverte)
                  {
                    Cerr << "Error while reading the parameters of the PETSC preconditioner: precond " << pc << " { ... }" << finl;
                    Cerr << "We expected " << accolade_ouverte << " instead of " << motlu << finl;
                    exit();
                  }
                is >> motlu;
                while (motlu!=accolade_fermee)
                  {
                    Motcles les_parametres_precond(4);
                    {
                      les_parametres_precond[0] = omega.name;
                      les_parametres_precond[1] = level.name;
                      les_parametres_precond[2] = epsilon.name;
                      les_parametres_precond[3] = ordering.name;
                    }
                    double tmp_int;
                    double tmp_double;
                    Nom tmp_string;
                    switch(les_parametres_precond.search(motlu))
                      {
                      case 0:
{
                          is >> tmp_double;
                          omega.value()=tmp_double;
                          omega.defined=1;
                          break;
                        }
                      case 1:
{
                          is >> tmp_int   ;
                          level.value()=(int)tmp_int;
                          level.defined=1;
                          if (amgx_)
{
                              Nom ilu_sparsity_level="p:ilu_sparsity_level=";
                              ilu_sparsity_level+=(Nom)level.value();
                              amgx_option+=ilu_sparsity_level+"\n";
                              Nom coloring_level="p:coloring_level="; //!< 1 par defaut
                              coloring_level+=Nom(level.value()+1);    //!< Doit valoir ilu_sparsity_level+1 pour MULTICOLOT_INU (voir AmgX reference guide)
                              amgx_option+=coloring_level+"\n";
                            }
                          break;
                        }
                      case 2:
{
                          is >> tmp_double;
                          epsilon.value()=tmp_double;
                          epsilon.defined=1;
                          break;
                        }
                      case 3:
{
                          is >> tmp_string;
                          ordering.value()=tmp_string;
                          ordering.defined=1;
                          break;
                        }
                      default:
{
                          Cerr << motlu << " : unrecognized option among all of those possible on Petsc preconditioner:" << finl;
                          Cerr << les_parametres_precond << finl;
                          Process::exit();
                        }
                      }
                    is >> motlu;
                  }
                break;
              }
            case 3:
              {
                pc="null";
                break;
              }
            case 4:
              {
                is >> nb_it_max_;
                convergence_with_nb_it_max_=1;
                if (amgx_)
                  {
                    amgx_option+="s:max_iters=";
                    amgx_option+=Nom(nb_it_max_)+"\n";
                  }
                break;
              }
            case 15:
              {
                save_matrice_=1;
                break;
              }
            case 5:
              {
// on sauvegarde au format petsc
                save_matrix_=1;
                break;
              }
            case 26:
              {
// on sauvegarde au format matrix market
                save_matrix_=2;
                break;
              }
            case 6:
              {
                if (Process::nproc()>1)
                  {
                    Cerr << "factored_matrix option is not available for parallel calculation." << finl;
                    exit();
                  }
                if (solveur_direct_!=petsc)
                  {
// Switch to PETSc Cholesky cause MUMPS or SUPERLU don't give access to LU ?
                    Cerr << "Only cholesky_lapack keyword may be used with the option factored_matrix." << finl;
                    exit();
                  }
                is >> factored_matrix_;
                break;
              }
            case 7:
              {
                read_matrix_=1;
                break;
              }
            case 8:
              {
                is >> controle_residu_;
                break;
              }
            case 9:
              {
                is >> motlu; //!< On lit l'accolade
                if (motlu != accolade_ouverte)
                  {
                    Cerr << "We expected " << accolade_ouverte << " instead of " << motlu << finl;
                    exit();
                  }
                Cerr << "Reading of the Petsc commands:" << finl;
                Nom valeur;
                is >> motlu;
                while (motlu!=accolade_fermee)
                  {
                    is >> valeur;
// "-option val" ou "-option" ?
// adding a test to support negative value
                    bool negative_value = is_number(valeur.getSuffix("-").getString());
                    if ((valeur.debute_par("-") && !negative_value) || valeur==accolade_fermee)
                      {
                        add_option(motlu.suffix("-"), "");
                        motlu = valeur;
                      }
                    else
                      {
                        add_option(motlu.suffix("-"), valeur);
                        is >> motlu;
                      }
                  }
                if (limpr()>-1)
                  fixer_limpr(1); //!< On imprime le residu si CLI Pour faciliter le debugage:
//
                if (rang == 18) //!< Verbose
                  {
                    add_option("ksp_view", "");
                    add_option("options_view", "");
                    add_option("options_left", "");
                  }
                break;
              }
            case 10:
              {
                is >> motlu;
// Si pas MUMPS on previent
                if (solveur_direct_!=mumps)
                  {
                    Cerr << "Ordering keyword for a solver is limited to Cholesky only." << finl;
                    Process::exit();
                  }
                Motcles mumps_ordering(6);
                {
// NB: Il y'a d'autres ordering (voir doc MUMPS)
                  mumps_ordering[0] = "amd";
                  mumps_ordering[1] = "pt-scotch";
                  mumps_ordering[2] = "parmetis";
                  mumps_ordering[3] = "scotch";
                  mumps_ordering[4] = "pord";
                  mumps_ordering[5] = "metis";
                }
                int rang_mumps=mumps_ordering.search(motlu);
// MUMPS fait un choix automatique par defaut (selon type et taille de la matrice, et nombre de processeurs) mais a savoir que:
// Sur le cas Cx et PAR_Cx 4 cores, Scotch en sequentiel et PT-Scotch en parallele sont les meilleurs choix
// Sur les gros cas, parfois Metis plus rapide pour A=LU et Scotch pour x=A-1B...
                if (rang_mumps==-1)
                  {
                    Cerr << motlu << " : unrecognized ordering from those available for the MUMPS solver Cholesky:" << finl;
                    Cerr << mumps_ordering << finl;
                    Process::exit();
                  }
                else if (rang_mumps==1 || rang_mumps==2)
                  {
                    if (Process::nproc()==1)
                      {
                        Cerr << "You can't use the parallel ordering " << motlu << " during a sequential calculation." << finl;
                        Process::exit();
                      }
                    add_option("mat_mumps_icntl_28","2");  //!< Parallel analysis
                    add_option("mat_mumps_icntl_29",(Nom)rang_mumps);        //!< Parallel ordering
                  }
                else
                  {
                    add_option("mat_mumps_icntl_28","1");  //!< Sequential analysis
                    add_option("mat_mumps_icntl_7",(Nom)rang_mumps); //!< Sequential ordering
                  }
                break;
              }
            case 11:
              {
                is >> petsc_decide_;
                different_partition_ = petsc_decide_; //!< If Petsc decides the matrix partition, the partition is often different than the TRUST partition
                break;
              }
            case 12:
              {
                mataij_=1;
                break;
              }
            case 13:
              {
                is >> motlu;
                is >> petsc_nb_cpus_;
                different_partition_ = 1; //!< If user decides a different number of CPUs to solve PETSc matrix, the matrix partition will be different than the TRUST partition
                if (motlu=="first")
                  petsc_cpus_selection_=1;
                else if (motlu=="every")
                  petsc_cpus_selection_=2;
                else
                  {
                    Cerr << "We should read the option first or every after the keyword nb_cpus." << finl;
                    Cerr << "Or we read: " << motlu << finl;
                    exit();
                  }
                if (petsc_nb_cpus_<1 || petsc_nb_cpus_>Process::nproc())
                  {
                    Cerr << "Incorrect number of CPUs selected for solving the PETSc matrix: " << petsc_nb_cpus_ << finl;
                    exit();
                  }
                break;
              }
            case 14:
              {
                is >> divtol_; //!< See http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/KSP/KSPSetTolerances.html
                break;
              }
            case 17:
              {
                KSPType type_ksp_method;
                KSPGetType(SolveurPetsc_, &type_ksp_method);
                if ((Nom)type_ksp_method != Nom("gmres") && ((Nom)type_ksp_method != Nom("fgmres")))
                  {
                    Cerr << "restart option is available only with [f]gmres methods" << finl;
                    exit();
                  }
                int restart_gmres;
                is >> restart_gmres;
                KSPGMRESSetRestart(SolveurPetsc_,restart_gmres);
                break;
              }
            case 19:
              {
// Si pas MUMPS on previent
                if (solveur_direct_!=mumps)
                  {
                    Cerr << les_parametres_solveur[rang] << " keyword for a solver is limited to " << les_solveurs[14] << " only." << finl;
                    Process::exit();
                  }
                double dropping_parameter;
                is >> dropping_parameter;
                add_option("mat_mumps_cntl_7",dropping_parameter);    //!< Dropping parameter
                break;
              }
            case 20:
              {
                if (solveur_direct_)
                  {
                    Cerr << "Definition of " << les_parametres_solveur(les_parametres_solveur.search(motlu)) << " is useless for a direct method." << finl;
                    Cerr << "Suppress the keyword." << finl;
                    exit();
                  }
                is >> seuil_relatif_;
                convergence_with_seuil=1;
                if (amgx_)
                  {
                    amgx_option+="s:convergence=RELATIVE_INI_CORE\ns:tolerance=";
                    amgx_option+=Nom(seuil_relatif_,"%e")+"\n";
                  }
                break;
              }
            case 22:
              int flag;
              is >> flag;
              ignore_new_nonzero_ = (bool)flag;
              break;
            case 23:
              is >> flag;
              rebuild_matrix_ = (bool)flag;
              break;
            case 24:
              is >> flag;
              allow_realloc_ = (bool)flag;
              break;
            case 25:
              is >> flag;
              clean_matrix_ = (bool)flag;
              break;
            case 27:
              set_reuse_preconditioner(true);
              break;
            default:
              {
                Cerr << motlu << " : unrecognized option from those available in the Petsc solver:" << finl;
                Cerr << les_parametres_solveur << finl;
                Process::exit();
              }
            }
          is >> motlu;
        }
// Some checks
      if (petsc_decide_ && petsc_cpus_selection_)
        {
          Cerr << "You can't use petsc_decide and nb_cpus option together." << finl;
          exit();
        }
      int pc_supported_on_gpu_by_petsc=0;
      int pc_supported_on_gpu_by_amgx=0;
      Motcles les_precond(13);
      {
        les_precond[0] = "NULL";               //!< Pas de preconditionnement
        les_precond[1] = "ILU";                //!< Incomplete LU
        les_precond[2] = "SSOR";               //!< Symetric Successive Over Relaxation
        les_precond[3] = "EISENSTAT";          //!< Symetric Successive Over Relaxation avec Eiseinstat trick
        les_precond[4] = "SPAI";               //!< Sparse Approximate Inverse
        les_precond[5] = "PILUT";              //!< Dual-threshold incomplete LU factorisation
        les_precond[6] = "DIAG";               //!< Diagonal precondtioner
        les_precond[7] = "BOOMERAMG";          //!< Multigrid preconditioner
        les_precond[8] = "BLOCK_JACOBI_ICC";   //!< Block Jacobi ICC preconditioner (code dans PETSc, optimise)
        les_precond[9] = "BLOCK_JACOBI_ILU";   //!< Block Jacobi ILU preconditioner (code dans PETSc, optimise)
        les_precond[10] = "C-AMG";    //!< Classical AMG
        les_precond[11] = "SA-AMG";   //!< Aggregated AMG
        les_precond[12] = "GS";   //!< Gauss-Seidel
      }
      if (pc!="")
        {
// On empeche le choix d'un preconditionneur avec une methode directe
// puisque celle ci EST le preconditionneur KSPREONLY
          if (solveur_direct_)
            {
              Cerr << "Using precond keyword with a direct method like Cholesky is useless" << finl;
              Cerr << "because for PETSc the LU factorization is used as a preconditioner." << finl;
              exit();
            }
// Option du preconditionneur
          rang = les_precond.search(pc);
          switch(rang)
            {
            case 0:
              {
                PCSetType(PreconditionneurPetsc_, PCNONE);
                pc_supported_on_gpu_by_petsc=1;
                pc_supported_on_gpu_by_amgx=1;
                if (amgx_)
                  {
                    amgx_option+="s:preconditioner(p)=NOSOLVER\n";
                  }
                check_not_defined(omega);
                check_not_defined(level);
                check_not_defined(epsilon);
                check_not_defined(ordering);
                break;
              }
            case 1:
              {
// Cout << "See http://www.ncsa.uiuc.edu/UserInfo/Resources/Software/Math/HYPRE/docs-1.6.0/HYPRE_usr_manual/node33.html" << finl;
// Cout << "to have some advices on the incomplete LU factorisation level: ILU(level)" << finl;
// On n'attaque pas le ILU de Petsc qui n'est pas parallele
// On prend celui de Hypre (Euclid=PILU(k)) en passant par les commandes en ligne
// car peu de parametres peuvent etre fixes sinon
// PCSetType(PreconditionneurPetsc_, PCHYPRE);
// PCHYPRESetType(PreconditionneurPetsc_, "euclid");
// add_option("pc_hypre_euclid_levels",(Nom)level.value());
// check_not_defined(omega);
// check_not_defined(epsilon);
// check_not_defined(ordering);
//
// CHANGES in the PETSc 3.6 version: Removed -pc_hypre_type euclid due to bit-rot
                pc_supported_on_gpu_by_amgx=1;
                if (amgx_)
                  {
                    amgx_option+="s:preconditioner(p)=MULTICOLOR_DILU\n"; //!< Converge mal...
                  }
                else if (gpu_)
                  {
                    add_option("pc_type","ilu");
                    add_option("pc_factor_mat_solver_type","cusparse");
                    add_option("pc_factor_levels",(Nom)level.value());
                  }
                else
                  {
                    Cerr << "Error: CHANGES in the PETSc 3.6 version: Removed -pc_hypre_type euclid due to bit-rot."
                         << finl;
                    Cerr << "So the ILU { level k } preconditioner no longer available. " << finl;
                    Cerr << "Change your data file." << finl;
                    Process::exit();
                  }
                break;
              }
            case 2:
              {
                PCSetType(PreconditionneurPetsc_, PCSOR);
                if (amgx_) Process::exit("SSOR is not available on GPU, try GS (Gauss Seidel)");
                if (omega.value()>=1. && omega.value()<=2.)
                  {
                    PCSORSetOmega(PreconditionneurPetsc_, omega.value());
                  }
                else
                  {
                    Cerr << "omega value for SSOR should be between 1 and 2" << finl;
                    exit();
                  }
                pc_supported_on_gpu_by_amgx=0;
                check_not_defined(level);
                check_not_defined(epsilon);
                check_not_defined(ordering);
                break;
              }
            case 3:
              {
                PCSetType(PreconditionneurPetsc_, PCEISENSTAT);
                if (omega.value()>=1. && omega.value()<=2.)
                  {
                    PCEisenstatSetOmega(PreconditionneurPetsc_, omega.value());
                  }
                else
                  {
                    Cerr << "omega value for EISENSTAT should be between 1 and 2" << finl;
                    exit();
                  }
                check_not_defined(level);
                check_not_defined(epsilon);
                check_not_defined(ordering);
                break;
              }
            case 4:
              {
                PCSetType(PreconditionneurPetsc_, PCHYPRE);
                PCHYPRESetType(PreconditionneurPetsc_, "parasails");
                add_option("pc_hypre_parasails_nlevels",(Nom)level.value());     //!< Higher values of level [>=0] leads to more accurate, but more expensive preconditioners (default 1)
                add_option("pc_hypre_parasails_thresh",(Nom)epsilon.value());   //!< Lower values of eps [0-1] leads to more accurate, but more expensive preconditioners (default 0.1)
                add_option("pc_hypre_parasails_sym","SPD"); //!< Matrice symetrique definie positive
                check_not_defined(omega);
                check_not_defined(ordering);
                break;
              }
            case 5:
              {
                PCSetType(PreconditionneurPetsc_, PCHYPRE);
                PCHYPRESetType(PreconditionneurPetsc_, "pilut");
                add_option("pc_hypre_pilut_factorrowsize",(Nom)level.value());        //!< Maximum nonzeros retained in each row of L and U (default 20)
                add_option("pc_hypre_pilut_tol",(Nom)epsilon.value());                //!< Values below the value are dropped in L and U (default 1.e-7)
                check_not_defined(omega);
                check_not_defined(ordering);
//
// ERROR VALGRIND
// Cerr << "Error VALGRIND with PETSc Dual Threashold Incomplete LU factorization." << finl;
// Cerr << "So the PILUT { level k epsilon thresh } preconditioner no longer available. " << finl;
// Cerr << "Change your data file." << finl;
// Process::exit();
                break;
              }
            case 6:
              {
                PCSetType(PreconditionneurPetsc_, PCJACOBI);
                pc_supported_on_gpu_by_petsc=1;
                pc_supported_on_gpu_by_amgx=1;
                if (amgx_)
                  {
                    amgx_option += "s:preconditioner(p)=BLOCK_JACOBI\n";
                    Process::exit("Diagonal preconditioner on GPU with AmgX is slow to converge. Try GS (Gauss-Seidel) preconditioner.");
                  }
                check_not_defined(omega);
                check_not_defined(level);
                check_not_defined(epsilon);
                check_not_defined(ordering);
                break;
              }
            case 9: //!< ilu
            case 8: //!< icc
              {
                if (rang==9) preconditionnement_non_symetrique_ = 1;
                pc_supported_on_gpu_by_amgx=1;
                pc_supported_on_gpu_by_petsc=1;
                if (amgx_)
                  amgx_option+="s:preconditioner(p)=MULTICOLOR_DILU\n"; //!< MULTICOLOR_ILU plante...
                else
                  {
                    add_option("sub_pc_type",rang==8 ? "icc" : "ilu");
                    add_option("sub_pc_factor_levels",(Nom)level.value());
// On fixe le precondtionnement non symetrique pour appliquer eventuellement un ordering autre que celui par defaut (natural)
// Un ordering rcm peut ameliorer par exemple la convergence
// Voir le remplissage de la matrice avec -mat_view_draw -draw_pause -1
                    if (ordering.value()!="")
                      {
                        add_option("sub_pc_factor_mat_ordering_type",ordering.value());
// Le preconditionnement natural (defaut) ne necessite pas une matrice de preconditionnement symetrique, les autres si:
                        preconditionnement_non_symetrique_=1;
                      }
                  }
                PCSetType(PreconditionneurPetsc_, PCBJACOBI);
                check_not_defined(omega);
                check_not_defined(epsilon);
                break;
              }
            case 7:
              {
                PCSetType(PreconditionneurPetsc_, PCHYPRE);
                PCHYPRESetType(PreconditionneurPetsc_, "boomeramg"); //!< Classical C-AMG Changement pc_hypre_boomeramg_relax_type_all pour PETSc 3.10, la matrice de preconditionnement etant seqaij, symetric-SOR/jacobi (defaut) provoque KSP_DIVERGED_INDEFINITE_PC Voir: https://lists.mcs.anl.gov/mailman/htdig/petsc-users/2012-December/015922.html
//
//
//
                add_option("pc_hypre_boomeramg_relax_type_all", "Jacobi");
// Voir https://mooseframework.inl.gov/application_development/hypre.html
                if (dimension==3) Cerr << "Warning, on massive parallel calculation for best performance, consider playing with -pc_hypre_boomeramg_strong_threshold 0.7 or 0.8 or 0.9" << finl;
                check_not_defined(omega);
                check_not_defined(level);
                check_not_defined(epsilon);
                check_not_defined(ordering);
                /*
                add_option("pc_hypre_boomeramg_max_iter","1");
                add_option("pc_hypre_boomeramg_strong_threshold","0.7");
                add_option("pc_hypre_boomeramg_grid_sweeps_up","1");
                add_option("pc_hypre_boomeramg_grid_sweeps_down","1");
                add_option("pc_hypre_boomeramg_agg_nl","2");
                add_option("pc_hypre_boomeramg_agg_num_paths","1");
                add_option("pc_hypre_boomeramg_max_levels","25");
                add_option("pc_hypre_boomeramg_coarsen_type","HMIS");
                add_option("pc_hypre_boomeramg_interp_type","ext+i");
                add_option("pc_hypre_boomeramg_P_max","2");
// Page 16: https://prace-ri.eu/wp-content/uploads/WP294-PETSc4FOAM-A-Library-to-plug-in-PETSc-into-the-OpenFOAM-Framework.pdf
                add_option("pc_hypre_boomeramg_truncfactor","0.2");*/
                break;
              }
            case 10: //!< Classical AMG
            case 11: //!< Aggregated AMG
              {
                pc_supported_on_gpu_by_amgx=1;
                pc_supported_on_gpu_by_petsc=1;
                preconditionnement_non_symetrique_ = 1;
                if (amgx_)
                  {
                    amgx_option+="s:preconditioner(p)=AMG\n";
                    amgx_option+="s:use_scalar_norm=1\n";
                    amgx_option+="p:error_scaling=0\n";
                    amgx_option+="p:print_grid_stats=1\n";
                    amgx_option+="p:max_iters=1\n";
                    amgx_option+="p:cycle=V\n";
                    amgx_option+="p:min_coarse_rows=2\n";
                    amgx_option+="p:max_levels=100\n";
                    amgx_option+="p:smoother(smoother)=BLOCK_JACOBI\n";
                    amgx_option+="p:presweeps=1\n";
                    amgx_option+="p:postsweeps=1\n";
                    amgx_option+="p:coarsest_sweeps=1\n";
                    amgx_option+="p:coarse_solver=DENSE_LU_SOLVER\n";
                    amgx_option+="p:dense_lu_num_rows=2\n";
                    if (rang==10) //!< C-AMG
                      {
                        amgx_option+="p:algorithm=CLASSICAL\n";
                        amgx_option+="p:selector=HMIS\n";
                        amgx_option+="p:interpolator=D2\n";
                        amgx_option+="p:strength=AHAT\n";
                      }
                    else //!< SA-AMG
                      {
                        amgx_option+="p:algorithm=AGGREGATION\n";
                        amgx_option+="p:selector=SIZE_2\n";
                        amgx_option+="p:max_matching_iterations=100000\n";
                        amgx_option+="p:max_unassigned_percentage=0.0\n";
                      }
                    amgx_option+="smoother:relaxation_factor=0.8\n";
                  }
                else
                  {
// ToDo : trouver des parametres pour PETSc afin d'avoir une comparaison possible CPU vs GPU (meme its par exemple):
                    add_option("pc_type","gamg");
                    if (rang==10) //!< C-AMG
                      {
                        add_option("pc_gamg_type","classical");
                      }
                    else //!< SA-AMG
                      {
                        add_option("pc_gamg_type","agg");
                        add_option("pc_gamg_agg_nsmooths","0");
// add_option("pc_gamg_agg_nsmooths","1"); //Crash
                      }
                  }
                break;
              }
            case 12:
              {
                if (!amgx_) Process::exit("GS (Gauss-Seidel) not available yet.");
                if (omega.value()<0 || omega.value()>2)
                  {
                    Cerr << "Relaxation value omega for GS should be between 0 and 2" << finl;
                    exit();
                  }
                pc_supported_on_gpu_by_amgx=1;
                if (amgx_)
                  {
                    amgx_option+="s:preconditioner(p)=GS\n"; //!< Non documente... amgx_option+="s:preconditioner(p)=MULTICOLOR_GS\n"; // MULTICOLOR_GS lent dans AmgX ?
//
                    Nom relaxation_factor="p:relaxation_factor="; //!< Defaut 0.9
                    relaxation_factor+=Nom(omega.value());
                    amgx_option+=relaxation_factor+"\n";
                    if (matrice_symetrique_) amgx_option+="p:symmetric_GS=1\n";
                  }
                check_not_defined(level);
                check_not_defined(epsilon);
                check_not_defined(ordering);
                break;
              }
            default:
              {
                Cerr << pc << " : preconditioner not officially recognized by TRUST among those possible for the moment:" << finl;
                Cerr << les_precond << finl;
                Cerr << "You can try to access directly to Petsc preconditioners with the command line." << finl;
                Cerr << "See the reference manual of Petsc to do this." << finl;
                Process::exit();
              }
            }
        }
      else
        {
          if (!solveur_direct_)
            {
              Cerr << "You forgot to define a preconditioner with the keyword precond." << finl;
              Cerr << "If you don't want a preconditioner, add for the solver definition:" << finl;
              Cerr << "precond null" << finl;
              Process::exit();
            }
          else
            {
// Pour un solveur direct le preconditionner EST le solveur:
              pc_supported_on_gpu_by_petsc = solver_supported_on_gpu_by_petsc;
              pc_supported_on_gpu_by_amgx = solver_supported_on_gpu_by_amgx;
            }
        }
// On verifie que les preconditionneurs sont supportes sur GPU:
      if (gpu_ && pc_supported_on_gpu_by_petsc==0)
        {
          Cerr << les_precond[rang] << " is not supported yet by PETSc on GPU." << finl;
          Process::exit();
        }
      if (amgx_ && pc_supported_on_gpu_by_amgx==0)
        {
          Cerr << les_precond[rang] << " is not supported yet by AmgX on GPU." << finl;
          Process::exit();
        }
    }
// On fixe des parametres du solveur et du preconditionneur selon que l'on ait un solveur direct ou iteratif
// KSPSetInitialGuessNonzero : Resout Ax=B en supposant x nul ou non
// KSPSetTolerances : Pour fixer les criteres de convergence du solveur iteratif
  if (solveur_direct_)
    {
      KSPSetInitialGuessNonzero(SolveurPetsc_, PETSC_FALSE);
      PCSetType(PreconditionneurPetsc_, PCLU);
    }
  else
    {
      KSPSetInitialGuessNonzero(SolveurPetsc_, PETSC_TRUE);
      if (convergence_with_nb_it_max_)
        {
          if (convergence_with_seuil)
            {
              Cerr << "You can only define solver convergence either by seuil or by nb_it_max." << finl;
              Cerr << "So suppress seuil keyword or nb_it_max keyword." << finl;
              exit();
            }
// Convergence is defined with nb_it_max, the norm is checked after nb_it_max iterations:
          seuil_ = DMAXFLOAT;
          add_option("ksp_check_norm_iteration",(Nom)(nb_it_max_-1));
          nb_it_max_ = NB_IT_MAX_DEFINED;
        }
// Convergence si residu(it) < MAX (seuil_relatif_ * residu(0), seuil_);
      if (seuil_==0 && seuil_relatif_==0) seuil_=1.e-12; //!< Si aucun seuil defini, on prend un seuil absolu de 1.e-12 (comme avant)
      KSPSetTolerances(SolveurPetsc_, seuil_relatif_, seuil_, (divtol_==0 ? PETSC_DEFAULT : divtol_), nb_it_max_);
    }
// Change le calcul du test de convergence relative (||Ax-b||/||Ax(0)-b|| au lieu de ||Ax-b||/||b||)
// Peu utilisee dans TRUST car on utilise la convergence sur la norme absolue
// Mais cela corrige une erreur KSP_DIVERGED_DTOL quand ||Ax-b||/||b||>10000=div_tol par defaut dans PETSc (rencontree sur Etude REV_4)
// add_option(sys, "ksp_converged_use_initial_residual_norm",1); // Before PETSc 3.5
  KSPConvergedDefaultSetUIRNorm(SolveurPetsc_); //!< After PETSc 3.5, a function is available
// Surcharge eventuelle par la ligne de commande
  KSPSetOptionsPrefix(SolveurPetsc_, option_prefix_);
  KSPSetFromOptions(SolveurPetsc_);
  PCSetOptionsPrefix(PreconditionneurPetsc_, option_prefix_);
  PCSetFromOptions(PreconditionneurPetsc_);
// Setting the names:
  KSPType type_ksp;
  KSPGetType(SolveurPetsc_, &type_ksp);
  type_ksp_=(Nom)type_ksp;
  PCType type_pc;
  PCGetType(PreconditionneurPetsc_, &type_pc);
  type_pc_=(Nom)type_pc;
// Creation du fichier de config .amgx (NB: les objets PETSc sont crees mais ne seront pas utilises)
  if (amgx_ && Process::je_suis_maitre())
    {
      SFichier s(config());
// Syntax: See https://github.com/NVIDIA/AMGX/raw/master/doc/AMGX_Reference.pdf
      s << "# AmgX config file" << finl << "config_version=2" << finl << amgx_option;
      if (!amgx_option.contient("s:print_config"))     s << "s:print_config=1" << finl;
      if (!amgx_option.contient("s:store_res_history")) s << "s:store_res_history=1" << finl;
      if (!amgx_option.contient("s:monitor_residual"))  s << "s:monitor_residual=1" << finl;
      if (!amgx_option.contient("s:print_solve_stats")) s << "s:print_solve_stats=1" << finl;
      if (!amgx_option.contient("s:obtain_timings"))    s << "s:obtain_timings=1" << finl;
      if (!amgx_option.contient("s:max_iters"))         s << "s:max_iters=10000" << finl; //!< 100 par defaut trop bas...
      s << "# determinism_flag=1" << finl; //!< Plus lent de 15% mais resultat deterministique et repetable
      s << "# communicator=MPI_DIRECT" << finl; //!< MPI_CUDA aware
      Cerr << "Writing the AmgX config file: " << config() << finl;
    }
#else
  Cerr << "Error, the code is not built with PETSc support." << finl;
  Cerr << "Contact TRUST support." << finl;
  Process::exit();
#endif
}
References allow_realloc_, amgx_, Cerr, check_not_defined(), cholmod, clean_matrix_, cli, config(), PE_Groups::current_group(), option::defined, Objet_U::dimension, Objet_U::disable_TU, DMAXFLOAT, Entree_Fichier_base::eof(), Process::exit(), finl, SolveurSys_base::fixer_limpr(), Entree_Fichier_base::get_ifstream(), PE_Groups::get_nb_groups(), gpu_, ignore_new_nonzero_, Process::je_suis_maitre(), SolveurSys_base::limpr(), mumps, option::name, NB_IT_MAX_DEFINED, Objet_U::nom_du_cas(), Objet_U::nommer(), Process::nproc(), numero_solveur, pastix, petsc, read_matrix_, rebuild_matrix_, ref_cast, SolveurSys_base::save_matrice_, Motcles::search(), SolveurSys_base::set_reuse_preconditioner(), sub_type, superlu_dist, umfpack, valeur(), option_string::value(), option_int::value(), option_double::value(), and verbose.
Referenced by Solv_AMGX::readOn(), readOn(), and Solv_Petsc_GPU::readOn().
cree_instance()
Objet_U * Solv_Petsc::cree_instance () static
Definition at line 43 of file Solv_Petsc.cpp.
duplique()
int Solv_Petsc::duplique () const override virtual
Implements Objet_U.
Reimplemented in Solv_Petsc_GPU.
Definition at line 43 of file Solv_Petsc.cpp.
get_info()
const Type_info * Solv_Petsc::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_Petsc_GPU.
Definition at line 43 of file Solv_Petsc.cpp.
info()
const Type_info * Solv_Petsc::info () static
Definition at line 43 of file Solv_Petsc.cpp.
printOn()
Sortie & Solv_Petsc::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_Petsc_GPU.
Definition at line 46 of file Solv_Petsc.cpp.
{
  s << chaine_lue_;
  return s;
}
References chaine_lue_.
read_matrix()
bool Solv_Petsc::read_matrix () const inline
Definition at line 56 of file Solv_Petsc.h.
  {
    return read_matrix_ == 1;
  }
References read_matrix_.
readOn()
Entree & Solv_Petsc::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Solv_Petsc_GPU.
Definition at line 53 of file Solv_Petsc.cpp.
{
  create_solver(is);
  return is;
}
References create_solver().
reset()
void Solv_Petsc::reset () inline
Definition at line 192 of file Solv_Petsc.h.
{
#ifdef PETSCKSP_H
  if (SolveurPetsc_!=NULL)
    {
      KSPDestroy(&SolveurPetsc_);
      finalize();
    }
  if (MatricePetsc_!=NULL)
    {
// Destruction des vecteurs
      VecDestroy(&SecondMembrePetsc_);
      VecDestroy(&SolutionPetsc_);
      if (LocalSolutionPetsc_!=NULL)
        {
          VecDestroy(&LocalSolutionPetsc_);
          VecScatterDestroy(&VecScatter_);
        }
// Destruction matrice
      MatDestroy(&MatricePetsc_);
// Destruction DM
      if (dm_!=NULL)
        DMDestroy(&dm_);
    }
  initialize();
#endif
}
Referenced by ~Solv_Petsc().
resoudre_systeme() [1/2]
int Solv_Petsc::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
Definition at line 1573 of file Solv_Petsc.cpp.
{
#ifdef PETSCKSP_H
// Si on utilise un solver petsc on le signale pour les stats finales
  statistiques().begin_count(solv_sys_petsc_counter_);
  statistiques().end_count(solv_sys_petsc_counter_,1,1);
  double start = Statistiques::get_time_now();
  if (nouvelle_matrice())
    {
      matrice_symetrique_ = 1;      //!< On suppose que la matrice est symetrique
// Construction de la numerotation globale:
      construit_renum(secmem);
// Matrice morse intermedaire de conversion
      Matrice_Morse matrice_morse_intermediaire;
      if (read_matrix_)
        {
// New in 1.6.9, it is possible to read the matrix
// Read the PETSc matrix
          RestoreMatrixFromFile();
          int nb_local_rows, nb_local_cols;
          MatGetLocalSize(MatricePetsc_, &nb_local_rows, &nb_local_cols);
          if (nb_local_rows != nb_items_to_keep_)
            {
              Cerr << "The matrix read has " << nb_local_rows << " local columns whereas" << finl;
              Cerr << "the RHS/Solution vectors have a size of " << nb_items_to_keep_ << "." << finl;
              Cerr << "Check your data file or the file containing the PETSc matrix." << finl;
              exit();
            }
        }
      else if (sub_type(Matrice_Petsc, la_matrice))
        {
// Matrice deja au format Petsc
          MatricePetsc_ = ref_cast(Matrice_Petsc, la_matrice).getMat();
          read_matrix_ = 1; //!< flag reutilise comme si on avait lu la matrice
        }
      else if (sub_type(Matrice_Morse_Sym, la_matrice))
        {
// Exemple: matrice de pression en VEFPreP1B
          const Matrice_Morse_Sym& matrice_morse_sym = ref_cast(Matrice_Morse_Sym, la_matrice);
          assert(matrice_morse_sym.get_est_definie());
          MorseSymToMorse(matrice_morse_sym, matrice_morse_intermediaire);
        }
      else if (sub_type(Matrice_Bloc_Sym, la_matrice))
        {
// Exemple : matrice de pression en VEF P0+P1+Pa
          const Matrice_Bloc_Sym& matrice = ref_cast(Matrice_Bloc_Sym, la_matrice);
// Conversion de la matrice Matrice_Bloc_Sym au format Matrice_Morse_Sym
          Matrice_Morse_Sym matrice_morse_sym;
          matrice.BlocSymToMatMorseSym(matrice_morse_sym);
          MorseSymToMorse(matrice_morse_sym, matrice_morse_intermediaire);
          matrice_morse_sym.dimensionner(0, 0); //!< Destruction de la matrice morse sym desormais inutile
        }
      else if (sub_type(Matrice_Morse, la_matrice))
        {
// Exemple : matrice implicite
          matrice_symetrique_ = 0;
        }
      else if (sub_type(Matrice_Bloc, la_matrice))
        {
// Exemple : matrice de pression en VDF
          const Matrice_Bloc& matrice_bloc = ref_cast(Matrice_Bloc, la_matrice);
          if (!sub_type(Matrice_Morse_Sym, matrice_bloc.get_bloc(0, 0).valeur()))
            matrice_symetrique_ = 0;
          else
            {
// Pour un solveur direct, operation si la matrice n'est pas definie (en incompressible VDF, rien n'etait fait...)
              Matrice_Morse_Sym& mat00 = ref_cast_non_const(Matrice_Morse_Sym, matrice_bloc.get_bloc(0, 0).valeur());
              if (solveur_direct_ && mat00.get_est_definie() == 0 && Process::je_suis_maitre())
                mat00(0, 0) *= 2;
            }
          matrice_bloc.BlocToMatMorse(matrice_morse_intermediaire);
        }
      else
        {
          Cerr << "Solv_Petsc : Warning, we do not know yet treat a matrix of type " << la_matrice.que_suis_je()
               << finl;
          exit();
        }
      if (verbose) Cout << "[Petsc] Time to convert matrix: \t" << Statistiques::get_time_now() - start << finl;
// Verification stockage de la matrice
      check_aij(matrice_morse_intermediaire);
      bool la_matrice_est_morse_non_symetrique =
        sub_type(Matrice_Morse, la_matrice) && !sub_type(Matrice_Morse_Sym, la_matrice);
      const Matrice_Morse& matrice_morse = la_matrice_est_morse_non_symetrique ? ref_cast(Matrice_Morse, la_matrice)
                                           : matrice_morse_intermediaire;
// Verification stencil de la matrice
      nouveau_stencil_ = (MatricePetsc_ == NULL ? true : check_stencil(matrice_morse));
      if (SecondMembrePetsc_ == NULL)
        {
// Build x and b during the first matrix creation
          Create_vectors(secmem);
// Creation de Champs (fields) pour pouvoir utiliser des preconditionneurs PCFIELDSPLIT
          Create_DM(secmem);
        }
// Construit ou update la matrice
      if (nouveau_stencil_)
        Create_objects(matrice_morse, secmem.line_size());
      else
        Update_matrix(MatricePetsc_, matrice_morse);
      /* reglage de BlockSize avec le line_size() du second membre */
      if (limpr() == 1)
        {
          Cout << "Order of the PETSc matrix : " << nb_rows_tot_ << " (~ "
               << (petsc_cpus_selection_ ? (int) (nb_rows_tot_ / petsc_nb_cpus_) : nb_rows_)
               << " unknowns per PETSc process ) " << (nouveau_stencil_ ? "New stencil." : "Same stencil.") << finl;
        }
    }
  start = Statistiques::get_time_now();
// Assemblage du second membre et de la solution
// ToDo calculer ix au moment de item_to_keep_
  int size=secmem.size_array();
  int colonne_globale=decalage_local_global_;
  ArrOfInt ix(size);
  for (int i=0; i<size; i++)
    if (items_to_keep_[i])
      {
        ix[i] = colonne_globale;
        colonne_globale++;
      }
    else
      ix[i] = -1;
  VecSetOption(SecondMembrePetsc_, VEC_IGNORE_NEGATIVE_INDICES, PETSC_TRUE);
  VecSetValues(SecondMembrePetsc_, size, ix.addr(), secmem.addr(), INSERT_VALUES);
  VecSetOption(SolutionPetsc_, VEC_IGNORE_NEGATIVE_INDICES, PETSC_TRUE);
  VecSetValues(SolutionPetsc_, size, ix.addr(), solution.addr(), INSERT_VALUES);
  VecAssemblyBegin(SecondMembrePetsc_);
  VecAssemblyEnd(SecondMembrePetsc_);
  VecAssemblyBegin(SolutionPetsc_);
  VecAssemblyEnd(SolutionPetsc_);
  if (verbose) Cout << "[Petsc] Time to update vectors: \t" << Statistiques::get_time_now() - start << finl;
// VecView(SecondMembrePetsc_,PETSC_VIEWER_STDOUT_WORLD);
// VecView(SolutionPetsc_,PETSC_VIEWER_STDOUT_WORLD);
// Save the matrix and the RHS
// if the matrix has changed...
  if (nouvelle_matrice())
    {
      start = Statistiques::get_time_now();
      if (save_matrix_==1)
        SaveObjectsToFile();
      else if (save_matrix_==2)
        {
// Format matrix market ToDo : method
          if (Process::nproc() > 1) Process::exit("Error, matrix market format is not available yet in parallel.");
          Nom filename(Objet_U::nom_du_cas());
          filename += "_matrix";
          filename += (Nom) instance;
          filename += ".mtx";
          SFichier mtx(filename);
          mtx.precision(14);
          mtx.setf(ios::scientific);
          PetscInt rows;
          const PetscInt *ia, *ja;
          PetscBool done;
          MatGetRowIJ(MatricePetsc_, 0, PETSC_FALSE, PETSC_FALSE, &rows, &ia, &ja, &done);
          if (!done) Process::exit("Error in MatGetRowIJ");
          PetscScalar *v;
          MatType mat_type;
          MatGetType(MatricePetsc_, &mat_type);
          Nom type;
          if (strcmp(mat_type, MATSEQAIJ) == 0)
            {
              type = "general";
              MatSeqAIJGetArray(MatricePetsc_, &v);
            }
          else if (strcmp(mat_type, MATSEQSBAIJ) == 0)
            {
              type = "symmetric";
              MatSeqSBAIJGetArray(MatricePetsc_, &v);
            }
          else Process::exit("Matrix type not supported.");
          mtx << "%%MatrixMarket matrix coordinate real " << type << finl;
          bool vectors = false; //!< Ecriture des vecteurs supporte par AmgX mais cela ne marche pas encore
          if (vectors)
            {
              Cerr << "Matrix (" << rows << " lines) written into file with RHS and solution: " << filename << finl;
              mtx << "%%matrix rhs solution" << finl;
            }
          else
            {
              Cerr << "Matrix (" << rows << " lines) written into file: " << filename << finl;
              mtx << "%%matrix" << finl;
            }
          mtx << rows << " " << rows << " " << ia[rows] << finl;
          for (int row=0; row<rows; row++)
            for (int j=ia[row]; j<ia[row+1]; j++)
              mtx << row+1 << " " << ja[j]+1 << " " << v[j] << finl;
          if (vectors)
            {
              mtx << "%%" << finl << "%% optional rhs " << secmem.size_array() << finl;
              for (int i = 0; i < secmem.size_array(); i++)
                mtx << secmem(i) << finl;
              mtx << "%%" << finl << "%% optional solution " << solution.size_array() << finl;
              for (int i = 0; i < solution.size_array(); i++)
                mtx << solution(i) << finl;
            }
          else
            {
// Provisoire: sauve un vector Petsc
              PetscViewer viewer;
              Nom rhs_filename(Objet_U::nom_du_cas());
              rhs_filename += "_rhs";
              rhs_filename += (Nom) instance;
              rhs_filename += ".petsc";
              PetscViewerBinaryOpen(PETSC_COMM_WORLD,rhs_filename,FILE_MODE_WRITE,&viewer);
              VecView(SecondMembrePetsc_, viewer);
              Cerr << "Save RHS into " << rhs_filename << finl;
              PetscViewerDestroy(&viewer);
            }
        }
      if (save_matrix_ && verbose) Cout << "[Petsc] Time to write matrix: \t" << Statistiques::get_time_now() - start << finl;
    }
//
// Solve the linear system
//
  PetscLogStagePush(KSPSolve_Stage_);
  int size_residu = nb_it_max_ + 1;
// DoubleTrav residu(size_residu); // bad_alloc sur gros cas, curie pourquoi ?
  ArrOfDouble residu(size_residu);
  int nbiter = solve(residu);
  if (limpr()>-1)
    {
      double residu_relatif=(residu[0]>0?residu[nbiter]/residu[0]:residu[nbiter]);
      Cout << finl << "Final residue: " << residu[nbiter] << " ( " << residu_relatif << " )"<<finl;
    }
// Recuperation de la solution
  start = Statistiques::get_time_now();
// ToDo un seul VecGetValues comme VecSetValues
  if (different_partition_)
    {
// TRUST and PETSc has different partition, a local vector LocalSolutionPetsc_ is gathered from the global vector SolutionPetsc_ :
      VecScatterBegin(VecScatter_, SolutionPetsc_, LocalSolutionPetsc_, INSERT_VALUES, SCATTER_FORWARD);
      VecScatterEnd  (VecScatter_, SolutionPetsc_, LocalSolutionPetsc_, INSERT_VALUES, SCATTER_FORWARD);
// Use the local vector to get the solution:
      int colonne_locale=0;
      for (int i=0; i<size; i++)
        if (items_to_keep_[i])
          {
            VecGetValues(LocalSolutionPetsc_, 1, &colonne_locale, &solution(i));
            colonne_locale++;
          }
      assert(nb_rows_==colonne_locale);
    }
  else
    {
// TRUST and PETSc has same partition, local solution can be accessed from the global vector:
      VecGetValues(SolutionPetsc_, size, ix.addr(), solution.addr());
    }
  solution.echange_espace_virtuel();
  fixer_nouvelle_matrice(0);
  if (verbose) Cout << finl << "[Petsc] Time to update solution: \t" << Statistiques::get_time_now() - start << finl;
// Calcul du vrai residu sur matrice initiale sur GPU:
  if (amgx_ || gpu_ || controle_residu_)
    {
      DoubleVect test(secmem);
      test*=-1;
      la_matrice.ajouter_multvect(solution,test);
      double vrai_residu = mp_norme_vect(test);
      if (verbose) Cout << "||Ax-b||=" << vrai_residu << finl;
// Verification de la solution sur la matrice initiale
      if (nbiter>0 && Process::je_suis_maitre())
        {
          double precision_machine=1.e-12;
          if (residu[0]>0 && residu[nbiter]/residu[0]>precision_machine && vrai_residu>10*residu[nbiter])
            {
              Cerr << "Error, computed solution x is false !" << finl;
              Cerr << "True residual (" << vrai_residu << ") is much higher than convergence residual (" << residu[nbiter] << ") !" << finl;
              Process::exit();
            }
        }
    }
  return nbiter;
#else
  return -1;
#endif
}
References TRUSTArray< _TYPE_ >::addr(), Matrice_Base::ajouter_multvect(), amgx_, Statistiques::begin_count(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Matrice_Bloc::BlocToMatMorse(), Cerr, Cout, Matrice_Morse::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Statistiques::end_count(), Process::exit(), finl, SolveurSys_base::fixer_nouvelle_matrice(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Statistiques::get_time_now(), gpu_, instance, Process::je_suis_maitre(), SolveurSys_base::limpr(), TRUSTVect< _TYPE_ >::line_size(), MorseSymToMorse(), mp_norme_vect(), Objet_U::nom_du_cas(), SolveurSys_base::nouvelle_matrice(), Process::nproc(), Sortie_Fichier_base::precision(), Objet_U::que_suis_je(), read_matrix_, ref_cast, ref_cast_non_const, Sortie_Fichier_base::setf(), TRUSTArray< _TYPE_ >::size_array(), solv_sys_petsc_counter_, statistiques(), sub_type, test(), Deriv_Matrice_Base::valeur(), and verbose.
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Petsc::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 50 of file Solv_Petsc.h.
  {
    return resoudre_systeme(M,A,B);
  };
References resoudre_systeme().
self_cast() [1/2]
const Solv_Petsc & Solv_Petsc::self_cast (const Objet_U & r) static
Definition at line 43 of file Solv_Petsc.cpp.
self_cast() [2/2]
Solv_Petsc & Solv_Petsc::self_cast (Objet_U & r) static
Definition at line 43 of file Solv_Petsc.cpp.
solveur_direct()
int Solv_Petsc::solveur_direct () const inline override virtual
Implements SolveurSys_base.
Definition at line 45 of file Solv_Petsc.h.
  {
    return (solveur_direct_>0);
  };
taille_memoire()
unsigned Solv_Petsc::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Solv_Petsc_GPU.
Definition at line 43 of file Solv_Petsc.cpp.
Member Data Documentation
allow_realloc_
bool Solv_Petsc::allow_realloc_ protected
Definition at line 169 of file Solv_Petsc.h.
Referenced by create_solver().
amgx_
bool Solv_Petsc::amgx_ protected
Utilisation des solveurs GPU de AMGX.
Definition at line 163 of file Solv_Petsc.h.
Referenced by config(), create_solver(), resoudre_systeme(), and Solv_AMGX::Solv_AMGX().
amgx_initialized_
bool Solv_Petsc::amgx_initialized_ protected
Amgx initialise Options dev:
Definition at line 165 of file Solv_Petsc.h.
chaine_lue_
Nom Solv_Petsc::chaine_lue_ protected
Chaine des mots cles lus.
Definition at line 160 of file Solv_Petsc.h.
Referenced by Solv_AMGX::printOn(), printOn(), and Solv_Petsc_GPU::printOn().
clean_matrix_
bool Solv_Petsc::clean_matrix_ protected
Definition at line 170 of file Solv_Petsc.h.
Referenced by create_solver().
gpu_
bool Solv_Petsc::gpu_ protected
Utilisation des solveurs GPU de PETSc.
Definition at line 162 of file Solv_Petsc.h.
Referenced by create_solver(), resoudre_systeme(), and Solv_Petsc_GPU::Solv_Petsc_GPU().
ignore_new_nonzero_
bool Solv_Petsc::ignore_new_nonzero_ protected
Definition at line 167 of file Solv_Petsc.h.
Referenced by create_solver().
info_obj
const Type_info Solv_Petsc::info_obj static
Definition at line 39 of file Solv_Petsc.h.
instance
int Solv_Petsc::instance =-1 static
Nombre d'instances en cours de la classe.
Definition at line 94 of file Solv_Petsc.h.
Referenced by resoudre_systeme(), Solv_Petsc(), and ~Solv_Petsc().
numero_solveur
int Solv_Petsc::numero_solveur =0 static
Compte les solveurs crees et utilises pour le prefix des options.
Definition at line 95 of file Solv_Petsc.h.
Referenced by create_solver().
read_matrix_
int Solv_Petsc::read_matrix_ protected
Read constant matrix in a file.
Definition at line 161 of file Solv_Petsc.h.
Referenced by create_solver(), read_matrix(), resoudre_systeme(), and Solv_Petsc().
rebuild_matrix_
bool Solv_Petsc::rebuild_matrix_ protected
Definition at line 168 of file Solv_Petsc.h.
Referenced by create_solver().
solveur_direct_
int Solv_Petsc::solveur_direct_ protected
Pour savoir si l'on manipule un solveur direct et non iteratif.
Definition at line 159 of file Solv_Petsc.h.
verbose
bool Solv_Petsc::verbose = false protected
Timing.
Definition at line 171 of file Solv_Petsc.h.
Referenced by create_solver(), and resoudre_systeme().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_Petsc.h
src/Kernel/Math/SolvSys/Solv_Petsc.cpp