TRUST: Champ_front_contact_fictif_VEF Class Reference
Champ_front_contact_fictif_VEF Class Reference
classe Champ_front_contact_fictif_VEF
Classe derivee de Champ_front_contact_VEF elle-meme derivant de
Champ_front_var qui represente les
champs a la frontiere obtenus en prenant la trace
d'un objet de type Champ_Inc (champ inconnue d'une equation)
#include <Champ_front_contact_fictif_VEF.h>
Public Member Functions
Champ_front_contact_fictif_VEF ()
~Champ_front_contact_fictif_VEF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Champ_front_contact_fictif_VEF & self_cast (Objet_U &)
static const
Champ_front_contact_fictif_VEF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
double conduct_fictif
conductivite du solide fictif
double ep_fictif
epaisseur du solide fictif
Detailed Description
classe Champ_front_contact_fictif_VEF
Classe derivee de Champ_front_contact_VEF elle-meme derivant de
Champ_front_var qui represente les
champs a la frontiere obtenus en prenant la trace
d'un objet de type Champ_Inc (champ inconnue d'une equation)
Definition at line 46 of file Champ_front_contact_fictif_VEF.h.
Constructor & Destructor Documentation
Champ_front_contact_fictif_VEF::Champ_front_contact_fictif_VEF ()
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
Champ_front_contact_fictif_VEF::~Champ_front_contact_fictif_VEF ()
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
Member Function Documentation
Objet_U * Champ_front_contact_fictif_VEF::cree_instance () [static]
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
int Champ_front_contact_fictif_VEF::duplique () const [virtual]
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
const Type_info * Champ_front_contact_fictif_VEF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
const Type_info * Champ_front_contact_fictif_VEF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
void Champ_front_contact_fictif_VEF::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
< coefficient d'echange du solide fictif
< temperature du fluide 1
< coefficient d'echange du fluide 1
< temperature du fluide 2
< coefficient d'echange du fluide 2
Reimplemented from Champ_front_contact_VEF.
Definition at line 50 of file Champ_front_contact_fictif_VEF.cpp.
References Cerr, Champ_front_contact_VEF::ch_fr_autre_pb, conduct_fictif, DoubleVect::echange_espace_virtuel(), ep_fictif, Process::exit(), finl, Champ_front_contact_VEF::fr_vf_autre_pb, Champ_front_contact_VEF::gradient_fro_local, Champ_front_contact_VEF::gradient_num_local, Champ_front_base::la_frontiere_dis, Frontiere::nb_faces(), Champ_front_contact_VEF::nom_bord1, Champ_front_contact_VEF::nom_bord2, Champ_front_contact_VEF::nom_pb1, Champ_front_contact_VEF::nom_pb2, O_U_Ptr::non_nul(), Champ_front_contact_VEF::trace_face_raccord(), Ref_Front_VF::valeur(), and Champ_front_base::valeurs().
{
  const Frontiere& la_front=la_frontiere_dis->frontiere();
  int nb_faces=la_front.nb_faces();
  DoubleTab& tab=valeurs();
// On recupere les coefficients gradient_num_transf et gradient_fro_transf de l'autre probleme
  DoubleVect gradient_num_transf_autre_pb(nb_faces);
  DoubleVect gradient_fro_transf_autre_pb(nb_faces);
  if (!ch_fr_autre_pb.non_nul())
    {
      Cerr << "Attention: Vous utilisez une condition de contact Champ_front_contact_fictif_VEF sur le bord " << nom_bord1 << " sur le probleme "<< nom_pb1 <<" " << finl;
      Cerr << "Vous devez avoir un Champ_front_contact_fictif_VEF equivalent sur le bord " << nom_bord2 << " du probleme "<<nom_pb2<<" " << finl;
      Process::exit();
    }
  trace_face_raccord(fr_vf_autre_pb.valeur(),ch_fr_autre_pb->get_gradient_num_transf(),gradient_num_transf_autre_pb);
  trace_face_raccord(fr_vf_autre_pb.valeur(),ch_fr_autre_pb->get_gradient_fro_transf(),gradient_fro_transf_autre_pb);
// PQ : 10/09/07 : pour plus de lisibilite, on renomme les tableaux servant
// au calcul de la temperature parietale, de sorte d'avoir :
//
// h1.Tf1 + (h2.hs/(h2+hs)). Tf2
// Tw_1 = ------------------------------
// (h1+hs) - (hs*hs/(h2+hs))
//
// avec :
  double hs = conduct_fictif / ep_fictif;         //!< coefficient d'echange du solide fictif
  DoubleVect& h1Tf1=(gradient_num_local);                   //!< temperature du fluide 1
  DoubleVect& h1=(gradient_fro_local);                   //!< coefficient d'echange du fluide 1
  DoubleVect& h2Tf2=(gradient_num_transf_autre_pb);  //!< temperature du fluide 2
  DoubleVect& h2=(gradient_fro_transf_autre_pb);   //!< coefficient d'echange du fluide 2
// Calcul de la temperature imposee
  int fac_front;
  for (fac_front=0; fac_front<nb_faces; fac_front++)
    {
      tab(fac_front,0)= -( h1Tf1(fac_front) + (hs*h2Tf2(fac_front)/(hs+h2(fac_front))) )
                        / ( hs+h1(fac_front) - (hs*hs/(hs+h2(fac_front))) );
// Cerr << " H1 " << h1(fac_front) << finl;
// Cerr << " T1 " << Tf1(fac_front) << finl;
// Cerr << " H2 " << h2(fac_front) << finl;
// Cerr << " T2 " << Tf2(fac_front) << finl;
// Cerr << " Hs " << hs << finl;
// Cerr << " TW " << tab(fac_front,0) << finl;
// Cerr << " " << finl;
    }
  tab.echange_espace_virtuel();
// Verification de la coherence des temperatures de bord calculees
// verifier_temperature_bord();
}
Sortie & Champ_front_contact_fictif_VEF::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_contact_VEF.
Definition at line 34 of file Champ_front_contact_fictif_VEF.cpp.
{
  return os;
}
Entree & Champ_front_contact_fictif_VEF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_contact_VEF.
Definition at line 40 of file Champ_front_contact_fictif_VEF.cpp.
References Cerr, conduct_fictif, ep_fictif, finl, Champ_front_contact_VEF::nom_bord1, Champ_front_contact_VEF::nom_bord2, Champ_front_contact_VEF::nom_pb1, and Champ_front_contact_VEF::nom_pb2.
{
  Champ_front_contact_VEF::readOn(is);
  is >>  conduct_fictif >> ep_fictif ;
  Cerr << "Champ_front_contact_fictif_VEF::readOn : " << nom_pb1 << nom_bord1 << finl;
  Cerr << "      connecte a                : " << nom_pb2 << nom_bord2 << finl;
// connect_est_remplit=0;
  return is;
}
Champ_front_contact_fictif_VEF & Champ_front_contact_fictif_VEF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
const Champ_front_contact_fictif_VEF & Champ_front_contact_fictif_VEF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
unsigned Champ_front_contact_fictif_VEF::taille_memoire () const [virtual]
Reimplemented from Champ_front_contact_VEF.
Definition at line 31 of file Champ_front_contact_fictif_VEF.cpp.
Member Data Documentation
double Champ_front_contact_fictif_VEF::conduct_fictif [protected]
conductivite du solide fictif
Definition at line 58 of file Champ_front_contact_fictif_VEF.h.
Referenced by mettre_a_jour(), and readOn().
double Champ_front_contact_fictif_VEF::ep_fictif [protected]
epaisseur du solide fictif
Definition at line 59 of file Champ_front_contact_fictif_VEF.h.
Referenced by mettre_a_jour(), and readOn().
const Type_info Champ_front_contact_fictif_VEF::info_obj [static]
Reimplemented from Champ_front_contact_VEF.
Definition at line 49 of file Champ_front_contact_fictif_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_front_contact_fictif_VEF.h
src/VEF/Champs/Champ_front_contact_fictif_VEF.cpp