TRUST: Champ_front_Tabule Class Reference
Champ_front_Tabule Class Reference
classe Champ_front_Tabule
Classe derivee de Champ_front_instationnaire_base qui
represente les champs aux frontieres uniformes en espace,
calcules par tabulation en fonction du temps.
#include <Champ_front_Tabule.h>
Public Member Functions
Champ_front_Tabule ()
~Champ_front_Tabule ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Champ_front_base & affecter_ (const Champ_front_base &ch)
Renvoie l'objet Champ_front_Tabule upcaste en Champ_front_base.
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
void mettre_a_jour (double temps)
Mise a jour en temps du champ.
Calcul du gradient Gpoint.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_Tabule & self_cast (Objet_U &)
static const Champ_front_Tabule & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime les valeurs du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les valeurs du champ tabule a partir d'un flot d'entree.
Format:
Champ_front_Tabule nb_comp { nval tps_1...tps_nval vrel_1...vrel_nval }.
Protected Attributes
Table la_table
Detailed Description
classe Champ_front_Tabule
Classe derivee de Champ_front_instationnaire_base qui
represente les champs aux frontieres uniformes en espace,
calcules par tabulation en fonction du temps.
Definition at line 42 of file Champ_front_Tabule.h.
Constructor & Destructor Documentation
Champ_front_Tabule::Champ_front_Tabule ()
Definition at line 26 of file Champ_front_Tabule.cpp.
Champ_front_Tabule::~Champ_front_Tabule ()
Definition at line 26 of file Champ_front_Tabule.cpp.
Member Function Documentation
Champ_front_base & Champ_front_Tabule::affecter_ (const Champ_front_base & ch) [virtual]
Renvoie l'objet Champ_front_Tabule upcaste en Champ_front_base.
Returns:
Champ_front_base&
Signification: (*this) upcaste en Champ_front_base
Contraintes:
Implements Champ_front_base.
Definition at line 123 of file Champ_front_Tabule.cpp.
{
  return *this;
}
Objet_U * Champ_front_Tabule::cree_instance () [static]
Definition at line 26 of file Champ_front_Tabule.cpp.
int Champ_front_Tabule::duplique () const [virtual]
Implements Champ_front_instationnaire_base.
Definition at line 26 of file Champ_front_Tabule.cpp.
const Type_info * Champ_front_Tabule::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 26 of file Champ_front_Tabule.cpp.
const Type_info * Champ_front_Tabule::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 26 of file Champ_front_Tabule.cpp.
int Champ_front_Tabule::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 129 of file Champ_front_Tabule.cpp.
References Champ_front_instationnaire_base::initialiser(), and mettre_a_jour().
{
  if (!Champ_front_instationnaire_base::initialiser(temps,inco))
    return 0;
  mettre_a_jour(temps);
  return 1;
}
void Champ_front_Tabule::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Calcul du gradient Gpoint.
Reimplemented from Champ_front_base.
Definition at line 152 of file Champ_front_Tabule.cpp.
References la_table, Table::valeurs(), and Champ_front_instationnaire_base::valeurs_au_temps().
Referenced by initialiser().
{
  la_table.valeurs(valeurs_au_temps(temps), temps);
}
Sortie & Champ_front_Tabule::printOn (Sortie & os) const [protected, virtual]
Imprime les valeurs du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 44 of file Champ_front_Tabule.cpp.
References Champ_front_base::valeurs().
{
  return os << valeurs();
}
Entree & Champ_front_Tabule::readOn (Entree & is) [protected, virtual]
Lit les valeurs du champ tabule a partir d'un flot d'entree.
Format:
Champ_front_Tabule nb_comp { nval tps_1...tps_nval vrel_1...vrel_nval }.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_instationnaire_base.
Definition at line 67 of file Champ_front_Tabule.cpp.
References Cerr, Process::exit(), finl, Field_base::fixer_nb_comp(), la_table, Champ_Proto::lire_dimension(), Objet_U::que_suis_je(), and Table::remplir().
{
  Motcle motlu;
  int nb_val;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  int dim,i,j;
  dim=lire_dimension(is,que_suis_je());
  fixer_nb_comp(dim);
  is >> motlu;
  if (motlu == accolade_ouverte)
    {
      nb_val=lire_dimension(is,que_suis_je());
      DoubleVect param(nb_val);
      DoubleTab tab_valeurs(nb_val, dim);
      for (i=0; i<nb_val; i++)
        is >> param[i];
      for (i=0; i<nb_val; i++)
        for (j=0; j<dim; j++)
          is >> tab_valeurs(i,j);
      la_table.remplir(param,tab_valeurs);
      is >> motlu;
      if (motlu != accolade_fermee)
        {
          Cerr << "Error reading from an object of type Champ_front_Tabule" << finl;
          Cerr << "We expected keyword } instead of " << motlu << finl;
          exit();
        }
    }
  else
    {
      Cerr << "Error reading from an object of type Champ_front_Tabule" << finl;
      Cerr << "We expected keyword { instead of " << motlu << finl;
      exit();
    }
  return is;
}
Champ_front_Tabule & Champ_front_Tabule::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_instationnaire_base.
Definition at line 26 of file Champ_front_Tabule.cpp.
const Champ_front_Tabule & Champ_front_Tabule::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_instationnaire_base.
Definition at line 26 of file Champ_front_Tabule.cpp.
unsigned Champ_front_Tabule::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Champ_front_Tabule.cpp.
Member Data Documentation
const Type_info Champ_front_Tabule::info_obj [static]
Reimplemented from Champ_front_instationnaire_base.
Definition at line 44 of file Champ_front_Tabule.h.
Table Champ_front_Tabule::la_table [protected]
Definition at line 54 of file Champ_front_Tabule.h.
Referenced by mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_Tabule.h
src/Kernel/Champs/Champ_front_Tabule.cpp