TRUST: Interprete Class Reference
Interprete Class Reference
Classe de base des objets "interprete".
Ces objets definissent des actions a realiser lorsqu'on les
rencontre dans le jeu de donnees. L'action est declanchee par
un appel a la methode interpreter().
L'interprete peut ensuite lire des parametres supplementaires
dans l'entree pour realiser sa tache. En general, l'interprete
agit sur d'autres objets declares dans le jeu de donnees. Il peut
y acceder par les methodes objet() et est_un_objet_existant().
Voir par exemple la classe Lire ou la classe Associer
Voir aussi la classe Interprete_bloc qui lit une serie d'instructions
a executer dans le jeu de donnees.
#include <Interprete.h>
Public Member Functions
Interprete ()
~Interprete ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Classe de base des objets "interprete".
Ces objets definissent des actions a realiser lorsqu'on les
rencontre dans le jeu de donnees. L'action est declanchee par
un appel a la methode interpreter().
L'interprete peut ensuite lire des parametres supplementaires
dans l'entree pour realiser sa tache. En general, l'interprete
agit sur d'autres objets declares dans le jeu de donnees. Il peut
y acceder par les methodes objet() et est_un_objet_existant().
Voir par exemple la classe Lire ou la classe Associer
Voir aussi la classe Interprete_bloc qui lit une serie d'instructions
a executer dans le jeu de donnees.
See also:
Interprete_bloc
Definition at line 46 of file Interprete.h.
Constructor & Destructor Documentation
Interprete::Interprete ()
Definition at line 27 of file Interprete.cpp.
Interprete::~Interprete ()
Definition at line 27 of file Interprete.cpp.
Member Function Documentation
Objet_U * Interprete::cree_instance () [static]
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
int Interprete::duplique () const [virtual]
Implements Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
const Type_info * Interprete::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
const Type_info * Interprete::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
virtual Entree& Interprete::interpreter (Entree & is) [inline, virtual]
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Decouper, Decouper_multi, Dimension, Interprete_geometrique_base, MaillerParallel, PrecisionGeom, Raffiner_isotrope_parallele, Scatter, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, Integrer_champ_med, LataToMED, latatoother, MergeMEDfiles, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, System, Typer_Lire, EcritureLectureSpecial, Phases, and Option_VDF.
Definition at line 50 of file Interprete.h.
References Process::exit().
Referenced by Interprete_bloc::interpreter_bloc().
  {
    exit();
    return is;
  }
Objet_U & Interprete::objet (const Nom & nom) [static]
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
Definition at line 48 of file Interprete.cpp.
References Interprete_bloc::objet_global().
Referenced by Champ_front_recyclage::associer_champ_evaluateur(), Interprete_geometrique_base::associer_domaine(), check_ICEM_binary_file(), paroi_contact::complement(), Terme_Source_Rappel_T_VEF_Face::completer(), Champ_Generique_Transformation::completer(), Champ_Generique_Extraction::completer(), Partitionneur_Union::construire_partition(), Champ_front_contact_VEF::creer(), Champ_front_calc::creer(), ExtrudeBord::extruder_bord(), ExtrudeBord::extruder_hexa_old(), Decouper::find_domain(), Moyenne_volumique::get_champ(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_base::get_discretisation(), get_obj(), Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_zone_dis_base(), Phases::interpreter(), Typer_Lire::interpreter(), Lire_Fichier::interpreter(), Lire::interpreter(), Ecrire::interpreter(), Moyenne_volumique::interpreter(), Integrer_champ_med::interpreter(), EcrMED::interpreter(), Ecrire_Champ_MED::interpreter(), Testeur_MEDCoupling::interpreter(), Pilote_ICoCo::interpreter(), Scatter::interpreter(), MaillerParallel::interpreter(), Analyse_Angle::interpreter(), Resoudre::interpreter(), Porosites_champ::interpreter(), Porosites::interpreter(), Discretiser::interpreter(), Diametre_hyd_champ::interpreter(), Associer::interpreter(), Ecrire_Fichier::interpreter_(), TroisDto2D::interpreter_(), Mailler::interpreter_(), ExtrudeBord::interpreter_(), Extraire_surface::interpreter_(), Extraire_plan::interpreter_(), Extraire_domaine::interpreter_(), DecoupeBord::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Postraitement::lire_motcle_non_standard(), Champ_Generique_refChamp::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Discretisation_base::nommer_completer_champ_physique(), OrienteFacesBord::oriente_faces_bord(), Champ_Input_Proto::read(), Terme_Source_Solide_SWIFT_VDF::readOn(), Source_Echange_Th_VDF::readOn(), Champ_Don_Face_lu::readOn(), Milieu_composite::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Champ_front_debit_QC::readOn(), Champ_Fonc_reprise::readOn(), Pb_MED::readOn(), Partitionneur_Partition::readOn(), Probleme_Couple::readOn(), Debog_Pb::readOn(), Champ_som_lu::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Tabule_Morceaux::readOn(), Champ_front_lu::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Champ_Don_lu::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_Fonc_txyz::readOn(), Ch_front_Vortex::readOn(), Champ_Generique_Interpolation::set_domaine(), and Moyenne_volumique::traiter_champs().
{
  return Interprete_bloc::objet_global(nom);
}
int Interprete::objet_existant (const Nom & nom) [static]
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Definition at line 55 of file Interprete.cpp.
References Interprete_bloc::objet_global_existant().
Referenced by Partitionneur_Sous_Zones::construire_partition(), Decouper::find_domain(), Typer_Lire::interpreter(), Lire::interpreter(), Milieu_composite::readOn(), and Champ_Fonc_MED::readOn().
{
  return Interprete_bloc::objet_global_existant(nom);
}
Sortie & Interprete::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 38 of file Interprete.cpp.
References Cerr, Process::exit(), and finl.
Referenced by MergeMEDfiles::printOn().
{
  Cerr << "Error in Interprete::printOn" << finl;
  exit();
  return os;
}
Entree & Interprete::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 31 of file Interprete.cpp.
References Cerr, Process::exit(), and finl.
Referenced by MergeMEDfiles::readOn().
{
  Cerr << "Error in Interprete::readOn" << finl;
  exit();
  return is;
}
Interprete & Interprete::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
const Interprete & Interprete::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
unsigned Interprete::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 27 of file Interprete.cpp.
Member Data Documentation
const Type_info Interprete::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Option_CoviMAC, Associer, Diametre_hyd_champ, Discretiser, Old_Debog, Porosites, Porosites_champ, Resoudre, Testeur, Analyse_Angle, Axi, Bidim_Axi, Calculer_Moments, Corriger_frontiere_periodique, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Decouper, Decouper_multi, Dilate, Dimension, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Interprete_geometrique_base, Lire_Ideas, Lire_Tgrid, Mailler, MaillerParallel, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, PrecisionGeom, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, Scatter, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, Pilote_ICoCo, Testeur_MEDCoupling, Test_solveur, Ecrire_Champ_MED, EcrMED, EcrMEDfile, Integrer_champ_med, LataToMED, latatoother, LireMED, LireMEDfile, MergeMEDfiles, Read_MED_For_Testing_No_Verify_Option, ScatterMED, Moyenne_volumique, Deactivate_SIGINT_Catch, Disable_TU, Ecrire, Ecrire_Fichier, Ecrire_Fichier_Formatte, Execute_parallel, Lire, Lire_Fichier, Lire_Fichier_Bin, MultipleFiles, Read_unsupported_ASCII_file_from_ICEM, System, Typer_Lire, EcritureLectureSpecial, Phases, Option_VDF, and VerifierCoin.
Definition at line 48 of file Interprete.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Interprete.h
src/Kernel/Utilitaires/Interprete.cpp