TRUST: Champ_Generique_refChamp Class Reference
Champ_Generique_refChamp Class Reference
Classe de champ particuliere qui encapsule une reference
a un champ volumique de TRUST de type Champ_base.
La classe ne gere pas la memoire de Champ_base.
#include <Champ_Generique_refChamp.h>
Public Member Functions
Champ_Generique_refChamp ()
~Champ_Generique_refChamp ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize (const Champ_base &champ)
On initialise la classe avec le champ en parametre.
On prend une ref a ce champ (il doit rester valable ensuite).
void set_param (Param &param) override
pb_champ : declenche la lecture du nom du probleme (nom_pb_) auquel appartient
le champ discret et le nom de ce champ discret (nom_champ_)
nom_source : option pour nommer le champ en tant que source (sinon nommer par defaut)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
int get_dimension () const override
Renvoie le nombre de coordonnees de chaque sommet du domaine.
Voir GenericField_base::get_dimension()
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Si le champ n'est pas un champ discret : exception Champ_Generique_erreur("INVALID")
Sinon, renvoie la localisation du champ pour le support "index".
Si index == -1 (valeur par defaut), leve une exception si le champ est multisupport.
Sinon, leve une exception si l'index est superieur au nombre de localisations du champ.
const DoubleTab & get_ref_values () const override
Verifie que le champ est bien un champ discret et
renvoie le tableau de valeurs. Sinon, leve l'exception Champ_Generique_erreur("NO_REF")
void get_copy_values (DoubleTab &) const override
Cree une copie du tableau de valeurs
Voir GenericField_base::get_copy_values()
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
appel a Champ_base::valeur_aux()
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
const Probleme_base & get_ref_pb_base () const override
virtual const Champ_base & get_ref_champ_base () const
Renvoie le champ_base sous-jacent. Teste si le champ a bien ete associe.
A terme, cette methode disparaitra de la classe GenericField_base mais reste
dans celle-ci (on y teste si le champ a ete associe).
Exceptions:
Champ_Generique_erreur("NOT_INITIALIZED")
void reset () override
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
Voir Champ_Generique_base::mettre_a_jour
Si le champ est champ_inc dans l'equation, il doit deja avoir
ete mis a jour par l'equation.
Si c est un clacule, l actualisation est faite dans get_champ.
const Champ_base & get_champ (Champ &espace_stockage) const override
Voir Champ_Generique_base::get_champ.
Ici, l'espace_stockage n'est pas utilise, le champ existe deja.
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
virtual void set_ref_champ (const Champ_base &)
Associe le champ et determine sa localisation.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Motcle get_directive_pour_discr () const override
void set_nom_champ (const Motcle &)
void nommer_source ()
int get_info_type_post () const override
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_refChamp & self_cast (Objet_U &)
static const Champ_Generique_refChamp & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Champ_base ref_champ_
Motcle localisation_
Nom nom_champ_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
Classe de champ particuliere qui encapsule une reference
a un champ volumique de TRUST de type Champ_base.
La classe ne gere pas la memoire de Champ_base.
Definition at line 33 of file Champ_Generique_refChamp.h.
Constructor & Destructor Documentation
Champ_Generique_refChamp()
Champ_Generique_refChamp::Champ_Generique_refChamp ()
Definition at line 29 of file Champ_Generique_refChamp.cpp.
~Champ_Generique_refChamp()
Champ_Generique_refChamp::~Champ_Generique_refChamp ()
Definition at line 29 of file Champ_Generique_refChamp.cpp.
Member Function Documentation
completer()
void Champ_Generique_refChamp::completer (const Postraitement_base & post) override virtual
Implements Champ_Generique_base.
Definition at line 385 of file Champ_Generique_refChamp.cpp.
{
  nommer_source();
}
References nommer_source().
cree_instance()
Objet_U * Champ_Generique_refChamp::cree_instance () static
Definition at line 29 of file Champ_Generique_refChamp.cpp.
duplique()
int Champ_Generique_refChamp::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 29 of file Champ_Generique_refChamp.cpp.
get_champ()
const Champ_base & Champ_Generique_refChamp::get_champ (Champ & espace_stockage) const override virtual
Voir Champ_Generique_base::get_champ.
Ici, l'espace_stockage n'est pas utilise, le champ existe deja.
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 403 of file Champ_Generique_refChamp.cpp.
{
  {
    const Nom& nom_cible = get_ref_champ_base().le_nom();
    ref_pb_->get_champ(nom_cible);
    return get_ref_champ_base();
  }
}
References Probleme_base::get_champ(), get_ref_champ_base(), Field_base::le_nom(), and Champ_Generique_base::ref_pb_.
Referenced by Postraitement::creer_champ_post_stat(), and get_champ_without_evaluation().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_refChamp::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 412 of file Champ_Generique_refChamp.cpp.
{
  return get_champ(espace_stockage);
}
References get_champ().
get_copy_connectivity()
void Champ_Generique_refChamp::get_copy_connectivity (Entity index1, Entity index2, IntTab & tab) const override virtual
Reimplemented from Champ_Generique_base.
Definition at line 354 of file Champ_Generique_refChamp.cpp.
{
  const IntTab& connectivity = get_ref_connectivity(index1, index2);
  tab = connectivity;
}
References get_ref_connectivity().
get_copy_coordinates()
void Champ_Generique_refChamp::get_copy_coordinates (DoubleTab & coordinates) const override virtual
Reimplemented from Champ_Generique_base.
Definition at line 297 of file Champ_Generique_refChamp.cpp.
{
  const DoubleTab& coord = get_ref_coordinates();
  coordinates = coord;
}
References get_ref_coordinates().
get_copy_values()
void Champ_Generique_refChamp::get_copy_values (DoubleTab & values) const override virtual
Cree une copie du tableau de valeurs
Voir GenericField_base::get_copy_values()
Reimplemented from Champ_Generique_base.
Definition at line 263 of file Champ_Generique_refChamp.cpp.
{
  const DoubleTab& val = get_ref_values();
// Cree une copie du tableau
  values = val;
}
References get_ref_values().
get_dimension()
int Champ_Generique_refChamp::get_dimension () const override virtual
Renvoie le nombre de coordonnees de chaque sommet du domaine.
Voir GenericField_base::get_dimension()
Reimplemented from Champ_Generique_base.
Definition at line 108 of file Champ_Generique_refChamp.cpp.
{
// Je n'utilise pas Objet_U::dimension expres car j'espere supprimer
// cette variable statique bientot.
  const DoubleTab coords = get_ref_coordinates();
  const int dim = coords.dimension(1);
  return dim;
}
References TRUSTTab< _TYPE_ >::dimension(), and get_ref_coordinates().
get_directive_pour_discr()
const Motcle Champ_Generique_refChamp::get_directive_pour_discr () const override virtual
Reimplemented from Champ_Generique_base.
Definition at line 465 of file Champ_Generique_refChamp.cpp.
{
  Motcle directive;
  const Champ_base& ch = get_ref_champ_base();
// Champs discrets a une seule localisation :
  if (sub_type(Champ_Inc_P0_base,ch) || sub_type(Champ_Fonc_P0_base,ch))
    {
      directive = "champ_elem";
// assert(localisation_=="ELEMENTS");
    }
  else if (sub_type(Champ_Inc_P1_base,ch) || sub_type(Champ_Fonc_P1_base,ch)
           || sub_type(Champ_Inc_P1_base,ch) || sub_type(Champ_Inc_Q1_base,ch)
           || sub_type(Champ_Fonc_Q1_base,ch))
    {
      directive = "champ_sommets";
// assert(localisation_=="SOMMETS");
    }
  else
    {
      const Nom& type = ch.que_suis_je();
      if ((type.debute_par("Champ_Face")) || (type=="Champ_P1NC") || (type=="Champ_Q1NC") ||
          (type=="Champ_Fonc_Face") || (type=="Champ_Fonc_P1NC") || (type=="Champ_Fonc_Q1NC"))
        {
          directive = "champ_face";
// assert(localisation_=="FACES");
        }
      else if ((type=="Champ_P1_isoP1Bulle") || (type=="Champ_Fonc_P1_isoP1Bulle"))
        {
          directive = "pression";
        }
      else if (sub_type(Champ_Uniforme,ch))
        {
          directive = "champ_uniforme";
        }
      else if (sub_type(Champ_Don_base,ch))
        {
          directive = "champ_don";
        }
      else
        {
          Cerr<<"No directive is available to create a storing field for the source field of type "<<ch.que_suis_je()<<finl;
          exit();
        }
    }
  return directive;
}
References Cerr, Nom::debute_par(), Process::exit(), finl, get_ref_champ_base(), Objet_U::que_suis_je(), and sub_type.
get_info()
const Type_info * Champ_Generique_refChamp::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 29 of file Champ_Generique_refChamp.cpp.
get_info_type_post()
int Champ_Generique_refChamp::get_info_type_post () const override virtual
Implements Champ_Generique_base.
Definition at line 536 of file Champ_Generique_refChamp.cpp.
{
  return 0;
}
get_localisation()
Entity Champ_Generique_refChamp::get_localisation (const int index = -1) const override virtual
Si le champ n'est pas un champ discret : exception Champ_Generique_erreur("INVALID")
Sinon, renvoie la localisation du champ pour le support "index".
Si index == -1 (valeur par defaut), leve une exception si le champ est multisupport.
Sinon, leve une exception si l'index est superieur au nombre de localisations du champ.
Reimplemented from Champ_Generique_base.
Definition at line 216 of file Champ_Generique_refChamp.cpp.
{
  Entity loc;
// Pour initialisation
  loc = NODE;
  const Champ_base& ch = get_ref_champ_base();
  const Zone_dis_base& z_dis_base = get_ref_zone_dis_base();
// Champs discrets a une seule localisation :
  if ((sub_type(Champ_Inc_P0_base, ch) || sub_type(Champ_Fonc_P0_base, ch)) && index <= 0)
    {
      loc = ELEMENT;
    }
  else if ((sub_type(Champ_Inc_P1_base, ch)|| sub_type(Champ_Fonc_P1_base, ch)) && index <= 0)
    {
      loc = NODE;
    }
  else if ((ch.que_suis_je().debute_par("Champ_Face_PolyMAC")
            || ch.valeurs().dimension(0) == ref_cast(Zone_VF,z_dis_base).nb_faces()) && index <= 0)
    {
      loc = FACE;
    }
  else
    {
// Champs discrets a plusieurs localisations
      Nom message="Invalid localization used for postprocessing the field ";
      message+=ch.le_nom()+". Change your data file.";
      throw Champ_Generique_erreur(message);
    }
  return loc;
}
References Nom::debute_par(), TRUSTTab< _TYPE_ >::dimension(), ELEMENT, FACE, get_ref_champ_base(), Champ_Generique_base::get_ref_zone_dis_base(), Field_base::le_nom(), message(), NODE, Objet_U::que_suis_je(), ref_cast, sub_type, and Champ_Proto::valeurs().
Referenced by get_ref_values(), and Champ_Generique_refChamp_special::get_ref_values().
get_property()
const Noms Champ_Generique_refChamp::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Generique_base.
Definition at line 126 of file Champ_Generique_refChamp.cpp.
{
  Motcles motcles(5);
  motcles[0] = "nom";
  motcles[1] = "nom_cible";
  motcles[2] = "unites";
  motcles[3] = "composantes";
  motcles[4] = "synonyms";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms mots(1);
        mots[0] = nom_post_;
        return mots;
        break;
      }
    case 1:
      {
        Noms mots(1);
        mots[0] = nom_champ_;
        return mots;
        break;
      }
    case 2 :
      {
        const Noms mots0= get_ref_champ_base().unites();
        ref_cast_non_const(Champ_base,get_ref_champ_base()).corriger_unite_nom_compo();
        const Noms mots = get_ref_champ_base().unites();
        if (mots.size()!=mots0.size())
          {
            Cerr<<"iuuuuuu"<<mots<<" "<<mots0<<finl;
            exit();
          }
        for (int i=0; i<mots.size(); i++)
          {
            if (mots0[i]!=mots[i])
              {
                Cerr <<" iiiiiiiiii"<<mots0[i]<< " "<<mots[i]<<finl;
                exit();
              }
          }
        return mots;
        break;
      }
    case 4 :
      {
        const Noms mots = get_ref_champ_base().get_synonyms();
        return mots;
        break;
      }
    case 3 :
      {
        {
          const Noms mots = get_ref_champ_base().noms_compo();
          int nb_comp = mots.size();
          Noms compo(nb_comp);
          for (int i=0; i<nb_comp; i++)
            {
              Nom nume(i);
              compo[i] = nom_post_+nume;
            }
          return compo;
          break;
        }
      }
    default :
      {
        Cerr<<"The identifiable properties are : "<<motcles<<finl;
        exit();
      }
    }
// Pour compilation
// On n'arrive jamais ici
  return get_property(query);
}
References Cerr, Process::exit(), finl, get_property(), get_ref_champ_base(), Field_base::get_synonyms(), nom_champ_, Champ_Generique_base::nom_post_, Field_base::noms_compo(), ref_cast_non_const, Motcles::search(), vect_impl::size(), and Field_base::unites().
Referenced by get_property().
get_property_names()
void Champ_Generique_refChamp::get_property_names (Motcles & list) const override virtual
Renvoie la liste des "query" possibles pour le champ.
Reimplemented from Champ_Generique_base.
Definition at line 117 of file Champ_Generique_refChamp.cpp.
{
  list.add("nom");
  list.add("nom_cible");
  list.add("unites");
  list.add("composantes");
  list.add("synonyms");
}
References Vect_Motcle::add().
get_ref_champ_base()
const Champ_base & Champ_Generique_refChamp::get_ref_champ_base () const virtual
Renvoie le champ_base sous-jacent. Teste si le champ a bien ete associe.
A terme, cette methode disparaitra de la classe GenericField_base mais reste
dans celle-ci (on y teste si le champ a ete associe).
Exceptions:
Champ_Generique_erreur("NOT_INITIALIZED")
Reimplemented in Champ_Generique_Champ.
Definition at line 372 of file Champ_Generique_refChamp.cpp.
{
  if (!ref_champ_.non_nul())
    throw Champ_Generique_erreur("NOT_INITIALIZED");
  return ref_champ_.valeur();
}
References O_U_Ptr::non_nul(), ref_champ_, and Ref_Champ_base::valeur().
Referenced by get_champ(), Champ_Generique_refChamp_special::get_champ(), get_directive_pour_discr(), get_localisation(), get_property(), get_ref_connectivity(), get_ref_values(), get_ref_zcl_dis_base(), get_time(), and nommer_source().
get_ref_connectivity()
const IntTab & Champ_Generique_refChamp::get_ref_connectivity (Entity index1, Entity index2) const override virtual
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
Reimplemented from Champ_Generique_base.
Definition at line 303 of file Champ_Generique_refChamp.cpp.
{
  const Champ_base& ch = get_ref_champ_base();
  const Zone_dis_base& zone_dis_base = ch.zone_dis_base();
  const Zone& zone = zone_dis_base.zone();
  const Zone_VF& zone_vf = ref_cast(Zone_VF, zone_dis_base);
  switch(index1)
    {
    case ELEMENT:
      {
        switch(index2)
          {
          case NODE:
            return zone.les_elems();
          case FACE:
            return zone_vf.elem_faces();
          default :
            {
              exit();
            }
          }
        break;
      }
    case FACE:
      {
        switch(index2)
          {
          case NODE:
            return zone_vf.face_sommets();
          case ELEMENT:
            return zone_vf.face_voisins();
          default :
            {
              exit();
            }
          }
        break;
      }
    default :
      {
        exit();
      }
    }
  Nom message="Invalid localization used for postprocessing the field ";
  message+=ch.le_nom()+". Change your data file.";
  throw Champ_Generique_erreur(message);
// On n'arrive jamais ici
  return get_ref_connectivity(index1,index2);
}
References Zone_VF::elem_faces(), ELEMENT, Process::exit(), FACE, Zone_VF::face_sommets(), Zone_VF::face_voisins(), get_ref_champ_base(), get_ref_connectivity(), Field_base::le_nom(), Zone::les_elems(), message(), NODE, ref_cast, Zone_dis_base::zone(), and Champ_base::zone_dis_base().
Referenced by get_copy_connectivity(), and get_ref_connectivity().
get_ref_coordinates()
const DoubleTab & Champ_Generique_refChamp::get_ref_coordinates () const override virtual
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
Reimplemented from Champ_Generique_base.
Definition at line 291 of file Champ_Generique_refChamp.cpp.
{
  const DoubleTab& coord = get_ref_domain().coord_sommets();
  return coord;
}
References Domaine::coord_sommets(), and Champ_Generique_base::get_ref_domain().
Referenced by get_copy_coordinates(), and get_dimension().
get_ref_pb_base()
const Probleme_base & Champ_Generique_refChamp::get_ref_pb_base () const override virtual
Reimplemented from Champ_Generique_base.
Definition at line 361 of file Champ_Generique_refChamp.cpp.
{
  return ref_pb_;
}
References Champ_Generique_base::ref_pb_.
get_ref_values()
const DoubleTab & Champ_Generique_refChamp::get_ref_values () const override virtual
Verifie que le champ est bien un champ discret et
renvoie le tableau de valeurs. Sinon, leve l'exception Champ_Generique_erreur("NO_REF")
Reimplemented from Champ_Generique_base.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 251 of file Champ_Generique_refChamp.cpp.
{
// Appel a get_localisation pour verifier que le champ est bien un champ discret
// (multi-support ou non)
  get_localisation(0);
// Renvoie les valeurs du champ
  const DoubleTab& val = get_ref_champ_base().valeurs();
  return val;
}
References get_localisation(), get_ref_champ_base(), and Champ_Proto::valeurs().
Referenced by get_copy_values().
get_ref_zcl_dis_base()
const Zone_Cl_dis_base & Champ_Generique_refChamp::get_ref_zcl_dis_base () const override virtual
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
Reimplemented from Champ_Generique_base.
Definition at line 276 of file Champ_Generique_refChamp.cpp.
{
  const Champ_base& ch = get_ref_champ_base();
  if (sub_type(Champ_Inc_base,ch))
    return ref_cast(Champ_Inc_base,ch).equation().zone_Cl_dis().valeur();
  else
    {
      Cerr<<"No zcl_dis is available for the field "<<ch.que_suis_je()<<finl;
      exit();
    }
// Pour compilation
  return get_ref_zcl_dis_base();
}
References Cerr, Process::exit(), finl, get_ref_champ_base(), get_ref_zcl_dis_base(), Objet_U::que_suis_je(), ref_cast, and sub_type.
Referenced by get_ref_zcl_dis_base().
get_time()
double Champ_Generique_refChamp::get_time () const override virtual
Renvoie le temps du Champ_Generique.
Reimplemented from Champ_Generique_base.
Definition at line 455 of file Champ_Generique_refChamp.cpp.
{
  double temps;
  temps = get_ref_champ_base().temps();
  return temps;
}
References get_ref_champ_base(), and Champ_base::temps().
get_xyz_values()
void Champ_Generique_refChamp::get_xyz_values (const DoubleTab & coords, DoubleTab & values, ArrOfBit & validity_flag) const override virtual
appel a Champ_base::valeur_aux()
Reimplemented from Champ_Generique_base.
Definition at line 271 of file Champ_Generique_refChamp.cpp.
{
  throw Champ_Generique_erreur("NOT_IMPLEMENTED");
}
info()
const Type_info * Champ_Generique_refChamp::info () static
Definition at line 29 of file Champ_Generique_refChamp.cpp.
initialize()
void Champ_Generique_refChamp::initialize (const Champ_base & champ)
On initialise la classe avec le champ en parametre.
On prend une ref a ce champ (il doit rester valable ensuite).
Definition at line 101 of file Champ_Generique_refChamp.cpp.
{
  ref_champ_ = champ;
}
References ref_champ_.
lire_motcle_non_standard()
int Champ_Generique_refChamp::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns
int
Reimplemented from Objet_U.
Definition at line 60 of file Champ_Generique_refChamp.cpp.
{
  if (mot=="Pb_champ")
    {
// Lecture du nom du probleme et du nom du champ
      is >> nom_pb_ >> nom_champ_;
// Recherche du probleme parmi les objets connus de l'interprete
      const Objet_U& ob = interprete().objet(nom_pb_);
      if (!sub_type(Probleme_base, ob))
        {
          Cerr << "Error in Champ_Generique_refChamp ::lire(keyword=\"pb_champ\"\n"
               << " The object " << nom_pb_ << " is not a Probleme_base" << finl;
          exit();
        }
      Probleme_base& pb = ref_cast_non_const(Probleme_base, ob);
      ref_pb_ = pb;
// Recherche du champ "nom_champ" dans le probleme:
      REF(Champ_base) ref_champ;
      Noms liste_noms;
      pb.get_noms_champs_postraitables(liste_noms);
      pb.creer_champ(nom_champ_);
      ref_champ = pb.get_champ(nom_champ_);
      ref_champ.valeur().corriger_unite_nom_compo();
      set_ref_champ(ref_champ.valeur());
      return 1;
    }
  else if (mot=="nom_source")
    {
      Nom id_source;
      is >> id_source;
      nommer(id_source);
      return 1;
    }
  else
    return Champ_Generique_base::lire_motcle_non_standard(mot,is);
  return 1;
}
References Cerr, Champ_base::corriger_unite_nom_compo(), Probleme_base::creer_champ(), Process::exit(), finl, Probleme_base::get_champ(), Probleme_base::get_noms_champs_postraitables(), Objet_U::interprete(), Champ_Generique_base::lire_motcle_non_standard(), nom_champ_, Champ_Generique_base::nom_pb_, Champ_Generique_base::nommer(), Interprete::objet(), REF, ref_cast_non_const, Champ_Generique_base::ref_pb_, set_ref_champ(), and sub_type.
Referenced by Champ_Generique_Champ::lire_motcle_non_standard().
mettre_a_jour()
void Champ_Generique_refChamp::mettre_a_jour (double temps) override virtual
Voir Champ_Generique_base::mettre_a_jour
Si le champ est champ_inc dans l'equation, il doit deja avoir
ete mis a jour par l'equation.
Si c est un clacule, l actualisation est faite dans get_champ.
Implements Champ_Generique_base.
Definition at line 395 of file Champ_Generique_refChamp.cpp.
{
}
nommer_source()
void Champ_Generique_refChamp::nommer_source ()
Definition at line 524 of file Champ_Generique_refChamp.cpp.
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_base, nom_dom_natif;
      nom_champ_base = get_ref_champ_base().le_nom();
      nom_dom_natif = get_ref_domain().le_nom();
      nom_post_source =  nom_champ_base + "_natif_" + nom_dom_natif;
      nommer(nom_post_source);
    }
}
References get_ref_champ_base(), Champ_Generique_base::get_ref_domain(), Field_base::le_nom(), Domaine::le_nom(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
Referenced by completer(), and Champ_Gen_de_Champs_Gen::nommer_sources().
printOn()
Sortie & Champ_Generique_refChamp::printOn (Sortie & os) const override protected virtual
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 38 of file Champ_Generique_refChamp.cpp.
{
  return os;
}
Referenced by Champ_Generique_Champ::printOn(), and Champ_Generique_refChamp_special::printOn().
readOn()
Entree & Champ_Generique_refChamp::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 44 of file Champ_Generique_refChamp.cpp.
{
  Champ_Generique_base::readOn(is);
  return is;
}
References Champ_Generique_base::readOn().
Referenced by Champ_Generique_Champ::readOn(), and Champ_Generique_refChamp_special::readOn().
reset()
void Champ_Generique_refChamp::reset () override virtual
Implements Champ_Generique_base.
Definition at line 379 of file Champ_Generique_refChamp.cpp.
{
  ref_champ_.reset();
  localisation_ = Motcle();
}
References localisation_, ref_champ_, and Ref_::reset().
Referenced by Champ_Generique_Champ::reset().
self_cast() [1/2]
const Champ_Generique_refChamp & Champ_Generique_refChamp::self_cast (const Objet_U & r) static
Definition at line 29 of file Champ_Generique_refChamp.cpp.
self_cast() [2/2]
Champ_Generique_refChamp & Champ_Generique_refChamp::self_cast (Objet_U & r) static
Definition at line 29 of file Champ_Generique_refChamp.cpp.
set_nom_champ()
void Champ_Generique_refChamp::set_nom_champ (const Motcle & nom)
Definition at line 517 of file Champ_Generique_refChamp.cpp.
{
  nom_champ_=nom;
}
References nom_champ_.
set_param()
void Champ_Generique_refChamp::set_param (Param & param) override virtual
pb_champ : declenche la lecture du nom du probleme (nom_pb_) auquel appartient
le champ discret et le nom de ce champ discret (nom_champ_)
nom_source : option pour nommer le champ en tant que source (sinon nommer par defaut)
Implements Champ_Generique_base.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 54 of file Champ_Generique_refChamp.cpp.
{
  param.ajouter_non_std("nom_source",(this));
  param.ajouter_non_std("Pb_champ",(this),Param::REQUIRED);
}
References Param::ajouter_non_std(), and Param::REQUIRED.
Referenced by Champ_Generique_refChamp_special::set_param().
set_ref_champ()
void Champ_Generique_refChamp::set_ref_champ (const Champ_base & champ) virtual
Associe le champ et determine sa localisation.
Definition at line 419 of file Champ_Generique_refChamp.cpp.
{
  assert(!ref_champ_.non_nul());
  ref_champ_ = champ;
// Determination de la localisation du champ
// On code quelques champs de types connus...
// Pour les autres, il faut les interpoler quelque part.
// L'ideal serait la localisation soit une propriete du champ discret lui-meme.
  Nom type = champ.que_suis_je();
  type.majuscule();
  if (type.debute_par("CHAMP_P0"))
    {
      localisation_ = "ELEMENTS";
    }
  else if (type == "CHAMP_P1")
    {
      localisation_ = "SOMMETS";
    }
  else if (type.debute_par("CHAMP_FACE"))
    {
      localisation_ = "FACES";
    }
  else if (type == "CHAMP_P1NC")
    {
      localisation_ = "FACES";
    }
  else
    {
      localisation_ = "LOCALISATION_INCONNUE";
    }
}
References Nom::debute_par(), localisation_, Nom::majuscule(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), and ref_champ_.
Referenced by Champ_Generique_Champ::lire_motcle_non_standard(), and lire_motcle_non_standard().
taille_memoire()
unsigned Champ_Generique_refChamp::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_Generique_refChamp_special.
Definition at line 29 of file Champ_Generique_refChamp.cpp.
Member Data Documentation
info_obj
const Type_info Champ_Generique_refChamp::info_obj static
Definition at line 35 of file Champ_Generique_refChamp.h.
localisation_
Motcle Champ_Generique_refChamp::localisation_ protected
Definition at line 82 of file Champ_Generique_refChamp.h.
Referenced by reset(), and set_ref_champ().
nom_champ_
Nom Champ_Generique_refChamp::nom_champ_ protected
Definition at line 84 of file Champ_Generique_refChamp.h.
Referenced by get_property(), lire_motcle_non_standard(), and set_nom_champ().
ref_champ_
Ref_Champ_base Champ_Generique_refChamp::ref_champ_ protected
Definition at line 79 of file Champ_Generique_refChamp.h.
Referenced by Champ_Generique_refChamp_special::get_champ(), get_ref_champ_base(), Champ_Generique_refChamp_special::get_ref_values(), initialize(), Champ_Generique_Champ::lire_motcle_non_standard(), reset(), and set_ref_champ().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_refChamp.h
src/Kernel/Champs/Champ_Generique_refChamp.cpp