TRUST: Champ_Fonc_reprise Class Reference
Champ_Fonc_reprise Class Reference
classe Champ_Fonc_reprise
Cette classe permet de relire un champ sauvegarde dans un fichier xyz
elle porte un champ de type Champ_Inc qui est du meme type que le
champ passe en argument
#include <Champ_Fonc_reprise.h>
Public Member Functions
Champ_Fonc_reprise ()
~Champ_Fonc_reprise ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
void mettre_a_jour (double) override
Mise a jour en temps du champ.
const DoubleTab & valeurs () const override
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &les_valeurs) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &les_valeurs, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
renvoie les valeurs aux sommets du Domaine dom
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
renvoie la compo eme valeur aux sommets de dom.
DoubleTab & remplir_coord_noeuds (DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleVect & valeur_aux_compo (const DoubleTab &tab, DoubleVect &les_valeurs, int comp) const override
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Public Member Functions inherited from Champ_Fonc_base
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc_reprise & self_cast (Objet_U &)
static const Champ_Fonc_reprise & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_base
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
virtual const Champ_Inc_base & le_champ () const
virtual Champ_Inc_base & le_champ ()
Private Attributes
Ref_Zone_dis_base zone_dis
Champ_Inc vrai_champ_
Additional Inherited Members
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_Fonc_reprise
Cette classe permet de relire un champ sauvegarde dans un fichier xyz
elle porte un champ de type Champ_Inc qui est du meme type que le
champ passe en argument
Definition at line 41 of file Champ_Fonc_reprise.h.
Constructor & Destructor Documentation
Champ_Fonc_reprise()
Champ_Fonc_reprise::Champ_Fonc_reprise ()
Definition at line 30 of file Champ_Fonc_reprise.cpp.
~Champ_Fonc_reprise()
Champ_Fonc_reprise::~Champ_Fonc_reprise ()
Definition at line 30 of file Champ_Fonc_reprise.cpp.
Member Function Documentation
associer_zone_dis_base()
void Champ_Fonc_reprise::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) inline override virtual
Reimplemented from Champ_base.
Definition at line 78 of file Champ_Fonc_reprise.h.
{
  zone_dis=la_zone_dis_base;
}
References zone_dis.
Referenced by readOn().
cree_instance()
Objet_U * Champ_Fonc_reprise::cree_instance () static
Definition at line 30 of file Champ_Fonc_reprise.cpp.
duplique()
int Champ_Fonc_reprise::duplique () const override virtual
Implements Objet_U.
Definition at line 30 of file Champ_Fonc_reprise.cpp.
get_info()
const Type_info * Champ_Fonc_reprise::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 30 of file Champ_Fonc_reprise.cpp.
info()
const Type_info * Champ_Fonc_reprise::info () static
Definition at line 30 of file Champ_Fonc_reprise.cpp.
le_champ() [1/2]
Champ_Inc_base & Champ_Fonc_reprise::le_champ (void) inline private virtual
Definition at line 87 of file Champ_Fonc_reprise.h.
{
  return vrai_champ_.valeur();
}
References Deriv_Champ_Inc_base::valeur(), and vrai_champ_.
le_champ() [2/2]
const Champ_Inc_base & Champ_Fonc_reprise::le_champ (void) const inline private virtual
Definition at line 82 of file Champ_Fonc_reprise.h.
{
  return vrai_champ_.valeur();
}
References Deriv_Champ_Inc_base::valeur(), and vrai_champ_.
Referenced by readOn(), remplir_coord_noeuds(), remplir_coord_noeuds_et_polys(), valeur_aux_compo(), valeur_aux_elems(), valeur_aux_elems_compo(), valeur_aux_sommets(), valeur_aux_sommets_compo(), and valeurs().
mettre_a_jour()
void Champ_Fonc_reprise::mettre_a_jour (double temps) override virtual
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_base.
Definition at line 446 of file Champ_Fonc_reprise.cpp.
{
  Champ_Fonc_base::mettre_a_jour(t);
}
References Champ_Fonc_base::mettre_a_jour().
printOn()
Sortie & Champ_Fonc_reprise::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 43 of file Champ_Fonc_reprise.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Fonc_reprise::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification:
Contraintes:
< Read the format
< Nombre d'operateurs statistiques
Reimplemented from Champ_Fonc_base.
Definition at line 50 of file Champ_Fonc_reprise.cpp.
{
  Cerr<<"Usage : Champ_Fonc_reprise [xyz|formatte|binaire|single_hdf] fichier.xyz nom_pb nom_inco [fonction n f1(val) f2(val) ... fn(val)] [temps|last_time]"<<finl;
  Nom nom_fic,nom_pb,nom_champ;
  Nom nom_champ_inc;
  Motcle format_rep("xyz");
  int last_time=0;
  double un_temps=-1;
// Lecture
  s>>nom_fic;
  if ((nom_fic==Motcle("xyz"))||(nom_fic==Motcle("binaire"))||(nom_fic==Motcle("single_hdf"))||(nom_fic==Motcle("formatte")))
    {
      format_rep=nom_fic;
      s>>nom_fic;
    }
  s>>nom_pb>>nom_champ;
  if (format_rep == "single_hdf" && Process::nproc() == 1)
    {
      Cerr << "Resuming with a single_hdf option is only available for a parallel calculation !" << finl;
      Process::exit();
    }
  if (Motcle(nom_champ).debute_par("MOYENNE_"))
    nom_champ_inc=((Motcle)nom_champ).suffix("MOYENNE_");
  Motcle ch, time;
  s>>ch;
  VECT(Parser_U) fxyz;
  if (ch=="FONCTION")
    {
      int nb_compo;
      s >> nb_compo;
      fxyz.dimensionner(nb_compo);
      Nom fonction;
      for (int i = 0; i<nb_compo; i++)
        {
          s >> fonction;
          fxyz[i].setNbVar(1);
          fxyz[i].setString(fonction);
          fxyz[i].addVar("val");
          fxyz[i].parseString();
        }
      s >> time;
      if (time=="LAST_TIME")
        last_time=1;
      else
        convert_to(time,un_temps);
    }
  else
    {
      if (ch=="LAST_TIME")
        last_time=1;
      else
        convert_to(ch,un_temps);
    }
// On recupere le pb, puis ensuite on cherche le champ; on recupere la zone_dis
  const Probleme_base& pb =ref_cast(Probleme_base,Interprete::objet(nom_pb));
  REF(Champ_base) ref_ch;
  int reprend_champ_moyen=0;
  int reprend_modele_k_eps=0;
  if (nom_champ_inc=="??")
    nom_champ_inc=nom_champ;
// Cas des champs moyens
  if (((Motcle)nom_champ).debute_par("MOYENNE_"))
    {
      nom_champ+="_natif_";
      nom_champ+=pb.domaine().le_nom();
      reprend_champ_moyen=1;
    }
// Cas du K-Epsilon
  if (((Motcle)nom_champ_inc)=="K_EPS")
    {
      reprend_modele_k_eps=1;
    }
  ref_ch = pb.get_champ(Motcle(nom_champ_inc));
  if (sub_type(Champ_Inc_base,ref_ch.valeur()))
    Cerr << nom_champ_inc << " is an unknown of problem " << nom_pb << finl;
  else
    {
      Cerr << nom_champ_inc << " is not an unknown of problem " << nom_pb << finl;
      Process::exit();
    }
// Ouverture du fichier
  statistiques().begin_count(temporary_counter_);
  Nom ident_lu;
  Nom type_objet_lu;
  int mode_lec_sa= EcritureLectureSpecial::mode_lec;
  DERIV(Entree_Fichier_base) fic_rep;
#ifdef MPI_
  Entree_Brute input_data;
  FichierHDFPar fic_hdf; //FichierHDF fic_hdf;
#endif
  if (format_rep == "xyz")
    {
      EcritureLectureSpecial::mode_lec=1;
      fic_rep.typer(EcritureLectureSpecial::Input);
      Cerr << "Opening xyz file " << nom_fic << " (" << EcritureLectureSpecial::Input << ")" << finl;
    }
  else
    {
      EcritureLectureSpecial::mode_lec=0;
      if (format_rep == "binaire")
        fic_rep.typer("LecFicDistribueBin");
      else if (format_rep == "single_hdf")
        {
#ifdef MPI_
          LecFicDiffuse test;
          if (!test.ouvrir(nom_fic))
            {
              Cerr << "Error! " << nom_fic << " file not found ! " << finl;
              Process::exit();
            }
          fic_hdf.open(nom_fic, true);
          fic_hdf.read_dataset("/sauv", Process::me(),input_data);
#endif
        }
      else
        fic_rep.typer("LecFicDistribue");
      Cerr << "Opening file " << nom_fic << " (LecFicDistribueBin)" << finl;
    }
  if (format_rep != "single_hdf")
    {
      fic_rep->ouvrir(nom_fic);
      if(fic_rep->fail())
        {
          Cerr<<"Error while opening the file of resumption : " <<nom_fic<<finl;
          Process::exit();
        }
      if (fic_rep->eof())
        {
          Cerr << "Error in Champ_Fonc_reprise::reprendre" << finl;
          Cerr << "The resumption file does not exist" << finl;
          Cerr << "or could not be opened correctly." << finl;
          Process::exit();
        }
    }
  if (last_time)
    {
      if(format_rep == "single_hdf")
        {
#ifdef MPI_
          un_temps = get_last_time(input_data);
          fic_hdf.read_dataset("/sauv", Process::me(), input_data);
#endif
        }
      else
        {
          un_temps = get_last_time(fic_rep.valeur());
          fic_rep->close();
          fic_rep->ouvrir(nom_fic);
        }
      Cerr << "In the " << nom_fic << " file, we find the last time: " << un_temps << " and read the fields." << finl;
    }
// Depuis la 1.5.5, lecture du format de sauvegarde
  if(format_rep != "single_hdf")
    fic_rep.valeur() >> ident_lu;
  else
    {
#ifdef MPI_
      input_data >> ident_lu;
#endif
    }
  int format_sauvegarde=0;
  if (ident_lu=="format_sauvegarde:")
    {
      if(format_rep != "single_hdf")
        fic_rep.valeur() >> format_sauvegarde; //!< Read the format
      else
        {
#ifdef MPI_
          input_data >> format_sauvegarde;
#endif
        }
    }
  else
    {
// Version anterieure, on referme et on reouvre
      if (format_rep=="xyz")
        {
          fic_rep->close();
          fic_rep->ouvrir(nom_fic);
        }
      else
        {
          Cerr<<"This .sauv file is too old and the format is not supported anymore."<<finl;
          Process::exit();
        }
    }
// Creation des identifiants
  Nom nom_ident;
  Nom nom_ident_champ_stat;
  Nom nom_ident_champ_keps;
  Nom type=ref_ch.valeur().que_suis_je();
  Nom nom_temps=Nom(un_temps,time_format_from(format_sauvegarde));
  if (reprend_champ_moyen)
    {
      nom_ident="Operateurs_Statistique_tps";
      nom_ident+=pb.domaine().le_nom();
      nom_ident+=nom_temps;
      nom_ident_champ_stat=nom_champ;
      nom_ident_champ_stat+="Champ_Fonc";
      type.suffix("Champ");
      nom_ident_champ_stat+=type;
      nom_ident_champ_stat+=pb.domaine().le_nom();
      nom_ident_champ_stat+=nom_temps;
    }
  else if (reprend_modele_k_eps)
    {
      nom_ident="Modele_turbulence_hyd_K_Epsilon";
      nom_ident+=pb.domaine().le_nom();
      nom_ident+=nom_temps;
      nom_ident_champ_keps=nom_champ_inc;
      nom_ident_champ_keps+=type;
      nom_ident_champ_keps+=pb.domaine().le_nom();
      nom_ident_champ_keps+=nom_temps;
    }
  else
    {
      nom_ident=nom_champ_inc;
      nom_ident+=type;
      nom_ident+=pb.domaine().le_nom();
      nom_ident+=nom_temps;
    }
  associer_zone_dis_base(pb.domaine_dis().zone_dis(0));
// on cree un champ comme le ch_ref;
  const Champ_Inc_base& ch_inc=ref_cast(Champ_Inc_base,ref_ch.valeur());
  vrai_champ_.typer(ch_inc.que_suis_je());
  vrai_champ_->associer_zone_dis_base(pb.domaine_dis().zone_dis(0));
// vrai_champ_->fixer_nb_valeurs_temporelles(2);
  vrai_champ_->nommer(ch_inc.le_nom());
  vrai_champ_->fixer_nb_comp(ch_inc.nb_comp());
// vrai_champ_->fixer_nb_valeurs_nodales(ch_inc.nb_valeurs_nodales());
  vrai_champ_->valeurs() = ch_inc.valeurs();
  nb_compo_ = ch_inc.nb_comp();
  if (ch=="FONCTION")
    if (fxyz.size()!=ch_inc.nb_comp())
      {
        Cerr<<"The number of components read " <<fxyz.size()<<" for the resume function"<<finl;
        Cerr<<"does not corresponds to the number of components "<<ch_inc.nb_comp()<<" of field target"<<finl;
        Process::exit();
      }
// Lecture du fichier
  if (format_rep != "single_hdf")
    avancer_fichier(fic_rep.valeur(), nom_ident);
  else
    {
#ifdef MPI_
      avancer_fichier(input_data, nom_ident);
#endif
    }
  if (reprend_champ_moyen)
    {
      double tdeb,tfin;
      int n; //!< Nombre d'operateurs statistiques
      if (format_rep != "single_hdf")
        {
          fic_rep.valeur() >> n;
          fic_rep.valeur() >> tdeb;
          fic_rep.valeur() >> tfin;
          avancer_fichier(fic_rep.valeur(),nom_ident_champ_stat);
        }
      else
        {
#ifdef MPI_
          input_data >> n;
          input_data >> tdeb;
          input_data >> tfin;
          avancer_fichier(input_data,nom_ident_champ_stat);
#endif
        }
// On cree un operateur_statistique qui va nous permettre de relire le champ moyen
      Op_Moyenne champ_moyen;
// On construit un Champ_Generique_refChamp pour pouvoir associer un Champ_Generique_base
// a l operateur
      Champ_Generique champ;
      Nom ajout("");
      ajout += " refChamp { Pb_champ ";
      ajout += pb.le_nom();
      ajout += " ";
      ajout += le_champ().le_nom();
      ajout += " }";
      Entree_complete s_complete(ajout,s);
      s_complete>>champ;
      champ_moyen.associer(pb.domaine_dis().zone_dis(0),champ.valeur(),tdeb,tfin);
      champ_moyen.completer(pb);
      champ_moyen.fixer_tstat_deb(tdeb,tfin);
      if (format_rep != "single_hdf")
        champ_moyen.reprendre(fic_rep.valeur());
      else
        {
#ifdef MPI_
          champ_moyen.reprendre(input_data);
#endif
        }
// On remplit le champ
      le_champ().valeurs() = champ_moyen.calculer_valeurs();
    }
  else if (reprend_modele_k_eps)
    {
      if (format_rep != "single_hdf")
        {
          avancer_fichier(fic_rep.valeur(), nom_ident_champ_keps);
          le_champ().reprendre(fic_rep.valeur());
        }
      else
        {
#ifdef MPI_
          avancer_fichier(input_data, nom_ident_champ_keps);
          le_champ().reprendre(input_data);
#endif
        }
    }
  else
    {
      if (format_rep != "single_hdf")
        le_champ().reprendre(fic_rep.valeur());
      else
        {
#ifdef MPI_
          le_champ().reprendre(input_data);
#endif
        }
    }
  if(format_rep == "single_hdf")
    {
#ifdef MPI_
      fic_hdf.close();
#endif
    }
  EcritureLectureSpecial::mode_lec=mode_lec_sa;
  statistiques().end_count(temporary_counter_);
  Cerr << "End of resuming the file " << nom_fic << " after " << statistiques().last_time(temporary_counter_) << " s" << finl;
//
// Transformation eventuelle du champ lu
//
  if (fxyz.size())
    {
      DoubleTab& tab_valeurs=le_champ().valeurs();
// Boucle sur les noeuds du champs
      int sz=tab_valeurs.dimension_tot(0);
      int nb_compo=fxyz.size();
      if (tab_valeurs.nb_dim()==1)
        {
          if (nb_compo!=1)
            {
              Cerr << "Error in the function read because the field " << le_champ().le_nom() << " has a single dimension." << finl;
              Process::exit();
            }
        }
      else if (nb_compo!=tab_valeurs.dimension_tot(1))
        {
          Cerr << "Error in the number of components of the function read:" << nb_compo << finl;
          Cerr << "The number of components of field " << le_champ().le_nom() << " is:" << tab_valeurs.dimension_tot(1) << finl;
          Process::exit();
        }
      for (int i=0; i<sz; i++)
        {
          for (int j=0; j<nb_compo; j++)
            {
              fxyz[j].setVar("val",tab_valeurs(i,j));
// On fait la transformation des valeurs du champs
              tab_valeurs(i,j)=fxyz[j].eval();
            }
        }
    }
  return s ;
}
References Op_Moyenne::associer(), Champ_Inc::associer_zone_dis_base(), associer_zone_dis_base(), avancer_fichier(), Statistiques::begin_count(), Op_Moyenne::calculer_valeurs(), Cerr, FichierHDF::close(), Op_Moyenne::completer(), convert_to(), DERIV, TRUSTTab< _TYPE_ >::dimension_tot(), Probleme_base::domaine(), Probleme_base::domaine_dis(), Statistiques::end_count(), Process::exit(), finl, Op_Moyenne::fixer_tstat_deb(), Probleme_base::get_champ(), get_last_time(), EcritureLectureSpecial::Input, Statistiques::last_time(), le_champ(), Field_base::le_nom(), Probleme_base::le_nom(), Domaine::le_nom(), Process::me(), EcritureLectureSpecial::mode_lec, Field_base::nb_comp(), Field_base::nb_compo_, TRUSTTab< _TYPE_ >::nb_dim(), Objet_U::nommer(), Process::nproc(), Interprete::objet(), FichierHDF::open(), Objet_U::que_suis_je(), FichierHDF::read_dataset(), REF, ref_cast, Champ_Inc_base::reprendre(), Op_Moyenne::reprendre(), statistiques(), sub_type, Nom::suffix(), temporary_counter_, test(), time_format_from(), Deriv_::typer(), Deriv_Champ_Generique_base::valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), VECT, vrai_champ_, and Domaine_dis::zone_dis().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_reprise::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 127 of file Champ_Fonc_reprise.h.
{
  return le_champ().remplir_coord_noeuds(coord);
}
References le_champ(), and Champ_Inc_base::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_reprise::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 132 of file Champ_Fonc_reprise.h.
{
  return le_champ().remplir_coord_noeuds_et_polys(coord, elems);
}
References le_champ(), and Champ_Inc_base::remplir_coord_noeuds_et_polys().
self_cast() [1/2]
const Champ_Fonc_reprise & Champ_Fonc_reprise::self_cast (const Objet_U & r) static
Definition at line 30 of file Champ_Fonc_reprise.cpp.
self_cast() [2/2]
Champ_Fonc_reprise & Champ_Fonc_reprise::self_cast (Objet_U & r) static
Definition at line 30 of file Champ_Fonc_reprise.cpp.
taille_memoire()
unsigned Champ_Fonc_reprise::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 30 of file Champ_Fonc_reprise.cpp.
valeur_aux_compo()
DoubleVect & Champ_Fonc_reprise::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const inline override virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
Returns
reference au tableau les_valeurs
Reimplemented from Champ_base.
Definition at line 136 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeur_aux_compo(tab,les_valeurs,comp);
}
References le_champ(), and Champ_Inc_base::valeur_aux_compo().
valeur_aux_elems()
DoubleTab & Champ_Fonc_reprise::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 101 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeur_aux_elems(positions, les_polys, les_valeurs);
}
References le_champ(), and Champ_base::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_reprise::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 108 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeur_aux_elems_compo(positions, les_polys, les_valeurs, ncomp);
}
References le_champ(), and Champ_base::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_reprise::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
Definition at line 116 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeur_aux_sommets(dom, sommets);
}
References le_champ(), and Champ_base::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_reprise::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
Definition at line 121 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeur_aux_sommets_compo(dom, sommets, compo);
}
References le_champ(), and Champ_base::valeur_aux_sommets_compo().
valeurs() [1/2]
const DoubleTab & Champ_Fonc_reprise::valeurs () const inline override virtual
Reimplemented from Champ_Don_base.
Definition at line 92 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeurs();
}
References le_champ(), and Champ_Inc_base::valeurs().
valeurs() [2/2]
DoubleTab & Champ_Fonc_reprise::valeurs () inline override virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
DoubleTab&
Signification: le tableau des valeurs du champs
Reimplemented from Champ_Don_base.
Definition at line 96 of file Champ_Fonc_reprise.h.
{
  return le_champ().valeurs();
}
References le_champ(), and Champ_Inc_base::valeurs().
zone_dis_base()
const Zone_dis_base & Champ_Fonc_reprise::zone_dis_base () const override virtual
Reimplemented from Champ_base.
Definition at line 453 of file Champ_Fonc_reprise.cpp.
{
  return zone_dis;
}
References zone_dis.
Member Data Documentation
info_obj
const Type_info Champ_Fonc_reprise::info_obj static
Definition at line 44 of file Champ_Fonc_reprise.h.
vrai_champ_
Champ_Inc Champ_Fonc_reprise::vrai_champ_ private
Definition at line 73 of file Champ_Fonc_reprise.h.
Referenced by le_champ(), and readOn().
zone_dis
Ref_Zone_dis_base Champ_Fonc_reprise::zone_dis private
Definition at line 71 of file Champ_Fonc_reprise.h.
Referenced by associer_zone_dis_base(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/Kernel/VF/Champs/Champ_Fonc_reprise.h
src/Kernel/VF/Champs/Champ_Fonc_reprise.cpp