TRUST: SChaine Class Reference
SChaine Class Reference
Cette classe derivee de Sortie empile ce qu'on lui envoie dans une
chaine de caracteres. On recupere le contenu de la chaine avec get_str().
#include <SChaine.h>
Public Member Functions
SChaine ()
~SChaine () override
const char * get_str () const
returns a copy of the string stored by the SChaine
unsigned get_size () const
void setf (std::_Ios_Fmtflags code) override
int set_bin (int bin) override
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Public Member Functions inherited from Sortie
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int ob)
virtual Sortie & operator<< (const unsigned ob)
virtual Sortie & operator<< (const long ob)
virtual Sortie & operator<< (const float ob)
virtual Sortie & operator<< (const double ob)
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual Sortie & operator<< (const std::string &str)
virtual int add_col (const double ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
virtual int put (const int *ob, int n, int nb_colonnes=1)
virtual int put (const float *ob, int n, int nb_colonnes=1)
virtual int put (const double *ob, int n, int nb_colonnes=1)
virtual int put (const long *ob, int n, int nb_colonnes=1)
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Protected Attributes
std::string string_
Protected Attributes inherited from Sortie
int bin_
int col_width_
Detailed Description
Cette classe derivee de Sortie empile ce qu'on lui envoie dans une
chaine de caracteres. On recupere le contenu de la chaine avec get_str().
Definition at line 27 of file SChaine.h.
Constructor & Destructor Documentation
SChaine()
SChaine::SChaine ()
Definition at line 58 of file SChaine.cpp.
{
  set_bin(0);
  ostringstream *os = new ostringstream();
  set_ostream(os);
}
References set_bin(), and Sortie::set_ostream().
~SChaine()
SChaine::~SChaine () override
Definition at line 72 of file SChaine.cpp.
{
}
Member Function Documentation
get_size()
unsigned SChaine::get_size () const
Definition at line 87 of file SChaine.cpp.
{
  const ostringstream& os = static_cast< const ostringstream& >(get_ostream());
  return os.str().size();
}
References Sortie::get_ostream().
get_str()
const char * SChaine::get_str () const
returns a copy of the string stored by the SChaine
Definition at line 79 of file SChaine.cpp.
{
  const ostringstream& os = static_cast< const ostringstream& >(get_ostream());
// Need a copy to make sure the char * remains unchanged even if the SChaine is further filled.
  string_=string(os.str());
  return string_.c_str();
}
References Sortie::get_ostream(), and string_.
Referenced by Refine_Mesh::build_new_sub_zones_descriptions(), Op_Div_VEFP1B_Elem::degres_liberte(), Statistiques::dump(), Extraire_plan::interpreter_(), LecFicDiffuse_JDD::ouvrir(), and Simpler_Base::readOn().
set_bin()
int SChaine::set_bin (int bin) override virtual
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Reimplemented from Sortie.
Definition at line 93 of file SChaine.cpp.
{
  if (bin != 0)
    {
      Cerr << "Error in SChaine::set_bin(int bin) : binary format not supported" << finl;
      Process::exit();
    }
  Sortie::set_bin(bin);
  return bin;
}
References Cerr, Process::exit(), finl, and Sortie::set_bin().
Referenced by SChaine().
setf()
void SChaine::setf (std::_Ios_Fmtflags code) override virtual
Reimplemented from Sortie.
Definition at line 65 of file SChaine.cpp.
{
  Sortie::setf( code );
// Cerr << "Error in SChaine::setf(IOS_FORMAT code)" << finl;
// Process::exit();
}
References Sortie::setf().
Member Data Documentation
string_
std::string SChaine::string_ mutable protected
Definition at line 39 of file SChaine.h.
Referenced by get_str().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/SChaine.h
src/Kernel/Utilitaires/SChaine.cpp