TRUST: Op_Diff_VEFP1NCP1B_Face Class Reference
Op_Diff_VEFP1NCP1B_Face Class Reference
class Op_Diff_VEF_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
#include <Op_Diff_VEFP1NCP1B_Face.h>
Public Member Functions
~Op_Diff_VEFP1NCP1B_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_VEFP1NCP1B_Face ()
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
const Zone_VEF_PreP1b & zone_VEFPreP1B () const
const Zone_Cl_VEFP1B & zone_Cl_VEFPreP1B () const
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void contribuer_au_second_membre (DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Op_Diff_VEF_Face
Op_Diff_VEF_Face ()
~Op_Diff_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
associe le champ de diffusivite
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
const Champ_base & diffusivite () const override
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void verifier () const
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, DoubleTab &nu, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEFP1NCP1B_Face & self_cast (Objet_U &)
static const Op_Diff_VEFP1NCP1B_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Diff_VEF_Face & self_cast (Objet_U &)
static const Op_Diff_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void initialiser ()
void remplir_nu_p1 (const DoubleTab &, DoubleTab &) const
Calcule la diffusivite "nu_p1" aux sommets du maillage
en fonction de la diffusivite "nu_elem" aux elements.
On suppose que nu_elem a son espace virtuel a jour,
que nu_p1 est dimensionne nb_dim==1 avec la structure domaine.md_vector_sommets()
En sortie l'espace virtuel de nu_p1 est mis a jour
L'interpolateur calculs pour un sommet la moyenne (non ponderee) des
diffusivites sur les elements adjacents a ce sommet.
void remplir_nu_pA (const DoubleTab &, DoubleTab &) const
DoubleVect & calculer_gradient_elem (const DoubleVect &) const
DoubleVect & calculer_gradient_som (const DoubleVect &) const
DoubleVect & calculer_gradient_aretes (const DoubleVect &) const
DoubleVect & calculer_divergence_elem (DoubleVect &) const
DoubleVect & calculer_divergence_som (DoubleVect &) const
DoubleVect & calculer_divergence_aretes (DoubleVect &) const
DoubleVect & corriger_div_pour_Cl (const DoubleVect &, const DoubleTab &, DoubleVect &) const
DoubleTab & corriger_pour_diffusivite (const DoubleTab &, DoubleTab &) const
void calculer_laplacien_som (const DoubleTab &) const
void calculer_flux_bords_elem (const DoubleVect &) const
void calculer_flux_bords_som (const DoubleVect &) const
void calculer_flux_bords_aretes (const DoubleVect &) const
void calculer_dt_stab_elem (const DoubleTab &, DoubleTab &) const
void calculer_dt_stab_som (const DoubleTab &, DoubleTab &) const
void calculer_dt_stab_aretes (const DoubleTab &, DoubleTab &) const
void ajouter_contribution_elem (const DoubleTab &, const DoubleVect &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_som (const DoubleTab &, const DoubleVect &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_aretes (const DoubleTab &, const DoubleVect &, const DoubleTab &, Matrice_Morse &) const
void coeff_matrice_som (const int, IntVect &, DoubleTab &, DoubleTab &, const DoubleVect &, const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void coeff_matrice_som_CL (const int, IntVect &, DoubleTab &, DoubleTab &, const DoubleVect &, const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void coeff_matrice_som_symetrie (const int, IntVect &, DoubleTab &, DoubleTab &, const DoubleVect &, const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void coeff_matrice_som_perio (const int, const int, IntVect &, DoubleTab &, DoubleTab &, const DoubleVect &, const DoubleTab &, const DoubleTab &, Matrice_Morse &) const
void gradient_som (const int face, const int, const int, const int, const int, const int, DoubleTab &) const
void gradient_som (const int, int &, IntVect &, DoubleTab &) const
void gradient_som_CL (const int, int &, IntVect &, DoubleTab &) const
void isInStencil (int, int, int &, int &, int &, int &) const
void isFaceOfSymetry (ArrOfBit &, int &) const
void liste_face (IntLists &, int &) const
void test () const
void corriger_Cl_test (DoubleTab &) const
Protected Member Functions inherited from Op_Diff_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
int test_
DoubleTab gradient_p0_
DoubleTab gradient_p1_
DoubleTab gradient_pa_
Matrice_Morse laplacien_p1_
int is_laplacian_filled_
int is_laplacian_built_
double convexite_
double coeff_
int alphaE
int alphaS
int alphaA
int dim_ch_
int decentrage_
Protected Attributes inherited from Op_Diff_VEF_Face
Ref_Champ_base diffusivite_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Diff_VEF_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
Definition at line 40 of file Op_Diff_VEFP1NCP1B_Face.h.
Constructor & Destructor Documentation
~Op_Diff_VEFP1NCP1B_Face()
Op_Diff_VEFP1NCP1B_Face::~Op_Diff_VEFP1NCP1B_Face ()
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
Op_Diff_VEFP1NCP1B_Face()
Op_Diff_VEFP1NCP1B_Face::Op_Diff_VEFP1NCP1B_Face ()
Definition at line 62 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
// Initialisation des attributs
  convexite_=1.e-3;
  alphaE=1;
  alphaS=1;
  alphaA=0;
  test_=0;
  coeff_=1.;//alphaE+alphaS;
  decentrage_=1;
  is_laplacian_filled_=0;
}
References alphaA, alphaE, alphaS, coeff_, convexite_, decentrage_, is_laplacian_filled_, and test_.
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_VEFP1NCP1B_Face::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 994 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const int nb_aretes_tot=zone.nb_aretes_tot();
// Recuperation de la diffusivite
  remplir_nu(nu_);
// Pour tenir compte de la porosite
  const int marq = phi_psi_diffuse(equation());
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  DoubleTab nu,nu_p1,nu_pA;
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  DoubleTab inconnue1;
  modif_par_porosite_si_flag(inconnue,inconnue1,marq,porosite_face);
  const DoubleVect& inconnue2 = inconnue1;
  DoubleVect& resu2 = resu;
  DoubleVect resu3(resu2);
  resu3=0.;
  if (alphaE)
    {
      gradient_p0_=0.;
      calculer_gradient_elem(inconnue2);
      corriger_pour_diffusivite(nu,gradient_p0_);
      gradient_p0_*=convexite_;
      calculer_divergence_elem(resu3);
      calculer_flux_bords_elem(inconnue2);
    }
  if (alphaA)
    {
      gradient_pa_=0.;
      nu_pA.resize(nb_aretes_tot);
      remplir_nu_pA(nu,nu_pA);
      calculer_gradient_aretes(inconnue2);
      corriger_pour_diffusivite(nu_pA,gradient_pa_);
      calculer_divergence_aretes(resu3);
      calculer_flux_bords_aretes(inconnue2);
    }
  corriger_div_pour_Cl(inconnue2,nu,resu3);
// Le corriger_div_pour_Cl() doit etre fait AVANT le calcul
// de la partie p1 car la matrice est deja codee pour tenir
// compte des coefficients periodiques
// REMARQUE IMPORTANTE : pour des raisons techniques inherentes
// a TrioU, le calcul du dt_stab a lieu AVANT l'application
// de la fonction ajouter(). Or le dt_stab a besoin de la matrice
// pour etre correctement calcule par consequent, la matrice
// laplacien_p1_ est construite dans la fonction calculer_dt_stab()
// et est seulement reutilisee ici.
  if (alphaS)
    {
      zone.domaine().creer_tableau_sommets(nu_p1);
      remplir_nu_p1(nu,nu_p1);
      laplacien_p1_.ajouter_multvect(inconnue2,resu3);
      gradient_p1_=0.;
      calculer_gradient_som(inconnue2);
      corriger_pour_diffusivite(nu_p1,gradient_p1_);
      gradient_p1_*=(1.-convexite_);
      calculer_flux_bords_som(inconnue2);
    }
  if (test_) test();
  resu2+=resu3;
  resu.echange_espace_virtuel();
  modifier_flux(*this);
  return resu;
}
References Matrice_Base::ajouter_multvect(), alphaA, alphaE, alphaS, calculer_divergence_aretes(), calculer_divergence_elem(), calculer_flux_bords_aretes(), calculer_flux_bords_elem(), calculer_flux_bords_som(), calculer_gradient_aretes(), calculer_gradient_elem(), calculer_gradient_som(), convexite_, corriger_div_pour_Cl(), corriger_pour_diffusivite(), Domaine::creer_tableau_sommets(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), gradient_p0_, gradient_p1_, gradient_pa_, laplacien_p1_, modif_par_porosite_si_flag(), Op_VEF_Face::modifier_flux(), Zone::nb_aretes_tot(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), remplir_nu_p1(), remplir_nu_pA(), TRUSTTab< _TYPE_ >::resize(), test(), test_, Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by calculer().
ajouter_contribution()
void Op_Diff_VEFP1NCP1B_Face::ajouter_contribution (const DoubleTab & inconnue, Matrice_Morse & matrice) const
Definition at line 2174 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
// Marqueur pour tenir compte de la porosite
  const int marq=phi_psi_diffuse(equation());
// Lignes pour tenir compte de la porosite
  const DoubleVect& porosite_elem=zone_VEF.porosite_elem();
  DoubleVect porosite_face(zone_VEF.porosite_face());
  if (!marq) porosite_face=1.;
// Lignes pour tenir compte de la diffusivite
  DoubleTab nu,nu_p1,nu_pA;
  remplir_nu(nu_);
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
// RESTE juste a gerer la porosite a la face
  if (alphaE)
    ajouter_contribution_elem(inconnue,porosite_face,nu,matrice);
  if (alphaS)
    {
      zone.domaine().creer_tableau_sommets(nu_p1);
      remplir_nu_p1(nu,nu_p1);
      ajouter_contribution_som(inconnue,porosite_face,nu_p1,matrice);
    }
  if (alphaA)
    {
      zone_VEF.creer_tableau_aretes(nu_pA);
      remplir_nu_pA(nu,nu_pA);
      ajouter_contribution_aretes(inconnue,porosite_face,nu_pA,matrice);
    }
  if (test_) test();
}
References ajouter_contribution_aretes(), ajouter_contribution_elem(), ajouter_contribution_som(), alphaA, alphaE, alphaS, Zone_VF::creer_tableau_aretes(), Domaine::creer_tableau_sommets(), Zone::domaine(), MorEqn::equation(), modif_par_porosite_si_flag(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), remplir_nu_p1(), remplir_nu_pA(), test(), test_, Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by contribuer_a_avec().
ajouter_contribution_aretes()
void Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_aretes (const DoubleTab & inconnue, const DoubleVect & porosite_face, const DoubleTab & nu, Matrice_Morse & matrice) const protected
Definition at line 1616 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
}
Referenced by ajouter_contribution().
ajouter_contribution_elem()
void Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem (const DoubleTab & inconnue, const DoubleVect & porosite_face, const DoubleTab & nu, Matrice_Morse & matrice) const protected
Definition at line 1337 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
// int nb_faces_tot = zone_VEF.nb_faces_tot();
  int nb_faces=zone_VEF.nb_faces();
  int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  int nb_comp = inconnue.line_size();
  int i,j,num_face;
  int elem1,elem2;
  double val;
  double coeff=1./coeff_;
  if (alphaS) coeff*=convexite_;
  int nb_bords=zone_VEF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int fac_asso;
          for (num_face=num1; num_face<num2; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              fac_asso = la_cl_perio.face_associee(num_face-num1)+num1;
// A la fin de la boucle :
// si ok=1, alors num_face appartient bien a elem1
// si ok=0, alors num_face n'appartient pas a elem1 et
// fac_asso appartient a elem1
              int ok=1;
              int fac_loc=0;
              while ((fac_loc<nb_faces_elem) && (elem_faces(elem1,fac_loc)!=num_face)) fac_loc++;
              if (fac_loc==nb_faces_elem) ok=0;
              for (i=0; i<nb_faces_elem; i++)
                if ( ( (j= elem_faces(elem1,i)) > num_face ) && (j != fac_asso ) )
                  {
                    val = viscA(num_face,j,elem1,nu(elem1));
// int fac_loc=0;
// while ((fac_loc<nb_faces_elem) && (elem_faces(elem1,fac_loc)!=num_face)) fac_loc++;
// if (fac_loc==nb_faces_elem) ok=0;
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        matrice(n0,n0)+=val*porosite_face(num_face)*coeff;
                        matrice(n0,j0)-=val*porosite_face(j)*coeff;
                        if (!ok) n0=fac_asso*nb_comp+nc;
                        if (j<nb_faces)
{
                            matrice(j0,n0)-=val*porosite_face((n0-nc)/nb_comp)*coeff;
                            matrice(j0,j0)+=val*porosite_face(j)*coeff;
                          }
                      }
                  }
// Deuxieme element
              elem2 = face_voisins(num_face,1);
              for (i=0; i<nb_faces_elem; i++)
                if ( ( (j= elem_faces(elem2,i)) > num_face ) && (j != fac_asso ) )
                  {
                    val = viscA(num_face,j,elem2,nu(elem2));
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        matrice(n0,n0)+=val*porosite_face(num_face)*coeff;
                        matrice(n0,j0)-=val*porosite_face(j)*coeff;
                      }
                  }
            }//fin du for sur "num_face"
        }
      else
        {
          for (num_face=num1; num_face<num2; num_face++)
            {
              elem1 = face_voisins(num_face,0);
              for (i=0; i<nb_faces_elem; i++)
                if ( (j= elem_faces(elem1,i)) > num_face )
                  {
                    val = viscA(num_face,j,elem1,nu(elem1));
                    for (int nc=0; nc<nb_comp; nc++)
                      {
                        int n0=num_face*nb_comp+nc;
                        int j0=j*nb_comp+nc;
                        matrice(n0,n0)+=val*porosite_face(num_face)*coeff;
                        matrice(n0,j0)-=val*porosite_face(j)*coeff;
                        if (j<nb_faces) //necessaire ????
{
                            matrice(j0,n0)-=val*porosite_face(num_face)*coeff;
                            matrice(j0,j0)+=val*porosite_face(j)*coeff;
                          }
                      }
                  }
            }
        }
    }
// On ne remplit que les lignes reelles
  for (num_face=zone_VEF.premiere_face_int(); num_face<nb_faces; num_face++)
    {
      elem1 = face_voisins(num_face,0);
      elem2 = face_voisins(num_face,1);
      for (i=0; i<nb_faces_elem; i++)
        {
          if ( (j=elem_faces(elem1,i)) > num_face )
            {
              val = viscA(num_face,j,elem1,nu(elem1));
              for (int nc=0; nc<nb_comp; nc++)
                {
                  int n0=num_face*nb_comp+nc;
                  int j0=j*nb_comp+nc;
                  matrice(n0,n0)+=val*porosite_face(num_face)*coeff;
                  matrice(n0,j0)-=val*porosite_face(j)*coeff;
                  if (j<nb_faces)
                    {
                      matrice(j0,n0)-=val*porosite_face(num_face)*coeff;
                      matrice(j0,j0)+=val*porosite_face(j)*coeff;
                    }
                }
            }
// if (elem2!=-1) //test non necessaire car la face est reelle
          if ( (j=elem_faces(elem2,i)) > num_face )
            {
              val= viscA(num_face,j,elem2,nu(elem2));
              for (int nc=0; nc<nb_comp; nc++)
                {
                  int n0=num_face*nb_comp+nc;
                  int j0=j*nb_comp+nc;
                  matrice(n0,n0)+=val*porosite_face(num_face)*coeff;
                  matrice(n0,j0)-=val*porosite_face(j)*coeff;
                  if (j<nb_faces)
                    {
                      matrice(j0,n0)-=val*porosite_face(num_face)*coeff;
                      matrice(j0,j0)+=val*porosite_face(j)*coeff;
                    }
                }
            }
        }
    }
}
References alphaS, coeff, coeff_, convexite_, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by ajouter_contribution(), and test().
ajouter_contribution_som()
void Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som (const DoubleTab & inconnue, const DoubleVect & porosite_face, const DoubleTab & nu_som, Matrice_Morse & matrice) const protected
Definition at line 1509 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  IntVect liste_som(dimension+2);//pour triangles et tetraedres
  DoubleTab gradient0(dimension,dimension+2);
  DoubleTab gradient1(dimension);
  const int premiere_face_int=zone_VEF.premiere_face_int();
  const int nb_faces=zone_VEF.nb_faces();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_bords=zone_VEF.nb_front_Cl();
  int face=0;
  int ind_face=0;
  int n_bord=0;
  int num1=0,num2=0;
  DoubleTab coeff_perio(nb_faces_tot);
  coeff_perio=1.;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
            coeff_perio(face)=0.5;
          }
    }
//
// Partie P1 du laplacien discret :
// on tourne sur les lignes donc nous n'avons
// besoin que de remplir les lignes reelles.
// ATTENTION : le remplissage des lignes reelles
// peut induire le calcul d'un coefficient
// lie a une colonne virtuelle
//
  /* Faces internes */
  for (face=premiere_face_int; face<nb_faces; face++)
    {
      coeff_matrice_som(face,liste_som,
                        gradient0,gradient1,
                        porosite_face,nu_som,
                        coeff_perio,matrice);
    }
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int faceAss=0;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              faceAss=le_bord.num_face(la_cl_perio.face_associee(ind_face));
// On prend la plus petite des faces pour etre sur de n'oublier
// aucune face de bord
              coeff_matrice_som_perio(face,faceAss,liste_som,
                                      gradient0,gradient1,
                                      porosite_face,nu_som,
                                      coeff_perio,matrice);
            }
        }
      else if (sub_type(Symetrie,la_cl.valeur()))
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
            coeff_matrice_som_symetrie(face,liste_som,
                                       gradient0,gradient1,
                                       porosite_face,nu_som,
                                       coeff_perio,matrice);
          }
      else
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
            coeff_matrice_som_CL(face,liste_som,
                                 gradient0,gradient1,
                                 porosite_face,nu_som,
                                 coeff_perio,matrice);
          }
    }
}
References coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), Objet_U::dimension, Periodique::face_associee(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and zone_VEFPreP1B().
Referenced by ajouter_contribution(), calculer_laplacien_som(), and test().
associer()
void Op_Diff_VEFP1NCP1B_Face::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_diffuse) override virtual
Implements Operateur_base.
Definition at line 192 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zvef = ref_cast(Zone_VEF_PreP1b,zone_dis.valeur());
  const Zone_Cl_VEFP1B& zclvef = ref_cast(Zone_Cl_VEFP1B,zone_cl_dis.valeur());
// On bloque la symetrie dans l operateur de diffusion P1NC sur vitesse (OK pour scalaire)
  for (int i = 0; i<zclvef.nb_cond_lim(); i++)
    {
      Cond_lim la_cl = zclvef.les_conditions_limites(i);
      if ( sub_type(Symetrie,la_cl.valeur()) && (ch_diffuse.valeur().nature_du_champ()==vectoriel) )
        {
          Cerr << "\nBoundary conditions of 'Symetrie' type with P1NCP1B diffusion operator are only allowed for Conduction equation!" << finl;
          Cerr << "Here you use a P1NCP1B diffusion operator in a '" << equation().que_suis_je() << "' equation where" << finl;
          Cerr << "boundary condition number " << i << ", on boundary '" << la_cl.frontiere_dis().le_nom() << "' has been assigned to: '" << la_cl.valeur().que_suis_je() << "'." << finl;
          Process::exit();
        }
    }
  if (sub_type(Champ_P1NC,ch_diffuse.valeur()))
    {
      const Champ_P1NC& inco = ref_cast(Champ_P1NC,ch_diffuse.valeur());
      inconnue_ = inco;
    }
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
}
References Cerr, MorEqn::equation(), Process::exit(), finl, Cond_lim::frontiere_dis(), Op_Diff_VEF_base::inconnue_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Field_base::nature_du_champ(), Zone_Cl_dis_base::nb_cond_lim(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), Deriv_Cond_lim_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and vectoriel.
calculer()
DoubleTab & Op_Diff_VEFP1NCP1B_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 1077 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  resu = 0;
  return ajouter(inconnue,resu);
}
References ajouter().
calculer_divergence_aretes()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::calculer_divergence_aretes (DoubleVect & div) const protected
Definition at line 961 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  return div;
}
Referenced by ajouter().
calculer_divergence_elem()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem (DoubleVect & div) const protected
Definition at line 818 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  int elem=0,face_loc=0,face=0,compi=0,compj=0;
  double signe=0.;
  for(elem=0; elem<nb_elem_tot; elem++)
    for(face_loc=0; face_loc<nb_faces_elem; face_loc++)
      {
        face=elem_faces(elem,face_loc);
        signe=1.;
        if(elem!=face_voisins(face,0)) signe=-1.;
        for(compi=0; compi<dim_ch_; compi++)
          for(compj=0; compj<dimension; compj++)
            div[face*dim_ch_+compi]-=
              gradient_p0_(elem,compi,compj)
              *signe*face_normales(face,compj);
      }
  div.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B divergence P0 : ", div);
  return div;
}
References dim_ch_, Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), gradient_p0_, Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Debog::verifier(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by ajouter().
calculer_divergence_som()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som (DoubleVect & div) const protected
Definition at line 854 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  ArrOfDouble sigma(dimension);
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const int nb_faces_elem=zone.nb_faces_elem();
  const int nb_som_face=zone_VEF.nb_som_face();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  int elem=0,face_loc=0,face_loc2=0,face=0;
  int compi=0,compj=0,som=0,ind_face=0;
  int num1=0, num2=0,som_loc=0;
  static double coeff_som=1./(dimension)/(dimension+1);
  double signe=0.;
// Algorithme sans tenir compte des CL
  for(elem=0; elem<nb_elem_tot; elem++)
    for(face_loc=0; face_loc<nb_faces_elem; face_loc++)
      {
        som=dom.get_renum_som_perio(som_elem(elem,face_loc));
        face=elem_faces(elem,face_loc);
        signe=1;
        if(elem!=face_voisins(face,0)) signe=-1;
        for(compj=0; compj<dimension; compj++)
          sigma[compj]=signe*face_normales(face,compj);
        for(face_loc2=0; face_loc2<nb_faces_elem; face_loc2++)
          for(compi=0; compi<dim_ch_; compi++)
            for(compj=0; compj<dimension; compj++)
              div[elem_faces(elem,face_loc2)*dim_ch_+compi]-=
                coeff_som*gradient_p1_(som,compi,compj)*sigma[compj];
      }
// Les conditions aux limites
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  const int nb_bords =les_cl.size();
  DoubleTab gradient_bord(dim_ch_,dimension);
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces();
      if (sub_type(Neumann,la_cl.valeur()) ||
          sub_type(Neumann_val_ext,la_cl.valeur()) ||
          sub_type(Neumann_homogene,la_cl.valeur()) ||
          sub_type(Symetrie,la_cl.valeur())
         )
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
// Le numero de la face (qui peut etre virtuelle)
              face=le_bord.num_face(ind_face);
// Le numero de l'element voisin
              elem=face_voisins(face,0);
              assert(elem!=-1);
// Calcul du gradient au milieu de la face de bord
// On prend une integration numerique approchee
              gradient_bord=0.;
              for (som_loc=0; som_loc<nb_som_face; som_loc++)
                {
                  som=dom.get_renum_som_perio(face_sommets(face,som_loc));
                  for(compi=0; compi<dim_ch_; compi++)
                    for(compj=0; compj<dimension; compj++)
                      gradient_bord(compi,compj)+=
                        gradient_p1_(som,compi,compj);
                }
              gradient_bord/=dimension;
// Calcul divergence au bord : formule d'integration numerique
// exacte pour polynome d'ordre 1
              for(compi=0; compi<dim_ch_; compi++)
                for(compj=0; compj<dimension; compj++)
                  div[face*dim_ch_+compi]-=
                    gradient_bord(compi,compj)
                    *face_normales(face,compj);
            }//fin du for sur "ind_face"
        }//fin du if sur "Neumann_paroi", "Neumann", "Symetrie"
    }//fin du for sur "n_bords"
  div.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B divergence P1 : ", div);
  return div;
}
References dim_ch_, Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), gradient_p1_, Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Zone_VF::nb_som_face(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Debog::verifier(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by test().
calculer_dt_stab()
double Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 230 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_faces=zone_VEF.nb_faces();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const DoubleVect& volumes_entrelaces=zone_VEF.volumes_entrelaces();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  DoubleTab coeffOperateur(nb_faces_tot);
  coeffOperateur=0.;
  DoubleTab nu;
  const int nb_bords=les_cl.size();
  const int marq = phi_psi_diffuse(equation());
  int face=0;
  int ind_face=0;
  int num1=0,num2=0;
  int n_bord=0;
  double dt_stab=DMAXFLOAT;
// Calcul de la porosite
  remplir_nu(nu_);
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
// Calcul : contribution des parties P0, P1 et Pa au dt_stab
  if (alphaE) calculer_dt_stab_elem(nu,coeffOperateur);
  if (alphaS)
    {
      DoubleTab nu_p1;
      zone.domaine().creer_tableau_sommets(nu_p1);
      remplir_nu_p1(nu,nu_p1);
      calculer_dt_stab_som(nu_p1,coeffOperateur);
    }
  if (alphaA)
    {
      DoubleTab nu_pA;
      zone_VEF.creer_tableau_aretes(nu_pA);
      remplir_nu_pA(nu,nu_pA);
      calculer_dt_stab_aretes(nu_pA,coeffOperateur);
    }
// Calcul : modification pour tenir compte de la matrice de masse
  for (face=0; face<nb_faces; face++)
    {
      coeffOperateur(face)/=volumes_entrelaces(face);
      assert(coeffOperateur(face)>=0.);
      coeffOperateur(face)=1./(coeffOperateur(face)+DMINFLOAT);
    }
// Calcul : modification pour les faces de Dirichlet
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Dirichlet_homogene,la_cl.valeur()) ||
          sub_type(Dirichlet,la_cl.valeur())
         )
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
            coeffOperateur(face)=1.e20;
          }
    }
// Calcul du pas de temps de stabilite
// : on en a besoin que sur les faces reelles
  for (face=0; face<nb_faces; face++)
    if (coeffOperateur(face)<dt_stab)
      dt_stab=coeffOperateur(face);
  dt_stab=Process::mp_min(dt_stab);
  return dt_stab;
}
References alphaA, alphaE, alphaS, calculer_dt_stab_aretes(), calculer_dt_stab_elem(), calculer_dt_stab_som(), Zone_VF::creer_tableau_aretes(), Domaine::creer_tableau_sommets(), DMAXFLOAT, DMINFLOAT, Zone::domaine(), MorEqn::equation(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), modif_par_porosite_si_flag(), Process::mp_min(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Op_Diff_VEF_base::nu_, Front_VF::num_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), ref_cast, Op_Diff_VEF_base::remplir_nu(), remplir_nu_p1(), remplir_nu_pA(), vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_VF::volumes_entrelaces(), Zone_dis_base::zone(), and zone_VEFPreP1B().
calculer_dt_stab_aretes()
void Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_aretes (const DoubleTab & nu, DoubleTab & coeffOperateur) const protected
Definition at line 415 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  Cerr<<"Error in Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_aretes()"<<finl;
  Cerr<<"Function not coded"<<finl;
  Cerr<<"Exit"<<finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by calculer_dt_stab().
calculer_dt_stab_elem()
void Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem (const DoubleTab & nu, DoubleTab & coeffOperateur) const protected
Definition at line 315 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const int nb_elem_tot=zone.nb_elem_tot();
  const int nb_faces_elem=zone.nb_faces_elem();
  const int nb_bords=les_cl.size();
  int elem=0;
  int face=0,face_loc=0;
  int faceAss=0,faceAss_loc=0;
  int dim=0;
  int ind_face=0;
  int num1=0,num2=0;
  int n_bord=0;
  double psc=0.;
  double volume=0.;
  double nu_elem=0.;
  double coeff=0.;
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      volume=volumes(elem);
      nu_elem=nu_(elem);
      for (face_loc=0; face_loc<nb_faces_elem; face_loc++)
        {
          face=elem_faces(elem,face_loc);
          psc=0.;
          for (dim=0; dim<dimension; dim++)
            psc+=face_normales(face,dim)*face_normales(face,dim);
          coeff=nu_elem;
          coeff/=volume;
          coeff*=psc;
          coeff*=convexite_;
          coeffOperateur(face)+=coeff;
        }
    }
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              faceAss_loc=la_cl_perio.face_associee(ind_face);
              faceAss=le_bord.num_face(faceAss_loc);
              if (face<faceAss)
                {
                  coeffOperateur(faceAss)+=coeffOperateur(face);
                  coeffOperateur(face)=coeffOperateur(faceAss);
                }
            }
        }
    }
}
References coeff, convexite_, Objet_U::dimension, Zone_VF::elem_faces(), Periodique::face_associee(), Zone_VEF::face_normales(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Op_Diff_VEF_base::nu_, Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_VF::volumes(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by calculer_dt_stab().
calculer_dt_stab_som()
void Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_som (const DoubleTab & nu_som, DoubleTab & coeffOperateur) const protected
Definition at line 394 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const int nb_faces=zone_VEF.nb_faces();
  int face=0;
  int face_C=0;
  if (laplacien_p1_.nb_lignes()<2) dimensionner(laplacien_p1_);
  if (!is_laplacian_filled_) calculer_laplacien_som(nu_som);
// REMARQUE : on multiplie par -1 car laplacien_p1_=+Delta
  for (face=0; face<nb_faces; face++)
    {
      face_C=face*dim_ch_;//pour le cas vectoriel
      coeffOperateur(face)+=-1.*laplacien_p1_(face_C,face_C);
    }
}
References calculer_laplacien_som(), dim_ch_, dimensionner(), is_laplacian_filled_, laplacien_p1_, Zone_VF::nb_faces(), Matrice_Morse::nb_lignes(), and zone_VEFPreP1B().
Referenced by calculer_dt_stab().
calculer_flux_bords_aretes()
void Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_aretes (const DoubleVect & inconnue) const protected
Definition at line 1326 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  Cerr<<"Op_Dift_VEF_P1NCP1B_Face::calculer_flux_bords_aretes() not coded"<<finl;
  Cerr<<"Exit"<<finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by ajouter().
calculer_flux_bords_elem()
void Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem (const DoubleVect & inconnue) const protected
Definition at line 1121 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_bords=zone_VEF.nb_front_Cl();
  int face=0;
  int elem=0;
  int n_bord=0,ind_face=0;
  int num1=0,num2=0;
  int compi=0,compj=0;
  double surface=0.;
  double Text=0.;
  double coeff_conv=1.;
  if (alphaS) coeff_conv=convexite_;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi=
            ref_cast(Neumann_paroi,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.face_surfaces(face);
              for (compi=0; compi<dim_ch_; compi++)
                flux_bords_(face,compi)=coeff_conv*
                                        la_cl_paroi.flux_impose(ind_face,compi)*
                                        surface;
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi=
            ref_cast(Echange_externe_impose,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.face_surfaces(face);
              for (compi=0; compi<dim_ch_; compi++)
                {
                  Text=la_cl_paroi.T_ext(ind_face,compi);
                  flux_bords_(face,compi)=coeff_conv*la_cl_paroi.h_imp(ind_face,compi)*surface;
                  flux_bords_(face,compi)*=(Text-inconnue[face*dim_ch_+compi]);
                }
            }
        }
      else if ( sub_type(Neumann_homogene,la_cl.valeur()) ||
                sub_type(Neumann_sortie_libre,la_cl.valeur()) ||
                sub_type(Symetrie,la_cl.valeur())
              )
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              for (compi=0; compi<dim_ch_; compi++)
                flux_bords_(face,compi)=0.;
            }
        }
      else
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              elem=face_voisins(face,0);
              assert(elem!=-1);
// le coefficient de convexite est deja dans gradient_p0_
              for (compi=0; compi<dim_ch_; compi++)
                for (compj=0; compj<dimension; compj++)
                  flux_bords_(face,compi)=gradient_p0_(elem,compi,compj)
                                          *face_normales(face,compj);
            }
        }
    }//fin du for sur n_bord
}
References alphaS, convexite_, dim_ch_, Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_base::flux_bords_, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), gradient_p0_, Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), ref_cast, sub_type, Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and zone_VEFPreP1B().
Referenced by ajouter().
calculer_flux_bords_som()
void Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som (const DoubleVect & inconnue) const protected
Definition at line 1219 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const IntTab& face_sommets=zone_VEF.face_sommets();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const int nb_som_face=zone_VEF.nb_som_face();
  const int nb_bords=zone_VEF.nb_front_Cl();
  int face=0;
  int som=0,som_loc=0;
  int n_bord=0,ind_face=0;
  int num1=0,num2=0;
  int compi=0,compj=0;
  double surface=0.;
  double Text=0.;
  double coeff_conv=1.;
  if (alphaE) coeff_conv=1.-convexite_;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi=
            ref_cast(Neumann_paroi,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.face_surfaces(face);
              for (compi=0; compi<dim_ch_; compi++)
                flux_bords_(face,compi)=coeff_conv*
                                        la_cl_paroi.flux_impose(ind_face,compi)*
                                        surface;
            }
        }
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi=
            ref_cast(Echange_externe_impose,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.face_surfaces(face);
              for (compi=0; compi<dim_ch_; compi++)
                {
                  Text=la_cl_paroi.T_ext(ind_face,compi);
                  flux_bords_(face,compi)=coeff_conv*la_cl_paroi.h_imp(ind_face,compi)*surface;
                  flux_bords_(face,compi)*=(Text-inconnue[face*dim_ch_+compi]);
                }
            }
        }
      else if ( sub_type(Neumann_homogene,la_cl.valeur()) ||
                sub_type(Neumann_sortie_libre,la_cl.valeur()) ||
                sub_type(Symetrie,la_cl.valeur())
              )
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              for (compi=0; compi<dim_ch_; compi++)
                flux_bords_(face,compi)=0.;
            }
        }
      else
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
// le coefficient de convexite est deja dans gradient_p1_
              for (som_loc=0; som_loc<nb_som_face; som_loc++)
                {
                  som=face_sommets(face,som_loc);
                  som=dom.get_renum_som_perio(som);
                  for (compi=0; compi<dim_ch_; compi++)
                    for (compj=0; compj<dimension; compj++)
                      flux_bords_(face,compi)+=gradient_p1_(som,compi,compj)*
                                               face_normales(face,compj);
                }
              for (compi=0; compi<dim_ch_; compi++)
                flux_bords_(face,compi)/=nb_som_face;
            }
        }
    }//fin du for sur n_bord
}
References alphaE, convexite_, dim_ch_, Objet_U::dimension, Zone::domaine(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Operateur_base::flux_bords_, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), gradient_p1_, Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Zone_VF::nb_som_face(), Front_VF::num_face(), ref_cast, sub_type, Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by ajouter().
calculer_gradient_aretes()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::calculer_gradient_aretes (const DoubleVect & inconnue) const protected
Definition at line 716 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  return gradient_pa_;
}
References gradient_pa_.
Referenced by ajouter().
calculer_gradient_elem()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem (const DoubleVect & inconnue) const protected
Definition at line 425 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleVect& volumes = zone_VEF.volumes();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const int nb_faces_elem=zone.nb_faces_elem();
  const int nb_elem_tot=zone.nb_elem_tot();
  int elem=0,face_loc=0,face=0,compi=0,compj=0;
  double signe=0.;
  double volume=0.;
// Valeurs INTEGRALES du gradient_p0_
  for(elem=0; elem<nb_elem_tot; elem++)
    for(face_loc=0; face_loc<nb_faces_elem; face_loc++)
      {
        face=elem_faces(elem,face_loc);
        signe=1;
        if(elem!=face_voisins(face,0)) signe=-1;
        for(compi=0; compi<dim_ch_; compi++)
          for(compj=0; compj<dimension; compj++)
            gradient_p0_(elem,compi,compj)+=signe*
                                            inconnue[face*dim_ch_+compi]*
                                            face_normales(face,compj);
      }
// Valeurs NODALES du gradient_p0_
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      volume = volumes(elem);
      for (compi=0; compi<dim_ch_; compi++)
        for (compj=0; compj<dimension; compj++)
          gradient_p0_(elem,compi,compj)/=(coeff_*volume);
    }
// REMARQUE : cet echange_espace_virtuel() est NECESSAIRE
// dans le cas ou alphaS==1 et/ou alphaA=1
  if (alphaS) gradient_p0_*=convexite_;
  gradient_p0_.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B Gradient P0 : ",gradient_p0_);
  return gradient_p0_;
}
References alphaS, coeff_, convexite_, dim_ch_, Objet_U::dimension, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), gradient_p0_, Zone::nb_elem_tot(), Zone::nb_faces_elem(), Debog::verifier(), Zone_VF::volumes(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by ajouter().
calculer_gradient_som()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som (const DoubleVect & inconnue) const protected
Definition at line 478 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_faces_elem=zone.nb_faces_elem();
  const int nb_som_face=zone_VEF.nb_som_face();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_som=zone_VEF.nb_som();
  const int nb_som_tot=zone_VEF.nb_som_tot();
  const int nb_bords =les_cl.size();
  int elem=0,face_loc=0,som_loc=0,face=0;
  int compi=0,compj=0,som=0,num1=0,num2=0;
  int i=0,ind_face=0;
  int n_bord=0;
  const double coeff_som=1./(dimension)/(dimension+1);
  double signe=0.;
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  DoubleTab secmem(gradient_p1_);
  ArrOfDouble sigma(dimension);
  DoubleVect secmemij;
  DoubleVect gradij;
  dom.creer_tableau_sommets(secmemij);
  dom.creer_tableau_sommets(gradij);
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& face_sommets=zone_VEF.face_sommets();
// Le second membre du systeme a inverser
  secmem=0.;
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      sigma = 0;
      for(face_loc=0; face_loc<nb_faces_elem; face_loc++)
        {
          face = elem_faces(elem,face_loc);
          for(compi=0; compi<dim_ch_; compi++)
            sigma[compi]+=inconnue[face*dim_ch_+compi];
        }
      for(face_loc=0; face_loc<nb_faces_elem; face_loc++)
        {
          som = dom.get_renum_som_perio(som_elem(elem,face_loc));
          face = elem_faces(elem,face_loc);
          signe=1;
          if(elem!=face_voisins(face,0)) signe=-1;
          for(compi=0; compi<dim_ch_; compi++)
            for(compj=0; compj<dimension; compj++)
              secmem(som,compi,compj)+=coeff_som*signe*
                                       sigma[compi]*face_normales(face,compj);
        }
    }
  secmem.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B secmem, avant CL : ", secmem);
// Les conditions aux limites pour le second membre
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
      if (sub_type(Dirichlet_homogene,la_cl.valeur()))
        {
// On ne fait rien et c'est normal
        }
      else if (sub_type(Dirichlet,la_cl.valeur()))
        {
          const Dirichlet& dirichlet =
            ref_cast(Dirichlet,la_cl.valeur());
          double x=0.,y=0.,z=0.;
          double inconnue_pt=0.;
          double temps = equation().schema_temps().temps_courant();
          const DoubleTab& coord_sommets = dom.coord_sommets();
          if (sub_type(Champ_front_txyz,dirichlet.champ_front().valeur()))
            {
              const Champ_front_txyz& champ_front =
                ref_cast(Champ_front_txyz,dirichlet.champ_front().valeur());
              for (ind_face=num1; ind_face<num2; ind_face++)
                {
                  face=le_bord.num_face(ind_face);
                  for(som_loc=0; som_loc<nb_som_face; som_loc++)
                    {
                      som=dom.get_renum_som_perio(face_sommets(face,som_loc));
// Formule d'integration numerique exacte pour les polynomes de degre 2
                      if (dimension==2) //formule de Simpson
{
// Coordonnees du sommet "som"
                          x=coord_sommets(som,0);
                          y=coord_sommets(som,1);
// Valeur de l'inconnue au point d'integration
                          for (compi=0; compi<dim_ch_; compi++)
{
                              inconnue_pt=
                                champ_front.valeur_au_temps_et_au_point(temps,som,x,y,z,compi);
                              for (compj=0; compj<dimension; compj++)
                                secmem(som,compi,compj) +=
                                  1./6*(2*inconnue[face*dim_ch_+compi]+inconnue_pt)
                                  *face_normales(face,compj) ;
                            }
                        }//fin du if sur dimension==2
                      else //formule exacte pour les polynomes de degre 2
{
// On suppose que l'element considere est un TETRAEDRE
                          for (i=1; i<3; i++)
{
                              int som2=face_sommets(face,(som_loc+i)%nb_som_face);
                              som2=dom.get_renum_som_perio(som2);
// Coordonnees des points d'integration
                              x=(coord_sommets(som,0)+coord_sommets(som2,0))/2.;
                              y=(coord_sommets(som,1)+coord_sommets(som2,1))/2.;
                              z=(coord_sommets(som,2)+coord_sommets(som2,2))/2.;
// Vitesse au point d'integration
                              for (compi=0; compi<dim_ch_; compi++)
{
                                  inconnue_pt=
                                    champ_front.valeur_au_temps_et_au_point(temps,som,x,y,z,compi);
                                  for (compj=0; compj<dimension; compj++)
                                    secmem(som, compi, compj) += 1./dimension*
                                                                 1/2.*inconnue_pt*face_normales(face,compj) ;
                                }
                            }
                        }//fin du else sur la dimension
                    }//fin du for sur "som_loc"
                }//fin du for sur "ind_face"
            }//fin du if sur "Champ_front_txyz"
          else
            {
              for (ind_face=num1; ind_face<num2; ind_face++)
                {
                  face = le_bord.num_face(ind_face);
                  for(som_loc=0; som_loc<nb_som_face; som_loc++)
                    {
                      som=dom.get_renum_som_perio(face_sommets(face,som_loc));
                      for (compi=0; compi<dim_ch_; compi++)
                        for (compj=0; compj<dimension; compj++)
                          secmem(som,compi,compj) += 1./dimension*
                                                     inconnue[face*dim_ch_+compi]*face_normales(face,compj) ;
                    }//fin du for sur "som_loc"
                }//fin du for sur "ind_face"
            }
        }//fin du if sur "Dirichlet"
      else if (!sub_type(Periodique,la_cl.valeur()))
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              for(som_loc=0; som_loc<nb_som_face; som_loc++)
                {
                  som=dom.get_renum_som_perio(face_sommets(face,som_loc));
                  for (compi=0; compi<dim_ch_; compi++)
                    for (compj=0; compj<dimension; compj++)
                      secmem(som,compi,compj) += 1./dimension*
                                                 inconnue[face*dim_ch_+compi]*face_normales(face,compj) ;
                }//fin du for sur "som_loc"
            }//fin du for sur "ind_face"
        }//fin du if sur "!Periodique"
    }//fin du for sur "n_bord"
  secmem.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B secmem, apres CL : ", secmem);
// Calcul de la solution du systeme a inverser
  for (compi=0; compi<dim_ch_; compi++)
    for (compj=0; compj<dimension; compj++)
      {
        for(i=0; i<nb_som_tot; i++)
          {
            som=dom.get_renum_som_perio(i);
            secmemij(som)=secmem(som,compi,compj);
          }
// Resolution du systeme
        for(i=0; i<nb_som; i++)
          {
            som=dom.get_renum_som_perio(i);
            gradij(som)=secmemij(som)/(coeff_*volume_aux_sommets(som));
          }
        for(i=0; i<nb_som_tot; i++)
          {
            som=dom.get_renum_som_perio(i);
            gradient_p1_(som,compi,compj)
              =gradij(som);
          }
      }
  gradient_p1_.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B Gradient P1 : ",gradient_p1_);
  return gradient_p1_;
}
References Cond_lim_base::champ_front(), coeff_, Domaine::coord_sommets(), Domaine::creer_tableau_sommets(), dim_ch_, Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), gradient_p1_, Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VEF_PreP1b::nb_som(), Zone_VF::nb_som_face(), Zone_dis_base::nb_som_tot(), Front_VF::num_face(), ref_cast, Equation_base::schema_temps(), vect_impl::size(), sub_type, Schema_Temps_base::temps_courant(), Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Champ_front_txyz::valeur_au_temps_et_au_point(), Debog::verifier(), Zone_VEF_PreP1b::volume_aux_sommets(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by ajouter(), and test().
calculer_laplacien_som()
void Op_Diff_VEFP1NCP1B_Face::calculer_laplacien_som (const DoubleTab & nu_som) const protected
Definition at line 967 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Champ_base& diffu=diffusivite();
  bool testl=false;
  testl|=sub_type(Champ_Don_Fonc_xyz,diffu);
  testl|=sub_type(Champ_Don_lu,diffu);
  testl|=sub_type(Champ_Uniforme,diffu);
  testl|=sub_type(Champ_Uniforme_Morceaux,diffu);
  testl|=sub_type(Champ_Fonc_base,diffu);
  is_laplacian_filled_=testl;
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  DoubleVect& coeff=laplacien_p1_.get_set_coeff();
  const DoubleTab& inconnue1=equation().inconnue().valeurs();
  const DoubleVect& porosite_face=zone_VEF.porosite_face();
  assert(laplacien_p1_.nb_lignes()>2);
  coeff=0.;
  ajouter_contribution_som(inconnue1,porosite_face,nu_som,laplacien_p1_);
  coeff*=-1;//pour l'explicite
}
References ajouter_contribution_som(), coeff, Op_Diff_VEF_Face::diffusivite(), MorEqn::equation(), Matrice_Morse::get_set_coeff(), Equation_base::inconnue(), is_laplacian_filled_, laplacien_p1_, Matrice_Morse::nb_lignes(), Zone_VF::porosite_face(), sub_type, Champ_Inc::valeurs(), and zone_VEFPreP1B().
Referenced by calculer_dt_stab_som().
coeff_matrice_som()
void Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som (const int face, IntVect & liste_som, DoubleTab & gradient0, DoubleTab & gradient1, const DoubleVect & porosite_face, const DoubleTab & nu_som, const DoubleTab & coeff_perio, Matrice_Morse & matrice) const protected
Definition at line 1624 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const ArrOfInt& tab1=matrice.get_tab1();
  const ArrOfInt& tab2=matrice.get_tab2();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const int nb_faces=zone_VEF.nb_faces();
  int face_C=0;
  int face2=0,face2_C=0;
  int som_loc=0,som=0;
  int som_loc0=0,som_loc1=0;
  int debut=0,size=0;
  int compi=0,compj=0;
  int elem0=0,elem1=0;
  int i=0;
  int nnz=0;
  double coeff_som=0.,coeff_mat=0.;
  double coeff_diff=0.;
  double psc=0.;
  double delta=decentrage_;
  double coeff_conv=1.;
  if (alphaE) coeff_conv=(1.-convexite_);
// Quelques verifications
  assert(gradient0.nb_dim()==2);
  assert(gradient0.dimension(0)==dimension);
  assert(gradient0.dimension(1)==dimension+2);
  assert(gradient1.nb_dim()==1);
  assert(gradient1.dimension(0)==dimension);
  assert(liste_som.size()==dimension+2);
//
// Partie P1 du laplacien discret
//
  liste_som=-1;
  gradient0=0.;
  gradient_som(face,nnz,liste_som,gradient0);
  /* gradient associe a "face" : calcul du coefficient */
  /* diagonal de la matrice associee a l'inconnue */
  coeff_mat=0.;
  for (som_loc=0; som_loc<nnz; som_loc++)
    {
      som=liste_som(som_loc);
      coeff_som=volume_aux_sommets(som)*coeff_;
      psc=0.;
      for (compj=0; compj<dimension; compj++)
        psc+=gradient0(compj,som_loc)
             *gradient0(compj,som_loc);
      psc*=coeff_som;
      psc*=nu_som(som);
      coeff_mat+=psc;
    }
  coeff_mat*=coeff_conv;
  for (compi=0; compi<dim_ch_; compi++)
    {
      face_C=face*dim_ch_+compi;
      matrice(face_C,face_C)+=coeff_mat;
    }
  /* calcul des coefficients extra-diagonaux de la matrice laplacien */
  /* la matrice etant diagonale par bloc, on effectue le calcul du */
  /* produit scalaire une seule fois avant de l'affecter aux differentes */
  /* composantes de la matrice */
  face_C=face*dim_ch_;
  debut=tab1[face_C]-1;
  size=tab1[face_C+1]-tab1[face_C];
  for (i=1; i<size; i++) //i=0 -> face2_C=face_C -> deja rempli
    {
      face2_C=tab2[debut+i]-1;
      face2=face2_C/dim_ch_;//division euclidienne
      if (face2>face)//pour la symetrie de l'operateur
        {
          coeff_mat=0.;
          for (som_loc=0; som_loc<nnz; som_loc++)
            {
              som=liste_som(som_loc);
              coeff_som=volume_aux_sommets(som)*coeff_;
              isInStencil(face2,som,elem0,som_loc0,elem1,som_loc1);
              if (elem0!=-1)//les deux faces se "voient"
                {
                  assert(som_loc0!=-1);
                  gradient1=0.;
                  gradient_som(face2,som,elem0,som_loc0,elem1,som_loc1,gradient1);
                  psc=0.;
                  for (compj=0; compj<dimension; compj++)
                    psc+=gradient0(compj,som_loc)
                         *gradient1(compj);
                  psc*=coeff_som;
                  psc*=nu_som(som);
                  coeff_mat+=psc;
                }
            }
          coeff_mat*=coeff_conv;
          coeff_diff=-1.*delta*maximum(0.,coeff_mat);
          coeff_mat+=coeff_diff;
          for (compi=0; compi<dim_ch_; compi++)
            {
              face_C=face*dim_ch_+compi;
              face2_C=face2*dim_ch_+compi;
              matrice(face_C,face2_C)+=coeff_mat*coeff_perio(face2);
              matrice(face_C,face_C)-=coeff_diff*coeff_perio(face2);
              if (face2<nb_faces)
                {
                  matrice(face2_C,face_C)+=coeff_mat;
                  matrice(face2_C,face2_C)-=coeff_diff;
                }
            }
        }
    }
}
References alphaE, coeff_, convexite_, decentrage_, dim_ch_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), gradient_som(), isInStencil(), maximum(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_VF::nb_faces(), TRUSTVect< _TYPE_ >::size(), Zone_VEF_PreP1b::volume_aux_sommets(), and zone_VEFPreP1B().
Referenced by ajouter_contribution_som().
coeff_matrice_som_CL()
void Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL (const int face, IntVect & liste_som, DoubleTab & gradient0, DoubleTab & gradient1, const DoubleVect & porosite_face, const DoubleTab & nu_som, const DoubleTab & coeff_perio, Matrice_Morse & matrice) const protected
Definition at line 1761 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const ArrOfInt& tab1=matrice.get_tab1();
  const ArrOfInt& tab2=matrice.get_tab2();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const int nb_faces=zone_VEF.nb_faces();
  int face_C=0;
  int face2=0,face2_C=0;
  int som_loc=0,som=0;
  int som_loc0=0,som_loc1=0;
  int debut=0,size=0;
  int compi=0,compj=0;
  int elem0=0,elem1=0;
  int i=0;
  int nnz=0;
  double coeff_som=0.,coeff_mat=0.;
  double coeff_diff=0.;
  double psc=0.;
  double delta=decentrage_;
  double coeff_conv=1.;
  if (alphaE) coeff_conv=(1.-convexite_);
// Quelques verifications
  assert(gradient0.nb_dim()==2);
  assert(gradient0.dimension(0)==dimension);
  assert(gradient0.dimension(1)==dimension+2);
  assert(gradient1.nb_dim()==1);
  assert(gradient1.dimension(0)==dimension);
  assert(liste_som.size()==dimension+2);
//
// Partie P1 du laplacien discret
//
  liste_som=-1;
  gradient0=0.;
  gradient_som_CL(face,nnz,liste_som,gradient0);
  /* gradient associe a "face" : calcul du coefficient */
  /* diagonal de la matrice associee a l'inconnue */
  coeff_mat=0.;
  for (som_loc=0; som_loc<nnz; som_loc++)
    {
      som=liste_som(som_loc);
      coeff_som=volume_aux_sommets(som)*coeff_;
      psc=0.;
      for (compj=0; compj<dimension; compj++)
        psc+=gradient0(compj,som_loc)
             *gradient0(compj,som_loc);
      psc*=coeff_som;
      psc*=nu_som(som);
      coeff_mat+=psc;
    }
  coeff_mat*=coeff_conv;
  for (compi=0; compi<dim_ch_; compi++)
    {
      face_C=face*dim_ch_+compi;
      matrice(face_C,face_C)+=coeff_mat;
    }
  /* calcul des coefficients extra-diagonaux de la matrice laplacien */
  /* la matrice etant diagonale par bloc, on effectue le calcul du */
  /* produit scalaire une seule fois avant de l'affecter aux differentes */
  /* composantes de la matrice */
  face_C=face*dim_ch_;
  debut=tab1[face_C]-1;
  size=tab1[face_C+1]-tab1[face_C];
  for (i=1; i<size; i++) //i=0 -> face2_C=face_C -> deja rempli
    {
      face2_C=tab2[debut+i]-1;
      face2=face2_C/dim_ch_;//division euclidienne
      if (face2>face)//pour la symetrie de l'operateur
        {
          coeff_mat=0.;
          for (som_loc=0; som_loc<nnz; som_loc++)
            {
              som=liste_som(som_loc);
              coeff_som=volume_aux_sommets(som)*coeff_;
              isInStencil(face2,som,elem0,som_loc0,elem1,som_loc1);
              if (elem0!=-1)//les deux faces se "voient"
                {
                  assert(som_loc0!=-1);
                  gradient1=0.;
                  gradient_som(face2,som,elem0,som_loc0,elem1,som_loc1,gradient1);
                  psc=0.;
                  for (compj=0; compj<dimension; compj++)
                    psc+=gradient0(compj,som_loc)
                         *gradient1(compj);
                  psc*=coeff_som;
                  psc*=nu_som(som);
                  coeff_mat+=psc;
                }
            }
          coeff_mat*=coeff_conv;
          coeff_diff=-1.*delta*maximum(0.,coeff_mat);
          coeff_mat+=coeff_diff;
          for (compi=0; compi<dim_ch_; compi++)
            {
              face_C=face*dim_ch_+compi;
              face2_C=face2*dim_ch_+compi;
              matrice(face_C,face2_C)+=coeff_mat*coeff_perio(face2);
              matrice(face_C,face_C)-=coeff_diff*coeff_perio(face2);
              if (face2<nb_faces)
                {
                  matrice(face2_C,face_C)+=coeff_mat;
                  matrice(face2_C,face2_C)-=coeff_diff;
                }
            }
        }
    }
}
References alphaE, coeff_, convexite_, decentrage_, dim_ch_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), gradient_som(), gradient_som_CL(), isInStencil(), maximum(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_VF::nb_faces(), TRUSTVect< _TYPE_ >::size(), Zone_VEF_PreP1b::volume_aux_sommets(), and zone_VEFPreP1B().
Referenced by ajouter_contribution_som().
coeff_matrice_som_perio()
void Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio (const int face, const int faceAss, IntVect & liste_som, DoubleTab & gradient0, DoubleTab & gradient1, const DoubleVect & porosite_face, const DoubleTab & nu_som, const DoubleTab & coeff_perio, Matrice_Morse & matrice) const protected
Definition at line 2039 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const ArrOfInt& tab1=matrice.get_tab1();
  const ArrOfInt& tab2=matrice.get_tab2();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const int nb_faces=zone_VEF.nb_faces();
  int face_C=0;
  int face2=0,face2_C=0;
  int som_loc=0,som=0;
  int som_loc0=0,som_loc1=0;
  int debut=0,size=0;
  int compi=0,compj=0;
  int elem0=0,elem1=0;
  int i=0;
  int nnz=0;
  double coeff_som=0.,coeff_mat=0.;
  double coeff_diff=0.;
  double psc=0.;
  double delta=decentrage_;
  double coeff_conv=1.;
  if (alphaE) coeff_conv=(1.-convexite_);
// Quelques verifications
  assert(gradient0.nb_dim()==2);
  assert(gradient0.dimension(0)==dimension);
  assert(gradient0.dimension(1)==dimension+2);
  assert(gradient1.nb_dim()==1);
  assert(gradient1.dimension(0)==dimension);
  assert(liste_som.size()==dimension+2);
//
// Partie P1 du laplacien discret
//
  liste_som=-1;
  gradient0=0.;
  gradient_som(face,nnz,liste_som,gradient0);
  /* gradient associe a "face" : calcul du coefficient */
  /* diagonal de la matrice associee a l'inconnue */
  coeff_mat=0.;
  for (som_loc=0; som_loc<nnz; som_loc++)
    {
      som=liste_som(som_loc);
      coeff_som=volume_aux_sommets(som)*coeff_;
      psc=0.;
      for (compj=0; compj<dimension; compj++)
        psc+=gradient0(compj,som_loc)
             *gradient0(compj,som_loc);
      psc*=coeff_som;
      psc*=nu_som(som);
      coeff_mat+=psc;
    }
  coeff_mat*=coeff_conv;
  for (compi=0; compi<dim_ch_; compi++)
    {
      face_C=face*dim_ch_+compi;
      matrice(face_C,face_C)+=coeff_mat;
    }
  /* calcul des coefficients extra-diagonaux de la matrice laplacien */
  /* la matrice etant diagonale par bloc, on effectue le calcul du */
  /* produit scalaire une seule fois avant de l'affecter aux differentes */
  /* composantes de la matrice */
  face_C=face*dim_ch_;
  debut=tab1[face_C]-1;
  size=tab1[face_C+1]-tab1[face_C];
  for (i=1; i<size; i++) //i=0 -> face2_C=face_C -> deja rempli
    {
      face2_C=tab2[debut+i]-1;
      face2=face2_C/dim_ch_;//division euclidienne
      if (face2>face)//pour la symetrie de l'operateur
        {
          coeff_mat=0.;
          for (som_loc=0; som_loc<nnz; som_loc++)
            {
              som=liste_som(som_loc);
              coeff_som=volume_aux_sommets(som)*coeff_;
              isInStencil(face2,som,elem0,som_loc0,elem1,som_loc1);
              if (elem0!=-1)//les deux faces se "voient"
                {
                  assert(som_loc0!=-1);
                  gradient1=0.;
                  gradient_som(face2,som,elem0,som_loc0,elem1,som_loc1,gradient1);
                  psc=0.;
                  for (compj=0; compj<dimension; compj++)
                    psc+=gradient0(compj,som_loc)
                         *gradient1(compj);
                  psc*=coeff_som;
                  psc*=nu_som(som);
                  coeff_mat+=psc;
                }
            }
          coeff_mat*=coeff_conv;
          coeff_diff=-1.*delta*maximum(0.,coeff_mat);
          coeff_mat+=coeff_diff;
          for (compi=0; compi<dim_ch_; compi++)
            {
              face_C=face*dim_ch_+compi;
              face2_C=face2*dim_ch_+compi;
              matrice(face_C,face2_C)+=coeff_mat*coeff_perio(face2);
              matrice(face_C,face_C)-=coeff_diff*coeff_perio(face2);
              if (face2<nb_faces)
                {
                  matrice(face2_C,face_C)+=coeff_mat*coeff_perio(face);
                  matrice(face2_C,face2_C)-=coeff_diff*coeff_perio(face);
                }
            }
        }
    }
}
References alphaE, coeff_, convexite_, decentrage_, dim_ch_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), gradient_som(), isInStencil(), maximum(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_VF::nb_faces(), TRUSTVect< _TYPE_ >::size(), Zone_VEF_PreP1b::volume_aux_sommets(), and zone_VEFPreP1B().
Referenced by ajouter_contribution_som().
coeff_matrice_som_symetrie()
void Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie (const int face, IntVect & liste_som, DoubleTab & gradient0, DoubleTab & gradient1, const DoubleVect & porosite_face, const DoubleTab & nu_som, const DoubleTab & coeff_perio, Matrice_Morse & matrice) const protected
Definition at line 1898 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const ArrOfInt& tab1=matrice.get_tab1();
  const ArrOfInt& tab2=matrice.get_tab2();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const int nb_faces=zone_VEF.nb_faces();
  int face_C=0;
  int face2=0,face2_C=0;
  int som_loc=0,som=0;
  int som_loc0=0,som_loc1=0;
  int debut=0,size=0;
  int compi=0,compj=0;
  int elem0=0,elem1=0;
  int i=0;
  int nnz=0;
  double coeff_som=0.,coeff_mat=0.;
  double coeff_diff=0.;
  double psc=0.;
  double delta=decentrage_;
  double coeff_conv=1.;
  if (alphaE) coeff_conv=(1.-convexite_);
// Quelques verifications
  assert(gradient0.nb_dim()==2);
  assert(gradient0.dimension(0)==dimension);
  assert(gradient0.dimension(1)==dimension+2);
  assert(gradient1.nb_dim()==1);
  assert(gradient1.dimension(0)==dimension);
  assert(liste_som.size()==dimension+2);
//
// Partie P1 du laplacien discret
//
  liste_som=-1;
  gradient0=0.;
  gradient_som_CL(face,nnz,liste_som,gradient0);
  /* gradient associe a "face" : calcul du coefficient */
  /* diagonal de la matrice associee a l'inconnue */
  coeff_mat=0.;
  for (som_loc=0; som_loc<nnz; som_loc++)
    {
      som=liste_som(som_loc);
      coeff_som=volume_aux_sommets(som)*coeff_;
      psc=0.;
      for (compj=0; compj<dimension; compj++)
        psc+=gradient0(compj,som_loc)
             *gradient0(compj,som_loc);
      psc*=coeff_som;
      psc*=nu_som(som);
      coeff_mat+=psc;
    }
  coeff_mat*=coeff_conv;
  for (compi=0; compi<dim_ch_; compi++)
    {
      face_C=face*dim_ch_+compi;
      matrice(face_C,face_C)+=coeff_mat;
    }
  /* calcul des coefficients extra-diagonaux de la matrice laplacien */
  /* la matrice etant diagonale par bloc, on effectue le calcul du */
  /* produit scalaire une seule fois avant de l'affecter aux differentes */
  /* composantes de la matrice */
  /* REMARQUE : la matrice est modifiee pour tenir compte des CL de */
  /* symetrie, mais on ne calcule pas les modifications associees -> */
  /* c'est la fonction Op_VEF_Face::modifier_pour_Cl() qui le fera */
  face_C=face*dim_ch_;
  debut=tab1[face_C]-1;
  size=tab1[face_C+1]-tab1[face_C];
  size-=(dim_ch_-1);//-> pour ne pas calculer les coefficients inutiles
  for (i=1; i<size; i++) //i=0 -> face2_C=face_C -> deja rempli
    {
      face2_C=tab2[debut+i]-1;
      face2=face2_C/dim_ch_;//division euclidienne
      if (face2>face)//pour la symetrie de l'operateur
        {
          coeff_mat=0.;
          for (som_loc=0; som_loc<nnz; som_loc++)
            {
              som=liste_som(som_loc);
              coeff_som=volume_aux_sommets(som)*coeff_;
              isInStencil(face2,som,elem0,som_loc0,elem1,som_loc1);
              if (elem0!=-1)//les deux faces se "voient"
                {
                  assert(som_loc0!=-1);
                  gradient1=0.;
                  gradient_som(face2,som,elem0,som_loc0,elem1,som_loc1,gradient1);
                  psc=0.;
                  for (compj=0; compj<dimension; compj++)
                    psc+=gradient0(compj,som_loc)
                         *gradient1(compj);
                  psc*=coeff_som;
                  psc*=nu_som(som);
                  coeff_mat+=psc;
                }
            }
          coeff_mat*=coeff_conv;
          coeff_diff=-1.*delta*maximum(0.,coeff_mat);
          coeff_mat+=coeff_diff;
          for (compi=0; compi<dim_ch_; compi++)
            {
              face_C=face*dim_ch_+compi;
              face2_C=face2*dim_ch_+compi;
              matrice(face_C,face2_C)+=coeff_mat*coeff_perio(face2);
              matrice(face_C,face_C)-=coeff_diff*coeff_perio(face2);
              if (face2<nb_faces)
                {
                  matrice(face2_C,face_C)+=coeff_mat;
                  matrice(face2_C,face2_C)-=coeff_diff;
                }
            }
        }
    }
}
References alphaE, coeff_, convexite_, decentrage_, dim_ch_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), gradient_som(), gradient_som_CL(), isInStencil(), maximum(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_VF::nb_faces(), TRUSTVect< _TYPE_ >::size(), Zone_VEF_PreP1b::volume_aux_sommets(), and zone_VEFPreP1B().
Referenced by ajouter_contribution_som().
completer()
void Op_Diff_VEFP1NCP1B_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 222 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  Op_Diff_VEF_Face::completer();
  initialiser();
}
References Op_Diff_VEF_Face::completer(), and initialiser().
contribuer_a_avec()
void Op_Diff_VEFP1NCP1B_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 143 of file Op_Diff_VEFP1NCP1B_Face.h.
{
  ajouter_contribution(inco, matrice);
}
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Diff_VEFP1NCP1B_Face::contribuer_au_second_membre (DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 152 of file Op_Diff_VEFP1NCP1B_Face.h.
{
  contribue_au_second_membre(resu);
}
References Op_Diff_VEF_Face::contribue_au_second_membre().
corriger_Cl_test()
void Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test (DoubleTab & resu) const protected
Definition at line 3901 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_bords =les_cl.size();
  int n_bord=0, num1=0, num2=0;
  int face=0, face_associee=0;
  int ind_face=0, comp=0;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              face_associee=
                le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (face<face_associee)
                for (comp=0; comp<dim_ch_; comp++)
                  {
                    resu[face*dim_ch_+comp]+=resu[face_associee*dim_ch_+comp];
                    resu[face_associee*dim_ch_+comp]=resu[face*dim_ch_+comp];
                  }
            }
        }
    }
  resu.echange_espace_virtuel();
}
References dim_ch_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Periodique::face_associee(), face_associee, Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), and Ref_Zone_Cl_VEF::valeur().
Referenced by test().
corriger_div_pour_Cl()
DoubleVect & Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl (const DoubleVect & inconnue, const DoubleTab & nu, DoubleVect & div) const protected
Definition at line 723 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
#ifndef NDEBUG
  const IntTab& face_voisins=zone_VEF.face_voisins();
#endif
  const int nb_bords =les_cl.size();
  int n_bord=0, num1=0, num2=0;
  int face=0, face_asso_loc=0, face_associee=0;
  int ind_face=0, comp=0;
  double flux=0.;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// Reinitialisation de num1 et num2
      num1 = 0;
      num2 = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
// periodicite
          const Periodique& la_cl_perio = ref_cast(Periodique, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              face_asso_loc=la_cl_perio.face_associee(ind_face);
              face_associee=le_bord.num_face(face_asso_loc);
              if (face<face_associee)
                for (comp=0; comp<dim_ch_; comp++)
                  {
                    div[face*dim_ch_+comp]+=div[face_associee*dim_ch_+comp];
                    div[face_associee*dim_ch_+comp]=div[face*dim_ch_+comp];
                  }
            }//fin du if sur for "ind_face"
        }//fin de la periodicite
      else if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi =
            ref_cast(Neumann_paroi, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              assert(face_voisins(face,0)!=-1);
              for (comp=0; comp<dim_ch_; comp++)
                {
                  flux=la_cl_paroi.flux_impose(ind_face,comp)
                       *zone_VEF.surface(face);
                  div[face*dim_ch_+comp]+=flux;
                }
            }
        }//fin if sur "Neumann"
      else if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi=
            ref_cast(Echange_externe_impose, la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              for (comp=0; comp<dim_ch_; comp++)
                {
                  flux=la_cl_paroi.h_imp(ind_face,comp)
                       *zone_VEF.surface(face);
                  flux*=(la_cl_paroi.T_ext(ind_face,comp)-inconnue[face*dim_ch_+comp]);
                  div[face*dim_ch_+comp]+=flux;
                }
            }
        }
    }//fin du for sur "n_bords"
  div.echange_espace_virtuel();
  Debog::verifier("OpDifP1NCP1B divergence apres CL : ", div);
  return div;
}
References dim_ch_, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Periodique::face_associee(), face_associee, Zone_VF::face_voisins(), Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Debog::verifier(), and zone_VEFPreP1B().
Referenced by ajouter().
corriger_pour_diffusivite()
DoubleTab & Op_Diff_VEFP1NCP1B_Face::corriger_pour_diffusivite (const DoubleTab & nu, DoubleTab & grad) const protected
Definition at line 1084 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  tab_multiply_any_shape(grad, nu);
  return grad;
}
References tab_multiply_any_shape().
Referenced by ajouter().
cree_instance()
Objet_U * Op_Diff_VEFP1NCP1B_Face::cree_instance () static
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
dimensionner()
void Op_Diff_VEFP1NCP1B_Face::dimensionner (Matrice_Morse & mat) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 3008 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_comp = inconnue_.valeur().valeurs().line_size();
  int face=0;
  int i=0,size=0;
  int comp=0,nnz=0,debut=0,face_f77=0,face_C=0;
  int nb_faces_of_symetry=0;
  int next=0;
  ArrOfBit is_symetry(nb_faces_tot);
  IntVect& tab1 = matrice.get_set_tab1();
  IntVect& tab2 = matrice.get_set_tab2();
  IntLists faces_faces;
  if (alphaE && !alphaS && !alphaA)
    Op_VEF_Face::dimensionner(la_zone_vef.valeur(), la_zcl_vef.valeur(), matrice);
  if (alphaS)
    {
// Calcul de la liste des faces
      liste_face(faces_faces,nnz);
      isFaceOfSymetry(is_symetry,nb_faces_of_symetry);
// Dimensionnement des tableaux de la matrice
// REMARQUE : par essence, ce dimensionnement sera toujours plus GRAND
// que le dimensionnement par defaut issu de OP_VEF_FACE
// REMARQUE : pour tenir compte des contraintes dues aux faces de
// symetrie, le dimensionnement de la matrice doit etre legerement
// elargie
      size=nnz*nb_comp;//dimensionnement sans face de symetrie
// size+=nb_faces_of_symetry*(nb_comp-1)*nb_comp;//dimensionnement avec faces de symetrie
// pour chaque face de symetrie pour chaque composante on ajoute nb_comp coeffs pour chaque face liee
      for (face=0; face<nb_faces_tot; face++)
        if (is_symetry[face])
          {
            int nb_v=faces_faces[face].size();
            size+=nb_v*(nb_comp-1)*nb_comp;
          }
      matrice.dimensionner(nb_faces_tot*nb_comp,size);
// Initialisation des grandeurs connues pour tab1
      tab1[nb_faces_tot*nb_comp]=size+1;
      tab1[0]=1;
// Remplissage de tab1
      /* pour les autres composantes de la face 0 */
      size=faces_faces[0].size();
      if (is_symetry[0]) size*=(nb_comp);
      for (comp=1; comp<nb_comp; comp++)
        {
          face_C=comp;
          tab1[face_C]=tab1[face_C-1]+size;
        }
      /* pour les autres faces */
      for (face=1; face<nb_faces_tot; face++)
        {
          size=faces_faces[face-1].size();
          if (is_symetry[face-1]) size*=(nb_comp);
          for (comp=0; comp<nb_comp; comp++)
            {
              face_C=face*nb_comp+comp;
              tab1[face_C]=tab1[face_C-1]+size;
              size=faces_faces[face].size();
              if (is_symetry[face]) size*=(nb_comp);
            }
        }
// Remplissage de tab2
      for (face=0; face<nb_faces_tot; face++)
        {
          size=faces_faces[face].size();
          for (comp=0; comp<nb_comp; comp++)
            {
              debut=tab1[face*nb_comp+comp]-1;
              for (i=0; i<size; i++)
                {
                  face_C=faces_faces[face][i]*nb_comp+comp;
                  face_f77=face_C+1;
                  tab2[debut+i]=face_f77;
                }//fin du for sur "i"
            }//fin du for sur "comp"
        }//fin du for sur "face"
      for (face=0; face<nb_faces_tot; face++)
        if (is_symetry[face])
          {
            size=faces_faces[face].size();
            for (comp=0; comp<nb_comp; comp++)
              {
                debut=tab1[face*nb_comp+comp]-1;
                debut+=size;
                for (int voi=0; voi<size; voi++)
                  {
                    int face2=faces_faces[face][voi];
                    for (i=0; i<nb_comp-1; i++)
                      {
// reste de la division euclidienne
                        next=(comp+i+1)%nb_comp;
                        face_C=face2*nb_comp+next;
                        face_f77=face_C+1;
                        tab2[debut+i]=face_f77;
// Cerr <<face*nb_comp+comp<<" face "<<face << " comp "<< comp<< " face2 "<< face2 << " comp "<<next <<" jface2 "<< face_C<<finl;
                        assert(debut+i<tab1[face*nb_comp+comp+1]-1);
                      }
                    debut+=nb_comp-1;
                  }
              }//fin du for sur "comp"
          }//fin du for sur "face"
    }//fin du if sur "alphaS"
  if (alphaA)
    {
      Cerr << "Erreur Op_Dift_VEFP1NCP1B_Face::dimensionner(Matrice_Morse&)" << finl;
      Cerr << "Le dimensionnement de la matrice implicite avec l'option alphaA"
           << " n'est pas encore codee" << finl;
      Cerr << "Sortie du programme" << finl;
      exit();
    }
}
References alphaA, alphaE, alphaS, Cerr, Op_VEF_Face::dimensionner(), Matrice_Morse::dimensionner(), Process::exit(), finl, Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Op_Diff_VEF_base::inconnue_, isFaceOfSymetry(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), liste_face(), Zone_VF::nb_faces_tot(), next(), TRUSTLists< _TYPE_ >::size(), Ref_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc_base::valeurs(), and zone_VEFPreP1B().
Referenced by calculer_dt_stab_som(), and test().
duplique()
int Op_Diff_VEFP1NCP1B_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_VEFP1NCP1B_Face_Var.
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
get_info()
const Type_info * Op_Diff_VEFP1NCP1B_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face_Var.
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
gradient_som() [1/2]
void Op_Diff_VEFP1NCP1B_Face::gradient_som (const int face, const int som_glob, const int elem0, const int som_loc0, const int elem1, const int som_loc1, DoubleTab & grad) const protected
Definition at line 2632 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const double coeff=1./dimension;
  const double coeff_som=coeff/(dimension+1);
  int face_opp=0,compj=0;
  int elem=0;
  double signe=0.;
  assert(grad.nb_dim()==1);
//
// Calcul du gradient
//
  /* On regarde le premier element voisin */
  assert(elem0!=-1);
  assert(som_loc0!=-1);
// Calcul du gradient local
  face_opp = elem_faces(elem0,som_loc0);
  signe=1.;
  if(elem0!=face_voisins(face_opp,0)) signe=-1.;
  for(compj=0; compj<dimension; compj++)
    grad(compj)=coeff_som*signe*
                face_normales(face_opp,compj);
  /* On regarde le deuxieme element voisin */
  if (elem1==-1)
    {
      /* Plusieurs possibilite :
         - "face" est interne reel
         - "face" est interne virtuel
         - "face" est de bord reel
         - "face" est de bord virtuel
         - "face" une face de joint */
      assert(som_loc1==-1);
      elem=face_voisins(face,1);
      assert(face_voisins(face,0)!=-1);
      /* "face" est de bord */
      if (elem==-1 && face_opp!=face)
        for (compj=0; compj<dimension; compj++)
          grad(compj)+=coeff*face_normales(face,compj) ;
    }
  else
    {
      assert(som_loc1!=-1);
      face_opp=elem_faces(elem1,som_loc1);
      signe=1.;
      if(elem1!=face_voisins(face_opp,0)) signe=-1.;
// Calcul du gradient local
      for(compj=0; compj<dimension; compj++)
        grad(compj)+=coeff_som*signe*
                     face_normales(face_opp,compj);
    }
  grad/=(coeff_*volume_aux_sommets(som_glob));
}
References coeff, coeff_, Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_VEF_PreP1b::volume_aux_sommets(), and zone_VEFPreP1B().
Referenced by coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), and test().
gradient_som() [2/2]
void Op_Diff_VEFP1NCP1B_Face::gradient_som (const int face, int & nnz, IntVect & som_glob, DoubleTab & grad) const protected
Definition at line 2718 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& elem_som=zone.les_elems();
  const double coeff=1./dimension;
  const double coeff_som=coeff/(dimension+1);
  const int nb_som_elem=zone.nb_som_elem();
  int face_opp=0,compj=0;
  int som_loc=0,som=0;
  int loc=0;
  int elem=0;
  double signe=0.;
  double volume=0.;
  assert(som_glob.size()==dimension+2);
  assert(grad.nb_dim()==2);
  assert(grad.dimension(1)==dimension+2);
//
// Calcul du gradient
//
  nnz=0;
  /* On regarde le premier element voisin */
  elem=face_voisins(face,0);
  assert(elem!=-1);
  for (som_loc=0; som_loc<nb_som_elem; som_loc++)
    {
      som=elem_som(elem,som_loc);
      som=dom.get_renum_som_perio(som);
      face_opp=elem_faces(elem,som_loc);
      signe=1.;
      if(elem!=face_voisins(face_opp,0)) signe=-1.;
// ajout a la liste et incrementation du repere
      som_glob(som_loc)=som;
      nnz++;
// Calcul du gradient local
      for(compj=0; compj<dimension; compj++)
        grad(compj,som_loc)=coeff_som*signe*
                            face_normales(face_opp,compj);
    }
  assert(nnz==nb_som_elem);
  /* On regarde le deuxieme element voisin */
  elem=face_voisins(face,1);
  assert(elem!=-1);
  for (som_loc=0; som_loc<nb_som_elem; som_loc++)
    {
      som=elem_som(elem,som_loc);
      som=dom.get_renum_som_perio(som);
      face_opp=elem_faces(elem,som_loc);
      signe=1.;
      if(elem!=face_voisins(face_opp,0)) signe=-1.;
// Localisation dans la liste deja construite
      for (loc=0; loc<nnz; loc++)
        if (som_glob[loc]==som)
          break;
// ajout a la liste et incrementation du repere
      if (loc==nnz)
        {
          som_glob(nnz)=som;
          nnz++;
        }
// Calcul du gradient local
      for(compj=0; compj<dimension; compj++)
        grad(compj,loc)+=coeff_som*signe*
                         face_normales(face_opp,compj);
    }
  assert(nnz<=(dimension+2));
  for (som_loc=0; som_loc<nnz; som_loc++)
    {
      som=som_glob(som_loc);
      volume=coeff_*volume_aux_sommets(som);
// On divise par la matrice de masse lumpee
      for(compj=0; compj<dimension; compj++)
        grad(compj,som_loc)/=volume;
    }
}
References coeff, coeff_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Domaine::get_renum_som_perio(), Zone::les_elems(), TRUSTTab< _TYPE_ >::nb_dim(), Zone::nb_som_elem(), TRUSTVect< _TYPE_ >::size(), Zone_VEF_PreP1b::volume_aux_sommets(), Zone_dis_base::zone(), and zone_VEFPreP1B().
gradient_som_CL()
void Op_Diff_VEFP1NCP1B_Face::gradient_som_CL (const int face, int & nnz, IntVect & som_glob, DoubleTab & grad) const protected
Definition at line 2833 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volume_aux_sommets=zone_VEF.volume_aux_sommets();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& elem_som=zone.les_elems();
  const IntTab& face_sommets=zone_VEF.face_sommets();
  const double coeff=1./dimension;
  const double coeff_som=coeff/(dimension+1);
  const int nb_som_elem=zone.nb_som_elem();
  const int nb_som_face=zone_VEF.nb_som_face();
  int face_opp=0,compj=0;
  int som_loc=0,som=0;
  int loc=0;
  int elem=0;
  double signe=0.;
  double volume=0.;
  assert(som_glob.size()==dimension+2);
  assert(grad.nb_dim()==2);
  assert(grad.dimension(1)==dimension+2);
//
// Calcul du gradient
//
  nnz=0;
  /* On regarde le premier element voisin */
  elem=face_voisins(face,0);
  assert(elem!=-1);
  for (som_loc=0; som_loc<nb_som_elem; som_loc++)
    {
      som=elem_som(elem,som_loc);
      som=dom.get_renum_som_perio(som);
      face_opp=elem_faces(elem,som_loc);
      signe=1.;
      if(elem!=face_voisins(face_opp,0)) signe=-1.;
// ajout a la liste et incrementation du repere
      som_glob(som_loc)=som;
      nnz++;
// Calcul du gradient local
      for(compj=0; compj<dimension; compj++)
        grad(compj,som_loc)=coeff_som*signe*
                            face_normales(face_opp,compj);
    }
  assert(nnz==nb_som_elem);
  /* On regarde le deuxieme element voisin */
  assert(face_voisins(face,1)==-1);
  for (som_loc=0; som_loc<nb_som_face; som_loc++) //sommets de "face"
    {
      som=face_sommets(face,som_loc);
      som=dom.get_renum_som_perio(som);
      for (loc=0; loc<nnz; loc++)
        if (som_glob(loc)==som)
          break;
      assert(som_loc<nnz);
      for (compj=0; compj<dimension; compj++)
        grad(compj,loc)+=coeff*face_normales(face,compj) ;
    }
  assert(nnz<=(dimension+2));
  for (som_loc=0; som_loc<nnz; som_loc++)
    {
      som=som_glob(som_loc);
      volume=coeff_*volume_aux_sommets(som);
// On divise par la matrice de masse lumpee
      for(compj=0; compj<dimension; compj++)
        grad(compj,som_loc)/=volume;
    }
}
References coeff, coeff_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Domaine::get_renum_som_perio(), Zone::les_elems(), TRUSTTab< _TYPE_ >::nb_dim(), Zone::nb_som_elem(), Zone_VF::nb_som_face(), TRUSTVect< _TYPE_ >::size(), Zone_VEF_PreP1b::volume_aux_sommets(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by coeff_matrice_som_CL(), coeff_matrice_som_symetrie(), and test().
info()
const Type_info * Op_Diff_VEFP1NCP1B_Face::info () static
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
initialiser()
void Op_Diff_VEFP1NCP1B_Face::initialiser () protected
Definition at line 1092 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const DoubleTab& unknown = equation().inconnue().valeurs();
  const int size = unknown.line_size();
// Definition des gradients
  gradient_p0_.resize(0, size, Objet_U::dimension);
  zone_VEF.zone().creer_tableau_elements(gradient_p0_);
  gradient_p1_.resize(0, size, Objet_U::dimension);
  zone_VEF.zone().domaine().creer_tableau_sommets(gradient_p1_);
  if (alphaA)
    {
      gradient_pa_.resize(0, size, Objet_U::dimension);
      zone_VEF.creer_tableau_aretes(gradient_pa_);
    }
// Initialisation de l'attribut dim_ch_
  dim_ch_=size;
// Dimensionnemt du tableau flux_bords
  flux_bords_.resize(zone_VEF.nb_faces_bord(),size);
  flux_bords_=0.;
}
References alphaA, Zone_VF::creer_tableau_aretes(), Zone::creer_tableau_elements(), Domaine::creer_tableau_sommets(), dim_ch_, Objet_U::dimension, Zone::domaine(), MorEqn::equation(), Operateur_base::flux_bords_, gradient_p0_, gradient_p1_, gradient_pa_, Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), Zone_VF::nb_faces_bord(), TRUSTTab< _TYPE_ >::resize(), Champ_Inc::valeurs(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by completer().
isFaceOfSymetry()
void Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry (ArrOfBit & is_symetry, int & nnz) const protected
Definition at line 3151 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const int nb_bords=zone_VEF.nb_front_Cl();
  int n_bord=0;
  int num1=0,num2=0;
  int ind_face=0;
  assert(is_symetry.size_array()==zone_VEF.nb_faces_tot());
// Preinitialisation
  nnz=0;
  is_symetry=0;
// Modification pour les faces de symetrie
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
      if (sub_type(Symetrie,la_cl.valeur()))
        {
          nnz+=num2;
          for (ind_face=num1; ind_face<num2; ind_face++)
            is_symetry.setbit(le_bord.num_face(ind_face));
        }
    }
}
References Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Front_VF::num_face(), ref_cast, ArrOfBit::setbit(), ArrOfBit::size_array(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and zone_VEFPreP1B().
Referenced by dimensionner().
isInStencil()
void Op_Diff_VEFP1NCP1B_Face::isInStencil (int face, int som_glob, int & elem0, int & som_loc0, int & elem1, int & som_loc1) const protected
Definition at line 2936 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& elem_som=zone.les_elems();
  const int nb_som_elem=zone.nb_som_elem();
  int elem00=0,elem11=0;
  int som_loc=0,som=0;
  elem00=face_voisins(face,0);
  assert(elem00!=-1);
  for (som_loc=0; som_loc<nb_som_elem; som_loc++)
    {
      som=elem_som(elem00,som_loc);
      som=dom.get_renum_som_perio(som);
      if (som_glob==som)
        {
          som_loc0=som_loc;
          elem0=elem00;
          break;
        }
    }
  if (som_loc==nb_som_elem)
    {
      elem0=-1;
      som_loc0=-1;
    }
  elem11=face_voisins(face,1);
  if (elem11==-1)
    {
      elem1=-1;
      som_loc1=-1;
    }
  else
    for (som_loc=0; som_loc<nb_som_elem; som_loc++)
      {
        som=elem_som(elem11,som_loc);
        som=dom.get_renum_som_perio(som);
        if (som_glob==som)
          {
            som_loc1=som_loc;
            elem1=elem11;
            break;
          }
      }
  if (som_loc==nb_som_elem)
    {
      elem1=-1;
      som_loc1=-1;
    }
// On ordonne
  if (elem0==-1 && elem1!=-1)
    {
      elem0=elem1;
      elem1=-1;
      som_loc0=som_loc1;
      som_loc1=-1;
    }
}
References Zone::domaine(), Zone_VF::face_voisins(), Domaine::get_renum_som_perio(), Zone::les_elems(), Zone::nb_som_elem(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), and test().
liste_face()
void Op_Diff_VEFP1NCP1B_Face::liste_face (IntLists & liste, int & nnz) const protected
Definition at line 2315 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const int firstFaceInt=zone_VEF.premiere_face_int();
  const int nb_som_tot=dom.nb_som_tot();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_som_elem=zone.nb_som_elem();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_faces_elem=zone.nb_faces_elem();
  const int nb_bords=zone_VEF.nb_front_Cl();
  int face=0,face2=0;
  int face_loc=0;
  int elem=0,elem_loc=0;
  int som=0,som_loc=0;
  int i=0,size=0;
  int n_bord=0,ind_face=0;
  int num1=0,num2=0;
  int tmp=0;
  IntTab faces_perio(nb_faces_tot);
  ArrOfBit fait(nb_faces_tot);
  IntLists sommets_faces(nb_som_tot);
// Il faut creer un second tableau travaillant sur les faces periodiques
// sinon la matrice pourrait ne pas etre homogene a l'operateur explicite
  for (face=0; face<nb_faces_tot; face++)
    faces_perio(face)=face;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int faceAss=0;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              faceAss=la_cl_perio.face_associee(ind_face);
              faceAss=le_bord.num_face(faceAss);
// Test afin de ne parcourir que la moitie des faces periodiques
// sachant que l'algorithme qui suit tient compte de ce choix
// REMARQUE : ce test marche aussi en parallele ou les faces
// virtuelles ne sont pas classees
              if (face<faceAss)
                {
                  faces_perio(face)=faceAss;
                  faces_perio(faceAss)=face;
                }
            }
        }
    }
// Connectivite liee aux sommets
  for (elem=0; elem<nb_elem_tot; elem++)
    for (som_loc=0; som_loc<nb_som_elem; som_loc++)
      {
        som=som_elem(elem,som_loc);
        som=dom.get_renum_som_perio(som);
        for (face_loc=0; face_loc<nb_faces_elem; face_loc++)
          {
            face=elem_faces(elem,face_loc);
            sommets_faces[som].add(face);
            if (faces_perio(face)!=face)
              sommets_faces[som].add(faces_perio(face));
          }
      }
  nnz=0;
  liste.dimensionner(nb_faces_tot);
// REMARQUE IMPORTANTE : IL FAUT ABSOLUMENT COMMENCER
// PAR REMPLIR LES FACES PERIODIQUES SINON :
// -LA MATRICE NE POURRA PAS ETRE PERIODIQUE
// -ET DES COEFFICIENTS POURRAIENT ETRE OUBLIES
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          int faceAss=0;
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              faceAss=la_cl_perio.face_associee(ind_face);
              faceAss=le_bord.num_face(faceAss);
// Test afin de ne parcourir que la moitie des faces periodiques
// sachant que l'algorithme qui suit tient compte de ce choix
// REMARQUE : ce test marche aussi en parallele ou les faces
// virtuelles ne sont pas classees
              if (face<faceAss)
                {
// RAZ du tableau fait
                  fait=0;
// pour la periodicite
                  size=liste[face].size();
                  for (i=0; i<size; i++)
                    fait.setbit(liste[face][i]);
// Pour que le premier element de la liste soit "face"
// Tient compte de la periodicite
                  if (size!=0)
                    {
                      tmp=liste[face][0];
                      liste[face][0]=face;
                      liste[face].add(tmp);
                      tmp=liste[faceAss][0];
                      liste[faceAss][0]=faceAss;
                      liste[faceAss].add(tmp);
                    }
                  else
                    {
                      liste[face].add(face);
                      liste[faceAss].add(faceAss);
                    }
                  fait.setbit(face);
                  fait.setbit(faceAss);
                  nnz+=2;//car on ajoute 2 coefficients
                  for (elem_loc=0; elem_loc<2; elem_loc++)
                    {
                      elem=face_voisins(face,elem_loc);
                      assert(elem!=-1);
                      for (som_loc=0; som_loc<nb_som_elem; som_loc++)
{
                          som=som_elem(elem,som_loc);
                          som=dom.get_renum_som_perio(som);
                          size=sommets_faces[som].size();
                          for (i=0; i<size; i++)
{
                              face2=sommets_faces[som][i];
                              if (!fait[face2])
{
                                  fait.setbit(face2);
                                  liste[face].add(face2);
                                  liste[faceAss].add(face2);
                                  liste[face2].add(face);
                                  liste[face2].add(faceAss);
                                  nnz+=4;//car on ajoute 4 coefficients
                                }
                            }//fin du for sur "i"
                        }//fin du for sur "som_loc"
                    }//fin du for sur "elem_loc"
                }//fin du if sur "face<faceAss"
            }//fin du for sur "ind_face"
        }//fin Periodique
    }//fin n_bord
// Autres conditions aux limites
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
      if (!sub_type(Periodique,la_cl.valeur()))
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
// RAZ du tableau fait
            fait=0;
// pour la periodicite
            size=liste[face].size();
            for (i=0; i<size; i++)
              fait.setbit(liste[face][i]);
// Pour que le premier element de la liste soit "face"
// Tient compte de la periodicite
            if (size!=0)
              {
                tmp=liste[face][0];
                liste[face][0]=face;
                liste[face].add(tmp);
              }
            else
              liste[face].add(face);
            fait.setbit(face);
            nnz++;
            elem=face_voisins(face,0);
            assert(elem!=-1);
            for (som_loc=0; som_loc<nb_som_elem; som_loc++)
              {
                som=som_elem(elem,som_loc);
                som=dom.get_renum_som_perio(som);
                size=sommets_faces[som].size();
                for (i=0; i<size; i++)
                  {
                    face2=sommets_faces[som][i];
                    if (!fait[face2])
                      {
                        fait.setbit(face2);
                        liste[face].add(face2);
                        nnz++;
                      }
                  }//fin du for sur "i"
              }//fin du for sur "som_loc"
          }//fin du else sur !Periodique
    }//fin du for sur n_bord
  for (face=firstFaceInt; face<nb_faces_tot; face++)
    if (!zone_VEF.est_une_face_virt_bord(face))
      {
// RAZ du tableau fait
        fait=0;
// pour la periodicite
        size=liste[face].size();
        for (i=0; i<size; i++)
          fait.setbit(liste[face][i]);
// Pour que le premier element de la liste soit "face"
// Tient compte de la periodicite
        if (size!=0)
          {
            tmp=liste[face][0];
            liste[face][0]=face;
            liste[face].add(tmp);
          }
        else
          liste[face].add(face);
        fait.setbit(face);
        nnz++;
        for (elem_loc=0; elem_loc<2; elem_loc++)
          {
            elem=face_voisins(face,elem_loc);
            if (elem!=-1) //pour face interne de joint
              for (som_loc=0; som_loc<nb_som_elem; som_loc++)
                {
                  som=som_elem(elem,som_loc);
                  som=dom.get_renum_som_perio(som);
                  size=sommets_faces[som].size();
                  for (i=0; i<size; i++)
                    {
                      face2=sommets_faces[som][i];
                      if (!fait[face2])
{
                          fait.setbit(face2);
                          liste[face].add(face2);
                          nnz++;
                        }
                    }//fin du for sur "i"
                }//fin du for sur "som_loc"
          }//fin du for sur "elem_loc"
      }//fin du for sur "face"
}
References liste::add(), Zone::domaine(), Zone_VF::elem_faces(), Zone_VF::est_une_face_virt_bord(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Zone::nb_som_elem(), Domaine::nb_som_tot(), Front_VF::num_face(), Zone_VF::premiere_face_int(), ref_cast, ArrOfBit::setbit(), TRUSTLists< _TYPE_ >::size(), liste::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by dimensionner().
printOn()
Sortie & Op_Diff_VEFP1NCP1B_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face_Var.
Definition at line 75 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Diff_VEFP1NCP1B_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_VEFP1NCP1B_Face_Var.
Definition at line 83 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
// Les mots a reconnaitre
  Motcle motlu, accouverte = "{" , accfermee = "}" ;
  Motcles les_mots(6);
  {
    les_mots[0] = "alphaE";
    les_mots[1] = "alphaS";
    les_mots[2] = "alphaA";
    les_mots[3] = "test";
    les_mots[4] = "decentrage";
    les_mots[5] = "epsilon";
  }
// Verification de la syntaxe
  s >> motlu;
  if (motlu!=accouverte)
    if (Process::je_suis_maitre())
      {
        Cerr << "Erreur Op_Diff_VEFP1NCP1B_Face::readOn()" << finl;
        Cerr << "Depuis la 1.5.5, la syntaxe du mot cle P1NCP1B a change."
             << finl;
        Cerr << "Il faut commencer par une accolade ouvrante {" << finl;
        Cerr << "et les options eventuelles sont entre les accolades :"
             << finl;
        Cerr << "Diffusion { P1NCP1B } -> Diffusion { P1NCB { } }" << finl;
        exit();
      }
// Lecture des parametres
  s >> motlu;
  while(motlu!=accfermee)
    {
      int rang = les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          s >> alphaE;
          break;
        case 1 :
          s >> alphaS;
          break;
        case 2 :
          if (Objet_U::dimension==3)
            s >> alphaA;
          else if (Process::je_suis_maitre())
            {
              Cerr << "Erreur Op_Diff_VEFP1NCP1B_Face::readOn()" << finl;
              Cerr << "L'option alphaA ne peut etre activee qu'en "
                   << "dimension 3" << finl;
              Cerr << "Sortie du programme" << finl;
              exit();
            }
          break;
        case 3 :
          test_=1;
          break;
        case 4 :
          s >> decentrage_;
          break;
        case 5 :
          s >> convexite_;
          break;
        default :
          if (Process::je_suis_maitre())
            {
              Cerr << "Erreur Op_Diff_VEFP1NCP1B_Face::readOn()" << finl;
              Cerr << "Mot clef " << motlu << " non reconnu" << finl;
              Cerr << "Les mots clef reconnus sont : " << les_mots << finl;
              Cerr << "Sortie du programme" << finl;
              exit();
            }
          break;
        }//fin du switch
// Suite de la lecture
      s >> motlu;
    }//fin du while
  if (alphaE && !alphaS) convexite_=1.;
  else if (alphaS && !alphaE) convexite_=0.;
  coeff_=1.;//alphaE+alphaS;
  return s;
}
References alphaA, alphaE, alphaS, Cerr, coeff_, convexite_, decentrage_, Objet_U::dimension, Process::exit(), finl, Process::je_suis_maitre(), Motcles::search(), and test_.
Referenced by Op_Diff_VEFP1NCP1B_Face_Var::readOn().
remplir_nu_p1()
void Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1 (const DoubleTab & nu_elem, DoubleTab & nu_p1) const protected
Calcule la diffusivite "nu_p1" aux sommets du maillage
en fonction de la diffusivite "nu_elem" aux elements.
On suppose que nu_elem a son espace virtuel a jour,
que nu_p1 est dimensionne nb_dim==1 avec la structure domaine.md_vector_sommets()
En sortie l'espace virtuel de nu_p1 est mis a jour
L'interpolateur calculs pour un sommet la moyenne (non ponderee) des
diffusivites sur les elements adjacents a ce sommet.
< Intialise a zero par defaut
Definition at line 2220 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone& zone=zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const int nb_som = dom.nb_som();
  const int nb_elem_tot=zone.nb_elem_tot();
  const int nb_som_elem=zone.nb_som_elem();
  int elem=0;
  int som_loc=0,som=0;
  const IntTab& elem_som=zone.les_elems();
  ArrOfInt nb_elem_per_som(nb_som); //!< Intialise a zero par defaut
  assert(nu_elem.get_md_vector() == zone.md_vector_elements());
  assert(nu_p1.get_md_vector() == dom.md_vector_sommets());
// On a besoin que l'espace virtuel de nu_elem soit a jour.
  assert_espace_virtuel_vect(nu_elem);
// Calcul effectif de "nu_som"
  nu_p1=0.;
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      const double nu = nu_elem[elem];
      for (som_loc=0; som_loc<nb_som_elem; som_loc++)
        {
          som=elem_som(elem,som_loc);
// Ne pas calculer les valeurs pour les sommets virtuels
// note BM: l'algo precedent ne calculait pas correctement les valeurs non plus
          if (som < nb_som)
            {
              som=dom.get_renum_som_perio(som);
              nu_p1(som) += nu;
              nb_elem_per_som[som]++;
            }
        }
    }
  for (som = 0; som < nb_som; som++)
    {
      const int som_perio = dom.get_renum_som_perio(som);
      int nvoisins = nb_elem_per_som[som_perio];
      if (nvoisins > 0)
        {
// La premiere fois qu'on tombe sur ce sommet on fait la division.
// On traite du meme coup le cas ou le sommet n'a pas d'elements voisins.
          nu_p1(som_perio) /= nvoisins;
          nb_elem_per_som[som_perio] = 0;
        }
      if (som != som_perio)
        nu_p1(som) = nu_p1(som_perio);
    }
// Le codage precedent n'avait apparemment pas besoin d'echange espace virtuel.
// A mon avis (BM) c'est un miracle du au fait qu'on fait les calculs avec epaisseur2
// (calcul sur nb_som_tot, donc les sommets des elements d'epaisseur 1 sont ok mais
// pas ceux d'epaisseur 2)
// Je prefere ce codage: (si on enleve, ca fait des ecarts en parallele)
  nu_p1.echange_espace_virtuel();
}
References assert_espace_virtuel_vect(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::get_renum_som_perio(), Zone::les_elems(), Zone::md_vector_elements(), Domaine::md_vector_sommets(), Zone::nb_elem_tot(), Domaine::nb_som(), Zone::nb_som_elem(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by ajouter(), ajouter_contribution(), calculer_dt_stab(), and test().
remplir_nu_pA()
void Op_Diff_VEFP1NCP1B_Face::remplir_nu_pA (const DoubleTab & nu_elem, DoubleTab & nu_pA) const protected
Definition at line 2301 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  Cerr << "Op_Diff_VEFP1NCP1B_Face::remplir_nu_pA() not coded" << finl;
  Cerr << "Exit" << finl;
  exit();
}
References Cerr, Process::exit(), and finl.
Referenced by ajouter(), ajouter_contribution(), and calculer_dt_stab().
self_cast() [1/2]
const Op_Diff_VEFP1NCP1B_Face & Op_Diff_VEFP1NCP1B_Face::self_cast (const Objet_U & r) static
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
self_cast() [2/2]
Op_Diff_VEFP1NCP1B_Face & Op_Diff_VEFP1NCP1B_Face::self_cast (Objet_U & r) static
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
taille_memoire()
unsigned Op_Diff_VEFP1NCP1B_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Diff_VEFP1NCP1B_Face_Var.
Definition at line 44 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
test()
void Op_Diff_VEFP1NCP1B_Face::test () const protected
Definition at line 3193 of file Op_Diff_VEFP1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF=zone_VEFPreP1B();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const Solveur_Masse& solveur_masse=equation().solv_masse();
  const int nb_bords=zone_VEF.nb_front_Cl();
  const int firstFaceInt=zone_VEF.premiere_face_int();
  const int nb_som_tot=dom.nb_som_tot();
  const DoubleTab& unknown = equation().inconnue().valeurs();
  const DoubleTab& xv=zone_VEF.xv();
  const DoubleTab& xs=dom.les_sommets();
  DoubleTab inco(unknown);
  DoubleVect& incoV = inco;
  incoV=0.;
  DoubleTab tmp(inco);
  DoubleTab resu(unknown);
  DoubleVect& resuV = resu;
  DoubleTab resuMat(unknown);
  const DoubleVect& resuMatV = resuMat;
  DoubleTab gradientMat(dimension,dimension+2);
  IntVect som_glob(dimension+2);
// Marqueur pour tenir compte de la porosite
  const int marq=phi_psi_diffuse(equation());
// Lignes pour tenir compte de la porosite
  const DoubleVect& poroE=zone_VEF.porosite_elem();
  DoubleVect poroF(zone_VEF.porosite_face());
  if (!marq) poroF=1.;
// Lignes pour tenir compte de la diffusivite
  DoubleTab nu;
  remplir_nu(nu_);
  modif_par_porosite_si_flag(nu_,nu,!marq,poroE);
  DoubleTab nu_p1;
  dom.creer_tableau_sommets(nu_p1);
  remplir_nu_p1(nu,nu_p1);
// Diverses variables utiles
  int face=0;
  int faceAss=0;
  int comp=0;
  int size0=zone_VEF.nb_faces();
  int i=0,j=0;
  int nnz=0;
  int compi=0,compj=0;
  int som=0;
  int n_bord=0;
  int num1=0,num2=0,ind_face=0;
  int ii=0;
  int size1 = unknown.line_size();
  Matrice_Morse matrice;
  dimensionner(matrice);
  if (alphaS) ajouter_contribution_som(inco,poroF,nu_p1,matrice);
  else if (alphaE) ajouter_contribution_elem(inco,poroF,nu,matrice);
  bool test1=false;
  double max=0.;
  DoubleTab gradient1(dimension);
  Motcle type;
  if (Process::nproc()>1)
    type="_PAR";
  else
    type="_SEQ";
  Motcles les_mots(8);
  {
    les_mots[0] = "matrice";
    les_mots[1] = "result";
    les_mots[2] = "res";
    les_mots[3] = "resMat";
    les_mots[4] = "grad";
    les_mots[5] = "gradMat";
    les_mots[6] = "div";
    les_mots[7] = "ligne_mat";
  }
  Motcle proc(Process::me());
  proc+=".txt";
  for (i=0; i<les_mots.size(); i++)
    {
      les_mots[i]+=type;
      les_mots[i]+=proc;
    }
  ofstream mat(les_mots[0].getChar());
  const Matrice_Morse& matConst=matrice;
  for (i=0; i<zone_VEF.nb_faces(); i++)
    {
      for (j=0; j<matConst.nb_colonnes(); j++)
        mat<<matConst(i,j)<<",";
      mat<<endl;
    }
  double coeff_diag=0.;
  double sum_coeff_extra_diag=0.;
  ofstream ligneMat(les_mots[7].getChar());
  for (i=0; i<matConst.nb_lignes(); i++)
    {
      coeff_diag=matConst(i,i);
      ligneMat<<"Ligne : "<<i<<endl;
      ligneMat<<"Coeff diag : "<<coeff_diag<<endl;
      ligneMat<<"Coeff extra diag : ";
      sum_coeff_extra_diag=0.;
      for (j=0; j<matConst.nb_colonnes(); j++)
        if (j!=i) sum_coeff_extra_diag+=matConst(i,j);
      ligneMat<<sum_coeff_extra_diag<<endl;
      ligneMat<<"Coeff extra diag par colonne : ";
      sum_coeff_extra_diag=0.;
      for (j=0; j<matConst.nb_colonnes(); j++)
        if (j!=i) sum_coeff_extra_diag+=matConst(j,i);
      ligneMat<<sum_coeff_extra_diag<<endl;
    }
  Motcle gradi("grad1");
  gradi+=type;
  gradi+=proc;
  int elem=0;
  int elem0=0,elem1=0;
  int som_loc0=1,som_loc1=1;
  int som_loc=0;
  const int nb_som_elem=zone.nb_som_elem();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& elem_som=zone.les_elems();
  ofstream grad1(gradi.getChar());
  for (face=0; face<size0; face++)
    {
      grad1<<"Face : "<<face<<endl;
      grad1<<"(";
      for (i=0; i<dimension; i++)
        grad1<<xv(face,i)<<",";
      grad1<<")"<<endl;
      for (ii=0; ii<2; ii++)
        {
          elem=face_voisins(face,ii);
          if (elem!=-1)
            for (som_loc=0; som_loc<nb_som_elem; som_loc++)
              {
                som=elem_som(elem,som_loc);
                som=dom.get_renum_som_perio(som);
                isInStencil(face,som,elem0,som_loc0,elem1,som_loc1);
                gradient1=0.;
                gradient_som(face,som,elem0,som_loc0,
                             elem1,som_loc1,gradient1);
                grad1<<som<<"(";
                for (i=0; i<dimension; i++)
                  grad1<<xs(som,i)<<",";
                grad1<<"):(";
                for (compj=0; compj<dimension; compj++)
                  grad1<<gradient1(compj)<<",";
                grad1<<")"<<endl;
              }
        }
    }
  ofstream result(les_mots[1].getChar());
  ofstream res(les_mots[2].getChar());
  ofstream resMat(les_mots[3].getChar());
  ofstream grad(les_mots[4].getChar());
  ofstream gradMat(les_mots[5].getChar());
  ofstream div(les_mots[6].getChar());
  for (face=firstFaceInt; face<size0; face++)
    {
      if (Process::je_suis_maitre()) incoV[face*size1+comp]=1.;
      inco.echange_espace_virtuel();
// Version explicite
      gradient_p1_=0.;
      calculer_gradient_som(inco);
// Controle des gradients
      grad<<"Face interne : "<<face*size1+comp<<endl;
      grad<<"(";
      for (i=0; i<dimension; i++)
        grad<<xv(face,i)<<",";
      grad<<")"<<endl;
      for (som=0; som<nb_som_tot; som++)
        {
          grad <<som<<"(";
          for (i=0; i<dimension; i++)
            grad<<xs(som,i)<<",";
          grad<<"):(";
          for (compi=0; compi<dim_ch_; compi++)
            for (compj=0; compj<dimension; compj++)
              grad<<gradient_p1_(som,compi,compj)<<",";
          grad<<")"<<endl;
        }
      gradientMat=0.;
      som_glob=-1;
      gradient_som(face,nnz,som_glob,gradientMat);
      gradMat<<"Face interne : "<<face*size1+comp<<endl;
      gradMat<<"(";
      for (i=0; i<dimension; i++)
        gradMat<<xv(face,i)<<",";
      gradMat<<")"<<endl;
      for (i=0; i<nnz; i++)
        {
          gradMat<<som_glob[i]<<"(";
          for (ii=0; ii<dimension; ii++)
            gradMat<<xs(som_glob[i],ii)<<",";
          gradMat<<"):(";
          for (compj=0; compj<dimension; compj++)
            gradMat<<gradientMat(compj,i)<<",";
          gradMat<<")"<<endl;
        }
      resu=0.;
      calculer_divergence_som(resu);
      corriger_Cl_test(resu);
      solveur_masse.appliquer(resu);
      div<<"Face interne : "<<face*size1+comp<<endl;
      div<<"(";
      for (i=0; i<dimension; i++)
        div<<xv(face,i)<<",";
      div<<")"<<endl;
      for (i=0; i<size0; i++)
        {
          div<<i<<"(";
          for (ii=0; ii<dimension; ii++)
            div<<xv(i,ii)<<",";
          div<<"):=(";
          for (j=0; j<size1; j++)
            div<<resu[i*size1+j]<<",";
          div<<")"<<endl;
        }
      resu*=-1.;
      res<<"Face interne : "<<face*size1+comp<<endl;
      res<<"(";
      for (i=0; i<dimension; i++)
        res<<xv(face,i)<<",";
      res<<")"<<endl;
      for (i=0; i<size0; i++)
        {
          res<<i<<"(";
          for (ii=0; ii<dimension; ii++)
            res<<xv(i,ii)<<",";
          res<<"):=(";
          for (j=0; j<size1; j++)
            res<<resu[i*size1+j]<<",";
          res<<")"<<endl;
        }
// Version matricielle
      resuMat=0.;
      matrice.ajouter_multTab_(inco,resuMat);
      solveur_masse.appliquer(resuMat);
      resuMat.echange_espace_virtuel();
      resMat<<"Face interne :"<<face*size1+comp<<endl;
      resMat<<"(";
      for (i=0; i<dimension; i++)
        resMat<<xv(face,i)<<",";
      resMat<<")"<<endl;
      for (i=0; i<size0; i++)
        {
          resMat<<i<<"(";
          for (ii=0; ii<dimension; ii++)
            resMat<<xv(i,ii)<<",";
          resMat<<"):=(";
          for (j=0; j<size1; j++)
            resMat<<resuMatV[i*size1+j]<<",";
          resMat<<")"<<endl;
        }
// Difference entre les resultat
      resu-=resuMat;
// Affichage des differences
      max=resu.local_max_abs_vect();
      if (max>1.e-14)
        {
          result<<"Diff pour face interne : "<<face*size1+comp<<endl;
          result<<"(";
          for (i=0; i<dimension; i++)
            result<<xv(face,i)<<",";
          result<<")"<<endl;
          for (i=0; i<size0; i++)
            {
              test1=false;
              for (j=0; j<size1; j++)
                test1|=(std::fabs(resuV[i*size1+j])>1.e-14);
              if (test1)
                {
                  result<<i<<"(";
                  for (ii=0; ii<dimension; ii++)
                    result<<xv(i,ii)<<",";
                  result<<"):=(";
                  for (j=0; j<size1; j++)
                    result <<resuV[i*size1+j]<<",";
                  result <<")"<<endl;
                }
            }
        }
      else
        {
          result<<"Diff pour face interne : "<<face*size1+comp<<endl;
          result<<"Maximum : "<<max<<endl;
        }
      if (Process::je_suis_maitre()) incoV[face*size1+comp]=0.;
      inco.echange_espace_virtuel();
    }
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1=0;
      num2=le_bord.nb_faces_tot();
// Modif pour tenir compte des conditions de Dirichlet
// -> la matrice de masse doit tout annuler
      if (sub_type(Dirichlet_homogene,la_cl.valeur()))
        {
// Il ne sert a rien de faire un test dans ce cas
        }
      else if (sub_type(Dirichlet,la_cl.valeur()))
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
// Version explicite
            gradient_p1_=0.;
            calculer_gradient_som(inco);
// Controle des gradients
            grad<<"Face Dirichlet : "<<face*size1+comp<<endl;
            grad<<"(";
            for (i=0; i<dimension; i++)
              grad<<xv(face,i)<<",";
            grad<<")"<<endl;
            for (som=0; som<nb_som_tot; som++)
              {
                grad <<som<<"(";
                for (i=0; i<dimension; i++)
                  grad<<xs(som,i)<<",";
                grad<<"):(";
                for (compi=0; compi<dim_ch_; compi++)
                  for (compj=0; compj<dimension; compj++)
                    grad<<gradient_p1_(som,compi,compj)<<",";
                grad<<")"<<endl;
              }
            gradientMat=0.;
            som_glob=-1;
            gradient_som_CL(face,nnz,som_glob,gradientMat);
            gradMat<<"Face Dirichlet : "<<face*size1+comp<<endl;
            gradMat<<"(";
            for (i=0; i<dimension; i++)
              gradMat<<xv(face,i)<<",";
            gradMat<<")"<<endl;
            for (i=0; i<nnz; i++)
              {
                gradMat<<som_glob[i]<<"(";
                for (ii=0; ii<dimension; ii++)
                  gradMat<<xs(som_glob[i],ii)<<",";
                gradMat<<"):(";
                for (compj=0; compj<dimension; compj++)
                  gradMat<<gradientMat(compj,i)<<",";
                gradMat<<")"<<endl;
              }
            for (i=0; i<size0; i++)
              for (j=0; j<size1; j++)
                resuV[i*size1+j]=0.;
          }
      else if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          assert(num2%2==0);
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              faceAss=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (Process::je_suis_maitre()) incoV[face*size1+comp]=1.;
              if (Process::je_suis_maitre()) incoV[faceAss*size1+comp]=1.;
              inco.echange_espace_virtuel();
// Version explicite
              gradient_p1_=0.;
              calculer_gradient_som(inco);
// Controle des gradients
              grad <<"Face perio : "<<face*size1+comp<<endl;
              grad<<"(";
              for (i=0; i<dimension; i++)
                grad<<xv(face,i)<<",";
              grad<<")"<<endl;
              for (som=0; som<nb_som_tot; som++)
                {
                  grad <<som<<"(";
                  for (i=0; i<dimension; i++)
                    grad<<xs(som,i)<<",";
                  grad<<"):(";
                  for (compi=0; compi<dim_ch_; compi++)
                    for (compj=0; compj<dimension; compj++)
                      grad<<gradient_p1_(som,compi,compj)<<",";
                  grad<<")"<<endl;
                }
              gradientMat=0.;
              som_glob=-1;
              gradient_som(face,nnz,som_glob,gradientMat);
              gradMat<<"Face perio : "<<face*size1+comp<<endl;
              gradMat<<"(";
              for (i=0; i<dimension; i++)
                gradMat<<xv(face,i)<<",";
              gradMat<<")"<<endl;
              for (i=0; i<nnz; i++)
                {
                  gradMat<<som_glob[i]<<"(";
                  for (ii=0; ii<dimension; ii++)
                    gradMat<<xs(som_glob[i],ii)<<",";
                  gradMat<<"):(";
                  for (compj=0; compj<dimension; compj++)
                    gradMat<<gradientMat(compj,i)<<",";
                  gradMat<<")"<<endl;
                }
              resu=0.;
              calculer_divergence_som(resu);
              corriger_Cl_test(resu);
              solveur_masse.appliquer(resu);
              div<<"Face perio : "<<face*size1+comp<<endl;
              div<<"(";
              for (i=0; i<dimension; i++)
                div<<xv(face,i)<<",";
              div<<")"<<endl;
              for (i=0; i<size0; i++)
                {
                  div<<i<<"(";
                  for (ii=0; ii<dimension; ii++)
                    div<<xv(i,ii)<<",";
                  div<<"):=(";
                  for (j=0; j<size1; j++)
                    div<<resu[i*size1+j]<<",";
                  div<<")"<<endl;
                }
              resu*=-1.;
              res<<"Face perio : "<<face*size1+comp<<endl;
              res<<"(";
              for (i=0; i<dimension; i++)
                res<<xv(face,i)<<",";
              res<<")"<<endl;
              for (i=0; i<size0; i++)
                {
                  res<<i<<"(";
                  for (ii=0; ii<dimension; ii++)
                    res<<xv(i,ii)<<",";
                  res<<"):=(";
                  for (j=0; j<size1; j++)
                    res<<resu[i*size1+j]<<",";
                  res<<")"<<endl;
                }
// Version matricielle
              resuMat=0.;
              matrice.ajouter_multTab_(inco,resuMat);
              solveur_masse.appliquer(resuMat);
              resuMat.echange_espace_virtuel();
              resMat<<"Face perio :"<<face*size1+comp<<endl;
              resMat<<"(";
              for (i=0; i<dimension; i++)
                resMat<<xv(face,i)<<",";
              resMat<<")"<<endl;
              for (i=0; i<size0; i++)
                {
                  resMat<<i<<"(";
                  for (ii=0; ii<dimension; ii++)
                    resMat<<xv(i,ii)<<",";
                  resMat<<"):=(";
                  for (j=0; j<size1; j++)
                    resMat<<resuMatV[i*size1+j]<<",";
                  resMat<<")"<<endl;
                }
// Difference entre les resultat
              resu-=resuMat;
// Affichage des differences
              max=resu.local_max_abs_vect();
              if (max>1.e-14)
                {
                  result<<"Diff pour face perio : "<<face*size1+comp<<endl;
                  result<<"(";
                  for (i=0; i<dimension; i++)
                    result<<xv(face,i)<<",";
                  result<<")"<<endl;
                  for (i=0; i<size0; i++)
                    {
                      test1=false;
                      for (j=0; j<size1; j++)
                        test1|=(std::fabs(resuV[i*size1+j])>1.e-14);
                      if (test1)
{
                          result<<i<<"(";
                          for (ii=0; ii<dimension; ii++)
                            result<<xv(i,ii)<<",";
                          result<<"):=(";
                          for (j=0; j<size1; j++)
                            result <<resuV[i*size1+j]<<",";
                          result <<")"<<endl;
                        }
                    }
                }
              else
                {
                  result<<"Diff pour face perio : "<<face*size1+comp<<endl;
                  result<<"Maximum : "<<max<<endl;
                }
              if (Process::je_suis_maitre()) incoV[face*size1+comp]=0.;
              if (Process::je_suis_maitre()) incoV[faceAss*size1+comp]=0.;
              inco.echange_espace_virtuel();
            }
        }//fin Perio
      else
        for (ind_face=num1; ind_face<num2; ind_face++)
          {
            face=le_bord.num_face(ind_face);
            if (Process::je_suis_maitre()) incoV[face*size1+comp]=1.;
            inco.echange_espace_virtuel();
// Version explicite
            gradient_p1_=0.;
            calculer_gradient_som(inco);
// Controle des gradients
            grad <<"Face CL : "<<face*size1+comp<<endl;
            grad<<"(";
            for (i=0; i<dimension; i++)
              grad<<xv(face,i)<<",";
            grad<<")"<<endl;
            for (som=0; som<nb_som_tot; som++)
              {
                grad <<som<<"(";
                for (i=0; i<dimension; i++)
                  grad<<xs(som,i)<<",";
                grad<<"):(";
                for (compi=0; compi<dim_ch_; compi++)
                  for (compj=0; compj<dimension; compj++)
                    grad<<gradient_p1_(som,compi,compj)<<",";
                grad<<")"<<endl;
              }
            gradientMat=0.;
            som_glob=-1;
            gradient_som_CL(face,nnz,som_glob,gradientMat);
            gradMat<<"Face CL : "<<face*size1+comp<<endl;
            gradMat<<"(";
            for (i=0; i<dimension; i++)
              gradMat<<xv(face,i)<<",";
            gradMat<<")"<<endl;
            for (i=0; i<nnz; i++)
              {
                gradMat<<som_glob[i]<<"(";
                for (ii=0; ii<dimension; ii++)
                  gradMat<<xs(som_glob[i],ii)<<",";
                gradMat<<"):(";
                for (compj=0; compj<dimension; compj++)
                  gradMat<<gradientMat(compj,i)<<",";
                gradMat<<")"<<endl;
              }
            resu=0.;
            calculer_divergence_som(resu);
            corriger_Cl_test(resu);
            solveur_masse.appliquer(resu);
            div<<"Face CL : "<<face*size1+comp<<endl;
            div<<"(";
            for (i=0; i<dimension; i++)
              div<<xv(face,i)<<",";
            div<<")"<<endl;
            for (i=0; i<size0; i++)
              {
                div<<i<<"(";
                for (ii=0; ii<dimension; ii++)
                  div<<xv(i,ii)<<",";
                div<<"):=(";
                for (j=0; j<size1; j++)
                  div<<resu[i*size1+j]<<",";
                div<<")"<<endl;
              }
            resu*=-1.;
            res<<"Face CL : "<<face*size1+comp<<endl;
            res<<"(";
            for (i=0; i<dimension; i++)
              res<<xv(face,i)<<",";
            res<<")"<<endl;
            for (i=0; i<size0; i++)
              {
                test1=false;
                for (j=0; j<size1; j++)
                  test1|=(std::fabs(resuV[i*size1+j])>max);
                if (test1)
                  {
                    res<<i<<"(";
                    for (ii=0; ii<dimension; ii++)
                      res<<xv(i,ii)<<",";
                    res<<"):=(";
                    for (j=0; j<size1; j++)
                      res<<resu[i*size1+j]<<",";
                    res<<")"<<endl;
                  }
              }
// Version matricielle
            resuMat=0.;
            matrice.ajouter_multTab_(inco,resuMat);
            solveur_masse.appliquer(resuMat);
            resuMat.echange_espace_virtuel();
            resMat<<"Face CL :"<<face*size1+comp<<endl;
            resMat<<"(";
            for (i=0; i<dimension; i++)
              resMat<<xv(face,i)<<",";
            resMat<<")"<<endl;
            for (i=0; i<size0; i++)
              {
                resMat<<i<<"(";
                for (ii=0; ii<dimension; ii++)
                  resMat<<xv(i,ii)<<",";
                resMat<<"):=(";
                for (j=0; j<size1; j++)
                  resMat<<resuMatV[i*size1+j]<<",";
                resMat<<")"<<endl;
              }
// Difference entre les resultat
            resu-=resuMat;
// Affichage des differences
            max=resu.local_max_abs_vect();
            if (max>1.e-14)
              {
                result<<"Diff pour face CL : "<<face*size1+comp<<endl;
                result<<"(";
                for (i=0; i<dimension; i++)
                  result<<xv(face,i)<<",";
                result<<")"<<endl;
                for (i=0; i<size0; i++)
                  {
                    test1=false;
                    for (j=0; j<size1; j++)
                      test1|=(std::fabs(resuV[i*size1+j])>1.e-14);
                    if (test1)
                      {
                        result<<i<<"(";
                        for (ii=0; ii<dimension; ii++)
                          result<<xv(i,ii)<<",";
                        result<<"):=(";
                        for (j=0; j<size1; j++)
                          result <<resuV[i*size1+j]<<",";
                        result <<")"<<endl;
                      }
                  }
              }
            else
              {
                result<<"Diff pour face CL : "<<face*size1+comp<<endl;
                result<<"Maximum : "<<max<<endl;
              }
            if (Process::je_suis_maitre()) incoV[face*size1+comp]=0.;
            inco.echange_espace_virtuel();
          }//fin autres CL
    }//fin du for sur n_bord
  exit();
}
References ajouter_contribution_elem(), ajouter_contribution_som(), Matrice_Morse::ajouter_multTab_(), alphaE, alphaS, Solveur_Masse::appliquer(), calculer_divergence_som(), calculer_gradient_som(), corriger_Cl_test(), Domaine::creer_tableau_sommets(), dim_ch_, Objet_U::dimension, dimensionner(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), Periodique::face_associee(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), Nom::getChar(), gradient_p1_, gradient_som(), gradient_som_CL(), Equation_base::inconnue(), isInStencil(), Process::je_suis_maitre(), Op_Diff_VEF_base::la_zcl_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Domaine::les_sommets(), TRUSTVect< _TYPE_ >::line_size(), TRUSTVect< _TYPE_ >::local_max_abs_vect(), Process::me(), modif_par_porosite_si_flag(), Matrice_Morse::nb_colonnes(), Zone_VF::nb_faces(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), Matrice_Morse::nb_lignes(), Zone::nb_som_elem(), Domaine::nb_som_tot(), Process::nproc(), Op_Diff_VEF_base::nu_, Front_VF::num_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), remplir_nu_p1(), vect_impl::size(), Equation_base::solv_masse(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Champ_Inc::valeurs(), Zone_VF::xv(), Zone_dis_base::zone(), and zone_VEFPreP1B().
Referenced by ajouter(), and ajouter_contribution().
zone_Cl_VEFPreP1B()
const Zone_Cl_VEFP1B & Op_Diff_VEFP1NCP1B_Face::zone_Cl_VEFPreP1B () const inline
Definition at line 162 of file Op_Diff_VEFP1NCP1B_Face.h.
{
  return ref_cast(Zone_Cl_VEFP1B,la_zcl_vef.valeur());
}
References Op_Diff_VEF_base::la_zcl_vef, ref_cast, and Ref_Zone_Cl_VEF::valeur().
zone_VEFPreP1B()
const Zone_VEF_PreP1b & Op_Diff_VEFP1NCP1B_Face::zone_VEFPreP1B () const inline
Definition at line 157 of file Op_Diff_VEFP1NCP1B_Face.h.
{
  return ref_cast(Zone_VEF_PreP1b,la_zone_vef.valeur());
}
References Op_Diff_VEF_base::la_zone_vef, ref_cast, and Ref_Zone_VEF::valeur().
Referenced by ajouter(), ajouter_contribution(), ajouter_contribution_som(), calculer_divergence_elem(), calculer_divergence_som(), calculer_dt_stab(), calculer_dt_stab_elem(), calculer_dt_stab_som(), calculer_flux_bords_elem(), calculer_flux_bords_som(), calculer_gradient_elem(), calculer_gradient_som(), calculer_laplacien_som(), coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), corriger_div_pour_Cl(), dimensionner(), gradient_som(), gradient_som_CL(), initialiser(), isFaceOfSymetry(), isInStencil(), liste_face(), remplir_nu_p1(), and test().
Member Data Documentation
alphaA
int Op_Diff_VEFP1NCP1B_Face::alphaA protected
Definition at line 135 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), ajouter_contribution(), calculer_dt_stab(), dimensionner(), initialiser(), Op_Diff_VEFP1NCP1B_Face(), and readOn().
alphaE
int Op_Diff_VEFP1NCP1B_Face::alphaE protected
Definition at line 133 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), ajouter_contribution(), calculer_dt_stab(), calculer_flux_bords_som(), coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), dimensionner(), Op_Diff_VEFP1NCP1B_Face(), readOn(), and test().
alphaS
int Op_Diff_VEFP1NCP1B_Face::alphaS protected
Definition at line 134 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), ajouter_contribution(), ajouter_contribution_elem(), calculer_dt_stab(), calculer_flux_bords_elem(), calculer_gradient_elem(), dimensionner(), Op_Diff_VEFP1NCP1B_Face(), readOn(), and test().
coeff_
double Op_Diff_VEFP1NCP1B_Face::coeff_ protected
Definition at line 132 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter_contribution_elem(), calculer_gradient_elem(), calculer_gradient_som(), coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), gradient_som(), gradient_som_CL(), Op_Diff_VEFP1NCP1B_Face(), and readOn().
convexite_
double Op_Diff_VEFP1NCP1B_Face::convexite_ protected
Definition at line 131 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), ajouter_contribution_elem(), calculer_dt_stab_elem(), calculer_flux_bords_elem(), calculer_flux_bords_som(), calculer_gradient_elem(), coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), Op_Diff_VEFP1NCP1B_Face(), and readOn().
decentrage_
int Op_Diff_VEFP1NCP1B_Face::decentrage_ protected
Definition at line 137 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), Op_Diff_VEFP1NCP1B_Face(), and readOn().
dim_ch_
int Op_Diff_VEFP1NCP1B_Face::dim_ch_ protected
Definition at line 136 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by calculer_divergence_elem(), calculer_divergence_som(), calculer_dt_stab_som(), calculer_flux_bords_elem(), calculer_flux_bords_som(), calculer_gradient_elem(), calculer_gradient_som(), coeff_matrice_som(), coeff_matrice_som_CL(), coeff_matrice_som_perio(), coeff_matrice_som_symetrie(), corriger_Cl_test(), corriger_div_pour_Cl(), initialiser(), and test().
gradient_p0_
DoubleTab Op_Diff_VEFP1NCP1B_Face::gradient_p0_ mutable protected
Definition at line 124 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), calculer_divergence_elem(), calculer_flux_bords_elem(), calculer_gradient_elem(), and initialiser().
gradient_p1_
DoubleTab Op_Diff_VEFP1NCP1B_Face::gradient_p1_ mutable protected
Definition at line 125 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), calculer_divergence_som(), calculer_flux_bords_som(), calculer_gradient_som(), initialiser(), and test().
gradient_pa_
DoubleTab Op_Diff_VEFP1NCP1B_Face::gradient_pa_ mutable protected
Definition at line 126 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), calculer_gradient_aretes(), and initialiser().
info_obj
const Type_info Op_Diff_VEFP1NCP1B_Face::info_obj static
Definition at line 42 of file Op_Diff_VEFP1NCP1B_Face.h.
is_laplacian_built_
int Op_Diff_VEFP1NCP1B_Face::is_laplacian_built_ mutable protected
Definition at line 129 of file Op_Diff_VEFP1NCP1B_Face.h.
is_laplacian_filled_
int Op_Diff_VEFP1NCP1B_Face::is_laplacian_filled_ mutable protected
Definition at line 128 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by calculer_dt_stab_som(), calculer_laplacien_som(), and Op_Diff_VEFP1NCP1B_Face().
laplacien_p1_
Matrice_Morse Op_Diff_VEFP1NCP1B_Face::laplacien_p1_ mutable protected
Definition at line 127 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), calculer_dt_stab_som(), and calculer_laplacien_som().
test_
int Op_Diff_VEFP1NCP1B_Face::test_ protected
Definition at line 121 of file Op_Diff_VEFP1NCP1B_Face.h.
Referenced by ajouter(), ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face(), and readOn().
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Diff_VEFP1NCP1B_Face.h
src/P1NCP1B/Operateurs/Op_Diff_VEFP1NCP1B_Face.cpp