TRUST: Tetraedre Class Reference
Tetraedre Class Reference
Classe Tetraedre
Cette classe represente l'element geometrique Tetraedre.
Un tetraedre est un polyedre qui a 4 faces, 4 sommets et
un seul type de face ayant 3 sommets par face.
#include <Tetraedre.h>
Public Member Functions
Tetraedre ()
~Tetraedre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int nb_som () const override
Renvoie le nombre de sommets d'un tetraedre: 4.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const override
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const override
Renvoie toujours 0, car l'element geometrique
Tetraedre n'est pas de type structure.
const Nom & nom_lml () const override
Renvoie le nom LML d'un tetraedre = "TETRA4".
int contient (const ArrOfDouble &, int) const override
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un tetraedre n'a qu'un seul type de face.
void calculer_volumes (DoubleVect &) const override
Calcule les volumes des elements de la zone associee.
void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const override
Calcule les normales aux faces des elements de la zone associee.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
voir ElemGeomBase::get_tab_faces_sommets_locaux
void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const override
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Tetraedre & self_cast (Objet_U &)
static const Tetraedre & self_cast (const Objet_U &)
static void matrice_base_tetraedre (const IntTab &polys, const DoubleTab &coords, int num_elem, Matrice33 &m, Vecteur3 &origine)
Idem que la precedente, mais remplit en plus "origine"
avec les coordonnees du premier sommet.
static void matrice_base_tetraedre (const IntTab &polys, const DoubleTab &coords, int num_elem, Matrice33 &m)
remplit la matrice m avec les trois vecteurs de base du tetraedre demande<br>(le premier sommet du tetra est pris comme origine).
polys est le tableau des elements de la zone, coords le tableau des coordonnees
num_elem le numero du tetraedre a calculer.
m est rempli avec la matrice m(i,j) = coord(polys(num_elem, j+1), i) - coord(polys(num_elem, 0), i)
static double coord_bary (const IntTab &polys, const DoubleTab &coords, const Vecteur3 &point, int le_poly, Vecteur3 &coord_bary, double epsilon=0.)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Tetraedre
Cette classe represente l'element geometrique Tetraedre.
Un tetraedre est un polyedre qui a 4 faces, 4 sommets et
un seul type de face ayant 3 sommets par face.
Definition at line 33 of file Tetraedre.h.
Constructor & Destructor Documentation
Tetraedre()
Tetraedre::Tetraedre ()
Definition at line 30 of file Tetraedre.cpp.
~Tetraedre()
Tetraedre::~Tetraedre ()
Definition at line 30 of file Tetraedre.cpp.
Member Function Documentation
calculer_normales()
void Tetraedre::calculer_normales (const IntTab & faces_sommets, DoubleTab & face_normales) const override virtual
Calcule les normales aux faces des elements de la zone associee.
Reimplemented from Elem_geom_base.
Definition at line 339 of file Tetraedre.cpp.
{
  const Zone& zone_geom = ma_zone.valeur();
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  int nbfaces = Face_sommets.dimension(0);
  double x1,y1,z1,x2,y2,z2;
  int n0,n1,n2;
  for (int numface=0; numface<nbfaces; numface++)
    {
      n0 = Face_sommets(numface,0);
      n1 = Face_sommets(numface,1);
      n2 = Face_sommets(numface,2);
      x1 = les_coords(n0,0) - les_coords(n1,0);
      y1 = les_coords(n0,1) - les_coords(n1,1);
      z1 = les_coords(n0,2) - les_coords(n1,2);
      x2 = les_coords(n2,0) - les_coords(n1,0);
      y2 = les_coords(n2,1) - les_coords(n1,1);
      z2 = les_coords(n2,2) - les_coords(n1,2);
      face_normales(numface,0) = (y1*z2 - y2*z1)/2;
      face_normales(numface,1) = (-x1*z2 + x2*z1)/2;
      face_normales(numface,2) = (x1*y2 - x2*y1)/2;
    }
}
References Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Elem_geom_base::ma_zone, and Ref_Zone::valeur().
calculer_volumes()
void Tetraedre::calculer_volumes (DoubleVect & volumes) const override virtual
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Definition at line 280 of file Tetraedre.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  double x0,y0,z0;
  double x1,y1,z1;
  double x2,y2,z2;
  double x3,y3,z3;
  int s[4];
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      for (int i=0; i<4; i++)
        s[i] = zone.sommet_elem(num_poly,i);
      x0 = dom.coord(s[0],0);
      y0 = dom.coord(s[0],1);
      z0 = dom.coord(s[0],2);
      x1 = dom.coord(s[1],0);
      y1 = dom.coord(s[1],1);
      z1 = dom.coord(s[1],2);
      x2 = dom.coord(s[2],0);
      y2 = dom.coord(s[2],1);
      z2 = dom.coord(s[2],2);
      x3 = dom.coord(s[3],0);
      y3 = dom.coord(s[3],1);
      z3 = dom.coord(s[3],2);
      volumes[num_poly] = std::fabs((x1-x0)*((y2-y0)*(z3-z0)-(y3-y0)*(z2-z0))-
                                    (x2-x0)*((y1-y0)*(z3-z0)-(y3-y0)*(z1-z0))+
                                    (x3-x0)*((y1-y0)*(z2-z0)-(y2-y0)*(z1-z0)))/6;
    }
}
References Domaine::coord(), Zone::domaine(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), TRUSTVect< _TYPE_ >::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [1/2]
int Tetraedre::contient (const ArrOfDouble & pos, int ielem) const override virtual
Renvoie 1 si l'element ielem de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element ielem
0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 122 of file Tetraedre.cpp.
{
// 29/01/2010 Optimisation CPU de la methode (50% plus rapide) par PL
  assert(pos.size_array()==3);
  const Zone& zone=ma_zone.valeur();
  const DoubleTab& coord=zone.domaine().coord_sommets();
  double prod1,prod2,xn,yn,zn;
  int som0 = zone.sommet_elem(ielem,0);
  int som1 = zone.sommet_elem(ielem,1);
  int som2 = zone.sommet_elem(ielem,2);
  int som3 = zone.sommet_elem(ielem,3);
  double X0 = coord(som0,0);
  double Y0 = coord(som0,1);
  double Z0 = coord(som0,2);
  double X1 = coord(som1,0);
  double Y1 = coord(som1,1);
  double Z1 = coord(som1,2);
  double X2 = coord(som2,0);
  double Y2 = coord(som2,1);
  double Z2 = coord(som2,2);
  double X3 = coord(som3,0);
  double Y3 = coord(som3,1);
  double Z3 = coord(som3,2);
  /*
    if ((est_egal(X0,pos(0)) && est_egal(Y0,pos(1)) && est_egal(Z0,pos(2)))
    || (est_egal(X1,pos(0)) && est_egal(Y1,pos(1)) && est_egal(Z1,pos(2)))
    || (est_egal(X2,pos(0)) && est_egal(Y2,pos(1)) && est_egal(Z2,pos(2)))
    || (est_egal(X3,pos(0)) && est_egal(Y3,pos(1)) && est_egal(Z3,pos(2))))
// On regarde tout d'abord si le point cherche n'est pas un des sommets du triangle
// D'apres gcov sur les 1000 cas tests, on ne gagne pas beaucoup a faire cela (utile dans 0.03% des cas!!!)
    return 1; */
  for (int j=0; j<4; j++)
    {
      switch(j)
        {
        case 0 :
// Inutile car deja fait quelques lignes plus haut
// som0 = zone.sommet_elem(ielem,0);
// som1 = zone.sommet_elem(ielem,1);
// som2 = zone.sommet_elem(ielem,2);
// som3 = zone.sommet_elem(ielem,3);
          break;
        case 1 :
          swap(som0,som1);
          swap(som2,som3);
          swap(X0,X1);
          swap(Y0,Y1);
          swap(Z0,Z1);
          swap(X2,X3);
          swap(Y2,Y3);
          swap(Z2,Z3);
// som0 = zone.sommet_elem(ielem,1);
// som1 = zone.sommet_elem(ielem,0);
// som2 = zone.sommet_elem(ielem,3);
// som3 = zone.sommet_elem(ielem,2);
          break;
        case 2 :
          swap(som0,som1);
          swap(som1,som3);
          swap(X0,X1);
          swap(Y0,Y1);
          swap(Z0,Z1);
          swap(X1,X3);
          swap(Y1,Y3);
          swap(Z1,Z3);
// som0 = zone.sommet_elem(ielem,0);
// som1 = zone.sommet_elem(ielem,2);
// som2 = zone.sommet_elem(ielem,3);
// som3 = zone.sommet_elem(ielem,1);
          break;
        case 3 :
          swap(som0,som1);
          swap(som1,som3);
          swap(X0,X1);
          swap(Y0,Y1);
          swap(Z0,Z1);
          swap(X1,X3);
          swap(Y1,Y3);
          swap(Z1,Z3);
// som0 = zone.sommet_elem(ielem,2);
// som1 = zone.sommet_elem(ielem,1);
// som2 = zone.sommet_elem(ielem,3);
// som3 = zone.sommet_elem(ielem,0);
          break;
        }
// Algorithme : le sommet 3 et le point M doivent pour j=0 a 3 du meme cote
// que le plan formes par les points som0,som1,som2.
// calcul de la normale au plan som0,som1,som2 :
      xn = ( Y1 - Y0 ) * ( Z2 - Z0 ) - ( Z1 - Z0 ) * ( Y2 - Y0 );
      yn = ( Z1 - Z0 ) * ( X2 - X0 ) - ( X1 - X0 ) * ( Z2 - Z0 );
      zn = ( X1 - X0 ) * ( Y2 - Y0 ) - ( Y1 - Y0 ) * ( X2 - X0 );
      prod1 = xn * ( X3 - X0 )
              + yn * ( Y3 - Y0 )
              + zn * ( Z3 - Z0 );
      prod2 = xn * ( pos[0] - X0 )
              + yn * ( pos[1] - Y0 )
              + zn * ( pos[2] - Z0 );
// Si le point est sur le plan (prod2 quasi nul) : on ne peut pas conclure...
      if (prod1*prod2 < 0 && std::fabs(prod2)>std::fabs(prod1)*Objet_U::precision_geom) return 0;
    }
  return 1;
}
References Domaine::coord_sommets(), Zone::domaine(), Elem_geom_base::ma_zone, Objet_U::precision_geom, TRUSTArray< _TYPE_ >::size_array(), Zone::sommet_elem(), swap(), and Ref_Zone::valeur().
contient() [2/2]
int Tetraedre::contient (const ArrOfInt & som, int element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Definition at line 253 of file Tetraedre.cpp.
{
  const Zone& zone=ma_zone.valeur();
  if((zone.sommet_elem(element,0)==som[0])&&
      (zone.sommet_elem(element,1)==som[1])&&
      (zone.sommet_elem(element,1)==som[2])&&
      (zone.sommet_elem(element,1)==som[3]))
    return 1;
  else
    return 0;
}
References Elem_geom_base::ma_zone, Zone::sommet_elem(), and Ref_Zone::valeur().
coord_bary()
double Tetraedre::coord_bary (const IntTab & polys, const DoubleTab & coords, const Vecteur3 & point, int le_poly, Vecteur3 & coord_bary, double epsilon = 0.) static
Definition at line 410 of file Tetraedre.cpp.
{
  Matrice33 m;
  Vecteur3 origine;
  matrice_base_tetraedre(polys, coords, le_poly, m, origine);
  Matrice33 inverse_m;
  Matrice33::inverse(m, inverse_m);
  Vecteur3 v(point-origine);
  Matrice33::produit(inverse_m, v, coord_bary);
  double resu;
  if (epsilon > 0.)
    {
// Une erreur epsilon sur la coordonnee "point" entraine une erreur sur coord_bary:
      double norm = inverse_m.norme_Linfini();
      resu = norm * epsilon;
    }
  else
    {
      resu = 0.;
    }
  return resu;
}
References coord_bary(), Matrice33::inverse(), matrice_base_tetraedre(), Matrice33::norme_Linfini(), and Matrice33::produit().
Referenced by coord_bary().
cree_instance()
Objet_U * Tetraedre::cree_instance () static
Definition at line 30 of file Tetraedre.cpp.
duplique()
int Tetraedre::duplique () const override virtual
Implements Objet_U.
Definition at line 30 of file Tetraedre.cpp.
est_structure()
int Tetraedre::est_structure () const inline override virtual
Renvoie toujours 0, car l'element geometrique
Tetraedre n'est pas de type structure.
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 0
Implements Elem_geom_base.
Definition at line 327 of file Tetraedre.h.
{
  return 0;
}
face_sommet()
int Tetraedre::face_sommet (int i, int j) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 98 of file Tetraedre.h.
{
  assert(i<4);
  switch(i)
    {
    case 0:
      return face_sommet0(j);
    case 1:
      return face_sommet1(j);
    case 2:
      return face_sommet2(j);
    case 3:
      return face_sommet3(j);
    default :
      return -1;
    }
}
References face_sommet0(), face_sommet1(), face_sommet2(), and face_sommet3().
face_sommet0()
int Tetraedre::face_sommet0 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 0.
Returns
int
Signification: le numero du i-ieme sommet de la face 0
Contraintes:
Definition at line 205 of file Tetraedre.h.
{
// face_sommet0(0)=1;
// face_sommet0(1)=2;
// face_sommet0(2)=3;
  assert(i>=0);
  assert(i<3);
  if(i>=3)
    {
      Cerr << "A tetrahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return (i+1);
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet1()
int Tetraedre::face_sommet1 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 1.
Returns
int
Signification: le numero du i-ieme sommet de la face 1
Contraintes:
Definition at line 235 of file Tetraedre.h.
{
// face_sommet0(0)=2;
// face_sommet1(1)=3;
// face_sommet2(2)=0;
  assert(i>=0);
  assert(i<3);
  if(i>=3)
    {
      Cerr << "A tetrahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return (i+2)%4;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet2()
int Tetraedre::face_sommet2 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 2.
Returns
int
Signification: le numero du i-ieme sommet de la face 2
Contraintes:
Definition at line 265 of file Tetraedre.h.
{
// face_sommet2(0)=3;
// face_sommet2(1)=0;
// face_sommet2(2)=1;
  assert(i>=0);
  assert(i<3);
  if(i>=3)
    {
      Cerr << "A tetrahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return (i+3)%4;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet3()
int Tetraedre::face_sommet3 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 3.
Returns
int
Signification: le numero du i-ieme sommet de la face 3
Contraintes:
Definition at line 295 of file Tetraedre.h.
{
// face_sommet2(0)=0;
// face_sommet2(1)=1;
// face_sommet2(2)=2;
  assert(i>=0);
  assert(i<3);
  if(i>=3)
    {
      Cerr << "A tetrahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return (i);
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
get_info()
const Type_info * Tetraedre::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 30 of file Tetraedre.cpp.
get_tab_aretes_sommets_locaux()
void Tetraedre::get_tab_aretes_sommets_locaux (IntTab & aretes_som_local) const override virtual
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Reimplemented from Elem_geom_base.
Definition at line 379 of file Tetraedre.cpp.
{
// un tetraedre a six aretes de deux sommets
  tab.resize(6, 2);
  int count = 0;
// Une arete entre chaque couple de sommet du tetra: n * (n-1) / 2 aretes avec n=4
  for (int i = 0; i < 3; i++)
    {
      for (int j = i + 1; j < 4; j++)
        {
          tab(count, 0) = i;
          tab(count, 1) = j;
          count++;
        }
    }
  assert(count == 6);
}
References TRUSTTab< _TYPE_ >::resize().
get_tab_faces_sommets_locaux()
int Tetraedre::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
voir ElemGeomBase::get_tab_faces_sommets_locaux
Reimplemented from Elem_geom_base.
Definition at line 369 of file Tetraedre.cpp.
{
// un tetraedre a quatre faces de trois sommets
  faces_som_local.resize(4,3);
  for (int i=0; i<4; i++)
    for (int j=0; j<3; j++)
      faces_som_local(i,j) = faces_sommets_tetra[i][j];
  return 1;
}
References faces_sommets_tetra, and TRUSTTab< _TYPE_ >::resize().
info()
const Type_info * Tetraedre::info () static
Definition at line 30 of file Tetraedre.cpp.
matrice_base_tetraedre() [1/2]
void Tetraedre::matrice_base_tetraedre (const IntTab & polys, const DoubleTab & coords, int num_elem, Matrice33 & m) inline static
remplit la matrice m avec les trois vecteurs de base du tetraedre demande<br>(le premier sommet du tetra est pris comme origine).
polys est le tableau des elements de la zone, coords le tableau des coordonnees
num_elem le numero du tetraedre a calculer.
m est rempli avec la matrice m(i,j) = coord(polys(num_elem, j+1), i) - coord(polys(num_elem, 0), i)
Definition at line 364 of file Tetraedre.h.
{
  const int som0 = polys(num_elem, 0);
  const int som1 = polys(num_elem, 1);
  const int som2 = polys(num_elem, 2);
  const int som3 = polys(num_elem, 3);
  const double x0 = coords(som0, 0);
  const double y0 = coords(som0, 1);
  const double z0 = coords(som0, 2);
// Matrice des trois vecteurs de base du tetra (origine au sommet 0)
  m(0,0) = coords(som1,0) - x0;
  m(1,0) = coords(som1,1) - y0;
  m(2,0) = coords(som1,2) - z0;
  m(0,1) = coords(som2,0) - x0;
  m(1,1) = coords(som2,1) - y0;
  m(2,1) = coords(som2,2) - z0;
  m(0,2) = coords(som3,0) - x0;
  m(1,2) = coords(som3,1) - y0;
  m(2,2) = coords(som3,2) - z0;
}
matrice_base_tetraedre() [2/2]
void Tetraedre::matrice_base_tetraedre (const IntTab & polys, const DoubleTab & coords, int num_elem, Matrice33 & m, Vecteur3 & origine) inline static
Idem que la precedente, mais remplit en plus "origine"
avec les coordonnees du premier sommet.
Definition at line 390 of file Tetraedre.h.
{
  const int som0 = polys(num_elem, 0);
  const int som1 = polys(num_elem, 1);
  const int som2 = polys(num_elem, 2);
  const int som3 = polys(num_elem, 3);
  const double x0 = coords(som0, 0);
  const double y0 = coords(som0, 1);
  const double z0 = coords(som0, 2);
// Matrice des trois vecteurs de base du tetra (origine au sommet 0)
  m(0,0) = coords(som1,0) - x0;
  m(1,0) = coords(som1,1) - y0;
  m(2,0) = coords(som1,2) - z0;
  m(0,1) = coords(som2,0) - x0;
  m(1,1) = coords(som2,1) - y0;
  m(2,1) = coords(som2,2) - z0;
  m(0,2) = coords(som3,0) - x0;
  m(1,2) = coords(som3,1) - y0;
  m(2,2) = coords(som3,2) - z0;
  origine[0] = x0;
  origine[1] = y0;
  origine[2] = z0;
}
Referenced by coord_bary().
nb_faces()
int Tetraedre::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Returns
int
Signification: le nombre de faces de type i
Contraintes: toujours egal a 4 (si i=0)
Implements Elem_geom_base.
Definition at line 152 of file Tetraedre.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A tetrahedron has not " << i << " types of face" << finl;
      exit();
    }
  return 4;
}
References Cerr, Process::exit(), and finl.
nb_som()
int Tetraedre::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un tetraedre: 4.
Returns
int
Signification: le nombre de sommets d'un tetraedre
Contraintes: toujours egal a 4
Implements Elem_geom_base.
Definition at line 131 of file Tetraedre.h.
{
  return 4;
}
nb_som_face()
int Tetraedre::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Contraintes: toujours egal a 3 (si i=0)
Implements Elem_geom_base.
Definition at line 179 of file Tetraedre.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A tetrahedron has not " << i << " types of face" << finl;
      exit();
    }
  return 3;
}
References Cerr, Process::exit(), and finl.
nom_lml()
const Nom & Tetraedre::nom_lml () const override virtual
Renvoie le nom LML d'un tetraedre = "TETRA4".
Returns
Nom&
Signification: toujours egal a "TETRA4"
Contraintes: reference constante
Implements Elem_geom_base.
Definition at line 89 of file Tetraedre.cpp.
{
  static Nom nom="TETRA4";
  return nom;
}
printOn()
Sortie & Tetraedre::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 47 of file Tetraedre.cpp.
{
  return s;
}
readOn()
Entree & Tetraedre::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Elem_geom_base.
Definition at line 67 of file Tetraedre.cpp.
{
  return s;
}
self_cast() [1/2]
const Tetraedre & Tetraedre::self_cast (const Objet_U & r) static
Definition at line 30 of file Tetraedre.cpp.
self_cast() [2/2]
Tetraedre & Tetraedre::self_cast (Objet_U & r) static
Definition at line 30 of file Tetraedre.cpp.
taille_memoire()
unsigned Tetraedre::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 30 of file Tetraedre.cpp.
type_face()
Type_Face Tetraedre::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un tetraedre n'a qu'un seul type de face.
Returns
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::triangle_3D (si i=0)
Implements Elem_geom_base.
Definition at line 348 of file Tetraedre.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A tetrahedron has not " << i << " types of face" << finl;
      exit();
    }
  return Faces::triangle_3D;
}
References Cerr, Process::exit(), finl, and Faces::triangle_3D.
Member Data Documentation
info_obj
const Type_info Tetraedre::info_obj static
Definition at line 36 of file Tetraedre.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Tetraedre.h
src/Kernel/Geometrie/Tetraedre.cpp