TRUST: Schema_Backward_Differentiation_base Class Reference
Schema_Backward_Differentiation_base Class Reference
classe Schema_Backward_Differentiation_base
#include <Schema_Backward_Differentiation_base.h>
Public Member Functions
Schema_Backward_Differentiation_base ()
~Schema_Backward_Differentiation_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
double changer_temps (Equation_base &eqn, const double &temps)
void update_time_derivative (Equation_base &eqn, const DoubleTab &data)
void mettre_a_jour_equation (Equation_base &eqn, const double &temps)
void store_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters)
void modify_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters)
void compute_coefficients (double time_step, const DoubleTab &times) const
void add_multi_timestep_data (const Equation_base &eqn, Matrice_Base &mat_morse, DoubleTab &secmem) const
const DoubleTab & coefficients () const
DoubleTab & coefficients ()
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Schema_Backward_Differentiation_base & self_cast (Objet_U &)
static const
Schema_Backward_Differentiation_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
virtual void compute_backward_differentiation_coefficients (double time_step, const DoubleTab &times) const =0
Protected Attributes
DoubleTab backward_differentiation_coefficients_
Detailed Description
classe Schema_Backward_Differentiation_base
Definition at line 40 of file Schema_Backward_Differentiation_base.h.
Constructor & Destructor Documentation
Schema_Backward_Differentiation_base::Schema_Backward_Differentiation_base ()
Definition at line 35 of file Schema_Backward_Differentiation_base.cpp.
Schema_Backward_Differentiation_base::~Schema_Backward_Differentiation_base ()
Definition at line 35 of file Schema_Backward_Differentiation_base.cpp.
Member Function Documentation
void Schema_Backward_Differentiation_base::add_multi_timestep_data (const Equation_base & eqn, Matrice_Base & mat_morse, DoubleTab & secmem) const [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 133 of file Schema_Backward_Differentiation_base.cpp.
References Solveur_Masse::ajouter_masse(), coefficients(), Equation_base::inconnue(), Schema_Implicite_Multi_TimeStep_base::nb_valeurs_passees(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), Equation_base::solv_masse(), and Champ_Inc::valeurs().
{
  double time_step               =  pas_de_temps();
  double effective_time_step     = -1.;
// Remark for "pen" interger : we do not penalize matrices and right members even in the case
// of Dirichlet or Symetrie boundary conditions
  int pen    = 0;
  int offset = 0;
  int i      = 0;
  effective_time_step     = coefficients()[nb_valeurs_passees()+1] * time_step;
// Modification due to present time and past times
  DoubleTab dudt(eqn.inconnue().valeurs());
  DoubleTab tmp(dudt);
  dudt = 0.;
  for (i=0; i<nb_valeurs_passees()+1; ++i)
    {
      offset  = nb_valeurs_passees()-i + 1;//due to Initialiser_Champs() offset
      tmp     = eqn.inconnue().passe(offset);
      tmp    *= coefficients()[i] ;
      dudt   += tmp; //past times and present time if i==nb_valeurs_passees()
    }
  eqn.solv_masse().ajouter_masse(effective_time_step,secmem,dudt,pen);
  eqn.solv_masse().ajouter_masse(effective_time_step,mat_morse,pen);
}
double Schema_Backward_Differentiation_base::changer_temps (Equation_base & eqn, const double & temps) [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 79 of file Schema_Backward_Differentiation_base.cpp.
References Equation_base::inconnue(), and Deriv_Champ_Inc_base::valeur().
{
  eqn.inconnue().valeur().Champ_base::changer_temps(temps);
  return temps;
}
DoubleTab & Schema_Backward_Differentiation_base::coefficients () [inline, virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 69 of file Schema_Backward_Differentiation_base.h.
References backward_differentiation_coefficients_.
{
  return backward_differentiation_coefficients_;
}
const DoubleTab & Schema_Backward_Differentiation_base::coefficients () const [inline, virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 64 of file Schema_Backward_Differentiation_base.h.
References backward_differentiation_coefficients_.
Referenced by add_multi_timestep_data(), and modify_equation_parameters().
{
  return backward_differentiation_coefficients_;
}
virtual void Schema_Backward_Differentiation_base::compute_backward_differentiation_coefficients (double time_step, const DoubleTab & times) const [protected, pure virtual]
Implemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Referenced by compute_coefficients().
void Schema_Backward_Differentiation_base::compute_coefficients (double time_step, const DoubleTab & times) const [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 95 of file Schema_Backward_Differentiation_base.cpp.
References compute_backward_differentiation_coefficients().
{
  compute_backward_differentiation_coefficients(time_step,times);
}
virtual int Schema_Backward_Differentiation_base::duplique () const [pure virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Implemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
const Type_info * Schema_Backward_Differentiation_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 35 of file Schema_Backward_Differentiation_base.cpp.
const Type_info * Schema_Backward_Differentiation_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 35 of file Schema_Backward_Differentiation_base.cpp.
void Schema_Backward_Differentiation_base::mettre_a_jour_equation (Equation_base & eqn, const double & temps) [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 90 of file Schema_Backward_Differentiation_base.cpp.
References Equation_base::inconnue(), and Champ_Inc::mettre_a_jour().
{
  eqn.inconnue().mettre_a_jour(temps);
}
void Schema_Backward_Differentiation_base::modify_equation_parameters (Equation_base & eqn, DoubleTab & stored_parameters) [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 114 of file Schema_Backward_Differentiation_base.cpp.
References coefficients(), Schema_Temps_base::nb_pas_dt(), Schema_Implicite_Multi_TimeStep_base::nb_pas_dt_seuil(), Schema_Implicite_Multi_TimeStep_base::nb_valeurs_passees(), Navier_Stokes_std::pression(), ref_cast, sub_type, and Champ_Inc::valeurs().
{
  if (nb_pas_dt()>nb_pas_dt_seuil())
    {
      if (sub_type(Navier_Stokes_std,eqn))
        {
          Navier_Stokes_std& navier_stokes = ref_cast(Navier_Stokes_std,eqn);
          DoubleTab& pressure = navier_stokes.pression().valeurs(); //pressure at time tnplus1 that is to say P(n+1)
          DoubleTab  delta_pressure(pressure);
          delta_pressure -= stored_parameters; //contains P(n+1) - P(n)
          delta_pressure /= coefficients()[nb_valeurs_passees()+1]; //take into account time scheme coefficient
          pressure        = stored_parameters;
          pressure       += delta_pressure;
        }
    }
}
Sortie & Schema_Backward_Differentiation_base::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 53 of file Schema_Backward_Differentiation_base.cpp.
{
  return  Schema_Implicite_Multi_TimeStep_base::printOn(s);
}
Entree & Schema_Backward_Differentiation_base::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 74 of file Schema_Backward_Differentiation_base.cpp.
{
  return Schema_Implicite_Multi_TimeStep_base::readOn(s);
}
const Schema_Backward_Differentiation_base & Schema_Backward_Differentiation_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 35 of file Schema_Backward_Differentiation_base.cpp.
Schema_Backward_Differentiation_base & Schema_Backward_Differentiation_base::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 35 of file Schema_Backward_Differentiation_base.cpp.
void Schema_Backward_Differentiation_base::store_equation_parameters (Equation_base & eqn, DoubleTab & stored_parameters) [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 101 of file Schema_Backward_Differentiation_base.cpp.
References Schema_Temps_base::nb_pas_dt(), Schema_Implicite_Multi_TimeStep_base::nb_pas_dt_seuil(), Navier_Stokes_std::pression(), ref_cast, sub_type, and Champ_Inc::valeurs().
{
  if (nb_pas_dt()>nb_pas_dt_seuil())
    {
      if (sub_type(Navier_Stokes_std,eqn))
        {
          Navier_Stokes_std& navier_stokes = ref_cast(Navier_Stokes_std,eqn);
          stored_parameters = navier_stokes.pression().valeurs(); //store pressure at time tn
        }
    }
}
void Schema_Backward_Differentiation_base::update_time_derivative (Equation_base & eqn, const DoubleTab & data) [virtual]
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 85 of file Schema_Backward_Differentiation_base.cpp.
{
// Nothing to do
}
Member Data Documentation
DoubleTab Schema_Backward_Differentiation_base::backward_differentiation_coefficients_ [mutable, protected]
Definition at line 61 of file Schema_Backward_Differentiation_base.h.
Referenced by coefficients(), Schema_Backward_Differentiation_order_3::compute_backward_differentiation_coefficients(), and Schema_Backward_Differentiation_order_2::compute_backward_differentiation_coefficients().
const Type_info Schema_Backward_Differentiation_base::info_obj [static]
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Reimplemented in Schema_Backward_Differentiation_order_2, and Schema_Backward_Differentiation_order_3.
Definition at line 43 of file Schema_Backward_Differentiation_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Schemas_Temps/Schema_Backward_Differentiation_base.h
src/ThHyd/Schemas_Temps/Schema_Backward_Differentiation_base.cpp