TRUST: T_It_VDF_Elem< _TYPE_ > Class Template Reference
T_It_VDF_Elem< _TYPE_ > Class Template Reference
#include <T_It_VDF_Elem.h>
Public Member Functions
T_It_VDF_Elem ()
T_It_VDF_Elem (const T_It_VDF_Elem< _TYPE_ > &)
Evaluateur_VDF & evaluateur ()
const Evaluateur_VDF & evaluateur () const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
void calculer_flux_bord (const DoubleTab &) const
void contribuer_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_vitesse (const DoubleTab &, Matrice_Morse &) const
void completer_ ()
int impr (Sortie &os) const
void modifier_flux () const
Protected Member Functions
DoubleTab & ajouter_bords (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter_interne (const DoubleTab &, DoubleTab &) const
void contribuer_au_second_membre_bords (DoubleTab &) const
void contribuer_au_second_membre_interne (DoubleTab &) const
void ajouter_contribution_bords (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_interne (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_interne_vitesse (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_bords_vitesse (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_autre_pb (const DoubleTab &inco, Matrice_Morse &matrice, const Cond_lim &la_cl, std::map< int, std::pair< int, int >> &) const
const Milieu_base & milieu () const
Protected Attributes
_TYPE_ flux_evaluateur
IntTab elem
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Private Member Functions
int duplique () const
unsigned taille_memoire () const
Detailed Description
template<class _TYPE_>
class T_It_VDF_Elem< _TYPE_ >
Definition at line 49 of file T_It_VDF_Elem.h.
Constructor & Destructor Documentation
template<class _TYPE_> T_It_VDF_Elem< _TYPE_ >::T_It_VDF_Elem () [inline]
Definition at line 67 of file T_It_VDF_Elem.h.
Referenced by T_It_VDF_Elem< _TYPE_ >::duplique().
{ } ;
template<class _TYPE_ > T_It_VDF_Elem< _TYPE_ >::T_It_VDF_Elem (const T_It_VDF_Elem< _TYPE_ > & iter) [inline]
Definition at line 95 of file T_It_VDF_Elem.h.
References T_It_VDF_Elem< _TYPE_ >::elem, and IntTab::ref().
  :Iterateur_VDF_base(iter),
   flux_evaluateur(iter.flux_evaluateur)
{
  elem.ref(iter.elem);
}
Member Function Documentation
template<class _TYPE_ > DoubleTab & T_It_VDF_Elem< _TYPE_ >::ajouter (const DoubleTab & donne, DoubleTab & resu) const [virtual]
Implements Iterateur_VDF_base.
Definition at line 130 of file T_It_VDF_Elem.h.
References ArrOfDouble::addr(), DoubleVect::line_size(), DoubleTab::nb_dim(), DoubleTab::resize(), DoubleVect::size(), and ArrOfDouble::size_array().
{
  ((_TYPE_&) flux_evaluateur).mettre_a_jour();
  assert(donne.nb_dim() < 3);
  assert(la_zcl.non_nul());
  assert(la_zone.non_nul());
  const int ncomp = donne.line_size();
  DoubleTab& flux_bords=op_base->flux_bords();
  flux_bords.resize(la_zone->nb_faces_bord(),ncomp);
  flux_bords=0;
  /* modif b.m.: on va faire += sur des items virtuels, initialiser les cases */
  /* sinon risque que les cases soient invalides ou non initialisees */
  {
    int n = resu.size_array() - resu.size();
    double *data = resu.addr() + resu.size();
    for (; n; n--, data++)
      *data = 0.;
  }
  ajouter_bords(donne, resu) ;
  ajouter_interne(donne, resu) ;
  modifier_flux() ;
  return resu;
}
template<class _TYPE_ > DoubleTab & T_It_VDF_Elem< _TYPE_ >::ajouter_bords (const DoubleTab & donnee, DoubleTab & resu) const [protected]
< codage avec flux en DoubleVect auquel on assigne la valeur de la fonction scalaire (pas de codage vectoriel de nscbc)
Definition at line 155 of file T_It_VDF_Elem.h.
References Cerr, echange_externe_impose, echange_global_impose, entree_fluide, est_egal(), finl, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), DoubleVect::line_size(), Front_VF::nb_faces(), nscbc, Front_VF::num_premiere_face(), paroi, paroi_defilante, paroi_fixe, periodique, ref_cast, sortie_libre, sub_type, symetrie, and Deriv_Cond_lim_base::valeur().
{
  const int ncomp = resu.line_size();
  int elem1, elem2;
  int ndeb, nfin;
  int face,k;
  DoubleVect flux(ncomp);
  int num_cl=0;
  int nb_front_Cl=la_zone->nb_front_Cl();
  DoubleTab& flux_bords=op_base->flux_bords();
  for (; num_cl<nb_front_Cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      ndeb = frontiere_dis.num_premiere_face();
      nfin = ndeb + frontiere_dis.nb_faces();
      /* Test en bidim axi */
      if (bidim_axi && !sub_type(Symetrie,la_cl.valeur()))
        {
          if (nfin>ndeb && est_egal(la_zone.valeur().face_surfaces()[ndeb],0))
            {
              Cerr << "Error in the definition of the boundary conditions." << finl;
              Cerr << "The axis of revolution for this 2D calculation is along Y." << finl;
              Cerr << "So you must specify symmetry boundary condition (symetrie keyword) for the boundary " << frontiere_dis.le_nom() << finl;
              exit();
            }
        }
      switch(type_cl(la_cl))
        {
        case symetrie :
          if (flux_evaluateur.calculer_flux_faces_symetrie())
            {
              const Symetrie& cl =(const Symetrie&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case sortie_libre :
          if (flux_evaluateur.calculer_flux_faces_sortie_libre())
            {
              const Neumann_sortie_libre& cl =(const Neumann_sortie_libre&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case entree_fluide :
          if (flux_evaluateur.calculer_flux_faces_entree_fluide())
            {
              const Dirichlet_entree_fluide& cl =(const Dirichlet_entree_fluide&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi_fixe :
          if (flux_evaluateur.calculer_flux_faces_paroi_fixe())
            {
              const Dirichlet_paroi_fixe& cl =(const Dirichlet_paroi_fixe&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi_defilante :
          if (flux_evaluateur.calculer_flux_faces_paroi_defilante())
            {
              const Dirichlet_paroi_defilante& cl =(const Dirichlet_paroi_defilante&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi_adiabatique :
          if (flux_evaluateur.calculer_flux_faces_paroi_adiabatique())
            {
              const Neumann_paroi_adiabatique& cl =(const Neumann_paroi_adiabatique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  /* on initialise elem1 elem2 et on fait planter */
                  elem1=-1;
                  elem2=-1;
                  assert(0);
                  exit();
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi :
          if (flux_evaluateur.calculer_flux_faces_paroi())
            {
              const Neumann_paroi& cl =(const Neumann_paroi&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1, k)+=flux(k);
                        flux_bords(face, k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2, k)-=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case echange_externe_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_externe_impose())
            {
              const Echange_externe_impose& cl =(const Echange_externe_impose&) (la_cl.valeur());
              int boundary_index=-1;
              if (la_zone.valeur().front_VF(num_cl).le_nom() == frontiere_dis.le_nom())
                boundary_index=num_cl;
              for (face=ndeb; face<nfin; face++)
                {
                  int local_face=la_zone.valeur().front_VF(boundary_index).num_local_face(face);
                  flux_evaluateur.flux_face(donnee, boundary_index, face, local_face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case echange_global_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_global_impose())
            {
              const Echange_global_impose& cl =(const Echange_global_impose&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case nscbc :
          if (flux_evaluateur.calculer_flux_faces_NSCBC())
            {
              const NSCBC& cl =(const NSCBC&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  assert(ncomp == 1); //!< codage avec flux en DoubleVect auquel on assigne la valeur de la fonction scalaire (pas de codage vectoriel de nscbc)
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
// flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case periodique :
          if (flux_evaluateur.calculer_flux_faces_periodique())
            {
              const Periodique& cl =(const Periodique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=0.5*flux(k);
                        if ( face < (ndeb+frontiere_dis.nb_faces()/2) )
                          flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=0.5*flux(k);
                        if ( (ndeb+frontiere_dis.nb_faces()/2) <= face )
                          flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
          /*
                                                                            case nouvelle_Cl_VDF :
                                                                            if (flux_evaluateur.calculer_flux_faces_echange_global_impose()){
                                                                            const Nouvelle_Cl_VDF& cl =(const Nouvelle_Cl_VDF&) (la_cl.valeur());
                                                                            for (face=ndeb; face<nfin; face++) {
                                                                            flux_evaluateur.flux_face(donnee, face, cl, ndeb, flux);
                                                                            if ( (elem1=elem(face,0)) > -1)
                                                                            for (k=0; k<ncomp; k++)
                                                                            resu(elem1,k) +=flux(k);
                                                                            if ( (elem2=elem(face,1)) > -1)
                                                                            for (k=0; k<ncomp; k++)
                                                                            resu(elem2,k) -=flux(k);
                                                                            }
                                                                            }
                                                                            break;
          */
        default :
          Cerr << "On ne reconnait pas la condition limite : " << la_cl.valeur();
          exit();
          break;
        }
    }
  return resu;
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
Implements Iterateur_VDF_base.
Definition at line 1225 of file T_It_VDF_Elem.h.
References DoubleVect::line_size(), DoubleTab::nb_dim(), and DoubleTab::resize().
{
  ((_TYPE_&) flux_evaluateur).mettre_a_jour();
  assert(inco.nb_dim() < 3);
  assert(la_zcl.non_nul());
  assert(la_zone.non_nul());
  const int ncomp = inco.line_size();
  DoubleTab& flux_bords=op_base->flux_bords();
  flux_bords.resize(la_zone->nb_faces_bord(),ncomp);
  flux_bords=0;
  ajouter_contribution_bords(inco, matrice) ;
  ajouter_contribution_interne(inco, matrice) ;
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_autre_pb (const DoubleTab & inco, Matrice_Morse & matrice, const Cond_lim & la_cl, std::map< int, std::pair< int, int >> & f2e) const [protected, virtual]
Reimplemented from Iterateur_VDF_base.
Definition at line 1690 of file T_It_VDF_Elem.h.
References Cond_lim::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, and Deriv_Cond_lim_base::valeur().
{
  double aii=0, ajj=0;
  const Front_VF& frontiere_dis = ref_cast(Front_VF, la_cl.frontiere_dis());
  const int ndeb = frontiere_dis.num_premiere_face();
  const int nfin = ndeb + frontiere_dis.nb_faces();
// assert(cl est bien paroi contact)
  if (flux_evaluateur.calculer_flux_faces_echange_global_impose())
    {
      const Echange_global_impose& cl =(const Echange_global_impose&) (la_cl.valeur());
      for (int f = ndeb; f < nfin; f++)
        {
          flux_evaluateur.coeffs_face(f, ndeb, cl, aii, ajj);
          const int e1 = f2e[f].first, e2 = f2e[f].second;
          matrice(e1, e2) = -(elem(f, 0) > -1 ? aii : ajj);
        }
    }
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords (const DoubleTab & inco, Matrice_Morse & matrice) const [protected]
Definition at line 1264 of file T_It_VDF_Elem.h.
References Cerr, echange_externe_impose, echange_global_impose, entree_fluide, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), DoubleVect::line_size(), Front_VF::nb_faces(), nscbc, Front_VF::num_premiere_face(), paroi, paroi_defilante, paroi_fixe, periodique, ref_cast, sortie_libre, symetrie, and Deriv_Cond_lim_base::valeur().
{
  const int ncomp = inco.line_size();
  int elem1, elem2;
  DoubleVect aii(ncomp), ajj(ncomp);
  int ndeb, nfin;
  int face;
  int num_cl=0;
  int nb_front_Cl=la_zone->nb_front_Cl();
  for (; num_cl<nb_front_Cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      ndeb = frontiere_dis.num_premiere_face();
      nfin = ndeb + frontiere_dis.nb_faces();
      switch(type_cl(la_cl))
        {
        case symetrie :
          if (flux_evaluateur.calculer_flux_faces_symetrie())
            {
              const Symetrie& cl =(const Symetrie&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case sortie_libre :
          if (flux_evaluateur.calculer_flux_faces_sortie_libre())
            {
              const Neumann_sortie_libre& cl =(const Neumann_sortie_libre&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case entree_fluide :
          if (flux_evaluateur.calculer_flux_faces_entree_fluide())
            {
              const Dirichlet_entree_fluide& cl =(const Dirichlet_entree_fluide&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case paroi_fixe :
          if (flux_evaluateur.calculer_flux_faces_paroi_fixe())
            {
              const Dirichlet_paroi_fixe& cl =(const Dirichlet_paroi_fixe&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case paroi_defilante :
          if (flux_evaluateur.calculer_flux_faces_paroi_defilante())
            {
              const Dirichlet_paroi_defilante& cl =(const Dirichlet_paroi_defilante&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case paroi_adiabatique :
          if (flux_evaluateur.calculer_flux_faces_paroi_adiabatique())
            {
              const Neumann_paroi_adiabatique& cl =(const Neumann_paroi_adiabatique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case paroi :
          if (flux_evaluateur.calculer_flux_faces_paroi())
            {
              const Neumann_paroi& cl =(const Neumann_paroi&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case echange_externe_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_externe_impose())
            {
              const Echange_externe_impose& cl =(const Echange_externe_impose&) (la_cl.valeur());
              int boundary_index=-1;
              if (la_zone.valeur().front_VF(num_cl).le_nom() == frontiere_dis.le_nom())
                boundary_index=num_cl;
              for (face=ndeb; face<nfin; face++)
                {
                  int local_face=la_zone.valeur().front_VF(boundary_index).num_local_face(face);
                  flux_evaluateur.coeffs_face(boundary_index,face,local_face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case echange_global_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_global_impose())
            {
              const Echange_global_impose& cl =(const Echange_global_impose&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case nscbc :
          if (flux_evaluateur.calculer_flux_faces_NSCBC())
            {
              const NSCBC& cl =(const NSCBC&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
// codage scalaire applique aux DoubleVect
                  assert(ncomp == 1);
                  double aii_ = 0., ajj_ = 0.;
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii_, ajj_);
                  aii = aii_, ajj = ajj_;
                  if ( (elem1=elem(face,0)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem1*ncomp+i,elem1*ncomp+i)+=aii(i);
                  if ( (elem2=elem(face,1)) > -1)
                    for (int i = 0; i < ncomp; i++)
                      matrice(elem2*ncomp+i,elem2*ncomp+i)+=ajj(i);
                }
            }
          break;
        case periodique :
          if (flux_evaluateur.calculer_flux_faces_periodique())
            {
              const Periodique& cl =(const Periodique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.coeffs_face(face,ndeb, cl, aii, ajj);
                  elem1 = elem(face,0);
                  elem2 = elem(face,1);
                  for (int i = 0; i < ncomp; i++)
                    {
                      int n1=elem1*ncomp+i;
                      int n2=elem2*ncomp+i;
                      matrice(n1,n1)+=0.5*aii(i);
                      matrice(n1,n2)-=0.5*ajj(i);
                      matrice(n2,n2)+=0.5*ajj(i);
                      matrice(n2,n1)-=0.5*aii(i);
                    }
                }
            }
          break;
        default :
          Cerr << "On ne reconnait pas la condition limite : " << la_cl.valeur();
          exit();
          break;
        }
    }
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [protected]
Definition at line 1521 of file T_It_VDF_Elem.h.
References Cerr, echange_externe_impose, echange_global_impose, entree_fluide, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), nscbc, Front_VF::num_premiere_face(), paroi, paroi_defilante, paroi_fixe, periodique, ref_cast, sortie_libre, symetrie, and Deriv_Cond_lim_base::valeur().
{
  int e1, e2;
  double aef=0;
  int ndeb, nfin;
  int nb_front_Cl=la_zone->nb_front_Cl();
  for (int num_cl = 0; num_cl<nb_front_Cl; num_cl++)
    {
      /* pour chaque Condition Limite on regarde son type */
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      ndeb = frontiere_dis.num_premiere_face();
      nfin = ndeb + frontiere_dis.nb_faces();
      switch(type_cl(la_cl))
        {
        case symetrie :
          if (flux_evaluateur.calculer_flux_faces_symetrie())
            {
              const Symetrie& cl =(const Symetrie&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case sortie_libre :
          if (flux_evaluateur.calculer_flux_faces_sortie_libre())
            {
              const Neumann_sortie_libre& cl =(const Neumann_sortie_libre&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case entree_fluide :
          if (flux_evaluateur.calculer_flux_faces_entree_fluide())
            {
              const Dirichlet_entree_fluide& cl =(const Dirichlet_entree_fluide&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case paroi_fixe :
          if (flux_evaluateur.calculer_flux_faces_paroi_fixe())
            {
              const Dirichlet_paroi_fixe& cl =(const Dirichlet_paroi_fixe&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case paroi_defilante :
          if (flux_evaluateur.calculer_flux_faces_paroi_defilante())
            {
              const Dirichlet_paroi_defilante& cl =(const Dirichlet_paroi_defilante&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case paroi_adiabatique :
          if (flux_evaluateur.calculer_flux_faces_paroi_adiabatique())
            {
              const Neumann_paroi_adiabatique& cl =(const Neumann_paroi_adiabatique&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case paroi :
          if (flux_evaluateur.calculer_flux_faces_paroi())
            {
              const Neumann_paroi& cl =(const Neumann_paroi&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case echange_externe_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_externe_impose())
            {
              const Echange_externe_impose& cl =(const Echange_externe_impose&) (la_cl.valeur());
              int boundary_index=-1;
              if (la_zone.valeur().front_VF(num_cl).le_nom() == frontiere_dis.le_nom())
                boundary_index=num_cl;
              for (int f = ndeb; f < nfin; f++)
                {
                  int local_face=la_zone.valeur().front_VF(boundary_index).num_local_face(f);
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, boundary_index, f, local_face, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e1, f) -= aef;
                }
            }
          break;
        case echange_global_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_global_impose())
            {
              const Echange_global_impose& cl =(const Echange_global_impose&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case nscbc :
          if (flux_evaluateur.calculer_flux_faces_NSCBC())
            {
              const NSCBC& cl =(const NSCBC&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1) matrice(e1, f) += aef;
                  if ( (e2 = elem(f, 1)) > -1) matrice(e2, f) -= aef;
                }
            }
          break;
        case periodique :
          if (flux_evaluateur.calculer_flux_faces_periodique())
            {
              const Periodique& cl =(const Periodique&) (la_cl.valeur());
              for (int f = ndeb; f < nfin; f++)
                {
                  aef = flux_evaluateur.coeffs_face_bloc_vitesse(inco, f, cl, ndeb);
                  if ( (e1 = elem(f, 0)) > -1)
                    {
                      if ( f < (ndeb+frontiere_dis.nb_faces()/2) )
                        matrice(e1, f) += aef;
                    }
                  if ( (e2 = elem(f, 1)) > -1)
                    {
                      if ( (ndeb+frontiere_dis.nb_faces()/2) <= f )
                        matrice(e2, f) -= aef;
                    }
                }
            }
          break;
        default :
          Cerr << "On ne reconnait pas la condition limite : " << la_cl.valeur();
          exit();
          break;
        }
    }
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne (const DoubleTab & inco, Matrice_Morse & matrice) const [protected]
Definition at line 1480 of file T_It_VDF_Elem.h.
References DoubleVect::line_size(), Zone_VF::nb_faces(), and Zone_VF::premiere_face_int().
{
  const int ncomp = inco.line_size();
  const Zone_VDF& zone_VDF = la_zone.valeur();
  int face,i;
  DoubleVect aii(ncomp), ajj(ncomp);
  int elem1,elem2;
  int ndeb=zone_VDF.premiere_face_int();
  int nfin=zone_VDF.nb_faces();
  for (face=ndeb; face<nfin; face++)
    {
      elem1 = elem(face,0);
      elem2 = elem(face,1);
      flux_evaluateur.coeffs_faces_interne(face, aii, ajj);
      for (i=0; i<ncomp; i++)
        {
          int i0=elem1*ncomp+i,j0=elem2*ncomp+i;
          matrice(i0,i0)+=aii(i) ;
          matrice(i0,j0)-=ajj(i) ;
          matrice(j0,j0)+=ajj(i) ;
          matrice(j0,i0)-=aii(i) ;
        }
    }
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_interne_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [protected]
Definition at line 1505 of file T_It_VDF_Elem.h.
References Zone_VF::nb_faces(), and Zone_VF::premiere_face_int().
{
  const Zone_VDF& zone_VDF = la_zone.valeur();
  double aef = 0;
  const int ndeb = zone_VDF.premiere_face_int();
  const int nfin = zone_VDF.nb_faces();
  for (int f = ndeb; f < nfin; f++)
    {
      const int e1 = elem(f, 0);
      const int e2 = elem(f, 1);
      aef = flux_evaluateur.coeffs_faces_interne_bloc_vitesse(inco, f);
      matrice(e1, f) += aef;
      matrice(e2, f) -= aef;
    }
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::ajouter_contribution_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
Implements Iterateur_VDF_base.
Definition at line 1239 of file T_It_VDF_Elem.h.
References DoubleTab::dimension(), and DoubleTab::nb_dim().
{
  ((_TYPE_&) flux_evaluateur).mettre_a_jour();
  assert(inco.nb_dim() < 3);
  assert(la_zcl.non_nul());
  assert(la_zone.non_nul());
  int ncomp=1;
  if (inco.nb_dim() == 2)
    ncomp=inco.dimension(1);
// DoubleTab& flux_bords=op_base->flux_bords();
// flux_bords.resize(la_zone->nb_faces_bord(),ncomp);
// flux_bords=0;
  if( ncomp == 1) /* cas scalaire */
    {
      ajouter_contribution_bords_vitesse(inco, matrice);
      ajouter_contribution_interne_vitesse(inco, matrice);
    }
  else /* cas vectoriel */
    {
      abort();
// ajouter_contribution_bords(inco, matrice, ncomp) ;
// ajouter_contribution_interne(inco, matrice, ncomp) ;
    }
}
template<class _TYPE_ > DoubleTab & T_It_VDF_Elem< _TYPE_ >::ajouter_interne (const DoubleTab & donnee, DoubleTab & resu) const [protected]
Definition at line 731 of file T_It_VDF_Elem.h.
References DoubleVect::line_size(), Zone_VF::nb_faces(), and Zone_VF::premiere_face_int().
{
  const int ncomp = resu.line_size();
  const Zone_VDF& zone_VDF = la_zone.valeur();
  DoubleVect flux(ncomp);
  int face,k;
  int elem0,elem1;
  int ndeb = zone_VDF.premiere_face_int();
  int nfin = zone_VDF.nb_faces();
  for (face=ndeb; face<nfin; face++)
    {
      flux_evaluateur.flux_faces_interne(donnee, face, flux);
      elem0 = elem(face,0);
      elem1 = elem(face,1);
      for (k=0; k<ncomp; k++)
        {
          resu(elem0,k)+=flux(k);
          resu(elem1,k)-=flux(k);
        }
    }
  return resu;
}
template<class _TYPE_ > DoubleTab & T_It_VDF_Elem< _TYPE_ >::calculer (const DoubleTab & inco, DoubleTab & resu) const [virtual]
Implements Iterateur_VDF_base.
Definition at line 754 of file T_It_VDF_Elem.h.
References ajouter(), operator_egal(), and VECT_REAL_ITEMS.
{
  operator_egal(resu, 0., VECT_REAL_ITEMS);
  return ajouter(inco,resu);
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord (const DoubleTab & donnee) const [virtual]
Reimplemented from Iterateur_VDF_base.
Definition at line 467 of file T_It_VDF_Elem.h.
References Cerr, echange_externe_impose, echange_global_impose, entree_fluide, est_egal(), Process::exit(), finl, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), DoubleVect::line_size(), DoubleTab::nb_dim(), Front_VF::nb_faces(), nscbc, Front_VF::num_premiere_face(), paroi, paroi_defilante, paroi_fixe, periodique, ref_cast, DoubleTab::resize(), sortie_libre, sub_type, symetrie, and Deriv_Cond_lim_base::valeur().
{
  ((_TYPE_&) flux_evaluateur).mettre_a_jour();
  assert(donnee.nb_dim() < 3);
  assert(la_zcl.non_nul());
  assert(la_zone.non_nul());
  const int ncomp = donnee.line_size();
  DoubleTab& flux_bords=op_base->flux_bords();
  flux_bords.resize(la_zone->nb_faces_bord(),ncomp);
  flux_bords=0;
  if( ncomp != 1) Process ::exit();/* cas scalaire */
  int ndeb, nfin;
  int face;
  int num_cl=0;
  double flux;
  int nb_front_Cl=la_zone->nb_front_Cl();
  for (; num_cl<nb_front_Cl; num_cl++)
    {
      /* pour chaque Condition Limite on regarde son type */
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      ndeb = frontiere_dis.num_premiere_face();
      nfin = ndeb + frontiere_dis.nb_faces();
      /* Test en bidim axi */
      if (bidim_axi && !sub_type(Symetrie,la_cl.valeur()))
        {
          if (nfin>ndeb && est_egal(la_zone.valeur().face_surfaces()[ndeb],0))
            {
              Cerr << "Error in the definition of the boundary conditions." << finl;
              Cerr << "The axis of revolution for this 2D calculation is along Y." << finl;
              Cerr << "So you must specify symmetry boundary condition (symetrie keyword) for the boundary " << frontiere_dis.le_nom() << finl;
              exit();
            }
        }
      switch(type_cl(la_cl))
        {
        case symetrie :
          if (flux_evaluateur.calculer_flux_faces_symetrie())
            {
              const Symetrie& cl =(const Symetrie&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case sortie_libre :
          if (flux_evaluateur.calculer_flux_faces_sortie_libre())
            {
              const Neumann_sortie_libre& cl =(const Neumann_sortie_libre&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case entree_fluide :
          if (flux_evaluateur.calculer_flux_faces_entree_fluide())
            {
              const Dirichlet_entree_fluide& cl =(const Dirichlet_entree_fluide&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case paroi_fixe :
          if (flux_evaluateur.calculer_flux_faces_paroi_fixe())
            {
              const Dirichlet_paroi_fixe& cl =(const Dirichlet_paroi_fixe&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case paroi_defilante :
          if (flux_evaluateur.calculer_flux_faces_paroi_defilante())
            {
              const Dirichlet_paroi_defilante& cl =(const Dirichlet_paroi_defilante&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case paroi_adiabatique :
          if (flux_evaluateur.calculer_flux_faces_paroi_adiabatique())
            {
              const Neumann_paroi_adiabatique& cl =(const Neumann_paroi_adiabatique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  assert(0);
                  exit();
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  flux_bords(face,0)+=flux;
                  flux_bords(face,0)-=flux;
                }
            }
          break;
        case paroi :
          if (flux_evaluateur.calculer_flux_faces_paroi())
            {
              const Neumann_paroi& cl =(const Neumann_paroi&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case echange_externe_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_externe_impose())
            {
              const Echange_externe_impose& cl =(const Echange_externe_impose&) (la_cl.valeur());
              int boundary_index=-1;
              if (la_zone.valeur().front_VF(num_cl).le_nom() == frontiere_dis.le_nom())
                boundary_index=num_cl;
              for (face=ndeb; face<nfin; face++)
                {
                  int local_face=la_zone.valeur().front_VF(boundary_index).num_local_face(face);
                  flux = flux_evaluateur.flux_face(donnee, boundary_index,face,local_face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case echange_global_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_global_impose())
            {
              const Echange_global_impose& cl =(const Echange_global_impose&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case nscbc :
          if (flux_evaluateur.calculer_flux_faces_NSCBC())
            {
              const NSCBC& cl =(const NSCBC&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
        case periodique :
          if (flux_evaluateur.calculer_flux_faces_periodique())
            {
              const Periodique& cl =(const Periodique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux = flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                  if ( (elem(face,0)) > -1)
                    {
                      if ( face < (ndeb+frontiere_dis.nb_faces()/2) )
                        flux_bords(face,0)+=flux;
                    }
                  if ( (elem(face,1)) > -1)
                    {
                      if ( (ndeb+frontiere_dis.nb_faces()/2) <= face )
                        flux_bords(face,0)-=flux;
                    }
                }
            }
          break;
          /*
                                                                            case nouvelle_Cl_VDF :
                                                                            if (flux_evaluateur.calculer_flux_faces_echange_global_impose()){
                                                                            const Nouvelle_Cl_VDF& cl =(const Nouvelle_Cl_VDF&) (la_cl.valeur());
                                                                            for (face=ndeb; face<nfin; face++) {
                                                                            if ( (int elem1=elem(face,0)) > -1)
                                                                            resu[elem1]+=flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                                                                            if ( (int elem2=elem(face,1)) > -1)
                                                                            resu[elem2]-=flux_evaluateur.flux_face(donnee, face, cl, ndeb);
                                                                            }
                                                                            }
                                                                            break;
          */
        default :
          Cerr << "On ne reconnait pas la condition limite : " << la_cl.valeur();
          Cerr << "Dans T_It_VDF_Elem<_TYPE_>::ajouter_bords"<<finl;
          exit();
          break;
        }
    }
  modifier_flux() ;
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::completer_ () [inline, virtual]
Implements Iterateur_VDF_base.
Definition at line 120 of file T_It_VDF_Elem.h.
{
  elem.ref(la_zone->face_voisins());
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre (DoubleTab & resu) const [virtual]
Implements Iterateur_VDF_base.
Definition at line 900 of file T_It_VDF_Elem.h.
References DoubleTab::nb_dim().
{
  ((_TYPE_&) flux_evaluateur).mettre_a_jour();
  assert(resu.nb_dim() < 3);
  assert(la_zcl.non_nul());
  assert(la_zone.non_nul());
  assert(op_base->flux_bords().dimension(0)==la_zone->nb_faces_bord()); /* resize deja fait */
  contribuer_au_second_membre_bords(resu) ;
  contribuer_au_second_membre_interne(resu) ;
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_bords (DoubleTab & resu) const [protected]
< codage avec flux en DoubleVect auquel on assigne la valeur de la fonction scalaire (pas de codage vectoriel de nscbc)
Definition at line 910 of file T_It_VDF_Elem.h.
References Cerr, echange_externe_impose, echange_global_impose, entree_fluide, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), DoubleVect::line_size(), Front_VF::nb_faces(), nscbc, Front_VF::num_premiere_face(), paroi, paroi_defilante, paroi_fixe, periodique, ref_cast, sortie_libre, symetrie, and Deriv_Cond_lim_base::valeur().
{
  const int ncomp = resu.line_size();
  int elem1, elem2;
  int ndeb, nfin;
  int face,k;
  DoubleVect flux(ncomp);
  int num_cl=0;
  int nb_front_Cl=la_zone->nb_front_Cl();
  DoubleTab& flux_bords=op_base->flux_bords();
  for (; num_cl<nb_front_Cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      ndeb = frontiere_dis.num_premiere_face();
      nfin = ndeb + frontiere_dis.nb_faces();
      switch(type_cl(la_cl))
        {
        case symetrie :
          if (flux_evaluateur.calculer_flux_faces_symetrie())
            {
              const Symetrie& cl =(const Symetrie&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case sortie_libre :
          if (flux_evaluateur.calculer_flux_faces_sortie_libre())
            {
              const Neumann_sortie_libre& cl =(const Neumann_sortie_libre&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case entree_fluide :
          if (flux_evaluateur.calculer_flux_faces_entree_fluide())
            {
              const Dirichlet_entree_fluide& cl =(const Dirichlet_entree_fluide&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi_fixe :
          if (flux_evaluateur.calculer_flux_faces_paroi_fixe())
            {
              const Dirichlet_paroi_fixe& cl =(const Dirichlet_paroi_fixe&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi_defilante :
          if (flux_evaluateur.calculer_flux_faces_paroi_defilante())
            {
              const Dirichlet_paroi_defilante& cl =(const Dirichlet_paroi_defilante&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi_adiabatique :
          if (flux_evaluateur.calculer_flux_faces_paroi_adiabatique())
            {
              const Neumann_paroi_adiabatique& cl =(const Neumann_paroi_adiabatique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case paroi :
          if (flux_evaluateur.calculer_flux_faces_paroi())
            {
              const Neumann_paroi& cl =(const Neumann_paroi&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case echange_externe_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_externe_impose())
            {
              const Echange_externe_impose& cl =(const Echange_externe_impose&) (la_cl.valeur());
              int boundary_index=-1;
              if (la_zone.valeur().front_VF(num_cl).le_nom() == frontiere_dis.le_nom())
                boundary_index=num_cl;
              for (face=ndeb; face<nfin; face++)
                {
                  int local_face=la_zone.valeur().front_VF(boundary_index).num_local_face(face);
                  flux_evaluateur.secmem_face(boundary_index,face,local_face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case echange_global_impose :
          if (flux_evaluateur.calculer_flux_faces_echange_global_impose())
            {
              const Echange_global_impose& cl =(const Echange_global_impose&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case nscbc :
          if (flux_evaluateur.calculer_flux_faces_NSCBC())
            {
              const NSCBC& cl =(const NSCBC&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  assert(ncomp == 1); //!< codage avec flux en DoubleVect auquel on assigne la valeur de la fonction scalaire (pas de codage vectoriel de nscbc)
                  flux = flux_evaluateur.secmem_face(face, cl, ndeb);
// flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=flux(k);
                        flux_bords(face,k)+=flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=flux(k);
                        flux_bords(face,k)-=flux(k);
                      }
                }
            }
          break;
        case periodique :
          if (flux_evaluateur.calculer_flux_faces_periodique())
            {
              const Periodique& cl =(const Periodique&) (la_cl.valeur());
              for (face=ndeb; face<nfin; face++)
                {
                  flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                  if ( (elem1=elem(face,0)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem1,k) +=0.5*flux(k);
                        flux_bords(face,k)+=0.5*flux(k);
                      }
                  if ( (elem2=elem(face,1)) > -1)
                    for (k=0; k<ncomp; k++)
                      {
                        resu(elem2,k) -=0.5*flux(k);
                        flux_bords(face,k)-=0.5*flux(k);
                      }
                }
            }
          break;
          /*
                                                                            case nouvelle_Cl_VDF :
                                                                            if (flux_evaluateur.calculer_flux_faces_echange_global_impose()){
                                                                            const Nouvelle_Cl_VDF& cl =(const Nouvelle_Cl_VDF&) (la_cl.valeur());
                                                                            for (face=ndeb; face<nfin; face++) {
                                                                            flux_evaluateur.secmem_face(face, cl, ndeb, flux);
                                                                            if ( (elem1=elem(face,0)) > -1)
                                                                            for (k=0; k<ncomp; k++)
                                                                            resu(elem1,k) +=flux(k);
                                                                            if ( (elem2=elem(face,1)) > -1)
                                                                            for (k=0; k<ncomp; k++)
                                                                            resu(elem2,k) -=flux(k);
                                                                            }
                                                                            }
                                                                            break;
          */
        default :
          Cerr << "On ne reconnait pas la condition limite : " << la_cl.valeur();
          exit();
          break;
        }
    }
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::contribuer_au_second_membre_interne (DoubleTab & resu) const [protected]
Definition at line 1202 of file T_It_VDF_Elem.h.
References DoubleVect::line_size(), Zone_VF::nb_faces(), and Zone_VF::premiere_face_int().
{
  const int ncomp = resu.line_size();
  const Zone_VDF& zone_VDF = la_zone.valeur();
  DoubleVect flux(ncomp);
  int face,k;
  int elem0,elem1;
  int ndeb=zone_VDF.premiere_face_int();
  int nfin=zone_VDF.nb_faces();
  for (face=ndeb; face<nfin; face++)
    {
      flux_evaluateur.secmem_faces_interne(face, flux);
      elem0 = elem(face,0);
      elem1 = elem(face,1);
      for (k=0; k<ncomp; k++)
        {
          resu(elem0,k)+=flux(k);
          resu(elem1,k)-=flux(k);
        }
    }
}
template<class _TYPE_> int T_It_VDF_Elem< _TYPE_ >::duplique () const [inline, private, virtual]
Implements Iterateur_VDF_base.
Definition at line 52 of file T_It_VDF_Elem.h.
References Cerr, Process::exit(), finl, Objet_U::numero(), and T_It_VDF_Elem< _TYPE_ >::T_It_VDF_Elem().
  {
    T_It_VDF_Elem* xxx = new  T_It_VDF_Elem(*this);
    if(!xxx)
      {
        Cerr << "Not enough memory " << finl;
        exit();
      }
    return xxx->numero();
  };
template<class _TYPE_ > const Evaluateur_VDF & T_It_VDF_Elem< _TYPE_ >::evaluateur () const [inline, virtual]
Implements Iterateur_VDF_base.
Definition at line 106 of file T_It_VDF_Elem.h.
{
  Evaluateur_VDF& eval = (Evaluateur_VDF&) flux_evaluateur;
  return eval;
}
template<class _TYPE_ > Evaluateur_VDF & T_It_VDF_Elem< _TYPE_ >::evaluateur () [inline, virtual]
Implements Iterateur_VDF_base.
Definition at line 101 of file T_It_VDF_Elem.h.
{
  Evaluateur_VDF& eval = (Evaluateur_VDF&) flux_evaluateur;
  return eval;
}
template<class _TYPE_ > int T_It_VDF_Elem< _TYPE_ >::impr (Sortie & os) const [virtual]
Implements Iterateur_VDF_base.
Definition at line 800 of file T_It_VDF_Elem.h.
References DoubleTab::dimension(), est_egal(), Zone_VF::face_surfaces(), finl, Cond_lim::frontiere_dis(), Frontiere_dis_base::le_nom(), LIST, mp_sum_for_each_item(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), periodique, ref_cast, EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
{
  const Zone_VDF& la_zone_vdf=ref_cast(Zone_VDF,op_base.valeur().equation().zone_dis().valeur());
  const Zone& mazone=la_zone->zone();
  const int impr_bord=(mazone.Bords_a_imprimer().est_vide() ? 0:1);
  const Schema_Temps_base& sch = la_zcl->equation().probleme().schema_temps();
  double temps = sch.temps_courant();
  DoubleTab& flux_bords=op_base->flux_bords();
  DoubleVect bilan(flux_bords.dimension(1));
  int k,face;
  int nb_front_Cl=la_zone->nb_front_Cl();
  DoubleTrav flux_bords2( 3, nb_front_Cl , flux_bords.dimension(1)) ;
  flux_bords2=0;
  /*flux_bord(k)          ->   flux_bords2(0,num_cl,k) */
  /*flux_bord_perio1(k)   ->   flux_bords2(1,num_cl,k) */
  /*flux_bord_perio2(k)   ->   flux_bords2(2,num_cl,k) */
  for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
    {
      const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      int ndeb = frontiere_dis.num_premiere_face();
      int nfin = ndeb + frontiere_dis.nb_faces();
      int periodicite = (type_cl(la_cl)==periodique?1:0);
      for (face=ndeb; face<nfin; face++)
        for(k=0; k<flux_bords.dimension(1); k++)
          {
            flux_bords2(0,num_cl,k)+=flux_bords(face, k);
            if(periodicite)
              {
                if( face < (ndeb+frontiere_dis.nb_faces()/2) )
                  flux_bords2(1,num_cl,k)+=flux_bords(face, k);
                else
                  flux_bords2(2,num_cl,k)+=flux_bords(face, k);
              }
          }
    } /* fin for num_cl */
  mp_sum_for_each_item(flux_bords2);
  if (je_suis_maitre())
    {
      op_base->ouvrir_fichier(Flux,"",1);
      Flux.add_col(temps);
      for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
        {
          const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
          int periodicite = (type_cl(la_cl)==periodique?1:0);
          for(k=0; k<flux_bords.dimension(1); k++)
            {
              bilan(k)+=flux_bords2(0,num_cl,k);
              if(periodicite)
                {
                  Flux.add_col(flux_bords2(1,num_cl,k));
                  Flux.add_col(flux_bords2(2,num_cl,k));
                }
              else
                Flux.add_col(flux_bords2(0,num_cl,k));
            }
        }
      for(k=0; k<flux_bords.dimension(1); k++)
        Flux.add_col(bilan(k));
      Flux << finl;
    }
  const LIST(Nom)& Liste_Bords_a_imprimer = la_zone->zone().Bords_a_imprimer();
  if (!Liste_Bords_a_imprimer.est_vide())
    {
      EcrFicPartage Flux_face;
      op_base->ouvrir_fichier_partage(Flux_face,"",impr_bord);
      for (int num_cl=0; num_cl<nb_front_Cl; num_cl++)
        {
          const Frontiere_dis_base& la_fr = la_zcl->les_conditions_limites(num_cl).frontiere_dis();
          const Cond_lim& la_cl = la_zcl->les_conditions_limites(num_cl);
          const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
          int ndeb = frontiere_dis.num_premiere_face();
          int nfin = ndeb + frontiere_dis.nb_faces();
          if (mazone.Bords_a_imprimer().contient(la_fr.le_nom()))
            {
              Flux_face << "# Flux par face sur " << la_fr.le_nom() << " au temps " << temps << " : " << finl;
              for (face=ndeb; face<nfin; face++)
                {
                  if (dimension == 2)
                    Flux_face << "# Face a x= " << la_zone->xv(face,0) << " y= " << la_zone->xv(face,1);
                  else if (dimension == 3)
                    Flux_face << "# Face a x= " << la_zone->xv(face,0) << " y= " << la_zone->xv(face,1) << " z= " << la_zone->xv(face,2);
                  for(k=0; k<flux_bords.dimension(1); k++)
                    {
                      if (!est_egal(la_zone_vdf.face_surfaces(face),0., 1.e-20))
{
                          Flux_face << " surface_face(m2)= " << la_zone_vdf.face_surfaces(face) ;
                          Flux_face << " flux_par_surface(W/m2)= "  << flux_bords(face, k)/la_zone_vdf.face_surfaces(face) ;
                        }
                      Flux_face << " flux(W)= " << flux_bords(face, k) ;
                    }
                  Flux_face << finl;
                }
              Flux_face.syncfile();
            }
        }
    }
  return 1;
}
template<class _TYPE_ > const Milieu_base & T_It_VDF_Elem< _TYPE_ >::milieu () const [protected]
Definition at line 125 of file T_It_VDF_Elem.h.
{
  return (la_zcl->equation()).milieu();
}
template<class _TYPE_ > void T_It_VDF_Elem< _TYPE_ >::modifier_flux () const
Definition at line 759 of file T_It_VDF_Elem.h.
References Zone_VF::face_voisins(), Champ_Don::nb_comp(), Zone_VF::nb_faces_bord(), ref_cast, sub_type, and Deriv_Champ_Don_base::valeur().
{
  if (op_base->equation().inconnue().le_nom().debute_par("temperature")
      && !( sub_type(Operateur_Diff_base,op_base.valeur()) && ref_cast(Operateur_Diff_base,op_base.valeur()).diffusivite().le_nom() == "conductivite" ) )
    {
      DoubleTab& flux_bords=op_base->flux_bords();
      const Zone_VDF& la_zone_vdf=ref_cast(Zone_VDF,op_base->equation().zone_dis().valeur());
      const Champ_base& rho = (op_base->equation()).milieu().masse_volumique();
      const Champ_Don& Cp = (op_base->equation()).milieu().capacite_calorifique();
      const IntTab& face_voisins=la_zone_vdf.face_voisins();
      int rho_uniforme=(sub_type(Champ_Uniforme,rho) ? 1:0);
      int cp_uniforme=(sub_type(Champ_Uniforme,Cp.valeur()) ? 1:0);
      int is_rho_u=op_base->equation().probleme().is_dilatable();
      if (is_rho_u)
        {
          const Operateur_base& op=op_base.valeur();
          is_rho_u=0;
          if (sub_type(Op_Conv_VDF_base,op))
            if (ref_cast(Op_Conv_VDF_base,op).vitesse().le_nom()=="rho_u")
              is_rho_u=1;
        }
      double Cp_=0,rho_=0;
      const int& nb_faces_bords=la_zone_vdf.nb_faces_bord();
      for (int face=0; face<nb_faces_bords; face++)
        {
          int num_elem=face_voisins(face,0);
          if (num_elem == -1) num_elem = face_voisins(face,1);
          if (cp_uniforme) Cp_=Cp(0,0);
          else if (Cp.nb_comp()==1) Cp_=Cp(num_elem);
          else Cp_=Cp(num_elem,0);
          if (rho_uniforme) rho_=rho(0,0);
          else if (rho.nb_comp()==1) rho_=rho(num_elem);
          else rho_=rho(num_elem,0);
          /* si on est en QC temperature on a calcule div(rhou * T) */
          /* il ne faut pas remultiplier par rho */
          if (is_rho_u) rho_=1;
          flux_bords(face,0) *= (rho_*Cp_);
        }
    }
}
template<class _TYPE_> unsigned T_It_VDF_Elem< _TYPE_ >::taille_memoire () const [inline, private, virtual]
Implements Objet_U.
Definition at line 62 of file T_It_VDF_Elem.h.
  {
    throw;
  };
Member Data Documentation
template<class _TYPE_> IntTab T_It_VDF_Elem< _TYPE_ >::elem [protected]
Definition at line 92 of file T_It_VDF_Elem.h.
Referenced by T_It_VDF_Elem< _TYPE_ >::T_It_VDF_Elem().
template<class _TYPE_> SFichier T_It_VDF_Elem< _TYPE_ >::Flux [mutable, protected]
Definition at line 93 of file T_It_VDF_Elem.h.
template<class _TYPE_> _TYPE_ T_It_VDF_Elem< _TYPE_ >::flux_evaluateur [protected]
Definition at line 81 of file T_It_VDF_Elem.h.
template<class _TYPE_> SFichier T_It_VDF_Elem< _TYPE_ >::Flux_moment [mutable, protected]
Definition at line 93 of file T_It_VDF_Elem.h.
template<class _TYPE_> SFichier T_It_VDF_Elem< _TYPE_ >::Flux_sum [mutable, protected]
Definition at line 93 of file T_It_VDF_Elem.h.
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Iterateurs/T_It_VDF_Elem.h