TRUST: Sous_zone_dis_base Class Reference
Sous_zone_dis_base Class Reference
#include <Sous_zone_dis_base.h>
Public Member Functions
Sous_zone_dis_base ()
~Sous_zone_dis_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_sous_zone (const Sous_Zone &)
Associe une Sous_Zone a l'objet.
const Sous_Zone & sous_zone () const
Sous_Zone & sous_zone ()
void associer_zone_dis (const Zone_dis_base &)
Associe une Zone_dis a l'objet.
const Zone_dis_base & zone_dis () const
Zone_dis_base & zone_dis ()
int nb_elem_tot () const
int operator() (int i) const
int operator[] (int i) const
virtual void discretiser ()=0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Sous_zone_dis_base & self_cast (Objet_U &)
static const Sous_zone_dis_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
Ref_Sous_Zone la_sous_zone
Ref_Zone_dis_base la_zone_dis
Detailed Description
Au moment de la discretisation du domaine, de meme qu'une Zone_dis est creee pour chaque zone, une Sous_zone_dis est creee pour chaque Sous_Zone et discretisee.
Les classes qui heritent de Sous_zone_dis_base doivent surcharger la methode discretiser();
La Sous_Zone definit un sous-ensemble des elements de la Zone. De meme, la Sous_zone_dis definit un sous_ensemble des attributs de la Zone_dis, en particulier des faces.
Voir aussi Domaine_dis, Sous_Zone, Zone_dis_base, Sous_Zone_VF ! Cette classe est a la base de la hierarchie des sous-zones discretisees.
Definition at line 47 of file Sous_zone_dis_base.h.
Constructor & Destructor Documentation
Sous_zone_dis_base::Sous_zone_dis_base ()
Definition at line 25 of file Sous_zone_dis_base.cpp.
Sous_zone_dis_base::~Sous_zone_dis_base ()
Definition at line 25 of file Sous_zone_dis_base.cpp.
Member Function Documentation
void Sous_zone_dis_base::associer_sous_zone (const Sous_Zone & une_sous_zone)
Associe une Sous_Zone a l'objet.
Definition at line 41 of file Sous_zone_dis_base.cpp.
References la_sous_zone.
Referenced by Sous_zone_dis::associer_sous_zone().
{
  la_sous_zone=une_sous_zone;
}
void Sous_zone_dis_base::associer_zone_dis (const Zone_dis_base & une_zone_dis)
Associe une Zone_dis a l'objet.
Definition at line 48 of file Sous_zone_dis_base.cpp.
References la_zone_dis.
Referenced by Sous_zone_dis::associer_zone_dis().
{
  la_zone_dis=une_zone_dis;
}
virtual void Sous_zone_dis_base::discretiser () [pure virtual]
Implemented in Sous_zone_VF.
Referenced by Sous_zone_dis::discretiser().
virtual int Sous_zone_dis_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Sous_zone_VF.
const Type_info * Sous_zone_dis_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 25 of file Sous_zone_dis_base.cpp.
const Type_info * Sous_zone_dis_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 25 of file Sous_zone_dis_base.cpp.
int Sous_zone_dis_base::nb_elem_tot () const [inline]
Definition at line 74 of file Sous_zone_dis_base.h.
References la_sous_zone.
  {
    return la_sous_zone->nb_elem_tot();
  }
int Sous_zone_dis_base::operator() (int i) const [inline]
Definition at line 78 of file Sous_zone_dis_base.h.
References la_sous_zone, and Ref_Sous_Zone::valeur().
  {
    return la_sous_zone.valeur()(i);
  }
int Sous_zone_dis_base::operator[] (int i) const [inline]
Definition at line 82 of file Sous_zone_dis_base.h.
References la_sous_zone, and Ref_Sous_Zone::valeur().
  {
    return la_sous_zone.valeur()[i];
  }
Sortie & Sous_zone_dis_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 28 of file Sous_zone_dis_base.cpp.
{
  return os ;
}
Entree & Sous_zone_dis_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 34 of file Sous_zone_dis_base.cpp.
{
  return is ;
}
const Sous_zone_dis_base & Sous_zone_dis_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 25 of file Sous_zone_dis_base.cpp.
Sous_zone_dis_base & Sous_zone_dis_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 25 of file Sous_zone_dis_base.cpp.
Sous_Zone& Sous_zone_dis_base::sous_zone () [inline]
Definition at line 59 of file Sous_zone_dis_base.h.
References la_sous_zone, and Ref_Sous_Zone::valeur().
  {
    return la_sous_zone.valeur();
  }
const Sous_Zone& Sous_zone_dis_base::sous_zone () const [inline]
Definition at line 55 of file Sous_zone_dis_base.h.
References la_sous_zone, and Ref_Sous_Zone::valeur().
  {
    return la_sous_zone.valeur();
  }
const Zone_dis_base& Sous_zone_dis_base::zone_dis () const [inline]
Definition at line 64 of file Sous_zone_dis_base.h.
References la_zone_dis, and Ref_Zone_dis_base::valeur().
  {
    return la_zone_dis.valeur();
  }
Zone_dis_base& Sous_zone_dis_base::zone_dis () [inline]
Definition at line 68 of file Sous_zone_dis_base.h.
References la_zone_dis, and Ref_Zone_dis_base::valeur().
  {
    return la_zone_dis.valeur();
  }
Member Data Documentation
const Type_info Sous_zone_dis_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Sous_zone_VF.
Definition at line 49 of file Sous_zone_dis_base.h.
Ref_Sous_Zone Sous_zone_dis_base::la_sous_zone [protected]
Definition at line 92 of file Sous_zone_dis_base.h.
Referenced by associer_sous_zone(), Sous_zone_VF::discretiser(), nb_elem_tot(), operator()(), operator[](), and sous_zone().
Ref_Zone_dis_base Sous_zone_dis_base::la_zone_dis [protected]
Definition at line 93 of file Sous_zone_dis_base.h.
Referenced by associer_zone_dis(), Sous_zone_VF::discretiser(), and zone_dis().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sous_zone_dis_base.h
src/Kernel/Framework/Sous_zone_dis_base.cpp