TRUST: Perte_Charge_CoviMAC_Face Class Reference
Perte_Charge_CoviMAC_Face Class Reference
class Perte_Charge_CoviMAC_Face
#include <Perte_Charge_CoviMAC_Face.h>
Public Member Functions
Perte_Charge_CoviMAC_Face ()
~Perte_Charge_CoviMAC_Face ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &)
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Perte_Charge_CoviMAC_Face & self_cast (Objet_U &)
static const
Perte_Charge_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Champ_Inc_base la_vitesse
Ref_Zone_CoviMAC la_zone_CoviMAC
Ref_Zone_Cl_CoviMAC la_zone_Cl_CoviMAC
Ref_Fluide_base le_fluide
IntVect num_faces
Detailed Description
class Perte_Charge_CoviMAC_Face
See also:
Source_base
Definition at line 48 of file Perte_Charge_CoviMAC_Face.h.
Constructor & Destructor Documentation
Perte_Charge_CoviMAC_Face::Perte_Charge_CoviMAC_Face ()
Definition at line 30 of file Perte_Charge_CoviMAC_Face.cpp.
Perte_Charge_CoviMAC_Face::~Perte_Charge_CoviMAC_Face ()
Definition at line 30 of file Perte_Charge_CoviMAC_Face.cpp.
Member Function Documentation
void Perte_Charge_CoviMAC_Face::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 65 of file Perte_Charge_CoviMAC_Face.cpp.
References associer_zones(), Cerr, Probleme_base::equation(), Process::exit(), finl, Equation_base::inconnue(), la_vitesse, le_fluide, Equation_base::milieu(), Probleme_base::nombre_d_equations(), ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
{
  Cerr << " Perte_Charge_CoviMAC_Face::associer_pb " << finl ;
  int nb_eqn = pb.nombre_d_equations();
  int ok=0;
  for (int i=0; i<nb_eqn; i++)
    {
      const Equation_base& eqn = pb.equation(i);
      if  (sub_type(Navier_Stokes_std,eqn))
        {
          la_vitesse = ref_cast(Champ_Face_CoviMAC,eqn.inconnue().valeur());
          le_fluide = ref_cast(Fluide_base,eqn.milieu());
          associer_zones(eqn.zone_dis(),eqn.zone_Cl_dis());
          i = nb_eqn;
          ok = 1;
        }
    }
  if (!ok)
    {
      Cerr << "Erreur TRUST dans Perte_Charge_CoviMAC_Face::associer_pb()" << finl;
      Cerr << "On ne trouve pas d'equation d'hydraulique dans le probleme" << finl;
      exit();
    }
}
void Perte_Charge_CoviMAC_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 91 of file Perte_Charge_CoviMAC_Face.cpp.
References Cerr, finl, la_zone_Cl_CoviMAC, la_zone_CoviMAC, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by associer_pb().
{
  Cerr << " Perte_Charge_CoviMAC_Face::associer_zones " << finl ;
  la_zone_CoviMAC = ref_cast(Zone_CoviMAC, zone_dis.valeur());
  la_zone_Cl_CoviMAC = ref_cast(Zone_Cl_CoviMAC, zone_Cl_dis.valeur());
}
virtual int Perte_Charge_CoviMAC_Face::duplique () const [pure virtual]
Implements Source_base.
Implemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
const Type_info * Perte_Charge_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 30 of file Perte_Charge_CoviMAC_Face.cpp.
const Type_info * Perte_Charge_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 30 of file Perte_Charge_CoviMAC_Face.cpp.
void Perte_Charge_CoviMAC_Face::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 51 of file Perte_Charge_CoviMAC_Face.cpp.
{
  ;
}
Sortie & Perte_Charge_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 37 of file Perte_Charge_CoviMAC_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je();
}
Entree & Perte_Charge_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 46 of file Perte_Charge_CoviMAC_Face.cpp.
{
  return s ;
}
const Perte_Charge_CoviMAC_Face & Perte_Charge_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 30 of file Perte_Charge_CoviMAC_Face.cpp.
Perte_Charge_CoviMAC_Face & Perte_Charge_CoviMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 30 of file Perte_Charge_CoviMAC_Face.cpp.
Member Data Documentation
const Type_info Perte_Charge_CoviMAC_Face::info_obj [static]
Reimplemented from Source_base.
Reimplemented in DP_Impose_CoviMAC_Face, and Perte_Charge_Singuliere_CoviMAC_Face.
Definition at line 54 of file Perte_Charge_CoviMAC_Face.h.
Ref_Champ_Inc_base Perte_Charge_CoviMAC_Face::la_vitesse [protected]
Definition at line 63 of file Perte_Charge_CoviMAC_Face.h.
Referenced by associer_pb().
Ref_Zone_Cl_CoviMAC Perte_Charge_CoviMAC_Face::la_zone_Cl_CoviMAC [protected]
Definition at line 65 of file Perte_Charge_CoviMAC_Face.h.
Referenced by associer_zones().
Ref_Zone_CoviMAC Perte_Charge_CoviMAC_Face::la_zone_CoviMAC [protected]
Definition at line 64 of file Perte_Charge_CoviMAC_Face.h.
Referenced by associer_zones().
Ref_Fluide_base Perte_Charge_CoviMAC_Face::le_fluide [protected]
Definition at line 66 of file Perte_Charge_CoviMAC_Face.h.
Referenced by associer_pb().
IntVect Perte_Charge_CoviMAC_Face::num_faces [protected]
Definition at line 67 of file Perte_Charge_CoviMAC_Face.h.
Referenced by Perte_Charge_Singuliere_CoviMAC_Face::mettre_a_jour(), DP_Impose_CoviMAC_Face::mettre_a_jour(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), and DP_Impose_CoviMAC_Face::remplir_num_faces().
The documentation for this class was generated from the following files:
src/CoviMAC/Sources/Perte_Charge_CoviMAC_Face.h
src/CoviMAC/Sources/Perte_Charge_CoviMAC_Face.cpp