TRUST: Ref_Zone_VEF_PreP1b Class Reference
Ref_Zone_VEF_PreP1b Class Reference
#include <Ref_Zone_VEF_PreP1b.h>
Public Member Functions
~Ref_Zone_VEF_PreP1b ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_VEF_PreP1b ()
Ref_Zone_VEF_PreP1b (const Zone_VEF_PreP1b &)
Ref_Zone_VEF_PreP1b (const Ref_Zone_VEF_PreP1b &)
const Zone_VEF_PreP1b & valeur () const
Zone_VEF_PreP1b & valeur ()
const Zone_VEF_PreP1b * operator-> () const
Zone_VEF_PreP1b * operator-> ()
const Ref_Zone_VEF_PreP1b & operator= (const Zone_VEF_PreP1b &)
const Ref_Zone_VEF_PreP1b & operator= (const Ref_Zone_VEF_PreP1b &)
operator const Zone_VEF_PreP1b & () const
operator Zone_VEF_PreP1b & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_VEF_PreP1b & self_cast (Objet_U &)
static const Ref_Zone_VEF_PreP1b & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_VEF_PreP1b * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
Constructor & Destructor Documentation
Ref_Zone_VEF_PreP1b::~Ref_Zone_VEF_PreP1b ()
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Ref_Zone_VEF_PreP1b::Ref_Zone_VEF_PreP1b ()
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Ref_Zone_VEF_PreP1b::Ref_Zone_VEF_PreP1b (const Zone_VEF_PreP1b & t)
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Ref_Zone_VEF_PreP1b::Ref_Zone_VEF_PreP1b (const Ref_Zone_VEF_PreP1b & t)
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Member Function Documentation
Objet_U * Ref_Zone_VEF_PreP1b::cree_instance () [static]
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
int Ref_Zone_VEF_PreP1b::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Type_info * Ref_Zone_VEF_PreP1b::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Type_info & Ref_Zone_VEF_PreP1b::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Type_info * Ref_Zone_VEF_PreP1b::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Ref_Zone_VEF_PreP1b::operator const Zone_VEF_PreP1b & () const
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Ref_Zone_VEF_PreP1b::operator Zone_VEF_PreP1b & ()
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Zone_VEF_PreP1b * Ref_Zone_VEF_PreP1b::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
Zone_VEF_PreP1b * Ref_Zone_VEF_PreP1b::operator-> () [inline]
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
const Ref_Zone_VEF_PreP1b & Ref_Zone_VEF_PreP1b::operator= (const Ref_Zone_VEF_PreP1b & t)
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Ref_Zone_VEF_PreP1b & Ref_Zone_VEF_PreP1b::operator= (const Zone_VEF_PreP1b & t)
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Sortie & Ref_Zone_VEF_PreP1b::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Entree & Ref_Zone_VEF_PreP1b::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Ref_Zone_VEF_PreP1b & Ref_Zone_VEF_PreP1b::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
Ref_Zone_VEF_PreP1b & Ref_Zone_VEF_PreP1b::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
void Ref_Zone_VEF_PreP1b::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
unsigned Ref_Zone_VEF_PreP1b::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_VEF_PreP1b.cpp.
const Zone_VEF_PreP1b & Ref_Zone_VEF_PreP1b::valeur () const [inline]
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
Referenced by Terme_Source_Acceleration_VEF_Face::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Diff_P1NC_barprim::calculer(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_P1_isoP1Bulle::zone_dis_base(), Champ_Fonc_P1_isoP1Bulle::zone_dis_base(), and Champ_Fonc_P1_isoP1Bulle::zone_vef().
Zone_VEF_PreP1b & Ref_Zone_VEF_PreP1b::valeur () [inline]
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
Member Data Documentation
const Type_info Ref_Zone_VEF_PreP1b::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
Zone_VEF_PreP1b* Ref_Zone_VEF_PreP1b::pointeur_ [private]
Definition at line 28 of file Ref_Zone_VEF_PreP1b.h.
The documentation for this class was generated from the following files:
src/P1NCP1B/Zones/Ref_Zone_VEF_PreP1b.h
src/P1NCP1B/Zones/Ref_Zone_VEF_PreP1b.cpp