TRUST: Faces Class Reference
Faces Class Reference
enum Type_Face
Les differents types geometriques de faces.
#include <Faces.h>
Public Types
enum Type_Face {
vide_0D , point_1D , point_1D_axi , segment_2D ,
segment_2D_axi , triangle_3D , quadrilatere_2D_axi , quadrangle_3D ,
quadrangle_3D_axi , polygone_3D
}
Public Member Functions
Faces ()
~Faces ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Type_Face type_face () const
Renvoie le type des Faces.
int nb_faces () const
Renvoie le nombre de Faces.
int nb_faces_tot () const
Renvoie le nombre total de Faces
i.e. Le nombre de faces reelles et virtuelles
sur le processeur courant.
int nb_som_faces () const
Renvoie le nombre de sommet par face.
int sommet (int, int) const
Renvoie le numero du j-ieme sommet de la i-ieme face.
int & sommet (int, int)
Renvoie une reference sur le numero
du j-ieme sommet de la i-ieme face.
IntTab & les_sommets ()
const IntTab & les_sommets () const
Renvoie le tableau des sommets de toutes les faces.
Type_Face type (const Motcle &) const
Renvoie un objet de Type_Face representant
le type de nom specifie.
Les noms de types reconnus sont:
"vide_0D"
"point_1D"
"point_1D_axi"
"segment_2D"
"triangle_3D"
"quadrangle_3D"
"segment_2D_axi"
"quadrangle_3D_axi"
"quadrilatere_2D_axi".
Motcle & type (const Type_Face &) const
Renvoie le nom associe a un type de face.
(inverse de Type_Face Faces::type(const Motcle&) const)
void ajouter (const IntTab &)
Ajoute des faces.
Ajouter des faces revient a ajouter des sommets.
void typer (const Motcle &)
Type les faces.
void typer (const Type_Face &)
Type les faces.
int dimensionner (int)
(Re-)dimensionne les faces
On redimensionne les voisins en consequence.
Les sommets implicitement ajoutes sont initialises a -1.
int voisin (int, int) const
Renvoie le numero du i-ieme voisin de face.
int & voisin (int, int)
Renvoie une reference le numero du i-ieme voisin de face.
IntTab & voisins ()
Renvoie le tableau des voisins (des faces).
const IntTab & voisins () const
void completer (int, int)
Complete la face specifie: met a jour
ses voisins.
void associer_zone (const Zone &)
Associe les faces a une Zone.
const Zone & zone () const
Renvoie la zone associee.
void calculer_surfaces (DoubleVect &) const
Calcule la surface des faces.
void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravite de chaque face.
void reordonner ()
Reordonne les faces.
(on ne reordonne que les quadrangles)
IntVect & compare (const Faces &, IntVect &)
Compare l'objet Faces passe en parametre avec
l'objet Faces lui-meme (this)
void initialiser_faces_joint (int)
Initialise les voisins des faces joints a -1.
void initialiser_sommets_faces_joint (int)
Initialise les sommets des faces joints a -1.
Entree & lit (Entree &)
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Ne fait rien si le type lu est "vide_0D".
Sortie & ecrit (Sortie &) const
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Faces & self_cast (Objet_U &)
static const Faces & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Entree & readOn (Entree &) override
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Cree un objets Faces avec 0 faces si le type est "vide_0D".
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Type_Face type_face_
int nb_som_face
IntTab sommets
IntTab faces_voisins
Ref_Zone ma_zone
Detailed Description
enum Type_Face
Les differents types geometriques de faces.
Classe Faces
Faces decrit un ensemble de faces par leur type (point ,segment,
triangle ou quadrangle), leurs sommets et leurs elements
adjacents.
Definition at line 42 of file Faces.h.
Member Enumeration Documentation
Type_Face
enum Faces::Type_Face
Enumerator
vide_0D
point_1D
point_1D_axi
segment_2D
segment_2D_axi
triangle_3D
quadrilatere_2D_axi
quadrangle_3D
quadrangle_3D_axi
polygone_3D
Definition at line 48 of file Faces.h.
  {
    vide_0D,
    point_1D,
    point_1D_axi,
    segment_2D,
    segment_2D_axi,
    triangle_3D,
    quadrilatere_2D_axi,
    quadrangle_3D,
    quadrangle_3D_axi,
    polygone_3D
  };
Constructor & Destructor Documentation
Faces()
Faces::Faces ()
Definition at line 24 of file Faces.cpp.
:nb_som_face(0) { }
~Faces()
Faces::~Faces ()
Definition at line 23 of file Faces.cpp.
Member Function Documentation
ajouter()
void Faces::ajouter (const IntTab & tab_sommet)
Ajoute des faces.
Ajouter des faces revient a ajouter des sommets.
Definition at line 352 of file Faces.cpp.
{
  assert(sommets.dimension(1)==tab_sommet.dimension(1));
  int oldsz=sommets.dimension(0);
  int addsz=tab_sommet.dimension(0);
  dimensionner(oldsz+addsz);
  for(int i=0; i<addsz; i++)
    for(int j=0; j<tab_sommet.dimension(1); j++)
      sommets(oldsz+i,j)=tab_sommet(i,j);
}
References TRUSTTab< _TYPE_ >::dimension(), dimensionner(), and sommets.
Referenced by Frontiere::ajouter_faces(), and Joint::ajouter_faces().
associer_zone()
void Faces::associer_zone (const Zone & z) inline
Associe les faces a une Zone.
Definition at line 327 of file Faces.h.
{
  ma_zone=z;
}
References ma_zone.
Referenced by Frontiere::associer_zone(), Elem_geom_base::creer_faces_elem(), Zone_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Zone_VF::infobord(), Distanceparoi::interpreter_(), and traite_bord().
calculer_centres_gravite()
void Faces::calculer_centres_gravite (DoubleTab & xv) const
Calcule les centres de gravite de chaque face.
Definition at line 857 of file Faces.cpp.
{
// Le tableau xv est dimensionne dans ::calculer_centres_gravite
  const Domaine& dom=zone().domaine();
  const DoubleTab& coord=dom.coord_sommets();
  ::calculer_centres_gravite(xv, type_face_,
                             coord, sommets);
}
References calculer_centres_gravite(), Domaine::coord_sommets(), Zone::domaine(), sommets, type_face_, and zone().
Referenced by calculer_centres_gravite(), Zone_VF::discretiser(), Equation_base::ecrire_fichier_xyz(), Distanceparoi::interpreter_(), Champ_front_synt::mettre_a_jour(), Faces_VDF::reordonner_pour_debog(), and traite_bord().
calculer_surfaces()
void Faces::calculer_surfaces (DoubleVect & surfaces) const
Calcule la surface des faces.
< faces de direction r
< surface = r0*abs(teta1-teta0)
< surface = r1-r2
Definition at line 589 of file Faces.cpp.
{
  surfaces.resize(nb_faces_tot());
  const Domaine& dom=zone().domaine();
// Verification qu'en coordonnees cylindriques, r est bien positif
  if (axi || bidim_axi)
    {
      int nb_som = dom.les_sommets().dimension(0);
      for (int i=0; i<nb_som; i++)
        {
          if (dom.coord(i,0)<0)
            {
              Cerr << "In axisymmetric, the coordinates of the mesh according to radius" << finl;
              Cerr << "ie along X, can not be negatives." << finl;
              Cerr << "The revolution axis must be at x=0." << finl;
              exit();
            }
        }
    }
  switch(type_face_)
    {
    case Faces::segment_2D :
      {
        assert(dimension==2);
        double delta0, delta1;
        for(int face=0; face <nb_faces_tot(); face++)
          {
            delta0=(dom.coord(sommet(face ,0), 0) - dom.coord(sommet(face ,1), 0));
            delta0*=delta0;
            delta1=(dom.coord(sommet(face ,0), 1) - dom.coord(sommet(face ,1), 1));
            delta1*=delta1;
            surfaces(face)=sqrt(delta0+delta1);
            if(surfaces(face)==0.)
              {
                Cerr << "area("<<face<<")=0 ! Check your mesh." << finl;
                exit();
              }
          }
        break;
      }
    case Faces::quadrilatere_2D_axi :
      {
        assert(dimension==2);
        double r0,r1,z0,z1,delta_r,delta_z;
        for(int face=0; face <nb_faces_tot(); face++)
          {
            r0 = dom.coord(sommet(face ,0), 0);
            r1 = dom.coord(sommet(face ,1), 0);
            delta_r=std::fabs(r1-r0);
            if ( est_egal(delta_r,0) ) //!<  faces de direction r
              {
                z0 = dom.coord(sommet(face ,0), 1);
                z1 = dom.coord(sommet(face ,1), 1);
                delta_z=std::fabs(z1-z0);
                surfaces(face) = 2*M_PI*r0*delta_z;
              }
            else //face de direction z
              {
                surfaces(face) = 2*M_PI*0.5*(r1+r0)*delta_r;
              }
          }
        break;
      }
    case  Faces::segment_2D_axi :
      {
        assert(dimension==2);
        double r0,r1,teta0,teta1,d_teta;
        for(int face=0; face <nb_faces_tot(); face++)
          {
            r0 = dom.coord(sommet(face ,0), 0);
            r1 = dom.coord(sommet(face ,1), 0);
            if ( est_egal(r0,r1) ) //!< surface = r0*abs(teta1-teta0)
              {
                teta0 = dom.coord(sommet(face ,0), 1);
                teta1 = dom.coord(sommet(face ,1), 1);
                d_teta = std::fabs(teta1-teta0);
                if(d_teta > M_PI) d_teta=2.*M_PI-d_teta;
                surfaces(face)=r0*d_teta;
              }
            else //!<  surface = r1-r2
              surfaces(face)=std::fabs(r1-r0);
          }
        break;
      }
    case  Faces::triangle_3D :
      {
        assert(dimension==3);
        double delta0, delta1, delta2;
        double longueur0, longueur1;
        double prod,sa;
        for(int face=0; face <nb_faces_tot(); face++)
          {
            prod=0;
            delta0=(dom.coord(sommet(face ,1), 0) - dom.coord(sommet(face ,0), 0));
            delta1=(dom.coord(sommet(face ,1), 1) - dom.coord(sommet(face ,0), 1));
            delta2=(dom.coord(sommet(face ,1), 2) - dom.coord(sommet(face ,0), 2));
            longueur0=(delta0*delta0+delta1*delta1+delta2*delta2);
            sa=delta0;
            delta0=(dom.coord(sommet(face ,2), 0) - dom.coord(sommet(face ,0), 0));
            prod=sa*delta0;
            sa=delta1;
            delta1=(dom.coord(sommet(face ,2), 1) - dom.coord(sommet(face ,0), 1));
            prod+=sa*delta1;
            sa=delta2;
            delta2=(dom.coord(sommet(face ,2), 2) - dom.coord(sommet(face ,0), 2));
            prod+=sa*delta2;
            longueur1=(delta0*delta0+delta1*delta1+delta2*delta2);
            surfaces(face)=0.5*(sqrt(longueur0*longueur1-prod*prod));
            if(surfaces(face)==0.)
              {
                Cerr << "area("<<face<<")=0 ! Check your mesh." << finl;
                exit();
              }
          }
        break;
      }
    case  Faces::quadrangle_3D :
      {
// On se base sur Hexa_VEF::normale():
        for(int face=0; face <nb_faces_tot(); face++)
          {
            int n0 = sommet(face, 0);
            int n1 = sommet(face, 1);
            int n2 = sommet(face, 2);
            int n3 = sommet(face, 3);
// NB: Dans un prisme, il y'a aussi des triangles comme faces... Donc:
            if (n3<0) n3 = n2;
            double x1 = dom.coord(n0, 0) - dom.coord(n1, 0);
            double y1 = dom.coord(n0, 1) - dom.coord(n1, 1);
            double z1 = dom.coord(n0, 2) - dom.coord(n1, 2);
            double x2 = dom.coord(n3, 0) - dom.coord(n1, 0);
            double y2 = dom.coord(n3, 1) - dom.coord(n1, 1);
            double z2 = dom.coord(n3, 2) - dom.coord(n1, 2);
            double nx = (y1*z2 - y2*z1)/2;
            double ny = (-x1*z2 + x2*z1)/2;
            double nz = (x1*y2 - x2*y1)/2;
            x1 = dom.coord(n0,0) - dom.coord(n2,0);
            y1 = dom.coord(n0,1) - dom.coord(n2,1);
            z1 = dom.coord(n0,2) - dom.coord(n2,2);
            x2 = dom.coord(n3,0) - dom.coord(n2,0);
            y2 = dom.coord(n3,1) - dom.coord(n2,1);
            z2 = dom.coord(n3,2) - dom.coord(n2,2);
            nx -= (y1*z2 - y2*z1)/2;
            ny -= (-x1*z2 + x2*z1)/2;
            nz -= (x1*y2 - x2*y1)/2;
            surfaces(face)=sqrt(nx*nx+ny*ny+nz*nz);
          }
        break;
      }
    case Faces::quadrangle_3D_axi :
      {
        assert(dimension==3);
        double r0,r1,teta0,teta1,teta2,z0,z2,d_teta,delta_r;
        for(int face=0; face <nb_faces_tot(); face++)
          {
            r0 = dom.coord(sommet(face ,0), 0);
            r1 = dom.coord(sommet(face ,1), 0);
            delta_r = std::fabs(r1 - r0);
            if ( est_egal(r0,r1) )
              {
                teta0 = dom.coord(sommet(face ,0), 1);
                teta1 = dom.coord(sommet(face ,1), 1);
                z0 = dom.coord(sommet(face ,0), 2);
                z2 = dom.coord(sommet(face ,2), 2);
                d_teta = std::fabs(teta1-teta0);
                if(d_teta > M_PI) d_teta=2.*M_PI-d_teta;
                surfaces(face)=r0*d_teta*std::fabs(z2-z0);
              }
            else
              {
                teta0 = dom.coord(sommet(face ,0), 1);
                teta2 = dom.coord(sommet(face ,2), 1);
                if (teta0 == teta2)
                  {
                    z0 = dom.coord(sommet(face ,0), 2);
                    z2 = dom.coord(sommet(face ,2), 2);
                    surfaces(face) = delta_r*std::fabs(z2-z0);
                  }
                else
                  {
                    d_teta=std::fabs(teta2-teta0);
                    if(d_teta > M_PI) d_teta=2.*M_PI-d_teta;
                    surfaces(face) = 0.5*(r0+r1)*d_teta*delta_r;
                  }
              }
          }
        break;
      }
    case Faces::point_1D:
    case Faces::vide_0D :
      {
        for(int face=0; face <nb_faces_tot(); face++)
          surfaces(face) = 1.0;
        break;
      }
    case Faces::point_1D_axi:
      {
        assert(dimension==3);
        const DomaineAxi1d& domax = ref_cast(DomaineAxi1d,dom);
        for(int face=0; face <nb_faces_tot(); face++)
          {
            int elem = voisin(face,0)==-1 ? voisin(face,1) : voisin(face,0);
            double x0 = domax.origine_repere(elem,0);
            double y0 = domax.origine_repere(elem,1);
            double x = dom.coord(sommet(face ,0), 0);
            double y = dom.coord(sommet(face ,0), 1);
            double r = sqrt((x-x0)*(x-x0)+(y-y0)*(y-y0));
            surfaces(face) = 2.*M_PI*r;
          }
        break;
      }
    case Faces::polygone_3D:
      {
        const DoubleTab& coord=dom.coord_sommets();
        int nmax=les_sommets().dimension(1);
        for(int face=0; face <nb_faces_tot(); face++)
          {
            double n0=0,n1=0,n2=0;
            int n=nmax-1;
            while (n >= 0 && sommet(face,n)==-1) n--;
            for (int i0=0; i0<=n; i0++)
              {
                int ip1_0=0;
                if (i0<n) ip1_0=i0+1;
                int i=sommet(face,i0);
                int ip1=sommet(face,ip1_0);
                n0+=coord(i,1)*coord(ip1,2)-coord(i,2)*coord(ip1,1);
                n1+=coord(i,2)*coord(ip1,0)-coord(i,0)*coord(ip1,2);
                n2+=coord(i,0)*coord(ip1,1)-coord(i,1)*coord(ip1,0);
              }
            surfaces(face)=sqrt(n0*n0+n1*n1+n2*n2)/2.;
          }
        break;
      }
    default :
      {
        Cerr << "Error TRUST in type of Faces not recognized " << finl;
        exit();
      }
    }
}
References Objet_U::axi, Objet_U::bidim_axi, Cerr, Domaine::coord(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), est_egal(), Process::exit(), finl, Domaine::les_sommets(), les_sommets(), M_PI, nb_faces_tot(), DomaineAxi1d::origine_repere(), point_1D, point_1D_axi, polygone_3D, prod(), quadrangle_3D, quadrangle_3D_axi, quadrilatere_2D_axi, ref_cast, TRUSTVect< _TYPE_ >::resize(), segment_2D, segment_2D_axi, sommet(), triangle_3D, type_face_, vide_0D, voisin(), and zone().
Referenced by Champ_front_recyclage::calcul_moyenne_recyclee(), Operateur_base::calculer_pour_post(), Zone_VF::discretiser(), Zone_VF::infobord(), and Champ_front_synt::mettre_a_jour().
compare()
IntVect & Faces::compare (const Faces & faces, IntVect & renum)
Compare l'objet Faces passe en parametre avec
l'objet Faces lui-meme (this)
Returns
IntVect&
Signification:
Contraintes:
Definition at line 1220 of file Faces.cpp.
{
  const Zone& la_zone=zone();
  const Zone& sa_zone=faces.zone();
  const Domaine& domaine=la_zone.domaine();
  const Domaine& son_domaine=sa_zone.domaine();
  if ( (nb_faces() != faces.nb_faces()) || ( type_face_ != faces.type_face_) )
    {
      renum.resize(1);
      renum=-1;
      return renum;
    }
  if(domaine.le_nom() == son_domaine.le_nom())
    {
// il suffit de comparer les numeros des sommets :
      IntLists listes;
      int premier=0;
      int numerol, face, ok, rang;
      for(face=0; face<nb_faces(); face++)
        {
          numerol=ppsf(*this, face, nb_som_face);
          listes[numerol].add(premier++);
        }
      for(face=0; face<nb_faces(); face++)
        {
          numerol=ppsf(faces, face, nb_som_face);
          IntList_Curseur curseur(listes[numerol]);
          ok=1;
          while (curseur && ok)
            {
              rang=curseur.valeur();
              ok=!same(faces, face, *this, rang, nb_som_face);
              if(!ok)
                {
// "face==rang"
                  renum(face)=rang;
                }
              else
                ++curseur;
            }
          if(!curseur)
            {
              renum.resize(1);
              renum=-1;
              return renum;
            }
        }
    }
  else
    {
// il faut comparer les coordonnees des sommets :
    }
  return renum;
}
References Zone::domaine(), Domaine::le_nom(), nb_faces(), nb_som_face, ppsf(), TRUSTVect< _TYPE_ >::resize(), same(), type_face_, TRUSTList_Curseur< _TYPE_ >::valeur(), and zone().
completer()
void Faces::completer (int face, int num_elem)
Complete la face specifie: met a jour
ses voisins.
Definition at line 551 of file Faces.cpp.
{
  if ( voisin(face,0) == -1)
    voisin(face, 0) = num_elem;
  else if( voisin(face,1) == -1)
    voisin(face, 1) = num_elem;
  else
    {
      Cerr << finl;
      Cerr << "Problem for the face number " << face << " and the cell " << num_elem << finl;
      Cerr << "Indeed, the face already belongs to the cells " << voisin(face, 0) << " and " << voisin(face, 1) << finl;
      Cerr << "The nodes of this face are:" << finl;
      for (int i=0; i<nb_som_face; i++)
        Cerr << "Node " << sommet(face,i) << finl;
      Cerr << "Check your mesh. Perhaps some cells " << finl;
      Cerr << "are defined 2 times." << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, nb_som_face, sommet(), and voisin().
Referenced by Elem_geom_base::creer_faces_elem().
cree_instance()
Objet_U * Faces::cree_instance () static
Definition at line 23 of file Faces.cpp.
dimensionner()
int Faces::dimensionner (int i)
(Re-)dimensionne les faces
On redimensionne les voisins en consequence.
Les sommets implicitement ajoutes sont initialises a -1.
Returns
int
Signification: le nouveau nombre de face
Contraintes:
< Fixed bug: To have the possibility of merging borders after discretization
Definition at line 379 of file Faces.cpp.
{
  int oldsz=nb_faces();
  int nombre_som_faces=nb_som_faces();
  if (sommets.size()!=0) sommets.detach_vect(); //!< Fixed bug: To have the possibility of merging borders after discretization
  sommets.resize(i,nombre_som_faces);
  faces_voisins.resize(i, 2);
  for(int j=oldsz; j<i; j++)
    {
      for(int k=0; k<nombre_som_faces; k++)
        sommets(j,k)=-1;
      faces_voisins(j,0)=faces_voisins(j,1)=-1;
    }
  return i;
}
References TRUSTVect< _TYPE_ >::detach_vect(), faces_voisins, nb_faces(), nb_som_faces(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), and sommets.
Referenced by BlocData::add_faces(), ajouter(), auto_build_joints(), Remove_elem::creer_faces(), Elem_geom_base::creer_faces_elem(), DecoupeBord::Decouper(), Frontiere::dimensionner(), Joint::dimensionner(), MaillerParallel::interpreter(), Lire_Ideas::interpreter_(), and RegroupeBord::regroupe_bord().
duplique()
int Faces::duplique () const override virtual
Implements Objet_U.
Reimplemented in Faces_VDF.
Definition at line 23 of file Faces.cpp.
ecrit()
Sortie & Faces::ecrit (Sortie & s) const
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Definition at line 80 of file Faces.cpp.
{
  if(nb_faces()==0)
    s << "vide_0D" << finl;
  else
    {
      s << (type(type_face_)) << finl;
      sommets.ecrit(s);
      faces_voisins.ecrit(s);
    }
  return s ;
}
References TRUSTTab< _TYPE_ >::ecrit(), faces_voisins, finl, nb_faces(), sommets, type(), and type_face_.
get_info()
const Type_info * Faces::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Faces_VDF.
Definition at line 23 of file Faces.cpp.
info()
const Type_info * Faces::info () static
Definition at line 23 of file Faces.cpp.
initialiser_faces_joint()
void Faces::initialiser_faces_joint (int nb_faces_joint)
Initialise les voisins des faces joints a -1.
Definition at line 409 of file Faces.cpp.
{
  int i;
  for(i=0; i<nb_faces_joint; i++)
// faces_voisins(i,0)=faces_voisins(i,1)=-2;
    faces_voisins(i,0)=faces_voisins(i,1)=-1;
}
References faces_voisins.
initialiser_sommets_faces_joint()
void Faces::initialiser_sommets_faces_joint (int nb_faces_joint)
Initialise les sommets des faces joints a -1.
Definition at line 431 of file Faces.cpp.
{
  int i;
  for(i=0; i<nb_faces_joint; i++)
    for(int k=0; k<nb_som_faces(); k++)
// sommets(i,k)=-2;
      sommets(i,k)=-1;
}
References nb_som_faces(), and sommets.
les_sommets() [1/2]
IntTab & Faces::les_sommets () inline
Definition at line 258 of file Faces.h.
{
  return sommets;
}
References sommets.
Referenced by Frontiere::add(), BlocData::add_faces(), auto_build_joints(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Ch_front_input::buildSommetsFaces(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), calculer_surfaces(), Reordonner_faces_periodiques::check_faces_periodiques(), Reordonner_faces_periodiques::chercher_direction_perio(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), corriger_type(), Remove_elem::creer_faces(), Faces_builder::creer_faces_frontiere(), Faces_builder::creer_faces_reeles(), Frontiere::creer_tableau_faces(), decoupe(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), DecoupeBord::Decouper(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Joint::dimensionner(), Zone_VF::discretiser(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), find_joint_faces(), Ch_front_input::getTemplate(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Frontiere::les_sommets_des_faces(), Scatter::lire_domaine(), NettoieNoeuds::nettoie(), OrienteFacesBord::oriente_faces_bord(), Remove_elem::recreer_faces(), Raffiner_Simplexes::refine_domain(), RegroupeBord::regroupe_bord(), Frontiere::renum(), reorder_vertices(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), Scatter::reordonner_faces_de_joint(), reordonner_vdf(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Trianguler_fin::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
les_sommets() [2/2]
const IntTab & Faces::les_sommets () const inline
Renvoie le tableau des sommets de toutes les faces.
Returns
IntTab&
Signification: le tableau des sommets de toutes les faces
Contraintes:
Definition at line 254 of file Faces.h.
{
  return sommets;
}
References sommets.
lit()
Entree & Faces::lit (Entree & s)
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Ne fait rien si le type lu est "vide_0D".
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Definition at line 156 of file Faces.cpp.
{
  Motcle typ;
  s >> typ;
  if(typ!="vide_0D")
    {
      typer(typ);
      sommets.lit(s);
      faces_voisins.lit(s);
      reordonner();
    }
  else
    {
      typer(typ);
      sommets.resize(0,0);
      faces_voisins.resize(0,2);
    }
  return s ;
}
References faces_voisins, TRUSTTab< _TYPE_ >::lit(), reordonner(), TRUSTTab< _TYPE_ >::resize(), sommets, and typer().
nb_faces()
int Faces::nb_faces () const inline
Renvoie le nombre de Faces.
Returns
int
Signification: le nombre de Faces
Contraintes:
Definition at line 142 of file Faces.h.
{
  return sommets.dimension(0);
}
References TRUSTTab< _TYPE_ >::dimension(), and sommets.
Referenced by Frontiere::add(), ajouter(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), calculer_liste_complete_aretes_joint(), Champ_base::calculer_valeurs_som_post(), compare(), Extruder_en3::construire_bord_lateral(), Faces_builder::creer_faces_frontiere(), dimensionner(), Zone_VF::discretiser(), ecrit(), Domaine_bord::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), ExtrudeBord::extruder_bord(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Zone::face_interne_conjuguee(), Zone_VF::infobord(), Frontiere::nb_faces(), printOn(), RegroupeBord::regroupe_bord(), reorder_vertices(), reordonner(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), Faces_VDF::reordonner(), Faces_VDF::reordonner_pour_debog(), reordonner_vdf(), Faces_VDF::swap(), traite_bord(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), and Extruder::traiter_faces_dvt_hexa().
nb_faces_tot()
int Faces::nb_faces_tot () const inline
Renvoie le nombre total de Faces
i.e. Le nombre de faces reelles et virtuelles
sur le processeur courant.
Returns
int
Signification: le nombre total de Faces
Contraintes:
Definition at line 163 of file Faces.h.
{
  return sommets.dimension_tot(0);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), and sommets.
Referenced by Faces_VDF::calculer_orientation(), calculer_surfaces(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), and Remove_Invalid_Internal_Boundaries::interpreter_().
nb_som_faces()
int Faces::nb_som_faces () const inline
Renvoie le nombre de sommet par face.
Returns
int
Signification: le nombre de sommet par face
Contraintes:
Definition at line 232 of file Faces.h.
{
  if (nb_som_face!=-1)
    return nb_som_face;
  else
    return sommets.dimension(1);
}
References TRUSTTab< _TYPE_ >::dimension(), nb_som_face, and sommets.
Referenced by Frontiere::add(), calculer_elements_voisins_bords(), calculer_liste_complete_aretes_joint(), Faces_VDF::calculer_orientation(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), DecoupeBord::Decouper(), dimensionner(), Domaine_bord::extraire_domaine_bord(), ExtrudeBord::extruder_bord(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), initialiser_sommets_faces_joint(), Remove_Invalid_Internal_Boundaries::interpreter_(), RegroupeBord::regroupe_bord(), Champ_front_MED::remplir_tab(), Faces_VDF::swap(), and traite_bord().
printOn()
Sortie & Faces::printOn (Sortie & s) const override protected virtual
Ecrit les faces sur un flots de sortie.
On ecrit:
- le type des faces
- les sommets
- les voisins
On ecrit juste le type Faces::vide_0D, si le nombre de
faces est nul.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Faces_VDF.
Definition at line 47 of file Faces.cpp.
{
  if(nb_faces()==0)
    s << "vide_0D" << finl;
  else
    {
      s << (type(type_face_)) << finl;
      s <<  sommets;
      s << faces_voisins;
    }
  return s ;
}
References faces_voisins, finl, nb_faces(), sommets, type(), and type_face_.
Referenced by Faces_VDF::printOn().
readOn()
Entree & Faces::readOn (Entree & s) override protected virtual
Lit les specifications d'un objet face a
partir d'un flot d'entree.
On lit:
- le type des faces
- les sommets
- les voisins
Et on reordonne les sommets.
Cree un objets Faces avec 0 faces si le type est "vide_0D".
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Faces_VDF.
Definition at line 114 of file Faces.cpp.
{
  Motcle typ;
  s >> typ;
  typer(typ);
  if (typ != "vide_0D")
    {
// Les sommets et faces ne sont ecrits que si le type n'est pas vide:
      s >> sommets;
      s >> faces_voisins;
    }
  else
    {
// pour ne pas planter betement la suite qui suppose nb_dim()==2 et line_size_ > 0
      sommets.resize(0,1);
      faces_voisins.resize(0,2);
    }
  return s;
}
References faces_voisins, TRUSTTab< _TYPE_ >::resize(), sommets, and typer().
Referenced by Faces_VDF::readOn().
reordonner()
void Faces::reordonner ()
Reordonne les faces.
(on ne reordonne que les quadrangles)
Definition at line 982 of file Faces.cpp.
{
// Cerr << "Faces::reordonner()" << finl;
  switch(type_face_)
    {
    case  Faces::point_1D :
    case  Faces::point_1D_axi :
      {
        break;
      }
    case  Faces::segment_2D :
      {
// on peut avoir des bords de maillage triangulaire en 3D
        assert(dimension>=2);
        break;
      }
    case Faces::quadrilatere_2D_axi :
      {
        assert(dimension==2);
        const Zone& mazone=zone();
        const Domaine& dom=mazone.domaine();
        ArrOfInt S(2);
        ArrOfInt NS(2);
        int i;
        const int nombre_faces=nb_faces();
        for(int face=0; face < nombre_faces; face++)
          {
            NS=-1;
            for(i=0; i<2; i++)
              S[i] = sommet(face, i);
            assert( S[0] >=0 );
            assert( S[1] >=0 );
            if (dom.coord(S[0], 0) > dom.coord(S[1], 0))
              {
                NS[0]=S[1];
                NS[1]=S[0];
              }
            else
              {
                NS[0]=S[0];
                NS[1]=S[1];
              }
            for(i=0; i<2; i++)
              {
                assert(NS[i]!=-1);
                sommet(face, i)=NS[i];
              }
          }
        break;
      }
    case  Faces::segment_2D_axi :
      {
        assert(dimension==2);
        break;
      }
    case  Faces::triangle_3D :
      {
        assert(dimension==3);
        break;
      }
    case  Faces::quadrangle_3D :
      {
        assert(dimension==3);
        const Zone& mazone=zone();
        const Domaine& dom=mazone.domaine();
        ArrOfInt S(4);
        ArrOfInt NS(4);
        int i;
        double xmin, ymin, zmin;
        double xmax, ymax, zmax;
        const int nombre_faces=nb_faces();
        for(int face=0; face < nombre_faces; face++)
          {
            NS=-1;
            for(i=0; i<4; i++)
              {
                S[i] = sommet(face, i);
                assert( S[i] >=0 );
              }
            if (1)
              {
// adaptation de Hexaedre_VEF::reordonne
                const DoubleTab& coord=dom.les_sommets();
                int s0=S[0];
                int s1=S[1];
                int s2=S[2];
                int s3=S[3];
                double x03=coord(s3,0)-coord(s0,0);
                double y03=coord(s3,1)-coord(s0,1);
                double z03=coord(s3,2)-coord(s0,2);
                double x02=coord(s2,0)-coord(s0,0);
                double y02=coord(s2,1)-coord(s0,1);
                double z02=coord(s2,2)-coord(s0,2);
                double x01=coord(s1,0)-coord(s0,0);
                double y01=coord(s1,1)-coord(s0,1);
                double z01=coord(s1,2)-coord(s0,2);
                Vecteur3 OA(x01,y01,z01);
                Vecteur3 OB(x03,y03,z03);
                Vecteur3 OC(x02,y02,z02);
                Vecteur3 nplan, nmedian;
// rectangle C B
// O A
// calcul de n= OA ^ OC
                Vecteur3::produit_vectoriel(OA,OC,nplan);
// calcul de la normale nmedian du plan (OB,n)
                Vecteur3::produit_vectoriel(OB,nplan,nmedian);
// on regarde si les points A et C sont bien de part et d'autre du plan
                double psC=Vecteur3::produit_scalaire(nmedian,OA);
                double psA=Vecteur3::produit_scalaire(nmedian,OC);
                if (psA*psC>0)
                  {
// inversion des sommets 2 et 3
                    sommet(face,2)=S[3];
                    sommet(face,3)=S[2];
                    Cerr << "Permutation of local nodes 2 and 3 on the face " <<face<<finl;
                  }
              }
            else
              {
                xmin=std::min(dom.coord(S[0], 0), dom.coord(S[1], 0));
                xmin=std::min(xmin, dom.coord(S[2], 0));
                xmax=std::max(dom.coord(S[0], 0), dom.coord(S[1], 0));
                xmax=std::max(xmax, dom.coord(S[2], 0));
                ymin=std::min(dom.coord(S[0], 1), dom.coord(S[1], 1));
                ymin=std::min(ymin, dom.coord(S[2], 1));
                ymax=std::max(dom.coord(S[0], 1), dom.coord(S[1], 1));
                ymax=std::max(ymax, dom.coord(S[2], 1));
                zmin=std::min(dom.coord(S[0], 2), dom.coord(S[1], 2));
                zmin=std::min(zmin, dom.coord(S[2], 2));
                zmax=std::max(dom.coord(S[0], 2), dom.coord(S[1], 2));
                zmax=std::max(zmax, dom.coord(S[2], 2));
                if(est_egal(zmin, zmax))
                  {
                    for(i=0; i<4; i++)
                      if ( est_egal(dom.coord(S[i], 0),xmin) && est_egal(dom.coord(S[i], 1),ymin))
                        NS[0]=S[i];
                    for(i=0; i<4; i++)
                      if ( !est_egal(dom.coord(S[i], 0),xmin) && est_egal(dom.coord(S[i], 1),ymin))
                        NS[1]=S[i];
                    for(i=0; i<4; i++)
                      if ( est_egal(dom.coord(S[i], 0),xmin) && !est_egal(dom.coord(S[i], 1),ymin))
                        NS[2]=S[i];
                    for(i=0; i<4; i++)
                      if ( !est_egal(dom.coord(S[i], 0),xmin) && !est_egal(dom.coord(S[i], 1),ymin))
                        NS[3]=S[i];
                  }
                if(est_egal(ymin, ymax))
                  {
                    for(i=0; i<4; i++)
                      if ( est_egal(dom.coord(S[i], 0),xmin) && est_egal(dom.coord(S[i], 2),zmin))
                        NS[0]=S[i];
                    for(i=0; i<4; i++)
                      if ( !est_egal(dom.coord(S[i], 0),xmin) && est_egal(dom.coord(S[i], 2),zmin))
                        NS[1]=S[i];
                    for(i=0; i<4; i++)
                      if ( est_egal(dom.coord(S[i], 0),xmin) && !est_egal(dom.coord(S[i], 2),zmin))
                        NS[2]=S[i];
                    for(i=0; i<4; i++)
                      if ( !est_egal(dom.coord(S[i], 0),xmin) && !est_egal(dom.coord(S[i], 2),zmin))
                        NS[3]=S[i];
                  }
                if(est_egal(xmin, xmax))
                  {
                    for(i=0; i<4; i++)
                      if ( est_egal(dom.coord(S[i], 1),ymin) && est_egal(dom.coord(S[i], 2),zmin))
                        NS[0]=S[i];
                    for(i=0; i<4; i++)
                      if ( !est_egal(dom.coord(S[i], 1),ymin) && est_egal(dom.coord(S[i], 2),zmin))
                        NS[1]=S[i];
                    for(i=0; i<4; i++)
                      if ( est_egal(dom.coord(S[i], 1),ymin) && !est_egal(dom.coord(S[i], 2),zmin))
                        NS[2]=S[i];
                    for(i=0; i<4; i++)
                      if ( !est_egal(dom.coord(S[i], 1),ymin) && !est_egal(dom.coord(S[i], 2),zmin))
                        NS[3]=S[i];
                  }
                for(i=0; i<4; i++)
                  {
                    assert(NS[i]!=-1);
                    sommet(face, i)=NS[i];
                  }
              }
          }
        break;
      }
    case Faces::quadrangle_3D_axi :
      {
        assert(dimension==3);
        break;
      }
    case Faces::polygone_3D:
      assert(dimension==3);
      break;
    default :
      {
        Cerr << "Error TRUST in type of Faces not recognized " << finl;
        exit();
      }
    }
// Cerr << "Faces::reordonner() ok" << finl;
}
References Cerr, Domaine::coord(), Objet_U::dimension, Zone::domaine(), est_egal(), Process::exit(), finl, Domaine::les_sommets(), nb_faces(), point_1D, point_1D_axi, polygone_3D, Vecteur3::produit_scalaire(), Vecteur3::produit_vectoriel(), quadrangle_3D, quadrangle_3D_axi, quadrilatere_2D_axi, segment_2D, segment_2D_axi, sommet(), triangle_3D, type_face_, and zone().
Referenced by lit().
self_cast() [1/2]
const Faces & Faces::self_cast (const Objet_U & r) static
Definition at line 23 of file Faces.cpp.
self_cast() [2/2]
Faces & Faces::self_cast (Objet_U & r) static
Definition at line 23 of file Faces.cpp.
sommet() [1/2]
int & Faces::sommet (int i, int j) inline
Renvoie une reference sur le numero
du j-ieme sommet de la i-ieme face.
Returns
int&
Signification: reference sur le numero du j-ieme sommet
de la i-ieme face
Contraintes:
Definition at line 213 of file Faces.h.
{
  return sommets(i,j);
}
References sommets.
sommet() [2/2]
int Faces::sommet (int i, int j) const inline
Renvoie le numero du j-ieme sommet de la i-ieme face.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Definition at line 187 of file Faces.h.
{
  return sommets(i,j);
}
References sommets.
Referenced by Frontiere::add(), ajouter(), Faces_VDF::calculer_orientation(), calculer_surfaces(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), completer(), Extruder_en3::construire_bord_lateral(), Elem_geom_base::creer_faces_elem(), Extruder::extruder(), Extruder_en20::extruder(), ExtrudeBord::extruder_bord(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Lire_Ideas::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), ppsf(), Champ_front_MED::remplir_tab(), reorder_vertices(), reordonner(), same(), Faces_VDF::swap(), traite_bord(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), and Extruder::traiter_faces_dvt_hexa().
taille_memoire()
unsigned Faces::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Faces_VDF.
Definition at line 23 of file Faces.cpp.
type() [1/2]
Type_Face Faces::type (const Motcle & mot) const
Renvoie un objet de Type_Face representant
le type de nom specifie.
Les noms de types reconnus sont:
"vide_0D"
"point_1D"
"point_1D_axi"
"segment_2D"
"triangle_3D"
"quadrangle_3D"
"segment_2D_axi"
"quadrangle_3D_axi"
"quadrilatere_2D_axi".
Returns
Type_Face
Signification: le type de face correspondant au parametre mo
Contraintes:
Definition at line 211 of file Faces.cpp.
{
  Motcles les_mots(10);
  {
    les_mots[0]="vide_0D";
    les_mots[1]="point_1D";
    les_mots[2]="point_1D_axi";
    les_mots[3]="segment_2D";
    les_mots[4]="triangle_3D";
    les_mots[5]="quadrangle_3D";
    les_mots[6]="segment_2D_axi";
    les_mots[7]="quadrangle_3D_axi";
    les_mots[8]="quadrilatere_2D_axi";
    les_mots[9]="polygone_3d";
  }
  int rang=les_mots.search(mot);
  switch(rang)
    {
    case  0 :
      return Faces::vide_0D;
    case  1 :
      return Faces::point_1D;
    case  2 :
      return Faces::point_1D_axi;
    case  3 :
      return Faces::segment_2D;
    case  4 :
      return Faces::triangle_3D;
    case  5 :
      return Faces::quadrangle_3D;
    case  6 :
      return Faces::segment_2D_axi;
    case  7 :
      return Faces::quadrangle_3D_axi;
    case  8 :
      return Faces::quadrilatere_2D_axi;
    case 9 :
      return Faces::polygone_3D;
    default :
      {
        Cerr << "In the area number " << Process::me() << " " << mot << " is not a type of face." << finl;
        Cerr << "Check your splitting." << finl;
// Si mot est vide c'est que l'on tente de relire des Zones creees avec une version anterieure a la 1.5.1
        if (mot=="")
          {
            Cerr << "Your splitting seems to have been done with a TRUST version 1.5 or earlier. Since" << finl;
            Cerr << "the 1.5.1, the files format of .Zones containing the splitting of your mesh has evolved." << finl;
            Cerr << "You must therefore rebuild the splitting of your mesh with TRUST version 1.5.1 or newer." <<
                 finl;
          }
        exit();
      }
    }
// pour le compilo :
  return Faces::point_1D;
}
References Cerr, Process::exit(), finl, Process::me(), point_1D, point_1D_axi, polygone_3D, quadrangle_3D, quadrangle_3D_axi, quadrilatere_2D_axi, Motcles::search(), segment_2D, segment_2D_axi, triangle_3D, and vide_0D.
Referenced by ecrit(), printOn(), and typer().
type() [2/2]
Motcle & Faces::type (const Type_Face & typ) const
Renvoie le nom associe a un type de face.
(inverse de Type_Face Faces::type(const Motcle&) const)
Returns
Motcle&
Signification: le nom correspondant au type speficie en parametre
Contraintes:
Definition at line 293 of file Faces.cpp.
{
  static Motcle mot;
  switch(typ)
    {
    case  Faces::vide_0D :
      mot="vide_0D";
      break;
    case  Faces::point_1D :
      mot="point_1D";
      break;
    case  Faces::point_1D_axi :
      mot="point_1D_axi";
      break;
    case  Faces::segment_2D :
      mot="segment_2D";
      break;
    case  Faces::segment_2D_axi :
      mot="segment_2D_axi";
      break;
    case  Faces::triangle_3D :
      mot="triangle_3D";
      break;
    case  Faces::quadrangle_3D :
      mot="quadrangle_3D";
      break;
    case  Faces::quadrangle_3D_axi :
      mot="quadrangle_3D_axi";
      break;
    case Faces::quadrilatere_2D_axi :
      mot="quadrilatere_2D_axi";
      break;
    case Faces::polygone_3D:
      mot="polygone_3D";
      break;
    default :
      {
        Cerr << "Error TRUST in Motcle& Faces::type(const Type_Face& typ)" << finl;
        exit();
      }
    }
  return mot;
}
References Cerr, Process::exit(), finl, point_1D, point_1D_axi, polygone_3D, quadrangle_3D, quadrangle_3D_axi, quadrilatere_2D_axi, segment_2D, segment_2D_axi, triangle_3D, and vide_0D.
type_face()
Type_Face Faces::type_face () const inline
Renvoie le type des Faces.
Returns
Type_Face
Signification: le type des Faces
Contraintes:
Definition at line 123 of file Faces.h.
{
  return type_face_;
}
References type_face_.
Referenced by Champ_Generique_Extraction::completer(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Zone::correct_type_of_borders_after_merge(), corriger_type(), and DecoupeBord::Decouper().
typer() [1/2]
void Faces::typer (const Motcle & typ)
Type les faces.
Definition at line 454 of file Faces.cpp.
{
  typer(type(typ));
}
References type(), and typer().
Referenced by auto_build_joints(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Zone::correct_type_of_borders_after_merge(), corriger_type(), DecoupeBord::Decouper(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Zone_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), MaillerParallel::interpreter(), Distanceparoi::interpreter_(), Lire_Ideas::interpreter_(), lit(), Polyedriser::polyedriser(), readOn(), Remove_elem::Remove_elem_(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler_fin::trianguler(), typer(), Frontiere::typer_faces(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
typer() [2/2]
void Faces::typer (const Type_Face & typ)
Type les faces.
< sera fixe plus tard
Definition at line 473 of file Faces.cpp.
{
  type_face_ = typ;
// int axi_ = 0;
  int max_dim = 3;
  switch(typ)
    {
    case  Faces::vide_0D :
      nb_som_face=0;
      break;
    case  Faces::point_1D :
    case  Faces::point_1D_axi :
      nb_som_face=1;
      break;
    case  Faces::segment_2D :
      nb_som_face=2;
      break;
    case  Faces::segment_2D_axi :
      nb_som_face=2; //axi_=1;
      break;
    case  Faces::triangle_3D :
      nb_som_face=3;
      break;
    case  Faces::quadrangle_3D :
      nb_som_face=4;
      break;
    case  Faces::quadrangle_3D_axi :
      nb_som_face=4; //axi_=1;
      break;
    case  Faces::quadrilatere_2D_axi :
      nb_som_face=2; //axi_=1;
      break;
    case Faces::polygone_3D:
      nb_som_face=-1; //!< sera fixe plus tard
      break;
    default :
      {
        Cerr << "Error TRUST in Faces::typer(const Motcle& typ)" << finl;
        exit();
      }
    }
  /* TroisDto2D marche pas
     if (axi_==1 && bidim_axi!=1 && axi!=1)
     {
     Cerr << "The mesh contains faces that show that is a revolution mesh." << finl;
     Cerr << "Add Bidim_axi or Axi in your data file." << finl;
     exit();
     } */
  if (dimension<std::min(max_dim,nb_som_face))
    {
      Cerr << "You are in dimension " << dimension << finl;
      Cerr << "and the mesh contains faces with " << nb_som_face << " nodes." << finl;
      Cerr << "and this seems to be a mesh of dimension " << std::min(max_dim,nb_som_face) << " ..." << finl;
      exit();
    }
}
References Cerr, Objet_U::dimension, Process::exit(), finl, nb_som_face, point_1D, point_1D_axi, polygone_3D, quadrangle_3D, quadrangle_3D_axi, quadrilatere_2D_axi, segment_2D, segment_2D_axi, triangle_3D, type_face_, and vide_0D.
voisin() [1/2]
int & Faces::voisin (int face, int i) inline
Renvoie une reference le numero du i-ieme voisin de face.
Returns
int&
Signification: reference sur le numero du i-ieme voisin de face
Contraintes:
Definition at line 308 of file Faces.h.
{
  return faces_voisins(face,i);
}
References faces_voisins.
voisin() [2/2]
int Faces::voisin (int face, int i) const inline
Renvoie le numero du i-ieme voisin de face.
Returns
int
Signification: le numero i-ieme voisin de face
Contraintes:
Definition at line 283 of file Faces.h.
{
  return faces_voisins(face,i);
}
References faces_voisins.
Referenced by Frontiere::add(), ajouter(), calculer_surfaces(), completer(), Extruder::extruder(), Extruder_en20::extruder(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), Faces_VDF::swap(), Raccord_distant_homogene::trace_elem_distant(), and Frontiere::trace_elem_local().
voisins() [1/2]
IntTab & Faces::voisins () inline
Renvoie le tableau des voisins (des faces).
Returns
IntTab&
Signification: le tableau des voisins (des faces)
Contraintes:
Definition at line 365 of file Faces.h.
{
  return faces_voisins;
}
References faces_voisins.
Referenced by Frontiere::add(), Joint::ajouter_faces(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Faces_builder::creer_faces_reeles(), decoupe(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Joint::dimensionner(), Zone_VF::discretiser(), TroisDto2D::extraire_2D(), ExtrudeParoi::extrude(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extraire_domaine::interpreter_(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), reordonner_vdf(), traite_bord(), Extruder::traiter_faces_dvt(), Extruder_en20::traiter_faces_dvt(), Extruder::traiter_faces_dvt_hexa(), Trianguler_fin::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
voisins() [2/2]
const IntTab & Faces::voisins () const inline
Definition at line 369 of file Faces.h.
{
  return faces_voisins;
}
References faces_voisins.
zone()
const Zone & Faces::zone () const inline
Renvoie la zone associee.
Returns
Zone&
Signification: la zone associee
Contraintes: reference constante
Definition at line 346 of file Faces.h.
{
  return ma_zone.valeur();
}
References ma_zone, and Ref_Zone::valeur().
Referenced by calculer_centres_gravite(), Faces_VDF::calculer_orientation(), calculer_surfaces(), compare(), reordonner(), Faces_VDF::reordonner(), and Faces_VDF::reordonner_pour_debog().
Member Data Documentation
faces_voisins
IntTab Faces::faces_voisins private
Definition at line 98 of file Faces.h.
Referenced by dimensionner(), ecrit(), initialiser_faces_joint(), lit(), printOn(), readOn(), voisin(), and voisins().
info_obj
const Type_info Faces::info_obj static
Definition at line 44 of file Faces.h.
ma_zone
Ref_Zone Faces::ma_zone private
Definition at line 99 of file Faces.h.
Referenced by associer_zone(), and zone().
nb_som_face
int Faces::nb_som_face private
Definition at line 96 of file Faces.h.
Referenced by compare(), completer(), nb_som_faces(), and typer().
sommets
IntTab Faces::sommets private
Definition at line 97 of file Faces.h.
Referenced by ajouter(), calculer_centres_gravite(), dimensionner(), ecrit(), initialiser_sommets_faces_joint(), les_sommets(), lit(), nb_faces(), nb_faces_tot(), nb_som_faces(), printOn(), readOn(), and sommet().
type_face_
Type_Face Faces::type_face_ private
Definition at line 95 of file Faces.h.
Referenced by calculer_centres_gravite(), calculer_surfaces(), compare(), ecrit(), printOn(), reordonner(), type_face(), and typer().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Faces.h
src/Kernel/Geometrie/Faces.cpp