TRUST: Op_Diff_EF_base Class Reference
Op_Diff_EF_base Class Reference
class Op_Diff_EF_base
Classe de base des operateurs de convection EF
#include <Op_Diff_EF_base.h>
Public Member Functions
Op_Diff_EF_base ()
~Op_Diff_EF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
double calculer_dt_stab () const
Calcul dt_stab.
virtual void remplir_nu (DoubleTab &) const =0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_EF_base & self_cast (Objet_U &)
static const Op_Diff_EF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_EF la_zone_EF
Ref_Zone_Cl_EF la_zcl_EF
Ref_Champ_Inc_base inconnue
DoubleTab nu_
Detailed Description
class Op_Diff_EF_base
Classe de base des operateurs de convection EF
Definition at line 56 of file Op_Diff_EF_base.h.
Constructor & Destructor Documentation
Op_Diff_EF_base::Op_Diff_EF_base ()
Definition at line 35 of file Op_Diff_EF_base.cpp.
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
{
  declare_support_masse_volumique(1);
}
Op_Diff_EF_base::~Op_Diff_EF_base ()
Definition at line 33 of file Op_Diff_EF_base.cpp.
Member Function Documentation
void Op_Diff_EF_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) [virtual]
Implements Operateur_base.
Definition at line 62 of file Op_Diff_EF_base.cpp.
References Operateur_base::flux_bords_, la_zcl_EF, la_zone_EF, Zone_VF::nb_faces_bord(), ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_EF& zEF = ref_cast(Zone_EF,zone_dis.valeur());
  const Zone_Cl_EF& zclEF = ref_cast(Zone_Cl_EF,zone_cl_dis.valeur());
  /*  if (sub_type(Champ_P1_VEF,ch_transporte.valeur()))
    {
      const Champ_P1_VEF& inco = ref_cast(Champ_P1_VEF,ch_transporte.valeur());
      REF(Champ_P1_VEF) inconnue;
      inconnue = inco;
    }
  if (sub_type(Champ_Q1_EF,ch_transporte.valeur()))
    {
      const Champ_Q1_EF& inco = ref_cast(Champ_Q1_EF,ch_transporte.valeur());
      REF(Champ_Q1_EF) inconnue;
      inconnue = inco;
    }
  */
  la_zone_EF = zEF;
  la_zcl_EF = zclEF;
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int nb_comp = 1;
// int nb_dim = resu.nb_dim();
// if(nb_dim==2)
// nb_comp=resu.dimension(1);
  (ref_cast(DoubleTab,flux_bords_)).resize(zone_EF.nb_faces_bord(),nb_comp);
  flux_bords_=0.;
}
double Op_Diff_EF_base::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 97 of file Op_Diff_EF_base.cpp.
References Zone_EF::carre_pas_du_maillage(), Zone_EF::carre_pas_maille(), Operateur_Diff_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Objet_U::dimension, DMAXFLOAT, DMINFLOAT, Zone::domaine(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), la_zone_EF, Zone::les_elems(), Domaine::les_sommets(), local_max_vect(), Process::mp_min(), Zone_dis_base::nb_elem(), nu_, ref_cast, remplir_nu(), sub_type, valeur(), Ref_Zone_EF::valeur(), Champ_Proto::valeurs(), and Zone_dis_base::zone().
{
  remplir_nu(nu_);
// La diffusivite est constante dans le domaine donc
//
// dt_diff = h*h/diffusivite
  double dt_stab = DMAXFLOAT;
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  if (! has_champ_masse_volumique())
    {
      if (1)
        {
// Methode "standard" de calcul du pas de temps
// Ce calcul est tres conservatif: si le max de la diffusivite
// n'est pas atteint a l'endroit ou le min de delta_h_carre est atteint,
// le pas de temps est sous-estime.
          const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
          const DoubleVect&      valeurs_diffusivite = champ_diffusivite.valeurs();
          double alpha_max = local_max_vect(valeurs_diffusivite);
          if ((alpha_max == 0.)||(zone_EF.nb_elem()==0))
            dt_stab = DMAXFLOAT;
          else
            {
              const double min_delta_h_carre = zone_EF.carre_pas_du_maillage();
              dt_stab = min_delta_h_carre / (2. * dimension * alpha_max);
            }
        }
      else
        {
          const Zone_EF& zone_ef=ref_cast(Zone_EF,equation().zone_dis().valeur());
          const DoubleTab& coord=zone_ef.zone().domaine().les_sommets();
          const IntTab& elems=zone_ef.zone().les_elems() ;
          const Champ_base& champ_diffusivite = diffusivite_pour_pas_de_temps();
          const DoubleVect&      valeurs_diffusivite = champ_diffusivite.valeurs();
          const int nb_elem = zone_EF.nb_elem();
          int elem;
// Champ de masse volumique variable.
          for (elem = 0; elem < nb_elem; elem++)
            {
              const double diffu   = valeurs_diffusivite(elem)+DMINFLOAT;
              double dx2=0,dl;
              for (int d=0; d<3; d++)
                {
                  dl=coord(elems(elem,0),d)-coord(elems(elem,7),d);
                  dx2+=(dl*dl);
                }
              const double dt      = dx2 /  diffu;
              if (dt_stab > dt)
                {
                  dt_stab = dt;
// Cerr<<" ii "<<elem<<" "<<diffu<<" "<<dx2<<finl;
                }
            }
        }
    }
  else
    {
      const double           deux_dim      = 2. * Objet_U::dimension;
      const Champ_base& champ_diffu   = diffusivite();
      const DoubleTab&       valeurs_diffu = champ_diffu.valeurs();
      const Champ_base&      champ_rho     = get_champ_masse_volumique();
      const DoubleTab&       valeurs_rho   = champ_rho.valeurs();
      assert(sub_type(Champ_Fonc_P0_base, champ_rho));
      assert(sub_type(Champ_Fonc_P0_base, champ_diffu));
      const int nb_elem = zone_EF.nb_elem();
      int elem;
// Champ de masse volumique variable.
      for (elem = 0; elem < nb_elem; elem++)
        {
          const double h_carre = zone_EF.carre_pas_maille(elem);
          const double diffu   = valeurs_diffu(elem);
          const double rho     = valeurs_rho(elem);
          const double dt      = h_carre * rho / (deux_dim * diffu);
          if (dt_stab > dt)
            dt_stab = dt;
        }
    }
  dt_stab = Process::mp_min(dt_stab);
  return dt_stab;
}
virtual int Op_Diff_EF_base::duplique () const [pure virtual]
Implements Operateur_Diff_base.
Implemented in Op_Diff_EF, and Op_Diff_option_EF.
const Type_info * Op_Diff_EF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 33 of file Op_Diff_EF_base.cpp.
int Op_Diff_EF_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 57 of file Op_Diff_EF_base.cpp.
{
  return Op_EF_base::impr(os, *this);
}
const Type_info * Op_Diff_EF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 33 of file Op_Diff_EF_base.cpp.
Sortie & Op_Diff_EF_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 43 of file Op_Diff_EF_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Diff_EF_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 52 of file Op_Diff_EF_base.cpp.
{
  return s ;
}
virtual void Op_Diff_EF_base::remplir_nu (DoubleTab &) const [pure virtual]
Implemented in Op_Diff_EF.
Referenced by calculer_dt_stab().
const Op_Diff_EF_base & Op_Diff_EF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 33 of file Op_Diff_EF_base.cpp.
Op_Diff_EF_base & Op_Diff_EF_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 33 of file Op_Diff_EF_base.cpp.
Member Data Documentation
Ref_Champ_Inc_base Op_Diff_EF_base::inconnue [protected]
Definition at line 72 of file Op_Diff_EF_base.h.
const Type_info Op_Diff_EF_base::info_obj [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Diff_EF, and Op_Diff_option_EF.
Definition at line 59 of file Op_Diff_EF_base.h.
Ref_Zone_Cl_EF Op_Diff_EF_base::la_zcl_EF [protected]
Definition at line 71 of file Op_Diff_EF_base.h.
Referenced by Op_Diff_EF::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Diff_EF::ajouter_contributions_bords(), Op_Diff_EF::ajouter_new(), Op_Diff_EF::ajouter_vectoriel_dim2_nbn_4(), Op_Diff_EF::ajouter_vectoriel_dim3_nbn_8(), Op_Diff_EF::ajouter_vectoriel_gen(), associer(), Op_Diff_EF::dimensionner(), and Op_Diff_EF::modifier_pour_Cl().
Ref_Zone_EF Op_Diff_EF_base::la_zone_EF [protected]
Definition at line 70 of file Op_Diff_EF_base.h.
Referenced by Op_Diff_EF::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Diff_EF::ajouter_contributions_bords(), associer(), calculer_dt_stab(), Op_Diff_EF::dimensionner(), Op_Diff_EF::modifier_pour_Cl(), and Op_Diff_EF::remplir_nu().
DoubleTab Op_Diff_EF_base::nu_ [mutable, protected]
Definition at line 73 of file Op_Diff_EF_base.h.
Referenced by Op_Diff_EF::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Diff_EF::ajouter_new(), Op_Diff_EF::ajouter_scalaire_dim2_nbn_4(), Op_Diff_EF::ajouter_scalaire_dim3_nbn_8(), Op_Diff_EF::ajouter_scalaire_gen(), Op_Diff_EF::ajouter_vectoriel_dim2_nbn_4(), Op_Diff_EF::ajouter_vectoriel_dim3_nbn_8(), Op_Diff_EF::ajouter_vectoriel_gen(), and calculer_dt_stab().
The documentation for this class was generated from the following files:
src/EF/Operateurs/Op_Diff_EF_base.h
src/EF/Operateurs/Op_Diff_EF_base.cpp