TRUST: Champ_P1iP1B_implementation Class Reference
Champ_P1iP1B_implementation Class Reference abstract
#include <Champ_P1iP1B_implementation.h>
Public Member Functions
Champ_P1iP1B_implementation ()
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
int imprime_P1B (Sortie &, int) const
DoubleTab & filtrage (const Zone_VEF_PreP1b &, const Champ_base &) const
Methode pour filtrer le champ.
const DoubleTab & champ_filtre () const
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Public Attributes
int Condition_Neumann_imposee_
Drapeau pour savoir s'il y'a des CL de Neumann (influe sur le filtrage)
Protected Member Functions
void completer (const Zone_Cl_dis_base &zcl)
virtual const Zone_VEF_PreP1b & zone_vef () const =0
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Protected Attributes
DoubleTab champ_filtre_
Contient les valeurs du champ filtre.
Matrice matrice_filtrage_
Contient la matrice necessaire au filtrage (evite d'avoir a la recalculer)
double temps_filtrage_
Temps du dernier filtrage (va servir a ne pas refiltrer inutilement)
const double * adresse_champ_filtre_
Adresse du champ filtre (va servir a ne pas refiltrer inutilement)
Detailed Description
Definition at line 27 of file Champ_P1iP1B_implementation.h.
Constructor & Destructor Documentation
Champ_P1iP1B_implementation()
Champ_P1iP1B_implementation::Champ_P1iP1B_implementation () inline
Definition at line 31 of file Champ_P1iP1B_implementation.h.
  {
    temps_filtrage_ = -DMAXFLOAT;
    adresse_champ_filtre_ = NULL;
    Condition_Neumann_imposee_ = 0;
  }
References adresse_champ_filtre_, Condition_Neumann_imposee_, DMAXFLOAT, and temps_filtrage_.
Member Function Documentation
champ_filtre()
const DoubleTab & Champ_P1iP1B_implementation::champ_filtre () const inline
Definition at line 55 of file Champ_P1iP1B_implementation.h.
{ return champ_filtre_; }
References champ_filtre_.
Referenced by Op_Grad_VEF_P1B_Face::impr().
completer()
void Champ_P1iP1B_implementation::completer (const Zone_Cl_dis_base & zcl) protected
Definition at line 481 of file Champ_P1iP1B_implementation.cpp.
{
  const Conds_lim& les_cl = zcl.les_conditions_limites();
  Condition_Neumann_imposee_ = 0;
  for(int i=0; i<les_cl.size(); i++)
    if (sub_type(Neumann_sortie_libre,les_cl[i].valeur()))
      Condition_Neumann_imposee_ = 1;
}
References Condition_Neumann_imposee_, Zone_Cl_dis_base::les_conditions_limites(), vect_impl::size(), sub_type, and valeur().
Referenced by Champ_Fonc_P1_isoP1Bulle::completer(), and Champ_P1_isoP1Bulle::completer().
filtrage()
DoubleTab & Champ_P1iP1B_implementation::filtrage (const Zone_VEF_PreP1b & zvef, const Champ_base & un_champ) const
Methode pour filtrer le champ.
Definition at line 451 of file Champ_P1iP1B_implementation.cpp.
{
// Filtrage si supports element et sommet presents au moins
  if (zvef.get_alphaE() && zvef.get_alphaS())
    {
// Pas de filtrage si deja fait sur ce champ:
      if (un_champ.valeurs().addr()==adresse_champ_filtre_ && un_champ.temps()==temps_filtrage_)
        return champ_filtre_;
// On copie le champ a filtrer dans le tableau qui contiendra le champ filtre
      champ_filtre_=un_champ.valeurs();
      temps_filtrage_=un_champ.temps();
      adresse_champ_filtre_=un_champ.valeurs().addr();
// Cout << "Filtrage du champ " << un_champ.le_nom() << " au temps " << un_champ.temps() << finl;
// Correction du champ
      corriger(zvef, champ_filtre_, matrice_filtrage_, Condition_Neumann_imposee_);
      Debog::verifier("champ apres filtre=", champ_filtre_);
      return champ_filtre_;
    }
  else
    {
      champ_filtre_=un_champ.valeurs();
      return champ_filtre_;
    }
}
References TRUSTArray< _TYPE_ >::addr(), adresse_champ_filtre_, champ_filtre_, Condition_Neumann_imposee_, corriger(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), matrice_filtrage_, Champ_base::temps(), temps_filtrage_, Champ_Proto::valeurs(), and Debog::verifier().
Referenced by Op_Grad_VEF_P1B_Face::impr(), valeur_aux_elems(), and valeur_aux_sommets().
imprime_P1B()
int Champ_P1iP1B_implementation::imprime_P1B (Sortie & , int) const
remplir_coord_noeuds()
DoubleTab & Champ_P1iP1B_implementation::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
Definition at line 215 of file Champ_P1iP1B_implementation.cpp.
{
  const Zone_VEF_PreP1b& zvef=zone_vef();
  const Zone& la_zone=zvef.zone();
  const Domaine& dom=la_zone.domaine();
  const DoubleTab& coord_sommets=dom.coord_sommets();
  int nbe=zvef.nb_elem_tot();
  int nbs=zvef.nb_som_tot();
  int pre=zvef.numero_premier_element();
  int prs=zvef.numero_premier_sommet();
  int dimension=Objet_U::dimension;
  const DoubleTab& xg = zvef.xp();
  int k=pre;
  coord.resize(nbe+nbs,dimension);
  {
    for(int i=0; i<nbe; i++)
      {
        for(int j=0; j<dimension; j++)
          coord(k,j)=xg(i,j);
        k++;
      }
  }
  k=prs;
  {
    for(int i=0; i<nbs; i++)
      {
        for(int j=0; j<dimension; j++)
          coord(k,j)=coord_sommets(i,j);
        k++;
      }
  }
  return coord;
}
References Domaine::coord_sommets(), Objet_U::dimension, Zone::domaine(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_som_tot(), Zone_VEF_PreP1b::numero_premier_element(), Zone_VEF_PreP1b::numero_premier_sommet(), TRUSTTab< _TYPE_ >::resize(), Zone_VF::xp(), Zone_dis_base::zone(), and zone_vef().
Referenced by Champ_P1_isoP1Bulle::remplir_coord_noeuds(), and Champ_Fonc_P1_isoP1Bulle::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_P1iP1B_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
Definition at line 251 of file Champ_P1iP1B_implementation.cpp.
{
  Cerr << "Pas code " << finl;
  assert(0);
  Process::exit();
  return 1;
}
References Cerr, Process::exit(), and finl.
Referenced by Champ_Fonc_P1_isoP1Bulle::remplir_coord_noeuds_et_polys().
trace()
DoubleTab & Champ_P1iP1B_implementation::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const protected
Definition at line 490 of file Champ_P1iP1B_implementation.cpp.
{
  assert(distant==0);
  const Front_VF& fr_vf = ref_cast(Front_VF, fr);
  const Zone_VEF_PreP1b& zone_dis = zone_vef();
  const DoubleTab& cg_faces = zone_dis.xv();
  int nb_faces_fr = fr_vf.nb_faces();
  int face, elem;
  assert(x.dimension(0)==fr_vf.nb_faces());
  IntVect elem_voisins(nb_faces_fr);
  elem_voisins = -1;
  DoubleTab cg_faces_fr(nb_faces_fr,Objet_U::dimension);
  DoubleTab val_interp(nb_faces_fr, 1);
// On recupere les elements voisins des faces de la frontiere
  for (int i=0; i<nb_faces_fr; i++)
    {
      face = fr_vf.num_premiere_face()+i;
      elem = zone_dis.face_voisins(face,0);
      if (elem==-1)
        elem = zone_dis.face_voisins(face,1);
      elem_voisins(i) = elem;
    }
// Remplissage du tableau contenant les coordonnees
// du centre de gravite des faces de la frontiere
  for (int num_face=0; num_face<nb_faces_fr; num_face++)
    for (int dim=0; dim<Objet_U::dimension; dim++)
      {
        face = fr_vf.num_premiere_face()+num_face;
        cg_faces_fr(num_face,dim) = cg_faces(face,dim);
      }
// Interpolation des valeurs du champ au centre de gravite des faces frontieres
  valeur_aux_elems(cg_faces_fr,elem_voisins,val_interp);
  for (int i=0; i<nb_faces_fr; i++)
    {
      x(i,0) = val_interp(i);
    }
// Useless ? x.echange_espace_virtuel();
  return x;
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::face_voisins(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, valeur_aux_elems(), Zone_VF::xv(), and zone_vef().
Referenced by Champ_Fonc_P1_isoP1Bulle::trace(), and Champ_P1_isoP1Bulle::trace().
valeur_a_elem()
DoubleVect & Champ_P1iP1B_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const override virtual
Implements Champ_implementation.
Definition at line 34 of file Champ_P1iP1B_implementation.cpp.
{
  int dimension=Objet_U::dimension;
  DoubleTab vals(1,1);
  IntVect les_polys(1);
  DoubleTab positions(1,dimension);
  les_polys(0) = le_poly;
  for (int i=0; i<dimension; i++)
    positions(0,i) = position(i);
  valeur_aux_elems(positions, les_polys, vals);
  val(0) = vals(0,0);
  return val;
}
References Objet_U::dimension, and valeur_aux_elems().
Referenced by Champ_Fonc_P1_isoP1Bulle::valeur_a_elem(), and Champ_P1_isoP1Bulle::valeur_a_elem().
valeur_a_elem_compo()
double Champ_P1iP1B_implementation::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 51 of file Champ_P1iP1B_implementation.cpp.
{
  double val=0;
  int dimension=Objet_U::dimension;
  DoubleVect vals(1);
  IntVect les_polys(1);
  DoubleTab positions(1,dimension);
  les_polys(0) = le_poly;
  for (int i=0; i<dimension; i++)
    positions(0,i) = position(i);
  valeur_aux_elems_compo(positions, les_polys, vals, ncomp);
  val = vals(0);
  return val;
}
References Objet_U::dimension, and valeur_aux_elems_compo().
Referenced by Champ_Fonc_P1_isoP1Bulle::valeur_a_elem_compo(), and Champ_P1_isoP1Bulle::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_P1iP1B_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
< nb_compo_ > 1
Implements Champ_implementation.
Definition at line 74 of file Champ_P1iP1B_implementation.cpp.
{
  int som;
  double xs,ys,zs=0;
// zs bien initialise en 3D
  const Zone_VEF_PreP1b& zvef = zone_vef();
  const Zone& zone_geom = zvef.zone();
  const DoubleTab& coord = zone_geom.domaine().coord_sommets();
  const IntTab& sommet_poly = zone_geom.les_elems();
  int prs=zvef.numero_premier_sommet();
  int nb_compo_=le_champ().nb_comp();
  int dimension=Objet_U::dimension;
  const int les_polys_size=les_polys.size();
// TODO : FIXME
// For FT the resize should be done in its good position and not here ...
  if (val.nb_dim() == 1 ) val.resize(les_polys_size,1);
  assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
  assert(val.line_size() == nb_compo_);
// Filtrage du champ dans le tableau champ_filtre_
  champ_filtre_=filtrage(zvef,le_champ());
  if (nb_compo_ == 1)
    {
      for(int rang_poly=0; rang_poly<les_polys_size; rang_poly++)
        {
// On initialise
          val(rang_poly,0) = 0.;
// On prend le_poly
          int le_poly=les_polys(rang_poly);
          if (le_poly != -1)
            {
// Contribution P0
              if (zvef.get_alphaE())
                val(rang_poly,0) += champ_filtre_(le_poly);
// Contribution P1
              if (zvef.get_alphaS())
                {
                  xs = positions(rang_poly,0);
                  ys = positions(rang_poly,1);
                  if (dimension == 3)
                    zs = positions(rang_poly,2);
// Calcul par les fonctions de forme P1 du champ filtre
// au point (xs,yz,zs)
                  for (int i=0; i<dimension+1; i++)
                    {
                      som = prs+sommet_poly(le_poly,i);
                      double champ_filtre_som=champ_filtre_(som);
                      double li=0.;
                      if (dimension == 2)
                        li=coord_barycentrique_P1_triangle(sommet_poly,
                                                           coord, xs, ys,
                                                           le_poly, i);
                      else if (dimension == 3)
                        li=coord_barycentrique_P1_tetraedre(sommet_poly,
                                                            coord, xs, ys, zs,
                                                            le_poly, i);
                      val(rang_poly,0) += champ_filtre_som * li;
                    }
                }
            }
        }
    }
  else //!< nb_compo_ > 1
    {
      Cerr << "Vous en etes deja la vous ?" << finl;
      Process::exit();
    }
  return val;
}
References Cerr, champ_filtre_, coord_barycentrique_P1_tetraedre(), coord_barycentrique_P1_triangle(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Zone::domaine(), Process::exit(), filtrage(), finl, Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Champ_implementation::le_champ(), Zone::les_elems(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_VEF_PreP1b::numero_premier_sommet(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::size(), Zone_dis_base::zone(), and zone_vef().
Referenced by trace(), valeur_a_elem(), Champ_Fonc_P1_isoP1Bulle::valeur_aux_elems(), and Champ_P1_isoP1Bulle::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_P1iP1B_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 152 of file Champ_P1iP1B_implementation.cpp.
{
  Cerr << "Champ_P1iP1B_implementation::valeur_aux_elems_compo non code." << finl;
// Factoriser le code avec la methode valeur_aux_elems()
  Process::exit();
  return val;
}
References Cerr, Process::exit(), and finl.
Referenced by valeur_a_elem_compo(), Champ_Fonc_P1_isoP1Bulle::valeur_aux_elems_compo(), and Champ_P1_isoP1Bulle::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_P1iP1B_implementation::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const override virtual
< Support P0
< Support P1
< nb_compo_ > 1
Implements Champ_implementation.
Definition at line 163 of file Champ_P1iP1B_implementation.cpp.
{
  const Zone_VEF_PreP1b& zvef = zone_vef();
  int nb_compo_=le_champ().nb_comp();
  assert(nb_compo_ == val.line_size());
// Filtrage du champ pour le postraitement (contenu dans le tableau champ_filtre_)
  champ_filtre_=filtrage(zvef,le_champ());
  if (zvef.get_alphaE()) //!< Support P0
    {
      Champ_P0_VEF tmp;
      tmp.associer_zone_dis_base(zvef);
      tmp.valeurs() = champ_filtre_;
      tmp.valeur_aux_sommets(zvef.zone().domaine(), val);
    }
  if (zvef.get_alphaS()) //!< Support P1
    {
      int nbs=zvef.nb_som();
      int prs=zvef.numero_premier_sommet();
      if (nb_compo_ == 1)
        {
          int som,num_som;
          for (num_som = 0; num_som<nbs; num_som++)
            {
              som = prs+num_som;
              val(num_som,0) += champ_filtre_(som);
            }
        }
      else //!< nb_compo_ > 1
        {
          Cerr << "Vous en etes deja la vous ?" << finl;
          Process::exit();
        }
    }
  return val;
}
References Champ_P0_VEF::associer_zone_dis_base(), Cerr, champ_filtre_, Zone::domaine(), Process::exit(), filtrage(), finl, Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_ >::line_size(), Field_base::nb_comp(), Zone_VEF_PreP1b::nb_som(), Zone_VEF_PreP1b::numero_premier_sommet(), Champ_Inc_P0_base::valeur_aux_sommets(), Champ_Inc_base::valeurs(), Zone_dis_base::zone(), and zone_vef().
Referenced by Champ_Fonc_P1_isoP1Bulle::valeur_aux_sommets(), and Champ_P1_isoP1Bulle::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_P1iP1B_implementation::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 204 of file Champ_P1iP1B_implementation.cpp.
{
  Cerr << "Champ_P1iP1B_implementation::valeur_aux_sommets_compo pas code." << finl;
// Factoriser avec la methode valeur_aux_sommets()
  Process::exit();
  return val;
}
References Cerr, Process::exit(), and finl.
Referenced by Champ_Fonc_P1_isoP1Bulle::valeur_aux_sommets_compo(), and Champ_P1_isoP1Bulle::valeur_aux_sommets_compo().
zone_vef()
virtual const Zone_VEF_PreP1b & Champ_P1iP1B_implementation::zone_vef () const protected pure virtual
Implemented in Champ_Fonc_P1_isoP1Bulle, and Champ_P1_isoP1Bulle.
Referenced by remplir_coord_noeuds(), trace(), valeur_aux_elems(), and valeur_aux_sommets().
Member Data Documentation
adresse_champ_filtre_
const double* Champ_P1iP1B_implementation::adresse_champ_filtre_ mutable protected
Adresse du champ filtre (va servir a ne pas refiltrer inutilement)
Definition at line 64 of file Champ_P1iP1B_implementation.h.
Referenced by Champ_P1iP1B_implementation(), and filtrage().
champ_filtre_
DoubleTab Champ_P1iP1B_implementation::champ_filtre_ mutable protected
Contient les valeurs du champ filtre.
Definition at line 61 of file Champ_P1iP1B_implementation.h.
Referenced by champ_filtre(), filtrage(), valeur_aux_elems(), and valeur_aux_sommets().
Condition_Neumann_imposee_
int Champ_P1iP1B_implementation::Condition_Neumann_imposee_
Drapeau pour savoir s'il y'a des CL de Neumann (influe sur le filtrage)
Definition at line 57 of file Champ_P1iP1B_implementation.h.
Referenced by Champ_P1iP1B_implementation(), completer(), and filtrage().
matrice_filtrage_
Matrice Champ_P1iP1B_implementation::matrice_filtrage_ mutable protected
Contient la matrice necessaire au filtrage (evite d'avoir a la recalculer)
Definition at line 62 of file Champ_P1iP1B_implementation.h.
Referenced by filtrage().
temps_filtrage_
double Champ_P1iP1B_implementation::temps_filtrage_ mutable protected
Temps du dernier filtrage (va servir a ne pas refiltrer inutilement)
Definition at line 63 of file Champ_P1iP1B_implementation.h.
Referenced by Champ_P1iP1B_implementation(), and filtrage().
The documentation for this class was generated from the following files:
src/P1NCP1B/Champs/Champ_P1iP1B_implementation.h
src/P1NCP1B/Champs/Champ_P1iP1B_implementation.cpp