TRUST: Deriv_Solveur_Masse_base Class Reference
Deriv_Solveur_Masse_base Class Reference
#include <Solveur_Masse.h>
Public Member Functions
~Deriv_Solveur_Masse_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Solveur_Masse_base ()
Deriv_Solveur_Masse_base (const Deriv_Solveur_Masse_base &)
const Solveur_Masse_base & valeur () const
Solveur_Masse_base & valeur ()
const Solveur_Masse_base * operator-> () const
Solveur_Masse_base * operator-> ()
const Deriv_Solveur_Masse_base & operator= (const Solveur_Masse_base &)
const Deriv_Solveur_Masse_base & operator= (const Deriv_Solveur_Masse_base &)
operator const Solveur_Masse_base & () const
operator Solveur_Masse_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Deriv_Solveur_Masse_base & self_cast (Objet_U &)
static const
Deriv_Solveur_Masse_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Solveur_Masse_base * pointeur_
Detailed Description
Definition at line 31 of file Solveur_Masse.h.
Constructor & Destructor Documentation
Deriv_Solveur_Masse_base::~Deriv_Solveur_Masse_base ()
Definition at line 30 of file Solveur_Masse.cpp.
Deriv_Solveur_Masse_base::Deriv_Solveur_Masse_base ()
Definition at line 30 of file Solveur_Masse.cpp.
Deriv_Solveur_Masse_base::Deriv_Solveur_Masse_base (const Deriv_Solveur_Masse_base & t)
Definition at line 30 of file Solveur_Masse.cpp.
Member Function Documentation
Objet_U * Deriv_Solveur_Masse_base::cree_instance () [static]
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
int Deriv_Solveur_Masse_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
const Type_info * Deriv_Solveur_Masse_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
const Type_info & Deriv_Solveur_Masse_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 30 of file Solveur_Masse.cpp.
const Type_info * Deriv_Solveur_Masse_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
Deriv_Solveur_Masse_base::operator const Solveur_Masse_base & () const
Definition at line 30 of file Solveur_Masse.cpp.
Deriv_Solveur_Masse_base::operator Solveur_Masse_base & ()
Definition at line 30 of file Solveur_Masse.cpp.
const Solveur_Masse_base * Deriv_Solveur_Masse_base::operator-> () const [inline]
Definition at line 31 of file Solveur_Masse.h.
: public DERIV(Solveur_Masse_base), public MorEqn
Solveur_Masse_base * Deriv_Solveur_Masse_base::operator-> () [inline]
Definition at line 31 of file Solveur_Masse.h.
: public DERIV(Solveur_Masse_base), public MorEqn
const Deriv_Solveur_Masse_base & Deriv_Solveur_Masse_base::operator= (const Deriv_Solveur_Masse_base & t)
Definition at line 30 of file Solveur_Masse.cpp.
const Deriv_Solveur_Masse_base & Deriv_Solveur_Masse_base::operator= (const Solveur_Masse_base & t)
Definition at line 30 of file Solveur_Masse.cpp.
Sortie & Deriv_Solveur_Masse_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
Entree & Deriv_Solveur_Masse_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
const Deriv_Solveur_Masse_base & Deriv_Solveur_Masse_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
Deriv_Solveur_Masse_base & Deriv_Solveur_Masse_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
void Deriv_Solveur_Masse_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 30 of file Solveur_Masse.cpp.
unsigned Deriv_Solveur_Masse_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Solveur_Masse.
Definition at line 30 of file Solveur_Masse.cpp.
const Solveur_Masse_base & Deriv_Solveur_Masse_base::valeur () const [inline]
Definition at line 31 of file Solveur_Masse.h.
Referenced by Solveur_Masse::ajouter_masse(), Solveur_Masse::ajouter_masse_dt_local(), Solveur_Masse::appliquer(), Solveur_Masse::assembler(), Equation_base::calculer_champ_conserve(), calculer_inv_volume(), QDM_Multiphase::completer(), Equation_base::completer(), Solveur_Masse::corriger_solution(), Equation_base::dimensionner_matrice_sans_mem(), Solveur_Masse::get_masse_divide_by_local_dt(), Solveur_Masse::get_masse_dt_local(), Equation_base::has_interface_blocs(), Solveur_Masse::mettre_a_jour(), Equation_base::preparer_calcul(), and Solveur_Masse::typer().
: public DERIV(Solveur_Masse_base), public MorEqn
Solveur_Masse_base & Deriv_Solveur_Masse_base::valeur () [inline]
Definition at line 31 of file Solveur_Masse.h.
: public DERIV(Solveur_Masse_base), public MorEqn
Member Data Documentation
const Type_info Deriv_Solveur_Masse_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Solveur_Masse.
Definition at line 31 of file Solveur_Masse.h.
Solveur_Masse_base* Deriv_Solveur_Masse_base::pointeur_ [private]
Definition at line 31 of file Solveur_Masse.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Solveur_Masse.h
src/Kernel/Framework/Solveur_Masse.cpp