TRUST: Flux_interfacial_PolyMAC Class Reference
Flux_interfacial_PolyMAC Class Reference
Classe Flux_interfacial_PolyMAC
Cette classe implemente dans PolyMAC un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
le calcul de C_{kl} est realise par la hierarchie Coefficient_Flux_interfacial_base.
#include <Flux_interfacial_PolyMAC.h>
Public Member Functions
Flux_interfacial_PolyMAC ()
~Flux_interfacial_PolyMAC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
DoubleTab & qpi () const
DoubleTab & dT_qpi () const
DoubleTab & da_qpi () const
DoubleTab & dp_qpi () const
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Flux_interfacial_PolyMAC & self_cast (Objet_U &)
static const Flux_interfacial_PolyMAC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
DoubleTab qpi_
DoubleTab dT_qpi_
DoubleTab da_qpi_
DoubleTab dp_qpi_
Ref_Correlation correlation_
Additional Inherited Members
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Classe Flux_interfacial_PolyMAC
Cette classe implemente dans PolyMAC un operateur de frottement interfacial
de la forme F_{kl} = - F_{lk} = - C_{kl} (u_k - u_l)
le calcul de C_{kl} est realise par la hierarchie Coefficient_Flux_interfacial_base.
Definition at line 32 of file Flux_interfacial_PolyMAC.h.
Constructor & Destructor Documentation
Flux_interfacial_PolyMAC()
Flux_interfacial_PolyMAC::Flux_interfacial_PolyMAC ()
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
~Flux_interfacial_PolyMAC()
Flux_interfacial_PolyMAC::~Flux_interfacial_PolyMAC ()
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
Member Function Documentation
ajouter_blocs()
void Flux_interfacial_PolyMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
< memes stencils que celui de l'equation courante
< E. Saikali : initialise dP_G ici sinon fuite memoire ...
< nv(n,n) = ||v(n)||, nv(n, k!=n) = ||v(n)-v(k)||
< k est la phase porteuse
< if the phase l is present
Reimplemented from Source_base.
Definition at line 125 of file Flux_interfacial_PolyMAC.cpp.
{
  const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, equation().probleme());
  const Champ_Elem_PolyMAC& ch = ref_cast(Champ_Elem_PolyMAC, equation().inconnue().valeur());
// Matrice_Morse *mat = matrices.count(ch.le_nom().getString()) ? matrices.at(ch.le_nom().getString()) : NULL;
  const Milieu_composite& milc = ref_cast(Milieu_composite, equation().milieu());
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, equation().zone_dis().valeur());
  const DoubleVect& pe = zone.porosite_elem(), &ve = zone.volumes();
  const tabs_t& der_h = ref_cast(Champ_Inc_base, milc.enthalpie()).derivees();
  const Champ_base& ch_rho = milc.masse_volumique();
  const Champ_Inc_base& ch_alpha = pbm.eq_masse.inconnue().valeur(), &ch_a_r = pbm.eq_masse.champ_conserve(), &ch_vit = pbm.eq_qdm.inconnue().valeur(),
                        &ch_temp = pbm.eq_energie.inconnue().valeur(), &ch_p = pbm.eq_qdm.pression().valeur(),
                         *pch_rho = sub_type(Champ_Inc_base, ch_rho) ? &ref_cast(Champ_Inc_base, ch_rho) : NULL;
  const DoubleTab& inco = ch.valeurs(), &alpha = ch_alpha.valeurs(), &press = ch_p.valeurs(), &temp  = ch_temp.valeurs(), &pvit = ch_vit.passe(),
                   &h = milc.enthalpie().valeurs(), *dP_h = der_h.count("pression") ? &der_h.at("pression") : NULL, *dT_h = der_h.count("temperature") ? &der_h.at("temperature") : NULL,
                    &lambda = milc.conductivite().passe(), &mu = milc.viscosite_dynamique().passe(), &rho = milc.masse_volumique().passe(), &Cp = milc.capacite_calorifique().passe(),
                     &p_ar = ch_a_r.passe(), &a_r = ch_a_r.valeurs(), &qi = qpi(), &dTqi = dT_qpi(), &daqi = da_qpi(), &dpqi = dp_qpi();
  Matrice_Morse *Mp = matrices.count("pression")    ? matrices.at("pression")    : NULL,
                 *Mt = matrices.count("temperature") ? matrices.at("temperature") : NULL,
                  *Ma = matrices.count("alpha") ? matrices.at("alpha") : NULL,
                   *Mai = matrices.count("interfacial_area") ? matrices.at("interfacial_area") : NULL;
  int i, j, col, e, d, D = dimension, k, l, n, N = inco.line_size(), nf_tot = zone.nb_faces_tot(),
                       cL = lambda.dimension_tot(0) == 1, cM = mu.dimension_tot(0) == 1, cR = rho.dimension_tot(0) == 1, cCp = Cp.dimension_tot(0) == 1, is_therm;
  const Flux_interfacial_base& correlation_fi = ref_cast(Flux_interfacial_base, correlation_.valeur().valeur());
  const Changement_phase_base *correlation_G = pbm.has_correlation("changement_phase") ? &ref_cast(Changement_phase_base, pbm.get_correlation("changement_phase").valeur()) : NULL;
  double dt = equation().schema_temps().pas_de_temps(), alpha_min = 1.e-6;
  /* limiteur de changement de phase : on limite gamma pour eviter d'avoir alpha_k < 0 dans une phase */
  /* pour cela, on assemble l'equation de masse sans changement de phase */
  DoubleTrav sec_m(alpha); //residus
  std::map<std::string, Matrice_Morse> mat_m_stockees;
  matrices_t mat_m; //derivees
  for (auto &&n_m : matrices)
    if (n_m.first.find("/") == std::string::npos) /* pour ignorer les inconnues venant d'autres problemes */
      {
        Matrice_Morse& dst = mat_m_stockees[n_m.first], &src = *n_m.second;
        dst.get_set_tab1().ref_array(src.get_set_tab1()); //!< memes stencils que celui de l'equation courante
        dst.get_set_tab2().ref_array(src.get_set_tab2());
        dst.set_nb_columns(src.nb_colonnes());
        dst.get_set_coeff().resize(src.get_set_coeff().size()); //coeffs nuls
        mat_m[n_m.first] = &dst;
      }
  const Masse_Multiphase& eq_m = pbm.eq_masse;
  for (i = 0; i < eq_m.nombre_d_operateurs(); i++) /* tous les operateurs */
    eq_m.operateur(i).l_op_base().ajouter_blocs(mat_m, sec_m, semi_impl);
  for (i = 0; i < eq_m.sources().size(); i++)
    if (!sub_type(Flux_interfacial_PolyMAC, eq_m.sources()(i).valeur())) /* toutes les sources sauf le flux interfacial */
      eq_m.sources()(i).valeur().ajouter_blocs(mat_m, sec_m, semi_impl);
  std::vector<std::array<Matrice_Morse *, 2>> vec_m; //vecteur "matrice source, matrice de destination"
  for (auto &&n_m : matrices)
    if (n_m.first.find("/") == std::string::npos && mat_m[n_m.first]->get_tab1().size() > 1) vec_m.push_back({{ mat_m[n_m.first], n_m.second }});
  /* elements */
// coefficients et plein de derivees...
  DoubleTrav hi(N, N), dT_hi(N, N, N), da_hi(N, N, N), dP_hi(N, N), dT_phi(N), da_phi(N), dT_G(N), da_G(N), nv(N, N);
  for (e = 0; e < zone.nb_elem(); e++)
    {
// double vol = pe(e) * ve(e), x, G = 0, dv_min = 0.1, dh = zone.diametre_hydraulique_elem()(e, 0), dP_G = 0.; // E. Saikali : initialise dP_G ici sinon fuite memoire ...
// PL ToDo: Uniformiser diametre_hydraulique_elem (vecteur) pour C3D et F5
      double vol = pe(e) * ve(e), x, G = 0, dv_min = 0.1, dh = zone.diametre_hydraulique_elem()(e), dP_G = 0.; //!< E. Saikali : initialise dP_G ici sinon fuite memoire ...
      for (nv = 0, d = 0; d < D; d++)
        for (n = 0; n < N; n++)
          for (k = 0 ; k<N ; k++) nv(n, k) += std::pow( pvit(nf_tot + D * e + d, n) - ((n!=k) ? pvit(nf_tot + D * e + d, k) : 0) , 2); //!< nv(n,n) = ||v(n)||, nv(n, k!=n) = ||v(n)-v(k)||
      for (n = 0; n < N; n++)
        for (k = 0 ; k<N ; k++) nv(n, k) = std::max(sqrt(nv(n, k)), dv_min);
// coeffs d'echange vers l'interface (explicites)
      correlation_fi.coeffs(dh, &alpha(e, 0), &temp(e, 0), press(e, 0), &nv(0, 0),
                            &lambda(!cL * e, 0), &mu(!cM * e, 0), &rho(!cR * e, 0), &Cp(!cCp * e, 0), e, hi, dT_hi, da_hi, dP_hi);
      for (k = 0; k < N; k++)
        for (l = k + 1; l < N; l++)
          if (milc.has_saturation(k, l)) //flux phase k <-> phase l si saturation
            {
              Saturation_base& sat = milc.get_saturation(k, l);
              if (correlation_G) /* taux de changement de phase par une correlation */
                G = correlation_G->calculer(k, l, dh, &alpha(e, 0), &temp(e, 0), press(e, 0), &nv(0), &lambda(!cL * e, 0), &mu(!cM * e, 0), &rho(!cM * e, 0), &Cp(!cCp * e, 0),
                                            sat, dT_G, da_G, dP_G);
              /* limite thermique */
              double Tk = temp(e, k), Tl = temp(e, l), p = press(e, 0), Ts = sat.Tsat(p), dP_Ts = sat.dP_Tsat(p), //temperature de chaque cote + Tsat + derivees
                     phi = hi(k, l) * (Tk - Ts) + hi(l, k) * (Tl - Ts) + qi(e, k, l) / vol, L = (phi < 0 ? h(e, l) : sat.Hvs(p)) - (phi > 0 ? h(e, k) : sat.Hls(p));
              if ((is_therm = !correlation_G || std::fabs(G) > std::fabs(phi / L))) G = phi / L;
              /* enthalpies des phases (dans le sens correspondant au mode choisi pour G) */
              /* G est-il limite par l'evanescence cote k ou l ? */
              int n_lim = G > 0 ? k : l, sgn = G > 0 ? 1 : -1; //phase sortante
              double Glim = sec_m(e, n_lim) / vol + p_ar(e, n_lim) / dt; //changement de phase max acceptable par cette phase
              if (std::fabs(G) < Glim) n_lim = -1;       //G ne rend pas la phase evanescente -> pas de limitation (n_lim = -2)
              else G = (G > 0 ? 1 : -1) * Glim;//la phase serait evanescente a cause de G -> on le bloque a G_lim (n_lim = k / l)
              double hk = G > 0 ? h(e, k) : sat.Hls(p), dTk_hk = G > 0 && dT_h ? (*dT_h)(e, k) : 0, dP_hk = G > 0 ? (dP_h ? (*dP_h)(e, k) : 0) : sat.dP_Hls(p),
                       hl = G < 0 ? h(e, l) : sat.Hvs(p), dTl_hl = G < 0 && dT_h ? (*dT_h)(e, l) : 0, dP_hl = G < 0 ? (dP_h ? (*dP_h)(e, l) : 0) : sat.dP_Hvs(p);
              if (n_lim < 0 && is_therm) /* derivees de G en limite thermique */
              {
                  double dP_phi = dP_hi(k, l) * (Tk - Ts) + dP_hi(l, k) * (Tl - Ts) - (hi(k, l) + hi(l, k)) * dP_Ts + dpqi(e, k, l) / vol,
                         dTk_L = -dTk_hk, dTl_L = dTl_hl, dP_L = dP_hl - dP_hk;
                  dP_G = (dP_phi - G * dP_L) / L;
                  for (n = 0; n < N; n++) dT_G(n) = ((n == k) * (hi(k, l) - G * dTk_L) + (n == l) * (hi(l, k) - G * dTl_L) + dT_hi(k, l, n) * (Tk - Ts) + dT_hi(l, k, n) * (Tl - Ts) + dTqi(e, k, l, n)) / L;
                  for (n = 0; n < N; n++) da_G(n) = (da_hi(k, l, n) * (Tk - Ts) + da_hi(l, k, n) * (Tl - Ts) + daqi(e, k, l, n)) / L;
                }
              if (sub_type(Masse_Multiphase, equation())) //eq de masse -> changement de phase
                {
                  for (i = 0; i < 2; i++) secmem(e, i ? l : k) -= vol * (i ? -1 : 1) * G;
                  if (n_lim < 0) /* G par limite thermique */
                    {
                      if (Ma)
                        for (i = 0; i < 2; i++)
                          for (n = 0; n < N; n++)  //derivees en alpha
                            (*Ma)(N * e + (i ? l : k), N * e + n) += vol * (i ? -1 : 1) * da_G(n);
                      if (Mt)
                        for (i = 0; i < 2; i++)
                          for (n = 0; n < N; n++)  //derivees en T
                            (*Mt)(N * e + (i ? l : k), N * e + n) += vol * (i ? -1 : 1) * dT_G(n);
                      if (Mp)
                        for (i = 0; i < 2; i++) //derivees en p
                          (*Mp)(N * e + (i ? l : k), e) += vol * (i ? -1 : 1) * dP_G;
                    }
                  else for (auto &s_d : vec_m) /* G par evanescence */
                      for (j = s_d[0]->get_tab1()(N * e + n_lim) - 1; j < s_d[0]->get_tab1()(N * e + n_lim + 1) - 1; j++)
                        for (col = s_d[0]->get_tab2()(j) - 1, x = -s_d[0]->get_coeff()(j), i = 0; i < 2; i++)
                          (*s_d[1])(N * e + (i ? l : k), col) += (i ? -1 : 1) * sgn * x;
                }
              else if (sub_type(Energie_Multiphase, equation())) //eq d'energie -> transfert de chaleur
                {
// on suppose que la limite thermique s'applique d'un cote : c (=0,1) / n_c (=k,l) / signe du flux sortant de la phase k : s_c (=1,-1)
                  int c = (a_r(e, k) > a_r(e, l)), n_c = c ? l : k, n_d = c ? k : l, s_c = c ? -1 : 1;
                  double Tc = c ? Tl : Tk, hc = c ? hl : hk, dT_hc = c ? dTl_hl : dTk_hk, dP_hc = c ? dP_hl : dP_hk;
                  for (i = 0; i < 2; i++) secmem(e, i ? l : k) -= vol * (i ? -1 : 1) * (s_c * hi(n_c, n_d) * (Tc - Ts) + G * hc) - (i != c) * qi(e, k, l);
                  /* derivees (y compris celles en G, sauf dans le cas limite)*/
                  if (Ma)
                    for (i = 0; i < 2; i++)
                      for (n = 0; n < N; n++) //derivees en alpha
                        (*Ma)(N * e + (i ? l : k), N * e + n) += vol * (i ? -1 : 1) * (s_c * da_hi(n_c, n_d, n) * (Tc - Ts) + (n_lim < 0) * da_G(n) * hc) - (i != c) * daqi(e, k, l, n);
                  if (Mt)
                    for (i = 0; i < 2; i++)
                      for (n = 0; n < N; n++) //derivees en T
                        (*Mt)(N * e + (i ? l : k), N * e + n) += vol * (i ? -1 : 1) * (s_c * (dT_hi(n_c, n_d, n) * (Tc - Ts) + (n == n_c) * hi(n_c, n_d)) + (n_lim < 0) * dT_G(n) * hc + G * (n == n_c) * dT_hc) - (i != c) * dTqi(e, k, l, n);
                  if (Mp)
                    for (i = 0; i < 2; i++) //derivees en p
                      (*Mp)(N * e + (i ? l : k), e) += vol * (i ? -1 : 1) * (s_c * (dP_hi(n_c, n_d) * (Tc - Ts) - hi(n_c, n_d) * dP_Ts) + (n_lim < 0) * dP_G * hc + G * dP_hc) - (i != c) * dpqi(e, k, l);
                  if (n_lim >= 0)
                    for (auto &s_d : vec_m) /* derivees de G dans le cas evanescent */
                      for (j = s_d[0]->get_tab1()(N * e + n_lim) - 1; j < s_d[0]->get_tab1()(N * e + n_lim + 1) - 1; j++)
                        for (col = s_d[0]->get_tab2()(j) - 1, x = -s_d[0]->get_coeff()(j), i = 0; i < 2; i++)
                          (*s_d[1])(N * e + (i ? l : k), col) += (i ? -1 : 1) * hc * sgn * x;
                }
              else if (sub_type(Aire_interfaciale, equation())) //eq d'aire interfaciale ; looks like the mass equation ; not a conservation equation !
                if (k==0) //!< k est la phase porteuse
                  if (alpha(e, l) > alpha_min) //!< if the phase l is present
                    {
                      secmem(e, l) += vol * 2./3. * inco(e, l) / (alpha(e, l) * (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * G ;
                      if (n_lim < 0) /* G par limite thermique */
{
                          if (Ma)   //derivees en alpha
{
                              (*Ma)(N * e + l , N * e + l) -= vol * 2./3. * inco(e, l) / (-alpha(e, l)*alpha(e, l) * (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * G;
                              for (n = 0; n < N; n++) (*Ma)(N * e + l , N * e + n) -=
                                  vol * 2./3. * inco(e, l) / (alpha(e, l)              * (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * da_G(n);
                            }
                          if (Mt)   //derivees en T
{
                              if (pch_rho) (*Mt)(N * e + l , N * e + l) -=
                                  vol * 2./3. * inco(e, l) / alpha(e, l)*-pch_rho->derivees().at("temperature")(e, l)/((*pch_rho).valeurs()(e, l)*(*pch_rho).valeurs()(e, l)) * G;
                              for (n = 0; n < N; n++) (*Mt)(N * e + l , N * e + n) -=
                                  vol * 2./3. * inco(e, l) / (alpha(e, l) * (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * dT_G(n);
                            }
                          if (Mp)  //derivees en p
{
                              if (pch_rho) (*Mp)(N * e + l , e) -=
                                  vol * 2./3. * inco(e, l) / alpha(e, l)*-pch_rho->derivees().at("pression")(e, l)/((*pch_rho).valeurs()(e, l)*(*pch_rho).valeurs()(e, l)) * G;
                              for (n = 0; n < N; n++) (*Mp)(N * e + l , N * e + n) -=
                                  vol * 2./3. * inco(e, l) / (alpha(e, l) * (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * dP_G;
                            }
                          if (Mai) //derivees en ai
{
                              (*Mai)(N * e + l , N * e + l) -= vol * 2./3. / (alpha(e, l)* (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * G;
                            } //!< dAi_G a ajouter
                        }
                      else for (auto &s_d : vec_m) /* G par evanescence */
                          for (j = s_d[0]->get_tab1()(N * e + n_lim) - 1; j < s_d[0]->get_tab1()(N * e + n_lim + 1) - 1; j++)
                            for (col = s_d[0]->get_tab2()(j) - 1, x = -s_d[0]->get_coeff()(j), i = 0; i < 2; i++)
                              (*s_d[1])(N * e + l , col) -= 2./3. * inco(e, l) / (alpha(e, l) * (pch_rho ? (*pch_rho).valeurs()(e, l) : rho(e, l))) * sgn * x;
                    }
            }
          else if (sub_type(Energie_Multiphase, equation())) /* pas de saturation : echanges d'energie seulement */
            {
// flux sortant de la phase k : hm * (Tk - Tl)
              double hm = 1. / (1. / hi(k, l) + 1. / hi(l, k)), Tk = temp(e, k), Tl = temp(e, l);
              for (i = 0; i < 2; i++) secmem(e, i ? l : k) -= vol * (i ? -1 : 1) * hm * (Tk - Tl);
              if (Mt)
                for (i = 0; i < 2; i++) //juste des derivees en T
                  {
                    (*Mt)(N * e + (i ? l : k), N * e + k) += vol * (i ? -1 : 1) * hm;
                    (*Mt)(N * e + (i ? l : k), N * e + l) += vol * (i ? 1 : -1) * hm;
                  }
            }
    }
}
References Operateur_base::ajouter_blocs(), Milieu_base::capacite_calorifique(), Equation_base::champ_conserve(), Milieu_base::conductivite(), correlation_, da_qpi(), Objet_U::dimension, dp_qpi(), dT_qpi(), Fluide_base::enthalpie(), Pb_Multiphase::eq_energie, Pb_Multiphase::eq_masse, Pb_Multiphase::eq_qdm, MorEqn::equation(), Pb_Multiphase::get_correlation(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Pb_Multiphase::has_correlation(), Navier_Stokes_std::inconnue(), Energie_Multiphase::inconnue(), Masse_Multiphase::inconnue(), Operateur::l_op_base(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Zone_VF::nb_faces_tot(), Masse_Multiphase::nombre_d_operateurs(), Masse_Multiphase::operateur(), Schema_Temps_base::pas_de_temps(), Champ_Proto::passe(), Zone_VF::porosite_elem(), Navier_Stokes_std::pression(), qpi(), TRUSTVect< _TYPE_ >::ref_array(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Equation_base::schema_temps(), Matrice_Morse::set_nb_columns(), Equation_base::sources(), sub_type, List_Source::valeur(), Deriv_Champ_Inc_base::valeur(), Deriv_Correlation_base::valeur(), Ref_Correlation::valeur(), valeur(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Fluide_base::viscosite_dynamique(), and Zone_VF::volumes().
associer_pb()
void Flux_interfacial_PolyMAC::associer_pb (const Probleme_base &) inline override virtual
Implements Source_base.
Definition at line 45 of file Flux_interfacial_PolyMAC.h.
{ };
associer_zones()
void Flux_interfacial_PolyMAC::associer_zones (const Zone_dis & , const Zone_Cl_dis &) inline override virtual
Implements Source_base.
Definition at line 44 of file Flux_interfacial_PolyMAC.h.
{ };
check_multiphase_compatibility()
void Flux_interfacial_PolyMAC::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 42 of file Flux_interfacial_PolyMAC.h.
{}; //of course
completer()
void Flux_interfacial_PolyMAC::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 82 of file Flux_interfacial_PolyMAC.cpp.
{
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, equation().zone_dis().valeur());
  int N = equation().inconnue().valeurs().line_size();
  if (!sub_type(Flux_interfacial_PolyMAC, equation().sources().dernier()->valeur())) Process::exit(que_suis_je() + " : Flux_interfacial_PolyMAC must be the last source term in the source term declaration list of the " + equation().que_suis_je() + " equation ! ");
  if (sub_type(Energie_Multiphase, equation()))
    {
      qpi_.resize(0, N, N), zone.zone().creer_tableau_elements(qpi_);
      dT_qpi_.resize(0, N, N, N), zone.zone().creer_tableau_elements(dT_qpi_);
      da_qpi_.resize(0, N, N, N), zone.zone().creer_tableau_elements(da_qpi_);
      dp_qpi_.resize(0, N, N), zone.zone().creer_tableau_elements(dp_qpi_);
    }
}
References Zone::creer_tableau_elements(), da_qpi_, dp_qpi_, dT_qpi_, MorEqn::equation(), Process::exit(), Equation_base::inconnue(), TRUSTVect< _TYPE_ >::line_size(), qpi_, Objet_U::que_suis_je(), ref_cast, TRUSTTab< _TYPE_ >::resize(), sub_type, valeur(), Champ_Inc::valeurs(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Flux_interfacial_PolyMAC::cree_instance () static
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
da_qpi()
DoubleTab & Flux_interfacial_PolyMAC::da_qpi () const
Definition at line 108 of file Flux_interfacial_PolyMAC.cpp.
{
  if (sub_type(Energie_Multiphase, equation())) return da_qpi_;
  return ref_cast(Flux_interfacial_PolyMAC, ref_cast(Pb_Multiphase, equation().probleme()).eq_energie.sources().dernier().valeur().valeur()).da_qpi();
}
References da_qpi_, MorEqn::equation(), ref_cast, and sub_type.
Referenced by ajouter_blocs().
dimensionner_blocs()
void Flux_interfacial_PolyMAC::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Definition at line 44 of file Flux_interfacial_PolyMAC.cpp.
{
  const Champ_Elem_PolyMAC& ch = ref_cast(Champ_Elem_PolyMAC, equation().inconnue().valeur());
  const Zone_PolyMAC& zone = ref_cast(Zone_PolyMAC, equation().zone_dis().valeur());
  const DoubleTab& inco = ch.valeurs();
  /* on doit pouvoir ajouter / soustraire les equations entre composantes */
  int i, j, e, n, N = inco.line_size();
  if (N == 1) return;
  std::set<int> idx;
  for (auto &&n_m : matrices)
    if (n_m.first.find("/") == std::string::npos) /* pour ignorer les inconnues venant d'autres problemes */
      {
        Matrice_Morse& mat = *n_m.second, mat2;
        const DoubleTab& dep = equation().probleme().get_champ(n_m.first).valeurs();
        int m, nc = dep.dimension_tot(0), M = dep.line_size();
        IntTrav sten(0, 2);
        sten.set_smart_resize(1);
        if (n_m.first == "temperature" || n_m.first == "pression" || n_m.first == "alpha" || n_m.first == "interfacial_area" ) /* temperature/pression: dependance locale */
          for (e = 0; e < zone.nb_elem(); e++)
            for (n = 0; n < N; n++)
              for (m = 0; m < M; m++) sten.append_line(N * e + n, M * e + m);
        else if (mat.nb_colonnes())
          for (e = 0; e < zone.nb_elem(); e++) /* autres variables: on peut melanger les composantes*/
            {
              for (idx.clear(), n = 0, i = N * e; n < N; n++, i++)
                for (j = mat.get_tab1()(i) - 1; j < mat.get_tab1()(i + 1) - 1; j++)
                  idx.insert(mat.get_tab2()(j) - 1); //idx : ensemble des colonnes dont depend au moins une ligne des N composantes en e
              for (n = 0, i = N * e; n < N; n++, i++)
                for (auto &&x : idx) sten.append_line(i, x); //ajout de cette depedance a toutes les lignes
            }
        else continue;
        Matrix_tools::allocate_morse_matrix(N * zone.nb_elem_tot(), M * nc, sten, mat2);
        mat.nb_colonnes() ? mat += mat2 : mat = mat2;
      }
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Equation_base::probleme(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), valeur(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dp_qpi()
DoubleTab & Flux_interfacial_PolyMAC::dp_qpi () const
Definition at line 114 of file Flux_interfacial_PolyMAC.cpp.
{
  if (sub_type(Energie_Multiphase, equation())) return dp_qpi_;
  return ref_cast(Flux_interfacial_PolyMAC, ref_cast(Pb_Multiphase, equation().probleme()).eq_energie.sources().dernier().valeur().valeur()).dp_qpi();
}
References dp_qpi_, MorEqn::equation(), ref_cast, and sub_type.
Referenced by ajouter_blocs().
dT_qpi()
DoubleTab & Flux_interfacial_PolyMAC::dT_qpi () const
Definition at line 102 of file Flux_interfacial_PolyMAC.cpp.
{
  if (sub_type(Energie_Multiphase, equation())) return dT_qpi_;
  return ref_cast(Flux_interfacial_PolyMAC, ref_cast(Pb_Multiphase, equation().probleme()).eq_energie.sources().dernier().valeur().valeur()).dT_qpi();
}
References dT_qpi_, MorEqn::equation(), ref_cast, and sub_type.
Referenced by ajouter_blocs().
duplique()
int Flux_interfacial_PolyMAC::duplique () const override virtual
Implements Objet_U.
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
get_info()
const Type_info * Flux_interfacial_PolyMAC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
has_interface_blocs()
int Flux_interfacial_PolyMAC::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 36 of file Flux_interfacial_PolyMAC.h.
  {
    return 1;
  }
info()
const Type_info * Flux_interfacial_PolyMAC::info () static
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
mettre_a_jour()
void Flux_interfacial_PolyMAC::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 120 of file Flux_interfacial_PolyMAC.cpp.
{
  qpi_ = 0, dT_qpi_ = 0, da_qpi_ = 0, dp_qpi_ = 0;
}
References da_qpi_, dp_qpi_, dT_qpi_, and qpi_.
printOn()
Sortie & Flux_interfacial_PolyMAC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 31 of file Flux_interfacial_PolyMAC.cpp.
{
  return os;
}
qpi()
DoubleTab & Flux_interfacial_PolyMAC::qpi () const
Definition at line 96 of file Flux_interfacial_PolyMAC.cpp.
{
  if (sub_type(Energie_Multiphase, equation())) return qpi_;
  return ref_cast(Flux_interfacial_PolyMAC, ref_cast(Pb_Multiphase, equation().probleme()).eq_energie.sources().dernier().valeur().valeur()).qpi();
}
References MorEqn::equation(), qpi_, ref_cast, and sub_type.
Referenced by ajouter_blocs().
readOn()
Entree & Flux_interfacial_PolyMAC::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 36 of file Flux_interfacial_PolyMAC.cpp.
{
  const Pb_Multiphase& pbm = ref_cast(Pb_Multiphase, equation().probleme());
  if (!pbm.has_correlation("flux_interfacial")) Process::exit(que_suis_je() + " : a flux_interfacial correlation must be defined in the global correlations { } block!");
  correlation_ = pbm.get_correlation("flux_interfacial");
  return is;
}
References correlation_, MorEqn::equation(), Process::exit(), Pb_Multiphase::get_correlation(), Pb_Multiphase::has_correlation(), Objet_U::que_suis_je(), and ref_cast.
self_cast() [1/2]
const Flux_interfacial_PolyMAC & Flux_interfacial_PolyMAC::self_cast (const Objet_U & r) static
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
self_cast() [2/2]
Flux_interfacial_PolyMAC & Flux_interfacial_PolyMAC::self_cast (Objet_U & r) static
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
taille_memoire()
unsigned Flux_interfacial_PolyMAC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 29 of file Flux_interfacial_PolyMAC.cpp.
Member Data Documentation
correlation_
Ref_Correlation Flux_interfacial_PolyMAC::correlation_ private
Definition at line 59 of file Flux_interfacial_PolyMAC.h.
Referenced by ajouter_blocs(), and readOn().
da_qpi_
DoubleTab Flux_interfacial_PolyMAC::da_qpi_ private
Definition at line 58 of file Flux_interfacial_PolyMAC.h.
Referenced by completer(), da_qpi(), and mettre_a_jour().
dp_qpi_
DoubleTab Flux_interfacial_PolyMAC::dp_qpi_ private
Definition at line 58 of file Flux_interfacial_PolyMAC.h.
Referenced by completer(), dp_qpi(), and mettre_a_jour().
dT_qpi_
DoubleTab Flux_interfacial_PolyMAC::dT_qpi_ private
Definition at line 58 of file Flux_interfacial_PolyMAC.h.
Referenced by completer(), dT_qpi(), and mettre_a_jour().
info_obj
const Type_info Flux_interfacial_PolyMAC::info_obj static
Definition at line 34 of file Flux_interfacial_PolyMAC.h.
qpi_
DoubleTab Flux_interfacial_PolyMAC::qpi_ mutable private
Definition at line 58 of file Flux_interfacial_PolyMAC.h.
Referenced by completer(), mettre_a_jour(), and qpi().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/PolyMAC/Flux_interfacial_PolyMAC.h
src/ThHyd/Multiphase/PolyMAC/Flux_interfacial_PolyMAC.cpp