TRUST: Champ_Fonc_P1_VDF Class Reference
Champ_Fonc_P1_VDF Class Reference
classe Champ_Fonc_P1_VDF
#include <Champ_Fonc_P1_VDF.h>
Public Member Functions
Champ_Fonc_P1_VDF ()
~Champ_Fonc_P1_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
const Zone_dis_base & zone_dis_base () const
virtual void mettre_a_jour (double)
Mise a jour en temps du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_P1_VDF & self_cast (Objet_U &)
static const Champ_Fonc_P1_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Detailed Description
classe Champ_Fonc_P1_VDF
Definition at line 37 of file Champ_Fonc_P1_VDF.h.
Constructor & Destructor Documentation
Champ_Fonc_P1_VDF::Champ_Fonc_P1_VDF ()
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
Champ_Fonc_P1_VDF::~Champ_Fonc_P1_VDF ()
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
Member Function Documentation
void Champ_Fonc_P1_VDF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [inline, virtual]
Implements Champ_Fonc_base.
Definition at line 53 of file Champ_Fonc_P1_VDF.h.
{
  la_zone_VDF = (const Zone_VDF&) la_zone_dis_base;
}
Objet_U * Champ_Fonc_P1_VDF::cree_instance () [static]
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
int Champ_Fonc_P1_VDF::duplique () const [virtual]
Implements Champ_Fonc_P1_base.
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
const Type_info * Champ_Fonc_P1_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
const Type_info * Champ_Fonc_P1_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
void Champ_Fonc_P1_VDF::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Implements Champ_Fonc_base.
Definition at line 40 of file Champ_Fonc_P1_VDF.cpp.
{
  Champ_Fonc_base::mettre_a_jour(t);
}
Sortie & Champ_Fonc_P1_VDF::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 29 of file Champ_Fonc_P1_VDF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Fonc_P1_VDF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 35 of file Champ_Fonc_P1_VDF.cpp.
{
  return s ;
}
Champ_Fonc_P1_VDF & Champ_Fonc_P1_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P1_base.
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
const Champ_Fonc_P1_VDF & Champ_Fonc_P1_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P1_base.
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
unsigned Champ_Fonc_P1_VDF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Champ_Fonc_P1_VDF.cpp.
const Zone_dis_base & Champ_Fonc_P1_VDF::zone_dis_base () const [virtual]
Implements Champ_Fonc_base.
Definition at line 45 of file Champ_Fonc_P1_VDF.cpp.
References la_zone_VDF, and Ref_Zone_VDF::valeur().
{
  return la_zone_VDF.valeur();
}
Member Data Documentation
const Type_info Champ_Fonc_P1_VDF::info_obj [static]
Reimplemented from Champ_Fonc_P1_base.
Definition at line 40 of file Champ_Fonc_P1_VDF.h.
Ref_Zone_VDF Champ_Fonc_P1_VDF::la_zone_VDF [protected]
Definition at line 50 of file Champ_Fonc_P1_VDF.h.
Referenced by zone_dis_base().
The documentation for this class was generated from the following files:
src/VDF/Champs/Champ_Fonc_P1_VDF.h
src/VDF/Champs/Champ_Fonc_P1_VDF.cpp