TRUST: Op_Dift_Stab_VEF_Face Class Reference
Op_Dift_Stab_VEF_Face Class Reference
class Op_Dift_Stab_VEF_Face
#include <Op_Dift_Stab_VEF_Face.h>
Public Member Functions
Op_Dift_Stab_VEF_Face ()
~Op_Dift_Stab_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void ajouter_cas_scalaire (const DoubleTab &inconnue, const DoubleTab &nu, const DoubleTab &nu_turb_m, DoubleTab &resu2) const
void ajouter_cas_multiscalaire (const DoubleTab &inconnue, const DoubleTab &nu, const DoubleTab &nu_turb_m, DoubleTab &resu2) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, const DoubleTab &nu, const DoubleTab &nu_turb_m, DoubleTab &resu2) const
void ajouter_contribution (const DoubleTab &transporte, Matrice_Morse &matrice) const
void ajouter_contribution_multi_scalaire (const DoubleTab &transporte, Matrice_Morse &matrice) const
void ajouter_contribution_cl (const DoubleTab &transporte, Matrice_Morse &matrice, const DoubleTab &nu, const DoubleTab &nu_turb, const DoubleVect &porosite_eventuelle) const
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Op_Dift_VEF_Face
Op_Dift_VEF_Face ()
~Op_Dift_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_diffusivite (const Champ_base &) override
const Champ_base & diffusivite () const override
double diffusivite (int) const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
void dimensionner (Matrice_Morse &) const override
on dimensionne notre matrice.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
on assemble la matrice.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void contribue_au_second_membre (DoubleTab &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_cl (const DoubleTab &, Matrice_Morse &, const DoubleTab &, const DoubleTab &, const DoubleVect &) const
void ajouter_contribution_multi_scalaire (const DoubleTab &, Matrice_Morse &) const
void ajouter_cas_scalaire (const DoubleVect &inconnue, DoubleVect &resu, DoubleTab &flux_bords, const DoubleVect &nu, const DoubleVect &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF) const
void ajouter_cas_vectoriel (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, const DoubleTab &nu, const DoubleTab &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
void ajouter_cas_multi_scalaire (const DoubleTab &inconnue, DoubleTab &resu, DoubleTab &flux_bords, const DoubleTab &nu, const DoubleVect &nu_turb, const Zone_Cl_VEF &zone_Cl_VEF, const Zone_VEF &zone_VEF, int nb_comp) const
Public Member Functions inherited from Op_Dift_VEF_base
Op_Dift_VEF_base ()
~Op_Dift_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_borne_locale (DoubleVect &, double, double) const override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_Stab_VEF_Face & self_cast (Objet_U &)
static const Op_Dift_Stab_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_Face
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_VEF_Face & self_cast (Objet_U &)
static const Op_Dift_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_base
static const Type_info * info ()
static Op_Dift_VEF_base & self_cast (Objet_U &)
static const Op_Dift_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
void calculer_coefficients (const DoubleTab &, DoubleTab &) const
void calculer_coefficients_vectoriel_diag (const DoubleTab &nu, const DoubleTab &nu2, DoubleTab &Aij) const
double aij_extradiag (const int elem, const int facei, const int facej, const int dim, const int dim2, const double nu_elem) const
void calculer_min (const DoubleTab &, int &, DoubleTab &) const
void calculer_max (const DoubleTab &, int &, DoubleTab &) const
double calculer_gradients (int, const DoubleTab &) const
void modifie_pour_Cl (const DoubleTab &, DoubleTab &) const
void ajouter_operateur_centre (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void ajouter_operateur_centre_vectoriel (const DoubleTab &Aij_diag, const DoubleTab &nu, const DoubleTab &inconnue, DoubleTab &resu2) const
void ajouter_diffusion (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void ajouter_diffusion_vectoriel (const DoubleTab &Aij, const DoubleTab &inconnueTab, DoubleTab &resuTab) const
void ajouter_antidiffusion (const DoubleTab &, const DoubleTab &, DoubleTab &) const
void ajouter_antidiffusion_vectoriel (const DoubleTab &Aij, const DoubleTab &inconnueTab, DoubleTab &resuTab) const
Protected Member Functions inherited from Op_Dift_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
int standard_
IntTab is_dirichlet_faces_
Ref_Champ_Inc divergence_U
int nu_lu_
int nut_lu_
int nu_transp_lu_
int nut_transp_lu_
int new_jacobian_
Protected Attributes inherited from Op_Dift_VEF_Face
Ref_Champ_base diffusivite_
DoubleTab grad_
grad DoubleTab grad_transp_;
Protected Attributes inherited from Op_Dift_VEF_base
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Dift_Stab_VEF_Face
Definition at line 29 of file Op_Dift_Stab_VEF_Face.h.
Constructor & Destructor Documentation
Op_Dift_Stab_VEF_Face()
Op_Dift_Stab_VEF_Face::Op_Dift_Stab_VEF_Face ()
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
~Op_Dift_Stab_VEF_Face()
Op_Dift_Stab_VEF_Face::~Op_Dift_Stab_VEF_Face ()
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
Member Function Documentation
aij_extradiag()
double Op_Dift_Stab_VEF_Face::aij_extradiag (const int elem, const int facei, const int facej, const int dim, const int dim2, const double nu_elem) const inline protected
Definition at line 81 of file Op_Dift_Stab_VEF_Face.h.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  double volume=0.;
  double signei=1.;
  double signej=1.;
  double aij=0.;
// Debut de l'algo
  assert(dim<equation().inconnue().valeurs().dimension(1));
  assert(dim2<equation().inconnue().valeurs().dimension(1));
  assert(dim<dim2);
  volume=1./volumes(elem);
  volume*=nu_elem;
  if (face_voisins(facei,0)!=elem) signei=-1.;
  if (face_voisins(facej,0)!=elem) signej=-1.;
  aij=face_normales(facei,dim2)*face_normales(facej,dim);
  aij*=signei*signej;
  aij*=volume;
  return aij;
}
References Objet_U::dimension, MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Op_Diff_VEF_base::la_zone_vef, Ref_Zone_VEF::valeur(), and Zone_VF::volumes().
Referenced by ajouter_operateur_centre_vectoriel().
ajouter()
DoubleTab & Op_Dift_Stab_VEF_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 163 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const DoubleTab& nu_turb=diffusivite_turbulente()->valeurs();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
  const Nature_du_champ nature_champ=equation().inconnue().valeur().nature_du_champ();
// const int nb_dim=resu.nb_dim();
// int nb_comp=1;
// if(nb_dim==2) nb_comp=resu.dimension(1);
  DoubleTab resu2(resu);
  resu2=0.;
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
  DoubleTab nu,nu_turb_m;
  DoubleTab tab_inconnue_;
  const int marq=phi_psi_diffuse(equation());
  remplir_nu(nu_);
  modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
  modif_par_porosite_si_flag(nu_turb,nu_turb_m,!marq,porosite_elem);
  const DoubleTab& inconnue=modif_par_porosite_si_flag(inconnue_org,tab_inconnue_,marq,porosite_face);
  assert_espace_virtuel_vect(nu);
  assert_espace_virtuel_vect(inconnue);
  assert_espace_virtuel_vect(nu_turb_m);
  Debog::verifier("Op_Dift_Stab_VEF_Face::ajouter nu",nu);
  Debog::verifier("Op_Dift_Stab_VEF_Face::ajouter nu_turb",nu_turb_m);
  Debog::verifier("Op_Dift_Stab_VEF_Face::ajouter inconnue_org",inconnue_org);
  Debog::verifier("Op_Dift_Stab_VEF_Face::ajouter inconnue",inconnue);
  if (nature_champ==scalaire)
    ajouter_cas_scalaire(inconnue,nu,nu_turb_m,resu2);
  if (nature_champ==vectoriel)
    ajouter_cas_vectoriel(inconnue,nu,nu_turb_m,resu2);
  if (nature_champ==multi_scalaire)
    ajouter_cas_multiscalaire(inconnue,nu,nu_turb_m,resu2);
  modifie_pour_Cl(inconnue,resu2);
  resu-=resu2;//-= car le laplacien est place en terme source dans l'equation
  modifier_flux(*this);
  return resu;
}
References ajouter_cas_multiscalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), assert_espace_virtuel_vect(), Op_Diff_Turbulent_base::diffusivite_turbulente(), MorEqn::equation(), Equation_base::inconnue(), Op_Diff_VEF_base::la_zone_vef, modif_par_porosite_si_flag(), modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), multi_scalaire, Field_base::nature_du_champ(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Op_Diff_VEF_base::remplir_nu(), scalaire, Deriv_Champ_Inc_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), vectoriel, and Debog::verifier().
ajouter_antidiffusion()
void Op_Dift_Stab_VEF_Face::ajouter_antidiffusion (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 570 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_comp=resuTab.line_size();
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  const DoubleTab& xv=zone_VEF.xv();
  DoubleTab rij(Objet_U::dimension);
  DoubleTab rji(rij);
  int elem=0,facei_loc=0,facei=0;
  int facej_loc=0,facej=0,dim=0,dim2=0;
  double inc_i=0.,inc_j=0.,delta_ij=0.;
  double delta_imax=0.,delta_imin=0.;
  double delta_jmax=0.,delta_jmin=0.;
  double sij=0.,muij=0.,muji=0.;
  bool ok_facei=false, ok_facej=false;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  DoubleTab Minima(nb_faces_tot);
  DoubleTab Maxima(nb_faces_tot);
  for (dim=0; dim<nb_comp; dim++)
    {
      calculer_min(inconnueTab,dim,Minima);
      calculer_max(inconnueTab,dim,Maxima);
      for (elem=0; elem<nb_elem_tot; elem++)
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          {
            facei=elem_faces(elem,facei_loc);
            ok_facei=is_dirichlet_faces_(facei);
            inc_i=inconnue[facei*nb_comp+dim];
            delta_imin=Minima(facei)-inc_i;
            delta_imax=Maxima(facei)-inc_i;
            assert(delta_imax>=0.);
            assert(delta_imin<=0.);
            for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
              {
                const double aij=Aij(elem,facei_loc,facej_loc);
                if (aij>0.)
                  {
                    facej=elem_faces(elem,facej_loc);
                    ok_facej=is_dirichlet_faces_(facej);
                    inc_j=inconnue[facej*nb_comp+dim];
                    for (dim2=0; dim2<Objet_U::dimension; dim2++)
                      rij(dim2)=xv(facej,dim2)-xv(facei,dim2);
                    rji=rij;
                    rji*=-1.;
                    delta_ij=inc_i-inc_j;
                    delta_jmin=Minima(facej)-inc_j;
                    delta_jmax=Maxima(facej)-inc_j;
                    assert(delta_jmax>=0.);
                    assert(delta_jmin<=0.);
                    muij=calculer_gradients(facei,rij);
                    muji=calculer_gradients(facej,rji);
                    sij=0.; //reste a 0 si que des faces de Dirichlet
                    if (delta_ij>0.)
                      {
                        muij*=delta_imax;
                        muji*=-delta_jmin;
                        if (!ok_facei && !ok_facej) //pas de face de Dirichlet
                          sij=my_minimum(muij,delta_ij,muji);
                        if (!ok_facei && ok_facej) //facej Dirichlet et pas facei
                          sij=my_minimum(muij,delta_ij);
                        if (ok_facei && !ok_facej) //facei Dirichlet et pas facej
                          sij=my_minimum(delta_ij,muji);
                      }
                    else if (delta_ij<0.)
                      {
                        muij*=delta_imin;
                        muji*=-delta_jmax;
                        if (!ok_facei && !ok_facej) //pas de face de Dirichlet
                          sij=my_maximum(muij,delta_ij,muji);
                        if (!ok_facei && ok_facej) //facej Dirichlet et pas facei
                          sij=my_maximum(muij,delta_ij);
                        if (ok_facei && !ok_facej) //facei Dirichlet et pas facej
                          sij=my_maximum(delta_ij,muji);
                      }
                    resu[facei*nb_comp+dim]-=aij*sij;
                    resu[facej*nb_comp+dim]+=aij*sij;
                  }
              }
          }
    }
}
References calculer_gradients(), calculer_max(), calculer_min(), Objet_U::dimension, Zone_VF::elem_faces(), is_dirichlet_faces_, Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), my_maximum(), my_minimum(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Zone_VF::nb_faces_tot(), Ref_Zone_VEF::valeur(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter_cas_multiscalaire(), and ajouter_cas_scalaire().
ajouter_antidiffusion_vectoriel()
void Op_Dift_Stab_VEF_Face::ajouter_antidiffusion_vectoriel (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 675 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_comp=resuTab.line_size();
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  const DoubleTab& xv=zone_VEF.xv();
  DoubleTab rij(Objet_U::dimension);
  DoubleTab rji(rij);
  int elem=0,facei_loc=0,facei=0;
  int facej_loc=0,facej=0,dim=0,dim2=0;
  double inc_i=0.,inc_j=0.,delta_ij=0.;
  double delta_imax=0.,delta_imin=0.;
  double delta_jmax=0.,delta_jmin=0.;
  double sij=0.,muij=0.,muji=0.;
  bool ok_facei=false,ok_facej=false;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  DoubleTab Minima(nb_faces_tot);
  DoubleTab Maxima(nb_faces_tot);
  for (dim=0; dim<nb_comp; dim++)
    {
      calculer_min(inconnueTab,dim,Minima);
      calculer_max(inconnueTab,dim,Maxima);
      for (elem=0; elem<nb_elem_tot; elem++)
        for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
          {
            facei=elem_faces(elem,facei_loc);
            ok_facei=is_dirichlet_faces_(facei);
            inc_i=inconnue[facei*nb_comp+dim];
            delta_imin=Minima(facei)-inc_i;
            delta_imax=Maxima(facei)-inc_i;
            assert(delta_imax>=0.);
            assert(delta_imin<=0.);
            for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
              {
                const double aij=Aij(elem,facei_loc,facej_loc,dim);
                if (aij>0.)
                  {
                    facej=elem_faces(elem,facej_loc);
                    ok_facej=is_dirichlet_faces_(facej);
                    inc_j=inconnue[facej*nb_comp+dim];
                    for (dim2=0; dim2<Objet_U::dimension; dim2++)
                      rij(dim2)=xv(facej,dim2)-xv(facei,dim2);
                    rji=rij;
                    rji*=-1.;
                    delta_ij=inc_i-inc_j;
                    delta_jmin=Minima(facej)-inc_j;
                    delta_jmax=Maxima(facej)-inc_j;
                    assert(delta_jmax>=0.);
                    assert(delta_jmin<=0.);
                    muij=calculer_gradients(facei,rij);
                    muji=calculer_gradients(facej,rji);
                    sij=0.; //reste a 0 si que des faces de Dirichlet
                    if (delta_ij>0.)
                      {
                        muij*=delta_imax;
                        muji*=-delta_jmin;
                        if (!ok_facei && !ok_facej) //pas de face de Dirichlet
                          sij=my_minimum(muij,delta_ij,muji);
                        if (!ok_facei && ok_facej) //facej Dirichlet et pas facei
                          sij=my_minimum(muij,delta_ij);
                        if (ok_facei && !ok_facej) //facei Dirichlet et pas facej
                          sij=my_minimum(delta_ij,muji);
                      }
                    else if (delta_ij<0.)
                      {
                        muij*=delta_imin;
                        muji*=-delta_jmax;
                        if (!ok_facei && !ok_facej) //pas de face de Dirichlet
                          sij=my_maximum(muij,delta_ij,muji);
                        if (!ok_facei && ok_facej) //facej Dirichlet et pas facei
                          sij=my_maximum(muij,delta_ij);
                        if (ok_facei && !ok_facej) //facei Dirichlet et pas facej
                          sij=my_maximum(delta_ij,muji);
                      }
                    resu[facei*nb_comp+dim]-=aij*sij;
                    resu[facej*nb_comp+dim]+=aij*sij;
                  }
              }
          }
    }
}
References calculer_gradients(), calculer_max(), calculer_min(), Objet_U::dimension, Zone_VF::elem_faces(), is_dirichlet_faces_, Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), my_maximum(), my_minimum(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Zone_VF::nb_faces_tot(), Ref_Zone_VEF::valeur(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by ajouter_cas_vectoriel().
ajouter_cas_multiscalaire()
void Op_Dift_Stab_VEF_Face::ajouter_cas_multiscalaire (const DoubleTab & inconnue, const DoubleTab & nu, const DoubleTab & nu_turb_m, DoubleTab & resu2) const
Definition at line 1227 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  DoubleTab Aij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
  DoubleTab nu_total(nu);
  nu_total+=nu_turb_m;
  calculer_coefficients(nu_total,Aij);
  ajouter_operateur_centre(Aij,inconnue,resu2);
  if (!standard_)
    {
      ajouter_diffusion(Aij,inconnue,resu2);
      ajouter_antidiffusion(Aij,inconnue,resu2);
    }
}
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_operateur_centre(), calculer_coefficients(), Op_Diff_VEF_base::la_zone_vef, Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), standard_, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_cas_scalaire()
void Op_Dift_Stab_VEF_Face::ajouter_cas_scalaire (const DoubleTab & inconnue, const DoubleTab & nu, const DoubleTab & nu_turb_m, DoubleTab & resu2) const
Definition at line 1208 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  DoubleTab Aij(nb_elem_tot,nb_faces_elem,nb_faces_elem);
  DoubleTab nu_total(nu);
  nu_total+=nu_turb_m;
  calculer_coefficients(nu_total,Aij);
  ajouter_operateur_centre(Aij,inconnue,resu2);
  if (!standard_)
    {
      ajouter_diffusion(Aij,inconnue,resu2);
      ajouter_antidiffusion(Aij,inconnue,resu2);
    }
}
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_operateur_centre(), calculer_coefficients(), Op_Diff_VEF_base::la_zone_vef, Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), standard_, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_cas_vectoriel()
void Op_Dift_Stab_VEF_Face::ajouter_cas_vectoriel (const DoubleTab & inconnue, const DoubleTab & nu, const DoubleTab & nu_turb_m, DoubleTab & resu2) const
Definition at line 1245 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_comp=resu2.dimension(1);
  DoubleTab Aij_diag(nb_elem_tot,nb_faces_elem,nb_faces_elem,nb_comp);
// DoubleTab Aij_extradiag(nb_elem_tot,nb_faces_elem,nb_faces_elem,nb_comp,nb_comp);
  DoubleTab nu_total(nu);
  if (nu_lu_==0) nu_total=0.;
  if (nut_lu_) nu_total+=nu_turb_m;
  DoubleTab nu_transp_total(nu);
  if (nu_transp_lu_==0) nu_transp_total=0.;
  if (nut_transp_lu_) nu_transp_total+=nu_turb_m;
  calculer_coefficients_vectoriel_diag(nu_total,nu_transp_total,Aij_diag);
// calculer_coefficients_vectoriel_extradiag(nu_transp_total,Aij_extradiag);
// ajouter_operateur_centre_vectoriel(Aij_diag,Aij_extradiag,inconnue,resu2);
  ajouter_operateur_centre_vectoriel(Aij_diag,nu_transp_total,inconnue,resu2);
  if (!standard_)
    {
      ajouter_diffusion_vectoriel(Aij_diag,inconnue,resu2);
      ajouter_antidiffusion_vectoriel(Aij_diag,inconnue,resu2);
    }
}
References ajouter_antidiffusion_vectoriel(), ajouter_diffusion_vectoriel(), ajouter_operateur_centre_vectoriel(), calculer_coefficients_vectoriel_diag(), TRUSTTab< _TYPE_ >::dimension(), Op_Diff_VEF_base::la_zone_vef, Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), nu_lu_, nu_transp_lu_, nut_lu_, nut_transp_lu_, standard_, Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
ajouter_contribution()
void Op_Dift_Stab_VEF_Face::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
< C'est une face virtuelle
< On traite les faces reelles
< on ajoute grad_U transpose
< On traite les faces reelles
Definition at line 1472 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (!new_jacobian_)
    Op_Dift_VEF_Face::ajouter_contribution(transporte,matrice);
  else
    {
      modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
      remplir_nu(nu_);
      const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const IntTab& elem_faces = zone_VEF.elem_faces();
      const IntTab& face_voisins = zone_VEF.face_voisins();
      int nb_faces = zone_VEF.nb_faces();
      const int nb_comp=transporte.line_size();
      int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
      const DoubleTab& nu_turb_=diffusivite_turbulente()->valeurs();
      DoubleVect n(dimension);
      DoubleTab nu,nu_turb;
      int marq=phi_psi_diffuse(equation());
      const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
      modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
      modif_par_porosite_si_flag(nu_turb_,nu_turb,!marq,porosite_elem);
      DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
      if (!marq)
        porosite_eventuelle=1;
// On traite les conditions limites separemment car sinon
// methode trop longue et mauvais inlining de certaines methodes
// sur certaines machines (Matrice_Morse::operator() et viscA)
      ajouter_contribution_cl(transporte, matrice, nu, nu_turb, porosite_eventuelle);
// On traite les faces internes
      int numpremiereface = zone_VEF.premiere_face_int();
      for (int num_face=numpremiereface; num_face<nb_faces; num_face++)
        {
          for (int l=0; l<2; l++)
            {
              int elem = face_voisins(num_face,l);
              double d_nu = nu(elem) + nu_turb(elem);
              for (int i=0; i<nb_faces_elem; i++)
                {
                  int j = elem_faces(elem,i);
                  if ( j > num_face )
                    {
                      int contrib=1;
                      if(j>=nb_faces) //!< C'est une face virtuelle
{
                          int el1 = face_voisins(j,0);
                          int el2 = face_voisins(j,1);
                          if((el1==-1)||(el2==-1))
                            contrib=0;
                        }
                      if (contrib)
{
                          double valA = viscA(num_face,j,elem,d_nu);
                          if (valA<0.) valA=0.;
                          double contrib_num_face = valA*porosite_eventuelle(num_face);
                          double contrib_j = valA*porosite_eventuelle(j);
                          for (int nc=0; nc<nb_comp; nc++)
{
                              int n0=num_face*nb_comp+nc;
                              int j0=j*nb_comp+nc;
                              matrice(n0,n0)+=contrib_num_face;
                              matrice(n0,j0)-=contrib_j;
                              if(j<nb_faces) //!< On traite les faces reelles
{
                                  matrice(j0,n0)-=contrib_num_face;
                                  matrice(j0,j0)+=contrib_j;
                                }
                              if (nb_comp>1) //!< on ajoute grad_U transpose
{
                                  for (int nc2=0; nc2<nb_comp; nc2++)
{
                                      int n1=num_face*nb_comp+nc2;
                                      int j1=j*nb_comp+nc2;
                                      double coeff_s=0.;//tmp*face_normale(num_face,nc2)*face_normale(j,nc);
                                      matrice(n0,n1)+=coeff_s*porosite_eventuelle(num_face);
                                      matrice(n0,j1)-=coeff_s*porosite_eventuelle(j);
                                      if(j<nb_faces) //!< On traite les faces reelles
{
                                          double coeff_s2=0.;//tmp*face_normale(num_face,nc)*face_normale(j,nc2);
                                          matrice(j0,n1)-=coeff_s2*porosite_eventuelle(num_face);
                                          matrice(j0,j1)+=coeff_s2*porosite_eventuelle(j);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
      modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
    }
}
References Op_Dift_VEF_Face::ajouter_contribution(), ajouter_contribution_cl(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_voisins(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), new_jacobian_, Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Op_Diff_VEF_base::viscA(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_contribution_cl()
void Op_Dift_Stab_VEF_Face::ajouter_contribution_cl (const DoubleTab & transporte, Matrice_Morse & matrice, const DoubleTab & nu, const DoubleTab & nu_turb, const DoubleVect & porosite_eventuelle) const
< C'est une face virtuelle
< On traite les faces reelles
< on ajoute grad_U transpose
< On traite les faces reelles
< on ajoute grad_U transpose
Definition at line 1277 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (!new_jacobian_)
    Op_Dift_VEF_Face::ajouter_contribution_cl(transporte,matrice,nu,nu_turb,porosite_eventuelle);
  else
    {
// On traite les faces bord
      const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
      const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const IntTab& face_voisins = zone_VEF.face_voisins();
      const IntTab& elem_faces = zone_VEF.elem_faces();
      const DoubleVect& volumes = zone_VEF.volumes();
      const DoubleTab& face_normale = zone_VEF.face_normales();
      int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
      int nb_faces = zone_VEF.nb_faces();
      const int nb_comp = transporte.line_size();
      int nb_bords=zone_VEF.nb_front_Cl();
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
          int nb_faces_bord_reel = le_bord.nb_faces();
          int j;
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
// on ne parcourt que la moitie des faces volontairement...
// GF il ne faut pas s'occuper des faces virtuelles
              num2=nb_faces_bord_reel/2;
              for (int ind_face=num1; ind_face<num2; ind_face++)
                {
                  int fac_asso = la_cl_perio.face_associee(ind_face);
                  fac_asso = le_bord.num_face(fac_asso);
                  int num_face = le_bord.num_face(ind_face);
                  for (int l=0; l<2; l++)
                    {
                      int elem = face_voisins(num_face,l);
                      double d_nu = nu(elem)+nu_turb(elem);
                      for (int i=0; i<nb_faces_elem; i++)
{
                          if ( (j= elem_faces(elem,i)) > num_face )
{
                              double valA = viscA(num_face,j,elem,d_nu);
                              if (valA<0.) valA=0.;
                              int orientation = 1;
                              if ( (elem == face_voisins(j,l)) || (face_voisins(num_face,(l+1)%2) == face_voisins(j,(l+1)%2)))
                                orientation = -1;
                              int fac_loc=0;
                              int ok=1;
                              while ((fac_loc<nb_faces_elem) && (elem_faces(elem,fac_loc)!=num_face)) fac_loc++;
                              if (fac_loc==nb_faces_elem)
                                ok=0;
                              int contrib=1;
                              if(j>=nb_faces) //!< C'est une face virtuelle
{
                                  int el1 = face_voisins(j,0);
                                  int el2 = face_voisins(j,1);
                                  if((el1==-1)||(el2==-1))
                                    contrib=0;
                                }
                              if (contrib)
{
                                  for (int nc=0; nc<nb_comp; nc++)
{
                                      int n0=num_face*nb_comp+nc;
                                      int n0perio=fac_asso*nb_comp+nc;
                                      int j0=j*nb_comp+nc;
                                      matrice(n0,n0)+=valA*porosite_eventuelle(num_face);
                                      matrice(n0,j0)-=valA*porosite_eventuelle(j);
                                      if(j<nb_faces) //!< On traite les faces reelles
{
// if (l==0)
                                          if (ok==1)
                                            matrice(j0,n0)-=valA*porosite_eventuelle(num_face);
                                          else
                                            matrice(j0,n0perio)-=valA*porosite_eventuelle(num_face);
                                          matrice(j0,j0)+=valA*porosite_eventuelle(j);
                                        }
                                      if (nb_comp > 1) //!< on ajoute grad_U transpose
                                        for (int nc2=0; nc2<nb_comp; nc2++)
{
                                            int n1=num_face*nb_comp+nc2;
                                            int j1=j*nb_comp+nc2;
                                            double coeff_s=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc2)*face_normale(j,nc);
                                            matrice(n0,n1)+=coeff_s*porosite_eventuelle(num_face);
                                            matrice(n0,j1)-= coeff_s*porosite_eventuelle(j);
                                            if(j<nb_faces) //!< On traite les faces reelles
{
                                                double coeff_s2=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc)*face_normale(j,nc2);
                                                if (ok==1)
                                                  matrice(j0,n1)-=coeff_s2*porosite_eventuelle(num_face);
                                                else
                                                  matrice(j0,fac_asso*nb_comp+nc2)-=coeff_s2*porosite_eventuelle(num_face);
                                                matrice(j0,j1)+=coeff_s2*porosite_eventuelle(j);
                                              }
                                          }
                                    }
                                }
                            }
                        }
                    }
                }
            }
          else
            {
// pas perio
// correction dans le cas dirichlet sur paroi temperature
              if(sub_type(Scalaire_impose_paroi,la_cl.valeur()))
                {
                  const Equation_base& my_eqn = zone_Cl_VEF.equation();
                  const RefObjU& modele_turbulence = my_eqn.get_modele(TURBULENCE);
                  if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
                    {
                      const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
                      const Turbulence_paroi_scal& loiparth = mod_turb_scal.loi_paroi();
                      if (loiparth->use_equivalent_distance())
{
// Comme on ne doit pas utiliser cet operateur sans la loi Pironneau,
// on ne doit jamais passer ici
                          Cerr<<"Error in  Op_Dift_Stab_VEF_Face::ajouter_contribution_cl()"<<finl;
                          Cerr<<"Case not coded yet"<<finl;
                          Process::exit();
                        }
                    }
                } //!< CL Temperature imposee
              else if  (sub_type(Echange_externe_impose,la_cl.valeur()))
                {
                  const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose, la_cl.valeur());
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  int ndeb = le_bord.num_premiere_face();
                  int nfin = ndeb + le_bord.nb_faces();
                  for (int face=ndeb; face<nfin; face++)
                    {
                      matrice(face,face) += la_cl_paroi.h_imp(face-ndeb)*zone_VEF.face_surfaces(face);
                    }
                }
              for (int ind_face=num1; ind_face<num2; ind_face++)
                {
                  int num_face = le_bord.num_face(ind_face);
                  int elem=face_voisins(num_face,0);
                  double d_nu = nu(elem)+nu_turb(elem);
// Boucle sur les faces :
                  for (int i=0; i<nb_faces_elem; i++)
                    if (( (j= elem_faces(elem,i)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                      {
                        double valA = viscA(num_face,j,elem,d_nu);
                        if (valA<0.) valA=0.;
                        int orientation = 1;
                        if ( (elem == face_voisins(j,0)) || (face_voisins(num_face,(0+1)%2) == face_voisins(j,(0+1)%2)))
                          orientation = -1;
// retire terme croisee pour l'intant
// orientation=0;
                        for (int nc=0; nc<nb_comp; nc++)
{
                            int n0=num_face*nb_comp+nc;
                            int j0=j*nb_comp+nc;
                            if (ind_face<nb_faces_bord_reel)
{
                                matrice(n0,n0)+=valA*porosite_eventuelle(num_face);
                                matrice(n0,j0)-=valA*porosite_eventuelle(j);
                              }
                            if(j<nb_faces)
{
                                matrice(j0,n0)-=valA*porosite_eventuelle(num_face);
                                matrice(j0,j0)+=valA*porosite_eventuelle(j);
                              }
                            if (nb_comp>1) //!< on ajoute grad_U transpose
                              for (int nc2=0; nc2<nb_comp; nc2++)
{
                                  int n1=num_face*nb_comp+nc2;
                                  int j1=j*nb_comp+nc2;
                                  if (ind_face<nb_faces_bord_reel)
{
                                      double coeff_s=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc2)*face_normale(j,nc);
                                      matrice(n0,n1)+=coeff_s*porosite_eventuelle(num_face);
                                      matrice(n0,j1)-= coeff_s*porosite_eventuelle(j);
                                    }
                                  if (j<nb_faces)
{
                                      double coeff_s=orientation*nu_turb(elem)/volumes(elem)*face_normale(num_face,nc)*face_normale(j,nc2);
                                      matrice(j0,n1)-=coeff_s*porosite_eventuelle(num_face);
                                      matrice(j0,j1)+=coeff_s*porosite_eventuelle(j);
                                    }
                                }
                          }
                      }
                }
            }
        }
    }
}
References Op_Dift_VEF_Face::ajouter_contribution_cl(), Cerr, Zone_VF::elem_faces(), MorEqn::equation(), Process::exit(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Equation_base::get_modele(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Modele_turbulence_scal_base::loi_paroi(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), new_jacobian_, Front_VF::num_face(), Front_VF::num_premiere_face(), ref_cast, sub_type, TURBULENCE, Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_contribution().
ajouter_contribution_multi_scalaire()
void Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
< C'est une face virtuelle
< On traite les faces reelles
< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
< C'est une face virtuelle
< On traite les faces reelles
Definition at line 1576 of file Op_Dift_Stab_VEF_Face.cpp.
{
  if (!new_jacobian_)
    Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(transporte,matrice);
  else
    {
      modifier_matrice_pour_periodique_avant_contribuer(matrice,equation());
// On remplit le tableau nu car l'assemblage d'une
// matrice avec ajouter_contribution peut se faire
// avant le premier pas de temps
      remplir_nu(nu_);
      const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
      const Zone_VEF& zone_VEF = la_zone_vef.valeur();
      const IntTab& elemfaces = zone_VEF.elem_faces();
      const IntTab& face_voisins = zone_VEF.face_voisins();
      int nb_faces = zone_VEF.nb_faces();
      const int nb_comp =transporte.line_size();
      int i,j,num_face0,elem1;
      int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
      double valA, d_nu;
      const DoubleTab& nu_turb_=diffusivite_turbulente()->valeurs();
      DoubleVect n(dimension);
      DoubleTab nu,nu_turb;
      int marq=phi_psi_diffuse(equation());
      const DoubleVect& porosite_elem = zone_VEF.porosite_elem();
// soit on a div(phi nu grad inco)
// soit on a div(nu grad phi inco)
// cela depend si on diffuse phi_psi ou psi
      modif_par_porosite_si_flag(nu_,nu,!marq,porosite_elem);
      modif_par_porosite_si_flag(nu_turb_,nu_turb,!marq,porosite_elem);
      DoubleVect porosite_eventuelle(zone_VEF.porosite_face());
      if (!marq)
        porosite_eventuelle=1;
// On traite les faces bord
      int nb_bords=zone_VEF.nb_front_Cl();
      for (int n_bord=0; n_bord<nb_bords; n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
// const IntTab& elemfaces = zone_VEF.elem_faces();
          int num1 = 0;
          int num2 = le_bord.nb_faces_tot();
          int nb_faces_bord_reel = le_bord.nb_faces();
          if (sub_type(Periodique,la_cl.valeur()))
            {
              const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
              int fac_asso;
// on ne parcourt que la moitie des faces volontairement...
              num2/=2;
              for (int ind_face=num1; ind_face<num2; ind_face++)
                {
                  fac_asso = la_cl_perio.face_associee(ind_face);
                  fac_asso= le_bord.num_face(fac_asso);
                  num_face0 = le_bord.num_face(ind_face);
// ICI
                  for (int l=0; l<2; l++)
                    {
                      int elem = face_voisins(num_face0,l);
// On elimine les elements avec CL de paroi (rang>=1)
// int rang = rang_elem_non_std(elem);
// if (rang<0)
                      {
                        for (i=0; i<nb_faces_elem; i++)
{
                            if ( (j= elemfaces(elem,i)) > num_face0 )
{
                                int fac_loc=0;
                                int ok=1;
                                while ((fac_loc<nb_faces_elem) && (elemfaces(elem,fac_loc)!=num_face0)) fac_loc++;
                                if (fac_loc==nb_faces_elem)
                                  ok=0;
                                for (int nc=0; nc<nb_comp; nc++)
{
                                    d_nu = nu(elem,nc)+nu_turb(elem);
                                    valA = viscA(num_face0,j,elem,d_nu);
                                    if (valA<0.) valA=0.;
                                    int n0=num_face0*nb_comp+nc;
                                    int n0perio=fac_asso*nb_comp+nc;
                                    int j0=j*nb_comp+nc;
                                    int contrib=1;
                                    if(j>=nb_faces) //!< C'est une face virtuelle
{
                                        int el1 = face_voisins(j,0);
                                        int el2 = face_voisins(j,1);
                                        if((el1==-1)||(el2==-1))
                                          contrib=0;
                                      }
                                    if(contrib)
{
                                        matrice(n0,n0)+=valA*porosite_eventuelle(num_face0);
                                        matrice(n0,j0)-=valA*porosite_eventuelle(j);
                                        if(j<nb_faces) //!< On traite les faces reelles
{
// if (l==0)
                                            if (ok==1)
                                              matrice(j0,n0)-=valA*porosite_eventuelle(num_face0);
                                            else
                                              matrice(j0,n0perio)-=valA*porosite_eventuelle(num_face0);
                                            matrice(j0,j0)+=valA*porosite_eventuelle(j);
                                          }
                                      }
                                  }
                              }
                          }
                      }
                    }
                }
            }
          else
            {
// pas perio
// correction dans le cas dirichlet sur paroi temperature
              if(sub_type(Scalaire_impose_paroi,la_cl.valeur()))
                {
                  const Equation_base& my_eqn = zone_Cl_VEF.equation();
                  const RefObjU& modele_turbulence = my_eqn.get_modele(TURBULENCE);
                  if (sub_type(Modele_turbulence_scal_base,modele_turbulence.valeur()))
                    {
                      const Modele_turbulence_scal_base& mod_turb_scal = ref_cast(Modele_turbulence_scal_base,modele_turbulence.valeur());
                      const Turbulence_paroi_scal& loiparth = mod_turb_scal.loi_paroi();
                      if (loiparth->use_equivalent_distance())
{
                          const DoubleTab& face_normale = zone_VEF.face_normales();
                          const DoubleVect& vol = zone_VEF.volumes();
                          const DoubleVect& d_equiv=loiparth->equivalent_distance(n_bord);
                          int nb_dim_pb=Objet_U::dimension;
                          DoubleVect le_mauvais_gradient(nb_dim_pb);
                          for (int ind_face=num1; ind_face<num2; ind_face++)
{
                              for (int nc=0; nc<nb_comp; nc++)
{
                                  int num_face = le_bord.num_face(ind_face);
// Tf est la temperature fluide moyenne dans le premier element
// sans tenir compte de la temperature de paroi.
                                  double Tf=0.;
                                  double bon_gradient=0.; //!< c'est la norme du gradient de temperature normal a la paroi calculee a l'aide de la loi de paroi.
//
                                  elem1 = face_voisins(num_face,0);
                                  if(elem1==-1) elem1 = face_voisins(num_face,1);
// inconnue(num_face) est la temperature de paroi : Tw.
// On se fiche du signe de bon gradient car c'est la norme du gradient
// de temperature dans l'element.
// Ensuite ce sera multiplie par le vecteur normal a la face de paroi
// qui lui a les bons signes.
// bon_gradient=(Tf-inconnue(num_face))/d_equiv(num_face);
                                  bon_gradient=1./d_equiv(ind_face)*(-zone_VEF.oriente_normale(num_face,elem1));
                                  double surface_face=zone_VEF.face_surfaces(num_face);
                                  double nutotal=nu(elem1,nc)+nu_turb(elem1);
                                  for (i=0; i<nb_faces_elem; i++)
{
                                      j= elemfaces(elem1,i);
                                      for (int ii=0; ii<nb_faces_elem; ii++)
{
                                          le_mauvais_gradient=0;
                                          int jj=elemfaces(elem1,ii);
                                          double surface_pond=0;
                                          for (int kk=0; kk<nb_dim_pb; kk++)
                                            surface_pond -= (face_normale(jj,kk)*zone_VEF.oriente_normale(jj,elem1)*face_normale(num_face,kk)*
                                                             zone_VEF.oriente_normale(num_face,elem1))/(surface_face*surface_face);
                                          Tf=surface_pond;
// Tf=1./(nb_faces_elem-1); // Temperature moyenne.
                                          for(int kk=0; kk<nb_dim_pb; kk++)
                                            le_mauvais_gradient(kk)+=face_normale(jj,kk)*zone_VEF.oriente_normale(jj,elem1);
                                          le_mauvais_gradient/=vol(elem1);
                                          double mauvais_gradient=0;
// double surface_face=zone_VEF.face_surfaces(num_face);
                                          for(int kk=0; kk<nb_dim_pb; kk++)
                                            mauvais_gradient+=le_mauvais_gradient(kk)*face_normale(num_face,kk)/surface_face;
                                          double resu1=0,resu2=0;
                                          for(int kk=0; kk<nb_dim_pb; kk++)
{
// resu1 += nutotal*le_mauvais_gradient(kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1));
                                              resu1 += nutotal*mauvais_gradient*face_normale(num_face,kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                              resu2 += nutotal*bon_gradient    *face_normale(num_face,kk)*face_normale(j,kk)*(-zone_VEF.oriente_normale(j,elem1))/surface_face;
                                            }
// bon gradient_reel =bongradient*(Tf-T_face) d'ou les derivees...
// mauvais gradient_reel=mauvai_gradient_j*Tj
                                          if (jj==num_face)
                                            resu2*=-1;
                                          else
                                            resu2*=Tf;
                                          int j0=j*nb_comp+nc;
                                          int jj0=jj*nb_comp+nc;
                                          matrice(j0,jj0)+=(resu1-resu2)*porosite_eventuelle(jj0);
                                        }
                                    }
                                }
                            }
                        }//!< loi de paroi
                    }//Equation Convection_Diffusion_Turbulente
                } //!< CL Temperature imposee
              for (int ind_face=num1; ind_face<num2; ind_face++)
                {
                  int num_face = le_bord.num_face(ind_face);
                  int elem=face_voisins(num_face,0);
// Boucle sur les faces :
                  for (int ii=0; ii<nb_faces_elem; ii++)
                    if (( (j= elemfaces(elem,ii)) > num_face ) || (ind_face>=nb_faces_bord_reel))
                      {
// int orientation = zone_VEF.oriente_normale(j,elem);
// retire terme croisee pour l'intant
// orientation=0;
                        for (int nc=0; nc<nb_comp; nc++)
{
                            d_nu = nu(elem,nc)+nu_turb(elem);
                            valA = viscA(num_face,j,elem,d_nu);
                            if (valA<0.) valA=0.;
                            int n0=num_face*nb_comp+nc;
                            int j0=j*nb_comp+nc;
                            if (ind_face<nb_faces_bord_reel)
{
                                matrice(n0,n0)+=valA*porosite_eventuelle(num_face);
                                matrice(n0,j0)-=valA*porosite_eventuelle(j);
                              }
                            if(j<nb_faces)
{
                                matrice(j0,n0)-=valA*porosite_eventuelle(num_face);
                                matrice(j0,j0)+=valA*porosite_eventuelle(j);
                              }
                          }
                      }
                }
            }
        }
// On traite les faces internes
      int numpremiereface=zone_VEF.premiere_face_int();
      for (num_face0=numpremiereface; num_face0<nb_faces; num_face0++)
        {
// ICI
          for (int l=0; l<2; l++)
            {
              int elem = face_voisins(num_face0,l);
// On elimine les elements avec CL de paroi (rang>=1)
// int rang = rang_elem_non_std(elem);
// if (rang<0)
              {
                for (i=0; i<nb_faces_elem; i++)
                  {
                    if ( (j= elemfaces(elem,i)) > num_face0 )
                      {
// int orientation = 1;
// if ((elem == face_voisins(j,l)) || (face_voisins(num_face,(l+1)%2) == face_voisins(j,(l+1)%2)))
// orientation = -1;
                        for (int nc=0; nc<nb_comp; nc++)
{
                            d_nu = nu(elem,nc)+nu_turb(elem);
                            valA = viscA(num_face0,j,elem,d_nu);
                            if (valA<0.) valA=0.;
                            int n0=num_face0*nb_comp+nc;
                            int j0=j*nb_comp+nc;
                            int contrib=1;
                            if(j>=nb_faces) //!< C'est une face virtuelle
{
                                int el1 = face_voisins(j,0);
                                int el2 = face_voisins(j,1);
                                if((el1==-1)||(el2==-1))
                                  contrib=0;
                              }
                            if(contrib)
{
                                matrice(n0,n0)+=valA*porosite_eventuelle(num_face0);
                                matrice(n0,j0)-=valA*porosite_eventuelle(j);
                                if(j<nb_faces) //!< On traite les faces reelles
{
                                    matrice(j0,n0)-=valA*porosite_eventuelle(num_face0);
                                    matrice(j0,j0)+=valA*porosite_eventuelle(j);
                                  }
                              }
                          }
                      }
                  }
              }
            }
        }
      modifier_matrice_pour_periodique_apres_contribuer(matrice,equation());
    }
}
References Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Zone_VEF::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Equation_base::get_modele(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Modele_turbulence_scal_base::loi_paroi(), modif_par_porosite_si_flag(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_dis_base::nb_front_Cl(), new_jacobian_, Op_Diff_VEF_base::nu_, Front_VF::num_face(), Zone_VEF::oriente_normale(), Op_Diff_VEF_base::phi_psi_diffuse(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Op_Diff_VEF_base::remplir_nu(), sub_type, TURBULENCE, Deriv_Cond_lim_base::valeur(), Ref_Objet_U::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_Fonc::valeurs(), Op_Diff_VEF_base::viscA(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by contribuer_a_avec().
ajouter_diffusion()
void Op_Dift_Stab_VEF_Face::ajouter_diffusion (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 484 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem = zone_VEF.zone().nb_faces_elem();
  const int nb_comp = resuTab.line_size();
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  int elem = 0, facei_loc = 0, facei = 0;
  int facej_loc=0,facej=0, dim=0;
  double inc_i=0., inc_j=0., delta_ij=0. , dij=0.;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            const double aij=Aij(elem,facei_loc,facej_loc);
            if (aij>0.)
              {
                dij=-aij;
                for (dim=0; dim<nb_comp; dim++)
                  {
                    inc_i=inconnue[facei*nb_comp+dim];
                    inc_j=inconnue[facej*nb_comp+dim];
                    delta_ij=dij*(inc_j-inc_i);
                    resu[facei*nb_comp+dim]+=delta_ij;
                    resu[facej*nb_comp+dim]-=delta_ij;
                  }
              }
          }
      }
}
References Zone_VF::elem_faces(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_cas_multiscalaire(), and ajouter_cas_scalaire().
ajouter_diffusion_vectoriel()
void Op_Dift_Stab_VEF_Face::ajouter_diffusion_vectoriel (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 527 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_comp=resuTab.line_size();
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  int elem=0,facei_loc=0,facei=0;
  int facej_loc=0,facej=0,dim=0;
  double inc_i=0.,inc_j=0.,delta_ij=0.,dij=0.;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            for (dim=0; dim<nb_comp; dim++)
              {
                const double aij=Aij(elem,facei_loc,facej_loc,dim);
                if (aij>0.)
                  {
                    dij=-aij;
                    inc_i=inconnue[facei*nb_comp+dim];
                    inc_j=inconnue[facej*nb_comp+dim];
                    delta_ij=dij*(inc_j-inc_i);
                    resu[facei*nb_comp+dim]+=delta_ij;
                    resu[facej*nb_comp+dim]-=delta_ij;
                  }
              }
          }
      }
}
References Zone_VF::elem_faces(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_cas_vectoriel().
ajouter_operateur_centre()
void Op_Dift_Stab_VEF_Face::ajouter_operateur_centre (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
Definition at line 309 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_comp=resuTab.line_size();
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resuTab;
  int elem=0, facei_loc=0,facei=0;
  int facej_loc=0,facej=0, dim=0;
  double inc_i=0., inc_j=0., delta_ij=0.;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            const double aij=Aij(elem,facei_loc,facej_loc);
            for (dim=0; dim<nb_comp; dim++)
              {
                inc_i=inconnue[facei*nb_comp+dim];
                inc_j=inconnue[facej*nb_comp+dim];
                delta_ij=aij*(inc_j-inc_i);
                resu[facei*nb_comp+dim]+=delta_ij;
                resu[facej*nb_comp+dim]-=delta_ij;
              }
          }
      }
}
References Zone_VF::elem_faces(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_cas_multiscalaire(), and ajouter_cas_scalaire().
ajouter_operateur_centre_vectoriel()
void Op_Dift_Stab_VEF_Face::ajouter_operateur_centre_vectoriel (const DoubleTab & Aij_diag, const DoubleTab & nu, const DoubleTab & inconnue, DoubleTab & resu2) const protected
Definition at line 417 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  int nb_comp=resu2.line_size();
  const DoubleVect& inconnue = inconnueTab;
  DoubleVect& resu = resu2;
  int elem=0,facei_loc=0,facei=0;
  int facej_loc=0,facej=0,dim=0, dim2=0;
  double inc_i=0.,inc_j=0., delta_ij=0., nu_elem=0.;
  const IntTab& elem_faces=zone_VEF.elem_faces();
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      nu_elem=nu(elem);
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
// Ajout de la partie diagonale : on tient compte de la symetrie
// de la matrice Aij_diag
          for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
            {
              facej=elem_faces(elem,facej_loc);
              for (dim=0; dim<nb_comp; dim++)
                {
                  const double aij=Aij_diag(elem,facei_loc,facej_loc,dim);
                  inc_i=inconnue[facei*nb_comp+dim];
                  inc_j=inconnue[facej*nb_comp+dim];
                  delta_ij=aij*(inc_j-inc_i);
                  resu[facei*nb_comp+dim]+=delta_ij;
                  resu[facej*nb_comp+dim]-=delta_ij;
                }
            }
// Ajout de la partie extra-diagonale : on tient compte de la symetrie
// de la partie extradiagonale de la matrice du laplacien
          for (facej_loc=0; facej_loc<nb_faces_elem; facej_loc++)
            if (facej_loc!=facei_loc)
              {
                facej=elem_faces(elem,facej_loc);
                for (dim=0; dim<nb_comp; dim++)
                  for (dim2=dim+1; dim2<nb_comp; dim2++)
                    {
                      const double aij=aij_extradiag(elem,facei,facej,dim,dim2,nu_elem);
                      inc_i=inconnue[facei*nb_comp+dim2];
                      inc_j=inconnue[facej*nb_comp+dim2];
                      delta_ij=aij*(inc_j-inc_i);
                      resu[facei*nb_comp+dim]+=delta_ij;
                      inc_i=inconnue[facei*nb_comp+dim];
                      inc_j=inconnue[facej*nb_comp+dim];
                      delta_ij=aij*(inc_j-inc_i);
                      resu[facej*nb_comp+dim2]-=delta_ij;
                    }
              }
        }
    }
}
References aij_extradiag(), Zone_VF::elem_faces(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_cas_vectoriel().
calculer_coefficients()
void Op_Dift_Stab_VEF_Face::calculer_coefficients (const DoubleTab & nu, DoubleTab & Aij) const protected
Definition at line 779 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  double volume=0.,signei=0.,signej=0.,psc=0.,nu_elem=0.;
  int elem=0,facei_loc=0,facei=0;
  int facej_loc=0,facej=0,dim=0;
  assert(Aij.nb_dim()==3);
  assert(Aij.dimension(0)==nb_elem_tot);
  assert(Aij.dimension(1)==nb_faces_elem);
  assert(Aij.dimension(2)==nb_faces_elem);
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      nu_elem=nu(elem);
      volume=1./volumes(elem);
      volume*=nu_elem;
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          signei=1.;
          if (face_voisins(facei,0)!=elem) signei=-1.;
          for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
            {
              facej=elem_faces(elem,facej_loc);
              signej=1.;
              if (face_voisins(facej,0)!=elem) signej=-1.;
              psc=0.;
              for (dim=0; dim<Objet_U::dimension; dim++)
                psc+=face_normales(facei,dim)*face_normales(facej,dim);
              psc*=signei*signej;
              psc*=volume;
              Aij(elem,facei_loc,facej_loc)=psc;
              Aij(elem,facej_loc,facei_loc)=psc;
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Op_Diff_VEF_base::la_zone_vef, TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_cas_multiscalaire(), and ajouter_cas_scalaire().
calculer_coefficients_vectoriel_diag()
void Op_Dift_Stab_VEF_Face::calculer_coefficients_vectoriel_diag (const DoubleTab & nu, const DoubleTab & nu2, DoubleTab & Aij) const protected
Definition at line 831 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_comp=equation().inconnue().valeurs().line_size();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  double volume=0.,signei=0.,signej=0.;
  double psc=0.,nu_elem=0.,nu2_elem=0.;
  int elem=0,facei_loc=0,facei=0;
  int facej_loc=0,facej=0,dim=0;
  assert(nb_comp!=0);
  assert(nb_comp==Objet_U::dimension);
  assert(Aij.nb_dim()==4);
  assert(Aij.dimension(0)==nb_elem_tot);
  assert(Aij.dimension(1)==nb_faces_elem);
  assert(Aij.dimension(2)==nb_faces_elem);
  assert(Aij.dimension(3)==nb_comp);
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      volume=1./volumes(elem);
      nu_elem=nu(elem);
      nu_elem*=volume;
      nu2_elem=nu2(elem);
      nu2_elem*=volume;
      for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
        {
          facei=elem_faces(elem,facei_loc);
          signei=1.;
          if (face_voisins(facei,0)!=elem) signei=-1.;
          for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
            {
              facej=elem_faces(elem,facej_loc);
              signej=1.;
              if (face_voisins(facej,0)!=elem) signej=-1.;
// Partie standard
              psc=0.;
              for (dim=0; dim<Objet_U::dimension; dim++)
                psc+=face_normales(facei,dim)*face_normales(facej,dim);
              psc*=signei*signej;
              psc*=nu_elem;
              for (dim=0; dim<nb_comp; dim++)
                {
                  Aij(elem,facei_loc,facej_loc,dim)=psc;
                  Aij(elem,facej_loc,facei_loc,dim)=psc;
                }
// Partie transposee
              for (dim=0; dim<nb_comp; dim++)
                {
                  psc=face_normales(facei,dim)*face_normales(facej,dim);
                  psc*=signei*signej;
                  psc*=nu2_elem;
                  Aij(elem,facei_loc,facej_loc,dim)+=psc;
                  Aij(elem,facej_loc,facei_loc,dim)+=psc;
                }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), MorEqn::equation(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Equation_base::inconnue(), Op_Diff_VEF_base::la_zone_vef, TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_cas_vectoriel().
calculer_gradients()
double Op_Dift_Stab_VEF_Face::calculer_gradients (int facei, const DoubleTab & rij) const protected
Definition at line 978 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  const IntTab& get_num_fac_loc=zone_VEF.get_num_fac_loc();
  const DoubleTab& face_normales=zone_VEF.face_normales();
  const DoubleVect& volumes=zone_VEF.volumes();
  double volume=0.,signek=0.,psc=0.,mu_ij=0.;
  int elem=0,elem_loc=0,facei_loc=0;
  int facek_loc=0,facek=0,dim=0;
  for (elem_loc=0; elem_loc<2; elem_loc++)
    {
      facei_loc=get_num_fac_loc(facei,elem_loc);
      elem=face_voisins(facei,elem_loc);
      if (elem!=-1)
        {
          volume+=volumes(elem);
          for (facek_loc=0; facek_loc<nb_faces_elem; facek_loc++)
            if (facek_loc!=facei_loc)
              {
                facek=elem_faces(elem,facek_loc);
                signek=1.;
                if (face_voisins(facek,0)!=elem) signek=-1.;
                psc=0.;
                for (dim=0; dim<Objet_U::dimension; dim++)
                  psc+=face_normales(facek,dim)*rij(dim);
                psc*=signek;
                if (psc<0.) psc*=-1.;
                mu_ij+=psc;
              }
        }
    }
  mu_ij/=volume;
  mu_ij*=2.;
  return mu_ij;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), Zone_VF::get_num_fac_loc(), Op_Diff_VEF_base::la_zone_vef, Zone::nb_faces_elem(), Ref_Zone_VEF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter_antidiffusion(), and ajouter_antidiffusion_vectoriel().
calculer_max()
void Op_Dift_Stab_VEF_Face::calculer_max (const DoubleTab & inconnueTab, int & dim, DoubleTab & Maxima) const protected
Definition at line 1099 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  int elem=0,facei_loc=0,facei=0,facej_loc=0,facej=0;
  const int nb_comp=inconnueTab.line_size();
  double inc_i=0.,inc_j=0.;
  const DoubleVect& inconnue = inconnueTab;
  assert(Maxima.nb_dim()==1);
  assert(Maxima.dimension(0)==nb_faces_tot);
  assert(dim<nb_comp);
  for (facei=0; facei<nb_faces_tot; facei++)
    Maxima(facei)=inconnue[facei*nb_comp+dim];
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        inc_i=inconnue[facei*nb_comp+dim];
        double& maxi=Maxima(facei);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            inc_j=inconnue[facej*nb_comp+dim];
            double& maxj=Maxima(facej);
            if (inc_j>maxi) maxi=inc_j;
            if (inc_i>maxj) maxj=inc_i;
          }
      }
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_bords=les_cl.size();
  int num1=0, num2=0,n_bord=0,ind_face=0;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              facej=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (facei<facej)
                {
                  double& maxi=Maxima(facei);
                  double& maxj=Maxima(facej);
                  if (maxi>maxj) maxj=maxi;
                  if (maxj>maxi) maxi=maxj;
                }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_antidiffusion(), and ajouter_antidiffusion_vectoriel().
calculer_min()
void Op_Dift_Stab_VEF_Face::calculer_min (const DoubleTab & inconnueTab, int & dim, DoubleTab & Minima) const protected
Definition at line 1024 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const int nb_elem_tot=zone_VEF.nb_elem_tot();
  const int nb_faces_elem=zone_VEF.zone().nb_faces_elem();
  const int nb_faces_tot=zone_VEF.nb_faces_tot();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  int elem=0,facei_loc=0,facei=0,facej_loc=0,facej=0;
  const int nb_comp=inconnueTab.line_size();
  double inc_i=0.,inc_j=0.;
  const DoubleVect& inconnue = inconnueTab;
  assert(Minima.nb_dim()==1);
  assert(Minima.dimension(0)==nb_faces_tot);
  assert(dim<nb_comp);
  for (facei=0; facei<nb_faces_tot; facei++)
    Minima(facei)=inconnue[facei*nb_comp+dim];
  for (elem=0; elem<nb_elem_tot; elem++)
    for (facei_loc=0; facei_loc<nb_faces_elem; facei_loc++)
      {
        facei=elem_faces(elem,facei_loc);
        inc_i=inconnue[facei*nb_comp+dim];
        double& mini=Minima(facei);
        for (facej_loc=facei_loc+1; facej_loc<nb_faces_elem; facej_loc++)
          {
            facej=elem_faces(elem,facej_loc);
            inc_j=inconnue[facej*nb_comp+dim];
            double& minj=Minima(facej);
            if (inc_j<mini) mini=inc_j;
            if (inc_i<minj) minj=inc_i;
          }
      }
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const int nb_bords=les_cl.size();
  int num1=0, num2=0,n_bord=0,ind_face=0;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces_tot();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              facei=le_bord.num_face(ind_face);
              facej=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (facei<facej)
                {
                  double& mini=Minima(facei);
                  double& minj=Minima(facej);
                  if (mini<minj) minj=mini;
                  if (minj<mini) mini=minj;
                }
            }
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), Periodique::face_associee(), Cond_lim::frontiere_dis(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), TRUSTTab< _TYPE_ >::nb_dim(), Zone_dis_base::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Zone_dis_base::zone().
Referenced by ajouter_antidiffusion(), and ajouter_antidiffusion_vectoriel().
completer()
void Op_Dift_Stab_VEF_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 1174 of file Op_Dift_Stab_VEF_Face.cpp.
{
  Op_Dift_VEF_Face::completer();
  {
    const Zone_VEF& zone_VEF=la_zone_vef.valeur();
    const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
    const Conds_lim& les_cl=zone_Cl_VEF.les_conditions_limites();
    const int nb_bord=les_cl.size();
    const int nb_faces_tot=zone_VEF.nb_faces_tot();
    int ind_face=-1;
    is_dirichlet_faces_.resize(nb_faces_tot);
    is_dirichlet_faces_=0;
    for (int n_bord=0; n_bord<nb_bord; n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int nb_faces_bord_tot=le_bord.nb_faces_tot();
        int face=-1;
        if ( (sub_type(Dirichlet,la_cl.valeur()))
             || (sub_type(Dirichlet_homogene,la_cl.valeur()))
           )
          for (ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
            {
              face = le_bord.num_face(ind_face);
              is_dirichlet_faces_(face)=1;
            }
      }
  }
}
References Op_Dift_VEF_base::completer(), Cond_lim::frontiere_dis(), is_dirichlet_faces_, Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
contribuer_a_avec()
void Op_Dift_Stab_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 113 of file Op_Dift_Stab_VEF_Face.h.
{
  if (!new_jacobian_)
    Op_Dift_VEF_Face::contribuer_a_avec(inco,matrice);
  else
    {
      const Champ_base& inconnue = equation().inconnue().valeur();
      const Nature_du_champ nature_champ = inconnue.nature_du_champ();
      if (nature_champ!=multi_scalaire)
        ajouter_contribution(inco, matrice);
      else
        ajouter_contribution_multi_scalaire(inco, matrice);
    }
}
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face::contribuer_a_avec(), MorEqn::equation(), Equation_base::inconnue(), multi_scalaire, Field_base::nature_du_champ(), new_jacobian_, and Deriv_Champ_Inc_base::valeur().
cree_instance()
Objet_U * Op_Dift_Stab_VEF_Face::cree_instance () static
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
duplique()
int Op_Dift_Stab_VEF_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_Stab_VEF_Face_Var.
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
get_info()
const Type_info * Op_Dift_Stab_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_Stab_VEF_Face_Var.
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
info()
const Type_info * Op_Dift_Stab_VEF_Face::info () static
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
modifie_pour_Cl()
void Op_Dift_Stab_VEF_Face::modifie_pour_Cl (const DoubleTab & inconnue, DoubleTab & resu) const protected
Definition at line 215 of file Op_Dift_Stab_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF =  la_zone_vef.valeur();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const DoubleVect& inconnueVect = inconnue;
  DoubleVect& resuVect = resu;
  const int nb_bords=les_cl.size();
  const int nb_comp=resu.line_size();
  DoubleTab& tab_flux_bords = flux_bords_;
  tab_flux_bords.resize(zone_VEF.nb_faces_bord(),nb_comp);
  tab_flux_bords=0.;
  int num1=0, num2=0, n_bord=0;
  int face=0, face_associee=0;
  int ind_face=0, dim=0;
  double surface=0., flux=0.;
  for (n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      num1 = 0;
      num2 = le_bord.nb_faces();
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              face_associee=le_bord.num_face(la_cl_perio.face_associee(ind_face));
              if (face<face_associee)
                for (dim=0; dim<nb_comp; dim++)
                  {
                    resuVect[face*nb_comp+dim]+=resuVect[face_associee*nb_comp+dim];
                    resuVect[face_associee*nb_comp+dim]=resuVect[face*nb_comp+dim];
                  }
            }
        }
      if (sub_type(Neumann_paroi,la_cl.valeur()))
        {
          const Neumann_paroi& la_cl_paroi = ref_cast(Neumann_paroi,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.surface(face);
              for (dim=0; dim<nb_comp; dim++)
                {
                  flux=la_cl_paroi.flux_impose(ind_face,dim)*surface;
                  resuVect[face*nb_comp+dim]-=flux;
                  tab_flux_bords(face,dim)=flux;
                }
            }
        }
      if (sub_type(Echange_externe_impose,la_cl.valeur()))
        {
          const Echange_externe_impose& la_cl_paroi = ref_cast(Echange_externe_impose,la_cl.valeur());
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              surface=zone_VEF.surface(face);
              for (dim=0; dim<nb_comp; dim++)
                {
                  flux=la_cl_paroi.h_imp(ind_face,dim)*(la_cl_paroi.T_ext(ind_face,dim)-inconnueVect[face*nb_comp+dim])*surface;
                  resuVect[face*nb_comp+dim]-=flux;
                  tab_flux_bords(face,dim)=flux;
                }
            }
        }
      if (sub_type(Neumann_homogene,la_cl.valeur())
          || sub_type(Symetrie,la_cl.valeur())
          || sub_type(Neumann_sortie_libre,la_cl.valeur()))
        {
          for (ind_face=num1; ind_face<num2; ind_face++)
            {
              face=le_bord.num_face(ind_face);
              for (dim=0; dim<nb_comp; dim++)
                tab_flux_bords(face,dim)=0.;
            }
        }
    }
}
References Periodique::face_associee(), face_associee, Operateur_base::flux_bords_, Neumann_paroi::flux_impose(), Cond_lim::frontiere_dis(), Echange_impose_base::h_imp(), Op_Diff_VEF_base::la_zcl_vef, Op_Diff_VEF_base::la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Front_VF::num_face(), ref_cast, TRUSTTab< _TYPE_ >::resize(), vect_impl::size(), sub_type, Zone_VF::surface(), Echange_impose_base::T_ext(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
printOn()
Sortie & Op_Dift_Stab_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_Stab_VEF_Face_Var.
Definition at line 66 of file Op_Dift_Stab_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_Stab_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_VEF_base.
Reimplemented in Op_Dift_Stab_VEF_Face_Var.
Definition at line 74 of file Op_Dift_Stab_VEF_Face.cpp.
{
  Cerr<<"Je suis dans Op_Dift_Stab_VEF_Face::readOn()"<<finl;
  Motcle accouverte = "{" , accfermee = "}" ;
  Motcles les_mots(6);
  {
    les_mots[0]="nu";
    les_mots[1]="nut";
    les_mots[2]="nu_transp";
    les_mots[3]="nut_transp";
    les_mots[4]="standard";
    les_mots[5]="new_jacobian";
  }
  Motcle motlu;
  nu_lu_=1;
  nut_lu_=1;
  nu_transp_lu_=0;
  nut_transp_lu_=1;
  standard_=0;
  new_jacobian_=0;
  is>>motlu;
  if (motlu!=accouverte)
    if (Process::je_suis_maitre())
      {
        Cerr<<"Error in Op_Dift_Stab_VEF_Face::readOn()"<<finl;
        Cerr<<"Option keywords must be preceded by an open brace"<<finl;
        Process::exit();
      }
  is>>motlu;
  while (motlu!=accfermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          is>>nu_lu_;
          break;
        case 1 :
          is>>nut_lu_;
          break;
        case 2 :
          is>>nu_transp_lu_;
          break;
        case 3 :
          is>>nut_transp_lu_;
          break;
        case 4 :
          is>>standard_;
          break;
        case 5 :
          is>>new_jacobian_;
          break;
        default :
          if (Process::je_suis_maitre())
            {
              Cerr<<"Error in Op_Dift_Stab_VEF_Face::readOn()"<<finl;
              Cerr<<"Word "<<motlu<<" is unknown"<<finl;
              Cerr<<"Known keywords are : "<<les_mots<<finl;
              Process::exit();
            }
          break;
        }
      is>>motlu;
    }
  if (Process::je_suis_maitre())
    {
      Cerr<<"Options read in Op_Dift_Stab_VEF_Face operator are : ";
      Cerr<<"nu="<<nu_lu_<<" nut="<<nut_lu_<<" nu_transp=" <<nu_transp_lu_<<" nut_transp="<<nut_transp_lu_<<" standard="<<standard_<< finl;
    }
  is>>motlu;
  if (motlu!=accfermee)
    if (Process::je_suis_maitre())
      {
        Cerr<<"Error in Op_Dift_Stab_VEF_Face::readOn()"<<finl;
        Cerr<<"Final known keyword is the closing brace sign"<<finl;
        Process::exit();
      }
  return is ;
}
References Cerr, Process::exit(), finl, Process::je_suis_maitre(), new_jacobian_, nu_lu_, nu_transp_lu_, nut_lu_, nut_transp_lu_, Motcles::search(), and standard_.
Referenced by Op_Dift_Stab_VEF_Face_Var::readOn().
self_cast() [1/2]
const Op_Dift_Stab_VEF_Face & Op_Dift_Stab_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
self_cast() [2/2]
Op_Dift_Stab_VEF_Face & Op_Dift_Stab_VEF_Face::self_cast (Objet_U & r) static
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
taille_memoire()
unsigned Op_Dift_Stab_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Dift_Stab_VEF_Face_Var.
Definition at line 33 of file Op_Dift_Stab_VEF_Face.cpp.
{
Member Data Documentation
divergence_U
Ref_Champ_Inc Op_Dift_Stab_VEF_Face::divergence_U protected
Definition at line 72 of file Op_Dift_Stab_VEF_Face.h.
info_obj
const Type_info Op_Dift_Stab_VEF_Face::info_obj static
Definition at line 31 of file Op_Dift_Stab_VEF_Face.h.
is_dirichlet_faces_
IntTab Op_Dift_Stab_VEF_Face::is_dirichlet_faces_ protected
Definition at line 68 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_antidiffusion(), ajouter_antidiffusion_vectoriel(), and completer().
new_jacobian_
int Op_Dift_Stab_VEF_Face::new_jacobian_ protected
Definition at line 78 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_contribution(), ajouter_contribution_cl(), ajouter_contribution_multi_scalaire(), contribuer_a_avec(), and readOn().
nu_lu_
int Op_Dift_Stab_VEF_Face::nu_lu_ protected
Definition at line 74 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_cas_vectoriel(), and readOn().
nu_transp_lu_
int Op_Dift_Stab_VEF_Face::nu_transp_lu_ protected
Definition at line 76 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_cas_vectoriel(), and readOn().
nut_lu_
int Op_Dift_Stab_VEF_Face::nut_lu_ protected
Definition at line 75 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_cas_vectoriel(), and readOn().
nut_transp_lu_
int Op_Dift_Stab_VEF_Face::nut_transp_lu_ protected
Definition at line 77 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_cas_vectoriel(), and readOn().
standard_
int Op_Dift_Stab_VEF_Face::standard_ protected
Definition at line 67 of file Op_Dift_Stab_VEF_Face.h.
Referenced by ajouter_cas_multiscalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Operateurs/Op_Dift_Stab_VEF_Face.h
src/VEF/Operateurs/Op_Dift_Stab_VEF_Face.cpp