TRUST: Terme_Source_Acceleration Class Reference
Terme_Source_Acceleration Class Reference abstract
#include <Terme_Source_Acceleration.h>
Public Member Functions
~Terme_Source_Acceleration () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Terme_Source_Acceleration ()
void associer_pb (const Probleme_base &) override
DoubleTab & calculer (DoubleTab &) const override
resu=0; ajouter(resu); (appel a ajouter() de la classe derivee)
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const override
Methode surchargee de Source_base.
Les mots compris sont:
"ACCELERATION" => renvoie terme_source_post_, homogene a d/dt(rho*v)
Attention a l'effet de bord de ajouter() (voir commentaires de ajouter())
const Champ_Don & champ_vitesse () const
const Champ_Don & omega () const
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Terme_Source_Acceleration & self_cast (Objet_U &)
static const Terme_Source_Acceleration & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
Appel a Terme_Source_Acceleration::lire_data.
virtual void lire_data (Entree &s)
Methode appelee par readOn des classes derivees
Terme_Source_Acceleration_VDF_Face, ...
Le format attendu est le suivant
{
[ omega Un_Champ_uniforme
domegadt Un_Champ_uniforme
centre_rotation Un_Champ_uniforme
option TERME_COMPLET | CORIOLIS_SEUL | ENTRAINEMENT_SEUL ]
[ acceleration Un_Champ_uniforme ]
}
Un_Champ_uniforme est typiquement:
Champ_Uniforme 3 x y z
ou
Champ_Fonc_t DOM 3 fx(t) fy(t) fz(t)
virtual const Champ_Fonc_base & get_terme_source_post () const
virtual Champ_Fonc & get_set_terme_source_post () const
virtual const DoubleTab & calculer_vitesse_faces (DoubleTab &stockage) const =0
const DoubleTab & calculer_la_source (DoubleTab &src_faces) const
Calcul de la valeur du champ la_source aux faces en fonction de
- calculer_vitesse_faces()
- champ_acceleration_
- omega_
- domegadt_
- centre_rotation_
Parametre: champ_source
Signification: un champ discretise aux elements de la zone_VF dans lequel
on stocke le resultat du calcul. Espace virtuel a jour.
virtual const Navier_Stokes_std & get_eq_hydraulique () const
Renvoie eq_hydraulique_ !
void mettre_a_jour (double temps) override
Evalue les champs d'acceleration et de rotation au temps t.
Protected Member Functions inherited from Source_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Types
enum Option_TSA { TERME_COMPLET , CORIOLIS_SEUL , ENTRAINEMENT_SEUL }
Private Attributes
Champ_Fonc terme_source_post_
Champ_Don champ_vitesse_
Champ_Don champ_acceleration_
Champ_Don omega_
Champ_Don domegadt_
Champ_Don centre_rotation_
Option_TSA option_
Additional Inherited Members
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 29 of file Terme_Source_Acceleration.h.
Member Enumeration Documentation
Option_TSA
enum Terme_Source_Acceleration::Option_TSA private
Enumerator
TERME_COMPLET
CORIOLIS_SEUL
ENTRAINEMENT_SEUL
Definition at line 85 of file Terme_Source_Acceleration.h.
{ TERME_COMPLET, CORIOLIS_SEUL, ENTRAINEMENT_SEUL };
Constructor & Destructor Documentation
~Terme_Source_Acceleration()
Terme_Source_Acceleration::~Terme_Source_Acceleration () override
Definition at line 24 of file Terme_Source_Acceleration.cpp.
Terme_Source_Acceleration()
Terme_Source_Acceleration::Terme_Source_Acceleration ()
Definition at line 26 of file Terme_Source_Acceleration.cpp.
{
  /*
    Noms& nom=champs_compris_.liste_noms_compris();
    nom.dimensionner(1);
    nom[0]="ACCELERATION_TERME_SOURCE";
  */
}
Member Function Documentation
a_pour_Champ_Fonc()
int Terme_Source_Acceleration::a_pour_Champ_Fonc (const Motcle & mot, Ref_Champ_base & ch_ref) const override virtual
Methode surchargee de Source_base.
Les mots compris sont:
"ACCELERATION" => renvoie terme_source_post_, homogene a d/dt(rho*v)
Attention a l'effet de bord de ajouter() (voir commentaires de ajouter())
Reimplemented from Source_base.
Definition at line 395 of file Terme_Source_Acceleration.cpp.
{
  int ok = 0;
  if (mot == "ACCELERATION_TERME_SOURCE")
    {
      ch_ref = terme_source_post_.valeur();
      ok = 1;
    }
  return ok;
}
References terme_source_post_, and Deriv_Champ_Fonc_base::valeur().
associer_pb()
void Terme_Source_Acceleration::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 232 of file Terme_Source_Acceleration.cpp.
{
}
calculer()
DoubleTab & Terme_Source_Acceleration::calculer (DoubleTab & resu) const override virtual
resu=0; ajouter(resu); (appel a ajouter() de la classe derivee)
Reimplemented from Source_base.
Definition at line 366 of file Terme_Source_Acceleration.cpp.
{
  resu = 0;
  ajouter(resu);
  resu.echange_espace_virtuel();
  return resu;
}
References Source_base::ajouter(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
calculer_la_source()
const DoubleTab & Terme_Source_Acceleration::calculer_la_source (DoubleTab & src_faces) const protected
Calcul de la valeur du champ la_source aux faces en fonction de
- calculer_vitesse_faces()
- champ_acceleration_
- omega_
- domegadt_
- centre_rotation_
Parametre: champ_source
Signification: un champ discretise aux elements de la zone_VF dans lequel
on stocke le resultat du calcul. Espace virtuel a jour.
< champ acceleration
< omega
< domegadt
< centre_gravite
< Terme d'acceleration
< =0. en 2D
< en 2D, v[3]=0.
< en 2D, xgr[3]=0.
Definition at line 258 of file Terme_Source_Acceleration.cpp.
{
  const Zone_VF&    zone_VF = ref_cast(Zone_VF, equation().zone_dis().valeur());;
  const DoubleTab& centre_faces = zone_VF.xv();
  double a[3] = {0., 0., 0.};  //!< champ acceleration
  double w[3] = {0., 0., 0.};  //!< omega
  double dw[3] = {0., 0., 0.}; //!< domegadt
  double c[3] = {0., 0., 0.};  //!< centre_gravite
  const int dim = Objet_U::dimension;
// ****************************************************************
// INITIALISATION DE a, w, dw, c
  int rotation_solide = 0;
  {
    int j;
    if (champ_acceleration_.non_nul())
      {
        const DoubleTab& a_ = champ_acceleration_.valeur().valeurs();
        for (j = 0; j < dim; j++)
          a[j] = a_(0, j);
      }
    if (omega_.non_nul())
      {
// L'utilisateur a specifie un mouvement de rotation solide
        const DoubleTab& champ_w  = omega_          .valeur().valeurs();
        const DoubleTab& champ_dw = domegadt_       .valeur().valeurs();
        const DoubleTab& champ_c  = centre_rotation_.valeur().valeurs();
// Attention: en 2D, le vecteur rotation est typiquement oriente
// dans la direction Z : donc boucle jusqu'a 3 dans tous les cas:
        for (j = 0; j < 3; j++) w[j]  = champ_w(0,j);
        for (j = 0; j < 3; j++) dw[j] = champ_dw(0,j);
        for (j = 0; j < dim; j++) c[j]  = champ_c(0,j);
        rotation_solide = 1;
      }
  }
// Si on a un terme source de rotation solide, on a besoin des trois
// composantes de la vitesse du fluide aux faces:
// Un espace de stockage pour la vitesse si elle doit etre
// calculee (en VDF, on calcule les trois composantes a chaque face)
  DoubleTab vitesse_faces_stockage;
// Calcul du champ de vitesse aux faces (a partir de l'inconnue
// de l'equation de N.S.)
  const DoubleTab& vitesse_faces =
    (rotation_solide)
    ? calculer_vitesse_faces(vitesse_faces_stockage)
    : vitesse_faces_stockage;
// **************************************************
// BOUCLE SUR LES FACES
  int i_face;
  const int nb_faces = acceleration_aux_faces.dimension(0);
// Vecteur vitesse du fluide dans l'element courant
// (attention: initialisation de la composante Z pour le 2D)
  double v[3] = {0., 0., 0.};
// Vecteur (centre_face - centre_rotation)
// (idem)
  double xgr[3] = {0., 0., 0.};
  for (i_face = 0; i_face < nb_faces; i_face++)
    {
      int j;
      double src[3];
      src[0] = -a[0]; //!< Terme d'acceleration
      src[1] = -a[1];
      src[2] = -a[2]; //!< =0. en 2D
// Formules identiques en 2D et en 3D :
// en 2D, les composantes z de v et xgr sont nulles.
      if (rotation_solide)
        {
          for (j = 0; j < dim; j++) //!< en 2D, v[3]=0.
            v[j] = vitesse_faces(i_face, j);
          for (j = 0; j < dim; j++) //!< en 2D, xgr[3]=0.
            xgr[j] = centre_faces(i_face, j) - c[j];
          if (option_ != ENTRAINEMENT_SEUL)
            {
              src[0] += -2. * (w[1] * v[2] - w[2] * v[1]);
              src[1] += -2. * (w[2] * v[0] - w[0] * v[2]);
              src[2] += -2. * (w[0] * v[1] - w[1] * v[0]);
              src[0] += dw[2] * xgr[1] - dw[1] * xgr[2];
              src[1] += dw[0] * xgr[2] - dw[2] * xgr[0];
              src[2] += dw[1] * xgr[0] - dw[0] * xgr[1];
            }
          if (option_ != CORIOLIS_SEUL)
            {
              src[0] += w[2]*w[2]*xgr[0] - w[0]*w[2]*xgr[2] - w[0]*w[1]*xgr[1] + w[1]*w[1]*xgr[0];
              src[1] += w[0]*w[0]*xgr[1] - w[0]*w[1]*xgr[0] - w[1]*w[2]*xgr[2] + w[2]*w[2]*xgr[1];
              src[2] += w[1]*w[1]*xgr[2] - w[1]*w[2]*xgr[1] - w[2]*w[0]*xgr[0] + w[0]*w[0]*xgr[2];
            }
        }
      for (j = 0; j < dim; j++)
        acceleration_aux_faces(i_face, j) = src[j];
    }
  return acceleration_aux_faces;
}
References calculer_vitesse_faces(), centre_rotation_, champ_acceleration_, CORIOLIS_SEUL, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, domegadt_, ENTRAINEMENT_SEUL, MorEqn::equation(), O_U_Ptr::non_nul(), omega_, option_, ref_cast, Deriv_Champ_Don_base::valeur(), valeur(), Champ_Don_base::valeurs(), and Zone_VF::xv().
Referenced by Terme_Source_Acceleration_VEF_Face::ajouter(), and Terme_Source_Acceleration_VDF_Face::ajouter_blocs().
calculer_vitesse_faces()
virtual const DoubleTab & Terme_Source_Acceleration::calculer_vitesse_faces (DoubleTab & stockage) const protected pure virtual
Implemented in Terme_Source_Acceleration_VDF_Face, and Terme_Source_Acceleration_VEF_Face.
Referenced by calculer_la_source().
champ_vitesse()
const Champ_Don & Terme_Source_Acceleration::champ_vitesse () const inline
Definition at line 39 of file Terme_Source_Acceleration.h.
{ return champ_vitesse_; }
References champ_vitesse_.
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
get_eq_hydraulique()
const Navier_Stokes_std & Terme_Source_Acceleration::get_eq_hydraulique () const protected virtual
Renvoie eq_hydraulique_ !
Definition at line 408 of file Terme_Source_Acceleration.cpp.
{
  const Navier_Stokes_std& ns = ref_cast(Navier_Stokes_std, equation());
  return ns;
}
References MorEqn::equation(), and ref_cast.
Referenced by Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), and Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces().
get_info()
const Type_info * Terme_Source_Acceleration::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Acceleration_VDF_Face, and Terme_Source_Acceleration_VEF_Face.
Definition at line 24 of file Terme_Source_Acceleration.cpp.
get_set_terme_source_post()
Champ_Fonc & Terme_Source_Acceleration::get_set_terme_source_post () const protected virtual
Definition at line 241 of file Terme_Source_Acceleration.cpp.
{
// terme_source_post_ est mutable, on peut donc le renvoyer "non const"
  return terme_source_post_;
}
References terme_source_post_.
Referenced by Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), lire_data(), and mettre_a_jour().
get_terme_source_post()
const Champ_Fonc_base & Terme_Source_Acceleration::get_terme_source_post () const protected virtual
Definition at line 236 of file Terme_Source_Acceleration.cpp.
{
  return terme_source_post_.valeur();
}
References terme_source_post_, and Deriv_Champ_Fonc_base::valeur().
info()
const Type_info * Terme_Source_Acceleration::info () static
Definition at line 24 of file Terme_Source_Acceleration.cpp.
lire_data()
void Terme_Source_Acceleration::lire_data (Entree & s) protected virtual
Methode appelee par readOn des classes derivees
Terme_Source_Acceleration_VDF_Face, ...
Le format attendu est le suivant
{
[ omega Un_Champ_uniforme
domegadt Un_Champ_uniforme
centre_rotation Un_Champ_uniforme
option TERME_COMPLET | CORIOLIS_SEUL | ENTRAINEMENT_SEUL ]
[ acceleration Un_Champ_uniforme ]
}
Un_Champ_uniforme est typiquement:
Champ_Uniforme 3 x y z
ou
Champ_Fonc_t DOM 3 fx(t) fy(t) fz(t)
Definition at line 69 of file Terme_Source_Acceleration.cpp.
{
  if (je_suis_maitre())
    Cerr << "Terme_Source_Acceleration::lire_data" << finl;
// Valeurs par defaut:
  option_ = TERME_COMPLET;
  Motcles les_mots(7);
  les_mots[0] = "omega";
  les_mots[1] = "domegadt";
  les_mots[2] = "centre_rotation";
  les_mots[3] = "option";
  les_mots[4] = "acceleration";
  les_mots[5] = "}";
  les_mots[6] = "vitesse";
  Motcle motlu;
  s >> motlu;
  if (motlu != "{")
    {
      Cerr << "Erreur dans Terme_Source_Acceleration::lire_data" << finl;
      Cerr << " On attendait {" << finl;
      assert(0);
      exit();
    }
  int fini = 0;
  while (!fini)
    {
      s >> motlu;
      const int i_mot = les_mots.search(motlu);
      if (je_suis_maitre() && i_mot < 5)
        Cerr << "Lecture de " << motlu << " : ";
      switch(i_mot)
        {
        case 0:
          s >> omega_;
          if (je_suis_maitre())
            Cerr << omega_.que_suis_je() << finl;
          break;
        case 1:
          s >> domegadt_;
          if (je_suis_maitre())
            Cerr << domegadt_.que_suis_je() << finl;
          break;
        case 2:
          s >> centre_rotation_;
          if (je_suis_maitre())
            Cerr << centre_rotation_.que_suis_je() << finl;
          break;
        case 3:
          {
            Motcles les_options(3);
            les_options[0] = "terme_complet";
            les_options[1] = "coriolis_seul";
            les_options[2] = "entrainement_seul";
            s >> motlu;
            const int i = les_options.search(motlu);
            switch (i)
              {
              case 0:
                option_ = TERME_COMPLET;
                break;
              case 1:
                option_ = CORIOLIS_SEUL;
                break;
              case 2:
                option_ = ENTRAINEMENT_SEUL;
                break;
              default:
                Cerr << "Erreur, les options valides sont : " << finl;
                Cerr << les_options << finl;
                assert(0);
                exit();
              }
            if (je_suis_maitre())
              Cerr << motlu << finl;
            break;
          }
        case 4:
          s >> champ_acceleration_;
          if (je_suis_maitre())
            Cerr << champ_acceleration_.que_suis_je() << finl;
          break;
        case 5:
          fini = 1;
          break;
        case 6:
          s >> champ_vitesse_;
          if (je_suis_maitre())
            Cerr << champ_vitesse_.que_suis_je() << finl;
          break;
        default:
          Cerr << "Erreur dans Terme_Source_Acceleration::lire_data" << finl;
          Cerr << " On ne comprend pas le mot " << motlu << finl;
          Cerr << " Les mots compris sont : " << les_mots << finl;
          assert(0);
          exit();
        }
    }
// On verifie que c'est coherent:
  int n = 0;
  if (omega_.non_nul()) n++;
  if (domegadt_.non_nul()) n++;
  if (centre_rotation_.non_nul()) n++;
  if (n != 0 && n != 3)
    {
      Cerr << "Erreur dans Terme_Source_Acceleration::lire_data" << finl;
      Cerr << " Si OMEGA ou DOMEGADT ou CENTRE_GRAVITE est donne" << finl;
      Cerr << " alors les trois doivent etre donnes" << finl;
      assert(0);
      exit();
    }
  if (n > 0)
    {
      if (omega_.valeur().valeurs().dimension(0) != 1
          || domegadt_.valeur().valeurs().dimension(0) != 1
          || omega_.valeur().valeurs().dimension(1) != 3
          || domegadt_.valeur().valeurs().dimension(1) != 3)
        {
          Cerr << "Erreur dans Terme_Source_Acceleration::lire_data" << finl;
          Cerr << " les champs OMEGA et DOMEGADT doivent etre des champs" << finl;
          Cerr << " uniformes a trois composantes (vecteur aligne sur Z en 2D)" << finl;
          assert(0);
          exit();
        }
    }
  if (champ_acceleration_.non_nul())
    {
      if (champ_acceleration_.valeur().valeurs().dimension(0) != 1)
        {
          Cerr << "Erreur dans Terme_Source_Acceleration::lire_data" << finl;
          Cerr << " Le champ ACCELERATION doit etre un champ uniforme" << finl;
          assert(0);
          exit();
        }
    }
// Discretisation de la_source et terme_source_post
// Il faut absolument le faire ici pour disposer des champs au moment de
// la lecture des postraitements (appel a a_pour_Champ_Fonc)
  {
    const Equation_base& eqn = equation();
    if (!sub_type(Navier_Stokes_std, eqn))
      {
        Cerr << "Erreur dans Terme_Source_Acceleration::lire_data\n"
             << " Ce terme source ne peut etre insere que dans une equation\n"
             << " derivee de Navier_Stokes_std" << finl;
        assert(0);
        exit();
      }
    const Discretisation_base& dis   = eqn.discretisation();
    const Zone_dis_base&        zone  = eqn.zone_dis().valeur();
    const double                temps = eqn.schema_temps().temps_courant();
    dis.discretiser_champ("vitesse", zone, "acceleration_terme_source", "kg/ms^2",
                          Objet_U::dimension, /* composantes */
                          temps,
                          get_set_terme_source_post());
    champs_compris_.ajoute_champ(terme_source_post_);
  }
}
References Champs_compris::ajoute_champ(), centre_rotation_, Cerr, champ_acceleration_, champ_vitesse_, Source_base::champs_compris_, CORIOLIS_SEUL, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), domegadt_, ENTRAINEMENT_SEUL, MorEqn::equation(), Process::exit(), finl, get_set_terme_source_post(), Process::je_suis_maitre(), O_U_Ptr::non_nul(), omega_, option_, Objet_U::que_suis_je(), Equation_base::schema_temps(), Motcles::search(), sub_type, Schema_Temps_base::temps_courant(), TERME_COMPLET, terme_source_post_, Deriv_Champ_Don_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don_base::valeurs(), and Equation_base::zone_dis().
Referenced by Terme_Source_Acceleration_VDF_Face::readOn(), and Terme_Source_Acceleration_VEF_Face::readOn().
mettre_a_jour()
void Terme_Source_Acceleration::mettre_a_jour (double temps) override protected virtual
Evalue les champs d'acceleration et de rotation au temps t.
Reimplemented from Source_base.
Definition at line 376 of file Terme_Source_Acceleration.cpp.
{
// Cerr << "Terme_Source_Acceleration::mettre_a_jour temps=" << temps << finl;
  if (champ_acceleration_.non_nul())
    champ_acceleration_.mettre_a_jour(temps);
  if (omega_.non_nul())
    {
      omega_.mettre_a_jour(temps);
      domegadt_.mettre_a_jour(temps);
      centre_rotation_.mettre_a_jour(temps);
    }
  get_set_terme_source_post().mettre_a_jour(temps);
}
References centre_rotation_, champ_acceleration_, domegadt_, get_set_terme_source_post(), Champ_Don::mettre_a_jour(), Champ_Fonc::mettre_a_jour(), O_U_Ptr::non_nul(), and omega_.
omega()
const Champ_Don & Terme_Source_Acceleration::omega () const inline
Definition at line 40 of file Terme_Source_Acceleration.h.
{ return omega_; }
References omega_.
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
printOn()
Sortie & Terme_Source_Acceleration::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Terme_Source_Acceleration_VDF_Face, and Terme_Source_Acceleration_VEF_Face.
Definition at line 35 of file Terme_Source_Acceleration.cpp.
{
  Cerr << "Terme_Source_Acceleration::printOn : appel invalide" << finl;
  assert(0);
  exit();
  return s;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Terme_Source_Acceleration::readOn (Entree & s) override protected virtual
Appel a Terme_Source_Acceleration::lire_data.
Reimplemented from Source_base.
Reimplemented in Terme_Source_Acceleration_VDF_Face, and Terme_Source_Acceleration_VEF_Face.
Definition at line 44 of file Terme_Source_Acceleration.cpp.
{
  Cerr << "Terme_Source_Acceleration::readOn : appel invalide" << finl;
  assert(0);
  exit();
  return s;
}
References Cerr, Process::exit(), and finl.
self_cast() [1/2]
const Terme_Source_Acceleration & Terme_Source_Acceleration::self_cast (const Objet_U & r) static
Definition at line 24 of file Terme_Source_Acceleration.cpp.
self_cast() [2/2]
Terme_Source_Acceleration & Terme_Source_Acceleration::self_cast (Objet_U & r) static
Definition at line 24 of file Terme_Source_Acceleration.cpp.
Member Data Documentation
centre_rotation_
Champ_Don Terme_Source_Acceleration::centre_rotation_ private
Definition at line 82 of file Terme_Source_Acceleration.h.
Referenced by calculer_la_source(), lire_data(), and mettre_a_jour().
champ_acceleration_
Champ_Don Terme_Source_Acceleration::champ_acceleration_ private
Definition at line 69 of file Terme_Source_Acceleration.h.
Referenced by calculer_la_source(), lire_data(), and mettre_a_jour().
champ_vitesse_
Champ_Don Terme_Source_Acceleration::champ_vitesse_ private
Definition at line 62 of file Terme_Source_Acceleration.h.
Referenced by champ_vitesse(), and lire_data().
domegadt_
Champ_Don Terme_Source_Acceleration::domegadt_ private
Definition at line 79 of file Terme_Source_Acceleration.h.
Referenced by calculer_la_source(), lire_data(), and mettre_a_jour().
info_obj
const Type_info Terme_Source_Acceleration::info_obj static
Definition at line 32 of file Terme_Source_Acceleration.h.
omega_
Champ_Don Terme_Source_Acceleration::omega_ private
Definition at line 76 of file Terme_Source_Acceleration.h.
Referenced by calculer_la_source(), lire_data(), mettre_a_jour(), and omega().
option_
Option_TSA Terme_Source_Acceleration::option_ private
Definition at line 86 of file Terme_Source_Acceleration.h.
Referenced by calculer_la_source(), and lire_data().
terme_source_post_
Champ_Fonc Terme_Source_Acceleration::terme_source_post_ mutable private
Definition at line 56 of file Terme_Source_Acceleration.h.
Referenced by a_pour_Champ_Fonc(), get_set_terme_source_post(), get_terme_source_post(), and lire_data().
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Sources/Terme_Source_Acceleration.h
src/ThHyd/Incompressible/Sources/Terme_Source_Acceleration.cpp