TRUST: Ref_Zone_Cl_VEFP1B Class Reference
Ref_Zone_Cl_VEFP1B Class Reference
#include <Ref_Zone_Cl_VEFP1B.h>
Public Member Functions
~Ref_Zone_Cl_VEFP1B ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_Cl_VEFP1B ()
Ref_Zone_Cl_VEFP1B (const Zone_Cl_VEFP1B &)
Ref_Zone_Cl_VEFP1B (const Ref_Zone_Cl_VEFP1B &)
const Zone_Cl_VEFP1B & valeur () const
Zone_Cl_VEFP1B & valeur ()
const Zone_Cl_VEFP1B * operator-> () const
Zone_Cl_VEFP1B * operator-> ()
const Ref_Zone_Cl_VEFP1B & operator= (const Zone_Cl_VEFP1B &)
const Ref_Zone_Cl_VEFP1B & operator= (const Ref_Zone_Cl_VEFP1B &)
operator const Zone_Cl_VEFP1B & () const
operator Zone_Cl_VEFP1B & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_Cl_VEFP1B & self_cast (Objet_U &)
static const Ref_Zone_Cl_VEFP1B & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_Cl_VEFP1B * pointeur_
Detailed Description
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
Constructor & Destructor Documentation
Ref_Zone_Cl_VEFP1B::~Ref_Zone_Cl_VEFP1B ()
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Ref_Zone_Cl_VEFP1B::Ref_Zone_Cl_VEFP1B ()
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Ref_Zone_Cl_VEFP1B::Ref_Zone_Cl_VEFP1B (const Zone_Cl_VEFP1B & t)
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Ref_Zone_Cl_VEFP1B::Ref_Zone_Cl_VEFP1B (const Ref_Zone_Cl_VEFP1B & t)
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Member Function Documentation
Objet_U * Ref_Zone_Cl_VEFP1B::cree_instance () [static]
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
int Ref_Zone_Cl_VEFP1B::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Type_info * Ref_Zone_Cl_VEFP1B::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Type_info & Ref_Zone_Cl_VEFP1B::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Type_info * Ref_Zone_Cl_VEFP1B::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Ref_Zone_Cl_VEFP1B::operator const Zone_Cl_VEFP1B & () const
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Ref_Zone_Cl_VEFP1B::operator Zone_Cl_VEFP1B & ()
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Zone_Cl_VEFP1B * Ref_Zone_Cl_VEFP1B::operator-> () const [inline]
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
Zone_Cl_VEFP1B * Ref_Zone_Cl_VEFP1B::operator-> () [inline]
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
const Ref_Zone_Cl_VEFP1B & Ref_Zone_Cl_VEFP1B::operator= (const Ref_Zone_Cl_VEFP1B & t)
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Ref_Zone_Cl_VEFP1B & Ref_Zone_Cl_VEFP1B::operator= (const Zone_Cl_VEFP1B & t)
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Sortie & Ref_Zone_Cl_VEFP1B::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Entree & Ref_Zone_Cl_VEFP1B::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Ref_Zone_Cl_VEFP1B & Ref_Zone_Cl_VEFP1B::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
Ref_Zone_Cl_VEFP1B & Ref_Zone_Cl_VEFP1B::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
void Ref_Zone_Cl_VEFP1B::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
unsigned Ref_Zone_Cl_VEFP1B::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_Cl_VEFP1B.cpp.
const Zone_Cl_VEFP1B & Ref_Zone_Cl_VEFP1B::valeur () const [inline]
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
Referenced by Terme_Source_Acceleration_VEF_Face::ajouter(), Op_Diff_P1NC_barprim::calculer(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), and Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl().
Zone_Cl_VEFP1B & Ref_Zone_Cl_VEFP1B::valeur () [inline]
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
Member Data Documentation
const Type_info Ref_Zone_Cl_VEFP1B::info_obj [static]
Reimplemented from Ref_.
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
Zone_Cl_VEFP1B* Ref_Zone_Cl_VEFP1B::pointeur_ [private]
Definition at line 30 of file Ref_Zone_Cl_VEFP1B.h.
The documentation for this class was generated from the following files:
src/P1NCP1B/Zones/Ref_Zone_Cl_VEFP1B.h
src/P1NCP1B/Zones/Ref_Zone_Cl_VEFP1B.cpp