TRUST: Evaluateur_Source_VEF Class Reference
Evaluateur_Source_VEF Class Reference abstract
#include <Evaluateur_Source_VEF.h>
Public Member Functions
Evaluateur_Source_VEF ()
virtual ~Evaluateur_Source_VEF ()
Evaluateur_Source_VEF (const Evaluateur_Source_VEF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual void changer_volumes_entrelaces_Cl (DoubleVect &)=0
Protected Attributes
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_cl
Detailed Description
Definition at line 32 of file Evaluateur_Source_VEF.h.
Constructor & Destructor Documentation
Evaluateur_Source_VEF() [1/2]
Evaluateur_Source_VEF::Evaluateur_Source_VEF () inline
Definition at line 56 of file Evaluateur_Source_VEF.h.
{}
~Evaluateur_Source_VEF()
virtual Evaluateur_Source_VEF::~Evaluateur_Source_VEF () inline virtual
Definition at line 38 of file Evaluateur_Source_VEF.h.
{};
Evaluateur_Source_VEF() [2/2]
Evaluateur_Source_VEF::Evaluateur_Source_VEF (const Evaluateur_Source_VEF & eval) inline
Definition at line 58 of file Evaluateur_Source_VEF.h.
  : la_zone(eval.la_zone),la_zone_cl(eval.la_zone_cl)
{
}
Member Function Documentation
associer_zones()
void Evaluateur_Source_VEF::associer_zones (const Zone_dis_base & zone_vef, const Zone_Cl_dis_base & zone_cl_vef) inline
Definition at line 63 of file Evaluateur_Source_VEF.h.
{
  la_zone = ref_cast(Zone_VEF,zone_vef);
  la_zone_cl = ref_cast(Zone_Cl_VEF,zone_cl_vef);
  completer();
}
References completer(), la_zone, la_zone_cl, and ref_cast.
Referenced by Terme_Puissance_Thermique_QC_VEF_Face::associer_zones(), Source_Darcy_VEF_Face::associer_zones(), Source_Dirac_VEF_Face::associer_zones(), Source_Forchheimer_VEF_Face::associer_zones(), Terme_Puissance_Thermique_VEF_Face::associer_zones(), and Terme_Source_Constituant_VEF_Face::associer_zones().
changer_volumes_entrelaces_Cl()
virtual void Evaluateur_Source_VEF::changer_volumes_entrelaces_Cl (DoubleVect &) pure virtual
Implemented in Evaluateur_Source_VEF_Face.
completer()
virtual void Evaluateur_Source_VEF::completer () pure virtual
Implemented in Eval_Puiss_Th_QC_VEF_Face, Eval_Puiss_Th_VEF_Face, Eval_Source_C_VEF_Face, and Evaluateur_Source_VEF_Face.
Referenced by associer_zones().
mettre_a_jour()
virtual void Evaluateur_Source_VEF::mettre_a_jour () pure virtual
Implemented in Eval_Puiss_Th_QC_VEF_Face, Eval_Darcy_VEF_Face, Eval_Dirac_VEF_Face, Eval_Forchheimer_VEF_Face, Eval_Puiss_Th_VEF_Face, and Eval_Source_C_VEF_Face.
Member Data Documentation
la_zone
Ref_Zone_VEF Evaluateur_Source_VEF::la_zone protected
Definition at line 47 of file Evaluateur_Source_VEF.h.
Referenced by Eval_Darcy_VEF_Face::associer(), associer_zones(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), Eval_Darcy_VEF_Face::mettre_a_jour(), and Eval_Dirac_VEF_Face::mettre_a_jour().
la_zone_cl
Ref_Zone_Cl_VEF Evaluateur_Source_VEF::la_zone_cl protected
Definition at line 48 of file Evaluateur_Source_VEF.h.
Referenced by associer_zones(), and Evaluateur_Source_VEF_Face::completer().
The documentation for this class was generated from the following file:
src/VEF/Sources/Evaluateurs/Evaluateur_Source_VEF.h