TRUST: Ref_Table Class Reference
Ref_Table Class Reference
#include <Ref_Table.h>
Public Member Functions
~Ref_Table ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Table ()
Ref_Table (const Table &)
Ref_Table (const Ref_Table &)
const Table & valeur () const
Table & valeur ()
const Table * operator-> () const
Table * operator-> ()
const Ref_Table & operator= (const Table &)
const Ref_Table & operator= (const Ref_Table &)
operator const Table & () const
operator Table & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Table & self_cast (Objet_U &)
static const Ref_Table & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Table * pointeur_
Detailed Description
Definition at line 28 of file Ref_Table.h.
Constructor & Destructor Documentation
Ref_Table::~Ref_Table ()
Definition at line 26 of file Ref_Table.cpp.
Ref_Table::Ref_Table ()
Definition at line 26 of file Ref_Table.cpp.
Ref_Table::Ref_Table (const Table & t)
Definition at line 26 of file Ref_Table.cpp.
Ref_Table::Ref_Table (const Ref_Table & t)
Definition at line 26 of file Ref_Table.cpp.
Member Function Documentation
Objet_U * Ref_Table::cree_instance () [static]
Definition at line 26 of file Ref_Table.cpp.
int Ref_Table::duplique () const [virtual]
Implements Ref_.
Definition at line 26 of file Ref_Table.cpp.
const Type_info * Ref_Table::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Table.cpp.
const Type_info & Ref_Table::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 26 of file Ref_Table.cpp.
const Type_info * Ref_Table::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Table.cpp.
Ref_Table::operator const Table & () const
Definition at line 26 of file Ref_Table.cpp.
Ref_Table::operator Table & ()
Definition at line 26 of file Ref_Table.cpp.
const Table * Ref_Table::operator-> () const [inline]
Definition at line 28 of file Ref_Table.h.
Table * Ref_Table::operator-> () [inline]
Definition at line 28 of file Ref_Table.h.
const Ref_Table & Ref_Table::operator= (const Ref_Table & t)
Definition at line 26 of file Ref_Table.cpp.
const Ref_Table & Ref_Table::operator= (const Table & t)
Definition at line 26 of file Ref_Table.cpp.
Sortie & Ref_Table::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Table.cpp.
Entree & Ref_Table::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 26 of file Ref_Table.cpp.
const Ref_Table & Ref_Table::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 26 of file Ref_Table.cpp.
Ref_Table & Ref_Table::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 26 of file Ref_Table.cpp.
void Ref_Table::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 26 of file Ref_Table.cpp.
unsigned Ref_Table::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Ref_Table.cpp.
const Table & Ref_Table::valeur () const [inline]
Definition at line 28 of file Ref_Table.h.
Referenced by Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), and Champ_Fonc_Tabule_P0_CoviMAC::mettre_a_jour().
Table & Ref_Table::valeur () [inline]
Definition at line 28 of file Ref_Table.h.
Member Data Documentation
const Type_info Ref_Table::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Table.h.
Table* Ref_Table::pointeur_ [private]
Definition at line 28 of file Ref_Table.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Ref_Table.h
src/Kernel/Math/Ref_Table.cpp