TRUST: Loi_Etat_Binaire_GP_base Class Reference
Loi_Etat_Binaire_GP_base Class Reference
classe Loi_Etat_Binaire_GP_base
Cette classe represente la loi d'etat pour les melanges binaires.
Elle definit un fluide binaire dilatable dont la loi d'eata est :
Pth = rho*R*T*(Y1/M1+Y2/M2)
#include <Loi_Etat_Binaire_GP_base.h>
Public Member Functions
~Loi_Etat_Binaire_GP_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Loi_Etat_Binaire_GP_base ()
void calculer_lambda ()
Calcule la conductivite.
void calculer_mu ()
Calcule la viscosite dynamique.
void calculer_mu_wilke ()
Calcule la viscosite dynamique de mélange (depend des fraction massique)
Voir Wilke https://aip.scitation.org/doi/pdf/10.1063/1.1747673.
void calculer_alpha ()
Calcule la diffusivite.
void calculer_mu_sur_Sc ()
returns rho * D
void calculer_nu_sur_Sc ()
returns D
void calculer_Cp ()
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
const Nom type_fluide () const
Renvoie le type de fluide associe.
double inverser_Pth (double, double)
Calcule la pression avec la temperature et la masse volumique.
virtual double calculer_masse_volumique (double P, double Y1) const
virtual void calculer_masse_volumique ()=0
Calcule la masse volumique.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Loi_Etat_Binaire_GP_base & self_cast (Objet_U &)
static const
Loi_Etat_Binaire_GP_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double massmol1_
double massmol2_
double mu1_
double mu2_
double tempr_
double diff_coeff_
Detailed Description
classe Loi_Etat_Binaire_GP_base
Cette classe represente la loi d'etat pour les melanges binaires.
Elle definit un fluide binaire dilatable dont la loi d'eata est :
Pth = rho*R*T*(Y1/M1+Y2/M2)
Definition at line 41 of file Loi_Etat_Binaire_GP_base.h.
Constructor & Destructor Documentation
Loi_Etat_Binaire_GP_base::~Loi_Etat_Binaire_GP_base ()
Definition at line 30 of file Loi_Etat_Binaire_GP_base.cpp.
Loi_Etat_Binaire_GP_base::Loi_Etat_Binaire_GP_base ()
Definition at line 32 of file Loi_Etat_Binaire_GP_base.cpp.
                                                  :
  massmol1_(-1),massmol2_(-1),mu1_(-1),mu2_(-1),tempr_(-1),diff_coeff_(-1) { }
Member Function Documentation
void Loi_Etat_Binaire_GP_base::calculer_alpha () [virtual]
Calcule la diffusivite.
Reimplemented from Loi_Etat_GP_base.
Definition at line 140 of file Loi_Etat_Binaire_GP_base.cpp.
{
  /* Do nothing */
}
void Loi_Etat_Binaire_GP_base::calculer_Cp () [virtual]
Calcule le Cp
NE FAIT RIEN : le Cp est constant.
Reimplemented from Loi_Etat_GP_base.
Definition at line 245 of file Loi_Etat_Binaire_GP_base.cpp.
{
  /* Do nothing */
}
void Loi_Etat_Binaire_GP_base::calculer_lambda () [virtual]
Calcule la conductivite.
Reimplemented from Loi_Etat_GP_base.
Definition at line 54 of file Loi_Etat_Binaire_GP_base.cpp.
{
  /* Do nothing */
}
double Loi_Etat_Binaire_GP_base::calculer_masse_volumique (double P, double Y1) const [virtual]
Reimplemented from Loi_Etat_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 299 of file Loi_Etat_Binaire_GP_base.cpp.
References massmol1_, massmol2_, Loi_Etat_Melange_GP_base::R_GAS, and tempr_.
{
  /*
   * Mixing species state equation
   * ===========================================================================
   * rho = ( P * M_mix ) / ( R * T)
   * with M_mix = 1 / (Y1/M1 + Y2/M2) = = M2 / (M2Y1/M1 + Y2)
   * But Y2 = 1 - Y1 => M_mix = M2 / (M2Y1/M1 + 1 -Y1) = M2 / (1 + Y1(M2/M1 -1))
   * ===========================================================================
   * See https://doi.org/10.1016/j.ijheatmasstransfer.2020.120470
  */
  const double PM2 = P*massmol2_;
  const double RT = R_GAS*tempr_;
  const double mix = 1.0+Y1*(massmol2_/massmol1_-1.0);
  const double rh = PM2/(RT*mix);
  return rh;
}
virtual void Loi_Etat_Binaire_GP_base::calculer_masse_volumique () [pure virtual]
Calcule la masse volumique.
Reimplemented from Loi_Etat_GP_base.
Implemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
void Loi_Etat_Binaire_GP_base::calculer_mu () [virtual]
Calcule la viscosite dynamique.
Reimplemented from Loi_Etat_base.
Definition at line 120 of file Loi_Etat_Binaire_GP_base.cpp.
References calculer_mu_wilke(), Cerr, Process::exit(), finl, Loi_Etat_base::le_fluide, sub_type, and Deriv_Champ_Don_base::valeur().
{
  Champ_Don& mu = le_fluide->viscosite_dynamique();
  if (!sub_type(Champ_Uniforme,mu.valeur()))
    {
      if (sub_type(Champ_Fonc_Tabule,mu.valeur()))
        {
          Cerr << "We should not have a dynamic viscosity of type Champ_Fonc_Tabule !" << finl;
          Process::exit();
        }
      else
        calculer_mu_wilke();
    }
  else
    {
      Cerr << "We should not have a dynamic viscosity of type Champ_Uniforme !" << finl;
      Process::exit();
    }
}
void Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc () [virtual]
returns rho * D
Calcule la viscosite dynamique sur Schmidt.
Reimplemented from Loi_Etat_base.
Definition at line 159 of file Loi_Etat_Binaire_GP_base.cpp.
References Cerr, Champ_base::changer_temps(), diff_coeff_, DoubleVect::echange_espace_virtuel(), Process::exit(), finl, Loi_Etat_base::le_fluide, DoubleVect::size(), sub_type, Champ_base::temps(), Deriv_Champ_Don_base::valeur(), Champ_Proto::valeurs(), and Champ_Don::valeurs().
{
  /*
   * ====================================================================
   * Schmidt number : Sc = nu / D = mu / ( rho * D )
   * => rho * D = mu/Sc
   * species equation : div ( rho * D * grad Y1) = div ( mu/Sc * grad Y1)
   * ====================================================================
   */
  Champ_Don& mu_sur_Sc = le_fluide->mu_sur_Schmidt();
  const Champ_base& rho = le_fluide->masse_volumique();
  DoubleTab& tab_mu_sur_Sc = mu_sur_Sc.valeurs();
  const DoubleTab& tab_rho = rho.valeurs();
  const int n=tab_mu_sur_Sc.size();
  if (!sub_type(Champ_Uniforme,mu_sur_Sc.valeur()))
    {
      if (sub_type(Champ_Uniforme,rho))
        {
          Cerr << "We should not have a density field of type Champ_Uniforme !" << finl;
          Process::exit();
        }
      else
        for (int i=0 ; i<n ; i++) tab_mu_sur_Sc(i,0) = tab_rho(i,0)*diff_coeff_;
    }
  else
    {
      Cerr << "We should not have a mu_sur_Sc of type Champ_Uniforme !" << finl;
      Process::exit();
    }
  double temps_champ = rho.temps();
  mu_sur_Sc.valeur().changer_temps(temps_champ);
  tab_mu_sur_Sc.echange_espace_virtuel();
}
void Loi_Etat_Binaire_GP_base::calculer_mu_wilke ()
Calcule la viscosite dynamique de mélange (depend des fraction massique)
Voir Wilke https://aip.scitation.org/doi/pdf/10.1063/1.1747673.
< All about binary mixture !
Definition at line 74 of file Loi_Etat_Binaire_GP_base.cpp.
References DoubleVect::echange_espace_virtuel(), Loi_Etat_base::le_fluide, massmol1_, massmol2_, mu1_, mu2_, DoubleVect::size(), and verifier().
Referenced by calculer_mu().
{
  const DoubleTab& tab_Y1 = le_fluide->inco_chaleur().valeurs();
  DoubleTab& tab_mu = le_fluide->viscosite_dynamique().valeurs();
  int i, n=tab_mu.size();
  for (i=0 ; i<n ; i++)
    {
      double m1om2 = massmol1_/massmol2_;
      double m2om1 = 1./m1om2;
      double mu1omu2 = mu1_/mu2_;
      double mu2omu1 = 1./mu1omu2;
// XXX : Which is better ?
      double a1 = 1. + sqrt(mu1omu2) * pow(mu2omu1,0.25);
      double a2 = 1. + sqrt(mu2omu1) * pow(mu1omu2,0.25);
// double a1 = 1. + sqrt(mu1omu2) * exp(0.25*log(mu2omu1));
// double a2 = 1. + sqrt(mu2omu1) * exp(0.25*log(mu1omu2));
      double b1 = sqrt(8.*(1.+m1om2));
      double b2 = sqrt(8.*(1.+m2om1));
      double phi_12 = m1om2*a1*a1/b1;
      double phi_21 = m2om1*a2*a2/b2;
      double y1 = tab_Y1(i,0);
      double y2 = 1. - y1; //!< All about binary mixture !
      tab_mu(i,0) = (mu1_*y1)/(y1+y2*phi_12) + (mu2_*y2)/(y2+y1*phi_21);
    }
  tab_mu.echange_espace_virtuel();
  Debog::verifier("calculer_mu_wilke",tab_mu);
}
void Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc () [virtual]
returns D
Calcule la viscosite dynamique sur Schmidt.
Reimplemented from Loi_Etat_base.
Definition at line 210 of file Loi_Etat_Binaire_GP_base.cpp.
References Champ_base::changer_temps(), diff_coeff_, DoubleVect::echange_espace_virtuel(), Loi_Etat_base::le_fluide, DoubleVect::size(), Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
{
  /*
   * ====================================================================
   * Schmidt number : Sc = nu / D
   * => D = nu/Sc
   * ====================================================================
   */
  Champ_Don& nu_sur_Sc = le_fluide->nu_sur_Schmidt();
  DoubleTab& tab_nu_sur_Sc = nu_sur_Sc.valeurs();
  const int n=tab_nu_sur_Sc.size();
  for (int i=0 ; i<n ; i++) tab_nu_sur_Sc(i,0) = diff_coeff_;
  double temps_champ = le_fluide->masse_volumique().temps();
  nu_sur_Sc.valeur().changer_temps(temps_champ);
  tab_nu_sur_Sc.echange_espace_virtuel();
}
virtual int Loi_Etat_Binaire_GP_base::duplique () const [pure virtual]
Implements Loi_Etat_Melange_GP_base.
Implemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
const Type_info * Loi_Etat_Binaire_GP_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 30 of file Loi_Etat_Binaire_GP_base.cpp.
const Type_info * Loi_Etat_Binaire_GP_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 30 of file Loi_Etat_Binaire_GP_base.cpp.
double Loi_Etat_Binaire_GP_base::inverser_Pth (double Y1, double rho) [virtual]
Calcule la pression avec la temperature et la masse volumique.
Reimplemented from Loi_Etat_GP_base.
Definition at line 283 of file Loi_Etat_Binaire_GP_base.cpp.
References Process::abort(), Cerr, and finl.
{
  /*
  // THIS IS OK, but we dont want to enter here !
  double RToM2 = R_GAS*tempr_/massmol2_;
  double mix = 1.0+Y1*(massmol2_/massmol1_-1.0);
  double p_t = rho * RToM2 * mix ;
  return p_t;
  */
  Cerr << "We should not enter in the method Loi_Etat_Binaire_GP_base::inverser_Pth !" << finl;
  Cerr << "This means that you are trying to solve an ODE for pth which is forbidden for this EOS!" << finl;
  abort();
  throw;
}
Sortie & Loi_Etat_Binaire_GP_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 35 of file Loi_Etat_Binaire_GP_base.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Loi_Etat_Binaire_GP_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 41 of file Loi_Etat_Binaire_GP_base.cpp.
References Param::ajouter(), diff_coeff_, Param::lire_avec_accolades_depuis(), massmol1_, massmol2_, mu1_, mu2_, Objet_U::que_suis_je(), Param::REQUIRED, and tempr_.
{
  Param param(que_suis_je());
  param.ajouter("molar_mass1",&massmol1_,Param::REQUIRED);
  param.ajouter("molar_mass2",&massmol2_,Param::REQUIRED);
  param.ajouter("mu1",&mu1_,Param::REQUIRED);
  param.ajouter("mu2",&mu2_,Param::REQUIRED);
  param.ajouter("temperature",&tempr_,Param::REQUIRED);
  param.ajouter("diffusion_coeff",&diff_coeff_,Param::REQUIRED);
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Loi_Etat_Binaire_GP_base & Loi_Etat_Binaire_GP_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 30 of file Loi_Etat_Binaire_GP_base.cpp.
Loi_Etat_Binaire_GP_base & Loi_Etat_Binaire_GP_base::self_cast (Objet_U & r) [static]
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 30 of file Loi_Etat_Binaire_GP_base.cpp.
const Nom Loi_Etat_Binaire_GP_base::type_fluide () const [virtual]
Renvoie le type de fluide associe.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_GP_base.
Definition at line 264 of file Loi_Etat_Binaire_GP_base.cpp.
{
  return "Melange_Binaire";
}
Member Data Documentation
double Loi_Etat_Binaire_GP_base::diff_coeff_ [protected]
Definition at line 60 of file Loi_Etat_Binaire_GP_base.h.
Referenced by calculer_mu_sur_Sc(), calculer_nu_sur_Sc(), and readOn().
const Type_info Loi_Etat_Binaire_GP_base::info_obj [static]
Reimplemented from Loi_Etat_Melange_GP_base.
Reimplemented in Loi_Etat_Binaire_GP_QC, and Loi_Etat_Binaire_GP_WC.
Definition at line 43 of file Loi_Etat_Binaire_GP_base.h.
double Loi_Etat_Binaire_GP_base::massmol1_ [protected]
Definition at line 60 of file Loi_Etat_Binaire_GP_base.h.
Referenced by calculer_masse_volumique(), calculer_mu_wilke(), and readOn().
double Loi_Etat_Binaire_GP_base::massmol2_ [protected]
Definition at line 60 of file Loi_Etat_Binaire_GP_base.h.
Referenced by calculer_masse_volumique(), calculer_mu_wilke(), and readOn().
double Loi_Etat_Binaire_GP_base::mu1_ [protected]
Definition at line 60 of file Loi_Etat_Binaire_GP_base.h.
Referenced by calculer_mu_wilke(), and readOn().
double Loi_Etat_Binaire_GP_base::mu2_ [protected]
Definition at line 60 of file Loi_Etat_Binaire_GP_base.h.
Referenced by calculer_mu_wilke(), and readOn().
double Loi_Etat_Binaire_GP_base::tempr_ [protected]
Definition at line 60 of file Loi_Etat_Binaire_GP_base.h.
Referenced by calculer_masse_volumique(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Binaire_GP_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Binaire_GP_base.cpp