TRUST: Champ_Fonc_P1_MED Class Reference
Champ_Fonc_P1_MED Class Reference
classe Champ_Fonc_P1_MED
permet de faire un champ P1 pour le post med
#include <Champ_Fonc_P1_MED.h>
Public Member Functions
Champ_Fonc_P1_MED ()
~Champ_Fonc_P1_MED ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
const Zone_dis_base & zone_dis_base () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_P1_MED & self_cast (Objet_U &)
static const Champ_Fonc_P1_MED & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type et le nom du Champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN.
Private Attributes
Ref_Zone_dis_base zonebidon
Detailed Description
classe Champ_Fonc_P1_MED
permet de faire un champ P1 pour le post med
Definition at line 38 of file Champ_Fonc_P1_MED.h.
Constructor & Destructor Documentation
Champ_Fonc_P1_MED::Champ_Fonc_P1_MED ()
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
Champ_Fonc_P1_MED::~Champ_Fonc_P1_MED ()
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
Member Function Documentation
void Champ_Fonc_P1_MED::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) [virtual]
Implements Champ_Fonc_base.
Definition at line 74 of file Champ_Fonc_P1_MED.cpp.
References zonebidon.
{
  zonebidon=la_zone_dis_base;
}
Objet_U * Champ_Fonc_P1_MED::cree_instance () [static]
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
int Champ_Fonc_P1_MED::duplique () const [virtual]
Implements Champ_Fonc_P1_base.
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
const Type_info * Champ_Fonc_P1_MED::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
const Type_info * Champ_Fonc_P1_MED::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
void Champ_Fonc_P1_MED::mettre_a_jour (double temps) [virtual]
Mise a jour en temps du champ.
Implements Champ_Fonc_base.
Definition at line 65 of file Champ_Fonc_P1_MED.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Champ_Fonc_P1_MED::mettre_a_jour must be overloaded"<<finl;
  exit();
}
Sortie & Champ_Fonc_P1_MED::printOn (Sortie & s) const [protected, virtual]
Ecrit le type et le nom du Champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 41 of file Champ_Fonc_P1_MED.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Champ_Fonc_P1_MED::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Champ_Fonc_P1_base.
Definition at line 61 of file Champ_Fonc_P1_MED.cpp.
{
  return s ;
}
Champ_Fonc_P1_MED & Champ_Fonc_P1_MED::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P1_base.
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
const Champ_Fonc_P1_MED & Champ_Fonc_P1_MED::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P1_base.
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
unsigned Champ_Fonc_P1_MED::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 24 of file Champ_Fonc_P1_MED.cpp.
const Zone_dis_base & Champ_Fonc_P1_MED::zone_dis_base () const [virtual]
Implements Champ_Fonc_base.
Definition at line 70 of file Champ_Fonc_P1_MED.cpp.
References Ref_Zone_dis_base::valeur(), and zonebidon.
{
  return zonebidon.valeur();
}
Member Data Documentation
const Type_info Champ_Fonc_P1_MED::info_obj [static]
Reimplemented from Champ_Fonc_P1_base.
Definition at line 40 of file Champ_Fonc_P1_MED.h.
Ref_Zone_dis_base Champ_Fonc_P1_MED::zonebidon [private]
Definition at line 47 of file Champ_Fonc_P1_MED.h.
Referenced by associer_zone_dis_base(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Champ_Fonc_P1_MED.h
src/Kernel/MEDimpl/Champ_Fonc_P1_MED.cpp