TRUST: Champ_front Class Reference
Champ_front Class Reference
classe Champ_front
Classe generique de la hierarchie des champs aux frontieres,
un objet Champ_front peut referencer n'importe quel objet derivant de
Champ_front_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Champ_front.h>
Public Member Functions
Champ_front ()
~Champ_front ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front (const Champ_front &)=default
Champ_front & operator= (const Champ_front_base &ch_base)
Operateur d'affectation d'un Champ_front_base dans un
Champ_front.
Champ_front & operator= (const Champ_front &ch_base)
Operateur d'affectation d'un Champ_front_base dans un
Champ_front.
void nommer (const Nom &name) override
Appel a l'objet sous-jacent
Donne un nom au champ.
const Nom & le_nom () const override
Appel a l'objet sous-jacent
Renvoie le nom du champ.
void associer_fr_dis_base (const Frontiere_dis_base &)
Appel a l'objet sous-jacent
Associe une frontiere discretisee au champ.
const Frontiere_dis_base & frontiere_dis () const
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee au champ<br>(version const)
Frontiere_dis_base & frontiere_dis ()
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee au champ.
int nb_comp () const
Appel a l'objet sous-jacent
Renvoie le nombre de composantes du champ.
void mettre_a_jour (double temps)
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
void calculer_coeffs_echange (double temps)
Calcul (si necessaire) les coefficients d'echange pour
un couplage.
DoubleTab & valeurs () override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ<br>(version const)
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Deriv_Champ_front_base
~Deriv_Champ_front_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_front_base ()
Deriv_Champ_front_base (const Deriv_Champ_front_base &)
const Champ_front_base & valeur () const
Champ_front_base & valeur ()
const Champ_front_base * operator-> () const
Champ_front_base * operator-> ()
const Deriv_Champ_front_base & operator= (const Champ_front_base &)
const Deriv_Champ_front_base & operator= (const Deriv_Champ_front_base &)
operator const Champ_front_base & () const
operator Champ_front_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_front & self_cast (Objet_U &)
static const Champ_front & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Champ_front_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_front_base & self_cast (Objet_U &)
static const Deriv_Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lit le champ a partir d'un flot d'entree.
Protected Member Functions inherited from Deriv_Champ_front_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Champ_front
Classe generique de la hierarchie des champs aux frontieres,
un objet Champ_front peut referencer n'importe quel objet derivant de
Champ_front_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 39 of file Champ_front.h.
Constructor & Destructor Documentation
Champ_front() [1/2]
Champ_front::Champ_front ()
Definition at line 19 of file Champ_front.cpp.
~Champ_front()
Champ_front::~Champ_front ()
Definition at line 19 of file Champ_front.cpp.
Champ_front() [2/2]
Champ_front::Champ_front (const Champ_front &) default
Member Function Documentation
add_synonymous()
void Champ_front::add_synonymous (const Nom & nom) inline
Definition at line 348 of file Champ_front.h.
{
  valeur().add_synonymous(nom);
}
References Field_base::add_synonymous(), and Deriv_Champ_front_base::valeur().
associer_fr_dis_base()
void Champ_front::associer_fr_dis_base (const Frontiere_dis_base & fr) inline
Appel a l'objet sous-jacent
Associe une frontiere discretisee au champ.
Definition at line 232 of file Champ_front.h.
{
  valeur().associer_fr_dis_base(fr);
}
References Champ_front_base::associer_fr_dis_base(), and Deriv_Champ_front_base::valeur().
Referenced by Cond_lim_base::associer_fr_dis_base(), Neumann_sortie_libre::associer_fr_dis_base(), Paroi_Knudsen_non_negligeable::completer(), Echange_couplage_thermique::completer(), Echange_global_impose::completer(), and Echange_contact_VDF::completer().
calculer_coeffs_echange()
void Champ_front::calculer_coeffs_echange (double temps) inline
Calcul (si necessaire) les coefficients d'echange pour
un couplage.
Definition at line 295 of file Champ_front.h.
{
  valeur().calculer_coeffs_echange(temps);
}
References Champ_front_base::calculer_coeffs_echange(), and Deriv_Champ_front_base::valeur().
Referenced by Cond_lim_base::calculer_coeffs_echange().
cree_instance()
Objet_U * Champ_front::cree_instance () static
Definition at line 19 of file Champ_front.cpp.
duplique()
int Champ_front::duplique () const override virtual
Reimplemented from Deriv_Champ_front_base.
Definition at line 19 of file Champ_front.cpp.
frontiere_dis() [1/2]
Frontiere_dis_base & Champ_front::frontiere_dis () inline
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee au champ.
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee associee au champ
Contraintes:
Definition at line 211 of file Champ_front.h.
{
  return valeur().frontiere_dis();
}
References Champ_front_base::frontiere_dis(), and Deriv_Champ_front_base::valeur().
frontiere_dis() [2/2]
const Frontiere_dis_base & Champ_front::frontiere_dis () const inline
Appel a l'objet sous-jacent
Renvoie la frontiere discretisee associee au champ<br>(version const)
Returns
Frontiere_dis_base&
Signification: la frontiere discretisee associee au champ
Contraintes: reference constante
Definition at line 190 of file Champ_front.h.
{
  return valeur().frontiere_dis();
}
References Champ_front_base::frontiere_dis(), and Deriv_Champ_front_base::valeur().
Referenced by Paroi_Knudsen_non_negligeable::completer(), Cond_lim_base::frontiere_dis(), and Frontiere_ouverte_rho_u_impose::val_imp_au_temps().
get_info()
const Type_info * Champ_front::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Champ_front_base.
Definition at line 19 of file Champ_front.cpp.
get_synonyms()
const Noms & Champ_front::get_synonyms () const inline
Definition at line 343 of file Champ_front.h.
{
  return valeur().get_synonyms();
}
References Field_base::get_synonyms(), and Deriv_Champ_front_base::valeur().
info()
const Type_info * Champ_front::info () static
Definition at line 19 of file Champ_front.cpp.
le_nom()
const Nom & Champ_front::le_nom () const inline override virtual
Appel a l'objet sous-jacent
Renvoie le nom du champ.
Returns
Nom&
Signification: le nom du champ
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 168 of file Champ_front.h.
{
  return valeur().le_nom();
}
References Field_base::le_nom(), and Deriv_Champ_front_base::valeur().
mettre_a_jour()
void Champ_front::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent
Effectue une mise a jour en temps.
Definition at line 274 of file Champ_front.h.
{
  valeur().mettre_a_jour(temps);
}
References Champ_front_base::mettre_a_jour(), and Deriv_Champ_front_base::valeur().
Referenced by Echange_impose_base::initialiser(), Cond_lim_base::mettre_a_jour(), Neumann_paroi::mettre_a_jour(), Neumann_sortie_libre::mettre_a_jour(), Echange_couplage_thermique::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Echange_impose_base::mettre_a_jour(), and Echange_contact_VDF::mettre_a_jour().
nb_comp()
int Champ_front::nb_comp () const inline
Appel a l'objet sous-jacent
Renvoie le nombre de composantes du champ.
Returns
int
Signification: le nombre de composantes du champ
Contraintes:
Definition at line 253 of file Champ_front.h.
{
  return valeur().nb_comp();
}
References Field_base::nb_comp(), and Deriv_Champ_front_base::valeur().
Referenced by Champ_front_xyz_debit::calculer_champ_vitesse(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Champ_front_xyz_debit::initialiser_coefficient(), Champ_front_debit::readOn(), and Champ_front_xyz_debit::readOn().
nommer()
void Champ_front::nommer (const Nom & name) inline override virtual
Appel a l'objet sous-jacent
Donne un nom au champ.
Reimplemented from Objet_U.
Definition at line 147 of file Champ_front.h.
{
  valeur().nommer(name) ;
}
References Field_base::nommer(), and Deriv_Champ_front_base::valeur().
operator=() [1/2]
Champ_front & Champ_front::operator= (const Champ_front & ch_front) inline
Operateur d'affectation d'un Champ_front_base dans un
Champ_front.
Returns
Champ_front&
Signification: le resultat de l'affectation
Contraintes:
Definition at line 126 of file Champ_front.h.
{
  DERIV(Champ_front_base)::operator=(ch_front.valeur());
  return *this;
}
References DERIV, operator=(), and Deriv_Champ_front_base::valeur().
operator=() [2/2]
Champ_front & Champ_front::operator= (const Champ_front_base & ch_base) inline
Operateur d'affectation d'un Champ_front_base dans un
Champ_front.
Returns
Champ_front&
Signification: le resultat de l'affectation
Contraintes:
Definition at line 104 of file Champ_front.h.
{
  DERIV(Champ_front_base)::operator=(ch_base);
  return *this;
}
References DERIV, and operator=().
Referenced by operator=().
printOn()
Sortie & Champ_front::printOn (Sortie & s) const override protected virtual
Imprime le champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Champ_front_base.
Definition at line 36 of file Champ_front.cpp.
{
  return DERIV(Champ_front_base)::printOn(s) ;
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Champ_front::readOn (Entree & s) override protected virtual
Lit le champ a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Champ_front_base.
Definition at line 57 of file Champ_front.cpp.
{
  return DERIV(Champ_front_base)::readOn(s) ;
}
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Champ_front & Champ_front::self_cast (const Objet_U & r) static
Definition at line 19 of file Champ_front.cpp.
self_cast() [2/2]
Champ_front & Champ_front::self_cast (Objet_U & r) static
Definition at line 19 of file Champ_front.cpp.
taille_memoire()
unsigned Champ_front::taille_memoire () const override virtual
Reimplemented from Deriv_Champ_front_base.
Definition at line 19 of file Champ_front.cpp.
valeurs() [1/6]
const DoubleTab & Champ_front::valeurs () const inline override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ<br>(version const)
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes: reference constante
Implements Champ_Proto.
Definition at line 338 of file Champ_front.h.
{
  return valeur().valeurs();
}
References Deriv_Champ_front_base::valeur(), and Champ_front_base::valeurs().
valeurs() [2/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Implements Champ_Proto.
valeurs() [3/6]
DoubleTab & Champ_front::valeurs () inline override virtual
Appel a l'objet sous-jacent
Renvoie le tableau des valeurs du champ.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ
Contraintes:
Implements Champ_Proto.
Definition at line 316 of file Champ_front.h.
{
  return valeur().valeurs();
}
References Deriv_Champ_front_base::valeur(), and Champ_front_base::valeurs().
Referenced by Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Sortie_libre_pression_moyenne_imposee::completer(), Echange_contact_Correlation_VDF::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Neumann::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Neumann_paroi::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_Text_H_ext::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Sortie_libre_Pression_imposee_Orlansky::flux_impose(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), Champ_Generique_Extraction::get_champ(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Echange_impose_base::h_imp(), Echange_couplage_thermique::initialiser(), Echange_global_impose::initialiser(), Echange_contact_VDF::initialiser(), Paroi_Knudsen_non_negligeable::k(), Echange_interne_impose::mettre_a_jour(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), PlaqThVDF::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::readOn(), Sortie_libre_pression_imposee_QC::readOn(), Sortie_libre_pression_imposee::readOn(), Sortie_libre_pression_moyenne_imposee::readOn(), Sortie_libre_Gradient_Pression_impose::readOn(), Sortie_libre_Pression_imposee_Orlansky::readOn(), Sortie_libre_Gradient_Pression_impose_VEF::readOn(), Sortie_libre_Gradient_Pression_libre_VEF::readOn(), Echange_impose_base::T_ext(), Echange_externe_impose_H::T_ext(), Neumann_sortie_libre::tab_ext(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre_Temp_H::val_ext(), Neumann_sortie_libre::val_ext(), Entree_fluide_temperature_imposee_H::val_imp(), Temperature_imposee_paroi_H::val_imp(), Entree_fluide_T_h_imposee::val_imp(), and Paroi_Knudsen_non_negligeable::vitesse_paroi().
valeurs() [4/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_Proto.
Definition at line 50 of file Champ_Proto.h.
{ return valeurs(); }
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_Proto.
Definition at line 51 of file Champ_Proto.h.
{ return valeurs(); }
Member Data Documentation
info_obj
const Type_info Champ_front::info_obj static
Definition at line 42 of file Champ_front.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_front.h
src/Kernel/Framework/Champ_front.cpp