TRUST: SupprimeBord Class Reference
SupprimeBord Class Reference
#include <SupprimeBord.h>
Public Member Functions
SupprimeBord ()
~SupprimeBord ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static SupprimeBord & self_cast (Objet_U &)
static const SupprimeBord & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 41 of file SupprimeBord.h.
Constructor & Destructor Documentation
SupprimeBord::SupprimeBord ()
Definition at line 25 of file SupprimeBord.cpp.
SupprimeBord::~SupprimeBord ()
Definition at line 25 of file SupprimeBord.cpp.
Member Function Documentation
Objet_U * SupprimeBord::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 25 of file SupprimeBord.cpp.
int SupprimeBord::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 25 of file SupprimeBord.cpp.
const Type_info * SupprimeBord::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file SupprimeBord.cpp.
const Type_info * SupprimeBord::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file SupprimeBord.cpp.
Entree & SupprimeBord::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 37 of file SupprimeBord.cpp.
References Interprete_geometrique_base::associer_domaine(), Zone::bord(), Cerr, Cout, Interprete_geometrique_base::domaine(), Process::exit(), Zone::faces_bord(), Zone::faces_raccord(), finl, LIST, Zone::raccord(), Zone::rang_frontiere(), liste::size(), List_Raccord::suppr(), List_Bord::suppr(), and Domaine::zone().
{
  Nom nom_dom;
  LIST(Nom) nlistbord;
  associer_domaine(is);
  Nom mot;
  is >>mot;
  if (mot!="{")
    {
      Cerr<< "we expected { and not "<<mot<<finl;
      exit();
    }
  is >>mot;
  while (mot!="}")
    {
      nlistbord.add(mot);
      is>>mot;
    }
  Domaine& dom=domaine();
  Cout<<"HERE  "<<nlistbord<<finl;
  Zone& zone=dom.zone(0);
  for (int b=0; b<nlistbord.size(); b++)
    {
      {
// la recup des bords et des raccords est dans la boucle
// pour pouvoir supprimer ...
        Bords& listbord=zone.faces_bord();
        Raccords& listrac=zone.faces_raccord();
        const Nom& nombord=nlistbord[b];
        int num_b=zone.rang_frontiere(nombord);
        if (num_b<listbord.size())
          listbord.suppr(zone.bord(nombord));
        else
          listrac.suppr(zone.raccord(nombord));
      }
    }
  return is;
}
Sortie & SupprimeBord::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 27 of file SupprimeBord.cpp.
{
  return Interprete::printOn(os);
}
Entree & SupprimeBord::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 32 of file SupprimeBord.cpp.
{
  return Interprete::readOn(is);
}
SupprimeBord & SupprimeBord::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file SupprimeBord.cpp.
const SupprimeBord & SupprimeBord::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file SupprimeBord.cpp.
unsigned SupprimeBord::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file SupprimeBord.cpp.
Member Data Documentation
const Type_info SupprimeBord::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 43 of file SupprimeBord.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/SupprimeBord.h
src/Kernel/Geometrie/SupprimeBord.cpp