TRUST: Operateur_base Class Reference
Operateur_base Class Reference
classe Operateur_base
Classe est la base de la hierarchie des objets representant un
operateur utilise dans des equations de TRUST. Ses membres sont
les attributs et les methodes communs a toutes les classes qui
representent un operateur. Un Operateur est un morceau d'equation
c'est pourquoi il derive de MorEqn qui lui permet d'avoir une
reference sur l'equation auquel il est attache.
Exemple de classe d'operateur: Op_Diff_K_Eps_negligeable,
Operateur_Div_base
#include <Operateur_base.h>
Public Member Functions
Operateur_base ()
~Operateur_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
void ouvrir_fichier (SFichier &os, const Nom &, const int &flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int &flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
virtual void creer_champ (const Motcle &motlu)
virtual const Champ_base & get_champ (const Motcle &nom) const
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
int col_width_
minimal size of a column for .out files (based on cl name length)
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Attributes
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Detailed Description
classe Operateur_base
Classe est la base de la hierarchie des objets representant un
operateur utilise dans des equations de TRUST. Ses membres sont
les attributs et les methodes communs a toutes les classes qui
representent un operateur. Un Operateur est un morceau d'equation
c'est pourquoi il derive de MorEqn qui lui permet d'avoir une
reference sur l'equation auquel il est attache.
Exemple de classe d'operateur: Op_Diff_K_Eps_negligeable,
Operateur_Div_base
Definition at line 63 of file Operateur_base.h.
Constructor & Destructor Documentation
Operateur_base::Operateur_base ()
Definition at line 37 of file Operateur_base.cpp.
References col_width_, decal_temps, and nb_ss_pas_de_temps.
{
  decal_temps=0;
  nb_ss_pas_de_temps=1;
  col_width_ = -1;
}
Operateur_base::~Operateur_base ()
Definition at line 35 of file Operateur_base.cpp.
Member Function Documentation
void Operateur_base::abortTimeStep () [virtual]
Reimplemented in Op_Conv_EF_base, and Op_Conv_VEF_base.
Definition at line 109 of file Operateur_base.cpp.
Referenced by Equation_base::abortTimeStep().
{
}
DoubleTab & Operateur_base::ajouter (const DoubleTab & inco, DoubleTab & secmem) const [virtual]
Reimplemented in Op_Div_CoviMAC, Op_Conv_EF, Op_Diff_EF, Op_Div_EF, Op_Grad_EF, Op_Diff_negligeable, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Dift_Stab_VEF_Face, Op_Dift_standard_VEF_Face, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, and Op_Grad_VEF_Face.
Definition at line 302 of file Operateur_base.cpp.
References ajouter_blocs(), Process::exit(), has_interface_blocs(), and Objet_U::que_suis_je().
Referenced by Operateur_Evanescence::ajouter(), Operateur_Div::ajouter(), Operateur_Diff::ajouter(), Operateur_Conv::ajouter(), ajouter_contribution_explicite_au_second_membre(), Op_Conv_VEF_base::calculer(), Op_Diff_PolyMAC_base::calculer(), Op_Conv_PolyMAC_base::calculer(), calculer(), Op_Conv_EF_base::calculer(), Op_Diff_CoviMAC_base::calculer(), Op_Conv_CoviMAC_base::calculer(), Champ_Post_Operateur_Eqn::get_champ(), Op_Conv_VEF_base::remplir_fluent(), and Op_Conv_EF_base::remplir_fluent().
{
  /* on tente ajouter_blocs */
  if (has_interface_blocs()) ajouter_blocs({}, secmem);
  else Process::exit(que_suis_je() + " : ajouter() not coded!");
  return secmem;
}
virtual void Operateur_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Diff_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Grad_CoviMAC_Face, Op_Conv_negligeable, Op_Diff_negligeable, Op_Evanescence_Homogene_CoviMAC_Elem, and Op_Evanescence_Homogene_CoviMAC_Face.
Referenced by Operateur_Grad_base::ajouter(), ajouter(), Navier_Stokes_std::assembler_blocs(), Operateur_Grad_base::contribuer_a_avec(), contribuer_a_avec(), contribuer_bloc_vitesse(), and contribuer_termes_croises().
void Operateur_base::ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base & inconnue, DoubleTab & derivee) const [virtual]
Definition at line 555 of file Operateur_base.cpp.
References ajouter(), and Champ_Inc_base::valeurs().
Referenced by Operateur::ajouter_contribution_explicite_au_second_membre().
{
// Methode par defaut pour les operateurs de TRUST:
  ajouter(inconnue.valeurs(), derivee);
}
void Operateur_base::ajouter_flux (const DoubleTab & inconnue, DoubleTab & contribution) const [virtual]
Reimplemented in Op_Conv_negligeable, and Op_Diff_negligeable.
Definition at line 643 of file Operateur_base.cpp.
References Cerr, Process::exit(), and finl.
Referenced by calculer_flux().
{
  Cerr << "Warning : 'Operateur_base::ajouter_flux()' must be overloaded" << finl;
  Process::exit();
}
void Operateur_base::ajouter_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, DoubleTab & resu) const [virtual]
Reimplemented in Op_Diff_PolyMAC_Elem.
Definition at line 246 of file Operateur_base.cpp.
Referenced by Equation_base::ajouter_termes_croises().
{
// si on a Interface_blocs, alors ajouter_blocs() est suffisant
  return;
}
virtual void Operateur_base::associer (const Zone_dis & , const Zone_Cl_dis & , const Champ_Inc & inco) [pure virtual]
Implemented in Op_Conv_CoviMAC_base, Op_Diff_CoviMAC_base, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF_base, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_P1NCP1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_Face, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Centre_old_VEF_Face, Op_Conv_kschemas_VEF, Op_Conv_VEF_base, Op_Diff_VEF_base, Op_Dift_VEF_base, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, and Op_Grad_VEF_Face.
Referenced by Op_Conv_ALE::associer(), and completer().
void Operateur_base::associer_champ (const Champ_Inc & ch) [virtual]
Definition at line 158 of file Operateur_base.cpp.
References le_champ_inco.
Referenced by Operateur::associer_champ().
{
  le_champ_inco = ch;
}
void Operateur_base::associer_eqn (const Equation_base & eqn) [inline]
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
Reimplemented from MorEqn.
Definition at line 190 of file Operateur_base.h.
Referenced by Convection_Diffusion_Chaleur_WC::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Divergence::completer(), Navier_Stokes_std::discretiser(), and Operateur::lire().
{
  MorEqn::associer_eqn(eqn);
}
void Operateur_base::associer_zone_cl_dis (const Zone_Cl_dis_base &) [virtual]
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_base, Op_Conv_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Conv_VDF_base, and Op_Conv_VEF_base.
Definition at line 380 of file Operateur_base.cpp.
References Cerr, Process::exit(), and finl.
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter(), Convection_Diffusion_Espece_Multi_QC::assembler(), and Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco().
{
  Cerr<<"Operateur_base::associer_zone_cl_dis must be overloaded "<<finl;
  exit();
}
DoubleTab & Operateur_base::calculer (const DoubleTab & inco, DoubleTab & secmem) const [virtual]
Reimplemented in Op_Conv_CoviMAC_base, Op_Diff_CoviMAC_base, Op_Div_CoviMAC, Op_Conv_EF_base, Op_Diff_EF, Op_Div_EF, Op_Grad_EF, Op_Diff_negligeable, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_P1NCP1B_Face, Op_Rot_VEFP1B, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_VEF_base, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, and Op_Grad_VEF_Face.
Definition at line 310 of file Operateur_base.cpp.
References ajouter().
Referenced by Operateur_Evanescence::calculer(), Operateur_Grad::calculer(), Operateur_Div::calculer(), Operateur_Diff::calculer(), Operateur_Conv::calculer(), Piso::iterer_NS(), Operateur_Grad_base::multvect(), Operateur_Div_base::multvect(), and tester_contribuer_a_avec().
{
  secmem = 0;
  return ajouter(inco, secmem);
}
void Operateur_base::calculer_dt_local (DoubleTab & dt) const [virtual]
Reimplemented in Op_Conv_VDF_base, and Op_Conv_VEF_base.
Definition at line 182 of file Operateur_base.cpp.
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Operateur::calculer_pas_de_temps_locaux().
{
  Cerr << "You must overload the method " << que_suis_je()
       << "::calculer_dt_local(DoubleVect&)" << finl;
  exit();
}
double Operateur_base::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Diff_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Conv_EF, Op_Conv_EF_base, Op_Diff_EF_base, Op_Diff_P1NC_barprim, Op_Diff_VEFP1NCP1B_Face, Op_Dift_VEF_P1NCP1B_Face, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Conv_VDF_base, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_base, Op_Diff_VEF_base, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 177 of file Operateur_base.cpp.
Referenced by Operateur::calculer_pas_de_temps(), and Op_Diff_negligeable::calculer_pour_post().
{
  return 1.e30;
}
void Operateur_base::calculer_flux (const DoubleTab & inconnue, DoubleTab & flux) const [virtual]
Reimplemented in Op_Conv_negligeable, and Op_Diff_negligeable.
Definition at line 649 of file Operateur_base.cpp.
References ajouter_flux().
{
  flux = 0.;
  ajouter_flux(inconnue,flux);
}
void Operateur_base::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const [virtual]
Reimplemented from MorEqn.
Reimplemented in Op_Conv_EF_base, Op_Diff_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Conv_VEF_base, Op_Diff_VEF_base, and Op_Dift_VEF_Face.
Definition at line 587 of file Operateur_base.cpp.
References Faces::calculer_surfaces(), Cerr, MorEqn::equation(), Process::exit(), Frontiere::faces(), finl, flux_bords_, Frontiere_dis_base::frontiere(), Cond_lim::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), DoubleTab::nb_dim(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), ref_cast, Deriv_Zone_dis_base::valeur(), Champ::valeurs(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
{
  if (Motcle(option)=="flux_bords" || Motcle(option)=="flux_surfacique_bords")
    {
      bool surfacique = (Motcle(option)=="flux_surfacique_bords");
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      es_valeurs = 0.;
      const Zone_Cl_dis_base& zcl_dis = equation().zone_Cl_dis();
      const Zone_dis_base& zdis = equation().zone_dis().valeur();
      int nb_front = zdis.nb_front_Cl();
      if (flux_bords_.nb_dim()==2)
        {
          DoubleVect aire;
          for (int n_bord=0; n_bord<nb_front; n_bord++)
            {
              const Cond_lim& la_cl = zcl_dis.les_conditions_limites(n_bord);
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              if (surfacique) la_cl.frontiere_dis().frontiere().faces().calculer_surfaces(aire);
              int ndeb = le_bord.num_premiere_face();
              int nfin = ndeb + le_bord.nb_faces();
              for (int face=ndeb; face<nfin; face++)
                es_valeurs(face) = flux_bords_(face,comp) / (surfacique ? aire(face-ndeb) : 1.);
            }
        }
    }
  else
    {
      Cerr<<"The method calculer_pour_post is not recognized for the option "<<option<<finl;
      exit();
    }
}
void Operateur_base::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Diff_EF, Op_Diff_P1NC_barprim, Op_Diff_VEFP1NCP1B_Face, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Grad_VDF_base, Op_Diff_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Dift_Stab_VEF_Face, and Op_Dift_VEF_base.
Definition at line 129 of file Operateur_base.cpp.
References associer(), col_width_, MorEqn::equation(), Nom::getSuffix(), le_champ_inco, Frontiere_dis_base::le_nom(), Zone_Cl_dis::les_conditions_limites(), Nom::longueur(), max(), MorEqn::mon_equation, O_U_Ptr::non_nul(), vect_impl::size(), and Ref_Champ_Inc::valeur().
Referenced by Operateur::completer().
{
  assert(mon_equation.non_nul());
  const Equation_base& eqn = equation();
  const Zone_dis& zdis= eqn.zone_dis();
  const Zone_Cl_dis& zcl = le_champ_inco.non_nul() ? le_champ_inco.valeur()->zone_Cl_dis() : eqn.zone_Cl_dis();
  const Champ_Inc& inco = le_champ_inco.non_nul() ? le_champ_inco.valeur() : eqn.inconnue();
  associer(zdis, zcl, inco);
  const Conds_lim& les_cl = zcl->les_conditions_limites();
  for (int i = 0; i < les_cl.size(); i++)
    {
      const Frontiere_dis_base& la_fr = les_cl[i].frontiere_dis();
      col_width_ = max(col_width_, la_fr.le_nom().longueur());
    }
  int w_suffix = 3; //!< pour ajout _Mx (moment)
// pour les champs a plusieurs composantes, le header des colonnes des fichiers .out prend la forme
// Time cl1_compo1  cl1_compo2 ...
// on prend en compte la longueur de compo1, compo2, etc...
  Noms noms_compo_courts(inco->noms_compo());
  if (noms_compo_courts.size() > 1) for (int i = 0; i < noms_compo_courts.size(); ++i)
      {
        noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getSuffix(eqn.inconnue().le_nom());
        w_suffix = max(w_suffix, noms_compo_courts[i].longueur());
      }
  col_width_ += w_suffix;
}
void Operateur_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented in Op_Div_CoviMAC, Op_Conv_EF, Op_Diff_EF, Op_Diff_negligeable, Operateur_Grad_base, Op_Diff_P1NC_barprim, Op_Diff_VEFP1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Dift_Stab_VEF_Face, Op_Dift_VEF_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 336 of file Operateur_base.cpp.
References ajouter_blocs(), MorEqn::equation(), Process::exit(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Equation_base::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), construire_matrice_implicite(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Equation_base::Gradient_conjugue_diff_impl(), Solveur_U_P::iterer_NS(), and tester_contribuer_a_avec().
{
  /* on tente ajouter_blocs() */
  DoubleTrav secmem(inco); //on va le jeter
  if (has_interface_blocs()) ajouter_blocs({{ equation().inconnue().le_nom().getString(), &matrice }}, secmem);
  else Process::exit(que_suis_je() + " : contribuer_a_avec() not coded!");
}
void Operateur_base::contribuer_au_second_membre (DoubleTab &) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented in Op_Conv_EF, Op_Diff_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Diff_P1NC_barprim, Op_Diff_VEFP1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Conv_VDF_base, Op_Diff_VDF_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 369 of file Operateur_base.cpp.
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Equation_base::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), and tester_contribuer_a_avec().
{
  Cerr << "You must overload the method " << que_suis_je()
       << "::contribuer_au_second_membre(DoubleTab&)" << finl;
  exit();
}
void Operateur_base::contribuer_bloc_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [virtual]
Reimplemented in Op_Conv_PolyMAC_iterateur_base, and Op_Conv_VDF_base.
Definition at line 344 of file Operateur_base.cpp.
References ajouter_blocs(), MorEqn::equation(), and has_interface_blocs().
{
  /* on tente ajouter_blocs() */
  if (has_interface_blocs())
    {
      DoubleTrav secmem(equation().inconnue().valeurs()); //on va le jeter
      ajouter_blocs({{ "vitesse", &matrice }}, secmem);
    }
}
void Operateur_base::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const [virtual]
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_VDF_Elem_base.
Definition at line 252 of file Operateur_base.cpp.
References ajouter_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), and Equation_base::probleme().
Referenced by Equation_base::contribuer_termes_croises().
{
  if (!has_interface_blocs()) return;
  DoubleTrav secmem(inco); //on va le jeter
  std::string nom_inco = equation().inconnue().le_nom().getString(),
              nom = equation().probleme().le_nom() == autre_pb.le_nom() ? nom_inco : nom_inco + "_" + autre_pb.le_nom().getString(); //nom de bloc croise pour l'interface_blocs
  ajouter_blocs({{ nom, &matrice}}, secmem, {});
}
void Operateur_base::creer_champ (const Motcle & motlu) [virtual]
Implements Champs_compris_interface.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem.
Definition at line 562 of file Operateur_base.cpp.
Referenced by Equation_base::creer_champ().
{
}
const Nom Operateur_base::description () const [inline]
Definition at line 126 of file Operateur_base.h.
References description_.
Referenced by ouvrir_fichier().
  {
    return description_;
  };
void Operateur_base::dimensionner (Matrice_Morse & mat) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented in Op_Div_CoviMAC, Op_Conv_EF, Op_Diff_EF, Op_Diff_negligeable, Operateur_Grad_base, Op_Diff_P1NC_barprim, Op_Diff_VEFP1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Grad_VDF_Face, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 225 of file Operateur_base.cpp.
References dimensionner_blocs(), MorEqn::equation(), Process::exit(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), O_U_Ptr::le_nom(), and Objet_U::que_suis_je().
Referenced by construire_matrice_implicite(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), QDM_Multiphase::dimensionner_matrice_sans_mem(), Masse_Multiphase::dimensionner_matrice_sans_mem(), Energie_Multiphase::dimensionner_matrice_sans_mem(), Equation_base::dimensionner_matrice_sans_mem(), and Solveur_U_P::iterer_NS().
{
  /* on tente dimensionner_blocs() */
  if (has_interface_blocs()) dimensionner_blocs({{ equation().inconnue().le_nom().getString(), &mat }});
  else Process::exit(que_suis_je() + " : dimensionner() not coded!");
}
void Operateur_base::dimensionner_bloc_vitesse (Matrice_Morse & matrice) const [virtual]
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_Amont_VDF_Elem, and Op_Conv_centre_VDF_Elem.
Definition at line 232 of file Operateur_base.cpp.
References dimensionner_blocs(), and has_interface_blocs().
{
  /* on tente dimensionner_blocs() */
  if (has_interface_blocs()) dimensionner_blocs({{ "vitesse", &mat }});
}
virtual void Operateur_base::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Diff_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Grad_CoviMAC_Face, Op_Conv_negligeable, Op_Diff_negligeable, Op_Evanescence_Homogene_CoviMAC_Elem, and Op_Evanescence_Homogene_CoviMAC_Face.
Referenced by Operateur_Grad_base::dimensionner(), dimensionner(), dimensionner_bloc_vitesse(), Navier_Stokes_std::dimensionner_matrice_sans_mem(), and dimensionner_termes_croises().
void Operateur_base::dimensionner_termes_croises (Matrice_Morse & mat, const Probleme_base & autre_pb, int nl, int nc) const [virtual]
Reimplemented in Op_Diff_PolyMAC_Elem, and Op_Diff_VDF_Elem_base.
Definition at line 238 of file Operateur_base.cpp.
References dimensionner_blocs(), MorEqn::equation(), Nom::getString(), has_interface_blocs(), Equation_base::inconnue(), Probleme_base::le_nom(), O_U_Ptr::le_nom(), and Equation_base::probleme().
Referenced by Equation_base::dimensionner_termes_croises().
{
  if (!has_interface_blocs()) return;
  std::string nom_inco = equation().inconnue().le_nom().getString(),
              nom = equation().probleme().le_nom() == autre_pb.le_nom() ? nom_inco : nom_inco + "_" + autre_pb.le_nom().getString(); //nom de bloc croise pour l'interface_blocs
  dimensionner_blocs({{ nom, &mat }}, {});
}
virtual int Operateur_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
const Nom Operateur_base::fichier () const [inline]
Definition at line 118 of file Operateur_base.h.
References out_.
  {
    return out_;
  };
DoubleTab& Operateur_base::flux_bords () const [inline]
Definition at line 134 of file Operateur_base.h.
References flux_bords_.
  {
    return flux_bords_;
  };
DoubleTab& Operateur_base::flux_bords () [inline]
Definition at line 130 of file Operateur_base.h.
References flux_bords_.
Referenced by Terme_Source_Th_TdivU_VEF_Face::ajouter(), Champ_P1NC::calcul_h_conv(), Terme_Source_Canal_perio::compute_heat_flux(), Op_VEF_Face::impr(), Op_Diff_PolyMAC_base::impr(), Op_EF_base::impr(), Op_Diff_CoviMAC_base::impr(), Op_VEF_Face::modifier_flux(), and Op_EF_base::modifier_flux().
  {
    return flux_bords_;
  };
const Champ_base & Operateur_base::get_champ (const Motcle & nom) const [virtual]
Implements Champs_compris_interface.
Reimplemented in Op_Conv_EF.
Definition at line 566 of file Operateur_base.cpp.
References champs_compris_, and Champs_compris::get_champ().
Referenced by Equation_base::get_champ().
{
  return champs_compris_.get_champ(nom);
}
int Operateur_base::get_decal_temps () const [inline]
Definition at line 194 of file Operateur_base.h.
References decal_temps.
Referenced by Equation_base::completer(), construire_matrice_implicite(), Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
{
  return decal_temps;
}
const Type_info * Operateur_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 35 of file Operateur_base.cpp.
Motcle Operateur_base::get_localisation_pour_post (const Nom & option) const [virtual]
Reimplemented from MorEqn.
Reimplemented in Op_Diff_negligeable, Op_Conv_PolyMAC_iterateur_base, Op_Conv_VDF_base, Op_Conv_VEF_base, Op_Diff_VEF_base, and Op_Dift_VEF_Face.
Definition at line 621 of file Operateur_base.cpp.
References Cerr, Nom::debute_par(), MorEqn::equation(), Process::exit(), finl, Objet_U::que_suis_je(), Deriv_Zone_dis_base::valeur(), and Equation_base::zone_dis().
{
  Motcle loc;
  if (Motcle(option)=="flux_bords" || Motcle(option)=="flux_surfacique_bords")
    {
      const Zone_dis_base& zdis = equation().zone_dis().valeur();
      if (!zdis.que_suis_je().debute_par("Zone_VDF"))
        loc = "face";
      else
        loc = "elem";
    }
  else
    {
      Cerr<<"The method get_localisation_pour_post is not actually coded "<<finl;
      Cerr<<"for the operator "<<que_suis_je()<<" and for the option "<<option<<finl;
      exit();
    }
  return loc;
}
const Matrice & Operateur_base::get_matrice () const [inline]
Definition at line 206 of file Operateur_base.h.
References matrice_.
Referenced by Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
{
  return matrice_;
}
int Operateur_base::get_nb_ss_pas_de_temps () const [inline]
Definition at line 214 of file Operateur_base.h.
References nb_ss_pas_de_temps.
Referenced by Operateur::ajouter().
{
  return nb_ss_pas_de_temps;
}
void Operateur_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const [virtual]
Implements Champs_compris_interface.
Definition at line 575 of file Operateur_base.cpp.
References Vect_Nom::add(), Cerr, champs_compris_, DESCRIPTION, finl, Champs_compris::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Equation_base::get_noms_champs_postraitables().
{
  if (opt==DESCRIPTION)
    Cerr<<que_suis_je()<<" : "<<champs_compris_.liste_noms_compris()<<finl;
  else
    nom.add(champs_compris_.liste_noms_compris());
}
const SolveurSys & Operateur_base::get_solveur () const [inline]
Definition at line 222 of file Operateur_base.h.
References solveur.
Referenced by construire_matrice_implicite(), Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
{
  return solveur;
}
bool Operateur_base::has_champ (const Motcle & nom, Ref_Champ_base & ref_champ) const [virtual]
Definition at line 570 of file Operateur_base.cpp.
References champs_compris_, and Champs_compris::has_champ().
{
  return champs_compris_.has_champ(nom, ref_champ);
}
virtual int Operateur_base::has_interface_blocs () const [inline, virtual]
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Diff_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Grad_CoviMAC_Face, Op_Conv_negligeable, Op_Diff_negligeable, Op_Evanescence_Homogene_CoviMAC_Elem, and Op_Evanescence_Homogene_CoviMAC_Face.
Definition at line 84 of file Operateur_base.h.
Referenced by Operateur_Grad_base::ajouter(), ajouter(), Operateur_Grad_base::contribuer_a_avec(), contribuer_a_avec(), contribuer_bloc_vitesse(), contribuer_termes_croises(), Operateur_Grad_base::dimensionner(), dimensionner(), dimensionner_bloc_vitesse(), dimensionner_termes_croises(), QDM_Multiphase::has_interface_blocs(), Masse_Multiphase::has_interface_blocs(), Energie_Multiphase::has_interface_blocs(), Navier_Stokes_std::has_interface_blocs(), and Equation_base::has_interface_blocs().
  {
    return 0;
  };
int Operateur_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented in Op_Conv_CoviMAC_base, Op_Diff_CoviMAC_base, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF_base, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Grad_VEF_P1B_Face, Op_Conv_PolyMAC_iterateur_base, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Conv_VEF_base, Op_Diff_VEF_base, Op_Div_VEF_Elem, and Op_Grad_VEF_Face.
Definition at line 204 of file Operateur_base.cpp.
Referenced by Operateur::impr(), and Operateur::imprimer().
{
  return 1;
}
const Type_info * Operateur_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 35 of file Operateur_base.cpp.
Entree & Operateur_base::lire_solveur (Entree & is) [inline]
Definition at line 202 of file Operateur_base.h.
References solveur.
Referenced by Operateur::lire().
{
  return is >> solveur;
}
void Operateur_base::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Diff_CoviMAC_base, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_var_Face_Axi, and Op_Dift_VEF_base.
Definition at line 104 of file Operateur_base.cpp.
Referenced by Operateur::mettre_a_jour(), and Equation_base::updateGivenFields().
{
}
void Operateur_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Diff_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Conv_EF, Op_Diff_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Diff_P1NC_barprim, Op_Div_VEFP1B_Elem, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_EF_Stab_PolyMAC_Face, Op_Diff_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_Muscl_New_VEF_Face, Op_Conv_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Q1, Op_Dift_VEF_Face, and Op_Dift_VEF_Face_Q1.
Definition at line 291 of file Operateur_base.cpp.
References Cerr, MorEqn::equation(), Process::exit(), finl, Equation_base::probleme(), Objet_U::que_suis_je(), and Probleme_base::schema_temps().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), and Equation_base::modifier_pour_Cl().
{
  Cerr << "***********************************************************************************" << finl;
  Cerr << "Sorry, implicit scheme is not available yet for the " << que_suis_je() << " scheme." << finl;
  Cerr << "Please, change this scheme or use another time scheme than " << equation().probleme().schema_temps().que_suis_je() << finl;
  Cerr << "***********************************************************************************" << finl;
// Cerr << "You must overload the method " << que_suis_je()
// << "::modifier_pour_Cl(Matrice_Morse&, DoubleTab&)" << finl;
  exit();
}
void Operateur_base::ouvrir_fichier (SFichier & os, const Nom & type, const int & flag = 1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
Definition at line 409 of file Operateur_base.cpp.
References Process::abort(), Sortie::add_col(), Zone::Bords_a_imprimer_sum(), Cerr, col_width_, List_Nom::contient(), description(), Objet_U::dimension, MorEqn::equation(), Process::exit(), finl, flux_bords_, Nom::getChar(), Nom::getSuffix(), Schema_Temps_base::gnuplot_header(), Equation_base::inconnue(), Process::je_suis_maitre(), Frontiere_dis_base::le_nom(), O_U_Ptr::le_nom(), Probleme_base::le_nom(), DoubleVect::line_size(), max(), DoubleTab::nb_dim(), Schema_Temps_base::nb_impr(), Objet_U::nom_du_cas(), out_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie::set_col_width(), Sortie_Fichier_base::setf(), vect_impl::size(), sub_type, valeur(), Schema_Temps_base::wcol(), Zone_dis::zone(), and Equation_base::zone_dis().
Referenced by Op_VEF_Face::impr(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Div_PolyMAC::impr(), Op_Diff_PolyMAC_base::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_EF_base::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Diff_CoviMAC_base::impr(), and Op_Conv_CoviMAC_base::impr().
{
// flag nul on n'ouvre pas le fichier
  if (flag==0)
    return ;
  if (!je_suis_maitre())
    {
      Cerr<<"Only master process can open "<<type<<" file. See Operateur_base::ouvrir_fichier()" << finl;
      Process::abort();
    }
  const Equation_base& eqn = equation();
  const Probleme_base& pb=eqn.probleme();
  const Schema_Temps_base& sch=pb.schema_temps();
  const int precision = sch.precision_impr(), wcol = max(col_width_, sch.wcol()), gnuplot_header = sch.gnuplot_header();
  os.set_col_width(wcol);
  Nom nomfichier(out_);
  if (type!="") nomfichier+=(Nom)"_"+type;
  nomfichier+=".out";
  struct stat f;
// On cree le fichier a la premiere impression avec l'en tete ou si le fichier n'existe pas
  if (stat(nomfichier,&f) || (sch.nb_impr()==1 && !pb.reprise_effectuee()))
    {
      os.ouvrir(nomfichier);
      std::vector<std::string> comp_m = {"_Mx", "_My", "_Mz"};
      os << (Nom)"# Printing on the boundaries of the equation "+eqn.que_suis_je()+" of the problem "+eqn.probleme().le_nom() << finl;
      os << "# " << (type=="moment" ? "Moment of " : "") << description() << finl;
      if (!gnuplot_header) os << "#";
      os.set_col_width(wcol - !gnuplot_header);
      os.add_col("Time");
      os.set_col_width(wcol);
      const Conds_lim& les_cls=eqn.inconnue()->zone_Cl_dis().les_conditions_limites();
      if (flux_bords_.nb_dim()!=2)
        {
          Cerr << "flux_bords_ not dimensioned for the operator " << que_suis_je() << finl;
          Process::exit();
        }
// s'il y a plusieurs composantes par CL, on se sert des noms de composante de l'inconnue
      int nb_compo = flux_bords_.line_size();
      if (type=="moment" && dimension == 2) nb_compo=1;
      Noms noms_compo_courts(eqn.inconnue()->noms_compo());
      if (nb_compo > 1) for (int i = 0; i < noms_compo_courts.size(); ++i)
          noms_compo_courts[i] = Motcle(noms_compo_courts[i]).getSuffix(eqn.inconnue().le_nom());
// ecriture de l'entete des colonnes de la forme
// Time cl1  cl2  cl3  ...
// ou s'il y a plusieurs composantes :
// Time cl1_compo1  cl1_compo2 cl2 compo1 cl2_compo2 ...
      for (int num_cl=0; num_cl<les_cls.size(); num_cl++)
        {
          const Frontiere_dis_base& la_fr = les_cls[num_cl].frontiere_dis();
          if (type!="sum" || eqn.zone_dis().zone().Bords_a_imprimer_sum().contient(la_fr.le_nom()))
            {
              Nom ch = la_fr.le_nom();
              if (type=="moment")
                {
                  if (dimension==2)
                    os.add_col((ch + comp_m[2].c_str()).getChar());
                  else
                    for (int d = 0; d < dimension; ++d)
                      os.add_col((ch + comp_m[d].c_str()).getChar());
                }
              else
                {
                  if (nb_compo > 1) for (int d = 0; d < nb_compo; ++d)
                      {
                        os.add_col((ch + "_" + noms_compo_courts[d]).getChar());
                      }
                  else os.add_col(ch.getChar());
// if periodic BC, we write the boundary name twice on the header of .out files
                  if ((sub_type(Periodique,les_cls[num_cl].valeur())) && (Objet_U::nom_du_cas()+"_"+eqn.probleme().le_nom()+"_Force_pression"!=out_))
                    {
                      if (nb_compo > 1) for (int d = 0; d < nb_compo; ++d)
{
                            os.add_col((ch + "_" + noms_compo_courts[d]).getChar());
                          }
                      else os.add_col(ch.getChar());
                    }
                }
            }
        }
      if (type!="sum" && type!="moment") if (Objet_U::nom_du_cas()+"_"+eqn.probleme().le_nom()+"_Force_pression"!=out_)
          {
            if (nb_compo > 1) for (int d = 0; d < nb_compo; ++d)
                os.add_col((Nom("Total_") + noms_compo_courts[d]).getChar());
            else os.add_col("Total");
          }
      os << finl;
    }
// Sinon on l'ouvre
  else
    {
      os.ouvrir(nomfichier,ios::app);
    }
  os.precision(precision);
  os.setf(ios::scientific);
}
void Operateur_base::ouvrir_fichier_partage (EcrFicPartage & os, const Nom & type, const int & flag = 1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
Definition at line 528 of file Operateur_base.cpp.
References MorEqn::equation(), Schema_Temps_base::nb_impr(), out_, EcrFicPartage::ouvrir(), EcrFicPartage::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Sortie_Fichier_base::setf().
Referenced by Op_VEF_Face::impr(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Div_PolyMAC::impr(), Op_Diff_PolyMAC_base::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_EF_base::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Diff_CoviMAC_base::impr(), and Op_Conv_CoviMAC_base::impr().
{
// flag nul on n'ouvre pas le fichier
  if (flag==0)
    return ;
  const Probleme_base& pb=equation().probleme();
  const Schema_Temps_base& sch=pb.schema_temps();
  const int& precision=sch.precision_impr();
  Nom nomfichier(out_);
  if (type!="") nomfichier+=(Nom)"_"+type;
  nomfichier+=".face";
// On cree le fichier a la premiere impression avec l'en tete
  if (sch.nb_impr()==1 && !pb.reprise_effectuee())
    {
      os.ouvrir(nomfichier);
    }
// Sinon on l'ouvre
  else
    {
      os.ouvrir(nomfichier,ios::app);
    }
  os.precision(precision);
  os.setf(ios::scientific);
}
void Operateur_base::preparer_calcul (void) [virtual]
Reimplemented in Op_Conv_EF_Stab_CoviMAC_Elem.
Definition at line 662 of file Operateur_base.cpp.
Referenced by Equation_base::preparer_calcul().
{ }
Sortie & Operateur_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 60 of file Operateur_base.cpp.
{
  return os ;
}
Entree & Operateur_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 82 of file Operateur_base.cpp.
{
  return is ;
}
const Operateur_base & Operateur_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 35 of file Operateur_base.cpp.
Operateur_base & Operateur_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 35 of file Operateur_base.cpp.
int Operateur_base::set_decal_temps (int i) [inline]
Definition at line 198 of file Operateur_base.h.
References decal_temps.
Referenced by Operateur::lire().
{
  return decal_temps=i;
}
void Operateur_base::set_description (const Nom & nom) [inline]
Definition at line 122 of file Operateur_base.h.
References description_.
Referenced by Operateur::set_description().
  {
    description_=nom;
  };
void Operateur_base::set_fichier (const Nom & nom)
Definition at line 386 of file Operateur_base.cpp.
References MorEqn::equation(), Probleme_base::le_nom(), Objet_U::nom_du_cas(), out_, and Equation_base::probleme().
Referenced by Operateur::set_fichier().
{
  out_=Objet_U::nom_du_cas();
  out_+="_";
  out_+=equation().probleme().le_nom()+"_"+nom;
  if (nom=="") out_+="unknown_operator";
}
Matrice & Operateur_base::set_matrice () [inline]
Definition at line 210 of file Operateur_base.h.
References matrice_.
Referenced by construire_matrice_implicite(), Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
{
  return matrice_;
}
int Operateur_base::set_nb_ss_pas_de_temps (int i) [inline]
Definition at line 218 of file Operateur_base.h.
References nb_ss_pas_de_temps.
Referenced by Operateur::lire().
{
  return nb_ss_pas_de_temps=i;
}
SolveurSys & Operateur_base::set_solveur () [inline]
Definition at line 226 of file Operateur_base.h.
References solveur.
Referenced by construire_matrice_implicite(), Navier_Stokes_std::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), and Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base().
{
  return solveur;
}
int Operateur_base::systeme_invariant () const [virtual]
Definition at line 376 of file Operateur_base.cpp.
Referenced by Equation_base::completer().
{
  return 1;
}
void Operateur_base::tester_contribuer_a_avec (const DoubleTab & inco, const Matrice_Morse & matrice)
< Calcule l'operateur Op(Inc(n)) avec methode ajouter dans resu
< Construit la matrice de l'operateur (mat=-A)
< Calcule le flux avec la matrice et l'ajoute a resu (resu=Op(Inc(n))-A*Inc(n))
< Ajoute flux impose
< M-1*(Op(Inc(n))-A*Inc(n)) On multiplie par le volume car les coefficients sont divises par le volume et on ne veut pas qu'un calcul sur des petites mailles semblent disfonctionner;
Definition at line 666 of file Operateur_base.cpp.
References Matrice_Base::ajouter_multvect(), Solveur_Masse::appliquer(), calculer(), Cerr, coeff, contribuer_a_avec(), contribuer_au_second_membre(), dabs(), Process::exit(), finl, Matrice_Morse::get_set_coeff(), MorEqn::mon_equation, mp_max_abs_vect(), mp_max_vect(), Objet_U::que_suis_je(), resu_, DoubleVect::size(), Equation_base::solv_masse(), and Ref_Equation_base::valeur().
Referenced by Convection_Diffusion_Temperature::assembler(), and Equation_base::assembler().
{
  int test_op=0;
  {
    char* theValue = getenv("TRUST_TEST_OPERATEUR_IMPLICITE");
    if (theValue != NULL) test_op=2;
  }
  {
    char* theValue = getenv("TRUST_TEST_OPERATEUR_IMPLICITE_BLOQUANT");
    if (theValue != NULL) test_op=1;
  }
  if (test_op==0) return;
  Matrice_Morse mat(matrice);
  DoubleTrav resu(inco);
  DoubleVect& coeff = mat.get_set_coeff();
// A*Inc(n)=Op(Inc(n))+
  coeff=0;
  calculer(inco, resu); //!< Calcule l'operateur Op(Inc(n)) avec methode ajouter dans resu
  contribuer_a_avec(inco, mat); //!< Construit la matrice de l'operateur (mat=-A)
  mat.ajouter_multvect(inco, resu); //!< Calcule le flux avec la matrice et l'ajoute a resu (resu=Op(Inc(n))-A*Inc(n))
  resu*=-1;
  contribuer_au_second_membre(resu); //!< Ajoute flux impose
  mon_equation.valeur().solv_masse().appliquer(resu); //!< M-1*(Op(Inc(n))-A*Inc(n)) On multiplie par le volume car les coefficients sont divises par le volume et on ne veut pas qu'un calcul sur des petites mailles semblent disfonctionner;
//
//
  DoubleTab un(inco);
  un=1;
  mon_equation.valeur().solv_masse().appliquer(un);
  resu/=mp_max_vect(un);
  double err=mp_max_abs_vect(resu);
  Cerr<<"Test contribuer_a_avec on " << que_suis_je() <<" error: "<<err<<finl;;
  if (err>1e-6)
    {
      {
        DoubleVect& resu_=resu;
        Cerr<<" size "<< resu_.size()<<finl;
        for (int i=0; i<resu_.size(); i++)
          if (dabs(resu_(i))>1e-10)
            {
              Cerr<<i << " "<< resu_(i)<< " "<<finl;
            }
      }
      if (test_op==1)
        exit();
    }
}
Member Data Documentation
Champs_compris Operateur_base::champs_compris_ [protected]
Definition at line 170 of file Operateur_base.h.
Referenced by Op_Conv_EF_Stab_CoviMAC_Elem::creer_champ(), get_champ(), get_noms_champs_postraitables(), has_champ(), and Op_Conv_EF_Stab_CoviMAC_Elem::readOn().
int Operateur_base::col_width_
minimal size of a column for .out files (based on cl name length)
Definition at line 159 of file Operateur_base.h.
Referenced by completer(), Operateur_base(), and ouvrir_fichier().
int Operateur_base::decal_temps [protected]
Definition at line 162 of file Operateur_base.h.
Referenced by get_decal_temps(), Operateur_base(), and set_decal_temps().
Nom Operateur_base::description_ [protected]
Description de l'operateur.
Definition at line 167 of file Operateur_base.h.
Referenced by description(), and set_description().
DoubleTab Operateur_base::flux_bords_ [mutable, protected]
Tableau contenant les flux sur les bords de l'operateur.
Definition at line 168 of file Operateur_base.h.
Referenced by Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter(), Op_Diff_VEF_Anisotrope_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Div_EF::ajouter(), Op_Div_CoviMAC::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Dift_standard_VEF_Face::ajouter_cas_vectoriel(), Op_Diff_VEF_base::associer(), Op_Diff_EF_base::associer(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), calculer_pour_post(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), flux_bords(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VEF_P1B_Face::impr(), Op_Grad_EF::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Conv_CoviMAC_base::impr(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour(), Op_Dift_Stab_VEF_Face::modifie_pour_Cl(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), ouvrir_fichier(), Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul(), Op_Conv_VEF_base::remplir_fluent(), and Op_Conv_EF_base::remplir_fluent().
const Type_info Operateur_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Op_Conv_CoviMAC_base, Op_Conv_EF_Stab_CoviMAC_Elem, Op_Conv_Amont_CoviMAC_Elem, Op_Conv_Centre_CoviMAC_Elem, Op_Conv_EF_Stab_CoviMAC_Face, Op_Conv_Amont_CoviMAC_Face, Op_Conv_Centre_CoviMAC_Face, Op_Diff_CoviMAC_base, Op_Diff_CoviMAC_Elem, Op_Diff_Nonlinear_CoviMAC_Elem, Op_Dift_CoviMAC_Elem, Op_Dift_Nonlinear_CoviMAC_Elem, Op_Diff_CoviMAC_Face, Op_Div_CoviMAC, Op_Grad_CoviMAC_Face, Op_Conv_EF, Op_Conv_BTD_EF, Op_Conv_EF_base, Op_Conv_SUPG_EF, Op_Diff_EF, Op_Diff_option_EF, Op_Diff_EF_base, Op_Div_EF, Op_Grad_EF, Op_Conv_negligeable, Op_Diff_negligeable, Op_Dift_negligeable, Operateur_Conv_base, Operateur_Diff_base, Operateur_Div_base, Operateur_Grad_base, Op_Curl_VEFP1B, Op_Diff_P1NC_barprim, Op_Diff_RotRot, Op_Diff_VEFP1NCP1B_Face, Op_Diff_VEFP1NCP1B_Face_Var, Op_Dift_VEF_P1NCP1B_Face, Op_Div_VEFP1B_Elem, Op_Grad_VEF_P1B_Face, Op_Rot_VEFP1B, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_iterateur_base, Op_Conv_Amont_PolyMAC_Face, Op_Conv_Centre_PolyMAC_Face, Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_PolyMAC_base, Op_Diff_PolyMAC_base, Op_Diff_PolyMAC_Elem, Op_Diff_Nonlinear_PolyMAC_Elem, Op_Dift_PolyMAC_Elem, Op_Dift_Nonlinear_PolyMAC_Elem, Op_Diff_PolyMAC_Face, Op_Div_PolyMAC, Op_Grad_PolyMAC_Face, Op_Conv_ALE, Op_Evanescence_Homogene_CoviMAC_Elem, Op_Evanescence_Homogene_CoviMAC_Face, Operateur_Evanescence_base, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Amont_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_centre4_VDF_Elem, Op_Conv_centre4_VDF_Face, Op_Conv_centre_VDF_Elem, Op_Conv_Centre_VDF_Face, Op_Conv_Quick_VDF_Elem, Op_Conv_Quick_VDF_Face, Op_Conv_VDF_base, Op_Div_VDF_base, Op_Div_VDF_Elem, Op_Grad_P0_to_Face, Op_Grad_VDF_base, Op_Grad_VDF_Face, Op_Diff_VDF_base, Op_Diff_VDF_Elem, Op_Diff_VDF_Elem_Axi, Op_Diff_VDF_Elem_base, Op_Diff_VDF_Face, Op_Diff_VDF_Face_Axi, Op_Diff_VDF_Face_base, Op_Diff_VDF_Multi_inco_Elem, Op_Diff_VDF_Multi_inco_Elem_Axi, Op_Diff_VDF_Multi_inco_var_Elem, Op_Diff_VDF_Multi_inco_var_Elem_Axi, Op_Diff_VDF_var_Elem, Op_Diff_VDF_var_Elem_aniso, Op_Diff_VDF_var_Elem_Axi, Op_Diff_VDF_var_Face, Op_Diff_VDF_var_Face_Axi, Op_Dift_VDF_base, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face_base, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, Op_Dift_VDF_var_Face_Axi, Op_Conv_Amont_old_VEF_Face, Op_Conv_Amont_VEF_Face, Op_Conv_AmontNew_VEF_Face, Op_Conv_Centre_EF_VEF_Face, Op_Conv_Centre_old_VEF_Face, Op_Conv_Centre_VEF_Face, Op_Conv_DI_L2_VEF_Face, Op_Conv_EF_VEF_P1NC, Op_Conv_EF_VEF_P1NC_Stab, Op_Conv_kschemas_centre_VEF, Op_Conv_kschemas_VEF, Op_Conv_Muscl3_VEF_Face, Op_Conv_Muscl_New_VEF_Face, Op_Conv_Muscl_old_VEF_Face, Op_Conv_Muscl_VEF_Face, Op_Conv_VEF_base, Op_Conv_VEF_Face, Op_Conv_Vort_VEF_Face, Op_Diff_VEF_Anisotrope_Face, Op_Diff_VEF_base, Op_Diff_VEF_Face, Op_Diff_VEF_Face_Penalise, Op_Diff_VEF_Face_Q1, Op_Diff_VEF_Face_Stab, Op_Diff_VEF_Face_Stab_Var, Op_Diff_VEF_Face_Var, Op_Diff_VEF_Face_Var_Q1, Op_Dift_Stab_VEF_Face, Op_Dift_Stab_VEF_Face_Var, Op_Dift_standard_VEF_Face, Op_Dift_standard_VEF_Face_Var, Op_Dift_VEF_base, Op_Dift_VEF_Face, Op_Dift_VEF_Face_Q1, Op_Dift_VEF_Face_Var, Op_Div_VEF_Elem, Op_Grad_P1NC_to_P0, Op_Grad_VEF_Face, OpVEF_Centre, OpVEF_Centre4, and OpVEF_Quick.
Definition at line 65 of file Operateur_base.h.
Ref_Champ_Inc Operateur_base::le_champ_inco [protected]
Definition at line 171 of file Operateur_base.h.
Referenced by associer_champ(), and completer().
Matrice Operateur_base::matrice_ [protected]
Definition at line 165 of file Operateur_base.h.
Referenced by get_matrice(), and set_matrice().
int Operateur_base::nb_ss_pas_de_temps [protected]
Definition at line 163 of file Operateur_base.h.
Referenced by get_nb_ss_pas_de_temps(), Operateur_base(), and set_nb_ss_pas_de_temps().
Nom Operateur_base::out_ [protected]
Nom du fichier .out pour l'impression.
Definition at line 166 of file Operateur_base.h.
Referenced by fichier(), ouvrir_fichier(), ouvrir_fichier_partage(), and set_fichier().
SolveurSys Operateur_base::solveur [protected]
Reimplemented in Op_Dift_VEF_P1NCP1B_Face.
Definition at line 164 of file Operateur_base.h.
Referenced by Op_Diff_RotRot::associer(), get_solveur(), lire_solveur(), and set_solveur().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Operateur_base.h
src/Kernel/Framework/Operateur_base.cpp