TRUST: Perte_Charge_Singuliere_VDF_Face Class Reference
Perte_Charge_Singuliere_VDF_Face Class Reference
class Perte_Charge_Singuliere_VDF_Face
#include <Perte_Charge_Singuliere_VDF_Face.h>
Public Member Functions
Perte_Charge_Singuliere_VDF_Face ()
~Perte_Charge_Singuliere_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &) const
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
void remplir_num_faces (Entree &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Singuliere_VDF_Face & self_cast (Objet_U &)
static const
Perte_Charge_Singuliere_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
IntVect sgn
Detailed Description
class Perte_Charge_Singuliere_VDF_Face
See also:
Perte_Charge_VDF_Face
Definition at line 42 of file Perte_Charge_Singuliere_VDF_Face.h.
Constructor & Destructor Documentation
Perte_Charge_Singuliere_VDF_Face::Perte_Charge_Singuliere_VDF_Face ()
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
Perte_Charge_Singuliere_VDF_Face::~Perte_Charge_Singuliere_VDF_Face ()
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Perte_Charge_Singuliere_VDF_Face::ajouter_ (const DoubleTab & inco, DoubleTab & resu) const [virtual]
< vitesse debitante
Implements Source_dep_inco_base.
Definition at line 147 of file Perte_Charge_Singuliere_VDF_Face.cpp.
References Objet_U::axi, dabs(), Perte_Charge_Singuliere::K(), Perte_Charge_VDF_Face::la_vitesse, Perte_Charge_VDF_Face::la_zone_VDF, Perte_Charge_VDF_Face::num_faces, Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), IntVect::size(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  int ndeb_faces_int = zone_VDF.premiere_face_int();
  int nb_faces = num_faces.size();
  int numfa;
  double Ck,U;
  double Ud; //!< vitesse debitante
  if (axi)
    for (int i=0; i<nb_faces; i++)
      {
        numfa = num_faces[i];
        U = vit[numfa];
        if (numfa < ndeb_faces_int)
          Ck = -0.5*K()/la_zone_VDF->dist_norm_bord_axi(numfa);
        else
          Ck = -0.5*K()/la_zone_VDF->dist_norm_axi(numfa);
        resu[numfa] += Ck*U*dabs(U)*volumes_entrelaces[numfa]*porosite_surf[numfa];
      }
  else
    for (int i=0; i<nb_faces; i++)
      {
        numfa = num_faces[i];
        U = inco[numfa]*porosite_surf[numfa];
        Ud = vit[numfa]*porosite_surf[numfa];
        if (numfa < ndeb_faces_int)
          Ck = -0.5*K()/la_zone_VDF->dist_norm_bord(numfa);
        else
          Ck = -0.5*K()/la_zone_VDF->dist_norm(numfa);
        resu[numfa] += Ck*U*dabs(Ud)*volumes_entrelaces[numfa]*porosite_surf[numfa];
      }
  return resu;
}
void Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
< vitesse debitante
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 98 of file Perte_Charge_Singuliere_VDF_Face.cpp.
References Objet_U::axi, dabs(), Perte_Charge_Singuliere::K(), Perte_Charge_VDF_Face::la_vitesse, Perte_Charge_VDF_Face::la_zone_VDF, Perte_Charge_VDF_Face::num_faces, Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), IntVect::size(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  int ndeb_faces_int = zone_VDF.premiere_face_int();
  int nb_faces = num_faces.size();
  int numfa;
  double Ck;
  double Ud; //!< vitesse debitante
  if (axi)
    for (int i=0; i<nb_faces; i++)
      {
        /*
          numfa = num_faces[i];
          U = vit[numfa];
          if (numfa < ndeb_faces_int)
          Ck = -0.5*K()/la_zone_VDF->dist_norm_bord_axi(numfa);
          else
          Ck = -0.5*K()/la_zone_VDF->dist_norm_axi(numfa);
          //resu[numfa] += Ck*U*dabs(U)*volumes_entrelaces[numfa]*porosite_surf[numfa];
          */
      }
  else
    for (int i=0; i<nb_faces; i++)
      {
        numfa = num_faces[i];
// U = vit[numfa];
        Ud = vit[numfa]*porosite_surf[numfa];
        if (numfa < ndeb_faces_int)
          Ck = -0.5*K()/la_zone_VDF->dist_norm_bord(numfa);
        else
          Ck = -0.5*K()/la_zone_VDF->dist_norm(numfa);
// resu[numfa] += Ck*Ud*dabs(Ud)*volumes_entrelaces[numfa]*porosite_surf[numfa];
        matrice(numfa,numfa)-=Ck*porosite_surf[numfa]*dabs(Ud)*volumes_entrelaces[numfa]*porosite_surf[numfa];
      }
}
Objet_U * Perte_Charge_Singuliere_VDF_Face::cree_instance () [static]
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
int Perte_Charge_Singuliere_VDF_Face::duplique () const [virtual]
Implements Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
const Type_info * Perte_Charge_Singuliere_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
const Type_info * Perte_Charge_Singuliere_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
void Perte_Charge_Singuliere_VDF_Face::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Perte_Charge_VDF_Face.
Definition at line 192 of file Perte_Charge_Singuliere_VDF_Face.cpp.
References Source_base::bilan(), Perte_Charge_Singuliere::calculate_Q(), MorEqn::equation(), Perte_Charge_VDF_Face::num_faces, sgn, and Perte_Charge_Singuliere::update_K().
{
  Perte_Charge_VDF_Face::mettre_a_jour(temps);
  update_K(equation(), calculate_Q(equation(), num_faces, sgn), bilan());
}
Sortie & Perte_Charge_Singuliere_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 36 of file Perte_Charge_Singuliere_VDF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Perte_Charge_Singuliere_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 45 of file Perte_Charge_Singuliere_VDF_Face.cpp.
References Source_base::bilan(), Perte_Charge_Singuliere::identifiant_, Perte_Charge_Singuliere::lire_donnees(), Perte_Charge_Singuliere::regul_, remplir_num_faces(), DoubleVect::resize(), Source_base::set_description(), and Source_base::set_fichier().
{
  Perte_Charge_Singuliere::lire_donnees(s);
  remplir_num_faces(s);
  if (regul_) //fichier de sortie si regulation
    {
      bilan().resize(3); //K deb cible
      set_fichier(Nom("K_") + identifiant_);
      set_description(Nom("Regulation du Ksing de la surface ") + identifiant_ + "\nt K deb cible");
    }
  return s;
}
void Perte_Charge_Singuliere_VDF_Face::remplir_num_faces (Entree & s)
Definition at line 67 of file Perte_Charge_Singuliere_VDF_Face.cpp.
References Cerr, Perte_Charge::direction_perte_charge(), Probleme_base::domaine(), MorEqn::equation(), Process::exit(), finl, Perte_Charge_Singuliere::lire_surfaces(), Process::mp_sum(), Zone_dis_base::nb_elem(), Perte_Charge_VDF_Face::num_faces, Zone_VDF::orientation(), Equation_base::probleme(), ref_cast, IntVect::resize(), sgn, IntVect::size(), and valeur().
Referenced by readOn().
{
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_VDF& zone_VDF = ref_cast(Zone_VDF,equation().zone_dis().valeur());
  int taille_bloc = zone_VDF.nb_elem();
  num_faces.resize(taille_bloc);
  lire_surfaces(s,le_domaine,zone_VDF,num_faces, sgn);
  int nfac = num_faces.size();
  int nfac_tot = mp_sum(num_faces.size());
  if (nfac_tot==0)
    {
      Cerr << "Erreur a la lecture des donnees de la perte de charge singuliere :" << finl;
      Cerr << " la surface sur laquelle vous avez defini une perte de charge" << finl;
      Cerr << " ne contient entierement aucune des faces de la geometrie " <<  finl;
      exit();
    }
  if (nfac != 0)
    {
      int ori = zone_VDF.orientation(num_faces[0]);
      if (ori != direction_perte_charge())
        {
          Cerr << "Erreur a la lecture des donnees de la perte de charge singuliere : " << finl;
          Cerr << " l'orientation de la surface est differente de la direction" << finl;
          Cerr << " de la perte de charge" << finl;
          exit();
        }
    }
}
const Perte_Charge_Singuliere_VDF_Face & Perte_Charge_Singuliere_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
Perte_Charge_Singuliere_VDF_Face & Perte_Charge_Singuliere_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
unsigned Perte_Charge_Singuliere_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Singuliere_VDF_Face.cpp.
Member Data Documentation
const Type_info Perte_Charge_Singuliere_VDF_Face::info_obj [static]
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Singuliere_QC_VDF_Face.
Definition at line 46 of file Perte_Charge_Singuliere_VDF_Face.h.
IntVect Perte_Charge_Singuliere_VDF_Face::sgn [protected]
Definition at line 56 of file Perte_Charge_Singuliere_VDF_Face.h.
Referenced by mettre_a_jour(), and remplir_num_faces().
The documentation for this class was generated from the following files:
src/VDF/Sources/Perte_Charge_Singuliere_VDF_Face.h
src/VDF/Sources/Perte_Charge_Singuliere_VDF_Face.cpp