TRUST: Echange_contact_Correlation_VDF Class Reference
Echange_contact_Correlation_VDF Class Reference
#include <Echange_contact_Correlation_VDF.h>
Public Member Functions
Echange_contact_Correlation_VDF ()
~Echange_contact_Correlation_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double) override
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
void completer () override
virtual void imprimer (double) const
virtual int limpr (double, double) const
virtual double calculer_coefficient_echange (int i)
virtual double volume (double s, double d)
double getU (int i) const
double getT (int i) const
double getMu (int i) const
double getLambda (int i) const
double getRho (int i) const
double getCp () const
double getDh () const
double getQh () const
Public Member Functions inherited from Echange_global_impose
Echange_global_impose ()
~Echange_global_impose ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int compatible_avec_discr (const Discretisation_base &discr) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
void completer () override
NE FAIT RIEN
A surcharger dans les classes derivees.
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void mettre_a_jour (double temps) override
Effectue une mise a jour en temps de la condition aux limites.
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Champ_front & derivee_phi_ext ()
const Champ_front & derivee_phi_ext () const
Champ_front & phi_ext ()
const Champ_front & phi_ext () const
virtual double champ_exterieur (int i, int j, const Champ_front &champ_ext) const
virtual double champ_exterieur (int i, const Champ_front &champ_ext) const
virtual double flux_exterieur_impose (int i) const
virtual double flux_exterieur_impose (int i, int j) const
virtual double derivee_flux_exterieur_imposee (int i) const
virtual double derivee_flux_exterieur_imposee (int i, int j) const
const bool & has_phi_ext () const
Public Member Functions inherited from Echange_impose_base
~Echange_impose_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual double h_imp (int num) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double h_imp (int num, int k) const
Renvoie la valeur du coefficient d'echange
de chaleur impose sur la i-eme composante
du champ de frontiere.
virtual double T_ext (int num) const
Renvoie la valeur de la temperature imposee
sur la i-eme composante du champ de frontiere.
virtual double T_ext (int num, int k) const
Renvoie la valeur de la temperature imposee
sur la (i,j)-eme composante du champ de frontiere.
void mettre_a_jour (double) override
Effectue une mise a jour en temps
des conditions aux limites.
Lors du premier appel des initialisations sont effectuees:
h_imp(0,0) = (rho(0,0)*Cp(0,0))
int initialiser (double temps) override
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
int a_mettre_a_jour_ss_pas_dt () override
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_temps_defaut (double temps) override
Change le i-eme temps futur de la cl.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
void changer_temps_futur (double temps, int i) override
Change le i-eme temps futur de la CL.
int avancer (double temps) override
Tourne la roue de la CL.
int reculer (double temps) override
Tourne la roue de la CL.
void associer_fr_dis_base (const Frontiere_dis_base &) override
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
virtual Champ_front & T_ext ()
Renvoie le champ T_ext de temperature imposee a la frontiere.
virtual const Champ_front & T_ext () const
Renvoie le champ T_ext de temperature imposee a la frontiere.
(version const)
virtual Champ_front & h_imp ()
Constructeur par defaut de la classe Echange_impose_base.
Ne construit rien, initialise le champ init a 0.
virtual const Champ_front & h_imp () const
int compatible_avec_eqn (const Equation_base &) const override
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
int compatible_avec_discr (const Discretisation_base &) const override
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void liste_faces_loi_paroi (IntTab &)
Public Member Functions inherited from Cond_lim_base
Cond_lim_base ()
~Cond_lim_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void completer ()
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int initialiser (double temps)
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour
Contrairementaux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de la condition aux limites.
virtual void calculer_coeffs_echange (double temps)
Calcul des coefficient d'echange pour un couplage par
Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de
l'inconnue. Ils doivent donc etre faits chaque fois que
l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et
stockes dans les CLs.
WEC : Les Champ_front_contact_VEF devraient disparaitre et cette
methode avec !!!
virtual void verifie_ch_init_nb_comp () const
Appel la verification du champ lu par l intermediaire
de l equation pour laquelle on considere la condition limite
La methode est surchargee dans les cas ou l utilisateur doit
specifier le champ frontiere.
virtual Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
virtual const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee a laquelle les conditions
aux limites s'appliquent.
(version const)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre
Champ_front de l'objet Cond_lim_base qui represente le champ des conditions
aux limites imposees a la frontiere.
Zone_Cl_dis_base & zone_Cl_dis ()
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
const Zone_Cl_dis_base & zone_Cl_dis () const
Renvoie la zone des conditions aux limites discretisee dont
l'objet fait partie.
(version const)
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)
Associe la Zone_Cl_dis_base (Zone des conditions aux limites discretisees)
a l'objet. Cette Zone_Cl_dis_base stocke (reference) toutes les conditions
aux limites relative a une Zone geometrique.
Champ_front & champ_front ()
const Champ_front & champ_front () const
virtual void set_temps_defaut (double temps)
Change le i-eme temps futur de la cl.
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Appel cha_front_base::fixer_nb_valeurs_temporelles.
virtual void champ_front (int, DoubleVect &) const
virtual int compatible_avec_eqn (const Equation_base &) const =0
virtual int compatible_avec_discr (const Discretisation_base &) const
Renvoie 1 si la condition aux limites est compatible
avec la discretisation passee en parametre.
NE FAIT RIEN
A Surcharger dans les classes derivees.
virtual void injecter_dans_champ_inc (const Champ_Inc &) const
virtual int a_mettre_a_jour_ss_pas_dt ()
Cette methode indique si cette condition aux limites doit
etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour
n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin<br>(exemple Echange_impose_base)
void set_modifier_val_imp (int)
Positionne le drapeau modifier_val_imp a la valeur donnee :
- si drap == 1 : modifier_val_imp=1
- sinon : modifier_val_imp=0
Ce drapeau permet a la CL de savoir si elle doit renvoyer la valeur stockee
telle quelle, ou si elle doit la traduire pour l'objet appelant
A la CL de savoir ensuite quelle traduction faire.
Voir application dans Temperature_imposee_paroi_H, ou la CL renvoie l'enthalpie
par defaut (modifier_val_imp=1), ou la temperature sinon (cas de l'operateur de diffusion)
Le drapeau est positionne dans le equation.derivee_en_temps_inco
selon l'operateur qui va etre appele.
virtual void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de la CL.
virtual int avancer (double temps)
Tourne la roue de la CL.
virtual int reculer (double temps)
Tourne la roue de la CL.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_contact_Correlation_VDF & self_cast (Objet_U &)
static const Echange_contact_Correlation_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_global_impose
static Objet_U * cree_instance ()
static const Type_info * info ()
static Echange_global_impose & self_cast (Objet_U &)
static const Echange_global_impose & self_cast (const Objet_U &)
Static Public Member Functions inherited from Echange_impose_base
static const Type_info * info ()
static Echange_impose_base & self_cast (Objet_U &)
static const Echange_impose_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Cond_lim_base
static const Type_info * info ()
static Cond_lim_base & self_cast (Objet_U &)
static const Cond_lim_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Echange_global_impose
static const Type_info info_obj
Static Public Attributes inherited from Echange_impose_base
static const Type_info info_obj
Static Public Attributes inherited from Cond_lim_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
void calculer_CL ()
void calculer_Q ()
void calculer_prop_physique ()
void trier_coord ()
void calculer_Vitesse ()
void calculer_Tfluide ()
void calculer_h_mon_pb (DoubleTab &)
void calculer_h_solide (DoubleTab &, const Equation_base &, const Zone_VDF &, const Front_VF &, const Milieu_base &)
void init_tab_echange ()
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecrit le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une condition aux limite de type Echange_impose_base
a partir d'un flot d'entree.
On doit lire le coefficient d'echange global H_imp et la temperature
a la frontiere T_ext.
Format:
"h_imp" type_champ_front bloc de lecture champ
"T_ext" type_champ_front bloc de lecture champ.
Protected Member Functions inherited from Cond_lim_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime la condition au limite sur un flot de sortie.
Seul le champ impose a la frontiere est imprime.
Entree & readOn (Entree &) override
Lecture d'une condition aux limites a partir d'un flot d'entree
Format:
lire un Champ_front.
void err_pas_compatible (const Equation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec l'equation sur laquelle on essaye
de l'appliquer.
void err_pas_compatible (const Discretisation_base &) const
Cette methode est appelee quand la condition aux limites
n'est pas compatible avec la discretisation sur laquelle on essaye
de l'appliquer.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect correspondance_solide_fluide
DoubleTab autre_h
int Reprise_temperature
DoubleTab tab_ech
double Tinf
double Tsup
Temperature entree, sortie.
double T_CL0
double T_CL1
CL sur le domaine. En seq. = Tinf et Tsup ; En parallele = Tvoisin.
int dir
Direction du cylindre.
Parser_U lambda_T
Parser_U mu_T
Parser_U rho_T
Parser_U fct_Nu
Parser_U fct_vol
double dt_impr
double Cp
double debit
double diam
diametre hydraulique
DoubleVect vol
volumes des tranches Sdz du volume suivant la direction de l'ecoulement
DoubleVect coord
coordonnees des points de discretisation 1D
int N
nb de points du maillage 1D pour la vitesse et la temperature
DoubleVect U
DoubleVect T
inconnues fluides vitesse et temperature
DoubleVect Qvol
puissance volumique dans le fluide 1D
DoubleVect rho
DoubleVect mu
DoubleVect lambda
tableau des proprietes physiques du fluide a un instant donne
DoubleVect h_correlation
le coeff d'echange par correlation
Protected Attributes inherited from Echange_global_impose
bool phi_ext_lu_
Champ_front derivee_phi_ext_
Champ_front phi_ext_
Protected Attributes inherited from Echange_impose_base
Champ_front h_imp_
Protected Attributes inherited from Cond_lim_base
Champ_front le_champ_front
Ref_Zone_Cl_dis_base ma_zone_cl_dis
int modifier_val_imp
Detailed Description
Definition at line 35 of file Echange_contact_Correlation_VDF.h.
Constructor & Destructor Documentation
Echange_contact_Correlation_VDF()
Echange_contact_Correlation_VDF::Echange_contact_Correlation_VDF ()
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
~Echange_contact_Correlation_VDF()
Echange_contact_Correlation_VDF::~Echange_contact_Correlation_VDF ()
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
Member Function Documentation
calculer_CL()
void Echange_contact_Correlation_VDF::calculer_CL () protected
Calcule les CL a appliquer sur l'equation d'energie
Definition at line 442 of file Echange_contact_Correlation_VDF.cpp.
{
  const int ME=Process::me();
  const Joints& joints = zone_Cl_dis().zone().faces_joint();
  const int nb_voisins = joints.size();
  DoubleVect les_cl_envoyees(2);
  DoubleVect les_cl_recues(2);
  les_cl_envoyees(0) = T(1);
  les_cl_envoyees(1) = T(N-2);
  T_CL0=Tinf;
  T_CL1=Tsup;
  for (int i=0; i<nb_voisins; i++)
    {
      int mon_voisin = joints[i].PEvoisin();
      Cerr << " Echange_contact_Correlation_VDF::calculer_CL() A verifier pour envoi blocant" << finl;
      exit();
      envoyer(les_cl_envoyees,ME,mon_voisin,ME);
      recevoir(les_cl_recues,mon_voisin,ME,mon_voisin);
      if (tab_ech(mon_voisin,ME) == 1)
        {
          T_CL0 = 0.5*(les_cl_recues(1)+T(1));
          T(0) = T_CL0;
        }
      else if (tab_ech(mon_voisin,ME) == 0)
        {
          T_CL1 = 0.5*(les_cl_recues(0)+T(N-2));
          T(N-1) = T_CL1;
        }
      else
        {
          Cerr << "Erreur de communication entre les processeurs " <<ME<< " et " <<mon_voisin << finl;
          Cerr << "dans Echange_contact_Correlation_VDF::calculer_CL" << finl;
          if (Process::nproc()>1) Cerr << "Verifier que votre decoupage est bien en tranches selon l'axe du modele 1D." << finl;
          exit();
        }
    }
}
References Cerr, envoyer(), Process::exit(), Zone::faces_joint(), finl, Process::me(), N, Process::nproc(), recevoir(), liste::size(), T, T_CL0, T_CL1, tab_ech, Tinf, Tsup, Zone_Cl_dis_base::zone(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_coefficient_echange()
double Echange_contact_Correlation_VDF::calculer_coefficient_echange (int i) virtual
Calcule le coeff d echange suivant la correlation entree dans le jdd
Reimplemented in Echange_contact_Colburn_VDF, and Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 309 of file Echange_contact_Correlation_VDF.cpp.
{
  double Re,Pr;
  Re = std::fabs(getQh()*getDh()/getMu(i));
  Pr = getMu(i)*getCp()/getLambda(i);
  fct_Nu.setVar("Re",Re);
  fct_Nu.setVar("Pr",Pr);
  return fct_Nu.eval()*getLambda(i)/getDh();
}
References Parser_U::eval(), fct_Nu, getCp(), getDh(), getLambda(), getMu(), getQh(), and Parser_U::setVar().
Referenced by completer(), and mettre_a_jour().
calculer_h_mon_pb()
void Echange_contact_Correlation_VDF::calculer_h_mon_pb (DoubleTab & tab) protected
Calcule le coeff d echange local dans la maille solide.
Definition at line 197 of file Echange_contact_Correlation_VDF.cpp.
{
// forcement local
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const Milieu_base& mon_milieu = mon_eqn.milieu();
  const Zone_VDF& ma_zvdf = ref_cast(Zone_VDF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  Nom nom_bord=frontiere_dis().frontiere().le_nom();
  calculer_h_solide(tab,mon_eqn,ma_zvdf,ma_front_vf,mon_milieu);
}
References calculer_h_solide(), MorEqn::equation(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Frontiere::le_nom(), Equation_base::milieu(), ref_cast, valeur(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_h_solide()
void Echange_contact_Correlation_VDF::calculer_h_solide (DoubleTab & tab, const Equation_base & une_eqn, const Zone_VDF & zvdf_2, const Front_VF & front_vf, const Milieu_base & le_milieu) protected
< la conductivite est un Champ uniforme
Definition at line 740 of file Echange_contact_Correlation_VDF.cpp.
{
  DoubleVect e;
  const IntTab& face_voisins = zvdf_2.face_voisins();
  int i;
  int nb_comp = le_milieu.conductivite()->nb_comp();
  int ndeb = front_vf.num_premiere_face();
  int nfin = ndeb + front_vf.nb_faces();
  e.resize(front_vf.nb_faces());
  for (int face=ndeb; face<nfin; face++)
    e(face-ndeb) = zvdf_2.dist_norm_bord(face);
// Calcul de tab = 1/(e/lambda + 1/h_paroi) =1/(e/lambda+invhparoi)
  if(!sub_type(Champ_Uniforme,le_milieu.conductivite().valeur()))
    {
// Cerr << "raccord local homogene et conductivite non uniforme" << finl;
      const DoubleTab& tab_lambda = le_milieu.conductivite().valeurs();
      for (int face=ndeb; face<nfin; face++)
        {
          int elem = face_voisins(face,0);
          if (elem == -1)
            elem = face_voisins(face,1);
          for(i=0; i<nb_comp; i++)
            {
              assert(le_milieu.conductivite()(elem,i)!=0.);
              tab(face-ndeb,i) = tab_lambda(elem,i)/e(face-ndeb);
            }
        }
    }
  else  //!< la conductivite est un Champ uniforme
    {
      for (int face=ndeb; face<nfin; face++)
        {
          for(i=0; i<nb_comp; i++)
            {
              assert(le_milieu.conductivite()(0,i)!=0.);
              tab(face-ndeb,i) = le_milieu.conductivite()(0,i)/e(face-ndeb);
            }
        }
    }
}
References Milieu_base::conductivite(), Zone_VDF::dist_norm_bord(), Zone_VF::face_voisins(), Champ_Don::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTVect< _TYPE_ >::resize(), sub_type, Deriv_Champ_Don_base::valeur(), and Champ_Don::valeurs().
Referenced by calculer_h_mon_pb().
calculer_prop_physique()
void Echange_contact_Correlation_VDF::calculer_prop_physique () protected
Calcule rho, mu et lambda du fluide pour la temperature courante
Definition at line 293 of file Echange_contact_Correlation_VDF.cpp.
{
  for (int i=0; i<N; i++)
    {
      rho_T.setVar("T",T(i));
      mu_T.setVar("T",T(i));
      lambda_T.setVar("T",T(i));
      rho(i) = rho_T.eval();
      mu(i) = mu_T.eval();
      lambda(i) = lambda_T.eval();
    }
}
References Parser_U::eval(), lambda, lambda_T, mu, mu_T, N, rho, rho_T, Parser_U::setVar(), and T.
Referenced by completer(), and mettre_a_jour().
calculer_Q()
void Echange_contact_Correlation_VDF::calculer_Q () protected
Calcul du terme source de puissance volumique dans l'equation d'energie 1D fluide.
Definition at line 322 of file Echange_contact_Correlation_VDF.cpp.
{
  const Zone_VDF& ma_zvdf = ref_cast(Zone_VDF,zone_Cl_dis().zone_dis().valeur());
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const int ndeb = ma_front_vf.num_premiere_face();
  const int nb_faces_bord = ma_front_vf.nb_faces();
  const DoubleVect& surfaces = ma_zvdf.face_surfaces();
  const IntTab& face_voisins = ma_zvdf.face_voisins();
  Champ_Inc_base& inco = zone_Cl_dis().equation().inconnue();
  DoubleTab& Ts = inco.valeurs();
  DoubleTab& mon_h= h_imp_->valeurs();
  Qvol=0.;
  for(int iface=0; iface<nb_faces_bord; iface++)
    {
      int corresp = correspondance_solide_fluide(iface);
      int elem =  face_voisins(ndeb+iface,0);
      if(elem == -1)
        elem =  face_voisins(ndeb+iface,1);
      Qvol(corresp)+=mon_h(iface,0)*(Ts(elem)-T(corresp))*surfaces(ndeb+iface);
    }
  for (int i=0; i<N; i++)
    Qvol(i)/=vol(i);
}
References correspondance_solide_fluide, MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Echange_impose_base::h_imp_, Equation_base::inconnue(), N, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Qvol, ref_cast, T, valeur(), Champ_front::valeurs(), Champ_Inc_base::valeurs(), vol, and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_Tfluide()
void Echange_contact_Correlation_VDF::calculer_Tfluide () protected
Calcule la temperature 1D dans le fluide en resolvant la conservation de l'energie
< diagonale
< sous-diagonale
< sur-diagonale
< schema amont pour le transport
Definition at line 500 of file Echange_contact_Correlation_VDF.cpp.
{
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  const double dt = mon_eqn.schema_temps().pas_de_temps();
  DoubleVect ma(N); //!< diagonale
  DoubleVect mb(N-1); //!< sous-diagonale
  DoubleVect mc(N-1); //!< sur-diagonale
  DoubleVect sm(N);
  const int sgn = (debit>0) ? 1 : -1; //!< schema amont pour le transport
  ma(0) = 1.;
  ma(N-1) = 1.;
  sm(0) = T_CL0;
  sm(N-1) = T_CL1;
  mc(0) = 0.;
  mb(N-2) = 0.;
  int i;
  for (i=1; i<N-1; i++)
    {
      const double dtrhoCp = dt/rho(i)/Cp;
      const double dz1 = coord(i+1)-coord(i);
      const double dz2 = coord(i)-coord(i-1);
      const double l1 = 0.5*(lambda(i+1)+lambda(i));
      const double l2 = 0.5*(lambda(i)+lambda(i-1));
      ma(i)=1+dtrhoCp*(sgn*Cp*debit/dz1+2*(l1/dz1+l2/dz2)/(dz1+dz2));
      sm(i) = T(i)+dtrhoCp*Qvol(i);
      mc(i) = dtrhoCp*(0.5*(1-sgn)*Cp*debit/dz1-2*l1/dz1/(dz1+dz2));
      mb(i-1) = dtrhoCp*(-2*l2/dz2/(dz1+dz2));
      mb(i-1) += dtrhoCp*(-0.5*(1+sgn)*Cp*debit/dz1);
    }
  DoubleVect xx(N);
  xx=0.;
  Solv_TDMA::resoudre(ma,mb,mc,sm,xx,N);
  for (i=0; i<N; i++)
    T(i) = xx(i);
}
References coord, Cp, debit, MorEqn::equation(), lambda, N, Schema_Temps_base::pas_de_temps(), Qvol, Solv_TDMA::resoudre(), rho, Equation_base::schema_temps(), sgn, T, T_CL0, T_CL1, and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
calculer_Vitesse()
void Echange_contact_Correlation_VDF::calculer_Vitesse () protected
Calcule la vitesse par conservation de la masse
Definition at line 490 of file Echange_contact_Correlation_VDF.cpp.
{
  for (int i=0; i<N; i++)
    U(i) = debit/rho(i);
}
References debit, N, rho, and U.
Referenced by mettre_a_jour().
compatible_avec_eqn()
int Echange_contact_Correlation_VDF::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Verifie la compatibilite des conditions aux limites avec
l'equation passee en parametre.
Les conditions aux limites de type Ech_imp_base sont
compatibles avec des equations de type:
- Thermique
- indetermine.
Returns
int
Signification: valeur booleenne, 1 si compatible 0 sinon
Contraintes:
Reimplemented from Echange_impose_base.
Definition at line 730 of file Echange_contact_Correlation_VDF.cpp.
{
  if ( sub_type(Conduction, eqn) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
References Cond_lim_base::err_pas_compatible(), and sub_type.
completer()
void Echange_contact_Correlation_VDF::completer (void) override virtual
Complete et initialise les attributs de la classe
Reimplemented from Echange_global_impose.
Definition at line 213 of file Echange_contact_Correlation_VDF.cpp.
{
  Echange_impose_base::completer();
  trier_coord();
  T=std::min(Tinf,Tsup);
  calculer_prop_physique();
  if (T(0)==Tinf)
    U=debit/rho(0);
  else U = debit/rho(N-1);
  for (int i=0; i<N; i++)
    h_correlation(i) = calculer_coefficient_echange(i);
  DoubleTab& mon_h= h_imp_->valeurs();
// calculer_h_mon_pb(mon_h);
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const int nb_faces_bord = ma_front_vf.nb_faces();
  DoubleTab& Text_valeurs = T_ext().valeur().valeurs();
  Text_valeurs.resize(nb_faces_bord,1);
  mon_h.resize(nb_faces_bord,1);
  for (int ii=0; ii<nb_faces_bord; ii++)
    {
      mon_h(ii,0) = h_correlation(correspondance_solide_fluide(ii));
      Text_valeurs(ii,0) = T(correspondance_solide_fluide(ii));
    }
  init_tab_echange();
// Mise a jour car pas de dependance a des donnees d un autre probleme
// dans le cas de probleme couple
// Methode completer() peut etre a remplacer par methode initialiser()
  Equation_base& mon_eqn = zone_Cl_dis().equation();
  const double temps = mon_eqn.schema_temps().temps_courant();
  mettre_a_jour(temps);
}
References calculer_coefficient_echange(), calculer_prop_physique(), Cond_lim_base::completer(), correspondance_solide_fluide, debit, MorEqn::equation(), Cond_lim_base::frontiere_dis(), h_correlation, Echange_impose_base::h_imp_, init_tab_echange(), mettre_a_jour(), N, Front_VF::nb_faces(), ref_cast, TRUSTTab< _TYPE_ >::resize(), rho, Equation_base::schema_temps(), T, Echange_impose_base::T_ext(), Schema_Temps_base::temps_courant(), Tinf, trier_coord(), Tsup, U, Deriv_Champ_front_base::valeur(), Champ_front::valeurs(), Champ_front_base::valeurs(), and Cond_lim_base::zone_Cl_dis().
cree_instance()
Objet_U * Echange_contact_Correlation_VDF::cree_instance () static
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
duplique()
int Echange_contact_Correlation_VDF::duplique () const override virtual
Reimplemented from Echange_global_impose.
Reimplemented in Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
get_info()
const Type_info * Echange_contact_Correlation_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Echange_global_impose.
Reimplemented in Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
getCp()
double Echange_contact_Correlation_VDF::getCp () const inline
Definition at line 87 of file Echange_contact_Correlation_VDF.h.
  {
    return Cp;
  }
References Cp.
Referenced by calculer_coefficient_echange(), and Echange_contact_Colburn_VDF::calculer_coefficient_echange().
getDh()
double Echange_contact_Correlation_VDF::getDh () const inline
Definition at line 91 of file Echange_contact_Correlation_VDF.h.
  {
    return diam;
  }
References diam.
Referenced by calculer_coefficient_echange(), Echange_contact_Colburn_VDF::calculer_coefficient_echange(), and Echange_contact_VDF_Plaque_Flux_Cte::calculer_coefficient_echange().
getLambda()
double Echange_contact_Correlation_VDF::getLambda (int i) const inline
Definition at line 79 of file Echange_contact_Correlation_VDF.h.
  {
    return lambda(i);
  }
References lambda.
Referenced by calculer_coefficient_echange(), Echange_contact_Colburn_VDF::calculer_coefficient_echange(), and Echange_contact_VDF_Plaque_Flux_Cte::calculer_coefficient_echange().
getMu()
double Echange_contact_Correlation_VDF::getMu (int i) const inline
Definition at line 75 of file Echange_contact_Correlation_VDF.h.
  {
    return mu(i);
  }
References mu.
Referenced by calculer_coefficient_echange(), and Echange_contact_Colburn_VDF::calculer_coefficient_echange().
getQh()
double Echange_contact_Correlation_VDF::getQh () const inline
< le debit
Definition at line 95 of file Echange_contact_Correlation_VDF.h.
  {
    return debit;  //!< le debit
  }
References debit.
Referenced by calculer_coefficient_echange(), and Echange_contact_Colburn_VDF::calculer_coefficient_echange().
getRho()
double Echange_contact_Correlation_VDF::getRho (int i) const inline
Definition at line 83 of file Echange_contact_Correlation_VDF.h.
  {
    return rho(i);
  }
References rho.
getT()
double Echange_contact_Correlation_VDF::getT (int i) const inline
Definition at line 71 of file Echange_contact_Correlation_VDF.h.
  {
    return T(i);
  }
References T.
getU()
double Echange_contact_Correlation_VDF::getU (int i) const inline
Definition at line 67 of file Echange_contact_Correlation_VDF.h.
  {
    return U(i);
  }
References U.
imprimer()
void Echange_contact_Correlation_VDF::imprimer (double temps) const virtual
Imprime les resultats
Definition at line 809 of file Echange_contact_Correlation_VDF.cpp.
{
  const int ME = Process::me();
  const int nbproc = Process::nproc();
  if (nbproc>1)
    {
      envoyer(coord,ME,0,ME);
      envoyer(T,ME,0,ME);
      envoyer(U,ME,0,ME);
      envoyer(h_correlation,ME,0,ME);
      envoyer(rho,ME,0,ME);
      envoyer(mu,ME,0,ME);
      envoyer(lambda,ME,0,ME);
      envoyer(Qvol,ME,0,ME);
      envoyer(vol,ME,0,ME);
      if (je_suis_maitre())
        {
          Nom nom_bord=frontiere_dis().frontiere().le_nom();
          nom_bord+="_";
          nom_bord+=Nom(temps);
          nom_bord+=".dat";
          SFichier fic(nom_bord);
          fic.precision(zone_Cl_dis().equation().schema_temps().precision_impr());
          fic.setf(ios::scientific);
          double Qt=0.;
          fic << "# X                T                U                h                rho                mu                lambda                        Q[W]" << finl;
          for (int p=0; p<nbproc; p++)
            {
              DoubleVect coord_tmp;
              DoubleVect T_tmp;
              DoubleVect U_tmp;
              DoubleVect h_tmp;
              DoubleVect rho_tmp;
              DoubleVect mu_tmp;
              DoubleVect lambda_tmp;
              DoubleVect Qvol_tmp;
              DoubleVect vol_tmp;
              recevoir(coord_tmp,p,0,p);
              recevoir(T_tmp,p,0,p);
              recevoir(U_tmp,p,0,p);
              recevoir(h_tmp,p,0,p);
              recevoir(rho_tmp,p,0,p);
              recevoir(mu_tmp,p,0,p);
              recevoir(lambda_tmp,p,0,p);
              recevoir(Qvol_tmp,p,0,p);
              recevoir(vol_tmp,p,0,p);
              for (int i =0; i<coord_tmp.size(); i++)
                {
                  fic << coord_tmp(i) << " \t" << T_tmp(i) << " \t" << U_tmp(i) << " \t" << h_tmp(i) << " \t" << rho_tmp(i);
                  fic << " \t" << mu_tmp(i) << " \t" << lambda_tmp(i) << " \t" << Qvol_tmp(i)*vol_tmp(i) << finl;
                  Qt+=Qvol_tmp(i)*vol_tmp(i);
                }
            }
          fic << "# Q total[W] = " << Qt << finl;
          fic << finl;
        }
    }
  else
    {
      Nom nom_bord=frontiere_dis().frontiere().le_nom();
      nom_bord+="_";
      nom_bord+=Nom(temps);
      nom_bord+=".dat";
      SFichier fic(nom_bord);
      fic.precision(zone_Cl_dis().equation().schema_temps().precision_impr());
      fic.setf(ios::scientific);
      double Qt=0.;
      fic << "# X                 T                 U                 h                 rho                 mu                 lambda                  Q[W]" << finl;
      for (int i =0; i<N; i++)
        {
          fic << coord(i) << " \t" << T(i) << " \t" << U(i) << " \t" << h_correlation(i) << " \t" << rho(i);
          fic << " \t" << mu(i) << " \t" << lambda(i) << " \t" << Qvol(i)*vol(i) << finl;
          Qt+=Qvol(i)*vol(i);
        }
      fic << "# Q total[W] = " << Qt << finl;
      fic << finl;
    }
}
References coord, envoyer(), finl, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), h_correlation, Process::je_suis_maitre(), lambda, Frontiere::le_nom(), Process::me(), mu, N, Process::nproc(), Sortie_Fichier_base::precision(), Qvol, recevoir(), rho, Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_ >::size(), T, U, vol, and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
info()
const Type_info * Echange_contact_Correlation_VDF::info () static
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
init_tab_echange()
void Echange_contact_Correlation_VDF::init_tab_echange () protected
Initialise le tab tab_ech pour le parallele
< y_min
< y_max
< mon_voisin m'enverra le max
< mon_voisin m'enverra le min
Definition at line 256 of file Echange_contact_Correlation_VDF.cpp.
{
  DoubleVect y_envoye(2);
  DoubleVect y_recu(2);
  y_envoye(0) = coord(1); //!< y_min
  y_envoye(1) = coord(N-2); //!< y_max
  const Joints& joints = zone_Cl_dis().zone().faces_joint();
  const int nb_voisins = joints.size();
  const int ME=Process::me();
  tab_ech.resize(Process::nproc(),Process::nproc());
  tab_ech=-1;
  for (int i=0; i<nb_voisins; i++)
    {
      int mon_voisin = joints[i].PEvoisin();
      Cerr << " Echange_contact_Correlation_VDF::init_tab_echange() A verifier pour envoi blocant" << finl;
      exit();
      envoyer(y_envoye,ME,mon_voisin,ME);
      recevoir(y_recu,mon_voisin,ME,mon_voisin);
      if (y_recu(1)<coord(1))
        {
          tab_ech(mon_voisin,ME)=1; //!< mon_voisin m'enverra le max
        }
      else if (y_recu(0)>coord(N-2))
        {
          tab_ech(mon_voisin,ME)=0; //!< mon_voisin m'enverra le min
        }
    }
}
References Cerr, coord, envoyer(), Process::exit(), Zone::faces_joint(), finl, Process::me(), N, Process::nproc(), recevoir(), TRUSTTab< _TYPE_ >::resize(), liste::size(), tab_ech, Zone_Cl_dis_base::zone(), and Cond_lim_base::zone_Cl_dis().
Referenced by completer().
limpr()
int Echange_contact_Correlation_VDF::limpr (double temps_courant, double dt) const virtual
Teste si l'impression est demandee
Definition at line 788 of file Echange_contact_Correlation_VDF.cpp.
{
  const Schema_Temps_base& sch = zone_Cl_dis().equation().schema_temps();
// Test un peu tordu, mais ca fonctionne !!!! (CM 05/07/2007)
  if (dt_impr<=dt || ((sch.temps_max()<=temps_courant || sch.nb_pas_dt_max()<=(sch.nb_pas_dt()+1) || (temps_courant!=sch.temps_courant() && sch.nb_pas_dt()==0)) && dt_impr!=1e10))
    return 1;
  else
    {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      static const double epsilon = 1.e-9;
      double i, j;
      modf(temps_courant/dt_impr + epsilon, &i);
      modf((temps_courant-dt)/dt_impr + epsilon, &j);
      return ( i>j );
    }
}
References dt_impr, MorEqn::equation(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_max(), and Cond_lim_base::zone_Cl_dis().
Referenced by mettre_a_jour().
mettre_a_jour()
void Echange_contact_Correlation_VDF::mettre_a_jour (double temps) override virtual
Mise a jour de la vitesse, temperature fluide et coeff d'echange
< J'envoie T pour connaitre la dimension de son tableau
< J'ouvre le fichier de sauvgarde en lecture seule
< Je lis le premier mot "Temps" pour rien
< Je lis le deuxieme mot "=" pour rien
< Je lis le temps et je le mets dans temps_lu
< Je boucle sur le nombre de processeur
< Je recupere T pour connaitre la dimension de son tableau au niveau du processeur maitre.
< Je boucle sur le nombre de temperature a definir
< Je lis le mot "T(i)" pour rien
< Je lis le mot "=" pour rien
< Je lis la valeur de la temperature et je la mets dans Temperature_reprise
< J'egale la variable du calcul T(i) a Temperature_reprise
< J'envoie T_tmp a tous les processeurs
< Je recupere T=T_tmp au niveau de chaque processeur
< Je lis le premier mot "Temps" pour rien
< Je lis le deuxieme mot "=" pour rien
< Je lis le temps et je le mets dans temps_lu
< Je lis le mot "T(i)" pour rien
< Je lis le mot "=" pour rien
< Je lis la valeur de la temperature et je la mets dans Temperature_reprise
< J'egale la variable du calcul T(i) a Temperature_reprise
< J'envoie T au processeur maitre
< J'ouvre le fichier de sauvegarde en ecriture
< J'imprime le temps
< Je boucle sur le nombre de processeur
< Je recupere les temperature de chaque processeur
< J'imprime les temperatures dans le fichier de sauvegarde
Reimplemented from Echange_global_impose.
Definition at line 552 of file Echange_contact_Correlation_VDF.cpp.
{
// Nom des fichiers de sauvegarde
  Nom Fichier_sauv_nom=zone_Cl_dis().equation().probleme().le_nom();
  Fichier_sauv_nom+="_";
  Fichier_sauv_nom+=frontiere_dis().frontiere().le_nom();
  Fichier_sauv_nom+=".sauv";
// Operation de reprise du champ de temperature dans le fluide
  const int ME = Process::me();
  const int nbproc = Process::nproc();
  FILE *Fichier_sauv;
  if (Reprise_temperature==1)
    {
      if (nbproc>1)
        {
          Cerr << "A verifier pour envoi blocant" << finl;
          exit();
          envoyer(T,ME,0,ME);                                                                //!< J'envoie T pour connaitre la dimension de son tableau
          if (je_suis_maitre())
            {
              double temps_lu=0., Temperature_reprise=0.;
              char tmp_lu;
// int code;
              Fichier_sauv=fopen(Fichier_sauv_nom,"r");                                //!< J'ouvre le fichier de sauvgarde en lecture seule
              if (Fichier_sauv!=NULL)
                {
                  if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                                //!< Je lis le premier mot "Temps" pour rien
                  if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                                //!< Je lis le deuxieme mot "=" pour rien
                  if (!fscanf(Fichier_sauv,"%lf",&temps_lu)) exit();                                //!< Je lis le temps et je le mets dans temps_lu
                  if (temps_lu==temps)
                    {
                      for (int p=0; p<nbproc; p++)                                      //!< Je boucle sur le nombre de processeur
{
                          Cerr << "Reprise du champs de temperature (" << Fichier_sauv_nom << ") pour la correlation sur le processeur " << p << "...";
                          DoubleVect T_tmp;
                          recevoir(T_tmp,p,0,p);                                        //!< Je recupere T pour connaitre la dimension de son tableau au niveau du processeur maitre.
                          for (int i=0; i<T_tmp.size(); i++)                      //!< Je boucle sur le nombre de temperature a definir
{
                              if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                //!< Je lis le mot "T(i)" pour rien
                              if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                //!< Je lis le mot "=" pour rien
                              if (!fscanf(Fichier_sauv,"%lf",&Temperature_reprise)) exit();//!< Je lis la valeur de la temperature et je la mets dans Temperature_reprise
                              T_tmp(i) = Temperature_reprise;                        //!< J'egale la variable du calcul T(i) a Temperature_reprise
                            }
                          envoyer(T_tmp,0,p,0);                                        //!< J'envoie T_tmp a tous les processeurs
                          Cerr << "   OK!" << finl;
                        }
                      fclose(Fichier_sauv);
                    }
                  else
                    {
                      Cerr << "\nLe temps indique dans le fichier \""<< Fichier_sauv_nom << "\" "<< temps_lu << finl;
                      Cerr << "est different du temps de reprise du calcul "<< temps << " !!!" << finl << finl;
                      Cerr << "Vous ne pouvez pas faire de reprise pour la correlation. Supprimez" << finl;
                      Cerr << "dans la correlation le mot clef \"Reprise\". La phase transitoire" << finl;
                      Cerr << "du calcul sera fausse, mais l'etat stationnaire sera juste." << finl << finl;
                      fclose(Fichier_sauv);
                      exit();
                    }
                }
              else
                {
                  Cerr << "\nLa reprise ne peut pas etre faite : Le fichier \"" << Fichier_sauv_nom << "\" est manquant !!!" << finl << finl;
                  exit();
                }
            }
          recevoir(T,0,ME,0);                                                                //!< Je recupere T=T_tmp au niveau de chaque processeur
        }
      else
        {
          Fichier_sauv=fopen(Fichier_sauv_nom,"r");
          double temps_lu=0., Temperature_reprise=0.;
          char tmp_lu;
          if (Fichier_sauv!=NULL)
            {
              if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                        //!< Je lis le premier mot "Temps" pour rien
              if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                        //!< Je lis le deuxieme mot "=" pour rien
              if (!fscanf(Fichier_sauv,"%lf",&temps_lu)) exit();                        //!< Je lis le temps et je le mets dans temps_lu
              if (temps_lu==temps)
                {
                  Cerr << "Reprise du champs de temperature (" << Fichier_sauv_nom << ") pour la correlation...";
                  for (int i=0; i<N; i++)
                    {
                      if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                //!< Je lis le mot "T(i)" pour rien
                      if (!fscanf(Fichier_sauv,"%s",&tmp_lu)) exit();                //!< Je lis le mot "=" pour rien
                      if (!fscanf(Fichier_sauv,"%lf",&Temperature_reprise)) exit();//!< Je lis la valeur de la temperature et je la mets dans Temperature_reprise
                      T(i) = Temperature_reprise;                        //!< J'egale la variable du calcul T(i) a Temperature_reprise
                    }
                  fclose(Fichier_sauv);
                  Cerr << "   OK!" << finl;
                }
              else
                {
                  Cerr << "\nLe temps indique dans le fichier \""<< Fichier_sauv_nom << "\" "<< temps_lu << finl;
                  Cerr << "est different du temps de reprise du calcul "<< temps << " !!!" << finl << finl;
                  Cerr << "Vous ne pouvez pas faire de reprise pour la correlation. Supprimez" << finl;
                  Cerr << "dans la correlation le mot clef \"Reprise\". La phase transitoire" << finl;
                  Cerr << "du calcul sera fausse, mais l'etat stationnaire sera juste." << finl << finl;
                  fclose(Fichier_sauv);
                  exit();
                }
            }
          else
            {
              Cerr << "\nLa reprise ne peut pas etre faite : Le fichier \"" << Fichier_sauv_nom << "\" est manquant !!!" << finl << finl;
              exit();
            }
        }
      Reprise_temperature=0;
    }
  calculer_CL();
  calculer_prop_physique();
  calculer_Q();
  calculer_Vitesse();
  calculer_Tfluide();
  for (int i=0; i<N; i++)
    h_correlation(i) = calculer_coefficient_echange(i);
  DoubleTab& mon_h= h_imp_->valeurs();
  calculer_h_mon_pb(mon_h);
  const int taille=mon_h.dimension(0);
  DoubleTab& Text_valeurs = T_ext().valeur().valeurs();
  for (int ii=0; ii<taille; ii++)
    {
      mon_h(ii,0) = 1./(1./mon_h(ii,0)+1./h_correlation(correspondance_solide_fluide(ii)));
      Text_valeurs(ii,0) = T(correspondance_solide_fluide(ii));
    }
  const Equation_base& mon_eqn = zone_Cl_dis().equation();
  if (limpr(temps,mon_eqn.schema_temps().pas_de_temps())) imprimer(temps);
  Echange_global_impose::mettre_a_jour(temps);
// Operation de sauvegarde du champ de temperature dans le fluide en vue d'une reprise
  if (nbproc>1)
    {
      envoyer(T,ME,0,ME);                                                                //!< J'envoie T au processeur maitre
      if (je_suis_maitre())
        {
          Fichier_sauv=fopen(Fichier_sauv_nom,"w");                //!< J'ouvre le fichier de sauvegarde en ecriture
          fprintf(Fichier_sauv,"Temps\t=\t%f\n",temps);                                //!< J'imprime le temps
          int j=0;
          for (int p=0; p<nbproc; p++)                                              //!< Je boucle sur le nombre de processeur
            {
              DoubleVect T_tmp;
              recevoir(T_tmp,p,0,p);                                                //!< Je recupere les temperature de chaque processeur
              for (int i=0; i<T_tmp.size(); i++)
                {
                  fprintf(Fichier_sauv,"T(%i)\t=\t%f\n",(True_int)j,T_tmp(i));        //!< J'imprime les temperatures dans le fichier de sauvegarde
                  j=j+1;
                }
            }
          fclose(Fichier_sauv);
        }
    }
  else
    {
      Fichier_sauv=fopen(Fichier_sauv_nom,"w");
      fprintf(Fichier_sauv,"Temps\t=\t%f\n",temps);
      for (int i=0; i<N; i++)
        {
          fprintf(Fichier_sauv,"T(%i)\t=\t%f\n",(True_int)i,T(i));
        }
      fclose(Fichier_sauv);
    }
}
References calculer_CL(), calculer_coefficient_echange(), calculer_h_mon_pb(), calculer_prop_physique(), calculer_Q(), calculer_Tfluide(), calculer_Vitesse(), Cerr, correspondance_solide_fluide, TRUSTTab< _TYPE_ >::dimension(), envoyer(), MorEqn::equation(), Process::exit(), finl, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), h_correlation, Echange_impose_base::h_imp_, imprimer(), Process::je_suis_maitre(), Probleme_base::le_nom(), Frontiere::le_nom(), limpr(), Process::me(), Echange_global_impose::mettre_a_jour(), N, Process::nproc(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), recevoir(), Reprise_temperature, Equation_base::schema_temps(), TRUSTVect< _TYPE_ >::size(), T, Echange_impose_base::T_ext(), Deriv_Champ_front_base::valeur(), Champ_front::valeurs(), Champ_front_base::valeurs(), and Cond_lim_base::zone_Cl_dis().
Referenced by completer().
printOn()
Sortie & Echange_contact_Correlation_VDF::printOn (Sortie & s) const override protected virtual
Ecrit le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_global_impose.
Reimplemented in Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 32 of file Echange_contact_Correlation_VDF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Echange_contact_Correlation_VDF::readOn (Entree & s) override protected virtual
Simple appel a Echange_impose_base::readOn(Entree&)
Lit les specifications des conditions aux limites
a partir d'un flot d'entree.
Returns
Entree&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Echange_global_impose.
Reimplemented in Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 37 of file Echange_contact_Correlation_VDF.cpp.
{
// Motcles les_mots(12);
// Rajout Cyril MALOD (14/09/2006)
  Reprise_temperature=0;
  Motcles les_mots(13);
  {
    les_mots[0] = "dir";
    les_mots[1] = "Tinf";
    les_mots[2] = "Tsup";
    les_mots[3] = "lambda";
    les_mots[4] = "rho";
    les_mots[5] = "Cp";
    les_mots[6] = "dt_impr";
    les_mots[7] = "mu";
    les_mots[8] = "debit";
    les_mots[9] = "Dh";
    les_mots[10] = "volume";
    les_mots[11] = "Nu";
// Rajout Cyril MALOD (14/09/2006)
    les_mots[12] = "Reprise_correlation";
  }
  dt_impr = 1e10;
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> dir;
            if (dir<0 ||dir>2)
              {
                Cerr << "La direction doit etre 0, 1 ou 2 dans  " << que_suis_je() << finl;
                exit();
              }
            break;
          }
        case 1 :
          {
            is >> Tinf;
            break;
          }
        case 2 :
          {
            is >> Tsup;
            break;
          }
        case 3 :
          {
            Nom tmp;
            is >> tmp;
            lambda_T.setNbVar(1);
            lambda_T.setString(tmp);
            lambda_T.addVar("T");
            lambda_T.parseString();
            break;
          }
        case 4 :
          {
            Nom tmp;
            is >> tmp;
            rho_T.setNbVar(1);
            rho_T.setString(tmp);
            rho_T.addVar("T");
            rho_T.parseString();
            break;
          }
        case 5 :
          {
            is >> Cp;
            break;
          }
        case 6 :
          {
            is >> dt_impr;
            break;
          }
        case 7 :
          {
            Nom tmp;
            is >> tmp;
            mu_T.setNbVar(1);
            mu_T.setString(tmp);
            mu_T.addVar("T");
            mu_T.parseString();
            break;
          }
        case 8 :
          {
            is >> debit;
            break;
          }
        case 9 :
          {
            is >> diam;
            break;
          }
        case 10 :
          {
            Nom tmp;
            is >> tmp;
            fct_vol.setNbVar(2);
            fct_vol.setString(tmp);
            fct_vol.addVar("Dh");
            fct_vol.addVar("S");
            fct_vol.parseString();
            break;
          }
        case 11 :
          {
            Nom tmp;
            is >> tmp;
            fct_Nu.setNbVar(2);
            fct_Nu.setString(tmp);
            fct_Nu.addVar("Re");
            fct_Nu.addVar("Pr");
            fct_Nu.parseString();
            break;
          }
// Rajout Cyril MALOD (14/09/2006)
        case 12 :
          {
            Reprise_temperature=1;
            break;
          }
        default :
          {
            Cerr << "On ne comprend le mot : " << motlu << "dans " << que_suis_je() << finl;
            exit();
          }
        }
      is >> motlu;
    }
  T_ext().typer("Champ_front_fonc");
  T_ext()->fixer_nb_comp(1);
  h_imp_.typer("Champ_front_fonc");
  h_imp_->fixer_nb_comp(1);
  return is ;
}
References Parser_U::addVar(), Cerr, Cp, debit, diam, dir, dt_impr, Process::exit(), fct_Nu, fct_vol, finl, Echange_impose_base::h_imp_, lambda_T, mu_T, Parser_U::parseString(), Objet_U::que_suis_je(), Reprise_temperature, rho_T, Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), Echange_impose_base::T_ext(), Tinf, Tsup, and Deriv_::typer().
Referenced by Echange_contact_Colburn_VDF::readOn(), and Echange_contact_VDF_Plaque_Flux_Cte::readOn().
self_cast() [1/2]
const Echange_contact_Correlation_VDF & Echange_contact_Correlation_VDF::self_cast (const Objet_U & r) static
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
self_cast() [2/2]
Echange_contact_Correlation_VDF & Echange_contact_Correlation_VDF::self_cast (Objet_U & r) static
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
taille_memoire()
unsigned Echange_contact_Correlation_VDF::taille_memoire () const override virtual
Reimplemented from Echange_global_impose.
Reimplemented in Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 27 of file Echange_contact_Correlation_VDF.cpp.
trier_coord()
void Echange_contact_Correlation_VDF::trier_coord () protected
< on rajoute les noeuds des bords
< ne sert pas
< le premier point du maillage
< le dernier point du maillage
< ne sert pas mais evite une division par zero dans le calcul de Qvol.
Definition at line 350 of file Echange_contact_Correlation_VDF.cpp.
{
  const Zone_VDF& ma_zvdf = ref_cast(Zone_VDF,zone_Cl_dis().zone_dis().valeur());
  const DoubleVect& surfaces = ma_zvdf.face_surfaces();
  const Front_VF& ma_front_vf = ref_cast(Front_VF,frontiere_dis());
  const int ndeb = ma_front_vf.num_premiere_face();
  const int nb_faces_bord = ma_front_vf.nb_faces();
  IntVect face_triee(nb_faces_bord);
  const DoubleTab& xv = ma_zvdf.xv();
  int i, j ,tmp;
// On trie les faces par coordonnees croissante (selon la coordonnee correspondante a la direction du tube)
  if (nb_faces_bord>1)
    {
      for(i=0; i<nb_faces_bord; i++)
        face_triee(i) = ndeb+i;
      for(i=1; i<nb_faces_bord; i++)
        {
          j=i-1;
          tmp = face_triee(i);
          while ( j>=0 && xv(face_triee(j),dir)>xv(tmp,dir))
            {
              face_triee(j+1) = face_triee(j);
              j--;
            }
          face_triee(j+1) = tmp;
        }
    }
// On determine le nb de mailles 1D dans le fluide fictif
// et on remplit les correspondances elements solides -> elements fluides
  correspondance_solide_fluide.resize(nb_faces_bord);
  N=3; //!< on rajoute les noeuds des bords
  correspondance_solide_fluide(face_triee(0)-ndeb) = 1;
  for(i=1; i<nb_faces_bord; i++)
    {
      if (xv(face_triee(i),dir) != xv(face_triee(i-1),dir))
        N++;
      correspondance_solide_fluide(face_triee(i)-ndeb) = N-2;
    }
  U.resize(N);
  T.resize(N);
  Qvol.resize(N);
  rho.resize(N);
  mu.resize(N);
  lambda.resize(N);
  vol.resize(N);
  coord.resize(N);
  h_correlation.resize(N);
// calcul des volumes des tranches
  DoubleVect surf(N);
  surf=0.;
  vol=0.;
  surf(0) = surf(N-1) = 0.; //!< ne sert pas
  for(int iface=0; iface<nb_faces_bord; iface++)
    {
      int corresp = correspondance_solide_fluide(iface);
      surf(corresp)+=surfaces(ndeb+iface);
      coord(corresp) = xv(ndeb+iface,dir);
    }
  coord(0) = coord(1)-0.5*(coord(2)-coord(1)); //!< le premier point du maillage
  coord(N-1) = coord(N-2)+0.5*(coord(N-2)-coord(N-3)); //!< le dernier point du maillage
  for (i=1; i<N-1; i++)
    {
      vol(i)=volume(surf(i),diam);
    }
  vol(0) = vol(N-1) = 1.; //!< ne sert pas mais evite une division par zero dans le calcul de Qvol.
}
References coord, correspondance_solide_fluide, diam, dir, Zone_VF::face_surfaces(), Cond_lim_base::frontiere_dis(), h_correlation, lambda, mu, N, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Qvol, ref_cast, TRUSTVect< _TYPE_ >::resize(), rho, T, U, valeur(), vol, volume(), Zone_VF::xv(), and Cond_lim_base::zone_Cl_dis().
Referenced by completer().
volume()
double Echange_contact_Correlation_VDF::volume (double s, double d) virtual
Calcule le volume d'une tranche de la section de surface laterale s et de diametre hydraulique d.
Reimplemented in Echange_contact_Colburn_VDF, and Echange_contact_VDF_Plaque_Flux_Cte.
Definition at line 430 of file Echange_contact_Correlation_VDF.cpp.
{
  fct_vol.setVar("Dh",d);
  fct_vol.setVar("S",s);
  return fct_vol.eval();
}
References Parser_U::eval(), fct_vol, and Parser_U::setVar().
Referenced by trier_coord().
Member Data Documentation
autre_h
DoubleTab Echange_contact_Correlation_VDF::autre_h protected
Definition at line 113 of file Echange_contact_Correlation_VDF.h.
coord
DoubleVect Echange_contact_Correlation_VDF::coord protected
coordonnees des points de discretisation 1D
Definition at line 133 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Tfluide(), imprimer(), init_tab_echange(), and trier_coord().
correspondance_solide_fluide
IntVect Echange_contact_Correlation_VDF::correspondance_solide_fluide protected
Definition at line 112 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Q(), completer(), mettre_a_jour(), and trier_coord().
Cp
double Echange_contact_Correlation_VDF::Cp protected
Definition at line 128 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Tfluide(), getCp(), and readOn().
debit
double Echange_contact_Correlation_VDF::debit protected
Definition at line 129 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Tfluide(), calculer_Vitesse(), completer(), getQh(), and readOn().
diam
double Echange_contact_Correlation_VDF::diam protected
diametre hydraulique
Definition at line 131 of file Echange_contact_Correlation_VDF.h.
Referenced by getDh(), readOn(), and trier_coord().
dir
int Echange_contact_Correlation_VDF::dir protected
Direction du cylindre.
Definition at line 121 of file Echange_contact_Correlation_VDF.h.
Referenced by readOn(), and trier_coord().
dt_impr
double Echange_contact_Correlation_VDF::dt_impr protected
Definition at line 127 of file Echange_contact_Correlation_VDF.h.
Referenced by limpr(), and readOn().
fct_Nu
Parser_U Echange_contact_Correlation_VDF::fct_Nu protected
Definition at line 125 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_coefficient_echange(), and readOn().
fct_vol
Parser_U Echange_contact_Correlation_VDF::fct_vol protected
Definition at line 126 of file Echange_contact_Correlation_VDF.h.
Referenced by readOn(), and volume().
h_correlation
DoubleVect Echange_contact_Correlation_VDF::h_correlation protected
le coeff d'echange par correlation
Definition at line 139 of file Echange_contact_Correlation_VDF.h.
Referenced by completer(), imprimer(), mettre_a_jour(), and trier_coord().
info_obj
const Type_info Echange_contact_Correlation_VDF::info_obj static
Definition at line 38 of file Echange_contact_Correlation_VDF.h.
lambda
DoubleVect Echange_contact_Correlation_VDF::lambda protected
tableau des proprietes physiques du fluide a un instant donne
Definition at line 138 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_prop_physique(), calculer_Tfluide(), getLambda(), imprimer(), and trier_coord().
lambda_T
Parser_U Echange_contact_Correlation_VDF::lambda_T protected
Definition at line 122 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_prop_physique(), and readOn().
mu
DoubleVect Echange_contact_Correlation_VDF::mu protected
Definition at line 138 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_prop_physique(), getMu(), imprimer(), and trier_coord().
mu_T
Parser_U Echange_contact_Correlation_VDF::mu_T protected
Definition at line 123 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_prop_physique(), and readOn().
N
int Echange_contact_Correlation_VDF::N protected
nb de points du maillage 1D pour la vitesse et la temperature
Definition at line 135 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), calculer_prop_physique(), calculer_Q(), calculer_Tfluide(), calculer_Vitesse(), completer(), imprimer(), init_tab_echange(), mettre_a_jour(), and trier_coord().
Qvol
DoubleVect Echange_contact_Correlation_VDF::Qvol protected
puissance volumique dans le fluide 1D
Definition at line 137 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Q(), calculer_Tfluide(), imprimer(), and trier_coord().
Reprise_temperature
int Echange_contact_Correlation_VDF::Reprise_temperature protected
Definition at line 114 of file Echange_contact_Correlation_VDF.h.
Referenced by mettre_a_jour(), and readOn().
rho
DoubleVect Echange_contact_Correlation_VDF::rho protected
Definition at line 138 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_prop_physique(), calculer_Tfluide(), calculer_Vitesse(), completer(), getRho(), imprimer(), and trier_coord().
rho_T
Parser_U Echange_contact_Correlation_VDF::rho_T protected
Definition at line 124 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_prop_physique(), and readOn().
T
DoubleVect Echange_contact_Correlation_VDF::T protected
inconnues fluides vitesse et temperature
Definition at line 136 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), calculer_prop_physique(), calculer_Q(), calculer_Tfluide(), completer(), getT(), imprimer(), mettre_a_jour(), and trier_coord().
T_CL0
double Echange_contact_Correlation_VDF::T_CL0 protected
Definition at line 120 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), and calculer_Tfluide().
T_CL1
double Echange_contact_Correlation_VDF::T_CL1 protected
CL sur le domaine. En seq. = Tinf et Tsup ; En parallele = Tvoisin.
Definition at line 120 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), and calculer_Tfluide().
tab_ech
DoubleTab Echange_contact_Correlation_VDF::tab_ech protected
Definition at line 117 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), and init_tab_echange().
Tinf
double Echange_contact_Correlation_VDF::Tinf protected
Definition at line 119 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), completer(), and readOn().
Tsup
double Echange_contact_Correlation_VDF::Tsup protected
Temperature entree, sortie.
Definition at line 119 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_CL(), completer(), and readOn().
U
DoubleVect Echange_contact_Correlation_VDF::U protected
Definition at line 136 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Vitesse(), completer(), getU(), imprimer(), and trier_coord().
vol
DoubleVect Echange_contact_Correlation_VDF::vol protected
volumes des tranches Sdz du volume suivant la direction de l'ecoulement
Definition at line 132 of file Echange_contact_Correlation_VDF.h.
Referenced by calculer_Q(), imprimer(), and trier_coord().
The documentation for this class was generated from the following files:
src/VDF/Cond_Lim/Echange_contact_Correlation_VDF.h
src/VDF/Cond_Lim/Echange_contact_Correlation_VDF.cpp