TRUST: Source_Dirac_VDF_Elem Class Reference
Source_Dirac_VDF_Elem Class Reference
#include <Source_Dirac_VDF_Elem.h>
Public Member Functions
~Source_Dirac_VDF_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Source_Dirac_VDF_Elem ()
void associer_pb (const Probleme_base &)
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void mettre_a_jour (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_Dirac_VDF_Elem & self_cast (Objet_U &)
static const
Source_Dirac_VDF_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Attributes
DoubleVect point
int nb_dirac
Detailed Description
Definition at line 51 of file Source_Dirac_VDF_Elem.h.
Constructor & Destructor Documentation
Source_Dirac_VDF_Elem::~Source_Dirac_VDF_Elem ()
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
Source_Dirac_VDF_Elem::Source_Dirac_VDF_Elem () [inline]
Definition at line 74 of file Source_Dirac_VDF_Elem.h.
                                                    :
  Terme_Puissance_Thermique_VDF_base(It_Sou_VDF_Elem(Eval_Dirac_VDF_Elem)())
{
}
Member Function Documentation
void Source_Dirac_VDF_Elem::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 66 of file Source_Dirac_VDF_Elem.cpp.
References Eval_Dirac_VDF_Elem::associer_champs(), DoubleVect::copy(), Iterateur_Source_VDF::evaluateur(), Terme_Source_VDF_base::iter, Terme_Puissance_Thermique::la_puissance, Eval_Dirac_VDF_Elem::le_point, point, and Terme_Puissance_Thermique::preparer_source().
{
  preparer_source(pb);
  Eval_Dirac_VDF_Elem& eval_puis = (Eval_Dirac_VDF_Elem&) iter.evaluateur();
  eval_puis.associer_champs(la_puissance);
  eval_puis.le_point.copy(point);
}
void Source_Dirac_VDF_Elem::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 47 of file Source_Dirac_VDF_Elem.cpp.
References Eval_Dirac_VDF_Elem::associer_nb_elem_dirac(), Evaluateur_Source_VDF::associer_zones(), Elem_geom::contient(), Iterateur_Source_VDF::evaluateur(), Terme_Source_VDF_base::iter, nb_dirac, Zone_dis_base::nb_elem(), point, test(), Zone::type_elem(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Zone_dis_base::zone().
{
// Cout << "<<<<<<<< Dans Source_Dirac_VDF_Elem::associer_zones " << finl;
  Terme_Puissance_Thermique_VDF_base::associer_zones(zone_dis,zone_cl_dis);
  Eval_Dirac_VDF_Elem& eval_grav = (Eval_Dirac_VDF_Elem&) iter.evaluateur();
  eval_grav.associer_zones(zone_dis.valeur(),zone_cl_dis.valeur());
  int nb_elem = zone_dis.valeur().nb_elem();
  const Zone& ma_zone = zone_dis.valeur().zone();
  nb_dirac=0;
  for (int elem=0; elem<nb_elem; elem++)
    {
      int test =  ma_zone.type_elem().contient(point,elem) ;
      if (test == 1) nb_dirac++;
    }
  eval_grav.associer_nb_elem_dirac(nb_dirac);
}
Objet_U * Source_Dirac_VDF_Elem::cree_instance () [static]
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
int Source_Dirac_VDF_Elem::duplique () const [virtual]
Implements Terme_Puissance_Thermique_VDF_base.
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
const Type_info * Source_Dirac_VDF_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
const Type_info * Source_Dirac_VDF_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
void Source_Dirac_VDF_Elem::mettre_a_jour (double temps) [inline]
Reimplemented from Terme_Puissance_Thermique.
Definition at line 60 of file Source_Dirac_VDF_Elem.h.
References Terme_Puissance_Thermique::mettre_a_jour().
  {
    Terme_Puissance_Thermique::mettre_a_jour(temps);
  }
Sortie & Source_Dirac_VDF_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 30 of file Source_Dirac_VDF_Elem.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Source_Dirac_VDF_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 35 of file Source_Dirac_VDF_Elem.cpp.
References Objet_U::dimension, point, DoubleVect::resize(), Source_base::set_description(), and Source_base::set_fichier().
{
  point = 0;
  point.resize(dimension);
  is >> point;
  Terme_Puissance_Thermique_VDF_base::readOn(is);
  set_fichier("Puissance_Thermique");
  set_description("Heat power release = nb_dirac*P*V [W]");
  return is;
}
Source_Dirac_VDF_Elem & Source_Dirac_VDF_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
const Source_Dirac_VDF_Elem & Source_Dirac_VDF_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
unsigned Source_Dirac_VDF_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Source_Dirac_VDF_Elem.cpp.
Member Data Documentation
const Type_info Source_Dirac_VDF_Elem::info_obj [static]
Reimplemented from Terme_Puissance_Thermique_VDF_base.
Definition at line 53 of file Source_Dirac_VDF_Elem.h.
int Source_Dirac_VDF_Elem::nb_dirac [protected]
Definition at line 67 of file Source_Dirac_VDF_Elem.h.
Referenced by associer_zones().
DoubleVect Source_Dirac_VDF_Elem::point [protected]
Definition at line 66 of file Source_Dirac_VDF_Elem.h.
Referenced by associer_pb(), associer_zones(), and readOn().
The documentation for this class was generated from the following files:
src/VDF/Sources/Source_Dirac_VDF_Elem.h
src/VDF/Sources/Source_Dirac_VDF_Elem.cpp