TRUST: Solv_TDMA Class Reference
Solv_TDMA Class Reference
#include <Solv_TDMA.h>
Static Public Member Functions
static void resoudre (const DoubleVect &ma, const DoubleVect &mb, const DoubleVect &mc, const DoubleVect &sm, DoubleVect &vi, int M)
Detailed Description
Definition at line 21 of file Solv_TDMA.h.
Member Function Documentation
resoudre()
void Solv_TDMA::resoudre (const DoubleVect & ma, const DoubleVect & mb, const DoubleVect & mc, const DoubleVect & sm, DoubleVect & vi, int M) static
Definition at line 19 of file Solv_TDMA.cpp.
{
  DoubleVect malpha, mbeta; //2 vecteurs intermediares
  DoubleVect my; //vecteur solution du systeme L.y=F
  int i;
  malpha.resize(M);
  mbeta.resize(M);
  my.resize(M);
// L'algorithme de Thomas (TDMA) repose sur la decomposition LU de la matrice
// tridiagonale a inverser. Soit A.x = y le systeme lineaire a inverser avec A = LU.
// On resoud d'abord par descente le syteme L.z = y avec z = U.x et on resoud ensuite
// par remontee le systeme U.x = z.
// Les 3 diagonales de la matrice sont chacune conservees sous forme de vecteur
// ma : diagonale principale ; mb : diagonale secondaire inferieure
// mc : diagonale secondaire superieure
// M est l'ordre de la matrice A
// La matrice L est composee d'une diagonale principale (malpha) et d'une diagonale
// secondaire inferieure (mb). La matrice U est composee d'une diagonale principale
// (dont tous les elements sont egaux a 1) et d'une diagonale secondaire superieure
// (mbeta).
// Resolution correcte d'un systeme lineaire 3*3 antisymetrique, le 23.05.2003
// Remplissage de malpha et mbeta
  malpha(0) = ma(0);
  mbeta(0) = mc(0)/ma(0);
  for (i = 1 ; i<M-1 ; i++)
    {
      malpha(i) = ma(i) - mb(i-1)*mbeta(i-1);
      mbeta(i) = mc(i)/malpha(i);
    }
  malpha(M-1) = ma(M-1) - mb(M-2)*mbeta(M-2);
// Resolution du premier systeme par descente
  my(0) = sm(0)/malpha(0);
  for (i = 1 ; i<M ; i++)
    my(i) = (sm(i)-mb(i-1)*my(i-1))/malpha(i);
// Resolution du premier systeme par remontee
  vi(M-1) = my(M-1);
  for (i = M-2 ; i>=0 ; i--)
    vi(i) = my(i) - mbeta(i)*vi(i+1);
}
References TRUSTVect< _TYPE_ >::resize().
Referenced by Echange_contact_Correlation_VDF::calculer_Tfluide(), and Echange_contact_Correlation_VEF::calculer_Tfluide().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_TDMA.h
src/Kernel/Math/SolvSys/Solv_TDMA.cpp