TRUST: System Class Reference
System Class Reference
#include <System.h>
Public Member Functions
System ()
~System ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static System & self_cast (Objet_U &)
static const System & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 30 of file System.h.
Constructor & Destructor Documentation
System::System ()
Definition at line 25 of file System.cpp.
System::~System ()
Definition at line 25 of file System.cpp.
Member Function Documentation
Objet_U * System::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
int System::duplique () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
const Type_info * System::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
const Type_info * System::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
Entree & System::interpreter (Entree & is) [virtual]
Reimplemented from Interprete.
Definition at line 42 of file System.cpp.
References Process::barrier(), Cerr, Process::exit(), finl, Entree::good(), Process::je_suis_maitre(), and Nom::prefix().
{
  Nom instruction,suite;
  is >> instruction;
  if (instruction[0]!='"')
    {
      Cerr<<"In System, instruction should begin by \""<<finl;
      Cerr<<"instruction beginning "<<instruction;
      exit();
    }
  instruction.suffix("\"");
  while(instruction[instruction.longueur()-2]!='"')
    {
      is >> suite;
      assert(is.good());
      instruction+=" ";
      instruction+=suite;
    }
  instruction.prefix("\"");
  if (je_suis_maitre())
    {
      Cerr<<"Shell command executed: " << instruction<<finl;
      int error = system(instruction);
      if (error)
        {
          Cerr << "The shell command returns an error: " << error << finl;
          Cerr << "Check your data file." << finl;
          exit();
        }
    }
  barrier();
  return is;
}
Sortie & System::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 30 of file System.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & System::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 35 of file System.cpp.
{
//
//
  return is;
}
System & System::self_cast (Objet_U & r) [static]
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
const System & System::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
unsigned System::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 25 of file System.cpp.
Member Data Documentation
const Type_info System::info_obj [static]
Reimplemented from Interprete.
Definition at line 33 of file System.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/System.h
src/Kernel/Utilitaires/System.cpp