TRUST: Decouper_Bord_coincident Class Reference
Decouper_Bord_coincident Class Reference
#include <Decouper_Bord_coincident.h>
Public Member Functions
Decouper_Bord_coincident ()
~Decouper_Bord_coincident ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
void Decouper_Bord_coincident_ (Zone &)
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Decouper_Bord_coincident & self_cast (Objet_U &)
static const Decouper_Bord_coincident & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Nom nom_bord
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 35 of file Decouper_Bord_coincident.h.
Constructor & Destructor Documentation
Decouper_Bord_coincident()
Decouper_Bord_coincident::Decouper_Bord_coincident ()
Definition at line 21 of file Decouper_Bord_coincident.cpp.
~Decouper_Bord_coincident()
Decouper_Bord_coincident::~Decouper_Bord_coincident ()
Definition at line 21 of file Decouper_Bord_coincident.cpp.
Member Function Documentation
cree_instance()
Objet_U * Decouper_Bord_coincident::cree_instance () static
Definition at line 21 of file Decouper_Bord_coincident.cpp.
Decouper_Bord_coincident_()
void Decouper_Bord_coincident::Decouper_Bord_coincident_ (Zone & zone)
< tableau sur-dimensionne
< face de bord a ne pas decouper
< face de bord a decouper
Definition at line 53 of file Decouper_Bord_coincident.cpp.
{
  if  (zone.type_elem()->que_suis_je() == "Triangle")
// ||(zone.type_elem()->que_suis_je() == "Tetraedre"))
    {
      Nom fichier="connectivity_failed_";
      fichier+=nom_bord;
      EFichier fic(fichier);
      if(!fic.good())
        {
          Cerr << "The file " << fichier << " was not found !!! " << finl;
          exit();
        }
      Domaine& dom = zone.domaine();
      const DoubleTab& xs = dom.coord_sommets();
      IntTab& les_elems = zone.les_elems();
      int oldsz = les_elems.dimension(0);
      int oldnbsom = zone.nb_som();
      IntTab new_elems(3*oldsz, dimension+1); //!< tableau sur-dimensionne
// Construction de l'Octree sur la grille VEF de base
      zone.construit_octree();
// On dimensionne une premiere fois le tableau des sommets
// puis on redimensionnera seulement a la fin par la dimension exacte
      Scatter::uninit_sequential_domain(dom);
      DoubleTab& sommets_dom = dom.les_sommets();
// int dim_som_old=sommets_dom.dimension(0); // dim_som_old = oldnbsom
      sommets_dom.resize(2*oldnbsom,dimension);
// On initialise new_elem sur la base du maillage non redecoupe :
      for(int elem=0; elem<oldsz; elem++)
        {
          for(int k=0; k<dimension+1; k++)
            new_elems(elem, k) = les_elems(elem,k);
          mettre_a_jour_sous_zone(zone,elem,oldsz,0);
        }
      int face_oldsz, face_newsz, fac, indice;
      fic >> face_oldsz;
      fic >> face_newsz;
      IntTab new_faces_racc(face_newsz, dimension);
// IntTab new_faces_int(3*face_oldsz, dimension); // tableau sur-dimensionne
      int j,elem;
      int j0=0,j1=0,j2=0;
      int som1=0,som2=0;
// compteurs
      int indice_new_som = oldnbsom;
      int i=0;
// int ii=0;
      fic >> indice ;
      while (indice!=-1)
        {
          if (!fic.good())
            {
              Cerr<<"Pb with "<<fichier <<" in Decouper_Bord_coincident::interpreter_"<<finl;
              Cerr<<" eof ???"<<finl;
              exit();
            }
          fic >> fac >> elem >> j ;
          if(j==0)
            {
              j0=0;
              j1=1;
              j2=2;
            }
          else if(j==1)
            {
              j0=1;
              j1=0;
              j2=2;
            }
          else if(j==2)
            {
              j0=2;
              j1=0;
              j2=1;
            }
          else
            {
              Cerr << " problem with the index j " << finl;
              exit();
            }
          if(indice==1) //!< face de bord a ne pas decouper
            {
              new_faces_racc(fac,0) = les_elems(elem,j1);
              new_faces_racc(fac,1) = les_elems(elem,j2);
            }
          else if(indice==2) //!< face de bord a decouper
            {
              som1=les_elems(elem,j1);
              som2=les_elems(elem,j2);
              sommets_dom(indice_new_som,0) = 0.5*(xs(som1,0)+xs(som2,0));
              sommets_dom(indice_new_som,1) = 0.5*(xs(som1,1)+xs(som2,1));
//
              new_elems(elem, 0) = les_elems(elem,j0);
              new_elems(elem, 1) = les_elems(elem,j1);
              new_elems(elem, 2) = indice_new_som;
              new_faces_racc(fac,0) = les_elems(elem,j1);
              new_faces_racc(fac,1) = indice_new_som;
//
              new_elems(i+oldsz, 0) = les_elems(elem,j0);
              new_elems(i+oldsz, 1) = les_elems(elem,j2);
              new_elems(i+oldsz, 2) = indice_new_som;
              new_faces_racc(i+face_oldsz,0) = les_elems(elem,2);
              new_faces_racc(i+face_oldsz,1) = indice_new_som;
              indice_new_som++;
              i++;
//
// new_faces_int(ii,0) = les_elems(elem,j0);
// new_faces_int(ii,1) = indice_new_som;
//
// ii++;
            }
          else
            {
              Cerr << "problem with the partition of the element to realize" << finl;
              Cerr << "We do not know how to split in " << indice << finl;
              exit();
            }
          fic >> indice ;
        }//while
      Cerr << " Number of boundary face (generated) " << i+face_oldsz << finl;
      Cerr << " Number of boundary face (planned)  " << face_newsz << finl;
      if( (i+face_oldsz) != face_newsz)
        {
          Cerr << " Concern in the reconstruction " << finl;
          exit();
        }
      sommets_dom.resize(indice_new_som,dimension);
      new_elems.resize(i+oldsz,dimension+1);
      les_elems.ref(new_elems);
// new_faces_int.resize(ii,dimension);
// Reconstruction de l'octree
      Cerr << "Splitting performs ..." << finl;
      zone.invalide_octree();
      if(dimension==2)
        zone.typer("Triangle");
      else
        zone.typer("Tetraedre");
      Cerr << "  Reconstruction of the Octree" << finl;
      zone.construit_octree();
      Cerr << "  Octree rebuilt" << finl;
      {
// Les Raccords
        Cerr << "Splitting of connections" << finl;
        LIST_CURSEUR(Raccord) curseur(zone.faces_raccord());;;
        while(curseur)
          {
            if(curseur.valeur()->le_nom()==nom_bord)
              {
                Faces& les_faces=curseur.valeur()->faces();
                if(dimension==2)
                  les_faces.typer(Faces::segment_2D);
                else
                  les_faces.typer(Faces::triangle_3D);
                IntTab& sommets=les_faces.les_sommets();
                assert(sommets.dimension(1)==dimension);
                sommets.ref(new_faces_racc);
                les_faces.voisins().resize(face_newsz, 2);
                les_faces.voisins()=-1;
              }
            ++curseur;
          }
      }
      Scatter::init_sequential_domain(dom);
      /*
        {
        // Les Faces internes
        Cerr << "Splitting of internal faces" << finl;
        LIST_CURSEUR(Faces_Interne) curseur(zone.faces_int());;;
        while(curseur)
        {
        Faces& les_faces=curseur->faces();
        if(dimension==2)
        les_faces.typer(Faces::segment_2D);
        else
        les_faces.typer(Faces::triangle_3D);
        IntTab& sommets=les_faces.les_sommets();
        int nb_faces=sommets.dimension(0);
        assert(sommets.dimension(1)==dimension);
        IntTab new_faces(nb_faces+ii, dimension);
        for(int j=0; j<nb_faces; j++)
        for(int k=0; k<dimension; k++)
        new_faces(j,k)=sommets(j,k);
        for(int j=0; j<ii; j++)
        for(int k=0; k<dimension; k++)
        new_faces(j+nb_faces,k)=new_faces_int(j,k);
        sommets.ref(new_faces);
        les_faces.voisins().resize(nb_faces+ii, 2);
        les_faces.voisins()=-1;
        }
        }
      */
      Cerr<<"END of Decouper_Bord_coincident..."<<finl;
      Cerr<<"  1 NbElem="<<zone.les_elems().dimension(0)<<"  NbSom="<<zone.nb_som()<<finl;
    }
  else
    {
      Cerr << "We do not yet know how to Decouper_Bord_coincident the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
    }
}
References Cerr, Zone::construit_octree(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Process::exit(), Zone::faces_raccord(), finl, Entree_Fichier_base::good(), Scatter::init_sequential_domain(), Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), LIST_CURSEUR, Interprete_geometrique_base::mettre_a_jour_sous_zone(), Zone::nb_som(), nom_bord, Objet_U::que_suis_je(), TRUSTTab< _TYPE_ >::ref(), TRUSTTab< _TYPE_ >::resize(), Faces::segment_2D, Faces::triangle_3D, Zone::type_elem(), Faces::typer(), Zone::typer(), Scatter::uninit_sequential_domain(), and Faces::voisins().
Referenced by interpreter_().
duplique()
int Decouper_Bord_coincident::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Decouper_Bord_coincident.cpp.
get_info()
const Type_info * Decouper_Bord_coincident::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Decouper_Bord_coincident.cpp.
info()
const Type_info * Decouper_Bord_coincident::info () static
Definition at line 21 of file Decouper_Bord_coincident.cpp.
interpreter_()
Entree & Decouper_Bord_coincident::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base.
Definition at line 33 of file Decouper_Bord_coincident.cpp.
{
  if(dimension==3)
    {
      Cerr << "We do not know how to split in 3D" << finl;
      exit();
    }
  associer_domaine(is);
  is >> nom_bord;
  for(int i=0; i<domaine().nb_zones() ; i++)
    {
      Decouper_Bord_coincident_(domaine().zone(i));
    }
  Cerr << "Decouper_Bord_coincident... OK" << finl;
  return is;
}
References Interprete_geometrique_base::associer_domaine(), Cerr, Decouper_Bord_coincident_(), Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), finl, Domaine::nb_zones(), and nom_bord.
printOn()
Sortie & Decouper_Bord_coincident::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 23 of file Decouper_Bord_coincident.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Decouper_Bord_coincident::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 28 of file Decouper_Bord_coincident.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Decouper_Bord_coincident & Decouper_Bord_coincident::self_cast (const Objet_U & r) static
Definition at line 21 of file Decouper_Bord_coincident.cpp.
self_cast() [2/2]
Decouper_Bord_coincident & Decouper_Bord_coincident::self_cast (Objet_U & r) static
Definition at line 21 of file Decouper_Bord_coincident.cpp.
taille_memoire()
unsigned Decouper_Bord_coincident::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Decouper_Bord_coincident.cpp.
Member Data Documentation
info_obj
const Type_info Decouper_Bord_coincident::info_obj static
Definition at line 37 of file Decouper_Bord_coincident.h.
nom_bord
Nom Decouper_Bord_coincident::nom_bord
Definition at line 44 of file Decouper_Bord_coincident.h.
Referenced by Decouper_Bord_coincident_(), and interpreter_().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Decouper_Bord_coincident.h
src/Kernel/Geometrie/Decouper_Bord_coincident.cpp