TRUST: Champ_front_var_instationnaire Class Reference
Champ_front_var_instationnaire Class Reference
classe Champ_front_var_instationnaire
Classe derivee de Champ_front_var qui represente les champs aux
frontieres variables en espace et dans le temps.
Les Champ_front_var_instationnaire sont classes suivant que
leurs valeurs dependent ou non de parametres externes a
l'equation, en Champ_front_var_instationnaire_indep et
Champ_front_var_instationnaire_dep.
L'implementation du calcul du champ doit se faire dans la
methode mettre_a_jour.
Dans le premier cas (indep), la methode initialiser peut
appeler la methode mettre_a_jour, mais pas dans le second cas<br>(dep). Elle peut de toutes facons utiliser l'inconnue qui lui
est passee en parametre comme une premiere estimation.
#include <Champ_front_var_instationnaire.h>
Public Member Functions
Champ_front_var_instationnaire ()
~Champ_front_var_instationnaire () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void fixer_nb_valeurs_temporelles (int nb_cases) override
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialise le temps courant et Gpoint.
DoubleTab & Gpoint ()
const DoubleTab & Gpoint () const
void Gpoint (double t1, double t2)
DoubleTab & valeurs_au_temps (double temps) override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
const DoubleTab & valeurs_au_temps (double temps) const override
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
int avancer (double temps) override
Avance jusqu'au temps desire.
Sinon, sort en erreur.
int reculer (double temps) override
Recule jusqu'au temps desire.
Sinon, sort en erreur.
virtual double valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const
virtual int valeur_au_temps_et_au_point_disponible () const
Public Member Functions inherited from Champ_front_var
Champ_front_var ()
~Champ_front_var () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco) override
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Public Member Functions inherited from Champ_front_base
~Champ_front_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_front_base ()
virtual void completer ()
virtual int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees
externes a l'equation (couplage). Si mettre_a_jour le fait,
alors initialiser ne doit pas appeler mettre_a_jour.
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
Associe une frontiere discretisee au champ.
DoubleTab & valeurs () override
Renvoie le tableau des valeurs du champ.
const DoubleTab & valeurs () const override
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
virtual DoubleTab & valeurs_au_temps (double temps)=0
virtual const DoubleTab & valeurs_au_temps (double temps) const =0
const Frontiere_dis_base & frontiere_dis () const
Renvoie la frontiere discretisee associee au champ.
(version const)
Frontiere_dis_base & frontiere_dis ()
Renvoie la frontiere discretisee associee au champ.
const Zone_dis_base & zone_dis () const
virtual Champ_front_base & affecter_ (const Champ_front_base &ch)=0
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
Appele par Conds_lim::completer
Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou
sous-pas-de-temps, elle peut eventuellement utiliser des donnees
exterieures a l'equation. A charge a l'algorithme de s'assurer
que ces donnees sont pertinentes...
Calcule la valeur de la condition aux limites au temps demande.
virtual void calculer_coeffs_echange (double temps)
NE FAIT RIEN, a surcharger
Cette methode peut calculer et stocker des donnees utiles a la
CL, et dependant uniquement de l'inconnue sur laquelle porte
cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple.
Elle est appelee lorsque l'inconnue est modifiee.
virtual void valeurs_face (int, DoubleVect &) const
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des
valeurs porte nb_faces * nb_compo_ valeurs.
Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parametre: num_face
Signification: l'indice d'une face sur la frontiere
0 <= num_face < frontiere_dis().frontiere().nb_faces()
Parametre: val
Signification: On resize ce tableau et on le remplit.
virtual void verifier (const Cond_lim_base &la_cl) const
double get_temps_defaut () const
void set_temps_defaut (double temps)
virtual void changer_temps_futur (double temps, int i)
virtual int avancer (double temps)
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe
en parametre.
virtual int reculer (double temps)
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe
en parametre.
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static const Type_info * info ()
static Champ_front_var_instationnaire & self_cast (Objet_U &)
static const Champ_front_var_instationnaire & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_var
static const Type_info * info ()
static Champ_front_var & self_cast (Objet_U &)
static const Champ_front_var & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_front_base
static const Type_info * info ()
static Champ_front_base & self_cast (Objet_U &)
static const Champ_front_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_var
static const Type_info info_obj
Static Public Attributes inherited from Champ_front_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Sortie & printOn (Sortie &x) const override
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleTab Gpoint_
Taux d'accroissement du champ.
Protected Attributes inherited from Champ_front_base
double temps_defaut
Le temps pris par defaut quand le parametre n'est pas specifie. Ce sera en particulier celui utilise par les operateurs et les solveurs.
Ref_Frontiere_dis_base la_frontiere_dis
Roue_ptr les_valeurs
Les valeurs du champ.
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_front_var_instationnaire
Classe derivee de Champ_front_var qui represente les champs aux
frontieres variables en espace et dans le temps.
Les Champ_front_var_instationnaire sont classes suivant que
leurs valeurs dependent ou non de parametres externes a
l'equation, en Champ_front_var_instationnaire_indep et
Champ_front_var_instationnaire_dep.
L'implementation du calcul du champ doit se faire dans la
methode mettre_a_jour.
Dans le premier cas (indep), la methode initialiser peut
appeler la methode mettre_a_jour, mais pas dans le second cas<br>(dep). Elle peut de toutes facons utiliser l'inconnue qui lui
est passee en parametre comme une premiere estimation.
Definition at line 42 of file Champ_front_var_instationnaire.h.
Constructor & Destructor Documentation
Champ_front_var_instationnaire()
Champ_front_var_instationnaire::Champ_front_var_instationnaire ()
Definition at line 18 of file Champ_front_var_instationnaire.cpp.
~Champ_front_var_instationnaire()
Champ_front_var_instationnaire::~Champ_front_var_instationnaire () override
Definition at line 18 of file Champ_front_var_instationnaire.cpp.
Member Function Documentation
avancer()
int Champ_front_var_instationnaire::avancer (double temps) override virtual
Avance jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
Definition at line 144 of file Champ_front_var_instationnaire.cpp.
{
// S"agit-il bien d'une avance en temps ?
  assert(temps>les_valeurs->temps());
  for(int i=1; i<les_valeurs->nb_cases(); i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        {
          les_valeurs=les_valeurs[i];
          return 1;
        }
    }
  Cerr << "In Champ_front_var_instationnaire::avancer(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return 0;
}
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, Roue::nb_cases(), print(), and Roue::temps().
Referenced by Champ_front_xyz_debit::avancer().
fixer_nb_valeurs_temporelles()
void Champ_front_var_instationnaire::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Champ_front_base.
Definition at line 63 of file Champ_front_var_instationnaire.cpp.
{
  les_valeurs->fixer_nb_cases(nb_cases);
}
References Roue::fixer_nb_cases(), and Champ_front_base::les_valeurs.
Referenced by Champ_front_xyz_debit::fixer_nb_valeurs_temporelles().
get_info()
const Type_info * Champ_front_var_instationnaire::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_var.
Reimplemented in Champ_front_MED, Champ_front_recyclage, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 18 of file Champ_front_var_instationnaire.cpp.
Gpoint() [1/3]
DoubleTab & Champ_front_var_instationnaire::Gpoint () inline
Definition at line 73 of file Champ_front_var_instationnaire.h.
{
  return Gpoint_;
}
References Gpoint_.
Referenced by Zone_Cl_dis_base::Gpoint(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Ch_front_input::setValue(), and Ch_front_input_P1::setValue().
Gpoint() [2/3]
const DoubleTab & Champ_front_var_instationnaire::Gpoint () const inline
Definition at line 78 of file Champ_front_var_instationnaire.h.
{
  return Gpoint_;
}
References Gpoint_.
Gpoint() [3/3]
void Champ_front_var_instationnaire::Gpoint (double t1, double t2)
Definition at line 192 of file Champ_front_var_instationnaire.cpp.
{
  Gpoint_=valeurs_au_temps(t1);
  if (t2>t1+DMINFLOAT)
    {
      Gpoint_ *= -1;
      Gpoint_ += valeurs_au_temps(t2);
      Gpoint_ /= (t2-t1);
    }
  else
    Gpoint_=0;
// Gpoint_.echange_espace_virtuel(); PL inutile
}
References DMINFLOAT, Gpoint_, and valeurs_au_temps().
info()
const Type_info * Champ_front_var_instationnaire::info () static
Definition at line 18 of file Champ_front_var_instationnaire.cpp.
initialiser()
int Champ_front_var_instationnaire::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialise le temps courant et Gpoint.
< pour dimensionner
Reimplemented from Champ_front_var.
Reimplemented in Champ_front_recyclage, Champ_front_pression_from_u, Champ_front_synt, Champ_front_contact_VEF, and Champ_front_tangentiel_VEF.
Definition at line 82 of file Champ_front_var_instationnaire.cpp.
{
  if (!Champ_front_var::initialiser(temps,inco))
    return 0;
  temps_defaut=temps;
  changer_temps_futur(temps,0);
  Gpoint_=valeurs(); //!< pour dimensionner
  Gpoint_=0.;
  return 1;
}
References Champ_front_base::changer_temps_futur(), Gpoint_, Champ_front_var::initialiser(), Champ_front_base::temps_defaut, and Champ_front_base::valeurs().
Referenced by Ch_front_Vortex::initialiser(), Champ_Front_Fonction::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), and Ch_front_var_instationnaire_indep::initialiser().
printOn()
Sortie & Champ_front_var_instationnaire::printOn (Sortie & s) const override protected virtual
Imprime le nom du champ sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_var.
Reimplemented in Champ_front_MED, Champ_front_recyclage, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 34 of file Champ_front_var_instationnaire.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_front_var_instationnaire::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_var.
Reimplemented in Champ_front_MED, Champ_front_recyclage, Champ_front_debit_QC, Champ_front_debit_QC_fonc_t, Champ_front_pression_from_u, Champ_front_synt, Champ_front_fonc_gradient_VDF, Champ_front_contact_fictif_VEF, Champ_front_contact_VEF, Champ_front_fonc_gradient_VEF, and Champ_front_tangentiel_VEF.
Definition at line 55 of file Champ_front_var_instationnaire.cpp.
{
  return s ;
}
reculer()
int Champ_front_var_instationnaire::reculer (double temps) override virtual
Recule jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
Definition at line 168 of file Champ_front_var_instationnaire.cpp.
{
// S"agit-il bien d'un recul en temps ?
  assert(temps<les_valeurs->temps());
  for(int i=les_valeurs->nb_cases()-1; i>=1; i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        {
          les_valeurs=les_valeurs[i];
          return 1;
        }
    }
  Cerr << "In Champ_front_var_instationnaire::reculer(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return 0;
}
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, Roue::nb_cases(), and print().
Referenced by Champ_front_xyz_debit::reculer().
self_cast() [1/2]
const Champ_front_var_instationnaire & Champ_front_var_instationnaire::self_cast (const Objet_U & r) static
Definition at line 18 of file Champ_front_var_instationnaire.cpp.
self_cast() [2/2]
Champ_front_var_instationnaire & Champ_front_var_instationnaire::self_cast (Objet_U & r) static
Definition at line 18 of file Champ_front_var_instationnaire.cpp.
valeur_au_temps_et_au_point()
virtual double Champ_front_var_instationnaire::valeur_au_temps_et_au_point (double temps, int som, double x, double y, double z, int comp) const inline virtual
Reimplemented in Champ_front_txyz, Champ_Front_xyz_Tabule, Ch_front_input_P1, and Champ_front_MED.
Definition at line 58 of file Champ_front_var_instationnaire.h.
  {
    Cerr<<"valeur_au_temps_et_au_point mut be defined si valeur_au_temps_et_au_point_disponible()==1"<<finl;
    exit();
    return 0;
  };
References Cerr, Process::exit(), and finl.
Referenced by Zone_Cl_EF::imposer_cond_lim().
valeur_au_temps_et_au_point_disponible()
virtual int Champ_front_var_instationnaire::valeur_au_temps_et_au_point_disponible () const inline virtual
Reimplemented in Champ_front_t, Champ_front_txyz, and Ch_front_input_P1.
Definition at line 64 of file Champ_front_var_instationnaire.h.
  {
    return 0;
  };
Referenced by Zone_Cl_EF::imposer_cond_lim().
valeurs_au_temps() [1/2]
const DoubleTab & Champ_front_var_instationnaire::valeurs_au_temps (double temps) const override virtual
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
< For compilers
Implements Champ_front_base.
Definition at line 125 of file Champ_front_var_instationnaire.cpp.
{
  for(int i=0; i<les_valeurs->nb_cases(); i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        return les_valeurs[i].valeurs();
    }
  Cerr << "In Champ_front_var_instationnaire::valeurs(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return valeurs(); //!< For compilers
}
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, Roue::nb_cases(), print(), and Champ_front_base::valeurs().
valeurs_au_temps() [2/2]
DoubleTab & Champ_front_var_instationnaire::valeurs_au_temps (double temps) override virtual
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
< For compilers
Implements Champ_front_base.
Definition at line 106 of file Champ_front_var_instationnaire.cpp.
{
  for(int i=0; i<les_valeurs->nb_cases(); i++)
    {
      if(est_egal(les_valeurs[i].temps(),temps))
        return les_valeurs[i].valeurs();
    }
  Cerr << "In Champ_front_var_instationnaire::valeurs(double), "
       << "time " << temps << " not found." << finl;
  print(les_valeurs);
  exit();
  return valeurs(); //!< For compilers
}
References Cerr, est_egal(), Process::exit(), finl, Champ_front_base::les_valeurs, Roue::nb_cases(), print(), and Champ_front_base::valeurs().
Referenced by Champ_front_MED::affecter_(), Gpoint(), Champ_front_bruite::mettre_a_jour(), Champ_front_calc::mettre_a_jour(), Champ_front_calc_interne::mettre_a_jour(), Champ_Front_Fonction::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_front_xyz_debit::mettre_a_jour(), Champ_Front_xyz_Tabule::mettre_a_jour(), Champ_front_MED::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), and Champ_front_contact_VEF::verifier_scalaire_bord().
Member Data Documentation
Gpoint_
DoubleTab Champ_front_var_instationnaire::Gpoint_ protected
Taux d'accroissement du champ.
Definition at line 69 of file Champ_front_var_instationnaire.h.
Referenced by Gpoint(), and initialiser().
info_obj
const Type_info Champ_front_var_instationnaire::info_obj static
Definition at line 45 of file Champ_front_var_instationnaire.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_front_var_instationnaire.h
src/Kernel/Framework/Champ_front_var_instationnaire.cpp