TRUST: Discr_inst Class Reference
Discr_inst Class Reference
class Discr_inst
Cette classe ne sait rien faire, on en a besoin pour le Pb_MED
on a besoin d'avoir associe une discretisation
#include <Discr_inst.h>
Public Member Functions
Discr_inst ()
~Discr_inst ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const override
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
void modifier_champ_tabule (const Zone_dis_base &zone_vdf, Champ_Fonc_Tabule &lambda_tab, const Vect_Ref_Champ_base &ch_temper) const override
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const override
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const override
Idem que Discr_inst::discretiser_champ(... , Champ_Inc)
pour un Champ_Fonc.
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const override
Idem que Discr_inst::discretiser_champ(... , Champ_Inc)
pour un Champ_Don.
Public Member Functions inherited from Discretisation_base
Discretisation_base ()
~Discretisation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual type_calcul_du_residu codage_du_calcul_du_residu (void) const
virtual void discretiser_variables () const
virtual void discretiser_Zone_Cl_dis (const Zone_dis &, Zone_Cl_dis &) const
virtual void discretiser (Domaine_dis &) const
virtual void zone_Cl_dis (Zone_dis &, Zone_Cl_dis &) const =0
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Fonc &champ) const
void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, const Nom &nom, const Nom &unite, int nb_comp, double temps, Champ_Don &champ) const
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc &champ, const Nom &sous_type=nom_vide) const
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Fonc &champ) const
idem
virtual void discretiser_champ (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, Champ_Don &champ) const
idem
void nommer_completer_champ_physique (const Zone_dis_base &zone_vdf, const Nom &nom_champ, const Nom &unite, Champ_base &champ, const Probleme_base &pbi) const
int verifie_sous_type (Nom &type, const Nom &sous_type, const Motcle &directive) const
void volume_maille (const Schema_Temps_base &sch, const Zone_dis &z, Champ_Fonc &ch) const
virtual void residu (const Zone_dis &, const Champ_Inc &, Champ_Fonc &) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const Ref_Champ_base &champ_supp=Ref_Champ_base()) const
remplit le Nom type en focntion de la classe de operateur, du type de l'operateur et de l'equation
Parametre: class_operateur
Signification: Ce nom correspond au type de la classe de base de l'objet que l'on veut construire
exemples: "source","Op_conv","Op_diff","Op_div","Op_grad","solveur_masse"
Exemple get_name_of_type_for("Op_conv","amont",eqn,type);
get_name_of_type_for("Op_diff"," ",eqn,type,champ_diffusisivite);
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Discr_inst & self_cast (Objet_U &)
static const Discr_inst & self_cast (const Objet_U &)
Static Public Member Functions inherited from Discretisation_base
static const Type_info * info ()
static Discretisation_base & self_cast (Objet_U &)
static const Discretisation_base & self_cast (const Objet_U &)
static void creer_champ (Champ_Inc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Inc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Fonc &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Fonc du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
static void creer_champ (Champ_Don &ch, const Zone_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=nom_vide, const Nom &nom_discretisation=nom_vide)
Methode statique qui cree un Champ_Don du type specifie.
Les parametres "directive" et "nom_discretisation" sont
utilises pour l'affichage uniquement et sont optionnels.
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Discretisation_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void discretiser_champ_fonc_don (const Motcle &directive, const Zone_dis_base &z, Nature_du_champ nature, const Noms &noms, const Noms &unites, int nb_comp, double temps, Objet_U &champ) const
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
Additional Inherited Members
Public Types inherited from Discretisation_base
enum type_calcul_du_residu { VIA_CONTRIBUER_AU_SECOND_MEMBRE = 0 , VIA_AJOUTER = 1 }
Static Protected Attributes inherited from Discretisation_base
static const Motcle demande_description = Motcle("demande_description")
static const Nom nom_vide = Nom("-")
Detailed Description
class Discr_inst
Cette classe ne sait rien faire, on en a besoin pour le Pb_MED
on a besoin d'avoir associe une discretisation
Definition at line 28 of file Discr_inst.h.
Constructor & Destructor Documentation
Discr_inst()
Discr_inst::Discr_inst ()
Definition at line 23 of file Discr_inst.cpp.
~Discr_inst()
Discr_inst::~Discr_inst ()
Definition at line 23 of file Discr_inst.cpp.
Member Function Documentation
cree_instance()
Objet_U * Discr_inst::cree_instance () static
Definition at line 23 of file Discr_inst.cpp.
discretiser_champ() [1/3]
void Discr_inst::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Don & champ) const override virtual
Idem que Discr_inst::discretiser_champ(... , Champ_Inc)
pour un Champ_Don.
Reimplemented from Discretisation_base.
Definition at line 63 of file Discr_inst.cpp.
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
References discretiser_champ_fonc_don().
discretiser_champ() [2/3]
void Discr_inst::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, double temps, Champ_Fonc & champ) const override virtual
Idem que Discr_inst::discretiser_champ(... , Champ_Inc)
pour un Champ_Fonc.
Reimplemented from Discretisation_base.
Definition at line 48 of file Discr_inst.cpp.
{
  discretiser_champ_fonc_don(directive, z,
                             nature, noms, unites,
                             nb_comp, temps, champ);
}
References discretiser_champ_fonc_don().
discretiser_champ() [3/3]
void Discr_inst::discretiser_champ (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & nom, const Noms & unite, int nb_comp, int nb_pas_dt, double temps, Champ_Inc & champ, const Nom & sous_type = nom_vide) const override virtual
Discretisation d'un champ en fonction de la directive et des autres
parametres. Voir les classes derivees. Cette methode
ne traite aucune directive, elle affiche la liste des directives comprises
par les classes derivees.
Voir par exemple VDF_discretisation.cpp et VEF...
Reimplemented from Discretisation_base.
Definition at line 36 of file Discr_inst.cpp.
{
  assert(0);
  throw;
}
discretiser_champ_fonc_don()
void Discr_inst::discretiser_champ_fonc_don (const Motcle & directive, const Zone_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, Objet_U & champ) const private
Idem que VEF_discretisation::discretiser_champ(... , Champ_Inc)
Traitement commun aux champ_fonc et champ_don.
Cette methode est privee (passage d'un Objet_U pas propre vu
de l'exterieur ...)
< Creer un champ aux elements (de type P0)
< Creer un champ aux sommets
Definition at line 80 of file Discr_inst.cpp.
{
// Deux pointeurs pour acceder facilement au champ_don ou au champ_fonc,
// suivant le type de l'objet champ.
  Champ_Fonc * champ_fonc = 0;
  Champ_Don * champ_don = 0;
  if (sub_type(Champ_Fonc, champ))
    champ_fonc = & ref_cast(Champ_Fonc, champ);
  else
    champ_don  = & ref_cast(Champ_Don, champ);
  Motcles motcles(2);
  motcles[0] = "champ_elem";  //!< Creer un champ aux elements (de type P0)
  motcles[1] = "champ_sommets";   //!< Creer un champ aux sommets
  Nom type;
  int rang = motcles.search(directive);
// int default_nb_comp = 1;
  const Domaine& domaine=z.zone().domaine();
  int nb_som_elem = domaine.zone(0).nb_som_elem();
  int nb_ddl=-1;
  switch(rang)
    {
    case 0:
      type = "Champ_Fonc_P0_MED";
      nb_ddl = domaine.zone(0).nb_elem();
      break;
    case 1:
      type = "Champ_Fonc_P1_MED";
      nb_ddl = domaine.nb_som();
      if (((dimension==2) && (nb_som_elem==4)) || ((dimension==3) && (nb_som_elem==8)))
        {
          type = "Champ_Fonc_Q1_MED";
        }
      break;
    default:
      assert(rang < 0);
      break;
    }
  if (directive == demande_description)
    Cerr << "Discr_inst : " << motcles;
// Si on n'a pas compris la directive (ou si c'est une demande_description)
// alors on appelle l'ancetre :
  if (rang < 0)
    {
      if (champ_fonc)
        Discretisation_base::discretiser_champ(directive, z, nature, noms, unites,
                                               nb_comp, temps, *champ_fonc);
      else
        Discretisation_base::discretiser_champ(directive, z, nature, noms, unites,
                                               nb_comp, temps, *champ_don);
      return;
    }
  if (champ_fonc)
    {
      Champ_Fonc& ch=*champ_fonc;
      ch.typer(type);
      ch->associer_zone_dis_base(z);
      ch->fixer_nb_comp(nb_comp);
      ch->fixer_nature_du_champ(nature);
      ch->fixer_nb_valeurs_nodales(nb_ddl);
    }
  else
    {
      assert(0);
      throw;
    }
}
References Champ_Fonc::associer_zone_dis_base(), Cerr, Discretisation_base::demande_description, Objet_U::dimension, Discretisation_base::discretiser_champ(), Zone::domaine(), Champ_Fonc::fixer_nb_valeurs_nodales(), Zone::nb_elem(), Domaine::nb_som(), Zone::nb_som_elem(), ref_cast, Motcles::search(), sub_type, Deriv_::typer(), Zone_dis_base::zone(), and Domaine::zone().
Referenced by discretiser_champ().
duplique()
int Discr_inst::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Discr_inst.cpp.
get_info()
const Type_info * Discr_inst::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Discretisation_base.
Definition at line 23 of file Discr_inst.cpp.
info()
const Type_info * Discr_inst::info () static
Definition at line 23 of file Discr_inst.cpp.
modifier_champ_tabule()
void Discr_inst::modifier_champ_tabule (const Zone_dis_base & zone_vdf, Champ_Fonc_Tabule & lambda_tab, const Vect_Ref_Champ_base & ch_temper) const inline override virtual
Reimplemented from Discretisation_base.
Definition at line 46 of file Discr_inst.h.
  {
    Cerr<<__FILE__<<(int)__LINE__<<" not coded"<<finl;
    Process::exit();
  };
References Cerr, Process::exit(), and finl.
printOn()
Sortie & Discr_inst::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Discretisation_base.
Definition at line 30 of file Discr_inst.cpp.
{
  return s ;
}
readOn()
Entree & Discr_inst::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Discretisation_base.
Definition at line 25 of file Discr_inst.cpp.
{
  return s ;
}
self_cast() [1/2]
const Discr_inst & Discr_inst::self_cast (const Objet_U & r) static
Definition at line 23 of file Discr_inst.cpp.
self_cast() [2/2]
Discr_inst & Discr_inst::self_cast (Objet_U & r) static
Definition at line 23 of file Discr_inst.cpp.
taille_memoire()
unsigned Discr_inst::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Discr_inst.cpp.
volume_maille()
void Discr_inst::volume_maille (const Schema_Temps_base & sch, const Zone_dis & z, Champ_Fonc & ch) const inline
Definition at line 41 of file Discr_inst.h.
  {
    Cerr<<__FILE__<<(int)__LINE__<<" not coded"<<finl;
    exit();
  };
References Cerr, Process::exit(), and finl.
zone_Cl_dis()
void Discr_inst::zone_Cl_dis (Zone_dis & , Zone_Cl_dis &) const inline override virtual
Implements Discretisation_base.
Definition at line 36 of file Discr_inst.h.
  {
    Cerr<<__FILE__<<(int)__LINE__<<" not coded"<<finl;
    exit();
  };
References Cerr, Process::exit(), and finl.
Member Data Documentation
info_obj
const Type_info Discr_inst::info_obj static
Definition at line 30 of file Discr_inst.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Discr_inst.h
src/Kernel/MEDimpl/Discr_inst.cpp