TRUST: Fluide_Incompressible Class Reference
Fluide_Incompressible Class Reference
classe Fluide_Incompressible
Cette classe represente un d'un fluide incompressible ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
#include <Fluide_Incompressible.h>
Public Member Functions
~Fluide_Incompressible ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_Incompressible ()
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
Public Member Functions inherited from Fluide_base
~Fluide_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Fluide_base ()
const Champ_Don & viscosite_cinematique () const
Renvoie la viscosite cinematique, nu.
(vesrion const)
const Champ_Don & viscosite_dynamique () const
Renvoie la viscosite dynamique, mu.
(version const)
const Champ_Don & beta_c () const
Renvoie la dilatabilite du constituant, beta_co.
(version const)
Champ_Don & viscosite_cinematique ()
Renvoie la viscosite cinematique, nu.
Champ_Don & viscosite_dynamique ()
Renvoie la viscosite dynamique, mu.
Champ_Don & beta_c ()
Renvoie la dilatabilite du constituant, beta_co.
virtual const Champ_base & energie_interne () const
virtual Champ_base & energie_interne ()
virtual const Champ_base & enthalpie () const
virtual Champ_base & enthalpie ()
int is_rayo_semi_transp () const override
int is_rayo_transp () const override
void fixer_type_rayo ()
void reset_type_rayo ()
int longueur_rayo_is_discretised ()
Champ_Don & kappa ()
Renvoie le coefficient d'absorbtion du fluide.
const Champ_Don & kappa () const
Renvoie le coefficient d'absorbtion du fluide.
Champ_Don & indice ()
Renvoie l'indice de refraction du fluide.
const Champ_Don & indice () const
Renvoie l'indice de refraction du fluide.
Champ_Don & longueur_rayo ()
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
const Champ_Don & longeur_rayo () const
Renvoie la longueur de penetration du rayonnement dans le fluide
definie comme l = 1/(3*kappa)
void set_param (Param &param) override
void verifier_coherence_champs (int &err, Nom &message) override
Verifie que les champs lus l'ont ete correctement.
bool initTimeStep (double dt) override
void mettre_a_jour (double) override
Effectue une mise a jour en temps du milieu,
et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le
nouveau temps specifie, les autres sont mis a
par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
int initialiser (const double temps) override
Initialise les parametres du fluide.
void creer_champs_non_lus () override
void discretiser (const Probleme_base &pb, const Discretisation_base &dis) override
virtual void set_h0_T0 (double h0, double T0)
Public Member Functions inherited from Milieu_base
~Milieu_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Milieu_base ()
virtual void set_param (Param &param)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual void preparer_calcul ()
virtual void verifier_coherence_champs (int &err, Nom &message)
virtual void creer_champs_non_lus ()
virtual void discretiser (const Probleme_base &pb, const Discretisation_base &dis)
virtual int is_rayo_semi_transp () const
virtual int is_rayo_transp () const
virtual void mettre_a_jour (double temps)
virtual bool initTimeStep (double dt)
virtual void abortTimeStep ()
virtual int initialiser (const double temps)
virtual void associer_gravite (const Champ_Don_base &)
Associe (affecte) un champ de gravite au milieu.
virtual const Champ & masse_volumique () const
Renvoie la masse volumique du milieu.
(version const)
virtual Champ & masse_volumique ()
Renvoie la masse volumique du milieu.
virtual const Champ_Don & diffusivite () const
Renvoie la diffusivite du milieu.
(version const)
virtual Champ_Don & diffusivite ()
Renvoie la diffusivite du milieu.
virtual const Champ_Don & conductivite () const
Renvoie la conductivite du milieu.
(version const)
virtual Champ_Don & conductivite ()
Renvoie la conductivite du milieu.
virtual const Champ_Don & capacite_calorifique () const
Renvoie la capacite calorifique du milieu.
(version const)
virtual Champ_Don & capacite_calorifique ()
Renvoie la capacite calorifique du milieu.
virtual const Champ_Don & beta_t () const
Renvoie beta_t du milieu.
(version const)
virtual Champ_Don & beta_t ()
Renvoie beta_t du milieu.
virtual int a_gravite () const
Renvoie 1 si la gravite a ete initialisee.
virtual const Champ_Don_base & gravite () const
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
(version const)
virtual Champ_Don_base & gravite ()
Renvoie la gravite du milieu si elle a ete associe
provoque une erreur sinon.
int associer_ (Objet_U &) override
Associe la gravite en controlant dynamiquement le
type de l'objet a associer.
Si l'objet est du type Champ_Don ou Champ_Don_base
l'association reussit, sinon elle echoue.
virtual int est_deja_associe ()
Renvoie 0 si le milieu est deja associe a un probleme, 1 sinon.
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void update_rho_cp (double temps)
virtual void associer_equation (const Equation_base *eqn) const
virtual const Equation_base & equation (const std::string &nom_inc) const
virtual int check_unknown_range () const
void set_id_composite (const int i)
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_Incompressible & self_cast (Objet_U &)
static const Fluide_Incompressible & self_cast (const Objet_U &)
Static Public Member Functions inherited from Fluide_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Fluide_base & self_cast (Objet_U &)
static const Fluide_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Milieu_base
static const Type_info * info ()
static Milieu_base & self_cast (Objet_U &)
static const Milieu_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Fluide_base
static const Type_info info_obj
Static Public Attributes inherited from Milieu_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Protected Member Functions inherited from Fluide_base
Sortie & printOn (Sortie &x) const override
Ecrit les proprietes du fluide sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
void creer_e_int () const
void creer_nu ()
Si l'objet reference par nu et du type Champ_Uniforme
type nu en "Champ_Uniforme" et le remplit
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
virtual void calculer_nu ()
Protected Member Functions inherited from Milieu_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn
Imprime un mileu sur un flot de sortie.
Appelle Milieu_base::ecrire.
Entree & readOn (Entree &) override
Lecture d'un milieu sur un flot d'entree.
Format:
{
grandeur_physique type_champ bloc de lecture du champ
}
cf set_param method to know the understood keywords
cf Param class to know possible options reading.
void ecrire (Sortie &) const
Ecrit un objet milieu sur un flot de sortie.
Ecrit les caracteristiques du milieu:
- masse volumique
- conductivite
- capacite calorifique
- beta_th.
void creer_alpha ()
virtual void calculer_alpha ()
Calcul de alpha=lambda/(rho*Cp).
Suivant lambda, rho et Cp alpha peut-etre type comme
un champ uniforme ou un champ uniforme par morceau.
void creer_derivee_rho ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Public Attributes inherited from Milieu_base
int id_composite = -1
Protected Types inherited from Milieu_base
enum Type_rayo { NONRAYO , TRANSP , SEMITRANSP }
Static Protected Member Functions inherited from Fluide_base
static void calculer_e_int (const Objet_U &obj, DoubleTab &val, DoubleTab &bval, tabs_t &deriv)
Protected Attributes inherited from Fluide_base
int e_int_auto_ = 0
Champ e_int
Champ h
Champ_Don mu
Champ_Don nu
Champ_Don beta_co
double h0_ = 0
double T0_ = 0
Champ_Don coeff_absorption_
Champ_Don indice_refraction_
Champ_Don longueur_rayo_
Protected Attributes inherited from Milieu_base
Champ rho
Champ_Don alpha
Champ_Don lambda
Champ_Don Cp
Champ_Don beta_th
Champ_Fonc rho_cp_elem_
Champ_Fonc rho_cp_comme_T_
Nom nom_
Ref_Champ_Don_base g
Type_rayo indic_rayo_
int deja_associe
Champs_compris champs_compris_
std::map< std::string, const Equation_base * > equation_
Detailed Description
classe Fluide_Incompressible
Cette classe represente un d'un fluide incompressible ainsi que
ses proprietes:
- viscosite cinematique, (mu)
- viscosite dynamique, (nu)
- masse volumique, (rho)
- diffusivite, (alpha)
- conductivite, (lambda)
- capacite calorifique, (Cp)
- dilatabilite thermique du constituant (beta_co)
Definition at line 38 of file Fluide_Incompressible.h.
Constructor & Destructor Documentation
~Fluide_Incompressible()
Fluide_Incompressible::~Fluide_Incompressible ()
Definition at line 28 of file Fluide_Incompressible.cpp.
Fluide_Incompressible()
Fluide_Incompressible::Fluide_Incompressible ()
Definition at line 38 of file Fluide_Incompressible.cpp.
{ }
Member Function Documentation
cree_instance()
Objet_U * Fluide_Incompressible::cree_instance () static
Definition at line 28 of file Fluide_Incompressible.cpp.
duplique()
int Fluide_Incompressible::duplique () const override virtual
Reimplemented from Fluide_base.
Reimplemented in Fluide_Ostwald.
Definition at line 28 of file Fluide_Incompressible.cpp.
get_info()
const Type_info * Fluide_Incompressible::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Fluide_base.
Reimplemented in Fluide_Ostwald.
Definition at line 28 of file Fluide_Incompressible.cpp.
info()
const Type_info * Fluide_Incompressible::info () static
Definition at line 28 of file Fluide_Incompressible.cpp.
printOn()
Sortie & Fluide_Incompressible::printOn (Sortie & os) const override protected virtual
Ecrit les proprietes du fluide sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Fluide_base.
Reimplemented in Fluide_Ostwald.
Definition at line 40 of file Fluide_Incompressible.cpp.
{
  return Fluide_base::printOn(os);
}
References Fluide_base::printOn().
readOn()
Entree & Fluide_Incompressible::readOn (Entree & is) override protected virtual
Lit les caracteristiques du fluide a partir d'un flot
d'entree.
Format:
Fluide_base
{
Mu type_champ bloc de lecture de champ
Rho Champ_Uniforme 1 vrel
[Cp Champ_Uniforme 1 vrel]
[Lambda type_champ bloc de lecture de champ]
[Beta_th type_champ bloc de lecture de champ]
[Beta_co type_champ bloc de lecture de champ]
}
cf Milieu_base::readOn.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Fluide_base.
Reimplemented in Fluide_Ostwald.
Definition at line 45 of file Fluide_Incompressible.cpp.
{
  Fluide_base::readOn(is);
  return is;
}
References Fluide_base::readOn().
Referenced by Fluide_Ostwald::readOn().
self_cast() [1/2]
const Fluide_Incompressible & Fluide_Incompressible::self_cast (const Objet_U & r) static
Definition at line 28 of file Fluide_Incompressible.cpp.
self_cast() [2/2]
Fluide_Incompressible & Fluide_Incompressible::self_cast (Objet_U & r) static
Definition at line 28 of file Fluide_Incompressible.cpp.
taille_memoire()
unsigned Fluide_Incompressible::taille_memoire () const override virtual
Reimplemented from Fluide_base.
Reimplemented in Fluide_Ostwald.
Definition at line 28 of file Fluide_Incompressible.cpp.
verifier_coherence_champs()
void Fluide_Incompressible::verifier_coherence_champs (int & err, Nom & message) override virtual
Verifie que les champs lus l'ont ete correctement.
Reimplemented from Fluide_base.
Definition at line 67 of file Fluide_Incompressible.cpp.
{
  msg="";
  if (rho.non_nul())
    {
      if (!sub_type(Champ_Uniforme,rho.valeur()))
        {
          msg += "The density rho is not of type Champ_Uniforme. \n";
          err = 1;
        }
    }
  if (Cp.non_nul())
    {
      if (!sub_type(Champ_Uniforme,Cp.valeur()))
        {
          msg += "Cp is not of type Champ_Uniforme. \n";
          err = 1;
        }
    }
  Fluide_base::verifier_coherence_champs(err, msg);
}
References Milieu_base::Cp, O_U_Ptr::non_nul(), Milieu_base::rho, sub_type, Deriv_Champ_base::valeur(), Deriv_Champ_Don_base::valeur(), and Fluide_base::verifier_coherence_champs().
Member Data Documentation
info_obj
const Type_info Fluide_Incompressible::info_obj static
Definition at line 40 of file Fluide_Incompressible.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Milieu/Fluide_Incompressible.h
src/ThHyd/Incompressible/Milieu/Fluide_Incompressible.cpp