TRUST: Scalaire_impose_paroi Class Reference
Scalaire_impose_paroi Class Reference
classe Scalaire_impose_paroi
Impose un scalaire a la paroi dans une equation de type
Convection-Difussion d'un scalaire
#include <Scalaire_impose_paroi.h>
Public Member Functions
Scalaire_impose_paroi ()
~Scalaire_impose_paroi ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int compatible_avec_eqn (const Equation_base &) const
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Scalaire_imposee_paroi sont compatibles
avec une equation dont le domaine est la Thermique, la Concentration
ou bien indetermine.
int compatible_avec_discr (const Discretisation_base &) const
Verifie que les conditions aux limites sont
compatiblea avec la discretisation specifiees en parametre.
Des CL de type Scalaire_imposee_paroi sont compatibles
avec une discretisation de type VEF.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Scalaire_impose_paroi & self_cast (Objet_U &)
static const
Scalaire_impose_paroi & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Simple appel a: Dirichlet::readOn(Entree&)
Detailed Description
classe Scalaire_impose_paroi
Impose un scalaire a la paroi dans une equation de type
Convection-Difussion d'un scalaire
Definition at line 38 of file Scalaire_impose_paroi.h.
Constructor & Destructor Documentation
Scalaire_impose_paroi::Scalaire_impose_paroi ()
Definition at line 28 of file Scalaire_impose_paroi.cpp.
Scalaire_impose_paroi::~Scalaire_impose_paroi ()
Definition at line 28 of file Scalaire_impose_paroi.cpp.
Member Function Documentation
int Scalaire_impose_paroi::compatible_avec_discr (const Discretisation_base & discr) const [virtual]
Verifie que les conditions aux limites sont
compatiblea avec la discretisation specifiees en parametre.
Des CL de type Scalaire_imposee_paroi sont compatibles
avec une discretisation de type VEF.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec la discretisation
0 sinon
Contraintes:
Reimplemented from Cond_lim_base.
Definition at line 90 of file Scalaire_impose_paroi.cpp.
References Cond_lim_base::err_pas_compatible(), and Objet_U::que_suis_je().
{
  Nom type_discr=discr.que_suis_je();
  if (type_discr == "VEF")
    return 1;
  else if (type_discr == "EF")
    return 1;
  else if (type_discr == "EF_axi")
    return 1;
  else if (type_discr == "VEF_P1_P1")
    return 1;
  else if (type_discr == "VEFPreP1B")
    return 1;
  else if (type_discr == "VEFPreP1B_Front_Tracking")
    return 1;
  else if (type_discr == "PolyMAC")
    return 1;
  else if (type_discr == "CoviMAC")
    return 1;
  else
    {
      err_pas_compatible(discr);
      return 0;
    }
}
int Scalaire_impose_paroi::compatible_avec_eqn (const Equation_base & eqn) const [virtual]
Renvoie un booleen indiquant la compatibilite des conditions
aux limites avec l'equation specifiee en parametre.
Des CL de type Scalaire_imposee_paroi sont compatibles
avec une equation dont le domaine est la Thermique, la Concentration
ou bien indetermine.
Returns:
int
Signification: valeur booleenne,
1 si les CL sont compatibles avec l'equation
0 sinon
Contraintes:
Implements Cond_lim_base.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 137 of file Scalaire_impose_paroi.cpp.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
{
  Motcle dom_app=eqn.domaine_application();
  Motcle Thermique="Thermique";
  Motcle Concentration="Concentration";
  Motcle indetermine="indetermine";
  if ( (dom_app==Thermique) || (dom_app==Concentration) || (dom_app==indetermine) )
    return 1;
  else
    {
      err_pas_compatible(eqn);
      return 0;
    }
}
Objet_U * Scalaire_impose_paroi::cree_instance () [static]
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
int Scalaire_impose_paroi::duplique () const [virtual]
Implements Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
const Type_info * Scalaire_impose_paroi::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
const Type_info * Scalaire_impose_paroi::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
Sortie & Scalaire_impose_paroi::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 46 of file Scalaire_impose_paroi.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & Scalaire_impose_paroi::readOn (Entree & s) [protected, virtual]
Simple appel a: Dirichlet::readOn(Entree&)
Returns:
Entree& s
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 65 of file Scalaire_impose_paroi.cpp.
{
  return Dirichlet::readOn(s) ;
}
const Scalaire_impose_paroi & Scalaire_impose_paroi::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
Scalaire_impose_paroi & Scalaire_impose_paroi::self_cast (Objet_U & r) [static]
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
unsigned Scalaire_impose_paroi::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 28 of file Scalaire_impose_paroi.cpp.
Member Data Documentation
const Type_info Scalaire_impose_paroi::info_obj [static]
Reimplemented from Dirichlet.
Reimplemented in Temperature_imposee_paroi_H, Temperature_imposee_paroi, and Echange_contact_Correlation_VEF.
Definition at line 41 of file Scalaire_impose_paroi.h.
The documentation for this class was generated from the following files:
src/ThHyd/Incompressible/Cond_Lim/Scalaire_impose_paroi.h
src/ThHyd/Incompressible/Cond_Lim/Scalaire_impose_paroi.cpp