TRUST: Schema_Adams_Moulton_base Class Reference
Schema_Adams_Moulton_base Class Reference abstract
#include <Schema_Adams_Moulton_base.h>
Public Member Functions
Schema_Adams_Moulton_base ()
class Schema_Adams_Moulton_base
~Schema_Adams_Moulton_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
double changer_temps (Equation_base &eqn, const double temps) override
void update_time_derivative (Equation_base &eqn, const DoubleTab &data) override
void mettre_a_jour_equation (Equation_base &eqn, const double temps) override
void store_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters) override
void modify_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters) override
void compute_coefficients (double time_step, const DoubleTab &times) const override
void add_multi_timestep_data (const Equation_base &eqn, Matrice_Base &mat_morse, DoubleTab &secmem) const override
const DoubleTab & coefficients () const override
DoubleTab & coefficients () override
void modifier_second_membre_full_impl (const Equation_base &eqn, DoubleTab &secmem) override
Public Member Functions inherited from Schema_Implicite_Multi_TimeStep_base
Schema_Implicite_Multi_TimeStep_base ()
~Schema_Implicite_Multi_TimeStep_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
bool initTimeStep (double dt) override
void set_param (Param &) override
int nb_valeurs_futures () const override
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
double temps_futur (int i) const override
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
double temps_defaut () const override
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
int nb_valeurs_temporelles_effectives () const
virtual double changer_temps (Equation_base &eqn, const double temps)=0
virtual void update_time_derivative (Equation_base &eqn, const DoubleTab &data)=0
virtual void mettre_a_jour_equation (Equation_base &eqn, const double temps)=0
virtual void modify_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters)=0
virtual void store_equation_parameters (Equation_base &eqn, DoubleTab &stored_parameters)=0
virtual DoubleTab & coefficients ()=0
virtual void compute_coefficients (double time_step, const DoubleTab &times) const =0
virtual void add_multi_timestep_data (const Equation_base &eqn, Matrice_Base &mat_morse, DoubleTab &secmem) const =0
virtual int nb_pas_dt_seuil () const =0
virtual int nb_valeurs_passees () const =0
virtual const DoubleTab & coefficients () const =0
virtual int faire_un_pas_de_temps_pb_couple (Probleme_Couple &, int &ok)
bool iterateTimeStep (bool &converged) override
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int faire_un_pas_de_temps_eqn_base (Equation_base &) override
int mettre_a_jour () override
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
void completer (void) override
void Initialiser_Champs (Probleme_base &)
void test_stationnaire (Probleme_base &)
int Iterer_Pb (Probleme_base &, int ite)
const double & residu_old () const
void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const override
virtual void modifier_second_membre_full_impl (const Equation_base &eqn, DoubleTab &secmem)
void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem) override
Public Member Functions inherited from Schema_Implicite_base
Schema_Implicite_base ()
class Schema_Implicite_base
~Schema_Implicite_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Solveur_Implicite & solveur ()
const Solveur_Implicite & solveur () const
void set_param (Param &param) override
Public Member Functions inherited from Schema_Temps_base
~Schema_Temps_base () override
< necessaire pour visual
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
virtual void terminate ()
virtual double computeTimeStep (bool &stop) const
virtual bool initTimeStep (double dt)
virtual void validateTimeStep ()
virtual bool isStationary () const
Retourne 1 si lors du dernier pas de temps, le probleme n'a pas evolue.
virtual void abortTimeStep ()
virtual bool iterateTimeStep (bool &converged)
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
int limpr () const
Renvoie 1 s'il y a lieu d'effectuer une impression (cf dt_impr)
Renvoie 0 sinon.
virtual int nb_valeurs_temporelles () const =0
virtual int nb_valeurs_futures () const =0
virtual double temps_futur (int i) const =0
virtual double temps_defaut () const =0
Schema_Temps_base ()
Constructeur par defaut d'un schema en temps.
Initialise differents membres de la classe.
void nommer (const Nom &) override
surcharge Objet_U::nommer(const Nom&)
Donne un nom au shema en temps
const Nom & le_nom () const override
surcharge Objet_U::le_nom()
Renvoie le nom du shema en temps
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)=0
virtual void set_param (Param &titi)
int sauvegarder (Sortie &) const override
Sauvegarde le temps courant et le nombre de pas de temps
sur un flot de sortie.
int reprendre (Entree &) override
Reprise (lecture) du temps courant et du nombre de pas de
temps effectues a partir d'un flot d'entree.
virtual int mettre_a_jour ()
Mise a jour du temps courant (t+=dt)
et du nombre de pas de temps effectue (nb_pas_dt_++).
virtual void mettre_a_jour_dt (double toto)
virtual void mettre_a_jour_dt_stab ()
double pas_de_temps () const
Renvoie le pas de temps (delta_t) courant.
const DoubleTab & pas_de_temps_locaux () const
virtual bool corriger_dt_calcule (double &dt) const
Corrige le pas de temps calcule que l'on passe en parametre
et verifie qu'il n'est pas "trop" petit (< dt-min_).
La correction est la suivante:
delta_t = min((facteur de securite * dt_calc), dt_max)
Et on verifie que delta_t est "suffisamment" plus grand que dt_min_.
virtual void imprimer (Sortie &os) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
virtual int impr (Sortie &os) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
void imprimer (Sortie &os, Probleme_base &pb) const
Imprime le pas de temps sur un flot de sortie s'il y a lieu.
void imprimer (Sortie &os, const Probleme_base &pb) const
virtual int impr (Sortie &os, Probleme_base &pb) const
Impression du numero du pas de temps, la valeur du pas de temps.
et du temps courant.
virtual int impr (Sortie &os, const Probleme_base &pb) const
void imprimer_temps_courant (SFichier &) const
double pas_temps_min () const
Renvoie le pas de temps minimum.
(version const)
double & pas_temps_min ()
Renvoie une reference sur le pas de temps minimum.
double pas_temps_max () const
Renvoie le pas de temps maximum.
(version const)
double & pas_temps_max ()
Renvoie une reference sur le pas de temps maximum.
int nb_impr () const
Renvoie le nombre d'impressions effectuees.
double temps_courant () const
Renvoie le temps courant.
double temps_precedent () const
Renvoie le temps courant.
double temps_calcul () const
Renvoie le temps de calcul ecoule i.e. (temps courant - temps initial).
virtual void changer_temps_courant (const double)
Change le temps courant.
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
//Actualisation de stationnaire_atteint_ et residu_
(critere residu_<seuil_statio_)
double facteur_securite_pas () const
Renvoie le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
(version const)
double & facteur_securite_pas ()
Renvoie une reference sur le facteur de securite ou multiplicateur de delta_t.
Ce facteur est utilise lors de la correction/verification du
pas de temps. Voir Schema_Temps_base::corriger_dt_calcule(double&)
virtual int stop () const
Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
- le temps final est atteint
- le nombre de pas de temps maximum est depasse
- l'etat stationnaire est atteint
- indicateur d'arret fichier (voir int Schema_Temps_base::stop_lu())
Renvoie 0 sinon.
int lsauv () const
int temps_final_atteint () const
Renvoie 1 si le temps final est atteint (ou depasse).
Renvoie 1 si temps_courant_ >= tmax
Renvoie 0 sinon.
int nb_pas_dt_max_atteint () const
Renvoie 1 si (le nombre de pas de temps >= nombre de pas de temps maximum).
Renvoie 0 sinon.
int temps_cpu_max_atteint () const
int stationnaire_atteint () const
int stop_lu () const
Renvoie 1 si le fichier (d'extension) .stop contient un 1
Renvoie 0 sinon.
int diffusion_implicite () const
Renvoie 1 si le schema en temps a ete lu diffusion_implicite.
double seuil_diffusion_implicite () const
int impr_diffusion_implicite () const
Seuil pour implicitation de la diffusion par GC.
int impr_extremums () const
Impression ou non de GC implicitation.
int niter_max_diffusion_implicite () const
int no_conv_subiteration_diffusion_implicite () const
Iterations maximale pour GC implicitation.
int no_error_if_not_converged_diffusion_implicite () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual Entree & lire_nb_pas_dt_max (Entree &)
virtual Entree & lire_periode_sauvegarde_securite_en_heures (Entree &)
virtual Entree & lire_temps_cpu_max (Entree &)
virtual void completer ()=0
double temps_init () const
Renvoie le temps initial.
double temps_max () const
Renvoie une reference sur le temps maximum.
double temps_sauv () const
Renvoie une reference sur le temps de sauvegarde.
double temps_impr () const
Renvoie une reference sur le temps d'impression.
int precision_impr () const
int wcol () const
int gnuplot_header () const
double seuil_statio () const
Renvoie une reference sur le seuil stationnaire.
int nb_pas_dt_max () const
Renvoie une reference sur le nombre de pas maxi.
int nb_pas_dt () const
Renvoie le nombre de pas de temps effectues.
double mode_dt_start () const
int indice_tps_final_atteint () const
int indice_nb_pas_dt_max_atteint () const
int lu () const
int file_allocation () const
double & set_temps_init ()
double & set_temps_max ()
double & set_temps_courant ()
double & set_temps_precedent ()
int & set_nb_pas_dt ()
int & set_nb_pas_dt_max ()
double & set_dt_min ()
double & set_dt_max ()
double & set_dt_sauv ()
double & set_dt_impr ()
int & set_precision_impr ()
double & set_dt ()
double & set_facsec ()
double & set_seuil_statio ()
int & set_stationnaire_atteint ()
void set_stationnaires_atteints (bool flag)
int & set_diffusion_implicite ()
double & set_seuil_diffusion_implicite ()
int & set_niter_max_diffusion_implicite ()
double & set_mode_dt_start ()
int & set_indice_tps_final_atteint ()
int & set_indice_nb_pas_dt_max_atteint ()
int & set_lu ()
const double & residu () const
double & residu ()
int & schema_impr ()
const int & schema_impr () const
virtual void associer_pb (const Probleme_base &)
Probleme_base & pb_base ()
const Probleme_base & pb_base () const
virtual void modifier_second_membre (const Equation_base &eqn, DoubleTab &secmem)
virtual void ajouter_inertie (Matrice_Base &mat_morse, DoubleTab &secmem, const Equation_base &eqn) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const Equation_base &eqn, const tabs_t &semi_impl={}) const
int disable_progress () const
int disable_dt_ev () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Schema_Adams_Moulton_base & self_cast (Objet_U &)
static const Schema_Adams_Moulton_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Schema_Implicite_Multi_TimeStep_base
static const Type_info * info ()
static Schema_Implicite_Multi_TimeStep_base & self_cast (Objet_U &)
static const Schema_Implicite_Multi_TimeStep_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Schema_Implicite_base
static const Type_info * info ()
static Schema_Implicite_base & self_cast (Objet_U &)
static const Schema_Implicite_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Schema_Temps_base
static const Type_info * info ()
static Schema_Temps_base & self_cast (Objet_U &)
static const Schema_Temps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Schema_Implicite_Multi_TimeStep_base
static const Type_info info_obj
Static Public Attributes inherited from Schema_Implicite_base
static const Type_info info_obj
Static Public Attributes inherited from Schema_Temps_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
virtual void compute_adams_moulton_coefficients (double time_step, const DoubleTab &times) const =0
Protected Member Functions inherited from Schema_Implicite_Multi_TimeStep_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
void authorized_equation (const Equation_base &eqn)
void authorized_equation (const Equation_base &eqn) const
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Entree & readOn (Entree &) override
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
DoubleTab adams_moulton_coefficients_
Protected Attributes inherited from Schema_Implicite_Multi_TimeStep_base
int nb_ite_max
double residu_old_
double facsec_max_
int nb_ite_sans_accel_
Protected Attributes inherited from Schema_Implicite_base
Solveur_Implicite le_solveur
Protected Attributes inherited from Schema_Temps_base
Ref_Probleme_base mon_probleme
Nom nom_
double dt_
Pas de temps de calcul.
DoubleTab dt_locaux_
Local time steps: Vector of size nb faces of the mesh.
double temps_courant_
double temps_precedent_
double dt_failed_
double dt_gf_
double tinit_
double tmax_
double tcpumax_
int nb_pas_dt_
int nb_pas_dt_max_
int nb_impr_
double dt_min_
Pas de temps min fixe par l'utilisateur.
double dt_max_
Pas de temps max fixe par l'utilisateur.
Nom dt_max_str_
Parser_U dt_max_fn_
double dt_stab_
Pas de temps de stabilite.
double facsec_
double seuil_statio_
int seuil_statio_relatif_deconseille_
Drapeau pour specifier si seuil_statio_ est une valeur absolue (defaut) ou relative.
double dt_sauv_
double limite_cpu_sans_sauvegarde_
double periode_cpu_sans_sauvegarde_
double temps_cpu_ecoule_
double dt_impr_
Pas de temps d'impression.
int precision_impr_
Nombre de chiffres significatifs impression.
double mode_dt_start_
mode calcul du pas de temps de depart
double residu_
Residu.
double residu_old_slope_
double cumul_slope_
int gnuplot_header_
int ind_tps_final_atteint
int ind_nb_pas_dt_max_atteint
int ind_temps_cpu_max_atteint
int lu_
int ind_diff_impl_
double seuil_diff_impl_
int impr_diff_impl_
int impr_extremums_
int niter_max_diff_impl_
int no_conv_subiteration_diff_impl_
int no_error_if_not_converged_diff_impl_
int schema_impr_
1 si le schema a le droit d'imprimer dans le .out et dt_ev
int file_allocation_
1 = allocation espace disque (par defaut), 0 sinon
int max_length_cl_
Detailed Description
Definition at line 30 of file Schema_Adams_Moulton_base.h.
Constructor & Destructor Documentation
Schema_Adams_Moulton_base()
Schema_Adams_Moulton_base::Schema_Adams_Moulton_base ()
class Schema_Adams_Moulton_base
Definition at line 32 of file Schema_Adams_Moulton_base.cpp.
~Schema_Adams_Moulton_base()
Schema_Adams_Moulton_base::~Schema_Adams_Moulton_base () override
Definition at line 32 of file Schema_Adams_Moulton_base.cpp.
Member Function Documentation
add_multi_timestep_data()
void Schema_Adams_Moulton_base::add_multi_timestep_data (const Equation_base & eqn, Matrice_Base & mat_morse, DoubleTab & secmem) const override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 84 of file Schema_Adams_Moulton_base.cpp.
{
  Equation_base& eqn_bis         = ref_cast_non_const(Equation_base,eqn);
  double time_step               = pas_de_temps();
  double effective_time_step     = -1.;
  double scaling                 = -1.;
// Remark for "pen" interger : we do not penalize matrices and right members even in the case
// of Dirichlet or Symetrie boundary conditions
  int pen    = 0;
  int offset = 0;
  int i      = 0;
  effective_time_step     = coefficients()[nb_valeurs_passees()+1] * time_step;
  scaling                 = 1./coefficients()[nb_valeurs_passees()+1];
// Modification due to pressure gradient
  DoubleTab correction(eqn.inconnue().valeurs());
  correction = 0.;
  eqn_bis.corriger_derivee_expl(correction);
  correction *= (scaling-1.);
  secmem     += correction;
// Modification due to present time and past times
  DoubleTab dudt(eqn.inconnue().passe(1)); //due to Initialiser_Champs() offset
  DoubleTab tmp(dudt);
  for (i=0; i<nb_valeurs_passees()+1; ++i)
    {
      offset  = nb_valeurs_passees()-i; //present time if offset==0 else past times
      tmp     = eqn.derivee_en_temps().passe(offset);
      tmp    *= coefficients()[i] * time_step;
      dudt   += tmp;
    }
  eqn.solv_masse().ajouter_masse(effective_time_step,secmem,dudt,pen);
  eqn.solv_masse().ajouter_masse(effective_time_step,mat_morse,pen);
}
References Solveur_Masse::ajouter_masse(), coefficients(), Equation_base::corriger_derivee_expl(), Equation_base::derivee_en_temps(), Equation_base::inconnue(), Schema_Implicite_Multi_TimeStep_base::nb_valeurs_passees(), Schema_Temps_base::pas_de_temps(), Champ_Inc::passe(), ref_cast_non_const, Equation_base::solv_masse(), and Champ_Inc::valeurs().
associer_pb()
void Schema_Adams_Moulton_base::associer_pb (const Probleme_base & un_probleme) override virtual
Reimplemented from Schema_Temps_base.
Definition at line 51 of file Schema_Adams_Moulton_base.cpp.
{
  Schema_Implicite_Multi_TimeStep_base::associer_pb(un_probleme);
// Loop on equations
  for (int i=0; i<pb_base().nombre_d_equations(); i++)
    pb_base().equation(i).set_calculate_time_derivative(1);
}
References Schema_Temps_base::associer_pb(), Probleme_base::equation(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), and Equation_base::set_calculate_time_derivative().
changer_temps()
double Schema_Adams_Moulton_base::changer_temps (Equation_base & eqn, const double temps) override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 59 of file Schema_Adams_Moulton_base.cpp.
{
  eqn.inconnue().valeur().Champ_base::changer_temps(temps);
  eqn.derivee_en_temps().valeur().Champ_base::changer_temps(temps);
  return temps;
}
References Equation_base::derivee_en_temps(), Equation_base::inconnue(), and Deriv_Champ_Inc_base::valeur().
coefficients() [1/2]
const DoubleTab & Schema_Adams_Moulton_base::coefficients () const inline override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 57 of file Schema_Adams_Moulton_base.h.
{
  return adams_moulton_coefficients_;
}
References adams_moulton_coefficients_.
Referenced by add_multi_timestep_data(), and modifier_second_membre_full_impl().
coefficients() [2/2]
DoubleTab & Schema_Adams_Moulton_base::coefficients () inline override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 62 of file Schema_Adams_Moulton_base.h.
{
  return adams_moulton_coefficients_;
}
References adams_moulton_coefficients_.
compute_adams_moulton_coefficients()
virtual void Schema_Adams_Moulton_base::compute_adams_moulton_coefficients (double time_step, const DoubleTab & times) const protected pure virtual
Implemented in Schema_Adams_Moulton_order_2, and Schema_Adams_Moulton_order_3.
Referenced by compute_coefficients().
compute_coefficients()
void Schema_Adams_Moulton_base::compute_coefficients (double time_step, const DoubleTab & times) const override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 79 of file Schema_Adams_Moulton_base.cpp.
{
  compute_adams_moulton_coefficients(time_step,times);
}
References compute_adams_moulton_coefficients().
get_info()
const Type_info * Schema_Adams_Moulton_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Adams_Moulton_order_2, and Schema_Adams_Moulton_order_3.
Definition at line 32 of file Schema_Adams_Moulton_base.cpp.
info()
const Type_info * Schema_Adams_Moulton_base::info () static
Definition at line 32 of file Schema_Adams_Moulton_base.cpp.
mettre_a_jour_equation()
void Schema_Adams_Moulton_base::mettre_a_jour_equation (Equation_base & eqn, const double temps) override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 73 of file Schema_Adams_Moulton_base.cpp.
{
  eqn.inconnue().mettre_a_jour(temps);
  eqn.derivee_en_temps().mettre_a_jour(temps);
}
References Equation_base::derivee_en_temps(), Equation_base::inconnue(), and Champ_Inc::mettre_a_jour().
modifier_second_membre_full_impl()
void Schema_Adams_Moulton_base::modifier_second_membre_full_impl (const Equation_base & eqn, DoubleTab & secmem) override virtual
Reimplemented from Schema_Implicite_Multi_TimeStep_base.
Definition at line 125 of file Schema_Adams_Moulton_base.cpp.
{
  Equation_base& eqn_bis = ref_cast_non_const(Equation_base,eqn);
  DoubleTab correction(secmem);
  correction=0.;
  eqn_bis.corriger_derivee_expl(correction);
  eqn.solv_masse().appliquer(correction);
  secmem-=correction; //on enleve le gradient de pression
  if (nb_pas_dt()>nb_pas_dt_seuil())
    {
      int i = 0;
      int offset = 0;
      double scaling = 1./coefficients()[nb_valeurs_passees()+1];
      for (i=0; i<nb_valeurs_passees()+1; ++i )
        {
          offset      = nb_valeurs_passees() - i;
          correction  = eqn.derivee_en_temps().passe(offset);//present time if i==nb_valeurs_passees() else past times
          correction *= coefficients()[i];
          secmem     -= correction;
        }
      secmem *= scaling;
    }
}
References Solveur_Masse::appliquer(), coefficients(), Equation_base::corriger_derivee_expl(), Equation_base::derivee_en_temps(), Schema_Temps_base::nb_pas_dt(), Schema_Implicite_Multi_TimeStep_base::nb_pas_dt_seuil(), Schema_Implicite_Multi_TimeStep_base::nb_valeurs_passees(), Champ_Inc::passe(), ref_cast_non_const, and Equation_base::solv_masse().
Referenced by update_time_derivative().
modify_equation_parameters()
void Schema_Adams_Moulton_base::modify_equation_parameters (Equation_base & eqn, DoubleTab & stored_parameters) override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 160 of file Schema_Adams_Moulton_base.cpp.
{
// Nothing to do
}
printOn()
Sortie & Schema_Adams_Moulton_base::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime le schema en temps sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les differents parametres du schema en temps.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Adams_Moulton_order_2, and Schema_Adams_Moulton_order_3.
Definition at line 38 of file Schema_Adams_Moulton_base.cpp.
{
  return  Schema_Implicite_base::printOn(s);
}
References Schema_Implicite_base::printOn().
Referenced by Schema_Adams_Moulton_order_2::printOn(), and Schema_Adams_Moulton_order_3::printOn().
readOn()
Entree & Schema_Adams_Moulton_base::readOn (Entree & is) override protected virtual
Lecture d'un schema en temps a partir d'un flot d'entree.
Le format de lecture attendu est le suivant:
{
[Motcle valeur_reelle]
}
Les mots clefs peuvent etre:
tinit, tmax, nb_pas_dt_max, dt_min, dt_max,
dt_sauv, dt_impr, facsec, seuil_statio,.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Adams_Moulton_order_2, and Schema_Adams_Moulton_order_3.
Definition at line 46 of file Schema_Adams_Moulton_base.cpp.
{
  return Schema_Implicite_Multi_TimeStep_base::readOn(s);
}
References Schema_Implicite_Multi_TimeStep_base::readOn().
Referenced by Schema_Adams_Moulton_order_2::readOn(), and Schema_Adams_Moulton_order_3::readOn().
self_cast() [1/2]
const Schema_Adams_Moulton_base & Schema_Adams_Moulton_base::self_cast (const Objet_U & r) static
Definition at line 32 of file Schema_Adams_Moulton_base.cpp.
self_cast() [2/2]
Schema_Adams_Moulton_base & Schema_Adams_Moulton_base::self_cast (Objet_U & r) static
Definition at line 32 of file Schema_Adams_Moulton_base.cpp.
store_equation_parameters()
void Schema_Adams_Moulton_base::store_equation_parameters (Equation_base & eqn, DoubleTab & stored_parameters) override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 154 of file Schema_Adams_Moulton_base.cpp.
{
// Nothing to do
}
update_time_derivative()
void Schema_Adams_Moulton_base::update_time_derivative (Equation_base & eqn, const DoubleTab & data) override virtual
Implements Schema_Implicite_Multi_TimeStep_base.
Definition at line 66 of file Schema_Adams_Moulton_base.cpp.
{
  DoubleTab& time_derivative = eqn.derivee_en_temps().futur();
  time_derivative = data;                                //here "data" is supposed to contain "vpoint" table
  modifier_second_membre_full_impl(eqn,time_derivative);
}
References Equation_base::derivee_en_temps(), Champ_Inc::futur(), and modifier_second_membre_full_impl().
Member Data Documentation
adams_moulton_coefficients_
DoubleTab Schema_Adams_Moulton_base::adams_moulton_coefficients_ mutable protected
Definition at line 54 of file Schema_Adams_Moulton_base.h.
Referenced by coefficients(), Schema_Adams_Moulton_order_2::compute_adams_moulton_coefficients(), and Schema_Adams_Moulton_order_3::compute_adams_moulton_coefficients().
info_obj
const Type_info Schema_Adams_Moulton_base::info_obj static
Definition at line 32 of file Schema_Adams_Moulton_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Adams_Moulton_base.h
src/Kernel/Schemas_Temps/Schema_Adams_Moulton_base.cpp