TRUST: Terme_Puissance_Thermique Class Reference
Terme_Puissance_Thermique Class Reference
Classe Terme_Puissance_Thermique
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique.
Un objet Terme_Puissance_Thermique contient la puissance (Champ donne
utilisateur) et des references a la masse volumique (rho) et la chaleur.
specifique (Cp).
#include <Terme_Puissance_Thermique.h>
Public Member Functions
void preparer_source (const Probleme_base &pb)
void associer_champs (const Champ_base &, const Champ_Don &)
Associe les champs donnes rho (masse volumique)
et Cp (chaleur specifique) a l'objet.
void lire_donnees (Entree &, const Equation_base &eqn)
Lit le terme de puissance thermique a partir
d'un flot d'entree et d une equation pour eventuellement
acceder a la discretisation afin de typer la_puissance.
Lit uniquement un champ donne representant la_puissance.
void mettre_a_jour (double temps)
void modify_name_file (Nom &) const
const DoubleTab & puissance_thermique () const
void initialiser_champ_puissance (const Equation_base &eqn)
Protected Attributes
Ref_Champ_base rho_ref
Ref_Champ_Don Cp
Champ_Don la_puissance_lu
Champ_Don la_puissance
Detailed Description
Classe Terme_Puissance_Thermique
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique.
Un objet Terme_Puissance_Thermique contient la puissance (Champ donne
utilisateur) et des references a la masse volumique (rho) et la chaleur.
specifique (Cp).
Definition at line 49 of file Terme_Puissance_Thermique.h.
Member Function Documentation
void Terme_Puissance_Thermique::associer_champs (const Champ_base & rho, const Champ_Don & cp) [inline]
Associe les champs donnes rho (masse volumique)
et Cp (chaleur specifique) a l'objet.
Definition at line 95 of file Terme_Puissance_Thermique.h.
Referenced by preparer_source().
{
  rho_ref=rho;
  Cp=cp;
}
void Terme_Puissance_Thermique::initialiser_champ_puissance (const Equation_base & eqn)
Definition at line 83 of file Terme_Puissance_Thermique.cpp.
References Champ_val_tot_sur_vol_base::evaluer(), la_puissance_lu, ref_cast, sub_type, Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Deriv_Champ_Don_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
Referenced by Terme_Puissance_Thermique_VEF_base::initialiser(), Terme_Puissance_Thermique_VDF_base::initialiser(), Terme_Puissance_Thermique_PolyMAC_base::initialiser(), and Terme_Puissance_Thermique_CoviMAC_base::initialiser().
{
  if (sub_type(Champ_val_tot_sur_vol_base,la_puissance_lu.valeur()))
    {
      const Zone_dis_base& zdis = eqn.zone_dis().valeur();
      const Zone_Cl_dis_base& zcldis = eqn.zone_Cl_dis().valeur();
      Champ_val_tot_sur_vol_base& champ_puis = ref_cast(Champ_val_tot_sur_vol_base,la_puissance_lu.valeur());
      champ_puis.evaluer(zdis,zcldis);
    }
}
void Terme_Puissance_Thermique::lire_donnees (Entree & is, const Equation_base & eqn)
Lit le terme de puissance thermique a partir
d'un flot d'entree et d une equation pour eventuellement
acceder a la discretisation afin de typer la_puissance.
Lit uniquement un champ donne representant la_puissance.
Definition at line 50 of file Terme_Puissance_Thermique.cpp.
References Champ_base::affecter(), Cerr, Nom::debute_par(), Equation_base::discretisation(), Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), finl, la_puissance, la_puissance_lu, O_U_Ptr::le_nom(), Field_base::nb_comp(), Objet_U::nommer(), Discretisation_base::nommer_completer_champ_physique(), Equation_base::probleme(), Objet_U::que_suis_je(), ref_cast, Deriv_::typer(), Deriv_Champ_Don_base::valeur(), Deriv_Zone_dis_base::valeur(), Champ_Don_base::valeurs(), and Equation_base::zone_dis().
Referenced by Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Puissance_Thermique_QC_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Puissance_Thermique_EF::readOn(), and Terme_Puissance_Thermique_CoviMAC_base::readOn().
{
  Cerr << "Lecture du Champ Puissance" << finl;
  Motcle type;
  is >> type;
  if (type=="Valeur_totale_sur_volume")
    {
      const Zone_dis_base& zdis = eqn.zone_dis().valeur();
      const Nom& type_zdis = zdis.que_suis_je();
      if (type_zdis.debute_par("Zone_VDF"))
        type += "_VDF";
      else  if (type_zdis.debute_par("Zone_VEF"))
        type += "_VEF";
    }
  la_puissance_lu.typer(type);
  Champ_Don_base& ch_puissance_lu = ref_cast(Champ_Don_base,la_puissance_lu.valeur());
  is >> ch_puissance_lu;
  const int nb_comp = ch_puissance_lu.nb_comp();
  eqn.probleme().discretisation().discretiser_champ("CHAMP_ELEM", eqn.zone_dis(), "pp", "1",nb_comp,0., la_puissance);
  la_puissance_lu->fixer_nb_comp(nb_comp);
  if (ch_puissance_lu.le_nom()=="anonyme") ch_puissance_lu.nommer("Puissance_volumique");
  for (int n = 0; n < nb_comp; n++) la_puissance_lu->fixer_nom_compo(n, ch_puissance_lu.le_nom() + (nb_comp > 1 ? Nom(n) :""));
  for (int n = 0; n < nb_comp; n++) la_puissance->fixer_nom_compo(n, ch_puissance_lu.le_nom() + (nb_comp > 1 ? Nom(n) :""));
// PL: Il faut faire nommer_completer_champ_physique les 2 champs (plantage sinon pour une puissance de type Champ_fonc_tabule)
  eqn.discretisation().nommer_completer_champ_physique(eqn.zone_dis(),ch_puissance_lu.le_nom(),"W/m3",la_puissance_lu,eqn.probleme());
  eqn.discretisation().nommer_completer_champ_physique(eqn.zone_dis(),ch_puissance_lu.le_nom(),"W/m3",la_puissance,eqn.probleme());
  la_puissance.valeur().valeurs() = 0;
  la_puissance.valeur().affecter(ch_puissance_lu);
}
void Terme_Puissance_Thermique::mettre_a_jour (double temps)
Reimplemented in Terme_Puissance_Thermique_CoviMAC_Elem, Puissance_Thermique_EF, Terme_Puissance_Thermique_PolyMAC_Elem, Puissance_Thermique_QC_EF, Terme_Puissance_Thermique_QC_VDF_Elem, Terme_Puissance_Thermique_QC_VEF_Face, Source_Neutronique, Source_Dirac_VDF_Elem, Terme_Puissance_Thermique_VDF_Elem, Source_Dirac_VEF_Face, and Terme_Puissance_Thermique_VEF_Face.
Definition at line 94 of file Terme_Puissance_Thermique.cpp.
References Champ_base::affecter(), la_puissance, la_puissance_lu, Champ_Don::mettre_a_jour(), and Deriv_Champ_Don_base::valeur().
Referenced by Terme_Puissance_Thermique_VEF_Face::mettre_a_jour(), Source_Dirac_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_VDF_Elem::mettre_a_jour(), Source_Dirac_VDF_Elem::mettre_a_jour(), Terme_Puissance_Thermique_QC_VEF_Face::mettre_a_jour(), Terme_Puissance_Thermique_QC_VDF_Elem::mettre_a_jour(), Terme_Puissance_Thermique_PolyMAC_Elem::mettre_a_jour(), and Terme_Puissance_Thermique_CoviMAC_Elem::mettre_a_jour().
{
  la_puissance_lu.mettre_a_jour(temps);
  la_puissance.valeur().affecter(la_puissance_lu.valeur());
}
void Terme_Puissance_Thermique::modify_name_file (Nom & fichier) const
Definition at line 116 of file Terme_Puissance_Thermique.cpp.
References la_puissance, and O_U_Ptr::le_nom().
Referenced by Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), and Terme_Puissance_Thermique_CoviMAC_base::readOn().
{
  if (la_puissance.le_nom()!="Puissance_volumique")
    {
      fichier+="_";
      fichier+=la_puissance.le_nom();
    }
}
void Terme_Puissance_Thermique::preparer_source (const Probleme_base & pb)
Definition at line 100 of file Terme_Puissance_Thermique.cpp.
References associer_champs(), Milieu_base::capacite_calorifique(), Cerr, Process::exit(), finl, Probleme_base::is_dilatable(), Milieu_base::masse_volumique(), Probleme_base::milieu(), and O_U_Ptr::non_nul().
Referenced by Terme_Puissance_Thermique_VEF_Face::associer_pb(), Source_Dirac_VEF_Face::associer_pb(), Terme_Puissance_Thermique_VDF_Elem::associer_pb(), Source_Neutronique_VDF::associer_pb(), Source_Dirac_VDF_Elem::associer_pb(), Terme_Puissance_Thermique_QC_VEF_Face::associer_pb(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_pb(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), and Terme_Puissance_Thermique_CoviMAC_Elem::associer_pb().
{
  if (!pb.is_dilatable())
    {
      if (!pb.milieu().capacite_calorifique().non_nul())
        {
          Cerr << "La capacite calorifique Cp n'est pas definie..." << finl;
          Cerr << "Elle est necessaire pour la definition du terme source puissance thermique." << finl;
          Process::exit();
        }
      const Champ_Don& le_Cp = pb.milieu().capacite_calorifique();
      const Champ_base& rho = pb.milieu().masse_volumique();
      associer_champs(rho, le_Cp);
    }
}
const DoubleTab& Terme_Puissance_Thermique::puissance_thermique () const [inline]
Definition at line 59 of file Terme_Puissance_Thermique.h.
References la_puissance, and Champ_Don::valeurs().
  {
    return la_puissance->valeurs();
  }
Member Data Documentation
Ref_Champ_Don Terme_Puissance_Thermique::Cp [protected]
Definition at line 68 of file Terme_Puissance_Thermique.h.
Referenced by Source_Neutronique_VDF::associer_pb().
Champ_Don Terme_Puissance_Thermique::la_puissance [protected]
Definition at line 69 of file Terme_Puissance_Thermique.h.
Referenced by Terme_Puissance_Thermique_VEF_Face::associer_pb(), Source_Dirac_VEF_Face::associer_pb(), Terme_Puissance_Thermique_VDF_Elem::associer_pb(), Source_Neutronique_VDF::associer_pb(), Source_Dirac_VDF_Elem::associer_pb(), Terme_Puissance_Thermique_QC_VEF_Face::associer_pb(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_pb(), Puissance_Thermique_QC_EF::associer_pb(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), Puissance_Thermique_EF::associer_pb(), Terme_Puissance_Thermique_CoviMAC_Elem::associer_pb(), lire_donnees(), mettre_a_jour(), Source_Neutronique::mettre_a_jour(), modify_name_file(), puissance_thermique(), Terme_Puissance_Thermique_VEF_base::readOn(), Terme_Puissance_Thermique_VDF_base::readOn(), Source_Neutronique::readOn(), Puissance_Thermique_QC_EF::readOn(), Terme_Puissance_Thermique_PolyMAC_base::readOn(), Puissance_Thermique_EF::readOn(), and Terme_Puissance_Thermique_CoviMAC_base::readOn().
Champ_Don Terme_Puissance_Thermique::la_puissance_lu [protected]
Definition at line 69 of file Terme_Puissance_Thermique.h.
Referenced by initialiser_champ_puissance(), lire_donnees(), and mettre_a_jour().
Ref_Champ_base Terme_Puissance_Thermique::rho_ref [protected]
Definition at line 67 of file Terme_Puissance_Thermique.h.
Referenced by Source_Neutronique_VDF::associer_pb().
The documentation for this class was generated from the following files:
src/ThSol/Terme_Puissance_Thermique.h
src/ThSol/Terme_Puissance_Thermique.cpp