TRUST: Format_Post Class Reference
Format_Post Class Reference
#include <Format_Post.h>
Public Member Functions
Format_Post ()
~Format_Post ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void typer_direct (const Nom &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Format_Post & self_cast (Objet_U &)
static const Format_Post & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Impression de Format_Post sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture de Format_Post sur un flot d'entree.
Detailed Description
Definition at line 28 of file Format_Post.h.
Constructor & Destructor Documentation
Format_Post::Format_Post ()
Definition at line 28 of file Format_Post.cpp.
Format_Post::~Format_Post ()
Definition at line 28 of file Format_Post.cpp.
Member Function Documentation
Objet_U * Format_Post::cree_instance () [static]
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
int Format_Post::duplique () const [virtual]
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
const Type_info * Format_Post::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
const Type_info * Format_Post::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
Sortie & Format_Post::printOn (Sortie & os) const [protected, virtual]
Impression de Format_Post sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Format_Post_base.
Definition at line 45 of file Format_Post.cpp.
References DERIV.
{
  return DERIV(Format_Post_base)::printOn(os);
}
Entree & Format_Post::readOn (Entree & is) [protected, virtual]
Lecture de Format_Post sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Format_Post_base.
Definition at line 65 of file Format_Post.cpp.
References DERIV.
{
  return DERIV(Format_Post_base)::readOn(is);
}
const Format_Post & Format_Post::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
Format_Post & Format_Post::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
unsigned Format_Post::taille_memoire () const [virtual]
Reimplemented from Deriv_Format_Post_base.
Definition at line 28 of file Format_Post.cpp.
void Format_Post::typer_direct (const Nom & typ)
Definition at line 84 of file Format_Post.cpp.
References DERIV, and Deriv_::typer().
Referenced by Postraiter_domaine::ecrire(), latatoother::interpreter(), Ecrire_Champ_MED::interpreter(), and Postraitement::readOn().
{
  DERIV(Format_Post_base)::typer(typ);
}
Member Data Documentation
const Type_info Format_Post::info_obj [static]
Reimplemented from Deriv_Format_Post_base.
Definition at line 30 of file Format_Post.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Format_Post.h
src/Kernel/Framework/Format_Post.cpp