TRUST: Correlation_Vec_Sca_VDF Class Reference
Correlation_Vec_Sca_VDF Class Reference
classe Correlation_Vec_Sca_VDF
#include <Correlation_Vec_Sca_VDF.h>
Public Member Functions
Correlation_Vec_Sca_VDF ()
~Correlation_Vec_Sca_VDF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
const Champ_base & mon_champ_Vec () const
const Champ_base & mon_champ_Sca () const
void mettre_a_jour (double)
Mise a jour en temps du champ.
void associer_champ_Vec (const Champ_base &)
void associer_champ_Sca (const Champ_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Correlation_Vec_Sca_VDF & self_cast (Objet_U &)
static const
Correlation_Vec_Sca_VDF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Ref_Champ_base mon_champ_Vec_
Ref_Champ_base mon_champ_Sca_
Detailed Description
classe Correlation_Vec_Sca_VDF
Definition at line 37 of file Correlation_Vec_Sca_VDF.h.
Constructor & Destructor Documentation
Correlation_Vec_Sca_VDF::Correlation_Vec_Sca_VDF ()
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
Correlation_Vec_Sca_VDF::~Correlation_Vec_Sca_VDF ()
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
Member Function Documentation
void Correlation_Vec_Sca_VDF::associer_champ_Sca (const Champ_base & le_champ_Sca)
Definition at line 49 of file Correlation_Vec_Sca_VDF.cpp.
References mon_champ_Sca_.
{
  mon_champ_Sca_= le_champ_Sca;
}
void Correlation_Vec_Sca_VDF::associer_champ_Vec (const Champ_base & le_champ_Vec)
Definition at line 44 of file Correlation_Vec_Sca_VDF.cpp.
References mon_champ_Vec_.
{
  mon_champ_Vec_= le_champ_Vec;
}
Objet_U * Correlation_Vec_Sca_VDF::cree_instance () [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
int Correlation_Vec_Sca_VDF::duplique () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
const Type_info * Correlation_Vec_Sca_VDF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
const Type_info * Correlation_Vec_Sca_VDF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
void Correlation_Vec_Sca_VDF::mettre_a_jour (double temps) [inline, virtual]
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 67 of file Correlation_Vec_Sca_VDF.h.
References Champ_base::changer_temps(), Objet_U::dimension, Champ_Fonc_P0_VDF::la_zone_VDF, mon_champ_Sca_, mon_champ_Vec_, Zone::nb_elem(), Ref_Zone_VDF::valeur(), Champ_Don_base::valeurs(), and Zone_dis_base::zone().
{
  int nb_elem=la_zone_VDF.valeur().zone().nb_elem();
  const DoubleTab& centres_de_gravites = la_zone_VDF->xp();
  DoubleTab& correlation = valeurs();
  int elem, ncom;
// Interpolation du champ scalaire de la correlation au
// centre des mailles.
  DoubleTab valeurs_Sca(nb_elem, mon_champ_Sca_->nb_comp());
  mon_champ_Sca_->valeur_aux_centres_de_gravite(centres_de_gravites, valeurs_Sca);
// Interpolation du champ vecteur de la correlation au
// centre des mailles.
  DoubleTab valeurs_Vec(nb_elem, mon_champ_Vec_->nb_comp());
  mon_champ_Vec_->valeur_aux_centres_de_gravite(centres_de_gravites, valeurs_Vec);
  for(elem=0; elem<nb_elem; elem++)
    {
      correlation(elem,0) = valeurs_Sca(elem,0);
      for (ncom=0; ncom<dimension; ncom++)
        correlation(elem,ncom+1) = valeurs_Vec(elem,ncom);
    }
  changer_temps(tps);
  Champ_Fonc_base::mettre_a_jour(tps);
}
const Champ_base & Correlation_Vec_Sca_VDF::mon_champ_Sca () const [inline]
Definition at line 62 of file Correlation_Vec_Sca_VDF.h.
References mon_champ_Sca_, and Ref_Champ_base::valeur().
{
  return mon_champ_Sca_.valeur();
}
const Champ_base & Correlation_Vec_Sca_VDF::mon_champ_Vec () const [inline]
Definition at line 57 of file Correlation_Vec_Sca_VDF.h.
{
  return mon_champ_Vec_.valeur();
}
Sortie & Correlation_Vec_Sca_VDF::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 31 of file Correlation_Vec_Sca_VDF.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  return s << que_suis_je() << " " << le_nom();
}
Entree & Correlation_Vec_Sca_VDF::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 39 of file Correlation_Vec_Sca_VDF.cpp.
{
  return s ;
}
const Correlation_Vec_Sca_VDF & Correlation_Vec_Sca_VDF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
Correlation_Vec_Sca_VDF & Correlation_Vec_Sca_VDF::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
unsigned Correlation_Vec_Sca_VDF::taille_memoire () const [virtual]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 25 of file Correlation_Vec_Sca_VDF.cpp.
Member Data Documentation
const Type_info Correlation_Vec_Sca_VDF::info_obj [static]
Reimplemented from Champ_Fonc_P0_VDF.
Definition at line 41 of file Correlation_Vec_Sca_VDF.h.
Ref_Champ_base Correlation_Vec_Sca_VDF::mon_champ_Sca_ [protected]
Definition at line 54 of file Correlation_Vec_Sca_VDF.h.
Referenced by associer_champ_Sca(), mettre_a_jour(), and mon_champ_Sca().
Ref_Champ_base Correlation_Vec_Sca_VDF::mon_champ_Vec_ [protected]
Definition at line 53 of file Correlation_Vec_Sca_VDF.h.
Referenced by associer_champ_Vec(), and mettre_a_jour().
The documentation for this class was generated from the following files:
src/VDF/Champs/Correlation_Vec_Sca_VDF.h
src/VDF/Champs/Correlation_Vec_Sca_VDF.cpp