TRUST: Terme_Source_Rappel_T_VEF_Face Class Reference
Terme_Source_Rappel_T_VEF_Face Class Reference
#include <Terme_Source_Rappel_T_VEF_Face.h>
Public Member Functions
Terme_Source_Rappel_T_VEF_Face ()
~Terme_Source_Rappel_T_VEF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Rappel_T_VEF_Face & self_cast (Objet_U &)
static const Terme_Source_Rappel_T_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Attributes
double alpha_tau
int fct_ok
Parser_U force_rappel
Ref_Champ_Inc_base l_inconnue
Ref_Zone_VEF zone_VEF_autre_pb
Nom nom_pb
Nom nom_autre_pb
Motcle nom_inco
ArrOfInt corresp_fin_gros
correspondance elem de l'autre pb vers elem du pb courant
ArrOfInt nb_fin
nb d'elements de l'autre pb par element du pb courant
ArrOfDouble vol_fin_tot
volume totale des elements fins s'appuyant un element grossier
Detailed Description
Definition at line 29 of file Terme_Source_Rappel_T_VEF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Rappel_T_VEF_Face()
Terme_Source_Rappel_T_VEF_Face::Terme_Source_Rappel_T_VEF_Face ()
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
~Terme_Source_Rappel_T_VEF_Face()
Terme_Source_Rappel_T_VEF_Face::~Terme_Source_Rappel_T_VEF_Face ()
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Terme_Source_Rappel_T_VEF_Face::ajouter (DoubleTab & resu) const override virtual
< valeurs sur les elems du pb courant du champ de l'autre pb.
nb_fin(corresp_fin_gros(i));
Reimplemented from Source_base.
Definition at line 168 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const int nb_faces = zone_VEF.nb_faces();
  const int premiere_face_std=zone_VEF.premiere_face_std();
  const int ndeb = zone_VEF.premiere_face_int();
  const int nb_elem = zone_VEF.nb_elem();
  const DoubleTab& temperature = mon_equation->inconnue().valeurs();
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = la_zone_Cl_VEF->volumes_entrelaces_Cl();
  const DoubleTab& xv=zone_VEF.xv() ;
  const double dt = mon_equation->schema_temps().pas_de_temps();
  const DoubleVect& volumes_autre_pb = zone_VEF_autre_pb->volumes();
  double vol;
  double force=0.;
  if (fct_ok == 1)
    {
      for(int num_face = 0 ; num_face<premiere_face_std ; num_face++)
        {
          vol = volumes_entrelaces_Cl(num_face);
          for (int i=0; i<dimension; i++)
            force_rappel.setVar(i,xv(num_face,i));
          force = force_rappel.eval();
          resu(num_face) += (force-temperature(num_face))/(alpha_tau*dt)*vol;
        }
      for(int num_face = 0 ; num_face<nb_faces ; num_face++)
        {
          vol = volumes_entrelaces(num_face);
          for (int i=0; i<dimension; i++)
            force_rappel.setVar(i,xv(num_face,i));
          force = force_rappel.eval();
          resu(num_face) += (force-temperature(num_face))/(alpha_tau*dt)*vol;
        }
    }
  else
    {
      const Zone_VEF& zoneVEF_autre_pb = ref_cast(Zone_VEF,l_inconnue->zone_dis_base());
      const int nb_elem_autre_pb = zoneVEF_autre_pb.nb_elem();
      const DoubleTab& xp=zoneVEF_autre_pb.xp() ;
      const IntTab& face_voisins=zone_VEF.face_voisins() ;
      ArrOfDouble val_elem(nb_elem); //!< valeurs sur les elems du pb courant du champ de l'autre pb.
      DoubleTab valeurs(nb_elem_autre_pb,l_inconnue->nb_comp()); //valeurs sur l'autre pb
      IntTab elems(nb_elem_autre_pb);
      for (int i=0; i<nb_elem_autre_pb; i++)
        elems(i)=i;
      l_inconnue->valeur_aux_elems(xp, elems, valeurs);
      val_elem=0.;
      for (int i=0; i<nb_elem_autre_pb; i++)
        {
          val_elem[corresp_fin_gros[i]] += valeurs(i,0)*volumes_autre_pb(i)/vol_fin_tot[corresp_fin_gros[i]] ; ///nb_fin(corresp_fin_gros(i));
        }
      for(int num_face = 0 ; num_face<ndeb ; num_face++)
        {
          vol = volumes_entrelaces_Cl(num_face);
          force = val_elem[face_voisins(num_face,0)];
          resu(num_face) += (force-temperature(num_face))/(alpha_tau*dt)*vol;
        }
      for(int num_face = ndeb ; num_face<premiere_face_std ; num_face++)
        {
          vol = volumes_entrelaces_Cl(num_face);
          force = 0.5*(val_elem[face_voisins(num_face,0)]+val_elem[face_voisins(num_face,1)]);
          if ((force!=0.))//&& (force-temperature(num_face)>0.))
            resu(num_face) += (force-temperature(num_face))/(alpha_tau*dt)*vol;
        }
      for(int num_face = premiere_face_std ; num_face<nb_faces ; num_face++)
        {
          vol = volumes_entrelaces(num_face);
          if ((val_elem[face_voisins(num_face,0)] !=0.) && (val_elem[face_voisins(num_face,1)] !=0.))
            force = 0.5*(val_elem[face_voisins(num_face,0)]+val_elem[face_voisins(num_face,1)]);
          else
            force = val_elem[face_voisins(num_face,0)]+val_elem[face_voisins(num_face,1)];
          if ((force!=0.))//&& (force-temperature(num_face)>0.))
            {
// Cout << "force = " << force << finl;
              resu(num_face) += (force-temperature(num_face))/(alpha_tau*dt)*vol;
            }
// Cout << "force-temperature(num_face) = " << force-temperature(num_face) << finl;
        }
    }
  return resu;
}
References alpha_tau, corresp_fin_gros, Objet_U::dimension, Parser_U::eval(), Zone_VF::face_voisins(), fct_ok, force_rappel, Equation_base::inconnue(), l_inconnue, la_zone_Cl_VEF, la_zone_VEF, MorEqn::mon_equation, Field_base::nb_comp(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Schema_Temps_base::pas_de_temps(), Zone_VF::premiere_face_int(), Zone_VEF::premiere_face_std(), ref_cast, Equation_base::schema_temps(), Parser_U::setVar(), Ref_Zone_VEF::valeur(), Champ_base::valeur_aux_elems(), Champ_Inc::valeurs(), vol_fin_tot, Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), Zone_Cl_VEF::volumes_entrelaces_Cl(), Zone_VF::xp(), Zone_VF::xv(), Champ_base::zone_dis_base(), and zone_VEF_autre_pb.
Referenced by calculer().
associer_pb()
void Terme_Source_Rappel_T_VEF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
Definition at line 114 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  ;
}
associer_zones()
void Terme_Source_Rappel_T_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 107 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  la_zone_VEF = ref_cast(Zone_VEF, zone_dis.valeur());
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer()
DoubleTab & Terme_Source_Rappel_T_VEF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
Definition at line 273 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References ajouter().
completer()
void Terme_Source_Rappel_T_VEF_Face::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 118 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  Source_base::completer();
  if (fct_ok == 0)
    {
      const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,equation().zone_dis().valeur());
      const Zone& zone = zone_VEF.zone();
      const int nb_elem = zone_VEF.nb_elem();
      Objet_U& ob1=Interprete::objet(nom_autre_pb);
      REF(Probleme_base) pb;
      if( sub_type(Probleme_base, ob1) )
        pb = ref_cast(Probleme_base, ob1);
      else
        {
          Cerr << "On ne trouve pas de probleme de nom " << nom_autre_pb << finl;
          exit();
        }
      REF(Champ_base) rch;
      rch = pb->get_champ(nom_inco);
      l_inconnue=ref_cast(Champ_Inc_base, rch.valeur()) ;
      zone_VEF_autre_pb = ref_cast(Zone_VEF,pb->domaine_dis().zone_dis(0).valeur());
      const int nb_elem_autre_pb = zone_VEF_autre_pb->nb_elem();
      const DoubleTab& xp_autre_pb = zone_VEF_autre_pb->xp() ;
      const DoubleVect& volumes = zone_VEF_autre_pb->volumes();
// Dimensionnement des tabs
      nb_fin.resize_array(nb_elem);
      corresp_fin_gros.resize_array(nb_elem_autre_pb);
      nb_fin=0;
      corresp_fin_gros=0;
      vol_fin_tot.resize_array(nb_elem);
      vol_fin_tot=0.;
// Calcul des connectivites entre les maillages des deux pbs
      zone.chercher_elements(xp_autre_pb, corresp_fin_gros);
      for (int i=0; i<nb_elem_autre_pb; i++)
        {
          assert(corresp_fin_gros[i]>0);
          nb_fin[corresp_fin_gros[i]]++;
          vol_fin_tot[corresp_fin_gros[i]] += volumes(i);
        }
    }
}
References Cerr, Zone::chercher_elements(), Source_base::completer(), corresp_fin_gros, Zone_dis_base::domaine_dis(), MorEqn::equation(), Process::exit(), fct_ok, finl, l_inconnue, Zone_dis_base::nb_elem(), nb_fin, nom_autre_pb, nom_inco, Interprete::objet(), REF, ref_cast, TRUSTArray< _TYPE_ >::resize_array(), sub_type, Deriv_Zone_dis_base::valeur(), valeur(), vol_fin_tot, Zone_VF::volumes(), Zone_VF::xp(), Zone_dis_base::zone(), Domaine_dis::zone_dis(), and zone_VEF_autre_pb.
cree_instance()
Objet_U * Terme_Source_Rappel_T_VEF_Face::cree_instance () static
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
duplique()
int Terme_Source_Rappel_T_VEF_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
get_info()
const Type_info * Terme_Source_Rappel_T_VEF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
info()
const Type_info * Terme_Source_Rappel_T_VEF_Face::info () static
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
mettre_a_jour()
void Terme_Source_Rappel_T_VEF_Face::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 39 of file Terme_Source_Rappel_T_VEF_Face.h.
{  } ;
printOn()
Sortie & Terme_Source_Rappel_T_VEF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 34 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Rappel_T_VEF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
< Expression de la force de rappel
< Expression de la force de rappel
Reimplemented from Source_base.
Definition at line 43 of file Terme_Source_Rappel_T_VEF_Face.cpp.
{
  Motcle mot_lu;
  Motcle acc_ouverte("{");
  Motcle acc_fermee("}");
  alpha_tau=1.;
  fct_ok=-1;
  Motcles les_mots(3);
  {
    les_mots[0]="alpha_tau"; //coeff de relaxation du terme source
    les_mots[1]="force_rappel"; //!< Expression de la force de rappel
    les_mots[2]="probleme"; //!< Expression de la force de rappel
  }
  is >> mot_lu;
  if(mot_lu != acc_ouverte)
    {
      Cerr << "On attendait { a la place de " << mot_lu
           << " lors de la lecture des parametres de la loi de paroi " << finl;
    }
  is >> mot_lu;
  while(mot_lu != acc_fermee)
    {
      int rang=les_mots.search(mot_lu);
      switch(rang)
        {
        case 0:
          is >> alpha_tau;
          break;
        case 1:
          {
            Nom tmp;
            is >> tmp;
            force_rappel.setNbVar(dimension);
            force_rappel.setString(tmp);
            force_rappel.addVar("x");
            force_rappel.addVar("y");
            if (dimension>2)
              force_rappel.addVar("z");
            force_rappel.parseString();
            fct_ok=1;
            break;
          }
        case 2:
          fct_ok=0;
          is >> nom_autre_pb >> nom_inco;
          break;
        default :
          {
            Cerr << mot_lu << " n'est pas un mot compris par Source_Canal_RANS_LES_VEF_P1NC" << finl;
            Cerr << "Les mots compris sont : " << les_mots << finl;
            exit();
          }
        }
      is >> mot_lu;
    }
  return is;
}
References Parser_U::addVar(), alpha_tau, Cerr, Objet_U::dimension, Process::exit(), fct_ok, finl, force_rappel, nom_autre_pb, nom_inco, Parser_U::parseString(), Motcles::search(), Parser_U::setNbVar(), and Parser_U::setString().
self_cast() [1/2]
const Terme_Source_Rappel_T_VEF_Face & Terme_Source_Rappel_T_VEF_Face::self_cast (const Objet_U & r) static
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
self_cast() [2/2]
Terme_Source_Rappel_T_VEF_Face & Terme_Source_Rappel_T_VEF_Face::self_cast (Objet_U & r) static
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Rappel_T_VEF_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 27 of file Terme_Source_Rappel_T_VEF_Face.cpp.
Member Data Documentation
alpha_tau
double Terme_Source_Rappel_T_VEF_Face::alpha_tau private
Definition at line 48 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and readOn().
corresp_fin_gros
ArrOfInt Terme_Source_Rappel_T_VEF_Face::corresp_fin_gros private
correspondance elem de l'autre pb vers elem du pb courant
Definition at line 57 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and completer().
fct_ok
int Terme_Source_Rappel_T_VEF_Face::fct_ok private
Definition at line 49 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), completer(), and readOn().
force_rappel
Parser_U Terme_Source_Rappel_T_VEF_Face::force_rappel mutable private
Definition at line 50 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and readOn().
info_obj
const Type_info Terme_Source_Rappel_T_VEF_Face::info_obj static
Definition at line 31 of file Terme_Source_Rappel_T_VEF_Face.h.
l_inconnue
Ref_Champ_Inc_base Terme_Source_Rappel_T_VEF_Face::l_inconnue private
Definition at line 52 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and completer().
la_zone_Cl_VEF
Ref_Zone_Cl_VEF Terme_Source_Rappel_T_VEF_Face::la_zone_Cl_VEF protected
Definition at line 44 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and associer_zones().
la_zone_VEF
Ref_Zone_VEF Terme_Source_Rappel_T_VEF_Face::la_zone_VEF protected
Definition at line 43 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and associer_zones().
nb_fin
ArrOfInt Terme_Source_Rappel_T_VEF_Face::nb_fin private
nb d'elements de l'autre pb par element du pb courant
Definition at line 58 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by completer().
nom_autre_pb
Nom Terme_Source_Rappel_T_VEF_Face::nom_autre_pb private
Definition at line 54 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by completer(), and readOn().
nom_inco
Motcle Terme_Source_Rappel_T_VEF_Face::nom_inco private
Definition at line 55 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by completer(), and readOn().
nom_pb
Nom Terme_Source_Rappel_T_VEF_Face::nom_pb private
Definition at line 54 of file Terme_Source_Rappel_T_VEF_Face.h.
vol_fin_tot
ArrOfDouble Terme_Source_Rappel_T_VEF_Face::vol_fin_tot private
volume totale des elements fins s'appuyant un element grossier
Definition at line 59 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and completer().
zone_VEF_autre_pb
Ref_Zone_VEF Terme_Source_Rappel_T_VEF_Face::zone_VEF_autre_pb private
Definition at line 53 of file Terme_Source_Rappel_T_VEF_Face.h.
Referenced by ajouter(), and completer().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Source_Rappel_T_VEF_Face.h
src/VEF/Sources/Terme_Source_Rappel_T_VEF_Face.cpp