TRUST: IntList_Curseur Class Reference
IntList_Curseur Class Reference
List_Curseur de reels int precision.
#include <IntList.h>
Public Member Functions
IntList_Curseur (const IntList &a_list)
Constructeur
Construit une liste_curseur a partir d'une liste.
IntList_Curseur (const IntListElem &a_list)
Constructeur
Construit une liste_curseur a partir d'une liste.
operator bool () const
Teste si le curseur est non nul.
void operator++ ()
Avance le curseur dans la liste
Si le curseur est sur le dernier element, il devient nul.
int valeur () const
retourne la valeur du curseur
int & valeur ()
retourne la valeur du curseur
void operator= (const IntList &a_list)
Affectation d'une liste a une liste_curseur.
const IntListElem & list () const
Retourne la liste associee a la liste_curseur.
IntListElem & list ()
Retourne la liste associee a la liste_curseur.
Private Attributes
IntListElem * curseur
Detailed Description
List_Curseur de reels int precision.
Definition at line 84 of file IntList.h.
Constructor & Destructor Documentation
IntList_Curseur::IntList_Curseur (const IntList & a_list) [inline]
Constructeur
Construit une liste_curseur a partir d'une liste.
Definition at line 137 of file IntList.h.
References curseur, and IntListElem::est_vide().
  : curseur(&(IntListElem&)a_list)
{
  if (a_list.est_vide())
    curseur=0;
}
IntList_Curseur::IntList_Curseur (const IntListElem & a_list) [inline]
Constructeur
Construit une liste_curseur a partir d'une liste.
Definition at line 159 of file IntList.h.
References curseur, and IntListElem::est_vide().
  : curseur(&(IntListElem&)a_list)
{
  if (a_list.est_vide())
    curseur=0;
}
Member Function Documentation
const IntListElem & IntList_Curseur::list () const [inline]
Retourne la liste associee a la liste_curseur.
Returns:
const IntList&
Signification: la liste associee
Contraintes:
Definition at line 288 of file IntList.h.
References curseur.
Referenced by IntList::printOn(), and IntList::suppr().
{
  return *curseur;
}
IntListElem & IntList_Curseur::list () [inline]
Retourne la liste associee a la liste_curseur.
Returns:
IntList&
Signification: la liste associee
Contraintes: IntList_H
Definition at line 308 of file IntList.h.
References curseur.
IntList_Curseur::operator bool () const [inline]
Teste si le curseur est non nul.
Returns:
int
Signification: 1 si le curseur est non nul, 0 si il est nul
Contraintes:
Definition at line 181 of file IntList.h.
References curseur.
{
  return (curseur!=0);
}
void IntList_Curseur::operator++ () [inline]
Avance le curseur dans la liste
Si le curseur est sur le dernier element, il devient nul.
Definition at line 202 of file IntList.h.
References curseur, IntListElem::est_dernier(), and IntListElem::suivant().
{
  if(curseur->est_dernier())
    curseur=0;
  else
    curseur=&(curseur->suivant());
}
void IntList_Curseur::operator= (const IntList & a_list) [inline]
Affectation d'une liste a une liste_curseur.
Definition at line 266 of file IntList.h.
References curseur, and IntListElem::est_vide().
{
  curseur=(&(IntListElem&)a_list);
  if (a_list.est_vide())
    curseur=0;
}
int IntList_Curseur::valeur () const [inline]
retourne la valeur du curseur
Returns:
int
Signification: valeur du curseur
Contraintes:
Definition at line 225 of file IntList.h.
References curseur, and IntListElem::valeur().
Referenced by IntList::calcule_min_max(), Faces::compare(), IntList::contient(), VerifierCoin::interpreter_(), IntList::operator=(), IntList::operator[](), IntList::printOn(), IntList::rang(), Matrice_Morse::remplir(), Matrice_Bloc::remplir(), and IntList::suppr().
{
  return curseur->valeur();
}
int & IntList_Curseur::valeur () [inline]
retourne la valeur du curseur
Returns:
int&
Signification: valeur du curseur
Contraintes:
Definition at line 245 of file IntList.h.
References curseur, and IntListElem::valeur().
{
  return curseur->valeur();
}
Member Data Documentation
IntListElem* IntList_Curseur::curseur [private]
Definition at line 98 of file IntList.h.
Referenced by IntList_Curseur(), list(), operator bool(), operator++(), operator=(), and valeur().
The documentation for this class was generated from the following file:
src/Kernel/Math/IntList.h