TRUST: TRUSTChamp_Morceaux_generique< _TYPE_ > Class Template Reference
TRUSTChamp_Morceaux_generique< _TYPE_ > Class Template Reference
#include <TRUSTChamp_Morceaux_generique.h>
Public Member Functions
Champ_base & affecter_ (const Champ_base &ch) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Renvoie la valeur du champ au point specifie par ses coordonnees.
Parametre: DoubleVect& positions
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& valeurs
Signification: la valeur du champ au point specifie.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& val
Signification: la valeur du champ au point specifie
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul.
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parametre: DoubleTab& positions
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleTab& valeurs
Signification: le tableau des valeurs du champ aux points specifies.
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees.
Parametre: DoubleTab& positions
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleVect& valeurs
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parametre: DoubleTab&
Signification: le tableau des coordonnees des points de calcul
Parametre: IntVect& les_polys
Signification: le tableau des elements dans lesquels sont situes les points de calcul
Parametre: DoubleTab& val
Signification: le tableau des valeurs du champ aux points specifies.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parametre: DoubleTab&
Signification: le tableau des coordonnees des points de calcul
Parametre: IntVect& les_polys
Signification: le tableau des elements dans lesquels sont situes les points de calcul
Parametre: DoubleVect& val
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
int initialiser (const double temps) override
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
const Ref_Domaine & domaine () const
Ref_Domaine & domaine ()
const List_Ref_Sous_Zone & sous_zones () const
List_Ref_Sous_Zone & sous_zones ()
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Protected Member Functions
void interprete_get_domaine (const Nom &nom)
void creer_tabs (const int)
Entree & complete_readOn (const int dim, const Nom &qsj, Entree &is, Nom &nom)
Protected Member Functions inherited from Champ_Don_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Protected Member Functions inherited from Field_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Ref_Sous_Zone les_sous_zones
Ref_Domaine mon_domaine
Ref_Probleme_base ref_pb
Vect_Parser_U parser
Nom nom_champ_parametre_
IntTab parser_idx
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Additional Inherited Members
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Detailed Description
template<Champ_Morceaux_Type _TYPE_>
class TRUSTChamp_Morceaux_generique< _TYPE_ >
Definition at line 31 of file TRUSTChamp_Morceaux_generique.h.
Member Function Documentation
affecter_()
template<Champ_Morceaux_Type _TYPE_> Champ_base & TRUSTChamp_Morceaux_generique< _TYPE_ >::affecter_ (const Champ_base &) override virtual
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Reimplemented from Champ_Don_base.
Definition at line 20 of file TRUSTChamp_Morceaux_generique.tpp.
{
  static constexpr bool IS_FONC = (_TYPE_ == Champ_Morceaux_Type::FONC);
  if (!IS_FONC) not_implemented_champ_<void>(__func__);
  if (sub_type(Champ_Uniforme, ch)) valeurs() = ch.valeurs()(0, 0);
  else valeurs() = ch.valeurs();
  return *this;
}
References FONC, sub_type, and Champ_Proto::valeurs().
complete_readOn()
template<Champ_Morceaux_Type _TYPE_> Entree & TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn (const int dim, const Nom & qsj, Entree & is, Nom & nom) protected
Definition at line 249 of file TRUSTChamp_Morceaux_generique.tpp.
{
  Motcle motlu;
  int k, poly;
  if (nom != "{")
    {
      Cerr << "Error while reading a " << qsj << " . We expected a { instead of " << nom << finl;
      Process::exit();
    }
  is >> motlu;
  if (motlu != Motcle("defaut"))
    {
      Cerr << "Error while reading a " << qsj << " . We expected defaut instead of " << nom << finl;
      Process::exit();
    }
  /* parsers par defaut */
  for (k = 0; k < dim; k++)
    {
      Parser_U psr;
      Nom tmp;
      is >> tmp;
      psr.setNbVar(5);
      psr.setString(tmp);
      psr.addVar("t"), psr.addVar("x"), psr.addVar("y"), psr.addVar("z");
      if (ref_pb.non_nul()) psr.addVar("val");
      psr.parseString();
      for (poly = 0; poly < mon_domaine->zone(0).nb_elem_tot(); poly++)
        parser_idx(poly, k) = parser.size();
      parser.add(psr);
    }
  is >> nom;
  while (nom != Nom("}"))
    {
      REF (Sous_Zone) refssz = les_sous_zones.add(mon_domaine->ss_zone(nom));
      Sous_Zone& ssz = refssz.valeur();
      for (k = 0; k < dim; k++)
        {
          Parser_U psr;
          Nom tmp;
          is >> tmp;
          psr.setNbVar(5);
          psr.setString(tmp);
          psr.addVar("t"), psr.addVar("x"), psr.addVar("y"), psr.addVar("z");
          if (ref_pb.non_nul()) psr.addVar("val");
          psr.parseString();
          for (poly = 0; poly < ssz.nb_elem_tot(); poly++)
            parser_idx(ssz(poly), k) = parser.size();
          parser.add(psr);
        }
      is >> nom;
    }
  return is;
}
References Parser_U::addVar(), Cerr, Process::exit(), finl, Sous_Zone::nb_elem_tot(), Parser_U::parseString(), REF, Parser_U::setNbVar(), and Parser_U::setString().
creer_tabs()
template<Champ_Morceaux_Type _TYPE_> void TRUSTChamp_Morceaux_generique< _TYPE_ >::creer_tabs (const int dim) protected
Definition at line 239 of file TRUSTChamp_Morceaux_generique.tpp.
{
  fixer_nb_comp(dim);
  parser_idx.resize(0, dim);
  mon_domaine->creer_tableau_elements(parser_idx);
  valeurs_.resize(0, dim);
  mon_domaine->creer_tableau_elements(valeurs_);
}
domaine() [1/2]
template<Champ_Morceaux_Type _TYPE_> Ref_Domaine & TRUSTChamp_Morceaux_generique< _TYPE_ >::domaine () inline
Definition at line 56 of file TRUSTChamp_Morceaux_generique.h.
{ return mon_domaine; }
References TRUSTChamp_Morceaux_generique< _TYPE_ >::mon_domaine.
domaine() [2/2]
template<Champ_Morceaux_Type _TYPE_> const Ref_Domaine & TRUSTChamp_Morceaux_generique< _TYPE_ >::domaine () const inline
Definition at line 55 of file TRUSTChamp_Morceaux_generique.h.
{ return mon_domaine; }
References TRUSTChamp_Morceaux_generique< _TYPE_ >::mon_domaine.
Referenced by Champ_Uniforme_Morceaux::affecter_().
initialiser()
template<Champ_Morceaux_Type _TYPE_> int TRUSTChamp_Morceaux_generique< _TYPE_ >::initialiser (const double temps) override virtual
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
Reimplemented from Champ_Don_base.
Definition at line 221 of file TRUSTChamp_Morceaux_generique.tpp.
{
  return Champ_Don_base::initialiser(time);
}
References Champ_Don_base::initialiser().
interprete_get_domaine()
template<Champ_Morceaux_Type _TYPE_> void TRUSTChamp_Morceaux_generique< _TYPE_ >::interprete_get_domaine (const Nom & nom) protected
Definition at line 227 of file TRUSTChamp_Morceaux_generique.tpp.
{
  static constexpr bool IS_FONC_TXYZ = (_TYPE_ == Champ_Morceaux_Type::FONC_TXYZ);
  if (IS_FONC_TXYZ)
    {
      ref_pb = ref_cast(Probleme_base, Interprete::objet(nom));
      mon_domaine = ref_pb->domaine();
    }
  else mon_domaine = ref_cast(Domaine, Interprete::objet(nom));
}
References FONC_TXYZ, Interprete::objet(), and ref_cast.
mettre_a_jour()
template<Champ_Morceaux_Type _TYPE_> void TRUSTChamp_Morceaux_generique< _TYPE_ >::mettre_a_jour (double temps) override virtual
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
Reimplemented from Champ_Don_base.
Definition at line 177 of file TRUSTChamp_Morceaux_generique.tpp.
{
  static constexpr bool IS_UNIFORME = (_TYPE_ == Champ_Morceaux_Type::UNIFORME);
  if (IS_UNIFORME)
    {
      Champ_Don_base::mettre_a_jour(time);
      return;
    }
  const IntTab& les_elems = mon_domaine->zone(0).les_elems();
  const int nb_som_elem = mon_domaine->zone(0).nb_som_elem();
  const Champ_base *ch = ref_pb.non_nul() ? &ref_pb->get_champ(nom_champ_parametre_) : nullptr;
  DoubleTab& tab = valeurs();
  for (int i = 0; i < mon_domaine->zone(0).nb_elem_tot(); i++)
    {
      /* xs : coordonnees du poly par barycentre des sommets -> pas top */
      double xs[3] = { 0, };
      int nb_som = 0, s, r;
      for (int j = 0; j < nb_som_elem && (s = les_elems(i, j)) >= 0; j++)
        for (r = 0, nb_som++; r < dimension; r++) xs[r] += mon_domaine->coord(s, r);
      for (r = 0; r < dimension; r++) xs[r] /= nb_som;
      /* calcul de chaque composante */
      double val = ch ? ch->valeurs()(i, 0) : 0;
      for (int k = 0; k < tab.dimension(1); k++)
        {
          Parser_U& psr = parser(parser_idx(i, k));
          psr.setVar("x", xs[0]);
          psr.setVar("y", xs[1]);
          psr.setVar("z", xs[2]);
          psr.setVar("t", time);
          if (ref_pb.non_nul()) psr.setVar("val", val);
          tab(i, k) = psr.eval();
        }
    }
}
References TRUSTTab< _TYPE_ >::dimension(), Parser_U::eval(), Champ_Don_base::mettre_a_jour(), Parser_U::setVar(), UNIFORME, and Champ_Proto::valeurs().
sous_zones() [1/2]
template<Champ_Morceaux_Type _TYPE_> List_Ref_Sous_Zone & TRUSTChamp_Morceaux_generique< _TYPE_ >::sous_zones () inline
Definition at line 58 of file TRUSTChamp_Morceaux_generique.h.
{ return les_sous_zones; }
References TRUSTChamp_Morceaux_generique< _TYPE_ >::les_sous_zones.
sous_zones() [2/2]
template<Champ_Morceaux_Type _TYPE_> const List_Ref_Sous_Zone & TRUSTChamp_Morceaux_generique< _TYPE_ >::sous_zones () const inline
Definition at line 57 of file TRUSTChamp_Morceaux_generique.h.
{ return les_sous_zones; }
References TRUSTChamp_Morceaux_generique< _TYPE_ >::les_sous_zones.
Referenced by Champ_Uniforme_Morceaux::affecter_().
valeur_a()
template<Champ_Morceaux_Type _TYPE_> DoubleVect & TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_a (const DoubleVect & position, DoubleVect & valeurs) const override virtual
Renvoie la valeur du champ au point specifie par ses coordonnees.
Parametre: DoubleVect& positions
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& valeurs
Signification: la valeur du champ au point specifie.
Reimplemented from Champ_base.
Definition at line 39 of file TRUSTChamp_Morceaux_generique.tpp.
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect le_poly(1);
  la_zone.chercher_elements(positions, le_poly);
  return valeur_a_elem(positions, tab_valeurs, le_poly[0]);
}
valeur_a_elem()
template<Champ_Morceaux_Type _TYPE_> DoubleVect & TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_a_elem (const DoubleVect & position, DoubleVect & valeurs, int le_poly) const override virtual
Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: DoubleVect& val
Signification: la valeur du champ au point specifie
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul.
Reimplemented from Champ_base.
Definition at line 57 of file TRUSTChamp_Morceaux_generique.tpp.
{
  if (val.size() != nb_compo_) erreur_champ_(__func__);
  const DoubleTab& ch = valeurs();
  for (int k = 0; k < nb_compo_; k++) val(k) = ch(le_poly, k);
  return val;
}
References erreur_champ_(), and TRUSTVect< _TYPE_ >::size().
valeur_a_elem_compo()
template<Champ_Morceaux_Type _TYPE_> double TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
Renvoie la valeur d'une composante du champ au point specifie
par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int le_poly
Signification: l'element dans lequel est situe le point de calcul
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
Reimplemented from Champ_base.
Definition at line 77 of file TRUSTChamp_Morceaux_generique.tpp.
{
  if (ncomp > nb_compo_) erreur_champ_(__func__);
  const DoubleTab& ch = valeurs();
  double val = (nb_compo_ == 1) ? ch(le_poly, 0) : ch(le_poly, ncomp);
  return val;
}
References erreur_champ_().
valeur_aux()
template<Champ_Morceaux_Type _TYPE_> DoubleTab & TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux (const DoubleTab & positions, DoubleTab & valeurs) const override virtual
Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parametre: DoubleTab& positions
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleTab& valeurs
Signification: le tableau des valeurs du champ aux points specifies.
Reimplemented from Champ_base.
Definition at line 94 of file TRUSTChamp_Morceaux_generique.tpp.
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(positions, les_polys);
  return valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References Zone::chercher_elements(), and Zone::nb_elem().
valeur_aux_compo()
template<Champ_Morceaux_Type _TYPE_> DoubleVect & TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_compo (const DoubleTab & positions, DoubleVect & valeurs, int ncomp) const override virtual
Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees.
Parametre: DoubleTab& positions
Signification: le tableau des coordonnees des points de calcul
Parametre: DoubleVect& valeurs
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
Reimplemented from Champ_base.
Definition at line 111 of file TRUSTChamp_Morceaux_generique.tpp.
{
  const Zone& la_zone = mon_domaine->zone(0);
  IntVect les_polys(la_zone.nb_elem());
  la_zone.chercher_elements(positions, les_polys);
  return valeur_aux_elems_compo(positions, les_polys, tab_valeurs, ncomp);
}
References Zone::chercher_elements(), and Zone::nb_elem().
valeur_aux_elems()
template<Champ_Morceaux_Type _TYPE_> DoubleTab & TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parametre: DoubleTab&
Signification: le tableau des coordonnees des points de calcul
Parametre: IntVect& les_polys
Signification: le tableau des elements dans lesquels sont situes les points de calcul
Parametre: DoubleTab& val
Signification: le tableau des valeurs du champ aux points specifies.
< (val.nb_dim() > 2)
Reimplemented from Champ_base.
Definition at line 129 of file TRUSTChamp_Morceaux_generique.tpp.
{
  if (val.nb_dim() == 2)
    {
      assert((val.dimension(0) == les_polys.size()) || (val.dimension_tot(0) == les_polys.size()));
      assert(val.dimension(1) == nb_compo_);
    }
  else erreur_champ_(__func__); //!< (val.nb_dim() > 2)
  const DoubleTab& ch = valeurs();
  val = 0.;
  int p;
  for (int rang_poly = 0; rang_poly < les_polys.size(); rang_poly++)
    if ((p = les_polys(rang_poly)) != -1)
      for (int n = 0; n < nb_compo_; n++) val(rang_poly, n) = ch(p, n);
  return val;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), erreur_champ_(), TRUSTTab< _TYPE_ >::nb_dim(), and TRUSTVect< _TYPE_ >::size().
valeur_aux_elems_compo()
template<Champ_Morceaux_Type _TYPE_> DoubleVect & TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parametre: DoubleTab&
Signification: le tableau des coordonnees des points de calcul
Parametre: IntVect& les_polys
Signification: le tableau des elements dans lesquels sont situes les points de calcul
Parametre: DoubleVect& val
Signification: le tableau des valeurs de la composante du champ aux points specifies
Parametre: int ncomp
Signification: l'index de la composante du champ a calculer.
Reimplemented from Champ_base.
Definition at line 161 of file TRUSTChamp_Morceaux_generique.tpp.
{
  assert(val.size() == les_polys.size());
  int le_poly;
  const DoubleTab& ch = valeurs();
  for (int rang_poly = 0; rang_poly < les_polys.size(); rang_poly++)
    {
      le_poly = les_polys(rang_poly);
      val(rang_poly) = (le_poly == -1) ? 0 : ch(le_poly, ncomp);
    }
  return val;
}
References TRUSTVect< _TYPE_ >::size().
Member Data Documentation
les_sous_zones
template<Champ_Morceaux_Type _TYPE_> List_Ref_Sous_Zone TRUSTChamp_Morceaux_generique< _TYPE_ >::les_sous_zones protected
Definition at line 61 of file TRUSTChamp_Morceaux_generique.h.
Referenced by TRUSTChamp_Morceaux_generique< _TYPE_ >::sous_zones().
mon_domaine
template<Champ_Morceaux_Type _TYPE_> Ref_Domaine TRUSTChamp_Morceaux_generique< _TYPE_ >::mon_domaine protected
Definition at line 62 of file TRUSTChamp_Morceaux_generique.h.
Referenced by TRUSTChamp_Morceaux_generique< _TYPE_ >::domaine().
nom_champ_parametre_
template<Champ_Morceaux_Type _TYPE_> Nom TRUSTChamp_Morceaux_generique< _TYPE_ >::nom_champ_parametre_ protected
Definition at line 65 of file TRUSTChamp_Morceaux_generique.h.
parser
template<Champ_Morceaux_Type _TYPE_> Vect_Parser_U TRUSTChamp_Morceaux_generique< _TYPE_ >::parser protected
Definition at line 64 of file TRUSTChamp_Morceaux_generique.h.
parser_idx
template<Champ_Morceaux_Type _TYPE_> IntTab TRUSTChamp_Morceaux_generique< _TYPE_ >::parser_idx protected
Definition at line 66 of file TRUSTChamp_Morceaux_generique.h.
ref_pb
template<Champ_Morceaux_Type _TYPE_> Ref_Probleme_base TRUSTChamp_Morceaux_generique< _TYPE_ >::ref_pb protected
Definition at line 63 of file TRUSTChamp_Morceaux_generique.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/TRUSTChamp_Morceaux_generique.h
src/Kernel/Framework/TRUSTChamp_Morceaux_generique.tpp