TRUST: Evaluateur_Source_PolyMAC_Elem Class Reference
Evaluateur_Source_PolyMAC_Elem Class Reference
#include <Evaluateur_Source_PolyMAC_Elem.h>
Public Member Functions
Evaluateur_Source_PolyMAC_Elem ()
Evaluateur_Source_PolyMAC_Elem (const Evaluateur_Source_PolyMAC_Elem &)
void completer () override
Public Member Functions inherited from Evaluateur_Source_PolyMAC
Evaluateur_Source_PolyMAC ()
virtual ~Evaluateur_Source_PolyMAC ()
Evaluateur_Source_PolyMAC (const Evaluateur_Source_PolyMAC &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual double calculer_terme_source (int) const =0
virtual void calculer_terme_source (int, DoubleVect &) const =0
Protected Attributes
DoubleVect volumes
DoubleVect porosite_vol
porosites volumiques
Protected Attributes inherited from Evaluateur_Source_PolyMAC
Ref_Zone_PolyMAC la_zone
Ref_Zone_Cl_PolyMAC la_zcl
Detailed Description
Definition at line 22 of file Evaluateur_Source_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Evaluateur_Source_PolyMAC_Elem() [1/2]
Evaluateur_Source_PolyMAC_Elem::Evaluateur_Source_PolyMAC_Elem () inline
Definition at line 25 of file Evaluateur_Source_PolyMAC_Elem.h.
{ }
Evaluateur_Source_PolyMAC_Elem() [2/2]
Evaluateur_Source_PolyMAC_Elem::Evaluateur_Source_PolyMAC_Elem (const Evaluateur_Source_PolyMAC_Elem & eval)
Definition at line 19 of file Evaluateur_Source_PolyMAC_Elem.cpp.
  : Evaluateur_Source_PolyMAC(eval)
{
  volumes.ref(eval.volumes);
  porosite_vol.ref(eval.porosite_vol);
}
References porosite_vol, TRUSTVect< _TYPE_ >::ref(), and volumes.
Member Function Documentation
completer()
void Evaluateur_Source_PolyMAC_Elem::completer (void) override virtual
Implements Evaluateur_Source_PolyMAC.
Definition at line 26 of file Evaluateur_Source_PolyMAC_Elem.cpp.
{
  Cerr << "Evaluateur_Source_PolyMAC_Elem::completer()" << finl;
  volumes.ref(la_zone->volumes());
  porosite_vol.ref(la_zone->porosite_elem());
}
References Cerr, finl, Evaluateur_Source_PolyMAC::la_zone, Zone_VF::porosite_elem(), porosite_vol, TRUSTVect< _TYPE_ >::ref(), Zone_VF::volumes(), and volumes.
Member Data Documentation
porosite_vol
DoubleVect Evaluateur_Source_PolyMAC_Elem::porosite_vol protected
porosites volumiques
Definition at line 30 of file Evaluateur_Source_PolyMAC_Elem.h.
Referenced by Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), completer(), and Evaluateur_Source_PolyMAC_Elem().
volumes
DoubleVect Evaluateur_Source_PolyMAC_Elem::volumes protected
Definition at line 30 of file Evaluateur_Source_PolyMAC_Elem.h.
Referenced by Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), completer(), and Evaluateur_Source_PolyMAC_Elem().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Evaluateur_Source_PolyMAC_Elem.h
src/PolyMAC/Sources/Evaluateur_Source_PolyMAC_Elem.cpp