TRUST: Terme_Puissance_Thermique_Echange_Impose_VEF_Face Class Reference
Terme_Puissance_Thermique_Echange_Impose_VEF_Face Class Reference
class Terme_Puissance_Thermique_Echange_Impose_VEF_Face
#include <Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h>
Public Member Functions
~Terme_Puissance_Thermique_Echange_Impose_VEF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void associer_pb (const Probleme_base &)
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Puissance_Thermique_Echange_Impose_VEF_Face & self_cast (Objet_U &)
static const
Terme_Puissance_Thermique_Echange_Impose_VEF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Champ_Don himp_
Champ_Don Text_
Detailed Description
class Terme_Puissance_Thermique_Echange_Impose_VEF_Face
See also:
Source_base
Definition at line 44 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
Constructor & Destructor Documentation
Terme_Puissance_Thermique_Echange_Impose_VEF_Face::~Terme_Puissance_Thermique_Echange_Impose_VEF_Face ()
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
Member Function Documentation
DoubleTab & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 119 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References ArrOfDouble::addr(), DoubleTab::dimension(), MorEqn::equation(), Zone_VF::face_voisins(), himp_, Equation_base::inconnue(), la_zone_VEF, Zone_VF::nb_faces(), Text_, Deriv_Champ_Don_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), Champ_Don_base::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
Referenced by calculer().
{
  int nb_faces=la_zone_VEF.valeur().nb_faces();
  const Zone_VF&     zone               = la_zone_VEF.valeur();
  const IntTab&      face_voisins       = zone.face_voisins();
  const DoubleVect& volumes_entrelaces = zone.volumes_entrelaces();
  const DoubleTab& himp = himp_.valeur().valeurs();
  const DoubleTab& Text = Text_.valeur().valeurs();
  const DoubleTab& T = equation().inconnue().valeurs();
  const DoubleVect& volumes_elements = zone.volumes();
  for (int num_face=0; num_face<nb_faces; num_face++)
    {
      const double vol = volumes_entrelaces(num_face);
      const int elem0 = face_voisins(num_face,0);
      const int elem1 = face_voisins(num_face,1);
      double h0 = 0, h1 = 0, text0=0, text1=0,vol0 = 0, vol1 = 0;
      if (elem0 >= 0)
        {
          h0 = himp.addr()[elem0 * (himp.dimension(0) > 1)];
          text0 = Text.addr()[elem0 * (Text.dimension(0) > 1)];
          vol0 = volumes_elements(elem0);
        }
      if (elem1 >= 0)
        {
          h1 = himp.addr()[elem1 * (himp.dimension(0) > 1)];
          text1 = Text.addr()[elem1 * (Text.dimension(0) > 1)];
          vol1 = volumes_elements(elem1);
        }
      double hm = (h0 * vol0 + h1 * vol1) / (vol0 + vol1);
      double htextm = (h0 * text0 * vol0 + h1 * text1 * vol1) / (vol0 + vol1);
      resu(num_face) -= (hm*T(num_face)-htextm) * vol;
    }
  return resu;
}
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::associer_pb (const Probleme_base &) [inline, virtual]
Implements Source_base.
Definition at line 56 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
{ };
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 110 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References Cerr, finl, la_zone_Cl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Cerr << " Terme_Puissance_Thermique_Echange_Impose_VEF_Face::associer_zones " << finl ;
  la_zone_VEF = ref_cast(Zone_VEF, zone_dis.valeur());
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
}
DoubleTab & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::calculer (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 161 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References ajouter().
{
  resu=0;
  ajouter(resu);
  return resu;
}
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const [virtual]
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 167 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References ArrOfDouble::addr(), DoubleTab::dimension(), Zone_VF::face_voisins(), himp_, la_zone_VEF, Zone_VF::nb_faces(), Deriv_Champ_Don_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Don_base::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  int nb_faces=la_zone_VEF.valeur().nb_faces();
  const Zone_VF&     zone               = la_zone_VEF.valeur();
  const IntTab&      face_voisins       = zone.face_voisins();
  const DoubleVect& volumes_entrelaces = zone.volumes_entrelaces();
  const DoubleTab& himp = himp_.valeur().valeurs();
// const DoubleTab& Text = Text_.valeur().valeurs();
// const DoubleTab& T = equation().inconnue().valeurs();
  const DoubleVect& volumes_elements = zone.volumes();
  for (int num_face=0; num_face<nb_faces; num_face++)
    {
      const double vol = volumes_entrelaces(num_face);
      const int elem0 = face_voisins(num_face,0);
      const int elem1 = face_voisins(num_face,1);
      double h0 = 0, h1 = 0,vol0 = 0, vol1 = 0;
      if (elem0 >= 0)
        {
          h0 = himp.addr()[elem0 * (himp.dimension(0) > 1)];
// text0 = text(elem0);
          vol0 = volumes_elements(elem0);
        }
      if (elem1 >= 0)
        {
          h1 = himp.addr()[elem1 * (himp.dimension(0) > 1)];
// text1 = text(elem0);
          vol1 = volumes_elements(elem1);
        }
      double hm = (h0 * vol0 + h1 * vol1) / (vol0 + vol1);
// double textm = (text0 * vol0 + text1 * vol1) / (vol0 + vol1);
      matrice(num_face,num_face) += hm* vol;
    }
}
Objet_U * Terme_Puissance_Thermique_Echange_Impose_VEF_Face::cree_instance () [static]
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
int Terme_Puissance_Thermique_Echange_Impose_VEF_Face::duplique () const [virtual]
Implements Source_base.
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
const Type_info * Terme_Puissance_Thermique_Echange_Impose_VEF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
const Type_info * Terme_Puissance_Thermique_Echange_Impose_VEF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
void Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 57 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References ArrOfDouble::addr(), Source_base::bilan(), DoubleTab::dimension(), MorEqn::equation(), Zone_VF::face_voisins(), Zone_VF::faces_doubles(), himp_, Equation_base::inconnue(), la_zone_VEF, Champ_Don::mettre_a_jour(), Zone_VF::nb_faces(), ref_cast, Text_, Deriv_Champ_Don_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Inc::valeurs(), Champ_Don_base::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  int nb_faces = la_zone_VEF.valeur().nb_faces();
  const Zone_VEF& zone = ref_cast(Zone_VEF, la_zone_VEF.valeur());
  const IntTab& face_voisins = zone.face_voisins();
  const DoubleVect& volumes_entrelaces = zone.volumes_entrelaces();
  const DoubleTab& himp = himp_.valeur().valeurs();
  const DoubleTab& Text = Text_.valeur().valeurs();
  const DoubleTab& T = equation().inconnue().valeurs();
  const DoubleVect& volumes_elements = zone.volumes();
  bilan()(0) = 0;
  for (int num_face = 0; num_face < nb_faces; num_face++)
    {
      const double vol = volumes_entrelaces(num_face);
      const int elem0 = face_voisins(num_face,0);
      const int elem1 = face_voisins(num_face,1);
      double h0 = 0, h1 = 0, text0 = 0, text1 = 0, vol0 = 0, vol1 = 0;
      if (elem0 >= 0)
        {
          h0 = himp.addr()[elem0 * (himp.dimension(0) > 1)];
          text0 = Text.addr()[elem0 * (Text.dimension(0) > 1)];
          vol0 = volumes_elements(elem0);
        }
      if (elem1 >= 0)
        {
          h1 = himp.addr()[elem1 * (himp.dimension(0) > 1)];
          text1 = Text.addr()[elem1 * (Text.dimension(0) > 1)];
          vol1 = volumes_elements(elem1);
        }
      double hm = (h0 * vol0 + h1 * vol1) / (vol0 + vol1);
      double htextm = (h0 * text0 * vol0 + h1 * text1 * vol1) / (vol0 + vol1);
      double c = (zone.faces_doubles()(num_face)==1) ? 0.5 : 1 ;
      bilan()(0) -= c * (hm*T(num_face)-htextm) * vol;
    }
  himp_.mettre_a_jour(temps);
  Text_.mettre_a_jour(temps);
}
Sortie & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 37 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je();
}
Entree & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 46 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
References Param::ajouter(), himp_, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), Param::REQUIRED, Source_base::set_description(), Source_base::set_fichier(), and Text_.
{
  Param param(que_suis_je());
  param.ajouter("himp",&himp_,Param::REQUIRED);
  param.ajouter("Text",&Text_,Param::REQUIRED);
  param.lire_avec_accolades_depuis(s);
  set_fichier("Terme_Puissance_Thermique_Echange_Impose");
  set_description("Power (W)");
  return s ;
}
Terme_Puissance_Thermique_Echange_Impose_VEF_Face & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
const Terme_Puissance_Thermique_Echange_Impose_VEF_Face & Terme_Puissance_Thermique_Echange_Impose_VEF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
unsigned Terme_Puissance_Thermique_Echange_Impose_VEF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 30 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp.
Member Data Documentation
Champ_Don Terme_Puissance_Thermique_Echange_Impose_VEF_Face::himp_ [protected]
Definition at line 63 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
Referenced by ajouter(), contribuer_a_avec(), mettre_a_jour(), and readOn().
const Type_info Terme_Puissance_Thermique_Echange_Impose_VEF_Face::info_obj [static]
Reimplemented from Source_base.
Definition at line 49 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
Ref_Zone_Cl_VEF Terme_Puissance_Thermique_Echange_Impose_VEF_Face::la_zone_Cl_VEF [protected]
Definition at line 62 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
Referenced by associer_zones().
Ref_Zone_VEF Terme_Puissance_Thermique_Echange_Impose_VEF_Face::la_zone_VEF [protected]
Definition at line 61 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
Referenced by ajouter(), associer_zones(), contribuer_a_avec(), and mettre_a_jour().
Champ_Don Terme_Puissance_Thermique_Echange_Impose_VEF_Face::Text_ [protected]
Definition at line 63 of file Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h.
Referenced by ajouter(), mettre_a_jour(), and readOn().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Puissance_Thermique_Echange_Impose_VEF_Face.h
src/VEF/Sources/Terme_Puissance_Thermique_Echange_Impose_VEF_Face.cpp