TRUST: Champ_Generique_Interpolation Class Reference
Champ_Generique_Interpolation Class Reference
Un champ generique qui est construit comme une interpolation
d'un autre champ generique (interpolation aux sommets ou aux elements).
L interpolation sera effectuee sur un domaine qui peut etre
le domaine de calcul ou un domaine different specifie par l utilisateur.
#include <Champ_Generique_Interpolation.h>
Public Member Functions
Champ_Generique_Interpolation ()
voir reset()
~Champ_Generique_Interpolation ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void reset () override
restore la configuration initiale de l'objet
localisation non specifiee, source non specifiee, methode=calculer_champ_post, domaine natif
void set_param (Param &param) override
virtual int set_localisation (const Motcle &localisation, int exit_on_error=1)
Initialisation de la classe: initialisation de la localisation
demandee. Parametres valides : elem, som.
virtual int set_methode (const Motcle &methode, int exit_on_error=1)
Initialisation de la classe: initialisation de la methode d'interpolation
Parametres valides : calculer_champ_post<br>(Idees pour la suite: affecter, affecter avec integrale...)
virtual int set_domaine (const Nom &nom_domaine, int exit_on_error=1)
Initialisation de la classe: initialisation du domaine d'interpolation
Parametres valides : "" => domaine natif, ou le nom d'un objet Domaine connu de l'interprete.
const Champ_base & get_champ (Champ &espace_stockage) const override
Interpolation du champ source en fonction de la methode, localisation et
domaine demandes.
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
virtual const Champ_base & get_champ_with_calculer_champ_post (Champ &espace_stockage) const
Interpolation du champ source a l'aide de Champ_base::calculer_champ_xxx_post.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
void nommer_source () override
void completer (const Postraitement_base &post) override
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Motcle get_directive_pour_discr () const override
void discretiser_domaine ()
const Noms & fixer_noms_compo (const Noms &noms)
const Noms & fixer_noms_synonyms (const Noms &noms)
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Generique_Interpolation & self_cast (Objet_U &)
static const Champ_Generique_Interpolation & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Noms compo_
Noms syno_
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
appel invalide
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Motcle localisation_
localisation d interpolation elem, som
Motcle methode_
calculer_champ_post, etc...
Nom nom_domaine_lu_
Nom du domaine lu.
Ref_Domaine domaine_
domaine sur lequel on veut interpoler le champ (domaine natif si reference nulle)
Domaine_dis le_dom_dis
rempli si domaine d interpolation different du domaine natif ex : Sonde utilise valeur_aux...() qui necessite de disposer d une zone discretisee
int optimisation_sous_maillage_
int optimisation_demande_
ArrOfInt renumerotation_maillage_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Detailed Description
Un champ generique qui est construit comme une interpolation
d'un autre champ generique (interpolation aux sommets ou aux elements).
L interpolation sera effectuee sur un domaine qui peut etre
le domaine de calcul ou un domaine different specifie par l utilisateur.
Definition at line 39 of file Champ_Generique_Interpolation.h.
Constructor & Destructor Documentation
Champ_Generique_Interpolation()
Champ_Generique_Interpolation::Champ_Generique_Interpolation ()
voir reset()
Definition at line 27 of file Champ_Generique_Interpolation.cpp.
{
// valeurs par defaut
  reset();
}
References reset().
~Champ_Generique_Interpolation()
Champ_Generique_Interpolation::~Champ_Generique_Interpolation ()
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
Member Function Documentation
completer()
void Champ_Generique_Interpolation::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 593 of file Champ_Generique_Interpolation.cpp.
{
  Champ_Gen_de_Champs_Gen::completer(post);
// Verifications:
  if (get_nb_sources() != 1)
    {
      Cerr << "Error in Champ_Generique_Interpolation::readOn\n"
           << " You must specify exactly 1 \"Source\"." << finl;
      exit();
    }
// Si le domaine lu n'est pas le domaine de calcul, on fixe le domaine
  const Domaine& domaine_calcul = get_source(0).get_ref_domain();
  if (optimisation_demande_!=1)
    optimisation_sous_maillage_=0;
  if ( (nom_domaine_lu_!="") && (nom_domaine_lu_!=domaine_calcul.le_nom()) )
    {
      set_domaine(nom_domaine_lu_);
    }
  else
    {
// optimisation sous maillage inutile
      if (optimisation_demande_==-1)
        optimisation_sous_maillage_=0;
    }
  discretiser_domaine();
}
References Cerr, Champ_Gen_de_Champs_Gen::completer(), discretiser_domaine(), Process::exit(), finl, Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Generique_base::get_ref_domain(), Champ_Gen_de_Champs_Gen::get_source(), Domaine::le_nom(), nom_domaine_lu_, optimisation_demande_, optimisation_sous_maillage_, and set_domaine().
cree_instance()
Objet_U * Champ_Generique_Interpolation::cree_instance () static
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
discretiser_domaine()
void Champ_Generique_Interpolation::discretiser_domaine ()
Definition at line 671 of file Champ_Generique_Interpolation.cpp.
{
  if (domaine_.non_nul())
    {
      le_dom_dis.associer_domaine(domaine_.valeur());
      const Probleme_base& Pb = get_ref_pb_base();
      const Discretisation_base& discr = Pb.discretisation();
      const Nom& type_discr = discr.que_suis_je();
// on ne cree pas les faces sauf si on veut une interpolation aux faces ou si on a des polyedres
// Nom type = sub_type(Poly_geom_base, domaine_.valeur().zone(0).type_elem().valeur()) ? "Zone_" : "NO_FACE_Zone_";
      Nom type = "NO_FACE_Zone_";
      if (localisation_=="faces")
        {
          type="Zone_";
// On verifie que la localisation aux faces est possible sur le domaine (sinon elem ou som)
          if (domaine_.valeur().zone(0).type_elem().valeur().nb_som_face()<=2 && dimension==3)
            {
              Cerr << "'localisation faces' is not possible in 3D on the 2D surface mesh " << domaine_.le_nom() << " with the field: " << get_property("NOM")[0] << finl;
              Cerr << "Please use 'localisation elem' instead." << finl;
              exit();
            }
        }
      type += type_discr;
      le_dom_dis.discretiser(type);
    }
}
References Domaine_dis::associer_domaine(), Cerr, Objet_U::dimension, Probleme_base::discretisation(), Domaine_dis::discretiser(), domaine_, Process::exit(), finl, get_property(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), le_dom_dis, O_U_Ptr::le_nom(), localisation_, Elem_geom_base::nb_som_face(), O_U_Ptr::non_nul(), Objet_U::que_suis_je(), Zone::type_elem(), Deriv_Elem_geom_base::valeur(), Ref_Domaine::valeur(), and Domaine::zone().
Referenced by completer().
duplique()
int Champ_Generique_Interpolation::duplique () const override virtual
Implements Objet_U.
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
fixer_noms_compo()
const Noms & Champ_Generique_Interpolation::fixer_noms_compo (const Noms & noms)
Definition at line 588 of file Champ_Generique_Interpolation.cpp.
{
  return compo_=noms;
}
References compo_.
Referenced by Postraitement::creer_champ_post(), and Postraitement::creer_champ_post_stat().
fixer_noms_synonyms()
const Noms & Champ_Generique_Interpolation::fixer_noms_synonyms (const Noms & noms)
Definition at line 584 of file Champ_Generique_Interpolation.cpp.
{
  return syno_=noms;
}
References syno_.
Referenced by Postraitement::creer_champ_post().
get_champ()
const Champ_base & Champ_Generique_Interpolation::get_champ (Champ & espace_stockage) const override virtual
Interpolation du champ source en fonction de la methode, localisation et
domaine demandes.
Implements Champ_Generique_base.
Definition at line 163 of file Champ_Generique_Interpolation.cpp.
{
  if (localisation_ == "")
    {
      Cerr << "Error in Champ_Generique_Interpolation::get_champ()\n"
           << " Localisation has not been initialized" << finl;
      exit();
    }
  if (methode_ == "calculer_champ_post")
    {
      get_champ_with_calculer_champ_post(espace_stockage);
    }
  else
    {
      Cerr << "Champ_Generique_Interpolation::get_champ : methode " << methode_ << " uncoded" << finl;
      exit();
    }
  return espace_stockage.valeur();
}
References Cerr, Process::exit(), finl, get_champ_with_calculer_champ_post(), localisation_, methode_, and Deriv_Champ_base::valeur().
Referenced by get_ref_values().
get_champ_with_calculer_champ_post()
const Champ_base & Champ_Generique_Interpolation::get_champ_with_calculer_champ_post (Champ & espace_stockage) const virtual
Interpolation du champ source a l'aide de Champ_base::calculer_champ_xxx_post.
< on ajoute 0.1 pour le cas ou v vaut i-epsilon
Definition at line 218 of file Champ_Generique_Interpolation.cpp.
{
  Champ espace_stockage_source;
  const Champ_base& source0 = get_source(0).get_champ(espace_stockage_source);
  Champ source_bis;
  if (optimisation_sous_maillage_==-1)
    {
      source_bis=source0;
// source.typer(source0.que_suis_je());
    }
  const Champ_base& source  = ((optimisation_sous_maillage_==-1)?source_bis.valeur():source0);
  Nom nom_champ_interpole;
// Domaine sur lequel on interpole le champ :
// si domaine_ est une ref nulle, on prend le domaine natif du champ.
  const Domaine& domaine = get_ref_domain();
  const Noms compo = get_property("composantes");
  const Noms nom_champ = get_property("nom");
  const Noms syno = get_property("synonyms");
  int ncomp;
// On fixe identifiant_appel_ a nom_champ[0] dans le cas ou il est egal a ??
  if (identifiant_appel_=="??")
    {
      ncomp = -1;
    }
  else
    {
      ncomp = Champ_Generique_base::composante(identifiant_appel_,nom_champ[0],compo,syno);
    }
// Creation du champ espace_stockage
  Nature_du_champ nature_source = (ncomp==-1)?source.nature_du_champ():scalaire;
  nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
// double default_value=-1e35;
// espace_stockage.valeurs()=default_value;
  int decal=10;
  if (optimisation_sous_maillage_==-1)
    {
      espace_stockage.valeurs()=0;
// premier appel avec maillage different (ou on a force) , on essaye de voir si on peut optimiser
// on champ la source on y met val(i)=i, pour recuperer le numero de la maille apres
      DoubleTab& val=source_bis.valeurs();
      int dim0 = val.dimension_tot(0);
      for (int i=0; i<dim0; i++)
        for (int j=0; j<nb_comp; j++)
          val(i,j) = i+decal;
    }
// Evaluation des valeurs du champ espace_stockage
  DoubleTab& espace_valeurs = espace_stockage->valeurs();
  if (optimisation_sous_maillage_==1)
    {
      const DoubleTab& val_temp= source.valeurs();
      int dim0 = espace_valeurs.dimension(0);
      for (int i=0; i<dim0; i++)
        if (ncomp==-1)
          for (int j=0; j<nb_comp; j++)
            {
              int n=renumerotation_maillage_[i];
              if (n>=0)
                espace_valeurs(i,j) = val_temp(n,j);
            }
        else espace_valeurs(i, ncomp) = val_temp[renumerotation_maillage_[i]];
      espace_valeurs.echange_espace_virtuel();
      return espace_stockage.valeur();
    }
  int imax=0;
// int jmax=0;;
  imax = espace_valeurs.dimension(0);
// if (espace_valeurs.nb_dim()==2)
// jmax = espace_valeurs.dimension(1);
  if (localisation_ == "elem")
    {
      const int nb_elements = domaine.zone(0).nb_elem();
      if (ncomp==-1)
        {
          DoubleTab val_temp;
          source.calculer_valeurs_elem_post(val_temp,
                                            nb_elements,
                                            nom_champ_interpole,
                                            domaine);
          for (int i_val=0; i_val<imax; i_val++)
            for (int j_val=0; j_val<nb_comp; j_val++)
              espace_valeurs(i_val,j_val) = val_temp(i_val,j_val);
        }
      else
// On construit un tableau de valeurs a nb_comp composantes meme si ncomp!=-1
        {
          DoubleTab val_temp;
          source.calculer_valeurs_elem_compo_post(val_temp,
                                                  ncomp,
                                                  nb_elements,
                                                  nom_champ_interpole,
                                                  domaine);
          int dim0 = val_temp.dimension(0);
          for (int i=0; i<dim0; i++)
            for (int j=0; j<nb_comp; j++)
              if (j==ncomp)
                espace_valeurs(i,j) = val_temp(i);
        }
    }
  else if (localisation_=="som")
    {
      const int nb_sommets = domaine.nb_som();
// PL: mise a jour de l'espace virtuel de la source:
      Champ copie_source;
      copie_source = source;
      copie_source.valeurs().echange_espace_virtuel();
      if (ncomp==-1)
        {
          DoubleTab val_temp;
          copie_source.valeur().calculer_valeurs_som_post(val_temp,
                                                          nb_sommets,
                                                          nom_champ_interpole,
                                                          domaine);
          for (int i_val=0; i_val<imax; i_val++)
            for (int j_val=0; j_val<nb_comp; j_val++)
              espace_valeurs(i_val,j_val) = val_temp(i_val,j_val);
        }
      else
// On construit un tableau de valeurs a nb_comp composantes meme si ncomp!=-1
        {
          DoubleTab val_temp;
          copie_source.valeur().calculer_valeurs_som_compo_post(val_temp,
                                                                ncomp,
                                                                nb_sommets,
                                                                nom_champ_interpole,
                                                                domaine);
          int dim0 = val_temp.dimension(0);
          for (int i=0; i<dim0; i++)
            for (int j=0; j<nb_comp; j++)
              if (j==ncomp)
                espace_valeurs(i,j) = val_temp(i);
        }
    }
  else
    {
// const Nom& nom_source = source.que_suis_je();
// if (((nom_source=="Champ_P1NC") || (nom_source=="Champ_Fonc_P1NC")) && (localisation_=="faces"))
// {
      espace_stockage->affecter(source);
      /* else
          {
            Cerr << "Champ_Generique_Interpolation::get_champ localisation uncoded " << localisation_ << " for " <<source.que_suis_je()<<finl;
            exit();
          }
// }
      */
    }
  if (optimisation_sous_maillage_==-1)
    {
// on recalcule le bon champ
      DoubleTab& val=espace_valeurs;
      int dim0 = val.dimension_tot(0);
      ArrOfInt& renumerotation_maillage=ref_cast_non_const(ArrOfInt, renumerotation_maillage_);
      renumerotation_maillage.resize_array(dim0);
      int ok=1;
      for (int i=0; (i<dim0)&& ok; i++)
        {
          double v;
          v=espace_valeurs(i,0) ;
          int iproche=-1;
          if (v>0)
            {
              iproche=int(v+0.1); //!< on ajoute 0.1 pour le cas ou v vaut i-epsilon
              if (std::fabs(iproche-v)>1e-5)
                {
                  ok=0;
                  Cerr<<nom_champ[0]<<" optimisation ko "<< finl;
                }
            }
          renumerotation_maillage[i]=iproche-decal;
        }
      int test=(int)mp_min(ok);
      if (test)
        {
          ref_cast_non_const(Champ_Generique_Interpolation,(*this)).optimisation_sous_maillage_=0;
          Champ espace_stockage_test;
          get_champ_with_calculer_champ_post(espace_stockage_test);
          ref_cast_non_const(Champ_Generique_Interpolation,(*this)).optimisation_sous_maillage_=test;
          get_champ_with_calculer_champ_post(espace_stockage);
          espace_stockage_test.valeurs()-=espace_stockage.valeurs();
          double dmax= mp_max_abs_vect(espace_stockage_test.valeurs());
          if (dmax > 1e-7)
            {
              Cerr<<nom_champ[0]<<" optimisation ko "<< dmax<<finl;
              exit();
            }
          else
            Cerr<<nom_champ[0]<<" optimisation ok "<< dmax<<finl;
        }
      else
        {
          if (optimisation_demande_==1)
            {
              Cerr<<nom_champ[0]<<" optimisation not allowed "<<finl;
              exit();
            }
        }
      ref_cast_non_const(Champ_Generique_Interpolation,(*this)).optimisation_sous_maillage_=test;
      return get_champ_with_calculer_champ_post(espace_stockage);
    }
  espace_valeurs.echange_espace_virtuel();
  return espace_stockage.valeur();
}
References Champ::affecter(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Cerr, Champ_Generique_base::composante(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Champ_Generique_base::get_champ(), get_champ_with_calculer_champ_post(), get_property(), get_ref_domain(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::identifiant_appel_, localisation_, mp_max_abs_vect(), Process::mp_min(), Field_base::nature_du_champ(), Field_base::nb_comp(), Zone::nb_elem(), Domaine::nb_som(), optimisation_demande_, optimisation_sous_maillage_, ref_cast_non_const, renumerotation_maillage_, TRUSTArray< _TYPE_ >::resize_array(), scalaire, test(), Deriv_Champ_base::valeur(), Champ::valeurs(), Champ_Proto::valeurs(), and Domaine::zone().
Referenced by get_champ(), and get_champ_with_calculer_champ_post().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Interpolation::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 185 of file Champ_Generique_Interpolation.cpp.
{
  Champ espace_stockage_source;
  const Champ_base& source = get_source(0).get_champ_without_evaluation(espace_stockage_source);
// Domaine sur lequel on interpole le champ :
// si domaine_ est une ref nulle, on prend le domaine natif du champ.
  const Noms compo = get_property("composantes");
  const Noms nom_champ = get_property("nom");
  const Noms syno = get_property("synonyms");
  int ncomp;
// On fixe identifiant_appel_ a nom_champ[0] dans le cas ou il est egal a ??
  if (identifiant_appel_=="??")
    {
      ncomp = -1;
    }
  else
    {
      ncomp = Champ_Generique_base::composante(identifiant_appel_,nom_champ[0],compo,syno);
    }
// Creation du champ espace_stockage
  Nature_du_champ nature_source = (ncomp==-1)?source.nature_du_champ():scalaire;
  nature_source = source.nature_du_champ();
  int nb_comp = source.nb_comp();
  Champ_Fonc es_tmp;
  espace_stockage = creer_espace_stockage(nature_source,nb_comp,es_tmp);
  return espace_stockage.valeur();
}
References Champ_Generique_base::composante(), Champ_Gen_de_Champs_Gen::creer_espace_stockage(), Champ_Generique_base::get_champ_without_evaluation(), get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::identifiant_appel_, Field_base::nature_du_champ(), Field_base::nb_comp(), scalaire, and Deriv_Champ_base::valeur().
get_copy_coordinates()
void Champ_Generique_Interpolation::get_copy_coordinates (DoubleTab & coordinates) const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 515 of file Champ_Generique_Interpolation.cpp.
{
  const DoubleTab& coord = get_ref_coordinates();
  coordinates = coord;
}
References get_ref_coordinates().
get_copy_domain()
void Champ_Generique_Interpolation::get_copy_domain (Domaine & domain) const override virtual
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 503 of file Champ_Generique_Interpolation.cpp.
{
  const Domaine& dom = get_ref_domain();
  domain = dom;
}
References get_ref_domain().
get_copy_values()
void Champ_Generique_Interpolation::get_copy_values (DoubleTab & values) const override virtual
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 461 of file Champ_Generique_Interpolation.cpp.
{
  const DoubleTab& val = get_ref_values();
// Cree une copie du tableau
  values = val;
}
References get_ref_values().
get_directive_pour_discr()
const Motcle Champ_Generique_Interpolation::get_directive_pour_discr () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 643 of file Champ_Generique_Interpolation.cpp.
{
  Motcle directive;
  if (localisation_=="elem")
    {
      directive = "champ_elem";
    }
  else if (localisation_=="som")
    {
      directive = "champ_sommets";
    }
  else if (localisation_=="faces")
    {
      directive = "champ_face";
    }
  else
    {
      Cerr<<"Localisation "<<localisation_<<" is not recognized by "<<que_suis_je()<<finl;
      exit();
    }
  return directive;
}
References Cerr, Process::exit(), finl, localisation_, and Objet_U::que_suis_je().
get_info()
const Type_info * Champ_Generique_Interpolation::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
get_localisation()
Entity Champ_Generique_Interpolation::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 468 of file Champ_Generique_Interpolation.cpp.
{
  Entity loc;
  if (localisation_=="elem")
    {
      loc = ELEMENT;
    }
  else if (localisation_=="som")
    {
      loc = NODE;
    }
  else if (localisation_=="faces")
    {
      loc = FACE;
    }
  else
    {
      Cerr << "Error of type : localisation should be specified to elem or som or faces for the defined field " << nom_post_ << finl;
      throw Champ_Generique_erreur("INVALID");
    }
  return loc;
}
References Cerr, ELEMENT, FACE, finl, localisation_, NODE, and Champ_Generique_base::nom_post_.
get_property()
const Noms Champ_Generique_Interpolation::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 521 of file Champ_Generique_Interpolation.cpp.
{
  Motcles motcles(2);
  motcles[0] = "composantes";
  motcles[1] = "synonyms";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        Noms source_compos = get_source(0).get_property("composantes");
        int nb_comp = source_compos.size();
        Noms compo(nb_comp);
        if (compo_.size()>1)
          {
// Le champ a ete cree par macro et on a rempli l attribut compo_ du Champ_Generique
// Cela permet de reproduire les noms de composantes dans les lml
            compo=compo_;
          }
        else
          {
            for (int i=0; i<nb_comp; i++)
              {
                Nom nume(i);
                compo[i] = nom_post_+nume;
              }
          }
        return compo;
        break;
      }
    case 1:
      {
        if (syno_.size()>0)
          {
            return syno_;
          }
        return get_source(0).get_property("synonyms");
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
References compo_, Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, Motcles::search(), vect_impl::size(), and syno_.
Referenced by discretiser_domaine(), get_champ_with_calculer_champ_post(), and get_champ_without_evaluation().
get_ref_coordinates()
const DoubleTab & Champ_Generique_Interpolation::get_ref_coordinates () const override virtual
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 509 of file Champ_Generique_Interpolation.cpp.
{
  const DoubleTab& coord = get_ref_domain().coord_sommets();
  return coord;
}
References Domaine::coord_sommets(), and get_ref_domain().
Referenced by get_copy_coordinates().
get_ref_domain()
const Domaine & Champ_Generique_Interpolation::get_ref_domain () const override virtual
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 491 of file Champ_Generique_Interpolation.cpp.
{
  if (domaine_.non_nul())
    {
      return domaine_.valeur();
    }
  else
    {
      return get_source(0).get_ref_domain();
    }
}
References domaine_, Champ_Generique_base::get_ref_domain(), Champ_Gen_de_Champs_Gen::get_source(), O_U_Ptr::non_nul(), and Ref_Domaine::valeur().
Referenced by Postraitement::creer_champ_post(), Postraitement::creer_champ_post_stat(), get_champ_with_calculer_champ_post(), get_copy_domain(), get_ref_coordinates(), and nommer_source().
get_ref_values()
const DoubleTab & Champ_Generique_Interpolation::get_ref_values () const override virtual
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 454 of file Champ_Generique_Interpolation.cpp.
{
  Champ champ_a_ecrire;
  get_champ(champ_a_ecrire);
  return champ_a_ecrire.valeurs();
}
References get_champ(), and Champ::valeurs().
Referenced by get_copy_values().
get_ref_zone_dis_base()
const Zone_dis_base & Champ_Generique_Interpolation::get_ref_zone_dis_base () const override virtual
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 620 of file Champ_Generique_Interpolation.cpp.
{
  if (domaine_.non_nul())
    {
      if (le_dom_dis.nombre_de_zones()==0)
        {
          Cerr << "Error in Interpolation definition:" << finl;
          Cerr << "The domain " << domaine_.le_nom() << " is not built." << finl;
          exit();
        }
      const Zone_dis_base& zone_dis = le_dom_dis.zone_dis(0).valeur();
      return zone_dis;
    }
  else
    {
      return Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base();
    }
// Pour compilation
  return get_ref_zone_dis_base();
}
References Cerr, domaine_, Process::exit(), finl, Champ_Gen_de_Champs_Gen::get_ref_zone_dis_base(), get_ref_zone_dis_base(), le_dom_dis, O_U_Ptr::le_nom(), Domaine_dis::nombre_de_zones(), O_U_Ptr::non_nul(), Deriv_Zone_dis_base::valeur(), and Domaine_dis::zone_dis().
Referenced by get_ref_zone_dis_base().
info()
const Type_info * Champ_Generique_Interpolation::info () static
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
nommer_source()
void Champ_Generique_Interpolation::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 571 of file Champ_Generique_Interpolation.cpp.
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source, nom_dom_interp;
      const Noms nom = get_source(0).get_property("nom");
      nom_champ_source = nom[0];
      nom_dom_interp = get_ref_domain().le_nom();
      nom_post_source = nom_champ_source + "_" + localisation_ + "_" +nom_dom_interp;
      nommer(nom_post_source);
    }
}
References Champ_Generique_base::get_property(), get_ref_domain(), Champ_Gen_de_Champs_Gen::get_source(), Domaine::le_nom(), localisation_, Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
printOn()
Sortie & Champ_Generique_Interpolation::printOn (Sortie & x) const override protected virtual
appel invalide
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 44 of file Champ_Generique_Interpolation.cpp.
{
  exit();
  return os;
}
References Process::exit().
readOn()
Entree & Champ_Generique_Interpolation::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 34 of file Champ_Generique_Interpolation.cpp.
{
  Champ_Gen_de_Champs_Gen::readOn(is);
  set_localisation(localisation_);
  set_methode(methode_);
  return is;
}
References localisation_, methode_, Champ_Gen_de_Champs_Gen::readOn(), set_localisation(), and set_methode().
reset()
void Champ_Generique_Interpolation::reset () override virtual
restore la configuration initiale de l'objet
localisation non specifiee, source non specifiee, methode=calculer_champ_post, domaine natif
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 68 of file Champ_Generique_Interpolation.cpp.
{
  nom_domaine_lu_ = "";
  localisation_ = "";
  methode_      = "calculer_champ_post";
  domaine_.reset();
  Champ_Gen_de_Champs_Gen::reset();
  optimisation_sous_maillage_=-1;
  optimisation_demande_=-1;
}
References domaine_, localisation_, methode_, nom_domaine_lu_, optimisation_demande_, optimisation_sous_maillage_, Ref_::reset(), and Champ_Gen_de_Champs_Gen::reset().
Referenced by Champ_Generique_Interpolation().
self_cast() [1/2]
const Champ_Generique_Interpolation & Champ_Generique_Interpolation::self_cast (const Objet_U & r) static
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
self_cast() [2/2]
Champ_Generique_Interpolation & Champ_Generique_Interpolation::self_cast (Objet_U & r) static
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
set_domaine()
int Champ_Generique_Interpolation::set_domaine (const Nom & nom_domaine, int exit_on_error = 1) virtual
Initialisation de la classe: initialisation du domaine d'interpolation
Parametres valides : "" => domaine natif, ou le nom d'un objet Domaine connu de l'interprete.
< reference nulle => domaine natif du champ
Definition at line 132 of file Champ_Generique_Interpolation.cpp.
{
  int ok = 0;
  if (nom_domaine == "")
    {
      domaine_.reset(); //!< reference nulle => domaine natif du champ
      ok = 1;
    }
  else
    {
      const Objet_U& ob = interprete().objet(nom_domaine);
      if (!sub_type(Domaine, ob))
        {
          Cerr << "Error in Champ_Generique_Interpolation::set_domaine(nom_domaine)\n"
               << " The object " << nom_domaine << " is not a domain" << finl;
          if (exit_on_error)
            {
              exit();
            }
        }
      else
        {
          domaine_ = ref_cast(Domaine, ob);
        }
    }
  return ok;
}
References Cerr, domaine_, Process::exit(), finl, Objet_U::interprete(), Interprete::objet(), ref_cast, Ref_::reset(), and sub_type.
Referenced by completer(), Postraitement::creer_champ_post(), and Postraitement::creer_champ_post_stat().
set_localisation()
int Champ_Generique_Interpolation::set_localisation (const Motcle & localisation, int exit_on_error = 1) virtual
Initialisation de la classe: initialisation de la localisation
demandee. Parametres valides : elem, som.
Definition at line 81 of file Champ_Generique_Interpolation.cpp.
{
  Motcles localisations(3);
  localisations[0] = "elem";
  localisations[1] = "som";
  localisations[2] = "faces";
  int ok = 0;
  if (localisations.search(loc) >= 0)
    {
      localisation_ = loc;
      ok = 1;
    }
  else
    {
      Cerr << "Error in Champ_Generique_Interpolation::set_localisation\n"
           << " Keyword read : " << loc << "\n The localizations allowed are " << localisations << finl;
      if (exit_on_error)
        {
          exit();
        }
    }
  return ok;
}
References Cerr, Process::exit(), finl, localisation_, and Motcles::search().
Referenced by readOn().
set_methode()
int Champ_Generique_Interpolation::set_methode (const Motcle & methode, int exit_on_error = 1) virtual
Initialisation de la classe: initialisation de la methode d'interpolation
Parametres valides : calculer_champ_post<br>(Idees pour la suite: affecter, affecter avec integrale...)
Definition at line 108 of file Champ_Generique_Interpolation.cpp.
{
  Motcles methodes_interpolation(1);
  methodes_interpolation[0] = "calculer_champ_post";
  int ok = 0;
  if (methodes_interpolation.search(methode) >= 0)
    {
      methode_ = methode;
      ok = 1;
    }
  else
    {
      Cerr << "Error in Champ_Generique_Interpolation::set_methode\n"
           << " Keyword read : " << methode << "\n The methods allowed are " << methodes_interpolation << finl;
      if (exit_on_error)
        {
          exit();
        }
    }
  return ok;
}
References Cerr, Process::exit(), finl, methode_, and Motcles::search().
Referenced by readOn().
set_param()
void Champ_Generique_Interpolation::set_param (Param & param) override virtual
< XD_ADD_P chaine type_loc indicate where is done the interpolation (elem for element or som for node).
< XD_ADD_P chaine The optional keyword methode is limited to calculer_champ_post for the moment.
< XD_ADD_P chaine the domain name where the interpolation is done (by default, the calculation domain)
< XD_ADD_P dico not_set
< XD_ADD_DICO not_set
< XD_ADD_DICO not_set
< XD_ADD_DICO not_set
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 53 of file Champ_Generique_Interpolation.cpp.
{
// XD interpolation champ_post_de_champs_post interpolation -1 To create a field which is an interpolation of the field given by the keyword source.
  Champ_Gen_de_Champs_Gen::set_param(param);
  param.ajouter("localisation",&localisation_,Param::REQUIRED); //!< XD_ADD_P chaine type_loc indicate where is done the interpolation (elem for element or som for node).
  param.ajouter("methode",&methode_); //!<  XD_ADD_P chaine The optional keyword methode is limited to calculer_champ_post for the moment.
  param.ajouter("domaine",&nom_domaine_lu_);  //!<  XD_ADD_P chaine  the domain name where the interpolation is done (by default, the calculation domain)
  param.ajouter("optimisation_sous_maillage",&optimisation_demande_); //!< XD_ADD_P dico not_set
  param.dictionnaire("default",-1); //!< XD_ADD_DICO not_set
  param.dictionnaire("yes",1);  //!< XD_ADD_DICO not_set
  param.dictionnaire("no",0); //!< XD_ADD_DICO not_set
}
References Param::ajouter(), Param::dictionnaire(), localisation_, methode_, nom_domaine_lu_, optimisation_demande_, Param::REQUIRED, and Champ_Gen_de_Champs_Gen::set_param().
taille_memoire()
unsigned Champ_Generique_Interpolation::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 23 of file Champ_Generique_Interpolation.cpp.
Member Data Documentation
compo_
Noms Champ_Generique_Interpolation::compo_
Definition at line 77 of file Champ_Generique_Interpolation.h.
Referenced by fixer_noms_compo(), and get_property().
domaine_
Ref_Domaine Champ_Generique_Interpolation::domaine_ private
domaine sur lequel on veut interpoler le champ (domaine natif si reference nulle)
Definition at line 83 of file Champ_Generique_Interpolation.h.
Referenced by discretiser_domaine(), get_ref_domain(), get_ref_zone_dis_base(), reset(), and set_domaine().
info_obj
const Type_info Champ_Generique_Interpolation::info_obj static
Definition at line 41 of file Champ_Generique_Interpolation.h.
le_dom_dis
Domaine_dis Champ_Generique_Interpolation::le_dom_dis private
rempli si domaine d interpolation different du domaine natif ex : Sonde utilise valeur_aux...() qui necessite de disposer d une zone discretisee
Definition at line 84 of file Champ_Generique_Interpolation.h.
Referenced by discretiser_domaine(), and get_ref_zone_dis_base().
localisation_
Motcle Champ_Generique_Interpolation::localisation_ private
localisation d interpolation elem, som
Definition at line 80 of file Champ_Generique_Interpolation.h.
Referenced by discretiser_domaine(), get_champ(), get_champ_with_calculer_champ_post(), get_directive_pour_discr(), get_localisation(), nommer_source(), readOn(), reset(), set_localisation(), and set_param().
methode_
Motcle Champ_Generique_Interpolation::methode_ private
calculer_champ_post, etc...
Definition at line 81 of file Champ_Generique_Interpolation.h.
Referenced by get_champ(), readOn(), reset(), set_methode(), and set_param().
nom_domaine_lu_
Nom Champ_Generique_Interpolation::nom_domaine_lu_ private
Nom du domaine lu.
Definition at line 82 of file Champ_Generique_Interpolation.h.
Referenced by completer(), reset(), and set_param().
optimisation_demande_
int Champ_Generique_Interpolation::optimisation_demande_ private
Definition at line 86 of file Champ_Generique_Interpolation.h.
Referenced by completer(), get_champ_with_calculer_champ_post(), reset(), and set_param().
optimisation_sous_maillage_
int Champ_Generique_Interpolation::optimisation_sous_maillage_ private
Definition at line 86 of file Champ_Generique_Interpolation.h.
Referenced by completer(), get_champ_with_calculer_champ_post(), and reset().
renumerotation_maillage_
ArrOfInt Champ_Generique_Interpolation::renumerotation_maillage_ private
Definition at line 87 of file Champ_Generique_Interpolation.h.
Referenced by get_champ_with_calculer_champ_post().
syno_
Noms Champ_Generique_Interpolation::syno_
Definition at line 77 of file Champ_Generique_Interpolation.h.
Referenced by fixer_noms_synonyms(), and get_property().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Interpolation.h
src/Kernel/Champs/Champ_Generique_Interpolation.cpp