TRUST: Hexaedre Class Reference
Hexaedre Class Reference
Classe Hexaedre
Cette represente un element geometrique a 6 faces, 8 sommets et
un seul type de face (Faces::quadrangle_3D) a 4 sommets.
#include <Hexaedre.h>
Public Member Functions
Hexaedre ()
~Hexaedre ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int face_sommet (int i, int j) const override
Cette methode n'est plus inlinee car probleme au link symbol "reference dans une section .rodata" sur certains compilateurs gcc 3.3.x.
int face_sommet0 (int i) const
Renvoie le numero du i-ieme sommet de la face 0.
int face_sommet1 (int i) const
Renvoie le numero du i-ieme sommet de la face 1.
int face_sommet2 (int i) const
Renvoie le numero du i-ieme sommet de la face 2.
int face_sommet3 (int i) const
Renvoie le numero du i-ieme sommet de la face 3.
int face_sommet4 (int i) const
Renvoie le numero du i-ieme sommet de la face 4.
int face_sommet5 (int i) const
Renvoie le numero du i-ieme sommet de la face 5.
int nb_som () const override
Renvoie le nombre de sommets d'un hexaedre: 8.
int nb_faces (int=0) const override
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
int nb_som_face (int=0) const override
Renvoie le nombre de sommets des faces
du type specifie.
int est_structure () const override
Renvoie toujours 1, car l'element geometrique
Hexaedre est de type structure.
const Nom & nom_lml () const override
Renvoie le nom LML d'un triangle = "VOXEL8".
int contient (const ArrOfDouble &, int) const override
Renvoie 1 si l'element "elemen" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
int contient (const ArrOfInt &, int) const override
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Type_Face type_face (int=0) const override
Renvoie le i-ieme type de face.
Un hexaedre n'a qu'un seul type de face.
void reordonner () override
Reordonne les sommets de l'hexaedre.
int reordonner_elem ()
Reordonne les sommets de l'hexaedre.
void calculer_volumes (DoubleVect &) const override
Calcule les volumes des elements de la zone associee.
void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const override
Calcule les normales aux faces des elements de la zone associee.
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
voir ElemGeomBase::get_tab_faces_sommets_locaux
Public Member Functions inherited from Elem_geom_base
Elem_geom_base ()
~Elem_geom_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void creer_faces_elem (Faces &, int, Type_Face) const
Cree les faces de l'element geometrique specifie de la zone
en precisant le type de face a creer.
void creer_faces_elem (Faces &, int) const
Cree les faces de l'element de la zone specifie.
virtual int face_sommet (int i, int j) const =0
void associer_zone (const Zone &)
Associe l'element geometrique a sa zone.
virtual int nb_som () const =0
virtual int nb_faces (int=0) const =0
virtual int nb_som_face (int=0) const =0
virtual int est_structure () const =0
virtual const Nom & nom_lml () const =0
virtual int contient (const ArrOfDouble &, int) const =0
virtual int contient (const ArrOfInt &, int) const =0
virtual int nb_type_face () const
Renvoie le nombre de type de face de l'element
geometrique.
Par exemple un prisme (Classe Prisme)
a 2 types de faces: un triangle ou un quadrangle.
virtual int num_face (int face, Type_Face &type) const
Renvoie le parametre face si le type
de face specifie est le meme que celui de l'element
geometrique.
virtual Type_Face type_face (int=0) const =0
virtual void calculer_centres_gravite (DoubleTab &) const
Calcule les centres de gravites de tous les elements
de la zone associee a l'element goemetrique.
virtual void reordonner ()
NE FAIT RIEN:
A surcharger dans les classes derivees.
virtual void calculer_volumes (DoubleVect &) const =0
virtual void calculer_normales (const IntTab &faces_sommets, DoubleTab &face_normales) const
Sort en erreur. Cette methode n'est pas virtuelle pure
pour des raisons de commodite.
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
remplit le tableau faces_som_local(i,j) qui donne pour
0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre
de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees
du tableau sont mises a -1
On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes:
aretes_som_local.dimension(0) = nombre d'aretes sur l'element de reference
aretes_som_local.dimension(1) = 2 (nombre de sommets par arete)
aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Hexaedre & self_cast (Objet_U &)
static const Hexaedre & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_geom_base
static const Type_info * info ()
static Elem_geom_base & self_cast (Objet_U &)
static const Elem_geom_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_geom_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_geom_base
Ref_Zone ma_zone
Detailed Description
Classe Hexaedre
Cette represente un element geometrique a 6 faces, 8 sommets et
un seul type de face (Faces::quadrangle_3D) a 4 sommets.
Definition at line 35 of file Hexaedre.h.
Constructor & Destructor Documentation
Hexaedre()
Hexaedre::Hexaedre ()
Definition at line 39 of file Hexaedre.cpp.
~Hexaedre()
Hexaedre::~Hexaedre ()
Definition at line 39 of file Hexaedre.cpp.
Member Function Documentation
calculer_normales()
void Hexaedre::calculer_normales (const IntTab & faces_sommets, DoubleTab & face_normales) const override virtual
Calcule les normales aux faces des elements de la zone associee.
Reimplemented from Elem_geom_base.
Definition at line 347 of file Hexaedre.cpp.
{
  const Zone& zone_geom = ma_zone.valeur();
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  int nbfaces = Face_sommets.dimension(0);
  double x1,y1,z1,x2,y2,z2;
  int n0,n1,n2;
  for (int numface=0; numface<nbfaces; numface++)
    {
      n0 = Face_sommets(numface,0);
      n1 = Face_sommets(numface,1);
      n2 = Face_sommets(numface,2);
      x1 = les_coords(n0,0) - les_coords(n1,0);
      y1 = les_coords(n0,1) - les_coords(n1,1);
      z1 = les_coords(n0,2) - les_coords(n1,2);
      x2 = les_coords(n2,0) - les_coords(n1,0);
      y2 = les_coords(n2,1) - les_coords(n1,1);
      z2 = les_coords(n2,2) - les_coords(n1,2);
      face_normales(numface,0) = (y1*z2 - y2*z1);
      face_normales(numface,1) = (-x1*z2 + x2*z1);
      face_normales(numface,2) = (x1*y2 - x2*y1);
    }
}
References Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Elem_geom_base::ma_zone, and Ref_Zone::valeur().
calculer_volumes()
void Hexaedre::calculer_volumes (DoubleVect & volumes) const override virtual
Calcule les volumes des elements de la zone associee.
Implements Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 307 of file Hexaedre.cpp.
{
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  double dx,dy,dz;
  int S1,S2,S3,S4;
  int size_tot = zone.nb_elem_tot();
  assert(volumes.size_totale()==size_tot);
  for (int num_poly=0; num_poly<size_tot; num_poly++)
    {
      S1 = zone.sommet_elem(num_poly,0);
      S2 = zone.sommet_elem(num_poly,1);
      S3 = zone.sommet_elem(num_poly,2);
      S4 = zone.sommet_elem(num_poly,4);
      dx = dom.coord(S2,0) - dom.coord(S1,0);
      dy = dom.coord(S3,1) - dom.coord(S1,1);
      dz = dom.coord(S4,2) - dom.coord(S1,2);
      volumes[num_poly]= dx*dy*dz;
    }
}
References Domaine::coord(), Zone::domaine(), Elem_geom_base::ma_zone, Zone::nb_elem_tot(), TRUSTVect< _TYPE_ >::size_totale(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [1/2]
int Hexaedre::contient (const ArrOfDouble & pos, int element) const override virtual
Renvoie 1 si l'element "elemen" de la zone associee a
l'element geometrique contient le point
de coordonnees specifiees par le parametre "pos".
Renvoie 0 sinon.
Returns
int
Signification: 1 si le point de coordonnees specifiees
appartient a l'element "element"
0 sinon
Contraintes:
Implements Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 236 of file Hexaedre.cpp.
{
  assert(pos.size_array()==3);
  const Zone& zone=ma_zone.valeur();
  const Domaine& dom=zone.domaine();
  int som0 = zone.sommet_elem(element,0);
  int som7 = zone.sommet_elem(element,7);
  if (    inf_ou_egal(dom.coord(som0,0),pos[0]) && inf_ou_egal(pos[0],dom.coord(som7,0))
          && inf_ou_egal(dom.coord(som0,1),pos[1]) && inf_ou_egal(pos[1],dom.coord(som7,1))
          && inf_ou_egal(dom.coord(som0,2),pos[2]) && inf_ou_egal(pos[2],dom.coord(som7,2)) )
    return 1;
  else
    return 0;
}
References Domaine::coord(), Zone::domaine(), inf_ou_egal(), Elem_geom_base::ma_zone, TRUSTArray< _TYPE_ >::size_array(), Zone::sommet_elem(), and Ref_Zone::valeur().
contient() [2/2]
int Hexaedre::contient (const ArrOfInt & som, int element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos"
sont les sommets de l'element "element" de la zone associee a
l'element geometrique.
Returns
int
Signification: 1 si les sommets passes en parametre
sont ceux de l'element specifie, 0 sinon
Contraintes:
Implements Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 276 of file Hexaedre.cpp.
{
  const Zone& zone=ma_zone.valeur();
  if((zone.sommet_elem(element,0)==som[0])&&
      (zone.sommet_elem(element,1)==som[1])&&
      (zone.sommet_elem(element,2)==som[2])&&
      (zone.sommet_elem(element,3)==som[3])&&
      (zone.sommet_elem(element,4)==som[4])&&
      (zone.sommet_elem(element,5)==som[5])&&
      (zone.sommet_elem(element,6)==som[6])&&
      (zone.sommet_elem(element,7)==som[7]))
    return 1;
  else
    return 0;
}
References Elem_geom_base::ma_zone, Zone::sommet_elem(), and Ref_Zone::valeur().
cree_instance()
Objet_U * Hexaedre::cree_instance () static
Definition at line 39 of file Hexaedre.cpp.
duplique()
int Hexaedre::duplique () const override virtual
Implements Objet_U.
Reimplemented in Hexaedre_axi.
Definition at line 39 of file Hexaedre.cpp.
est_structure()
int Hexaedre::est_structure () const inline override virtual
Renvoie toujours 1, car l'element geometrique
Hexaedre est de type structure.
Returns
int
Signification: 1 si l'element est de type structure
0 sinon
Contraintes: toujours egal a 1
Implements Elem_geom_base.
Definition at line 344 of file Hexaedre.h.
{
  return 1;
}
face_sommet()
int Hexaedre::face_sommet (int i, int j) const override virtual
Cette methode n'est plus inlinee car probleme au link symbol "reference dans une section .rodata" sur certains compilateurs gcc 3.3.x.
Renvoie le numero du j-ieme sommet de la i-ieme face de
l'element.
Returns
int
Signification: le numero du j-ieme sommet de la i-ieme face
Contraintes:
Implements Elem_geom_base.
Definition at line 406 of file Hexaedre.cpp.
{
  assert(i<6);
  switch(i)
    {
    case 0:
      return face_sommet0(j);
    case 1:
      return face_sommet1(j);
    case 2:
      return face_sommet2(j);
    case 3:
      return face_sommet3(j);
    case 4:
      return face_sommet4(j);
    case 5:
      return face_sommet5(j);
    default :
      return -1;
    }
}
References face_sommet0(), face_sommet1(), face_sommet2(), face_sommet3(), face_sommet4(), and face_sommet5().
face_sommet0()
int Hexaedre::face_sommet0 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 0.
Returns
int
Signification: le numero du i-ieme sommet de la face 0
Contraintes:
Definition at line 156 of file Hexaedre.h.
{
// face_sommet0(0)=0;
// face_sommet0(1)=2;
// face_sommet0(2)=4;
// face_sommet0(3)=6;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A hexahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet1()
int Hexaedre::face_sommet1 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 1.
Returns
int
Signification: le numero du i-ieme sommet de la face 1
Contraintes:
Definition at line 187 of file Hexaedre.h.
{
// face_sommet1(0)=0;
// face_sommet1(1)=1;
// face_sommet1(2)=4;
// face_sommet1(3)=5;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A hexahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*(i/2)+i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet2()
int Hexaedre::face_sommet2 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 2.
Returns
int
Signification: le numero du i-ieme sommet de la face 2
Contraintes:
Definition at line 218 of file Hexaedre.h.
{
// face_sommet2(0)=0;
// face_sommet2(1)=1;
// face_sommet2(2)=2;
// face_sommet2(3)=3;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A hexahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return i;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet3()
int Hexaedre::face_sommet3 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 3.
Returns
int
Signification: le numero du i-ieme sommet de la face 3
Contraintes:
Definition at line 249 of file Hexaedre.h.
{
// face_sommet3(0)=1;
// face_sommet3(1)=3;
// face_sommet3(2)=5;
// face_sommet3(3)=7;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A hexahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*i+1;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet4()
int Hexaedre::face_sommet4 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 4.
Returns
int
Signification: le numero du i-ieme sommet de la face 4
Contraintes:
Definition at line 280 of file Hexaedre.h.
{
// face_sommet4(0)=2;
// face_sommet4(1)=3;
// face_sommet4(2)=6;
// face_sommet4(3)=7;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A hexahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return 2*(i/2)+i+2;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
face_sommet5()
int Hexaedre::face_sommet5 (int i) const inline
Renvoie le numero du i-ieme sommet de la face 5.
Returns
int
Signification: le numero du i-ieme sommet de la face 5
Contraintes:
Definition at line 311 of file Hexaedre.h.
{
// face_sommet4(0)=4;
// face_sommet4(1)=5;
// face_sommet4(2)=6;
// face_sommet4(3)=7;
  assert(i>=0);
  assert(i<4);
  if(i>=4)
    {
      Cerr << "A hexahedron has not " << i << " nodes per face" << finl;
      exit();
    }
  return i+4;
}
References Cerr, Process::exit(), and finl.
Referenced by face_sommet().
get_info()
const Type_info * Hexaedre::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 39 of file Hexaedre.cpp.
get_tab_faces_sommets_locaux()
int Hexaedre::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
voir ElemGeomBase::get_tab_faces_sommets_locaux
Reimplemented from Elem_geom_base.
Definition at line 377 of file Hexaedre.cpp.
{
  faces_som_local.resize(6,4);
  for (int i=0; i<6; i++)
    for (int j=0; j<4; j++)
      faces_som_local(i,j) = faces_sommets_hexa[i][j];
  return 1;
}
References faces_sommets_hexa, and TRUSTTab< _TYPE_ >::resize().
info()
const Type_info * Hexaedre::info () static
Definition at line 39 of file Hexaedre.cpp.
nb_faces()
int Hexaedre::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie
que possede l'element geometrique.
Returns
int
Signification: le nombre de faces de type i
Contraintes: toujours egal a 6 (si i=0)
Implements Elem_geom_base.
Definition at line 103 of file Hexaedre.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A hexahedron has not " << i << " types of face" << finl;
      exit();
    }
  return 6;
}
References Cerr, Process::exit(), and finl.
nb_som()
int Hexaedre::nb_som () const inline override virtual
Renvoie le nombre de sommets d'un hexaedre: 8.
Returns
int
Signification: le nombre de sommets d'un hexaedre
Contraintes: toujours egal a 8
Implements Elem_geom_base.
Definition at line 82 of file Hexaedre.h.
{
  return 8;
}
Referenced by Hexaedre_axi::calculer_centres_gravite().
nb_som_face()
int Hexaedre::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre de sommets des faces
du type specifie.
Returns
int
Signification: le nombre de sommets des faces de type i
Contraintes: toujours egal a 4 (si i=0)
Implements Elem_geom_base.
Definition at line 130 of file Hexaedre.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A hexahedron has not " << i << " types of face" << finl;
      exit();
    }
  return 4;
}
References Cerr, Process::exit(), and finl.
nom_lml()
const Nom & Hexaedre::nom_lml () const override virtual
Renvoie le nom LML d'un triangle = "VOXEL8".
Returns
Nom&
Signification: toujours egal a "VOXEL8"
Contraintes: reference constante
Implements Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 203 of file Hexaedre.cpp.
{
  static Nom nom="VOXEL8";
  return nom;
}
printOn()
Sortie & Hexaedre::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 56 of file Hexaedre.cpp.
{
  return s;
}
readOn()
Entree & Hexaedre::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 76 of file Hexaedre.cpp.
{
  return s;
}
reordonner()
void Hexaedre::reordonner () override virtual
Reordonne les sommets de l'hexaedre.
Reimplemented from Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 95 of file Hexaedre.cpp.
{
  if (reordonner_elem()==-1)
    {
      Cerr << "This mesh is not composed of regular hexahedra\n";
      Cerr << "This seems to be VEF hexahedra (Hexaedre_VEF)\n";
      Cerr << "Check your mesh." << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, and reordonner_elem().
Referenced by Hexaedre_axi::reordonner().
reordonner_elem()
int Hexaedre::reordonner_elem ()
Reordonne les sommets de l'hexaedre.
Definition at line 120 of file Hexaedre.cpp.
{
  Zone& zone = ma_zone.valeur();
  const Domaine& dom = zone.domaine();
  const DoubleTab& dom_coord = dom.les_sommets();
  IntTab& elem = zone.les_elems();
  ArrOfInt S(8);
  ArrOfInt NS(8);
  double coord[8][3];
  double xmin[3];
  int i, j;
  const int nb_elem = zone.nb_elem();
  const int delta[3] = {1, 2, 4};
  int changed_count = 0;
  for (int num_poly = 0; num_poly < nb_elem; num_poly++)
    {
      xmin[0] = xmin[1] = xmin[2] = 1e40;
      for(i=0; i<8; i++)
        {
          int s = elem(num_poly,i);
          S[i] = s;
          NS[i] = -1;
          for(j=0; j<3; j++)
            {
              double x = dom_coord(s, j);
              coord[i][j] = x;
              if (x < xmin[j])
                xmin[j] = x;
            }
        }
// Pour chaque sommet, chercher rang dans l'element
// en fonction de ses coordonnees
      for (i=0; i<8; i++)
        {
          int num_sommet = 0;
          for (j=0; j<3; j++)
            {
              double x = coord[i][j];
              if (!est_egal(x, xmin[j]))
                num_sommet += delta[j];
            }
          if (NS[num_sommet] == -1)
            NS[num_sommet] = S[i];
          else
            return -1;
        }
// Est ce bien un hexaedre regulier ?
      if (min_array(NS)==-1)
        return -1;
// Tous les sommets ont-ils ete trouves ?
      int updated = 0;
      for(i=0; i<8; i++)
        {
          if (S[i] != NS[i])
            updated = 1;
          elem(num_poly, i) = NS[i];
        }
      if (updated)
        changed_count++;
    }
  changed_count = Process::mp_sum(changed_count);
  if (Process::je_suis_maitre())
    Cerr << "Hexaedre::reordonner : " << changed_count << " elements reversed" << finl;
  return 0;
}
References Cerr, Zone::domaine(), est_egal(), finl, Process::je_suis_maitre(), Zone::les_elems(), Domaine::les_sommets(), Elem_geom_base::ma_zone, min_array(), Process::mp_sum(), Zone::nb_elem(), and Ref_Zone::valeur().
Referenced by reordonner().
self_cast() [1/2]
const Hexaedre & Hexaedre::self_cast (const Objet_U & r) static
Definition at line 39 of file Hexaedre.cpp.
self_cast() [2/2]
Hexaedre & Hexaedre::self_cast (Objet_U & r) static
Definition at line 39 of file Hexaedre.cpp.
taille_memoire()
unsigned Hexaedre::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Hexaedre_axi.
Definition at line 39 of file Hexaedre.cpp.
type_face()
Type_Face Hexaedre::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un hexaedre n'a qu'un seul type de face.
Returns
Type_Face
Signification: un type de face
Contraintes: toujours egal a Faces::quadrangle_3D (si i=0)
Implements Elem_geom_base.
Reimplemented in Hexaedre_axi.
Definition at line 365 of file Hexaedre.h.
{
  assert(i==0);
  if(i!=0)
    {
      Cerr << "A hexahedron has not " << i << " types of face" << finl;
      exit();
    }
  return Faces::quadrangle_3D;
}
References Cerr, Process::exit(), finl, and Faces::quadrangle_3D.
Member Data Documentation
info_obj
const Type_info Hexaedre::info_obj static
Definition at line 38 of file Hexaedre.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Hexaedre.h
src/Kernel/Geometrie/Hexaedre.cpp