TRUST: Elem_EF_base Class Reference
Elem_EF_base Class Reference
#include <Elem_EF_base.h>
Public Member Functions
Elem_EF_base ()
~Elem_EF_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Elem_EF_base & self_cast (Objet_U &)
static const Elem_EF_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 37 of file Elem_EF_base.h.
Constructor & Destructor Documentation
Elem_EF_base::Elem_EF_base ()
Definition at line 26 of file Elem_EF_base.cpp.
Elem_EF_base::~Elem_EF_base ()
Definition at line 26 of file Elem_EF_base.cpp.
Member Function Documentation
virtual void Elem_EF_base::calcul_vc (const ArrOfInt & , ArrOfDouble & , const ArrOfDouble & , const DoubleTab & , const Champ_Inc_base & , int) const [pure virtual]
Implemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Tetra_EF, and Tri_EF.
Referenced by Elem_EF::calcul_vc().
virtual void Elem_EF_base::calcul_xg (DoubleVect & , const DoubleTab & , const int , int & , int & , int & , int &) const [pure virtual]
Implemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Tetra_EF, and Tri_EF.
Referenced by Elem_EF::calcul_xg().
virtual int Elem_EF_base::duplique () const [pure virtual]
Implements Objet_U.
Implemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
const Type_info * Elem_EF_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 26 of file Elem_EF_base.cpp.
const Type_info * Elem_EF_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 26 of file Elem_EF_base.cpp.
virtual void Elem_EF_base::normale (int , DoubleTab & , const IntTab & , const IntTab & , const IntTab & , const Zone &) const [pure virtual]
Implemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Referenced by Elem_EF::normale().
Sortie & Elem_EF_base::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 30 of file Elem_EF_base.cpp.
{
  return s;
}
Entree & Elem_EF_base::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 35 of file Elem_EF_base.cpp.
{
  return is;
}
Elem_EF_base & Elem_EF_base::self_cast (Objet_U & r) [static]
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 26 of file Elem_EF_base.cpp.
const Elem_EF_base & Elem_EF_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 26 of file Elem_EF_base.cpp.
Member Data Documentation
const Type_info Elem_EF_base::info_obj [static]
Reimplemented from Objet_U.
Reimplemented in Hexa_EF, Point_EF, Quadri_EF, Segment_EF, Segment_EF_axi, Tetra_EF, and Tri_EF.
Definition at line 40 of file Elem_EF_base.h.
The documentation for this class was generated from the following files:
src/EF/Zones/Elem_EF_base.h
src/EF/Zones/Elem_EF_base.cpp