TRUST: Terme_Gravite_VDF_Face Class Reference
Terme_Gravite_VDF_Face Class Reference
#include <Terme_Gravite_VDF_Face.h>
Public Member Functions
~Terme_Gravite_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Gravite_VDF_Face ()
void associer_pb (const Probleme_base &)
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Terme_Gravite_VDF_Face & self_cast (Objet_U &)
static const
Terme_Gravite_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_gravite (const Champ_Don_base &)
Protected Attributes
Ref_Champ_Don_base gravite
Detailed Description
Definition at line 54 of file Terme_Gravite_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Gravite_VDF_Face::~Terme_Gravite_VDF_Face ()
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
Terme_Gravite_VDF_Face::Terme_Gravite_VDF_Face () [inline]
Definition at line 78 of file Terme_Gravite_VDF_Face.h.
                                                      :
  Terme_Source_VDF_base(It_Sou_VDF_Face(Eval_Gravite_VDF_Face)())
{
}
Member Function Documentation
void Terme_Gravite_VDF_Face::associer_gravite (const Champ_Don_base & g) [protected]
Definition at line 67 of file Terme_Gravite_VDF_Face.cpp.
References Eval_Gravite_VDF_Face::associer(), Iterateur_Source_VDF::evaluateur(), gravite, and Terme_Source_VDF_base::iter.
Referenced by associer_pb().
{
  gravite = g;
  Eval_Gravite_VDF_Face& eval_grav = (Eval_Gravite_VDF_Face&) iter.evaluateur();
  eval_grav.associer(g);
}
void Terme_Gravite_VDF_Face::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 60 of file Terme_Gravite_VDF_Face.cpp.
References associer_gravite(), Milieu_base::gravite(), and Probleme_base::milieu().
{
  const Milieu_base& le_milieu = pb.milieu();
  const Champ_Don_base& la_gravite = le_milieu.gravite();
  associer_gravite(la_gravite);
}
void Terme_Gravite_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Implements Source_base.
Definition at line 48 of file Terme_Gravite_VDF_Face.cpp.
References Evaluateur_Source_VDF::associer_zones(), Iterateur_Source_VDF::evaluateur(), Terme_Source_VDF_base::iter, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  iter->associer_zones(zvdf, zclvdf);
  Eval_Gravite_VDF_Face& eval_grav = (Eval_Gravite_VDF_Face&) iter.evaluateur();
  eval_grav.associer_zones(zvdf, zclvdf );
}
Objet_U * Terme_Gravite_VDF_Face::cree_instance () [static]
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
int Terme_Gravite_VDF_Face::duplique () const [virtual]
Implements Terme_Source_VDF_base.
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
const Type_info * Terme_Gravite_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
const Type_info * Terme_Gravite_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
void Terme_Gravite_VDF_Face::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 63 of file Terme_Gravite_VDF_Face.h.
  {
    gravite->mettre_a_jour(temps);
  };
Sortie & Terme_Gravite_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 33 of file Terme_Gravite_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
Entree & Terme_Gravite_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_VDF_base.
Definition at line 41 of file Terme_Gravite_VDF_Face.cpp.
References Source_base::set_description(), and Source_base::set_fichier().
{
  set_fichier("Gravite");
  set_description("Buoyancy term = Integral(rho*g*dv) [m/s2]");
  return s ;
}
Terme_Gravite_VDF_Face & Terme_Gravite_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_VDF_base.
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
const Terme_Gravite_VDF_Face & Terme_Gravite_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_VDF_base.
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
unsigned Terme_Gravite_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Terme_Gravite_VDF_Face.cpp.
Member Data Documentation
Ref_Champ_Don_base Terme_Gravite_VDF_Face::gravite [protected]
Definition at line 66 of file Terme_Gravite_VDF_Face.h.
Referenced by associer_gravite().
const Type_info Terme_Gravite_VDF_Face::info_obj [static]
Reimplemented from Terme_Source_VDF_base.
Definition at line 56 of file Terme_Gravite_VDF_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Gravite_VDF_Face.h
src/VDF/Sources/Terme_Gravite_VDF_Face.cpp