TRUST: DP_Impose_PolyMAC_Face Class Reference
DP_Impose_PolyMAC_Face Class Reference
class DP_Impose_PolyMAC_Face
#include <DP_Impose_PolyMAC_Face.h>
Public Member Functions
DP_Impose_PolyMAC_Face ()
~DP_Impose_PolyMAC_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void remplir_num_faces (Entree &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Perte_Charge_PolyMAC_Face
Perte_Charge_PolyMAC_Face ()
~Perte_Charge_PolyMAC_Face () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Public Member Functions inherited from DP_Impose
~DP_Impose () override
Entree & lire_donnees (Entree &)
Lit les specifications d'un Delta P impose
a partir d'un flot d'entree.
void mettre_a_jour (double temps)
Public Member Functions inherited from Perte_Charge_Singuliere
virtual ~Perte_Charge_Singuliere ()
Entree & lire_donnees (Entree &)
Lit les specifications d'une perte de charge singuliere
a partir d'un flot d'entree.
virtual void lire_surfaces (Entree &, const Domaine &, const Zone_dis_base &, IntVect &, IntVect &)
double K () const
double calculate_Q (const Equation_base &eqn, const IntVect &num_faces, const IntVect &sgn) const
void update_K (const Equation_base &eqn, double deb, DoubleVect &bilan)
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Renvoie la direction de perte de charge.
(X,Y ou Z), ou -1 si toutes les directions.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static DP_Impose_PolyMAC_Face & self_cast (Objet_U &)
static const DP_Impose_PolyMAC_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Perte_Charge_PolyMAC_Face
static const Type_info * info ()
static Perte_Charge_PolyMAC_Face & self_cast (Objet_U &)
static const Perte_Charge_PolyMAC_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Perte_Charge_PolyMAC_Face
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Member Functions inherited from Perte_Charge_PolyMAC_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect sgn
double surf
Protected Attributes inherited from Perte_Charge_PolyMAC_Face
Ref_Champ_Inc_base la_vitesse
Ref_Fluide_base le_fluide
IntVect num_faces
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Protected Attributes inherited from DP_Impose
Champ_Don DP_
Protected Attributes inherited from Perte_Charge_Singuliere
double K_
Nom identifiant_
int regul_
Parser_U deb_cible_
Parser_U eps_
Protected Attributes inherited from Perte_Charge
int direction_perte_charge_
Detailed Description
class DP_Impose_PolyMAC_Face
See also
Perte_Charge_PolyMAC_Face
Definition at line 35 of file DP_Impose_PolyMAC_Face.h.
Constructor & Destructor Documentation
DP_Impose_PolyMAC_Face()
DP_Impose_PolyMAC_Face::DP_Impose_PolyMAC_Face ()
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
~DP_Impose_PolyMAC_Face()
DP_Impose_PolyMAC_Face::~DP_Impose_PolyMAC_Face ()
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
Member Function Documentation
ajouter_blocs()
void DP_Impose_PolyMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
Definition at line 82 of file DP_Impose_PolyMAC_Face.cpp.
{
  const Zone_Poly_base& zone_poly = ref_cast(Zone_Poly_base,equation().zone_dis().valeur());
  const DoubleVect& pf = zone_poly.porosite_face(), &fs = zone_poly.face_surfaces();
  const DoubleTab& vit = equation().inconnue().valeurs();
  const std::string& nom_inco = equation().inconnue().le_nom().getString();
  Matrice_Morse *mat = matrices.count(nom_inco) ? matrices.at(nom_inco) : NULL;
// valeurs du champ de DP
  DoubleTrav xvf(num_faces.size(), dimension), DP(num_faces.size(), 3);
  for (int i = 0; i < num_faces.size(); i++)
    for (int j = 0; j < dimension; j++) xvf(i, j) = zone_poly.xv()(num_faces(i), j);
  DP_.valeur().valeur_aux(xvf, DP);
  double rho = equation().milieu().masse_volumique()(0, 0), fac_rho = equation().probleme().is_dilatable() ? 1.0 : 1.0 / rho;
  for (int i = 0, f; i < num_faces.size(); i++)
    if ((f = num_faces(i)) < zone_poly.nb_faces())
      {
        secmem(f) += fs(f) * pf(f) * sgn(i) * (DP(i, 0) + DP(i, 1) * (surf * sgn(i) * vit(f) - DP(i, 2))) * fac_rho;
        if (mat) (*mat)(f, f) -= fs(f) * pf(f) * DP(i, 1) * surf * fac_rho;
      }
  bilan().resize(4); //DP dDP/dQ Q Q0
  bilan()(0) = Process::mp_max(num_faces.size() ? DP(0, 0)       : -DBL_MAX);
  bilan()(1) = Process::mp_max(num_faces.size() ? DP(0, 1) / rho : -DBL_MAX);
  bilan()(3) = Process::mp_max(num_faces.size() ? DP(0, 2) * rho : -DBL_MAX);
  if (Process::me()) bilan() = 0; //pour eviter un sommage en sortie
}
References Source_base::bilan(), Objet_U::dimension, DP_Impose::DP_, MorEqn::equation(), Zone_VF::face_surfaces(), Nom::getString(), Equation_base::inconnue(), Probleme_base::is_dilatable(), O_U_Ptr::le_nom(), Milieu_base::masse_volumique(), Process::me(), Equation_base::milieu(), Process::mp_max(), Zone_VF::nb_faces(), Perte_Charge_PolyMAC_Face::num_faces, Zone_VF::porosite_face(), Equation_base::probleme(), ref_cast, TRUSTVect< _TYPE_ >::resize(), sgn, TRUSTVect< _TYPE_ >::size(), surf, Deriv_Champ_Don_base::valeur(), valeur(), Champ_base::valeur_aux(), Champ_Inc::valeurs(), and Zone_VF::xv().
cree_instance()
Objet_U * DP_Impose_PolyMAC_Face::cree_instance () static
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
dimensionner_blocs()
void DP_Impose_PolyMAC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const inline override virtual
Reimplemented from Source_base.
Definition at line 46 of file DP_Impose_PolyMAC_Face.h.
{}) const override { }; //rien
duplique()
int DP_Impose_PolyMAC_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
get_info()
const Type_info * DP_Impose_PolyMAC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
has_interface_blocs()
int DP_Impose_PolyMAC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 42 of file DP_Impose_PolyMAC_Face.h.
  {
    return 1;
  };
info()
const Type_info * DP_Impose_PolyMAC_Face::info () static
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
mettre_a_jour()
void DP_Impose_PolyMAC_Face::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 112 of file DP_Impose_PolyMAC_Face.cpp.
{
  DP_Impose::mettre_a_jour(temps);
  bilan().resize(4); //DP dDP/dQ Q Q0
  bilan()(2) = calculate_Q(equation(), num_faces, sgn) * (Process::me() ? 0 : 1); //pour eviter le sommage en sortie
}
References Source_base::bilan(), Perte_Charge_Singuliere::calculate_Q(), MorEqn::equation(), Process::me(), DP_Impose::mettre_a_jour(), Perte_Charge_PolyMAC_Face::num_faces, TRUSTVect< _TYPE_ >::resize(), and sgn.
printOn()
Sortie & DP_Impose_PolyMAC_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 29 of file DP_Impose_PolyMAC_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & DP_Impose_PolyMAC_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 37 of file DP_Impose_PolyMAC_Face.cpp.
{
  DP_Impose::lire_donnees(s);
  remplir_num_faces(s);
  if (!mp_max(sgn.size()))
    Cerr << "DP_Impose_PolyMAC_Face : champ d'orientation non renseigne!" << finl, Process::exit();
// fichier de sortie
  set_fichier(Nom("DP_") + identifiant_);
  set_description(Nom("DP impose sur la surface ") + identifiant_ + "\nt DP dDP/dQ Q Q0");
  return s;
}
References Cerr, Process::exit(), finl, Perte_Charge_Singuliere::identifiant_, DP_Impose::lire_donnees(), Process::mp_max(), remplir_num_faces(), Source_base::set_description(), Source_base::set_fichier(), sgn, and TRUSTVect< _TYPE_ >::size().
remplir_num_faces()
void DP_Impose_PolyMAC_Face::remplir_num_faces (Entree & s)
< not to count several (number of processes) times the same face
Definition at line 58 of file DP_Impose_PolyMAC_Face.cpp.
{
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_Poly_base& zone_poly = ref_cast(Zone_Poly_base,equation().zone_dis().valeur());
  int taille_bloc = zone_poly.nb_elem();
  num_faces.resize(taille_bloc);
  lire_surfaces(s,le_domaine,zone_poly,num_faces, sgn);
// int nfac_tot = mp_sum(num_faces.size());
  int nfac_max = (int)mp_max(num_faces.size()); //!< not to count several (number of processes) times the same face
  if(je_suis_maitre() && nfac_max == 0)
    {
      Cerr << "Error when defining the surface plane for the singular porosity :" << finl;
      Cerr << "No mesh faces has been found for the surface plane." << finl;
      Cerr << "Check the coordinate of the surface plane which should match mesh coordinates." << finl;
      exit();
    }
  DoubleTrav S;
  zone_poly.creer_tableau_faces(S);
  for (int i = 0; i < num_faces.size(); i++) S(num_faces(i)) = zone_poly.face_surfaces(num_faces(i));
  surf = mp_somme_vect(S);
}
References Cerr, Zone_VF::creer_tableau_faces(), Probleme_base::domaine(), MorEqn::equation(), Process::exit(), Zone_VF::face_surfaces(), finl, Process::je_suis_maitre(), Perte_Charge_Singuliere::lire_surfaces(), Process::mp_max(), mp_somme_vect(), Zone_dis_base::nb_elem(), Perte_Charge_PolyMAC_Face::num_faces, Equation_base::probleme(), ref_cast, TRUSTVect< _TYPE_ >::resize(), sgn, TRUSTVect< _TYPE_ >::size(), surf, and valeur().
Referenced by readOn().
self_cast() [1/2]
const DP_Impose_PolyMAC_Face & DP_Impose_PolyMAC_Face::self_cast (const Objet_U & r) static
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
self_cast() [2/2]
DP_Impose_PolyMAC_Face & DP_Impose_PolyMAC_Face::self_cast (Objet_U & r) static
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
taille_memoire()
unsigned DP_Impose_PolyMAC_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file DP_Impose_PolyMAC_Face.cpp.
Member Data Documentation
info_obj
const Type_info DP_Impose_PolyMAC_Face::info_obj static
Definition at line 39 of file DP_Impose_PolyMAC_Face.h.
sgn
IntVect DP_Impose_PolyMAC_Face::sgn protected
Definition at line 52 of file DP_Impose_PolyMAC_Face.h.
Referenced by ajouter_blocs(), mettre_a_jour(), readOn(), and remplir_num_faces().
surf
double DP_Impose_PolyMAC_Face::surf protected
Definition at line 53 of file DP_Impose_PolyMAC_Face.h.
Referenced by ajouter_blocs(), and remplir_num_faces().
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/DP_Impose_PolyMAC_Face.h
src/PolyMAC/Sources/DP_Impose_PolyMAC_Face.cpp