TRUST: Zone_CoviMAC Class Reference
Zone_CoviMAC Class Reference
class Zone_CoviMAC
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
#include <Zone_CoviMAC.h>
Public Member Functions
Zone_CoviMAC ()
~Zone_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void typer_elem (Zone &zone_geom)
void discretiser ()
Genere les faces
construits les frontieres.
virtual void reordonner (Faces &)
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
void modifier_pour_Cl (const Conds_lim &)
const Elem_CoviMAC & type_elem () const
int nb_elem_Cl () const
int nb_faces_joint () const
int nb_faces_std () const
int nb_elem_std () const
double carre_pas_du_maillage () const
double carre_pas_maille (int i) const
double face_normales (int, int) const
DoubleTab & face_normales ()
const DoubleTab & face_normales () const
IntVect & rang_elem_non_std ()
const IntVect & rang_elem_non_std () const
int oriente_normale (int face_opp, int elem2) const
const ArrOfInt & ind_faces_virt_non_std () const
void calculer_h_carre ()
DoubleTab & volumes_entrelaces_dir ()
const DoubleTab & volumes_entrelaces_dir () const
double dot (const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
std::array< double, 3 > cross (int dima, int dimb, const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
double dist_norm (int num_face) const
double dist_norm_bord (int num_face) const
DoubleVect & dist_norm_bord (DoubleVect &, const Nom &nom_bord) const
double dist_face_elem0 (int num_face, int n0) const
double dist_face_elem1 (int num_face, int n1) const
double dist_face_elem0_period (int num_face, int n0, double l) const
double dist_face_elem1_period (int num_face, int n1, double l) const
void detecter_faces_non_planes () const
void init_equiv () const
void init_ve () const
void init_stencils () const
double nu_dot (const DoubleTab *nu, int e, int n, const double *a, const double *b, const double *ma=NULL, const double *mb=NULL) const
void harmonic_points (const Conds_lim &cls, int is_p, int nu_grad, const DoubleTab *nu, const DoubleTab *invh, DoubleTab &xh, DoubleTab &wh, DoubleTab *whm) const
void fgrad (const Conds_lim &cls, const IntTab &fcl, const DoubleTab *nu, const DoubleTab *invh, const DoubleTab &xh, const DoubleTab &wh, const DoubleTab *whm, const IntTab *pe_ext, int nu_grad, int full_stencil, DoubleTab &phif_w, IntTab &phif_d, IntTab &phif_e, DoubleTab &phif_c, IntTab *phif_pe, DoubleTab *phif_pc) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Zone_CoviMAC & self_cast (Objet_U &)
static const Zone_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
std::map< std::string, int > is_init
IntTab equiv
IntTab ved
IntTab vej
DoubleTab vec
IntTab fsten_d
IntTab fsten_f
MD_Vector mdv_ch_face
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Private Member Functions
void remplir_elem_faces ()
Sortie & ecrit (Sortie &os) const
void creer_faces_virtuelles_non_std ()
Private Attributes
double h_carre
carre du pas du maillage
DoubleVect h_carre_
carre du pas d'une maille
Elem_CoviMAC type_elem_
type de l'element de discretisation
DoubleTab face_normales_
normales aux faces
int nb_faces_std_
nombre de faces standard
int nb_elem_std_
nombre d'elements standard
IntVect rang_elem_non_std_
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
ArrOfInt ind_faces_virt_non_std_
contient les indices des faces virtuelles non standard
Detailed Description
class Zone_CoviMAC
Classe instanciable qui derive de Zone_VF.
Cette classe contient les informations geometriques que demande
la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
La classe porte un certain nombre d'informations concernant les faces
Dans cet ensemble de faces on fait figurer aussi les faces du bord et
des joints. Pour manipuler les faces on distingue 2 categories:
- les faces non standard qui sont sur un joint, un bord ou qui sont
internes tout en appartenant a un element du bord
- les faces standard qui sont les faces internes n'appartenant pas
a un element du bord
Cette distinction correspond au traitement des conditions aux limites:les
faces standard ne "voient pas" les conditions aux limites.
L'ensemble des faces est numerote comme suit:
- les faces qui sont sur une Zone_joint apparaissent en premier
(dans l'ordre du vecteur les_joints)
- les faces qui sont sur une Zone_bord apparaissent ensuite
(dans l'ordre du vecteur les_bords)
- les faces internes non standard apparaissent ensuite
- les faces internes standard en dernier
Finalement on trouve regroupees en premier toutes les faces non standard
qui vont necessiter un traitement particulier
On distingue deux types d'elements
- les elements non standard : ils ont au moins une face de bord
- les elements standard : ils n'ont pas de face de bord
Les elements standard (resp. les elements non standard) ne sont pas ranges
de maniere consecutive dans l'objet Zone. On utilise le tableau
rang_elem_non_std pour acceder de maniere selective a l'un ou
l'autre des types d'elements
Definition at line 95 of file Zone_CoviMAC.h.
Constructor & Destructor Documentation
Zone_CoviMAC::Zone_CoviMAC ()
Definition at line 83 of file Zone_CoviMAC.cpp.
Zone_CoviMAC::~Zone_CoviMAC ()
Definition at line 83 of file Zone_CoviMAC.cpp.
Member Function Documentation
void Zone_CoviMAC::calculer_h_carre ()
Definition at line 547 of file Zone_CoviMAC.cpp.
References Zone_VF::elem_faces(), Zone_VF::face_surfaces(), h_carre, h_carre_, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Zone::nb_faces_elem(), DoubleVect::resize(), Zone_VF::volumes(), and Zone_dis_base::zone().
{
// Calcul de h_carre
  h_carre = 1.e30;
  h_carre_.resize(nb_faces());
// Calcul des surfaces
  const DoubleVect& surfaces=face_surfaces();
  const int& nb_faces_elem=zone().nb_faces_elem();
  const int& nbe=nb_elem();
  for (int num_elem=0; num_elem<nbe; num_elem++)
    {
      double surf_max = 0;
      for (int i=0; i<nb_faces_elem; i++)
        {
          double surf = surfaces(elem_faces(num_elem,i));
          surf_max = (surf > surf_max)? surf : surf_max;
        }
      double vol = volumes(num_elem)/surf_max;
      vol *= vol;
      h_carre_(num_elem) = vol;
      h_carre = ( vol < h_carre )? vol : h_carre;
    }
}
double Zone_CoviMAC::carre_pas_du_maillage () const [inline]
Definition at line 295 of file Zone_CoviMAC.h.
References h_carre.
{
  return h_carre;
}
double Zone_CoviMAC::carre_pas_maille (int i) const [inline]
Definition at line 112 of file Zone_CoviMAC.h.
References h_carre_.
  {
    return h_carre_(i);
  };
Objet_U * Zone_CoviMAC::cree_instance () [static]
Definition at line 83 of file Zone_CoviMAC.cpp.
void Zone_CoviMAC::creer_faces_virtuelles_non_std () [private]
std::array< double, 3 > Zone_CoviMAC::cross (int dima, int dimb, const double * a, const double * b, const double * ma = NULL, const double * mb = NULL) const [inline]
Definition at line 332 of file Zone_CoviMAC.h.
{
  std::array<double, 3> va = {{ 0, 0, 0 }}, vb = {{ 0, 0, 0 }}, res;
  for (int i = 0; i < dima; i++) va[i] = a[i] - (ma ? ma[i] : 0);
  for (int i = 0; i < dimb; i++) vb[i] = b[i] - (mb ? mb[i] : 0);
  for (int i = 0; i < 3; i++) res[i] = va[(i + 1) % 3] * vb[(i + 2) % 3] - va[(i + 2) % 3] * vb[(i + 1) % 3];
  return res;
}
void Zone_CoviMAC::detecter_faces_non_planes () const
Definition at line 524 of file Zone_CoviMAC.cpp.
References Cerr, Domaine::coord_sommets(), Zone::domaine(), dot(), envoyer_all_to_all(), Process::exit(), face_normales_, Zone_VF::face_sommets_, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, M_PI, Process::me(), Zone_VF::nb_faces(), Process::nproc(), Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by discretiser().
{
  const IntTab& f_e = face_voisins(), &f_s = face_sommets_;
  const DoubleTab& xs = zone().domaine().coord_sommets(), &nf = face_normales_;
  const DoubleVect& fs = face_surfaces();
  int i, j, f, s, rk = Process::me(), np = Process::nproc();
  double sin2;
  ArrOfDouble val(np); //sur chaque proc : { cos^2 max, indice de face, indices d'elements }
  IntTab face(np), elem1(np), elem2(np);
// sur chaque proc : on cherche l'angle le plus grand entre un sommet et le plan de sa face
  for (f = 0; f < nb_faces(); f++) for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
      if ((sin2 = std::pow(dot(&xs(s, 0), &nf(f, 0), &xv_(f, 0)) / fs(f), 2) / dot(&xs(s, 0), &xs(s, 0), &xv_(f, 0), &xv_(f, 0))) > val(rk))
        val(rk) = sin2, face(rk) = f, elem1(rk) = f_e(f, 0), elem2(rk) = f_e(f, 1);
  envoyer_all_to_all(val, val), envoyer_all_to_all(face, face), envoyer_all_to_all(elem1, elem1), envoyer_all_to_all(elem2, elem2);
  for (i = j = sin2 = 0; i < Process::nproc(); i++) if (val(i) > sin2) sin2 = val(i), j = i;
  double theta = asin(sqrt(sin2)) * 180 / M_PI;
  Cerr << "Zone_CoviMAC : angle sommet/face max " << theta << " deg (proc " << j << " , face ";
  Cerr << face(j) << " , elems " << elem1(j) << " / " << elem2(j) << " )" << finl;
  if (theta > 1) Cerr << "Zone_CoviMAC : face non plane detectee! Veuillez reparer votre maillage..." << finl, Process::exit();
}
void Zone_CoviMAC::discretiser () [virtual]
Genere les faces
construits les frontieres.
< Detache la structure parallele
< Extremas du domaine et volumes
< Aires des bords
< Nombre elements et sommets
Reimplemented from Zone_VF.
Definition at line 341 of file Zone_CoviMAC.cpp.
References MD_Vector_composite::add_part(), Zone_VF::calculer_diametres_hydrauliques(), Zone_VF::calculer_porosites(), Cerr, Domaine::coord_sommets(), MD_Vector::copy(), Zone_VF::creer_tableau_faces(), dabs(), detecter_faces_non_planes(), IntTab::dimension(), Objet_U::dimension, Zone::domaine(), dot(), DoubleVect::echange_espace_virtuel(), Zone_VF::elem_faces(), est_egal(), Process::exit(), face_normales_, Zone_VF::face_sommets(), Zone_VF::face_sommets_, face_vois(), Zone_VF::face_voisins(), finl, Domaine::le_nom(), Zone_VF::md_vector_faces(), mdv_ch_face, Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Elem_CoviMAC::normale(), Objet_U::que_suis_je(), DoubleTab::resize(), sub_type, swap(), Zone::type_elem(), type_elem_, typer_elem(), Deriv_Elem_CoviMAC_base::valeur(), Deriv_Elem_geom_base::valeur(), Zone_VF::volumes_entrelaces_, Zone_VF::volumes_entrelaces_dir_, Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
{
  Zone& zone_geom=zone();
  typer_elem(zone_geom);
  Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  Zone_VF::discretiser();
// Correction du tableau facevoisins:
// A l'issue de Zone_VF::discretiser(), les elements voisins 0 et 1 d'une
// face sont les memes sur tous les processeurs qui possedent la face.
// Si la face est virtuelle et qu'un des deux elements voisins n'est
// pas connu (il n'est pas dans l'epaisseur du joint), l'element voisin
// vaut -1. Cela peut etre un voisin 0 ou un voisin 1.
// On corrige les faces virtuelles pour que, si un element voisin n'est
// pas connu, alors il est voisin1. Le voisin0 est donc toujours valide.
  {
    IntTab& face_vois = face_voisins();
    const int debut = nb_faces();
    const int fin   = nb_faces_tot();
    for (int i = debut; i < fin; i++)
      {
        if (face_voisins(i, 0) == -1)
          {
            face_vois(i, 0) = face_vois(i, 1);
            face_vois(i, 1) = -1;
          }
      }
  }
// Verification de la coherence entre l'element geometrique et
// l'elemnt de discretisation
  if (sub_type(Segment_CoviMAC,type_elem_.valeur()))
    {
      if (!sub_type(Segment,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  else if (sub_type(Tri_CoviMAC,type_elem_.valeur()))
    {
      if (!sub_type(Triangle,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " <<
               elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Triangle est compatible avec la discretisation CoviMAC en dimension 2" << finl;
          Cerr << " Il faut trianguler le domaine lorsqu'on utilise le mailleur interne" ;
          Cerr << " en utilisant l'instruction: Trianguler nom_dom" << finl;
          exit();
        }
    }
  else if (sub_type(Tetra_CoviMAC,type_elem_.valeur()))
    {
      if (!sub_type(Tetraedre,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " <<
               elem_geom.que_suis_je() << " est incorrect" << finl;
          Cerr << " Seul le type Tetraedre est compatible avec la discretisation CoviMAC en dimension 3" << finl;
          Cerr << " Il faut tetraedriser le domaine lorsqu'on utilise le mailleur interne";
          Cerr << " en utilisant l'instruction: Tetraedriser nom_dom" << finl;
          exit();
        }
    }
  else if (sub_type(Quadri_CoviMAC,type_elem_.valeur()))
    {
      if (!sub_type(Quadrangle_VEF,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  else if (sub_type(Hexa_CoviMAC,type_elem_.valeur()))
    {
      if (!sub_type(Hexaedre_VEF,elem_geom))
        {
          Cerr << " Le type de l'element geometrique " << elem_geom.que_suis_je() << " est incorrect" << finl;
          exit();
        }
    }
  int num_face;
// On remplit le tableau face_normales_;
// Attention : le tableau face_voisins n'est pas exactement un
// tableau distribue. Une face n'a pas ses deux voisins dans le
// meme ordre sur tous les processeurs qui possedent la face.
// Donc la normale a la face peut changer de direction d'un
// processeur a l'autre, y compris pour les faces de joint.
  {
    const int n = nb_faces();
    face_normales_.resize(n, dimension);
// const Domaine & dom = zone().domaine();
// Scatter::creer_tableau_distribue(dom, Joint::FACE, face_normales_);
    creer_tableau_faces(face_normales_);
    const IntTab& face_som = face_sommets();
    IntTab& face_vois = face_voisins();
    const IntTab& elem_face = elem_faces();
    const int n_tot = nb_faces_tot();
    for (num_face = 0; num_face < n_tot; num_face++)
      {
        type_elem_.normale(num_face,
                           face_normales_,
                           face_som, face_vois, elem_face, zone_geom);
      }
    DoubleTab old(face_normales_);
    face_normales_.echange_espace_virtuel();
    for (num_face = 0; num_face < n_tot; num_face++)
      {
        int id=1;
        for (int d=0; d<dimension; d++)
          if (!est_egal(old(num_face,d),face_normales_(num_face,d)))
            {
              id=0;
              if (!est_egal(old(num_face,d),-face_normales_(num_face,d)))
                {
                  Cerr<<"pb in faces_normales" <<finl;
                  exit();
                }
            }
        if (id==0)
          {
// on a change le sens de la normale, on inverse elem1 elem2
            std::swap(face_vois(num_face,0),face_vois(num_face,1));
          }
      }
  }
  /* recalcul de xv pour avoir les vrais CG des faces */
  const DoubleTab& coords = zone().domaine().coord_sommets();
  for (int face = 0; dimension == 3 && face < nb_faces(); face++)
    {
      double xs[3] = { 0, }, S = 0;
      for (int k = 0; k < face_sommets_.dimension(1); k++) if (face_sommets_(face, k) >= 0)
          {
            int s0 = face_sommets_(face, 0), s1 = face_sommets_(face, k),
                s2 = k + 1 < face_sommets_.dimension(1) && face_sommets_(face, k + 1) >= 0 ? face_sommets_(face, k +1) : s0;
            double s = 0;
            for (int r = 0; r < 3; r++) for (int i = 0; i < 2; i++)
                s += (i ? -1 : 1) * face_normales_(face, r) * (coords(s2, (r + 1 +  i) % 3) - coords(s0, (r + 1 +  i) % 3))
                     * (coords(s1, (r + 1 + !i) % 3) - coords(s0, (r + 1 + !i) % 3));
            for (int r = 0; r < 3; r++) xs[r] += s * (coords(s0, r) + coords(s1, r) + coords(s2, r)) / 3;
            S += s;
          }
      if (S == 0 && sub_type(Hexa_CoviMAC,type_elem_.valeur()))
        {
          Cerr << "===============================" << finl;
          Cerr << "Error in your mesh for PolyMAC!" << finl;
          Cerr << "Add this keyword before discretization in your data file to create polyedras:" << finl;
          Cerr << "Polyedriser " << zone().domaine().le_nom() << finl;
          Process::exit();
        }
      for (int r = 0; r < 3; r++) xv_(face, r) = xs[r] / S;
    }
  xv_.echange_espace_virtuel();
  detecter_faces_non_planes();
// MD_vector pour Champ_Face_CoviMAC (faces + dimension * champ_p0)
  MD_Vector_composite mdc_ch_face;
  mdc_ch_face.add_part(md_vector_faces());
  mdc_ch_face.add_part(zone().md_vector_elements(), dimension);
  mdv_ch_face.copy(mdc_ch_face);
// volumes_entrelaces_ et volumes_entrelaces_dir : par projection de l'amont/aval sur la normale a la face
  creer_tableau_faces(volumes_entrelaces_);
  volumes_entrelaces_dir_.resize(0, 2), creer_tableau_faces(volumes_entrelaces_dir_);
  for (int f = 0, i, e; f < nb_faces(); f++)
    for (i = 0; i < 2 && (e = face_voisins_(f, i)) >= 0; volumes_entrelaces_(f) += volumes_entrelaces_dir_(f, i), i++)
      volumes_entrelaces_dir_(f, i) = dabs(dot(&xp_(e, 0), &face_normales_(f, 0), &xv_(f, 0)));
  volumes_entrelaces_.echange_espace_virtuel(), volumes_entrelaces_dir_.echange_espace_virtuel();
  Zone_VF::calculer_porosites();
  Zone_VF::calculer_diametres_hydrauliques();
}
double Zone_CoviMAC::dist_face_elem0 (int num_face, int n0) const [inline]
Definition at line 390 of file Zone_CoviMAC.h.
References dabs(), dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::xp_, and Zone_VF::xv_.
{
  return dabs(dot(&xp_(e, 0), &face_normales_(f, 0), &xv_(f, 0))) / face_surfaces(f);
}
double Zone_CoviMAC::dist_face_elem0_period (int num_face, int n0, double l) const [inline]
Definition at line 400 of file Zone_CoviMAC.h.
References Process::abort().
{
  abort();
  return 0;
}
double Zone_CoviMAC::dist_face_elem1 (int num_face, int n1) const [inline]
Definition at line 395 of file Zone_CoviMAC.h.
References dabs(), dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::xp_, and Zone_VF::xv_.
{
  return dabs(dot(&xp_(e, 0), &face_normales_(f, 0), &xv_(f, 0))) / face_surfaces(f);
}
double Zone_CoviMAC::dist_face_elem1_period (int num_face, int n1, double l) const [inline]
Definition at line 406 of file Zone_CoviMAC.h.
References Process::abort().
{
  abort();
  return 0;
}
double Zone_CoviMAC::dist_norm (int num_face) const [inline]
Definition at line 385 of file Zone_CoviMAC.h.
References dabs(), dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), and Zone_VF::xp_.
{
  return dabs(dot(&xp_(face_voisins(f, 0), 0), &face_normales_(f, 0), &xp_(face_voisins(f, 1), 0))) / face_surfaces(f);
}
double Zone_CoviMAC::dist_norm_bord (int num_face) const [inline]
Definition at line 379 of file Zone_CoviMAC.h.
References dabs(), dot(), face_normales_, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::xp_, and Zone_VF::xv_.
Referenced by dist_norm_bord(), fgrad(), Echange_contact_CoviMAC::fgrad(), and Op_Diff_CoviMAC_base::update_nu_invh().
{
  assert(face_voisins(f, 1) == -1);
  return dabs(dot(&xp_(face_voisins(f, 0), 0), &face_normales_(f, 0), &xv_(f, 0))) / face_surfaces(f);
}
DoubleVect & Zone_CoviMAC::dist_norm_bord (DoubleVect & dist, const Nom & nom_bord) const
Definition at line 645 of file Zone_CoviMAC.cpp.
References dist_norm_bord(), Zone_VF::front_VF(), Frontiere_dis_base::le_nom(), Zone_VF::les_bords_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), DoubleVect::resize(), and vect_impl::size().
{
  for (int n_bord=0; n_bord<les_bords_.size(); n_bord++)
    {
      const Front_VF& fr_vf = front_VF(n_bord);
      if (fr_vf.le_nom() == nom_bord)
        {
          dist.resize(fr_vf.nb_faces());
          int ndeb = fr_vf.num_premiere_face();
          for (int face=ndeb; face<ndeb+fr_vf.nb_faces(); face++)
            dist(face-ndeb) = dist_norm_bord(face);
        }
    }
  return dist;
}
double Zone_CoviMAC::dot (const double * a, const double * b, const double * ma = NULL, const double * mb = NULL) const [inline]
Definition at line 324 of file Zone_CoviMAC.h.
References Objet_U::dimension.
Referenced by detecter_faces_non_planes(), discretiser(), dist_face_elem0(), dist_face_elem1(), dist_norm(), dist_norm_bord(), fgrad(), Echange_contact_CoviMAC::fgrad(), harmonic_points(), Echange_contact_CoviMAC::harmonic_points(), init_equiv(), Echange_contact_CoviMAC::init_fe_dist(), Champ_Face_CoviMAC::init_ve2(), nu_dot(), and Champ_Face_CoviMAC::v_norm().
{
  double res = 0;
  for (int i = 0; i < dimension; i++) res += (a[i] - (ma ? ma[i] : 0)) * (b[i] - (mb ? mb[i] : 0));
  return res;
}
int Zone_CoviMAC::duplique () const [virtual]
Implements Zone_VF.
Definition at line 83 of file Zone_CoviMAC.cpp.
Sortie & Zone_CoviMAC::ecrit (Sortie & os) const [private]
Definition at line 89 of file Zone_CoviMAC.cpp.
References IntVect::ecrit(), DoubleTab::ecrit(), DoubleVect::ecrit(), face_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, printOn(), rang_elem_non_std_, type_elem_, and Zone_VF::volumes_entrelaces_.
{
  Zone_VF::printOn(os);
  os << "____ h_carre "<<finl;
  os << h_carre << finl;
  os << "____ type_elem_ "<<finl;
  os << type_elem_ << finl;
  os << "____ nb_elem_std_ "<<finl;
  os << nb_elem_std_ << finl;
  os << "____ volumes_entrelaces_ "<<finl;
  volumes_entrelaces_.ecrit(os);
  os << "____ face_normales_ "<<finl;
  face_normales_.ecrit(os);
  os << "____ nb_faces_std_ "<<finl;
  os << nb_faces_std_ << finl;
  os << "____ rang_elem_non_std_ "<<finl;
  rang_elem_non_std_.ecrit(os);
  return os;
}
double Zone_CoviMAC::face_normales (int face, int comp) const [inline, virtual]
Implements Zone_VF.
Definition at line 221 of file Zone_CoviMAC.h.
References face_normales_.
Referenced by Champ_Fonc_Face_CoviMAC::affecter_(), Champ_Face_CoviMAC::affecter_(), Masse_CoviMAC_Face::ajouter_blocs(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Echange_contact_CoviMAC::fgrad(), Echange_contact_CoviMAC::harmonic_points(), Champ_Face_CoviMAC::init_ve2(), Op_Diff_CoviMAC_base::update_nu_invh(), Champ_Face_CoviMAC::v_norm(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), and Champ_Face_CoviMAC::valeur_aux_faces().
{
  return face_normales_(face,comp);
}
DoubleTab & Zone_CoviMAC::face_normales () [inline]
Definition at line 228 of file Zone_CoviMAC.h.
References face_normales_.
Referenced by fgrad(), harmonic_points(), and init_equiv().
{
  return face_normales_;
}
const DoubleTab & Zone_CoviMAC::face_normales () const [inline]
Definition at line 235 of file Zone_CoviMAC.h.
References face_normales_.
{
  return face_normales_;
}
void Zone_CoviMAC::fgrad (const Conds_lim & cls, const IntTab & fcl, const DoubleTab * nu, const DoubleTab * invh, const DoubleTab & xh, const DoubleTab & wh, const DoubleTab * whm, const IntTab * pe_ext, int nu_grad, int full_stencil, DoubleTab & phif_w, IntTab & phif_d, IntTab & phif_e, DoubleTab & phif_c, IntTab * phif_pe, DoubleTab * phif_pc) const
Definition at line 837 of file Zone_CoviMAC.cpp.
References IntTab::append_line(), IntTab::dimension(), Objet_U::dimension, DoubleTab::dimension(), dist_norm_bord(), dot(), F77NAME, face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::fbord(), fsten_d, fsten_f, init_stencils(), local_max_abs_vect(), Zone_dis_base::nb_elem_tot(), nu_dot(), ref_cast, DoubleTab::resize(), IntTab::resize(), ArrOfDouble::set_smart_resize(), ArrOfInt::set_smart_resize(), IntVect::size(), sort(), sub_type, valeur(), Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Op_Grad_CoviMAC_Face::mu_f().
{
  const IntTab& f_e = face_voisins();
  const DoubleTab& nf = face_normales();
  const DoubleVect& fs = face_surfaces();
  int i, j, k, l, e, f, e_s, f_s, f_sb, m, n, N = xh.dimension(1), M = whm ? whm->dimension(2) : N, ne_tot = nb_elem_tot(), nw, infoo, d, D = dimension, f_max = phif_w.dimension(0), nnz, hdiag;
  char trans = 'N';
  double i3[3][3] = { { 1, 0, 0 }, { 0, 1, 0}, { 0, 0, 1 }};
  phif_d.set_smart_resize(1), phif_e.set_smart_resize(1), phif_e.resize(0), phif_c.set_smart_resize(1), phif_c.resize(0, N, 2);
  if (phif_pe) phif_d.resize(1, 2), phif_pe->set_smart_resize(1), phif_pe->resize(0, 2), phif_pc->set_smart_resize(1), phif_pc->resize(0, N, M, 2);
  else phif_d.resize(1);
  DoubleTrav base, A, B, interp, phi, W(1), r_int(N, 2), lambda(2);
  base.set_smart_resize(1), A.set_smart_resize(1), B.set_smart_resize(1), interp.set_smart_resize(1), phi.set_smart_resize(1), W.set_smart_resize(1);
  std::vector<std::pair<int, int>> p_e; //stencil aux elements
  init_stencils();
  for (f = 0; f < f_max; (phif_pe ? phif_d.append_line(phif_e.size(), phif_pe->dimension(0)) : phif_d.append_line(phif_e.size())), f++)
    if (fcl(f, 0) >= 0 && sub_type(Echange_contact_CoviMAC, cls[fcl(f, 1)].valeur())) //Echange_contact -> delegation
      {
        ref_cast(Echange_contact_CoviMAC, cls[fcl(f, 1)].valeur()).fgrad(full_stencil, phif_w, phif_d, phif_e, phif_c, *phif_pe, *phif_pc); //remplit toutes les faces de la CL
        phif_d.resize(phif_d.dimension(0) - 1, 2), f = phif_d.dimension(0) - 1; //pour que f et phif_d soient bons a la prochaine iteration de la boucle
      }
    else if (wh(f, 0) >= 0) //faces internes ou de bord "normales" -> il faut etre assez loin du joint pour que tous les ooints harmoniques soient definis
      {
        int ok = 1, n_f = fsten_d(f + 1) - fsten_d(f), nc = n_f + 1, nl = D + 1, nrhs = 1 + (f_e(f, 1) >= 0); //nombre de faces dans le stencil, indice de face de bord
        const int *fa = &fsten_f(fsten_d(f)); //pointeur vers la premiere face du stencil
        for (i = 0; i < n_f; i++) ok &= (wh(fa[i], 0) >= 0);
        if (!ok) continue; //il manque un point harmonique -> on sort
        base.resize(nrhs, D, D), A.resize(nc, nl), B.resize(nrhs, nc), interp.resize(nc, N, nrhs); //systeme Ax = B -> format LAPACK
        for (interp = 0, n = 0; n < N; n++) for (i = 0; i < nrhs; i++) interp(n_f, n, i) = 1; //interpolation de depart : celle au point harmonique
        for (n = 0; n < N; n++)
          {
            /* base : base de "vecteurs tests" amont/aval d'un gradient verifiant nf.nu_am.vec_am = nf.nu_av.vec_av */
            for (i = 0; i < nrhs; i++) lambda(i) = nu_dot(nu, f_e(f, i), n, &nf(f, 0), &nf(f, 0)) / (fs(f) * fs(f));
            for (i = 0; i < nrhs; i++) for (j = 0; j < D; j++) for (d = 0; d < D; d++)
                  base(i, j, d) = i3[j][d] + (i ? -1 : 1) * (nu_dot(nu, f_e(f, f_e(f, 1) >= 0), n, &nf(f, 0), i3[j]) - nu_dot(nu, f_e(f, 0), n, &nf(f, 0), i3[j])) * nf(f, d) / (2 * lambda(i) * fs(f) * fs(f));
            /* seconds membres : au passage, on calcule la resistance interne r = d / lambda */
            for (B = 0, i = 0; i < nrhs; i++)
              {
                e = f_e(f, i), r_int(n, i) = (i ? -1 : 1) * dot(&xv_(f, 0), &nf(f, 0), &xp_(e, 0)) / (fs(f) * (nu_grad ? lambda(i) : 1));
                for (d = 0; d < D; d++) B(i, d) = xp_(e, d) + (i ? -1 : 1) * r_int(n, i) * (nu_grad ? nu_dot(nu, e, n, &nf(f, 0), i3[d]) : nf(f, d)) / fs(f) - xh(f, n, d);
              }
            /* interpolation des points projetes amont / aval */
            if (std::pow(1e6 * local_max_abs_vect(B), D - 1) > fs(f)) //si les pts projetes ne sont pas dessus -> corrections
              {
                /* matrice A (format LAPACK) */
                for (i = 0; i < n_f; i++) for (k = (dot(&xh(fa[i], n, 0), &nf(f, 0), &xh(f, n, 0)) > 0 && nrhs > 1), d = 0; d < nl; d++) //faces du stencil
                    A(i, d) = d < D ? dot(&xh(fa[i], n, 0), &base(k, d, 0), &xh(f, n, 0)) : 1;
                for (d = 0; d < nl; d++) A(n_f, d) = d < D ? 0 : 1; //face elle-meme
                /* resolution */
                nw = -1, F77NAME(dgels)(&trans, &nl, &nc, &nrhs, &A(0, 0), &nl, &B(0, 0), &nc, &W(0), &nw, &infoo);
                W.resize(nw = W(0)), F77NAME(dgels)(&trans, &nl, &nc, &nrhs, &A(0, 0), &nl, &B(0, 0), &nc, &W(0), &nw, &infoo);
                /* correction de interp (avec ecretage) */
                for (i = 0; i < nrhs; i++) for (j = 0; j < nc; j++) interp(j, n, i) += dabs(B(i, j)) > 1e-8 ? B(i, j) : 0;
              }
          }
        /* construction du stencil aux elements */
        for (p_e.clear(), i = 0; i <= n_f; i++) for (f_s = i < n_f ? fa[i] : f, f_sb = fbord(f_s), j = 0; j < 2; j++)
            if ((e_s = f_e(f_s, j)) >= 0) p_e.push_back(std::make_pair(0, e_s)); //element normal
            else if (f_sb >= 0 && pe_ext && (e_s = (*pe_ext)(f_sb, 1)) >= 0) p_e.push_back(std::make_pair((*pe_ext)(f_sb, 0), e_s)); //de l'autre cote d'un Echange_contact
            else if (f_sb >= 0) p_e.push_back(std::make_pair(0, ne_tot + f_s)); //CL non Echange_contact -> dependance en les valeurs aux bords
        std::sort(p_e.begin(), p_e.end()), p_e.erase(std::unique(p_e.begin(), p_e.end()), p_e.end()); //classement + deduplication
        /* passage au flux */
        phi.resize(p_e.size(), N, M, 2), phi = 0;
        for (n = 0; n < N; n++) phif_w(f, n) = nrhs < 2 ? 1 : r_int(n, 0) * wh(f, n) / (r_int(n, 0) * wh(f, n) + r_int(n, 1) * (1 - wh(f, n))); //poids de l'amont
        for (i = 0; i <= n_f; i++) for (f_s = i < n_f ? fa[i] : f, f_sb = fbord(f_s), j = 0; j < 2; j++)
            if ((e_s = f_e(f_s, j) >= 0 ? f_e(f_s, j) : f_sb >= 0 && pe_ext && (*pe_ext)(f_sb, 0) >= 0 ? (*pe_ext)(f_sb, 1) : -1) >= 0) //il existe un element source (interne ou externe)
              {
                k = std::lower_bound(p_e.begin(), p_e.end(), std::make_pair(f_e(f_s, j) >= 0 ? 0 : (*pe_ext)(f_sb, 0), e_s)) - p_e.begin();//position dans le stencil
                if (f_sb < 0 || !pe_ext || (*pe_ext)(f_sb, 0) < 0) for (n = 0; n < N; n++) for (l = 0; l < nrhs; l++) //point harmonique standard -> composantes separees
                      phi(k, n, n, l) += (l ? -1 : 1) / r_int(n, l) * interp(i, n, l) * (j ? 1 - wh(f_s, n) : wh(f_s, n));
                else for (n = 0; n < N; n++) for (m = 0; m < M; m++) for (l = 0; l < nrhs; l++) //pt harmonique a une Echange_contact -> melange des composantes
                        phi(k, n, m, l) += (l ? -1 : 1) / r_int(n, l) * interp(i, n, l) * (*whm)((*pe_ext)(f_sb, 2), n, m, j);
              }
            else for (k = std::lower_bound(p_e.begin(), p_e.end(), std::make_pair((int)0, ne_tot + f_s)) - p_e.begin(), n = 0; n < N; n++) //face de bord -> dependance en la CL
                for (l = 0; l < nrhs; l++) phi(k, n, n, l) += (l ? -1 : 1) / r_int(n, l) * interp(i, n, l)
                                                                * (wh(f_s, n) < 1 ? 1 - wh(f_s, n) : dist_norm_bord(f_s) / (nu_grad ? -nu_dot(nu, f_e(f_s, 0), n, &nf(f_s, 0), &nf(f_s, 0)) / (fs(f_s) * fs(f_s)) : 1));
// amont/aval
        for (i = 0; i < nrhs; i++) for (k = std::lower_bound(p_e.begin(), p_e.end(), std::make_pair((int)0, f_e(f, i))) - p_e.begin(), n = 0; n < N; n++)
            phi(k, n, n, i) += (i ? 1 : -1) / r_int(n, i);
        /* remplissage de phif_e/pe/c/pc */
        for (i = 0; i < (int) p_e.size(); i++)
          {
            for (nnz = 0, hdiag = 0, n = 0; n < N; n++) for (m = 0; m < M; m++) for (l = 0; l < nrhs; l++) if (phi(i, n, m, l) != 0) nnz++, hdiag |= (m != n);
            if (!nnz && !full_stencil) continue; //on peut sauter ce point
            if (p_e[i].first == 0 && !hdiag) //contrib diagonale d'un elem local -> dans phif_e/c
              for (phif_e.append_line(p_e[i].second), k = phif_c.dimension(0), phif_c.resize(k + 1, N, 2), n = 0; n < N; n++)
                for (l = 0; l < 2; l++) phif_c(k, n, l) = phi(i, n, n, l);
            else for (phif_pe->append_line(p_e[i].first, p_e[i].second), k = phif_pc->dimension(0), phif_pc->resize(k + 1, N, M, 2), n = 0; n < N; n++)
                for (m = 0; m < M; m++) for (l = 0; l < 2; l++) (*phif_pc)(k, n, m, l) = phi(i, n, m, l);
          }
      }
}
const Type_info * Zone_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_VF.
Definition at line 83 of file Zone_CoviMAC.cpp.
void Zone_CoviMAC::harmonic_points (const Conds_lim & cls, int is_p, int nu_grad, const DoubleTab * nu, const DoubleTab * invh, DoubleTab & xh, DoubleTab & wh, DoubleTab * whm) const
Definition at line 760 of file Zone_CoviMAC.cpp.
References Process::abort(), Objet_U::dimension, DoubleTab::dimension(), dot(), face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Zone_VF::fbord(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), nu_dot(), Front_VF::num_face(), Zone_VF::premiere_face_int(), ref_cast, vect_impl::size(), sub_type, valeur(), Zone_VF::xp_, and Zone_VF::xv_.
Referenced by Op_Grad_CoviMAC_Face::mu_f().
{
  const IntTab& f_e = face_voisins();
  const DoubleTab& nf = face_normales();
  const DoubleVect& fs = face_surfaces();
  int i, j, e, f, fb, n, N = xh.dimension(1), nf_tot = nb_faces_tot(), d, D = dimension;
  DoubleTrav lambda(2, N), xef(2, D), def(2), lambda_t(2, N, D);
  double i3[3][3] = { { 1, 0, 0 }, { 0, 1, 0}, { 0, 0, 1 }};
  /* faces de bord : on delegue les CLs monolithique a Echange_contact_CoviMAC et on traite les autres */
  wh = -1; //valeur par defaut : a la fin, wh = -1 que les faces au bord des joints
  for (i = 0; i < cls.size(); i++)
    if (sub_type(Echange_contact_CoviMAC, cls[i].valeur())) ref_cast(Echange_contact_CoviMAC, cls[i].valeur()).harmonic_points(xh, wh, *whm);
    else /* vraie face de bord */
      {
        const Cond_lim_base& cl = cls[i].valeur();
        const Front_VF& fvf = ref_cast(Front_VF, cl.frontiere_dis());
        int neu  = sub_type(Neumann, cl), neu_h = sub_type(Neumann_homogene, cl), sym = sub_type(Symetrie, cl),
            dir  = sub_type(Dirichlet, cl), dir_h = sub_type(Dirichlet_homogene, cl),
            echg = sub_type(Echange_impose_base, cl);
        for (j = 0; j < fvf.nb_faces_tot(); j++)
          {
            f = fvf.num_face(j), e = f_e(f, 0), fb = fbord(f); //numero de l'elem en face, de face de bord
// diffusion : partie normale (nf.nu.nf), partie tangente (nu.nf - (nf.nu.nf)nf)
            for (n = 0; n < N; n++) for (lambda(0, n) = nu_dot(nu, e, n, &nf(f, 0), &nf(f, 0)) / (fs(f) * fs(f)), d = 0; d < D; d++)
                lambda_t(0, n, d) = (nu_dot(nu, e, n, i3[d], &nf(f, 0)) - lambda(0, n) * nf(f, d)) / fs(f);
            for (def(0) = dot(&xv_(f, 0), &nf(f, 0), &xp_(e, 0)) / fs(f), d = 0; d < D; d++) //projection elem->face
              xef(0, d) = xp_(e, d) + def(0) * nf(f, d) / fs(f), xef(1, d) = xv_(f, d);
            if (is_p ? (neu || neu_h) : (dir || dir_h || echg)) for (n = 0; n < N; n++) //Dirichlet / Echange_impose_base : pt harmonique avec def(1) -> 0
                {
                  double r = (invh ? (*invh)(fb, n) : 0) + (echg ? 1. / ref_cast(Echange_impose_base, cl).h_imp(j, n) : 0); //resistance thermique totale
// double scal = dot(&xv_(f, 0), &nf(f, 0), &xp_(e, 0)) / (fs(f) * (nu_grad ? lambda(0, n) : 1));
                  for (wh(f, n) = 1 - 1. / (1 + r * lambda(0, n) / def(0)), d = 0; d < D; d++) //poids de l'amont
                    xh(f, n, d) = (def(0) * xef(1, d) + r * (lambda(0, n) * xef(0, d) + def(0) * lambda_t(0, n, d))) / (def(0) + r * lambda(0, n)); //position
// xh(f, n, d) = xp_(e, d) + scal * (nu_grad ? nu_dot(nu, e, n, &nf(f, 0), i3[d]) : nf(f, d)) / fs(f);
                }
            else if (is_p ? (dir || dir_h || sym) : (neu || neu_h || sym)) for (n = 0; n < N; n++) //Neumann : projection sur la face selon nu.nf
                {
                  double scal = dot(&xv_(f, 0), &nf(f, 0), &xp_(e, 0)) / (fs(f) * (nu_grad ? lambda(0, n) : 1));
                  for (wh(f, n) = 1, d = 0; d < D; d++) xh(f, n, d) = xp_(e, d) + scal * (nu_grad ? nu_dot(nu, e, n, &nf(f, 0), i3[d]) : nf(f, d)) / fs(f);
                }
            else abort();
          }
      }
  /* faces internes */
  for (f = premiere_face_int(); f < nf_tot; f++) if (f_e(f, 0) >= 0 && f_e(f, 1) >= 0) /* on doit avoir les deux voisins */
      {
        for (i = 0; i < 2; i++) for (e = f_e(f, i), n = 0; n < N; n++) lambda(i, n) = nu_dot(nu, e, n, &nf(f, 0), &nf(f, 0)) / (fs(f) * fs(f));
        for (i = 0; i < 2; i++) for (e = f_e(f, i), def(i) = (i ? -1 : 1) * dot(&xv_(f, 0), &nf(f, 0), &xp_(e, 0)) / fs(f), d = 0; d < D; d++)
            xef(i, d) = xp_(e, d) + (i ? -1 : 1) * def(i) * nf(f, d) / fs(f);
        for (i = 0; i < 2; i++) for (e = f_e(f, i), n = 0; n < N; n++) for (d = 0; d < D; d++)
              lambda_t(i, n, d) = (nu_dot(nu, e, n, i3[d], &nf(f, 0)) - lambda(i, n) * nf(f, d)) / fs(f);
        for (n = 0; n < N; n++) for (d = 0; d < D; d++) /* position du "harmonic average point "*/
            xh(f, n, d) = (lambda(1, n) * def(0) * xef(1, d) + lambda(0, n) * def(1) * xef(0, d) + def(0) * def(1) * (lambda_t(1, n, d) - lambda_t(0, n, d)))
                          / (lambda(1, n) * def(0) + lambda(0, n) * def(1));
        for (n = 0; n < N; n++) /* poids de l'amont dans la valeur a ce point */
          wh(f, n) = lambda(0, n) * def(1) / (lambda(1, n) * def(0) + lambda(0, n) * def(1));
      }
}
const ArrOfInt & Zone_CoviMAC::ind_faces_virt_non_std () const [inline]
Definition at line 318 of file Zone_CoviMAC.h.
References ind_faces_virt_non_std_.
{
  return ind_faces_virt_non_std_;
}
const Type_info * Zone_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_VF.
Definition at line 83 of file Zone_CoviMAC.cpp.
void Zone_CoviMAC::init_equiv () const
Definition at line 662 of file Zone_CoviMAC.cpp.
References Cerr, Zone_VF::creer_tableau_faces(), dabs(), IntTab::dimension(), Objet_U::dimension, Zone::domaine(), dot(), Zone_VF::elem_faces(), equiv, f1, f2, face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, is_init, Domaine::le_nom(), mp_somme_vect(), Zone_VF::nb_faces_tot(), IntTab::resize(), Zone_VF::xp_, Zone_VF::xv_, and Zone_dis_base::zone().
Referenced by Op_Diff_CoviMAC_Face::completer(), Op_Conv_EF_Stab_CoviMAC_Face::completer(), and Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul().
{
  if (is_init["equiv"]) return;
  const IntTab& e_f = elem_faces(), &f_e = face_voisins();
  const DoubleTab& nf = face_normales();
  const DoubleVect& fs = face_surfaces();//, &vf = volumes_entrelaces();
  int i, j, e1, e2, f, f1, f2, d, D = dimension, ok;
  IntTrav ntot, nequiv;
  creer_tableau_faces(ntot), creer_tableau_faces(nequiv);
  equiv.resize(nb_faces_tot(), 2, e_f.dimension(1));
  Cerr << zone().domaine().le_nom() << " : initialisation de equiv... ";
  for (f = 0, equiv = -1; f < nb_faces_tot(); f++) if ((e1 = f_e(f, 0)) >= 0 && (e2 = f_e(f, 1)) >= 0)
      for (i = 0; i < e_f.dimension(1) && (f1 = e_f(e1, i)) >= 0; i++)
        for (j = 0, ntot(f)++; j < e_f.dimension(1) && (f2 = e_f(e2, j)) >= 0; j++)
          {
            if (dabs(dabs(dot(&nf(f1, 0), &nf(f2, 0)) / (fs(f1) * fs(f2))) - 1) > 1e-6) continue; //normales colineaires?
            for (ok = 1, d = 0; d < D; d++) ok &= dabs((xv_(f1, d) - xp_(e1, d)) - (xv_(f2, d) - xp_(e2, d))) < 1e-12; //xv - xp identiques?
            if (!ok) continue;
            equiv(f, 0, i) = f2, equiv(f, 1, j) = f1, nequiv(f)++; //si oui, on a equivalence
          }
  Cerr << mp_somme_vect(nequiv) * 100. / mp_somme_vect(ntot) << "% de faces equivalentes!" << finl;
  is_init["equiv"] = 1;
}
void Zone_CoviMAC::init_stencils () const
Definition at line 711 of file Zone_CoviMAC.cpp.
References IntTab::append_line(), CRIMP, IntTab::dimension(), Zone::domaine(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), fsten_d, fsten_f, Zone::ind_faces_virt_bord(), is_init, Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Domaine::nb_som_tot(), Zone_VF::premiere_face_int(), IntTab::resize(), ArrOfInt::set_smart_resize(), IntVect::size(), and Zone_dis_base::zone().
Referenced by fgrad().
{
  if (is_init["stencils"]) return;
  const IntTab& f_s = face_sommets(), &f_e = face_voisins(), &e_f = elem_faces(), &e_s = zone().les_elems();
  int i, j, k, e, f, fb, s, ns_tot = zone().domaine().nb_som_tot(), ok;
  fsten_d.set_smart_resize(1), fsten_d.resize(1), fsten_f.set_smart_resize(1);
// is_fb(f) = 1 pour les faces de bord
  IntTrav is_fb(nb_faces_tot());
  for (f = 0; f < premiere_face_int(); f++) is_fb(f) = 1;
  for (f = nb_faces(); f < nb_faces_tot(); f++) is_fb(f) = (zone().ind_faces_virt_bord()(f - nb_faces()) >= 0);
  /* connectivite sommets -> elems / faces de bord */
  std::vector<std::set<int>> som_e(ns_tot), som_f(ns_tot);
  for (e = 0; e < nb_elem_tot(); e++) for (i = 0; i < e_s.dimension(1) && (s = e_s(e, i)) >= 0; i++) som_e[s].insert(e);
  for (f = 0; f < nb_faces_tot(); f++) if (is_fb(f)) for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++) som_f[s].insert(f);
  std::set<int> soms, sf_f; //sommets de la face f, elems connectes a e par soms, sommets / faces connectes par une face commune
  for (f = 0; f < nb_faces_tot(); fsten_d.append_line(fsten_f.size()), f++) if (f_e(f, 0) >= 0 && (is_fb(f) || f_e(f, 1) >= 0))
      {
        soms.clear(), sf_f.clear();
        for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++) soms.insert(s);
        /* connectivite par faces + sommets */
        for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++) //tout ce qui touche un sommet de f et est voisin de l'amont/aval
          for (j = 0; j < e_f.dimension(1) && (fb = e_f(e, j)) >= 0; j++)
            {
              for (k = 0, ok = 0; !ok && k < f_s.dimension(1) && (s = f_s(fb, k)) >= 0; k++) ok |= soms.count(s);
              if (!ok) continue; //pas de sommet en commun avec f
              if (fb != f) sf_f.insert(fb); //face
            }
        /* remplissage */
        for (auto && fa : sf_f) fsten_f.append_line(fa);
      }
  CRIMP(fsten_d), CRIMP(fsten_f);
  is_init["stencils"] = 1;
}
void Zone_CoviMAC::init_ve () const
Definition at line 688 of file Zone_CoviMAC.cpp.
References DoubleTab::append_line(), IntTab::append_line(), Cerr, CRIMP, IntTab::dimension(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, is_init, Domaine::le_nom(), Zone_dis_base::nb_elem_tot(), DoubleTab::resize(), IntTab::resize(), ArrOfDouble::set_smart_resize(), ArrOfInt::set_smart_resize(), vec, ved, vej, Zone_VF::volumes_, Zone_VF::xp(), Zone_VF::xv(), and Zone_dis_base::zone().
Referenced by Champ_Face_CoviMAC::init_ve2(), and Champ_Face_CoviMAC::update_ve().
{
  const IntTab& e_f = elem_faces(), &f_e = face_voisins();
  const DoubleVect& ve = volumes_, &fs = face_surfaces();
  int i, k, e, f;
  if (is_init["ve"]) return;
  Cerr << zone().domaine().le_nom() << " : initialisation de ve... ";
  ved.resize(1), ved.set_smart_resize(1), vej.set_smart_resize(1), vec.resize(0, dimension), vec.set_smart_resize(1);
// formule (1) de Basumatary et al. (2014) https://doi.org/10.1016/j.jcp.2014.04.033 d'apres Perot
  for (e = 0; e < nb_elem_tot(); ved.append_line(vej.dimension(0)), e++)
    for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
      {
        double x[3] = { 0, };
        for (k = 0; k < dimension; k++) x[k] = fs(f) * (xv(f, k) - xp(e, k)) * (e == f_e(f, 0) ? 1 : -1) / ve(e);
        vej.append_line(f), dimension < 3 ? vec.append_line(x[0], x[1]) : vec.append_line(x[0], x[1], x[2]);
      }
  CRIMP(ved), CRIMP(vej), CRIMP(vec);
  is_init["ve"] = 1, Cerr << "OK" << finl;
}
void Zone_CoviMAC::modifier_pour_Cl (const Conds_lim &) [inline, virtual]
Reimplemented from Zone_VF.
Definition at line 104 of file Zone_CoviMAC.h.
{ };
int Zone_CoviMAC::nb_elem_Cl () const [inline]
Definition at line 288 of file Zone_CoviMAC.h.
References Zone_dis_base::nb_elem(), and nb_elem_std_.
{
  return nb_elem() - nb_elem_std_;
}
int Zone_CoviMAC::nb_elem_std () const [inline]
Definition at line 282 of file Zone_CoviMAC.h.
References nb_elem_std_.
{
  return nb_elem_std_;
}
int Zone_CoviMAC::nb_faces_joint () const [inline]
Definition at line 269 of file Zone_CoviMAC.h.
{
  return 0;
// return nb_faces_joint_;    A FAIRE
}
int Zone_CoviMAC::nb_faces_std () const [inline]
Definition at line 276 of file Zone_CoviMAC.h.
References nb_faces_std_.
{
  return nb_faces_std_;
}
double Zone_CoviMAC::nu_dot (const DoubleTab * nu, int e, int n, const double * a, const double * b, const double * ma = NULL, const double * mb = NULL) const [inline]
Definition at line 413 of file Zone_CoviMAC.h.
References Objet_U::dimension, dot(), and DoubleTab::nb_dim().
Referenced by Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), fgrad(), Echange_contact_CoviMAC::fgrad(), harmonic_points(), Echange_contact_CoviMAC::harmonic_points(), and Op_Diff_CoviMAC_base::update_nu_invh().
{
  if (!nu) return dot(a, b, ma, mb);
  int d, db, D = dimension;
  double resu = 0;
  if (nu->nb_dim() == 2) resu += (*nu)(e, n) * dot(a, b, ma, mb); //isotrope
  else if (nu->nb_dim() == 3) for (d = 0; d < D; d++) //anisotrope diagonal
      resu += (*nu)(e, n, d) * (a[d] - (ma ? ma[d] : 0)) * (b[d] - (mb ? mb[d] : 0));
  else for (d = 0; d < D; d++) for (db = 0; db < D; db++)
        resu += (*nu)(e, n, d, db) * (a[d] - (ma ? ma[d] : 0)) * (b[db] - (mb ? mb[db] : 0));
  return resu;
}
int Zone_CoviMAC::oriente_normale (int face_opp, int elem2) const [inline]
Definition at line 301 of file Zone_CoviMAC.h.
References Zone_VF::face_voisins().
{
  if(face_voisins(face_opp,0)==elem2)
    return 1;
  else return -1;
}
Sortie & Zone_CoviMAC::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la zone discretisee sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_VF.
Definition at line 112 of file Zone_CoviMAC.cpp.
References face_normales_, finl, h_carre, nb_elem_std_, nb_faces_std_, rang_elem_non_std_, type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
Referenced by ecrit().
{
  Zone_VF::printOn(os);
  os << h_carre << finl;
  os << type_elem_ << finl;
  os << nb_elem_std_ << finl;
  os << volumes_entrelaces_ << finl;
  os << face_normales_ << finl;
  os << xp_ << finl;
  os << xv_ << finl;
  os << nb_faces_std_ << finl;
  os << rang_elem_non_std_ << finl;
  return os;
}
IntVect & Zone_CoviMAC::rang_elem_non_std () [inline]
Definition at line 256 of file Zone_CoviMAC.h.
References rang_elem_non_std_.
{
  return rang_elem_non_std_;
}
const IntVect & Zone_CoviMAC::rang_elem_non_std () const [inline]
Definition at line 262 of file Zone_CoviMAC.h.
References rang_elem_non_std_.
{
  return rang_elem_non_std_;
}
Entree & Zone_CoviMAC::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit une zone discretisee a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_VF.
Definition at line 131 of file Zone_CoviMAC.cpp.
References face_normales_, h_carre, nb_elem_std_, nb_faces_std_, rang_elem_non_std_, type_elem_, Zone_VF::volumes_entrelaces_, Zone_VF::xp_, and Zone_VF::xv_.
{
  Zone_VF::readOn(is);
  is >> h_carre;
  is >> type_elem_;
  is >> nb_elem_std_ ;
  is >> volumes_entrelaces_ ;
  is >> face_normales_ ;
  is >> xp_;
  is >> xv_;
  is >> nb_faces_std_ ;
  is >> rang_elem_non_std_ ;
  return is;
}
void Zone_CoviMAC::remplir_elem_faces () [inline, private, virtual]
Implements Zone_VF.
Definition at line 205 of file Zone_CoviMAC.h.
{};
void Zone_CoviMAC::reordonner (Faces & les_faces) [virtual]
Methode appelee par Zone_VF::discretiser apres la creation
des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard"
au debut de la liste des faces. Les faces non standard sont celles
dont les volumes de controles sont modifies par les conditions aux
limites.
< renum_items_communs rempli ?
< ancien indice local
Reimplemented from Zone_VF.
Definition at line 153 of file Zone_CoviMAC.cpp.
References Cerr, Domaine::creer_tableau_elements(), IntTab::dimension(), Zone::domaine(), IntVect::echange_espace_virtuel(), Zone_VF::elem_faces_, Joint::FACE, Zone::faces_joint(), finl, Frontiere::fixer_num_premiere_face(), Process::je_suis_maitre(), Faces::les_sommets(), Zone_dis_base::nb_elem(), nb_elem_std_, Frontiere::nb_faces(), Faces::nb_faces(), Zone::nb_faces_frontiere(), nb_faces_std_, ArrOfInt::ordonne_array(), rang_elem_non_std_, Joint_Items::set_items_communs(), Joint::set_joint_item(), liste::size(), IntVect::size(), ArrOfInt::size_array(), IntVect::size_totale(), Faces::voisin(), Faces::voisins(), and Zone_dis_base::zone().
{
  if (Process::je_suis_maitre())
    Cerr << "Zone_CoviMAC::reordonner les_faces " << finl;
// Construction de rang_elem_non_std_ :
// C'est un vecteur indexe par les elements du domaine.
// size() = nb_elem()
// size_tot() = nb_elem_tot()
// Valeurs dans le tableau :
// rang_elem_non_std_[i] = -1 si l'element i est standard,
// sinon
// rang_elem_non_std_[i] = j, ou j est l'indice de l'element dans
// les tableaux indexes par les elements non standards (par exemple
// le tableau Zone_Cl_CoviMAC::type_elem_Cl_).
// Un element est non standard s'il est voisin d'une face frontiere.
  {
    const Domaine& dom = zone().domaine();
    const int nb_elements = nb_elem();
    const int nb_faces_front = zone().nb_faces_frontiere();
    dom.creer_tableau_elements(rang_elem_non_std_);
// rang_elem_non_std_.resize(nb_elements);
// Scatter::creer_tableau_distribue(dom, Joint::ELEMENT, rang_elem_non_std_);
    rang_elem_non_std_ = -1;
    int nb_elems_non_std = 0;
// D'abord on marque les elements non standards avec rang_elem_non_std_[i] = 0
    for (int i_face = 0; i_face < nb_faces_front; i_face++)
      {
        const int elem = les_faces.voisin(i_face, 0);
        if (rang_elem_non_std_[elem] < 0)
          {
            rang_elem_non_std_[elem] = 0;
            nb_elems_non_std++;
          }
      }
    nb_elem_std_ = nb_elements - nb_elems_non_std;
    rang_elem_non_std_.echange_espace_virtuel();
    int count = 0;
    const int size_tot = rang_elem_non_std_.size_totale();
// On remplace le marqueur "0" par l'indice j.
    for (int elem = 0; elem < size_tot; elem++)
      {
        if (rang_elem_non_std_[elem] == 0)
          {
            rang_elem_non_std_[elem] = count;
            count++;
          }
      }
  }
// Construction du tableau de renumerotation des faces. Ce tableau,
// une fois trie dans l'ordre croissant donne l'ordre des faces dans
// la zone_VF. La cle de tri est construite de sorte a pouvoir retrouver
// l'indice de la face a partir de la cle par la formule :
// indice_face = cle % nb_faces
  const int nbfaces = les_faces.nb_faces();
  ArrOfInt sort_key(nbfaces);
  {
    nb_faces_std_ =0;
    const int nb_faces_front = zone().nb_faces_frontiere();
// Attention : face_voisins_ n'est pas encore initialise, il
// faut passer par les_faces.voisins() :
    const IntTab& facevoisins = les_faces.voisins();
// On place en premier les faces de bord:
    int i_face;
    for (i_face = 0; i_face < nbfaces; i_face++)
      {
        int key = -1;
        if (i_face < nb_faces_front)
          {
// Si la face est au bord, elle doit etre placee au debut
// (en fait elle ne doit pas etre renumerotee)
            key = i_face;
          }
        else
          {
            const int elem0 = facevoisins(i_face, 0);
            const int elem1 = facevoisins(i_face, 1);
// Ces faces ont toujours deux voisins.
            assert(elem0 >= 0 && elem1 >= 0);
            if (rang_elem_non_std_[elem0] >= 0 || rang_elem_non_std_[elem1] >= 0)
              {
// Si la face est voisine d'un element non standard, elle
// doit etre classee juste apres les faces de bord:
                key = i_face;
              }
            else
              {
// Face standard : a la fin du tableau
                key = i_face + nbfaces;
                nb_faces_std_++;
              }
          }
        sort_key[i_face] = key;
      }
    sort_key.ordonne_array();
// On transforme a nouveau la cle en numero de face:
    for (i_face = 0; i_face < nbfaces; i_face++)
      {
        const int key = sort_key[i_face] % nbfaces;
        sort_key[i_face] = key;
      }
  }
// On reordonne les faces:
  {
    IntTab& faces_sommets = les_faces.les_sommets();
    IntTab old_tab(faces_sommets);
    const int nb_som_faces = faces_sommets.dimension(1);
    for (int i = 0; i < nbfaces; i++)
      {
        const int old_i = sort_key[i];
        for (int j = 0; j < nb_som_faces; j++)
          faces_sommets(i, j) = old_tab(old_i, j);
      }
  }
  {
    IntTab& faces_voisins = les_faces.voisins();
    IntTab old_tab(faces_voisins);
    for (int i = 0; i < nbfaces; i++)
      {
        const int old_i = sort_key[i];
        faces_voisins(i, 0) = old_tab(old_i, 0);
        faces_voisins(i, 1) = old_tab(old_i, 1);
      }
  }
// Calcul de la table inversee: reverse_index[ancien_numero] = nouveau numero
  ArrOfInt reverse_index(nbfaces);
  {
    for (int i = 0; i < nbfaces; i++)
      {
        const int j = sort_key[i];
        reverse_index[j] = i;
      }
  }
// Renumerotation de elem_faces:
  {
// Nombre d'indices de faces dans le tableau
    const int nb_items = elem_faces_.size();
    ArrOfInt& array = elem_faces_;
    for (int i = 0; i < nb_items; i++)
      {
        const int old = array[i];
        if (old<0)
          array[i] = -1;
        else
          array[i] = reverse_index[old];
      }
  }
// Mise a jour des indices des faces de joint:
  {
    Joints&      joints    = zone().faces_joint();
    const int nbjoints = joints.size();
    for (int i_joint = 0; i_joint < nbjoints; i_joint++)
      {
        Joint&     un_joint         = joints[i_joint];
        ArrOfInt& indices_faces = un_joint.set_joint_item(Joint::FACE).set_items_communs();
        const int nbfaces2    = indices_faces.size_array();
        assert(nbfaces2 == un_joint.nb_faces()); //!< renum_items_communs rempli ?
        for (int i = 0; i < nbfaces2; i++)
          {
            const int old = indices_faces[i]; //!< ancien indice local
            indices_faces[i] = reverse_index[old];
          }
// Les faces de joint ne sont plus consecutives dans le
// tableau: num_premiere_face n'a plus ne sens
        un_joint.fixer_num_premiere_face(-1);
      }
  }
}
Zone_CoviMAC & Zone_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Zone_VF.
Definition at line 83 of file Zone_CoviMAC.cpp.
const Zone_CoviMAC & Zone_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Zone_VF.
Definition at line 83 of file Zone_CoviMAC.cpp.
unsigned Zone_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 83 of file Zone_CoviMAC.cpp.
const Elem_CoviMAC & Zone_CoviMAC::type_elem () const [inline]
Definition at line 214 of file Zone_CoviMAC.h.
References type_elem_.
Referenced by CoviMAC_discretisation::vorticite().
{
  return type_elem_;
}
void Zone_CoviMAC::typer_elem (Zone & zone_geom) [virtual]
Reimplemented from Zone_VF.
Definition at line 326 of file Zone_CoviMAC.cpp.
References Objet_U::que_suis_je(), sub_type, Zone::type_elem(), type_elem_, Elem_CoviMAC::typer(), Zone::typer(), and Deriv_Elem_geom_base::valeur().
Referenced by discretiser().
{
  const Elem_geom_base& type_elem_geom = zone_geom.type_elem().valeur();
  if (sub_type(Rectangle,type_elem_geom))
    {
      zone_geom.typer("Quadrangle");
    }
  else if (sub_type(Hexaedre,type_elem_geom))
    zone_geom.typer("Hexaedre_VEF");
  const Elem_geom_base& elem_geom = zone_geom.type_elem().valeur();
  type_elem_.typer(elem_geom.que_suis_je());
}
DoubleTab & Zone_CoviMAC::volumes_entrelaces_dir () [inline]
Reimplemented from Zone_VF.
Definition at line 242 of file Zone_CoviMAC.h.
References Zone_VF::volumes_entrelaces_dir_.
{
  return volumes_entrelaces_dir_;
}
const DoubleTab & Zone_CoviMAC::volumes_entrelaces_dir () const [inline]
Reimplemented from Zone_VF.
Definition at line 249 of file Zone_CoviMAC.h.
References Zone_VF::volumes_entrelaces_dir_.
{
  return volumes_entrelaces_dir_;
}
Member Data Documentation
IntTab Zone_CoviMAC::equiv [mutable]
Definition at line 146 of file Zone_CoviMAC.h.
Referenced by init_equiv().
DoubleTab Zone_CoviMAC::face_normales_ [private]
normales aux faces
Definition at line 197 of file Zone_CoviMAC.h.
Referenced by detecter_faces_non_planes(), discretiser(), dist_face_elem0(), dist_face_elem1(), dist_norm(), dist_norm_bord(), ecrit(), face_normales(), printOn(), and readOn().
IntTab Zone_CoviMAC::fsten_d [mutable]
Definition at line 155 of file Zone_CoviMAC.h.
Referenced by fgrad(), Echange_contact_CoviMAC::fgrad(), and init_stencils().
IntTab Zone_CoviMAC::fsten_f [mutable]
Definition at line 155 of file Zone_CoviMAC.h.
Referenced by fgrad(), Echange_contact_CoviMAC::fgrad(), and init_stencils().
double Zone_CoviMAC::h_carre [private]
carre du pas du maillage
Definition at line 194 of file Zone_CoviMAC.h.
Referenced by calculer_h_carre(), carre_pas_du_maillage(), ecrit(), printOn(), and readOn().
DoubleVect Zone_CoviMAC::h_carre_ [private]
carre du pas d'une maille
Definition at line 195 of file Zone_CoviMAC.h.
Referenced by calculer_h_carre(), and carre_pas_maille().
ArrOfInt Zone_CoviMAC::ind_faces_virt_non_std_ [private]
contient les indices des faces virtuelles non standard
Definition at line 204 of file Zone_CoviMAC.h.
Referenced by ind_faces_virt_non_std().
const Type_info Zone_CoviMAC::info_obj [static]
Reimplemented from Zone_VF.
Definition at line 98 of file Zone_CoviMAC.h.
std::map<std::string, int> Zone_CoviMAC::is_init [mutable]
Definition at line 143 of file Zone_CoviMAC.h.
Referenced by init_equiv(), init_stencils(), and init_ve().
MD_Vector Zone_CoviMAC::mdv_ch_face
Definition at line 191 of file Zone_CoviMAC.h.
Referenced by discretiser(), and Champ_Face_CoviMAC::fixer_nb_valeurs_nodales().
int Zone_CoviMAC::nb_elem_std_ [private]
nombre d'elements standard
Definition at line 199 of file Zone_CoviMAC.h.
Referenced by ecrit(), nb_elem_Cl(), nb_elem_std(), printOn(), readOn(), and reordonner().
int Zone_CoviMAC::nb_faces_std_ [private]
nombre de faces standard
Definition at line 198 of file Zone_CoviMAC.h.
Referenced by ecrit(), nb_faces_std(), printOn(), readOn(), and reordonner().
IntVect Zone_CoviMAC::rang_elem_non_std_ [private]
rang_elem_non_std_= -1 si l'element est standard rang_elem_non_std_= rang de l'element dans les tableaux relatifs aux elements non standards
Definition at line 200 of file Zone_CoviMAC.h.
Referenced by ecrit(), printOn(), rang_elem_non_std(), readOn(), and reordonner().
Elem_CoviMAC Zone_CoviMAC::type_elem_ [private]
type de l'element de discretisation
Definition at line 196 of file Zone_CoviMAC.h.
Referenced by discretiser(), ecrit(), printOn(), readOn(), type_elem(), and typer_elem().
DoubleTab Zone_CoviMAC::vec [mutable]
Definition at line 151 of file Zone_CoviMAC.h.
Referenced by init_ve(), and Champ_Face_CoviMAC::update_ve().
IntTab Zone_CoviMAC::ved [mutable]
Definition at line 150 of file Zone_CoviMAC.h.
Referenced by init_ve(), and Champ_Face_CoviMAC::update_ve().
IntTab Zone_CoviMAC::vej [mutable]
Definition at line 150 of file Zone_CoviMAC.h.
Referenced by init_ve(), and Champ_Face_CoviMAC::update_ve().
The documentation for this class was generated from the following files:
src/CoviMAC/Zones/Zone_CoviMAC.h
src/CoviMAC/Zones/Zone_CoviMAC.cpp