TRUST: Terme_Puissance_Thermique_PolyMAC_Elem Class Reference
Terme_Puissance_Thermique_PolyMAC_Elem Class Reference
class Terme_Puissance_Thermique_PolyMAC_Elem
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique<br>.SECTION
voir aussi Terme_Puissance_Thermique, Terme_Source_PolyMAC_base
#include <Terme_Puissance_Thermique_PolyMAC_Elem.h>
Public Member Functions
~Terme_Puissance_Thermique_PolyMAC_Elem ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Terme_Puissance_Thermique_PolyMAC_Elem ()
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
void associer_pb (const Probleme_base &)
virtual void mettre_a_jour (double temps)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Puissance_Thermique_PolyMAC_Elem & self_cast (Objet_U &)
static const
Terme_Puissance_Thermique_PolyMAC_Elem & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
class Terme_Puissance_Thermique_PolyMAC_Elem
Cette classe represente un terme source de l'equation de la thermique
du type degagement volumique de puissance thermique<br>.SECTION
voir aussi Terme_Puissance_Thermique, Terme_Source_PolyMAC_base
Definition at line 41 of file Terme_Puissance_Thermique_PolyMAC_Elem.h.
Constructor & Destructor Documentation
Terme_Puissance_Thermique_PolyMAC_Elem::~Terme_Puissance_Thermique_PolyMAC_Elem ()
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
Terme_Puissance_Thermique_PolyMAC_Elem::Terme_Puissance_Thermique_PolyMAC_Elem () [inline]
Definition at line 64 of file Terme_Puissance_Thermique_PolyMAC_Elem.h.
  : Terme_Puissance_Thermique_PolyMAC_base(It_Sou_PolyMAC_Elem(Eval_Puiss_Th_PolyMAC_Elem)())
{
}
Member Function Documentation
void Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 52 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
References Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Iterateur_Source_PolyMAC::evaluateur(), Terme_Source_PolyMAC_base::iter, Terme_Puissance_Thermique::la_puissance, and Terme_Puissance_Thermique::preparer_source().
{
  preparer_source(pb);
  Eval_Puiss_Th_PolyMAC_Elem& eval_puis = (Eval_Puiss_Th_PolyMAC_Elem&) iter.evaluateur();
  eval_puis.associer_champs(la_puissance);
}
void Terme_Puissance_Thermique_PolyMAC_Elem::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis) [virtual]
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 43 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
References Evaluateur_Source_PolyMAC::associer_zones(), Iterateur_Source_PolyMAC::evaluateur(), Terme_Source_PolyMAC_base::iter, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  Terme_Puissance_Thermique_PolyMAC_base::associer_zones(zone_dis,zone_cl_dis);
  Eval_Puiss_Th_PolyMAC_Elem& eval_puis = (Eval_Puiss_Th_PolyMAC_Elem&) iter.evaluateur();
  eval_puis.associer_zones(zone_dis.valeur(),zone_cl_dis.valeur());
}
Objet_U * Terme_Puissance_Thermique_PolyMAC_Elem::cree_instance () [static]
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
int Terme_Puissance_Thermique_PolyMAC_Elem::duplique () const [virtual]
Implements Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
const Type_info * Terme_Puissance_Thermique_PolyMAC_Elem::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
const Type_info * Terme_Puissance_Thermique_PolyMAC_Elem::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
virtual void Terme_Puissance_Thermique_PolyMAC_Elem::mettre_a_jour (double temps) [inline, virtual]
Reimplemented from Terme_Puissance_Thermique.
Definition at line 50 of file Terme_Puissance_Thermique_PolyMAC_Elem.h.
References Terme_Puissance_Thermique::mettre_a_jour().
  {
    Terme_Puissance_Thermique::mettre_a_jour(temps);
  }
Sortie & Terme_Puissance_Thermique_PolyMAC_Elem::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 31 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
{
  return s << que_suis_je() ;
}
Entree & Terme_Puissance_Thermique_PolyMAC_Elem::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 36 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
{
  Terme_Puissance_Thermique_PolyMAC_base::readOn(s);
  return s;
}
Terme_Puissance_Thermique_PolyMAC_Elem & Terme_Puissance_Thermique_PolyMAC_Elem::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
const Terme_Puissance_Thermique_PolyMAC_Elem & Terme_Puissance_Thermique_PolyMAC_Elem::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
unsigned Terme_Puissance_Thermique_PolyMAC_Elem::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 28 of file Terme_Puissance_Thermique_PolyMAC_Elem.cpp.
Member Data Documentation
const Type_info Terme_Puissance_Thermique_PolyMAC_Elem::info_obj [static]
Reimplemented from Terme_Puissance_Thermique_PolyMAC_base.
Definition at line 43 of file Terme_Puissance_Thermique_PolyMAC_Elem.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Terme_Puissance_Thermique_PolyMAC_Elem.h
src/PolyMAC/Sources/Terme_Puissance_Thermique_PolyMAC_Elem.cpp