TRUST: TroisDto2D Class Reference
TroisDto2D Class Reference
Classe TroisDto2D
x->alpha x.
#include <TroisDto2D.h>
Public Member Functions
TroisDto2D ()
~TroisDto2D ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete Extract_2D_from_3D
Structure du jeu de donnee (en dimension 3) :
Extract_2D_from_3D dom3D bord3D dom2D.
void extraire_2D (const Domaine &, Domaine &, const Bord &, const Nom &, int)
double getXa ()
double getYa ()
double getZa ()
double getIx ()
double getIy ()
double getIz ()
double getJx ()
double getJy ()
double getJz ()
double getKx ()
double getKy ()
double getKz ()
int & coupe ()
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static TroisDto2D & self_cast (Objet_U &)
static const TroisDto2D & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int coupe_
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Private Attributes
double xa
double ya
double za
double Ix
double Iy
double Iz
double Jx
double Jy
double Jz
double Kx
double Ky
double Kz
Detailed Description
Classe TroisDto2D
x->alpha x.
Definition at line 33 of file TroisDto2D.h.
Constructor & Destructor Documentation
TroisDto2D()
TroisDto2D::TroisDto2D ()
< Algorithme de coupe utilise par Xprepro
Definition at line 22 of file TroisDto2D.cpp.
{
  coupe_=1; //!< Algorithme de coupe utilise par Xprepro
}
References coupe_.
~TroisDto2D()
TroisDto2D::~TroisDto2D ()
Definition at line 20 of file TroisDto2D.cpp.
Member Function Documentation
coupe()
int & TroisDto2D::coupe () inline
Definition at line 159 of file TroisDto2D.h.
{
  return coupe_;
}
References coupe_.
Referenced by ExtrudeBord::extruder_bord().
cree_instance()
Objet_U * TroisDto2D::cree_instance () static
Definition at line 20 of file TroisDto2D.cpp.
duplique()
int TroisDto2D::duplique () const override virtual
Implements Objet_U.
Reimplemented in TroisDto2Daxi.
Definition at line 20 of file TroisDto2D.cpp.
extraire_2D()
void TroisDto2D::extraire_2D (const Domaine & dom3D, Domaine & dom2D, const Bord & bord3D, const Nom & nom_bord, int test_axi)
Definition at line 140 of file TroisDto2D.cpp.
{
  const DoubleTab& coord_sommets3D=dom3D.coord_sommets();
  DoubleTab& coord_sommets2D=dom2D.les_sommets();
  const Zone& zone3D=dom3D.zone(0);
  const Faces& faces3D=bord3D.faces();
  const IntTab& les_faces3D=faces3D.les_sommets();
  int nb_som3D=coord_sommets3D.dimension(0);
  Cerr << "number of 3D nodes :" << nb_som3D << finl;
  int nb_faces3D=les_faces3D.dimension(0);
  Cerr << "number of 3D faces of " << nom_bord << " :" << nb_faces3D << finl;
  int nb_som_fac3D=les_faces3D.dimension(1);
  Cerr << "number of nodes per faces in 3D :" << nb_som_fac3D << finl;
// Construction de renum_som3D2D
  ArrOfInt renum_som3D2D(nb_som3D);
  for (int i=0; i<nb_som3D ; i++)
    renum_som3D2D[i]=-1;
  int compteur=0;
  for (int i=0; i<nb_faces3D; i++)
    for (int j=0; j<nb_som_fac3D; j++)
      {
        int& tmp=renum_som3D2D[les_faces3D(i,j)];
        if(tmp==-1)
          tmp=compteur++;
      }
  int nb_som2D=compteur;
// Construction de renum_som2D3D
  ArrOfInt renum_som2D3D(nb_som2D);
  for (int i=0; i<nb_som3D ; i++)
    {
      int j;
      if((j=renum_som3D2D[i])!=-1)
        renum_som2D3D[j]=i;
    }
  coord_sommets2D.resize(nb_som2D,2);
  if (coupe_==2) coord_sommets2D.resize(nb_som2D,3);
  Zone tmpz;
  Zone& zone2D=dom2D.add(tmpz);
  Nom nom_zone("surface");
  nom_zone+=dom2D.le_nom();
  zone2D.nommer("surface");
  if(zone3D.type_elem()->que_suis_je()=="Hexaedre")
    if (test_axi)
      zone2D.typer("Rectangle_2D_axi");
    else
      zone2D.typer("Rectangle");
  else if(zone3D.type_elem()->que_suis_je()=="Tetraedre")
    {
      zone2D.typer("Triangle");
    }
  else if(zone3D.type_elem()->que_suis_je()=="Hexaedre_VEF")
    {
      zone2D.typer("Quadrangle");
    }
  if (coupe_!=1)
    {
// Algorithme general
// La frontiere doit etre plane (non verifie), parallele a un axe ou pas
// Attention: les coordonnees du domaine 2D sont dans le nouveau repere
      double xb,yb,zb;
      double xc,yc,zc;
      double ux,uy,uz;
      double norm;
      double scalI,scalJ;
      xa=0.;
      ya=0.;
      za=0.;
      xb=0.;
      yb=0.;
      zb=0.;
      xc=0.;
      yc=0.;
      zc=0;
      ux=0.;
      uy=0.;
      uz=0.;
      norm=0.;
      scalI=0.;
      scalJ=0.;
// on determine un repere orthonorme (A;IJK) sur le bord a extraire
      xa = coord_sommets3D(les_faces3D(0,0),0);
      ya = coord_sommets3D(les_faces3D(0,0),1);
      za = coord_sommets3D(les_faces3D(0,0),2);
      xb = coord_sommets3D(les_faces3D(0,1),0);
      yb = coord_sommets3D(les_faces3D(0,1),1);
      zb = coord_sommets3D(les_faces3D(0,1),2);
      xc = coord_sommets3D(les_faces3D(0,2),0);
      yc = coord_sommets3D(les_faces3D(0,2),1);
      zc = coord_sommets3D(les_faces3D(0,2),2);
// calcul de I = AB/norme(AB)
      Ix=xb-xa;
      Iy=yb-ya;
      Iz=zb-za;
      norm = sqrt(Ix*Ix+Iy*Iy+Iz*Iz);
      Ix/=norm;
      Iy/=norm;
      Iz/=norm;
// calcul de K = AB^AC/norme(AB^AC)
      ux=xc-xa;
      uy=yc-ya;
      uz=zc-za;
      norm = sqrt(ux*ux+uy*uy+uz*uz);
      ux/=norm;
      uy/=norm;
      uz/=norm;
      Kx = Iy*uz-uy*Iz;
      Ky = Iz*ux-Ix*uz;
      Kz = Ix*uy-Iy*ux;
      norm = sqrt(Kx*Kx+Ky*Ky+Kz*Kz);
      Kx/=norm;
      Ky/=norm;
      Kz/=norm;
// calcul de J = K^I
      Jx = Ky*Iz-Iy*Kz;
      Jy = Kz*Ix-Iz*Kx;
      Jz = Kx*Iy-Ky*Ix;
// produit scalaire OA.I et OA.J
      scalI = xa*Ix+ya*Iy+za*Iz;
      scalJ = xa*Jx+ya*Jy+za*Jz;
// on calcule les coordonnees des points du bord dans le nouveau repere 2D (A;I;J)
// pour cela changement de repere du repere 3D vers le repere (A;I;J)
      for(int i=0; i<nb_som2D; i++)
        {
          double x = coord_sommets3D(renum_som2D3D[i],0);
          double y = coord_sommets3D(renum_som2D3D[i],1);
          double z = coord_sommets3D(renum_som2D3D[i],2);
          if (coupe_==0)
            {
              coord_sommets2D(i,0) = -scalI + x*Ix + y*Iy + z*Iz;
              coord_sommets2D(i,1) = -scalJ + x*Jx + y*Jy + z*Jz;
            }
          else
            {
              assert(coupe_==2);
// on ne ramene pas en 2D
              coord_sommets2D(i,0)=x;
              coord_sommets2D(i,1)=y;
              coord_sommets2D(i,2)=z;
            }
// Cout << "coord 1 = " << coord_sommets2D(i,0) << finl;
// Cout << "coord 2 = " << coord_sommets2D(i,1) << finl;
// Cout << "coord 3 = " << -xa*Kx-ya*Ky-za*Kz+x*Kx + y*Ky + z*Kz << finl;
        }
    }
  else
    {
// Algorithme de coupe utilise par Xprepro en VDF
// Attention: limite a une frontiere plane parallele a un axe
// Les coordoonnees du domaine 2D sont conservees
      int test=0;
      double precision=DMAXFLOAT;
      for (test=2; test>-1; test--)
        {
          double x1,x2,x3;
          x1=coord_sommets3D(les_faces3D(0,0),test);
          x2=coord_sommets3D(les_faces3D(0,1),test);
          x3=coord_sommets3D(les_faces3D(0,2),test);
          double tmp=std::fabs(x1-x2);
          precision=(tmp<precision && tmp>0?tmp:precision);
          tmp=std::fabs(x3-x2);
          precision=(tmp<precision && tmp>0?tmp:precision);
          if (est_egal(x1,x2)&&est_egal(x2,x3)) break;
        }
      if (test==-1)
        {
          Cerr << "Error into TroisDto2D.cpp..." << finl;
          Cerr << "May be the " << dom2D.le_nom() << " boundary domain is not plane enough" << finl;
          Cerr << "Try to use: PrecisionGeom " << 100*precision << " in your data file" << finl;
          Cerr << "Or contact TRUST support." << finl;
          exit();
        }
      IntVect dir(2);
      int kk=0;
      for (int jj=0; jj<3; jj++)
        {
          if (test!=jj)
            {
              dir[kk]=jj;
              kk++;
            }
        }
      for(int i=0; i<nb_som2D; i++)
        for(int j=0; j<2; j++)
          coord_sommets2D(i,j)=coord_sommets3D(renum_som2D3D[i],dir[j]);
    }
  zone2D.associer_domaine(dom2D);
  IntTab& les_elems2D=zone2D.les_elems();
  les_elems2D=les_faces3D;
  for (int i=0; i< nb_faces3D; i++)
    for (int j=0; j< nb_som_fac3D; j++)
      {
        les_elems2D(i,j)=renum_som3D2D[les_elems2D(i,j)];
      }
  dimension=2;
  {
// On recupere les bords :
    CONST_LIST_CURSEUR(Bord) curseur(zone3D.faces_bord());
    while(curseur)
      {
        const Frontiere& front=curseur.valeur();
        const Faces& faces3D_front=front.faces();
        if ( (front.le_nom()!=nom_bord))
          {
            Bord tmp;
            Bord& bord2D=zone2D.faces_bord().add(tmp);
            bord2D.nommer(front.le_nom());
            bord2D.associer_zone(zone2D);
            if (test_axi)
              bord2D.typer_faces("QUADRILATERE_2D_AXI");
            else
              bord2D.typer_faces("segment_2D");
// creer les faces de bord 2D ici!
            int compteur2=0;
            const IntTab& faces_sommets=faces3D_front.les_sommets();
            int nb_faces=faces_sommets.dimension(0);
            IntTab& aretes=bord2D.les_sommets_des_faces();
            IntTab& faces_voisins=bord2D.faces().voisins();
            aretes.resize(nb_faces, 2);
// Boucle sur les faces du domaine 2D
            int doublons=0;
            for(int face=0; face < nb_faces; face++)
              {
                int ok=0;
                int tmpbis;
                for(int i=0; i<nb_som_fac3D; i++)
                  {
                    tmpbis=renum_som3D2D[faces_sommets(face,i)];
                    if (tmpbis!=-1)
                      {
                        ok++;
                        if(ok==1)
                          aretes(compteur2,0)=tmpbis;
                        if(ok==2)
{
                            aretes(compteur2,1)=tmpbis;
                            compteur2++;
                          }
                        if(ok==3)
{
// Si 3 sommets de la face appartienne a la frontiere
// il y'a un probleme, on ajoute les 3 aretes et on cherchera
// les doublons qu'il faudra eliminer...
                            doublons=1;
                            aretes(compteur2,0)=aretes(compteur2-1,1);
                            aretes(compteur2,1)=tmpbis;
                            compteur2++;
                            aretes(compteur2,0)=aretes(compteur2-1,1);
                            aretes(compteur2,1)=aretes(compteur2-2,0);
                            compteur2++;
                          }
                      }
                  }
              }
            if (doublons)
              {
// Recherche des doublons (algo en n^2)
                for (int i=0; i<compteur2; i++)
                  {
                    int& S10=aretes(i,0);
                    int& S11=aretes(i,1);
                    for (int j=i+1; j<compteur2; j++)
                      {
                        int& S20=aretes(j,0);
                        int& S21=aretes(j,1);
                        if ( (S10==S20 && S11==S21) || (S10==S21 && S11==S20) )
{
                            S10=-1;
                            S11=-1;
                            S20=-1;
                            S21=-1;
                          }
                      }
                  }
// On supprime les doublons
                for (int i=0; i<compteur2; i++)
                  if (aretes(i,0)==-1)
                    {
                      for (int j=i; j<compteur2-1; j++)
{
                          aretes(j,0)=aretes(j+1,0);
                          aretes(j,1)=aretes(j+1,1);
                        }
                      compteur2--;
                    }
              }
            aretes.resize(compteur2, 2);
            faces_voisins.resize(compteur2,2);
            faces_voisins=-1;
            if (compteur2==0)
              {
                Cerr<<"boundary to eliminate " << front.le_nom()<<finl;
                zone2D.faces_bord().suppr(bord2D);
              }
            else
              {
                Cerr<<"boundary maintained " << front.le_nom()<<finl;
              }
          }
        ++curseur;
      }
  }
  {
// On recupere les raccords :
    CONST_LIST_CURSEUR(Raccord) curseur(zone3D.faces_raccord());;;
    while(curseur)
      {
// while(curseur)
        const Frontiere& front=curseur->valeur();
        const Faces& faces3Dfront=front.faces();
        if ( (front.le_nom()!=nom_bord))
          {
            Raccord tmpbis;
            Raccord& bord2D=zone2D.faces_raccord().add(tmpbis);
            bord2D.typer(curseur->valeur().le_type());
            bord2D->nommer(front.le_nom());
            bord2D->associer_zone(zone2D);
            if (test_axi)
              bord2D->typer_faces("QUADRILATERE_2D_AXI");
            else
              bord2D->typer_faces("segment_2D");
// creer les faces de bord 2D ici!
            int compteur2=0;
            const IntTab& faces_sommets=faces3Dfront.les_sommets();
            int nb_faces=faces_sommets.dimension(0);
            IntTab& aretes=bord2D->les_sommets_des_faces();
            IntTab& faces_voisins=bord2D->faces().voisins();
            aretes.resize(nb_faces, 2);
            for(int face=0; face < nb_faces; face++)
              {
                int ok=0;
                int tmp;
                for(int i=0; i<nb_som_fac3D; i++)
                  {
                    tmp=renum_som3D2D[faces_sommets(face,i)];
                    if (tmp!=-1)
                      {
                        ok++;
                        if(ok==1)
                          aretes(compteur2,0)=tmp;
                        else if(ok==2)
{
                            aretes(compteur2,1)=tmp;
                            compteur2++;
                            i=nb_som_fac3D;
                          }
                      }
                  }
              }
            aretes.resize(compteur2, 2);
            faces_voisins.resize(compteur2,2);
            faces_voisins=-1;
            if (compteur2==0)
              {
                Cerr<<"connector to eliminate " << front.le_nom()<<finl;
                zone2D.faces_raccord().suppr(bord2D);
              }
            else
              {
                Cerr<<"connector maintained " << front.le_nom()<<finl;
              }
          }
        ++curseur;
      }
  }
  if(zone3D.type_elem()->que_suis_je()!="Hexaedre_VEF")
    if (coupe_!=2)
      dom2D.reordonner();
  dimension=3;
}
References List_Bord::add(), List_Raccord::add(), Domaine::add(), Zone::associer_domaine(), Frontiere::associer_zone(), Cerr, compteur, CONST_LIST_CURSEUR, Domaine::coord_sommets(), coupe_, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DMAXFLOAT, est_egal(), Process::exit(), Frontiere::faces(), Zone::faces_bord(), Zone::faces_raccord(), finl, Ix, Iy, Iz, Jx, Jy, Jz, Kx, Ky, Kz, Domaine::le_nom(), Frontiere::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Faces::les_sommets(), Frontiere::les_sommets_des_faces(), Objet_U::nommer(), Frontiere::nommer(), Zone::nommer(), Objet_U::que_suis_je(), Domaine::reordonner(), TRUSTTab< _TYPE_ >::resize(), List_Bord::suppr(), List_Raccord::suppr(), test(), Zone::type_elem(), Deriv_::typer(), Zone::typer(), Frontiere::typer_faces(), Faces::voisins(), xa, ya, za, and Domaine::zone().
Referenced by ExtrudeBord::extruder_bord(), and interpreter_().
get_info()
const Type_info * TroisDto2D::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Reimplemented in TroisDto2Daxi.
Definition at line 20 of file TroisDto2D.cpp.
getIx()
double TroisDto2D::getIx () inline
Renvoi la composante X du premier vecteur de base I du repere local au bord, calcule par la classe.
Definition at line 73 of file TroisDto2D.h.
  {
    return Ix;
  }
References Ix.
Referenced by ExtrudeBord::extruder_bord().
getIy()
double TroisDto2D::getIy () inline
Renvoi la composante Y du premier vecteur de base I du repere local au bord, calcule par la classe.
Definition at line 81 of file TroisDto2D.h.
  {
    return Iy;
  }
References Iy.
Referenced by ExtrudeBord::extruder_bord().
getIz()
double TroisDto2D::getIz () inline
Renvoi la composante Z du premier vecteur de base I du repere local au bord, calcule par la classe.
Definition at line 89 of file TroisDto2D.h.
  {
    return Iz;
  }
References Iz.
Referenced by ExtrudeBord::extruder_bord().
getJx()
double TroisDto2D::getJx () inline
Renvoi la composante X du vecteur de base J du repere local au bord, calcule par la classe.
Definition at line 98 of file TroisDto2D.h.
  {
    return Jx;
  }
References Jx.
Referenced by ExtrudeBord::extruder_bord().
getJy()
double TroisDto2D::getJy () inline
Renvoi la composante Y du vecteur de base J du repere local au bord, calcule par la classe.
Definition at line 106 of file TroisDto2D.h.
  {
    return Jy;
  }
References Jy.
Referenced by ExtrudeBord::extruder_bord().
getJz()
double TroisDto2D::getJz () inline
Renvoi la composante Z du vecteur de base J du repere local au bord, calcule par la classe.
Definition at line 114 of file TroisDto2D.h.
  {
    return Jz;
  }
References Jz.
Referenced by ExtrudeBord::extruder_bord().
getKx()
double TroisDto2D::getKx () inline
Renvoi la composante X du vecteur de base K du repere local au bord, calcule par la classe.
Definition at line 123 of file TroisDto2D.h.
  {
    return Kx;
  }
References Kx.
Referenced by ExtrudeBord::extruder_bord().
getKy()
double TroisDto2D::getKy () inline
Renvoi la composante Y du vecteur de base K du repere local au bord, calcule par la classe.
Definition at line 131 of file TroisDto2D.h.
  {
    return Ky;
  }
References Ky.
Referenced by ExtrudeBord::extruder_bord().
getKz()
double TroisDto2D::getKz () inline
Renvoi la composante Z du vecteur de base K du repere local au bord, calcule par la classe.
Definition at line 139 of file TroisDto2D.h.
  {
    return Kz;
  }
References Kz.
Referenced by ExtrudeBord::extruder_bord().
getXa()
double TroisDto2D::getXa () inline
Renvoi la composante X de l'origine A du repere local au bord, calcule par la classe.
Definition at line 47 of file TroisDto2D.h.
  {
    return xa;
  }
References xa.
Referenced by ExtrudeBord::extruder_bord().
getYa()
double TroisDto2D::getYa () inline
Renvoi la composante Y de l'origine A du repere local au bord, calcule par la classe.
Definition at line 55 of file TroisDto2D.h.
  {
    return ya;
  }
References ya.
Referenced by ExtrudeBord::extruder_bord().
getZa()
double TroisDto2D::getZa () inline
Renvoi la composante Z de l'origine A du repere local au bord, calcule par la classe.
Definition at line 63 of file TroisDto2D.h.
  {
    return za;
  }
References za.
Referenced by ExtrudeBord::extruder_bord().
info()
const Type_info * TroisDto2D::info () static
Definition at line 20 of file TroisDto2D.cpp.
interpreter_()
Entree & TroisDto2D::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Extract_2D_from_3D
Structure du jeu de donnee (en dimension 3) :
Extract_2D_from_3D dom3D bord3D dom2D.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 82 of file TroisDto2D.cpp.
{
  if(Objet_U::dimension==2)
    {
      Cerr << finl;
      Cerr << "You can not use " << que_suis_je() << " on a case already 2D" << finl;
      exit();
    }
  dimension=3;
  int test_axi=0;
  if (que_suis_je()=="Extract_2Daxi_from_3D")
    {
      test_axi=1;
      Cerr<<"We generate a 2D axi domain"<<finl;
    }
  Nom nom_bord, nom_dom2D;
  associer_domaine(is);
  is >> nom_bord >> nom_dom2D;
  Cerr << "Extraction of boundary " << nom_bord
       << " of domain " << domaine().le_nom()
       << " --> " << nom_dom2D << finl;
  {
// Si l'objet nom_dom2D n'existe pas encore, on
// ajoute un nouvel objet a l'interprete bloc courant
    Interprete_bloc& interp = Interprete_bloc::interprete_courant();
    if (interp.objet_global_existant(nom_dom2D))
      {
        if (sub_type(Domaine, interp.objet_global(nom_dom2D)))
          {
            Cerr << "Domain " << nom_dom2D
                 << " already exists, writing to this object." << finl;
          }
        else
          {
            Cerr << "Error : object " << nom_dom2D
                 << " already exists and is not a domain." << finl;
            exit();
          }
      }
    else
      {
        Cerr << "Declaring a new domain with name " << nom_dom2D << finl;
        DerObjU ob;
        ob.typer("Domaine");
        interp.ajouter(nom_dom2D, ob);
      }
  }
  Domaine& dom2D = ref_cast(Domaine, objet(nom_dom2D));
  const Domaine& dom3D = domaine();
  const Zone& zone3D=dom3D.zone(0);
  const Bord& bord3D=zone3D.bord(nom_bord);
  Scatter::uninit_sequential_domain(dom2D);
  extraire_2D(dom3D, dom2D, bord3D,nom_bord, test_axi);
  Scatter::init_sequential_domain(dom2D);
  return is;
}
References Interprete_bloc::ajouter(), Interprete_geometrique_base::associer_domaine(), Zone::bord(), Cerr, Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), extraire_2D(), finl, Scatter::init_sequential_domain(), Interprete_bloc::interprete_courant(), Domaine::le_nom(), Interprete::objet(), Interprete_bloc::objet_global(), Interprete_bloc::objet_global_existant(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_::typer(), Scatter::uninit_sequential_domain(), and Domaine::zone().
printOn()
Sortie & TroisDto2D::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Reimplemented in TroisDto2Daxi.
Definition at line 41 of file TroisDto2D.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & TroisDto2D::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Reimplemented in TroisDto2Daxi.
Definition at line 61 of file TroisDto2D.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const TroisDto2D & TroisDto2D::self_cast (const Objet_U & r) static
Definition at line 20 of file TroisDto2D.cpp.
self_cast() [2/2]
TroisDto2D & TroisDto2D::self_cast (Objet_U & r) static
Definition at line 20 of file TroisDto2D.cpp.
taille_memoire()
unsigned TroisDto2D::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in TroisDto2Daxi.
Definition at line 20 of file TroisDto2D.cpp.
Member Data Documentation
coupe_
int TroisDto2D::coupe_ protected
Definition at line 148 of file TroisDto2D.h.
Referenced by coupe(), extraire_2D(), and TroisDto2D().
info_obj
const Type_info TroisDto2D::info_obj static
Definition at line 35 of file TroisDto2D.h.
Ix
double TroisDto2D::Ix private
Definition at line 152 of file TroisDto2D.h.
Referenced by extraire_2D(), and getIx().
Iy
double TroisDto2D::Iy private
Definition at line 152 of file TroisDto2D.h.
Referenced by extraire_2D(), and getIy().
Iz
double TroisDto2D::Iz private
Definition at line 152 of file TroisDto2D.h.
Referenced by extraire_2D(), and getIz().
Jx
double TroisDto2D::Jx private
Definition at line 153 of file TroisDto2D.h.
Referenced by extraire_2D(), and getJx().
Jy
double TroisDto2D::Jy private
Definition at line 153 of file TroisDto2D.h.
Referenced by extraire_2D(), and getJy().
Jz
double TroisDto2D::Jz private
Definition at line 153 of file TroisDto2D.h.
Referenced by extraire_2D(), and getJz().
Kx
double TroisDto2D::Kx private
Definition at line 154 of file TroisDto2D.h.
Referenced by extraire_2D(), and getKx().
Ky
double TroisDto2D::Ky private
Definition at line 154 of file TroisDto2D.h.
Referenced by extraire_2D(), and getKy().
Kz
double TroisDto2D::Kz private
Definition at line 154 of file TroisDto2D.h.
Referenced by extraire_2D(), and getKz().
xa
double TroisDto2D::xa private
Definition at line 151 of file TroisDto2D.h.
Referenced by extraire_2D(), and getXa().
ya
double TroisDto2D::ya private
Definition at line 151 of file TroisDto2D.h.
Referenced by extraire_2D(), and getYa().
za
double TroisDto2D::za private
Definition at line 151 of file TroisDto2D.h.
Referenced by extraire_2D(), and getZa().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/TroisDto2D.h
src/Kernel/Geometrie/TroisDto2D.cpp