TRUST: Ref_Sous_Zone Class Reference
Ref_Sous_Zone Class Reference
#include <Ref_Sous_Zone.h>
Public Member Functions
~Ref_Sous_Zone ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Sous_Zone ()
Ref_Sous_Zone (const Sous_Zone &)
Ref_Sous_Zone (const Ref_Sous_Zone &)
const Sous_Zone & valeur () const
Sous_Zone & valeur ()
const Sous_Zone * operator-> () const
Sous_Zone * operator-> ()
const Ref_Sous_Zone & operator= (const Sous_Zone &)
const Ref_Sous_Zone & operator= (const Ref_Sous_Zone &)
operator const Sous_Zone & () const
operator Sous_Zone & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Sous_Zone & self_cast (Objet_U &)
static const Ref_Sous_Zone & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Sous_Zone * pointeur_
Detailed Description
Definition at line 33 of file Ref_Sous_Zone.h.
Constructor & Destructor Documentation
Ref_Sous_Zone::~Ref_Sous_Zone ()
Definition at line 25 of file Ref_Sous_Zone.cpp.
Ref_Sous_Zone::Ref_Sous_Zone ()
Definition at line 25 of file Ref_Sous_Zone.cpp.
Ref_Sous_Zone::Ref_Sous_Zone (const Sous_Zone & t)
Definition at line 25 of file Ref_Sous_Zone.cpp.
Ref_Sous_Zone::Ref_Sous_Zone (const Ref_Sous_Zone & t)
Definition at line 25 of file Ref_Sous_Zone.cpp.
Member Function Documentation
Objet_U * Ref_Sous_Zone::cree_instance () [static]
Definition at line 25 of file Ref_Sous_Zone.cpp.
int Ref_Sous_Zone::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Type_info * Ref_Sous_Zone::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Type_info & Ref_Sous_Zone::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Type_info * Ref_Sous_Zone::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
Ref_Sous_Zone::operator const Sous_Zone & () const
Definition at line 25 of file Ref_Sous_Zone.cpp.
Ref_Sous_Zone::operator Sous_Zone & ()
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Sous_Zone * Ref_Sous_Zone::operator-> () const [inline]
Definition at line 33 of file Ref_Sous_Zone.h.
Sous_Zone * Ref_Sous_Zone::operator-> () [inline]
Definition at line 33 of file Ref_Sous_Zone.h.
const Ref_Sous_Zone & Ref_Sous_Zone::operator= (const Ref_Sous_Zone & t)
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Ref_Sous_Zone & Ref_Sous_Zone::operator= (const Sous_Zone & t)
Definition at line 25 of file Ref_Sous_Zone.cpp.
Sortie & Ref_Sous_Zone::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
Entree & Ref_Sous_Zone::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Ref_Sous_Zone & Ref_Sous_Zone::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
Ref_Sous_Zone & Ref_Sous_Zone::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Sous_Zone.cpp.
void Ref_Sous_Zone::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Sous_Zone.cpp.
unsigned Ref_Sous_Zone::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Sous_Zone.cpp.
const Sous_Zone & Ref_Sous_Zone::valeur () const [inline]
Definition at line 33 of file Ref_Sous_Zone.h.
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::contribuer_a_avec(), Sous_zone_VF::discretiser(), Champ_input_P0::getTemplate(), Sous_zone_dis_base::operator()(), Sous_zone_dis_base::operator[](), Champ_input_P0::readOn(), Champ_input_P0::setValue(), and Sous_zone_dis_base::sous_zone().
Sous_Zone & Ref_Sous_Zone::valeur () [inline]
Definition at line 33 of file Ref_Sous_Zone.h.
Member Data Documentation
const Type_info Ref_Sous_Zone::info_obj [static]
Reimplemented from Ref_.
Definition at line 33 of file Ref_Sous_Zone.h.
Sous_Zone* Ref_Sous_Zone::pointeur_ [private]
Definition at line 33 of file Ref_Sous_Zone.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Ref_Sous_Zone.h
src/Kernel/Geometrie/Ref_Sous_Zone.cpp