TRUST: Op_Conv_PolyMAC_iterateur_base Class Reference
Op_Conv_PolyMAC_iterateur_base Class Reference
class Op_Conv_PolyMAC_iterateur_base
Classe de base des operateurs de convection PolyMAC
#include <Op_Conv_PolyMAC_iterateur_base.h>
Public Member Functions
Op_Conv_PolyMAC_iterateur_base ()
~Op_Conv_PolyMAC_iterateur_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Op_Conv_PolyMAC_iterateur_base (const Iterateur_PolyMAC_base &)
constructeur
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &resu) const
ajoute la contribution de la convection au second membre resu
renvoie resu
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const
calcule la contribution de la convection, la range dans resu
renvoie resu
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
on assemble la matrice.
void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
virtual const Champ_base & vitesse () const =0
virtual Champ_base & vitesse ()=0
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
double calculer_dt_stab () const
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &)
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Op_Conv_PolyMAC_iterateur_base & self_cast (Objet_U &)
static const
Op_Conv_PolyMAC_iterateur_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
Iterateur_PolyMAC iter
Detailed Description
class Op_Conv_PolyMAC_iterateur_base
Classe de base des operateurs de convection PolyMAC
Definition at line 47 of file Op_Conv_PolyMAC_iterateur_base.h.
Constructor & Destructor Documentation
Op_Conv_PolyMAC_iterateur_base::Op_Conv_PolyMAC_iterateur_base ()
Definition at line 31 of file Op_Conv_PolyMAC_iterateur_base.cpp.
Op_Conv_PolyMAC_iterateur_base::~Op_Conv_PolyMAC_iterateur_base ()
Definition at line 31 of file Op_Conv_PolyMAC_iterateur_base.cpp.
Op_Conv_PolyMAC_iterateur_base::Op_Conv_PolyMAC_iterateur_base (const Iterateur_PolyMAC_base & iter_base) [inline]
constructeur
Definition at line 80 of file Op_Conv_PolyMAC_iterateur_base.h.
                                                                                                             :
  iter(iter_base)
{}
Member Function Documentation
DoubleTab & Op_Conv_PolyMAC_iterateur_base::ajouter (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
ajoute la contribution de la convection au second membre resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 87 of file Op_Conv_PolyMAC_iterateur_base.h.
References Iterateur_PolyMAC::ajouter(), and iter.
{
  return iter.ajouter(inco, resu);
}
void Op_Conv_PolyMAC_iterateur_base::associer_zone_cl_dis (const Zone_Cl_dis_base & zcl) [virtual]
Reimplemented from Operateur_base.
Definition at line 233 of file Op_Conv_PolyMAC_iterateur_base.cpp.
References Iterateur_PolyMAC_base::associer_zone_cl_dis(), iter, and Deriv_Iterateur_PolyMAC_base::valeur().
{
  iter.valeur().associer_zone_cl_dis(zcl);
}
DoubleTab & Op_Conv_PolyMAC_iterateur_base::calculer (const DoubleTab & inco, DoubleTab & resu) const [inline, virtual]
calcule la contribution de la convection, la range dans resu
renvoie resu
Reimplemented from Operateur_base.
Definition at line 119 of file Op_Conv_PolyMAC_iterateur_base.h.
References Iterateur_PolyMAC::calculer(), and iter.
{
  return iter.calculer(inco, resu);
}
double Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
< (elem2 != -1)
Reimplemented from Operateur_base.
Definition at line 65 of file Op_Conv_PolyMAC_iterateur_base.cpp.
References Zone::creer_tableau_elements(), diviser_par_rho_si_dilatable(), DMINFLOAT, MorEqn::equation(), eval_fluent(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Operateur_Conv_base::fixer_dt_stab_conv(), Cond_lim::frontiere_dis(), iter, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_min(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), O_U_Ptr::non_nul(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, ref_cast_non_const, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Champ_base::valeur(), Champ_Proto::valeurs(), vitesse(), Operateur_Conv_base::vitesse_pour_pas_de_temps_, Zone_VF::volumes(), Zone_dis_base::zone(), Iterateur_PolyMAC::zone(), and Iterateur_PolyMAC::zone_Cl().
{
  const Zone_PolyMAC& zone_PolyMAC = iter.zone();
  const Zone_Cl_PolyMAC& zone_Cl_PolyMAC = iter.zone_Cl();
  const IntTab& face_voisins = zone_PolyMAC.face_voisins();
  const DoubleVect& volumes = zone_PolyMAC.volumes();
  const DoubleVect& face_surfaces = zone_PolyMAC.face_surfaces();
  const DoubleVect& vit_associe = vitesse().valeurs();
  const DoubleVect& vit= (vitesse_pour_pas_de_temps_.non_nul()?vitesse_pour_pas_de_temps_.valeur().valeurs(): vit_associe);
  DoubleTab fluent;
// fluent est initialise a zero par defaut:
  zone_PolyMAC.zone().creer_tableau_elements(fluent);
// Remplissage du tableau fluent
  double psc;
  int num1,num2,face;
  int elem1;
// On traite les bords
  for (int n_bord=0; n_bord<zone_PolyMAC.nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_PolyMAC.les_conditions_limites(n_bord);
      if ( sub_type(Dirichlet_entree_fluide,la_cl.valeur())
           || sub_type(Neumann_sortie_libre,la_cl.valeur())  )
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          num1 = le_bord.num_premiere_face();
          num2 = num1 + le_bord.nb_faces();
          for (face=num1; face<num2; face++)
            {
              psc = vit[face]*face_surfaces(face);
              if ( (elem1 = face_voisins(face,0)) != -1)
                {
                  if (psc < 0)
                    fluent[elem1] -= psc;
                }
              else //!< (elem2 != -1)
                if (psc > 0)
                  fluent[face_voisins(face,1)] += psc;
            }
        }
    }
// Boucle sur les faces internes pour remplir fluent
  int zone_PolyMAC_nb_faces=zone_PolyMAC.nb_faces();
  int premiere_face=zone_PolyMAC.premiere_face_int();
  for (face=premiere_face; face<zone_PolyMAC_nb_faces; face++)
    {
      psc = vit[face]*face_surfaces(face);
      eval_fluent(psc,face_voisins(face,0),face_voisins(face,1),fluent);
    }
// Calcul du pas de temps de stabilite a partir du tableau fluent
  if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
    diviser_par_rho_si_dilatable(fluent,equation().milieu());
  double dt_stab = 1.e30;
  int zone_PolyMAC_nb_elem=zone_PolyMAC.nb_elem();
// dt_stab = min (1 / (|U|/dx + |V|/dy + |W|/dz))
  for (int num_poly=0; num_poly<zone_PolyMAC_nb_elem; num_poly++)
    {
      double dt_elem = volumes(num_poly)/(fluent[num_poly]+DMINFLOAT);
      if (dt_elem<dt_stab)
        dt_stab = dt_elem;
    }
  dt_stab = Process::mp_min(dt_stab);
// astuce pour contourner le type const de la methode
  Op_Conv_PolyMAC_iterateur_base& op =ref_cast_non_const(Op_Conv_PolyMAC_iterateur_base, *this);
  op.fixer_dt_stab_conv(dt_stab);
  return dt_stab;
}
void Op_Conv_PolyMAC_iterateur_base::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const [virtual]
< (elem2 != -1)
Reimplemented from Operateur_base.
Definition at line 141 of file Op_Conv_PolyMAC_iterateur_base.cpp.
References diviser_par_rho_si_dilatable(), MorEqn::equation(), eval_fluent(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), iter, Objet_U::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_dis_base::nb_elem(), Zone::nb_elem_tot(), Zone_VF::nb_faces(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::premiere_face_int(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Champ_Proto::valeurs(), Champ::valeurs(), vitesse(), Zone_VF::volumes(), Zone_dis_base::zone(), Iterateur_PolyMAC::zone(), and Iterateur_PolyMAC::zone_Cl().
{
  if (Motcle(option)=="stabilite")
    {
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      es_valeurs = 1.e30;
      const Zone_PolyMAC& zone_PolyMAC = iter.zone();
      const Zone_Cl_PolyMAC& zone_Cl_PolyMAC = iter.zone_Cl();
      const IntTab& face_voisins = zone_PolyMAC.face_voisins();
      const DoubleVect& volumes = zone_PolyMAC.volumes();
      const DoubleVect& face_surfaces = zone_PolyMAC.face_surfaces();
      const DoubleVect& vit = vitesse().valeurs();
      DoubleTrav fluent(zone_PolyMAC.zone().nb_elem_tot());
// Remplissage du tableau fluent
      fluent = 0;
      double psc;
      int num1,num2,face;
      int elem1;
// On traite les bords
      for (int n_bord=0; n_bord<zone_PolyMAC.nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = zone_Cl_PolyMAC.les_conditions_limites(n_bord);
          if ( sub_type(Dirichlet_entree_fluide,la_cl.valeur())
               || sub_type(Neumann_sortie_libre,la_cl.valeur())  )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              num1 = le_bord.num_premiere_face();
              num2 = num1 + le_bord.nb_faces();
              for (face=num1; face<num2; face++)
                {
                  psc = vit[face]*face_surfaces(face);
                  if ( (elem1 = face_voisins(face,0)) != -1)
                    {
                      if (psc < 0)
                        fluent[elem1] -= psc;
                    }
                  else //!< (elem2 != -1)
                    if (psc > 0)
                      fluent[face_voisins(face,1)] += psc;
                }
            }
        }
// Boucle sur les faces internes pour remplir fluent
      int zone_PolyMAC_nb_faces=zone_PolyMAC.nb_faces();
      for (face=zone_PolyMAC.premiere_face_int(); face<zone_PolyMAC_nb_faces; face++)
        {
          psc = vit[face]*face_surfaces(face);
          eval_fluent(psc,face_voisins(face,0),face_voisins(face,1),fluent);
        }
// fluent.echange_espace_virtuel();
      if (vitesse().le_nom()=="rho_u" && equation().probleme().is_dilatable())
        diviser_par_rho_si_dilatable(fluent,equation().milieu());
      int zone_PolyMAC_nb_elem=zone_PolyMAC.nb_elem();
      for (int num_poly=0; num_poly<zone_PolyMAC_nb_elem; num_poly++)
        {
          es_valeurs(num_poly) = volumes(num_poly)/(fluent[num_poly]+1.e-30);
        }
// double dt_min = mp_min_vect(es_valeurs);
// assert(dt_min==calculer_dt_stab());
    }
  else
    Operateur_Conv_base::calculer_pour_post(espace_stockage,option,comp);
}
void Op_Conv_PolyMAC_iterateur_base::completer (void) [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 228 of file Op_Conv_PolyMAC_iterateur_base.cpp.
References Iterateur_PolyMAC::completer_(), and iter.
{
  Operateur_base::completer();
  iter.completer_();
}
void Op_Conv_PolyMAC_iterateur_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 95 of file Op_Conv_PolyMAC_iterateur_base.h.
References Iterateur_PolyMAC::ajouter_contribution(), and iter.
{
  iter.ajouter_contribution(inco, matrice);
}
void Op_Conv_PolyMAC_iterateur_base::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 110 of file Op_Conv_PolyMAC_iterateur_base.h.
References Iterateur_PolyMAC::contribuer_au_second_membre(), and iter.
{
  iter.contribuer_au_second_membre(resu);
}
void Op_Conv_PolyMAC_iterateur_base::contribuer_bloc_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 101 of file Op_Conv_PolyMAC_iterateur_base.h.
References Iterateur_PolyMAC::ajouter_contribution_vitesse(), and iter.
{
  iter.ajouter_contribution_vitesse(inco, matrice);
}
virtual int Op_Conv_PolyMAC_iterateur_base::duplique () const [pure virtual]
Implements Operateur_Conv_base.
Implemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
const Type_info * Op_Conv_PolyMAC_iterateur_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 31 of file Op_Conv_PolyMAC_iterateur_base.cpp.
Motcle Op_Conv_PolyMAC_iterateur_base::get_localisation_pour_post (const Nom & option) const [virtual]
Reimplemented from Operateur_base.
Definition at line 218 of file Op_Conv_PolyMAC_iterateur_base.cpp.
{
  Motcle loc;
  if (Motcle(option)=="stabilite")
    loc = "elem";
  else
    return Operateur_Conv_base::get_localisation_pour_post(option);
  return loc;
}
int Op_Conv_PolyMAC_iterateur_base::impr (Sortie & os) const [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 238 of file Op_Conv_PolyMAC_iterateur_base.cpp.
References Iterateur_PolyMAC::impr(), and iter.
{
  return iter.impr(os);
}
const Type_info * Op_Conv_PolyMAC_iterateur_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 31 of file Op_Conv_PolyMAC_iterateur_base.cpp.
Sortie & Op_Conv_PolyMAC_iterateur_base::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 36 of file Op_Conv_PolyMAC_iterateur_base.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Conv_PolyMAC_iterateur_base::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 44 of file Op_Conv_PolyMAC_iterateur_base.cpp.
{
  return s ;
}
const Op_Conv_PolyMAC_iterateur_base & Op_Conv_PolyMAC_iterateur_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 31 of file Op_Conv_PolyMAC_iterateur_base.cpp.
Op_Conv_PolyMAC_iterateur_base & Op_Conv_PolyMAC_iterateur_base::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 31 of file Op_Conv_PolyMAC_iterateur_base.cpp.
virtual Champ_base& Op_Conv_PolyMAC_iterateur_base::vitesse () [pure virtual]
Implemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
virtual const Champ_base& Op_Conv_PolyMAC_iterateur_base::vitesse () const [pure virtual]
Implemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Referenced by calculer_dt_stab(), and calculer_pour_post().
Member Data Documentation
const Type_info Op_Conv_PolyMAC_iterateur_base::info_obj [static]
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Elem, and Op_Conv_Centre_PolyMAC_Elem.
Definition at line 50 of file Op_Conv_PolyMAC_iterateur_base.h.
Iterateur_PolyMAC Op_Conv_PolyMAC_iterateur_base::iter [protected]
Definition at line 70 of file Op_Conv_PolyMAC_iterateur_base.h.
Referenced by ajouter(), Op_Conv_Centre_PolyMAC_Elem::associer(), Op_Conv_Amont_PolyMAC_Elem::associer(), Op_Conv_Centre_PolyMAC_Elem::associer_vitesse(), Op_Conv_Amont_PolyMAC_Elem::associer_vitesse(), associer_zone_cl_dis(), calculer(), calculer_dt_stab(), calculer_pour_post(), completer(), contribuer_a_avec(), contribuer_au_second_membre(), contribuer_bloc_vitesse(), Op_Conv_Centre_PolyMAC_Elem::dimensionner(), Op_Conv_Amont_PolyMAC_Elem::dimensionner(), Op_Conv_Centre_PolyMAC_Elem::dimensionner_bloc_vitesse(), Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse(), impr(), Op_Conv_Centre_PolyMAC_Elem::modifier_pour_Cl(), Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl(), Op_Conv_Centre_PolyMAC_Elem::vitesse(), and Op_Conv_Amont_PolyMAC_Elem::vitesse().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Conv_iterateur/Op_Conv_PolyMAC_iterateur_base.h
src/PolyMAC/Operateurs/Conv_iterateur/Op_Conv_PolyMAC_iterateur_base.cpp