TRUST: Ref_Champ_Uniforme Class Reference
Ref_Champ_Uniforme Class Reference
#include <Ref_Champ_Uniforme.h>
Public Member Functions
~Ref_Champ_Uniforme ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Champ_Uniforme ()
Ref_Champ_Uniforme (const Champ_Uniforme &)
Ref_Champ_Uniforme (const Ref_Champ_Uniforme &)
const Champ_Uniforme & valeur () const
Champ_Uniforme & valeur ()
const Champ_Uniforme * operator-> () const
Champ_Uniforme * operator-> ()
const Ref_Champ_Uniforme & operator= (const Champ_Uniforme &)
const Ref_Champ_Uniforme & operator= (const Ref_Champ_Uniforme &)
operator const Champ_Uniforme & () const
operator Champ_Uniforme & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Champ_Uniforme & self_cast (Objet_U &)
static const Ref_Champ_Uniforme & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Champ_Uniforme * pointeur_
Detailed Description
Definition at line 28 of file Ref_Champ_Uniforme.h.
Constructor & Destructor Documentation
Ref_Champ_Uniforme::~Ref_Champ_Uniforme ()
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Ref_Champ_Uniforme::Ref_Champ_Uniforme ()
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Ref_Champ_Uniforme::Ref_Champ_Uniforme (const Champ_Uniforme & t)
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Ref_Champ_Uniforme::Ref_Champ_Uniforme (const Ref_Champ_Uniforme & t)
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Member Function Documentation
Objet_U * Ref_Champ_Uniforme::cree_instance () [static]
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
int Ref_Champ_Uniforme::duplique () const [virtual]
Implements Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Type_info * Ref_Champ_Uniforme::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Type_info & Ref_Champ_Uniforme::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Type_info * Ref_Champ_Uniforme::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Ref_Champ_Uniforme::operator Champ_Uniforme & ()
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Ref_Champ_Uniforme::operator const Champ_Uniforme & () const
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Champ_Uniforme * Ref_Champ_Uniforme::operator-> () const [inline]
Definition at line 28 of file Ref_Champ_Uniforme.h.
Champ_Uniforme * Ref_Champ_Uniforme::operator-> () [inline]
Definition at line 28 of file Ref_Champ_Uniforme.h.
const Ref_Champ_Uniforme & Ref_Champ_Uniforme::operator= (const Ref_Champ_Uniforme & t)
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Ref_Champ_Uniforme & Ref_Champ_Uniforme::operator= (const Champ_Uniforme & t)
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Sortie & Ref_Champ_Uniforme::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Entree & Ref_Champ_Uniforme::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Ref_Champ_Uniforme & Ref_Champ_Uniforme::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
Ref_Champ_Uniforme & Ref_Champ_Uniforme::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
void Ref_Champ_Uniforme::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
unsigned Ref_Champ_Uniforme::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Ref_Champ_Uniforme.cpp.
const Champ_Uniforme & Ref_Champ_Uniforme::valeur () const [inline]
Definition at line 28 of file Ref_Champ_Uniforme.h.
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_VDF_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter_bord(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution_bord(), Eval_Diff_VDF_const::associer(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::diffusivite(), Eval_Diff_VDF_const::get_diffusivite(), and Eval_Diff_VDF_const::mettre_a_jour().
Champ_Uniforme & Ref_Champ_Uniforme::valeur () [inline]
Definition at line 28 of file Ref_Champ_Uniforme.h.
Member Data Documentation
const Type_info Ref_Champ_Uniforme::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Champ_Uniforme.h.
Champ_Uniforme* Ref_Champ_Uniforme::pointeur_ [private]
Definition at line 28 of file Ref_Champ_Uniforme.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Ref_Champ_Uniforme.h
src/Kernel/Champs/Ref_Champ_Uniforme.cpp