TRUST: Op_Dift_VEF_P1NCP1B_Face Class Reference
Op_Dift_VEF_P1NCP1B_Face Class Reference
class Op_Dift_VEF_P1NCP1B_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
#include <Op_Dift_VEF_P1NCP1B_Face.h>
Public Member Functions
Op_Dift_VEF_P1NCP1B_Face ()
~Op_Dift_VEF_P1NCP1B_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_diffusivite (const Champ_base &) override
const Champ_base & diffusivite () const override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void verifier () const
void contribue_au_second_membre () const
void ajouter_contribution () const
double calculer_dt_stab () const override
Calcul dt_stab.
void remplir_nu (DoubleTab &) const override
Public Member Functions inherited from Op_Dift_VEF_base
Op_Dift_VEF_base ()
~Op_Dift_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void calculer_borne_locale (DoubleVect &, double, double) const override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
Public Member Functions inherited from Op_Diff_VEF_base
Op_Diff_VEF_base ()
~Op_Diff_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
double viscA (int face_i, int face_j, int num_elem, double diffu) const
double viscA (int face_i, int face_j, int num_elem, DoubleTab &diffu) const
double viscA (int face_i, int face_j, int num_elem, ArrOfDouble &diffu_ci_cj_elem) const
double calculer_dt_stab () const override
Calcul dt_stab.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void remplir_nu (DoubleTab &) const
int phi_psi_diffuse (const Equation_base &eq) const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_VEF_Face
Op_VEF_Face ()
void dimensionner (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VEF &, const Zone_Cl_VEF &, Matrice_Morse &, DoubleTab &) const
int impr (Sortie &, const Operateur_base &) const
void modifier_flux (const Operateur_base &) const
void modifier_matrice_pour_periodique_avant_contribuer (Matrice_Morse &matrice, const Equation_base &) const
divise les coefficients sur les ligne des faces periodiques par 2 en prevision
de l'application modifier_matrice_pour_periodique_apres_contribuer qui va sommer les 2 lignes des faces periodiques associees
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Somme les 2 lignes des faces periodiques associees
permet de calculer dans le code sans se poser de question pour retrouver la face_associee
on ne parcourt que la moitiee des faces periodiques dans contribuer_a_avec (en general).
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Dift_VEF_P1NCP1B_Face & self_cast (Objet_U &)
static const Op_Dift_VEF_P1NCP1B_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VEF_base
static const Type_info * info ()
static Op_Dift_VEF_base & self_cast (Objet_U &)
static const Op_Dift_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VEF_base
static const Type_info * info ()
static Op_Diff_VEF_base & self_cast (Objet_U &)
static const Op_Diff_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & calculer_gradient_elem (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer_gradient_som (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer_divergence_elem (double, const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & calculer_divergence_som (double, const DoubleTab &, const DoubleTab &, DoubleTab &) const
DoubleTab & corriger_div_pour_Cl (DoubleTab &) const
Protected Member Functions inherited from Op_Dift_VEF_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Champ_base diffusivite_
Ref_Mod_turb_hyd_base le_modele_turbulence
Ref_Zone_VEF_PreP1b la_zone_vef
Ref_Zone_Cl_VEFP1B la_zcl_vef
SolveurSys solveur
int trans
double lambda
int filtre
Matrice_Morse_Sym masse
DoubleTab savgrad
Protected Attributes inherited from Op_Dift_VEF_base
Ref_Mod_turb_hyd_base le_modele_turbulence
A deplacer dans Op_Diff_turb ?
DoubleTab tau_tan_
Protected Attributes inherited from Op_Diff_VEF_base
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Ref_Champ_Inc_base inconnue_
DoubleTab nu_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
class Op_Dift_VEF_P1NCP1B_Face
Cette classe represente l'operateur de diffusion
La discretisation est VEF
Le champ diffuse est scalaire
Le champ de diffusivite est uniforme
Definition at line 38 of file Op_Dift_VEF_P1NCP1B_Face.h.
Constructor & Destructor Documentation
Op_Dift_VEF_P1NCP1B_Face()
Op_Dift_VEF_P1NCP1B_Face::Op_Dift_VEF_P1NCP1B_Face ()
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
~Op_Dift_VEF_P1NCP1B_Face()
Op_Dift_VEF_P1NCP1B_Face::~Op_Dift_VEF_P1NCP1B_Face ()
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 529 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
// const Zone_Cl_VEFP1B& zone_Cl_VEF = la_zcl_vef.valeur();
  const Zone_VEF_PreP1b& zone_VEF = la_zone_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  int nb_elem_tot=zone.nb_elem_tot();
  int nb_som_tot=dom.nb_som_tot();
  const DoubleTab& nu_turb=diffusivite_turbulente()->valeurs();
  double nu=(diffusivite_.valeur())(0,0);
  DoubleTab gradient(nb_elem_tot+nb_som_tot, dimension, dimension);
  gradient = 0.;
  calculer_gradient_elem(inconnue, gradient);
  calculer_gradient_som(inconnue, gradient);
  calculer_divergence_elem(nu, nu_turb, gradient, resu);
  calculer_divergence_som(nu, nu_turb, gradient, resu);
  corriger_div_pour_Cl(resu);
  resu.echange_espace_virtuel();
  modifier_flux(*this);
  return resu;
}
References calculer_divergence_elem(), calculer_divergence_som(), calculer_gradient_elem(), calculer_gradient_som(), corriger_div_pour_Cl(), diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), la_zone_vef, Op_VEF_Face::modifier_flux(), Zone::nb_elem_tot(), Domaine::nb_som_tot(), Ref_Champ_base::valeur(), Ref_Zone_VEF_PreP1b::valeur(), Champ_Fonc::valeurs(), and Zone_dis_base::zone().
Referenced by calculer().
ajouter_contribution()
void Op_Dift_VEF_P1NCP1B_Face::ajouter_contribution () const
Definition at line 567 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  return;
}
associer()
void Op_Dift_VEF_P1NCP1B_Face::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) override virtual
Implements Operateur_base.
Definition at line 44 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zvef = ref_cast(Zone_VEF_PreP1b,zone_dis.valeur());
  const Zone_Cl_VEFP1B& zclvef = ref_cast(Zone_Cl_VEFP1B,zone_cl_dis.valeur());
  const Champ_P1NC& inco = ref_cast(Champ_P1NC,ch_transporte.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
  inconnue_ = inco;
  solveur.typer("Solv_GCP");
  Precond p;
  p.typer("SSOR");
  ref_cast(Solv_GCP,solveur.valeur()).set_precond(p);
  solveur.nommer("diffusion_solver");
}
References Op_Diff_VEF_base::inconnue_, la_zcl_vef, la_zone_vef, SolveurSys::nommer(), ref_cast, solveur, Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), and Deriv_SolveurSys_base::valeur().
associer_diffusivite()
void Op_Dift_VEF_P1NCP1B_Face::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
Definition at line 62 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  diffusivite_ = ref_cast(Champ_Uniforme, diffu);
}
References diffusivite_, and ref_cast.
associer_modele_turbulence()
void Op_Dift_VEF_P1NCP1B_Face::associer_modele_turbulence (const Mod_turb_hyd_base &)
calculer()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
Definition at line 554 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  resu = 0;
  return ajouter(inconnue,resu);
}
References ajouter().
calculer_divergence_elem()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem (double nu, const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & div) const protected
Definition at line 422 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int elem,indice,face,compi, compj;
  ArrOfDouble sigma(dimension);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      double nu_tot=nu+nu_turb(elem);
      for(indice=0; indice<nfe; indice++)
        {
          face = elem_faces(elem,indice);
          double signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(compi=0; compi<dimension; compi++)
            for(compj=0; compj<dimension; compj++)
              div(face, compi)-=nu_tot*grad(elem, compi, compj)
                                *signe*face_normales(face,compj);
        }
    }
// Cerr << "AP elem div =" << div << finl;
  return div;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), la_zone_vef, Zone::nb_elem_tot(), Zone::nb_faces_elem(), ref_cast, Ref_Zone_VEF_PreP1b::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_divergence_som()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som (double nu, const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & div) const protected
Definition at line 456 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int nps=zone_VEF.numero_premier_sommet();
  int elem,indice,indice2,face,compi,compj,som;
  ArrOfDouble sigma(dimension);
  static double coeff_som=1./(dimension)/(dimension+1);
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      double nu_tot=nu+nu_turb(elem);
      for(indice=0; indice<nfe; indice++)
        {
          som = nps+dom.get_renum_som_perio(som_elem(elem,indice));
          face = elem_faces(elem,indice);
          double signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(int comp=0; comp<dimension; comp++)
            {
              sigma[comp]=signe*face_normales(face,comp);
            }
          for(indice2=0; indice2<nfe; indice2++)
            for(compi=0; compi<dimension; compi++)
              for(compj=0; compj<dimension; compj++)
                div(elem_faces(elem,indice2),compi)-=coeff_som*nu_tot*
                                                     grad(som,compi,compj)*sigma[compj];
        }
    }
// Cerr << "div AV CL : " << div << finl;
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  int nb_bords =les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      {
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int num1 = le_bord.num_premiere_face();
        int num2 = num1 + le_bord.nb_faces();
        if(sub_type(Neumann_sortie_libre,la_cl.valeur()))
          for (int face2=num1; face2<num2; face2++)
            {
              double nu_tot=nu+nu_turb(face_voisins(face2,0));
              for(indice=0; indice<(nfe-1); indice++)
                {
                  som=nps+dom.get_renum_som_perio(face_sommets(face2,indice));
                  for (compi=0; compi<dimension; compi++)
                    for (compj=0; compj<dimension; compj++)
                      div(face2,compi)-= nu_tot/dimension*
                                         face_normales(face2,compj)*grad(som,compi,compj);
                }
            }
      }
    }
// Cerr << "div AP CL : " << div << finl;
  return div;
}
References Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), la_zcl_vef, la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Front_VF::num_premiere_face(), Zone_VEF_PreP1b::numero_premier_sommet(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEFP1B::valeur(), Ref_Zone_VEF_PreP1b::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_dt_stab()
double Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 68 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
// Calcul de dt_stab
// La diffusivite est constante par elements donc
// il faut calculer dt_diff pour chaque element et
// dt_stab=Min(dt_diff (K) = h(K)*h(K)/(2*dimension*diffu2_(K)))
// ou diffu2_ est la somme des 2 diffusivite laminaire et turbulente
  int num_face;
  double vol,surf;
  double surf_max;
  double dt_stab=1.e30;
  double coef;
  const Zone_VEF_PreP1b& la_zone_VEF = la_zone_vef.valeur();
  const DoubleVect& volumes = la_zone_VEF.volumes();
  const IntTab& elem_faces = la_zone_VEF.elem_faces();
  const DoubleTab& face_normales = la_zone_VEF.face_normales();
  const Zone& la_zone= la_zone_VEF.zone();
// const int nb_elem = la_zone.nb_elem_tot();
// const DoubleTab& xp=la_zone_VEF.xp();
  int nb_faces_elem = la_zone.nb_faces_elem();
  double diffu = (diffusivite_.valeur())(0,0);
  const DoubleVect& diffu_turb=diffusivite_turbulente()->valeurs();
  double diffu2_;
// diffu_turb=1.;
// for(int j=0;j<nb_elem;j++)
// diffu_turb[j]=1.-0.9*xp(j,1);
  int la_zone_nb_elem=la_zone.nb_elem();
  for (int num_elem=0; num_elem<la_zone_nb_elem; num_elem++)
    {
      surf_max = 1.e-30;
      for (int i=0; i<nb_faces_elem; i++)
        {
          num_face = elem_faces(num_elem,i);
          surf = face_normales(num_face,0)*face_normales(num_face,0);
          for (int j=1; j<dimension; j++)
            surf += face_normales(num_face,j)*face_normales(num_face,j);
          surf_max = (surf > surf_max)? surf : surf_max;
        }
      vol = volumes(num_elem);
      vol *=vol/surf_max;
      diffu2_ = diffu + diffu_turb[num_elem];
      coef=vol/(2.*dimension*(diffu2_+DMINFLOAT));
      dt_stab = (coef < dt_stab )? coef : dt_stab;
    }
  return dt_stab;
}
References diffusivite_, Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, DMINFLOAT, Zone_VF::elem_faces(), Zone_VEF::face_normales(), la_zone_vef, Zone::nb_elem(), Zone::nb_faces_elem(), Ref_Champ_base::valeur(), Ref_Zone_VEF_PreP1b::valeur(), Champ_Fonc::valeurs(), Zone_VF::volumes(), and Zone_dis_base::zone().
calculer_gradient_elem()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem (const DoubleTab & vit, DoubleTab & grad) const protected
Definition at line 117 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             (la_zone_vef.valeur()));
  const Zone& zone = zone_VEF.zone();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int elem,indice,face,compi, compj;
  double signe;
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      for(indice=0; indice<nfe; indice++)
        {
          face = elem_faces(elem,indice);
          signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(compi=0; compi<dimension; compi++)
            for(compj=0; compj<dimension; compj++)
              grad(elem,compi,compj)+=signe*vit(face, compi)*
                                      face_normales(face,compj);
        }
    }
  return grad;
}
References Objet_U::dimension, Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_voisins(), la_zone_vef, Zone::nb_elem_tot(), Zone::nb_faces_elem(), ref_cast, Ref_Zone_VEF_PreP1b::valeur(), and Zone_dis_base::zone().
Referenced by ajouter().
calculer_gradient_som()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som (const DoubleTab & vit, DoubleTab & grad) const protected
Definition at line 150 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             (la_zone_vef.valeur()));
  const Zone& zone = zone_VEF.zone();
  const Domaine& dom=zone.domaine();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const IntTab& som_elem=zone.les_elems();
  const IntTab& elem_faces=zone_VEF.elem_faces();
  const IntTab& face_voisins=zone_VEF.face_voisins();
  double mijK, miiK, miK=1./(dimension+1)/(dimension+1);
  int nfe=zone.nb_faces_elem();
  int nb_elem_tot=zone.nb_elem_tot();
  int nps=zone_VEF.numero_premier_sommet();
  int nb_som=grad.dimension(0)-nb_elem_tot;
  int nb_som_elem = zone.nb_som_elem();
  const IntTab& elem_som = zone.les_elems();
  DoubleTab secmem(nb_som, dimension, dimension);
  if(Objet_U::dimension==2)
    {
      mijK=1./12.;
      miiK= 1./6.;
    }
  else
    {
      mijK=1./18.;
      miiK= 1./12.;
    }
  if ( masse.nb_lignes() <2 )
    {
      Cerr<<"On remplit la matrice de masse"<<finl;
      (ref_cast_non_const(DoubleTab,savgrad)).resize(nb_som,dimension,dimension);
      Matrice_Morse_Sym& mat=ref_cast_non_const(Matrice_Morse_Sym, masse);
      int rang;
      int nnz=0;
      IntLists voisins(nb_som);
      DoubleLists coeffs(nb_som);
      DoubleVect diag(nb_som);
      int elem;
      for (elem=0; elem<nb_elem_tot; elem++)
        {
          double vol=zone_VEF.volumes(elem);
          double coeff_ij=mijK*vol-miK*vol;
          double coeff_ii=miiK*vol-miK*vol;
          for (int isom=0; isom<nb_som_elem; isom++)
            {
              int som=elem_som(elem,isom);
              int ii=dom.get_renum_som_perio(som);
              diag[ii]+=coeff_ii;
              for (int jsom=isom+1; jsom<nb_som_elem; jsom++)
                {
                  int sombis=elem_som(elem,jsom);
                  int j=dom.get_renum_som_perio(sombis);
                  int i=ii;
                  if(i>j)
                    {
                      int kl=j;
                      j=i;
                      i=kl;
                    }
                  rang=voisins[i].rang(j);
                  if(rang==-1)
                    {
                      voisins[i].add(j);
                      coeffs[i].add(coeff_ij);
                      nnz++;
                    }
                  else
                    {
                      coeffs[i][rang]+=coeff_ij;
                    }
                }
            }
        }
      {
        for (int i=0; i<nb_som; i++)
          if(diag(i)==0)
            diag(i)=1.;
      }
      mat.dimensionner(nb_som, nnz+nb_som) ;
      mat.remplir(voisins, coeffs, diag) ;
      mat.compacte() ;
      mat.set_est_definie(1);
    }
  int elem,indice,face,compi,compj,som;
  ArrOfDouble sigma(dimension);
  static double coeff_som=1./(dimension)/(dimension+1);
  double signe;
  for(elem=0; elem<nb_elem_tot; elem++)
    {
      sigma = 0;
      for(indice=0; indice<nfe; indice++)
        {
          face = elem_faces(elem,indice);
          for(int comp=0; comp<dimension; comp++)
            sigma[comp]+=vit(face, comp);
        }
      for(indice=0; indice<nfe; indice++)
        {
          som = dom.get_renum_som_perio(som_elem(elem,indice));
          face = elem_faces(elem,indice);
          signe=1;
          if(elem!=face_voisins(face,0))
            signe=-1;
          for(compi=0; compi<dimension; compi++)
            for(compj=0; compj<dimension; compj++)
              secmem(som, compi, compj)+=coeff_som*signe*
                                         sigma[compi]*face_normales(face,compj);
        }
    }
// Cerr << "Avant CL secmem = " << secmem << finl;
  const Zone_Cl_VEF& zone_Cl_VEF = la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  int nb_bords =les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      {
        if (!sub_type(Periodique,la_cl.valeur()))
          {
            const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
            int num1 = le_bord.num_premiere_face();
            int num2 = num1 + le_bord.nb_faces();
            for (face=num1; face<num2; face++)
              {
                for(indice=0; indice<(nfe-1); indice++)
                  {
                    som=dom.get_renum_som_perio(face_sommets(face,indice));
                    for (compi=0; compi<dimension; compi++)
                      for (compj=0; compj<dimension; compj++)
                        secmem(som, compi, compj) += 1./dimension*
                                                     vit(face,compi) * face_normales(face,compj) ;
                  }
              }
          }
      }
    }
// Cerr << "Apres CL secmem = " << secmem << finl;
  double coeff=1./(dimension+1.);
  {
    DoubleVect secmemij;
    DoubleVect gradij;
    dom.creer_tableau_sommets(secmemij);
    dom.creer_tableau_sommets(gradij);
    DoubleTab& sgrad = ref_cast_non_const(DoubleTab, savgrad);
    for (compi=0; compi<dimension; compi++)
      for (compj=0; compj<dimension; compj++)
        {
          int i;
          for(i=0; i<nb_som; i++)
            {
              int soml=dom.get_renum_som_perio(i);
              secmemij(soml)=secmem(soml,compi,compj);
              gradij(soml)=sgrad(soml,compi,compj);
            }
          for(elem=0; elem<nb_elem_tot; elem++)
            for(indice=0; indice<nfe; indice++)
              {
                som = dom.get_renum_som_perio(som_elem(elem,indice));
                secmemij(som)-=coeff*grad(elem,compi,compj);
              }
          (ref_cast_non_const(SolveurSys,solveur)).resoudre_systeme(masse, secmemij, gradij);
          for(i=0; i<nb_som; i++)
            {
              int soml=dom.get_renum_som_perio(i);
              double x = gradij(soml);
              grad(nps+soml,compi,compj)=x;
              sgrad(soml,compi,compj)=x;
            }
        }
  }
  for (elem=0; elem<nb_elem_tot; elem++)
    {
      double vol=zone_VEF.volumes(elem);
      for (compi=0; compi<dimension; compi++)
        for (compj=0; compj<dimension; compj++)
          grad(elem,compi,compj)/=vol;
      for(indice=0; indice<nfe; indice++)
        {
          som = nps+dom.get_renum_som_perio(som_elem(elem,indice));
          for (compi=0; compi<dimension; compi++)
            for (compj=0; compj<dimension; compj++)
              grad(elem,compi,compj)-=coeff*grad(som,compi,compj);
        }
    }
  DoubleTab tmp(grad);
  int ntot=tmp.dimension(0);
  for(int ind=0; ind<ntot; ind++)
    for (compi=0; compi<dimension; compi++)
      for (compj=0; compj<dimension; compj++)
        tmp(ind,compi, compj)=0.5*(grad(ind,compi, compj)+grad(ind,compj, compi));
  grad=tmp;
// Cout << "grad = " << grad << finl;
  return grad;
}
References Cerr, coeff, Matrice_Morse_Sym::compacte(), Domaine::creer_tableau_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Matrice_Morse::dimensionner(), Zone::domaine(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Domaine::get_renum_som_perio(), la_zcl_vef, la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), masse, Zone::nb_elem_tot(), Front_VF::nb_faces(), Zone::nb_faces_elem(), Matrice_Morse::nb_lignes(), Zone::nb_som_elem(), Front_VF::num_premiere_face(), Zone_VEF_PreP1b::numero_premier_sommet(), ref_cast, ref_cast_non_const, Matrice_Morse::remplir(), savgrad, Matrice_Sym::set_est_definie(), vect_impl::size(), solveur, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEFP1B::valeur(), Ref_Zone_VEF_PreP1b::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by ajouter().
contribue_au_second_membre()
void Op_Dift_VEF_P1NCP1B_Face::contribue_au_second_membre () const
Definition at line 573 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  return;
}
corriger_div_pour_Cl()
DoubleTab & Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl (DoubleTab & div) const protected
Definition at line 359 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b,
                                             la_zone_vef.valeur());
  const DoubleTab& face_normales = zone_VEF.face_normales();
  const Zone_Cl_VEF& zone_Cl_VEF=la_zcl_vef.valeur();
  const Conds_lim& les_cl = zone_Cl_VEF.les_conditions_limites();
  int nb_bords =les_cl.size();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
      {
        const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
        int num1 = le_bord.num_premiere_face();
        int num2 = num1 + le_bord.nb_faces();
        if (sub_type(Periodique,la_cl.valeur()))
          {
// periodicite
            const Periodique& la_cl_perio = ref_cast(Periodique,
                                                     la_cl.valeur());
            ArrOfInt fait(le_bord.nb_faces());
            for (int face=num1; face<num2; face++)
              {
                if(!fait[face-num1])
                  {
                    int face_associee=num1+la_cl_perio.face_associee(face-num1);
                    fait[face-num1]=(fait[face_associee-num1]=1);
                    for (int comp=0; comp<dimension; comp++)
                      {
                        div(face,comp)+= div(face_associee,comp);
                        div(face_associee,comp)=div(face,comp);
                      }
                  }
              }
          }
        else
          {
            if(sub_type(Symetrie,la_cl.valeur()))
              {
                for (int face=num1; face<num2; face++)
                  {
                    double psc=0;
                    double norme=0;
                    int comp;
                    for (comp=0; comp<dimension; comp++)
                      psc += div(face,comp)*face_normales(face,comp);
                    for (comp=0; comp<dimension; comp++)
                      norme += face_normales(face,comp)*face_normales(face,comp);
// psc/=norme; // Fixed bug: Arithmetic exception
                    if (std::fabs(norme)>=DMINFLOAT) psc/=norme;
                    for (comp=0; comp<dimension; comp++)
                      div(face,comp)-=psc*face_normales(face,comp);
                  }
              }
          }
      }
    }
// Cout << "div = " << div << finl;
  return div;
}
References Objet_U::dimension, DMINFLOAT, Periodique::face_associee(), face_associee, Zone_VEF::face_normales(), Cond_lim::frontiere_dis(), la_zcl_vef, la_zone_vef, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), norme(), Front_VF::num_premiere_face(), ref_cast, vect_impl::size(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEFP1B::valeur(), and Ref_Zone_VEF_PreP1b::valeur().
Referenced by ajouter().
cree_instance()
Objet_U * Op_Dift_VEF_P1NCP1B_Face::cree_instance () static
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
diffusivite()
const Champ_base & Op_Dift_VEF_P1NCP1B_Face::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
Definition at line 47 of file Op_Dift_VEF_P1NCP1B_Face.h.
  {
    return diffusivite_;
  };
References diffusivite_.
duplique()
int Op_Dift_VEF_P1NCP1B_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
get_info()
const Type_info * Op_Dift_VEF_P1NCP1B_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
info()
const Type_info * Op_Dift_VEF_P1NCP1B_Face::info () static
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
printOn()
Sortie & Op_Dift_VEF_P1NCP1B_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 30 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_VEF_P1NCP1B_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Diff_base.
Definition at line 38 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
{
  return s ;
}
remplir_nu()
void Op_Dift_VEF_P1NCP1B_Face::remplir_nu (DoubleTab &) const inline override virtual
Reimplemented from Op_Diff_VEF_base.
Definition at line 62 of file Op_Dift_VEF_P1NCP1B_Face.h.
  {
    Cerr<<__FILE__<<":"<<(int)__LINE__<<finl;
    exit();
  } ;
References Cerr, Process::exit(), and finl.
self_cast() [1/2]
const Op_Dift_VEF_P1NCP1B_Face & Op_Dift_VEF_P1NCP1B_Face::self_cast (const Objet_U & r) static
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
self_cast() [2/2]
Op_Dift_VEF_P1NCP1B_Face & Op_Dift_VEF_P1NCP1B_Face::self_cast (Objet_U & r) static
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
taille_memoire()
unsigned Op_Dift_VEF_P1NCP1B_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Op_Dift_VEF_P1NCP1B_Face.cpp.
verifier()
void Op_Dift_VEF_P1NCP1B_Face::verifier () const
Member Data Documentation
diffusivite_
Ref_Champ_base Op_Dift_VEF_P1NCP1B_Face::diffusivite_ protected
Definition at line 69 of file Op_Dift_VEF_P1NCP1B_Face.h.
Referenced by ajouter(), associer_diffusivite(), calculer_dt_stab(), and diffusivite().
filtre
int Op_Dift_VEF_P1NCP1B_Face::filtre protected
Definition at line 84 of file Op_Dift_VEF_P1NCP1B_Face.h.
info_obj
const Type_info Op_Dift_VEF_P1NCP1B_Face::info_obj static
Definition at line 40 of file Op_Dift_VEF_P1NCP1B_Face.h.
la_zcl_vef
Ref_Zone_Cl_VEFP1B Op_Dift_VEF_P1NCP1B_Face::la_zcl_vef protected
Definition at line 80 of file Op_Dift_VEF_P1NCP1B_Face.h.
Referenced by associer(), calculer_divergence_som(), calculer_gradient_som(), and corriger_div_pour_Cl().
la_zone_vef
Ref_Zone_VEF_PreP1b Op_Dift_VEF_P1NCP1B_Face::la_zone_vef protected
Definition at line 79 of file Op_Dift_VEF_P1NCP1B_Face.h.
Referenced by ajouter(), associer(), calculer_divergence_elem(), calculer_divergence_som(), calculer_dt_stab(), calculer_gradient_elem(), calculer_gradient_som(), and corriger_div_pour_Cl().
lambda
double Op_Dift_VEF_P1NCP1B_Face::lambda protected
Definition at line 83 of file Op_Dift_VEF_P1NCP1B_Face.h.
le_modele_turbulence
Ref_Mod_turb_hyd_base Op_Dift_VEF_P1NCP1B_Face::le_modele_turbulence protected
Definition at line 78 of file Op_Dift_VEF_P1NCP1B_Face.h.
masse
Matrice_Morse_Sym Op_Dift_VEF_P1NCP1B_Face::masse protected
Definition at line 85 of file Op_Dift_VEF_P1NCP1B_Face.h.
Referenced by calculer_gradient_som().
savgrad
DoubleTab Op_Dift_VEF_P1NCP1B_Face::savgrad protected
Definition at line 86 of file Op_Dift_VEF_P1NCP1B_Face.h.
Referenced by calculer_gradient_som().
solveur
SolveurSys Op_Dift_VEF_P1NCP1B_Face::solveur protected
Definition at line 81 of file Op_Dift_VEF_P1NCP1B_Face.h.
Referenced by associer(), and calculer_gradient_som().
trans
int Op_Dift_VEF_P1NCP1B_Face::trans protected
Definition at line 82 of file Op_Dift_VEF_P1NCP1B_Face.h.
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Dift_VEF_P1NCP1B_Face.h
src/P1NCP1B/Operateurs/Op_Dift_VEF_P1NCP1B_Face.cpp