TRUST: Op_Grad_PolyMAC_Face Class Reference
Op_Grad_PolyMAC_Face Class Reference
class Op_Grad_PolyMAC_Face
Cette classe represente l'operateur de gradient
La discretisation est PolyMAC
On calcule le gradient d'un champ_Elem_PolyMAC (la pression)
#include <Op_Grad_PolyMAC_Face.h>
Public Member Functions
Op_Grad_PolyMAC_Face ()
~Op_Grad_PolyMAC_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void check_multiphase_compatibility () const override
Public Member Functions inherited from Operateur_Grad_base
Operateur_Grad_base ()
~Operateur_Grad_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner (Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & ajouter (const DoubleTab &inco, DoubleTab &secmem) const override
virtual DoubleVect & multvect (const DoubleTab &, DoubleTab &) const
Calcul sans les conditions aux limites ?
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Grad_PolyMAC_Face & self_cast (Objet_U &)
static const Op_Grad_PolyMAC_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Grad_base
static const Type_info * info ()
static Operateur_Grad_base & self_cast (Objet_U &)
static const Operateur_Grad_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Grad_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Private Attributes
Ref_Zone_PolyMAC ref_zone
Ref_Zone_Cl_PolyMAC ref_zcl
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Op_Grad_PolyMAC_Face
Cette classe represente l'operateur de gradient
La discretisation est PolyMAC
On calcule le gradient d'un champ_Elem_PolyMAC (la pression)
Definition at line 38 of file Op_Grad_PolyMAC_Face.h.
Constructor & Destructor Documentation
Op_Grad_PolyMAC_Face()
Op_Grad_PolyMAC_Face::Op_Grad_PolyMAC_Face ()
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
~Op_Grad_PolyMAC_Face()
Op_Grad_PolyMAC_Face::~Op_Grad_PolyMAC_Face ()
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Grad_PolyMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 109 of file Op_Grad_PolyMAC_Face.cpp.
{
  const Zone_PolyMAC& zone = ref_zone.valeur();
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces(), &fcl = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur()).fcl();
  const DoubleTab& vfd = zone.volumes_entrelaces_dir(), &press = semi_impl.count("pression") ? semi_impl.at("pression") : ref_cast(Navier_Stokes_std, equation()).pression().valeurs(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const DoubleVect& fs = zone.face_surfaces(), &vf = zone.volumes_entrelaces(), &pe = zone.porosite_elem();
  int i, j, e, eb, f, fb, ne_tot = zone.nb_elem_tot(), n, N = secmem.line_size(), m, M = press.line_size();
  Matrice_Morse *mat = !semi_impl.count("pression") && matrices.count("pression") ? matrices.at("pression") : NULL;
  DoubleTrav w2, alpha(N), coeff_e(N); //matrice W2 dans chaque element, taux de vide a la face
  w2.set_smart_resize(1);
  for (e = 0; e < ne_tot; e++)
    for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(0); i++)
      if ((f = e_f(e, i)) < zone.nb_faces())
        {
          /* taux de vide a la face (identique a celui de Masse_PolyMAC_Face) */
          double prefac = (e == f_e(f, 0) ? 1 : -1) * pe(e) * vfd(f, e != f_e(f, 0)) / fs(f); /* ponderation pour elimner p_f si on est en TPFA */
          for (alpha = 0, j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
            for (n = 0; n < N; n++) alpha(n) += vfd(f, j) * (alp ? (*alp)(eb, n) : 1) / vf(f);
          for (coeff_e = 0, j = 0; j < w2.dimension(1); j++)
            if (w2(i, j, 0))
              for (fb = e_f(e, j), n = 0, m = 0; n < N; n++, m += (M > 1))
                {
                  double fac = alpha(n) * w2(i, j, 0) * prefac;
                  secmem(f, n) -= fac * (press(ne_tot + fb, m) - press(e, m));
                  if (mat && fcl(fb, 0) != 1) (*mat)(N * f + n, M * (ne_tot + fb) + m) += fac; /* bloc (face, face) */
                  coeff_e(n) += fac;
                }
          if (mat)
            for (n = 0, m = 0; n < N; n++, m += (M > 1)) (*mat)(N * f + n, M * e + m) -= coeff_e(n); /* bloc (face, elem) */
        }
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), TRUSTVect< _TYPE_ >::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), Zone_VF::porosite_elem(), ref_cast, ref_zone, TRUSTArray< _TYPE_ >::set_smart_resize(), sub_type, Ref_Zone_PolyMAC::valeur(), valeur(), Zone_VF::volumes_entrelaces(), Zone_Poly_base::volumes_entrelaces_dir(), and Zone_PolyMAC::W2().
associer()
void Op_Grad_PolyMAC_Face::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch) override virtual
Implements Operateur_base.
Definition at line 61 of file Op_Grad_PolyMAC_Face.cpp.
{
  ref_zone = ref_cast(Zone_PolyMAC, zone_dis.valeur());
  ref_zcl = ref_cast(Zone_Cl_PolyMAC, zone_cl_dis.valeur());
}
References ref_cast, ref_zcl, ref_zone, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
check_multiphase_compatibility()
void Op_Grad_PolyMAC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 58 of file Op_Grad_PolyMAC_Face.h.
{ }; //ok
completer()
void Op_Grad_PolyMAC_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 67 of file Op_Grad_PolyMAC_Face.cpp.
{
  Operateur_Grad_base::completer();
  const Zone_PolyMAC& zone = ref_zone.valeur();
  /* initialisation des inconnues auxiliaires de la pression... */
  ref_cast(Champ_Elem_PolyMAC, ref_cast(Navier_Stokes_std, equation()).pression().valeur()).init_auxiliary_variables();
  /* et de grad P si la vitesse en a */
  if (equation().inconnue().valeurs().get_md_vector() == zone.mdv_faces_aretes)
    ref_cast(Champ_Face_PolyMAC, ref_cast(Navier_Stokes_std, equation()).grad_P().valeur()).init_auxiliary_variables();
  /* besoin d'un joint de 1 */
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Grad_PolyMAC_Face : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
}
References Cerr, Operateur_base::completer(), Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Zone::joint(), Zone_PolyMAC::mdv_faces_aretes, Zone::nb_joints(), ref_cast, ref_zone, Ref_Zone_PolyMAC::valeur(), valeur(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Op_Grad_PolyMAC_Face::cree_instance () static
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
dimensionner_blocs()
void Op_Grad_PolyMAC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 81 of file Op_Grad_PolyMAC_Face.cpp.
{
  if (!matrices.count("pression")) return; //rien a faire
  const Zone_PolyMAC& zone = ref_zone.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const IntTab& e_f = zone.elem_faces(), &fcl = ch.fcl();
  const DoubleTab& vit = ch.valeurs(), &press = ref_cast(Navier_Stokes_std, equation()).pression().valeurs();
  int i, j, e, f, fb, ne_tot = zone.nb_elem_tot(), n, N = vit.line_size(), m, M = press.line_size();
  Matrice_Morse *mat = matrices["pression"], mat2;
  IntTrav sten(0, 2);
  DoubleTrav w2;
  sten.set_smart_resize(1), w2.set_smart_resize(1);
  for (e = 0; e < ne_tot; e++)
    for (zone.W2(NULL, e, w2), i = 0; i < w2.dimension(0); i++)
      if ((f = e_f(e, i)) < zone.nb_faces()) /* faces reelles seulement */
        {
          for (n = 0, m = 0; n < N; n++, m += (M > 1)) sten.append_line(N * f + n, M * e + m); /* bloc (face, elem )*/
          for (j = 0; j < w2.dimension(1); j++)
            if (fcl(fb = e_f(e, j), 0) != 1 && w2(i, j, 0)) /* bloc (face, face) */
              for (n = 0, m = 0; n < N; n++, m += (M > 1)) sten.append_line(N * f + n, M * (ne_tot + fb) + m);
        }
  /* allocation / remplissage */
  tableau_trier_retirer_doublons(sten);
  Matrix_tools::allocate_morse_matrix(vit.size_totale(), press.size_totale(), sten, mat2);
  mat->nb_colonnes() ? *mat += mat2 : *mat = mat2;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Champ_Face_PolyMAC::fcl(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces(), ref_cast, ref_zone, TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTVect< _TYPE_ >::size_totale(), tableau_trier_retirer_doublons(), Ref_Zone_PolyMAC::valeur(), valeur(), Champ_Inc_base::valeurs(), and Zone_PolyMAC::W2().
duplique()
int Op_Grad_PolyMAC_Face::duplique () const override virtual
Implements Objet_U.
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
get_info()
const Type_info * Op_Grad_PolyMAC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
has_interface_blocs()
int Op_Grad_PolyMAC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 49 of file Op_Grad_PolyMAC_Face.h.
  {
    return 1;
  };
impr()
int Op_Grad_PolyMAC_Face::impr (Sortie & os) const override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Operateur_base.
Definition at line 144 of file Op_Grad_PolyMAC_Face.cpp.
{
  return 0;
}
info()
const Type_info * Op_Grad_PolyMAC_Face::info () static
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
printOn()
Sortie & Op_Grad_PolyMAC_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 45 of file Op_Grad_PolyMAC_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Op_Grad_PolyMAC_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Operateur_Grad_base.
Definition at line 53 of file Op_Grad_PolyMAC_Face.cpp.
{
  return s ;
}
self_cast() [1/2]
const Op_Grad_PolyMAC_Face & Op_Grad_PolyMAC_Face::self_cast (const Objet_U & r) static
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
self_cast() [2/2]
Op_Grad_PolyMAC_Face & Op_Grad_PolyMAC_Face::self_cast (Objet_U & r) static
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
taille_memoire()
unsigned Op_Grad_PolyMAC_Face::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 39 of file Op_Grad_PolyMAC_Face.cpp.
Member Data Documentation
info_obj
const Type_info Op_Grad_PolyMAC_Face::info_obj static
Definition at line 41 of file Op_Grad_PolyMAC_Face.h.
ref_zcl
Ref_Zone_Cl_PolyMAC Op_Grad_PolyMAC_Face::ref_zcl private
Definition at line 63 of file Op_Grad_PolyMAC_Face.h.
Referenced by associer().
ref_zone
Ref_Zone_PolyMAC Op_Grad_PolyMAC_Face::ref_zone private
Definition at line 62 of file Op_Grad_PolyMAC_Face.h.
Referenced by ajouter_blocs(), associer(), completer(), and dimensionner_blocs().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Grad_PolyMAC_Face.h
src/PolyMAC/Operateurs/Op_Grad_PolyMAC_Face.cpp