TRUST: Champ_front_fonc_pois_ipsn Class Reference
Champ_front_fonc_pois_ipsn Class Reference
class Champ_front_fonc_pois_ipsn
Classe derivee de Champ_front_fonc
#include <Champ_front_fonc_pois_ipsn.h>
Public Member Functions
Champ_front_fonc_pois_ipsn ()
~Champ_front_fonc_pois_ipsn ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
int initialiser (double temps, const Champ_Inc_base &inco)
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_front_fonc_pois_ipsn & self_cast (Objet_U &)
static const
Champ_front_fonc_pois_ipsn & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le nom du champ sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Protected Attributes
DoubleVect U_moy
double R_tube
DoubleVect R_loc
Detailed Description
class Champ_front_fonc_pois_ipsn
Classe derivee de Champ_front_fonc
Definition at line 35 of file Champ_front_fonc_pois_ipsn.h.
Constructor & Destructor Documentation
Champ_front_fonc_pois_ipsn::Champ_front_fonc_pois_ipsn ()
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
Champ_front_fonc_pois_ipsn::~Champ_front_fonc_pois_ipsn ()
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
Member Function Documentation
Objet_U * Champ_front_fonc_pois_ipsn::cree_instance () [static]
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
int Champ_front_fonc_pois_ipsn::duplique () const [virtual]
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
const Type_info * Champ_front_fonc_pois_ipsn::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
const Type_info * Champ_front_fonc_pois_ipsn::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
int Champ_front_fonc_pois_ipsn::initialiser (double temps, const Champ_Inc_base & inco) [virtual]
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel.
Les classes derivees doivent imperativement appeler cette methode.
Returns:
0 en cas d'erreur, 1 sinon.
Signification:
Contraintes:
Reimplemented from Champ_front_var.
Definition at line 75 of file Champ_front_fonc_pois_ipsn.cpp.
References Domaine::coord(), dabs(), Objet_U::dimension, Zone::domaine(), DoubleVect::echange_espace_virtuel(), Frontiere::faces(), Champ_front_var::initialiser(), Champ_front_base::la_frontiere_dis, Field_base::nb_comp(), Frontiere::nb_faces(), Faces::nb_som_faces(), R_loc, R_tube, Faces::sommet(), U_moy, Champ_front_base::valeurs(), and Frontiere::zone().
{
  if (!Champ_front_fonc::initialiser(temps,inco))
    return 0;
  int dim = nb_comp();
  const Frontiere& front=la_frontiere_dis->frontiere();
  const Zone& zone=front.zone();
  const Domaine& domaine=zone.domaine();
  const Faces& faces=front.faces();
  int nb_faces=front.nb_faces();
  int nbsf=faces.nb_som_faces();
  DoubleTab& tab=valeurs();
  DoubleVect loc_local(dim) ;
  double teta = 40./360.*2.*3.14159  ;
  double dummy ;
  DoubleTab coord_trans(3,3) ;
  coord_trans(0,0) = cos(teta) ;
  coord_trans(0,1) = 0.        ;
  coord_trans(0,2) = sin(teta) ;
  coord_trans(1,0) = 0. ;
  coord_trans(1,1) = 1. ;
  coord_trans(1,2) = 0. ;
  coord_trans(2,0) = -sin(teta) ;
  coord_trans(2,1) = 1.        ;
  coord_trans(2,2) = cos(teta) ;
  DoubleVect trans(3) ;
  int k, i ,j ;
  for( int fac=0; fac<nb_faces; fac++)
    {
      loc_local = 0.;
      for( k=0; k<nbsf; k++)
        {
          for ( i=0; i<dim; i++)
            loc_local(i)+=domaine.coord(faces.sommet(fac,k),i);
        }
      loc_local /= double(nbsf);
      trans = 0. ;
      for (i=0; i<dimension; i++)
        for (j=0; j<dimension; j++)
          trans(i) += (loc_local(j) - R_loc(j)) * coord_trans(i,j) ;
      loc_local = trans ;
      double ray2 = R_tube*R_tube ;
      dummy = loc_local(0)*loc_local(1)*ray2 ;
      tab(fac,2) = dabs(dummy) ;
      dummy = loc_local(0)*loc_local(2)*ray2 ;
      tab(fac,1) = dabs(dummy) ;
      dummy = loc_local(1)*loc_local(2)*ray2 ;
      tab(fac,0) = dabs(dummy) ;
      dummy = loc_local(0)*loc_local(0)*loc_local(0)*loc_local(1) ;
      tab(fac,2) -= dabs(dummy) ;
      dummy = loc_local(1)*loc_local(1)*loc_local(1)*loc_local(0) ;
      tab(fac,2) -= dabs(dummy) ;
      dummy = loc_local(0)*loc_local(0)*loc_local(0)*loc_local(2) ;
      tab(fac,1) -= dabs(dummy) ;
      dummy = loc_local(2)*loc_local(2)*loc_local(2)*loc_local(0) ;
      tab(fac,1) -= dabs(dummy) ;
      dummy = loc_local(2)*loc_local(2)*loc_local(2)*loc_local(1) ;
      tab(fac,0) -= dabs(dummy) ;
      dummy = loc_local(1)*loc_local(1)*loc_local(1)*loc_local(2) ;
      tab(fac,0) -= dabs(dummy) ;
      for ( i=0; i<dim; i++)
        tab(fac,i) *= U_moy(i) ;
    }
  tab.echange_espace_virtuel();
  return 1;
}
Sortie & Champ_front_fonc_pois_ipsn::printOn (Sortie & s) const [protected, virtual]
Imprime le nom du champ sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_front_fonc.
Definition at line 32 of file Champ_front_fonc_pois_ipsn.cpp.
References finl, Field_base::le_nom(), Objet_U::que_suis_je(), DoubleVect::size(), and Champ_front_base::valeurs().
{
  s << que_suis_je() << " " << le_nom() << finl ;
  const DoubleTab& tab=valeurs();
  s << tab.size() << " ";
  for(int i=0; i<tab.size(); i++)
    s << tab(0,i);
  return  s ;
}
Entree & Champ_front_fonc_pois_ipsn::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees
Doit dans tous les cas fixer nb_comp.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_front_fonc.
Definition at line 48 of file Champ_front_fonc_pois_ipsn.cpp.
References Field_base::fixer_nb_comp(), Champ_Proto::lire_dimension(), Objet_U::que_suis_je(), R_loc, R_tube, DoubleVect::resize(), and U_moy.
{
  is >> R_tube ;
  int nbcomp , i;
  nbcomp=lire_dimension(is,que_suis_je());
  fixer_nb_comp(nbcomp);
  U_moy.resize(nbcomp) ;
  R_loc.resize(nbcomp) ;
  for (i = 0; i < nbcomp; i++)
    {
      is >> U_moy(i) ;
    }
  for (i = 0; i < nbcomp; i++)
    {
      is >> R_loc(i) ;
    }
// Cerr << "Champ_front_fonc_pois_ipsn lu U_moy = "<< U_moy << finl ;
  return is ;
}
Champ_front_fonc_pois_ipsn & Champ_front_fonc_pois_ipsn::self_cast (Objet_U & r) [static]
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
const Champ_front_fonc_pois_ipsn & Champ_front_fonc_pois_ipsn::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
unsigned Champ_front_fonc_pois_ipsn::taille_memoire () const [virtual]
Reimplemented from Champ_front_fonc.
Definition at line 27 of file Champ_front_fonc_pois_ipsn.cpp.
Member Data Documentation
const Type_info Champ_front_fonc_pois_ipsn::info_obj [static]
Reimplemented from Champ_front_fonc.
Definition at line 38 of file Champ_front_fonc_pois_ipsn.h.
DoubleVect Champ_front_fonc_pois_ipsn::R_loc [protected]
Definition at line 48 of file Champ_front_fonc_pois_ipsn.h.
Referenced by initialiser(), and readOn().
double Champ_front_fonc_pois_ipsn::R_tube [protected]
Definition at line 47 of file Champ_front_fonc_pois_ipsn.h.
Referenced by initialiser(), and readOn().
DoubleVect Champ_front_fonc_pois_ipsn::U_moy [protected]
Definition at line 46 of file Champ_front_fonc_pois_ipsn.h.
Referenced by initialiser(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_front_fonc_pois_ipsn.h
src/Kernel/Champs/Champ_front_fonc_pois_ipsn.cpp