TRUST: Champ_Tabule_Temps Class Reference
Champ_Tabule_Temps Class Reference
Classe Champ_Tabule_Temps
Cette classe derivee de Champ_Uniforme_inst qui represente
un champ constant dans l'espace et tabule en temps.
La valeur du champ a un instant quelconque est calcule par interpolation
lineaire a partir de la table des valeurs.
#include <Champ_Tabule_Temps.h>
Public Member Functions
Champ_Tabule_Temps ()
~Champ_Tabule_Temps ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void me_calculer (double t)
Mise a jour en temps des valeurs tabulees du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Tabule_Temps & self_cast (Objet_U &)
static const Champ_Tabule_Temps & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN.
virtual Entree & readOn (Entree &)
Lit les valeurs du champ tabule en temps a partir
d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp) et on
remplit une table a partir des nval couples (vrel_i, tps_i).
Format:
Champ_Tabule_Temps nb_comp { nval tps_1...tps_nval vrel_1...vrel_nval }.
Private Attributes
Table la_table
Detailed Description
Classe Champ_Tabule_Temps
Cette classe derivee de Champ_Uniforme_inst qui represente
un champ constant dans l'espace et tabule en temps.
La valeur du champ a un instant quelconque est calcule par interpolation
lineaire a partir de la table des valeurs.
Definition at line 43 of file Champ_Tabule_Temps.h.
Constructor & Destructor Documentation
Champ_Tabule_Temps::Champ_Tabule_Temps ()
Definition at line 25 of file Champ_Tabule_Temps.cpp.
Champ_Tabule_Temps::~Champ_Tabule_Temps ()
Definition at line 25 of file Champ_Tabule_Temps.cpp.
Member Function Documentation
Objet_U * Champ_Tabule_Temps::cree_instance () [static]
Reimplemented from Champ_Uniforme.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
int Champ_Tabule_Temps::duplique () const [virtual]
Implements Champ_Uniforme_inst.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
const Type_info * Champ_Tabule_Temps::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme_inst.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
const Type_info * Champ_Tabule_Temps::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Uniforme_inst.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
void Champ_Tabule_Temps::me_calculer (double t) [virtual]
Mise a jour en temps des valeurs tabulees du champ.
Implements Champ_Uniforme_inst.
Definition at line 129 of file Champ_Tabule_Temps.cpp.
References la_table, DoubleVect::size(), Champ_base::temps(), Table::val(), Table::valeurs(), and Champ_Don_base::valeurs().
{
  if (temps() != tps)
    {
      DoubleVect& mes_valeurs = valeurs();
      if (mes_valeurs.size() == 1)
        mes_valeurs[0] = la_table.val(tps);
      else
        la_table.valeurs(mes_valeurs,tps);
    }
}
Sortie & Champ_Tabule_Temps::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Champ_Uniforme_inst.
Definition at line 42 of file Champ_Tabule_Temps.cpp.
{
  return os;
}
Entree & Champ_Tabule_Temps::readOn (Entree & is) [protected, virtual]
Lit les valeurs du champ tabule en temps a partir
d'un flot d'entree.
On lit le nombre de composante du champ (nb_comp) et on
remplit une table a partir des nval couples (vrel_i, tps_i).
Format:
Champ_Tabule_Temps nb_comp { nval tps_1...tps_nval vrel_1...vrel_nval }.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Uniforme_inst.
Definition at line 68 of file Champ_Tabule_Temps.cpp.
References Cerr, Champ_base::changer_temps(), Champ_Don_base::dimensionner(), Process::exit(), finl, la_table, Champ_Proto::lire_dimension(), Field_base::nb_compo_, Objet_U::que_suis_je(), and Table::remplir().
{
  Motcle motlu;
  int nb_val;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  nb_compo_=lire_dimension(is,que_suis_je());
  if (nb_compo_ <= 0)
    {
      Cerr << "Error in Champ_Tabule_Temps::readOn : nb_compo <= 0" << finl;
      assert(0);
      exit();
    }
  dimensionner(1, nb_compo_);
  is >> motlu;
  if (motlu == accolade_ouverte)
    {
      nb_val=lire_dimension(is,que_suis_je());
      DoubleVect param(nb_val);
      DoubleTab les_valeurs(nb_val, nb_compo_);
      for (int i = 0; i < nb_val; i++)
        is >> param[i];
      for (int i = 0; i < nb_val; i++)
        for (int k = 0; k < nb_compo_; k++)
          is >> les_valeurs(i, k);
      la_table.remplir(param, les_valeurs);
      is >> motlu;
      if (motlu != accolade_fermee)
        {
          Cerr << "Error reading from an object of type Champ_Tabule_Temps" << finl;
          Cerr << "We expected keyword } instead of " << motlu << finl;
          exit();
        }
    }
  else
    {
      Cerr << "Error reading from an object of type Champ_Tabule_Temps" << finl;
      Cerr << "We expected keyword { instead of " << motlu << finl;
      exit();
    }
  changer_temps(-1e9);
// mettre_a_jour(0.);
  return is;
}
Champ_Tabule_Temps & Champ_Tabule_Temps::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Uniforme_inst.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
const Champ_Tabule_Temps & Champ_Tabule_Temps::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Uniforme_inst.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
unsigned Champ_Tabule_Temps::taille_memoire () const [virtual]
Reimplemented from Champ_Uniforme.
Definition at line 25 of file Champ_Tabule_Temps.cpp.
Member Data Documentation
const Type_info Champ_Tabule_Temps::info_obj [static]
Reimplemented from Champ_Uniforme_inst.
Definition at line 46 of file Champ_Tabule_Temps.h.
Table Champ_Tabule_Temps::la_table [private]
Definition at line 54 of file Champ_Tabule_Temps.h.
Referenced by me_calculer(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Tabule_Temps.h
src/Kernel/Champs/Champ_Tabule_Temps.cpp