TRUST: Multiplicateur_diphasique_Lottes_Flinn Class Reference
Multiplicateur_diphasique_Lottes_Flinn Class Reference
classe Multiplicateur_diphasique_Lottes_Flinn
correlation de multiplicateur diphasique de Lottes-Flinn :
alpha < alpha_min -> seule la phase liquide frotte avec phi = 1 / (1-alpha)^2
alpha > alpha_max -> seule la vapeur frotte
parametres :
- alpha_min -> debut de la transition
- alpha_fin -> fin de la transition
#include <Multiplicateur_diphasique_Lottes_Flinn.h>
Public Member Functions
Multiplicateur_diphasique_Lottes_Flinn ()
~Multiplicateur_diphasique_Lottes_Flinn ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void coefficient (const double *alpha, const double *rho, const double *v, const double *f, const double *mu, const double Dh, const double gamma, const double *Fk, const double Fm, DoubleTab &coeff) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Multiplicateur_diphasique_Lottes_Flinn & self_cast (Objet_U &)
static const
Multiplicateur_diphasique_Lottes_Flinn & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Attributes
double alpha_min_
double alpha_max_
int n_l
int n_g
Detailed Description
classe Multiplicateur_diphasique_Lottes_Flinn
correlation de multiplicateur diphasique de Lottes-Flinn :
alpha < alpha_min -> seule la phase liquide frotte avec phi = 1 / (1-alpha)^2
alpha > alpha_max -> seule la vapeur frotte
parametres :
- alpha_min -> debut de la transition
- alpha_fin -> fin de la transition
Definition at line 39 of file Multiplicateur_diphasique_Lottes_Flinn.h.
Constructor & Destructor Documentation
Multiplicateur_diphasique_Lottes_Flinn::Multiplicateur_diphasique_Lottes_Flinn ()
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
Multiplicateur_diphasique_Lottes_Flinn::~Multiplicateur_diphasique_Lottes_Flinn ()
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
Member Function Documentation
void Multiplicateur_diphasique_Lottes_Flinn::coefficient (const double * alpha, const double * rho, const double * v, const double * f, const double * mu, const double Dh, const double gamma, const double * Fk, const double Fm, DoubleTab & coeff) const [virtual]
Implements Multiplicateur_diphasique_base.
Definition at line 53 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
References alpha_max_, alpha_min_, coeff, max(), min(), n_g, and n_l.
{
  double a_tot = alpha[n_l] + (n_g >= 0 ? alpha[n_g] : 0), a_l = alpha[n_l] / a_tot, a_g = n_g >= 0 ? alpha[n_g] / a_tot : 0,
         a_m = alpha_min_, b_m = 1 - a_m, a_M = alpha_max_, b_M = 1 - a_M;
  coeff = 0;
  coeff(n_l, 0) = a_l < b_m ? max(a_l - b_M, 0.) / (b_m * b_m) : 1. / (a_l * a_l);
  if (n_g >= 0) coeff(n_g, 0) = min(max((a_g - a_m) / (a_M - a_m), 0.), 1.);
}
Objet_U * Multiplicateur_diphasique_Lottes_Flinn::cree_instance () [static]
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
int Multiplicateur_diphasique_Lottes_Flinn::duplique () const [virtual]
Implements Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
const Type_info * Multiplicateur_diphasique_Lottes_Flinn::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
const Type_info * Multiplicateur_diphasique_Lottes_Flinn::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
Sortie & Multiplicateur_diphasique_Lottes_Flinn::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 28 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
{
  return os;
}
Entree & Multiplicateur_diphasique_Lottes_Flinn::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 33 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
References Param::ajouter(), alpha_max_, alpha_min_, Nom::debute_par(), Process::exit(), Nom::finit_par(), Param::lire_avec_accolades_depuis(), n_g, n_l, Pb_Multiphase::nb_phases(), Pb_Multiphase::nom_phase(), Correlation_base::pb_, Objet_U::que_suis_je(), ref_cast, sub_type, and Ref_Probleme_base::valeur().
{
  alpha_min_ = 0.9, alpha_max_ = 0.95, n_l = -1, n_g = -1;
  Param param(que_suis_je());
  param.ajouter("alpha_min", &alpha_min_);
  param.ajouter("alpha_max", &alpha_max_);
  param.lire_avec_accolades_depuis(is);
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, pb_.valeur()) ? &ref_cast(Pb_Multiphase, pb_.valeur()) : NULL;
  if (!pbm || pbm->nb_phases() == 1) n_l = 0, n_g = -1; //pas un Pb_Multiphase -> monophasique liquide
  else for (int n = 0; n < pbm->nb_phases(); n++) //recherche de n_l, n_g : phase {liquide,gaz}_continu en priorite
      if (pbm->nom_phase(n).debute_par("liquide") && (n_l < 0 || pbm->nom_phase(n).finit_par("continu")))  n_l = n;
      else if (pbm->nom_phase(n).debute_par("gaz") && (n_g < 0 || pbm->nom_phase(n).finit_par("continu"))) n_g = n;
  if (n_l < 0) Process::exit(que_suis_je() + " : main phase not found!");
  return is;
}
const Multiplicateur_diphasique_Lottes_Flinn & Multiplicateur_diphasique_Lottes_Flinn::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
Multiplicateur_diphasique_Lottes_Flinn & Multiplicateur_diphasique_Lottes_Flinn::self_cast (Objet_U & r) [static]
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
unsigned Multiplicateur_diphasique_Lottes_Flinn::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 26 of file Multiplicateur_diphasique_Lottes_Flinn.cpp.
Member Data Documentation
double Multiplicateur_diphasique_Lottes_Flinn::alpha_max_ [protected]
Definition at line 47 of file Multiplicateur_diphasique_Lottes_Flinn.h.
Referenced by coefficient(), and readOn().
double Multiplicateur_diphasique_Lottes_Flinn::alpha_min_ [protected]
Definition at line 47 of file Multiplicateur_diphasique_Lottes_Flinn.h.
Referenced by coefficient(), and readOn().
const Type_info Multiplicateur_diphasique_Lottes_Flinn::info_obj [static]
Reimplemented from Multiplicateur_diphasique_base.
Definition at line 41 of file Multiplicateur_diphasique_Lottes_Flinn.h.
int Multiplicateur_diphasique_Lottes_Flinn::n_g [protected]
Definition at line 48 of file Multiplicateur_diphasique_Lottes_Flinn.h.
Referenced by coefficient(), and readOn().
int Multiplicateur_diphasique_Lottes_Flinn::n_l [protected]
Definition at line 48 of file Multiplicateur_diphasique_Lottes_Flinn.h.
Referenced by coefficient(), and readOn().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_Lottes_Flinn.h
src/ThHyd/Multiphase/Correlations/Multiplicateur_diphasique_Lottes_Flinn.cpp