TRUST: Saturation_constant Class Reference
Saturation_constant Class Reference
#include <Saturation_constant.h>
Public Member Functions
Saturation_constant ()
~Saturation_constant ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double Tsat_ (const double P) const override
double dP_Tsat_ (const double P) const override
double Psat_ (const double T) const override
double dT_Psat_ (const double T) const override
double Lvap_ (const double P) const override
double dP_Lvap_ (const double P) const override
double Hls_ (const double P) const override
double dP_Hls_ (const double P) const override
double Hvs_ (const double P) const override
double dP_Hvs_ (const double P) const override
double sigma_ (const double T, const double P) const override
Public Member Functions inherited from Saturation_base
Saturation_base ()
~Saturation_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
double Tsat (const double P) const
double dP_Tsat (const double P) const
double Psat (const double T) const
double dT_Psat (const double T) const
double Lvap (const double P) const
double dP_Lvap (const double P) const
double Hls (const double P) const
double dP_Hls (const double P) const
double Hvs (const double P) const
double dP_Hvs (const double P) const
virtual double Tsat_ (const double P) const =0
virtual double dP_Tsat_ (const double P) const =0
virtual double Psat_ (const double T) const =0
virtual double dT_Psat_ (const double T) const =0
virtual double Lvap_ (const double P) const =0
virtual double dP_Lvap_ (const double P) const =0
virtual double Hls_ (const double P) const =0
virtual double dP_Hls_ (const double P) const =0
virtual double Hvs_ (const double P) const =0
virtual double dP_Hvs_ (const double P) const =0
double get_Pref () const
Public Member Functions inherited from Interface_base
Interface_base ()
~Interface_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)
double sigma (const double T, const double P) const
virtual double sigma_ (const double T, const double P) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Saturation_constant & self_cast (Objet_U &)
static const Saturation_constant & self_cast (const Objet_U &)
Static Public Member Functions inherited from Saturation_base
static const Type_info * info ()
static Saturation_base & self_cast (Objet_U &)
static const Saturation_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interface_base
static const Type_info * info ()
static Interface_base & self_cast (Objet_U &)
static const Interface_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Saturation_base
static const Type_info info_obj
Static Public Attributes inherited from Interface_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
double tsat_ = - 1e+38
double psat_ = - 1e+38
double lvap_ = - 1e+38
double hls_ = - 1e+38
double hvs_ = - 1e+38
Protected Attributes inherited from Saturation_base
double P_ref_ = -1
double T_ref_ = -1
Protected Attributes inherited from Interface_base
double sigma__ = -1
Ref_Pb_Multiphase pb_multi
Detailed Description
Definition at line 21 of file Saturation_constant.h.
Constructor & Destructor Documentation
Saturation_constant()
Saturation_constant::Saturation_constant ()
Definition at line 18 of file Saturation_constant.cpp.
~Saturation_constant()
Saturation_constant::~Saturation_constant ()
Definition at line 18 of file Saturation_constant.cpp.
Member Function Documentation
cree_instance()
Objet_U * Saturation_constant::cree_instance () static
Definition at line 18 of file Saturation_constant.cpp.
dP_Hls_()
double Saturation_constant::dP_Hls_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 81 of file Saturation_constant.cpp.
{
  return 0;
}
dP_Hvs_()
double Saturation_constant::dP_Hvs_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 91 of file Saturation_constant.cpp.
{
  return 0;
}
dP_Lvap_()
double Saturation_constant::dP_Lvap_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 71 of file Saturation_constant.cpp.
{
  return 0;
}
dP_Tsat_()
double Saturation_constant::dP_Tsat_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 55 of file Saturation_constant.cpp.
{
  return 0;
}
dT_Psat_()
double Saturation_constant::dT_Psat_ (const double T) const override virtual
Implements Saturation_base.
Definition at line 63 of file Saturation_constant.cpp.
{
  return 0;
}
duplique()
int Saturation_constant::duplique () const override virtual
Implements Objet_U.
Definition at line 18 of file Saturation_constant.cpp.
get_info()
const Type_info * Saturation_constant::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Saturation_base.
Definition at line 18 of file Saturation_constant.cpp.
Hls_()
double Saturation_constant::Hls_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 76 of file Saturation_constant.cpp.
{
  return hls_;
}
References hls_.
Hvs_()
double Saturation_constant::Hvs_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 86 of file Saturation_constant.cpp.
{
  return hvs_;
}
References hvs_.
info()
const Type_info * Saturation_constant::info () static
Definition at line 18 of file Saturation_constant.cpp.
Lvap_()
double Saturation_constant::Lvap_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 67 of file Saturation_constant.cpp.
{
  return lvap_;
}
References lvap_.
printOn()
Sortie & Saturation_constant::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Saturation_base.
Definition at line 26 of file Saturation_constant.cpp.
{
  return os;
}
Psat_()
double Saturation_constant::Psat_ (const double T) const override virtual
Implements Saturation_base.
Definition at line 59 of file Saturation_constant.cpp.
{
  return psat_;
}
References psat_.
readOn()
Entree & Saturation_constant::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Saturation_base.
Definition at line 31 of file Saturation_constant.cpp.
{
  Param param(que_suis_je());
  param.ajouter("Tsat", &tsat_,Param::REQUIRED);
  param.ajouter("Psat", &psat_,Param::REQUIRED);
  param.ajouter("Lvap", &lvap_);
  param.ajouter("Hlsat", &hls_);
  param.ajouter("Hvsat", &hvs_);
  param.ajouter("tension_superficielle", &sigma__);
  param.lire_avec_accolades_depuis(is);
// verifications hlsat/hvsat/lvap
  const int i = (lvap_ > 0) + (hls_ > 0) + (hvs_ > 0);
  if (i != 2) Process::exit(que_suis_je() + " Please give 2 properties among {Lvap, Hlsat, Hvsat}");
  if (lvap_ > 0 && hls_ > 0) hvs_ = hls_ + lvap_;
  else if (lvap_ > 0 && hvs_ > 0) hls_ = hvs_ - lvap_;
  else if (hls_ > 0 && hvs_ > 0) lvap_ = hvs_ - hls_;
  else Process::exit(que_suis_je() + "bad parameters");
  return is;
}
References Param::ajouter(), Process::exit(), hls_, hvs_, Param::lire_avec_accolades_depuis(), lvap_, psat_, Objet_U::que_suis_je(), Param::REQUIRED, Interface_base::sigma__, and tsat_.
self_cast() [1/2]
const Saturation_constant & Saturation_constant::self_cast (const Objet_U & r) static
Definition at line 18 of file Saturation_constant.cpp.
self_cast() [2/2]
Saturation_constant & Saturation_constant::self_cast (Objet_U & r) static
Definition at line 18 of file Saturation_constant.cpp.
sigma_()
double Saturation_constant::sigma_ (const double T, const double P) const override virtual
Implements Interface_base.
Definition at line 96 of file Saturation_constant.cpp.
{
  if (sigma__ <= 0) Process::exit(que_suis_je() + ": expected positive value of the surface tension");
  return sigma__;
}
References Process::exit(), Objet_U::que_suis_je(), and Interface_base::sigma__.
taille_memoire()
unsigned Saturation_constant::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 18 of file Saturation_constant.cpp.
Tsat_()
double Saturation_constant::Tsat_ (const double P) const override virtual
Implements Saturation_base.
Definition at line 51 of file Saturation_constant.cpp.
{
  return tsat_;
}
References tsat_.
Member Data Documentation
hls_
double Saturation_constant::hls_ = - 1e+38 protected
Definition at line 38 of file Saturation_constant.h.
Referenced by Hls_(), and readOn().
hvs_
double Saturation_constant::hvs_ = - 1e+38 protected
Definition at line 38 of file Saturation_constant.h.
Referenced by Hvs_(), and readOn().
info_obj
const Type_info Saturation_constant::info_obj static
Definition at line 23 of file Saturation_constant.h.
lvap_
double Saturation_constant::lvap_ = - 1e+38 protected
Definition at line 38 of file Saturation_constant.h.
Referenced by Lvap_(), and readOn().
psat_
double Saturation_constant::psat_ = - 1e+38 protected
Definition at line 38 of file Saturation_constant.h.
Referenced by Psat_(), and readOn().
tsat_
double Saturation_constant::tsat_ = - 1e+38 protected
Definition at line 38 of file Saturation_constant.h.
Referenced by readOn(), and Tsat_().
The documentation for this class was generated from the following files:
src/ThHyd/Multiphase/Milieu/Saturation_constant.h
src/ThHyd/Multiphase/Milieu/Saturation_constant.cpp