TRUST: Op_Conv_EF_Stab_PolyMAC_Face Class Reference
Op_Conv_EF_Stab_PolyMAC_Face Class Reference
: class Op_Conv_EF_Stab_PolyMAC_Face
<Description of class Op_Conv_EF_Stab_PolyMAC_Face>
#include <Op_Conv_EF_Stab_PolyMAC_Face.h>
Public Member Functions
Op_Conv_EF_Stab_PolyMAC_Face ()
~Op_Conv_EF_Stab_PolyMAC_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
double calculer_dt_stab () const override
Calcul dt_stab.
int has_interface_blocs () const override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
void check_multiphase_compatibility () const override
void set_incompressible (const int flag) override
Public Member Functions inherited from Op_Conv_PolyMAC_base
Op_Conv_PolyMAC_base ()
~Op_Conv_PolyMAC_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
double calculer_dt_stab () const override
Calcul dt_stab.
DoubleTab & calculer (const DoubleTab &inco, DoubleTab &resu) const override
calcule la contribution de la convection, la range dans resu
renvoie resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_zone_cl_dis (const Zone_Cl_dis_base &) override
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_vitesse (const Champ_base &) override
Public Member Functions inherited from Operateur_Conv_base
Operateur_Conv_base ()
initialise dt_stab_conv a -123
~Operateur_Conv_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_vitesse (const Champ_base &vit)=0
double dt_stab_conv () const
void fixer_dt_stab_conv (double dt)
virtual void associer_norme_vitesse (const Champ_base &norme_vitesse)
virtual void associer_vitesse_pour_pas_de_temps (const Champ_base &vitesse)
virtual void set_incompressible (const int)
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Op_Conv_EF_Stab_PolyMAC_Face & self_cast (Objet_U &)
static const Op_Conv_EF_Stab_PolyMAC_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Conv_PolyMAC_base
static const Type_info * info ()
static Op_Conv_PolyMAC_base & self_cast (Objet_U &)
static const Op_Conv_PolyMAC_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Conv_base
static const Type_info * info ()
static Operateur_Conv_base & self_cast (Objet_U &)
static const Operateur_Conv_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Conv_PolyMAC_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Conv_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Op_Conv_PolyMAC_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Attributes
double alpha
DoubleVect porosite_f
DoubleVect porosite_e
Protected Attributes inherited from Op_Conv_PolyMAC_base
Ref_Zone_Poly_base la_zone_poly_
Ref_Zone_Cl_PolyMAC la_zcl_poly_
Ref_Champ_base vitesse_
SFichier Flux
SFichier Flux_moment
SFichier Flux_sum
Protected Attributes inherited from Operateur_Conv_base
Ref_Champ_base la_norme_vitesse
Ref_Champ_base vitesse_pour_pas_de_temps_
double dt_stab_conv_
int incompressible_ = 1
incompressible_= 1 -> l'operateur discretise div(v x inco), incompressible_ = 0 -> il discretise v.grad(inco)
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Additional Inherited Members
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
: class Op_Conv_EF_Stab_PolyMAC_Face
<Description of class Op_Conv_EF_Stab_PolyMAC_Face>
Definition at line 30 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
Constructor & Destructor Documentation
Op_Conv_EF_Stab_PolyMAC_Face()
Op_Conv_EF_Stab_PolyMAC_Face::Op_Conv_EF_Stab_PolyMAC_Face ()
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
~Op_Conv_EF_Stab_PolyMAC_Face()
Op_Conv_EF_Stab_PolyMAC_Face::~Op_Conv_EF_Stab_PolyMAC_Face ()
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Op_Conv_EF_Stab_PolyMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 165 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
{
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const Conds_lim& cls = la_zcl_poly_.valeur().les_conditions_limites();
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces(), &fcl = ch.fcl();
  const DoubleTab& vit = ch.passe(), &nf = zone.face_normales(), &vfd = zone.volumes_entrelaces_dir(), &xp = zone.xp(), &xv = zone.xv();
  const DoubleVect& fs = zone.face_surfaces(), &pe = porosite_e, &pf = porosite_f, &ve = zone.volumes();
  /* a_r : produit alpha_rho si Pb_Multiphase -> par semi_implicite, ou en recuperant le champ_conserve de l'equation de masse */
  const std::string& nom_inco = ch.le_nom().getString();
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const Masse_ajoutee_base *corr = pbm && pbm->has_correlation("masse_ajoutee") ? &ref_cast(Masse_ajoutee_base, pbm->get_correlation("masse_ajoutee").valeur()) : NULL;
  const DoubleTab& inco = semi_impl.count(nom_inco) ? semi_impl.at(nom_inco) : ch.valeurs(),
                   *a_r = !pbm ? NULL : semi_impl.count("alpha_rho") ? &semi_impl.at("alpha_rho") : &pbm->eq_masse.champ_conserve().valeurs(),
                    *alp = pbm ? &pbm->eq_masse.inconnue().passe() : NULL, &rho = equation().milieu().masse_volumique().passe();
  Matrice_Morse *mat = matrices.count(nom_inco) && !semi_impl.count(nom_inco) ? matrices.at(nom_inco) : NULL;
  int i, j, k, l, e, eb, f, fb, fc, fd, m, n, N = inco.line_size(), d, D = dimension, comp = !incompressible_;
  double mult;
  DoubleTrav dfac(2, N, N), masse(N, N);
  for (f = 0; f < zone.nb_faces_tot(); f++)
    if (f_e(f, 0) >= 0 && (f_e(f, 1) >= 0 || fcl(f, 0) == 1 || fcl(f, 0) == 3))
      {
        for (i = 0, dfac = 0; i < 2; i++)
          {
// masse : diagonale + masse ajoutee si correlation
            for (masse = 0, e = f_e(f, f_e(f, i) >= 0 ? i : 0), n = 0; n < N; n++) masse(n, n) = a_r ? (*a_r)(e, n) : 1;
            if (corr) corr->ajouter(&(*alp)(e, 0), &rho(e, 0), masse);
// contribution a dfac
            for (e = f_e(f, i), eb = f_e(f, i), n = 0; n < N; n++)
              for (m = 0; m < N; m++)
                dfac(fcl(f, 0) == 1 ? 0 : i, n, m) += fs(f) * vit(f, m) * pe(eb >= 0 ? eb : f_e(f, 0)) * masse(n, m)
                                                      * (1. + (vit(f, m) * (i ? -1 : 1) >= 0 ? 1. : vit(f, m) ? -1. : 0.) * alpha) / 2;
          }
        for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
          {
            for (k = 0; k < e_f.dimension(1) && (fb = e_f(e, k)) >= 0; k++)
              if (fb < zone.nb_faces())
                {
                  if ((fc = zone.equiv(f, i, k)) >= 0 || f_e(f, 1) < 0)
                    for (j = 0; j < 2; j++) //equivalence : face fd -> face fb
                      {
                        eb = f_e(f, j), fd = (j == i ? fb : fc); //element/face sources
                        mult = (fd < 0 || zone.dot(&nf(fb, 0), &nf(fd, 0)) > 0 ? 1 : -1) * (fd >= 0 ? pf(fd) / pe(eb) : 1); //multiplicateur pour passer de vf a ve
                        for (n = 0; n < N; n++)
                          for (m = 0; m < N; m++)
                            if (dfac(j, n, m))
{
                                double fac = (i ? -1 : 1) * vfd(fb, e != f_e(fb, 0)) * dfac(j, n, m) / ve(e);
                                if (fd >= 0) secmem(fb, n) -= fac * mult * inco(fd, m); //autre face calculee
                                else for (d = 0; d < D; d++)  //CL de Dirichlet
                                    secmem(fb, n) -= fac * nf(fb, d) / fs(fb) * ref_cast(Dirichlet, cls[fcl(f, 1)].valeur()).val_imp(fcl(f, 2), N * d + m);
                                if (comp) secmem(fb, n) += fac * inco(fb, m); //partie v div(alpha rho v)
                                if (!mat) continue;
                                if (fd >= 0) (*mat)(N * fb + n, N * fd + m) += fac * mult;
                                if (comp) (*mat)(N * fb + n, N * fb + m) -= fac;
                              }
                      }
                  else for (j = 0; j < 2; j++)  //pas d'equivalence : n_f * operateur aux elements
                      {
                        for (eb = f_e(f, j), l = 0; l < e_f.dimension(1) && (fc = e_f(eb, l)) >= 0; l++)
                          if (std::abs(fs(fc) * zone.dot(&xv(fc, 0), &nf(fb, 0), &xp(eb, 0))) > 1e-6 * ve(eb) * fs(fb))
                            for (n = 0; n < N; n++)
                              for (m = 0; m < N; m++)
                                if (dfac(j, n, m))
{
                                    double fac = (i ? -1 : 1) * vfd(fb, e != f_e(fb, 0)) * dfac(j, n, m) * (eb == f_e(fc, 0) ? 1 : -1) * fs(fc) * zone.dot(&xv(fc, 0), &nf(fb, 0), &xp(eb, 0)) / (ve(e) * ve(eb) * fs(fb));
                                    secmem(fb, n) -= fac * inco(fc, m);
                                    if (mat && fac) (*mat)(N * fb + n, N * fc + m) += fac;
                                  }
                        if (comp)
                          for (l = 0; l < e_f.dimension(1) && (fc = e_f(e, l)) >= 0; l++)
                            if (std::abs(fs(fc) * zone.dot(&xv(fc, 0), &nf(fb, 0), &xp(e, 0))) > 1e-6 * ve(e) * fs(fb))
                              for (n = 0; n < N; n++)
                                for (m = 0; m < N; m++)
                                  if (dfac(j, n, m))
{
                                      double fac = (i ? -1 : 1) * vfd(fb, e != f_e(fb, 0)) * dfac(j, n, m) * (e == f_e(fc, 0) ? 1 : -1) * fs(fc) * zone.dot(&xv(fc, 0), &nf(fb, 0), &xp(e, 0)) / (ve(e) * ve(e) * fs(fb));
                                      secmem(fb, n) += fac * inco(fc, m);
                                      if (mat && fac) (*mat)(N * fb + n, N * fc + m) -= fac;
                                    }
                      }
                }
          }
      }
}
References Masse_ajoutee_base::ajouter(), alpha, Equation_base::champ_conserve(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_Poly_base::dot(), Zone_VF::elem_faces(), Pb_Multiphase::eq_masse, MorEqn::equation(), Zone_Poly_base::equiv, Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), Pb_Multiphase::get_correlation(), Nom::getString(), Pb_Multiphase::has_correlation(), Operateur_Conv_base::incompressible_, Masse_Multiphase::inconnue(), Op_Conv_PolyMAC_base::la_zcl_poly_, Op_Conv_PolyMAC_base::la_zone_poly_, Field_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), Champ_Proto::passe(), Champ_Inc::passe(), Champ_Inc_base::passe(), porosite_e, porosite_f, ref_cast, sub_type, Ref_Zone_Poly_base::valeur(), Ref_Zone_Cl_PolyMAC::valeur(), Deriv_Correlation_base::valeur(), valeur(), Champ_Inc_base::valeurs(), Zone_VF::volumes(), Zone_Poly_base::volumes_entrelaces_dir(), Zone_VF::xp(), and Zone_VF::xv().
calculer_dt_stab()
double Op_Conv_EF_Stab_PolyMAC_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 91 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
{
  double dt = 1e10;
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face(), &ve = zone.volumes(), &pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces();
  const DoubleTab& vit = vitesse_->valeurs(), &vfd = zone.volumes_entrelaces_dir(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins(), &fcl = ch.fcl();
  int i, e, f, n, N = vit.line_size();
  DoubleTrav flux(N), vol(N); //somme des flux pf * |f| * vf, volume minimal des mailles d'elements/faces affectes par ce flux
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (vol = pe(e) * ve(e), flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++)
        for (n = 0; n < N; n++)
          {
            flux(n) += pf(f) * fs(f) * std::max((e == f_e(f, 1) ? 1 : -1) * vit(f, n), 0.); //seul le flux entrant dans e compte
            if (0 && fcl(f, 0) < 2) vol(n) = std::min(vol(n), pf(f) * vf(f) * vf(f) / vfd(f, e != f_e(f, 0))); //prise en compte de la contribution aux faces
          }
      for (n = 0; n < N; n++)
        if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) dt = std::min(dt, vol(n) / flux(n));
    }
  return Process::mp_min(dt);
}
References TRUSTTab< _TYPE_ >::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), Op_Conv_PolyMAC_base::la_zone_poly_, TRUSTVect< _TYPE_ >::line_size(), Process::mp_min(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Ref_Zone_Poly_base::valeur(), valeur(), Champ_Proto::valeurs(), Op_Conv_PolyMAC_base::vitesse_, Zone_VF::volumes(), Zone_VF::volumes_entrelaces(), and Zone_Poly_base::volumes_entrelaces_dir().
check_multiphase_compatibility()
void Op_Conv_EF_Stab_PolyMAC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Definition at line 48 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
{ }; //of course
completer()
void Op_Conv_EF_Stab_PolyMAC_Face::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Operateur_base.
Definition at line 78 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
{
  Op_Conv_PolyMAC_base::completer();
  /* au cas ou... */
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  zone.init_equiv();
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 2)
    Cerr << "Op_Conv_EF_Stab_PolyMAC_Face : largeur de joint insuffisante (minimum 2)!" << finl, Process::exit();
  porosite_f.ref(zone.porosite_face());
  porosite_e.ref(zone.porosite_elem());
}
References Cerr, Op_Conv_PolyMAC_base::completer(), Joint::epaisseur(), Process::exit(), finl, Zone_Poly_base::init_equiv(), Zone::joint(), Op_Conv_PolyMAC_base::la_zone_poly_, Zone::nb_joints(), porosite_e, Zone_VF::porosite_elem(), porosite_f, Zone_VF::porosite_face(), TRUSTVect< _TYPE_ >::ref(), Ref_Zone_Poly_base::valeur(), and Zone_dis_base::zone().
cree_instance()
Objet_U * Op_Conv_EF_Stab_PolyMAC_Face::cree_instance () static
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
dimensionner_blocs()
void Op_Conv_EF_Stab_PolyMAC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
Definition at line 118 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
{
  const Zone_Poly_base& zone = la_zone_poly_.valeur();
  const Champ_Face_PolyMAC& ch = ref_cast(Champ_Face_PolyMAC, equation().inconnue().valeur());
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces(), &fcl = ch.fcl();
  const DoubleTab& nf = zone.face_normales(), &inco = ch.valeurs(), &xp = zone.xp(), &xv = zone.xv();
  const DoubleVect& fs = zone.face_surfaces(), &ve = zone.volumes();
  const std::string& nom_inco = ch.le_nom().getString();
  if (!matrices.count(nom_inco) || semi_impl.count(nom_inco)) return; //pas de bloc diagonal ou semi-implicite -> rien a faire
  const Pb_Multiphase *pbm = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()) : NULL;
  const Masse_ajoutee_base *corr = pbm && pbm->has_correlation("masse_ajoutee") ? &ref_cast(Masse_ajoutee_base, pbm->get_correlation("masse_ajoutee").valeur()) : NULL;
  Matrice_Morse& mat = *matrices.at(nom_inco), mat2;
  int i, j, k, l, e, eb, f, fb, fc, m, n, N = equation().inconnue().valeurs().line_size();
  IntTab stencil(0, 2);
  stencil.set_smart_resize(1);
  /* agit uniquement aux elements; diagonale omise */
  for (f = 0; f < zone.nb_faces_tot(); f++)
    if (f_e(f, 0) >= 0 && (f_e(f, 1) >= 0 || fcl(f, 0) == 3))
      for (i = 0; i < 2 && (e = f_e(f, i)) >= 0; i++)
        for (j = 0; j < 2 && (eb = f_e(f, j)) >= 0; j++)
          {
            for (k = 0; k < e_f.dimension(1) && (fb = e_f(e, k)) >= 0; k++)
              if (fb < zone.nb_faces())
                {
                  if ((fc = zone.equiv(f, i, k)) >= 0) //equivalence : face -> face
                    for (n = 0; n < N; n++)
                      for (m = (corr ? 0 : n); m < (corr ? N : n + 1); m++) stencil.append_line(N * fb + n, N * fc + m);
                  else if (f_e(f, 1) >= 0)
                    for (l = 0; l < e_f.dimension(1) && (fc = e_f(eb, l)) >= 0; l++) //pas d'equivalence : faces de l'elem -> face
                      if(std::abs(fs(fc) * zone.dot(&xv(fc, 0), &nf(fb, 0), &xp(eb, 0))) > 1e-6 * ve(eb) * fs(fb))
                        for (n = 0; n < N; n++)
                          for (m = (corr ? 0 : n); m < (corr ? N : n + 1); m++)
                            stencil.append_line(N * fb + n, N * fc + m);
                }
          }
  tableau_trier_retirer_doublons(stencil);
  Matrix_tools::allocate_morse_matrix(inco.size_totale(), inco.size_totale(), stencil, mat2);
  mat.nb_colonnes() ? mat += mat2 : mat = mat2;
}
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_ >::append_line(), Zone_Poly_base::dot(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_Poly_base::equiv, Zone_Poly_base::face_normales(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_PolyMAC::fcl(), Pb_Multiphase::get_correlation(), Nom::getString(), Pb_Multiphase::has_correlation(), Equation_base::inconnue(), Op_Conv_PolyMAC_base::la_zone_poly_, Field_base::le_nom(), TRUSTVect< _TYPE_ >::line_size(), Matrice_Morse::nb_colonnes(), Zone_VF::nb_faces(), Zone_VF::nb_faces_tot(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), sub_type, tableau_trier_retirer_doublons(), Ref_Zone_Poly_base::valeur(), Deriv_Correlation_base::valeur(), valeur(), Champ_Inc::valeurs(), Champ_Inc_base::valeurs(), Zone_VF::volumes(), Zone_VF::xp(), and Zone_VF::xv().
duplique()
int Op_Conv_EF_Stab_PolyMAC_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Op_Conv_Amont_PolyMAC_Face, and Op_Conv_Centre_PolyMAC_Face.
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
get_info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Face, and Op_Conv_Centre_PolyMAC_Face.
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
has_interface_blocs()
int Op_Conv_EF_Stab_PolyMAC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Definition at line 41 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
  {
    return 1;
  };
info()
const Type_info * Op_Conv_EF_Stab_PolyMAC_Face::info () static
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
modifier_pour_Cl()
void Op_Conv_EF_Stab_PolyMAC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 37 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
{ };
printOn()
Sortie & Op_Conv_EF_Stab_PolyMAC_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Face, and Op_Conv_Centre_PolyMAC_Face.
Definition at line 37 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
{
  Op_Conv_PolyMAC_base::printOn( os );
  return os;
}
References Op_Conv_PolyMAC_base::printOn().
readOn()
Entree & Op_Conv_EF_Stab_PolyMAC_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
Reimplemented from Operateur_Conv_base.
Reimplemented in Op_Conv_Amont_PolyMAC_Face, and Op_Conv_Centre_PolyMAC_Face.
Definition at line 55 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
{
  Op_Conv_PolyMAC_base::readOn( is );
  Param param(que_suis_je());
  param.ajouter("alpha", &alpha);            //!< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
  param.lire_avec_accolades_depuis(is);
  return is;
}
References Param::ajouter(), alpha, Param::lire_avec_accolades_depuis(), Objet_U::que_suis_je(), and Op_Conv_PolyMAC_base::readOn().
self_cast() [1/2]
const Op_Conv_EF_Stab_PolyMAC_Face & Op_Conv_EF_Stab_PolyMAC_Face::self_cast (const Objet_U & r) static
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
self_cast() [2/2]
Op_Conv_EF_Stab_PolyMAC_Face & Op_Conv_EF_Stab_PolyMAC_Face::self_cast (Objet_U & r) static
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
set_incompressible()
void Op_Conv_EF_Stab_PolyMAC_Face::set_incompressible (const int flag) inline override virtual
Reimplemented from Operateur_Conv_base.
Definition at line 49 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
  {
    incompressible_ = flag;
  }
References Operateur_Conv_base::incompressible_.
taille_memoire()
unsigned Op_Conv_EF_Stab_PolyMAC_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Op_Conv_Amont_PolyMAC_Face, and Op_Conv_Centre_PolyMAC_Face.
Definition at line 32 of file Op_Conv_EF_Stab_PolyMAC_Face.cpp.
Member Data Documentation
alpha
double Op_Conv_EF_Stab_PolyMAC_Face::alpha protected
Definition at line 55 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
Referenced by ajouter_blocs(), readOn(), Op_Conv_Amont_PolyMAC_Face::readOn(), and Op_Conv_Centre_PolyMAC_Face::readOn().
info_obj
const Type_info Op_Conv_EF_Stab_PolyMAC_Face::info_obj static
Definition at line 33 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
porosite_e
DoubleVect Op_Conv_EF_Stab_PolyMAC_Face::porosite_e protected
Definition at line 56 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
Referenced by ajouter_blocs(), and completer().
porosite_f
DoubleVect Op_Conv_EF_Stab_PolyMAC_Face::porosite_f protected
Definition at line 56 of file Op_Conv_EF_Stab_PolyMAC_Face.h.
Referenced by ajouter_blocs(), and completer().
The documentation for this class was generated from the following files:
src/PolyMAC/Operateurs/Op_Conv_EF_Stab_PolyMAC_Face.h
src/PolyMAC/Operateurs/Op_Conv_EF_Stab_PolyMAC_Face.cpp