TRUST: Raffiner_anisotrope Class Reference
Raffiner_anisotrope Class Reference
#include <Raffiner_anisotrope.h>
Public Member Functions
Raffiner_anisotrope ()
~Raffiner_anisotrope ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &)
void Raffiner_anisotrope_ (Zone &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Raffiner_anisotrope & self_cast (Objet_U &)
static const Raffiner_anisotrope & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
Definition at line 41 of file Raffiner_anisotrope.h.
Constructor & Destructor Documentation
Raffiner_anisotrope::Raffiner_anisotrope ()
Definition at line 26 of file Raffiner_anisotrope.cpp.
Raffiner_anisotrope::~Raffiner_anisotrope ()
Definition at line 26 of file Raffiner_anisotrope.cpp.
Member Function Documentation
Objet_U * Raffiner_anisotrope::cree_instance () [static]
Reimplemented from Interprete.
Definition at line 26 of file Raffiner_anisotrope.cpp.
int Raffiner_anisotrope::duplique () const [virtual]
Implements Interprete_geometrique_base.
Definition at line 26 of file Raffiner_anisotrope.cpp.
const Type_info * Raffiner_anisotrope::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Raffiner_anisotrope.cpp.
const Type_info * Raffiner_anisotrope::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Raffiner_anisotrope.cpp.
Entree & Raffiner_anisotrope::interpreter_ (Entree & is) [virtual]
Implements Interprete_geometrique_base.
Definition at line 38 of file Raffiner_anisotrope.cpp.
References Interprete_geometrique_base::associer_domaine(), Cerr, Objet_U::dimension, Interprete_geometrique_base::domaine(), Process::exit(), finl, Scatter::init_sequential_domain(), Domaine::nb_zones(), Raffiner_anisotrope_(), and Scatter::uninit_sequential_domain().
{
  if (dimension == 2)
    {
      Cerr << "Refinement of each element into 3 new triangles... " <<finl;
    }
  else if (dimension == 3)
    {
      Cerr << "Refinement of each element into 4 new tetrahedra... " <<finl;
    }
  else
    {
      Cerr << "we can not refine in dimension " << dimension <<finl;
      exit();
    }
  associer_domaine(is);
  Scatter::uninit_sequential_domain(domaine());
  for(int i=0; i<domaine().nb_zones() ; i++)
    {
      Raffiner_anisotrope_(domaine().zone(i));
    }
  Scatter::init_sequential_domain(domaine());
  Cerr << "Refinement... OK" << finl;
  return is;
}
Sortie & Raffiner_anisotrope::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 28 of file Raffiner_anisotrope.cpp.
{
  return Interprete::printOn(os);
}
void Raffiner_anisotrope::Raffiner_anisotrope_ (Zone & zone)
Definition at line 65 of file Raffiner_anisotrope.cpp.
References Elem_geom::calculer_centres_gravite(), Cerr, Objet_U::dimension, DoubleTab::dimension(), IntTab::dimension(), Zone::domaine(), Process::exit(), finl, Zone::invalide_octree(), Zone::les_elems(), Domaine::les_sommets(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Zone::nb_som(), Objet_U::que_suis_je(), IntTab::ref(), DoubleTab::resize(), Zone::type_elem(), and Zone::typer().
Referenced by interpreter_().
{
  if  ((zone.type_elem()->que_suis_je() == "Triangle")
       ||(zone.type_elem()->que_suis_je() == "Tetraedre"))
    {
      Domaine& dom=zone.domaine();
      IntTab& les_elems=zone.les_elems();
      int oldsz=les_elems.dimension(0);
      DoubleTab& sommets=dom.les_sommets();
      int cpt=sommets.dimension(0);
      {
        DoubleTab sommets_ajoutes(oldsz, dimension);
        zone.type_elem()->calculer_centres_gravite(sommets_ajoutes);
        sommets.resize(cpt+oldsz, dimension);
        for(int i=0; i<oldsz; i++)
          for(int j=0; j<dimension; j++)
            sommets(cpt+i,j)=sommets_ajoutes(i,j);
      }
      zone.typer(zone.type_elem()->que_suis_je());
      IntTab new_elems((dimension+1)*oldsz, dimension+1);
      if(dimension==2)
        {
          for(int i=0; i< oldsz; i++)
            {
              new_elems(i  , 0) = i+cpt;
              new_elems(i  , 1) = les_elems(i,0);
              new_elems(i  , 2) = les_elems(i,1);
              new_elems(i+oldsz, 0) = i+cpt;
              new_elems(i+oldsz, 1) = les_elems(i,0);
              new_elems(i+oldsz, 2) = les_elems(i,2);
              mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
              new_elems(i+2*oldsz, 0) = i+cpt;
              new_elems(i+2*oldsz, 1) = les_elems(i,1);
              new_elems(i+2*oldsz, 2) = les_elems(i,2);
              mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
            }
        }
      else
        {
          for(int i=0; i< oldsz; i++)
            {
              new_elems(i  , 0) = i+cpt;
              new_elems(i  , 1) = les_elems(i,0);
              new_elems(i  , 2) = les_elems(i,1);
              new_elems(i  , 3) = les_elems(i,2);
              new_elems(i+oldsz, 0) = i+cpt;
              new_elems(i+oldsz, 1) = les_elems(i,0);
              new_elems(i+oldsz, 2) = les_elems(i,1);
              new_elems(i+oldsz, 3) = les_elems(i,3);
              mettre_a_jour_sous_zone(zone,i,i+oldsz,1);
              new_elems(i+2*oldsz, 0) = i+cpt;
              new_elems(i+2*oldsz, 1) = les_elems(i,0);
              new_elems(i+2*oldsz, 2) = les_elems(i,2);
              new_elems(i+2*oldsz, 3) = les_elems(i,3);
              mettre_a_jour_sous_zone(zone,i,i+2*oldsz,1);
              new_elems(i+3*oldsz, 0) = i+cpt;
              new_elems(i+3*oldsz, 1) = les_elems(i,1);
              new_elems(i+3*oldsz, 2) = les_elems(i,2);
              new_elems(i+3*oldsz, 3) = les_elems(i,3);
              mettre_a_jour_sous_zone(zone,i,i+3*oldsz,1);
            }
        }
      les_elems.ref(new_elems);
// Reconstruction de l'octree
      if (dimension == 2)
        Cerr << "We have split the triangles ..." << finl;
      else
        Cerr << "We have split the tetrahedra ..." << finl;
      zone.invalide_octree();
      Cerr<<"END of Raffiner_anisotrope..."<<finl;
      Cerr<<"  1 NbElem="<<zone.les_elems().dimension(0)<<"  NbNod="<<zone.nb_som()<<finl;
    }
  else
    {
      Cerr << "We do not yet know how to Raffiner_anisotrope the "
           << zone.type_elem()->que_suis_je() <<"s"<<finl;
      exit();
    }
}
Entree & Raffiner_anisotrope::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 33 of file Raffiner_anisotrope.cpp.
{
  return Interprete::readOn(is);
}
const Raffiner_anisotrope & Raffiner_anisotrope::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Raffiner_anisotrope.cpp.
Raffiner_anisotrope & Raffiner_anisotrope::self_cast (Objet_U & r) [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 26 of file Raffiner_anisotrope.cpp.
unsigned Raffiner_anisotrope::taille_memoire () const [virtual]
Reimplemented from Interprete.
Definition at line 26 of file Raffiner_anisotrope.cpp.
Member Data Documentation
const Type_info Raffiner_anisotrope::info_obj [static]
Reimplemented from Interprete_geometrique_base.
Definition at line 43 of file Raffiner_anisotrope.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raffiner_anisotrope.h
src/Kernel/Geometrie/Raffiner_anisotrope.cpp