TRUST: Source_Scalaire_EF Class Reference
Source_Scalaire_EF Class Reference
class Source_Scalaire_EF
#include <Source_Scalaire_EF.h>
Public Member Functions
Source_Scalaire_EF ()
~Source_Scalaire_EF ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &)
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
void mettre_a_jour (double)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Source_Scalaire_EF & self_cast (Objet_U &)
static const Source_Scalaire_EF & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Zone_EF la_zone_EF
Champ_Don la_source_
Champ_Don la_source_lu_
Detailed Description
class Source_Scalaire_EF
See also:
Source_base
Definition at line 42 of file Source_Scalaire_EF.h.
Constructor & Destructor Documentation
Source_Scalaire_EF::Source_Scalaire_EF ()
Definition at line 35 of file Source_Scalaire_EF.cpp.
Source_Scalaire_EF::~Source_Scalaire_EF ()
Definition at line 35 of file Source_Scalaire_EF.cpp.
Member Function Documentation
DoubleTab & Source_Scalaire_EF::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 93 of file Source_Scalaire_EF.cpp.
References MorEqn::equation(), Equation_base::inconnue(), Zone_EF::IPhi(), la_source_, la_zone_EF, Zone::les_elems(), Field_base::nb_comp(), Zone::nb_elem_tot(), Zone::nb_som_elem(), sub_type, Deriv_Champ_Don_base::valeur(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_EF::valeur(), Champ_Don_base::valeurs(), and Zone_dis_base::zone().
Referenced by calculer().
{
  const Zone_EF& zone_EF = la_zone_EF.valeur();
  int ncomp=equation().inconnue().valeur().nb_comp();
  const IntTab& elems= zone_EF.zone().les_elems() ;
  int nb_som_elem=zone_EF.zone().nb_som_elem();
  int nb_elems=zone_EF.zone().nb_elem_tot();
// Attention calcul IPhi *S(e)
// const DoubleTab& IPhi_thilde=zone_EF.IPhi_thilde();
  const DoubleTab& IPhi=zone_EF.IPhi();
  int is_source_unif=0;
  if (sub_type(Champ_Uniforme,la_source_.valeur()))
    is_source_unif=1;
  const DoubleTab& tab_source=la_source_.valeur().valeurs();
  if (ncomp>1)
    for (int num_elem=0; num_elem<nb_elems; num_elem++)
      for (int comp=0; comp<ncomp; comp++)
        {
          double source ;
          int cc=0;
          if (!is_source_unif) cc=num_elem;
          source=tab_source(cc,comp);
          for (int i=0; i<nb_som_elem; i++)
            resu(elems(num_elem,i),comp)+=source*IPhi(num_elem,i);
        }
  else
    {
      for (int num_elem=0; num_elem<nb_elems; num_elem++)
        {
          double source ;
          if (!is_source_unif)
            source=tab_source(num_elem);
          else
            source=tab_source(0,0);
          for (int i=0; i<nb_som_elem; i++)
            resu(elems(num_elem,i))+=source*IPhi(num_elem,i);
        }
    }
  return resu;
}
void Source_Scalaire_EF::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 50 of file Source_Scalaire_EF.cpp.
{ }
void Source_Scalaire_EF::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 85 of file Source_Scalaire_EF.cpp.
References la_zone_EF, ref_cast, and Deriv_Zone_dis_base::valeur().
{
  la_zone_EF = ref_cast(Zone_EF, zone_dis.valeur());
// la_zone_Cl_EF = ref_cast(Zone_Cl_EF, zone_Cl_dis.valeur());
}
DoubleTab & Source_Scalaire_EF::calculer (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 142 of file Source_Scalaire_EF.cpp.
References ajouter().
{
  resu = 0;
  return ajouter(resu);
}
Objet_U * Source_Scalaire_EF::cree_instance () [static]
Definition at line 35 of file Source_Scalaire_EF.cpp.
int Source_Scalaire_EF::duplique () const [virtual]
Implements Source_base.
Definition at line 35 of file Source_Scalaire_EF.cpp.
const Type_info * Source_Scalaire_EF::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 35 of file Source_Scalaire_EF.cpp.
const Type_info * Source_Scalaire_EF::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 35 of file Source_Scalaire_EF.cpp.
void Source_Scalaire_EF::mettre_a_jour (double temps) [virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 148 of file Source_Scalaire_EF.cpp.
References la_source_, and Champ_Don::mettre_a_jour().
{
  la_source_->mettre_a_jour(temps);
}
Sortie & Source_Scalaire_EF::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 42 of file Source_Scalaire_EF.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Source_Scalaire_EF::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 51 of file Source_Scalaire_EF.cpp.
References Champ_base::affecter(), Champs_compris::ajoute_champ(), Cerr, Source_base::champs_compris_, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), Process::exit(), finl, Equation_base::inconnue(), la_source_, la_source_lu_, Field_base::nb_comp(), Champ_Don::nb_comp(), Discretisation_base::nommer_completer_champ_physique(), Equation_base::probleme(), Objet_U::que_suis_je(), sub_type, Deriv_::typer(), Deriv_Champ_Inc_base::valeur(), and Deriv_Champ_Don_base::valeur().
{
  s >> la_source_lu_;
  const  Probleme_base& pb =equation().probleme();
  if (sub_type(Champ_Uniforme,la_source_lu_.valeur()))
    {
      la_source_.typer(la_source_lu_.valeur().que_suis_je());
      la_source_.valeur()=la_source_lu_.valeur();
    }
// else if (sub_type(Champ_couplage_primaire_secondaire,la_source_lu_.valeur()))
  else if (la_source_lu_.valeur().que_suis_je()=="Champ_couplage_primaire_secondaire")
    {
      la_source_=la_source_lu_;
    }
  else
    {
      equation().discretisation().discretiser_champ("champ_elem",equation().zone_dis(),"source",",",1,0.,la_source_);
      la_source_.valeur().affecter(la_source_lu_);
      la_source_lu_.detach();
    }
// const Equation_base& eqn = pb.equation(0);
  equation().discretisation().nommer_completer_champ_physique(equation().zone_dis(),"Puissance_volumique","W/m3",la_source_,pb);
  champs_compris_.ajoute_champ(la_source_);
  if (la_source_->nb_comp() != equation().inconnue().valeur().nb_comp())
    {
      Cerr << "Erreur a la lecture du terme source de type " << que_suis_je() << finl;
      Cerr << "le champ source doit avoir " << equation().inconnue().valeur().nb_comp() << " composantes" << finl;
      exit();
    }
  return s;
}
Source_Scalaire_EF & Source_Scalaire_EF::self_cast (Objet_U & r) [static]
Reimplemented from Source_base.
Definition at line 35 of file Source_Scalaire_EF.cpp.
const Source_Scalaire_EF & Source_Scalaire_EF::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_base.
Definition at line 35 of file Source_Scalaire_EF.cpp.
unsigned Source_Scalaire_EF::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 35 of file Source_Scalaire_EF.cpp.
Member Data Documentation
const Type_info Source_Scalaire_EF::info_obj [static]
Reimplemented from Source_base.
Definition at line 45 of file Source_Scalaire_EF.h.
Champ_Don Source_Scalaire_EF::la_source_ [protected]
Definition at line 60 of file Source_Scalaire_EF.h.
Referenced by ajouter(), mettre_a_jour(), and readOn().
Champ_Don Source_Scalaire_EF::la_source_lu_ [protected]
Definition at line 60 of file Source_Scalaire_EF.h.
Referenced by readOn().
Ref_Zone_EF Source_Scalaire_EF::la_zone_EF [protected]
Definition at line 56 of file Source_Scalaire_EF.h.
Referenced by ajouter(), and associer_zones().
The documentation for this class was generated from the following files:
src/EF/Sources/Source_Scalaire_EF.h
src/EF/Sources/Source_Scalaire_EF.cpp