TRUST: ILU Class Reference
ILU Class Reference
#include <ILU.h>
Public Member Functions
ILU ()
~ILU ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int a_un_interet ()
int type_precond ()
Public Member Functions inherited from Precond_base
~Precond_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Precond_base ()
void reinit (Init_Status x=REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
void set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
void prepare (const Matrice_Base &, const DoubleVect &src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
virtual int supporte_matrice_morse_sym ()
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Init_Status get_status ()
virtual int get_flag_updated_input () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static ILU & self_cast (Objet_U &)
static const ILU & self_cast (const Objet_U &)
Static Public Member Functions inherited from Precond_base
static const Type_info * info ()
static Precond_base & self_cast (Objet_U &)
static const Precond_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Precond_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Types
enum Type_Precond { PRECOND_NUL = 0 , PRECOND_GAUCHE = 1 , PRECOND_DROITE = 2 , PRECOND_GAUCHE_DROITE = 3 }
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void prepare_ (const Matrice_Base &, const DoubleVect &) override
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
int preconditionner_ (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
Calcule la solution du systeme lineaire: A * solution = b
avec la methode de relaxation ILU.
int factorisation (const Matrice_Morse &, const DoubleVect &secmem)
virtual int factoriser (const Matrice_Morse &, const DoubleVect &)
int ilu (int, const DoubleVect &, DoubleVect &)
int ilut (int, const DoubleVect &, DoubleVect &)
Protected Member Functions inherited from Precond_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)=0
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
ArrOfInt ju
tableau pour L et U
ArrOfDouble alu
tableau pour L et U
ArrOfInt jlu
tableau pour L et U
int precond_
Flag pour le preconditionnement ILU.
int lfil_
Parametre de remplissage pour ilut.
Matrice_Morse MLOC
Protected Attributes inherited from Precond_base
int echange_ev_solution_
Additional Inherited Members
Public Types inherited from Precond_base
enum Init_Status { READY = 0 , REINIT_COEFF = 1 , REINIT_ALL = 2 }
Detailed Description
Definition at line 25 of file ILU.h.
Member Enumeration Documentation
Type_Precond
enum ILU::Type_Precond protected
Enumerator
PRECOND_NUL
PRECOND_GAUCHE
PRECOND_DROITE
PRECOND_GAUCHE_DROITE
Definition at line 43 of file ILU.h.
{ PRECOND_NUL = 0, PRECOND_GAUCHE = 1, PRECOND_DROITE = 2, PRECOND_GAUCHE_DROITE = 3};
Constructor & Destructor Documentation
ILU()
ILU::ILU ()
Definition at line 22 of file ILU.cpp.
~ILU()
ILU::~ILU ()
Definition at line 22 of file ILU.cpp.
Member Function Documentation
a_un_interet()
int ILU::a_un_interet () inline
Definition at line 29 of file ILU.h.
{ return 1; }
cree_instance()
Objet_U * ILU::cree_instance () static
Definition at line 22 of file ILU.cpp.
duplique()
int ILU::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file ILU.cpp.
factorisation()
int ILU::factorisation (const Matrice_Morse & mat, const DoubleVect & secmem) protected
Definition at line 183 of file ILU.cpp.
{
  if (nproc()==1)
    {
      return factoriser(mat,secmem);
    }
  if(1)
    {
// dimensionnenment de la matrice MLOC
      int n_reel = secmem.size();
// int n_tot = secmem.size_array();
      MLOC.dimensionner(n_reel,0);
      int ii,jj;
      int cpt=0;
      const IntVect& tab1_tot = mat.get_tab1();
      const IntVect& tab2_tot = mat.get_tab2();
// const DoubleVect& coeff_tot = mat.get_set_coeff();
      IntVect& tab1_reel = MLOC.get_set_tab1();
      IntVect& tab2_reel = MLOC.get_set_tab2();
// DoubleVect& coeff_reel = MLOC.get_set_coeff();
      tab1_reel(0)=1;
      for(ii=0; ii<n_reel; ii++)
        {
          int dl = tab1_tot(ii);
          int fl = tab1_tot(ii+1);
          for(jj=dl; jj<fl; jj++)
            {
              if(tab2_tot(jj-1)<=n_reel)
                cpt++;
            }
          tab1_reel(ii+1)=cpt+1;
        }
      MLOC.dimensionner(n_reel,tab1_reel(n_reel)-1);
      cpt=0;
      for(ii=0; ii<n_reel; ii++)
        {
          int dl = tab1_tot(ii);
          int fl = tab1_tot(ii+1);
          for(jj=dl; jj<fl; jj++)
            {
              if(tab2_tot(jj-1)<=n_reel)
                {
                  tab2_reel(cpt++)=tab2_tot(jj-1);
// coeff_reel(cpt++)=coeff_tot(jj-1);
                }
            }
        }
    }
// copie des coeffs
  {
    int ii,jj;
    int cpt=0;
    int n_reel = secmem.size();
    const IntVect& tab1_tot = mat.get_tab1();
    const IntVect& tab2_tot = mat.get_tab2();
    const DoubleVect& coeff_tot = mat.get_coeff();
// IntVect& tab1_reel = MLOC.get_set_tab1();
// IntVect& tab2_reel = MLOC.get_set_tab2();
    DoubleVect& coeff_reel = MLOC.get_set_coeff();
    for(ii=0; ii<n_reel; ii++)
      {
        int dl = tab1_tot(ii);
        int fl = tab1_tot(ii+1);
        for(jj=dl; jj<fl; jj++)
          {
            if(tab2_tot(jj-1)<=n_reel)
              {
// tab2_reel(cpt)=tab2_tot(jj-1);
                coeff_reel(cpt++)=coeff_tot(jj-1);
              }
          }
      }
  }
  return factoriser(MLOC,secmem);
}
References Matrice_Morse::dimensionner(), factoriser(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), MLOC, Process::nproc(), and TRUSTVect< _TYPE_ >::size().
Referenced by prepare_().
factoriser()
int ILU::factoriser (const Matrice_Morse & mat, const DoubleVect & b) protected virtual
< niveau d'erreur
< nombre de termes non nuls dans LU
< filtrage des coefficents de L U ArrOfDouble wu(n1+1); // tableau de travail pour ilut ArrOfDouble wl(n1); // tableau de travail pour ilut ArrOfInt jr(n1); // tableau de travail pour ilut ArrOfInt jwu(n1); // tableau de travail pour ilut ArrOfInt jwl(n1); // tableau de travail pour ilut F77NAME(ILUT)(&n1, mat.coeff_, mat.tab2_, mat.tab1_, &lfil_, &to, alu.addr(), jlu.addr(), ju.addr(), &iw, wu.addr(), wl.addr(), jr.addr(), jwl.addr(), jwu.addr(), &ie);
Definition at line 119 of file ILU.cpp.
{
  int ie=1;                                //!< niveau d'erreur
  if (precond_!=0)
    {
      int n1 = mat.nb_lignes();
      int n2 = mat.nb_coeff()+(2*lfil_*n1);        //!< nombre de termes non nuls dans LU
// Cerr<<"Calculation of matrix preconditioning by LU decomposition..."<<finl;
      int  iw = n2 + 2;
      ju.resize_array(n1+1);
      jlu.resize_array(iw);
      alu.resize_array(iw);
      double to = 1.e-4;                //!< filtrage des coefficents de L U   ArrOfDouble wu(n1+1);                // tableau de travail pour ilut ArrOfDouble wl(n1);                // tableau de travail pour ilut ArrOfInt jr(n1);                        // tableau de travail pour ilut ArrOfInt jwu(n1);                        // tableau de travail pour ilut ArrOfInt jwl(n1);                        // tableau de travail pour ilut       F77NAME(ILUT)(&n1, mat.coeff_, mat.tab2_, mat.tab1_, &lfil_,                     &to, alu.addr(), jlu.addr(), ju.addr(),                     &iw, wu.addr(),                     wl.addr(), jr.addr(), jwl.addr(), jwu.addr(), &ie);
//
//
//
//
//
//
//
//
//
      ArrOfDouble wbis(n1+1);
      ArrOfInt jwbis(2*n1);
      F77NAME(ILUTV2)(&n1, mat.get_coeff().addr(), mat.get_tab2().addr(), mat.get_tab1().addr(), &lfil_,
                      &to, alu.addr(), jlu.addr(), ju.addr(),
                      &iw, wbis.addr(),
                      jwbis.addr(), &ie);
      switch(ie)
        {
        case 0 :
          break;
        case -1 :
          Cerr << "Error in ilut 'matrix may be wrong' dixit SAAD" << finl;
          exit();
          break;
        case  -2  :
          Cerr << "Error in ilut : overflow in L " << finl;
          exit();
          break;
        case   -3  :
          Cerr << "Error in ilut : overflow in U " << finl;
          exit();
          break;
        case    -4   :
          Cerr << "Illegal value for lfil : it may be a memory trouble " << finl;
          exit();
          break;
        case    -5  :
          Cerr << "Empty line met " << finl;
          exit();
          break;
        default :
          Cerr << "Pivot null met ! at step " << ie << finl;;
          exit();
        }
    }
  return 0;
}
References TRUSTArray< _TYPE_ >::addr(), alu, Cerr, Process::exit(), F77NAME, finl, Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), ILUTV2(), jlu, ju, lfil_, Matrice_Morse::nb_coeff(), Matrice_Morse::nb_lignes(), precond_, and TRUSTArray< _TYPE_ >::resize_array().
Referenced by factorisation().
get_info()
const Type_info * ILU::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 22 of file ILU.cpp.
ilu()
int ILU::ilu (int n, const DoubleVect & u, DoubleVect & s) protected
Definition at line 262 of file ILU.cpp.
{
  F77NAME(LUSOLV2)(&n,u.addr(),s.addr(),alu.addr(),jlu.addr(),ju.addr());
  return 1;
}
References TRUSTArray< _TYPE_ >::addr(), alu, F77NAME, jlu, ju, and LUSOLV2().
Referenced by preconditionner_().
ilut()
int ILU::ilut (int n, const DoubleVect & u, DoubleVect & s) protected
Definition at line 268 of file ILU.cpp.
{
  F77NAME(LUTSOLV2)(&n,u.addr(),s.addr(),alu.addr(),jlu.addr(),ju.addr());
  return 1;
}
References TRUSTArray< _TYPE_ >::addr(), alu, F77NAME, jlu, ju, and LUTSOLV2().
info()
const Type_info * ILU::info () static
Definition at line 22 of file ILU.cpp.
preconditionner_()
int ILU::preconditionner_ (const Matrice_Base & la_matrice, const DoubleVect & u, DoubleVect & s) override protected virtual
Calcule la solution du systeme lineaire: A * solution = b
avec la methode de relaxation ILU.
Implements Precond_base.
Definition at line 111 of file ILU.cpp.
{
  int n = u.size();
  return ilu(n,u,s);
}
References ilu(), and TRUSTVect< _TYPE_ >::size().
prepare_()
void ILU::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
Definition at line 62 of file ILU.cpp.
{
  if (get_status() != READY)
    {
      if(sub_type(Matrice_Morse_Sym,la_matrice))
        {
          Cerr<<"ILU ERROR : one is not able to carry out a ILU preconditioning"
              <<" on a symetric matrix"<<finl;
          exit();
        }
      else if(sub_type(Matrice_Morse,la_matrice))
        {
          const Matrice_Morse& m = ref_cast(Matrice_Morse,la_matrice);
          factorisation(m, v);
        }
      else if(sub_type(Matrice_Bloc,la_matrice))
        {
          const Matrice_Bloc& matrice = ref_cast(Matrice_Bloc,la_matrice);
          const Matrice& bloc0 = matrice.get_bloc(0,0);
          if(sub_type(Matrice_Morse_Sym,bloc0.valeur()))
            {
              /*
                Cerr<<"ILU ERROR : one is not able to carry out a ILU preconditioning"
                <<" on a symetric matrix"<<finl;
                exit();
              */
              const Matrice_Morse_Sym ms=ref_cast(Matrice_Morse_Sym,bloc0.valeur());
              Matrice_Morse m2;
              MorseSymToMorse(ms,m2);
              factorisation(m2,v);
            }
          else if(sub_type(Matrice_Morse,bloc0.valeur()))
            {
              const Matrice_Morse& m = ref_cast(Matrice_Morse,bloc0.valeur());
              factorisation(m, v);
            }
        }
      else
        {
          Cerr<<"ILU : Warning : preconditioning can be carry out only for linear systems based on Matrice_Morse or Matrice_Bloc type matrixes"<<finl;
          exit();
        }
    }
  Precond_base::prepare_(la_matrice, v);
}
References Cerr, Process::exit(), factorisation(), finl, Matrice_Bloc::get_bloc(), Precond_base::get_status(), m2, MorseSymToMorse(), Precond_base::prepare_(), Precond_base::READY, ref_cast, sub_type, and Deriv_Matrice_Base::valeur().
printOn()
Sortie & ILU::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 26 of file ILU.cpp.
{
  s << " { type "<<precond_ ;
  s << " filling "<< lfil_ << " } " ;
  return s;
}
References lfil_, and precond_.
readOn()
Entree & ILU::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 33 of file ILU.cpp.
{
  precond_ = _TYPE_ILU_;
  lfil_ = _LFIL_ILU_;
  Param param(que_suis_je());
  param.ajouter("type", &precond_, Param::OPTIONAL);
  param.dictionnaire("0", PRECOND_NUL);
  param.dictionnaire("1", PRECOND_GAUCHE);
  param.dictionnaire("2", PRECOND_DROITE);
  param.dictionnaire("3", PRECOND_GAUCHE_DROITE);
  param.ajouter("filling", &lfil_, Param::OPTIONAL);
  param.lire_avec_accolades(is);
  return is;
}
References _LFIL_ILU_, _TYPE_ILU_, Param::ajouter(), Param::dictionnaire(), lfil_, Param::lire_avec_accolades(), Param::OPTIONAL, precond_, PRECOND_DROITE, PRECOND_GAUCHE, PRECOND_GAUCHE_DROITE, PRECOND_NUL, and Objet_U::que_suis_je().
self_cast() [1/2]
const ILU & ILU::self_cast (const Objet_U & r) static
Definition at line 22 of file ILU.cpp.
self_cast() [2/2]
ILU & ILU::self_cast (Objet_U & r) static
Definition at line 22 of file ILU.cpp.
taille_memoire()
unsigned ILU::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file ILU.cpp.
type_precond()
int ILU::type_precond () inline
Definition at line 30 of file ILU.h.
{ return precond_; }
References precond_.
Referenced by Solv_Gen::solve().
Member Data Documentation
alu
ArrOfDouble ILU::alu protected
tableau pour L et U
Definition at line 41 of file ILU.h.
Referenced by factoriser(), ilu(), and ilut().
info_obj
const Type_info ILU::info_obj static
Definition at line 27 of file ILU.h.
jlu
ArrOfInt ILU::jlu protected
tableau pour L et U
Definition at line 42 of file ILU.h.
Referenced by factoriser(), ilu(), and ilut().
ju
ArrOfInt ILU::ju protected
tableau pour L et U
Definition at line 40 of file ILU.h.
Referenced by factoriser(), ilu(), and ilut().
lfil_
int ILU::lfil_ protected
Parametre de remplissage pour ilut.
Definition at line 45 of file ILU.h.
Referenced by factoriser(), printOn(), and readOn().
MLOC
Matrice_Morse ILU::MLOC protected
Definition at line 46 of file ILU.h.
Referenced by factorisation().
precond_
int ILU::precond_ protected
Flag pour le preconditionnement ILU.
Definition at line 44 of file ILU.h.
Referenced by factoriser(), printOn(), readOn(), and type_precond().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/ILU.h
src/Kernel/Math/SolvSys/ILU.cpp