TRUST: Assembleur_P_VDF Class Reference
Assembleur_P_VDF Class Reference
#include <Assembleur_P_VDF.h>
Public Member Functions
Assembleur_P_VDF ()
~Assembleur_P_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
Assemblage de la matrice de pression M telle que
M*P = div(porosite * grad (P))
et calcul des coefficients pour modifier_secmem.
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Assemblage de la matrice de pression M telle que
M*P = div(porosite/rho * grad (P))
et calcul des coefficients pour modifier_secmem.
Parametre: matrice
Signification: La matrice a assembler.
Contrainte: Soit la matrice n'est pas encore typee (alors on la "construit"),
soit c'est la meme que lors de l'appel precedent.
Parametre: rho
Contrainte: Doit etre un champ de type Champ_Fonc_Face.
int assembler_QC (const DoubleTab &, Matrice &) override
Assemble la matrice de pression pour un fluide quasi compressible.
La matrice M est telle que M*P = div(porosite * grad(P)).
Le drapeau resoudre_increment_pression est mis a zero s'il n'a pas
encore ete assigne.
int modifier_secmem (DoubleTab &) override
Modification du second membre pour appliquer les conditions aux limites.
Les conditions prises en charge sont
Neumann_sortie_libre,
Entree_fluide_vitesse_imposee,
Dirichlet_paroi_defilante (rien a faire),
Dirichlet_paroi_fixe (rien a faire),
Symetrie (rien a faire)
int modifier_solution (DoubleTab &) override
void completer (const Equation_base &) override
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_VDF & self_cast (Objet_U &)
static const Assembleur_P_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
int construire (Matrice &la_matrice)
Determine les elements non nuls de la matrice et prepare le stockage.
Matrice creuse de taille nb_elements (lignes) * nb_elem_tot (colonnes)
Codee comme une matrice bloc composee de deux matrices morse:
* Matrice carree symetrique nb_elements * nb_elements
(contient les termes M(i,j) ou i et j sont des numeros d'elements reels)
* Matrice rectangle nb_elements * (nb_elem_tot - nb_elem)
(contient les termes M(i,j) ou i est reel et j est virtuel.
int remplir (Matrice &la_matrice, const DoubleVect &volumes_entrelaces, const Champ_Don_base *rho_ptr)
Calcul des coefficients de la matrice de pression avec un champ de rho.
Si rho_ptr == 0, on calcule la matrice -div(porosite * grad P),
sinon on calcule -div(porosite/rho grad P) et *rho_ptr doit etre un Champ_Fonc_Face.
void modifier_secmem_pression_imposee (const Neumann_sortie_libre &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
Modification du second membre du solveur en pression pour une condition
"Neumann_sortie_libre".
Calcul en "increment de pression" :
ajouter l'increment de pression, c'est a dire zero (c.l. instationnaire non supportee)
Calcul en "pression" :
Ajout du terme Pimpose * surface / volume_entrelace au second membre dans la discretisation de la
pression au bord (entre un element elem0 et un element fictif exterieur a pression imposee) :
grad P = (P(elem0) - Pimpose) * surface / volume_entrelace.
void modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
Modification du second membre du systeme en pression pour une condition aux limites
de vitesse imposee.
Si on resout en increment de pression, ...
sinon rien a faire.
int liste_faces_periodiques (ArrOfInt &faces)
Remplit le tableau faces avec la liste des indices des faces periodiques
dans le tableau faces_voisins. Chaque face periodique figure deux fois
dans faces_voisins (a chaque face correspond la face opposee). On ne
met dans le tableau faces que celle des deux qui a l'indice le + petit
dans la liste des faces de chaque bord periodique.
Valeur de retour:
nombre de faces periodiques (egal a la taille du tableau faces).
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
ArrOfDouble les_coeff_pression
int has_P_ref
Detailed Description
Definition at line 33 of file Assembleur_P_VDF.h.
Constructor & Destructor Documentation
Assembleur_P_VDF()
Assembleur_P_VDF::Assembleur_P_VDF ()
Definition at line 34 of file Assembleur_P_VDF.cpp.
                                   :
  has_P_ref(0)
{
}
~Assembleur_P_VDF()
Assembleur_P_VDF::~Assembleur_P_VDF ()
Definition at line 32 of file Assembleur_P_VDF.cpp.
Member Function Documentation
assembler()
int Assembleur_P_VDF::assembler (Matrice & matrice) override virtual
Assemblage de la matrice de pression M telle que
M*P = div(porosite * grad (P))
et calcul des coefficients pour modifier_secmem.
Implements Assembleur_base.
Definition at line 689 of file Assembleur_P_VDF.cpp.
{
  if (je_suis_maitre())
    Cerr << "Assemblage de la matrice pression : Assembleur_P_VDF::assembler" << finl;
// Par defaut, resolution en increment de pression
  set_resoudre_increment_pression(1);
  set_resoudre_en_u(1);
  construire(matrice);
  const Zone_VDF& zone_vdf   = la_zone_VDF.valeur();
  const DoubleVect& volumes_entrelaces = zone_vdf.volumes_entrelaces();
  remplir(matrice,volumes_entrelaces, 0);
  return 1;
}
References Cerr, construire(), finl, Process::je_suis_maitre(), la_zone_VDF, remplir(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
assembler_mat()
int Assembleur_P_VDF::assembler_mat (Matrice & matrice, const DoubleVect & volumes_entrelaces, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
Definition at line 669 of file Assembleur_P_VDF.cpp.
{
  if (! matrice.non_nul())
    {
      if (je_suis_maitre())
        Cerr << "Assemblage de la matrice pression : Assembleur_P_VDF::assembler" << finl;
// Par defaut, resolution en increment de pression
      construire(matrice);
    }
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  remplir(matrice,volumes_entrelaces, 0);
  return 1;
}
References Cerr, construire(), finl, Process::je_suis_maitre(), O_U_Ptr::non_nul(), remplir(), Assembleur_base::set_resoudre_en_u(), and Assembleur_base::set_resoudre_increment_pression().
assembler_QC()
int Assembleur_P_VDF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible.
La matrice M est telle que M*P = div(porosite * grad(P)).
Le drapeau resoudre_increment_pression est mis a zero s'il n'a pas
encore ete assigne.
Returns
int
Signification: renvoie toujours 1
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 756 of file Assembleur_P_VDF.cpp.
{
// Par defaut pour le qc: resolution en pression et pas en increment pression.
  if (get_resoudre_increment_pression() < 0)
    {
      set_resoudre_increment_pression(1);
      set_resoudre_en_u(0);
    }
  if (! matrice.non_nul())
    {
      if (je_suis_maitre())
        {
          Cerr << "Assemblage de la matrice pression : ";
          Cerr << "Assembleur_P_VDF::assembler_QC" << finl;
        }
      construire(matrice);
      const Zone_VDF& zone_vdf   = la_zone_VDF.valeur();
      const DoubleVect& volumes_entrelaces = zone_vdf.volumes_entrelaces();
      remplir(matrice,volumes_entrelaces, 0);
      Matrice_Bloc& matrice_bloc=ref_cast(Matrice_Bloc,matrice.valeur());
      Matrice_Morse_Sym& la_matrice =ref_cast(Matrice_Morse_Sym,matrice_bloc.get_bloc(0,0).valeur());
      if (la_matrice.get_est_definie()!=1)
        {
          if ((je_suis_maitre()) && (la_matrice.nb_lignes()==0) && (la_matrice.nb_colonnes()==0))
            {
              Cerr<<"Pressure matrix will not be defined."<<finl;
              exit();
            }
          if ((la_matrice.nb_lignes()>0) && (la_matrice.nb_colonnes()>0))
            {
              Cerr<<"la_matrice(0,0)"<<la_matrice(0,0)<<finl;
              Cerr<<"Pas de pression imposee  --> P(0)=0"<<finl;
              if (je_suis_maitre())    la_matrice(0,0) *= 2;
            }
          la_matrice.set_est_definie(1);
        }
    }
  return 1;
}
References Cerr, construire(), Process::exit(), finl, Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Assembleur_base::get_resoudre_increment_pression(), Process::je_suis_maitre(), la_zone_VDF, Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), O_U_Ptr::non_nul(), ref_cast, remplir(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), Deriv_Matrice_Base::valeur(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
assembler_rho_variable()
int Assembleur_P_VDF::assembler_rho_variable (Matrice & matrice, const Champ_Don_base & rho) override virtual
Assemblage de la matrice de pression M telle que
M*P = div(porosite/rho * grad (P))
et calcul des coefficients pour modifier_secmem.
Parametre: matrice
Signification: La matrice a assembler.
Contrainte: Soit la matrice n'est pas encore typee (alors on la "construit"),
soit c'est la meme que lors de l'appel precedent.
Parametre: rho
Contrainte: Doit etre un champ de type Champ_Fonc_Face.
Reimplemented from Assembleur_base.
Definition at line 714 of file Assembleur_P_VDF.cpp.
{
// assembler_rho_variable a ete introduit pour le front-tracking:
// il faut dire explicitement si on resout en increment de pression
  assert(get_resoudre_increment_pression() >= 0);
// idem pour resoudre en u
  assert(get_resoudre_en_u() >= 0);
// Si la matrice n'a pas encore ete typee, il faut la construire :
  if (! matrice.non_nul())
    {
      if (je_suis_maitre())
        {
          Cerr << "Assemblage de la matrice pression : ";
          Cerr << "Assembleur_P_VDF::assembler_rho_variable" << finl;
        }
      construire(matrice);
    }
  const Zone_VDF& zone_vdf   = la_zone_VDF.valeur();
  const DoubleVect& volumes_entrelaces = zone_vdf.volumes_entrelaces();
  remplir(matrice,volumes_entrelaces, & rho);
  return 1;
}
References Cerr, construire(), finl, Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Process::je_suis_maitre(), la_zone_VDF, O_U_Ptr::non_nul(), remplir(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
associer_zone_cl_dis_base()
void Assembleur_P_VDF::associer_zone_cl_dis_base (const Zone_Cl_dis_base & la_zone_Cl_dis) override virtual
Implements Assembleur_base.
Definition at line 814 of file Assembleur_P_VDF.cpp.
{
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, la_zone_Cl_dis);
}
References la_zone_Cl_VDF, and ref_cast.
associer_zone_dis_base()
void Assembleur_P_VDF::associer_zone_dis_base (const Zone_dis_base & la_zone_dis) override virtual
Implements Assembleur_base.
Definition at line 809 of file Assembleur_P_VDF.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, la_zone_dis);
}
References la_zone_VDF, and ref_cast.
completer()
void Assembleur_P_VDF::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
Definition at line 819 of file Assembleur_P_VDF.cpp.
{
// CCa 30/04/99 : je ne sais pas si je dois faire qqchose
  ;
}
construire()
int Assembleur_P_VDF::construire (Matrice & la_matrice) protected
Determine les elements non nuls de la matrice et prepare le stockage.
Matrice creuse de taille nb_elements (lignes) * nb_elem_tot (colonnes)
Codee comme une matrice bloc composee de deux matrices morse:
* Matrice carree symetrique nb_elements * nb_elements
(contient les termes M(i,j) ou i et j sont des numeros d'elements reels)
* Matrice rectangle nb_elements * (nb_elem_tot - nb_elem)
(contient les termes M(i,j) ou i est reel et j est virtuel.
< Astuce pour boucler sur les faces internes et periodiques
< elem0 est reel
< elem1 reel
< elem1 virtuel
< tab1_ contient un indice fortran (1er element en 1)
< Indice fortran 1<=i<=nb_elem
< Nombre de coefficients non nuls sur chaque ligne
< Verifie qu'on a bien deux elements voisins
< elem0 est reel
< Indice fortran
< elem1 est reel aussi
< Indice fortran
< Indice fortran dans tab2
< elem1 est virtuel
< Indice fortran
< Indice fortran dans tab2
Definition at line 104 of file Assembleur_P_VDF.cpp.
{
  int i;
  const Zone_VDF& zone_vdf   = la_zone_VDF.valeur();
  const IntTab& face_voisins = zone_vdf.face_voisins();
// Comptage du nombre total d'elements non nuls:
// matrice carree : nombre de faces internes / 2 + nb_elem + nbfaces periodiques
// (chaque face interne donne un coef, et on a un element
// diagonal et chaque face periodique donne aussi un coef)
// matrice rectangle : nombre de faces de joint
// Premiere etape : comptage du nombre d'elements non nuls sur chaque ligne
// Pour chaque ligne de la matrice carree, nombre d'elements non nuls
  const int nb_elem     = zone_vdf.nb_elem();
  const int nb_elem_tot = zone_vdf.nb_elem_tot();
  ArrOfInt carre_nb_non_zero(nb_elem);
// Idem pour le rectangle
  ArrOfInt rect_nb_non_zero(nb_elem);
// Il y a l'element sur la diagonale :
  carre_nb_non_zero = 1;
  rect_nb_non_zero = 0;
  int carre_nb_non_zero_tot = nb_elem;
  int rect_nb_non_zero_tot = 0;
// Plus un element non nul pour chaque face interne et chaque face periodique
// (matrice symetrique, on ne stocke que l'element m(line,col) avec col>line)
  ArrOfInt liste_faces_perio;
  const int nb_faces_periodiques = liste_faces_periodiques(liste_faces_perio);
  const int nb_faces_internes = zone_vdf.nb_faces_internes();
  const int premiere_face_interne = zone_vdf.premiere_face_int();
  for (i = 0; i < nb_faces_internes + nb_faces_periodiques; i++)
    {
      int face;
      if (i < nb_faces_internes) //!< Astuce pour boucler sur les faces internes et periodiques
        face = premiere_face_interne + i;
      else
        face = liste_faces_perio[i - nb_faces_internes];
      int elem0 = face_voisins(face,0);
      int elem1 = face_voisins(face,1);
      if (elem0 > elem1)
        {
          int tmp = elem1;
          elem1 = elem0;
          elem0 = tmp;
        }
      if (elem0 < nb_elem)   //!< elem0 est reel
        {
          if (elem1 < nb_elem)      //!< elem1 reel
            {
              carre_nb_non_zero[elem0] ++;
              carre_nb_non_zero_tot ++;
            }
          else                      //!< elem1 virtuel
            {
              rect_nb_non_zero[elem0] ++;
              rect_nb_non_zero_tot ++;
            }
        }
    }
// Typage et dimensionnement de la matrice de pression
  la_matrice.typer("Matrice_Bloc");
  Matrice_Bloc& matrice =ref_cast(Matrice_Bloc , la_matrice.valeur());
  matrice.dimensionner(1,2);
  matrice.get_bloc(0,0).typer("Matrice_Morse_Sym");
  matrice.get_bloc(0,1).typer("Matrice_Morse");
  Matrice_Morse_Sym& carre = ref_cast(Matrice_Morse_Sym ,matrice.get_bloc(0,0).valeur());
  Matrice_Morse&      rect  = ref_cast(Matrice_Morse ,     matrice.get_bloc(0,1).valeur());
  carre.dimensionner(nb_elem, carre_nb_non_zero_tot);
  rect.dimensionner(nb_elem, nb_elem_tot - nb_elem, rect_nb_non_zero_tot);
  {
    const int nb_faces_bord = zone_vdf.nb_faces_bord();
    les_coeff_pression.resize_array(nb_faces_bord);
  }
  ArrOfInt& carre_tab1 = carre.get_set_tab1();
  ArrOfInt& rect_tab1 = rect.get_set_tab1();
// Matrice creuse, stockage morse avec des indices fortran:
// lignes numerotees 1..n, colonnes 1..m
// Le k-ieme coefficient non nul de la ligne i (1<=i<=n) est (avec 1<=k)
// M(i,j) = coeff_[tab1_[k]]     en fortran
// M(i,j) = coeff_[tab1_[k-1]-1] en C
// Le numero j de la colonne ou se trouve ce coefficient (1<=j<=m) est
// j = tab2_[tab1_[k]]     en fortran
// j = tab2_[tab1_[k-1]-1] en C
//
// Calcul de l'indice du premier coefficient de la ligne i
// dans le tableau d'indices morse des deux matrices (tab1_)
  {
    int indice = 1; //!< tab1_ contient un indice fortran (1er element en 1)
    for (i = 0; i < nb_elem; i++)
      {
        carre_tab1[i] = indice;
        indice += carre_nb_non_zero[i];
      }
    carre_tab1[i] = indice;
    indice = 1;
    for (i = 0; i < nb_elem; i++)
      {
        rect_tab1[i] = indice;
        indice += rect_nb_non_zero[i];
      }
    rect_tab1[i] = indice;
  }
// Deuxieme etape : remplissage de tab2_ = numero de la colonne de chaque
// terme non nul de la matrice
  ArrOfInt& carre_tab2 = carre.get_set_tab2();
  ArrOfInt& rect_tab2 = rect.get_set_tab2();
  carre_tab2 = -1;
  rect_tab2 = -1;
// Terme diagonal:
  for (i = 1; i <= nb_elem; i++)
    carre_tab2[carre_tab1[i-1]-1] = i; //!< Indice fortran 1<=i<=nb_elem
  carre_nb_non_zero = 1; //!< Nombre de coefficients non nuls sur chaque ligne
  rect_nb_non_zero = 0;
// Termes extra-diagonaux:
  for (int i_face = 0; i_face < nb_faces_internes + nb_faces_periodiques; i_face++)
    {
// Calcul du numero de la face a traiter
      const int face = (i_face < nb_faces_internes)
                       ? premiere_face_interne + i_face
                       : liste_faces_perio[i_face - nb_faces_internes];
      int elem0 = face_voisins(face,0);
      int elem1 = face_voisins(face,1);
      if (elem0 > elem1)
        {
          int tmp = elem1;
          elem1 = elem0;
          elem0 = tmp;
        }
      assert(elem0 >= 0);            //!< Verifie qu'on a bien deux elements voisins
      if (elem0 < nb_elem)                              //!< elem0 est reel
        {
          const int ligne = elem0 + 1;                 //!< Indice fortran
          if (elem1 < nb_elem)                            //!< elem1 est reel aussi
            {
              const int colonne = elem1 + 1;             //!< Indice fortran
              const int n = carre_nb_non_zero[ligne-1]++;
              const int index = carre_tab1[ligne-1] + n; //!< Indice fortran dans tab2
              carre_tab2[index - 1] = colonne;
            }
          else                                           //!< elem1 est virtuel
            {
              const int colonne = elem1 - nb_elem + 1;  //!< Indice fortran
              const int n = rect_nb_non_zero[ligne-1]++;
              const int index = rect_tab1[ligne-1] + n; //!< Indice fortran dans tab2
              rect_tab2[index - 1] = colonne;
            }
        }
    }
  return 1;
}
References carre(), Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Zone_VF::face_voisins(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_zone_VDF, les_coeff_pression, liste_faces_periodiques(), Zone_dis_base::nb_elem(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_bord(), Zone_VF::nb_faces_internes(), Zone_VF::premiere_face_int(), ref_cast, TRUSTArray< _TYPE_ >::resize_array(), Deriv_::typer(), Deriv_Matrice_Base::valeur(), and Ref_Zone_VDF::valeur().
Referenced by assembler(), assembler_mat(), assembler_QC(), and assembler_rho_variable().
cree_instance()
Objet_U * Assembleur_P_VDF::cree_instance () static
Definition at line 32 of file Assembleur_P_VDF.cpp.
duplique()
int Assembleur_P_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 32 of file Assembleur_P_VDF.cpp.
get_info()
const Type_info * Assembleur_P_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 32 of file Assembleur_P_VDF.cpp.
info()
const Type_info * Assembleur_P_VDF::info () static
Definition at line 32 of file Assembleur_P_VDF.cpp.
liste_faces_periodiques()
int Assembleur_P_VDF::liste_faces_periodiques (ArrOfInt & faces) protected
Remplit le tableau faces avec la liste des indices des faces periodiques
dans le tableau faces_voisins. Chaque face periodique figure deux fois
dans faces_voisins (a chaque face correspond la face opposee). On ne
met dans le tableau faces que celle des deux qui a l'indice le + petit
dans la liste des faces de chaque bord periodique.
Valeur de retour:
nombre de faces periodiques (egal a la taille du tableau faces).
Definition at line 57 of file Assembleur_P_VDF.cpp.
{
// On commence par surestimer largement la taille du tableau :
// nombre de faces de bord
  const int nb_faces_bord = la_zone_VDF.valeur().nb_faces_bord();
  faces.resize_array(nb_faces_bord);
// Recherche des faces periodiques dans les conditions aux limites:
  const Conds_lim& les_cl = la_zone_Cl_VDF.valeur().les_conditions_limites();
  const int nb_cl = les_cl.size();
  int nb_faces_periodiques = 0;
  for (int num_cl = 0; num_cl < nb_cl; num_cl++)
    {
      const Cond_lim_base& la_cl = les_cl[num_cl].valeur();
// Selectionne uniquement les conditions Periodique
      if ( ! sub_type(Periodique,la_cl))
        continue;
      const Periodique& la_cl_perio = ref_cast(Periodique, la_cl);
      const Front_VF&    frontiere = ref_cast(Front_VF, la_cl.frontiere_dis());
      const int nb_faces_cl = frontiere.nb_faces();
      const int num_premiere_face = frontiere.num_premiere_face();
      for (int i = 0; i < nb_faces_cl; i++)
        {
// Numero de la face opposee dans le tableau des faces du bord:
          const int face_associee = la_cl_perio.face_associee(i);
          if (face_associee > i)
            {
              const int num_face_global = num_premiere_face + i;
              faces[nb_faces_periodiques] = num_face_global;
              nb_faces_periodiques++;
            }
        }
    }
// Taille finale du tableau faces
  faces.resize_array(nb_faces_periodiques);
  return nb_faces_periodiques;
}
References Periodique::face_associee(), face_associee, Cond_lim_base::frontiere_dis(), la_zone_Cl_VDF, la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces_bord(), Front_VF::num_premiere_face(), ref_cast, TRUSTArray< _TYPE_ >::resize_array(), vect_impl::size(), sub_type, Ref_Zone_Cl_VDF::valeur(), and Ref_Zone_VDF::valeur().
Referenced by construire(), and remplir().
modifier_secmem()
int Assembleur_P_VDF::modifier_secmem (DoubleTab & secmem) override virtual
Modification du second membre pour appliquer les conditions aux limites.
Les conditions prises en charge sont
Neumann_sortie_libre,
Entree_fluide_vitesse_imposee,
Dirichlet_paroi_defilante (rien a faire),
Dirichlet_paroi_fixe (rien a faire),
Symetrie (rien a faire)
Implements Assembleur_base.
Definition at line 490 of file Assembleur_P_VDF.cpp.
{
  const Zone_Cl_VDF& la_zone_cl = la_zone_Cl_VDF.valeur();
  int nb_cond_lim = la_zone_cl.nb_cond_lim();
  for (int indice_cl = 0; indice_cl < nb_cond_lim; indice_cl++)
    {
      const Cond_lim_base& la_cl_base =
        la_zone_cl.les_conditions_limites(indice_cl).valeur();
      const Front_VF& frontiere_vf = ref_cast(Front_VF, la_cl_base.frontiere_dis());
      if (sub_type(Neumann_sortie_libre, la_cl_base))
        {
          modifier_secmem_pression_imposee(ref_cast( Neumann_sortie_libre, la_cl_base),
                                           frontiere_vf,
                                           secmem);
        }
      else if (sub_type(Entree_fluide_vitesse_imposee, la_cl_base))
        {
          modifier_secmem_vitesse_imposee(ref_cast(Entree_fluide_vitesse_imposee ,la_cl_base),
                                          frontiere_vf,
                                          secmem);
        }
      else if (sub_type(Dirichlet_paroi_defilante, la_cl_base))
        {
// Pour une paroi defilante, rien a faire.
        }
      else if (sub_type(Dirichlet_paroi_fixe, la_cl_base))
        {
// Rien a faire non plus.
        }
      else if (sub_type(Symetrie, la_cl_base))
        {
// Encore rien a faire
        }
      else if (sub_type(Periodique, la_cl_base))
        {
// Rien a faire
        }
      else
        {
          Cerr << "Erreur dans Assembleur_P_VDF::modifier_secmem\n la condition aux limites ";
          Cerr << la_cl_base.que_suis_je() << " n'est pas prise en charge." << finl;
          assert(0);
          exit();
        }
    }
  secmem.echange_espace_virtuel();
  return 1;
}
References Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, Cond_lim_base::frontiere_dis(), la_zone_Cl_VDF, Zone_Cl_dis_base::les_conditions_limites(), modifier_secmem_pression_imposee(), modifier_secmem_vitesse_imposee(), Zone_Cl_dis_base::nb_cond_lim(), Objet_U::que_suis_je(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), and Ref_Zone_Cl_VDF::valeur().
modifier_secmem_pression_imposee()
void Assembleur_P_VDF::modifier_secmem_pression_imposee (const Neumann_sortie_libre & cond_lim, const Front_VF & frontiere_vf, DoubleTab & secmem) protected
Modification du second membre du solveur en pression pour une condition
"Neumann_sortie_libre".
Calcul en "increment de pression" :
ajouter l'increment de pression, c'est a dire zero (c.l. instationnaire non supportee)
Calcul en "pression" :
Ajout du terme Pimpose * surface / volume_entrelace au second membre dans la discretisation de la
pression au bord (entre un element elem0 et un element fictif exterieur a pression imposee) :
grad P = (P(elem0) - Pimpose) * surface / volume_entrelace.
Definition at line 552 of file Assembleur_P_VDF.cpp.
{
  const Zone_VDF& la_zone = la_zone_VDF.valeur();
  const IntTab& face_voisins = la_zone.face_voisins();
  if (get_resoudre_increment_pression())
    {
      /*
        const Champ_front_base & champ_front = cond_lim.champ_front().valeur();
        if (sub_type(Champ_front_instationnaire_base, champ_front)
        || sub_type(Champ_front_var_instationnaire, champ_front)) {
        Cerr << "Erreur dans Assembleur_P_VDF::modifier_secmem_pression_imposee\n ";
        Cerr << champ_front.que_suis_je();
        Cerr << " + resoudre_increment_pression non code" << finl;
        assert(0);
        exit();
        } else {
        // Champ stationnaire, on ajoute un increment de pression nul.
        // Donc rien a faire.
        }
      */
    }
  else
    {
      const int nb_faces = frontiere_vf.nb_faces();
      const int num_premiere_face = frontiere_vf.num_premiere_face();
      for (int i = 0; i < nb_faces; i++)
        {
          const int num_face = num_premiere_face + i;
          const double Pimp = cond_lim.flux_impose(i);
          const double coef = les_coeff_pression[num_face] * Pimp;
          const int elem = face_voisins(num_face, 0) + face_voisins(num_face, 1) + 1;
          secmem[elem] += coef;
        }
    }
}
References Zone_VF::face_voisins(), Neumann::flux_impose(), Assembleur_base::get_resoudre_increment_pression(), la_zone_VDF, les_coeff_pression, Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Ref_Zone_VDF::valeur().
Referenced by modifier_secmem().
modifier_secmem_vitesse_imposee()
void Assembleur_P_VDF::modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee & cond_lim, const Front_VF & frontiere_vf, DoubleTab & secmem) protected
Modification du second membre du systeme en pression pour une condition aux limites
de vitesse imposee.
Si on resout en increment de pression, ...
sinon rien a faire.
< Instationnaire uniforme
< Instationnaire variable
< Stationnaire
Definition at line 595 of file Assembleur_P_VDF.cpp.
{
  const Champ_front_base& champ_front = cond_lim.champ_front().valeur();
  const Zone_VDF& la_zone = la_zone_VDF.valeur();
  const DoubleVect& face_surfaces = la_zone.face_surfaces();
  const IntTab& face_voisins = la_zone.face_voisins();
  if (get_resoudre_en_u())
    {
      int gpoint_variable;
      if (sub_type(Champ_front_instationnaire_base, champ_front))
        gpoint_variable = 0; //!< Instationnaire uniforme
      else if (sub_type(Champ_front_var_instationnaire, champ_front))
        gpoint_variable = 1; //!< Instationnaire variable
      else
        gpoint_variable = -1; //!< Stationnaire
      if (gpoint_variable >= 0)
        {
          const DoubleTab& tab_gpoint = (gpoint_variable)
                                        ? ref_cast(Champ_front_var_instationnaire,  champ_front).Gpoint()
                                        : ref_cast(Champ_front_instationnaire_base, champ_front).Gpoint();
          const int nb_faces = frontiere_vf.nb_faces();
          const int num_premiere_face = frontiere_vf.num_premiere_face();
          for (int i = 0; i < nb_faces; i++)
            {
              const int num_face = num_premiere_face + i;
              const double surface = face_surfaces(num_face);
              const int elem0 = face_voisins(num_face, 0);
              const int elem1 = face_voisins(num_face, 1);
// gpoint est relatif a la normale a la face (elle pointe vers elem1)
// La normale est-elle entrante ou sortante ?
              const double signe = (elem0 < 0) ? 1. : -1.;
// Numero de l'element adjacent a la face de bord
              const int elem = elem0 + elem1 + 1;
              const int ori = la_zone.orientation(num_face);
              const double gpoint = (gpoint_variable) ? tab_gpoint(i, ori) : tab_gpoint(ori);
              secmem[elem] += signe * surface * gpoint;
            }
        }
      else
        {
// Le champ frontiere est stationnaire, rien a faire.
        }
    }
  else
    {
// Resolution en pression: la condition aux limites est imposee ailleurs
    }
}
References Cond_lim_base::champ_front(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Assembleur_base::get_resoudre_en_u(), la_zone_VDF, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), ref_cast, sub_type, Deriv_Champ_front_base::valeur(), and Ref_Zone_VDF::valeur().
Referenced by modifier_secmem().
modifier_solution()
int Assembleur_P_VDF::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Definition at line 650 of file Assembleur_P_VDF.cpp.
{
// Projection :
  double press_0;
  if(!has_P_ref)
    {
// On prend la pression minimale comme pression de reference
// afin d'avoir la meme pression de reference en sequentiel et parallele
      press_0=DMAXFLOAT;
      int nb_elem=la_zone_VDF.valeur().zone().nb_elem();
      for(int n=0; n<nb_elem; n++)
        if (pression[n] < press_0)
          press_0 = pression[n];
      press_0 = mp_min(press_0);
      pression -=press_0;
      pression.echange_espace_virtuel();
    }
  return 1;
}
References DMAXFLOAT, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), has_P_ref, la_zone_VDF, Process::mp_min(), Zone::nb_elem(), Ref_Zone_VDF::valeur(), and Zone_dis_base::zone().
printOn()
Sortie & Assembleur_P_VDF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 39 of file Assembleur_P_VDF.cpp.
{
  return s << que_suis_je() << " " << le_nom() ;
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Assembleur_P_VDF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 44 of file Assembleur_P_VDF.cpp.
{
  return Assembleur_base::readOn(s);
}
References Assembleur_base::readOn().
remplir()
int Assembleur_P_VDF::remplir (Matrice & la_matrice, const DoubleVect & volumes_entrelaces, const Champ_Don_base * rho_ptr) protected
Calcul des coefficients de la matrice de pression avec un champ de rho.
Si rho_ptr == 0, on calcule la matrice -div(porosite * grad P),
sinon on calcule -div(porosite/rho grad P) et *rho_ptr doit etre un Champ_Fonc_Face.
< Indice fortran Indice fortran de l'element diagonal (elem0, elem0)
< a la ligne elem1+1 Indice fortran de l'element extradiagonal (elem0, elem1)
< Indice fortran dans tab2 Coefficient extra-diagonal
< Indice fortran
Definition at line 295 of file Assembleur_P_VDF.cpp.
{
  const Zone_VDF& zone_vdf   = la_zone_VDF.valeur();
  const IntTab& face_voisins = zone_vdf.face_voisins();
  const DoubleVect& face_surfaces = zone_vdf.face_surfaces();
// const DoubleVect & volumes_entrelaces = zone_vdf.volumes_entrelaces();
  const DoubleVect& porosite_face = zone_vdf.porosite_face();
  const DoubleVect * valeurs_rho = 0;
  if (rho_ptr)
    {
      assert(sub_type(Champ_Fonc_Face, *rho_ptr));
      valeurs_rho = & (rho_ptr->valeurs());
    }
// Raccourcis vers la partie carree (coefficients elements reels/reels)
// et la partie rectangulaire (elements reels / elements virtuels) de la matrice
  Matrice_Bloc& matrice = ref_cast(Matrice_Bloc, la_matrice.valeur());
  Matrice_Morse_Sym& carre = ref_cast(Matrice_Morse_Sym, matrice.get_bloc(0,0).valeur());
  Matrice_Morse&      rect  = ref_cast(Matrice_Morse,     matrice.get_bloc(0,1).valeur());
  const int nb_elem = zone_vdf.nb_elem();
  ArrOfInt carre_nb_non_zero(nb_elem);
  ArrOfInt rect_nb_non_zero(nb_elem);
  carre_nb_non_zero = 1;
  rect_nb_non_zero = 0;
  ArrOfInt& carre_tab1 = carre.get_set_tab1();
  ArrOfInt& rect_tab1 = rect.get_set_tab1();
  ArrOfDouble& carre_coeff = carre.get_set_coeff();
  ArrOfDouble& rect_coeff = rect.get_set_coeff();
  carre_coeff = 0.;
  rect_coeff = 0.;
// Traitement des faces internes et periodiques :
// Pour chaque face entre deux elements elem0 et elem1, y a quatre termes a ajouter :
// M(elem0,elem0)
// M(elem0,elem1)
// M(elem1,elem1)
// M(elem1,elem0)  (omis car la matrice est stockee symetrique)
// Construction de la liste des faces periodiques
  ArrOfInt liste_faces_perio;
  const int nb_faces_periodiques = liste_faces_periodiques(liste_faces_perio);
  const int nb_faces_internes = zone_vdf.nb_faces_internes();
  const int premiere_face_interne = zone_vdf.premiere_face_int();
  for (int i_face = 0; i_face < nb_faces_internes + nb_faces_periodiques; i_face++)
    {
// Calcul du numero de la face a traiter
      const int num_face = (i_face < nb_faces_internes)
                           ? premiere_face_interne + i_face
                           : liste_faces_perio[i_face - nb_faces_internes];
// Calcul de rho sur cette face
      const double rho_face = (valeurs_rho) ? (*valeurs_rho)[num_face] : 1.;
// Calcul du coefficient
      const double surface  = face_surfaces[num_face];
      const double volume   = volumes_entrelaces[num_face];
      const double porosite = porosite_face[num_face];
      const double coefficient = surface * surface * porosite / (volume * rho_face);
// Numeros des deux elements voisins (le plus petit dans elem0)
      int elem0 = face_voisins(num_face,0);
      int elem1 = face_voisins(num_face,1);
      if (elem0 > elem1)
        {
          int tmp = elem1;
          elem1 = elem0;
          elem0 = tmp;
        }
      if (elem0 < nb_elem)
        {
// elem0 est reel
          const int ligne = elem0 + 1;   //!< Indice fortran Indice fortran de l'element diagonal (elem0, elem0)
//
          const int index_diag = carre_tab1[ligne-1];
          carre_coeff[index_diag - 1] += coefficient;
          if (elem1 < nb_elem)
            {
// elem1 est reel aussi
// Indice fortran de l'element diagonal (elem1, elem1)
              const int index_diag1 = carre_tab1[elem1]; //!< a la ligne elem1+1 Indice fortran de l'element extradiagonal (elem0, elem1)
//
              const int n = carre_nb_non_zero[ligne-1]++;
              const int index = index_diag + n;
// Coefficient diagonal
              carre_coeff[index_diag1 - 1] += coefficient;
// Coefficient extra-diagonal
              carre_coeff[index - 1] = - coefficient;
              assert(carre.get_tab2()(index - 1) == elem1 + 1);
            }
          else
            {
// elem1 est virtuel
              const int n = rect_nb_non_zero[ligne-1]++;
              const int index = rect_tab1[ligne-1] + n; //!< Indice fortran dans tab2 Coefficient extra-diagonal
//
              rect_coeff[index - 1] = - coefficient;
              assert(rect.get_tab2()(index - 1) == elem1 - nb_elem + 1);
            }
        }
    }
// Traitement des conditions aux limites
  const Conds_lim& les_cl = la_zone_Cl_VDF.valeur().les_conditions_limites();
  const int nb_cl = les_cl.size();
  for (int num_cl = 0; num_cl < nb_cl; num_cl++)
    {
      const Cond_lim_base& la_cl = les_cl[num_cl].valeur();
      const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
// Test sur les conditions limites en 2D RZ (on doit avoir symetrie selon l'axe de revolution)
      if (bidim_axi && !sub_type(Symetrie,la_cl))
        {
          const int ndeb = la_front_dis.num_premiere_face();
          const int nfin = ndeb + la_front_dis.nb_faces();
          if (nfin>ndeb && est_egal(face_surfaces[ndeb],0))
            {
              Cerr << "\nFirst face surface is smaller than PrecisionGeom = " << precision_geom << finl;
              Cerr << "May be you have an error in the definition of the boundary conditions." << finl;
              Cerr << "The axis of revolution for this 2D calculation is along Y." << finl;
              Cerr << "So you must specify symmetry boundary condition (symetrie keyword) for the boundary " << la_front_dis.le_nom() << finl;
              exit();
            }
        }
// Pour chaque face de bord entre elem0 et un element fictif exterieur
// a pression imposee P0, on a :
// grad P = (P(elem0) - P0) * surface / volume_entrelace
// elem0 est une inconnue, P0 est ajoute au second membre dans "modifier_secmem".
      if (sub_type(Neumann_sortie_libre,la_cl))
        {
          has_P_ref = 1;
          carre.set_est_definie(1);
          const int ndeb = la_front_dis.num_premiere_face();
          const int nfin = ndeb + la_front_dis.nb_faces();
          for (int num_face = ndeb; num_face < nfin; num_face++)
            {
// Calcul de rho sur cette face
              const double rho_face = (valeurs_rho) ? (*valeurs_rho)[num_face] : 1.;
// Calcul du coefficient a ajouter dans la matrice
              const double surface  = face_surfaces[num_face];
// Attention: le volume entrelace a une valeur particuliere au bord
// (voir Zone_VDF::calculer_volumes_entrelaces())
              const double volume   = volumes_entrelaces[num_face];
              const double porosite = porosite_face[num_face];
              const double coefficient = Option_VDF::coeff_P_neumann * surface * surface * porosite / (volume * rho_face);
              assert(coefficient > 0.);
// Numero de l'element voisin (l'un est -1, l'autre est un element reel)
              const int elem0 = face_voisins(num_face, 0);
              const int elem1 = face_voisins(num_face, 1);
              assert(elem0 == -1 || elem1 == -1);
              const int elem = elem0 + elem1 + 1;
// Ajout du coefficient a la matrice
              assert(elem < nb_elem);
              const int index = carre_tab1[elem]; //!< Indice fortran
              carre_coeff[index - 1] += coefficient;
              les_coeff_pression[num_face] = coefficient;
            }
        }
      else
        {
// Pour les autres conditions aux limites, aucun terme supplementaire dans
// la matrice (grad P scalaire n = 0 sur le bord,
// ou derivee en temps de grad P scalaire n = 0 sur le bord)
        }
    }
  has_P_ref = (int)mp_max(has_P_ref);
// Verification sanitaire: pas d'element nul sur la diagonale
  for (int i = 0; i < nb_elem; i++)
    {
      const int index = carre_tab1[i];
      const double coeff_diagonal = carre_coeff[index - 1];
      if (coeff_diagonal == 0.)
        {
// La maille i n'a pas de voisin: pression quelconque
          carre_coeff[index - 1] = 1.;
        }
    }
  carre.compacte();
  rect.compacte();
  return 1;
}
References Objet_U::bidim_axi, carre(), Cerr, Option_VDF::coeff_P_neumann, Matrice_Morse::compacte(), est_egal(), Process::exit(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, Cond_lim_base::frontiere_dis(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_tab2(), has_P_ref, la_zone_Cl_VDF, la_zone_VDF, Frontiere_dis_base::le_nom(), les_coeff_pression, Zone_Cl_dis_base::les_conditions_limites(), liste_faces_periodiques(), Process::mp_max(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_VF::nb_faces_internes(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), Objet_U::precision_geom, Zone_VF::premiere_face_int(), ref_cast, vect_impl::size(), sub_type, Deriv_Matrice_Base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), and Champ_Don_base::valeurs().
Referenced by assembler(), assembler_mat(), assembler_QC(), and assembler_rho_variable().
self_cast() [1/2]
const Assembleur_P_VDF & Assembleur_P_VDF::self_cast (const Objet_U & r) static
Definition at line 32 of file Assembleur_P_VDF.cpp.
self_cast() [2/2]
Assembleur_P_VDF & Assembleur_P_VDF::self_cast (Objet_U & r) static
Definition at line 32 of file Assembleur_P_VDF.cpp.
taille_memoire()
unsigned Assembleur_P_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 32 of file Assembleur_P_VDF.cpp.
zone_Cl_dis_base()
const Zone_Cl_dis_base & Assembleur_P_VDF::zone_Cl_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 804 of file Assembleur_P_VDF.cpp.
{
  return la_zone_Cl_VDF.valeur();
}
References la_zone_Cl_VDF, and Ref_Zone_Cl_VDF::valeur().
zone_dis_base()
const Zone_dis_base & Assembleur_P_VDF::zone_dis_base () const override virtual
Implements Assembleur_base.
Definition at line 799 of file Assembleur_P_VDF.cpp.
{
  return la_zone_VDF.valeur();
}
References la_zone_VDF, and Ref_Zone_VDF::valeur().
Member Data Documentation
has_P_ref
int Assembleur_P_VDF::has_P_ref protected
Definition at line 66 of file Assembleur_P_VDF.h.
Referenced by modifier_solution(), and remplir().
info_obj
const Type_info Assembleur_P_VDF::info_obj static
Definition at line 35 of file Assembleur_P_VDF.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Assembleur_P_VDF::la_zone_Cl_VDF protected
Definition at line 62 of file Assembleur_P_VDF.h.
Referenced by associer_zone_cl_dis_base(), liste_faces_periodiques(), modifier_secmem(), remplir(), and zone_Cl_dis_base().
la_zone_VDF
Ref_Zone_VDF Assembleur_P_VDF::la_zone_VDF protected
Definition at line 61 of file Assembleur_P_VDF.h.
Referenced by assembler(), assembler_QC(), assembler_rho_variable(), associer_zone_dis_base(), construire(), liste_faces_periodiques(), modifier_secmem_pression_imposee(), modifier_secmem_vitesse_imposee(), modifier_solution(), remplir(), and zone_dis_base().
les_coeff_pression
ArrOfDouble Assembleur_P_VDF::les_coeff_pression protected
Definition at line 63 of file Assembleur_P_VDF.h.
Referenced by construire(), modifier_secmem_pression_imposee(), and remplir().
The documentation for this class was generated from the following files:
src/VDF/Solveurs/Assembleur_P_VDF.h
src/VDF/Solveurs/Assembleur_P_VDF.cpp