TRUST: FichierHDF Class Reference
FichierHDF Class Reference
This abstract class provides all the functionalities to open and manipulate HDF files and related
concepts (datasets, groups, etc ...)
It intentionally does not place itself in the Sortie_Fichier_base or Entree_Fichier_base hierarchy
since it is rather the datasets inside the HDF file that are regarded as TRUST Fichier objects.
#include <FichierHDF.h>
Public Member Functions
FichierHDF ()
virtual ~FichierHDF ()
virtual void create (Nom filename)
virtual void open (Nom filename, bool readOnly)
virtual void close ()
virtual void create_and_fill_dataset_MW (Nom dataset_basename, Sortie_Brute &sortie)
virtual void create_and_fill_dataset_MW (Nom dataset_basename, SChaine &sortie)
virtual void create_and_fill_dataset_SW (Nom datasetname, Sortie_Brute &sortie)
virtual void read_dataset (Nom dataset_basename, int proc_rank, Entree_Brute &entree)
void fill_dataset (Nom dataset_name, Sortie_Brute &sortie)
virtual bool exists (const char *dataset_name)
void check_int_size (Nom filename)
void set_int_size ()
Static Public Member Functions
static bool is_hdf5 (const char *file_name)
Protected Member Functions
virtual void prepare_file_props ()
virtual void prepare_dataset_props ()
Private Member Functions
FichierHDF & operator= (const FichierHDF &)
FichierHDF (const FichierHDF &)
Detailed Description
This abstract class provides all the functionalities to open and manipulate HDF files and related
concepts (datasets, groups, etc ...)
It intentionally does not place itself in the Sortie_Fichier_base or Entree_Fichier_base hierarchy
since it is rather the datasets inside the HDF file that are regarded as TRUST Fichier objects.
Definition at line 49 of file FichierHDF.h.
Constructor & Destructor Documentation
FichierHDF() [1/2]
FichierHDF::FichierHDF ()
Definition at line 21 of file FichierHDF.cpp.
{
  Cerr << "FichierHDF needs HDF (so MED) to be used!" << finl;
  Process::exit(-1);
}
References Cerr, Process::exit(), and finl.
~FichierHDF()
FichierHDF::~FichierHDF () virtual
Definition at line 26 of file FichierHDF.cpp.
{}
FichierHDF() [2/2]
FichierHDF::FichierHDF (const FichierHDF &) private
Member Function Documentation
check_int_size()
void FichierHDF::check_int_size (Nom filename)
close()
void FichierHDF::close () virtual
Definition at line 30 of file FichierHDF.cpp.
{}
Referenced by DomaineCutter::ecrire_zones(), end_journal(), Probleme_base::finir(), Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), Probleme_base::readOn(), Champ_Fonc_reprise::readOn(), and Probleme_base::sauver().
create()
void FichierHDF::create (Nom filename) virtual
Definition at line 28 of file FichierHDF.cpp.
{}
Referenced by DomaineCutter::ecrire_zones(), end_journal(), Probleme_base::finir(), Raffiner_isotrope_parallele::interpreter(), and Probleme_base::sauver().
create_and_fill_dataset_MW() [1/2]
void FichierHDF::create_and_fill_dataset_MW (Nom dataset_basename, SChaine & sortie) virtual
Definition at line 33 of file FichierHDF.cpp.
{}
create_and_fill_dataset_MW() [2/2]
void FichierHDF::create_and_fill_dataset_MW (Nom dataset_basename, Sortie_Brute & sortie) virtual
Definition at line 32 of file FichierHDF.cpp.
{}
Referenced by end_journal(), Probleme_base::finir(), Raffiner_isotrope_parallele::interpreter(), and Probleme_base::sauver().
create_and_fill_dataset_SW()
void FichierHDF::create_and_fill_dataset_SW (Nom datasetname, Sortie_Brute & sortie) virtual
Definition at line 34 of file FichierHDF.cpp.
{}
Referenced by DomaineCutter::ecrire_zones().
exists()
bool FichierHDF::exists (const char * dataset_name) virtual
Definition at line 39 of file FichierHDF.cpp.
{
  return true;
}
Referenced by Scatter::lire_domaine().
fill_dataset()
void FichierHDF::fill_dataset (Nom dataset_name, Sortie_Brute & sortie)
Definition at line 35 of file FichierHDF.cpp.
{}
Referenced by DomaineCutter::ecrire_zones().
is_hdf5()
bool FichierHDF::is_hdf5 (const char * file_name) static
Definition at line 43 of file FichierHDF.cpp.
{
  return false;
}
Referenced by Raffiner_isotrope_parallele::interpreter(), and Scatter::lire_domaine().
open()
void FichierHDF::open (Nom filename, bool readOnly) virtual
Definition at line 29 of file FichierHDF.cpp.
{}
Referenced by Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), Probleme_base::readOn(), and Champ_Fonc_reprise::readOn().
operator=()
FichierHDF & FichierHDF::operator= (const FichierHDF &) private
prepare_dataset_props()
void FichierHDF::prepare_dataset_props () protected virtual
Reimplemented in FichierHDFPar.
Definition at line 49 of file FichierHDF.cpp.
{}
Referenced by FichierHDFPar::prepare_dataset_props().
prepare_file_props()
void FichierHDF::prepare_file_props () protected virtual
Reimplemented in FichierHDFPar.
Definition at line 48 of file FichierHDF.cpp.
{}
Referenced by FichierHDFPar::prepare_file_props().
read_dataset()
void FichierHDF::read_dataset (Nom dataset_basename, int proc_rank, Entree_Brute & entree) virtual
Definition at line 37 of file FichierHDF.cpp.
{}
Referenced by Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), Probleme_base::readOn(), and Champ_Fonc_reprise::readOn().
set_int_size()
void FichierHDF::set_int_size ()
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/FichierHDF.h
src/Kernel/Utilitaires/FichierHDF.cpp