TRUST: ICoCo::ProblemTrio Class Reference
ICoCo::ProblemTrio Class Reference
class ProblemTrio
This class defines the API a problem has to implement in order to be coupled.
For precise specifications and possible use of this API, See NT
SSTH/LMDL_2006_001
Implements IterativeUnsteadyProblem and FieldIO
#include <ProblemTrio.h>
Public Member Functions
bool initialize_pb (Probleme_U &pb)
ProblemTrio ()
As initialize doesn't have any arguments, they can be passed to the Problem
at the time of instantiation.
They can include data file name, MPI communicator,..
In this implementation (for use outside TRUST), only the name of an
underlying Probleme_U needs to be provided.
void setDataFile (const std::string &datafile) override
void setMPIComm (void *) override
~ProblemTrio () override
bool initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
bool solveTimeStep () override
Calculates the unknown fields for the next time step.
The default implementation uses iterations.
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
void setStationaryMode (bool stationary) override
new in V2
bool getStationaryMode () const override
new in V2
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the ProblemTrio wishes to abort the time step resolution.
std::vector< std::string > getInputFieldsNames () const override
This method is used to find the names of input fields understood by the Problem.
std::vector< std::string > getOutputFieldsNames () const override
ValueType getFieldType (const std::string &name) const override
void getInputFieldTemplate (const std::string &name, TrioField &afield) const override
This method is used to get a template of a field expected for the given name.
void setInputField (const std::string &name, const TrioField &afield) override
This method is used to provide the Problem with an input field.
void getOutputField (const std::string &name, TrioField &afield) const override
void updateOutputField (const std::string &name, TrioField &afield) const override
void getInputMEDDoubleFieldTemplate (const std::string &name, MEDDoubleField &afield) const override
void setInputMEDDoubleField (const std::string &name, const MEDDoubleField &afield) override
void getOutputMEDDoubleField (const std::string &name, MEDDoubleField &afield) const override
void updateOutputMEDDoubleField (const std::string &name, MEDDoubleField &afield) const override
int getMEDCouplingMajorVersion () const override
bool isMEDCoupling64Bits () const override
void setInputIntValue (const std::string &name, const int &val) override
int getOutputIntValue (const std::string &name) const override
double getOutputDoubleValue (const std::string &name) const override
void setInputDoubleValue (const std::string &name, const double &val) override
MEDDoubleField getDirectAccessToUnknown (const std::string &unk_name, bool isFuture)
Protected Attributes
Init_Params * my_params
Probleme_U * pb
mon_main * p
Detailed Description
class ProblemTrio
This class defines the API a problem has to implement in order to be coupled.
For precise specifications and possible use of this API, See NT
SSTH/LMDL_2006_001
Implements IterativeUnsteadyProblem and FieldIO
Definition at line 48 of file ProblemTrio.h.
Constructor & Destructor Documentation
ProblemTrio()
ProblemTrio::ProblemTrio ()
As initialize doesn't have any arguments, they can be passed to the Problem
at the time of instantiation.
They can include data file name, MPI communicator,..
In this implementation (for use outside TRUST), only the name of an
underlying Probleme_U needs to be provided.
Definition at line 98 of file ProblemTrio.cpp.
{
  my_params=new Init_Params;
  (*my_params).problem_name="default_vvvvv";
  (*my_params).problem_name="pb";
// my_params.comm=MPI_COMM_WORLD;
  (*my_params).is_mpi=0;
  pb=NULL;
  p=NULL;
}
References my_params, p, pb, and ICoCo::Init_Params::problem_name.
~ProblemTrio()
ProblemTrio::~ProblemTrio () override
Definition at line 55 of file ProblemTrio.cpp.
{
  if(p) delete p;
  p=0;
  delete (my_params);
}
References my_params, and p.
Member Function Documentation
abortTimeStep()
void ProblemTrio::abortTimeStep () override
Aborts the resolution of the current time step.
Definition at line 454 of file ProblemTrio.cpp.
{
  pb->abortTimeStep();
}
References Probleme_U::abortTimeStep(), and pb.
Referenced by main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
computeTimeStep()
double ProblemTrio::computeTimeStep (bool & stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
Returns
double
Signification: The desired time step
Contraintes:
Definition at line 310 of file ProblemTrio.cpp.
{
  return pb->computeTimeStep(stop);
}
References Probleme_U::computeTimeStep(), and pb.
Referenced by main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
getDirectAccessToUnknown()
ICoCo::MEDDoubleField ProblemTrio::getDirectAccessToUnknown (const std::string & unk_name, bool isFuture)
Definition at line 736 of file ProblemTrio.cpp.
{
  using namespace MEDCoupling;
  if(sub_type(Probleme_base,*pb))
    {
      Probleme_base& pb_base = ref_cast(Probleme_base,*pb);
      double * ptr = nullptr;
      size_t nbTup = -1, nbCompo = -1;
      for (int i=0; i < pb_base.nombre_d_equations(); i++)
        {
          Champ_Inc& ci = pb_base.equation(i).inconnue();
          assert(ci.valeurs().nb_dim() == 2);
          if (Motcle(ci.le_nom()) == Motcle(unk_name))
            {
              DoubleTab& t = isFuture ? ci.futur() : ci.valeurs() ;
              ptr = t.addr();
              nbTup = t.dimension_tot(0);
              nbCompo = t.dimension_tot(1);
              break;
            }
        }
      if (ptr == nullptr)
        throw WrongArgument((*my_params).problem_name,"getDirectAccessToUnknown","unk_name","invalid unknown name!!");
// Now wrap the underlying array in a dummy MEDDoubleField, with no valid mesh and no valid field information.
      MCAuto<DataArrayDouble> da = DataArrayDouble::New();
      da->useExternalArrayWithRWAccess(ptr, nbTup, nbCompo);
      MCAuto<MEDCouplingFieldDouble> f = MEDCouplingFieldDouble::New(ON_CELLS,ONE_TIME);
      f->setArray(da);
      MEDDoubleField ret(f);
      return ret;
    }
  else
    throw WrongArgument((*my_params).problem_name,"getDirectAccessToUnknown","","Problem type must derive from Probleme_base!!");
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension_tot(), Probleme_base::equation(), Champ_Inc::futur(), Equation_base::inconnue(), O_U_Ptr::le_nom(), TRUSTTab< _TYPE_ >::nb_dim(), Probleme_base::nombre_d_equations(), pb, ref_cast, sub_type, and Champ_Inc::valeurs().
getFieldType()
ICoCo::ValueType ProblemTrio::getFieldType (const std::string & name) const override
Definition at line 619 of file ProblemTrio.cpp.
{
  vector<string> fld = getOutputFieldsNames();
  if (std::find(fld.begin(), fld.end(), name) == fld.end())
    {
      fld = getInputFieldsNames();
      if (std::find(fld.begin(), fld.end(), name) == fld.end())
        throw WrongArgument((*my_params).problem_name,"getFieldType","name","invalid field name!!");
    }
// All fields thus far are Double field in TRUST:
  return ICoCo::ValueType::Double;
}
References getInputFieldsNames(), and getOutputFieldsNames().
getInputFieldsNames()
vector< string > ProblemTrio::getInputFieldsNames () const override
This method is used to find the names of input fields understood by the Problem.
Returns
vector<string>
Signification: list of names usable with getInputFieldTemplate and setInputField
Contraintes:
Definition at line 508 of file ProblemTrio.cpp.
{
  vector<string> v;
  Noms noms;
  pb->getInputFieldsNames(noms);
  for (int i=0; i<noms.size(); i++)
    v.push_back(noms[i].getChar());
  return v;
}
References Probleme_U::getInputFieldsNames(), pb, and vect_impl::size().
Referenced by getFieldType(), getOutputDoubleValue(), main_pilote_icoco_1(), and main_pilote_icoco_2().
getInputFieldTemplate()
void ProblemTrio::getInputFieldTemplate (const std::string & name, TrioField & afield) const override
This method is used to get a template of a field expected for the given name.
Definition at line 535 of file ProblemTrio.cpp.
{
  Nom nom(name);
  pb->getInputFieldTemplate(nom,afield);
}
References Probleme_U::getInputFieldTemplate(), and pb.
Referenced by getInputMEDDoubleFieldTemplate(), main_abort(), main_pilote_icoco_1(), main_pilote_icoco_2(), and setInputMEDDoubleField().
getInputMEDDoubleFieldTemplate()
void ProblemTrio::getInputMEDDoubleFieldTemplate (const std::string & name, MEDDoubleField & afield) const override
Definition at line 656 of file ProblemTrio.cpp.
{
#ifndef NO_MEDFIELD
  TrioField  triofield;
  getInputFieldTemplate(name,triofield);
  medfield=build_medfield(triofield);
#else
  throw NotImplemented("No ParaMEDMEM","getInputMEDDoubleFieldTemplate");
#endif
}
References build_medfield(), and getInputFieldTemplate().
getMEDCouplingMajorVersion()
int ProblemTrio::getMEDCouplingMajorVersion () const override
Definition at line 714 of file ProblemTrio.cpp.
{
#ifdef OLD_MEDCOUPLING
  return 7;
#else
  return MEDCOUPLING_VERSION_MAJOR;
#endif
}
getOutputDoubleValue()
double ProblemTrio::getOutputDoubleValue (const std::string & name) const override
Definition at line 568 of file ProblemTrio.cpp.
{
  TrioField f;
  try
    {
      getOutputField(name,f);
    }
  catch (WrongArgument& err)
    {
      vector<string> fld = getInputFieldsNames();
      if (std::find(fld.begin(), fld.end(), name) == fld.end())
        throw err;
      Cerr << "WARNING: trying to call getOutputDoubleValue() of an input field...!!" << finl;
      return -1e+38;
    }
  if (f.nb_values()!=1)
    throw WrongArgument((*my_params).problem_name,"getOutputDoubleValue",name,"invalid field size (should be 1)!!");
  return f._field[0];
}
References Cerr, finl, getInputFieldsNames(), and getOutputField().
getOutputField()
void ProblemTrio::getOutputField (const std::string & name, TrioField & afield) const override
Definition at line 632 of file ProblemTrio.cpp.
{
  Motcle name(name_);
  pb->getOutputField(name,afield);
}
References Probleme_U::getOutputField(), and pb.
Referenced by getOutputDoubleValue(), getOutputMEDDoubleField(), updateOutputField(), and updateOutputMEDDoubleField().
getOutputFieldsNames()
vector< string > ProblemTrio::getOutputFieldsNames () const override
Definition at line 606 of file ProblemTrio.cpp.
{
// const Probleme_base& pb_base=ref_cast(Probleme_base,*pb);
  Noms my_names;
  pb->getOutputFieldsNames(my_names);
  vector<string> output_names;
  for (int i=0; i<my_names.size(); i++)
    output_names.push_back(my_names(i).getChar());
  return  output_names;
}
References Probleme_U::getOutputFieldsNames(), pb, and vect_impl::size().
Referenced by getFieldType().
getOutputIntValue()
int ProblemTrio::getOutputIntValue (const std::string & name) const override
Definition at line 597 of file ProblemTrio.cpp.
{
  const Nom nom(name.c_str());
// [ABN] A bit ugly: we force cast to int to handle the 64b situation.
// In 64b the ScalarRegister will become long, but the final ICoCo interface will be int.
// Hopefully soon we will have a clean 64-bits version...
  return (int)pb->getOutputIntValue(nom);
}
References Probleme_U::getOutputIntValue(), and pb.
getOutputMEDDoubleField()
void ProblemTrio::getOutputMEDDoubleField (const std::string & name, MEDDoubleField & afield) const override
Definition at line 644 of file ProblemTrio.cpp.
{
#ifndef NO_MEDFIELD
  TrioField  triofield;
  getOutputField(name,triofield);
  medfield= build_medfield(triofield);
#else
  throw NotImplemented("No ParaMEDMEM","getInputMEDDoubleField");
#endif
}
References build_medfield(), and getOutputField().
getStationaryMode()
bool ProblemTrio::getStationaryMode () const override
new in V2
Definition at line 430 of file ProblemTrio.cpp.
{
// TODO TODO FIXME
  Cerr << "ProblemTrio::getStationaryMode() not impl!" << finl;
  Process::exit(-1);
  return true;
}
References Cerr, Process::exit(), and finl.
initialize()
bool ProblemTrio::initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
< ???
Definition at line 142 of file ProblemTrio.cpp.
{
  Process::exception_sur_exit=1;
  if (((*my_params).problem_name=="default_vvvvv") || ((*my_params).data_file=="default_vvvvv"))
    throw WrongArgument("??","Constructor","data","data shoud point to the name of a Probleme_U");
#ifdef MPI_
// exception if I don't belong to comm !
  True_int rank_in_comm=0;
  if ((*my_params).is_mpi!=0)
    {
      if (MPI_Comm_rank((*my_params).comm,&rank_in_comm)!=MPI_SUCCESS)
        throw WrongArgument((*my_params).problem_name,"initialize","comm","This process should belong to comm");
      if (rank_in_comm==MPI_UNDEFINED)
        throw WrongArgument((*my_params).problem_name,"initialize","comm","This process should belong to comm");
      Comm_Group_MPI::set_trio_u_world((*my_params).comm);
    }
  Comm_Group_MPI::set_must_mpi_initialize(0); //!< ???
#endif
  int argc=2;
  char** argv=new char*[argc];
  string code="TRUST wrapper";
// Les copies sont necessaires pour se debarrasser des const...
  argv[0]=new char[code.length()+1];
  strcpy(argv[0],code.c_str());
  argv[1]=new char[(*my_params).data_file.length()+1];
  strcpy(argv[1],(*my_params).data_file.c_str());
// pour salome
  if (p) delete p;
  p=NULL;
  int res;
// on lance avec ou sans mpi
  res=main_TRUST(argc,argv,p,(*my_params).is_mpi);
  delete [] argv[0];
  delete [] argv[1];
  delete [] argv;
  Nom nom("ICoCoProblemName"),nom_pb;
  if (nom.interprete().objet_existant(nom))
    {
      nom_pb=ref_cast(Nom,get_obj(nom));
      Cout<<finl<<" ICoCoProblemName from data file "<<nom_pb<< finl;
    }
  else
    {
      nom_pb="pb";
      Cout<<finl<<" ICoCoProblemName not found in data file, we try "<<nom_pb<< finl;
    }
  (*my_params).problem_name=nom_pb;
  pb=&ref_cast(Probleme_U,get_obj(nom_pb));
  if (res || !pb)
    throw WrongArgument((*my_params).problem_name,"initialize","problem_name","No problem of that name found in data file");
  initialize_pb(*pb);
// Register signal and signal handler (SIGINT) if user presses ctrl-c during exec
  if (!Objet_U::DEACTIVATE_SIGINT_CATCH)
    {
      Catch_SIGINIT sig;
      sig.set_nom_cas_pour_signal(pb->nom_du_cas());
      signal(SIGINT, Catch_SIGINIT::signal_callback_handler);
    }
// Print the initialization CPU statistics
  if (!Objet_U::disable_TU)
    {
      statistiques().dump("Statistiques d'initialisation du calcul", 0);
      print_statistics_analyse("Statistiques d'initialisation du calcul", 0);
    }
  statistiques().reset_counters();
  statistiques().begin_count(temps_total_execution_counter_);
  return true;
}
References Statistiques::begin_count(), Cout, Objet_U::DEACTIVATE_SIGINT_CATCH, Objet_U::disable_TU, Statistiques::dump(), Process::exception_sur_exit, finl, get_obj(), initialize_pb(), main_TRUST(), Objet_U::nom_du_cas(), p, pb, print_statistics_analyse(), ref_cast, Statistiques::reset_counters(), Comm_Group_MPI::set_must_mpi_initialize(), Catch_SIGINIT::set_nom_cas_pour_signal(), Comm_Group_MPI::set_trio_u_world(), Catch_SIGINIT::signal_callback_handler(), statistiques(), and temps_total_execution_counter_.
initialize_pb()
bool ProblemTrio::initialize_pb (Probleme_U & pb)
Definition at line 219 of file ProblemTrio.cpp.
{
  if (pb==NULL)
    pb=&pb_to_solve;
  pb_to_solve.initialize();
  pb_to_solve.postraiter(1);
  return true;
}
References Probleme_U::initialize(), pb, and Probleme_U::postraiter().
Referenced by initialize(), main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
initTimeStep()
bool ProblemTrio::initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
Returns
bool
Signification: true=OK, false=error, not able to tackle this dt
Contraintes:
Definition at line 334 of file ProblemTrio.cpp.
{
  return pb->initTimeStep(dt);
}
References Probleme_U::initTimeStep(), and pb.
Referenced by main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
isMEDCoupling64Bits()
bool ProblemTrio::isMEDCoupling64Bits () const override
Definition at line 723 of file ProblemTrio.cpp.
{
#ifdef OLD_MEDCOUPLING
  return false;
#else
  return sizeof(mcIdType) == 8;
#endif
}
isStationary()
bool ProblemTrio::isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
Returns
bool
Signification: true=stationary, false=not stationary
Contraintes:
Definition at line 418 of file ProblemTrio.cpp.
{
  return pb->isStationary();
}
References Probleme_U::isStationary(), and pb.
Referenced by main_pilote_icoco_1(), and main_pilote_icoco_2().
iterateTimeStep()
bool ProblemTrio::iterateTimeStep (bool & converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the ProblemTrio wishes to abort the time step resolution.
Returns
bool
Signification: true=OK, false=unable to converge
Contraintes:
Definition at line 488 of file ProblemTrio.cpp.
{
  return pb->iterateTimeStep(converged);
}
References Probleme_U::iterateTimeStep(), and pb.
presentTime()
double ProblemTrio::presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
Returns
double
Signification: present time
Contraintes:
Definition at line 287 of file ProblemTrio.cpp.
{
  return pb->presentTime();
}
References pb, and Probleme_U::presentTime().
Referenced by main_pilote_icoco_1().
setDataFile()
void ProblemTrio::setDataFile (const std::string & datafile) override
Definition at line 110 of file ProblemTrio.cpp.
{
  (*my_params).data_file=file;
}
setInputDoubleValue()
void ProblemTrio::setInputDoubleValue (const std::string & name, const double & val) override
Definition at line 562 of file ProblemTrio.cpp.
{
  Nom mot(name);
  pb->setInputDoubleValue(mot,val);
}
References pb, and Probleme_U::setInputDoubleValue().
setInputField()
void ProblemTrio::setInputField (const std::string & name, const TrioField & afield) override
This method is used to provide the Problem with an input field.
Definition at line 556 of file ProblemTrio.cpp.
{
  Nom nom(name);
  pb->setInputField(nom,afield);
}
References pb, and Probleme_U::setInputField().
Referenced by main_abort(), main_pilote_icoco_1(), main_pilote_icoco_2(), and setInputMEDDoubleField().
setInputIntValue()
void ProblemTrio::setInputIntValue (const std::string & name, const int & val) override
Definition at line 590 of file ProblemTrio.cpp.
{
// add value in ICoCoScalarRegister
  const Nom nom(name.c_str());
  pb->setInputIntValue(nom, val);
}
References pb, and Probleme_U::setInputIntValue().
setInputMEDDoubleField()
void ProblemTrio::setInputMEDDoubleField (const std::string & name, const MEDDoubleField & afield) override
Definition at line 667 of file ProblemTrio.cpp.
{
#ifndef NO_MEDFIELD
// bof en attendant mieux
  TrioField  triofield;
  getInputFieldTemplate(name,triofield);
#ifdef OLD_MEDCOUPLING
  const ParaMEDMEM::DataArrayDouble *fieldArr=afield.getField()->getArray();
#else
  const MEDCoupling::DataArrayDouble *fieldArr=afield.getMCField()->getArray();
#endif
  triofield._field=const_cast<double*> (fieldArr->getConstPointer());
// il faut copier les valeurs
  setInputField(name,triofield);
  triofield._field=0;
// fieldArr->decrRef();
// Assigning proper component names
  const unsigned int nbcomp = fieldArr->getNumberOfComponents();
  std::vector<std::string> compo_names = fieldArr->getInfoOnComponents();
  REF(Field_base) ch = pb->findInputField(Nom(name));
  assert(nbcomp == (unsigned)ch->nb_comp());
  for (unsigned int i = 0; i < nbcomp; i++)
    {
      Nom compo_name(compo_names[i]);
      ch->fixer_nom_compo((int)i, compo_name);
    }
#else
  throw NotImplemented("No ParaMEDMEM","setInputMEDDoubleField");
#endif
}
References Probleme_U::findInputField(), getInputFieldTemplate(), pb, REF, and setInputField().
setMPIComm()
void ProblemTrio::setMPIComm (void * mpicomm) override
Definition at line 114 of file ProblemTrio.cpp.
{
#ifdef MPI_
  if (mpicomm)
    {
      (*my_params).is_mpi=1;
      (*my_params).comm=*((MPI_Comm*)(mpicomm));
    }
#endif
}
setStationaryMode()
void ProblemTrio::setStationaryMode (bool stationary) override
new in V2
Definition at line 423 of file ProblemTrio.cpp.
{
// TODO TODO FIXME
  Cerr << "ProblemTrio::setStationaryMode() not impl!" << finl;
  Process::exit(-1);
}
References Cerr, Process::exit(), and finl.
solveTimeStep()
bool ProblemTrio::solveTimeStep (void) override
Calculates the unknown fields for the next time step.
The default implementation uses iterations.
Returns
bool
Signification: true=OK, false=unable to find the solution.
Contraintes:
Definition at line 356 of file ProblemTrio.cpp.
{
  statistiques().begin_count(timestep_counter_);
  if (pb->lsauv())
    pb->sauver();
  bool res=pb->solveTimeStep();
  return res;
}
References Statistiques::begin_count(), Probleme_U::lsauv(), pb, Probleme_U::sauver(), Probleme_U::solveTimeStep(), statistiques(), and timestep_counter_.
Referenced by main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
terminate()
void ProblemTrio::terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
Definition at line 244 of file ProblemTrio.cpp.
{
  pb->postraiter(1);
  pb->terminate();
  int mode_append=1;
  if (!Objet_U::disable_TU)
    {
      statistiques().dump("Statistiques Resolution", mode_append);
      print_statistics_analyse("Statistiques Resolution", 1);
    }
  if(p)
    {
      delete p;
      p=0;
// fait dans mon_main maintenant // PE_Groups::finalize();
    }
}
References Objet_U::disable_TU, Statistiques::dump(), p, pb, Probleme_U::postraiter(), print_statistics_analyse(), statistiques(), and Probleme_U::terminate().
Referenced by main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
updateOutputField()
void ProblemTrio::updateOutputField (const std::string & name, TrioField & afield) const override
Definition at line 639 of file ProblemTrio.cpp.
{
  getOutputField(name, afield);
}
References getOutputField().
updateOutputMEDDoubleField()
void ProblemTrio::updateOutputMEDDoubleField (const std::string & name, MEDDoubleField & afield) const override
Definition at line 701 of file ProblemTrio.cpp.
{
#ifndef NO_MEDFIELD
  TrioField  triofield;
  getOutputField(name,triofield);
  medfield= build_medfield(triofield);
#else
  throw NotImplemented("No ParaMEDMEM","getInputMEDDoubleField");
#endif
}
References build_medfield(), and getOutputField().
validateTimeStep()
void ProblemTrio::validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
Definition at line 385 of file ProblemTrio.cpp.
{
  pb->validateTimeStep();
  if(sub_type(Probleme_base,*pb))
    {
      const Probleme_base& pb_base = ref_cast(Probleme_base,*pb);
      const Schema_Temps_base& sch = pb_base.schema_temps();
      bool stop_ = sch.stop();
      if (!stop_) pb->postraiter(0);
    }
  else
    {
// If *pb is a coupled problem, we may get the last line duplicated in post-processing files.
      pb->postraiter(0);
    }
  statistiques().end_count(timestep_counter_);
}
References Statistiques::end_count(), pb, Probleme_U::postraiter(), ref_cast, Probleme_base::schema_temps(), statistiques(), Schema_Temps_base::stop(), sub_type, timestep_counter_, and Probleme_U::validateTimeStep().
Referenced by main_abort(), main_pilote_icoco_1(), and main_pilote_icoco_2().
Member Data Documentation
my_params
Init_Params* ICoCo::ProblemTrio::my_params protected
Definition at line 123 of file ProblemTrio.h.
Referenced by ProblemTrio(), and ~ProblemTrio().
p
mon_main* ICoCo::ProblemTrio::p protected
Definition at line 125 of file ProblemTrio.h.
Referenced by initialize(), ProblemTrio(), terminate(), and ~ProblemTrio().
pb
Probleme_U* ICoCo::ProblemTrio::pb protected
Definition at line 124 of file ProblemTrio.h.
Referenced by abortTimeStep(), computeTimeStep(), getDirectAccessToUnknown(), getInputFieldsNames(), getInputFieldTemplate(), getOutputField(), getOutputFieldsNames(), getOutputIntValue(), initialize(), initialize_pb(), initTimeStep(), isStationary(), iterateTimeStep(), presentTime(), ProblemTrio(), setInputDoubleValue(), setInputField(), setInputIntValue(), setInputMEDDoubleField(), solveTimeStep(), terminate(), and validateTimeStep().
The documentation for this class was generated from the following files:
src/Kernel/ICoCo/ProblemTrio.h
src/Kernel/ICoCo/ProblemTrio.cpp