TRUST: Solv_GCP_NS Class Reference
Solv_GCP_NS Class Reference
#include <Solv_GCP_NS.h>
Public Member Functions
Solv_GCP_NS ()
~Solv_GCP_NS ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
int resoudre_systeme (const Matrice_Base &, const DoubleVect &, DoubleVect &, int) override
void reinit () override
int supporte_matrice_morse_sym () override
Public Member Functions inherited from solv_iteratif
~solv_iteratif () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
solv_iteratif ()
void set_seuil (double s)
double get_seuil () const
int solveur_direct () const override
Public Member Functions inherited from SolveurSys_base
~SolveurSys_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
SolveurSys_base ()
virtual int solveur_direct () const =0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x)=0
virtual int resoudre_systeme (const Matrice_Base &a, const DoubleVect &b, DoubleVect &x, int niter_max)
virtual void fixer_schema_temps_limpr (int l)
void fixer_limpr (int l)
void set_return_on_error (int ret)
int limpr () const
virtual void reinit ()
int nouvelle_matrice () const
void fixer_nouvelle_matrice (int i)
virtual int supporte_matrice_morse_sym ()
virtual int get_flag_updated_input () const
void set_flag_updated_result (int flag)
int get_flag_updated_result () const
void save_matrice_secmem_conditionnel (const Matrice_Base &la_matrice, const DoubleVect &secmem, const DoubleVect &solution, int binaire=1)
void set_reuse_preconditioner (bool flag)
bool reuse_preconditioner ()
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Solv_GCP_NS & self_cast (Objet_U &)
static const Solv_GCP_NS & self_cast (const Objet_U &)
Static Public Member Functions inherited from solv_iteratif
static const Type_info * info ()
static solv_iteratif & self_cast (Objet_U &)
static const solv_iteratif & self_cast (const Objet_U &)
Static Public Member Functions inherited from SolveurSys_base
static const Type_info * info ()
static SolveurSys_base & self_cast (Objet_U &)
static const SolveurSys_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from solv_iteratif
static const Type_info info_obj
Static Public Attributes inherited from SolveurSys_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from solv_iteratif
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from SolveurSys_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
SolveurSys solveur_poisson1
Matrice_Morse_Sym non supporte.
SolveurSys solveur_poisson0
Precond le_precond_
Protected Attributes inherited from solv_iteratif
double seuil_
Protected Attributes inherited from SolveurSys_base
int nouvelle_matrice_
Drapeau pour savoir si un stockage ou une factorisation est a refaire.
int save_matrice_
Drapeau pour savoir si un stockage disque est a refaire.
int return_on_error_ = 0
Detailed Description
Definition at line 24 of file Solv_GCP_NS.h.
Constructor & Destructor Documentation
Solv_GCP_NS()
Solv_GCP_NS::Solv_GCP_NS ()
Definition at line 21 of file Solv_GCP_NS.cpp.
~Solv_GCP_NS()
Solv_GCP_NS::~Solv_GCP_NS ()
Definition at line 21 of file Solv_GCP_NS.cpp.
Member Function Documentation
cree_instance()
Objet_U * Solv_GCP_NS::cree_instance () static
Definition at line 21 of file Solv_GCP_NS.cpp.
duplique()
int Solv_GCP_NS::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Solv_GCP_NS.cpp.
get_info()
const Type_info * Solv_GCP_NS::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Solv_GCP_NS.cpp.
info()
const Type_info * Solv_GCP_NS::info () static
Definition at line 21 of file Solv_GCP_NS.cpp.
printOn()
Sortie & Solv_GCP_NS::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Solv_GCP_NS.cpp.
{
  return s ;
}
readOn()
Entree & Solv_GCP_NS::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 30 of file Solv_GCP_NS.cpp.
{
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  Motcles les_parametres(6);
  {
    les_parametres[0] = "seuil";
    les_parametres[1] = "solveur1";
    les_parametres[2] = "solveur0";
    les_parametres[3] = "impr";
    les_parametres[4] = "precond";
    les_parametres[5] = "quiet";
  }
  int rang;
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error when reading the parameters of the conjugate gradient SSOR " << finl;
      Cerr << "One expected : " << accolade_ouverte << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      rang = les_parametres.search(motlu);
      switch(rang)
        {
        case 0:
          {
            is >> seuil_;
            break;
          }
        case 1:
          {
            is >> solveur_poisson1;
            solveur_poisson1.nommer("poisson_solver1");
            break;
          }
        case 2:
          {
            is >> solveur_poisson0;
            solveur_poisson0.nommer("poisson_solver0");
            break;
          }
        case 3:
          {
            fixer_limpr(1);
            break;
          }
        case 4:
          {
            is >> le_precond_;
            break;
          }
        case 5:
          {
            fixer_limpr(-1);
            break;
          }
        default :
          {
            Cerr << "Error when reading the parameters of the conjugate gradient SSOR " << finl;
            Cerr << "One expected " << les_parametres << " instead of " << motlu << finl;
            exit();
          }
        }
      is >> motlu;
    }
  return is;
}
References Cerr, Process::exit(), finl, SolveurSys_base::fixer_limpr(), le_precond_, SolveurSys::nommer(), Motcles::search(), solv_iteratif::seuil_, solveur_poisson0, and solveur_poisson1.
reinit()
void Solv_GCP_NS::reinit () inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 46 of file Solv_GCP_NS.h.
{
  SolveurSys_base::reinit();
  solveur_poisson1.valeur().reinit();
  solveur_poisson0.valeur().reinit();
}
References SolveurSys_base::reinit(), solveur_poisson0, solveur_poisson1, and Deriv_SolveurSys_base::valeur().
resoudre_systeme() [1/2]
int Solv_GCP_NS::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
Definition at line 272 of file Solv_GCP_NS.cpp.
{
  return resoudre_systeme(la_matrice, secmem, solution,  1000000);
}
References resoudre_systeme().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_GCP_NS::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int niter_max) override virtual
Reimplemented from SolveurSys_base.
Definition at line 141 of file Solv_GCP_NS.cpp.
{
// A00 X0 + A01 X1 = F0
// A10 X0 + A11 X1 = F1
// X1 = A11^(-1) (F1 - A10 X0)
// X0 = (A00 -A01 A11^(-1) A10) (F0 - A01 A11^(-1) F1)
//
// Gradient conjugue sur ce systeme preconditionne par A00
//
// Cerr << "resoudre_systeme : secmem" << secmem << finl;
// int n = secmem.size();
  assert(solution.size_totale() == secmem.size_totale());
  const int n = secmem.size_totale();
  const Matrice_Bloc_Sym& matbloc=ref_cast(Matrice_Bloc_Sym, matrice);
  if (matbloc.nb_bloc_lignes()!=2 || matbloc.nb_bloc_colonnes()!=2) erreur();
  const Matrice_Base& A00=matbloc.get_bloc(0,0);
  const Matrice_Base& A01=matbloc.get_bloc(0,1);
  const Matrice_Base& A11=matbloc.get_bloc(1,1);
  int n0=A00.nb_lignes();
  int n1=A11.nb_lignes();
  int nmax_min = 100;
  int nmax= std::max(Process::mp_sum(n), nmax_min);
  int niter = 0;
  double dold,dnew,alfa;
  solution=0.0;
// Creation de tableaux distribues X1 et F1 sur les sommets
  ConstDoubleTab_parts mo_solution(solution);
  DoubleVect X1=mo_solution[1];
// DoubleVect X1;
// champ.domaine().creer_tableau_sommets(X1);
  DoubleVect F1(X1);
  if (X1.size_totale()!=n1) erreur();
  DoubleVect resu(solution);
// Creation de tableaux distribues X0 et F0 sur les elements
// DoubleVect X0;
// champ.domaine().creer_tableau_elements(X0);
// ConstDoubleTab_parts mo_solution(solution);
  DoubleVect X0=mo_solution[0];
  DoubleVect F0(X0);
  if (X0.size_totale()!=n0) erreur();
// F0 :
  extraire(F0, secmem, 0, n0);
  DoubleVect residu(F0);
// F1 :
  extraire(F1, secmem, n0, n1);
// X1 = A11^(-1) F1
  solveur_poisson1.resoudre_systeme(A11, F1, X1);
  injecter(X1, solution, n0, n1);
// F0=A01 X1
  A01.multvect(X1, F0);
// residu=-F0+A01 X1
  residu -= F0;
  residu *=-1;
  DoubleVect g(F0);
  double norme = mp_norme_vect(residu);
  if(le_precond_.non_nul())
    le_precond_.preconditionner(A00,residu,g);
  else
    solveur_poisson0.resoudre_systeme(A00, residu, g);
  DoubleVect p(g);
  p *= -1.;
  dold = mp_prodscal(residu,g);
  dnew = dold;
  if (limpr()>-1)
    Cout << "GCP NS residue = " << norme << " " << finl;
  double s=0;
  while ( ( norme > seuil_ ) && (niter++ < nmax) )
    {
// F1=A10 p
      p.echange_espace_virtuel();
      A01.multvectT(p, F1);
// X1=-A11^(-1) A10p
      if ((limpr()==1)&& (je_suis_maitre())) Cout << "Solveur1: " ;
      solveur_poisson1.resoudre_systeme(A11, F1, X1);
      X1*=-1.;
// F0=(A00  -A01 A11^(-1) A10) p
      X1.echange_espace_virtuel();
      A01.multvect(X1, F0);
      A00.ajouter_multvect(p, F0);
      s = mp_prodscal(F0,p);
      alfa = dold/(s);
      corriger(solution, alfa, alfa, X1, p, n0, n1);
      residu.ajoute(alfa,F0);
      norme = mp_norme_vect(residu);
      if(norme>seuil_ && dnew>0)
        {
          if ((limpr()==1)&& (je_suis_maitre())) Cout << "Solveur0: " ;
          if(le_precond_.non_nul())
            le_precond_.preconditionner(A00,residu,g);
          else
            solveur_poisson0.resoudre_systeme(A00, residu, g);
          dnew = mp_prodscal(residu,g);
          p *= (dnew/dold);
          p -= g;
          dold = dnew;
          if (dnew < 0)
            {
              Cerr << "Error : dnew<0 in GCP NS solver." << finl;
              Cerr << "Try to reduce the threshold value of solveur0" << finl;
              Cerr << "to a value inferior to those of the GCP NS solver." << finl;
              exit();
            }
        }
      if ((limpr()==1)&& (je_suis_maitre()))
        {
          Cout << "GCP NS residue = " << norme << " " << finl;
          if ((niter % 15) == 0) Cout << finl ;
        }
    }
  if(norme > seuil_)
    {
      Cerr << "No convergence after : " << niter << " iterations\n";
      Cerr << " Residue : "<< norme << "\n";
    }
  solution.echange_espace_virtuel();
  return(niter);
}
References TRUSTVect< _TYPE_ >::ajoute(), Matrice_Base::ajouter_multvect(), Cerr, corriger(), Cout, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), erreur(), Process::exit(), extraire(), finl, Matrice_Bloc_Sym::get_bloc(), injecter(), Process::je_suis_maitre(), le_precond_, SolveurSys_base::limpr(), mp_norme_vect(), mp_prodscal(), Process::mp_sum(), Matrice_Base::multvect(), Matrice_Base::multvectT(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), Matrice_Base::nb_lignes(), O_U_Ptr::non_nul(), norme(), Precond::preconditionner(), ref_cast, SolveurSys::resoudre_systeme(), solv_iteratif::seuil_, TRUSTVect< _TYPE_ >::size_totale(), solveur_poisson0, and solveur_poisson1.
self_cast() [1/2]
const Solv_GCP_NS & Solv_GCP_NS::self_cast (const Objet_U & r) static
Definition at line 21 of file Solv_GCP_NS.cpp.
self_cast() [2/2]
Solv_GCP_NS & Solv_GCP_NS::self_cast (Objet_U & r) static
Definition at line 21 of file Solv_GCP_NS.cpp.
supporte_matrice_morse_sym()
int Solv_GCP_NS::supporte_matrice_morse_sym () inline override virtual
Reimplemented from SolveurSys_base.
Definition at line 34 of file Solv_GCP_NS.h.
  {
    return 0;
  }; //!< Matrice_Morse_Sym non supporte
taille_memoire()
unsigned Solv_GCP_NS::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Solv_GCP_NS.cpp.
Member Data Documentation
info_obj
const Type_info Solv_GCP_NS::info_obj static
Definition at line 26 of file Solv_GCP_NS.h.
le_precond_
Precond Solv_GCP_NS::le_precond_ protected
Definition at line 43 of file Solv_GCP_NS.h.
Referenced by readOn(), and resoudre_systeme().
solveur_poisson0
SolveurSys Solv_GCP_NS::solveur_poisson0 protected
Definition at line 42 of file Solv_GCP_NS.h.
Referenced by readOn(), reinit(), and resoudre_systeme().
solveur_poisson1
SolveurSys Solv_GCP_NS::solveur_poisson1 protected
Matrice_Morse_Sym non supporte.
Definition at line 41 of file Solv_GCP_NS.h.
Referenced by readOn(), reinit(), and resoudre_systeme().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/Solv_GCP_NS.h
src/Kernel/Math/SolvSys/Solv_GCP_NS.cpp