TRUST: Ref_Comm_Group Class Reference
Ref_Comm_Group Class Reference
#include <Ref_Comm_Group.h>
Public Member Functions
~Ref_Comm_Group ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Comm_Group ()
Ref_Comm_Group (const Comm_Group &)
Ref_Comm_Group (const Ref_Comm_Group &)
const Comm_Group & valeur () const
Comm_Group & valeur ()
const Comm_Group * operator-> () const
Comm_Group * operator-> ()
const Ref_Comm_Group & operator= (const Comm_Group &)
const Ref_Comm_Group & operator= (const Ref_Comm_Group &)
operator const Comm_Group & () const
operator Comm_Group & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Comm_Group & self_cast (Objet_U &)
static const Ref_Comm_Group & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Comm_Group * pointeur_
Detailed Description
Definition at line 29 of file Ref_Comm_Group.h.
Constructor & Destructor Documentation
Ref_Comm_Group::~Ref_Comm_Group ()
Definition at line 27 of file Comm_Group.cpp.
Ref_Comm_Group::Ref_Comm_Group ()
Definition at line 27 of file Comm_Group.cpp.
Ref_Comm_Group::Ref_Comm_Group (const Comm_Group & t)
Definition at line 27 of file Comm_Group.cpp.
Ref_Comm_Group::Ref_Comm_Group (const Ref_Comm_Group & t)
Definition at line 27 of file Comm_Group.cpp.
Member Function Documentation
Objet_U * Ref_Comm_Group::cree_instance () [static]
Definition at line 27 of file Comm_Group.cpp.
int Ref_Comm_Group::duplique () const [virtual]
Implements Ref_.
Definition at line 27 of file Comm_Group.cpp.
const Type_info * Ref_Comm_Group::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Comm_Group.cpp.
const Type_info & Ref_Comm_Group::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 27 of file Comm_Group.cpp.
const Type_info * Ref_Comm_Group::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Comm_Group.cpp.
Ref_Comm_Group::operator Comm_Group & ()
Definition at line 27 of file Comm_Group.cpp.
Ref_Comm_Group::operator const Comm_Group & () const
Definition at line 27 of file Comm_Group.cpp.
const Comm_Group * Ref_Comm_Group::operator-> () const [inline]
Definition at line 29 of file Ref_Comm_Group.h.
Comm_Group * Ref_Comm_Group::operator-> () [inline]
Definition at line 29 of file Ref_Comm_Group.h.
const Ref_Comm_Group & Ref_Comm_Group::operator= (const Ref_Comm_Group & t)
Definition at line 27 of file Comm_Group.cpp.
const Ref_Comm_Group & Ref_Comm_Group::operator= (const Comm_Group & t)
Definition at line 27 of file Comm_Group.cpp.
Sortie & Ref_Comm_Group::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Comm_Group.cpp.
Entree & Ref_Comm_Group::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 27 of file Comm_Group.cpp.
const Ref_Comm_Group & Ref_Comm_Group::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 27 of file Comm_Group.cpp.
Ref_Comm_Group & Ref_Comm_Group::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 27 of file Comm_Group.cpp.
void Ref_Comm_Group::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 27 of file Comm_Group.cpp.
unsigned Ref_Comm_Group::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 27 of file Comm_Group.cpp.
const Comm_Group & Ref_Comm_Group::valeur () const [inline]
Definition at line 29 of file Ref_Comm_Group.h.
Referenced by Schema_Comm::begin_comm(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), PE_Groups::exit_group(), Schema_Comm::get_group(), PE_Groups::groupe_TRUST(), Schema_Comm::operator=(), Schema_Comm::set_group(), and Schema_Comm::set_send_recv_pe_list().
Comm_Group & Ref_Comm_Group::valeur () [inline]
Definition at line 29 of file Ref_Comm_Group.h.
Member Data Documentation
const Type_info Ref_Comm_Group::info_obj [static]
Reimplemented from Ref_.
Definition at line 29 of file Ref_Comm_Group.h.
Comm_Group* Ref_Comm_Group::pointeur_ [private]
Definition at line 29 of file Ref_Comm_Group.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Ref_Comm_Group.h
src/Kernel/Utilitaires/Comm_Group.cpp