TRUST: Loi_Etat_GP_QC Class Reference
Loi_Etat_GP_QC Class Reference
classe Loi_Etat_GP_QC
Cette classe represente la loi d'etat pour les gaz parfaits.
Associe a un fluide dilatable, elle definit un fluide quasi compressible
dont la loi d'eata est :
Pth = rho*R*T
#include <Loi_Etat_GP_QC.h>
Public Member Functions
Loi_Etat_GP_QC ()
~Loi_Etat_GP_QC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual void calculer_masse_volumique ()
Calcule la masse volumique.
virtual double calculer_masse_volumique (double, double) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Loi_Etat_GP_QC & self_cast (Objet_U &)
static const Loi_Etat_GP_QC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Detailed Description
classe Loi_Etat_GP_QC
Cette classe represente la loi d'etat pour les gaz parfaits.
Associe a un fluide dilatable, elle definit un fluide quasi compressible
dont la loi d'eata est :
Pth = rho*R*T
Definition at line 41 of file Loi_Etat_GP_QC.h.
Constructor & Destructor Documentation
Loi_Etat_GP_QC::Loi_Etat_GP_QC ()
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
Loi_Etat_GP_QC::~Loi_Etat_GP_QC ()
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
Member Function Documentation
void Loi_Etat_GP_QC::calculer_masse_volumique () [virtual]
Calcule la masse volumique.
Reimplemented from Loi_Etat_GP_base.
Definition at line 65 of file Loi_Etat_GP_QC.cpp.
Referenced by calculer_masse_volumique().
{
  Loi_Etat_Mono_GP_base::calculer_masse_volumique();
}
double Loi_Etat_GP_QC::calculer_masse_volumique (double P, double T) const [virtual]
Reimplemented from Loi_Etat_GP_base.
Definition at line 45 of file Loi_Etat_GP_QC.cpp.
References calculer_masse_volumique(), O_U_Ptr::non_nul(), and Loi_Etat_Mono_GP_base::rho_constant_pour_debug_.
{
  return rho_constant_pour_debug_.non_nul() ? rho_constant_pour_debug_(0,0) :
         Loi_Etat_Mono_GP_base::calculer_masse_volumique(P,T);
}
Objet_U * Loi_Etat_GP_QC::cree_instance () [static]
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
int Loi_Etat_GP_QC::duplique () const [virtual]
Implements Loi_Etat_Mono_GP_base.
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
const Type_info * Loi_Etat_GP_QC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
const Type_info * Loi_Etat_GP_QC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
Sortie & Loi_Etat_GP_QC::printOn (Sortie & s) const [protected, virtual]
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns:
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 33 of file Loi_Etat_GP_QC.cpp.
References finl, and Objet_U::que_suis_je().
{
  os <<que_suis_je()<< finl;
  return os;
}
Entree & Loi_Etat_GP_QC::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 39 of file Loi_Etat_GP_QC.cpp.
References Cerr, and finl.
{
  Cerr << "Lecture de la loi d'etat gaz parfait pour le QC ... " << finl;
  return Loi_Etat_Mono_GP_base::readOn(is);
}
const Loi_Etat_GP_QC & Loi_Etat_GP_QC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
Loi_Etat_GP_QC & Loi_Etat_GP_QC::self_cast (Objet_U & r) [static]
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
unsigned Loi_Etat_GP_QC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Loi_Etat_GP_QC.cpp.
Member Data Documentation
const Type_info Loi_Etat_GP_QC::info_obj [static]
Reimplemented from Loi_Etat_Mono_GP_base.
Definition at line 43 of file Loi_Etat_GP_QC.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_GP_QC.h
src/ThHyd/Dilatable/Quasi_Compressible/Loi_Etat/Loi_Etat_GP_QC.cpp