TRUST: Iterateur_Source_PolyMAC Class Reference
Iterateur_Source_PolyMAC Class Reference
#include <Iterateur_Source_PolyMAC.h>
Public Member Functions
Iterateur_Source_PolyMAC ()
~Iterateur_Source_PolyMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Iterateur_Source_PolyMAC (const Iterateur_Source_PolyMAC_base &)
void completer_ ()
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
Evaluateur_Source_PolyMAC & evaluateur ()
void associer (const Source_base &source)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Iterateur_Source_PolyMAC & self_cast (Objet_U &)
static const
Iterateur_Source_PolyMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 37 of file Iterateur_Source_PolyMAC.h.
Constructor & Destructor Documentation
Iterateur_Source_PolyMAC::Iterateur_Source_PolyMAC ()
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
Iterateur_Source_PolyMAC::~Iterateur_Source_PolyMAC ()
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
Iterateur_Source_PolyMAC::Iterateur_Source_PolyMAC (const Iterateur_Source_PolyMAC_base & Opb) [inline]
Definition at line 57 of file Iterateur_Source_PolyMAC.h.
References DERIV, and Deriv_Iterateur_Source_PolyMAC_base::operator=().
  : DERIV(Iterateur_Source_PolyMAC_base)()
{
  DERIV(Iterateur_Source_PolyMAC_base)::operator=(Opb);
}
Member Function Documentation
DoubleTab & Iterateur_Source_PolyMAC::ajouter (DoubleTab & resu) const [inline]
Definition at line 74 of file Iterateur_Source_PolyMAC.h.
References Iterateur_Source_PolyMAC_base::ajouter(), and Deriv_Iterateur_Source_PolyMAC_base::valeur().
Referenced by Terme_Source_PolyMAC_base::ajouter().
{
  return valeur().ajouter(resu);
}
void Iterateur_Source_PolyMAC::associer (const Source_base & source) [inline]
Definition at line 84 of file Iterateur_Source_PolyMAC.h.
References Iterateur_Source_PolyMAC_base::associer(), and Deriv_Iterateur_Source_PolyMAC_base::valeur().
Referenced by Terme_Source_PolyMAC_base::completer().
{
  return valeur().associer(source);
}
DoubleTab & Iterateur_Source_PolyMAC::calculer (DoubleTab & resu) const [inline]
Definition at line 79 of file Iterateur_Source_PolyMAC.h.
References Iterateur_Source_PolyMAC_base::calculer(), and Deriv_Iterateur_Source_PolyMAC_base::valeur().
Referenced by Terme_Source_PolyMAC_base::calculer().
{
  return valeur().calculer(resu);
}
void Iterateur_Source_PolyMAC::completer_ () [inline]
Definition at line 64 of file Iterateur_Source_PolyMAC.h.
References Iterateur_Source_PolyMAC_base::completer_(), and Deriv_Iterateur_Source_PolyMAC_base::valeur().
Referenced by Terme_Source_PolyMAC_base::completer().
{
  valeur().completer_();
}
Objet_U * Iterateur_Source_PolyMAC::cree_instance () [static]
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
int Iterateur_Source_PolyMAC::duplique () const [virtual]
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
Evaluateur_Source_PolyMAC & Iterateur_Source_PolyMAC::evaluateur () [inline]
Definition at line 69 of file Iterateur_Source_PolyMAC.h.
References Iterateur_Source_PolyMAC_base::evaluateur(), and Deriv_Iterateur_Source_PolyMAC_base::valeur().
Referenced by Terme_Source_Constituant_PolyMAC_Elem::associer_pb(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_pb(), Terme_Source_Constituant_PolyMAC_Elem::associer_zones(), and Terme_Puissance_Thermique_PolyMAC_Elem::associer_zones().
{
  return valeur().evaluateur();
}
const Type_info * Iterateur_Source_PolyMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
const Type_info * Iterateur_Source_PolyMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
Sortie & Iterateur_Source_PolyMAC::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 31 of file Iterateur_Source_PolyMAC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Iterateur_Source_PolyMAC::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 40 of file Iterateur_Source_PolyMAC.cpp.
{
  return s ;
}
const Iterateur_Source_PolyMAC & Iterateur_Source_PolyMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
Iterateur_Source_PolyMAC & Iterateur_Source_PolyMAC::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
unsigned Iterateur_Source_PolyMAC::taille_memoire () const [virtual]
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 26 of file Iterateur_Source_PolyMAC.cpp.
Member Data Documentation
const Type_info Iterateur_Source_PolyMAC::info_obj [static]
Reimplemented from Deriv_Iterateur_Source_PolyMAC_base.
Definition at line 40 of file Iterateur_Source_PolyMAC.h.
The documentation for this class was generated from the following files:
src/PolyMAC/Sources/Iterateur_Source_PolyMAC.h
src/PolyMAC/Sources/Iterateur_Source_PolyMAC.cpp