TRUST: List_Raccord Class Reference
List_Raccord Class Reference
#include <Raccords.h>
Public Member Functions
List_Raccord ()
~List_Raccord ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Raccord (const Raccord &t)
List_Raccord (const List_Raccord &t)
Raccord & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Raccord & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Raccord & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Raccord & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Raccord & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Raccord & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Raccord & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Raccord & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Raccord & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Raccord & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Raccord & operator= (const Raccord &t)
Raccord * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Raccord & operator= (const List_Raccord &)
List_Raccord & add (const List_Raccord &)
Raccord & add (const Raccord &)
List_Raccord & inserer (const List_Raccord &)
Raccord & inserer (const Raccord &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Raccord & operator+= (const List_Raccord &)
List_Raccord & operator+= (const Raccord &)
Raccord & add_if_not (const Raccord &)
Raccord & add_if_not (const char *const)
List_Raccord & search (const Raccord &) const
List_Raccord & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Raccord & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Raccord & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Raccord & dernier () const
Renvoie le dernier element de la liste.
List_Raccord & dernier ()
Renvoie le dernier element de la liste.
List_Raccord & operator-= (const Raccord &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Raccord &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Raccord &) const
void suppr (const Raccord &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Raccord & self_cast (Objet_U &)
static const List_Raccord & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Raccord &) const
Detailed Description
Definition at line 34 of file Raccords.h.
Constructor & Destructor Documentation
List_Raccord::List_Raccord ()
Definition at line 24 of file Raccords.cpp.
List_Raccord::~List_Raccord ()
Definition at line 24 of file Raccords.cpp.
List_Raccord::List_Raccord (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord::List_Raccord (const List_Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Member Function Documentation
List_Raccord & List_Raccord::add (const List_Raccord & a_list) [inline]
Definition at line 34 of file Raccords.h.
Referenced by Zones::comprimer(), DomaineCutter::construire_faces_raccords_ssdom(), DecoupeBord::Decouper(), TroisDto2D::extraire_2D(), Modif_bord_to_raccord::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Zones::merge(), Pave::readOn(), and Raffiner_Simplexes::refine_domain().
: public LIST(Raccord)
Raccord & List_Raccord::add (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::add_if_not (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::add_if_not (const char * const t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
int List_Raccord::contient (const Raccord & t) const [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
int List_Raccord::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Objet_U * List_Raccord::cree_instance () [static]
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
const List_Raccord& List_Raccord::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Raccord & List_Raccord::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
int List_Raccord::duplique () const [virtual]
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
int List_Raccord::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 24 of file Raccords.cpp.
int List_Raccord::est_egal_a (const List_Raccord &) const [inline, protected]
const Type_info * List_Raccord::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
const Type_info * List_Raccord::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
List_Raccord & List_Raccord::inserer (const List_Raccord & a_list) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::inserer (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
const Raccord & List_Raccord::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
const Raccord & List_Raccord::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::operator+= (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::operator+= (const List_Raccord & a_list) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::operator-= (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord * List_Raccord::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::operator= (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::operator= (const List_Raccord & a_list) [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
const Raccord & List_Raccord::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
const Raccord & List_Raccord::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Sortie & List_Raccord::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
int List_Raccord::rang (const Raccord & t) const [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Entree & List_Raccord::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
List_Raccord & List_Raccord::search (const Raccord & t) const [inline]
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
const List_Raccord & List_Raccord::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
List_Raccord & List_Raccord::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
const List_Raccord & List_Raccord::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
List_Raccord & List_Raccord::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
void List_Raccord::suppr (const Raccord & t) [inline]
Definition at line 34 of file Raccords.h.
Referenced by DecoupeBord::Decouper(), TroisDto2D::extraire_2D(), SupprimeBord::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), and RegroupeBord::regroupe_bord().
: public LIST(Raccord)
void List_Raccord::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
unsigned List_Raccord::taille_memoire () const [virtual]
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 24 of file Raccords.cpp.
const Raccord & List_Raccord::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
: public LIST(Raccord)
Raccord & List_Raccord::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 34 of file Raccords.h.
Referenced by Faces_builder::creer_faces_reeles(), Zone::frontiere(), Zone_VF::infobord(), and Raffiner_Simplexes::refine_domain().
: public LIST(Raccord)
Member Data Documentation
const Type_info List_Raccord::info_obj [static]
Reimplemented from liste.
Reimplemented in Raccords.
Definition at line 34 of file Raccords.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Raccords.h
src/Kernel/Geometrie/Raccords.cpp