TRUST: Terme_Boussinesq_VEFPreP1B_Face Class Reference
Terme_Boussinesq_VEFPreP1B_Face Class Reference
class Terme_Boussinesq_scalaire_VEFPreP1B_Face
Terme Source de Boussinesq pour une dicretisation VEFPreP1B
#include <Terme_Boussinesq_VEFPreP1B_Face.h>
Public Member Functions
Terme_Boussinesq_VEFPreP1B_Face ()
~Terme_Boussinesq_VEFPreP1B_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Boussinesq_VEFPreP1B_Face & self_cast (Objet_U &)
static const
Terme_Boussinesq_VEFPreP1B_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
class Terme_Boussinesq_scalaire_VEFPreP1B_Face
Terme Source de Boussinesq pour une dicretisation VEFPreP1B
Definition at line 34 of file Terme_Boussinesq_VEFPreP1B_Face.h.
Constructor & Destructor Documentation
Terme_Boussinesq_VEFPreP1B_Face::Terme_Boussinesq_VEFPreP1B_Face ()
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
Terme_Boussinesq_VEFPreP1B_Face::~Terme_Boussinesq_VEFPreP1B_Face ()
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
Member Function Documentation
DoubleTab & Terme_Boussinesq_VEFPreP1B_Face::ajouter (DoubleTab & resu) const [virtual]
< nombre de points d'integration
< ordre 2
< ordre 2
< lambda_i des points
< Vaut 1 si temperature, nb_constituents si concentration
< Forcee a 0 car ne marche pas d'apres essais Ulrich&Thomas
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 52 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
References Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_base::beta(), calculer_coef_som(), Terme_Boussinesq_base::check(), Cout, Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Terme_Boussinesq_base::equation_scalaire(), Process::exit(), f2, face_associee, Periodique::face_associee(), finl, Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Terme_Boussinesq_base::gravite(), Convection_Diffusion_std::inconnue(), Terme_Boussinesq_VEF_Face::la_zone_Cl_VEF, Terme_Boussinesq_VEF_Face::la_zone_VEF, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Domaine::les_sommets(), Field_base::nb_comp(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::nb_front_Cl(), Zone_VF::porosite_face(), ref_cast, Terme_Boussinesq_base::Scalaire0(), sub_type, Deriv_Cond_lim_base::valeur(), Deriv_Champ_Don_base::valeur(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Champ_base::valeur_aux_elems(), Champ_Don_base::valeurs(), Zone_VF::volumes(), and Zone_dis_base::zone().
{
  const Zone_VEF_PreP1b& zone_VEF = ref_cast(Zone_VEF_PreP1b, la_zone_VEF.valeur());
// Si seulement support P0 on appelle en VEF
  if (zone_VEF.get_alphaE() && !zone_VEF.get_alphaS() && !zone_VEF.get_alphaA())
    return Terme_Boussinesq_VEF_Face::ajouter(resu);
  const DoubleVect& volumes = zone_VEF.volumes();
  const DoubleVect& porosite_surf = zone_VEF.porosite_face();
  const Champ_Inc& le_scalaire = equation_scalaire().inconnue();
  const DoubleVect& g = gravite().valeurs();
  const Zone_Cl_VEF& zone_Cl_VEF = la_zone_Cl_VEF.valeur();
  const IntTab& elem_sommets = zone_VEF.zone().les_elems();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const DoubleTab& coord_sommets=zone_VEF.zone().domaine().les_sommets();
// Verifie la validite de T0:
  check();
  int nbpts=-1; //!< nombre de points d'integration
  if(dimension==2)
    {
      nbpts=3; //!< ordre 2
    }
  else if(dimension==3)
    {
      nbpts=4; //!< ordre 2
    }
  else
    assert(0);
// On remplit les Poids et les coord_bary :
  ArrOfDouble Poids(nbpts);
  DoubleTab coord_bary(nbpts,dimension+1); //!< lambda_i des points
  if(dimension==2)
    {
      double tiers=0.333333333333333;
      Poids(0)=tiers;
      Poids(1)=Poids(2)=Poids(0);
      coord_bary(0,0)=0.5;
      coord_bary(0,1)=0.;
      coord_bary(0,2)=0.5;
      coord_bary(1,0)=0.;
      coord_bary(1,1)=0.5;
      coord_bary(1,2)=0.5;
      coord_bary(2,0)=0.5;
      coord_bary(2,1)=0.5;
      coord_bary(2,2)=0.;
    }
  else if(dimension==3)
    {
      Poids(0)=0.25;
      Poids(1)=Poids(2)=Poids(3)=Poids(0);
      double a = 0.5854101966249685;
      double b = 0.1381966011250105;
      coord_bary(0,0)=a;
      coord_bary(0,1)=b;
      coord_bary(0,2)=b;
      coord_bary(0,3)=b;
      coord_bary(1,0)=b;
      coord_bary(1,1)=a;
      coord_bary(1,2)=b;
      coord_bary(1,3)=b;
      coord_bary(2,1)=b;
      coord_bary(2,0)=b;
      coord_bary(2,2)=a;
      coord_bary(2,3)=b;
      coord_bary(3,2)=b;
      coord_bary(3,0)=b;
      coord_bary(3,1)=b;
      coord_bary(3,3)=a;
    }
  else
    assert(0);
  int nb_comp = le_scalaire.valeur().nb_comp(); //!< Vaut 1 si temperature, nb_constituents si concentration
  IntVect les_polygones(nbpts);
  DoubleTab les_positions(nbpts,dimension);
  DoubleTab valeurs_scalaire(nbpts,nb_comp);
  DoubleTab valeurs_beta(nbpts,nb_comp);
  DoubleVect valeurs_Psi(nbpts);
  ArrOfDouble somme(dimension);
  ArrOfDouble a0(dimension),a0a1(dimension),a0a2(dimension),a0a3(dimension);
// Extension possible des volumes de controle:
  int modif_traitement_diri=( sub_type(Zone_VEF_PreP1b,zone_VEF) ? ref_cast(Zone_VEF_PreP1b,zone_VEF).get_modif_div_face_dirichlet() : 0);
  modif_traitement_diri = 0; //!< Forcee a 0 car ne marche pas d'apres essais Ulrich&Thomas
  int nb_face_diri=0;
  ArrOfInt indice_diri(dimension+1);
// Boucle sur les elements:
  int nb_elem_tot=zone_VEF.nb_elem_tot();
  for (int elem=0; elem<nb_elem_tot; elem++)
    {
      if (modif_traitement_diri)
        calculer_coef_som(elem,nb_face_diri,indice_diri,zone_Cl_VEF,zone_VEF);
      double volume=volumes(elem);
      for (int i=0; i<nbpts; i++)
        les_polygones(i)=elem;
// On remplit la matrice de changement d'element  :
      const int som_glob = elem_sommets(elem,0);
      for (int dim=0; dim<dimension; dim++)
        a0(dim)=coord_sommets(som_glob,dim);
      const int som_glob1 = elem_sommets(elem,1);
      for (int dim=0; dim<dimension; dim++)
        a0a1(dim)=coord_sommets(som_glob1,dim)-a0(dim);
      const int som_glob2 = elem_sommets(elem,2);
      for (int dim=0; dim<dimension; dim++)
        a0a2(dim)=coord_sommets(som_glob2,dim)-a0(dim);
      if(dimension == 3)
        {
          const int som_glob3 = elem_sommets(elem,3);
          for (int dim=0; dim<dimension; dim++)
            a0a3(dim)=coord_sommets(som_glob3,dim)-a0(dim);
        }
// On remplit les_positions :
      if(dimension == 2)
        {
          for (int pt=0; pt<nbpts; pt++)
            {
              for (int dim=0; dim<dimension; dim++)
                les_positions(pt,dim)=a0(dim)
                                      +coord_bary(pt,1)* a0a1(dim)
                                      +coord_bary(pt,2)* a0a2(dim);
            }
        }
      else if(dimension == 3)
        {
          for (int pt=0; pt<nbpts; pt++)
            {
              for (int dim=0; dim<dimension; dim++)
                les_positions(pt,dim)=a0(dim)
                                      +coord_bary(pt,1)* a0a1(dim)
                                      +coord_bary(pt,2)* a0a2(dim)
                                      +coord_bary(pt,3)* a0a3(dim);
            }
        }
      else
        assert(0);
// Calcul du terme source aux points d'integration :
      le_scalaire.valeur().valeur_aux_elems(les_positions,les_polygones,valeurs_scalaire);
      beta().valeur().valeur_aux_elems(les_positions,les_polygones,valeurs_beta);
// Boucle sur les faces de l'element:
      for(int face=0; face<=dimension; face++)
        {
          int num_face=elem_faces(elem, face);
// Calcul des Psi aux points d'integration :
          for (int pt=0; pt<nbpts; pt++)
// valeurs_Psi(pt)=(1-dimension*coord_bary(pt,face))*porosite_surf(face); // Fixed bug
            valeurs_Psi(pt)=(1-dimension*coord_bary(pt,face))*porosite_surf(num_face);
// Integration sur les nbpts points:
          for (int pt=0; pt<nbpts; pt++)
            {
              for (int dim=0; dim<dimension; dim++)
                {
                  double contrib=0;
                  for (int comp=0; comp<nb_comp; comp++)
                    contrib+=Poids(pt)*volume*(Scalaire0(comp)-valeurs_scalaire(pt,comp))*valeurs_beta(pt,comp)*g(dim)*valeurs_Psi(pt);
                  resu(num_face,dim)+=contrib;
                  somme(dim)+=contrib;
                  if (modif_traitement_diri)
                    {
                      for (int fdiri=0; fdiri<nb_face_diri; fdiri++)
{
                          int indice=indice_diri[fdiri];
                          int facel = elem_faces(elem,indice);
                          if (num_face==facel)
{
                              resu(facel,dim)-=contrib;
                              double contrib2=contrib/(dimension+1-nb_face_diri);
                              for (int f2=0; f2<dimension+1; f2++)
{
                                  int face2=elem_faces(elem,f2);
                                  resu(face2,dim)+=contrib2;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
  {
// modif pour periodique
    for (int n_bord=0; n_bord<zone_VEF.nb_front_Cl(); n_bord++)
      {
        const Cond_lim& la_cl = zone_Cl_VEF.les_conditions_limites(n_bord);
        if (sub_type(Periodique,la_cl.valeur()))
          {
            const Periodique& la_cl_perio = ref_cast(Periodique,la_cl.valeur());
            const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
            int nb_faces_bord=le_bord.nb_faces();
            IntVect fait(nb_faces_bord);
            fait = 0;
            for (int ind_face=0; ind_face<nb_faces_bord; ind_face++)
              {
                if (fait(ind_face) == 0)
                  {
                    int ind_face_associee = la_cl_perio.face_associee(ind_face);
                    fait(ind_face) = 1;
                    fait(ind_face_associee) = 1;
                    int face = le_bord.num_face(ind_face);
                    int face_associee = le_bord.num_face(ind_face_associee);
                    for (int dim=0; dim<dimension; dim++)
                      resu(face, dim)=(resu(face_associee, dim)+=resu(face, dim));
                  }//!< if fait
              }//!< for face
          }//!< sub_type Perio
      }
  }
// Verification:
  if (0)
    {
      Cout <<"Integrale : (";
      for (int dim=0; dim<dimension; ++dim)
        {
          Cout<<somme(dim);
          if (dim<(dimension-1))
            Cout<<",";
        }
      Cout<<")"<<finl;
      Process::exit();
    }
  return resu;
}
Objet_U * Terme_Boussinesq_VEFPreP1B_Face::cree_instance () [static]
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
int Terme_Boussinesq_VEFPreP1B_Face::duplique () const [virtual]
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
const Type_info * Terme_Boussinesq_VEFPreP1B_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
const Type_info * Terme_Boussinesq_VEFPreP1B_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
Sortie & Terme_Boussinesq_VEFPreP1B_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 41 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
{
  return Terme_Boussinesq_base::printOn(s);
}
Entree & Terme_Boussinesq_VEFPreP1B_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 47 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
{
  return Terme_Boussinesq_base::readOn(s);
}
const Terme_Boussinesq_VEFPreP1B_Face & Terme_Boussinesq_VEFPreP1B_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
Terme_Boussinesq_VEFPreP1B_Face & Terme_Boussinesq_VEFPreP1B_Face::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
unsigned Terme_Boussinesq_VEFPreP1B_Face::taille_memoire () const [virtual]
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.cpp.
Member Data Documentation
const Type_info Terme_Boussinesq_VEFPreP1B_Face::info_obj [static]
Reimplemented from Terme_Boussinesq_VEF_Face.
Definition at line 36 of file Terme_Boussinesq_VEFPreP1B_Face.h.
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Boussinesq_VEFPreP1B_Face.h
src/VEF/Sources/Terme_Boussinesq_VEFPreP1B_Face.cpp