TRUST: interface_INITGAUSS Class Reference
interface_INITGAUSS Class Reference
#include <interface_INITGAUSS.h>
Public Member Functions
void initialiser_les_commons ()
void init ()
void init_sans_initialiser_les_commons ()
void check_common ()
void compare_common ()
void set_param (Param &)
void dump (Sortie &)
void init_from_common ()
void init_from_file (const Nom &)
void Compute (const int idimg, const int nbnn, const int npgau, ArrOfDouble &xgau, ArrOfDouble &frgau, ArrOfDouble &dfrgau, ArrOfDouble &poigau) const
Detailed Description
Definition at line 23 of file interface_INITGAUSS.h.
Member Function Documentation
check_common()
void interface_INITGAUSS::check_common ()
Definition at line 47 of file interface_INITGAUSS.cpp.
{
}
compare_common()
void interface_INITGAUSS::compare_common ()
Definition at line 51 of file interface_INITGAUSS.cpp.
{
}
Compute()
void interface_INITGAUSS::Compute (const int idimg, const int nbnn, const int npgau, ArrOfDouble & xgau, ArrOfDouble & frgau, ArrOfDouble & dfrgau, ArrOfDouble & poigau) const
Definition at line 55 of file interface_INITGAUSS.cpp.
{
  F77NAME(INITGAUSS)(&idimg, &nbnn, &npgau,  xgau.addr(),  frgau.addr(),  dfrgau.addr(),  poigau.addr());
}
References TRUSTArray< _TYPE_ >::addr(), and F77NAME.
Referenced by ajouter_bord(), and Zone_EF::calculer_Bij().
dump()
void interface_INITGAUSS::dump (Sortie & os)
Definition at line 67 of file interface_INITGAUSS.cpp.
{
  Param param("interface_INITGAUSS");
  set_param(param);
  param.print(os);
}
References Param::print(), and set_param().
init()
void interface_INITGAUSS::init ()
Definition at line 36 of file interface_INITGAUSS.cpp.
{
  initialiser_les_commons();
  init_sans_initialiser_les_commons();
}
References init_sans_initialiser_les_commons(), and initialiser_les_commons().
init_from_common()
void interface_INITGAUSS::init_from_common ()
Definition at line 44 of file interface_INITGAUSS.cpp.
{
}
init_from_file()
void interface_INITGAUSS::init_from_file (const Nom & nom_fic)
Definition at line 59 of file interface_INITGAUSS.cpp.
{
  LecFicDiffuse entree(nom_fic);
  Param param("interface_INITGAUSS");
  set_param(param);
  param.read(entree);
}
References Param::read(), and set_param().
init_sans_initialiser_les_commons()
void interface_INITGAUSS::init_sans_initialiser_les_commons ()
Definition at line 41 of file interface_INITGAUSS.cpp.
{
}
Referenced by init().
initialiser_les_commons()
void interface_INITGAUSS::initialiser_les_commons ()
Definition at line 33 of file interface_INITGAUSS.cpp.
{
}
Referenced by init().
set_param()
void interface_INITGAUSS::set_param (Param & param)
Definition at line 74 of file interface_INITGAUSS.cpp.
{
}
Referenced by dump(), and init_from_file().
The documentation for this class was generated from the following files:
src/EF/fortran/interface_INITGAUSS.h
src/EF/fortran/interface_INITGAUSS.cpp