TRUST: Synonyme_info Class Reference
Synonyme_info Class Reference
modelise une information de synonyme pour les Objet_U
#include <Synonyme_info.h>
Public Member Functions
Synonyme_info ()
~Synonyme_info ()
Synonyme_info (const char *name, const char *org)
Constructeur par un nom, un tableau de meres.
const char * org_name_ () const
const char * nom () const
Static Public Member Functions
static Sortie & hierarchie (Sortie &)
Ecriture de toute la hierarchie du synonyme considere sur un flux de sortie.
static int est_un_synonyme (const char *)
Test d'existence d'une classe du synonyme indique
si il existe une classe T dont le Synonyme_info a
le nom nom, alors est_un_synonyme renvoie 1
renvoie le pointeur nul sinon.
static const Synonyme_info * synonyme_info_from_name (const char *synonyme_name)
Methode statique qui renvoie un pointeur vers le Synonyme_info
dont le nom est "synonyme_name". Si synonyme_name n'est pas un synonyme,
renvoie un pointeur nul.
static void ajouter_synonyme (const Synonyme_info &synonyme_info)
Methode statique appelee par les constructeurs de Synonyme_info pour
ajouter un nouveau synonyme a la liste des synonymes enregistres.
Verifie que le nom du synonyme n'existe pas encore.
Private Member Functions
Synonyme_info (Synonyme_info &)
Synonyme_info & operator= (Synonyme_info &)
Constructeur par copie invalide.
Static Private Member Functions
static void retirer_synonyme (const char *nom)
Methode statique appelee par les constructeurs de Synonyme_info pour
ajouter un nouveau synonyme a la liste des synonymes enregistres.
Verifie que le nom du synonyme n'existe pas encore.
static int search_synonyme_info_name (const char *nom, int &index)
Recherche le synonyme de nom "nom" dans la liste de synonymes enregistres
par une recherche binaire.
On compare les chaines converties en majuscules.
On range dans "index" l'indice du synonyme, s'il a ete trouve
et sinon l'indice du synonyme juste apres (dans ce cas, on a
les_synonymes[index-1]->n < nom < les_synonymes[index]->n)
Si le synonyme a ete trouve on renvoie 1, sinon 0.
Private Attributes
const char * n
const char * org
Static Private Attributes
static const Synonyme_info ** les_synonymes =0
static int nb_classes =0
static int les_synonymes_memsize =0
Detailed Description
modelise une information de synonyme pour les Objet_U
Definition at line 35 of file Synonyme_info.h.
Constructor & Destructor Documentation
Synonyme_info() [1/3]
Synonyme_info::Synonyme_info () inline
Definition at line 38 of file Synonyme_info.h.
{};
~Synonyme_info()
Synonyme_info::~Synonyme_info ()
Definition at line 63 of file Synonyme_info.cpp.
{
  retirer_synonyme(nom());
  if ((nb_classes==0) && (les_synonymes_memsize!=0))
    {
      delete [] les_synonymes;
      les_synonymes_memsize=0;
    }
}
References les_synonymes, les_synonymes_memsize, nb_classes, nom(), and retirer_synonyme().
Synonyme_info() [2/3]
Synonyme_info::Synonyme_info (const char * name, const char * org)
Constructeur par un nom, un tableau de meres.
Definition at line 138 of file Synonyme_info.cpp.
                                                                     :
  n(un_nom),org(org_name)
{
  if((un_nom == 0)||(org_name==0))
    {
      Cerr << "Synonyme_info::Synonyme_info(const char* nom,Objet_U* (*f)()...)\n";
      Cerr << " Error : nom==0" << finl;
      assert(0);
      Process::exit();
    }
  ajouter_synonyme(*this);
}
References ajouter_synonyme(), Cerr, Process::exit(), and finl.
Synonyme_info() [3/3]
Synonyme_info::Synonyme_info (Synonyme_info &) inline private
Definition at line 61 of file Synonyme_info.h.
{}; //!< Constructeur par copie invalide
Member Function Documentation
ajouter_synonyme()
void Synonyme_info::ajouter_synonyme (const Synonyme_info & synonyme_info) static
Methode statique appelee par les constructeurs de Synonyme_info pour
ajouter un nouveau synonyme a la liste des synonymes enregistres.
Verifie que le nom du synonyme n'existe pas encore.
Definition at line 178 of file Synonyme_info.cpp.
{
// Verifie qu'il y a assez de place dans le tableau :
  if (les_synonymes_memsize <= nb_classes + 1)
    {
      static const int INCREMENT = 512;
// Plus assez de place dans le tableau: on redimensionne.
      les_synonymes_memsize += INCREMENT;
      const Synonyme_info** nouveau = new const Synonyme_info*[les_synonymes_memsize];
      for (int i = 0; i < nb_classes; i++)
        nouveau[i] = les_synonymes[i];
      delete[] les_synonymes;
      les_synonymes = nouveau;
    }
// On cherche ou mettre le synonyme dans le tableau :
  int index;
  int existe_deja=Type_info::est_un_type(synonyme_info.n);
  if (existe_deja)
    {
      Cerr<<" The synonym "<<synonyme_info.n<<" exists as a class which is forbidden !!!!"<<finl;
      Process::exit();
    }
  existe_deja = search_synonyme_info_name(synonyme_info.n, index);
  if (existe_deja)
    {
      Cerr<<" Synonym "<<synonyme_info.n<<" already exists, which is forbidden!!!!"<<finl;
      Process::exit();
    }
  else
    {
// Ajout du synonyme dans le tableau a l'indice "index":
      for (int i = nb_classes; i > index; i--)
        les_synonymes[i] = les_synonymes[i-1];
      les_synonymes[index] = &synonyme_info;
      nb_classes++;
    }
}
References Cerr, Type_info::est_un_type(), Process::exit(), finl, les_synonymes, les_synonymes_memsize, n, nb_classes, and search_synonyme_info_name().
Referenced by Synonyme_info().
est_un_synonyme()
int Synonyme_info::est_un_synonyme (const char * nom) static
Test d'existence d'une classe du synonyme indique
si il existe une classe T dont le Synonyme_info a
le nom nom, alors est_un_synonyme renvoie 1
renvoie le pointeur nul sinon.
Returns
int
Signification: code de retour (0 ou 1)
Contraintes:
Definition at line 258 of file Synonyme_info.cpp.
{
  const Synonyme_info * synonyme = synonyme_info_from_name(nom);
  return (synonyme != 0);
}
References nom(), and synonyme_info_from_name().
Referenced by Type_info::ajouter_type().
hierarchie()
Sortie & Synonyme_info::hierarchie (Sortie & os) static
Ecriture de toute la hierarchie du synonyme considere sur un flux de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Definition at line 232 of file Synonyme_info.cpp.
{
  os << "There is " << nb_classes << " synomyms:" << finl;
  int i= nb_classes;
  while(i--)
    os << les_synonymes[i]->nom() << " <=> "<< les_synonymes[i]->org_name_()<<finl;
  return os << finl<<flush;
}
References finl, les_synonymes, nb_classes, nom(), and org_name_().
Referenced by Process::exit().
nom()
const char * Synonyme_info::nom () const inline
Definition at line 46 of file Synonyme_info.h.
  {
    return n;
  };
References n.
Referenced by est_un_synonyme(), hierarchie(), retirer_synonyme(), search_synonyme_info_name(), and ~Synonyme_info().
operator=()
Synonyme_info & Synonyme_info::operator= (Synonyme_info &) private
Constructeur par copie invalide.
Operateur= invalide
org_name_()
const char * Synonyme_info::org_name_ () const inline
Definition at line 42 of file Synonyme_info.h.
  {
    return org;
  };
References org.
Referenced by hierarchie(), and Deriv_::typer().
retirer_synonyme()
void Synonyme_info::retirer_synonyme (const char * nom) static private
Methode statique appelee par les constructeurs de Synonyme_info pour
ajouter un nouveau synonyme a la liste des synonymes enregistres.
Verifie que le nom du synonyme n'existe pas encore.
Definition at line 155 of file Synonyme_info.cpp.
{
// On cherche ou mettre le synonyme dans le tableau :
  int index;
  int existe_deja = search_synonyme_info_name(nom, index);
  if (!existe_deja)
    {
      Cerr<<"A synonym is suppressed whereas it doesn't exist !!!!!"<<finl;
      Process::exit();
    }
  else
    {
// Ajout du synonyme dans le tableau a l'indice "index":
      for (int i = index; i < nb_classes-1; i++)
        les_synonymes[i] = les_synonymes[i+1];
      nb_classes--;
    }
}
References Cerr, Process::exit(), finl, les_synonymes, nb_classes, nom(), and search_synonyme_info_name().
Referenced by ~Synonyme_info().
search_synonyme_info_name()
int Synonyme_info::search_synonyme_info_name (const char * nom, int & index) static private
Recherche le synonyme de nom "nom" dans la liste de synonymes enregistres
par une recherche binaire.
On compare les chaines converties en majuscules.
On range dans "index" l'indice du synonyme, s'il a ete trouve
et sinon l'indice du synonyme juste apres (dans ce cas, on a
les_synonymes[index-1]->n < nom < les_synonymes[index]->n)
Si le synonyme a ete trouve on renvoie 1, sinon 0.
Definition at line 81 of file Synonyme_info.cpp.
{
  assert(nom != 0);
// [imin..imax] est l'intervalle ou se trouve l'index recherche
  int imin = 0;
  int imax = nb_classes;
  while (imax > imin)
    {
// On a toujours milieu < imax
      int milieu = (imin + imax) / 2;
      int comparaison = strcmp_uppercase(nom, les_synonymes[milieu]->n);
      if (comparaison == 0)
        {
          index = milieu;
          return 1;
        }
      if (comparaison < 0)
        {
// nom < les_synonymes[milieu]
// l'index recherche est donc inferieur ou egal a "milieu"
          imax = milieu;
        }
      else
        {
// nom > les_synonymes[milieu]
// l'index recherche est donc strictement superieur a "milieu"
          imin = milieu + 1;
        }
    }
  index = imax;
  return 0;
}
References les_synonymes, n, nb_classes, nom(), and strcmp_uppercase().
Referenced by ajouter_synonyme(), retirer_synonyme(), and synonyme_info_from_name().
synonyme_info_from_name()
const Synonyme_info * Synonyme_info::synonyme_info_from_name (const char * synonyme_name) static
Methode statique qui renvoie un pointeur vers le Synonyme_info
dont le nom est "synonyme_name". Si synonyme_name n'est pas un synonyme,
renvoie un pointeur nul.
Definition at line 270 of file Synonyme_info.cpp.
{
  const Synonyme_info * synonyme_info = 0;
  if (synonyme_name != 0)
    {
      int index;
      if (search_synonyme_info_name(synonyme_name, index))
        synonyme_info = les_synonymes[index];
    }
  return synonyme_info;
}
References les_synonymes, and search_synonyme_info_name().
Referenced by est_un_synonyme(), and Deriv_::typer().
Member Data Documentation
les_synonymes
const Synonyme_info ** Synonyme_info::les_synonymes =0 static private
Definition at line 74 of file Synonyme_info.h.
Referenced by ajouter_synonyme(), hierarchie(), retirer_synonyme(), search_synonyme_info_name(), synonyme_info_from_name(), and ~Synonyme_info().
les_synonymes_memsize
int Synonyme_info::les_synonymes_memsize =0 static private
Definition at line 80 of file Synonyme_info.h.
Referenced by ajouter_synonyme(), and ~Synonyme_info().
n
const char* Synonyme_info::n private
Definition at line 69 of file Synonyme_info.h.
Referenced by ajouter_synonyme(), nom(), and search_synonyme_info_name().
nb_classes
int Synonyme_info::nb_classes =0 static private
Definition at line 77 of file Synonyme_info.h.
Referenced by ajouter_synonyme(), hierarchie(), retirer_synonyme(), search_synonyme_info_name(), and ~Synonyme_info().
org
const char* Synonyme_info::org private
Definition at line 70 of file Synonyme_info.h.
Referenced by org_name_().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Synonyme_info.h
src/Kernel/Utilitaires/Synonyme_info.cpp