TRUST: Op_Rot_VEFP1B Class Reference
Op_Rot_VEFP1B Class Reference
#include <Op_Rot_VEFP1B.h>
Public Member Functions
Op_Rot_VEFP1B ()
~Op_Rot_VEFP1B ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab vecteur_normal (const int &face, const int &elem) const
const Zone_VEF_PreP1b & zone_Vef () const
void associer_coins (const ArrOfInt &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Rot_VEFP1B & self_cast (Objet_U &)
static const Op_Rot_VEFP1B & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Attributes
ArrOfInt coins
Ref_Zone_VEF la_zone_vef
Ref_Zone_Cl_VEF la_zcl_vef
Detailed Description
Definition at line 32 of file Op_Rot_VEFP1B.h.
Constructor & Destructor Documentation
Op_Rot_VEFP1B::Op_Rot_VEFP1B ()
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
Op_Rot_VEFP1B::~Op_Rot_VEFP1B ()
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
Member Function Documentation
DoubleTab & Op_Rot_VEFP1B::ajouter (const DoubleTab & vorticite, DoubleTab & rot) const [virtual]
Reimplemented from Operateur_base.
Definition at line 96 of file Op_Rot_VEFP1B.cpp.
References IntList::add_if_not(), Cerr, composante(), Objet_U::dimension, Zone_VF::elem_faces(), IntListElem::est_vide(), Process::exit(), Zone_VF::face_voisins(), finl, la_zone_vef, Zone::nb_elem(), Zone_VF::nb_faces(), Zone::nb_som(), Zone::nb_som_elem(), Zone_VF::premiere_face_int(), IntList::size(), Zone::sommet_elem(), Ref_Zone_VEF::valeur(), vecteur_normal(), IntList::vide(), and Zone_dis_base::zone().
Referenced by calculer().
{
  Cerr << "je suis dans OpRot" << finl;
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone& zone = zone_VEF.zone();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  int elem0,elem1;
  int sommet_global,face_opp;
// Quelques variables bien utiles
  DoubleTab vecteur_normal_elem0(dimension);
  DoubleTab vecteur_normal_elem1(dimension);
  DoubleTab vecteur_normal_opp_elem0(dimension);
  DoubleTab vecteur_normal_opp_elem1(dimension);
  IntList sommets_elem0, sommets_elem1;
  IntList faces_opp_elem0,faces_opp_elem1;
// On traite les conditions limites:
// pour l'instant pas de conditions aux limites pour la vorticite.
// Sortie libre = pas de conditions aux limites ????
// On traite les faces internes i.e. sans les conditions aux limites
  int premiere_face_int = zone_VEF.premiere_face_int();
  int nb_faces = zone_VEF.nb_faces();
  if (dimension > 2)
    {
      Cerr << "Erreur OpRot: seul le cas 2D est etudie pour le moment" << finl;
      Process::exit();
    }
  for (int face=premiere_face_int; face<nb_faces; face++)
    {
      int modulo;
      elem0 = face_voisins(face,0);
      elem1 = face_voisins(face,1);
// Calcul du rotationnel de la vorticite: partie P0 de l'inconnue
      /* Calcul du vecteur tangent adequat pour la partie P0 de l'inconnue */
      vecteur_normal_elem0 = vecteur_normal(face,elem0);
      vecteur_normal_elem1 = vecteur_normal(face,elem1);
      /* Calcul du rotationnel de la vorticite proprement dit */
      /* Partie P0 */
      for (int composante=0; composante<dimension; composante++)
        {
          modulo = (1+composante)%dimension;
          rot(face,composante) += pow(-1.,modulo)*
                                  ( vorticite(elem0) * vecteur_normal_elem0(modulo)+
                                    vorticite(elem1) * vecteur_normal_elem1(modulo));
        }
// Calcul du rotationnel de la vorticite: partie P1 de l'inconnue
      /* On a besoin pour chaque triangle de connaitre la liste */
      /* des sommets qui en font parti ainsi que les faces */
      /* opposees a ces sommets */
      if (!sommets_elem0.est_vide()) sommets_elem0.vide();
      if (!sommets_elem1.est_vide()) sommets_elem1.vide();
      if (!faces_opp_elem0.est_vide()) faces_opp_elem0.vide();
      if (!faces_opp_elem1.est_vide()) faces_opp_elem1.vide();
      for (int i=0; i<zone.nb_som_elem(); i++)
        {
          sommets_elem0.add_if_not(zone.sommet_elem(elem0,i));
          faces_opp_elem0.add_if_not(zone_VEF.elem_faces(elem0,i));
          sommets_elem1.add_if_not(zone.sommet_elem(elem1,i));
          faces_opp_elem1.add_if_not(zone_VEF.elem_faces(elem1,i));
        }
      /* Maintenant, on calcule la contribution au rotationnel */
      /* pour la partie P1 de l'inconnue */
      /* ATTENTION: compte tenu de la definition de l'espace */
      /* vectoriel engendrant omega, il NE FAUT PAS tenir compte */
      /* du sommet de plus GRAND numero */
      for (int composante=0; composante<dimension; composante++)
        {
          modulo = (1+composante)%dimension;
//
          /* Partie (w,curl Psi_c e_i) */
//
          double sommation_sommets=0.;
// On fait les calculs pour "elem0"
          for (int i=0; i<sommets_elem0.size(); i++)
            {
              sommet_global = sommets_elem0[i];
// Pour eliminer le dernier sommet
              if (sommet_global != zone.nb_som()-1)
                sommation_sommets += vorticite(zone.nb_elem()+sommet_global);
            }
          rot(face,composante) += -pow(-1.,modulo)/(dimension+1)*
                                  vecteur_normal_elem0(modulo) * sommation_sommets;
// On fait les calculs pour "elem1"
          sommation_sommets=0.;
          for (int i=0; i<sommets_elem1.size(); i++)
            {
              sommet_global = sommets_elem1[i];
// Pour eliminer le dernier sommet
              if (sommet_global != zone.nb_som()-1)
                sommation_sommets += vorticite(zone.nb_elem()+sommet_global);
            }
          rot(face,composante) += -pow(-1.,modulo)/(dimension+1)*
                                  vecteur_normal_elem1(modulo) * sommation_sommets;
//
          /* Fin de partie (w,curl Psi_c e_i) */
//
//
          /* Partie (curl w,Psi_c e_i) */
//
// On fait les calculs pour "elem0"
          sommation_sommets=0.;
          for (int i=0; i<sommets_elem0.size(); i++)
            {
              sommet_global = sommets_elem0[i];
// Pour eliminer le dernier sommet
              if (sommet_global != zone.nb_som()-1)
                {
                  face_opp = faces_opp_elem0[i];
                  vecteur_normal_opp_elem0 = vecteur_normal(face_opp,elem0);
                  sommation_sommets += vorticite(zone.nb_elem()+sommet_global)
                                       * vecteur_normal_opp_elem0(modulo);
                }
            }
          rot(face,composante) += pow(-1.,modulo)/(dimension*(dimension+1))*
                                  sommation_sommets;
// On fait les calculs pour "elem1"
          sommation_sommets=0.;
          for (int i=0; i<sommets_elem1.size(); i++)
            {
              sommet_global = sommets_elem1[i];
// Pour eliminer le dernier sommet
              if (sommet_global != zone.nb_som()-1)
                {
                  face_opp = faces_opp_elem1[i];
                  vecteur_normal_opp_elem1 = vecteur_normal(face_opp,elem1);
                  sommation_sommets += vorticite(zone.nb_elem()+sommet_global)
                                       * vecteur_normal_opp_elem1(modulo);
                }
            }
// C_h^t
          rot(face,composante) += pow(-1.,modulo)/(dimension*(dimension+1))*
                                  sommation_sommets;
//
          /* Fin de partie (curl w,Psi_c e_i) */
//
        } //fin du for sur "composante" pour la partie P1 de l'inconnue
    } //fin du for sur "face"
  return rot;
}
void Op_Rot_VEFP1B::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis, const Champ_Inc &) [virtual]
Implements Operateur_base.
Definition at line 77 of file Op_Rot_VEFP1B.cpp.
References la_zcl_vef, la_zone_vef, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by Op_Diff_RotRot::associer().
{
  const Zone_VEF& zvef = ref_cast(Zone_VEF, zone_dis.valeur());
  const Zone_Cl_VEF& zclvef = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
  la_zone_vef = zvef;
  la_zcl_vef = zclvef;
}
void Op_Rot_VEFP1B::associer_coins (const ArrOfInt & arr)
Definition at line 52 of file Op_Rot_VEFP1B.cpp.
References coins.
{
  coins=arr ;
}
DoubleTab & Op_Rot_VEFP1B::calculer (const DoubleTab & vorticite, DoubleTab & rot) const [virtual]
Reimplemented from Operateur_base.
Definition at line 88 of file Op_Rot_VEFP1B.cpp.
References ajouter().
Referenced by Op_Diff_RotRot::ajouter().
{
  rot = 0;
  return ajouter(vorticite,rot);
}
Objet_U * Op_Rot_VEFP1B::cree_instance () [static]
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
int Op_Rot_VEFP1B::duplique () const [virtual]
Implements Operateur_base.
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
const Type_info * Op_Rot_VEFP1B::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
const Type_info * Op_Rot_VEFP1B::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
Sortie & Op_Rot_VEFP1B::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Operateur_base.
Definition at line 40 of file Op_Rot_VEFP1B.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Op_Rot_VEFP1B::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Operateur_base.
Definition at line 46 of file Op_Rot_VEFP1B.cpp.
{
  return s ;
}
const Op_Rot_VEFP1B & Op_Rot_VEFP1B::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
Op_Rot_VEFP1B & Op_Rot_VEFP1B::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
unsigned Op_Rot_VEFP1B::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 36 of file Op_Rot_VEFP1B.cpp.
DoubleTab Op_Rot_VEFP1B::vecteur_normal (const int & face, const int & elem) const
Definition at line 277 of file Op_Rot_VEFP1B.cpp.
References composante(), Objet_U::dimension, Zone_VEF::face_normales(), la_zone_vef, Zone_VEF::oriente_normale(), and Ref_Zone_VEF::valeur().
Referenced by ajouter().
{
  assert(dimension == 2);
  const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  DoubleTab le_vecteur_normal(dimension);
  for (int composante = 0; composante<dimension; composante++)
    le_vecteur_normal(composante) = zone_VEF.face_normales(face,composante)
                                    * zone_VEF.oriente_normale(face,elem);
  return le_vecteur_normal;
}
const Zone_VEF_PreP1b & Op_Rot_VEFP1B::zone_Vef () const
Definition at line 58 of file Op_Rot_VEFP1B.cpp.
References la_zone_vef, ref_cast, and Ref_Zone_VEF::valeur().
{
  return ref_cast(Zone_VEF_PreP1b, la_zone_vef.valeur());
}
Member Data Documentation
ArrOfInt Op_Rot_VEFP1B::coins [protected]
Definition at line 62 of file Op_Rot_VEFP1B.h.
Referenced by associer_coins().
const Type_info Op_Rot_VEFP1B::info_obj [static]
Reimplemented from Operateur_base.
Definition at line 35 of file Op_Rot_VEFP1B.h.
Ref_Zone_Cl_VEF Op_Rot_VEFP1B::la_zcl_vef [protected]
Definition at line 64 of file Op_Rot_VEFP1B.h.
Referenced by associer().
Ref_Zone_VEF Op_Rot_VEFP1B::la_zone_vef [protected]
Definition at line 63 of file Op_Rot_VEFP1B.h.
Referenced by ajouter(), associer(), vecteur_normal(), and zone_Vef().
The documentation for this class was generated from the following files:
src/P1NCP1B/Operateurs/Op_Rot_VEFP1B.h
src/P1NCP1B/Operateurs/Op_Rot_VEFP1B.cpp