TRUST: Schema_Euler_explicite Class Reference
Schema_Euler_explicite Class Reference
classe Schema_Euler_explicite
Cette classe represente un schema en temps d'Euler explicite:
U(n+1) = U(n) + dt*(dU/dt)(n)
#include <Schema_Euler_explicite.h>
Public Member Functions
Schema_Euler_explicite ()
~Schema_Euler_explicite ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual int nb_valeurs_temporelles () const
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
virtual int nb_valeurs_futures () const
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
virtual double temps_futur (int i) const
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
virtual double temps_defaut () const
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
virtual int faire_un_pas_de_temps_eqn_base (Equation_base &)
Effectue un pas de temps d'Euler explicite
sur l'equation passee en parametre.
void completer ()
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Schema_Euler_explicite & self_cast (Objet_U &)
static const
Schema_Euler_explicite & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Detailed Description
classe Schema_Euler_explicite
Cette classe represente un schema en temps d'Euler explicite:
U(n+1) = U(n) + dt*(dU/dt)(n)
Definition at line 41 of file Schema_Euler_explicite.h.
Constructor & Destructor Documentation
Schema_Euler_explicite::Schema_Euler_explicite ()
Definition at line 29 of file Schema_Euler_explicite.cpp.
Schema_Euler_explicite::~Schema_Euler_explicite ()
Definition at line 29 of file Schema_Euler_explicite.cpp.
Member Function Documentation
void Schema_Euler_explicite::completer (void) [inline, virtual]
Implements Schema_Temps_base.
Definition at line 69 of file Schema_Euler_explicite.h.
{
  /*   Cerr << "Here is : Euler_Explicite::completer()" << finl; */
}
Objet_U * Schema_Euler_explicite::cree_instance () [static]
Definition at line 29 of file Schema_Euler_explicite.cpp.
int Schema_Euler_explicite::duplique () const [virtual]
Implements Schema_Temps_base.
Definition at line 29 of file Schema_Euler_explicite.cpp.
int Schema_Euler_explicite::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) [virtual]
Effectue un pas de temps d'Euler explicite
sur l'equation passee en parametre.
< Un
< Un+1
Implements Schema_Temps_base.
Definition at line 124 of file Schema_Euler_explicite.cpp.
References Champ_Inc::avancer(), Equation_base::derivee_en_temps_inco(), Schema_Temps_base::dt_, Champ_Inc::futur(), Zone_Cl_dis::imposer_cond_lim(), Equation_base::inconnue(), Schema_Temps_base::pas_de_temps(), Champ_Inc::reculer(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), Champ_Inc::valeurs(), and Equation_base::zone_Cl_dis().
{
  DoubleTab& present = eqn.inconnue().valeurs(); //!< Un
  DoubleTab& futur   = eqn.inconnue().futur();   //!< Un+1
  DoubleTab dudt(futur);
// Boundary conditions applied on Un+1:
  eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
// On tourne la roue pour que les operateurs utilisent les champs au temps futur
  eqn.inconnue().avancer();
  eqn.derivee_en_temps_inco(dudt);
  eqn.inconnue().reculer();
// Un+1=Un+dt_*dU/dt
  futur=dudt;
  futur*=dt_;
  futur+=present;
  eqn.zone_Cl_dis()->imposer_cond_lim(eqn.inconnue(),temps_courant()+pas_de_temps());
  update_critere_statio(dudt, eqn);
  return 1;
}
const Type_info * Schema_Euler_explicite::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 29 of file Schema_Euler_explicite.cpp.
const Type_info * Schema_Euler_explicite::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 29 of file Schema_Euler_explicite.cpp.
int Schema_Euler_explicite::nb_valeurs_futures () const [virtual]
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
Definition at line 92 of file Schema_Euler_explicite.cpp.
{
  return 1 ;
}
int Schema_Euler_explicite::nb_valeurs_temporelles () const [virtual]
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
Implements Schema_Temps_base.
Definition at line 84 of file Schema_Euler_explicite.cpp.
{
  return 2 ;
}
Sortie & Schema_Euler_explicite::printOn (Sortie & s) const [protected, virtual]
Simple appel a: Schema_Temps_base::printOn(Sortie&)
Ecrit le schema en temps sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 47 of file Schema_Euler_explicite.cpp.
{
  return  Schema_Temps_base::printOn(s);
}
Entree & Schema_Euler_explicite::readOn (Entree & s) [protected, virtual]
Lit le schema en temps a partir d'un flot d'entree.
Simple appel a: Schema_Temps_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Schema_Temps_base.
Definition at line 68 of file Schema_Euler_explicite.cpp.
{
  return Schema_Temps_base::readOn(s) ;
}
const Schema_Euler_explicite & Schema_Euler_explicite::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Schema_Temps_base.
Definition at line 29 of file Schema_Euler_explicite.cpp.
Schema_Euler_explicite & Schema_Euler_explicite::self_cast (Objet_U & r) [static]
Reimplemented from Schema_Temps_base.
Definition at line 29 of file Schema_Euler_explicite.cpp.
unsigned Schema_Euler_explicite::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 29 of file Schema_Euler_explicite.cpp.
double Schema_Euler_explicite::temps_defaut () const [virtual]
Renvoie le le temps le temps que doivent rendre les champs a
l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 110 of file Schema_Euler_explicite.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  return temps_courant()+pas_de_temps();
}
double Schema_Euler_explicite::temps_futur (int i) const [virtual]
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
Definition at line 100 of file Schema_Euler_explicite.cpp.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
{
  assert(i==1);
  return temps_courant()+pas_de_temps();
}
Member Data Documentation
const Type_info Schema_Euler_explicite::info_obj [static]
Reimplemented from Schema_Temps_base.
Definition at line 44 of file Schema_Euler_explicite.h.
The documentation for this class was generated from the following files:
src/Kernel/Schemas_Temps/Schema_Euler_explicite.h
src/Kernel/Schemas_Temps/Schema_Euler_explicite.cpp