TRUST: Op_Diff_negligeable Class Reference
Op_Diff_negligeable Class Reference
Classe Op_Diff_negligeable
Cette classe represente un operateur de diffusion negligeable.
Lorsqu'un operateur de ce type est utilise dans une equation
cela revient a negliger le terme de diffusion.
Les methodes de modification et de participation a un calcul de
l'operateur sont en fait des appels aux meme methodes de
Operateur_negligeable qui ne font rien.
#include <Op_Diff_negligeable.h>
Public Member Functions
Op_Diff_negligeable ()
~Op_Diff_negligeable ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
Ajoute la contribution de l'operateur a un tableau passe en parametre.
Simple appel a Operateur_negligeable::ajouter(const DoubleTab&,DoubleTab&)
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
Initialise le parametre tableau avec la contribution
de l'operateur negligeable: initialise le tableau a ZERO.
Simple appel a Operateur_negligeable::(calculer(const DoubleTab&, DoubleTab&)
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::mettre_a_jour(double)
void contribuer_au_second_membre (DoubleTab &) const
on ajoute la contribution du second membre.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void mettre_a_jour (double)
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN.
void associer_diffusivite (const Champ_base &)
Associe la diffusivite a l'operateur.
const Champ_base & diffusivite () const
Renvoie le champ representant la diffusivite.
void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &resu, const tabs_t &semi_impl={}) const
void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_negligeable & self_cast (Objet_U &)
static const Op_Diff_negligeable & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime la diffusivite sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit la diffusivite a partir d'un flot d'entree.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &)
Associe divers objets a un operateurs negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::associer(const Zone_dis&,
const Zone_Cl_dis&,
const Champ_Inc&)
Protected Attributes
Ref_Champ_base la_diffusivite
Detailed Description
Classe Op_Diff_negligeable
Cette classe represente un operateur de diffusion negligeable.
Lorsqu'un operateur de ce type est utilise dans une equation
cela revient a negliger le terme de diffusion.
Les methodes de modification et de participation a un calcul de
l'operateur sont en fait des appels aux meme methodes de
Operateur_negligeable qui ne font rien.
Definition at line 45 of file Op_Diff_negligeable.h.
Constructor & Destructor Documentation
Op_Diff_negligeable::Op_Diff_negligeable ()
Definition at line 28 of file Op_Diff_negligeable.cpp.
Op_Diff_negligeable::~Op_Diff_negligeable ()
Definition at line 28 of file Op_Diff_negligeable.cpp.
Member Function Documentation
DoubleTab & Op_Diff_negligeable::ajouter (const DoubleTab & x, DoubleTab & y) const [inline]
Ajoute la contribution de l'operateur a un tableau passe en parametre.
Simple appel a Operateur_negligeable::ajouter(const DoubleTab&,DoubleTab&)
Returns:
DoubleTab&
Signification: le parametre d'entree y non modifie
Contraintes:
Reimplemented from Operateur_negligeable.
Definition at line 111 of file Op_Diff_negligeable.h.
{
  return Operateur_negligeable::ajouter(x,y);
}
void Op_Diff_negligeable::ajouter_blocs (matrices_t matrices, DoubleTab & resu) const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 73 of file Op_Diff_negligeable.h.
{ }) const { };
void Op_Diff_negligeable::ajouter_flux (const DoubleTab & inconnue, DoubleTab & contribution) const [virtual]
Reimplemented from Operateur_base.
Definition at line 143 of file Op_Diff_negligeable.cpp.
{
// nothing to do
}
void Op_Diff_negligeable::associer (const Zone_dis & z, const Zone_Cl_dis & zcl, const Champ_Inc & ch) [inline, protected]
Associe divers objets a un operateurs negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::associer(const Zone_dis&,
const Zone_Cl_dis&,
const Champ_Inc&)
Reimplemented from Operateur_negligeable.
Definition at line 221 of file Op_Diff_negligeable.h.
{
  Operateur_negligeable::associer(z, zcl, ch);
}
void Op_Diff_negligeable::associer_champ_masse_volumique (const Champ_base & ch) [inline, virtual]
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
Reimplemented from Support_Champ_Masse_Volumique.
Definition at line 229 of file Op_Diff_negligeable.h.
{
}
void Op_Diff_negligeable::associer_diffusivite (const Champ_base & ch) [virtual]
Associe la diffusivite a l'operateur.
Implements Operateur_Diff_base.
Definition at line 96 of file Op_Diff_negligeable.cpp.
References la_diffusivite.
{
  la_diffusivite=ch;
}
DoubleTab & Op_Diff_negligeable::calculer (const DoubleTab & x, DoubleTab & y) const [inline]
Initialise le parametre tableau avec la contribution
de l'operateur negligeable: initialise le tableau a ZERO.
Simple appel a Operateur_negligeable::(calculer(const DoubleTab&, DoubleTab&)
Returns:
DoubleTab&
Signification: le tableau d'entree y mis a zero
Contraintes:
Reimplemented from Operateur_negligeable.
Definition at line 139 of file Op_Diff_negligeable.h.
{
  return Operateur_negligeable::calculer(x,y);
}
void Op_Diff_negligeable::calculer_flux (const DoubleTab & inconnue, DoubleTab & flux) const [virtual]
Reimplemented from Operateur_base.
Definition at line 148 of file Op_Diff_negligeable.cpp.
{
  flux = 0.0;
}
void Op_Diff_negligeable::calculer_pour_post (Champ & espace_stockage, const Nom & option, int comp) const [virtual]
Reimplemented from Operateur_base.
Definition at line 121 of file Op_Diff_negligeable.cpp.
References Operateur_base::calculer_dt_stab(), and Champ::valeurs().
{
  if (Motcle(option)=="stabilite")
    {
      DoubleTab& es_valeurs = espace_stockage->valeurs();
      es_valeurs = calculer_dt_stab();
    }
  else
    Operateur_base::calculer_pour_post(espace_stockage,option,comp);
}
void Op_Diff_negligeable::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 74 of file Op_Diff_negligeable.h.
{ };
void Op_Diff_negligeable::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & amatrice) const [inline, virtual]
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN
Simple appel a Operateur_negligeable::mettre_a_jour(double)
on assemble la matrice.
Reimplemented from Operateur_base.
Definition at line 163 of file Op_Diff_negligeable.h.
{
  ;
}
void Op_Diff_negligeable::contribuer_au_second_membre (DoubleTab & resu) const [inline, virtual]
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
Definition at line 172 of file Op_Diff_negligeable.h.
{
  ;
}
Objet_U * Op_Diff_negligeable::cree_instance () [static]
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
const Champ_base & Op_Diff_negligeable::diffusivite () const [virtual]
Renvoie le champ representant la diffusivite.
Returns:
Champ_Don_base&
Signification: le champ representant la diffusivite
Contraintes:
Implements Operateur_Diff_base.
Definition at line 116 of file Op_Diff_negligeable.cpp.
References la_diffusivite, and Ref_Champ_base::valeur().
{
  return la_diffusivite.valeur();
}
void Op_Diff_negligeable::dimensionner (Matrice_Morse & mat) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 183 of file Op_Diff_negligeable.h.
{
  ;
}
void Op_Diff_negligeable::dimensionner_blocs (matrices_t matrices) const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 72 of file Op_Diff_negligeable.h.
{ }) const { };
int Op_Diff_negligeable::duplique () const [virtual]
Implements Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
const Type_info * Op_Diff_negligeable::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
Motcle Op_Diff_negligeable::get_localisation_pour_post (const Nom & option) const [virtual]
Reimplemented from Operateur_base.
Definition at line 132 of file Op_Diff_negligeable.cpp.
{
  Motcle loc;
  if (Motcle(option)=="stabilite")
    loc = "elem";
  else if (Motcle(option)=="flux_bords" || Motcle(option)=="flux_surfacique_bords")
    loc = "face";
  return loc;
}
virtual int Op_Diff_negligeable::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 68 of file Op_Diff_negligeable.h.
  {
    return 1;
  };
const Type_info * Op_Diff_negligeable::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
void Op_Diff_negligeable::mettre_a_jour (double) [inline]
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN.
Reimplemented from Operateur_negligeable.
Definition at line 188 of file Op_Diff_negligeable.h.
{
  Operateur_negligeable::mettre_a_jour(temps);
}
void Op_Diff_negligeable::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 178 of file Op_Diff_negligeable.h.
{
  ;
}
Sortie & Op_Diff_negligeable::printOn (Sortie & os) const [protected, virtual]
Imprime la diffusivite sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 56 of file Op_Diff_negligeable.cpp.
References la_diffusivite.
{
  return os << la_diffusivite;
}
Entree & Op_Diff_negligeable::readOn (Entree & is) [protected, virtual]
Lit la diffusivite a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 76 of file Op_Diff_negligeable.cpp.
References la_diffusivite.
{
  return is >> la_diffusivite;
}
const Op_Diff_negligeable & Op_Diff_negligeable::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
Op_Diff_negligeable & Op_Diff_negligeable::self_cast (Objet_U & r) [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
unsigned Op_Diff_negligeable::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Op_Dift_negligeable.
Definition at line 28 of file Op_Diff_negligeable.cpp.
Member Data Documentation
const Type_info Op_Diff_negligeable::info_obj [static]
Reimplemented from Operateur_Diff_base.
Reimplemented in Op_Dift_negligeable.
Definition at line 48 of file Op_Diff_negligeable.h.
Ref_Champ_base Op_Diff_negligeable::la_diffusivite [protected]
Definition at line 74 of file Op_Diff_negligeable.h.
Referenced by associer_diffusivite(), diffusivite(), printOn(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Operateurs/Op_Diff_negligeable.h
src/Kernel/Operateurs/Op_Diff_negligeable.cpp