TRUST: Traitement_particulier_NS_canal_VEF Class Reference
Traitement_particulier_NS_canal_VEF Class Reference
classe Traitement_particulier_NS_canal_VEF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
#include <Traitement_particulier_NS_canal_VEF.h>
Public Member Functions
Traitement_particulier_NS_canal_VEF ()
~Traitement_particulier_NS_canal_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & lire (const Motcle &, Entree &)
Entree & lire (Entree &) override
Public Member Functions inherited from Traitement_particulier_NS_canal
~Traitement_particulier_NS_canal () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Traitement_particulier_NS_canal ()
Entree & lire (Entree &) override
void preparer_calcul_particulier () override
void reprendre_stat () override
void sauver_stat () const override
void post_traitement_particulier () override
void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double) override
int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
int comprend_champ (const Motcle &mot) const
Public Member Functions inherited from Traitement_particulier_NS_base
Traitement_particulier_NS_base ()
~Traitement_particulier_NS_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_eqn (const Equation_base &)
virtual void preparer_calcul_particulier (void)=0
virtual void post_traitement_particulier (void)=0
virtual Entree & lire (Entree &is)=0
virtual void sauver_stat (void) const =0
virtual void reprendre_stat (void)=0
virtual void en_cours_de_resolution (int, DoubleTab &, DoubleTab &, double)=0
void creer_champ (const Motcle &) override
const Champ_base & get_champ (const Motcle &nom) const override
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Traitement_particulier_NS_canal_VEF & self_cast (Objet_U &)
static const Traitement_particulier_NS_canal_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_canal
static const Type_info * info ()
static Traitement_particulier_NS_canal & self_cast (Objet_U &)
static const Traitement_particulier_NS_canal & self_cast (const Objet_U &)
Static Public Member Functions inherited from Traitement_particulier_NS_base
static const Type_info * info ()
static Traitement_particulier_NS_base & self_cast (Objet_U &)
static const Traitement_particulier_NS_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_canal
static const Type_info info_obj
Static Public Attributes inherited from Traitement_particulier_NS_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void remplir_Y (DoubleVect &, DoubleVect &, int &) const override
void calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab &) const override
void calculer_moyenne_spatiale_nut (DoubleTab &) const override
void calculer_moyenne_spatiale_Temp (DoubleTab &) const override
Protected Member Functions inherited from Traitement_particulier_NS_canal
Sortie & printOn (Sortie &x) const override
Entree & readOn (Entree &) override
void reprendre_stat_canal (DoubleTab &, const Nom &)
void sauver_stat_canal (const DoubleTab &, const Nom &) const
virtual void remplir_Y (DoubleVect &, DoubleVect &, int &) const =0
virtual void remplir_Tab_recap (IntTab &) const
void remplir_reordonne_Y_tot (const DoubleVect &, DoubleVect &) const
virtual void calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab &) const =0
virtual void calculer_moyenne_spatiale_nut (DoubleTab &) const =0
virtual void calculer_moyenne_spatiale_Temp (DoubleTab &) const =0
void calcul_reynolds_tau ()
void ecriture_fichiers_moy_vitesse_rho_mu (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_nut (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_Temp (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_vitesse_rho_mu_old (const DoubleTab &, const Nom &, const double, const int) const
void ecriture_fichiers_moy_Temp_old (const DoubleTab &, const Nom &, const double, const int) const
Sortie & printOn (Sortie &x) const override
Impression de l'equation sur un flot de sortie.
Simple appel a Equation_base::printOn(Sortie&).
Entree & readOn (Entree &) override
Lit les specifications de l'equation de Navier Stokes a
partir d'un flot d'entree.
Simple appel a Navier_Stokes_std::readOn(Entree&)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Additional Inherited Members
Protected Attributes inherited from Traitement_particulier_NS_canal
int Ny
int Nval
int Nphase
DoubleTab val_moy_tot
DoubleTab val_moy_temp
DoubleTab val_moy_phase
DoubleVect Y
DoubleVect Y_tot
DoubleVect compt
DoubleVect compt_tot
IntVect Nb_ech_phase
nombre d'echantillons par phase
IntTab Tab_recap
double w
double freq
int ind_phase
int oui_profil_nu_t
int oui_profil_Temp
int oui_repr
int oui_pulse
double temps_deb
double temps_fin
double debut_phase
double dt_impr_moy_spat
double dt_impr_moy_temp
Nom fich_repr
Ref_Champ_base Temp
DoubleVect uv_moy_temp
DoubleVect wv_moy_temp
DoubleVect uw_moy_temp
DoubleVect u2_moy_temp
DoubleVect v2_moy_temp
DoubleVect w2_moy_temp
DoubleVect nu_t_temp
Protected Attributes inherited from Traitement_particulier_NS_base
Ref_Navier_Stokes_std mon_equation
Champs_compris champs_compris_
Detailed Description
classe Traitement_particulier_NS_canal_VEF
Cette classe permet de faire les traitements particuliers
pour le calcul d'un canal plan :
* conservation du debit
* calculs de moyennes
Definition at line 35 of file Traitement_particulier_NS_canal_VEF.h.
Constructor & Destructor Documentation
Traitement_particulier_NS_canal_VEF()
Traitement_particulier_NS_canal_VEF::Traitement_particulier_NS_canal_VEF ()
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
~Traitement_particulier_NS_canal_VEF()
Traitement_particulier_NS_canal_VEF::~Traitement_particulier_NS_canal_VEF ()
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
Member Function Documentation
calculer_moyenne_spatiale_nut()
void Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
Definition at line 220 of file Traitement_particulier_NS_canal_VEF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const DoubleTab& xv = zone_VEF.xv();
  const Equation_base& N_S_Turb  = mon_equation.valeur();
  const RefObjU& modele_turbulence_hydr = N_S_Turb.get_modele(TURBULENCE);
  const Mod_turb_hyd_base& le_modele = ref_cast(Mod_turb_hyd_base,modele_turbulence_hydr.valeur());
  const DoubleTab& nu_t = le_modele.viscosite_turbulente().valeurs();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  double y;
  int nb_faces = zone_VEF.nb_faces();
  int num_face,i,elem0,elem1;
  const ArrOfInt& faces_doubles = zone_VEF.faces_doubles();
  double c;
  for (num_face=0; num_face<nb_faces; num_face++)
    {
      c = (faces_doubles[num_face]==1) ? 0.5 : 1. ;
      y=xv(num_face,1);
      for (i=0; i<Ny; i++)
        if(est_egal(y,Y[i])) break;
      elem0 = face_voisins(num_face,0);
      elem1 = face_voisins(num_face,1);
      if (elem1!=-1)
        {
          val_moy(i,12) += c*0.5*(nu_t[elem0]+nu_t[elem1]);
        }
      else
        {
          val_moy(i,12) += c*nu_t[elem0];
        }
    }
}
References est_egal(), Zone_VF::face_voisins(), Zone_VF::faces_doubles(), Equation_base::get_modele(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Zone_VF::nb_faces(), Traitement_particulier_NS_canal::Ny, ref_cast, TURBULENCE, Ref_Objet_U::valeur(), Ref_Navier_Stokes_std::valeur(), Champ_Fonc::valeurs(), Mod_turb_hyd_base::viscosite_turbulente(), Zone_VF::xv(), Traitement_particulier_NS_canal::Y, and Champ_Inc::zone_dis_base().
calculer_moyenne_spatiale_Temp()
void Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
Definition at line 259 of file Traitement_particulier_NS_canal_VEF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const DoubleTab& xv = zone_VEF.xv();
  const DoubleTab& temperature = Temp.valeur().valeurs();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  double y,u,v,wl,T;
  int nb_faces = zone_VEF.nb_faces();
  int num_face,i;
  const ArrOfInt& faces_doubles = zone_VEF.faces_doubles();
  double c;
  for (num_face=0; num_face<nb_faces; num_face++)
    {
      c = (faces_doubles[num_face]==1) ? 0.5 : 1. ;
      y=xv(num_face,1);
      T = temperature[num_face];
      u = vitesse(num_face,0);
      v = vitesse(num_face,1);
      for (i=0; i<Ny; i++)
        if(est_egal(y,Y[i])) break;
      val_moy(i,13) += c*T;
      val_moy(i,14) += c*T*T;
      val_moy(i,15) += c*u*T;
      val_moy(i,16) += c*v*T;
      if(Objet_U::dimension==3)
        {
          wl = vitesse(num_face,2);
          val_moy(i,17) += c*wl*T;
        }
    }
}
References Objet_U::dimension, est_egal(), Zone_VF::faces_doubles(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Zone_VF::nb_faces(), Traitement_particulier_NS_canal::Ny, ref_cast, Traitement_particulier_NS_canal::Temp, Ref_Champ_base::valeur(), Champ_Inc::valeurs(), Champ_Proto::valeurs(), Zone_VF::xv(), Traitement_particulier_NS_canal::Y, and Champ_Inc::zone_dis_base().
calculer_moyenne_spatiale_vitesse_rho_mu()
void Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
Definition at line 138 of file Traitement_particulier_NS_canal_VEF.cpp.
{
  const Zone_dis_base& zdisbase=mon_equation->inconnue().zone_dis_base();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const DoubleTab& xv = zone_VEF.xv();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& vitesse = mon_equation->inconnue().valeurs();
  double y,u,v,wl;
  int nb_faces = zone_VEF.nb_faces();
  int num_face,i,elem0,elem1;
  const ArrOfInt& faces_doubles = zone_VEF.faces_doubles();
  double c;
  const Fluide_base& le_fluide = ref_cast(Fluide_base,mon_equation->milieu());
  const DoubleTab& visco_dyn = le_fluide.viscosite_dynamique()->valeurs();
  const DoubleTab& tab_rho_face = le_fluide.masse_volumique().valeurs();
  int taille_mu=visco_dyn.dimension(0);
  int taille_rho=tab_rho_face.dimension(0);
  if (visco_dyn.nb_dim()>2)
    {
      Cerr<<"Error in Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu()"<<finl;
      Process::exit();
    }
  for (num_face=0; num_face<nb_faces; num_face++)
    {
      c = (faces_doubles[num_face]==1) ? 0.5 : 1. ;
      y=xv(num_face,1);
      u = vitesse(num_face,0);
      v = vitesse(num_face,1);
      for (i=0; i<Ny; i++)
        if(est_egal(y,Y[i])) break;
      val_moy(i,0) += c*u;
      val_moy(i,1) += c*v;
      val_moy(i,3) += c*u*u;
      val_moy(i,4) += c*v*v;
      val_moy(i,6) += c*u*v;
      if(dimension==2)   val_moy(i,9) += c*sqrt(u*u);      //vitesse tangentielle pour calcul du frottement
      if(dimension==3)
        {
          wl = vitesse(num_face,2);
          val_moy(i,2) += c*wl;
          val_moy(i,5) += c*wl*wl;
          val_moy(i,7) += c*u*wl;
          val_moy(i,8) += c*v*wl;
          val_moy(i,9) += c*sqrt(u*u+wl*wl);      //vitesse tangentielle pour calcul du frottement
        }
      if (taille_rho==1)  val_moy(i,10) += c*tab_rho_face(0,0);
      else                val_moy(i,10) += c*tab_rho_face[num_face];
      elem0 = face_voisins(num_face,0);
      elem1 = face_voisins(num_face,1);
      if (taille_mu==1)
        val_moy(i,11) += c*visco_dyn(0,0);
      else
        {
          if (elem1!=-1)
            {
              val_moy(i,11) += c*0.5*(visco_dyn(elem0,0)+visco_dyn(elem1,0));
            }
          else
            {
              val_moy(i,11) += c*visco_dyn(elem0,0);
            }
        }
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, est_egal(), Process::exit(), Zone_VF::face_voisins(), Zone_VF::faces_doubles(), finl, Navier_Stokes_std::inconnue(), Milieu_base::masse_volumique(), Navier_Stokes_std::milieu(), Traitement_particulier_NS_base::mon_equation, TRUSTTab< _TYPE_ >::nb_dim(), Zone_VF::nb_faces(), Traitement_particulier_NS_canal::Ny, ref_cast, Champ::valeurs(), Champ_Don::valeurs(), Champ_Inc::valeurs(), Fluide_base::viscosite_dynamique(), Zone_VF::xv(), Traitement_particulier_NS_canal::Y, and Champ_Inc::zone_dis_base().
cree_instance()
Objet_U * Traitement_particulier_NS_canal_VEF::cree_instance () static
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
duplique()
int Traitement_particulier_NS_canal_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
get_info()
const Type_info * Traitement_particulier_NS_canal_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
info()
const Type_info * Traitement_particulier_NS_canal_VEF::info () static
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
lire() [1/2]
Entree & Traitement_particulier_NS_canal_VEF::lire (const Motcle & , Entree &)
lire() [2/2]
Entree & Traitement_particulier_NS_canal_VEF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 66 of file Traitement_particulier_NS_canal_VEF.cpp.
{
  return Traitement_particulier_NS_canal::lire(is);
}
References Traitement_particulier_NS_canal::lire().
printOn()
Sortie & Traitement_particulier_NS_canal_VEF::printOn (Sortie & is) const override protected virtual
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 41 of file Traitement_particulier_NS_canal_VEF.cpp.
{
  return is;
}
readOn()
Entree & Traitement_particulier_NS_canal_VEF::readOn (Entree & is) override protected virtual
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Traitement_particulier_NS_canal.
Definition at line 61 of file Traitement_particulier_NS_canal_VEF.cpp.
{
  return is;
}
remplir_Y()
void Traitement_particulier_NS_canal_VEF::remplir_Y (DoubleVect & tabY, DoubleVect & tabcompt, int & aNy) const override protected virtual
Implements Traitement_particulier_NS_canal.
Definition at line 71 of file Traitement_particulier_NS_canal_VEF.cpp.
{
// On va initialiser les differents parametres membres de la classe
// utiles au calcul des differentes moyennes
// Initialisation de : Y, compt
  const Zone_dis_base& zdisbase = mon_equation->inconnue().zone_dis_base();
  const Zone_VF& zone_VF=ref_cast(Zone_VF, zdisbase);
  const DoubleTab& xv = zone_VF.xv();
  const Zone_VEF& zone_VEF=ref_cast(Zone_VEF, zdisbase);
  const ArrOfInt& faces_doubles = zone_VEF.faces_doubles();
  int nb_faces = zone_VF.nb_faces();
  int num_face,j,indic,trouve;
  double y;
  j=0;
  indic = 0;
  tabY.resize(200);
  tabcompt.resize(200);
  tabY = -100.;
  tabcompt = 0;
// Remplissage du tableau Y
//
// GF PQ. on ajoute 2 a compt dans le cas des faces standards, 1 pour les faces doubles
// et on divise compt a la fin par 2.
// pour etre coherent sur le nombre de faces vis a vis de calculer_moyenne_spatiale_vitesse_rho_mu
  for (num_face=0; num_face<nb_faces; num_face++)
    {
      int c = (faces_doubles[num_face]==1) ? 1 : 2 ;
      y = xv(num_face,1);
      trouve = 0;
      for (j=0; j<indic+1; j++)
        {
          if(est_egal(y,tabY[j]))
            {
              tabcompt[j] +=c;
              j=indic+1;
              trouve = 1;
              break;
            }
        }
      if (trouve==0)
        {
          tabY[indic]=y;
          tabcompt[indic] +=c;
          indic++;
          tabY.resize(indic+1);
          tabY(indic)=-100.;
          tabcompt.resize(indic+1);
        }
    }
  aNy = indic;
  tabY.resize(aNy);
  tabcompt.resize(aNy);
  tabcompt/=2;
}
References est_egal(), Zone_VF::faces_doubles(), Navier_Stokes_std::inconnue(), Traitement_particulier_NS_base::mon_equation, Zone_VF::nb_faces(), ref_cast, TRUSTVect< _TYPE_ >::resize(), Zone_VF::xv(), and Champ_Inc::zone_dis_base().
self_cast() [1/2]
const Traitement_particulier_NS_canal_VEF & Traitement_particulier_NS_canal_VEF::self_cast (const Objet_U & r) static
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
self_cast() [2/2]
Traitement_particulier_NS_canal_VEF & Traitement_particulier_NS_canal_VEF::self_cast (Objet_U & r) static
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
taille_memoire()
unsigned Traitement_particulier_NS_canal_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 24 of file Traitement_particulier_NS_canal_VEF.cpp.
Member Data Documentation
info_obj
const Type_info Traitement_particulier_NS_canal_VEF::info_obj static
Definition at line 37 of file Traitement_particulier_NS_canal_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Traitement_particulier_NS_canal_VEF.h
src/VEF/Traitement_particulier_NS_canal_VEF.cpp