TRUST: Eval_Darcy_VEF_Face Class Reference
Eval_Darcy_VEF_Face Class Reference
class Eval_Darcy_VEF_Face
#include <Eval_Darcy_VEF_Face.h>
Public Member Functions
Eval_Darcy_VEF_Face ()
Eval_Darcy_VEF_Face (const Eval_Darcy_VEF_Face &eval)
void mettre_a_jour () override
double calculer_terme_source_standard (int) const override
void calculer_terme_source_standard (int, DoubleVect &) const override
double calculer_terme_source_non_standard (int) const override
void calculer_terme_source_non_standard (int, DoubleVect &) const override
void associer (const Champ_Don &)
associe le champ de diffusivite
void associer (const Champ_Inc &)
double & getPorosite ()
Public Member Functions inherited from Evaluateur_Source_VEF_Face
Evaluateur_Source_VEF_Face ()
Evaluateur_Source_VEF_Face (const Evaluateur_Source_VEF_Face &)
void completer () override
virtual double calculer_terme_source_standard (int) const =0
virtual double calculer_terme_source_non_standard (int) const =0
virtual void calculer_terme_source_standard (int, DoubleVect &) const =0
virtual void calculer_terme_source_non_standard (int, DoubleVect &) const =0
void changer_volumes_entrelaces_Cl (DoubleVect &) override
Public Member Functions inherited from Evaluateur_Source_VEF
Evaluateur_Source_VEF ()
virtual ~Evaluateur_Source_VEF ()
Evaluateur_Source_VEF (const Evaluateur_Source_VEF &)
void associer_zones (const Zone_dis_base &, const Zone_Cl_dis_base &)
virtual void mettre_a_jour ()=0
virtual void completer ()=0
virtual void changer_volumes_entrelaces_Cl (DoubleVect &)=0
Public Attributes
Modele_Permeabilite modK
Protected Member Functions
void calculer_terme_source (int, DoubleVect &, const DoubleVect &) const
Protected Attributes
Ref_Champ_Inc vitesse
Ref_Champ_Don_base diffusivite_
DoubleTab db_diffusivite
double porosite
Protected Attributes inherited from Evaluateur_Source_VEF_Face
DoubleVect volumes_entrelaces
DoubleVect volumes_entrelaces_Cl
DoubleVect porosite_surf
IntTab face_voisins
Protected Attributes inherited from Evaluateur_Source_VEF
Ref_Zone_VEF la_zone
Ref_Zone_Cl_VEF la_zone_cl
Detailed Description
class Eval_Darcy_VEF_Face
Definition at line 31 of file Eval_Darcy_VEF_Face.h.
Constructor & Destructor Documentation
Eval_Darcy_VEF_Face() [1/2]
Eval_Darcy_VEF_Face::Eval_Darcy_VEF_Face () inline
Definition at line 63 of file Eval_Darcy_VEF_Face.h.
                                               : porosite(1)
{}
Eval_Darcy_VEF_Face() [2/2]
Eval_Darcy_VEF_Face::Eval_Darcy_VEF_Face (const Eval_Darcy_VEF_Face & eval) inline
Definition at line 66 of file Eval_Darcy_VEF_Face.h.
  : Evaluateur_Source_VEF_Face(eval),porosite(1)
{
}
Member Function Documentation
associer() [1/2]
void Eval_Darcy_VEF_Face::associer (const Champ_Don & diffu) inline
associe le champ de diffusivite
Definition at line 73 of file Eval_Darcy_VEF_Face.h.
{
  int nb_faces_tot = la_zone.valeur().nb_faces_tot();
  db_diffusivite.resize(nb_faces_tot,Array_base::NOCOPY_NOINIT);
  diffusivite_ = diffu.valeur();
  mettre_a_jour();
}
References db_diffusivite, diffusivite_, Evaluateur_Source_VEF::la_zone, mettre_a_jour(), Zone_VF::nb_faces_tot(), Array_base::NOCOPY_NOINIT, TRUSTTab< _TYPE_ >::resize(), Deriv_Champ_Don_base::valeur(), and Ref_Zone_VEF::valeur().
Referenced by Source_Darcy_VEF_Face::associer_pb().
associer() [2/2]
void Eval_Darcy_VEF_Face::associer (const Champ_Inc & v) inline
Definition at line 81 of file Eval_Darcy_VEF_Face.h.
{
  vitesse = v;
}
References vitesse.
calculer_terme_source()
void Eval_Darcy_VEF_Face::calculer_terme_source (int num_face, DoubleVect & source, const DoubleVect & volumes) const inline protected
Definition at line 122 of file Eval_Darcy_VEF_Face.h.
{
  int size=source.size();
  for (int i=0; i<size; i++)
    source(i) = -db_diffusivite(num_face)/modK->getK(porosite)*volumes(num_face)*porosite_surf(num_face)*(vitesse->valeurs()(num_face,i));
}
References db_diffusivite, Modele_Permeabilite::getK(), modK, porosite, Evaluateur_Source_VEF_Face::porosite_surf, TRUSTVect< _TYPE_ >::size(), Champ_Inc::valeurs(), and vitesse.
Referenced by calculer_terme_source_non_standard(), and calculer_terme_source_standard().
calculer_terme_source_non_standard() [1/2]
double Eval_Darcy_VEF_Face::calculer_terme_source_non_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 143 of file Eval_Darcy_VEF_Face.h.
{
  Cerr << "Eval_Darcy_VEF_Face::calculer_terme_source_non_standard(int num_face) can't be used on a vector source term." << finl;
  Process::exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
calculer_terme_source_non_standard() [2/2]
void Eval_Darcy_VEF_Face::calculer_terme_source_non_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 133 of file Eval_Darcy_VEF_Face.h.
{
  calculer_terme_source(num_face, source, volumes_entrelaces_Cl);
}
References calculer_terme_source(), and Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
calculer_terme_source_standard() [1/2]
double Eval_Darcy_VEF_Face::calculer_terme_source_standard (int num_face) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 137 of file Eval_Darcy_VEF_Face.h.
{
  Cerr << "Eval_Darcy_VEF_Face::calculer_terme_source_standard(int num_face) can't be used on a vector source term." << finl;
  Process::exit();
  return 0;
}
References Cerr, Process::exit(), and finl.
calculer_terme_source_standard() [2/2]
void Eval_Darcy_VEF_Face::calculer_terme_source_standard (int num_face, DoubleVect & source) const inline override virtual
Implements Evaluateur_Source_VEF_Face.
Definition at line 129 of file Eval_Darcy_VEF_Face.h.
{
  calculer_terme_source(num_face, source, volumes_entrelaces);
}
References calculer_terme_source(), and Evaluateur_Source_VEF_Face::volumes_entrelaces.
getPorosite()
double & Eval_Darcy_VEF_Face::getPorosite () inline
Definition at line 46 of file Eval_Darcy_VEF_Face.h.
  {
    return porosite;
  }
References porosite.
Referenced by Source_Darcy_VEF_Face::readOn().
mettre_a_jour()
void Eval_Darcy_VEF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source_VEF.
Definition at line 86 of file Eval_Darcy_VEF_Face.h.
{
  int nb_faces_tot = la_zone.valeur().nb_faces_tot();
  if (sub_type(Champ_Uniforme,diffusivite_.valeur()))
    {
      db_diffusivite = diffusivite_.valeur()(0,0);
    }
  else
    {
      const DoubleTab& val_diff = diffusivite_.valeur().valeurs();
      const IntTab& face_vois = la_zone.valeur().face_voisins();
      const DoubleVect& volumes = la_zone.valeur().volumes();
      db_diffusivite = 0.;
// Compute nu(fac)=(nu(elem1).vol(elem1)+nu(elem2).vol(elem2))/(vol(elem1)+vol(elem2))
// Viscosity at face is the volume weighted average of viscosity on elements
      for (int fac=0; fac<nb_faces_tot; fac++)
        {
          int elem1 = face_vois(fac,0);
          int elem2 = face_vois(fac,1);
          double vol = 0;
          if (elem1!=-1)
            {
              db_diffusivite(fac) += val_diff(elem1)*volumes(elem1);
              vol += volumes(elem1);
            }
          if (elem2!=-1)
            {
              db_diffusivite(fac) += val_diff(elem2)*volumes(elem2);
              vol += volumes(elem2);
            }
          db_diffusivite(fac) /= vol;
        }
    }
}
References db_diffusivite, diffusivite_, face_vois(), Zone_VF::face_voisins(), Evaluateur_Source_VEF::la_zone, Zone_VF::nb_faces_tot(), sub_type, Ref_Champ_Don_base::valeur(), Ref_Zone_VEF::valeur(), Champ_Don_base::valeurs(), and Zone_VF::volumes().
Referenced by associer().
Member Data Documentation
db_diffusivite
DoubleTab Eval_Darcy_VEF_Face::db_diffusivite protected
Definition at line 55 of file Eval_Darcy_VEF_Face.h.
Referenced by associer(), calculer_terme_source(), and mettre_a_jour().
diffusivite_
Ref_Champ_Don_base Eval_Darcy_VEF_Face::diffusivite_ protected
Definition at line 54 of file Eval_Darcy_VEF_Face.h.
Referenced by associer(), and mettre_a_jour().
modK
Modele_Permeabilite Eval_Darcy_VEF_Face::modK
Definition at line 45 of file Eval_Darcy_VEF_Face.h.
Referenced by calculer_terme_source(), and Source_Darcy_VEF_Face::readOn().
porosite
double Eval_Darcy_VEF_Face::porosite protected
Definition at line 56 of file Eval_Darcy_VEF_Face.h.
Referenced by calculer_terme_source(), and getPorosite().
vitesse
Ref_Champ_Inc Eval_Darcy_VEF_Face::vitesse protected
Definition at line 53 of file Eval_Darcy_VEF_Face.h.
Referenced by associer(), and calculer_terme_source().
The documentation for this class was generated from the following file:
src/VEF/Sources/Evaluateurs/Eval_Darcy_VEF_Face.h