TRUST: Champ_Post_Operateur_Eqn Class Reference
Champ_Post_Operateur_Eqn Class Reference
class Champ_Post_Operateur_Eqn
Champ destine a post-traiter le gradient d un champ generique
La classe porte un operateur statistique "gradient"
#include <Champ_Post_Operateur_Eqn.h>
Public Member Functions
Champ_Post_Operateur_Eqn ()
~Champ_Post_Operateur_Eqn ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const Champ_base & get_champ (Champ &espace_stockage) const override
const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const override
const Operateur_base & Operateur () const override
Operateur_base & Operateur () override
void completer (const Postraitement_base &post) override
void nommer_source () override
void set_param (Param &param) override
void verification_cas_compo () const
const Champ_base & get_champ_compo_without_evaluation (Champ &espace_stockage) const
Public Member Functions inherited from Champ_Generique_Operateur_base
~Champ_Generique_Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_Generique_Operateur_base ()
virtual const Operateur_base & Operateur () const =0
virtual Operateur_base & Operateur ()=0
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
Champ_Gen_de_Champs_Gen ()
~Champ_Gen_de_Champs_Gen () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void set_param (Param &param) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual List_Champ_Generique & get_set_sources ()
virtual Champ_Generique & get_set_source ()
void reset () override
int sauvegarder (Sortie &os) const override
sauvegarde des differentes sources
int reprendre (Entree &is) override
reprise des differentes sources
void completer (const Postraitement_base &post) override
void mettre_a_jour (double temps) override
virtual Champ_Fonc & creer_espace_stockage (const Nature_du_champ &nature, const int nb_comp, Champ_Fonc &es_tmp) const
virtual const Champ_Generique_base & get_source (int i) const
virtual Champ_Generique_base & set_source (int i)
virtual int get_nb_sources () const
int get_dimension () const override
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
void get_property_names (Motcles &list) const override
Renvoie la liste des "query" possibles pour le champ.
double get_time () const override
Renvoie le temps du Champ_Generique.
const Probleme_base & get_ref_pb_base () const override
const Discretisation_base & get_discretisation () const override
const Motcle get_directive_pour_discr () const override
const Noms get_property (const Motcle &query) const override
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Entity get_localisation (const int index=-1) const override
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
const DoubleTab & get_ref_values () const override
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_copy_values (DoubleTab &) const override
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
const Domaine & get_ref_domain () const override
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
void get_copy_domain (Domaine &) const override
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_dis_base & get_ref_zone_dis_base () const override
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
const Zone_Cl_dis_base & get_ref_zcl_dis_base () const override
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
const DoubleTab & get_ref_coordinates () const override
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
void get_copy_coordinates (DoubleTab &) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const override
void nommer_sources ()
virtual void nommer_source ()
int get_info_type_post () const override
const Champ_Generique_base & get_champ_post (const Motcle &nom) const override
int comprend_champ_post (const Motcle &identifiant) const override
virtual void fixer_serie (const double t1, const double t2)
virtual void fixer_tstat_deb (const double t1, const double t2)
virtual void lire_bidon (Entree &is) const
Public Member Functions inherited from Champ_Generique_base
Champ_Generique_base ()
~Champ_Generique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void set_param (Param &param)=0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int get_dimension () const
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values.
(par exemple, un champ defini sur une surface peut etre de dimension 3 si les
coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes
le long de la surface)
virtual double get_time () const
Renvoie le temps du Champ_Generique.
virtual const Probleme_base & get_ref_pb_base () const
virtual const Discretisation_base & get_discretisation () const
virtual const Motcle get_directive_pour_discr () const
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
virtual const Nom & get_nom_post () const
virtual void get_property_names (Motcles &list) const
Renvoie la liste des "query" possibles pour le champ.
virtual const Noms get_property (const Motcle &query) const
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
virtual Entity get_localisation (const int index=-1) const
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
virtual int get_nb_localisations () const
virtual const DoubleTab & get_ref_values () const
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const.
Le maillage sur lequel ces valeurs sont definies est accessible par les methodes
get_node_coordinates(), get_connectivity(), get_field_type().
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_values();
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_copy_values (DoubleTab &) const
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
- GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
- GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie.
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
virtual const Domaine & get_ref_domain () const
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual void get_copy_domain (Domaine &) const
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_dis_base & get_ref_zone_dis_base () const
Renvoie une ref a la zone_discretisee du domaine
sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
virtual const Zone_Cl_dis_base & get_ref_zcl_dis_base () const
Renvoie une ref a la zone_cl_discretisee de l equation portant le champ cible.
virtual const DoubleTab & get_ref_coordinates () const
Renvoie une reference au tableau des coordonnees des sommets du maillage support
du champ, s'il existe. Le tableau a toujours deux dimensions :
dimension(0) = nombre de sommets reels
dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ)
En parallele, le tableau est un tableau distribue avec items communs.
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_coordinates();.
virtual void get_copy_coordinates (DoubleTab &) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple
get_ref_connectivity(ELEM, NODE) = Zone::mes_elems
get_ref_connectivity(ELEM, FACE) = ZoneVF::elem_faces_
get_ref_connectivity(FACE, ELEM) = ZoneVF::face_voisins_
Le tableau a toujours deux dimensions :
dimension(0) = nombre d'entites "index1" reelles
dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1"
En parallele, le tableau est un tableau distribue avec items communs
Exceptions:
- GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
- GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire,
il faut utiliser get_copy_connectivity();.
virtual void get_copy_connectivity (Entity index1, Entity index2, IntTab &) const
virtual void reset ()=0
virtual void completer (const Postraitement_base &post)=0
virtual void mettre_a_jour (double temps)=0
virtual const Champ_base & get_champ (Champ &espace_stockage) const =0
virtual const Champ_base & get_champ_without_evaluation (Champ &espace_stockage) const =0
virtual const Champ_Generique_base & get_champ_post (const Motcle &nom) const
virtual int comprend_champ_post (const Motcle &identifiant) const
virtual int get_info_type_post () const =0
void fixer_identifiant_appel (const Nom &identifiant)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Post_Operateur_Eqn & self_cast (Objet_U &)
static const Champ_Post_Operateur_Eqn & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_Operateur_base
static const Type_info * info ()
static Champ_Generique_Operateur_base & self_cast (Objet_U &)
static const Champ_Generique_Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Gen_de_Champs_Gen
static const Type_info * info ()
static Champ_Gen_de_Champs_Gen & self_cast (Objet_U &)
static const Champ_Gen_de_Champs_Gen & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Generique_base
static const Type_info * info ()
static Champ_Generique_base & self_cast (Objet_U &)
static const Champ_Generique_base & self_cast (const Objet_U &)
static int composante (const Nom &nom_test, const Nom &nom, const Noms &composantes, const Noms &synonyms)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Gen_de_Champs_Gen
static const Type_info info_obj
Static Public Attributes inherited from Champ_Generique_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Champ_Generique_base
Sortie & printOn (Sortie &x) const override
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int numero_source_
int numero_op_
Ref_Equation_base ref_eq_
int sans_solveur_masse_
Entity localisation_inco_
int compo_
Protected Attributes inherited from Champ_Gen_de_Champs_Gen
List_Nom noms_sources_ref_
List_Ref_Champ_Generique_base sources_reference_
Protected Attributes inherited from Champ_Generique_base
Nom nom_post_
Nom identifiant_appel_
Nom nom_pb_
Ref_Probleme_base ref_pb_
Additional Inherited Members
Static Protected Member Functions inherited from Champ_Generique_base
static void assert_parallel (int)
Detailed Description
class Champ_Post_Operateur_Eqn
Champ destine a post-traiter le gradient d un champ generique
La classe porte un operateur statistique "gradient"
Definition at line 44 of file Champ_Post_Operateur_Eqn.h.
Constructor & Destructor Documentation
Champ_Post_Operateur_Eqn()
Champ_Post_Operateur_Eqn::Champ_Post_Operateur_Eqn ()
Definition at line 34 of file Champ_Post_Operateur_Eqn.cpp.
{
  numero_op_=-1;
  numero_source_=-1;
  sans_solveur_masse_=0;
  compo_=-1;
}
References compo_, numero_op_, numero_source_, and sans_solveur_masse_.
~Champ_Post_Operateur_Eqn()
Champ_Post_Operateur_Eqn::~Champ_Post_Operateur_Eqn ()
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
Member Function Documentation
completer()
void Champ_Post_Operateur_Eqn::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 87 of file Champ_Post_Operateur_Eqn.cpp.
{
  Champ_Gen_de_Champs_Gen::completer(post);
  const Probleme_base& Pb = ref_cast(Postraitement,post).probleme();
  int numero_eq_=-1;
  if (sub_type(Champ_Generique_refChamp,get_source(0)))
    {
      Champ espace_stockage;
      const Champ_base& mon_champ = get_source(0).get_champ(espace_stockage);
      if (sub_type(Champ_Inc_base,mon_champ))
        {
          const Champ_Inc_base& mon_champ_inc = ref_cast(Champ_Inc_base,mon_champ);
          {
// On recupere l equation alors qu elle n est pas encore associee au Champ_Inc
// On parcours les equatiosn du probleme et on identifie celle qui correspond au champ inconnu
            int nb_eq = Pb.nombre_d_equations();
            int i=0;
            while (i<nb_eq)
              {
                const Equation_base& eq_test = Pb.equation(i);
                if ((eq_test.inconnue().le_nom() == mon_champ_inc.le_nom()))
                  {
                    numero_eq_=i;
                    break;
                  }
                i++;
              }
          }
        }
    }
  if (numero_eq_==-1)
    {
      Cerr<<"Champ_Post_Operateur_Eqn can be applied only to equation unknown."<<finl;
      exit();
    }
  ref_eq_=Pb.equation(numero_eq_);
  int ok=0;
  const Equation_base& eqn=ref_eq_.valeur();
  const MD_Vector& mdf = eqn.inconnue().valeurs().get_md_vector(),
                   md = sub_type(MD_Vector_composite, mdf.valeur()) ? ref_cast(MD_Vector_composite, mdf.valeur()).get_desc_part(0) : mdf;
  const Zone_VF& zvf= ref_cast( Zone_VF,ref_eq_.valeur().zone_dis().valeur());
  if (md== zvf.face_sommets().get_md_vector())
    {
      localisation_inco_=FACE;
      ok=1;
    }
  if (md== zvf.zone().les_elems().get_md_vector())
    {
      localisation_inco_=ELEMENT;
      ok=1;
    }
  if (md == zvf.zone().domaine().les_sommets().get_md_vector())
    {
      ok=1;
      localisation_inco_=NODE;
    }
  if (ok==0)
    {
      Cerr<<"Error in "<<que_suis_je()<<" unknown localisation"<<finl;
      exit();
    }
  verification_cas_compo();
}
References Cerr, Champ_Gen_de_Champs_Gen::completer(), Zone::domaine(), ELEMENT, Probleme_base::equation(), Process::exit(), FACE, Zone_VF::face_sommets(), finl, Champ_Generique_base::get_champ(), TRUSTVect< _TYPE_ >::get_md_vector(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Field_base::le_nom(), O_U_Ptr::le_nom(), Zone::les_elems(), Domaine::les_sommets(), localisation_inco_, NODE, Probleme_base::nombre_d_equations(), Objet_U::que_suis_je(), ref_cast, ref_eq_, sub_type, Ref_Equation_base::valeur(), Deriv_Zone_dis_base::valeur(), MD_Vector::valeur(), Champ_Inc::valeurs(), verification_cas_compo(), Zone_dis_base::zone(), and Equation_base::zone_dis().
cree_instance()
Objet_U * Champ_Post_Operateur_Eqn::cree_instance () static
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
duplique()
int Champ_Post_Operateur_Eqn::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
get_champ()
const Champ_base & Champ_Post_Operateur_Eqn::get_champ (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 199 of file Champ_Post_Operateur_Eqn.cpp.
{
// On commence par construire le champ vectoriel complet
  Champ espace_stockage_complet;
  espace_stockage_complet = get_champ_without_evaluation(espace_stockage_complet);
  DoubleTab& es = (espace_stockage_complet.valeurs());
// if (ref_eq_->schema_temps().temps_courant()!=0)
  {
    if (numero_op_!=-1)
      {
// certains calculer  sont faux !!!! il faudrait tous les recoder en res =0 ajouter();
        es=0;
        Operateur().ajouter(ref_eq_->operateur(numero_op_).mon_inconnue().valeurs(),es);
      }
    else
      ref_eq_->sources()(numero_source_).calculer(es);
    if (!sans_solveur_masse_)
      ref_eq_->solv_masse().valeur().appliquer_impl(es); //On divise par le volume
// Hack: car Masse_PolyMAC_Face::appliquer_impl ne divise pas par le volume (matrice de masse)....
    if (ref_eq_->solv_masse().valeur().que_suis_je()=="Masse_PolyMAC_Face")
      {
// Cerr << "Volumic source terms on faces with PolyMAC can't be post-processed yet." << finl;
        Cerr << "Warning, source terms on faces with PolyMAC are post-processed as S*dV not as volumic source terms S." << finl;
        Cerr << "Cause Masse_PolyMAC_Face::appliquer_impl do not divide per volume." << finl;
// Process::exit();
      }
  }
  es.echange_espace_virtuel();
// apres je recupere juste la composante si elle est demandee
  if (compo_>-1)
    {
// on prepare l'espace de stockage pour une composante
      Champ espace_stockage_compo;
      espace_stockage_compo = get_champ_compo_without_evaluation(espace_stockage_compo);
      DoubleTab& es_compo = (espace_stockage_compo.valeurs());
      int nb_pos = es.dimension(0);
      for (int i=0; i<nb_pos; i++)
        {
          es_compo(i) = es(i,compo_);
        }
      espace_stockage = espace_stockage_compo;
    }
  else
    espace_stockage = espace_stockage_complet;
  return espace_stockage.valeur();
}
References Operateur_base::ajouter(), Solveur_Masse_base::appliquer_impl(), Cerr, compo_, TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), finl, get_champ_compo_without_evaluation(), get_champ_without_evaluation(), Operateur::mon_inconnue(), numero_op_, numero_source_, Operateur(), Equation_base::operateur(), Objet_U::que_suis_je(), ref_eq_, sans_solveur_masse_, Equation_base::solv_masse(), Equation_base::sources(), Deriv_Champ_base::valeur(), Deriv_Solveur_Masse_base::valeur(), Champ::valeurs(), and Champ_Inc::valeurs().
get_champ_compo_without_evaluation()
const Champ_base & Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation (Champ & espace_stockage) const
Definition at line 166 of file Champ_Post_Operateur_Eqn.cpp.
{
  Champ_Fonc espace_stockage_fonc;
  Champ source_espace_stockage;
  double temps=0.;
  Nom directive;
  switch (localisation_inco_)
    {
    case ELEMENT:
      directive="CHAMP_ELEM";
      break;
    case NODE:
      directive="CHAMP_SOMMETS";
      break;
    case FACE:
      directive="CHAMP_FACE";
      break;
    default:
      Cerr<<"error in Champ_Post_Operateur_Eqn::get_champ"<<finl;
      exit();
    }
  int nb_comp = 1;
  ref_eq_.valeur().discretisation().discretiser_champ(directive,ref_eq_->zone_dis().valeur(),"oooo","unit", nb_comp,temps,espace_stockage_fonc);
  espace_stockage = espace_stockage_fonc;
  espace_stockage.valeur().fixer_nature_du_champ(scalaire);
  return espace_stockage;
}
References Cerr, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), ELEMENT, Process::exit(), FACE, finl, Field_base::fixer_nature_du_champ(), localisation_inco_, NODE, ref_eq_, scalaire, Deriv_Champ_base::valeur(), Ref_Equation_base::valeur(), Deriv_Zone_dis_base::valeur(), and Equation_base::zone_dis().
Referenced by get_champ().
get_champ_without_evaluation()
const Champ_base & Champ_Post_Operateur_Eqn::get_champ_without_evaluation (Champ & espace_stockage) const override virtual
Implements Champ_Generique_base.
Definition at line 160 of file Champ_Post_Operateur_Eqn.cpp.
{
  espace_stockage = ref_eq_.valeur().inconnue();
  return espace_stockage;
}
References Equation_base::inconnue(), ref_eq_, and Ref_Equation_base::valeur().
Referenced by get_champ().
get_info()
const Type_info * Champ_Post_Operateur_Eqn::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
get_localisation()
Entity Champ_Post_Operateur_Eqn::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes
sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans
parametre, sauf si on sait quoi faire pour les champs multi-supports.
Voir aussi get_nb_localisations()
Parametre : index
Signification : index de la localisation demandee (pour les champs multi-support).
Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support.
Si index >= 0 : on renvoie le i-ieme support.
Valeur par defaut : -1
Exceptions:
- GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques
(il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ
est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 309 of file Champ_Post_Operateur_Eqn.cpp.
{
  return localisation_inco_;
}
References localisation_inco_.
get_property()
const Noms Champ_Post_Operateur_Eqn::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee. Exemples:
"DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...)
"ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc)
"DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC})
"NAME" : nom du champ
"COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z})
"BOUNDARY_NAMES" : nom des bords
"COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...)
Exceptions:
- GenericFieldError::INVALID : query non comprise.
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 248 of file Champ_Post_Operateur_Eqn.cpp.
{
// Creation des composantes serait a faire de maniere dynamique (Eqn_...)
  Motcles motcles(2);
  motcles[0] = "composantes";
  motcles[1] = "unites";
  int rang = motcles.search(query);
  switch(rang)
    {
    case 0:
      {
        if (compo_==-1)
          {
            int nb_comp= ref_eq_.valeur().inconnue().valeur().nb_comp();
            Noms compo(nb_comp);
            for (int i=0; i<nb_comp; i++)
              {
                Nom nume(i);
                compo[i] = nom_post_+nume;
              }
            return compo;
          }
        else
          {
            Noms compo(1);
            compo[0] = nom_post_;
            return compo;
          }
        break;
      }
    case 1:
      {
        if (compo_==-1)
          {
            int nb_comp= ref_eq_.valeur().inconnue().valeur().nb_comp();
            Noms unites(nb_comp);
// Noms source_unites = get_source(0).get_property("unites");
            for (int i=0; i<nb_comp; i++)
              {
                unites[i] = "unit";
              }
            return unites;
          }
        else
          {
// J'utilise un vecteur car la methode renvoie Noms
            Noms unites(1);
            unites[0] = "unit";
            return unites;
          }
        break;
      }
    }
  return Champ_Gen_de_Champs_Gen::get_property(query);
}
References compo_, Champ_Gen_de_Champs_Gen::get_property(), Equation_base::inconnue(), Field_base::nb_comp(), Champ_Generique_base::nom_post_, ref_eq_, Motcles::search(), Deriv_Champ_Inc_base::valeur(), and Ref_Equation_base::valeur().
info()
const Type_info * Champ_Post_Operateur_Eqn::info () static
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
nommer_source()
void Champ_Post_Operateur_Eqn::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 317 of file Champ_Post_Operateur_Eqn.cpp.
{
  if (nom_post_=="??")
    {
      Nom nom_post_source, nom_champ_source;
// const Noms nom = get_source(0).get_property("nom");
      nom_post_source = "Eqn_s";
      nom_post_source +=  numero_source_ ;
      nom_post_source += "_o" ;
      nom_post_source += numero_op_ ;
      if (compo_!=-1)
        {
          Nom nume(compo_);
          nom_post_source += nume;
        }
      nommer(nom_post_source);
    }
}
References compo_, Champ_Generique_base::nom_post_, Champ_Generique_base::nommer(), numero_op_, and numero_source_.
Operateur() [1/2]
const Operateur_base & Champ_Post_Operateur_Eqn::Operateur () const override virtual
Implements Champ_Generique_Operateur_base.
Definition at line 336 of file Champ_Post_Operateur_Eqn.cpp.
{
  return ref_eq_->operateur(numero_op_).l_op_base();
}
References Operateur::l_op_base(), numero_op_, Equation_base::operateur(), and ref_eq_.
Referenced by get_champ().
Operateur() [2/2]
Operateur_base & Champ_Post_Operateur_Eqn::Operateur () override virtual
Implements Champ_Generique_Operateur_base.
Definition at line 341 of file Champ_Post_Operateur_Eqn.cpp.
{
  return ref_eq_->operateur(numero_op_).l_op_base();
}
References Operateur::l_op_base(), numero_op_, Equation_base::operateur(), and ref_eq_.
printOn()
Sortie & Champ_Post_Operateur_Eqn::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 30 of file Champ_Post_Operateur_Eqn.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Objet_U::le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Champ_Post_Operateur_Eqn::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Generique_Operateur_base.
Definition at line 51 of file Champ_Post_Operateur_Eqn.cpp.
{
  Champ_Generique_Operateur_base::readOn(s);
  return s ;
}
References Champ_Generique_Operateur_base::readOn().
self_cast() [1/2]
const Champ_Post_Operateur_Eqn & Champ_Post_Operateur_Eqn::self_cast (const Objet_U & r) static
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
self_cast() [2/2]
Champ_Post_Operateur_Eqn & Champ_Post_Operateur_Eqn::self_cast (Objet_U & r) static
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
set_param()
void Champ_Post_Operateur_Eqn::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
Definition at line 42 of file Champ_Post_Operateur_Eqn.cpp.
{
  Champ_Generique_Operateur_base::set_param(param);
  param.ajouter("numero_source",&numero_source_);
  param.ajouter("numero_op",&numero_op_);
  param.ajouter_flag("sans_solveur_masse",&sans_solveur_masse_);
  param.ajouter("compo",&compo_);
}
References Param::ajouter(), Param::ajouter_flag(), compo_, numero_op_, numero_source_, sans_solveur_masse_, and Champ_Gen_de_Champs_Gen::set_param().
taille_memoire()
unsigned Champ_Post_Operateur_Eqn::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file Champ_Post_Operateur_Eqn.cpp.
verification_cas_compo()
void Champ_Post_Operateur_Eqn::verification_cas_compo () const
Definition at line 58 of file Champ_Post_Operateur_Eqn.cpp.
{
// On applique compo a un vecteur
  const Nature_du_champ& nature_ch=ref_eq_.valeur().inconnue().valeur().nature_du_champ();
  if ((nature_ch != vectoriel) && (compo_ != -1 ))
    {
      Cerr<<"Error in Champ_Post_Operateur_Eqn::verification_cas_compo()"<<finl;
      Cerr<<"It isn't possible to get a component from a non vectoriel field " <<finl;
      exit();
    }
// Verification de compo
  const int nb_compo= ref_eq_.valeur().inconnue().valeur().nb_comp();
  if ((compo_<-1)||(compo_>nb_compo-1))
    {
      Cerr<<"Error in Champ_Post_Operateur_Eqn::verification_cas_compo()"<<finl;
      Cerr<<"compo="<<compo_<<" is not allowed."<<" You must give a value between 0 and "<< nb_compo-1<<finl;
      exit();
    }
// Verifier qu'on n'est pas en VDF
  const Zone_dis_base& zone_dis = ref_eq_.valeur().zone_dis().valeur();
  if ((zone_dis.que_suis_je().debute_par("Zone_VDF")) && (compo_ != -1 ))
    {
      Cerr<<"Error in Champ_Post_Operateur_Eqn::verification_cas_compo()"<<finl;
      Cerr<<"The option compo is not available in case of VDF discretization"<<finl;
      exit();
    }
}
References Cerr, compo_, Nom::debute_par(), Process::exit(), finl, Equation_base::inconnue(), Field_base::nature_du_champ(), Field_base::nb_comp(), Objet_U::que_suis_je(), ref_eq_, Deriv_Champ_Inc_base::valeur(), Ref_Equation_base::valeur(), Deriv_Zone_dis_base::valeur(), vectoriel, and Equation_base::zone_dis().
Referenced by completer().
Member Data Documentation
compo_
int Champ_Post_Operateur_Eqn::compo_ protected
Definition at line 71 of file Champ_Post_Operateur_Eqn.h.
Referenced by Champ_Post_Operateur_Eqn(), get_champ(), get_property(), nommer_source(), set_param(), and verification_cas_compo().
info_obj
const Type_info Champ_Post_Operateur_Eqn::info_obj static
Definition at line 47 of file Champ_Post_Operateur_Eqn.h.
localisation_inco_
Entity Champ_Post_Operateur_Eqn::localisation_inco_ protected
Definition at line 70 of file Champ_Post_Operateur_Eqn.h.
Referenced by completer(), get_champ_compo_without_evaluation(), and get_localisation().
numero_op_
int Champ_Post_Operateur_Eqn::numero_op_ protected
Definition at line 67 of file Champ_Post_Operateur_Eqn.h.
Referenced by Champ_Post_Operateur_Eqn(), get_champ(), nommer_source(), Operateur(), and set_param().
numero_source_
int Champ_Post_Operateur_Eqn::numero_source_ protected
Definition at line 67 of file Champ_Post_Operateur_Eqn.h.
Referenced by Champ_Post_Operateur_Eqn(), get_champ(), nommer_source(), and set_param().
ref_eq_
Ref_Equation_base Champ_Post_Operateur_Eqn::ref_eq_ protected
Definition at line 68 of file Champ_Post_Operateur_Eqn.h.
Referenced by completer(), get_champ(), get_champ_compo_without_evaluation(), get_champ_without_evaluation(), get_property(), Operateur(), and verification_cas_compo().
sans_solveur_masse_
int Champ_Post_Operateur_Eqn::sans_solveur_masse_ protected
Definition at line 69 of file Champ_Post_Operateur_Eqn.h.
Referenced by Champ_Post_Operateur_Eqn(), get_champ(), and set_param().
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_Post_Operateur_Eqn.h
src/Kernel/Champs_dis/Champ_Post_Operateur_Eqn.cpp