TRUST: Terme_Source_Canal_perio_VEF_P1NC Class Reference
Terme_Source_Canal_perio_VEF_P1NC Class Reference
#include <Terme_Source_Canal_perio_VEF_P1NC.h>
Public Member Functions
Terme_Source_Canal_perio_VEF_P1NC ()
~Terme_Source_Canal_perio_VEF_P1NC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Terme_Source_Canal_perio_VEF_P1NC & self_cast (Objet_U &)
static const
Terme_Source_Canal_perio_VEF_P1NC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
virtual void calculer_debit (double &) const
Protected Attributes
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Detailed Description
Definition at line 46 of file Terme_Source_Canal_perio_VEF_P1NC.h.
Constructor & Destructor Documentation
Terme_Source_Canal_perio_VEF_P1NC::Terme_Source_Canal_perio_VEF_P1NC ()
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
Terme_Source_Canal_perio_VEF_P1NC::~Terme_Source_Canal_perio_VEF_P1NC ()
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
Member Function Documentation
DoubleTab & Terme_Source_Canal_perio_VEF_P1NC::ajouter (DoubleTab & resu) const [virtual]
Reimplemented from Source_base.
Definition at line 83 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
References Source_base::bilan_, Objet_U::dimension, Zone_VF::faces_doubles(), la_zone_Cl_VEF, la_zone_VEF, Zone_VF::nb_faces(), Zone_VF::porosite_face(), Zone_VEF::premiere_face_std(), ArrOfDouble::size_array(), Terme_Source_Canal_perio::source(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), Zone_VF::volumes_entrelaces(), and Zone_Cl_VEF::volumes_entrelaces_Cl().
{
  const Zone_VF& zone_VF = la_zone_VEF.valeur();
  const DoubleVect& volumes_entrelaces = zone_VF.volumes_entrelaces();
  const DoubleVect& volumes_entrelaces_Cl = la_zone_Cl_VEF.valeur().volumes_entrelaces_Cl();
  int premiere_face_std=la_zone_VEF.valeur().premiere_face_std() ;
  const DoubleVect& porosite_face=zone_VF.porosite_face();
  ArrOfDouble s;
  s = source();
  if (s.size_array()==dimension)
    {
// Case Navier Stokes, s is uniform
      for (int num_face = 0 ; num_face<premiere_face_std; num_face++)
        {
          double vol = volumes_entrelaces_Cl(num_face)*porosite_face(num_face);
          for (int i=0; i<dimension; i++)
            resu(num_face,i)+= s(i)*vol;
        }
      int nb_faces = zone_VF.nb_faces();
      for (int num_face = premiere_face_std; num_face<nb_faces; num_face++)
        {
          double vol = volumes_entrelaces(num_face)*porosite_face(num_face);
          for (int i=0; i<dimension; i++)
            resu(num_face,i)+= s(i)*vol;
        }
    }
  else
    {
// Case Energy, s is non uniform
      bilan_=0;
      const ArrOfInt& fd=zone_VF.faces_doubles();
      for (int num_face = 0 ; num_face<premiere_face_std; num_face++)
        {
          double vol = volumes_entrelaces_Cl(num_face)*porosite_face(num_face);
          double contrib = s(num_face)*vol;
          resu(num_face)+= contrib;
          bilan_(0)+= contrib*(1-0.5*fd(num_face));
        }
      int nb_faces = zone_VF.nb_faces();
      for (int num_face = premiere_face_std; num_face<nb_faces; num_face++)
        {
          double vol = volumes_entrelaces(num_face)*porosite_face(num_face);
          double contrib = s(num_face)*vol;
          resu(num_face)+= contrib;
          bilan_(0)+= contrib*(1-0.5*fd(num_face));
        }
    }
  return resu;
}
void Terme_Source_Canal_perio_VEF_P1NC::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 76 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
References la_zone_Cl_VEF, la_zone_VEF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
{
  la_zone_VEF = ref_cast(Zone_VEF, zone_dis.valeur());
  la_zone_Cl_VEF = ref_cast(Zone_Cl_VEF, zone_Cl_dis.valeur());
}
void Terme_Source_Canal_perio_VEF_P1NC::calculer_debit (double & debit_e) const [protected, virtual]
Implements Terme_Source_Canal_perio.
Definition at line 133 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
References Terme_Source_Canal_perio::bord_periodique_, dabs(), Objet_U::dimension, Terme_Source_Canal_perio::direction_ecoulement_, MorEqn::equation(), Zone_VF::face_normales(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), la_zone_Cl_VEF, la_zone_VEF, Frontiere_dis_base::le_nom(), Field_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Ref_Zone_VEF::valeur(), and Champ_Inc_base::valeurs().
{
  const Zone_VF& zone_VF = la_zone_VEF.valeur();
  const Zone_Cl_dis_base& zone_Cl_dis = la_zone_Cl_VEF.valeur();
  const Champ_Inc_base& velocity = (sub_type(Convection_Diffusion_std,equation()) ? ref_cast(Convection_Diffusion_std,equation()).vitesse_transportante() : equation().inconnue());
  const DoubleVect& porosite_face=zone_VF.porosite_face();
// Check we have really velocity:
  assert(velocity.le_nom()=="vitesse");
  const DoubleTab& vitesse = velocity.valeurs();
  int nb_bords = zone_VF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_dis.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          if (bord_periodique_ == le_bord.le_nom())
            {
              debit_e=0.;
// const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = le_bord.num_premiere_face();
              int nfin = ndeb + le_bord.nb_faces()/2;
              int axe = direction_ecoulement_;
              if (equation().probleme().is_dilatable()==1)
                {
// Si l'on est en Quasi Compressible, il faut conserver
// le debit massique et non pas le debit volumique.
// C'est pour cela que dans le cas QC, on multiplie les vecteurs vitesse
// par la masse volumique discretisee aux faces pour que lorsqu'on integre sur la surface,
// on obtienne bien un debit massique et non pas un debit volumique.
                  const DoubleTab& tab_rho_face = ref_cast(Fluide_Dilatable_base,equation().milieu()).rho_discvit();
                  if (axe>=0)
                    for (int num_face=ndeb; num_face<nfin; num_face++)
                      {
                        double debit_face = porosite_face(num_face)*vitesse(num_face,axe) * dabs(zone_VF.face_normales(num_face,axe));
                        debit_e += tab_rho_face[num_face] * debit_face;
                      }
                  else
                    for (int num_face=ndeb; num_face<nfin; num_face++)
                      {
                        double debit_face=0;
                        for (int i=0; i<dimension; i++)
                          debit_face += porosite_face(num_face)*vitesse(num_face,i) * zone_VF.face_normales(num_face,i);
                        debit_e += tab_rho_face[num_face] * debit_face;
                      }
                }
              else
                {
                  if (axe>=0)
                    for (int num_face=ndeb; num_face<nfin; num_face++)
                      {
                        double debit_face = porosite_face(num_face)*vitesse(num_face,axe) * dabs(zone_VF.face_normales(num_face,axe));
                        debit_e += debit_face;
                      }
                  else
                    for (int num_face=ndeb; num_face<nfin; num_face++)
                      {
                        double debit_face=0;
                        for (int i=0; i<dimension; i++)
                          debit_face += porosite_face(num_face)*vitesse(num_face,i) * zone_VF.face_normales(num_face,i);
                        debit_e += debit_face;
                      }
                }
            }
        }
    }
  debit_e = mp_sum(debit_e);
}
Objet_U * Terme_Source_Canal_perio_VEF_P1NC::cree_instance () [static]
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
int Terme_Source_Canal_perio_VEF_P1NC::duplique () const [virtual]
Implements Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
const Type_info * Terme_Source_Canal_perio_VEF_P1NC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
const Type_info * Terme_Source_Canal_perio_VEF_P1NC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
Sortie & Terme_Source_Canal_perio_VEF_P1NC::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 62 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Terme_Source_Canal_perio_VEF_P1NC::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 71 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
References Terme_Source_Canal_perio::lire_donnees().
{
  return Terme_Source_Canal_perio::lire_donnees(s);
}
const Terme_Source_Canal_perio_VEF_P1NC & Terme_Source_Canal_perio_VEF_P1NC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
Terme_Source_Canal_perio_VEF_P1NC & Terme_Source_Canal_perio_VEF_P1NC::self_cast (Objet_U & r) [static]
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
unsigned Terme_Source_Canal_perio_VEF_P1NC::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 39 of file Terme_Source_Canal_perio_VEF_P1NC.cpp.
Member Data Documentation
const Type_info Terme_Source_Canal_perio_VEF_P1NC::info_obj [static]
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VEF_P1NC.
Definition at line 48 of file Terme_Source_Canal_perio_VEF_P1NC.h.
Ref_Zone_Cl_VEF Terme_Source_Canal_perio_VEF_P1NC::la_zone_Cl_VEF [protected]
Definition at line 56 of file Terme_Source_Canal_perio_VEF_P1NC.h.
Referenced by ajouter(), associer_zones(), and calculer_debit().
Ref_Zone_VEF Terme_Source_Canal_perio_VEF_P1NC::la_zone_VEF [protected]
Definition at line 55 of file Terme_Source_Canal_perio_VEF_P1NC.h.
Referenced by ajouter(), associer_zones(), and calculer_debit().
The documentation for this class was generated from the following files:
src/VEF/Sources/Terme_Source_Canal_perio_VEF_P1NC.h
src/VEF/Sources/Terme_Source_Canal_perio_VEF_P1NC.cpp