TRUST: Deriv_Champ_Don_base Class Reference
Deriv_Champ_Don_base Class Reference
#include <Champ_Don.h>
Public Member Functions
~Deriv_Champ_Don_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Champ_Don_base ()
Deriv_Champ_Don_base (const Deriv_Champ_Don_base &)
const Champ_Don_base & valeur () const
Champ_Don_base & valeur ()
const Champ_Don_base * operator-> () const
Champ_Don_base * operator-> ()
const Deriv_Champ_Don_base & operator= (const Champ_Don_base &)
const Deriv_Champ_Don_base & operator= (const Deriv_Champ_Don_base &)
operator const Champ_Don_base & () const
operator Champ_Don_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Champ_Don_base & self_cast (Objet_U &)
static const Deriv_Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Champ_Don_base * pointeur_
Detailed Description
Definition at line 23 of file Champ_Don.h.
Constructor & Destructor Documentation
~Deriv_Champ_Don_base()
Deriv_Champ_Don_base::~Deriv_Champ_Don_base ()
Definition at line 18 of file Champ_Don.cpp.
Deriv_Champ_Don_base() [1/2]
Deriv_Champ_Don_base::Deriv_Champ_Don_base ()
Definition at line 18 of file Champ_Don.cpp.
Deriv_Champ_Don_base() [2/2]
Deriv_Champ_Don_base::Deriv_Champ_Don_base (const Deriv_Champ_Don_base & t)
Definition at line 18 of file Champ_Don.cpp.
Member Function Documentation
cree_instance()
Objet_U * Deriv_Champ_Don_base::cree_instance () static
Definition at line 18 of file Champ_Don.cpp.
duplique()
int Deriv_Champ_Don_base::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_Don.
Definition at line 18 of file Champ_Don.cpp.
get_info()
const Type_info * Deriv_Champ_Don_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Don.
Definition at line 18 of file Champ_Don.cpp.
get_info_ptr()
const Type_info & Deriv_Champ_Don_base::get_info_ptr () const override virtual
Implements O_U_Ptr.
Definition at line 18 of file Champ_Don.cpp.
info()
const Type_info * Deriv_Champ_Don_base::info () static
Definition at line 18 of file Champ_Don.cpp.
operator Champ_Don_base &()
Deriv_Champ_Don_base::operator Champ_Don_base & ()
Definition at line 18 of file Champ_Don.cpp.
operator const Champ_Don_base &()
Deriv_Champ_Don_base::operator const Champ_Don_base & () const
Definition at line 18 of file Champ_Don.cpp.
operator->() [1/2]
Champ_Don_base * Deriv_Champ_Don_base::operator-> () inline
Definition at line 23 of file Champ_Don.h.
: public DERIV(Champ_Don_base), public Champ_Proto
operator->() [2/2]
const Champ_Don_base * Deriv_Champ_Don_base::operator-> () const inline
Definition at line 23 of file Champ_Don.h.
: public DERIV(Champ_Don_base), public Champ_Proto
operator=() [1/2]
const Deriv_Champ_Don_base & Deriv_Champ_Don_base::operator= (const Champ_Don_base & t)
Definition at line 18 of file Champ_Don.cpp.
operator=() [2/2]
const Deriv_Champ_Don_base & Deriv_Champ_Don_base::operator= (const Deriv_Champ_Don_base & t)
Definition at line 18 of file Champ_Don.cpp.
printOn()
Sortie & Deriv_Champ_Don_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Don.
Definition at line 18 of file Champ_Don.cpp.
readOn()
Entree & Deriv_Champ_Don_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Champ_Don.
Definition at line 18 of file Champ_Don.cpp.
self_cast() [1/2]
const Deriv_Champ_Don_base & Deriv_Champ_Don_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Champ_Don.cpp.
self_cast() [2/2]
Deriv_Champ_Don_base & Deriv_Champ_Don_base::self_cast (Objet_U & r) static
Definition at line 18 of file Champ_Don.cpp.
set_O_U_Ptr()
void Deriv_Champ_Don_base::set_O_U_Ptr (Objet_U * ptr) override protected virtual
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 18 of file Champ_Don.cpp.
taille_memoire()
unsigned Deriv_Champ_Don_base::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_Don.
Definition at line 18 of file Champ_Don.cpp.
valeur() [1/2]
Champ_Don_base & Deriv_Champ_Don_base::valeur () inline
Definition at line 23 of file Champ_Don.h.
: public DERIV(Champ_Don_base), public Champ_Proto
valeur() [2/2]
const Champ_Don_base & Deriv_Champ_Don_base::valeur () const inline
Definition at line 23 of file Champ_Don.h.
: public DERIV(Champ_Don_base), public Champ_Proto
Referenced by Champ_Don::affecter_(), Champ_Don::affecter_compo(), PDF_model::affecter_vitesse_imposee(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::ajouter_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Eval_Darcy_VDF_Face::associer(), Eval_Darcy_VEF_Face::associer(), Op_Grad_EF::associer(), Eval_Puiss_Neutr_VDF_Elem::associer_champs(), Source_PDF_EF::associer_pb(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_P1NC::calcul_y_plus(), Champ_Face::calcul_y_plus(), Milieu_base::calculer_alpha(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), calculer_h_distant(), calculer_h_local(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Terme_Source_Acceleration::calculer_la_source(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_base::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), Champ_Ostwald_VDF::calculer_mu(), Champ_Ostwald_VEF::calculer_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_base::calculer_nu(), Fluide_base::calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Eval_Puiss_Th_VDF_Elem::calculer_terme_source(), Eval_Source_C_VDF_Elem::calculer_terme_source(), Eval_Puiss_Th_PolyMAC_Elem::calculer_terme_source(), Eval_Source_C_PolyMAC_Elem::calculer_terme_source(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_VEF_Face::calculer_terme_source_non_standard(), Eval_Source_C_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_EF::calculer_terme_source_standard(), Eval_Puiss_Th_QC_EF::calculer_terme_source_standard(), Eval_Puiss_Th_QC_VEF_Face::calculer_terme_source_standard(), Eval_Puiss_Th_VEF_Face::calculer_terme_source_standard(), Eval_Source_C_VEF_Face::calculer_terme_source_standard(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Echange_global_impose::champ_exterieur(), Perte_Charge_Anisotrope_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Directionnelle_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Anisotrope_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Directionnelle_VEF_P1NC::coeffs_perte_charge(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::contribuer_a_avec(), Discretisation_base::creer_champ(), Fluide_Dilatable_base::creer_champs_non_lus(), Fluide_base::creer_nu(), Interpolation_IBM_hybrid::discretise(), Interpolation_IBM_elem_fluid::discretise(), Interpolation_IBM_mean_gradient::discretise(), Milieu_base::discretiser(), Fluide_Dilatable_base::discretiser(), Constituant::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Milieu_composite::discretiser(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Champ_Don::fixer_nb_valeurs_nodales(), Echange_couplage_thermique::get_dRho_dCp(), Zone_Cl_EF::imposer_symetrie(), Zone_Cl_EF::imposer_symetrie_matrice_secmem(), Zone_Cl_EF::imposer_symetrie_partiellement(), Champ_Don::initialiser(), Milieu_base::initialiser(), Terme_Puissance_Thermique::initialiser_champ_puissance(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), Diametre_hyd_champ::interpreter(), Porosites_champ::interpreter(), Equation_base::lire_cond_init(), Navier_Stokes_std::lire_cond_init(), Terme_Source_Acceleration::lire_data(), Terme_Puissance_Thermique::lire_donnees(), Fluide_Dilatable_base::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Champ_Don::mettre_a_jour(), Milieu_base::mettre_a_jour(), Terme_Puissance_Thermique::mettre_a_jour(), Loi_Fermeture_Test::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_PolyMAC::mettre_a_jour(), Fluide_base::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_P0_VDF::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_VEF_Face::mettre_a_jour(), Zone_Cl_EF::modifie_gradient(), T_It_VDF_Elem< _TYPE_ >::modifier_flux(), Op_VEF_Face::modifier_flux(), Champ_Don::nb_comp(), Champ_Don::nb_valeurs_nodales(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), PolyMAC_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), Source_Scalaire_EF::readOn(), Champ_front_MED::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Diametre_bulles_champ::readOn(), Zone_Cl_EF::remplir_type_elem_Cl(), Fluide_Dilatable_base::set_Cp(), Milieu_base::update_rho_cp(), Fluide_Dilatable_base::update_rho_cp(), Source_PDF_base::updateChampRho(), Champ_front_MED::valeur_au_temps_et_au_point(), Champ_Don::valeurs(), Fluide_Dilatable_base::verifier_coherence_champs(), Fluide_base::verifier_coherence_champs(), Fluide_Incompressible::verifier_coherence_champs(), and Solide::verifier_coherence_champs().
Member Data Documentation
info_obj
const Type_info Deriv_Champ_Don_base::info_obj static
Definition at line 23 of file Champ_Don.h.
pointeur_
Champ_Don_base* Deriv_Champ_Don_base::pointeur_ private
Definition at line 23 of file Champ_Don.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Champ_Don.h
src/Kernel/Framework/Champ_Don.cpp