TRUST: Op_Dift_VDF_Face_Axi_base Class Reference
Op_Dift_VDF_Face_Axi_base Class Reference abstract
#include <Op_Dift_VDF_Face_Axi_base.h>
Public Member Functions
Op_Dift_VDF_Face_Axi_base ()
~Op_Dift_VDF_Face_Axi_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double calculer_dt_stab () const override
Calcul dt_stab.
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &) override
void associer_modele_turbulence (const Mod_turb_hyd_base &)
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
void contribue_au_second_membre (DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void contribuer_au_second_membre (DoubleTab &resu) const override
on ajoute la contribution du second membre.
void associer_loipar (const Turbulence_paroi &)
void associer_diffusivite_turbulente (const Champ_Fonc &visc_turb)
void dimensionner (Matrice_Morse &matrice) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Public Member Functions inherited from Op_Dift_VDF_Face_base
Op_Dift_VDF_Face_base ()
~Op_Dift_VDF_Face_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Dift_VDF_Face_base (const Iterateur_VDF_base &iter_base)
double calculer_dt_stab () const override
Calcul dt_stab.
double calculer_dt_stab (const Zone_VDF &) const
void calculer_borne_locale (DoubleVect &, double, double) const override
const Champ_base & diffusivite () const override=0
XXX : E Saikali : juste pour securite ...
void associer_loipar (const Turbulence_paroi &)
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
Public Member Functions inherited from Op_Dift_VDF_base
Op_Dift_VDF_base ()
~Op_Dift_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Dift_VDF_base (const Iterateur_VDF_base &iter_base)
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
void associer_diffusivite_turbulente_base (const Champ_Fonc &diff_turb)
void completer_Op_Dift_VDF_base ()
Public Member Functions inherited from Op_Diff_VDF_base
Op_Diff_VDF_base ()
~Op_Diff_VDF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Op_Diff_VDF_base (const Iterateur_VDF_base &iter_base)
void completer () override
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void contribuer_au_second_membre (DoubleTab &) const override
on ajoute la contribution du second membre.
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
calcule la contribution de la diffusion, la range dans resu
int impr (Sortie &os) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
virtual void calculer_flux_bord (const DoubleTab &inco) const
const Iterateur_VDF & get_iter () const
Iterateur_VDF & get_iter ()
int has_interface_blocs () const override
void init_op_ext () const
Public Member Functions inherited from Operateur_Diff_base
Operateur_Diff_base ()
~Operateur_Diff_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void associer_diffusivite (const Champ_base &)=0
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Associe la vraie diffusivite en m^2/s (en QC par exemple, l'operateur
est applique a rho*u, et on associe alors la viscosite dynamique a
l'operateur au lieu de la viscosite dynamique. Dans ce cas, il
faut associer la vraie diffusivite ici pour le calcul du pas de
temps de stabilite.
virtual const Champ_base & diffusivite () const =0
virtual void calculer_borne_locale (DoubleVect &, double, double) const
Public Member Functions inherited from Operateur_base
Operateur_base ()
~Operateur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
virtual DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
virtual void associer_champ (const Champ_Inc &)
virtual void associer (const Zone_dis &, const Zone_Cl_dis &, const Champ_Inc &inco)=0
virtual void associer_zone_cl_dis (const Zone_Cl_dis_base &)
virtual void dimensionner (Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &matrice) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void contribuer_bloc_vitesse (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
void tester_contribuer_a_avec (const DoubleTab &, const Matrice_Morse &)
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
virtual void dimensionner_termes_croises (Matrice_Morse &, const Probleme_base &autre_pb, int nl, int nc) const
virtual void ajouter_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, DoubleTab &resu) const
virtual void contribuer_termes_croises (const DoubleTab &inco, const Probleme_base &autre_pb, const DoubleTab &autre_inco, Matrice_Morse &matrice) const
virtual double calculer_dt_stab () const
Calcul dt_stab.
virtual void calculer_dt_local (DoubleTab &) const
virtual void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
virtual void abortTimeStep ()
virtual int impr (Sortie &os) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
void associer_eqn (const Equation_base &)
Associe une equation a l'operateur.
Simple Appel a MorEqn::associer_eqn(const Equation_base&)
int get_decal_temps () const
int set_decal_temps (int)
int get_nb_ss_pas_de_temps () const
int set_nb_ss_pas_de_temps (int)
const Matrice & get_matrice () const
Matrice & set_matrice ()
const SolveurSys & get_solveur () const
SolveurSys & set_solveur ()
Entree & lire_solveur (Entree &)
virtual int systeme_invariant () const
virtual void ajouter_contribution_explicite_au_second_membre (const Champ_Inc_base &inconnue, DoubleTab &derivee) const
const Champ_Inc & mon_inconnue () const
bool has_champ_inco () const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un operateur
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
const Nom fichier () const
void set_description (const Nom &nom)
const Nom description () const
DoubleTab & flux_bords ()
DoubleTab & flux_bords () const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const override
Motcle get_localisation_pour_post (const Nom &option) const override
virtual void ajouter_flux (const DoubleTab &inconnue, DoubleTab &contribution) const
virtual void calculer_flux (const DoubleTab &inconnue, DoubleTab &flux) const
virtual void preparer_calcul (void)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Constructeur de la classe. Par defaut, une classe derivee deja codee
appelle le constructeur sans argument. support_ok est mis a zero
et on produit une erreur si Associer_champ_masse_volumique est appele.
Pour signifier que le champ de masse volumique est supporte par
la classe derivee, il faut appeler Declare_support_masse_volumique.
virtual ~Support_Champ_Masse_Volumique ()
Destructeur virtuel (pour eviter les warnings)
virtual void associer_champ_masse_volumique (const Champ_base &)
Methode a appeler dans la preparation du probleme pour demander
a l'objet de tenir compte du champ de masse volumique en parametre.
virtual void dissocier_champ_masse_volumique ()
Annule la reference a la masse volumique.
virtual int has_champ_masse_volumique () const
Renvoie 1 si la masse volumique a ete associee, 0 sinon.
virtual const Champ_base & get_champ_masse_volumique () const
Renvoie le champ de masse volumique.
const int & support_ok () const
Public Member Functions inherited from Op_Diff_Turbulent_base
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Public Member Functions inherited from Op_VDF_Face
void dimensionner (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &) const
void modifier_pour_Cl (const Zone_VDF &, const Zone_Cl_VDF &, Matrice_Morse &, DoubleTab &) const
Static Public Member Functions
static const Type_info * info ()
static Op_Dift_VDF_Face_Axi_base & self_cast (Objet_U &)
static const Op_Dift_VDF_Face_Axi_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VDF_Face_base
static const Type_info * info ()
static Op_Dift_VDF_Face_base & self_cast (Objet_U &)
static const Op_Dift_VDF_Face_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Dift_VDF_base
static const Type_info * info ()
static Op_Dift_VDF_base & self_cast (Objet_U &)
static const Op_Dift_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Op_Diff_VDF_base
static const Type_info * info ()
static Op_Diff_VDF_base & self_cast (Objet_U &)
static const Op_Diff_VDF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_Diff_base
static const Type_info * info ()
static Operateur_Diff_base & self_cast (Objet_U &)
static const Operateur_Diff_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Operateur_base
static const Type_info * info ()
static Operateur_base & self_cast (Objet_U &)
static const Operateur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VDF_Face_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Dift_VDF_base
static const Type_info info_obj
Static Public Attributes inherited from Op_Diff_VDF_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_Diff_base
static const Type_info info_obj
Static Public Attributes inherited from Operateur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void mettre_a_jour_var (double) const =0
virtual bool is_VAR () const =0
virtual double nu_ (const int) const =0
virtual double nu_mean_2_pts_ (const int, const int) const =0
virtual double nu_mean_4_pts_ (const int, const int) const =0
virtual double nu_mean_4_pts_ (const int, const int, const int, const int) const =0
Protected Member Functions inherited from Op_Dift_VDF_Face_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Operateur_Diff_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Renvoie le champ_don correspondant a la vraie diffusivite du milieu
qui sert pour le calcul du pas de temps. Si l'operateur s'applique a rho*v
par exemple (cas du QC par exemple), la diffusivite associee est la
viscosite dynamique et non la viscosite cinematique. Il faut utiliser
la viscosite cinematique pour le calcul du pas de temps...
La vraie diffusivite (en m^2/s) est determinee comme suit:
* si diffusivite_pour_pas_de_temps_ a ete initialise => on l'utilise
(systeme mis en place pour le front-tracking, car le milieu
est invalide)
* sinon on utilise diffusivite()
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime l'operateur sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lit un operateur sur un flot d'entree.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Le constructeur d'une classe derivee qui se sert de la masse volumique
doit appeler cette fonction avec la valeur 1. Si une classe cliente
(Navier Stokes par ex.) essaie d'associer la masse volumique a une
classe qui n'a pas fait ok=1, on s'arrete : fonction non implementee.
Protected Attributes
Ref_Mod_turb_hyd_base le_modele_turbulence
Ref_Champ_Face inconnue
Ref_Zone_VDF la_zone_vdf
Ref_Zone_Cl_VDF la_zcl_vdf
IntVect orientation
IntVect type_arete_bord
IntTab Qdm
IntTab face_voisins
IntTab elem_faces
DoubleVect surface
DoubleVect volumes_entrelaces
DoubleVect porosite
DoubleTab xp
DoubleTab xv
DoubleTab tau_tan
Protected Attributes inherited from Op_Diff_VDF_base
Iterateur_VDF iter
int op_ext_init_
Protected Attributes inherited from Operateur_Diff_base
Ref_Champ_base diffusivite_pour_pas_de_temps_
Protected Attributes inherited from Operateur_base
int decal_temps
int nb_ss_pas_de_temps
SolveurSys solveur
Matrice matrice_
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description de l'operateur.
DoubleTab flux_bords_
Tableau contenant les flux sur les bords de l'operateur.
Champs_compris champs_compris_
Ref_Champ_Inc le_champ_inco
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Private Member Functions
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void ajouter_elem (const DoubleVect &, const DoubleTab &, DoubleTab &) const
void ajouter_elem_3D (const DoubleVect &, const DoubleTab &, DoubleTab &) const
void ajouter_aretes_bords (const DoubleVect &, const DoubleTab &, DoubleTab &) const
void fill_resu_aretes_mixtes (const int, const int, const int, const int, const double, const double, DoubleTab &) const
void ajouter_aretes_mixtes (const DoubleTab &, DoubleTab &) const
void fill_resu_aretes_internes (const int, const int, const int, const int, const double, const double, const double, const double, DoubleTab &) const
void ajouter_aretes_internes (const DoubleVect &, const DoubleTab &, DoubleTab &) const
void fill_coeff_matrice_morse (const int, const int, const double, Matrice_Morse &) const
void ajouter_contribution (const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_elem (const DoubleVect &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_elem_3D (const DoubleVect &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_aretes_bords (const DoubleVect &, const DoubleTab &, Matrice_Morse &) const
void ajouter_contribution_aretes_mixtes (Matrice_Morse &) const
void ajouter_contribution_aretes_internes (const DoubleVect &, Matrice_Morse &) const
void not_implemented (const char *nom_funct) const
Additional Inherited Members
Public Attributes inherited from Operateur_Diff_base
std::vector< const Operateur_Diff_base * > op_ext
Public Attributes inherited from Operateur_base
int col_width_
minimal size of a column for .out files (based on cl name length)
Detailed Description
Definition at line 24 of file Op_Dift_VDF_Face_Axi_base.h.
Constructor & Destructor Documentation
Op_Dift_VDF_Face_Axi_base()
Op_Dift_VDF_Face_Axi_base::Op_Dift_VDF_Face_Axi_base ()
Definition at line 19 of file Op_Dift_VDF_Face_Axi_base.cpp.
~Op_Dift_VDF_Face_Axi_base()
Op_Dift_VDF_Face_Axi_base::~Op_Dift_VDF_Face_Axi_base () override
Definition at line 19 of file Op_Dift_VDF_Face_Axi_base.cpp.
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_VDF_Face_Axi_base::ajouter (const DoubleTab & inco, DoubleTab & resu) const override private virtual
< seulement pour var_axi !
< Boucle sur les elements pour traiter les facettes situees a l'interieur des elements
< Boucle sur les aretes bord
< Boucle sur les aretes mixtes
< Boucle sur les aretes internes
Reimplemented from Operateur_base.
Definition at line 300 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  if (inco.line_size() > 1) not_implemented(__func__);
  const double temps = equation().schema_temps().temps_courant();
  mettre_a_jour_var(temps); //!< seulement pour var_axi !
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
  const DoubleVect& visco_turb = diffusivite_turbulente()->valeurs();
  const DoubleTab& tau_diag = inconnue->tau_diag(), &tau_croises = inconnue->tau_croises();
  ref_cast_non_const(Champ_Face,inconnue.valeur()).calculer_dercov_axi(zclvdf);
  ajouter_elem(visco_turb,tau_diag,resu); //!< Boucle sur les elements pour traiter les facettes situees a l'interieur des elements
  if (dimension == 3) ajouter_elem_3D(visco_turb,tau_diag,resu);
  ajouter_aretes_bords(visco_turb,tau_croises,resu); //!< Boucle sur les aretes bord
  ajouter_aretes_mixtes(tau_croises,resu); //!< Boucle sur les aretes mixtes
  ajouter_aretes_internes(visco_turb,tau_croises,resu); //!< Boucle sur les aretes internes
  return resu;
}
References ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_elem(), ajouter_elem_3D(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, MorEqn::equation(), inconnue, la_zcl_vdf, TRUSTVect< _TYPE_ >::line_size(), mettre_a_jour_var(), not_implemented(), ref_cast_non_const, Equation_base::schema_temps(), Champ_Face::tau_croises(), Champ_Face::tau_diag(), Schema_Temps_base::temps_courant(), Ref_Champ_Face::valeur(), Ref_Zone_Cl_VDF::valeur(), and Champ_Fonc::valeurs().
Referenced by calculer().
ajouter_aretes_bords()
void Op_Dift_VDF_Face_Axi_base::ajouter_aretes_bords (const DoubleVect & visco_turb, const DoubleTab & tau_croises, DoubleTab & resu) const private
< paroi-paroi
< XXX : E Saikali : sais pas quoi faire sinon ecarts ...
< Autre solution pour le calcul du frottement : On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
< bord d'equation R = cte
< bord d'equation teta = cte
< if (ori3b == 2) flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
Definition at line 103 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  const int ndeb = la_zone_vdf->premiere_arete_bord(), nfin = ndeb + la_zone_vdf->nb_aretes_bord();
  double d_visco_turb, d_visco_lam;
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int n_type = type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI: //!< paroi-paroi
          {
            const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), ori3 = orientation(fac3);
            const int rang1 = (fac1 - la_zone_vdf->premiere_face_bord()), rang2 = (fac2-la_zone_vdf->premiere_face_bord());
            double coef;
            if (is_VAR()) //!< XXX : E Saikali : sais pas quoi faire sinon ecarts ...
              {
// Calcul du frottement identique a celui de TRIOVF : On calcule la moyenne des u_star et on l'eleve au carre. On calcule la moyenne des surfaces
                const double tau_tan_1 = tau_tan(rang1,ori3), tau_tan_2 = tau_tan(rang2,ori3) ;
                double tau = 0.5*(tau_tan_1 + tau_tan_2 ), surf = 0.5*(surface(fac1)+surface(fac2));
                coef = tau*tau*surf;
              }
            else //!< Autre solution pour le calcul du frottement : On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
              {
                const double tau1 = tau_tan(rang1,ori3)*0.5*surface(fac1), tau2 = tau_tan(rang2,ori3)*0.5*surface(fac2);
                coef = tau1+tau2;
              }
            resu[fac3] += coef;
            break;
          }
        case TypeAreteBordVDF::FLUIDE_FLUIDE: /* fall through */
        case TypeAreteBordVDF::PAROI_FLUIDE:
          {
            const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), signe  = Qdm(n_arete,3), ori1b = orientation(fac1), ori3b = orientation(fac3);
            d_visco_turb = 0.5*(visco_turb(face_voisins(fac3,0)) + visco_turb(face_voisins(fac3,1)));
            d_visco_lam = nu_mean_2_pts_(face_voisins(fac3,0),face_voisins(fac3,1));
            if (ori1b == 0) //!< bord d'equation R = cte
              {
                double flux1;
                if (ori3b == 1)
                  {
                    const double tau12 = tau_croises(n_arete,0), tau21 = tau_croises(n_arete,1);
                    flux1 = (d_visco_lam*tau12 + d_visco_turb*(tau12+tau21))*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 2)
                  {
                    assert (ori3b == 2) ;
                    const double tau13 = tau_croises(n_arete,0), tau31 = tau_croises(n_arete,1);
                    flux1 = (d_visco_lam*tau13 + d_visco_turb*(tau13+tau31))*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3] += signe*flux1;
              }
            else if (ori1b == 1) //!< bord d'equation teta = cte
              {
                double flux2;
                if (ori3b == 0)
                  {
                    const double tau21 = tau_croises(n_arete,0), tau12 = tau_croises(n_arete,1);
                    flux2 = (d_visco_lam*tau21 + d_visco_turb*(tau12+tau21))*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
                    const double coef_laplacien_axi = 0.5*(d_visco_lam*tau21 + d_visco_turb*(tau12+tau21));
                    resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                    resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                  }
                else //!< if (ori3b == 2) flux de tau23 a travers le bord
                  {
                    assert (ori3b == 2);
                    const double tau23 = tau_croises(n_arete,0), tau32 = tau_croises(n_arete,1);
                    flux2 = (d_visco_lam*tau23 + d_visco_turb*(tau23+tau32))*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3] += signe*flux2;
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                double flux3;
                if (ori3b == 0)
                  {
                    const double tau31 = tau_croises(n_arete,0), tau13 = tau_croises(n_arete,1);
                    flux3 = (d_visco_lam*tau31 + d_visco_turb*(tau13+tau31))*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                else //if (ori3 == 1)  flux de tau32 a travers le bord
                  {
                    assert(ori3b == 1);
                    const double tau32 = tau_croises(n_arete,0), tau23 = tau_croises(n_arete,1);
                    flux3 = (d_visco_lam*tau32 + d_visco_turb*(tau23+tau32))*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                  }
                resu[fac3] += signe*flux3;
              }
            break;
          }
        case TypeAreteBordVDF::SYM_SYM:
          break;
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu : [ num arete : " << n_arete << " ], [ type : " << n_type << " ]" << finl;
            Process::exit();
            break;
          }
        }
    }
}
References Cerr, Process::exit(), face_voisins, finl, TypeAreteBordVDF::FLUIDE_FLUIDE, is_VAR(), la_zone_vdf, Zone_VDF::nb_aretes_bord(), nu_mean_2_pts_(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Zone_VF::premiere_face_bord(), Qdm, surface, TypeAreteBordVDF::SYM_SYM, tau_tan, type_arete_bord, volumes_entrelaces, and xv.
Referenced by ajouter().
ajouter_aretes_internes()
void Op_Dift_VDF_Face_Axi_base::ajouter_aretes_internes (const DoubleVect & visco_turb, const DoubleTab & tau_croises, DoubleTab & resu) const private
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Definition at line 262 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  const int ndeb = la_zone_vdf->premiere_arete_interne(), nfin = la_zone_vdf->nb_aretes();
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), fac4 = Qdm(n_arete,3), ori1 = orientation(fac1), ori3 = orientation(fac3);
// Calcul de la viscosite turbulente au milieu de l'arete
      const double d_visco_turb = 0.25*(visco_turb(face_voisins(fac3,0)) + visco_turb(face_voisins(fac3,1)) + visco_turb(face_voisins(fac4,0)) + visco_turb(face_voisins(fac4,1)));
      const double d_visco_lam = nu_mean_4_pts_(face_voisins(fac3,0), face_voisins(fac3,1), face_voisins(fac4,0), face_voisins(fac4,1));
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          const double tau12 = tau_croises(n_arete,0), tau21 = tau_croises(n_arete,1);
          fill_resu_aretes_internes(fac1,fac2,fac3,fac4,d_visco_lam,d_visco_turb,tau12,tau21,resu);
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
          const double coef_laplacien_axi = 0.5*(d_visco_lam*tau21 + d_visco_turb*(tau21+tau12));
          resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
          fill_resu_aretes_internes(fac3,fac4,fac1,fac2,d_visco_lam,d_visco_turb,tau21,tau12,resu);
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          const double tau23 = tau_croises(n_arete,0), tau32 = tau_croises(n_arete,1);
          fill_resu_aretes_internes(fac1,fac2,fac3,fac4,d_visco_lam,d_visco_turb,tau23,tau32,resu);
          fill_resu_aretes_internes(fac3,fac4,fac1,fac2,d_visco_lam,d_visco_turb,tau32,tau23,resu);
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
          const double tau13 = tau_croises(n_arete,0), tau31 = tau_croises(n_arete,1);
          fill_resu_aretes_internes(fac1,fac2,fac3,fac4,d_visco_lam,d_visco_turb,tau13,tau31,resu);
          fill_resu_aretes_internes(fac3,fac4,fac1,fac2,d_visco_lam,d_visco_turb,tau31,tau13,resu);
        }
    }
}
References face_voisins, fill_resu_aretes_internes(), la_zone_vdf, Zone_VDF::nb_aretes(), nu_mean_4_pts_(), orientation, porosite, Zone_VDF::premiere_arete_interne(), Qdm, volumes_entrelaces, and xv.
Referenced by ajouter().
ajouter_aretes_mixtes()
void Op_Dift_VDF_Face_Axi_base::ajouter_aretes_mixtes (const DoubleTab & tau_croises, DoubleTab & resu) const private
< XXX : BUG corrige dans cette fonction si ecart ...
< (seule possibilite : ori3 =0) Arete XY
< (seule possibilite ori1 = 2) arete YZ
< seule possibilite ori1 = 2 et ori3 = 0: arete XZ
Definition at line 218 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
// Sur les aretes mixtes les termes croises du tenseur de Reynolds sont nuls: il ne reste donc que la diffusion laminaire
  const int ndeb = la_zone_vdf->premiere_arete_mixte(), nfin = la_zone_vdf->premiere_arete_interne();
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int fac1=Qdm(n_arete,0), fac2=Qdm(n_arete,1), fac3=Qdm(n_arete,2), fac4=Qdm(n_arete,3), ori1 = orientation(fac1), ori3 = orientation(fac3);
      const double d_visco_lam = nu_mean_4_pts_(fac3,fac4); //!< XXX : BUG corrige dans cette fonction si ecart ...
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          const double tau12 = tau_croises(n_arete,0), tau21 = tau_croises(n_arete,1);
          fill_resu_aretes_mixtes(fac1,fac2,fac3,fac4,d_visco_lam,tau21,resu);
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
          const double coef_laplacien_axi = 0.5*d_visco_lam*tau21;
          resu(fac1) += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          resu(fac2) += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
          fill_resu_aretes_mixtes(fac3,fac4,fac1,fac2,d_visco_lam,tau12,resu);
        }
      else if (ori3 == 1) //!< (seule possibilite ori1 = 2) arete YZ
        {
          const double tau23 = tau_croises(n_arete,0), tau32 = tau_croises(n_arete,1);
          fill_resu_aretes_mixtes(fac1,fac2,fac3,fac4,d_visco_lam,tau32,resu);
          fill_resu_aretes_mixtes(fac3,fac4,fac1,fac2,d_visco_lam,tau23,resu);
        }
      else //!< seule possibilite ori1 = 2 et ori3 = 0:  arete XZ
        {
          const double tau13 = tau_croises(n_arete,0), tau31 = tau_croises(n_arete,1);
          fill_resu_aretes_mixtes(fac1,fac2,fac3,fac4,d_visco_lam,tau31,resu);
          fill_resu_aretes_mixtes(fac3,fac4,fac1,fac2,d_visco_lam,tau13,resu);
        }
    }
}
References fill_resu_aretes_mixtes(), la_zone_vdf, nu_mean_4_pts_(), orientation, porosite, Zone_VDF::premiere_arete_interne(), Zone_VDF::premiere_arete_mixte(), Qdm, volumes_entrelaces, and xv.
Referenced by ajouter().
ajouter_contribution()
void Op_Dift_VDF_Face_Axi_base::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const private
< seulement pour var_axi !
< Boucle sur les elements pour traiter les facettes situees a l'interieur des elements
< Boucle sur les aretes bord
< Boucle sur les aretes mixtes
< Boucle sur les aretes internes
Definition at line 558 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  if (inco.line_size() > 1) not_implemented(__func__);
  const double temps = equation().schema_temps().temps_courant();
  mettre_a_jour_var(temps); //!< seulement pour var_axi !
  const Zone_Cl_VDF& zclvdf = la_zcl_vdf.valeur();
  const DoubleVect& visco_turb = diffusivite_turbulente()->valeurs();
  const DoubleTab& tau_diag = inconnue->tau_diag();
  ref_cast_non_const(Champ_Face,inconnue.valeur()).calculer_dercov_axi(zclvdf);
  ajouter_contribution_elem(visco_turb,tau_diag,matrice); //!< Boucle sur les elements pour traiter les facettes situees a l'interieur des elements
  if (dimension == 3) ajouter_contribution_elem_3D(visco_turb,tau_diag,matrice);
  ajouter_contribution_aretes_bords(visco_turb,tau_diag,matrice); //!< Boucle sur les aretes bord
  ajouter_contribution_aretes_mixtes(matrice); //!< Boucle sur les aretes mixtes
  ajouter_contribution_aretes_internes(visco_turb,matrice); //!< Boucle sur les aretes internes
}
References ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), ajouter_contribution_elem_3D(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, MorEqn::equation(), inconnue, la_zcl_vdf, TRUSTVect< _TYPE_ >::line_size(), mettre_a_jour_var(), not_implemented(), ref_cast_non_const, Equation_base::schema_temps(), Champ_Face::tau_diag(), Schema_Temps_base::temps_courant(), Ref_Champ_Face::valeur(), Ref_Zone_Cl_VDF::valeur(), and Champ_Fonc::valeurs().
Referenced by contribuer_a_avec().
ajouter_contribution_aretes_bords()
void Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_bords (const DoubleVect & visco_turb, const DoubleTab & tau_diag, Matrice_Morse & matrice) const private
< bord d'equation R = cte
< bord d'equation teta = cte
< flux de tau23 a travers le bord
< (ori1 == 2) bord d'equation Z = cte
Definition at line 394 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  IntVect& tab1 = matrice.get_set_tab1(), &tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
  int ndeb = la_zone_vdf->premiere_arete_bord(), nfin = ndeb + la_zone_vdf->nb_aretes_bord();
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int n_type = type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI:
          break;
        case TypeAreteBordVDF::FLUIDE_FLUIDE: /* fall through */
        case TypeAreteBordVDF::PAROI_FLUIDE:
          {
            const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), signe  = Qdm(n_arete,3), ori1b = orientation(fac1), ori3b = orientation(fac3);
            const double d_visco_turb = 0.5*(visco_turb(face_voisins(fac3,0))+ visco_turb(face_voisins(fac3,1)));
            const double d_visco_lam = nu_mean_2_pts_(face_voisins(fac3,0),face_voisins(fac3,1));
            if (ori1b == 0) //!< bord d'equation R = cte
              {
// XXX j'ai supprime le if
                const double flux1 = (d_visco_lam+ d_visco_turb)*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                for (int l = tab1[fac3]-1; l < tab1[fac3+1]-1; l++)
                  if (tab2[l]-1 == fac3) coeff[l] += signe*flux1;
              }
            else if (ori1b == 1) //!< bord d'equation teta = cte
              {
                if (ori3b == 0)
                  {
                    const double flux2 = (d_visco_lam + d_visco_turb)*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                    for (int l = tab1[fac3]-1; l < tab1[fac3+1]-1; l++)
                      if (tab2[l]-1 == fac3) coeff[l] += signe*flux2;
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
                    const double coef_laplacien_axi = 0.5*(d_visco_lam + d_visco_turb);
                    for (int l = tab1[fac1]-1; l < tab1[fac1+1]-1; l++)
                      if (tab2[l]-1 == fac1) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
                    for (int l = tab1[fac2]-1; l < tab1[fac2+1]-1; l++)
                      if (tab2[l]-1 == fac2) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
                  }
                else if (ori3b == 2) //!< flux de tau23 a travers le bord
                  {
                    const double flux3 = (d_visco_lam + d_visco_turb)*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                    for (int l = tab1[fac3]-1; l < tab1[fac3+1]-1; l++)
                      if (tab2[l]-1 == fac3) coeff[l] += signe*flux3;
                  }
              }
            else //!< (ori1 == 2) bord d'equation Z = cte
              {
                const double flux4 = (d_visco_lam + d_visco_turb)*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
                for (int l = tab1[fac3]-1; l < tab1[fac3+1]-1; l++)
                  if (tab2[l]-1 == fac3) coeff[l] += signe*flux4;
              }
            break;
          }
        case TypeAreteBordVDF::SYM_SYM:
          break;
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu : [ num arete : " << n_arete << " ], [ type : " << n_type << " ]" << finl;
            Process::exit();
            break;
          }
        }
    }
}
References Cerr, coeff, Process::exit(), face_voisins, finl, TypeAreteBordVDF::FLUIDE_FLUIDE, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_zone_vdf, Zone_VDF::nb_aretes_bord(), nu_mean_2_pts_(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, porosite, Zone_VDF::premiere_arete_bord(), Qdm, surface, TypeAreteBordVDF::SYM_SYM, type_arete_bord, volumes_entrelaces, and xv.
Referenced by ajouter_contribution().
ajouter_contribution_aretes_internes()
void Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_internes (const DoubleVect & visco_turb, Matrice_Morse & matrice) const private
< (seule possibilite : ori3 =0) Arete XY
< 2 possibilites : ori1 = 2 et ori3 == 1: arete YZ OU ori1 = 2 et ori3 = 0: arete XZ
Definition at line 512 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  IntVect& tab1 = matrice.get_set_tab1(), &tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
  const int ndeb = la_zone_vdf->premiere_arete_interne(), nfin = la_zone_vdf->nb_aretes();
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), fac4 = Qdm(n_arete,3), ori1 = orientation(fac1);
// Calcul de la viscosite turbulente au milieu de l'arete
      const double d_visco_turb = 0.25*(visco_turb(face_voisins(fac3,0)) + visco_turb(face_voisins(fac3,1)) + visco_turb(face_voisins(fac4,0)) + visco_turb(face_voisins(fac4,1)));
      const double d_visco_lam = nu_mean_4_pts_(face_voisins(fac3,0), face_voisins(fac3,1), face_voisins(fac4,0), face_voisins(fac4,1));
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
// flux de mu_lam*tau21 + mu_turb*(tau21+tau12) sur la facette a cheval sur les faces fac1 et fac2
          double flux1;
          flux1 = (d_visco_lam + d_visco_turb)*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          fill_coeff_matrice_morse(fac3,fac4,flux1,matrice);
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
          const double coef_laplacien_axi = 0.5*(d_visco_lam + d_visco_turb);
          for (int l = tab1[fac1]-1; l < tab1[fac1+1]-1; l++)
            if (tab2[l]-1 == fac1) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          for (int l = tab1[fac2]-1; l < tab1[fac2+1]-1; l++)
            if (tab2[l]-1 == fac2) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
// flux de mu_lam*tau12 + mu_turb*(tau21+tau12) sur la facette a cheval sur les faces fac3 et fac4
          flux1 = (d_visco_lam + d_visco_turb)*0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          fill_coeff_matrice_morse(fac1,fac2,flux1,matrice);
        }
      else //!< 2 possibilites : ori1 = 2 et ori3 == 1: arete YZ OU  ori1 = 2 et ori3 = 0:  arete XZ
        {
          double flux2;
// flux de  mu_lam*tau31 + mu_turb*(tau31+tau13) sur la facette a cheval sur les faces fac1 et fac2
          flux2 = (d_visco_lam+ d_visco_turb)*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          fill_coeff_matrice_morse(fac3,fac4,flux2,matrice);
// flux de mu_lam*tau13 + mu_turb*(tau13+tau31) sur la facette a cheval sur les faces fac3 et fac4
          flux2 = (d_visco_lam + d_visco_turb)*0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          fill_coeff_matrice_morse(fac1,fac2,flux2,matrice);
        }
    }
}
References coeff, face_voisins, fill_coeff_matrice_morse(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_zone_vdf, Zone_VDF::nb_aretes(), nu_mean_4_pts_(), orientation, porosite, Zone_VDF::premiere_arete_interne(), Qdm, surface, volumes_entrelaces, and xv.
Referenced by ajouter_contribution().
ajouter_contribution_aretes_mixtes()
void Op_Dift_VDF_Face_Axi_base::ajouter_contribution_aretes_mixtes (Matrice_Morse & matrice) const private
< XXX : BUG corrige dans cette fonction si ecart ...
< (seule possibilite : ori3 =0) Arete XY
< 2 possibilites : ori1 = 2 et ori3 == 1: arete YZ OU ori1 = 2 et ori3 = 0: arete XZ
Definition at line 464 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  IntVect& tab1 = matrice.get_set_tab1(), &tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
// Sur les aretes mixtes les termes croises du tenseur de Reynolds sont nuls: il ne reste donc que la diffusion laminaire
  const int ndeb = la_zone_vdf->premiere_arete_mixte(), nfin = la_zone_vdf->premiere_arete_interne();
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), fac4 = Qdm(n_arete,3), ori1 = orientation(fac1);
      const double d_visco_lam = nu_mean_4_pts_(fac3,fac4); //!< XXX : BUG corrige dans cette fonction si ecart ...
      if (ori1 == 1)  //!< (seule possibilite : ori3 =0)  Arete XY
        {
          double flux1;
// flux de mu_lam*tau21 sur la facette a cheval sur les faces fac1 et fac2
          flux1 = d_visco_lam*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          fill_coeff_matrice_morse(fac3,fac4,flux1,matrice);
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
          const double coef_laplacien_axi = 0.5*d_visco_lam;
          for (int l = tab1[fac1]-1; l < tab1[fac1+1]-1; l++)
            if (tab2[l]-1 == fac1) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fac1)*porosite(fac1)/xv(fac1,0);
          for (int l = tab1[fac2]-1; l < tab1[fac2+1]-1; l++)
            if (tab2[l]-1 == fac2) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fac2)*porosite(fac2)/xv(fac2,0);
// flux de mu_lam*tau12 sur la facette a cheval sur les faces fac3 et fac4
          flux1 = d_visco_lam*0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          fill_coeff_matrice_morse(fac1,fac2,flux1,matrice);
        }
      else  //!< 2 possibilites : ori1 = 2 et ori3 == 1: arete YZ OU  ori1 = 2 et ori3 = 0:  arete XZ
        {
// flux de mu_lam*tau32 sur la facette a cheval sur les faces fac1 et fac2 ou
// flux de mu_lam*tau31 sur la facette a cheval sur les faces fac1 et fac2
          double flux2;
          flux2 = d_visco_lam*0.25*(surface(fac1)+surface(fac2))*(porosite(fac1)+porosite(fac2));
          fill_coeff_matrice_morse(fac3,fac4,flux2,matrice);
// flux de mu_lam*tau23 sur la facette a cheval sur les faces fac3 et fac4 ou
// flux de mu_lam*tau13 sur la facette a cheval sur les faces fac3 et fac4
          flux2 = d_visco_lam*0.25*(surface(fac3)+surface(fac4))*(porosite(fac3)+porosite(fac4));
          fill_coeff_matrice_morse(fac1,fac2,flux2,matrice);
        }
    }
}
References coeff, fill_coeff_matrice_morse(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), la_zone_vdf, nu_mean_4_pts_(), orientation, porosite, Zone_VDF::premiere_arete_interne(), Zone_VDF::premiere_arete_mixte(), Qdm, surface, volumes_entrelaces, and xv.
Referenced by ajouter_contribution().
ajouter_contribution_elem()
void Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem (const DoubleVect & visco_turb, const DoubleTab & tau_diag, Matrice_Morse & matrice) const private
< XXX : comprends rien la
Definition at line 342 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  IntVect& tab1 = matrice.get_set_tab1(), &tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
  for (int num_elem = 0; num_elem < la_zone_vdf->nb_elem(); num_elem++)
    {
      const int fx0 = elem_faces(num_elem,0), fx1 = elem_faces(num_elem,dimension), fy0 = elem_faces(num_elem,1), fy1 = elem_faces(num_elem,1+dimension);
      const double visc_elem = nu_(num_elem) + 2*visco_turb(num_elem);
      double flux_X, flux_Y;
      if (is_VAR())
        {
          flux_X = (visc_elem*tau_diag(num_elem,0))*0.5*(surface(fx0)+surface(fx1));
          flux_Y = (visc_elem*tau_diag(num_elem,1))*0.5*(surface(fy0)+surface(fy1));
        }
      else
        {
          flux_X = visc_elem*0.5*(surface(fx0)+surface(fx1));
          flux_Y = visc_elem*0.5*(surface(fy0)+surface(fy1));
        }
      fill_coeff_matrice_morse(fx0,fx1,flux_X,matrice);
      fill_coeff_matrice_morse(fy0,fy1,flux_Y,matrice);
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
      double coef_laplacien_axi;
      if (is_VAR()) coef_laplacien_axi = -0.5*(tau_diag(num_elem,1)*visc_elem);
      else coef_laplacien_axi = -0.5*visc_elem; //!< XXX : comprends rien la
      for (int l = tab1[fx0]-1; l < tab1[fx0+1]-1; l++)
        if (tab2[l]-1 == fx0) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fx0)*porosite(fx0)/xv(fx0,0);
      for (int l = tab1[fx1]-1; l < tab1[fx1+1]-1; l++)
        if (tab2[l]-1 == fx1) coeff[l] += coef_laplacien_axi*volumes_entrelaces(fx1)*porosite(fx1)/xv(fx1,0);
    }
}
References coeff, Objet_U::dimension, elem_faces, fill_coeff_matrice_morse(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), is_VAR(), la_zone_vdf, Zone_dis_base::nb_elem(), nu_(), porosite, surface, volumes_entrelaces, and xv.
Referenced by ajouter_contribution().
ajouter_contribution_elem_3D()
void Op_Dift_VDF_Face_Axi_base::ajouter_contribution_elem_3D (const DoubleVect & visco_turb, const DoubleTab & tau_diag, Matrice_Morse & matrice) const private
Definition at line 379 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  for (int num_elem = 0; num_elem < la_zone_vdf->nb_elem(); num_elem++)
    {
      const int fz0 = elem_faces(num_elem,2), fz1 = elem_faces(num_elem,2+dimension);
      const double visc_elem = nu_(num_elem) + 2*visco_turb(num_elem);
      double flux_Z;
      if (is_VAR()) flux_Z = (visc_elem*tau_diag(num_elem,2))*0.5*(surface(fz0)+surface(fz1));
      else flux_Z = visc_elem*0.5*(surface(fz0)+surface(fz1));
      fill_coeff_matrice_morse(fz0,fz1,flux_Z,matrice);
    }
}
References Objet_U::dimension, elem_faces, fill_coeff_matrice_morse(), is_VAR(), la_zone_vdf, Zone_dis_base::nb_elem(), nu_(), and surface.
Referenced by ajouter_contribution().
ajouter_elem()
void Op_Dift_VDF_Face_Axi_base::ajouter_elem (const DoubleVect & visco_turb, const DoubleTab & tau_diag, DoubleTab & resu) const private
< TODO FIXME EUH .?.?. Yannick help :/
< TODO FIXME EUH .?.?. Yannick help :/
Definition at line 73 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  for (int num_elem = 0; num_elem < la_zone_vdf->nb_elem(); num_elem++)
    {
      const int fx0 = elem_faces(num_elem,0), fx1 = elem_faces(num_elem,dimension), fy0 = elem_faces(num_elem,1), fy1 = elem_faces(num_elem,1+dimension);
      const double visc_elem = nu_(num_elem) + 2*visco_turb(num_elem);
      const double flux_X = (visc_elem*tau_diag(num_elem,0))*0.5*(surface(fx0)+surface(fx1)), flux_Y = (visc_elem*tau_diag(num_elem,1))*0.5*(surface(fy0)+surface(fy1));
      resu(fx0) += flux_X;
      resu(fx1) += flux_X; //!< TODO FIXME EUH .?.?. Yannick help :/
      resu(fy0) += flux_Y;
      resu(fy1) += flux_Y; //!< TODO FIXME EUH .?.?. Yannick help :/
// Termes supplementaires dans le laplacien en axi : Ils sont integres comme des termes sources
      const double coef_laplacien_axi = -0.5*(tau_diag(num_elem,1)*visc_elem);
      resu[fx0] += coef_laplacien_axi*volumes_entrelaces(fx0)*porosite(fx0)/xv(fx0,0);
      resu[fx1] += coef_laplacien_axi*volumes_entrelaces(fx1)*porosite(fx1)/xv(fx1,0);
    }
}
References Objet_U::dimension, elem_faces, la_zone_vdf, Zone_dis_base::nb_elem(), nu_(), porosite, surface, volumes_entrelaces, and xv.
Referenced by ajouter().
ajouter_elem_3D()
void Op_Dift_VDF_Face_Axi_base::ajouter_elem_3D (const DoubleVect & visco_turb, const DoubleTab & tau_diag, DoubleTab & resu) const private
Definition at line 92 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  for (int num_elem = 0; num_elem < la_zone_vdf->nb_elem(); num_elem++)
    {
      const int fz0 = elem_faces(num_elem,2), fz1 = elem_faces(num_elem,2+dimension);
      const double visc_elem = nu_(num_elem) + 2*visco_turb(num_elem), flux_Z = (visc_elem*tau_diag(num_elem,2))*0.5*(surface(fz0)+surface(fz1));
      resu[fz0] += flux_Z;
      resu[fz1] -= flux_Z;
    }
}
References Objet_U::dimension, elem_faces, la_zone_vdf, Zone_dis_base::nb_elem(), nu_(), and surface.
Referenced by ajouter().
associer()
void Op_Dift_VDF_Face_Axi_base::associer (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_cl_dis, const Champ_Inc & ch_transporte) override virtual
Implements Operateur_base.
Definition at line 24 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  const Zone_VDF& zvdf = ref_cast(Zone_VDF,zone_dis.valeur());
  const Zone_Cl_VDF& zclvdf = ref_cast(Zone_Cl_VDF,zone_cl_dis.valeur());
  const Champ_Face& inco = ref_cast(Champ_Face,ch_transporte.valeur());
  la_zone_vdf = zvdf;
  la_zcl_vdf = zclvdf;
  inconnue = inco;
  surface.ref(zvdf.face_surfaces());
  volumes_entrelaces.ref(zvdf.volumes_entrelaces());
  orientation.ref(zvdf.orientation());
  porosite.ref(zvdf.porosite_face());
  xp.ref(zvdf.xp());
  xv.ref(zvdf.xv());
  Qdm.ref(zvdf.Qdm());
  face_voisins.ref(zvdf.face_voisins());
  elem_faces.ref(zvdf.elem_faces());
  type_arete_bord.ref(zclvdf.type_arete_bord());
}
References Zone_VF::elem_faces(), elem_faces, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), face_voisins, inconnue, la_zcl_vdf, la_zone_vdf, orientation, Zone_VDF::orientation(), porosite, Zone_VF::porosite_face(), Qdm, Zone_VDF::Qdm(), TRUSTTab< _TYPE_ >::ref(), TRUSTVect< _TYPE_ >::ref(), ref_cast, surface, type_arete_bord, Zone_Cl_VDF::type_arete_bord(), Deriv_Champ_Inc_base::valeur(), Deriv_Zone_Cl_dis_base::valeur(), Deriv_Zone_dis_base::valeur(), Zone_VF::volumes_entrelaces(), volumes_entrelaces, Zone_VF::xp(), xp, Zone_VF::xv(), and xv.
associer_diffusivite_turbulente()
void Op_Dift_VDF_Face_Axi_base::associer_diffusivite_turbulente (const Champ_Fonc & visc_turb) inline
Definition at line 39 of file Op_Dift_VDF_Face_Axi_base.h.
{ Op_Diff_Turbulent_base::associer_diffusivite_turbulente(visc_turb);}
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente().
Referenced by associer_modele_turbulence().
associer_loipar()
void Op_Dift_VDF_Face_Axi_base::associer_loipar (const Turbulence_paroi &) inline
Definition at line 38 of file Op_Dift_VDF_Face_Axi_base.h.
{ /* do nothing */}
Referenced by associer_modele_turbulence().
associer_modele_turbulence()
void Op_Dift_VDF_Face_Axi_base::associer_modele_turbulence (const Mod_turb_hyd_base & mod)
Definition at line 66 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  le_modele_turbulence = mod;
  associer_diffusivite_turbulente(le_modele_turbulence->viscosite_turbulente());
  associer_loipar(le_modele_turbulence->loi_paroi()); /* on fait rien pour le moment ... */
}
References associer_diffusivite_turbulente(), associer_loipar(), le_modele_turbulence, Mod_turb_hyd_base::loi_paroi(), and Mod_turb_hyd_base::viscosite_turbulente().
Referenced by completer().
calculer()
DoubleTab & Op_Dift_VDF_Face_Axi_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
calcule la contribution de la diffusion, la range dans resu
Reimplemented from Op_Diff_VDF_base.
Definition at line 320 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  resu = 0;
  return ajouter(inco,resu);
}
References ajouter().
calculer_dt_stab()
double Op_Dift_VDF_Face_Axi_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 55 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  return Op_Dift_VDF_Face_base::calculer_dt_stab(la_zone_vdf.valeur()) ;
}
References Op_Dift_VDF_Face_base::calculer_dt_stab(), la_zone_vdf, and Ref_Zone_VDF::valeur().
completer()
void Op_Dift_VDF_Face_Axi_base::completer (void) override virtual
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_VDF_base.
Definition at line 44 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  Op_Dift_VDF_base::completer();
  Equation_base& eqn_hydr = equation();
  Champ_Face& vitesse = ref_cast(Champ_Face,eqn_hydr.inconnue().valeur());
  vitesse.dimensionner_tenseur_Grad();
  const RefObjU& modele_turbulence = eqn_hydr.get_modele(TURBULENCE);
  const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
  associer_modele_turbulence(mod_turb);
}
References associer_modele_turbulence(), Op_Diff_VDF_base::completer(), Champ_Face::dimensionner_tenseur_Grad(), MorEqn::equation(), Equation_base::get_modele(), Equation_base::inconnue(), ref_cast, TURBULENCE, Deriv_Champ_Inc_base::valeur(), and Ref_Objet_U::valeur().
contribue_au_second_membre()
void Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre (DoubleTab & resu) const
< seulement pour var_axi !
< Autre solution pour le calcul du frottement : On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
Definition at line 576 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  if (resu.line_size() > 1) not_implemented(__func__);
  const double temps = equation().schema_temps().temps_courant();
  mettre_a_jour_var(temps); //!< seulement pour var_axi !
  const int ndeb = la_zone_vdf->premiere_arete_bord(), nfin = ndeb + la_zone_vdf->nb_aretes_bord();
  for (int n_arete = ndeb; n_arete < nfin; n_arete++)
    {
      const int n_type = type_arete_bord(n_arete-ndeb);
      switch(n_type)
        {
        case TypeAreteBordVDF::PAROI_PAROI:
          {
            const int fac1 = Qdm(n_arete,0), fac2 = Qdm(n_arete,1), fac3 = Qdm(n_arete,2), ori3 = orientation(fac3);
            const int rang1 = (fac1 - la_zone_vdf->premiere_face_bord()), rang2 = (fac2 - la_zone_vdf->premiere_face_bord());
            double coef;
            if (is_VAR())
              {
// Calcul du frottement identique a celui de TRIOVF : On calcule la moyenne des u_star et on l'eleve au carre. On calcule la moyenne des surfaces
                const double tau = 0.5*(sqrt(tau_tan(rang1,ori3)) + sqrt(tau_tan(rang2,ori3))), surf = 0.5*(surface(fac1)+surface(fac2));
                coef = tau*tau*surf;
              }
            else //!< Autre solution pour le calcul du frottement : On calcule u_star*u_star*surf sur chaque partie de la facette de Qdm
              {
                const double tau1 = tau_tan(rang1,ori3)*0.5*surface(fac1), tau2 = tau_tan(rang2,ori3)*0.5*surface(fac2);
                coef = tau1+tau2;
              }
            resu[fac3] += coef;
            break;
          }
        case TypeAreteBordVDF::FLUIDE_FLUIDE: /* fall through */
        case TypeAreteBordVDF::PAROI_FLUIDE:
        case TypeAreteBordVDF::SYM_SYM:
          break;
        default :
          {
            Cerr << "On a rencontre un type d'arete non prevu : [ num arete : " << n_arete << " ], [ type : " << n_type << " ]" << finl;
            Process::exit();
            break;
          }
        }
    }
}
References Cerr, MorEqn::equation(), Process::exit(), finl, TypeAreteBordVDF::FLUIDE_FLUIDE, is_VAR(), la_zone_vdf, TRUSTVect< _TYPE_ >::line_size(), mettre_a_jour_var(), Zone_VDF::nb_aretes_bord(), not_implemented(), orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, Zone_VDF::premiere_arete_bord(), Zone_VF::premiere_face_bord(), Qdm, Equation_base::schema_temps(), surface, TypeAreteBordVDF::SYM_SYM, tau_tan, Schema_Temps_base::temps_courant(), and type_arete_bord.
Referenced by contribuer_au_second_membre().
contribuer_a_avec()
void Op_Dift_VDF_Face_Axi_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 36 of file Op_Dift_VDF_Face_Axi_base.h.
{ ajouter_contribution(inco, matrice); }
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Dift_VDF_Face_Axi_base::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Op_Dift_VDF_base.
Definition at line 37 of file Op_Dift_VDF_Face_Axi_base.h.
{ contribue_au_second_membre(resu); }
References contribue_au_second_membre().
dimensionner()
void Op_Dift_VDF_Face_Axi_base::dimensionner (Matrice_Morse & mat) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 40 of file Op_Dift_VDF_Face_Axi_base.h.
{ Op_VDF_Face::dimensionner(la_zone_vdf.valeur(), la_zcl_vdf.valeur(), matrice); }
References Op_VDF_Face::dimensionner(), la_zcl_vdf, la_zone_vdf, Ref_Zone_Cl_VDF::valeur(), and Ref_Zone_VDF::valeur().
fill_coeff_matrice_morse()
void Op_Dift_VDF_Face_Axi_base::fill_coeff_matrice_morse (const int fac1, const int fac2, const double flux, Matrice_Morse & matrice) const private
Definition at line 326 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  const IntVect& tab1 = matrice.get_set_tab1(), &tab2 = matrice.get_set_tab2();
  DoubleVect& coeff = matrice.get_set_coeff();
  for (int k = tab1[fac1]-1; k < tab1[fac1+1]-1; k++)
    {
      if (tab2[k]-1 == fac1) coeff[k] += flux;
      if (tab2[k]-1 == fac2) coeff[k] -= flux;
    }
  for (int k = tab1[fac2]-1; k < tab1[fac2+1]-1; k++)
    {
      if (tab2[k]-1 == fac1) coeff[k] -= flux;
      if (tab2[k]-1 == fac2) coeff[k] += flux;
    }
}
References coeff, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), and Matrice_Morse::get_set_tab2().
Referenced by ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), and ajouter_contribution_elem_3D().
fill_resu_aretes_internes()
void Op_Dift_VDF_Face_Axi_base::fill_resu_aretes_internes (const int i, const int j, const int k, const int l, const double v_lam, const double v_turb, const double tau1, const double tau2, DoubleTab & resu) const private
Definition at line 254 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
// flux de v_lam*tau2 + v_turb*(tau2+tau1) sur la facette a cheval sur les faces i et j
  const double flux = (v_lam*tau2 + v_turb*(tau2+tau1))*0.25*(surface(i)+surface(j))*(porosite(i)+porosite(j));
  resu(k) += flux;
  resu(l) -= flux;
}
References porosite, and surface.
Referenced by ajouter_aretes_internes().
fill_resu_aretes_mixtes()
void Op_Dift_VDF_Face_Axi_base::fill_resu_aretes_mixtes (const int i, const int j, const int k, const int l, const double d_visco_lam, const double tau, DoubleTab & resu) const private
Definition at line 210 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
// flux de mu_lam*tau sur la facette a cheval sur les faces i et j
  const double flux = d_visco_lam*tau*0.25*(surface(i)+surface(j))*(porosite(i)+porosite(j));
  resu(k) += flux;
  resu(l) -= flux;
}
References porosite, and surface.
Referenced by ajouter_aretes_mixtes().
get_info()
const Type_info * Op_Dift_VDF_Face_Axi_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Definition at line 19 of file Op_Dift_VDF_Face_Axi_base.cpp.
info()
const Type_info * Op_Dift_VDF_Face_Axi_base::info () static
Definition at line 19 of file Op_Dift_VDF_Face_Axi_base.cpp.
is_VAR()
virtual bool Op_Dift_VDF_Face_Axi_base::is_VAR () const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Referenced by ajouter_aretes_bords(), ajouter_contribution_elem(), ajouter_contribution_elem_3D(), and contribue_au_second_membre().
mettre_a_jour()
void Op_Dift_VDF_Face_Axi_base::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour de l'operateur.
Reimplemented from Operateur_base.
Definition at line 60 of file Op_Dift_VDF_Face_Axi_base.cpp.
{
  if (le_modele_turbulence->loi_paroi().non_nul()) tau_tan.ref(le_modele_turbulence->loi_paroi()->Cisaillement_paroi());
}
References Turbulence_paroi::Cisaillement_paroi(), le_modele_turbulence, Mod_turb_hyd_base::loi_paroi(), O_U_Ptr::non_nul(), TRUSTTab< _TYPE_ >::ref(), and tau_tan.
mettre_a_jour_var()
virtual void Op_Dift_VDF_Face_Axi_base::mettre_a_jour_var (double) const protected pure virtual
Implemented in Op_Dift_VDF_var_Face_Axi, and Op_Dift_VDF_Face_Axi.
Referenced by ajouter(), ajouter_contribution(), and contribue_au_second_membre().
modifier_pour_Cl()
void Op_Dift_VDF_Face_Axi_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 41 of file Op_Dift_VDF_Face_Axi_base.h.
{ Op_VDF_Face::modifier_pour_Cl(la_zone_vdf.valeur(), la_zcl_vdf.valeur(), matrice,  secmem); }
References la_zcl_vdf, la_zone_vdf, Op_VDF_Face::modifier_pour_Cl(), Ref_Zone_Cl_VDF::valeur(), and Ref_Zone_VDF::valeur().
not_implemented()
void Op_Dift_VDF_Face_Axi_base::not_implemented (const char * nom_funct) const inline private
Definition at line 78 of file Op_Dift_VDF_Face_Axi_base.h.
  {
    std::cerr << "Erreur dans : " << nom_funct << std::endl;
    std::cerr << "On ne sait pas traiter la diffusion d'un Champ_Face a plusieurs inconnues ! " << std::endl;
    throw;
  }
Referenced by ajouter(), ajouter_contribution(), and contribue_au_second_membre().
nu_()
virtual double Op_Dift_VDF_Face_Axi_base::nu_ (const int) const protected pure virtual
Implemented in Op_Dift_VDF_var_Face_Axi, and Op_Dift_VDF_Face_Axi.
Referenced by ajouter_contribution_elem(), ajouter_contribution_elem_3D(), ajouter_elem(), and ajouter_elem_3D().
nu_mean_2_pts_()
virtual double Op_Dift_VDF_Face_Axi_base::nu_mean_2_pts_ (const int , const int) const protected pure virtual
Implemented in Op_Dift_VDF_var_Face_Axi, and Op_Dift_VDF_Face_Axi.
Referenced by ajouter_aretes_bords(), and ajouter_contribution_aretes_bords().
nu_mean_4_pts_() [1/2]
virtual double Op_Dift_VDF_Face_Axi_base::nu_mean_4_pts_ (const int , const int) const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Referenced by ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_internes(), and ajouter_contribution_aretes_mixtes().
nu_mean_4_pts_() [2/2]
virtual double Op_Dift_VDF_Face_Axi_base::nu_mean_4_pts_ (const int , const int , const int , const int) const protected pure virtual
Implemented in Op_Dift_VDF_var_Face_Axi, and Op_Dift_VDF_Face_Axi.
printOn()
Sortie & Op_Dift_VDF_Face_Axi_base::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Definition at line 21 of file Op_Dift_VDF_Face_Axi_base.cpp.
{ return s << que_suis_je() ; }
References Objet_U::que_suis_je().
readOn()
Entree & Op_Dift_VDF_Face_Axi_base::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Dift_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi, and Op_Dift_VDF_var_Face_Axi.
Definition at line 22 of file Op_Dift_VDF_Face_Axi_base.cpp.
{ return s ; }
self_cast() [1/2]
const Op_Dift_VDF_Face_Axi_base & Op_Dift_VDF_Face_Axi_base::self_cast (const Objet_U & r) static
Definition at line 19 of file Op_Dift_VDF_Face_Axi_base.cpp.
self_cast() [2/2]
Op_Dift_VDF_Face_Axi_base & Op_Dift_VDF_Face_Axi_base::self_cast (Objet_U & r) static
Definition at line 19 of file Op_Dift_VDF_Face_Axi_base.cpp.
Member Data Documentation
elem_faces
IntTab Op_Dift_VDF_Face_Axi_base::elem_faces protected
Definition at line 49 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_contribution_elem(), ajouter_contribution_elem_3D(), ajouter_elem(), ajouter_elem_3D(), and associer().
face_voisins
IntTab Op_Dift_VDF_Face_Axi_base::face_voisins protected
Definition at line 49 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), associer(), and Op_Dift_VDF_var_Face_Axi::nu_mean_4_pts_().
inconnue
Ref_Champ_Face Op_Dift_VDF_Face_Axi_base::inconnue protected
Definition at line 45 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter(), ajouter_contribution(), and associer().
info_obj
const Type_info Op_Dift_VDF_Face_Axi_base::info_obj static
Definition at line 26 of file Op_Dift_VDF_Face_Axi_base.h.
la_zcl_vdf
Ref_Zone_Cl_VDF Op_Dift_VDF_Face_Axi_base::la_zcl_vdf protected
Definition at line 47 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter(), ajouter_contribution(), associer(), dimensionner(), and modifier_pour_Cl().
la_zone_vdf
Ref_Zone_VDF Op_Dift_VDF_Face_Axi_base::la_zone_vdf protected
Definition at line 46 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), ajouter_contribution_elem_3D(), ajouter_elem(), ajouter_elem_3D(), associer(), calculer_dt_stab(), contribue_au_second_membre(), dimensionner(), and modifier_pour_Cl().
le_modele_turbulence
Ref_Mod_turb_hyd_base Op_Dift_VDF_Face_Axi_base::le_modele_turbulence protected
Definition at line 44 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by associer_modele_turbulence(), and mettre_a_jour().
orientation
IntVect Op_Dift_VDF_Face_Axi_base::orientation protected
Definition at line 48 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), associer(), and contribue_au_second_membre().
porosite
DoubleVect Op_Dift_VDF_Face_Axi_base::porosite protected
Definition at line 50 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), ajouter_elem(), associer(), fill_resu_aretes_internes(), and fill_resu_aretes_mixtes().
Qdm
IntTab Op_Dift_VDF_Face_Axi_base::Qdm protected
Definition at line 49 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), associer(), and contribue_au_second_membre().
surface
DoubleVect Op_Dift_VDF_Face_Axi_base::surface protected
Definition at line 50 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), ajouter_contribution_elem_3D(), ajouter_elem(), ajouter_elem_3D(), associer(), contribue_au_second_membre(), fill_resu_aretes_internes(), and fill_resu_aretes_mixtes().
tau_tan
DoubleTab Op_Dift_VDF_Face_Axi_base::tau_tan protected
Definition at line 51 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), contribue_au_second_membre(), and mettre_a_jour().
type_arete_bord
IntVect Op_Dift_VDF_Face_Axi_base::type_arete_bord protected
Definition at line 48 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_contribution_aretes_bords(), associer(), and contribue_au_second_membre().
volumes_entrelaces
DoubleVect Op_Dift_VDF_Face_Axi_base::volumes_entrelaces protected
Definition at line 50 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), ajouter_elem(), and associer().
xp
DoubleTab Op_Dift_VDF_Face_Axi_base::xp protected
Definition at line 51 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by associer().
xv
DoubleTab Op_Dift_VDF_Face_Axi_base::xv protected
Definition at line 51 of file Op_Dift_VDF_Face_Axi_base.h.
Referenced by ajouter_aretes_bords(), ajouter_aretes_internes(), ajouter_aretes_mixtes(), ajouter_contribution_aretes_bords(), ajouter_contribution_aretes_internes(), ajouter_contribution_aretes_mixtes(), ajouter_contribution_elem(), ajouter_elem(), and associer().
The documentation for this class was generated from the following files:
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_base/Op_Dift_VDF_Face_Axi_base.h
src/VDF/Operateurs/Op_Diff_Dift/Op_Diff_Dift_base/Op_Dift_VDF_Face_Axi_base.cpp