TRUST: Schema_Comm_Vecteurs Class Reference
Schema_Comm_Vecteurs Class Reference
Classe outil utilisee notamment par les methodes MD_Vector::echange_espace_virtuel()
Permet d'echanger avec d'autres processeurs des blocs d'ints ou de double
accessibles par des tableaux dans lesquels on lit et on ecrit directement<br>(contrairement a Schema_Comm qui utilise readOn et printOn, plus lent).
Pour des raisons de performances, la communication est separee en deux parties
- definition des tailles de buffers (permet d'allouer a l'avance les bufffers
begin_init()
add_send/recv_area_int/double(processeur, size)
(declaration des types, tailles et processeurs destinataire des blocs que l'on va envoyer,
on peut envoyer plusieurs blocs de types identiques ou differents a chaque processeur)
end_init()
- echange de donnees (autant de fois qu'on veut):
begin_comm()
for(each bloc to send) {
ArrOfInt/Double & buf = get_next_area_int/double(pe, size);
for (i=0; i<size; i++)
buf[i] = ...
}
exchange();
for (each bloc to recv) {
... get_next_area_int/double(...)
end_comm();.
#include <Schema_Comm_Vecteurs.h>
Public Member Functions
Schema_Comm_Vecteurs ()
~Schema_Comm_Vecteurs ()
void begin_init ()
Reinitialise les tailles de buffers.
Il faut ensuite definir les tailles de buffers avec add_send/recv_area_...()
Cette methode doit etre appelee simultanement sur tous les processeurs du groupe.
template<typename _TYPE_ >
void add_send_area_template (int pe, int size)
template<typename _TYPE_ >
void add_recv_area_template (int pe, int size)
template<typename _TYPE_ >
TRUSTArray< _TYPE_ > & get_next_area_template (int pe, int array_size)
void end_init ()
Une fois les donnees a echanger declarees avec add_send/recv_area_...(),
initialise les offset de buffers et alloue un buffer global de taille
suffisante.
Methode a appeler par tous les processeurs du groupe.
void begin_comm ()
Commence un nouvel echange de donnees (les tailles de buffers
doivent avoir ete initialisees avec begin_init() ... end_init())
On place les sdata_.buf_pointers_ au debut des buffers pour chaque
processeur pour lequel un buffer a ete declare en "send"
Apres begin_comm(), il faut remplir les buffers en utilisant
get_next_area_int() ou get_next_area_double() dans le meme
ordre que celui declare dans la phase d'initialisation,
puis appeler exchange()
void exchange ()
void end_comm ()
template<>
void add_send_area_template (int pe, int size)
template<>
void add_send_area_template (int pe, int size)
template<>
void add_recv_area_template (int pe, int size)
template<>
void add_recv_area_template (int pe, int size)
template<>
ArrOfInt & get_next_area_template (int pe, int size)
renvoie un tableau contenant les "size" valeurs suivantes
recues du processeur pe lors de la communication en cours.
Attention:
Le tableau renvoye est une reference a un tableau interne qui n'est valide que
jusqu'au prochain appel a une methode get_next_xxx.
template<>
ArrOfDouble & get_next_area_template (int pe, int size)
Protected Types
enum Status {
RESET , BEGIN_INIT , END_INIT , BEGIN_COMM ,
EXCHANGED
}
Protected Member Functions
void add (int pe, int size, ArrOfInt &procs, ArrOfInt &buf_sizes, int align_size)
int check_buffers_full () const
Selon status_, verifie que tous les pointeurs de buffers
pointent a la fin du buffer aloue pour chaque processeur en emission
ou reception. Renvoie 0 en cas d'erreur (si un buffer n'a pas ete
entierement rempli ou vide)
int check_next_area (int pe, int byte_size) const
verifie qu'il reste au moins byte_size octets dans le buffer du processeur pe
Protected Attributes
ArrOfInt send_buf_sizes_
ArrOfInt recv_buf_sizes_
ArrOfInt send_procs_
ArrOfInt recv_procs_
int sorted_
int min_buf_size_
Status status_
Static Protected Attributes
static int buffer_locked_
static ArrOfDouble tmp_area_double_
static ArrOfInt tmp_area_int_
static Schema_Comm_Vecteurs_Static_Data sdata_
Detailed Description
Classe outil utilisee notamment par les methodes MD_Vector::echange_espace_virtuel()
Permet d'echanger avec d'autres processeurs des blocs d'ints ou de double
accessibles par des tableaux dans lesquels on lit et on ecrit directement<br>(contrairement a Schema_Comm qui utilise readOn et printOn, plus lent).
Pour des raisons de performances, la communication est separee en deux parties
- definition des tailles de buffers (permet d'allouer a l'avance les bufffers
begin_init()
add_send/recv_area_int/double(processeur, size)
(declaration des types, tailles et processeurs destinataire des blocs que l'on va envoyer,
on peut envoyer plusieurs blocs de types identiques ou differents a chaque processeur)
end_init()
- echange de donnees (autant de fois qu'on veut):
begin_comm()
for(each bloc to send) {
ArrOfInt/Double & buf = get_next_area_int/double(pe, size);
for (i=0; i<size; i++)
buf[i] = ...
}
exchange();
for (each bloc to recv) {
... get_next_area_int/double(...)
end_comm();.
Definition at line 45 of file Schema_Comm_Vecteurs.h.
Member Enumeration Documentation
Status
enum Schema_Comm_Vecteurs::Status protected
Enumerator
RESET
BEGIN_INIT
END_INIT
BEGIN_COMM
EXCHANGED
Definition at line 85 of file Schema_Comm_Vecteurs.h.
{ RESET, BEGIN_INIT, END_INIT, BEGIN_COMM, EXCHANGED };
Constructor & Destructor Documentation
Schema_Comm_Vecteurs()
Schema_Comm_Vecteurs::Schema_Comm_Vecteurs ()
Definition at line 62 of file Schema_Comm_Vecteurs.cpp.
{
  status_ = RESET;
  send_buf_sizes_.set_smart_resize(1);
  recv_buf_sizes_.set_smart_resize(1);
  send_procs_.set_smart_resize(1);
  recv_procs_.set_smart_resize(1);
}
References recv_buf_sizes_, recv_procs_, RESET, send_buf_sizes_, send_procs_, TRUSTArray< _TYPE_ >::set_smart_resize(), and status_.
~Schema_Comm_Vecteurs()
Schema_Comm_Vecteurs::~Schema_Comm_Vecteurs ()
Definition at line 71 of file Schema_Comm_Vecteurs.cpp.
{
  assert (status_ == END_INIT || status_ == RESET);
}
References END_INIT, RESET, and status_.
Member Function Documentation
add()
void Schema_Comm_Vecteurs::add (int pe, int size, ArrOfInt & procs, ArrOfInt & buf_sizes, int align_size) inline protected
< Padding before block
Definition at line 125 of file Schema_Comm_Vecteurs.h.
{
  assert(status_ == BEGIN_INIT);
  assert(size >= 0);
  int& x = buf_sizes[pe];
  if (x == 0 && size > 0)
    {
      const int n = procs.size_array();
      if (n > 0 && procs[n-1] > pe)
        sorted_ = 0;
      procs.append_array(pe);
    }
  x = ((x+align_size-1)&(~(align_size-1))) + size; //!< Padding before block
}
References TRUSTArray< _TYPE_ >::append_array(), BEGIN_INIT, TRUSTArray< _TYPE_ >::size_array(), sorted_, and status_.
Referenced by add_recv_area_template(), and add_send_area_template().
add_recv_area_template() [1/3]
template<typename _TYPE_ > void Schema_Comm_Vecteurs::add_recv_area_template (int pe, int size) inline
Referenced by MD_Vector_std::initialize_comm_template().
add_recv_area_template() [2/3]
template<> void Schema_Comm_Vecteurs::add_recv_area_template (int pe, int size) inline
Definition at line 154 of file Schema_Comm_Vecteurs.h.
{
  add(pe, BLOCSIZE_INT(size), recv_procs_, recv_buf_sizes_, sizeof(int));
}
References add(), BLOCSIZE_INT, recv_buf_sizes_, and recv_procs_.
add_recv_area_template() [3/3]
template<> void Schema_Comm_Vecteurs::add_recv_area_template (int pe, int size) inline
Definition at line 160 of file Schema_Comm_Vecteurs.h.
{
  add(pe, BLOCSIZE_DOUBLE(size), recv_procs_, recv_buf_sizes_, sizeof(double));
}
References add(), BLOCSIZE_DOUBLE, recv_buf_sizes_, and recv_procs_.
add_send_area_template() [1/3]
template<typename _TYPE_ > void Schema_Comm_Vecteurs::add_send_area_template (int pe, int size) inline
Referenced by MD_Vector_std::initialize_comm_template().
add_send_area_template() [2/3]
template<> void Schema_Comm_Vecteurs::add_send_area_template (int pe, int size) inline
Definition at line 142 of file Schema_Comm_Vecteurs.h.
{
  add(pe, BLOCSIZE_INT(size), send_procs_, send_buf_sizes_, sizeof(int));
}
References add(), BLOCSIZE_INT, send_buf_sizes_, and send_procs_.
add_send_area_template() [3/3]
template<> void Schema_Comm_Vecteurs::add_send_area_template (int pe, int size) inline
Definition at line 148 of file Schema_Comm_Vecteurs.h.
{
  add(pe, BLOCSIZE_DOUBLE(size), send_procs_, send_buf_sizes_, sizeof(double));
}
References add(), BLOCSIZE_DOUBLE, send_buf_sizes_, and send_procs_.
begin_comm()
void Schema_Comm_Vecteurs::begin_comm ()
Commence un nouvel echange de donnees (les tailles de buffers
doivent avoir ete initialisees avec begin_init() ... end_init())
On place les sdata_.buf_pointers_ au debut des buffers pour chaque
processeur pour lequel un buffer a ete declare en "send"
Apres begin_comm(), il faut remplir les buffers en utilisant
get_next_area_int() ou get_next_area_double() dans le meme
ordre que celui declare dans la phase d'initialisation,
puis appeler exchange()
Definition at line 173 of file Schema_Comm_Vecteurs.cpp.
{
  assert(status_ == END_INIT);
// Pas un assert car erreur grave et sans doute rare...
  if (buffer_locked_)
    {
      Cerr << "Internal error in Schema_Comm_Vecteurs::begin_comm(): buffers already locked by another communication" << finl;
      Process::exit();
    }
  buffer_locked_ = 1;
  sdata_.init(min_buf_size_);
// Fait pointer les buffers sur le debut des send_buffers
  char *ptr = sdata_.buffer_base_;
  const int nsend = send_procs_.size_array();
  for (int i = 0; i < nsend; i++)
    {
      const int pe = send_procs_[i];
      sdata_.buf_pointers_[pe] = ptr;
      ptr += send_buf_sizes_[i];
    }
  buffer_locked_ = 1;
  status_ = BEGIN_COMM;
}
References BEGIN_COMM, Schema_Comm_Vecteurs_Static_Data::buf_pointers_, Schema_Comm_Vecteurs_Static_Data::buffer_base_, buffer_locked_, Cerr, END_INIT, Process::exit(), finl, Schema_Comm_Vecteurs_Static_Data::init(), min_buf_size_, sdata_, send_buf_sizes_, send_procs_, TRUSTArray< _TYPE_ >::size_array(), and status_.
Referenced by echange_espace_virtuel_().
begin_init()
void Schema_Comm_Vecteurs::begin_init ()
Reinitialise les tailles de buffers.
Il faut ensuite definir les tailles de buffers avec add_send/recv_area_...()
Cette methode doit etre appelee simultanement sur tous les processeurs du groupe.
Definition at line 81 of file Schema_Comm_Vecteurs.cpp.
{
  assert(status_ == END_INIT || status_ == RESET);
// Reset des tableaux sizes_
  const int np = Process::nproc();
  send_buf_sizes_.resize_array(np, ArrOfInt::NOCOPY_NOINIT);
  send_buf_sizes_ = 0;
  recv_buf_sizes_.resize_array(np, ArrOfInt::NOCOPY_NOINIT);
  recv_buf_sizes_ = 0;
  send_procs_.resize_array(0);
  recv_procs_.resize_array(0);
  sorted_ = 1;
  status_ = BEGIN_INIT;
}
References BEGIN_INIT, END_INIT, Array_base::NOCOPY_NOINIT, Process::nproc(), recv_buf_sizes_, recv_procs_, RESET, TRUSTArray< _TYPE_ >::resize_array(), send_buf_sizes_, send_procs_, sorted_, and status_.
Referenced by echange_espace_virtuel_().
check_buffers_full()
int Schema_Comm_Vecteurs::check_buffers_full () const protected
Selon status_, verifie que tous les pointeurs de buffers
pointent a la fin du buffer aloue pour chaque processeur en emission
ou reception. Renvoie 0 en cas d'erreur (si un buffer n'a pas ete
entierement rempli ou vide)
Definition at line 258 of file Schema_Comm_Vecteurs.cpp.
{
  char *ptr = sdata_.buffer_base_;
  const int nsend = send_procs_.size_array();
  int i;
  int ok = 1;
  if (status_ == BEGIN_COMM)
    {
      for (i = 0; i < nsend; i++)
        {
          ptr += send_buf_sizes_[i];
          const int pe = send_procs_[i];
          char *ptr2 = sdata_.buf_pointers_[pe];
          ALIGN_SIZE(ptr2, sizeof(double));
          if (ptr != ptr2)
            {
              Cerr << "Internal error in Schema_Comm_Vecteurs::check_buffers_full(): send buffer for processor "
                   << pe << " is not full" << finl;
              ok = 0;
            }
        }
    }
  else if (status_ == EXCHANGED)
    {
      for (i = 0; i < nsend; i++)
        ptr += send_buf_sizes_[i];
      const int nrecv = recv_procs_.size_array();
      for (i = 0; i < nrecv; i++)
        {
          ptr += recv_buf_sizes_[i];
          const int pe = recv_procs_[i];
          char *ptr2 = sdata_.buf_pointers_[pe];
          ALIGN_SIZE(ptr2, sizeof(double));
          if (ptr != ptr2)
            {
              Cerr << "Internal error in Schema_Comm_Vecteurs::check_buffers_full(): recv buffer for processor "
                   << pe << " has not been read entirely" << finl;
              ok = 0;
            }
        }
    }
  else
    {
      Cerr << "check_buffers_full: What ?" << finl;
      Process::exit();
    }
  return ok;
}
References ALIGN_SIZE, BEGIN_COMM, Schema_Comm_Vecteurs_Static_Data::buf_pointers_, Schema_Comm_Vecteurs_Static_Data::buffer_base_, Cerr, EXCHANGED, Process::exit(), finl, recv_buf_sizes_, recv_procs_, sdata_, send_buf_sizes_, send_procs_, TRUSTArray< _TYPE_ >::size_array(), and status_.
Referenced by end_comm(), and exchange().
check_next_area()
int Schema_Comm_Vecteurs::check_next_area (int pe, int byte_size) const protected
verifie qu'il reste au moins byte_size octets dans le buffer du processeur pe
< pointeur sur la fin du buffer de ce processeur
Definition at line 308 of file Schema_Comm_Vecteurs.cpp.
{
  assert(byte_size >= 0);
  if (byte_size == 0)
    {
      return 1;
    }
  const ArrOfInt& procs = (status_ == BEGIN_COMM) ? send_procs_ : recv_procs_;
  const ArrOfInt& sizes = (status_ == BEGIN_COMM) ? send_buf_sizes_ : recv_buf_sizes_;
  const int n = procs.size_array();
  int i;
  char * ptr = sdata_.buffer_base_;
// Si on est en phase de reception, le debut des buffers de reception se trouve a la
// fin des buffers en emission:
  if (status_ != BEGIN_COMM)
    {
      const int nsend = send_procs_.size_array();
      for (i = 0; i < nsend; i++)
        ptr += send_buf_sizes_[i];
    }
  for (i = 0; i < n; i++)
    {
      ptr += sizes[i]; //!< pointeur sur la fin du buffer de ce processeur
      if (procs[i] == pe)
        return (sdata_.buf_pointers_[pe] + byte_size) <= ptr;
    }
// aucun buffer declare pour ce processeur
  return 0;
}
References BEGIN_COMM, Schema_Comm_Vecteurs_Static_Data::buf_pointers_, Schema_Comm_Vecteurs_Static_Data::buffer_base_, recv_buf_sizes_, recv_procs_, sdata_, send_buf_sizes_, send_procs_, TRUSTArray< _TYPE_ >::size_array(), and status_.
Referenced by get_next_area_template().
end_comm()
void Schema_Comm_Vecteurs::end_comm ()
< pret pour un nouveau begin_comm()
Definition at line 245 of file Schema_Comm_Vecteurs.cpp.
{
  assert(status_ == EXCHANGED);
// Verifie qu'on a bien lu toutes les donnees
  assert(check_buffers_full());
  status_ = END_INIT; //!< pret pour un nouveau begin_comm()
  buffer_locked_ = 0;
}
References buffer_locked_, check_buffers_full(), END_INIT, EXCHANGED, and status_.
Referenced by echange_espace_virtuel_().
end_init()
void Schema_Comm_Vecteurs::end_init ()
Une fois les donnees a echanger declarees avec add_send/recv_area_...(),
initialise les offset de buffers et alloue un buffer global de taille
suffisante.
Methode a appeler par tous les processeurs du groupe.
< align size on 8 bytes
< send_procs_ trie dans l'ordre croissant
< align size on 8 bytes
< recv_procs_ trie dans l'ordre croissant
< taille du buffer a alouer recv_buf_offset_[i] = offset;
Definition at line 103 of file Schema_Comm_Vecteurs.cpp.
{
  assert(status_ == BEGIN_INIT);
  assert(Process::nproc() == send_buf_sizes_.size_array());
// Verification des tailles en emission et en reception:
  if (Comm_Group::check_enabled())
    {
      const int n = send_buf_sizes_.size_array();
      ArrOfInt tmp(n);
      envoyer_all_to_all(send_buf_sizes_, tmp);
      int err = 0;
      for (int i = 0; i < n; i++)
        if (tmp[i] != recv_buf_sizes_[i])
          err++;
      if (Process::mp_sum(err))
        {
          Cerr << "Error in Schema_Comm_Vecteurs::end_init(): send_size_ and recv_size_ don't match, see log files" << finl;
          Process::Journal() << "Error in Schema_Comm_Vecteurs::end_init():\n"
                             << "send_sizes_ = " << send_buf_sizes_
                             << "\n recv_sizes_ = " << recv_buf_sizes_ << finl;
          Process::barrier();
          Process::exit();
        }
    }
// Tri des numeros de processeurs dans l'ordre croissant
  if (!sorted_)
    {
      send_procs_.ordonne_array();
      recv_procs_.ordonne_array();
    }
  const int nsend = send_procs_.size_array();
  const int nrecv = recv_procs_.size_array();
  int offset = 0;
  int i;
  for (i = 0; i < nsend; i++)
    {
      int pe = send_procs_[i];
      const int size = (send_buf_sizes_[pe]+7)&(~7); //!< align size on 8 bytes
      offset += size;
      assert(pe >= i); //!< send_procs_ trie dans l'ordre croissant
      send_buf_sizes_[i] = size;
    }
  for (i = 0; i < nrecv; i++)
    {
      int pe = recv_procs_[i];
      const int size = (recv_buf_sizes_[pe]+7)&(~7); //!< align size on 8 bytes
      offset += size;
      assert(pe >= i); //!< recv_procs_ trie dans l'ordre croissant
      recv_buf_sizes_[i] = size;
    }
  min_buf_size_ = offset; //!< taille du buffer a alouer    recv_buf_offset_[i] = offset;
  send_buf_sizes_.resize_array(nsend);
  recv_buf_sizes_.resize_array(nrecv);
  status_ = END_INIT;
}
References Process::barrier(), BEGIN_INIT, Cerr, Comm_Group::check_enabled(), END_INIT, envoyer_all_to_all(), Process::exit(), finl, Process::Journal(), min_buf_size_, Process::mp_sum(), Process::nproc(), TRUSTArray< _TYPE_ >::ordonne_array(), recv_buf_sizes_, recv_procs_, TRUSTArray< _TYPE_ >::resize_array(), send_buf_sizes_, send_procs_, TRUSTArray< _TYPE_ >::size_array(), sorted_, and status_.
Referenced by echange_espace_virtuel_().
exchange()
void Schema_Comm_Vecteurs::exchange ()
< Pour toute a l'heure adresse de base des buffers de reception
Definition at line 199 of file Schema_Comm_Vecteurs.cpp.
{
  assert(status_ == BEGIN_COMM);
// Verifie que tous les buffers sont pleins
  assert(check_buffers_full());
// Echange les donnees
  const int nsend = send_procs_.size_array();
  const int nrecv = recv_procs_.size_array();
// On utilise le tableau sdata_.buf_pointers_ pour stocker les adresses
// des buffers a donner a Comm_Group::send_recv_start()
// (dimensionne a 2*nproc() donc suffisant)
  assert(nsend + nrecv <= sdata_.buf_pointers_size_);
  char ** send_bufs = sdata_.buf_pointers_;
  char ** recv_bufs = sdata_.buf_pointers_ + nsend;
  char * ptr = sdata_.buffer_base_;
  int i;
  for (i = 0; i < nsend; i++)
    {
      send_bufs[i] = ptr;
      ptr += send_buf_sizes_[i];
    }
  char * recv_ptr_base = ptr; //!< Pour toute a l'heure adresse de base des buffers de reception
  for (i = 0; i < nrecv; i++)
    {
      recv_bufs[i] = ptr;
      ptr += recv_buf_sizes_[i];
    }
  const Comm_Group& group = PE_Groups::current_group();
// On devrait pouvoir mettre un int64 comme type ici car
// les buffers sont de alignes sur 8 octets.
  group.send_recv_start(send_procs_, send_buf_sizes_, send_bufs,
                        recv_procs_, recv_buf_sizes_, recv_bufs,
                        Comm_Group::INT);
  group.send_recv_finish();
// Fait pointer les buffers sur les donnees recues
  ptr = recv_ptr_base;
  for (i = 0; i < nrecv; i++)
    {
      const int pe = recv_procs_[i];
      sdata_.buf_pointers_[pe] = ptr;
      ptr += recv_buf_sizes_[i];
    }
  status_ = EXCHANGED;
}
References BEGIN_COMM, Schema_Comm_Vecteurs_Static_Data::buf_pointers_, Schema_Comm_Vecteurs_Static_Data::buf_pointers_size_, Schema_Comm_Vecteurs_Static_Data::buffer_base_, check_buffers_full(), PE_Groups::current_group(), EXCHANGED, Comm_Group::INT, recv_buf_sizes_, recv_procs_, sdata_, send_buf_sizes_, send_procs_, Comm_Group::send_recv_finish(), Comm_Group::send_recv_start(), TRUSTArray< _TYPE_ >::size_array(), and status_.
Referenced by echange_espace_virtuel_().
get_next_area_template() [1/3]
template<typename _TYPE_ > TRUSTArray< _TYPE_ > & Schema_Comm_Vecteurs::get_next_area_template (int pe, int array_size) inline
Referenced by mincol1_to_vect_items(), vect_blocs_generic(), and vect_items_generic().
get_next_area_template() [2/3]
template<> ArrOfInt & Schema_Comm_Vecteurs::get_next_area_template (int pe, int size) inline
renvoie un tableau contenant les "size" valeurs suivantes
recues du processeur pe lors de la communication en cours.
Attention:
Le tableau renvoye est une reference a un tableau interne qui n'est valide que
jusqu'au prochain appel a une methode get_next_xxx.
Definition at line 171 of file Schema_Comm_Vecteurs.h.
{
  ALIGN_SIZE(sdata_.buf_pointers_[pe], sizeof(int));
  assert(check_next_area(pe, BLOCSIZE_INT(size)));
  int *bufptr = (int *) (sdata_.buf_pointers_[pe]);
// attention a l'arithmetique de pointeurs, ajout d'une taille en octets
  sdata_.buf_pointers_[pe] += BLOCSIZE_INT(size);
  tmp_area_int_.ref_data(bufptr, size);
  return tmp_area_int_;
}
References ALIGN_SIZE, BLOCSIZE_INT, Schema_Comm_Vecteurs_Static_Data::buf_pointers_, check_next_area(), TRUSTArray< _TYPE_ >::ref_data(), sdata_, and tmp_area_int_.
get_next_area_template() [3/3]
template<> ArrOfDouble & Schema_Comm_Vecteurs::get_next_area_template (int pe, int size) inline
Definition at line 183 of file Schema_Comm_Vecteurs.h.
{
  ALIGN_SIZE(sdata_.buf_pointers_[pe], sizeof(double));
  assert(check_next_area(pe, BLOCSIZE_DOUBLE(size)));
  double *bufptr = (double *) (sdata_.buf_pointers_[pe]);
// attention a l'arithmetique de pointeurs, ajout d'une taille en octets
  sdata_.buf_pointers_[pe] += BLOCSIZE_DOUBLE(size);
  tmp_area_double_.ref_data(bufptr, size);
  return tmp_area_double_;
}
References ALIGN_SIZE, BLOCSIZE_DOUBLE, Schema_Comm_Vecteurs_Static_Data::buf_pointers_, check_next_area(), TRUSTArray< _TYPE_ >::ref_data(), sdata_, and tmp_area_double_.
Member Data Documentation
buffer_locked_
int Schema_Comm_Vecteurs::buffer_locked_ static protected
Definition at line 89 of file Schema_Comm_Vecteurs.h.
Referenced by begin_comm(), and end_comm().
min_buf_size_
int Schema_Comm_Vecteurs::min_buf_size_ protected
Definition at line 83 of file Schema_Comm_Vecteurs.h.
Referenced by begin_comm(), and end_init().
recv_buf_sizes_
ArrOfInt Schema_Comm_Vecteurs::recv_buf_sizes_ protected
Definition at line 76 of file Schema_Comm_Vecteurs.h.
Referenced by add_recv_area_template(), begin_init(), check_buffers_full(), check_next_area(), end_init(), exchange(), and Schema_Comm_Vecteurs().
recv_procs_
ArrOfInt Schema_Comm_Vecteurs::recv_procs_ protected
Definition at line 79 of file Schema_Comm_Vecteurs.h.
Referenced by add_recv_area_template(), begin_init(), check_buffers_full(), check_next_area(), end_init(), exchange(), and Schema_Comm_Vecteurs().
sdata_
Schema_Comm_Vecteurs_Static_Data Schema_Comm_Vecteurs::sdata_ static protected
Definition at line 94 of file Schema_Comm_Vecteurs.h.
Referenced by begin_comm(), check_buffers_full(), check_next_area(), exchange(), and get_next_area_template().
send_buf_sizes_
ArrOfInt Schema_Comm_Vecteurs::send_buf_sizes_ protected
Definition at line 75 of file Schema_Comm_Vecteurs.h.
Referenced by add_send_area_template(), begin_comm(), begin_init(), check_buffers_full(), check_next_area(), end_init(), exchange(), and Schema_Comm_Vecteurs().
send_procs_
ArrOfInt Schema_Comm_Vecteurs::send_procs_ protected
Definition at line 78 of file Schema_Comm_Vecteurs.h.
Referenced by add_send_area_template(), begin_comm(), begin_init(), check_buffers_full(), check_next_area(), end_init(), exchange(), and Schema_Comm_Vecteurs().
sorted_
int Schema_Comm_Vecteurs::sorted_ protected
Definition at line 81 of file Schema_Comm_Vecteurs.h.
Referenced by add(), begin_init(), and end_init().
status_
Status Schema_Comm_Vecteurs::status_ protected
Definition at line 86 of file Schema_Comm_Vecteurs.h.
Referenced by add(), begin_comm(), begin_init(), check_buffers_full(), check_next_area(), end_comm(), end_init(), exchange(), Schema_Comm_Vecteurs(), and ~Schema_Comm_Vecteurs().
tmp_area_double_
ArrOfDouble Schema_Comm_Vecteurs::tmp_area_double_ static protected
Definition at line 91 of file Schema_Comm_Vecteurs.h.
Referenced by get_next_area_template().
tmp_area_int_
ArrOfInt Schema_Comm_Vecteurs::tmp_area_int_ static protected
Definition at line 92 of file Schema_Comm_Vecteurs.h.
Referenced by get_next_area_template().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Schema_Comm_Vecteurs.h
src/Kernel/Utilitaires/Schema_Comm_Vecteurs.cpp