TRUST: Process Class Reference
Process Class Reference
Classe de base de TRUST (notamment Objet_U).
Elle fournit quelques services de base
accessibles de partout dans le code (ces services etaient historiquement
des methodes non statiques, depuis que tous ces services sont statiques,
cette classe n'a plus vraiment d'autre fonction que de ranger ces methodes
quelque part)
#include <Process.h>
Public Member Functions
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int &ranks, const Nom &filename)
Static Public Attributes
static int exception_sur_exit = 0
static int multiple_files = 5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Detailed Description
Classe de base de TRUST (notamment Objet_U).
Elle fournit quelques services de base
accessibles de partout dans le code (ces services etaient historiquement
des methodes non statiques, depuis que tous ces services sont statiques,
cette classe n'a plus vraiment d'autre fonction que de ranger ces methodes
quelque part)
Definition at line 47 of file Process.h.
Constructor & Destructor Documentation
Process::Process ()
Constructeur par defaut.
Definition at line 103 of file Process.cpp.
{
}
Process::~Process () [virtual]
Destructeur
Ne fait rien.
Definition at line 147 of file Process.cpp.
{
}
Member Function Documentation
void Process::abort () [static]
Routine de sortie de Trio-U sur une erreur abort()
Definition at line 329 of file Process.cpp.
References exit().
Referenced by Champ_Fonc_Face_PolyMAC::affecter_(), Champs_compris::ajoute_champ(), Source_PDF_base::ajouter_(), Matrice_Dense::ajouter_multTab_(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1(), Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_PolyMAC::assembler_rho_variable(), Terme_Boussinesq_base::associer_pb(), Source_PDF_base::associer_pb(), Source_PDF_base::associer_zones(), build_medfield(), Champ_Face_CoviMAC::calcul_S_barre(), Champ_Face_PolyMAC::calcul_S_barre_sans_contrib_paroi(), Champ_Face_CoviMAC::calcul_S_barre_sans_contrib_paroi(), Point_EF::calcul_vc(), Point_EF::calcul_xg(), Simple::calculer_correction_en_vitesse(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_Elem::calculer_flux_bord(), Loi_Etat_rhoT_GR_QC::calculer_H(), Source_PDF_base::calculer_vitesse_imposee_elem_fluid(), Source_PDF_base::calculer_vitesse_imposee_hybrid(), Source_PDF_base::calculer_vitesse_imposee_mean_grad(), Champ_Generique_Transformation::completer(), Source_PDF_base::compute_coeff_elem(), Source_PDF_base::compute_coeff_matrice_pression(), Polyedre::compute_virtual_index(), Source_PDF_base::compute_vitesse_imposee_projete(), Point::contient(), Source_PDF_base::contribuer_a_avec(), Op_Diff_PolyMAC_Face::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_au_second_membre(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_au_second_membre(), Source_PDF_base::correct_incr_pressure(), Source_PDF_base::correct_pressure(), Source_PDF_base::correct_vitesse(), Source_PDF_EF::correct_vitesse(), Navier_Stokes_std::corriger_derivee_impl(), Loi_Etat_GR_base::De_DP(), Loi_Etat_base::De_DP(), Loi_Etat_GR_base::De_DT(), Loi_Etat_base::De_DT(), Source_PDF_base::diag_coeff_elem(), Zone_PolyMAC::dist_face_elem0_period(), Zone_CoviMAC::dist_face_elem0_period(), Zone_PolyMAC::dist_face_elem1_period(), Zone_CoviMAC::dist_face_elem1_period(), Loi_Etat_base::Drho_DP(), Loi_Etat_base::Drho_DT(), exit(), Matrice_Morse::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Zone_CoviMAC::harmonic_points(), Zone_Cl_CoviMAC::imposer_cond_lim(), Source_PDF_base::impr(), Zone_Cl_PolyMAC::initialiser(), Zone_Cl_EF::initialiser(), Zone_Cl_CoviMAC::initialiser(), Champ_Face_CoviMAC::interp_gve(), Matrice_Dense::inverse(), Loi_Etat_rhoT_GP_QC::inverser_Pth(), Loi_Etat_GR_base::inverser_Pth(), Loi_Etat_Binaire_GP_base::inverser_Pth(), Rotationnel_Champ_P1_EF::me_calculer(), QDM_Multiphase::mettre_a_jour(), Champ_Fonc_Tabule_P0_PolyMAC::mettre_a_jour(), Champ_Fonc_Tabule_P0_CoviMAC::mettre_a_jour(), Schema_Temps_base::mettre_a_jour_dt(), Traitement_particulier_NS_THI_new::msg_erreur_maillage(), Traitement_particulier_NS_THI::msg_erreur_maillage(), Source_PDF_base::multiply_coeff_volume(), Point_EF::normale(), ptrParam::operator=(), Sortie_Fichier_base::ouvrir(), Operateur_base::ouvrir_fichier(), ptrParam::ptrParam(), Matrice_Dense::read_from_file(), Navier_Stokes_std::readOn(), Loi_Etat_rhoT_GR_QC::readOn(), Loi_Etat_Mono_GP_base::readOn(), Loi_Etat::readOn(), Solveur_Lineaire_Std::readOn(), Partitionneur_Union::readOn(), Sutherland::readOn(), Op_Diff_PolyMAC_base::remplir_nu_ef(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Fluide_Quasi_Compressible::Resoudre_EDO_PT(), Source_PDF_base::rotate_imposed_velocity(), Echange_externe_impose_H::T_ext(), Option_VDF::test_mot(), Op_Diff_CoviMAC_base::update_nu_invh(), Neumann_sortie_libre_Temp_H::val_ext(), Temperature_imposee_paroi_H::val_imp(), and Entree_fluide_temperature_imposee_H::val_imp().
{
#ifdef NDEBUG
// En optimise on sort proprement.
  exit();
#else
// En debug, on sort brutal pour avoir des infos avec le debugger ?
  ::abort(); //Seul ::abort() utilise dans le code
#endif
}
void Process::barrier () [static]
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
Definition at line 127 of file Process.cpp.
References Comm_Group::barrier(), and PE_Groups::current_group().
Referenced by Probleme_base::allocation(), assert_espace_virtuel_vect(), assert_parallel(), Loi_Fermeture_base::associer_pb_base(), Calcul_integrale_locale::Calcul_integrale_locale(), Reordonner_faces_periodiques::check_faces_periodiques(), check_frontiere(), Schema_Comm::check_send_recv_pe_list(), EcrFicPartage::close(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Equation_base::ecrire_fichier_xyz(), Schema_Comm_Vecteurs::end_init(), estimate_allreduce(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), Zone_PolyMAC::init_m1_3d(), Champ_front_recyclage::initialiser(), System::interpreter(), Execute_parallel::interpreter(), Moyenne_volumique::interpreter(), latatoother::interpreter(), Scatter::interpreter(), MaillerParallel::interpreter(), Ecrire_Fichier::interpreter_(), Corriger_frontiere_periodique::interpreter_(), ScatterMED::lire_domaine(), Scatter::lire_domaine(), lire_special(), Format_Post_Lata::modify_file_basename(), EcrFicPartage::ouvrir(), Objet_a_lire::read(), Champ_Don_Face_lu::readOn(), Moyenne_volumique::readOn(), and Moyenne_volumique::traiter_champs().
{
  PE_Groups::current_group().barrier(0);
}
void Process::exit (int exit_code = -1) [static]
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
Definition at line 223 of file Process.cpp.
References message().
Referenced by abort(), Int_ptr_trav::add(), Double_ptr_trav::add(), Memoire::add(), liste::add(), BlocData::add_bloc(), liste::add_deplace(), MD_Vector_composite::add_part(), Debog_Pb::add_renum_item(), Parser::addFunc(), Parser::addVar(), Champ_Face::affecter(), Champ_Inc_base::affecter_(), Champ_Don_base::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Champ_Uniforme::affecter_(), Champ_Front_Fonction::affecter_(), Champ_Fonc_Fonction_txyz_Morceaux::affecter_(), Champ_Don_base::affecter_compo(), Champ_base::affecter_erreur(), PDF_model::affecter_vitesse_imposee(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Dift_VDF_base::ajouter(), Op_Diff_VDF_var_Face_Axi::ajouter(), Op_Diff_VDF_Face_Axi::ajouter(), Op_Diff_VDF_base::ajouter(), Op_Rot_VEFP1B::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Curl_VEFP1B::ajouter(), Interprete_bloc::ajouter(), Operateur_Grad_base::ajouter(), Domaine::ajouter(), Source_base::ajouter(), Probleme_Couple::ajouter(), Operateur_base::ajouter(), Op_Diff_EF::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Source_PDF_EF::ajouter_(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion(), Solveur_Masse_base::ajouter_blocs(), Op_Diff_VDF_Face_Axi::ajouter_bord(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_vectoriel(), Op_Conv_EF_VEF_P1NC::ajouter_contribution(), Op_Dift_VDF_var_Face_Axi::ajouter_contribution(), Op_Dift_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_var_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution(), Op_Diff_VDF_Face_Axi::ajouter_contribution_bord(), Op_Dift_Stab_VEF_Face::ajouter_contribution_cl(), Operateur_base::ajouter_flux(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), ajouter_joint(), Matrice_Petsc::ajouter_multTab_(), Matrice_Morse_Diag::ajouter_multTab_(), Matrice_Bloc_Sym::ajouter_multTab_(), Matrice_Bloc::ajouter_multTab_(), Matrice_Petsc::ajouter_multvect_(), Matrice_Petsc::ajouter_multvectT_(), Matrice_Morse_Sym::ajouter_multvectT_(), Matrice_Morse_Diag::ajouter_multvectT_(), Matrice_Bloc_Sym::ajouter_multvectT_(), Synonyme_info::ajouter_synonyme(), Type_info::ajouter_type(), Probleme_base::allocation(), Masse_VEF_P1NC::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Solveur_Masse_EF::appliquer_impl(), SETS::assembler(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Equation_base::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_base::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Assembleur_P_VDF::assembler_QC(), Assembleur_base::assembler_QC(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_base::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), Matrice_Bloc::assert_check_block_matrix_structure(), Matrice_Morse::assert_check_morse_matrix_structure(), Matrice_Morse::assert_check_sorted_morse_matrix_structure(), Matrice_Morse_Sym::assert_check_sorted_symmetric_morse_matrix_structure(), Matrice_Bloc_Sym::assert_check_symmetric_block_matrix_structure(), Matrice_Morse_Sym::assert_check_symmetric_morse_matrix_structure(), assert_espace_virtuel_vect(), assert_parallel(), Op_Conv_kschemas_VEF::associer(), Op_Conv_Quick_VDF_Face::associer(), Op_Conv_Quick_VDF_Elem::associer(), Op_Conv_centre4_VDF_Face::associer(), Op_Conv_centre4_VDF_Elem::associer(), Eval_Diff_VDF_var_aniso::associer(), Op_Diff_VEFP1NCP1B_Face::associer(), Op_Correlation::associer(), Champ_front_recyclage::associer_champ_evaluateur(), Support_Champ_Masse_Volumique::associer_champ_masse_volumique(), Terme_Source_Acceleration_VEF_Face::associer_champ_rho(), Terme_Source_Acceleration_VDF_Face::associer_champ_rho(), Source_base::associer_champ_rho(), Interprete_geometrique_base::associer_domaine(), Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), Milieu_base::associer_equation(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Milieu_base::associer_gravite(), Pb_Thermohydraulique_Concentration::associer_milieu_base(), Pb_Thermohydraulique::associer_milieu_base(), Pb_Hydraulique_Concentration::associer_milieu_base(), Pb_Hydraulique::associer_milieu_base(), Navier_Stokes_std::associer_milieu_base(), Convection_Diffusion_Temperature::associer_milieu_base(), Convection_Diffusion_Concentration::associer_milieu_base(), Pb_WC_base::associer_milieu_base(), Pb_QC_base::associer_milieu_base(), Op_Correlation::associer_op_stat(), Terme_Source_Th_TdivU_VEF_Face::associer_pb(), Terme_Source_Qdm_lambdaup_VEF_Face::associer_pb(), Perte_Charge_VEF_Face::associer_pb(), Terme_Source_inc_VDF_Face::associer_pb(), Terme_Source_inc_th_VDF_Face::associer_pb(), Terme_Source_Coriolis_VDF_Face::associer_pb(), Source_Echange_Th_VDF::associer_pb(), Perte_Charge_VDF_Face::associer_pb(), Terme_Boussinesq_base::associer_pb(), Source_QC_QDM_Gen::associer_pb(), Perte_Charge_PolyMAC_Face::associer_pb(), Perte_Charge_CoviMAC_Face::associer_pb(), Loi_Fermeture_base::associer_pb_base(), Sonde_Int::associer_post(), Sonde::associer_post(), Pb_Dilatable_base::associer_sch_tps_base(), Probleme_base::associer_sch_tps_base(), Operateur_base::associer_zone_cl_dis(), Champ_Ostwald::associer_zone_dis_base(), Champ_base::associer_zone_dis_base(), Schema_Implicite_Multi_TimeStep_base::authorized_equation(), Schema_Explicite_Multi_TimeStep_base::authorized_equation(), Op_Diff_VEF_Face_Penalise::autre_face(), Champ_front_var_instationnaire::avancer(), Champ_front_instationnaire_base::avancer(), Champ_front_base::avancer(), bad_ref_cast(), Comm_Group_MPI::barrier(), Schema_Comm_Vecteurs::begin_comm(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), build_cell_refinement_pattern(), build_edges_pattern(), Octree_Double::build_elements(), build_face_refinement_pattern(), build_faces_pattern(), build_frontier(), build_medfield(), Octree_Double::build_nodes(), Matrice_Base::build_stencil(), build_triofield(), vect_impl::build_vect_impl(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Calcul_integrale_locale::Calcul_integrale_locale(), calcul_longueur_filtre(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Reaction::calcul_proportion_implicite(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_P1NC::calcul_y_plus(), Eval_Diff_VDF_Face< Eval_Dift_VDF_var_Face >::calculer_arete_coin_fluide(), Eval_VDF_Face::calculer_arete_coin_fluide(), Zone_EF::calculer_Bij(), Aretes::calculer_centre_de_gravite(), Echange_contact_Correlation_VEF::calculer_CL(), Echange_contact_Correlation_VDF::calculer_CL(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), calculer_coef_som(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Op_Conv_EF_VEF_P1NC_Stab::calculer_coefficients_operateur_centre(), NSCBC::calculer_contribution_valeurs_propres(), Moyenne_volumique::calculer_convolution_champ_face(), Op_Conv_EF_VEF_P1NC_Stab::calculer_data_pour_dirichlet(), Champ_Face::calculer_dercov_axi(), Operateur_base::calculer_dt_local(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_aretes(), Traitement_particulier_NS_EC::calculer_Ec(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant_elements(), T_It_VDF_Elem< _TYPE_ >::calculer_flux_bord(), Iterateur_VDF_base::calculer_flux_bord(), T_It_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Iterateur_PolyMAC_base::calculer_flux_bord(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Op_Conv_EF_VEF_P1NC_Stab::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_aretes(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Echange_contact_VDF::calculer_h_autre_pb(), Champ_P1NC::calculer_integrale_volumique(), Assembleur_P_VEF::calculer_inv_volume(), Loi_Etat_GP_base::calculer_lambda(), calculer_liste_complete_items_joint(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_base::calculer_masse_volumique(), Loi_Etat_GP_base::calculer_masse_volumique(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Loi_Etat_Binaire_GP_base::calculer_mu(), Loi_Etat_base::calculer_mu(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Elem_geom_base::calculer_normales(), Faces_VDF::calculer_orientation(), Equation_base::calculer_pas_de_temps_locaux(), Operateur_base::calculer_pour_post(), MorEqn::calculer_pour_post(), Op_Conv_EF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Faces::calculer_surfaces(), Eval_Puiss_Th_VEF_Face::calculer_terme_source_non_standard(), Eval_Forchheimer_VEF_Face::calculer_terme_source_non_standard(), Eval_Dirac_VEF_Face::calculer_terme_source_non_standard(), Eval_Darcy_VEF_Face::calculer_terme_source_non_standard(), Eval_Puiss_Th_VEF_Face::calculer_terme_source_standard(), Eval_Forchheimer_VEF_Face::calculer_terme_source_standard(), Eval_Darcy_VEF_Face::calculer_terme_source_standard(), Eval_Puiss_Th_QC_EF::calculer_terme_source_standard(), Eval_Puiss_Th_EF::calculer_terme_source_standard(), Op_Ecart_type::calculer_valeurs(), Champ_base::calculer_valeurs_som_post(), Zone::calculer_volumes(), Rectangle::calculer_volumes(), Champ_Face_get_val_imp_face_bord(), Champ_Generique_erreur::Champ_Generique_erreur(), Terme_Boussinesq_base::check(), EcrFicPartageMPIIO::check(), check(), check_boundary_name(), Schema_Comm_Vecteurs::check_buffers_full(), Refine_Mesh::check_cell_type(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_dimension(), Rectify_Mesh::check_dimension(), check_domaine(), Faces_builder::check_erreur_faces(), Reordonner_faces_periodiques::check_faces_periodiques(), check_frontiere(), check_ICEM_ascii_file(), check_ICEM_binary_file(), check_internal_diagonal(), check_internal_diagonal_for_tetrahedron(), MorEqn::check_multiphase_compatibility(), Refine_Mesh::check_nb_zones(), Rectify_Mesh::check_nb_zones(), check_not_defined(), O_U_Ptr::check_O_U_Ptr_type(), check_positive_volumes(), check_positive_volumes_for_tetrahedron(), check_positive_volumes_for_triangle(), Schema_Comm::check_send_recv_pe_list(), Fluide_Weakly_Compressible::checkTraitementPth(), Fluide_Quasi_Compressible::checkTraitementPth(), Scatter::Chercher_Correspondance(), Partitionneur_Tranche::chercher_direction_perio(), Zone::chercher_elements(), chercher_elems_voisins_faces(), Solv_Cholesky::Cholesky(), choose_internal_diagonal(), choose_internal_diagonal_for_tetrahedron(), EcrFicPartage::close(), Matrice_Diagonale::coeff(), coeff_opt(), Op_Diff_VEF_Face_Penalise::coefficient_penalisation(), Eval_Amont_VDF_Face::coeffs_arete_coin_fluide(), Eval_Diff_VDF_Elem< DERIVED_T >::coeffs_face(), Eval_centre4_VDF_Elem::coeffs_face(), Eval_Amont_VDF_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_Amont_VDF_Elem::coeffs_face_bloc_vitesse(), Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse(), Comm_Group::Comm_Group(), Memoire::compacte(), Matrice_Morse::compacte(), Cond_lim_utilisateur_base::compatible_avec_eqn(), paroi_contact_fictif::complement(), paroi_contact::complement(), Zone_Cl_VEF::completer(), Terme_Source_Rappel_T_VEF_Face::completer(), Terme_Source_Decroissance_Radioactive_VEF_Face::completer(), Perte_Charge_VEF::completer(), Op_Dift_VEF_base::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Champ_front_contact_VEF::completer(), Zone_Cl_VDF::completer(), Terme_Source_Canal_perio::completer(), Fluide_Weakly_Compressible::completer(), EDO_Pression_th_VEF::completer(), Fluide_Quasi_Compressible::completer(), Reaction::completer(), Chimie::completer(), Zone_Cl_PolyMAC::completer(), Masse_PolyMAC_Face::completer(), Masse_PolyMAC_Elem::completer(), Terme_Source_Decroissance_Radioactive_P0_PolyMAC::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Periodique::completer(), Faces::completer(), Source_Generique_base::completer(), Equation_base::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Transformation::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Generique_Interpolation::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Correlation::completer(), Champ_front_calc_interne::completer(), Champ_front_calc::completer(), Zone_Cl_EF::completer(), Zone_Cl_CoviMAC::completer(), Terme_Source_Decroissance_Radioactive_P0_CoviMAC::completer(), Op_Grad_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Face::completer(), Op_Diff_CoviMAC_Elem::completer(), Op_Diff_CoviMAC_base::completer(), Op_Conv_EF_Stab_CoviMAC_Face::completer(), Champ_Generique_Statistiques_base::completer_post_statistiques(), composante(), Champ_Generique_base::composante(), Pb_MED::comprend_champ(), Zones::comprimer(), Joints::comprimer(), Statistiques::compute_avg_min_max_var_per_step(), compute_cell_qualities(), MD_Vector_tools::compute_sequential_items_index(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_fonc_gradient::condition_limite(), Zone_Cl_dis_base::condition_limite_de_la_frontiere(), Champ_front_contact_VEF::connectivity_failed(), ConstDoubleTab_parts::ConstDoubleTab_parts(), ConstIntTab_parts::ConstIntTab_parts(), Convection_Diffusion_Concentration::constituant(), Octree::construire(), Scatter::construire_correspondance_items_par_coordonnees(), Scatter::construire_espace_virtuel_traduction(), Domain_Graph::construire_graph_elem_elem(), construire_nom_fichier_sous_domaine(), Zone_VEF_PreP1b::construire_ok_arete(), Partitionneur_Union::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Metis::construire_partition(), Partitionneur_Fichier_Decoupage::construire_partition(), construit_connectivite_sommet(), Champ_Generique_Predefini::construit_expression(), Prisme::contient(), Polygone::contient(), contient_Tetra(), Op_Conv_EF_VEF_P1NC::contribue_au_second_membre(), Op_Dift_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Dift_VDF_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_var_Face_Axi::contribue_au_second_membre(), Op_Diff_VDF_Face_Axi::contribue_au_second_membre(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Op_Dift_VDF_base::contribuer_a_avec(), Op_Diff_VDF_base::contribuer_a_avec(), Operateur_Grad_base::contribuer_a_avec(), Operateur_base::contribuer_a_avec(), Op_Dift_VDF_base::contribuer_au_second_membre(), Op_Diff_VDF_base::contribuer_au_second_membre(), Source_base::contribuer_au_second_membre(), Operateur_base::contribuer_au_second_membre(), convert_to(), convkschemas(), coord_barycentrique(), coord_barycentrique3D(), coord_barycentrique_P1(), coord_barycentrique_P1_hexaedre(), coord_barycentrique_P1_rectangle(), coord_barycentrique_P1_tetraedre(), coord_barycentrique_P1_triangle(), corriger(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Schema_Temps_base::corriger_dt_calcule(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), corriger_type(), Assembleur_base::corriger_vitesses(), Discret_Thyd::courant_maille(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Param::create_or_get_objet_a_lire(), Solv_Petsc::create_solver(), vect_impl::cree_une_instance(), Champ_front_contact_VEF::creer(), Champ_Fonc_MED::creer(), Champ_front_calc::creer(), Zone::creer_aretes(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_moreqn(), Postraitement::creer_champ_post_stat(), VEF_discretisation::creer_champ_vorticite(), Discret_Thyd::creer_champ_vorticite(), PolyMAC_discretisation::creer_champ_vorticite(), EF_discretisation::creer_champ_vorticite(), CoviMAC_discretisation::creer_champ_vorticite(), Fluide_Dilatable_base::creer_champs_non_lus(), Zone_dis_base::creer_elements_fictifs(), Faces_builder::creer_faces_reeles(), Quadri_VEF::creer_facette_normales(), MD_Vector_tools::creer_md_vect_renum(), creer_md_vect_renum(), Quadri_VEF::creer_normales_facettes_Cl(), Hexa_VEF::creer_normales_facettes_Cl(), Tetraedriser_homogene_fin::creer_sommet(), creer_sommet(), MD_Vector_tools::creer_tableau_distribue(), creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Champ_Fonc_base::creer_tableau_distribue(), Domaine::creer_tableau_elements(), crit_err_hdlr(), Discret_Thyd::critere_Q(), Debog_Pb::Debog_Pb(), DoubleTab::decomp_LU(), Tetraedriser_homogene_fin::decoupe(), Tetraedriser_homogene_compact::decoupe(), DecoupeBord::Decouper(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Op_Div_VEFP1B_Elem::degres_liberte(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco_eq_base(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Zone_PolyMAC::detecter_faces_non_planes(), Zone_CoviMAC::detecter_faces_non_planes(), Matrice_Morse::diagmulmat(), Op_Diff_VEFP1NCP1B_Face::dimensionner(), vect_impl::dimensionner(), Operateur_Grad_base::dimensionner(), Matrice_Bloc_Sym::dimensionner(), IntListsListe::dimensionner(), IntLists::dimensionner(), DoubleLists::dimensionner(), Operateur_base::dimensionner(), Op_EF_base::dimensionner(), QDM_Multiphase::dimensionner_blocs(), vect_impl::dimensionner_force(), OctreeLoc::direction(), Periodique::direction_periodicite(), Probleme_base::discretisation(), Equation_base::discretisation(), Zone_VEF::discretiser(), Zone_VDF::discretiser(), Pb_Multiphase::discretiser(), Zone_PolyMAC::discretiser(), Domaine_dis::discretiser(), Zone_EF::discretiser(), Zone_CoviMAC::discretiser(), VEF_discretisation::discretiser_champ(), VEFPreP1B::discretiser_champ(), Discretisation_base::discretiser_champ(), EF_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ_fonc_don(), VDF_discretisation::discretiser_champ_fonc_don(), PolyMAC_discretisation::discretiser_champ_fonc_don(), VEFPreP1B::discretiser_champ_fonc_don(), EF_discretisation::discretiser_champ_fonc_don(), CoviMAC_discretisation::discretiser_champ_fonc_don(), Champ_Generique_Interpolation::discretiser_domaine(), Discretisation_base::discretiser_variables(), Discretisation_base::discretiser_Zone_Cl_dis(), diviser_par_rho_si_dilatable(), DomaineCutter::DomaineCutter(), DoubleLists::DoubleLists(), DoubleTab_parts::DoubleTab_parts(), Statistiques::dump(), T_It_Sou_VDF_Face< _TYPE_ >::duplique(), T_It_Sou_VDF_Elem< _TYPE_ >::duplique(), T_It_VDF_Face< _TYPE_ >::duplique(), T_It_VDF_Elem< _TYPE_ >::duplique(), T_It_PolyMAC_Elem< _TYPE_ >::duplique(), Echange_contact_Correlation_VEF_reprendre(), echange_espace_virtuel1_(), Schema_Comm::echange_messages(), Postraiter_domaine::ecrire(), Decouper::ecrire(), Format_Post_Lata_V1::ecrire_champ_lata_V1(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lata::ecrire_entete_lata(), ecrire_fichier_decoupage(), Equation_base::ecrire_fichier_xyz(), Format_Post_Lata::ecrire_item_int(), DomaineCutter::ecrire_zones(), EcritureLectureSpecial::ecriture_special(), ecriture_special_part2(), EFichier::EFichier(), EFichierBin::EFichierBin(), SETS::eliminer(), Traitement_particulier_NS_THI_new::en_cours_de_resolution(), Schema_Comm_Vecteurs::end_init(), ensure_positive_volumes(), PE_Groups::enter_group(), Entree_Fichier_base::Entree_Fichier_base(), envoyer_broadcast_(), Assembleur_P_VEF::equation(), Champ_front_contact_VEF::equation(), Pb_Multiphase::equation(), Modele_turbulence_scal_base::equation(), Mod_turb_hyd_base::equation(), Pb_Thermohydraulique_Concentration::equation(), Pb_Thermohydraulique::equation(), Pb_Hydraulique_Concentration::equation(), Pb_Hydraulique::equation(), Assembleur_P_VEFPreP1B::equation(), Pb_MED::equation(), Probleme_base::equation(), MorEqn::equation(), List_Equations_Scalaires_Passifs_Especes::equation(), Champ_front_calc::equation(), Assembleur_P_EF::equation(), Pb_Dilatable_Proto::equation_impl(), Cond_lim_base::err_pas_compatible(), erreur(), erreur_chfront(), erreur_non_convergence(), Debog_Pb::error_function(), Entree::error_handle_(), Sqrt::eval(), Ln::eval(), Parser::eval(), Moyenne_volumique::eval_filtre(), Parser::evalFunc(), Parser::evalOp(), exit(), PE_Groups::exit_group(), TroisDto2D::extraire_2D(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder_en20::extruder(), Extruder::extruder(), face_bord_amont2(), Zone::face_interne_conjuguee(), Zone_VF_inst::face_normales(), Triangle::face_sommet0(), Tetraedre::face_sommet0(), Segment::face_sommet0(), Rectangle::face_sommet0(), Quadrangle_VEF::face_sommet0(), Prisme::face_sommet0(), Point::face_sommet0(), Hexaedre_VEF::face_sommet0(), Hexaedre::face_sommet0(), Triangle::face_sommet1(), Tetraedre::face_sommet1(), Rectangle::face_sommet1(), Quadrangle_VEF::face_sommet1(), Prisme::face_sommet1(), Hexaedre_VEF::face_sommet1(), Hexaedre::face_sommet1(), Triangle::face_sommet2(), Tetraedre::face_sommet2(), Rectangle::face_sommet2(), Quadrangle_VEF::face_sommet2(), Prisme::face_sommet2(), Hexaedre_VEF::face_sommet2(), Hexaedre::face_sommet2(), Tetraedre::face_sommet3(), Rectangle::face_sommet3(), Quadrangle_VEF::face_sommet3(), Hexaedre_VEF::face_sommet3(), Hexaedre::face_sommet3(), Hexaedre_VEF::face_sommet4(), Hexaedre::face_sommet4(), Hexaedre_VEF::face_sommet5(), Hexaedre::face_sommet5(), Zone_dis_base::face_sommets(), Zone_dis_base::face_voisins(), Solv_Cholesky::Fact_Cholesky(), ILU::factoriser(), Sch_CN_iteratif::faire_un_pas_de_temps_eqn_base(), Echange_contact_CoviMAC::fgrad(), Fichier_Lata::Fichier_Lata(), FichierHDF::FichierHDF(), FichierHDFPar::FichierHDFPar(), fill_tab_2(), fill_tab_2_new(), fill_tab_3(), Champ_P1NC_implementation::filtrer_L2(), Decouper::find_domain(), find_joint_faces(), find_matching_coordinates(), Champ_Inc_base::fixer_nb_valeurs_nodales(), Champ_Fonc_base::fixer_nb_valeurs_nodales(), Champ_base::fixer_nb_valeurs_nodales(), Masse_Multiphase::fluide(), Energie_Multiphase::fluide(), Convection_Diffusion_Temperature::fluide(), Convection_Diffusion_Fluide_Dilatable_base::fluide(), Eval_Diff_VDF_Face< Eval_Dift_VDF_var_Face >::flux_arete_coin_fluide(), Eval_VDF_Face::flux_arete_coin_fluide(), Eval_Amont_VDF_Face::flux_arete_coin_fluide(), Eval_Diff_VDF_Elem< DERIVED_T >::flux_face(), Eval_Quick_VDF_Elem::flux_face(), Eval_centre4_VDF_Elem::flux_face(), Eval_Amont_VDF_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_Diff_VDF_Elem< DERIVED_T >::flux_faces_interne(), Sortie_libre_Gradient_Pression_impose_VEF::flux_impose(), Sortie_libre_Gradient_Pression_impose::flux_impose(), Sortie_libre_Text_H_ext::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), Neumann_paroi::flux_impose(), Sortie_libre_pression_imposee_QC::flux_impose(), Neumann::flux_impose(), Champ_Q1NC_impl::fonction_forme_2D_normalise(), Champ_Q1NC_impl::fonction_forme_3D_normalise(), Champ_implementation_P1::form_function(), formule_2D(), formule_3D(), Zone::frontiere(), Lec_Diffuse_base::get(), Entree::get(), Simpler_Base::get_and_set_parametre_implicite(), Matrice_Bloc_Sym::get_bloc(), Matrice_Bloc::get_bloc(), Pb_MED::get_champ(), Probleme_base::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_Morceau_Equation::get_champ(), Champ_Generique_Interpolation::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Probleme_base::get_champ_post(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Gradient::get_champ_without_evaluation(), Champ_Generique_Divergence::get_champ_without_evaluation(), Statistiques::get_counter_id_from_index_in_comm_tracking_info(), Champ_Generique_Transformation::get_directive_pour_discr(), Champ_Generique_refChamp::get_directive_pour_discr(), Champ_Generique_Interpolation::get_directive_pour_discr(), Op_Dift_VDF_Face_base::get_eval_face(), Op_Diff_VDF_Face_base::get_eval_face(), LecFicDiffuse::get_istream(), Operateur_base::get_localisation_pour_post(), MorEqn::get_localisation_pour_post(), Discretisation_base::get_name_of_type_for(), Postraitement::get_nom_localisation(), O_U_Ptr::get_O_U_Ptr_check(), Champ_Generique_refChamp::get_property(), Champ_Generique_refChamp::get_ref_connectivity(), get_ref_coordinates_items(), Champ_Generique_Extraction::get_ref_domain(), Champ_Generique_refChamp::get_ref_zcl_dis_base(), Champ_Generique_Interpolation::get_ref_zone_dis_base(), Champ_Generique_Extraction::get_ref_zone_dis_base(), get_seq_flags(), Champ_Gen_de_Champs_Gen::get_source(), Matrice_Base::get_stencil(), Matrice_Base::get_stencil_and_coefficients(), Matrice_Nulle::get_symmetric_stencil(), Matrice_Nulle::get_symmetric_stencil_and_coefficients(), Elem_geom_base::get_tab_aretes_sommets_locaux(), Prisme::get_tab_faces_sommets_locaux(), Elem_geom_base::get_tab_faces_sommets_locaux(), Param::get_value(), Objet_a_lire::get_value(), Champ_implementation_base::get_zone_dis(), ICoCo::ProblemTrio::getStationaryMode(), gmres_local(), Debog_Pb::goto_msg(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), Discret_Thyd::grad_T(), Discret_Thyd::grad_u(), gradient_biconjugue(), Equation_base::Gradient_conjugue_diff_impl(), Milieu_base::gravite(), Discret_Thyd::h_conv(), Echange_impose_base::h_imp(), handle_error(), Champs_compris::has_champ(), histogramme_angle(), htoi(), Zone::identifie_item_unique(), Zone_Cl_VEF::imposer_cond_lim(), Zone_Cl_VDF::imposer_cond_lim(), Zone_Cl_PolyMAC::imposer_cond_lim(), Zone_Cl_EF::imposer_cond_lim(), Zone_Cl_CoviMAC::imposer_cond_lim(), Op_VEF_Face::impr(), Op_Grad_P0_to_Face::impr(), Navier_Stokes_std::impr(), Op_EF_base::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Champ_P0_VDF::imprime(), Champ_Fonc_P0_VDF::imprime(), Champ_Inc_base::imprime(), Champ_Don_base::imprime(), Equation_base::imprime_residu(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), List_Equations_Scalaires_Passifs_Especes::inconnue(), Couplage_U::indice_probleme(), Echange_contact_Correlation_VEF::init(), Postraitement::init(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Champ_P0_PolyMAC::init_cl(), Champ_Face_PolyMAC::init_cl(), Champ_P0_CoviMAC::init_fcl(), Champ_Face_CoviMAC::init_fcl(), Echange_contact_CoviMAC::init_fe_dist(), Champ_implementation_P1::init_from_file(), Comm_Group::init_group(), Comm_Group_MPI::init_group_trio(), init_journal_file(), mon_main::init_parallel(), init_petsc(), Probleme_base::init_postraitements(), Echange_contact_Correlation_VDF::init_tab_echange(), Champ_Face_CoviMAC::init_ve2(), Raccord_distant_homogene::initialise(), Echange_contact_VDF::initialiser(), Champ_Ostwald::initialiser(), Champ_front_pression_from_u::initialiser(), Echange_contact_PolyMAC::initialiser(), Champ_front_recyclage::initialiser(), DomaineCutter::initialiser(), Sonde::initialiser(), Champ_front_xyz_debit::initialiser(), Champ_front_lu::initialiser(), Ch_front_Vortex::initialiser(), Echange_contact_CoviMAC::initialiser(), Loi_Etat_Multi_GP_WC::initialiser_inco_ch(), Format_Post_Lata::initialize(), Navier_Stokes_std::initTimeStep(), Cond_lim_base::injecter_dans_champ_inc(), liste::inserer(), install_handlers(), Type_info::instance(), Champ_Inc_base::integrale_espace(), Comm_Group_MPI::internal_collective(), Phases::interpreter(), EcritureLectureSpecial::interpreter(), System::interpreter(), Lire_Fichier::interpreter(), Interprete::interpreter(), Execute_parallel::interpreter(), Moyenne_volumique::interpreter(), MergeMEDfiles::interpreter(), latatoother::interpreter(), Integrer_champ_med::interpreter(), EcrMED::interpreter(), Ecrire_Champ_MED::interpreter(), Testeur_MEDCoupling::interpreter(), Pilote_ICoCo::interpreter(), Scatter::interpreter(), Raffiner_isotrope_parallele::interpreter(), PrecisionGeom::interpreter(), MaillerParallel::interpreter(), Decouper_multi::interpreter(), Resoudre::interpreter(), Porosites_champ::interpreter(), Porosites::interpreter(), Discretiser::interpreter(), Diametre_hyd_champ::interpreter(), Associer::interpreter(), VerifierCoin::interpreter_(), Ecrire_Fichier::interpreter_(), TroisDto2D::interpreter_(), Triangulation_base::interpreter_(), SupprimeBord::interpreter_(), Rotation::interpreter_(), Reorienter_triangles::interpreter_(), Reorienter_tetraedres::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), RegroupeBord::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Raffiner_anisotrope::interpreter_(), Postraiter_domaine::interpreter_(), Polyedriser::interpreter_(), NettoieNoeuds::interpreter_(), Mailler::interpreter_(), Lire_Tgrid::interpreter_(), Extruder_en3::interpreter_(), ExtrudeBord::interpreter_(), Extraire_surface::interpreter_(), Extraire_plan::interpreter_(), Extraire_domaine::interpreter_(), Distanceparoi::interpreter_(), Dilate::interpreter_(), Decouper_Bord_coincident::interpreter_(), DecoupeBord::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Calculer_Moments::interpreter_(), Interprete_bloc::interpreter_bloc(), IntLists::IntLists(), IntListsListe::IntListsListe(), IntTab::IntTab(), IntTab_parts::IntTab_parts(), Matrice_Morse_Sym::inverse(), Matrice_Morse::inverse(), Matrice33::inverse(), inverse(), Loi_Etat_GP_WC::inverser_Pth(), is_parallel_object(), Cond_lim_utilisateur_base::is_pb_VEF(), SETS::iterer_eqn(), Solveur_Implicite_Base::iterer_eqs(), Solveur_U_P::iterer_NS(), Simpler::iterer_NS(), Piso::iterer_NS(), Joint::joint_item(), Joints::joint_PE(), Zone_Cl_dis_base::la_cl_de_la_face(), largest_angle(), Champ_Fonc_Tabule::le_champ_tabule_discretise(), LecFicDiffuse::LecFicDiffuse(), LecFicDiffuse_JDD::LecFicDiffuse_JDD(), EcritureLectureSpecial::lecture_special(), lecture_special_part2(), Type_info::les_sous_types(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Profils_VDF::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_Solide_canal::lire(), Simple::lire(), Piso::lire(), SETS::lire(), Traitement_particulier_NS_THI_new::lire(), Traitement_particulier_NS_THI::lire(), Traitement_particulier_NS_temperature::lire(), Traitement_particulier_NS_Profils::lire(), Traitement_particulier_NS_EC::lire(), Traitement_particulier_NS_chmoy_faceperio::lire(), Traitement_particulier_NS_canal::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Champ_Fonc_MED_Table_Temps::lire(), Champ_Fonc_MED::lire(), Operateur::lire(), Equation_base::lire(), Param::lire_avec_accolades_depuis(), Zone::Lire_Bords_a_imprimer(), Zone::Lire_Bords_a_imprimer_sum(), Postraitement::lire_champs_a_postraiter(), Postraitement::lire_champs_operateurs(), Postraitement::lire_champs_stat_a_postraiter(), Equation_base::lire_cl(), QDM_Multiphase::lire_cond_init(), Navier_Stokes_std::lire_cond_init(), Equation_base::lire_cond_init(), Pb_Multiphase::lire_correlations(), Terme_Source_Acceleration::lire_data(), Champ_Proto::lire_dimension(), Scatter::lire_domaine(), Terme_Source_inc_th::lire_donnees(), Terme_Source_inc::lire_donnees(), Terme_Source_Coriolis::lire_donnees(), Terme_Source_Canal_perio::lire_donnees(), Terme_Boussinesq_base::lire_donnees(), Perte_Charge_Singuliere::lire_donnees(), Perte_Charge_Reguliere::lire_donnees(), DP_Impose::lire_donnees(), Champ_Inc_base::lire_donnees(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Sondes::lire_fichier(), Champ_front_recyclage::lire_fichier_format1(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Pave::lire_front(), Champ_front_recyclage::lire_info_moyenne_imposee(), Champ_front_recyclage::lire_info_moyenne_recyclee(), Pave::lire_Longueurs(), Option_VDF::lire_motcle_non_standard(), Conduction::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Mod_turb_hyd_base::lire_motcle_non_standard(), PDF_model::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Fluide_Weakly_Compressible::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Fluide_Dilatable_base::lire_motcle_non_standard(), Reaction::lire_motcle_non_standard(), Objet_U::lire_motcle_non_standard(), Parametre_diffusion_implicite::lire_motcle_non_standard(), Remove_elem::lire_motcle_non_standard(), Postraiter_domaine::lire_motcle_non_standard(), Partitionneur_Metis::lire_motcle_non_standard(), Partitionneur_base::lire_motcle_non_standard(), Decouper_multi::lire_motcle_non_standard(), Decouper::lire_motcle_non_standard(), Schema_Temps_base::lire_motcle_non_standard(), Postraitement_base::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Milieu_base::lire_motcle_non_standard(), Format_Post_Lata::lire_motcle_non_standard(), Format_Post_base::lire_motcle_non_standard(), Equation_base::lire_motcle_non_standard(), Champ_Generique_base::lire_motcle_non_standard(), Champ_Generique_Transformation::lire_motcle_non_standard(), Champ_Generique_refChamp::lire_motcle_non_standard(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Pave::lire_Noeuds(), lire_partitionneur(), Probleme_base::lire_postraitement_interfaces(), Postraitements::lire_postraitements(), Param::lire_sans_accolade(), lire_special(), Perte_Charge_Singuliere::lire_surfaces(), Lecture_Table::lire_table(), Postraitement::lire_tableaux_a_postraiter(), IntVect::lit(), IntTab::lit(), DoubleVect::lit(), DoubleTab::lit(), Sortie::lockfile(), main_TRUST(), Motcle::map_to_int(), Zone::md_vector_elements(), MD_Vector_std::MD_Vector_std(), Champ_Ostwald::me_calculer(), med_non_installe(), MergeMEDfiles::mergeFields(), message_erreur_conc(), message_erreur_fraction_massique(), message_erreur_therm(), Terme_Source_Canal_RANS_LES_VEF_Face::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Champ_Ostwald::mettre_a_jour(), Chimie::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::mettre_a_jour(), Champ_Fonc_Q1_MED::mettre_a_jour(), Champ_Fonc_P1_MED::mettre_a_jour(), Champ_Fonc_P0_MED::mettre_a_jour(), Champ_Fonc_MED_Tabule::mettre_a_jour(), Source_base::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), Integrale_tps_Champ::mettre_a_jour_integrale(), Probleme_Couple::mettre_a_jour_modele_rayo(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Navier_Stokes_std::milieu(), Convection_Diffusion_Temperature::mise_en_place_zone_fantome(), Tri_VEF::modif_volumes_entrelaces(), Tetra_VEF::modif_volumes_entrelaces(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Discr_inst::modifier_champ_tabule(), Discretisation_base::modifier_champ_tabule(), Assembleur_P_VEFPreP1B::modifier_matrice(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Operateur_base::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Schema_Implicite_Multi_TimeStep_base::modifier_second_membre(), Schema_Implicite_Multi_TimeStep_base::modifier_second_membre_full_impl(), Assembleur_P_VEFPreP1B::modifier_solution(), Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl(), mon_construire_correspondance_items_par_coordonnees(), moy_2D_vit(), moy_3D_vit(), Champ_Fonc_P0_VDF::moyenne(), mpi_print_error(), multiplier_diviser_rho(), multiplier_par_rho_si_dilatable(), Matrice_Petsc::nb_colonnes(), Triangle::nb_faces(), Tetraedre::nb_faces(), Segment::nb_faces(), Rectangle::nb_faces(), Quadrangle_VEF::nb_faces(), Prisme::nb_faces(), Polygone::nb_faces(), Polyedre::nb_faces(), Point::nb_faces(), Hexaedre_VEF::nb_faces(), Hexaedre::nb_faces(), Zone_Cl_PolyMAC::nb_faces_sortie_libre(), Zone_Cl_EF::nb_faces_sortie_libre(), Zone_Cl_CoviMAC::nb_faces_sortie_libre(), Matrice_Petsc::nb_lignes(), Triangle::nb_som_face(), Tetraedre::nb_som_face(), Segment::nb_som_face(), Rectangle::nb_som_face(), Quadrangle_VEF::nb_som_face(), Prisme::nb_som_face(), Point::nb_som_face(), Hexaedre_VEF::nb_som_face(), Hexaedre::nb_som_face(), Champ_base::nb_valeurs_nodales(), Statistiques::new_counter(), StringTokenizer::nextToken(), Nom::Nom(), nom_fichier(), Nom::nom_me(), Champ_Generique_Morceau_Equation::nommer_source(), Champ_Gen_de_Champs_Gen::nommer_sources(), norm_2D_vit(), norm_3D_vit(), not_implemented(), Interprete_bloc::objet_global(), Interprete_bloc::objet_local(), Memoire::objet_u(), Memoire::objet_u_ptr(), Conduction::operateur(), Masse_Multiphase::operateur(), Navier_Stokes_std::operateur(), Convection_Diffusion_std::operateur(), List_Equations_Scalaires_Passifs_Especes::operateur(), Navier_Stokes_std::operateur_fonctionnel(), Equation_base::operateur_fonctionnel(), Matrice_Morse::operator()(), operator+(), EcrFicPartageMPIIO::operator<<(), vect_impl::operator=(), Lec_Diffuse_base::operator=(), Comm_Group::operator=(), IntListsListe::operator=(), IntLists::operator=(), DoubleLists::operator=(), IntTab_parts::operator=(), ConstIntTab_parts::operator=(), DoubleTab_parts::operator=(), ConstDoubleTab_parts::operator=(), VIntdata::operator=(), VDoubledata::operator=(), DomaineCutter::operator=(), Lec_Diffuse_base::operator>>(), Entree::operator>>(), liste::operator[](), IntList::operator[](), DoubleList::operator[](), operator_divide(), operator_inverse(), Matrice_Petsc::ordre(), Zone_VF::orientation(), OrienteFacesBord::oriente_faces_bord(), Sortie_Fichier_base::ouvrir(), LecFicDiffuse_JDD::ouvrir(), Source_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Parser::parserState0(), Parser::parserState1(), Parser::parserState2(), Parser::parseString(), Matrice_Morse::partie_sup(), Convection_Diffusion_Temperature::penalisation_L2(), Polyedriser::polyedriser(), Precond_local::precond(), SSOR::preconditionner_(), PrecondA::preconditionner_(), Precond_local::prepare_(), ILU::prepare_(), Solv_GCP::prepare_data(), MD_Vector_std::prepare_send_data(), Op_Conv_EF_Stab_CoviMAC_Elem::preparer_calcul(), Traitement_particulier_NS_chmoy_faceperio::preparer_calcul_particulier(), Champ_Generique_Transformation::preparer_macro(), Terme_Puissance_Thermique::preparer_source(), Objet_a_lire::print(), Terme_Source_Acceleration::printOn(), Lire_Fichier::printOn(), Interprete_bloc::printOn(), Interprete::printOn(), Execute_parallel::printOn(), Comm_Group_Noparallel::printOn(), Comm_Group_MPI::printOn(), Comm_Group::printOn(), latatoother::printOn(), Format_Post_Medfile::printOn(), Format_Post_Med_major::printOn(), Format_Post_Med::printOn(), IntVect::printOn(), IntTab::printOn(), DoubleVect::printOn(), DoubleTab::printOn(), DescStructure::printOn(), DomaineCutter::printOn(), Domaine_bord::printOn(), Partitionneur_Union::printOn(), Partitionneur_Tranche::printOn(), Partitionneur_Sous_Zones::printOn(), Partitionneur_Sous_Domaine::printOn(), Partitionneur_Ptscotch::printOn(), Partitionneur_Partition::printOn(), Partitionneur_Parmetis::printOn(), Partitionneur_Metis::printOn(), Partitionneur_Fichier_Decoupage::printOn(), Partitionneur_base::printOn(), Decouper::printOn(), Loi_Fermeture_base::printOn(), Format_Post_XYZ::printOn(), Format_Post_Lml::printOn(), Format_Post_Lata::printOn(), Format_Post_base::printOn(), Debog_Pb::printOn(), Old_Debog::printOn(), Champ_som_lu::printOn(), Champ_Generique_Interpolation::printOn(), Champ_Generique_Extraction::printOn(), Champ_Gen_de_Champs_Gen::printOn(), MD_Vector_std::process_recv_data(), Assembleur_P_VEFPreP1B::projete_L2(), projette(), Discret_Thyd::proprietes_physiques_fluide_Ostwald(), EcrFicPartageMPIIO::put(), pwd(), Loi_Etat_Multi_GP_QC::rabot(), Raffiner_anisotrope::Raffiner_anisotrope_(), OctreeRoot::rang_arete(), OctreeRoot::rang_elem(), Zone::rang_elem_depuis(), OctreeRoot::rang_elem_depuis(), Zone::rang_frontiere(), Zone_dis_base::rang_frontiere(), OctreeRoot::rang_sommet(), Param::read(), Objet_a_lire::read(), Champ_Input_Proto::read(), Scatter::readDomainWithoutCollComm(), Elem_VEF::readOn(), Terme_Source_Rappel_T_VEF_Face::readOn(), Terme_Source_Qdm_VEF_Face::readOn(), Terme_Source_Qdm_lambdaup_VEF_Face::readOn(), Terme_Source_Canal_RANS_LES_VEF_Face::readOn(), Source_Forchheimer_VEF_Face::readOn(), Source_Darcy_VEF_Face::readOn(), Perte_Charge_Isotrope_VEF_P1NC::readOn(), Perte_Charge_Directionnelle_VEF_P1NC::readOn(), Perte_Charge_Circulaire_VEF_P1NC::readOn(), Perte_Charge_Anisotrope_VEF_P1NC::readOn(), Op_Dift_standard_VEF_Face::readOn(), Op_Dift_Stab_VEF_Face::readOn(), Op_Diff_VEF_Face_Stab::readOn(), Op_Diff_VEF_Face_Penalise::readOn(), Op_Conv_VEF_Face::readOn(), Op_Conv_Muscl3_VEF_Face::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Op_Conv_EF_VEF_P1NC::readOn(), Echange_contact_Correlation_VEF::readOn(), Terme_Source_Solide_SWIFT_VDF::readOn(), Terme_Source_Qdm_VDF_Face::readOn(), Terme_Source_Canal_RANS_LES_VDF_Face::readOn(), Terme_Source_Canal_RANS_LES_VDF_Elem::readOn(), Source_Forchheimer_VDF_Face::readOn(), Source_Darcy_VDF_Face::readOn(), ModPerm_ErgunPourForch::readOn(), ModPerm_Cte::readOn(), ModPerm_Carman_Kozeny::readOn(), Echange_contact_Correlation_VDF::readOn(), Champ_Don_Face_lu::readOn(), Source_Neutronique::readOn(), Echange_impose_base::readOn(), Modele_turbulence_hyd_nul::readOn(), Simpler_Base::readOn(), Saturation_constant::readOn(), Milieu_composite::readOn(), Fluide_reel_base::readOn(), QDM_Multiphase::readOn(), Flux_interfacial_CoviMAC::readOn(), Multiplicateur_diphasique_Muhler_Steinhagen::readOn(), Multiplicateur_diphasique_Lottes_Flinn::readOn(), Multiplicateur_diphasique_homogene::readOn(), Multiplicateur_diphasique_Friedel::readOn(), Frottement_interfacial_Wallis::readOn(), Frottement_interfacial_Sonnenburg::readOn(), Turbulence_paroi_scal::readOn(), Turbulence_paroi::readOn(), Modele_turbulence_scal_base::readOn(), Mod_turb_hyd_base::readOn(), Mod_turb_hyd::readOn(), Terme_Source_Acceleration::readOn(), PDF_model::readOn(), Sortie_libre_Text_H_ext::readOn(), Neumann_sortie_libre::readOn(), Entree_fluide_T_h_imposee::readOn(), Champ_front_synt::readOn(), Loi_Etat_Multi_GP_WC::readOn(), Loi_Etat_GP_WC::readOn(), Navier_Stokes_WC::readOn(), Champ_front_debit_QC_fonc_t::readOn(), Champ_front_debit_QC::readOn(), Source_QC_QDM_Gen::readOn(), Loi_Etat_rhoT_GP_QC::readOn(), Navier_Stokes_QC::readOn(), Convection_Diffusion_Espece_Binaire_base::readOn(), Reaction::readOn(), Elem_PolyMAC::readOn(), Terme_Source_Qdm_Face_PolyMAC::readOn(), Perte_Charge_Isotrope_PolyMAC_Face::readOn(), Perte_Charge_Directionnelle_PolyMAC_Face::readOn(), Perte_Charge_Circulaire_PolyMAC_Face::readOn(), Perte_Charge_Anisotrope_PolyMAC_Face::readOn(), DP_Impose_PolyMAC_Face::readOn(), VEFPreP1B::readOn(), Op_Diff_VEFP1NCP1B_Face::readOn(), Champ_front_recyclage::readOn(), Champ_Fonc_reprise::readOn(), liste::readOn(), Lire_Fichier::readOn(), Interprete_bloc::readOn(), Interprete::readOn(), Execute_parallel::readOn(), Deriv_::readOn(), Comm_Group_Noparallel::readOn(), Comm_Group_MPI::readOn(), Comm_Group::readOn(), Moyenne_volumique::readOn(), Solveur_Lineaire_Std::readOn(), Schema_Implicite_Multi_TimeStep_base::readOn(), Schema_Euler_Implicite::readOn(), Pbc_MED::readOn(), latatoother::readOn(), Champ_Fonc_MED_Table_Temps::readOn(), Champ_Fonc_MED::readOn(), UserUnaryFunction::readOn(), Solv_Gmres::readOn(), Solv_Gen::readOn(), Solv_GCP_NS::readOn(), Solv_GCP::readOn(), Solv_Cholesky::readOn(), PrecondA::readOn(), IntVect::readOn(), IntTab::readOn(), DoubleVect::readOn(), DoubleTab::readOn(), ArrOfInt::readOn(), ArrOfDouble::readOn(), Sous_Zone::readOn(), Pave::readOn(), Joint::readOn(), DomaineCutter::readOn(), DomaineAxi1d::readOn(), Domaine_bord::readOn(), Partitionneur_Tranche::readOn(), Partitionneur_Sous_Zones::readOn(), Partitionneur_Partition::readOn(), Decouper::readOn(), Zone_Cl_dis_base::readOn(), Sources::readOn(), Sondes_Int::readOn(), Sondes::readOn(), Sonde_Int::readOn(), Sonde::readOn(), Schema_Temps_base::readOn(), Probleme_Couple::readOn(), Probleme_base::readOn(), Postraitements::readOn(), Postraitement::readOn(), Loi_horaire::readOn(), List_Equations_Scalaires_Passifs_Especes::readOn(), Debog_Pb::readOn(), Old_Debog::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Tabule_Temps::readOn(), Champ_Tabule_Morceaux::readOn(), champ_init_canal_sinal::readOn(), Champ_Generique_Reduction_0D::readOn(), Champ_front_tangentiel::readOn(), Champ_front_Tabule::readOn(), Champ_front_bruite::readOn(), Champ_Fonc_Tabule::readOn(), Champ_Fonc_t::readOn(), Champ_Fonc_Morceaux::readOn(), Champ_Fonc_Fonction_txyz_Morceaux::readOn(), Champ_Fonc_Fonction_txyz::readOn(), Sutherland::readOn(), Champ_Don_lu::readOn(), Ch_front_Vortex::readOn(), Champ_front_normal_VEF::readOn(), Elem_EF::readOn(), Source_Scalaire_EF::readOn(), Source_Qdm_EF::readOn(), Op_Conv_EF::readOn(), Elem_CoviMAC::readOn(), Terme_Source_Qdm_Face_CoviMAC::readOn(), Perte_Charge_Isotrope_CoviMAC_Face::readOn(), Perte_Charge_Directionnelle_CoviMAC_Face::readOn(), Perte_Charge_Circulaire_CoviMAC_Face::readOn(), Perte_Charge_Anisotrope_CoviMAC_Face::readOn(), DP_Impose_CoviMAC_Face::readOn(), Reaction::reagir(), recevoir_array_(), recherche(), Champ_front_var_instationnaire::reculer(), Champ_front_instationnaire_base::reculer(), Champ_front_base::reculer(), Raffiner_Simplexes::refine_domain(), Precond_base::reinit(), Remove_elem::Remove_elem_(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Table::remplir(), Fluide_Weakly_Compressible::remplir_champ_pression_for_EOS(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Q1NC_impl::remplir_coord_noeuds(), Champ_P1NC_implementation::remplir_coord_noeuds(), Champ_Face_implementation::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds_et_polys(), Zone_VF::remplir_face_voisins_fictifs(), Op_Dift_VEF_Face_Q1::remplir_nu(), Op_Dift_VEF_P1NCP1B_Face::remplir_nu(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_pA(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), DP_Impose_CoviMAC_Face::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Op_Diff_RotRot::remplir_som_som_EF(), remplir_sommets(), Zone_Cl_VEF::remplir_type_elem_Cl(), Reordonner_faces_periodiques::renum_som_perio(), reordonne(), Rectangle::reordonner(), Hexaedre_VEF::reordonner(), Hexaedre::reordonner(), Faces::reordonner(), Scatter::reordonner_faces_de_joint(), Operateurs_Statistique_tps::reprendre(), Postraitement::reprendre(), Champ_Inc_base::reprendre(), Traitement_particulier_NS_Profils_thermo_VDF::reprendre_stat(), Traitement_particulier_NS_Profils::reprendre_stat(), Traitement_particulier_NS_canal::reprendre_stat_canal(), Ch_front_Vortex::reprendre_vortex(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), Discretisation_base::residu(), IntTab::resize(), DoubleTab::resize(), IntVect::resize_vect_(), DoubleVect::resize_vect_(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Solv_Gen::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Solv_Cholesky::resoudre_systeme(), Synonyme_info::retirer_synonyme(), Discret_Thyd::reynolds_maille(), Navier_Stokes_std::rho_la_vitesse(), Champ_Inc_base::sauvegarder(), Probleme_base::sauver(), Matrice_Petsc::scale(), Probleme_Couple::schema_temps(), Probleme_base::schema_temps(), Equation_base::schema_temps(), liste::search(), Eval_Amont_VDF_Face::secmem_arete_coin_fluide(), Eval_Diff_VDF_Elem< DERIVED_T >::secmem_face(), Eval_centre4_VDF_Elem::secmem_face(), Eval_Amont_VDF_Elem::secmem_face(), Eval_Amont_PolyMAC_Elem::secmem_face(), Nom::selftest(), Comm_Group_MPI::send_recv_start(), Sortie_Brute::set_bin(), Sortie::set_bin(), SChaine::set_bin(), Entree_complete::set_bin(), Entree_Brute::set_bin(), Entree::set_bin(), Champ_Generique_Interpolation::set_domaine(), Operateur_Conv_base::set_incompressible(), Joint::set_joint_item(), Champ_Generique_Interpolation::set_localisation(), IntVect::set_md_vector(), DoubleVect::set_md_vector(), Champ_Generique_Interpolation::set_methode(), Comm_Group_MPI::set_must_mpi_initialize(), Solveur_Masse_base::set_name_of_coefficient_temporel(), Format_Post_Lata::set_param(), Parametre_implicite::set_seuil_solveur_avec_seuil_convergence_solveur(), Comm_Group_MPI::set_trio_u_world(), ICoCo::ProblemTrio::setStationaryMode(), SFichier::SFichier(), Catch_SIGINIT::signal_callback_handler(), Conduction::solide(), Solv_Gen::solve(), Sortie::Sortie(), Terme_Source_Canal_perio::source(), Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion(), Param::supprimer(), Param::supprimer_condition(), Sortie::syncfile(), Synonyme_info::Synonyme_info(), Echange_impose_base::T_ext(), tab_divide_any_shape(), tab_divide_any_shape_(), Eval_Dift_VDF_var_Face::tau_tan_impl(), Eval_Dift_VDF_const_Face::tau_tan_impl(), Discret_Thyd::taux_cisaillement(), Op_Diff_VEFP1NCP1B_Face::test(), Format_Post_base::test_coherence(), Discretisation_base::test_demande_description(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_Kij(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Op_Conv_EF_VEF_P1NC_Stab::test_implicite(), test_solveur(), Loi_horaire::tester(), tester_compatibilite_hydr_concentration(), tester_compatibilite_hydr_fraction_massique(), tester_compatibilite_hydr_thermique(), Operateur_base::tester_contribuer_a_avec(), Champ_Face_implementation::trace(), Champ_P1_isoP1Bulle::trace(), Champ_base::trace(), Raccord_distant_homogene::trace_elem_distant(), Frontiere::trace_elem_distant(), Frontiere::trace_elem_local(), Frontiere::trace_face_distant(), Frontiere::trace_face_local(), Champ_front_contact_VEF::trace_face_raccord(), Frontiere::trace_som_distant(), Frontiere::trace_som_local(), trait_part_calculer_ec_faces(), traite_bord(), Moyenne_volumique::traiter_champs(), Matrice_Morse::transpose(), Op_Diff_RotRot::Tri(), tri_lexicographique_tableau_indirect(), Trianguler_fin::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser::trianguler(), Aretes::trier_pour_debog(), Motcle::try_map_to_int(), Faces::type(), Tetraedre::type_face(), Segment_axi::type_face(), Segment::type_face(), Rectangle_axi::type_face(), Rectangle_2D_axi::type_face(), Rectangle::type_face(), Quadrangle_VEF::type_face(), Prisme::type_face(), Polygone::type_face(), Polyedre::type_face(), Point::type_face(), Hexaedre_VEF::type_face(), Hexaedre::type_face(), Type_info::Type_info(), Elem_VEF::typer(), Elem_PolyMAC::typer(), Deriv_::typer(), Faces::typer(), Elem_EF::typer(), Elem_CoviMAC::typer(), Sortie::unlockfile(), Schema_Temps_base::update_critere_statio(), Milieu_base::update_rho_cp(), Loi_Etat_Multi_GP_WC::update_Yn_values(), usage(), Navier_Stokes_std::uzawa(), va_a_la_parenthese_fermante(), Table::val(), Sortie_libre_Text_H_ext::val_ext(), Neumann_sortie_libre::val_ext(), Entree_fluide_T_h_imposee::val_imp(), Frontiere_ouverte_rho_u_impose::val_imp_au_temps(), Dirichlet::val_imp_au_temps(), Champ_Face::val_imp_face_bord_private(), ptrParam::valeur(), Champ_som_lu_VEF::valeur_a(), Champ_som_lu_VDF::valeur_a(), Champ_som_lu::valeur_a(), Champ_Don_Fonc_xyz::valeur_a(), Champ_Don_Fonc_txyz::valeur_a(), Champ_som_lu_VEF::valeur_a_compo(), Champ_Don_Fonc_xyz::valeur_a_compo(), Champ_Face_implementation::valeur_a_elem(), Champ_base::valeur_a_elem(), Champ_Uniforme_Morceaux::valeur_a_elem(), Champ_Fonc_Morceaux::valeur_a_elem(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem(), Champ_Don_lu::valeur_a_elem(), Champ_som_lu_VEF::valeur_a_elem_compo(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_base::valeur_a_elem_compo(), Champ_Uniforme_Morceaux::valeur_a_elem_compo(), champ_init_canal_sinal::valeur_a_elem_compo(), Champ_Fonc_Morceaux::valeur_a_elem_compo(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_a_elem_compo(), Champ_Don_lu::valeur_a_elem_compo(), Champ_Don_Fonc_xyz::valeur_a_elem_compo(), Champ_base::valeur_a_sommet_compo(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_front_var_instationnaire::valeur_au_temps_et_au_point(), Ch_front_input_P1::valeur_au_temps_et_au_point(), Champ_base::valeur_aux(), Champ_Don_Fonc_xyz::valeur_aux(), Champ_Don_Fonc_txyz::valeur_aux(), Champ_Inc_base::valeur_aux_bords(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_Q1NC_impl::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_som_lu_VDF::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_base::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_Uniforme_Morceaux::valeur_aux_elems(), Champ_Fonc_Morceaux::valeur_aux_elems(), Champ_Fonc_Fonction_txyz_Morceaux::valeur_aux_elems(), Champ_Don_lu::valeur_aux_elems(), Champ_Fonc_Face_CoviMAC::valeur_aux_elems(), Champ_Face_CoviMAC::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_P1iP1B_implementation::valeur_aux_elems_compo(), Champ_base::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_base::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_base::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_CoviMAC::valeur_aux_faces(), Champ_Face_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), Champ_P1iP1B_implementation::valeur_aux_sommets_compo(), Table::valeurs(), Champ_Inc_base::valeurs(), Champ_front_var_instationnaire::valeurs_au_temps(), Champ_front_instationnaire_base::valeurs_au_temps(), Champ_implementation_Q1::value_interpolation(), VDoubledata::VDoubledata(), vect_impl::vect_impl(), Champ_Post_Operateur_Eqn::verification_cas_compo(), verifie(), Memoire::verifie(), Equation_base::verifie_ch_init_nb_comp(), Zone_EF_axi::verifie_compatibilite_domaine(), Zone_EF::verifie_compatibilite_domaine(), NettoieNoeuds::verifie_noeuds(), Postraitement::verifie_nom_et_sources(), Zone_VEF_PreP1b::verifie_ok_arete(), Discretisation_base::verifie_sous_type(), verifie_syntaxe(), Transformer::verifie_type_elem(), verifier(), Milieu_base::verifier_coherence_champs(), Champ_Generique_Transformation::verifier_coherence_donnees(), Echange_contact_VDF::verifier_correspondance(), Loi_horaire::verifier_derivee(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), Debog_Pb::verifier_gen(), Champ_Generique_Transformation::verifier_localisation(), Debog_Pb::verifier_Mat_elems(), Debog_Pb::verifier_partie_std(), VIntdata::VIntdata(), VEF_1D::vitesse(), Discr_inst::volume_maille(), VEF_discretisation::vorticite(), PolyMAC_discretisation::vorticite(), EF_discretisation::vorticite(), CoviMAC_discretisation::vorticite(), Zone_PolyMAC::W_stabiliser(), Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax(), Fluide_Dilatable_base::warn_syntax_Sutherland(), Format_Post_Lata::write_doubletab(), Terme_Source_Canal_perio::write_flow_rate(), Debog_Pb::write_geometry_data(), Format_Post_Lata::write_inttab(), Discret_Thyd::y_plus(), Discr_inst::zone_Cl_dis(), Champ_Inc_base::zone_Cl_dis(), Equation_base::zone_dis(), Champ_Ostwald::zone_dis_base(), Champ_base::zone_dis_base(), Champ_implementation::zone_dis_base(), and Memoire::~Memoire().
{
  Nom message="=========================================\nTRUST has caused an error and will stop.\nUnexpected error during TRUST calculation.";
  exit(message,i);
}
void Process::exit (const Nom & message, int exit_code = -1) [static]
Definition at line 228 of file Process.cpp.
References Comm_Group::abort(), abort(), Cerr, end_journal(), exception_sur_exit, exit(), PE_Groups::finalize(), finl, get_disable_stop(), PE_Groups::groupe_TRUST(), Synonyme_info::hierarchie(), Type_info::hierarchie(), je_suis_maitre(), Journal(), journal_file_open_, journal_shared_, me(), MPI_ENTIER, Objet_U::nom_du_cas(), nproc(), ref_cast, std_err_, and verbose_level_.
{
  if(je_suis_maitre())
    {
      Cerr << message << finl;
      Cerr.flush();
      SFichier hier("hierarchie.dump");
      hier << "\n             KEYWORDS\n";
      Type_info::hierarchie(hier);
      hier << "\n             SYNONYMS\n";
      Synonyme_info::hierarchie(hier);
      if (!get_disable_stop() && Process::je_suis_maitre())
        {
          Nom nomfic( Objet_U::nom_du_cas() );
          nomfic += ".stop";
          {
            SFichier ficstop( nomfic );
            ficstop <<message<<finl;
          }
        }
    }
  Journal() << message << finl;
  if( journal_shared_ && journal_file_open_)
    end_journal(verbose_level_);
  if (exception_sur_exit)
    {
// Lancement d'une exception (utilise par Execute_parallel)
      throw TriouError("Error in trust ",Process::me());
    }
  else
    {
      int abort=0;
#ifdef MPI_
#ifdef INT_is_64_
#define MPI_ENTIER MPI_LONG
#else
#define MPI_ENTIER MPI_INT
#endif
      if (Process::nproc()>1)
        {
          const MPI_Comm& mpi_comm=ref_cast(Comm_Group_MPI,PE_Groups::groupe_TRUST()).get_mpi_comm();
          int tag = 666;
          int buffer[1]= {1};
          MPI_Request request;
// Envoi non bloquant vers me()+1
          int to_pe = (me()==nproc()-1?0:me()+1);
          MPI_Isend(buffer, 1, MPI_ENTIER, to_pe, tag, mpi_comm, &request);
// Reception non bloquante depuis me()-1
          int from_pe = (me()==0?nproc()-1:me()-1);
          MPI_Irecv(buffer, 1, MPI_ENTIER, from_pe, tag, mpi_comm, &request);
// Attente
          sleep(1);
// Test si me() a recu de me()-1
          True_int ok;
          MPI_Status status;
          MPI_Test(&request,&ok,&status);
          if (!ok)
            abort=1;
        }
#endif
      if (abort)
        {
          if (!je_suis_maitre())
            {
              std_err_ << "!!! TRUST process number " << Process::me() << " exited unexpectedly ! See error message at the end of the file " << journal_file_name_ << " -> Aborting calculation..." << finl;
            }
          PE_Groups::groupe_TRUST().abort();
        }
      else
        {
#ifdef MPI_
          MPI_Finalize();
#endif
          PE_Groups::finalize();
        }
    }
// On force exit();
  if (i==0) i=-1;
  ::exit(i); //Seul ::exit utilise dans le code
}
bool Process::force_single_file (const int & ranks, const Nom & filename) [static]
< Attention, necessaire, car appel possible tres tot dans main.cpp alors que Cerr par defini completement sur les processes
Definition at line 72 of file Process.cpp.
References Cerr, finl, je_suis_maitre(), and multiple_files.
Referenced by mon_main::dowork(), Decouper::ecrire(), Raffiner_isotrope_parallele::interpreter(), and Probleme_base::readOn().
{
  char* theValue = getenv("TRUST_MultipleFiles");
  if (theValue != NULL) multiple_files=atoi(theValue);
  if (ranks>multiple_files)
    {
      if (Process::je_suis_maitre())   //!< Attention, necessaire, car appel possible tres tot dans main.cpp alors que Cerr par defini completement sur les processes
        {
          Cerr << "======================================================================================================" << finl;
          Cerr << "Warning! Single file option is forced for " << filename << " above " << multiple_files << " MPI ranks." << finl;
          Cerr << "for I/O performance reasons on cluster and inodes number limitation." << finl;
          Cerr << "If you want to keep multiple files, add at the beginning of your data file to outpass the limitation:" << finl;
          Cerr << "MultipleFiles " << ranks << finl;
          Cerr << "=====================================================================================================" << finl;
        }
      return true;
    }
  else
    return false;
}
void Process::imprimer_ram_totale (int all_process = 0) [static]
Definition at line 374 of file Process.cpp.
References Cout, finl, Journal(), me(), mp_max(), mp_sum(), and ram_processeur().
Referenced by Schema_Temps_base::corriger_dt_calcule(), mon_main::dowork(), Interprete_geometrique_base::interpreter(), and test_un_solveur().
{
  double memoire=ram_processeur();
  if (memoire)
    {
      int Mo=1024*1024;
      if (all_process) Journal() << (int)(memoire/Mo) << " MBytes of RAM taken by the processor " << Process::me() << finl;
      /*      if (Process::nproc()>100)
              {
                memoire=Process::nproc()*memoire;
                Cout << (int)(memoire/Mo) << " MBytes of RAM taken by the calculation (estimation)." << finl;
              }
            else */
      {
// int max_memoire=Process::mp_max(memoire); // int au lieu de double provoque un segfault comment detecter ?
        double max_memoire=Process::mp_max(memoire);
        double total_memoire=Process::mp_sum(memoire);
        Cout << (int)(total_memoire/Mo) << " MBytes of RAM taken by the calculation (max on a rank: "<<(int)(max_memoire/Mo)<<" MB)." << finl;
      }
    }
}
int Process::je_suis_maitre () [static]
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
Definition at line 95 of file Process.cpp.
References PE_Groups::current_group(), and Comm_Group::rank().
Referenced by Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Conv_Muscl_New_VEF_Face::ajouter_antidiffusion(), Probleme_base::allocation(), Assembleur_P_VDF::assembler(), Assembleur_P_VDF::assembler_mat(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VDF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_EF::assembler_QC(), Assembleur_P_VDF::assembler_rho_variable(), Operateur_Diff_base::associer_diffusivite_pour_pas_de_temps(), Convection_Diffusion_Temperature::associer_milieu_base(), Operateur_Conv_base::associer_norme_vitesse(), Terme_Source_Acceleration_VEF_Face::associer_zones(), Terme_Source_Acceleration_VDF_Face::associer_zones(), avancer_fichier(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Op_Conv_Muscl_New_VEF_Face::calculer_coefficients_operateur_centre(), Scatter::calculer_espace_distant_aretes(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_faces(), Scatter::calculer_espace_distant_sommets(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_bords(), Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle(), Terme_Source_Canal_RANS_LES_VDF_Face::calculer_integrale_temporelle(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Reordonner_faces_periodiques::check_faces_periodiques(), Schema_Comm::check_send_recv_pe_list(), Fluide_Quasi_Compressible::checkTraitementPth(), EcrFicPartage::close(), Fluide_Quasi_Compressible::completer_edo(), Format_Post_Med::completer_post_med(), compute_global_connex_components(), Zone_VEF_PreP1b::construire_ok_arete(), Scatter::corriger_espace_distant_elements_perio(), Solv_Petsc::create_solver(), Milieu_base::creer_alpha(), Convection_Diffusion_Temperature::discretiser(), Sous_zone_VF::discretiser(), mon_main::dowork(), Statistiques::dump(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Postraiter_domaine::ecrire(), Decouper::ecrire(), Cond_lim_utilisateur_base::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Med::ecrire_champ_med(), Format_Post_XYZ::ecrire_champ_xyz(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Med::ecrire_domaine_med(), Format_Post_Lml::ecrire_entete_lml(), Format_Post_Med::ecrire_entete_med(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Equation_base::ecrire_fichier_xyz(), Debog_Pb::ecrire_gen(), Format_Post_Lml::ecrire_temps_lml(), Format_Post_Med::ecrire_temps_med(), DomaineCutter::ecrire_zones(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp(), Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col(), EcritureLectureSpecial::ecriture_special(), Lec_Diffuse_base::eof(), exit(), Lec_Diffuse_base::fail(), Probleme_base::file_size_xyz(), Probleme_base::finir(), Format_Post_Lml::finir_lml(), Format_Post_Med::finir_med(), Format_Post_Lata::finir_sans_reprise(), force_single_file(), generate_defaut(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Lec_Diffuse_base::get(), get_Cerr(), get_Cout(), LecFicDiffuse::get_istream(), Lec_Diffuse_base::good(), Debog_Pb::goto_msg(), Op_VEF_Face::impr(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Div_PolyMAC::impr(), Op_Diff_PolyMAC_base::impr(), Op_Grad_VEF_P1B_Face::impr(), Source_base::impr(), Terme_Source_EF_base::impr(), Source_PDF_EF::impr(), Op_Grad_EF::impr(), Op_EF_base::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Diff_CoviMAC_base::impr(), Op_Conv_CoviMAC_base::impr(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Schema_Temps_base::imprimer(), Loi_horaire::imprimer(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), mon_main::init_parallel(), Sonde_Int::initialiser(), Sonde::initialiser(), Schema_Temps_base::initialize(), System::interpreter(), Test_solveur::interpreter(), Scatter::interpreter(), MaillerParallel::interpreter(), Dimension::interpreter(), Old_Debog::interpreter(), Distanceparoi::interpreter_(), EcritureLectureSpecial::is_ecriture_special(), Fichier_Lata::is_master(), is_parallel_object(), Sch_CN_iteratif::iterateTimeStep(), LecFicDiffuse::LecFicDiffuse(), LecFicDiffuse_JDD::LecFicDiffuse_JDD(), Mod_turb_hyd_base::limiter_viscosite_turbulente(), Terme_Source_Acceleration::lire_data(), Scatter::lire_domaine(), PDF_model::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Postraitement_lata::lire_motcle_non_standard(), Schema_Temps_base::lire_nb_pas_dt_max(), Schema_Temps_base::lire_periode_sauvegarde_securite_en_heures(), lire_special(), Schema_Temps_base::lire_temps_cpu_max(), main_TRUST(), Echange_contact_Correlation_VDF::mettre_a_jour(), Schema_Temps_base::mettre_a_jour(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Format_Post_Lata::modify_file_basename(), Traitement_particulier_NS_THI_new::msg_erreur_maillage(), Traitement_particulier_NS_THI::msg_erreur_maillage(), Lec_Diffuse_base::operator>>(), LecFicDistribue::ouvrir(), LecFicDiffuse_JDD::ouvrir(), LecFicDiffuse::ouvrir(), EcrFicPartageMPIIO::ouvrir(), EcrFicPartage::ouvrir(), EcrFicCollecte::ouvrir(), Sonde_Int::ouvrir_fichier(), Sonde::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Turbulence_paroi_scal_base::ouvrir_fichier_partage(), Turbulence_paroi_base::ouvrir_fichier_partage(), Traitement_particulier_NS_EC::post_traitement_particulier(), Traitement_particulier_NS_canal::post_traitement_particulier(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), Sonde_Int::postraiter(), Sonde::postraiter(), Solv_Optimal::prepare_resol(), Traitement_particulier_NS_EC::preparer_calcul_particulier(), Format_Post_Med::preparer_post_med(), Statistiques::print_communciation_tracking_details(), print_stat(), print_statistics_analyse(), Debog_Pb::read_geometry_data(), Op_Dift_Stab_VEF_Face::readOn(), Op_Diff_VEF_Face_Stab::readOn(), Op_Conv_EF_VEF_P1NC_Stab::readOn(), Champ_Don_Face_lu::readOn(), Op_Diff_VEFP1NCP1B_Face::readOn(), Sous_Zone::readOn(), Joint::readOn(), Sonde::readOn(), Debog_Pb::readOn(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), DP_Impose_CoviMAC_Face::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Zone_VEF::reordonner(), Zone_PolyMAC::reordonner(), Zone_EF::reordonner(), Zone_CoviMAC::reordonner(), Hexaedre::reordonner_elem(), Schema_Implicite_Multi_TimeStep_base::reprendre(), Traitement_particulier_NS_canal::reprendre_stat(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Probleme_U::runUntil(), Champ_Inc_base::sauvegarder(), Champ_Fonc_base::sauvegarder(), Probleme_base::sauver(), Traitement_particulier_NS_canal::sauver_stat(), Probleme_base::sauver_xyz(), Fluide_Quasi_Compressible::secmembre_divU_Z(), Lec_Diffuse_base::set_bin(), Catch_SIGINIT::signal_callback_handler(), Solv_Gen::solve(), Terme_Source_Canal_perio::source(), Schema_Temps_base::stop_lu(), EcrFicPartage::syncfile(), Schema_Temps_base::terminate(), Op_Diff_VEFP1NCP1B_Face::test(), Navier_Stokes_std::uzawa(), Schema_Temps_base::validateTimeStep(), Zone_VEF_PreP1b::verifie_ok_arete(), Debog_Pb::verifier(), Loi_horaire::verifier_derivee(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie_std(), and Fluide_Quasi_Compressible::write_mean_edo().
{
  const int r = PE_Groups::current_group().rank();
  return r == 0;
}
Sortie & Process::Journal (int message_level = 0) [static]
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
Definition at line 345 of file Process.cpp.
References journal_file_, journal_file_open_, journal_shared_, journal_shared_stream_, journal_zero_, and std_err_.
Referenced by Interprete_bloc::ajouter(), assert_parallel(), auto_build_joints(), Comm_Group_MPI::barrier(), Statistiques::begin_count_(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_liste_complete_aretes_joint(), Faces_builder::check_erreur_faces(), Schema_Comm::check_send_recv_pe_list(), Scatter::Chercher_Correspondance(), Zone_Cl_VDF::completer(), Champ_Generique_Transformation::completer(), Zone::comprimer(), compute_global_connex_components(), Octree::construire(), Zone::creer_aretes(), crit_err_hdlr(), Op_Div_VEFP1B_Elem::degres_liberte(), mon_main::dowork(), Echange_contact_Correlation_VEF_sauvegarder(), Statistiques::end_communication_tracking(), Schema_Comm_Vecteurs::end_init(), Entree_complete::Entree_complete(), exit(), find_joint_faces(), Zone::fixer_premieres_faces_frontiere(), Zone_VDF::genere_aretes(), imprimer_ram_totale(), Schema_Comm_Vecteurs_Static_Data::init(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), Execute_parallel::interpreter(), MaillerParallel::interpreter(), VerifierCoin::interpreter_(), Interprete_bloc::interpreter_bloc(), Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Zone_VF::marquer_faces_double_contrib(), Zone_VEF::modifier_pour_Cl(), Zone_PolyMAC::modifier_pour_Cl(), Zone_EF::modifier_pour_Cl(), mpi_print_error(), LecFicDistribue::ouvrir(), LecFicDiffuse_JDD::ouvrir(), Solv_GCP::prepare_data(), Champ_Generique_Transformation::preparer_macro(), Champ_Don_Face_lu::readOn(), Sous_Zone::readOn(), Zone_Cl_dis_base::readOn(), Champ_Generique_base::readOn(), Raffiner_Simplexes::refine_domain(), Reorienter_triangles::Reorienter(), Reorienter_tetraedres::Reorienter(), Op_Conv_EF_VEF_P1NC_Stab::test_difference_resu(), Reorienter_tetraedres::test_orientation_tetra(), Reorienter_triangles::test_orientation_triangle(), va_a_la_parenthese_fermante(), and mon_main::~mon_main().
{
  if (message_level <= verbose_level_ && verbose_level_ > 0)
    {
      if (journal_file_open_)
        {
          if(journal_shared_)
            return journal_shared_stream_;
          else
            return journal_file_;
        }
      else
        return std_err_;
    }
  return journal_zero_;
}
int Process::me () [static]
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
Definition at line 117 of file Process.cpp.
References PE_Groups::current_group(), and Comm_Group::rank().
Referenced by add_sommets_communs(), Terme_Source_inc_VDF_Face::ajouter(), Terme_Source_inc_th_VDF_Face::ajouter(), DP_Impose_PolyMAC_Face::ajouter(), SETS::assembler(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_CoviMAC::assembler_mat(), Echange_contact_Correlation_VDF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), EcrFicPartageMPIIO::check(), Scatter::check_consistancy_remote_items(), O_U_Ptr::check_O_U_Ptr_type(), EcrFicPartage::close(), construire_connectivite_real_som_virtual_elem(), Scatter::construire_correspondance_items_par_coordonnees(), Zone::construire_elem_virt_pe_num(), Scatter::construire_espace_virtuel_traduction(), Zone_VF::construire_face_virt_pe_num(), Domain_Graph::construire_graph_elem_elem(), Scatter::construire_md_vector(), coord_barycentrique(), coord_barycentrique_P1_hexaedre(), coord_barycentrique_P1_rectangle(), coord_barycentrique_P1_tetraedre(), coord_barycentrique_P1_triangle(), corriger_type(), Zone::creer_aretes(), creer_md_vect_renum(), crit_err_hdlr(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_PolyMAC::detecter_faces_non_planes(), Zone_CoviMAC::detecter_faces_non_planes(), mon_main::dowork(), Statistiques::dump(), Schema_Comm::echange_messages(), echanger_tableau_aretes(), Postraiter_domaine::ecrire(), Decouper::ecrire(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_dis(), DomaineCutter::ecrire_zones(), EFichier::EFichier(), Schema_Comm::end_comm(), envoyer(), envoyer_buffered_(), erreur_non_convergence(), exit(), Extraire_surface::extraire_surface(), Fichier_Lata::Fichier_Lata(), find_matching_coordinates(), Format_Post_Med::finir(), Champ_implementation_P1::form_function(), O_U_Ptr::get_O_U_Ptr_check(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), imprimer_ram_totale(), Echange_contact_Correlation_VEF::init(), Echange_contact_Correlation_VDF::init_tab_echange(), Zone_VDF::init_virt_e_map(), Zone_PolyMAC::init_virt_ef_map(), Raccord_distant_homogene::initialise(), Echange_contact_VDF::initialiser(), Echange_contact_PolyMAC::initialiser(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), Champ_front_lu::initialiser(), Execute_parallel::interpreter(), Ecrire::interpreter(), Scatter::interpreter(), Raffiner_isotrope_parallele::interpreter(), MaillerParallel::interpreter(), Extraire_plan::interpreter_(), Extraire_domaine::interpreter_(), Solveur_U_P::iterer_NS(), ScatterMED::lire_domaine(), Scatter::lire_domaine(), main_TRUST(), MD_Vector_std::MD_Vector_std(), Echange_contact_Correlation_VEF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), DP_Impose_PolyMAC_Face::mettre_a_jour(), DP_Impose_CoviMAC_Face::mettre_a_jour(), Sortie_Fichier_base::ouvrir(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde_Int::postraiter(), Sonde::postraiter(), StatComm::print_stat(), Champ_Fonc_reprise::readOn(), Champ_Fonc_MED::readOn(), Sous_Zone::readOn(), Probleme_base::readOn(), Champ_Don_lu::readOn(), recevoir(), recevoir_buffered_(), Schema_Comm::recv_buffer(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Reordonner_faces_periodiques::renum_som_perio(), Scatter::reordonner_faces_de_joint(), Ch_front_Vortex::reprendre_vortex(), Ch_front_Vortex::sauvegarder_vortex(), Schema_Comm::send_buffer(), SFichier::SFichier(), EcrFicPartage::syncfile(), Op_Diff_VEFP1NCP1B_Face::test(), Aretes::trier_pour_debog(), Faces::type(), Perte_Charge_Singuliere::update_K(), valeur_P1_L2(), Zone_VEF_PreP1b::verifie_ok_arete(), and verifier().
{
  const int r = PE_Groups::current_group().rank();
  return r;
}
bool Process::mp_and (bool b) [static]
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
Definition at line 199 of file Process.cpp.
References Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int x = b ? 1 : 0;
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MIN);
  return y == 1;
}
double Process::mp_max (double x) [static]
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
Definition at line 156 of file Process.cpp.
References Comm_Group::COLL_MAX, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by DP_Impose_PolyMAC_Face::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Assembleur_P_EF::assembler_mat(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Moyenne_volumique::calculer_convolution(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Scatter::calculer_espace_distant_elements(), Reordonner_faces_periodiques::check_faces_periodiques(), Fluide_reel_base::check_unknown_range(), corriger_incr_alpha(), Zone::creer_aretes(), Statistiques::dump(), Decouper::ecrire(), DomaineCutter::ecrire_zones(), MD_Vector_tools::extend(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Ch_front_input_P1::getTemplate(), Ch_front_input::getTemplate(), Domaine::imprimer(), imprimer_ram_totale(), Zone::init_faces_virt_bord(), Zone_PolyMAC::init_m2(), Echange_contact_PolyMAC::initialiser(), Sonde_Int::initialiser(), Sonde::initialiser(), Scatter::interpreter(), Raffiner_isotrope_parallele::interpreter(), MaillerParallel::interpreter(), Scatter::lire_domaine(), Assembleur_P_VEFPreP1B::modifier_matrice(), Format_Post_Lata::modify_file_basename(), mp_max_abs_vect(), mp_max_vect(), print_statistics_analyse(), DP_Impose_PolyMAC_Face::readOn(), Champ_Fonc_MED::readOn(), Probleme_base::readOn(), DP_Impose_CoviMAC_Face::readOn(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_CoviMAC_Face::remplir_num_faces(), DP_Impose_CoviMAC_Face::remplir_num_faces(), test_un_solveur(), Debog_Pb::verifier_partie_std(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MAX);
  return y;
}
double Process::mp_min (double x) [static]
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
Definition at line 167 of file Process.cpp.
References Comm_Group::COLL_MIN, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Zone_VDF::calcul_h(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Conv_EF_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_CoviMAC_Face::calculer_dt_stab(), Op_Diff_CoviMAC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), Op_Conv_EF_Stab_CoviMAC_Elem::calculer_dt_stab(), Zone_VEF::calculer_h_carre(), Operateur::calculer_pas_de_temps(), Fluide_reel_base::check_unknown_range(), Statistiques::dump(), estimate_allreduce(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Domaine::imprimer(), Zone_PolyMAC::init_m2(), Scatter::interpreter(), lire_special(), Assembleur_P_VEF::modifier_solution(), Assembleur_P_VDF::modifier_solution(), Assembleur_P_EF::modifier_solution(), Assembleur_P_CoviMAC::modifier_solution(), mp_min_abs_vect(), mp_min_vect(), print_statistics_analyse(), Probleme_base::readOn(), valeur_P1_H1(), and valeur_P1_L2().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_MIN);
  return y;
}
double Process::mp_sum (double x) [static]
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
Definition at line 178 of file Process.cpp.
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_P1NC::calcul_h_conv(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_THI::calcul_nb_elem_dir(), Traitement_particulier_NS_THI::calcul_nb_som_dir(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Traitement_particulier_NS_EC::calculer_Ec(), Scatter::calculer_espace_distant_elements(), Zone_VEF::calculer_h_carre(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Schema_Comm::check_send_recv_pe_list(), Zone::check_zone(), EcrFicPartage::close(), compute_global_connex_components(), Terme_Source_Canal_perio::compute_heat_flux(), Domain_Graph::construire_graph_elem_elem(), creer_md_vect_renum(), Sous_zone_VF::discretiser(), distdot2_(), Postraiter_domaine::ecrire(), Decouper::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Lml::ecrire_domaine_lml(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Equation_base::ecrire_fichier_xyz(), Schema_Comm_Vecteurs::end_init(), estimate_allreduce(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), gmres_local(), histogramme_angle(), Op_Div_PolyMAC::impr(), Op_Grad_EF::impr(), Op_EF_base::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Conv_CoviMAC_base::impr(), Domaine::imprimer(), imprimer_ram_totale(), Zone_VF::info_elem_som(), Zone_VF::infobord(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Zone_PolyMAC::init_m2(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), Champ_front_lu::initialiser(), Scatter::interpreter(), Scatter::lire_domaine(), lire_special(), EDO_Pression_th_VDF::masse_totale(), MD_Vector_std::MD_Vector_std(), Sortie_libre_pression_moyenne_imposee::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_Fonc_P0_VDF::moyenne(), mp_carre_norme_vect(), mp_prodscal(), mp_somme_vect(), Zone_PolyMAC::orthocentrer(), Traitement_particulier_NS_Brech_VEF::post_traitement_particulier_calcul_flux(), SSOR::prepare_(), Statistiques::print_communciation_tracking_details(), print_statistics_analyse(), EcrFicPartageMPIIO::put(), Champ_Don_Face_lu::readOn(), Domaine::readOn(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), Hexaedre::reordonner_elem(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Mod_turb_hyd_base::sauvegarder(), Solv_Gen::solve(), Zone_VEF_PreP1b::verifie_ok_arete(), Debog_Pb::verifier(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
{
  const Comm_Group& grp = PE_Groups::current_group();
  double y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_SUM);
  return y;
}
int Process::mp_sum (int x) [static]
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
Definition at line 189 of file Process.cpp.
References Comm_Group::COLL_SUM, PE_Groups::current_group(), and Comm_Group::mp_collective_op().
{
  const Comm_Group& grp = PE_Groups::current_group();
  int y;
  grp.mp_collective_op(&x, &y, 1, Comm_Group::COLL_SUM);
  return y;
}
int Process::nproc () [static]
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
Definition at line 109 of file Process.cpp.
References PE_Groups::current_group(), and Comm_Group::nproc().
Referenced by Probleme_base::allocation(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Conv_kschemas_VEF::associer(), Op_Conv_Quick_VDF_Face::associer(), Op_Conv_Quick_VDF_Elem::associer(), Op_Conv_centre4_VDF_Face::associer(), Op_Conv_centre4_VDF_Elem::associer(), auto_build_joints(), Schema_Comm_Vecteurs::begin_init(), Echange_contact_Correlation_VDF::calculer_CL(), Moyenne_volumique::calculer_convolution(), Simple::calculer_correction_en_vitesse(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Op_Diff_RotRot::calculer_vorticite(), Reordonner_faces_periodiques::check_faces_periodiques(), Schema_Comm::check_send_recv_pe_list(), Zone::check_zone(), Solv_Cholesky::Cholesky(), Champ_front_contact_VEF::completer(), Raccord_distant_homogene::completer(), Champ_front_calc::completer(), Zones::comprimer(), compute_global_connex_components(), Stat_Results::compute_min_max_avg(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_base::corriger_bords_avec_graphe(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), corriger_type(), Solv_Petsc::create_solver(), Zone::creer_aretes(), DecoupeBord::Decouper(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_PolyMAC::detecter_faces_non_planes(), Zone_CoviMAC::detecter_faces_non_planes(), mon_main::dowork(), Statistiques::dump(), Echange_contact_Correlation_VEF_reprendre(), Echange_contact_Correlation_VEF_sauvegarder(), Postraiter_domaine::ecrire(), Decouper::ecrire(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine_lata_V1(), Format_Post_Med::ecrire_domaine_med(), Format_Post_Lata_V1::ecrire_faces_lata_V1(), Format_Post_Lata::ecrire_item_int(), DomaineCutter::ecrire_zones(), ecrit(), Schema_Comm_Vecteurs::end_init(), envoyer_all_to_all(), erreur_non_convergence(), exit(), MD_Vector_tools::extend(), Domaine_bord::extraire_domaine_bord(), ILU::factorisation(), Fichier_Lata::Fichier_Lata(), find_matching_coordinates(), generate_defaut(), Ensemble_Lagrange_base::generer_marqueurs_sz(), EcritureLectureSpecial::get_Output(), gradient_biconjugue(), Navier_Stokes_std::impr(), Echange_contact_Correlation_VEF::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Matrice_Morse::imprimer_formatte(), Matrice_Morse::imprimer_image(), Echange_contact_Correlation_VEF::init(), mon_main::init_parallel(), Echange_contact_Correlation_VDF::init_tab_echange(), Raccord_distant_homogene::initialise(), Champ_front_recyclage::initialiser(), Sonde::initialiser(), Execute_parallel::interpreter(), Ecrire::interpreter(), Scatter::interpreter(), Raffiner_isotrope_parallele::interpreter(), MaillerParallel::interpreter(), VerifierCoin::interpreter_(), Ecrire_Fichier::interpreter_(), Triangulation_base::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Polyedriser::interpreter_(), Mailler::interpreter_(), Lire_Tgrid::interpreter_(), Distanceparoi::interpreter_(), Dilate::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Matrice_Morse::inverse(), is_parallel_object(), Scatter::lire_domaine(), Partitionneur_Metis::lire_motcle_non_standard(), main_TRUST(), MD_Vector_std::MD_Vector_std(), Echange_contact_Correlation_VEF::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_Fonc_P0_VDF::moyenne(), mp_moyenne_vect(), Nom::nom_me(), LecFicDistribue::ouvrir(), EcrFicCollecte::ouvrir(), Traitement_particulier_NS_canal::post_traitement_particulier(), Sonde_Int::postraiter(), Sonde::postraiter(), Precond_local::precond(), SSOR::prepare_(), Statistiques::print_communciation_tracking_details(), print_stat(), print_statistics_analyse(), IntVect::printOn(), IntTab::printOn(), DoubleVect::printOn(), DoubleTab::printOn(), EcrFicPartageMPIIO::put(), Champ_front_contact_VEF::readOn(), Champ_Fonc_reprise::readOn(), Champ_Fonc_MED::readOn(), Solv_Cholesky::readOn(), Sous_Zone::readOn(), Domaine::readOn(), Zone_Cl_dis_base::readOn(), Probleme_base::readOn(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Ch_front_Vortex::reprendre_vortex(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Solv_Petsc::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Ch_front_Vortex::sauvegarder_vortex(), Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC(), Schema_Comm::Schema_Comm(), EcrFicPartage::syncfile(), Fichier_Lata::syncfile(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_contact_VEF::trace_face_raccord(), Zone_VEF_PreP1b::verifie_ok_arete(), verifier(), Debog_Pb::write_geometry_data(), and zero().
{
  const int n = PE_Groups::current_group().nproc();
  return n;
}
double Process::ram_processeur () [static]
Definition at line 363 of file Process.cpp.
Referenced by imprimer_ram_totale().
{
#ifdef PETSCKSP_H
  PetscLogDouble memoire;
  PetscMemoryGetCurrentUsage(&memoire);
  return memoire;
#else
  return 0;
#endif
}
Member Data Documentation
int Process::exception_sur_exit = 0 [static]
Definition at line 70 of file Process.h.
Referenced by exit(), ICoCo::ProblemTrio::initialize(), and Execute_parallel::interpreter().
int Process::multiple_files = 5120 [static]
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Definition at line 71 of file Process.h.
Referenced by force_single_file(), and MultipleFiles::interpreter().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Process.h
src/Kernel/Utilitaires/Process.cpp