TRUST: Joint_Items Class Reference
Joint_Items Class Reference
Joint_Items contient les informations de distribution
parallele d'un item geometrique particulier avec une zone
voisine particuliere (item = sommet, element, face, etc..)
Ces structures sont initialisees dans Scatter.
Elles sont ensuite utilisees par exemple pour creer
un tableau distribue indexe par les indices des items
geometriques.
#include <Joint_Items.h>
Public Member Functions
Joint_Items ()
constructeur par defaut
void reset ()
remise dans l'etat initial obtenu apres constructeur par defaut
int nb_items_reels () const
Pas encore utilise (prevu pour faciliter la creation
des tableaux distribues, mais les joints ne sont pas le bon endroit
pour stocker cette valeur: il faut pouvoir la stocker meme s'il n'y
a aucun processeur voisin).
const ArrOfInt & items_communs () const
Voir items_communs_.
const ArrOfInt & items_distants () const
Voir items_distants_.
int nb_items_virtuels () const
Voir nb_items_virtuels_.
const IntTab & renum_items_communs () const
Voir renum_items_communs_.
void set_nb_items_reels (int n)
Pas encore utilise.
ArrOfInt & set_items_communs ()
Renvoie le tableau items_communs_ pour le remplir.
(BM: ce tableau n'est pas encore rempli)
ArrOfInt & set_items_distants ()
Renvoie le tableau items_distants_ pour le remplir
Voir Scatter::calculer_espace_distant,
Scatter::calculer_espace_distant_faces_frontieres,
Scatter::calculer_espace_distant_elements.
void set_nb_items_virtuels (int n)
Voir nb_items_virtuels_
Voir Scatter::calculer_nb_items_virtuels.
IntTab & set_renum_items_communs ()
Voir renum_items_communs_
Voir Scatter::calculer_colonne0_renum_faces_communes
Scatter::construire_correspondance_sommets_par_coordonnees.
Private Attributes
int nb_items_reels_
ArrOfInt items_communs_
ArrOfInt items_distants_
int nb_items_virtuels_
IntTab renum_items_communs_
int flags_init_
Detailed Description
Joint_Items contient les informations de distribution
parallele d'un item geometrique particulier avec une zone
voisine particuliere (item = sommet, element, face, etc..)
Ces structures sont initialisees dans Scatter.
Elles sont ensuite utilisees par exemple pour creer
un tableau distribue indexe par les indices des items
geometriques.
Definition at line 35 of file Joint_Items.h.
Constructor & Destructor Documentation
Joint_Items()
Joint_Items::Joint_Items ()
constructeur par defaut
Definition at line 23 of file Joint_Items.cpp.
{
  nb_items_virtuels_ = -1;
  nb_items_reels_ = -1;
  flags_init_ = 0;
}
References flags_init_, nb_items_reels_, and nb_items_virtuels_.
Member Function Documentation
items_communs()
const ArrOfInt & Joint_Items::items_communs () const
Voir items_communs_.
Definition at line 42 of file Joint_Items.cpp.
{
  return items_communs_;
}
References items_communs_.
Referenced by add_sommets_communs(), Scatter::calculer_espace_distant_elements(), calculer_liste_complete_sommets_joint(), Scatter::calculer_renum_items_communs(), Scatter::check_consistancy_remote_items(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), Scatter::construire_md_vector(), DomaineCutter::ecrire_zones(), Scatter::mergeDomains(), mon_construire_correspondance_items_par_coordonnees(), and Joint::printOn().
items_distants()
const ArrOfInt & Joint_Items::items_distants () const
Voir items_distants_.
Definition at line 56 of file Joint_Items.cpp.
{
  assert(flags_init_ & 2);
  return items_distants_;
}
References flags_init_, and items_distants_.
Referenced by Scatter::calculer_espace_distant_elements(), calculer_espace_distant_item(), Scatter::calculer_nb_items_virtuels(), Scatter::construire_md_vector(), dump_lata(), DomaineCutter::ecrire_zones(), Joint::esp_dist_elems(), Joint::esp_dist_faces(), Joint::esp_dist_sommets(), Scatter::mergeDomains(), and Joint::printOn().
nb_items_reels()
int Joint_Items::nb_items_reels () const
Pas encore utilise (prevu pour faciliter la creation
des tableaux distribues, mais les joints ne sont pas le bon endroit
pour stocker cette valeur: il faut pouvoir la stocker meme s'il n'y
a aucun processeur voisin).
Definition at line 115 of file Joint_Items.cpp.
{
  assert(flags_init_ & 16);
  return nb_items_reels_;
}
References flags_init_, and nb_items_reels_.
nb_items_virtuels()
int Joint_Items::nb_items_virtuels () const
Voir nb_items_virtuels_.
Definition at line 81 of file Joint_Items.cpp.
{
  assert(flags_init_ & 4);
  return nb_items_virtuels_;
}
References flags_init_, and nb_items_virtuels_.
Referenced by Scatter::construire_md_vector().
renum_items_communs()
const IntTab & Joint_Items::renum_items_communs () const
Voir renum_items_communs_.
Definition at line 97 of file Joint_Items.cpp.
{
  assert(flags_init_ & 8);
  return renum_items_communs_;
}
References flags_init_, and renum_items_communs_.
Referenced by add_sommets_communs(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), Extraire_surface::extraire_surface(), Extraire_plan::interpreter_(), Zone_VF::marquer_faces_double_contrib(), and Joint::renum_virt_loc().
reset()
void Joint_Items::reset ()
remise dans l'etat initial obtenu apres constructeur par defaut
Definition at line 31 of file Joint_Items.cpp.
{
  nb_items_virtuels_ = -1;
  nb_items_reels_ = -1;
  flags_init_ = 0;
  items_communs_.reset();
  items_distants_.reset();
  renum_items_communs_.reset();
}
References flags_init_, items_communs_, items_distants_, nb_items_reels_, nb_items_virtuels_, renum_items_communs_, TRUSTArray< _TYPE_ >::reset(), and TRUSTTab< _TYPE_ >::reset().
set_items_communs()
ArrOfInt & Joint_Items::set_items_communs ()
Renvoie le tableau items_communs_ pour le remplir.
(BM: ce tableau n'est pas encore rempli)
Definition at line 49 of file Joint_Items.cpp.
{
  flags_init_ |= 1;
  return items_communs_;
}
References flags_init_, and items_communs_.
Referenced by ajouter_joint(), ajouter_joints(), auto_build_joints(), Scatter::construire_correspondance_items_par_coordonnees(), DomaineCutter::construire_sommets_joints_ssdom(), Faces_builder::creer_faces_reeles(), mon_construire_correspondance_items_par_coordonnees(), Joint::readOn(), Raffiner_Simplexes::refine_domain(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), and reordonner_vdf().
set_items_distants()
ArrOfInt & Joint_Items::set_items_distants ()
Renvoie le tableau items_distants_ pour le remplir
Voir Scatter::calculer_espace_distant,
Scatter::calculer_espace_distant_faces_frontieres,
Scatter::calculer_espace_distant_elements.
Definition at line 66 of file Joint_Items.cpp.
{
  flags_init_ |= 2;
  return items_distants_;
}
References flags_init_, and items_distants_.
Referenced by ajouter_joint(), Scatter::calculer_espace_distant(), Scatter::calculer_espace_distant_elements(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), Joint::readOn(), and Raffiner_Simplexes::refine_domain().
set_nb_items_reels()
void Joint_Items::set_nb_items_reels (int n)
Pas encore utilise.
Definition at line 104 of file Joint_Items.cpp.
{
  assert(n >= 0);
  flags_init_ |= 16;
  nb_items_reels_ = n;
}
References flags_init_, and nb_items_reels_.
set_nb_items_virtuels()
void Joint_Items::set_nb_items_virtuels (int n)
Voir nb_items_virtuels_
Voir Scatter::calculer_nb_items_virtuels.
Definition at line 74 of file Joint_Items.cpp.
{
  flags_init_ |= 4;
  nb_items_virtuels_ = n;
}
References flags_init_, and nb_items_virtuels_.
Referenced by ajouter_joint(), and Scatter::calculer_nb_items_virtuels().
set_renum_items_communs()
IntTab & Joint_Items::set_renum_items_communs ()
Voir renum_items_communs_
Voir Scatter::calculer_colonne0_renum_faces_communes
Scatter::construire_correspondance_sommets_par_coordonnees.
Definition at line 90 of file Joint_Items.cpp.
{
  flags_init_ |= 8;
  return renum_items_communs_;
}
References flags_init_, and renum_items_communs_.
Referenced by ajouter_joint(), and Scatter::calculer_renum_items_communs().
Member Data Documentation
flags_init_
int Joint_Items::flags_init_ private
Definition at line 86 of file Joint_Items.h.
Referenced by items_distants(), Joint_Items(), nb_items_reels(), nb_items_virtuels(), renum_items_communs(), reset(), set_items_communs(), set_items_distants(), set_nb_items_reels(), set_nb_items_virtuels(), and set_renum_items_communs().
items_communs_
ArrOfInt Joint_Items::items_communs_ private
Definition at line 65 of file Joint_Items.h.
Referenced by items_communs(), reset(), and set_items_communs().
items_distants_
ArrOfInt Joint_Items::items_distants_ private
Definition at line 70 of file Joint_Items.h.
Referenced by items_distants(), reset(), and set_items_distants().
nb_items_reels_
int Joint_Items::nb_items_reels_ private
Definition at line 59 of file Joint_Items.h.
Referenced by Joint_Items(), nb_items_reels(), reset(), and set_nb_items_reels().
nb_items_virtuels_
int Joint_Items::nb_items_virtuels_ private
Definition at line 75 of file Joint_Items.h.
Referenced by Joint_Items(), nb_items_virtuels(), reset(), and set_nb_items_virtuels().
renum_items_communs_
IntTab Joint_Items::renum_items_communs_ private
Definition at line 83 of file Joint_Items.h.
Referenced by renum_items_communs(), reset(), and set_renum_items_communs().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Joint_Items.h
src/Kernel/Geometrie/Joint_Items.cpp