TRUST: DomaineAxi1d Class Reference
DomaineAxi1d Class Reference
: class DomaineAxi1d
<Description of class DomaineAxi1d>
#include <DomaineAxi1d.h>
Public Member Functions
DomaineAxi1d ()
~DomaineAxi1d ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Champ & champ_origine () const
const Champ & champ_origine ()
const DoubleTab & origine_repere ()
const DoubleTab & origine_repere () const
void associer_origine_repere (const DoubleTab &orig)
double origine_repere (int i, int j)
double origine_repere (int i, int j) const
Public Member Functions inherited from Domaine
~Domaine ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Domaine ()
Constructeur par defaut d'un objet Domaine.
Ne fait rien sauf fixer la valeur d'epsilon
a Objet_U::precision_geom
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
const Nom & le_nom () const override
Renvoie le nom du domaine.
void nommer (const Nom &) override
Donne un nom au domaine.
int nb_zones () const
Renvoie le nombre de zone du domaine.
const Zone & zone (int) const
Renvoie la i-ieme zone du domaine.
(version const)
Zone & zone (int)
Renvoie la i-ieme zone du domaine.
const Zone & zone (const Nom &) const
Renvoie la Zone dont le nom est indique en parametre.
(version const)
Zone & zone (const Nom &)
Renvoie la Zone dont le nom est indique en parametre.
int nb_ss_zones () const
Renvoie le nombre de sous-zone.
const Sous_Zone & ss_zone (int) const
Renvoie la i-ieme sous-zone.
(version const)
Sous_Zone & ss_zone (int)
Renvoie la i-ieme sous-zone.
const Sous_Zone & ss_zone (const Nom &) const
Renvoie la sous-zone dont le nom est indique en parametre.
(version const)
Sous_Zone & ss_zone (const Nom &)
Renvoie la sous-zone dont le nom est indique en parametre.
double coord (int, int) const
Renvoie la j-ieme coordonnee du i-ieme noeud.
double & coord (int, int)
Renvoie une reference sur la j-ieme coordonnee
du i-ieme noeud. (ce qui permet de modifier sa valeur)
const DoubleTab & coord_sommets () const
Renvoie le tableau des coordonnees des noeuds (sommets).
(acces en lecture)
virtual int nb_som () const
Renvoie le nombre de sommets.
virtual int nb_som_tot () const
Renvoie le nombre total de sommets.
void add (const Sous_Zone &)
Ajoute une Sous_Zone au domaine.
int associer_ (Objet_U &) override
Association d'une Sous_Zone au domaine.
L'interface permet de passer n'importe quel
Objet_U mais ne gere (dynamiquement) que
l'association d'un objet derivant Sous_Zone.
DoubleTab & les_sommets ()
Renvoie le nombre total de sommets.
const DoubleTab & les_sommets () const
Renvoie le tableau des sommets du domaine.
DoubleTab getBoundingBox () const
Zone & add (Zone &)
Ajoute une Zone au domaine.
void ajouter (const DoubleTab &, IntVect &)
Ajoute des noeuds au domaine avec elimination des noeuds double
au retour nums contient les nouveaux numeros des noeuds de soms
apres elimination des doublons.
void ajouter (const DoubleTab &)
Ajoute des noeuds (ou sommets) au domaine<br>(sans verifier les doublons)
void comprimer ()
Rassemble les Zones de meme type.
void fixer_epsilon (double)
Fixe epsilon,
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
double epsilon () const
Renvoie epsilon.
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
void reordonner ()
Reordonne les mailles du domaine suivant les
conventions de Trio-U.
int numero_sommet (int i) const
const Zones & zones () const
Zones & zones ()
const List_Ref_Sous_Zone & ss_zones () const
int deformable () const
int & deformable ()
int get_renum_som_perio (int) const
void construire_renum_som_perio (const Conds_lim &, const Zone_dis &)
virtual void initialiser (double temps, Domaine_dis &, Probleme_base &)
virtual void set_dt (double &dt_)
virtual void mettre_a_jour (double temps, Domaine_dis &, Probleme_base &)
void set_fichier_lu (Nom &nom)
const Nom & get_fichier_lu () const
virtual void creer_tableau_sommets (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par sommet du maillage.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void creer_tableau_elements (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par element du maillage.
Pour l'instant, erreur s'il y a plus d'une zone dans le domaine.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual const MD_Vector & md_vector_sommets () const
void set_renum_som_perio (IntTab &renum)
void creer_mes_domaines_frontieres (const Zone_VF &zone_vf)
void imprimer () const
const List_Ref_Domaine & domaines_frontieres () const
void buildUFacesMesh (const Zone_dis_base &zone_dis_base) const
bool Axi1d () const
bool Axi1d ()
void read_vertices (Entree &s)
only read vertices from the stream s
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static DomaineAxi1d & self_cast (Objet_U &)
static const DomaineAxi1d & self_cast (const Objet_U &)
Static Public Member Functions inherited from Domaine
static Objet_U * cree_instance ()
static const Type_info * info ()
static Domaine & self_cast (Objet_U &)
static const Domaine & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Domaine
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le domaine sur un flot de sortie.
On ecrit le nom, les sommets, les zones
et les sous-zones.
Entree & readOn (Entree &) override
Lit les specifications d'un domaine
a partir d'un flot d'entree. Associe les zones
lues au domaine.
Format:
nom_domaine
bloc de lecture des Sommets
bloc de lecture des Zones
bloc de lecture des Sous_Zones
Attention: en parallele, chaque processeur s'attend a lire une strucutre domaine
avec des infos de joint, mais il y a des communications globales.
Pour lire un domaine sur un seul processeur, il faut mettre le processeur dans
un groupe seul.
Sortie & printOn (Sortie &x) const override
Ecrit le domaine sur un flot de sortie.
On ecrit le nom, les sommets, les zones
et les sous-zones.
Entree & readOn (Entree &) override
Lit les specifications d'un domaine
a partir d'un flot d'entree. Associe les zones
lues au domaine.
Format:
nom_domaine
bloc de lecture des Sommets
bloc de lecture des Zones
bloc de lecture des Sous_Zones
Attention: en parallele, chaque processeur s'attend a lire une strucutre domaine
avec des infos de joint, mais il y a des communications globales.
Pour lire un domaine sur un seul processeur, il faut mettre le processeur dans
un groupe seul.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Champ champ_orig
Ref_DoubleTab ref_origine_
Protected Attributes inherited from Domaine
List_Ref_Domaine domaines_frontieres_
Nom nom_
DoubleTab sommets
List_Ref_Sous_Zone les_ss_zones
Zones les_zones
ArrOfInt renum_som_perio
double epsilon_
int deformable_
Nom fichier_lu_
int axi1d
Detailed Description
: class DomaineAxi1d
<Description of class DomaineAxi1d>
Definition at line 31 of file DomaineAxi1d.h.
Constructor & Destructor Documentation
DomaineAxi1d()
DomaineAxi1d::DomaineAxi1d ()
Definition at line 20 of file DomaineAxi1d.cpp.
{
  axi1d = 1;
}
References Domaine::axi1d.
~DomaineAxi1d()
DomaineAxi1d::~DomaineAxi1d ()
Definition at line 18 of file DomaineAxi1d.cpp.
Member Function Documentation
associer_origine_repere()
void DomaineAxi1d::associer_origine_repere (const DoubleTab & orig)
Definition at line 91 of file DomaineAxi1d.cpp.
{
  ref_origine_ = orig;
}
References ref_origine_.
Referenced by Zone_EF_axi::remplir_tableau_origine().
champ_origine() [1/2]
const Champ & DomaineAxi1d::champ_origine ()
Definition at line 71 of file DomaineAxi1d.cpp.
{
  return champ_orig;
}
References champ_orig.
champ_origine() [2/2]
const Champ & DomaineAxi1d::champ_origine () const
Definition at line 76 of file DomaineAxi1d.cpp.
{
  return champ_orig;
}
References champ_orig.
Referenced by Zone_EF_axi::remplir_tableau_origine().
cree_instance()
Objet_U * DomaineAxi1d::cree_instance () static
Definition at line 18 of file DomaineAxi1d.cpp.
duplique()
int DomaineAxi1d::duplique () const override virtual
Reimplemented from Domaine.
Definition at line 18 of file DomaineAxi1d.cpp.
get_info()
const Type_info * DomaineAxi1d::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Domaine.
Definition at line 18 of file DomaineAxi1d.cpp.
info()
const Type_info * DomaineAxi1d::info () static
Definition at line 18 of file DomaineAxi1d.cpp.
origine_repere() [1/4]
const DoubleTab & DomaineAxi1d::origine_repere ()
Definition at line 81 of file DomaineAxi1d.cpp.
{
  return ref_origine_.valeur();
}
References ref_origine_, and Ref_DoubleTab::valeur().
Referenced by Faces::calculer_surfaces(), Segment_axi::calculer_volumes(), Echange_interne_global_impose::completer(), and Segment_EF_axi::normale().
origine_repere() [2/4]
const DoubleTab & DomaineAxi1d::origine_repere () const
Definition at line 86 of file DomaineAxi1d.cpp.
{
  return ref_origine_.valeur();
}
References ref_origine_, and Ref_DoubleTab::valeur().
origine_repere() [3/4]
double DomaineAxi1d::origine_repere (int i, int j) inline
Definition at line 53 of file DomaineAxi1d.h.
{
  return ref_origine_.valeur()(i,j);
}
References ref_origine_, and Ref_DoubleTab::valeur().
origine_repere() [4/4]
double DomaineAxi1d::origine_repere (int i, int j) const inline
Definition at line 58 of file DomaineAxi1d.h.
{
  return ref_origine_.valeur()(i,j);
}
References ref_origine_, and Ref_DoubleTab::valeur().
printOn()
Sortie & DomaineAxi1d::printOn (Sortie & s) const override protected virtual
Ecrit le domaine sur un flot de sortie.
On ecrit le nom, les sommets, les zones
et les sous-zones.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Domaine.
Definition at line 25 of file DomaineAxi1d.cpp.
{
  Domaine::printOn( os );
  return os;
}
References Domaine::printOn().
readOn()
Entree & DomaineAxi1d::readOn (Entree & s) override protected virtual
Lit les specifications d'un domaine
a partir d'un flot d'entree. Associe les zones
lues au domaine.
Format:
nom_domaine
bloc de lecture des Sommets
bloc de lecture des Zones
bloc de lecture des Sous_Zones
Attention: en parallele, chaque processeur s'attend a lire une strucutre domaine
avec des infos de joint, mais il y a des communications globales.
Pour lire un domaine sur un seul processeur, il faut mettre le processeur dans
un groupe seul.
Reimplemented from Domaine.
Definition at line 31 of file DomaineAxi1d.cpp.
{
  const Motcle accolade_ouverte("{");
  const Motcle accolade_fermee("}");
  Motcle motlu;
  is >> motlu;
  if (motlu != accolade_ouverte)
    {
      Cerr << "Error while reading 1D axi domain " <<  finl;
      Cerr << "We expected a " << accolade_ouverte << " instead of \n"
           << motlu << finl;
      Process::exit();
    }
  while (1)
    {
      is >> motlu;
      if (motlu == accolade_fermee)
        break;
      if (motlu=="ORIGINE")
        {
          is >> champ_orig;
        }
      else
        {
          Cerr << "Error while reading 1D axi domain " <<  finl;
          Cerr << "We expected a \"origine\" instead of \n"
               << motlu << finl;
          Process::exit();
        }
    }
  return is;
}
References Cerr, champ_orig, Process::exit(), and finl.
self_cast() [1/2]
const DomaineAxi1d & DomaineAxi1d::self_cast (const Objet_U & r) static
Definition at line 18 of file DomaineAxi1d.cpp.
self_cast() [2/2]
DomaineAxi1d & DomaineAxi1d::self_cast (Objet_U & r) static
Definition at line 18 of file DomaineAxi1d.cpp.
taille_memoire()
unsigned DomaineAxi1d::taille_memoire () const override virtual
Reimplemented from Domaine.
Definition at line 18 of file DomaineAxi1d.cpp.
Member Data Documentation
champ_orig
Champ DomaineAxi1d::champ_orig protected
Definition at line 49 of file DomaineAxi1d.h.
Referenced by champ_origine(), and readOn().
info_obj
const Type_info DomaineAxi1d::info_obj static
Definition at line 34 of file DomaineAxi1d.h.
ref_origine_
Ref_DoubleTab DomaineAxi1d::ref_origine_ protected
Definition at line 50 of file DomaineAxi1d.h.
Referenced by associer_origine_repere(), and origine_repere().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/DomaineAxi1d.h
src/Kernel/Geometrie/DomaineAxi1d.cpp