TRUST: List_Ref_Champ_Inc_base Class Reference
List_Ref_Champ_Inc_base Class Reference
classe Loi_Etat_Multi_GP_base
Cette classe represente la loi d'etat pour un melange de gaz parfaits.
#include <Loi_Etat_Multi_GP_base.h>
Public Member Functions
List_Ref_Champ_Inc_base ()
~List_Ref_Champ_Inc_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
List_Ref_Champ_Inc_base (const Ref_Champ_Inc_base &t)
List_Ref_Champ_Inc_base (const List_Ref_Champ_Inc_base &t)
Ref_Champ_Inc_base & operator[] (int)
Operateur d'acces au ieme element de la liste.
const Ref_Champ_Inc_base & operator[] (int) const
Operateur d'acces au ieme element de la liste.
Ref_Champ_Inc_base & operator[] (const Nom &)
Operateur d'acces a l'element de la liste qui est egal a nom.
const Ref_Champ_Inc_base & operator[] (const Nom &) const
Operateur d'acces a l'element de la liste qui est egal a nom.
Ref_Champ_Inc_base & operator() (int i)
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
const Ref_Champ_Inc_base & operator() (int i) const
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Ref_Champ_Inc_base & operator() (const Nom &n)
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
const Ref_Champ_Inc_base & operator() (const Nom &n) const
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Ref_Champ_Inc_base & valeur ()
Retourne l'Objet_U associe a la cellule de la liste.
const Ref_Champ_Inc_base & valeur () const
Retourne l'Objet_U associe a la cellule de la liste.
List_Ref_Champ_Inc_base & operator= (const Ref_Champ_Inc_base &t)
Ref_Champ_Inc_base * operator-> ()
Retourne un pointeur sur l'Objet_U premier element de la liste.
List_Ref_Champ_Inc_base & operator= (const List_Ref_Champ_Inc_base &)
List_Ref_Champ_Inc_base & add (const List_Ref_Champ_Inc_base &)
Ref_Champ_Inc_base & add (const Ref_Champ_Inc_base &)
List_Ref_Champ_Inc_base & inserer (const List_Ref_Champ_Inc_base &)
Ref_Champ_Inc_base & inserer (const Ref_Champ_Inc_base &)
void supprimer ()
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
List_Ref_Champ_Inc_base & operator+= (const List_Ref_Champ_Inc_base &)
List_Ref_Champ_Inc_base & operator+= (const Ref_Champ_Inc_base &)
Ref_Champ_Inc_base & add_if_not (const Ref_Champ_Inc_base &)
Ref_Champ_Inc_base & add_if_not (const char *const)
List_Ref_Champ_Inc_base & search (const Ref_Champ_Inc_base &) const
List_Ref_Champ_Inc_base & search (const char *const) const
Recherche d'un Objet_U de Nom ch dans la liste.
List_Ref_Champ_Inc_base & suivant ()
Retourne la liste composee des elements suivants de la liste consideree.
const List_Ref_Champ_Inc_base & suivant () const
Retourne la liste composee des elements suivants de la liste consideree.
const List_Ref_Champ_Inc_base & dernier () const
Renvoie le dernier element de la liste.
List_Ref_Champ_Inc_base & dernier ()
Renvoie le dernier element de la liste.
List_Ref_Champ_Inc_base & operator-= (const Ref_Champ_Inc_base &)
int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
int contient (const Ref_Champ_Inc_base &) const
int contient (const char *const) const
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
int rang (const Ref_Champ_Inc_base &) const
void suppr (const Ref_Champ_Inc_base &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static List_Ref_Champ_Inc_base & self_cast (Objet_U &)
static const
List_Ref_Champ_Inc_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture d'une liste sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une liste sur un flot d'entree.
int est_egal_a (const List_Ref_Champ_Inc_base &) const
Detailed Description
classe Loi_Etat_Multi_GP_base
Cette classe represente la loi d'etat pour un melange de gaz parfaits.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
Constructor & Destructor Documentation
List_Ref_Champ_Inc_base::List_Ref_Champ_Inc_base ()
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
List_Ref_Champ_Inc_base::~List_Ref_Champ_Inc_base ()
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
List_Ref_Champ_Inc_base::List_Ref_Champ_Inc_base (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base::List_Ref_Champ_Inc_base (const List_Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Member Function Documentation
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::add (const List_Ref_Champ_Inc_base & a_list) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
Referenced by Loi_Etat_Multi_GP_base::associer_inconnue().
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::add (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::add_if_not (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::add_if_not (const char * const t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
int List_Ref_Champ_Inc_base::contient (const Ref_Champ_Inc_base & t) const [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
int List_Ref_Champ_Inc_base::contient (const char * const ch) const [inline]
Verifie si un Objet_U de Nom ch appartient ou non a la liste.
Returns:
int
Signification: 1 si la liste contient un Objet_U de Nom ch, 0 sinon
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Objet_U * List_Ref_Champ_Inc_base::cree_instance () [static]
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
const List_Ref_Champ_Inc_base& List_Ref_Champ_Inc_base::dernier () const [inline]
Renvoie le dernier element de la liste.
Returns:
const liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::dernier () [inline]
Renvoie le dernier element de la liste.
Returns:
liste&
Signification: le dernier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
int List_Ref_Champ_Inc_base::duplique () const [virtual]
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
int List_Ref_Champ_Inc_base::est_egal_a (const Objet_U & x) const [virtual]
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
Reimplemented from Objet_U.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
int List_Ref_Champ_Inc_base::est_egal_a (const List_Ref_Champ_Inc_base &) const [inline, protected]
const Type_info * List_Ref_Champ_Inc_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
const Type_info * List_Ref_Champ_Inc_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::inserer (const List_Ref_Champ_Inc_base & a_list) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::inserer (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
const Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator() (const Nom & nom) const [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator() (const Nom & nom) [inline]
Retourne le premier element de la liste dont le Nom est nom
Sort en erreur si aucun Objet_U n'est trouve.
Returns:
Objet_U&
Signification: le premier element de la liste dont le Nom est nom
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
const Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator() (int i) const [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator() (int i) [inline]
Retourne le ieme element de la liste
Sort en erreur si l'indice deborde de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator+= (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator+= (const List_Ref_Champ_Inc_base & a_list) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator-= (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base * List_Ref_Champ_Inc_base::operator-> () [inline]
Retourne un pointeur sur l'Objet_U premier element de la liste.
Returns:
Objet_U*
Signification: pointeur sur l'Objet_U premier element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator= (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator= (const List_Ref_Champ_Inc_base & a_list) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator[] (int i) [inline]
Operateur d'acces au ieme element de la liste.
Returns:
Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator[] (const Nom & nom) [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
const Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator[] (const Nom & nom) const [inline]
Operateur d'acces a l'element de la liste qui est egal a nom.
Returns:
const Objet_U&
Signification: l'element de la liste qui est egal a nom
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
const Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::operator[] (int i) const [inline]
Operateur d'acces au ieme element de la liste.
Returns:
const Objet_U&
Signification: le ieme element de la liste
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Sortie & List_Ref_Champ_Inc_base::printOn (Sortie & os) const [protected, virtual]
Ecriture d'une liste sur un flot de sortie.
Returns:
Sortie&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
int List_Ref_Champ_Inc_base::rang (const Ref_Champ_Inc_base & t) const [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Entree & List_Ref_Champ_Inc_base::readOn (Entree & is) [protected, virtual]
Lecture d'une liste sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::search (const Ref_Champ_Inc_base & t) const [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::search (const char * const ch) const [inline]
Recherche d'un Objet_U de Nom ch dans la liste.
Returns:
liste&
Signification: L'element de la liste trouve
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
const List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::self_cast (Objet_U & r) [static]
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
const List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::suivant () const [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
const liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
List_Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::suivant () [inline]
Retourne la liste composee des elements suivants de la liste consideree.
Returns:
liste&
Signification: liste des elements suivants
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
void List_Ref_Champ_Inc_base::suppr (const Ref_Champ_Inc_base & t) [inline]
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
void List_Ref_Champ_Inc_base::supprimer () [inline]
Supprime l'element suivant de la liste
Ne fait rien si la liste est vide ou si l'element courant est le dernier de la liste.
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
unsigned List_Ref_Champ_Inc_base::taille_memoire () const [virtual]
Reimplemented from liste.
Definition at line 31 of file Loi_Etat_Multi_GP_base.cpp.
const Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::valeur () const [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
const Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
: public Loi_Etat_Melange_GP_base
Ref_Champ_Inc_base & List_Ref_Champ_Inc_base::valeur () [inline]
Retourne l'Objet_U associe a la cellule de la liste.
Returns:
Objet_U&
Signification: reference sur l'Objet_U courant
Contraintes:
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
Referenced by Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_QC::calculer_mu_wilke(), Loi_Etat_Multi_GP_QC::calculer_tab_Cp(), Loi_Etat_Multi_GP_base::initialiser_inco_ch(), and Loi_Etat_Multi_GP_QC::rabot().
: public Loi_Etat_Melange_GP_base
Member Data Documentation
const Type_info List_Ref_Champ_Inc_base::info_obj [static]
Reimplemented from liste.
Definition at line 42 of file Loi_Etat_Multi_GP_base.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Multi_GP_base.h
src/ThHyd/Dilatable/Common/Loi_Etat/Loi_Etat_Multi_GP_base.cpp