TRUST: Frontiere Class Reference
Frontiere Class Reference
Classe Frontiere.
Une Frontiere decrit une partie de la frontiere d'une Zone,
elle possede un Nom, elle porte des Faces et a une Zone associee.
Une Frontiere peut etre specialisee en un Bord, un Joint un
Raccord ou une Face Interne.
#include <Frontiere.h>
Public Member Functions
Frontiere ()
~Frontiere () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone (const Zone &)
Associe la frontiere a la zone dont elle depend.
const Zone & zone () const
Renvoie la Zone associee a la frontiere.
(version const)
Zone & zone ()
Renvoie la Zone associee a la frontiere.
void nommer (const Nom &) override
Donne un nom a la frontiere.
void ajouter_faces (const IntTab &)
Ajoute une (ou plusieurs) face(s) a la frontiere,
la (les) face(s) est (sont) specifiee(s) par un tableau
contenant les numeros des sommets.
void typer_faces (const Motcle &)
Type les faces de la frontiere.
void typer_faces (const Type_Face &)
Type les faces de la frontiere.
const Faces & faces () const
Renvoie les faces de la frontiere<br>(version const)
Faces & faces ()
Renvoie les faces de la frontiere.
IntTab & les_sommets_des_faces ()
Renvoie les sommets des faces de la frontiere.
const IntTab & les_sommets_des_faces () const
Renvoie les sommets des faces de la frontiere.
int nb_faces () const
Renvoie le nombre de faces de la frontiere.
void dimensionner (int)
Dimensionne la frontiere, i.e. fixe
son nombre de faces.
const Nom & le_nom () const override
Renvoie le nom de la frontiere.
void renum (const IntVect &)
Renumerote les noeuds (sommets) des faces.
Le noeud de numero k devient le noeud de numero Les_Nums[k].
void add (const Frontiere &)
Ajoute les sommets (et faces) de la frontiere
passee en parametre a l'objet (Frontiere).
int nb_faces_virt () const
int face_virt (int i) const
int num_premiere_face () const
void fixer_num_premiere_face (int)
const ArrOfInt & get_faces_virt () const
ArrOfInt & get_faces_virt ()
const double & get_aire () const
void set_aire (double &aire)
virtual void creer_tableau_faces (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par face de cette frontiere
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void trace_elem_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux elements y.
virtual void trace_face_local (const DoubleTab &, DoubleTab &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_face_local (const DoubleVect &, DoubleVect &) const
Renvoie la trace sur la frontiere du tableau aux faces y.
virtual void trace_elem_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_som_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleTab &, DoubleTab &) const
virtual void trace_face_distant (const DoubleVect &, DoubleVect &) const
virtual void trace_som_local (const DoubleTab &y, DoubleTab &x) const
Renvoie la trace sur la frontiere du tableau aux noeuds y.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Frontiere & self_cast (Objet_U &)
static const Frontiere & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit la frontiere sur un flot de sortie.
On ecrit:
le nom de la frontiere
les faces.
Entree & readOn (Entree &) override
Lit les specification d'une frontiere
a partir d'un flot d'entree.
On lit:
le nom
les faces.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Nom nom
Faces les_faces
Ref_Zone la_zone
ArrOfInt faces_virt
int num_premiere_face_
double aire_
Detailed Description
Classe Frontiere.
Une Frontiere decrit une partie de la frontiere d'une Zone,
elle possede un Nom, elle porte des Faces et a une Zone associee.
Une Frontiere peut etre specialisee en un Bord, un Joint un
Raccord ou une Face Interne.
Definition at line 33 of file Frontiere.h.
Constructor & Destructor Documentation
Frontiere()
Frontiere::Frontiere ()
Definition at line 20 of file Frontiere.cpp.
~Frontiere()
Frontiere::~Frontiere () override
Definition at line 20 of file Frontiere.cpp.
Member Function Documentation
add()
void Frontiere::add (const Frontiere & front)
Ajoute les sommets (et faces) de la frontiere
passee en parametre a l'objet (Frontiere).
Definition at line 292 of file Frontiere.cpp.
{
  const Faces& a_ajouter=front.faces();
  int nbf1=les_faces.nb_faces();
  int nbf2=a_ajouter.nb_faces();
// max to treat the case where my front is empty
  int nbs=std::max(les_faces.nb_som_faces(), a_ajouter.nb_som_faces());
  int face;
  les_faces.les_sommets().resize(nbf1+nbf2, nbs);
  for(face=0; face<nbf2; face++)
    for(int som=0; som<nbs; som++)
      les_faces.sommet(nbf1+face, som)=a_ajouter.sommet(face, som);
  if(a_ajouter.voisins().nb_dim() == 1)
    return;
  int nb_voisins = a_ajouter.voisins().dimension(1);
  les_faces.voisins().resize(nbf1+nbf2, nb_voisins);
  for(face=0; face<nbf2; face++)
    for(int voisin=0; voisin<nb_voisins; voisin++)
      les_faces.voisin(nbf1+face, voisin)=a_ajouter.voisin(face, voisin);
}
References TRUSTTab< _TYPE_ >::dimension(), faces(), les_faces, Faces::les_sommets(), TRUSTTab< _TYPE_ >::nb_dim(), Faces::nb_faces(), Faces::nb_som_faces(), TRUSTTab< _TYPE_ >::resize(), Faces::sommet(), Faces::voisin(), and Faces::voisins().
Referenced by Zone::comprimer(), Zone::comprimer_joints(), RegroupeBord::interpreter_(), and Mod_turb_hyd_base::lire_motcle_non_standard().
ajouter_faces()
void Frontiere::ajouter_faces (const IntTab & sommets)
Ajoute une (ou plusieurs) face(s) a la frontiere,
la (les) face(s) est (sont) specifiee(s) par un tableau
contenant les numeros des sommets.
Definition at line 127 of file Frontiere.cpp.
{
  les_faces.ajouter(sommets);
}
References Faces::ajouter(), and les_faces.
Referenced by ExtrudeBord::extruder_hexa_old(), and Pave::lire_front().
associer_zone()
void Frontiere::associer_zone (const Zone & une_zone)
Associe la frontiere a la zone dont elle depend.
Definition at line 85 of file Frontiere.cpp.
{
  la_zone=une_zone;
  les_faces.associer_zone(une_zone);
}
References Faces::associer_zone(), la_zone, and les_faces.
Referenced by ajouter_joint(), ajouter_joints(), auto_build_joints(), build_frontier(), Zone::comprimer(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), DomaineCutter::construire_sommets_joints_ssdom(), TroisDto2D::extraire_2D(), MaillerParallel::interpreter(), Lire_Ideas::interpreter_(), and Pave::lire_front().
creer_tableau_faces()
void Frontiere::creer_tableau_faces (Array_base & v, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Cree un tableau ayant une "ligne" par face de cette frontiere
Voir MD_Vector_tools::creer_tableau_distribue()
Definition at line 317 of file Frontiere.cpp.
{
  const MD_Vector& md = les_faces.les_sommets().get_md_vector();
  MD_Vector_tools::creer_tableau_distribue(md, v, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), TRUSTVect< _TYPE_ >::get_md_vector(), les_faces, and Faces::les_sommets().
Referenced by Echange_interne_global_impose::completer(), Echange_contact_VDF::initialiser(), and Champ_front_var::initialiser().
dimensionner()
void Frontiere::dimensionner (int i) inline
Dimensionne la frontiere, i.e. fixe
son nombre de faces.
Definition at line 128 of file Frontiere.h.
{
  les_faces.dimensionner(i);
}
References Faces::dimensionner(), and les_faces.
Referenced by ExtrudeBord::extruder_hexa_old(), and Pave::lire_front().
face_virt()
int Frontiere::face_virt (int i) const inline
Definition at line 196 of file Frontiere.h.
{
  return faces_virt[i];
}
References faces_virt.
Referenced by Periodique::completer().
faces() [1/2]
Faces & Frontiere::faces () inline
Renvoie les faces de la frontiere.
Returns
Faces&
Signification: les faces de la frontiere
Contraintes:
Definition at line 187 of file Frontiere.h.
{
  return les_faces;
}
References les_faces.
faces() [2/2]
const Faces & Frontiere::faces () const inline
Renvoie les faces de la frontiere<br>(version const)
Returns
Faces&
Signification: les faces de la frontiere
Contraintes: reference constante
Definition at line 168 of file Frontiere.h.
{
  return les_faces;
}
References les_faces.
Referenced by add(), BlocData::add_faces(), Joint::ajouter_faces(), auto_build_joints(), Ch_front_input::buildSommetsFaces(), Champ_front_recyclage::calcul_moyenne_recyclee(), calculer_elements_voisins_bords(), Partitionneur_base::calculer_graphe_connexions_periodiques(), calculer_liste_complete_aretes_joint(), calculer_liste_complete_sommets_joint(), Operateur_base::calculer_pour_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Reordonner_faces_periodiques::check_faces_periodiques(), Reordonner_faces_periodiques::chercher_direction_perio(), Champ_Generique_Extraction::completer(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Zone::correct_type_of_borders_after_merge(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), Faces_builder::creer_faces_frontiere(), DecoupeBord::Decouper(), Joint::dimensionner(), Zone_VF::discretiser(), Postraiter_domaine::ecrire(), Equation_base::ecrire_fichier_xyz(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), ExtrudeBord::extruder_bord(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), find_joint_faces(), Ch_front_input::getTemplate(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Lire_Ideas::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Scatter::lire_domaine(), Champ_front_synt::mettre_a_jour(), NettoieNoeuds::nettoie(), OrienteFacesBord::oriente_faces_bord(), Raffiner_Simplexes::refine_domain(), RegroupeBord::regroupe_bord(), Remove_elem::Remove_elem_(), Champ_front_MED::remplir_tab(), renum(), Scatter::reordonner_faces_de_joint(), Raccord_distant_homogene::trace_elem_distant(), and trace_elem_local().
fixer_num_premiere_face()
void Frontiere::fixer_num_premiere_face (int i) inline
Definition at line 205 of file Frontiere.h.
{
  num_premiere_face_ = i;
}
References num_premiere_face_.
Referenced by Faces_builder::creer_faces_frontiere(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), and reordonner_vdf().
get_aire()
const double & Frontiere::get_aire () const inline
Definition at line 64 of file Frontiere.h.
  {
    return aire_;
  };
References aire_.
Referenced by Terme_Source_Canal_perio::completer().
get_faces_virt() [1/2]
ArrOfInt & Frontiere::get_faces_virt () inline
Definition at line 215 of file Frontiere.h.
{
  return faces_virt;
}
References faces_virt.
get_faces_virt() [2/2]
const ArrOfInt & Frontiere::get_faces_virt () const inline
Definition at line 210 of file Frontiere.h.
{
  return faces_virt;
}
References faces_virt.
Referenced by Periodique::completer(), Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle(), find_cl_face(), Zone::init_faces_virt_bord(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_local_face(), and Zone_Cl_VEF::remplir_volumes_entrelaces_Cl().
get_info()
const Type_info * Frontiere::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Joint, Raccord_base, Raccord_local, Raccord_distant, Raccord_local_homogene, and Raccord_distant_homogene.
Definition at line 20 of file Frontiere.cpp.
info()
const Type_info * Frontiere::info () static
Definition at line 20 of file Frontiere.cpp.
le_nom()
const Nom & Frontiere::le_nom () const inline override virtual
Renvoie le nom de la frontiere.
Returns
Nom&
Signification: le nom de la frontiere
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 148 of file Frontiere.h.
{
  return nom;
}
References nom.
Referenced by build_frontier(), calculer_elements_voisins_bords(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Echange_contact_VDF::calculer_h_autre_pb(), Echange_contact_Correlation_VDF::calculer_h_mon_pb(), Reordonner_faces_periodiques::check_faces_periodiques(), Partitionneur_Tranche::chercher_direction_perio(), Equation_base::completer(), Champ_front_calc::completer(), Periodique::completer(), Champ_front_contact_VEF::completer(), Joints::comprimer(), Zone::comprimer(), Zone::comprimer_joints(), Zone_Cl_dis_base::condition_limite_de_la_frontiere(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Zone::correct_type_of_borders_after_merge(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Faces_builder::creer_faces_frontiere(), Domaine::creer_mes_domaines_frontieres(), DecoupeBord::Decouper(), Op_Div_VEFP1B_Elem::degres_liberte(), Postraiter_domaine::ecrire(), Equation_base::ecrire_fichier_xyz(), TroisDto2D::extraire_2D(), ExtrudeParoi::extrude(), ExtrudeBord::extruder_hexa_old(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Raccord_distant_homogene::initialise(), Echange_contact_VDF::initialiser(), Champ_front_lu::initialiser(), Champ_front_recyclage::initialiser(), RegroupeBord::interpreter_(), Frontiere_dis_base::le_nom(), Mod_turb_hyd_base::lire_motcle_non_standard(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), RegroupeBord::rassemble_bords(), RegroupeBord::regroupe_bord(), and Champ_front_contact_VEF::trace_face_raccord().
les_sommets_des_faces() [1/2]
IntTab & Frontiere::les_sommets_des_faces ()
Renvoie les sommets des faces de la frontiere.
Returns
IntTab&
Signification: le tableau contenant les numeros des
sommets des faces de la frontiere
Contraintes:
Definition at line 189 of file Frontiere.cpp.
{
  return les_faces.les_sommets();
}
References les_faces, and Faces::les_sommets().
Referenced by build_frontier(), calculer_elements_voisins_bords(), Joints::comprimer(), Scatter::corriger_espace_distant_elements_perio(), TroisDto2D::extraire_2D(), ExtrudeParoi::extrude(), ExtrudeBord::extruder_hexa_old(), Zone::init_faces_virt_bord(), Reordonner_faces_periodiques::renum_som_perio(), and trace_som_local().
les_sommets_des_faces() [2/2]
const IntTab & Frontiere::les_sommets_des_faces () const
Renvoie les sommets des faces de la frontiere.
Returns
IntTab&
Signification: le tableau contenant les numeros des
sommets des faces de la frontiere
Contraintes:
Definition at line 208 of file Frontiere.cpp.
{
  return les_faces.les_sommets();
}
References les_faces, and Faces::les_sommets().
nb_faces()
int Frontiere::nb_faces () const inline
Renvoie le nombre de faces de la frontiere.
Returns
int
Signification: le nombre de faces de la frontiere
Contraintes:
Definition at line 107 of file Frontiere.h.
{
  return les_faces.nb_faces();
}
References les_faces, and Faces::nb_faces().
Referenced by Op_Div_VEFP1B_Elem::ajouter_som(), Traitement_particulier_NS_EC::calculer_Ec(), calculer_elements_voisins_bords(), Partitionneur_base::calculer_graphe_connexions_periodiques(), Echange_contact_VDF::calculer_h_autre_pb(), Reordonner_faces_periodiques::chercher_direction_perio(), Periodique::completer(), Champ_Generique_Extraction::completer(), Zone_Cl_VDF::completer(), Joints::comprimer(), Zone_Cl_dis_base::condition_limite_de_la_face_reelle(), Zone_Cl_dis_base::condition_limite_de_la_face_virtuelle(), Scatter::corriger_espace_distant_elements_perio(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Faces_builder::creer_faces_reeles(), Zone_VF::discretiser(), Equation_base::ecrire_fichier_xyz(), DomaineCutter::ecrire_zones(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), ExtrudeBord::extruder_hexa_old(), find_cl_face(), Champ_Generique_Extraction::get_champ(), Zone::init_faces_virt_bord(), Raccord_distant_homogene::initialise(), Echange_contact_VDF::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Champ_front_contact_VEF::initialiser(), Distanceparoi::interpreter_(), Zone_Cl_dis_base::la_cl_de_la_face(), Scatter::lire_domaine(), Champ_front_bruite::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_contact_VEF::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), RegroupeBord::regroupe_bord(), Champ_front_contact_VEF::remplir_connect_bords(), Zone_VF::remplir_face_numero_bord(), Champ_front_MED::remplir_tab(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Zone_VEF::reordonner(), reordonner_vdf(), trace_elem_local(), Raccord_distant_homogene::trace_face_distant(), trace_face_local(), trace_som_local(), Champ_front_base::valeurs_face(), and Champ_front_contact_VEF::verifier_scalaire_bord().
nb_faces_virt()
int Frontiere::nb_faces_virt () const inline
Definition at line 192 of file Frontiere.h.
{
  return faces_virt.size_array();
}
References faces_virt, and TRUSTArray< _TYPE_ >::size_array().
nommer()
void Frontiere::nommer (const Nom & name) override virtual
Donne un nom a la frontiere.
Reimplemented from Objet_U.
Definition at line 105 of file Frontiere.cpp.
{
  nom=name;
}
References nom.
Referenced by ajouter_joint(), ajouter_joints(), auto_build_joints(), build_frontier(), Joints::comprimer(), Extruder_en3::construire_bords(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), DomaineCutter::construire_sommets_joints_ssdom(), DecoupeBord::Decouper(), TroisDto2D::extraire_2D(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), ExtrudeBord::extruder_hexa_old(), Create_domain_from_sous_zone::interpreter_(), Extraire_domaine::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Pave::lire_front(), RegroupeBord::regroupe_bord(), and Remove_elem::Remove_elem_().
num_premiere_face()
int Frontiere::num_premiere_face () const inline
Definition at line 201 of file Frontiere.h.
{
  return num_premiere_face_ ;
}
References num_premiere_face_.
Referenced by Traitement_particulier_NS_EC::calculer_Ec(), Periodique::completer(), Champ_Generique_Extraction::completer(), Zone_Cl_VDF::completer(), Zone_Cl_dis_base::condition_limite_de_la_face_reelle(), Faces_builder::creer_faces_reeles(), Zone_VF::discretiser(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), find_cl_face(), Zone::init_faces_virt_bord(), Raccord_distant_homogene::initialise(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Distanceparoi::interpreter_(), Zone_Cl_dis_base::la_cl_de_la_face(), Ch_front_Vortex::mettre_a_jour(), Front_VF::num_premiere_face(), Zone_VF::remplir_face_numero_bord(), Raccord_distant_homogene::trace_face_distant(), trace_face_local(), and Frontiere_ouverte_rho_u_impose::val_imp_au_temps().
printOn()
Sortie & Frontiere::printOn (Sortie & os) const override protected virtual
Ecrit la frontiere sur un flot de sortie.
On ecrit:
le nom de la frontiere
les faces.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Joint, Raccord_base, Raccord_local, Raccord_distant, Raccord_local_homogene, and Raccord_distant_homogene.
Definition at line 65 of file Frontiere.cpp.
{
  os << nom << finl;
  return os << les_faces;
}
References finl, les_faces, and nom.
Referenced by Bord::printOn(), Faces_Interne::printOn(), Joint::printOn(), and Raccord_base::printOn().
readOn()
Entree & Frontiere::readOn (Entree & is) override protected virtual
Lit les specification d'une frontiere
a partir d'un flot d'entree.
On lit:
le nom
les faces.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Joint, Raccord_base, Raccord_local, Raccord_distant, Raccord_local_homogene, and Raccord_distant_homogene.
Definition at line 41 of file Frontiere.cpp.
{
  is >> nom;
  return is >> les_faces;
}
References les_faces, and nom.
Referenced by Bord::readOn(), Faces_Interne::readOn(), Joint::readOn(), and Raccord_base::readOn().
renum()
void Frontiere::renum (const IntVect & Les_Nums)
Renumerote les noeuds (sommets) des faces.
Le noeud de numero k devient le noeud de numero Les_Nums[k].
Definition at line 229 of file Frontiere.cpp.
{
  IntTab& les_sommets=faces().les_sommets();
  for(int i=0; i<les_sommets.dimension(0); i++)
    for(int j=0; j<les_sommets.dimension(1); j++)
      les_sommets(i,j)=Les_Nums[les_sommets(i,j)];
}
References TRUSTTab< _TYPE_ >::dimension(), faces(), and Faces::les_sommets().
self_cast() [1/2]
const Frontiere & Frontiere::self_cast (const Objet_U & r) static
Definition at line 20 of file Frontiere.cpp.
self_cast() [2/2]
Frontiere & Frontiere::self_cast (Objet_U & r) static
Definition at line 20 of file Frontiere.cpp.
set_aire()
void Frontiere::set_aire (double & aire) inline
Definition at line 68 of file Frontiere.h.
  {
    aire_ = aire;
  };
References aire_.
trace_elem_distant()
void Frontiere::trace_elem_distant (const DoubleTab & , DoubleTab &) const virtual
Reimplemented in Raccord_local_homogene, and Raccord_distant_homogene.
Definition at line 406 of file Frontiere.cpp.
{
  Cerr<<que_suis_je()<<"::trace_elem_distant not implemented "<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by calculer_h_distant(), and Champ_implementation_P0::trace().
trace_elem_local()
void Frontiere::trace_elem_local (const DoubleTab & y, DoubleTab & x) const virtual
Renvoie la trace sur la frontiere du tableau aux elements y.
Definition at line 325 of file Frontiere.cpp.
{
  const int size = nb_faces(), nb_compo_ = y.line_size();
// On dimensionne x si ce n'est pas fait
  if (x.size_array() == 0 && size != 0)
    x.resize(size, nb_compo_);
  else if (x.dimension(0) != size || nb_compo_ != x.line_size())
    {
      Cerr << "Call to Frontiere::trace_elem with a DoubleTab x not located on boundary faces or don't have the same number of components" << finl;
      Process::exit();
    }
  for (int i = 0; i < size; i++)
    {
      int elem = faces().voisin(i, 0);
      if (elem == -1)
        elem = faces().voisin(i, 1);
      for(int j = 0; j < nb_compo_; j++)
        x(i, j) = y(elem, j);
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), faces(), finl, TRUSTVect< _TYPE_ >::line_size(), nb_faces(), TRUSTTab< _TYPE_ >::resize(), TRUSTArray< _TYPE_ >::size_array(), and Faces::voisin().
Referenced by Champ_implementation_P0::trace(), and Raccord_local_homogene::trace_elem_distant().
trace_face_distant() [1/2]
void Frontiere::trace_face_distant (const DoubleTab & , DoubleTab &) const virtual
Reimplemented in Raccord_local_homogene, and Raccord_distant_homogene.
Definition at line 411 of file Frontiere.cpp.
{
  Cerr<<que_suis_je()<<"::trace_face_distant not implemented "<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by calculer_h_distant(), Champ_P1NC_implementation::trace(), Champ_Q1NC_impl::trace(), Champ_Elem_PolyMAC::trace(), and Champ_front_contact_VEF::trace_face_raccord().
trace_face_distant() [2/2]
void Frontiere::trace_face_distant (const DoubleVect & , DoubleVect &) const virtual
Reimplemented in Raccord_local_homogene, and Raccord_distant_homogene.
Definition at line 416 of file Frontiere.cpp.
{
  Cerr<<que_suis_je()<<"::trace_face_distant not implemented "<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
trace_face_local() [1/2]
void Frontiere::trace_face_local (const DoubleTab & y, DoubleTab & x) const virtual
Renvoie la trace sur la frontiere du tableau aux faces y.
Definition at line 388 of file Frontiere.cpp.
{
  int size = nb_faces(), M = y.line_size(), N = x.line_size();
  assert(x.dimension(0)==size);
  for (int i = 0; i < size; i++)
    {
      int face = num_premiere_face() + i;
      for (int n = 0; n < N; n++)
        x.addr()[N * i + n] = y.addr()[M * face + n];
    }
}
References TRUSTArray< _TYPE_ >::addr(), TRUSTTab< _TYPE_ >::dimension(), TRUSTVect< _TYPE_ >::line_size(), nb_faces(), and num_premiere_face().
Referenced by Champ_P1NC_implementation::trace(), Champ_Q1NC_impl::trace(), Champ_Elem_PolyMAC::trace(), and Raccord_local_homogene::trace_face_distant().
trace_face_local() [2/2]
void Frontiere::trace_face_local (const DoubleVect & y, DoubleVect & x) const virtual
Renvoie la trace sur la frontiere du tableau aux faces y.
Definition at line 379 of file Frontiere.cpp.
{
  Cerr << "Frontiere::trace_face(const DoubleVect& y, DoubleVect& x) const" << finl;
  Cerr << "not coded yet." << finl;
  Process::exit();
}
References Cerr, Process::exit(), and finl.
trace_som_distant()
void Frontiere::trace_som_distant (const DoubleTab & , DoubleTab &) const virtual
Definition at line 400 of file Frontiere.cpp.
{
  Cerr<<que_suis_je()<<"::trace_som_distant not implemented "<<finl;
  Process::exit();
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Champ_implementation_sommet_base::trace().
trace_som_local()
void Frontiere::trace_som_local (const DoubleTab & y, DoubleTab & x) const virtual
Renvoie la trace sur la frontiere du tableau aux noeuds y.
Definition at line 350 of file Frontiere.cpp.
{
  const IntTab& som_face = les_sommets_des_faces();
  const int size = nb_faces(), nb_compo_ = y.line_size();
  const int nsomfa = som_face.dimension(1);
// On dimensionne x si ce n'est pas fait
  if (x.size_array() == 0 && size != 0)
    x.resize(size, nb_compo_);
  else if (x.dimension(0) != size || nb_compo_ != x.line_size())
    {
      Cerr << "Call to Frontiere::trace_elem with a DoubleTab x not located on boundary faces or don't have the same number of components" << finl;
      Process::exit();
    }
  for (int i = 0; i < size; i++)
    for(int j=0; j<nb_compo_; j++)
      {
        double s = 0.;
        for (int isom = 0; isom < nsomfa; isom++)
          s += y(som_face(i, isom), j);
        s /= nsomfa;
        x(i, j) = s;
      }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Process::exit(), finl, les_sommets_des_faces(), TRUSTVect< _TYPE_ >::line_size(), nb_faces(), TRUSTTab< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Champ_implementation_sommet_base::trace().
typer_faces() [1/2]
void Frontiere::typer_faces (const Motcle & typ)
Type les faces de la frontiere.
Definition at line 148 of file Frontiere.cpp.
{
  les_faces.typer(typ);
}
References les_faces, and Faces::typer().
Referenced by build_frontier(), DomaineCutter::construire_faces_joints_ssdom(), TroisDto2D::extraire_2D(), ExtrudeBord::extruder_hexa_old(), Extraire_domaine::interpreter_(), Pave::lire_front(), and Remove_elem::Remove_elem_().
typer_faces() [2/2]
void Frontiere::typer_faces (const Type_Face & typ)
Type les faces de la frontiere.
Definition at line 169 of file Frontiere.cpp.
{
  les_faces.typer(typ);
}
References les_faces, and Faces::typer().
zone() [1/2]
Zone & Frontiere::zone ()
Renvoie la Zone associee a la frontiere.
Returns
Zone&
Signification: la zone associee a la frontiere
Contraintes:
Definition at line 271 of file Frontiere.cpp.
{
  return la_zone.valeur();
}
References la_zone, and Ref_Zone::valeur().
zone() [2/2]
const Zone & Frontiere::zone () const
Renvoie la Zone associee a la frontiere.
(version const)
Returns
Zone&
Signification: la zone associee a la frontiere
Contraintes: reference constante
Definition at line 252 of file Frontiere.cpp.
{
  return la_zone.valeur();
}
References la_zone, and Ref_Zone::valeur().
Referenced by calculer_liste_complete_aretes_joint(), Reordonner_faces_periodiques::check_faces_periodiques(), Periodique::completer(), Zone::comprimer(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), and Champ_front_MED::remplir_tab().
Member Data Documentation
aire_
double Frontiere::aire_ private
Definition at line 89 of file Frontiere.h.
Referenced by get_aire(), and set_aire().
faces_virt
ArrOfInt Frontiere::faces_virt private
Definition at line 87 of file Frontiere.h.
Referenced by face_virt(), get_faces_virt(), and nb_faces_virt().
info_obj
const Type_info Frontiere::info_obj static
Definition at line 35 of file Frontiere.h.
la_zone
Ref_Zone Frontiere::la_zone private
Definition at line 86 of file Frontiere.h.
Referenced by associer_zone(), and zone().
les_faces
Faces Frontiere::les_faces private
Definition at line 85 of file Frontiere.h.
Referenced by add(), ajouter_faces(), associer_zone(), creer_tableau_faces(), dimensionner(), faces(), les_sommets_des_faces(), nb_faces(), printOn(), readOn(), and typer_faces().
nom
Nom Frontiere::nom private
Definition at line 84 of file Frontiere.h.
Referenced by le_nom(), nommer(), printOn(), and readOn().
num_premiere_face_
int Frontiere::num_premiere_face_ private
Definition at line 88 of file Frontiere.h.
Referenced by fixer_num_premiere_face(), and num_premiere_face().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Frontiere.h
src/Kernel/Geometrie/Frontiere.cpp