TRUST: Champ_Face_CoviMAC Class Reference
Champ_Face_CoviMAC Class Reference
: class Champ_Face_CoviMAC
Champ correspondant a une inconnue decrite par ses tangentes aux faces duales (ligne amont-aval, type vitesse)
Les flux aux faces sont accessibles par les methodes valeurs_normales(), avec synchro automatique
Degres de libertes : composantes tangentielles aux faces duales
#include <Champ_Face_CoviMAC.h>
Public Member Functions
Champ_Face_CoviMAC ()
~Champ_Face_CoviMAC ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int fixer_nb_valeurs_nodales (int n)
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const
NE FAIT RIEN
Methode a surcharger.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
DoubleVect & calcul_S_barre_sans_contrib_paroi (const DoubleTab &vitesse, DoubleVect &SMA_barre) const
DoubleVect & calcul_S_barre (const DoubleTab &vitesse, DoubleVect &SMA_barre) const
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Champ_base & affecter_ (const Champ_base &)
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
const Zone_VF & zone_vf () const
const IntTab & fcl () const
void init_gve () const
void update_ve (DoubleTab &val) const
void init_ve2 () const
void update_ve2 (DoubleTab &val, int incr=0) const
void interp_gve (const DoubleTab &inco, DoubleTab &vals) const
double v_norm (const DoubleTab &val, const DoubleTab &val_f, int e, int f, int k, int l, double *v_ext, double *dnv) const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Face_CoviMAC & self_cast (Objet_U &)
static const Champ_Face_CoviMAC & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
IntTab ve2d
IntTab ve2j
IntTab ve2bj
DoubleTab ve2c
DoubleTab ve2bc
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
virtual Entree & readOn (Entree &)
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
virtual Champ_base & le_champ (void)
virtual const Champ_base & le_champ (void) const
void init_fcl () const
Protected Attributes
Ref_Zone_VF ref_zone_vf_
IntTab fcl_
int fcl_init_ = 0
Detailed Description
: class Champ_Face_CoviMAC
Champ correspondant a une inconnue decrite par ses tangentes aux faces duales (ligne amont-aval, type vitesse)
Les flux aux faces sont accessibles par les methodes valeurs_normales(), avec synchro automatique
Degres de libertes : composantes tangentielles aux faces duales
Definition at line 42 of file Champ_Face_CoviMAC.h.
Constructor & Destructor Documentation
Champ_Face_CoviMAC::Champ_Face_CoviMAC ()
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
Champ_Face_CoviMAC::~Champ_Face_CoviMAC ()
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
Member Function Documentation
Champ_base & Champ_Face_CoviMAC::affecter_ (const Champ_base & ch) [virtual]
Affectation d'un Champ generique (Champ_base) dans
un champ inconnue.
Returns:
Champ_base&
Signification: le resultat de l'affectation (*this)
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 101 of file Champ_Face_CoviMAC.cpp.
References Objet_U::dimension, DoubleTab::dimension_tot(), DoubleVect::echange_espace_virtuel(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Champ_Inc_base::les_valeurs, DoubleVect::line_size(), Zone_VF::nb_faces_tot(), ref_cast, ref_zone_vf_, DoubleTab::resize(), sub_type, update_ve(), Ref_Zone_VF::valeur(), Champ_base::valeur_aux(), Champ_Proto::valeurs(), Champ_Inc_base::valeurs(), and Zone_VF::xv().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,ref_zone_vf_.valeur());
  const DoubleVect& fs = zone.face_surfaces();
  const DoubleTab& nf = zone.face_normales(), &xv = zone.xv();
  DoubleTab& val = valeurs(), eval;
  int f, n, N = val.line_size(), d, D = dimension, unif = sub_type(Champ_Uniforme, ch);
  if (unif) eval = ch.valeurs();
  else eval.resize(val.dimension_tot(0), N * D), ch.valeur_aux(xv,eval);
  for (f = 0; f < zone.nb_faces_tot(); f++) for (d = 0; d < D; d++) for (n = 0; n < N; n++)
        val(f, n) += eval(unif ? 0 : f, N * d + n) * nf(f, d) / fs(f);
  update_ve(val);
// copie dans toutes les cases
  valeurs().echange_espace_virtuel();
  for(int i=1; i<les_valeurs->nb_cases(); i++) les_valeurs[i].valeurs() = valeurs();
  return *this;
}
void Champ_Face_CoviMAC::associer_zone_dis_base (const Zone_dis_base & z_dis) [virtual]
Reimplemented from Champ_base.
Definition at line 69 of file Champ_Face_CoviMAC.cpp.
References ref_cast, and ref_zone_vf_.
{
  ref_zone_vf_=ref_cast(Zone_VF, z_dis);
}
DoubleVect & Champ_Face_CoviMAC::calcul_S_barre (const DoubleTab & vitesse, DoubleVect & SMA_barre) const
Definition at line 377 of file Champ_Face_CoviMAC.cpp.
References Process::abort().
Referenced by calcul_S_barre_sans_contrib_paroi().
{
  abort();
  return SMA_barre;
}
DoubleVect & Champ_Face_CoviMAC::calcul_S_barre_sans_contrib_paroi (const DoubleTab & vitesse, DoubleVect & SMA_barre) const
Definition at line 370 of file Champ_Face_CoviMAC.cpp.
References Process::abort(), and calcul_S_barre().
{
// avec contrib au bord pour l'instant...
  abort();
  return calcul_S_barre(vitesse, SMA_barre);
}
Objet_U * Champ_Face_CoviMAC::cree_instance () [static]
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
int Champ_Face_CoviMAC::duplique () const [virtual]
Implements Champ_Inc_base.
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
const IntTab& Champ_Face_CoviMAC::fcl () const [inline]
Definition at line 88 of file Champ_Face_CoviMAC.h.
References fcl_, fcl_init_, and init_fcl().
Referenced by Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab(), and Op_Grad_CoviMAC_Face::mu_f().
  {
    if (!fcl_init_) init_fcl();
    return fcl_;
  }
int Champ_Face_CoviMAC::fixer_nb_valeurs_nodales (int n) [virtual]
Reimplemented from Champ_Inc_base.
Definition at line 74 of file Champ_Face_CoviMAC.cpp.
References Champ_Inc_base::creer_tableau_distribue(), Objet_U::dimension, Zone_CoviMAC::mdv_ch_face, Field_base::nb_compo_, Zone_dis_base::nb_elem(), Zone_VF::nb_faces(), ref_cast, and zone_dis_base().
{
// j'utilise le meme genre de code que dans Champ_Fonc_P0_base
// sauf que je recupere le nombre de faces au lieu du nombre d'elements
//
// je suis tout de meme etonne du code utilise dans
// Champ_Fonc_P0_base::fixer_nb_valeurs_nodales()
// pour recuperer la zone discrete...
  const Champ_Inc_base& self = ref_cast(Champ_Inc_base, *this);
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,self.zone_dis_base());
  assert(n == zone.nb_faces() + nb_compo_ * zone.nb_elem());
// Probleme: nb_comp vaut dimension mais on ne veut qu'une dimension !!!
// HACK :
  int old_nb_compo = nb_compo_;
  nb_compo_ /= dimension;
  /* variables : valeurs normales aux faces, puis valeurs aux elements par blocs -> pour que line_size() marche */
  creer_tableau_distribue(zone.mdv_ch_face);
  nb_compo_ = old_nb_compo;
  return n;
}
const Type_info * Champ_Face_CoviMAC::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
const Type_info * Champ_Face_CoviMAC::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
void Champ_Face_CoviMAC::init_fcl () const [protected]
Definition at line 134 of file Champ_Face_CoviMAC.cpp.
References Cerr, Process::exit(), fcl_, fcl_init_, finl, Zone_Cl_dis::les_conditions_limites(), Front_VF::nb_faces_tot(), Zone_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, IntTab::resize(), vect_impl::size(), sub_type, valeur(), Champ_Inc_base::zone_Cl_dis(), and zone_vf().
Referenced by fcl(), init_ve2(), and update_ve2().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  const Conds_lim& cls = zone_Cl_dis().les_conditions_limites();
  int i, f, n;
  fcl_.resize(zone.nb_faces_tot(), 3);
  for (n = 0; n < cls.size(); n++)
    {
      const Front_VF& fvf = ref_cast(Front_VF, cls[n].frontiere_dis());
      int idx = sub_type(Neumann, cls[n].valeur()) + sub_type(Neumann_homogene, cls[n].valeur())
                + 2 * sub_type(Symetrie, cls[n].valeur())
                + 3 * sub_type(Dirichlet, cls[n].valeur()) + 4 * sub_type(Dirichlet_homogene, cls[n].valeur());
      if (!idx) Cerr << "Champ_Face_CoviMAC : CL non codee rencontree!" << finl, Process::exit();
      for (i = 0; i < fvf.nb_faces_tot(); i++)
        f = fvf.num_face(i), fcl_(f, 0) = idx, fcl_(f, 1) = n, fcl_(f, 2) = i;
    }
  fcl_init_ = 1;
}
void Champ_Face_CoviMAC::init_gve () const
void Champ_Face_CoviMAC::init_ve2 () const
< v_i[{f, -1 (interne) ou composante }] = indice
< v_i[i_v[f]] = f
Definition at line 169 of file Champ_Face_CoviMAC.cpp.
References Cerr, Objet_U::dimension, IntTab::dimension(), Zone_CoviMAC::dot(), Zone_VF::elem_faces(), Process::exit(), Zone_CoviMAC::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), fcl_, finl, init_fcl(), Zone_CoviMAC::init_ve(), Zone::les_elems(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), Zone::nb_som(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, IntTab::resize(), ArrOfDouble::set_smart_resize(), ArrOfInt::set_smart_resize(), ve2bc, ve2bj, ve2c, ve2d, ve2j, Zone_VF::xp(), Zone_VF::xv(), Zone_dis_base::zone(), and zone_vf().
Referenced by update_ve2().
{
#ifdef _COMPILE_AVEC_PGCC
// PL ToDo: rewrite code
  Cerr << "Internal error with nvc++: Internal error: read_memory_region: not all expected entries were read." << finl;
  Process::exit();
#else
  if (ve2d.dimension(0)) return; //deja initialise
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem(), &fs = zone.face_surfaces();
  const DoubleTab& xp = zone.xp(), &xv = zone.xv(), &nf = zone.face_normales();
  const IntTab& f_e = zone.face_voisins(), &e_f = zone.elem_faces(), &e_s = zone.zone().les_elems(), &f_s = zone.face_sommets();
  int i, j, jb, k, e, f, s, d, db, D = dimension, nc, nl = D * (D + 1), nw, infoo=0, un = 1, rank;
  double eps = 1e-8;
  const double *xf;
  zone.init_ve(), init_fcl();
// position des points aux faces de bord : CG si interne ou Dirichlet, projection si Neumann
  DoubleTrav xfb(zone.nb_faces_tot(), D), ve2, ve2i, A, B, P, W(1);
  IntTrav pvt;
  ve2.set_smart_resize(1), A.set_smart_resize(1), B.set_smart_resize(1), P.set_smart_resize(1), W.set_smart_resize(1), pvt.set_smart_resize(1);
  for (f = 0; f < zone.nb_faces_tot(); f++) if (fcl_(f, 0) == 1 || fcl_(f, 0) == 2) //Neumann / Symetrie
      {
        double scal = zone.dot(&xv(f, 0), &nf(f, 0), &xp(e = f_e(f, 0), 0)) / (fs(f) * fs(f));
        for (d = 0; d < D; d++) xfb(f, d) = xp(e, d) + scal * nf(f, d);
      }
    else if (fcl_(f, 0)) for (d = 0; d < D; d++) xfb(f, d) = xv(f, d); //Dirichlet
  /* connectivites som-elem et elem-elem */
  std::vector<std::set<int>> s_f(zone.zone().nb_som()), e_s_f(zone.nb_elem());
  for (f = 0; f < zone.nb_faces_tot(); f++) for (i = 0; i < f_s.dimension(1) && (s = f_s(f, i)) >= 0; i++)
      if (s < zone.zone().nb_som()) s_f[s].insert(f);
  for (e = 0; e < zone.nb_elem(); e++) for (i = 0; i < e_s.dimension(1) && (s = e_s(e, i)) >= 0; i++)
      for (auto &&fa : s_f[s]) e_s_f[e].insert(fa);
  ve2d.resize(1, 2), ve2d.set_smart_resize(1), ve2j.set_smart_resize(1), ve2bj.resize(0, 2), ve2bj.set_smart_resize(1);
  ve2c.set_smart_resize(1), ve2bc.set_smart_resize(1);
  std::map<std::array<int, 2>, int> v_i; //!< v_i[{f, -1 (interne) ou composante }] = indice
  std::vector<std::array<int, 2>> i_v; //!< v_i[i_v[f]] = f
  for (e = 0; e < zone.nb_elem(); e++, v_i.clear(), i_v.clear())
    {
      /* stencil : faces de l'element et de ses voisins par som-elem + toutes composantes a ses faces de bord */
      for (auto &&fa : e_s_f[e]) if (!v_i.count({{ fa, -1 }})) v_i[ {{fa, -1}}] = i_v.size(), i_v.push_back({{fa, -1}});
      for (i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++) if (fcl_(f, 0)) for (d = 0; d < D; d++)
            v_i[ {{f, d }}] = i_v.size(), i_v.push_back({{f, d}});
      /* coeffs de l'interpolation d'ordre 1, ponderations (comme dans Zone_CoviMAC::{e,f}grad)  */
      ve2.resize(nc = i_v.size(), D), A.resize(nc, nl), B.resize(nc), P.resize(nc), pvt.resize(nc);
      for (ve2 = 0, i = zone.ved(e); i < zone.ved(e + 1); i++) for (j = v_i.at({{zone.vej(i), -1}}), d = 0; d < D; d++)
      ve2(j, d) += zone.vec(i, d);
      for (i = 0; i < nc; i++) f = i_v[i][0], xf = i_v[i][1] < 0 ? &xv(f, 0) : &xfb(f, 0), P(i) = 1. / sqrt(zone.dot(xf, xf, &xp(e, 0), &xp(e, 0)));
      /* par composante : correction pour etre d'ordre 2 */
      for (d = 0; d < D; d++)
        {
          /* systeme A.x = b */
          for (B = 0, pvt = 0, i = 0; i < nc; i++) for (f = i_v[i][0], db = i_v[i][1], xf = db < 0 ? &xv(f, 0) : &xfb(f, 0), j = 0, jb = 0; j < D; j++) for (k = 0; k <= D; k++, jb++)
                {
                  double fac = (db < 0 ? nf(f, j) / fs(f) : (db == j)) * (k < D ? xf[k] - xp(e, k) : 1);
                  A(i, jb) = fac * P(i);
                  if (k < D) B(jb) -= fac * ve2(i, d); //erreur de l'interp d'ordre 1 a corriger
                }
          /* x de norme L2 minimale par dgels */
          nw = -1,             F77NAME(dgelsy)(&nl, &nc, &un, &A(0, 0), &nl, &B(0), &nc, &pvt(0), &eps, &rank, &W(0), &nw, &infoo);
          W.resize(nw = W(0)), F77NAME(dgelsy)(&nl, &nc, &un, &A(0, 0), &nl, &B(0), &nc, &pvt(0), &eps, &rank, &W(0), &nw, &infoo);
          assert(infoo == 0);
          /* ajout dans ve2 */
          for (i = 0; i < nc; i++) ve2(i, d) += P(i) * B(i);
        }
      /* implicitation des CLs de Neumann / Symetrie */
      Matrice33 M(1, 0, 0, 0, 1, 0, 0, 0, 1), iM;
      for (i = 0; i < nc; i++) if (i_v[i][1] >= 0 && fcl_(i_v[i][0], 0) < 2) for (j = 0; j < D; j++)
            M(j, i_v[i][1]) -= ve2(i, j);
      Matrice33::inverse(M, iM);
      for (ve2i.resize(nc, D), i = 0; i < nc; i++) for (j = 0; j < D; j++) for (ve2i(i, j) = 0, k = 0; k < D; k++)
            ve2i(i, j) += iM(j, k) * ve2(i, k);
      /* stockage */
      for (d = 0; d < D; d++, ve2d.append_line(ve2c.size(), ve2bc.size())) for (i = 0; i < nc; i++) if (dabs(ve2i(i, d)) > 1e-6 && (i_v[i][1] < 0 || fcl_(i_v[i][0], 0) == 3))
            {
              i_v[i][1] < 0 ? ve2j.append_line(i_v[i][0])  : ve2bj.append_line(i_v[i][0], i_v[i][1]);
              (i_v[i][1] < 0 ? &ve2c : &ve2bc)->append_line(ve2i(i, d) * pf(i_v[i][0]) / pe(e));
            }
    }
  CRIMP(ve2d), CRIMP(ve2j), CRIMP(ve2bj), CRIMP(ve2c), CRIMP(ve2bc);
#endif
}
void Champ_Face_CoviMAC::interp_gve (const DoubleTab & inco, DoubleTab & vals) const
Definition at line 282 of file Champ_Face_CoviMAC.cpp.
References Process::abort().
{
  abort();
}
Champ_base & Champ_Face_CoviMAC::le_champ (void) [protected, virtual]
Definition at line 59 of file Champ_Face_CoviMAC.cpp.
Referenced by trace(), valeur_aux_elems(), and valeur_aux_faces().
{
  return *this;
}
const Champ_base & Champ_Face_CoviMAC::le_champ (void) const [protected, virtual]
Definition at line 64 of file Champ_Face_CoviMAC.cpp.
{
  return *this;
}
Sortie & Champ_Face_CoviMAC::printOn (Sortie & os) const [protected, virtual]
Surcharge Champ_base::printOn(Sortie&) const
Imprime le champ sur un flot de sortie.
Simple appel a Champ_base::printOn(Sortie&) const.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 48 of file Champ_Face_CoviMAC.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  os << que_suis_je() << " " << le_nom();
  return os;
}
Entree & Champ_Face_CoviMAC::readOn (Entree & is) [protected, virtual]
Lit un champ inconnue sur un flot d'entree.
Simple appel a Champ_base::readOn(Entree&)
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 54 of file Champ_Face_CoviMAC.cpp.
{
  return is;
}
DoubleTab & Champ_Face_CoviMAC::remplir_coord_noeuds (DoubleTab & positions) const [virtual]
Implements Champ_Inc_base.
Definition at line 327 of file Champ_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::remplir_coord_noeuds(positions);
}
int Champ_Face_CoviMAC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const [virtual]
NE FAIT RIEN
Methode a surcharger.
Returns:
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Inc_base.
Definition at line 334 of file Champ_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::remplir_coord_noeuds_et_polys(positions,polys);
}
Champ_Face_CoviMAC & Champ_Face_CoviMAC::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Inc_base.
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
const Champ_Face_CoviMAC & Champ_Face_CoviMAC::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Inc_base.
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
unsigned Champ_Face_CoviMAC::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 46 of file Champ_Face_CoviMAC.cpp.
DoubleTab & Champ_Face_CoviMAC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const [virtual]
voir Champ_base
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
Definition at line 383 of file Champ_Face_CoviMAC.cpp.
References Objet_U::dimension, Zone_VF::face_voisins(), le_champ(), Field_base::nb_comp(), Zone_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Zone_VF::nb_faces_tot(), Front_VF::num_premiere_face(), ref_cast, Champ_Inc_base::valeurs(), vectoriel, and zone_vf().
{
  assert(distant==0);
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  const bool vectoriel = (le_champ().nb_comp() > 1);
  const int dim = vectoriel ? dimension : 1, ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot();
  const Front_VF& fr_vf = ref_cast(Front_VF, fr);
  const IntTab& face_voisins = zone.face_voisins();
  const DoubleTab& val = valeurs(t);
  for (int i = 0; i < fr_vf.nb_faces(); i++)
    {
      const int face = fr_vf.num_premiere_face() + i, elem = face_voisins(face, 0);
      for (int d = 0; d < dim; d++) x(i, d) = val(vectoriel ? nf_tot + ne_tot * d + elem : face);
    }
  return x;
}
void Champ_Face_CoviMAC::update_ve (DoubleTab & val) const
Definition at line 154 of file Champ_Face_CoviMAC.cpp.
References Objet_U::dimension, Zone_CoviMAC::init_ve(), DoubleVect::line_size(), Zone_dis_base::nb_elem_tot(), Zone_VF::nb_faces_tot(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, Zone_CoviMAC::vec, Zone_CoviMAC::ved, Zone_CoviMAC::vej, and zone_vf().
Referenced by affecter_(), Masse_CoviMAC_Face::corriger_solution(), and Op_Conv_EF_Stab_CoviMAC_Elem::mettre_a_jour().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  const DoubleVect& pf = zone.porosite_face(), &pe = zone.porosite_elem();
  int e, f, j, d, D = dimension, n, N = val.line_size(), ne_tot = zone.nb_elem_tot(), nf_tot = zone.nb_faces_tot();
  zone.init_ve();
  for (e = 0; e < ne_tot; e++)
    {
      for (d = 0; d < D; d++) for (n = 0; n < N; n++) val(nf_tot + D * e + d, n) = 0;
      for (j = zone.ved(e); j < zone.ved(e + 1); j++) for (f = zone.vej(j), d = 0; d < D; d++) for (n = 0; n < N; n++)
            val(nf_tot + D * e + d, n) += zone.vec(j, d) * val(f, n) * pf(f) / pe(e);
    }
}
void Champ_Face_CoviMAC::update_ve2 (DoubleTab & val, int incr = 0) const
Definition at line 260 of file Champ_Face_CoviMAC.cpp.
References Objet_U::dimension, DoubleVect::echange_espace_virtuel(), fcl_, init_fcl(), init_ve2(), Zone_Cl_dis::les_conditions_limites(), DoubleVect::line_size(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), ref_cast, valeur(), ve2bc, ve2bj, ve2c, ve2d, ve2j, Champ_Inc_base::zone_Cl_dis(), and zone_vf().
Referenced by Masse_CoviMAC_Face::corriger_solution().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  const Conds_lim& cls = zone_Cl_dis().les_conditions_limites();
  int i, j, e, ed, d, D = dimension, n, N = val.line_size(), nf_tot = zone.nb_faces_tot();
  init_ve2(), init_fcl();
  for (e = 0, ed = 0, i = nf_tot; e < zone.nb_elem(); e++) for (d = 0; d < D; d++, ed++, i++) for (n = 0; n < N; n++)
        {
          /* partie "interne" */
          for (val(i, n) = 0, j = ve2d(ed, 0); j < ve2d(ed + 1, 0); j++)
            val(i, n) += ve2c(j) * val(ve2j(j), n);
          /* partie "faces de bord de Dirichlet" (sauf si on fait des increments) */
          if (!incr) for (j = ve2d(ed, 1); j < ve2d(ed + 1, 1); j++)
              val(i, n) += ve2bc(j) * ref_cast(Dirichlet, cls[fcl_(ve2bj(j, 0), 1)].valeur()).val_imp(fcl_(ve2bj(j, 0), 2), N * ve2bj(j, 1) + n);
        }
  val.echange_espace_virtuel();
}
double Champ_Face_CoviMAC::v_norm (const DoubleTab & val, const DoubleTab & val_f, int e, int f, int k, int l, double * v_ext, double * dnv) const [inline]
Definition at line 110 of file Champ_Face_CoviMAC.h.
References Objet_U::dimension, Zone_CoviMAC::dot(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), Zone_VF::nb_faces_tot(), ref_cast, and zone_dis_base().
  {
    const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC, zone_dis_base());
    int d, D = dimension, nf_tot = zone.nb_faces_tot();
    const DoubleTab& nf = zone.face_normales();
    const DoubleVect& fs = zone.face_surfaces();
    double scal = 0, vf = f >= 0 ? val_f(f, k) - (l >= 0 ? val_f(f, l) : 0) : 0, v_temp[3], *v = v_ext ? v_ext : v_temp;
    for (d = 0; d < D; d++) v[d] = val(nf_tot + D * e + d, k) - (l >= 0 ? val(nf_tot + D * e + d, l) : 0);
    if (f >= 0) for (d = 0, scal = zone.dot(v, &nf(f, 0)) / fs(f); d < D; d++) v[d] += (vf - scal) * nf(f, d) / fs(f);
    double nv = sqrt(zone.dot(v, v));
    if (dnv) for (d = 0; d < D; d++) dnv[d] = nv ? (v[d] - (f >= 0 ? vf * nf(f, d) / fs(f) : 0)) / nv : 0;
    if (dnv) dnv[3] = f >= 0 && nv ? vf / nv : 0;
    return nv;
  }
DoubleVect & Champ_Face_CoviMAC::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns:
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 121 of file Champ_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_a_elem(position,result,poly);
}
double Champ_Face_CoviMAC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
Definition at line 127 of file Champ_Face_CoviMAC.cpp.
{
  throw;
// return Champ_implementation_RT0::valeur_a_elem_compo(position,poly,ncomp);
}
DoubleTab & Champ_Face_CoviMAC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 287 of file Champ_Face_CoviMAC.cpp.
References Cerr, DoubleTab::dimension(), Objet_U::dimension, DoubleTab::dimension_tot(), Process::exit(), finl, le_champ(), DoubleVect::line_size(), Field_base::nb_comp(), DoubleTab::nb_dim(), Zone_dis_base::nb_elem(), Zone_VF::nb_faces_tot(), ref_cast, IntVect::size(), Champ_Inc_base::valeurs(), and zone_vf().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  const Champ_base& cha=le_champ();
  int nb_compo=cha.nb_comp(), nf_tot = zone.nb_faces_tot(), d, D = dimension, n, N = valeurs().line_size();
// XXX : TODO Check this assert (positions and not val)
  assert((positions.dimension(0) == les_polys.size())||(positions.dimension_tot(0) == les_polys.size()));
// assert((val.dimension(0) == les_polys.size())||(val.dimension_tot(0) == les_polys.size()));
  if (val.nb_dim() > 2)
    {
      Cerr << "Erreur TRUST dans Champ_Face_implementation::valeur_aux_elems()" << finl;
      Cerr << "Le DoubleTab val a plus de 2 entrees" << finl;
      Process::exit();
    }
  if (nb_compo == 1)
    {
      Cerr<<"Champ_Face_implementation::valeur_aux_elems"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  for (int p = 0, e; p < les_polys.size(); p++) for (e = les_polys(p), d = 0; e < zone.nb_elem() && d < D; d++) for (n = 0; n < N; n++)
        val(p, N * d + n) = valeurs()(nf_tot + D * e + d, n);
  return val;
}
DoubleVect & Champ_Face_CoviMAC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const [virtual]
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns:
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 316 of file Champ_Face_CoviMAC.cpp.
References ArrOfDouble::addr(), Objet_U::dimension, DoubleVect::line_size(), Zone_VF::nb_faces_tot(), ref_cast, IntVect::size(), DoubleVect::size(), Champ_Inc_base::valeurs(), and zone_vf().
{
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,zone_vf());
  int nf_tot = zone.nb_faces_tot(), D = dimension, N = valeurs().line_size();
  assert(val.size() == polys.size());
  for (int p = 0, e; p < polys.size(); p++) val(p) = (e = polys(p)) < 0 ? 0. : valeurs().addr()[N * (nf_tot + D * e) + ncomp];
  return val;
}
DoubleTab & Champ_Face_CoviMAC::valeur_aux_faces (DoubleTab & result) const [virtual]
renvoie la valeur du champ aux faces
Reimplemented from Champ_base.
Definition at line 341 of file Champ_Face_CoviMAC.cpp.
References Cerr, Objet_U::dimension, Process::exit(), Zone_CoviMAC::face_normales(), Zone_VF::face_surfaces(), finl, le_champ(), Field_base::nb_comp(), Zone_VF::nb_faces(), ref_cast, ref_zone_vf_, DoubleTab::resize(), Ref_Zone_VF::valeur(), and Champ_Proto::valeurs().
{
  const Champ_base& cha=le_champ();
  int nb_compo=cha.nb_comp();
  if (nb_compo == 1)
    {
      Cerr<<"Champ_Face_CoviMAC::valeur_aux_faces"<<finl;
      Cerr <<"A scalar field cannot be of Champ_Face type." << finl;
      Process::exit();
    }
  const Zone_CoviMAC& zone = ref_cast(Zone_CoviMAC,ref_zone_vf_.valeur());
  const DoubleTab& nf = zone.face_normales();
  const DoubleVect& fs = zone.face_surfaces();
  val.resize(zone.nb_faces(), dimension), val = 0;
  for (int f = 0; f < zone.nb_faces(); f++)
    for (int r = 0; r < dimension; r++)
      val(f, r) = cha.valeurs()(f) * nf(f, r) / fs(f);
  return val;
}
virtual const Zone_dis_base& Champ_Face_CoviMAC::zone_dis_base () const [inline, virtual]
Reimplemented from Champ_base.
Definition at line 54 of file Champ_Face_CoviMAC.h.
References ref_zone_vf_, and Ref_Zone_VF::valeur().
Referenced by fixer_nb_valeurs_nodales(), and v_norm().
  {
    return ref_zone_vf_.valeur();
  } ;
const Zone_VF& Champ_Face_CoviMAC::zone_vf () const [inline]
Definition at line 76 of file Champ_Face_CoviMAC.h.
References ref_zone_vf_, and Ref_Zone_VF::valeur().
Referenced by Zone_Cl_CoviMAC::imposer_cond_lim(), init_fcl(), init_ve2(), trace(), update_ve(), update_ve2(), valeur_aux_elems(), and valeur_aux_elems_compo().
  {
    return ref_zone_vf_.valeur();
  };
Member Data Documentation
IntTab Champ_Face_CoviMAC::fcl_ [mutable, protected]
Definition at line 129 of file Champ_Face_CoviMAC.h.
Referenced by fcl(), init_fcl(), init_ve2(), and update_ve2().
int Champ_Face_CoviMAC::fcl_init_ = 0 [mutable, protected]
Definition at line 130 of file Champ_Face_CoviMAC.h.
Referenced by fcl(), and init_fcl().
const Type_info Champ_Face_CoviMAC::info_obj [static]
Reimplemented from Champ_Inc_base.
Definition at line 45 of file Champ_Face_CoviMAC.h.
Ref_Zone_VF Champ_Face_CoviMAC::ref_zone_vf_ [protected]
Definition at line 126 of file Champ_Face_CoviMAC.h.
Referenced by affecter_(), associer_zone_dis_base(), valeur_aux_faces(), zone_dis_base(), and zone_vf().
DoubleTab Champ_Face_CoviMAC::ve2bc [mutable]
Definition at line 102 of file Champ_Face_CoviMAC.h.
Referenced by init_ve2(), and update_ve2().
IntTab Champ_Face_CoviMAC::ve2bj [mutable]
Definition at line 101 of file Champ_Face_CoviMAC.h.
Referenced by init_ve2(), and update_ve2().
DoubleTab Champ_Face_CoviMAC::ve2c [mutable]
Definition at line 102 of file Champ_Face_CoviMAC.h.
Referenced by init_ve2(), and update_ve2().
IntTab Champ_Face_CoviMAC::ve2d [mutable]
Definition at line 101 of file Champ_Face_CoviMAC.h.
Referenced by init_ve2(), and update_ve2().
IntTab Champ_Face_CoviMAC::ve2j [mutable]
Definition at line 101 of file Champ_Face_CoviMAC.h.
Referenced by init_ve2(), and update_ve2().
The documentation for this class was generated from the following files:
src/CoviMAC/Champs/Champ_Face_CoviMAC.h
src/CoviMAC/Champs/Champ_Face_CoviMAC.cpp