TRUST: Champ_Q1NC_impl Class Reference
Champ_Q1NC_impl Class Reference abstract
#include <Champ_Q1NC_impl.h>
Public Member Functions
~Champ_Q1NC_impl () override
double fonction_forme_2D (double x, double y, int le_poly, int face)
double fonction_forme_3D (double x, double y, double z, int le_poly, int face)
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double calcule_valeur_a_elem_compo (double xs, double ys, double zs, int le_poly, int ncomp) const
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
double valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
void transforme_coord2D ()
void transforme_coord3D ()
Public Member Functions inherited from Champ_implementation
virtual ~Champ_implementation ()
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const =0
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const =0
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const =0
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const =0
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const =0
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const =0
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const =0
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const =0
Static Public Member Functions
static double fonction_forme_2D_normalise (double x, double y, int face)
static double fonction_forme_3D_normalise (double x, double y, double z, int face)
static DoubleTab & Derivee_fonction_forme_2D_normalise (double u, double v, DoubleTab &DF)
static DoubleTab & Derivee_fonction_forme_3D_normalise (double u, double v, double w, DoubleTab &DF)
Protected Member Functions
virtual const Zone_VEF & zone_vef () const =0
DoubleTab & trace (const Frontiere_dis_base &fr, const DoubleTab &y, DoubleTab &x, int distant) const
Protected Member Functions inherited from Champ_implementation
virtual const Champ_base & le_champ () const =0
virtual Champ_base & le_champ ()=0
const Zone & zone () const
virtual const Zone_dis_base & zone_dis_base () const
Protected Attributes
DoubleTab tab_param
Detailed Description
Definition at line 26 of file Champ_Q1NC_impl.h.
Constructor & Destructor Documentation
~Champ_Q1NC_impl()
Champ_Q1NC_impl::~Champ_Q1NC_impl () inline override
Definition at line 31 of file Champ_Q1NC_impl.h.
{ }
Member Function Documentation
calcule_valeur_a_elem_compo()
double Champ_Q1NC_impl::calcule_valeur_a_elem_compo (double xs, double ys, double zs, int le_poly, int ncomp) const
Definition at line 99 of file Champ_Q1NC_impl.cpp.
{
  const Zone_VEF& zone_VEF = zone_vef();
  const DoubleTab& ch = le_champ().valeurs();
  int face,init=tab_param.size() , D = Objet_U::dimension;
  if (init == 0 && D == 2) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord2D();
  if (init == 0 && D == 3) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord3D();
  double val;
  if (le_poly == -1)
    val = 0;
  else
    {
// Calcul d'apres les fonctions de forme sur le quadrangle ou son extension en 3D
      val = 0;
      for (int i=0; i< 2 * D; i++)
        {
          face = zone_VEF.elem_faces(le_poly,i);
          val += ch(face, ncomp)*
                 ( (D == 2) ? (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_2D(xs,ys,le_poly,i) :
                   (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_3D(xs,ys,zs,le_poly,i));
        }
    }
  return val;
}
References Objet_U::dimension, Zone_VF::elem_faces(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), Champ_Proto::valeurs(), verif_cast, and zone_vef().
Referenced by valeur_a_elem_compo(), and valeur_a_sommet_compo().
Derivee_fonction_forme_2D_normalise()
DoubleTab & Champ_Q1NC_impl::Derivee_fonction_forme_2D_normalise (double u, double v, DoubleTab & DF) static
Definition at line 22 of file Champ_Q1NC_impl.cpp.
{
  DF(0,0) = -0.5 + 0.5*u;
  DF(0,1) =      - 0.5*u;
  DF(0,2) =  0.5 + 0.5*u;
  DF(0,3) =      - 0.5*u;
  DF(1,0) =      - 0.5*v;
  DF(1,1) = -0.5 + 0.5*v;
  DF(1,2) =      - 0.5*v;
  DF(1,3) =  0.5 + 0.5*v;
  return DF;
}
Derivee_fonction_forme_3D_normalise()
DoubleTab & Champ_Q1NC_impl::Derivee_fonction_forme_3D_normalise (double u, double v, double w, DoubleTab & DF) static
Definition at line 38 of file Champ_Q1NC_impl.cpp.
{
  double tier=1./3.;
  DF(0,0) = -0.5 + 2*tier*u;
  DF(0,1) =      - tier*u;
  DF(0,2) =      - tier*u;
  DF(0,3) =  0.5 + 2*tier*u;
  DF(0,4) =      - tier*u;
  DF(0,5) =      - tier*u;
  DF(1,0) =      - tier*v;
  DF(1,1) = -0.5 + 2*tier*v;
  DF(1,2) =      - tier*v;
  DF(1,3) =      - tier*v;
  DF(1,4) =  0.5 + 2*tier*v;
  DF(1,5) =      - tier*v;
  DF(2,0) =      - tier*w;
  DF(2,1) =      - tier*w;
  DF(2,2) = -0.5 + 2*tier*w;
  DF(2,3) =      - tier*w;
  DF(2,4) =      - tier*w;
  DF(2,5) = 0.5  + 2*tier*w;
  return DF;
}
fonction_forme_2D()
double Champ_Q1NC_impl::fonction_forme_2D (double x, double y, int le_poly, int face) inline
Definition at line 65 of file Champ_Q1NC_impl.h.
{
  double ksi,eta;
  ksi=tab_param(le_poly,0)*x+tab_param(le_poly,1)*y+tab_param(le_poly,2);
  eta=tab_param(le_poly,3)*x+tab_param(le_poly,4)*y+tab_param(le_poly,5);
  double fonction_de_forme=1.;
  fonction_de_forme*=fonction_forme_2D_normalise(ksi,eta,face);
// Cerr << "fonction_de_forme " << fonction_de_forme << finl;
  return fonction_de_forme;
}
References fonction_forme_2D_normalise(), and tab_param.
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
fonction_forme_2D_normalise()
double Champ_Q1NC_impl::fonction_forme_2D_normalise (double x, double y, int face) inline static
Definition at line 94 of file Champ_Q1NC_impl.h.
{
// la fonction de forme est calculer dans la base (ksi), (eta).
// aux milieu des faces.
// Psi1(x,y) = 0.25 - 0.5ksi + 0.25(ksi^2 - eta^2)
// Psi2(x,y) = 0.25 - 0.5eta - 0.25(ksi^2 - eta^2)
// Psi3(x,y) = 0.25 + 0.5ksi + 0.25(ksi^2 - eta^2)
// Psi4(x,y) = 0.25 + 0.5eta - 0.25(ksi^2 - eta^2)
  double fonction_de_forme_normalisee, carre_ksi=ksi*ksi, carre_eta=eta*eta ;
  switch(face)
    {
    case 0:
      {
        fonction_de_forme_normalisee = 0.25 - 0.5*ksi + 0.25*(carre_ksi - carre_eta);
        break;
      }
    case 1:
      {
        fonction_de_forme_normalisee = 0.25 - 0.5*eta - 0.25*(carre_ksi - carre_eta);
        break;
      }
    case 2:
      {
        fonction_de_forme_normalisee = 0.25 + 0.5*ksi + 0.25*(carre_ksi - carre_eta);
        break;
      }
    case 3:
      {
        fonction_de_forme_normalisee = 0.25 + 0.5*eta - 0.25*(carre_ksi - carre_eta);
        break;
      }
    default :
      {
        Cerr << "Erreur dans Champ_Q1NC_impl::fonction_forme_2D : " << finl;
        Cerr << "Un quadrangle n'a pas " << face << " faces" << finl;
        Process::exit();
        fonction_de_forme_normalisee=-1;
      }
    }
  return fonction_de_forme_normalisee;
}
References Cerr, Process::exit(), and finl.
Referenced by fonction_forme_2D().
fonction_forme_3D()
double Champ_Q1NC_impl::fonction_forme_3D (double x, double y, double z, int le_poly, int face) inline
Definition at line 76 of file Champ_Q1NC_impl.h.
{
  double ksi,eta,psi;
  ksi=tab_param(le_poly,0)*x+tab_param(le_poly,1)*y+tab_param(le_poly,2)*z+tab_param(le_poly,3);
  eta=tab_param(le_poly,4)*x+tab_param(le_poly,5)*y+tab_param(le_poly,6)*z+tab_param(le_poly,7);
  psi=tab_param(le_poly,8)*x+tab_param(le_poly,9)*y+tab_param(le_poly,10)*z+tab_param(le_poly,11);
  double fonction_de_forme=1.;
  fonction_de_forme*=fonction_forme_3D_normalise(ksi,eta,psi,face);
// Cerr << "ksi " << ksi << " eta " << eta << " psi " << psi << finl;
  return fonction_de_forme;
}
References fonction_forme_3D_normalise(), and tab_param.
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
fonction_forme_3D_normalise()
double Champ_Q1NC_impl::fonction_forme_3D_normalise (double x, double y, double z, int face) inline static
Definition at line 138 of file Champ_Q1NC_impl.h.
{
// la fonction de forme est calculer dans la base (ksi), (eta), (psi).
// aux milieu des faces.
// Psi0(x,y,z) = 1/6. - 0.5ksi + 1/3.(ksi^2 - eta^2) + 1/6.(eta^2 - psi^2)
// Psi1(x,y,z) = 1/6. - 0.5eta - 1/6.(ksi^2 - eta^2) + 1/6.(eta^2 - psi^2)
// Psi2(x,y,z) = 1/6. - 0.5psi - 1/6.(ksi^2 - eta^2) + 1/6.(eta^2 - psi^2)
// Psi3(x,y,z) = 1/6. + 0.5ksi + 1/3.(ksi^2 - eta^2) + 1/6.(eta^2 - psi^2)
// Psi4(x,y,z) = 1/6. + 0.5eta - 1/6.(ksi^2 - eta^2) + 1/6.(eta^2 - psi^2)
// Psi5(x,y,z) = 1/6. + 0.5psi - 1/6.(ksi^2 - eta^2) + 1/6.(eta^2 - psi^2)
  double fonction_de_forme_normalisee ;
  double six=1./6., tier=1./3., carre_ksi=ksi*ksi, carre_eta=eta*eta, carre_psi=psi*psi;
  switch(face)
    {
    case 0:
      {
        fonction_de_forme_normalisee = six - 0.5*ksi + tier*(carre_ksi - carre_eta) + six*(carre_eta - carre_psi);
        break;
      }
    case 1:
      {
        fonction_de_forme_normalisee = six - 0.5*eta - six*(carre_ksi - carre_eta) + six*(carre_eta - carre_psi);
        break;
      }
    case 2:
      {
        fonction_de_forme_normalisee = six - 0.5*psi - six*(carre_ksi - carre_eta) - tier*(carre_eta - carre_psi);
        break;
      }
    case 3:
      {
        fonction_de_forme_normalisee = six + 0.5*ksi + tier*(carre_ksi - carre_eta) + six*(carre_eta - carre_psi);
        break;
      }
    case 4:
      {
        fonction_de_forme_normalisee = six + 0.5*eta - six*(carre_ksi - carre_eta) + six*(carre_eta - carre_psi);
        break;
      }
    case 5:
      {
        fonction_de_forme_normalisee = six + 0.5*psi - six*(carre_ksi - carre_eta) - tier*(carre_eta - carre_psi);
        break;
      }
    default :
      {
        Cerr << "Erreur dans Champ_Q1NC_impl::fonction_forme_2D : " << finl;
        Cerr << "Un quadrangle n'a pas " << face << " faces" << finl;
        fonction_de_forme_normalisee=-1;
        Process::exit();
      }
    }
  return fonction_de_forme_normalisee;
}
References Cerr, Process::exit(), and finl.
Referenced by fonction_forme_3D().
remplir_coord_noeuds()
DoubleTab & Champ_Q1NC_impl::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
Definition at line 314 of file Champ_Q1NC_impl.cpp.
{
  const Zone_VEF& zvef = zone_vef();
  const DoubleTab& xv = zvef.xv();
  int nb_fac = zvef.nb_faces();
  if ( (xv.dimension(0) == nb_fac ) && (xv.line_size() == Objet_U::dimension) )
    noeuds.ref(xv);
  else
    {
      Cerr << "Erreur dans Champ_Q1NC_impl::remplir_coord_noeuds()" << finl;
      Cerr << "Les centres de gravite des faces n'ont pas ete calcules" << finl;
      Process::exit();
    }
  return noeuds;
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Process::exit(), finl, TRUSTVect< _TYPE_ >::line_size(), Zone_VF::nb_faces(), TRUSTTab< _TYPE_ >::ref(), Zone_VF::xv(), and zone_vef().
Referenced by Champ_Fonc_Q1NC::remplir_coord_noeuds(), Champ_Q1NC::remplir_coord_noeuds(), and remplir_coord_noeuds_et_polys().
remplir_coord_noeuds_et_polys()
int Champ_Q1NC_impl::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
Definition at line 331 of file Champ_Q1NC_impl.cpp.
{
  remplir_coord_noeuds(positions);
  const Zone_VEF& zvef=zone_vef();
  const IntTab& face_voisins=zvef.face_voisins();
  int nb_faces=zvef.nb_faces();
  polys.resize(nb_faces);
  for(int i= 0; i< nb_faces; i++)
    polys(i)=face_voisins(i, 0);
  return 1;
}
References Zone_VF::face_voisins(), Zone_VF::nb_faces(), remplir_coord_noeuds(), TRUSTVect< _TYPE_ >::resize(), and zone_vef().
Referenced by Champ_Fonc_Q1NC::remplir_coord_noeuds_et_polys(), and Champ_Q1NC::remplir_coord_noeuds_et_polys().
trace()
DoubleTab & Champ_Q1NC_impl::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const inline protected
Definition at line 198 of file Champ_Q1NC_impl.h.
{
  if (distant)
    fr.frontiere().trace_face_distant(y, x);
  else
    fr.frontiere().trace_face_local(y, x);
// useless ? x.echange_espace_virtuel();
  return x;
}
References Frontiere_dis_base::frontiere(), Frontiere::trace_face_distant(), and Frontiere::trace_face_local().
Referenced by Champ_Fonc_Q1NC::trace(), and Champ_Q1NC::trace().
transforme_coord2D()
void Champ_Q1NC_impl::transforme_coord2D ()
Definition at line 351 of file Champ_Q1NC_impl.cpp.
{
// const Zone_VEF& zone_VEF = la_zone_vef.valeur();
  const Zone_VEF& zone_VEF = zone_vef();
  const Zone& zone_geom = zone();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const IntTab& sommet_face = zone_VEF.face_sommets();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const Domaine& dom=zone_geom.domaine();
  const DoubleTab& coords=dom.les_sommets();
  double lec0, lec1, alpha, beta;
  int i,poly,som0,som1;
//
//
  tab_param.resize(nb_elem_tot,6);
  int Nb_noeud_elem = 4;
  DoubleVect le_coord0(Nb_noeud_elem), le_coord1(Nb_noeud_elem);
  for (poly=0; poly<nb_elem_tot; poly++)
    {
      for ( i = 0; i < Nb_noeud_elem; i++ )
        {
          som0 = sommet_face(elem_faces(poly,i),0);
          som1 = sommet_face(elem_faces(poly,i),1);
          le_coord0(i)=0.5*(coords(som0,0)+coords(som1,0));
          le_coord1(i)=0.5*(coords(som0,1)+coords(som1,1));
        }
//
// calcul de ksi
//
// ksi = a_ksi x + b_ksi y + c_ksi
// ksi = [ (x2-x0) x + (y2-y0) y ] alpha + beta
// a_ksi = alpha (x2-x0)
// b_ksi = alpha (y2-y0)
// c_ksi = beta
//
// ou ksi(x0,y0) = -1     eqn(1)
// et ksi(x2,y2) = 1      eqn(2)
//
// donc (2)-(1) donne
// alpha = 2/[ (x2-x0)x2 - (x2-x0)x0 + (y2-y0)y2 - (y2-y0)y0 ]
// beta  = 1 - [(x2-x0)x2 + (y2-y0)y2] alpha
//
      lec0=carre(le_coord0(2))+carre(le_coord0(0))-2.*le_coord0(2)*le_coord0(0);
      lec1=carre(le_coord1(2))+carre(le_coord1(0))-2.*le_coord1(2)*le_coord1(0);
      alpha=2./(lec0+lec1);
      lec0=(le_coord0(2)-le_coord0(0))*le_coord0(2);
      lec1=(le_coord1(2)-le_coord1(0))*le_coord1(2);
      beta=1.-(lec0+lec1)*alpha;
//
      tab_param(poly,0)=alpha*(le_coord0(2)-le_coord0(0));
      tab_param(poly,1)=alpha*(le_coord1(2)-le_coord1(0));
      tab_param(poly,2)=beta;
//
// calcul de eta
//
      lec0=carre(le_coord0(3))+carre(le_coord0(1))-2.*le_coord0(3)*le_coord0(1);
      lec1=carre(le_coord1(3))+carre(le_coord1(1))-2.*le_coord1(3)*le_coord1(1);
      alpha=2./(lec0+lec1);
      lec0=(le_coord0(3)-le_coord0(1))*le_coord0(3);
      lec1=(le_coord1(3)-le_coord1(1))*le_coord1(3);
      beta=1.-(lec0+lec1)*alpha;
//
      tab_param(poly,3)=alpha*(le_coord0(3)-le_coord0(1));
      tab_param(poly,4)=alpha*(le_coord1(3)-le_coord1(1));
      tab_param(poly,5)=beta;
    }
}
References carre(), Zone::domaine(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), Domaine::les_sommets(), Zone_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_ >::resize(), tab_param, Champ_implementation::zone(), and zone_vef().
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
transforme_coord3D()
void Champ_Q1NC_impl::transforme_coord3D ()
Definition at line 419 of file Champ_Q1NC_impl.cpp.
{
  const Zone_VEF& zone_VEF = zone_vef();
  const Zone& zone_geom = zone();
  const int nb_elem_tot = zone_VEF.nb_elem_tot();
  const IntTab& sommet_face = zone_VEF.face_sommets();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const Domaine& dom=zone_geom.domaine();
  const DoubleTab& coords=dom.les_sommets();
  double lec0, lec1, lec2;
  double alpha, beta;
  int i, poly;
  int som0, som1, som2, som3;
  tab_param.resize(nb_elem_tot,12);
//
//
  int Nb_noeud_elem = 6;
  DoubleVect le_coord0(Nb_noeud_elem), le_coord1(Nb_noeud_elem), le_coord2(Nb_noeud_elem);
  for (poly=0; poly<nb_elem_tot; poly++)
    {
      for ( i = 0; i < Nb_noeud_elem; i++ )
        {
          som0 = sommet_face(elem_faces(poly,i),0);
          som1 = sommet_face(elem_faces(poly,i),1);
          som2 = sommet_face(elem_faces(poly,i),2);
          som3 = sommet_face(elem_faces(poly,i),3);
          le_coord0(i)=0.25*(coords(som0,0)+coords(som1,0)+coords(som2,0)+coords(som3,0));
          le_coord1(i)=0.25*(coords(som0,1)+coords(som1,1)+coords(som2,1)+coords(som3,1));
          le_coord2(i)=0.25*(coords(som0,2)+coords(som1,2)+coords(som2,2)+coords(som3,2));
        }
//
// calcul de ksi
//
      lec0=carre(le_coord0(3))+carre(le_coord0(0))-2.*le_coord0(3)*le_coord0(0);
      lec1=carre(le_coord1(3))+carre(le_coord1(0))-2.*le_coord1(3)*le_coord1(0);
      lec2=carre(le_coord2(3))+carre(le_coord2(0))-2.*le_coord2(3)*le_coord2(0);
      alpha=2./(lec0+lec1+lec2);
      lec0=(le_coord0(3)-le_coord0(0))*le_coord0(3);
      lec1=(le_coord1(3)-le_coord1(0))*le_coord1(3);
      lec2=(le_coord2(3)-le_coord2(0))*le_coord2(3);
      beta=1.-(lec0+lec1+lec2)*alpha;
//
      tab_param(poly,0)=alpha*(le_coord0(3)-le_coord0(0));
      tab_param(poly,1)=alpha*(le_coord1(3)-le_coord1(0));
      tab_param(poly,2)=alpha*(le_coord2(3)-le_coord2(0));
      tab_param(poly,3)=beta;
//
// calcul de eta
//
      lec0=carre(le_coord0(4))+carre(le_coord0(1))-2.*le_coord0(4)*le_coord0(1);
      lec1=carre(le_coord1(4))+carre(le_coord1(1))-2.*le_coord1(4)*le_coord1(1);
      lec2=carre(le_coord2(4))+carre(le_coord2(1))-2.*le_coord2(4)*le_coord2(1);
      alpha=2./(lec0+lec1+lec2);
      lec0=(le_coord0(4)-le_coord0(1))*le_coord0(4);
      lec1=(le_coord1(4)-le_coord1(1))*le_coord1(4);
      lec2=(le_coord2(4)-le_coord2(1))*le_coord2(4);
      beta=1.-(lec0+lec1+lec2)*alpha;
//
      tab_param(poly,4)=alpha*(le_coord0(4)-le_coord0(1));
      tab_param(poly,5)=alpha*(le_coord1(4)-le_coord1(1));
      tab_param(poly,6)=alpha*(le_coord2(4)-le_coord2(1));
      tab_param(poly,7)=beta;
//
// calcul de psi
//
      lec0=carre(le_coord0(5))+carre(le_coord0(2))-2.*le_coord0(5)*le_coord0(2);
      lec1=carre(le_coord1(5))+carre(le_coord1(2))-2.*le_coord1(5)*le_coord1(2);
      lec2=carre(le_coord2(5))+carre(le_coord2(2))-2.*le_coord2(5)*le_coord2(2);
      alpha=2./(lec0+lec1+lec2);
      lec0=(le_coord0(5)-le_coord0(2))*le_coord0(5);
      lec1=(le_coord1(5)-le_coord1(2))*le_coord1(5);
      lec2=(le_coord2(5)-le_coord2(2))*le_coord2(5);
      beta=1.-(lec0+lec1+lec2)*alpha;
//
      tab_param(poly,8)=alpha*(le_coord0(5)-le_coord0(2));
      tab_param(poly,9)=alpha*(le_coord1(5)-le_coord1(2));
      tab_param(poly,10)=alpha*(le_coord2(5)-le_coord2(2));
      tab_param(poly,11)=beta;
    }
}
References carre(), Zone::domaine(), Zone_VF::elem_faces(), Zone_VF::face_sommets(), Domaine::les_sommets(), Zone_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_ >::resize(), tab_param, Champ_implementation::zone(), and zone_vef().
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
valeur_a_elem()
DoubleVect & Champ_Q1NC_impl::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const override virtual
Implements Champ_implementation.
Definition at line 66 of file Champ_Q1NC_impl.cpp.
{
  const Champ_base& cha=le_champ();
  int face, nb_compo_=cha.nb_comp();
  double xs,ys,zs;
  const DoubleTab& ch = cha.valeurs();
  const Zone_VEF& zone_VEF = zone_vef();
  int init=tab_param.size(), D = Objet_U::dimension;
  if (init == 0 && D == 2) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord2D();
  if (init == 0 && D == 3) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord3D();
  val=0;
  if (le_poly != -1)
    {
      xs = position(0);
      ys = position(1);
      zs = (D ==3 ) ? position(2) : 0.;
      for (int i=0; i< 2 * D; i++)
        {
          face = zone_VEF.elem_faces(le_poly,i);
          for(int ncomp=0; ncomp<nb_compo_; ncomp++)
            val(ncomp) += ch(face, ncomp)*
                          ( (D == 2) ? (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_2D(xs,ys,le_poly,i) :
                            (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_3D(xs,ys,zs,le_poly,i));
        }
    }
  return val;
}
References Objet_U::dimension, Zone_VF::elem_faces(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), Champ_Proto::valeurs(), verif_cast, and zone_vef().
Referenced by Champ_Fonc_Q1NC::valeur_a_elem(), and Champ_Q1NC::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Q1NC_impl::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 127 of file Champ_Q1NC_impl.cpp.
{
  double xs,ys,zs=0;
  xs = position(0);
  ys = position(1);
  if (Objet_U::dimension == 3) zs = position(2);
  return calcule_valeur_a_elem_compo(xs,ys,zs,le_poly,ncomp);
}
References calcule_valeur_a_elem_compo(), and Objet_U::dimension.
Referenced by Champ_Fonc_Q1NC::valeur_a_elem_compo(), Champ_Q1NC::valeur_a_elem_compo(), valeur_aux_sommets(), and valeur_aux_sommets_compo().
valeur_a_sommet_compo()
double Champ_Q1NC_impl::valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const
Definition at line 136 of file Champ_Q1NC_impl.cpp.
{
// Cerr << "Champ_Q1NC_impl::valeur_a_sommet_compo" << finl;
// Contrairement au Champ_P1NC les fonctions de forme
// ne sont pas triviales au sommet des hexas... On repasse
// par calcule_valeur_a_elem_compo
  double xs,ys,zs=0;
  const Domaine& dom=zone().domaine();
  xs = dom.coord(num_som,0);
  ys = dom.coord(num_som,1);
  if (Objet_U::dimension == 3) zs = dom.coord(num_som,2);
  return calcule_valeur_a_elem_compo(xs,ys,zs,le_poly,ncomp);
}
References calcule_valeur_a_elem_compo(), Domaine::coord(), Objet_U::dimension, Zone::domaine(), and Champ_implementation::zone().
Referenced by Champ_Q1NC::valeur_a_sommet_compo().
valeur_aux_elems()
DoubleTab & Champ_Q1NC_impl::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
Implements Champ_implementation.
Definition at line 150 of file Champ_Q1NC_impl.cpp.
{
  const Champ_base& cha=le_champ();
  int face, nb_compo_=cha.nb_comp();
  double xs,ys,zs;
  const Zone_VEF& zone_VEF = zone_vef();
  int init=tab_param.size(), D = Objet_U::dimension;
  if (init == 0 && D == 2) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord2D();
  if (init == 0 && D == 3) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord3D();
  if (val.nb_dim() > 2)
    {
      Cerr << "Erreur TRUST dans Champ_Q1NC_impl::valeur_aux_elems()\n";
      Cerr << "Le DoubleTab val a plus de 2 entrees\n";
      Process::exit();
    }
  int le_poly;
  const DoubleTab& ch = cha.valeurs();
  for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
    {
      le_poly=les_polys(rang_poly);
      if (le_poly == -1)
        for(int ncomp=0; ncomp<nb_compo_; ncomp++)
          val(rang_poly, ncomp) = 0;
      else
        {
          for(int ncomp=0; ncomp<nb_compo_; ncomp++)
            {
              val(rang_poly, ncomp) = 0;
              xs = positions(rang_poly,0);
              ys = positions(rang_poly,1);
              zs = (D == 3) ? positions(rang_poly,2) : 0.;
              for (int i=0; i< 2 * D ; i++)
                {
                  face = zone_VEF.elem_faces(le_poly,i);
                  val(rang_poly, ncomp) += ch(face, ncomp)*
                                           ((D==2) ? (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_2D(xs,ys,le_poly,i) :
                                            (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_3D(xs,ys,zs,le_poly,i));
                }
            }
        }
    }
  return val;
}
References Cerr, Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_ >::nb_dim(), TRUSTVect< _TYPE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), Champ_Proto::valeurs(), verif_cast, and zone_vef().
Referenced by Champ_Fonc_Q1NC::valeur_aux_elems(), and Champ_Q1NC::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Q1NC_impl::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 200 of file Champ_Q1NC_impl.cpp.
{
// Cerr << "Champ_Q1NC_impl::valeur_aux_elems_compo " << finl;
  const Champ_base& cha=le_champ();
  double xs,ys,zs;
  int face;
  const Zone_VEF& zone_VEF = zone_vef();
  assert(val.size() == les_polys.size());
  int le_poly;
  const DoubleTab& ch = cha.valeurs();
  int init=tab_param.size(), D = Objet_U::dimension;
  if (init == 0 && D == 2) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord2D();
  if (init == 0 && D == 3) (verif_cast(Champ_Q1NC_impl&, *this)).transforme_coord3D();
  for(int rang_poly=0; rang_poly<les_polys.size(); rang_poly++)
    {
      le_poly=les_polys(rang_poly);
      if (le_poly == -1) val(rang_poly) = 0;
      else
        {
// Calcul d'apres les fonctions de forme sur le quadrangle ou son extension en 3D
          val = 0;
          xs = positions(rang_poly,0);
          ys = positions(rang_poly,1);
          zs = (D == 3) ? positions(rang_poly,2) : 0.;
          for (int i=0; i< 2 * D; i++)
            {
              face = zone_VEF.elem_faces(le_poly,i);
              val(rang_poly) += ch(face, ncomp)*
                                ( (D == 2) ? (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_2D(xs,ys,le_poly,i) :
                                  (verif_cast(Champ_Q1NC_impl&, *this)).fonction_forme_3D(xs,ys,zs,le_poly,i));
            }
        }
    }
  return val;
}
References Objet_U::dimension, Zone_VF::elem_faces(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), Champ_Proto::valeurs(), verif_cast, and zone_vef().
Referenced by Champ_Fonc_Q1NC::valeur_aux_elems_compo(), and Champ_Q1NC::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Q1NC_impl::valeur_aux_sommets (const Domaine & dom, DoubleTab & ch_som) const override virtual
Implements Champ_implementation.
Definition at line 241 of file Champ_Q1NC_impl.cpp.
{
// Cerr << "Champ_Q1NC_impl::valeur_aux_sommets " << finl;
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& ma_zone = zone_dis.zone();
  int nb_elem_tot = ma_zone.nb_elem_tot(), nb_som = ma_zone.nb_som(), nb_som_elem = ma_zone.nb_som_elem();
  const Champ_base& cha=le_champ();
  int nb_compo_=cha.nb_comp();
  IntVect compteur(nb_som);
  int ncomp, num_elem,num_som,j;
  ch_som = 0;
  compteur = 0;
  DoubleVect position(Objet_U::dimension);
  for (num_elem=0; num_elem<nb_elem_tot; num_elem++)
    for (j=0; j<nb_som_elem; j++)
      {
        num_som = ma_zone.sommet_elem(num_elem,j);
// Cerr << "num_som " << num_som << finl;
        for(int k=0; k<Objet_U::dimension; k++)
          position(k)=dom.coord(num_som,k);
// Cerr << "position " << position << finl;
        if(num_som < nb_som)
          {
            compteur[num_som]++;
            for (ncomp=0; ncomp<nb_compo_; ncomp++)
              {
                ch_som(num_som,ncomp) += valeur_a_elem_compo(position,num_elem,ncomp);
// Cerr << "ch_som " <<  ch_som(num_som,ncomp)  << finl;
              }
          }
      }
  for (num_som=0; num_som<nb_som; num_som++)
    for (ncomp=0; ncomp<nb_compo_; ncomp++)
      ch_som(num_som,ncomp) /= compteur[num_som];
  return ch_som;
}
References compteur, Domaine::coord(), Objet_U::dimension, Champ_implementation::le_champ(), Field_base::nb_comp(), Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), Zone::sommet_elem(), valeur_a_elem_compo(), Zone_dis_base::zone(), and Champ_implementation::zone_dis_base().
Referenced by Champ_Fonc_Q1NC::valeur_aux_sommets(), and Champ_Q1NC::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Q1NC_impl::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & ch_som, int ncomp) const override virtual
Implements Champ_implementation.
Definition at line 281 of file Champ_Q1NC_impl.cpp.
{
// Cerr << "Champ_Q1NC_impl::valeur_aux_sommets_compo " << finl;
  const Zone_dis_base& zone_dis = zone_dis_base();
  const Zone& ma_zone = zone_dis.zone();
  int nb_elem_tot = ma_zone.nb_elem_tot(), nb_som = ma_zone.nb_som(), nb_som_elem = ma_zone.nb_som_elem();
  IntVect compteur(nb_som);
  int num_elem,num_som,j;
  ch_som = 0;
  compteur = 0;
  DoubleVect position(Objet_U::dimension);
  for (num_elem=0; num_elem<nb_elem_tot; num_elem++)
    for (j=0; j<nb_som_elem; j++)
      {
        num_som = ma_zone.sommet_elem(num_elem,j);
        for(int k=0; k<Objet_U::dimension; k++)
          position(k)=dom.coord(num_som,k);
        if(num_som < nb_som)
          {
            compteur[num_som]++;
            ch_som(num_som) +=  valeur_a_elem_compo(position,num_elem,ncomp);
          }
      }
  for (num_som=0; num_som<nb_som; num_som++)
    ch_som(num_som) /= compteur[num_som];
  return ch_som;
}
References compteur, Domaine::coord(), Objet_U::dimension, Zone::nb_elem_tot(), Zone::nb_som(), Zone::nb_som_elem(), Zone::sommet_elem(), valeur_a_elem_compo(), Zone_dis_base::zone(), and Champ_implementation::zone_dis_base().
Referenced by Champ_Fonc_Q1NC::valeur_aux_sommets_compo(), and Champ_Q1NC::valeur_aux_sommets_compo().
zone_vef()
virtual const Zone_VEF & Champ_Q1NC_impl::zone_vef () const protected pure virtual
Implemented in Champ_Fonc_Q1NC, and Champ_Q1NC.
Referenced by calcule_valeur_a_elem_compo(), remplir_coord_noeuds(), remplir_coord_noeuds_et_polys(), transforme_coord2D(), transforme_coord3D(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
Member Data Documentation
tab_param
DoubleTab Champ_Q1NC_impl::tab_param protected
Definition at line 61 of file Champ_Q1NC_impl.h.
Referenced by calcule_valeur_a_elem_compo(), fonction_forme_2D(), fonction_forme_3D(), transforme_coord2D(), transforme_coord3D(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
The documentation for this class was generated from the following files:
src/VEF/Champs/Champ_Q1NC_impl.h
src/VEF/Champs/Champ_Q1NC_impl.cpp