TRUST: Entree_Brute Class Reference
Entree_Brute Class Reference
An Entree whose main source of data is an arbitrary binary buffer set using the
set_data() method. This Entree can then be used to feed any standard TRUST objects.
#include <Entree_Brute.h>
Public Member Functions
Entree_Brute ()
~Entree_Brute ()
int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
void set_data (const char *data, unsigned sz)
Protected Attributes
istringstream * istrstream_
char * data_
Detailed Description
An Entree whose main source of data is an arbitrary binary buffer set using the
set_data() method. This Entree can then be used to feed any standard TRUST objects.
Definition at line 38 of file Entree_Brute.h.
Constructor & Destructor Documentation
Entree_Brute::Entree_Brute ()
Definition at line 29 of file Entree_Brute.cpp.
References istrstream_, set_bin(), and Entree::set_istream().
                          :
  Entree(), data_(0)
{
  set_bin(1);
  istrstream_ = new istringstream();
  set_istream(istrstream_);
}
Entree_Brute::~Entree_Brute ()
Definition at line 38 of file Entree_Brute.cpp.
References data_.
{
  delete[] data_;
}
Member Function Documentation
int Entree_Brute::set_bin (int bin) [virtual]
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand.
Reimplemented from Entree.
Definition at line 43 of file Entree_Brute.cpp.
References Cerr, Process::exit(), and finl.
Referenced by Entree_Brute().
{
  if (bin != 1)
    {
      Cerr << "Error in Entree_Brute::set_bin(int bin) : only binary format supported. Use EChaine otherwise." << finl;
      Process::exit();
    }
  Entree::set_bin(bin);
  return bin;
}
void Entree_Brute::set_data (const char * data, unsigned sz)
Definition at line 54 of file Entree_Brute.cpp.
References data_, Entree::get_istream(), istrstream_, Entree::set_istream(), and sz.
{
  if(data_)
    {
// For now forbid multiple calls ... could try deleting data_
// Cerr << "Entree_Brute::set_data(): Multiple calls forbidden!  " << finl;
// Process::exit(-1);
      delete[] data_;
      if (istrstream_)
        delete istrstream_;
      istrstream_ = new istringstream();
      set_istream(istrstream_);
    }
  const std::istream& iss = get_istream();
  std::streambuf * sb = iss.rdbuf();
  data_ = new char[sz];
  std::copy(data, data+sz, data_);
  sb->pubsetbuf(data_, sz);
}
Member Data Documentation
char* Entree_Brute::data_ [protected]
Definition at line 51 of file Entree_Brute.h.
Referenced by set_data(), and ~Entree_Brute().
istringstream* Entree_Brute::istrstream_ [protected]
Definition at line 50 of file Entree_Brute.h.
Referenced by Entree_Brute(), and set_data().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Entree_Brute.h
src/Kernel/Utilitaires/Entree_Brute.cpp