TRUST: Integrer_champ_med Class Reference
Integrer_champ_med Class Reference
Classe Integrer_champ_med
Lecture d'un fichier.
#include <Integrer_champ_med.h>
Public Member Functions
Integrer_champ_med ()
~Integrer_champ_med ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Fonction principale de l'interprete.
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Integrer_champ_med & self_cast (Objet_U &)
static const Integrer_champ_med & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Classe Integrer_champ_med
Lecture d'un fichier.
Definition at line 37 of file Integrer_champ_med.h.
Constructor & Destructor Documentation
Integrer_champ_med()
Integrer_champ_med::Integrer_champ_med ()
Definition at line 21 of file Integrer_champ_med.cpp.
~Integrer_champ_med()
Integrer_champ_med::~Integrer_champ_med ()
Definition at line 21 of file Integrer_champ_med.cpp.
Member Function Documentation
cree_instance()
Objet_U * Integrer_champ_med::cree_instance () static
Definition at line 21 of file Integrer_champ_med.cpp.
duplique()
int Integrer_champ_med::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Integrer_champ_med.cpp.
get_info()
const Type_info * Integrer_champ_med::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Integrer_champ_med.cpp.
info()
const Type_info * Integrer_champ_med::info () static
Definition at line 21 of file Integrer_champ_med.cpp.
interpreter()
Entree & Integrer_champ_med::interpreter (Entree & is) override virtual
Fonction principale de l'interprete.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Interprete.
Definition at line 143 of file Integrer_champ_med.cpp.
{
  Motcle nom_methode;
  Nom nom_fichier("integrale");
  Nom nom_champ_fonc_med;
  double zmin=0,zmax=0;
  int nb_tranche=1;
  Param param(que_suis_je());
  param.ajouter("champ_med",&nom_champ_fonc_med,Param::REQUIRED);
  param.ajouter("methode",&nom_methode,Param::REQUIRED);
  param.ajouter("zmin",&zmin);
  param.ajouter("zmax",&zmax);
  param.ajouter("nb_tranche",&nb_tranche);
  param.ajouter("fichier_sortie",&nom_fichier);
  param.lire_avec_accolades_depuis(is);
  if ((nom_methode!="integrale_en_z")&&(nom_methode!="debit_total"))
    {
      Cerr<<"method "<<nom_methode <<" not coded yet "<<finl;
    }
// on recupere le domaine
  if(! sub_type(Champ_Fonc_MED, objet(nom_champ_fonc_med)))
    {
      Cerr << nom_champ_fonc_med << " type is " << objet(nom_champ_fonc_med).que_suis_je() << finl;
      Cerr << "only the objects of type Champ_Fonc_MED can be meshed" << finl;
      exit();
    }
  Champ_Fonc_MED& champ=ref_cast(Champ_Fonc_MED, objet(nom_champ_fonc_med));
  const Zone& zone=champ.zone_dis_base().zone();
  const DoubleTab& coord=zone.domaine().les_sommets();
// on fait une coie pour les modifier
  IntTab les_elems_mod=zone.les_elems();
  const IntTab&  les_elems=zone.les_elems();
  ArrOfDouble normal(3);
  const DoubleTab& valeurs= champ.valeurs();
  assert(valeurs.dimension(0)==zone.nb_elem());
  assert(valeurs.dimension(1)==3);
  double dz=(zmax-zmin)/nb_tranche;
  ArrOfDouble res(nb_tranche),pos(nb_tranche),surface(nb_tranche);
  int nb_elem=les_elems.dimension(0);
  Cerr<<" Field integration using the method "<<nom_methode<<" on the domain "<<zone.domaine().le_nom() <<finl;
  if (nom_methode=="debit_total")
    {
      nb_tranche=1;
      zmax=DMAXFLOAT/2.;
      zmin=-zmax;
      dz=(zmax-zmin);
      pos[0]=0;
    }
// if (nom_methode=="integrale_en_z")
  {
// Etape 1 on reordonne les triangles pour classeren z les sommets
    for (int elem=0; elem<nb_elem; elem++)
      {
        DoubleTab zz(3,2);
        for (int i=0; i<3; i++)
          {
            int s=les_elems(elem,i);
            zz(i,1)=s;
            zz(i,0)=coord(s,2);
          }
        qsort(zz.addr(),3,sizeof(double) * 2 , fonction_tri_data);
        for (int i=0; i<3; i++)
          {
            int ss=(int)zz(i,1);
// if (ss!=les_elems(elem,i)) Cerr<<" coucou" <<elem<<finl;
            les_elems_mod(elem,i)=ss;
          }
      }
//
    ArrOfDouble point0(3),point1(3),point2(3);
    for (int elem=0; elem<nb_elem; elem++)
      {
        for (int i=0; i<3; i++)
          {
            point0[i]=coord(les_elems(elem,0),i);
            point1[i]=coord(les_elems(elem,1),i);
            point2[i]=coord(les_elems(elem,2),i);
          }
        calcul_normal_norme(point0,point1,  point2, normal);
        for (int i=0; i<3; i++)
          {
            point0[i]=coord(les_elems_mod(elem,0),i);
            point1[i]=coord(les_elems_mod(elem,1),i);
            point2[i]=coord(les_elems_mod(elem,2),i);
          }
        for (int tranche=0; tranche<nb_tranche; tranche++)
          {
            double zminl=(zmin)+(zmax-zmin)/nb_tranche*tranche;
            double zmaxl=zminl+dz;
            pos[tranche]=(zminl+zmaxl)/2.;
            double z0=coord(les_elems_mod(elem,0),2);
            if (z0<=zmaxl)
              {
                double z2=coord(les_elems_mod(elem,2),2);
                if (z2>=zminl)
                  {
                    double portion=portion_surface(point0,point1,point2,zminl,zmaxl);
                    double prod_scal=0;
                    for (int i=0; i<3; i++)
                      prod_scal+=valeurs(elem,i)*normal[i];
                    res[tranche]+=portion*prod_scal;
                    surface[tranche]+=portion;
                  }
              }
          }
      }
  }
  double trace=0;
  SFichier so(nom_fichier);
  for (int nb=0; nb<nb_tranche; nb++)
    {
      trace+=res[nb];
      if (surface[nb]!=0)
        res[nb]/=surface[nb];
      else assert(res[nb]==0);
    }
  Cout<<"# overall balance "<<trace<<finl;
  so<<"# bilan global "<<trace<<finl;
  so<<"# position, valeur moyenne, surface, flux"<<finl;
  for (int nb=0; nb<nb_tranche; nb++)
    so << pos[nb]<<" "<<res[nb]<<" "<<surface[nb]<<" "<<res[nb]*surface[nb]<<finl;
  return is;
}
References TRUSTArray< _TYPE_ >::addr(), Param::ajouter(), calcul_normal_norme(), Cerr, Cout, TRUSTTab< _TYPE_ >::dimension(), DMAXFLOAT, Zone::domaine(), Process::exit(), finl, fonction_tri_data(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Param::lire_avec_accolades_depuis(), Zone::nb_elem(), nom_fichier(), Interprete::objet(), portion_surface(), Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, sub_type, Champ_Fonc_MED::valeurs(), Zone_dis_base::zone(), and Champ_Fonc_MED::zone_dis_base().
printOn()
Sortie & Integrer_champ_med::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 37 of file Integrer_champ_med.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Integrer_champ_med::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 56 of file Integrer_champ_med.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Integrer_champ_med & Integrer_champ_med::self_cast (const Objet_U & r) static
Definition at line 21 of file Integrer_champ_med.cpp.
self_cast() [2/2]
Integrer_champ_med & Integrer_champ_med::self_cast (Objet_U & r) static
Definition at line 21 of file Integrer_champ_med.cpp.
taille_memoire()
unsigned Integrer_champ_med::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Integrer_champ_med.cpp.
Member Data Documentation
info_obj
const Type_info Integrer_champ_med::info_obj static
Definition at line 39 of file Integrer_champ_med.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Integrer_champ_med.h
src/Kernel/MEDimpl/Integrer_champ_med.cpp