TRUST: Pbc_MED Class Reference
Pbc_MED Class Reference
#include <Pb_MED.h>
Public Member Functions
Pbc_MED ()
~Pbc_MED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Probleme_Couple
Probleme_Couple ()
~Probleme_Couple ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
double computeTimeStep (bool &stop) const override
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
bool solveTimeStep () override
pour recodage eventuel et appel unifie en python
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
void ajouter (Probleme_base &)
Ajoute un probleme a la liste des problemes couples.
Met en place la reference du probleme vers this.
Verifie que l'ordre conduction, thHyd est respecte.
int associer_ (Objet_U &) override
Surcharge Objet_U::associer_(Objet_U&)
Associe un objet au probleme couple, en verifiant le type
dynamiquement. L'objet peut-etre:
- un schema en temps (Schema_Temps_base), et on l'associe aux problemes
- un probleme (Probleme_base), on l'ajoute a la liste.
virtual void associer_sch_tps_base (Schema_Temps_base &)
Associe une copie du schema en temps a chaque probleme
du Probleme couple.
virtual const Schema_Temps_base & schema_temps () const
Renvoie le schema en temps associe aux problemes couples.
(version const)
virtual Schema_Temps_base & schema_temps ()
Renvoie le schema en temps associe aux problemes couples.
virtual void discretiser (const Discretisation_base &)
Associe une discretisation a tous les problemes du probleme
couple.
Appelle Probleme_Base::discretiser(const Discretisation_base&)
sur chacun des problemes du probleme couple.
voir Probleme_Base::discretiser(const Discretisation_base&)
virtual void mettre_a_jour_modele_rayo (double temps)
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
Public Member Functions inherited from Couplage_U
Couplage_U ()
~Couplage_U ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void initialize () override
This method is called once at the beginning, before any other one of
the interface Problem.
void terminate () override
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
double presentTime () const override
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
bool initTimeStep (double dt) override
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
void validateTimeStep () override
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
bool isStationary () const override
Tells if the Problem unknowns have changed during the last time step.
void setStationary (bool) override
Tells to the Problem that stationary is reached or not.
void abortTimeStep () override
Aborts the resolution of the current time step.
bool iterateTimeStep (bool &converged) override
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
void getInputFieldsNames (Noms &noms) const override
This method is used to find the names of input fields understood by the Problem.
void getOutputFieldsNames (Noms &noms) const override
This method is used to find the names of output fields understood by the Problem.
int postraiter (int force=1) override
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
int limpr () const override
Doit-on imprimer les statistiques d'execution maintenant ?
int lsauv () const override
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
void sauver () const override
Sauvegarder l'etat du probleme sur disque.
bool updateGivenFields () override
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
double futureTime () const override
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
Ref_Field_base findInputField (const Nom &name) const override
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
Ref_Champ_Generique_base findOutputField (const Nom &name) const override
void addProblem (Probleme_U &)
Append a problem to the list.
int nb_problemes () const
Number of problems.
const Probleme_U & probleme (int i) const
Access by index (const)
Probleme_U & probleme (int i)
Access by index.
const Probleme_U & probleme (const Nom &nom_pb) const
Access by name (const)
Probleme_U & probleme (const Nom &nom_pb)
Access by name.
int indice_probleme (const Nom &nom_pb) const
Index from name.
Public Member Functions inherited from Probleme_U
Probleme_U ()
~Probleme_U () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual void initialize ()
This method is called once at the beginning, before any other one of
the interface Problem.
virtual void terminate ()
This method is called once at the end, after any other one.
It frees the memory and saves anything that needs to be saved.
virtual double presentTime () const
Returns the present time.
This value may change only at the call of validateTimeStep.
A surcharger.
virtual double computeTimeStep (bool &stop) const
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep,
but it is a hint.
This method may use all the internal state of the Problem.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual bool solveTimeStep ()
pour recodage eventuel et appel unifie en python
virtual void validateTimeStep ()
Validates the calculated unknown by moving the present time
at the end of the time step.
This method is allowed to free past values of the unknown and given
fields.
virtual bool isStationary () const
Tells if the Problem unknowns have changed during the last time step.
virtual void setStationary (bool)
Tells to the Problem that stationary is reached or not.
virtual void abortTimeStep ()
Aborts the resolution of the current time step.
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void getInputFieldsNames (Noms &noms) const
This method is used to find the names of input fields understood by the Problem.
virtual void getInputFieldTemplate (const Nom &name, ICoCo::TrioField &afield) const
This method is used to get a template of a field expected for the given name.
virtual void setInputField (const Nom &name, const ICoCo::TrioField &afield)
This method is used to provide the Problem with an input field.
virtual void getOutputFieldsNames (Noms &noms) const
This method is used to find the names of output fields understood by the Problem.
virtual void getOutputField (const Nom &nameField, ICoCo::TrioField &afield) const
virtual void setInputIntValue (const Nom &name, const int &val)
virtual int getOutputIntValue (const Nom &name) const
virtual void setInputDoubleValue (const Nom &name, const double val)
virtual int postraiter (int force=1)
Demande au probleme de postraiter ses champs, sondes,...
Dans Probleme_U::run(), postraiter() est appele a chaque pas de
temps avec force=0 et au debut et a la fin du calcul avec force=1.
WEC : il serait bon que, un jour, postraiter soit const.
virtual int limpr () const
Doit-on imprimer les statistiques d'execution maintenant ?
virtual int lsauv () const
Doit-on sauvegarder l'etat du probleme sur disque maintenant ?
virtual void sauver () const
Sauvegarder l'etat du probleme sur disque.
virtual bool updateGivenFields ()
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant
que certains vont chercher eux-memes des informations dans les
problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre
rendu independant de l'exterieur, et peut du coup rejoindre
initTimeStep.
Le reste passe dans l'interface d'echange de champs.
Ce travail sera fini quand updateGivenFields sera vide et supprime !
virtual double futureTime () const
Returns the future time (end of current computing interval)
This value is valid between initTimeStep and either
validateTimeStep or abortTimeStep.
A surcharger.
virtual bool run ()
Cette methode est une sorte de main() du Problem
Elle peut etre utilisee si le probleme n'est couple a aucun autre.
(s'il n'a besoin d'aucun champ d'entree).
virtual bool runUntil (double time)
This method has the same role as the method run, but it stops
when reaching the time given in parameter.
If this time cannot be reached, the method returns false.
virtual Ref_Field_base findInputField (const Nom &name) const
This method is used to find in a hierarchy of problems the
Champ_Input_Proto of a given name.
Implementation is not optimal in 2 ways :
- no error if two input fields have the same name.
- no optimisation of the number of REF objects created and destroyed.
virtual Ref_Champ_Generique_base findOutputField (const Nom &name) const
void nommer (const Nom &) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Pbc_MED & self_cast (Objet_U &)
static const Pbc_MED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_Couple
static Objet_U * cree_instance ()
static const Type_info * info ()
static Probleme_Couple & self_cast (Objet_U &)
static const Probleme_Couple & self_cast (const Objet_U &)
Static Public Member Functions inherited from Couplage_U
static Objet_U * cree_instance ()
static const Type_info * info ()
static Couplage_U & self_cast (Objet_U &)
static const Couplage_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Probleme_U
static const Type_info * info ()
static Probleme_U & self_cast (Objet_U &)
static const Probleme_U & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Probleme_Couple
static const Type_info info_obj
Static Public Attributes inherited from Couplage_U
static const Type_info info_obj
Static Public Attributes inherited from Probleme_U
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime les problemes couples sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime les problemes couples sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
A surcharger...
Entree & readOn (Entree &) override
A surcharger...
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Schema_Temps sch_
Additional Inherited Members
Protected Attributes inherited from Probleme_Couple
ArrOfInt groupes
Vect_Schema_Temps sch_clones
Protected Attributes inherited from Probleme_U
Nom nom
ScalarRegister reg
Detailed Description
Definition at line 84 of file Pb_MED.h.
Constructor & Destructor Documentation
Pbc_MED()
Pbc_MED::Pbc_MED ()
Definition at line 23 of file Pb_MED.cpp.
~Pbc_MED()
Pbc_MED::~Pbc_MED ()
Definition at line 23 of file Pb_MED.cpp.
Member Function Documentation
cree_instance()
Objet_U * Pbc_MED::cree_instance () static
Definition at line 23 of file Pb_MED.cpp.
duplique()
int Pbc_MED::duplique () const override virtual
Reimplemented from Probleme_Couple.
Definition at line 23 of file Pb_MED.cpp.
get_info()
const Type_info * Pbc_MED::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Probleme_Couple.
Definition at line 23 of file Pb_MED.cpp.
info()
const Type_info * Pbc_MED::info () static
Definition at line 23 of file Pb_MED.cpp.
printOn()
Sortie & Pbc_MED::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
Imprime les problemes couples sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Probleme_Couple.
Definition at line 44 of file Pb_MED.cpp.
{
  return s;
}
readOn()
Entree & Pbc_MED::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
< fin du readOn
Reimplemented from Probleme_Couple.
Definition at line 48 of file Pb_MED.cpp.
{
  int nmax=10,npb=0;
  sch_.typer("Schema_Euler_explicite");
// Schema_Euler_explicite& sch=ref_cast(Schema_Euler_explicite,sch_.valeur());
  Schema_Temps_base& sch=ref_cast(Schema_Temps_base,sch_.valeur());
  sch.changer_temps_courant(-1.);
  associer_sch_tps_base(sch);
// Pb_MED* listpb;
// On cree une liste de DerObjU car c'est eux que l'on peut ajouter a l'interprete...
  DerObjU* listob =new DerObjU[nmax];
  Motcle accouv("{"),accfer("}"),virg(","),motlu;
  is >> motlu;
  if (motlu!=accouv)
    {
      Cerr<<" One expects { to begin the read of Pbc_Med"<<finl;
      exit();
    }
  Interprete_bloc inter;
  while (motlu!=accfer)
    {
      assert((motlu==virg)||(motlu==accouv));
      if (npb>=nmax)
        {
          Cerr<<"The number of coupled problems is to large"<<finl;
          exit();
        }
      Nom nom_numero(npb);
      Nom nompb("pbMED_");
      nompb+=nom_numero;
      DerObjU& ob= listob[npb];
      ob.typer("Pb_MED");
      inter.ajouter(nompb,ob);
      Pb_MED& pb=ref_cast(Pb_MED,inter.objet_global(nompb));
      pb.nommer(nompb);
      associer_(pb);
      pb.associer_sch_tps_base(sch);
      is >> pb;
      npb++;
      is >> motlu;
      if ((motlu!=accfer)&&(motlu!=virg))
        {
          Cerr<<"One expects } or , between the problems "<<finl;
          Cerr<<"and not "<<motlu<<finl;
          exit();
        }
    }
  for (int i=0; i<nb_problemes(); i++)
    ref_cast(Probleme_base,probleme(i)).init_postraitements();
// On oublie les axi, car les inconnues ont deja eu le traitement
// apres l'init pour ecrire correctement les geom
  bidim_axi=0;
  axi=0;
// const Probleme_base& pb1=les_problemes[0].valeur();
  const ArrOfDouble& temps_sauv=ref_cast(Pb_MED,inter.objet_global("pbMED_0")).temps_sauv();
  int nbpasdetemps=temps_sauv.size_array();
  Cerr<<"nbpasdetemps "<<nbpasdetemps<<finl;
  for (int i=0; i<nbpasdetemps; i++)
    {
      schema_temps().mettre_a_jour();
      schema_temps().changer_temps_courant(temps_sauv[i]);
      postraiter();
    }
  if (nbpasdetemps==1)
    {
// pour eviter bug meshtv
// postraiter();
    }
  for (int i=0; i<nb_problemes(); i++)
    ref_cast(Probleme_base,probleme(i)).finir();
  delete [] listob;
  return is;
}
References Interprete_bloc::ajouter(), Probleme_Couple::associer_(), Probleme_base::associer_sch_tps_base(), Probleme_Couple::associer_sch_tps_base(), Objet_U::axi, Objet_U::bidim_axi, Cerr, Schema_Temps_base::changer_temps_courant(), Process::exit(), finl, Schema_Temps_base::mettre_a_jour(), Couplage_U::nb_problemes(), Probleme_base::nommer(), Interprete_bloc::objet_global(), Couplage_U::postraiter(), Couplage_U::probleme(), ref_cast, sch_, Probleme_Couple::schema_temps(), TRUSTArray< _TYPE_ >::size_array(), Deriv_::typer(), and Deriv_Schema_Temps_base::valeur().
self_cast() [1/2]
const Pbc_MED & Pbc_MED::self_cast (const Objet_U & r) static
Definition at line 23 of file Pb_MED.cpp.
self_cast() [2/2]
Pbc_MED & Pbc_MED::self_cast (Objet_U & r) static
Definition at line 23 of file Pb_MED.cpp.
taille_memoire()
unsigned Pbc_MED::taille_memoire () const override virtual
Reimplemented from Probleme_Couple.
Definition at line 23 of file Pb_MED.cpp.
Member Data Documentation
info_obj
const Type_info Pbc_MED::info_obj static
Definition at line 87 of file Pb_MED.h.
sch_
Schema_Temps Pbc_MED::sch_ private
Definition at line 89 of file Pb_MED.h.
Referenced by readOn().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Pb_MED.h
src/Kernel/MEDimpl/Pb_MED.cpp