TRUST: Source Class Reference
Source Class Reference
classe Source
Classe generique de la hierarchie des sources, un objet Source peut
referencer n'importe quel d'objet derivant de Source_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
#include <Source.h>
Public Member Functions
Source ()
~Source ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const
Appel a l'objet sous-jacent.
Ajoute la contribution de la source au tableau passe en parametre.
DoubleTab & calculer (DoubleTab &) const
Appel a l'objet sous-jacent.
Affecte le terme source au tableau passe en parametre.
void mettre_a_jour (double temps)
Appel a l'objet sous-jacent.
Mise a jour (en temps) de la source.
void completer ()
Appel a l'objet sous-jacent.
Met a jour les references aux objets lies a l'objet Source.
int impr (Sortie &) const
Appel a l'objet sous-jacent.
Met a jour les references aux objets lies a l'objet Source.
void typer_direct (const Nom &)
void typer (const Nom &, const Equation_base &)
Type la source en calculant le nom du type necessaire
grace aux parametres fournis.
int initialiser (double temps)
Appel a l'objet sous-jacent.
Public Member Functions inherited from Deriv_Source_base
~Deriv_Source_base ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Deriv_Source_base ()
Deriv_Source_base (const Deriv_Source_base &)
const Source_base & valeur () const
Source_base & valeur ()
const Source_base * operator-> () const
Source_base * operator-> ()
const Deriv_Source_base & operator= (const Source_base &)
const Deriv_Source_base & operator= (const Deriv_Source_base &)
operator const Source_base & () const
operator Source_base & ()
const Type_info & get_info_ptr () const override
Public Member Functions inherited from Deriv_
Deriv_ ()
~Deriv_ () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void detach ()
Objet_U * typer (const char *nom_type)
Essaie de creer une instance du type "type".
si type n'est pas un type ou type n'est pas instanciable=>arret
si type n'est pas un sous-type du type du pointeur=>retour 0
si ok, renvoie l'adresse de l'objet cree.
int associer_ (Objet_U &) override
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
Public Member Functions inherited from O_U_Ptr
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int non_nul () const
Renvoie 1 si le pointeur est non_nul
Renvoie 0 sinon.
const Nom & le_nom () const override
Renvoie ref_().le_nom() si le pointeur est non nul
ou "Pointeur Nul".
virtual const Type_info & get_info_ptr () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Source & self_cast (Objet_U &)
static const Source & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_Source_base
static Objet_U * cree_instance ()
static const Type_info * info ()
static Deriv_Source_base & self_cast (Objet_U &)
static const Deriv_Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Deriv_
static const Type_info * info ()
static Deriv_ & self_cast (Objet_U &)
static const Deriv_ & self_cast (const Objet_U &)
Static Public Member Functions inherited from O_U_Ptr
static const Type_info * info ()
static O_U_Ptr & self_cast (Objet_U &)
static const O_U_Ptr & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Deriv_Source_base
static const Type_info info_obj
Static Public Attributes inherited from Deriv_
static const Type_info info_obj
Static Public Attributes inherited from O_U_Ptr
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Impression de la source sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture de la source sur un flot d'entree.
Protected Member Functions inherited from Deriv_Source_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_O_U_Ptr (Objet_U *) override
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Protected Member Functions inherited from Deriv_
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from O_U_Ptr
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
~O_U_Ptr () override
Destructeur. Il ne detruit pas l'objet en reference.
O_U_Ptr ()
construit un pointeur nul (cle a -1)
virtual void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
virtual Objet_U * get_O_U_Ptr () const
Renvoie un pointeur sur l'Objet_U associe
ATTENTION: l'adresse peut etre nulle (si le pointeur est nul)
int get_ptr_cle () const
int get_ptr_object_id () const
void recopie (const Objet_U &)
Duplique l'Objet_U obj puis change le pointeur vers cette copie.
int change_num (const int *const) override
renumerotation des objets
Objet_U * get_O_U_Ptr_check () const
Verifie si le pointeur est valide. Le pointeur est valide
si cle_==-1
ou si la_memoire().objet_u(cle_) a le meme object_id_ que
celui enregistre dans ptr_object_id_.
Si le pointeur n'est pas valide, arret du programme.
Renvoie l'adresse de l'objet pointe (de type Objet_U)
int check_O_U_Ptr_type (const Objet_U *ptr) const
Verifie que l'objet pointe par ptr est d'un type acceptable
pour le pointeur (avec get_info_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Source
Classe generique de la hierarchie des sources, un objet Source peut
referencer n'importe quel d'objet derivant de Source_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
Declare_deriv().;
Definition at line 38 of file Source.h.
Constructor & Destructor Documentation
Source()
Source::Source ()
Definition at line 25 of file Source.cpp.
~Source()
Source::~Source ()
Definition at line 25 of file Source.cpp.
Member Function Documentation
ajouter()
DoubleTab & Source::ajouter (DoubleTab & xx) const
Appel a l'objet sous-jacent.
Ajoute la contribution de la source au tableau passe en parametre.
Returns
DoubleTab&
Signification: le parametre xx modifie
Contraintes:
Definition at line 195 of file Source.cpp.
{
  statistiques().begin_count(source_counter_);
  DoubleTab& tmp = valeur().ajouter(xx);
  statistiques().end_count(source_counter_);
  return tmp;
}
References Source_base::ajouter(), Statistiques::begin_count(), Statistiques::end_count(), source_counter_, statistiques(), and Deriv_Source_base::valeur().
Referenced by Source_QC_QDM_Gen::ajouter().
calculer()
DoubleTab & Source::calculer (DoubleTab & xx) const
Appel a l'objet sous-jacent.
Affecte le terme source au tableau passe en parametre.
Returns
DoubleTab&
Signification: le parametre xx modifie
Contraintes:
Definition at line 218 of file Source.cpp.
{
  statistiques().begin_count(source_counter_);
  DoubleTab& tmp = valeur().calculer(xx);
  statistiques().end_count(source_counter_);
  return tmp;
}
References Statistiques::begin_count(), Source_base::calculer(), Statistiques::end_count(), source_counter_, statistiques(), and Deriv_Source_base::valeur().
completer()
void Source::completer (void)
Appel a l'objet sous-jacent.
Met a jour les references aux objets lies a l'objet Source.
Definition at line 136 of file Source.cpp.
{
  valeur().completer();
}
References Source_base::completer(), and Deriv_Source_base::valeur().
Referenced by Source_QC_QDM_Gen::completer().
cree_instance()
Objet_U * Source::cree_instance () static
Definition at line 25 of file Source.cpp.
duplique()
int Source::duplique () const override virtual
Reimplemented from Deriv_Source_base.
Definition at line 25 of file Source.cpp.
get_info()
const Type_info * Source::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Source_base.
Definition at line 25 of file Source.cpp.
impr()
int Source::impr (Sortie & os) const
Appel a l'objet sous-jacent.
Met a jour les references aux objets lies a l'objet Source.
Definition at line 156 of file Source.cpp.
{
  return valeur().impr(os);
}
References Source_base::impr(), and Deriv_Source_base::valeur().
Referenced by Source_QC_QDM_Gen::impr().
info()
const Type_info * Source::info () static
Definition at line 25 of file Source.cpp.
initialiser()
int Source::initialiser (double temps)
Appel a l'objet sous-jacent.
Definition at line 175 of file Source.cpp.
{
  return valeur().initialiser(temps);
}
References Source_base::initialiser(), and Deriv_Source_base::valeur().
mettre_a_jour()
void Source::mettre_a_jour (double temps) inline
Appel a l'objet sous-jacent.
Mise a jour (en temps) de la source.
Definition at line 67 of file Source.h.
{
  valeur().mettre_a_jour(temps);
}
References Source_base::mettre_a_jour(), and Deriv_Source_base::valeur().
Referenced by Source_QC_QDM_Gen::mettre_a_jour().
printOn()
Sortie & Source::printOn (Sortie & os) const override protected virtual
Impression de la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Deriv_Source_base.
Definition at line 42 of file Source.cpp.
{
  return DERIV(Source_base)::printOn(os);
}
References DERIV, and printOn().
Referenced by printOn().
readOn()
Entree & Source::readOn (Entree & is) override protected virtual
Lecture de la source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Deriv_Source_base.
Definition at line 62 of file Source.cpp.
{
  return DERIV(Source_base)::readOn(is);
}
References DERIV, and readOn().
Referenced by readOn().
self_cast() [1/2]
const Source & Source::self_cast (const Objet_U & r) static
Definition at line 25 of file Source.cpp.
self_cast() [2/2]
Source & Source::self_cast (Objet_U & r) static
Definition at line 25 of file Source.cpp.
taille_memoire()
unsigned Source::taille_memoire () const override virtual
Reimplemented from Deriv_Source_base.
Definition at line 25 of file Source.cpp.
typer()
void Source::typer (const Nom & typ, const Equation_base & eqn)
Type la source en calculant le nom du type necessaire
grace aux parametres fournis.
Definition at line 108 of file Source.cpp.
{
  Nom type= eqn.discretisation().get_name_of_type_for(que_suis_je(),typ,eqn);
  if (eqn.que_suis_je() == "Transport_Marqueur_FT")
    type = typ;
  Cerr << type << finl;
// Cout << "Dans source.cpp type source = " << type << finl;
  DERIV(Source_base)::typer(type);
}
References Cerr, DERIV, Equation_base::discretisation(), finl, Discretisation_base::get_name_of_type_for(), Objet_U::que_suis_je(), and typer().
Referenced by Sources::readOn(), typer(), and typer_direct().
typer_direct()
void Source::typer_direct (const Nom & typ)
Definition at line 81 of file Source.cpp.
{
// Cerr << "Source::typer_direct()" << finl;
  DERIV(Source_base)::typer(typ);
}
References DERIV, and typer().
Referenced by Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Navier_Stokes_std::completer(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), and Source_QC_QDM_Gen::readOn_spec().
Member Data Documentation
info_obj
const Type_info Source::info_obj static
Definition at line 40 of file Source.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Source.h
src/Kernel/Framework/Source.cpp