TRUST: Deriv_Turbulence_paroi_scal_base Class Reference
Deriv_Turbulence_paroi_scal_base Class Reference
#include <Turbulence_paroi_scal.h>
Public Member Functions
~Deriv_Turbulence_paroi_scal_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Deriv_Turbulence_paroi_scal_base ()
Deriv_Turbulence_paroi_scal_base (const Deriv_Turbulence_paroi_scal_base &)
const Turbulence_paroi_scal_base & valeur () const
Turbulence_paroi_scal_base & valeur ()
const Turbulence_paroi_scal_base * operator-> () const
Turbulence_paroi_scal_base * operator-> ()
const
Deriv_Turbulence_paroi_scal_base & operator= (const Turbulence_paroi_scal_base &)
const
Deriv_Turbulence_paroi_scal_base & operator= (const Deriv_Turbulence_paroi_scal_base &)
operator const Turbulence_paroi_scal_base & () const
operator Turbulence_paroi_scal_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Deriv_Turbulence_paroi_scal_base & self_cast (Objet_U &)
static const
Deriv_Turbulence_paroi_scal_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Turbulence_paroi_scal_base * pointeur_
Detailed Description
Definition at line 33 of file Turbulence_paroi_scal.h.
Constructor & Destructor Documentation
Deriv_Turbulence_paroi_scal_base::~Deriv_Turbulence_paroi_scal_base ()
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Deriv_Turbulence_paroi_scal_base::Deriv_Turbulence_paroi_scal_base ()
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Deriv_Turbulence_paroi_scal_base::Deriv_Turbulence_paroi_scal_base (const Deriv_Turbulence_paroi_scal_base & t)
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Member Function Documentation
Objet_U * Deriv_Turbulence_paroi_scal_base::cree_instance () [static]
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
int Deriv_Turbulence_paroi_scal_base::duplique () const [virtual]
Implements Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Type_info * Deriv_Turbulence_paroi_scal_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Type_info & Deriv_Turbulence_paroi_scal_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Type_info * Deriv_Turbulence_paroi_scal_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Deriv_Turbulence_paroi_scal_base::operator const Turbulence_paroi_scal_base & () const
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Deriv_Turbulence_paroi_scal_base::operator Turbulence_paroi_scal_base & ()
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Turbulence_paroi_scal_base * Deriv_Turbulence_paroi_scal_base::operator-> () const [inline]
Definition at line 33 of file Turbulence_paroi_scal.h.
: public DERIV(Turbulence_paroi_scal_base)
Turbulence_paroi_scal_base * Deriv_Turbulence_paroi_scal_base::operator-> () [inline]
Definition at line 33 of file Turbulence_paroi_scal.h.
: public DERIV(Turbulence_paroi_scal_base)
const Deriv_Turbulence_paroi_scal_base & Deriv_Turbulence_paroi_scal_base::operator= (const Deriv_Turbulence_paroi_scal_base & t)
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Deriv_Turbulence_paroi_scal_base & Deriv_Turbulence_paroi_scal_base::operator= (const Turbulence_paroi_scal_base & t)
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Sortie & Deriv_Turbulence_paroi_scal_base::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Entree & Deriv_Turbulence_paroi_scal_base::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Deriv_Turbulence_paroi_scal_base & Deriv_Turbulence_paroi_scal_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
Deriv_Turbulence_paroi_scal_base & Deriv_Turbulence_paroi_scal_base::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
void Deriv_Turbulence_paroi_scal_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
unsigned Deriv_Turbulence_paroi_scal_base::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Turbulence_paroi_scal.
Definition at line 31 of file Turbulence_paroi_scal.cpp.
const Turbulence_paroi_scal_base & Deriv_Turbulence_paroi_scal_base::valeur () const [inline]
Definition at line 33 of file Turbulence_paroi_scal.h.
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), Turbulence_paroi_scal::calculer_scal(), Turbulence_paroi_scal::imprimer_nusselt(), Turbulence_paroi_scal::init_lois_paroi(), Turbulence_paroi_scal::readOn(), Turbulence_paroi_scal::tab_equivalent_distance(), and Turbulence_paroi_scal::tab_equivalent_distance_size().
: public DERIV(Turbulence_paroi_scal_base)
Turbulence_paroi_scal_base & Deriv_Turbulence_paroi_scal_base::valeur () [inline]
Definition at line 33 of file Turbulence_paroi_scal.h.
: public DERIV(Turbulence_paroi_scal_base)
Member Data Documentation
const Type_info Deriv_Turbulence_paroi_scal_base::info_obj [static]
Reimplemented from Deriv_.
Reimplemented in Turbulence_paroi_scal.
Definition at line 33 of file Turbulence_paroi_scal.h.
Turbulence_paroi_scal_base* Deriv_Turbulence_paroi_scal_base::pointeur_ [private]
Definition at line 33 of file Turbulence_paroi_scal.h.
The documentation for this class was generated from the following files:
src/ThHyd/Modele_turbulence_base/Turbulence_paroi_scal.h
src/ThHyd/Modele_turbulence_base/Turbulence_paroi_scal.cpp