TRUST: Champ_Fonc_MED Class Reference
Champ_Fonc_MED Class Reference
classe Champ_Fonc_MED
#include <Champ_Fonc_MED.h>
Public Member Functions
Champ_Fonc_MED ()
~Champ_Fonc_MED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
void mettre_a_jour (double) override
Mise a jour en temps du champ.
int creer (const Nom &, const Domaine &dom, const Motcle &localisation, ArrOfDouble &temps_sauv)
const Domaine & domaine () const
virtual void lire (double tps, int given_iteration=-1)
int nb_pas_temps ()
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const override
renvoie les valeurs aux sommets du Domaine dom
DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const override
renvoie la compo eme valeur aux sommets de dom.
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
DoubleTab & remplir_coord_noeuds (DoubleTab &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual const Champ_Fonc_base & le_champ () const
virtual Champ_Fonc_base & le_champ ()
const ArrOfDouble & get_saved_times (void) const
Public Member Functions inherited from Champ_Fonc_base
Champ_Fonc_base ()
~Champ_Fonc_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps du champ.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
Reprise a partir d'un flot d'entree
Lit le temps et les valeurs du champ.
Saute un bloc si le nom du champ est "anonyme".
int sauvegarder (Sortie &) const override
Sauvegarde le champ sur un flot de sortie
Ecrit le nom, le temps et les valeurs.
Champ_base & affecter_ (const Champ_base &) override
Affecte un Champ_base dans un Champ_Fonc_base.
Champ_base & affecter_compo (const Champ_base &, int compo) override
Affecte une composante d'un Champ_base dans la meme composnate
d'un Champ_Fonc_base.
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
NE FAIT RIEN
A surcharger dans les classes derivees.
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
const Domaine & domaine () const
int a_une_zone_dis_base () const override
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void creer_espace_distant (int dummy)
Public Member Functions inherited from Champ_Don_base
Champ_Don_base ()
~Champ_Don_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void mettre_a_jour (double temps) override
Mise a jour en temps.
Parametre: double
Signification: le temps de mise a jour.
void dimensionner (int, int)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parametre: int
Signification: le nombre de noeud par composante du champ (le nombre de dl par composante)
Parametre: int
Signification: le nombre de composante du champ.
int imprime (Sortie &, int) const override
NE FAIT RIEN. EXIT ! A surcharger dans les classes derivees.
int fixer_nb_valeurs_nodales (int nb_noeuds) override
Fixe le nombre de degres de liberte par composante
Parametre: int nb_noeuds
Signification: le nombre de degre de liberte par composante.
int reprendre (Entree &) override
NE FAIT RIEN. A surcharger dans les classes derivees.
int sauvegarder (Sortie &) const override
NE FAIT RIEN. A surcharger dans les classes derivees.
DoubleTab & valeurs () override
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
const DoubleTab & valeurs () const override
Champ_base & affecter_ (const Champ_base &) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
Champ_base & affecter_compo (const Champ_base &, int) override
Provoque une erreur ! A surcharger par les classes derivees !
non virtuelle pure par commoditees de developpement !
virtual int initialiser (const double temps)
NE FAIT RIEN. A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire.
int nb_valeurs_nodales () const override
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
operator DoubleTab & ()=delete
operator const DoubleTab & () const =delete
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
Public Member Functions inherited from Champ_base
~Champ_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide,
donne le nom "anonyme" au champ et lui donne une nature
scalaire.
virtual int nb_valeurs_nodales () const
double temps () const
Renvoie le temps du champ.
virtual double changer_temps (const double t)
Fixe le temps auquel se situe le champ.
virtual int fixer_nb_valeurs_nodales (int n)
virtual void associer_zone_dis_base (const Zone_dis_base &)
virtual const Zone_dis_base & zone_dis_base () const
virtual int a_une_zone_dis_base () const
Par defaut, on ne sait pas si une zone_dis_base sera definie.
virtual void mettre_a_jour (double)
mettre_a_jour de la classe de base Champ_base :ne fait rien !
virtual void abortTimeStep ()
virtual Champ_base & affecter_ (const Champ_base &)=0
Champ_base & affecter (const Champ_base &)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
void affecter_erreur ()
virtual Champ_base & affecter_compo (const Champ_base &, int compo)=0
virtual int imprime (Sortie &, int) const =0
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
Calcule la valeur ponctuelle de la composante "compo" du champ
au point de coordonnees pos.
Dans la classe de base, l'implementation appelle
valeur_a(const DoubleVect &, DoubleVect &)
Parametre: DoubleVect&
Signification: les coordonnees du point de calcul
Parametre: int
Signification: l'index de la composante du champ a calculer.
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
Provoque une erreur !
Doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees.
virtual DoubleTab & valeur_aux_centres_de_gravite (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule
uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: pos
Signification: le tableau des coordonnees des points de calcul
(on ne traite pas l'espace virtuel du tableau)
Parametre: les_valeurs
Signification: tableau destination des valeurs a calculer.
Le tableau valeurs doit avoir la bonne taille en entree,
soit les_valeurs.size() == pos.dimension(0)
Parametre: compo
Signification: l'index de la composante du champ a calculer.
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
virtual DoubleTab & valeur_aux_elems_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs)
virtual DoubleVect & valeur_aux_elems_compo_smooth (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp)
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
virtual double valeur_a_sommet_compo (int, int, int) const
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
virtual DoubleTab & valeur_aux_sommets (const Domaine &, DoubleTab &) const
renvoie les valeurs aux sommets du Domaine dom
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &, DoubleVect &, int) const
renvoie la compo eme valeur aux sommets de dom.
virtual DoubleTab & valeur_aux_faces (DoubleTab &result) const
renvoie la valeur du champ aux faces
virtual DoubleTab valeur_aux_bords () const
renvoie la valeur du champ aux faces de bord
int calculer_valeurs_som_post (DoubleTab &valeurs, int nbsom, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_som_compo_post (DoubleTab &valeurs, int ncomp, int nbsom, Nom &nom_post, const Domaine &dom, int appliquer_cl=0) const
int calculer_valeurs_elem_post (DoubleTab &valeurs, int nbelem, Nom &nom_post, const Domaine &dom) const
int calculer_valeurs_elem_compo_post (DoubleTab &valeurs, int ncomp, int nbelem, Nom &nom_post, const Domaine &dom) const
void corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos
elle n'est pas const en realite !!!
virtual int completer_post_champ (const Domaine &dom, const int axi, const Nom &loc_post, const Nom &le_nom_champ_post, Format_Post_base &format) const
virtual void completer (const Zone_Cl_dis_base &zcl)
Public Member Functions inherited from Field_base
~Field_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Field_base ()
Field_base (const Field_base &other)=default
void nommer (const Nom &) override
Donne un nom au champ
Parametre: Nom& name
Signification: le nom a donner au champ.
const Nom & le_nom () const override
Renvoie le nom du champ.
const Noms & get_synonyms () const
void add_synonymous (const Nom &nom)
int nb_comp () const
Renvoie le nombre de composantes du champ.
virtual void fixer_nb_comp (int i)
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
const Noms & noms_compo () const
Renvoie le tableau des noms des composantes du champ.
const Nom & nom_compo (int) const
Renvoie le nom de la ieme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Valeurs par defaut:
Contraintes: i < nombre de composantes du champ.
const Nom & nom_compo () const
Renvoie le nom d'un champ scalaire.
virtual const Noms & fixer_noms_compo (const Noms &)
Fixe le nom des composantes du champ
Parametre: Noms& noms
Signification: le tableau des noms a donner aux composantes du champ.
virtual const Nom & fixer_nom_compo (int, const Nom &)
Fixe le nom de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut specifier le nom
Contraintes: i < nombre de composantes du champ
Parametre: Nom& nom
Signification: le nom a donner a la i-eme composante du champ.
virtual const Nom & fixer_nom_compo (const Nom &)
Fixe le nom d'un champ scalaire.
const Noms & unites () const
Renvoie les unites des composantes du champ.
const Nom & unite () const
Renvoie l'unite d'un champ scalaire dont toutes les composantes ont la meme unite.
const Nom & unite (int) const
Renvoie l'unite de la i-eme composante du champ
Parametre: int i
Signification: l'index de la composante du champ dont on veut connaitre l'unite.
virtual const Noms & fixer_unites (const Noms &)
Specifie les unites des composantes du champ.
Ces unites sont specifiees grace a un tableau de Nom et peuvent etre differentes pour chaque composante du champ.
Parametre: Noms& noms
Signification: les noms des unites des composantes du champ.
virtual const Nom & fixer_unite (const Nom &)
Specifie l'unite d'un champ scalaire ou dont toutes les composantes ont la meme unite
Parametre: Nom& nom
Signification: l'unite a specifier.
virtual const Nom & fixer_unite (int i, const Nom &)
Specifie l'unite de la i-eme composante du champ
Signification: l'index de la composante du champ dont on veut specifier l'unite
Parametre: Nom& nom
Signification: le type de l'unite a specifier.
Nature_du_champ nature_du_champ () const
Renvoie la nature d'un champ (scalaire, multiscalaire, vectoriel).
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parametre: Nature_du_champ n
Signification: la nature a donner au champ.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Champ_Proto
virtual ~Champ_Proto ()
virtual DoubleTab & valeurs ()=0
virtual const DoubleTab & valeurs () const =0
virtual DoubleTab & valeurs (double temps)
virtual const DoubleTab & valeurs (double temps) const
virtual DoubleTab & futur (int i=1)
virtual const DoubleTab & futur (int i=1) const
virtual DoubleTab & passe (int i=1)
virtual const DoubleTab & passe (int i=1) const
int lire_dimension (Entree &, const Nom &)
Verification de la dimension du champ
Renvoie la dimension du champ.
int lire_dimension (int dim, const Nom &le_nom_)
Verification de la dimension du champ
Renvoie la dimension du champ.
double operator() (int i, int j) const
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
(version const par valeur)
double & operator() (int i, int j)
Operateur d'indexation 2D.
Renvoie la composante (i,j) du champ.
double operator() (int i) const
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
(version const par valeur)
double & operator() (int i)
Operateur d'indexation 1D.
Renvoie la i-ieme composantes du champ.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Champ_Fonc_MED & self_cast (Objet_U &)
static const Champ_Fonc_MED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Fonc_base
static const Type_info * info ()
static Champ_Fonc_base & self_cast (Objet_U &)
static const Champ_Fonc_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_Don_base
static const Type_info * info ()
static Champ_Don_base & self_cast (Objet_U &)
static const Champ_Don_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Champ_base
static const Type_info * info ()
static Champ_base & self_cast (Objet_U &)
static const Champ_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Field_base
static const Type_info * info ()
static Field_base & self_cast (Objet_U &)
static const Field_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Champ_Fonc_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_Don_base
static const Type_info info_obj
Static Public Attributes inherited from Champ_base
static const Type_info info_obj
Static Public Attributes inherited from Field_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Member Functions inherited from Champ_Fonc_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual void creer_tableau_distribue (const MD_Vector &, Array_base::Resize_Options=Array_base::COPY_INIT)
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
Imprime le nom du champ sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture du nom d'un champ sur un flot d'entree.
Format:
nom_du_champ.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Domaine mon_dom
Domaine dom_med_
Zone_VF_inst zonebidon_inst
int numero_ch
int nb_dt
Nom nom_fichier_med_
Champ_Fonc vrai_champ_
Nom nom_champ_dans_fichier_med_
ArrOfInt filter
ArrOfDouble temps_sauv_
int last_time_only_
bool use_medcoupling_
Protected Attributes inherited from Champ_Don_base
DoubleTab valeurs_
Protected Attributes inherited from Champ_base
double temps_
Protected Attributes inherited from Field_base
Nom nom_
Noms noms_synonymes_
Noms noms_compo_
Noms unite_
int nb_compo_
Nature_du_champ nature_
Detailed Description
classe Champ_Fonc_MED
Definition at line 44 of file Champ_Fonc_MED.h.
Constructor & Destructor Documentation
Champ_Fonc_MED()
Champ_Fonc_MED::Champ_Fonc_MED ()
Definition at line 40 of file Champ_Fonc_MED.cpp.
                              :Champ_Fonc_base::Champ_Fonc_base()
{
  last_time_only_=0;
#ifdef MEDCOUPLING_
  use_medcoupling_ = true;
  field_type = MEDCoupling::ON_CELLS;
#else
  use_medcoupling_ = false;
#endif
}
References last_time_only_, and use_medcoupling_.
~Champ_Fonc_MED()
Champ_Fonc_MED::~Champ_Fonc_MED ()
Definition at line 38 of file Champ_Fonc_MED.cpp.
Member Function Documentation
associer_zone_dis_base()
void Champ_Fonc_MED::associer_zone_dis_base (const Zone_dis_base & la_zone_dis_base) inline override virtual
Reimplemented from Champ_base.
Definition at line 118 of file Champ_Fonc_MED.h.
{
  Cerr<<"Champ_Fonc_MED::associer_zone_dis_base does nothing"<<finl;
}
References Cerr, and finl.
cree_instance()
Objet_U * Champ_Fonc_MED::cree_instance () static
Definition at line 38 of file Champ_Fonc_MED.cpp.
creer()
int Champ_Fonc_MED::creer (const Nom & nom_fic, const Domaine & dom, const Motcle & localisation, ArrOfDouble & temps_sauv)
Definition at line 513 of file Champ_Fonc_MED.cpp.
{
#ifdef MED_
  nom_fichier_med_ = nom_fic;
  mon_dom=un_dom;
  int nbcomp,size;
  const Nom& type_elem=un_dom.zone(0).type_elem()->que_suis_je();
  Nom type_champ;
  nom_champ_dans_fichier_med_ = le_nom();
#ifdef MEDCOUPLING_
  if (use_medcoupling_)
    {
// MEDCoupling
      int mesh_dimension = -1;
      cell_type = type_geo_trio_to_type_medcoupling(type_elem, mesh_dimension);
      if (localisation != Nom())
        {
          if (localisation == "som")
            {
              field_type = MEDCoupling::ON_NODES;
              if ((cell_type == INTERP_KERNEL::NORM_QUAD4) || (cell_type == INTERP_KERNEL::NORM_HEXA8))
                type_champ = "Champ_Fonc_Q1_MED";
              else
                type_champ = "Champ_Fonc_P1_MED";
            }
          else if (localisation == "elem")
            {
              field_type = MEDCoupling::ON_CELLS;
              type_champ = "Champ_Fonc_P0_MED";
            }
          else
            {
              Cerr << localisation << " localization unknown." << finl;
              exit();
            }
        }
      std::string meshName = mon_dom.le_nom().getString();
      std::string fileName = nom_fic.getString();
// Try to guess the field name in the MED file:
      Noms fieldNamesGuess;
      fieldNamesGuess.add((Motcle)nom_champ_dans_fichier_med_+"_"+mon_dom.le_nom());
      if (localisation != Nom())
        fieldNamesGuess.add((Motcle)nom_champ_dans_fichier_med_+"_"+localisation+"_"+mon_dom.le_nom());
      fieldNamesGuess.add((Motcle)nom_champ_dans_fichier_med_);
      if (!fieldNamesGuess.contient_(nom_champ_dans_fichier_med_))
        fieldNamesGuess.add(nom_champ_dans_fichier_med_);
      bool ok = false;
      std::vector<std::string> fieldNames = GetAllFieldNamesOnMesh(fileName, meshName);
      for (int i=0; i<fieldNamesGuess.size(); i++)
        {
          if (std::find(fieldNames.begin(), fieldNames.end(), fieldNamesGuess[i].getString()) != fieldNames.end())
            {
              nom_champ_dans_fichier_med_ = fieldNamesGuess[i];
              ok = true;
              break;
            }
        }
      if (!ok)
        {
          Cerr << "Unable to find into file " << fileName << " a field named like :" << finl;
          Cerr << fieldNamesGuess << finl;
          Cerr << "This file contains the field(s) named:" << finl;
          for (unsigned i=0; i<fieldNames.size(); i++)
            Cerr << fieldNames[i] << finl;
          Process::exit();
        }
      else
        Cerr << "Ok, we find into file " << fileName << " a field named " << nom_champ_dans_fichier_med_ << finl;
      std::string fieldName = nom_champ_dans_fichier_med_.getString();
      lire_donnees_champ(fileName,meshName,fieldName,temps_sauv,size,nbcomp,type_champ);
    }
  else
#endif
    {
// MEDFile
      type_geo = type_geo_trio_to_type_med(type_elem);
      int verifie_type = 0;
      if (localisation != Nom())
        {
          verifie_type = 1;
          if (localisation == "som")
            type_ent = MED_NODE;
          else if (localisation == "elem")
            type_ent = MED_CELL;
          else
            {
              Cerr << localisation << " localisation not understood " << finl;
              exit();
            }
        }
      nom_champ_dans_fichier_med_ = medinfo1champ(nom_fic, nom_champ_dans_fichier_med_, numero_ch, nbcomp, nb_dt,
                                                  type_ent, type_geo, size, un_dom.le_nom(), verifie_type, temps_sauv);
      if (type_ent == MED_NODE)
        {
          if ((type_geo == MED_QUAD4) || (type_geo == MED_HEXA8))
            type_champ = "Champ_Fonc_Q1_MED";
          else
            type_champ = "Champ_Fonc_P1_MED";
        }
      else if (type_ent == MED_CELL)
        {
          type_champ = "Champ_Fonc_P0_MED";
        }
    }
// Definition:
  vrai_champ_.typer(type_champ);
  fixer_nb_comp(nbcomp);
  le_champ().fixer_nb_comp(nbcomp);
  zonebidon_inst.associer_zone(un_dom.zone(0));
  le_champ().associer_zone_dis_base(zonebidon_inst);
  le_champ().fixer_nb_valeurs_nodales(type_champ == "Champ_Fonc_P0_MED" ? un_dom.zone(0).nb_elem() : un_dom.nb_som());
// pour forcer la lecture lors du mettre a jour
  changer_temps(-1e3);
// corriger_unite_nom_compo();
  le_champ().nommer(le_nom());
// le_champ().corriger_unite_nom_compo();
  return size;
#else
  med_non_installe();
  return 0;
#endif
}
References Vect_Nom::add(), Zone_dis_base::associer_zone(), Champ_base::associer_zone_dis_base(), Cerr, Champ_base::changer_temps(), Noms::contient_(), Process::exit(), finl, Field_base::fixer_nb_comp(), Champ_Fonc_base::fixer_nb_valeurs_nodales(), Nom::getString(), le_champ(), Field_base::le_nom(), Domaine::le_nom(), O_U_Ptr::le_nom(), MED_HEXA8, med_non_installe(), MED_QUAD4, mon_dom, nb_dt, Zone::nb_elem(), Domaine::nb_som(), nom_champ_dans_fichier_med_, nom_fichier_med_, Field_base::nommer(), numero_ch, Objet_U::que_suis_je(), vect_impl::size(), Zone::type_elem(), type_elem(), Deriv_::typer(), use_medcoupling_, vrai_champ_, Domaine::zone(), and zonebidon_inst.
Referenced by Pb_MED::creer_champ(), and readOn().
domaine()
const Domaine & Champ_Fonc_MED::domaine () const inline
Definition at line 67 of file Champ_Fonc_MED.h.
  {
    return mon_dom;
  }
References mon_dom.
duplique()
int Champ_Fonc_MED::duplique () const override virtual
Implements Objet_U.
Reimplemented in Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, and Champ_Fonc_MED_Tabule.
Definition at line 38 of file Champ_Fonc_MED.cpp.
get_info()
const Type_info * Champ_Fonc_MED::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, and Champ_Fonc_MED_Tabule.
Definition at line 38 of file Champ_Fonc_MED.cpp.
get_saved_times()
const ArrOfDouble & Champ_Fonc_MED::get_saved_times (void) const
Definition at line 711 of file Champ_Fonc_MED.cpp.
{
  return temps_sauv_;
}
References temps_sauv_.
info()
const Type_info * Champ_Fonc_MED::info () static
Definition at line 38 of file Champ_Fonc_MED.cpp.
le_champ() [1/2]
Champ_Fonc_base & Champ_Fonc_MED::le_champ (void) inline virtual
Definition at line 127 of file Champ_Fonc_MED.h.
{
  return vrai_champ_.valeur();
}
References Deriv_Champ_Fonc_base::valeur(), and vrai_champ_.
le_champ() [2/2]
const Champ_Fonc_base & Champ_Fonc_MED::le_champ (void) const inline virtual
Definition at line 122 of file Champ_Fonc_MED.h.
{
  return vrai_champ_.valeur();
}
References Deriv_Champ_Fonc_base::valeur(), and vrai_champ_.
Referenced by creer(), Pb_MED::creer_champ(), Pb_MED::get_champ(), lire(), Champ_Fonc_MED_Table_Temps::lire(), readOn(), remplir_coord_noeuds(), remplir_coord_noeuds_et_polys(), valeur_a(), valeur_a_elem(), valeur_aux_elems(), valeur_aux_elems_compo(), valeur_aux_sommets(), valeur_aux_sommets_compo(), and valeurs().
lire()
void Champ_Fonc_MED::lire (double tps, int given_iteration = -1) virtual
< Cas d'une zone vide
Reimplemented in Champ_Fonc_MED_Table_Temps.
Definition at line 306 of file Champ_Fonc_MED.cpp.
{
  if (zonebidon_inst.nb_elem()==0) //!< Cas d'une zone vide
    {
// Mise a jour:
      Champ_Fonc_base::mettre_a_jour(t);
      le_champ().Champ_Fonc_base::mettre_a_jour(t);
      return;
    }
#ifdef MED_
#ifdef MEDCOUPLING_
  if (use_medcoupling_)
    {
// Read a field
      std::string  meshName = mon_dom.le_nom().getString();
      std::string fieldName = nom_champ_dans_fichier_med_.getString();
      std::string  fileName = nom_fichier_med_.getString();
// Etude des conditions pour chercher ou nom un champ dans le fichier MED:
      bool search_field = true;
      nb_dt = temps_sauv_.size_array();
      if (nb_dt>0)
        {
// nb_dt nombre de pas de temps dans le fichier MED
// ndt taille du tableau temps_sauv contenant les pas de temps du champ dans le fichier MED
// tmax dernier temps du tableau temps_sauv ?
// dt ?
// t temps courant pour lequel on veut remplir le champ
// last_time_only_ specifie dans le jeu de donnees ou non
          double tmax = temps_sauv_[nb_dt - 1];
          double dt = temps_sauv_[nb_dt - 1];
          if (((nb_dt == 1) && (!est_egal(dt, t))) || ((last_time_only_ == 1) && (!est_egal(tmax, t))))
            {
              Cout << "We assume that the field " << fieldName << " is stationary." << finl;
              search_field = false;
            }
        }
      if (search_field)
        {
          if (temps_sauv_.size_array()==0)
            temps_sauv_ = lire_temps_champ(fileName, fieldName);
          unsigned int nn = temps_sauv_.size_array();
          if (given_it == -1)
            {
              for (given_it = 0; given_it < (int) nn; given_it++)
                if (est_egal(temps_sauv_[given_it], t)) break;
              if (given_it == (int)nn)
                {
                  Cerr << "Error. Time " << t << " not found in the times list of the " << fileName << " file" << finl;
                  for (unsigned int n=0; n<nn; n++)
                    Cerr << temps_sauv_[n] << finl;
                  Process::exit();
                }
            }
          int iteration = time_steps_[given_it].first;
          int order = time_steps_[given_it].second;
// Only one MCAuto below to avoid double deletion:
          MCAuto<MEDCouplingField> ffield = lire_champ(fileName, meshName, fieldName, iteration, order);
          Cerr << " at time " << t << " ... " << finl;
          MEDCouplingFieldDouble * field = dynamic_cast<MEDCouplingFieldDouble *>((MEDCouplingField *)ffield);
          if (field == 0)
            {
              Cerr << "ERROR reading MED field! Not a MEDCouplingFieldDouble!!" << finl;
              Process::exit(-1);
            }
          const double *field_values = field->getArray()->begin();
          assert(field->getNumberOfTuplesExpected() == le_champ().valeurs().dimension(0));
          assert((int) field->getNumberOfComponents() ==
                 (le_champ().valeurs().nb_dim() == 1 ? 1 : le_champ().valeurs().dimension(1)));
          memcpy(le_champ().valeurs().addr(), field_values,
                 le_champ().valeurs().size_array() * sizeof(double));
        }
    }
  else
#endif
    {
      med_idt fid = MEDfileOpen(nom_fichier_med_, MED_ACC_RDONLY);
      if (fid < 0)
        {
          Cerr << "Problem while opening the file " << nom_fichier_med_ << finl;
          exit();
        }
      Char_ptr pflname;
      pflname.allocate(MED_NAME_SIZE);
      if (given_it != -1)
        {
          Cerr<<"Searching for the "<<given_it+1<< " iteration of the field "<<le_nom()<<finl;
        }
      Char_ptr dt_unit;
      dt_unit.allocate(MED_SNAME_SIZE);
// on cherche le numero du pas de temps
      med_int numdt, numo;
      double dt = -2;
      int ret, size = 0;
      Char_ptr maa_ass;
      maa_ass.allocate(MED_NAME_SIZE);
// Cerr<<"nb_dt"<<nb_dt<<finl;
      Nom nom_dom(mon_dom.le_nom());
      int i2 = 0;
      Nom& le_nom_du_champ = nom_champ_dans_fichier_med_;
      med_field_type typcha;
// Nom meshname; dimensionne_nom_taille(meshname,MED_NAME_SIZE);
      Char_ptr dtunit;
      dtunit.allocate(MED_SNAME_SIZE);
      med_bool localmesh;
      med_int nbofcstp;
      int ncomp = MEDfieldnComponentByName(fid, le_nom_du_champ);
      Char_ptr comp;
      comp.allocate(MED_SNAME_SIZE * ncomp);
      Char_ptr unit;
      unit.allocate(MED_SNAME_SIZE * ncomp);
      ret = MEDfieldInfoByName(fid, le_nom_du_champ, maa_ass, &localmesh, &typcha, comp, unit, dtunit, &nbofcstp);
      int nb_dt_tot = nbofcstp;
      double tmax = -1;
      for (int j = 0; j < nb_dt_tot; j++)
        {
          med_int meshnumdt, meshnumit;
          MEDfieldComputingStepMeshInfo(fid, le_nom_du_champ, j + 1, &numdt, &numo, &dt, &meshnumdt, &meshnumit);
          tmax = dt;
        }
      for (int j = 0; j < nb_dt_tot; j++)
        {
          if (i2 >= nb_dt) exit();
          med_int meshnumdt, meshnumit;
          MEDfieldComputingStepMeshInfo(fid, le_nom_du_champ, j + 1, &numdt, &numo, &dt, &meshnumdt, &meshnumit);
          Nom Nmaa_ass(maa_ass);
          if (est_egal(dt, t))
            {
              size = MEDfieldnValue(fid, le_nom_du_champ, numdt, numo, type_ent, type_geo);
              if ((size != 0) && (nom_dom == Nmaa_ass))
                break;
            }
          if (Nmaa_ass == nom_dom)
            {
              if (given_it == i2)
                {
                  t = dt;
                  given_it = j;
                  break;
                }
              i2++;
            }
        }
// dt=t;
// numdt=1;
// numo=MED_NONOR;
// Cerr << "Provisoire temps=" << temps_sauv_ << finl;
// Cerr << "Provisoire temps= " << nb_dt << " " << dt << " " << t << " " << tmax << " " << last_time_only_ << finl;
      if (((nb_dt == 1) && (!est_egal(dt, t))) || ((last_time_only_ == 1) && (!est_egal(tmax, t))))
        {
          Cout << "We assume that the field " << le_nom_du_champ << " is stationary." << finl;
        }
      else
        {
          if (!est_egal(dt, t))
            {
              Cerr.precision(12);
              Cerr << "Error: we did not find the time " << t << finl;
              Cerr << "Available times for " << le_nom_du_champ << " domain " << nom_dom << " are:" << finl;
              for (int j = 0; j < nb_dt; j++)
                {
                  med_int meshnumdt, meshnumit;
                  MEDfieldComputingStepMeshInfo(fid, le_nom_du_champ, j + 1, &numdt, &numo, &dt, &meshnumdt, &meshnumit);
                  Cerr << dt << finl;
                }
              exit();
            }
          Cerr << "Reading the time step " << (int) numdt << " of field " << le_nom_du_champ << " time " << t
               << " type ent " << (int) type_ent << finl;
          if (filter.size_array() > 0) //lecture sur domaine parallele -> avec un filtre
            {
              Cerr << "Read with filter..." << finl;
              med_filter flt = MED_FILTER_INIT;
              if(MEDfilterEntityCr(fid, size, 1, le_champ().valeurs().nb_dim() > 1 ? le_champ().valeurs().dimension(1) : 1, MED_ALL_CONSTITUENT,
                                   MED_FULL_INTERLACE, MED_COMPACT_STMODE, MED_ALLENTITIES_PROFILE, filter.size_array(), filter.addr(), &flt) < 0)
                Cerr << "Champ_Fonc_MED on parallel domain : error at filter creation!" << finl, Process::exit();
              ret = MEDfieldValueAdvancedRd(fid,le_nom_du_champ,numdt,numo,type_ent,type_geo,&flt,(unsigned char*)le_champ().valeurs().addr());
            }
          else if (le_champ().valeurs().dimension(0) > 0)//lecture complete
            ret = MEDfieldValueRd(fid, le_nom_du_champ, numdt, numo, type_ent, type_geo, MED_FULL_INTERLACE,
                                  MED_ALL_CONSTITUENT, (unsigned char *) le_champ().valeurs().addr());
          if (ret < 0)
            {
              Cerr << "Problem while reading field " << le_nom_du_champ << " name of domain " << mon_dom.le_nom() << finl;
              exit();
            }
          MEDfileClose(fid);
        }
    }
// Mise a jour:
  Champ_Fonc_base::mettre_a_jour(t);
  le_champ().Champ_Fonc_base::mettre_a_jour(t);
#else
  med_non_installe();
#endif
}
References TRUSTArray< _TYPE_ >::addr(), Char_ptr::allocate(), Cerr, Cout, Objet_U::dimension, est_egal(), Process::exit(), filter, finl, Nom::getString(), last_time_only_, le_champ(), Field_base::le_nom(), O_U_Ptr::le_nom(), MED_FULL_INTERLACE, med_non_installe(), Champ_Fonc_base::mettre_a_jour(), mon_dom, nb_dt, Zone_dis_base::nb_elem(), nom_champ_dans_fichier_med_, nom_fichier_med_, TRUSTArray< _TYPE_ >::size_array(), temps_sauv_, use_medcoupling_, valeurs(), and zonebidon_inst.
Referenced by Champ_Fonc_MED_Tabule::mettre_a_jour(), and mettre_a_jour().
mettre_a_jour()
void Champ_Fonc_MED::mettre_a_jour (double temps) override virtual
Mise a jour en temps du champ.
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_MED_Tabule.
Definition at line 294 of file Champ_Fonc_MED.cpp.
{
  if (t<0)
    {
// Si t negatif convention (non indique dans la doc Trust) pour specifier un numero de pas de temps:
      int given_it = -(int) t - 1;
      lire(-1, given_it);
    }
  else
    lire(t);
}
References lire().
Referenced by Pb_MED::get_champ(), and readOn().
nb_pas_temps()
int Champ_Fonc_MED::nb_pas_temps () inline
Definition at line 72 of file Champ_Fonc_MED.h.
  {
    return nb_dt;
  }
References nb_dt.
printOn()
Sortie & Champ_Fonc_MED::printOn (Sortie & s) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, and Champ_Fonc_MED_Tabule.
Definition at line 51 of file Champ_Fonc_MED.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Champ_Fonc_MEDfile::printOn(), Champ_Fonc_MED_Table_Temps::printOn(), and Champ_Fonc_MED_Tabule::printOn().
readOn()
Entree & Champ_Fonc_MED::readOn (Entree & s) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
Entree&
Signification:
Contraintes:
< Cas ou le maillage .med suit la numerotation du maillage decoupe
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, and Champ_Fonc_MED_Tabule.
Definition at line 70 of file Champ_Fonc_MED.cpp.
{
  Nom chaine_lue,nom_dom,nom_champ, nom_decoup;
  Motcle localisation;
  double un_temps;
  s>>chaine_lue;
  int use_existing_domain=0, field_size, nom_decoup_lu = 0;
  last_time_only_=0;
  if (chaine_lue=="use_existing_domain")
    {
      use_existing_domain=1;
      s>>chaine_lue;
    }
  if (chaine_lue=="last_time")
    {
      last_time_only_=1;
      s>>chaine_lue;
    }
  if (chaine_lue=="decoup")
    {
      s>>nom_decoup;
      s>>chaine_lue;
      if (use_medcoupling_)
        {
          Cerr << "Error: Decoup option is only available for the moment with Champ_Fonc_MEDFile keyword only." << finl;
          Process::exit();
        }
      if (!use_existing_domain)
        {
          Cerr << "Error: you need to use use_existing_domain option with Decoup option." << finl;
          Process::exit();
        }
      nom_decoup_lu = 1;
    }
  nom_fichier_med_ = chaine_lue;
  lire_nom_med(nom_dom,s);
  if (!nom_decoup_lu) nom_decoup = Nom("decoup/") + nom_dom + ".txt"; //valeur par defaut de nom_decoup
  lire_nom_med(nom_champ,s);
  s>>localisation;
  s>>un_temps;
  traite_nom_fichier_med(nom_fichier_med_);
// #ifdef MED_
// test_version(nom_fichier_med_);
// #endif
// MEDCoupling:
  if (use_medcoupling_)
    Cerr << "Using MEDCoupling API. To switch to the MEDFile API, use Champ_Fonc_MEDfile keyword." << finl;
// La lecture de fichiers multiples .med fonctionne: voir cas test Champ_fonc_MED_Parallele
// Un test est fait plus loin pour bien verifier que les partitionnement se recouvrent pour cela
  int multiple_med = 0;
  Nom tmp(nom_fichier_med_);
  tmp.prefix("0001.med");
  if (tmp!=nom_fichier_med_ && Process::nproc()>1)
    {
      multiple_med = 1;
      /*
      // Ajout d'un test bloquant pour empecher la lecture de fichiers 000n.med
      Cerr << "Error, Champ_Fonc_MED can't read, for the moment, partitioned MED files." << finl;
      Cerr << "Try to build a single MED file by:" << finl;
      Cerr << "A) Using LATA format for the previous calculation." << finl;
      Cerr << "B) Convert the LATA files into a single MED file with Lata_to_MED keyword." << finl;
      Cerr << "C) Use this single MED file with Champ_Fonc_MED keyword." << finl;
      exit(); */
    }
  multiple_med = mp_max(multiple_med);
  nommer(nom_champ);
  bool domain_exist=( interprete().objet_existant(nom_dom) && sub_type(Domaine, interprete().objet(nom_dom)) );
  if (use_existing_domain)
    {
      if (!domain_exist)
        {
          Cerr << "The domain " << nom_dom << " does not exist !!!! In Champ_Fonc_MED " << nom_fichier_med_ << " " << nom_dom
               << " " << nom_champ << " " << localisation << " " << un_temps << finl;
          exit();
        }
      else
        {
// use_existing_domain utilisable en parallele uniquement si le process 0 gere tout le domaine ou si decoup specifie:
          const Domaine& le_domaine=ref_cast(Domaine, interprete().objet(nom_dom));
          if (Process::nproc()>1 && mp_max(le_domaine.nb_som()>0) != 0 && use_medcoupling_==1)
            {
              Cerr << "Warning, you can't use use_existing_domain on a partitionned domain like " << nom_dom << finl;
              Cerr << "It is not parallelized yet... So we use MED mesh, which is not optimal." << finl;
              Cerr << "Try suppress use_existing_domain option." << finl;
// Process::exit();
              use_existing_domain = 0;
            }
        }
    }
  if (domain_exist && use_existing_domain)
    {
      Cerr<<nom_dom<<" was not read into the med file because it already exists." <<finl;
      const Domaine& le_domaine=ref_cast(Domaine, interprete().objet(nom_dom));
#ifndef NDEBUG
// on va verifier que l'on a le meme domaine en mode debug car lent
// Ce test ne peut etre fait qu'en sequentiel car en parallele, dom=domaine_complet, un_dom=domaine_local
      if (nproc()==1)
        {
          LireMED liremed;
          dom_med_.nommer(nom_dom);
// ne pas initialiser le nom du domaine va conduire a ne pas creer les fichiers sous zones
          Nom nom_dom_trio_non_nomme;
          liremed.lire_geom(nom_fichier_med_,dom_med_,nom_dom,nom_dom_trio_non_nomme);
          DoubleTab diff_som(dom_med_.les_sommets());
          IntTab diff_elem(dom_med_.zone(0).les_elems());
          diff_som.set_md_vector(le_domaine.les_sommets().get_md_vector());
          diff_elem.set_md_vector(le_domaine.zone(0).les_elems().get_md_vector());
          diff_som-=le_domaine.les_sommets();
          diff_elem-=le_domaine.zone(0).les_elems();
          /*
                    diff_som.set_md_vector(un_dom.les_sommets().get_md_vector());
                    diff_som-=un_dom.les_sommets();
                    diff_som.set_md_vector(MD_Vector());
                    diff_elem.set_md_vector(un_dom.zone(0).les_elems().get_md_vector());
                    diff_elem-=un_dom.zone(0).les_elems();
                    diff_elem.set_md_vector(MD_Vector());
          */
          double err_som0 = max_abs_array(diff_som);
          int err_elem0 = max_abs_array(diff_elem);
// Le domaine un_dom a peut etre ete reordonne, on refait le test en reordonnant le domaine dom .....
          dom_med_.reordonner();
          dom_med_.les_sommets().set_md_vector(le_domaine.les_sommets().get_md_vector());
          dom_med_.les_sommets()-=le_domaine.les_sommets();
          dom_med_.les_sommets().set_md_vector(MD_Vector());
          dom_med_.zone(0).les_elems().set_md_vector(le_domaine.zone(0).les_elems().get_md_vector());
          dom_med_.zone(0).les_elems()-=le_domaine.zone(0).les_elems();
          dom_med_.zone(0).les_elems().set_md_vector(MD_Vector());
          double err_som = max_abs_array(dom_med_.les_sommets());
          int err_elem = max_abs_array(dom_med_.zone(0).les_elems());
          if ((err_som>1e-5 || err_elem>0) && (err_som0>1e-5 || err_elem0>0))
            {
              Cerr<<"Error the domain in the file "<<nom_fichier_med_<<" and domain "<<nom_dom<<" are not the same (coords,conn)."<<finl;
              exit();
            }
// Reset:
          dom_med_=Domaine();
        }
#endif
      field_size = creer(nom_fichier_med_,le_domaine,localisation,temps_sauv_);
    }
  else
    {
      if (domain_exist && !use_existing_domain)
        {
          Cerr<<"INFO: You can use Champ_fonc_med use_existing_domain "<< nom_fichier_med_<<" "<<nom_dom<<" "<<nom_champ<<" "<<localisation<<" "<<un_temps<<" to optimize."<<finl;
        }
      LireMED liremed;
      dom_med_.nommer(nom_dom);
// ne pas initialiser le nom du domaine va conduire a ne pas creer les fichiers sous zones
      Nom nom_dom_trio_non_nomme;
// Remplit dom:
      liremed.lire_geom(nom_fichier_med_,dom_med_,nom_dom,nom_dom_trio_non_nomme);
      if (multiple_med)
        {
// On verifie que l'on a bien des recouvrements identiques (verification imparfaite sur les BoundingBox)
          DoubleTab BB1 = dom_med_.getBoundingBox();
          const Domaine& dom_calcul = ref_cast(Domaine, interprete().objet(nom_dom));
          DoubleTab BB2 = dom_calcul.getBoundingBox();
          for (int i=0; i<dimension; i++)
            for (int j=0; j<2; j++)
              if (est_different(BB1(i,j), BB2(i,j)))
                {
                  Cerr << "Error, Champ_Fonc_MED can't read the partitionned MED files." << finl;
                  Cerr << "Cause if seems the MED partition is different than the " << dom_calcul.le_nom() << " domain partition." << finl;
                  Process::exit();
                }
          Cerr << "Ok MED partition matches the domain partition so reading multiple MED files..." << finl;
        }
// MODIF ELI LAUCOIN (06/03/2012) :
// j'ajoute l'attribut temps_sauv_
      field_size = creer(nom_fichier_med_,dom_med_,localisation,temps_sauv_);
    }
  if (last_time_only_)
    {
      un_temps=temps_sauv_[temps_sauv_.size_array()-1];
      Cout << "The resumption time is "<<un_temps<<finl;
    }
// FIN MODIF ELI LAUCOIN (06/03/2012)
  /* si on est en parallele : creation du filtre */
  if (Process::nproc() > 1 && field_size != le_champ().valeurs().dimension(0))
    {
      ArrOfInt dec;
      filter.set_smart_resize(1);
      EFichier fdec;
      fdec.ouvrir(nom_decoup);
// Cas ou le maillage du fichier .med suit la numerotation du maillage initial (necessite le fichier du decoupage pour retrouver la numerotation)
      if (fdec.good())
        {
          fdec >> dec;
          for (int i = 0; i < dec.size_array(); i++)
            if (dec[i] == Process::me()) filter.append_array(i + 1);//les indices commencent a 1
          if (field_size != dec.size_array())
            Cerr << "Champ_Fonc_MED on parallel domain : inconsistency between 'decoup' file and field!" << finl, Process::exit();
        }
      else //!< Cas ou le maillage .med suit la numerotation du maillage decoupe
        {
          int nb_item = le_champ().valeurs().dimension(0);
          int first_item = mppartial_sum(nb_item);
          for (int i=0; i<nb_item; i++)
            filter.append_array(first_item + i + 1);//les indices commencent a 1
        }
      filter.set_smart_resize(0), filter.resize(filter.size_array());
      Cerr << "Creating a filter to access efficiently values in " << nom_fichier_med_ << finl;
      if (filter.size_array() != le_champ().valeurs().dimension(0))
        Cerr << "Champ_Fonc_MED on parallel domain : inconsistency between filter and domain!" << finl, Process::exit();
    }
  else if (field_size != le_champ().valeurs().dimension(0))
    Cerr << "Champ_Fonc_MED on existing domain : inconsistency between domain file and field!" << finl, Process::exit();
  le_champ().nommer(nom_champ);
  le_champ().corriger_unite_nom_compo();
  mettre_a_jour(un_temps);
  return s ;
}
References TRUSTArray< _TYPE_ >::append_array(), Cerr, Champ_base::corriger_unite_nom_compo(), Cout, creer(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, dom_med_, est_different(), Process::exit(), filter, finl, TRUSTVect< _TYPE_ >::get_md_vector(), Domaine::getBoundingBox(), Entree_Fichier_base::good(), Objet_U::interprete(), last_time_only_, le_champ(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), LireMED::lire_geom(), lire_nom_med(), max_abs_array(), Process::me(), mettre_a_jour(), Process::mp_max(), mppartial_sum(), Domaine::nb_som(), nom_fichier_med_, Field_base::nommer(), Domaine::nommer(), Process::nproc(), Interprete::objet_existant(), Entree_Fichier_base::ouvrir(), Nom::prefix(), ref_cast, Domaine::reordonner(), TRUSTArray< _TYPE_ >::resize(), TRUSTTab< _TYPE_ >::set_md_vector(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), sub_type, temps_sauv_, traite_nom_fichier_med(), use_medcoupling_, Champ_Don_base::valeurs(), valeurs(), and Domaine::zone().
Referenced by Champ_Fonc_MEDfile::readOn(), Champ_Fonc_MED_Table_Temps::readOn(), and Champ_Fonc_MED_Tabule::readOn().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_MED::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
DoubleTab&
Signification: renvoie toujours le parametre coord
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 187 of file Champ_Fonc_MED.h.
{
  return le_champ().remplir_coord_noeuds(coord);
}
References le_champ(), and Champ_Fonc_base::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_MED::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns
int
Signification: renvoie toujours 0
Contraintes:
Reimplemented from Champ_Fonc_base.
Definition at line 192 of file Champ_Fonc_MED.h.
{
  return le_champ().remplir_coord_noeuds_et_polys(coord, elems);
}
References le_champ(), and Champ_Fonc_base::remplir_coord_noeuds_et_polys().
self_cast() [1/2]
const Champ_Fonc_MED & Champ_Fonc_MED::self_cast (const Objet_U & r) static
Definition at line 38 of file Champ_Fonc_MED.cpp.
self_cast() [2/2]
Champ_Fonc_MED & Champ_Fonc_MED::self_cast (Objet_U & r) static
Definition at line 38 of file Champ_Fonc_MED.cpp.
taille_memoire()
unsigned Champ_Fonc_MED::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Champ_Fonc_MEDfile, Champ_Fonc_MED_Table_Temps, and Champ_Fonc_MED_Tabule.
Definition at line 38 of file Champ_Fonc_MED.cpp.
valeur_a()
DoubleVect & Champ_Fonc_MED::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const inline override virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle
valeur_aux(const DoubleTab &, DoubleTab &)
Parametre: DoubleVect&
Signification: les coordonnees du point ou evaluer le champ
Parametre: DoubleVect& valeurs
Signification: En entree: doit avoir la bonne taille (nb_comp),
en sortie contient les composantes du champ.
Returns
reference a "valeurs"
Reimplemented from Champ_base.
Definition at line 144 of file Champ_Fonc_MED.h.
{
  const Zone& zone=zonebidon_inst.zone();
  IntVect le_poly(1);
  zone.chercher_elements(position, le_poly);
  return le_champ().valeur_a_elem(position,tab_valeurs,le_poly(0));
}
References Zone::chercher_elements(), le_champ(), Champ_base::valeur_a_elem(), Zone_dis_base::zone(), and zonebidon_inst.
valeur_a_elem()
DoubleVect & Champ_Fonc_MED::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie la valeur du champ au point specifie
par ses coordonnees, en indiquant que ce point est
situe dans un element specifie.
Returns
DoubleVect&
Signification: la valeur du champ au point specifie
Contraintes:
Reimplemented from Champ_base.
Definition at line 154 of file Champ_Fonc_MED.h.
{
// Le codage de cette methode passe par valeur_a() et ignore l'entier le_poly
// car si on utilise le_champ().valeur_a_elem(position,tab_valeurs,le_poly), on
// a des ecarts sequentiel-parallele pour les champs P0 (et probablement aussi pour
// les autres champs).
// Je m'explique cela par le fait qu'en parallele, le_poly designe un numero d'element
// dans la partition associee a un processeur, alors que le champ designe par le pointeur vrai_champ_
// est defini sur la totalite du domaine.
// Pour cette raison, j'utilise valeur_a(), qui localise la position dans la totalite du domaine,
// et qui retourne la valeur de vrai_champ_ dans cet element.
  return le_champ().valeur_a(position,tab_valeurs);
}
References le_champ(), and Champ_base::valeur_a().
valeur_aux_elems()
DoubleTab & Champ_Fonc_MED::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleTab&
Signification: le tableau des valeurs du champ aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 140 of file Champ_Fonc_MED.h.
{
  return le_champ().valeur_aux_elems(positions, les_polys, tab_valeurs);
}
References le_champ(), and Champ_base::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_MED::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur !
doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Renvoie les valeurs d'une composante du champ aux points specifies
par leurs coordonnees, en indiquant que les points de
calculs sont situes dans les elements indiques.
Returns
DoubleVect&
Signification: le tableau des valeurs de la composante du champ
aux points specifies
Contraintes:
Reimplemented from Champ_base.
Definition at line 168 of file Champ_Fonc_MED.h.
{
  return le_champ().valeur_aux_elems_compo(positions, les_polys, tab_valeurs, ncomp);
}
References le_champ(), and Champ_base::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_MED::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
Definition at line 176 of file Champ_Fonc_MED.h.
{
  return le_champ().valeur_aux_sommets(un_dom, sommets);
}
References le_champ(), and Champ_base::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_MED::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
Definition at line 181 of file Champ_Fonc_MED.h.
{
  return le_champ().valeur_aux_sommets_compo(un_dom, sommets, compo);
}
References le_champ(), and Champ_base::valeur_aux_sommets_compo().
valeurs() [1/2]
const DoubleTab & Champ_Fonc_MED::valeurs () const inline override virtual
Reimplemented from Champ_Don_base.
Definition at line 135 of file Champ_Fonc_MED.h.
{
  return le_champ().valeurs();
}
References le_champ(), and Champ_Don_base::valeurs().
valeurs() [2/2]
DoubleTab & Champ_Fonc_MED::valeurs () inline override virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
DoubleTab&
Signification: le tableau des valeurs du champs
Reimplemented from Champ_Don_base.
Definition at line 131 of file Champ_Fonc_MED.h.
{
  return le_champ().valeurs();
}
References le_champ(), and Champ_Don_base::valeurs().
Referenced by Integrer_champ_med::interpreter(), lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Champ_Fonc_MED_Tabule::mettre_a_jour(), and readOn().
zone_dis_base()
const Zone_dis_base & Champ_Fonc_MED::zone_dis_base () const override virtual
Reimplemented from Champ_base.
Definition at line 706 of file Champ_Fonc_MED.cpp.
{
  return zonebidon_inst;
}
References zonebidon_inst.
Referenced by Integrer_champ_med::interpreter().
Member Data Documentation
dom_med_
Domaine Champ_Fonc_MED::dom_med_ protected
Definition at line 96 of file Champ_Fonc_MED.h.
Referenced by readOn().
filter
ArrOfInt Champ_Fonc_MED::filter protected
Definition at line 112 of file Champ_Fonc_MED.h.
Referenced by lire(), and readOn().
info_obj
const Type_info Champ_Fonc_MED::info_obj static
Definition at line 47 of file Champ_Fonc_MED.h.
last_time_only_
int Champ_Fonc_MED::last_time_only_ protected
Definition at line 114 of file Champ_Fonc_MED.h.
Referenced by Champ_Fonc_MED(), lire(), and readOn().
mon_dom
Ref_Domaine Champ_Fonc_MED::mon_dom protected
Definition at line 95 of file Champ_Fonc_MED.h.
Referenced by creer(), domaine(), lire(), and Champ_Fonc_MED_Table_Temps::lire_donnees_champ().
nb_dt
int Champ_Fonc_MED::nb_dt protected
Definition at line 99 of file Champ_Fonc_MED.h.
Referenced by creer(), lire(), and nb_pas_temps().
nom_champ_dans_fichier_med_
Nom Champ_Fonc_MED::nom_champ_dans_fichier_med_ protected
Definition at line 111 of file Champ_Fonc_MED.h.
Referenced by creer(), and lire().
nom_fichier_med_
Nom Champ_Fonc_MED::nom_fichier_med_ protected
Definition at line 100 of file Champ_Fonc_MED.h.
Referenced by creer(), lire(), and readOn().
numero_ch
int Champ_Fonc_MED::numero_ch protected
Definition at line 98 of file Champ_Fonc_MED.h.
Referenced by creer().
temps_sauv_
ArrOfDouble Champ_Fonc_MED::temps_sauv_ protected
Definition at line 113 of file Champ_Fonc_MED.h.
Referenced by get_saved_times(), lire(), Champ_Fonc_MED_Tabule::mettre_a_jour(), and readOn().
use_medcoupling_
bool Champ_Fonc_MED::use_medcoupling_ protected
Definition at line 115 of file Champ_Fonc_MED.h.
Referenced by Champ_Fonc_MED(), Champ_Fonc_MEDfile::Champ_Fonc_MEDfile(), creer(), lire(), and readOn().
vrai_champ_
Champ_Fonc Champ_Fonc_MED::vrai_champ_ protected
Definition at line 110 of file Champ_Fonc_MED.h.
Referenced by creer(), and le_champ().
zonebidon_inst
Zone_VF_inst Champ_Fonc_MED::zonebidon_inst protected
Definition at line 97 of file Champ_Fonc_MED.h.
Referenced by creer(), lire(), Champ_Fonc_MED_Table_Temps::lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), valeur_a(), and zone_dis_base().
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Champ_Fonc_MED.h
src/Kernel/MEDimpl/Champ_Fonc_MED.cpp