TRUST: Zone_Cl_EF Class Reference
Zone_Cl_EF Class Reference
#include <Zone_Cl_EF.h>
Public Member Functions
Zone_Cl_EF ()
~Zone_Cl_EF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_EF &)
etape de discretisation : dimensionnement des tableaux
void completer (const Zone_dis &) override
remplissage des tableaux
int initialiser (double temps) override
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
void imposer_cond_lim (Champ_Inc &, double) override
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
void imposer_symetrie (DoubleTab &, int tous_les_sommets_sym=0) const
Impose les conditions de symetrie
c.a.d annules les composantes du champ sur la ou les normales
si tous_les_sommets_sym =1 alors meme les sommets appartenant aussi a un dirichlet sont mis a zero.
void imposer_symetrie_partiellement (DoubleTab &, const Noms &) const
void imposer_symetrie_matrice_secmem (Matrice_Morse &la_matrice, DoubleTab &secmem) const
void modifie_gradient (ArrOfDouble &grad_mod, const ArrOfDouble &grad, int num_som) const
int nb_faces_sortie_libre () const
Zone_EF & zone_EF ()
const Zone_EF & zone_EF () const
int nb_bord_periodicite () const
const ArrOfInt & get_type_sommet () const
Public Member Functions inherited from Zone_Cl_dis_base
Zone_Cl_dis_base ()
~Zone_Cl_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Cond_lim & les_conditions_limites (int) const
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
int nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de toutes les conditions
aux limites.
virtual void mettre_a_jour_ss_pas_dt (double temps)
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
void completer ()
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
int contient_Cl (const Nom &)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Zone_dis & zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
const Zone_dis & zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Zone & zone ()
const Zone & zone () const
virtual int calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour les problemes couples thermiques.
virtual void imposer_cond_lim (Champ_Inc &, double)=0
int nb_faces_Cl () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
void Gpoint (double t1, double t2)
void set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
int avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
int reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void associer_inconnue (const Champ_Inc &)
virtual const Champ_Inc & inconnue () const
virtual Champ_Inc & inconnue ()
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_EF & self_cast (Objet_U &)
static const Zone_Cl_EF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Cl_dis_base
static const Type_info * info ()
static Zone_Cl_dis_base & self_cast (Objet_U &)
static const Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_Cl_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void remplir_type_elem_Cl (const Zone_EF &)
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Protected Member Functions inherited from Zone_Cl_dis_base
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
virtual void completer (const Zone_dis &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int modif_perio_fait_
ArrOfInt type_sommet_
-1 interne 0 Neumann 1 Symetrie >2 Dirichlet Un sommet est d'abord diri , puis Symetrie , puis Neumann , puis interne
Champ_Don normales_symetrie_
Champ_Don normales_symetrie_bis_
Champ_Don normales_symetrie_ter_
Protected Attributes inherited from Zone_Cl_dis_base
Nom nom_
Conds_lim les_conditions_limites_
Ref_Champ_Inc mon_inconnue
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 39 of file Zone_Cl_EF.h.
Constructor & Destructor Documentation
Zone_Cl_EF()
Zone_Cl_EF::Zone_Cl_EF ()
Definition at line 39 of file Zone_Cl_EF.cpp.
~Zone_Cl_EF()
Zone_Cl_EF::~Zone_Cl_EF ()
Definition at line 39 of file Zone_Cl_EF.cpp.
Member Function Documentation
associer()
void Zone_Cl_EF::associer (const Zone_EF & la_zone_EF)
etape de discretisation : dimensionnement des tableaux
Definition at line 89 of file Zone_Cl_EF.cpp.
{
// int nb_elem_Cl  = la_zone_EF.nb_elem_Cl();
}
Referenced by EF_discretisation::zone_Cl_dis().
completer()
void Zone_Cl_EF::completer (const Zone_dis & une_zone_dis) override virtual
remplissage des tableaux
Implements Zone_Cl_dis_base.
Definition at line 96 of file Zone_Cl_EF.cpp.
{
  modif_perio_fait_ =0;
  if (sub_type(Zone_EF,une_zone_dis.valeur()))
    {
      const Zone_EF& la_zone_EF = ref_cast(Zone_EF, une_zone_dis.valeur());
      remplir_type_elem_Cl(la_zone_EF);
    }
  else
    {
      Cerr << "Zone_Cl_EF::completer() prend comme argument une Zone_EF " << finl;
      exit();
    }
}
References Cerr, Process::exit(), finl, modif_perio_fait_, ref_cast, remplir_type_elem_Cl(), sub_type, and Deriv_Zone_dis_base::valeur().
cree_instance()
Objet_U * Zone_Cl_EF::cree_instance () static
Definition at line 39 of file Zone_Cl_EF.cpp.
duplique()
int Zone_Cl_EF::duplique () const override virtual
Implements Objet_U.
Definition at line 39 of file Zone_Cl_EF.cpp.
get_info()
const Type_info * Zone_Cl_EF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 39 of file Zone_Cl_EF.cpp.
get_type_sommet()
const ArrOfInt & Zone_Cl_EF::get_type_sommet () const inline
Definition at line 64 of file Zone_Cl_EF.h.
  {
    return type_sommet_ ;
  };
References type_sommet_.
Referenced by Assembleur_P_EF::assembler_mat().
imposer_cond_lim()
void Zone_Cl_EF::imposer_cond_lim (Champ_Inc & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
Implements Zone_Cl_dis_base.
Definition at line 638 of file Zone_Cl_EF.cpp.
{
  DoubleTab& ch_tab = ch->valeurs(temps);
  int nb_comp = ch->nb_comp();
  const Zone_EF& zoneEF =  zone_EF(); //ref_cast(Zone_EF,ch->equation().zone_dis().valeur());
  const IntTab& faces_sommets=zoneEF.face_sommets();
  int nb_som_face=faces_sommets.dimension(1);
  const DoubleTab& coords= zoneEF.zone().domaine().coord_sommets();
// dans un premier temps on annule le champ sur les dirichlets
// puis on ajoute 1/nb_cl*val_imp
  for (int n_bord=0; n_bord<nb_cond_lim(); n_bord++)
    {
      const Cond_lim_base& la_cl = les_conditions_limites(n_bord).valeur();
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num2 =  le_bord.nb_faces_tot();
      if (sub_type(Dirichlet,la_cl)||(sub_type(Dirichlet_homogene,la_cl)))
        {
// const Dirichlet& la_cl_diri = ref_cast(Dirichlet,la_cl);
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int s=0; s<nb_som_face; s++)
                {
                  int som=faces_sommets(face,s);
                  assert(type_sommet_[som]>=2);
                  if (nb_comp == 1)
                    ch_tab[som]=0;
                  else
                    for (int ncomp=0; ncomp<nb_comp; ncomp++)
                      ch_tab(som,ncomp)=0;
                }
            }
        }
    }
  for (int n_bord=0; n_bord<nb_cond_lim(); n_bord++)
    {
      const Cond_lim_base& la_cl = les_conditions_limites(n_bord).valeur();
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num2 =  le_bord.nb_faces_tot();
      if (sub_type(Dirichlet,la_cl))
        {
          const Dirichlet& la_cl_diri = ref_cast(Dirichlet,la_cl);
          if (sub_type(Champ_front_softanalytique,la_cl_diri.champ_front().valeur()))
            {
              Cerr<<" Il faut utiliser Champ_front_fonc_txyz et non "<<la_cl_diri.champ_front().valeur().que_suis_je()<<finl;
              exit();
            }
          int avec_valeur_aux_sommets=0;
          if (sub_type(Champ_front_var_instationnaire,la_cl_diri.champ_front().valeur()))
            {
              const Champ_front_var_instationnaire& ch_txyz=ref_cast(Champ_front_var_instationnaire,la_cl_diri.champ_front().valeur());
              avec_valeur_aux_sommets=ch_txyz.valeur_au_temps_et_au_point_disponible();
            }
// Pour les faces de Dirichlet on impose l'inconnue au sommet
          if (avec_valeur_aux_sommets)
            {
              const Champ_front_var_instationnaire& ch_txyz=ref_cast(Champ_front_var_instationnaire,la_cl_diri.champ_front().valeur());
              for (int ind_face=0; ind_face<num2; ind_face++)
                {
                  int face=le_bord.num_face(ind_face);
                  for (int s=0; s<nb_som_face; s++)
                    {
                      int som=faces_sommets(face,s);
                      assert(type_sommet_[som]>=4);
                      double coef=1./(type_sommet_[som]/2-1);
// Cerr<<"iciPB "<<coef<<finl;
                      double x,y,z=0;
                      x=coords(som,0);
                      y=coords(som,1);
                      if (dimension==3)
                        z=coords(som,2);
                      if (nb_comp == 1)
                        ch_tab[som]+=coef*ch_txyz.valeur_au_temps_et_au_point(temps,som,x,y,z,0);
                      else
                        for (int ncomp=0; ncomp<nb_comp; ncomp++)
                          ch_tab(som,ncomp)+=coef*ch_txyz.valeur_au_temps_et_au_point(temps,som,x,y,z,ncomp);
                    }
                }
            }
          else
            for (int ind_face=0; ind_face<num2; ind_face++)
              {
                int face=le_bord.num_face(ind_face);
                for (int s=0; s<nb_som_face; s++)
                  {
                    int som=faces_sommets(face,s);
                    assert(type_sommet_[som]>=4);
                    double coef=1./(type_sommet_[som]/2-1);
// Cerr<<"iciPB "<<coef<<finl;
                    if (nb_comp == 1)
                      ch_tab[som]+=coef*la_cl_diri.val_imp_au_temps(temps,ind_face);
                    else
                      for (int ncomp=0; ncomp<nb_comp; ncomp++)
                        ch_tab(som,ncomp)+=coef*la_cl_diri.val_imp_au_temps(temps,ind_face,ncomp);
                  }
              }
        }
      /*
      else if (sub_type(Dirichlet_homogene,la_cl))
      {
        // Pour les faces de Dirichlet on impose l'inconnue au sommet
        for (int ind_face=0; ind_face<num2; ind_face++)
      {
      int face=le_bord.num_face(ind_face);
      for (int s=0;s<nb_som_face;s++)
        {
          int som=faces_sommets(face,s);
          assert(type_sommet_(som)>=2);
          if (nb_comp == 1)
      ch_tab[som] = 0;
          else
      for (int ncomp=0; ncomp<nb_comp; ncomp++)
        ch_tab(som,ncomp) =0;
        }
      }
      }
      */
// provsoire a fair equ'une fois
      else if ( (sub_type(Symetrie,la_cl) ) &&
                (ch->nature_du_champ()==vectoriel) )
        {
          imposer_symetrie(ch_tab);
        }
    }
}
References Cerr, Cond_lim_base::champ_front(), Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone::domaine(), Process::exit(), Zone_VF::face_sommets(), finl, Cond_lim_base::frontiere_dis(), imposer_symetrie(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Objet_U::que_suis_je(), ref_cast, sub_type, type_sommet_, Dirichlet::val_imp_au_temps(), Deriv_Champ_front_base::valeur(), Champ_front_var_instationnaire::valeur_au_temps_et_au_point(), Champ_front_var_instationnaire::valeur_au_temps_et_au_point_disponible(), Champ_Inc::valeurs(), vectoriel, Zone_dis_base::zone(), and zone_EF().
imposer_symetrie()
void Zone_Cl_EF::imposer_symetrie (DoubleTab & values, int tous_les_sommets_sym = 0) const
Impose les conditions de symetrie
c.a.d annules les composantes du champ sur la ou les normales
si tous_les_sommets_sym =1 alors meme les sommets appartenant aussi a un dirichlet sont mis a zero.
Definition at line 361 of file Zone_Cl_EF.cpp.
{
// return;
  assert(values.dimension(1)==dimension);
  const Zone& z = zone_dis().zone();
  int nb_som_tot=z.nb_som_tot();
  assert(values.dimension_tot(0)==nb_som_tot);
  const DoubleTab& n =normales_symetrie_.valeur().valeurs();
  const DoubleTab& n_bis =normales_symetrie_bis_.valeur().valeurs();
  int dirmax=2;
  if (normales_symetrie_ter_.non_nul()) dirmax=3;
  for (int som=0; som<nb_som_tot; som++)
    if (( type_sommet_[som]==1)|| ( tous_les_sommets_sym&&(type_sommet_[som]%2==1)))
      {
        for (int dir=0; dir<dirmax; dir++)
          {
            const DoubleTab& nn=(dir==0?n:(dir==1?n_bis:normales_symetrie_ter_.valeur().valeurs()));
            double prod=0;
            for (int d=0; d<dimension; d++)
              prod+=values(som,d)*nn(som,d);
            for (int d=0; d<dimension; d++)
              values(som,d)-=prod*nn(som,d);
          }
      }
}
References TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_ >::dimension_tot(), Zone::nb_som_tot(), O_U_Ptr::non_nul(), normales_symetrie_, normales_symetrie_bis_, normales_symetrie_ter_, prod(), type_sommet_, Deriv_Champ_Don_base::valeur(), Champ_Don_base::valeurs(), Zone_dis::zone(), and Zone_Cl_dis_base::zone_dis().
Referenced by ajouter_bord(), Solveur_Masse_EF::appliquer_impl(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_pressure(), and imposer_cond_lim().
imposer_symetrie_matrice_secmem()
void Zone_Cl_EF::imposer_symetrie_matrice_secmem (Matrice_Morse & la_matrice, DoubleTab & secmem) const
Definition at line 486 of file Zone_Cl_EF.cpp.
{
// return;
  assert(secmem.dimension(1)==dimension);
  const Zone& z = zone_dis().zone();
  int nb_som=z.nb_som();
  assert(secmem.dimension(0)==nb_som);
  int nb_comp=secmem.dimension(1);
  const DoubleTab& n =normales_symetrie_.valeur().valeurs();
  const DoubleTab& n_bis =normales_symetrie_bis_.valeur().valeurs();
  ArrOfDouble normale(dimension);
  const IntVect& tab1=la_matrice.get_tab1();
  const IntVect& tab2=la_matrice.get_tab2();
  const DoubleTab& champ_inconnue = equation().inconnue().valeurs();
  int dirmax=2;
  if (normales_symetrie_ter_.non_nul()) dirmax=3;
  for (int som=0; som<nb_som; som++)
    if ( type_sommet_[som]==1)
      {
        for (int dir=0; dir<dirmax; dir++)
          {
            const DoubleTab& nn=(dir==0?n:(dir==1?n_bis:normales_symetrie_ter_.valeur().valeurs()));
            for (int d=0; d<dimension; d++) normale[d]=nn(som,d);
// On commence par recalculer secmem=secmem-A *present pour pouvoir modifier A (on en profite pour projeter)
            int nb_coeff_ligne=tab1[som*nb_comp+1] - tab1[som*nb_comp];
            for (int k=0; k<nb_coeff_ligne; k++)
              {
                for (int comp=0; comp<nb_comp; comp++)
                  {
                    int j=tab2[tab1[som*nb_comp+comp]-1+k]-1;
// assert(j!=(som*nb_comp+comp));
// if ((j>=(som*nb_comp))&&(j<(som*nb_comp+nb_comp)))
                    const    double coef_ij=la_matrice(som*nb_comp+comp,j);
                    int som2=j/nb_comp;
                    int comp2=j-som2*nb_comp;
                    secmem(som,comp)-=coef_ij*champ_inconnue(som2,comp2);
                  }
              }
            double somme_b=0;
            for (int comp=0; comp<nb_comp; comp++)
              somme_b+=secmem(som,comp)*normale[comp];
// Cerr<<som<<" sommet " <<somme_b<<" "<<secmem(som,0)<<" "<<secmem(som,1)<<finl;
// on retire secmem.n n
            for (int comp=0; comp<nb_comp; comp++)
              secmem(som,comp)-=somme_b*normale[comp];
            if (1)
              {
// on doit remettre la meme diagonale partout on prend la moyenne
                double ref=0;
                for (int comp=0; comp<nb_comp; comp++)
                  {
                    int j0=som*nb_comp+comp;
                    ref+=la_matrice.coef(j0,j0);
                  }
                ref/=nb_comp;
                for (int comp=0; comp<nb_comp; comp++)
                  {
                    int j0=som*nb_comp+comp;
                    double rap=ref/la_matrice.coef(j0,j0);
// Cerr<<dir<<" "<<som <<" "<<comp<<" rpp "<<rap <<finl;
                    for (int k=0; k<nb_coeff_ligne; k++)
                      {
                        int j=tab2[tab1[j0]-1+k]-1;
                        la_matrice(j0,j)*=rap;
                      }
                    assert(est_egal(la_matrice(j0,j0),ref));
                  }
              }
            if (1)
              {
// on annule tous les coef extra diagonaux du bloc
// sur les lignes i pour lesquelles normale(d) !=0
// c.a.d dasb(normale(d)>1e-5)
                for (int k=0; k<nb_coeff_ligne; k++)
                  {
                    for (int comp=0; comp<nb_comp; comp++)
                      if (std::fabs(normale[comp])>1e-5)
{
                          int j=tab2[tab1[som*nb_comp+comp]-1+k]-1;
                          if (j!=(som*nb_comp+comp))
                            if ((j>=(som*nb_comp))&&(j<(som*nb_comp+nb_comp)))
{
                                la_matrice(som*nb_comp+comp,j)=0;
                              }
                        }
                  }
              }
            {
// pour les blocs extra diagonaux on assure que Aij.ni=0
              ArrOfDouble somme(nb_coeff_ligne);
              for (int k=0; k<nb_coeff_ligne; k++)
                {
                  int j=tab2[tab1[som*nb_comp]-1+k]-1;
                  for (int comp=0; comp<nb_comp; comp++)
                    somme[k]+=la_matrice(som*nb_comp+comp,j)*normale[comp];
                }
// on retire somme ni
              for (int k=0; k<nb_coeff_ligne; k++)
                {
                  int j=tab2[tab1[som*nb_comp]-1+k]-1;
                  for (int comp=0; comp<nb_comp; comp++)
                    if ((j<(som*nb_comp))||(j>=(som*nb_comp+nb_comp)))
                      la_matrice(som*nb_comp+comp,j)-=(somme[k])*normale[comp];
                }
            }
// Finalement on recalule secmem=secmem+A*champ_inconnue (A a ete beaucoup modiife)
            for (int k=0; k<nb_coeff_ligne; k++)
              {
                for (int comp=0; comp<nb_comp; comp++)
                  {
                    int j=tab2[tab1[som*nb_comp+comp]-1+k]-1;
                    int som2=j/nb_comp;
                    int comp2=j-som2*nb_comp;
                    const    double coef_ij=la_matrice(som*nb_comp+comp,j);
                    secmem(som,comp)+=coef_ij*champ_inconnue(som2,comp2);
                  }
              }
            {
// verification
              double somme_b2=0;
              for (int comp=0; comp<nb_comp; comp++)
                somme_b2+=secmem(som,comp)*normale[comp];
// Cerr<<" lllllllll "<<somme_b2<<" "<<tt<<finl;
              assert(std::fabs(somme_b2) <1e-8);
// on retire secmem.n n
              for (int comp=0; comp<nb_comp; comp++)
                secmem(som,comp)-=somme_b2*normale[comp];
            }
          }
      }
// exit();
}
References Matrice_Morse::coef(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), est_egal(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Equation_base::inconnue(), Zone::nb_som(), O_U_Ptr::non_nul(), normales_symetrie_, normales_symetrie_bis_, normales_symetrie_ter_, type_sommet_, Deriv_Champ_Don_base::valeur(), Champ_Don_base::valeurs(), Champ_Inc::valeurs(), Zone_dis::zone(), and Zone_Cl_dis_base::zone_dis().
Referenced by Op_EF_base::modifier_pour_Cl().
imposer_symetrie_partiellement()
void Zone_Cl_EF::imposer_symetrie_partiellement (DoubleTab & values, const Noms & a_exclure) const
Definition at line 389 of file Zone_Cl_EF.cpp.
{
  const IntTab& faces_sommets=zone_EF().face_sommets();
  int nb_som_face=faces_sommets.dimension(1);
  const DoubleTab& n =normales_symetrie_.valeur().valeurs();
  const DoubleTab& n_bis =normales_symetrie_bis_.valeur().valeurs();
  int dirmax=2;
  if (normales_symetrie_ter_.non_nul()) dirmax=3;
  int nbcond=nb_cond_lim();
  ArrOfInt type_sommet_bis(type_sommet_);
  for (int n_bord=0; n_bord<nbcond; n_bord++)
    {
      const Cond_lim_base& la_cl = les_conditions_limites(n_bord).valeur();
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num2 =  le_bord.nb_faces_tot();
      const Nom& nom_bord=le_bord.le_nom();
      if (sub_type(Symetrie,la_cl)&&(a_exclure.rang(nom_bord)>-1))
        {
          Cerr<<__FILE__<<(int)__LINE__<<" on  impose pas symetrie sur "<<nom_bord<<finl;
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int s=0; s<nb_som_face; s++)
                {
                  int som=faces_sommets(face,s);
                  type_sommet_bis[som]=3;
                }
            }
        }
    }
  for (int n_bord=0; n_bord<nbcond; n_bord++)
    {
      const Cond_lim_base& la_cl = les_conditions_limites(n_bord).valeur();
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num2 =  le_bord.nb_faces_tot();
      const Nom& nom_bord=le_bord.le_nom();
      if (sub_type(Symetrie,la_cl)&&(a_exclure.rang(nom_bord)<0))
        {
          Cerr<<__FILE__<<(int)__LINE__<<" on impose symetrie sur "<<nom_bord<<finl;
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int s=0; s<nb_som_face; s++)
                {
                  int som=faces_sommets(face,s);
                  if ( type_sommet_bis[som]==1)  //|| ( tous_les_sommets_sym&&(type_sommet_(som)%2==1)))
                    {
                      for (int dir=0; dir<dirmax; dir++)
{
                          const DoubleTab& nn=(dir==0?n:(dir==1?n_bis:normales_symetrie_ter_.valeur().valeurs()));
                          double prod=0;
                          for (int d=0; d<dimension; d++)
                            prod+=values(som,d)*nn(som,d);
                          for (int d=0; d<dimension; d++)
                            values(som,d)-=prod*nn(som,d);
                        }
                    }
                }
            }
        }
    }
}
References Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::face_sommets(), finl, Cond_lim_base::frontiere_dis(), Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), O_U_Ptr::non_nul(), normales_symetrie_, normales_symetrie_bis_, normales_symetrie_ter_, Front_VF::num_face(), prod(), Noms::rang(), ref_cast, sub_type, type_sommet_, Deriv_Champ_Don_base::valeur(), Champ_Don_base::valeurs(), and zone_EF().
info()
const Type_info * Zone_Cl_EF::info () static
Definition at line 39 of file Zone_Cl_EF.cpp.
initialiser()
int Zone_Cl_EF::initialiser (double temps) override virtual
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Returns
int
Signification: 1 si OK, 0 sinon
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 807 of file Zone_Cl_EF.cpp.
{
  Zone_Cl_dis_base::initialiser(temps);
  if (nb_bord_periodicite()>0)
    {
      Cerr<<" La periodicite n'est pas code !!!"<<finl;
      abort();
    }
  return 1;
}
References Process::abort(), Cerr, finl, Zone_Cl_dis_base::initialiser(), and nb_bord_periodicite().
modifie_gradient()
void Zone_Cl_EF::modifie_gradient (ArrOfDouble & grad_mod, const ArrOfDouble & grad, int num_som) const
Definition at line 459 of file Zone_Cl_EF.cpp.
{
  if (type_sommet_[som]!=1) return;
  assert(grad_mod.size_array()==dimension);
  const DoubleTab& n =normales_symetrie_.valeur().valeurs();
  const DoubleTab& n_bis =normales_symetrie_bis_.valeur().valeurs();
  assert ( type_sommet_[som]>=1);
  int dirmax=2;
  if (normales_symetrie_ter_.non_nul()) dirmax=3;
  for (int dir=0; dir<dirmax; dir++)
    {
      const DoubleTab& nn=(dir==0?n:(dir==1?n_bis:normales_symetrie_ter_.valeur().valeurs()));
      double prod=0;
      for (int d=0; d<dimension; d++)
        prod+=grad[d]*nn(som,d);
      for (int d=0; d<dimension; d++)
        grad_mod[d]+=prod*nn(som,d);
    }
}
References Objet_U::dimension, O_U_Ptr::non_nul(), normales_symetrie_, normales_symetrie_bis_, normales_symetrie_ter_, prod(), TRUSTArray< _TYPE_ >::size_array(), type_sommet_, Deriv_Champ_Don_base::valeur(), and Champ_Don_base::valeurs().
Referenced by Assembleur_P_EF::assembler_mat().
nb_bord_periodicite()
int Zone_Cl_EF::nb_bord_periodicite () const
Definition at line 795 of file Zone_Cl_EF.cpp.
{
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if (sub_type(Periodique,les_conditions_limites_[cl].valeur()))
        compteur++;
    }
  return compteur;
}
References compteur, Zone_Cl_dis_base::les_conditions_limites_, vect_impl::size(), sub_type, and valeur().
Referenced by initialiser().
nb_faces_sortie_libre()
int Zone_Cl_EF::nb_faces_sortie_libre () const
Definition at line 777 of file Zone_Cl_EF.cpp.
{
  exit();
  /*
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if(sub_type(Neumann_sortie_libre, les_conditions_limites_[cl].valeur()))
  {
    const Front_VF& le_bord=ref_cast(Front_VF,les_conditions_limites_[cl]->frontiere_dis());
    compteur+=le_bord.nb_faces();
  }
    }
  return compteur;
  */
  return -1;
}
References Process::exit().
printOn()
Sortie & Zone_Cl_EF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 67 of file Zone_Cl_EF.cpp.
{
  return os;
}
readOn()
Entree & Zone_Cl_EF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 75 of file Zone_Cl_EF.cpp.
{
  return Zone_Cl_dis_base::readOn(is) ;
}
References Zone_Cl_dis_base::readOn().
remplir_type_elem_Cl()
void Zone_Cl_EF::remplir_type_elem_Cl (const Zone_EF & la_zone_EF) protected
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
Definition at line 169 of file Zone_Cl_EF.cpp.
{
  const Zone& z = la_zone_EF.zone();
  const IntTab& faces_sommets=la_zone_EF.face_sommets();
  int nb_som_face=faces_sommets.dimension(1);
  int nb_som_tot=z.nb_som_tot();
  type_sommet_.resize_array(z.nb_som_tot());
  type_sommet_=-1;
  IntTab titi(nb_som_tot);
  for(int i=0; i<les_conditions_limites_.size(); i++)
    {
      Cond_lim_base& la_cl=les_conditions_limites_[i].valeur();
      const Front_VF& le_bord= la_zone_EF.front_VF(i);
      int num2 =  le_bord.nb_faces_tot();
      if ( (sub_type(Dirichlet,la_cl))|| (sub_type(Dirichlet_homogene,la_cl)) )
        {
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int s=0; s<nb_som_face; s++)
                {
                  int som=faces_sommets(face,s);
// Si on a Dirichlet_paroi_fixe_iso_Genepi2 on ne prend pas en compte le 0 pour la moyenne
                  if (!sub_type(Dirichlet_paroi_fixe_iso_Genepi2,la_cl))
                    titi(som)++;
                  if ((type_sommet_[som]!=1)&& (type_sommet_[som]!=3))
                    type_sommet_[som]=2;
                  else
                    type_sommet_[som]=3;
                }
            }
        }
      else if ( (sub_type(Symetrie,la_cl)))
        {
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int s=0; s<nb_som_face; s++)
                {
                  int som=faces_sommets(face,s);
                  if (type_sommet_[som]<=1)
                    type_sommet_[som]=1;
                  else
                    type_sommet_[som]=3;
                }
            }
        }
      else  if ( (sub_type(Neumann,la_cl))|| (sub_type(Neumann_homogene,la_cl)) )
        {
          for (int ind_face=0; ind_face<num2; ind_face++)
            {
              int face=le_bord.num_face(ind_face);
              for (int s=0; s<nb_som_face; s++)
                {
                  int som=faces_sommets(face,s);
                  if (type_sommet_[som]<0)
                    type_sommet_[som]=0;
                }
            }
        }
      else
        {
          Cerr<<__FILE__<<":" <<(int)__LINE__<<" non code pour cette cl "<<la_cl.que_suis_je()<<finl;
        }
    }
// si on a un dirichet on stocke 2*nb participant + 1 si sommet aussi de sym
  for (int som=0; som<nb_som_tot; som++)
    {
      if (type_sommet_[som]>1)
        {
// assert(titi(som)>0);
          type_sommet_[som]+=2*(titi(som));
        }
    }
// On cree la connectivite sommet -> face de bord symetrie
  if (equation().inconnue().valeur().nature_du_champ()==vectoriel)
    {
      equation().probleme().discretisation().discretiser_champ("VITESSE",la_zone_EF,"normales_nodales","1",dimension,0.,normales_symetrie_);
      equation().probleme().discretisation().discretiser_champ("CHAMP_SOMMETS",la_zone_EF,"normales_nodales_bis","1",dimension,0., normales_symetrie_bis_);
      Static_Int_Lists sommet_face_symetrie;
      int type_cl=1;
      construit_connectivite_sommet(type_cl,sommet_face_symetrie,les_conditions_limites_,la_zone_EF);
// sommet_face_symetrie contient le nombre de face de symetrie associe a chaque sommet
      const DoubleTab& face_normales = la_zone_EF.face_normales();
      ArrOfDouble n(dimension),t1(dimension),t2(dimension);
      for (int som=0; som<nb_som_tot; som++)
        {
          int nbf= sommet_face_symetrie.get_list_size(som);
          if (nbf>0)
// if (type_sommet_(som)==1)
            {
              n=0;
              t1=0;
              t2=0;
// on determine la normale sommet
// int nbf= sommet_face_symetrie.get_list_size(som);
              for (int f=0; f<nbf; f++)
                {
                  int face=sommet_face_symetrie(som,f);
                  for (int d=0; d<dimension; d++)
                    n[d]+=face_normales(face,d);
                }
              n/=nbf;
              double norm_n=norme_array(n);
              n/=norm_n;
              for (int d=0; d<dimension; d++)
                normales_symetrie_.valeur().valeurs()(som,d)=n[d];
// Cerr<<som<<" on doit annuler une premiere direction "<<n(0) << " " <<n(1)<<" "<<n(dimension==3?2:1)<<finl;
              for (int f=0; f<nbf; f++)
                {
                  int face=sommet_face_symetrie(som,f);
                  double prod=0;
                  for (int d=0; d<dimension; d++)
                    prod+=face_normales(face,d)*n[d];
                  double s=0;
// double v = 0;
                  for (int d=0; d<dimension; d++)
                    {
                      t1[d]=face_normales(face,d)-n[d]*prod;
                      s+=face_normales(face,d)*face_normales(face,d);
// v+=t1[d]*n[d];
                    }
// Cerr<<" vv"<< v<<" "<<norme_array(t1)<<" "<<norm_n<<finl;
                  if (norme_array(t1)>(1e-4*sqrt(s)))
                    {
// facilite le debugage
                      if (std::fabs(min_array(t1))>max_array(t1))
                        t1*=-1;
                      t1/=norme_array(t1);
// Cerr<<som<<" on doit annuler une deuxieme direction "<<t1(0) << " " <<t1(1)<<" "<<t1(dimension==3?2:1)<<finl;
                      f=nbf;
                      for (int d=0; d<dimension; d++)
                        normales_symetrie_bis_.valeur().valeurs()(som,d)=t1[d];
// assert(v==0);
                    }
                }
              for (int f=0; f<nbf; f++)
                {
                  int face=sommet_face_symetrie(som,f);
                  double prod=0,prod1=0,s=0;
                  for (int d=0; d<dimension; d++)
                    {
                      prod+=face_normales(face,d)*n[d];
                      prod1+=face_normales(face,d)*t1[d];
                      s+=face_normales(face,d)*face_normales(face,d);
                    }
                  for (int d=0; d<dimension; d++)
                    t2[d]=face_normales(face,d)-n[d]*prod-t1[d]*prod1;
                  if (norme_array(t2)>(1e-4*sqrt(s)))
                    {
// facilite le debugage
                      if (std::fabs(min_array(t2))>max_array(t2))
                        t2*=-1;
                      t2/=norme_array(t2);
                      Cerr<<face<<" "<<nbf<<" sommet "<<som<<" "<<norme_array(t2)/s<<" on doit annuler une troiseme direction"<<t2[0] << " " <<t2[1]<<" "<<t2[2]<<finl;
                      Cerr<<som<<" "<<t1[0] << " " <<t1[1]<<" "<<t1[2]<<finl;
                      Cerr<<som<<" "<<n[0] << " " <<n[1]<<" "<<n[2]<<finl;
                      f=nbf;
                      if (!normales_symetrie_ter_.non_nul())
                        equation().probleme().discretisation().discretiser_champ("CHAMP_SOMMETS",la_zone_EF,"normales_nodales_bis","1",dimension,0., normales_symetrie_ter_);
                      for (int d=0; d<dimension; d++)
                        normales_symetrie_ter_.valeur().valeurs()(som,d)=t2[d];
// exit();
                    }
                }
            }
        }
      normales_symetrie_.valeur().valeurs().echange_espace_virtuel();
      normales_symetrie_bis_.valeur().valeurs().echange_espace_virtuel();
// exit();
    }
}
References Cerr, construit_connectivite_sommet(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), MorEqn::equation(), Zone_EF::face_normales(), Zone_VF::face_sommets(), finl, Zone_VF::front_VF(), Static_Int_Lists::get_list_size(), Equation_base::inconnue(), Zone_Cl_dis_base::les_conditions_limites_, max_array(), min_array(), Field_base::nature_du_champ(), Front_VF::nb_faces_tot(), Zone::nb_som_tot(), O_U_Ptr::non_nul(), normales_symetrie_, normales_symetrie_bis_, normales_symetrie_ter_, norme_array(), Front_VF::num_face(), Equation_base::probleme(), prod(), Objet_U::que_suis_je(), TRUSTArray< _TYPE_ >::resize_array(), vect_impl::size(), sub_type, type_sommet_, Deriv_Champ_Don_base::valeur(), Deriv_Champ_Inc_base::valeur(), Champ_Don_base::valeurs(), vectoriel, and Zone_dis_base::zone().
Referenced by completer().
self_cast() [1/2]
const Zone_Cl_EF & Zone_Cl_EF::self_cast (const Objet_U & r) static
Definition at line 39 of file Zone_Cl_EF.cpp.
self_cast() [2/2]
Zone_Cl_EF & Zone_Cl_EF::self_cast (Objet_U & r) static
Definition at line 39 of file Zone_Cl_EF.cpp.
taille_memoire()
unsigned Zone_Cl_EF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 39 of file Zone_Cl_EF.cpp.
zone_EF() [1/2]
Zone_EF & Zone_Cl_EF::zone_EF ()
Definition at line 819 of file Zone_Cl_EF.cpp.
{
  return ref_cast(Zone_EF, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Referenced by imposer_cond_lim(), and imposer_symetrie_partiellement().
zone_EF() [2/2]
const Zone_EF & Zone_Cl_EF::zone_EF () const
Definition at line 824 of file Zone_Cl_EF.cpp.
{
  return ref_cast(Zone_EF, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Member Data Documentation
info_obj
const Type_info Zone_Cl_EF::info_obj static
Definition at line 42 of file Zone_Cl_EF.h.
modif_perio_fait_
int Zone_Cl_EF::modif_perio_fait_ protected
Definition at line 72 of file Zone_Cl_EF.h.
Referenced by completer().
normales_symetrie_
Champ_Don Zone_Cl_EF::normales_symetrie_ protected
Definition at line 79 of file Zone_Cl_EF.h.
Referenced by imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().
normales_symetrie_bis_
Champ_Don Zone_Cl_EF::normales_symetrie_bis_ protected
Definition at line 79 of file Zone_Cl_EF.h.
Referenced by imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().
normales_symetrie_ter_
Champ_Don Zone_Cl_EF::normales_symetrie_ter_ protected
Definition at line 79 of file Zone_Cl_EF.h.
Referenced by imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().
type_sommet_
ArrOfInt Zone_Cl_EF::type_sommet_ protected
-1 interne 0 Neumann 1 Symetrie >2 Dirichlet Un sommet est d'abord diri , puis Symetrie , puis Neumann , puis interne
Definition at line 77 of file Zone_Cl_EF.h.
Referenced by get_type_sommet(), imposer_cond_lim(), imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().
The documentation for this class was generated from the following files:
src/EF/Zones/Zone_Cl_EF.h
src/EF/Zones/Zone_Cl_EF.cpp