TRUST: Perte_Charge_Reguliere_VDF_Face Class Reference
Perte_Charge_Reguliere_VDF_Face Class Reference
class Perte_Charge_Reguliere_VDF_Face
#include <Perte_Charge_Reguliere_VDF_Face.h>
Public Member Functions
Perte_Charge_Reguliere_VDF_Face ()
~Perte_Charge_Reguliere_VDF_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter_ (const DoubleTab &, DoubleTab &) const
void remplir_num_faces (Nom &)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Perte_Charge_Reguliere_VDF_Face & self_cast (Objet_U &)
static const
Perte_Charge_Reguliere_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Detailed Description
class Perte_Charge_Reguliere_VDF_Face
See also:
Perte_Charge_VDF_Face
Definition at line 39 of file Perte_Charge_Reguliere_VDF_Face.h.
Constructor & Destructor Documentation
Perte_Charge_Reguliere_VDF_Face::Perte_Charge_Reguliere_VDF_Face ()
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
Perte_Charge_Reguliere_VDF_Face::~Perte_Charge_Reguliere_VDF_Face ()
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
Member Function Documentation
DoubleTab & Perte_Charge_Reguliere_VDF_Face::ajouter_ (const DoubleTab & inco, DoubleTab & resu) const [virtual]
Implements Source_dep_inco_base.
Definition at line 143 of file Perte_Charge_Reguliere_VDF_Face.cpp.
References Perte_Charge_Reguliere::calculer_Cf_blasius(), Cerr, Perte_Charge_Reguliere::CF(), Perte_Charge_Reguliere::Cf_utilisateur, Perte_Charge_VDF_Face::corr_front_ss, Perte_Charge_Reguliere::couronne_tube, Perte_Charge_Reguliere::D(), Perte_Charge_Reguliere::d(), dabs(), Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), Zone_VF::face_voisins(), finl, Perte_Charge_VDF_Face::la_vitesse, Perte_Charge_VDF_Face::la_zone_VDF, Perte_Charge_VDF_Face::le_fluide, Perte_Charge_VDF_Face::num_faces, Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, IntVect::size(), sub_type, Deriv_Champ_Don_base::valeur(), Ref_Zone_VDF::valeur(), Champ_Don::valeurs(), and Zone_VF::volumes_entrelaces().
{
  const Zone_VDF& zone_VDF = la_zone_VDF.valeur();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const DoubleVect& volumes_entrelaces = zone_VDF.volumes_entrelaces();
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const DoubleVect& porosite_surf = zone_VDF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  int ndeb_faces_int = zone_VDF.premiere_face_int();
// on prend nu et non mu
  const Champ_Don& nu = le_fluide->viscosite_cinematique();
  double d_visco=-1;
  int l_visco_unif=0;
  if (sub_type(Champ_Uniforme,nu.valeur()))
    {
      const Champ_Uniforme& ch_nu = ref_cast(Champ_Uniforme,nu.valeur());
      d_visco = ch_nu(0,0);
      l_visco_unif = 1;
    }
  {
    int nb_faces,numfa;
    double Cf,CK,U,U_abs,Reynolds;
    const DoubleTab& visco = nu.valeurs();
    {
      nb_faces = num_faces.size();
      for (int i=0; i<nb_faces; i++)
        {
          numfa = num_faces[i];
          U = inco[numfa];
          U_abs = dabs(vit[numfa]);
          if (!l_visco_unif)
            {
              if (numfa < ndeb_faces_int)
                {
                  int n0 = face_voisins(numfa,0);
                  if (n0 != -1)
                    d_visco =  visco[n0];
                  else
                    d_visco = visco[face_voisins(numfa,1)];
                }
              else
                d_visco = 0.5*(visco[face_voisins(numfa,0)]+visco[face_voisins(numfa,1)]);
            }
          if (couronne_tube == 1)
            {
              if (vit!=inco)
                {
                  Cerr<<"not implemented " <<finl;
                  exit();
                }
              double U_res=0.,vit1,vit2,div,corr_sign=1.0;
              int ori,el,fa1,fa2,fa3,fa4 ;
// modifications ajoutees par fabio :
              ori = zone_VDF.orientation(numfa);
              vit1 = 0;
              vit2 = 0;
              div = 4.;
              for (int ind=0; ind <2; ind++)
                {
                  el = face_voisins(numfa,ind);
                  if (el!=-1)
                    {
                      fa1 = elem_faces(el,(ori+1));
                      fa2 = elem_faces(el,(ori+1+dimension)%(2*dimension));
                      vit1 += vit[fa1] + vit[fa2] ;
                      if (dimension == 3)
{
                          fa3 = elem_faces(el,(ori+2));
                          fa4 = elem_faces(el,(ori+2+dimension)%(2*dimension));
                          vit2 += vit[fa3] + vit[fa4];
                        }
                    }
                  else div = 2.;
                }
              vit1 = vit1/div;
              U_res = U*U+vit1*vit1;
              if (dimension == 3)
                {
                  vit2 = vit2/div;
                  U_res += vit2*vit2;
                }
// U_res = sqrt(U_res)/rasu();
              U_res = sqrt(U_res);
              Reynolds = U_res*d()/d_visco;
              if (!Cf_utilisateur)
                Cf = calculer_Cf_blasius(Reynolds);
              else
                Cf = CF();
              CK = -0.5*Cf/D();
              if (U != 0)
                {
                  corr_sign = U/dabs(U);
                }
              resu[numfa] += CK*U_res*U_res*volumes_entrelaces[numfa]*porosite_surf[numfa]*corr_front_ss[i]*corr_sign;
            }
          else
            {
              Reynolds = U_abs*d()/d_visco;
              if (!Cf_utilisateur)
                Cf = calculer_Cf_blasius(Reynolds);
              else
                Cf = CF();
              CK = -0.5*Cf/D();
              resu[numfa] += CK*U*U_abs*volumes_entrelaces[numfa]*porosite_surf[numfa]*corr_front_ss[i];
            }
        }
    }
  }
  return resu;
}
Objet_U * Perte_Charge_Reguliere_VDF_Face::cree_instance () [static]
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
int Perte_Charge_Reguliere_VDF_Face::duplique () const [virtual]
Implements Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
const Type_info * Perte_Charge_Reguliere_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
const Type_info * Perte_Charge_Reguliere_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
Sortie & Perte_Charge_Reguliere_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 38 of file Perte_Charge_Reguliere_VDF_Face.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() ;
}
Entree & Perte_Charge_Reguliere_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 47 of file Perte_Charge_Reguliere_VDF_Face.cpp.
References Cerr, finl, Perte_Charge_Reguliere::lire_donnees(), and remplir_num_faces().
{
  Perte_Charge_Reguliere::lire_donnees(s);
  Nom nom_sous_zone;
  s >> nom_sous_zone;
  Cerr << " nom de la sous zone " << nom_sous_zone << finl ;
  remplir_num_faces(nom_sous_zone);
  return s ;
}
void Perte_Charge_Reguliere_VDF_Face::remplir_num_faces (Nom & nom_sous_zone)
< le poly voisin n'est pas dans la sous_zone
< le poly voisin n'est pas dans la sous_zone
Definition at line 66 of file Perte_Charge_Reguliere_VDF_Face.cpp.
References Cerr, Perte_Charge_VDF_Face::corr_front_ss, Perte_Charge_Reguliere::correction_direction(), Objet_U::dimension, Perte_Charge_Reguliere::dir, Perte_Charge::direction_perte_charge(), Probleme_base::domaine(), Zone_VF::elem_faces(), MorEqn::equation(), face_associee, Zone_VF::face_voisins(), finl, Zone_dis_base::nb_elem_tot(), Sous_Zone::nb_elem_tot(), Perte_Charge_VDF_Face::num_faces, Equation_base::probleme(), ref_cast, DoubleVect::resize(), IntVect::resize(), Domaine::ss_zone(), valeur(), Zone_VF::volumes(), and Zone_VF::xv().
Referenced by readOn().
{
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_VDF& zone_VDF = ref_cast(Zone_VDF,equation().zone_dis().valeur());
  const IntTab& elem_faces = zone_VDF.elem_faces();
  const IntTab& face_voisins = zone_VDF.face_voisins();
  const DoubleVect& volumes = zone_VDF.volumes();
  const DoubleTab& xv = zone_VDF.xv() ;
  const Sous_Zone& la_sous_zone = le_domaine.ss_zone(nom_sous_zone);
  int nb_poly_ss_zone = la_sous_zone.nb_elem_tot();
  int k = direction_perte_charge();
  DoubleVect xv_(dimension) ;
  int dir_a_faire ;
  int face_associee,nfac;
  int num_poly;
  num_faces.resize(nb_poly_ss_zone*6);
  corr_front_ss.resize(nb_poly_ss_zone*6);
  corr_front_ss = 1. ;
  nfac = 0 ;
  IntVect num_loc(zone_VDF.nb_elem_tot());
  num_loc = -1;
  int num_elem,num_face;
  for (num_elem=0; num_elem<nb_poly_ss_zone; num_elem++)
    {
      num_loc[la_sous_zone(num_elem)] = num_elem;
    }
  for (int direction = 0; direction<dimension; direction++)
    {
      Cerr << " Perte_Charge_Reguliere_VDF_Face::remplir num_face en direction " << direction << finl ;
      if ((direction ==  k) || (dir[direction] == 1 ))
        {
          dir_a_faire = k ;
          if (dir[direction] == 1 ) dir_a_faire = direction ;
          for (num_elem=0; num_elem<nb_poly_ss_zone; num_elem++)
            {
              num_poly = la_sous_zone(num_elem);
              num_face =  elem_faces(num_poly,dir_a_faire);
              num_faces[nfac++] = num_face;
              for (int ifa=0; ifa<dimension; ifa++) xv_(ifa)= xv(num_face,ifa) ;
              corr_front_ss[nfac-1] *= correction_direction( xv_ , dir_a_faire );
              int num_poly_vois0 = face_voisins(num_face,0);
              if (num_poly_vois0 != -1)
                if (num_loc[num_poly_vois0] == -1)  //!< le poly voisin n'est pas dans la sous_zone
                  {
                    corr_front_ss[nfac-1]*= volumes(num_poly)/(volumes(num_poly)+volumes(num_poly_vois0)) ;
                  }
              face_associee = elem_faces(num_poly,dir_a_faire+dimension);
              int num_poly_vois1 = face_voisins(face_associee,1);
              if (num_poly_vois1 != -1)
                {
                  if (num_loc[num_poly_vois1] == -1)  //!< le poly voisin n'est pas dans la sous_zone
                    {
                      num_faces[nfac++] = face_associee;
                      for (int ifa=0; ifa<dimension; ifa++) xv_(ifa) = xv(face_associee,ifa) ;
                      corr_front_ss[nfac-1] *= correction_direction( xv_, dir_a_faire);
                      corr_front_ss[nfac-1] *= volumes(num_poly)/(volumes(num_poly)+volumes(num_poly_vois1)) ;
                    }
                }
              else
                {
                  num_faces[nfac++]=face_associee;
                }
            }
        }
    }
  num_faces.resize(nfac);
  corr_front_ss.resize(nfac);
}
Perte_Charge_Reguliere_VDF_Face & Perte_Charge_Reguliere_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
const Perte_Charge_Reguliere_VDF_Face & Perte_Charge_Reguliere_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
unsigned Perte_Charge_Reguliere_VDF_Face::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 31 of file Perte_Charge_Reguliere_VDF_Face.cpp.
Member Data Documentation
const Type_info Perte_Charge_Reguliere_VDF_Face::info_obj [static]
Reimplemented from Perte_Charge_VDF_Face.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face.
Definition at line 44 of file Perte_Charge_Reguliere_VDF_Face.h.
The documentation for this class was generated from the following files:
src/VDF/Sources/Perte_Charge_Reguliere_VDF_Face.h
src/VDF/Sources/Perte_Charge_Reguliere_VDF_Face.cpp