TRUST: TRUSTTabFT< _TYPE_ > Class Template Reference
TRUSTTabFT< _TYPE_ > Class Template Reference
#include <TRUSTTabFT.h>
Public Member Functions
TRUSTTabFT ()
TRUSTTabFT (const TRUSTTabFT &)=default
TRUSTTabFT (int i, int j)
TRUSTTabFT (const TRUSTTab< _TYPE_ > &x)
TRUSTTabFT & operator= (const TRUSTTab< _TYPE_ > &x)
TRUSTTabFT & operator= (const TRUSTTabFT &x)
TRUSTTabFT & operator= (const double x)
Public Member Functions inherited from TRUSTTab< _TYPE_ >
TRUSTTab ()
TRUSTTab (const TRUSTTab &dbt)
TRUSTTab (int n)
TRUSTTab (int n1, int n2)
TRUSTTab (int n1, int n2, int n3)
TRUSTTab (int n1, int n2, int n3, int n4)
void resize_dim0 (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n1, int n2, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n1, int n2, int n3, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (int n1, int n2, int n3, int n4, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void resize (const TRUSTArray< int > &tailles, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy (const TRUSTTab &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void append_line (_TYPE_)
void append_line (_TYPE_, _TYPE_)
void append_line (_TYPE_, _TYPE_, _TYPE_)
void append_line (_TYPE_, _TYPE_, _TYPE_, _TYPE_)
int dimension (int) const
int dimension_tot (int) const
int nb_dim () const
TRUSTTab & operator= (const TRUSTTab &)
TRUSTTab & operator= (const TRUSTVect< _TYPE_ > &)
TRUSTTab & operator= (_TYPE_ d)
_TYPE_ & operator() (const TRUSTArray< int > &indice)
_TYPE_ operator() (const TRUSTArray< int > &indice) const
_TYPE_ & operator[] (int i)
const _TYPE_ & operator[] (int i) const
_TYPE_ & operator() (int i)
const _TYPE_ & operator() (int i) const
_TYPE_ & operator() (int i1, int i2)
const _TYPE_ & operator() (int i1, int i2) const
_TYPE_ & operator() (int i1, int i2, int i3)
const _TYPE_ & operator() (int i1, int i2, int i3) const
_TYPE_ & operator() (int i1, int i2, int i3, int i4)
const _TYPE_ & operator() (int i1, int i2, int i3, int i4) const
void ajoute_produit_tensoriel (double alpha, const TRUSTTab< double > &, const TRUSTTab< double > &)
z+=alpha*x*y;
void resoud_LU (int, TRUSTArray< int > &, const TRUSTArray< double > &, TRUSTArray< double > &)
int inverse_LU (const TRUSTArray< double > &, TRUSTArray< double > &)
int decomp_LU (int, TRUSTArray< int > &, TRUSTTab< double > &)
double max_du_u (const TRUSTTab< double > &)
virtual void ref (const TRUSTTab &)
virtual void ref_tab (TRUSTTab &, int start_line=0, int nb_lines=-1)
void set_md_vector (const MD_Vector &) override
void jump (Entree &) override
void lit (Entree &, int resize_and_read=1) override
void ecrit (Sortie &) const override
void ref (const TRUSTVect< _TYPE_ > &) override
void ref_data (_TYPE_ *ptr, int size) override
void ref_array (TRUSTArray< _TYPE_ > &, int start=0, int sz=-1) override
void reset () override
void resize_tab (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT) override
Public Member Functions inherited from TRUSTVect< _TYPE_ >
virtual ~TRUSTVect ()
TRUSTVect ()
TRUSTVect (int n)
construction d'un vecteur de taille n. Les elements du vecteur sont initialises a zero par defaut. Pour ne pas initialiser les valeurs, utiliser ceci:
DoubleVect toto;
toto.resize(n, NOCOPY_NOINIT);
TRUSTVect (const TRUSTVect &v)
Constructeur par copie. Il s'agit d'un "deep copy" voir ArrOfDouble::ArrOfDouble(const ArrOfDouble &)
Remarque: il n'y a pas de constructeur par copie a partir de ArrOfDouble
Ceci est volontaire, sinon on risque de grosses pertes de performances par creation implicite d'objets, difficile a trouver.
(exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt produit une copie du tableau !)
Utiliser copy() pour copier un ArrOfDouble dans un DoubleVect.
TRUSTVect & operator= (const TRUSTVect &)
TRUSTVect & operator= (_TYPE_)
int size () const
int size_totale () const
int size_reelle () const
int size_reelle_ok () const
int line_size () const
void resize (int, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy (const TRUSTArray< _TYPE_ > &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy (const TRUSTVect &, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void operator+= (const TRUSTVect &v)
void operator+= (const _TYPE_ x)
void operator-= (const TRUSTVect &v)
void operator-= (const _TYPE_ x)
void operator*= (const TRUSTVect &v)
void operator*= (const _TYPE_ x)
void operator/= (const TRUSTVect< double > &v)
void operator/= (const TRUSTVect< int > &v)=delete
forbidden
void operator/= (const _TYPE_ x)
void abs (Mp_vect_options opt=VECT_ALL_ITEMS)
void carre (Mp_vect_options opt=VECT_ALL_ITEMS)
void racine_carree (Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute (double alpha, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute_sans_ech_esp_virt (double alpha, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_REAL_ITEMS)
x+=alpha*y sans echange_espace_virtuel
void ajoute_produit_scalaire (double alpha, const TRUSTVect< double > &x, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_ALL_ITEMS)
z+=alpha*x*y;
void ajoute_carre (double alpha, const TRUSTVect< double > &y, Mp_vect_options opt=VECT_ALL_ITEMS)
void ajoute (int alpha, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... a voir si besoin
void ajoute_sans_ech_esp_virt (int alpha, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_REAL_ITEMS)=delete
forbidden ... a voir si besoin
void ajoute_produit_scalaire (int alpha, const TRUSTVect< int > &x, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... a voir si besoin
void ajoute_carre (int alpha, const TRUSTVect< int > &y, Mp_vect_options opt=VECT_ALL_ITEMS)=delete
forbidden ... a voir si besoin
_TYPE_ local_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ local_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ local_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ local_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_max_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_min_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_max_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_min_abs_vect (Mp_vect_options opt=VECT_REAL_ITEMS) const
_TYPE_ mp_norme_vect () const
virtual void ref (const TRUSTVect &)
virtual void echange_espace_virtuel ()
virtual void set_md_vector (const MD_Vector &)
virtual void jump (Entree &)
virtual void lit (Entree &, int resize_and_read=1)
virtual void ecrit (Sortie &) const
virtual void detach_vect ()
virtual const MD_Vector & get_md_vector () const
void resize_tab (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT) override
void ref_data (_TYPE_ *ptr, int new_size) override
void ref_array (TRUSTArray< _TYPE_ > &, int start=0, int sz=-1) override
void reset () override
met l'objet dans l'etat obtenu par le constructeur par defaut.
Public Member Functions inherited from TRUSTArray< _TYPE_ >
Iterator begin ()
Iterator end ()
virtual ~TRUSTArray ()
TRUSTArray ()
TRUSTArray (int n)
TRUSTArray (const TRUSTArray &A)
void resize (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void resize_array (int new_size, Array_base::Resize_Options opt=COPY_INIT)
void set_smart_resize (int flag)
void set_mem_storage (const Storage storage)
Storage get_mem_storage () const
TRUSTArray & operator= (const TRUSTArray &)
TRUSTArray & operator= (_TYPE_ x)
_TYPE_ & operator[] (int i)
const _TYPE_ & operator[] (int i) const
!<
_TYPE_ & operator() (int i)
const _TYPE_ & operator() (int i) const
_TYPE_ * addr ()
!<
const _TYPE_ * addr () const
int size_array () const
int ref_count () const
void append_array (_TYPE_ valeur)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & inject_array (const TRUSTArray &source, int nb_elements=-1, int first_element_dest=0, int first_element_source=0)
TRUSTArray & copy_array (const TRUSTArray &a)
void ordonne_array ()
void array_trier_retirer_doublons ()
!<
virtual void ref_data (_TYPE_ *ptr, int size)
virtual void reset ()
virtual void ref_array (TRUSTArray &, int start=0, int sz=-1)
virtual void resize_tab (int n, Array_base::Resize_Options opt=COPY_INIT)
Public Member Functions inherited from Array_base
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Additional Inherited Members
Public Types inherited from TRUSTArray< _TYPE_ >
using value_type = _TYPE_
return int, double ou float
using Iterator = TRUSTIterator< TRUSTArray< _TYPE_ > >
Public Types inherited from Array_base
enum Resize_Options { NOCOPY_NOINIT = 0 , COPY_NOINIT = 1 , COPY_INIT = 2 }
enum Storage { STANDARD , TEMP_STORAGE }
Static Public Member Functions inherited from Array_base
static const Type_info * info ()
static Array_base & self_cast (Objet_U &)
static const Array_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes inherited from Array_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions inherited from TRUSTTab< _TYPE_ >
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
ecriture d'un tableau sequentiel (idem que TRUSTVect::printOn() on ne sait pas quoi faire de pertinent pour un tableau distribue).
Entree & readOn (Entree &is) override
lecture d'un tableau sequentiel
Protected Member Functions inherited from TRUSTVect< _TYPE_ >
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &is) override
Lecture d'un vecteur sequentiel (comme un ArrOfDouble)
Attention: appel invalide si le vecteur a un MD_Vector non nul. (pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
void set_line_size_ (int n)
void resize_vect_ (int n, Array_base::Resize_Options opt=Array_base::COPY_INIT)
void copy_ (const TRUSTVect &v, Array_base::Resize_Options opt=Array_base::COPY_INIT)
Protected Member Functions inherited from TRUSTArray< _TYPE_ >
unsigned taille_memoire () const override
int duplique () const override
Sortie & printOn (Sortie &os) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &is) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void attach_array (const TRUSTArray &a, int start=0, int size=-1)
void fill_default_value (Array_base::Resize_Options opt, int first, int nb)
void resize_array_ (int n, Array_base::Resize_Options opt=COPY_INIT)
int detach_array ()
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
template<typename _TYPE_>
class TRUSTTabFT< _TYPE_ >
Definition at line 24 of file TRUSTTabFT.h.
Constructor & Destructor Documentation
TRUSTTabFT() [1/4]
template<typename _TYPE_ > TRUSTTabFT< _TYPE_ >::TRUSTTabFT () inline
Definition at line 28 of file TRUSTTabFT.h.
{ TRUSTTab<_TYPE_>::set_smart_resize(1);}
References TRUSTArray< _TYPE_ >::set_smart_resize().
TRUSTTabFT() [2/4]
template<typename _TYPE_ > TRUSTTabFT< _TYPE_ >::TRUSTTabFT (const TRUSTTabFT< _TYPE_ > &) default
TRUSTTabFT() [3/4]
template<typename _TYPE_ > TRUSTTabFT< _TYPE_ >::TRUSTTabFT (int i, int j) inline
Definition at line 32 of file TRUSTTabFT.h.
  {
    TRUSTTab<_TYPE_>::set_smart_resize(1);
    TRUSTTab<_TYPE_>::resize(i, j);
  }
References TRUSTTab< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::set_smart_resize().
TRUSTTabFT() [4/4]
template<typename _TYPE_ > TRUSTTabFT< _TYPE_ >::TRUSTTabFT (const TRUSTTab< _TYPE_ > & x) inline
Definition at line 38 of file TRUSTTabFT.h.
  {
    TRUSTTab<_TYPE_>::set_smart_resize(1);
    TRUSTTab<_TYPE_>::operator=(x);
  }
References TRUSTTab< _TYPE_ >::operator=(), and TRUSTArray< _TYPE_ >::set_smart_resize().
Member Function Documentation
operator=() [1/3]
template<typename _TYPE_ > TRUSTTabFT & TRUSTTabFT< _TYPE_ >::operator= (const double x) inline
Definition at line 56 of file TRUSTTabFT.h.
  {
    TRUSTTab<_TYPE_>::operator=(x);
    return *this;
  }
References TRUSTTab< _TYPE_ >::operator=().
operator=() [2/3]
template<typename _TYPE_ > TRUSTTabFT & TRUSTTabFT< _TYPE_ >::operator= (const TRUSTTab< _TYPE_ > & x) inline
Definition at line 44 of file TRUSTTabFT.h.
  {
    TRUSTTab<_TYPE_>::operator=(x);
    return *this;
  }
References TRUSTTab< _TYPE_ >::operator=().
operator=() [3/3]
template<typename _TYPE_ > TRUSTTabFT & TRUSTTabFT< _TYPE_ >::operator= (const TRUSTTabFT< _TYPE_ > & x) inline
Definition at line 50 of file TRUSTTabFT.h.
  {
    TRUSTTab<_TYPE_>::operator=(x);
    return *this;
  }
References TRUSTTab< _TYPE_ >::operator=().
The documentation for this class was generated from the following file:
src/Kernel/Math/TRUSTTabFT.h