TRUST: Lire_Ideas Class Reference
Lire_Ideas Class Reference
#include <Lire_Ideas.h>
Public Member Functions
Lire_Ideas ()
~Lire_Ideas ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Lire_Ideas & self_cast (Objet_U &)
static const Lire_Ideas & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Definition at line 131 of file Lire_Ideas.h.
Constructor & Destructor Documentation
Lire_Ideas()
Lire_Ideas::Lire_Ideas ()
Definition at line 21 of file Lire_Ideas.cpp.
~Lire_Ideas()
Lire_Ideas::~Lire_Ideas ()
Definition at line 21 of file Lire_Ideas.cpp.
Member Function Documentation
cree_instance()
Objet_U * Lire_Ideas::cree_instance () static
Definition at line 21 of file Lire_Ideas.cpp.
duplique()
int Lire_Ideas::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Lire_Ideas.cpp.
get_info()
const Type_info * Lire_Ideas::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 21 of file Lire_Ideas.cpp.
info()
const Type_info * Lire_Ideas::info () static
Definition at line 21 of file Lire_Ideas.cpp.
interpreter_()
Entree & Lire_Ideas::interpreter_ (Entree & is) override virtual
< Remplace UFichier
Implements Interprete_geometrique_base.
Definition at line 35 of file Lire_Ideas.cpp.
{
  Nom nom_fic;
  associer_domaine(is);
  is >> nom_fic;
  Domaine& dom=domaine();
//
  int NDIM=dimension;
  int NNOEUDS=0;
  int NELEM=0;
  int NTETRA=0;
  int NFACB=0;
  int NSEG=0;
  int NGROUPE=0;
  int CAS=0;
//
  Cerr << "First pass to determine the sizes of arrays" << finl;
//
  char  nom_fic2[81];
  for (int ii=0; ii<80; ii++)
    nom_fic2[ii]='\0';
  strcpy(nom_fic2,nom_fic);
  F77NAME(LIREPREM) (nom_fic2,
                     &NDIM,
                     &NNOEUDS,
                     &NELEM,
                     &NTETRA,
                     &NFACB,
                     &NSEG,
                     &NGROUPE,
                     &CAS);
//
  Cerr << "Number of nodes             : " << NNOEUDS << finl;
  Cerr << "Number of elements          : " << NELEM << finl;
  Cerr << "Number of tetrahedra        : " << NTETRA << finl;
  Cerr << "Number of boundary faces    : " << NFACB << finl;
  Cerr << "Number of boundary segments : " << NSEG << finl;
  Cerr << "Number of groups            : " << NGROUPE << finl;
//
  ArrOfInt NGELEM(NGROUPE);
  ArrOfInt WORK(std::max(NTETRA,NFACB*4));
//
// Passage F77 a C++: les indices entre les deux langages sont inverses
// (methode de stockage differente)
//
  IntTab TETRA(4,NTETRA);
  IntTab FACB(3,NFACB);
  IntTab GROUP(NFACB,NGROUPE);
//
  ArrOfDouble X(NNOEUDS);
  ArrOfDouble Y(NNOEUDS);
  ArrOfDouble Z(NNOEUDS);
  Cerr << "call of LIREIDEAS " << finl;
//
  F77NAME(LIREIDEAS)(nom_fic2,
                     &NDIM,
                     X.addr(),
                     Y.addr(),
                     Z.addr(),
                     TETRA.addr(),
                     FACB.addr(),
                     GROUP.addr(),
                     &NNOEUDS,
                     &NELEM,
                     &NTETRA,
                     &NFACB,
                     &NGROUPE,
                     NGELEM.addr(),
                     WORK.addr(),
                     &CAS);
//
  Cerr << " Reading completed " << finl;
//
  DoubleTab& coord=dom.les_sommets();
  Zone une_zone;
  Zone& la_zone=dom.add(une_zone);
//
  la_zone.nommer(dom.le_nom());
  la_zone.associer_domaine(dom);
  la_zone.type_elem().typer("Tetraedre");
  la_zone.type_elem().associer_zone(la_zone);
//
// On commence par transferer les coordonnees
//
  coord.resize(NNOEUDS, dimension);
  {
    for(int i=0; i<NNOEUDS; i++)
      {
        coord(i,0) = (X[i]);
        coord(i,1) = (Y[i]);
        coord(i,2) = (Z[i]);
      }
  }
//
  Cerr << " Completing the assignment of coordinates of nodes" << finl;
//
// On continue par les elements (connectivite element -> noeuds)
//
  IntTab& les_elems=la_zone.les_elems();
  les_elems.resize(NTETRA, dimension+1);
  for(int i=0; i<NTETRA; i++)
    {
      for(int j=0; j<dimension+1; j++)
        {
//
// ATTENTION : Inversion des indices entre le tableau Fortran et C++
//
          les_elems(i,j)= TETRA(j,i)-1 ;
        }
    }
//
  Cerr << " Completing the assignment of elements" << finl;
//
//
// Maintenant, on traite les faces de bords (tableau FACB, de dim (NFACB,3))
// qui se trouvent dans les differents groupes de faces de bords. Chaque
// groupe correspond a un bord bien defini du domaine (paroi, entree, sortie,
// symetrie, ...) et chaque groupe porte le nom de ce type de bord (GRNAME)
//
// En resume :
// GRNAME (NGROUPE)         : Nom des differents bords
// GROUP  (NNOEUDS,NGROUPE) : Groupe de faces de bord (Numero de la face)
// NGELEM (NGROUPE)         : Nombre de faces de bords pour le groupe NGROUPE
// FACB   (NFACB,3)         : Connectivite des faces de bords (les 3 noeuds du triangle)
//
//
//
// On ouvre le fichier contenant les noms des groupes
//
  Nom nom1="nom.groupe";
  EFichier fic(nom1);
  fic.set_check_types(1); //!< Remplace UFichier
  Cerr << "Reading of the file : " << nom1 << finl;
// On definit les bords comme etant des faces de bords de la zone
// On fait Zone --> les_bords
//
  Bords& les_bords=la_zone.faces_bord();
//
// Ici, on associe les bords a la zone (on se refere a la_zone)
// On fait les_bords --> Zone
//
  les_bords.associer_zone(la_zone);
//
  Nom nom_bord="Bord";
//
// On affecte les bords :
//
  for(int k=0; k<NGROUPE; k++)
    {
      fic >> nom_bord;
      Bord& nouveau=les_bords.add(Bord());
//
      nouveau.nommer(nom_bord);
      nouveau.faces().typer(Faces::triangle_3D);
//
      nouveau.faces().dimensionner(NGELEM[k]);
//
      int num;
      for (int j=0; j<NGELEM[k]; j++)
        {
//
// ATTENTION : Inversion des indices entre le tableau Fortran et C++
//
// GF renumerotation dans lire_ideas.f maintenant...
//
// num=GROUP(j,k)-1-NTETRA;
          num=GROUP(j,k)-1;
          nouveau.faces().sommet(j,0)= FACB(0,num)-1;
          nouveau.faces().sommet(j,1)= FACB(1,num)-1;
          nouveau.faces().sommet(j,2)= FACB(2,num)-1;
        }
      nouveau.associer_zone(la_zone);
    }
//
  Cerr << " Completing the assignment of the boundary faces" << finl;
//
  Cerr << " Exit of Lire_Ideas " << finl;
//
  la_zone.fixer_premieres_faces_frontiere();
  Scatter::init_sequential_domain(dom);
  return is;
}
References List_Bord::add(), Domaine::add(), TRUSTArray< _TYPE_ >::addr(), Zone::associer_domaine(), Interprete_geometrique_base::associer_domaine(), Bords::associer_zone(), Elem_geom::associer_zone(), Frontiere::associer_zone(), Cerr, Objet_U::dimension, Faces::dimensionner(), Interprete_geometrique_base::domaine(), F77NAME, Frontiere::faces(), Zone::faces_bord(), finl, Zone::fixer_premieres_faces_frontiere(), Scatter::init_sequential_domain(), Domaine::le_nom(), Zone::les_elems(), Domaine::les_sommets(), Frontiere::nommer(), Zone::nommer(), TRUSTTab< _TYPE_ >::resize(), Entree::set_check_types(), Faces::sommet(), Faces::triangle_3D, Zone::type_elem(), Deriv_::typer(), and Faces::typer().
printOn()
Sortie & Lire_Ideas::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 25 of file Lire_Ideas.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Lire_Ideas::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Interprete_geometrique_base.
Definition at line 30 of file Lire_Ideas.cpp.
{
  return is;
}
self_cast() [1/2]
const Lire_Ideas & Lire_Ideas::self_cast (const Objet_U & r) static
Definition at line 21 of file Lire_Ideas.cpp.
self_cast() [2/2]
Lire_Ideas & Lire_Ideas::self_cast (Objet_U & r) static
Definition at line 21 of file Lire_Ideas.cpp.
taille_memoire()
unsigned Lire_Ideas::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Lire_Ideas.cpp.
Member Data Documentation
info_obj
const Type_info Lire_Ideas::info_obj static
Definition at line 134 of file Lire_Ideas.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Lire_Ideas.h
src/Kernel/Geometrie/Lire_Ideas.cpp