TRUST: Catch_SIGINIT Class Reference
Catch_SIGINIT Class Reference
#include <Catch_SIGINIT.h>
Public Member Functions
void set_nom_cas_pour_signal (const Nom &cas)
Static Public Member Functions
static void signal_callback_handler (True_int signum)
Static Protected Attributes
static Nom NOM_DU_CAS_ = ""
static int NB_CAUGHT_SIGNALS_ =0
we give the user 2 tries before a forced exit !
Detailed Description
Definition at line 24 of file Catch_SIGINIT.h.
Member Function Documentation
set_nom_cas_pour_signal()
void Catch_SIGINIT::set_nom_cas_pour_signal (const Nom & cas) inline
Definition at line 28 of file Catch_SIGINIT.h.
{ NOM_DU_CAS_ = cas ; }
References NOM_DU_CAS_.
Referenced by ICoCo::ProblemTrio::initialize(), and Resoudre::interpreter().
signal_callback_handler()
void Catch_SIGINIT::signal_callback_handler (True_int signum) static
< force an exit
< force an exit when nb_caught_signals = 2 (3 tries)
Definition at line 21 of file Catch_SIGINIT.cpp.
{
  if (NB_CAUGHT_SIGNALS_ < 2)
    {
      if (Process::je_suis_maitre())
        {
          std::cerr << " " << std::endl;
          std::cerr << "=======================================================" << std::endl;
          std::cerr << " " << std::endl;
          std::cerr << "Caught signal " << signum << std::endl;
          std::cerr << "We are trying to finish the simulation correctly ... " << std::endl;
          std::cerr << " " << std::endl;
          std::cerr << "=======================================================" << std::endl;
          std::cerr << " " << std::endl;
        }
    }
  else //!< force an exit
    {
      if (Process::je_suis_maitre())
        {
          std::cerr << " " << std::endl;
          std::cerr << "=======================================================" << std::endl;
          std::cerr << " " << std::endl;
          std::cerr << "Multiple signals " << signum <<" are caught !" << std::endl;
          std::cerr << "We are forcing the exit of the processors ... " << std::endl;
          std::cerr << " " << std::endl;
          std::cerr << "=======================================================" << std::endl;
          std::cerr << " " << std::endl;
        }
      Process::exit();
    }
// Terminate TRUST correctly => print 1 in stop file
  Nom command = "echo '1' > ";
  command += NOM_DU_CAS_;
  command += ".stop";
  NB_CAUGHT_SIGNALS_++; //!< force an exit when nb_caught_signals = 2 (3 tries)
  int err = system(command);
  if (err)
    {
      if (Process::je_suis_maitre())
        std::cerr << "We can not finish the simulation correctly because the stop file " << NOM_DU_CAS_<<".stop is not in the directory !" << std::endl;
      Process::exit();
    }
}
References Process::exit(), Process::je_suis_maitre(), NB_CAUGHT_SIGNALS_, and NOM_DU_CAS_.
Referenced by ICoCo::ProblemTrio::initialize(), and Resoudre::interpreter().
Member Data Documentation
NB_CAUGHT_SIGNALS_
int Catch_SIGINIT::NB_CAUGHT_SIGNALS_ =0 static protected
we give the user 2 tries before a forced exit !
Definition at line 32 of file Catch_SIGINIT.h.
Referenced by signal_callback_handler().
NOM_DU_CAS_
Nom Catch_SIGINIT::NOM_DU_CAS_ = "" static protected
Definition at line 31 of file Catch_SIGINIT.h.
Referenced by set_nom_cas_pour_signal(), and signal_callback_handler().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Catch_SIGINIT.h
src/Kernel/Framework/Catch_SIGINIT.cpp