TRUST: Octree_Double Class Reference
Octree_Double Class Reference
: Un octree permettant de chercher dans l'espace des elements ou des points
decrits par des coordonnees reeles. Cet objet est base sur Octree_Int.
Astuces:
Pour chercher des points a epsilon pres on peut faire:
1) build_nodes(coord, include_virt, 0.)
suivi de
search_elements_box(center, epsilon, elements);
2) build_nodes(coord, include_virt, epsilon)
suivi de
search_elements(x,y,z,...)
La premiere solution prend plus de temps pour construire l'octree mais la recherche est plus rapide
La deuxieme, c'est inverse... et on peut choisir epsilon pour chaque point.
#include <Octree_Double.h>
Public Member Functions
Octree_Double ()
void reset ()
void build_elements (const DoubleTab &coords, const IntTab &elements, const double epsilon, const int include_virtual)
Construit un octree a partir d'elements volumiques decrits par des
ensembles de sommets. On stocke dans l'octree les parallelipipdes englobant chaque
element (contenant tous les sommets de l'element) plus une marge de epsilon.
Si include_virtual=1, on stocke elements.dimension_tot(0) elements, sinon on en
stocke elements.dimension(0)
void build_nodes (const DoubleTab &coords, const int include_virtual, const double epsilon=0.)
construit un octree contenant les points de coordonnees coords.
Si include_virtual=1, on stocke coords.dimension_tot(0) elements, sinon on en
stocke coords.dimension(0)
Si epsilon = 0, on construit un octree de points de taille nulle (chaque point
se trouve dans un seul octree_floor)
Sinon, on construit un octree d'elements cubiques centres sur les coords, de demie-largeur epsilon.
Un point peut alors se trouver dans plusieurs octree_floor.
int search_elements (double x, double y, double z, int &index) const
cherche les elements ou les points contenus dans l'octree_floor qui
contient le point (x,y,z). Renvoie le nombre n de ces elements.
Les indices des elements sont dans floor_elements()[index+i] pour 0 <= i < n
int search_elements_box (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, ArrOfInt &elements) const
cherche tous les elements ou points ayant potentiellement une intersection
non vide avec la boite donnee.
int search_elements_box (const ArrOfDouble &center, const double radius, ArrOfInt &elements) const
cherche tous les elements ou points ayant potentiellement une intersection
non vide avec la boite donnee (centre + ou - radius dans chaque direction)
int dimension () const
const ArrOfInt & floor_elements () const
Static Public Member Functions
static int search_nodes_close_to (double x, double y, double z, const DoubleTab &coords, ArrOfInt &node_list, double epsilon)
Methode hors classe
Cherche parmi les sommets de la liste node_list ceux qui sont a une
distance inferieure a epsilon du point (x,y,z). node_list contient des indices de
sommets dans le tableau coords. La liste des noeuds verifiant le critere est mise
dans node_list. On renvoie l'indice dans le tableau coords du sommet le plus proche.
static int search_nodes_close_to (const ArrOfDouble &point, const DoubleTab &coords, ArrOfInt &node_list, double epsilon)
Idem que search_nodes_close_to(double x, double y, double z, ...)
Protected Member Functions
int integer_position (double x, int direction, int &ix) const
Convertit une coordonnees reele en coordonnee entiere pour l'octree_int
Valeur de retour: 1 si ok, 0 si coordonnee hors de l'octree.
int integer_position_clip (double xmin, double xmax, int &x0, int &x1, int direction) const
void compute_origin_factors (const DoubleTab &coords, const double epsilon, const int include_virtual)
methode outil pour build_nodes et build_elements
(calcul des facteurs de conversion entre reels et entiers pour Octree_Int
epsilon est ajoute aux coordonnees min et max pour la bounding box de l'octree.
Protected Attributes
Octree_Int octree_int_
ArrOfDouble origin_
ArrOfDouble factor_
int dim_
Detailed Description
: Un octree permettant de chercher dans l'espace des elements ou des points
decrits par des coordonnees reeles. Cet objet est base sur Octree_Int.
Astuces:
Pour chercher des points a epsilon pres on peut faire:
1) build_nodes(coord, include_virt, 0.)
suivi de
search_elements_box(center, epsilon, elements);
2) build_nodes(coord, include_virt, epsilon)
suivi de
search_elements(x,y,z,...)
La premiere solution prend plus de temps pour construire l'octree mais la recherche est plus rapide
La deuxieme, c'est inverse... et on peut choisir epsilon pour chaque point.
Definition at line 35 of file Octree_Double.h.
Constructor & Destructor Documentation
Octree_Double()
Octree_Double::Octree_Double ()
Definition at line 18 of file Octree_Double.cpp.
{
  dim_ = 0;
}
References dim_.
Member Function Documentation
build_elements()
void Octree_Double::build_elements (const DoubleTab & coords, const IntTab & elements, const double epsilon, const int include_virtual)
Construit un octree a partir d'elements volumiques decrits par des
ensembles de sommets. On stocke dans l'octree les parallelipipdes englobant chaque
element (contenant tous les sommets de l'element) plus une marge de epsilon.
Si include_virtual=1, on stocke elements.dimension_tot(0) elements, sinon on en
stocke elements.dimension(0)
Definition at line 198 of file Octree_Double.cpp.
{
  octree_int_.reset();
  compute_origin_factors(coords, epsilon, include_virtual);
  const int nb_elems = include_virtual ? elements.dimension_tot(0) : elements.dimension(0);
  const int nb_som_elem = elements.dimension(1);
  const int dim = coords.dimension(1);
  IntTab elements_boxes;
  elements_boxes.resize(nb_elems, dim * 2, ArrOfInt::NOCOPY_NOINIT);
  for (int i = 0; i < nb_elems; i++)
    {
      for (int j = 0; j < dim; j++)
        {
          double xmin = 1.e37;
          double xmax = -1.e37;
          for (int k = 0; k < nb_som_elem; k++)
            {
              const int som = elements(i, k);
              const double x = coords(som, j);
              xmin = (x<xmin) ? x : xmin;
              xmax = (x>xmax) ? x : xmax;
            }
          int pos1 = 0, pos2 = 0;
          if (!integer_position(xmin, j, pos1) || !integer_position(xmax, j, pos2))
            {
              Cerr << "Fatal error in octree : integer position outside octree" << finl;
              Process::exit();
            }
          elements_boxes(i, j) = pos1;
          elements_boxes(i, j+dim) = pos2;
        }
    }
  octree_int_.build(dim, elements_boxes);
}
References Octree_Int::build(), Cerr, compute_origin_factors(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), finl, integer_position(), Array_base::NOCOPY_NOINIT, octree_int_, Octree_Int::reset(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Octree_Zone::build().
build_nodes()
void Octree_Double::build_nodes (const DoubleTab & coords, const int include_virtual, const double epsilon = 0.)
construit un octree contenant les points de coordonnees coords.
Si include_virtual=1, on stocke coords.dimension_tot(0) elements, sinon on en
stocke coords.dimension(0)
Si epsilon = 0, on construit un octree de points de taille nulle (chaque point
se trouve dans un seul octree_floor)
Sinon, on construit un octree d'elements cubiques centres sur les coords, de demie-largeur epsilon.
Un point peut alors se trouver dans plusieurs octree_floor.
< octree vide
Definition at line 147 of file Octree_Double.cpp.
{
  octree_int_.reset();
  compute_origin_factors(coords, epsilon, include_virtual);
  const int nb_som = include_virtual ? coords.dimension_tot(0) : coords.dimension(0);
  if (nb_som == 0)
    return; //!< octree vide
  const int dim = coords.dimension(1);
  if (epsilon < 0.)
    {
      Cerr << "Internal error in Octree_Double::build_nodes: negative epsilon" << finl;
      Process::exit();
    }
  int have_epsilon = (epsilon == 0.) ? 0 : 1;
  IntTab elements_boxes;
  elements_boxes.resize(nb_som, have_epsilon ? (dim*2) : dim, ArrOfInt::NOCOPY_NOINIT);
  for (int i = 0; i < nb_som; i++)
    {
      for (int j = 0; j < dim; j++)
        {
          int pos1 = 0;
          const double x0 = coords(i, j);
          double x = x0 - epsilon;
          if (!integer_position(x, j, pos1))
            {
              Cerr << "Fatal error in octree : integer position outside octree" << finl;
              Process::exit();
            }
          elements_boxes(i, j) = pos1;
          if (have_epsilon)
            {
              pos1 = 0;
              double xbis = x0 + epsilon;
              if (!integer_position(xbis, j, pos1))
                {
                  Cerr << "Fatal error in octree : integer position outside octree" << finl;
                  Process::exit();
                }
              elements_boxes(i, dim+j) = pos1;
            }
        }
    }
  octree_int_.build(dim, elements_boxes);
}
References Octree_Int::build(), Cerr, compute_origin_factors(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), Process::exit(), finl, integer_position(), Array_base::NOCOPY_NOINIT, octree_int_, Octree_Int::reset(), and TRUSTTab< _TYPE_ >::resize().
Referenced by Debog_Pb::add_renum_item(), Domaine::ajouter(), Calcul_integrale_locale::Calcul_integrale_locale(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), find_matching_coordinates(), Champ_implementation_P1::init_from_file(), Redresser_hexaedres_vdf::interpreter_(), Zone_VEF_PreP1b::lecture_ok_arete(), lire_special(), and Reordonner_faces_periodiques::reordonner_faces_periodiques().
compute_origin_factors()
void Octree_Double::compute_origin_factors (const DoubleTab & coords, const double epsilon, const int include_virtual) protected
methode outil pour build_nodes et build_elements
(calcul des facteurs de conversion entre reels et entiers pour Octree_Int
epsilon est ajoute aux coordonnees min et max pour la bounding box de l'octree.
< octree vide
Definition at line 95 of file Octree_Double.cpp.
{
// Recherche des coordonnees min et max du domaine
  const int nb_som = include_virtual ? coords.dimension_tot(0) : coords.dimension(0);
  if (nb_som == 0)
    return; //!< octree vide
  const int dim = coords.dimension(1);
  dim_ = dim;
  origin_.resize_array(3);
  factor_.resize_array(3);
  ArrOfDouble xmin(dim);
  xmin= 1.e37;
  ArrOfDouble xmax(dim);
  xmax= -1.e-37;
  assert(dim >= 1 && dim <= 3);
  int i, j;
  for (i = 0; i < nb_som; i++)
    {
      for (j = 0; j < dim; j++)
        {
          const double x = coords(i, j);
          if (x < xmin[j])
            xmin[j] = x;
          if (x > xmax[j])
            xmax[j] = x;
        }
    }
  const double coord_max = (double) Octree_Int::coord_max_;
  for (j = 0; j < dim; j++)
    {
      xmin[j] -= epsilon;
      xmax[j] += epsilon;
      origin_[j] = xmin[j];
      if (xmax[j] - xmin[j] > 0.)
        {
          factor_[j] = coord_max / (xmax[j] - xmin[j]);
        }
      else
        factor_[j] = 0.;
    }
}
References Octree_Int::coord_max_, dim_, TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), factor_, origin_, and TRUSTArray< _TYPE_ >::resize_array().
Referenced by build_elements(), and build_nodes().
dimension()
int Octree_Double::dimension () const inline
Definition at line 47 of file Octree_Double.h.
  {
    assert(dim_ > 0);
    return dim_;
  }
References dim_.
floor_elements()
const ArrOfInt & Octree_Double::floor_elements () const inline
Definition at line 52 of file Octree_Double.h.
{ return octree_int_.floor_elements(); }
References Octree_Int::floor_elements(), and octree_int_.
Referenced by Octree_Zone::find_elements(), and lire_special().
integer_position()
int Octree_Double::integer_position (double x, int direction, int & ix) const inline protected
Convertit une coordonnees reele en coordonnee entiere pour l'octree_int
Valeur de retour: 1 si ok, 0 si coordonnee hors de l'octree.
Definition at line 33 of file Octree_Double.cpp.
{
  const double coord_max = (double) Octree_Int::coord_max_;
  double rnd_x = (x - origin_[direction]) * factor_[direction];
// 0.49 permet d'accepter une coordonnee x egale a xmin ou xmax de l'octree,
// sinon pour un octree cree a partir de sommets, il y a un risque
// de ne pas trouver les coordonnees des points qu'on avait mis au bord de l'octree.
  if (rnd_x >= -0.49 && rnd_x <= coord_max + 0.49)
    {
      ix = (int) floor(rnd_x + 0.5);
      return 1;
    }
  return 0;
}
References Octree_Int::coord_max_, factor_, and origin_.
Referenced by build_elements(), build_nodes(), and search_elements().
integer_position_clip()
int Octree_Double::integer_position_clip (double xmin, double xmax, int & x0, int & x1, int direction) const inline protected
Definition at line 49 of file Octree_Double.cpp.
{
  const double coord_max = (double) Octree_Int::coord_max_;
  xmin = (xmin - origin_[direction]) * factor_[direction];
  xmax = (xmax - origin_[direction]) * factor_[direction];
// pas de marge ici comme on cherche avec une boite, l'epsilon est deja
// dans la dimension de la boite.
  if (xmin > coord_max || xmax < 0.)
    return 0;
  if (xmin < .0)
    x0 = 0;
  else
    x0 = (int) (floor(xmin+0.5));
  if (xmax > coord_max)
    x1 = Octree_Int::coord_max_;
  else
    x1 = (int) (floor(xmax+0.5));
  return 1;
}
References Octree_Int::coord_max_, factor_, and origin_.
Referenced by search_elements_box().
reset()
void Octree_Double::reset ()
Definition at line 23 of file Octree_Double.cpp.
{
  dim_ = 0;
  octree_int_.reset();
  origin_.reset();
  factor_.reset();
}
References dim_, factor_, octree_int_, origin_, Octree_Int::reset(), and TRUSTArray< _TYPE_ >::reset().
Referenced by Octree_Zone::reset().
search_elements()
int Octree_Double::search_elements (double x, double y, double z, int & index) const
cherche les elements ou les points contenus dans l'octree_floor qui
contient le point (x,y,z). Renvoie le nombre n de ces elements.
Les indices des elements sont dans floor_elements()[index+i] pour 0 <= i < n
< octree vide
Definition at line 74 of file Octree_Double.cpp.
{
  if (dim_ == 0)
    return 0; //!< octree vide
  int ix = 0, iy = 0, iz = 0;
  int ok = integer_position(x, 0, ix)
           && integer_position(y, 1, iy)
           && integer_position(z, 2, iz);
  if (ok)
    {
      return octree_int_.search_elements(ix, iy, iz, index);
    }
  else
    {
      return 0;
    }
}
References dim_, integer_position(), octree_int_, and Octree_Int::search_elements().
Referenced by Octree_Zone::find_elements(), and lire_special().
search_elements_box() [1/2]
int Octree_Double::search_elements_box (const ArrOfDouble & center, const double radius, ArrOfInt & elements) const
cherche tous les elements ou points ayant potentiellement une intersection
non vide avec la boite donnee (centre + ou - radius dans chaque direction)
Definition at line 264 of file Octree_Double.cpp.
{
  int dim = center.size_array();
  double x = center[0];
  double y = (dim>=2) ? center[1] : 0.;
  double z = (dim>2) ? center[2] : 0.;
  int i = search_elements_box(x-radius, y-radius, z-radius,
                              x+radius, y+radius, z+radius,
                              elements);
  return i;
}
References search_elements_box(), and TRUSTArray< _TYPE_ >::size_array().
search_elements_box() [2/2]
int Octree_Double::search_elements_box (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, ArrOfInt & elements) const
cherche tous les elements ou points ayant potentiellement une intersection
non vide avec la boite donnee.
Definition at line 237 of file Octree_Double.cpp.
{
  const int dim = dim_;
  if (dim == 0)
    {
      elements.resize_array(0);
      return 0;
    }
  int x0 = 0, x1 = 0, y0 = 0, y1 = 0, z0 = 0, z1 = 0;
  int ok = integer_position_clip(xmin, xmax, x0, x1, 0);
  if ((ok) && (dim >= 1))
    {
      ok = integer_position_clip(ymin, ymax, y0, y1, 1);
      if ((ok) && (dim >= 2))
        ok = integer_position_clip(zmin, zmax, z0, z1, 2);
    }
  if (ok)
    octree_int_.search_elements_box(x0, y0, z0, x1, y1, z1, elements);
  else
    elements.resize_array(0);
  return elements.size_array();
}
References dim_, integer_position_clip(), octree_int_, TRUSTArray< _TYPE_ >::resize_array(), Octree_Int::search_elements_box(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Debog_Pb::add_renum_item(), Domaine::ajouter(), Calcul_integrale_locale::calculer(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), find_matching_coordinates(), Champ_implementation_P1::init_from_file(), Redresser_hexaedres_vdf::interpreter_(), Zone_VEF_PreP1b::lecture_ok_arete(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), and search_elements_box().
search_nodes_close_to() [1/2]
int Octree_Double::search_nodes_close_to (const ArrOfDouble & point, const DoubleTab & coords, ArrOfInt & node_list, double epsilon) static
Idem que search_nodes_close_to(double x, double y, double z, ...)
Definition at line 315 of file Octree_Double.cpp.
{
  int dim = point.size_array();
  double x = point[0];
  double y = (dim>=2) ? point[1] : 0.;
  double z = (dim>2) ? point[2] : 0.;
  int i = search_nodes_close_to(x, y, z, coords, node_list, epsilon);
  return i;
}
References search_nodes_close_to(), and TRUSTArray< _TYPE_ >::size_array().
search_nodes_close_to() [2/2]
int Octree_Double::search_nodes_close_to (double x, double y, double z, const DoubleTab & coords, ArrOfInt & node_list, double epsilon) static
Methode hors classe
Cherche parmi les sommets de la liste node_list ceux qui sont a une
distance inferieure a epsilon du point (x,y,z). node_list contient des indices de
sommets dans le tableau coords. La liste des noeuds verifiant le critere est mise
dans node_list. On renvoie l'indice dans le tableau coords du sommet le plus proche.
Definition at line 282 of file Octree_Double.cpp.
{
  const int n = node_list.size_array();
  double eps2 = epsilon * epsilon;
  int count = 0;
  const int dim = coords.dimension(1);
  double dmin = eps2;
  int nearest = -1;
  for (int i = 0; i < n; i++)
    {
      const int som = node_list[i];
      double dx = x - coords(som, 0);
      double dy = (dim >= 2) ? y - coords(som, 1) : 0.;
      double dz = (dim >= 3) ? z - coords(som, 2) : 0.;
      double d2 = dx * dx + dy * dy + dz * dz;
      if (d2 < eps2)
        {
          node_list[count] = som;
          if (d2 < dmin)
            {
              dmin = d2;
              nearest = som;
            }
          count++;
        }
    }
  node_list.resize_array(count);
  return nearest;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTArray< _TYPE_ >::resize_array(), and TRUSTArray< _TYPE_ >::size_array().
Referenced by Debog_Pb::add_renum_item(), Domaine::ajouter(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), find_matching_coordinates(), Champ_implementation_P1::init_from_file(), Zone_VEF_PreP1b::lecture_ok_arete(), lire_special(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), and search_nodes_close_to().
Member Data Documentation
dim_
int Octree_Double::dim_ protected
Definition at line 61 of file Octree_Double.h.
Referenced by compute_origin_factors(), dimension(), Octree_Double(), reset(), search_elements(), and search_elements_box().
factor_
ArrOfDouble Octree_Double::factor_ protected
Definition at line 60 of file Octree_Double.h.
Referenced by compute_origin_factors(), integer_position(), integer_position_clip(), and reset().
octree_int_
Octree_Int Octree_Double::octree_int_ protected
Definition at line 58 of file Octree_Double.h.
Referenced by build_elements(), build_nodes(), floor_elements(), reset(), search_elements(), and search_elements_box().
origin_
ArrOfDouble Octree_Double::origin_ protected
Definition at line 60 of file Octree_Double.h.
Referenced by compute_origin_factors(), integer_position(), integer_position_clip(), and reset().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Octree_Double.h
src/Kernel/Geometrie/Octree_Double.cpp