TRUST: Pb_Dilatable_base Class Reference
Pb_Dilatable_base Class Reference
classe Pb_Dilatable_base
Cette classe est censee factoriser ce qui est commun a l'ensemble
des problemes dilatables.
.SECTION voir Pb_Fluide_base
#include <Pb_Dilatable_base.h>
Public Member Functions
Pb_Dilatable_base ()
~Pb_Dilatable_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual bool initTimeStep (double dt)
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
virtual void preparer_calcul ()
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
virtual void mettre_a_jour (double temps)
Ne met a jour que les postraitements.
virtual void associer_milieu_base (const Milieu_base &)
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
virtual void associer_sch_tps_base (const Schema_Temps_base &)
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
virtual void update_pressure_fields (double)
virtual bool iterateTimeStep (bool &converged)
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
virtual void solve_pressure_thermo ()=0
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Pb_Dilatable_base & self_cast (Objet_U &)
static const Pb_Dilatable_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
virtual Entree & readOn (Entree &)
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Protected Attributes
Ref_Fluide_Dilatable_base le_fluide_
Detailed Description
classe Pb_Dilatable_base
Cette classe est censee factoriser ce qui est commun a l'ensemble
des problemes dilatables.
.SECTION voir Pb_Fluide_base
Definition at line 42 of file Pb_Dilatable_base.h.
Constructor & Destructor Documentation
Pb_Dilatable_base::Pb_Dilatable_base ()
Definition at line 37 of file Pb_Dilatable_base.cpp.
Pb_Dilatable_base::~Pb_Dilatable_base ()
Definition at line 37 of file Pb_Dilatable_base.cpp.
Member Function Documentation
void Pb_Dilatable_base::associer_milieu_base (const Milieu_base & mil) [virtual]
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_QC_base, and Pb_WC_base.
Definition at line 43 of file Pb_Dilatable_base.cpp.
References le_fluide_, and ref_cast.
{
  Pb_Fluide_base::associer_milieu_base(mil);
  le_fluide_ =  ref_cast(Fluide_Dilatable_base,mil);
}
void Pb_Dilatable_base::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) [virtual]
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes
les equations du probleme.
Reimplemented from Probleme_base.
Definition at line 49 of file Pb_Dilatable_base.cpp.
References Cerr, Probleme_base::coupled_, Process::exit(), finl, Objet_U::que_suis_je(), and sub_type.
{
  if (!sub_type(Schema_Euler_explicite,sch) && !sub_type(Schema_Euler_Implicite,sch)
      && !sub_type(RRK2,sch) && !sub_type(RK3,sch))
    {
      Cerr << "TRUST can't solve a " << que_suis_je() << " with a " << sch.que_suis_je() << " time scheme." << finl;
      Process::exit();
    }
  if ( sub_type(Schema_Euler_Implicite,sch) && coupled_==1 )
    {
      Cerr << finl;
      Cerr << "Coupled problem with unique Euler implicit time scheme with " << que_suis_je() <<  "fluid are not allowed!" << finl;
      Cerr << "Choose another time scheme or set a time scheme for each of your problems." << finl;
      Process::exit();
    }
  Pb_Fluide_base::associer_sch_tps_base(sch);
}
virtual int Pb_Dilatable_base::duplique () const [pure virtual]
Implements Pb_Fluide_base.
Implemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
const Type_info * Pb_Dilatable_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 37 of file Pb_Dilatable_base.cpp.
const Type_info * Pb_Dilatable_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 37 of file Pb_Dilatable_base.cpp.
bool Pb_Dilatable_base::initTimeStep (double dt) [virtual]
This method allocates and initializes the unknown and given fields
for the future time step.
The value of the interval is imposed through the parameter dt.
In case of error, returns false.
Returns:
bool
Signification: true=OK, false=error, not able to tackle this dt
Contraintes:
Reimplemented from Probleme_base.
Definition at line 80 of file Pb_Dilatable_base.cpp.
References le_fluide_.
{
  bool ok = Pb_Fluide_base::initTimeStep(dt);
  le_fluide_->preparer_pas_temps();
  return ok;
}
bool Pb_Dilatable_base::iterateTimeStep (bool & converged) [virtual]
In the case solveTimeStep uses an iterative process,
this method executes a single iteration.
It is thus possible to modify the given fields between iterations.
converged is set to true if the process has converged, ie if the
unknown fields are solution to the problem on the next time step.
Otherwise converged is set to false.
The return value indicates if the convergence process behaves normally.
If false, the Problem wishes to abort the time step resolution.
Returns:
bool
Signification: true=OK, false=unable to converge
Contraintes:
Reimplemented from Probleme_base.
Definition at line 107 of file Pb_Dilatable_base.cpp.
References Statistiques::begin_count(), Statistiques::end_count(), Probleme_base::equation(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), Equation_base::inconnue(), le_fluide_, Probleme_base::le_nom(), Champ_Inc::mettre_a_jour(), Milieu_base::mettre_a_jour(), mettre_a_jour_counter_, Equation_base::milieu(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pas_de_temps(), Champ_Inc::reculer(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), solve_pressure_thermo(), statistiques(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_defaut(), update_pressure_fields(), and Equation_base::zone_Cl_dis().
{
  Debog::set_nom_pb_actuel(le_nom());
  Schema_Temps_base& sch=schema_temps();
  double temps_present=sch.temps_courant();
  double temps_futur=temps_present+sch.pas_de_temps();
// 1. Solve all the equations except the first one (Navier Stokes, solved later at //6)
  for (int i=1; i<nombre_d_equations(); i++)
    {
      sch.faire_un_pas_de_temps_eqn_base(equation(i));
      statistiques().begin_count(mettre_a_jour_counter_);
      equation(i).milieu().mettre_a_jour(temps_futur);
      equation(i).inconnue().mettre_a_jour(temps_futur);
      statistiques().end_count(mettre_a_jour_counter_);
    }
  statistiques().begin_count(mettre_a_jour_counter_);
// 2. Compute temperature-dependent coefficients
  le_fluide_->calculer_coeff_T();
// 3. Compute volumic mass (update Cp)
  le_fluide_->calculer_masse_volumique();
// 4. Solve EDO equation (pressure) if needed (ie. QC)
  solve_pressure_thermo();
// 5. Compute volumic mass
  le_fluide_->calculer_masse_volumique();
  statistiques().end_count(mettre_a_jour_counter_);
// 6. Solve Navier Stokes equation
  sch.faire_un_pas_de_temps_eqn_base(equation(0));
  statistiques().begin_count(mettre_a_jour_counter_);
  equation(0).milieu().mettre_a_jour(temps_futur);
  equation(0).inconnue().mettre_a_jour(temps_futur);
  statistiques().end_count(mettre_a_jour_counter_);
// Update pressure fields (total/thermo/hydro) if necessary
  update_pressure_fields(temps_futur);
// on recule les inconnues (le pb mettra a jour les equations)
  for (int i=0; i<nombre_d_equations(); i++)
    equation(i).inconnue().reculer();
// Calculs coeffs echange sur l'instant sur lequel doivent agir les operateurs.
  double tps=schema_temps().temps_defaut();
  for(int i=0; i<nombre_d_equations(); i++)
    equation(i).zone_Cl_dis()->calculer_coeffs_echange(tps);
  converged=true;
  return true;
}
void Pb_Dilatable_base::mettre_a_jour (double temps) [virtual]
Ne met a jour que les postraitements.
< thermique
< NS
< if species ...
Reimplemented from Probleme_base.
Definition at line 87 of file Pb_Dilatable_base.cpp.
References Probleme_base::domaine(), Probleme_base::domaine_dis(), Probleme_base::equation(), Probleme_base::le_nom(), Probleme_base::les_postraitements, LIST_CURSEUR, Probleme_base::liste_loi_fermeture_, Loi_Fermeture_base::mettre_a_jour(), Domaine::mettre_a_jour(), Postraitements::mettre_a_jour(), Equation_base::mettre_a_jour(), Probleme_base::nombre_d_equations(), REF, and Debog::set_nom_pb_actuel().
{
  Debog::set_nom_pb_actuel(le_nom());
  equation(1).mettre_a_jour(temps); //!< thermique
  equation(0).mettre_a_jour(temps); //!< NS
  for(int i=2; i<nombre_d_equations(); i++) //!< if species ...
    equation(i).mettre_a_jour(temps);
  les_postraitements.mettre_a_jour(temps);
  domaine().mettre_a_jour(temps,domaine_dis(),*this);
  LIST_CURSEUR(REF(Loi_Fermeture_base)) curseur = liste_loi_fermeture_;
  while (curseur)
    {
      Loi_Fermeture_base& loi=curseur.valeur().valeur();
      loi.mettre_a_jour(temps);
      ++curseur;
    }
}
void Pb_Dilatable_base::preparer_calcul (void) [virtual]
Prepare le calcul: initialise les parametres du milieu et
prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
Definition at line 67 of file Pb_Dilatable_base.cpp.
References Fluide_Dilatable_base::calculer_masse_volumique(), Fluide_Dilatable_base::completer(), Probleme_base::equation(), Equation_base::inconnue(), Probleme_base::milieu(), Objet_U::nommer(), Fluide_Dilatable_base::preparer_calcul(), ref_cast, and Fluide_Dilatable_base::type_fluide().
{
  Fluide_Dilatable_base& le_fluide = ref_cast(Fluide_Dilatable_base,milieu());
  if (le_fluide.type_fluide()=="Gaz_Reel") equation(1).inconnue()->nommer("temperature");
  if (le_fluide.type_fluide()=="Melange_Binaire") equation(1).inconnue()->nommer("fraction_massique");
  le_fluide.completer(*this);
  le_fluide.preparer_calcul();
  Pb_Fluide_base::preparer_calcul();
  le_fluide.calculer_masse_volumique();
  le_fluide.preparer_calcul();
}
Sortie & Pb_Dilatable_base::printOn (Sortie & os) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture d'un probleme sur un flot de sortie.
!! Attention n'est pas symetrique de la lecture !!
On ecrit les equations, le postraitement et le domaine
discretise.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 39 of file Pb_Dilatable_base.cpp.
{ return Pb_Fluide_base::printOn(os); }
Entree & Pb_Dilatable_base::readOn (Entree & is) [protected, virtual]
Lecture d'un probleme dans un flot d'entree, et ouverture du
flot de sauvegarde.
Format:
{
nom_equation bloc de lecture d'une equation
Postraitement bloc de lecture postraitement
reprise | sauvegarde | sauvegarde_simple
formatte | binaire
nom_de_fichier
}
L'option sauvegarde_simple permet de sauver le probleme dans le fichier choisi
en ecrasant a chaque fois les sauvegardes precedentes : cela permet d'economiser de la place disque.
Returns:
Entree&
Signification: le flot d'entre modifie
Contraintes:
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 41 of file Pb_Dilatable_base.cpp.
{ return Pb_Fluide_base::readOn(is); }
Pb_Dilatable_base & Pb_Dilatable_base::self_cast (Objet_U & r) [static]
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 37 of file Pb_Dilatable_base.cpp.
const Pb_Dilatable_base & Pb_Dilatable_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 37 of file Pb_Dilatable_base.cpp.
virtual void Pb_Dilatable_base::solve_pressure_thermo () [pure virtual]
Implemented in Pb_QC_base, and Pb_WC_base.
Referenced by iterateTimeStep().
void Pb_Dilatable_base::update_pressure_fields (double t) [virtual]
Definition at line 162 of file Pb_Dilatable_base.cpp.
References le_fluide_.
Referenced by iterateTimeStep().
{
  le_fluide_->update_pressure_fields(t);
}
Member Data Documentation
const Type_info Pb_Dilatable_base::info_obj [static]
Reimplemented from Pb_Fluide_base.
Reimplemented in Pb_Thermohydraulique_Especes_QC, Pb_Thermohydraulique_Especes_WC, Pb_Hydraulique_Melange_Binaire_QC, Pb_QC_base, Pb_Thermohydraulique_QC, Pb_Hydraulique_Melange_Binaire_WC, Pb_Thermohydraulique_WC, and Pb_WC_base.
Definition at line 44 of file Pb_Dilatable_base.h.
Ref_Fluide_Dilatable_base Pb_Dilatable_base::le_fluide_ [protected]
Definition at line 57 of file Pb_Dilatable_base.h.
Referenced by associer_milieu_base(), initTimeStep(), iterateTimeStep(), Pb_QC_base::solve_pressure_thermo(), and update_pressure_fields().
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Common/Problems/Pb_Dilatable_base.h
src/ThHyd/Dilatable/Common/Problems/Pb_Dilatable_base.cpp