TRUST: Interprete_geometrique_base Class Reference
Interprete_geometrique_base Class Reference abstract
classe Interprete_geometrique_base
.
#include <Interprete_geometrique_base.h>
Public Member Functions
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
classe Interprete_geometrique_base
.
Definition at line 47 of file Interprete_geometrique_base.h.
Constructor & Destructor Documentation
Interprete_geometrique_base()
Interprete_geometrique_base::Interprete_geometrique_base ()
Definition at line 21 of file Interprete_geometrique_base.cpp.
~Interprete_geometrique_base()
Interprete_geometrique_base::~Interprete_geometrique_base () override
Definition at line 21 of file Interprete_geometrique_base.cpp.
Member Function Documentation
associer_domaine() [1/2]
void Interprete_geometrique_base::associer_domaine (Entree & is)
Definition at line 43 of file Interprete_geometrique_base.cpp.
{
  Cerr << "Association of the domain on which the interpreter applies " << que_suis_je() << finl;
  Nom nom_dom;
  is >> nom_dom;
  if(!sub_type(Domaine, objet(nom_dom)))
    {
      Cerr << nom_dom << " is of type " << objet(nom_dom).que_suis_je() << finl;
      Cerr << "we know to treat only one domain with the interpreter " << que_suis_je() << finl;
      exit();
    }
  domains_.add(ref_cast(Domaine, objet(nom_dom)));
}
References List_Ref_Domaine::add(), Cerr, domains_, Process::exit(), finl, Interprete::objet(), Objet_U::que_suis_je(), ref_cast, and sub_type.
associer_domaine() [2/2]
void Interprete_geometrique_base::associer_domaine (Nom & nom_dom)
Definition at line 37 of file Interprete_geometrique_base.cpp.
{
  EChaine is(nom_dom);
  associer_domaine(is);
}
References associer_domaine().
Referenced by associer_domaine(), Calculer_Moments::interpreter_(), Create_domain_from_sous_zone::interpreter_(), DecoupeBord::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), Modif_bord_to_raccord::interpreter_(), NettoieNoeuds::interpreter_(), OrienteFacesBord::interpreter_(), Polyedriser::interpreter_(), Postraiter_domaine::interpreter_(), Raffiner_anisotrope::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), RegroupeBord::interpreter_(), Remove_elem::interpreter_(), Reordonner::interpreter_(), Reorienter_tetraedres::interpreter_(), Reorienter_triangles::interpreter_(), Rotation::interpreter_(), SupprimeBord::interpreter_(), Transformer::interpreter_(), Triangulation_base::interpreter_(), TroisDto2D::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Orienter_Simplexes::interpreter_(), Raffiner_Simplexes::interpreter_(), Rectify_Mesh::interpreter_(), Refine_Mesh::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Verifier_Qualite_Raffinements::interpreter_(), Verifier_Simplexes::interpreter_(), and Postraiter_domaine::lire_motcle_non_standard().
domaine() [1/2]
Domaine & Interprete_geometrique_base::domaine (int i = 0) inline
Definition at line 57 of file Interprete_geometrique_base.h.
  {
    return domains_(i).valeur();
  };
References domains_, and List_Ref_Domaine::valeur().
Referenced by Rectify_Mesh::apply(), Refine_Mesh::apply(), Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Refine_Mesh::build_edges(), Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Refine_Mesh::build_new_sub_zones_descriptions(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_cell_type(), Rectify_Mesh::check_nb_zones(), Refine_Mesh::check_nb_zones(), Remove_elem::creer_faces(), Postraiter_domaine::ecrire(), ExtrudeBord::extruder_bord(), ExtrudeBord::extruder_hexa_old(), interpreter(), Calculer_Moments::interpreter_(), Create_domain_from_sous_zone::interpreter_(), DecoupeBord::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), Modif_bord_to_raccord::interpreter_(), NettoieNoeuds::interpreter_(), OrienteFacesBord::interpreter_(), Polyedriser::interpreter_(), Raffiner_anisotrope::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), RegroupeBord::interpreter_(), Remove_elem::interpreter_(), Reordonner::interpreter_(), Reorienter_tetraedres::interpreter_(), Reorienter_triangles::interpreter_(), SupprimeBord::interpreter_(), Triangulation_base::interpreter_(), TroisDto2D::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Orienter_Simplexes::interpreter_(), Raffiner_Simplexes::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Verifier_Simplexes::interpreter_(), Remove_elem::Remove_elem_(), Reordonner_faces_periodiques::renum_som_perio(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), Transformer::transformation_complete(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_cells(), Refine_Mesh::update_connector_faces(), Refine_Mesh::update_internal_frontier_faces(), Refine_Mesh::update_nodes(), Refine_Mesh::update_octree(), Refine_Mesh::update_sub_zones(), Transformer::verifie_type_elem(), and Verifier_Qualite_Raffinements::verifier_qualite_raffinements().
domaine() [2/2]
const Domaine & Interprete_geometrique_base::domaine (int i = 0) const inline
Definition at line 61 of file Interprete_geometrique_base.h.
  {
    return domains_(i).valeur();
  };
References domains_, and List_Ref_Domaine::valeur().
domaines()
List_Ref_Domaine & Interprete_geometrique_base::domaines () inline
Definition at line 65 of file Interprete_geometrique_base.h.
  {
    return domains_;
  };
References domains_.
Referenced by Postraiter_domaine::interpreter_(), and Verifier_Qualite_Raffinements::verifier_qualite_raffinements().
get_info()
const Type_info * Interprete_geometrique_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Lire_Ideas, Lire_Tgrid, Mailler, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, LireMED, LireMEDfile, Read_MED_For_Testing_No_Verify_Option, and VerifierCoin.
Definition at line 21 of file Interprete_geometrique_base.cpp.
info()
const Type_info * Interprete_geometrique_base::info () static
Definition at line 21 of file Interprete_geometrique_base.cpp.
interpreter()
Entree & Interprete_geometrique_base::interpreter (Entree & is) override virtual
Reimplemented from Interprete.
Reimplemented in Raffiner_isotrope_parallele.
Definition at line 57 of file Interprete_geometrique_base.cpp.
{
  Cerr << "Execution of the interpreter " << que_suis_je() << finl;
  Process::imprimer_ram_totale();
// Appel a l'interprete fils
  interpreter_(is);
// On met a jour un certain nombre de choses
// suite a la modification des domaines
  for (int j=0; j<domains_.size(); j++)
    for(int i=0; i<domaine(j).nb_zones() ; i++)
      {
        Zone& zone = domaine(j).zone(i);
        zone.invalide_octree();
        zone.faces_bord().associer_zone(zone);
        zone.faces_joint().associer_zone(zone);
        zone.faces_raccord().associer_zone(zone);
        zone.faces_int().associer_zone(zone);
        zone.type_elem().associer_zone(zone);
        zone.fixer_premieres_faces_frontiere();
        zone.associer_domaine(domaine(j));
      }
  return is;
}
References Zone::associer_domaine(), Bords::associer_zone(), Elem_geom::associer_zone(), Faces_Internes::associer_zone(), Joints::associer_zone(), Raccords::associer_zone(), Cerr, domaine(), domains_, Zone::faces_bord(), Zone::faces_int(), Zone::faces_joint(), Zone::faces_raccord(), finl, Zone::fixer_premieres_faces_frontiere(), Process::imprimer_ram_totale(), interpreter_(), Zone::invalide_octree(), Domaine::nb_zones(), Objet_U::que_suis_je(), liste::size(), Zone::type_elem(), and Domaine::zone().
Referenced by Extraire_plan::interpreter_().
interpreter_()
virtual Entree & Interprete_geometrique_base::interpreter_ (Entree & is) pure virtual
Implemented in Calculer_Moments, Create_domain_from_sous_zone, DecoupeBord, Decouper_Bord_coincident, Dilate, Discretiser_domaine, Distanceparoi, Extraire_domaine, Extraire_plan, Extraire_surface, ExtrudeBord, ExtrudeParoi, Extruder, Extruder_en20, Extruder_en3, Imprimer_flux, Imprimer_flux_sum, Lire_Ideas, Lire_Tgrid, Mailler, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Polyedriser, Postraiter_domaine, Raffiner_anisotrope, Redresser_hexaedres_vdf, RegroupeBord, Remove_elem, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, SupprimeBord, Transformer, Triangulation_base, TroisDto2D, LireMED, Read_MED_For_Testing_No_Verify_Option, VerifierCoin, Corriger_frontiere_periodique, Orienter_Simplexes, Raffiner_Simplexes, Rectify_Mesh, Refine_Mesh, Remove_Invalid_Internal_Boundaries, Verifier_Qualite_Raffinements, and Verifier_Simplexes.
Referenced by interpreter().
mettre_a_jour_sous_zone()
void Interprete_geometrique_base::mettre_a_jour_sous_zone (Zone & zone, int & elem, int num_premier_elem, int nb_elem) const
Definition at line 83 of file Interprete_geometrique_base.cpp.
{
  Domaine& dom=zone.domaine();
  for (int ssz=0; ssz<dom.nb_ss_zones(); ssz++)
    {
      Sous_Zone& sous_zone=dom.ss_zone(ssz);
      if ((que_suis_je()=="Raffiner_anisotrope")
          || (que_suis_je()=="Raffiner_isotrope")
          || (que_suis_je()=="Remove_elem")
          || (que_suis_je()=="Tetraedriser_homogene")
          || (que_suis_je()=="Tetraedriser_homogene_compact")
          || (que_suis_je()=="Tetraedriser_homogene_fin")
          || (que_suis_je()=="Tetraedriser_par_prisme")
          || (que_suis_je()=="Tetraedriser")
          || (que_suis_je()=="Trianguler")
          || (que_suis_je()=="Trianguler_fin")
          || (que_suis_je()=="Trianguler_H")
          || (que_suis_je()=="VerifierCoin"))
        {
          const int nb_poly=sous_zone.nb_elem_tot();
          for (int nb_p=0; nb_p<nb_poly; nb_p++)
            {
              if (elem==sous_zone[nb_p])
                {
                  Cerr << "   The element " << elem << " which will be modified, is included to the subarea \"" << sous_zone.le_nom() << "\". So the element";
                  if (nb_elem>1) Cerr << "s";
                  Cerr << " generated [";
                  for(int num_elem=num_premier_elem; num_elem<num_premier_elem+nb_elem; num_elem++)
                    {
                      sous_zone.add_poly(num_elem);
                      if (num_elem!=num_premier_elem) Cerr << " ";
                      Cerr << num_elem;
                    }
                  Cerr << "] will be added to this subarea." << finl;
                }
            }
        }
      else
        {
          Cerr << finl;
          Cerr << "You have defined the subarea \"" << sous_zone.le_nom() << "\" before using the interpreter \"" << que_suis_je() << "\"." << finl;
          Cerr << "To correctly mark the good elements, set the subarea after to have used the interpreter." << finl;
          exit();
        }
    }
}
References Sous_Zone::add_poly(), Cerr, Zone::domaine(), Process::exit(), finl, Sous_Zone::le_nom(), Sous_Zone::nb_elem_tot(), Domaine::nb_ss_zones(), Objet_U::que_suis_je(), and Domaine::ss_zone().
Referenced by Decouper_Bord_coincident::Decouper_Bord_coincident_(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), VerifierCoin::interpreter_(), Raffiner_anisotrope::Raffiner_anisotrope_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), and Trianguler_H::trianguler().
printOn()
Sortie & Interprete_geometrique_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Lire_Ideas, Lire_Tgrid, Mailler, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, LireMED, LireMEDfile, Read_MED_For_Testing_No_Verify_Option, and VerifierCoin.
Definition at line 26 of file Interprete_geometrique_base.cpp.
{
  return os;
}
Referenced by Orienter_Simplexes::printOn(), Verifier_Qualite_Raffinements::printOn(), and Verifier_Simplexes::printOn().
readOn()
Entree & Interprete_geometrique_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Lire_Ideas, Lire_Tgrid, Mailler, Modif_bord_to_raccord, NettoieNoeuds, OrienteFacesBord, Orienter_Simplexes, Polyedriser, Postraiter_domaine, Raffiner_anisotrope, Raffiner_isotrope_parallele, Raffiner_Simplexes, Rectify_Mesh, Redresser_hexaedres_vdf, Refine_Mesh, RegroupeBord, Remove_elem, Remove_Invalid_Internal_Boundaries, Reordonner, Reorienter_tetraedres, Reorienter_triangles, Rotation, SupprimeBord, Tetraedriser, Tetraedriser_homogene, Tetraedriser_homogene_compact, Tetraedriser_homogene_fin, Tetraedriser_par_prisme, Transformer, Triangulation_base, Trianguler, Trianguler_fin, Trianguler_H, TroisDto2D, TroisDto2Daxi, Verifier_Qualite_Raffinements, Verifier_Simplexes, LireMED, LireMEDfile, Read_MED_For_Testing_No_Verify_Option, and VerifierCoin.
Definition at line 32 of file Interprete_geometrique_base.cpp.
{
  return is;
}
Referenced by Orienter_Simplexes::readOn(), Verifier_Qualite_Raffinements::readOn(), and Verifier_Simplexes::readOn().
self_cast() [1/2]
const Interprete_geometrique_base & Interprete_geometrique_base::self_cast (const Objet_U & r) static
Definition at line 21 of file Interprete_geometrique_base.cpp.
self_cast() [2/2]
Interprete_geometrique_base & Interprete_geometrique_base::self_cast (Objet_U & r) static
Definition at line 21 of file Interprete_geometrique_base.cpp.
Member Data Documentation
domains_
List_Ref_Domaine Interprete_geometrique_base::domains_ protected
List of reference to domains.
Definition at line 73 of file Interprete_geometrique_base.h.
Referenced by associer_domaine(), domaine(), domaines(), and interpreter().
info_obj
const Type_info Interprete_geometrique_base::info_obj static
Definition at line 49 of file Interprete_geometrique_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Interprete_geometrique_base.h
src/Kernel/Geometrie/Interprete_geometrique_base.cpp