TRUST: Operateur_Statistique_tps_base Class Reference
Operateur_Statistique_tps_base Class Reference abstract
classe Operateur_Statistique_tps_base
Represente des operations statistiques sur les champs.
Des operateurs statistiques sont utilises pour le postraitement.
#include <Operateur_Statistique_tps_base.h>
Public Member Functions
Operateur_Statistique_tps_base ()
~Operateur_Statistique_tps_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Nom & localisation_post () const
void associer (const Nom &loc_post)
virtual void associer_op_stat (const Operateur_Statistique_tps_base &)
virtual void associer (const Zone_dis_base &, const Champ_Generique_base &, double, double)=0
virtual void fixer_tstat_deb (double, double)=0
virtual void fixer_tstat_fin (double)=0
virtual void mettre_a_jour (double temps)=0
const Nom & le_nom () const override=0
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual double temps () const =0
virtual const Integrale_tps_Champ & integrale () const =0
virtual void initialiser (double val)=0
virtual void completer (const Probleme_base &)=0
virtual DoubleTab calculer_valeurs () const =0
virtual int completer_post_statistiques (const Domaine &dom, const int is_axi, Format_Post_base &format)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Operateur_Statistique_tps_base & self_cast (Objet_U &)
static const Operateur_Statistique_tps_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Nom localisation_post_
Detailed Description
classe Operateur_Statistique_tps_base
Represente des operations statistiques sur les champs.
Des operateurs statistiques sont utilises pour le postraitement.
Definition at line 38 of file Operateur_Statistique_tps_base.h.
Constructor & Destructor Documentation
Operateur_Statistique_tps_base()
Operateur_Statistique_tps_base::Operateur_Statistique_tps_base ()
Definition at line 18 of file Operateur_Statistique_tps_base.cpp.
~Operateur_Statistique_tps_base()
Operateur_Statistique_tps_base::~Operateur_Statistique_tps_base () override
Definition at line 18 of file Operateur_Statistique_tps_base.cpp.
Member Function Documentation
associer() [1/2]
void Operateur_Statistique_tps_base::associer (const Nom & loc_post) inline
Definition at line 49 of file Operateur_Statistique_tps_base.h.
  {
    localisation_post_=loc_post;
  };
References localisation_post_.
associer() [2/2]
virtual void Operateur_Statistique_tps_base::associer (const Zone_dis_base & , const Champ_Generique_base & , double , double) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
associer_op_stat()
virtual void Operateur_Statistique_tps_base::associer_op_stat (const Operateur_Statistique_tps_base &) inline virtual
Reimplemented in Op_Correlation, and Op_Ecart_type.
Definition at line 53 of file Operateur_Statistique_tps_base.h.
{};
calculer_valeurs()
virtual DoubleTab Operateur_Statistique_tps_base::calculer_valeurs () const pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Operateur_Statistique_tps::calculer_valeurs(), and Moyenne_volumique::get_champ().
completer()
virtual void Operateur_Statistique_tps_base::completer (const Probleme_base &) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Operateur_Statistique_tps::completer().
completer_post_statistiques()
int Operateur_Statistique_tps_base::completer_post_statistiques (const Domaine & dom, const int is_axi, Format_Post_base & format) virtual
Reimplemented in Op_Correlation.
Definition at line 60 of file Operateur_Statistique_tps_base.cpp.
{
  const Nom nom_post = le_nom();
  const Nom& localisation = localisation_post();
  Champ espace_stockage_source;
  const Champ_base& source = integrale().le_champ()->get_champ(espace_stockage_source);
  source.completer_post_champ(dom,axi,localisation,nom_post,format);
  return 1;
}
References Objet_U::axi, Champ_base::completer_post_champ(), Champ_Generique_base::get_champ(), integrale(), Integrale_tps_Champ::le_champ(), le_nom(), and localisation_post().
Referenced by Operateur_Statistique_tps::completer_post_statistiques().
fixer_tstat_deb()
virtual void Operateur_Statistique_tps_base::fixer_tstat_deb (double , double) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Champ_Generique_Statistiques_base::fixer_serie(), Champ_Generique_Statistiques_base::fixer_tstat_deb(), and Operateur_Statistique_tps::fixer_tstat_deb().
fixer_tstat_fin()
virtual void Operateur_Statistique_tps_base::fixer_tstat_fin (double) pure virtual
Implemented in Op_Moyenne, Op_Correlation, and Op_Ecart_type.
Referenced by Champ_Generique_Statistiques_base::fixer_serie(), and Operateur_Statistique_tps::fixer_tstat_fin().
get_info()
const Type_info * Operateur_Statistique_tps_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 18 of file Operateur_Statistique_tps_base.cpp.
info()
const Type_info * Operateur_Statistique_tps_base::info () static
Definition at line 18 of file Operateur_Statistique_tps_base.cpp.
initialiser()
virtual void Operateur_Statistique_tps_base::initialiser (double val) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Champ_Generique_Statistiques_base::fixer_serie(), and Operateur_Statistique_tps::initialiser().
integrale()
virtual const Integrale_tps_Champ & Operateur_Statistique_tps_base::integrale () const pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by completer_post_statistiques(), Moyenne_volumique::get_champ(), and Operateur_Statistique_tps::integrale().
le_nom()
const Nom & Operateur_Statistique_tps_base::le_nom () const override pure virtual
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
Nom&
Signification: le nom de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by completer_post_statistiques(), Operateur_Statistique_tps::le_nom(), and printOn().
localisation_post()
const Nom & Operateur_Statistique_tps_base::localisation_post () const inline
Definition at line 45 of file Operateur_Statistique_tps_base.h.
  {
    return localisation_post_;
  };
References localisation_post_.
Referenced by completer_post_statistiques(), and Operateur_Statistique_tps::localisation_post().
mettre_a_jour()
virtual void Operateur_Statistique_tps_base::mettre_a_jour (double temps) pure virtual
Implemented in Op_Moyenne, Op_Correlation, and Op_Ecart_type.
Referenced by Champ_Generique_Statistiques_base::mettre_a_jour(), and Operateur_Statistique_tps::mettre_a_jour().
printOn()
Sortie & Operateur_Statistique_tps_base::printOn (Sortie & s) const override protected virtual
Imprime le nom et le type de l'operateur sur
un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 35 of file Operateur_Statistique_tps_base.cpp.
{
  return s << que_suis_je() << " " << le_nom();
}
References le_nom(), and Objet_U::que_suis_je().
readOn()
Entree & Operateur_Statistique_tps_base::readOn (Entree & s) override protected virtual
NE FAIT RIEN.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 55 of file Operateur_Statistique_tps_base.cpp.
{
  return s ;
}
self_cast() [1/2]
const Operateur_Statistique_tps_base & Operateur_Statistique_tps_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Operateur_Statistique_tps_base.cpp.
self_cast() [2/2]
Operateur_Statistique_tps_base & Operateur_Statistique_tps_base::self_cast (Objet_U & r) static
Definition at line 18 of file Operateur_Statistique_tps_base.cpp.
temps()
virtual double Operateur_Statistique_tps_base::temps () const pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Operateur_Statistique_tps::temps().
Member Data Documentation
info_obj
const Type_info Operateur_Statistique_tps_base::info_obj static
Definition at line 41 of file Operateur_Statistique_tps_base.h.
localisation_post_
Nom Operateur_Statistique_tps_base::localisation_post_ protected
Definition at line 67 of file Operateur_Statistique_tps_base.h.
Referenced by associer(), and localisation_post().
The documentation for this class was generated from the following files:
src/Kernel/Statistiques_temps/Operateur_Statistique_tps_base.h
src/Kernel/Statistiques_temps/Operateur_Statistique_tps_base.cpp