TRUST: PrecondSolv Class Reference
PrecondSolv Class Reference
#include <PrecondSolv.h>
Public Member Functions
~PrecondSolv ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
PrecondSolv ()
int supporte_matrice_morse_sym () override
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Public Member Functions inherited from Precond_base
~Precond_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Precond_base ()
void reinit (Init_Status x=REINIT_ALL)
this method must be called before preconditionner() whenever
the matrix changes (coefficients only or coefficients and structure) to
tell the object to recompute some matrix related data.
void set_echange_espace_virtuel_resultat (int flag)
Call this method to change the behaviour of the preconditionner() method
0-> result will not have an up-to-date virtual space
1-> yes it will (this must be the default value in the implementation)
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
Call to the prepare() method if reinit() has been called previously, then
call to preconditionner_()...
If echange_ev_solution is not zero, the solution vector will have an updated virtual space.
void prepare (const Matrice_Base &, const DoubleVect &src)
prepares the preconditionner if needed after a matrix change (reinit() call).
prepare() is public, in case we want to perform preparation separately from preconditionning (eg nested solvers)
but calling prepare() is not mandatory (done automatically in preconditionner())
m is the new matrix, and md is the descriptor of the solution vector.
virtual int supporte_matrice_morse_sym ()
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Init_Status get_status ()
virtual int get_flag_updated_input () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static PrecondSolv & self_cast (Objet_U &)
static const PrecondSolv & self_cast (const Objet_U &)
Static Public Member Functions inherited from Precond_base
static const Type_info * info ()
static Precond_base & self_cast (Objet_U &)
static const Precond_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Precond_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void prepare_ (const Matrice_Base &, const DoubleVect &src) override
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
int preconditionner_ (const Matrice_Base &, const DoubleVect &, DoubleVect &) override
Calcule la solution du systeme lineaire: A * solution = b
avec la methode de relaxation PrecondSolv.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int preconditionner_ (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)=0
virtual void prepare_ (const Matrice_Base &, const DoubleVect &)
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
SolveurSys solveur
Protected Attributes inherited from Precond_base
int echange_ev_solution_
Additional Inherited Members
Public Types inherited from Precond_base
enum Init_Status { READY = 0 , REINIT_COEFF = 1 , REINIT_ALL = 2 }
Detailed Description
Definition at line 26 of file PrecondSolv.h.
Constructor & Destructor Documentation
~PrecondSolv()
PrecondSolv::~PrecondSolv ()
Definition at line 19 of file PrecondSolv.cpp.
PrecondSolv()
PrecondSolv::PrecondSolv ()
Definition at line 19 of file PrecondSolv.cpp.
Member Function Documentation
cree_instance()
Objet_U * PrecondSolv::cree_instance () static
Definition at line 19 of file PrecondSolv.cpp.
duplique()
int PrecondSolv::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file PrecondSolv.cpp.
get_info()
const Type_info * PrecondSolv::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Precond_base.
Definition at line 19 of file PrecondSolv.cpp.
info()
const Type_info * PrecondSolv::info () static
Definition at line 19 of file PrecondSolv.cpp.
preconditionner_()
int PrecondSolv::preconditionner_ (const Matrice_Base & matrice, const DoubleVect & b, DoubleVect & solution) override protected virtual
Calcule la solution du systeme lineaire: A * solution = b
avec la methode de relaxation PrecondSolv.
Implements Precond_base.
Definition at line 47 of file PrecondSolv.cpp.
{
  double norme=mp_norme_vect(b);
  if (norme > 0.)
    {
      DoubleVect b2(b);
// Certains solveurs peuvent avoir besoin de l'espace virtuel,
// on calcule tout le vecteur:
      assert_espace_virtuel_vect(b2);
      operator_multiply(b2, 1. / norme, VECT_ALL_ITEMS);
      solveur.resoudre_systeme(matrice, b2, solution);
      if (echange_ev_solution_)
        {
// On veut renvoyer un vecteur avec espace virtuel a jour
// Plutot que de refaire un echange on multiplie tous les elements
// mais il faut que l'espace virtuel soit deja a jour avant:
          assert_espace_virtuel_vect(solution);
          operator_multiply(solution, norme, VECT_ALL_ITEMS);
        }
      else
        {
          operator_multiply(solution, norme);
        }
    }
  else
    {
      if (echange_ev_solution_)
        {
          operator_egal(solution, 0., VECT_ALL_ITEMS);
        }
      else
        {
          operator_egal(solution, 0.);
        }
    }
  return 1;
}
References assert_espace_virtuel_vect(), Precond_base::echange_ev_solution_, mp_norme_vect(), norme(), operator_egal(), operator_multiply(), SolveurSys::resoudre_systeme(), solveur, and VECT_ALL_ITEMS.
prepare_()
void PrecondSolv::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_().
Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise
status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
Definition at line 38 of file PrecondSolv.cpp.
{
  solveur.valeur().reinit();
  Precond_base::prepare_(m, src);
}
References Precond_base::prepare_(), SolveurSys_base::reinit(), solveur, and Deriv_SolveurSys_base::valeur().
printOn()
Sortie & PrecondSolv::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 23 of file PrecondSolv.cpp.
{
  return s;
}
readOn()
Entree & PrecondSolv::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Precond_base.
Definition at line 28 of file PrecondSolv.cpp.
{
  is >> solveur;
  solveur.nommer("PrecondSolv");
// Pour eviter trop d'affichage (Convergence)
  if (!solveur.valeur().limpr())
    solveur.valeur().fixer_limpr(-1);
  return is;
}
References SolveurSys_base::fixer_limpr(), SolveurSys_base::limpr(), SolveurSys::nommer(), solveur, and Deriv_SolveurSys_base::valeur().
self_cast() [1/2]
const PrecondSolv & PrecondSolv::self_cast (const Objet_U & r) static
Definition at line 19 of file PrecondSolv.cpp.
self_cast() [2/2]
PrecondSolv & PrecondSolv::self_cast (Objet_U & r) static
Definition at line 19 of file PrecondSolv.cpp.
supporte_matrice_morse_sym()
int PrecondSolv::supporte_matrice_morse_sym () inline override virtual
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Reimplemented from Precond_base.
Definition at line 31 of file PrecondSolv.h.
  {
    return solveur.valeur().supporte_matrice_morse_sym();
  };
References solveur, SolveurSys_base::supporte_matrice_morse_sym(), and Deriv_SolveurSys_base::valeur().
taille_memoire()
unsigned PrecondSolv::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file PrecondSolv.cpp.
Member Data Documentation
info_obj
const Type_info PrecondSolv::info_obj static
Definition at line 28 of file PrecondSolv.h.
solveur
SolveurSys PrecondSolv::solveur protected
Definition at line 40 of file PrecondSolv.h.
Referenced by preconditionner_(), prepare_(), readOn(), and supporte_matrice_morse_sym().
The documentation for this class was generated from the following files:
src/Kernel/Math/SolvSys/PrecondSolv.h
src/Kernel/Math/SolvSys/PrecondSolv.cpp