TRUST: Ref_Zone_Cl_dis Class Reference
Ref_Zone_Cl_dis Class Reference
#include <Ref_Zone_Cl_dis.h>
Public Member Functions
~Ref_Zone_Cl_dis ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Zone_Cl_dis ()
Ref_Zone_Cl_dis (const Zone_Cl_dis &)
Ref_Zone_Cl_dis (const Ref_Zone_Cl_dis &)
const Zone_Cl_dis & valeur () const
Zone_Cl_dis & valeur ()
const Zone_Cl_dis * operator-> () const
Zone_Cl_dis * operator-> ()
const Ref_Zone_Cl_dis & operator= (const Zone_Cl_dis &)
const Ref_Zone_Cl_dis & operator= (const Ref_Zone_Cl_dis &)
operator const Zone_Cl_dis & () const
operator Zone_Cl_dis & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Zone_Cl_dis & self_cast (Objet_U &)
static const Ref_Zone_Cl_dis & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Zone_Cl_dis * pointeur_
Detailed Description
Definition at line 28 of file Ref_Zone_Cl_dis.h.
Constructor & Destructor Documentation
Ref_Zone_Cl_dis::~Ref_Zone_Cl_dis ()
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Ref_Zone_Cl_dis::Ref_Zone_Cl_dis ()
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Ref_Zone_Cl_dis::Ref_Zone_Cl_dis (const Zone_Cl_dis & t)
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Ref_Zone_Cl_dis::Ref_Zone_Cl_dis (const Ref_Zone_Cl_dis & t)
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Member Function Documentation
Objet_U * Ref_Zone_Cl_dis::cree_instance () [static]
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
int Ref_Zone_Cl_dis::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Type_info * Ref_Zone_Cl_dis::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Type_info & Ref_Zone_Cl_dis::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Type_info * Ref_Zone_Cl_dis::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Ref_Zone_Cl_dis::operator const Zone_Cl_dis & () const
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Ref_Zone_Cl_dis::operator Zone_Cl_dis & ()
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Zone_Cl_dis * Ref_Zone_Cl_dis::operator-> () const [inline]
Definition at line 28 of file Ref_Zone_Cl_dis.h.
Zone_Cl_dis * Ref_Zone_Cl_dis::operator-> () [inline]
Definition at line 28 of file Ref_Zone_Cl_dis.h.
const Ref_Zone_Cl_dis & Ref_Zone_Cl_dis::operator= (const Ref_Zone_Cl_dis & t)
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Ref_Zone_Cl_dis & Ref_Zone_Cl_dis::operator= (const Zone_Cl_dis & t)
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Sortie & Ref_Zone_Cl_dis::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Entree & Ref_Zone_Cl_dis::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Ref_Zone_Cl_dis & Ref_Zone_Cl_dis::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
Ref_Zone_Cl_dis & Ref_Zone_Cl_dis::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
void Ref_Zone_Cl_dis::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
unsigned Ref_Zone_Cl_dis::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Zone_Cl_dis.cpp.
const Zone_Cl_dis & Ref_Zone_Cl_dis::valeur () const [inline]
Definition at line 28 of file Ref_Zone_Cl_dis.h.
Referenced by EDO_Pression_th_VEF::calculer_grad(), EOS_Tools_VEF::divu_discvit(), Champ_P0_PolyMAC::init_cl(), Champ_P0_CoviMAC::init_fcl(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), and Champ_Inc_base::zone_Cl_dis().
Zone_Cl_dis & Ref_Zone_Cl_dis::valeur () [inline]
Definition at line 28 of file Ref_Zone_Cl_dis.h.
Member Data Documentation
const Type_info Ref_Zone_Cl_dis::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Zone_Cl_dis.h.
Zone_Cl_dis* Ref_Zone_Cl_dis::pointeur_ [private]
Definition at line 28 of file Ref_Zone_Cl_dis.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Zone_Cl_dis.h
src/Kernel/Framework/Ref_Zone_Cl_dis.cpp