TRUST: Matrice Class Reference
Matrice Class Reference
#include <Matrice.h>
Public Member Functions
Matrice ()
~Matrice ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Matrice (const Matrice &)
Matrice & operator= (const Matrice &matrix)
Matrice & operator= (const Matrice_Base &matrix)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Matrice & self_cast (Objet_U &)
static const Matrice & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
virtual Entree & readOn (Entree &)
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Detailed Description
Definition at line 46 of file Matrice.h.
Constructor & Destructor Documentation
Matrice::Matrice ()
Definition at line 27 of file Matrice.cpp.
Matrice::~Matrice ()
Definition at line 27 of file Matrice.cpp.
Matrice::Matrice (const Matrice &)
Member Function Documentation
Objet_U * Matrice::cree_instance () [static]
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
int Matrice::duplique () const [virtual]
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
const Type_info * Matrice::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
const Type_info * Matrice::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
Matrice & Matrice::operator= (const Matrice & matrix)
Definition at line 41 of file Matrice.cpp.
References DERIV, and Deriv_Matrice_Base::valeur().
Referenced by operator=().
{
  DERIV( Matrice_Base )::operator= ( matrix.valeur( ) );
  return *this;
}
Matrice & Matrice::operator= (const Matrice_Base & matrix)
Reimplemented from Deriv_Matrice_Base.
Definition at line 47 of file Matrice.cpp.
References DERIV, and operator=().
{
  DERIV( Matrice_Base )::operator= ( matrix );
  return *this;
}
Sortie & Matrice::printOn (Sortie & x) const [protected, virtual]
Surcharge Objet_U::printOn(Sortie&)
Ecriture de la cle d'un O_U_Ptr sur un flot de sortie.
A definir avec readOn. Pour l'instant :
os << cle_ << finl;.
Reimplemented from Deriv_Matrice_Base.
Definition at line 29 of file Matrice.cpp.
References DERIV.
{
  DERIV( Matrice_Base )::printOn( os );
  return os;
}
Entree & Matrice::readOn (Entree & is) [protected, virtual]
Surcharge Objet_U::readOn(Entree&)
Lecture d'un O_U_Ptr (par sa cle) dans un flot d'entree
ATTENTION: Le comportement de cette fonction est a definir.
Pour l'instant: ne fait rien.
Reimplemented from Deriv_Matrice_Base.
Definition at line 35 of file Matrice.cpp.
References DERIV.
{
  DERIV( Matrice_Base )::readOn( is );
  return is;
}
Matrice & Matrice::self_cast (Objet_U & r) [static]
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
const Matrice & Matrice::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
unsigned Matrice::taille_memoire () const [virtual]
Reimplemented from Deriv_Matrice_Base.
Definition at line 27 of file Matrice.cpp.
Member Data Documentation
const Type_info Matrice::info_obj [static]
Reimplemented from Deriv_Matrice_Base.
Definition at line 49 of file Matrice.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice.h
src/Kernel/Math/Matrices/Matrice.cpp