TRUST: Domaine Class Reference
Domaine Class Reference
Classe Domaine
Un Domaine represente le domaine (spatial) de resolution d'un Probleme.
Un Domaine a un Nom, il est constitue d'une ou plusieurs Zone qui
peuvent etre eventuellement decoupees en Sous_Zone.
Un Domaine porte l'ensemble des sommets utilises par ses Zones.
On peut vouloir resoudre des problemes de type different sur plusieurs
domaines, geometriquement les domaines sont alors couples par des
surfaces qu'on appelle Raccord.
#include <Domaine.h>
Public Member Functions
~Domaine ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Domaine ()
Constructeur par defaut d'un objet Domaine.
Ne fait rien sauf fixer la valeur d'epsilon
a Objet_U::precision_geom
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
const Nom & le_nom () const override
Renvoie le nom du domaine.
void nommer (const Nom &) override
Donne un nom au domaine.
int nb_zones () const
Renvoie le nombre de zone du domaine.
const Zone & zone (int) const
Renvoie la i-ieme zone du domaine.
(version const)
Zone & zone (int)
Renvoie la i-ieme zone du domaine.
const Zone & zone (const Nom &) const
Renvoie la Zone dont le nom est indique en parametre.
(version const)
Zone & zone (const Nom &)
Renvoie la Zone dont le nom est indique en parametre.
int nb_ss_zones () const
Renvoie le nombre de sous-zone.
const Sous_Zone & ss_zone (int) const
Renvoie la i-ieme sous-zone.
(version const)
Sous_Zone & ss_zone (int)
Renvoie la i-ieme sous-zone.
const Sous_Zone & ss_zone (const Nom &) const
Renvoie la sous-zone dont le nom est indique en parametre.
(version const)
Sous_Zone & ss_zone (const Nom &)
Renvoie la sous-zone dont le nom est indique en parametre.
double coord (int, int) const
Renvoie la j-ieme coordonnee du i-ieme noeud.
double & coord (int, int)
Renvoie une reference sur la j-ieme coordonnee
du i-ieme noeud. (ce qui permet de modifier sa valeur)
const DoubleTab & coord_sommets () const
Renvoie le tableau des coordonnees des noeuds (sommets).
(acces en lecture)
virtual int nb_som () const
Renvoie le nombre de sommets.
virtual int nb_som_tot () const
Renvoie le nombre total de sommets.
void add (const Sous_Zone &)
Ajoute une Sous_Zone au domaine.
int associer_ (Objet_U &) override
Association d'une Sous_Zone au domaine.
L'interface permet de passer n'importe quel
Objet_U mais ne gere (dynamiquement) que
l'association d'un objet derivant Sous_Zone.
DoubleTab & les_sommets ()
Renvoie le nombre total de sommets.
const DoubleTab & les_sommets () const
Renvoie le tableau des sommets du domaine.
DoubleTab getBoundingBox () const
Zone & add (Zone &)
Ajoute une Zone au domaine.
void ajouter (const DoubleTab &, IntVect &)
Ajoute des noeuds au domaine avec elimination des noeuds double
au retour nums contient les nouveaux numeros des noeuds de soms
apres elimination des doublons.
void ajouter (const DoubleTab &)
Ajoute des noeuds (ou sommets) au domaine<br>(sans verifier les doublons)
void comprimer ()
Rassemble les Zones de meme type.
void fixer_epsilon (double)
Fixe epsilon,
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
double epsilon () const
Renvoie epsilon.
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
void reordonner ()
Reordonne les mailles du domaine suivant les
conventions de Trio-U.
int numero_sommet (int i) const
const Zones & zones () const
Zones & zones ()
const List_Ref_Sous_Zone & ss_zones () const
int deformable () const
int & deformable ()
int get_renum_som_perio (int) const
void construire_renum_som_perio (const Conds_lim &, const Zone_dis &)
virtual void initialiser (double temps, Domaine_dis &, Probleme_base &)
virtual void set_dt (double &dt_)
virtual void mettre_a_jour (double temps, Domaine_dis &, Probleme_base &)
void set_fichier_lu (Nom &nom)
const Nom & get_fichier_lu () const
virtual void creer_tableau_sommets (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par sommet du maillage.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual void creer_tableau_elements (Array_base &, Array_base::Resize_Options opt=Array_base::COPY_INIT) const
Cree un tableau ayant une "ligne" par element du maillage.
Pour l'instant, erreur s'il y a plus d'une zone dans le domaine.
Voir MD_Vector_tools::creer_tableau_distribue()
virtual const MD_Vector & md_vector_sommets () const
void set_renum_som_perio (IntTab &renum)
void creer_mes_domaines_frontieres (const Zone_VF &zone_vf)
void imprimer () const
const List_Ref_Domaine & domaines_frontieres () const
void buildUFacesMesh (const Zone_dis_base &zone_dis_base) const
bool Axi1d () const
bool Axi1d ()
void read_vertices (Entree &s)
only read vertices from the stream s
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Domaine & self_cast (Objet_U &)
static const Domaine & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecrit le domaine sur un flot de sortie.
On ecrit le nom, les sommets, les zones
et les sous-zones.
Entree & readOn (Entree &) override
Lit les specifications d'un domaine
a partir d'un flot d'entree. Associe les zones
lues au domaine.
Format:
nom_domaine
bloc de lecture des Sommets
bloc de lecture des Zones
bloc de lecture des Sous_Zones
Attention: en parallele, chaque processeur s'attend a lire une strucutre domaine
avec des infos de joint, mais il y a des communications globales.
Pour lire un domaine sur un seul processeur, il faut mettre le processeur dans
un groupe seul.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
List_Ref_Domaine domaines_frontieres_
Nom nom_
DoubleTab sommets
List_Ref_Sous_Zone les_ss_zones
Zones les_zones
ArrOfInt renum_som_perio
double epsilon_
int deformable_
Nom fichier_lu_
int axi1d
Detailed Description
Classe Domaine
Un Domaine represente le domaine (spatial) de resolution d'un Probleme.
Un Domaine a un Nom, il est constitue d'une ou plusieurs Zone qui
peuvent etre eventuellement decoupees en Sous_Zone.
Un Domaine porte l'ensemble des sommets utilises par ses Zones.
On peut vouloir resoudre des problemes de type different sur plusieurs
domaines, geometriquement les domaines sont alors couples par des
surfaces qu'on appelle Raccord.
Definition at line 51 of file Domaine.h.
Constructor & Destructor Documentation
~Domaine()
Domaine::~Domaine ()
Definition at line 36 of file Domaine.cpp.
Domaine()
Domaine::Domaine ()
Constructeur par defaut d'un objet Domaine.
Ne fait rien sauf fixer la valeur d'epsilon
a Objet_U::precision_geom
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
Definition at line 160 of file Domaine.cpp.
                 : epsilon_(Objet_U::precision_geom),deformable_(0)
{
#ifdef MEDCOUPLING_
  mesh_ = NULL;
#endif
  axi1d = 0;
}
References axi1d.
Member Function Documentation
add() [1/2]
void Domaine::add (const Sous_Zone & ssz)
Ajoute une Sous_Zone au domaine.
Definition at line 385 of file Domaine.cpp.
{
  les_ss_zones.add(ssz);
}
References List_Ref_Sous_Zone::add(), and les_ss_zones.
Referenced by associer_(), Champ_Generique_Extraction::completer(), DomaineCutter::construire_sous_domaine(), convert_domain_to_Domaine(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeBord::extruder_hexa_old(), MaillerParallel::interpreter(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extruder_en3::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), Scatter::mergeDomains(), and Scatter::readDomainWithoutCollComm().
add() [2/2]
Zone & Domaine::add (Zone & une_zone)
Ajoute une Zone au domaine.
Returns
Zone&
Signification: la zone que l'on vient d'ajouter au domaine
Contraintes:
Definition at line 196 of file Domaine.cpp.
{
  return les_zones.add(une_zone);
}
References List_Zone::add(), and les_zones.
ajouter() [1/2]
void Domaine::ajouter (const DoubleTab & soms)
Ajoute des noeuds (ou sommets) au domaine<br>(sans verifier les doublons)
Definition at line 217 of file Domaine.cpp.
{
  int oldsz=sommets.dimension(0);
  int ajoutsz=soms.dimension(0);
  int dim=soms.dimension(1);
  sommets.resize(oldsz+ajoutsz,dim);
  for(int i=0; i<ajoutsz; i++)
    for(int k=0; k<dim; k++)
      sommets(oldsz+i,k)=soms(i,k) ;
}
References TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::resize(), and sommets.
ajouter() [2/2]
void Domaine::ajouter (const DoubleTab & soms, IntVect & nums)
Ajoute des noeuds au domaine avec elimination des noeuds double
au retour nums contient les nouveaux numeros des noeuds de soms
apres elimination des doublons.
Definition at line 252 of file Domaine.cpp.
{
  int oldsz=sommets.dimension(0);
  int ajoutsz=soms.dimension(0);
  int dim=soms.dimension(1);
  nums.resize(ajoutsz);
  nums=-1;
  if(oldsz!=0)
    {
      assert(dim==sommets.dimension(1));
      Octree_Double octree;
      octree.build_nodes(les_sommets(), 0 /* ne pas inclure les sommets virtuels */);
      int i, k;
      int compteur=0;
      ArrOfDouble tab_coord(dim);
      ArrOfInt liste_sommets;
      liste_sommets.set_smart_resize(1);
      for( i=0; i< ajoutsz; i++)
        {
          for (int j = 0; j < dim; j++)
            tab_coord[j] = soms(i,j);
          octree.search_elements_box(tab_coord, epsilon_, liste_sommets);
          octree.search_nodes_close_to(tab_coord, les_sommets(), liste_sommets, epsilon_);
          const int nb_sommets_proches = liste_sommets.size_array();
          if (nb_sommets_proches == 0)
            {
// Aucun sommet du premier domaine n'est proche du sommet i.
// Garder i.
            }
          else if (nb_sommets_proches == 1)
            {
// Un sommet est confondu avec le sommet i a epsilon_ pres.
// Ne pas garder le sommet
              nums(i) = liste_sommets[0];
              compteur++;
            }
          else
            {
// Plusieurs sommets du domaine initial sont dans un rayon de epsilon.
// epsilon est trop grand.
              Cerr << "Error : several nodes of the domain 1 are within radius epsilon="
                   << epsilon_ << " of point " << tab_coord << ". We must reduce epsilon. " << finl;
              Process::exit();
            }
        }
      Cerr << compteur << " double nodes were found \n";
      sommets.resize(oldsz+ajoutsz-compteur,dim);
      compteur=0;
      for( i=0; i<ajoutsz; i++)
        if(nums(i)==-1)
          {
            nums(i)=oldsz+compteur;
            compteur++;
            for( k=0; k<dim; k++)
              sommets(nums(i),k)=soms(i,k) ;
          }
    }
  else
    {
      sommets=soms;
// if som has a descriptor, delete it:
      sommets.set_md_vector(MD_Vector());
      for(int i=0; i<ajoutsz; i++)
        {
          nums(i)=i;
        }
    }
}
References Octree_Double::build_nodes(), Cerr, compteur, TRUSTTab< _TYPE_ >::dimension(), epsilon_, Process::exit(), finl, les_sommets(), TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Octree_Double::search_elements_box(), Octree_Double::search_nodes_close_to(), TRUSTTab< _TYPE_ >::set_md_vector(), TRUSTArray< _TYPE_ >::set_smart_resize(), TRUSTArray< _TYPE_ >::size_array(), and sommets.
Referenced by Pave::associer_domaine(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), ExtrudeBord::extruder_bord(), Extruder::extruder_hexa(), Extruder_en3::interpreter_(), Mailler::interpreter_(), and Scatter::mergeDomains().
associer_()
int Domaine::associer_ (Objet_U & ob) override virtual
Association d'une Sous_Zone au domaine.
L'interface permet de passer n'importe quel
Objet_U mais ne gere (dynamiquement) que
l'association d'un objet derivant Sous_Zone.
Returns
int
Signification: 1 si l'association a reussie
0 sinon (l'objet n'etait pas derive Sous_Zone)
Contraintes:
Reimplemented from Objet_U.
Definition at line 359 of file Domaine.cpp.
{
  if( sub_type(Sous_Zone, ob))
    {
      add(ref_cast(Sous_Zone, ob));
      ob.associer_(*this);
      return 1;
    }
  return 0;
}
References add(), Objet_U::associer_(), ref_cast, and sub_type.
Axi1d() [1/2]
bool Domaine::Axi1d () inline
Definition at line 155 of file Domaine.h.
  {
    return axi1d;
  }
References axi1d.
Axi1d() [2/2]
bool Domaine::Axi1d () const inline
Definition at line 151 of file Domaine.h.
  {
    return axi1d;
  }
References axi1d.
Referenced by Echange_interne_global_impose::completer().
buildUFacesMesh()
void Domaine::buildUFacesMesh (const Zone_dis_base & zone_dis_base) const
Definition at line 567 of file Domaine.cpp.
{
#ifdef MEDCOUPLING_
  MCAuto<DataArrayInt> desc(DataArrayInt::New());
  MCAuto<DataArrayInt> descIndx(DataArrayInt::New());
  MCAuto<DataArrayInt> revDesc(DataArrayInt::New());
  MCAuto<DataArrayInt> revDescIndx(DataArrayInt::New());
  faces_mesh_ = mesh_->buildDescendingConnectivity(desc, descIndx, revDesc, revDescIndx);
// Renumber faces to have the same numbering than Domaine_dis
  std::size_t size = faces_mesh_->getNumberOfCells();
  IntVect renum(size);
// Compute Center of Mass
  MCAuto<DataArrayDouble> xv_med = faces_mesh_->computeCellCenterOfMass();
// On boucle sur les elements des tableaux Zone_VF::elem_faces et desc
// Ensuite on compare geometriquement les centres des faces de ces tableaux pour trouver les relations
// Boucle sur les mailles
  const IntTab& elem_faces = ref_cast(Zone_VF, zone_dis_base).elem_faces();
  int nb_elem = elem_faces.dimension(0);
  assert(nb_elem == (int)descIndx->getNbOfElems()-1);
// Centre des faces TRUST:
  const DoubleTab& xv = ref_cast(Zone_VF, zone_dis_base).xv();
// int nb_faces = xv.dimension_tot(0);
  int nb_comp = xv.dimension_tot(1), f;
// Boucle sur les elements
  MCAuto<DataArrayInt> renum_local(DataArrayInt::New());
  for (int elem=0; elem<nb_elem; elem++)
    {
// Cerr << "elem=" << elem << finl;
      int nb_face_elem = 0;
      for (int i = 0; i < elem_faces.dimension(1) && elem_faces(elem, i) >= 0; i++)
        nb_face_elem++;
// xv1, xv2 tableaux temporaires des centres des faces de l'element elem pour comparaison
      MCAuto<DataArrayDouble> xv1(DataArrayDouble::New());
      xv1->alloc(nb_face_elem, nb_comp);
      MCAuto<DataArrayDouble> xv2(DataArrayDouble::New());
      xv2->alloc(nb_face_elem, nb_comp);
      for (int i = 0; i < elem_faces.dimension(1) && (f = elem_faces(elem, i)) >= 0; i++)
        {
          /*
          Cerr << "\tface=" << face;
          for (int j=0; j<nb_comp; j++) Cerr << " " << xv(face, j);
          Cerr << finl; */
// Face globale MED
          int index = descIndx->getIJ(elem, 0);
          int face_med = desc->getIJ(index + i, 0);
          /*
          Cerr << "\tface_med=" << face_med;
          for (int j=0; j<nb_comp; j++) Cerr << " " << xv_med->getIJ(face_med, j);
          Cerr << finl; */
// Centre des faces TRUST et MED
          for (int j=0; j<nb_comp; j++)
            {
              xv1->setIJ(i, j, xv(f, j));
              xv2->setIJ(i, j, xv_med->getIJ(face_med, j));
            }
        }
      renum_local = xv2->findClosestTupleId(xv1);
      for (int i=0; i<renum_local->getNumberOfTuples(); i++)
        {
          int i_med = renum_local->getIJ(i, 0);
          int face_med = desc->getIJ(descIndx->getIJ(elem, 0) + i_med, 0);
          int face = elem_faces(elem, i);
          /*
          Cerr << "Local: " << i_med << " -> " << (int)i << finl;
          Cerr << "Global:" << face_med << " -> " << face << finl;
           */
          renum(face_med) = face;
        }
    }
#ifdef NDEBUG
  bool check = false;
#else
  bool check = true;
#endif
// Apply the renumbering:
  faces_mesh_->renumberCells(renum.addr(), check);
#ifndef NDEBUG
  faces_mesh_->checkConsistency();
#endif
#endif
}
References TRUSTArray< _TYPE_ >::addr(), check(), TRUSTTab< _TYPE_ >::dimension(), TRUSTTab< _TYPE_ >::dimension_tot(), and ref_cast.
comprimer()
void Domaine::comprimer ()
Rassemble les Zones de meme type.
Definition at line 336 of file Domaine.cpp.
{
  les_zones.comprimer();
}
References Zones::comprimer(), and les_zones.
Referenced by Extruder_en3::interpreter_(), and Mailler::interpreter_().
construire_renum_som_perio()
void Domaine::construire_renum_som_perio (const Conds_lim & les_cl, const Zone_dis & zone_dis)
Definition at line 411 of file Domaine.cpp.
{
  Noms bords_perio;
  const int nb_bords = les_cl.size();
  for (int n_bord = 0; n_bord < nb_bords; n_bord++)
    {
      if (sub_type(Periodique, les_cl[n_bord].valeur()))
        bords_perio.add(les_cl[n_bord].frontiere_dis().frontiere().le_nom());
    }
  Reordonner_faces_periodiques::renum_som_perio(*this, bords_perio, renum_som_perio,
                                                1 /* Calculer les valeurs pour les sommets virtuels */);
}
References Vect_Nom::add(), le_nom(), renum_som_perio, Reordonner_faces_periodiques::renum_som_perio(), vect_impl::size(), sub_type, and valeur().
Referenced by Conds_lim::completer().
coord() [1/2]
double & Domaine::coord (int i, int j) inline
Renvoie une reference sur la j-ieme coordonnee
du i-ieme noeud. (ce qui permet de modifier sa valeur)
Returns
double&
Signification: reference sur la j-ieme coordonnee du i-ieme noeud
Contraintes:
Definition at line 473 of file Domaine.h.
{
  return sommets(numero_sommet(i),j);
}
References numero_sommet(), and sommets.
coord() [2/2]
double Domaine::coord (int i, int j) const inline
Renvoie la j-ieme coordonnee du i-ieme noeud.
Returns
double
Signification: la j-ieme coordonnee du i-ieme noeud
Contraintes:
Definition at line 448 of file Domaine.h.
{
  return sommets(numero_sommet(i),j);
}
References numero_sommet(), and sommets.
Referenced by Elem_geom_base::calculer_centres_gravite(), Hexaedre_axi::calculer_centres_gravite(), Rectangle_axi::calculer_centres_gravite(), Faces_VDF::calculer_orientation(), Faces::calculer_surfaces(), Polyedre::calculer_un_centre_gravite(), Source_PDF_EF::calculer_vitesse_imposee_elem_fluid(), Source_PDF_EF::calculer_vitesse_imposee_hybrid(), Source_PDF_EF::calculer_vitesse_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Hexaedre::calculer_volumes(), Hexaedre_axi::calculer_volumes(), Hexaedre_VEF::calculer_volumes(), Rectangle::calculer_volumes(), Rectangle_2D_axi::calculer_volumes(), Rectangle_axi::calculer_volumes(), Segment::calculer_volumes(), Segment_axi::calculer_volumes(), Tetraedre::calculer_volumes(), Hexaedre::contient(), Hexaedre_axi::contient(), Point::contient(), Prisme::contient(), Quadrangle_VEF::contient(), Rectangle::contient(), Rectangle_axi::contient(), Segment::contient(), Triangle::contient(), contient_Tetra(), Op_Div_VEFP1B_Elem::degres_liberte(), Format_Post_Lml::ecrire_domaine_lml(), ExtrudeBord::extruder_bord(), ExtrudeBord::extruder_hexa_old(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Op_Diff_VEF_Face_Penalise::longueur(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), OctreeRoot::rang_sommet(), Champ_Uniforme_Morceaux::readOn(), Sous_Zone::readOn(), Champ_front_MED::remplir_tab(), Faces::reordonner(), Segment::reordonner(), Rectangle::reordonner_elem(), Champ_Face_implementation::valeur_a_elem(), Champ_Face_implementation::valeur_a_elem_compo(), Champ_base::valeur_a_sommet(), Champ_Q1NC_impl::valeur_a_sommet_compo(), Champ_Face_implementation::valeur_aux_elems(), Champ_Face_implementation::valeur_aux_elems_compo(), Champ_Face_implementation::valeur_aux_sommets(), Champ_Q1NC_impl::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets_compo(), and Champ_Q1NC_impl::valeur_aux_sommets_compo().
coord_sommets()
const DoubleTab & Domaine::coord_sommets () const inline
Renvoie le tableau des coordonnees des noeuds (sommets).
(acces en lecture)
Returns
DoubleTab&
Signification: le tableau des coordonnees des noeuds
Contraintes: reference constante
Definition at line 493 of file Domaine.h.
{
  return sommets;
}
References sommets.
Referenced by Champ_P1_isoP1Bulle::affecter_(), Champ_P1NC::affecter_(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_PolyMAC_Face::ajouter_blocs_ext(), ajouter_bord(), Assembleur_P_VDF_Q4::assembler(), Source_PDF_EF::associer_pb(), Zone_EF::calculer_Bij(), Zone_EF_axi::calculer_Bij_gen(), Faces::calculer_centres_gravite(), Polyedre::calculer_centres_gravite(), Polygone::calculer_centres_gravite(), Zone::calculer_centres_gravite_aretes(), Op_Conv_Muscl_New_VEF_Face::calculer_flux_operateur_centre(), EDO_Pression_th_VEF::calculer_grad(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Zone_EF_axi::calculer_IPhi(), calculer_liste_complete_aretes_joint(), Hexaedre::calculer_normales(), Rectangle::calculer_normales(), Tetraedre::calculer_normales(), Triangle::calculer_normales(), Faces::calculer_surfaces(), Polygone::calculer_un_centre_gravite(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Polyedre::calculer_volumes(), Polygone::calculer_volumes(), Prisme::calculer_volumes(), Quadrangle_VEF::calculer_volumes(), Triangle::calculer_volumes(), Faces_builder::check_erreur_faces(), Reordonner_faces_periodiques::chercher_direction_perio(), Source_PDF_EF::compute_vitesse_imposee_projete(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), OctreeRoot::construire(), Octree::construire(), Scatter::construire_correspondance_sommets_par_coordonnees(), DomaineCutter::construire_sous_domaine(), Polyedre::contient(), Polygone::contient(), Tetraedre::contient(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Hexa_VEF::creer_normales_facettes_Cl(), Tetraedriser_homogene_compact::creer_sommet(), Tetraedriser_homogene_fin::creer_sommet(), creer_sommet(), decoupe(), DecoupeBord::Decouper(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Zone_Poly_base::detecter_faces_non_planes(), Zone_Poly_base::discretiser(), Zone_PolyMAC::discretiser(), Zone_VDF::dist_face_period(), distance_sommets(), exemple_champ_non_homogene(), TroisDto2D::extraire_2D(), ExtrudeBord::extruder_bord(), Zone_PolyMAC_P0::fgrad(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_ref_coordinates(), Champ_Generique_refChamp::get_ref_coordinates(), getBoundingBox(), Zone_Cl_EF::imposer_cond_lim(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Champ_Q4_implementation::imprime_Q4(), Zone::indice_elements(), Echange_contact_Correlation_VEF::init(), Zone_Poly_base::init_dist_paroi_globale(), Champ_implementation_P1::init_from_file(), Echange_contact_PolyMAC_P0::init_fs_dist(), Decouper_multi::interpreter(), Distanceparoi::interpreter_(), Extruder_en3::interpreter_(), Mailler::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Zone_PolyMAC::M1(), Scatter::mergeDomains(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VDF_Q4::modifier_secmem(), mon_construire_correspondance_sommets_par_coordonnees(), Hexa_EF::normale(), Quadri_EF::normale(), Segment_EF_axi::normale(), Tetra_EF::normale(), Tri_EF::normale(), Hexa_poly::normale(), Polyedre_poly::normale(), Polygone_poly::normale(), Quadri_poly::normale(), Tetra_poly::normale(), Tri_poly::normale(), Hexa_VEF::normale(), Quadri_VEF::normale(), Tetra_VEF::normale(), Tri_VEF::normale(), OrienteFacesBord::oriente_faces_bord(), Zone_PolyMAC::orthocentrer(), Polyedriser::polyedriser(), Postraitement::postraiter_tableau(), projette(), OctreeRoot::rang_arete(), Debog_Pb::read_geometry_data(), Champ_Q4_implementation::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Zone_Cl_VEF::remplir_normales_facettes_Cl(), Reordonner_faces_periodiques::renum_som_perio(), Reorienter_tetraedres::Reorienter(), Reorienter_triangles::Reorienter(), som_pscal(), Trianguler_fin::trianguler(), Champ_P1NC_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_som_lu::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_base::valeur_aux_sommets(), Champ_implementation_base::valeur_aux_sommets(), Champ_base::valeur_aux_sommets_compo(), Champ_implementation_base::valeur_aux_sommets_compo(), Zone_VEF::vecteur_face_facette(), verifier(), and Zone_PolyMAC::W1().
cree_instance()
Objet_U * Domaine::cree_instance () static
Definition at line 36 of file Domaine.cpp.
creer_mes_domaines_frontieres()
void Domaine::creer_mes_domaines_frontieres (const Zone_VF & zone_vf)
Definition at line 461 of file Domaine.cpp.
{
  const Nom expr_elements("1");
  const Nom expr_faces("1");
  int nb_frontieres = zone(0).nb_front_Cl();
  domaines_frontieres_.vide();
  for (int i=0; i<nb_frontieres; i++)
    {
// Nom de la frontiere
      Noms nom_frontiere(1);
      nom_frontiere[0]=zone(0).frontiere(i).le_nom();
// Nom du domaine surfacique que l'on va construire
      Nom nom_domaine_surfacique=le_nom();
      nom_domaine_surfacique+="_boundaries_";
      nom_domaine_surfacique+=zone(0).frontiere(i).le_nom();
// Creation
      Cerr << "Creating a surface domain named " << nom_domaine_surfacique << " for the boundary " << nom_frontiere[0] << " of the domain " << le_nom() << finl;
      Interprete_bloc& interp = Interprete_bloc::interprete_courant();
      if (interp.objet_global_existant(nom_domaine_surfacique))
        {
          Cerr << "Domain " << nom_domaine_surfacique
               << " already exists, writing to this object." << finl;
          Domaine& dom_new = ref_cast(Domaine, interprete().objet(nom_domaine_surfacique));
          Scatter::uninit_sequential_domain(dom_new);
        }
      else
        {
          DerObjU ob;
          ob.typer("Domaine");
          interp.ajouter(nom_domaine_surfacique, ob);
        }
      Domaine& dom_new = ref_cast(Domaine, interprete().objet(nom_domaine_surfacique));
      Extraire_surface::extraire_surface(dom_new,*this,nom_domaine_surfacique,zone_vf,expr_elements,expr_faces,0,nom_frontiere);
      REF(Domaine)& ref_dom_new=domaines_frontieres_.add(REF(Domaine)());
      ref_dom_new=dom_new;
    }
}
References List_Ref_Domaine::add(), Interprete_bloc::ajouter(), Cerr, domaines_frontieres_, Extraire_surface::extraire_surface(), finl, Zone::frontiere(), Objet_U::interprete(), Interprete_bloc::interprete_courant(), le_nom(), Frontiere::le_nom(), Zone::nb_front_Cl(), Interprete_bloc::objet_global_existant(), REF, ref_cast, Deriv_::typer(), Scatter::uninit_sequential_domain(), liste::vide(), and zone().
Referenced by Zone_VF::discretiser().
creer_tableau_elements()
void Domaine::creer_tableau_elements (Array_base & v, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Cree un tableau ayant une "ligne" par element du maillage.
Pour l'instant, erreur s'il y a plus d'une zone dans le domaine.
Voir MD_Vector_tools::creer_tableau_distribue()
Definition at line 443 of file Domaine.cpp.
{
// On pourra faire evoluer le code ci-dessous en creant un
// tableau associe a un MD_Vector_composite:
  if (nb_zones() != 1)
    {
      Cerr << "Error in Domaine::creer_tableau_elements(Array_base & v):\n"
           << " Domain does not have exactely 1 zone !" << finl;
      Process::exit();
    }
  zone(0).creer_tableau_elements(v, opt);
}
References Cerr, Zone::creer_tableau_elements(), Process::exit(), finl, nb_zones(), and zone().
Referenced by Zone_EF::calculer_IPhi(), Zone_EF_axi::calculer_IPhi(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Champ_Don_Fonc_txyz::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Sous_Zone::readOn(), Zone_EF_axi::remplir_tableau_origine(), Zone_EF::reordonner(), Zone_Poly_base::reordonner(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC::valeur_aux_elems(), and Champ_Face_PolyMAC::valeur_aux_elems_compo().
creer_tableau_sommets()
void Domaine::creer_tableau_sommets (Array_base & v, Array_base::Resize_Options opt = Array_base::COPY_INIT) const virtual
Cree un tableau ayant une "ligne" par sommet du maillage.
Voir MD_Vector_tools::creer_tableau_distribue()
Definition at line 428 of file Domaine.cpp.
{
  const MD_Vector& md = md_vector_sommets();
  MD_Vector_tools::creer_tableau_distribue(md, v, opt);
}
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_sommets().
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), corriger(), Zone_EF::discretiser(), Zone_VEF_PreP1b::discretiser(), Zone_PolyMAC_P0::fgrad(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Champ_implementation_P1::init_from_file(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Zone_VEF_PreP1b::modifier_pour_Cl(), and Op_Diff_VEFP1NCP1B_Face::test().
deformable() [1/2]
int & Domaine::deformable () inline
Definition at line 100 of file Domaine.h.
  {
    return deformable_;
  };
References deformable_.
deformable() [2/2]
int Domaine::deformable () const inline
Definition at line 96 of file Domaine.h.
  {
    return deformable_;
  };
References deformable_.
Referenced by convert_domain_to_Domaine(), Postraitement::init(), Sonde::mettre_a_jour(), and Postraitement::postraiter_champs().
domaines_frontieres()
const List_Ref_Domaine & Domaine::domaines_frontieres () const inline
Definition at line 131 of file Domaine.h.
  {
    return domaines_frontieres_;
  };
References domaines_frontieres_.
Referenced by Postraiter_domaine::ecrire(), and Format_Post_Lata::ecrire_domaine().
duplique()
int Domaine::duplique () const override virtual
Implements Objet_U.
Reimplemented in Domaine_bord, and DomaineAxi1d.
Definition at line 36 of file Domaine.cpp.
epsilon()
double Domaine::epsilon () const inline
Renvoie epsilon.
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
Returns
double
Signification: la distance a partir de laquelles 2 points
sont confondus
Contraintes:
Definition at line 536 of file Domaine.h.
{
  return epsilon_;
}
References epsilon_.
Referenced by Sonde::ajouter_bords(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Zone::epsilon(), Octree::get_epsilon(), and lecture_special_part2().
fixer_epsilon()
void Domaine::fixer_epsilon (double eps) inline
Fixe epsilon,
Si 2 points d'un domaine sont separes d'une distance
inferieure ou egale a epsilon ils sont consideres egaux.
Definition at line 514 of file Domaine.h.
{
  epsilon_=eps;
}
References epsilon_.
Referenced by Mailler::interpreter_().
get_fichier_lu()
const Nom & Domaine::get_fichier_lu () const inline
Definition at line 113 of file Domaine.h.
  {
    return fichier_lu_;
  };
References fichier_lu_.
get_info()
const Type_info * Domaine::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Domaine_bord, and DomaineAxi1d.
Definition at line 36 of file Domaine.cpp.
get_renum_som_perio()
int Domaine::get_renum_som_perio (int i) const inline
Definition at line 592 of file Domaine.h.
{
  return renum_som_perio[i];
}
References renum_som_perio.
Referenced by add_curl_som(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), assembler(), calcul_longueur_filtre(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Assembleur_P_VEFPreP1B::changer_base_pression(), Assembleur_P_VEFPreP1B::changer_base_pression_inverse(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), chercher_arete(), Zone_VEF_PreP1b::construire_ok_arete(), Zone_VEF_PreP1b::construire_renum_arete_perio(), corriger(), Op_Div_VEFP1B_Elem::degres_liberte(), exemple_champ_non_homogene(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Zone_VEF_PreP1b::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEFPreP1B::modifier_solution(), operation01(), operation11(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), remplir_sommets(), EOS_Tools_VEF::secmembre_divU_Z(), second_membre(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Zone_VEF_PreP1b::verifie_ok_arete(), and verifier().
getBoundingBox()
DoubleTab Domaine::getBoundingBox () const
Definition at line 502 of file Domaine.cpp.
{
  DoubleTab BB(dimension, 2);
  int nbsom=coord_sommets().dimension(0);
  for (int j=0; j<dimension; j++)
    {
      double min_=0.5*DMAXFLOAT;
      double max_=-0.5*DMAXFLOAT;
      for (int i=0; i<nbsom; i++)
        {
          double c = coord_sommets()(i,j);
          min_ = (c < min_ ? c : min_);
          max_ = (c > max_ ? c : max_);
        }
      BB(j,0) = min_;
      BB(j,1) = max_;
    }
  return BB;
}
References coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, and DMAXFLOAT.
Referenced by imprimer(), and Champ_Fonc_MED::readOn().
imprimer()
void Domaine::imprimer () const
Definition at line 522 of file Domaine.cpp.
{
  Cerr << "==============================================" << finl;
  Cerr << "The extreme coordinates of the domain " << le_nom() << " are:" << finl;
// Il n'existe pas de recherche du min et du max dans DoubleTab donc je code:
  DoubleTab BB = getBoundingBox();
  for (int j=0; j<dimension; j++)
    {
      double min_ = mp_min(BB(j,0));
      double max_ = mp_max(BB(j,1));
      if (j==0) Cerr << "x ";
      if (j==1) Cerr << "y ";
      if (j==2) Cerr << "z ";
      Cerr << "is between " << min_ << " and " << max_ << finl;
    }
  Cerr << "==============================================" << finl;
// We recompute volumes (cause stored in Zone_VF and so not available from Domaine...):
  DoubleVect volumes;
  DoubleVect inverse_volumes;
  zone(0).calculer_volumes(volumes,inverse_volumes);
  Cerr << "==============================================" << finl;
  Cerr << "The volume cells of the domain " << le_nom() << " are:" << finl;
  const int i_vmax = imax_array(volumes);
  const int i_vmin = imin_array(volumes);
  const double vmin_local = (i_vmin < 0) ? 1e40 : volumes[i_vmin];
  const double vmax_local = (i_vmax < 0) ? -1e40 : volumes[i_vmax];
  const double volmin = mp_min(vmin_local);
  const double volmax = mp_max(vmax_local);
  double volume_total = mp_somme_vect(volumes);
  const int nb_elem = zone(0).nb_elem();
  double volmoy = volume_total / Process::mp_sum(nb_elem);
  Cerr << "sum(volume cells)= "  << volume_total << finl;
  Cerr << "mean(volume cells)= " << volmoy << finl;
  Cerr << "min(volume cells)= "  << volmin << finl;
  Cerr << "max(volume cells)= "  << volmax << finl;
  if (volmin*1000<volmoy)
    {
      Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
      Cerr << "Warning, a cell volume is more than 1000 times smaller than the average cell volume. Check your mesh." << finl;
      Cerr << "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" << finl;
    }
  Cerr << "==============================================" << finl;
}
References Zone::calculer_volumes(), Cerr, Objet_U::dimension, finl, getBoundingBox(), imax_array(), imin_array(), le_nom(), Process::mp_max(), Process::mp_min(), mp_somme_vect(), Process::mp_sum(), Zone::nb_elem(), and zone().
Referenced by Zone_VF::discretiser(), and Decouper::lire().
info()
const Type_info * Domaine::info () static
Definition at line 36 of file Domaine.cpp.
initialiser()
virtual void Domaine::initialiser (double temps, Domaine_dis & , Probleme_base &) inline virtual
Definition at line 106 of file Domaine.h.
{}
Referenced by Probleme_base::initialize().
le_nom()
const Nom & Domaine::le_nom () const inline override virtual
Renvoie le nom du domaine.
Returns
Nom&
Signification: le nom du domaine
Contraintes: reference constante
Reimplemented from Objet_U.
Definition at line 197 of file Domaine.h.
{
  return nom_;
}
References nom_.
Referenced by Mod_turb_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Champ_implementation_P0::affecter_(), Rectify_Mesh::apply(), Refine_Mesh::apply(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Terme_Boussinesq_base::check(), Reordonner_faces_periodiques::chercher_direction_perio(), Partitionneur_Tranche::chercher_direction_perio(), Faces::compare(), Equation_base::completer(), Sonde::completer(), Champ_front_calc::completer(), Champ_front_contact_VEF::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Interpolation::completer(), Format_Post_Med::completer_post(), Champ_front_contact_VEF::connectivity_failed(), Extruder_en3::construire_bords(), Zone_VEF_PreP1b::construire_ok_arete(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), construire_renum_som_perio(), DomaineCutter::construire_sous_domaine(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_naif(), Champ_Fonc_MED::creer(), Zone::creer_aretes(), Pb_MED::creer_champ(), Postraitement::creer_champ_post(), Postraitement::creer_champ_post_stat(), creer_mes_domaines_frontieres(), DecoupeBord::Decouper(), Op_Div_VEFP1B_Elem::degres_liberte(), Zone_Poly_base::discretiser(), Zone_VEF::discretiser(), Domaine_dis::discretiser(), dump_lata(), Postraiter_domaine::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Med::ecrire_champ_med(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Med::ecrire_domaine_med(), Postraitement_lata::ecrire_zone(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), find_joint_faces(), histogramme_angle(), imprimer(), Zone_VF::info_elem_som(), Zone_VF::infobord(), Postraitement::init(), Zone_Poly_base::init_dist_paroi_globale(), Zone_Poly_base::init_equiv(), Raccord_distant_homogene::initialise(), Sonde::initialiser(), Ecrire_Champ_MED::interpreter(), Integrer_champ_med::interpreter(), MaillerParallel::interpreter(), latatoother::interpreter(), DecoupeBord::interpreter_(), Dilate::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), Lire_Ideas::interpreter_(), NettoieNoeuds::interpreter_(), RegroupeBord::interpreter_(), TroisDto2D::interpreter_(), VerifierCoin::interpreter_(), Zone_VEF_PreP1b::lecture_ok_arete(), Mod_turb_hyd_base::lire_distance_paroi(), ScatterMED::lire_domaine(), Mod_turb_hyd_base::lire_motcle_non_standard(), Zone::md_vector_elements(), NettoieNoeuds::nettoie(), nom_fichier(), Champ_Generique_refChamp::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Zone_PolyMAC::orthocentrer(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), postraiter_decoupage(), Postraitement_lata::postraiter_liste_champs(), Postraitement::postraiter_tableau(), Postraitement::postraiter_tableaux(), Domaine_dis::printOn(), Zone_dis_base::rang_frontiere(), read_vertices(), Sonde::readOn(), readOn(), Champ_Fonc_MED::readOn(), Champ_Fonc_reprise::readOn(), Remove_elem::Remove_elem_(), Champ_front_contact_VEF::remplir_connect_bords(), Equation_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Navier_Stokes_std::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_nul::sauvegarder(), Postraitement::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), Champ_front_contact_VEF::test_faces_coin(), traite_bord(), Champ_implementation_base::valeur_aux_sommets(), Champ_implementation_base::valeur_aux_sommets_compo(), and Echange_contact_VDF::verifier_correspondance().
les_sommets() [1/2]
DoubleTab & Domaine::les_sommets () inline
Renvoie le nombre total de sommets.
Returns
int
Signification: le nombre total de sommets
Contraintes:
Definition at line 556 of file Domaine.h.
{
  return sommets;
}
References sommets.
Referenced by BlocData::add_bloc(), ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), auto_build_joints(), Octree_Zone::build(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), build_triofield(), Ch_front_input::buildSommetsFaces(), Traitement_particulier_NS_THI::calcul_nb_som_dir(), Aretes::calculer_centre_de_gravite(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Navier_Stokes_std::calculer_pression_hydrostatique(), Faces::calculer_surfaces(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Scatter::check_consistancy_remote_items(), Reordonner_faces_periodiques::check_faces_periodiques(), check_internal_diagonal_for_tetrahedron(), check_positive_volumes_for_tetrahedron(), check_positive_volumes_for_triangle(), choose_internal_diagonal_for_tetrahedron(), Champ_Generique_Extraction::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), Zone_VEF_PreP1b::construire_ok_arete(), DomaineCutter::construire_sous_domaine(), Scatter::construire_structures_paralleles(), convert_domain_to_Domaine(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), create_listb_geom(), Remove_elem::creer_faces(), Decouper_Bord_coincident::Decouper_Bord_coincident_(), Zone_VF::discretiser(), Zone_VEF_PreP1b::discretiser_arete(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lml::ecrire_domaine_lml(), Format_Post_Med::ecrire_domaine_med(), Postraitement_lata::ecrire_zone(), ensure_positive_volumes_for_tetrahedron(), ensure_positive_volumes_for_triangle(), entre_faces(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), ExtrudeBord::extruder_hexa_old(), Champ_implementation_Q1::form_function(), get_ref_coordinates_items(), Ch_front_input::getTemplate(), Champ_input_P0::getTemplate(), histogramme_angle(), Zone_VF::info_elem_som(), Zone::init_faces_virt_bord(), Scatter::init_sequential_domain(), Sonde::initialiser(), Integrer_champ_med::interpreter(), Moyenne_volumique::interpreter(), Raffiner_isotrope_parallele::interpreter(), latatoother::interpreter(), Dilate::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), VerifierCoin::interpreter_(), Scatter::lire_domaine(), md_vector_sommets(), NettoieNoeuds::nettoie(), Raffiner_anisotrope::Raffiner_anisotrope_(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), Remove_elem::Remove_elem_(), Champ_implementation_sommet_base::remplir_coord_noeuds(), Champ_implementation_sommet_base::remplir_coord_noeuds_et_polys(), Reordonner_faces_periodiques::renum_som_perio(), Faces::reordonner(), Hexaedre_VEF::reordonner(), Quadrangle_VEF::reordonner(), Hexaedre::reordonner_elem(), Scatter::reordonner_faces_de_joint(), Reordonner_faces_periodiques::reordonner_faces_periodiques(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Q1NC_impl::transforme_coord2D(), Champ_Q1NC_impl::transforme_coord3D(), Transformer::transformer(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Scatter::uninit_sequential_domain(), Refine_Mesh::update_nodes(), Champ_implementation_P1::value_interpolation(), Champ_implementation_Q1::value_interpolation(), and NettoieNoeuds::verifie_noeuds().
les_sommets() [2/2]
const DoubleTab & Domaine::les_sommets () const inline
Renvoie le tableau des sommets du domaine.
Returns
DoubleTab&
Signification: le tableau des sommets du domaine
Contraintes:
Definition at line 575 of file Domaine.h.
{
  return sommets;
}
References sommets.
md_vector_sommets()
const MD_Vector & Domaine::md_vector_sommets () const virtual
Definition at line 434 of file Domaine.cpp.
{
  const MD_Vector& md = les_sommets().get_md_vector();
  return md;
}
References TRUSTVect< _TYPE_ >::get_md_vector(), and les_sommets().
Referenced by Traitement_particulier_NS_THI_new::calcul_nb_som_dir(), creer_tableau_sommets(), Zone_VEF_PreP1b::discretiser_suite(), Champ_Fonc_P1_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Q1_base::fixer_nb_valeurs_nodales(), Champ_Inc_P1_base::fixer_nb_valeurs_nodales(), Champ_Inc_Q1_base::fixer_nb_valeurs_nodales(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Milieu_base::update_rho_cp(), and Debog_Pb::write_geometry_data().
mettre_a_jour()
virtual void Domaine::mettre_a_jour (double temps, Domaine_dis & , Probleme_base &) inline virtual
Definition at line 108 of file Domaine.h.
{}
Referenced by Probleme_base::mettre_a_jour(), and Pb_Dilatable_base::mettre_a_jour().
nb_som()
int Domaine::nb_som () const virtual
Renvoie le nombre de sommets.
Definition at line 177 of file Domaine.cpp.
{
  return sommets.dimension(0);
}
References TRUSTTab< _TYPE_ >::dimension(), and sommets.
Referenced by Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_sommets(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Champ_Generique_Extraction::completer(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_Metis::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_base::corriger_bords_avec_graphe(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), Champ_Fonc_MED::creer(), Domaine_dis::discretiser(), Discr_inst::discretiser_champ_fonc_don(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Lml::ecrire_domaine_lml(), DomaineCutter::ecrire_zones(), Domaine_bord::extraire_domaine_bord(), find_joint_faces(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Postraitement::init(), Champ_implementation_P1::init_from_file(), Scatter::init_sequential_domain(), Decouper_multi::interpreter(), Raffiner_isotrope_parallele::interpreter(), Zone::nb_som(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), printOn(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Reordonner_faces_periodiques::renum_som_perio(), and verifier().
nb_som_tot()
int Domaine::nb_som_tot () const virtual
Renvoie le nombre total de sommets.
Definition at line 170 of file Domaine.cpp.
{
  return sommets.dimension_tot(0);
}
References TRUSTTab< _TYPE_ >::dimension_tot(), and sommets.
Referenced by Op_Dift_VEF_P1NCP1B_Face::ajouter(), DomaineCutter::construire_sous_domaine(), Triangle::contient(), Partitionneur_base::corriger_bords_avec_liste(), Partitionneur_base::corriger_sommets_bord(), Zone_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Champ_Generique_Transformation::get_champ(), Zone_PolyMAC_P0::init_stencils(), DomaineCutter::initialiser(), Distanceparoi::interpreter_(), Extraire_surface::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Zone::nb_som_tot(), Reordonner_faces_periodiques::renum_som_perio(), Op_Diff_VEFP1NCP1B_Face::test(), and verifier().
nb_ss_zones()
int Domaine::nb_ss_zones () const inline
Renvoie le nombre de sous-zone.
Returns
int
Signification: le nombre de sous-zone
Contraintes:
Definition at line 346 of file Domaine.h.
{
  return les_ss_zones.size();
}
References les_ss_zones, and liste::size().
Referenced by Refine_Mesh::build_new_sub_zones_descriptions(), Partitionneur_Sous_Zones::construire_partition(), Domaine_dis::discretiser(), Postraiter_domaine::ecrire(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), and Refine_Mesh::update_sub_zones().
nb_zones()
int Domaine::nb_zones () const inline
Renvoie le nombre de zone du domaine.
Returns
int
Signification: le nombre de zones du domaine
Contraintes:
Definition at line 235 of file Domaine.h.
{
  return les_zones.size();
}
References les_zones, and liste::size().
Referenced by Rectify_Mesh::check_nb_zones(), Refine_Mesh::check_nb_zones(), DomaineCutter::construire_sous_domaine(), creer_tableau_elements(), Domaine_dis::discretiser(), Domaine_bord::extraire_domaine_bord(), Scatter::init_sequential_domain(), DomaineCutter::initialiser(), Interprete_geometrique_base::interpreter(), Decouper_Bord_coincident::interpreter_(), Polyedriser::interpreter_(), Raffiner_anisotrope::interpreter_(), Remove_elem::interpreter_(), Triangulation_base::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Scatter::mergeDomains(), Reorienter_tetraedres::Reorienter(), Reorienter_triangles::Reorienter(), Scatter::uninit_sequential_domain(), and zone().
nommer()
void Domaine::nommer (const Nom & un_nom) inline override virtual
Donne un nom au domaine.
Reimplemented from Objet_U.
Definition at line 216 of file Domaine.h.
{
  nom_=un_nom;
}
References nom_.
Referenced by DomaineCutter::construire_sous_domaine(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), latatoother::interpreter(), Create_domain_from_sous_zone::interpreter_(), and Champ_Fonc_MED::readOn().
numero_sommet()
int Domaine::numero_sommet (int i) const inline
Definition at line 89 of file Domaine.h.
  {
    return i;
  };
Referenced by coord().
printOn()
Sortie & Domaine::printOn (Sortie & s) const override protected virtual
Ecrit le domaine sur un flot de sortie.
On ecrit le nom, les sommets, les zones
et les sous-zones.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Domaine_bord, and DomaineAxi1d.
Definition at line 55 of file Domaine.cpp.
{
  Cerr << "Writing of " << nb_som() << " nodes." << finl;
#ifdef SORT_POUR_DEBOG
  s.setf(ios::scientific);
  s.precision(20);
#endif
  s << nom_ << finl;
  s << sommets;
  s << les_zones;
// s << les_ss_zones;
  return s ;
}
References Cerr, finl, les_zones, nb_som(), nom_, Sortie::precision(), Sortie::setf(), and sommets.
Referenced by DomaineAxi1d::printOn().
read_vertices()
void Domaine::read_vertices (Entree & s)
only read vertices from the stream s
Definition at line 125 of file Domaine.cpp.
{
// Ajout BM: reset de la structure (a pour effet de debloquer la structure parallele)
  sommets.reset();
  renum_som_perio.reset();
  les_zones.vide();
  Nom tmp;
  s >> tmp;
// Si le domaine n'est pas nomme, on prend celui lu
  if (nom_=="??") nom_=tmp;
  Cerr << "Reading domain " << le_nom() << finl;
  s >> sommets;
}
References Cerr, finl, le_nom(), les_zones, nom_, renum_som_perio, TRUSTArray< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::reset(), sommets, and liste::vide().
Referenced by Scatter::readDomainWithoutCollComm().
readOn()
Entree & Domaine::readOn (Entree & s) override protected virtual
Lit les specifications d'un domaine
a partir d'un flot d'entree. Associe les zones
lues au domaine.
Format:
nom_domaine
bloc de lecture des Sommets
bloc de lecture des Zones
bloc de lecture des Sous_Zones
Attention: en parallele, chaque processeur s'attend a lire une strucutre domaine
avec des infos de joint, mais il y a des communications globales.
Pour lire un domaine sur un seul processeur, il faut mettre le processeur dans
un groupe seul.
Reimplemented from Objet_U.
Reimplemented in Domaine_bord, and DomaineAxi1d.
Definition at line 83 of file Domaine.cpp.
{
#ifdef SORT_POUR_DEBOG
  s.setf(ios::scientific);
  s.precision(20);
#endif
// Ajout BM: reset de la structure (a pour effet de debloquer la structure parallele)
  sommets.reset();
  renum_som_perio.reset();
// ne pas faire reset du nom (deja lu)
// pour deformable je ne sais pas...
// Pour les sous_zones je ne sais pas non plus... les_ss_zones.vide();
  les_zones.vide();
  Nom tmp;
  s >> tmp;
// Si le domaine n'est pas nomme, on prend celui lu
  if (nom_=="??") nom_=tmp;
  Cerr << "Reading domain " << le_nom() << finl;
  s >> sommets;
// PL : pas tout a fait exact le nombre affiche de sommets, on compte plusieurs fois les sommets des joints...
  int nbsom = mp_sum(sommets.dimension(0));
  Cerr << " Number of nodes: " << nbsom << finl;
  s >> les_zones;
// s >> les_ss_zones;
  if ( (Process::nproc()==1) && (NettoieNoeuds::NettoiePasNoeuds==0) )
    {
      NettoieNoeuds::nettoie(*this);
      nbsom = mp_sum(sommets.dimension(0));
      Cerr << " Number of nodes after node-cleanup: " << nbsom << finl;
    }
  les_zones.associer_domaine(*this);
// On initialise les descripteurs "sequentiels" (attention, cela bloque le resize des tableaux sommets et elements !)
  Scatter::init_sequential_domain(*this);
  return s;
}
References Zones::associer_domaine(), Cerr, TRUSTTab< _TYPE_ >::dimension(), finl, Scatter::init_sequential_domain(), le_nom(), les_zones, Process::mp_sum(), NettoieNoeuds::nettoie(), NettoieNoeuds::NettoiePasNoeuds, nom_, Process::nproc(), renum_som_perio, TRUSTArray< _TYPE_ >::reset(), TRUSTTab< _TYPE_ >::reset(), sommets, and liste::vide().
reordonner()
void Domaine::reordonner ()
Reordonne les mailles du domaine suivant les
conventions de Trio-U.
Definition at line 406 of file Domaine.cpp.
{
  les_zones.reordonner();
}
References les_zones, and Zones::reordonner().
Referenced by TroisDto2D::extraire_2D(), Reordonner::interpreter_(), Champ_Fonc_MED::readOn(), Pb_MED::readOn(), and Transformer::transformation_complete().
self_cast() [1/2]
const Domaine & Domaine::self_cast (const Objet_U & r) static
Definition at line 36 of file Domaine.cpp.
self_cast() [2/2]
Domaine & Domaine::self_cast (Objet_U & r) static
Definition at line 36 of file Domaine.cpp.
set_dt()
virtual void Domaine::set_dt (double & dt_) inline virtual
Definition at line 107 of file Domaine.h.
{}
Referenced by Probleme_base::initTimeStep().
set_fichier_lu()
void Domaine::set_fichier_lu (Nom & nom) inline
Definition at line 109 of file Domaine.h.
  {
    fichier_lu_=nom;
  };
References fichier_lu_.
Referenced by Raffiner_isotrope_parallele::interpreter(), Scatter::lire_domaine(), and ScatterMED::lire_domaine().
set_renum_som_perio()
void Domaine::set_renum_som_perio (IntTab & renum) inline
Definition at line 121 of file Domaine.h.
  {
    renum_som_perio=renum;
  };
References renum_som_perio.
Referenced by Domaine_dis::discretiser().
ss_zone() [1/4]
Sous_Zone & Domaine::ss_zone (const Nom & un_nom) inline
Renvoie la sous-zone dont le nom est indique en parametre.
Returns
Sous_Zone&
Signification: la sous-zone dont le nom est indique en parametre
Contraintes:
Definition at line 424 of file Domaine.h.
{
  return les_ss_zones(un_nom).valeur();
}
References les_ss_zones, and List_Ref_Sous_Zone::valeur().
ss_zone() [2/4]
const Sous_Zone & Domaine::ss_zone (const Nom & un_nom) const inline
Renvoie la sous-zone dont le nom est indique en parametre.
(version const)
Returns
Sous_Zone&
Signification: la sous-zone dont le nom est indique en parametre
Contraintes: reference constante
Definition at line 405 of file Domaine.h.
{
  return les_ss_zones(un_nom).valeur();
}
References les_ss_zones, and List_Ref_Sous_Zone::valeur().
ss_zone() [3/4]
Sous_Zone & Domaine::ss_zone (int i) inline
Renvoie la i-ieme sous-zone.
Returns
Sous_Zone&
Signification: la i-ieme sous-zone
Contraintes:
Definition at line 385 of file Domaine.h.
{
  return les_ss_zones[i].valeur();
}
References les_ss_zones, and List_Ref_Sous_Zone::valeur().
ss_zone() [4/4]
const Sous_Zone & Domaine::ss_zone (int i) const inline
Renvoie la i-ieme sous-zone.
(version const)
Returns
Sous_Zone&
Signification: la i-ieme sous-zone
Contraintes: reference constante
Definition at line 366 of file Domaine.h.
{
  return les_ss_zones[i].valeur();
}
References les_ss_zones, and List_Ref_Sous_Zone::valeur().
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Refine_Mesh::build_new_sub_zones_descriptions(), Perte_Charge_PolyMAC::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), Partitionneur_Sous_Zones::construire_partition(), Domaine_dis::discretiser(), Postraiter_domaine::ecrire(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Perte_Charge_Singuliere::lire_surfaces(), Interprete_geometrique_base::mettre_a_jour_sous_zone(), Champ_Input_Proto::read(), Champ_Fonc_Tabule_Morceaux::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), and Refine_Mesh::update_sub_zones().
ss_zones()
const List_Ref_Sous_Zone & Domaine::ss_zones () const inline
Definition at line 587 of file Domaine.h.
{
  return les_ss_zones;
}
References les_ss_zones.
Referenced by DomaineCutter::ecrire_zones(), and Create_domain_from_sous_zone::interpreter_().
taille_memoire()
unsigned Domaine::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Domaine_bord, and DomaineAxi1d.
Definition at line 36 of file Domaine.cpp.
zone() [1/4]
Zone & Domaine::zone (const Nom & un_nom) inline
Renvoie la Zone dont le nom est indique en parametre.
Returns
Zone&
Signification: la Zone dont le nom est indique en parametre
Contraintes:
Definition at line 326 of file Domaine.h.
{
  check_domaine(nb_zones());
  return les_zones(un_nom);
}
References check_domaine(), les_zones, and nb_zones().
zone() [2/4]
const Zone & Domaine::zone (const Nom & un_nom) const inline
Renvoie la Zone dont le nom est indique en parametre.
(version const)
Returns
Zone&
Signification: la Zone dont le nom est indique en parametre
Contraintes: reference constante
Definition at line 306 of file Domaine.h.
{
  check_domaine(nb_zones());
  return les_zones(un_nom);
}
References check_domaine(), les_zones, and nb_zones().
zone() [3/4]
Zone & Domaine::zone (int i) inline
Renvoie la i-ieme zone du domaine.
Returns
Zone&
Signification: la i-ieme zone du domaine
Contraintes:
Definition at line 285 of file Domaine.h.
{
  check_domaine(nb_zones());
  return les_zones[i];
}
References check_domaine(), les_zones, and nb_zones().
zone() [4/4]
const Zone & Domaine::zone (int i) const inline
Renvoie la i-ieme zone du domaine.
(version const)
Returns
Zone&
Signification: la i-ieme zone du domaine
Contraintes: reference constante
Definition at line 265 of file Domaine.h.
{
  check_domaine(nb_zones());
  return les_zones[i];
}
References check_domaine(), les_zones, and nb_zones().
Referenced by BlocData::add_bloc(), add_sommets_communs(), Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Refine_Mesh::build_edges(), Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), calculer_elements_voisins_bords(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_sommets(), calculer_liste_complete_aretes_joint(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_cell_type(), Scatter::check_consistancy_remote_items(), check_internal_diagonal(), check_internal_diagonal_for_tetrahedron(), check_positive_volumes(), check_positive_volumes_for_tetrahedron(), check_positive_volumes_for_triangle(), Reordonner_faces_periodiques::chercher_direction_perio(), choose_internal_diagonal(), choose_internal_diagonal_for_tetrahedron(), Champ_Generique_Extraction::completer(), Conds_lim::completer(), compute_cell_qualities(), compute_cell_qualities_for_tetrahedron(), compute_cell_qualities_for_triangle(), Extruder_en3::construire_bords(), Scatter::construire_correspondance_sommets_par_coordonnees(), DomaineCutter::construire_elements_distants_ssdom(), DomaineCutter::construire_faces_bords_ssdom(), DomaineCutter::construire_faces_internes_ssdom(), DomaineCutter::construire_faces_joints_ssdom(), DomaineCutter::construire_faces_raccords_ssdom(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), Scatter::construire_md_vector(), Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Metis::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Sous_Zones::construire_partition(), Partitionneur_Tranche::construire_partition(), Partitionneur_Union::construire_partition(), DomaineCutter::construire_sous_domaine(), Scatter::construire_structures_paralleles(), convert_domain_to_Domaine(), Partitionneur_base::corriger_bords_avec_liste(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_multiperiodique(), Partitionneur_base::corriger_sommets_bord(), create_listb_from_domaine2(), create_listb_from_xyz(), create_listb_geom(), create_listb_naif(), Champ_Fonc_MED::creer(), creer_mes_domaines_frontieres(), creer_tableau_elements(), DecoupeBord::Decouper(), Domaine_dis::discretiser(), Marqueur_Lagrange_base::discretiser(), Discr_inst::discretiser_champ_fonc_don(), Champ_Generique_Interpolation::discretiser_domaine(), dump_lata(), Postraiter_domaine::ecrire(), Format_Post_Lml::ecrire_champ_lml(), Format_Post_Med::ecrire_champ_med(), Format_Post_Lata::ecrire_domaine(), Format_Post_Lata_V1::ecrire_domaine(), Format_Post_Lml::ecrire_domaine_lml(), DomaineCutter::ecrire_zones(), ensure_positive_volumes(), ensure_positive_volumes_for_tetrahedron(), ensure_positive_volumes_for_triangle(), TroisDto2D::extraire_2D(), Domaine_bord::extraire_domaine_bord(), Extraire_surface::extraire_surface(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), ExtrudeBord::extruder_bord(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), ExtrudeBord::extruder_hexa_old(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), histogramme_angle(), Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), imprimer(), Postraitement::init(), Scatter::init_sequential_domain(), Sonde::initialiser(), DomaineCutter::initialiser(), Champ_front_lu::initialiser(), Scatter::interpreter(), Moyenne_volumique::interpreter(), Decouper_multi::interpreter(), Interprete_geometrique_base::interpreter(), MaillerParallel::interpreter(), Raffiner_isotrope_parallele::interpreter(), Calculer_Moments::interpreter_(), Create_domain_from_sous_zone::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), ExtrudeBord::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Tgrid::interpreter_(), Mailler::interpreter_(), Modif_bord_to_raccord::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), RegroupeBord::interpreter_(), SupprimeBord::interpreter_(), TroisDto2D::interpreter_(), VerifierCoin::interpreter_(), Corriger_frontiere_periodique::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Scatter::lire_domaine(), ScatterMED::lire_domaine(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), Mod_turb_hyd_base::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Scatter::mergeDomains(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), mon_construire_correspondance_sommets_par_coordonnees(), NettoieNoeuds::nettoie(), OrienteFacesBord::oriente_faces_bord(), Postraitement_lata::postraiter(), Postraitement::postraiter_champs(), Format_Post_base::postraiter_debug_valeurs_un_instant(), postraiter_decoupage(), Postraitement_lata::postraiter_liste_champs(), Postraitement::postraiter_tableau(), Postraitement::postraiter_tableaux(), RegroupeBord::rassemble_bords(), Debog_Pb::read_geometry_data(), Champ_input_P0::readOn(), Champ_Don_Fonc_txyz::readOn(), Champ_Don_Fonc_xyz::readOn(), Champ_Don_lu::readOn(), Champ_Uniforme_Morceaux::readOn(), Champ_Uniforme_Morceaux_Tabule_Temps::readOn(), Sonde_Int::readOn(), Champ_Fonc_MED::readOn(), Raffiner_Simplexes::refine_domain(), RegroupeBord::regroupe_bord(), Reordonner_faces_periodiques::renum_som_perio(), Scatter::reordonner_faces_de_joint(), Reorienter_tetraedres::Reorienter(), Reorienter_triangles::Reorienter(), Transformer::transformation_complete(), Scatter::uninit_sequential_domain(), Refine_Mesh::update_cells(), Refine_Mesh::update_octree(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_base::valeur_aux_sommets(), Champ_Face_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_base::valeur_aux_sommets_compo(), Champ_Face_implementation::valeur_aux_sommets_compo(), Zone_VEF_PreP1b::verifie_ok_arete(), Transformer::verifie_type_elem(), and Debog_Pb::write_geometry_data().
zones() [1/2]
Zones & Domaine::zones () inline
Definition at line 583 of file Domaine.h.
{
  return les_zones;
}
References les_zones.
zones() [2/2]
const Zones & Domaine::zones () const inline
Definition at line 579 of file Domaine.h.
{
  return les_zones;
}
References les_zones.
Referenced by Lire_Tgrid::interpreter_(), Scatter::lire_domaine(), and Scatter::mergeDomains().
Member Data Documentation
axi1d
int Domaine::axi1d protected
Definition at line 179 of file Domaine.h.
Referenced by Axi1d(), Domaine(), and DomaineAxi1d::DomaineAxi1d().
deformable_
int Domaine::deformable_ protected
Definition at line 171 of file Domaine.h.
Referenced by deformable().
domaines_frontieres_
List_Ref_Domaine Domaine::domaines_frontieres_ protected
Definition at line 164 of file Domaine.h.
Referenced by creer_mes_domaines_frontieres(), and domaines_frontieres().
epsilon_
double Domaine::epsilon_ protected
Definition at line 170 of file Domaine.h.
Referenced by ajouter(), epsilon(), and fixer_epsilon().
fichier_lu_
Nom Domaine::fichier_lu_ protected
Definition at line 172 of file Domaine.h.
Referenced by get_fichier_lu(), and set_fichier_lu().
info_obj
const Type_info Domaine::info_obj static
Definition at line 53 of file Domaine.h.
les_ss_zones
List_Ref_Sous_Zone Domaine::les_ss_zones protected
Definition at line 167 of file Domaine.h.
Referenced by add(), nb_ss_zones(), ss_zone(), and ss_zones().
les_zones
Zones Domaine::les_zones protected
Definition at line 168 of file Domaine.h.
Referenced by add(), comprimer(), nb_zones(), printOn(), read_vertices(), readOn(), reordonner(), zone(), and zones().
nom_
Nom Domaine::nom_ protected
Definition at line 165 of file Domaine.h.
Referenced by le_nom(), nommer(), printOn(), read_vertices(), and readOn().
renum_som_perio
ArrOfInt Domaine::renum_som_perio protected
Definition at line 169 of file Domaine.h.
Referenced by construire_renum_som_perio(), get_renum_som_perio(), read_vertices(), readOn(), and set_renum_som_perio().
sommets
DoubleTab Domaine::sommets protected
Definition at line 166 of file Domaine.h.
Referenced by ajouter(), coord(), coord_sommets(), les_sommets(), nb_som(), nb_som_tot(), printOn(), read_vertices(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Domaine.h
src/Kernel/Geometrie/Domaine.cpp