TRUST: Terme_Source_Canal_perio_VDF_Face Class Reference
Terme_Source_Canal_perio_VDF_Face Class Reference
#include <Terme_Source_Canal_perio_VDF_Face.h>
Public Member Functions
Terme_Source_Canal_perio_VDF_Face ()
~Terme_Source_Canal_perio_VDF_Face ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl) const override
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl) const override
int has_interface_blocs () const override
Public Member Functions inherited from Terme_Source_Canal_perio
Terme_Source_Canal_perio ()
~Terme_Source_Canal_perio () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
DoubleTab & calculer (DoubleTab &resu) const override
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Terme_Source_Canal_perio_VDF_Face & self_cast (Objet_U &)
static const Terme_Source_Canal_perio_VDF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Terme_Source_Canal_perio
static const Type_info * info ()
static Terme_Source_Canal_perio & self_cast (Objet_U &)
static const Terme_Source_Canal_perio & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Terme_Source_Canal_perio
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void calculer_debit (double &) const override
Protected Member Functions inherited from Terme_Source_Canal_perio
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Entree & lire_donnees (Entree &)
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void calculer_debit (double &) const =0
ArrOfDouble source () const
Term source calculation (called by VDF and VEF implementations)
TODO: returning an ArrOfDouble is baaad.
void write_flow_rate (const Nom &ext_nom_source, double debit) const
double compute_heat_flux () const
virtual ArrOfDouble source_convection_diffusion (double debit_e) const
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
Protected Attributes inherited from Terme_Source_Canal_perio
ArrOfDouble dir_source_
int direction_ecoulement_
int velocity_weighting_
Nom bord_periodique_
double surface_bord_
double h
double coeff
double u_etoile
int deb_
double source_
double debnm1_
double debit_ref_
double dernier_temps_calc_
int is_debit_impose_
double debit_impose_
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
Definition at line 41 of file Terme_Source_Canal_perio_VDF_Face.h.
Constructor & Destructor Documentation
Terme_Source_Canal_perio_VDF_Face()
Terme_Source_Canal_perio_VDF_Face::Terme_Source_Canal_perio_VDF_Face ()
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
~Terme_Source_Canal_perio_VDF_Face()
Terme_Source_Canal_perio_VDF_Face::~Terme_Source_Canal_perio_VDF_Face ()
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
Member Function Documentation
ajouter_blocs()
void Terme_Source_Canal_perio_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
Reimplemented in Terme_Source_Canal_perio_VDF_P0.
Definition at line 94 of file Terme_Source_Canal_perio_VDF_Face.cpp.
{
  const Zone_VF& zone_VF = la_zone_VDF.valeur();
  const Zone_Cl_dis_base& zone_Cl_dis = la_zone_Cl_VDF.valeur();
  const IntVect& orientation = la_zone_VDF->orientation();
  const DoubleVect& porosite_surf = zone_VF.porosite_face();
  const DoubleVect& volumes_entrelaces = zone_VF.volumes_entrelaces();
  int ncomp;
  ArrOfDouble s(source());
// Boucle sur les conditions limites pour traiter les faces de bord
  int n_bord,ndeb,nfin;
  for (n_bord=0; n_bord<zone_VF.nb_front_Cl(); n_bord++)
    {
// pour chaque Condition Limite on regarde son type
// Si face de Dirichlet ou de Symetrie on ne fait rien
// Si face de Neumann on calcule la contribution au terme source
      const Cond_lim& la_cl = zone_Cl_dis.les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre,la_cl.valeur())
          ||sub_type(Periodique,la_cl.valeur())
          ||sub_type(Symetrie,la_cl.valeur()))
        {
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          ndeb = le_bord.num_premiere_face();
          nfin = ndeb + le_bord.nb_faces();
          for (int num_face=ndeb; num_face<nfin; num_face++)
            {
              double vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
              ncomp = orientation(num_face);
              secmem(num_face) += s[ncomp]*vol;
            }
        }
      else if ( (sub_type(Dirichlet,la_cl.valeur()))
                ||
                (sub_type(Dirichlet_homogene,la_cl.valeur()))
              )
        {
// do nothing
          ;
        }
    }
// Boucle sur les faces internes
  ndeb = zone_VF.premiere_face_int();
  int nb_faces = zone_VF.nb_faces();
  for (int num_face = ndeb; num_face<nb_faces; num_face++)
    {
      double vol = volumes_entrelaces(num_face)*porosite_surf(num_face);
      ncomp = orientation(num_face);
      secmem(num_face)+= s[ncomp]*vol;
    }
}
References Cond_lim::frontiere_dis(), la_zone_Cl_VDF, la_zone_VDF, Zone_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, Terme_Source_Canal_perio::source(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), and Zone_VF::volumes_entrelaces().
associer_zones()
void Terme_Source_Canal_perio_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) override protected virtual
Implements Source_base.
Definition at line 87 of file Terme_Source_Canal_perio_VDF_Face.cpp.
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
calculer_debit()
void Terme_Source_Canal_perio_VDF_Face::calculer_debit (double & debit_e) const override protected virtual
Implements Terme_Source_Canal_perio.
Definition at line 154 of file Terme_Source_Canal_perio_VDF_Face.cpp.
{
  const Zone_VF& zone_VF = la_zone_VDF.valeur();
  const Zone_Cl_dis_base& zone_Cl_dis = la_zone_Cl_VDF.valeur();
  const DoubleTab& vitesse = equation().inconnue().valeurs();
  const DoubleVect& porosite_surf = zone_VF.porosite_face();
  int ndeb,nfin,num_face;
  int nb_bords = zone_VF.nb_front_Cl();
  for (int n_bord=0; n_bord<nb_bords; n_bord++)
    {
      const Cond_lim& la_cl = zone_Cl_dis.les_conditions_limites(n_bord);
      if (sub_type(Periodique,la_cl.valeur()))
        {
          const Periodique& perio = ref_cast(Periodique,la_cl.valeur());
          const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
          if (bord_periodique_ == le_bord.le_nom())
            {
              int axe = perio.direction_periodicite();
              assert(axe==direction_ecoulement_);
              debit_e=0.;
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces()/2;
              if (equation().probleme().is_dilatable()==1)
                {
// Si l'on est en Quasi/Weakly Compressible, il faut conserver
// le debit massique et non pas le debit volumique.
// C'est pour cela que dans le cas QC/WC, on multiplie les vecteurs vitesse
// par la masse volumique discretisee aux faces pour que lorsqu'on integre sur la surface,
// on obtienne bien un debit massique et non pas un debit volumique.
                  const DoubleTab& tab_rho_face = ref_cast(Fluide_Dilatable_base,equation().milieu()).rho_discvit();
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      double debit_face = porosite_surf[num_face]*vitesse[num_face] * std::fabs(zone_VF.face_normales(num_face,axe));
                      debit_e += tab_rho_face[num_face] * debit_face;
                    }
                }
              else
                {
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      double debit_face = porosite_surf[num_face]*vitesse[num_face] * std::fabs(zone_VF.face_normales(num_face,axe));
                      debit_e += debit_face;
                    }
                }
            }
        }
    }
  debit_e = mp_sum(debit_e);
}
References Terme_Source_Canal_perio::bord_periodique_, Terme_Source_Canal_perio::direction_ecoulement_, Periodique::direction_periodicite(), MorEqn::equation(), Zone_VF::face_normales(), Cond_lim::frontiere_dis(), Equation_base::inconnue(), la_zone_Cl_VDF, la_zone_VDF, Frontiere_dis_base::le_nom(), Zone_Cl_dis_base::les_conditions_limites(), Process::mp_sum(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Zone_VF::porosite_face(), ref_cast, sub_type, Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VDF::valeur(), Ref_Zone_VDF::valeur(), and Champ_Inc::valeurs().
cree_instance()
Objet_U * Terme_Source_Canal_perio_VDF_Face::cree_instance () static
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
dimensionner_blocs()
void Terme_Source_Canal_perio_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
Definition at line 46 of file Terme_Source_Canal_perio_VDF_Face.h.
{}
duplique()
int Terme_Source_Canal_perio_VDF_Face::duplique () const override virtual
Implements Objet_U.
Reimplemented in Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, and Terme_Source_Canal_perio_VDF_P0.
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
get_info()
const Type_info * Terme_Source_Canal_perio_VDF_Face::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, and Terme_Source_Canal_perio_VDF_P0.
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
has_interface_blocs()
int Terme_Source_Canal_perio_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
Definition at line 48 of file Terme_Source_Canal_perio_VDF_Face.h.
  {
    return 1;
  };
info()
const Type_info * Terme_Source_Canal_perio_VDF_Face::info () static
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
printOn()
Sortie & Terme_Source_Canal_perio_VDF_Face::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, and Terme_Source_Canal_perio_VDF_P0.
Definition at line 73 of file Terme_Source_Canal_perio_VDF_Face.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
readOn()
Entree & Terme_Source_Canal_perio_VDF_Face::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Terme_Source_Canal_perio.
Reimplemented in Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, and Terme_Source_Canal_perio_VDF_P0.
Definition at line 82 of file Terme_Source_Canal_perio_VDF_Face.cpp.
{
  return Terme_Source_Canal_perio::lire_donnees(s);
}
References Terme_Source_Canal_perio::lire_donnees().
Referenced by Terme_Source_Canal_perio_VDF_P0::readOn().
self_cast() [1/2]
const Terme_Source_Canal_perio_VDF_Face & Terme_Source_Canal_perio_VDF_Face::self_cast (const Objet_U & r) static
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
self_cast() [2/2]
Terme_Source_Canal_perio_VDF_Face & Terme_Source_Canal_perio_VDF_Face::self_cast (Objet_U & r) static
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
taille_memoire()
unsigned Terme_Source_Canal_perio_VDF_Face::taille_memoire () const override virtual
Implements Objet_U.
Reimplemented in Terme_Source_Canal_perio_QC_VDF_Face, Terme_Source_Canal_perio_VDF_Front_Tracking, and Terme_Source_Canal_perio_VDF_P0.
Definition at line 68 of file Terme_Source_Canal_perio_VDF_Face.cpp.
Member Data Documentation
info_obj
const Type_info Terme_Source_Canal_perio_VDF_Face::info_obj static
Definition at line 43 of file Terme_Source_Canal_perio_VDF_Face.h.
la_zone_Cl_VDF
Ref_Zone_Cl_VDF Terme_Source_Canal_perio_VDF_Face::la_zone_Cl_VDF protected
Definition at line 55 of file Terme_Source_Canal_perio_VDF_Face.h.
Referenced by ajouter_blocs(), associer_zones(), and calculer_debit().
la_zone_VDF
Ref_Zone_VDF Terme_Source_Canal_perio_VDF_Face::la_zone_VDF protected
Definition at line 54 of file Terme_Source_Canal_perio_VDF_Face.h.
Referenced by ajouter_blocs(), Terme_Source_Canal_perio_VDF_P0::ajouter_blocs(), associer_zones(), and calculer_debit().
The documentation for this class was generated from the following files:
src/VDF/Sources/Terme_Source_Canal_perio_VDF_Face.h
src/VDF/Sources/Terme_Source_Canal_perio_VDF_Face.cpp