TRUST: Perte_Charge_VDF_Face Class Reference
Perte_Charge_VDF_Face Class Reference
class Perte_Charge_VDF_Face
#include <Perte_Charge_VDF_Face.h>
Public Member Functions
Perte_Charge_VDF_Face ()
~Perte_Charge_VDF_Face ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void associer_pb (const Probleme_base &)
void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Perte_Charge_VDF_Face & self_cast (Objet_U &)
static const
Perte_Charge_VDF_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &)
Protected Attributes
Ref_Champ_Face la_vitesse
Ref_Fluide_base le_fluide
Ref_Zone_VDF la_zone_VDF
Ref_Zone_Cl_VDF la_zone_Cl_VDF
IntVect num_faces
DoubleVect corr_front_ss
Detailed Description
class Perte_Charge_VDF_Face
See also:
Source_base
Definition at line 46 of file Perte_Charge_VDF_Face.h.
Constructor & Destructor Documentation
Perte_Charge_VDF_Face::Perte_Charge_VDF_Face ()
Definition at line 31 of file Perte_Charge_VDF_Face.cpp.
Perte_Charge_VDF_Face::~Perte_Charge_VDF_Face ()
Definition at line 31 of file Perte_Charge_VDF_Face.cpp.
Member Function Documentation
void Perte_Charge_VDF_Face::associer_pb (const Probleme_base & pb) [virtual]
Implements Source_base.
Definition at line 61 of file Perte_Charge_VDF_Face.cpp.
References associer_zones(), Cerr, Probleme_base::equation(), Process::exit(), finl, Equation_base::inconnue(), la_vitesse, le_fluide, Equation_base::milieu(), Probleme_base::nombre_d_equations(), ref_cast, sub_type, Deriv_Champ_Inc_base::valeur(), Equation_base::zone_Cl_dis(), and Equation_base::zone_dis().
{
  int nb_eqn = pb.nombre_d_equations();
  int ok=0;
  for (int i=0; i<nb_eqn; i++)
    {
      const Equation_base& eqn = pb.equation(i);
      if  (sub_type(Navier_Stokes_std,eqn))
        {
          la_vitesse = ref_cast(Champ_Face,eqn.inconnue().valeur());
          le_fluide = ref_cast(Fluide_base,eqn.milieu());
          associer_zones(eqn.zone_dis(),eqn.zone_Cl_dis());
          i = nb_eqn;
          ok = 1;
        }
    }
  if (!ok)
    {
      Cerr << "Erreur TRUST dans Perte_Charge_VDF_Face::associer_pb()" << finl;
      Cerr << "On ne trouve pas d'equation d'hydraulique dans le probleme" << finl;
      Process::exit();
    }
}
void Perte_Charge_VDF_Face::associer_zones (const Zone_dis & zone_dis, const Zone_Cl_dis & zone_Cl_dis) [protected, virtual]
Implements Source_base.
Definition at line 86 of file Perte_Charge_VDF_Face.cpp.
References la_zone_Cl_VDF, la_zone_VDF, ref_cast, Deriv_Zone_Cl_dis_base::valeur(), and Deriv_Zone_dis_base::valeur().
Referenced by associer_pb().
{
  la_zone_VDF = ref_cast(Zone_VDF, zone_dis.valeur());
  la_zone_Cl_VDF = ref_cast(Zone_Cl_VDF, zone_Cl_dis.valeur());
}
virtual int Perte_Charge_VDF_Face::duplique () const [pure virtual]
Implements Source_dep_inco_base.
Implemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
const Type_info * Perte_Charge_VDF_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 31 of file Perte_Charge_VDF_Face.cpp.
const Type_info * Perte_Charge_VDF_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 31 of file Perte_Charge_VDF_Face.cpp.
void Perte_Charge_VDF_Face::mettre_a_jour (double temps) [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Reimplemented in Perte_Charge_Singuliere_VDF_Face.
Definition at line 54 of file Perte_Charge_VDF_Face.h.
  {
    ;
  }
Sortie & Perte_Charge_VDF_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 37 of file Perte_Charge_VDF_Face.cpp.
{
  return s ;
}
Entree & Perte_Charge_VDF_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 46 of file Perte_Charge_VDF_Face.cpp.
{
  return s ;
}
const Perte_Charge_VDF_Face & Perte_Charge_VDF_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 31 of file Perte_Charge_VDF_Face.cpp.
Perte_Charge_VDF_Face & Perte_Charge_VDF_Face::self_cast (Objet_U & r) [static]
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 31 of file Perte_Charge_VDF_Face.cpp.
Member Data Documentation
DoubleVect Perte_Charge_VDF_Face::corr_front_ss [protected]
Definition at line 66 of file Perte_Charge_VDF_Face.h.
Referenced by Perte_Charge_Reguliere_VDF_Face::ajouter_(), and Perte_Charge_Reguliere_VDF_Face::remplir_num_faces().
const Type_info Perte_Charge_VDF_Face::info_obj [static]
Reimplemented from Source_dep_inco_base.
Reimplemented in Perte_Charge_Reguliere_QC_VDF_Face, Perte_Charge_Singuliere_QC_VDF_Face, Perte_Charge_Reguliere_VDF_Face, and Perte_Charge_Singuliere_VDF_Face.
Definition at line 49 of file Perte_Charge_VDF_Face.h.
Ref_Champ_Face Perte_Charge_VDF_Face::la_vitesse [protected]
Definition at line 61 of file Perte_Charge_VDF_Face.h.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), associer_pb(), and Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec().
Ref_Zone_Cl_VDF Perte_Charge_VDF_Face::la_zone_Cl_VDF [protected]
Definition at line 64 of file Perte_Charge_VDF_Face.h.
Referenced by associer_zones().
Ref_Zone_VDF Perte_Charge_VDF_Face::la_zone_VDF [protected]
Definition at line 63 of file Perte_Charge_VDF_Face.h.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), associer_zones(), and Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec().
Ref_Fluide_base Perte_Charge_VDF_Face::le_fluide [protected]
Definition at line 62 of file Perte_Charge_VDF_Face.h.
Referenced by Perte_Charge_Reguliere_VDF_Face::ajouter_(), and associer_pb().
IntVect Perte_Charge_VDF_Face::num_faces [protected]
Definition at line 65 of file Perte_Charge_VDF_Face.h.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Perte_Charge_Singuliere_VDF_Face::contribuer_a_avec(), Perte_Charge_Singuliere_VDF_Face::mettre_a_jour(), Perte_Charge_Singuliere_VDF_Face::remplir_num_faces(), and Perte_Charge_Reguliere_VDF_Face::remplir_num_faces().
The documentation for this class was generated from the following files:
src/VDF/Sources/Perte_Charge_VDF_Face.h
src/VDF/Sources/Perte_Charge_VDF_Face.cpp