TRUST: ArrOfBit Class Reference
ArrOfBit Class Reference
#include <ArrOfBit.h>
Public Member Functions
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
ArrOfBit (int n=0)
Constructeur d'un tableau de taille n, non initialise.
ArrOfBit (const ArrOfBit &array)
Constructeur par copie.
~ArrOfBit () override
Destructeur.
ArrOfBit & operator= (const ArrOfBit &array)
Operateur copie.
ArrOfBit & operator= (int i)
Si la valeur est non nulle, met la valeur 1 dans
tous les elements du tableau, sinon met la valeur 0.
int operator[] (int i) const
Renvoie 1 si le bit e est mis, 0 sinon.
void setbit (int i) const
Met le bit e a 1.
int testsetbit (int i) const
Renvoie la valeur du bit e, puis met le bit e a 1.
void clearbit (int i) const
Met le bit e a 0.
int size_array () const
Renvoie la taille du tableau en bits.
ArrOfBit & resize_array (int n)
Change la taille du tableau et copie les donnees
existantes. Si la taille est plus petite, les donnees sont
tronquees, et si la taille est plus grande, les nouveaux elements
ne sont pas initialises.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static ArrOfBit & self_cast (Objet_U &)
static const ArrOfBit & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture du tableau. Format:
n
0 1 0 0 1 0 ... (n valeurs)
Entree & readOn (Entree &) override
Lecture du tableau. Format:
n
0 1 0 0 1 0 ... (n valeurs)
int calculer_int_size (int taille) const
Taille en "int" du tableau requis pour stocker un tableau de bits
de taille donnees.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int taille
unsigned int * data
Static Protected Attributes
static const unsigned int SIZE_OF_INT_BITS = 5
static const unsigned int DRAPEAUX_INT = 31
Detailed Description
Definition at line 22 of file ArrOfBit.h.
Constructor & Destructor Documentation
ArrOfBit() [1/2]
ArrOfBit::ArrOfBit (int n = 0)
Constructeur d'un tableau de taille n, non initialise.
Definition at line 25 of file ArrOfBit.cpp.
{
  taille = 0;
  data = 0;
  resize_array(n);
}
References data, resize_array(), and taille.
ArrOfBit() [2/2]
ArrOfBit::ArrOfBit (const ArrOfBit & array)
Constructeur par copie.
Constructeur par copie (deep copy)
Definition at line 41 of file ArrOfBit.cpp.
                                       :Objet_U(array)
{
  taille = 0;
  data = 0;
  operator=(array);
}
References data, operator=(), and taille.
~ArrOfBit()
ArrOfBit::~ArrOfBit () override
Destructeur.
Definition at line 33 of file ArrOfBit.cpp.
{
  if (data)
    delete[] data;
  data = 0;
}
References data.
Member Function Documentation
calculer_int_size()
int ArrOfBit::calculer_int_size (int taille) const protected
Taille en "int" du tableau requis pour stocker un tableau de bits
de taille donnees.
Definition at line 51 of file ArrOfBit.cpp.
{
  assert(la_taille >= 0);
  int siz = la_taille >> SIZE_OF_INT_BITS;
  if (la_taille & DRAPEAUX_INT)
    siz++;
  return siz;
}
References DRAPEAUX_INT, and SIZE_OF_INT_BITS.
Referenced by operator=(), and resize_array().
clearbit()
void ArrOfBit::clearbit (int i) const inline
Met le bit e a 0.
Definition at line 78 of file ArrOfBit.h.
{
  assert(e >= 0 && e < taille);
  unsigned int i = (unsigned int) e;
  unsigned int flag = 1 << (i & DRAPEAUX_INT);
  data[i >> SIZE_OF_INT_BITS] &= ~flag;
}
References data, DRAPEAUX_INT, SIZE_OF_INT_BITS, and taille.
Referenced by clearflag(), and Scatter::corriger_espace_distant_elements_perio().
cree_instance()
Objet_U * ArrOfBit::cree_instance () static
Definition at line 19 of file ArrOfBit.cpp.
duplique()
int ArrOfBit::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file ArrOfBit.cpp.
get_info()
const Type_info * ArrOfBit::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 19 of file ArrOfBit.cpp.
info()
const Type_info * ArrOfBit::info () static
Definition at line 19 of file ArrOfBit.cpp.
operator=() [1/2]
ArrOfBit & ArrOfBit::operator= (const ArrOfBit & array)
Operateur copie.
Operateur copie (deep copy).
Definition at line 93 of file ArrOfBit.cpp.
{
  int newsize = calculer_int_size(array.taille);
  if (taille != array.taille)
    {
      if (data)
        {
          delete[] data;
          data = 0;
        }
      if (newsize > 0)
        data = new unsigned int[newsize];
    }
  taille = array.taille;
  if (taille)
    memcpy(data, array.data, newsize * sizeof(unsigned int));
  return *this;
}
References calculer_int_size(), data, and taille.
Referenced by ArrOfBit(), and readOn().
operator=() [2/2]
ArrOfBit & ArrOfBit::operator= (int i)
Si la valeur est non nulle, met la valeur 1 dans
tous les elements du tableau, sinon met la valeur 0.
Definition at line 115 of file ArrOfBit.cpp.
{
  unsigned int valeur = val ? (~((unsigned int) 0)) : 0;
  int size = calculer_int_size(taille);
  int i;
  for (i = 0; i < size; i++)
    data[i] = valeur;
  return *this;
}
References calculer_int_size(), data, taille, and valeur().
operator[]()
int ArrOfBit::operator[] (int i) const inline
Renvoie 1 si le bit e est mis, 0 sinon.
Definition at line 46 of file ArrOfBit.h.
{
  assert(e >= 0 && e < taille);
  unsigned int i = (unsigned int) e;
  unsigned int x = data[i >> SIZE_OF_INT_BITS];
  unsigned int flag = 1 << (i & DRAPEAUX_INT);
  int resultat = ((x & flag) != 0) ? 1 : 0;
  return resultat;
}
References data, DRAPEAUX_INT, SIZE_OF_INT_BITS, and taille.
Referenced by printOn().
printOn()
Sortie & ArrOfBit::printOn (Sortie & x) const override protected virtual
Ecriture du tableau. Format:
n
0 1 0 0 1 0 ... (n valeurs)
Reimplemented from Objet_U.
Definition at line 128 of file ArrOfBit.cpp.
{
  os << taille << finl;
  int i;
// Un retour a la ligne tous les 32 bits,
// Une espace tous les 8 bits
  for (i = 0; i < taille; i++)
    {
      os << operator[](i);
      if ((i & 7) == 7)
        os << space;
      if ((i & 31) == 31)
        os << finl;
    }
// Un retour a la ligne si la derniere ligne n'etait pas terminee
  if (i & 31)
    os << finl;
  return os;
}
References finl, operator[](), space, and taille.
readOn()
Entree & ArrOfBit::readOn (Entree & is) override protected virtual
Lecture du tableau. Format:
n
0 1 0 0 1 0 ... (n valeurs)
Reimplemented from Objet_U.
Definition at line 151 of file ArrOfBit.cpp.
{
  int newsize;
  is >> newsize;
  resize_array(newsize);
  operator=(0);
  int i;
  for (i = 0; i < taille; i++)
    {
      int bit;
      is >> bit;
      if (bit) setbit(i);
    }
  return is;
}
References operator=(), resize_array(), setbit(), and taille.
resize_array()
ArrOfBit & ArrOfBit::resize_array (int n)
Change la taille du tableau et copie les donnees
existantes. Si la taille est plus petite, les donnees sont
tronquees, et si la taille est plus grande, les nouveaux elements
ne sont pas initialises.
< data!=0 sinon taille==n et on ne serait pas ici
Definition at line 64 of file ArrOfBit.cpp.
{
  if (taille == n)
    return *this;
  assert(n >= 0);
  if (n > 0)
    {
      int oldsize = calculer_int_size(taille);
      int newsize = calculer_int_size(n);
      unsigned int * newdata = new unsigned int[newsize];
      int size_copy = (newsize > oldsize) ? oldsize : newsize;
      if (size_copy)
        {
          memcpy(newdata, data, size_copy);
          delete[] data;
        }
      data = newdata;
      taille = n;
    }
  else
    {
      delete[] data; //!< data!=0 sinon taille==n et on ne serait pas ici
      data = 0;
      taille = 0;
    }
  return *this;
}
References calculer_int_size(), data, and taille.
Referenced by ArrOfBit(), MD_Vector_tools::get_sequential_items_flags(), and readOn().
self_cast() [1/2]
const ArrOfBit & ArrOfBit::self_cast (const Objet_U & r) static
Definition at line 19 of file ArrOfBit.cpp.
self_cast() [2/2]
ArrOfBit & ArrOfBit::self_cast (Objet_U & r) static
Definition at line 19 of file ArrOfBit.cpp.
setbit()
void ArrOfBit::setbit (int i) const inline
Met le bit e a 1.
Definition at line 57 of file ArrOfBit.h.
{
  assert(e >= 0 && e < taille);
  unsigned int i = (unsigned int) e;
  unsigned int flag = 1 << (i & DRAPEAUX_INT);
  data[i >> SIZE_OF_INT_BITS] |= flag;
}
References data, DRAPEAUX_INT, SIZE_OF_INT_BITS, and taille.
Referenced by Matrice_Morse::check_morse_matrix_structure(), Matrice_Morse::check_sorted_morse_matrix_structure(), DomaineCutter::construire_faces_joints_ssdom(), Scatter::corriger_espace_distant_elements_perio(), Partitionneur_base::corriger_sommets_bord(), find_joint_faces(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), parcourir_epaisseurs_elements(), and readOn().
size_array()
int ArrOfBit::size_array () const inline
Renvoie la taille du tableau en bits.
Definition at line 87 of file ArrOfBit.h.
{
  return taille;
}
References taille.
Referenced by Zone_VEF_PreP1b::construire_ok_arete(), ecrit(), and Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry().
taille_memoire()
unsigned ArrOfBit::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file ArrOfBit.cpp.
testsetbit()
int ArrOfBit::testsetbit (int i) const inline
Renvoie la valeur du bit e, puis met le bit e a 1.
Definition at line 66 of file ArrOfBit.h.
{
  assert(e >= 0 && e < taille);
  unsigned int i = (unsigned int) e;
  unsigned int flag = 1 << (i & DRAPEAUX_INT);
  int index = i >> SIZE_OF_INT_BITS;
  unsigned int old = data[index];
  data[index] = old | flag;
  return ((old & flag) != 0) ? 1 : 0;
}
References data, DRAPEAUX_INT, SIZE_OF_INT_BITS, and taille.
Referenced by Raccord_distant_homogene::completer(), compute_global_connex_components(), DomaineCutter::construire_faces_joints_ssdom(), construire_liste_sommets_sousdomaine(), Scatter::construire_md_vector(), Corriger_frontiere_periodique::corriger_coordonnees_sommets_perio(), Scatter::corriger_espace_distant_elements_perio(), parcourir_epaisseurs_elements(), Champ_Don_Face_lu::readOn(), and Octree_Int::search_elements_box_floor().
Member Data Documentation
data
unsigned int* ArrOfBit::data protected
Definition at line 40 of file ArrOfBit.h.
Referenced by ArrOfBit(), clearbit(), operator=(), operator[](), resize_array(), setbit(), testsetbit(), and ~ArrOfBit().
DRAPEAUX_INT
const unsigned int ArrOfBit::DRAPEAUX_INT = 31 static protected
Definition at line 42 of file ArrOfBit.h.
Referenced by calculer_int_size(), clearbit(), operator[](), setbit(), and testsetbit().
info_obj
const Type_info ArrOfBit::info_obj static
Definition at line 24 of file ArrOfBit.h.
SIZE_OF_INT_BITS
const unsigned int ArrOfBit::SIZE_OF_INT_BITS = 5 static protected
Definition at line 41 of file ArrOfBit.h.
Referenced by calculer_int_size(), clearbit(), operator[](), setbit(), and testsetbit().
taille
int ArrOfBit::taille protected
Definition at line 39 of file ArrOfBit.h.
Referenced by ArrOfBit(), clearbit(), operator=(), operator[](), printOn(), readOn(), resize_array(), setbit(), size_array(), and testsetbit().
The documentation for this class was generated from the following files:
src/Kernel/Math/ArrOfBit.h
src/Kernel/Math/ArrOfBit.cpp