TRUST: Ecrire_Champ_MED Class Reference
Ecrire_Champ_MED Class Reference
classe Ecrire_Champ_MED
#include <Ecrire_Champ_MED.h>
Public Member Functions
Ecrire_Champ_MED ()
~Ecrire_Champ_MED ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Fonction principale de l'interprete Ecrire_Champ_MED:
erreur si cela echoue.
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Ecrire_Champ_MED & self_cast (Objet_U &)
static const Ecrire_Champ_MED & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Entree & readOn (Entree &) override
Simple appel a:
Interprete::readOn(Entree&)
Ecrit l'interprete sur un flot d'entree.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
classe Ecrire_Champ_MED
Definition at line 31 of file Ecrire_Champ_MED.h.
Constructor & Destructor Documentation
Ecrire_Champ_MED()
Ecrire_Champ_MED::Ecrire_Champ_MED ()
Definition at line 21 of file Ecrire_Champ_MED.cpp.
~Ecrire_Champ_MED()
Ecrire_Champ_MED::~Ecrire_Champ_MED ()
Definition at line 21 of file Ecrire_Champ_MED.cpp.
Member Function Documentation
cree_instance()
Objet_U * Ecrire_Champ_MED::cree_instance () static
Definition at line 21 of file Ecrire_Champ_MED.cpp.
duplique()
int Ecrire_Champ_MED::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Ecrire_Champ_MED.cpp.
get_info()
const Type_info * Ecrire_Champ_MED::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Ecrire_Champ_MED.cpp.
info()
const Type_info * Ecrire_Champ_MED::info () static
Definition at line 21 of file Ecrire_Champ_MED.cpp.
interpreter()
Entree & Ecrire_Champ_MED::interpreter (Entree & is) override virtual
Fonction principale de l'interprete Ecrire_Champ_MED:
erreur si cela echoue.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Interprete.
Definition at line 88 of file Ecrire_Champ_MED.cpp.
{
  Nom nom_domaine, nom_champ,nom_fic;
  is >> nom_domaine >> nom_champ >> nom_fic;
  Objet_U& obj_champ=objet(nom_champ);
  if (!sub_type(Champ_Don_base, obj_champ))
    {
      Cerr << "The field "<< nom_champ << " is not of type Champ_Don" << finl;
      Process::exit();
    }
  Champ_Don_base& chp = ref_cast(Champ_Don_base,obj_champ);
  /*  EcrMED ecrmed;
      ecrmed.ecrire_domaine(nom_fic,dom,nom_domaine);
      ecrmed.ecrire_champ("CHAMPMAILLE",nom_fic,nom_domaine,"critere",const DoubleTab&val,const Noms& unite,const Nom& type_elem,double time,int compteur)
  */
  Objet_U& obj_dom=objet(nom_domaine);
  const Domaine& dom = ref_cast(Domaine,obj_dom);
  Format_Post post_typer;
  post_typer.typer_direct("format_post_med");
  Format_Post_base& post=ref_cast(Format_Post_base,post_typer.valeur());
  Nom nom_fic2(nom_fic);
  nom_fic2.prefix(".med");
  post.initialize_by_default(nom_fic2);
  int est_le_premier_post=1;
  post.ecrire_entete(0.,0,est_le_premier_post);
  int reprise = 0;
  double t_init = 0.;
// ecriture domaine
  post.preparer_post(dom.le_nom(),est_le_premier_post,reprise,t_init);
  post.ecrire_domaine(dom, est_le_premier_post);
  double tps=chp.temps();
  post.ecrire_temps(tps);
  post.init_ecriture(tps,-1.,est_le_premier_post,dom);
  chp.corriger_unite_nom_compo();
// ecriture champ
// chp.postraiter_champ(dom, tps, nom_champ, "ELEM", post);
// la nature ne sert pas en MED
  Nom Nature("pas_defini");
  post.ecrire_champ(dom,chp.unites(),chp.noms_compo(),-1,tps,tps,Motcle(chp.le_nom()),dom.le_nom(),Motcle("elem"),Nature,chp.valeurs());
  int fin=1;
  post.finir(fin);
  return is;
}
References Cerr, Champ_base::corriger_unite_nom_compo(), Format_Post_base::ecrire_champ(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_temps(), Process::exit(), Format_Post_base::finir(), finl, Format_Post_base::init_ecriture(), Format_Post_base::initialize_by_default(), Field_base::le_nom(), Domaine::le_nom(), Field_base::noms_compo(), Interprete::objet(), Nom::prefix(), Format_Post_base::preparer_post(), ref_cast, sub_type, Champ_base::temps(), Format_Post::typer_direct(), Field_base::unites(), Deriv_Format_Post_base::valeur(), and Champ_Don_base::valeurs().
printOn()
Sortie & Ecrire_Champ_MED::printOn (Sortie & os) const override protected virtual
Simple appel a:
Interprete::printOn(Sortie&)
Imprime l'interprete sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 40 of file Ecrire_Champ_MED.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Ecrire_Champ_MED::readOn (Entree & is) override protected virtual
Simple appel a:
Interprete::readOn(Entree&)
Ecrit l'interprete sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 62 of file Ecrire_Champ_MED.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Ecrire_Champ_MED & Ecrire_Champ_MED::self_cast (const Objet_U & r) static
Definition at line 21 of file Ecrire_Champ_MED.cpp.
self_cast() [2/2]
Ecrire_Champ_MED & Ecrire_Champ_MED::self_cast (Objet_U & r) static
Definition at line 21 of file Ecrire_Champ_MED.cpp.
taille_memoire()
unsigned Ecrire_Champ_MED::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Ecrire_Champ_MED.cpp.
Member Data Documentation
info_obj
const Type_info Ecrire_Champ_MED::info_obj static
Definition at line 33 of file Ecrire_Champ_MED.h.
The documentation for this class was generated from the following files:
src/Kernel/MEDimpl/Ecrire_Champ_MED.h
src/Kernel/MEDimpl/Ecrire_Champ_MED.cpp