TRUST: Vect_MD_Vector Class Reference
Vect_MD_Vector Class Reference
#include <VectMD_Vector.h>
Public Member Functions
Vect_MD_Vector ()
int size () const
Vect_MD_Vector (int)
const MD_Vector & operator[] (int) const
MD_Vector & operator[] (int)
Vect_MD_Vector (const Vect_MD_Vector &)
virtual ~Vect_MD_Vector ()
Vect_MD_Vector & operator= (const Vect_MD_Vector &)
Vect_MD_Vector & add (const MD_Vector &)
Protected Attributes
int sz
MD_Vector * data
Detailed Description
Definition at line 92 of file VectMD_Vector.h.
Constructor & Destructor Documentation
Vect_MD_Vector::Vect_MD_Vector ()
Definition at line 26 of file MD_Vector_composite.cpp.
: public MD_Vector_std
Vect_MD_Vector::Vect_MD_Vector (int)
Vect_MD_Vector::Vect_MD_Vector (const Vect_MD_Vector & vect)
Definition at line 26 of file MD_Vector_composite.cpp.
: public MD_Vector_std
Vect_MD_Vector::~Vect_MD_Vector () [virtual]
Definition at line 26 of file MD_Vector_composite.cpp.
: public MD_Vector_std
Member Function Documentation
Vect_MD_Vector & Vect_MD_Vector::add (const MD_Vector & data_to_add)
Definition at line 26 of file MD_Vector_composite.cpp.
Referenced by MD_Vector_composite::add_part(), MD_Vector_composite::readOn(), and Debog_Pb::register_item().
: public MD_Vector_std
Vect_MD_Vector & Vect_MD_Vector::operator= (const Vect_MD_Vector & vect)
Definition at line 26 of file MD_Vector_composite.cpp.
: public MD_Vector_std
const MD_Vector & Vect_MD_Vector::operator[] (int i) const
Definition at line 26 of file MD_Vector_composite.cpp.
: public MD_Vector_std
MD_Vector & Vect_MD_Vector::operator[] (int i)
Definition at line 26 of file MD_Vector_composite.cpp.
: public MD_Vector_std
int Vect_MD_Vector::size () const [inline]
Definition at line 92 of file VectMD_Vector.h.
Referenced by MD_Vector_composite::add_part(), init_parts(), MD_Vector_composite::nb_parts(), and MD_Vector_composite::printOn().
Member Data Documentation
MD_Vector* Vect_MD_Vector::data [protected]
Definition at line 92 of file VectMD_Vector.h.
int Vect_MD_Vector::sz [protected]
Definition at line 92 of file VectMD_Vector.h.
The documentation for this class was generated from the following files:
src/Kernel/Math/VectMD_Vector.h
src/Kernel/Math/MD_Vector_composite.cpp