TRUST: Champ_Generique_Champ Class Reference
Champ_Generique_Champ Class Reference
: class Champ_Generique_Champ
<Description of class Champ_Generique_Champ>
#include <Champ_Generique_Champ.h>
Public Member Functions
Champ_Generique_Champ ()
~Champ_Generique_Champ ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Generique_Champ & self_cast (Objet_U &)
static const
Champ_Generique_Champ & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void set_param (Param &param)
pb_champ : declenche la lecture du nom du probleme (nom_pb_) auquel appartient
le champ discret et le nom de ce champ discret (nom_champ_)
nom_source : option pour nommer le champ en tant que source (sinon nommer par defaut)
int lire_motcle_non_standard (const Motcle &, Entree &)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual const Champ_base & get_champ (Champ &espace_stockage) const
Voir Champ_Generique_base::get_champ.
Ici, l'espace_stockage n'est pas utilise, le champ existe deja.
const Champ_base & get_ref_champ_base () const
Renvoie le champ_base sous-jacent. Teste si le champ a bien ete associe.
A terme, cette methode disparaitra de la classe GenericField_base mais reste
dans celle-ci (on y teste si le champ a ete associe).
Exceptions:
Champ_Generique_erreur("NOT_INITIALIZED")
virtual void reset ()
void mettre_a_jour (double temps)
Voir Champ_Generique_base::mettre_a_jour
Si le champ est champ_inc dans l'equation, il doit deja avoir
ete mis a jour par l'equation.
Si c est un clacule, l actualisation est faite dans get_champ.
Protected Attributes
Champ champ_
Detailed Description
: class Champ_Generique_Champ
<Description of class Champ_Generique_Champ>
Definition at line 37 of file Champ_Generique_Champ.h.
Constructor & Destructor Documentation
Champ_Generique_Champ::Champ_Generique_Champ ()
Definition at line 26 of file Champ_Generique_Champ.cpp.
Champ_Generique_Champ::~Champ_Generique_Champ ()
Definition at line 26 of file Champ_Generique_Champ.cpp.
Member Function Documentation
Objet_U * Champ_Generique_Champ::cree_instance () [static]
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
int Champ_Generique_Champ::duplique () const [virtual]
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
const Champ_base & Champ_Generique_Champ::get_champ (Champ & espace_stockage) const [protected, virtual]
Voir Champ_Generique_base::get_champ.
Ici, l'espace_stockage n'est pas utilise, le champ existe deja.
Reimplemented from Champ_Generique_refChamp.
Definition at line 73 of file Champ_Generique_Champ.cpp.
References champ_, and Deriv_Champ_base::valeur().
{
  return champ_.valeur();
}
const Type_info * Champ_Generique_Champ::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
const Champ_base & Champ_Generique_Champ::get_ref_champ_base () const [protected, virtual]
Renvoie le champ_base sous-jacent. Teste si le champ a bien ete associe.
A terme, cette methode disparaitra de la classe GenericField_base mais reste
dans celle-ci (on y teste si le champ a ete associe).
Exceptions:
Champ_Generique_erreur("NOT_INITIALIZED")
Reimplemented from Champ_Generique_refChamp.
Definition at line 78 of file Champ_Generique_Champ.cpp.
References champ_, and Deriv_Champ_base::valeur().
{
  return champ_.valeur();
}
const Type_info * Champ_Generique_Champ::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
int Champ_Generique_Champ::lire_motcle_non_standard (const Motcle & motlu, Entree & is) [protected, virtual]
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
Returns:
int
Reimplemented from Champ_Generique_refChamp.
Definition at line 52 of file Champ_Generique_Champ.cpp.
References champ_, Champ_Generique_refChamp::ref_champ_, Ref_::reset(), and Champ_Generique_refChamp::set_ref_champ().
{
  if (mot=="champ")
    {
// Lecture du champ
      is >> champ_;
      set_ref_champ(champ_.valeur());
      ref_champ_.reset();
      return 1;
    }
  else
    return Champ_Generique_refChamp::lire_motcle_non_standard(mot,is);
  return 1;
}
void Champ_Generique_Champ::mettre_a_jour (double temps) [protected, virtual]
Voir Champ_Generique_base::mettre_a_jour
Si le champ est champ_inc dans l'equation, il doit deja avoir
ete mis a jour par l'equation.
Si c est un clacule, l actualisation est faite dans get_champ.
Reimplemented from Champ_Generique_refChamp.
Definition at line 66 of file Champ_Generique_Champ.cpp.
References champ_, and Champ::mettre_a_jour().
{
  champ_.mettre_a_jour(temps);
}
Sortie & Champ_Generique_Champ::printOn (Sortie & os) const [protected, virtual]
Imprime sur un flot de sortie.
Parametre: Sortie& os
Signification: un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Reimplemented from Champ_Generique_refChamp.
Definition at line 28 of file Champ_Generique_Champ.cpp.
{
  Champ_Generique_refChamp::printOn( os );
  return os;
}
Entree & Champ_Generique_Champ::readOn (Entree & s) [protected, virtual]
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns:
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Champ_Generique_refChamp.
Definition at line 34 of file Champ_Generique_Champ.cpp.
{
  Champ_Generique_refChamp::readOn( is );
  return is;
}
void Champ_Generique_Champ::reset () [protected, virtual]
Reimplemented from Champ_Generique_refChamp.
Definition at line 82 of file Champ_Generique_Champ.cpp.
References champ_, and Deriv_::detach().
{
  champ_.detach();
  Champ_Generique_refChamp::reset();
}
const Champ_Generique_Champ & Champ_Generique_Champ::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
Champ_Generique_Champ & Champ_Generique_Champ::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
void Champ_Generique_Champ::set_param (Param & param) [protected, virtual]
pb_champ : declenche la lecture du nom du probleme (nom_pb_) auquel appartient
le champ discret et le nom de ce champ discret (nom_champ_)
nom_source : option pour nommer le champ en tant que source (sinon nommer par defaut)
Reimplemented from Champ_Generique_refChamp.
Definition at line 45 of file Champ_Generique_Champ.cpp.
References Param::ajouter(), Param::ajouter_non_std(), Champ_Generique_base::nom_pb_, and Param::REQUIRED.
{
  param.ajouter_non_std("nom_source",(this));
  param.ajouter_non_std("champ",(this),Param::REQUIRED);
  param.ajouter("nom_pb",&nom_pb_,Param::REQUIRED);
}
unsigned Champ_Generique_Champ::taille_memoire () const [virtual]
Reimplemented from Champ_Generique_refChamp.
Definition at line 26 of file Champ_Generique_Champ.cpp.
Member Data Documentation
Champ Champ_Generique_Champ::champ_ [protected]
Definition at line 50 of file Champ_Generique_Champ.h.
Referenced by get_champ(), get_ref_champ_base(), lire_motcle_non_standard(), mettre_a_jour(), and reset().
const Type_info Champ_Generique_Champ::info_obj [static]
Reimplemented from Champ_Generique_refChamp.
Definition at line 40 of file Champ_Generique_Champ.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs/Champ_Generique_Champ.h
src/Kernel/Champs/Champ_Generique_Champ.cpp