TRUST: Matrice_Base Class Reference
Matrice_Base Class Reference abstract
Classe Matrice_Base
Classe de base de la hierarchie des matrices.
Cette classe definie l'interface generique d'une matrice telle
qu'elle est utilisee dans Trio-U. En consequence elle n'est pas
instanciable. Toutes les types de matrices devront deriver de cette
classe de base et implementer ses methodes abstraites.
Dans les commentaires des methodes A represente un objet Matrice_base.
#include <Matrice_Base.h>
Public Member Functions
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
bool is_stencil_up_to_date_
IntTab stencil_
Friends
DoubleVect operator* (const Matrice_Base &, const DoubleVect &)
Fonction (hors classe) amie de la classe Matrice_Base.
Operateur de multiplication: renvoie (A*vect)
Appelle Matrice_base::multv(const DoubleVect&) sur A.
Detailed Description
Classe Matrice_Base
Classe de base de la hierarchie des matrices.
Cette classe definie l'interface generique d'une matrice telle
qu'elle est utilisee dans Trio-U. En consequence elle n'est pas
instanciable. Toutes les types de matrices devront deriver de cette
classe de base et implementer ses methodes abstraites.
Dans les commentaires des methodes A represente un objet Matrice_base.
Definition at line 39 of file Matrice_Base.h.
Constructor & Destructor Documentation
Matrice_Base()
Matrice_Base::Matrice_Base ()
Definition at line 22 of file Matrice_Base.cpp.
~Matrice_Base()
Matrice_Base::~Matrice_Base () override
Definition at line 22 of file Matrice_Base.cpp.
Member Function Documentation
ajouter_multTab()
DoubleTab & Matrice_Base::ajouter_multTab (const DoubleTab & x, DoubleTab & r) const inline virtual
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
Returns
DoubleTab&
Signification: la matrice resultat de l'operation
Contraintes:
Definition at line 273 of file Matrice_Base.h.
{
  ajouter_multTab_(x,r);
  r.echange_espace_virtuel();
  return r;
}
References ajouter_multTab_(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
ajouter_multTab_()
virtual DoubleTab & Matrice_Base::ajouter_multTab_ (const DoubleTab & x, DoubleTab & r) const pure virtual
Implemented in Matrice_Morse, Matrice_Morse_Diag, Matrice_Morse_Sym, Matrice_Bloc, Matrice_Dense, Matrice_Diagonale, Matrice_Nulle, Matrice_Petsc, and Matrice_Bloc_Sym.
Referenced by ajouter_multTab(), and multTab().
ajouter_multvect()
DoubleVect & Matrice_Base::ajouter_multvect (const DoubleVect & x, DoubleVect & r) const inline virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
Definition at line 215 of file Matrice_Base.h.
{
  ajouter_multvect_(x,r);
  r.echange_espace_virtuel();
  return r;
}
References ajouter_multvect_(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
Referenced by Op_Diff_VEFP1NCP1B_Face::ajouter(), Matrice_Morse::ajouter_multTab_(), Matrice_Morse_Sym::ajouter_multTab_(), Equation_base::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Equation_base::Gradient_conjugue_diff_impl(), Simple::iterer_eqn(), Simple::iterer_eqs(), Piso::iterer_NS(), Solveur_U_P::iterer_NS(), PrecondA::preconditionner_(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), test_un_solveur(), and Op_Diff_PolyMAC_base::update_aux().
ajouter_multvect_()
virtual DoubleVect & Matrice_Base::ajouter_multvect_ (const DoubleVect & x, DoubleVect & r) const pure virtual
Implemented in Matrice_Morse, Matrice_Morse_Sym, Matrice_Bloc, Matrice_Dense, Matrice_Diagonale, Matrice_Nulle, Matrice_Petsc, Matrice_Bloc_Sym, and Matrice_Morse_Diag.
Referenced by ajouter_multvect(), Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), and multvect_().
ajouter_multvectT()
DoubleVect & Matrice_Base::ajouter_multvectT (const DoubleVect & x, DoubleVect & r) const inline virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
Definition at line 243 of file Matrice_Base.h.
{
  ajouter_multvectT_(x,r);
  r.echange_espace_virtuel();
  return r;
}
References ajouter_multvectT_(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
Referenced by PrecondA::preconditionner_().
ajouter_multvectT_()
virtual DoubleVect & Matrice_Base::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & r) const pure virtual
Implemented in Matrice_Morse, Matrice_Morse_Diag, Matrice_Morse_Sym, Matrice_Bloc, Matrice_Dense, Matrice_Diagonale, Matrice_Nulle, Matrice_Petsc, and Matrice_Bloc_Sym.
Referenced by Matrice_Bloc_Sym::ajouter_multvect_(), ajouter_multvectT(), Matrice_Bloc::ajouter_multvectT_(), and multvectT_().
build_stencil()
void Matrice_Base::build_stencil (void) virtual
Reimplemented in Matrice_Bloc.
Definition at line 63 of file Matrice_Base.cpp.
{
  Cerr << "Error in 'Matrice_Base::build_stencil( )"<<finl;
  Cerr << "  This method should be implemented in derived class." << finl;
  Cerr << "  Exiting..." << finl;
  Process::exit( );
}
References Cerr, and finl.
get_info()
const Type_info * Matrice_Base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, Matrice_Dense, Matrice_Diagonale, Matrice_Morse, Matrice_Morse_Diag, Matrice_Morse_Sym, Matrice_Nulle, and Matrice_Petsc.
Definition at line 22 of file Matrice_Base.cpp.
get_stencil()
void Matrice_Base::get_stencil (IntTab & stencil) const virtual
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, Matrice_Dense, Matrice_Diagonale, Matrice_Morse, Matrice_Morse_Sym, and Matrice_Nulle.
Definition at line 76 of file Matrice_Base.cpp.
{
  Cerr << "Error in 'Matrice_Base::get_stencil( )':" << finl;
  Cerr << "  This method should be implemented in derived class." << finl;
  Cerr << "  Exiting..." << finl;
  Process::exit( );
}
References Cerr, Process::exit(), and finl.
Referenced by Matrix_tools::allocate_for_scaled_addition(), Matrice_Bloc::build_stencil(), Matrix_tools::extend_matrix_stencil(), Matrice_Bloc::get_stencil(), and Matrice_Bloc_Sym::get_symmetric_stencil().
get_stencil_and_coefficients()
void Matrice_Base::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const virtual
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, Matrice_Diagonale, Matrice_Morse, Matrice_Morse_Sym, and Matrice_Nulle.
Definition at line 93 of file Matrice_Base.cpp.
{
  Cerr << "Error in 'Matrice_Base::get_stencill_and_coefficients( )':" << finl;
  Cerr << "  This method should be implemented in derived class" << finl;
  Cerr << "  Exiting..." << finl;
  Process::exit( );
}
References Cerr, Process::exit(), and finl.
Referenced by Matrix_tools::add_scaled_matrices(), Matrix_tools::convert_to_morse_matrix(), Matrice_Bloc::get_stencil_and_coefficients(), and Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients().
get_stencil_size()
int Matrice_Base::get_stencil_size (void) const
Definition at line 71 of file Matrice_Base.cpp.
{
  return stencil_.dimension( 0 );
}
References TRUSTTab< _TYPE_ >::dimension(), and stencil_.
get_symmetric_stencil()
void Matrice_Base::get_symmetric_stencil (IntTab & stencil) const virtual
Reimplemented in Matrice_Bloc_Sym, Matrice_Diagonale, Matrice_Morse_Sym, and Matrice_Nulle.
Definition at line 84 of file Matrice_Base.cpp.
{
  Matrice_Morse tmp1;
  Matrix_tools::convert_to_morse_matrix( *this, tmp1 );
  Matrice_Morse_Sym tmp2( tmp1 );
  tmp2.get_symmetric_stencil( stencil );
}
References Matrix_tools::convert_to_morse_matrix(), and Matrice_Morse_Sym::get_symmetric_stencil().
Referenced by Matrix_tools::allocate_for_symmetric_scaled_addition(), and Matrice_Bloc_Sym::get_symmetric_stencil().
get_symmetric_stencil_and_coefficients()
void Matrice_Base::get_symmetric_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const virtual
Reimplemented in Matrice_Bloc_Sym, Matrice_Diagonale, Matrice_Morse_Sym, and Matrice_Nulle.
Definition at line 102 of file Matrice_Base.cpp.
{
  Matrice_Morse tmp1;
  Matrix_tools::convert_to_morse_matrix( *this, tmp1 );
  Matrice_Morse_Sym tmp2( tmp1 );
  tmp2.get_symmetric_stencil_and_coefficients( stencil, coefficients );
}
References Matrix_tools::convert_to_morse_matrix(), and Matrice_Morse_Sym::get_symmetric_stencil_and_coefficients().
Referenced by Matrix_tools::add_symmetric_scaled_matrices(), Matrix_tools::convert_to_symmetric_morse_matrix(), and Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients().
imprimer()
Sortie & Matrice_Base::imprimer (Sortie & os) const inline virtual
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, and Matrice_Morse.
Definition at line 305 of file Matrice_Base.h.
{
  return os<<*this;
}
Referenced by Matrice_Bloc::imprimer().
imprimer_formatte()
Sortie & Matrice_Base::imprimer_formatte (Sortie & s) const inline virtual
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, Matrice_Dense, Matrice_Morse, and Matrice_Morse_Sym.
Definition at line 310 of file Matrice_Base.h.
{
  return os<<*this;
}
Referenced by estim_cond(), and Matrice_Bloc::imprimer_formatte().
info()
const Type_info * Matrice_Base::info () static
Definition at line 22 of file Matrice_Base.cpp.
is_stencil_up_to_date()
bool Matrice_Base::is_stencil_up_to_date (void) const
Definition at line 119 of file Matrice_Base.cpp.
{
  return is_stencil_up_to_date_;
}
References is_stencil_up_to_date_.
Referenced by Matrice_Morse::operator=(), and Matrice_Morse_Sym::operator=().
multTab()
DoubleTab & Matrice_Base::multTab (const DoubleTab & x, DoubleTab & r) const inline virtual
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
Returns
DoubleTab&
Signification: la matrice resultat de l'operation
Contraintes:
Definition at line 185 of file Matrice_Base.h.
{
  r=0;
  ajouter_multTab_(x,r);
  r.echange_espace_virtuel();
  return r;
}
References ajouter_multTab_(), and TRUSTVect< _TYPE_ >::echange_espace_virtuel().
multvect()
DoubleVect & Matrice_Base::multvect (const DoubleVect & x, DoubleVect & r) const inline virtual
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
Definition at line 112 of file Matrice_Base.h.
{
  multvect_(x,r);
  r.echange_espace_virtuel();
  return r;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), and multvect_().
Referenced by Assembleur_P_EF::assembler_mat(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), estim_cond(), gmres_local(), Equation_base::Gradient_conjugue_diff_impl(), Matrice_Morse::inverse(), inverser_par_diagonale(), operator*(), PrecondA::preconditionner_(), Solv_GCP::resoudre_(), Solv_Gmres::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Solv_Gen::solve(), verifier(), verifier_complet(), and Debog_Pb::verifier_matrice().
multvect_()
DoubleVect & Matrice_Base::multvect_ (const DoubleVect & x, DoubleVect & r) const inline virtual
Definition at line 120 of file Matrice_Base.h.
{
  r=0;
  ajouter_multvect_(x,r);
  return r;
}
References ajouter_multvect_().
Referenced by gmres_local(), multvect(), and Solv_GCP::resoudre_().
multvectT()
DoubleVect & Matrice_Base::multvectT (const DoubleVect & x, DoubleVect & r) const inline virtual
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
Returns
DoubleVect&
Signification: le vecteur resultat de l'operation
Contraintes:
Definition at line 148 of file Matrice_Base.h.
{
  multvectT_(x,r);
  r.echange_espace_virtuel();
  return r;
}
References TRUSTVect< _TYPE_ >::echange_espace_virtuel(), and multvectT_().
Referenced by Solv_GCP_NS::resoudre_systeme(), and Solv_Gen::solve().
multvectT_()
DoubleVect & Matrice_Base::multvectT_ (const DoubleVect & x, DoubleVect & r) const inline virtual
Definition at line 156 of file Matrice_Base.h.
{
  r=0;
  ajouter_multvectT_(x,r);
  return r;
}
References ajouter_multvectT_().
Referenced by multvectT().
nb_colonnes()
virtual int Matrice_Base::nb_colonnes () const pure virtual
Implemented in Matrice_Dense, Matrice_Morse, Matrice_Nulle, Matrice_Petsc, Matrice_Bloc, and Matrice_Diagonale.
Referenced by Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrice_Bloc::build_stencil(), Matrice_Bloc::check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), Matrix_tools::convert_to_morse_matrix(), Matrix_tools::convert_to_symmetric_morse_matrix(), Matrix_tools::extend_matrix_stencil(), Matrice_Bloc::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), and Matrice_Bloc::nb_colonnes().
nb_lignes()
virtual int Matrice_Base::nb_lignes () const pure virtual
Implemented in Matrice_Dense, Matrice_Morse, Matrice_Nulle, Matrice_Petsc, Matrice_Bloc, and Matrice_Diagonale.
Referenced by Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Matrix_tools::allocate_for_scaled_addition(), Matrix_tools::allocate_for_symmetric_scaled_addition(), Matrice_Bloc::build_stencil(), Matrice_Bloc::check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), Matrix_tools::convert_to_morse_matrix(), Matrix_tools::convert_to_symmetric_morse_matrix(), estim_cond(), Matrix_tools::extend_matrix_stencil(), Matrice_Bloc::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), Matrice_Bloc::nb_lignes(), and Solv_GCP_NS::resoudre_systeme().
ordre()
virtual int Matrice_Base::ordre () const pure virtual
Implemented in Matrice_Dense, Matrice_Morse, Matrice_Nulle, Matrice_Petsc, Matrice_Bloc, and Matrice_Diagonale.
Referenced by Op_Diff_RotRot::ajouter().
printOn()
Sortie & Matrice_Base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, Matrice_Dense, Matrice_Diagonale, Matrice_Morse, Matrice_Morse_Diag, Matrice_Morse_Sym, Matrice_Nulle, and Matrice_Petsc.
Definition at line 24 of file Matrice_Base.cpp.
{
  return s << que_suis_je() << finl;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & Matrice_Base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Matrice_Bloc, Matrice_Bloc_Sym, Matrice_Dense, Matrice_Diagonale, Matrice_Morse, Matrice_Morse_Diag, Matrice_Morse_Sym, Matrice_Nulle, and Matrice_Petsc.
Definition at line 29 of file Matrice_Base.cpp.
{
  return s ;
}
scale()
virtual void Matrice_Base::scale (const double x) pure virtual
Implemented in Matrice_Bloc, Matrice_Dense, Matrice_Diagonale, Matrice_Morse, Matrice_Morse_Sym, Matrice_Nulle, and Matrice_Petsc.
Referenced by Matrice_Bloc::scale().
self_cast() [1/2]
const Matrice_Base & Matrice_Base::self_cast (const Objet_U & r) static
Definition at line 22 of file Matrice_Base.cpp.
self_cast() [2/2]
Matrice_Base & Matrice_Base::self_cast (Objet_U & r) static
Definition at line 22 of file Matrice_Base.cpp.
set_stencil()
void Matrice_Base::set_stencil (const IntTab & stencil)
Definition at line 112 of file Matrice_Base.cpp.
{
  stencil_ = stencil ;
  tableau_trier_retirer_doublons( stencil_ );
  is_stencil_up_to_date_ = false ;
}
References is_stencil_up_to_date_, stencil_, and tableau_trier_retirer_doublons().
Referenced by Matrix_tools::allocate_from_stencil(), and Matrix_tools::allocate_morse_matrix().
Friends And Related Function Documentation
operator*
DoubleVect operator* (const Matrice_Base & , const DoubleVect &) friend
Fonction (hors classe) amie de la classe Matrice_Base.
Operateur de multiplication: renvoie (A*vect)
Appelle Matrice_base::multv(const DoubleVect&) sur A.
Returns
DoubleVect
Signification: le vecteur resultat de l'operation
Contraintes: le vecteur est alloue par la methode
Definition at line 56 of file Matrice_Base.cpp.
{
  DoubleVect r;
  return A.multvect(vect, r);
}
Member Data Documentation
info_obj
const Type_info Matrice_Base::info_obj static
Definition at line 42 of file Matrice_Base.h.
is_stencil_up_to_date_
bool Matrice_Base::is_stencil_up_to_date_ protected
Definition at line 86 of file Matrice_Base.h.
Referenced by Matrice_Bloc::build_stencil(), Matrice_Morse::formeC(), Matrice_Morse::formeF(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Bloc::get_stencil(), Matrice_Diagonale::get_stencil(), Matrice_Morse::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), is_stencil_up_to_date(), Matrice_Bloc::Matrice_Bloc(), Matrice_Diagonale::Matrice_Diagonale(), Matrice_Morse::Matrice_Morse(), Matrice_Morse::operator=(), Matrice_Morse_Sym::operator=(), Matrice_Morse::remplir(), and set_stencil().
stencil_
IntTab Matrice_Base::stencil_ protected
Definition at line 87 of file Matrice_Base.h.
Referenced by Matrice_Bloc::build_stencil(), Matrice_Bloc::get_stencil(), Matrice_Diagonale::get_stencil(), Matrice_Morse::get_stencil(), Matrice_Bloc::get_stencil_and_coefficients(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), get_stencil_size(), and set_stencil().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Base.h
src/Kernel/Math/Matrices/Matrice_Base.cpp