TRUST: Execute_parallel Class Reference
Execute_parallel Class Reference
Interprete permettant l'execution simultanee de plusieurs fichiers<br>.data en creant des sous-groupes de processeurs en parallele
Voir Execute_parallel::interpreter()
#include <Execute_parallel.h>
Public Member Functions
Execute_parallel ()
~Execute_parallel ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter (Entree &) override
Cree une partition des nproc processeurs du calcul pour interpreter
N jeux de donnees differents. La syntaxe du jeu de donnees est la suivante
Execute_parallel {
liste_cas N cas1 cas2 cas3 ...
[ nb_procs N nproc1 nproc2 nproc3 ... ]
}
"cas1" est le nom du cas (on lit le fichier cas1.data sur disque)
nproc1 est le nombre de processeurs a utiliser pour ce cas
Par defaut, on utilise 1 processeur pour chaque cas
Les sorties Cerr et Cout sont redirigees vers le journal du processeur
maitre de chaque cas.
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Execute_parallel & self_cast (Objet_U &)
static const Execute_parallel & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Interprete permettant l'execution simultanee de plusieurs fichiers<br>.data en creant des sous-groupes de processeurs en parallele
Voir Execute_parallel::interpreter()
Definition at line 24 of file Execute_parallel.h.
Constructor & Destructor Documentation
Execute_parallel()
Execute_parallel::Execute_parallel ()
Definition at line 25 of file Execute_parallel.cpp.
~Execute_parallel()
Execute_parallel::~Execute_parallel ()
Definition at line 25 of file Execute_parallel.cpp.
Member Function Documentation
cree_instance()
Objet_U * Execute_parallel::cree_instance () static
Definition at line 25 of file Execute_parallel.cpp.
duplique()
int Execute_parallel::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Execute_parallel.cpp.
get_info()
const Type_info * Execute_parallel::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Execute_parallel.cpp.
info()
const Type_info * Execute_parallel::info () static
Definition at line 25 of file Execute_parallel.cpp.
interpreter()
Entree & Execute_parallel::interpreter (Entree & is) override virtual
Cree une partition des nproc processeurs du calcul pour interpreter
N jeux de donnees differents. La syntaxe du jeu de donnees est la suivante
Execute_parallel {
liste_cas N cas1 cas2 cas3 ...
[ nb_procs N nproc1 nproc2 nproc3 ... ]
}
"cas1" est le nom du cas (on lit le fichier cas1.data sur disque)
nproc1 est le nombre de processeurs a utiliser pour ce cas
Par defaut, on utilise 1 processeur pour chaque cas
Les sorties Cerr et Cout sont redirigees vers le journal du processeur
maitre de chaque cas.
Reimplemented from Interprete.
Definition at line 53 of file Execute_parallel.cpp.
{
  Cerr << "Execute_parallel::interpreter to run several cases:" << finl;
  Noms liste_cas;
  ArrOfInt nb_procs;
  int disable_journal = 0;
  Param param(que_suis_je());
  param.ajouter("liste_cas", &liste_cas, Param::REQUIRED);
  param.ajouter("nb_procs", &nb_procs);
  param.ajouter_flag("disable_journal", &disable_journal);
  param.lire_avec_accolades_depuis(is);
// Si on n'a pas donne nb_procs, on suppose que ca vaut 1
  const int n_calculs = liste_cas.size();
  if (nb_procs.size_array() == 0)
    {
      Cerr << "Nb_procs not given, we assume that calculations are sequential."
           << finl;
      nb_procs.resize_array(n_calculs);
      nb_procs = 1;
    }
// Verification de la taille des tableaux
  if (nb_procs.size_array() != n_calculs)
    {
      Cerr << "Error : nb_procs array must have " << n_calculs
           << " values." << finl;
      barrier();
      exit();
    }
  if (n_calculs == 0)
    return is;
// Verification du contenu :
  if (min_array(nb_procs) < 1)
    {
      Cerr << "Error : processor numbers must be >= 1" << finl;
      barrier();
      exit();
    }
  int count = 0;
  for (int i = 0; i < n_calculs; i++)
    count += nb_procs[i];
  if (count > nproc())
    {
      Cerr << "Error : computations require " << count << " processors." << finl;
      Cerr << "but only " << nproc() << " processors has been asked." << finl;
      barrier();
      exit();
    }
// Creation des N groupes de processeurs
// (les groupes sont detruits quand le VECT est detruit)
  VECT(DERIV(Comm_Group)) groupes(n_calculs);
  count = 0;
  Nom log_courant("");
  for (int i = 0; i < n_calculs; i++)
    {
      const int n = nb_procs[i];
      Nom log("");
      Nom log1(Objet_U::nom_du_cas());
      log1+="_";
      char s[20];
      sprintf(s, "%05d", (True_int)count);
      log1+=s;
      log1+=".log";
      if (n==1)
        {
          log+=log1;
          log+=" file";
        }
      else
        {
          Nom log2(Objet_U::nom_du_cas());
          log2+="_";
          char s2[20];
          sprintf(s2, "%05d", (True_int)(count+n-1));
          log2+=s2;
          log2+=".log";
          log="log files from ";
          log+=log1;
          log+=" to ";
          log+=log2;
        }
      Cerr << "Error and standard outputs are redirected into " << log << " for case " << liste_cas[i] << finl;
// On stocke dans log_courant car reutilise plus loin
      if (Process::me()>=count && Process::me()<=count+n-1)
        log_courant=log;
      ArrOfInt tab(n);
      for (int j = 0; j < n; j++)
        tab[j] = count++;
      PE_Groups::create_group(tab, groupes[i]);
    }
// On lancer une exception si un calcul s'arrete donc
// on change le comportement de Process par defaut (MPI_Abort)
  Process::exception_sur_exit=1;
  Cerr << n_calculs << " cases are running..." << finl;
// Chaque processeur entre dans son groupe et interprete le jeu de donnees
  Nom ancien_nom_du_cas(nom_du_cas());
  const int old_journal_level = get_journal_level();
  for (int i = 0; i < n_calculs; i++)
    {
      if (PE_Groups::enter_group(groupes[i].valeur()))
        {
          set_Cerr_to_journal(1);
          if (disable_journal)
            change_journal_level(0);
          Nom nom_fichier(liste_cas[i]);
          get_set_nom_du_cas() = nom_fichier;
          Journal(1) << "Execute_parallel: Entering subgroup " << i
                     << " to run case " << nom_fichier << finl;
          nom_fichier += ".data";
          {
// Ouverture du fichier (on cree l'objet LecFicDiffuse a l'interieur
// de l'accolade pour detruire le fichier avant de sortir du groupe)
            LecFicDiffuse_JDD data_file(nom_fichier);
            data_file.set_check_types(1);
// On cree un nouvel interprete. A la fin de la lecture du cas
// les objets seront detruits.
            Interprete_bloc interp;
// On utilise les exceptions pour des calculs qui s'arretent
            int ok=1;
            try
              {
                interp.interpreter_bloc(data_file,
                                        Interprete_bloc::FIN /* on attend FIN a la fin du fichier */,
                                        0 /* verifie_sans_interpreter=0 */);
              }
            catch (TriouError err)
              {
                assert(err.get_pe()==Process::me());
                ok=0;
              }
            set_Cerr_to_journal(0);
            if (ok)
              Cerr << "Case " << liste_cas[i] << " has finished. See " << log_courant << finl;
            else
              Cerr << "!!! Case " << liste_cas[i] << " has failed. See " << log_courant << " !!!" << finl;
          }
          Journal(1) << "Execute_parallel: Exiting subgroup " << i << finl;
          PE_Groups::exit_group();
        }
    }
// on revient au comportement standard de trio
  Process::exception_sur_exit=0;
  change_journal_level(old_journal_level);
// On attend que tous les processeurs aient fini d'executer leur calcul.
  barrier();
  get_set_nom_du_cas() = ancien_nom_du_cas;
  Cerr << finl << "End of Execute_parallel::interpreter" << finl;
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), Process::barrier(), Cerr, change_journal_level(), PE_Groups::create_group(), DERIV, PE_Groups::enter_group(), Process::exception_sur_exit, Process::exit(), PE_Groups::exit_group(), Interprete_bloc::FIN, finl, get_journal_level(), TriouError::get_pe(), Objet_U::get_set_nom_du_cas(), Interprete_bloc::interpreter_bloc(), Process::Journal(), Param::lire_avec_accolades_depuis(), Process::me(), min_array(), Objet_U::nom_du_cas(), nom_fichier(), Process::nproc(), Objet_U::que_suis_je(), Param::REQUIRED, TRUSTArray< _TYPE_ >::resize_array(), set_Cerr_to_journal(), Lec_Diffuse_base::set_check_types(), vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), valeur(), and VECT.
printOn()
Sortie & Execute_parallel::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 34 of file Execute_parallel.cpp.
{
  Cerr << "Execute_parallel::printOn() not coded" << finl;
  exit();
  return os;
}
References Cerr, Process::exit(), and finl.
readOn()
Entree & Execute_parallel::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 27 of file Execute_parallel.cpp.
{
  Cerr << "Execute_parallel::readOn() not coded" << finl;
  exit();
  return is;
}
References Cerr, Process::exit(), and finl.
self_cast() [1/2]
const Execute_parallel & Execute_parallel::self_cast (const Objet_U & r) static
Definition at line 25 of file Execute_parallel.cpp.
self_cast() [2/2]
Execute_parallel & Execute_parallel::self_cast (Objet_U & r) static
Definition at line 25 of file Execute_parallel.cpp.
taille_memoire()
unsigned Execute_parallel::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Execute_parallel.cpp.
Member Data Documentation
info_obj
const Type_info Execute_parallel::info_obj static
Definition at line 26 of file Execute_parallel.h.
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Execute_parallel.h
src/Kernel/Utilitaires/Execute_parallel.cpp