TRUST: Champ_Fonc_P0_base Class Reference
Champ_Fonc_P0_base Class Reference
: class Champ_Fonc_P0_base
Decrire ici la classe Champ_Fonc_P0_base
#include <Champ_Fonc_P0_base.h>
Public Member Functions
Champ_Fonc_P0_base ()
~Champ_Fonc_P0_base ()
virtual int duplique () const =0
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const
virtual DoubleTab & valeur_aux_sommets (const Domaine &domain, DoubleTab &result) const
virtual DoubleVect & valeur_aux_sommets_compo (const Domaine &domain, DoubleVect &result, int ncomp) const
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
virtual Champ_base & affecter_ (const Champ_base &)
int fixer_nb_valeurs_nodales (int n)
Fixe le nombre de degres de liberte par composante.
Static Public Member Functions
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Champ_Fonc_P0_base & self_cast (Objet_U &)
static const Champ_Fonc_P0_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Champ_base & le_champ (void)
virtual const Champ_base & le_champ (void) const
Detailed Description
: class Champ_Fonc_P0_base
Decrire ici la classe Champ_Fonc_P0_base
Definition at line 36 of file Champ_Fonc_P0_base.h.
Constructor & Destructor Documentation
Champ_Fonc_P0_base::Champ_Fonc_P0_base ()
Definition at line 29 of file Champ_Fonc_P0_base.cpp.
Champ_Fonc_P0_base::~Champ_Fonc_P0_base ()
Definition at line 29 of file Champ_Fonc_P0_base.cpp.
Member Function Documentation
Champ_base & Champ_Fonc_P0_base::affecter_ (const Champ_base & ch) [virtual]
Reimplemented from Champ_implementation_P0.
Reimplemented in Champ_Ostwald.
Definition at line 63 of file Champ_Fonc_P0_base.cpp.
References Champ_implementation_P0::affecter_().
{
  if (Champ_implementation_P0::affecter_(ch))
    {
      return *this;
    }
  else
    {
      return Champ_Fonc_base::affecter_(ch);
    }
}
virtual int Champ_Fonc_P0_base::duplique () const [pure virtual]
Implements Champ_Fonc_base.
Implemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
int Champ_Fonc_P0_base::fixer_nb_valeurs_nodales (int nb_noeuds) [virtual]
Fixe le nombre de degres de liberte par composante.
Returns:
int
Signification: le nombre de degres de liberte par composante
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Ostwald.
Definition at line 52 of file Champ_Fonc_P0_base.cpp.
References Champ_Fonc_base::creer_tableau_distribue(), Zone::md_vector_elements(), Zone::nb_elem(), ref_cast, and Zone_dis_base::zone().
Referenced by VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::critere_Q(), VDF_discretisation::critere_Q(), VEF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), EF_discretisation::distance_paroi(), CoviMAC_discretisation::distance_paroi(), VEF_discretisation::grad_u(), VDF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), CoviMAC_discretisation::grad_u(), VEF_discretisation::h_conv(), VEF_discretisation::modifier_champ_tabule(), VDF_discretisation::modifier_champ_tabule(), PolyMAC_discretisation::modifier_champ_tabule(), EF_discretisation::modifier_champ_tabule(), CoviMAC_discretisation::modifier_champ_tabule(), VEF_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VDF_discretisation::vorticite(), VEF_discretisation::y_plus(), and VDF_discretisation::y_plus().
{
// Encore une syntaxe a la con, sinon on ne sait pas s'il faut appeler
// zone_dis_base() de champ_inc_base ou de champ_impl...
  const Zone_dis_base& zonedis = ref_cast(Champ_Fonc_base, *this).zone_dis_base();
  assert(n == zonedis.zone().nb_elem());
  const MD_Vector& md = zonedis.zone().md_vector_elements();
  creer_tableau_distribue(md);
  return 1;
}
const Type_info * Champ_Fonc_P0_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 29 of file Champ_Fonc_P0_base.cpp.
const Type_info * Champ_Fonc_P0_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 29 of file Champ_Fonc_P0_base.cpp.
const Champ_base & Champ_Fonc_P0_base::le_champ (void) const [protected, virtual]
Implements Champ_implementation_P0.
Definition at line 47 of file Champ_Fonc_P0_base.cpp.
{
  return *this;
}
Champ_base & Champ_Fonc_P0_base::le_champ (void) [protected, virtual]
Implements Champ_implementation_P0.
Definition at line 42 of file Champ_Fonc_P0_base.cpp.
{
  return *this;
}
Sortie & Champ_Fonc_P0_base::printOn (Sortie & s) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 31 of file Champ_Fonc_P0_base.cpp.
References Field_base::le_nom(), and Objet_U::que_suis_je().
{
  os << que_suis_je() << " " << le_nom();
  return os;
}
Entree & Champ_Fonc_P0_base::readOn (Entree & s) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification:
Contraintes:
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 37 of file Champ_Fonc_P0_base.cpp.
{
  return is;
}
DoubleTab & Champ_Fonc_P0_base::remplir_coord_noeuds (DoubleTab & positions) const [inline, virtual]
Reimplemented from Champ_implementation_P0.
Definition at line 89 of file Champ_Fonc_P0_base.h.
Referenced by Champ_Ostwald::affecter_(), Champ_Fonc_P0_VEF::remplir_coord_noeuds_et_polys(), Champ_Fonc_P0_PolyMAC::remplir_coord_noeuds_et_polys(), Champ_Fonc_P0_EF::remplir_coord_noeuds_et_polys(), and Champ_Fonc_P0_CoviMAC::remplir_coord_noeuds_et_polys().
{
  return Champ_implementation_P0::remplir_coord_noeuds(positions);
}
int Champ_Fonc_P0_base::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const [inline, virtual]
Reimplemented from Champ_implementation_P0.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_P0_PolyMAC, and Champ_Fonc_P0_VEF.
Definition at line 94 of file Champ_Fonc_P0_base.h.
Referenced by Champ_Ostwald::affecter_().
{
  return Champ_implementation_P0::remplir_coord_noeuds_et_polys(positions,polys);
}
Champ_Fonc_P0_base & Champ_Fonc_P0_base::self_cast (Objet_U & r) [static]
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 29 of file Champ_Fonc_P0_base.cpp.
const Champ_Fonc_P0_base & Champ_Fonc_P0_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 29 of file Champ_Fonc_P0_base.cpp.
DoubleTab & Champ_Fonc_P0_base::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const [virtual]
Calcule la trace d'un champ sur une frontiere au temps tps
WEC :
La frontiere passee en parametre doit faire partie du domaine
sur lequel s'appuie le champ
Le resultat est calcule sur cette frontiere et la taille du
DoubleTab x correspond au nombre de faces de la frontiere.
x peut avoir un espace virtuel, la fonction trace apelle
echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le
raccord associe. Dans ce cas, le DoubleTab x doit etre
dimensionne sur le raccord associe.
Returns:
DoubleTab&
Signification: les valeurs du champ sur la frontiere au temps tps
Contraintes:
Reimplemented from Champ_base.
Definition at line 77 of file Champ_Fonc_P0_base.cpp.
References Champ_Don_base::valeurs().
{
  return Champ_implementation_P0::trace(fr, valeurs(), x,distant);
}
DoubleVect & Champ_Fonc_P0_base::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const [inline, virtual]
Reimplemented from Champ_implementation_P0.
Definition at line 59 of file Champ_Fonc_P0_base.h.
{
  return Champ_implementation_P0::valeur_a_elem(position,result,poly);
}
double Champ_Fonc_P0_base::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const [inline, virtual]
Reimplemented from Champ_implementation_P0.
Definition at line 64 of file Champ_Fonc_P0_base.h.
{
  return Champ_implementation_P0::valeur_a_elem_compo(position,poly,ncomp);
}
DoubleTab & Champ_Fonc_P0_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const [inline, virtual]
Reimplemented from Champ_implementation_P0.
Definition at line 69 of file Champ_Fonc_P0_base.h.
{
  return Champ_implementation_P0::valeur_aux_elems(positions,polys,result);
}
DoubleVect & Champ_Fonc_P0_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const [inline, virtual]
Reimplemented from Champ_implementation_P0.
Definition at line 74 of file Champ_Fonc_P0_base.h.
{
  return Champ_implementation_P0::valeur_aux_elems_compo(positions,polys,result,ncomp);
}
DoubleTab & Champ_Fonc_P0_base::valeur_aux_sommets (const Domaine & domain, DoubleTab & result) const [inline, virtual]
Reimplemented from Champ_implementation_base.
Definition at line 79 of file Champ_Fonc_P0_base.h.
{
  return Champ_implementation_P0::valeur_aux_sommets(domain,result);
}
DoubleVect & Champ_Fonc_P0_base::valeur_aux_sommets_compo (const Domaine & domain, DoubleVect & result, int ncomp) const [inline, virtual]
Reimplemented from Champ_implementation_base.
Definition at line 84 of file Champ_Fonc_P0_base.h.
{
  return Champ_implementation_P0::valeur_aux_sommets_compo(domain,result,ncomp);
}
Member Data Documentation
const Type_info Champ_Fonc_P0_base::info_obj [static]
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_P0_CoviMAC, Champ_Fonc_Tabule_P0_CoviMAC, grad_U_Champ_Face_CoviMAC, Champ_Fonc_P0_EF, Champ_Fonc_Tabule_P0_EF, Rotationnel_Champ_P1_EF, Rotationnel_Champ_Q1_EF, Champ_input_P0, Champ_Fonc_P0_MED, Champ_Fonc_P0_PolyMAC, Champ_Fonc_Tabule_P0_PolyMAC, grad_U_Champ_Face_PolyMAC, Champ_Ostwald, Champ_Fonc_P0_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald_VDF, Correlation_Vec_Sca_VDF, Critere_Q_Champ_Face, grad_U_Champ_Face, Rotationnel_Champ_Face, Taux_cisaillement_P0_VDF, Y_plus_Champ_Face, Champ_Fonc_P0_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VEF, Critere_Q_Champ_P1NC, grad_T_Champ_P1NC, grad_U_Champ_P1NC, h_conv_Champ_P1NC, Rotationnel_Champ_P1NC, Rotationnel_Champ_Q1NC, Taux_cisaillement_P0_VEF, and Y_plus_Champ_P1NC.
Definition at line 39 of file Champ_Fonc_P0_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Champs_dis/Champ_Fonc_P0_base.h
src/Kernel/Champs_dis/Champ_Fonc_P0_base.cpp