TRUST: Assembleur_P_VEFPreP1B Class Reference
Assembleur_P_VEFPreP1B Class Reference
#include <Assembleur_P_VEFPreP1B.h>
Public Member Functions
Assembleur_P_VEFPreP1B ()
~Assembleur_P_VEFPreP1B ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
const Zone_VEF_PreP1b & zone_Vef () const
int assembler (Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &) override
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u) override
int modifier_secmem (DoubleTab &) override
int preparer_solution (DoubleTab &)
int modifier_solution (DoubleTab &) override
int modifier_matrice (Matrice &) override
Modifier eventuellement la matrice pour la rendre definie si elle ne l'est pas
Valeurs par defaut:
Contraintes:
Acces: lecture.
void verifier_dirichlet ()
void completer (const Equation_base &) override
const Equation_base & equation () const
int modifier_secmem_elem (const DoubleTab &, DoubleTab &)
int modifier_secmem_som (const DoubleTab &, DoubleTab &)
int modifier_secmem_aretes (const DoubleTab &, DoubleTab &)
int changement_base () const
void changer_base_matrice (Matrice &)
A->A~ (P0+P1->P1Bulle)
void changer_base_second_membre (DoubleVect &)
y->y~ (P0+P1->P1Bulle)
void changer_base_pression_inverse (DoubleVect &) const
x~->x (P1Bulle->P0+P1)
void changer_base_pression (DoubleVect &)
x->x~ (P0+P1->P1Bulle) Ne sert que pour les tests
Public Member Functions inherited from Assembleur_P_VEF
Assembleur_P_VEF ()
~Assembleur_P_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_zone_dis_base (const Zone_dis_base &) override
void associer_zone_cl_dis_base (const Zone_Cl_dis_base &) override
const Zone_dis_base & zone_dis_base () const override
const Zone_Cl_dis_base & zone_Cl_dis_base () const override
int assembler (Matrice &) override
int assembler_mat (Matrice &, const DoubleVect &, int, int) override
int remplir (Matrice &, const DoubleTab &)
int remplir (Matrice &, const DoubleVect &)
int assembler_QC (const DoubleTab &, Matrice &) override
Assemble la matrice de pression pour un fluide quasi compressible
laplacein(P) est remplace par div(grad(P)/rho).
int modifier_secmem (DoubleTab &) override
int modifier_solution (DoubleTab &) override
virtual int modifier_matrice (Matrice &)
Modifier eventuellement la matrice pour la rendre definie si elle ne l'est pas
Valeurs par defaut:
Contraintes:
Acces: lecture.
void completer (const Equation_base &) override
const Equation_base & equation () const
Public Member Functions inherited from Assembleur_base
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_VEFPreP1B & self_cast (Objet_U &)
static const Assembleur_P_VEFPreP1B & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_P_VEF
static Objet_U * cree_instance ()
static const Type_info * info ()
static Assembleur_P_VEF & self_cast (Objet_U &)
static const Assembleur_P_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Assembleur_base
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Matrice la_matrice_de_travail_
Matrice de travail.
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_P_VEF
static const Type_info info_obj
Static Public Attributes inherited from Assembleur_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void projete_L2 (DoubleTab &)
Protected Member Functions inherited from Assembleur_P_VEF
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
void calculer_inv_volume (DoubleTab &inv_volumes_entrelaces, const Zone_Cl_VEF &zone_Cl_VEF, const DoubleVect &volumes_entrelaces)
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
int init
Ref_Equation_base mon_equation
double alpha
double beta
Coefficients du changement de base P0+P1<->P1Bulle.
Protected Attributes inherited from Assembleur_P_VEF
Ref_Equation_base mon_equation
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
DoubleTab les_coeff_pression
int has_P_ref
Detailed Description
Definition at line 24 of file Assembleur_P_VEFPreP1B.h.
Constructor & Destructor Documentation
Assembleur_P_VEFPreP1B()
Assembleur_P_VEFPreP1B::Assembleur_P_VEFPreP1B ()
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
~Assembleur_P_VEFPreP1B()
Assembleur_P_VEFPreP1B::~Assembleur_P_VEFPreP1B ()
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
Member Function Documentation
assembler()
int Assembleur_P_VEFPreP1B::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
Definition at line 175 of file Assembleur_P_VEFPreP1B.cpp.
{
  return Assembleur_P_VEF::assembler(la_matrice);
}
References Assembleur_P_VEF::assembler().
assembler_mat()
int Assembleur_P_VEFPreP1B::assembler_mat (Matrice & la_matrice, const DoubleVect & quantitee_entrelacee, int incr_pression, int resoudre_en_u) override virtual
< Lecture de la matrice dans un fichier
< Assemblage de la matrice
< A->A~
< On n'est pas en P0
< Suppression des coefficients nuls et quasi non nuls
< Suppression des coefficients nuls et quasi non nuls
Reimplemented from Assembleur_base.
Definition at line 218 of file Assembleur_P_VEFPreP1B.cpp.
{
// On fixe les drapeaux de Assembleur_base
  set_resoudre_increment_pression(incr_pression);
  set_resoudre_en_u(resoudre_en_u);
  SolveurSys& solveur_pression = ref_cast(Navier_Stokes_std, mon_equation.valeur()).solveur_pression();
  bool read_matrix = false;
  if (sub_type(Solv_Petsc, solveur_pression.valeur()))
    read_matrix = ref_cast(Solv_Petsc, solveur_pression.valeur()).read_matrix();
  if (read_matrix) //!< Lecture de la matrice dans un fichier
    {
      la_matrice.typer("Matrice_Petsc");
// ref_cast(Matrice_Petsc, la_matrice.valeur()).RestoreMatrixFromFile();
    }
  else //!< Assemblage de la matrice
    {
      const Zone_VEF_PreP1b& zone_vef = zone_Vef();
      Cerr << "Assemblage de la matrice de pression" << (zone_vef.get_alphaE() ? " P0" : "")
           << (zone_vef.get_alphaS() ? " P1" : "") << (zone_vef.get_alphaA() ? " Pa" : "") << " en cours..." << finl;
// Les decoupages doivent etre de largeur de joint de 2
// si le support P1 ou Pa est utilise...
      if (Process::nproc() > 1 &&
          zone_vef.zone().nb_joints() &&
          zone_vef.zone().joint(0).epaisseur() < 2 &&
          (zone_vef.get_alphaS() || zone_vef.get_alphaA()))
        {
          Cerr << "Ghost cells width of " << zone_vef.zone().joint(0).epaisseur()
               << " is not enough for assembling VEFPreP1B pressure matrix" << finl;
          Cerr << "for parallel calculation. Partition your mesh with larg_joint option set to 2." << finl;
          Process::exit();
        }
      DoubleTab inverse_quantitee_entrelacee;
      const Zone_Cl_VEF& zone_Cl_VEF = la_zone_Cl_VEF.valeur();
      calculer_inv_volume(inverse_quantitee_entrelacee, zone_Cl_VEF, quantitee_entrelacee);
      int P0 = 0;
      int P1 = P0 + zone_vef.get_alphaE();
      int Pa = P1 + zone_vef.get_alphaS();
      int nombre_supports = Pa + zone_vef.get_alphaA();
      DoubleVect coef_som;
      if (zone_vef.get_alphaS())
        {
          zone_vef.zone().creer_tableau_elements(coef_som);
          for (int elem = 0; elem < coef_som.size_totale(); elem++)
            coef_som[elem] = Op_Grad_VEF_P1B_Face::calculer_coef_som(elem, zone_Cl_VEF, zone_vef);
          coef_som.echange_espace_virtuel();
        }
// Assemblage de la matrice complete selon les supports choisis
      Matrice_Bloc_Sym& la_matrice_bloc_sym_de_travail = ref_cast(Matrice_Bloc_Sym, la_matrice_de_travail_.valeur());
      if (la_matrice_bloc_sym_de_travail.nb_bloc_lignes()==0)
        {
          la_matrice_bloc_sym_de_travail.dimensionner(nombre_supports, nombre_supports);
          if (zone_vef.get_alphaE())
            assemblerP0P0(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P0, P0),
                          inverse_quantitee_entrelacee);
          if (zone_vef.get_alphaS())
            assemblerP1P1(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P1, P1),
                          inverse_quantitee_entrelacee, coef_som);
          if (zone_vef.get_alphaE() && zone_vef.get_alphaS())
            assemblerP0P1(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P0, P1),
                          inverse_quantitee_entrelacee, coef_som);
          if (zone_vef.get_alphaA())
            assemblerPaPa(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(Pa, Pa),
                          inverse_quantitee_entrelacee);
          if (zone_vef.get_alphaS() && zone_vef.get_alphaA())
            assemblerP1Pa(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P1, Pa),
                          inverse_quantitee_entrelacee, coef_som);
          if (zone_vef.get_alphaE() && zone_vef.get_alphaA())
            assemblerP0Pa(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P0, Pa),
                          inverse_quantitee_entrelacee);
        }
// On met a zero la matrice meme si elle a ete correctement construite et remplie dans les methodes
// assemblerPiPi et on la remplit a nouveau. Pourquoi? Pour avoir une couverture de tests
// suffisante des methodes updatePiPi en attendant de factoriser correctement les
// methodes assemblerPiPi et updatePiPi
      zero(la_matrice_bloc_sym_de_travail);
      {
        if (zone_vef.get_alphaE())
          updateP0P0(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P0, P0),
                     inverse_quantitee_entrelacee);
        if (zone_vef.get_alphaS())
          {
            updateP1P1(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P1, P1),
                       inverse_quantitee_entrelacee, coef_som);
            if (zone_vef.get_cl_pression_sommet_faible() == 0)
              modifieP1P1neumann(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P1, P1),
                                 inverse_quantitee_entrelacee, coef_som);
          }
        if (zone_vef.get_alphaE() && zone_vef.get_alphaS())
          updateP0P1(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P0, P1),
                     inverse_quantitee_entrelacee, coef_som);
        if (zone_vef.get_alphaA())
          updatePaPa(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(Pa, Pa),
                     inverse_quantitee_entrelacee);
        if (zone_vef.get_alphaS() && zone_vef.get_alphaA())
          updateP1Pa(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P1, Pa),
                     inverse_quantitee_entrelacee, coef_som);
        if (zone_vef.get_alphaE() && zone_vef.get_alphaA())
          updateP0Pa(zone_vef, zone_Cl_VEF, la_matrice_bloc_sym_de_travail.get_bloc(P0, Pa),
                     inverse_quantitee_entrelacee);
      }
      int ordre_matrice = mp_sum(la_matrice_bloc_sym_de_travail.nb_lignes());
      Cerr << "Order of the matrix = " << ordre_matrice << finl;
// Methode verifier
      char *theValue = getenv("TRUST_VERIFIE_MATRICE_VEF");
      if (theValue != NULL) verifier(*this, la_matrice_bloc_sym_de_travail, zone_vef, inverse_quantitee_entrelacee);
//
// Changement de base eventuel P0P1->P1Bulle
//
      if (changement_base())
        changer_base_matrice(la_matrice_de_travail_); //!< A->A~
//
// Modification de la matrice si pas de pression de reference
//
      modifier_matrice(la_matrice_de_travail_);
// Conversion eventuelle en Matrice_Morse_Sym
      if (ref_cast(Navier_Stokes_std, mon_equation.valeur()).solveur_pression().supporte_matrice_morse_sym() &&
          zone_vef.get_alphaE() != nombre_supports) //!< On n'est pas en P0
        {
//
// La matrice retournee est une Matrice_Morse_Sym nettoyee
// si le solveur utilisee supporte ce type de matrice
// et si on n'est pas en P0 seulement (dans ce cas la, la
// conversion en Mat_Morse_Sym n'apporte rien, et plante le SSOR
// car la matrice morse contient alors des parties virtuelles
// alors qu'il n'y a pas d'items communs et on tombe sur
// l'assert assert(*tab2_ptr<=n); Deux autres solutions:
// -Modifier le SSOR pour ne resoudre que la partie reelle
// -Dans le cas de P0 seul, il faudrait vider VV et RV dans la Mat_Bloc_Sym
//
          la_matrice.typer("Matrice_Morse_Sym");
          ref_cast(Matrice_Bloc_Sym, la_matrice_de_travail_.valeur()).BlocSymToMatMorseSym(
            ref_cast(Matrice_Morse_Sym, la_matrice.valeur()));
          ref_cast(Matrice_Morse_Sym, la_matrice.valeur()).compacte(
            2);//!< Suppression des coefficients nuls et quasi non nuls
        }
      else
        {
//
// La matrice retournee est une Matrice_Bloc_Sym nettoyee
//
          la_matrice = la_matrice_de_travail_;
          for (int i = 0; i < nombre_supports; i++)
            for (int j = i; j < nombre_supports; j++)
              {
                Matrice_Bloc_Sym& mat_bloc_sym = ref_cast(Matrice_Bloc_Sym, la_matrice.valeur());
                Matrice_Bloc& bloc_ij = ref_cast(Matrice_Bloc, mat_bloc_sym.get_bloc(i, j).valeur());
                ref_cast(Matrice_Morse, bloc_ij.get_bloc(0, 0).valeur()).compacte(
                  2); //!< Suppression des coefficients nuls et quasi non nuls
              }
        }
    }
// Si pas deja fait, on prends un solveur (SolveurPP1B) qui fera les changements de base pour la solution et le second membre
  if (changement_base() && solveur_pression.valeur().que_suis_je() != "SolveurPP1B")
    {
      SolveurSys solveur_pression_lu = solveur_pression;
      solveur_pression.typer("SolveurPP1B");
      SolveurPP1B& solveur_pression_PP1B = ref_cast(SolveurPP1B, solveur_pression.valeur());
      solveur_pression_PP1B.associer(*this, solveur_pression_lu);
    }
//
// Affichage eventuel du conditionnement de la matrice
//
  char* theValue2 = getenv("TRUST_CONDITIONNEMENT_MATRICE");
  if(theValue2 != NULL)
    Cout << "Estimation du conditionnement de la matrice: " << estim_cond(la_matrice)<<finl;
  return 1;
}
References assemblerP0P0(), assemblerP0P1(), assemblerP0Pa(), assemblerP1P1(), assemblerP1Pa(), assemblerPaPa(), SolveurPP1B::associer(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), Assembleur_P_VEF::calculer_inv_volume(), Cerr, changement_base(), changer_base_matrice(), Cout, Zone::creer_tableau_elements(), Matrice_Bloc_Sym::dimensionner(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Joint::epaisseur(), estim_cond(), Process::exit(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Zone_VEF_PreP1b::get_cl_pression_sommet_faible(), Zone::joint(), la_matrice_de_travail_, Assembleur_P_VEF::la_zone_Cl_VEF, modifieP1P1neumann(), modifier_matrice(), mon_equation, Process::mp_sum(), Matrice_Bloc::nb_bloc_lignes(), Zone::nb_joints(), Matrice_Bloc::nb_lignes(), Process::nproc(), Objet_U::que_suis_je(), ref_cast, Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTVect< _TYPE_ >::size_totale(), sub_type, Deriv_::typer(), updateP0P0(), updateP0P1(), updateP0Pa(), updateP1P1(), updateP1Pa(), updatePaPa(), Ref_Equation_base::valeur(), Deriv_Matrice_Base::valeur(), Deriv_SolveurSys_base::valeur(), Ref_Zone_Cl_VEF::valeur(), verifier(), zero(), Zone_dis_base::zone(), and zone_Vef().
Referenced by assembler_rho_variable().
assembler_rho_variable()
int Assembleur_P_VEFPreP1B::assembler_rho_variable (Matrice & mat, const Champ_Don_base & rho) override virtual
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
Reimplemented from Assembleur_base.
Definition at line 180 of file Assembleur_P_VEFPreP1B.cpp.
{
// On multiplie par la masse volumique aux faces
  if (!sub_type(Champ_Fonc_P1NC, rho))
    {
      Cerr << "La masse volumique n'est pas aux faces dans Assembleur_P_VEFPreP1B::assembler_rho_variable." << finl;
      Process::exit();
    }
  const DoubleVect& volumes_entrelaces=zone_Vef().volumes_entrelaces();
  const DoubleVect& masse_volumique=rho.valeurs();
  DoubleVect quantitee_entrelacee(volumes_entrelaces);
  int size=quantitee_entrelacee.size_array();
  for (int i=0; i<size; i++)
    quantitee_entrelacee(i)=(volumes_entrelaces(i)*masse_volumique(i));
// On assemble la matrice
  return assembler_mat(la_matrice,quantitee_entrelacee,1,1);
}
References assembler_mat(), Cerr, Process::exit(), finl, TRUSTArray< _TYPE_ >::size_array(), sub_type, Champ_Don_base::valeurs(), Zone_VF::volumes_entrelaces(), and zone_Vef().
changement_base()
int Assembleur_P_VEFPreP1B::changement_base () const inline
Definition at line 55 of file Assembleur_P_VEFPreP1B.h.
  {
    return (beta!=0);
  };
References beta.
Referenced by assembler_mat().
changer_base_matrice()
void Assembleur_P_VEFPreP1B::changer_base_matrice (Matrice & la_matrice)
A->A~ (P0+P1->P1Bulle)
< P0+P1 uniquement
Definition at line 1160 of file Assembleur_P_VEFPreP1B.cpp.
{
  assert(zone_Vef().get_alphaE() && zone_Vef().get_alphaS() && !zone_Vef().get_alphaA()); //!< P0+P1 uniquement
  Cerr << "Changement de base pour la matrice: P0+P1->P1Bulle" << finl;
  Matrice_Bloc_Sym& matrice=ref_cast(Matrice_Bloc_Sym, la_matrice.valeur());
  Matrice_Bloc& A00=ref_cast(Matrice_Bloc, matrice.get_bloc(0,0).valeur());
  Matrice_Bloc& A01=ref_cast(Matrice_Bloc, matrice.get_bloc(0,1).valeur());
  Matrice_Bloc& A11=ref_cast(Matrice_Bloc, matrice.get_bloc(1,1).valeur());
// Modification du bloc A11
// As1s2~=As1s2-beta*[somme(Ak1s2)(s1 appartient a k1)+somme(Ak1s1)(s2 appartenant a k1)]+beta*beta*somme(Ak1k2)(s1 appartenant a k1 et s2 appartenant a k2)
  operation11(A00,A01,A11,beta,zone_Vef().zone());
// Modification du bloc A01
// Ak1s~=alpha*Ak1s - alpha*beta*somme(Ak1k2)(s appartenant a k2)
  A01*=alpha;
  operation01(A00,A01,alpha,beta,zone_Vef().zone());
// Modification du bloc A00
// Ak1k2~ = alpha * alpha * Ak1k2
  A00*=alpha*alpha;
}
References alpha, beta, Cerr, finl, Matrice_Bloc_Sym::get_bloc(), operation01(), operation11(), ref_cast, Deriv_Matrice_Base::valeur(), and zone_Vef().
Referenced by assembler_mat().
changer_base_pression()
void Assembleur_P_VEFPreP1B::changer_base_pression (DoubleVect & x)
x->x~ (P0+P1->P1Bulle) Ne sert que pour les tests
< P0+P1 uniquement xk~ = xk / alpha + beta / alpha * somme(xs)(s appartenant a k) xs~ = xs
Definition at line 1227 of file Assembleur_P_VEFPreP1B.cpp.
{
  assert(zone_Vef().get_alphaE() && zone_Vef().get_alphaS() && !zone_Vef().get_alphaA()); //!< P0+P1 uniquement xk~ = xk / alpha + beta / alpha * somme(xs)(s appartenant a k) xs~ = xs
//
//
  const IntTab& les_elems=zone_Vef().zone().les_elems();
  const Domaine& dom=zone_Vef().zone().domaine();
  int nb_elem_tot=zone_Vef().nb_elem_tot();
  int nb_som_elem=les_elems.dimension(1);
  for (int k=0; k<nb_elem_tot; k++)
    {
      x(k) /= alpha;
      double somme=0;
      for (int som=0; som<nb_som_elem; som++)
        {
          int s = nb_elem_tot+dom.get_renum_som_perio(les_elems(k,som));
          somme += x(s);
        }
      x(k) += beta / alpha * somme;
    }
  assert(check_espace_virtuel_vect(x));
}
References alpha, beta, check_espace_virtuel_vect(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Domaine::get_renum_som_perio(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::zone(), and zone_Vef().
Referenced by SolveurPP1B::resoudre_systeme().
changer_base_pression_inverse()
void Assembleur_P_VEFPreP1B::changer_base_pression_inverse (DoubleVect & x) const
x~->x (P1Bulle->P0+P1)
< P0+P1 uniquement xk = alpha * xk~ - beta * somme(xs~)(s appartenant a k) xs = xs~
Definition at line 1205 of file Assembleur_P_VEFPreP1B.cpp.
{
  assert(zone_Vef().get_alphaE() && zone_Vef().get_alphaS() && !zone_Vef().get_alphaA()); //!< P0+P1 uniquement xk = alpha * xk~ - beta * somme(xs~)(s appartenant a k) xs = xs~
//
//
  const IntTab& les_elems=zone_Vef().zone().les_elems();
  const Domaine& dom=zone_Vef().zone().domaine();
  int nb_elem_tot=zone_Vef().nb_elem_tot();
  int nb_som_elem=les_elems.dimension(1);
  for (int k=0; k<nb_elem_tot; k++)
    {
      double somme=0;
      for (int som=0; som<nb_som_elem; som++)
        {
          int s = nb_elem_tot+dom.get_renum_som_perio(les_elems(k,som));
          somme += x(s);
        }
      x(k) = alpha * x(k) - beta * somme;
    }
  assert(check_espace_virtuel_vect(x));
}
References alpha, beta, check_espace_virtuel_vect(), TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), Domaine::get_renum_som_perio(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::zone(), and zone_Vef().
Referenced by SolveurPP1B::resoudre_systeme().
changer_base_second_membre()
void Assembleur_P_VEFPreP1B::changer_base_second_membre (DoubleVect & y)
y->y~ (P0+P1->P1Bulle)
< P0+P1 uniquement ys~ = ys - beta * somme(yk)(s appartenant a k) yk~ = alpha * yk
Definition at line 1184 of file Assembleur_P_VEFPreP1B.cpp.
{
  assert(zone_Vef().get_alphaE() && zone_Vef().get_alphaS() && !zone_Vef().get_alphaA()); //!< P0+P1 uniquement ys~ = ys - beta * somme(yk)(s appartenant a k) yk~ = alpha * yk
//
//
  const IntTab& les_elems=zone_Vef().zone().les_elems();
  const Domaine& dom=zone_Vef().zone().domaine();
  int nb_elem_tot=zone_Vef().nb_elem_tot();
  int nb_som_elem=les_elems.dimension(1);
  for (int k=0; k<nb_elem_tot; k++)
    {
      for (int som=0; som<nb_som_elem; som++)
        {
          int s = nb_elem_tot+dom.get_renum_som_perio(les_elems(k,som));
          y(s) -= beta * y(k);
        }
      y(k) *= alpha;
    }
  y.echange_espace_virtuel();
}
References alpha, beta, TRUSTTab< _TYPE_ >::dimension(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Domaine::get_renum_som_perio(), Zone::les_elems(), Zone_dis_base::nb_elem_tot(), Zone_dis_base::zone(), and zone_Vef().
Referenced by SolveurPP1B::resoudre_systeme().
completer()
void Assembleur_P_VEFPreP1B::completer (const Equation_base & eqn) override virtual
Implements Assembleur_base.
Definition at line 88 of file Assembleur_P_VEFPreP1B.cpp.
{
  mon_equation=eqn;
  Assembleur_P_VEF::completer(eqn);
// Initialisation de alpha, beta
  alpha=0.;
  beta=0.;
  if (zone_Vef().get_P1Bulle())
    {
// Pour changer de base et retrouver le P1Bulle
      alpha=1./Objet_U::dimension;
      beta=1./(Objet_U::dimension*(Objet_U::dimension+1));
    }
  la_matrice_de_travail_.typer("Matrice_Bloc_Sym");
}
References alpha, beta, Assembleur_P_VEF::completer(), Objet_U::dimension, la_matrice_de_travail_, mon_equation, Deriv_::typer(), and zone_Vef().
cree_instance()
Objet_U * Assembleur_P_VEFPreP1B::cree_instance () static
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
duplique()
int Assembleur_P_VEFPreP1B::duplique () const override virtual
Implements Objet_U.
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
equation()
const Equation_base & Assembleur_P_VEFPreP1B::equation () const inline
Definition at line 40 of file Assembleur_P_VEFPreP1B.h.
  {
    if (mon_equation.non_nul()==0)
      {
        Cerr << "\nError in Assembleur_P_VEFPreP1B::equation() : The equation is unknown !" << finl;
        Process::exit();
      }
    return mon_equation.valeur();
  };
References Cerr, Process::exit(), finl, mon_equation, O_U_Ptr::non_nul(), and Ref_Equation_base::valeur().
Referenced by modifier_secmem(), verifier(), and verifier_complet().
get_info()
const Type_info * Assembleur_P_VEFPreP1B::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
info()
const Type_info * Assembleur_P_VEFPreP1B::info () static
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
modifier_matrice()
int Assembleur_P_VEFPreP1B::modifier_matrice (Matrice & la_matrice) override virtual
Modifier eventuellement la matrice pour la rendre definie si elle ne l'est pas
Valeurs par defaut:
Contraintes:
Acces: lecture.
Returns
int
Signification: renvoie 1 si la matrice est modifiee 0 sinon
Contraintes:
Reimplemented from Assembleur_P_VEF.
Definition at line 868 of file Assembleur_P_VEFPreP1B.cpp.
{
  int matrice_modifiee=0;
  has_P_ref=0;
  const Conds_lim& les_cl = la_zone_Cl_VEF.valeur().les_conditions_limites();
  const Zone_VEF_PreP1b& zone_VEF = zone_Vef();
// Recherche s'il y'a une pression de reference, et si oui la matrice n'est pas modifiee
  for(int i=0; i<les_cl.size(); i++)
    if (sub_type(Neumann_sortie_libre,les_cl[i].valeur()))
      {
        has_P_ref=1;
        if (zone_VEF.get_alphaA())
          {
// On en profite pour verifier si la pression est bien nulle si support Pa
            const DoubleTab& val=ref_cast(Neumann_sortie_libre,les_cl[i].valeur()).champ_front().valeurs();
            int nbval=val.dimension(0);
            for (int n=0; n<nbval; n++)
              if (val(n,0)!=0)
                {
                  Cerr << "La condition limite pression imposee non nulle n'est pas encore" << finl;
                  Cerr << "supportee en VEF avec support arete Pa." << finl;
// Le travail est a faire dans Assembleur_P_VEFPreP1B::modifier_secmem_aretes
                  Process::exit();
                }
          }
      }
  Matrice_Bloc_Sym& matrice=ref_cast(Matrice_Bloc_Sym, la_matrice.valeur());
  int P0 = 0;
  int P1 = P0 + zone_VEF.get_alphaE();
  int Pa = P1 + zone_VEF.get_alphaS();
  int CL_neumann=has_P_ref;
//
// Partie P0
//
  if (zone_VEF.get_alphaE())
    {
// On impose une pression de reference sur un element si pas de CL de Neumann
      if (has_P_ref)
        {
          Matrice_Bloc& mat_bloc=ref_cast(Matrice_Bloc,matrice.get_bloc(P0,P0).valeur());
          Matrice_Morse_Sym& A00RR = ref_cast(Matrice_Morse_Sym,mat_bloc.get_bloc(0,0).valeur());
          A00RR.set_est_definie(1);
        }
      matrice_modifiee=Assembleur_P_VEF::modifier_matrice(matrice.get_bloc(P0,P0));
    }
//
// Partie P1
//
  if (zone_VEF.get_alphaS())
    {
      Matrice_Bloc& mat_bloc_p1_p1 = ref_cast(Matrice_Bloc, matrice.get_bloc(P1,P1).valeur());
      Matrice_Morse_Sym& A11RR = ref_cast(Matrice_Morse_Sym,mat_bloc_p1_p1.get_bloc(0,0).valeur());
// On impose une pression de reference sur un sommet si support P0 ou si pas de CL de Neumann
      if (((!(Process::mp_max(CL_neumann))) || ((zone_VEF.get_alphaE()) && (zone_VEF.get_cl_pression_sommet_faible()==1) ) ) && Process::je_suis_maitre())
        {
          int sommet_referent=0;
          double distance=DMAXFLOAT;
          const DoubleTab& coord=zone_VEF.zone().domaine().coord_sommets();
          int nb_som=zone_VEF.zone().nb_som();
          for(int i=0; i<nb_som; i++)
            {
              double tmp=0;
              for (int j=0; j<dimension; j++)
                tmp+=coord(i,j)*coord(i,j);
              if (inf_strict(tmp,distance) && !est_egal(A11RR(i,i),0.))
                {
                  distance=tmp;
                  sommet_referent=i;
                }
            }
// Cerr << "On modifie la ligne (sommet) " << sommet_referent << finl;
          A11RR(sommet_referent,sommet_referent)*=2;
// has_P_ref=1;
          matrice_modifiee=1;
        }
      A11RR.set_est_definie(1);
    }
//
// Partie Pa
//
  if (zone_VEF.get_alphaA())
    {
      Matrice_Bloc& mat_bloc_pa_pa = ref_cast(Matrice_Bloc, matrice.get_bloc(Pa,Pa).valeur());
      Matrice_Morse_Sym& A22RR = ref_cast(Matrice_Morse_Sym,mat_bloc_pa_pa.get_bloc(0,0).valeur());
// On impose une pression de reference sur une arete en P0+Pa uniquement
      if ((zone_VEF.get_alphaE() && !zone_VEF.get_alphaS()) && Process::je_suis_maitre())
        {
          int arete_referente=0;
          double distance=DMAXFLOAT;
          const DoubleTab& coord=zone_VEF.xa();
          int nb_aretes=zone_VEF.zone().nb_aretes();
          for(int i=0; i<nb_aretes; i++)
            {
              double tmp=0;
              for (int j=0; j<dimension; j++)
                tmp+=coord(i,j)*coord(i,j);
              if (tmp<distance && A22RR(i,i)!=0)
                {
                  distance=tmp;
                  arete_referente=i;
                }
            }
// Cerr << "On modifie la ligne (arete) " << arete_referente << finl;
          A22RR(arete_referente,arete_referente)*=2;
// has_P_ref=1;
          matrice_modifiee=1;
        }
      A22RR.set_est_definie(1);
    }
  {
    Matrice_Bloc& bloc_P0_P0 = ref_cast( Matrice_Bloc,matrice.get_bloc(P0,P0).valeur( ) );
    Matrice_Morse_Sym& A00RR = ref_cast( Matrice_Morse_Sym, bloc_P0_P0.get_bloc(0,0).valeur() );
    matrice.set_est_definie( A00RR.get_est_definie( ) );
  }
  return matrice_modifiee;
}
References Cerr, Domaine::coord_sommets(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, DMAXFLOAT, Zone::domaine(), est_egal(), Process::exit(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Matrice_Bloc::get_bloc(), Matrice_Bloc_Sym::get_bloc(), Zone_VEF_PreP1b::get_cl_pression_sommet_faible(), Matrice_Sym::get_est_definie(), Assembleur_P_VEF::has_P_ref, inf_strict(), Process::je_suis_maitre(), Assembleur_P_VEF::la_zone_Cl_VEF, Zone_Cl_dis_base::les_conditions_limites(), Assembleur_P_VEF::modifier_matrice(), Process::mp_max(), Zone::nb_aretes(), Zone::nb_som(), ref_cast, Matrice_Sym::set_est_definie(), vect_impl::size(), sub_type, Deriv_Matrice_Base::valeur(), Ref_Zone_Cl_VEF::valeur(), valeur(), Zone_VF::xa(), Zone_dis_base::zone(), and zone_Vef().
Referenced by assembler_mat().
modifier_secmem()
int Assembleur_P_VEFPreP1B::modifier_secmem (DoubleTab & b) override virtual
< Les aretes superflues ont une valeur nulle
< Les aretes periodiques ont une valeur nulle
< Drapeau pour economiser potentiellement un echange_espace_virtuel
Implements Assembleur_base.
Definition at line 406 of file Assembleur_P_VEFPreP1B.cpp.
{
  const Zone_VEF_PreP1b& la_zone = zone_Vef();
// Verification sur le support Pa
  if (la_zone.get_alphaA())
    {
// Verification sur les aretes que:
      const ArrOfInt& renum_arete_perio=la_zone.get_renum_arete_perio();
      const ArrOfInt& ok_arete=la_zone.get_ok_arete();
      int npa=la_zone.numero_premiere_arete();
// b n'a pas forcement son espace virtuel a jour
      int nb_aretes=la_zone.zone().nb_aretes();
      for(int i=0; i<nb_aretes; i++)
        if(!ok_arete[i] && b(npa+i)!=0.) //!< Les aretes superflues ont une valeur nulle
          {
            Cerr << "Pb div Aretes, la pression sur l'arete " << i << " (qui est superflue) n'est pas nulle." << finl;
            Process::exit();
          }
        else if ( (renum_arete_perio[i]!=i) && b(npa+i)!=0.) //!< Les aretes periodiques ont une valeur nulle
          {
            Cerr << "Pb div Aretes Perio, la pression sur l'arete " << i << " (qui est periodique) n'est pas nulle." << finl;
            Process::exit();
          }
    }
// Verification sur le support P1
  if (la_zone.get_alphaS())
    {
// Verification que la pression sur les sommets periodiques est nulle
      const Domaine& dom=la_zone.zone().domaine();
      int nps=la_zone.numero_premier_sommet();
      int ns=la_zone.zone().nb_som();
      for(int i=0; i<ns; i++)
        {
          int k=dom.get_renum_som_perio(i);
          if((k!=i)&& b(nps+i)!=0.)
            {
              Cerr << "Pb div Som, la pression sur le sommet " << i << " (qui est periodique) n'est pas nulle." << finl;
              Cerr << "En terme clair, le second membre n'est pas nul sur un sommet periodique." << finl;
              if (b(nps+i)!=b(nps+k))
                {
                  Cerr << "En outre, le second membre n'a pas la meme valeur sur les 2 sommets periodiques." << finl;
                  Cerr << "b(nps+i)=" << b(nps+i) << " <> b(nps+k)=" << b(nps+k) << finl;
                }
              Cerr << "Il y'a probabilite que le modele utilise soit mal implemente pour" << finl;
              Cerr << "une condition de periodicite. Contacter le support TRUST." << finl;
              Process::exit();
            }
        }
    }
  if (get_resoudre_en_u())
    {
      const Zone_VEF_PreP1b& zone_VEF =  zone_Vef();
      const Zone_Cl_VEF& zone_Cl = la_zone_Cl_VEF.valeur();
      const DoubleVect& porosite_face = zone_VEF.porosite_face();
      const int nb_cond_lim = zone_Cl.nb_cond_lim();
      /**************************/
      /* Recuperation de Gpoint */
      /**************************/
      DoubleTab Gpoint(equation().inconnue().valeurs());
      Gpoint=0.;
      int Gpoint_nul = 1; //!< Drapeau pour economiser potentiellement un echange_espace_virtuel
      for (int cond_lim=0; cond_lim<nb_cond_lim; cond_lim++)
        {
          const Cond_lim_base& cl_base = zone_Cl.les_conditions_limites(cond_lim).valeur();
          const Front_VF& front_VF = ref_cast(Front_VF,cl_base.frontiere_dis());
          const Champ_front_base& champ_front = cl_base.champ_front().valeur();
          const int ndeb = front_VF.num_premiere_face();
          const int nfin = ndeb+front_VF.nb_faces();
          /* Test sur la nature du champ au bord du domaine */
          if (sub_type(Entree_fluide_vitesse_imposee, cl_base))
            {
              if (sub_type(Champ_front_instationnaire_base,champ_front))
                {
                  Gpoint_nul = 0;
                  const DoubleTab& gpoint =
                    ref_cast(Champ_front_instationnaire_base,champ_front).Gpoint();
                  assert(gpoint.nb_dim()==1);
                  for (int num_face=ndeb; num_face<nfin; num_face++)
                    for (int dim=0; dim<Objet_U::dimension; dim++)
                      Gpoint(num_face,dim)=porosite_face(num_face)*gpoint(dim);
                }//fin du if sur "sub_type(Champ_front_instationnaire_base)"
              else if (sub_type(Champ_front_var_instationnaire,champ_front))
                {
                  Gpoint_nul = 0;
                  const DoubleTab& gpoint =
                    ref_cast(Champ_front_var_instationnaire,champ_front).Gpoint();
                  assert(gpoint.nb_dim()==2);
                  for (int num_face=ndeb; num_face<nfin; num_face++)
                    for (int dim=0; dim<Objet_U::dimension; dim++)
                      Gpoint(num_face,dim)=porosite_face(num_face)*gpoint(num_face-ndeb,dim);
                }//fin du if sur "sub_type(Champ_front_var_instationnaire)"
            }//fin du if sur "sub_type(Entree_fluide_vitesse_imposee)"
        }//fin du for sur "cond_lim"
// Pour le parallele
      if (!Gpoint_nul) Gpoint.echange_espace_virtuel();
      /******************************/
      /* Fin recuperation de Gpoint */
      /******************************/
      /*********************************/
      /* Modification du second membre */
      /*********************************/
      if (zone_VEF.get_alphaE()) modifier_secmem_elem(Gpoint,b);
      if (zone_VEF.get_alphaS()) modifier_secmem_som(Gpoint,b);
      if (zone_VEF.get_alphaA()) modifier_secmem_aretes(Gpoint,b);
      /**********************************/
      /* Fin modification second membre */
      /**********************************/
      b.echange_espace_virtuel();
    }
  return 1;
}
References Cerr, Cond_lim_base::champ_front(), Objet_U::dimension, Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), equation(), Process::exit(), finl, Cond_lim_base::frontiere_dis(), Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Assembleur_base::get_resoudre_en_u(), Assembleur_P_VEF::la_zone_Cl_VEF, Zone_Cl_dis_base::les_conditions_limites(), modifier_secmem_aretes(), modifier_secmem_elem(), modifier_secmem_som(), Zone::nb_aretes(), Zone_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_ >::nb_dim(), Front_VF::nb_faces(), Zone::nb_som(), Front_VF::num_premiere_face(), Zone_VEF_PreP1b::numero_premier_sommet(), Zone_VEF_PreP1b::numero_premiere_arete(), Zone_VF::porosite_face(), ref_cast, sub_type, Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_dis_base::zone(), and zone_Vef().
modifier_secmem_aretes()
int Assembleur_P_VEFPreP1B::modifier_secmem_aretes (const DoubleTab & Gpoint, DoubleTab & b)
Definition at line 679 of file Assembleur_P_VEFPreP1B.cpp.
{
  return 1;
}
Referenced by modifier_secmem().
modifier_secmem_elem()
int Assembleur_P_VEFPreP1B::modifier_secmem_elem (const DoubleTab & Gpoint, DoubleTab & b)
Definition at line 543 of file Assembleur_P_VEFPreP1B.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF =  zone_Vef();
  const Zone_Cl_VEF& zone_Cl = la_zone_Cl_VEF.valeur();
  const int nb_cond_lim = zone_Cl.nb_cond_lim();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  for (int cond_lim=0; cond_lim<nb_cond_lim; cond_lim++)
    {
      const Cond_lim_base& cl_base = zone_Cl.les_conditions_limites(cond_lim).valeur();
      const Front_VF& front_VF = ref_cast(Front_VF,cl_base.frontiere_dis());
      const Champ_front_base& champ_front = cl_base.champ_front().valeur();
      /* Test sur la nature du champ au bord du domaine */
      if (sub_type(Entree_fluide_vitesse_imposee, cl_base))
        {
          if ( sub_type(Champ_front_instationnaire_base,champ_front) ||
               sub_type(Champ_front_var_instationnaire,champ_front)
             )
            {
// Construction de la liste des faces a traiter (reelles + virtuelles)
              const int nb_faces_bord_tot = front_VF.nb_faces_tot();
              for (int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
                {
                  const int num_face =  front_VF.num_face(ind_face);
                  const int elem = face_voisins(num_face,0);
                  assert(elem!=-1);
                  for (int dim=0; dim<Objet_U::dimension; dim++)
                    b(elem)-=Gpoint(num_face,dim)*face_normales(num_face,dim);
                }
            }
        }
    }
  return 1;
}
References Cond_lim_base::champ_front(), Objet_U::dimension, Zone_VEF::face_normales(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Assembleur_P_VEF::la_zone_Cl_VEF, Zone_Cl_dis_base::les_conditions_limites(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), and zone_Vef().
Referenced by modifier_secmem().
modifier_secmem_som()
int Assembleur_P_VEFPreP1B::modifier_secmem_som (const DoubleTab & Gpoint, DoubleTab & b)
Definition at line 587 of file Assembleur_P_VEFPreP1B.cpp.
{
  const Zone_VEF_PreP1b& zone_VEF =  zone_Vef();
  const Zone_Cl_VEF& zone_Cl = la_zone_Cl_VEF.valeur();
  const Zone& zone = zone_VEF.zone();
  const Domaine& domaine = zone.domaine();
  const int nb_cond_lim = zone_Cl.nb_cond_lim();
  const int nb_elem_tot = (zone_VEF.get_alphaE()?zone.nb_elem_tot():0);
  const int nb_faces_elem = zone.nb_faces_elem();
  const double coeff_dim = Objet_U::dimension*(Objet_U::dimension+1);
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_sommets = zone_VEF.face_sommets();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const IntTab& elem_sommets = zone.les_elems();
  const DoubleTab& face_normales = zone_VEF.face_normales();
  ArrOfDouble sigma(Objet_U::dimension);
  for (int cond_lim=0; cond_lim<nb_cond_lim; cond_lim++)
    {
      const Cond_lim_base& cl_base = zone_Cl.les_conditions_limites(cond_lim).valeur();
      const Front_VF& front_VF = ref_cast(Front_VF,cl_base.frontiere_dis());
      const Champ_front_base& champ_front = cl_base.champ_front().valeur();
      /* Test sur la nature du champ au bord du domaine */
      if (sub_type(Entree_fluide_vitesse_imposee, cl_base))
        {
          if ( sub_type(Champ_front_instationnaire_base,champ_front) ||
               sub_type(Champ_front_var_instationnaire,champ_front)
             )
            {
// Construction de la liste des faces a traiter (reelles + virtuelles)
              const int nb_faces_bord_tot = front_VF.nb_faces_tot();
              for (int ind_face=0; ind_face<nb_faces_bord_tot; ind_face++)
                {
                  const int num_face =  front_VF.num_face(ind_face);
                  const int elem = face_voisins(num_face,0);
                  assert(elem!=-1);
// Calcul de la vitesse au centre de l'element
                  sigma=0.;
                  for (int face_loc=0; face_loc<nb_faces_elem; face_loc++)
                    {
                      const int face = elem_faces(elem,face_loc);
                      for(int comp=0; comp<dimension; comp++)
                        sigma[comp]+=Gpoint(face,comp);
                    }
// Calcul de la divergence de la vitesse
                  for(int face_loc=0; face_loc<nb_faces_elem; face_loc++)
                    {
                      const int som = nb_elem_tot+domaine.get_renum_som_perio(elem_sommets(elem,face_loc));
                      const int face = elem_faces(elem,face_loc);
                      double psc=0;
                      double signe=1.;
                      if(elem!=face_voisins(face,0)) signe=-1.;
                      for(int comp=0; comp<dimension; comp++)
                        psc+=sigma[comp]*face_normales(face,comp);
                      b(som)-=signe*psc/coeff_dim;
                    }
                  double flux = 0. ;
                  for (int comp=0; comp<dimension; comp++)
                    flux += Gpoint(num_face,comp) * face_normales(num_face,comp) ;
                  flux*=1./dimension;
                  for(int som_loc=0; som_loc<nb_faces_elem-1; som_loc++)
                    {
                      const int som=domaine.get_renum_som_perio(face_sommets(num_face,som_loc));
                      b(nb_elem_tot+som)-=flux;
                    }
// Fin du calcul de la divergence de la vitesse
                }
            }
        }
    }
  return 1;
}
References Cond_lim_base::champ_front(), Objet_U::dimension, Zone::domaine(), Zone_VF::elem_faces(), Zone_VEF::face_normales(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Zone_VEF_PreP1b::get_alphaE(), Domaine::get_renum_som_perio(), Assembleur_P_VEF::la_zone_Cl_VEF, Zone_Cl_dis_base::les_conditions_limites(), Zone::les_elems(), Zone_Cl_dis_base::nb_cond_lim(), Zone::nb_elem_tot(), Zone::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), ref_cast, sub_type, Deriv_Champ_front_base::valeur(), Deriv_Cond_lim_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_dis_base::zone(), and zone_Vef().
Referenced by modifier_secmem().
modifier_solution()
int Assembleur_P_VEFPreP1B::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Definition at line 684 of file Assembleur_P_VEFPreP1B.cpp.
{
// if (!has_P_ref) exit();
  const Zone_VEF_PreP1b& la_zone = zone_Vef();
// Verification sur les aretes
  if (la_zone.get_alphaA())
    {
// On impose la pression a 0 sur les aretes superflues:
      const IntVect& ok_arete=la_zone.get_ok_arete();
      const ArrOfInt& renum_arete_perio=la_zone.get_renum_arete_perio();
// Nombre d'aretes reelles
      int nb_aretes=ok_arete.size();
      int npa=la_zone.numero_premiere_arete();
      for(int i=0; i<nb_aretes; i++)
        {
          if(!ok_arete(i) && pression(npa+i)!=0.)
            {
              Cerr << "Pb pression arete superflue, P(" << npa+i << ")=" << pression(npa+i) << finl;
              pression(npa+i)=0;
              Process::exit();
            }
          else if ( (renum_arete_perio[i]!=i) && pression(npa+i)!=0.)
            {
              Cerr << "Pb pression arete superflue periodique, P(" << npa+i << ")=" << pression(npa+i) << finl;
              pression(npa+i)=0;
              Process::exit();
            }
        }
    }
// On applique la periodicite sur les sommets pour la pression:
  if (la_zone.get_alphaS())
    {
      const Domaine& dom=la_zone.zone().domaine();
      int nps=la_zone.numero_premier_sommet();
      int ns=la_zone.zone().nb_som();
      for(int i=0; i<ns; i++)
        {
          int k=dom.get_renum_som_perio(i);
          if (k!=i) pression(nps+i)=pression(nps+k);
        }
    }
// pression.echange_espace_virtuel();
// pour retirer le min de la pression si pas de Pref et si que PO sinon on filtre plus tard
  if (la_zone.get_alphaE() && (la_zone.get_alphaS()==0) && (la_zone.get_alphaA()==0) )
    Assembleur_P_VEF::modifier_solution( pression);
// Verification possible par variable d'environnement:
  char* theValue = getenv("TRUST_VERIFIE_DIRICHLET");
  if(theValue != NULL) verifier_dirichlet();
  return 1;
}
References Cerr, Zone::domaine(), Process::exit(), finl, Zone_VEF_PreP1b::get_alphaA(), Zone_VEF_PreP1b::get_alphaE(), Zone_VEF_PreP1b::get_alphaS(), Zone_VEF_PreP1b::get_ok_arete(), Zone_VEF_PreP1b::get_renum_arete_perio(), Domaine::get_renum_som_perio(), Assembleur_P_VEF::modifier_solution(), Zone::nb_som(), Zone_VEF_PreP1b::numero_premier_sommet(), Zone_VEF_PreP1b::numero_premiere_arete(), TRUSTVect< _TYPE_ >::size(), verifier_dirichlet(), Zone_dis_base::zone(), and zone_Vef().
preparer_solution()
int Assembleur_P_VEFPreP1B::preparer_solution (DoubleTab &)
printOn()
Sortie & Assembleur_P_VEFPreP1B::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 41 of file Assembleur_P_VEFPreP1B.cpp.
{
  return Assembleur_base::printOn(s);
}
References Assembleur_base::printOn().
projete_L2()
void Assembleur_P_VEFPreP1B::projete_L2 (DoubleTab & pression) protected
Definition at line 816 of file Assembleur_P_VEFPreP1B.cpp.
{
  if (zone_Vef().get_alphaE()+zone_Vef().get_alphaS()+zone_Vef().get_alphaA()!=3)
    {
      Cerr << "Assembleur_P_VEFPreP1B::projete_L2 ne fonctionne qu'en P0+P1+Pa" << finl;
      Process::exit();
    }
// Cerr << "Projection L2" << finl;
  const Zone_VEF_PreP1b& zone_vef = zone_Vef();
  const Zone& zone = zone_vef.zone();
  int nb_elem_tot=zone.nb_elem_tot();
  int ns=zone.nb_som_tot();
  int nb_elem=zone.nb_elem();
  int i,j;
  const IntTab& som_elem=zone_vef.zone().les_elems();
  const DoubleVect& volumes=zone_vef.volumes();
  double volume_tot=0;
  double somme=0;
  int nsr=nb_elem_tot+ns;
  int nse=zone.nb_som_elem();
  for(i=nb_elem_tot; i<nsr; i++)
    somme+=pression(i);
  somme/=ns;
  for(i=nb_elem_tot; i<nsr; i++)
    pression(i)-=somme;
  static double dalpha =(1./dimension*(dimension+1));
  double pmoy=0;
  for(i=0; i<nb_elem; i++)
    {
      double p=pression(i);
      double v=volumes(i);
      for(j=0; j<nse; j++)
        p+=pression(nb_elem_tot+som_elem(i,j))*dalpha;
      pmoy+=p*v;
      volume_tot+=v;
    }
  pmoy/=volume_tot;
  for(i=0; i<nb_elem; i++)
    pression(i)-=pmoy;
}
References Cerr, Objet_U::dimension, Process::exit(), finl, Zone::les_elems(), Zone::nb_elem(), Zone::nb_elem_tot(), Zone::nb_som_elem(), Zone::nb_som_tot(), Zone_VF::volumes(), Zone_dis_base::zone(), and zone_Vef().
readOn()
Entree & Assembleur_P_VEFPreP1B::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Assembleur_base.
Definition at line 46 of file Assembleur_P_VEFPreP1B.cpp.
{
  return Assembleur_base::readOn(is);
}
References Assembleur_base::readOn().
self_cast() [1/2]
const Assembleur_P_VEFPreP1B & Assembleur_P_VEFPreP1B::self_cast (const Objet_U & r) static
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
self_cast() [2/2]
Assembleur_P_VEFPreP1B & Assembleur_P_VEFPreP1B::self_cast (Objet_U & r) static
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
taille_memoire()
unsigned Assembleur_P_VEFPreP1B::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 37 of file Assembleur_P_VEFPreP1B.cpp.
verifier_dirichlet()
void Assembleur_P_VEFPreP1B::verifier_dirichlet ()
Definition at line 739 of file Assembleur_P_VEFPreP1B.cpp.
{
  if (zone_Vef().get_alphaE()+zone_Vef().get_alphaS()+zone_Vef().get_alphaA()!=dimension)
    {
      Cerr << "Assembleur_P_VEFPreP1B::verifier_dirichlet ne fonctionne pas encore avec votre discretisation" << finl;
      Process::exit();
    }
// Verifications diverses des conditions limites
// en postraitant le resultat dans le champ Divergence_U
  IntVect Faces_de_Dirichlet(zone_Vef().nb_elem_tot());
  IntTab faces(zone_Vef().nb_elem_tot(),2);
  faces=-1;
  const IntTab& face_sommets=zone_Vef().face_sommets();
  Faces_de_Dirichlet=0;
  const Conds_lim& les_cl = la_zone_Cl_VEF.valeur().les_conditions_limites();
  for(int i=0; i<les_cl.size(); i++)
    {
      const Cond_lim& la_cl = les_cl[i];
      const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
      int num1 = le_bord.num_premiere_face();
      int num2 = num1 + le_bord.nb_faces();
      if ((sub_type(Dirichlet, la_cl.valeur()))
          || (sub_type(Dirichlet_homogene, la_cl.valeur())))
        {
          for (int face=num1; face<num2; face++)
            {
              int elem=zone_Vef().face_voisins(face,0);
              if (elem!=-1)
                {
                  Faces_de_Dirichlet(elem)++;
                  if (faces(elem,0)==-1) faces(elem,0)=face;
                  else faces(elem,1)=face;
                }
              elem=zone_Vef().face_voisins(face,1);
              if (elem!=-1) Faces_de_Dirichlet(elem)++;
            }
        }
    }
  DoubleVect& post=ref_cast(Navier_Stokes_std,mon_equation.valeur()).div().valeurs();
  post=0;
  for (int elem=0; elem<Faces_de_Dirichlet.size_array(); elem++)
    {
// post(elem)=Faces_de_Dirichlet(elem);
      if (Faces_de_Dirichlet(elem)>1)
        {
          Cerr << "L'element " << elem << " a " << Faces_de_Dirichlet(elem) << " faces de Dirichlet separees par une ";
          const IntVect& ok_arete=zone_Vef().get_ok_arete();
          const IntTab& aretes_som=zone_Vef().zone().aretes_som();
// Parcours des aretes pour verifier les aretes de bord
          for (int k=0; k<6; k++)
            {
              int arete=zone_Vef().zone().elem_aretes(elem,k);
// Les 2 sommets de l'arete
              int S0=aretes_som(arete,0);
              int S1=aretes_som(arete,1);
// On verifie s'ils sont 2 fois dans les sommets des faces
// auquels cas c'est l'arete qui partage 2 faces de Dirichlet
              int ok=0;
              for (int l=0; l<2; l++)
                {
                  int face=faces(elem,l);
                  for (int s=0; s<3; s++)
                    {
                      if (face_sommets(face,s)==S0) ok++;
                      if (face_sommets(face,s)==S1) ok++;
                    }
                }
              if (ok==4) Cerr << "arete " << (ok_arete(arete)==0?"superflue":"") << finl;
// On compte les aretes superflues
              post(elem)+=(ok_arete(arete)==0);
            }
// Process::exit();
        }
    }
}
References Zone::aretes_som(), Cerr, Objet_U::dimension, Zone::elem_aretes(), Process::exit(), Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Zone_VEF_PreP1b::get_ok_arete(), Assembleur_P_VEF::la_zone_Cl_VEF, Zone_Cl_dis_base::les_conditions_limites(), mon_equation, Front_VF::nb_faces(), Front_VF::num_premiere_face(), ref_cast, vect_impl::size(), TRUSTArray< _TYPE_ >::size_array(), sub_type, Deriv_Cond_lim_base::valeur(), Ref_Equation_base::valeur(), Ref_Zone_Cl_VEF::valeur(), Zone_dis_base::zone(), and zone_Vef().
Referenced by modifier_solution().
zone_Vef()
const Zone_VEF_PreP1b & Assembleur_P_VEFPreP1B::zone_Vef () const
Definition at line 104 of file Assembleur_P_VEFPreP1B.cpp.
{
  return ref_cast(Zone_VEF_PreP1b, la_zone_VEF.valeur());
}
References Assembleur_P_VEF::la_zone_VEF, ref_cast, and Ref_Zone_VEF::valeur().
Referenced by assembler_mat(), assembler_rho_variable(), changer_base_matrice(), changer_base_pression(), changer_base_pression_inverse(), changer_base_second_membre(), completer(), modifier_matrice(), modifier_secmem(), modifier_secmem_elem(), modifier_secmem_som(), modifier_solution(), projete_L2(), and verifier_dirichlet().
Member Data Documentation
alpha
double Assembleur_P_VEFPreP1B::alpha protected
Definition at line 72 of file Assembleur_P_VEFPreP1B.h.
Referenced by changer_base_matrice(), changer_base_pression(), changer_base_pression_inverse(), changer_base_second_membre(), and completer().
beta
double Assembleur_P_VEFPreP1B::beta protected
Coefficients du changement de base P0+P1<->P1Bulle.
Definition at line 72 of file Assembleur_P_VEFPreP1B.h.
Referenced by changement_base(), changer_base_matrice(), changer_base_pression(), changer_base_pression_inverse(), changer_base_second_membre(), and completer().
info_obj
const Type_info Assembleur_P_VEFPreP1B::info_obj static
Definition at line 27 of file Assembleur_P_VEFPreP1B.h.
init
int Assembleur_P_VEFPreP1B::init protected
Definition at line 69 of file Assembleur_P_VEFPreP1B.h.
la_matrice_de_travail_
Matrice Assembleur_P_VEFPreP1B::la_matrice_de_travail_
Matrice de travail.
Definition at line 65 of file Assembleur_P_VEFPreP1B.h.
Referenced by assembler_mat(), and completer().
mon_equation
Ref_Equation_base Assembleur_P_VEFPreP1B::mon_equation protected
Definition at line 70 of file Assembleur_P_VEFPreP1B.h.
Referenced by assembler_mat(), completer(), equation(), and verifier_dirichlet().
The documentation for this class was generated from the following files:
src/P1NCP1B/Solveurs/Assembleur_P_VEFPreP1B.h
src/P1NCP1B/Solveurs/Assembleur_P_VEFPreP1B.cpp