TRUST: Op_Diff_CoviMAC_Face Class Reference
Op_Diff_CoviMAC_Face Class Reference
: class Op_Diff_CoviMAC_Face
<Description of class Op_Diff_CoviMAC_Face>
#include <Op_Diff_CoviMAC_Face.h>
Public Member Functions
Op_Diff_CoviMAC_Face ()
~Op_Diff_CoviMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
int has_interface_blocs () const
double calculer_dt_stab () const
Calcul dt_stab.
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void check_multiphase_compatibility () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Op_Diff_CoviMAC_Face & self_cast (Objet_U &)
static const Op_Diff_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
DoubleVect porosite_e
DoubleVect porosite_f
Private Attributes
double eps = 0.2
Detailed Description
: class Op_Diff_CoviMAC_Face
<Description of class Op_Diff_CoviMAC_Face>
Definition at line 36 of file Op_Diff_CoviMAC_Face.h.
Constructor & Destructor Documentation
Op_Diff_CoviMAC_Face::Op_Diff_CoviMAC_Face ()
Op_Diff_CoviMAC_Face::~Op_Diff_CoviMAC_Face ()
Member Function Documentation
void Op_Diff_CoviMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Operateur_base.
double Op_Diff_CoviMAC_Face::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 82 of file Op_Diff_CoviMAC_Face.cpp.
References IntTab::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_CoviMAC::face_normales(), Zone_VF::face_voisins(), Equation_base::inconnue(), Op_Diff_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), min(), Process::mp_min(), Zone_dis_base::nb_elem(), Op_Diff_CoviMAC_base::nu_, Zone_CoviMAC::nu_dot(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, Op_Diff_CoviMAC_base::update_nu_invh(), valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc::valeurs(), Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins(), &fcl = ref_cast(Champ_Face_CoviMAC, equation().inconnue().valeur()).fcl();
  const DoubleTab& nf = zone.face_normales(),
                   &mu_f = ref_cast(Op_Grad_CoviMAC_Face, ref_cast(Navier_Stokes_std, equation()).operateur_gradient().valeur()).mu_f(), /* poids amont/aval aux faces */
                    *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL,
                     *a_r = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.champ_conserve().passe() : NULL; /* produit alpha * rho */
  const DoubleVect& pe = zone.porosite_elem(), &pf = zone.porosite_face(), &vf = zone.volumes_entrelaces(), &ve = zone.volumes();
  update_nu_invh();
  int i, e, f, n, N = equation().inconnue().valeurs().line_size();
  double dt = 1e10;
  DoubleTrav flux(N), vol(N);
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (flux = 0, vol = pe(e) * ve(e), i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++) for (n = 0; n < N; n++)
          {
            flux(n) += zone.nu_dot(&nu_, e, n, &nf(f, 0), &nf(f, 0)) / vf(f);
            if (fcl(f, 0) < 2) vol(n) = min(vol(n), pf(f) * vf(f) / mu_f(f, n, e != f_e(f, 0))); //cf. Op_Conv_EF_Stab_CoviMAC_Face.cpp
          }
      for (n = 0; n < N; n++) if ((!alp || (*alp)(e, n) > 0.25) && flux(n)) /* sous 0.5e-6, on suppose que l'evanescence fait le job */
          dt = min(dt, vol(n) * (a_r ? (*a_r)(e, n) : 1) / flux(n));
    }
  return Process::mp_min(dt);
}
void Op_Diff_CoviMAC_Face::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 51 of file Op_Diff_CoviMAC_Face.h.
{}; //ok
void Op_Diff_CoviMAC_Face::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Diff_CoviMAC_base.
Definition at line 59 of file Op_Diff_CoviMAC_Face.cpp.
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente(), Cerr, Objet_U::dimension, Joint::epaisseur(), MorEqn::equation(), Process::exit(), finl, Operateur_base::flux_bords_, Equation_base::get_modele(), Equation_base::inconnue(), Zone_CoviMAC::init_equiv(), Zone::joint(), Op_Diff_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), Zone::nb_joints(), O_U_Ptr::non_nul(), porosite_e, Zone_VF::porosite_elem(), porosite_f, Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), DoubleVect::ref(), ref_cast, DoubleTab::resize(), TURBULENCE, Ref_Objet_U::valeur(), Deriv_Champ_Inc_base::valeur(), Ref_Zone_CoviMAC::valeur(), Champ_Inc_base::valeurs(), Mod_turb_hyd_base::viscosite_turbulente(), and Zone_dis_base::zone().
{
  Op_Diff_CoviMAC_base::completer();
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const Equation_base& eq = equation();
  const Champ_Face_CoviMAC& ch = ref_cast(Champ_Face_CoviMAC, eq.inconnue().valeur());
  zone.init_equiv();
  flux_bords_.resize(zone.premiere_face_int(), dimension * ch.valeurs().line_size());
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 1)
    Cerr << "Op_Diff_CoviMAC_Face : largeur de joint insuffisante (minimum 1)!" << finl, Process::exit();
  porosite_e.ref(zone.porosite_elem());
  porosite_f.ref(zone.porosite_face());
  const RefObjU& modele_turbulence = equation().get_modele(TURBULENCE);
  if (modele_turbulence.non_nul())
    {
      const Mod_turb_hyd_base& mod_turb = ref_cast(Mod_turb_hyd_base,modele_turbulence.valeur());
      const Champ_Fonc& alpha_t = mod_turb.viscosite_turbulente();
      associer_diffusivite_turbulente(alpha_t);
    }
}
static Objet_U* Op_Diff_CoviMAC_Face::cree_instance () [static]
void Op_Diff_CoviMAC_Face::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Operateur_base.
int Op_Diff_CoviMAC_Face::duplique () const [virtual]
Implements Op_Diff_CoviMAC_base.
const Type_info* Op_Diff_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
int Op_Diff_CoviMAC_Face::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 44 of file Op_Diff_CoviMAC_Face.h.
  {
    return 1;
  };
static const Type_info* Op_Diff_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
void Op_Diff_CoviMAC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 43 of file Op_Diff_CoviMAC_Face.h.
{ };
Sortie & Op_Diff_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
Definition at line 47 of file Op_Diff_CoviMAC_Face.cpp.
{
  Op_Diff_CoviMAC_base::printOn( os );
  return os;
}
Entree & Op_Diff_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
Reimplemented from Op_Diff_CoviMAC_base.
Definition at line 53 of file Op_Diff_CoviMAC_Face.cpp.
{
  Op_Diff_CoviMAC_base::readOn( is );
  return is;
}
static Op_Diff_CoviMAC_Face& Op_Diff_CoviMAC_Face::self_cast (Objet_U &) [static]
Reimplemented from Op_Diff_CoviMAC_base.
static const Op_Diff_CoviMAC_Face& Op_Diff_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Diff_CoviMAC_base.
unsigned Op_Diff_CoviMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Member Data Documentation
double Op_Diff_CoviMAC_Face::eps = 0.2 [private]
Definition at line 56 of file Op_Diff_CoviMAC_Face.h.
const Type_info Op_Diff_CoviMAC_Face::info_obj [static]
Reimplemented from Op_Diff_CoviMAC_base.
Definition at line 39 of file Op_Diff_CoviMAC_Face.h.
DoubleVect Op_Diff_CoviMAC_Face::porosite_e [protected]
Definition at line 51 of file Op_Diff_CoviMAC_Face.h.
Referenced by completer().
DoubleVect Op_Diff_CoviMAC_Face::porosite_f [protected]
Definition at line 54 of file Op_Diff_CoviMAC_Face.h.
Referenced by completer().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_Face.h
src/CoviMAC/Operateurs/Op_Diff_CoviMAC_Face.cpp