TRUST: Sortie Class Reference
Sortie Class Reference
Classe de base des flux de sortie. Elle sait ecrire des types simples<br>(entiers, flottants) et des Objet_U (via printOn de l'objet_U)
Attention, certains classes derivees sont paralleles: dans ce cas, il faut appeler
syncfile() periodiquement sur tous les processeurs. Voir class EcrFicPartage
Attention: pour ecrire correctement un flux a la fois en ASCII et BINAIRE,
il faut utiliser un Separateur (finl ou space) pour separer les objets ecrits.
#include <Sortie.h>
Public Member Functions
Sortie ()
Sortie (ostream &os)
Sortie (const Sortie &os)
Sortie & operator= (ostream &os)
Sortie & operator= (Sortie &os)
ostream & get_ostream ()
const ostream & get_ostream () const
void set_ostream (ostream *os)
void set_col_width (const int)
Sortie & operator<< (ostream &(*f)(ostream &))
Sortie & operator<< (Sortie &(*f)(Sortie &))
Sortie & operator<< (ios &(*f)(ios &))
virtual Sortie & flush ()
virtual Sortie & lockfile ()
virtual Sortie & unlockfile ()
virtual Sortie & syncfile ()
virtual void setf (std::_Ios_Fmtflags)
virtual void precision (int)
virtual Sortie & operator<< (const Separateur &)
virtual Sortie & operator<< (const Objet_U &ob)
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
virtual Sortie & operator<< (const int &ob)
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
virtual Sortie & operator<< (const unsigned &ob)
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
virtual Sortie & operator<< (const long &ob)
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
virtual Sortie & operator<< (const float &ob)
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
virtual Sortie & operator<< (const double &ob)
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
virtual Sortie & operator<< (const char *ob)
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
virtual int add_col (const double &ob)
virtual int add_col (const char *ob)
virtual int put (const unsigned *ob, int n, int nb_colonnes=1)
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
virtual int put (const int *ob, int n, int nb_colonnes=1)
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
virtual int put (const long *ob, int n, int nb_colonnes=1)
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
virtual int put (const float *ob, int n, int nb_colonnes=1)
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
virtual int put (const double *ob, int n, int nb_colonnes=1)
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
virtual ~Sortie ()
virtual int set_bin (int bin)
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
int is_bin ()
bool has_ostream () const
Protected Attributes
int bin_
int col_width_
Private Attributes
ostream * ostream_
Detailed Description
Classe de base des flux de sortie. Elle sait ecrire des types simples<br>(entiers, flottants) et des Objet_U (via printOn de l'objet_U)
Attention, certains classes derivees sont paralleles: dans ce cas, il faut appeler
syncfile() periodiquement sur tous les processeurs. Voir class EcrFicPartage
Attention: pour ecrire correctement un flux a la fois en ASCII et BINAIRE,
il faut utiliser un Separateur (finl ou space) pour separer les objets ecrits.
Definition at line 60 of file Sortie.h.
Constructor & Destructor Documentation
Sortie::Sortie ()
Definition at line 37 of file Sortie.cpp.
References bin_, col_width_, and ostream_.
{
  bin_=0;
  ostream_=0;
  col_width_ = -1;
}
Sortie::Sortie (ostream & os)
Definition at line 61 of file Sortie.cpp.
References bin_, Process::exit(), and ostream_.
{
  bin_=0;
  if(os.rdbuf())
    {
      ostream_ = new ostream(os.rdbuf());
    }
  else
    {
      Process::exit();
    }
}
Sortie::Sortie (const Sortie & os)
Definition at line 74 of file Sortie.cpp.
References bin_, Cerr, finl, get_ostream(), has_ostream(), and ostream_.
{
  bin_=0;
  if (os.has_ostream())
    {
      Cerr<<"we try to copy a Sortie with ostream !!!"<<finl;
      abort();
      ostream_ = new ostream(os.get_ostream().rdbuf());
    }
  else
    ostream_=0;
}
Sortie::~Sortie () [virtual]
Definition at line 570 of file Sortie.cpp.
References ostream_.
{
  if(ostream_)
    delete ostream_;
  ostream_=0;
}
Member Function Documentation
int Sortie::add_col (const double & ob) [virtual]
Definition at line 126 of file Sortie.cpp.
References bin_, col_width_, and ostream_.
Referenced by Op_VEF_Face::impr(), Op_Div_VEF_Elem::impr(), Op_Grad_VDF_Face::impr(), Op_Grad_PolyMAC_Face::impr(), Op_Div_PolyMAC::impr(), Op_Diff_PolyMAC_base::impr(), Op_Grad_VEF_P1B_Face::impr(), Source_base::impr(), Op_Grad_EF::impr(), Op_EF_base::impr(), Op_Div_EF::impr(), Op_Div_CoviMAC::impr(), Op_Diff_CoviMAC_base::impr(), Op_Conv_CoviMAC_base::impr(), Terme_Source_Constituant::ouvrir_fichier(), Source_base::ouvrir_fichier(), and Operateur_base::ouvrir_fichier().
{
  if (bin_ or col_width_ == -1)
    abort();
  else
    {
      (*ostream_) << std::right << std::setw(col_width_) << ob;
    }
  return ostream_->good();
}
int Sortie::add_col (const char * ob) [virtual]
Definition at line 137 of file Sortie.cpp.
References bin_, col_width_, and ostream_.
{
  if (bin_ or col_width_ == -1)
    abort();
  else
    {
      (*ostream_) << std::right << std::setw(col_width_) << ob;
    }
  return ostream_->good();
}
Sortie & Sortie::flush () [virtual]
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, OBuffer, Sortie_Fichier_base, and Sortie_Nulle.
Definition at line 464 of file Sortie.cpp.
References ostream_.
Referenced by Modele_turbulence_scal_base::a_faire(), Mod_turb_hyd_base::a_faire(), operator<<(), Modele_turbulence_hyd_nul::sauvegarder(), Operateurs_Statistique_tps::sauvegarder(), Postraitement::sauvegarder(), Champ_Inc_base::sauvegarder(), and Champ_Fonc_base::sauvegarder().
{
// get_ostream().flush();
  ostream_->flush();
  return *this;
}
ostream & Sortie::get_ostream ()
Definition at line 111 of file Sortie.cpp.
References ostream_.
Referenced by check_ICEM_binary_file(), Sortie_Brute::get_data(), Sortie_Brute::get_size(), Ecrire_Fichier::interpreter_(), operator=(), read_write_string_from(), Sortie(), and EcrFicPartage::syncfile().
{
  return *ostream_;
}
const ostream & Sortie::get_ostream () const
Definition at line 116 of file Sortie.cpp.
References ostream_.
{
  return *ostream_;
}
bool Sortie::has_ostream () const
Definition at line 596 of file Sortie.cpp.
References ostream_.
Referenced by operator=(), and Sortie().
{
  return (ostream_!=0);
}
int Sortie::is_bin ()
Definition at line 601 of file Sortie.cpp.
References bin_.
{
  return bin_;
}
Sortie & Sortie::lockfile () [virtual]
Reimplemented in EcrFicPartage, and EcrFicPartageMPIIO.
Definition at line 498 of file Sortie.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Sortie::lockfile() : we should not go through it !!"<<finl;
  Process::exit();
  return *this;
}
Sortie & Sortie::operator<< (Sortie &(*)(Sortie &) f)
Definition at line 451 of file Sortie.cpp.
{
  (*f)(*this);
  return *this;
}
Sortie & Sortie::operator<< (const Objet_U & ob) [virtual]
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees)
on appelle simplement ob.printOn (a l'exception de Sortie_Nulle)
Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE,
il faut inserer "\<\< space \<\<" ou "\<\< finl \<\<" pour separer les objets.
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 525 of file Sortie.cpp.
References Objet_U::printOn().
{
  ob.printOn(*this);
  return *this;
}
Sortie & Sortie::operator<< (ios &(*)(ios &) f)
Definition at line 457 of file Sortie.cpp.
References ostream_.
{
  if (ostream_)
    (*f)(*ostream_);
  return *this;
}
Sortie & Sortie::operator<< (const char * ob) [virtual]
Ecriture d'une chaine de caracteres. Attention, pour pouvoir
relire correctement la chaine en mode ascii, celle-ci ne doit
pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 535 of file Sortie.cpp.
References bin_, and ostream_.
{
  if(bin_)
    {
// Ca c'est dommage : dans LIST, il y a "<< blanc <<"
// qui oblige a mettre ce test :
// Il faudrait mettre "<< space <<"  mais cela change les fichiers
// .Zones binaires...
      if (strcmp(ob, " "))
        {
          const int n = strlen(ob) + 1;
          ostream_->write((char *) ob, n * sizeof(char));
        }
    }
  else
    {
      (*ostream_) << ob;
    }
// B.Mathieu, 7/10/2004 : je supprime l'espace apres ecrire(ob).
// Attention, maintenant, il faut faire
// fichier << "chaine" << space << nombre;
// pour pouvoir relire le fichier de facon transparente avec
// fichier >> motcle >> nombre;
// Ancien code:
// if(!bin_)
// ecrire(" ");
  return *this;
}
Sortie & Sortie::operator<< (const int & ob) [virtual]
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 211 of file Sortie.cpp.
References bin_, and ostream_.
{
  if(bin_)
    {
      /* Ecriture en mode binaire */
      ostream_->write((char *) & ob, sizeof(int));
    }
  else
    {
      /* Ecriture avec conversion en ascii */
      (*ostream_) << ob;
    }
  return *this;
}
Sortie & Sortie::operator<< (const unsigned & ob) [virtual]
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 153 of file Sortie.cpp.
References bin_, and ostream_.
{
  if(bin_)
    {
      /* Ecriture en mode binaire */
      ostream_->write((char *) & ob, sizeof(unsigned));
    }
  else
    {
      /* Ecriture avec conversion en ascii */
      (*ostream_) << ob;
    }
  return *this;
}
Sortie & Sortie::operator<< (const long & ob) [virtual]
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 270 of file Sortie.cpp.
References bin_, and ostream_.
{
  if(bin_)
    {
      /* Ecriture en mode binaire */
      ostream_->write((char *) & ob, sizeof(long));
    }
  else
    {
      /* Ecriture avec conversion en ascii */
      (*ostream_) << ob;
    }
  return *this;
}
Sortie & Sortie::operator<< (const float & ob) [virtual]
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 329 of file Sortie.cpp.
References bin_, and ostream_.
{
  if(bin_)
    {
      /* Ecriture en mode binaire */
      ostream_->write((char *) & ob, sizeof(float));
    }
  else
    {
      /* Ecriture avec conversion en ascii */
      (*ostream_) << ob;
    }
  return *this;
}
Sortie & Sortie::operator<< (const double & ob) [virtual]
Methode de bas niveau pour ecrire un int ou flottant dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 387 of file Sortie.cpp.
References bin_, and ostream_.
{
  if(bin_)
    {
      /* Ecriture en mode binaire */
      ostream_->write((char *) & ob, sizeof(double));
    }
  else
    {
      /* Ecriture avec conversion en ascii */
      (*ostream_) << ob;
    }
  return *this;
}
Sortie & Sortie::operator<< (const Separateur & ob) [virtual]
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 471 of file Sortie.cpp.
References bin_, Separateur::ENDL, Separateur::get_type(), ostream_, and Separateur::SPACE.
{
  if (bin_)
    {
// En binaire on n'ecrit pas les separateurs
    }
  else
    {
      switch (ob.get_type())
        {
        case Separateur::ENDL:
// On ecrit "\n" et pas endl...
// C'est peut-etre une mauvaise idee
// (*ostream_) << '\n';
// GF pb sous windows avec ancienne ligne
          (*ostream_)<<endl;
// Flush (important pour les fichiers de log)
          ostream_->flush();
          break;
        case Separateur::SPACE:
          (*ostream_) << ' ';
          break;
        }
    }
  return *this;
}
Sortie & Sortie::operator<< (ostream &(*)(ostream &) f)
Definition at line 442 of file Sortie.cpp.
References bin_, and ostream_.
{
// Ca c'est pas genial, c'est pour permettre  "<< endl"
// Probleme: ca ne marche pas si ostream_ == 0.
  if(ostream_ && !bin_)
    (*f)(*ostream_);
  return *this;
}
Sortie & Sortie::operator= (Sortie & os)
Definition at line 96 of file Sortie.cpp.
References Cerr, finl, get_ostream(), has_ostream(), and ostream_.
{
  if(ostream_)
    delete ostream_;
  if (os.has_ostream())
    {
      Cerr<<"we try to copy a Sortie with ostream !!!"<<finl;
      abort();
      ostream_ = new ostream(os.get_ostream().rdbuf());
    }
  else
    ostream_=0;
  return *this;
}
Sortie & Sortie::operator= (ostream & os)
Definition at line 88 of file Sortie.cpp.
References ostream_.
{
  if(ostream_)
    delete ostream_;
  ostream_ = new ostream(os.rdbuf());
  return *this;
}
void Sortie::precision (int pre) [virtual]
Reimplemented in EcrFicPartage, OBuffer, Sortie_Fichier_base, and Sortie_Nulle.
Definition at line 50 of file Sortie.cpp.
References ostream_.
Referenced by Statistiques::dump(), and Domaine::printOn().
{
  if(ostream_)
    ostream_->precision(pre);
}
int Sortie::put (const int * ob, int n, int nb_colonnes = 1) [virtual]
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 234 of file Sortie.cpp.
References bin_, ostream_, and sz.
{
  assert(n >= 0);
  if (bin_)
    {
      std::streamsize sz = sizeof(int);
      sz *= n;
// Overflow checking :
      assert(sz / (std::streamsize)sizeof(int) == (std::streamsize)n);
      ostream_->write((const char *) ob, sz);
    }
  else
    {
      int j = nb_col;
      for (int i = 0; i < n; i++)
        {
          (*ostream_) << (ob[i]) << (' ');
          j--;
          if (j <= 0)
            {
              (*ostream_) << (endl);
              j = nb_col;
            }
        }
// Si on n'a pas fini pas un retour a la ligne, en ajouter un
      if (j != nb_col && n > 0)
        (*ostream_) << (endl);
      ostream_->flush();
    }
  return ostream_->good();
}
int Sortie::put (const double * ob, int n, int nb_colonnes = 1) [virtual]
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 410 of file Sortie.cpp.
References bin_, ostream_, and sz.
{
  assert(n >= 0);
  if (bin_)
    {
      std::streamsize sz = sizeof(double);
      sz *= n;
// Overflow checking :
      assert(sz / (std::streamsize)sizeof(double) == (std::streamsize)n);
      ostream_->write((const char *) ob, sz);
    }
  else
    {
      int j = nb_col;
      for (int i = 0; i < n; i++)
        {
          (*ostream_) << (ob[i]) << (' ');
          j--;
          if (j <= 0)
            {
              (*ostream_) << (endl);
              j = nb_col;
            }
        }
// Si on n'a pas fini pas un retour a la ligne, en ajouter un
      if (j != nb_col && n > 0)
        (*ostream_) << (endl);
      ostream_->flush();
    }
  return ostream_->good();
}
int Sortie::put (const float * ob, int n, int nb_colonnes = 1) [virtual]
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 352 of file Sortie.cpp.
References bin_, ostream_, and sz.
{
  assert(n >= 0);
  if (bin_)
    {
      std::streamsize sz = sizeof(float);
      sz *= n;
// Overflow checking :
      assert(sz / (std::streamsize)sizeof(float) == (std::streamsize)n);
      ostream_->write((const char *) ob, sz);
    }
  else
    {
      int j = nb_col;
      for (int i = 0; i < n; i++)
        {
          (*ostream_) << (ob[i]) << (' ');
          j--;
          if (j <= 0)
            {
              (*ostream_) << (endl);
              j = nb_col;
            }
        }
// Si on n'a pas fini pas un retour a la ligne, en ajouter un
      if (j != nb_col && n > 0)
        (*ostream_) << (endl);
      ostream_->flush();
    }
  return ostream_->good();
}
int Sortie::put (const unsigned * ob, int n, int nb_colonnes = 1) [virtual]
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 176 of file Sortie.cpp.
References bin_, ostream_, and sz.
Referenced by MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_partie(), ecrit(), IntTab::ecrit(), DoubleTab::ecrit(), IntTab::printOn(), FloatTab::printOn(), DoubleTab::printOn(), ArrOfInt::printOn(), ArrOfFloat::printOn(), ArrOfDouble::printOn(), EcrFicPartage::put(), Format_Post_Lata::write_doubletab(), and Format_Post_Lata::write_inttab().
{
  assert(n >= 0);
  if (bin_)
    {
      std::streamsize sz = sizeof(unsigned);
      sz *= n;
// Overflow checking :
      assert(sz / (std::streamsize)sizeof(unsigned) == (std::streamsize)n);
      ostream_->write((const char *) ob, sz);
    }
  else
    {
      int j = nb_col;
      for (int i = 0; i < n; i++)
        {
          (*ostream_) << (ob[i]) << (' ');
          j--;
          if (j <= 0)
            {
              (*ostream_) << (endl);
              j = nb_col;
            }
        }
// Si on n'a pas fini pas un retour a la ligne, en ajouter un
      if (j != nb_col && n > 0)
        (*ostream_) << (endl);
      ostream_->flush();
    }
  return ostream_->good();
}
int Sortie::put (const long * ob, int n, int nb_colonnes = 1) [virtual]
Methode de bas niveau pour ecrire un tableau d'ints ou reels dans le stream.
Dans l'implementation de la classe de base, on ecrit dans ostream_.
En binaire on utilise ostream::write(), en ascii ostream::operato<<()
En ascii, on revient a la ligne chaque fois qu'on a ecrit "nb_col" valeurs et a la
fin du tableau.
Valeur de retour : ostream_->good()
Reimplemented in EcrFicPartage, EcrFicPartageMPIIO, and Sortie_Nulle.
Definition at line 293 of file Sortie.cpp.
References bin_, ostream_, and sz.
{
  assert(n >= 0);
  if (bin_)
    {
      std::streamsize sz = sizeof(long);
      sz *= n;
// Overflow checking :
      assert(sz / (std::streamsize)sizeof(long) == (std::streamsize)n);
      ostream_->write((const char *) ob, sz);
    }
  else
    {
      int j = nb_col;
      for (int i = 0; i < n; i++)
        {
          (*ostream_) << (ob[i]) << (' ');
          j--;
          if (j <= 0)
            {
              (*ostream_) << (endl);
              j = nb_col;
            }
        }
// Si on n'a pas fini pas un retour a la ligne, en ajouter un
      if (j != nb_col && n > 0)
        (*ostream_) << (endl);
      ostream_->flush();
    }
  return ostream_->good();
}
int Sortie::set_bin (int bin) [virtual]
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention
cependant pour les fichiers Ecrire_Fichier_Partage :
il faut faire le changement uniquement au debut de l'ecriture
d'un bloc, juste apres syncfile() (sinon, mauvaise traduction
des retours a la ligne lors du syncfile suivant).
Reimplemented in EcrFicPartage, OBuffer, SChaine, and Sortie_Brute.
Definition at line 584 of file Sortie.cpp.
References bin_, Cerr, Process::exit(), finl, and ostream_.
Referenced by EcrFicCollecteBin::EcrFicCollecteBin(), DomaineCutter::ecrire_zones(), Fichier_Lata::Fichier_Lata(), Raffiner_isotrope_parallele::interpreter(), Ecrire_Fichier::interpreter_(), DecoupeBord::interpreter_(), SolveurSys_base::save_matrice_secmem_conditionnel(), SChaine::set_bin(), and SFichierBin::SFichierBin().
{
  assert(bin==0 || bin==1);
  bin_ = bin;
  if (ostream_)
    {
      Cerr<<"Error you cant change binary format after open "<<finl;
      assert(0);
      Process::exit();
    }
  return bin_;
}
void Sortie::set_col_width (const int w)
Definition at line 56 of file Sortie.cpp.
References col_width_.
Referenced by Terme_Source_Constituant::ouvrir_fichier(), Source_base::ouvrir_fichier(), and Operateur_base::ouvrir_fichier().
{
  col_width_ = w;
}
void Sortie::set_ostream (ostream * os)
Definition at line 121 of file Sortie.cpp.
References ostream_.
Referenced by OBuffer::new_buffer(), OutputCommBuffer::OutputCommBuffer(), Sortie_Fichier_base::ouvrir(), Sortie_Brute::Sortie_Brute(), Sortie_Fichier_base::Sortie_Fichier_base(), OBuffer::~OBuffer(), and OutputCommBuffer::~OutputCommBuffer().
{
  ostream_ = os;
}
void Sortie::setf (std::_Ios_Fmtflags code) [virtual]
Reimplemented in SChaine, Sortie_Fichier_base, and Sortie_Nulle.
Definition at line 44 of file Sortie.cpp.
References ostream_.
Referenced by Domaine::printOn(), and SChaine::setf().
{
  if(ostream_)
    ostream_->setf(code);
}
Sortie & Sortie::syncfile () [virtual]
Reimplemented in EcrFicPartage, and EcrFicPartageMPIIO.
Definition at line 512 of file Sortie.cpp.
References Cerr, Process::exit(), and finl.
Referenced by ecrit(), EcritureLectureSpecial::ecriture_special(), ecriture_special_part2(), and Fichier_Lata::syncfile().
{
  Cerr<<"Sortie::syncfile() : we should not go through it !!"<<finl;
  Process::exit();
  return *this;
}
Sortie & Sortie::unlockfile () [virtual]
Reimplemented in EcrFicPartage, and EcrFicPartageMPIIO.
Definition at line 505 of file Sortie.cpp.
References Cerr, Process::exit(), and finl.
{
  Cerr<<"Sortie::unlockfile() : we should not go through it !!"<<finl;
  Process::exit();
  return *this;
}
Member Data Documentation
int Sortie::bin_ [protected]
Definition at line 114 of file Sortie.h.
Referenced by add_col(), EcrFicPartageMPIIO::EcrFicPartageMPIIO(), is_bin(), operator<<(), EcrFicPartageMPIIO::operator<<(), OutputCommBuffer::OutputCommBuffer(), Sortie_Fichier_base::ouvrir(), put(), OBuffer::put_null_char(), set_bin(), OBuffer::set_bin(), EcrFicPartage::set_bin(), Sortie(), Sortie_Fichier_base::Sortie_Fichier_base(), and EcrFicPartage::syncfile().
int Sortie::col_width_ [protected]
Definition at line 115 of file Sortie.h.
Referenced by add_col(), set_col_width(), and Sortie().
ostream* Sortie::ostream_ [private]
Definition at line 117 of file Sortie.h.
Referenced by add_col(), flush(), get_ostream(), has_ostream(), operator<<(), operator=(), precision(), put(), set_bin(), set_ostream(), setf(), Sortie(), and ~Sortie().
The documentation for this class was generated from the following files:
src/Kernel/Utilitaires/Sortie.h
src/Kernel/Utilitaires/Sortie.cpp