TRUST: EDO_Pression_th_VDF_Gaz_Parfait Class Reference
EDO_Pression_th_VDF_Gaz_Parfait Class Reference
classe EDO_Pression_th_VDF_Gaz_Parfait
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VDF et pour les gaz parfaits.
#include <EDO_Pression_th_VDF_Gaz_Parfait.h>
Public Member Functions
EDO_Pression_th_VDF_Gaz_Parfait ()
~EDO_Pression_th_VDF_Gaz_Parfait ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double resoudre (double) override
Resoud l'EDO.
Public Member Functions inherited from EDO_Pression_th_VDF
~EDO_Pression_th_VDF () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
EDO_Pression_th_VDF ()
const Fluide_Quasi_Compressible & le_fluide () const
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
void completer () override
Complete l'EDO : calcule rho sur les faces.
void calculer_grad (const DoubleTab &, DoubleTab &)
double masse_totale (double P, const DoubleTab &T) override
Renvoie la valeur de la pression calculee pour conserver la masse.
void mettre_a_jour_CL (double P) override
double getM0 ()
Public Member Functions inherited from EDO_Pression_th_base
EDO_Pression_th_base ()
~EDO_Pression_th_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer_fluide (const Fluide_Quasi_Compressible &)
Associe le fluide a l'EDO.
virtual void completer ()=0
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void mettre_a_jour_CL (double)=0
virtual double masse_totale (double P, const DoubleTab &T)=0
virtual double resoudre (double)=0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static EDO_Pression_th_VDF_Gaz_Parfait & self_cast (Objet_U &)
static const EDO_Pression_th_VDF_Gaz_Parfait & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_VDF
static const Type_info * info ()
static EDO_Pression_th_VDF & self_cast (Objet_U &)
static const EDO_Pression_th_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from EDO_Pression_th_base
static const Type_info * info ()
static EDO_Pression_th_base & self_cast (Objet_U &)
static const EDO_Pression_th_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_VDF
static const Type_info info_obj
Static Public Attributes inherited from EDO_Pression_th_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime la loi sur un flot de sortie.
Entree & readOn (Entree &) override
Lecture d'une EDO sur un flot d'entree.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from EDO_Pression_th_VDF
Ref_Zone_VDF la_zone
Ref_Zone_Cl_dis la_zone_Cl
double M0
la masse totale initiale
Protected Attributes inherited from EDO_Pression_th_base
Ref_Fluide_Quasi_Compressible le_fluide_
Detailed Description
classe EDO_Pression_th_VDF_Gaz_Parfait
Cette classe represente l'EDO sur la pression associee au schema de
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VDF et pour les gaz parfaits.
Definition at line 32 of file EDO_Pression_th_VDF_Gaz_Parfait.h.
Constructor & Destructor Documentation
EDO_Pression_th_VDF_Gaz_Parfait()
EDO_Pression_th_VDF_Gaz_Parfait::EDO_Pression_th_VDF_Gaz_Parfait ()
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
~EDO_Pression_th_VDF_Gaz_Parfait()
EDO_Pression_th_VDF_Gaz_Parfait::~EDO_Pression_th_VDF_Gaz_Parfait ()
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
Member Function Documentation
cree_instance()
Objet_U * EDO_Pression_th_VDF_Gaz_Parfait::cree_instance () static
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
duplique()
int EDO_Pression_th_VDF_Gaz_Parfait::duplique () const override virtual
Implements Objet_U.
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
get_info()
const Type_info * EDO_Pression_th_VDF_Gaz_Parfait::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from EDO_Pression_th_VDF.
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
info()
const Type_info * EDO_Pression_th_VDF_Gaz_Parfait::info () static
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
printOn()
Sortie & EDO_Pression_th_VDF_Gaz_Parfait::printOn (Sortie & os) const override protected virtual
Imprime la loi sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from EDO_Pression_th_VDF.
Definition at line 45 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
{
  os <<que_suis_je()<< finl;
  return os;
}
References finl, and Objet_U::que_suis_je().
readOn()
Entree & EDO_Pression_th_VDF_Gaz_Parfait::readOn (Entree & is) override protected virtual
Lecture d'une EDO sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from EDO_Pression_th_VDF.
Definition at line 65 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
{
  return is;
}
resoudre()
double EDO_Pression_th_VDF_Gaz_Parfait::resoudre (double Pth_n) override virtual
Resoud l'EDO.
Returns
double
Signification: La nouvelle valeur de la pression
Contraintes:
Implements EDO_Pression_th_base.
Definition at line 85 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
{
  int traitPth = le_fluide_->getTraitementPth();
  const DoubleTab& tempnp1 = le_fluide_->inco_chaleur().valeurs();       //actuel
  if (traitPth==0)
    {
      Cerr<<"on choisit le traitement "<<finl;
      int n_bord ;
      traitPth=1;
      for (n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
        {
          const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
          if (sub_type(Neumann_sortie_libre, la_cl.valeur()))
            {
              traitPth=2;
              return Pth_n;
            }
        }
    }
  double dt = le_fluide_->vitesse()->equation().schema_temps().pas_de_temps();
  if (traitPth==2)   //Cerr << "trait cst" << finl;
    {
      return Pth_n;
    }
  else if (traitPth == 1)
    {
      /*
      //Cerr << "trait cons" << finl;
      double Sco=0,v;
      int elem, nb_elem=la_zone->nb_elem();
      for (elem=0 ; elem<nb_elem ; elem++) {
      v = la_zone->volumes(elem);
      //V += v;
      //rho_moy += tab_rho(elem) *v;
      Sco += v/tempnp1(elem);
      }
      double Pth = loi_.R()*getM0()/Sco;
      //        Cerr<<"ICI " <<(Pth-Pth_n)/dt<<finl;
      return Pth;
      }
      else
      {
      */
      const DoubleTab& tempn = le_fluide_->inco_chaleur().passe();
      double cn1=0,cn=0,v;
      int elem, nb_elem=la_zone->nb_elem();
      for (elem=0 ; elem<nb_elem ; elem++)
        {
          v = la_zone->volumes(elem);
// V += v;
// rho_moy += tab_rho(elem) *v;
          cn1 += v/tempnp1(elem);
          cn+=v/tempn(elem);
        }
      int n_bord ;
      double cm=0;
      const IntTab& face_voisins=la_zone->face_voisins();
      const DoubleVect& Surface=la_zone->face_surfaces();
// ce n'est pas la bonne vitesse mais on essaye
      const IntVect& orientation=la_zone->orientation();
      for (n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
        {
          const Cond_lim_base& la_cl = la_zone_Cl->les_conditions_limites(n_bord).valeur();
          if (sub_type(Dirichlet, la_cl))
            {
              const Dirichlet& diri=ref_cast(Dirichlet,la_cl);
              const Front_VF& la_front_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
              int ndeb = la_front_dis.num_premiere_face();
              int nfin = ndeb + la_front_dis.nb_faces();
              for (int num_face=ndeb; num_face<nfin; num_face++)
                {
                  int n0 = face_voisins(num_face, 0);
                  double S=Surface(num_face);
                  if (n0 == -1)
                    {
                      n0 = face_voisins(num_face, 1);
                      S*=-1;
                    }
                  cm+=S/tempnp1(n0)*diri.val_imp(num_face-ndeb,orientation(num_face));
                }
            }
          else if (sub_type(Neumann_sortie_libre, la_cl))
            {
              Cerr<<la_cl.que_suis_je()<<" est incompatible avec le traitement conservation_masse pour l'instant"<<finl;
              abort();
            }
        }
// exit();
// Cerr<<"ici "<<cm;
      double cnt=mp_sum(cn);
      double cn1t=mp_sum(cn1);
      double cmt=mp_sum(cm);
      double Pt= Pth_n*cnt/cn1t/(1+dt/cn1t*cmt);
      return Pt;
    }
  Cerr<<" Utilisez traitement conservation_masse ou constant " <<finl;
  abort();
// traitement edo ???
  int n_bord;
  for (n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
      if (sub_type(Neumann_sortie_libre, la_cl.valeur()))
        return Pth_n;
    }
  Cerr<<" Le codage ici est faux !!!!"<<finl;
  Cerr<<" Pour l'instant on bloque"<<finl;
  assert(0);
  exit();
  const DoubleTab& tab_vit = ref_cast(Navier_Stokes_std,le_fluide_->vitesse()->equation()).vitesse()->valeurs();
  const DoubleTab& tempn = le_fluide_->inco_chaleur().passe();        //passe
  const DoubleTab& tab_rho = le_fluide_->masse_volumique().valeurs();    //actuel
  Cerr<<"---EDO : Tnp1="<<tempnp1(0)<<" Tn="<<tempn(0)<<finl;
  int elem, nb_elem=la_zone->nb_elem();
  double V = 0; //mesure du domaine
  double F = 0; //integrale du gradient de U
  double S = 0; //second membre
// double Pth1 = le_fluide_->pression_th1();
  double v;
  const IntTab& elem_faces = la_zone->elem_faces();
  DoubleTrav divU(tab_vit.dimension(0));
  ref_cast(Navier_Stokes_std,le_fluide_->vitesse()->equation()).operateur_divergence().calculer(tab_vit,divU);
  DoubleTrav gradT(tab_vit.dimension(0));
  DoubleTrav Tstar(tab_vit.dimension(0));
  for (elem=0 ; elem<nb_elem ; elem++)
    {
      Tstar(elem) = .5*(tempn(elem)+tempnp1(elem));
    }
  calculer_grad(Tstar,gradT);
  DoubleTab u_gradT(nb_elem);
  int f1,f2,i;
  for (elem=0 ; elem<nb_elem ; elem++)
    {
      u_gradT(elem)=0;
      for (i=0 ; i<dimension ; i++)
        {
          f1 = elem_faces(elem,i);
          f2 = elem_faces(elem,i+dimension);
// u_gradT(elem) += .25* (gradT(f1)+gradT(f2)) * (tab_vit(f1)+tab_vit(f2));
          u_gradT(elem) += .5* (gradT(f1)*tab_vit(f1) + gradT(f2)*tab_vit(f2));
        }
    }
  for (elem=0 ; elem<nb_elem ; elem++)
    {
      v = la_zone->volumes(elem);
      V += v;
      S += v * tab_rho(elem) * ((tempnp1(elem)-tempn(elem))/dt + u_gradT(elem));
    }
// int nb_cond_lim = la_zone->nb_front_Cl();
  int ndeb, nfin, face;
  double norm;
  DoubleVect norme(dimension);
  for (n_bord=0; n_bord<la_zone->nb_front_Cl(); n_bord++)
    {
      const Cond_lim& la_cl = la_zone_Cl->les_conditions_limites(n_bord);
      const Front_VF& frontiere_dis = ref_cast(Front_VF,la_cl.frontiere_dis());
      ndeb = frontiere_dis.num_premiere_face();
      nfin = ndeb + frontiere_dis.nb_faces();
// if (sub_type(Neumann_sortie_libre, la_cl.valeur()) || sub_type(Dirichlet_entree_fluide, la_cl.valeur())) {
      for (face=ndeb ; face<nfin ; face++)
        {
          elem = la_zone->face_voisins(face,0);
          norm = la_zone->face_surfaces(face);
          if (elem==-1)
            {
              elem = la_zone->face_voisins(face,1);
              norm *= -1;
            }
// calcul de F=Som(div(U))
          F += tab_vit(face) * norm;
// }
        }
    }
  const Loi_Etat_GP_QC& loi_ = ref_cast(Loi_Etat_GP_QC,le_fluide_->loi_etat().valeur());
  S *= loi_.R();
// Cout<<"Volume="<<V<<finl;
// Cout<<"F="<<F<<finl;
// Cout<<"S="<<S<<finl;
// Cout<<"Vit_CN="<<tab_vit<<finl;
// Cout<<"temp="<<temp<<finl;
// Cout<<"tempn="<<tempn<<finl;
  double Pth = (1./(V/dt+F/2.)) * ((V/dt-F/2.)*Pth_n + S);
// double Pth = (1./(V)) * ((-F)*Pth_n + S);
  Cerr<<"Pression thermo recalculee = "<<Pth<<finl;
// Cout<<"Pression thermo recalculee = "<<Pth<<finl;
// return Pth1;
  return Pth;
  /*
  // Resolution par Euler Implicite => plus stable que Crank Nicholson mais ordre 1
  int traitPth = le_fluide_->getTraitementPth();
  if (traitPth==2) { //Cerr << "trait cst" << finl;
  return Pth_n;
  }
  int n_bord ;
  const DoubleTab& tab_vit_CN = le_fluide_->vitesse().valeurs();
  const DoubleTab& tempnp1 = le_fluide_->inco_chaleur().valeurs();       //actuel
  const DoubleTab& tempn = le_fluide_->inco_chaleur().passe();        //passe
  const DoubleTab& tab_rho = le_fluide_->masse_volumique().valeurs();    //actuel
  const Loi_Etat_GP_QC& loi_ = ref_cast(Loi_Etat_GP_QC,le_fluide_->loi_etat().valeur());
  int elem, nb_elem=la_zone->nb_elem();
  double V = 0; //mesure du domaine
  double F = 0; //integrale du gradient de U
  double S = 0; //second membre
  double rho_moy = 0; //second membre
  //double Pth1 = le_fluide_->pression_th1();
  double dt = le_fluide_->vitesse()->equation().schema_temps().pas_de_temps();
  double v;
  const IntTab& elem_faces = la_zone->elem_faces();
  double Sco=0,Pth;
  if (traitPth == 0)
  { //Cerr << "trait edo" << finl;
  for (elem=0 ; elem<nb_elem ; elem++) {
  v = la_zone->volumes(elem);
  V += v;
  rho_moy += tab_rho(elem) *v;
  S += v * tab_rho(elem) * ((tempnp1(elem)-tempn(elem))/dt)/tempnp1(elem);// + u_gradT(elem));
  // Sco += v/tempnp1(elem);
  }
  //double dp = (getM0()-rho_moy)*loi_.R()/Sco;
  S/=rho_moy;
  Pth = Pth_n/(1- S*dt) ;
  //Cerr<<"Pth "<<Pth<<finl;
  //Cerr << "dt ODE = " << 1/S << finl;
  }
  else if (traitPth == 1)
  { //Cerr << "trait cons" << finl;
  for (elem=0 ; elem<nb_elem ; elem++) {
  v = la_zone->volumes(elem);
  V += v;
  rho_moy += tab_rho(elem) *v;
  Sco += v/tempnp1(elem);
  }
  Pth = loi_.R()*getM0()/Sco;
  //Cerr<<"Pth "<<Pth<<finl;
  }
  Cerr<<"Pression thermo recalculee = "<<Pth<<finl;
  return Pth;
  */
}
References Process::abort(), EDO_Pression_th_VDF::calculer_grad(), Cerr, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, Zone_VF::elem_faces(), Process::exit(), f1, f2, Zone_VF::face_surfaces(), Zone_VF::face_voisins(), finl, Cond_lim::frontiere_dis(), Cond_lim_base::frontiere_dis(), Fluide_Dilatable_base::getTraitementPth(), Fluide_Dilatable_base::inco_chaleur(), EDO_Pression_th_VDF::la_zone, EDO_Pression_th_VDF::la_zone_Cl, EDO_Pression_th_base::le_fluide_, Zone_Cl_dis::les_conditions_limites(), Fluide_Dilatable_base::loi_etat(), Milieu_base::masse_volumique(), Process::mp_sum(), Zone_dis_base::nb_elem(), Front_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), norme(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Champ_Inc::passe(), Objet_U::que_suis_je(), Loi_Etat_GP_base::R(), ref_cast, sub_type, Dirichlet::val_imp(), Deriv_Cond_lim_base::valeur(), Deriv_Loi_Etat_base::valeur(), Champ::valeurs(), Champ_Inc::valeurs(), Fluide_Dilatable_base::vitesse(), and Zone_VF::volumes().
self_cast() [1/2]
const EDO_Pression_th_VDF_Gaz_Parfait & EDO_Pression_th_VDF_Gaz_Parfait::self_cast (const Objet_U & r) static
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
self_cast() [2/2]
EDO_Pression_th_VDF_Gaz_Parfait & EDO_Pression_th_VDF_Gaz_Parfait::self_cast (Objet_U & r) static
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
taille_memoire()
unsigned EDO_Pression_th_VDF_Gaz_Parfait::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 28 of file EDO_Pression_th_VDF_Gaz_Parfait.cpp.
Member Data Documentation
info_obj
const Type_info EDO_Pression_th_VDF_Gaz_Parfait::info_obj static
Definition at line 34 of file EDO_Pression_th_VDF_Gaz_Parfait.h.
The documentation for this class was generated from the following files:
src/ThHyd/Dilatable/Quasi_Compressible/VDF/EDO_Pression_th_VDF_Gaz_Parfait.h
src/ThHyd/Dilatable/Quasi_Compressible/VDF/EDO_Pression_th_VDF_Gaz_Parfait.cpp