TRUST: Sonde_Int Class Reference
Sonde_Int Class Reference
classe Sonde_Int
Cette classe permet d'effectuer l'evolution d'un champ au cours du temps.
On choisit l'ensemble des points sur lesquels on veut sonder un champ et
la periodicite des observations. Les objets Postraitement porte des
des sondes sur les champs a observer, une sonde porte d'ailleurs une
reference sur un postraitement.
#include <Sonde_Int.h>
Public Member Functions
Sonde_Int ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Sonde_Int (const Nom &)
Constructeur d'une sonde a partir de son nom.
void associer_post (const Postraitement &)
Associer le postraitement a la sonde.
void initialiser (const Zone &)
Initialise la sonde. Dimensionne les tableaux,
de valeurs, verifie si les points specifies sont
bien dans la zone de calcul.
void mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de la sonde
effectue le postraitement.
void postraiter (double)
Effectue un postraitement.
Imprime les valeurs du tableau aux positions demandees
sur le fichier associe.
void ouvrir_fichier ()
Ouvre le fichier associe a la sonde. (*.son)
void fermer_fichier ()
Ferme le fichier sur laquelle la sonde ecrit.
const IntVect & le_tableau () const
Renvoie le champ associe.
const DoubleTab & les_positions () const
Renvoie le tableau des positions du champ qui sont sondees.
const IntVect & les_poly () const
Renvoie le tableau des elements qui sont sondes.
void fixer_periode (double)
Fixe la periode avec laquelle on sonde le champ.
double temps () const
Le temps ecoule.
SFichier & fichier ()
Renvoie un flot de sortie Fichier, pointant sur
le fichier de sortie utilise par la sonde.
~Sonde_Int () override
Destructeur. Ferme le fichier avant de detruire l'objet.
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Sonde_Int & self_cast (Objet_U &)
static const Sonde_Int & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Imprime le type de l'objet sur un flot de sortie.
Entree & readOn (Entree &) override
Lit les specifications d'une sonde a partir d'un flot d'entree.
Format:
Sonde_Ints
{
[nom_sonde nom_champ Periode dts Points n x1 y1 [z1] ... xn yn [zn]
[nom_sonde nom_champ Periode dts Segment ns x1 y1 [z1] x2 y2 [z2]
...
}.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
Ref_Postraitement mon_post
Nom nom_
le nom de la sonde
int dim
la dimension de la sone (point:0,segment:1,plan:2,volume:3)
int nbre_points1
int nbre_points2
int nbre_points3
faire des sonde_segment,sonde_plan,etc...
Ref_IntVect mon_tableau
Le tableau sonde.
DoubleTab les_positions_
les coordonnees des sondes ponctuelles
IntVect elem_
les elements contenant les sondes ponctuelles
IntTab valeurs
les valeurs de mon_tableau pour les indices donnes par elem_
double periode
periode d'echantillonnage
double nb_bip
SFichier * le_fichier
Detailed Description
classe Sonde_Int
Cette classe permet d'effectuer l'evolution d'un champ au cours du temps.
On choisit l'ensemble des points sur lesquels on veut sonder un champ et
la periodicite des observations. Les objets Postraitement porte des
des sondes sur les champs a observer, une sonde porte d'ailleurs une
reference sur un postraitement.
Definition at line 38 of file Sonde_Int.h.
Constructor & Destructor Documentation
Sonde_Int() [1/2]
Sonde_Int::Sonde_Int ()
Definition at line 22 of file Sonde_Int.cpp.
:le_fichier(0) { }
Sonde_Int() [2/2]
Sonde_Int::Sonde_Int (const Nom & nom) inline
Constructeur d'une sonde a partir de son nom.
Definition at line 92 of file Sonde_Int.h.
  : nom_(nom), le_fichier(0)
{}
~Sonde_Int()
Sonde_Int::~Sonde_Int () inline override
Destructeur. Ferme le fichier avant de detruire l'objet.
Definition at line 256 of file Sonde_Int.h.
{
  fermer_fichier();
}
References fermer_fichier().
Member Function Documentation
associer_post()
void Sonde_Int::associer_post (const Postraitement & le_post)
Associer le postraitement a la sonde.
Definition at line 295 of file Sonde_Int.cpp.
{
  mon_post=le_post;
  if (mon_post->noms_fichiers_sondes().contient(nom_)==0)
    mon_post->noms_fichiers_sondes().add(nom_);
  else
    {
      Cerr << "The filename " << nom_ << " is used several times for probes." << finl;
      Cerr << "A probe must have a unique filename to avoid writing conflicts." << finl;
      exit();
    }
}
References List_Nom::add(), Cerr, List_Nom::contient(), Process::exit(), finl, mon_post, nom_, and Postraitement::noms_fichiers_sondes().
Referenced by Sondes_Int::readOn().
cree_instance()
Objet_U * Sonde_Int::cree_instance () static
Definition at line 21 of file Sonde_Int.cpp.
duplique()
int Sonde_Int::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Sonde_Int.cpp.
fermer_fichier()
void Sonde_Int::fermer_fichier () inline
Ferme le fichier sur laquelle la sonde ecrit.
Definition at line 133 of file Sonde_Int.h.
{
  if (le_fichier)
    {
      delete le_fichier;
    }
}
References le_fichier.
Referenced by ~Sonde_Int().
fichier()
SFichier & Sonde_Int::fichier () inline
Renvoie un flot de sortie Fichier, pointant sur
le fichier de sortie utilise par la sonde.
Returns
SFichier&
Signification: le fichier de sortie utilise par la sonde
Contraintes:
Definition at line 237 of file Sonde_Int.h.
{
  return *le_fichier;
}
References le_fichier.
Referenced by ouvrir_fichier(), and postraiter().
fixer_periode()
void Sonde_Int::fixer_periode (double pe) inline
Fixe la periode avec laquelle on sonde le champ.
Definition at line 156 of file Sonde_Int.h.
{
  periode=pe;
}
References periode.
get_info()
const Type_info * Sonde_Int::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 21 of file Sonde_Int.cpp.
info()
const Type_info * Sonde_Int::info () static
Definition at line 21 of file Sonde_Int.cpp.
initialiser()
void Sonde_Int::initialiser (const Zone & zone_geom)
Initialise la sonde. Dimensionne les tableaux,
de valeurs, verifie si les points specifies sont
bien dans la zone de calcul.
Definition at line 326 of file Sonde_Int.cpp.
{
  nb_bip = 0.;
  int nbre_points = les_positions_.dimension(0);
  elem_.resize(nbre_points);
  zone_geom.chercher_elements(les_positions_,elem_);
  for (int i=0; i<nbre_points; i++)
    if (mp_max(elem_[i])==-1 && je_suis_maitre())
      {
        Cerr << "The point number " << i+1 << " of probe " << nom_ << finl;
        Cerr << "is outside of the computational domain" << finl;
      }
  if (sub_type(IntTab,mon_tableau.valeur()))
    {
      const IntTab& tab_val = static_cast<const IntTab&>(mon_tableau.valeur());
      valeurs.resize(nbre_points,tab_val.dimension(1));
    }
  else
    valeurs.resize(nbre_points);
}
References Cerr, Zone::chercher_elements(), TRUSTTab< _TYPE_ >::dimension(), elem_, finl, Process::je_suis_maitre(), les_positions_, mon_tableau, Process::mp_max(), nb_bip, nom_, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), sub_type, Ref_IntVect::valeur(), and valeurs.
Referenced by readOn().
le_tableau()
const IntVect & Sonde_Int::le_tableau () const inline
Renvoie le champ associe.
Returns
Champ_base&
Signification: le champ associe
Contraintes: reference constante
Definition at line 176 of file Sonde_Int.h.
{
  return mon_tableau.valeur();
}
References mon_tableau, and Ref_IntVect::valeur().
les_poly()
const IntVect & Sonde_Int::les_poly () const inline
Renvoie le tableau des elements qui sont sondes.
Returns
IntVect&
Signification: les ments qui sont sondes
Contraintes: reference constante
Definition at line 216 of file Sonde_Int.h.
{
  return elem_;
}
References elem_.
les_positions()
const DoubleTab & Sonde_Int::les_positions () const inline
Renvoie le tableau des positions du champ qui sont sondees.
Returns
DoubleTab&
Signification: les positions sondees
Contraintes: reference constante
Definition at line 196 of file Sonde_Int.h.
{
  return les_positions_;
}
References les_positions_.
Referenced by ouvrir_fichier().
mettre_a_jour()
void Sonde_Int::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de la sonde
effectue le postraitement.
Definition at line 522 of file Sonde_Int.cpp.
{
  double nb;
  modf((un_temps-tinit)/periode, &nb);
  if (nb>nb_bip)
    {
      nb_bip=nb;
      postraiter(un_temps);
    }
}
References nb_bip, periode, and postraiter().
ouvrir_fichier()
void Sonde_Int::ouvrir_fichier ()
Ouvre le fichier associe a la sonde. (*.son)
< if (dimension==2)
Definition at line 363 of file Sonde_Int.cpp.
{
  if(je_suis_maitre())
    {
      if( le_fichier)
        delete le_fichier;
      Nom nom_fich(nom_du_cas());
      nom_fich += "_";
      nom_fich += nom_;
      nom_fich += ".son";
      le_fichier=new SFichier(nom_fich);
      SFichier& s = *le_fichier;
      s.setf(ios::scientific);
      s.precision(8);
// Ecriture de l'en tete des fichiers sondes :
      if (dim==0 || dim==1)
        {
          const DoubleTab& p=les_positions();
          int nbre_points = les_positions_.dimension(0);
          s << "# " << nom_fich << finl;
          s << "# Temps";
          for(int i=0; i<nbre_points; i++)
            {
              s << " x=" << p(i,0) << " y=" << p(i,1) ;
              if (dimension==3) fichier() << " z=" << p(i,2) ;
            }
          s << finl;
        }
      if (dim==2)
        {
          s << "TRUST   Version1  01/09/96" << finl;
          s << nom_du_cas() << finl;
          s << "TRUST" << finl;
          s << "GRILLE" << finl;
          Nom nom_grille("Grille");
          Nom nom_topologie("Topologie");
          nom_grille += "_";
          nom_grille += nom_;
          nom_topologie += "_";
          nom_topologie += nom_;
          int k,kn;
          int nbre_points = les_positions_.dimension(0);
          const DoubleTab& p=les_positions();
          double xn,yn,zn,norme;
          if (dimension==3)
            {
              xn=(p(1,2)-p(0,2))*(p(nbre_points1,1)
                                  -p(0,1))-(p(1,1)-p(0,1))*(p(nbre_points1,2)-p(0,2));
              yn=(p(1,0)-p(0,0))*(p(nbre_points1,2)-p(0,2))
                 -(p(1,2)-p(0,2))*(p(nbre_points1,0)-p(0,0));
            }
          else//!< if (dimension==2)
            {
              assert(dimension==2);
              xn=0.;
              yn=0.;
            }
          zn=(p(1,1)-p(0,1))*(p(nbre_points1,0)-p(0,0))
             -(p(1,0)-p(0,0))*(p(nbre_points1,1)-p(0,1));
          norme=std::fabs(xn)+std::fabs(yn)+std::fabs(zn);
          xn/=norme;
          yn/=norme;
          zn/=norme;
          s << nom_grille << " 3 " << 2*nbre_points << finl;
          int i;
          for(i=0; i<nbre_points; i++)
            {
              s << p(i,0) << " " << p(i,1) ;
              if (dimension==3) fichier() << " " << p(i,2) << finl;
              else if (dimension==2) s << " 0." << finl;
            }
          for(i=0; i<nbre_points; i++)
            {
              s << p(i,0)+xn << " " << p(i,1)+yn ;
              if (dimension==3) s << " " << p(i,2)+zn << finl;
              else if (dimension==2) s << " " << zn << finl;
            }
          s << "TOPOLOGIE" << finl;
          s << nom_topologie << " " << nom_grille << finl;
          s << "MAILLE" << finl;
          s << (nbre_points1-1)*(nbre_points2-1) << finl;
          for(int j=0; j<nbre_points2-1; j++)
            for(i=0; i<nbre_points1-1; i++)
              {
                k=j*nbre_points1+i+1;
                kn=k+nbre_points;
                s << "VOXEL8 " << k << " " << k+1 << " ";
                s << k+nbre_points1 << " " << k+nbre_points1+1;
                s << " " << kn << " " << kn+1 << " " << kn+nbre_points1;
                s << " " << kn+nbre_points1+1 << finl;
              }
          s << "FACE" << finl;
          s << "0" << finl;
        }
      if (dim==3)
        {
          s << "TRUST   Version1  01/09/96" << finl;
          s << nom_du_cas() << finl;
          s << "TRUST" << finl;
          s << "GRILLE" << finl;
          Nom nom_grille("Grille");
          Nom nom_topologie("Topologie");
          nom_grille += "_";
          nom_grille += nom_;
          nom_topologie += "_";
          nom_topologie += nom_;
          int k,kn;
          int nbre_points = les_positions_.dimension(0);
          const DoubleTab& p=les_positions();
          s << nom_grille << " 3 " << nbre_points << finl;
          int i;
          for(i=0; i<nbre_points; i++)
            {
              s << p(i,0) << " " << p(i,1) ;
              s << " " << p(i,2) << finl;
            }
          s << "TOPOLOGIE" << finl;
          s << nom_topologie << " " << nom_grille << finl;
          s << "MAILLE" << finl;
          s << (nbre_points1-1)*(nbre_points2-1)*(nbre_points3-1) << finl;
          for(int m=0; m<nbre_points3-1; m++)
            for(int j=0; j<nbre_points2-1; j++)
              for(i=0; i<nbre_points1-1; i++)
                {
                  k=m*nbre_points2*nbre_points1+j*nbre_points1+i+1;
                  kn=k+nbre_points2*nbre_points1;
                  s << "VOXEL8 " << k << " " << k+1 << " ";
                  s << k+nbre_points1 << " " << k+nbre_points1+1;
                  s << " " << kn << " " << kn+1 << " " << kn+nbre_points1;
                  s << " " << kn+nbre_points1+1 << finl;
                }
          s << "FACE" << finl;
          s << "0" << finl;
        }
    }
}
References dim, TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, fichier(), finl, Process::je_suis_maitre(), le_fichier, les_positions(), les_positions_, nbre_points1, nbre_points2, nbre_points3, nom_, Objet_U::nom_du_cas(), norme(), Sortie_Fichier_base::precision(), and Sortie_Fichier_base::setf().
postraiter()
void Sonde_Int::postraiter (double un_temps)
Effectue un postraitement.
Imprime les valeurs du tableau aux positions demandees
sur le fichier associe.
Definition at line 550 of file Sonde_Int.cpp.
{
  if (sub_type(IntTab,mon_tableau.valeur()))
    {
      const IntTab& val_tab= static_cast<const IntTab&>(mon_tableau.valeur());
      int nval = val_tab.dimension(1);
// int i,j;
// int nb_compo=valeurs.nb_dim();
      int nbre_points = les_positions_.dimension(0);
      for (int i=0; i<nbre_points; i++)
        for (int j=0; j<nval; j++)
          valeurs(i,j) = val_tab(elem_(i),j);
      if(je_suis_maitre())
        {
          int p;
          int nbproc = Process::nproc();
          IntTab valeurs_pe;
          int val_max;
          for(p=1; p<nbproc; p++)
            {
              recevoir(valeurs_pe,p,0,p);
              int n1=valeurs.dimension(0);
              int n2=valeurs.dimension(1);
              int k;
              for(int i=0; i<n1; i++)
                for(k=0; k<n2; k++)
                  {
#ifdef INT_is_64_
                    val_max = std::max(labs(valeurs(i,k)),labs(valeurs_pe(i,k)));
                    if(val_max==(labs(valeurs_pe(i,k))))
                      valeurs(i,k)=valeurs_pe(i,k);
#else
                    val_max = std::max(abs(valeurs(i,k)),abs(valeurs_pe(i,k)));
                    if(val_max==(abs(valeurs_pe(i,k))))
                      valeurs(i,k)=valeurs_pe(i,k);
#endif
                  }
            }
          if (dim==0 || dim==1)
            {
              fichier() << un_temps;
              for(int i=0; i<valeurs.dimension(0); i++)
                for(int k=0; k<valeurs.dimension(1); k++)
                  fichier() << " " << valeurs(i,k);
              fichier() << finl;
            }
// Pour les sondes type plan, impression au format lml :
// num_sommet comp1 [comp2] [comp3]
// et dans la troisieme direction :
          else if (dim==2 || dim==3)
            {
              Nom unite;
              Nom nom_topologie("Topologie");
              nom_topologie += "_";
              nom_topologie += nom_;
              fichier() << "TEMPS " << un_temps << "\n";
              fichier() << "CHAMPOINT " << nom_ << " " << nom_topologie
                        << " " << un_temps << "\n";
              fichier() << nom_ << " " << nval << " " << unite << "\n";
              int nbp=nbre_points;
              if (dim==2) nbp*=2;
              fichier() << "type1 " << nbp << "\n";
              int i;
              for(i=0; i<nbre_points; i++)
                {
                  fichier() << i+1;
                  for(int j=0; j<valeurs.dimension(1); j++)
                    fichier() << " " << valeurs(i,j);
// Pour ne pas flusher :
                  fichier() << "\n";
                }
// Pour le 2D, on rajoute une direction
              if (dim==2)
                {
                  for(i=0; i<nbre_points; i++)
                    {
                      fichier() << nbre_points+i+1;
                      for(int j=0; j<valeurs.dimension(1); j++)
                        fichier() << " " << valeurs(i,j);
// Pour ne pas flusher :
                      fichier() << "\n";
                    }
                }
            }
          fichier().flush();
        }
      else
        envoyer(valeurs,Process::me(),0,Process::me());
    }
  else
    {
      const IntVect& val_tab= static_cast<const IntVect&>(mon_tableau.valeur());
      int nval =1;
// int nb_compo=valeurs.nb_dim();
      int nbre_points = les_positions_.dimension(0);
      for (int i=0; i<nbre_points; i++)
        valeurs(i) = val_tab(elem_(i));
      if(je_suis_maitre())
        {
          int p;
          int nbproc = Process::nproc();
          IntTab valeurs_pe;
          int val_max;
          for(p=1; p<nbproc; p++)
            {
              recevoir(valeurs_pe,p,0,p);
              for(int i=0; i<valeurs.dimension(0); i++)
                {
#ifdef INT_is_64_
                  val_max = std::max(labs(valeurs(i)),labs(valeurs_pe(i)));
                  if(val_max==(labs(valeurs_pe(i))))
                    valeurs(i)=valeurs_pe(i);
#else
                  val_max = std::max(abs(valeurs(i)),abs(valeurs_pe(i)));
                  if(val_max==(abs(valeurs_pe(i))))
                    valeurs(i)=valeurs_pe(i);
#endif
                }
            }
          if (dim==0 || dim==1)
            {
              fichier() << un_temps;
              for(int i=0; i<valeurs.dimension(0); i++)
                fichier() << " " << valeurs(i);
              fichier() << finl;
            }
// Pour les sondes type plan, impression au format lml :
// num_sommet comp1 [comp2] [comp3]
// et dans la troisieme direction :
          else if (dim==2 || dim==3)
            {
              Nom unite;
              Nom nom_topologie("Topologie");
              nom_topologie += "_";
              nom_topologie += nom_;
              fichier() << "TEMPS " << un_temps << "\n";
              fichier() << "CHAMPOINT " << nom_ << " " << nom_topologie
                        << " " << un_temps << "\n";
              fichier() << nom_ << " " << nval << " " << unite << "\n";
              int nbp=nbre_points;
              if (dim==2) nbp*=2;
              fichier() << "type0 " << nbp << "\n";
// int i;
              for(int i=0; i<nbre_points; i++)
                {
                  fichier() << i+1;
                  fichier() << " " << valeurs(i);
// Pour ne pas flusher :
                  fichier() << "\n";
                }
// Pour le 2D, on rajoute une direction
              if (dim==2)
                {
                  for(int i=0; i<nbre_points; i++)
                    {
                      fichier() << nbre_points+i+1;
                      fichier() << " " << valeurs(i);
// Pour ne pas flusher :
                      fichier() << "\n";
                    }
                }
            }
          fichier().flush();
        }
      else
        envoyer(valeurs,Process::me(),0,Process::me());
    }
}
References dim, TRUSTTab< _TYPE_ >::dimension(), elem_, envoyer(), fichier(), finl, Sortie_Fichier_base::flush(), Process::je_suis_maitre(), les_positions_, Process::me(), mon_tableau, nom_, Process::nproc(), recevoir(), sub_type, Ref_IntVect::valeur(), and valeurs.
Referenced by mettre_a_jour().
printOn()
Sortie & Sonde_Int::printOn (Sortie & s) const override protected virtual
Imprime le type de l'objet sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 39 of file Sonde_Int.cpp.
{
  return s << que_suis_je();
}
References Objet_U::que_suis_je().
readOn()
Entree & Sonde_Int::readOn (Entree & is) override protected virtual
Lit les specifications d'une sonde a partir d'un flot d'entree.
Format:
Sonde_Ints
{
[nom_sonde nom_champ Periode dts Points n x1 y1 [z1] ... xn yn [zn]
[nom_sonde nom_champ Periode dts Segment ns x1 y1 [z1] x2 y2 [z2]
...
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 68 of file Sonde_Int.cpp.
{
  assert(mon_post.non_nul());
  Probleme_base& pb = mon_post->probleme();
  Motcle motlu;
  Motcle accolade_ouverte("{");
  Motcle accolade_fermee("}");
  int nbre_points;
// initialisation de periode par defaut
  periode = 1.e10;
// Recherche du tableau sonde
// Remplissage de la reference au tableau
  is >> motlu;
  Noms liste_noms;
  pb.get_noms_champs_postraitables(liste_noms);
//
// if (liste_noms.contient(motlu))
  for (int i=0; i<liste_noms.size(); i++)
    {
      if (liste_noms[i]==motlu)
        {
          REF(IntVect) ref_tab;
//
          if (pb.a_pour_IntVect(motlu,ref_tab))
            mon_tableau = ref_tab;
          else
            {
              Cerr << "The problem does not have the array " << motlu << finl;
              exit();
            }
        }
    }
  /*
      else
      if (!ref_tab.non_nul())
      {
      Cerr << "The array name " << motlu << " is not understood by the problem" << finl;
      exit();
      }
  */
// Lecture des caracteristiques de la sonde
  IntVect fait(2);
  Motcles les_motcles(6);
  {
    les_motcles[0] = "periode";
    les_motcles[1] = "point";
    les_motcles[2] = "points";
    les_motcles[3] = "segment";
    les_motcles[4] = "plan";
    les_motcles[5] = "volume";
  }
  while ((fait(0) != 1) || (fait(1) != 1))
    {
      is >> motlu;
      if (motlu == accolade_fermee)
        {
          Cerr << "Error while reading the probe " << nom_ <<finl;
          Cerr << "The data of the probe were not defined" << finl;
          exit();
        }
      int rang=les_motcles.search(motlu);
      if (rang == -1)
        {
          Cerr << "Error while reading the probe " << nom_ <<finl;
          Cerr << motlu << " is not understood; the keywords understood are : " << finl;
          Cerr << les_motcles;
          exit();
        }
      switch(rang)
        {
        case 0:
          {
            is >> periode;
            break;
          }
        case 1:
        case 2:
          {
            rang = 1;
            dim = 0;
            is >> nbre_points;
            les_positions_.resize(nbre_points,dimension);
            for (int i=0; i<nbre_points; i++)
              for (int j=0; j<dimension; j++)
                is >> les_positions_(i,j);
            break;
          }
        case 3:
          {
            rang = 1;
            dim = 1;
            DoubleVect origine(dimension);
            DoubleVect extremite(dimension);
            DoubleVect dx(dimension);
            int i=0,j=0;
            is >> nbre_points;
            les_positions_.resize(nbre_points,dimension);
            for (; i<dimension; i++)
              is >> origine(i);
            for (i=0; i<dimension; i++)
              is >> extremite(i);
            for (i=0; i<dimension; i++)
              dx(i)=(extremite(i)-origine(i))/(nbre_points-1);
            for (i=0; i<nbre_points; i++)
              for (j=0; j<dimension; j++)
                les_positions_(i,j)=origine(j)+i*dx(j);
            break;
          }
        case 4:
          {
            rang = 1;
            dim = 2;
            DoubleVect origine(dimension);
            DoubleVect extremite1(dimension);
            DoubleVect extremite2(dimension);
            DoubleVect dx1(dimension);
            DoubleVect dx2(dimension);
            int i=0,j=0,k=0;
            is >> nbre_points1;
            is >> nbre_points2;
            nbre_points=nbre_points1*nbre_points2;
            les_positions_.resize(nbre_points,dimension);
            for (; i<dimension; i++)
              is >> origine(i);
            for (i=0; i<dimension; i++)
              is >> extremite1(i);
            for (i=0; i<dimension; i++)
              is >> extremite2(i);
            for (i=0; i<dimension; i++)
              dx1(i)=(extremite1(i)-origine(i))/(nbre_points1-1);
            for (i=0; i<dimension; i++)
              dx2(i)=(extremite2(i)-origine(i))/(nbre_points2-1);
            for (i=0; i<nbre_points1; i++)
              for (j=0; j<nbre_points2; j++)
                for (k=0; k<dimension; k++)
                  les_positions_(i*nbre_points2+j,k)=origine(k)+i*dx1(k)+j*dx2(k);
            break;
          }
        case 5:
          {
            rang = 1;
            dim = 3;
            DoubleVect origine(dimension);
            DoubleVect extremite1(dimension);
            DoubleVect extremite2(dimension);
            DoubleVect extremite3(dimension);
            DoubleVect dx1(dimension);
            DoubleVect dx2(dimension);
            DoubleVect dx3(dimension);
            int i=0,j=0,k=0;
            is >> nbre_points1;
            is >> nbre_points2;
            is >> nbre_points3;
            nbre_points=nbre_points1*nbre_points2*nbre_points3;
            les_positions_.resize(nbre_points,dimension);
            for (; i<dimension; i++)
              is >> origine(i);
            for (i=0; i<dimension; i++)
              is >> extremite1(i);
            for (i=0; i<dimension; i++)
              is >> extremite2(i);
            for (i=0; i<dimension; i++)
              is >> extremite3(i);
            for (i=0; i<dimension; i++)
              dx1(i)=(extremite1(i)-origine(i))/(nbre_points1-1);
            for (i=0; i<dimension; i++)
              dx2(i)=(extremite2(i)-origine(i))/(nbre_points2-1);
            for (i=0; i<dimension; i++)
              dx3(i)=(extremite3(i)-origine(i))/(nbre_points3-1);
            for (i=0; i<nbre_points1; i++)
              for (j=0; j<nbre_points2; j++)
                for (int m=0; m<nbre_points3; m++)
                  for (k=0; k<dimension; k++)
                    les_positions_(i*nbre_points2*nbre_points1+j*nbre_points1+m,k)=origine(k)+i*dx1(k)+j*dx2(k)+m*dx3(k);
            break;
          }
        default:
          {
            Cerr << motlu <<"is not yet understood!" << finl;
            exit();
          }
        }
      fait(rang) = 1;
    }
  if ( (fait[0] == 0) || (fait[1] == 0) )
    {
      Cerr << "Error while reading the probe " << nom_ << finl;
      Cerr << "The data of the probe have not been properly defined" << finl;
      exit();
    }
  const Zone& la_zone =pb.domaine().zone(0);
  initialiser(la_zone);
  return is;
}
References Probleme_base::a_pour_IntVect(), Cerr, dim, Objet_U::dimension, Probleme_base::domaine(), Process::exit(), finl, Probleme_base::get_noms_champs_postraitables(), initialiser(), les_positions_, mon_post, mon_tableau, nbre_points1, nbre_points2, nbre_points3, nom_, O_U_Ptr::non_nul(), periode, Postraitement::probleme(), REF, TRUSTTab< _TYPE_ >::resize(), Motcles::search(), vect_impl::size(), and Domaine::zone().
self_cast() [1/2]
const Sonde_Int & Sonde_Int::self_cast (const Objet_U & r) static
Definition at line 21 of file Sonde_Int.cpp.
self_cast() [2/2]
Sonde_Int & Sonde_Int::self_cast (Objet_U & r) static
Definition at line 21 of file Sonde_Int.cpp.
taille_memoire()
unsigned Sonde_Int::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Sonde_Int.cpp.
temps()
double Sonde_Int::temps () const inline
Le temps ecoule.
Returns
double
Signification: le temps ecoule
Contraintes:
Definition at line 112 of file Sonde_Int.h.
{
  return nb_bip*periode;
}
References nb_bip, and periode.
Member Data Documentation
dim
int Sonde_Int::dim private
la dimension de la sone (point:0,segment:1,plan:2,volume:3)
Definition at line 66 of file Sonde_Int.h.
Referenced by ouvrir_fichier(), postraiter(), and readOn().
elem_
IntVect Sonde_Int::elem_ private
les elements contenant les sondes ponctuelles
Definition at line 70 of file Sonde_Int.h.
Referenced by initialiser(), les_poly(), and postraiter().
info_obj
const Type_info Sonde_Int::info_obj static
Definition at line 40 of file Sonde_Int.h.
le_fichier
SFichier* Sonde_Int::le_fichier private
Definition at line 74 of file Sonde_Int.h.
Referenced by fermer_fichier(), fichier(), and ouvrir_fichier().
les_positions_
DoubleTab Sonde_Int::les_positions_ private
les coordonnees des sondes ponctuelles
Definition at line 69 of file Sonde_Int.h.
Referenced by initialiser(), les_positions(), ouvrir_fichier(), postraiter(), and readOn().
mon_post
Ref_Postraitement Sonde_Int::mon_post private
Definition at line 64 of file Sonde_Int.h.
Referenced by associer_post(), and readOn().
mon_tableau
Ref_IntVect Sonde_Int::mon_tableau private
Le tableau sonde.
Definition at line 68 of file Sonde_Int.h.
Referenced by initialiser(), le_tableau(), postraiter(), and readOn().
nb_bip
double Sonde_Int::nb_bip private
Definition at line 73 of file Sonde_Int.h.
Referenced by initialiser(), mettre_a_jour(), and temps().
nbre_points1
int Sonde_Int::nbre_points1 private
Definition at line 67 of file Sonde_Int.h.
Referenced by ouvrir_fichier(), and readOn().
nbre_points2
int Sonde_Int::nbre_points2 private
Definition at line 67 of file Sonde_Int.h.
Referenced by ouvrir_fichier(), and readOn().
nbre_points3
int Sonde_Int::nbre_points3 private
faire des sonde_segment,sonde_plan,etc...
Definition at line 67 of file Sonde_Int.h.
Referenced by ouvrir_fichier(), and readOn().
nom_
Nom Sonde_Int::nom_ private
le nom de la sonde
Definition at line 65 of file Sonde_Int.h.
Referenced by associer_post(), initialiser(), ouvrir_fichier(), postraiter(), and readOn().
periode
double Sonde_Int::periode private
periode d'echantillonnage
Definition at line 72 of file Sonde_Int.h.
Referenced by fixer_periode(), mettre_a_jour(), readOn(), and temps().
valeurs
IntTab Sonde_Int::valeurs private
les valeurs de mon_tableau pour les indices donnes par elem_
Definition at line 71 of file Sonde_Int.h.
Referenced by initialiser(), and postraiter().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Sonde_Int.h
src/Kernel/Framework/Sonde_Int.cpp