TRUST: Matrice_Dense Class Reference
Matrice_Dense Class Reference
#include <Matrice_Dense.h>
Public Member Functions
~Matrice_Dense ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Matrice_Dense (void)
Matrice_Dense (const int nb_lines, const int nb_cols)
void dimensionner (const int nb_lines, const int nb_cols)
void read_from_file (const Nom &filename)
void convert_to_morse_matrix (Matrice_Morse &morse_matrix) const
const double & operator() (const int line, const int col) const
double & operator() (const int line, const int col)
void build_matrix_from_coefficients_line_by_line (const DoubleVect &coefficients)
void build_matrix_from_coefficients_column_by_column (const DoubleVect &coefficients)
bool is_the_same (const Matrice_Dense &other_matrix, const double tol=1e-14) const
void build_the_transposed (Matrice_Dense &transposed) const
void set_coefficient (const int i, const int j, const double value)
Sortie & imprimer_formatte (Sortie &s) const override
int ordre () const override
int nb_lignes () const override
int nb_colonnes () const override
DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + Matrix_ * x.
DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const override
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const override
void scale (const double x) override
void get_stencil (IntTab &stencil) const override
void inverse ()
void multiplyToRight (const Matrice_Dense &B, Matrice_Dense &RES) const
DoubleTab & coeffs ()
Public Member Functions inherited from Matrice_Base
Matrice_Base ()
~Matrice_Base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int ordre () const =0
virtual int nb_lignes () const =0
virtual int nb_colonnes () const =0
virtual DoubleVect & ajouter_multvect_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleVect & ajouter_multvectT_ (const DoubleVect &x, DoubleVect &r) const =0
virtual DoubleTab & ajouter_multTab_ (const DoubleTab &x, DoubleTab &r) const =0
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: r = r + A*x.
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Operation de multiplication-accumulation (saxpy) matrice matrice<br>(matrice represente par un tableau)
Operation: R = R + A*X.
virtual DoubleVect & multvect_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice.
Operation: r = A*x.
virtual DoubleVect & multvectT_ (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Multiplication d'un vecteur par la matrice transposee.
Operation: r = AT*x.
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
NON CODE
Multiplication d'une matrice representee par un tableau par la matrice.
Operation: R = A*X.
virtual Sortie & imprimer (Sortie &) const
virtual Sortie & imprimer_formatte (Sortie &s) const
virtual void scale (const double x)=0
virtual void get_stencil (IntTab &stencil) const
virtual void get_symmetric_stencil (IntTab &stencil) const
virtual void get_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
virtual void get_symmetric_stencil_and_coefficients (IntTab &stencil, ArrOfDouble &coefficients) const
int get_stencil_size (void) const
virtual void build_stencil (void)
void set_stencil (const IntTab &stencil)
bool is_stencil_up_to_date (void) const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Matrice_Dense & self_cast (Objet_U &)
static const Matrice_Dense & self_cast (const Objet_U &)
Static Public Member Functions inherited from Matrice_Base
static const Type_info * info ()
static Matrice_Base & self_cast (Objet_U &)
static const Matrice_Base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Matrice_Base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
DoubleTab Matrix_
Additional Inherited Members
Protected Attributes inherited from Matrice_Base
bool is_stencil_up_to_date_
IntTab stencil_
Detailed Description
Definition at line 24 of file Matrice_Dense.h.
Constructor & Destructor Documentation
~Matrice_Dense()
Matrice_Dense::~Matrice_Dense ()
Definition at line 21 of file Matrice_Dense.cpp.
Matrice_Dense() [1/2]
Matrice_Dense::Matrice_Dense (void)
Definition at line 63 of file Matrice_Dense.cpp.
{
  dimensionner( 0 , 0 );
}
References dimensionner().
Matrice_Dense() [2/2]
Matrice_Dense::Matrice_Dense (const int nb_lines, const int nb_cols)
Definition at line 68 of file Matrice_Dense.cpp.
{
  dimensionner( nb_lines , nb_cols );
}
References dimensionner().
Member Function Documentation
ajouter_multTab_()
DoubleTab & Matrice_Dense::ajouter_multTab_ (const DoubleTab & x, DoubleTab & r) const override virtual
Implements Matrice_Base.
Definition at line 360 of file Matrice_Dense.cpp.
{
  Cerr<<"Error in Matrice_Dense::ajouter_multTab_ ."<<finl;
  Cerr<<"This function is virtual pure in Matrice_Base but seems never used."<<finl;
  Cerr<<"One should get rid off it."<<finl;
  Cerr<<"Aborting..."<<finl;
  Process::abort( );
  return resu;
}
References Process::abort(), Cerr, and finl.
ajouter_multvect_()
DoubleVect & Matrice_Dense::ajouter_multvect_ (const DoubleVect & x, DoubleVect & r) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur.
Operation: resu = resu + Matrix_ * x.
< store the result of Matrix_(i , j) * x(j) with 0<= j <=nb_cols
Implements Matrice_Base.
Definition at line 212 of file Matrice_Dense.cpp.
{
  const int nb_lines = nb_lignes( ) ;
  const int nb_cols  = nb_colonnes( );
  assert( x.size_array( ) == nb_cols );
// the test is in this order because size() maybe invalid
  assert( resu.size_array( ) == nb_lines || resu.size( ) == nb_lines );
// for a given i such that 0 <= i <= nb_lines we have
// resu(i) = resu(i) + Matrix_(i , j) * x(j)
// with 0 <= j <= nb_cols
  for(int i=0; i<nb_lines; i++)
    {
      double old_resu = resu( i );
      double prod_mat_vect = 0; //!< store the result of Matrix_( i , j ) * x( j ) with 0<= j <=nb_cols
      for(int j=0; j<nb_cols; j++)
        {
          prod_mat_vect += Matrix_( i , j ) * x( j );
        }
      resu( i ) = old_resu + prod_mat_vect ;
    }
  return resu;
}
References Matrix_, nb_colonnes(), nb_lignes(), TRUSTVect< _TYPE_ >::size(), and TRUSTArray< _TYPE_ >::size_array().
ajouter_multvectT_()
DoubleVect & Matrice_Dense::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & r) const override virtual
Operation de multiplication-accumulation (saxpy) matrice vecteur,
par la matrice transposee.
Operation: resu = resu + A^{T}*x.
Implements Matrice_Base.
Definition at line 295 of file Matrice_Dense.cpp.
{
  const int nb_lines = nb_lignes( ) ;
  const int nb_cols  = nb_colonnes( );
  assert( x.size_array( ) == nb_lines );
// the test is in this order because size() maybe invalid
  assert( resu.size_array( ) == nb_cols || resu.size( ) == nb_cols );
// for a given i such that 0 <= i <= nb_cols we have
// resu(i) = resu(i) + Matrix_(j , i) * x(j)
// with 0 <= j <= nb_lines
  for(int i=0; i<nb_cols; i++)
    {
      double old_resu = resu( i );
      double prod_mat_vect = 0;
      for(int j=0; j<nb_lines; j++)
        {
          prod_mat_vect += Matrix_( j , i ) * x( j );
        }
      resu( i ) = old_resu + prod_mat_vect ;
    }
  return resu;
}
References Matrix_, nb_colonnes(), nb_lignes(), TRUSTVect< _TYPE_ >::size(), and TRUSTArray< _TYPE_ >::size_array().
build_matrix_from_coefficients_column_by_column()
void Matrice_Dense::build_matrix_from_coefficients_column_by_column (const DoubleVect & coefficients)
Definition at line 131 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
  assert( coefficients.size( ) == nb_lines * nb_cols );
  dimensionner( nb_lines , nb_cols );
  int counter=0;
  for(int j=0; j<nb_cols; j++)
    {
      for( int i=0; i<nb_lines; i++)
        {
          Matrix_( i , j ) = coefficients( counter );
          counter++;
        }
    }
}
References dimensionner(), Matrix_, nb_colonnes(), nb_lignes(), and TRUSTVect< _TYPE_ >::size().
build_matrix_from_coefficients_line_by_line()
void Matrice_Dense::build_matrix_from_coefficients_line_by_line (const DoubleVect & coefficients)
Definition at line 114 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
  assert( coefficients.size( ) == nb_lines * nb_cols );
  dimensionner( nb_lines , nb_cols );
  int counter=0;
  for( int i=0; i<nb_lines; i++)
    {
      for(int j=0; j<nb_cols; j++)
        {
          Matrix_( i , j ) = coefficients( counter );
          counter++;
        }
    }
}
References dimensionner(), Matrix_, nb_colonnes(), nb_lignes(), and TRUSTVect< _TYPE_ >::size().
build_the_transposed()
void Matrice_Dense::build_the_transposed (Matrice_Dense & transposed) const
Definition at line 245 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
  transposed.dimensionner( nb_lines , nb_cols );
  for(int j=0; j<nb_cols; j++)
    {
      for(int i=0; i<nb_lines; i++)
        {
          double value = Matrix_( i , j );
          transposed.set_coefficient( j , i , value ) ;
        }
    }
}
References dimensionner(), Matrix_, nb_colonnes(), nb_lignes(), and set_coefficient().
coeffs()
DoubleTab & Matrice_Dense::coeffs () inline
Definition at line 60 of file Matrice_Dense.h.
  {
    return Matrix_;
  }
References Matrix_.
convert_to_morse_matrix()
void Matrice_Dense::convert_to_morse_matrix (Matrice_Morse & morse_matrix) const
Definition at line 149 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( ) ;
  int nnz = nb_lines * nb_cols ;
  morse_matrix.dimensionner( nb_lines , nb_cols , nnz );
  int size_tab1 = nb_lines + 1 ;
  int size_tab2 = nnz ;
  morse_matrix.get_set_tab1().resize( size_tab1 );
  morse_matrix.get_set_tab2().resize( size_tab2 );
  morse_matrix.get_set_coeff().resize( nnz );
  for(int i=0; i<size_tab1; i++)
    {
      morse_matrix.get_set_tab1()( i ) =  /*already registred*/i*nb_cols + /*fortran index*/ 1 ;
    }
  int count = 0;
  for(int i=0 ; i<nb_lines ; i++)
    {
      for(int j=0; j<nb_cols; j++)
        {
          morse_matrix.get_set_tab2()( count ) = j+1 ;
          morse_matrix.get_set_coeff()( count ) = Matrix_( i , j );
          count++;
        }
    }
}
References Matrice_Morse::dimensionner(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrix_, nb_colonnes(), nb_lignes(), and TRUSTVect< _TYPE_ >::resize().
cree_instance()
Objet_U * Matrice_Dense::cree_instance () static
Definition at line 21 of file Matrice_Dense.cpp.
dimensionner()
void Matrice_Dense::dimensionner (const int nb_lines, const int nb_cols)
Definition at line 180 of file Matrice_Dense.cpp.
{
  Matrix_.resize( nb_lines , nb_cols );
}
References Matrix_, and TRUSTTab< _TYPE_ >::resize().
Referenced by build_matrix_from_coefficients_column_by_column(), build_matrix_from_coefficients_line_by_line(), build_the_transposed(), Matrice_Dense(), and read_from_file().
duplique()
int Matrice_Dense::duplique () const override virtual
Implements Objet_U.
Definition at line 21 of file Matrice_Dense.cpp.
get_info()
const Type_info * Matrice_Dense::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Matrice_Base.
Definition at line 21 of file Matrice_Dense.cpp.
get_stencil()
void Matrice_Dense::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Definition at line 336 of file Matrice_Dense.cpp.
{
  const int nb_lines = nb_lignes( );
  const int nb_cols  = nb_colonnes( );
  stencil.resize( 0, 2 );
  stencil.set_smart_resize( 1 );
  for(int i=0; i<nb_lines; i++)
    {
      for(int j=0; j<nb_cols; j++)
        {
          stencil.append_line( i , j );
        }
    }
  const int new_size = stencil.dimension( 0 );
  stencil.set_smart_resize( 0 );
  stencil.resize( new_size, 2 );
}
References TRUSTTab< _TYPE_ >::append_line(), TRUSTTab< _TYPE_ >::dimension(), nb_colonnes(), nb_lignes(), TRUSTTab< _TYPE_ >::resize(), and TRUSTArray< _TYPE_ >::set_smart_resize().
imprimer_formatte()
Sortie & Matrice_Dense::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Definition at line 45 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
  s << nb_lines << " ";
  s << nb_cols << "\n\n";
  for(int i=0; i<nb_lines; i++)
    {
      for(int j=0; j<nb_cols; j++)
        {
          s << Matrix_( i , j )<<" ";
        }
      s <<"\n";
    }
  return s;
}
References Matrix_, nb_colonnes(), and nb_lignes().
info()
const Type_info * Matrice_Dense::info () static
Definition at line 21 of file Matrice_Dense.cpp.
inverse()
void Matrice_Dense::inverse ()
Definition at line 370 of file Matrice_Dense.cpp.
{
// This method compute the inverse of the matrix.
// It uses the LAPACK library.
  const int nbLines = nb_lignes();
  const int nbCols = nb_colonnes();
  int infoerr = 0;
  ArrOfInt ipiv(nbLines);
  ArrOfDouble work(nbLines);
  if (nbLines != nbCols)
    {
      Cerr << "Error in Matrice_Dense::inverse" << finl;
      Cerr << "The matrix is not a square matrix !" << finl;
      Process::abort( );
    }
  F77NAME(DGETRF)(&nbLines, &nbLines, Matrix_.addr(), &nbLines, ipiv.addr(), &infoerr);
  assert(infoerr == 0);
  F77NAME(DGETRI)(&nbLines, Matrix_.addr(), &nbLines, ipiv.addr(), work.addr(), &nbLines, &infoerr);
  assert(infoerr == 0);
  return;
}
References Process::abort(), TRUSTArray< _TYPE_ >::addr(), Cerr, F77NAME, finl, Matrix_, nb_colonnes(), and nb_lignes().
is_the_same()
bool Matrice_Dense::is_the_same (const Matrice_Dense & other_matrix, const double tol = 1e-14) const
Definition at line 263 of file Matrice_Dense.cpp.
{
  bool same = true;
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
// check if the other has same number of lines/columns
  if( other_matrix.nb_lignes( ) != nb_lines )
    {
      same = false;
    }
  if( other_matrix.nb_colonnes( ) != nb_cols )
    {
      same = false;
    }
// check each coefficient
  for(int i=0; i<nb_lines; i++)
    {
      for(int j=0; j<nb_cols; j++)
        {
          if( std::fabs( other_matrix( i , j ) - Matrix_( i , j )) >= tol  )
            {
              same = false;
            }
        }
    }
  return same;
}
References Matrix_, nb_colonnes(), nb_lignes(), and same().
multiplyToRight()
void Matrice_Dense::multiplyToRight (const Matrice_Dense & B, Matrice_Dense & RES) const
Definition at line 395 of file Matrice_Dense.cpp.
{
// This method allows to perform the multiplication of two matrix.
// It is the "right" multiplication : (*this) * B = RES
  assert(nb_colonnes() == B.nb_lignes());
  assert(nb_lignes() == RES.nb_lignes());
  assert(B.nb_colonnes() == RES.nb_colonnes());
  for (int i = 0; i < nb_lignes(); ++i)
    {
      for (int j = 0; j < B.nb_colonnes(); ++j)
        {
          RES.set_coefficient(i, j, 0.0);
          for (int k = 0; k < nb_colonnes(); ++k)
            {
              RES.set_coefficient(i, j, RES(i, j) + Matrix_(i, k) * B(k, j));
            }
        }
    }
  return;
}
References Matrix_, nb_colonnes(), nb_lignes(), and set_coefficient().
nb_colonnes()
int Matrice_Dense::nb_colonnes (void) const override virtual
Implements Matrice_Base.
Definition at line 190 of file Matrice_Dense.cpp.
{
  return Matrix_.dimension( 1 );
}
References TRUSTTab< _TYPE_ >::dimension(), and Matrix_.
Referenced by ajouter_multvect_(), ajouter_multvectT_(), build_matrix_from_coefficients_column_by_column(), build_matrix_from_coefficients_line_by_line(), build_the_transposed(), convert_to_morse_matrix(), get_stencil(), imprimer_formatte(), inverse(), is_the_same(), multiplyToRight(), ordre(), printOn(), scale(), and set_coefficient().
nb_lignes()
int Matrice_Dense::nb_lignes (void) const override virtual
Implements Matrice_Base.
Definition at line 185 of file Matrice_Dense.cpp.
{
  return Matrix_.dimension( 0 );
}
References TRUSTTab< _TYPE_ >::dimension(), and Matrix_.
Referenced by ajouter_multvect_(), ajouter_multvectT_(), build_matrix_from_coefficients_column_by_column(), build_matrix_from_coefficients_line_by_line(), build_the_transposed(), convert_to_morse_matrix(), get_stencil(), imprimer_formatte(), inverse(), is_the_same(), multiplyToRight(), ordre(), printOn(), scale(), and set_coefficient().
operator()() [1/2]
double & Matrice_Dense::operator() (const int line, const int col) inline
Definition at line 77 of file Matrice_Dense.h.
{
  assert( line < nb_lignes( ) );
  assert( col < nb_colonnes( ) );
  return Matrix_( line , col );
}
operator()() [2/2]
const double & Matrice_Dense::operator() (const int line, const int col) const inline
Definition at line 70 of file Matrice_Dense.h.
{
  assert( line < nb_lignes( ) );
  assert( col < nb_colonnes( ) );
  return Matrix_( line , col );
}
ordre()
int Matrice_Dense::ordre (void) const override virtual
Implements Matrice_Base.
Definition at line 195 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
  if( nb_lines == nb_cols )
    {
      return nb_lines ;
    }
  else
    {
      return 0 ;
    }
}
References nb_colonnes(), and nb_lignes().
printOn()
Sortie & Matrice_Dense::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Matrice_Base.
Definition at line 23 of file Matrice_Dense.cpp.
{
  int nb_lines = nb_lignes( );
  int nb_cols  = nb_colonnes( );
// s << nb_lines << " "<< nb_cols << "\n";
  for(int i=0; i<nb_lines; i++)
    {
      for( int j=0; j<nb_cols; j++)
        {
          s << Matrix_( i , j )<<" ";
        }
      s << "\n";
    }
  return s;
}
References Matrix_, nb_colonnes(), and nb_lignes().
read_from_file()
void Matrice_Dense::read_from_file (const Nom & filename)
Definition at line 81 of file Matrice_Dense.cpp.
{
  std::ifstream file(filename, ios::in);
  int nb_lines, nb_cols;
  if( file )
    {
      file >> nb_lines ;
      file >> nb_cols  ;
      dimensionner( nb_lines , nb_cols );
      for( int i=0; i<nb_lines; i++)
        {
          for(int j=0; j<nb_cols; j++)
            {
              file >> Matrix_( i , j );
            }
        }
    }
  else
    {
      Cerr<<"Error in Matrice_Dense::read_from_file"<<finl;
      Cerr<<"The file "<<filename<<" was not found or a problem occured while opening the file"<<finl;
      Cerr<<"Aborting..."<<finl;
      Process::abort( );
    }
}
References Process::abort(), Cerr, dimensionner(), finl, and Matrix_.
readOn()
Entree & Matrice_Dense::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Matrice_Base.
Definition at line 39 of file Matrice_Dense.cpp.
{
  return s;
}
scale()
void Matrice_Dense::scale (const double x) override virtual
Implements Matrice_Base.
Definition at line 321 of file Matrice_Dense.cpp.
{
  const int nb_lines = nb_lignes( );
  const int nb_cols  = nb_colonnes( );
  for(int i=0; i<nb_lines; i++)
    {
      for(int j=0; j<nb_cols; j++)
        {
          Matrix_( i , j ) *= x ;
        }
    }
}
References Matrix_, nb_colonnes(), and nb_lignes().
self_cast() [1/2]
const Matrice_Dense & Matrice_Dense::self_cast (const Objet_U & r) static
Definition at line 21 of file Matrice_Dense.cpp.
self_cast() [2/2]
Matrice_Dense & Matrice_Dense::self_cast (Objet_U & r) static
Definition at line 21 of file Matrice_Dense.cpp.
set_coefficient()
void Matrice_Dense::set_coefficient (const int i, const int j, const double value)
Definition at line 238 of file Matrice_Dense.cpp.
{
  assert( i < nb_lignes( ) );
  assert( j < nb_colonnes( ) );
  Matrix_( i , j ) = value;
}
References Matrix_, nb_colonnes(), and nb_lignes().
Referenced by build_the_transposed(), and multiplyToRight().
taille_memoire()
unsigned Matrice_Dense::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 21 of file Matrice_Dense.cpp.
Member Data Documentation
info_obj
const Type_info Matrice_Dense::info_obj static
Definition at line 27 of file Matrice_Dense.h.
Matrix_
DoubleTab Matrice_Dense::Matrix_ private
Definition at line 66 of file Matrice_Dense.h.
Referenced by ajouter_multvect_(), ajouter_multvectT_(), build_matrix_from_coefficients_column_by_column(), build_matrix_from_coefficients_line_by_line(), build_the_transposed(), coeffs(), convert_to_morse_matrix(), dimensionner(), imprimer_formatte(), inverse(), is_the_same(), multiplyToRight(), nb_colonnes(), nb_lignes(), printOn(), read_from_file(), scale(), and set_coefficient().
The documentation for this class was generated from the following files:
src/Kernel/Math/Matrices/Matrice_Dense.h
src/Kernel/Math/Matrices/Matrice_Dense.cpp