TRUST: Op_Diff_Turbulent_base Class Reference
Op_Diff_Turbulent_base Class Reference
classe Op_Diff_Turbulent_base
Classe de base pour les operateurs de diffusion pour un ecoulement
turbulent.
#include <Op_Diff_Turbulent_base.h>
Public Member Functions
virtual ~Op_Diff_Turbulent_base ()
void associer_diffusivite_turbulente (const Champ_Fonc &)
const Champ_Fonc & diffusivite_turbulente () const
bool has_diffusivite_turbulente () const
Private Attributes
Ref_Champ_Fonc la_diffusivite_turbulente
Detailed Description
classe Op_Diff_Turbulent_base
Classe de base pour les operateurs de diffusion pour un ecoulement
turbulent.
Definition at line 43 of file Op_Diff_Turbulent_base.h.
Constructor & Destructor Documentation
virtual Op_Diff_Turbulent_base::~Op_Diff_Turbulent_base () [inline, virtual]
Definition at line 46 of file Op_Diff_Turbulent_base.h.
{};
Member Function Documentation
void Op_Diff_Turbulent_base::associer_diffusivite_turbulente (const Champ_Fonc & diff_turb)
Reimplemented in Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Face, Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Multi_inco_Elem, Op_Dift_VDF_Multi_inco_Elem_Axi, Op_Dift_VDF_Multi_inco_var_Elem, Op_Dift_VDF_Multi_inco_var_Elem_Axi, Op_Dift_VDF_var_Elem, Op_Dift_VDF_var_Elem_Axi, Op_Dift_VDF_var_Face, and Op_Dift_VDF_var_Face_Axi.
Definition at line 25 of file Op_Diff_Turbulent_base.cpp.
References la_diffusivite_turbulente.
Referenced by Op_Dift_VEF_base::completer(), Op_Diff_PolyMAC_Face::completer(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_CoviMAC_Face::completer(), and Op_Diff_CoviMAC_Elem::completer().
{
  la_diffusivite_turbulente = diff_turb;
}
const Champ_Fonc& Op_Diff_Turbulent_base::diffusivite_turbulente () const [inline]
Definition at line 48 of file Op_Diff_Turbulent_base.h.
References la_diffusivite_turbulente, and Ref_Champ_Fonc::valeur().
Referenced by Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VDF_var_Face_Axi::ajouter(), Op_Dift_VDF_Face_Axi::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution(), Op_Dift_Stab_VEF_Face::ajouter_contribution(), Op_Dift_VDF_var_Face_Axi::ajouter_contribution(), Op_Dift_VDF_Face_Axi::ajouter_contribution(), Op_Dift_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_Stab_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Dift_VEF_Face_Q1::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_dt_stab(), Op_Dift_VDF_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_Axi::calculer_dt_stab(), Op_Dift_VDF_Elem::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_dt_stab(), Op_Dift_VEF_Face::calculer_pour_post(), Op_Dift_VEF_Face::contribue_au_second_membre(), Op_Diff_PolyMAC_base::update_nu(), and Op_Diff_CoviMAC_base::update_nu_invh().
  {
    return la_diffusivite_turbulente.valeur();
  }
bool Op_Diff_Turbulent_base::has_diffusivite_turbulente () const [inline]
Definition at line 52 of file Op_Diff_Turbulent_base.h.
References la_diffusivite_turbulente, and O_U_Ptr::non_nul().
Referenced by Op_Diff_CoviMAC_base::completer(), Op_Diff_PolyMAC_base::update_nu(), and Op_Diff_CoviMAC_base::update_nu_invh().
  {
    return la_diffusivite_turbulente.non_nul();
  }
Member Data Documentation
Ref_Champ_Fonc Op_Diff_Turbulent_base::la_diffusivite_turbulente [private]
Definition at line 59 of file Op_Diff_Turbulent_base.h.
Referenced by associer_diffusivite_turbulente(), diffusivite_turbulente(), and has_diffusivite_turbulente().
The documentation for this class was generated from the following files:
src/ThHyd/Turbulence/Op_Diff_Turbulent_base.h
src/ThHyd/Turbulence/Op_Diff_Turbulent_base.cpp