TRUST: paroi_contact Class Reference
paroi_contact Class Reference
#include <Cond_lim_utilisateur_base.h>
Public Member Functions
paroi_contact ()
~paroi_contact ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void complement (Nom &nom)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static paroi_contact & self_cast (Objet_U &)
static const paroi_contact & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecrit le type de l'objet sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Private Attributes
Nom nom_autre_pb
Nom nom_autre_bord
Detailed Description
Definition at line 96 of file Cond_lim_utilisateur_base.h.
Constructor & Destructor Documentation
paroi_contact::paroi_contact ()
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
paroi_contact::~paroi_contact ()
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
Member Function Documentation
void paroi_contact::complement (Nom & nom) [virtual]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 317 of file Cond_lim_utilisateur_base.cpp.
References Cerr, Process::exit(), finl, Cond_lim_utilisateur_base::is_pb_CoviMAC(), Cond_lim_utilisateur_base::is_pb_PolyMAC(), Cond_lim_utilisateur_base::is_pb_rayo(), Cond_lim_utilisateur_base::is_pb_VDF(), O_U_Ptr::le_nom(), Cond_lim_utilisateur_base::mon_equation, nom_autre_bord, nom_autre_pb, Cond_lim_utilisateur_base::nom_bord_, Interprete::objet(), Objet_U::que_suis_je(), and ref_cast.
{
  int rayo =        is_pb_rayo();
  if (!rayo)
    {
      if (ref_cast(Probleme_base,Interprete::objet(nom_autre_pb)).milieu().is_rayo_transp())
        rayo = 2;
      else if (ref_cast(Probleme_base,Interprete::objet(nom_autre_pb)).milieu().is_rayo_semi_transp())
        rayo = 1;
    }
  const Nom& nom_mon_pb=mon_equation->probleme().le_nom();
  if (nom_mon_pb==nom_autre_pb)
    {
      Cerr<<"Error in "<<que_suis_je()<<" the name of the other problem is the same as my problem :"<<nom_mon_pb<<" on the boundary :"<< nom_bord_<<finl;
      exit();
    }
  if (is_pb_VDF())
    {
// paroi_echange_contact_VDF pb2 Droit1 temperature 1.e10
      ajout= "paroi_echange_contact_VDF ";
      if (rayo==2)
        ajout= "Echange_contact_Rayo_transp_VDF ";
      if (rayo==1)
        ajout="Paroi_Echange_contact_rayo_semi_transp_VDF ";
      ajout+=nom_autre_pb;
      ajout+=" ";
      ajout+=nom_autre_bord;
      ajout+=" temperature 1.e10";
    }
  else if (is_pb_PolyMAC())
    {
// paroi_echange_contact_PolyMAC pb2 Droit1 temperature 1.e10
      ajout= "paroi_echange_contact_PolyMAC ";
      ajout+=nom_autre_pb;
      ajout+=" ";
      ajout+=nom_autre_bord;
      ajout+=" temperature 1.e10";
    }
  else if (is_pb_CoviMAC())
    {
// paroi_echange_contact_CoviMAC pb2 Droit1 temperature 1.e10
      ajout= "paroi_echange_contact_CoviMAC ";
      ajout+=nom_autre_pb;
      ajout+=" ";
      ajout+=nom_autre_bord + " ";
      ajout+=mon_equation->inconnue().le_nom() + " 1.e10";
    }
  else
    {
      if (rayo==1)
        {
          ajout="paroi_temperature_imposee_rayo_semi_transp ";
          ajout+="Champ_Front_contact_rayo_semi_transp_VEF ";
        }
      else if (rayo==2)
        {
          ajout="paroi_temperature_imposee_rayo_transp ";
          ajout+="Champ_Front_contact_rayo_transp_VEF ";
        }
      else
        {
          ajout="scalaire_impose_paroi ";
          ajout+="Champ_Front_contact_VEF ";
        }
      ajout+=nom_mon_pb;
      ajout+=" ";
      ajout+=nom_bord_;
      ajout+=" ";
      ajout+=nom_autre_pb;
      ajout+=" ";
      ajout+=nom_autre_bord;
    }
}
Objet_U * paroi_contact::cree_instance () [static]
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
int paroi_contact::duplique () const [virtual]
Implements Cond_lim_utilisateur_base.
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
const Type_info * paroi_contact::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
const Type_info * paroi_contact::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
Sortie & paroi_contact::printOn (Sortie & s) const [protected, virtual]
Ecrit le type de l'objet sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 67 of file Cond_lim_utilisateur_base.cpp.
References nom_autre_bord, nom_autre_pb, and Objet_U::que_suis_je().
{
  return s << que_suis_je()  << " "<<nom_autre_pb<<" "<<nom_autre_bord ;
}
Entree & paroi_contact::readOn (Entree & s) [protected, virtual]
Lecture d'une condition aux limite de type Cond_lim_utilisateur_base
a partir d'un flot d'entree.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 105 of file Cond_lim_utilisateur_base.cpp.
References nom_autre_bord, and nom_autre_pb.
{
  s >> nom_autre_pb;
  s >> nom_autre_bord;
  return s ;
}
const paroi_contact & paroi_contact::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
paroi_contact & paroi_contact::self_cast (Objet_U & r) [static]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
unsigned paroi_contact::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 37 of file Cond_lim_utilisateur_base.cpp.
Member Data Documentation
const Type_info paroi_contact::info_obj [static]
Reimplemented from Cond_lim_utilisateur_base.
Definition at line 98 of file Cond_lim_utilisateur_base.h.
Nom paroi_contact::nom_autre_bord [private]
Definition at line 102 of file Cond_lim_utilisateur_base.h.
Referenced by complement(), printOn(), and readOn().
Nom paroi_contact::nom_autre_pb [private]
Definition at line 102 of file Cond_lim_utilisateur_base.h.
Referenced by complement(), printOn(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Cond_lim_utilisateur_base.h
src/Kernel/Framework/Cond_lim_utilisateur_base.cpp