TRUST: Eval_Dift_VDF_var_Elem Class Reference
Eval_Dift_VDF_var_Elem Class Reference
class Eval_Dift_VDF_var_Elem
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est scalaire (Champ_P0_VDF)
Le champ de diffusivite n'est pas constant.
#include <Eval_Dift_VDF_leaves.h>
Public Member Functions
Eval_Dift_VDF_var_Elem ()
int get_ind_Fluctu_Term () const
void associer_modele_turbulence (const Modele_turbulence_scal_base &mod)
virtual void associer_loipar (const Turbulence_paroi_scal &loi_paroi)
Static Public Attributes
static constexpr bool IS_MODIF_DEQ = true
Private Attributes
Ref_Modele_turbulence_scal_base le_modele_turbulence
int ind_Fluctu_Term
TODO: WTF ?
Detailed Description
class Eval_Dift_VDF_var_Elem
Evaluateur VDF pour la diffusion totale (laminaire et turbulente)
Le champ diffuse est scalaire (Champ_P0_VDF)
Le champ de diffusivite n'est pas constant.
Definition at line 144 of file Eval_Dift_VDF_leaves.h.
Constructor & Destructor Documentation
Eval_Dift_VDF_var_Elem::Eval_Dift_VDF_var_Elem () [inline]
Definition at line 149 of file Eval_Dift_VDF_leaves.h.
: ind_Fluctu_Term(1) {}
Member Function Documentation
virtual void Eval_Dift_VDF_var_Elem::associer_loipar (const Turbulence_paroi_scal & loi_paroi) [inline, virtual]
Reimplemented from Eval_Turbulence.
Definition at line 166 of file Eval_Dift_VDF_leaves.h.
References Eval_Dift_VDF_const_Elem::associer_loipar(), and Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >::ind_Fluctu_Term().
Referenced by Op_Dift_VDF_var_Elem::associer_loipar().
  {
    Eval_Dift_VDF_var::associer_loipar(loi_paroi);
    ind_Fluctu_Term = 0;
  }
void Eval_Dift_VDF_var_Elem::associer_modele_turbulence (const Modele_turbulence_scal_base & mod) [inline]
Definition at line 157 of file Eval_Dift_VDF_leaves.h.
References Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >::ind_Fluctu_Term(), Eval_Dift_VDF_const_Elem::le_modele_turbulence, Eval_Turbulence::loipar, and O_U_Ptr::non_nul().
Referenced by Op_Dift_VDF_var_Elem::completer().
  {
// On remplit la reference au modele de turbulence et le tableau k:
    le_modele_turbulence = mod;
    ind_Fluctu_Term = 0;
    if (!loipar.non_nul())
      ind_Fluctu_Term = 1;
  }
int Eval_Dift_VDF_var_Elem::get_ind_Fluctu_Term () const [inline]
Reimplemented from Eval_Diff_VDF.
Definition at line 152 of file Eval_Dift_VDF_leaves.h.
References Eval_Diff_VDF_Elem< Eval_Dift_VDF_const_Elem >::ind_Fluctu_Term().
  {
    return ind_Fluctu_Term;
  }
Member Data Documentation
int Eval_Dift_VDF_var_Elem::ind_Fluctu_Term [private]
TODO: WTF ?
Definition at line 174 of file Eval_Dift_VDF_leaves.h.
constexpr bool Eval_Dift_VDF_var_Elem::IS_MODIF_DEQ = true [static]
Reimplemented from Eval_Diff_VDF_Elem< Eval_Dift_VDF_var_Elem >.
Definition at line 150 of file Eval_Dift_VDF_leaves.h.
Ref_Modele_turbulence_scal_base Eval_Dift_VDF_var_Elem::le_modele_turbulence [private]
Definition at line 173 of file Eval_Dift_VDF_leaves.h.
The documentation for this class was generated from the following file:
src/VDF/Operateurs/Evaluateurs_Diff/Eval_Dift_VDF_leaves.h