TRUST: MD_Vector_composite Class Reference
MD_Vector_composite Class Reference
Metadata for a distributed composite vector.
This class describes a vector that contains one or more sub-vectors (see P1bubble arrays),
each sub-vector has the same shape as the base vector, plus one dimension if shapes_[i] > 0
See also class DoubleTab_Parts and class ConstDoubleTab_Parts.
#include <MD_Vector_composite.h>
Public Member Functions
MD_Vector_composite ()
~MD_Vector_composite ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void add_part (const MD_Vector &part, int shape=0, Nom name="")
Append the "part" descriptor to the composite vector.
By default, shape=0 says that for each item in "part", one item will
be appended to the composite descriptor.
If shape=n, each items in "part" will be duplicated n times in the
composite descriptor.
The difference between 0 and 1 is when we create parts with DoubleTab_parts<br>(see class DoubleTab_parts)
Exemples:
1) P1Bubble pressure fields have one, two or three parts with shape=1.
(see Zone_VEF_PreP1b::discretiser_suite())
2) One can create a composite field containing
- velocity degrees of freedom at the faces
- pressure d.o.f. at the elements
- one multiscalar d.o.f at nodes
MD_Vector_composite mdc;
mdc.add_part(zonevf.md_vector_faces(), dimension);
mdc.add_part(zone.md_vector_elements(), 0 /* scalar ‍/);
mdc.add_part(domaine.md_vector_sommets(), 1 / multiscalar with 1 component ‍/);
MD_Vector md;
md.copy(mdc);
I will create a DoubleVect of this form by attaching this descriptor:
DoubleVect v;
MD_Vector_tools::creer_tableau_distribue(md, v);
DoubleTab_Parts parts(v);
// parts[0] has nb_dim()==2, dimensions are [ zonevf.nb_faces_tot, 3 ]
// parts[1] has nb_dim()==1, dimension [ zone.nb_elem_tot ] / speciel case shape==0 ‍/
// parts[2] has nb_dim()==2, dimension [ domaine.nb_som_tot, 1 ]
I can duplicate items in the descriptor by creating DoubleTab objects:
The following code will create an array containing 12 d.o.f for each face
followed by 4 d.o.f for each element and 4 d.o.f for each node:
DoubleTab tab(0, 4);
MD_Vector_tools::creer_tableau_distribue(md, tab);
DoubleTab_Parts parts(tab);
// parts[0] has nb_dim()==3, dimensions are [ zonevf.nb_faces_tot, 3, 4 ]
// parts[1] has nb_dim()==2, dimension [ zone.nb_elem_tot, 4 ] / speciel case shape==0 *‍/
// parts[2] has nb_dim()==3, dimension [ domaine.nb_som_tot, 1, 4 ].
void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const override
void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const override
void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const override
void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const override
void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const override
void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const override
int nb_parts () const
int get_shape (int i) const
const MD_Vector & get_desc_part (int i) const
Nom get_name (int i) const
Public Member Functions inherited from MD_Vector_base2
~MD_Vector_base2 () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
MD_Vector_base2 ()
int get_nb_items_reels () const override
int get_nb_items_tot () const override
const ArrOfInt & get_items_to_compute () const override
const ArrOfInt & get_items_to_sum () const override
int nb_items_seq_tot () const override
int nb_items_seq_local () const override
Public Member Functions inherited from MD_Vector_base
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
MD_Vector_base ()
MD_Vector_base (const MD_Vector_base &)
~MD_Vector_base () override
virtual int get_nb_items_reels () const =0
virtual int get_nb_items_tot () const =0
virtual void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, DoubleVect &) const =0
virtual void initialize_comm (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual void prepare_send_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual void process_recv_data (const Echange_EV_Options &opt, Schema_Comm_Vecteurs &, IntVect &) const =0
virtual const ArrOfInt & get_items_to_compute () const =0
virtual const ArrOfInt & get_items_to_sum () const =0
virtual int nb_items_seq_tot () const =0
virtual int nb_items_seq_local () const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static MD_Vector_composite & self_cast (Objet_U &)
static const MD_Vector_composite & self_cast (const Objet_U &)
Static Public Member Functions inherited from MD_Vector_base2
static const Type_info * info ()
static MD_Vector_base2 & self_cast (Objet_U &)
static const MD_Vector_base2 & self_cast (const Objet_U &)
static void append_item_to_blocs (ArrOfInt &blocs, int item)
methode outil pour ajouter un item a un tableau du genre "blocs" contenant
des series de blocs... alonge le bloc precedent ou commence un nouveau bloc si l'item n'est pas contigu avec le bloc precedent.
Static Public Member Functions inherited from MD_Vector_base
static const Type_info * info ()
static MD_Vector_base & self_cast (Objet_U &)
static const MD_Vector_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Public Attributes
Vect_MD_Vector data_
MD_Vector_std global_md_
ArrOfInt parts_offsets_
ArrOfInt shapes_
Noms names_
Public Attributes inherited from MD_Vector_base2
int nb_items_tot_
int nb_items_reels_
int nb_items_seq_tot_
int nb_items_seq_local_
ArrOfInt blocs_items_to_sum_
ArrOfInt blocs_items_to_compute_
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from MD_Vector_base2
static const Type_info info_obj
Static Public Attributes inherited from MD_Vector_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::dump_vector_with_md()
Entree & readOn (Entree &) override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::restore_vector_with_md()
Sortie & printOn (Sortie &x) const override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::dump_vector_with_md()
Entree & readOn (Entree &) override
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::restore_vector_with_md()
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Detailed Description
Metadata for a distributed composite vector.
This class describes a vector that contains one or more sub-vectors (see P1bubble arrays),
each sub-vector has the same shape as the base vector, plus one dimension if shapes_[i] > 0
See also class DoubleTab_Parts and class ConstDoubleTab_Parts.
Definition at line 27 of file MD_Vector_composite.h.
Constructor & Destructor Documentation
MD_Vector_composite()
MD_Vector_composite::MD_Vector_composite ()
Definition at line 22 of file MD_Vector_composite.cpp.
~MD_Vector_composite()
MD_Vector_composite::~MD_Vector_composite ()
Definition at line 22 of file MD_Vector_composite.cpp.
Member Function Documentation
add_part()
void MD_Vector_composite::add_part (const MD_Vector & part, int shape = 0, Nom name = "")
Append the "part" descriptor to the composite vector.
By default, shape=0 says that for each item in "part", one item will
be appended to the composite descriptor.
If shape=n, each items in "part" will be duplicated n times in the
composite descriptor.
The difference between 0 and 1 is when we create parts with DoubleTab_parts<br>(see class DoubleTab_parts)
Exemples:
1) P1Bubble pressure fields have one, two or three parts with shape=1.
(see Zone_VEF_PreP1b::discretiser_suite())
2) One can create a composite field containing
- velocity degrees of freedom at the faces
- pressure d.o.f. at the elements
- one multiscalar d.o.f at nodes
MD_Vector_composite mdc;
mdc.add_part(zonevf.md_vector_faces(), dimension);
mdc.add_part(zone.md_vector_elements(), 0 /* scalar ‍/);
mdc.add_part(domaine.md_vector_sommets(), 1 / multiscalar with 1 component ‍/);
MD_Vector md;
md.copy(mdc);
I will create a DoubleVect of this form by attaching this descriptor:
DoubleVect v;
MD_Vector_tools::creer_tableau_distribue(md, v);
DoubleTab_Parts parts(v);
// parts[0] has nb_dim()==2, dimensions are [ zonevf.nb_faces_tot, 3 ]
// parts[1] has nb_dim()==1, dimension [ zone.nb_elem_tot ] / speciel case shape==0 ‍/
// parts[2] has nb_dim()==2, dimension [ domaine.nb_som_tot, 1 ]
I can duplicate items in the descriptor by creating DoubleTab objects:
The following code will create an array containing 12 d.o.f for each face
followed by 4 d.o.f for each element and 4 d.o.f for each node:
DoubleTab tab(0, 4);
MD_Vector_tools::creer_tableau_distribue(md, tab);
DoubleTab_Parts parts(tab);
// parts[0] has nb_dim()==3, dimensions are [ zonevf.nb_faces_tot, 3, 4 ]
// parts[1] has nb_dim()==2, dimension [ zone.nb_elem_tot, 4 ] / speciel case shape==0 *‍/
// parts[2] has nb_dim()==3, dimension [ domaine.nb_som_tot, 1, 4 ].
< size() will be invalid for arrays with this descriptor
Definition at line 284 of file MD_Vector_composite.cpp.
{
  assert(part.non_nul());
  assert(shape >= 0);
  if (data_.size() == 0)
    {
      nb_items_tot_ = 0;
      nb_items_seq_tot_ = 0;
      nb_items_seq_local_ = 0;
    }
  const int multiplier = (shape == 0) ? 1 : shape;
  data_.add(part);
  const int offset = nb_items_tot_;
  parts_offsets_.set_smart_resize(1);
  parts_offsets_.append_array(offset);
  shapes_.set_smart_resize(1);
  shapes_.append_array(shape);
  names_.add(name);
  nb_items_tot_ += part.valeur().get_nb_items_tot() * multiplier;
  if (data_.size() > 1 || part.valeur().get_nb_items_reels() < 0)
    nb_items_reels_ = -1; //!< size() will be invalid for arrays with this descriptor
  else
    nb_items_reels_ = part.valeur().get_nb_items_reels() * multiplier;
  nb_items_seq_tot_ += part.valeur().nb_items_seq_tot() * multiplier;
  nb_items_seq_local_ += part.valeur().nb_items_seq_local() * multiplier;
  append_blocs(blocs_items_to_sum_, part.valeur().get_items_to_sum(), offset, multiplier);
  append_blocs(blocs_items_to_compute_, part.valeur().get_items_to_compute(), offset, multiplier);
  if (sub_type(MD_Vector_std, part.valeur()))
    append_global_md(global_md_, ref_cast(MD_Vector_std, part.valeur()), offset, multiplier);
  else if (sub_type(MD_Vector_composite, part.valeur()))
    append_global_md(global_md_, ref_cast(MD_Vector_composite, part.valeur()).global_md_, offset, multiplier);
  else
    {
      Cerr << "Internal error in MD_Vector_composite::add_part: unknown part type " << part.valeur().que_suis_je() << finl;
      Process::exit();
    }
}
References Vect_MD_Vector::add(), Vect_Nom::add(), TRUSTArray< _TYPE_ >::append_array(), append_blocs(), append_global_md(), MD_Vector_base2::blocs_items_to_compute_, MD_Vector_base2::blocs_items_to_sum_, Cerr, data_, Process::exit(), finl, MD_Vector_base::get_items_to_compute(), MD_Vector_base::get_items_to_sum(), MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), global_md_, names_, MD_Vector_base2::nb_items_reels_, MD_Vector_base::nb_items_seq_local(), MD_Vector_base2::nb_items_seq_local_, MD_Vector_base::nb_items_seq_tot(), MD_Vector_base2::nb_items_seq_tot_, MD_Vector_base2::nb_items_tot_, MD_Vector::non_nul(), parts_offsets_, Objet_U::que_suis_je(), ref_cast, TRUSTArray< _TYPE_ >::set_smart_resize(), shapes_, Vect_MD_Vector::size(), sub_type, and MD_Vector::valeur().
Referenced by Zone_PolyMAC::discretiser(), Zone_PolyMAC_P0::discretiser(), Zone_VEF_PreP1b::discretiser_suite(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), and Op_Diff_PolyMAC_base::update_aux().
cree_instance()
Objet_U * MD_Vector_composite::cree_instance () static
Definition at line 22 of file MD_Vector_composite.cpp.
duplique()
int MD_Vector_composite::duplique () const override virtual
Implements Objet_U.
Definition at line 22 of file MD_Vector_composite.cpp.
get_desc_part()
const MD_Vector & MD_Vector_composite::get_desc_part (int i) const inline
Definition at line 42 of file MD_Vector_composite.h.
{ return data_[i]; }
References data_.
get_info()
const Type_info * MD_Vector_composite::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from MD_Vector_base2.
Definition at line 22 of file MD_Vector_composite.cpp.
get_name()
Nom MD_Vector_composite::get_name (int i) const inline
Definition at line 43 of file MD_Vector_composite.h.
{ return names_[i]; }
References names_.
get_shape()
int MD_Vector_composite::get_shape (int i) const inline
Definition at line 41 of file MD_Vector_composite.h.
{ return shapes_[i]; }
References shapes_.
info()
const Type_info * MD_Vector_composite::info () static
Definition at line 22 of file MD_Vector_composite.cpp.
initialize_comm() [1/2]
void MD_Vector_composite::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, DoubleVect & v) const override virtual
Implements MD_Vector_base.
Definition at line 325 of file MD_Vector_composite.cpp.
{
  global_md_.initialize_comm(opt, comm, v);
}
References comm, global_md_, and MD_Vector_std::initialize_comm().
initialize_comm() [2/2]
void MD_Vector_composite::initialize_comm (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, IntVect & v) const override virtual
Implements MD_Vector_base.
Definition at line 340 of file MD_Vector_composite.cpp.
{
  global_md_.initialize_comm(opt, comm, v);
}
References comm, global_md_, and MD_Vector_std::initialize_comm().
nb_parts()
int MD_Vector_composite::nb_parts () const inline
Definition at line 40 of file MD_Vector_composite.h.
{ return data_.size(); }
References data_, and Vect_MD_Vector::size().
prepare_send_data() [1/2]
void MD_Vector_composite::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, DoubleVect & v) const override virtual
Implements MD_Vector_base.
Definition at line 330 of file MD_Vector_composite.cpp.
{
  global_md_.prepare_send_data(opt, comm, v);
}
References comm, global_md_, and MD_Vector_std::prepare_send_data().
prepare_send_data() [2/2]
void MD_Vector_composite::prepare_send_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, IntVect & v) const override virtual
Implements MD_Vector_base.
Definition at line 345 of file MD_Vector_composite.cpp.
{
  global_md_.prepare_send_data(opt, comm, v);
}
References comm, global_md_, and MD_Vector_std::prepare_send_data().
printOn()
Sortie & MD_Vector_composite::printOn (Sortie & x) const override protected virtual
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::dump_vector_with_md()
Reimplemented from MD_Vector_base2.
Definition at line 26 of file MD_Vector_composite.cpp.
{
  MD_Vector_base2::printOn(os);
  int np=data_.size();
  os << np<<finl;
  for (int p=0; p<np; p++)
    {
      const MD_Vector_base& md = get_desc_part(p).valeur();
      os << md.que_suis_je() << finl;
      os << md << finl;
    }
  os << "{" << finl;
  os << "global_md" << finl << global_md_ << finl;
  os << "parts_offsets" << space << parts_offsets_ << finl;
  os << "shapes" << space << shapes_ << finl;
  os << "names" << space << names_ << finl;
  os << "}" << finl;
  return os;
}
References finl, MD_Vector_base2::printOn(), Objet_U::que_suis_je(), and space.
process_recv_data() [1/2]
void MD_Vector_composite::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, DoubleVect & v) const override virtual
Implements MD_Vector_base.
Definition at line 335 of file MD_Vector_composite.cpp.
{
  global_md_.process_recv_data(opt, comm, v);
}
References comm, global_md_, and MD_Vector_std::process_recv_data().
process_recv_data() [2/2]
void MD_Vector_composite::process_recv_data (const Echange_EV_Options & opt, Schema_Comm_Vecteurs & comm, IntVect & v) const override virtual
Implements MD_Vector_base.
Definition at line 350 of file MD_Vector_composite.cpp.
{
  global_md_.process_recv_data(opt, comm, v);
}
References comm, global_md_, and MD_Vector_std::process_recv_data().
readOn()
Entree & MD_Vector_composite::readOn (Entree & is) override protected virtual
method used to dump/restore a descriptor in a file
Each process writes a different descriptor. See MD_Vector_tools::restore_vector_with_md()
Reimplemented from MD_Vector_base2.
Definition at line 49 of file MD_Vector_composite.cpp.
{
  MD_Vector_base2::readOn(is);
  int np;
  is >> np ;
  for (int p=0; p<np; p++)
    {
      DERIV(MD_Vector_base) md_ptr;
      Nom md_type;
      is >> md_type;
      md_ptr.typer(md_type);
      is >> md_ptr.valeur();
      if (1)
        {
// Creation du MD_Vector attache au tableau
          data_.add(MD_Vector());
          MD_Vector& mdV =data_[p];
          mdV.copy(md_ptr.valeur());
        }
    }
  Param p(que_suis_je());
  p.ajouter("global_md", &global_md_);
  p.ajouter("parts_offsets", &parts_offsets_);
  p.ajouter("shapes", &shapes_);
  p.ajouter("names", &names_);
  p.lire_avec_accolades(is);
  return is;
}
References Vect_MD_Vector::add(), Param::ajouter(), MD_Vector::copy(), data_, DERIV, global_md_, Param::lire_avec_accolades(), MD_Vector_base::MD_Vector, names_, parts_offsets_, Objet_U::que_suis_je(), MD_Vector_base2::readOn(), and shapes_.
self_cast() [1/2]
const MD_Vector_composite & MD_Vector_composite::self_cast (const Objet_U & r) static
Definition at line 22 of file MD_Vector_composite.cpp.
self_cast() [2/2]
MD_Vector_composite & MD_Vector_composite::self_cast (Objet_U & r) static
Definition at line 22 of file MD_Vector_composite.cpp.
taille_memoire()
unsigned MD_Vector_composite::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 22 of file MD_Vector_composite.cpp.
Member Data Documentation
data_
Vect_MD_Vector MD_Vector_composite::data_
Definition at line 46 of file MD_Vector_composite.h.
Referenced by add_part(), get_desc_part(), init_parts(), nb_parts(), and readOn().
global_md_
MD_Vector_std MD_Vector_composite::global_md_
Definition at line 48 of file MD_Vector_composite.h.
Referenced by add_part(), MD_Vector_tools::creer_md_vect_renum(), initialize_comm(), prepare_send_data(), process_recv_data(), and readOn().
info_obj
const Type_info MD_Vector_composite::info_obj static
Definition at line 29 of file MD_Vector_composite.h.
names_
Noms MD_Vector_composite::names_
Definition at line 55 of file MD_Vector_composite.h.
Referenced by add_part(), get_name(), and readOn().
parts_offsets_
ArrOfInt MD_Vector_composite::parts_offsets_
Definition at line 51 of file MD_Vector_composite.h.
Referenced by add_part(), init_parts(), and readOn().
shapes_
ArrOfInt MD_Vector_composite::shapes_
Definition at line 53 of file MD_Vector_composite.h.
Referenced by add_part(), get_shape(), init_parts(), and readOn().
The documentation for this class was generated from the following files:
src/Kernel/Math/MD_Vector_composite.h
src/Kernel/Math/MD_Vector_composite.cpp