TRUST: Quadri_VEF Class Reference
Quadri_VEF Class Reference
#include <Quadri_VEF.h>
Public Member Functions
~Quadri_VEF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Quadri_VEF ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
int nb_facette () const override
void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const override
calcule les normales des facettes pour des elem standards
void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const override
remplit le tableau normales_facettes_Cl dans la Zone_Cl_VEF
pour la facette fa7 de l'element num_elem
void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const override
modifie les volumes entrelaces pour la face j d'un elem
non standard
void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const override
modifie les volumes entrelaces pour la face joint j d'un elem
non standard
void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const override
modifie normales_facettes_Cl quand idirichlet=3
idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=3, n1 est le numero du sommet confondu avec G
void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const override
void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const override
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const override
remplit le tableau face_normales dans la Zone_VEF
void traiter_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, int, int, int, int, int) const
Public Member Functions inherited from Elem_VEF_base
Elem_VEF_base ()
~Elem_VEF_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual int nb_facette () const =0
const IntTab & KEL () const
virtual void creer_facette_normales (const Zone &, DoubleTab &, const IntVect &) const =0
virtual void creer_normales_facettes_Cl (DoubleTab &, int, int, const DoubleTab &, const DoubleVect &, const Zone &) const =0
virtual void modif_volumes_entrelaces (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_volumes_entrelaces_faces_joints (int, int, const Zone_VEF &, DoubleVect &, int) const =0
virtual void modif_normales_facettes_Cl (DoubleTab &, int, int, int, int, int, int) const =0
virtual void calcul_vc (const ArrOfInt &, ArrOfDouble &, const ArrOfDouble &, const DoubleTab &, const Champ_Inc_base &, int, const DoubleVect &) const =0
virtual void calcul_xg (DoubleVect &, const DoubleTab &, const int, int &, int &, int &, int &) const =0
virtual void normale (int, DoubleTab &, const IntTab &, const IntTab &, const IntTab &, const Zone &) const =0
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Quadri_VEF & self_cast (Objet_U &)
static const Quadri_VEF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Elem_VEF_base
static const Type_info * info ()
static Elem_VEF_base & self_cast (Objet_U &)
static const Elem_VEF_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Elem_VEF_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Elem_VEF_base
IntTab KEL_
Detailed Description
Definition at line 23 of file Quadri_VEF.h.
Constructor & Destructor Documentation
~Quadri_VEF()
Quadri_VEF::~Quadri_VEF ()
Definition at line 19 of file Quadri_VEF.cpp.
Quadri_VEF()
Quadri_VEF::Quadri_VEF ()
KEL_(0,fa7),KEL_(1,fa7) sont les numeros locaux des 2 faces
qui entourent la facette de numero local fa7
le numero local de la fa7 est celui du sommet qui la porte.
Definition at line 37 of file Quadri_VEF.cpp.
{
  int tmp[3][4]=
  {
    {0, 1, 0, 2},
    {1, 2, 3, 3},
    {0, 1, 2, 3}
  };
  KEL_.resize(3,4);
  for (int i=0; i<3; i++)
    for (int j=0; j<4; j++)
      KEL_(i,j)=tmp[i][j];
}
References Elem_VEF_base::KEL_, and TRUSTTab< _TYPE_ >::resize().
Member Function Documentation
calcul_vc()
void Quadri_VEF::calcul_vc (const ArrOfInt & Face, ArrOfDouble & vc, const ArrOfDouble & vs, const DoubleTab & vsom, const Champ_Inc_base & vitesse, int type_cl, const DoubleVect & porosite_face) const override virtual
Implements Elem_VEF_base.
Definition at line 506 of file Quadri_VEF.cpp.
{
// Cerr << " DANS Quadri_VEF::calcul_vc , type_cl = " << type_cl << finl;
// Cerr << "vs " << vs << " et vsom " << vsom << " et vitesse " << vitesse << finl;
// switch(type_cl) {
// case 0: //  pas de Face de Dirichlet
// {
  vc[0] = vs[0]*0.25;
  vc[1] = vs[1]*0.25;
// break;
// }
// case 1: // une Face de Dirichlet : Face 3
// {
// vc[0] = vitesse(Face[3],0);
// vc[1] = vitesse(Face[3],1);
// break;
// }
// case 3: // une Face de Dirichlet : Face 2
// {
// vc[0] = vitesse(Face[2],0);
// vc[1] = vitesse(Face[2],1);
// break;
// }
// case 9: // une Face de Dirichlet : Face 1
// {
// vc[0] = vitesse(Face[1],0);
// vc[1] = vitesse(Face[1],1);
// break;
// }
// case 27: // une Faces de Dirichlet :Face 0
// {
// vc[0] = vitesse(Face[0],0);
// vc[1] = vitesse(Face[0],1);
// break;
// }
// case 4: // deux Faces de Dirichlet : Faces 2,3
// {
// vc[0]= vsom(3,0);
// vc[1]= vsom(3,1);
// break;
// }
// case 28: // deux Faces de Dirichlet : Faces 0,3
// {
// vc[0]= vsom(2,0);
// vc[1]= vsom(2,1);
// break;
// }
// case 12: // deux Faces de Dirichlet : Faces 1,2
// {
// vc[0]= vsom(1,0);
// vc[1]= vsom(1,1);
// break;
// }
// case 36: // deux Faces de Dirichlet : Faces 0,1
// {
// vc[0]= vsom(0,0);
// vc[1]= vsom(0,1);
// break;
// }
// case 10: // deux Faces de Dirichlet : Faces 1,3
// {
// vc[0] = vs[0]*0.25;
// vc[1] = vs[1]*0.25;
// break;
// }
// case 30: // deux Faces de Dirichlet : Faces 0,2
// {
// vc[0] = vs[0]*0.25;
// vc[1] = vs[1]*0.25;
// break;
// }
// case 13: //trois Faces de Dirichlet : Faces 3,2,1
// {
// vc[0]= vitesse(Face[2],0);
// vc[1]= vitesse(Face[2],1);
// break;
// }
// case 31: //trois Faces de Dirichlet : Faces 0,3,2
// {
// vc[0]= vitesse(Face[3],0);
// vc[1]= vitesse(Face[3],1);
// break;
// }
// case 37: //trois Faces de Dirichlet : Faces 1,0,3
// {
// vc[0]= vitesse(Face[0],0);
// vc[1]= vitesse(Face[0],1);
// break;
// }
// case 39: //trois Faces de Dirichlet : Faces 2,1,0
// {
// vc[0]= vitesse(Face[1],0);
// vc[1]= vitesse(Face[1],1);
// break;
// }
// default :
// {
// Cerr << "\n  type inconnu : " << type_cl ;
// exit();
// }
// } // fin du switch
}
calcul_xg()
void Quadri_VEF::calcul_xg (DoubleVect & xg, const DoubleTab & x, const int type_elem_Cl, int & idirichlet, int & n1, int & , int &) const override virtual
calcule les coord xg du centre d'un element non standard
calcule aussi idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=2, n1 est le numero du sommet confondu avec G
Implements Elem_VEF_base.
Definition at line 634 of file Quadri_VEF.cpp.
{
  int dim=xg.size();
// switch(type_elem_Cl) {
// case 0:  //  pas de Face de dirichlet: il a 4 Facettes
// //  le point G est le barycentre des sommets du triangle
// {
  for (int j=0; j<dim; j++)
    xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j))*0.25;
  idirichlet=0;
// break;
// }
// case 1: // une Face de Dirichlet : Face 3
// // le point G est le centre de la face 3
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(2,j)+x(3,j))*0.5;
// idirichlet=1;
// break;
// }
// case 3: // une Face de Dirichlet : Face 2
// // le point G est le centre de la face 2
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(1,j)+x(3,j))*0.5;
// idirichlet=1;
// break;
// }
// case 9: // une Face de Dirichlet : Face 1
// // le point G est le centre de la face 1
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j))*0.5;
// idirichlet=1;
// break;
// }
// case 27: // une Faces de Dirichlet :Face 0
// // le point G est le centre de la face 0
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(2,j))*0.5;
// idirichlet=1;
// break;
// }
// case 4: // deux Faces de Dirichlet : Faces 2,3
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=x(3,j);
// idirichlet=2;
// break;
// }
// case 28: // deux Faces de Dirichlet : Faces 0,3
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=x(2,j);
// idirichlet=2;
// break;
// }
// case 12: // deux Faces de Dirichlet : Faces 1,2
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=x(1,j);
// idirichlet=2;
// break;
// }
// case 36: // deux Faces de Dirichlet : Faces 0,1
// //le point G est le sommet commun au deux faces de dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=x(0,j);
// idirichlet=2;
// break;
// }
// case 10: // deux Faces de Dirichlet : Faces 1,3
// // on garde les memes volumes de controles que pour des faces internes
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j))*0.25;
// idirichlet=0;
// break;
// }
// case 30: // deux Faces de Dirichlet : Faces 0,2
// // on garde les memes volumes de controles que pour des faces internes
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j)+x(2,j)+x(3,j))*0.25;
// idirichlet=0;
// break;
// }
// case 13: //trois Faces de Dirichlet : Faces 3,2,1
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(1,j)+x(3,j))*0.5;
// idirichlet=3;
// break;
// }
// case 31: //trois Faces de Dirichlet : Faces 0,3,2
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(2,j)+x(3,j))*0.5;
// idirichlet=3;
// break;
// }
// case 37: //trois Faces de Dirichlet : Faces 1,0,3
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(2,j))*0.5;
// idirichlet=3;
// break;
// }
// case 39: //trois Faces de Dirichlet : Faces 2,1,0
// // le point G est le centre de la face de dirichlet opposee a la face non-dirichlet
// {
// for (int j=0; j<dim; j++)
// xg[j]=(x(0,j)+x(1,j))*0.5;
// idirichlet=3;
// break;
// }
// } // fin du switch
}
References TRUSTVect< _TYPE_ >::size().
cree_instance()
Objet_U * Quadri_VEF::cree_instance () static
Definition at line 19 of file Quadri_VEF.cpp.
creer_facette_normales()
void Quadri_VEF::creer_facette_normales (const Zone & zone_geom, DoubleTab & facette_normales, const IntVect & rang_elem_non_std) const override virtual
calcule les normales des facettes pour des elem standards
Implements Elem_VEF_base.
Definition at line 137 of file Quadri_VEF.cpp.
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  const IntTab& les_Polys = zone_geom.les_elems();
  int nb_elem = zone_geom.nb_elem();
  int i, fa7;
  int i0=-1,i1=-1;
  int num_som[4];
  double x[4][2];
  double xg[2];
  double xj0[2];
  double u[2];
  double v[2];
  double psc;
  facette_normales.resize(0, nb_facette(), 2);
  zone_geom.creer_tableau_elements(facette_normales);
  for(i=0; i<nb_elem; i++)
    {
      if (rang_elem_non_std(i)==-1)
        {
          num_som[0]=les_Polys(i,0);
          num_som[1]=les_Polys(i,1);
          num_som[2]=les_Polys(i,2);
          num_som[3]=les_Polys(i,3);
// Cerr << "numero de sommet dans Quadri_VEF : "
// << num_som[0] << " " << num_som[1] << " "
// << num_som[2] << " " << num_som[3] << finl;
          x[0][0]=les_coords(num_som[0],0);
          x[0][1]=les_coords(num_som[0],1);
          x[1][0]=les_coords(num_som[1],0);
          x[1][1]=les_coords(num_som[1],1);
          x[2][0]=les_coords(num_som[2],0);
          x[2][1]=les_coords(num_som[2],1);
          x[3][0]=les_coords(num_som[3],0);
          x[3][1]=les_coords(num_som[3],1);
          xg[0]=(x[0][0]+x[1][0]+x[2][0]+x[3][0])*0.25;
          xg[1]=(x[0][1]+x[1][1]+x[2][1]+x[3][1])*0.25;
          for (fa7=0; fa7<4; fa7++)
            {
// la fa7 d'un element standard a pour sommets
// fa7 et G de coordonnees xg :
              u[0]= x[fa7][0]-xg[0];
              u[1]= x[fa7][1]-xg[1];
              v[0]= -u[1];
              v[1]= u[0];
// Orientation des normales :
              switch (fa7)
                {
                case 0:
                  i0=1;
                  i1=2;
                  break;
                case 1:
                  i0=3;
                  i1=0;
                  break;
                case 2:
                  i0=3;
                  i1=0;
                  break;
                case 3:
                  i0=2;
                  i1=1;
                  break;
                default:
                  i0=-1;
                  i1=-1;
                  assert(0);
                  exit();
                  break;
                }
// i0 = KEL_(0,fa7);
// i1 = KEL_(1,fa7);
              xj0[0]= x[i0][0]-x[i1][0];
              xj0[1]= x[i0][1]-x[i1][1];
              psc=xj0[0]*v[0] + xj0[1]*v[1];
// Cerr << "facette_normales : " << facette_normales << finl;
// Cerr << "numero d'element : " << i << finl;
// Cerr << "numero de fa7 : " << fa7 << finl;
              if (psc < 0)
                {
                  facette_normales(i,fa7,0) = -v[0];
                  facette_normales(i,fa7,1) = -v[1];
                }
              else
                {
                  facette_normales(i,fa7,0) = v[0];
                  facette_normales(i,fa7,1) = v[1];
                }
// Cerr << "facette_normales : " << facette_normales << finl;
            }
        }
    }
  facette_normales.echange_espace_virtuel();
// Cerr << "facette_normales internes (Quadri_VEF::creer_normales_facettes) : " << facette_normales << finl;
}
References Domaine::coord_sommets(), Zone::creer_tableau_elements(), Zone::domaine(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Zone::les_elems(), Zone::nb_elem(), nb_facette(), and TRUSTTab< _TYPE_ >::resize().
creer_normales_facettes_Cl()
void Quadri_VEF::creer_normales_facettes_Cl (DoubleTab & normales_facettes_Cl, int fa7, int num_elem, const DoubleTab & x, const DoubleVect & xg, const Zone & zone_geom) const override virtual
remplit le tableau normales_facettes_Cl dans la Zone_Cl_VEF
pour la facette fa7 de l'element num_elem
Implements Elem_VEF_base.
Definition at line 248 of file Quadri_VEF.cpp.
{
  double u[2];
  double v[2];
  double xj0[2];
  double psc;
  u[0]= x(fa7,0)-xg[0];
  u[1]= x(fa7,1)-xg[1];
  v[0]= -u[1];
  v[1]= u[0];
  int i0=-1;
  int i1=-1;
  switch (fa7)
    {
    case 0:
      i0=1;
      i1=2;
      break;
    case 1:
      i0=3;
      i1=0;
      break;
    case 2:
      i0=3;
      i1=0;
      break;
    case 3:
      i0=2;
      i1=1;
      break;
    default:
      i0=-1;
      i1=-1;
      assert(0);
      exit();
      break;
    }
// Orientation des normales :
  xj0[0]= x(i0,0)-x(i1,0);
  xj0[1]= x(i0,1)-x(i1,1);
  psc=xj0[0]*v[0] + xj0[1]*v[1];
  if (psc < 0)
    {
      normales_facettes_Cl(num_elem,fa7,0) = -v[0];
      normales_facettes_Cl(num_elem,fa7,1) = -v[1];
    }
  else
    {
      normales_facettes_Cl(num_elem,fa7,0) = v[0];
      normales_facettes_Cl(num_elem,fa7,1) = v[1];
    }
// Cerr << "normales_facettes_Cl " << normales_facettes_Cl << finl;
}
References Process::exit().
duplique()
int Quadri_VEF::duplique () const override virtual
Implements Objet_U.
Definition at line 19 of file Quadri_VEF.cpp.
get_info()
const Type_info * Quadri_VEF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 19 of file Quadri_VEF.cpp.
info()
const Type_info * Quadri_VEF::info () static
Definition at line 19 of file Quadri_VEF.cpp.
modif_normales_facettes_Cl()
void Quadri_VEF::modif_normales_facettes_Cl (DoubleTab & normales_facettes_Cl, int fa7, int num_elem, int idirichlet, int n1, int , int) const override virtual
modifie normales_facettes_Cl quand idirichlet=3
idirichlet=nb de faces de Dirichlet de l'element
si idirichlet=3, n1 est le numero du sommet confondu avec G
Implements Elem_VEF_base.
Definition at line 784 of file Quadri_VEF.cpp.
{
// Cerr << "Quadri_VEF::modif_normales_facettes_Cl, fa7 " << fa7 << "num_elem " << num_elem << "idirichlet " << idirichlet << "n1 " << n1 << "normales_facettes_Cl " << normales_facettes_Cl <<  finl;
  switch (idirichlet)
    {
    case 0:
      break;
    case 1:
      break;
    case 2:
      break;
    case 3:
      {
// normales_facettes_Cl(num_elem,n1,0) = 0;
// normales_facettes_Cl(num_elem,n1,1) = 0;
        break;
      }
    }
}
modif_volumes_entrelaces()
void Quadri_VEF::modif_volumes_entrelaces (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & volumes_entrelaces_Cl, int type_cl) const override virtual
modifie les volumes entrelaces pour la face j d'un elem
non standard
Implements Elem_VEF_base.
Definition at line 313 of file Quadri_VEF.cpp.
{
  Cerr << "Quadri_VEF::modif_volumes_entrelaces() ne fait rien pour le moment " << finl;
// double surf_mod;
// const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
// const IntTab& elem_faces = la_zone_VEF.elem_faces();
// Cerr << "elem " << elem << finl;
// Cerr << "type_cl " << type_cl << finl;
// switch(type_cl) {
// // pas de Face de Dirichlet : impossible
// case 0:
// {
// Cerr << "Quadri_VEF::modif_volumes_entrelaces() type 0 impossible!\n";
// break;
// }
// case 1: // une Face de Dirichlet : Face 3
// {
// DoubleTab coord(3,2);
// for(int i=0;i<3;i++)
// for(int k=0;k<2;k++)
// coord(i,k)=la_zone_VEF.zone().domaine().coord(la_zone_VEF.zone().sommet_elem(elem,i),k);
// volumes_entrelaces_Cl[elem_faces(elem,0)]  = std::fabs((coord(0,0)-coord(2,0))*((coord(2,1)+coord(3,1))/2-coord(2,2)) - ((coord(2,0)+coord(3,0))/2-coord(2,0))*(coord(0,1)-coord(2,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,2)]  = std::fabs((coord(1,0)-coord(3,0))*((coord(2,1)+coord(3,1))/2-coord(3,2)) - ((coord(2,0)+coord(3,0))/2-coord(3,0))*(coord(1,1)-coord(3,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,1)]  = std::fabs((coord(1,0)-coord(0,0))*((coord(2,1)+coord(3,1))/2-coord(0,2)) - ((coord(2,0)+coord(3,0))/2-coord(0,0))*(coord(1,1)-coord(0,2)))/2;
// break;
// }
// case 3: // une Face de Dirichlet : Face 2
// {
// DoubleTab coord(3,2);
// for(int i=0;i<3;i++)
// for(int k=0;k<2;k++)
// coord(i,k)=la_zone_VEF.zone().domaine().coord(la_zone_VEF.zone().sommet_elem(elem,i),k);
// volumes_entrelaces_Cl[elem_faces(elem,1)]  = std::fabs((coord(2,0)-coord(3,0))*((coord(1,1)+coord(3,1))/2-coord(3,2)) - ((coord(1,0)+coord(3,0))/2-coord(3,0))*(coord(2,1)-coord(3,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,3)]  = std::fabs((coord(0,0)-coord(1,0))*((coord(1,1)+coord(3,1))/2-coord(1,2)) - ((coord(1,0)+coord(3,0))/2-coord(1,0))*(coord(0,1)-coord(1,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,0)]  = std::fabs((coord(0,0)-coord(2,0))*((coord(1,1)+coord(3,1))/2-coord(2,2)) - ((coord(1,0)+coord(3,0))/2-coord(2,0))*(coord(0,1)-coord(2,2)))/2;
// break;
// }
// case 9: // une Face de Dirichlet : Face 1
// {
// DoubleTab coord(3,2);
// for(int i=0;i<3;i++)
// for(int k=0;k<2;k++)
// coord(i,k)=la_zone_VEF.zone().domaine().coord(la_zone_VEF.zone().sommet_elem(elem,i),k);
// volumes_entrelaces_Cl[elem_faces(elem,0)]  = std::fabs((coord(2,0)-coord(0,0))*((coord(0,1)+coord(1,1))/2-coord(0,2)) - ((coord(0,0)+coord(1,0))/2-coord(0,0))*(coord(2,1)-coord(0,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,2)]  = std::fabs((coord(3,0)-coord(1,0))*((coord(0,1)+coord(1,1))/2-coord(1,2)) - ((coord(0,0)+coord(1,0))/2-coord(1,0))*(coord(3,1)-coord(1,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,3)]  = std::fabs((coord(3,0)-coord(2,0))*((coord(0,1)+coord(1,1))/2-coord(2,2)) - ((coord(0,0)+coord(1,0))/2-coord(2,0))*(coord(3,1)-coord(2,2)))/2;
// break;
// }
// case 27: // une Face de Dirichlet :Face 0
// {
// DoubleTab coord(3,2);
// for(int i=0;i<3;i++) {
// for(int k=0;k<2;k++) {
// Cerr << "la_zone_VEF.zone().sommet_elem(elem,i) " << la_zone_VEF.zone().sommet_elem(elem,i) << finl;
// coord(i,k)=la_zone_VEF.zone().domaine().coord(la_zone_VEF.zone().sommet_elem(elem,i),k);
// Cerr << "coord(i,k) " <<  coord(i,k) << finl;
// }
// }
// Cerr << " elem_faces(elem,1) " << elem_faces(elem,1) << finl;
// Cerr << " elem_faces(elem,3) " << elem_faces(elem,3) << finl;
// Cerr << " elem_faces(elem,2) " << elem_faces(elem,2) << finl;
// Cerr << " coord(0,0) " << coord(0,0) << " coord(0,1) " << coord(0,1)  << finl;
// Cerr << " coord(1,0) " << coord(1,0) << " coord(1,1) " << coord(1,1)  << finl;
// Cerr << " coord(2,0) " << coord(2,0) << " coord(2,1) " << coord(2,1)  << finl;
// volumes_entrelaces_Cl[elem_faces(elem,1)]  = std::fabs((coord(3,0)-coord(2,0))*((coord(0,1)+coord(2,1))/2-coord(2,2)) - ((coord(0,0)+coord(2,0))/2-coord(2,0))*(coord(3,1)-coord(2,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,3)]  = std::fabs((coord(1,0)-coord(0,0))*((coord(0,1)+coord(2,1))/2-coord(0,2)) - ((coord(0,0)+coord(2,0))/2-coord(0,0))*(coord(1,1)-coord(0,2)))/2;
// volumes_entrelaces_Cl[elem_faces(elem,2)]  = std::fabs((coord(3,0)-coord(1,0))*((coord(0,1)+coord(2,1))/2-coord(1,2)) - ((coord(0,0)+coord(2,0))/2-coord(1,0))*(coord(3,1)-coord(1,2)))/2;
// break;
// }
// case 4: // deux Faces de Dirichlet : Faces 2,3
// {
// Cerr << " elem_faces(elem,0) " << elem_faces(elem,0) << finl;
// Cerr << " elem_faces(elem,1) " << elem_faces(elem,1) << finl;
// volumes_entrelaces_Cl[elem_faces(elem,0)]  +=volumes_entrelaces[elem_faces(elem,3)];
// volumes_entrelaces_Cl[elem_faces(elem,1)]  +=volumes_entrelaces[elem_faces(elem,2)];
// break;
// }
// case 28: // deux Faces de Dirichlet : Faces 0,3
// {
// volumes_entrelaces_Cl[elem_faces(elem,1)]  +=volumes_entrelaces[elem_faces(elem,0)];
// volumes_entrelaces_Cl[elem_faces(elem,2)]  +=volumes_entrelaces[elem_faces(elem,3)];
// break;
// }
// case 12: // deux Faces de Dirichlet : Faces 1,2
// {
// volumes_entrelaces_Cl[elem_faces(elem,0)]  +=volumes_entrelaces[elem_faces(elem,1)];
// volumes_entrelaces_Cl[elem_faces(elem,3)]  +=volumes_entrelaces[elem_faces(elem,2)];
// break;
// }
// case 36: // deux Faces de Dirichlet : Faces 0,1
// {
// volumes_entrelaces_Cl[elem_faces(elem,3)]  +=volumes_entrelaces[elem_faces(elem,0)];
// volumes_entrelaces_Cl[elem_faces(elem,2)]  +=volumes_entrelaces[elem_faces(elem,1)];
// break;
// }
// case 10: // deux Faces de Dirichlet : Faces 1,3
// {
// volumes_entrelaces_Cl[elem_faces(elem,0)]  +=volumes_entrelaces[elem_faces(elem,0)];
// volumes_entrelaces_Cl[elem_faces(elem,2)]  +=volumes_entrelaces[elem_faces(elem,2)];
// break;
// }
// case 30: // deux Faces de Dirichlet : Faces 0,2
// {
// volumes_entrelaces_Cl[elem_faces(elem,1)]  +=volumes_entrelaces[elem_faces(elem,1)];
// volumes_entrelaces_Cl[elem_faces(elem,3)]  +=volumes_entrelaces[elem_faces(elem,3)];
// break;
// }
// case 13: //trois Faces de Dirichlet : Faces 3,2,1
// {
// volumes_entrelaces_Cl[elem_faces(elem,0)]  +=volumes_entrelaces[elem_faces(elem,3)]+volumes_entrelaces[elem_faces(elem,2)]
// +volumes_entrelaces[elem_faces(elem,1)];
// break;
// }
// case 31: //trois Faces de Dirichlet : Faces 0,3,2
// {
// volumes_entrelaces_Cl[elem_faces(elem,1)]  +=volumes_entrelaces[elem_faces(elem,3)]+volumes_entrelaces[elem_faces(elem,2)]
// +volumes_entrelaces[elem_faces(elem,0)];
// break;
// }
// case 37: //trois Faces de Dirichlet : Faces 1,0,3
// {
// volumes_entrelaces_Cl[elem_faces(elem,2)]  +=volumes_entrelaces[elem_faces(elem,3)]+volumes_entrelaces[elem_faces(elem,1)]
// +volumes_entrelaces[elem_faces(elem,0)];
// break;
// }
// case 39: //trois Faces de Dirichlet : Faces 2,1,0
// {
// volumes_entrelaces_Cl[elem_faces(elem,3)]  +=volumes_entrelaces[elem_faces(elem,2)]+volumes_entrelaces[elem_faces(elem,1)]
// +volumes_entrelaces[elem_faces(elem,0)];
// break;
// }
// default :
// {
// Cerr << "\n  type inconnu : " << type_cl ;
// exit();
// }
// } // fin du switch
}
References Cerr, and finl.
modif_volumes_entrelaces_faces_joints()
void Quadri_VEF::modif_volumes_entrelaces_faces_joints (int j, int elem, const Zone_VEF & la_zone_VEF, DoubleVect & volumes_entrelaces_Cl, int type_cl) const override virtual
modifie les volumes entrelaces pour la face joint j d'un elem
non standard
Implements Elem_VEF_base.
Definition at line 482 of file Quadri_VEF.cpp.
{
// const DoubleVect& volumes_entrelaces = la_zone_VEF.volumes_entrelaces();
// const IntTab& elem_faces = la_zone_VEF.elem_faces();
// switch(type_cl) {
// // pas de Face de Dirichlet : impossible
// case 0:
// {
// Cerr << "Quadri_VEF::modif_volumes_entrelaces() type 0 impossible!\n";
// break;
// }
// } // fin du switch
}
nb_facette()
int Quadri_VEF::nb_facette () const inline override virtual
Implements Elem_VEF_base.
Definition at line 30 of file Quadri_VEF.h.
  {
    return 4;
  };
Referenced by creer_facette_normales().
normale()
void Quadri_VEF::normale (int num_Face, DoubleTab & Face_normales, const IntTab & Face_sommets, const IntTab & Face_voisins, const IntTab & elem_faces, const Zone & zone_geom) const override virtual
remplit le tableau face_normales dans la Zone_VEF
Implements Elem_VEF_base.
Definition at line 53 of file Quadri_VEF.cpp.
{
  const DoubleTab& les_coords = zone_geom.domaine().coord_sommets();
  double x1,y1;
  double nx,ny;
  double x1g=0,y1g=0;
  double x2g=0,y2g=0;
  double grx,gry,psc;
  int sign=1,i;
  int n0 = Face_sommets(num_Face,0);
  int n1 = Face_sommets(num_Face,1);
  x1 = les_coords(n0,0)-les_coords(n1,0);
  y1 = les_coords(n0,1)-les_coords(n1,1);
  nx = -y1;
  ny = x1;
  int elem1=Face_voisins(num_Face,0);
  int elem2=Face_voisins(num_Face,1);
// Orientation de la normale vers le plus grand numero d'elem
// pour cela on teste d'abord si l'on est sur le bord
  if (elem2!=-1)
    {
// on oriente a partir du centre de gravite
// calcul du centre de gravite de chaque element
      for(i=0; i<4; i++)
        {
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),0);
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),0);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),1);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),1);
          x2g+=les_coords(Face_sommets(elem_faces(elem2,i),0),0);
          x2g+=les_coords(Face_sommets(elem_faces(elem2,i),1),0);
          y2g+=les_coords(Face_sommets(elem_faces(elem2,i),0),1);
          y2g+=les_coords(Face_sommets(elem_faces(elem2,i),1),1);
        }
      grx=(x2g-x1g)*0.125;
      gry=(y2g-y1g)*0.125;
// on regarde le signe du produit scalaire
      psc=grx*nx+gry*ny;
      if(psc<0)
        {
          if(elem1<elem2)
            sign=-1;
          else if(elem2<elem1)
            sign=-1;
        }
    }
  else
    {
// on oriente a partir du centre de gravite et du milieu de la
// face courante
      for(i=0; i<4; i++)
        {
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),0);
          x1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),0);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),0),1);
          y1g+=les_coords(Face_sommets(elem_faces(elem1,i),1),1);
        }
// Cerr << "xg et yg de Face_normales: " << x1g << " " << y1g << finl;
      x2g = les_coords(n0,0)+les_coords(n1,0);
      y2g = les_coords(n0,1)+les_coords(n1,1);
      grx=x2g*0.5-x1g*0.125;
      gry=y2g*0.5-y1g*0.125;
// Cerr << "grx et gry : " << grx << " " << gry << finl;
// on regarde le signe du produit scalaire
      psc=grx*nx+gry*ny;
      if(psc<0)
        sign=-1;
    }
  Face_normales(num_Face,0)=sign*nx;
  Face_normales(num_Face,1)=sign*ny;
}
References Domaine::coord_sommets(), and Zone::domaine().
printOn()
Sortie & Quadri_VEF::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 23 of file Quadri_VEF.cpp.
{
  return s << que_suis_je() << "\n";
}
References Objet_U::que_suis_je().
readOn()
Entree & Quadri_VEF::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Elem_VEF_base.
Definition at line 28 of file Quadri_VEF.cpp.
{
  return s ;
}
self_cast() [1/2]
const Quadri_VEF & Quadri_VEF::self_cast (const Objet_U & r) static
Definition at line 19 of file Quadri_VEF.cpp.
self_cast() [2/2]
Quadri_VEF & Quadri_VEF::self_cast (Objet_U & r) static
Definition at line 19 of file Quadri_VEF.cpp.
taille_memoire()
unsigned Quadri_VEF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 19 of file Quadri_VEF.cpp.
traiter_normales_facettes_Cl()
void Quadri_VEF::traiter_normales_facettes_Cl (DoubleTab & , int , int , const DoubleTab & , const DoubleVect & , int , int , int , int , int) const
Member Data Documentation
info_obj
const Type_info Quadri_VEF::info_obj static
Definition at line 26 of file Quadri_VEF.h.
The documentation for this class was generated from the following files:
src/VEF/Zones/Quadri_VEF.h
src/VEF/Zones/Quadri_VEF.cpp