TRUST: ModPerm_Carman_Kozeny Class Reference
ModPerm_Carman_Kozeny Class Reference
Cette classe represente la correlation de Carman Kozeny
pour la permeabilite d'un lit de particule de diametre donne.
#include <ModPerm_Carman_Kozeny.h>
Public Member Functions
~ModPerm_Carman_Kozeny ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
ModPerm_Carman_Kozeny ()
double getK (double porosite) const
void setDiametre (double d)
double getDiametre () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static ModPerm_Carman_Kozeny & self_cast (Objet_U &)
static const
ModPerm_Carman_Kozeny & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Public Attributes
double diam
double C
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Imprime le type du modele sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Detailed Description
Cette classe represente la correlation de Carman Kozeny
pour la permeabilite d'un lit de particule de diametre donne.
Definition at line 36 of file ModPerm_Carman_Kozeny.h.
Constructor & Destructor Documentation
ModPerm_Carman_Kozeny::~ModPerm_Carman_Kozeny ()
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
ModPerm_Carman_Kozeny::ModPerm_Carman_Kozeny ()
Definition at line 28 of file ModPerm_Carman_Kozeny.cpp.
: diam(1.),C(180.) { }
Member Function Documentation
Objet_U * ModPerm_Carman_Kozeny::cree_instance () [static]
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
int ModPerm_Carman_Kozeny::duplique () const [virtual]
Implements Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
const Type_info * ModPerm_Carman_Kozeny::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
double ModPerm_Carman_Kozeny::getDiametre () const [inline]
Definition at line 55 of file ModPerm_Carman_Kozeny.h.
References diam.
  {
    return diam;
  } ;
double ModPerm_Carman_Kozeny::getK (double porosite) const [inline, virtual]
Renvoie la valeur de la permeabilite en fonction de la porosite (d'une face par exemple).
Parameters:
porosite la porosite
Implements Modele_Permeabilite_base.
Definition at line 66 of file ModPerm_Carman_Kozeny.h.
References C, and diam.
{
// assert(porosite != 1.);
// Cout << " Dans ModPerm_Carman_Kozeny C = " << C << finl;
  double tmp = diam *porosite /(1.-porosite);
  return tmp*tmp*porosite/C;
}
const Type_info * ModPerm_Carman_Kozeny::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
Sortie & ModPerm_Carman_Kozeny::printOn (Sortie & s) const [protected, virtual]
Imprime le type du modele sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 45 of file ModPerm_Carman_Kozeny.cpp.
References Objet_U::que_suis_je().
{
  return s << que_suis_je() << "\n";
}
Entree & ModPerm_Carman_Kozeny::readOn (Entree & is) [protected, virtual]
Lit les specifications d'un modele Permeabilite
a partir d'un flot d'entree.
Controle dynamique du type du terme source.
Returns:
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 67 of file ModPerm_Carman_Kozeny.cpp.
References Cerr, diam, Process::exit(), finl, Objet_U::que_suis_je(), and Motcles::search().
{
  Motcles les_mots(1);
  {
    les_mots[0] = "diametre";
  }
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> diam;
            break;
          }
        default :
          {
            Cerr << "Mot cle inconnu dans ModPerm_Carman_Kozeny  " << finl;
            exit();
          }
        }
      is >> motlu;
    }
// Cout << "<<<<<<<<<<<<<<Dans ModPerm_Carman_Kozeny diam = " << diam << finl;
  return is;
}
const ModPerm_Carman_Kozeny & ModPerm_Carman_Kozeny::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
ModPerm_Carman_Kozeny & ModPerm_Carman_Kozeny::self_cast (Objet_U & r) [static]
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
void ModPerm_Carman_Kozeny::setDiametre (double d) [inline]
Definition at line 51 of file ModPerm_Carman_Kozeny.h.
References diam.
  {
    diam = d;
  } ;
unsigned ModPerm_Carman_Kozeny::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 26 of file ModPerm_Carman_Kozeny.cpp.
Member Data Documentation
double ModPerm_Carman_Kozeny::C
Definition at line 63 of file ModPerm_Carman_Kozeny.h.
Referenced by getK(), and ModPerm_ErgunPourDarcy::ModPerm_ErgunPourDarcy().
double ModPerm_Carman_Kozeny::diam
Definition at line 58 of file ModPerm_Carman_Kozeny.h.
Referenced by getDiametre(), getK(), ModPerm_ErgunPourDarcy::ModPerm_ErgunPourDarcy(), readOn(), and setDiametre().
const Type_info ModPerm_Carman_Kozeny::info_obj [static]
Reimplemented from Modele_Permeabilite_base.
Reimplemented in ModPerm_ErgunPourDarcy.
Definition at line 39 of file ModPerm_Carman_Kozeny.h.
The documentation for this class was generated from the following files:
src/VDF/Sources/ModPerm_Carman_Kozeny.h
src/VDF/Sources/ModPerm_Carman_Kozeny.cpp