TRUST: Assembleur_base Class Reference
Assembleur_base Class Reference abstract
#include <Assembleur_base.h>
Public Member Functions
Assembleur_base ()
~Assembleur_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
int set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
int get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
int set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
int get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
virtual int assembler (Matrice &)=0
virtual int assembler_mat (Matrice &, const DoubleVect &, int incr_pression, int resoudre_en_u)
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
virtual int assembler_QC (const DoubleTab &, Matrice &)
virtual void completer (const Equation_base &)=0
virtual void associer_zone_dis_base (const Zone_dis_base &)=0
virtual void associer_zone_cl_dis_base (const Zone_Cl_dis_base &)=0
virtual const Zone_dis_base & zone_dis_base () const =0
virtual const Zone_Cl_dis_base & zone_Cl_dis_base () const =0
virtual int modifier_secmem (DoubleTab &)=0
virtual void modifier_secmem_pour_incr_p (const DoubleTab &press, const double fac, DoubleTab &incr) const
virtual int modifier_solution (DoubleTab &)=0
virtual void dimensionner_continuite (matrices_t matrices, int aux_only=0) const
virtual void assembler_continuite (matrices_t matrices, DoubleTab &secmem, int aux_only=0) const
virtual DoubleTab norme_continuite () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Assembleur_base & self_cast (Objet_U &)
static const Assembleur_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
int resoudre_increment_pression_
int resoudre_en_u_
Detailed Description
Definition at line 29 of file Assembleur_base.h.
Constructor & Destructor Documentation
Assembleur_base()
Assembleur_base::Assembleur_base ()
Definition at line 20 of file Assembleur_base.cpp.
                                 :
  resoudre_increment_pression_(-1),resoudre_en_u_(-1) //!< -1 signifie "non initialise"
{
}
~Assembleur_base()
Assembleur_base::~Assembleur_base () override
Definition at line 18 of file Assembleur_base.cpp.
Member Function Documentation
assembler()
virtual int Assembleur_base::assembler (Matrice &) pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Assembleur::assembler().
assembler_continuite()
virtual void Assembleur_base::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const inline virtual
Reimplemented in Assembleur_P_PolyMAC, and Assembleur_P_PolyMAC_P0.
Definition at line 64 of file Assembleur_base.h.
  {
    Process::exit(Nom("assembler_continuite(...) must be overloaded by ") + que_suis_je());
  };
References Process::exit(), and Objet_U::que_suis_je().
assembler_mat()
virtual int Assembleur_base::assembler_mat (Matrice & , const DoubleVect & , int incr_pression, int resoudre_en_u) inline virtual
Reimplemented in Assembleur_P_EF, Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_PolyMAC_P0, Assembleur_P_VDF, and Assembleur_P_VEF.
Definition at line 38 of file Assembleur_base.h.
  {
    Cerr << "assembler_mat(Matrice&,const DoubleVect&,int incr_pression,int resoudre_en_u) must be overloaded by " << que_suis_je() << finl;
    exit();
    return 1;
  }
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), Navier_Stokes_std::initTimeStep(), and Navier_Stokes_std::preparer_calcul().
assembler_QC()
int Assembleur_base::assembler_QC (const DoubleTab & , Matrice & matrice) virtual
Reimplemented in Assembleur_P_EF, Assembleur_P_PolyMAC, Assembleur_P_VDF, and Assembleur_P_VEF.
Definition at line 99 of file Assembleur_base.cpp.
{
  Cerr << "Stop in Assembleur_base::assembler_QC." << finl;
  assert(0);
  exit();
  return 1;
}
References Cerr, Process::exit(), and finl.
Referenced by Assembleur::assembler_QC().
assembler_rho_variable()
int Assembleur_base::assembler_rho_variable (Matrice & mat, const Champ_Don_base & rho) virtual
Assemblage de la matrice div(porosite/rho * grad P)
Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, ...)
Pour le front-tracking par exemple.
Reimplemented in Assembleur_P_VEFPreP1B, Assembleur_P_EF, Assembleur_P_PolyMAC, and Assembleur_P_VDF.
Definition at line 89 of file Assembleur_base.cpp.
{
  Cerr << "Error in Assembleur_base::assembler_rho_variable\n";
  Cerr << "This method has not been implemented for ";
  Cerr << que_suis_je() << finl;
  assert(0);
  exit();
  return 0;
}
References Cerr, Process::exit(), finl, and Objet_U::que_suis_je().
associer_zone_cl_dis_base()
virtual void Assembleur_base::associer_zone_cl_dis_base (const Zone_Cl_dis_base &) pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Assembleur::associer_zone_cl_dis_base().
associer_zone_dis_base()
virtual void Assembleur_base::associer_zone_dis_base (const Zone_dis_base &) pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Assembleur::associer_zone_dis_base().
completer()
void Assembleur_base::completer (const Equation_base &) pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Definition at line 107 of file Assembleur_base.cpp.
{
  ;
}
Referenced by Assembleur::completer().
dimensionner_continuite()
virtual void Assembleur_base::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const inline virtual
Reimplemented in Assembleur_P_PolyMAC, and Assembleur_P_PolyMAC_P0.
Definition at line 60 of file Assembleur_base.h.
  {
    Process::exit(Nom("dimensionner_continuite(...) must be overloaded by ") + que_suis_je());
  }
References Process::exit(), and Objet_U::que_suis_je().
get_info()
const Type_info * Assembleur_base::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_PolyMAC_P0, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Definition at line 18 of file Assembleur_base.cpp.
get_resoudre_en_u()
int Assembleur_base::get_resoudre_en_u () const
Renvoie la valeur du drapeau resoudre_en_u_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
Definition at line 80 of file Assembleur_base.cpp.
{
  return resoudre_en_u_;
}
References resoudre_en_u_.
Referenced by Assembleur_P_VDF::assembler_rho_variable(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), and Assembleur_P_VDF::modifier_secmem_vitesse_imposee().
get_resoudre_increment_pression()
int Assembleur_base::get_resoudre_increment_pression () const
Renvoie la valeur du drapeau resoudre_increment_pression_ (0 ou 1)
Renvoie -1 si le drapeau n'a pas ete initialise.
Definition at line 58 of file Assembleur_base.cpp.
{
  return resoudre_increment_pression_;
}
References resoudre_increment_pression_.
Referenced by Assembleur_P_VDF::assembler_QC(), Assembleur_P_VDF::assembler_rho_variable(), Navier_Stokes_std::corriger_derivee_expl(), Navier_Stokes_std::corriger_derivee_impl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), and Assembleur_P_VDF::modifier_secmem_pression_imposee().
info()
const Type_info * Assembleur_base::info () static
Definition at line 18 of file Assembleur_base.cpp.
modifier_secmem()
virtual int Assembleur_base::modifier_secmem (DoubleTab &) pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Simpler::iterer_NS(), Assembleur::modifier_secmem(), and Traitement_particulier_NS_Pression_VEF::post_traitement_particulier_calcul_pression().
modifier_secmem_pour_incr_p()
virtual void Assembleur_base::modifier_secmem_pour_incr_p (const DoubleTab & press, const double fac, DoubleTab & incr) const inline virtual
Reimplemented in Assembleur_P_PolyMAC, and Assembleur_P_PolyMAC_P0.
Definition at line 55 of file Assembleur_base.h.
{ };
modifier_solution()
virtual int Assembleur_base::modifier_solution (DoubleTab &) pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), and Assembleur::modifier_solution().
norme_continuite()
virtual DoubleTab Assembleur_base::norme_continuite () const inline virtual
Reimplemented in Assembleur_P_PolyMAC.
Definition at line 68 of file Assembleur_base.h.
  {
    Process::exit(Nom("norme_continuite(...) must be overloaded by ") + que_suis_je());
    return DoubleTab();
  };
References Process::exit(), and Objet_U::que_suis_je().
printOn()
Sortie & Assembleur_base::printOn (Sortie & s) const override protected virtual
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Returns
Sortie&
Signification: flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_PolyMAC_P0, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Definition at line 28 of file Assembleur_base.cpp.
{
  return s  << que_suis_je();
}
References Objet_U::que_suis_je().
Referenced by Assembleur_P_VEFPreP1B::printOn().
readOn()
Entree & Assembleur_base::readOn (Entree & s) override protected virtual
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Returns
Entree& s
Signification: flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Reimplemented in Assembleur_P_VEFPreP1B, Assembleur_P_PolyMAC, Assembleur_P_PolyMAC_P0, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Definition at line 36 of file Assembleur_base.cpp.
{
  return is;
}
Referenced by Assembleur_P_EF::readOn(), Assembleur_P_VEFPreP1B::readOn(), Assembleur_P_PolyMAC::readOn(), Assembleur_P_VDF::readOn(), Assembleur_P_VDF_Q4::readOn(), and Assembleur_P_VEF::readOn().
self_cast() [1/2]
const Assembleur_base & Assembleur_base::self_cast (const Objet_U & r) static
Definition at line 18 of file Assembleur_base.cpp.
self_cast() [2/2]
Assembleur_base & Assembleur_base::self_cast (Objet_U & r) static
Definition at line 18 of file Assembleur_base.cpp.
set_resoudre_en_u()
int Assembleur_base::set_resoudre_en_u (int flag)
Definit la valeur du drapeau resoudre_en_u__.
Ce drapeau determine si le solveur en pression resou en u ou en rho*u
(cela affecte
en particulier le calcul des conditions aux limites Dirichlet).
flag = 1 : resolution en u
flag = 0 : resolution en rho_u.
Definition at line 70 of file Assembleur_base.cpp.
{
  assert(flag == 0 || flag == 1);
  resoudre_en_u_ = flag;
  return flag;
}
References resoudre_en_u_.
Referenced by Assembleur_P_VDF::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_VDF::assembler_mat(), Assembleur_P_VEF::assembler_mat(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), and Assembleur_P_VEF::assembler_QC().
set_resoudre_increment_pression()
int Assembleur_base::set_resoudre_increment_pression (int flag)
Definit la valeur du drapeau resoudre_increment_pression_.
Ce drapeau determine si le solveur en pression calcule un increment de
pression entre deux pas de temps ou la pression totale (cela affecte
en particulier le calcul des conditions aux limites).
flag = 0 : resolution en pression
flag = 1 : resolution en increment de pression.
Definition at line 48 of file Assembleur_base.cpp.
{
  assert(flag == 0 || flag == 1);
  resoudre_increment_pression_ = flag;
  return flag;
}
References resoudre_increment_pression_.
Referenced by Assembleur_P_VDF::assembler(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_VDF::assembler_mat(), Assembleur_P_VEF::assembler_mat(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), and Assembleur_P_VDF::assembler_QC().
zone_Cl_dis_base()
virtual const Zone_Cl_dis_base & Assembleur_base::zone_Cl_dis_base () const pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Assembleur::zone_Cl_dis_base().
zone_dis_base()
virtual const Zone_dis_base & Assembleur_base::zone_dis_base () const pure virtual
Implemented in Assembleur_P_EF, Assembleur_P_PolyMAC, Assembleur_P_VDF, Assembleur_P_VDF_Q4, and Assembleur_P_VEF.
Referenced by Assembleur::zone_dis_base().
Member Data Documentation
info_obj
const Type_info Assembleur_base::info_obj static
Definition at line 31 of file Assembleur_base.h.
resoudre_en_u_
int Assembleur_base::resoudre_en_u_ private
Definition at line 78 of file Assembleur_base.h.
Referenced by get_resoudre_en_u(), and set_resoudre_en_u().
resoudre_increment_pression_
int Assembleur_base::resoudre_increment_pression_ private
Definition at line 77 of file Assembleur_base.h.
Referenced by get_resoudre_increment_pression(), and set_resoudre_increment_pression().
The documentation for this class was generated from the following files:
src/Kernel/Framework/Assembleur_base.h
src/Kernel/Framework/Assembleur_base.cpp