TRUST: Extraire_surface Class Reference
Extraire_surface Class Reference
Classe Extraire_surface
Lecture d'un fichier.
#include <Extraire_surface.h>
Public Member Functions
Extraire_surface ()
~Extraire_surface ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
Entree & interpreter_ (Entree &) override
Fonction principale de l'interprete.
Public Member Functions inherited from Interprete_geometrique_base
Interprete_geometrique_base ()
~Interprete_geometrique_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter_ (Entree &is)=0
Entree & interpreter (Entree &is) override
void associer_domaine (Nom &nom_dom)
void associer_domaine (Entree &is)
Domaine & domaine (int i=0)
const Domaine & domaine (int i=0) const
List_Ref_Domaine & domaines ()
void mettre_a_jour_sous_zone (Zone &zone, int &elem, int num_premier_elem, int nb_elem) const
Public Member Functions inherited from Interprete
Interprete ()
~Interprete ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual Entree & interpreter (Entree &is)
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Extraire_surface & self_cast (Objet_U &)
static const Extraire_surface & self_cast (const Objet_U &)
static void extraire_surface (Domaine &dom, const Domaine &domaine_volumique, const Nom &nom_domaine_surfacique, const Zone_VF &zone_vf, const Nom &expr_elements, const Nom &expr_faces, int avec_les_bords, const Noms &noms_des_bords)
Static Public Member Functions inherited from Interprete_geometrique_base
static const Type_info * info ()
static Interprete_geometrique_base & self_cast (Objet_U &)
static const Interprete_geometrique_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Interprete
static Objet_U * cree_instance ()
static const Type_info * info ()
static Interprete & self_cast (Objet_U &)
static const Interprete & self_cast (const Objet_U &)
static Objet_U & objet (const Nom &)
Voir Interprete_bloc::objet_global()
BM: la classe Interprete n'est pas le meilleur endroit pour cette
methode mais on verra ca plus tard...
static int objet_existant (const Nom &)
Renvoie 1 si l'objet existe, 0 sinon
voir Interprete_bloc::objet_global_existant()
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Interprete_geometrique_base
static const Type_info info_obj
Static Public Attributes inherited from Interprete
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Simple appel a: Interprete::printOn(Sortie&)
Entree & readOn (Entree &) override
Simple appel a: Interprete::readOn(Entree&)
Protected Member Functions inherited from Interprete_geometrique_base
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Interprete
Sortie & printOn (Sortie &x) const override
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
Entree & readOn (Entree &) override
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Additional Inherited Members
Protected Attributes inherited from Interprete_geometrique_base
List_Ref_Domaine domains_
List of reference to domains.
Detailed Description
Classe Extraire_surface
Lecture d'un fichier.
Definition at line 37 of file Extraire_surface.h.
Constructor & Destructor Documentation
Extraire_surface()
Extraire_surface::Extraire_surface ()
Definition at line 25 of file Extraire_surface.cpp.
~Extraire_surface()
Extraire_surface::~Extraire_surface ()
Definition at line 25 of file Extraire_surface.cpp.
Member Function Documentation
cree_instance()
Objet_U * Extraire_surface::cree_instance () static
Definition at line 25 of file Extraire_surface.cpp.
duplique()
int Extraire_surface::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Extraire_surface.cpp.
extraire_surface()
void Extraire_surface::extraire_surface (Domaine & dom, const Domaine & domaine_volumique, const Nom & nom_domaine_surfacique, const Zone_VF & zone_vf, const Nom & expr_elements, const Nom & expr_faces, int avec_les_bords, const Noms & noms_des_bords) static
< pas un joint, ou on est le proprietaire
Definition at line 126 of file Extraire_surface.cpp.
{
  domaine_surfacique.nommer(nom_domaine_surfacique);
  Parser_U condition_elements,condition_faces;
  condition_elements.setNbVar(dimension);
  condition_elements.addVar("x");
  condition_elements.addVar("y");
  if (dimension==3)
    condition_elements.addVar("z");
  condition_faces.setNbVar(dimension);
  condition_faces.addVar("x");
  condition_faces.addVar("y");
  if (dimension==3)
    condition_faces.addVar("z");
  condition_faces.setString(expr_faces);
  condition_faces.parseString();
  condition_elements.setString(expr_elements);
  condition_elements.parseString();
// Copie des sommets
  domaine_surfacique.les_sommets()=domaine_volumique.les_sommets();
  const DoubleTab& coord=domaine_surfacique.les_sommets();
  Zone zone__;
  domaine_surfacique.add(zone__);
  Zone& zone=domaine_surfacique.zone(0);
  zone.nommer("NO_FACE");
  const Nom& type_elem=zone_vf.zone().type_elem().valeur().que_suis_je();
  if (dimension==3)
    {
      if (type_elem==Motcle("Tetraedre"))
        {
          zone.typer("Triangle");
        }
      else
        {
          if (type_elem==Motcle("Segment"))
            {
              zone.typer("Point");
            }
          else
            {
              if ((type_elem==Motcle("Hexaedre"))|| (type_elem==Motcle("Hexaedre_VEF")))
                {
                  zone.typer("Quadrangle");
                }
              else
                {
                  if (type_elem==Motcle("Polyedre"))
                    {
                      zone.typer("Polygone");
                    }
                  else
                    {
                      Cerr<<"WARNING "<<type_elem<< " not coded, use Quadrangle" <<finl;
                      zone.typer("Quadrangle");
// exit();
                    }
                }
            }
        }
    }
  else
    {
      zone.typer("segment");
    }
  zone.associer_domaine(domaine_surfacique);
  const DoubleTab& xp =zone_vf.xp();
  int nb_elem=zone_vf.nb_elem();
  IntTab marq_elem;
  zone_vf.zone().creer_tableau_elements(marq_elem);
  std::string X("X"), Y("Y"), Z("Z");
  for (int elem=0; elem<nb_elem; elem++)
    {
      condition_elements.setVar(X,xp(elem,0));
      condition_elements.setVar(Y,xp(elem,1));
      if (dimension==3)
        condition_elements.setVar(Z,xp(elem,2));
      double res=condition_elements.eval();
      if (std::fabs(res)>1e-5)
        marq_elem(elem)=1;
      else
        marq_elem(elem)=0;
    }
  marq_elem.echange_espace_virtuel();
  const DoubleTab& xv =zone_vf.xv();
  int nb_faces=zone_vf.nb_faces();
  const IntTab& face_voisin=zone_vf.face_voisins();
  ArrOfInt marq(nb_faces);
// on marque les joints
  int nbjoints=zone_vf.nb_joints();
  for(int njoint=0; njoint<nbjoints; njoint++)
    {
      const Joint& joint_temp = zone_vf.joint(njoint);
      int pe_voisin=joint_temp.PEvoisin();
      if (pe_voisin<me())
        {
          const IntTab& indices_faces_joint = joint_temp.joint_item(Joint::FACE).renum_items_communs();
          const int nbfaces = indices_faces_joint.dimension(0);
          for (int j = 0; j < nbfaces; j++)
            {
              int face_de_joint = indices_faces_joint(j, 1);
              marq[face_de_joint] = -1;
            }
        }
    }
  int nb_t=0;
// on flage les face sde bords qui nous interesse
  ArrOfInt face_bord_int(nb_faces);
  if (avec_les_bords==1)
    face_bord_int=1;
  if (noms_des_bords.size()!=0)
    {
      if (avec_les_bords!=0)
        {
          Cerr<<" the option avec_les_bords is incompatible with the option avec_certains_bords"<<finl;
          exit();
        }
      for (int b=0; b<noms_des_bords.size(); b++)
        {
          const Frontiere& fr=zone_vf.frontiere_dis(zone_vf.rang_frontiere(noms_des_bords[b])).frontiere();
          int deb=fr.num_premiere_face();
          int fin=deb+fr.nb_faces();
          for (int f=deb; f<fin; f++)
            face_bord_int[f]=1;
        }
    }
// on marque toutes les faces que l'on veut mettre dans le domaine
  for (int fac=0; fac<nb_faces; fac++)
    {
      int elem0=face_voisin(fac,0);
      int elem1=face_voisin(fac,1);
      int val0=-1;
      if (elem0!=-1) val0=marq_elem(elem0);
      int val1=-1;
      if (elem1!=-1) val1=marq_elem(elem1);
      if (val0!=val1)
        {
          if (((val0*val1==0)&&(val0+val1==1))||((val0==1)&&(face_bord_int[fac]==1))||((val1==1)&&(face_bord_int[fac]==1)))
// if (zone_test.chercher_elements(xv(fac,0),xv(fac,1),xv(fac,2))==0)
            {
              condition_faces.setVar(X,xv(fac,0));
              condition_faces.setVar(Y,xv(fac,1));
              if (dimension==3)
                condition_faces.setVar(Z,xv(fac,2));
              double res=condition_faces.eval();
              if (std::fabs(res)>1e-5)
                if (marq[fac]!=-1)  //!< pas un joint, ou on est le proprietaire
                  {
                    marq[fac]=1;
                    nb_t++;
                  }
            }
        }
    }
  ArrOfDouble point0b(3),point1b(3),point2b(3);
  Cerr<<"Number of elements of the new domain : "<<nb_t<<finl;
  IntTab& les_elems=zone.les_elems();
  const IntTab& face_sommets=zone_vf.face_sommets();
  int nb_sommet_face=face_sommets.dimension(1);
  les_elems.resize(nb_t,nb_sommet_face);
  int nb=0;
  ArrOfDouble normal(dimension);
  ArrOfDouble normal_b(3);
  for (int fac=0; fac<nb_faces; fac++)
    if (marq[fac]==1)
      {
        int el1=face_voisin(fac,0);
        if (el1==-1)  el1=face_voisin(fac,1);
        if (marq_elem(el1)!=1)
          el1=face_voisin(fac,1);
        for (int i=0; i<dimension; i++)
          normal[i]=xv(fac,i)-xp(el1,i);
        for (int s=0; s<nb_sommet_face; s++)
          les_elems(nb,s)=face_sommets(fac,s);
// on calcule la normale
        if (nb_sommet_face>1)
          {
            if (dimension==3)
              {
                for (int i=0; i<3; i++)
                  {
                    point0b[i]=coord(les_elems(nb,0),i);
                    point1b[i]=coord(les_elems(nb,1),i);
                    point2b[i]=coord(les_elems(nb,2),i);
                  }
                calcul_normal(point0b,point1b,point2b,normal_b);
                if (dotproduct_array(normal,normal_b)<0)
                  {
// si normal a l'envers on inverse les deux sommets
                    les_elems(nb,1)=face_sommets(fac,2);
                    les_elems(nb,2)=face_sommets(fac,1);
                  }
              }
            else
              {
                for (int i=0; i<nb_sommet_face; i++)
                  {
                    point0b[i]=coord(les_elems(nb,1),i)-coord(les_elems(nb,0),i);
                  }
                double produit=normal[0]*point0b[1]-normal[1]*point0b[0];
                if (produit<0)
                  {
// si normal a l'envers on inverse les deux sommets
                    les_elems(nb,0)=face_sommets(fac,1);
                    les_elems(nb,1)=face_sommets(fac,0);
                  }
              }
          }
        nb++;
      }
  assert(nb==nb_t);
  NettoieNoeuds::nettoie(domaine_surfacique);
}
References Domaine::add(), Parser_U::addVar(), Zone::associer_domaine(), calcul_normal(), Cerr, Zone::creer_tableau_elements(), TRUSTTab< _TYPE_ >::dimension(), Objet_U::dimension, dotproduct_array(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Parser_U::eval(), Process::exit(), Joint::FACE, Zone_VF::face_sommets(), Zone_VF::face_voisins(), finl, Frontiere_dis_base::frontiere(), Zone_VF::frontiere_dis(), Zone_VF::joint(), Joint::joint_item(), Zone::les_elems(), Domaine::les_sommets(), Process::me(), Zone_dis_base::nb_elem(), Frontiere::nb_faces(), Zone_VF::nb_faces(), Zone_VF::nb_joints(), NettoieNoeuds::nettoie(), Domaine::nommer(), Zone::nommer(), Frontiere::num_premiere_face(), Parser_U::parseString(), Joint::PEvoisin(), Objet_U::que_suis_je(), Zone_dis_base::rang_frontiere(), Joint_Items::renum_items_communs(), TRUSTTab< _TYPE_ >::resize(), Parser_U::setNbVar(), Parser_U::setString(), Parser_U::setVar(), vect_impl::size(), Zone::type_elem(), type_elem(), Zone::typer(), Deriv_Elem_geom_base::valeur(), Zone_VF::xp(), Zone_VF::xv(), Zone_dis_base::zone(), and Domaine::zone().
Referenced by Domaine::creer_mes_domaines_frontieres(), and interpreter_().
get_info()
const Type_info * Extraire_surface::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Objet_U.
Definition at line 25 of file Extraire_surface.cpp.
info()
const Type_info * Extraire_surface::info () static
Definition at line 25 of file Extraire_surface.cpp.
interpreter_()
Entree & Extraire_surface::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete.
Returns
Entree&
Signification: le flot d'entree
Contraintes:
Implements Interprete_geometrique_base.
Definition at line 79 of file Extraire_surface.cpp.
{
  Nom nom_pb;
  Nom nom_domaine_surfacique;
  Nom expr_elements("1"),expr_faces("1");
  int avec_les_bords;
  Noms noms_des_bords;
  Param param(que_suis_je());
  param.ajouter("domaine",&nom_domaine_surfacique,Param::REQUIRED);
  param.ajouter("probleme",&nom_pb,Param::REQUIRED);
  param.ajouter("condition_elements",&expr_elements);
  param.ajouter("condition_faces",&expr_faces);
  param.ajouter_flag("avec_les_bords",&avec_les_bords);
  param.ajouter("avec_certains_bords",&noms_des_bords);
  param.lire_avec_accolades_depuis(is);
  associer_domaine(nom_domaine_surfacique);
  Domaine& domaine_surfacique=domaine();
  if (domaine_surfacique.nb_som_tot()!=0)
    {
      Cerr << "Error!" << finl;
      Cerr <<"The domain " << domaine_surfacique.le_nom() << " can't be used by the Extraire_surface keyword." <<finl;
      Cerr <<"The domain for Extraire_surface keyword should be empty and created just before." << finl;
      exit();
    }
// on recupere le pb
  if(! sub_type(Probleme_base, objet(nom_pb)))
    {
      Cerr << nom_pb << " is of type " << objet(nom_pb).que_suis_je() << finl;
      Cerr << "and not of type Probleme_base" << finl;
      exit();
    }
  Probleme_base& pb=ref_cast(Probleme_base, objet(nom_pb));
  const Zone_VF& zone_vf=ref_cast(Zone_VF,pb.equation(0).zone_dis().valeur());
  const Domaine& domaine_volumique = zone_vf.zone().domaine();
  extraire_surface(domaine_surfacique,domaine_volumique,nom_domaine_surfacique,zone_vf,expr_elements,expr_faces,avec_les_bords,noms_des_bords);
  return is;
}
References Param::ajouter(), Param::ajouter_flag(), Interprete_geometrique_base::associer_domaine(), Cerr, Zone::domaine(), Interprete_geometrique_base::domaine(), Probleme_base::equation(), Process::exit(), extraire_surface(), finl, Domaine::le_nom(), Param::lire_avec_accolades_depuis(), Domaine::nb_som_tot(), Interprete::objet(), Objet_U::que_suis_je(), ref_cast, Param::REQUIRED, sub_type, Deriv_Zone_dis_base::valeur(), Zone_dis_base::zone(), and Equation_base::zone_dis().
printOn()
Sortie & Extraire_surface::printOn (Sortie & os) const override protected virtual
Simple appel a: Interprete::printOn(Sortie&)
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 41 of file Extraire_surface.cpp.
{
  return Interprete::printOn(os);
}
References Interprete::printOn().
readOn()
Entree & Extraire_surface::readOn (Entree & is) override protected virtual
Simple appel a: Interprete::readOn(Entree&)
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Objet_U.
Definition at line 60 of file Extraire_surface.cpp.
{
  return Interprete::readOn(is);
}
References Interprete::readOn().
self_cast() [1/2]
const Extraire_surface & Extraire_surface::self_cast (const Objet_U & r) static
Definition at line 25 of file Extraire_surface.cpp.
self_cast() [2/2]
Extraire_surface & Extraire_surface::self_cast (Objet_U & r) static
Definition at line 25 of file Extraire_surface.cpp.
taille_memoire()
unsigned Extraire_surface::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Extraire_surface.cpp.
Member Data Documentation
info_obj
const Type_info Extraire_surface::info_obj static
Definition at line 39 of file Extraire_surface.h.
The documentation for this class was generated from the following files:
src/Kernel/Geometrie/Extraire_surface.h
src/Kernel/Geometrie/Extraire_surface.cpp