TRUST: Ref_Equation_base Class Reference
Ref_Equation_base Class Reference
#include <Ref_Equation_base.h>
Public Member Functions
~Ref_Equation_base ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
Ref_Equation_base ()
Ref_Equation_base (const Equation_base &)
Ref_Equation_base (const Ref_Equation_base &)
const Equation_base & valeur () const
Equation_base & valeur ()
const Equation_base * operator-> () const
Equation_base * operator-> ()
const Ref_Equation_base & operator= (const Equation_base &)
const Ref_Equation_base & operator= (const Ref_Equation_base &)
operator const Equation_base & () const
operator Equation_base & ()
const Type_info & get_info_ptr () const
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static Ref_Equation_base & self_cast (Objet_U &)
static const Ref_Equation_base & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
Ecriture de l'Objet_U reference sur un flot de sortie.
virtual Entree & readOn (Entree &)
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
void set_O_U_Ptr (Objet_U *)
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Private Attributes
Equation_base * pointeur_
Detailed Description
Definition at line 28 of file Ref_Equation_base.h.
Constructor & Destructor Documentation
Ref_Equation_base::~Ref_Equation_base ()
Definition at line 25 of file Ref_Equation_base.cpp.
Ref_Equation_base::Ref_Equation_base ()
Definition at line 25 of file Ref_Equation_base.cpp.
Ref_Equation_base::Ref_Equation_base (const Equation_base & t)
Definition at line 25 of file Ref_Equation_base.cpp.
Ref_Equation_base::Ref_Equation_base (const Ref_Equation_base & t)
Definition at line 25 of file Ref_Equation_base.cpp.
Member Function Documentation
Objet_U * Ref_Equation_base::cree_instance () [static]
Definition at line 25 of file Ref_Equation_base.cpp.
int Ref_Equation_base::duplique () const [virtual]
Implements Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
const Type_info * Ref_Equation_base::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
const Type_info & Ref_Equation_base::get_info_ptr () const [virtual]
Implements O_U_Ptr.
Definition at line 25 of file Ref_Equation_base.cpp.
const Type_info * Ref_Equation_base::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
Ref_Equation_base::operator const Equation_base & () const
Definition at line 25 of file Ref_Equation_base.cpp.
Ref_Equation_base::operator Equation_base & ()
Definition at line 25 of file Ref_Equation_base.cpp.
const Equation_base * Ref_Equation_base::operator-> () const [inline]
Definition at line 28 of file Ref_Equation_base.h.
Equation_base * Ref_Equation_base::operator-> () [inline]
Definition at line 28 of file Ref_Equation_base.h.
const Ref_Equation_base & Ref_Equation_base::operator= (const Ref_Equation_base & t)
Definition at line 25 of file Ref_Equation_base.cpp.
const Ref_Equation_base & Ref_Equation_base::operator= (const Equation_base & t)
Definition at line 25 of file Ref_Equation_base.cpp.
Sortie & Ref_Equation_base::printOn (Sortie & os) const [protected, virtual]
Ecriture de l'Objet_U reference sur un flot de sortie.
Returns:
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
Entree & Ref_Equation_base::readOn (Entree & is) [protected, virtual]
Lecture dans un flot d'entree
A surcharger. Ne fait rien.
Returns:
Entree&
Signification: le flux d'entree non modifie
Contraintes:
Reimplemented from Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
const Ref_Equation_base & Ref_Equation_base::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
Ref_Equation_base & Ref_Equation_base::self_cast (Objet_U & r) [static]
Reimplemented from Ref_.
Definition at line 25 of file Ref_Equation_base.cpp.
void Ref_Equation_base::set_O_U_Ptr (Objet_U * ptr) [protected, virtual]
Fait pointer *this sur l'objet *ptr
L'adresse peut etre nulle (pointeur nul).
Reimplemented from O_U_Ptr.
Definition at line 25 of file Ref_Equation_base.cpp.
unsigned Ref_Equation_base::taille_memoire () const [virtual]
Implements Objet_U.
Definition at line 25 of file Ref_Equation_base.cpp.
const Equation_base & Ref_Equation_base::valeur () const [inline]
Definition at line 28 of file Ref_Equation_base.h.
Referenced by Terme_Source_Canal_RANS_LES_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Source_WC_Gravite_VEF::ajouter(), Source_QC_Gravite_VEF::ajouter(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Op_Dift_VDF_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_var_Elem::calculer_dt_stab(), Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab(), Op_Dift_VDF_Elem::calculer_dt_stab(), MorEqn::check_multiphase_compatibility(), Champ_Post_Operateur_Eqn::completer(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Mod_turb_hyd_base::equation(), Assembleur_P_VEFPreP1B::equation(), MorEqn::equation(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation(), Champ_Post_Operateur_Eqn::get_champ_without_evaluation(), Champ_Post_Operateur_Eqn::get_property(), Terme_Source_Th_TdivU_VEF_Face::modifier_zone_cl(), Sources::readOn(), Source_QC_QDM_Gen::readOn_spec(), Operateur_base::tester_contribuer_a_avec(), Operateur_Evanescence::typer(), Operateur_Div::typer(), Operateur_Diff::typer(), Operateur_Conv::typer(), Solveur_Masse::typer(), Champ_Post_Operateur_Eqn::verification_cas_compo(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
Equation_base & Ref_Equation_base::valeur () [inline]
Definition at line 28 of file Ref_Equation_base.h.
Member Data Documentation
const Type_info Ref_Equation_base::info_obj [static]
Reimplemented from Ref_.
Definition at line 28 of file Ref_Equation_base.h.
Equation_base* Ref_Equation_base::pointeur_ [private]
Definition at line 28 of file Ref_Equation_base.h.
The documentation for this class was generated from the following files:
src/Kernel/Framework/Ref_Equation_base.h
src/Kernel/Framework/Ref_Equation_base.cpp