TRUST: Op_Conv_EF_Stab_CoviMAC_Face Class Reference
Op_Conv_EF_Stab_CoviMAC_Face Class Reference
: class Op_Conv_EF_Stab_CoviMAC_Face
<Description of class Op_Conv_EF_Stab_CoviMAC_Face>
#include <Op_Conv_EF_Stab_CoviMAC_Face.h>
Public Member Functions
Op_Conv_EF_Stab_CoviMAC_Face ()
~Op_Conv_EF_Stab_CoviMAC_Face ()
unsigned taille_memoire () const
int duplique () const
const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
void completer ()
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
NE FAIT RIEN
A surcharger dans les classes derivees.
double calculer_dt_stab () const
Calcul dt_stab.
int has_interface_blocs () const
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void check_multiphase_compatibility () const
void set_incompressible (const int flag)
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static
Op_Conv_EF_Stab_CoviMAC_Face & self_cast (Objet_U &)
static const
Op_Conv_EF_Stab_CoviMAC_Face & self_cast (const Objet_U &)
methode ajoutee pour caster en python
Static Public Attributes
static const Type_info info_obj
Protected Member Functions
virtual Sortie & printOn (Sortie &x) const
NE FAIT RIEN
A surcharger dans les classes derivees.
virtual Entree & readOn (Entree &)
NE FAIT RIEN
A surcharger dans les classes derivees.
Protected Attributes
double alpha
DoubleVect porosite_f
DoubleVect porosite_e
Detailed Description
: class Op_Conv_EF_Stab_CoviMAC_Face
<Description of class Op_Conv_EF_Stab_CoviMAC_Face>
Definition at line 37 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
Constructor & Destructor Documentation
Op_Conv_EF_Stab_CoviMAC_Face::Op_Conv_EF_Stab_CoviMAC_Face ()
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
Op_Conv_EF_Stab_CoviMAC_Face::~Op_Conv_EF_Stab_CoviMAC_Face ()
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
Member Function Documentation
void Op_Conv_EF_Stab_CoviMAC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem) [virtual]
Reimplemented from Operateur_base.
double Op_Conv_EF_Stab_CoviMAC_Face::calculer_dt_stab () const [virtual]
Calcul dt_stab.
Returns:
double
Signification: renvoie toujours 1.e30
Contraintes:
Reimplemented from Operateur_base.
Definition at line 100 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
References IntTab::dimension(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_surfaces(), Zone_VF::face_voisins(), Champ_Face_CoviMAC::fcl(), Op_Conv_CoviMAC_base::la_zone_poly_, DoubleVect::line_size(), max(), min(), Process::mp_min(), Zone_dis_base::nb_elem(), Zone_VF::porosite_elem(), Zone_VF::porosite_face(), ref_cast, sub_type, valeur(), Ref_Zone_CoviMAC::valeur(), Op_Conv_CoviMAC_base::vitesse_, Zone_VF::volumes(), and Zone_VF::volumes_entrelaces().
{
  double dt = 1e10;
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  const Champ_Face_CoviMAC& ch = ref_cast(Champ_Face_CoviMAC, equation().inconnue().valeur());
  const DoubleVect& fs = zone.face_surfaces(), &pf = zone.porosite_face(), &ve = zone.volumes(), &pe = zone.porosite_elem(), &vf = zone.volumes_entrelaces();
  const DoubleTab& vit = vitesse_->valeurs(), &mu_f = ref_cast(Op_Grad_CoviMAC_Face, ref_cast(Navier_Stokes_std, equation()).operateur_gradient().valeur()).mu_f(),
                   *alp = sub_type(Pb_Multiphase, equation().probleme()) ? &ref_cast(Pb_Multiphase, equation().probleme()).eq_masse.inconnue().passe() : NULL;
  const IntTab& e_f = zone.elem_faces(), &f_e = zone.face_voisins(), &fcl = ch.fcl();
  int i, e, f, n, N = vit.line_size();
  DoubleTrav flux(N), vol(N); //somme des flux pf * |f| * vf, volume minimal des mailles d'elements/faces affectes par ce flux
  for (e = 0; e < zone.nb_elem(); e++)
    {
      for (vol = pe(e) * ve(e), flux = 0, i = 0; i < e_f.dimension(1) && (f = e_f(e, i)) >= 0; i++) for (n = 0; n < N; n++)
          {
            flux(n) += pf(f) * fs(f) * max((e == f_e(f, 1) ? 1 : -1) * vit(f, n), 0.); //seul le flux entrant dans e compte
            if (0 && fcl(f, 0) < 2) vol(n) = min(vol(n), pf(f) * vf(f) / mu_f(f, n, e != f_e(f, 0))); //prise en compte de la contribution aux faces
          }
      for (n = 0; n < N; n++) if ((!alp || (*alp)(e, n) > 1e-3) && flux(n)) dt = min(dt, vol(n) / flux(n));
    }
  return Process::mp_min(dt);
}
void Op_Conv_EF_Stab_CoviMAC_Face::check_multiphase_compatibility () const [inline, virtual]
Reimplemented from MorEqn.
Definition at line 55 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
{ }; //of course
void Op_Conv_EF_Stab_CoviMAC_Face::completer () [virtual]
Associe l'operateur a la zone_dis, la zone_Cl_dis,
et a l'inconnue de son equation.
< pour ajout _Mx (moment)
Reimplemented from Op_Conv_CoviMAC_base.
Definition at line 87 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
References Cerr, Joint::epaisseur(), Process::exit(), finl, Zone_CoviMAC::init_equiv(), Zone::joint(), Op_Conv_CoviMAC_base::la_zone_poly_, Zone::nb_joints(), porosite_e, Zone_VF::porosite_elem(), porosite_f, Zone_VF::porosite_face(), DoubleVect::ref(), Ref_Zone_CoviMAC::valeur(), and Zone_dis_base::zone().
{
  Op_Conv_CoviMAC_base::completer();
  /* au cas ou... */
  const Zone_CoviMAC& zone = la_zone_poly_.valeur();
  zone.init_equiv();
  if (zone.zone().nb_joints() && zone.zone().joint(0).epaisseur() < 2)
    Cerr << "Op_Conv_EF_Stab_CoviMAC_Face : largeur de joint insuffisante (minimum 2)!" << finl, Process::exit();
  porosite_f.ref(zone.porosite_face());
  porosite_e.ref(zone.porosite_elem());
}
Objet_U * Op_Conv_EF_Stab_CoviMAC_Face::cree_instance () [static]
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
void Op_Conv_EF_Stab_CoviMAC_Face::dimensionner_blocs (matrices_t matrices) [virtual]
Reimplemented from Operateur_base.
int Op_Conv_EF_Stab_CoviMAC_Face::duplique () const [virtual]
Implements Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
const Type_info * Op_Conv_EF_Stab_CoviMAC_Face::get_info () const [virtual]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
int Op_Conv_EF_Stab_CoviMAC_Face::has_interface_blocs () const [inline, virtual]
Reimplemented from Operateur_base.
Definition at line 48 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
  {
    return 1;
  };
const Type_info * Op_Conv_EF_Stab_CoviMAC_Face::info () [static]
Donne des informations sur le type de l'Objet_U.
Returns:
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
void Op_Conv_EF_Stab_CoviMAC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const [inline, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Reimplemented from Operateur_base.
Definition at line 44 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
{ };
Sortie & Op_Conv_EF_Stab_CoviMAC_Face::printOn (Sortie & os) const [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Sortie&
Signification: le flot de sortie
Contraintes:
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 46 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
{
  Op_Conv_CoviMAC_base::printOn( os );
  return os;
}
Entree & Op_Conv_EF_Stab_CoviMAC_Face::readOn (Entree & is) [protected, virtual]
NE FAIT RIEN
A surcharger dans les classes derivees.
Returns:
Entree&
Signification: le flot d'entree
Contraintes:
< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 64 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
References Param::ajouter(), alpha, Param::lire_avec_accolades_depuis(), and Objet_U::que_suis_je().
{
  Op_Conv_CoviMAC_base::readOn( is );
  Param param(que_suis_je());
  param.ajouter("alpha", &alpha);            //!< XD_ADD_P double parametre ajustant la stabilisation de 0 (schema centre) a 1 (schema amont)
  param.lire_avec_accolades_depuis(is);
  return is;
}
const Op_Conv_EF_Stab_CoviMAC_Face & Op_Conv_EF_Stab_CoviMAC_Face::self_cast (const Objet_U & obj) [static]
methode ajoutee pour caster en python
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
Op_Conv_EF_Stab_CoviMAC_Face & Op_Conv_EF_Stab_CoviMAC_Face::self_cast (Objet_U & r) [static]
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
void Op_Conv_EF_Stab_CoviMAC_Face::set_incompressible (const int flag) [inline, virtual]
Reimplemented from Operateur_Conv_base.
Definition at line 56 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
References Operateur_Conv_base::incompressible_.
  {
    incompressible_ = flag;
  }
unsigned Op_Conv_EF_Stab_CoviMAC_Face::taille_memoire () const [virtual]
Implements Objet_U.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 41 of file Op_Conv_EF_Stab_CoviMAC_Face.cpp.
Member Data Documentation
double Op_Conv_EF_Stab_CoviMAC_Face::alpha [protected]
Definition at line 62 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
Referenced by Op_Conv_Centre_CoviMAC_Face::readOn(), Op_Conv_Amont_CoviMAC_Face::readOn(), and readOn().
const Type_info Op_Conv_EF_Stab_CoviMAC_Face::info_obj [static]
Reimplemented from Op_Conv_CoviMAC_base.
Reimplemented in Op_Conv_Amont_CoviMAC_Face, and Op_Conv_Centre_CoviMAC_Face.
Definition at line 40 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
DoubleVect Op_Conv_EF_Stab_CoviMAC_Face::porosite_e [protected]
Definition at line 63 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
Referenced by completer().
DoubleVect Op_Conv_EF_Stab_CoviMAC_Face::porosite_f [protected]
Definition at line 63 of file Op_Conv_EF_Stab_CoviMAC_Face.h.
Referenced by completer().
The documentation for this class was generated from the following files:
src/CoviMAC/Operateurs/Op_Conv_EF_Stab_CoviMAC_Face.h
src/CoviMAC/Operateurs/Op_Conv_EF_Stab_CoviMAC_Face.cpp