TRUST: Source_Neutronique Class Reference
Source_Neutronique Class Reference abstract
class Source_Neutronique
Cette classe represente un terme source de l'equation de la thermique
du type puissance volumique issue de la neutronique.
La determination de la puissance s'effectue par resolution d'equations
differentielles regissant la cinetique neutronique.
.SECTION
voir aussi Terme_Puissance_Thermique
#include <Source_Neutronique.h>
Public Member Functions
Source_Neutronique ()
~Source_Neutronique () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
double rho (double, double)
const Nom & repartition () const
const Nom & nom_ssz () const
void faire_un_pas_de_temps_RK ()
void faire_un_pas_de_temps_EE ()
void aller_au_temps (double)
void mettre_a_jour (double temps) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void imprimer (double) const
virtual int limpr (double, double) const
double puissance_neutro () const
virtual double calculer_Tmoyenne ()=0
Public Member Functions inherited from Terme_Puissance_Thermique
void lire_donnees (Entree &, const Equation_base &eqn)
Lit le terme de puissance thermique a partir
d'un flot d'entree et d une equation pour eventuellement
acceder a la discretisation afin de typer la_puissance.
Lit uniquement un champ donne representant la_puissance.
void mettre_a_jour (double temps)
void modify_name_file (Nom &) const
const DoubleTab & puissance_thermique () const
void initialiser_champ_puissance (const Equation_base &eqn)
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static const Type_info * info ()
static Source_Neutronique & self_cast (Objet_U &)
static const Source_Neutronique & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Member Functions inherited from Source_base
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Member Functions
void mul (DoubleTab &m, DoubleVect &v, DoubleVect &resu)
void mettre_a_jour_matA (double t)
Private Attributes
int N
Nombre de groupe >= 1.
double Tvie
duree de vie d'un neutron
DoubleVect Un
DoubleVect Unp1
Inconnus a l'instant n et n+1 : Puissance Un(0) et Concentrations Un(i) du groupe i.
DoubleVect beta
beta(i) = nombre de neutrons retardees issue de l espece i,
double beta_som
somme des beta(i)
DoubleVect lambda
DoubleTab matA
matrice du systeme d'equa diff
double dt
pas de temps
int init
double P0
Puissance a t=0.
DoubleVect Ci0
Concentration a t=0.
int Ci0_ok
double dt_impr
double temps_courant
void(Source_Neutronique::* faire_un_pas_de_temps)(void)
double Tmoy
temperature moyenne
Parser_U fct_tT
Nom f_xyz
Nom n_ssz
Additional Inherited Members
Protected Attributes inherited from Terme_Puissance_Thermique
Champ_Don la_puissance_lu
Champ_Don la_puissance
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
class Source_Neutronique
Cette classe represente un terme source de l'equation de la thermique
du type puissance volumique issue de la neutronique.
La determination de la puissance s'effectue par resolution d'equations
differentielles regissant la cinetique neutronique.
.SECTION
voir aussi Terme_Puissance_Thermique
Definition at line 37 of file Source_Neutronique.h.
Constructor & Destructor Documentation
Source_Neutronique()
Source_Neutronique::Source_Neutronique ()
Definition at line 26 of file Source_Neutronique.cpp.
~Source_Neutronique()
Source_Neutronique::~Source_Neutronique () override
Definition at line 26 of file Source_Neutronique.cpp.
Member Function Documentation
aller_au_temps()
void Source_Neutronique::aller_au_temps (double temps)
Aller_au_temps : permet d'avancer avec le pas de temps de stabilite propre de l'equation.
Definition at line 339 of file Source_Neutronique.cpp.
{
  while (temps_courant<temps)
    {
      const double dt_stab = 0.8*Tvie/beta_som*std::max(std::fabs(rho(temps_courant,Tmoy)-1),1.);
      dt = std::min(dt_stab, temps-temps_courant);
      (this->*faire_un_pas_de_temps)();
      Un = Unp1;
      temps_courant += dt;
      mettre_a_jour_matA(temps_courant);
      if (limpr(temps_courant,dt)) imprimer(temps_courant);
    }
}
References beta_som, dt, faire_un_pas_de_temps, imprimer(), limpr(), mettre_a_jour_matA(), rho(), temps_courant, Tmoy, Tvie, Un, and Unp1.
Referenced by mettre_a_jour().
calculer_Tmoyenne()
virtual double Source_Neutronique::calculer_Tmoyenne () pure virtual
Implemented in Source_Neutronique_VDF.
Referenced by mettre_a_jour().
completer()
void Source_Neutronique::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Reimplemented in Source_Neutronique_VDF.
Definition at line 230 of file Source_Neutronique.cpp.
{
  Source_base::completer();
  Un.resize(N+1);
  Unp1.resize(N+1);
  matA.resize(N+1,N+1);
  matA = 0.;
  for (int i=1; i<N+1; i++)
    {
      matA(0,i) = lambda(i-1);
      matA(i,i) = -lambda(i-1);
      matA(i,0) = beta(i-1)/Tvie;
    }
  Un(0) = P0;
  if (Ci0_ok == 0)
    for (int i=1; i<N+1; i++)
      Un(i) = beta(i-1)*Un(0)/Tvie/lambda(i-1);
  else
    for (int i=1; i<N+1; i++)
      Un(i) = Ci0(i-1);
}
References beta, Ci0, Ci0_ok, Source_base::completer(), lambda, matA, N, P0, TRUSTTab< _TYPE_ >::resize(), TRUSTVect< _TYPE_ >::resize(), Tvie, Un, and Unp1.
Referenced by Source_Neutronique_VDF::completer().
faire_un_pas_de_temps_EE()
void Source_Neutronique::faire_un_pas_de_temps_EE ()
Schema Euler explicite
Definition at line 325 of file Source_Neutronique.cpp.
{
  mul(matA,Un, Unp1);
  Unp1*=dt;
  Unp1 += Un;
  /* Cout << "matA " << matA << finl;
     Cout << "Un " << Un << finl;
     Cout << "Unp1 " << Unp1 << finl;
  */
}
References dt, matA, mul(), Un, and Unp1.
Referenced by readOn().
faire_un_pas_de_temps_RK()
void Source_Neutronique::faire_un_pas_de_temps_RK ()
Schema de Runge Kutta classique
Definition at line 273 of file Source_Neutronique.cpp.
{
  static const double a1 = 1./6.;
  static const double a2 = 1./3.;
  DoubleVect fn1(Un);
  DoubleVect fn2(Un);
  DoubleVect fn3(Un);
  DoubleVect fn4(Un);
  const double dt2 = dt/2.;
// Un1 = Un+dt/2*f(tn,un)
  mul(matA,Un, fn1);
  Unp1 = Un;
  Unp1.ajoute(dt2, fn1);
// Un2 = Un+dt/2*f(tn+dt/2,Un1)
  mettre_a_jour_matA(temps_courant+dt2);
  mul(matA,Unp1, fn2);
  Unp1 = Un;
  Unp1.ajoute(dt2, fn2);
// Un3 = Un+dt*f(tn+dt/2,Un2)
  mul(matA,Unp1, fn3);
  Unp1 = Un;
  Unp1.ajoute(dt, fn3);
// Un+1 = Un+dt*(a1*f(tn,un) + a2*f(tn+dt/2,Un1) + a2*f(tn+dt/2,Un2) + a1*f(tn+dt/2,Un3))
  mettre_a_jour_matA(temps_courant+dt);
  mul(matA,Unp1, fn4);
  Unp1 = Un;
  Unp1.ajoute(a1*dt, fn4);
  Unp1.ajoute(a2*dt, fn3);
  Unp1.ajoute(a2*dt, fn2);
  Unp1.ajoute(a1*dt, fn1);
}
References TRUSTVect< _TYPE_ >::ajoute(), dt, matA, mettre_a_jour_matA(), mul(), temps_courant, Un, and Unp1.
Referenced by readOn().
get_info()
const Type_info * Source_Neutronique::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_Neutronique_VDF.
Definition at line 26 of file Source_Neutronique.cpp.
imprimer()
void Source_Neutronique::imprimer (double temps) const virtual
Imprime les resultats dans le fichier puissance.dat
Definition at line 357 of file Source_Neutronique.cpp.
{
  SFichier fic("puissances.dat",ios::app);
  fic << temps ;
  for (int i =0; i<N+1; i++)
    {
      fic << " " << Un(i);
    }
  fic << finl;
  /*Cout << "Impression du pas de temps pour l'equation de la cinetique point " << finl;
    Cout << ">>>> Pas de temps utilise dt = " << dt << finl;
    Cout << ">>>> Pas de temps de stabilite dt_stab = " << dt_stab << finl;
  */
}
References finl, N, and Un.
Referenced by aller_au_temps().
info()
const Type_info * Source_Neutronique::info () static
Definition at line 26 of file Source_Neutronique.cpp.
limpr()
int Source_Neutronique::limpr (double le_temps_courant, double ddt) const virtual
Definition at line 374 of file Source_Neutronique.cpp.
{
  static const double epsilon = 1.e-9;
  const Schema_Temps_base& sch = mon_equation->schema_temps();
// Si impression a chaque pas de temps, alors que pas demande, faire comme limpr() de Echange_contact_Correlation_VDF.cpp
  if (sch.nb_pas_dt()==0)
    return 0;
  if (dt_impr<=ddt || ((sch.temps_final_atteint() || sch.nb_pas_dt_max_atteint() || sch.nb_pas_dt()<=1 || sch.stationnaire_atteint()) && dt_impr!=1e10))
    return 1;
  else
    {
// Voir Schema_Temps_base::limpr pour information sur epsilon et modf
      double i, j;
      modf(le_temps_courant/dt_impr + epsilon, &i);
      modf((le_temps_courant-ddt)/dt_impr + epsilon, &j);
      return ( i>j );
    }
}
References dt_impr, MorEqn::mon_equation, Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max_atteint(), Equation_base::schema_temps(), Schema_Temps_base::stationnaire_atteint(), and Schema_Temps_base::temps_final_atteint().
Referenced by aller_au_temps().
mettre_a_jour()
void Source_Neutronique::mettre_a_jour (double temps) override virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Reimplemented from Source_base.
Definition at line 394 of file Source_Neutronique.cpp.
{
  if (init)
    {
      init = 0;
      Tmoy = calculer_Tmoyenne();
      temps_courant = temps;
      mettre_a_jour_matA(temps);
      la_puissance(0) = Un(0);
    }
  else
    {
      Tmoy = calculer_Tmoyenne();
      aller_au_temps(temps);
      temps_courant = temps;
      la_puissance(0) = Un(0);
    }
}
References aller_au_temps(), calculer_Tmoyenne(), init, Terme_Puissance_Thermique::la_puissance, mettre_a_jour_matA(), temps_courant, Tmoy, and Un.
mettre_a_jour_matA()
void Source_Neutronique::mettre_a_jour_matA (double temps) private
Met a jour les coefficients de la matrice A
Definition at line 315 of file Source_Neutronique.cpp.
{
  matA(0,0) = beta_som/Tvie*(rho(temps,Tmoy)-1);
}
References beta_som, matA, rho(), Tmoy, and Tvie.
Referenced by aller_au_temps(), faire_un_pas_de_temps_RK(), and mettre_a_jour().
mul()
void Source_Neutronique::mul (DoubleTab & m, DoubleVect & v, DoubleVect & resu) private
Effectue resu = m*v
Definition at line 258 of file Source_Neutronique.cpp.
{
  resu = 0.;
  resu(0) = m(0,0)*v(0);
  for (int i=1; i<N+1; i++)
    {
      resu(0)+= m(0,i)*v(i);
      resu(i) = m(i,0)*v(0) + m(i,i)*v(i);
    }
}
References N.
Referenced by faire_un_pas_de_temps_EE(), and faire_un_pas_de_temps_RK().
nom_ssz()
const Nom & Source_Neutronique::nom_ssz () const
Renvoie le nom de la sous zone de degagement de puissance
Definition at line 224 of file Source_Neutronique.cpp.
{
  return n_ssz;
}
References n_ssz.
Referenced by Source_Neutronique_VDF::associer_pb().
printOn()
Sortie & Source_Neutronique::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_Neutronique_VDF.
Definition at line 31 of file Source_Neutronique.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
puissance_neutro()
double Source_Neutronique::puissance_neutro () const inline
Definition at line 54 of file Source_Neutronique.h.
  {
    return Un(0);
  }
References Un.
readOn()
Entree & Source_Neutronique::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Reimplemented in Source_Neutronique_VDF.
Definition at line 38 of file Source_Neutronique.cpp.
{
  Motcles les_mots(11);
  {
    les_mots[0] = "N";
    les_mots[1] = "lambda";
    les_mots[2] = "Tvie";
    les_mots[3] = "beta";
    les_mots[4] = "rho_cte";
    les_mots[5] = "P0";
    les_mots[6] = "dt_impr";
    les_mots[7] = "schema_temps";
    les_mots[8] = "rho";
    les_mots[9] = "repartition";
    les_mots[10] = "Ci0";
  }
  EChaine ec("Champ_Uniforme 1 1");
  ec >> la_puissance;
  Ci0_ok=0;
  f_xyz = "1.";
  n_ssz="defaut";
  N = -1;
  init = 1;
  dt_impr = 1e10;
  faire_un_pas_de_temps =  &Source_Neutronique::faire_un_pas_de_temps_RK;
  Motcle motlu, accolade_fermee="}", accolade_ouverte="{";
  is >> motlu;
  if(motlu!=accolade_ouverte)
    {
      Cerr << "On attendait une { a la lecture d'une " << que_suis_je() << finl;
      Cerr << "et non : " << motlu << finl;
      exit();
    }
  is >> motlu;
  while (motlu != accolade_fermee)
    {
      int rang=les_mots.search(motlu);
      switch(rang)
        {
        case 0 :
          {
            is >> N;
            if (N<1)
              {
                Cerr << "Le nombre de groupes doit etre >=1 dans  " << que_suis_je() << finl;
                exit();
              }
            break;
          }
        case 1 :
          {
            if (N<1)
              {
                Cerr << "Il faut rentrer le nb de groupes N avant lambda dans  " << que_suis_je() << finl;
                exit();
              }
            lambda.resize(N);
            for (int i=0; i<N; i++) is>>lambda(i);
            break;
          }
        case 2 :
          {
            is >> Tvie;
            break;
          }
        case 3 :
          {
            if (N<1)
              {
                Cerr << "Il faut rentrer le nb de groupes N avant beta dans  " << que_suis_je() << finl;
                exit();
              }
            beta.resize(N);
            beta_som=0.;
            for (int i=0; i<N; i++)
              {
                is>>beta(i);
                beta_som+=beta(i);
              }
            break;
          }
        case 5 :
          {
            is >> P0;
            break;
          }
        case 6 :
          {
            is >> dt_impr;
            break;
          }
        case 7 :
          {
            Motcle nom_sch;
            is >> nom_sch;
            if (nom_sch == "euler_explicite")
              {
                faire_un_pas_de_temps =  &Source_Neutronique::faire_un_pas_de_temps_EE;
              }
            else if (nom_sch == "runge_kutta")
              {
                faire_un_pas_de_temps =  &Source_Neutronique::faire_un_pas_de_temps_RK;
              }
            else
              {
                Cerr << "On ne comprend le mot : " << motlu << "dans " << que_suis_je() << finl;
                exit();
              }
            break;
          }
        case 8 :
          {
            Nom tmp;
            is >> tmp;
            Cerr << "Lecture de la reactivite " << tmp << finl;
            fct_tT.setNbVar(2);
            fct_tT.setString(tmp);
            fct_tT.addVar("t");
            fct_tT.addVar("T");
            fct_tT.parseString();
            break;
          }
        case 9 :
          {
            is >> f_xyz;
            is >> n_ssz;
            break;
          }
        case 10 :
          {
            if (N<1)
              {
                Cerr << "Il faut rentrer le nb de groupes N avant les Ci initiaux dans  " << que_suis_je() << finl;
                exit();
              }
            Ci0_ok = 1;
            Ci0.resize(N);
            for (int i=0; i<N; i++)
              {
                is>>Ci0(i);
              }
            break;
          }
        default :
          {
            Cerr << "On ne comprend le mot : " << motlu << "dans " << que_suis_je() << finl;
            exit();
          }
        }
      is >> motlu;
    }
  if (N<1)
    {
      Cerr << "Il faut rentrer le nb de groupes N  dans  " << que_suis_je() << finl;
      exit();
    }
  return is;
}
References Parser_U::addVar(), beta, beta_som, Cerr, Ci0, Ci0_ok, dt_impr, Process::exit(), f_xyz, faire_un_pas_de_temps, faire_un_pas_de_temps_EE(), faire_un_pas_de_temps_RK(), fct_tT, finl, init, Terme_Puissance_Thermique::la_puissance, lambda, N, n_ssz, P0, Parser_U::parseString(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_ >::resize(), Motcles::search(), Parser_U::setNbVar(), Parser_U::setString(), and Tvie.
Referenced by Source_Neutronique_VDF::readOn().
repartition()
const Nom & Source_Neutronique::repartition () const
Renvoie la chaine de caracere representant la fonction de repartition f(x,y,z) de la puissance
Definition at line 216 of file Source_Neutronique.cpp.
{
  return f_xyz;
}
References f_xyz.
Referenced by Source_Neutronique_VDF::associer_pb().
rho()
double Source_Neutronique::rho (double t, double T)
Definition at line 205 of file Source_Neutronique.cpp.
{
  fct_tT.setVar("t",t);
  fct_tT.setVar("T",T);
  return fct_tT.eval();
}
References Parser_U::eval(), fct_tT, and Parser_U::setVar().
Referenced by aller_au_temps(), and mettre_a_jour_matA().
self_cast() [1/2]
const Source_Neutronique & Source_Neutronique::self_cast (const Objet_U & r) static
Definition at line 26 of file Source_Neutronique.cpp.
self_cast() [2/2]
Source_Neutronique & Source_Neutronique::self_cast (Objet_U & r) static
Definition at line 26 of file Source_Neutronique.cpp.
Member Data Documentation
beta
DoubleVect Source_Neutronique::beta private
beta(i) = nombre de neutrons retardees issue de l espece i,
Definition at line 66 of file Source_Neutronique.h.
Referenced by completer(), and readOn().
beta_som
double Source_Neutronique::beta_som private
somme des beta(i)
Definition at line 67 of file Source_Neutronique.h.
Referenced by aller_au_temps(), mettre_a_jour_matA(), and readOn().
Ci0
DoubleVect Source_Neutronique::Ci0 private
Concentration a t=0.
Definition at line 73 of file Source_Neutronique.h.
Referenced by completer(), and readOn().
Ci0_ok
int Source_Neutronique::Ci0_ok private
Definition at line 74 of file Source_Neutronique.h.
Referenced by completer(), and readOn().
dt
double Source_Neutronique::dt private
pas de temps
Definition at line 70 of file Source_Neutronique.h.
Referenced by aller_au_temps(), faire_un_pas_de_temps_EE(), and faire_un_pas_de_temps_RK().
dt_impr
double Source_Neutronique::dt_impr private
Definition at line 75 of file Source_Neutronique.h.
Referenced by limpr(), and readOn().
f_xyz
Nom Source_Neutronique::f_xyz private
Definition at line 81 of file Source_Neutronique.h.
Referenced by readOn(), and repartition().
faire_un_pas_de_temps
void(Source_Neutronique::* Source_Neutronique::faire_un_pas_de_temps) (void) private
Definition at line 77 of file Source_Neutronique.h.
Referenced by aller_au_temps(), and readOn().
fct_tT
Parser_U Source_Neutronique::fct_tT private
Definition at line 80 of file Source_Neutronique.h.
Referenced by readOn(), and rho().
info_obj
const Type_info Source_Neutronique::info_obj static
Definition at line 39 of file Source_Neutronique.h.
init
int Source_Neutronique::init private
Definition at line 71 of file Source_Neutronique.h.
Referenced by mettre_a_jour(), and readOn().
lambda
DoubleVect Source_Neutronique::lambda private
Definition at line 68 of file Source_Neutronique.h.
Referenced by completer(), and readOn().
matA
DoubleTab Source_Neutronique::matA private
matrice du systeme d'equa diff
Definition at line 69 of file Source_Neutronique.h.
Referenced by completer(), faire_un_pas_de_temps_EE(), faire_un_pas_de_temps_RK(), and mettre_a_jour_matA().
N
int Source_Neutronique::N private
Nombre de groupe >= 1.
Definition at line 63 of file Source_Neutronique.h.
Referenced by completer(), imprimer(), mul(), and readOn().
n_ssz
Nom Source_Neutronique::n_ssz private
Definition at line 82 of file Source_Neutronique.h.
Referenced by nom_ssz(), and readOn().
P0
double Source_Neutronique::P0 private
Puissance a t=0.
Definition at line 72 of file Source_Neutronique.h.
Referenced by completer(), and readOn().
temps_courant
double Source_Neutronique::temps_courant private
Definition at line 76 of file Source_Neutronique.h.
Referenced by aller_au_temps(), faire_un_pas_de_temps_RK(), and mettre_a_jour().
Tmoy
double Source_Neutronique::Tmoy private
temperature moyenne
Definition at line 78 of file Source_Neutronique.h.
Referenced by aller_au_temps(), mettre_a_jour(), and mettre_a_jour_matA().
Tvie
double Source_Neutronique::Tvie private
duree de vie d'un neutron
Definition at line 64 of file Source_Neutronique.h.
Referenced by aller_au_temps(), completer(), mettre_a_jour_matA(), and readOn().
Un
DoubleVect Source_Neutronique::Un private
Definition at line 65 of file Source_Neutronique.h.
Referenced by aller_au_temps(), completer(), faire_un_pas_de_temps_EE(), faire_un_pas_de_temps_RK(), imprimer(), mettre_a_jour(), and puissance_neutro().
Unp1
DoubleVect Source_Neutronique::Unp1 private
Inconnus a l'instant n et n+1 : Puissance Un(0) et Concentrations Un(i) du groupe i.
Definition at line 65 of file Source_Neutronique.h.
Referenced by aller_au_temps(), completer(), faire_un_pas_de_temps_EE(), and faire_un_pas_de_temps_RK().
The documentation for this class was generated from the following files:
src/ThSol/Source_Neutronique.h
src/ThSol/Source_Neutronique.cpp