TRUST: Zone_Cl_VDF Class Reference
Zone_Cl_VDF Class Reference
< namespace TypeAreteCoinVDF
#include <Zone_Cl_VDF.h>
Public Member Functions
Zone_Cl_VDF ()
~Zone_Cl_VDF ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void associer (const Zone_VDF &)
int num_Cl_face (int) const
const Cond_lim & la_cl_de_la_face (int) const override
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
int type_arete_bord (int) const
const IntVect & type_arete_bord () const
const int & type_arete_coin (int) const
const IntVect & type_arete_coin () const
void completer (const Zone_dis &) override
void imposer_cond_lim (Champ_Inc &, double) override
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
int nb_faces_sortie_libre () const
Zone_VDF & zone_VDF ()
const Zone_VDF & zone_VDF () const
int nb_faces_bord () const
Public Member Functions inherited from Zone_Cl_dis_base
Zone_Cl_dis_base ()
~Zone_Cl_dis_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
void nommer (const Nom &nom) override
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const Cond_lim & les_conditions_limites (int) const
Renvoie la i-ieme condition aux limites.
(version const)
Cond_lim & les_conditions_limites (int)
Renvoie la i-ieme condition aux limites.
Conds_lim & les_conditions_limites ()
Renvoie le tableaux des conditions aux limites.
const Conds_lim & les_conditions_limites () const
Renvoie le tableaux des conditions aux limites.
(version const)
int nb_cond_lim () const
Renvoie le nombre de conditions aux limites.
virtual void mettre_a_jour (double temps)
Effectue une mise a jour en temps de toutes les conditions
aux limites.
virtual void mettre_a_jour_ss_pas_dt (double temps)
Effectue une mise a jour pour des sous pas de temps
d'un schema en temps (par exemple dans RungeKutta)
pour toutes les Cond Lims renvoyant 1 par le biais de la methode
int Cond_Lim_base::a_mettre_a_jour_ss_pas_dt();.
void completer ()
Appel Cond_lim_base::completer() sur chaque
condition aux limites.
int contient_Cl (const Nom &)
Renvoie 1 si l'objet contient une condition aux limites
du Nom specifie.
Renvoie 0 sinon.
Zone_dis & zone_dis ()
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
const Zone_dis & zone_dis () const
Renvoie une reference sur la zone discretisee associee aux conditions
aux limites. Cette Zone_dis est associee au travers de l'equation
associee et pas directement a l'objet Zone_Cl_dis_base.
(version const)
Zone & zone ()
const Zone & zone () const
virtual int calculer_coeffs_echange (double temps)
Calcul des coefficients d'echange pour les problemes couples thermiques.
virtual void imposer_cond_lim (Champ_Inc &, double)=0
int nb_faces_Cl () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
void changer_temps_futur (double temps, int i)
Change le i-eme temps futur de toutes les CLs.
void Gpoint (double t1, double t2)
void set_temps_defaut (double temps)
Change le i-eme temps futur de toutes les CLs.
int avancer (double temps)
Tourne la roue des CLs jusqu'au temps donne.
int reculer (double temps)
Tourne la roue des CLsj usqu'au temps donne.
virtual int initialiser (double temps)
Initialise les CLs
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des CLs ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
const Nom & le_nom () const override
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
virtual void associer_inconnue (const Champ_Inc &)
virtual const Champ_Inc & inconnue () const
virtual Champ_Inc & inconnue ()
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Zone_Cl_VDF & self_cast (Objet_U &)
static const Zone_Cl_VDF & self_cast (const Objet_U &)
Static Public Member Functions inherited from Zone_Cl_dis_base
static const Type_info * info ()
static Zone_Cl_dis_base & self_cast (Objet_U &)
static const Zone_Cl_dis_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Zone_Cl_dis_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Sortie & printOn (Sortie &x) const override
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Entree & readOn (Entree &) override
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
virtual void completer (const Zone_dis &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Private Attributes
IntVect type_arete_bord_
type des aretes bord: type = 0 si l'arete separe deux faces de paroi type = 1 si l'arete separe deux faces "fluide" type = 2 si l'arete separe une face de paroi et une face "fluide" type = 3 si l'arete separe deux faces de symetrie type = 5 si l'arete separe une face de symetrie et une face de paroi type = 6 si l'arete separe une face de symetrie et une face "fluide"
IntVect type_arete_coin_
type des aretes coin: type = 0 si l'arete contient deux faces de periodicite type = 1 si l'arete contient une face de periodicite et une face de paroi
IntVect num_Cl_face_
pour chaque face de bord numero de la condition limite a laquelle elle se rattache
Additional Inherited Members
Protected Attributes inherited from Zone_Cl_dis_base
Nom nom_
Conds_lim les_conditions_limites_
Ref_Champ_Inc mon_inconnue
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Detailed Description
< namespace TypeAreteCoinVDF
Definition at line 73 of file Zone_Cl_VDF.h.
Constructor & Destructor Documentation
Zone_Cl_VDF()
Zone_Cl_VDF::Zone_Cl_VDF ()
Definition at line 31 of file Zone_Cl_VDF.cpp.
~Zone_Cl_VDF()
Zone_Cl_VDF::~Zone_Cl_VDF ()
Definition at line 31 of file Zone_Cl_VDF.cpp.
Member Function Documentation
associer()
void Zone_Cl_VDF::associer (const Zone_VDF & zone_vdf)
Definition at line 58 of file Zone_Cl_VDF.cpp.
{
  type_arete_bord_.resize(zone_vdf.nb_aretes_bord());
  type_arete_coin_.resize(zone_vdf.nb_aretes_coin());
  num_Cl_face_.resize(zone_vdf.nb_faces_bord());
}
References Zone_VDF::nb_aretes_bord(), Zone_VDF::nb_aretes_coin(), Zone_VF::nb_faces_bord(), num_Cl_face_, TRUSTVect< _TYPE_ >::resize(), type_arete_bord_, and type_arete_coin_.
Referenced by VDF_discretisation::zone_Cl_dis().
completer()
void Zone_Cl_VDF::completer (const Zone_dis & une_zone_dis) override virtual
< face de periodicite
< face de periodicite
< face de paroi
< Sortie libre ou entree de fluide
< face de paroi
< face de periodicite
< face de paroi
< face de fluide
< face sortie libre ou entree de fluide
< face symetrie
< face paroi
< face sortie libre ou entree de fluide
< face periodique
< face symetrie
< face paroi
< face sortie libre ou entree de fluide
< symetrie
< periodicite
Implements Zone_Cl_dis_base.
Definition at line 65 of file Zone_Cl_VDF.cpp.
{
  Cerr << "Zone_Cl_VDF::completer ..." << finl;
  if (sub_type(Zone_VDF,une_zone_dis.valeur()))
    {
      const Zone_VDF& la_zone_VDF = ref_cast(Zone_VDF,une_zone_dis.valeur());
// Remplissage du tableau d'entiers type_arete_bord_
// tableau intermediaire : les_faces_Cl
// On remplit le tableau d'entiers local les_faces_Cl qui
// donne la condition aux limites pour chaque face de bord
// avec les conventions suivantes :
// 0 pour une condition de paroi
// 1 pour une condition d'entree ou de sortie de fluide (face "fluide")
// 2 pour une condition de symetrie
// 3 pour une condition de periodicite
// 0 pour toute autre Cl.
// On ne considere que les conditions aux limites qui interviennent pour
// la quantite de mouvement
      int nb_aretes_bord = la_zone_VDF.nb_aretes_bord();
      IntVect les_faces_Cl;
      la_zone_VDF.creer_tableau_faces_bord(les_faces_Cl);
// Boucle sur les conditions aux limites pour remplir les_faces_Cl:
      for (int n_bord=0; n_bord<la_zone_VDF.nb_front_Cl(); n_bord++)
        {
// pour chaque Condition Limite on regarde son type
          const Cond_lim_base& la_cl = les_conditions_limites_[n_bord].valeur();
          int numero_cl = 0;
          if ( (sub_type(Dirichlet_paroi_fixe,la_cl)) ||
               (sub_type(Dirichlet_paroi_defilante,la_cl)) )
            numero_cl = 0;
          else if ( (sub_type(Dirichlet_entree_fluide,la_cl)) ||
                    (sub_type(Neumann_sortie_libre,la_cl)) )
            numero_cl = 1;
          else if (sub_type(Symetrie,la_cl))
            numero_cl = 2;
          else if (sub_type(Periodique,la_cl))
            numero_cl = 3;
          const Frontiere& fr = la_cl.frontiere_dis().frontiere();
          const int ndeb = fr.num_premiere_face();
          const int nfin = ndeb + fr.nb_faces();
          for (int i=ndeb; i<nfin; i++)
            {
              les_faces_Cl[i] = numero_cl;
              num_Cl_face_[i] = n_bord;
            }
        }
      les_faces_Cl.echange_espace_virtuel();
// Boucle sur les aretes bord pour remplir type_arete_bord_
      int face1,face2;
      int rang1,rang2;
      type_arete_bord_= TypeAreteBordVDF::VIDE;
      int ndeb = la_zone_VDF.premiere_arete_bord();
      int nfin = ndeb + nb_aretes_bord;
      int num_arete_;
      int decal_virt = la_zone_VDF.nb_faces();
      int sz_faces_Cl = les_faces_Cl.size_reelle();
      const ArrOfInt& ind_faces_virt_bord = la_zone_VDF.zone().ind_faces_virt_bord();
      int num_arete;
      for ( num_arete=ndeb; num_arete<nfin; num_arete++)
        {
          num_arete_=num_arete-ndeb;
          face1 = la_zone_VDF.Qdm(num_arete,0);
          face2 = la_zone_VDF.Qdm(num_arete,1);
          rang1 = face1;
          rang2 = face2;
          if(rang1>=sz_faces_Cl) rang1=ind_faces_virt_bord[rang1-decal_virt];
          if(rang2>=sz_faces_Cl) rang2=ind_faces_virt_bord[rang2-decal_virt];
          if (les_faces_Cl[rang1] == 0)
            {
              if (les_faces_Cl[rang2] == 0)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::PAROI_PAROI;
              else if (les_faces_Cl[rang2] == 1)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::PAROI_FLUIDE;
              else if (les_faces_Cl[rang2] == 2)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::PAROI_SYM;
              else
                {
                  Cerr << "On traite une arete qui separe deux faces de meme orientation : " << finl;
                  Cerr << "l'une de ces faces porte une condition limite de type paroi " << finl;
                  Cerr << "et l'autre porte une condition de type Periodicite" << finl;
                  Cerr << "TRUST ne sait pas traiter cette situation" << finl;
                  Process::Journal()<<"ERREUR Faces_CL"<<finl;
                  Process::Journal()<<"face1:"<<face1<<" , face2:"<<face2<<finl;
                  Process::Journal()<<"rang1:"<<rang1<<" , rang2:"<<rang2<<finl;
                  Process::Journal()<<"les_faces_Cl[rang1]:"<<les_faces_Cl[rang1]<<" , les_faces_Cl[rang2]:"<<les_faces_Cl[rang2]<<finl;
                  assert(0);
                  exit();
                }
            }
          else if (les_faces_Cl[rang1] == 1)
            {
              if (les_faces_Cl[rang2] == 0)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::PAROI_FLUIDE;
              else if (les_faces_Cl[rang2] == 1)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::FLUIDE_FLUIDE;
              else if (les_faces_Cl[rang2] == 2)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::FLUIDE_SYM;
              else
                {
                  Cerr << "On traite une arete qui separe deux faces de meme orientation : " << finl;
                  Cerr << "l'une de ces faces porte une condition limite de type frontiere fluide " << finl;
                  Cerr << "et l'autre porte une condition de type  Periodicite" << finl;
                  Cerr << "TRUST ne sait pas traiter cette situation" << finl;
                  exit();
                }
            }
          else if (les_faces_Cl[rang1] == 2)
            {
              if (les_faces_Cl[rang2] == 0)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::PAROI_SYM;
              else if (les_faces_Cl[rang2] == 1)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::FLUIDE_SYM;
              else if (les_faces_Cl[rang2] == 2)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::SYM_SYM;
              else
                {
                  Cerr << "On traite une arete qui separe deux faces de meme orientation : " << finl;
                  Cerr << "l'une de ces faces porte une condition limite de type Symetrie " << finl;
                  Cerr << "et l'autre porte une condition de type Periodicite" << finl;
                  Cerr << "TRUST ne sait pas traiter cette situation" << finl;
                  exit();
                }
            }
          else if (les_faces_Cl[rang1] == 3)
            {
              if (les_faces_Cl[rang2] == 3)
                type_arete_bord_[num_arete_] = TypeAreteBordVDF::PERIO_PERIO;
              else
                {
                  Cerr << "On traite une arete qui separe deux faces de meme orientation : " << finl;
                  Cerr << "l'une de ces faces porte une condition limite de type Periodicite " << finl;
                  Cerr << "et l'autre porte une condition d'un autre type" << finl;
                  Cerr << "TRUST ne sait pas traiter cette situation" << finl;
                  exit();
                }
            }
        }
// MODIFS CA : 21/09/99
// Boucle sur les aretes coin pour remplir type_arete_coin_
      type_arete_coin_= TypeAreteCoinVDF::VIDE;
      ndeb = la_zone_VDF.premiere_arete_coin();
      nfin = ndeb + la_zone_VDF.nb_aretes_coin();
      int fac1,fac2,fac3,fac4;
      for (num_arete=ndeb; num_arete<nfin; num_arete++)
        {
          num_arete_=num_arete-ndeb;
// On cherche les 2 valeurs differentes de -1
          fac1 = la_zone_VDF.Qdm(num_arete_,0);
          fac2 = la_zone_VDF.Qdm(num_arete_,1);
          fac3 = la_zone_VDF.Qdm(num_arete_,2);
          fac4 = la_zone_VDF.Qdm(num_arete_,3);
          IntVect f(2);
          f = -2;
          int i=0;
          if (fac1 != -1)
            {
              f(i) = fac1;
              i++;
            }
          if (fac2 != -1)
            {
              f(i) = fac2;
              i++;
            }
          if (fac3 != -1)
            {
              f(i) = fac3;
              i++;
            }
          if (fac4 != -1)
            {
              f(i) = fac4;
              i++;
            }
          rang1 = f(0);
          rang2 = f(1);
          if(rang1>=sz_faces_Cl) rang1-=decal_virt;
          if(rang2>=sz_faces_Cl) rang2-=decal_virt;
          if (les_faces_Cl[rang1] == 3) //!< face de periodicite
            {
              if (les_faces_Cl[rang2] == 3)  //!< face de periodicite
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PERIO_PERIO;
              else if (les_faces_Cl[rang2] == 0) //!< face de paroi
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PERIO_PAROI;
              else if (les_faces_Cl[rang2] == 1) //!< Sortie libre ou entree de fluide
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PERIO_FLUIDE;
              else
                {
                  Cerr << "On traite une arete qui separe deux faces dans un coin : " << finl;
                  Cerr << "l'une de ces faces porte une condition limite de type periodicite " << finl;
                  Cerr << "et l'autre porte une condition autre que periodicite ou paroi" << finl;
                  Cerr << "On n a pas encore fait la modif!!!" << finl;
// exit();
                }
            }
          else if (les_faces_Cl[rang1] == 0)  //!< face de paroi
            {
              if (les_faces_Cl[rang2] == 3)   //!< face de periodicite
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PERIO_PAROI;
              else if (les_faces_Cl[rang2] == 0) //!< face de paroi
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PAROI_PAROI;
              else if (les_faces_Cl[rang2] == 1)   //!< face de fluide
                {
                  if (Option_VDF::traitement_coins)
                    type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PAROI_FLUIDE;
                  else
                    /* {
                      Cerr << "On traite une arete qui separe deux faces dans un coin : " << finl;
                      Cerr << "l'une de ces faces porte une condition limite de type paroi " << finl;
                      Cerr << "et l'autre porte une condition autre que periodicite" << finl;
                      Cerr << "On n a pas encore fait la modif!!!" << finl;
                    } */
// On ne change rien. De toute facon, ce type d'arete ne necessite pas de traitement particulier
                    type_arete_coin_[num_arete_] = TypeAreteCoinVDF::VIDE;
                }
            }
          else if (les_faces_Cl[rang1] == 1)  //!< face sortie libre ou entree de fluide
            {
              if (les_faces_Cl[rang2] == 2)  //!< face symetrie
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::FLUIDE_SYM;
              else if (les_faces_Cl[rang2] == 0) //!< face paroi
                {
                  if (Option_VDF::traitement_coins)
                    type_arete_coin_[num_arete_] = TypeAreteCoinVDF::FLUIDE_PAROI;
                  else
// On ne change rien. De toute facon, ce type d'arete ne necessite pas de traitement particulier
                    type_arete_coin_[num_arete_] = TypeAreteCoinVDF::VIDE;
                }
              else if (les_faces_Cl[rang2] == 1) //!< face sortie libre ou entree de fluide
                {
                  if (Option_VDF::traitement_coins)
                    type_arete_coin_[num_arete_] = TypeAreteCoinVDF::FLUIDE_FLUIDE;
                  else
// On ne change rien. De toute facon, ce type d'arete ne necessite pas de traitement particulier
                    type_arete_coin_[num_arete_] = TypeAreteCoinVDF::VIDE;
                }
// Modif AC : 27/02/03
              else if (les_faces_Cl[rang2] == 3) //!< face periodique
                {
                  type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PERIO_FLUIDE;
                }
// Fin Modif AC : 27/02/03
              else
                {
                  Cerr <<"On ne traite pas ce cas pour les_faces_Cl[rang1] = 1 "<<finl;
                  Cerr <<"les_faces_Cl[rang2] = "<<les_faces_Cl[rang2]<<finl;
                  exit();
                }
            }
          else if (les_faces_Cl[rang1] == 2)   //!< face symetrie
            {
              if (les_faces_Cl[rang2] == 0)  //!< face paroi
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::PAROI_SYM;
              else if (les_faces_Cl[rang2] == 1)  //!< face sortie libre ou entree de fluide
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::FLUIDE_SYM;
              else if (les_faces_Cl[rang2] == 2) //!< symetrie
                type_arete_coin_[num_arete_] = TypeAreteCoinVDF::SYM_SYM;
              else if (les_faces_Cl[rang2] == 3) //!< periodicite
                {
// On ne change rien. De toute facon, ce type d'arete ne necessite pas de traitement particulier
                  type_arete_coin_[num_arete_] = TypeAreteCoinVDF::VIDE;
                }
              else
                {
                  Cerr <<"On ne traite pas ce cas pour les_faces_Cl[rang1] = 2 "<<finl;
                  Cerr <<"les_faces_Cl[rang2] = "<<les_faces_Cl[rang2]<<finl;
                  exit();
                }
            }
        }
    }
  else
    {
      Cerr << "Zone_Cl_VDF::completer() attend en argument une Zone_VDF\n";
      exit();
    }
  Cerr << "Zone_Cl_VDF::completer OK" << finl;
}
References Cerr, Zone_VF::creer_tableau_faces_bord(), TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), finl, TypeAreteBordVDF::FLUIDE_FLUIDE, TypeAreteCoinVDF::FLUIDE_FLUIDE, TypeAreteCoinVDF::FLUIDE_PAROI, TypeAreteBordVDF::FLUIDE_SYM, TypeAreteCoinVDF::FLUIDE_SYM, Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Zone::ind_faces_virt_bord(), Process::Journal(), Zone_Cl_dis_base::les_conditions_limites_, Zone_VDF::nb_aretes_bord(), Zone_VDF::nb_aretes_coin(), Frontiere::nb_faces(), Zone_VF::nb_faces(), Zone_dis_base::nb_front_Cl(), num_Cl_face_, Frontiere::num_premiere_face(), TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteCoinVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, TypeAreteCoinVDF::PAROI_PAROI, TypeAreteBordVDF::PAROI_SYM, TypeAreteCoinVDF::PAROI_SYM, TypeAreteCoinVDF::PERIO_FLUIDE, TypeAreteCoinVDF::PERIO_PAROI, TypeAreteBordVDF::PERIO_PERIO, TypeAreteCoinVDF::PERIO_PERIO, Zone_VDF::premiere_arete_bord(), Zone_VDF::premiere_arete_coin(), Zone_VDF::Qdm(), ref_cast, TRUSTVect< _TYPE_ >::size_reelle(), sub_type, TypeAreteBordVDF::SYM_SYM, TypeAreteCoinVDF::SYM_SYM, Option_VDF::traitement_coins, type_arete_bord_, type_arete_coin_, Deriv_Zone_dis_base::valeur(), TypeAreteBordVDF::VIDE, TypeAreteCoinVDF::VIDE, and Zone_dis_base::zone().
cree_instance()
Objet_U * Zone_Cl_VDF::cree_instance () static
Definition at line 31 of file Zone_Cl_VDF.cpp.
duplique()
int Zone_Cl_VDF::duplique () const override virtual
Implements Objet_U.
Definition at line 31 of file Zone_Cl_VDF.cpp.
get_info()
const Type_info * Zone_Cl_VDF::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 31 of file Zone_Cl_VDF.cpp.
imposer_cond_lim()
void Zone_Cl_VDF::imposer_cond_lim (Champ_Inc & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du
Champ_Inc.
Implements Zone_Cl_dis_base.
Definition at line 370 of file Zone_Cl_VDF.cpp.
{
  static int init=0;
  Champ_Inc_base& ch_base=ch.valeur();
  DoubleTab& ch_tab = ch_base.valeurs(temps);
  if (sub_type(Champ_P0_VDF,ch_base))
    ;
  else if(ch_base.nature_du_champ()==scalaire)
    ;
  else if (sub_type(Champ_Face,ch_base))
    {
      Champ_Face& ch_face = ref_cast(Champ_Face, ch_base);
      const Zone_VDF& ma_zone_VDF = ch_face.zone_vdf();
      int ndeb,nfin, num_face;
      for(int i=0; i<nb_cond_lim(); i++)
        {
          const Cond_lim_base& la_cl = les_conditions_limites(i).valeur();
          if (sub_type(Periodique,la_cl))
            {
              if (init == 0)
                {
// On fait en sorte que le champ ait la meme valeur
// sur deux faces de periodicite qui sont en face l'une de l'autre
                  const Periodique& la_cl_perio = ref_cast(Periodique,la_cl);
                  const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
                  ndeb = le_bord.num_premiere_face();
                  nfin = ndeb + le_bord.nb_faces();
                  int voisine;
                  double moy;
                  for (num_face=ndeb; num_face<nfin; num_face++)
                    {
                      voisine = la_cl_perio.face_associee(num_face-ndeb) + ndeb;
                      if ( ch_tab[num_face] != ch_tab[voisine] )
{
// Cerr << "dans Zone_Cl_VDF::imposer_cond_lim : on reajuste les vitesses!! pour la face num=" << num_face << finl;
// Cerr << "difference = ch_tab[num_face]-ch_tab[voisine]=" << ch_tab[num_face]-ch_tab[voisine] << finl;
                          moy = 0.5*(ch_tab[num_face] + ch_tab[voisine]);
                          ch_tab[num_face] = moy;
                          ch_tab[voisine] = moy;
                        }
                    }
// Il ne faut pas le faire a la premiere cl mais une fois toutes les cl faites une fois, cas multi perio avec ci non perio
// init = 1;
                }
            }
          else if( sub_type(Symetrie,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                ch_tab[num_face] = 0;
            }
          else if ( sub_type(Dirichlet_entree_fluide,la_cl) )
            {
              const Dirichlet_entree_fluide& la_cl_diri = ref_cast(Dirichlet_entree_fluide,la_cl);
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                {
// WEC : optimisable (pour chaque face recherche le bon temps !)
                  ch_tab[num_face] = la_cl_diri.val_imp_au_temps(temps,num_face-ndeb,ma_zone_VDF.orientation(num_face));
                }
            }
          else if ( sub_type(Dirichlet_paroi_fixe,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                ch_tab[num_face] = 0;
            }
          else if ( sub_type(Dirichlet_paroi_defilante,la_cl) )
            {
              const Front_VF& le_bord = ref_cast(Front_VF,la_cl.frontiere_dis());
              ndeb = le_bord.num_premiere_face();
              nfin = ndeb + le_bord.nb_faces();
              for (num_face=ndeb; num_face<nfin; num_face++)
                ch_tab[num_face] = 0;
            }
        }
      init = 1;
    }
  else
    {
      Cerr << "Le type de Champ_Inc " <<  ch->que_suis_je() << " n'est pas prevu en VDF\n";
      exit();
    }
  ch_tab.echange_espace_virtuel();
  Debog::verifier("Zone_Cl_VDF::imposer_cond_lim ch_tab",ch_tab);
}
References Cerr, TRUSTVect< _TYPE_ >::echange_espace_virtuel(), Process::exit(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Zone_Cl_dis_base::les_conditions_limites(), Field_base::nature_du_champ(), Zone_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Zone_VDF::orientation(), Objet_U::que_suis_je(), ref_cast, scalaire, sub_type, Dirichlet::val_imp_au_temps(), Deriv_Champ_Inc_base::valeur(), Champ_Inc_base::valeurs(), Debog::verifier(), and Champ_Face::zone_vdf().
info()
const Type_info * Zone_Cl_VDF::info () static
Definition at line 31 of file Zone_Cl_VDF.cpp.
la_cl_de_la_face()
const Cond_lim & Zone_Cl_VDF::la_cl_de_la_face (int num_face) const inline override virtual
A partir d'un indice de face de bord dans la Zone_VF,
renvoie la condition aux limites a laquelle cette face
appartient, pour 0 <= num_face < nb_faces_Cl().
Reimplemented from Zone_Cl_dis_base.
Definition at line 139 of file Zone_Cl_VDF.h.
{
  return les_conditions_limites_[num_Cl_face_[numfa]];
}
References Zone_Cl_dis_base::les_conditions_limites_, and num_Cl_face_.
nb_faces_bord()
int Zone_Cl_VDF::nb_faces_bord () const
Definition at line 490 of file Zone_Cl_VDF.cpp.
{
  return zone_VDF().nb_faces_bord();
}
References Zone_VF::nb_faces_bord(), and zone_VDF().
nb_faces_sortie_libre()
int Zone_Cl_VDF::nb_faces_sortie_libre () const
Definition at line 466 of file Zone_Cl_VDF.cpp.
{
  int compteur=0;
  for(int cl=0; cl<les_conditions_limites_.size(); cl++)
    {
      if(sub_type(Sortie_libre_pression_imposee, les_conditions_limites_[cl].valeur()))
        {
          const Front_VF& le_bord=ref_cast(Front_VF,les_conditions_limites_[cl]->frontiere_dis());
          compteur+=le_bord.nb_faces();
        }
    }
  return compteur;
}
References compteur, Zone_Cl_dis_base::les_conditions_limites_, Front_VF::nb_faces(), ref_cast, vect_impl::size(), sub_type, and valeur().
num_Cl_face()
int Zone_Cl_VDF::num_Cl_face (int numfa) const inline
Definition at line 134 of file Zone_Cl_VDF.h.
{
  return num_Cl_face_[numfa];
}
References num_Cl_face_.
printOn()
Sortie & Zone_Cl_VDF::printOn (Sortie & os) const override protected virtual
Surcharge Objet_U::printOn(Sortie&)
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime les conditions aux limites discretisees sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 36 of file Zone_Cl_VDF.cpp.
{
  Zone_Cl_dis_base::printOn(os) ;
  return os << "type_arete_bord_ : " << type_arete_bord_ << finl
         << "num_Cl_face_ : " << num_Cl_face_ << finl;
}
References finl, num_Cl_face_, Zone_Cl_dis_base::printOn(), and type_arete_bord_.
readOn()
Entree & Zone_Cl_VDF::readOn (Entree & is) override protected virtual
Surcharge Objet_U::readOn(Sortie&)
Lit les conditions aux limites discretisees a partir d'un flot d'entree
Le format attendu est le suivant:
{
Nom Cond_lim [REPETER LECTURE AUTANT DE FOIS QUE NECESSAIRE]
}.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Zone_Cl_dis_base.
Definition at line 46 of file Zone_Cl_VDF.cpp.
{
  return Zone_Cl_dis_base::readOn(is) ;
}
References Zone_Cl_dis_base::readOn().
self_cast() [1/2]
const Zone_Cl_VDF & Zone_Cl_VDF::self_cast (const Objet_U & r) static
Definition at line 31 of file Zone_Cl_VDF.cpp.
self_cast() [2/2]
Zone_Cl_VDF & Zone_Cl_VDF::self_cast (Objet_U & r) static
Definition at line 31 of file Zone_Cl_VDF.cpp.
taille_memoire()
unsigned Zone_Cl_VDF::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 31 of file Zone_Cl_VDF.cpp.
type_arete_bord() [1/2]
const IntVect & Zone_Cl_VDF::type_arete_bord () const inline
Definition at line 119 of file Zone_Cl_VDF.h.
{
  return type_arete_bord_;
}
References type_arete_bord_.
type_arete_bord() [2/2]
int Zone_Cl_VDF::type_arete_bord (int num_arete) const inline
Definition at line 114 of file Zone_Cl_VDF.h.
{
  return type_arete_bord_[num_arete];
}
References type_arete_bord_.
Referenced by Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), Champ_Face::calculer_dercov_axi(), and Zone_VDF::modifier_pour_Cl().
type_arete_coin() [1/2]
const IntVect & Zone_Cl_VDF::type_arete_coin () const inline
Definition at line 129 of file Zone_Cl_VDF.h.
{
  return type_arete_coin_;
}
References type_arete_coin_.
type_arete_coin() [2/2]
const int & Zone_Cl_VDF::type_arete_coin (int num_arete) const inline
Definition at line 124 of file Zone_Cl_VDF.h.
{
  return type_arete_coin_[num_arete];
}
References type_arete_coin_.
Referenced by Champ_Face::calcul_duidxj(), Champ_Face::calcul_S_barre_sans_contrib_paroi(), and Zone_VDF::modifier_pour_Cl().
zone_VDF() [1/2]
Zone_VDF & Zone_Cl_VDF::zone_VDF ()
Definition at line 480 of file Zone_Cl_VDF.cpp.
{
  return ref_cast(Zone_VDF, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Referenced by Champ_Face_get_val_imp_face_bord(), Champ_Face_get_val_imp_face_bord_sym(), and nb_faces_bord().
zone_VDF() [2/2]
const Zone_VDF & Zone_Cl_VDF::zone_VDF () const
Definition at line 485 of file Zone_Cl_VDF.cpp.
{
  return ref_cast(Zone_VDF, zone_dis().valeur());
}
References ref_cast, valeur(), and Zone_Cl_dis_base::zone_dis().
Member Data Documentation
info_obj
const Type_info Zone_Cl_VDF::info_obj static
Definition at line 76 of file Zone_Cl_VDF.h.
num_Cl_face_
IntVect Zone_Cl_VDF::num_Cl_face_ private
pour chaque face de bord numero de la condition limite a laquelle elle se rattache
Definition at line 107 of file Zone_Cl_VDF.h.
Referenced by associer(), completer(), la_cl_de_la_face(), num_Cl_face(), and printOn().
type_arete_bord_
IntVect Zone_Cl_VDF::type_arete_bord_ private
type des aretes bord: type = 0 si l'arete separe deux faces de paroi type = 1 si l'arete separe deux faces "fluide" type = 2 si l'arete separe une face de paroi et une face "fluide" type = 3 si l'arete separe deux faces de symetrie type = 5 si l'arete separe une face de symetrie et une face de paroi type = 6 si l'arete separe une face de symetrie et une face "fluide"
Definition at line 96 of file Zone_Cl_VDF.h.
Referenced by associer(), completer(), printOn(), and type_arete_bord().
type_arete_coin_
IntVect Zone_Cl_VDF::type_arete_coin_ private
type des aretes coin: type = 0 si l'arete contient deux faces de periodicite type = 1 si l'arete contient une face de periodicite et une face de paroi
Definition at line 104 of file Zone_Cl_VDF.h.
Referenced by associer(), completer(), and type_arete_coin().
The documentation for this class was generated from the following files:
src/VDF/Zones/Zone_Cl_VDF.h
src/VDF/Zones/Zone_Cl_VDF.cpp