TRUST: Eval_Source_C_VDF_Elem Class Reference
Eval_Source_C_VDF_Elem Class Reference
#include <Eval_Source_C_VDF_Elem.h>
Public Member Functions
Eval_Source_C_VDF_Elem ()
void associer_champs (const Champ_Don &)
void mettre_a_jour ()
double calculer_terme_source (int) const
void calculer_terme_source (int, DoubleVect &) const
Protected Attributes
Ref_Champ_Don la_source_constituant
DoubleTab source_constituant
Detailed Description
Definition at line 39 of file Eval_Source_C_VDF_Elem.h.
Constructor & Destructor Documentation
Eval_Source_C_VDF_Elem::Eval_Source_C_VDF_Elem () [inline]
Definition at line 61 of file Eval_Source_C_VDF_Elem.h.
{}
Member Function Documentation
void Eval_Source_C_VDF_Elem::associer_champs (const Champ_Don & Q)
Definition at line 26 of file Eval_Source_C_VDF_Elem.cpp.
References la_source_constituant, DoubleTab::ref(), source_constituant, and Champ_Don::valeurs().
Referenced by Terme_Source_Constituant_VDF_Elem::associer_pb().
{
  la_source_constituant = Q;
  source_constituant.ref(Q.valeurs());
}
void Eval_Source_C_VDF_Elem::calculer_terme_source (int num_elem, DoubleVect & source) const [inline, virtual]
Implements Evaluateur_Source_VDF.
Definition at line 69 of file Eval_Source_C_VDF_Elem.h.
References la_source_constituant, Evaluateur_Source_VDF_Elem::porosite_vol, DoubleVect::size(), source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_VDF_Elem::volumes.
{
  int size=source.size();
  if (sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()))
    for (int i=0; i<size; i++)
      source(i) = source_constituant(0,i)*volumes(num_elem)*porosite_vol(num_elem);
  else
    for (int i=0; i<size; i++)
      source(i) = source_constituant(num_elem,i)*volumes(num_elem)*porosite_vol(num_elem);
}
double Eval_Source_C_VDF_Elem::calculer_terme_source (int num_elem) const [inline, virtual]
Implements Evaluateur_Source_VDF.
Definition at line 63 of file Eval_Source_C_VDF_Elem.h.
References la_source_constituant, Evaluateur_Source_VDF_Elem::porosite_vol, source_constituant, sub_type, Deriv_Champ_Don_base::valeur(), Ref_Champ_Don::valeur(), and Evaluateur_Source_VDF_Elem::volumes.
{
  const int k = sub_type(Champ_Uniforme,la_source_constituant.valeur().valeur()) ? 0 : num_elem;
  return source_constituant(k, 0) * volumes(num_elem) * porosite_vol(num_elem);
}
void Eval_Source_C_VDF_Elem::mettre_a_jour () [virtual]
Implements Evaluateur_Source_VDF.
Definition at line 32 of file Eval_Source_C_VDF_Elem.cpp.
{
}
Member Data Documentation
Ref_Champ_Don Eval_Source_C_VDF_Elem::la_source_constituant [protected]
Definition at line 52 of file Eval_Source_C_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
DoubleTab Eval_Source_C_VDF_Elem::source_constituant [protected]
Definition at line 53 of file Eval_Source_C_VDF_Elem.h.
Referenced by associer_champs(), and calculer_terme_source().
The documentation for this class was generated from the following files:
src/VDF/Sources/Evaluateurs/Eval_Source_C_VDF_Elem.h
src/VDF/Sources/Evaluateurs/Eval_Source_C_VDF_Elem.cpp