TRUST: Perte_Charge_Reguliere_VEF_P1NC Class Reference
Perte_Charge_Reguliere_VEF_P1NC Class Reference
class Perte_Charge_Reguliere_VEF_P1NC
#include <Perte_Charge_Reguliere_VEF_P1NC.h>
Public Member Functions
Perte_Charge_Reguliere_VEF_P1NC ()
~Perte_Charge_Reguliere_VEF_P1NC ()
unsigned taille_memoire () const override
int duplique () const override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const override
DoubleTab & calculer (DoubleTab &) const override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
contribution a la matrice implicite des termes sources
par defaut pas de contribution
void remplir_num_faces (Nom &)
void completer () override
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Public Member Functions inherited from Perte_Charge_VEF_Face
Perte_Charge_VEF_Face ()
~Perte_Charge_VEF_Face () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
DoubleTab & ajouter (DoubleTab &) const override=0
DoubleTab & calculer (DoubleTab &) const override=0
void associer_pb (const Probleme_base &) override
void mettre_a_jour (double) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
Public Member Functions inherited from Source_base
Source_base ()
~Source_base () override
const Type_info * get_info () const override
Donne des informations sur le type de l'Objet_U.
virtual DoubleTab & ajouter (DoubleTab &) const
virtual DoubleTab & calculer (DoubleTab &) const
virtual void mettre_a_jour (double temps)
NE FAIT RIEN
A surcharger dans les classes derivees.
Mise a jour en temps du terme source.
virtual void completer ()
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
virtual void dimensionner (Matrice_Morse &) const
Dimensionnement de la matrice implicite des termes sources.
Par defaut ne fait rien.
virtual void dimensionner_bloc_vitesse (Matrice_Morse &) const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
contribution a la matrice implicite des termes sources
par defaut pas de contribution
virtual void contribuer_au_second_membre (DoubleTab &) const
contribution au second membres des termes sources en implicite
par defaut erreur
methode presente par coherence avec Operateur_base
virtual int impr (Sortie &os) const
void associer_zones_public (const Zone_dis &, const Zone_Cl_dis &)
virtual int initialiser (double temps)
Contrairement aux methodes mettre_a_jour, les methodes
initialiser des sources ne peuvent pas dependre de l'exterieur
(lui-meme peut ne pas etre initialise)
Par defaut, mettre_a_jour.
virtual void associer_champ_rho (const Champ_base &champ_rho)
Cette methode (ou la methode de la classe derivee) est appelee
par Sources::associer_champ_rho pour chaque source de la liste
(par exemple, a l'initialisation d'un calcul front-tracking).
Cette methode doit etre reimplementee dans les classes derivees
utilisees dans les problemes a rho variable.
La methode ajouter calcule le terme suivant:
INTEGRALE (terme source)
sur volume entrelace
Dans les problemes ou rho est variable, "terme source" homogene a rho*v.
Sinon, "terme source" est homogene a v.
virtual int a_pour_Champ_Fonc (const Motcle &mot, Ref_Champ_base &ch_ref) const
Si la source comprend le motcle "mot", elle remplit la reference a ch_ref
et renvoie 1, sinon renvoie 0 (voir Source_Translation par ex.)
virtual void contribuer_jacobienne (Matrice_Bloc &, int) const
virtual int has_interface_blocs () const
virtual void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const
virtual void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const
void creer_champ (const Motcle &motlu) override
const Champ_base & get_champ (const Motcle &nom) const override
virtual bool has_champ (const Motcle &nom, Ref_Champ_base &ref_champ) const
void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const override
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
Ouverture/creation d'un fichier d'impression d'un terme source
A surcharger dans les classes derivees.
void set_fichier (const Nom &)
void set_description (const Nom &nom)
const Nom fichier () const
const Nom description () const
DoubleVect & bilan ()
DoubleVect & bilan () const
Champs_compris & champs_compris ()
Public Member Functions inherited from Champs_compris_interface
virtual ~Champs_compris_interface ()
virtual void creer_champ (const Motcle &motlu)=0
virtual const Champ_base & get_champ (const Motcle &nom) const =0
virtual void get_noms_champs_postraitables (Noms &nom, Option opt=NONE) const =0
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Associe une equation a l'objet.
Affecte le membre MorEqn::mon_equation avec l'objet
passe en parametre.
virtual void calculer_pour_post (Champ &espace_stockage, const Nom &option, int comp) const
virtual Motcle get_localisation_pour_post (const Nom &option) const
const Equation_base & equation () const
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
(version const)
Equation_base & equation ()
Renvoie la reference sur l'equation pointe par
MorEqn::mon_equation.
int mon_equation_non_nul () const
virtual void check_multiphase_compatibility () const
Public Member Functions inherited from Objet_U
~Objet_U () override
Destructeur, supprime l'objet de la liste d'objets enregistres
dans "memoire".
int numero () const
Renvoie l'indice de l'objet dans Memoire::data.
int get_object_id () const
Renvoie l'identifiant unique de l'objet object_id_.
virtual const Type_info * get_info () const
Donne des informations sur le type de l'Objet_U.
virtual const Nom & le_nom () const
Donne le nom de l'Objet_U
Methode a surcharger : renvoie "neant" dans cette implementation.
const Nom & que_suis_je () const
renvoie la chaine identifiant la classe.
virtual void nommer (const Nom &)
Donne un nom a l'Objet_U
Methode virtuelle a surcharger.
const char * le_type () const
Donne le nom du type de l'Objet_U.
virtual int est_egal_a (const Objet_U &) const
Renvoie 1 si l'objet x et *this sont une seule et meme instance<br>(meme adresse en memoire).
virtual int duplique () const =0
virtual unsigned taille_memoire () const =0
virtual int change_num (const int *const)
Change le numero interne de l'Objet_U.
virtual Sortie & printOn (Sortie &) const
Ecriture de l'objet sur un flot de sortie
Methode a surcharger.
virtual Entree & readOn (Entree &)
Lecture d'un Objet_U sur un flot d'entree
Methode a surcharger.
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
Lecture des parametres de type non simple d'un objet_U
a partir d'un flot d'entree.
virtual int reprendre (Entree &)
Reprise d'un Objet_U sur un flot d'entree
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int sauvegarder (Sortie &) const
Sauvegarde d'un Objet_U sur un flot de sortie
Methode a surcharger : retourne toujours 1 dans cette implementation.
virtual int associer_ (Objet_U &)
Associe l'Objet_U a un autre Objet_U
Methode virtuelle a surcharger.
const Interprete & interprete () const
Interprete & interprete ()
Public Member Functions inherited from Process
Process ()
Constructeur par defaut.
virtual ~Process ()
Destructeur
Ne fait rien.
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don & source () const
Renvoie le champ donne representant le terme source.
Public Member Functions inherited from Perte_Charge_Reguliere
Perte_Charge_Reguliere (void)
double correction_direction (DoubleVect &, int) const
double calculer_Cf_blasius (double) const
Entree & lire_donnees (Entree &)
Lit les specifications d'une perte de charge reguliere
a partir d'un flot d'entree.
double D () const
double d () const
double a () const
double b () const
double CF () const
Public Member Functions inherited from Perte_Charge
int direction_perte_charge () const
Renvoie la direction de perte de charge.
(X,Y ou Z), ou -1 si toutes les directions.
Static Public Member Functions
static Objet_U * cree_instance ()
static const Type_info * info ()
static Perte_Charge_Reguliere_VEF_P1NC & self_cast (Objet_U &)
static const Perte_Charge_Reguliere_VEF_P1NC & self_cast (const Objet_U &)
Static Public Member Functions inherited from Perte_Charge_VEF_Face
static const Type_info * info ()
static Perte_Charge_VEF_Face & self_cast (Objet_U &)
static const Perte_Charge_VEF_Face & self_cast (const Objet_U &)
Static Public Member Functions inherited from Source_base
static const Type_info * info ()
static Source_base & self_cast (Objet_U &)
static const Source_base & self_cast (const Objet_U &)
Static Public Member Functions inherited from Objet_U
static const Nom & nom_du_cas ()
Renvoie une reference constante vers le nom du cas.
Cette methode est statique.
static Nom & get_set_nom_du_cas ()
Renvoie une reference non constante vers le nom du cas<br>(pour pouvoir le modifier).
Cette methode est statique.
static const Type_info * info ()
Donne des informations sur le type de l'Objet_U.
static const Objet_U & self_cast (const Objet_U &)
methode ajoutee pour caster en python
static Objet_U & self_cast (Objet_U &)
Static Public Member Functions inherited from Process
static int je_suis_maitre ()
renvoie 1 si on est sur le processeur maitre du groupe courant
(c'est a dire me() == 0), 0 sinon. Voir Comm_Group::rank()
static int nproc ()
renvoie le nombre de processeurs dans le groupe courant
Voir Comm_Group::nproc() et PE_Groups::current_group()
static void barrier ()
Synchronise tous les processeurs du groupe courant<br>(attend que tous les processeurs soient arrives a la barriere)
Instruction a executer sur tous les processeurs du groupe.
static double mp_sum (double)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static double mp_max (double)
Calcule le max de x sur tous les processeurs du groupe courant.
Remarques :
Cette methode doit etre appelee sur tous les processeurs du groupe.
La valeur renvoyee est identique sur tous les processeurs.
static double mp_min (double)
Calcule le min de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static int mp_sum (int)
Calcule la somme de x sur tous les processeurs du groupe courant.
Voir aussi mp_max()
static bool mp_and (bool)
Calcule le 'et' logique de b sur tous les processeurs du groupe courant.
static int me ()
renvoie mon rang dans le groupe de communication courant.
Voir Comm_Group::rank() et PE_Groups::current_group()
static void exit (int exit_code=-1)
Routine de sortie de Trio-U sur une erreur
Sauvegarde la memoire et le hierarchie dans les fichiers "memoire.dump" et "hierarchie.dump".
static void exit (const Nom &message, int exit_code=-1)
static void abort ()
Routine de sortie de Trio-U sur une erreur abort()
static Sortie & Journal (int message_level=0)
Renvoie un objet statique de type Sortie qui sert de journal d'evenements.
Si message_level <= verbose_level_, on ecrit le message, sinon
on l'envoie sur une Sortie_Nulle.
Si le fichier journal est ouvert, on ecrit dans le fichier, sinon dans stderr.
static double ram_processeur ()
static void imprimer_ram_totale (int all_process=0)
static bool force_single_file (const int ranks, const Nom &filename)
Static Public Attributes
static const Type_info info_obj
Static Public Attributes inherited from Perte_Charge_VEF_Face
static const Type_info info_obj
Static Public Attributes inherited from Source_base
static const Type_info info_obj
Static Public Attributes inherited from Objet_U
static int dimension =0
static double precision_geom =1e-10
static int format_precision_geom =11
static int axi =0
static int bidim_axi =0
static int DEACTIVATE_SIGINT_CATCH =0
flag to not enter the overloaded function signal_callback_handler
static Type_info info_obj
static int disable_TU =0
Flag to disable the writing of the .TU files.
Static Public Attributes inherited from Process
static int exception_sur_exit =0
static int multiple_files =5120
Valeur modifiable dans le jeu de donnees ou variable d'environnement:
Protected Member Functions
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Protected Member Functions inherited from Perte_Charge_VEF_Face
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
void associer_zones (const Zone_dis &, const Zone_Cl_dis &) override
Sortie & printOn (Sortie &x) const override
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Entree & readOn (Entree &) override
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
virtual void associer_zones (const Zone_dis &, const Zone_Cl_dis &)=0
virtual void associer_pb (const Probleme_base &)=0
Protected Member Functions inherited from MorEqn
virtual ~MorEqn ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Constructeur par defaut : attribue un numero d'identifiant unique
a l'objet (object_id_), et enregistre l'objet en "memoire"
en lui donnant un numero num_obj. L'object_id_ et tres
pratique pour debugger...
Objet_U (const Objet_U &)
Constructeur par copie. Cree un nouveau numero d'objet
(ne copie pas le numero de l'autre objet !)
const Objet_U & operator= (const Objet_U &)
Operateur= : ne fait rien (on conserve le numero et l'identifiant)
Protected Attributes
IntVect num_faces
Nom nom_sous_zone
DoubleVect corr_front_ss
Protected Attributes inherited from Perte_Charge_VEF_Face
Ref_Champ_Inc_base la_vitesse
Ref_Zone_VEF la_zone_VEF
Ref_Zone_Cl_VEF la_zone_Cl_VEF
Ref_Fluide_base le_fluide
IntVect num_faces
Protected Attributes inherited from Source_base
int col_width_ = 0
Nom out_
Nom du fichier .out pour l'impression.
Nom description_
Description du terme source.
DoubleVect bilan_
Vecteur contenant les valeurs du terme source dans le domaine.
Champs_compris champs_compris_
Protected Attributes inherited from MorEqn
Ref_Equation_base mon_equation
Protected Attributes inherited from Terme_Source_Qdm
Champ_Don la_source
Protected Attributes inherited from Perte_Charge_Reguliere
double D_
double d_
double a_
double b_
double Cf_
int couronne_tube
int Cf_utilisateur
double xo
double yo
double zo
int dir [3]
double h0
double h
Protected Attributes inherited from Perte_Charge
int direction_perte_charge_
Detailed Description
class Perte_Charge_Reguliere_VEF_P1NC
See also
Perte_Charge_VEF_P1NC
Definition at line 32 of file Perte_Charge_Reguliere_VEF_P1NC.h.
Constructor & Destructor Documentation
Perte_Charge_Reguliere_VEF_P1NC()
Perte_Charge_Reguliere_VEF_P1NC::Perte_Charge_Reguliere_VEF_P1NC ()
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
~Perte_Charge_Reguliere_VEF_P1NC()
Perte_Charge_Reguliere_VEF_P1NC::~Perte_Charge_Reguliere_VEF_P1NC ()
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
Member Function Documentation
ajouter()
DoubleTab & Perte_Charge_Reguliere_VEF_P1NC::ajouter (DoubleTab & resu) const override virtual
Implements Perte_Charge_VEF_Face.
Definition at line 121 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
// Cerr << " Perte_Charge_Reguliere_VEF_P1NC::ajouter " << finl;
  const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,equation().zone_dis().valeur());
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  double U_abs;
  double Cf,CK,Reynolds;
  int numfa,n0,n1;
  const Champ_Don& nu = le_fluide->viscosite_cinematique();
  const DoubleTab& visco = nu.valeurs();
  double d_visco=-1;
  int l_visco_unif=0;
  if (sub_type(Champ_Uniforme,nu.valeur()))
    {
      const Champ_Uniforme& ch_nu = ref_cast(Champ_Uniforme,nu.valeur());
      d_visco = ch_nu(0,0);
      l_visco_unif = 1;
    }
  if (couronne_tube == 1)
    {
      Cerr << " PQ : 17/06/08 : Cette option a ete supprimee dans Perte_Charge_Reguliere_VEF_P1NC" << finl;
      Cerr << " Possibilite de retrouver la meme fonctionnalite a l'aide du mot cle : " << finl;
      Cerr << "  Perte_charge_anisotrope (voir doc) " << finl;
      exit();
    }
  int premiere_face_int=zone_VEF.premiere_face_int();
  int direction = direction_perte_charge();
  int nb_faces = num_faces.size();
  for (int i=0; i<nb_faces; i++)
    {
      numfa = num_faces[i];
      if (!l_visco_unif)
        {
          n0 = face_voisins(numfa,0);
          n1 = face_voisins(numfa,1);
          if (numfa < premiere_face_int)
            {
              if (n0 != -1)
                d_visco = visco[n0];
              else
                d_visco = visco[n1];
            }
          else
            d_visco = 0.5*(visco[n0]+visco[n1]);
        }
// GF La vitesse pour caluler le Rey ne depend pas de la porosite
// et on utilise la norme
      U_abs=0;
      for (int j =0; j<dimension; j++ )
        U_abs += vit(numfa,j)*vit(numfa,j);
      U_abs = sqrt(U_abs) ;
      Reynolds = U_abs*D()/d_visco;
      if (!Cf_utilisateur)
        Cf = calculer_Cf_blasius(Reynolds);
      else
        Cf = CF();
      CK = -0.5*Cf/D();
      resu(numfa,direction) += CK*U_abs*vit(numfa,direction)*volumes_entrelaces(numfa)*porosite_face(numfa)*corr_front_ss(i);
    }
  return resu;
}
References Perte_Charge_Reguliere::calculer_Cf_blasius(), Cerr, Perte_Charge_Reguliere::CF(), Perte_Charge_Reguliere::Cf_utilisateur, corr_front_ss, Perte_Charge_Reguliere::couronne_tube, Perte_Charge_Reguliere::D(), Objet_U::dimension, Perte_Charge::direction_perte_charge(), MorEqn::equation(), Process::exit(), Zone_VF::face_voisins(), finl, Perte_Charge_VEF_Face::la_vitesse, Perte_Charge_VEF_Face::le_fluide, num_faces, Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), valeur(), Champ_Don::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Zone_VF::volumes_entrelaces().
Referenced by Perte_Charge_Reguliere_QC_VEF_P1NC::ajouter_mere(), and calculer().
calculer()
DoubleTab & Perte_Charge_Reguliere_VEF_P1NC::calculer (DoubleTab & resu) const override virtual
Implements Perte_Charge_VEF_Face.
Definition at line 285 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
  resu = 0;
  return ajouter(resu);
}
References ajouter().
completer()
void Perte_Charge_Reguliere_VEF_P1NC::completer (void) override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees:
Source_base::associer_zones(const Zone_dis& ,const Zone_Cl_dis&)
Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
Definition at line 292 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
  Source_base::completer();
  remplir_num_faces(nom_sous_zone);
}
References Source_base::completer(), nom_sous_zone, and remplir_num_faces().
contribuer_a_avec()
void Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources
par defaut pas de contribution
Reimplemented from Source_base.
Definition at line 202 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
// Cerr << " Perte_Charge_Reguliere_VEF_P1NC::ajouter " << finl;
  const Zone_VEF& zone_VEF = ref_cast(Zone_VEF,equation().zone_dis().valeur());
  const DoubleVect& volumes_entrelaces = zone_VEF.volumes_entrelaces();
  const DoubleVect& porosite_face = zone_VEF.porosite_face();
  const DoubleTab& vit = la_vitesse->valeurs();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  double U_abs;
  double Cf,CK,Reynolds;
  int numfa,n0,n1;
  const Champ_Don& nu = le_fluide->viscosite_cinematique();
  const DoubleTab& visco = nu.valeurs();
  double d_visco=-1;
  int l_visco_unif=0;
  if (sub_type(Champ_Uniforme,nu.valeur()))
    {
      const Champ_Uniforme& ch_nu = ref_cast(Champ_Uniforme,nu.valeur());
      d_visco = ch_nu(0,0);
      l_visco_unif = 1;
    }
  if (couronne_tube == 1)
    {
      Cerr << " PQ : 17/06/08 : Cette option a ete supprimee dans Perte_Charge_Reguliere_VEF_P1NC" << finl;
      Cerr << " Possibilite de retrouver la meme fonctionnalite a l'aide du mot cle : " << finl;
      Cerr << "  Perte_charge_anisotrope (voir doc) " << finl;
      exit();
    }
  int premiere_face_int=zone_VEF.premiere_face_int();
  int direction = direction_perte_charge();
  int nb_faces = num_faces.size();
  for (int i=0; i<nb_faces; i++)
    {
      numfa = num_faces[i];
      if (!l_visco_unif)
        {
          n0 = face_voisins(numfa,0);
          n1 = face_voisins(numfa,1);
          if (numfa < premiere_face_int)
            {
              if (n0 != -1)
                d_visco = visco[n0];
              else
                d_visco = visco[n1];
            }
          else
            d_visco = 0.5*(visco[n0]+visco[n1]);
        }
// GF La vitesse pour caluler le Rey ne depend pas de la porosite
// et on utilise la norme
      U_abs=0;
      for (int j =0; j<dimension; j++ )
        U_abs += vit(numfa,j)*vit(numfa,j);
      U_abs = sqrt(U_abs) ;
      Reynolds = U_abs*D()/d_visco;
      if (!Cf_utilisateur)
        Cf = calculer_Cf_blasius(Reynolds);
      else
        Cf = CF();
      CK = -0.5*Cf/D();
// resu(numfa,dir) += CK*U_abs*vit(numfa,dir)*volumes_entrelaces(numfa)*porosite_face(numfa)*corr_front_ss(i);
      int n0bis=numfa*dimension+direction;
      matrice.coef(n0bis,n0bis)-=CK*U_abs*volumes_entrelaces(numfa)*porosite_face(numfa)*corr_front_ss(i);
    }
}
References Perte_Charge_Reguliere::calculer_Cf_blasius(), Cerr, Perte_Charge_Reguliere::CF(), Perte_Charge_Reguliere::Cf_utilisateur, Matrice_Morse::coef(), corr_front_ss, Perte_Charge_Reguliere::couronne_tube, Perte_Charge_Reguliere::D(), Objet_U::dimension, Perte_Charge::direction_perte_charge(), MorEqn::equation(), Process::exit(), Zone_VF::face_voisins(), finl, Perte_Charge_VEF_Face::la_vitesse, Perte_Charge_VEF_Face::le_fluide, num_faces, Zone_VF::porosite_face(), Zone_VF::premiere_face_int(), ref_cast, TRUSTVect< _TYPE_ >::size(), sub_type, Deriv_Champ_Don_base::valeur(), valeur(), Champ_Don::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), and Zone_VF::volumes_entrelaces().
cree_instance()
Objet_U * Perte_Charge_Reguliere_VEF_P1NC::cree_instance () static
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
duplique()
int Perte_Charge_Reguliere_VEF_P1NC::duplique () const override virtual
Implements Objet_U.
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
get_info()
const Type_info * Perte_Charge_Reguliere_VEF_P1NC::get_info () const override virtual
Donne des informations sur le type de l'Objet_U.
Returns
const Type_info*
Signification: structure regroupant les informations sur le type de l'Objet_U
Contraintes:
Reimplemented from Source_base.
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
info()
const Type_info * Perte_Charge_Reguliere_VEF_P1NC::info () static
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
printOn()
Sortie & Perte_Charge_Reguliere_VEF_P1NC::printOn (Sortie & os) const override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Imprime la source sur un flot de sortie.
Returns
Sortie&
Signification: le flot de sortie modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 32 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
  return s << que_suis_je() ;
}
References Objet_U::que_suis_je().
Referenced by Perte_Charge_Reguliere_QC_VEF_P1NC::printOn().
readOn()
Entree & Perte_Charge_Reguliere_VEF_P1NC::readOn (Entree & is) override protected virtual
NE FAIT RIEN
A surcharger dans les classes derivees.
Lecture d'un terme source sur un flot d'entree.
Returns
Entree&
Signification: le flot d'entree modifie
Contraintes:
Reimplemented from Source_base.
Definition at line 41 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
  Cerr << " Perte_Charge_Reguliere_VEF_P1NC::readOn " << finl  ;
  Perte_Charge_Reguliere::lire_donnees(s);
// Nom nom_sous_zone;
  s >> nom_sous_zone;
  return s ;
}
References Cerr, finl, Perte_Charge_Reguliere::lire_donnees(), and nom_sous_zone.
Referenced by Perte_Charge_Reguliere_QC_VEF_P1NC::readOn().
remplir_num_faces()
void Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces (Nom & un_nom_sous_zone)
< le poly voisin n'est pas dans la sous_zone
Definition at line 60 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
{
  Cerr << " Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces " << finl;
  const Domaine& le_domaine = equation().probleme().domaine();
  const Zone_VEF& zone_VEF = la_zone_VEF.valeur();
  const IntTab& elem_faces = zone_VEF.elem_faces();
  const IntTab& face_voisins = zone_VEF.face_voisins();
  const DoubleVect& volumes = zone_VEF.volumes();
  const Sous_Zone& la_sous_zone = le_domaine.ss_zone(un_nom_sous_zone);
  int nb_poly_ss_zone = la_sous_zone.nb_elem_tot();
  int nfe=zone_VEF.zone().nb_faces_elem();
  int nfac;
  int num_poly;
  num_faces.resize(nb_poly_ss_zone*4);
  corr_front_ss.resize(nb_poly_ss_zone*4);
  corr_front_ss = 1. ;
  nfac = 0;
  IntVect num_loc(zone_VEF.nb_elem_tot());
  IntVect fait(zone_VEF.nb_faces_tot());
  fait = -1;
  num_loc = -1;
  int num_poly_vois;
  int num_elem,num_face, face_loc;
  for (num_elem=0; num_elem<nb_poly_ss_zone; num_elem++)
    {
      num_loc[la_sous_zone(num_elem)] = num_elem;
    }
  for (num_elem=0; num_elem<nb_poly_ss_zone; num_elem++)
    {
      num_poly = la_sous_zone(num_elem);
      for  (face_loc = 0; face_loc < nfe ; face_loc++)
        {
          num_face =  elem_faces(num_poly,face_loc);
          if (fait(num_face) ==-1)
            {
              fait(num_face) = 1 ;
              num_faces[nfac++] = num_face;
              for (int i=0; i<2; i++ )
                {
                  num_poly_vois = face_voisins(num_face,i);
                  if (num_poly_vois != -1)
                    if (num_loc[num_poly_vois] == -1)  //!< le poly voisin n'est pas dans la sous_zone
                      {
                        corr_front_ss[nfac-1] = volumes(num_poly)/(volumes(num_poly)+volumes(num_poly_vois)) ;
                      }
                }
            }
        }
    }
  num_faces.resize(nfac);
  corr_front_ss.resize(nfac);
}
References Cerr, corr_front_ss, Probleme_base::domaine(), Zone_VF::elem_faces(), MorEqn::equation(), Zone_VF::face_voisins(), finl, Perte_Charge_VEF_Face::la_zone_VEF, Zone_dis_base::nb_elem_tot(), Sous_Zone::nb_elem_tot(), Zone::nb_faces_elem(), Zone_VF::nb_faces_tot(), num_faces, Equation_base::probleme(), TRUSTVect< _TYPE_ >::resize(), Domaine::ss_zone(), Ref_Zone_VEF::valeur(), Zone_VF::volumes(), and Zone_dis_base::zone().
Referenced by completer().
self_cast() [1/2]
const Perte_Charge_Reguliere_VEF_P1NC & Perte_Charge_Reguliere_VEF_P1NC::self_cast (const Objet_U & r) static
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
self_cast() [2/2]
Perte_Charge_Reguliere_VEF_P1NC & Perte_Charge_Reguliere_VEF_P1NC::self_cast (Objet_U & r) static
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
taille_memoire()
unsigned Perte_Charge_Reguliere_VEF_P1NC::taille_memoire () const override virtual
Implements Objet_U.
Definition at line 25 of file Perte_Charge_Reguliere_VEF_P1NC.cpp.
Member Data Documentation
corr_front_ss
DoubleVect Perte_Charge_Reguliere_VEF_P1NC::corr_front_ss protected
Definition at line 50 of file Perte_Charge_Reguliere_VEF_P1NC.h.
Referenced by ajouter(), contribuer_a_avec(), and remplir_num_faces().
info_obj
const Type_info Perte_Charge_Reguliere_VEF_P1NC::info_obj static
Definition at line 37 of file Perte_Charge_Reguliere_VEF_P1NC.h.
nom_sous_zone
Nom Perte_Charge_Reguliere_VEF_P1NC::nom_sous_zone protected
Definition at line 49 of file Perte_Charge_Reguliere_VEF_P1NC.h.
Referenced by completer(), and readOn().
num_faces
IntVect Perte_Charge_Reguliere_VEF_P1NC::num_faces protected
Definition at line 48 of file Perte_Charge_Reguliere_VEF_P1NC.h.
Referenced by ajouter(), contribuer_a_avec(), and remplir_num_faces().
The documentation for this class was generated from the following files:
src/VEF/Sources/Perte_Charge_Reguliere_VEF_P1NC.h
src/VEF/Sources/Perte_Charge_Reguliere_VEF_P1NC.cpp